ns-3: src/wifi/test/80211b.c File Reference
80211b.c File Reference
#include <gsl/gsl_math.h>
#include <gsl/gsl_integration.h>
#include <gsl/gsl_cdf.h>
#include <gsl/gsl_sf_bessel.h>
Classes
struct fn_parameters
fn_parameter_t structure
Macros
#define max(a, b) ((a) > (b) ? (a) : (b))
#define min(a, b) ((a) < (b) ? (a) : (b))
#define WLAN_SIR_impossible 0.1
#define WLAN_SIR_perfect 10.0
Functions
double DbToNoneDb (double x)
double DQPSKFunction (double x)
double f (double x, void *params)
double Get80211bDsssDbpskBer (double sinr)
double Get80211bDsssDbpskBerIeee (double EcNc)
double Get80211bDsssDqpskBer (double sinr)
double Get80211bDsssDqpskBerIeee (double EcNc)
double Get80211bDsssDqpskCCK11BerIeee (double EcNc)
double Get80211bDsssDqpskCCK5_5BerIeee (double EcNc)
double NoneDbToDb (double x)
double p_e1 (double e1)
double p_e2 (double e2)
double QFunction (double x)
Macro Definition Documentation
max
#define max (a, b) ((a) > (b) ? (a) : (b))
Definition at line 44 of file 80211b.c.
min
#define min (a, b) ((a) < (b) ? (a) : (b))
Definition at line 43 of file 80211b.c.
WLAN_SIR_impossible
#define WLAN_SIR_impossible 0.1
Definition at line 46 of file 80211b.c.
WLAN_SIR_perfect
#define WLAN_SIR_perfect 10.0
Definition at line 45 of file 80211b.c.
Function Documentation
DbToNoneDb()
double DbToNoneDb (double x)
Definition at line 103 of file 80211b.c.
References sample-rng-plot::x.
DQPSKFunction()
double DQPSKFunction (double x)
Definition at line 113 of file 80211b.c.
References sample-rng-plot::x.
Referenced by Get80211bDsssDqpskBer().
f()
double f (double x, void * params)
Definition at line 70 of file 80211b.c.
References sample-rng-plot::n, aloha::params, and sample-rng-plot::x.
Referenced by LteEarfcnTestCase::LteEarfcnTestCase(), SpectrumConverterTestSuite::SpectrumConverterTestSuite(), SpectrumValueTestSuite::SpectrumValueTestSuite(), ns3::static_SpectrumModel300Khz300GhzLog_initializer::static_SpectrumModel300Khz300GhzLog_initializer(), ns3::WifiSpectrumModelId::WifiSpectrumModelId(), ns3::EpcTft::Add(), ns3::FriisSpectrumPropagationLossModel::CalculateLoss(), ns3::QueueDisc::Classify(), ComputeSnr(), ns3::WifiPhy::ConfigureChannelForStandard(), ns3::PendingData::CopyFromSeq(), ns3::WifiPhy::DefineChannelNumber(), LteEarfcnTestCase::DoRun(), LteEarfcnDlTestCase::DoRun(), LteEarfcnUlTestCase::DoRun(), WriteModeCreateTestCase::DoRun(), ReadModeCreateTestCase::DoRun(), FileHeaderTestCase::DoRun(), RecordHeaderTestCase::DoRun(), ReadFileTestCase::DoRun(), DiffTestCase::DoRun(), ns3::WifiPhy::FindChannelNumberForFrequencyWidth(), ns3::WifiPhy::GetFrequencyWidthForChannelNumberStandard(), ns3::RandomRoomPositionAllocator::GetNext(), ns3::WifiSpectrumValueHelper::GetSpectrumModel(), ns3::LteSpectrumValueHelper::GetSpectrumModel(), ns3::MakeEvent(), ns3::operator<<(), p_e2(), PhyStateTrace(), RemainingEnergyTrace(), ns3::Simulator::Schedule(), ns3::Simulator::ScheduleDestroy(), ns3::Simulator::ScheduleNow(), ns3::Simulator::ScheduleWithContext(), ns3::aodv::RrepHeader::SetAckRequired(), ns3::aodv::RoutingProtocol::SetBroadcastEnable(), ns3::WifiPhy::SetChannelNumber(), ns3::aodv::RreqHeader::SetDestinationOnly(), ns3::aodv::RoutingProtocol::SetDestinationOnlyFlag(), ns3::dsdv::RoutingProtocol::SetEnableBufferFlag(), ns3::dsdv::RoutingProtocol::SetEnableRAFlag(), ns3::Icmpv6RA::SetFlags(), ns3::dsr::DsrPassiveBuffEntry::SetFragmentOffset(), ns3::ThreeGppPropagationLossModel::SetFrequency(), ns3::ThreeGppChannelModel::SetFrequency(), ns3::aodv::RoutingProtocol::SetGratuitousReplyFlag(), ns3::aodv::RreqHeader::SetGratuitousRrep(), ns3::aodv::RoutingProtocol::SetHelloEnable(), ns3::aodv::RerrHeader::SetNoDelete(), ns3::AnimationInterface::SetOutputFile(), ns3::SpectrumAnalyzer::SetRxSpectrumModel(), ns3::WifiHelper::SetSelectQueueCallback(), ns3::aodv::RreqHeader::SetUnknownSeqno(), ns3::dsdv::RoutingProtocol::SetWSTFlag(), ns3::AnimationInterface::WriteN(), and ns3::AnimationInterface::WriteXmlAnim().
Get80211bDsssDbpskBer()
double Get80211bDsssDbpskBer (double sinr)
Definition at line 137 of file 80211b.c.
Get80211bDsssDbpskBerIeee()
double Get80211bDsssDbpskBerIeee (double EcNc)
Definition at line 119 of file 80211b.c.
References min, QFunction(), WLAN_SIR_impossible, and WLAN_SIR_perfect.
Get80211bDsssDqpskBer()
double Get80211bDsssDqpskBer (double sinr)
Definition at line 162 of file 80211b.c.
References DQPSKFunction().
Get80211bDsssDqpskBerIeee()
double Get80211bDsssDqpskBerIeee (double EcNc)
Definition at line 144 of file 80211b.c.
References min, QFunction(), WLAN_SIR_impossible, and WLAN_SIR_perfect.
Get80211bDsssDqpskCCK11BerIeee()
double Get80211bDsssDqpskCCK11BerIeee (double EcNc)
Definition at line 190 of file 80211b.c.
References min, QFunction(), WLAN_SIR_impossible, and WLAN_SIR_perfect.
Get80211bDsssDqpskCCK5_5BerIeee()
double Get80211bDsssDqpskCCK5_5BerIeee (double EcNc)
Definition at line 170 of file 80211b.c.
References min, QFunction(), WLAN_SIR_impossible, and WLAN_SIR_perfect.
NoneDbToDb()
double NoneDbToDb (double x)
Definition at line 108 of file 80211b.c.
References sample-rng-plot::x.
p_e1()
double p_e1 (double e1)
Definition at line 98 of file 80211b.c.
References p_e2().
p_e2()
double p_e2 (double e2)
Definition at line 78 of file 80211b.c.
References f(), and aloha::params.
Referenced by p_e1().
QFunction()
double QFunction (double x)
Definition at line 65 of file 80211b.c.
References sample-rng-plot::x.
Referenced by Get80211bDsssDbpskBerIeee(), Get80211bDsssDqpskBerIeee(), Get80211bDsssDqpskCCK11BerIeee(), and Get80211bDsssDqpskCCK5_5BerIeee().