ns-3: utils/bench-packets.cc File Reference
bench-packets.cc File Reference
#include "ns3/command-line.h"
#include "ns3/system-wall-clock-ms.h"
#include "ns3/packet.h"
#include "ns3/packet-metadata.h"
#include <iostream>
#include <sstream>
#include <string>
#include <stdlib.h>
#include <limits>
#include <algorithm>
Classes
class BenchHeader< N >
BenchHeader class used for benchmarking packet serialization/deserialization.
class BenchTag< N >
BenchTag class used for benchmarking packet serialization/deserialization.
Functions
static void benchA (uint32_t n)
static void benchB (uint32_t n)
static void benchByteTags (uint32_t n)
static void benchC (uint32_t n)
static void benchD (uint32_t n)
static void benchFragment (uint32_t n)
static void C1 (Ptr< Packet > p)
static void C2 (Ptr< Packet > p)
static void runBench (void(*bench)(uint32_t), uint32_t n, uint32_t minIterations, char const *name)
static uint64_t runBenchOneIteration (void(*bench)(uint32_t), uint32_t n)
Function Documentation
benchA()
static void benchA (uint32_t n) static
Definition at line 223 of file bench-packets.cc.
References ns3::Packet::AddHeader(), ns3::Packet::Copy(), BenchHeader< N >::IsOk(), sample-rng-plot::n, NS_ASSERT_MSG(), and ns3::Packet::RemoveHeader().
benchB()
static void benchB (uint32_t n) static
Definition at line 243 of file bench-packets.cc.
References ns3::Packet::AddHeader(), and sample-rng-plot::n.
benchByteTags()
static void benchByteTags (uint32_t n) static
Definition at line 314 of file bench-packets.cc.
References ns3::Packet::AddAtEnd(), ns3::Packet::AddByteTag(), and sample-rng-plot::n.
benchC()
static void benchC (uint32_t n) static
Definition at line 272 of file bench-packets.cc.
References ns3::Packet::AddHeader(), C1(), and sample-rng-plot::n.
benchD()
static void benchD (uint32_t n) static
Definition at line 199 of file bench-packets.cc.
References ns3::Packet::AddHeader(), ns3::Packet::AddPacketTag(), ns3::Packet::Copy(), sample-rng-plot::n, ns3::Packet::RemoveHeader(), and ns3::Packet::RemovePacketTag().
benchFragment()
static void benchFragment (uint32_t n) static
Definition at line 286 of file bench-packets.cc.
References ns3::Packet::AddAtEnd(), ns3::Packet::AddHeader(), ns3::Packet::CreateFragment(), sample-rng-plot::n, and ns3::Packet::RemoveHeader().
C1()
static void C1 (Ptr< Packet > p) static
Definition at line 264 of file bench-packets.cc.
References C2(), and ns3::Packet::RemoveHeader().
Referenced by benchC().
C2()
static void C2 (Ptr< Packet > p) static
Definition at line 256 of file bench-packets.cc.
References ns3::Packet::RemoveHeader().
Referenced by C1().
runBench()
static void runBench (void(*)(uint32_t) bench, uint32_t n, uint32_t minIterations, char const * name) static
Definition at line 343 of file bench-packets.cc.
References max, min, sample-rng-plot::n, and runBenchOneIteration().
runBenchOneIteration()
static uint64_t runBenchOneIteration (void(*)(uint32_t) bench, uint32_t n) static
Definition at line 332 of file bench-packets.cc.
References ns3::SystemWallClockMs::End(), sample-rng-plot::n, and ns3::SystemWallClockMs::Start().
Referenced by runBench().