ns-3: src/mobility/examples/bonnmotion-ns2-example.cc File Reference
bonnmotion-ns2-example.cc File Reference
#include "ns3/core-module.h"
#include "ns3/mobility-module.h"
Functions
void showPosition (Ptr< Node > node, double deltaTime)
Function Documentation
showPosition()
void showPosition (Ptr< Node > node, double deltaTime)
Definition at line 48 of file bonnmotion-ns2-example.cc.
References ns3::Node::GetId(), ns3::Object::GetObject(), ns3::MobilityModel::GetPosition(), ns3::Time::GetSeconds(), ns3::MobilityModel::GetVelocity(), ns3::Simulator::Now(), ns3::Simulator::Schedule(), ns3::Seconds(), ns3::Vector3D::x, ns3::Vector3D::y, and ns3::Vector3D::z.