ns-3: src/core/model/cairo-wideint.c File Reference
cairo-wideint.c File Reference
Core » High Precision Q64.64
#include <climits>
#include "cairo-wideint-private.h"
Macros
#define _cairo_msbset64(q) (q & ((uint64_t) 1 << 63))
#define _cairo_uint32s_to_uint64(h, l) ((uint64_t) (h) << 32 | (l))
#define uint64_carry32 (((uint64_t) 1) << 32)
#define uint64_hi(i) ((i) >> 32)
#define uint64_hi32(i) ((i) >> 32)
#define uint64_lo(i) ((i) & 0xffffffff)
#define uint64_lo32(i) ((i) & 0xffffffff)
#define uint64_shift32(i) ((i) << 32)
Functions
cairo_quorem128_t _cairo_int128_divrem (cairo_int128_t num, cairo_int128_t den)
int _cairo_int128_lt (cairo_int128_t a, cairo_int128_t b)
cairo_int128_t _cairo_int32_to_int128 (int32_t i)
cairo_quorem64_t _cairo_int64_divrem (cairo_int64_t num, cairo_int64_t den)
cairo_int128_t _cairo_int64_to_int128 (cairo_int64_t i)
cairo_int128_t _cairo_int64x64_128_mul (cairo_int64_t a, cairo_int64_t b)
cairo_quorem64_t _cairo_int_96by64_32x64_divrem (cairo_int128_t num, cairo_int64_t den)
cairo_uint128_t _cairo_uint128_add (cairo_uint128_t a, cairo_uint128_t b)
cairo_uquorem128_t _cairo_uint128_divrem (cairo_uint128_t num, cairo_uint128_t den)
int _cairo_uint128_eq (cairo_uint128_t a, cairo_uint128_t b)
cairo_uint128_t _cairo_uint128_lsl (cairo_uint128_t a, int shift)
int _cairo_uint128_lt (cairo_uint128_t a, cairo_uint128_t b)
cairo_uint128_t _cairo_uint128_mul (cairo_uint128_t a, cairo_uint128_t b)
cairo_uint128_t _cairo_uint128_negate (cairo_uint128_t a)
cairo_uint128_t _cairo_uint128_not (cairo_uint128_t a)
cairo_uint128_t _cairo_uint128_rsa (cairo_int128_t a, int shift)
cairo_uint128_t _cairo_uint128_rsl (cairo_uint128_t a, int shift)
cairo_uint128_t _cairo_uint128_sub (cairo_uint128_t a, cairo_uint128_t b)
cairo_uint128_t _cairo_uint32_to_uint128 (uint32_t i)
cairo_uquorem64_t _cairo_uint64_divrem (cairo_uint64_t num, cairo_uint64_t den)
cairo_uint128_t _cairo_uint64_to_uint128 (cairo_uint64_t i)
cairo_uint128_t _cairo_uint64x64_128_mul (cairo_uint64_t a, cairo_uint64_t b)
cairo_uquorem64_t _cairo_uint_96by64_32x64_divrem (cairo_uint128_t num, cairo_uint64_t den)
_cairo_uint_96by64_32x64_divrem:
Variables
const char * cairo_impl128 = "cairo_uint64_t"
const char * cairo_impl64 = "uint64_t"
Detailed Description
Implementation of the cairo_x functions which implement high precision arithmetic.
Definition in file cairo-wideint.c.
Macro Definition Documentation
_cairo_msbset64
#define _cairo_msbset64 (q) (q & ((uint64_t) 1 << 63))
Definition at line 596 of file cairo-wideint.c.
_cairo_uint32s_to_uint64
#define _cairo_uint32s_to_uint64 (h, l) ((uint64_t) (h) << 32 | (l))
Definition at line 50 of file cairo-wideint.c.
uint64_carry32
#define uint64_carry32 (((uint64_t) 1) << 32)
Definition at line 419 of file cairo-wideint.c.
uint64_hi
#define uint64_hi (i) ((i) >> 32)
Definition at line 417 of file cairo-wideint.c.
uint64_hi32
#define uint64_hi32 (i) ((i) >> 32)
Definition at line 415 of file cairo-wideint.c.
uint64_lo
#define uint64_lo (i) ((i) & 0xffffffff)
Definition at line 416 of file cairo-wideint.c.
uint64_lo32
#define uint64_lo32 (i) ((i) & 0xffffffff)
Definition at line 414 of file cairo-wideint.c.
uint64_shift32
#define uint64_shift32 (i) ((i) << 32)
Definition at line 418 of file cairo-wideint.c.
Function Documentation
_cairo_int128_divrem()
cairo_quorem128_t _cairo_int128_divrem (cairo_int128_t num, cairo_int128_t den)
Definition at line 652 of file cairo-wideint.c.
References _cairo_int128_negate, _cairo_int128_negative, _cairo_uint128_divrem(), cairo_uquorem128_t::quo, cairo_quorem128_t::quo, cairo_uquorem128_t::rem, and cairo_quorem128_t::rem.
_cairo_int128_lt()
int _cairo_int128_lt (cairo_int128_t a, cairo_int128_t b)
Definition at line 578 of file cairo-wideint.c.
References _cairo_int128_negative, and _cairo_uint128_lt().
_cairo_int32_to_int128()
cairo_int128_t _cairo_int32_to_int128 (int32_t i)
Definition at line 358 of file cairo-wideint.c.
References _cairo_int32_to_int64, cairo_int128_t::hi, and cairo_int128_t::lo.
_cairo_int64_divrem()
cairo_quorem64_t _cairo_int64_divrem (cairo_int64_t num, cairo_int64_t den)
Definition at line 306 of file cairo-wideint.c.
References _cairo_int64_negate, _cairo_int64_negative, _cairo_uint64_divrem(), cairo_uquorem64_t::quo, cairo_quorem64_t::quo, cairo_uquorem64_t::rem, and cairo_quorem64_t::rem.
_cairo_int64_to_int128()
cairo_int128_t _cairo_int64_to_int128 (cairo_int64_t i)
Definition at line 378 of file cairo-wideint.c.
References _cairo_int32_to_int64, _cairo_int64_negative, cairo_int128_t::hi, and cairo_int128_t::lo.
_cairo_int64x64_128_mul()
cairo_int128_t _cairo_int64x64_128_mul (cairo_int64_t a, cairo_int64_t b)
Definition at line 488 of file cairo-wideint.c.
References _cairo_int64_negative, _cairo_int64_to_uint64, _cairo_uint64_sub, _cairo_uint64x64_128_mul(), and cairo_int128_t::hi.
_cairo_int_96by64_32x64_divrem()
cairo_quorem64_t _cairo_int_96by64_32x64_divrem (cairo_int128_t num, cairo_int64_t den)
Definition at line 795 of file cairo-wideint.c.
References _cairo_int128_negate, _cairo_int128_negative, _cairo_int64_negate, _cairo_int64_negative, _cairo_int64_to_uint64, _cairo_uint32s_to_uint64, _cairo_uint64_eq, _cairo_uint_96by64_32x64_divrem(), cairo_uquorem64_t::quo, cairo_quorem64_t::quo, cairo_uquorem64_t::rem, and cairo_quorem64_t::rem.
_cairo_uint128_add()
cairo_uint128_t _cairo_uint128_add (cairo_uint128_t a, cairo_uint128_t b)
Definition at line 388 of file cairo-wideint.c.
References _cairo_uint32_to_uint64, _cairo_uint64_add, and _cairo_uint64_lt.
Referenced by _cairo_uint128_divrem(), _cairo_uint128_negate(), ns3::int64x64_t::Udiv(), ns3::int64x64_t::Umul(), and ns3::int64x64_t::UmulByInvert().
_cairo_uint128_divrem()
cairo_uquorem128_t _cairo_uint128_divrem (cairo_uint128_t num, cairo_uint128_t den)
Definition at line 601 of file cairo-wideint.c.
References _cairo_msbset64, _cairo_uint128_add(), _cairo_uint128_le, _cairo_uint128_lsl(), _cairo_uint128_lt(), _cairo_uint128_ne, _cairo_uint128_rsl(), _cairo_uint128_sub(), _cairo_uint32_to_uint128(), cairo_uquorem128_t::quo, and cairo_uquorem128_t::rem.
Referenced by _cairo_int128_divrem(), and ns3::int64x64_t::Udiv().
_cairo_uint128_eq()
int _cairo_uint128_eq (cairo_uint128_t a, cairo_uint128_t b)
Definition at line 588 of file cairo-wideint.c.
References _cairo_uint64_eq.
Referenced by ns3::int64x64_t::Udiv().
_cairo_uint128_lsl()
cairo_uint128_t _cairo_uint128_lsl (cairo_uint128_t a, int shift)
Definition at line 516 of file cairo-wideint.c.
References _cairo_uint32_to_uint64, _cairo_uint64_add, _cairo_uint64_lsl, and _cairo_uint64_rsl.
Referenced by _cairo_uint128_divrem(), ns3::int64x64_t::Udiv(), and ns3::int64x64_t::Umul().
_cairo_uint128_lt()
int _cairo_uint128_lt (cairo_uint128_t a, cairo_uint128_t b)
Definition at line 570 of file cairo-wideint.c.
References _cairo_uint64_eq, and _cairo_uint64_lt.
Referenced by _cairo_int128_lt(), _cairo_uint128_divrem(), and ns3::int64x64_t::Udiv().
_cairo_uint128_mul()
cairo_uint128_t _cairo_uint128_mul (cairo_uint128_t a, cairo_uint128_t b)
Definition at line 503 of file cairo-wideint.c.
References _cairo_uint64_add, _cairo_uint64_mul, and _cairo_uint64x64_128_mul().
_cairo_uint128_negate()
cairo_uint128_t _cairo_uint128_negate (cairo_uint128_t a)
Definition at line 634 of file cairo-wideint.c.
References _cairo_uint128_add(), _cairo_uint32_to_uint128(), and _cairo_uint64_not.
Referenced by ns3::output_sign().
_cairo_uint128_not()
cairo_uint128_t _cairo_uint128_not (cairo_uint128_t a)
Definition at line 642 of file cairo-wideint.c.
References _cairo_uint64_not.
_cairo_uint128_rsa()
cairo_uint128_t _cairo_uint128_rsa (cairo_int128_t a, int shift)
Definition at line 552 of file cairo-wideint.c.
References _cairo_uint64_add, _cairo_uint64_lsl, _cairo_uint64_rsa, _cairo_uint64_rsl, cairo_int128_t::hi, and cairo_int128_t::lo.
_cairo_uint128_rsl()
cairo_uint128_t _cairo_uint128_rsl (cairo_uint128_t a, int shift)
Definition at line 534 of file cairo-wideint.c.
References _cairo_uint32_to_uint64, _cairo_uint64_add, _cairo_uint64_lsl, and _cairo_uint64_rsl.
Referenced by _cairo_uint128_divrem(), _cairo_uint_96by64_32x64_divrem(), and ns3::int64x64_t::Udiv().
_cairo_uint128_sub()
cairo_uint128_t _cairo_uint128_sub (cairo_uint128_t a, cairo_uint128_t b)
Definition at line 400 of file cairo-wideint.c.
References _cairo_uint32_to_uint64, _cairo_uint64_gt, and _cairo_uint64_sub.
Referenced by _cairo_uint128_divrem().
_cairo_uint32_to_uint128()
cairo_uint128_t _cairo_uint32_to_uint128 (uint32_t i)
Definition at line 348 of file cairo-wideint.c.
References _cairo_uint32_to_uint64.
Referenced by _cairo_uint128_divrem(), _cairo_uint128_negate(), and ns3::int64x64_t::Udiv().
_cairo_uint64_divrem()
cairo_uquorem64_t _cairo_uint64_divrem (cairo_uint64_t num, cairo_uint64_t den)
Definition at line 52 of file cairo-wideint.c.
References cairo_uquorem64_t::quo, and cairo_uquorem64_t::rem.
Referenced by _cairo_int64_divrem(), and _cairo_uint_96by64_32x64_divrem().
_cairo_uint64_to_uint128()
cairo_uint128_t _cairo_uint64_to_uint128 (cairo_uint64_t i)
Definition at line 368 of file cairo-wideint.c.
References _cairo_uint32_to_uint64.
Referenced by ns3::int64x64_t::Umul().
_cairo_uint64x64_128_mul()
cairo_uint128_t _cairo_uint64x64_128_mul (cairo_uint64_t a, cairo_uint64_t b)
Definition at line 460 of file cairo-wideint.c.
References _cairo_uint32x32_64_mul, _cairo_uint64_add, _cairo_uint64_lt, uint64_carry32, uint64_hi, uint64_hi32, uint64_lo, uint64_lo32, and uint64_shift32.
Referenced by _cairo_int64x64_128_mul(), _cairo_uint128_mul(), ns3::int64x64_t::Umul(), and ns3::int64x64_t::UmulByInvert().
_cairo_uint_96by64_32x64_divrem()
cairo_uquorem64_t _cairo_uint_96by64_32x64_divrem (cairo_uint128_t num, cairo_uint64_t den)
_cairo_uint_96by64_32x64_divrem:
Compute a 32 bit quotient and 64 bit remainder of a 96 bit unsigned dividend and 64 bit divisor. If the quotient doesn't fit into 32 bits then the returned remainder is equal to the divisor, and the quotient is the largest representable 64 bit integer. It is an error to call this function with the high 32 bits of ‘num’ being non-zero.
Definition at line 685 of file cairo-wideint.c.
References _cairo_uint128_rsl(), _cairo_uint128_to_uint32, _cairo_uint128_to_uint64, _cairo_uint32_to_uint64, _cairo_uint32s_to_uint64, _cairo_uint32x32_64_mul, _cairo_uint64_add, _cairo_uint64_divrem(), _cairo_uint64_ge, _cairo_uint64_lt, _cairo_uint64_sub, _cairo_uint64_to_uint32, cairo_uquorem64_t::quo, cairo_uquorem64_t::rem, uint64_hi32, and sample-rng-plot::x.
Referenced by _cairo_int_96by64_32x64_divrem().
Variable Documentation
cairo_impl128
const char* cairo_impl128 = "cairo_uint64_t"
Definition at line 345 of file cairo-wideint.c.
Referenced by ns3::int64x64::test::Int64x64ImplTestCase::DoRun().
cairo_impl64
const char* cairo_impl64 = "uint64_t"
Definition at line 47 of file cairo-wideint.c.
Referenced by ns3::int64x64::test::Int64x64ImplTestCase::DoRun().