ns-3: UdpTraceClientServerTestCase Class Reference
UdpTraceClientServerTestCase Class Reference
Test that all the udp packets generated by an udpTraceClient application are correctly received by an udpServer application.
Public Member Functions
UdpTraceClientServerTestCase ()
virtual ~UdpTraceClientServerTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test that all the udp packets generated by an udpTraceClient application are correctly received by an udpServer application.
Definition at line 126 of file udp-client-server-test.cc.
Constructor & Destructor Documentation
UdpTraceClientServerTestCase()
UdpTraceClientServerTestCase::UdpTraceClientServerTestCase ()
Definition at line 137 of file udp-client-server-test.cc.
~UdpTraceClientServerTestCase()
UdpTraceClientServerTestCase::~UdpTraceClientServerTestCase () virtual
Definition at line 142 of file udp-client-server-test.cc.
Member Function Documentation
DoRun()
void UdpTraceClientServerTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 146 of file udp-client-server-test.cc.
References ns3::NetDeviceContainer::Add(), ns3::Ipv4AddressHelper::Assign(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::UdpServerHelper::GetServer(), ns3::UdpServerHelper::Install(), ns3::UdpTraceClientHelper::Install(), ns3::InternetStackHelper::Install(), sample-rng-plot::n, NS_TEST_ASSERT_MSG_EQ, port, ns3::Seconds(), ns3::UdpTraceClientHelper::SetAttribute(), ns3::Ipv4AddressHelper::SetBase(), ns3::SimpleNetDevice::SetChannel(), ns3::ApplicationContainer::Start(), and ns3::ApplicationContainer::Stop().
The documentation for this class was generated from the following file:
src/applications/test/udp-client-server-test.cc