ns-3: ns3::lorawan::GatewayStatus Class Reference
ns3::lorawan::GatewayStatus Class Reference
#include "gateway-status.h"
Public Member Functions
GatewayStatus ()
GatewayStatus (Address address, Ptr< NetDevice > netDevice, Ptr< GatewayLorawanMac > gwMac)
virtual ~GatewayStatus ()
Address GetAddress ()
Get this gateway's P2P link address.
Ptr< GatewayLorawanMac > GetGatewayMac (void)
Get a pointer to this gateway's MAC instance.
Ptr< NetDevice > GetNetDevice ()
Get the NetDevice through which it's possible to contact this gateway from the server.
bool IsAvailableForTransmission (double frequency)
Set a pointer to this gateway's MAC instance.
void SetAddress (Address address)
Set this gateway's P2P link address.
void SetNetDevice (Ptr< NetDevice > netDevice)
Set the NetDevice through which it's possible to contact this gateway from the server.
void SetNextTransmissionTime (Time nextTransmissionTime)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Address m_address
The Address of the P2PNetDevice of this gateway.
Ptr< GatewayLorawanMac > m_gatewayMac
The Mac layer of the gateway.
Ptr< NetDevice > m_netDevice
The NetDevice through which to reach this gateway from the server.
Time m_nextTransmissionTime
This gateway's next transmission time.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 32 of file gateway-status.h.
Constructor & Destructor Documentation
GatewayStatus() [1/2]
ns3::lorawan::GatewayStatus::GatewayStatus ()
Definition at line 39 of file gateway-status.cc.
References NS_LOG_FUNCTION.
GatewayStatus() [2/2]
ns3::lorawan::GatewayStatus::GatewayStatus (Address address, Ptr< NetDevice > netDevice, Ptr< GatewayLorawanMac > gwMac)
Definition at line 49 of file gateway-status.cc.
References NS_LOG_FUNCTION.
~GatewayStatus()
ns3::lorawan::GatewayStatus::~GatewayStatus () virtual
Definition at line 44 of file gateway-status.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
GetAddress()
Address ns3::lorawan::GatewayStatus::GetAddress ()
Get this gateway's P2P link address.
Definition at line 60 of file gateway-status.cc.
References m_address, and NS_LOG_FUNCTION.
GetGatewayMac()
Ptr< GatewayLorawanMac > ns3::lorawan::GatewayStatus::GetGatewayMac (void)
Get a pointer to this gateway's MAC instance.
Definition at line 88 of file gateway-status.cc.
References m_gatewayMac.
GetNetDevice()
Ptr< NetDevice > ns3::lorawan::GatewayStatus::GetNetDevice ()
Get the NetDevice through which it's possible to contact this gateway from the server.
Definition at line 76 of file gateway-status.cc.
References m_netDevice.
GetTypeId()
TypeId ns3::lorawan::GatewayStatus::GetTypeId (void) static
Definition at line 30 of file gateway-status.cc.
References ns3::TypeId::AddConstructor().
IsAvailableForTransmission()
bool ns3::lorawan::GatewayStatus::IsAvailableForTransmission (double frequency)
Set a pointer to this gateway's MAC instance.
Query whether or not this gateway is available for immediate transmission on this frequency.
Parameters
frequency The frequency at which the gateway's availability should be queried.
Returns
True if the gateway's available, false otherwise.
Definition at line 94 of file gateway-status.cc.
References ns3::Time::GetSeconds(), m_gatewayMac, m_nextTransmissionTime, ns3::MilliSeconds(), ns3::Simulator::Now(), NS_LOG_INFO, and ns3::Seconds().
SetAddress()
void ns3::lorawan::GatewayStatus::SetAddress (Address address)
Set this gateway's P2P link address.
Definition at line 68 of file gateway-status.cc.
References first::address, m_address, and NS_LOG_FUNCTION.
SetNetDevice()
void ns3::lorawan::GatewayStatus::SetNetDevice (Ptr< NetDevice > netDevice)
Set the NetDevice through which it's possible to contact this gateway from the server.
Definition at line 82 of file gateway-status.cc.
References m_netDevice.
SetNextTransmissionTime()
void ns3::lorawan::GatewayStatus::SetNextTransmissionTime (Time nextTransmissionTime)
Definition at line 127 of file gateway-status.cc.
References m_nextTransmissionTime.
Member Data Documentation
m_address
Address ns3::lorawan::GatewayStatus::m_address private
The Address of the P2PNetDevice of this gateway.
Definition at line 85 of file gateway-status.h.
Referenced by GetAddress(), and SetAddress().
m_gatewayMac
Ptr<GatewayLorawanMac> ns3::lorawan::GatewayStatus::m_gatewayMac private
The Mac layer of the gateway.
Definition at line 89 of file gateway-status.h.
Referenced by GetGatewayMac(), and IsAvailableForTransmission().
m_netDevice
Ptr<NetDevice> ns3::lorawan::GatewayStatus::m_netDevice private
The NetDevice through which to reach this gateway from the server.
Definition at line 87 of file gateway-status.h.
Referenced by GetNetDevice(), and SetNetDevice().
m_nextTransmissionTime
Time ns3::lorawan::GatewayStatus::m_nextTransmissionTime private
This gateway's next transmission time.
Definition at line 91 of file gateway-status.h.
Referenced by IsAvailableForTransmission(), and SetNextTransmissionTime().
The documentation for this class was generated from the following files:
src/lorawan/model/gateway-status.h
src/lorawan/model/gateway-status.cc