ns-3: ns3::GtpcModifyBearerRequestMessage Class Reference
ns3::GtpcModifyBearerRequestMessage Class Reference
#include "epc-gtpc-header.h"
Classes
struct BearerContextToBeModified
Public Member Functions
GtpcModifyBearerRequestMessage ()
virtual ~GtpcModifyBearerRequestMessage ()
virtual uint32_t Deserialize (Buffer::Iterator start)
std::list< BearerContextToBeModified > GetBearerContextsToBeModified () const
uint64_t GetImsi () const
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetMessageSize (void) const
virtual uint32_t GetSerializedSize (void) const
uint32_t GetUliEcgi () const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetBearerContextsToBeModified (std::list< BearerContextToBeModified > bearerContexts)
void SetImsi (uint64_t imsi)
void SetUliEcgi (uint32_t uliEcgi)
Public Member Functions inherited from ns3::GtpcHeader
GtpcHeader ()
virtual ~GtpcHeader ()
void ComputeMessageLength (void)
uint16_t GetMessageLength () const
Get message length.
uint8_t GetMessageType () const
Get message type.
uint32_t GetSequenceNumber () const
Get sequence number.
uint32_t GetTeid () const
Get TEID.
void SetIesLength (uint16_t iesLength)
Set IEs length.
void SetMessageLength (uint16_t messageLength)
Set message length.
void SetMessageType (uint8_t messageType)
Set message type.
void SetSequenceNumber (uint32_t sequenceNumber)
Set sequence number.
void SetTeid (uint32_t teid)
Set TEID.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Public Member Functions inherited from ns3::GtpcIes
uint32_t DeserializeBearerContextHeader (Buffer::Iterator &i, uint16_t &length)
uint32_t DeserializeBearerQos (Buffer::Iterator &i, EpsBearer &bearerQos)
uint32_t DeserializeBearerTft (Buffer::Iterator &i, Ptr< EpcTft > epcTft)
uint32_t DeserializeCause (Buffer::Iterator &i, Cause_t &cause)
uint32_t DeserializeEbi (Buffer::Iterator &i, uint8_t &epsBearerId)
uint32_t DeserializeFteid (Buffer::Iterator &i, GtpcHeader::Fteid_t &fteid)
uint32_t DeserializeImsi (Buffer::Iterator &i, uint64_t &imsi)
uint32_t DeserializeUliEcgi (Buffer::Iterator &i, uint32_t &uliEcgi)
uint32_t GetSerializedSizeBearerTft (std::list< EpcTft::PacketFilter > packetFilters) const
uint64_t ReadNtohU40 (Buffer::Iterator &i)
void SerializeBearerContextHeader (Buffer::Iterator &i, uint16_t length) const
void SerializeBearerQos (Buffer::Iterator &i, EpsBearer bearerQos) const
void SerializeBearerTft (Buffer::Iterator &i, std::list< EpcTft::PacketFilter > packetFilters) const
void SerializeCause (Buffer::Iterator &i, Cause_t cause) const
void SerializeEbi (Buffer::Iterator &i, uint8_t epsBearerId) const
void SerializeFteid (Buffer::Iterator &i, GtpcHeader::Fteid_t fteid) const
void SerializeImsi (Buffer::Iterator &i, uint64_t imsi) const
void SerializeUliEcgi (Buffer::Iterator &i, uint32_t uliEcgi) const
void WriteHtonU40 (Buffer::Iterator &i, uint64_t data) const
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::GtpcHeader
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
std::list< BearerContextToBeModified > m_bearerContextsToBeModified
uint64_t m_imsi
uint32_t m_uliEcgi
Additional Inherited Members
Public Types inherited from ns3::GtpcHeader
enum InterfaceType_t {
S1U_ENB_GTPU = 0, S5_SGW_GTPU = 4, S5_PGW_GTPU = 5, S5_SGW_GTPC = 6,
S5_PGW_GTPC = 7, S11_MME_GTPC = 10
}
Interface Type enumeration.
enum MessageType_t {
Reserved = 0, CreateSessionRequest = 32, CreateSessionResponse = 33, ModifyBearerRequest = 34,
ModifyBearerResponse = 35, DeleteSessionRequest = 36, DeleteSessionResponse = 37, DeleteBearerCommand = 66,
DeleteBearerRequest = 99, DeleteBearerResponse = 100
}
Message Type enumeration.
Public Types inherited from ns3::GtpcIes
enum Cause_t { RESERVED = 0, REQUEST_ACCEPTED = 16 }
Public Attributes inherited from ns3::GtpcIes
const uint32_t serializedSizeBearerContextHeader = 4
const uint32_t serializedSizeBearerQos = 26
const uint32_t serializedSizeCause = 6
const uint32_t serializedSizeEbi = 5
const uint32_t serializedSizeFteid = 13
const uint32_t serializedSizeImsi = 12
const uint32_t serializedSizePacketFilter = 3 + 9 + 9 + 5 + 5 + 3
const uint32_t serializedSizeUliEcgi = 12
Protected Member Functions inherited from ns3::GtpcHeader
uint32_t PreDeserialize (Buffer::Iterator &i)
Deserialize the GTP-C header in the GTP-C messages.
void PreSerialize (Buffer::Iterator &i) const
Serialize the GTP-C header in the GTP-C messages.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 320 of file epc-gtpc-header.h.
Constructor & Destructor Documentation
GtpcModifyBearerRequestMessage()
ns3::GtpcModifyBearerRequestMessage::GtpcModifyBearerRequestMessage ()
Definition at line 794 of file epc-gtpc-header.cc.
References m_imsi, m_uliEcgi, ns3::GtpcHeader::ModifyBearerRequest, ns3::GtpcHeader::SetMessageType(), and ns3::GtpcHeader::SetSequenceNumber().
~GtpcModifyBearerRequestMessage()
ns3::GtpcModifyBearerRequestMessage::~GtpcModifyBearerRequestMessage () virtual
Definition at line 802 of file epc-gtpc-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::GtpcModifyBearerRequestMessage::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Reimplemented from ns3::GtpcHeader.
Definition at line 847 of file epc-gtpc-header.cc.
References ns3::GtpcIes::DeserializeBearerContextHeader(), ns3::GtpcIes::DeserializeEbi(), ns3::GtpcIes::DeserializeFteid(), ns3::GtpcIes::DeserializeImsi(), ns3::GtpcIes::DeserializeUliEcgi(), ns3::GtpcModifyBearerRequestMessage::BearerContextToBeModified::epsBearerId, ns3::GtpcModifyBearerRequestMessage::BearerContextToBeModified::fteid, ns3::Buffer::Iterator::GetRemainingSize(), GetSerializedSize(), m_bearerContextsToBeModified, m_imsi, m_uliEcgi, ns3::GtpcHeader::PreDeserialize(), and visualizer.core::start().
GetBearerContextsToBeModified()
std::list< GtpcModifyBearerRequestMessage::BearerContextToBeModified > ns3::GtpcModifyBearerRequestMessage::GetBearerContextsToBeModified () const
Definition at line 902 of file epc-gtpc-header.cc.
References m_bearerContextsToBeModified.
Referenced by ns3::EpcPgwApplication::DoRecvModifyBearerRequest(), and ns3::EpcSgwApplication::DoRecvModifyBearerRequest().
GetImsi()
uint64_t ns3::GtpcModifyBearerRequestMessage::GetImsi () const
Definition at line 878 of file epc-gtpc-header.cc.
References m_imsi.
Referenced by ns3::EpcPgwApplication::DoRecvModifyBearerRequest(), and ns3::EpcSgwApplication::DoRecvModifyBearerRequest().
GetInstanceTypeId()
TypeId ns3::GtpcModifyBearerRequestMessage::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Reimplemented from ns3::GtpcHeader.
Definition at line 807 of file epc-gtpc-header.cc.
References GetTypeId().
GetMessageSize()
uint32_t ns3::GtpcModifyBearerRequestMessage::GetMessageSize (void) const virtual
Reimplemented from ns3::GtpcHeader.
Definition at line 813 of file epc-gtpc-header.cc.
References m_bearerContextsToBeModified, ns3::GtpcIes::serializedSizeBearerContextHeader, ns3::GtpcIes::serializedSizeEbi, ns3::GtpcIes::serializedSizeFteid, ns3::GtpcIes::serializedSizeImsi, and ns3::GtpcIes::serializedSizeUliEcgi.
Referenced by GetSerializedSize().
GetSerializedSize()
uint32_t ns3::GtpcModifyBearerRequestMessage::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Reimplemented from ns3::GtpcHeader.
Definition at line 823 of file epc-gtpc-header.cc.
References GetMessageSize(), and ns3::GtpcHeader::GetSerializedSize().
Referenced by Deserialize().
GetTypeId()
TypeId ns3::GtpcModifyBearerRequestMessage::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 785 of file epc-gtpc-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
GetUliEcgi()
uint32_t ns3::GtpcModifyBearerRequestMessage::GetUliEcgi () const
Definition at line 890 of file epc-gtpc-header.cc.
References m_uliEcgi.
Referenced by ns3::EpcPgwApplication::DoRecvModifyBearerRequest(), and ns3::EpcSgwApplication::DoRecvModifyBearerRequest().
Print()
void ns3::GtpcModifyBearerRequestMessage::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Reimplemented from ns3::GtpcHeader.
Definition at line 872 of file epc-gtpc-header.cc.
References m_imsi, and m_uliEcgi.
Serialize()
void ns3::GtpcModifyBearerRequestMessage::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Reimplemented from ns3::GtpcHeader.
Definition at line 829 of file epc-gtpc-header.cc.
References m_bearerContextsToBeModified, m_imsi, m_uliEcgi, ns3::GtpcHeader::PreSerialize(), ns3::GtpcIes::SerializeBearerContextHeader(), ns3::GtpcIes::serializedSizeEbi, ns3::GtpcIes::serializedSizeFteid, ns3::GtpcIes::SerializeEbi(), ns3::GtpcIes::SerializeFteid(), ns3::GtpcIes::SerializeImsi(), ns3::GtpcIes::SerializeUliEcgi(), and visualizer.core::start().
SetBearerContextsToBeModified()
void ns3::GtpcModifyBearerRequestMessage::SetBearerContextsToBeModified (std::list< BearerContextToBeModified > bearerContexts)
Definition at line 908 of file epc-gtpc-header.cc.
References m_bearerContextsToBeModified.
Referenced by ns3::EpcMmeApplication::DoPathSwitchRequest().
SetImsi()
void ns3::GtpcModifyBearerRequestMessage::SetImsi (uint64_t imsi)
Definition at line 884 of file epc-gtpc-header.cc.
References m_imsi.
Referenced by ns3::EpcMmeApplication::DoPathSwitchRequest(), and ns3::EpcSgwApplication::DoRecvModifyBearerRequest().
SetUliEcgi()
void ns3::GtpcModifyBearerRequestMessage::SetUliEcgi (uint32_t uliEcgi)
Definition at line 896 of file epc-gtpc-header.cc.
References m_uliEcgi.
Referenced by ns3::EpcMmeApplication::DoPathSwitchRequest(), and ns3::EpcSgwApplication::DoRecvModifyBearerRequest().
Member Data Documentation
m_bearerContextsToBeModified
std::list<BearerContextToBeModified> ns3::GtpcModifyBearerRequestMessage::m_bearerContextsToBeModified private
Definition at line 356 of file epc-gtpc-header.h.
Referenced by Deserialize(), GetBearerContextsToBeModified(), GetMessageSize(), Serialize(), and SetBearerContextsToBeModified().
m_imsi
uint64_t ns3::GtpcModifyBearerRequestMessage::m_imsi private
Definition at line 353 of file epc-gtpc-header.h.
Referenced by GtpcModifyBearerRequestMessage(), Deserialize(), GetImsi(), Print(), Serialize(), and SetImsi().
m_uliEcgi
uint32_t ns3::GtpcModifyBearerRequestMessage::m_uliEcgi private
Definition at line 354 of file epc-gtpc-header.h.
Referenced by GtpcModifyBearerRequestMessage(), Deserialize(), GetUliEcgi(), Print(), Serialize(), and SetUliEcgi().
The documentation for this class was generated from the following files:
src/lte/model/epc-gtpc-header.h
src/lte/model/epc-gtpc-header.cc