ns-3: ns3::AdhocAlohaNoackIdealPhyHelper Class Reference
ns3::AdhocAlohaNoackIdealPhyHelper Class Reference
Spectrum Models
create the AlohaNoackNetDevice
#include "adhoc-aloha-noack-ideal-phy-helper.h"
Public Member Functions
AdhocAlohaNoackIdealPhyHelper ()
~AdhocAlohaNoackIdealPhyHelper ()
NetDeviceContainer Install (NodeContainer c) const
NetDeviceContainer Install (Ptr< Node > node) const
NetDeviceContainer Install (std::string nodeName) const
void SetAntenna (std::string type, std::string n0="", const AttributeValue &v0=EmptyAttributeValue(), std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue(), std::string n6="", const AttributeValue &v6=EmptyAttributeValue(), std::string n7="", const AttributeValue &v7=EmptyAttributeValue())
void SetChannel (Ptr< SpectrumChannel > channel)
set the SpectrumChannel that will be used by SpectrumPhy instances created by this helper
void SetChannel (std::string channelName)
set the SpectrumChannel that will be used by SpectrumPhy instances created by this helper
void SetDeviceAttribute (std::string n1, const AttributeValue &v1)
void SetNoisePowerSpectralDensity (Ptr< SpectrumValue > noisePsd)
void SetPhyAttribute (std::string name, const AttributeValue &v)
void SetTxPowerSpectralDensity (Ptr< SpectrumValue > txPsd)
Protected Attributes
ObjectFactory m_antenna
Object factory for the Antenna objects.
Ptr< SpectrumChannel > m_channel
Channel.
ObjectFactory m_device
Object factory for the NetDevice objects.
Ptr< SpectrumValue > m_noisePsd
Noise power spectral density.
ObjectFactory m_phy
Object factory for the phy objects.
ObjectFactory m_queue
Object factory for the Queue objects.
Ptr< SpectrumValue > m_txPsd
Tx power spectral density.
Detailed Description
create the AlohaNoackNetDevice
Definition at line 42 of file adhoc-aloha-noack-ideal-phy-helper.h.
Constructor & Destructor Documentation
AdhocAlohaNoackIdealPhyHelper()
ns3::AdhocAlohaNoackIdealPhyHelper::AdhocAlohaNoackIdealPhyHelper ()
Definition at line 41 of file adhoc-aloha-noack-ideal-phy-helper.cc.
References m_antenna, m_device, m_phy, m_queue, and ns3::ObjectFactory::SetTypeId().
~AdhocAlohaNoackIdealPhyHelper()
ns3::AdhocAlohaNoackIdealPhyHelper::~AdhocAlohaNoackIdealPhyHelper ()
Definition at line 49 of file adhoc-aloha-noack-ideal-phy-helper.cc.
Member Function Documentation
Install() [1/3]
NetDeviceContainer ns3::AdhocAlohaNoackIdealPhyHelper::Install (NodeContainer c) const
Parameters
c the set of nodes on which a device must be created
Returns
a device container which contains all the devices created by this method.
Definition at line 118 of file adhoc-aloha-noack-ideal-phy-helper.cc.
References ns3::Node::AddDevice(), ns3::Mac48Address::Allocate(), ns3::NodeContainer::Begin(), ns3::ObjectFactory::Create(), first::devices, ns3::NodeContainer::End(), ns3::Object::GetObject(), m_antenna, m_channel, m_device, m_noisePsd, m_phy, m_queue, m_txPsd, ns3::MakeCallback(), ns3::AlohaNoackNetDevice::NotifyReceptionEndOk(), ns3::AlohaNoackNetDevice::NotifyReceptionStart(), ns3::AlohaNoackNetDevice::NotifyTransmissionEnd(), NS_ASSERT, NS_ASSERT_MSG(), third::phy, and ns3::HalfDuplexIdealPhy::StartTx().
Referenced by SpectrumIdealPhyTestCase::DoRun(), and Install().
Install() [2/3]
NetDeviceContainer ns3::AdhocAlohaNoackIdealPhyHelper::Install (Ptr< Node > node) const
Parameters
node the node on which a device must be created
Returns
a device container which contains all the devices created by this method.
Definition at line 173 of file adhoc-aloha-noack-ideal-phy-helper.cc.
References Install().
Install() [3/3]
NetDeviceContainer ns3::AdhocAlohaNoackIdealPhyHelper::Install (std::string nodeName) const
Parameters
nodeName the name of node on which a device must be created
Returns
a device container which contains all the devices created by this method.
Definition at line 179 of file adhoc-aloha-noack-ideal-phy-helper.cc.
References Install().
SetAntenna()
void ns3::AdhocAlohaNoackIdealPhyHelper::SetAntenna (std::string type, std::string n0 = "", const AttributeValue & v0 = EmptyAttributeValue (), std::string n1 = "", const AttributeValue & v1 = EmptyAttributeValue (), std::string n2 = "", const AttributeValue & v2 = EmptyAttributeValue (), std::string n3 = "", const AttributeValue & v3 = EmptyAttributeValue (), std::string n4 = "", const AttributeValue & v4 = EmptyAttributeValue (), std::string n5 = "", const AttributeValue & v5 = EmptyAttributeValue (), std::string n6 = "", const AttributeValue & v6 = EmptyAttributeValue (), std::string n7 = "", const AttributeValue & v7 = EmptyAttributeValue ())
Parameters
type the type of the model to set
n0 the name of the attribute to set
v0 the value of the attribute to set
n1 the name of the attribute to set
v1 the value of the attribute to set
n2 the name of the attribute to set
v2 the value of the attribute to set
n3 the name of the attribute to set
v3 the value of the attribute to set
n4 the name of the attribute to set
v4 the value of the attribute to set
n5 the name of the attribute to set
v5 the value of the attribute to set
n6 the name of the attribute to set
v6 the value of the attribute to set
n7 the name of the attribute to set
v7 the value of the attribute to set
Configure the AntennaModel instance for each new device to be created
Definition at line 94 of file adhoc-aloha-noack-ideal-phy-helper.cc.
References m_antenna, ns3::ObjectFactory::Set(), and ns3::ObjectFactory::SetTypeId().
SetChannel() [1/2]
void ns3::AdhocAlohaNoackIdealPhyHelper::SetChannel (Ptr< SpectrumChannel > channel)
set the SpectrumChannel that will be used by SpectrumPhy instances created by this helper
Parameters
channel
Definition at line 54 of file adhoc-aloha-noack-ideal-phy-helper.cc.
References third::channel, and m_channel.
Referenced by SpectrumIdealPhyTestCase::DoRun().
SetChannel() [2/2]
void ns3::AdhocAlohaNoackIdealPhyHelper::SetChannel (std::string channelName)
set the SpectrumChannel that will be used by SpectrumPhy instances created by this helper
Parameters
channelName
Definition at line 60 of file adhoc-aloha-noack-ideal-phy-helper.cc.
References third::channel, and m_channel.
SetDeviceAttribute()
void ns3::AdhocAlohaNoackIdealPhyHelper::SetDeviceAttribute (std::string n1, const AttributeValue & v1)
Parameters
n1 the name of the attribute to set
v1 the value of the attribute to set
Set these attributes on each AlohaNoackNetDevice created
Definition at line 88 of file adhoc-aloha-noack-ideal-phy-helper.cc.
References m_device, and ns3::ObjectFactory::Set().
SetNoisePowerSpectralDensity()
void ns3::AdhocAlohaNoackIdealPhyHelper::SetNoisePowerSpectralDensity (Ptr< SpectrumValue > noisePsd)
Parameters
noisePsd the Power Spectral Density to be used for transmission by all created PHY instances
Definition at line 74 of file adhoc-aloha-noack-ideal-phy-helper.cc.
References m_noisePsd, and NS_LOG_FUNCTION.
Referenced by SpectrumIdealPhyTestCase::DoRun().
SetPhyAttribute()
void ns3::AdhocAlohaNoackIdealPhyHelper::SetPhyAttribute (std::string name, const AttributeValue & v)
Parameters
name the name of the attribute to set
v the value of the attribute
Set these attributes on each HdOfdmSpectrumPhy instance to be created
Definition at line 81 of file adhoc-aloha-noack-ideal-phy-helper.cc.
References m_phy, and ns3::ObjectFactory::Set().
Referenced by SpectrumIdealPhyTestCase::DoRun().
SetTxPowerSpectralDensity()
void ns3::AdhocAlohaNoackIdealPhyHelper::SetTxPowerSpectralDensity (Ptr< SpectrumValue > txPsd)
Parameters
txPsd the Power Spectral Density to be used for transmission by all created PHY instances
Definition at line 67 of file adhoc-aloha-noack-ideal-phy-helper.cc.
References m_txPsd, and NS_LOG_FUNCTION.
Referenced by SpectrumIdealPhyTestCase::DoRun().
Member Data Documentation
m_antenna
ObjectFactory ns3::AdhocAlohaNoackIdealPhyHelper::m_antenna protected
Object factory for the Antenna objects.
Definition at line 144 of file adhoc-aloha-noack-ideal-phy-helper.h.
Referenced by AdhocAlohaNoackIdealPhyHelper(), Install(), and SetAntenna().
m_channel
Ptr<SpectrumChannel> ns3::AdhocAlohaNoackIdealPhyHelper::m_channel protected
Channel.
Definition at line 145 of file adhoc-aloha-noack-ideal-phy-helper.h.
Referenced by Install(), and SetChannel().
m_device
ObjectFactory ns3::AdhocAlohaNoackIdealPhyHelper::m_device protected
Object factory for the NetDevice objects.
Definition at line 142 of file adhoc-aloha-noack-ideal-phy-helper.h.
Referenced by AdhocAlohaNoackIdealPhyHelper(), Install(), and SetDeviceAttribute().
m_noisePsd
Ptr<SpectrumValue> ns3::AdhocAlohaNoackIdealPhyHelper::m_noisePsd protected
Noise power spectral density.
Definition at line 147 of file adhoc-aloha-noack-ideal-phy-helper.h.
Referenced by Install(), and SetNoisePowerSpectralDensity().
m_phy
ObjectFactory ns3::AdhocAlohaNoackIdealPhyHelper::m_phy protected
Object factory for the phy objects.
Definition at line 141 of file adhoc-aloha-noack-ideal-phy-helper.h.
Referenced by AdhocAlohaNoackIdealPhyHelper(), Install(), and SetPhyAttribute().
m_queue
ObjectFactory ns3::AdhocAlohaNoackIdealPhyHelper::m_queue protected
Object factory for the Queue objects.
Definition at line 143 of file adhoc-aloha-noack-ideal-phy-helper.h.
Referenced by AdhocAlohaNoackIdealPhyHelper(), and Install().
m_txPsd
Ptr<SpectrumValue> ns3::AdhocAlohaNoackIdealPhyHelper::m_txPsd protected
Tx power spectral density.
Definition at line 146 of file adhoc-aloha-noack-ideal-phy-helper.h.
Referenced by Install(), and SetTxPowerSpectralDensity().
The documentation for this class was generated from the following files:
src/spectrum/helper/adhoc-aloha-noack-ideal-phy-helper.h
src/spectrum/helper/adhoc-aloha-noack-ideal-phy-helper.cc