ns-3: ns3::OrbisTopologyReader Class Reference
ns3::OrbisTopologyReader Class Reference
Topology Input Readers
Topology file reader (Orbis-format type).
#include "orbis-topology-reader.h"
Public Member Functions
OrbisTopologyReader ()
virtual ~OrbisTopologyReader ()
virtual NodeContainer Read (void)
Main topology reading function.
Public Member Functions inherited from ns3::TopologyReader
TopologyReader ()
virtual ~TopologyReader ()
void AddLink (Link link)
Adds a link to the topology.
std::string GetFileName (void) const
Returns the input file name.
ConstLinksIterator LinksBegin (void) const
Returns an iterator to the the first link in this block.
bool LinksEmpty (void) const
Checks if the block contains any links.
ConstLinksIterator LinksEnd (void) const
Returns an iterator to the the last link in this block.
int LinksSize (void) const
Returns the number of links in this block.
void SetFileName (const std::string &fileName)
Sets the input file name.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TopologyReader
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
OrbisTopologyReader (const OrbisTopologyReader &)
Copy constructor.
OrbisTopologyReader & operator= (const OrbisTopologyReader &)
Copy constructor.
Additional Inherited Members
Public Types inherited from ns3::TopologyReader
typedef std::list< Link >::const_iterator ConstLinksIterator
Constant iterator to the list of the links.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Topology file reader (Orbis-format type).
This class takes an input file in Orbis format and extracts all the information needed to build the topology (i.e.number of nodes, links and links structure). It have been tested with Orbis 0.70 http://www.sysnet.ucsd.edu/~pmahadevan/topo_research/topo.html
Definition at line 49 of file orbis-topology-reader.h.
Constructor & Destructor Documentation
OrbisTopologyReader() [1/2]
ns3::OrbisTopologyReader::OrbisTopologyReader ()
Definition at line 52 of file orbis-topology-reader.cc.
References NS_LOG_FUNCTION.
~OrbisTopologyReader()
ns3::OrbisTopologyReader::~OrbisTopologyReader () virtual
Definition at line 57 of file orbis-topology-reader.cc.
References NS_LOG_FUNCTION.
OrbisTopologyReader() [2/2]
ns3::OrbisTopologyReader::OrbisTopologyReader (const OrbisTopologyReader &) private
Copy constructor.
Defined and unimplemented to avoid misuse.
Member Function Documentation
GetTypeId()
TypeId ns3::OrbisTopologyReader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId.
Definition at line 42 of file orbis-topology-reader.cc.
References ns3::TypeId::SetParent().
operator=()
OrbisTopologyReader& ns3::OrbisTopologyReader::operator= (const OrbisTopologyReader &) private
Copy constructor.
Defined and unimplemented to avoid misuse.
Returns
Read()
NodeContainer ns3::OrbisTopologyReader::Read (void) virtual
Main topology reading function.
This method opens an input stream and reads the Orbis-format file. Every row represents a topology link (the ids of a couple of nodes), so the input file is read line by line to figure out how many links and nodes are in the topology.
Returns
The container of the nodes created (or empty container if there was an error)
Implements ns3::TopologyReader.
Definition at line 63 of file orbis-topology-reader.cc.
References ns3::TopologyReader::AddLink(), ns3::TopologyReader::GetFileName(), first::nodes, and NS_LOG_INFO.
The documentation for this class was generated from the following files:
src/topology-read/model/orbis-topology-reader.h
src/topology-read/model/orbis-topology-reader.cc