ns-3: TestParentQueueDisc Class Reference
TestParentQueueDisc Class Reference
Traffic-control » traffic-control module tests | Test suites
Test Parent Queue Disc having a child of type TestChildQueueDisc.
Public Member Functions
TestParentQueueDisc ()
Constructor.
virtual ~TestParentQueueDisc ()
virtual bool CheckConfig (void)
Check whether the current configuration is correct.
virtual Ptr< QueueDiscItem > DoDequeue (void)
This function actually extracts a packet from the queue disc.
virtual bool DoEnqueue (Ptr< QueueDiscItem > item)
This function actually enqueues a packet into the queue disc.
virtual void InitializeParams (void)
Initialize parameters (if any) before the first packet is enqueued.
Public Member Functions inherited from ns3::QueueDisc
QueueDisc (QueueDiscSizePolicy policy, QueueSizeUnit unit)
Constructor.
QueueDisc (QueueDiscSizePolicy policy=QueueDiscSizePolicy::SINGLE_INTERNAL_QUEUE)
Constructor.
virtual ~QueueDisc ()
void AddInternalQueue (Ptr< InternalQueue > queue)
Add an internal queue to the tail of the list of queues.
void AddPacketFilter (Ptr< PacketFilter > filter)
Add a packet filter to the tail of the list of filters used to classify packets.
void AddQueueDiscClass (Ptr< QueueDiscClass > qdClass)
Add a queue disc class to the tail of the list of classes.
int32_t Classify (Ptr< QueueDiscItem > item)
Classify a packet by calling the packet filters, one at a time, until either a filter able to classify the packet is found or all the filters have been processed.
Ptr< QueueDiscItem > Dequeue (void)
Extract from the queue disc the packet that has been dequeued by calling Peek, if any, or call the private DoDequeue method (which must be implemented by derived classes) to dequeue a packet, otherwise.
bool Enqueue (Ptr< QueueDiscItem > item)
Pass a packet to store to the queue discipline.
QueueSize GetCurrentSize (void)
Get the current size of the queue disc in bytes, if operating in bytes mode, or packets, otherwise.
Ptr< InternalQueue > GetInternalQueue (std::size_t i) const
Get the i-th internal queue.
QueueSize GetMaxSize (void) const
Get the maximum size of the queue disc.
uint32_t GetNBytes (void) const
Get the amount of bytes stored by the queue disc.
Ptr< NetDeviceQueueInterface > GetNetDeviceQueueInterface (void) const
std::size_t GetNInternalQueues (void) const
Get the number of internal queues.
std::size_t GetNPacketFilters (void) const
Get the number of packet filters.
uint32_t GetNPackets (void) const
Get the number of packets stored by the queue disc.
std::size_t GetNQueueDiscClasses (void) const
Get the number of queue disc classes.
Ptr< PacketFilter > GetPacketFilter (std::size_t i) const
Get the i-th packet filter.
Ptr< QueueDiscClass > GetQueueDiscClass (std::size_t i) const
Get the i-th queue disc class.
virtual uint32_t GetQuota (void) const
Get the maximum number of dequeue operations following a packet enqueue.
SendCallback GetSendCallback (void) const
const Stats & GetStats (void)
Retrieve all the collected statistics.
virtual WakeMode GetWakeMode (void) const
When setting up the wake callbacks on the netdevice queues, it is necessary to determine which queue disc (the root queue disc or one of its children) should be activated when the netdevice wakes one of its transmission queues.
Ptr< const QueueDiscItem > Peek (void)
Get a copy of the next packet the queue discipline will extract.
void Run (void)
Modelled after the Linux function __qdisc_run (net/sched/sch_generic.c) Dequeues multiple packets, until a quota is exceeded or sending a packet to the device failed.
bool SetMaxSize (QueueSize size)
Set the maximum size of the queue disc.
void SetNetDeviceQueueInterface (Ptr< NetDeviceQueueInterface > ndqi)
virtual void SetQuota (const uint32_t quota)
Set the maximum number of dequeue operations following a packet enqueue.
void SetSendCallback (SendCallback func)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Additional Inherited Members
Public Types inherited from ns3::QueueDisc
typedef Queue< QueueDiscItem > InternalQueue
Internal queues store QueueDiscItem objects.
typedef std::function< void(Ptr< QueueDiscItem >)> SendCallback
Callback invoked to send a packet to the receiving object when Run is called.
enum WakeMode { WAKE_ROOT = 0x00, WAKE_CHILD = 0x01 }
Used to determine whether the queue disc itself or its children must be activated when a netdevice wakes a transmission queue.
Static Public Member Functions inherited from ns3::QueueDisc
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes inherited from ns3::QueueDisc
static constexpr const char * CHILD_QUEUE_DISC_DROP = "(Dropped by child queue disc) "
Packet dropped by a child queue disc.
static constexpr const char * CHILD_QUEUE_DISC_MARK = "(Marked by child queue disc) "
Packet marked by a child queue disc.
static constexpr const char * INTERNAL_QUEUE_DROP = "Dropped by internal queue"
Packet dropped by an internal queue.
Protected Member Functions inherited from ns3::QueueDisc
virtual void DoDispose (void)
Dispose of the object.
void DoInitialize (void)
Check whether the configuration is correct and initialize parameters.
void DropAfterDequeue (Ptr< const QueueDiscItem > item, const char *reason)
Perform the actions required when the queue disc is notified of a packet dropped after dequeue.
void DropBeforeEnqueue (Ptr< const QueueDiscItem > item, const char *reason)
Perform the actions required when the queue disc is notified of a packet dropped before enqueue.
bool Mark (Ptr< QueueDiscItem > item, const char *reason)
Marks the given packet and, if successful, updates the counters associated with the given reason.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Test Parent Queue Disc having a child of type TestChildQueueDisc.
Definition at line 151 of file queue-disc-traces-test-suite.cc.
Constructor & Destructor Documentation
TestParentQueueDisc()
TestParentQueueDisc::TestParentQueueDisc ()
Constructor.
Definition at line 165 of file queue-disc-traces-test-suite.cc.
~TestParentQueueDisc()
TestParentQueueDisc::~TestParentQueueDisc () virtual
Definition at line 170 of file queue-disc-traces-test-suite.cc.
Member Function Documentation
CheckConfig()
bool TestParentQueueDisc::CheckConfig (void) virtual
Check whether the current configuration is correct.
Default objects (such as internal queues) might be created by this method to ensure the configuration is correct. This method is automatically called at simulation initialization time, and it is called before the InitializeParams () method. It is appropriate to promote parameter initialization to this method if it aids in checking for correct configuration.
See also
QueueDisc::InitializeParams
Returns
true if the configuration is correct, false otherwise
Implements ns3::QueueDisc.
Definition at line 187 of file queue-disc-traces-test-suite.cc.
References ns3::QueueDisc::AddQueueDiscClass(), and ns3::QueueDiscClass::SetQueueDisc().
DoDequeue()
Ptr< QueueDiscItem > TestParentQueueDisc::DoDequeue (void) virtual
This function actually extracts a packet from the queue disc.
Returns
0 if the operation was not successful; the item otherwise.
Implements ns3::QueueDisc.
Definition at line 181 of file queue-disc-traces-test-suite.cc.
References ns3::QueueDisc::GetQueueDiscClass().
DoEnqueue()
bool TestParentQueueDisc::DoEnqueue (Ptr< QueueDiscItem > item) virtual
This function actually enqueues a packet into the queue disc.
Parameters
item item to enqueue
Returns
True if the operation was successful; false otherwise
Implements ns3::QueueDisc.
Definition at line 175 of file queue-disc-traces-test-suite.cc.
References ns3::QueueDisc::GetQueueDiscClass().
InitializeParams()
void TestParentQueueDisc::InitializeParams (void) virtual
Initialize parameters (if any) before the first packet is enqueued.
This method is automatically called at simulation initialization time, after the CheckConfig() method has been called.
See also
QueueDisc::CheckConfig
Implements ns3::QueueDisc.
Definition at line 196 of file queue-disc-traces-test-suite.cc.
The documentation for this class was generated from the following file:
src/traffic-control/test/queue-disc-traces-test-suite.cc