ns-3: ns3::ConstantSpectrumPropagationLossModel Class Reference
ns3::ConstantSpectrumPropagationLossModel Class Reference
Spectrum Models
#include "constant-spectrum-propagation-loss.h"
Public Member Functions
ConstantSpectrumPropagationLossModel ()
~ConstantSpectrumPropagationLossModel ()
virtual Ptr< SpectrumValue > DoCalcRxPowerSpectralDensity (Ptr< const SpectrumValue > txPsd, Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const
double GetLossDb () const
Get the propagation loss.
void SetLossDb (double lossDb)
Set the propagation loss.
Public Member Functions inherited from ns3::SpectrumPropagationLossModel
SpectrumPropagationLossModel ()
virtual ~SpectrumPropagationLossModel ()
Ptr< SpectrumValue > CalcRxPowerSpectralDensity (Ptr< const SpectrumValue > txPsd, Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const
This method is to be called to calculate.
void SetNext (Ptr< SpectrumPropagationLossModel > next)
Used to chain various instances of SpectrumPropagationLossModel.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::SpectrumPropagationLossModel
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Attributes
double m_lossDb
Propagation loss [dB].
double m_lossLinear
Propagation loss (linear)
Additional Inherited Members
Protected Member Functions inherited from ns3::SpectrumPropagationLossModel
virtual void DoDispose ()
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A Constant (fixed) propagation loss. The loss is not dependent on the distance.
Definition at line 33 of file constant-spectrum-propagation-loss.h.
Constructor & Destructor Documentation
ConstantSpectrumPropagationLossModel()
ns3::ConstantSpectrumPropagationLossModel::ConstantSpectrumPropagationLossModel ()
Definition at line 35 of file constant-spectrum-propagation-loss.cc.
References NS_LOG_FUNCTION.
~ConstantSpectrumPropagationLossModel()
ns3::ConstantSpectrumPropagationLossModel::~ConstantSpectrumPropagationLossModel ()
Definition at line 40 of file constant-spectrum-propagation-loss.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoCalcRxPowerSpectralDensity()
Ptr< SpectrumValue > ns3::ConstantSpectrumPropagationLossModel::DoCalcRxPowerSpectralDensity (Ptr< const SpectrumValue > txPsd, Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const virtual
Parameters
txPsd set of values Vs frequency representing the transmission power. See SpectrumChannel for details.
a sender mobility
b receiver mobility
Returns
set of values Vs frequency representing the received power in the same units used for the txPower parameter.
Implements ns3::SpectrumPropagationLossModel.
Definition at line 81 of file constant-spectrum-propagation-loss.cc.
References ns3::SpectrumValue::ConstBandsBegin(), ns3::SpectrumValue::ConstBandsEnd(), m_lossLinear, NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC(), ns3::SpectrumValue::ValuesBegin(), and ns3::SpectrumValue::ValuesEnd().
GetLossDb()
double ns3::ConstantSpectrumPropagationLossModel::GetLossDb () const
Get the propagation loss.
Returns
the propagation loss [dB]
Definition at line 73 of file constant-spectrum-propagation-loss.cc.
References m_lossDb, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::ConstantSpectrumPropagationLossModel::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 46 of file constant-spectrum-propagation-loss.cc.
References GetLossDb(), ns3::MakeDoubleAccessor(), SetLossDb(), and ns3::TypeId::SetParent().
SetLossDb()
void ns3::ConstantSpectrumPropagationLossModel::SetLossDb (double lossDb)
Set the propagation loss.
Parameters
lossDb the propagation loss [dB]
Definition at line 64 of file constant-spectrum-propagation-loss.cc.
References m_lossDb, m_lossLinear, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
Member Data Documentation
m_lossDb
double ns3::ConstantSpectrumPropagationLossModel::m_lossDb protected
Propagation loss [dB].
Definition at line 60 of file constant-spectrum-propagation-loss.h.
Referenced by GetLossDb(), and SetLossDb().
m_lossLinear
double ns3::ConstantSpectrumPropagationLossModel::m_lossLinear protected
Propagation loss (linear)
Definition at line 61 of file constant-spectrum-propagation-loss.h.
Referenced by DoCalcRxPowerSpectralDensity(), and SetLossDb().
The documentation for this class was generated from the following files:
src/spectrum/model/constant-spectrum-propagation-loss.h
src/spectrum/model/constant-spectrum-propagation-loss.cc