ns-3: ns3::PbbTlv Class Reference
ns3::PbbTlv Class Reference
A packet or message TLV.
#include "packetbb.h"
Public Member Functions
PbbTlv (void)
virtual ~PbbTlv (void)
void Deserialize (Buffer::Iterator &start)
Deserializes a TLV from the specified buffer.
uint32_t GetSerializedSize (void) const
uint8_t GetType (void) const
uint8_t GetTypeExt (void) const
Buffer GetValue (void) const
bool HasTypeExt (void) const
Tests whether or not this TLV has a type extension.
bool HasValue (void) const
Tests whether or not this TLV has a value.
bool operator!= (const PbbTlv &other) const
Inequality operator for PbbTlv.
bool operator== (const PbbTlv &other) const
Equality operator for PbbTlv.
void Print (std::ostream &os) const
Pretty-prints the contents of this TLV.
void Print (std::ostream &os, int level) const
Pretty-prints the contents of this TLV, with specified indentation.
void Serialize (Buffer::Iterator &start) const
Serializes this TLV into the specified buffer.
void SetType (uint8_t type)
Sets the type of this TLV.
void SetTypeExt (uint8_t type)
Sets the type extension of this TLV.
void SetValue (Buffer start)
Sets the value of this message to the specified buffer.
void SetValue (const uint8_t *buffer, uint32_t size)
Sets the value of this message to a buffer with the specified data.
Public Member Functions inherited from ns3::SimpleRefCount< PbbTlv >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Protected Member Functions
uint8_t GetIndexStart (void) const
Get the starting point index.
uint8_t GetIndexStop (void) const
Get the stop point index.
bool HasIndexStart (void) const
Checks if there is a starting index.
bool HasIndexStop (void) const
Checks if there is a stop index.
bool IsMultivalue (void) const
Check the multivalue parameter.
void SetIndexStart (uint8_t index)
Set an index as starting point.
void SetIndexStop (uint8_t index)
Set an index as stop point.
void SetMultivalue (bool isMultivalue)
Set the multivalue parameter.
Private Attributes
bool m_hasIndexStart
Start index present.
bool m_hasIndexStop
Stop index present.
bool m_hasTypeExt
Extended type present.
bool m_hasValue
Has value.
uint8_t m_indexStart
Start index.
uint8_t m_indexStop
Stop index.
bool m_isMultivalue
Is multivalue.
uint8_t m_type
Type of this TLV.
uint8_t m_typeExt
Extended type.
Buffer m_value
Value.
Detailed Description
A packet or message TLV.
Definition at line 1659 of file packetbb.h.
Constructor & Destructor Documentation
PbbTlv()
ns3::PbbTlv::PbbTlv (void)
Definition at line 2648 of file packetbb.cc.
References m_hasIndexStart, m_hasIndexStop, m_hasTypeExt, m_hasValue, m_isMultivalue, and NS_LOG_FUNCTION.
~PbbTlv()
ns3::PbbTlv::~PbbTlv (void) virtual
Definition at line 2658 of file packetbb.cc.
References ns3::Buffer::GetSize(), m_value, NS_LOG_FUNCTION, and ns3::Buffer::RemoveAtEnd().
Member Function Documentation
Deserialize()
void ns3::PbbTlv::Deserialize (Buffer::Iterator & start)
Deserializes a TLV from the specified buffer.
Parameters
start a reference to the point in a buffer to begin deserializing.
Users should not need to call this. TLVs will be deserialized by their containing blocks.
Definition at line 2889 of file packetbb.cc.
References ns3::Buffer::AddAtStart(), ns3::Buffer::Begin(), m_hasValue, m_value, NS_LOG_FUNCTION, SetIndexStart(), SetIndexStop(), SetType(), SetTypeExt(), visualizer.core::start(), THAS_EXT_LEN, THAS_MULTI_INDEX, THAS_SINGLE_INDEX, THAS_TYPE_EXT, THAS_VALUE, and ns3::Buffer::Iterator::Write().
GetIndexStart()
uint8_t ns3::PbbTlv::GetIndexStart (void) const protected
Get the starting point index.
Returns
the starting index
Definition at line 2710 of file packetbb.cc.
References HasIndexStart(), m_indexStart, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::PbbAddressTlv::GetIndexStart(), Print(), and Serialize().
GetIndexStop()
uint8_t ns3::PbbTlv::GetIndexStop (void) const protected
Get the stop point index.
Returns
the stop index
Definition at line 2733 of file packetbb.cc.
References HasIndexStop(), m_indexStop, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::PbbAddressTlv::GetIndexStop(), Print(), and Serialize().
GetSerializedSize()
uint32_t ns3::PbbTlv::GetSerializedSize (void) const
Returns
The size (in bytes) needed to serialize this TLV.
Definition at line 2794 of file packetbb.cc.
References ns3::GetSize(), ns3::Buffer::GetSize(), GetValue(), HasIndexStart(), HasIndexStop(), HasTypeExt(), HasValue(), and NS_LOG_FUNCTION.
GetType()
uint8_t ns3::PbbTlv::GetType (void) const
Returns
the type of this TLV.
Definition at line 2672 of file packetbb.cc.
References m_type, and NS_LOG_FUNCTION.
Referenced by operator==(), Print(), and Serialize().
GetTypeExt()
uint8_t ns3::PbbTlv::GetTypeExt (void) const
Returns
the type extension for this TLV.
Calling this while HasTypeExt is False is undefined. Make sure you check it first. This will be checked by an assert in debug builds.
Definition at line 2687 of file packetbb.cc.
References HasTypeExt(), m_typeExt, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by operator==(), Print(), and Serialize().
GetValue()
Buffer ns3::PbbTlv::GetValue (void) const
Returns
a Buffer pointing to the value of this TLV.
Calling this while HasValue is False is undefined. Make sure you check it first. This will be checked by an assert in debug builds.
Definition at line 2779 of file packetbb.cc.
References HasValue(), m_value, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by GetSerializedSize(), operator==(), Print(), and Serialize().
HasIndexStart()
bool ns3::PbbTlv::HasIndexStart (void) const protected
Checks if there is a starting index.
Returns
true if the start index has been set
Definition at line 2718 of file packetbb.cc.
References m_hasIndexStart, and NS_LOG_FUNCTION.
Referenced by GetIndexStart(), GetSerializedSize(), ns3::PbbAddressTlv::HasIndexStart(), Print(), and Serialize().
HasIndexStop()
bool ns3::PbbTlv::HasIndexStop (void) const protected
Checks if there is a stop index.
Returns
true if the stop index has been set
Definition at line 2741 of file packetbb.cc.
References m_hasIndexStop, and NS_LOG_FUNCTION.
Referenced by GetIndexStop(), GetSerializedSize(), ns3::PbbAddressTlv::HasIndexStop(), Print(), and Serialize().
HasTypeExt()
bool ns3::PbbTlv::HasTypeExt (void) const
Tests whether or not this TLV has a type extension.
Returns
true if this TLV has a type extension, false otherwise.
This should be called before calling GetTypeExt to make sure there actually is one.
Definition at line 2695 of file packetbb.cc.
References m_hasTypeExt, and NS_LOG_FUNCTION.
Referenced by GetSerializedSize(), GetTypeExt(), operator==(), Print(), and Serialize().
HasValue()
bool ns3::PbbTlv::HasValue (void) const
Tests whether or not this TLV has a value.
Returns
true if this tlv has a TLV, false otherwise.
This should be called before calling GetTypeExt to make sure there actually is one.
Definition at line 2787 of file packetbb.cc.
References m_hasValue, and NS_LOG_FUNCTION.
Referenced by GetSerializedSize(), GetValue(), operator==(), Print(), and Serialize().
IsMultivalue()
bool ns3::PbbTlv::IsMultivalue (void) const protected
Check the multivalue parameter.
Returns
the multivalue status
Definition at line 2755 of file packetbb.cc.
References m_isMultivalue, and NS_LOG_FUNCTION.
Referenced by ns3::PbbAddressTlv::IsMultivalue(), Print(), and Serialize().
operator!=()
bool ns3::PbbTlv::operator!= (const PbbTlv & other) const
Inequality operator for PbbTlv.
Parameters
other PbbTlv to compare to this one
Returns
true if PbbTlv are not equal
Definition at line 3024 of file packetbb.cc.
operator==()
bool ns3::PbbTlv::operator== (const PbbTlv & other) const
Equality operator for PbbTlv.
Parameters
other PbbTlv to compare to this one
Returns
true if PbbTlv are equal
Definition at line 2979 of file packetbb.cc.
References ns3::Buffer::GetSize(), GetType(), GetTypeExt(), GetValue(), HasTypeExt(), HasValue(), and ns3::Buffer::PeekData().
Print() [1/2]
void ns3::PbbTlv::Print (std::ostream & os) const
Pretty-prints the contents of this TLV.
Parameters
os a stream object to print to.
Definition at line 2934 of file packetbb.cc.
References NS_LOG_FUNCTION.
Print() [2/2]
void ns3::PbbTlv::Print (std::ostream & os, int level) const
Pretty-prints the contents of this TLV, with specified indentation.
Parameters
os a stream object to print to.
level level of indentation.
This probably never needs to be called by users. This is used when recursively printing sub-objects.
Definition at line 2941 of file packetbb.cc.
References GetIndexStart(), GetIndexStop(), ns3::Buffer::GetSize(), GetType(), GetTypeExt(), GetValue(), HasIndexStart(), HasIndexStop(), HasTypeExt(), HasValue(), IsMultivalue(), and NS_LOG_FUNCTION.
Serialize()
void ns3::PbbTlv::Serialize (Buffer::Iterator & start) const
Serializes this TLV into the specified buffer.
Parameters
start a reference to the point in a buffer to begin serializing.
Users should not need to call this. TLVs will be serialized by their containing blocks.
Definition at line 2832 of file packetbb.cc.
References GetIndexStart(), GetIndexStop(), ns3::Buffer::GetSize(), GetType(), GetTypeExt(), GetValue(), HasIndexStart(), HasIndexStop(), HasTypeExt(), HasValue(), IsMultivalue(), NS_LOG_FUNCTION, visualizer.core::start(), THAS_EXT_LEN, THAS_MULTI_INDEX, THAS_SINGLE_INDEX, THAS_TYPE_EXT, THAS_VALUE, TIS_MULTIVALUE, and ns3::Buffer::Iterator::WriteU8().
SetIndexStart()
void ns3::PbbTlv::SetIndexStart (uint8_t index) protected
Set an index as starting point.
Parameters
index the starting index
Definition at line 2702 of file packetbb.cc.
References m_hasIndexStart, m_indexStart, and NS_LOG_FUNCTION.
Referenced by Deserialize(), and ns3::PbbAddressTlv::SetIndexStart().
SetIndexStop()
void ns3::PbbTlv::SetIndexStop (uint8_t index) protected
Set an index as stop point.
Parameters
index the stop index
Definition at line 2725 of file packetbb.cc.
References m_hasIndexStop, m_indexStop, and NS_LOG_FUNCTION.
Referenced by Deserialize(), and ns3::PbbAddressTlv::SetIndexStop().
SetMultivalue()
void ns3::PbbTlv::SetMultivalue (bool isMultivalue) protected
Set the multivalue parameter.
Parameters
isMultivalue the multivalue status
Definition at line 2748 of file packetbb.cc.
References m_isMultivalue, and NS_LOG_FUNCTION.
Referenced by ns3::PbbAddressTlv::SetMultivalue().
SetType()
void ns3::PbbTlv::SetType (uint8_t type)
Sets the type of this TLV.
Parameters
type the type value to set.
Definition at line 2665 of file packetbb.cc.
References m_type, and NS_LOG_FUNCTION.
Referenced by PbbTestSuite::PbbTestSuite(), and Deserialize().
SetTypeExt()
void ns3::PbbTlv::SetTypeExt (uint8_t type)
Sets the type extension of this TLV.
Parameters
type the type extension value to set.
The type extension is like a sub-type used to further distinguish between TLVs of the same type.
Definition at line 2679 of file packetbb.cc.
References m_hasTypeExt, m_typeExt, and NS_LOG_FUNCTION.
Referenced by PbbTestSuite::PbbTestSuite(), and Deserialize().
SetValue() [1/2]
void ns3::PbbTlv::SetValue (Buffer start)
Sets the value of this message to the specified buffer.
Parameters
start a buffer instance.
The buffer is not copied until this TLV is serialized. You should not change the contents of the buffer you pass in to this function.
Definition at line 2762 of file packetbb.cc.
References m_hasValue, m_value, NS_LOG_FUNCTION, and visualizer.core::start().
Referenced by PbbTestSuite::PbbTestSuite().
SetValue() [2/2]
void ns3::PbbTlv::SetValue (const uint8_t * buffer, uint32_t size)
Sets the value of this message to a buffer with the specified data.
Parameters
buffer a pointer to data to put in the TLVs buffer.
size the size of the buffer.
The buffer is copied into a new buffer instance. You can free the data in the buffer provided anytime you wish.
Definition at line 2770 of file packetbb.cc.
References ns3::Buffer::AddAtStart(), ns3::Buffer::Begin(), m_hasValue, m_value, NS_LOG_FUNCTION, and ns3::Buffer::Iterator::Write().
Member Data Documentation
m_hasIndexStart
bool ns3::PbbTlv::m_hasIndexStart private
Start index present.
Definition at line 1841 of file packetbb.h.
Referenced by PbbTlv(), HasIndexStart(), and SetIndexStart().
m_hasIndexStop
bool ns3::PbbTlv::m_hasIndexStop private
Stop index present.
Definition at line 1844 of file packetbb.h.
Referenced by PbbTlv(), HasIndexStop(), and SetIndexStop().
m_hasTypeExt
bool ns3::PbbTlv::m_hasTypeExt private
Extended type present.
Definition at line 1838 of file packetbb.h.
Referenced by PbbTlv(), HasTypeExt(), and SetTypeExt().
m_hasValue
bool ns3::PbbTlv::m_hasValue private
Has value.
Definition at line 1848 of file packetbb.h.
Referenced by PbbTlv(), Deserialize(), HasValue(), and SetValue().
m_indexStart
uint8_t ns3::PbbTlv::m_indexStart private
Start index.
Definition at line 1842 of file packetbb.h.
Referenced by GetIndexStart(), and SetIndexStart().
m_indexStop
uint8_t ns3::PbbTlv::m_indexStop private
Stop index.
Definition at line 1845 of file packetbb.h.
Referenced by GetIndexStop(), and SetIndexStop().
m_isMultivalue
bool ns3::PbbTlv::m_isMultivalue private
Is multivalue.
Definition at line 1847 of file packetbb.h.
Referenced by PbbTlv(), IsMultivalue(), and SetMultivalue().
m_type
uint8_t ns3::PbbTlv::m_type private
Type of this TLV.
Definition at line 1836 of file packetbb.h.
Referenced by GetType(), and SetType().
m_typeExt
uint8_t ns3::PbbTlv::m_typeExt private
Extended type.
Definition at line 1839 of file packetbb.h.
Referenced by GetTypeExt(), and SetTypeExt().
m_value
Buffer ns3::PbbTlv::m_value private
Value.
Definition at line 1849 of file packetbb.h.
Referenced by ~PbbTlv(), Deserialize(), GetValue(), and SetValue().
The documentation for this class was generated from the following files:
src/network/utils/packetbb.h
src/network/utils/packetbb.cc