ns-3: ns3::OfdmUlBurstProfile Class Reference
ns3::OfdmUlBurstProfile Class Reference
This class implements the UL burst profile as described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems" 11.3.1.1 Uplink burst profile encodings, page 655.
#include "ul-mac-messages.h"
Public Types
enum Uiuc {
UIUC_INITIAL_RANGING = 1, UIUC_REQ_REGION_FULL, UIUC_REQ_REGION_FOCUSED, UIUC_FOCUSED_CONTENTION_IE,
UIUC_BURST_PROFILE_5, UIUC_BURST_PROFILE_6, UIUC_BURST_PROFILE_7, UIUC_BURST_PROFILE_8,
UIUC_BURST_PROFILE_9, UIUC_BURST_PROFILE_10, UIUC_BURST_PROFILE_11, UIUC_BURST_PROFILE_12,
UIUC_SUBCH_NETWORK_ENTRY, UIUC_END_OF_MAP
}
UIUC enumeraton.
Public Member Functions
OfdmUlBurstProfile (void)
~OfdmUlBurstProfile (void)
uint8_t GetFecCodeType (void) const
Get FEC code type.
uint8_t GetLength (void) const
Get length.
uint16_t GetSize (void) const
Get size.
uint8_t GetType (void) const
Get type.
uint8_t GetUiuc (void) const
Get UIUC.
Buffer::Iterator Read (Buffer::Iterator start)
Read item.
void SetFecCodeType (uint8_t fecCodeType)
Set FEC code type.
void SetLength (uint8_t length)
Set length.
void SetType (uint8_t type)
Set type.
void SetUiuc (uint8_t uiuc)
Set UIUC.
Buffer::Iterator Write (Buffer::Iterator start) const
Write item.
Private Attributes
uint8_t m_fecCodeType
FEC code type.
uint8_t m_length
length
uint8_t m_type
type
uint8_t m_uiuc
UIUC.
Detailed Description
This class implements the UL burst profile as described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems" 11.3.1.1 Uplink burst profile encodings, page 655.
Definition at line 203 of file ul-mac-messages.h.
Member Enumeration Documentation
Uiuc
enum ns3::OfdmUlBurstProfile::Uiuc
UIUC enumeraton.
Enumerator
UIUC_INITIAL_RANGING
UIUC_REQ_REGION_FULL
UIUC_REQ_REGION_FOCUSED
UIUC_FOCUSED_CONTENTION_IE
UIUC_BURST_PROFILE_5
UIUC_BURST_PROFILE_6
UIUC_BURST_PROFILE_7
UIUC_BURST_PROFILE_8
UIUC_BURST_PROFILE_9
UIUC_BURST_PROFILE_10
UIUC_BURST_PROFILE_11
UIUC_BURST_PROFILE_12
UIUC_SUBCH_NETWORK_ENTRY
UIUC_END_OF_MAP
Definition at line 207 of file ul-mac-messages.h.
Constructor & Destructor Documentation
OfdmUlBurstProfile()
ns3::OfdmUlBurstProfile::OfdmUlBurstProfile (void)
Definition at line 166 of file ul-mac-messages.cc.
~OfdmUlBurstProfile()
ns3::OfdmUlBurstProfile::~OfdmUlBurstProfile (void)
Definition at line 174 of file ul-mac-messages.cc.
Member Function Documentation
GetFecCodeType()
uint8_t ns3::OfdmUlBurstProfile::GetFecCodeType (void) const
Get FEC code type.
Returns
the FEC code type
Definition at line 221 of file ul-mac-messages.cc.
References m_fecCodeType.
Referenced by ns3::SubscriberStationNetDevice::ProcessUcd().
GetLength()
uint8_t ns3::OfdmUlBurstProfile::GetLength (void) const
Get length.
Returns
the length
Definition at line 209 of file ul-mac-messages.cc.
References m_length.
GetSize()
uint16_t ns3::OfdmUlBurstProfile::GetSize (void) const
Get size.
Returns
the size
Definition at line 227 of file ul-mac-messages.cc.
Referenced by ns3::Ucd::GetSerializedSize().
GetType()
uint8_t ns3::OfdmUlBurstProfile::GetType (void) const
Get type.
Returns
the type
Definition at line 203 of file ul-mac-messages.cc.
References m_type.
GetUiuc()
uint8_t ns3::OfdmUlBurstProfile::GetUiuc (void) const
Get UIUC.
Returns
the UIUC
Definition at line 215 of file ul-mac-messages.cc.
References m_uiuc.
Referenced by ns3::SubscriberStationNetDevice::ProcessUcd().
Read()
Buffer::Iterator ns3::OfdmUlBurstProfile::Read (Buffer::Iterator start)
Read item.
Parameters
start the iterator
Returns
the updated iterator
Definition at line 244 of file ul-mac-messages.cc.
References m_fecCodeType, m_length, m_type, m_uiuc, ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
Referenced by ns3::Ucd::Deserialize().
SetFecCodeType()
void ns3::OfdmUlBurstProfile::SetFecCodeType (uint8_t fecCodeType)
Set FEC code type.
Parameters
fecCodeType the FEC code type
Definition at line 197 of file ul-mac-messages.cc.
References m_fecCodeType.
Referenced by ns3::SubscriberStationNetDevice::ProcessUcd(), and ns3::BaseStationNetDevice::SetUlBurstProfiles().
SetLength()
void ns3::OfdmUlBurstProfile::SetLength (uint8_t length)
Set length.
Parameters
length the length
Definition at line 185 of file ul-mac-messages.cc.
References m_length.
Referenced by ns3::BaseStationNetDevice::SetUlBurstProfiles().
SetType()
void ns3::OfdmUlBurstProfile::SetType (uint8_t type)
Set type.
Parameters
type the type
Definition at line 179 of file ul-mac-messages.cc.
References m_type.
Referenced by ns3::BaseStationNetDevice::SetUlBurstProfiles().
SetUiuc()
void ns3::OfdmUlBurstProfile::SetUiuc (uint8_t uiuc)
Set UIUC.
Parameters
uiuc the UIUC
Definition at line 191 of file ul-mac-messages.cc.
References m_uiuc.
Referenced by ns3::SubscriberStationNetDevice::ProcessUcd(), and ns3::BaseStationNetDevice::SetUlBurstProfiles().
Write()
Buffer::Iterator ns3::OfdmUlBurstProfile::Write (Buffer::Iterator start) const
Write item.
Parameters
start the iterator
Returns
the updated iterator
Definition at line 233 of file ul-mac-messages.cc.
References m_fecCodeType, m_length, m_type, m_uiuc, visualizer.core::start(), and ns3::Buffer::Iterator::WriteU8().
Referenced by ns3::Ucd::Serialize().
Member Data Documentation
m_fecCodeType
uint8_t ns3::OfdmUlBurstProfile::m_fecCodeType private
FEC code type.
Definition at line 294 of file ul-mac-messages.h.
Referenced by GetFecCodeType(), Read(), SetFecCodeType(), and Write().
m_length
uint8_t ns3::OfdmUlBurstProfile::m_length private
length
Definition at line 290 of file ul-mac-messages.h.
Referenced by GetLength(), Read(), SetLength(), and Write().
m_type
uint8_t ns3::OfdmUlBurstProfile::m_type private
type
Definition at line 289 of file ul-mac-messages.h.
Referenced by GetType(), Read(), SetType(), and Write().
m_uiuc
uint8_t ns3::OfdmUlBurstProfile::m_uiuc private
UIUC.
Definition at line 291 of file ul-mac-messages.h.
Referenced by GetUiuc(), Read(), SetUiuc(), and Write().
The documentation for this class was generated from the following files:
src/wimax/model/ul-mac-messages.h
src/wimax/model/ul-mac-messages.cc