ns-3: ns3::SimpleChannel Class Reference
ns3::SimpleChannel Class Reference
Network » Channel
A simple channel, for simple things and testing.
#include "simple-channel.h"
Public Member Functions
SimpleChannel ()
virtual void Add (Ptr< SimpleNetDevice > device)
Attached a net device to the channel.
virtual void BlackList (Ptr< SimpleNetDevice > from, Ptr< SimpleNetDevice > to)
Blocks the communications from a NetDevice to another NetDevice.
virtual Ptr< NetDevice > GetDevice (std::size_t i) const
virtual std::size_t GetNDevices (void) const
virtual void Send (Ptr< Packet > p, uint16_t protocol, Mac48Address to, Mac48Address from, Ptr< SimpleNetDevice > sender)
A packet is sent by a net device.
virtual void UnBlackList (Ptr< SimpleNetDevice > from, Ptr< SimpleNetDevice > to)
Un-Blocks the communications from a NetDevice to another NetDevice.
Public Member Functions inherited from ns3::Channel
Channel ()
virtual ~Channel ()
uint32_t GetId (void) const
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Channel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
std::map< Ptr< SimpleNetDevice >, std::vector< Ptr< SimpleNetDevice > > > m_blackListedDevices
devices blocked on a device
Time m_delay
The assigned speed-of-light delay of the channel.
std::vector< Ptr< SimpleNetDevice > > m_devices
devices connected by the channel
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A simple channel, for simple things and testing.
This channel doesn't check for packet collisions and it does not introduce any error. By default, it does not add any delay to the packets. Furthermore, it assumes that the associated NetDevices are using 48-bit MAC addresses.
This channel is meant to be used by ns3::SimpleNetDevices.
Definition at line 46 of file simple-channel.h.
Constructor & Destructor Documentation
SimpleChannel()
ns3::SimpleChannel::SimpleChannel ()
Definition at line 49 of file simple-channel.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Add()
void ns3::SimpleChannel::Add (Ptr< SimpleNetDevice > device) virtual
Attached a net device to the channel.
Parameters
device the device to attach to the channel
Reimplemented in ns3::ErrorChannel.
Definition at line 81 of file simple-channel.cc.
References m_devices, and NS_LOG_FUNCTION.
BlackList()
void ns3::SimpleChannel::BlackList (Ptr< SimpleNetDevice > from, Ptr< SimpleNetDevice > to) virtual
Blocks the communications from a NetDevice to another NetDevice.
The block is unidirectional
Parameters
from the device to BlackList
to the device wanting to block the other one
Definition at line 102 of file simple-channel.cc.
References m_blackListedDevices.
Referenced by ns3::olsr::Bug780Test::CreateNodes().
GetDevice()
Ptr< NetDevice > ns3::SimpleChannel::GetDevice (std::size_t i) const virtual
Parameters
i index of NetDevice to retrieve
Returns
one of the NetDevices connected to this channel.
This method must be implemented by subclasses.
Implements ns3::Channel.
Reimplemented in ns3::ErrorChannel.
Definition at line 95 of file simple-channel.cc.
References m_devices, and NS_LOG_FUNCTION.
GetNDevices()
std::size_t ns3::SimpleChannel::GetNDevices (void) const virtual
Returns
the number of NetDevices connected to this Channel.
This method must be implemented by subclasses.
Implements ns3::Channel.
Reimplemented in ns3::ErrorChannel.
Definition at line 88 of file simple-channel.cc.
References m_devices, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::SimpleChannel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 35 of file simple-channel.cc.
References m_delay, ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::Seconds(), and ns3::TypeId::SetParent().
Send()
void ns3::SimpleChannel::Send (Ptr< Packet > p, uint16_t protocol, Mac48Address to, Mac48Address from, Ptr< SimpleNetDevice > sender) virtual
A packet is sent by a net device.
A receive event will be scheduled for all net device connected to the channel other than the net device who sent the packet
Parameters
p packet to be sent
protocol protocol number
to address to send packet to
from address the packet is coming from
sender netdevice who sent the packet
Reimplemented in ns3::ErrorChannel.
Definition at line 55 of file simple-channel.cc.
References ns3::Packet::Copy(), m_blackListedDevices, m_delay, m_devices, NS_LOG_FUNCTION, ns3::SimpleNetDevice::Receive(), and ns3::Simulator::ScheduleWithContext().
UnBlackList()
void ns3::SimpleChannel::UnBlackList (Ptr< SimpleNetDevice > from, Ptr< SimpleNetDevice > to) virtual
Un-Blocks the communications from a NetDevice to another NetDevice.
The block is unidirectional
Parameters
from the device to BlackList
to the device wanting to block the other one
Definition at line 119 of file simple-channel.cc.
References m_blackListedDevices.
Member Data Documentation
m_blackListedDevices
std::map<Ptr<SimpleNetDevice>, std::vector<Ptr<SimpleNetDevice> > > ns3::SimpleChannel::m_blackListedDevices private
devices blocked on a device
Definition at line 103 of file simple-channel.h.
Referenced by BlackList(), Send(), and UnBlackList().
m_delay
Time ns3::SimpleChannel::m_delay private
The assigned speed-of-light delay of the channel.
Definition at line 101 of file simple-channel.h.
Referenced by GetTypeId(), and Send().
m_devices
std::vector<Ptr<SimpleNetDevice> > ns3::SimpleChannel::m_devices private
devices connected by the channel
Definition at line 102 of file simple-channel.h.
Referenced by Add(), GetDevice(), GetNDevices(), and Send().
The documentation for this class was generated from the following files:
src/network/utils/simple-channel.h
src/network/utils/simple-channel.cc