ns-3: LrWpanAckTestCase Class Reference
LrWpanAckTestCase Class Reference
LR-WPAN models » LrWpan module tests | Test suites
LrWpan ACK Test.
Public Member Functions
LrWpanAckTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Static Public Member Functions
static void DataConfirm (LrWpanAckTestCase *testCase, Ptr< LrWpanNetDevice > dev, McpsDataConfirmParams params)
Function called when DataConfirm is hit.
static void DataIndication (LrWpanAckTestCase *testCase, Ptr< LrWpanNetDevice > dev, McpsDataIndicationParams params, Ptr< Packet > p)
Function called when DataIndication is hit.
static void ExtendedAddressingDataConfirm (LrWpanAckTestCase *testCase, Ptr< LrWpanNetDevice > dev, McpsDataConfirmParams params)
Function called when DataConfirm is hit in extended addressing test.
static void ExtendedAddressingDataIndication (LrWpanAckTestCase *testCase, Ptr< LrWpanNetDevice > dev, McpsDataIndicationParams params, Ptr< Packet > p)
Function called when DataIndication is hit in extended addressing test.
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
Time m_replyAckTime
Reply ack time.
Time m_replyArrivalTime
Reply arrival time.
Time m_replyTime
Reply time.
Time m_requestAckTime
Request ack time.
Time m_requestTime
Request time.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
LrWpan ACK Test.
Definition at line 50 of file lr-wpan-ack-test.cc.
Constructor & Destructor Documentation
LrWpanAckTestCase()
LrWpanAckTestCase::LrWpanAckTestCase ()
Definition at line 96 of file lr-wpan-ack-test.cc.
References m_replyAckTime, m_replyArrivalTime, m_replyTime, m_requestAckTime, m_requestTime, and ns3::Seconds().
Member Function Documentation
DataConfirm()
void LrWpanAckTestCase::DataConfirm (LrWpanAckTestCase * testCase, Ptr< LrWpanNetDevice > dev, McpsDataConfirmParams params) static
Function called when DataConfirm is hit.
Parameters
testCase The TestCase.
dev The LrWpanNetDevice.
params The MCPS params.
Definition at line 130 of file lr-wpan-ack-test.cc.
References ns3::LrWpanNetDevice::GetMac(), m_replyAckTime, m_requestAckTime, and ns3::Now().
Referenced by DoRun().
DataIndication()
void LrWpanAckTestCase::DataIndication (LrWpanAckTestCase * testCase, Ptr< LrWpanNetDevice > dev, McpsDataIndicationParams params, Ptr< Packet > p) static
Function called when DataIndication is hit.
Parameters
testCase The TestCase.
dev The LrWpanNetDevice.
params The MCPS params.
p the packet.
Definition at line 107 of file lr-wpan-ack-test.cc.
References ns3::LrWpanNetDevice::GetMac(), m_replyArrivalTime, m_replyTime, ns3::Now(), aloha::params, ns3::SHORT_ADDR, and ns3::TX_OPTION_NONE.
Referenced by DoRun().
DoRun()
void LrWpanAckTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 179 of file lr-wpan-ack-test.cc.
References ns3::Node::AddDevice(), ns3::LrWpanNetDevice::AssignStreams(), third::channel, DataConfirm(), DataIndication(), ns3::EXT_ADDR, ExtendedAddressingDataConfirm(), ExtendedAddressingDataIndication(), ns3::LrWpanNetDevice::GetMac(), ns3::LrWpanNetDevice::GetPhy(), m_replyAckTime, m_replyArrivalTime, m_replyTime, m_requestAckTime, m_requestTime, ns3::MakeBoundCallback(), ns3::Now(), NS_TEST_EXPECT_MSG_LT, aloha::params, ns3::Seconds(), ns3::LrWpanNetDevice::SetAddress(), ns3::LrWpanNetDevice::SetChannel(), ns3::MobilityModel::SetPosition(), ns3::SHORT_ADDR, and ns3::TX_OPTION_ACK.
ExtendedAddressingDataConfirm()
void LrWpanAckTestCase::ExtendedAddressingDataConfirm (LrWpanAckTestCase * testCase, Ptr< LrWpanNetDevice > dev, McpsDataConfirmParams params) static
Function called when DataConfirm is hit in extended addressing test.
Parameters
testCase The TestCase.
dev The LrWpanNetDevice.
params The MCPS params.
Definition at line 166 of file lr-wpan-ack-test.cc.
References ns3::LrWpanNetDevice::GetMac(), m_replyAckTime, m_requestAckTime, and ns3::Now().
Referenced by DoRun().
ExtendedAddressingDataIndication()
void LrWpanAckTestCase::ExtendedAddressingDataIndication (LrWpanAckTestCase * testCase, Ptr< LrWpanNetDevice > dev, McpsDataIndicationParams params, Ptr< Packet > p) static
Function called when DataIndication is hit in extended addressing test.
Parameters
testCase The TestCase.
dev The LrWpanNetDevice.
params The MCPS params.
p the packet.
Definition at line 143 of file lr-wpan-ack-test.cc.
References ns3::EXT_ADDR, ns3::LrWpanNetDevice::GetMac(), m_replyArrivalTime, m_replyTime, ns3::Now(), aloha::params, and ns3::TX_OPTION_NONE.
Referenced by DoRun().
Member Data Documentation
m_replyAckTime
Time LrWpanAckTestCase::m_replyAckTime private
Reply ack time.
Definition at line 92 of file lr-wpan-ack-test.cc.
Referenced by LrWpanAckTestCase(), DataConfirm(), DoRun(), and ExtendedAddressingDataConfirm().
m_replyArrivalTime
Time LrWpanAckTestCase::m_replyArrivalTime private
Reply arrival time.
Definition at line 93 of file lr-wpan-ack-test.cc.
Referenced by LrWpanAckTestCase(), DataIndication(), DoRun(), and ExtendedAddressingDataIndication().
m_replyTime
Time LrWpanAckTestCase::m_replyTime private
Reply time.
Definition at line 91 of file lr-wpan-ack-test.cc.
Referenced by LrWpanAckTestCase(), DataIndication(), DoRun(), and ExtendedAddressingDataIndication().
m_requestAckTime
Time LrWpanAckTestCase::m_requestAckTime private
Request ack time.
Definition at line 90 of file lr-wpan-ack-test.cc.
Referenced by LrWpanAckTestCase(), DataConfirm(), DoRun(), and ExtendedAddressingDataConfirm().
m_requestTime
Time LrWpanAckTestCase::m_requestTime private
Request time.
Definition at line 89 of file lr-wpan-ack-test.cc.
Referenced by LrWpanAckTestCase(), and DoRun().
The documentation for this class was generated from the following file:
src/lr-wpan/test/lr-wpan-ack-test.cc