ns-3: ns3::ThreeGppAntennaArrayModel Class Reference
ns3::ThreeGppAntennaArrayModel Class Reference
Class implementing the antenna model defined in 3GPP TR 38.901 V15.0.0.
#include "three-gpp-antenna-array-model.h"
Public Types
typedef std::vector< std::complex< double > > ComplexVector
type definition for complex vectors
Public Member Functions
ThreeGppAntennaArrayModel (void)
Constructor.
virtual ~ThreeGppAntennaArrayModel (void)
Destructor.
void ChangeToOmniTx (void)
Change the antenna model to omnidirectional (ignoring the beams)
const ComplexVector & GetBeamformingVector (void) const
Returns the beamforming vector that is currently being used.
std::pair< double, double > GetElementFieldPattern (Angles a) const
Returns the horizontal and vertical components of the antenna element field pattern at the specified direction.
virtual Vector GetElementLocation (uint64_t index) const
Returns the location of the antenna element with the specified index assuming the left bottom corner is (0,0,0), normalized with respect to the wavelength.
virtual uint64_t GetNumberOfElements (void) const
Returns the number of antenna elements.
bool IsOmniTx (void) const
Returns true if the antenna is configured for omnidirectional transmissions.
void SetBeamformingVector (const ComplexVector &beamformingVector)
Sets the beamforming vector to be used.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
double GetRadiationPattern (double vAngleRadian, double hAngleRadian) const
Returns the radiation power pattern of a single antenna element in dB, generated according to Table 7.3-1 in 3GPP TR 38.901.
Private Attributes
double m_alpha
the bearing angle in radians
ComplexVector m_beamformingVector
the beamforming vector in use
double m_beta
the downtilt angle in radians
double m_disH
antenna spacing in the horizontal direction in multiples of wave length
double m_disV
antenna spacing in the vertical direction in multiples of wave length
double m_gE
directional gain of a single antenna element (dBi)
bool m_isIsotropic
if true, antenna elements are isotropic
bool m_isOmniTx
true if the antenna is configured for omni transmissions
uint32_t m_numColumns
number of columns
uint32_t m_numRows
number of rows
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Class implementing the antenna model defined in 3GPP TR 38.901 V15.0.0.
Note
the current implementation supports the modeling of antenna arrays composed of a single panel and with single (vertical) polarization.
Definition at line 37 of file three-gpp-antenna-array-model.h.
Member Typedef Documentation
ComplexVector
typedef std::vector<std::complex<double> > ns3::ThreeGppAntennaArrayModel::ComplexVector
type definition for complex vectors
Definition at line 54 of file three-gpp-antenna-array-model.h.
Constructor & Destructor Documentation
ThreeGppAntennaArrayModel()
ns3::ThreeGppAntennaArrayModel::ThreeGppAntennaArrayModel (void)
Constructor.
Definition at line 33 of file three-gpp-antenna-array-model.cc.
References m_isOmniTx, and NS_LOG_FUNCTION.
~ThreeGppAntennaArrayModel()
ns3::ThreeGppAntennaArrayModel::~ThreeGppAntennaArrayModel (void) virtual
Destructor.
Definition at line 39 of file three-gpp-antenna-array-model.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
ChangeToOmniTx()
void ns3::ThreeGppAntennaArrayModel::ChangeToOmniTx (void)
Change the antenna model to omnidirectional (ignoring the beams)
Definition at line 102 of file three-gpp-antenna-array-model.cc.
References m_isOmniTx, and NS_LOG_FUNCTION.
GetBeamformingVector()
const ThreeGppAntennaArrayModel::ComplexVector & ns3::ThreeGppAntennaArrayModel::GetBeamformingVector (void) const
Returns the beamforming vector that is currently being used.
Returns
the current beamforming vector
Definition at line 117 of file three-gpp-antenna-array-model.cc.
References m_beamformingVector, and NS_LOG_FUNCTION.
Referenced by ThreeGppSpectrumPropagationLossModelTest::DoRun().
GetElementFieldPattern()
std::pair< double, double > ns3::ThreeGppAntennaArrayModel::GetElementFieldPattern (Angles a) const
Returns the horizontal and vertical components of the antenna element field pattern at the specified direction.
Only vertical polarization is considered.
Parameters
a the angle indicating the interested direction
Returns
a pair in which the first element is the horizontal component of the field pattern and the second element is the vertical component of the field pattern
Definition at line 124 of file three-gpp-antenna-array-model.cc.
References GetRadiationPattern(), m_alpha, m_beta, NS_ASSERT_MSG(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Angles::phi, and ns3::Angles::theta.
GetElementLocation()
Vector ns3::ThreeGppAntennaArrayModel::GetElementLocation (uint64_t index) const virtual
Returns the location of the antenna element with the specified index assuming the left bottom corner is (0,0,0), normalized with respect to the wavelength.
Antenna elements are scanned row by row, left to right and bottom to top. For example, an antenna with 2 rows and 3 columns will be ordered as follows: ^ z | 3 4 5 | 0 1 2 -------—> y
Parameters
index index of the antenna element
Returns
the 3D vector that represents the position of the element
Definition at line 195 of file three-gpp-antenna-array-model.cc.
References m_alpha, m_beta, m_disH, m_disV, m_numColumns, and NS_LOG_FUNCTION.
Referenced by DoBeamforming(), and ThreeGppSpectrumPropagationLossModelTest::DoBeamforming().
GetNumberOfElements()
uint64_t ns3::ThreeGppAntennaArrayModel::GetNumberOfElements (void) const virtual
Returns the number of antenna elements.
Returns
the number of antenna elements
Definition at line 215 of file three-gpp-antenna-array-model.cc.
References m_numColumns, m_numRows, and NS_LOG_FUNCTION.
Referenced by DoBeamforming(), ThreeGppSpectrumPropagationLossModelTest::DoBeamforming(), and ThreeGppChannelMatrixComputationTest::DoComputeNorm().
GetRadiationPattern()
double ns3::ThreeGppAntennaArrayModel::GetRadiationPattern (double vAngleRadian, double hAngleRadian) const private
Returns the radiation power pattern of a single antenna element in dB, generated according to Table 7.3-1 in 3GPP TR 38.901.
Parameters
vAngleRadian the vertical angle in radians
hAngleRadian the horizontal angle in radians
Returns
the radiation power pattern in dB
Definition at line 168 of file three-gpp-antenna-array-model.cc.
References m_gE, m_isIsotropic, min, and NS_ASSERT_MSG().
Referenced by GetElementFieldPattern().
GetTypeId()
TypeId ns3::ThreeGppAntennaArrayModel::GetTypeId (void) static
Definition at line 45 of file three-gpp-antenna-array-model.cc.
References m_alpha, m_beta, m_disH, m_disV, m_gE, m_isIsotropic, m_numColumns, m_numRows, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeDoubleAccessor(), ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
IsOmniTx()
bool ns3::ThreeGppAntennaArrayModel::IsOmniTx (void) const
Returns true if the antenna is configured for omnidirectional transmissions.
Returns
whether the transmission is set to omni
Definition at line 95 of file three-gpp-antenna-array-model.cc.
References m_isOmniTx, and NS_LOG_FUNCTION.
SetBeamformingVector()
void ns3::ThreeGppAntennaArrayModel::SetBeamformingVector (const ComplexVector & beamformingVector)
Sets the beamforming vector to be used.
Parameters
beamformingVector the beamforming vector
Definition at line 109 of file three-gpp-antenna-array-model.cc.
References m_beamformingVector, m_isOmniTx, and NS_LOG_FUNCTION.
Referenced by DoBeamforming(), ThreeGppSpectrumPropagationLossModelTest::DoBeamforming(), and ThreeGppSpectrumPropagationLossModelTest::DoRun().
Member Data Documentation
m_alpha
double ns3::ThreeGppAntennaArrayModel::m_alpha private
the bearing angle in radians
Definition at line 127 of file three-gpp-antenna-array-model.h.
Referenced by GetElementFieldPattern(), GetElementLocation(), and GetTypeId().
m_beamformingVector
ComplexVector ns3::ThreeGppAntennaArrayModel::m_beamformingVector private
the beamforming vector in use
Definition at line 122 of file three-gpp-antenna-array-model.h.
Referenced by GetBeamformingVector(), and SetBeamformingVector().
m_beta
double ns3::ThreeGppAntennaArrayModel::m_beta private
the downtilt angle in radians
Definition at line 128 of file three-gpp-antenna-array-model.h.
Referenced by GetElementFieldPattern(), GetElementLocation(), and GetTypeId().
m_disH
double ns3::ThreeGppAntennaArrayModel::m_disH private
antenna spacing in the horizontal direction in multiples of wave length
Definition at line 126 of file three-gpp-antenna-array-model.h.
Referenced by GetElementLocation(), and GetTypeId().
m_disV
double ns3::ThreeGppAntennaArrayModel::m_disV private
antenna spacing in the vertical direction in multiples of wave length
Definition at line 125 of file three-gpp-antenna-array-model.h.
Referenced by GetElementLocation(), and GetTypeId().
m_gE
double ns3::ThreeGppAntennaArrayModel::m_gE private
directional gain of a single antenna element (dBi)
Definition at line 129 of file three-gpp-antenna-array-model.h.
Referenced by GetRadiationPattern(), and GetTypeId().
m_isIsotropic
bool ns3::ThreeGppAntennaArrayModel::m_isIsotropic private
if true, antenna elements are isotropic
Definition at line 130 of file three-gpp-antenna-array-model.h.
Referenced by GetRadiationPattern(), and GetTypeId().
m_isOmniTx
bool ns3::ThreeGppAntennaArrayModel::m_isOmniTx private
true if the antenna is configured for omni transmissions
Definition at line 121 of file three-gpp-antenna-array-model.h.
Referenced by ThreeGppAntennaArrayModel(), ChangeToOmniTx(), IsOmniTx(), and SetBeamformingVector().
m_numColumns
uint32_t ns3::ThreeGppAntennaArrayModel::m_numColumns private
number of columns
Definition at line 123 of file three-gpp-antenna-array-model.h.
Referenced by GetElementLocation(), GetNumberOfElements(), and GetTypeId().
m_numRows
uint32_t ns3::ThreeGppAntennaArrayModel::m_numRows private
number of rows
Definition at line 124 of file three-gpp-antenna-array-model.h.
Referenced by GetNumberOfElements(), and GetTypeId().
The documentation for this class was generated from the following files:
src/antenna/model/three-gpp-antenna-array-model.h
src/antenna/model/three-gpp-antenna-array-model.cc