ns-3: ns3::HtConfiguration Class Reference
ns3::HtConfiguration Class Reference
Wifi Models
HT configuration.
#include "ht-configuration.h"
Public Member Functions
HtConfiguration ()
virtual ~HtConfiguration ()
bool GetGreenfieldSupported (void) const
bool GetRifsSupported (void) const
bool GetShortGuardIntervalSupported (void) const
void SetGreenfieldSupported (bool enable)
Enable or disable Greenfield support.
void SetRifsSupported (bool enable)
Enable or disable RIFS support.
void SetShortGuardIntervalSupported (bool enable)
Enable or disable SGI support.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
bool m_greenfieldSupported
flag whether Greenfield is supported
bool m_rifsSupported
flag whether RIFS is supported
bool m_sgiSupported
flag whether short guard interval is supported
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
HT configuration.
This object stores HT configuration information, for use in modifying AP or STA behavior and for constructing HT-related information elements.
Definition at line 36 of file ht-configuration.h.
Constructor & Destructor Documentation
HtConfiguration()
ns3::HtConfiguration::HtConfiguration ()
Definition at line 32 of file ht-configuration.cc.
References NS_LOG_FUNCTION.
~HtConfiguration()
ns3::HtConfiguration::~HtConfiguration () virtual
Definition at line 37 of file ht-configuration.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
GetGreenfieldSupported()
bool ns3::HtConfiguration::GetGreenfieldSupported (void) const
Returns
whether the device supports Greenfield.
true if Greenfield is supported, false otherwise.
Definition at line 92 of file ht-configuration.cc.
References m_greenfieldSupported.
Referenced by GetTypeId().
GetRifsSupported()
bool ns3::HtConfiguration::GetRifsSupported (void) const
Returns
whether the device supports RIFS capability.
true if short RIFS is supported, false otherwise.
Definition at line 105 of file ht-configuration.cc.
References m_rifsSupported.
Referenced by GetTypeId().
GetShortGuardIntervalSupported()
bool ns3::HtConfiguration::GetShortGuardIntervalSupported (void) const
Returns
whether the device supports SGI.
true if SGI is supported, false otherwise.
Definition at line 79 of file ht-configuration.cc.
References m_sgiSupported.
Referenced by ns3::ConvertGuardIntervalToNanoSeconds(), and GetTypeId().
GetTypeId()
TypeId ns3::HtConfiguration::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 43 of file ht-configuration.cc.
References GetGreenfieldSupported(), GetRifsSupported(), GetShortGuardIntervalSupported(), ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), SetGreenfieldSupported(), ns3::TypeId::SetParent(), SetRifsSupported(), and SetShortGuardIntervalSupported().
SetGreenfieldSupported()
void ns3::HtConfiguration::SetGreenfieldSupported (bool enable)
Enable or disable Greenfield support.
Parameters
enable true if Greenfield is to be supported, false otherwise
Definition at line 85 of file ht-configuration.cc.
References m_greenfieldSupported, and NS_LOG_FUNCTION.
Referenced by GetTypeId(), and Experiment::Run().
SetRifsSupported()
void ns3::HtConfiguration::SetRifsSupported (bool enable)
Enable or disable RIFS support.
Parameters
enable true if RIFS is to be supported, false otherwise
Definition at line 98 of file ht-configuration.cc.
References m_rifsSupported, and NS_LOG_FUNCTION.
Referenced by GetTypeId(), and Experiment::Run().
SetShortGuardIntervalSupported()
void ns3::HtConfiguration::SetShortGuardIntervalSupported (bool enable)
Enable or disable SGI support.
Parameters
enable true if SGI is to be supported, false otherwise
Definition at line 72 of file ht-configuration.cc.
References m_sgiSupported, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
Member Data Documentation
m_greenfieldSupported
bool ns3::HtConfiguration::m_greenfieldSupported private
flag whether Greenfield is supported
Definition at line 95 of file ht-configuration.h.
Referenced by GetGreenfieldSupported(), and SetGreenfieldSupported().
m_rifsSupported
bool ns3::HtConfiguration::m_rifsSupported private
flag whether RIFS is supported
Definition at line 94 of file ht-configuration.h.
Referenced by GetRifsSupported(), and SetRifsSupported().
m_sgiSupported
bool ns3::HtConfiguration::m_sgiSupported private
flag whether short guard interval is supported
Definition at line 93 of file ht-configuration.h.
Referenced by GetShortGuardIntervalSupported(), and SetShortGuardIntervalSupported().
The documentation for this class was generated from the following files:
src/wifi/model/ht-configuration.h
src/wifi/model/ht-configuration.cc