ns-3: TwoLinkTest Class Reference
TwoLinkTest Class Reference
Internet » internet module tests | Test suites
IPv4 GlobalRouting Two Link test.
Public Member Functions
TwoLinkTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
virtual void DoSetup (void)
Implementation to do any local setup required for this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Attributes
NodeContainer m_nodes
Nodes used in the test.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
IPv4 GlobalRouting Two Link test.
Definition at line 291 of file ipv4-global-routing-test-suite.cc.
Constructor & Destructor Documentation
TwoLinkTest()
TwoLinkTest::TwoLinkTest ()
Definition at line 301 of file ipv4-global-routing-test-suite.cc.
Member Function Documentation
DoRun()
void TwoLinkTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 338 of file ipv4-global-routing-test-suite.cc.
References ns3::NodeContainer::Get(), ns3::Ipv4RoutingTableEntry::GetDest(), ns3::Ipv4RoutingTableEntry::GetGateway(), ns3::Ipv4GlobalRouting::GetNRoutes(), ns3::Object::GetObject(), ns3::Ipv4GlobalRouting::GetRoute(), ns3::Ipv4L3Protocol::GetRoutingProtocol(), m_nodes, NS_LOG_DEBUG, NS_TEST_ASSERT_MSG_EQ, and NS_TEST_ASSERT_MSG_NE.
DoSetup()
void TwoLinkTest::DoSetup (void) virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test setup before DoRun is invoked.
Reimplemented from ns3::TestCase.
Definition at line 307 of file ipv4-global-routing-test-suite.cc.
References ns3::NetDeviceContainer::Add(), ns3::Ipv4AddressHelper::Assign(), third::channel, ns3::NodeContainer::Create(), ns3::NodeContainer::Get(), ns3::SimpleNetDeviceHelper::Install(), ns3::InternetStackHelper::Install(), m_nodes, ns3::Ipv4AddressHelper::SetBase(), ns3::SimpleNetDeviceHelper::SetNetDevicePointToPointMode(), and ns3::InternetStackHelper::SetRoutingHelper().
Member Data Documentation
m_nodes
NodeContainer TwoLinkTest::m_nodes private
Nodes used in the test.
Definition at line 298 of file ipv4-global-routing-test-suite.cc.
Referenced by DoRun(), and DoSetup().
The documentation for this class was generated from the following file:
src/internet/test/ipv4-global-routing-test-suite.cc