ns-3: ns3::UanPhyCalcSinrFhFsk Class Reference
ns3::UanPhyCalcSinrFhFsk Class Reference
UAN Models
#include "uan-phy-gen.h"
Public Member Functions
UanPhyCalcSinrFhFsk ()
Constructor.
virtual ~UanPhyCalcSinrFhFsk ()
Destructor.
virtual double CalcSinrDb (Ptr< Packet > pkt, Time arrTime, double rxPowerDb, double ambNoiseDb, UanTxMode mode, UanPdp pdp, const UanTransducer::ArrivalList &arrivalList) const
Calculate the SINR value for a packet.
Public Member Functions inherited from ns3::UanPhyCalcSinr
virtual void Clear (void)
Clear all pointer references.
double DbToKp (double db) const
Convert dB re 1 uPa to kilopascals.
double KpToDb (double kp) const
Convert kilopascals to dB re 1 uPa.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::UanPhyCalcSinr
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint32_t m_hops
Number of hops.
Additional Inherited Members
Protected Member Functions inherited from ns3::UanPhyCalcSinr
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
WHOI Micromodem like FH-FSK model.
Model of interference calculation for FH-FSK wherein all nodes use an identical hopping pattern. In this case, there is an (M-1)*SymbolTime clearing time between symbols transmitted on the same frequency. This clearing time combats ISI from channel delay spread and also has a byproduct of possibly reducing interference from other transmitted packets.
Thanks to Randall Plate for the latest model revision based on the following papers:
Parrish, "System Design Considerations for Undersea Networks: Link and Multiple Access Protocols"
Siderius, "Effects of Ocean Thermocline Variability on Noncoherent Underwater Acoustic Communications"
Rao, "Channel Coding Techniques for Wireless Communications", ch 2
Definition at line 227 of file uan-phy-gen.h.
Constructor & Destructor Documentation
UanPhyCalcSinrFhFsk()
ns3::UanPhyCalcSinrFhFsk::UanPhyCalcSinrFhFsk ()
Constructor.
Definition at line 101 of file uan-phy-gen.cc.
~UanPhyCalcSinrFhFsk()
ns3::UanPhyCalcSinrFhFsk::~UanPhyCalcSinrFhFsk () virtual
Destructor.
Definition at line 105 of file uan-phy-gen.cc.
Member Function Documentation
CalcSinrDb()
double ns3::UanPhyCalcSinrFhFsk::CalcSinrDb (Ptr< Packet > pkt, Time arrTime, double rxPowerDb, double ambNoiseDb, UanTxMode mode, UanPdp pdp, const UanTransducer::ArrivalList & arrivalList) const virtual
Calculate the SINR value for a packet.
Parameters
pkt Packet to calculate SINR for.
arrTime Arrival time of pkt.
rxPowerDb The received signal strength of the packet in dB re 1 uPa.
ambNoiseDb Ambient channel noise in dB re 1 uPa.
mode TX Mode of pkt.
pdp Power delay profile of pkt.
arrivalList List of interfering arrivals given from Transducer.
Returns
The SINR in dB re 1 uPa.
Implements ns3::UanPhyCalcSinr.
Definition at line 126 of file uan-phy-gen.cc.
References ns3::Abs(), ns3::UanPhyCalcSinr::DbToKp(), ns3::UanTxMode::FSK, ns3::UanPdp::GetBegin(), ns3::UanTxMode::GetConstellationSize(), ns3::Tap::GetDelay(), ns3::UanPdp::GetEnd(), ns3::UanTxMode::GetModType(), ns3::UanTxMode::GetPhyRateSps(), ns3::UanPdp::GetTap(), ns3::UanPhyCalcSinr::KpToDb(), m_hops, NS_FATAL_ERROR, NS_LOG_DEBUG, ns3::Seconds(), visualizer.core::start(), ns3::UanPdp::SumTapsFromMaxNc(), and ns3::UanPdp::SumTapsNc().
GetTypeId()
TypeId ns3::UanPhyCalcSinrFhFsk::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 111 of file uan-phy-gen.cc.
References m_hops, ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
Member Data Documentation
m_hops
uint32_t ns3::UanPhyCalcSinrFhFsk::m_hops private
Number of hops.
Definition at line 251 of file uan-phy-gen.h.
Referenced by CalcSinrDb(), and GetTypeId().
The documentation for this class was generated from the following files:
src/uan/model/uan-phy-gen.h
src/uan/model/uan-phy-gen.cc