ns-3: ns3::WifiMacHeader Class Reference
ns3::WifiMacHeader Class Reference
Wifi Models
#include "wifi-mac-header.h"
Public Types
enum AddressType { ADDR1, ADDR2, ADDR3, ADDR4 }
Address types.
enum QosAckPolicy { NORMAL_ACK = 0, NO_ACK = 1, NO_EXPLICIT_ACK = 2, BLOCK_ACK = 3 }
Ack policy for QoS frames.
typedef void(* TracedCallback) (const WifiMacHeader &header)
TracedCallback signature for WifiMacHeader.
Public Member Functions
WifiMacHeader ()
virtual ~WifiMacHeader ()
uint32_t Deserialize (Buffer::Iterator start)
Mac48Address GetAddr1 (void) const
Return the address in the Address 1 field.
Mac48Address GetAddr2 (void) const
Return the address in the Address 2 field.
Mac48Address GetAddr3 (void) const
Return the address in the Address 3 field.
Mac48Address GetAddr4 (void) const
Return the address in the Address 4 field.
Time GetDuration (void) const
Return the duration from the Duration/ID field (Time object).
uint8_t GetFragmentNumber (void) const
Return the fragment number of the header.
TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
QosAckPolicy GetQosAckPolicy (void) const
Return the QoS Ack policy in the QoS control field.
uint8_t GetQosTid (void) const
Return the Traffic ID of a QoS header.
uint16_t GetRawDuration (void) const
Return the raw duration from the Duration/ID field.
uint16_t GetSequenceControl (void) const
Return the raw Sequence Control field.
uint16_t GetSequenceNumber (void) const
Return the sequence number of the header.
uint32_t GetSerializedSize (void) const
uint32_t GetSize (void) const
Return the size of the WifiMacHeader in octets.
WifiMacType GetType (void) const
Return the type (enum WifiMacType)
const char * GetTypeString (void) const
Return a string corresponds to the header type.
bool HasData (void) const
Return true if the header type is DATA and is not DATA_NULL.
bool IsAck (void) const
Return true if the header is an Ack header.
bool IsAction (void) const
Return true if the header is an Action header.
bool IsAssocReq (void) const
Return true if the header is an Association Request header.
bool IsAssocResp (void) const
Return true if the header is an Association Response header.
bool IsAuthentication (void) const
Return true if the header is an Authentication header.
bool IsBeacon (void) const
Return true if the header is a Beacon header.
bool IsBlockAck (void) const
Return true if the header is a BlockAck header.
bool IsBlockAckReq (void) const
Return true if the header is a BlockAckRequest header.
bool IsCfAck (void) const
Return true if the header is a CF-Ack header.
bool IsCfEnd (void) const
Return true if the header is a CF-End header.
bool IsCfPoll (void) const
Return true if the Type/Subtype is one of the possible CF-Poll headers.
bool IsCtl (void) const
Return true if the Type is Control.
bool IsCts (void) const
Return true if the header is a CTS header.
bool IsData (void) const
Return true if the Type is DATA.
bool IsDeauthentication (void) const
Return true if the header is a Deauthentication header.
bool IsDisassociation (void) const
Return true if the header is a Disassociation header.
bool IsFromDs (void) const
bool IsMgt (void) const
Return true if the Type is Management.
bool IsMoreFragments (void) const
Return if the More Fragment bit is set.
bool IsMultihopAction (void) const
Check if the header is a Multihop action header.
bool IsProbeReq (void) const
Return true if the header is a Probe Request header.
bool IsProbeResp (void) const
Return true if the header is a Probe Response header.
bool IsQosAck (void) const
Return if the QoS Ack policy is Normal Ack.
bool IsQosAmsdu (void) const
Check if the A-MSDU present bit is set in the QoS control field.
bool IsQosBlockAck (void) const
Return if the QoS Ack policy is Block Ack.
bool IsQosData (void) const
Return true if the Type is DATA and Subtype is one of the possible values for QoS Data.
bool IsQosEosp (void) const
Return if the end of service period (EOSP) is set.
bool IsQosNoAck (void) const
Return if the QoS Ack policy is No Ack.
bool IsReassocReq (void) const
Return true if the header is a Reassociation Request header.
bool IsReassocResp (void) const
Return true if the header is a Reassociation Response header.
bool IsRetry (void) const
Return if the Retry bit is set.
bool IsRts (void) const
Return true if the header is a RTS header.
bool IsToDs (void) const
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetAddr1 (Mac48Address address)
Fill the Address 1 field with the given address.
void SetAddr2 (Mac48Address address)
Fill the Address 2 field with the given address.
void SetAddr3 (Mac48Address address)
Fill the Address 3 field with the given address.
void SetAddr4 (Mac48Address address)
Fill the Address 4 field with the given address.
void SetDsFrom (void)
Set the From DS bit in the Frame Control field.
void SetDsNotFrom (void)
Un-set the From DS bit in the Frame Control field.
void SetDsNotTo (void)
Un-set the To DS bit in the Frame Control field.
void SetDsTo (void)
Set the To DS bit in the Frame Control field.
void SetDuration (Time duration)
Set the Duration/ID field with the given duration (Time object).
void SetFragmentNumber (uint8_t frag)
Set the fragment number of the header.
void SetId (uint16_t id)
Set the Duration/ID field with the given ID.
void SetMoreFragments (void)
Set the More Fragment bit in the Frame Control field.
void SetNoMoreFragments (void)
Un-set the More Fragment bit in the Frame Control Field.
void SetNoOrder (void)
Unset order bit in the frame control field.
void SetNoRetry (void)
Un-set the Retry bit in the Frame Control field.
void SetOrder (void)
Set order bit in the frame control field.
void SetQosAckPolicy (QosAckPolicy policy)
Set the QoS Ack policy in the QoS control field.
void SetQosAmsdu (void)
Set that A-MSDU is present.
void SetQosEosp ()
Set the end of service period (EOSP) bit in the QoS control field.
void SetQosMeshControlPresent ()
Set the Mesh Control Present flag for the QoS header.
void SetQosNoAmsdu (void)
Set that A-MSDU is not present.
void SetQosNoEosp ()
Un-set the end of service period (EOSP) bit in the QoS control field.
void SetQosNoMeshControlPresent ()
Clear the Mesh Control Present flag for the QoS header.
void SetQosTid (uint8_t tid)
Set the TID for the QoS header.
void SetQosTxopLimit (uint8_t txop)
Set TXOP limit in the QoS control field.
void SetRawDuration (uint16_t duration)
Set the Duration/ID field with the given raw uint16_t value.
void SetRetry (void)
Set the Retry bit in the Frame Control field.
void SetSequenceNumber (uint16_t seq)
Set the sequence number of the header.
void SetType (WifiMacType type, bool resetToDsFromDs=true)
Set Type/Subtype values with the correct values depending on the given type.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
uint16_t GetFrameControl (void) const
Return the raw Frame Control field.
uint16_t GetQosControl (void) const
Return the raw QoS Control field.
void PrintFrameControl (std::ostream &os) const
Print the Frame Control field to the output stream.
void SetFrameControl (uint16_t control)
Set the Frame Control field with the given raw value.
void SetQosControl (uint16_t qos)
Set the QoS Control field with the given raw value.
void SetSequenceControl (uint16_t seq)
Set the Sequence Control field with the given raw value.
Private Attributes
Mac48Address m_addr1
address 1
Mac48Address m_addr2
address 2
Mac48Address m_addr3
address 3
Mac48Address m_addr4
address 4
uint8_t m_amsduPresent
A-MSDU present.
uint8_t m_ctrlFromDs
control from DS
uint8_t m_ctrlMoreData
control more data
uint8_t m_ctrlMoreFrag
control more fragments
uint8_t m_ctrlOrder
control order (set to 1 for QoS Data and Management frames to signify that HT/VHT/HE control field is present, knowing that the latter are not implemented yet)
uint8_t m_ctrlRetry
control retry
uint8_t m_ctrlSubtype
control subtype
uint8_t m_ctrlToDs
control to DS
uint8_t m_ctrlType
control type
uint8_t m_ctrlWep
control WEP
uint16_t m_duration
duration
uint8_t m_qosAckPolicy
QoS Ack policy.
uint8_t m_qosEosp
QoS EOSP.
uint8_t m_qosStuff
QoS stuff.
uint8_t m_qosTid
QoS TID.
uint8_t m_seqFrag
sequence fragment
uint16_t m_seqSeq
sequence sequence
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implements the IEEE 802.11 MAC header
Definition at line 83 of file wifi-mac-header.h.
Member Typedef Documentation
TracedCallback
typedef void(* ns3::WifiMacHeader::TracedCallback) (const WifiMacHeader &header)
TracedCallback signature for WifiMacHeader.
Parameters
[in] header The header
Definition at line 566 of file wifi-mac-header.h.
Member Enumeration Documentation
AddressType
enum ns3::WifiMacHeader::AddressType
Address types.
Enumerator
ADDR1
ADDR2
ADDR3
ADDR4
Definition at line 100 of file wifi-mac-header.h.
QosAckPolicy
enum ns3::WifiMacHeader::QosAckPolicy
Ack policy for QoS frames.
Enumerator
NORMAL_ACK
NO_ACK
NO_EXPLICIT_ACK
BLOCK_ACK
Definition at line 89 of file wifi-mac-header.h.
Constructor & Destructor Documentation
WifiMacHeader()
ns3::WifiMacHeader::WifiMacHeader ()
Definition at line 53 of file wifi-mac-header.cc.
~WifiMacHeader()
ns3::WifiMacHeader::~WifiMacHeader () virtual
Definition at line 61 of file wifi-mac-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::WifiMacHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 1167 of file wifi-mac-header.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_addr1, m_addr2, m_addr3, m_addr4, m_ctrlFromDs, m_ctrlSubtype, m_ctrlToDs, m_ctrlType, m_duration, ns3::ReadFrom(), ns3::Buffer::Iterator::ReadLsbtohU16(), SetFrameControl(), SetQosControl(), SetSequenceControl(), visualizer.core::start(), ns3::SUBTYPE_CTL_ACK, ns3::SUBTYPE_CTL_BACKREQ, ns3::SUBTYPE_CTL_BACKRESP, ns3::SUBTYPE_CTL_CTS, ns3::SUBTYPE_CTL_END, ns3::SUBTYPE_CTL_END_ACK, ns3::SUBTYPE_CTL_RTS, ns3::TYPE_CTL, ns3::TYPE_DATA, and ns3::TYPE_MGT.
GetAddr1()
Mac48Address ns3::WifiMacHeader::GetAddr1 (void) const
Return the address in the Address 1 field.
Returns
the address in the Address 1 field
Definition at line 395 of file wifi-mac-header.cc.
References m_addr1.
Referenced by ns3::WifiMacQueueItem::Aggregate(), ns3::QosTxop::CompleteMpduTx(), ns3::MacLow::DeaggregateAmpduAndReceive(), AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), HeAggregationTest::DoRunSubTest(), ns3::MacLow::ForwardDown(), ns3::MeshWifiInterfaceMac::ForwardDown(), ns3::WifiMacQueueItem::GetDestinationAddress(), ns3::QosTxop::GetFragmentOffset(), ns3::Txop::GetFragmentOffset(), ns3::QosTxop::GetFragmentSize(), ns3::Txop::GetFragmentSize(), ns3::QosTxop::GetNextFragmentSize(), ns3::Txop::GetNextFragmentSize(), ns3::MacTxMiddle::GetNextSequenceNumberFor(), ns3::QosTxop::GotAck(), ns3::QosTxop::GotAddBaResponse(), ns3::BlockAckManager::InsertInRetryQueue(), ns3::QosTxop::IsLastFragment(), ns3::Txop::IsLastFragment(), ns3::QosTxop::IsTxopFragmentation(), ns3::QosTxop::MapDestAddressForAggregation(), ns3::QosTxop::MissedAck(), ns3::Txop::MissedAck(), ns3::QosTxop::MissedBlockAck(), ns3::Txop::MissedCfPollResponse(), ns3::Txop::MissedCts(), ns3::QosTxop::NeedBarRetransmission(), ns3::Txop::NeedDataRetransmission(), ns3::QosTxop::NeedFragmentation(), ns3::Txop::NeedFragmentation(), ns3::WifiRemoteStationManager::NeedRts(), ns3::Txop::NeedRtsRetransmission(), ns3::QosTxop::NotifyAccessGranted(), ns3::Txop::NotifyAccessGranted(), ns3::QosTxop::NotifyInternalCollision(), ns3::BlockAckManager::NotifyMissedAck(), ns3::QosTxop::NotifyMissedCts(), ns3::MacLow::NotifyNav(), ns3::MacTxMiddle::PeekNextSequenceNumberFor(), NodeStatistics::PhyCallback(), ns3::WifiMacQueueItem::Print(), ns3::aodv::Neighbors::ProcessTxError(), ns3::dsr::DsrRouteCache::ProcessTxError(), ns3::QosTxop::PushFront(), ns3::Txop::Queue(), ns3::flame::FlameProtocolMac::Receive(), ns3::MeshWifiInterfaceMac::Receive(), ns3::OcbWifiMac::Receive(), ns3::AdhocWifiMac::Receive(), ns3::ApWifiMac::Receive(), ns3::MacRxMiddle::Receive(), ns3::RegularWifiMac::Receive(), ns3::StaWifiMac::Receive(), ns3::MacLow::ReceiveOk(), ns3::Txop::SendCfFrame(), ns3::MeshWifiInterfaceMac::SendManagementFrame(), ns3::QosTxop::SetupBlockAckIfNeeded(), ns3::QosTxop::StartNextPacket(), ns3::MacLow::StartTransmission(), ns3::BlockAckManager::StorePacket(), ns3::PyViz::TraceNetDevTxWifi(), ns3::dot11s::PeerManagementProtocolMac::TxError(), ns3::ApWifiMac::TxFailed(), ns3::ApWifiMac::TxOk(), ns3::dot11s::PeerManagementProtocolMac::TxOk(), and ns3::dot11s::PeerManagementProtocolMac::UpdateOutcomingFrame().
GetAddr2()
Mac48Address ns3::WifiMacHeader::GetAddr2 (void) const
Return the address in the Address 2 field.
Returns
the address in the Address 2 field
Definition at line 401 of file wifi-mac-header.cc.
References m_addr2.
Referenced by ns3::WifiMacQueueItem::Aggregate(), ns3::MacLow::DeaggregateAmpduAndReceive(), ns3::MacRxMiddle::Lookup(), ns3::QosTxop::MapSrcAddressForAggregation(), ns3::MacLow::NotifyNav(), ns3::dot11s::PeerManagementProtocolMac::Receive(), ns3::flame::FlameProtocolMac::Receive(), ns3::MeshWifiInterfaceMac::Receive(), ns3::OcbWifiMac::Receive(), ns3::AdhocWifiMac::Receive(), ns3::ApWifiMac::Receive(), ns3::MacRxMiddle::Receive(), ns3::RegularWifiMac::Receive(), ns3::StaWifiMac::Receive(), ns3::dot11s::HwmpProtocolMac::ReceiveAction(), ns3::MacLow::ReceiveMpdu(), ns3::MacLow::ReceiveOk(), ns3::MacLow::StoreMpduIfNeeded(), ns3::PyViz::TraceNetDevRxWifi(), ns3::AnimationInterface::WavePhyRxBeginTrace(), and ns3::AnimationInterface::WifiPhyRxBeginTrace().
GetAddr3()
Mac48Address ns3::WifiMacHeader::GetAddr3 (void) const
Return the address in the Address 3 field.
Returns
the address in the Address 3 field
Definition at line 407 of file wifi-mac-header.cc.
References m_addr3.
Referenced by ns3::QosTxop::MapDestAddressForAggregation(), ns3::QosTxop::MapSrcAddressForAggregation(), ns3::dot11s::PeerManagementProtocolMac::Receive(), ns3::MeshWifiInterfaceMac::Receive(), ns3::OcbWifiMac::Receive(), ns3::ApWifiMac::Receive(), ns3::StaWifiMac::Receive(), ns3::dot11s::HwmpProtocolMac::ReceiveAction(), ns3::dot11s::HwmpProtocolMac::ReceiveData(), ns3::PyViz::TraceNetDevRxWifi(), and ns3::PyViz::TraceNetDevTxWifi().
GetAddr4()
Mac48Address ns3::WifiMacHeader::GetAddr4 (void) const
Return the address in the Address 4 field.
Returns
the address in the Address 4 field
Definition at line 413 of file wifi-mac-header.cc.
References m_addr4.
Referenced by ns3::MeshWifiInterfaceMac::Receive(), ns3::dot11s::HwmpProtocolMac::ReceiveData(), and ns3::PyViz::TraceNetDevRxWifi().
GetDuration()
Time ns3::WifiMacHeader::GetDuration (void) const
Return the duration from the Duration/ID field (Time object).
Returns
the duration from the Duration/ID field (Time object)
Definition at line 728 of file wifi-mac-header.cc.
References m_duration, and ns3::MicroSeconds().
Referenced by ns3::MacLow::DeaggregateAmpduAndReceive(), ns3::MacLow::ForwardDown(), ns3::MacLow::NotifyNav(), and ns3::MacLow::ReceiveOk().
GetFragmentNumber()
uint8_t ns3::WifiMacHeader::GetFragmentNumber (void) const
Return the fragment number of the header.
Returns
the fragment number of the header
Definition at line 746 of file wifi-mac-header.cc.
References m_seqFrag.
Referenced by ns3::MacRxMiddle::HandleFragments(), ns3::BlockAckManager::InsertInRetryQueue(), ns3::MacRxMiddle::Receive(), ns3::MacLow::StartTransmission(), ns3::BlockAckManager::StorePacket(), and ns3::BlockAckCache::UpdateWithMpdu().
GetFrameControl()
uint16_t ns3::WifiMacHeader::GetFrameControl (void) const private
Return the raw Frame Control field.
Returns
the raw Frame Control field
Definition at line 832 of file wifi-mac-header.cc.
References m_ctrlFromDs, m_ctrlMoreData, m_ctrlMoreFrag, m_ctrlOrder, m_ctrlRetry, m_ctrlSubtype, m_ctrlToDs, m_ctrlType, and m_ctrlWep.
Referenced by Serialize().
GetInstanceTypeId()
TypeId ns3::WifiMacHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 1000 of file wifi-mac-header.cc.
References GetTypeId().
GetQosAckPolicy()
WifiMacHeader::QosAckPolicy ns3::WifiMacHeader::GetQosAckPolicy (void) const
Return the QoS Ack policy in the QoS control field.
Returns
the QoS Ack policy in the QoS control field
Definition at line 792 of file wifi-mac-header.cc.
References BLOCK_ACK, IsQosData(), m_qosAckPolicy, NO_ACK, NO_EXPLICIT_ACK, NORMAL_ACK, NS_ABORT_MSG, and NS_ASSERT.
GetQosControl()
uint16_t ns3::WifiMacHeader::GetQosControl (void) const private
Return the raw QoS Control field.
Returns
the raw QoS Control field
Definition at line 848 of file wifi-mac-header.cc.
References m_amsduPresent, m_qosAckPolicy, m_qosEosp, m_qosStuff, and m_qosTid.
Referenced by Serialize().
GetQosTid()
uint8_t ns3::WifiMacHeader::GetQosTid (void) const
Return the Traffic ID of a QoS header.
Returns
the Traffic ID of a QoS header
Definition at line 825 of file wifi-mac-header.cc.
References IsQosData(), m_qosTid, and NS_ASSERT.
Referenced by ns3::QosTxop::CompleteMpduTx(), ns3::MacLow::DeaggregateAmpduAndReceive(), ns3::ApWifiMac::DeaggregateAmsduAndForward(), ns3::MacTxMiddle::GetNextSequenceNumberFor(), ns3::GetTid(), ns3::QosTxop::GotAck(), ns3::QosTxop::GotAddBaResponse(), ns3::BlockAckManager::InsertInRetryQueue(), ns3::MacRxMiddle::Lookup(), ns3::QosTxop::MissedAck(), ns3::QosTxop::NeedBarRetransmission(), ns3::WifiRemoteStationManager::NeedRetransmission(), ns3::QosTxop::NotifyAccessGranted(), ns3::BlockAckManager::NotifyMissedAck(), ns3::MacTxMiddle::PeekNextSequenceNumberFor(), ns3::WifiMacQueueItem::Print(), ns3::MeshWifiInterfaceMac::Receive(), ns3::ApWifiMac::Receive(), ns3::MacLow::ReceiveMpdu(), ns3::MacLow::ReceiveOk(), ns3::WifiRemoteStationManager::ReportDataFailed(), ns3::WifiRemoteStationManager::ReportDataOk(), ns3::WifiRemoteStationManager::ReportFinalDataFailed(), ns3::WifiRemoteStationManager::ReportFinalRtsFailed(), ns3::WifiRemoteStationManager::ReportRtsFailed(), ns3::WifiRemoteStationManager::ReportRtsOk(), ns3::QosTxop::SetupBlockAckIfNeeded(), ns3::QosTxop::StartNextPacket(), ns3::MacLow::StartTransmission(), ns3::MacLow::StoreMpduIfNeeded(), and ns3::BlockAckManager::StorePacket().
GetRawDuration()
uint16_t ns3::WifiMacHeader::GetRawDuration (void) const
Return the raw duration from the Duration/ID field.
Returns
the raw duration from the Duration/ID field
Definition at line 722 of file wifi-mac-header.cc.
References m_duration.
Referenced by ns3::MacLow::NotifyNav().
GetSequenceControl()
uint16_t ns3::WifiMacHeader::GetSequenceControl (void) const
Return the raw Sequence Control field.
Returns
the raw Sequence Control field
Definition at line 734 of file wifi-mac-header.cc.
References m_seqFrag, and m_seqSeq.
Referenced by ns3::MacLow::ForwardDown(), ns3::MacRxMiddle::HandleFragments(), ns3::BlockAckManager::InsertInRetryQueue(), ns3::MacRxMiddle::IsDuplicate(), ns3::Txop::NotifyAccessGranted(), ns3::MacRxMiddle::Receive(), Serialize(), ns3::MacLow::StoreMpduIfNeeded(), and ns3::BlockAckManager::StorePacket().
GetSequenceNumber()
uint16_t ns3::WifiMacHeader::GetSequenceNumber (void) const
Return the sequence number of the header.
Returns
the sequence number of the header
Definition at line 740 of file wifi-mac-header.cc.
References m_seqSeq.
Referenced by ns3::MacLow::DeaggregateAmpduAndReceive(), ns3::BlockAckManager::DiscardOutstandingMpdus(), AmpduAggregationTest::DoRun(), ns3::MpduAggregator::GetNextAmpdu(), ns3::MacRxMiddle::HandleFragments(), ns3::BlockAckManager::InsertInRetryQueue(), ns3::BlockAckManager::NotifyMissedAck(), ns3::WifiMacQueueItem::Print(), ns3::MacRxMiddle::Receive(), ns3::MacLow::ReceiveMpdu(), ns3::MacLow::StartTransmission(), ns3::BlockAckManager::StorePacket(), and ns3::BlockAckCache::UpdateWithMpdu().
GetSerializedSize()
uint32_t ns3::WifiMacHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 1108 of file wifi-mac-header.cc.
References GetSize().
Referenced by ns3::WifiPsdu::WifiPsdu(), ns3::MacLow::CanTransmitNextCfFrame(), ns3::WifiMacQueueItem::GetSize(), ns3::MacLow::NotifyNav(), InterferenceExperiment::SendA(), and InterferenceExperiment::SendB().
GetSize()
uint32_t ns3::WifiMacHeader::GetSize (void) const
Return the size of the WifiMacHeader in octets.
GetSerializedSize calls this function.
Returns
the size of the WifiMacHeader in octets
Definition at line 889 of file wifi-mac-header.cc.
References m_ctrlFromDs, m_ctrlSubtype, m_ctrlToDs, m_ctrlType, ns3::SUBTYPE_CTL_ACK, ns3::SUBTYPE_CTL_BACKREQ, ns3::SUBTYPE_CTL_BACKRESP, ns3::SUBTYPE_CTL_CTLWRAPPER, ns3::SUBTYPE_CTL_CTS, ns3::SUBTYPE_CTL_END, ns3::SUBTYPE_CTL_END_ACK, ns3::SUBTYPE_CTL_RTS, ns3::TYPE_CTL, ns3::TYPE_DATA, and ns3::TYPE_MGT.
Referenced by ns3::GetAckSize(), ns3::GetBlockAckRequestSize(), ns3::GetBlockAckSize(), ns3::MacLow::GetCfEndSize(), ns3::GetCtsSize(), ns3::WifiRemoteStationManager::GetFragmentOffset(), ns3::WifiRemoteStationManager::GetFragmentSize(), ns3::MsduAggregator::GetNextAmsdu(), ns3::WifiRemoteStationManager::GetNFragments(), ns3::GetRtsSize(), GetSerializedSize(), ns3::GetSize(), ns3::MacRxMiddle::HandleFragments(), ns3::WifiRemoteStationManager::NeedFragmentation(), ns3::WifiRemoteStationManager::NeedRetransmission(), ns3::WifiRemoteStationManager::NeedRts(), ns3::WifiRemoteStationManager::ReportDataFailed(), ns3::WifiRemoteStationManager::ReportDataOk(), and ns3::WifiRemoteStationManager::ReportFinalDataFailed().
GetType()
WifiMacType ns3::WifiMacHeader::GetType (void) const
Return the type (enum WifiMacType)
Returns
the type (enum WifiMacType)
Definition at line 419 of file wifi-mac-header.cc.
References m_ctrlSubtype, m_ctrlType, NS_ASSERT, ns3::SUBTYPE_CTL_ACK, ns3::SUBTYPE_CTL_BACKREQ, ns3::SUBTYPE_CTL_BACKRESP, ns3::SUBTYPE_CTL_CTS, ns3::SUBTYPE_CTL_END, ns3::SUBTYPE_CTL_END_ACK, ns3::SUBTYPE_CTL_RTS, ns3::TYPE_CTL, ns3::TYPE_DATA, ns3::TYPE_MGT, ns3::WIFI_MAC_CTL_ACK, ns3::WIFI_MAC_CTL_BACKREQ, ns3::WIFI_MAC_CTL_BACKRESP, ns3::WIFI_MAC_CTL_CTS, ns3::WIFI_MAC_CTL_END, ns3::WIFI_MAC_CTL_END_ACK, ns3::WIFI_MAC_CTL_RTS, ns3::WIFI_MAC_DATA, ns3::WIFI_MAC_DATA_CFACK, ns3::WIFI_MAC_DATA_CFACK_CFPOLL, ns3::WIFI_MAC_DATA_CFPOLL, ns3::WIFI_MAC_DATA_NULL, ns3::WIFI_MAC_DATA_NULL_CFACK, ns3::WIFI_MAC_DATA_NULL_CFACK_CFPOLL, ns3::WIFI_MAC_DATA_NULL_CFPOLL, ns3::WIFI_MAC_MGT_ACTION, ns3::WIFI_MAC_MGT_ACTION_NO_ACK, ns3::WIFI_MAC_MGT_ASSOCIATION_REQUEST, ns3::WIFI_MAC_MGT_ASSOCIATION_RESPONSE, ns3::WIFI_MAC_MGT_AUTHENTICATION, ns3::WIFI_MAC_MGT_BEACON, ns3::WIFI_MAC_MGT_DEAUTHENTICATION, ns3::WIFI_MAC_MGT_DISASSOCIATION, ns3::WIFI_MAC_MGT_MULTIHOP_ACTION, ns3::WIFI_MAC_MGT_PROBE_REQUEST, ns3::WIFI_MAC_MGT_PROBE_RESPONSE, ns3::WIFI_MAC_MGT_REASSOCIATION_REQUEST, ns3::WIFI_MAC_MGT_REASSOCIATION_RESPONSE, ns3::WIFI_MAC_QOSDATA, ns3::WIFI_MAC_QOSDATA_CFACK, ns3::WIFI_MAC_QOSDATA_CFACK_CFPOLL, ns3::WIFI_MAC_QOSDATA_CFPOLL, ns3::WIFI_MAC_QOSDATA_NULL, ns3::WIFI_MAC_QOSDATA_NULL_CFACK_CFPOLL, and ns3::WIFI_MAC_QOSDATA_NULL_CFPOLL.
Referenced by GetTypeString(), HasData(), IsAck(), IsAction(), IsAssocReq(), IsAssocResp(), IsAuthentication(), IsBeacon(), IsBlockAck(), IsBlockAckReq(), IsCfAck(), IsCfEnd(), IsCfPoll(), IsCts(), IsDeauthentication(), IsDisassociation(), IsMultihopAction(), IsProbeReq(), IsProbeResp(), IsReassocReq(), IsReassocResp(), IsRts(), NodeStatistics::PhyCallback(), Print(), and ns3::RegularWifiMac::Receive().
GetTypeId()
TypeId ns3::WifiMacHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 989 of file wifi-mac-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
GetTypeString()
const char * ns3::WifiMacHeader::GetTypeString (void) const
Return a string corresponds to the header type.
Returns
a string corresponds to the header type.
Definition at line 932 of file wifi-mac-header.cc.
References ns3::DATA, FOO, and GetType().
Referenced by ns3::MacLow::ForwardDown(), Print(), and ns3::MacLow::ReceiveOk().
HasData()
bool ns3::WifiMacHeader::HasData (void) const
Return true if the header type is DATA and is not DATA_NULL.
Returns
true if the header type is DATA and is not DATA_NULL, false otherwise
Definition at line 601 of file wifi-mac-header.cc.
References GetType(), ns3::WIFI_MAC_DATA, ns3::WIFI_MAC_DATA_CFACK, ns3::WIFI_MAC_DATA_CFACK_CFPOLL, ns3::WIFI_MAC_DATA_CFPOLL, ns3::WIFI_MAC_QOSDATA, ns3::WIFI_MAC_QOSDATA_CFACK, ns3::WIFI_MAC_QOSDATA_CFACK_CFPOLL, and ns3::WIFI_MAC_QOSDATA_CFPOLL.
Referenced by ns3::MacLow::ForwardDown(), ns3::ApWifiMac::Receive(), ns3::StaWifiMac::Receive(), ns3::MacLow::ReceiveOk(), and TxCallback().
IsAck()
bool ns3::WifiMacHeader::IsAck (void) const
Return true if the header is an Ack header.
Returns
true if the header is an Ack header, false otherwise
Definition at line 632 of file wifi-mac-header.cc.
References GetType(), and ns3::WIFI_MAC_CTL_ACK.
Referenced by ns3::MacLow::DeaggregateAmpduAndReceive(), and ns3::MacLow::ReceiveOk().
IsAction()
bool ns3::WifiMacHeader::IsAction (void) const
Return true if the header is an Action header.
Returns
true if the header is an Action header, false otherwise
Definition at line 698 of file wifi-mac-header.cc.
References GetType(), and ns3::WIFI_MAC_MGT_ACTION.
Referenced by ns3::GetTid(), ns3::QosTxop::GotAck(), ns3::QosTxop::MissedAck(), ns3::QosTxop::MissedBlockAck(), ns3::dot11s::HwmpProtocolMac::Receive(), ns3::dot11s::PeerManagementProtocolMac::Receive(), ns3::OcbWifiMac::Receive(), ns3::RegularWifiMac::Receive(), Bug2470TestCase::RxErrorCallback(), and ns3::dot11s::PeerManagementProtocolMac::UpdateOutcomingFrame().
IsAssocReq()
bool ns3::WifiMacHeader::IsAssocReq (void) const
Return true if the header is an Association Request header.
Returns
true if the header is an Association Request header, false otherwise
Definition at line 638 of file wifi-mac-header.cc.
References GetType(), and ns3::WIFI_MAC_MGT_ASSOCIATION_REQUEST.
Referenced by ns3::ApWifiMac::Receive(), and ns3::StaWifiMac::Receive().
IsAssocResp()
bool ns3::WifiMacHeader::IsAssocResp (void) const
Return true if the header is an Association Response header.
Returns
true if the header is an Association Response header, false otherwise
Definition at line 644 of file wifi-mac-header.cc.
References GetType(), and ns3::WIFI_MAC_MGT_ASSOCIATION_RESPONSE.
Referenced by ns3::StaWifiMac::Receive(), ns3::ApWifiMac::TxFailed(), and ns3::ApWifiMac::TxOk().
IsAuthentication()
bool ns3::WifiMacHeader::IsAuthentication (void) const
Return true if the header is an Authentication header.
Returns
true if the header is an Authentication header, false otherwise
Definition at line 686 of file wifi-mac-header.cc.
References GetType(), and ns3::WIFI_MAC_MGT_AUTHENTICATION.
IsBeacon()
bool ns3::WifiMacHeader::IsBeacon (void) const
Return true if the header is a Beacon header.
Returns
true if the header is a Beacon header, false otherwise
Definition at line 674 of file wifi-mac-header.cc.
References GetType(), and ns3::WIFI_MAC_MGT_BEACON.
Referenced by ns3::MacLow::ForwardDown(), ns3::dot11s::PeerManagementProtocolMac::Receive(), ns3::MeshWifiInterfaceMac::Receive(), ns3::StaWifiMac::Receive(), ns3::MacLow::ReceiveOk(), Bug2831TestCase::RxCallback(), TxCallback(), and ns3::ApWifiMac::TxOk().
IsBlockAck()
bool ns3::WifiMacHeader::IsBlockAck (void) const
Return true if the header is a BlockAck header.
Returns
true if the header is a BlockAck header, false otherwise
Definition at line 716 of file wifi-mac-header.cc.
References GetType(), and ns3::WIFI_MAC_CTL_BACKRESP.
Referenced by ns3::MacLow::DeaggregateAmpduAndReceive(), ns3::GetTid(), ns3::QosTxop::NeedBarRetransmission(), BlockAckAggregationDisabledTest::Receive(), and ns3::MacLow::ReceiveOk().
IsBlockAckReq()
bool ns3::WifiMacHeader::IsBlockAckReq (void) const
Return true if the header is a BlockAckRequest header.
Returns
true if the header is a BlockAckRequest header, false otherwise
Definition at line 710 of file wifi-mac-header.cc.
References GetType(), and ns3::WIFI_MAC_CTL_BACKREQ.
Referenced by ns3::MacLow::DeaggregateAmpduAndReceive(), ns3::GetTid(), ns3::QosTxop::MissedBlockAck(), ns3::QosTxop::NeedBarRetransmission(), ns3::MacLow::ReceiveOk(), and BlockAckAggregationDisabledTest::Transmit().
IsCfAck()
bool ns3::WifiMacHeader::IsCfAck (void) const
Return true if the header is a CF-Ack header.
Returns
true if the header is a CF-Ack header, false otherwise
Definition at line 584 of file wifi-mac-header.cc.
References GetType(), ns3::WIFI_MAC_CTL_END_ACK, ns3::WIFI_MAC_DATA_CFACK, ns3::WIFI_MAC_DATA_CFACK_CFPOLL, ns3::WIFI_MAC_DATA_NULL_CFACK, and ns3::WIFI_MAC_DATA_NULL_CFACK_CFPOLL.
Referenced by ns3::MacLow::ReceiveOk(), and TxCallback().
IsCfEnd()
bool ns3::WifiMacHeader::IsCfEnd (void) const
Return true if the header is a CF-End header.
Returns
true if the header is a CF-End header, false otherwise
Definition at line 571 of file wifi-mac-header.cc.
References GetType(), ns3::WIFI_MAC_CTL_END, and ns3::WIFI_MAC_CTL_END_ACK.
Referenced by ns3::MacLow::ForwardDown(), ns3::MacLow::NotifyNav(), ns3::MacLow::ReceiveOk(), and TxCallback().
IsCfPoll()
bool ns3::WifiMacHeader::IsCfPoll (void) const
Return true if the Type/Subtype is one of the possible CF-Poll headers.
Returns
true if the Type/Subtype is one of the possible CF-Poll headers, false otherwise
Definition at line 552 of file wifi-mac-header.cc.
References GetType(), ns3::WIFI_MAC_DATA_CFACK_CFPOLL, ns3::WIFI_MAC_DATA_CFPOLL, ns3::WIFI_MAC_DATA_NULL_CFACK_CFPOLL, ns3::WIFI_MAC_DATA_NULL_CFPOLL, ns3::WIFI_MAC_QOSDATA_CFACK_CFPOLL, ns3::WIFI_MAC_QOSDATA_CFPOLL, ns3::WIFI_MAC_QOSDATA_NULL_CFACK_CFPOLL, and ns3::WIFI_MAC_QOSDATA_NULL_CFPOLL.
Referenced by ns3::MacLow::ForwardDown(), ns3::StaWifiMac::Receive(), ns3::MacLow::ReceiveOk(), TxCallback(), ns3::ApWifiMac::TxFailed(), and ns3::ApWifiMac::TxOk().
IsCtl()
bool ns3::WifiMacHeader::IsCtl (void) const
Return true if the Type is Control.
Returns
true if Type is Control, false otherwise
Definition at line 540 of file wifi-mac-header.cc.
References m_ctrlType, and ns3::TYPE_CTL.
Referenced by ns3::OcbWifiMac::Receive(), ns3::AdhocWifiMac::Receive(), ns3::StaWifiMac::Receive(), ns3::MacLow::ReceiveOk(), and ns3::MacLow::StartTransmission().
IsCts()
bool ns3::WifiMacHeader::IsCts (void) const
Return true if the header is a CTS header.
Returns
true if the header is a CTS header, false otherwise
Definition at line 626 of file wifi-mac-header.cc.
References GetType(), and ns3::WIFI_MAC_CTL_CTS.
Referenced by ns3::MacLow::ReceiveOk().
IsData()
bool ns3::WifiMacHeader::IsData (void) const
Return true if the Type is DATA.
The method does not check the Subtype field. (e.g. the header may be Data with QoS)
Returns
true if Type is DATA, false otherwise
Definition at line 527 of file wifi-mac-header.cc.
References m_ctrlType, and ns3::TYPE_DATA.
Referenced by ns3::MacLow::DeaggregateAmpduAndReceive(), ns3::QosTxop::NeedFragmentation(), ns3::QosTxop::NotifyAccessGranted(), OcbWifiMacTestCase::PhyTxTrace(), ns3::dot11s::HwmpProtocolMac::Receive(), ns3::flame::FlameProtocolMac::Receive(), ns3::MeshWifiInterfaceMac::Receive(), ns3::OcbWifiMac::Receive(), ns3::AdhocWifiMac::Receive(), ns3::ApWifiMac::Receive(), ns3::MacRxMiddle::Receive(), ns3::StaWifiMac::Receive(), ns3::dot11s::HwmpProtocolMac::ReceiveData(), ns3::MacLow::ReceiveOk(), Bug2470TestCase::RxCallback(), TxCallback(), ns3::dot11s::HwmpProtocolMac::UpdateOutcomingFrame(), and ns3::flame::FlameProtocolMac::UpdateOutcomingFrame().
IsDeauthentication()
bool ns3::WifiMacHeader::IsDeauthentication (void) const
Return true if the header is a Deauthentication header.
Returns
true if the header is a Deauthentication header, false otherwise
Definition at line 692 of file wifi-mac-header.cc.
References GetType(), and ns3::WIFI_MAC_MGT_DEAUTHENTICATION.
IsDisassociation()
bool ns3::WifiMacHeader::IsDisassociation (void) const
Return true if the header is a Disassociation header.
Returns
true if the header is a Disassociation header, false otherwise
Definition at line 680 of file wifi-mac-header.cc.
References GetType(), and ns3::WIFI_MAC_MGT_DISASSOCIATION.
Referenced by ns3::ApWifiMac::Receive().
IsFromDs()
bool ns3::WifiMacHeader::IsFromDs (void) const
Returns
true if From DS bit is set, false otherwise
Definition at line 515 of file wifi-mac-header.cc.
References m_ctrlFromDs.
Referenced by ns3::WifiMacQueueItem::Aggregate(), ns3::ApWifiMac::Receive(), ns3::StaWifiMac::Receive(), ns3::PyViz::TraceNetDevRxWifi(), and ns3::PyViz::TraceNetDevTxWifi().
IsMgt()
bool ns3::WifiMacHeader::IsMgt (void) const
Return true if the Type is Management.
Returns
true if Type is Management, false otherwise
Definition at line 546 of file wifi-mac-header.cc.
References m_ctrlType, and ns3::TYPE_MGT.
Referenced by ns3::WifiRemoteStationManager::GetDataTxVector(), ns3::GetTid(), ns3::OcbWifiMac::Receive(), ns3::ApWifiMac::Receive(), ns3::MacRxMiddle::Receive(), ns3::RegularWifiMac::Receive(), and ns3::MacLow::ReceiveOk().
IsMoreFragments()
bool ns3::WifiMacHeader::IsMoreFragments (void) const
Return if the More Fragment bit is set.
Returns
true if the More Fragment bit is set, false otherwise
Definition at line 758 of file wifi-mac-header.cc.
References m_ctrlMoreFrag.
Referenced by ns3::MacRxMiddle::HandleFragments(), and ns3::MacLow::StartTransmission().
IsMultihopAction()
bool ns3::WifiMacHeader::IsMultihopAction (void) const
Check if the header is a Multihop action header.
Returns
true if the header is a Multihop action header, false otherwise
Definition at line 704 of file wifi-mac-header.cc.
References GetType(), and ns3::WIFI_MAC_MGT_MULTIHOP_ACTION.
IsProbeReq()
bool ns3::WifiMacHeader::IsProbeReq (void) const
Return true if the header is a Probe Request header.
Returns
true if the header is a Probe Request header, false otherwise
Definition at line 662 of file wifi-mac-header.cc.
References GetType(), and ns3::WIFI_MAC_MGT_PROBE_REQUEST.
Referenced by ns3::ApWifiMac::Receive(), and ns3::StaWifiMac::Receive().
IsProbeResp()
bool ns3::WifiMacHeader::IsProbeResp (void) const
Return true if the header is a Probe Response header.
Returns
true if the header is a Probe Response header, false otherwise
Definition at line 668 of file wifi-mac-header.cc.
References GetType(), and ns3::WIFI_MAC_MGT_PROBE_RESPONSE.
Referenced by ns3::StaWifiMac::Receive(), and ns3::MacLow::ReceiveOk().
IsQosAck()
bool ns3::WifiMacHeader::IsQosAck (void) const
Return if the QoS Ack policy is Normal Ack.
Returns
true if the QoS Ack policy is No Ack, false otherwise
Definition at line 778 of file wifi-mac-header.cc.
References IsQosData(), m_qosAckPolicy, and NS_ASSERT.
Referenced by ns3::MacLow::DeaggregateAmpduAndReceive(), ns3::WifiMacQueueItem::Print(), and ns3::MacLow::ReceiveOk().
IsQosAmsdu()
bool ns3::WifiMacHeader::IsQosAmsdu (void) const
Check if the A-MSDU present bit is set in the QoS control field.
Returns
true if the A-MSDU present bit is set, false otherwise
Definition at line 818 of file wifi-mac-header.cc.
References IsQosData(), m_amsduPresent, and NS_ASSERT.
Referenced by ns3::WifiMacQueueItem::WifiMacQueueItem(), ns3::QosTxop::GotAck(), ns3::QosTxop::NotifyAccessGranted(), ns3::OcbWifiMac::Receive(), ns3::AdhocWifiMac::Receive(), ns3::ApWifiMac::Receive(), and ns3::StaWifiMac::Receive().
IsQosBlockAck()
bool ns3::WifiMacHeader::IsQosBlockAck (void) const
Return if the QoS Ack policy is Block Ack.
Returns
true if the QoS Ack policy is Block Ack, false otherwise
Definition at line 764 of file wifi-mac-header.cc.
References IsQosData(), m_qosAckPolicy, and NS_ASSERT.
Referenced by ns3::WifiMacQueueItem::Print(), ns3::MacLow::ReceiveOk(), and BlockAckAggregationDisabledTest::Transmit().
IsQosData()
bool ns3::WifiMacHeader::IsQosData (void) const
Return true if the Type is DATA and Subtype is one of the possible values for QoS Data.
Returns
true if Type is QoS DATA, false otherwise
Definition at line 534 of file wifi-mac-header.cc.
References m_ctrlSubtype, m_ctrlType, and ns3::TYPE_DATA.
Referenced by ns3::WifiMacQueueItem::WifiMacQueueItem(), ns3::QosTxop::CompleteMpduTx(), ns3::MacLow::DeaggregateAmpduAndReceive(), ns3::MacTxMiddle::GetNextSequenceNumberFor(), GetQosAckPolicy(), GetQosTid(), ns3::GetTid(), ns3::QosTxop::GotAck(), ns3::QosTxop::GotAddBaResponse(), ns3::BlockAckManager::InsertInRetryQueue(), IsQosAck(), IsQosAmsdu(), IsQosBlockAck(), IsQosEosp(), IsQosNoAck(), ns3::MacRxMiddle::Lookup(), ns3::QosTxop::MissedAck(), ns3::QosTxop::NeedBarRetransmission(), ns3::QosTxop::NeedFragmentation(), ns3::WifiRemoteStationManager::NeedRetransmission(), ns3::QosTxop::NotifyAccessGranted(), ns3::BlockAckManager::NotifyMissedAck(), PreservePacketsInAmpdus::NotifyPsduForwardedDown(), ns3::MacTxMiddle::PeekNextSequenceNumberFor(), ns3::WifiMacQueueItem::Print(), ns3::MeshWifiInterfaceMac::Receive(), ns3::OcbWifiMac::Receive(), ns3::AdhocWifiMac::Receive(), ns3::ApWifiMac::Receive(), ns3::StaWifiMac::Receive(), ns3::MacLow::ReceiveMpdu(), ns3::MacLow::ReceiveOk(), ns3::WifiRemoteStationManager::ReportDataFailed(), ns3::WifiRemoteStationManager::ReportDataOk(), ns3::WifiRemoteStationManager::ReportFinalDataFailed(), ns3::WifiRemoteStationManager::ReportFinalRtsFailed(), ns3::WifiRemoteStationManager::ReportRtsFailed(), ns3::WifiRemoteStationManager::ReportRtsOk(), ns3::QosTxop::StartNextPacket(), ns3::MacLow::StartTransmission(), ns3::BlockAckManager::StorePacket(), BlockAckAggregationDisabledTest::Transmit(), and QosFragmentationTestCase::Transmit().
IsQosEosp()
bool ns3::WifiMacHeader::IsQosEosp (void) const
Return if the end of service period (EOSP) is set.
Returns
true if the end of service period (EOSP) is set, false otherwise
Definition at line 785 of file wifi-mac-header.cc.
References IsQosData(), m_qosEosp, and NS_ASSERT.
IsQosNoAck()
bool ns3::WifiMacHeader::IsQosNoAck (void) const
Return if the QoS Ack policy is No Ack.
Returns
true if the QoS Ack policy is No Ack, false otherwise
Definition at line 771 of file wifi-mac-header.cc.
References IsQosData(), m_qosAckPolicy, and NS_ASSERT.
Referenced by ns3::WifiMacQueueItem::Print(), and ns3::MacLow::ReceiveOk().
IsReassocReq()
bool ns3::WifiMacHeader::IsReassocReq (void) const
Return true if the header is a Reassociation Request header.
Returns
true if the header is a Reassociation Request header, false otherwise
Definition at line 650 of file wifi-mac-header.cc.
References GetType(), and ns3::WIFI_MAC_MGT_REASSOCIATION_REQUEST.
Referenced by ns3::ApWifiMac::Receive(), ns3::StaWifiMac::Receive(), and Bug2831TestCase::RxCallback().
IsReassocResp()
bool ns3::WifiMacHeader::IsReassocResp (void) const
Return true if the header is a Reassociation Response header.
Returns
true if the header is a Reassociation Response header, false otherwise
Definition at line 656 of file wifi-mac-header.cc.
References GetType(), and ns3::WIFI_MAC_MGT_REASSOCIATION_RESPONSE.
Referenced by ns3::StaWifiMac::Receive(), Bug2831TestCase::RxCallback(), ns3::ApWifiMac::TxFailed(), and ns3::ApWifiMac::TxOk().
IsRetry()
bool ns3::WifiMacHeader::IsRetry (void) const
Return if the Retry bit is set.
Returns
true if the Retry bit is set, false otherwise
Definition at line 752 of file wifi-mac-header.cc.
References m_ctrlRetry.
Referenced by ns3::MacRxMiddle::IsDuplicate().
IsRts()
bool ns3::WifiMacHeader::IsRts (void) const
Return true if the header is a RTS header.
Returns
true if the header is a RTS header, false otherwise
Definition at line 620 of file wifi-mac-header.cc.
References GetType(), and ns3::WIFI_MAC_CTL_RTS.
Referenced by ns3::MacLow::NotifyNav(), and ns3::MacLow::ReceiveOk().
IsToDs()
bool ns3::WifiMacHeader::IsToDs (void) const
Returns
true if To DS bit is set, false otherwise
Definition at line 521 of file wifi-mac-header.cc.
References m_ctrlToDs.
Referenced by ns3::WifiMacQueueItem::Aggregate(), ns3::ApWifiMac::Receive(), ns3::StaWifiMac::Receive(), ns3::PyViz::TraceNetDevRxWifi(), and ns3::PyViz::TraceNetDevTxWifi().
Print()
void ns3::WifiMacHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 1015 of file wifi-mac-header.cc.
References GetType(), GetTypeString(), m_addr1, m_addr2, m_addr3, m_addr4, m_ctrlFromDs, m_ctrlToDs, m_duration, m_seqFrag, m_seqSeq, NS_FATAL_ERROR, PrintFrameControl(), ns3::WIFI_MAC_CTL_ACK, ns3::WIFI_MAC_CTL_BACKREQ, ns3::WIFI_MAC_CTL_BACKRESP, ns3::WIFI_MAC_CTL_CTLWRAPPER, ns3::WIFI_MAC_CTL_CTS, ns3::WIFI_MAC_CTL_END, ns3::WIFI_MAC_CTL_END_ACK, ns3::WIFI_MAC_CTL_RTS, ns3::WIFI_MAC_DATA, ns3::WIFI_MAC_DATA_CFACK, ns3::WIFI_MAC_DATA_CFACK_CFPOLL, ns3::WIFI_MAC_DATA_CFPOLL, ns3::WIFI_MAC_DATA_NULL, ns3::WIFI_MAC_DATA_NULL_CFACK, ns3::WIFI_MAC_DATA_NULL_CFACK_CFPOLL, ns3::WIFI_MAC_DATA_NULL_CFPOLL, ns3::WIFI_MAC_MGT_ACTION, ns3::WIFI_MAC_MGT_ACTION_NO_ACK, ns3::WIFI_MAC_MGT_ASSOCIATION_REQUEST, ns3::WIFI_MAC_MGT_ASSOCIATION_RESPONSE, ns3::WIFI_MAC_MGT_AUTHENTICATION, ns3::WIFI_MAC_MGT_BEACON, ns3::WIFI_MAC_MGT_DEAUTHENTICATION, ns3::WIFI_MAC_MGT_DISASSOCIATION, ns3::WIFI_MAC_MGT_MULTIHOP_ACTION, ns3::WIFI_MAC_MGT_PROBE_REQUEST, ns3::WIFI_MAC_MGT_PROBE_RESPONSE, ns3::WIFI_MAC_MGT_REASSOCIATION_REQUEST, ns3::WIFI_MAC_MGT_REASSOCIATION_RESPONSE, ns3::WIFI_MAC_QOSDATA, ns3::WIFI_MAC_QOSDATA_CFACK, ns3::WIFI_MAC_QOSDATA_CFACK_CFPOLL, ns3::WIFI_MAC_QOSDATA_CFPOLL, ns3::WIFI_MAC_QOSDATA_NULL, ns3::WIFI_MAC_QOSDATA_NULL_CFACK_CFPOLL, and ns3::WIFI_MAC_QOSDATA_NULL_CFPOLL.
PrintFrameControl()
void ns3::WifiMacHeader::PrintFrameControl (std::ostream & os) const private
Print the Frame Control field to the output stream.
Parameters
os the output stream to print to
Definition at line 1006 of file wifi-mac-header.cc.
References m_ctrlFromDs, m_ctrlMoreData, m_ctrlMoreFrag, m_ctrlRetry, and m_ctrlToDs.
Referenced by Print().
Serialize()
void ns3::WifiMacHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 1114 of file wifi-mac-header.cc.
References GetFrameControl(), GetQosControl(), GetSequenceControl(), m_addr1, m_addr2, m_addr3, m_addr4, m_ctrlFromDs, m_ctrlSubtype, m_ctrlToDs, m_ctrlType, m_duration, NS_ASSERT, ns3::SUBTYPE_CTL_ACK, ns3::SUBTYPE_CTL_BACKREQ, ns3::SUBTYPE_CTL_BACKRESP, ns3::SUBTYPE_CTL_CTS, ns3::SUBTYPE_CTL_END, ns3::SUBTYPE_CTL_END_ACK, ns3::SUBTYPE_CTL_RTS, ns3::TYPE_CTL, ns3::TYPE_DATA, ns3::TYPE_MGT, ns3::Buffer::Iterator::WriteHtolsbU16(), and ns3::WriteTo().
SetAddr1()
void ns3::WifiMacHeader::SetAddr1 (Mac48Address address)
Fill the Address 1 field with the given address.
Parameters
address the address to be used in the Address 1 field
Definition at line 90 of file wifi-mac-header.cc.
References first::address, and m_addr1.
Referenced by ns3::MeshWifiBeacon::CreateHeader(), AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), HeAggregationTest::DoRunSubTest(), ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::StaWifiMac::Enqueue(), ns3::MeshWifiInterfaceMac::ForwardDown(), ns3::ApWifiMac::ForwardDown(), ns3::dot11s::HwmpProtocolMac::ForwardPerr(), ns3::BlockAckManager::NotifyDiscardedMpdu(), ns3::QosTxop::PrepareBlockAckRequest(), ns3::MacLow::SendAckAfterData(), ns3::QosTxop::SendAddBaRequest(), ns3::RegularWifiMac::SendAddBaResponse(), ns3::StaWifiMac::SendAssociationRequest(), ns3::ApWifiMac::SendAssocResp(), ns3::MacLow::SendBlockAckResponse(), ns3::Txop::SendCfFrame(), ns3::MacLow::SendCtsAfterRts(), ns3::MacLow::SendCtsToSelf(), ns3::MacLow::SendDataPacket(), ns3::QosTxop::SendDelbaFrame(), ns3::ApWifiMac::SendOneBeacon(), ns3::dot11s::PeerManagementProtocolMac::SendPeerLinkManagementFrame(), ns3::dot11s::HwmpProtocolMac::SendPrep(), ns3::dot11s::HwmpProtocolMac::SendPreq(), ns3::StaWifiMac::SendProbeRequest(), ns3::ApWifiMac::SendProbeResp(), ns3::MacLow::SendRtsForPacket(), ns3::OcbWifiMac::SendVsc(), ns3::dot11s::HwmpProtocolMac::UpdateOutcomingFrame(), and ns3::flame::FlameProtocolMac::UpdateOutcomingFrame().
SetAddr2()
void ns3::WifiMacHeader::SetAddr2 (Mac48Address address)
Fill the Address 2 field with the given address.
Parameters
address the address to be used in the Address 2 field
Definition at line 96 of file wifi-mac-header.cc.
References first::address, and m_addr2.
Referenced by ns3::MeshWifiBeacon::CreateHeader(), AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), HeAggregationTest::DoRunSubTest(), ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::StaWifiMac::Enqueue(), ns3::MeshWifiInterfaceMac::ForwardDown(), ns3::ApWifiMac::ForwardDown(), ns3::dot11s::HwmpProtocolMac::ForwardPerr(), ns3::BlockAckManager::NotifyDiscardedMpdu(), ns3::QosTxop::PrepareBlockAckRequest(), ns3::QosTxop::SendAddBaRequest(), ns3::RegularWifiMac::SendAddBaResponse(), ns3::StaWifiMac::SendAssociationRequest(), ns3::ApWifiMac::SendAssocResp(), ns3::MacLow::SendBlockAckResponse(), ns3::Txop::SendCfFrame(), ns3::QosTxop::SendDelbaFrame(), ns3::ApWifiMac::SendOneBeacon(), ns3::dot11s::PeerManagementProtocolMac::SendPeerLinkManagementFrame(), ns3::dot11s::HwmpProtocolMac::SendPrep(), ns3::dot11s::HwmpProtocolMac::SendPreq(), ns3::StaWifiMac::SendProbeRequest(), ns3::ApWifiMac::SendProbeResp(), ns3::MacLow::SendRtsForPacket(), and ns3::OcbWifiMac::SendVsc().
SetAddr3()
void ns3::WifiMacHeader::SetAddr3 (Mac48Address address)
Fill the Address 3 field with the given address.
Parameters
address the address to be used in the Address 3 field
Definition at line 102 of file wifi-mac-header.cc.
References first::address, and m_addr3.
Referenced by ns3::WifiMacQueueItem::Aggregate(), ns3::MeshWifiBeacon::CreateHeader(), ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::StaWifiMac::Enqueue(), ns3::MeshWifiInterfaceMac::ForwardDown(), ns3::ApWifiMac::ForwardDown(), ns3::dot11s::HwmpProtocolMac::ForwardPerr(), ns3::BlockAckManager::NotifyDiscardedMpdu(), ns3::QosTxop::SendAddBaRequest(), ns3::RegularWifiMac::SendAddBaResponse(), ns3::StaWifiMac::SendAssociationRequest(), ns3::ApWifiMac::SendAssocResp(), ns3::Txop::SendCfFrame(), ns3::QosTxop::SendDelbaFrame(), ns3::ApWifiMac::SendOneBeacon(), ns3::dot11s::PeerManagementProtocolMac::SendPeerLinkManagementFrame(), ns3::dot11s::HwmpProtocolMac::SendPrep(), ns3::dot11s::HwmpProtocolMac::SendPreq(), ns3::StaWifiMac::SendProbeRequest(), ns3::ApWifiMac::SendProbeResp(), and ns3::OcbWifiMac::SendVsc().
SetAddr4()
void ns3::WifiMacHeader::SetAddr4 (Mac48Address address)
Fill the Address 4 field with the given address.
Parameters
address the address to be used in the Address 4 field
Definition at line 108 of file wifi-mac-header.cc.
References first::address, and m_addr4.
Referenced by ns3::MeshWifiInterfaceMac::ForwardDown().
SetDsFrom()
void ns3::WifiMacHeader::SetDsFrom (void)
Set the From DS bit in the Frame Control field.
Definition at line 66 of file wifi-mac-header.cc.
References m_ctrlFromDs.
Referenced by ns3::MeshWifiInterfaceMac::ForwardDown(), ns3::ApWifiMac::ForwardDown(), ns3::Txop::SendCfFrame(), and ns3::dot11s::AirtimeLinkMetricCalculator::SetHeaderTid().
SetDsNotFrom()
void ns3::WifiMacHeader::SetDsNotFrom (void)
Un-set the From DS bit in the Frame Control field.
Definition at line 72 of file wifi-mac-header.cc.
References m_ctrlFromDs.
Referenced by ns3::MeshWifiBeacon::CreateHeader(), ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::StaWifiMac::Enqueue(), ns3::dot11s::HwmpProtocolMac::ForwardPerr(), ns3::BlockAckManager::NotifyDiscardedMpdu(), ns3::QosTxop::PrepareBlockAckRequest(), ns3::MacLow::SendAckAfterData(), ns3::QosTxop::SendAddBaRequest(), ns3::RegularWifiMac::SendAddBaResponse(), ns3::StaWifiMac::SendAssociationRequest(), ns3::ApWifiMac::SendAssocResp(), ns3::MacLow::SendBlockAckResponse(), ns3::Txop::SendCfFrame(), ns3::MacLow::SendCtsAfterRts(), ns3::MacLow::SendCtsToSelf(), ns3::QosTxop::SendDelbaFrame(), ns3::ApWifiMac::SendOneBeacon(), ns3::dot11s::PeerManagementProtocolMac::SendPeerLinkManagementFrame(), ns3::dot11s::HwmpProtocolMac::SendPrep(), ns3::dot11s::HwmpProtocolMac::SendPreq(), ns3::StaWifiMac::SendProbeRequest(), ns3::ApWifiMac::SendProbeResp(), ns3::MacLow::SendRtsForPacket(), and ns3::OcbWifiMac::SendVsc().
SetDsNotTo()
void ns3::WifiMacHeader::SetDsNotTo (void)
Un-set the To DS bit in the Frame Control field.
Definition at line 84 of file wifi-mac-header.cc.
References m_ctrlToDs.
Referenced by ns3::MeshWifiBeacon::CreateHeader(), ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::ApWifiMac::ForwardDown(), ns3::dot11s::HwmpProtocolMac::ForwardPerr(), ns3::BlockAckManager::NotifyDiscardedMpdu(), ns3::QosTxop::PrepareBlockAckRequest(), ns3::MacLow::SendAckAfterData(), ns3::QosTxop::SendAddBaRequest(), ns3::RegularWifiMac::SendAddBaResponse(), ns3::StaWifiMac::SendAssociationRequest(), ns3::ApWifiMac::SendAssocResp(), ns3::MacLow::SendBlockAckResponse(), ns3::Txop::SendCfFrame(), ns3::MacLow::SendCtsAfterRts(), ns3::MacLow::SendCtsToSelf(), ns3::QosTxop::SendDelbaFrame(), ns3::ApWifiMac::SendOneBeacon(), ns3::dot11s::PeerManagementProtocolMac::SendPeerLinkManagementFrame(), ns3::dot11s::HwmpProtocolMac::SendPrep(), ns3::dot11s::HwmpProtocolMac::SendPreq(), ns3::StaWifiMac::SendProbeRequest(), ns3::ApWifiMac::SendProbeResp(), ns3::MacLow::SendRtsForPacket(), and ns3::OcbWifiMac::SendVsc().
SetDsTo()
void ns3::WifiMacHeader::SetDsTo (void)
Set the To DS bit in the Frame Control field.
Definition at line 78 of file wifi-mac-header.cc.
References m_ctrlToDs.
Referenced by ns3::StaWifiMac::Enqueue(), ns3::MeshWifiInterfaceMac::ForwardDown(), ns3::Txop::SendCfFrame(), and ns3::dot11s::AirtimeLinkMetricCalculator::SetHeaderTid().
SetDuration()
void ns3::WifiMacHeader::SetDuration (Time duration)
Set the Duration/ID field with the given duration (Time object).
The method converts the given time to microseconds.
Parameters
duration the duration (Time object)
Definition at line 278 of file wifi-mac-header.cc.
References aloha::duration, m_duration, and NS_ASSERT.
Referenced by ns3::MacLow::SendAckAfterData(), ns3::MacLow::SendBlockAckResponse(), ns3::MacLow::SendCtsAfterRts(), ns3::MacLow::SendCtsToSelf(), and ns3::MacLow::SendRtsForPacket().
SetFragmentNumber()
void ns3::WifiMacHeader::SetFragmentNumber (uint8_t frag)
Set the fragment number of the header.
Parameters
frag the given fragment number
Definition at line 295 of file wifi-mac-header.cc.
References m_seqFrag.
Referenced by ns3::QosTxop::DequeuePeekedFrame(), AmpduAggregationTest::DoRun(), HeAggregationTest::DoRunSubTest(), ns3::QosTxop::GetFragmentPacket(), ns3::Txop::GetFragmentPacket(), ns3::Txop::NotifyAccessGranted(), ns3::QosTxop::PeekNextFrame(), ns3::QosTxop::SendAddBaRequest(), and ns3::Txop::SendCfFrame().
SetFrameControl()
void ns3::WifiMacHeader::SetFrameControl (uint16_t control) private
Set the Frame Control field with the given raw value.
Parameters
control the raw Frame Control field value
Definition at line 860 of file wifi-mac-header.cc.
References m_ctrlFromDs, m_ctrlMoreData, m_ctrlMoreFrag, m_ctrlOrder, m_ctrlRetry, m_ctrlSubtype, m_ctrlToDs, m_ctrlType, and m_ctrlWep.
Referenced by Deserialize().
SetId()
void ns3::WifiMacHeader::SetId (uint16_t id)
Set the Duration/ID field with the given ID.
Parameters
id the ID
Definition at line 285 of file wifi-mac-header.cc.
References m_duration.
SetMoreFragments()
void ns3::WifiMacHeader::SetMoreFragments (void)
Set the More Fragment bit in the Frame Control field.
Definition at line 305 of file wifi-mac-header.cc.
References m_ctrlMoreFrag.
Referenced by ns3::QosTxop::GetFragmentPacket(), and ns3::Txop::GetFragmentPacket().
SetNoMoreFragments()
void ns3::WifiMacHeader::SetNoMoreFragments (void)
Un-set the More Fragment bit in the Frame Control Field.
Definition at line 300 of file wifi-mac-header.cc.
References m_ctrlMoreFrag.
Referenced by ns3::QosTxop::DequeuePeekedFrame(), AmpduAggregationTest::DoRun(), HeAggregationTest::DoRunSubTest(), ns3::QosTxop::GetFragmentPacket(), ns3::Txop::GetFragmentPacket(), ns3::Txop::NotifyAccessGranted(), ns3::BlockAckManager::NotifyDiscardedMpdu(), ns3::QosTxop::PeekNextFrame(), ns3::QosTxop::PrepareBlockAckRequest(), ns3::MacLow::SendAckAfterData(), ns3::QosTxop::SendAddBaRequest(), ns3::MacLow::SendBlockAckResponse(), ns3::Txop::SendCfFrame(), ns3::MacLow::SendCtsAfterRts(), ns3::MacLow::SendCtsToSelf(), and ns3::MacLow::SendRtsForPacket().
SetNoOrder()
void ns3::WifiMacHeader::SetNoOrder (void)
Unset order bit in the frame control field.
Definition at line 315 of file wifi-mac-header.cc.
References m_ctrlOrder.
Referenced by ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::StaWifiMac::Enqueue(), and ns3::ApWifiMac::ForwardDown().
SetNoRetry()
void ns3::WifiMacHeader::SetNoRetry (void)
Un-set the Retry bit in the Frame Control field.
Definition at line 325 of file wifi-mac-header.cc.
References m_ctrlRetry.
Referenced by ns3::QosTxop::DequeuePeekedFrame(), AmpduAggregationTest::DoRun(), HeAggregationTest::DoRunSubTest(), ns3::Txop::NotifyAccessGranted(), ns3::BlockAckManager::NotifyDiscardedMpdu(), ns3::QosTxop::PeekNextFrame(), ns3::QosTxop::PrepareBlockAckRequest(), ns3::MacLow::SendAckAfterData(), ns3::QosTxop::SendAddBaRequest(), ns3::MacLow::SendBlockAckResponse(), ns3::Txop::SendCfFrame(), ns3::MacLow::SendCtsAfterRts(), ns3::MacLow::SendCtsToSelf(), and ns3::MacLow::SendRtsForPacket().
SetOrder()
void ns3::WifiMacHeader::SetOrder (void)
Set order bit in the frame control field.
Definition at line 310 of file wifi-mac-header.cc.
References m_ctrlOrder.
SetQosAckPolicy()
void ns3::WifiMacHeader::SetQosAckPolicy (QosAckPolicy policy)
Set the QoS Ack policy in the QoS control field.
Parameters
policy the Qos Ack policy
Definition at line 345 of file wifi-mac-header.cc.
References BLOCK_ACK, m_qosAckPolicy, NO_ACK, NO_EXPLICIT_ACK, and NORMAL_ACK.
Referenced by ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::StaWifiMac::Enqueue(), ns3::MeshWifiInterfaceMac::ForwardDown(), ns3::ApWifiMac::ForwardDown(), and ns3::MpduAggregator::GetNextAmpdu().
SetQosAmsdu()
void ns3::WifiMacHeader::SetQosAmsdu (void)
Set that A-MSDU is present.
Definition at line 364 of file wifi-mac-header.cc.
References m_amsduPresent.
Referenced by ns3::WifiMacQueueItem::Aggregate().
SetQosControl()
void ns3::WifiMacHeader::SetQosControl (uint16_t qos) private
Set the QoS Control field with the given raw value.
Parameters
qos the raw QoS Control field value
Definition at line 879 of file wifi-mac-header.cc.
References m_amsduPresent, m_qosAckPolicy, m_qosEosp, m_qosStuff, and m_qosTid.
Referenced by Deserialize().
SetQosEosp()
void ns3::WifiMacHeader::SetQosEosp ()
Set the end of service period (EOSP) bit in the QoS control field.
Definition at line 335 of file wifi-mac-header.cc.
References m_qosEosp.
SetQosMeshControlPresent()
void ns3::WifiMacHeader::SetQosMeshControlPresent ()
Set the Mesh Control Present flag for the QoS header.
Definition at line 379 of file wifi-mac-header.cc.
References m_qosStuff.
Referenced by ns3::dot11s::HwmpProtocolMac::UpdateOutcomingFrame().
SetQosNoAmsdu()
void ns3::WifiMacHeader::SetQosNoAmsdu (void)
Set that A-MSDU is not present.
Definition at line 369 of file wifi-mac-header.cc.
References m_amsduPresent.
Referenced by ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::StaWifiMac::Enqueue(), ns3::MeshWifiInterfaceMac::ForwardDown(), and ns3::ApWifiMac::ForwardDown().
SetQosNoEosp()
void ns3::WifiMacHeader::SetQosNoEosp ()
Un-set the end of service period (EOSP) bit in the QoS control field.
Definition at line 340 of file wifi-mac-header.cc.
References m_qosEosp.
Referenced by ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::StaWifiMac::Enqueue(), ns3::MeshWifiInterfaceMac::ForwardDown(), and ns3::ApWifiMac::ForwardDown().
SetQosNoMeshControlPresent()
void ns3::WifiMacHeader::SetQosNoMeshControlPresent ()
Clear the Mesh Control Present flag for the QoS header.
Definition at line 386 of file wifi-mac-header.cc.
References m_qosStuff.
SetQosTid()
void ns3::WifiMacHeader::SetQosTid (uint8_t tid)
Set the TID for the QoS header.
Parameters
tid the TID for the QoS header
Definition at line 330 of file wifi-mac-header.cc.
References m_qosTid.
Referenced by AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), HeAggregationTest::DoRunSubTest(), ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::StaWifiMac::Enqueue(), ns3::MeshWifiInterfaceMac::ForwardDown(), ns3::ApWifiMac::ForwardDown(), SpectrumWifiPhyBasicTest::MakeSignal(), WifiPhyThresholdsTest::MakeWifiSignal(), TestAmpduReception::SendAmpduWithThreeMpdus(), TestThresholdPreambleDetectionWithoutFrameCapture::SendPacket(), TestThresholdPreambleDetectionWithFrameCapture::SendPacket(), TestPhyHeadersReception::SendPacket(), TestSimpleFrameCaptureModel::SendPacket(), ns3::dot11s::AirtimeLinkMetricCalculator::SetHeaderTid(), PowerRateAdaptationTest::TestAparf(), PowerRateAdaptationTest::TestParf(), and PowerRateAdaptationTest::TestRrpaa().
SetQosTxopLimit()
void ns3::WifiMacHeader::SetQosTxopLimit (uint8_t txop)
Set TXOP limit in the QoS control field.
Parameters
txop the TXOP limit
Definition at line 374 of file wifi-mac-header.cc.
References m_qosStuff.
Referenced by ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::StaWifiMac::Enqueue(), ns3::MeshWifiInterfaceMac::ForwardDown(), and ns3::ApWifiMac::ForwardDown().
SetRawDuration()
void ns3::WifiMacHeader::SetRawDuration (uint16_t duration)
Set the Duration/ID field with the given raw uint16_t value.
Parameters
duration the raw duration in uint16_t
Definition at line 271 of file wifi-mac-header.cc.
References aloha::duration, m_duration, and NS_ASSERT.
SetRetry()
void ns3::WifiMacHeader::SetRetry (void)
Set the Retry bit in the Frame Control field.
Definition at line 320 of file wifi-mac-header.cc.
References m_ctrlRetry.
Referenced by ns3::BlockAckManager::InsertInRetryQueue(), ns3::QosTxop::MissedAck(), ns3::Txop::MissedAck(), ns3::QosTxop::MissedBlockAck(), ns3::Txop::MissedCfPollResponse(), and ns3::Txop::SendCfFrame().
SetSequenceControl()
void ns3::WifiMacHeader::SetSequenceControl (uint16_t seq) private
Set the Sequence Control field with the given raw value.
Parameters
seq the raw Sequence Control field value
Definition at line 873 of file wifi-mac-header.cc.
References m_seqFrag, and m_seqSeq.
Referenced by Deserialize().
SetSequenceNumber()
void ns3::WifiMacHeader::SetSequenceNumber (uint16_t seq)
Set the sequence number of the header.
Parameters
seq the given sequence number
Definition at line 290 of file wifi-mac-header.cc.
References m_seqSeq.
Referenced by ns3::QosTxop::DequeuePeekedFrame(), OriginatorBlockAckWindowTest::DoRun(), AmpduAggregationTest::DoRun(), HeAggregationTest::DoRunSubTest(), ns3::Txop::NotifyAccessGranted(), ns3::QosTxop::PeekNextFrame(), ns3::QosTxop::SendAddBaRequest(), and ns3::Txop::SendCfFrame().
SetType()
void ns3::WifiMacHeader::SetType (WifiMacType type, bool resetToDsFromDs = true)
Set Type/Subtype values with the correct values depending on the given type.
Parameters
type the WifiMacType for the header
resetToDsFromDs whether the ToDs and FromDs flags should be reset.
Definition at line 114 of file wifi-mac-header.cc.
References m_ctrlFromDs, m_ctrlSubtype, m_ctrlToDs, m_ctrlType, ns3::SUBTYPE_CTL_ACK, ns3::SUBTYPE_CTL_BACKREQ, ns3::SUBTYPE_CTL_BACKRESP, ns3::SUBTYPE_CTL_CTLWRAPPER, ns3::SUBTYPE_CTL_CTS, ns3::SUBTYPE_CTL_END, ns3::SUBTYPE_CTL_END_ACK, ns3::SUBTYPE_CTL_RTS, ns3::TYPE_CTL, ns3::TYPE_DATA, ns3::TYPE_MGT, ns3::WIFI_MAC_CTL_ACK, ns3::WIFI_MAC_CTL_BACKREQ, ns3::WIFI_MAC_CTL_BACKRESP, ns3::WIFI_MAC_CTL_CTLWRAPPER, ns3::WIFI_MAC_CTL_CTS, ns3::WIFI_MAC_CTL_END, ns3::WIFI_MAC_CTL_END_ACK, ns3::WIFI_MAC_CTL_RTS, ns3::WIFI_MAC_DATA, ns3::WIFI_MAC_DATA_CFACK, ns3::WIFI_MAC_DATA_CFACK_CFPOLL, ns3::WIFI_MAC_DATA_CFPOLL, ns3::WIFI_MAC_DATA_NULL, ns3::WIFI_MAC_DATA_NULL_CFACK, ns3::WIFI_MAC_DATA_NULL_CFACK_CFPOLL, ns3::WIFI_MAC_DATA_NULL_CFPOLL, ns3::WIFI_MAC_MGT_ACTION, ns3::WIFI_MAC_MGT_ACTION_NO_ACK, ns3::WIFI_MAC_MGT_ASSOCIATION_REQUEST, ns3::WIFI_MAC_MGT_ASSOCIATION_RESPONSE, ns3::WIFI_MAC_MGT_AUTHENTICATION, ns3::WIFI_MAC_MGT_BEACON, ns3::WIFI_MAC_MGT_DEAUTHENTICATION, ns3::WIFI_MAC_MGT_DISASSOCIATION, ns3::WIFI_MAC_MGT_MULTIHOP_ACTION, ns3::WIFI_MAC_MGT_PROBE_REQUEST, ns3::WIFI_MAC_MGT_PROBE_RESPONSE, ns3::WIFI_MAC_MGT_REASSOCIATION_REQUEST, ns3::WIFI_MAC_MGT_REASSOCIATION_RESPONSE, ns3::WIFI_MAC_QOSDATA, ns3::WIFI_MAC_QOSDATA_CFACK, ns3::WIFI_MAC_QOSDATA_CFACK_CFPOLL, ns3::WIFI_MAC_QOSDATA_CFPOLL, ns3::WIFI_MAC_QOSDATA_NULL, ns3::WIFI_MAC_QOSDATA_NULL_CFACK_CFPOLL, and ns3::WIFI_MAC_QOSDATA_NULL_CFPOLL.
Referenced by ns3::InterferenceHelper::AddForeignSignal(), ns3::MacLow::CanTransmitNextCfFrame(), ns3::MeshWifiBeacon::CreateHeader(), OriginatorBlockAckWindowTest::DoRun(), AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), HeAggregationTest::DoRunSubTest(), ns3::OcbWifiMac::Enqueue(), ns3::AdhocWifiMac::Enqueue(), ns3::StaWifiMac::Enqueue(), ns3::MeshWifiInterfaceMac::ForwardDown(), ns3::ApWifiMac::ForwardDown(), ns3::dot11s::HwmpProtocolMac::ForwardPerr(), ns3::GetAckSize(), ns3::GetBlockAckRequestSize(), ns3::GetBlockAckSize(), ns3::MacLow::GetCfEndSize(), ns3::GetCtsSize(), ns3::GetRtsSize(), SpectrumWifiPhyBasicTest::MakeSignal(), WifiPhyThresholdsTest::MakeWifiSignal(), ns3::BlockAckManager::NotifyDiscardedMpdu(), ns3::MacLow::NotifyNav(), ns3::QosTxop::PrepareBlockAckRequest(), InterferenceExperiment::SendA(), ns3::MacLow::SendAckAfterData(), ns3::QosTxop::SendAddBaRequest(), ns3::RegularWifiMac::SendAddBaResponse(), TestAmpduReception::SendAmpduWithThreeMpdus(), ns3::StaWifiMac::SendAssociationRequest(), ns3::ApWifiMac::SendAssocResp(), InterferenceExperiment::SendB(), ns3::MacLow::SendBlockAckResponse(), ns3::Txop::SendCfFrame(), ns3::MacLow::SendCtsAfterRts(), ns3::MacLow::SendCtsToSelf(), ns3::QosTxop::SendDelbaFrame(), ns3::ApWifiMac::SendOneBeacon(), TestThresholdPreambleDetectionWithoutFrameCapture::SendPacket(), TestThresholdPreambleDetectionWithFrameCapture::SendPacket(), TestPhyHeadersReception::SendPacket(), TestSimpleFrameCaptureModel::SendPacket(), ns3::dot11s::PeerManagementProtocolMac::SendPeerLinkManagementFrame(), ns3::dot11s::HwmpProtocolMac::SendPrep(), ns3::dot11s::HwmpProtocolMac::SendPreq(), ns3::StaWifiMac::SendProbeRequest(), ns3::ApWifiMac::SendProbeResp(), ns3::MacLow::SendRtsForPacket(), ns3::OcbWifiMac::SendVsc(), ns3::dot11s::AirtimeLinkMetricCalculator::SetHeaderTid(), PowerRateAdaptationTest::TestAparf(), PowerRateAdaptationTest::TestParf(), and PowerRateAdaptationTest::TestRrpaa().
Member Data Documentation
m_addr1
Mac48Address ns3::WifiMacHeader::m_addr1 private
address 1
Definition at line 617 of file wifi-mac-header.h.
Referenced by Deserialize(), GetAddr1(), Print(), Serialize(), and SetAddr1().
m_addr2
Mac48Address ns3::WifiMacHeader::m_addr2 private
address 2
Definition at line 618 of file wifi-mac-header.h.
Referenced by Deserialize(), GetAddr2(), Print(), Serialize(), and SetAddr2().
m_addr3
Mac48Address ns3::WifiMacHeader::m_addr3 private
address 3
Definition at line 619 of file wifi-mac-header.h.
Referenced by Deserialize(), GetAddr3(), Print(), Serialize(), and SetAddr3().
m_addr4
Mac48Address ns3::WifiMacHeader::m_addr4 private
address 4
Definition at line 622 of file wifi-mac-header.h.
Referenced by Deserialize(), GetAddr4(), Print(), Serialize(), and SetAddr4().
m_amsduPresent
uint8_t ns3::WifiMacHeader::m_amsduPresent private
A-MSDU present.
Definition at line 626 of file wifi-mac-header.h.
Referenced by GetQosControl(), IsQosAmsdu(), SetQosAmsdu(), SetQosControl(), and SetQosNoAmsdu().
m_ctrlFromDs
uint8_t ns3::WifiMacHeader::m_ctrlFromDs private
control from DS
Definition at line 610 of file wifi-mac-header.h.
Referenced by Deserialize(), GetFrameControl(), GetSize(), IsFromDs(), Print(), PrintFrameControl(), Serialize(), SetDsFrom(), SetDsNotFrom(), SetFrameControl(), and SetType().
m_ctrlMoreData
uint8_t ns3::WifiMacHeader::m_ctrlMoreData private
control more data
Definition at line 613 of file wifi-mac-header.h.
Referenced by GetFrameControl(), PrintFrameControl(), and SetFrameControl().
m_ctrlMoreFrag
uint8_t ns3::WifiMacHeader::m_ctrlMoreFrag private
control more fragments
Definition at line 611 of file wifi-mac-header.h.
Referenced by GetFrameControl(), IsMoreFragments(), PrintFrameControl(), SetFrameControl(), SetMoreFragments(), and SetNoMoreFragments().
m_ctrlOrder
uint8_t ns3::WifiMacHeader::m_ctrlOrder private
control order (set to 1 for QoS Data and Management frames to signify that HT/VHT/HE control field is present, knowing that the latter are not implemented yet)
Definition at line 615 of file wifi-mac-header.h.
Referenced by GetFrameControl(), SetFrameControl(), SetNoOrder(), and SetOrder().
m_ctrlRetry
uint8_t ns3::WifiMacHeader::m_ctrlRetry private
control retry
Definition at line 612 of file wifi-mac-header.h.
Referenced by GetFrameControl(), IsRetry(), PrintFrameControl(), SetFrameControl(), SetNoRetry(), and SetRetry().
m_ctrlSubtype
uint8_t ns3::WifiMacHeader::m_ctrlSubtype private
control subtype
Definition at line 608 of file wifi-mac-header.h.
Referenced by Deserialize(), GetFrameControl(), GetSize(), GetType(), IsQosData(), Serialize(), SetFrameControl(), and SetType().
m_ctrlToDs
uint8_t ns3::WifiMacHeader::m_ctrlToDs private
control to DS
Definition at line 609 of file wifi-mac-header.h.
Referenced by Deserialize(), GetFrameControl(), GetSize(), IsToDs(), Print(), PrintFrameControl(), Serialize(), SetDsNotTo(), SetDsTo(), SetFrameControl(), and SetType().
m_ctrlType
uint8_t ns3::WifiMacHeader::m_ctrlType private
control type
Definition at line 607 of file wifi-mac-header.h.
Referenced by Deserialize(), GetFrameControl(), GetSize(), GetType(), IsCtl(), IsData(), IsMgt(), IsQosData(), Serialize(), SetFrameControl(), and SetType().
m_ctrlWep
uint8_t ns3::WifiMacHeader::m_ctrlWep private
control WEP
Definition at line 614 of file wifi-mac-header.h.
Referenced by GetFrameControl(), and SetFrameControl().
m_duration
uint16_t ns3::WifiMacHeader::m_duration private
duration
Definition at line 616 of file wifi-mac-header.h.
Referenced by Deserialize(), GetDuration(), GetRawDuration(), Print(), Serialize(), SetDuration(), SetId(), and SetRawDuration().
m_qosAckPolicy
uint8_t ns3::WifiMacHeader::m_qosAckPolicy private
QoS Ack policy.
Definition at line 625 of file wifi-mac-header.h.
Referenced by GetQosAckPolicy(), GetQosControl(), IsQosAck(), IsQosBlockAck(), IsQosNoAck(), SetQosAckPolicy(), and SetQosControl().
m_qosEosp
uint8_t ns3::WifiMacHeader::m_qosEosp private
QoS EOSP.
Definition at line 624 of file wifi-mac-header.h.
Referenced by GetQosControl(), IsQosEosp(), SetQosControl(), SetQosEosp(), and SetQosNoEosp().
m_qosStuff
uint8_t ns3::WifiMacHeader::m_qosStuff private
QoS stuff.
Definition at line 627 of file wifi-mac-header.h.
Referenced by GetQosControl(), SetQosControl(), SetQosMeshControlPresent(), SetQosNoMeshControlPresent(), and SetQosTxopLimit().
m_qosTid
uint8_t ns3::WifiMacHeader::m_qosTid private
QoS TID.
Definition at line 623 of file wifi-mac-header.h.
Referenced by GetQosControl(), GetQosTid(), SetQosControl(), and SetQosTid().
m_seqFrag
uint8_t ns3::WifiMacHeader::m_seqFrag private
sequence fragment
Definition at line 620 of file wifi-mac-header.h.
Referenced by GetFragmentNumber(), GetSequenceControl(), Print(), SetFragmentNumber(), and SetSequenceControl().
m_seqSeq
uint16_t ns3::WifiMacHeader::m_seqSeq private
sequence sequence
Definition at line 621 of file wifi-mac-header.h.
Referenced by GetSequenceControl(), GetSequenceNumber(), Print(), SetSequenceControl(), and SetSequenceNumber().
The documentation for this class was generated from the following files:
src/wifi/model/wifi-mac-header.h
src/wifi/model/wifi-mac-header.cc