ns-3: ns3::FfMacCschedSapProvider Class Reference
ns3::FfMacCschedSapProvider Class Reference abstract
LTE Models » FF MAC Schedulers
Provides the CSCHED SAP.
#include "ff-mac-csched-sap.h"
Classes
struct CschedCellConfigReqParameters
Parameters of the API primitives.
struct CschedLcConfigReqParameters
Parameters of the CSCHED_LC_CONFIG_REQ primitive.
struct CschedLcReleaseReqParameters
Parameters of the CSCHED_LC_RELEASE_REQ primitive.
struct CschedUeConfigReqParameters
Parameters of the CSCHED_UE_CONFIG_REQ primitive.
struct CschedUeReleaseReqParameters
Parameters of the CSCHED_UE_RELEASE_REQ primitive.
Public Member Functions
virtual ~FfMacCschedSapProvider ()
virtual void CschedCellConfigReq (const struct CschedCellConfigReqParameters &params)=0
CSCHED_CELL_CONFIG_REQ.
virtual void CschedLcConfigReq (const struct CschedLcConfigReqParameters &params)=0
CSCHED_LC_CONFIG_REQ.
virtual void CschedLcReleaseReq (const struct CschedLcReleaseReqParameters &params)=0
CSCHED_LC_RELEASE_REQ.
virtual void CschedUeConfigReq (const struct CschedUeConfigReqParameters &params)=0
CSCHED_UE_CONFIG_REQ.
virtual void CschedUeReleaseReq (const struct CschedUeReleaseReqParameters &params)=0
CSCHED_UE_RELEASE_REQ.
Detailed Description
Provides the CSCHED SAP.
This abstract class defines the MAC Scheduler interface specified in the Femto Forum Technical Document:
LTE MAC Scheduler Interface Specification v1.11
The Technical Document contains a detailed description of the API. The documentation of this class refers to sections of this Technical Document.
You can found an example of the implementation of this interface in the SampleFfMacCschedSapProvider and SampleFfMacCschedSapuser classes
Definition at line 45 of file ff-mac-csched-sap.h.
Constructor & Destructor Documentation
~FfMacCschedSapProvider()
ns3::FfMacCschedSapProvider::~FfMacCschedSapProvider () virtual
Definition at line 25 of file ff-mac-csched-sap.cc.
Member Function Documentation
CschedCellConfigReq()
virtual void ns3::FfMacCschedSapProvider::CschedCellConfigReq (const struct CschedCellConfigReqParameters & params) pure virtual
CSCHED_CELL_CONFIG_REQ.
Parameters
params CschedCellConfigReqParameters
Implemented in ns3::MemberCschedSapProvider< C >.
Referenced by ns3::LteEnbMac::DoConfigureMac().
CschedLcConfigReq()
virtual void ns3::FfMacCschedSapProvider::CschedLcConfigReq (const struct CschedLcConfigReqParameters & params) pure virtual
CSCHED_LC_CONFIG_REQ.
Parameters
params CschedLcConfigReqParameters
Implemented in ns3::MemberCschedSapProvider< C >.
Referenced by ns3::LteEnbMac::DoAddLc().
CschedLcReleaseReq()
virtual void ns3::FfMacCschedSapProvider::CschedLcReleaseReq (const struct CschedLcReleaseReqParameters & params) pure virtual
CSCHED_LC_RELEASE_REQ.
Parameters
params CschedLcReleaseReqParameters
Implemented in ns3::MemberCschedSapProvider< C >.
Referenced by ns3::LteEnbMac::DoReleaseLc().
CschedUeConfigReq()
virtual void ns3::FfMacCschedSapProvider::CschedUeConfigReq (const struct CschedUeConfigReqParameters & params) pure virtual
CSCHED_UE_CONFIG_REQ.
Parameters
params CschedUeConfigReqParameters
Implemented in ns3::MemberCschedSapProvider< C >.
Referenced by ns3::LteEnbMac::DoAddUe(), and ns3::LteEnbMac::DoUeUpdateConfigurationReq().
CschedUeReleaseReq()
virtual void ns3::FfMacCschedSapProvider::CschedUeReleaseReq (const struct CschedUeReleaseReqParameters & params) pure virtual
CSCHED_UE_RELEASE_REQ.
Parameters
params CschedUeReleaseReqParameters
Implemented in ns3::MemberCschedSapProvider< C >.
Referenced by ns3::LteEnbMac::DoRemoveUe().
The documentation for this class was generated from the following files:
src/lte/model/ff-mac-csched-sap.h
src/lte/model/ff-mac-csched-sap.cc