ns-3: ns3::LteUeCcmRrcSapProvider Class Reference
ns3::LteUeCcmRrcSapProvider Class Reference abstract
Service Access Point (SAP) offered by the UE component carrier manager to the UE RRC.
#include "lte-ue-ccm-rrc-sap.h"
Classes
struct LcsConfig
LcsConfig structure.
Public Member Functions
virtual ~LteUeCcmRrcSapProvider ()
virtual std::vector< LteUeCcmRrcSapProvider::LcsConfig > AddLc (uint8_t lcId, LteUeCmacSapProvider::LogicalChannelConfig lcConfig, LteMacSapUser *msu)=0
add a new Logical Channel (LC)
virtual LteMacSapUser * ConfigureSignalBearer (uint8_t lcid, LteUeCmacSapProvider::LogicalChannelConfig lcConfig, LteMacSapUser *msu)=0
Add the Signal Bearer for a specific Ue in LteUeComponenCarrierManager.
virtual void NotifyConnectionReconfigurationMsg ()=0
Notify reconfiguration msg function.
virtual std::vector< uint16_t > RemoveLc (uint8_t lcid)=0
Remove an existing Logical Channel for a Ue in the LteUeComponentCarrierManager.
virtual void Reset ()=0
Reset LC maps.
Friends
class LteMacSapUser
allow LteMacSapUser class friend access
Detailed Description
Service Access Point (SAP) offered by the UE component carrier manager to the UE RRC.
This is the Component Carrier Management SAP Provider, i.e., the part of the SAP that contains the component carrier manager methods called by the Ue RRC instance.
Definition at line 44 of file lte-ue-ccm-rrc-sap.h.
Constructor & Destructor Documentation
~LteUeCcmRrcSapProvider()
ns3::LteUeCcmRrcSapProvider::~LteUeCcmRrcSapProvider () virtual
Definition at line 27 of file lte-ue-ccm-rrc-sap.cc.
Member Function Documentation
AddLc()
virtual std::vector<LteUeCcmRrcSapProvider::LcsConfig> ns3::LteUeCcmRrcSapProvider::AddLc (uint8_t lcId, LteUeCmacSapProvider::LogicalChannelConfig lcConfig, LteMacSapUser * msu) pure virtual
add a new Logical Channel (LC)
Parameters
lcId is the Logical Channel Id
lcConfig is a single structure contains logical Channel Id, Logical Channel config and Component Carrier Id
msu is the pointer to LteMacSapUser related to the Rlc instance
Returns
vector of LcsConfig contains the lc configuration for each Mac the size of the vector is equal to the number of component carrier enabled.
The Logical Channel configurations for each component carrier depend on the algorithm used to split the traffic between the component carriers themself.
Implemented in ns3::MemberLteUeCcmRrcSapProvider< C >.
Referenced by ns3::LteUeRrc::ApplyRadioResourceConfigDedicated().
ConfigureSignalBearer()
virtual LteMacSapUser* ns3::LteUeCcmRrcSapProvider::ConfigureSignalBearer (uint8_t lcid, LteUeCmacSapProvider::LogicalChannelConfig lcConfig, LteMacSapUser * msu) pure virtual
Add the Signal Bearer for a specific Ue in LteUeComponenCarrierManager.
Parameters
lcid the Logical Channel Id
lcConfig this structure it is hard-coded in the LteEnbRrc
msu it is the MacSapUser of the Rlc istance
Returns
the LteMacSapUser of the ComponentCarrierManager
Implemented in ns3::MemberLteUeCcmRrcSapProvider< C >.
Referenced by ns3::LteUeRrc::ApplyRadioResourceConfigDedicated(), and ns3::LteUeRrc::DoInitialize().
NotifyConnectionReconfigurationMsg()
virtual void ns3::LteUeCcmRrcSapProvider::NotifyConnectionReconfigurationMsg () pure virtual
Notify reconfiguration msg function.
Implemented in ns3::MemberLteUeCcmRrcSapProvider< C >.
RemoveLc()
virtual std::vector<uint16_t> ns3::LteUeCcmRrcSapProvider::RemoveLc (uint8_t lcid) pure virtual
Remove an existing Logical Channel for a Ue in the LteUeComponentCarrierManager.
Parameters
lcid the Logical Channel Id
Returns
vector of integer the componentCarrierId of the componentCarrier where the bearer is enabled
Implemented in ns3::MemberLteUeCcmRrcSapProvider< C >.
Reset()
virtual void ns3::LteUeCcmRrcSapProvider::Reset () pure virtual
Reset LC maps.
Implemented in ns3::MemberLteUeCcmRrcSapProvider< C >.
Referenced by ns3::LteUeRrc::DoRecvRrcConnectionReconfiguration(), and ns3::LteUeRrc::LeaveConnectedMode().
Friends And Related Function Documentation
LteMacSapUser
friend class LteMacSapUser friend
allow LteMacSapUser class friend access
Definition at line 48 of file lte-ue-ccm-rrc-sap.h.
The documentation for this class was generated from the following files:
src/lte/model/lte-ue-ccm-rrc-sap.h
src/lte/model/lte-ue-ccm-rrc-sap.cc