ns-3: LenaDataPhyErrorModelTestCase Class Reference
LenaDataPhyErrorModelTestCase Class Reference
LTE Models » lte module tests | Test suites
This system test program creates different test cases with a single eNB and several UEs, all having the same Radio Bearer specification. In each test case, the UEs see the same SINR from the eNB; different test cases are implemented obtained by using different SINR values and different numbers of UEs. The test consists on ...
#include "lte-test-phy-error-model.h"
Public Member Functions
LenaDataPhyErrorModelTestCase (uint16_t nUser, uint16_t dist, double blerRef, uint16_t toleranceRxPackets, Time statsStartTime, uint32_t rngRun)
Constructor.
virtual ~LenaDataPhyErrorModelTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Static Private Member Functions
static std::string BuildNameString (uint16_t nUser, uint16_t dist, uint32_t rngRun)
Builds the test name string based on provided parameter values.
Private Attributes
double m_blerRef
the expected BLER
double m_dist
the distance between nodes
uint16_t m_nUser
number of UE nodes
uint32_t m_rngRun
the rng run
Time m_statsStartTime
Extra time in the beginning of simulation to allow RRC connection establishment + SRS.
uint16_t m_toleranceRxPackets
receive packet tolerance loss
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
This system test program creates different test cases with a single eNB and several UEs, all having the same Radio Bearer specification. In each test case, the UEs see the same SINR from the eNB; different test cases are implemented obtained by using different SINR values and different numbers of UEs. The test consists on ...
Definition at line 42 of file lte-test-phy-error-model.h.
Constructor & Destructor Documentation
LenaDataPhyErrorModelTestCase()
LenaDataPhyErrorModelTestCase::LenaDataPhyErrorModelTestCase (uint16_t nUser, uint16_t dist, double blerRef, uint16_t toleranceRxPackets, Time statsStartTime, uint32_t rngRun)
Constructor.
Parameters
nUser the number of UE nodes
dist the distance between nodes
blerRef expected BLER
toleranceRxPackets receive packet loss tolerance
statsStartTime the start time for collecting statistics
rngRun rng run
Definition at line 142 of file lte-test-phy-error-model.cc.
~LenaDataPhyErrorModelTestCase()
LenaDataPhyErrorModelTestCase::~LenaDataPhyErrorModelTestCase () virtual
Definition at line 155 of file lte-test-phy-error-model.cc.
Member Function Documentation
BuildNameString()
std::string LenaDataPhyErrorModelTestCase::BuildNameString (uint16_t nUser, uint16_t dist, uint32_t rngRun) static private
Builds the test name string based on provided parameter values.
Parameters
nUser the number of UE nodes
dist the distance between nodes
rngRun the rng run
Returns
the name string
Definition at line 135 of file lte-test-phy-error-model.cc.
DoRun()
void LenaDataPhyErrorModelTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 160 of file lte-test-phy-error-model.cc.
References ns3::LteHelper::ActivateDataRadioBearer(), ns3::LteHelper::AssignStreams(), ns3::LteHelper::Attach(), ns3::NodeContainer::Create(), ns3::LteHelper::EnableRlcTraces(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::RadioBearerStatsCalculator::GetDlRxPackets(), ns3::RadioBearerStatsCalculator::GetDlTxPackets(), ns3::Time::GetMilliSeconds(), ns3::Object::GetObject(), ns3::LteEnbNetDevice::GetPhy(), ns3::LteUeNetDevice::GetPhy(), ns3::LteHelper::GetRlcStats(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), m_blerRef, m_dist, m_nUser, m_rngRun, m_statsStartTime, m_toleranceRxPackets, third::mobility, NS_LOG_INFO, NS_TEST_ASSERT_MSG_EQ_TOL, NS_UNUSED, ns3::Seconds(), ns3::ObjectBase::SetAttribute(), ns3::Config::SetDefault(), ns3::Config::SetGlobal(), ns3::LteHelper::SetPathlossModelAttribute(), ns3::MobilityModel::SetPosition(), ns3::LteHelper::SetSchedulerAttribute(), and ns3::LteHelper::SetSchedulerType().
Member Data Documentation
m_blerRef
double LenaDataPhyErrorModelTestCase::m_blerRef private
the expected BLER
Definition at line 72 of file lte-test-phy-error-model.h.
Referenced by DoRun().
m_dist
double LenaDataPhyErrorModelTestCase::m_dist private
the distance between nodes
Definition at line 71 of file lte-test-phy-error-model.h.
Referenced by DoRun().
m_nUser
uint16_t LenaDataPhyErrorModelTestCase::m_nUser private
number of UE nodes
Definition at line 70 of file lte-test-phy-error-model.h.
Referenced by DoRun().
m_rngRun
uint32_t LenaDataPhyErrorModelTestCase::m_rngRun private
the rng run
Definition at line 75 of file lte-test-phy-error-model.h.
Referenced by DoRun().
m_statsStartTime
Time LenaDataPhyErrorModelTestCase::m_statsStartTime private
Extra time in the beginning of simulation to allow RRC connection establishment + SRS.
Definition at line 74 of file lte-test-phy-error-model.h.
Referenced by DoRun().
m_toleranceRxPackets
uint16_t LenaDataPhyErrorModelTestCase::m_toleranceRxPackets private
receive packet tolerance loss
Definition at line 73 of file lte-test-phy-error-model.h.
Referenced by DoRun().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-phy-error-model.h
src/lte/test/lte-test-phy-error-model.cc