ns-3: ns3::UeMemberLteUePhySapProvider Class Reference
ns3::UeMemberLteUePhySapProvider Class Reference
UeMemberLteUePhySapProvider class.
Public Member Functions
UeMemberLteUePhySapProvider (LteUePhy *phy)
Constructor.
virtual void NotifyConnectionSuccessful ()
Notify PHY about the successful RRC connection establishment.
virtual void SendLteControlMessage (Ptr< LteControlMessage > msg)
Send SendLteControlMessage (PDCCH map, CQI feedbacks) using the ideal control channel.
virtual void SendMacPdu (Ptr< Packet > p)
Send the MAC PDU to the channel.
virtual void SendRachPreamble (uint32_t prachId, uint32_t raRnti)
Send a preamble on the PRACH.
Public Member Functions inherited from ns3::LteUePhySapProvider
virtual ~LteUePhySapProvider ()
Private Attributes
LteUePhy * m_phy
the Phy
Detailed Description
UeMemberLteUePhySapProvider class.
Definition at line 77 of file lte-ue-phy.cc.
Constructor & Destructor Documentation
UeMemberLteUePhySapProvider()
ns3::UeMemberLteUePhySapProvider::UeMemberLteUePhySapProvider (LteUePhy * phy)
Constructor.
Parameters
phy the LTE UE Phy
Definition at line 97 of file lte-ue-phy.cc.
Member Function Documentation
NotifyConnectionSuccessful()
void ns3::UeMemberLteUePhySapProvider::NotifyConnectionSuccessful () virtual
Notify PHY about the successful RRC connection establishment.
Implements ns3::LteUePhySapProvider.
Definition at line 121 of file lte-ue-phy.cc.
References ns3::LteUePhy::DoNotifyConnectionSuccessful(), and m_phy.
SendLteControlMessage()
void ns3::UeMemberLteUePhySapProvider::SendLteControlMessage (Ptr< LteControlMessage > msg) virtual
Send SendLteControlMessage (PDCCH map, CQI feedbacks) using the ideal control channel.
Parameters
msg the Ideal Control Message to send
Implements ns3::LteUePhySapProvider.
Definition at line 109 of file lte-ue-phy.cc.
References ns3::LteUePhy::DoSendLteControlMessage(), and m_phy.
SendMacPdu()
void ns3::UeMemberLteUePhySapProvider::SendMacPdu (Ptr< Packet > p) virtual
Send the MAC PDU to the channel.
Parameters
p the MAC PDU to send
Returns
true if
Implements ns3::LteUePhySapProvider.
Definition at line 103 of file lte-ue-phy.cc.
References ns3::LteUePhy::DoSendMacPdu(), and m_phy.
SendRachPreamble()
void ns3::UeMemberLteUePhySapProvider::SendRachPreamble (uint32_t prachId, uint32_t raRnti) virtual
Send a preamble on the PRACH.
Parameters
prachId the ID of the preamble
raRnti the RA RNTI
Implements ns3::LteUePhySapProvider.
Definition at line 115 of file lte-ue-phy.cc.
References ns3::LteUePhy::DoSendRachPreamble(), and m_phy.
Member Data Documentation
m_phy
LteUePhy* ns3::UeMemberLteUePhySapProvider::m_phy private
the Phy
Definition at line 94 of file lte-ue-phy.cc.
Referenced by NotifyConnectionSuccessful(), SendLteControlMessage(), SendMacPdu(), and SendRachPreamble().
The documentation for this class was generated from the following file:
src/lte/model/lte-ue-phy.cc