ns-3: ns3::DelayJitterEstimationTimestampTag Class Reference
ns3::DelayJitterEstimationTimestampTag Class Reference
Tag to perform Delay and Jitter estimations.
Public Member Functions
DelayJitterEstimationTimestampTag ()
virtual void Deserialize (TagBuffer i)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize (void) const
Time GetTxTime (void) const
Get the Transmission time stored in the tag.
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer i) const
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint64_t m_creationTime
The time stored in the tag.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Tag to perform Delay and Jitter estimations.
The tag holds the packet's creation timestamp
Definition at line 33 of file delay-jitter-estimation.cc.
Constructor & Destructor Documentation
DelayJitterEstimationTimestampTag()
ns3::DelayJitterEstimationTimestampTag::DelayJitterEstimationTimestampTag ()
Definition at line 59 of file delay-jitter-estimation.cc.
Member Function Documentation
Deserialize()
void ns3::DelayJitterEstimationTimestampTag::Deserialize (TagBuffer i) virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 96 of file delay-jitter-estimation.cc.
References m_creationTime, and ns3::TagBuffer::ReadU64().
GetInstanceTypeId()
TypeId ns3::DelayJitterEstimationTimestampTag::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 80 of file delay-jitter-estimation.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::DelayJitterEstimationTimestampTag::GetSerializedSize (void) const virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 86 of file delay-jitter-estimation.cc.
GetTxTime()
Time ns3::DelayJitterEstimationTimestampTag::GetTxTime (void) const
Get the Transmission time stored in the tag.
Returns
the transmission time
Definition at line 106 of file delay-jitter-estimation.cc.
References m_creationTime, and ns3::TimeStep().
Referenced by GetTypeId(), and ns3::DelayJitterEstimation::RecordRx().
GetTypeId()
TypeId ns3::DelayJitterEstimationTimestampTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 65 of file delay-jitter-estimation.cc.
References GetTxTime(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), and ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::DelayJitterEstimationTimestampTag::Print (std::ostream & os) const virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 101 of file delay-jitter-estimation.cc.
References m_creationTime.
Serialize()
void ns3::DelayJitterEstimationTimestampTag::Serialize (TagBuffer i) const virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 91 of file delay-jitter-estimation.cc.
References m_creationTime, and ns3::TagBuffer::WriteU64().
Member Data Documentation
m_creationTime
uint64_t ns3::DelayJitterEstimationTimestampTag::m_creationTime private
The time stored in the tag.
Definition at line 56 of file delay-jitter-estimation.cc.
Referenced by Deserialize(), GetTxTime(), Print(), and Serialize().
The documentation for this class was generated from the following file:
src/network/helper/delay-jitter-estimation.cc