ns-3: ns3::LteAnrSapProvider Class Reference
ns3::LteAnrSapProvider Class Reference abstract
Service Access Point (SAP) offered by the ANR instance to the eNodeB RRC instance.
#include "lte-anr-sap.h"
Public Member Functions
virtual ~LteAnrSapProvider ()
virtual void AddNeighbourRelation (uint16_t cellId)=0
Add a new Neighbour Relation entry.
virtual bool GetNoHo (uint16_t cellId) const =0
Get the value of No HO field of a neighbouring cell from the Neighbour Relation Table (NRT).
virtual bool GetNoRemove (uint16_t cellId) const =0
Get the value of No Remove field of a neighbouring cell from the Neighbour Relation Table (NRT).
virtual bool GetNoX2 (uint16_t cellId) const =0
Get the value of No X2 field of a neighbouring cell from the Neighbour Relation Table (NRT).
virtual void ReportUeMeas (LteRrcSap::MeasResults measResults)=0
Send a UE measurement report to the ANC instance.
Detailed Description
Service Access Point (SAP) offered by the ANR instance to the eNodeB RRC instance.
This is the ANR SAP Provider, i.e., the part of the SAP that contains the ANR (Automatic Neighbour Relation) methods called by the eNodeB RRC instance.
Definition at line 37 of file lte-anr-sap.h.
Constructor & Destructor Documentation
~LteAnrSapProvider()
ns3::LteAnrSapProvider::~LteAnrSapProvider () virtual
Definition at line 28 of file lte-anr-sap.cc.
Member Function Documentation
AddNeighbourRelation()
virtual void ns3::LteAnrSapProvider::AddNeighbourRelation (uint16_t cellId) pure virtual
Add a new Neighbour Relation entry.
Parameters
cellId the Physical Cell ID of the new neighbouring cell
Implemented in ns3::MemberLteAnrSapProvider< C >.
Referenced by ns3::LteEnbRrc::AddX2Neighbour().
GetNoHo()
virtual bool ns3::LteAnrSapProvider::GetNoHo (uint16_t cellId) const pure virtual
Get the value of No HO field of a neighbouring cell from the Neighbour Relation Table (NRT).
Parameters
cellId the Physical Cell ID of the neighbouring cell of interest
Returns
if true, the Neighbour Relation shall not be used by the eNodeB for handover reasons
Implemented in ns3::MemberLteAnrSapProvider< C >.
Referenced by ns3::LteEnbRrc::DoTriggerHandover().
GetNoRemove()
virtual bool ns3::LteAnrSapProvider::GetNoRemove (uint16_t cellId) const pure virtual
Get the value of No Remove field of a neighbouring cell from the Neighbour Relation Table (NRT).
Parameters
cellId the Physical Cell ID of the neighbouring cell of interest
Returns
if true, the Neighbour Relation shall not be removed from the NRT
Implemented in ns3::MemberLteAnrSapProvider< C >.
GetNoX2()
virtual bool ns3::LteAnrSapProvider::GetNoX2 (uint16_t cellId) const pure virtual
Get the value of No X2 field of a neighbouring cell from the Neighbour Relation Table (NRT).
Parameters
cellId the Physical Cell ID of the neighbouring cell of interest
Returns
if true, the Neighbour Relation shall not use an X2 interface in order to initiate procedures towards the eNodeB parenting the target cell
Implemented in ns3::MemberLteAnrSapProvider< C >.
Referenced by ns3::LteEnbRrc::DoTriggerHandover().
ReportUeMeas()
virtual void ns3::LteAnrSapProvider::ReportUeMeas (LteRrcSap::MeasResults measResults) pure virtual
Send a UE measurement report to the ANC instance.
Parameters
measResults a single report of one measurement identity
The received measurement report is a result of the UE measurement configuration previously configured by calling LteAnrSapUser::AddUeMeasReportConfigForAnr. The report may be stored and utilized for the purpose of maintaining Neighbour Relation Table (NRT).
Implemented in ns3::MemberLteAnrSapProvider< C >.
The documentation for this class was generated from the following files:
src/lte/model/lte-anr-sap.h
src/lte/model/lte-anr-sap.cc