ns-3: ns3::lorawan::NetworkServer Class Reference
ns3::lorawan::NetworkServer Class Reference
The NetworkServer is an application standing on top of a node equipped with links that connect it with the gateways.
#include "network-server.h"
Public Member Functions
NetworkServer ()
virtual ~NetworkServer ()
void AddComponent (Ptr< NetworkControllerComponent > component)
A NetworkControllerComponent to this NetworkServer instance.
void AddGateway (Ptr< Node > gateway, Ptr< NetDevice > netDevice)
Add this gateway to the list of gateways connected to this NS.
void AddNode (Ptr< Node > node)
Inform the NetworkServer that this node is connected to the network.
void AddNodes (NodeContainer nodes)
Inform the NetworkServer that these nodes are connected to the network.
Ptr< NetworkStatus > GetNetworkStatus (void)
bool Receive (Ptr< NetDevice > device, Ptr< const Packet > packet, uint16_t protocol, const Address &address)
Receive a packet from a gateway.
void StartApplication (void)
Start the NS application.
void StopApplication (void)
Stop the NS application.
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Attributes
Ptr< NetworkController > m_controller
TracedCallback< Ptr< const Packet > > m_receivedPacket
Ptr< NetworkScheduler > m_scheduler
Ptr< NetworkStatus > m_status
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Additional Inherited Members
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Protected Member Functions inherited from ns3::Application
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The NetworkServer is an application standing on top of a node equipped with links that connect it with the gateways.
This version of the NetworkServer attempts to closely mimic an actual Network Server, by providing as much functionality as possible.
Definition at line 49 of file network-server.h.
Constructor & Destructor Documentation
NetworkServer()
ns3::lorawan::NetworkServer::NetworkServer ()
Definition at line 56 of file network-server.cc.
References NS_LOG_FUNCTION_NOARGS.
~NetworkServer()
ns3::lorawan::NetworkServer::~NetworkServer () virtual
Definition at line 64 of file network-server.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
AddComponent()
void ns3::lorawan::NetworkServer::AddComponent (Ptr< NetworkControllerComponent > component)
A NetworkControllerComponent to this NetworkServer instance.
Definition at line 177 of file network-server.cc.
References m_controller, and NS_LOG_FUNCTION.
AddGateway()
void ns3::lorawan::NetworkServer::AddGateway (Ptr< Node > gateway, Ptr< NetDevice > netDevice)
Add this gateway to the list of gateways connected to this NS.
Each GW is identified by its Address in the NS-GWs network.
Definition at line 82 of file network-server.cc.
References ns3::Node::GetDevice(), ns3::Node::GetNDevices(), ns3::Object::GetObject(), m_status, NS_ASSERT, and NS_LOG_FUNCTION.
AddNode()
void ns3::lorawan::NetworkServer::AddNode (Ptr< Node > node)
Inform the NetworkServer that this node is connected to the network.
This method will create a DeviceStatus object for the new node (if it doesn't already exist).
Definition at line 128 of file network-server.cc.
References ns3::Node::GetDevice(), ns3::Node::GetNDevices(), m_status, and NS_LOG_FUNCTION.
Referenced by AddNodes().
AddNodes()
void ns3::lorawan::NetworkServer::AddNodes (NodeContainer nodes)
Inform the NetworkServer that these nodes are connected to the network.
This method will create a DeviceStatus object for each new node, and add it to the list.
Definition at line 115 of file network-server.cc.
References AddNode(), first::nodes, and NS_LOG_FUNCTION_NOARGS.
GetNetworkStatus()
Ptr< NetworkStatus > ns3::lorawan::NetworkServer::GetNetworkStatus (void)
Definition at line 185 of file network-server.cc.
References m_status.
GetTypeId()
TypeId ns3::lorawan::NetworkServer::GetTypeId (void) static
Definition at line 43 of file network-server.cc.
References m_receivedPacket, ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
Receive()
bool ns3::lorawan::NetworkServer::Receive (Ptr< NetDevice > device, Ptr< const Packet > packet, uint16_t protocol, const Address & address)
Receive a packet from a gateway.
Parameters
packet the received packet
Definition at line 153 of file network-server.cc.
References first::address, m_controller, m_receivedPacket, m_scheduler, m_status, and NS_LOG_FUNCTION.
Referenced by ns3::lorawan::NetworkServerHelper::InstallPriv().
StartApplication()
void ns3::lorawan::NetworkServer::StartApplication (void) virtual
Start the NS application.
Reimplemented from ns3::Application.
Definition at line 70 of file network-server.cc.
References NS_LOG_FUNCTION_NOARGS.
StopApplication()
void ns3::lorawan::NetworkServer::StopApplication (void) virtual
Stop the NS application.
Reimplemented from ns3::Application.
Definition at line 76 of file network-server.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Data Documentation
m_controller
Ptr<NetworkController> ns3::lorawan::NetworkServer::m_controller protected
Definition at line 104 of file network-server.h.
Referenced by AddComponent(), and Receive().
m_receivedPacket
TracedCallback<Ptr<const Packet> > ns3::lorawan::NetworkServer::m_receivedPacket protected
Definition at line 107 of file network-server.h.
Referenced by GetTypeId(), and Receive().
m_scheduler
Ptr<NetworkScheduler> ns3::lorawan::NetworkServer::m_scheduler protected
Definition at line 105 of file network-server.h.
Referenced by Receive().
m_status
Ptr<NetworkStatus> ns3::lorawan::NetworkServer::m_status protected
Definition at line 103 of file network-server.h.
Referenced by AddGateway(), AddNode(), GetNetworkStatus(), and Receive().
The documentation for this class was generated from the following files:
src/lorawan/model/network-server.h
src/lorawan/model/network-server.cc