ns-3: ns3::CsmaHelper Class Reference
ns3::CsmaHelper Class Reference
CSMA Network Device
build a set of CsmaNetDevice objects
#include "csma-helper.h"
Public Member Functions
CsmaHelper ()
Construct a CsmaHelper.
virtual ~CsmaHelper ()
int64_t AssignStreams (NetDeviceContainer c, int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
NetDeviceContainer Install (const NodeContainer &c) const
This method creates an ns3::CsmaChannel with the attributes configured by CsmaHelper::SetChannelAttribute.
NetDeviceContainer Install (const NodeContainer &c, Ptr< CsmaChannel > channel) const
For each Ptr<node> in the provided container, this method creates an ns3::CsmaNetDevice (with the attributes configured by CsmaHelper::SetDeviceAttribute); adds the device to the node; and attaches the provided channel to the device.
NetDeviceContainer Install (const NodeContainer &c, std::string channelName) const
For each Ptr<node> in the provided container, this method creates an ns3::CsmaNetDevice (with the attributes configured by CsmaHelper::SetDeviceAttribute); adds the device to the node; and attaches the provided channel to the device.
NetDeviceContainer Install (Ptr< Node > node) const
This method creates an ns3::CsmaChannel with the attributes configured by CsmaHelper::SetChannelAttribute, an ns3::CsmaNetDevice with the attributes configured by CsmaHelper::SetDeviceAttribute and then adds the device to the node and attaches the channel to the device.
NetDeviceContainer Install (Ptr< Node > node, Ptr< CsmaChannel > channel) const
This method creates an ns3::CsmaNetDevice with the attributes configured by CsmaHelper::SetDeviceAttribute and then adds the device to the node and attaches the provided channel to the device.
NetDeviceContainer Install (Ptr< Node > node, std::string channelName) const
This method creates an ns3::CsmaNetDevice with the attributes configured by CsmaHelper::SetDeviceAttribute and then adds the device to the node and attaches the provided channel to the device.
NetDeviceContainer Install (std::string name) const
This method creates an ns3::CsmaChannel with the attributes configured by CsmaHelper::SetChannelAttribute, an ns3::CsmaNetDevice with the attributes configured by CsmaHelper::SetDeviceAttribute and then adds the device to the node and attaches the channel to the device.
NetDeviceContainer Install (std::string nodeName, Ptr< CsmaChannel > channel) const
This method creates an ns3::CsmaNetDevice with the attributes configured by CsmaHelper::SetDeviceAttribute and then adds the device to the node and attaches the provided channel to the device.
NetDeviceContainer Install (std::string nodeName, std::string channelName) const
This method creates an ns3::CsmaNetDevice with the attributes configured by CsmaHelper::SetDeviceAttribute and then adds the device to the node and attaches the provided channel to the device.
void SetChannelAttribute (std::string n1, const AttributeValue &v1)
void SetDeviceAttribute (std::string n1, const AttributeValue &v1)
void SetQueue (std::string type, std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue())
Public Member Functions inherited from ns3::PcapHelperForDevice
PcapHelperForDevice ()
Construct a PcapHelperForDevice.
virtual ~PcapHelperForDevice ()
Destroy a PcapHelperForDevice.
void EnablePcap (std::string prefix, NetDeviceContainer d, bool promiscuous=false)
Enable pcap output on each device in the container which is of the appropriate type.
void EnablePcap (std::string prefix, NodeContainer n, bool promiscuous=false)
Enable pcap output on each device (which is of the appropriate type) in the nodes provided in the container.
void EnablePcap (std::string prefix, Ptr< NetDevice > nd, bool promiscuous=false, bool explicitFilename=false)
Enable pcap output the indicated net device.
void EnablePcap (std::string prefix, std::string ndName, bool promiscuous=false, bool explicitFilename=false)
Enable pcap output the indicated net device using a device previously named using the ns-3 object name service.
void EnablePcap (std::string prefix, uint32_t nodeid, uint32_t deviceid, bool promiscuous=false)
Enable pcap output on the device specified by a global node-id (of a previously created node) and associated device-id.
void EnablePcapAll (std::string prefix, bool promiscuous=false)
Enable pcap output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
Public Member Functions inherited from ns3::AsciiTraceHelperForDevice
AsciiTraceHelperForDevice ()
Construct an AsciiTraceHelperForDevice.
virtual ~AsciiTraceHelperForDevice ()
Destroy an AsciiTraceHelperForDevice.
void EnableAscii (Ptr< OutputStreamWrapper > stream, NetDeviceContainer d)
Enable ascii trace output on each device in the container which is of the appropriate type.
void EnableAscii (Ptr< OutputStreamWrapper > stream, NodeContainer n)
Enable ascii trace output on each device (which is of the appropriate type) in the nodes provided in the container.
void EnableAscii (Ptr< OutputStreamWrapper > stream, Ptr< NetDevice > nd)
Enable ascii trace output on the indicated net device.
void EnableAscii (Ptr< OutputStreamWrapper > stream, std::string ndName)
Enable ascii trace output the indicated net device using a device previously named using the ns-3 object name service.
void EnableAscii (Ptr< OutputStreamWrapper > stream, uint32_t nodeid, uint32_t deviceid)
Enable ascii trace output on the device specified by a global node-id (of a previously created node) and associated device-id.
void EnableAscii (std::string prefix, NetDeviceContainer d)
Enable ascii trace output on each device in the container which is of the appropriate type.
void EnableAscii (std::string prefix, NodeContainer n)
Enable ascii trace output on each device (which is of the appropriate type) in the nodes provided in the container.
void EnableAscii (std::string prefix, Ptr< NetDevice > nd, bool explicitFilename=false)
Enable ascii trace output on the indicated net device.
void EnableAscii (std::string prefix, std::string ndName, bool explicitFilename=false)
Enable ascii trace output the indicated net device using a device previously named using the ns-3 object name service.
void EnableAscii (std::string prefix, uint32_t nodeid, uint32_t deviceid, bool explicitFilename)
Enable ascii trace output on the device specified by a global node-id (of a previously created node) and associated device-id.
void EnableAsciiAll (Ptr< OutputStreamWrapper > stream)
Enable ascii trace output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
void EnableAsciiAll (std::string prefix)
Enable ascii trace output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
Private Member Functions
virtual void EnableAsciiInternal (Ptr< OutputStreamWrapper > stream, std::string prefix, Ptr< NetDevice > nd, bool explicitFilename)
Enable ascii trace output on the indicated net device.
virtual void EnablePcapInternal (std::string prefix, Ptr< NetDevice > nd, bool promiscuous, bool explicitFilename)
Enable pcap output on the indicated net device.
Ptr< NetDevice > InstallPriv (Ptr< Node > node, Ptr< CsmaChannel > channel) const
This method creates an ns3::CsmaNetDevice with the attributes configured by CsmaHelper::SetDeviceAttribute and then adds the device to the node and attaches the provided channel to the device.
Private Attributes
ObjectFactory m_channelFactory
factory for the channel
ObjectFactory m_deviceFactory
factory for the NetDevices
ObjectFactory m_queueFactory
factory for the queues
Detailed Description
build a set of CsmaNetDevice objects
Normally we eschew multiple inheritance, however, the classes PcapUserHelperForDevice and AsciiTraceUserHelperForDevice are treated as "mixins". A mixin is a self-contained class that encapsulates a general attribute or a set of functionality that may be of interest to many other classes.
Definition at line 46 of file csma-helper.h.
Constructor & Destructor Documentation
CsmaHelper()
ns3::CsmaHelper::CsmaHelper ()
Construct a CsmaHelper.
Definition at line 42 of file csma-helper.cc.
References m_channelFactory, m_deviceFactory, m_queueFactory, and ns3::ObjectFactory::SetTypeId().
~CsmaHelper()
virtual ns3::CsmaHelper::~CsmaHelper () inline virtual
Definition at line 53 of file csma-helper.h.
Member Function Documentation
AssignStreams()
int64_t ns3::CsmaHelper::AssignStreams (NetDeviceContainer c, int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned. The Install() method should have previously been called by the user.
Parameters
c NetDeviceContainer of the set of net devices for which the CsmaNetDevice should be modified to use a fixed stream
stream first stream index to use
Returns
the number of stream indices assigned by this helper
Definition at line 288 of file csma-helper.cc.
References ns3::NetDeviceContainer::Begin(), second::csma, and ns3::NetDeviceContainer::End().
EnableAsciiInternal()
void ns3::CsmaHelper::EnableAsciiInternal (Ptr< OutputStreamWrapper > stream, std::string prefix, Ptr< NetDevice > nd, bool explicitFilename) private virtual
Enable ascii trace output on the indicated net device.
NetDevice-specific implementation mechanism for hooking the trace and writing to the trace file.
Parameters
stream The output stream object to use when logging ascii traces.
prefix Filename prefix to use for ascii trace files.
nd Net device for which you want to enable tracing.
explicitFilename Treat the prefix as an explicit filename if true
Implements ns3::AsciiTraceHelperForDevice.
Definition at line 117 of file csma-helper.cc.
References ns3::Config::Connect(), ns3::AsciiTraceHelper::CreateFileStream(), ns3::AsciiTraceHelper::DefaultDequeueSinkWithContext(), ns3::AsciiTraceHelper::DefaultDropSinkWithContext(), ns3::AsciiTraceHelper::DefaultEnqueueSinkWithContext(), ns3::AsciiTraceHelper::DefaultReceiveSinkWithContext(), ns3::Packet::EnablePrinting(), ns3::AsciiTraceHelper::GetFilenameFromDevice(), ns3::CsmaNetDevice::GetQueue(), ns3::AsciiTraceHelper::HookDefaultDequeueSinkWithoutContext(), ns3::AsciiTraceHelper::HookDefaultDropSinkWithoutContext(), ns3::AsciiTraceHelper::HookDefaultEnqueueSinkWithoutContext(), ns3::AsciiTraceHelper::HookDefaultReceiveSinkWithoutContext(), ns3::MakeBoundCallback(), and NS_LOG_INFO.
EnablePcapInternal()
void ns3::CsmaHelper::EnablePcapInternal (std::string prefix, Ptr< NetDevice > nd, bool promiscuous, bool explicitFilename) private virtual
Enable pcap output on the indicated net device.
NetDevice-specific implementation mechanism for hooking the trace and writing to the trace file.
Parameters
prefix Filename prefix to use for pcap files.
nd Net device for which you want to enable tracing.
promiscuous If true capture all possible packets available at the device.
explicitFilename Treat the prefix as an explicit filename if true
Implements ns3::PcapHelperForDevice.
Definition at line 78 of file csma-helper.cc.
References ns3::PcapHelper::CreateFile(), ns3::PcapHelper::DLT_EN10MB, anonymous_namespace{print-introspected-doxygen.cc}::file, ns3::PcapHelper::GetFilenameFromDevice(), ns3::PcapHelper::HookDefaultSink(), and NS_LOG_INFO.
Install() [1/9]
NetDeviceContainer ns3::CsmaHelper::Install (const NodeContainer & c) const
This method creates an ns3::CsmaChannel with the attributes configured by CsmaHelper::SetChannelAttribute.
For each Ptr<node> in the provided container: it creates an ns3::CsmaNetDevice (with the attributes configured by CsmaHelper::SetDeviceAttribute); adds the device to the node; and attaches the channel to the device.
Parameters
c The NodeContainer holding the nodes to be changed.
Returns
A container holding the added net devices.
Definition at line 260 of file csma-helper.cc.
References third::channel, ns3::ObjectFactory::Create(), ns3::Object::GetObject(), Install(), and m_channelFactory.
Install() [2/9]
NetDeviceContainer ns3::CsmaHelper::Install (const NodeContainer & c, Ptr< CsmaChannel > channel) const
For each Ptr<node> in the provided container, this method creates an ns3::CsmaNetDevice (with the attributes configured by CsmaHelper::SetDeviceAttribute); adds the device to the node; and attaches the provided channel to the device.
Parameters
c The NodeContainer holding the nodes to be changed.
channel The channel to attach to the devices.
Returns
A container holding the added net devices.
Definition at line 268 of file csma-helper.cc.
References ns3::NetDeviceContainer::Add(), ns3::NodeContainer::Begin(), third::channel, ns3::NodeContainer::End(), and InstallPriv().
Install() [3/9]
NetDeviceContainer ns3::CsmaHelper::Install (const NodeContainer & c, std::string channelName) const
For each Ptr<node> in the provided container, this method creates an ns3::CsmaNetDevice (with the attributes configured by CsmaHelper::SetDeviceAttribute); adds the device to the node; and attaches the provided channel to the device.
Parameters
c The NodeContainer holding the nodes to be changed.
channelName The name of the channel to attach to the devices.
Returns
A container holding the added net devices.
Definition at line 281 of file csma-helper.cc.
References third::channel, and Install().
Install() [4/9]
NetDeviceContainer ns3::CsmaHelper::Install (Ptr< Node > node) const
This method creates an ns3::CsmaChannel with the attributes configured by CsmaHelper::SetChannelAttribute, an ns3::CsmaNetDevice with the attributes configured by CsmaHelper::SetDeviceAttribute and then adds the device to the node and attaches the channel to the device.
Parameters
node The node to install the device in
Returns
A container holding the added net device.
Definition at line 218 of file csma-helper.cc.
References third::channel, ns3::ObjectFactory::Create(), ns3::Object::GetObject(), and m_channelFactory.
Referenced by ns3::CsmaStarHelper::CsmaStarHelper(), EpcS1uDlTestCase::DoRun(), EpcS1uUlTestCase::DoRun(), and Install().
Install() [5/9]
NetDeviceContainer ns3::CsmaHelper::Install (Ptr< Node > node, Ptr< CsmaChannel > channel) const
This method creates an ns3::CsmaNetDevice with the attributes configured by CsmaHelper::SetDeviceAttribute and then adds the device to the node and attaches the provided channel to the device.
Parameters
node The node to install the device in
channel The channel to attach to the device.
Returns
A container holding the added net device.
Definition at line 232 of file csma-helper.cc.
References third::channel, and InstallPriv().
Install() [6/9]
NetDeviceContainer ns3::CsmaHelper::Install (Ptr< Node > node, std::string channelName) const
This method creates an ns3::CsmaNetDevice with the attributes configured by CsmaHelper::SetDeviceAttribute and then adds the device to the node and attaches the provided channel to the device.
Parameters
node The node to install the device in
channelName The name of the channel to attach to the device.
Returns
A container holding the added net device.
Definition at line 238 of file csma-helper.cc.
References third::channel, and InstallPriv().
Install() [7/9]
NetDeviceContainer ns3::CsmaHelper::Install (std::string name) const
This method creates an ns3::CsmaChannel with the attributes configured by CsmaHelper::SetChannelAttribute, an ns3::CsmaNetDevice with the attributes configured by CsmaHelper::SetDeviceAttribute and then adds the device to the node and attaches the channel to the device.
Parameters
name The name of the node to install the device in
Returns
A container holding the added net device.
Definition at line 225 of file csma-helper.cc.
References Install().
Install() [8/9]
NetDeviceContainer ns3::CsmaHelper::Install (std::string nodeName, Ptr< CsmaChannel > channel) const
This method creates an ns3::CsmaNetDevice with the attributes configured by CsmaHelper::SetDeviceAttribute and then adds the device to the node and attaches the provided channel to the device.
Parameters
nodeName The name of the node to install the device in
channel The channel to attach to the device.
Returns
A container holding the added net device.
Definition at line 245 of file csma-helper.cc.
References third::channel, and InstallPriv().
Install() [9/9]
NetDeviceContainer ns3::CsmaHelper::Install (std::string nodeName, std::string channelName) const
This method creates an ns3::CsmaNetDevice with the attributes configured by CsmaHelper::SetDeviceAttribute and then adds the device to the node and attaches the provided channel to the device.
Parameters
nodeName The name of the node to install the device in
channelName The name of the channel to attach to the device.
Returns
A container holding the added net device.
Definition at line 252 of file csma-helper.cc.
References third::channel, and InstallPriv().
InstallPriv()
Ptr< NetDevice > ns3::CsmaHelper::InstallPriv (Ptr< Node > node, Ptr< CsmaChannel > channel) const private
This method creates an ns3::CsmaNetDevice with the attributes configured by CsmaHelper::SetDeviceAttribute and then adds the device to the node and attaches the provided channel to the device.
Parameters
node The node to install the device in
channel The channel to attach to the device.
Returns
A container holding the added net device.
Definition at line 305 of file csma-helper.cc.
References ns3::Node::AddDevice(), ns3::Mac48Address::Allocate(), third::channel, ns3::ObjectFactory::Create(), m_deviceFactory, and m_queueFactory.
Referenced by Install().
SetChannelAttribute()
void ns3::CsmaHelper::SetChannelAttribute (std::string n1, const AttributeValue & v1)
Parameters
n1 the name of the attribute to set
v1 the value of the attribute to set
Set these attributes on each ns3::CsmaChannel created by CsmaHelper::Install
Definition at line 72 of file csma-helper.cc.
References m_channelFactory, and ns3::ObjectFactory::Set().
SetDeviceAttribute()
void ns3::CsmaHelper::SetDeviceAttribute (std::string n1, const AttributeValue & v1)
Parameters
n1 the name of the attribute to set
v1 the value of the attribute to set
Set these attributes on each ns3::CsmaNetDevice created by CsmaHelper::Install
Definition at line 66 of file csma-helper.cc.
References m_deviceFactory, and ns3::ObjectFactory::Set().
SetQueue()
void ns3::CsmaHelper::SetQueue (std::string type, std::string n1 = "", const AttributeValue & v1 = EmptyAttributeValue (), std::string n2 = "", const AttributeValue & v2 = EmptyAttributeValue (), std::string n3 = "", const AttributeValue & v3 = EmptyAttributeValue (), std::string n4 = "", const AttributeValue & v4 = EmptyAttributeValue ())
Parameters
type the type of queue
n1 the name of the attribute to set on the queue
v1 the value of the attribute to set on the queue
n2 the name of the attribute to set on the queue
v2 the value of the attribute to set on the queue
n3 the name of the attribute to set on the queue
v3 the value of the attribute to set on the queue
n4 the name of the attribute to set on the queue
v4 the value of the attribute to set on the queue
Set the type of queue to create and associated to each CsmaNetDevice created through CsmaHelper::Install.
Definition at line 50 of file csma-helper.cc.
References ns3::QueueBase::AppendItemTypeIfNotPresent(), m_queueFactory, ns3::ObjectFactory::Set(), and ns3::ObjectFactory::SetTypeId().
Member Data Documentation
m_channelFactory
ObjectFactory ns3::CsmaHelper::m_channelFactory private
factory for the channel
Definition at line 252 of file csma-helper.h.
Referenced by CsmaHelper(), Install(), and SetChannelAttribute().
m_deviceFactory
ObjectFactory ns3::CsmaHelper::m_deviceFactory private
factory for the NetDevices
Definition at line 251 of file csma-helper.h.
Referenced by CsmaHelper(), InstallPriv(), and SetDeviceAttribute().
m_queueFactory
ObjectFactory ns3::CsmaHelper::m_queueFactory private
factory for the queues
Definition at line 250 of file csma-helper.h.
Referenced by CsmaHelper(), InstallPriv(), and SetQueue().
The documentation for this class was generated from the following files:
src/csma/helper/csma-helper.h
src/csma/helper/csma-helper.cc