ns-3: ns3::BurstProfileManager Class Reference
ns3::BurstProfileManager Class Reference
WiMAX Models
#include "burst-profile-manager.h"
Public Member Functions
BurstProfileManager (Ptr< WimaxNetDevice > device)
Constructor.
~BurstProfileManager (void)
void DoDispose (void)
Destructor implementation.
uint8_t GetBurstProfile (WimaxPhy::ModulationType modulationType, WimaxNetDevice::Direction direction) const
returns the burst profile
uint8_t GetBurstProfileForSS (const SSRecord *ssRecord, const RngReq *rngreq, WimaxPhy::ModulationType &modulationType)
Get burst profile for SS.
uint8_t GetBurstProfileToRequest (void)
Get burst profile to request.
WimaxPhy::ModulationType GetModulationType (uint8_t iuc, WimaxNetDevice::Direction direction) const
returns the modulation type of a given iuc
WimaxPhy::ModulationType GetModulationTypeForSS (const SSRecord *ssRecord, const RngReq *rngreq)
Get module ation type for SS.
uint16_t GetNrBurstProfilesToDefine (void)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
BurstProfileManager (const BurstProfileManager &)
Type conversion operator.
BurstProfileManager & operator= (const BurstProfileManager &)
Assignment operator.
Private Attributes
Ptr< WimaxNetDevice > m_device
the device
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 37 of file burst-profile-manager.h.
Constructor & Destructor Documentation
BurstProfileManager() [1/2]
ns3::BurstProfileManager::BurstProfileManager (Ptr< WimaxNetDevice > device)
Constructor.
Parameters
device WIMAX device
Definition at line 44 of file burst-profile-manager.cc.
~BurstProfileManager()
ns3::BurstProfileManager::~BurstProfileManager (void)
Definition at line 49 of file burst-profile-manager.cc.
References m_device.
BurstProfileManager() [2/2]
ns3::BurstProfileManager::BurstProfileManager (const BurstProfileManager &) private
Type conversion operator.
Member Function Documentation
DoDispose()
void ns3::BurstProfileManager::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 55 of file burst-profile-manager.cc.
References m_device.
GetBurstProfile()
uint8_t ns3::BurstProfileManager::GetBurstProfile (WimaxPhy::ModulationType modulationType, WimaxNetDevice::Direction direction) const
returns the burst profile
Parameters
modulationType
direction should be uplink or downlink
Returns
the modulation type of the selected iuc
Definition at line 107 of file burst-profile-manager.cc.
References ns3::WimaxNetDevice::DIRECTION_DOWNLINK, m_device, and NS_FATAL_ERROR.
Referenced by GetBurstProfileForSS(), and GetBurstProfileToRequest().
GetBurstProfileForSS()
uint8_t ns3::BurstProfileManager::GetBurstProfileForSS (const SSRecord * ssRecord, const RngReq * rngreq, WimaxPhy::ModulationType & modulationType)
Get burst profile for SS.
Parameters
modulationType
ssRecord
rngreq
Returns
the burst profile for SS
Definition at line 145 of file burst-profile-manager.cc.
References ns3::WimaxNetDevice::DIRECTION_DOWNLINK, GetBurstProfile(), and GetModulationTypeForSS().
GetBurstProfileToRequest()
uint8_t ns3::BurstProfileManager::GetBurstProfileToRequest (void)
Get burst profile to request.
Returns
the burst profile for SS
Definition at line 165 of file burst-profile-manager.cc.
References ns3::WimaxNetDevice::DIRECTION_DOWNLINK, GetBurstProfile(), ns3::SubscriberStationNetDevice::GetModulationType(), and m_device.
GetModulationType()
WimaxPhy::ModulationType ns3::BurstProfileManager::GetModulationType (uint8_t iuc, WimaxNetDevice::Direction direction) const
returns the modulation type of a given iuc
Parameters
direction should be uplink or downlink
iuc the iuc
Returns
the modulation type of the selected iuc
Definition at line 70 of file burst-profile-manager.cc.
References ns3::WimaxNetDevice::DIRECTION_DOWNLINK, m_device, and NS_FATAL_ERROR.
Referenced by GetModulationTypeForSS().
GetModulationTypeForSS()
WimaxPhy::ModulationType ns3::BurstProfileManager::GetModulationTypeForSS (const SSRecord * ssRecord, const RngReq * rngreq)
Get module ation type for SS.
Parameters
ssRecord
rngreq
Returns
the burst profile for SS
Definition at line 157 of file burst-profile-manager.cc.
References ns3::WimaxNetDevice::DIRECTION_DOWNLINK, GetModulationType(), and ns3::RngReq::GetReqDlBurstProfile().
Referenced by GetBurstProfileForSS().
GetNrBurstProfilesToDefine()
uint16_t ns3::BurstProfileManager::GetNrBurstProfilesToDefine (void)
Returns
the number of available burst profile
Definition at line 61 of file burst-profile-manager.cc.
GetTypeId()
TypeId ns3::BurstProfileManager::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 36 of file burst-profile-manager.cc.
References ns3::TypeId::SetParent().
operator=()
BurstProfileManager& ns3::BurstProfileManager::operator= (const BurstProfileManager &) private
Assignment operator.
Returns
burst profile manager
Member Data Documentation
m_device
Ptr<WimaxNetDevice> ns3::BurstProfileManager::m_device private
the device
Definition at line 107 of file burst-profile-manager.h.
Referenced by ~BurstProfileManager(), DoDispose(), GetBurstProfile(), GetBurstProfileToRequest(), and GetModulationType().
The documentation for this class was generated from the following files:
src/wimax/model/burst-profile-manager.h
src/wimax/model/burst-profile-manager.cc