ns-3: TcpScalableIncrementTest Class Reference
TcpScalableIncrementTest Class Reference
Internet » internet module tests | Test suites
Testing the congestion avoidance increment on TcpScalable.
Public Member Functions
TcpScalableIncrementTest (uint32_t cWnd, uint32_t segmentSize, uint32_t segmentsAcked, const std::string &name)
Constructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
uint32_t m_cWnd
Congestion window.
uint32_t m_segmentsAcked
Segments ACKed.
uint32_t m_segmentSize
Segment size.
Ptr< TcpSocketState > m_state
TCP socket state.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Testing the congestion avoidance increment on TcpScalable.
Definition at line 44 of file tcp-scalable-test.cc.
Constructor & Destructor Documentation
TcpScalableIncrementTest()
TcpScalableIncrementTest::TcpScalableIncrementTest (uint32_t cWnd, uint32_t segmentSize, uint32_t segmentsAcked, const std::string & name)
Constructor.
Parameters
cWnd Congestion window.
segmentSize Segment size.
segmentsAcked Segments ACKed.
name Test description.
Definition at line 67 of file tcp-scalable-test.cc.
Member Function Documentation
DoRun()
void TcpScalableIncrementTest::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 79 of file tcp-scalable-test.cc.
References ns3::TracedValue< T >::Get(), ns3::UintegerValue::Get(), ns3::ObjectBase::GetAttribute(), ns3::TcpNewReno::IncreaseWindow(), ns3::TcpSocketState::m_cWnd, m_cWnd, m_segmentsAcked, ns3::TcpSocketState::m_segmentSize, m_segmentSize, m_state, min, and NS_TEST_ASSERT_MSG_EQ.
Member Data Documentation
m_cWnd
uint32_t TcpScalableIncrementTest::m_cWnd private
Congestion window.
Definition at line 61 of file tcp-scalable-test.cc.
Referenced by DoRun().
m_segmentsAcked
uint32_t TcpScalableIncrementTest::m_segmentsAcked private
Segments ACKed.
Definition at line 63 of file tcp-scalable-test.cc.
Referenced by DoRun().
m_segmentSize
uint32_t TcpScalableIncrementTest::m_segmentSize private
Segment size.
Definition at line 62 of file tcp-scalable-test.cc.
Referenced by DoRun().
m_state
Ptr<TcpSocketState> TcpScalableIncrementTest::m_state private
TCP socket state.
Definition at line 64 of file tcp-scalable-test.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/internet/test/tcp-scalable-test.cc