ns-3: ns3::GtsFields Class Reference
ns3::GtsFields Class Reference
LR-WPAN models
#include "lr-wpan-fields.h"
Classes
struct gtsDescriptor
Public Member Functions
GtsFields ()
Buffer::Iterator Deserialize (Buffer::Iterator i)
Deserialize the entire GTS fields.
uint8_t GetGtsDirectionField (void) const
Get the GTS Direction Field from the GTS Fields.
uint8_t GetGtsSpecField (void) const
Get the GTS Specification Field from the GTS Fields.
uint32_t GetSerializedSize (void) const
Get the size of the serialized GTS fields.
Buffer::Iterator Serialize (Buffer::Iterator i) const
Serialize the entire GTS fields.
void SetGtsDirectionField (uint8_t gtsDir)
Set the GTS direction field to the GTS Fields gtsDir The GTS Direction Field to set.
void SetGtsSpecField (uint8_t gtsSpec)
Set the GTS Specification Field to the GTS Fields gtsSpec The GTS Specification Field to set.
Private Attributes
uint8_t m_gtsDirMask
GTS Direction field Directions Mask (Bit 0-6) GTS Direction field Reserved (Not Necessary) (Bit 7)
gtsDescriptor m_gtsList [6]
GTS List field (maximum descriptors stored == 7)
uint8_t m_gtsSpecDescCount
GTS specification field Descriptor Count (Bit 0-2) GTS specification field Reserved (Not necessary) (Bit 3-6)
uint8_t m_gtsSpecPermit
GTS specification field GTS Permit (Bit 7)
Detailed Description
Represent the GTS information fields. See IEEE 802.15.4-2011 Section 5.2.2 Figure 39
Definition at line 160 of file lr-wpan-fields.h.
Constructor & Destructor Documentation
GtsFields()
ns3::GtsFields::GtsFields ()
Definition at line 206 of file lr-wpan-fields.cc.
References m_gtsDirMask, m_gtsSpecDescCount, and m_gtsSpecPermit.
Member Function Documentation
Deserialize()
Buffer::Iterator ns3::GtsFields::Deserialize (Buffer::Iterator i)
Deserialize the entire GTS fields.
Parameters
i an iterator which points to where the superframe specification field should be read.
Returns
an iterator.
Definition at line 291 of file lr-wpan-fields.cc.
References ns3::GtsFields::gtsDescriptor::m_gtsDescLength, ns3::GtsFields::gtsDescriptor::m_gtsDescStartSlot, m_gtsList, m_gtsSpecDescCount, ns3::ReadFrom(), ns3::Buffer::Iterator::ReadU8(), SetGtsDirectionField(), and SetGtsSpecField().
Referenced by ns3::BeaconPayloadHeader::Deserialize().
GetGtsDirectionField()
uint8_t ns3::GtsFields::GetGtsDirectionField (void) const
Get the GTS Direction Field from the GTS Fields.
Returns
The GTS Direction Field
Definition at line 228 of file lr-wpan-fields.cc.
References m_gtsDirMask.
Referenced by Serialize().
GetGtsSpecField()
uint8_t ns3::GtsFields::GetGtsSpecField (void) const
Get the GTS Specification Field from the GTS Fields.
Returns
The GTS Spcecification Field
Definition at line 216 of file lr-wpan-fields.cc.
References m_gtsSpecDescCount, and m_gtsSpecPermit.
Referenced by ns3::BeaconPayloadHeader::Print(), and Serialize().
GetSerializedSize()
uint32_t ns3::GtsFields::GetSerializedSize (void) const
Get the size of the serialized GTS fields.
Returns
the size of the serialized fields.
Definition at line 253 of file lr-wpan-fields.cc.
References m_gtsSpecDescCount.
Referenced by ns3::BeaconPayloadHeader::GetSerializedSize().
Serialize()
Buffer::Iterator ns3::GtsFields::Serialize (Buffer::Iterator i) const
Serialize the entire GTS fields.
Parameters
i an iterator which points to where the superframe specification field should be written.
Returns
an iterator.
Definition at line 268 of file lr-wpan-fields.cc.
References GetGtsDirectionField(), GetGtsSpecField(), ns3::GtsFields::gtsDescriptor::m_gtsDescLength, ns3::GtsFields::gtsDescriptor::m_gtsDescStartSlot, m_gtsList, m_gtsSpecDescCount, ns3::WriteTo(), and ns3::Buffer::Iterator::WriteU8().
Referenced by ns3::BeaconPayloadHeader::Serialize().
SetGtsDirectionField()
void ns3::GtsFields::SetGtsDirectionField (uint8_t gtsDir)
Set the GTS direction field to the GTS Fields gtsDir The GTS Direction Field to set.
Definition at line 246 of file lr-wpan-fields.cc.
References m_gtsDirMask.
Referenced by Deserialize().
SetGtsSpecField()
void ns3::GtsFields::SetGtsSpecField (uint8_t gtsSpec)
Set the GTS Specification Field to the GTS Fields gtsSpec The GTS Specification Field to set.
Definition at line 238 of file lr-wpan-fields.cc.
References m_gtsSpecDescCount, and m_gtsSpecPermit.
Referenced by Deserialize().
Member Data Documentation
m_gtsDirMask
uint8_t ns3::GtsFields::m_gtsDirMask private
GTS Direction field Directions Mask (Bit 0-6) GTS Direction field Reserved (Not Necessary) (Bit 7)
Definition at line 217 of file lr-wpan-fields.h.
Referenced by GtsFields(), GetGtsDirectionField(), and SetGtsDirectionField().
m_gtsList
gtsDescriptor ns3::GtsFields::m_gtsList[6] private
GTS List field (maximum descriptors stored == 7)
Definition at line 220 of file lr-wpan-fields.h.
Referenced by Deserialize(), and Serialize().
m_gtsSpecDescCount
uint8_t ns3::GtsFields::m_gtsSpecDescCount private
GTS specification field Descriptor Count (Bit 0-2) GTS specification field Reserved (Not necessary) (Bit 3-6)
Definition at line 213 of file lr-wpan-fields.h.
Referenced by GtsFields(), Deserialize(), GetGtsSpecField(), GetSerializedSize(), Serialize(), and SetGtsSpecField().
m_gtsSpecPermit
uint8_t ns3::GtsFields::m_gtsSpecPermit private
GTS specification field GTS Permit (Bit 7)
Definition at line 215 of file lr-wpan-fields.h.
Referenced by GtsFields(), GetGtsSpecField(), and SetGtsSpecField().
The documentation for this class was generated from the following files:
src/lr-wpan/model/lr-wpan-fields.h
src/lr-wpan/model/lr-wpan-fields.cc