ns-3: ns3::DlMap Class Reference
ns3::DlMap Class Reference
This class implements DL-MAP as described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems" 8.2.1.8.1 Compressed DL-MAP, page 402.
#include "dl-mac-messages.h"
Public Member Functions
DlMap (void)
virtual ~DlMap (void)
void AddDlMapElement (OfdmDlMapIe dlMapElement)
Add DL Map element field.
uint32_t Deserialize (Buffer::Iterator start)
Mac48Address GetBaseStationId (void) const
Get base station ID field.
uint8_t GetDcdCount (void) const
Get DCD count field.
std::list< OfdmDlMapIe > GetDlMapElements (void) const
Get DL Map elements field.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
std::string GetName (void) const
Get name field.
uint32_t GetSerializedSize (void) const
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetBaseStationId (Mac48Address baseStationID)
Set base station ID field.
void SetDcdCount (uint8_t dcdCount)
Set DCD count field.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Mac48Address m_baseStationId
base station ID
uint8_t m_dcdCount
DCD count.
std::list< OfdmDlMapIe > m_dlMapElements
DL Map elements.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class implements DL-MAP as described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems" 8.2.1.8.1 Compressed DL-MAP, page 402.
Definition at line 541 of file dl-mac-messages.h.
Constructor & Destructor Documentation
DlMap()
ns3::DlMap::DlMap (void)
Definition at line 550 of file dl-mac-messages.cc.
~DlMap()
ns3::DlMap::~DlMap (void) virtual
Definition at line 556 of file dl-mac-messages.cc.
Member Function Documentation
AddDlMapElement()
void ns3::DlMap::AddDlMapElement (OfdmDlMapIe dlMapElement)
Add DL Map element field.
Parameters
dlMapElement the DL map element
Definition at line 573 of file dl-mac-messages.cc.
References m_dlMapElements.
Referenced by ns3::BaseStationNetDevice::CreateDlMap(), and Deserialize().
Deserialize()
uint32_t ns3::DlMap::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 658 of file dl-mac-messages.cc.
References AddDlMapElement(), ns3::Buffer::Iterator::GetDistanceFrom(), ns3::OfdmDlMapIe::GetDiuc(), m_baseStationId, m_dcdCount, m_dlMapElements, ns3::OfdmDlMapIe::Read(), ns3::ReadFrom(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetBaseStationId()
Mac48Address ns3::DlMap::GetBaseStationId (void) const
Get base station ID field.
Returns
the MAC address
Definition at line 585 of file dl-mac-messages.cc.
References m_baseStationId.
Referenced by ns3::SubscriberStationNetDevice::ProcessDlMap().
GetDcdCount()
uint8_t ns3::DlMap::GetDcdCount (void) const
Get DCD count field.
Returns
the DCD count
Definition at line 579 of file dl-mac-messages.cc.
References m_dcdCount.
Referenced by ns3::SubscriberStationNetDevice::ProcessDlMap().
GetDlMapElements()
std::list< OfdmDlMapIe > ns3::DlMap::GetDlMapElements (void) const
Get DL Map elements field.
Returns
the DL map elements
Definition at line 591 of file dl-mac-messages.cc.
References m_dlMapElements.
Referenced by ns3::SubscriberStationNetDevice::ProcessDlMap().
GetInstanceTypeId()
TypeId ns3::DlMap::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 614 of file dl-mac-messages.cc.
References GetTypeId().
GetName()
std::string ns3::DlMap::GetName (void) const
Get name field.
Returns
the name string
Definition at line 597 of file dl-mac-messages.cc.
GetSerializedSize()
uint32_t ns3::DlMap::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 628 of file dl-mac-messages.cc.
References ns3::OfdmDlMapIe::GetSize(), and m_dlMapElements.
GetTypeId()
TypeId ns3::DlMap::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 603 of file dl-mac-messages.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::DlMap::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 620 of file dl-mac-messages.cc.
References m_baseStationId, m_dcdCount, and m_dlMapElements.
Serialize()
void ns3::DlMap::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 643 of file dl-mac-messages.cc.
References m_baseStationId, m_dcdCount, m_dlMapElements, visualizer.core::start(), ns3::OfdmDlMapIe::Write(), ns3::WriteTo(), and ns3::Buffer::Iterator::WriteU8().
SetBaseStationId()
void ns3::DlMap::SetBaseStationId (Mac48Address baseStationID)
Set base station ID field.
Parameters
baseStationID the base station ID
Definition at line 567 of file dl-mac-messages.cc.
References m_baseStationId.
Referenced by ns3::BaseStationNetDevice::CreateDlMap().
SetDcdCount()
void ns3::DlMap::SetDcdCount (uint8_t dcdCount)
Set DCD count field.
Parameters
dcdCount the DCD count
Definition at line 561 of file dl-mac-messages.cc.
References m_dcdCount.
Referenced by ns3::BaseStationNetDevice::CreateDlMap().
Member Data Documentation
m_baseStationId
Mac48Address ns3::DlMap::m_baseStationId private
base station ID
Definition at line 596 of file dl-mac-messages.h.
Referenced by Deserialize(), GetBaseStationId(), Print(), Serialize(), and SetBaseStationId().
m_dcdCount
uint8_t ns3::DlMap::m_dcdCount private
DCD count.
Definition at line 595 of file dl-mac-messages.h.
Referenced by Deserialize(), GetDcdCount(), Print(), Serialize(), and SetDcdCount().
m_dlMapElements
std::list<OfdmDlMapIe> ns3::DlMap::m_dlMapElements private
DL Map elements.
Definition at line 597 of file dl-mac-messages.h.
Referenced by AddDlMapElement(), Deserialize(), GetDlMapElements(), GetSerializedSize(), Print(), and Serialize().
The documentation for this class was generated from the following files:
src/wimax/model/dl-mac-messages.h
src/wimax/model/dl-mac-messages.cc