ns-3: ChannelCoordinationTestCase Class Reference
ChannelCoordinationTestCase Class Reference
WAVE module » wave module tests | Test suites
This test case tests the channel coordination. In particular, it checks the following:
Public Member Functions
ChannelCoordinationTestCase (void)
virtual ~ChannelCoordinationTestCase (void)
void NotifyCchStartNow (Time duration)
Notify CCS start now function.
void NotifyGuardStartNow (Time duration, bool inCchInterval)
Notify guard start now function.
void NotifySchStartNow (Time duration)
Notify SCH start now function.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void TestIntervalAfter (bool cchi, bool schi, bool guardi)
Test interval after function.
Private Attributes
Ptr< ChannelCoordinator > m_coordinator
coordinator
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
This test case tests the channel coordination. In particular, it checks the following:
channel interval calculation including CCH Interval, SCH Interval, Guard Interval and Sync Interval
current interval state for current time and future time
channel coordination events notified at the correct time.
Definition at line 49 of file mac-extension-test-suite.cc.
Constructor & Destructor Documentation
ChannelCoordinationTestCase()
ChannelCoordinationTestCase::ChannelCoordinationTestCase (void)
Definition at line 121 of file mac-extension-test-suite.cc.
~ChannelCoordinationTestCase()
ChannelCoordinationTestCase::~ChannelCoordinationTestCase (void) virtual
Definition at line 125 of file mac-extension-test-suite.cc.
Member Function Documentation
DoRun()
void ChannelCoordinationTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 203 of file mac-extension-test-suite.cc.
References ns3::ChannelCoordinator::GetCchInterval(), ns3::ChannelCoordinator::GetGuardInterval(), ns3::ChannelCoordinator::GetSchInterval(), ns3::ChannelCoordinator::GetSyncInterval(), ns3::ChannelCoordinator::IsValidConfig(), m_coordinator, ns3::MilliSeconds(), NS_TEST_EXPECT_MSG_EQ, ns3::ChannelCoordinator::RegisterListener(), ns3::Seconds(), ns3::ChannelCoordinator::SetCchInterval(), ns3::ChannelCoordinator::SetGuardInterval(), ns3::ChannelCoordinator::SetSchInterval(), and TestIntervalAfter().
NotifyCchStartNow()
void ChannelCoordinationTestCase::NotifyCchStartNow (Time duration)
Notify CCS start now function.
Parameters
duration the duration
Definition at line 141 of file mac-extension-test-suite.cc.
References ns3::ChannelCoordinator::GetGuardInterval(), ns3::Time::GetMilliSeconds(), ns3::ChannelCoordinator::GetSyncInterval(), m_coordinator, and ns3::Now().
NotifyGuardStartNow()
void ChannelCoordinationTestCase::NotifyGuardStartNow (Time duration, bool inCchInterval)
Notify guard start now function.
Parameters
duration the duration
inCchInterval the CCH interval
Definition at line 179 of file mac-extension-test-suite.cc.
References ns3::ChannelCoordinator::GetCchInterval(), ns3::Time::GetMilliSeconds(), ns3::ChannelCoordinator::GetSyncInterval(), m_coordinator, and ns3::Now().
NotifySchStartNow()
void ChannelCoordinationTestCase::NotifySchStartNow (Time duration)
Notify SCH start now function.
Parameters
duration the duration
Definition at line 159 of file mac-extension-test-suite.cc.
References ns3::ChannelCoordinator::GetCchInterval(), ns3::ChannelCoordinator::GetGuardInterval(), ns3::Time::GetMilliSeconds(), ns3::ChannelCoordinator::GetSyncInterval(), m_coordinator, and ns3::Now().
TestIntervalAfter()
void ChannelCoordinationTestCase::TestIntervalAfter (bool cchi, bool schi, bool guardi) private
Test interval after function.
Parameters
cchi the CCHI
schi the SCHI
guardi the guard
Definition at line 130 of file mac-extension-test-suite.cc.
References ns3::Time::GetMilliSeconds(), ns3::ChannelCoordinator::IsCchInterval(), ns3::ChannelCoordinator::IsGuardInterval(), ns3::ChannelCoordinator::IsSchInterval(), m_coordinator, ns3::Now(), and NS_TEST_EXPECT_MSG_EQ.
Referenced by DoRun().
Member Data Documentation
m_coordinator
Ptr<ChannelCoordinator> ChannelCoordinationTestCase::m_coordinator private
coordinator
Definition at line 81 of file mac-extension-test-suite.cc.
Referenced by DoRun(), NotifyCchStartNow(), NotifyGuardStartNow(), NotifySchStartNow(), and TestIntervalAfter().
The documentation for this class was generated from the following file:
src/wave/test/mac-extension-test-suite.cc