ns-3: ns3::SimpleTag Class Reference
ns3::SimpleTag Class Reference
SimpleNetDevice tag to store source, destination and protocol of each packet.
Public Member Functions
virtual void Deserialize (TagBuffer i)
Mac48Address GetDst (void) const
Get the destination address.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint16_t GetProto (void) const
Get the protocol number.
virtual uint32_t GetSerializedSize (void) const
Mac48Address GetSrc (void) const
Get the source address.
void Print (std::ostream &os) const
virtual void Serialize (TagBuffer i) const
void SetDst (Mac48Address dst)
Set the destination address.
void SetProto (uint16_t proto)
Set the protocol number.
void SetSrc (Mac48Address src)
Set the source address.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Mac48Address m_dst
destination address
uint16_t m_protocolNumber
protocol number
Mac48Address m_src
source address
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
SimpleNetDevice tag to store source, destination and protocol of each packet.
Definition at line 41 of file simple-net-device.cc.
Member Function Documentation
Deserialize()
void ns3::SimpleTag::Deserialize (TagBuffer i) virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 130 of file simple-net-device.cc.
References ns3::Mac48Address::CopyFrom(), m_dst, m_protocolNumber, m_src, third::mac, ns3::TagBuffer::Read(), and ns3::TagBuffer::ReadU16().
GetDst()
Mac48Address ns3::SimpleTag::GetDst (void) const
Get the destination address.
Returns
the destination address
Definition at line 159 of file simple-net-device.cc.
References m_dst.
Referenced by ns3::SimpleNetDevice::TransmitComplete().
GetInstanceTypeId()
TypeId ns3::SimpleTag::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 109 of file simple-net-device.cc.
References GetTypeId().
GetProto()
uint16_t ns3::SimpleTag::GetProto (void) const
Get the protocol number.
Returns
the protocol number
Definition at line 171 of file simple-net-device.cc.
References m_protocolNumber.
Referenced by ns3::SimpleNetDevice::TransmitComplete().
GetSerializedSize()
uint32_t ns3::SimpleTag::GetSerializedSize (void) const virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 115 of file simple-net-device.cc.
GetSrc()
Mac48Address ns3::SimpleTag::GetSrc (void) const
Get the source address.
Returns
the source address
Definition at line 147 of file simple-net-device.cc.
References m_src.
Referenced by ns3::SimpleNetDevice::TransmitComplete().
GetTypeId()
TypeId ns3::SimpleTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 99 of file simple-net-device.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::SimpleTag::Print (std::ostream & os) const virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 177 of file simple-net-device.cc.
References m_dst, m_protocolNumber, and m_src.
Serialize()
void ns3::SimpleTag::Serialize (TagBuffer i) const virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 120 of file simple-net-device.cc.
References ns3::Mac48Address::CopyTo(), m_dst, m_protocolNumber, m_src, third::mac, ns3::TagBuffer::Write(), and ns3::TagBuffer::WriteU16().
SetDst()
void ns3::SimpleTag::SetDst (Mac48Address dst)
Set the destination address.
Parameters
dst destination address
Definition at line 153 of file simple-net-device.cc.
References m_dst.
Referenced by ns3::SimpleNetDevice::SendFrom().
SetProto()
void ns3::SimpleTag::SetProto (uint16_t proto)
Set the protocol number.
Parameters
proto protocol number
Definition at line 165 of file simple-net-device.cc.
References m_protocolNumber.
Referenced by ns3::SimpleNetDevice::SendFrom().
SetSrc()
void ns3::SimpleTag::SetSrc (Mac48Address src)
Set the source address.
Parameters
src source address
Definition at line 141 of file simple-net-device.cc.
References m_src.
Referenced by ns3::SimpleNetDevice::SendFrom().
Member Data Documentation
m_dst
Mac48Address ns3::SimpleTag::m_dst private
destination address
Definition at line 91 of file simple-net-device.cc.
Referenced by Deserialize(), GetDst(), Print(), Serialize(), and SetDst().
m_protocolNumber
uint16_t ns3::SimpleTag::m_protocolNumber private
protocol number
Definition at line 92 of file simple-net-device.cc.
Referenced by Deserialize(), GetProto(), Print(), Serialize(), and SetProto().
m_src
Mac48Address ns3::SimpleTag::m_src private
source address
Definition at line 90 of file simple-net-device.cc.
Referenced by Deserialize(), GetSrc(), Print(), Serialize(), and SetSrc().
The documentation for this class was generated from the following file:
src/network/utils/simple-net-device.cc