ns-3: LteInterferenceTestCase Class Reference
LteInterferenceTestCase Class Reference
LTE Models » lte module tests | Test suites
Test that SINR calculation and MCS selection works fine in a multi-cell interference scenario.
#include "lte-test-interference.h"
Public Member Functions
LteInterferenceTestCase (std::string name, double d1, double d2, double dlSinr, double ulSinr, double dlSe, double ulSe, uint16_t dlMcs, uint16_t ulMcs)
Constructor.
virtual ~LteInterferenceTestCase ()
void DlScheduling (DlSchedulingCallbackInfo dlInfo)
DL scheduling function.
void UlScheduling (uint32_t frameNo, uint32_t subframeNo, uint16_t rnti, uint8_t mcs, uint16_t sizeTb)
UL scheduling function.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
double m_d1
distance between UE and ENB
double m_d2
distance between UE and other ENB
uint16_t m_dlMcs
the DL MCS
double m_expectedDlSinrDb
expected DL SINR in dB
double m_expectedUlSinrDb
expected UL SINR in dB
uint16_t m_ulMcs
the UL MCS
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test that SINR calculation and MCS selection works fine in a multi-cell interference scenario.
Definition at line 51 of file lte-test-interference.h.
Constructor & Destructor Documentation
LteInterferenceTestCase()
LteInterferenceTestCase::LteInterferenceTestCase (std::string name, double d1, double d2, double dlSinr, double ulSinr, double dlSe, double ulSe, uint16_t dlMcs, uint16_t ulMcs)
Constructor.
TestCase.
Parameters
name the reference name
d1 distance between ENB and UE
d2 distnace between ENB and other UE
dlSinr the DL SINR
ulSinr the UL SINR
dlSe the DL se
ulSe the UL se
dlMcs the DL MCS
ulMcs the UL MCS
Definition at line 97 of file lte-test-interference.cc.
~LteInterferenceTestCase()
LteInterferenceTestCase::~LteInterferenceTestCase () virtual
Definition at line 108 of file lte-test-interference.cc.
Member Function Documentation
DlScheduling()
void LteInterferenceTestCase::DlScheduling (DlSchedulingCallbackInfo dlInfo)
DL scheduling function.
Parameters
dlInfo the DL info
Definition at line 245 of file lte-test-interference.cc.
References ns3::DlSchedulingCallbackInfo::frameNo, m_dlMcs, ns3::DlSchedulingCallbackInfo::mcsTb1, ns3::DlSchedulingCallbackInfo::mcsTb2, ns3::MilliSeconds(), ns3::Now(), NS_LOG_FUNCTION, NS_TEST_ASSERT_MSG_EQ, ns3::DlSchedulingCallbackInfo::rnti, ns3::DlSchedulingCallbackInfo::sizeTb1, ns3::DlSchedulingCallbackInfo::sizeTb2, and ns3::DlSchedulingCallbackInfo::subframeNo.
Referenced by LteTestDlSchedulingCallback().
DoRun()
void LteInterferenceTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 113 of file lte-test-interference.cc.
References ns3::LteHelper::ActivateDataRadioBearer(), ns3::ListPositionAllocator::Add(), ns3::LteHelper::Attach(), ns3::Config::Connect(), ns3::NodeContainer::Create(), ns3::NetDeviceContainer::Get(), ns3::LtePhy::GetDownlinkSpectrumPhy(), ns3::TestCase::GetName(), ns3::Object::GetObject(), ns3::LtePhy::GetUplinkSpectrumPhy(), ns3::LteSpectrumValueCatcher::GetValue(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), LteTestDlSchedulingCallback(), LteTestUlSchedulingCallback(), m_d1, m_d2, m_dlMcs, m_expectedDlSinrDb, m_expectedUlSinrDb, m_ulMcs, ns3::MakeBoundCallback(), ns3::MakeCallback(), third::mobility, NS_LOG_INFO, NS_TEST_ASSERT_MSG_EQ_TOL, ns3::Seconds(), ns3::ObjectBase::SetAttribute(), ns3::Config::SetDefault(), ns3::LteHelper::SetSchedulerAttribute(), and ns3::LteHelper::SetSchedulerType().
UlScheduling()
void LteInterferenceTestCase::UlScheduling (uint32_t frameNo, uint32_t subframeNo, uint16_t rnti, uint8_t mcs, uint16_t sizeTb)
UL scheduling function.
Parameters
frameNo the frame number
subframeNo the subframe number
rnti the RNTI
mcs the MCS
sizeTb
Definition at line 256 of file lte-test-interference.cc.
References m_ulMcs, ns3::MilliSeconds(), ns3::Now(), NS_LOG_FUNCTION, and NS_TEST_ASSERT_MSG_EQ.
Referenced by LteTestUlSchedulingCallback().
Member Data Documentation
m_d1
double LteInterferenceTestCase::m_d1 private
distance between UE and ENB
Definition at line 91 of file lte-test-interference.h.
Referenced by DoRun().
m_d2
double LteInterferenceTestCase::m_d2 private
distance between UE and other ENB
Definition at line 92 of file lte-test-interference.h.
Referenced by DoRun().
m_dlMcs
uint16_t LteInterferenceTestCase::m_dlMcs private
the DL MCS
Definition at line 95 of file lte-test-interference.h.
Referenced by DlScheduling(), and DoRun().
m_expectedDlSinrDb
double LteInterferenceTestCase::m_expectedDlSinrDb private
expected DL SINR in dB
Definition at line 93 of file lte-test-interference.h.
Referenced by DoRun().
m_expectedUlSinrDb
double LteInterferenceTestCase::m_expectedUlSinrDb private
expected UL SINR in dB
Definition at line 94 of file lte-test-interference.h.
Referenced by DoRun().
m_ulMcs
uint16_t LteInterferenceTestCase::m_ulMcs private
the UL MCS
Definition at line 96 of file lte-test-interference.h.
Referenced by DoRun(), and UlScheduling().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-interference.h
src/lte/test/lte-test-interference.cc