ns-3: ns3::lorawan::LoraPhyHelper Class Reference
ns3::lorawan::LoraPhyHelper Class Reference
Helper to install LoraPhy instances on multiple Nodes.
#include "lora-phy-helper.h"
Public Types
enum DeviceType { GW, ED }
Enum for the type of device: End Device (ED) or Gateway (GW)
Public Member Functions
LoraPhyHelper ()
Create a phy helper without any parameter set.
Ptr< LoraPhy > Create (Ptr< Node > node, Ptr< NetDevice > device) const
Crate a LoraPhy and connect it to a device on a node.
TypeId GetDeviceType (void) const
void Set (std::string name, const AttributeValue &v)
Set an attribute of the underlying PHY object.
void SetChannel (Ptr< LoraChannel > channel)
Set the LoraChannel to connect the PHYs to.
void SetDeviceType (enum DeviceType dt)
Set the kind of PHY this helper will create.
void SetGatewayTransmissionPriority (bool txPriority)
Set if giving priority to downlink transmission over reception at the gateways.
void SetMaxReceptionPaths (int maxReceptionPaths)
Set the maximum number of gateway receive paths.
Private Attributes
Ptr< LoraChannel > m_channel
The channel instance the PHYs will be connected to.
int m_maxReceptionPaths
The maximum number of receive paths at the gateway.
ObjectFactory m_phy
The PHY layer factory object.
bool m_txPriority
If giving priority to downlink transmission over reception at the gateways.
Detailed Description
Helper to install LoraPhy instances on multiple Nodes.
Definition at line 38 of file lora-phy-helper.h.
Member Enumeration Documentation
DeviceType
enum ns3::lorawan::LoraPhyHelper::DeviceType
Enum for the type of device: End Device (ED) or Gateway (GW)
Enumerator
GW
ED
Definition at line 44 of file lora-phy-helper.h.
Constructor & Destructor Documentation
LoraPhyHelper()
ns3::lorawan::LoraPhyHelper::LoraPhyHelper ()
Create a phy helper without any parameter set.
The user must set them all to be able to call Install later.
Definition at line 30 of file lora-phy-helper.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Create()
Ptr< LoraPhy > ns3::lorawan::LoraPhyHelper::Create (Ptr< Node > node, Ptr< NetDevice > device) const
Crate a LoraPhy and connect it to a device on a node.
Parameters
node the node on which we wish to create a wifi PHY.
device the device within which this PHY will be created.
Returns
a newly-created PHY object.
Definition at line 73 of file lora-phy-helper.cc.
References ns3::ObjectFactory::Create(), ns3::Node::GetId(), ns3::TypeId::GetName(), ns3::ObjectFactory::GetTypeId(), m_channel, m_maxReceptionPaths, m_phy, NS_LOG_FUNCTION, and third::phy.
Referenced by ns3::lorawan::LoraHelper::Install().
GetDeviceType()
TypeId ns3::lorawan::LoraPhyHelper::GetDeviceType (void) const
Definition at line 60 of file lora-phy-helper.cc.
References ns3::ObjectFactory::GetTypeId(), m_phy, and NS_LOG_FUNCTION.
Referenced by ns3::lorawan::LoraHelper::Install().
Set()
void ns3::lorawan::LoraPhyHelper::Set (std::string name, const AttributeValue & v)
Set an attribute of the underlying PHY object.
Parameters
name the name of the attribute to set.
v the value of the attribute.
Definition at line 67 of file lora-phy-helper.cc.
References m_phy, and ns3::ObjectFactory::Set().
SetChannel()
void ns3::lorawan::LoraPhyHelper::SetChannel (Ptr< LoraChannel > channel)
Set the LoraChannel to connect the PHYs to.
Every PHY created by a call to Install is associated to this channel.
Parameters
channel the channel to associate to this helper.
Definition at line 38 of file lora-phy-helper.cc.
References third::channel, and m_channel.
Referenced by ns3::lorawan::CreateEndDevices(), and ns3::lorawan::CreateGateways().
SetDeviceType()
void ns3::lorawan::LoraPhyHelper::SetDeviceType (enum DeviceType dt)
Set the kind of PHY this helper will create.
Parameters
dt the device type.
Definition at line 44 of file lora-phy-helper.cc.
References ED, GW, m_phy, NS_LOG_FUNCTION, and ns3::ObjectFactory::SetTypeId().
Referenced by ns3::lorawan::CreateEndDevices(), and ns3::lorawan::CreateGateways().
SetGatewayTransmissionPriority()
void ns3::lorawan::LoraPhyHelper::SetGatewayTransmissionPriority (bool txPriority)
Set if giving priority to downlink transmission over reception at the gateways.
Definition at line 142 of file lora-phy-helper.cc.
References m_txPriority.
SetMaxReceptionPaths()
void ns3::lorawan::LoraPhyHelper::SetMaxReceptionPaths (int maxReceptionPaths)
Set the maximum number of gateway receive paths.
Parameters
maxReceptionPaths The maximum number of reception paths at the gateway
Definition at line 135 of file lora-phy-helper.cc.
References m_maxReceptionPaths, and NS_LOG_FUNCTION.
Member Data Documentation
m_channel
Ptr<LoraChannel> ns3::lorawan::LoraPhyHelper::m_channel private
The channel instance the PHYs will be connected to.
Definition at line 116 of file lora-phy-helper.h.
Referenced by Create(), and SetChannel().
m_maxReceptionPaths
int ns3::lorawan::LoraPhyHelper::m_maxReceptionPaths private
The maximum number of receive paths at the gateway.
Definition at line 121 of file lora-phy-helper.h.
Referenced by Create(), and SetMaxReceptionPaths().
m_phy
ObjectFactory ns3::lorawan::LoraPhyHelper::m_phy private
The PHY layer factory object.
Definition at line 111 of file lora-phy-helper.h.
Referenced by Create(), GetDeviceType(), Set(), and SetDeviceType().
m_txPriority
bool ns3::lorawan::LoraPhyHelper::m_txPriority private
If giving priority to downlink transmission over reception at the gateways.
Definition at line 126 of file lora-phy-helper.h.
Referenced by SetGatewayTransmissionPriority().
The documentation for this class was generated from the following files:
src/lorawan/helper/lora-phy-helper.h
src/lorawan/helper/lora-phy-helper.cc