ns-3: ns3::MpduAggregator Class Reference
ns3::MpduAggregator Class Reference
Wifi Models
Aggregator used to construct A-MPDUs.
#include "mpdu-aggregator.h"
Public Types
typedef std::map< AcIndex, Ptr< QosTxop > > EdcaQueues
EDCA queues typedef.
Public Member Functions
MpduAggregator ()
virtual ~MpduAggregator ()
uint32_t GetMaxAmpduSize (Mac48Address recipient, uint8_t tid, WifiModulationClass modulation) const
Determine the maximum size for an A-MPDU of the given TID that can be sent to the given receiver when using the given modulation class.
std::vector< Ptr< WifiMacQueueItem > > GetNextAmpdu (Ptr< const WifiMacQueueItem > mpdu, WifiTxVector txVector, Time ppduDurationLimit=Time::Min()) const
Attempt to aggregate other MPDUs to the given MPDU, while meeting the following constraints:
void SetEdcaQueues (EdcaQueues edcaQueues)
Set the map of EDCA queues.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static void Aggregate (Ptr< const WifiMacQueueItem > mpdu, Ptr< Packet > ampdu, bool isSingle)
Aggregate an MPDU to an A-MPDU.
static uint8_t CalculatePadding (uint32_t ampduSize)
static AmpduSubframeHeader GetAmpduSubframeHeader (uint16_t mpduSize, bool isSingle)
Get the A-MPDU subframe header corresponding to the MPDU size and whether the MPDU is a single MPDU.
static uint32_t GetSizeIfAggregated (uint32_t mpduSize, uint32_t ampduSize)
Compute the size of the A-MPDU resulting from the aggregation of an MPDU of size mpduSize and an A-MPDU of size ampduSize.
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
EdcaQueues m_edca
the map of EDCA queues
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Aggregator used to construct A-MPDUs.
Definition at line 41 of file mpdu-aggregator.h.
Member Typedef Documentation
EdcaQueues
typedef std::map<AcIndex, Ptr<QosTxop> > ns3::MpduAggregator::EdcaQueues
EDCA queues typedef.
Definition at line 47 of file mpdu-aggregator.h.
Constructor & Destructor Documentation
MpduAggregator()
ns3::MpduAggregator::MpduAggregator ()
Definition at line 58 of file mpdu-aggregator.cc.
~MpduAggregator()
ns3::MpduAggregator::~MpduAggregator () virtual
Definition at line 62 of file mpdu-aggregator.cc.
Member Function Documentation
Aggregate()
void ns3::MpduAggregator::Aggregate (Ptr< const WifiMacQueueItem > mpdu, Ptr< Packet > ampdu, bool isSingle) static
Aggregate an MPDU to an A-MPDU.
Parameters
mpdu the MPDU.
ampdu the A-MPDU.
isSingle whether it is a single MPDU.
Definition at line 73 of file mpdu-aggregator.cc.
References ns3::Packet::AddAtEnd(), ns3::Packet::AddHeader(), ns3::AddWifiMacTrailer(), CalculatePadding(), GetAmpduSubframeHeader(), ns3::Packet::GetSize(), NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::WifiPsdu::GetPacket().
CalculatePadding()
uint8_t ns3::MpduAggregator::CalculatePadding (uint32_t ampduSize) static
Parameters
ampduSize the size of the A-MPDU that needs to be padded in bytes
Returns
the size of the padding that must be added to the end of an A-MPDU in bytes
Calculates how much padding must be added to the end of an A-MPDU of the given size (once another MPDU is aggregated). Each A-MPDU subframe is padded so that its length is multiple of 4 octets.
Definition at line 191 of file mpdu-aggregator.cc.
Referenced by Aggregate(), ns3::WifiPsdu::GetAmpduSubframeSize(), and GetSizeIfAggregated().
GetAmpduSubframeHeader()
AmpduSubframeHeader ns3::MpduAggregator::GetAmpduSubframeHeader (uint16_t mpduSize, bool isSingle) static
Get the A-MPDU subframe header corresponding to the MPDU size and whether the MPDU is a single MPDU.
Parameters
mpduSize size of the MPDU in bytes.
isSingle true if S-MPDU.
Definition at line 197 of file mpdu-aggregator.cc.
References ns3::AmpduSubframeHeader::SetEof(), and ns3::AmpduSubframeHeader::SetLength().
Referenced by Aggregate(), and ns3::WifiPsdu::GetAmpduSubframe().
GetMaxAmpduSize()
uint32_t ns3::MpduAggregator::GetMaxAmpduSize (Mac48Address recipient, uint8_t tid, WifiModulationClass modulation) const
Determine the maximum size for an A-MPDU of the given TID that can be sent to the given receiver when using the given modulation class.
Parameters
recipient the receiver station address.
tid the TID.
modulation the modulation class.
Returns
the maximum A-MPDU size in bytes.
Definition at line 113 of file mpdu-aggregator.cc.
References ns3::AC_BE, ns3::AC_BK, ns3::AC_VI, ns3::AC_VO, ns3::UintegerValue::Get(), ns3::Txop::GetLow(), ns3::WifiNetDevice::GetMac(), ns3::WifiNetDevice::GetRemoteStationManager(), ns3::WifiRemoteStationManager::GetStationHeCapabilities(), ns3::WifiRemoteStationManager::GetStationHtCapabilities(), ns3::WifiRemoteStationManager::GetStationVhtCapabilities(), m_edca, min, NS_ABORT_MSG, NS_ABORT_MSG_IF, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::QosUtilsMapTidToAc(), ns3::WIFI_MOD_CLASS_HE, ns3::WIFI_MOD_CLASS_HT, and ns3::WIFI_MOD_CLASS_VHT.
Referenced by GetNextAmpdu().
GetNextAmpdu()
std::vector< Ptr< WifiMacQueueItem > > ns3::MpduAggregator::GetNextAmpdu (Ptr< const WifiMacQueueItem > mpdu, WifiTxVector txVector, Time ppduDurationLimit = Time::Min ()) const
Attempt to aggregate other MPDUs to the given MPDU, while meeting the following constraints:
the size of the resulting A-MPDU does not exceed the maximum A-MPDU size as determined for the modulation class indicated by the given TxVector
the time to transmit the resulting PPDU, according to the given TxVector, does not exceed both the maximum PPDU duration allowed by the corresponding modulation class (if any) and the given PPDU duration limit (if distinct from Time::Min ())
For now, only non-broadcast QoS Data frames can be aggregated (do not pass other types of frames to this method). MPDUs to aggregate are looked for among those with the same TID and receiver as the given MPDU.
The resulting A-MPDU is returned as a vector of the constituent MPDUs (including the given MPDU), which are not actually aggregated (call the Aggregate method afterwards to get the actual A-MPDU). If aggregation was not possible (aggregation is disabled, there is no Block Ack agreement established with the receiver, or another MPDU to aggregate was not found), the returned vector is empty.
Parameters
mpdu the given MPDU.
txVector the TxVector used to transmit the frame
ppduDurationLimit the limit on the PPDU duration
Returns
the resulting A-MPDU, if aggregation is possible.
Definition at line 209 of file mpdu-aggregator.cc.
References ns3::Copy(), ns3::WifiMacQueueItem::GetHeader(), GetMaxAmpduSize(), ns3::WifiTxVector::GetMode(), ns3::WifiMode::GetModulationClass(), ns3::WifiMacHeader::GetSequenceNumber(), ns3::WifiMacQueueItem::GetSize(), GetSizeIfAggregated(), ns3::GetTid(), ns3::Mac48Address::IsBroadcast(), ns3::IsInWindow(), m_edca, ns3::WifiMacHeader::NORMAL_ACK, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::QosUtilsMapTidToAc(), and ns3::WifiMacHeader::SetQosAckPolicy().
GetSizeIfAggregated()
uint32_t ns3::MpduAggregator::GetSizeIfAggregated (uint32_t mpduSize, uint32_t ampduSize) static
Compute the size of the A-MPDU resulting from the aggregation of an MPDU of size mpduSize and an A-MPDU of size ampduSize.
Parameters
mpduSize the MPDU size in bytes.
ampduSize the A-MPDU size in bytes.
Returns
the size of the resulting A-MPDU in bytes.
Definition at line 105 of file mpdu-aggregator.cc.
References CalculatePadding(), and NS_LOG_FUNCTION.
Referenced by ns3::WifiPsdu::WifiPsdu(), and GetNextAmpdu().
GetTypeId()
TypeId ns3::MpduAggregator::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 48 of file mpdu-aggregator.cc.
References ns3::TypeId::SetParent().
SetEdcaQueues()
void ns3::MpduAggregator::SetEdcaQueues (EdcaQueues edcaQueues)
Set the map of EDCA queues.
Parameters
edcaQueues the map of EDCA queues.
Definition at line 67 of file mpdu-aggregator.cc.
References m_edca.
Member Data Documentation
m_edca
EdcaQueues ns3::MpduAggregator::m_edca private
the map of EDCA queues
Definition at line 149 of file mpdu-aggregator.h.
Referenced by GetMaxAmpduSize(), GetNextAmpdu(), and SetEdcaQueues().
The documentation for this class was generated from the following files:
src/wifi/model/mpdu-aggregator.h
src/wifi/model/mpdu-aggregator.cc