ns-3: ns3::EmuFdNetDeviceHelper Class Reference
ns3::EmuFdNetDeviceHelper Class Reference
File Descriptor Network Device
build a set of FdNetDevice objects attached to a physical network interface
#include "emu-fd-net-device-helper.h"
Public Member Functions
EmuFdNetDeviceHelper ()
Construct a EmuFdNetDeviceHelper.
virtual ~EmuFdNetDeviceHelper ()
std::string GetDeviceName (void)
Get the device name of this device.
void SetDeviceName (std::string deviceName)
Set the device name of this device.
Public Member Functions inherited from ns3::FdNetDeviceHelper
FdNetDeviceHelper ()
Construct a FdNetDeviceHelper.
virtual ~FdNetDeviceHelper ()
virtual NetDeviceContainer Install (const NodeContainer &c) const
This method creates a FdNetDevice and associates it to a node.
virtual NetDeviceContainer Install (Ptr< Node > node) const
This method creates a FdNetDevice and associates it to a node.
virtual NetDeviceContainer Install (std::string name) const
This method creates a FdNetDevice and associates it to a node.
void SetAttribute (std::string n1, const AttributeValue &v1)
Public Member Functions inherited from ns3::PcapHelperForDevice
PcapHelperForDevice ()
Construct a PcapHelperForDevice.
virtual ~PcapHelperForDevice ()
Destroy a PcapHelperForDevice.
void EnablePcap (std::string prefix, NetDeviceContainer d, bool promiscuous=false)
Enable pcap output on each device in the container which is of the appropriate type.
void EnablePcap (std::string prefix, NodeContainer n, bool promiscuous=false)
Enable pcap output on each device (which is of the appropriate type) in the nodes provided in the container.
void EnablePcap (std::string prefix, Ptr< NetDevice > nd, bool promiscuous=false, bool explicitFilename=false)
Enable pcap output the indicated net device.
void EnablePcap (std::string prefix, std::string ndName, bool promiscuous=false, bool explicitFilename=false)
Enable pcap output the indicated net device using a device previously named using the ns-3 object name service.
void EnablePcap (std::string prefix, uint32_t nodeid, uint32_t deviceid, bool promiscuous=false)
Enable pcap output on the device specified by a global node-id (of a previously created node) and associated device-id.
void EnablePcapAll (std::string prefix, bool promiscuous=false)
Enable pcap output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
Public Member Functions inherited from ns3::AsciiTraceHelperForDevice
AsciiTraceHelperForDevice ()
Construct an AsciiTraceHelperForDevice.
virtual ~AsciiTraceHelperForDevice ()
Destroy an AsciiTraceHelperForDevice.
void EnableAscii (Ptr< OutputStreamWrapper > stream, NetDeviceContainer d)
Enable ascii trace output on each device in the container which is of the appropriate type.
void EnableAscii (Ptr< OutputStreamWrapper > stream, NodeContainer n)
Enable ascii trace output on each device (which is of the appropriate type) in the nodes provided in the container.
void EnableAscii (Ptr< OutputStreamWrapper > stream, Ptr< NetDevice > nd)
Enable ascii trace output on the indicated net device.
void EnableAscii (Ptr< OutputStreamWrapper > stream, std::string ndName)
Enable ascii trace output the indicated net device using a device previously named using the ns-3 object name service.
void EnableAscii (Ptr< OutputStreamWrapper > stream, uint32_t nodeid, uint32_t deviceid)
Enable ascii trace output on the device specified by a global node-id (of a previously created node) and associated device-id.
void EnableAscii (std::string prefix, NetDeviceContainer d)
Enable ascii trace output on each device in the container which is of the appropriate type.
void EnableAscii (std::string prefix, NodeContainer n)
Enable ascii trace output on each device (which is of the appropriate type) in the nodes provided in the container.
void EnableAscii (std::string prefix, Ptr< NetDevice > nd, bool explicitFilename=false)
Enable ascii trace output on the indicated net device.
void EnableAscii (std::string prefix, std::string ndName, bool explicitFilename=false)
Enable ascii trace output the indicated net device using a device previously named using the ns-3 object name service.
void EnableAscii (std::string prefix, uint32_t nodeid, uint32_t deviceid, bool explicitFilename)
Enable ascii trace output on the device specified by a global node-id (of a previously created node) and associated device-id.
void EnableAsciiAll (Ptr< OutputStreamWrapper > stream)
Enable ascii trace output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
void EnableAsciiAll (std::string prefix)
Enable ascii trace output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
Protected Member Functions
virtual int CreateFileDescriptor (void) const
Call out to a separate process running as suid root in order to get a raw socket.
Ptr< NetDevice > InstallPriv (Ptr< Node > node) const
This method creates an ns3::FdNetDevice attached to a physical network interface.
virtual void SetFileDescriptor (Ptr< FdNetDevice > device) const
Sets a file descriptor on the FileDescriptorNetDevice.
Protected Attributes
std::string m_deviceName
The unix/linux name of the underlying device (e.g., eth0)
Detailed Description
build a set of FdNetDevice objects attached to a physical network interface
Definition at line 40 of file emu-fd-net-device-helper.h.
Constructor & Destructor Documentation
EmuFdNetDeviceHelper()
ns3::EmuFdNetDeviceHelper::EmuFdNetDeviceHelper ()
Construct a EmuFdNetDeviceHelper.
Definition at line 62 of file emu-fd-net-device-helper.cc.
References m_deviceName.
~EmuFdNetDeviceHelper()
virtual ns3::EmuFdNetDeviceHelper::~EmuFdNetDeviceHelper () inline virtual
Definition at line 47 of file emu-fd-net-device-helper.h.
Member Function Documentation
CreateFileDescriptor()
int ns3::EmuFdNetDeviceHelper::CreateFileDescriptor (void) const protected virtual
Call out to a separate process running as suid root in order to get a raw socket.
We do this to avoid having the entire simulation running as root.
Returns
the rawSocket number
Reimplemented in ns3::TapFdNetDeviceHelper, and ns3::PlanetLabFdNetDeviceHelper.
Definition at line 193 of file emu-fd-net-device-helper.cc.
References ns3::BufferToString(), EMU_MAGIC, NS_ASSERT_MSG(), NS_FATAL_ERROR, NS_LOG_DEBUG, NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by SetFileDescriptor().
GetDeviceName()
std::string ns3::EmuFdNetDeviceHelper::GetDeviceName (void)
Get the device name of this device.
Returns
The device name of this device.
Definition at line 74 of file emu-fd-net-device-helper.cc.
References m_deviceName.
InstallPriv()
Ptr< NetDevice > ns3::EmuFdNetDeviceHelper::InstallPriv (Ptr< Node > node) const protected virtual
This method creates an ns3::FdNetDevice attached to a physical network interface.
Parameters
node The node to install the device in
Returns
A container holding the added net device.
Reimplemented from ns3::FdNetDeviceHelper.
Reimplemented in ns3::TapFdNetDeviceHelper, and ns3::PlanetLabFdNetDeviceHelper.
Definition at line 80 of file emu-fd-net-device-helper.cc.
References ns3::FdNetDeviceHelper::InstallPriv(), and SetFileDescriptor().
SetDeviceName()
void ns3::EmuFdNetDeviceHelper::SetDeviceName (std::string deviceName)
Set the device name of this device.
Parameters
deviceName The device name of this device.
Definition at line 68 of file emu-fd-net-device-helper.cc.
References m_deviceName.
Referenced by ns3::EmuEpcHelper::EmuEpcHelper(), and ns3::EmuEpcHelper::AddEnb().
SetFileDescriptor()
void ns3::EmuFdNetDeviceHelper::SetFileDescriptor (Ptr< FdNetDevice > device) const protected virtual
Sets a file descriptor on the FileDescriptorNetDevice.
Reimplemented in ns3::TapFdNetDeviceHelper, and ns3::PlanetLabFdNetDeviceHelper.
Definition at line 89 of file emu-fd-net-device-helper.cc.
References CreateFileDescriptor(), m_deviceName, NS_FATAL_ERROR, and NS_LOG_LOGIC().
Referenced by InstallPriv().
Member Data Documentation
m_deviceName
std::string ns3::EmuFdNetDeviceHelper::m_deviceName protected
The unix/linux name of the underlying device (e.g., eth0)
Definition at line 91 of file emu-fd-net-device-helper.h.
Referenced by EmuFdNetDeviceHelper(), ns3::TapFdNetDeviceHelper::TapFdNetDeviceHelper(), ns3::TapFdNetDeviceHelper::CreateFileDescriptor(), GetDeviceName(), SetDeviceName(), and SetFileDescriptor().
The documentation for this class was generated from the following files:
src/fd-net-device/helper/emu-fd-net-device-helper.h
src/fd-net-device/helper/emu-fd-net-device-helper.cc