ns-3: RoutingExperiment Class Reference
RoutingExperiment Class Reference
Public Member Functions
RoutingExperiment ()
std::string CommandSetup (int argc, char **argv)
void Run (int nSinks, double txp, std::string CSVfileName)
Private Member Functions
void CheckThroughput ()
void ReceivePacket (Ptr< Socket > socket)
Ptr< Socket > SetupPacketReceive (Ipv4Address addr, Ptr< Node > node)
Private Attributes
uint32_t bytesTotal
std::string m_CSVfileName
int m_nSinks
uint32_t m_protocol
std::string m_protocolName
bool m_traceMobility
double m_txp
uint32_t packetsReceived
uint32_t port
Detailed Description
Definition at line 86 of file manet-routing-compare.cc.
Constructor & Destructor Documentation
RoutingExperiment()
RoutingExperiment::RoutingExperiment ()
Definition at line 112 of file manet-routing-compare.cc.
Member Function Documentation
CheckThroughput()
void RoutingExperiment::CheckThroughput () private
Definition at line 155 of file manet-routing-compare.cc.
References bytesTotal, m_CSVfileName, m_nSinks, m_protocolName, m_txp, ns3::Now(), packetsReceived, and ns3::Seconds().
Referenced by Run().
CommandSetup()
std::string RoutingExperiment::CommandSetup (int argc, char ** argv)
Definition at line 188 of file manet-routing-compare.cc.
References second::cmd, COMMANDLINE, m_CSVfileName, m_protocol, and m_traceMobility.
ReceivePacket()
void RoutingExperiment::ReceivePacket (Ptr< Socket > socket) private
Definition at line 142 of file manet-routing-compare.cc.
References bytesTotal, ns3::Packet::GetSize(), NS_LOG_UNCOND, packetsReceived, PrintReceivedPacket(), and ns3::Socket::RecvFrom().
Referenced by SetupPacketReceive().
Run()
void RoutingExperiment::Run (int nSinks, double txp, std::string CSVfileName)
Definition at line 222 of file manet-routing-compare.cc.
References ns3::YansWifiChannelHelper::AddPropagationLoss(), ns3::Ipv4AddressHelper::Assign(), ns3::PositionAllocator::AssignStreams(), ns3::MobilityHelper::AssignStreams(), CheckThroughput(), ns3::NodeContainer::Create(), ns3::ObjectFactory::Create(), ns3::YansWifiChannelHelper::Create(), ns3::AsciiTraceHelper::CreateFileStream(), ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::Object::GetObject(), ns3::UniformRandomVariable::GetValue(), ns3::DsrMainHelper::Install(), ns3::OnOffHelper::Install(), ns3::MobilityHelper::Install(), ns3::InternetStackHelper::Install(), list, m_CSVfileName, m_nSinks, m_protocol, m_protocolName, m_txp, first::nodes, NS_FATAL_ERROR, NS_LOG_INFO, NS_UNUSED, port, ns3::Seconds(), ns3::WifiPhyHelper::Set(), ns3::ObjectFactory::Set(), ns3::OnOffHelper::SetAttribute(), ns3::Ipv4AddressHelper::SetBase(), ns3::YansWifiPhyHelper::SetChannel(), ns3::Config::SetDefault(), ns3::MobilityHelper::SetMobilityModel(), ns3::MobilityHelper::SetPositionAllocator(), ns3::YansWifiChannelHelper::SetPropagationDelay(), ns3::InternetStackHelper::SetRoutingHelper(), ns3::WifiMacHelper::SetType(), ns3::ObjectFactory::SetTypeId(), SetupPacketReceive(), sink, ns3::ApplicationContainer::Start(), ns3::ApplicationContainer::Stop(), third::wifi, and ns3::WIFI_PHY_STANDARD_80211b.
SetupPacketReceive()
Ptr< Socket > RoutingExperiment::SetupPacketReceive (Ipv4Address addr, Ptr< Node > node) private
Definition at line 176 of file manet-routing-compare.cc.
References ns3::MakeCallback(), port, ReceivePacket(), and sink.
Referenced by Run().
Member Data Documentation
bytesTotal
uint32_t RoutingExperiment::bytesTotal private
Definition at line 101 of file manet-routing-compare.cc.
Referenced by CheckThroughput(), and ReceivePacket().
m_CSVfileName
std::string RoutingExperiment::m_CSVfileName private
Definition at line 104 of file manet-routing-compare.cc.
Referenced by CheckThroughput(), CommandSetup(), and Run().
m_nSinks
int RoutingExperiment::m_nSinks private
Definition at line 105 of file manet-routing-compare.cc.
Referenced by CheckThroughput(), and Run().
m_protocol
uint32_t RoutingExperiment::m_protocol private
Definition at line 109 of file manet-routing-compare.cc.
Referenced by CommandSetup(), and Run().
m_protocolName
std::string RoutingExperiment::m_protocolName private
Definition at line 106 of file manet-routing-compare.cc.
Referenced by CheckThroughput(), and Run().
m_traceMobility
bool RoutingExperiment::m_traceMobility private
Definition at line 108 of file manet-routing-compare.cc.
Referenced by CommandSetup().
m_txp
double RoutingExperiment::m_txp private
Definition at line 107 of file manet-routing-compare.cc.
Referenced by CheckThroughput(), and Run().
packetsReceived
uint32_t RoutingExperiment::packetsReceived private
Definition at line 102 of file manet-routing-compare.cc.
Referenced by CheckThroughput(), and ReceivePacket().
port
uint32_t RoutingExperiment::port private
Definition at line 100 of file manet-routing-compare.cc.
Referenced by Run(), and SetupPacketReceive().
The documentation for this class was generated from the following file:
examples/routing/manet-routing-compare.cc