ns-3: ns3::dsr::DsrNodeStab Class Reference
ns3::dsr::DsrNodeStab Class Reference
DsrNodeStab class (DSR node stability)
#include "dsr-rcache.h"
Public Member Functions
DsrNodeStab (Time nodeStab=Simulator::Now())
Constructor.
virtual ~DsrNodeStab ()
Time GetNodeStability () const
Get node stability.
void SetNodeStability (Time nodeStab)
Set node stability.
Private Attributes
Time m_nodeStability
the node stability
Detailed Description
DsrNodeStab class (DSR node stability)
Definition at line 185 of file dsr-rcache.h.
Constructor & Destructor Documentation
DsrNodeStab()
ns3::dsr::DsrNodeStab::DsrNodeStab (Time nodeStab = Simulator::Now ())
Constructor.
Parameters
nodeStab duration of stable node time
Definition at line 81 of file dsr-rcache.cc.
~DsrNodeStab()
ns3::dsr::DsrNodeStab::~DsrNodeStab () virtual
Definition at line 86 of file dsr-rcache.cc.
Member Function Documentation
GetNodeStability()
Time ns3::dsr::DsrNodeStab::GetNodeStability () const inline
Get node stability.
Returns
the remaining time for node stability
Definition at line 208 of file dsr-rcache.h.
References m_nodeStability, and ns3::Simulator::Now().
SetNodeStability()
void ns3::dsr::DsrNodeStab::SetNodeStability (Time nodeStab) inline
Set node stability.
Parameters
nodeStab duration of the node stability
Definition at line 200 of file dsr-rcache.h.
References m_nodeStability, and ns3::Simulator::Now().
Referenced by ns3::dsr::DsrRouteCache::AddRoute_Link().
Member Data Documentation
m_nodeStability
Time ns3::dsr::DsrNodeStab::m_nodeStability private
the node stability
Definition at line 213 of file dsr-rcache.h.
Referenced by GetNodeStability(), and SetNodeStability().
The documentation for this class was generated from the following files:
src/dsr/model/dsr-rcache.h
src/dsr/model/dsr-rcache.cc