ns-3: ns3::BufferSizeLevelBsr Class Reference
ns3::BufferSizeLevelBsr Class Reference
BufferSizeLevelBsr class.
#include "lte-common.h"
Static Public Member Functions
static uint32_t BsrId2BufferSize (uint8_t val)
Convert BSR ID to buffer size.
static uint8_t BufferSize2BsrId (uint32_t val)
Convert Buffer size to BSR ID.
Static Public Attributes
static int m_bufferSizeLevelBsr [64]
buffer size level BSR
Detailed Description
BufferSizeLevelBsr class.
Definition at line 149 of file lte-common.h.
Member Function Documentation
BsrId2BufferSize()
uint32_t ns3::BufferSizeLevelBsr::BsrId2BufferSize (uint8_t val) static
Convert BSR ID to buffer size.
Parameters
val BSR ID
Returns
buffer size
Definition at line 184 of file lte-common.cc.
References ns3::BufferSizeLevelBsrTable, and NS_ABORT_MSG_UNLESS.
Referenced by ns3::CqaFfMacScheduler::DoSchedUlMacCtrlInfoReq(), ns3::FdBetFfMacScheduler::DoSchedUlMacCtrlInfoReq(), ns3::FdMtFfMacScheduler::DoSchedUlMacCtrlInfoReq(), ns3::FdTbfqFfMacScheduler::DoSchedUlMacCtrlInfoReq(), ns3::PfFfMacScheduler::DoSchedUlMacCtrlInfoReq(), ns3::PssFfMacScheduler::DoSchedUlMacCtrlInfoReq(), ns3::RrFfMacScheduler::DoSchedUlMacCtrlInfoReq(), ns3::TdBetFfMacScheduler::DoSchedUlMacCtrlInfoReq(), ns3::TdMtFfMacScheduler::DoSchedUlMacCtrlInfoReq(), ns3::TdTbfqFfMacScheduler::DoSchedUlMacCtrlInfoReq(), ns3::TtaFfMacScheduler::DoSchedUlMacCtrlInfoReq(), ns3::NoOpComponentCarrierManager::DoUlReceiveMacCe(), and ns3::RrComponentCarrierManager::DoUlReceiveMacCe().
BufferSize2BsrId()
uint8_t ns3::BufferSizeLevelBsr::BufferSize2BsrId (uint32_t val) static
Convert Buffer size to BSR ID.
Parameters
val buffer size
Returns
BSR ID
Definition at line 191 of file lte-common.cc.
References ns3::BufferSizeLevelBsrTable, and NS_ASSERT.
Referenced by ns3::NoOpComponentCarrierManager::DoUlReceiveMacCe(), ns3::RrComponentCarrierManager::DoUlReceiveMacCe(), and ns3::LteUeMac::SendReportBufferStatus().
Member Data Documentation
m_bufferSizeLevelBsr
int ns3::BufferSizeLevelBsr::m_bufferSizeLevelBsr[64] static
buffer size level BSR
Definition at line 168 of file lte-common.h.
The documentation for this class was generated from the following files:
src/lte/model/lte-common.h
src/lte/model/lte-common.cc