ns-3: CobaltQueueDiscBasicEnqueueDequeue Class Reference
CobaltQueueDiscBasicEnqueueDequeue Class Reference
Traffic-control » traffic-control module tests | Test suites
Test 1: simple enqueue/dequeue with no drops.
Public Member Functions
CobaltQueueDiscBasicEnqueueDequeue (QueueSizeUnit mode)
Constructor.
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Attributes
QueueSizeUnit m_mode
Queue test size function.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test 1: simple enqueue/dequeue with no drops.
Definition at line 104 of file cobalt-queue-disc-test-suite.cc.
Constructor & Destructor Documentation
CobaltQueueDiscBasicEnqueueDequeue()
CobaltQueueDiscBasicEnqueueDequeue::CobaltQueueDiscBasicEnqueueDequeue (QueueSizeUnit mode)
Constructor.
Parameters
mode the mode
Definition at line 127 of file cobalt-queue-disc-test-suite.cc.
References m_mode.
Member Function Documentation
DoRun()
void CobaltQueueDiscBasicEnqueueDequeue::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 134 of file cobalt-queue-disc-test-suite.cc.
References ns3::BYTES, ns3::QueueDisc::Dequeue(), ns3::QueueDisc::Enqueue(), ns3::QueueDisc::GetCurrentSize(), ns3::QueueDisc::Stats::GetNDroppedPackets(), ns3::QueueItem::GetPacket(), ns3::QueueDisc::GetStats(), ns3::Packet::GetUid(), ns3::QueueSize::GetValue(), ns3::Object::Initialize(), m_mode, NS_TEST_EXPECT_MSG_EQ, ns3::PACKETS, and ns3::ObjectBase::SetAttributeFailSafe().
Member Data Documentation
m_mode
QueueSizeUnit CobaltQueueDiscBasicEnqueueDequeue::m_mode private
Queue test size function.
Parameters
queue the queue disc
size the size
error the error string mode
Definition at line 124 of file cobalt-queue-disc-test-suite.cc.
Referenced by CobaltQueueDiscBasicEnqueueDequeue(), and DoRun().
The documentation for this class was generated from the following file:
src/traffic-control/test/cobalt-queue-disc-test-suite.cc