ns-3: HwmpSimplestRegressionTest Class Reference
HwmpSimplestRegressionTest Class Reference
Mesh Device » mesh module tests » dot11s sub-module tests | Test suites
Peering Management & HWM Protocol regression test Initiate scenario with 2 stations. Procedure of opening peer link is the following:
#include "hwmp-simplest-regression.h"
Public Member Functions
HwmpSimplestRegressionTest ()
virtual ~HwmpSimplestRegressionTest ()
void CheckResults ()
Check results function.
virtual void DoRun ()
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CreateDevices ()
Create devices function.
void CreateNodes ()
Create nodes function.
void HandleReadClient (Ptr< Socket > socket)
Handle a packet reception.
void HandleReadServer (Ptr< Socket > socket)
Handle a packet reception.
void InstallApplications ()
Install application function.
void ResetPosition ()
Reset position.
void SendData (Ptr< Socket > socket)
Send data.
Private Attributes
Ptr< Socket > m_clientSocket
Client-side socket.
Ipv4InterfaceContainer m_interfaces
interfaces
NodeContainer * m_nodes
uint32_t m_sentPktsCounter
sent packets counter
Ptr< Socket > m_serverSocket
Server-side socket.
Time m_time
Simulation time.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Peering Management & HWM Protocol regression test Initiate scenario with 2 stations. Procedure of opening peer link is the following:
* <-----------|----------->   Broadcast frame
*             |----------->|  Unicast frame
*
*                                        !!! PMP routines:
* <-----------|----------->|             Beacon
*             |<-----------|             Peer Link Open frame
*             |----------->|             Peer Link Open frame
*             |----------->|             Peer Link Confirm frame
*             |<-----------|             Peer Link Confirm frame
*             |............|             !!! Data started:
*             |<-----------|-----------> Arp Request
* <-----------|----------->|             Arp Request (fwd)
* <-----------|----------->|             PREQ
*             |<-----------|             PREP
*             |----------->|             ARP reply
*             |<-----------|             Data
*             |----------->|             Data
*             |............|             Some other beacons
*             |<-----------|             Data
*             |----------->|             Data
*             |............|             !!! Route expiration routines:
*             |<-----------|-----------> PREQ (route expired)
*             |----------->|             PREP
*             |<-----------|             Data
*             |----------->|             Data
*             |............|
*
At 10 seconds stations become unreachable, so UDP client tries to close peer link due to TX-fail, and UDP-srver tries to close link due to beacon loss
Definition at line 70 of file hwmp-simplest-regression.h.
Constructor & Destructor Documentation
HwmpSimplestRegressionTest()
HwmpSimplestRegressionTest::HwmpSimplestRegressionTest ()
Definition at line 44 of file hwmp-simplest-regression.cc.
~HwmpSimplestRegressionTest()
HwmpSimplestRegressionTest::~HwmpSimplestRegressionTest () virtual
Definition at line 51 of file hwmp-simplest-regression.cc.
References m_nodes.
Member Function Documentation
CheckResults()
void HwmpSimplestRegressionTest::CheckResults ()
Check results function.
Definition at line 150 of file hwmp-simplest-regression.cc.
References NS_PCAP_TEST_EXPECT_EQ, and PREFIX.
Referenced by DoRun().
CreateDevices()
void HwmpSimplestRegressionTest::CreateDevices () private
Create devices function.
Definition at line 117 of file hwmp-simplest-regression.cc.
References first::address, ns3::MeshHelper::AssignStreams(), ns3::InternetStackHelper::AssignStreams(), ns3::YansWifiChannelHelper::AssignStreams(), ns3::YansWifiChannelHelper::Create(), ns3::TestCase::CreateTempDirFilename(), ns3::PcapHelperForDevice::EnablePcapAll(), ns3::NetDeviceContainer::GetN(), ns3::MeshHelper::Install(), ns3::InternetStackHelper::Install(), m_interfaces, m_nodes, NS_TEST_ASSERT_MSG_EQ, PREFIX, ns3::Seconds(), ns3::YansWifiPhyHelper::SetChannel(), ns3::MeshHelper::SetMacType(), ns3::MeshHelper::SetNumberOfInterfaces(), and ns3::MeshHelper::SetStackInstaller().
Referenced by DoRun().
CreateNodes()
void HwmpSimplestRegressionTest::CreateNodes () private
Create nodes function.
Definition at line 73 of file hwmp-simplest-regression.cc.
References ns3::NodeContainer::Create(), m_nodes, third::mobility, ResetPosition(), and ns3::Seconds().
Referenced by DoRun().
DoRun()
void HwmpSimplestRegressionTest::DoRun () virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 56 of file hwmp-simplest-regression.cc.
References CheckResults(), CreateDevices(), CreateNodes(), InstallApplications(), m_nodes, and m_time.
HandleReadClient()
void HwmpSimplestRegressionTest::HandleReadClient (Ptr< Socket > socket) private
Handle a packet reception.
This function is called by lower layers.
Parameters
socket the socket the packet was received to.
Definition at line 185 of file hwmp-simplest-regression.cc.
References ns3::Socket::RecvFrom().
Referenced by InstallApplications().
HandleReadServer()
void HwmpSimplestRegressionTest::HandleReadServer (Ptr< Socket > socket) private
Handle a packet reception.
This function is called by lower layers.
Parameters
socket the socket the packet was received to.
Definition at line 171 of file hwmp-simplest-regression.cc.
References ns3::Socket::RecvFrom(), ns3::Packet::RemoveAllByteTags(), ns3::Packet::RemoveAllPacketTags(), and ns3::Socket::SendTo().
Referenced by InstallApplications().
InstallApplications()
void HwmpSimplestRegressionTest::InstallApplications () private
Install application function.
Definition at line 101 of file hwmp-simplest-regression.cc.
References ns3::Socket::Bind(), ns3::Socket::Connect(), ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::Node::GetId(), ns3::Socket::GetNode(), HandleReadClient(), HandleReadServer(), m_clientSocket, m_interfaces, m_nodes, m_serverSocket, ns3::MakeCallback(), ns3::Seconds(), SendData(), and ns3::Socket::SetRecvCallback().
Referenced by DoRun().
ResetPosition()
void HwmpSimplestRegressionTest::ResetPosition () private
Reset position.
Definition at line 90 of file hwmp-simplest-regression.cc.
References ns3::NodeContainer::Get(), ns3::Object::GetObject(), m_nodes, and ns3::MobilityModel::SetPosition().
Referenced by CreateNodes().
SendData()
void HwmpSimplestRegressionTest::SendData (Ptr< Socket > socket) private
Send data.
Parameters
socket the sending socket
Definition at line 159 of file hwmp-simplest-regression.cc.
References ns3::Node::GetId(), ns3::Socket::GetNode(), m_sentPktsCounter, m_time, ns3::Now(), ns3::Seconds(), and ns3::Socket::Send().
Referenced by InstallApplications().
Member Data Documentation
m_clientSocket
Ptr<Socket> HwmpSimplestRegressionTest::m_clientSocket private
Client-side socket.
Definition at line 99 of file hwmp-simplest-regression.h.
Referenced by InstallApplications().
m_interfaces
Ipv4InterfaceContainer HwmpSimplestRegressionTest::m_interfaces private
interfaces
Definition at line 85 of file hwmp-simplest-regression.h.
Referenced by CreateDevices(), and InstallApplications().
m_nodes
NodeContainer* HwmpSimplestRegressionTest::m_nodes private
Internal: It is important to have pointers here
Definition at line 82 of file hwmp-simplest-regression.h.
Referenced by ~HwmpSimplestRegressionTest(), CreateDevices(), CreateNodes(), DoRun(), InstallApplications(), and ResetPosition().
m_sentPktsCounter
uint32_t HwmpSimplestRegressionTest::m_sentPktsCounter private
sent packets counter
Definition at line 102 of file hwmp-simplest-regression.h.
Referenced by SendData().
m_serverSocket
Ptr<Socket> HwmpSimplestRegressionTest::m_serverSocket private
Server-side socket.
Definition at line 97 of file hwmp-simplest-regression.h.
Referenced by InstallApplications().
m_time
Time HwmpSimplestRegressionTest::m_time private
Simulation time.
Definition at line 84 of file hwmp-simplest-regression.h.
Referenced by DoRun(), and SendData().
The documentation for this class was generated from the following files:
src/mesh/test/dot11s/hwmp-simplest-regression.h
src/mesh/test/dot11s/hwmp-simplest-regression.cc