ns-3: HwmpProactiveRegressionTest Class Reference
HwmpProactiveRegressionTest Class Reference
Mesh Device » mesh module tests » dot11s sub-module tests | Test suites
There are 5 stations set into a column, the center station is root. Regression test indicates, that traffic goes from the first to the last stations without reactive route discovery procedure.
#include "hwmp-proactive-regression.h"
Public Member Functions
HwmpProactiveRegressionTest ()
virtual ~HwmpProactiveRegressionTest ()
void CheckResults ()
Check results function.
virtual void DoRun ()
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CreateDevices ()
Create devices function.
void CreateNodes ()
Create nodes function.
void HandleReadClient (Ptr< Socket > socket)
Handle a packet reception.
void HandleReadServer (Ptr< Socket > socket)
Handle a packet reception.
void InstallApplications ()
Install application function.
void ResetPosition ()
Reset position function.
void SendData (Ptr< Socket > socket)
Send data.
Private Attributes
Ptr< Socket > m_clientSocket
Client-side socket.
Ipv4InterfaceContainer m_interfaces
interfaces
NodeContainer * m_nodes
uint32_t m_sentPktsCounter
sent packets counter
Ptr< Socket > m_serverSocket
Server-side socket.
Time m_time
Simulation time.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
There are 5 stations set into a column, the center station is root. Regression test indicates, that traffic goes from the first to the last stations without reactive route discovery procedure.
* Src                Root                 Dst
*           |         |<--------|-------->|         |          Proactive PREQ
*           |         |-------->|         |         |          PREP
*           |         |         |<--------|         |          PREP
*           |<--------|-------->|<--------|-------->|          Proactive PREQ
*           |-------->|         |         |<--------|          PREP
*           |         |-------->|         |         |          PREP
*           |         |         |<--------|         |          PREP
*  <--------|-------->|         |         |<--------|--------> Proactive PREQ
*  Note, that at this moment all routes are known, and no reactive
*  path discovery procedure shall be initiated
*  <--------|-------->|         |         |         |          ARP request
*           |.........|.........|.........|.........|
*           |         |         |<--------|-------->|          ARP request
*           |         |         |         |<--------|          ARP reply
*           |.........|.........|.........|.........|
*           |<--------|         |         |         |          ARP reply
*           |-------->|         |         |         |          DATA
*             ^ Further data is forwarded by proactive path
*
Definition at line 59 of file hwmp-proactive-regression.h.
Constructor & Destructor Documentation
HwmpProactiveRegressionTest()
HwmpProactiveRegressionTest::HwmpProactiveRegressionTest ()
Definition at line 45 of file hwmp-proactive-regression.cc.
~HwmpProactiveRegressionTest()
HwmpProactiveRegressionTest::~HwmpProactiveRegressionTest () virtual
Definition at line 52 of file hwmp-proactive-regression.cc.
References m_nodes.
Member Function Documentation
CheckResults()
void HwmpProactiveRegressionTest::CheckResults ()
Check results function.
Definition at line 142 of file hwmp-proactive-regression.cc.
References NS_PCAP_TEST_EXPECT_EQ, and PREFIX.
Referenced by DoRun().
CreateDevices()
void HwmpProactiveRegressionTest::CreateDevices () private
Create devices function.
Definition at line 106 of file hwmp-proactive-regression.cc.
References first::address, ns3::MeshHelper::AssignStreams(), ns3::InternetStackHelper::AssignStreams(), ns3::YansWifiChannelHelper::AssignStreams(), ns3::YansWifiChannelHelper::Create(), ns3::TestCase::CreateTempDirFilename(), ns3::PcapHelperForDevice::EnablePcapAll(), ns3::NetDeviceContainer::GetN(), ns3::MeshHelper::Install(), ns3::InternetStackHelper::Install(), m_interfaces, m_nodes, NS_TEST_ASSERT_MSG_EQ, PREFIX, ns3::Seconds(), ns3::YansWifiPhyHelper::SetChannel(), ns3::WifiPhyHelper::SetErrorRateModel(), ns3::MeshHelper::SetMacType(), ns3::MeshHelper::SetNumberOfInterfaces(), and ns3::MeshHelper::SetStackInstaller().
Referenced by DoRun().
CreateNodes()
void HwmpProactiveRegressionTest::CreateNodes () private
Create nodes function.
Definition at line 74 of file hwmp-proactive-regression.cc.
References ns3::NodeContainer::Create(), m_nodes, and third::mobility.
Referenced by DoRun().
DoRun()
void HwmpProactiveRegressionTest::DoRun () virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 57 of file hwmp-proactive-regression.cc.
References CheckResults(), CreateDevices(), CreateNodes(), InstallApplications(), m_nodes, and m_time.
HandleReadClient()
void HwmpProactiveRegressionTest::HandleReadClient (Ptr< Socket > socket) private
Handle a packet reception.
This function is called by lower layers.
Parameters
socket the socket the packet was received to.
Definition at line 177 of file hwmp-proactive-regression.cc.
References ns3::Socket::RecvFrom().
Referenced by InstallApplications().
HandleReadServer()
void HwmpProactiveRegressionTest::HandleReadServer (Ptr< Socket > socket) private
Handle a packet reception.
This function is called by lower layers.
Parameters
socket the socket the packet was received to.
Definition at line 163 of file hwmp-proactive-regression.cc.
References ns3::Socket::RecvFrom(), ns3::Packet::RemoveAllByteTags(), ns3::Packet::RemoveAllPacketTags(), and ns3::Socket::SendTo().
Referenced by InstallApplications().
InstallApplications()
void HwmpProactiveRegressionTest::InstallApplications () private
Install application function.
Definition at line 90 of file hwmp-proactive-regression.cc.
References ns3::Socket::Bind(), ns3::Socket::Connect(), ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::Node::GetId(), ns3::Socket::GetNode(), HandleReadClient(), HandleReadServer(), m_clientSocket, m_interfaces, m_nodes, m_serverSocket, ns3::MakeCallback(), ns3::Seconds(), SendData(), and ns3::Socket::SetRecvCallback().
Referenced by DoRun().
ResetPosition()
void HwmpProactiveRegressionTest::ResetPosition () private
Reset position function.
SendData()
void HwmpProactiveRegressionTest::SendData (Ptr< Socket > socket) private
Send data.
Parameters
socket the sending socket
Definition at line 151 of file hwmp-proactive-regression.cc.
References ns3::Node::GetId(), ns3::Socket::GetNode(), m_sentPktsCounter, m_time, ns3::Now(), ns3::Seconds(), and ns3::Socket::Send().
Referenced by InstallApplications().
Member Data Documentation
m_clientSocket
Ptr<Socket> HwmpProactiveRegressionTest::m_clientSocket private
Client-side socket.
Definition at line 88 of file hwmp-proactive-regression.h.
Referenced by InstallApplications().
m_interfaces
Ipv4InterfaceContainer HwmpProactiveRegressionTest::m_interfaces private
interfaces
Definition at line 74 of file hwmp-proactive-regression.h.
Referenced by CreateDevices(), and InstallApplications().
m_nodes
NodeContainer* HwmpProactiveRegressionTest::m_nodes private
Internal: It is important to have pointers here
Definition at line 71 of file hwmp-proactive-regression.h.
Referenced by ~HwmpProactiveRegressionTest(), CreateDevices(), CreateNodes(), DoRun(), and InstallApplications().
m_sentPktsCounter
uint32_t HwmpProactiveRegressionTest::m_sentPktsCounter private
sent packets counter
Definition at line 91 of file hwmp-proactive-regression.h.
Referenced by SendData().
m_serverSocket
Ptr<Socket> HwmpProactiveRegressionTest::m_serverSocket private
Server-side socket.
Definition at line 86 of file hwmp-proactive-regression.h.
Referenced by InstallApplications().
m_time
Time HwmpProactiveRegressionTest::m_time private
Simulation time.
Definition at line 73 of file hwmp-proactive-regression.h.
Referenced by DoRun(), and SendData().
The documentation for this class was generated from the following files:
src/mesh/test/dot11s/hwmp-proactive-regression.h
src/mesh/test/dot11s/hwmp-proactive-regression.cc