ns-3: MyApp Class Reference
MyApp Class Reference
Public Member Functions
MyApp ()
MyApp ()
MyApp ()
virtual ~MyApp ()
virtual ~MyApp ()
virtual ~MyApp ()
void Setup (Ptr< Socket > socket, Address address, uint32_t packetSize, uint32_t nPackets, DataRate dataRate)
void Setup (Ptr< Socket > socket, Address address, uint32_t packetSize, uint32_t nPackets, DataRate dataRate)
void Setup (Ptr< Socket > socket, Address address, uint32_t packetSize, uint32_t nPackets, DataRate dataRate)
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void ScheduleTx (void)
void ScheduleTx (void)
void ScheduleTx (void)
void SendPacket (void)
void SendPacket (void)
void SendPacket (void)
virtual void StartApplication (void)
Application specific startup code.
virtual void StartApplication (void)
Application specific startup code.
virtual void StartApplication (void)
Application specific startup code.
virtual void StopApplication (void)
Application specific shutdown code.
virtual void StopApplication (void)
Application specific shutdown code.
virtual void StopApplication (void)
Application specific shutdown code.
Private Attributes
DataRate m_dataRate
uint32_t m_nPackets
uint32_t m_packetSize
uint32_t m_packetsSent
Address m_peer
bool m_running
EventId m_sendEvent
Ptr< Socket > m_socket
Additional Inherited Members
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Protected Member Functions inherited from ns3::Application
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 62 of file fifth.cc.
Constructor & Destructor Documentation
MyApp() [1/3]
MyApp::MyApp ()
Definition at line 88 of file fifth.cc.
~MyApp() [1/3]
MyApp::~MyApp () virtual
Definition at line 100 of file fifth.cc.
References m_socket.
MyApp() [2/3]
MyApp::MyApp ()
~MyApp() [2/3]
virtual MyApp::~MyApp () virtual
MyApp() [3/3]
MyApp::MyApp ()
~MyApp() [3/3]
virtual MyApp::~MyApp () virtual
Member Function Documentation
GetTypeId() [1/2]
TypeId MyApp::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 111 of file seventh.cc.
References ns3::TypeId::SetParent().
GetTypeId() [2/2]
static TypeId MyApp::GetTypeId (void) static
Register this type.
Returns
The TypeId.
ScheduleTx() [1/3]
void MyApp::ScheduleTx (void) private
Definition at line 154 of file fifth.cc.
References ns3::DataRate::GetBitRate(), m_dataRate, m_packetSize, m_running, m_sendEvent, ns3::Seconds(), and SendPacket().
Referenced by SendPacket().
ScheduleTx() [2/3]
void MyApp::ScheduleTx (void) private
ScheduleTx() [3/3]
void MyApp::ScheduleTx (void) private
SendPacket() [1/3]
void MyApp::SendPacket (void) private
Definition at line 142 of file fifth.cc.
References m_nPackets, m_packetSize, m_packetsSent, m_socket, ScheduleTx(), and ns3::Socket::Send().
Referenced by ScheduleTx(), and StartApplication().
SendPacket() [2/3]
void MyApp::SendPacket (void) private
SendPacket() [3/3]
void MyApp::SendPacket (void) private
Setup() [1/3]
void MyApp::Setup (Ptr< Socket > socket, Address address, uint32_t packetSize, uint32_t nPackets, DataRate dataRate)
Definition at line 106 of file fifth.cc.
References first::address, m_dataRate, m_nPackets, m_packetSize, m_peer, m_socket, and packetSize.
Setup() [2/3]
void MyApp::Setup (Ptr< Socket > socket, Address address, uint32_t packetSize, uint32_t nPackets, DataRate dataRate)
Setup() [3/3]
void MyApp::Setup (Ptr< Socket > socket, Address address, uint32_t packetSize, uint32_t nPackets, DataRate dataRate)
StartApplication() [1/3]
void MyApp::StartApplication (void) private virtual
Application specific startup code.
The StartApplication method is called at the start time specified by Start This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 116 of file fifth.cc.
References ns3::Socket::Bind(), ns3::Socket::Connect(), m_packetsSent, m_peer, m_running, m_socket, and SendPacket().
StartApplication() [2/3]
virtual void MyApp::StartApplication (void) private virtual
Application specific startup code.
The StartApplication method is called at the start time specified by Start This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
StartApplication() [3/3]
virtual void MyApp::StartApplication (void) private virtual
Application specific startup code.
The StartApplication method is called at the start time specified by Start This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
StopApplication() [1/3]
void MyApp::StopApplication (void) private virtual
Application specific shutdown code.
The StopApplication method is called at the stop time specified by Stop This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 126 of file fifth.cc.
References ns3::Socket::Close(), ns3::EventId::IsRunning(), m_running, m_sendEvent, and m_socket.
StopApplication() [2/3]
virtual void MyApp::StopApplication (void) private virtual
Application specific shutdown code.
The StopApplication method is called at the stop time specified by Stop This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
StopApplication() [3/3]
virtual void MyApp::StopApplication (void) private virtual
Application specific shutdown code.
The StopApplication method is called at the stop time specified by Stop This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Member Data Documentation
m_dataRate
DataRate MyApp::m_dataRate private
Definition at line 82 of file fifth.cc.
Referenced by ScheduleTx(), and Setup().
m_nPackets
uint32_t MyApp::m_nPackets private
Definition at line 81 of file fifth.cc.
Referenced by SendPacket(), and Setup().
m_packetSize
uint32_t MyApp::m_packetSize private
Definition at line 80 of file fifth.cc.
Referenced by ScheduleTx(), SendPacket(), and Setup().
m_packetsSent
uint32_t MyApp::m_packetsSent private
Definition at line 85 of file fifth.cc.
Referenced by SendPacket(), and StartApplication().
m_peer
Address MyApp::m_peer private
Definition at line 79 of file fifth.cc.
Referenced by Setup(), and StartApplication().
m_running
bool MyApp::m_running private
Definition at line 84 of file fifth.cc.
Referenced by ScheduleTx(), StartApplication(), and StopApplication().
m_sendEvent
EventId MyApp::m_sendEvent private
Definition at line 83 of file fifth.cc.
Referenced by ScheduleTx(), and StopApplication().
m_socket
Ptr< Socket > MyApp::m_socket private
Definition at line 78 of file fifth.cc.
Referenced by ~MyApp(), SendPacket(), Setup(), StartApplication(), and StopApplication().
The documentation for this class was generated from the following files:
examples/tutorial/fifth.cc
examples/tutorial/seventh.cc
examples/tutorial/sixth.cc