ns-3: ns3::SupportedRates Class Reference
ns3::SupportedRates Class Reference
Wifi Models
The Supported Rates Information Element.
#include "supported-rates.h"
Public Member Functions
SupportedRates ()
SupportedRates (const SupportedRates &)
type conversion operator
void AddBssMembershipSelectorRate (uint64_t bs)
Add a special value to the supported rate set, corresponding to a BSS membership selector.
void AddSupportedRate (uint64_t bs)
Add the given rate to the supported rates.
uint8_t DeserializeInformationField (Buffer::Iterator start, uint8_t length)
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
WifiInformationElementId ElementId () const
uint8_t GetInformationFieldSize () const
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
uint8_t GetNRates (void) const
Return the number of supported rates.
uint32_t GetRate (uint8_t i) const
Return the rate at the given index.
bool IsBasicRate (uint64_t bs) const
Check if the given rate is a basic rate.
bool IsBssMembershipSelectorRate (uint64_t bs) const
Check if the given rate is a BSS membership selector value.
bool IsSupportedRate (uint64_t bs) const
Check if the given rate is supported.
SupportedRates & operator= (const SupportedRates &rates)
assignment operator
void SerializeInformationField (Buffer::Iterator start) const
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
void SetBasicRate (uint64_t bs)
Set the given rate to basic rates.
Public Member Functions inherited from ns3::WifiInformationElement
virtual ~WifiInformationElement ()
Buffer::Iterator Deserialize (Buffer::Iterator i)
Deserialize entire IE, which must be present.
Buffer::Iterator DeserializeIfPresent (Buffer::Iterator i)
Deserialize entire IE if it is present.
virtual WifiInformationElementId ElementIdExt () const
uint16_t GetSerializedSize () const
Get the size of the serialized IE including Element ID and length fields.
virtual bool operator== (WifiInformationElement const &a) const
Compare two IEs for equality by ID & Length, and then through memcmp of serialised version.
virtual void Print (std::ostream &os) const
Generate human-readable form of IE.
Buffer::Iterator Serialize (Buffer::Iterator i) const
Serialize entire IE including Element ID and length fields.
Public Member Functions inherited from ns3::SimpleRefCount< WifiInformationElement >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Attributes
ExtendedSupportedRatesIE extended
extended supported rates info element
Static Public Attributes
static const uint8_t MAX_SUPPORTED_RATES = 32
This defines the maximum number of supported rates that a STA is allowed to have.
Private Attributes
uint8_t m_nRates
Number of supported rates.
uint8_t m_rates [MAX_SUPPORTED_RATES]
List of supported bit rates (divided by 500000)
Friends
class ExtendedSupportedRatesIE
We support the Extended Supported Rates Information Element through the ExtendedSupportedRatesIE object which is declared above.
Detailed Description
The Supported Rates Information Element.
This class knows how to serialise and deserialise the Supported Rates Element that holds the first 8 (non-HT) supported rates.
The ExtendedSupportedRatesIE class (of which an instance exists in objects of this class) deals with rates beyond the first 8.
Definition at line 95 of file supported-rates.h.
Constructor & Destructor Documentation
SupportedRates() [1/2]
ns3::SupportedRates::SupportedRates ()
Definition at line 32 of file supported-rates.cc.
References NS_LOG_FUNCTION.
SupportedRates() [2/2]
ns3::SupportedRates::SupportedRates (const SupportedRates & rates)
type conversion operator
Definition at line 39 of file supported-rates.cc.
References extended, m_nRates, m_rates, MAX_SUPPORTED_RATES, NS_LOG_FUNCTION, and ns3::ExtendedSupportedRatesIE::SetSupportedRates().
Member Function Documentation
AddBssMembershipSelectorRate()
void ns3::SupportedRates::AddBssMembershipSelectorRate (uint64_t bs)
Add a special value to the supported rate set, corresponding to a BSS membership selector.
Parameters
bs the special membership selector value (not a valid rate)
Definition at line 97 of file supported-rates.cc.
References BSS_MEMBERSHIP_SELECTOR_HE_PHY, BSS_MEMBERSHIP_SELECTOR_HT_PHY, BSS_MEMBERSHIP_SELECTOR_VHT_PHY, m_nRates, m_rates, NS_ASSERT_MSG(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by ns3::ApWifiMac::GetSupportedRates(), and ns3::StaWifiMac::GetSupportedRates().
AddSupportedRate()
void ns3::SupportedRates::AddSupportedRate (uint64_t bs)
Add the given rate to the supported rates.
Parameters
bs the rate to be added in bps
Definition at line 59 of file supported-rates.cc.
References IsBssMembershipSelectorRate(), IsSupportedRate(), m_nRates, m_rates, MAX_SUPPORTED_RATES, NS_ASSERT, NS_ASSERT_MSG(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by ns3::MeshWifiInterfaceMac::GetSupportedRates(), ns3::ApWifiMac::GetSupportedRates(), ns3::StaWifiMac::GetSupportedRates(), and SetBasicRate().
DeserializeInformationField()
uint8_t ns3::SupportedRates::DeserializeInformationField (Buffer::Iterator start, uint8_t length) virtual
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
length
Returns
the number of bytes read
Implements ns3::WifiInformationElement.
Definition at line 198 of file supported-rates.cc.
References m_nRates, m_rates, NS_ASSERT, and visualizer.core::start().
ElementId()
WifiInformationElementId ns3::SupportedRates::ElementId () const virtual
Returns
Own unique Element ID
Implements ns3::WifiInformationElement.
Definition at line 174 of file supported-rates.cc.
References IE_SUPPORTED_RATES.
GetInformationFieldSize()
uint8_t ns3::SupportedRates::GetInformationFieldSize () const virtual
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
This is the value that will appear in the second octet of the entire IE - the length field)
Returns
the length of serialized information
Implements ns3::WifiInformationElement.
Definition at line 180 of file supported-rates.cc.
References m_nRates.
GetNRates()
uint8_t ns3::SupportedRates::GetNRates (void) const
Return the number of supported rates.
Returns
the number of supported rates
Definition at line 162 of file supported-rates.cc.
References m_nRates.
Referenced by ns3::operator<<().
GetRate()
uint32_t ns3::SupportedRates::GetRate (uint8_t i) const
Return the rate at the given index.
Return the rate (converted back to raw value) at the given index.
Parameters
i the given index
Returns
the rate in bps
Definition at line 168 of file supported-rates.cc.
References m_rates.
Referenced by ns3::operator<<().
IsBasicRate()
bool ns3::SupportedRates::IsBasicRate (uint64_t bs) const
Check if the given rate is a basic rate.
The rate is encoded as it is serialized to the Supported Rates Information Element (i.e. as a multiple of 500 Kbits/sec, with MSB set to 1).
Parameters
bs the rate to be checked in bps
Returns
true if the rate is a basic rate, false otherwise
Definition at line 118 of file supported-rates.cc.
References m_nRates, m_rates, and NS_LOG_FUNCTION.
Referenced by ns3::operator<<(), ns3::MeshWifiInterfaceMac::Receive(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromProbeResp().
IsBssMembershipSelectorRate()
bool ns3::SupportedRates::IsBssMembershipSelectorRate (uint64_t bs) const
Check if the given rate is a BSS membership selector value.
The rate is encoded as it is serialized to the Supporting Rates Information Element (i.e. with the MSB set to 1).
Parameters
bs the rate to be checked in bps
Returns
true if the rate is a BSS membership selector, false otherwise
Definition at line 149 of file supported-rates.cc.
References BSS_MEMBERSHIP_SELECTOR_HE_PHY, BSS_MEMBERSHIP_SELECTOR_HT_PHY, BSS_MEMBERSHIP_SELECTOR_VHT_PHY, and NS_LOG_FUNCTION.
Referenced by AddSupportedRate(), ns3::StaWifiMac::Receive(), SetBasicRate(), and ns3::StaWifiMac::UpdateApInfoFromProbeResp().
IsSupportedRate()
bool ns3::SupportedRates::IsSupportedRate (uint64_t bs) const
Check if the given rate is supported.
The rate is encoded as it is serialized to the Supported Rates Information Element (i.e. as a multiple of 500 Kbits/sec, possibly with MSB set to 1).
Parameters
bs the rate to be checked in bps
Returns
true if the rate is supported, false otherwise
Definition at line 133 of file supported-rates.cc.
References m_nRates, m_rates, and NS_LOG_FUNCTION.
Referenced by AddSupportedRate(), ns3::MeshWifiInterfaceMac::CheckSupportedRates(), ns3::MeshWifiInterfaceMac::Receive(), ns3::ApWifiMac::Receive(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), ns3::StaWifiMac::UpdateApInfoFromBeacon(), and ns3::StaWifiMac::UpdateApInfoFromProbeResp().
operator=()
SupportedRates & ns3::SupportedRates::operator= (const SupportedRates & rates)
assignment operator
Parameters
rates the rates to assign
Returns
the assigned value
Definition at line 49 of file supported-rates.cc.
References extended, m_nRates, m_rates, MAX_SUPPORTED_RATES, and ns3::ExtendedSupportedRatesIE::SetSupportedRates().
SerializeInformationField()
void ns3::SupportedRates::SerializeInformationField (Buffer::Iterator start) const virtual
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
Implements ns3::WifiInformationElement.
Definition at line 189 of file supported-rates.cc.
References m_nRates, m_rates, and visualizer.core::start().
SetBasicRate()
void ns3::SupportedRates::SetBasicRate (uint64_t bs)
Set the given rate to basic rates.
Parameters
bs the rate to be set in bps
Definition at line 74 of file supported-rates.cc.
References AddSupportedRate(), IsBssMembershipSelectorRate(), m_nRates, m_rates, NS_ASSERT_MSG(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by ns3::MeshWifiInterfaceMac::GetSupportedRates(), and ns3::ApWifiMac::GetSupportedRates().
Friends And Related Function Documentation
ExtendedSupportedRatesIE
friend class ExtendedSupportedRatesIE friend
We support the Extended Supported Rates Information Element through the ExtendedSupportedRatesIE object which is declared above.
We allow this class to be a friend so that it can access our private data detailing the rates, and create an instance as extended.
Definition at line 197 of file supported-rates.h.
Member Data Documentation
extended
ExtendedSupportedRatesIE ns3::SupportedRates::extended
extended supported rates info element
Definition at line 198 of file supported-rates.h.
Referenced by SupportedRates(), ns3::dot11s::PeerLinkOpenStart::Deserialize(), ns3::dot11s::PeerLinkConfirmStart::Deserialize(), ns3::MgtAssocRequestHeader::Deserialize(), ns3::MgtReassocRequestHeader::Deserialize(), ns3::MgtAssocResponseHeader::Deserialize(), ns3::MgtProbeRequestHeader::Deserialize(), ns3::MgtProbeResponseHeader::Deserialize(), ns3::dot11s::PeerLinkOpenStart::GetSerializedSize(), ns3::dot11s::PeerLinkConfirmStart::GetSerializedSize(), ns3::MgtAssocRequestHeader::GetSerializedSize(), ns3::MgtReassocRequestHeader::GetSerializedSize(), ns3::MgtAssocResponseHeader::GetSerializedSize(), ns3::MgtProbeRequestHeader::GetSerializedSize(), ns3::MgtProbeResponseHeader::GetSerializedSize(), operator=(), ns3::dot11s::PeerLinkOpenStart::Serialize(), ns3::dot11s::PeerLinkConfirmStart::Serialize(), ns3::MgtAssocRequestHeader::Serialize(), ns3::MgtReassocRequestHeader::Serialize(), ns3::MgtAssocResponseHeader::Serialize(), ns3::MgtProbeRequestHeader::Serialize(), and ns3::MgtProbeResponseHeader::Serialize().
m_nRates
uint8_t ns3::SupportedRates::m_nRates private
Number of supported rates.
Definition at line 202 of file supported-rates.h.
Referenced by SupportedRates(), AddBssMembershipSelectorRate(), AddSupportedRate(), ns3::ExtendedSupportedRatesIE::DeserializeInformationField(), DeserializeInformationField(), ns3::ExtendedSupportedRatesIE::GetInformationFieldSize(), GetInformationFieldSize(), GetNRates(), ns3::ExtendedSupportedRatesIE::GetSerializedSize(), IsBasicRate(), IsSupportedRate(), operator=(), ns3::ExtendedSupportedRatesIE::Serialize(), ns3::ExtendedSupportedRatesIE::SerializeInformationField(), SerializeInformationField(), and SetBasicRate().
m_rates
uint8_t ns3::SupportedRates::m_rates[MAX_SUPPORTED_RATES] private
List of supported bit rates (divided by 500000)
Definition at line 203 of file supported-rates.h.
Referenced by SupportedRates(), AddBssMembershipSelectorRate(), AddSupportedRate(), ns3::ExtendedSupportedRatesIE::DeserializeInformationField(), DeserializeInformationField(), GetRate(), IsBasicRate(), IsSupportedRate(), operator=(), ns3::ExtendedSupportedRatesIE::SerializeInformationField(), SerializeInformationField(), and SetBasicRate().
MAX_SUPPORTED_RATES
const uint8_t ns3::SupportedRates::MAX_SUPPORTED_RATES = 32 static
This defines the maximum number of supported rates that a STA is allowed to have.
Currently this number is set for IEEE 802.11b/g and SISO IEEE 802.11n stations which need 2 rates each from Clauses 15 and 18, and then 8 from Clause 19.
Definition at line 124 of file supported-rates.h.
Referenced by SupportedRates(), AddSupportedRate(), ns3::ExtendedSupportedRatesIE::DeserializeInformationField(), and operator=().
The documentation for this class was generated from the following files:
src/wifi/model/supported-rates.h
src/wifi/model/supported-rates.cc