ns-3: WifiInterferenceTestCase Class Reference
WifiInterferenceTestCase Class Reference
Public Member Functions
WifiInterferenceTestCase ()
virtual ~WifiInterferenceTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void PrintEndSync (std::string context, uint32_t dataRate, double snr, double per)
void ReceivePacket (Ptr< Socket > socket)
double WifiSimpleInterference (std::string phyMode, double Prss, double Irss, double delta, uint32_t PpacketSize, uint32_t IpacketSize, bool verbose, InternetStackHelper internet, WifiPhyStandard wifiStandard)
Static Private Member Functions
static void GenerateTraffic (Ptr< Socket > socket, uint32_t pktSize, uint32_t pktCount, Time pktInterval)
Private Attributes
uint32_t m_DataRate
double m_PER
double m_SNR
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 35 of file wifi-interference-test-suite.cc.
Constructor & Destructor Documentation
WifiInterferenceTestCase()
WifiInterferenceTestCase::WifiInterferenceTestCase ()
Definition at line 54 of file wifi-interference-test-suite.cc.
~WifiInterferenceTestCase()
WifiInterferenceTestCase::~WifiInterferenceTestCase () virtual
Definition at line 59 of file wifi-interference-test-suite.cc.
Member Function Documentation
DoRun()
void WifiInterferenceTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 230 of file wifi-interference-test-suite.cc.
References NS_TEST_ASSERT_MSG_EQ, verbose, ns3::WIFI_PHY_STANDARD_80211b, ns3::WIFI_PHY_STANDARD_80211n_2_4GHZ, and WifiSimpleInterference().
GenerateTraffic()
void WifiInterferenceTestCase::GenerateTraffic (Ptr< Socket > socket, uint32_t pktSize, uint32_t pktCount, Time pktInterval) static private
Definition at line 83 of file wifi-interference-test-suite.cc.
References ns3::Socket::Close(), and ns3::Socket::Send().
Referenced by WifiSimpleInterference().
PrintEndSync()
void WifiInterferenceTestCase::PrintEndSync (std::string context, uint32_t dataRate, double snr, double per) private
Definition at line 97 of file wifi-interference-test-suite.cc.
References m_DataRate, m_PER, m_SNR, and NS_LOG_UNCOND.
Referenced by WifiSimpleInterference().
ReceivePacket()
void WifiInterferenceTestCase::ReceivePacket (Ptr< Socket > socket) private
Definition at line 77 of file wifi-interference-test-suite.cc.
References NS_LOG_UNCOND, and PrintReceivedPacket().
Referenced by WifiSimpleInterference().
WifiSimpleInterference()
double WifiInterferenceTestCase::WifiSimpleInterference (std::string phyMode, double Prss, double Irss, double delta, uint32_t PpacketSize, uint32_t IpacketSize, bool verbose, InternetStackHelper internet, WifiPhyStandard wifiStandard) private
Definition at line 106 of file wifi-interference-test-suite.cc.
References ns3::ListPositionAllocator::Add(), ns3::YansWifiChannelHelper::AddPropagationLoss(), ns3::Ipv4AddressHelper::Assign(), ns3::Socket::Bind(), ns3::Socket::Connect(), ns3::Config::Connect(), ns3::NodeContainer::Create(), ns3::YansWifiChannelHelper::Create(), first::devices, GenerateTraffic(), ns3::NodeContainer::Get(), ns3::Node::GetId(), ns3::Socket::GetNode(), ns3::InternetStackHelper::Install(), m_DataRate, m_PER, m_SNR, ns3::MakeCallback(), third::mobility, NS_LOG_INFO, PrintEndSync(), ReceivePacket(), ns3::Seconds(), ns3::WifiPhyHelper::Set(), ns3::Ipv4AddressHelper::SetBase(), ns3::YansWifiPhyHelper::SetChannel(), ns3::Config::SetDefault(), ns3::WifiPhyHelper::SetPcapDataLinkType(), ns3::YansWifiChannelHelper::SetPropagationDelay(), ns3::Socket::SetRecvCallback(), ns3::WifiMacHelper::SetType(), startTime, third::wifi, ns3::WIFI_PHY_STANDARD_80211ac, ns3::WIFI_PHY_STANDARD_80211n_2_4GHZ, and ns3::WIFI_PHY_STANDARD_80211n_5GHZ.
Referenced by DoRun().
Member Data Documentation
m_DataRate
uint32_t WifiInterferenceTestCase::m_DataRate private
Definition at line 50 of file wifi-interference-test-suite.cc.
Referenced by PrintEndSync(), and WifiSimpleInterference().
m_PER
double WifiInterferenceTestCase::m_PER private
Definition at line 48 of file wifi-interference-test-suite.cc.
Referenced by PrintEndSync(), and WifiSimpleInterference().
m_SNR
double WifiInterferenceTestCase::m_SNR private
Definition at line 49 of file wifi-interference-test-suite.cc.
Referenced by PrintEndSync(), and WifiSimpleInterference().
The documentation for this class was generated from the following file:
src/test/ns3wifi/wifi-interference-test-suite.cc