ns-3: ns3::OfdmDlMapIe Class Reference
ns3::OfdmDlMapIe Class Reference
This class implements the OFDM DL-MAP information element as described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems" 6.3.2.3.43.6 Compact DL-MAP IE page 109.
#include "dl-mac-messages.h"
Public Member Functions
OfdmDlMapIe (void)
~OfdmDlMapIe (void)
Cid GetCid (void) const
Set CID field.
uint8_t GetDiuc (void) const
Get DIUC field.
uint8_t GetPreamblePresent (void) const
Get preamble present field.
uint16_t GetSize (void) const
Get size.
uint16_t GetStartTime (void) const
Get start time field.
Buffer::Iterator Read (Buffer::Iterator start)
Read item.
void SetCid (Cid cid)
Set CID function.
void SetDiuc (uint8_t diuc)
Set DIUC field.
void SetPreamblePresent (uint8_t preamblePresent)
Set preamble present field.
void SetStartTime (uint16_t startTime)
Set start time field.
Buffer::Iterator Write (Buffer::Iterator start) const
Wrtie item.
Private Attributes
Cid m_cid
CID.
uint8_t m_diuc
DIUC.
uint8_t m_preamblePresent
preamble present
uint16_t m_startTime
start time
Detailed Description
This class implements the OFDM DL-MAP information element as described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems" 6.3.2.3.43.6 Compact DL-MAP IE page 109.
Definition at line 446 of file dl-mac-messages.h.
Constructor & Destructor Documentation
OfdmDlMapIe()
ns3::OfdmDlMapIe::OfdmDlMapIe (void)
Definition at line 458 of file dl-mac-messages.cc.
~OfdmDlMapIe()
ns3::OfdmDlMapIe::~OfdmDlMapIe (void)
Definition at line 466 of file dl-mac-messages.cc.
Member Function Documentation
GetCid()
Cid ns3::OfdmDlMapIe::GetCid (void) const
Set CID field.
Returns
the CID
Definition at line 495 of file dl-mac-messages.cc.
References m_cid.
Referenced by ns3::BaseStationNetDevice::SendBursts().
GetDiuc()
uint8_t ns3::OfdmDlMapIe::GetDiuc (void) const
Get DIUC field.
Returns
the DIUC
Definition at line 501 of file dl-mac-messages.cc.
References m_diuc.
Referenced by ns3::DlMap::Deserialize(), and ns3::BaseStationNetDevice::SendBursts().
GetPreamblePresent()
uint8_t ns3::OfdmDlMapIe::GetPreamblePresent (void) const
Get preamble present field.
Returns
the preamble present indicator
Definition at line 507 of file dl-mac-messages.cc.
References m_preamblePresent.
GetSize()
uint16_t ns3::OfdmDlMapIe::GetSize (void) const
Get size.
Returns
the size
Definition at line 519 of file dl-mac-messages.cc.
Referenced by ns3::DlMap::GetSerializedSize().
GetStartTime()
uint16_t ns3::OfdmDlMapIe::GetStartTime (void) const
Get start time field.
Returns
the start time
Definition at line 513 of file dl-mac-messages.cc.
References m_startTime.
Read()
Buffer::Iterator ns3::OfdmDlMapIe::Read (Buffer::Iterator start)
Read item.
Parameters
start the iterator
Returns
the updated iterator
Definition at line 536 of file dl-mac-messages.cc.
References m_cid, m_diuc, m_preamblePresent, m_startTime, ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
Referenced by ns3::DlMap::Deserialize().
SetCid()
void ns3::OfdmDlMapIe::SetCid (Cid cid)
Set CID function.
Parameters
cid the CID
Definition at line 471 of file dl-mac-messages.cc.
References m_cid.
Referenced by ns3::BSSchedulerRtps::AddDownlinkBurst(), ns3::BSSchedulerSimple::AddDownlinkBurst(), and ns3::BaseStationNetDevice::CreateDlMap().
SetDiuc()
void ns3::OfdmDlMapIe::SetDiuc (uint8_t diuc)
Set DIUC field.
Parameters
diuc the DIUC
Definition at line 477 of file dl-mac-messages.cc.
References m_diuc.
Referenced by ns3::BSSchedulerRtps::AddDownlinkBurst(), ns3::BSSchedulerSimple::AddDownlinkBurst(), and ns3::BaseStationNetDevice::CreateDlMap().
SetPreamblePresent()
void ns3::OfdmDlMapIe::SetPreamblePresent (uint8_t preamblePresent)
Set preamble present field.
Parameters
preamblePresent the preamble present
Definition at line 483 of file dl-mac-messages.cc.
References m_preamblePresent.
Referenced by ns3::BaseStationNetDevice::CreateDlMap().
SetStartTime()
void ns3::OfdmDlMapIe::SetStartTime (uint16_t startTime)
Set start time field.
Parameters
startTime the start time value
Definition at line 489 of file dl-mac-messages.cc.
References m_startTime, and startTime.
Referenced by ns3::BaseStationNetDevice::CreateDlMap().
Write()
Buffer::Iterator ns3::OfdmDlMapIe::Write (Buffer::Iterator start) const
Wrtie item.
Parameters
start the iterator
Returns
the updated iterator
Definition at line 525 of file dl-mac-messages.cc.
References ns3::Cid::GetIdentifier(), m_cid, m_diuc, m_preamblePresent, m_startTime, visualizer.core::start(), ns3::Buffer::Iterator::WriteU16(), and ns3::Buffer::Iterator::WriteU8().
Referenced by ns3::DlMap::Serialize().
Member Data Documentation
m_cid
Cid ns3::OfdmDlMapIe::m_cid private
CID.
Definition at line 513 of file dl-mac-messages.h.
Referenced by GetCid(), Read(), SetCid(), and Write().
m_diuc
uint8_t ns3::OfdmDlMapIe::m_diuc private
DIUC.
Definition at line 514 of file dl-mac-messages.h.
Referenced by GetDiuc(), Read(), SetDiuc(), and Write().
m_preamblePresent
uint8_t ns3::OfdmDlMapIe::m_preamblePresent private
preamble present
Definition at line 515 of file dl-mac-messages.h.
Referenced by GetPreamblePresent(), Read(), SetPreamblePresent(), and Write().
m_startTime
uint16_t ns3::OfdmDlMapIe::m_startTime private
start time
Definition at line 516 of file dl-mac-messages.h.
Referenced by GetStartTime(), Read(), SetStartTime(), and Write().
The documentation for this class was generated from the following files:
src/wimax/model/dl-mac-messages.h
src/wimax/model/dl-mac-messages.cc