ns-3: FriisPropagationLossModelTestCase Class Reference
FriisPropagationLossModelTestCase Class Reference
Classes
struct TestVector
Public Member Functions
FriisPropagationLossModelTestCase ()
virtual ~FriisPropagationLossModelTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
TestVectors< TestVector > m_testVectors
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 37 of file propagation-loss-model-test-suite.cc.
Constructor & Destructor Documentation
FriisPropagationLossModelTestCase()
FriisPropagationLossModelTestCase::FriisPropagationLossModelTestCase ()
Definition at line 56 of file propagation-loss-model-test-suite.cc.
~FriisPropagationLossModelTestCase()
FriisPropagationLossModelTestCase::~FriisPropagationLossModelTestCase () virtual
Definition at line 61 of file propagation-loss-model-test-suite.cc.
Member Function Documentation
DoRun()
void FriisPropagationLossModelTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 66 of file propagation-loss-model-test-suite.cc.
References ns3::PropagationLossModel::CalcRxPower(), FriisPropagationLossModelTestCase::TestVector::m_position, FriisPropagationLossModelTestCase::TestVector::m_pr, FriisPropagationLossModelTestCase::TestVector::m_pt, m_testVectors, FriisPropagationLossModelTestCase::TestVector::m_tolerance, NS_TEST_EXPECT_MSG_EQ_TOL, ns3::Config::SetDefault(), and ns3::MobilityModel::SetPosition().
Member Data Documentation
m_testVectors
TestVectors<TestVector> FriisPropagationLossModelTestCase::m_testVectors private
Definition at line 53 of file propagation-loss-model-test-suite.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/propagation/test/propagation-loss-model-test-suite.cc