ns-3: SampleEmitter Class Reference
SampleEmitter Class Reference
Public Member Functions
SampleEmitter ()
virtual ~SampleEmitter ()
double GetTime ()
double GetValue ()
void Reschedule ()
void Start ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void Report ()
Private Attributes
double aux
double m_time
TracedValue< double > m_trace
Ptr< ExponentialRandomVariable > m_var
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 17 of file double-probe-test-suite.cc.
Constructor & Destructor Documentation
SampleEmitter()
SampleEmitter::SampleEmitter () inline
Definition at line 21 of file double-probe-test-suite.cc.
~SampleEmitter()
virtual SampleEmitter::~SampleEmitter () inline virtual
Definition at line 25 of file double-probe-test-suite.cc.
Member Function Documentation
GetTime()
double SampleEmitter::GetTime () inline
Definition at line 38 of file double-probe-test-suite.cc.
GetTypeId()
TypeId SampleEmitter::GetTypeId (void) static
Definition at line 61 of file double-probe-test-suite.cc.
References m_trace, ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
GetValue()
double SampleEmitter::GetValue () inline
Definition at line 42 of file double-probe-test-suite.cc.
Referenced by ProbeTestCase1::TraceSink().
Report()
void SampleEmitter::Report () inline private
Definition at line 47 of file double-probe-test-suite.cc.
Referenced by Reschedule().
Reschedule()
void SampleEmitter::Reschedule () inline
Definition at line 32 of file double-probe-test-suite.cc.
References ns3::Time::GetSeconds(), ns3::Simulator::Now(), Report(), ns3::Simulator::Schedule(), and ns3::Seconds().
Start()
void SampleEmitter::Start () inline
Definition at line 28 of file double-probe-test-suite.cc.
Referenced by ProbeTestCase1::DoRun().
Member Data Documentation
aux
double SampleEmitter::aux private
Definition at line 56 of file double-probe-test-suite.cc.
m_time
double SampleEmitter::m_time private
Definition at line 54 of file double-probe-test-suite.cc.
m_trace
TracedValue<double> SampleEmitter::m_trace private
Definition at line 55 of file double-probe-test-suite.cc.
Referenced by GetTypeId().
m_var
Ptr<ExponentialRandomVariable> SampleEmitter::m_var private
Definition at line 53 of file double-probe-test-suite.cc.
The documentation for this class was generated from the following file:
src/stats/test/double-probe-test-suite.cc