ns-3: TbfQueueDiscTestCase Class Reference
TbfQueueDiscTestCase Class Reference
Traffic-control » traffic-control module tests | Test suites
Tbf Queue Disc Test Case.
Public Member Functions
TbfQueueDiscTestCase ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void DequeueAndCheck (Ptr< TbfQueueDisc > queue, bool flag, std::string printStatement)
DequeueAndCheck function to check if a packet is blocked or not after dequeuing and verify against expected result.
void Enqueue (Ptr< TbfQueueDisc > queue, Address dest, uint32_t size)
Enqueue function.
void RunTbfTest (QueueSizeUnit mode)
Run TBF test function.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Tbf Queue Disc Test Case.
Definition at line 99 of file tbf-queue-disc-test-suite.cc.
Constructor & Destructor Documentation
TbfQueueDiscTestCase()
TbfQueueDiscTestCase::TbfQueueDiscTestCase ()
Definition at line 126 of file tbf-queue-disc-test-suite.cc.
Member Function Documentation
DequeueAndCheck()
void TbfQueueDiscTestCase::DequeueAndCheck (Ptr< TbfQueueDisc > queue, bool flag, std::string printStatement) private
DequeueAndCheck function to check if a packet is blocked or not after dequeuing and verify against expected result.
Parameters
queue the queue disc on which DequeueAndCheck needs to be done
flag the boolean value against which the return value of dequeue () has to be compared with
printStatement the string to be printed in the NS_TEST_EXPECT_MSG_EQ
Definition at line 420 of file tbf-queue-disc-test-suite.cc.
References ns3::QueueDisc::Dequeue(), and NS_TEST_EXPECT_MSG_EQ.
Referenced by RunTbfTest().
DoRun()
void TbfQueueDiscTestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 427 of file tbf-queue-disc-test-suite.cc.
References ns3::BYTES, ns3::PACKETS, and RunTbfTest().
Enqueue()
void TbfQueueDiscTestCase::Enqueue (Ptr< TbfQueueDisc > queue, Address dest, uint32_t size) private
Enqueue function.
Parameters
queue the queue disc into which enqueue needs to be done
dest the destination address
size the size of the packet in bytes to be enqueued
Definition at line 414 of file tbf-queue-disc-test-suite.cc.
References ns3::QueueDisc::Enqueue().
Referenced by RunTbfTest().
RunTbfTest()
void TbfQueueDiscTestCase::RunTbfTest (QueueSizeUnit mode) private
Run TBF test function.
Parameters
mode the mode
Definition at line 132 of file tbf-queue-disc-test-suite.cc.
References ns3::Node::AddDevice(), ns3::Object::AggregateObject(), ns3::BYTES, ns3::NodeContainer::Create(), ns3::QueueDisc::Dequeue(), DequeueAndCheck(), ns3::QueueDisc::Enqueue(), Enqueue(), ns3::NodeContainer::Get(), ns3::SimpleNetDevice::GetAddress(), ns3::QueueDisc::GetCurrentSize(), ns3::TbfQueueDisc::GetFirstBucketTokens(), ns3::QueueItem::GetPacket(), ns3::Packet::GetUid(), ns3::QueueSize::GetValue(), ns3::Object::Initialize(), NS_TEST_EXPECT_MSG_EQ, ns3::Seconds(), ns3::ObjectBase::SetAttributeFailSafe(), ns3::SimpleNetDevice::SetChannel(), ns3::Config::SetDefault(), ns3::SimpleNetDevice::SetNode(), and ns3::TrafficControlLayer::SetRootQueueDiscOnDevice().
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/traffic-control/test/tbf-queue-disc-test-suite.cc