ns-3: AnimationRemainingEnergyTestCase Class Reference
AnimationRemainingEnergyTestCase Class Reference
Network Animation » animation module tests | Test suites
Animation Remaining Energy Test Case.
Public Member Functions
AnimationRemainingEnergyTestCase ()
Constructor.
Public Member Functions inherited from AbstractAnimationInterfaceTestCase
AbstractAnimationInterfaceTestCase (std::string name)
Constructor.
virtual ~AbstractAnimationInterfaceTestCase ()
Destructor.
virtual void DoRun (void)
Run unit tests for this class.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void CheckLogic ()
Check logic function.
virtual void PrepareNetwork ()
Prepare network function.
Private Attributes
Ptr< SimpleDeviceEnergyModel > m_energyModel
energy model
Ptr< BasicEnergySource > m_energySource
energy source
const double m_initialEnergy
initial energy
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Protected Attributes inherited from AbstractAnimationInterfaceTestCase
AnimationInterface * m_anim
animation
NodeContainer m_nodes
the nodes
Detailed Description
Animation Remaining Energy Test Case.
Definition at line 197 of file netanim-test.cc.
Constructor & Destructor Documentation
AnimationRemainingEnergyTestCase()
AnimationRemainingEnergyTestCase::AnimationRemainingEnergyTestCase ()
Constructor.
Definition at line 218 of file netanim-test.cc.
Member Function Documentation
CheckLogic()
void AnimationRemainingEnergyTestCase::CheckLogic () private virtual
Check logic function.
Implements AbstractAnimationInterfaceTestCase.
Definition at line 245 of file netanim-test.cc.
References ns3::NodeContainer::Get(), ns3::AnimationInterface::GetNodeEnergyFraction(), ns3::BasicEnergySource::GetRemainingEnergy(), AbstractAnimationInterfaceTestCase::m_anim, m_energySource, m_initialEnergy, AbstractAnimationInterfaceTestCase::m_nodes, NS_TEST_ASSERT_MSG_EQ, and NS_TEST_ASSERT_MSG_EQ_TOL.
PrepareNetwork()
void AnimationRemainingEnergyTestCase::PrepareNetwork () private virtual
Prepare network function.
Implements AbstractAnimationInterfaceTestCase.
Definition at line 225 of file netanim-test.cc.
References ns3::Object::AggregateObject(), ns3::EnergySource::AppendDeviceEnergyModel(), ns3::NodeContainer::Create(), ns3::NodeContainer::Get(), m_energyModel, m_energySource, m_initialEnergy, AbstractAnimationInterfaceTestCase::m_nodes, ns3::Seconds(), ns3::SimpleDeviceEnergyModel::SetCurrentA(), ns3::SimpleDeviceEnergyModel::SetEnergySource(), and ns3::BasicEnergySource::SetInitialEnergy().
Member Data Documentation
m_energyModel
Ptr<SimpleDeviceEnergyModel> AnimationRemainingEnergyTestCase::m_energyModel private
energy model
Definition at line 214 of file netanim-test.cc.
Referenced by PrepareNetwork().
m_energySource
Ptr<BasicEnergySource> AnimationRemainingEnergyTestCase::m_energySource private
energy source
Definition at line 213 of file netanim-test.cc.
Referenced by CheckLogic(), and PrepareNetwork().
m_initialEnergy
const double AnimationRemainingEnergyTestCase::m_initialEnergy private
initial energy
Definition at line 215 of file netanim-test.cc.
Referenced by CheckLogic(), and PrepareNetwork().
The documentation for this class was generated from the following file:
src/netanim/test/netanim-test.cc