ns-3: LenaPfFfMacSchedulerTestCase2 Class Reference
LenaPfFfMacSchedulerTestCase2 Class Reference
LTE Models » lte module tests | Test suites
Lena PfFf Mac Scheduler Test Case 2.
#include "lte-test-pf-ff-mac-scheduler.h"
Public Member Functions
LenaPfFfMacSchedulerTestCase2 (std::vector< double > dist, std::vector< uint32_t > estThrPfDl, std::vector< uint32_t > estThrPfUl, bool errorModelEnabled)
Constructor.
virtual ~LenaPfFfMacSchedulerTestCase2 ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Static Private Member Functions
static std::string BuildNameString (uint16_t nUser, std::vector< double > dist)
Builds the test name string based on provided parameter values.
Private Attributes
std::vector< double > m_dist
the distance between nodes
bool m_errorModelEnabled
indicates whether the error model is enabled
std::vector< uint32_t > m_estThrPfDl
the estimated DL throughput
std::vector< uint32_t > m_estThrPfUl
the estimated UL throughput
uint16_t m_nUser
number of UE nodes
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Lena PfFf Mac Scheduler Test Case 2.
Definition at line 82 of file lte-test-pf-ff-mac-scheduler.h.
Constructor & Destructor Documentation
LenaPfFfMacSchedulerTestCase2()
LenaPfFfMacSchedulerTestCase2::LenaPfFfMacSchedulerTestCase2 (std::vector< double > dist, std::vector< uint32_t > estThrPfDl, std::vector< uint32_t > estThrPfUl, bool errorModelEnabled)
Constructor.
Parameters
dist the distance between nodes
estThrPfDl the estimated DL throughput PF
estThrPfUl the estimated UL throughput PF
errorModelEnabled if true the error model is enabled
Definition at line 378 of file lte-test-pf-ff-mac-scheduler.cc.
~LenaPfFfMacSchedulerTestCase2()
LenaPfFfMacSchedulerTestCase2::~LenaPfFfMacSchedulerTestCase2 () virtual
Definition at line 388 of file lte-test-pf-ff-mac-scheduler.cc.
Member Function Documentation
BuildNameString()
std::string LenaPfFfMacSchedulerTestCase2::BuildNameString (uint16_t nUser, std::vector< double > dist) static private
Builds the test name string based on provided parameter values.
Parameters
nUser the number of UE nodes
dist the distnace between nodes
Returns
the name string
Definition at line 365 of file lte-test-pf-ff-mac-scheduler.cc.
DoRun()
void LenaPfFfMacSchedulerTestCase2::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Initialize Simulation Scenario: 1 eNB and m_nUser UEs
Check that the assignment is done in a "proportional fair" manner among users with different SINRs: the bandwidth should be distributed according to the ratio of the estimated throughput per TTI of each user.
Check that the assignment in uplink is done in a round robin manner.
Implements ns3::TestCase.
Definition at line 393 of file lte-test-pf-ff-mac-scheduler.cc.
References ns3::LteHelper::ActivateDataRadioBearer(), ns3::LteHelper::Attach(), ns3::NodeContainer::Create(), ns3::TestCase::CreateTempDirFilename(), ns3::LteHelper::EnableRlcTraces(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::RadioBearerStatsCalculator::GetDlRxData(), ns3::Object::GetObject(), ns3::LteEnbNetDevice::GetPhy(), ns3::LteUeNetDevice::GetPhy(), ns3::LteHelper::GetRlcStats(), ns3::RadioBearerStatsCalculator::GetUlRxData(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), m_dist, m_errorModelEnabled, m_estThrPfDl, m_estThrPfUl, m_nUser, third::mobility, NS_LOG_FUNCTION, NS_LOG_INFO, NS_TEST_ASSERT_MSG_EQ_TOL, ns3::Seconds(), ns3::ObjectBase::SetAttribute(), ns3::Config::SetDefault(), ns3::MobilityModel::SetPosition(), ns3::LteHelper::SetSchedulerAttribute(), and ns3::LteHelper::SetSchedulerType().
Member Data Documentation
m_dist
std::vector<double> LenaPfFfMacSchedulerTestCase2::m_dist private
the distance between nodes
Definition at line 106 of file lte-test-pf-ff-mac-scheduler.h.
Referenced by DoRun().
m_errorModelEnabled
bool LenaPfFfMacSchedulerTestCase2::m_errorModelEnabled private
indicates whether the error model is enabled
Definition at line 109 of file lte-test-pf-ff-mac-scheduler.h.
Referenced by DoRun().
m_estThrPfDl
std::vector<uint32_t> LenaPfFfMacSchedulerTestCase2::m_estThrPfDl private
the estimated DL throughput
Definition at line 107 of file lte-test-pf-ff-mac-scheduler.h.
Referenced by DoRun().
m_estThrPfUl
std::vector<uint32_t> LenaPfFfMacSchedulerTestCase2::m_estThrPfUl private
the estimated UL throughput
Definition at line 108 of file lte-test-pf-ff-mac-scheduler.h.
Referenced by DoRun().
m_nUser
uint16_t LenaPfFfMacSchedulerTestCase2::m_nUser private
number of UE nodes
Definition at line 105 of file lte-test-pf-ff-mac-scheduler.h.
Referenced by DoRun().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-pf-ff-mac-scheduler.h
src/lte/test/lte-test-pf-ff-mac-scheduler.cc