ns-3: ns3::LteFfrRrcSapUser Class Reference
ns3::LteFfrRrcSapUser Class Reference abstract
Service Access Point (SAP) offered by the eNodeB RRC instance to the Frequency Reuse algorithm instance.
#include "lte-ffr-rrc-sap.h"
Public Member Functions
virtual ~LteFfrRrcSapUser ()
virtual uint8_t AddUeMeasReportConfigForFfr (LteRrcSap::ReportConfigEutra reportConfig)=0
Request a certain reporting configuration to be fulfilled by the UEs attached to the eNodeB entity.
virtual void SendLoadInformation (EpcX2Sap::LoadInformationParams params)=0
SendLoadInformation.
virtual void SetPdschConfigDedicated (uint16_t rnti, LteRrcSap::PdschConfigDedicated pdschConfigDedicated)=0
Instruct the eNodeB RRC entity to perform RrcConnectionReconfiguration to inform UE about new PdschConfigDedicated (i.e.
Detailed Description
Service Access Point (SAP) offered by the eNodeB RRC instance to the Frequency Reuse algorithm instance.
This is the LteFfrRrcSapUser, i.e., the part of the SAP that contains the eNodeB RRC methods called by the Frequency Reuse algorithm instance.
Definition at line 88 of file lte-ffr-rrc-sap.h.
Constructor & Destructor Documentation
~LteFfrRrcSapUser()
ns3::LteFfrRrcSapUser::~LteFfrRrcSapUser () virtual
Definition at line 34 of file lte-ffr-rrc-sap.cc.
Member Function Documentation
AddUeMeasReportConfigForFfr()
virtual uint8_t ns3::LteFfrRrcSapUser::AddUeMeasReportConfigForFfr (LteRrcSap::ReportConfigEutra reportConfig) pure virtual
Request a certain reporting configuration to be fulfilled by the UEs attached to the eNodeB entity.
Parameters
reportConfig the UE measurement reporting configuration
Returns
the measurement identity associated with this newly added reporting configuration
The eNodeB RRC entity is expected to configure the same reporting configuration in each of the attached UEs. When later in the simulation a UE measurement report is received from a UE as a result of this configuration, the eNodeB RRC entity shall forward this report to the Frequency Reuse algorithm through the LteFfrRrcSapProvider::ReportUeMeas SAP function.
Note
This function is only valid before the simulation begins.
Implemented in ns3::MemberLteFfrRrcSapUser< C >.
Referenced by ns3::LteFfrDistributedAlgorithm::DoInitialize(), ns3::LteFfrEnhancedAlgorithm::DoInitialize(), ns3::LteFfrSoftAlgorithm::DoInitialize(), ns3::LteFrSoftAlgorithm::DoInitialize(), ns3::LteFrStrictAlgorithm::DoInitialize(), and ns3::LteFfrSimple::DoInitialize().
SendLoadInformation()
virtual void ns3::LteFfrRrcSapUser::SendLoadInformation (EpcX2Sap::LoadInformationParams params) pure virtual
SendLoadInformation.
Parameters
params the EpcX2Sap::LoadInformationParams
Implemented in ns3::MemberLteFfrRrcSapUser< C >.
Referenced by ns3::LteFfrDistributedAlgorithm::SendLoadInformation().
SetPdschConfigDedicated()
virtual void ns3::LteFfrRrcSapUser::SetPdschConfigDedicated (uint16_t rnti, LteRrcSap::PdschConfigDedicated pdschConfigDedicated) pure virtual
Instruct the eNodeB RRC entity to perform RrcConnectionReconfiguration to inform UE about new PdschConfigDedicated (i.e.
P_a value). Also Downlink Power Allocation is done based on this value.
Parameters
rnti Radio Network Temporary Identity, an integer identifying the UE which shall perform the handover
pdschConfigDedicated new PdschConfigDedicated to be configured for UE
This function is used by the Frequency Reuse algorithm entity when it decides that PDSCH for this UE should be allocated with different transmit power.
The process to produce the decision is up to the implementation of Frequency Reuse algorithm. It is typically based on the reported UE measurements, which are received through the LteFfrRrcSapProvider::ReportUeMeas function.
Implemented in ns3::MemberLteFfrRrcSapUser< C >.
Referenced by ns3::LteFfrDistributedAlgorithm::DoReportUeMeas(), ns3::LteFfrEnhancedAlgorithm::DoReportUeMeas(), ns3::LteFfrSoftAlgorithm::DoReportUeMeas(), ns3::LteFrSoftAlgorithm::DoReportUeMeas(), ns3::LteFrStrictAlgorithm::DoReportUeMeas(), and ns3::LteFfrSimple::UpdatePdschConfigDedicated().
The documentation for this class was generated from the following files:
src/lte/model/lte-ffr-rrc-sap.h
src/lte/model/lte-ffr-rrc-sap.cc