ns-3: CarrierAggregationConfigTestCase Class Reference
CarrierAggregationConfigTestCase Class Reference
LTE Models » lte module tests | Test suites
Carrier aggregation configuration test case.
Public Member Functions
CarrierAggregationConfigTestCase (uint32_t numberOfNodes, uint16_t numberOfComponentCarriers, std::vector< ConfigToCheck > configToCheck, Time simulationDuration)
Constructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
std::string BuildNameString (uint32_t numberOfNodes, uint16_t numberOfComponentCarriers, std::vector< ConfigToCheck > configToCheck, Time simulationDuration)
Build name string function.
virtual void DoRun (void)
Implementation to actually run this TestCase.
std::vector< std::map< uint16_t, ConfigToCheck > > EquallySpacedCcs ()
Equally spaced component carriers function.
void Evaluate (std::string context, Ptr< LteUeRrc > ueRrc, std::list< LteRrcSap::SCellToAddMod > sCellToAddModList)
Evaluate function.
Private Attributes
std::vector< ConfigToCheck > m_configToCheck
Vector containing all the configurations to check.
std::vector< std::map< uint16_t, ConfigToCheck > > m_configToCheckContainer
Vector of maps containing the per component carrier configuration.
uint32_t m_connectionCounter
Connection counter.
uint16_t m_numberOfComponentCarriers
Number of component carriers.
uint32_t m_numberOfNodes
Numer of nodes.
Time m_simulationDuration
Simulation duration.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Carrier aggregation configuration test case.
Definition at line 81 of file lte-test-carrier-aggregation-configuration.cc.
Constructor & Destructor Documentation
CarrierAggregationConfigTestCase()
CarrierAggregationConfigTestCase::CarrierAggregationConfigTestCase (uint32_t numberOfNodes, uint16_t numberOfComponentCarriers, std::vector< ConfigToCheck > configToCheck, Time simulationDuration) inline
Constructor.
Parameters
numberOfNodes Total Number of eNBs and UEs
numberOfComponentCarriers Total number of component carriers
configToCheck Vector containing all the configurations to check
simulationDuration Duration of the simulation
Definition at line 92 of file lte-test-carrier-aggregation-configuration.cc.
Member Function Documentation
BuildNameString()
std::string CarrierAggregationConfigTestCase::BuildNameString (uint32_t numberOfNodes, uint16_t numberOfComponentCarriers, std::vector< ConfigToCheck > configToCheck, Time simulationDuration) private
Build name string function.
Parameters
numberOfNodes Total Number of eNBs and UEs
numberOfComponentCarriers Total number of component carriers
configToCheck Vector containing all the configurations to check
simulationDuration Duration of the simulation
Returns
the name string
Definition at line 139 of file lte-test-carrier-aggregation-configuration.cc.
DoRun()
void CarrierAggregationConfigTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 271 of file lte-test-carrier-aggregation-configuration.cc.
References ns3::LteHelper::ActivateDataRadioBearer(), ns3::NetDeviceContainer::Add(), ns3::ListPositionAllocator::Add(), ns3::LteHelper::AssignStreams(), ns3::LteHelper::Attach(), ns3::Config::Connect(), ns3::NodeContainer::Create(), ns3::Simulator::Destroy(), Evaluate(), ns3::EpsBearer::GBR_CONV_VOICE, ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::NodeContainer::GetN(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), ConfigToCheck::m_dlBandwidth, ConfigToCheck::m_dlEarfcn, ConfigToCheck::m_ulBandwidth, ConfigToCheck::m_ulEarfcn, ns3::MakeCallback(), third::mobility, sample-rng-plot::n, NS_TEST_ASSERT_MSG_EQ, ns3::Simulator::Run(), ns3::Config::SetDefault(), ns3::LteHelper::SetEnbDeviceAttribute(), ns3::LteHelper::SetUeDeviceAttribute(), and ns3::Simulator::Stop().
EquallySpacedCcs()
std::vector< std::map< uint16_t, ConfigToCheck > > CarrierAggregationConfigTestCase::EquallySpacedCcs () private
Equally spaced component carriers function.
Returns
Vector of maps containing the per component carrier configuration
Definition at line 149 of file lte-test-carrier-aggregation-configuration.cc.
References ns3::LteSpectrumValueHelper::GetChannelBandwidth(), ns3::LteSpectrumValueHelper::GetDownlinkCarrierBand(), ns3::LteSpectrumValueHelper::GetUplinkCarrierBand(), ConfigToCheck::m_dlBandwidth, ConfigToCheck::m_dlEarfcn, ConfigToCheck::m_ulBandwidth, ConfigToCheck::m_ulEarfcn, NS_FATAL_ERROR, and NS_LOG_INFO.
Evaluate()
void CarrierAggregationConfigTestCase::Evaluate (std::string context, Ptr< LteUeRrc > ueRrc, std::list< LteRrcSap::SCellToAddMod > sCellToAddModList) private
Evaluate function.
Parameters
context The context
ueRrc Pointer to the UE RRC
sCellToAddModList List of the configuration parameters for secondary cell
Definition at line 204 of file lte-test-carrier-aggregation-configuration.cc.
References ns3::LteUeRrc::GetCellId(), ns3::LteUeRrc::GetDlBandwidth(), ns3::LteUeRrc::GetDlEarfcn(), ns3::LteUeRrc::GetUlBandwidth(), ns3::LteUeRrc::GetUlEarfcn(), ConfigToCheck::m_dlBandwidth, ConfigToCheck::m_dlEarfcn, ConfigToCheck::m_ulBandwidth, ConfigToCheck::m_ulEarfcn, max, min, NS_LOG_INFO, and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
Member Data Documentation
m_configToCheck
std::vector<ConfigToCheck> CarrierAggregationConfigTestCase::m_configToCheck private
Vector containing all the configurations to check.
Definition at line 132 of file lte-test-carrier-aggregation-configuration.cc.
m_configToCheckContainer
std::vector<std::map<uint16_t, ConfigToCheck> > CarrierAggregationConfigTestCase::m_configToCheckContainer private
Vector of maps containing the per component carrier configuration.
Definition at line 135 of file lte-test-carrier-aggregation-configuration.cc.
m_connectionCounter
uint32_t CarrierAggregationConfigTestCase::m_connectionCounter private
Connection counter.
Definition at line 133 of file lte-test-carrier-aggregation-configuration.cc.
m_numberOfComponentCarriers
uint16_t CarrierAggregationConfigTestCase::m_numberOfComponentCarriers private
Number of component carriers.
Definition at line 131 of file lte-test-carrier-aggregation-configuration.cc.
m_numberOfNodes
uint32_t CarrierAggregationConfigTestCase::m_numberOfNodes private
Numer of nodes.
Definition at line 130 of file lte-test-carrier-aggregation-configuration.cc.
m_simulationDuration
Time CarrierAggregationConfigTestCase::m_simulationDuration private
Simulation duration.
Definition at line 134 of file lte-test-carrier-aggregation-configuration.cc.
The documentation for this class was generated from the following file:
src/lte/test/lte-test-carrier-aggregation-configuration.cc