ns-3: ns3::FlowProbe Class Reference
ns3::FlowProbe Class Reference
The FlowProbe class is responsible for listening for packet events in a specific point of the simulated space, report those events to the global FlowMonitor, and collect its own flow statistics regarding only the packets that pass through that probe.
#include "flow-probe.h"
Classes
struct FlowStats
Structure to hold the statistics of a flow.
Public Types
typedef std::map< FlowId, FlowStats > Stats
Container to map FlowId -> FlowStats.
Public Member Functions
virtual ~FlowProbe ()
void AddPacketDropStats (FlowId flowId, uint32_t packetSize, uint32_t reasonCode)
Add a packet drop data to the flow stats.
void AddPacketStats (FlowId flowId, uint32_t packetSize, Time delayFromFirstProbe)
Add a packet data to the flow stats.
Stats GetStats () const
Get the partial flow statistics stored in this probe.
void SerializeToXmlStream (std::ostream &os, uint16_t indent, uint32_t index) const
Serializes the results to an std::ostream in XML format.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
FlowProbe (Ptr< FlowMonitor > flowMonitor)
Constructor.
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes
Ptr< FlowMonitor > m_flowMonitor
the FlowMonitor instance
Stats m_stats
The flow stats.
Private Member Functions
FlowProbe (FlowProbe const &)
Defined and not implemented to avoid misuse.
FlowProbe & operator= (FlowProbe const &)
Defined and not implemented to avoid misuse.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The FlowProbe class is responsible for listening for packet events in a specific point of the simulated space, report those events to the global FlowMonitor, and collect its own flow statistics regarding only the packets that pass through that probe.
Definition at line 39 of file flow-probe.h.
Member Typedef Documentation
Stats
typedef std::map<FlowId, FlowStats> ns3::FlowProbe::Stats
Container to map FlowId -> FlowStats.
Definition at line 80 of file flow-probe.h.
Constructor & Destructor Documentation
FlowProbe() [1/2]
ns3::FlowProbe::FlowProbe (FlowProbe const &) private
Defined and not implemented to avoid misuse.
FlowProbe() [2/2]
ns3::FlowProbe::FlowProbe (Ptr< FlowMonitor > flowMonitor) protected
Constructor.
Parameters
flowMonitor the FlowMonitor this probe is associated with
Definition at line 43 of file flow-probe.cc.
References m_flowMonitor.
~FlowProbe()
ns3::FlowProbe::~FlowProbe () virtual
Definition at line 38 of file flow-probe.cc.
Member Function Documentation
AddPacketDropStats()
void ns3::FlowProbe::AddPacketDropStats (FlowId flowId, uint32_t packetSize, uint32_t reasonCode)
Add a packet drop data to the flow stats.
Parameters
flowId the flow Identifier
packetSize the packet size
reasonCode reason code for the drop
Definition at line 66 of file flow-probe.cc.
References ns3::FlowProbe::FlowStats::bytesDropped, m_stats, ns3::FlowProbe::FlowStats::packetsDropped, and packetSize.
Referenced by ns3::FlowMonitor::ReportDrop().
AddPacketStats()
void ns3::FlowProbe::AddPacketStats (FlowId flowId, uint32_t packetSize, Time delayFromFirstProbe)
Add a packet data to the flow stats.
Parameters
flowId the flow Identifier
packetSize the packet size
delayFromFirstProbe packet delay
Definition at line 57 of file flow-probe.cc.
References ns3::FlowProbe::FlowStats::bytes, ns3::FlowProbe::FlowStats::delayFromFirstProbeSum, m_stats, ns3::FlowProbe::FlowStats::packets, and packetSize.
Referenced by ns3::FlowMonitor::ReportFirstTx(), ns3::FlowMonitor::ReportForwarding(), and ns3::FlowMonitor::ReportLastRx().
DoDispose()
void ns3::FlowProbe::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Reimplemented in ns3::Ipv6FlowProbe, and ns3::Ipv4FlowProbe.
Definition at line 50 of file flow-probe.cc.
References ns3::Object::DoDispose(), and m_flowMonitor.
Referenced by ns3::Ipv4FlowProbe::DoDispose(), and ns3::Ipv6FlowProbe::DoDispose().
GetStats()
FlowProbe::Stats ns3::FlowProbe::GetStats () const
Get the partial flow statistics stored in this probe.
With this information you can, for example, find out what is the delay from the first probe to this one.
Returns
the partial flow statistics
Definition at line 80 of file flow-probe.cc.
References m_stats.
GetTypeId()
TypeId ns3::FlowProbe::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 27 of file flow-probe.cc.
References ns3::TypeId::SetParent().
operator=()
FlowProbe& ns3::FlowProbe::operator= (FlowProbe const &) private
Defined and not implemented to avoid misuse.
Returns
SerializeToXmlStream()
void ns3::FlowProbe::SerializeToXmlStream (std::ostream & os, uint16_t indent, uint32_t index) const
Serializes the results to an std::ostream in XML format.
Parameters
os the output stream
indent number of spaces to use as base indentation level
index FlowProbe index
Definition at line 86 of file flow-probe.cc.
References check-style::indent(), and m_stats.
Member Data Documentation
m_flowMonitor
Ptr<FlowMonitor> ns3::FlowProbe::m_flowMonitor protected
the FlowMonitor instance
Definition at line 106 of file flow-probe.h.
Referenced by FlowProbe(), DoDispose(), ns3::Ipv4FlowProbe::DropLogger(), ns3::Ipv6FlowProbe::DropLogger(), ns3::Ipv4FlowProbe::ForwardLogger(), ns3::Ipv6FlowProbe::ForwardLogger(), ns3::Ipv4FlowProbe::ForwardUpLogger(), ns3::Ipv6FlowProbe::ForwardUpLogger(), ns3::Ipv4FlowProbe::QueueDiscDropLogger(), ns3::Ipv6FlowProbe::QueueDiscDropLogger(), ns3::Ipv4FlowProbe::QueueDropLogger(), ns3::Ipv6FlowProbe::QueueDropLogger(), ns3::Ipv4FlowProbe::SendOutgoingLogger(), and ns3::Ipv6FlowProbe::SendOutgoingLogger().
m_stats
Stats ns3::FlowProbe::m_stats protected
The flow stats.
Definition at line 107 of file flow-probe.h.
Referenced by AddPacketDropStats(), AddPacketStats(), GetStats(), and SerializeToXmlStream().
The documentation for this class was generated from the following files:
src/flow-monitor/model/flow-probe.h
src/flow-monitor/model/flow-probe.cc