ns-3: ns3::DsssSigHeader Class Reference
ns3::DsssSigHeader Class Reference
Wifi Models
#include "wifi-phy-header.h"
Public Member Functions
DsssSigHeader ()
virtual ~DsssSigHeader ()
uint32_t Deserialize (Buffer::Iterator start)
TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint16_t GetLength (void) const
Return the LENGTH field of L-SIG (in bytes).
uint64_t GetRate (void) const
Return the RATE field of L-SIG (in bit/s).
uint32_t GetSerializedSize (void) const
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetLength (uint16_t length)
Fill the LENGTH field of L-SIG (in bytes).
void SetRate (uint64_t rate)
Fill the RATE field of L-SIG (in bit/s).
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint16_t m_length
LENGTH field.
uint8_t m_rate
RATE field.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implements the IEEE 802.11 DSSS SIG PHY header. See section 16.2.2 in IEEE 802.11-2016.
Definition at line 34 of file wifi-phy-header.h.
Constructor & Destructor Documentation
DsssSigHeader()
ns3::DsssSigHeader::DsssSigHeader ()
Definition at line 27 of file wifi-phy-header.cc.
~DsssSigHeader()
ns3::DsssSigHeader::~DsssSigHeader () virtual
Definition at line 33 of file wifi-phy-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::DsssSigHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 143 of file wifi-phy-header.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_length, m_rate, ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetInstanceTypeId()
TypeId ns3::DsssSigHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 49 of file wifi-phy-header.cc.
References GetTypeId().
GetLength()
uint16_t ns3::DsssSigHeader::GetLength (void) const
Return the LENGTH field of L-SIG (in bytes).
Returns
the LENGTH field of L-SIG expressed in bytes
Definition at line 128 of file wifi-phy-header.cc.
References m_length.
Referenced by ns3::WifiPpdu::GetTxDuration().
GetRate()
uint64_t ns3::DsssSigHeader::GetRate (void) const
Return the RATE field of L-SIG (in bit/s).
Returns
the RATE field of L-SIG expressed in bit/s
Definition at line 97 of file wifi-phy-header.cc.
References m_rate, and NS_ASSERT_MSG().
Referenced by ns3::WifiPpdu::GetTxVector(), and Print().
GetSerializedSize()
uint32_t ns3::DsssSigHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 62 of file wifi-phy-header.cc.
GetTypeId()
TypeId ns3::DsssSigHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 38 of file wifi-phy-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::DsssSigHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 55 of file wifi-phy-header.cc.
References GetRate(), and m_length.
Serialize()
void ns3::DsssSigHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 134 of file wifi-phy-header.cc.
References m_length, m_rate, and visualizer.core::start().
SetLength()
void ns3::DsssSigHeader::SetLength (uint16_t length)
Fill the LENGTH field of L-SIG (in bytes).
Parameters
length the LENGTH field of L-SIG expressed in bytes
Definition at line 122 of file wifi-phy-header.cc.
References m_length.
Referenced by ns3::WifiPpdu::WifiPpdu().
SetRate()
void ns3::DsssSigHeader::SetRate (uint64_t rate)
Fill the RATE field of L-SIG (in bit/s).
Parameters
rate the RATE field of L-SIG expressed in bit/s
Definition at line 68 of file wifi-phy-header.cc.
References m_rate, and NS_ASSERT_MSG().
Referenced by ns3::WifiPpdu::WifiPpdu().
Member Data Documentation
m_length
uint16_t ns3::DsssSigHeader::m_length private
LENGTH field.
Definition at line 79 of file wifi-phy-header.h.
Referenced by Deserialize(), GetLength(), Print(), Serialize(), and SetLength().
m_rate
uint8_t ns3::DsssSigHeader::m_rate private
RATE field.
Definition at line 78 of file wifi-phy-header.h.
Referenced by Deserialize(), GetRate(), Serialize(), and SetRate().
The documentation for this class was generated from the following files:
src/wifi/model/wifi-phy-header.h
src/wifi/model/wifi-phy-header.cc