ns-3: ns3::Probe Class Reference
ns3::Probe Class Reference abstract
Statistics » Probes
#include "probe.h"
Public Member Functions
Probe ()
virtual ~Probe ()
virtual bool ConnectByObject (std::string traceSource, Ptr< Object > obj)=0
connect to a trace source attribute provided by a given object
virtual void ConnectByPath (std::string path)=0
connect to a trace source provided by a config path
virtual bool IsEnabled (void) const
Public Member Functions inherited from ns3::DataCollectionObject
DataCollectionObject ()
virtual ~DataCollectionObject ()
void Disable (void)
Unset the status of an individual object.
void Enable (void)
Set the status of an individual object.
std::string GetName (void) const
Get the object's name.
void SetName (std::string name)
Set the object's name. All spaces are replaced by underscores.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::DataCollectionObject
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Attributes
Time m_start
Time when logging starts.
Time m_stop
Time when logging stops.
Protected Attributes inherited from ns3::DataCollectionObject
bool m_enabled
Object's activation state.
std::string m_name
Name of the object within the data collection framework.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Base class for probes.
This class provides general functionality to control each probe and the data generated by it.
Definition at line 39 of file probe.h.
Constructor & Destructor Documentation
Probe()
ns3::Probe::Probe ()
Definition at line 53 of file probe.cc.
References NS_LOG_FUNCTION.
~Probe()
ns3::Probe::~Probe () virtual
Definition at line 58 of file probe.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
ConnectByObject()
virtual bool ns3::Probe::ConnectByObject (std::string traceSource, Ptr< Object > obj) pure virtual
connect to a trace source attribute provided by a given object
Parameters
traceSource the name of the attribute TraceSource to connect to
obj ns3::Object to connect to
Returns
true if the trace source was successfully connected
Implemented in ns3::Uinteger8Probe, ns3::Uinteger32Probe, ns3::Uinteger16Probe, ns3::TimeProbe, ns3::DoubleProbe, ns3::BooleanProbe, ns3::PacketProbe, ns3::Ipv6PacketProbe, ns3::Ipv4PacketProbe, and ns3::ApplicationPacketProbe.
ConnectByPath()
virtual void ns3::Probe::ConnectByPath (std::string path) pure virtual
connect to a trace source provided by a config path
Parameters
path Config path to bind to
Note, if an invalid path is provided, the probe will not be connected to anything.
Implemented in ns3::Uinteger8Probe, ns3::Uinteger32Probe, ns3::Uinteger16Probe, ns3::TimeProbe, ns3::DoubleProbe, ns3::BooleanProbe, ns3::PacketProbe, ns3::Ipv6PacketProbe, ns3::Ipv4PacketProbe, and ns3::ApplicationPacketProbe.
GetTypeId()
TypeId ns3::Probe::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 34 of file probe.cc.
References m_start, m_stop, ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::Seconds(), and ns3::TypeId::SetParent().
IsEnabled()
bool ns3::Probe::IsEnabled (void) const virtual
Returns
true if Probe is currently enabled
Reimplemented from ns3::DataCollectionObject.
Definition at line 64 of file probe.cc.
References ns3::DataCollectionObject::IsEnabled(), m_start, m_stop, ns3::Simulator::Now(), and ns3::Seconds().
Referenced by ns3::BooleanProbe::TraceSink(), ns3::DoubleProbe::TraceSink(), ns3::PacketProbe::TraceSink(), ns3::ApplicationPacketProbe::TraceSink(), ns3::Ipv4PacketProbe::TraceSink(), ns3::Ipv6PacketProbe::TraceSink(), ns3::TimeProbe::TraceSink(), ns3::Uinteger16Probe::TraceSink(), ns3::Uinteger32Probe::TraceSink(), and ns3::Uinteger8Probe::TraceSink().
Member Data Documentation
m_start
Time ns3::Probe::m_start protected
Time when logging starts.
Definition at line 76 of file probe.h.
Referenced by GetTypeId(), and IsEnabled().
m_stop
Time ns3::Probe::m_stop protected
Time when logging stops.
Definition at line 79 of file probe.h.
Referenced by GetTypeId(), and IsEnabled().
The documentation for this class was generated from the following files:
src/stats/model/probe.h
src/stats/model/probe.cc