ns-3: ns3::RngRsp Class Reference
ns3::RngRsp Class Reference
WiMAX Models
#include "mac-messages.h"
Public Member Functions
RngRsp (void)
virtual ~RngRsp (void)
uint32_t Deserialize (Buffer::Iterator start)
uint8_t GetAasBdcastPermission (void) const
Cid GetBasicCid (void) const
uint32_t GetDlFreqOverride (void) const
uint16_t GetDlOperBurstProfile (void) const
uint32_t GetFrameNumber (void) const
uint8_t GetInitRangOppNumber (void) const
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
Mac48Address GetMacAddress (void) const
std::string GetName (void) const
uint32_t GetOffsetFreqAdjust (void) const
uint8_t GetPowerLevelAdjust (void) const
Cid GetPrimaryCid (void) const
uint8_t GetRangStatus (void) const
uint8_t GetRangSubchnl (void) const
uint32_t GetSerializedSize (void) const
uint32_t GetTimingAdjust (void) const
uint8_t GetUlChnlIdOverride (void) const
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetAasBdcastPermission (uint8_t aasBdcastPermission)
set AAS broadcast permission.
void SetBasicCid (Cid basicCid)
set basic CID.
void SetDlFreqOverride (uint32_t dlFreqOverride)
set the Center frequency, in kHz, of new downlink channel where the SS should redo initial ranging.
void SetDlOperBurstProfile (uint16_t dlOperBurstProfile)
set the DL oper burst profile
void SetFrameNumber (uint32_t frameNumber)
set frame number.
void SetInitRangOppNumber (uint8_t initRangOppNumber)
set initial range opp number.
void SetMacAddress (Mac48Address macAddress)
set the MAC address
void SetOffsetFreqAdjust (uint32_t offsetFreqAdjust)
set the relative change in transmission frequency that the SS should take in order to better match the BS.
void SetPowerLevelAdjust (uint8_t powerLevelAdjust)
set the relative change in transmission power level that the SS should make in order that transmissions arrive at the BS at the desired power.
void SetPrimaryCid (Cid primaryCid)
set primary CID.
void SetRangStatus (uint8_t rangStatus)
set the range status.
void SetRangSubchnl (uint8_t rangSubchnl)
set range sub channel.
void SetTimingAdjust (uint32_t timingAdjust)
set the Tx timing offset adjustment (signed 32-bit).
void SetUlChnlIdOverride (uint8_t ulChnlIdOverride)
set the identifier of the uplink channel with which the SS is to redo initial ranging
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_aasBdcastPermission
AAS broadcast permission.
Cid m_basicCid
basic CID
uint32_t m_dlFreqOverride
Center frequency, in kHz, of new downlink channel where the SS should redo initial ranging.
uint16_t m_dlOperBurstProfile
This parameter is sent in response to the RNG-REQ Requested Downlink Burst Profile parameter.
uint32_t m_frameNumber
Frame number where the associated RNG_REQ message was detected by the BS.
uint8_t m_initRangOppNumber
Initial Ranging opportunity (1–255) in which the associated RNG_REQ message was detected by the BS.
Mac48Address m_macAddress
MAC address.
uint32_t m_offsetFreqAdjust
Specifies the relative change in transmission frequency that the SS is to make in order to better match the BS.
uint8_t m_powerLevelAdjust
Specifies the relative change in transmission power level that the SS is to make in order that transmissions arrive at the BS at the desired power.
Cid m_primaryCid
primary CID
uint8_t m_rangStatus
range status.
uint8_t m_rangSubchnl
Used to indicate the OFDM subchannel reference that was used to transmit the initial ranging message (OFDM with subchannelization).
uint8_t m_reserved
changed as per the amendment 802.16e-2005
uint32_t m_timingAdjust
Tx timing offset adjustment (signed 32-bit).
uint8_t m_ulChnlIdOverride
Licensed bands: The identifier of the uplink channel with which the SS is to redo initial ranging (not used with PHYs without channelized uplinks).
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class implements the ranging response message described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems" 6.3.2.3.6 Ranging response (RNG-RSP) message, page 50
Definition at line 121 of file mac-messages.h.
Constructor & Destructor Documentation
RngRsp()
ns3::RngRsp::RngRsp (void)
Definition at line 234 of file mac-messages.cc.
~RngRsp()
ns3::RngRsp::~RngRsp (void) virtual
Definition at line 253 of file mac-messages.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::RngRsp::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 489 of file mac-messages.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_aasBdcastPermission, m_basicCid, m_dlFreqOverride, m_dlOperBurstProfile, m_frameNumber, m_initRangOppNumber, m_macAddress, m_offsetFreqAdjust, m_powerLevelAdjust, m_primaryCid, m_rangStatus, m_rangSubchnl, m_reserved, m_timingAdjust, m_ulChnlIdOverride, ns3::ReadFrom(), ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU32(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetAasBdcastPermission()
uint8_t ns3::RngRsp::GetAasBdcastPermission (void) const
Returns
AAS broadcast permission
Definition at line 402 of file mac-messages.cc.
References m_aasBdcastPermission.
GetBasicCid()
Cid ns3::RngRsp::GetBasicCid (void) const
Returns
basic CID
Definition at line 390 of file mac-messages.cc.
References m_basicCid.
Referenced by ns3::SSLinkManager::PerformRanging().
GetDlFreqOverride()
uint32_t ns3::RngRsp::GetDlFreqOverride (void) const
Returns
Center frequency, in kHz, of new downlink channel where the SS should redo initial ranging.
Definition at line 366 of file mac-messages.cc.
References m_dlFreqOverride.
Referenced by ns3::SSLinkManager::PerformRanging().
GetDlOperBurstProfile()
uint16_t ns3::RngRsp::GetDlOperBurstProfile (void) const
Returns
DlOperBurstProfile: This parameter is sent in response to the RNG-REQ Requested Downlink Burst Profile parameter
Definition at line 378 of file mac-messages.cc.
References m_dlOperBurstProfile.
GetFrameNumber()
uint32_t ns3::RngRsp::GetFrameNumber (void) const
Returns
frame number
Definition at line 408 of file mac-messages.cc.
References m_frameNumber.
Referenced by ns3::SSLinkManager::PerformRanging().
GetInitRangOppNumber()
uint8_t ns3::RngRsp::GetInitRangOppNumber (void) const
Returns
initial range opp number
Definition at line 414 of file mac-messages.cc.
References m_initRangOppNumber.
Referenced by ns3::SSLinkManager::PerformRanging().
GetInstanceTypeId()
TypeId ns3::RngRsp::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 443 of file mac-messages.cc.
References GetTypeId().
GetMacAddress()
Mac48Address ns3::RngRsp::GetMacAddress (void) const
Returns
MAC address
Definition at line 384 of file mac-messages.cc.
References m_macAddress.
Referenced by ns3::SSLinkManager::PerformRanging().
GetName()
std::string ns3::RngRsp::GetName (void) const
Returns
name string
Definition at line 426 of file mac-messages.cc.
GetOffsetFreqAdjust()
uint32_t ns3::RngRsp::GetOffsetFreqAdjust (void) const
Returns
the relative change in transmission frequency that the SS should take in order to better match the BS. This is fine-frequency adjustment within a channel, not reassignment to a different channel.
Definition at line 354 of file mac-messages.cc.
References m_offsetFreqAdjust.
Referenced by ns3::SSLinkManager::AdjustRangingParameters().
GetPowerLevelAdjust()
uint8_t ns3::RngRsp::GetPowerLevelAdjust (void) const
Returns
the relative change in transmission power level that the SS should take in order that transmissions arrive at the BS at the desired power. When subchannelization is employed, the subscriber shall interpret the power offset adjustment as a required change to the transmitted power density.
Definition at line 348 of file mac-messages.cc.
References m_powerLevelAdjust.
Referenced by ns3::SSLinkManager::AdjustRangingParameters().
GetPrimaryCid()
Cid ns3::RngRsp::GetPrimaryCid (void) const
Returns
primary CID
Definition at line 396 of file mac-messages.cc.
References m_primaryCid.
Referenced by ns3::SSLinkManager::PerformRanging().
GetRangStatus()
uint8_t ns3::RngRsp::GetRangStatus (void) const
Returns
the range status.
Definition at line 360 of file mac-messages.cc.
References m_rangStatus.
Referenced by ns3::SSLinkManager::PerformRanging(), and ns3::BSLinkManager::ScheduleRngRspMessage().
GetRangSubchnl()
uint8_t ns3::RngRsp::GetRangSubchnl (void) const
Returns
range sub channel
Definition at line 420 of file mac-messages.cc.
References m_rangSubchnl.
GetSerializedSize()
uint32_t ns3::RngRsp::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 462 of file mac-messages.cc.
GetTimingAdjust()
uint32_t ns3::RngRsp::GetTimingAdjust (void) const
Returns
Tx timing offset adjustment (signed 32-bit). The time required to advance SS transmission so frames arrive at the expected time instance at the BS.
Definition at line 342 of file mac-messages.cc.
References m_timingAdjust.
Referenced by ns3::SSLinkManager::AdjustRangingParameters().
GetTypeId()
TypeId ns3::RngRsp::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 432 of file mac-messages.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
GetUlChnlIdOverride()
uint8_t ns3::RngRsp::GetUlChnlIdOverride (void) const
Returns
The identifier of the uplink channel with which the SS is to redo initial ranging
Definition at line 372 of file mac-messages.cc.
References m_ulChnlIdOverride.
Print()
void ns3::RngRsp::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 449 of file mac-messages.cc.
References m_aasBdcastPermission, m_basicCid, m_dlFreqOverride, m_dlOperBurstProfile, m_frameNumber, m_initRangOppNumber, m_macAddress, m_offsetFreqAdjust, m_powerLevelAdjust, m_primaryCid, m_rangStatus, m_rangSubchnl, m_timingAdjust, and m_ulChnlIdOverride.
Serialize()
void ns3::RngRsp::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 468 of file mac-messages.cc.
References ns3::Cid::GetIdentifier(), m_aasBdcastPermission, m_basicCid, m_dlFreqOverride, m_dlOperBurstProfile, m_frameNumber, m_initRangOppNumber, m_macAddress, m_offsetFreqAdjust, m_powerLevelAdjust, m_primaryCid, m_rangStatus, m_rangSubchnl, m_reserved, m_timingAdjust, m_ulChnlIdOverride, visualizer.core::start(), ns3::WriteTo(), ns3::Buffer::Iterator::WriteU16(), ns3::Buffer::Iterator::WriteU32(), and ns3::Buffer::Iterator::WriteU8().
SetAasBdcastPermission()
void ns3::RngRsp::SetAasBdcastPermission (uint8_t aasBdcastPermission)
set AAS broadcast permission.
Parameters
aasBdcastPermission
Definition at line 318 of file mac-messages.cc.
References m_aasBdcastPermission.
SetBasicCid()
void ns3::RngRsp::SetBasicCid (Cid basicCid)
set basic CID.
Parameters
basicCid
Definition at line 306 of file mac-messages.cc.
References m_basicCid.
Referenced by ns3::ConnectionManager::AllocateManagementConnections().
SetDlFreqOverride()
void ns3::RngRsp::SetDlFreqOverride (uint32_t dlFreqOverride)
set the Center frequency, in kHz, of new downlink channel where the SS should redo initial ranging.
Parameters
dlFreqOverride the Center frequency in kHz
Definition at line 282 of file mac-messages.cc.
References m_dlFreqOverride.
Referenced by ns3::BSLinkManager::PerformInitialRanging().
SetDlOperBurstProfile()
void ns3::RngRsp::SetDlOperBurstProfile (uint16_t dlOperBurstProfile)
set the DL oper burst profile
Parameters
dlOperBurstProfile the oper burt profile
Definition at line 294 of file mac-messages.cc.
References m_dlOperBurstProfile.
Referenced by ns3::BSLinkManager::PerformInitialRanging().
SetFrameNumber()
void ns3::RngRsp::SetFrameNumber (uint32_t frameNumber)
set frame number.
Parameters
frameNumber
Definition at line 324 of file mac-messages.cc.
References m_frameNumber.
Referenced by ns3::BSLinkManager::PerformRanging().
SetInitRangOppNumber()
void ns3::RngRsp::SetInitRangOppNumber (uint8_t initRangOppNumber)
set initial range opp number.
Parameters
initRangOppNumber
Definition at line 330 of file mac-messages.cc.
References m_initRangOppNumber.
Referenced by ns3::BSLinkManager::PerformRanging().
SetMacAddress()
void ns3::RngRsp::SetMacAddress (Mac48Address macAddress)
set the MAC address
Parameters
macAddress the MAC address
Definition at line 300 of file mac-messages.cc.
References m_macAddress.
Referenced by ns3::BSLinkManager::PerformInitialRanging().
SetOffsetFreqAdjust()
void ns3::RngRsp::SetOffsetFreqAdjust (uint32_t offsetFreqAdjust)
set the relative change in transmission frequency that the SS should take in order to better match the BS.
This is fine-frequency adjustment within a channel, not reassignment to a different channel
Parameters
offsetFreqAdjust
Definition at line 270 of file mac-messages.cc.
References m_offsetFreqAdjust.
Referenced by ns3::BSLinkManager::SetParametersToAdjust().
SetPowerLevelAdjust()
void ns3::RngRsp::SetPowerLevelAdjust (uint8_t powerLevelAdjust)
set the relative change in transmission power level that the SS should make in order that transmissions arrive at the BS at the desired power.
When subchannelization is employed, the subscriber shall interpret the power offset adjustment as a required change to the transmitted power density.
Parameters
powerLevelAdjust the relative change in transmission power level
Definition at line 264 of file mac-messages.cc.
References m_powerLevelAdjust.
Referenced by ns3::BSLinkManager::SetParametersToAdjust().
SetPrimaryCid()
void ns3::RngRsp::SetPrimaryCid (Cid primaryCid)
set primary CID.
Parameters
primaryCid
Definition at line 312 of file mac-messages.cc.
References m_primaryCid.
Referenced by ns3::ConnectionManager::AllocateManagementConnections().
SetRangStatus()
void ns3::RngRsp::SetRangStatus (uint8_t rangStatus)
set the range status.
Parameters
rangStatus
Definition at line 276 of file mac-messages.cc.
References m_rangStatus.
Referenced by ns3::BSLinkManager::AbortRanging(), ns3::BSLinkManager::AcceptRanging(), ns3::BSLinkManager::ContinueRanging(), and ns3::BSLinkManager::PerformRanging().
SetRangSubchnl()
void ns3::RngRsp::SetRangSubchnl (uint8_t rangSubchnl)
set range sub channel.
Parameters
rangSubchnl
Definition at line 336 of file mac-messages.cc.
References m_rangSubchnl.
SetTimingAdjust()
void ns3::RngRsp::SetTimingAdjust (uint32_t timingAdjust)
set the Tx timing offset adjustment (signed 32-bit).
Parameters
timingAdjust The time required to advance SS transmission so frames arrive at the expected time instance at the BS.
Definition at line 258 of file mac-messages.cc.
References m_timingAdjust.
Referenced by ns3::BSLinkManager::SetParametersToAdjust().
SetUlChnlIdOverride()
void ns3::RngRsp::SetUlChnlIdOverride (uint8_t ulChnlIdOverride)
set the identifier of the uplink channel with which the SS is to redo initial ranging
Parameters
ulChnlIdOverride the uplink channel index
Definition at line 288 of file mac-messages.cc.
References m_ulChnlIdOverride.
Member Data Documentation
m_aasBdcastPermission
uint8_t ns3::RngRsp::m_aasBdcastPermission private
AAS broadcast permission.
Definition at line 328 of file mac-messages.h.
Referenced by Deserialize(), GetAasBdcastPermission(), Print(), Serialize(), and SetAasBdcastPermission().
m_basicCid
Cid ns3::RngRsp::m_basicCid private
basic CID
Definition at line 326 of file mac-messages.h.
Referenced by Deserialize(), GetBasicCid(), Print(), Serialize(), and SetBasicCid().
m_dlFreqOverride
uint32_t ns3::RngRsp::m_dlFreqOverride private
Center frequency, in kHz, of new downlink channel where the SS should redo initial ranging.
Definition at line 310 of file mac-messages.h.
Referenced by Deserialize(), GetDlFreqOverride(), Print(), Serialize(), and SetDlFreqOverride().
m_dlOperBurstProfile
uint16_t ns3::RngRsp::m_dlOperBurstProfile private
This parameter is sent in response to the RNG-REQ Requested Downlink Burst Profile parameter.
Byte 0: Specifies the least robust DIUC that may be used by the BS for transmissions to the SS. Byte 1: Configuration Change Count value of DCD defining the burst profile associated with DIUC.
Definition at line 323 of file mac-messages.h.
Referenced by Deserialize(), GetDlOperBurstProfile(), Print(), Serialize(), and SetDlOperBurstProfile().
m_frameNumber
uint32_t ns3::RngRsp::m_frameNumber private
Frame number where the associated RNG_REQ message was detected by the BS.
Usage is mutually exclusive with SS MAC Address
Definition at line 334 of file mac-messages.h.
Referenced by Deserialize(), GetFrameNumber(), Print(), Serialize(), and SetFrameNumber().
m_initRangOppNumber
uint8_t ns3::RngRsp::m_initRangOppNumber private
Initial Ranging opportunity (1–255) in which the associated RNG_REQ message was detected by the BS.
Usage is mutually exclusive with SS MAC Address
Definition at line 340 of file mac-messages.h.
Referenced by Deserialize(), GetInitRangOppNumber(), Print(), Serialize(), and SetInitRangOppNumber().
m_macAddress
Mac48Address ns3::RngRsp::m_macAddress private
MAC address.
Definition at line 325 of file mac-messages.h.
Referenced by Deserialize(), GetMacAddress(), Print(), Serialize(), and SetMacAddress().
m_offsetFreqAdjust
uint32_t ns3::RngRsp::m_offsetFreqAdjust private
Specifies the relative change in transmission frequency that the SS is to make in order to better match the BS.
This is fine-frequency adjustment within a channel, not reassignment to a different channel.
Definition at line 302 of file mac-messages.h.
Referenced by Deserialize(), GetOffsetFreqAdjust(), Print(), Serialize(), and SetOffsetFreqAdjust().
m_powerLevelAdjust
uint8_t ns3::RngRsp::m_powerLevelAdjust private
Specifies the relative change in transmission power level that the SS is to make in order that transmissions arrive at the BS at the desired power.
When subchannelization is employed, the subscriber shall interpret the power offset adjustment as a required change to the transmitted power density.
Definition at line 296 of file mac-messages.h.
Referenced by Deserialize(), GetPowerLevelAdjust(), Print(), Serialize(), and SetPowerLevelAdjust().
m_primaryCid
Cid ns3::RngRsp::m_primaryCid private
primary CID
Definition at line 327 of file mac-messages.h.
Referenced by Deserialize(), GetPrimaryCid(), Print(), Serialize(), and SetPrimaryCid().
m_rangStatus
uint8_t ns3::RngRsp::m_rangStatus private
range status.
Definition at line 307 of file mac-messages.h.
Referenced by Deserialize(), GetRangStatus(), Print(), Serialize(), and SetRangStatus().
m_rangSubchnl
uint8_t ns3::RngRsp::m_rangSubchnl private
Used to indicate the OFDM subchannel reference that was used to transmit the initial ranging message (OFDM with subchannelization).
Definition at line 346 of file mac-messages.h.
Referenced by Deserialize(), GetRangSubchnl(), Print(), Serialize(), and SetRangSubchnl().
m_reserved
uint8_t ns3::RngRsp::m_reserved private
changed as per the amendment 802.16e-2005
Definition at line 280 of file mac-messages.h.
Referenced by Deserialize(), and Serialize().
m_timingAdjust
uint32_t ns3::RngRsp::m_timingAdjust private
Tx timing offset adjustment (signed 32-bit).
The time required to advance SS transmission so frames arrive at the expected time instance at the BS.
Definition at line 288 of file mac-messages.h.
Referenced by Deserialize(), GetTimingAdjust(), Print(), Serialize(), and SetTimingAdjust().
m_ulChnlIdOverride
uint8_t ns3::RngRsp::m_ulChnlIdOverride private
Licensed bands: The identifier of the uplink channel with which the SS is to redo initial ranging (not used with PHYs without channelized uplinks).
Definition at line 316 of file mac-messages.h.
Referenced by Deserialize(), GetUlChnlIdOverride(), Print(), Serialize(), and SetUlChnlIdOverride().
The documentation for this class was generated from the following files:
src/wimax/model/mac-messages.h
src/wimax/model/mac-messages.cc