ns-3: ns3::BeaconPayloadHeader Class Reference
ns3::BeaconPayloadHeader Class Reference
LR-WPAN models
#include "lr-wpan-mac-pl-headers.h"
Public Member Functions
BeaconPayloadHeader ()
uint32_t Deserialize (Buffer::Iterator start)
GtsFields GetGtsFields (void) const
Get the Guaranteed Time Slots (GTS) fields from the beacon payload header.
TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
PendingAddrFields GetPndAddrFields (void) const
uint32_t GetSerializedSize (void) const
SuperframeField GetSuperframeSpecField (void) const
Get the superframe specification field from the beacon payload header.
void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetGtsFields (GtsFields gtsFields)
Set the superframe Guaranteed Time Slot (GTS) fields to the beacon payload header.
void SetPndAddrFields (PendingAddrFields pndAddrFields)
Set the superframe Pending Address fields to the beacon payload header.
void SetSuperframeSpecField (SuperframeField sfrmField)
Set the superframe specification field to the beacon payload header.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
GtsFields m_gtsFields
GTS Fields.
PendingAddrFields m_pndAddrFields
Pending Address Fields.
SuperframeField m_superframeField
Superframe Specification Field.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implements the header for the MAC payload beacon frame according to the IEEE 802.15.4-2011 Std.
Definition at line 39 of file lr-wpan-mac-pl-headers.h.
Constructor & Destructor Documentation
BeaconPayloadHeader()
ns3::BeaconPayloadHeader::BeaconPayloadHeader ()
Definition at line 30 of file lr-wpan-mac-pl-headers.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::BeaconPayloadHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 74 of file lr-wpan-mac-pl-headers.cc.
References ns3::SuperframeField::Deserialize(), ns3::GtsFields::Deserialize(), ns3::PendingAddrFields::Deserialize(), ns3::Buffer::Iterator::GetDistanceFrom(), m_gtsFields, m_pndAddrFields, m_superframeField, and visualizer.core::start().
GetGtsFields()
GtsFields ns3::BeaconPayloadHeader::GetGtsFields (void) const
Get the Guaranteed Time Slots (GTS) fields from the beacon payload header.
Returns
The GTS fields.
Definition at line 119 of file lr-wpan-mac-pl-headers.cc.
References m_gtsFields.
GetInstanceTypeId()
TypeId ns3::BeaconPayloadHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 48 of file lr-wpan-mac-pl-headers.cc.
References GetTypeId().
GetPndAddrFields()
PendingAddrFields ns3::BeaconPayloadHeader::GetPndAddrFields (void) const
Definition at line 125 of file lr-wpan-mac-pl-headers.cc.
References m_pndAddrFields.
Referenced by ns3::LrWpanMac::PdDataIndication().
GetSerializedSize()
uint32_t ns3::BeaconPayloadHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 54 of file lr-wpan-mac-pl-headers.cc.
References ns3::SuperframeField::GetSerializedSize(), ns3::GtsFields::GetSerializedSize(), ns3::PendingAddrFields::GetSerializedSize(), m_gtsFields, m_pndAddrFields, and m_superframeField.
GetSuperframeSpecField()
SuperframeField ns3::BeaconPayloadHeader::GetSuperframeSpecField (void) const
Get the superframe specification field from the beacon payload header.
Returns
The superframe specification field
Definition at line 113 of file lr-wpan-mac-pl-headers.cc.
References m_superframeField.
Referenced by ns3::LrWpanMac::PdDataIndication().
GetTypeId()
TypeId ns3::BeaconPayloadHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 37 of file lr-wpan-mac-pl-headers.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::BeaconPayloadHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 86 of file lr-wpan-mac-pl-headers.cc.
References ns3::GtsFields::GetGtsSpecField(), ns3::PendingAddrFields::GetPndAddrSpecField(), m_gtsFields, m_pndAddrFields, and m_superframeField.
Serialize()
void ns3::BeaconPayloadHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 65 of file lr-wpan-mac-pl-headers.cc.
References m_gtsFields, m_pndAddrFields, m_superframeField, ns3::SuperframeField::Serialize(), ns3::GtsFields::Serialize(), ns3::PendingAddrFields::Serialize(), and visualizer.core::start().
SetGtsFields()
void ns3::BeaconPayloadHeader::SetGtsFields (GtsFields gtsFields)
Set the superframe Guaranteed Time Slot (GTS) fields to the beacon payload header.
Parameters
gtsFields The GTS fields.
Definition at line 101 of file lr-wpan-mac-pl-headers.cc.
References m_gtsFields.
Referenced by ns3::LrWpanMac::SendOneBeacon().
SetPndAddrFields()
void ns3::BeaconPayloadHeader::SetPndAddrFields (PendingAddrFields pndAddrFields)
Set the superframe Pending Address fields to the beacon payload header.
Parameters
pndAddrFields The Pending Address fields.
Definition at line 107 of file lr-wpan-mac-pl-headers.cc.
References m_pndAddrFields.
Referenced by ns3::LrWpanMac::SendOneBeacon().
SetSuperframeSpecField()
void ns3::BeaconPayloadHeader::SetSuperframeSpecField (SuperframeField sfrmField)
Set the superframe specification field to the beacon payload header.
Parameters
sfrmField The superframe specification field
Definition at line 95 of file lr-wpan-mac-pl-headers.cc.
References m_superframeField.
Referenced by ns3::LrWpanMac::SendOneBeacon().
Member Data Documentation
m_gtsFields
GtsFields ns3::BeaconPayloadHeader::m_gtsFields private
GTS Fields.
Definition at line 93 of file lr-wpan-mac-pl-headers.h.
Referenced by Deserialize(), GetGtsFields(), GetSerializedSize(), Print(), Serialize(), and SetGtsFields().
m_pndAddrFields
PendingAddrFields ns3::BeaconPayloadHeader::m_pndAddrFields private
Pending Address Fields.
Definition at line 97 of file lr-wpan-mac-pl-headers.h.
Referenced by Deserialize(), GetPndAddrFields(), GetSerializedSize(), Print(), Serialize(), and SetPndAddrFields().
m_superframeField
SuperframeField ns3::BeaconPayloadHeader::m_superframeField private
Superframe Specification Field.
Definition at line 89 of file lr-wpan-mac-pl-headers.h.
Referenced by Deserialize(), GetSerializedSize(), GetSuperframeSpecField(), Print(), Serialize(), and SetSuperframeSpecField().
The documentation for this class was generated from the following files:
src/lr-wpan/model/lr-wpan-mac-pl-headers.h
src/lr-wpan/model/lr-wpan-mac-pl-headers.cc