ns-3: ns3::MobilityModel Class Reference
ns3::MobilityModel Class Reference abstract
Mobility
Keep track of the current position and velocity of an object.
#include "mobility-model.h"
Public Types
typedef void(* TracedCallback) (Ptr< const MobilityModel > model)
TracedCallback signature.
Public Member Functions
MobilityModel ()
virtual ~MobilityModel ()=0
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
double GetDistanceFrom (Ptr< const MobilityModel > position) const
Vector GetPosition (void) const
double GetRelativeSpeed (Ptr< const MobilityModel > other) const
Vector GetVelocity (void) const
void SetPosition (const Vector &position)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type with the TypeId system.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
void NotifyCourseChange (void) const
Must be invoked by subclasses when the course of the position changes to notify course change listeners.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
virtual int64_t DoAssignStreams (int64_t start)
The default implementation does nothing but return the passed-in parameter.
virtual Vector DoGetPosition (void) const =0
virtual Vector DoGetVelocity (void) const =0
virtual void DoSetPosition (const Vector &position)=0
Private Attributes
ns3::TracedCallback< Ptr< const MobilityModel > > m_courseChangeTrace
Used to alert subscribers that a change in direction, velocity, or position has occurred.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Keep track of the current position and velocity of an object.
All space coordinates in this class and its subclasses are understood to be meters or meters/s. i.e., they are all metric international units.
This is a base class for all specific mobility models.
Definition at line 39 of file mobility-model.h.
Member Typedef Documentation
TracedCallback
typedef void(* ns3::MobilityModel::TracedCallback) (Ptr< const MobilityModel > model)
TracedCallback signature.
Parameters
[in] model Value of the MobilityModel.
Definition at line 87 of file mobility-model.h.
Constructor & Destructor Documentation
MobilityModel()
ns3::MobilityModel::MobilityModel ()
Definition at line 55 of file mobility-model.cc.
~MobilityModel()
ns3::MobilityModel::~MobilityModel () pure virtual
Definition at line 59 of file mobility-model.cc.
Member Function Documentation
AssignStreams()
int64_t ns3::MobilityModel::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 101 of file mobility-model.cc.
References DoAssignStreams(), and visualizer.core::start().
Referenced by SteadyStateRandomWaypointTest::DoRun().
DoAssignStreams()
int64_t ns3::MobilityModel::DoAssignStreams (int64_t start) private virtual
The default implementation does nothing but return the passed-in parameter.
Subclasses using random variables are expected to override this.
Parameters
start starting stream index
Returns
the number of streams used
Reimplemented in ns3::SteadyStateRandomWaypointMobilityModel, ns3::RandomWaypointMobilityModel, ns3::RandomWalk2dMobilityModel, ns3::RandomDirection2dMobilityModel, and ns3::GaussMarkovMobilityModel.
Definition at line 108 of file mobility-model.cc.
Referenced by AssignStreams().
DoGetPosition()
virtual Vector ns3::MobilityModel::DoGetPosition (void) const private pure virtual
Returns
the current position.
Concrete subclasses of this base class must implement this method.
Implemented in ns3::WaypointMobilityModel, ns3::SteadyStateRandomWaypointMobilityModel, ns3::RandomWaypointMobilityModel, ns3::RandomWalk2dMobilityModel, ns3::RandomDirection2dMobilityModel, ns3::HierarchicalMobilityModel, ns3::GaussMarkovMobilityModel, ns3::ConstantVelocityMobilityModel, ns3::ConstantPositionMobilityModel, and ns3::ConstantAccelerationMobilityModel.
Referenced by GetDistanceFrom(), and GetPosition().
DoGetVelocity()
virtual Vector ns3::MobilityModel::DoGetVelocity (void) const private pure virtual
Returns
the current velocity.
Concrete subclasses of this base class must implement this method.
Implemented in ns3::WaypointMobilityModel, ns3::SteadyStateRandomWaypointMobilityModel, ns3::RandomWaypointMobilityModel, ns3::RandomWalk2dMobilityModel, ns3::RandomDirection2dMobilityModel, ns3::HierarchicalMobilityModel, ns3::GaussMarkovMobilityModel, ns3::ConstantVelocityMobilityModel, ns3::ConstantPositionMobilityModel, and ns3::ConstantAccelerationMobilityModel.
Referenced by GetVelocity().
DoSetPosition()
virtual void ns3::MobilityModel::DoSetPosition (const Vector & position) private pure virtual
Parameters
position the position to set.
Concrete subclasses of this base class must implement this method.
Implemented in ns3::WaypointMobilityModel, ns3::SteadyStateRandomWaypointMobilityModel, ns3::RandomWaypointMobilityModel, ns3::RandomWalk2dMobilityModel, ns3::RandomDirection2dMobilityModel, ns3::HierarchicalMobilityModel, ns3::GaussMarkovMobilityModel, ns3::ConstantVelocityMobilityModel, ns3::ConstantPositionMobilityModel, and ns3::ConstantAccelerationMobilityModel.
Referenced by SetPosition().
GetDistanceFrom()
double ns3::MobilityModel::GetDistanceFrom (Ptr< const MobilityModel > position) const
Parameters
position a reference to another mobility model
Returns
the distance between the two objects. Unit is meters.
Definition at line 81 of file mobility-model.cc.
References ns3::CalculateDistance(), and DoGetPosition().
Referenced by ns3::FriisPropagationLossModel::DoCalcRxPower(), ns3::TwoRayGroundPropagationLossModel::DoCalcRxPower(), ns3::LogDistancePropagationLossModel::DoCalcRxPower(), ns3::ThreeLogDistancePropagationLossModel::DoCalcRxPower(), ns3::NakagamiPropagationLossModel::DoCalcRxPower(), ns3::RangePropagationLossModel::DoCalcRxPower(), ns3::ConstantSpeedPropagationDelayModel::GetDelay(), ns3::UanPropModelIdeal::GetDelay(), ns3::UanPropModelThorp::GetDelay(), ns3::HybridBuildingsPropagationLossModel::GetLoss(), ns3::ItuR1238PropagationLossModel::GetLoss(), ns3::Cost231PropagationLossModel::GetLoss(), ns3::ItuR1411LosPropagationLossModel::GetLoss(), ns3::ItuR1411NlosOverRooftopPropagationLossModel::GetLoss(), ns3::Kun2600MhzPropagationLossModel::GetLoss(), ns3::OkumuraHataPropagationLossModel::GetLoss(), ns3::UanPropModelThorp::GetPathLossDb(), ns3::HybridBuildingsPropagationLossModel::ItuR1411(), ns3::lorawan::LoraChannel::Send(), ns3::YansWifiChannel::Send(), ns3::SimpleOfdmWimaxChannel::Send(), and ns3::UanChannel::TxPacket().
GetPosition()
Vector ns3::MobilityModel::GetPosition (void) const
Returns
the current position
Definition at line 64 of file mobility-model.cc.
References DoGetPosition().
Referenced by Ns2MobilityHelperTest::CheckInitialPositions(), CourseChange(), CourseChangeCallback(), SteadyStateRandomWaypointTest::DistribCompare(), ns3::lorawan::CorrelatedShadowingPropagationLossModel::DoCalcRxPower(), ns3::TwoRayGroundPropagationLossModel::DoCalcRxPower(), ns3::ThreeGppPropagationLossModel::DoCalcRxPower(), ns3::HierarchicalMobilityModel::DoGetPosition(), ns3::lorawan::LoraHelper::DoPrintDeviceStatus(), RandomRoomPositionAllocatorTestCase::DoRun(), ns3::HierarchicalMobilityModel::DoSetPosition(), ns3::HybridBuildingsPropagationLossModel::GetLoss(), ns3::ItuR1238PropagationLossModel::GetLoss(), ns3::ItuR1411LosPropagationLossModel::GetLoss(), ns3::ItuR1411NlosOverRooftopPropagationLossModel::GetLoss(), ns3::OkumuraHataPropagationLossModel::GetLoss(), ns3::ThreeGppRmaPropagationLossModel::GetShadowingStd(), GetTypeId(), ns3::ThreeGppPropagationLossModel::GetVectorDifference(), ns3::lorawan::LoraHelper::Install(), ns3::MobilityBuildingInfo::IsIndoor(), ns3::BuildingsHelper::MakeConsistent(), ns3::MobilityBuildingInfo::MakeConsistent(), OcbWifiMacTestCase::PostDeviceConfiguration(), NetAnimExperiment::Run(), Experiment::Run(), ns3::lorawan::LoraChannel::Send(), ns3::HierarchicalMobilityModel::SetChild(), ns3::SetInitialPosition(), ns3::HierarchicalMobilityModel::SetParent(), ns3::SetSchedPosition(), showPosition(), ns3::MultiModelSpectrumChannel::StartTx(), ns3::SingleModelSpectrumChannel::StartTx(), LteX2HandoverTestCase::TeleportUeNearTargetEnb(), WaypointLazyNotifyFalse::TestXPosition(), WaypointLazyNotifyTrue::TestXPosition(), WaypointMobilityModelViaHelper::TestXPosition(), WaypointInitialPositionIsWaypoint::TestXPosition(), and ns3::AnimationInterface::UpdatePosition().
GetRelativeSpeed()
double ns3::MobilityModel::GetRelativeSpeed (Ptr< const MobilityModel > other) const
Parameters
other reference to another object's mobility model
Returns
the relative speed between the two objects. Unit is meters/s.
Definition at line 89 of file mobility-model.cc.
References GetVelocity().
GetTypeId()
TypeId ns3::MobilityModel::GetTypeId (void) static
Register this type with the TypeId system.
Returns
the object TypeId
Definition at line 31 of file mobility-model.cc.
References ns3::TypeId::ATTR_GET, ns3::TypeId::ATTR_SET, GetPosition(), GetVelocity(), m_courseChangeTrace, ns3::MakeTraceSourceAccessor(), ns3::MakeVectorAccessor(), ns3::MakeVectorChecker(), ns3::TypeId::SetParent(), and SetPosition().
GetVelocity()
Vector ns3::MobilityModel::GetVelocity (void) const
Returns
the current velocity.
Definition at line 69 of file mobility-model.cc.
References DoGetVelocity().
Referenced by Ns2MobilityHelperTest::CheckInitialPositions(), SteadyStateRandomWaypointTest::DistribCompare(), ns3::HierarchicalMobilityModel::DoGetVelocity(), GetRelativeSpeed(), GetTypeId(), and showPosition().
NotifyCourseChange()
void ns3::MobilityModel::NotifyCourseChange (void) const protected
Must be invoked by subclasses when the course of the position changes to notify course change listeners.
Definition at line 95 of file mobility-model.cc.
References m_courseChangeTrace.
Referenced by ns3::RandomDirection2dMobilityModel::BeginPause(), ns3::RandomWaypointMobilityModel::BeginWalk(), ns3::SteadyStateRandomWaypointMobilityModel::BeginWalk(), ns3::HierarchicalMobilityModel::ChildChanged(), ns3::RandomWaypointMobilityModel::DoInitializePrivate(), ns3::SteadyStateRandomWaypointMobilityModel::DoInitializePrivate(), ns3::ConstantAccelerationMobilityModel::DoSetPosition(), ns3::ConstantPositionMobilityModel::DoSetPosition(), ns3::ConstantVelocityMobilityModel::DoSetPosition(), ns3::WaypointMobilityModel::DoSetPosition(), ns3::GaussMarkovMobilityModel::DoWalk(), ns3::RandomWalk2dMobilityModel::DoWalk(), ns3::HierarchicalMobilityModel::ParentChanged(), ns3::RandomDirection2dMobilityModel::SetDirectionAndSpeed(), ns3::ConstantVelocityMobilityModel::SetVelocity(), ns3::ConstantAccelerationMobilityModel::SetVelocityAndAcceleration(), ns3::SteadyStateRandomWaypointMobilityModel::Start(), ns3::SteadyStateRandomWaypointMobilityModel::SteadyStateBeginWalk(), and ns3::WaypointMobilityModel::Update().
SetPosition()
void ns3::MobilityModel::SetPosition (const Vector & position)
Parameters
position the position to set.
Definition at line 75 of file mobility-model.cc.
References DoSetPosition().
Referenced by JakesPropagationExample::JakesPropagationExample(), BuildingsPathlossTestCase::CreateMobilityModel(), BuildingsShadowingTestCase::CreateMobilityModel(), TestCaseHelper::CreatWaveDevice(), ns3::aodv::LoopbackTestCase::DoRun(), BuildingsChannelConditionModelTestCase::DoRun(), BuildingsHelperOneTestCase::DoRun(), LrWpanAckTestCase::DoRun(), LrWpanCcaTestCase::DoRun(), LrWpanCollisionTestCase::DoRun(), LrWpanEdTestCase::DoRun(), LrWpanErrorDistanceTestCase::DoRun(), LrWpanDataIfsTestCase::DoRun(), LrWpanSlottedCsmacaTestCase::DoRun(), CarrierAggregationTestCase::DoRun(), LenaCqaFfMacSchedulerTestCase1::DoRun(), LenaCqaFfMacSchedulerTestCase2::DoRun(), LenaFdBetFfMacSchedulerTestCase1::DoRun(), LenaFdBetFfMacSchedulerTestCase2::DoRun(), LenaFdMtFfMacSchedulerTestCase::DoRun(), LenaFdTbfqFfMacSchedulerTestCase1::DoRun(), LenaFdTbfqFfMacSchedulerTestCase2::DoRun(), LenaHarqTestCase::DoRun(), LenaMimoTestCase::DoRun(), LtePathlossModelSystemTestCase::DoRun(), LenaPfFfMacSchedulerTestCase1::DoRun(), LenaPfFfMacSchedulerTestCase2::DoRun(), LenaDataPhyErrorModelTestCase::DoRun(), LenaDlCtrlPhyErrorModelTestCase::DoRun(), LenaPssFfMacSchedulerTestCase1::DoRun(), LenaPssFfMacSchedulerTestCase2::DoRun(), LenaRrFfMacSchedulerTestCase::DoRun(), LenaTdBetFfMacSchedulerTestCase1::DoRun(), LenaTdBetFfMacSchedulerTestCase2::DoRun(), LenaTdMtFfMacSchedulerTestCase::DoRun(), LenaTdTbfqFfMacSchedulerTestCase1::DoRun(), LenaTdTbfqFfMacSchedulerTestCase2::DoRun(), LenaTtaFfMacSchedulerTestCase::DoRun(), WaypointInitialPositionIsWaypoint::DoRun(), ThreeGppChannelConditionModelTestCase::DoRun(), ItuR1411LosPropagationLossModelTestCase::DoRun(), ItuR1411NlosOverRooftopPropagationLossModelTestCase::DoRun(), Kun2600MhzPropagationLossModelTestCase::DoRun(), OkumuraHataPropagationLossModelTestCase::DoRun(), FriisPropagationLossModelTestCase::DoRun(), TwoRayGroundPropagationLossModelTestCase::DoRun(), LogDistancePropagationLossModelTestCase::DoRun(), RangePropagationLossModelTestCase::DoRun(), ThreeGppRmaPropagationLossModelTestCase::DoRun(), ThreeGppUmaPropagationLossModelTestCase::DoRun(), ThreeGppUmiPropagationLossModelTestCase::DoRun(), ThreeGppIndoorOfficePropagationLossModelTestCase::DoRun(), ThreeGppChannelMatrixComputationTest::DoRun(), ThreeGppChannelMatrixUpdateTest::DoRun(), ThreeGppSpectrumPropagationLossModelTest::DoRun(), AcousticModemEnergyTestCase::DoRun(), DcfImmediateAccessBroadcastTestCase::DoRun(), Bug2831TestCase::DoRun(), ns3::HierarchicalMobilityModel::DoSetPosition(), GetTypeId(), ns3::MobilityHelper::Install(), LteRrcConnectionEstablishmentErrorTestCase::JumpAway(), LteRadioLinkFailureTestCase::JumpAway(), LteRrcConnectionEstablishmentErrorTestCase::JumpBack(), OcbWifiMacTestCase::PostDeviceConfiguration(), PhyConnectivityTest::Reset(), HwmpReactiveRegressionTest::ResetPosition(), HwmpSimplestRegressionTest::ResetPosition(), InterferenceExperiment::Run(), ThreeGppShadowingTestCase::RunTest(), ns3::HierarchicalMobilityModel::SetChild(), ns3::SetInitialPosition(), ns3::HierarchicalMobilityModel::SetParent(), ns3::LteHexGridEnbTopologyHelper::SetPositionAndInstallEnbDevice(), ns3::SetSchedPosition(), LteFrAreaTestCase::SimpleTeleportUe(), LteUeMeasurementsPiecewiseTestCase1::TeleportFar(), LteUeMeasurementsPiecewiseTestCase2::TeleportFar(), LteUeMeasurementsPiecewiseTestCase1::TeleportNear(), LteUeMeasurementsPiecewiseTestCase2::TeleportNear(), LteFrAreaTestCase::TeleportUe(), LteUplinkPowerControlTestCase::TeleportUe(), LteFrAreaTestCase::TeleportUe2(), LteX2HandoverTestCase::TeleportUeNearTargetEnb(), LteX2HandoverTestCase::TeleportUeToMiddle(), LteUeMeasurementsPiecewiseTestCase1::TeleportVeryFar(), LteUeMeasurementsPiecewiseTestCase2::TeleportVeryFar(), LteUeMeasurementsPiecewiseTestCase1::TeleportVeryNear(), LteUeMeasurementsPiecewiseTestCase2::TeleportVeryNear(), TestDeterministic(), TestDeterministicByTime(), TestProbabilistic(), NetAnimExperiment::UpdatePositions(), and Experiment::UpdatePositions().
Member Data Documentation
m_courseChangeTrace
ns3::TracedCallback<Ptr<const MobilityModel> > ns3::MobilityModel::m_courseChangeTrace private
Used to alert subscribers that a change in direction, velocity, or position has occurred.
Definition at line 130 of file mobility-model.h.
Referenced by GetTypeId(), and NotifyCourseChange().
The documentation for this class was generated from the following files:
src/mobility/model/mobility-model.h
src/mobility/model/mobility-model.cc