ns-3: ns3::OfdmUlMapIe Class Reference
ns3::OfdmUlMapIe Class Reference
This class implements the UL-MAP_IE message as described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems" 6.3.2.3.43.7 UL-MAP_IE, page 115.
#include "ul-mac-messages.h"
Public Member Functions
OfdmUlMapIe (void)
~OfdmUlMapIe (void)
Cid GetCid (void) const
Get CID.
uint16_t GetDuration (void) const
Get duration.
uint8_t GetMidambleRepetitionInterval (void) const
Get Midamble repetition interval.
uint16_t GetSize (void) const
Get size.
uint16_t GetStartTime (void) const
Get start time.
uint8_t GetSubchannelIndex (void) const
Get subchannel index.
uint8_t GetUiuc (void) const
Get UIUC.
Buffer::Iterator Read (Buffer::Iterator start)
Read item.
void SetCid (const Cid &cid)
Set CID.
void SetDuration (uint16_t duration)
Set duration.
void SetMidambleRepetitionInterval (uint8_t midambleRepetitionInterval)
Set midambe repetition interval.
void SetStartTime (uint16_t startTime)
Set start time.
void SetSubchannelIndex (uint8_t subchannelIndex)
Set subchannel index.
void SetUiuc (uint8_t uiuc)
Set UIUC.
Buffer::Iterator Write (Buffer::Iterator start) const
Write item.
Private Attributes
Cid m_cid
CID.
uint16_t m_duration
duration
uint8_t m_midambleRepetitionInterval
midamble repetition interval
uint16_t m_startTime
start time
uint8_t m_subchannelIndex
subchannel index
uint8_t m_uiuc
UIUC.
Detailed Description
This class implements the UL-MAP_IE message as described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems" 6.3.2.3.43.7 UL-MAP_IE, page 115.
Definition at line 452 of file ul-mac-messages.h.
Constructor & Destructor Documentation
OfdmUlMapIe()
ns3::OfdmUlMapIe::OfdmUlMapIe (void)
Definition at line 460 of file ul-mac-messages.cc.
~OfdmUlMapIe()
ns3::OfdmUlMapIe::~OfdmUlMapIe (void)
Definition at line 470 of file ul-mac-messages.cc.
Member Function Documentation
GetCid()
Cid ns3::OfdmUlMapIe::GetCid (void) const
Get CID.
Returns
the CID
Definition at line 512 of file ul-mac-messages.cc.
References m_cid.
Referenced by ns3::BaseStationNetDevice::MarkUplinkAllocations(), and ns3::SubscriberStationNetDevice::ProcessUlMap().
GetDuration()
uint16_t ns3::OfdmUlMapIe::GetDuration (void) const
Get duration.
Returns
the duration
Definition at line 536 of file ul-mac-messages.cc.
References m_duration.
Referenced by ns3::BaseStationNetDevice::MarkUplinkAllocations(), and ns3::SubscriberStationNetDevice::ProcessUlMap().
GetMidambleRepetitionInterval()
uint8_t ns3::OfdmUlMapIe::GetMidambleRepetitionInterval (void) const
Get Midamble repetition interval.
Returns
the midamble repetition interval
Definition at line 542 of file ul-mac-messages.cc.
References m_midambleRepetitionInterval.
GetSize()
uint16_t ns3::OfdmUlMapIe::GetSize (void) const
Get size.
Returns
the size
Definition at line 548 of file ul-mac-messages.cc.
Referenced by ns3::UlMap::GetSerializedSize().
GetStartTime()
uint16_t ns3::OfdmUlMapIe::GetStartTime (void) const
Get start time.
Returns
the start time
Definition at line 518 of file ul-mac-messages.cc.
References m_startTime.
Referenced by ns3::BaseStationNetDevice::MarkUplinkAllocations(), and ns3::SubscriberStationNetDevice::ProcessUlMap().
GetSubchannelIndex()
uint8_t ns3::OfdmUlMapIe::GetSubchannelIndex (void) const
Get subchannel index.
Returns
the subchannel index
Definition at line 524 of file ul-mac-messages.cc.
References m_subchannelIndex.
GetUiuc()
uint8_t ns3::OfdmUlMapIe::GetUiuc (void) const
Get UIUC.
Returns
the UIUC
Definition at line 530 of file ul-mac-messages.cc.
References m_uiuc.
Referenced by ns3::UlMap::Deserialize(), ns3::BaseStationNetDevice::MarkUplinkAllocations(), ns3::SubscriberStationNetDevice::ProcessUlMap(), ns3::UplinkSchedulerMBQoS::ServiceUnsolicitedGrants(), ns3::UplinkSchedulerRtps::ServiceUnsolicitedGrants(), and ns3::UplinkSchedulerSimple::ServiceUnsolicitedGrants().
Read()
Buffer::Iterator ns3::OfdmUlMapIe::Read (Buffer::Iterator start)
Read item.
Parameters
start the iterator
Returns
the updated iterator
Definition at line 567 of file ul-mac-messages.cc.
References m_cid, m_duration, m_midambleRepetitionInterval, m_startTime, m_subchannelIndex, m_uiuc, ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
Referenced by ns3::UlMap::Deserialize().
SetCid()
void ns3::OfdmUlMapIe::SetCid (const Cid & cid)
Set CID.
Parameters
cid the CID
Definition at line 475 of file ul-mac-messages.cc.
References m_cid.
Referenced by ns3::UplinkSchedulerMBQoS::AllocateInitialRangingInterval(), ns3::UplinkSchedulerRtps::AllocateInitialRangingInterval(), ns3::UplinkSchedulerSimple::AllocateInitialRangingInterval(), ns3::UplinkSchedulerMBQoS::Schedule(), ns3::UplinkSchedulerRtps::Schedule(), ns3::UplinkSchedulerSimple::Schedule(), and ns3::UplinkSchedulerRtps::ULSchedulerRTPSConnection().
SetDuration()
void ns3::OfdmUlMapIe::SetDuration (uint16_t duration)
Set duration.
Parameters
duration the duration
Definition at line 499 of file ul-mac-messages.cc.
References aloha::duration, and m_duration.
Referenced by ns3::UplinkSchedulerMBQoS::AddUplinkAllocation(), ns3::UplinkSchedulerRtps::AddUplinkAllocation(), ns3::UplinkSchedulerSimple::AddUplinkAllocation(), ns3::UplinkSchedulerMBQoS::Schedule(), ns3::UplinkSchedulerRtps::Schedule(), and ns3::UplinkSchedulerSimple::Schedule().
SetMidambleRepetitionInterval()
void ns3::OfdmUlMapIe::SetMidambleRepetitionInterval (uint8_t midambleRepetitionInterval)
Set midambe repetition interval.
Parameters
midambleRepetitionInterval the midambe repetition interval
Definition at line 505 of file ul-mac-messages.cc.
References m_midambleRepetitionInterval.
SetStartTime()
void ns3::OfdmUlMapIe::SetStartTime (uint16_t startTime)
Set start time.
Parameters
startTime the start time
Definition at line 481 of file ul-mac-messages.cc.
References m_startTime, and startTime.
Referenced by ns3::UplinkSchedulerMBQoS::AddUplinkAllocation(), ns3::UplinkSchedulerRtps::AddUplinkAllocation(), ns3::UplinkSchedulerSimple::AddUplinkAllocation(), ns3::UplinkSchedulerMBQoS::AllocateInitialRangingInterval(), ns3::UplinkSchedulerRtps::AllocateInitialRangingInterval(), ns3::UplinkSchedulerSimple::AllocateInitialRangingInterval(), ns3::UplinkSchedulerMBQoS::Schedule(), ns3::UplinkSchedulerRtps::Schedule(), ns3::UplinkSchedulerSimple::Schedule(), ns3::UplinkSchedulerMBQoS::ServiceUnsolicitedGrants(), ns3::UplinkSchedulerRtps::ServiceUnsolicitedGrants(), and ns3::UplinkSchedulerSimple::ServiceUnsolicitedGrants().
SetSubchannelIndex()
void ns3::OfdmUlMapIe::SetSubchannelIndex (uint8_t subchannelIndex)
Set subchannel index.
Parameters
subchannelIndex
Definition at line 487 of file ul-mac-messages.cc.
References m_subchannelIndex.
SetUiuc()
void ns3::OfdmUlMapIe::SetUiuc (uint8_t uiuc)
Set UIUC.
Parameters
uiuc the UIUC
Definition at line 493 of file ul-mac-messages.cc.
References m_uiuc.
Referenced by ns3::UplinkSchedulerMBQoS::AllocateInitialRangingInterval(), ns3::UplinkSchedulerRtps::AllocateInitialRangingInterval(), ns3::UplinkSchedulerSimple::AllocateInitialRangingInterval(), ns3::UplinkSchedulerMBQoS::Schedule(), ns3::UplinkSchedulerRtps::Schedule(), ns3::UplinkSchedulerSimple::Schedule(), ns3::UplinkSchedulerMBQoS::ServiceUnsolicitedGrants(), ns3::UplinkSchedulerRtps::ServiceUnsolicitedGrants(), ns3::UplinkSchedulerSimple::ServiceUnsolicitedGrants(), and ns3::UplinkSchedulerRtps::ULSchedulerRTPSConnection().
Write()
Buffer::Iterator ns3::OfdmUlMapIe::Write (Buffer::Iterator start) const
Write item.
Parameters
start the iterator
Returns
the updated iterator
Definition at line 554 of file ul-mac-messages.cc.
References ns3::Cid::GetIdentifier(), m_cid, m_duration, m_midambleRepetitionInterval, m_startTime, m_subchannelIndex, m_uiuc, visualizer.core::start(), ns3::Buffer::Iterator::WriteU16(), and ns3::Buffer::Iterator::WriteU8().
Referenced by ns3::UlMap::Serialize().
Member Data Documentation
m_cid
Cid ns3::OfdmUlMapIe::m_cid private
CID.
Definition at line 539 of file ul-mac-messages.h.
Referenced by GetCid(), Read(), SetCid(), and Write().
m_duration
uint16_t ns3::OfdmUlMapIe::m_duration private
duration
Definition at line 543 of file ul-mac-messages.h.
Referenced by GetDuration(), Read(), SetDuration(), and Write().
m_midambleRepetitionInterval
uint8_t ns3::OfdmUlMapIe::m_midambleRepetitionInterval private
midamble repetition interval
Definition at line 544 of file ul-mac-messages.h.
Referenced by GetMidambleRepetitionInterval(), Read(), SetMidambleRepetitionInterval(), and Write().
m_startTime
uint16_t ns3::OfdmUlMapIe::m_startTime private
start time
Definition at line 540 of file ul-mac-messages.h.
Referenced by GetStartTime(), Read(), SetStartTime(), and Write().
m_subchannelIndex
uint8_t ns3::OfdmUlMapIe::m_subchannelIndex private
subchannel index
Definition at line 541 of file ul-mac-messages.h.
Referenced by GetSubchannelIndex(), Read(), SetSubchannelIndex(), and Write().
m_uiuc
uint8_t ns3::OfdmUlMapIe::m_uiuc private
UIUC.
Definition at line 542 of file ul-mac-messages.h.
Referenced by GetUiuc(), Read(), SetUiuc(), and Write().
The documentation for this class was generated from the following files:
src/wimax/model/ul-mac-messages.h
src/wimax/model/ul-mac-messages.cc