ns-3: ns3::lorawan::SubBand Class Reference
ns3::lorawan::SubBand Class Reference
Class representing a SubBand, i.e., a frequency band subject to some regulations on duty cycle and transmission power.
#include "sub-band.h"
Public Member Functions
SubBand ()
SubBand (double firstFrequency, double lastFrequency, double dutyCycle, double maxTxPowerDbm)
Create a new SubBand by specifying all of its properties.
virtual ~SubBand ()
bool BelongsToSubBand (double frequency)
Return whether or not a frequency belongs to this SubBand.
bool BelongsToSubBand (Ptr< LogicalLoraChannel > channel)
Return whether or not a channel belongs to this SubBand.
double GetDutyCycle (void)
Get the last frequency of the subband.
double GetFirstFrequency (void)
Get the lowest frequency of the SubBand.
double GetMaxTxPowerDbm (void)
Return the maximum transmission power that is allowed on this SubBand.
Time GetNextTransmissionTime (void)
Returns the next time from which transmission on this subband will be possible.
void SetMaxTxPowerDbm (double maxTxPowerDbm)
Set the maximum transmission power that is allowed on this SubBand.
void SetNextTransmissionTime (Time nextTime)
Update the next transmission time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
double m_dutyCycle
The duty cycle that needs to be enforced on this subband.
double m_firstFrequency
Starting frequency of the subband, in MHz.
double m_lastFrequency
Ending frequency of the subband, in MHz.
double m_maxTxPowerDbm
The maximum transmission power that is admitted on this subband.
Time m_nextTransmissionTime
The next time a transmission will be allowed in this subband.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Class representing a SubBand, i.e., a frequency band subject to some regulations on duty cycle and transmission power.
Definition at line 37 of file sub-band.h.
Constructor & Destructor Documentation
SubBand() [1/2]
ns3::lorawan::SubBand::SubBand ()
Definition at line 40 of file sub-band.cc.
References NS_LOG_FUNCTION.
SubBand() [2/2]
ns3::lorawan::SubBand::SubBand (double firstFrequency, double lastFrequency, double dutyCycle, double maxTxPowerDbm)
Create a new SubBand by specifying all of its properties.
Parameters
firstFrequency The SubBand's lowest frequency.
lastFrequency The SubBand's highest frequency.
dutyCycle The duty cycle (as a fraction) allowed on this SubBand.
maxTxPowerDbm The maximum transmission power [dBm] allowed on this SubBand.
Definition at line 45 of file sub-band.cc.
References NS_LOG_FUNCTION.
~SubBand()
ns3::lorawan::SubBand::~SubBand () virtual
Definition at line 57 of file sub-band.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
BelongsToSubBand() [1/2]
bool ns3::lorawan::SubBand::BelongsToSubBand (double frequency)
Return whether or not a frequency belongs to this SubBand.
Parameters
frequency the frequency we want to test against the current subband
Returns
True if the frequency is between firstFrequency and lastFrequency, false otherwise.
Definition at line 75 of file sub-band.cc.
References m_firstFrequency, and m_lastFrequency.
Referenced by BelongsToSubBand(), and LogicalLoraChannelTest::DoRun().
BelongsToSubBand() [2/2]
bool ns3::lorawan::SubBand::BelongsToSubBand (Ptr< LogicalLoraChannel > channel)
Return whether or not a channel belongs to this SubBand.
Parameters
channel the channel we want to test against the current subband
Returns
True if the channel's center frequency is between firstFrequency and lastFrequency, false otherwise.
Definition at line 81 of file sub-band.cc.
References BelongsToSubBand().
GetDutyCycle()
double ns3::lorawan::SubBand::GetDutyCycle (void)
Get the last frequency of the subband.
Returns
The lowest frequency of the SubBand. Get the duty cycle of the subband.
The duty cycle (as a fraction) that needs to be enforced on this SubBand.
Definition at line 69 of file sub-band.cc.
References m_dutyCycle.
GetFirstFrequency()
double ns3::lorawan::SubBand::GetFirstFrequency (void)
Get the lowest frequency of the SubBand.
Returns
The lowest frequency of the SubBand.
Definition at line 63 of file sub-band.cc.
References m_firstFrequency.
GetMaxTxPowerDbm()
double ns3::lorawan::SubBand::GetMaxTxPowerDbm (void)
Return the maximum transmission power that is allowed on this SubBand.
Returns
The maximum transmission power, in dBm.
Definition at line 106 of file sub-band.cc.
References m_maxTxPowerDbm.
GetNextTransmissionTime()
Time ns3::lorawan::SubBand::GetNextTransmissionTime (void)
Returns the next time from which transmission on this subband will be possible.
Returns
The next time at which transmission in this SubBand will be allowed.
Definition at line 94 of file sub-band.cc.
References m_nextTransmissionTime.
GetTypeId()
TypeId ns3::lorawan::SubBand::GetTypeId (void) static
Definition at line 32 of file sub-band.cc.
References ns3::TypeId::SetParent().
SetMaxTxPowerDbm()
void ns3::lorawan::SubBand::SetMaxTxPowerDbm (double maxTxPowerDbm)
Set the maximum transmission power that is allowed on this SubBand.
Parameters
maxTxPowerDbm The maximum transmission power [dBm] to set.
Definition at line 100 of file sub-band.cc.
References m_maxTxPowerDbm.
SetNextTransmissionTime()
void ns3::lorawan::SubBand::SetNextTransmissionTime (Time nextTime)
Update the next transmission time.
This function is used by LogicalLoraChannelHelper, which computes the time based on the SubBand's duty cycle and on the transmission duration.
Parameters
nextTime The future time from which transmission should be allowed again.
Definition at line 88 of file sub-band.cc.
References m_nextTransmissionTime.
Member Data Documentation
m_dutyCycle
double ns3::lorawan::SubBand::m_dutyCycle private
The duty cycle that needs to be enforced on this subband.
Definition at line 133 of file sub-band.h.
Referenced by GetDutyCycle().
m_firstFrequency
double ns3::lorawan::SubBand::m_firstFrequency private
Starting frequency of the subband, in MHz.
Definition at line 131 of file sub-band.h.
Referenced by BelongsToSubBand(), and GetFirstFrequency().
m_lastFrequency
double ns3::lorawan::SubBand::m_lastFrequency private
Ending frequency of the subband, in MHz.
Definition at line 132 of file sub-band.h.
Referenced by BelongsToSubBand().
m_maxTxPowerDbm
double ns3::lorawan::SubBand::m_maxTxPowerDbm private
The maximum transmission power that is admitted on this subband.
Definition at line 135 of file sub-band.h.
Referenced by GetMaxTxPowerDbm(), and SetMaxTxPowerDbm().
m_nextTransmissionTime
Time ns3::lorawan::SubBand::m_nextTransmissionTime private
The next time a transmission will be allowed in this subband.
Definition at line 134 of file sub-band.h.
Referenced by GetNextTransmissionTime(), and SetNextTransmissionTime().
The documentation for this class was generated from the following files:
src/lorawan/model/sub-band.h
src/lorawan/model/sub-band.cc