ns-3: ns3::LteMacSapUser Class Reference
ns3::LteMacSapUser Class Reference abstract
Service Access Point (SAP) offered by the MAC to the RLC See Femto Forum MAC Scheduler Interface Specification v 1.11, Figure 1.
#include "lte-mac-sap.h"
Classes
struct ReceivePduParameters
Parameters for LteMacSapUser::ReceivePdu.
struct TxOpportunityParameters
Parameters for LteMacSapUser::NotifyTxOpportunity.
Public Member Functions
virtual ~LteMacSapUser ()
virtual void NotifyHarqDeliveryFailure ()=0
Called by the MAC to notify the RLC that an HARQ process related to this RLC instance has failed.
virtual void NotifyTxOpportunity (TxOpportunityParameters params)=0
Called by the MAC to notify the RLC that the scheduler granted a transmission opportunity to this RLC instance.
virtual void ReceivePdu (ReceivePduParameters params)=0
Called by the MAC to notify the RLC of the reception of a new PDU.
Detailed Description
Service Access Point (SAP) offered by the MAC to the RLC See Femto Forum MAC Scheduler Interface Specification v 1.11, Figure 1.
This is the MAC SAP User, i.e., the part of the SAP that contains the RLC methods called by the MAC
Definition at line 95 of file lte-mac-sap.h.
Constructor & Destructor Documentation
~LteMacSapUser()
ns3::LteMacSapUser::~LteMacSapUser () virtual
Definition at line 32 of file lte-mac-sap.cc.
Member Function Documentation
NotifyHarqDeliveryFailure()
virtual void ns3::LteMacSapUser::NotifyHarqDeliveryFailure () pure virtual
Called by the MAC to notify the RLC that an HARQ process related to this RLC instance has failed.
Todo:
eventual parameters to be defined
Implemented in ns3::SimpleUeCcmMacSapUser, ns3::LteRlcSpecificLteMacSapUser, and ns3::MemberLteCcmMacSapUser< C >.
NotifyTxOpportunity()
virtual void ns3::LteMacSapUser::NotifyTxOpportunity (TxOpportunityParameters params) pure virtual
Called by the MAC to notify the RLC that the scheduler granted a transmission opportunity to this RLC instance.
Parameters
params the TxOpportunityParameters
Implemented in ns3::SimpleUeCcmMacSapUser, ns3::MemberLteCcmMacSapUser< C >, and ns3::LteRlcSpecificLteMacSapUser.
Referenced by ns3::LteTestMac::DoReportBufferStatus(), and ns3::LteTestMac::SendTxOpportunity().
ReceivePdu()
virtual void ns3::LteMacSapUser::ReceivePdu (ReceivePduParameters params) pure virtual
Called by the MAC to notify the RLC of the reception of a new PDU.
Parameters
params the ReceivePduParameters
Implemented in ns3::SimpleUeCcmMacSapUser, ns3::MemberLteCcmMacSapUser< C >, and ns3::LteRlcSpecificLteMacSapUser.
Referenced by ns3::LteTestMac::DoTransmitPdu(), and ns3::LteTestMac::Receive().
The documentation for this class was generated from the following files:
src/lte/model/lte-mac-sap.h
src/lte/model/lte-mac-sap.cc