ns-3: MyTag Class Reference
MyTag Class Reference
Network
Public Member Functions
virtual void Deserialize (TagBuffer i)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize (void) const
uint8_t GetSimpleValue (void) const
Get the tag value.
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer i) const
void SetSimpleValue (uint8_t value)
Set the tag value.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_simpleValue
tag value
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A simple example of an Tag implementation
Definition at line 31 of file main-packet-tag.cc.
Member Function Documentation
Deserialize()
void MyTag::Deserialize (TagBuffer i) virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 90 of file main-packet-tag.cc.
References ns3::TagBuffer::ReadU8().
GetInstanceTypeId()
TypeId MyTag::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 75 of file main-packet-tag.cc.
GetSerializedSize()
uint32_t MyTag::GetSerializedSize (void) const virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 80 of file main-packet-tag.cc.
GetSimpleValue()
uint8_t MyTag::GetSimpleValue (void) const
Get the tag value.
Returns
the tag value.
Definition at line 105 of file main-packet-tag.cc.
Referenced by GetTypeId().
GetTypeId()
TypeId MyTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 61 of file main-packet-tag.cc.
References GetSimpleValue(), ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
Print()
void MyTag::Print (std::ostream & os) const virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 95 of file main-packet-tag.cc.
Serialize()
void MyTag::Serialize (TagBuffer i) const virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 85 of file main-packet-tag.cc.
References ns3::TagBuffer::WriteU8().
SetSimpleValue()
void MyTag::SetSimpleValue (uint8_t value)
Set the tag value.
Parameters
value The tag value.
Definition at line 100 of file main-packet-tag.cc.
Member Data Documentation
m_simpleValue
uint8_t MyTag::m_simpleValue private
tag value
Definition at line 57 of file main-packet-tag.cc.
The documentation for this class was generated from the following file:
src/network/examples/main-packet-tag.cc