ns-3: TcpDctcpDecrementTest Class Reference
TcpDctcpDecrementTest Class Reference
Internet » internet module tests | Test suites
Test to validate cWnd decrement DCTCP.
Public Member Functions
TcpDctcpDecrementTest (uint32_t cWnd, uint32_t segmentSize, uint32_t segmentsAcked, SequenceNumber32 nextTxSequence, SequenceNumber32 lastAckedSeq, Time rtt, const std::string &name)
Constructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void ExecuteTest (void)
Execute the test.
Private Attributes
uint32_t m_cWnd
cWnd
SequenceNumber32 m_lastAckedSeq
last acked seq
SequenceNumber32 m_nextTxSequence
next seq num to be sent
Time m_rtt
rtt
uint32_t m_segmentsAcked
segments acked
uint32_t m_segmentSize
segment size
Ptr< TcpSocketState > m_state
state
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test to validate cWnd decrement DCTCP.
Definition at line 603 of file tcp-dctcp-test.cc.
Constructor & Destructor Documentation
TcpDctcpDecrementTest()
TcpDctcpDecrementTest::TcpDctcpDecrementTest (uint32_t cWnd, uint32_t segmentSize, uint32_t segmentsAcked, SequenceNumber32 nextTxSequence, SequenceNumber32 lastAckedSeq, Time rtt, const std::string & name)
Constructor.
Parameters
cWnd congestion window
segmentSize segment size
segmentsAcked segments acked
highTxMark high tx mark
lastAckedSeq last acked seq
rtt RTT
name Name of the test
Definition at line 635 of file tcp-dctcp-test.cc.
Member Function Documentation
DoRun()
void TcpDctcpDecrementTest::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 648 of file tcp-dctcp-test.cc.
References ExecuteTest(), ns3::Seconds(), and ns3::Config::SetDefault().
ExecuteTest()
void TcpDctcpDecrementTest::ExecuteTest (void) private
Execute the test.
Definition at line 657 of file tcp-dctcp-test.cc.
References ns3::TracedValue< T >::Get(), ns3::TcpSocketState::m_cWnd, m_cWnd, ns3::TcpSocketState::m_ecnState, ns3::TcpSocketState::m_lastAckedSeq, m_lastAckedSeq, ns3::TcpSocketState::m_nextTxSequence, m_nextTxSequence, m_rtt, m_segmentsAcked, ns3::TcpSocketState::m_segmentSize, m_segmentSize, m_state, NS_TEST_ASSERT_MSG_EQ, ns3::TcpDctcp::PktsAcked(), and ns3::TcpDctcp::ReduceCwnd().
Referenced by DoRun().
Member Data Documentation
m_cWnd
uint32_t TcpDctcpDecrementTest::m_cWnd private
cWnd
Definition at line 626 of file tcp-dctcp-test.cc.
Referenced by ExecuteTest().
m_lastAckedSeq
SequenceNumber32 TcpDctcpDecrementTest::m_lastAckedSeq private
last acked seq
Definition at line 631 of file tcp-dctcp-test.cc.
Referenced by ExecuteTest().
m_nextTxSequence
SequenceNumber32 TcpDctcpDecrementTest::m_nextTxSequence private
next seq num to be sent
Definition at line 630 of file tcp-dctcp-test.cc.
Referenced by ExecuteTest().
m_rtt
Time TcpDctcpDecrementTest::m_rtt private
rtt
Definition at line 629 of file tcp-dctcp-test.cc.
Referenced by ExecuteTest().
m_segmentsAcked
uint32_t TcpDctcpDecrementTest::m_segmentsAcked private
segments acked
Definition at line 628 of file tcp-dctcp-test.cc.
Referenced by ExecuteTest().
m_segmentSize
uint32_t TcpDctcpDecrementTest::m_segmentSize private
segment size
Definition at line 627 of file tcp-dctcp-test.cc.
Referenced by ExecuteTest().
m_state
Ptr<TcpSocketState> TcpDctcpDecrementTest::m_state private
state
Definition at line 632 of file tcp-dctcp-test.cc.
Referenced by ExecuteTest().
The documentation for this class was generated from the following file:
src/internet/test/tcp-dctcp-test.cc