ns-3: ns3::AlohaNoackMacHeader Class Reference
ns3::AlohaNoackMacHeader Class Reference
Spectrum Models
#include "aloha-noack-mac-header.h"
Public Member Functions
virtual uint32_t Deserialize (Buffer::Iterator start)
Mac48Address GetDestination () const
Get the destination address.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize (void) const
Mac48Address GetSource () const
Get the source address.
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetDestination (Mac48Address destination)
Set the destination address.
void SetSource (Mac48Address source)
Set the source address.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Mac48Address m_destination
destination address
Mac48Address m_source
source address
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Header for the AlohaNoack NetDevice
Definition at line 36 of file aloha-noack-mac-header.h.
Member Function Documentation
Deserialize()
uint32_t ns3::AlohaNoackMacHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 66 of file aloha-noack-mac-header.cc.
References GetSerializedSize(), m_destination, m_source, ns3::ReadFrom(), and visualizer.core::start().
GetDestination()
Mac48Address ns3::AlohaNoackMacHeader::GetDestination () const
Get the destination address.
Returns
the destination address
Definition at line 101 of file aloha-noack-mac-header.cc.
References m_destination.
Referenced by ns3::AlohaNoackNetDevice::NotifyReceptionEndOk().
GetInstanceTypeId()
TypeId ns3::AlohaNoackMacHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 43 of file aloha-noack-mac-header.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::AlohaNoackMacHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 51 of file aloha-noack-mac-header.cc.
Referenced by Deserialize().
GetSource()
Mac48Address ns3::AlohaNoackMacHeader::GetSource () const
Get the source address.
Returns
the source address
Definition at line 89 of file aloha-noack-mac-header.cc.
References m_source.
Referenced by ns3::AlohaNoackNetDevice::NotifyReceptionEndOk().
GetTypeId()
TypeId ns3::AlohaNoackMacHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 32 of file aloha-noack-mac-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::AlohaNoackMacHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 75 of file aloha-noack-mac-header.cc.
References m_destination, and m_source.
Serialize()
void ns3::AlohaNoackMacHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 59 of file aloha-noack-mac-header.cc.
References m_destination, m_source, visualizer.core::start(), and ns3::WriteTo().
SetDestination()
void ns3::AlohaNoackMacHeader::SetDestination (Mac48Address destination)
Set the destination address.
Parameters
destination the destination address
Definition at line 95 of file aloha-noack-mac-header.cc.
References m_destination.
Referenced by ns3::AlohaNoackNetDevice::SendFrom().
SetSource()
void ns3::AlohaNoackMacHeader::SetSource (Mac48Address source)
Set the source address.
Parameters
source the source address
Definition at line 83 of file aloha-noack-mac-header.cc.
References m_source.
Referenced by ns3::AlohaNoackNetDevice::SendFrom().
Member Data Documentation
m_destination
Mac48Address ns3::AlohaNoackMacHeader::m_destination private
destination address
Definition at line 74 of file aloha-noack-mac-header.h.
Referenced by Deserialize(), GetDestination(), Print(), Serialize(), and SetDestination().
m_source
Mac48Address ns3::AlohaNoackMacHeader::m_source private
source address
Definition at line 73 of file aloha-noack-mac-header.h.
Referenced by Deserialize(), GetSource(), Print(), Serialize(), and SetSource().
The documentation for this class was generated from the following files:
src/spectrum/model/aloha-noack-mac-header.h
src/spectrum/model/aloha-noack-mac-header.cc