ns-3: ns3::dot11s::IeBeaconTimingUnit Class Reference
ns3::dot11s::IeBeaconTimingUnit Class Reference
Mesh Device » IEEE 802.11s draft
Information element describing one unit of beacon timing element.
#include "ie-dot11s-beacon-timing.h"
Public Member Functions
IeBeaconTimingUnit ()
uint8_t GetAid () const
Get AID value.
uint16_t GetBeaconInterval () const
Get beacon interval.
uint16_t GetLastBeacon () const
Get last beacon value.
void SetAid (uint8_t aid)
Set AID value.
void SetBeaconInterval (uint16_t beaconInterval)
Set beacon interval value.
void SetLastBeacon (uint16_t lastBeacon)
Set last beacon value.
Public Member Functions inherited from ns3::SimpleRefCount< IeBeaconTimingUnit >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
uint8_t m_aid
Least significant octet of AID:
uint16_t m_beaconInterval
Beacon interval of remote mesh point.
uint16_t m_lastBeacon
Last time we received a beacon in accordance with a local TSF measured in 256 microseconds unit.
Friends
bool operator== (const IeBeaconTimingUnit &a, const IeBeaconTimingUnit &b)
equality operator
Detailed Description
Information element describing one unit of beacon timing element.
Definition at line 34 of file ie-dot11s-beacon-timing.h.
Constructor & Destructor Documentation
IeBeaconTimingUnit()
ns3::dot11s::IeBeaconTimingUnit::IeBeaconTimingUnit ()
Definition at line 28 of file ie-dot11s-beacon-timing.cc.
Member Function Documentation
GetAid()
uint8_t ns3::dot11s::IeBeaconTimingUnit::GetAid () const
Get AID value.
Returns
the AID
Definition at line 48 of file ie-dot11s-beacon-timing.cc.
References m_aid.
Referenced by ns3::dot11s::operator==().
GetBeaconInterval()
uint16_t ns3::dot11s::IeBeaconTimingUnit::GetBeaconInterval () const
Get beacon interval.
Returns
the beacon interval
Definition at line 58 of file ie-dot11s-beacon-timing.cc.
References m_beaconInterval.
Referenced by ns3::dot11s::operator==().
GetLastBeacon()
uint16_t ns3::dot11s::IeBeaconTimingUnit::GetLastBeacon () const
Get last beacon value.
Returns
the last beacon
Definition at line 53 of file ie-dot11s-beacon-timing.cc.
References m_lastBeacon.
Referenced by ns3::dot11s::operator==().
SetAid()
void ns3::dot11s::IeBeaconTimingUnit::SetAid (uint8_t aid)
Set AID value.
Parameters
aid the AID
Definition at line 33 of file ie-dot11s-beacon-timing.cc.
References m_aid.
Referenced by ns3::dot11s::IeBeaconTiming::AddNeighboursTimingElementUnit(), and ns3::dot11s::IeBeaconTiming::DeserializeInformationField().
SetBeaconInterval()
void ns3::dot11s::IeBeaconTimingUnit::SetBeaconInterval (uint16_t beaconInterval)
Set beacon interval value.
Parameters
beaconInterval the beacon interval
Definition at line 43 of file ie-dot11s-beacon-timing.cc.
References m_beaconInterval.
Referenced by ns3::dot11s::IeBeaconTiming::AddNeighboursTimingElementUnit(), and ns3::dot11s::IeBeaconTiming::DeserializeInformationField().
SetLastBeacon()
void ns3::dot11s::IeBeaconTimingUnit::SetLastBeacon (uint16_t lastBeacon)
Set last beacon value.
Parameters
lastBeacon the last beacon
Definition at line 38 of file ie-dot11s-beacon-timing.cc.
References m_lastBeacon.
Referenced by ns3::dot11s::IeBeaconTiming::AddNeighboursTimingElementUnit(), and ns3::dot11s::IeBeaconTiming::DeserializeInformationField().
Friends And Related Function Documentation
operator==
bool operator== (const IeBeaconTimingUnit & a, const IeBeaconTimingUnit & b) friend
equality operator
Parameters
a lhs
b rhs
Returns
true if equal
Definition at line 185 of file ie-dot11s-beacon-timing.cc.
Member Data Documentation
m_aid
uint8_t ns3::dot11s::IeBeaconTimingUnit::m_aid private
Least significant octet of AID:
Definition at line 72 of file ie-dot11s-beacon-timing.h.
Referenced by GetAid(), and SetAid().
m_beaconInterval
uint16_t ns3::dot11s::IeBeaconTimingUnit::m_beaconInterval private
Beacon interval of remote mesh point.
Definition at line 76 of file ie-dot11s-beacon-timing.h.
Referenced by GetBeaconInterval(), and SetBeaconInterval().
m_lastBeacon
uint16_t ns3::dot11s::IeBeaconTimingUnit::m_lastBeacon private
Last time we received a beacon in accordance with a local TSF measured in 256 microseconds unit.
Definition at line 74 of file ie-dot11s-beacon-timing.h.
Referenced by GetLastBeacon(), and SetLastBeacon().
The documentation for this class was generated from the following files:
src/mesh/model/dot11s/ie-dot11s-beacon-timing.h
src/mesh/model/dot11s/ie-dot11s-beacon-timing.cc