ns-3: ns3::SllHeader Class Reference
ns3::SllHeader Class Reference
Network » Packet
Protocol header serialization and deserialization.
#include "sll-header.h"
Public Types
enum PacketType {
UNICAST_FROM_PEER_TO_ME = 0, BROADCAST_BY_PEER = 1, MULTICAST_BY_PEER = 2, INTERCEPTED_PACKET = 3,
SENT_BY_US
}
Type of the packet.
Public Member Functions
SllHeader ()
virtual ~SllHeader ()
virtual uint32_t Deserialize (Buffer::Iterator start)
uint16_t GetArpType () const
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
enum PacketType GetPacketType () const
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetArpType (uint16_t arphdType)
void SetPacketType (PacketType type)
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Attributes
uint64_t m_address
Address.
uint16_t m_addressLength
Address length.
uint16_t m_arphdType
ARP protocol hardware identifier.
PacketType m_packetType
Packet type.
uint16_t m_protocolType
protocol type
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Protocol header serialization and deserialization.
Libpcap sometimes add an additional header to provide information that would be lost otherwise due to the link-layer/capture mechanism, for instance when capturing from "nlmon" device on linux
See also
http://www.tcpdump.org/linktypes/LINKTYPE_LINUX_SLL.html
https://wiki.wireshark.org/SLL
  +---------------------------+
  |         Packet type       |
  |         (2 Octets)        |
  +---------------------------+
  |        ARPHRD_ type       |
  |         (2 Octets)        |
  +---------------------------+
  | Link-layer address length |
  |         (2 Octets)        |
  +---------------------------+
  |    Link-layer address     |
  |         (8 Octets)        |
  +---------------------------+
  |        Protocol type      |
  |         (2 Octets)        |
  +---------------------------+
  |           Payload         |
  .                           .
  .                           .
  .                           .
Definition at line 64 of file sll-header.h.
Member Enumeration Documentation
PacketType
enum ns3::SllHeader::PacketType
Type of the packet.
Enumerator
UNICAST_FROM_PEER_TO_ME
the packet was specifically sent to us by somebody else
BROADCAST_BY_PEER
packet was broadcast by somebody else
MULTICAST_BY_PEER
packet was multicast, but not broadcast, by somebody else
INTERCEPTED_PACKET
packet was sent to somebody else by somebody else
SENT_BY_US
the packet was sent by us
Definition at line 71 of file sll-header.h.
Constructor & Destructor Documentation
SllHeader()
ns3::SllHeader::SllHeader ()
Definition at line 30 of file sll-header.cc.
References NS_LOG_FUNCTION.
~SllHeader()
ns3::SllHeader::~SllHeader () virtual
Definition at line 40 of file sll-header.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Deserialize()
uint32_t ns3::SllHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 113 of file sll-header.cc.
References GetSerializedSize(), m_address, m_addressLength, m_arphdType, m_packetType, m_protocolType, ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadNtohU64(), and visualizer.core::start().
GetArpType()
uint16_t ns3::SllHeader::GetArpType () const
Returns
ARP header type field in network byte order The ARPHRD_ type field is in network byte order; it contains a Linux ARPHRD_ value for the link-layer device type.
Definition at line 64 of file sll-header.cc.
References m_arphdType.
GetInstanceTypeId()
TypeId ns3::SllHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 58 of file sll-header.cc.
References GetTypeId().
GetPacketType()
SllHeader::PacketType ns3::SllHeader::GetPacketType () const
Returns
Packet type
Definition at line 77 of file sll-header.cc.
References m_packetType.
GetSerializedSize()
uint32_t ns3::SllHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 96 of file sll-header.cc.
Referenced by Deserialize().
GetTypeId()
TypeId ns3::SllHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 47 of file sll-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::SllHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 90 of file sll-header.cc.
References m_packetType, and m_protocolType.
Serialize()
void ns3::SllHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 102 of file sll-header.cc.
References m_address, m_addressLength, m_arphdType, m_packetType, m_protocolType, visualizer.core::start(), ns3::Buffer::Iterator::WriteHtonU16(), and ns3::Buffer::Iterator::WriteHtonU64().
SetArpType()
void ns3::SllHeader::SetArpType (uint16_t arphdType)
Parameters
arphdType ARP protocol hardware identifier
Definition at line 70 of file sll-header.cc.
References m_arphdType, and NS_LOG_FUNCTION.
SetPacketType()
void ns3::SllHeader::SetPacketType (PacketType type)
Parameters
type Depends on source and address of the packet
Definition at line 83 of file sll-header.cc.
References m_packetType, and NS_LOG_FUNCTION.
Member Data Documentation
m_address
uint64_t ns3::SllHeader::m_address protected
Address.
Definition at line 123 of file sll-header.h.
Referenced by Deserialize(), and Serialize().
m_addressLength
uint16_t ns3::SllHeader::m_addressLength protected
Address length.
Definition at line 122 of file sll-header.h.
Referenced by Deserialize(), and Serialize().
m_arphdType
uint16_t ns3::SllHeader::m_arphdType protected
ARP protocol hardware identifier.
Definition at line 121 of file sll-header.h.
Referenced by Deserialize(), GetArpType(), Serialize(), and SetArpType().
m_packetType
PacketType ns3::SllHeader::m_packetType protected
Packet type.
Definition at line 120 of file sll-header.h.
Referenced by Deserialize(), GetPacketType(), Print(), Serialize(), and SetPacketType().
m_protocolType
uint16_t ns3::SllHeader::m_protocolType protected
protocol type
Definition at line 124 of file sll-header.h.
Referenced by Deserialize(), Print(), and Serialize().
The documentation for this class was generated from the following files:
src/network/utils/sll-header.h
src/network/utils/sll-header.cc