ns-3: ns3::WimaxPhy Class Reference
ns3::WimaxPhy Class Reference abstract
WiMAX Models
#include "wimax-phy.h"
Public Types
enum ModulationType {
MODULATION_TYPE_BPSK_12, MODULATION_TYPE_QPSK_12, MODULATION_TYPE_QPSK_34, MODULATION_TYPE_QAM16_12,
MODULATION_TYPE_QAM16_34, MODULATION_TYPE_QAM64_23, MODULATION_TYPE_QAM64_34
}
ModulationType enumeration.
enum PhyState { PHY_STATE_IDLE, PHY_STATE_SCANNING, PHY_STATE_TX, PHY_STATE_RX }
PhyState enumeration.
enum PhyType { SimpleWimaxPhy, simpleOfdmWimaxPhy }
PhyType enumeration.
Public Member Functions
WimaxPhy (void)
virtual ~WimaxPhy (void)
virtual int64_t AssignStreams (int64_t stream)=0
Assign a fixed random variable stream number to the random variables used by this model.
void Attach (Ptr< WimaxChannel > channel)
Attach the physical layer to a channel.
virtual void DoDispose (void)
Destructor implementation.
Ptr< WimaxChannel > GetChannel (void) const
uint32_t GetChannelBandwidth (void) const
Get the channel bandwidth.
EventId GetChnlSrchTimeoutEvent (void) const
Get channel search timeout event.
uint32_t GetDataRate (ModulationType modulationType) const
Get the data rate corresponding to a modulation type.
Ptr< NetDevice > GetDevice (void) const
Time GetFrameDuration (uint8_t frameDurationCode) const
Get the frame duration corresponding to a given code.
Time GetFrameDuration (void) const
Get the frame duration.
uint8_t GetFrameDurationCode (void) const
Get the frame duration code.
Time GetFrameDurationSec (void) const
Get the frame duration This method is redundant with GetFrameDuration ()
uint32_t GetFrequency (void) const
Get the frequency on which the device is locked.
double GetGValue (void) const
Get the guard interval factor (the ratio TG/Td)
virtual Ptr< Object > GetMobility (void)
Get the mobility model of the device.
uint16_t GetNfft (void) const
Get the size of the FFT.
uint64_t GetNrBytes (uint32_t symbols, ModulationType modulationType) const
Get the maximum number of bytes that could be carried by symbols symbols using the modulation modulationType.
uint8_t GetNrCarriers (void) const
Get the number of carriers in the physical frame.
uint64_t GetNrSymbols (uint32_t size, ModulationType modulationType) const
Get the number of symbols needed to transmit size bytes using the modulation modulationType.
virtual PhyType GetPhyType (void) const =0
Get the type of the physical layer.
Time GetPsDuration (void) const
Get the physical slot duration.
uint16_t GetPsPerFrame (void) const
Get the number of physical slots per frame.
uint16_t GetPsPerSymbol (void) const
Get the number of physical slots per symbol.
Callback< void, Ptr< const PacketBurst > > GetReceiveCallback (void) const
uint16_t GetRtg (void) const
Get the receive/transmit transition gap.
uint64_t GetRxFrequency (void) const
Get the reception frequency.
double GetSamplingFactor (void) const
Get the sampling factor.
double GetSamplingFrequency (void) const
Get the sampling frequency.
uint64_t GetScanningFrequency (void) const
Get the scanning frequency.
PhyState GetState (void) const
Get the state of the device.
Time GetSymbolDuration (void) const
Get the OFDM symbol duration.
uint32_t GetSymbolsPerFrame (void) const
Get the number of symbols per frame.
Time GetTransmissionTime (uint32_t size, ModulationType modulationType) const
Get transmission time needed to send bytes at a given modulation.
uint16_t GetTtg (void) const
Get the transmit/receive transition gap.
uint64_t GetTxFrequency (void) const
Get the transmission frequency.
bool IsDuplex (void) const
Check if configured in duplex mode.
virtual void Send (SendParams *params)=0
send a packet on the channel
void SetChannelBandwidth (uint32_t channelBandwidth)
Set the channel bandwidth.
void SetDataRates (void)
calculates the data rate of each modulation and save them for future use
void SetDevice (Ptr< WimaxNetDevice > device)
Set the device in which this physical layer is installed.
void SetDuplex (uint64_t rxFrequency, uint64_t txFrequency)
configure the physical layer in duplex mode
void SetFrameDuration (Time frameDuration)
Set the frame duration.
void SetFrequency (uint32_t frequency)
set the frequency on which the device should lock
virtual void SetMobility (Ptr< Object > mobility)
set the mobility model of the device
void SetNrCarriers (uint8_t nrCarriers)
Set the number of carriers in the physical frame.
void SetPhyParameters (void)
computes the Physical parameters and store them
void SetPsDuration (Time psDuration)
set the physical slot duration
void SetPsPerFrame (uint16_t psPerFrame)
set the number of physical slots per frame
void SetPsPerSymbol (uint16_t psPerSymbol)
set the number of physical slots per symbol
void SetReceiveCallback (Callback< void, Ptr< const PacketBurst > > callback)
set the callback function to call when a burst is received
void SetScanningCallback (void) const
calls the scanning call back function
void SetSimplex (uint64_t frequency)
configure the physical layer in simplex mode
void SetState (PhyState state)
set the state of the device
void SetSymbolDuration (Time symbolDuration)
set the OFDM symbol duration
void SetSymbolsPerFrame (uint32_t symbolsPerFrame)
set the number of symbols per frame
void StartScanning (uint64_t frequency, Time timeout, Callback< void, bool, uint64_t > callback)
scan a frequency for maximum timeout seconds and call the callback if the frequency can be used
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual void DoAttach (Ptr< WimaxChannel > channel)=0
Attach channel.
virtual uint32_t DoGetDataRate (ModulationType modulationType) const =0
Get data rate.
virtual Time DoGetFrameDuration (uint8_t frameDurationCode) const =0
Get frame duration.
virtual uint8_t DoGetFrameDurationCode (void) const =0
Get frame duration code.
virtual double DoGetGValue (void) const =0
Get G value.
virtual uint16_t DoGetNfft (void) const =0
Get NFFT.
virtual uint64_t DoGetNrBytes (uint32_t symbols, ModulationType modulationType) const =0
Get number of bytes.
virtual uint64_t DoGetNrSymbols (uint32_t size, ModulationType modulationType) const =0
Get number of symbols.
virtual uint16_t DoGetRtg (void) const =0
Get RTG.
virtual double DoGetSamplingFactor (void) const =0
Get sampling factor.
virtual double DoGetSamplingFrequency (void) const =0
Get sampling frequency.
virtual Time DoGetTransmissionTime (uint32_t size, ModulationType modulationType) const =0
Get transmission time.
virtual uint16_t DoGetTtg (void) const =0
Get TTG.
virtual void DoSetDataRates (void)=0
Set data rates.
virtual void DoSetPhyParameters (void)=0
Set phy parameters.
void EndScanning (void)
End scanning.
void GetModulationFecParams (ModulationType modulationType, uint8_t &bitsPerSymbol, double &fecCode) const
Get modulation FEC parameters.
Private Attributes
Ptr< WimaxChannel > m_channel
channel
uint32_t m_channelBandwidth
in Hz
Ptr< WimaxNetDevice > m_device
the device
EventId m_dlChnlSrchTimeoutEvent
DL channel search timeout event.
bool m_duplex
duplex
Time m_frameDuration
in seconds
uint32_t m_frequency
in KHz
Ptr< Object > m_mobility
modility model
uint8_t m_nrCarriers
number of carriers
Time m_psDuration
in seconds
uint16_t m_psPerFrame
ps per framce
uint16_t m_psPerSymbol
ps per sumbol
Callback< void, Ptr< const PacketBurst > > m_rxCallback
receive callback function
uint64_t m_rxFrequency
receive frequency
Callback< void, bool, uint64_t > m_scanningCallback
scanning callback function
uint64_t m_scanningFrequency
scanning frequency
PhyState m_state
state
Time m_symbolDuration
in seconds
uint32_t m_symbolsPerFrame
symbols per frame
uint64_t m_txFrequency
transmit frequency
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 45 of file wimax-phy.h.
Member Enumeration Documentation
ModulationType
enum ns3::WimaxPhy::ModulationType
ModulationType enumeration.
Enumerator
MODULATION_TYPE_BPSK_12
MODULATION_TYPE_QPSK_12
MODULATION_TYPE_QPSK_34
MODULATION_TYPE_QAM16_12
MODULATION_TYPE_QAM16_34
MODULATION_TYPE_QAM64_23
MODULATION_TYPE_QAM64_34
Definition at line 49 of file wimax-phy.h.
PhyState
enum ns3::WimaxPhy::PhyState
PhyState enumeration.
Enumerator
PHY_STATE_IDLE
PHY_STATE_SCANNING
PHY_STATE_TX
PHY_STATE_RX
Definition at line 61 of file wimax-phy.h.
PhyType
enum ns3::WimaxPhy::PhyType
PhyType enumeration.
Enumerator
SimpleWimaxPhy
simpleOfdmWimaxPhy
Definition at line 70 of file wimax-phy.h.
Constructor & Destructor Documentation
WimaxPhy()
ns3::WimaxPhy::WimaxPhy (void)
Definition at line 75 of file wimax-phy.cc.
References m_duplex, m_mobility, m_rxFrequency, and m_txFrequency.
~WimaxPhy()
ns3::WimaxPhy::~WimaxPhy (void) virtual
Definition at line 94 of file wimax-phy.cc.
Member Function Documentation
AssignStreams()
virtual int64_t ns3::WimaxPhy::AssignStreams (int64_t stream) pure virtual
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Implemented in ns3::SimpleOfdmWimaxPhy.
Attach()
void ns3::WimaxPhy::Attach (Ptr< WimaxChannel > channel)
Attach the physical layer to a channel.
Parameters
channel the channel to which the physical layer will be attached
Definition at line 106 of file wimax-phy.cc.
References third::channel, DoAttach(), and m_channel.
Referenced by GetTypeId().
DoAttach()
virtual void ns3::WimaxPhy::DoAttach (Ptr< WimaxChannel > channel) private pure virtual
Attach channel.
Parameters
channel the wimax channel
Implemented in ns3::SimpleOfdmWimaxPhy.
Referenced by Attach().
DoDispose()
void ns3::WimaxPhy::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Reimplemented in ns3::SimpleOfdmWimaxPhy.
Definition at line 99 of file wimax-phy.cc.
References m_channel, and m_device.
Referenced by ns3::SimpleOfdmWimaxPhy::DoDispose().
DoGetDataRate()
virtual uint32_t ns3::WimaxPhy::DoGetDataRate (ModulationType modulationType) const private pure virtual
Get data rate.
Parameters
modulationType the modulation type
Returns
the data rate
Implemented in ns3::SimpleOfdmWimaxPhy.
Referenced by GetDataRate().
DoGetFrameDuration()
virtual Time ns3::WimaxPhy::DoGetFrameDuration (uint8_t frameDurationCode) const private pure virtual
Get frame duration.
Parameters
frameDurationCode the frame duration code
Returns
the frame duration time
Implemented in ns3::SimpleOfdmWimaxPhy.
Referenced by GetFrameDuration().
DoGetFrameDurationCode()
virtual uint8_t ns3::WimaxPhy::DoGetFrameDurationCode (void) const private pure virtual
Get frame duration code.
Returns
the frame duration code
Implemented in ns3::SimpleOfdmWimaxPhy.
Referenced by GetFrameDurationCode().
DoGetGValue()
virtual double ns3::WimaxPhy::DoGetGValue (void) const private pure virtual
Get G value.
Returns
he G value
Implemented in ns3::SimpleOfdmWimaxPhy.
Referenced by GetGValue().
DoGetNfft()
virtual uint16_t ns3::WimaxPhy::DoGetNfft (void) const private pure virtual
Get NFFT.
Returns
the NFFT
Implemented in ns3::SimpleOfdmWimaxPhy.
Referenced by GetNfft().
DoGetNrBytes()
virtual uint64_t ns3::WimaxPhy::DoGetNrBytes (uint32_t symbols, ModulationType modulationType) const private pure virtual
Get number of bytes.
Parameters
symbols the number of symbols
modulationType the modulation type
Returns
the number of bytes
Implemented in ns3::SimpleOfdmWimaxPhy.
Referenced by GetNrBytes().
DoGetNrSymbols()
virtual uint64_t ns3::WimaxPhy::DoGetNrSymbols (uint32_t size, ModulationType modulationType) const private pure virtual
Get number of symbols.
Parameters
size the transmission size
modulationType the modulation type
Returns
the number of symbols
Implemented in ns3::SimpleOfdmWimaxPhy.
Referenced by GetNrSymbols().
DoGetRtg()
virtual uint16_t ns3::WimaxPhy::DoGetRtg (void) const private pure virtual
Get RTG.
Returns
the RTG
Implemented in ns3::SimpleOfdmWimaxPhy.
Referenced by GetRtg().
DoGetSamplingFactor()
virtual double ns3::WimaxPhy::DoGetSamplingFactor (void) const private pure virtual
Get sampling factor.
Returns
the sampling factor
Implemented in ns3::SimpleOfdmWimaxPhy.
Referenced by GetSamplingFactor().
DoGetSamplingFrequency()
virtual double ns3::WimaxPhy::DoGetSamplingFrequency (void) const private pure virtual
Get sampling frequency.
Returns
the sampling frequency
Implemented in ns3::SimpleOfdmWimaxPhy.
Referenced by GetSamplingFrequency().
DoGetTransmissionTime()
virtual Time ns3::WimaxPhy::DoGetTransmissionTime (uint32_t size, ModulationType modulationType) const private pure virtual
Get transmission time.
Parameters
size the transmission size
modulationType the modulation type
Returns
the transmission time
Implemented in ns3::SimpleOfdmWimaxPhy.
Referenced by GetTransmissionTime().
DoGetTtg()
virtual uint16_t ns3::WimaxPhy::DoGetTtg (void) const private pure virtual
Get TTG.
Returns
the TTG
Implemented in ns3::SimpleOfdmWimaxPhy.
Referenced by GetTtg().
DoSetDataRates()
virtual void ns3::WimaxPhy::DoSetDataRates (void) private pure virtual
Set data rates.
Implemented in ns3::SimpleOfdmWimaxPhy.
Referenced by SetDataRates().
DoSetPhyParameters()
virtual void ns3::WimaxPhy::DoSetPhyParameters (void) private pure virtual
Set phy parameters.
Implemented in ns3::SimpleOfdmWimaxPhy.
Referenced by SetPhyParameters().
EndScanning()
void ns3::WimaxPhy::EndScanning (void) private
End scanning.
Definition at line 143 of file wimax-phy.cc.
References m_scanningCallback, and m_scanningFrequency.
Referenced by StartScanning().
GetChannel()
Ptr< WimaxChannel > ns3::WimaxPhy::GetChannel (void) const
Returns
the channel to which this physical layer is attached
Definition at line 113 of file wimax-phy.cc.
References m_channel.
Referenced by ns3::SimpleOfdmWimaxPhy::DoAttach(), GetTypeId(), and ns3::SimpleOfdmWimaxPhy::StartSendDummyFecBlock().
GetChannelBandwidth()
uint32_t ns3::WimaxPhy::GetChannelBandwidth (void) const
Get the channel bandwidth.
Returns
the channel bandwidth
Definition at line 332 of file wimax-phy.cc.
References m_channelBandwidth.
Referenced by ns3::SimpleOfdmWimaxPhy::DoGetSamplingFactor(), ns3::SimpleOfdmWimaxPhy::DoGetSamplingFrequency(), ns3::SimpleOfdmWimaxPhy::GetBandwidth(), and GetTypeId().
GetChnlSrchTimeoutEvent()
EventId ns3::WimaxPhy::GetChnlSrchTimeoutEvent (void) const
Get channel search timeout event.
Returns
event ID
Definition at line 210 of file wimax-phy.cc.
References m_dlChnlSrchTimeoutEvent.
Referenced by ns3::SimpleOfdmWimaxPhy::StartReceive().
GetDataRate()
uint32_t ns3::WimaxPhy::GetDataRate (WimaxPhy::ModulationType modulationType) const
Get the data rate corresponding to a modulation type.
Returns
the data rate
Parameters
modulationType the modulation that you want to get its data rate
Definition at line 228 of file wimax-phy.cc.
References DoGetDataRate().
GetDevice()
Ptr< NetDevice > ns3::WimaxPhy::GetDevice (void) const
Returns
the the device in which this physical layer is installed
Definition at line 125 of file wimax-phy.cc.
References m_device.
GetFrameDuration() [1/2]
Time ns3::WimaxPhy::GetFrameDuration (uint8_t frameDurationCode) const
Get the frame duration corresponding to a given code.
Parameters
frameDurationCode the frame duration code to use
Returns
the frame duration
Definition at line 270 of file wimax-phy.cc.
References DoGetFrameDuration().
GetFrameDuration() [2/2]
Time ns3::WimaxPhy::GetFrameDuration (void) const
Get the frame duration.
Returns
the frame duration
Definition at line 302 of file wimax-phy.cc.
References GetFrameDurationSec().
Referenced by ns3::SimpleOfdmWimaxPhy::DoGetFrameDurationCode(), and ns3::SimpleOfdmWimaxPhy::DoSetPhyParameters().
GetFrameDurationCode()
uint8_t ns3::WimaxPhy::GetFrameDurationCode (void) const
Get the frame duration code.
Returns
the frame duration code
Definition at line 264 of file wimax-phy.cc.
References DoGetFrameDurationCode().
GetFrameDurationSec()
Time ns3::WimaxPhy::GetFrameDurationSec (void) const
Get the frame duration This method is redundant with GetFrameDuration ()
Returns
the frame duration
Definition at line 308 of file wimax-phy.cc.
References m_frameDuration.
Referenced by GetFrameDuration(), and GetTypeId().
GetFrequency()
uint32_t ns3::WimaxPhy::GetFrequency (void) const
Get the frequency on which the device is locked.
Returns
the frequency on which the device is locked
Definition at line 320 of file wimax-phy.cc.
References m_frequency.
Referenced by GetTypeId().
GetGValue()
double ns3::WimaxPhy::GetGValue (void) const
Get the guard interval factor (the ratio TG/Td)
Returns
the guard interval factor
Definition at line 380 of file wimax-phy.cc.
References DoGetGValue().
GetMobility()
Ptr< Object > ns3::WimaxPhy::GetMobility (void) virtual
Get the mobility model of the device.
Returns
the mobility model of the device
Definition at line 421 of file wimax-phy.cc.
References m_mobility.
GetModulationFecParams()
void ns3::WimaxPhy::GetModulationFecParams (ModulationType modulationType, uint8_t & bitsPerSymbol, double & fecCode) const private
Get modulation FEC parameters.
Parameters
modulationType the modultion type
bitsPerSymbol the number of bits per symbol page
fecCode the FEC code
GetNfft()
uint16_t ns3::WimaxPhy::GetNfft (void) const
Get the size of the FFT.
Returns
the size of the FFT
Definition at line 338 of file wimax-phy.cc.
References DoGetNfft().
GetNrBytes()
uint64_t ns3::WimaxPhy::GetNrBytes (uint32_t symbols, WimaxPhy::ModulationType modulationType) const
Get the maximum number of bytes that could be carried by symbols symbols using the modulation modulationType.
Returns
the maximum number of bytes
Parameters
symbols the number of symbols to use
modulationType the modulation that will be used
Definition at line 246 of file wimax-phy.cc.
References DoGetNrBytes().
GetNrCarriers()
uint8_t ns3::WimaxPhy::GetNrCarriers (void) const
Get the number of carriers in the physical frame.
Returns
the number of carriers in the physical frame
Definition at line 290 of file wimax-phy.cc.
References m_nrCarriers.
Referenced by ns3::SimpleOfdmWimaxPhy::CalculateDataRate().
GetNrSymbols()
uint64_t ns3::WimaxPhy::GetNrSymbols (uint32_t size, WimaxPhy::ModulationType modulationType) const
Get the number of symbols needed to transmit size bytes using the modulation modulationType.
Returns
the number of symbols needed
Parameters
size the number of byte to transmit
modulationType the modulation that will be used to transmit the bytes
Definition at line 240 of file wimax-phy.cc.
References DoGetNrSymbols().
GetPhyType()
virtual PhyType ns3::WimaxPhy::GetPhyType (void) const pure virtual
Get the type of the physical layer.
Returns
the phy type
Implemented in ns3::SimpleOfdmWimaxPhy.
GetPsDuration()
Time ns3::WimaxPhy::GetPsDuration (void) const
Get the physical slot duration.
Returns
the physical slot duration
Definition at line 362 of file wimax-phy.cc.
References m_psDuration.
GetPsPerFrame()
uint16_t ns3::WimaxPhy::GetPsPerFrame (void) const
Get the number of physical slots per frame.
Returns
the number of physical slot per frame
Definition at line 404 of file wimax-phy.cc.
References m_psPerFrame.
GetPsPerSymbol()
uint16_t ns3::WimaxPhy::GetPsPerSymbol (void) const
Get the number of physical slots per symbol.
Returns
the number of physical slots per symbol
Definition at line 392 of file wimax-phy.cc.
References m_psPerSymbol.
Referenced by ns3::SimpleOfdmWimaxPhy::DoGetRtg(), and ns3::SimpleOfdmWimaxPhy::DoGetTtg().
GetReceiveCallback()
Callback< void, Ptr< const PacketBurst > > ns3::WimaxPhy::GetReceiveCallback (void) const
Returns
the receive callback
Definition at line 155 of file wimax-phy.cc.
References m_rxCallback.
Referenced by ns3::SimpleOfdmWimaxPhy::EndReceive().
GetRtg()
uint16_t ns3::WimaxPhy::GetRtg (void) const
Get the receive/transmit transition gap.
Returns
the receive/transmit transition gap
Definition at line 258 of file wimax-phy.cc.
References DoGetRtg().
GetRxFrequency()
uint64_t ns3::WimaxPhy::GetRxFrequency (void) const
Get the reception frequency.
Returns
the reception frequency
Definition at line 175 of file wimax-phy.cc.
References m_rxFrequency.
Referenced by ns3::SimpleOfdmWimaxPhy::StartReceive().
GetSamplingFactor()
double ns3::WimaxPhy::GetSamplingFactor (void) const
Get the sampling factor.
Returns
the sampling factor
Definition at line 344 of file wimax-phy.cc.
References DoGetSamplingFactor().
GetSamplingFrequency()
double ns3::WimaxPhy::GetSamplingFrequency (void) const
Get the sampling frequency.
Returns
the sampling frequency
Definition at line 350 of file wimax-phy.cc.
References DoGetSamplingFrequency().
GetScanningFrequency()
uint64_t ns3::WimaxPhy::GetScanningFrequency (void) const
Get the scanning frequency.
Returns
the scanning frequency
Definition at line 187 of file wimax-phy.cc.
References m_scanningFrequency.
Referenced by SetScanningCallback(), and ns3::SimpleOfdmWimaxPhy::StartReceive().
GetState()
WimaxPhy::PhyState ns3::WimaxPhy::GetState (void) const
Get the state of the device.
Returns
the state of the device (PHY_STATE_IDLE, PHY_STATE_SCANNING, PHY_STATE_TX, PHY_STATE_RX)
Definition at line 198 of file wimax-phy.cc.
References m_state.
Referenced by ns3::SimpleOfdmWimaxPhy::Send(), and ns3::SimpleOfdmWimaxPhy::StartReceive().
GetSymbolDuration()
Time ns3::WimaxPhy::GetSymbolDuration (void) const
Get the OFDM symbol duration.
Returns
the symbol duration in second
Definition at line 374 of file wimax-phy.cc.
References m_symbolDuration.
Referenced by ns3::SimpleOfdmWimaxPhy::CalculateDataRate(), ns3::SimpleOfdmWimaxPhy::DoGetNrBytes(), ns3::SimpleOfdmWimaxPhy::DoGetNrSymbols(), and ns3::SimpleOfdmWimaxPhy::DoGetTransmissionTime().
GetSymbolsPerFrame()
uint32_t ns3::WimaxPhy::GetSymbolsPerFrame (void) const
Get the number of symbols per frame.
Returns
the number of symbols per frame
Definition at line 416 of file wimax-phy.cc.
References m_symbolsPerFrame.
GetTransmissionTime()
Time ns3::WimaxPhy::GetTransmissionTime (uint32_t size, WimaxPhy::ModulationType modulationType) const
Get transmission time needed to send bytes at a given modulation.
Returns
the time needed
Parameters
size the number of byte to transmit
modulationType the modulation that will be used to transmit the bytes
Definition at line 234 of file wimax-phy.cc.
References DoGetTransmissionTime().
GetTtg()
uint16_t ns3::WimaxPhy::GetTtg (void) const
Get the transmit/receive transition gap.
Returns
the transmit/receive transition gap
Definition at line 252 of file wimax-phy.cc.
References DoGetTtg().
GetTxFrequency()
uint64_t ns3::WimaxPhy::GetTxFrequency (void) const
Get the transmission frequency.
Returns
the transmission frequency
Definition at line 181 of file wimax-phy.cc.
References m_txFrequency.
Referenced by ns3::SimpleOfdmWimaxPhy::StartSendDummyFecBlock().
GetTypeId()
TypeId ns3::WimaxPhy::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 39 of file wimax-phy.cc.
References Attach(), GetChannel(), GetChannelBandwidth(), GetFrameDurationSec(), GetFrequency(), ns3::MakePointerAccessor(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeUintegerAccessor(), ns3::Seconds(), SetChannelBandwidth(), SetFrameDuration(), SetFrequency(), and ns3::TypeId::SetParent().
IsDuplex()
bool ns3::WimaxPhy::IsDuplex (void) const
Check if configured in duplex mode.
Returns
true if the device is configured in duplex mode
Definition at line 204 of file wimax-phy.cc.
References m_duplex.
Referenced by ns3::SimpleOfdmWimaxPhy::StartReceive().
Send()
virtual void ns3::WimaxPhy::Send (SendParams * params) pure virtual
send a packet on the channel
Parameters
params the parameters used to send the packet
Implemented in ns3::SimpleOfdmWimaxPhy.
SetChannelBandwidth()
void ns3::WimaxPhy::SetChannelBandwidth (uint32_t channelBandwidth)
Set the channel bandwidth.
Parameters
channelBandwidth The channel bandwidth
Definition at line 326 of file wimax-phy.cc.
References m_channelBandwidth.
Referenced by GetTypeId(), and ns3::SimpleOfdmWimaxPhy::SetBandwidth().
SetDataRates()
void ns3::WimaxPhy::SetDataRates (void)
calculates the data rate of each modulation and save them for future use
Definition at line 222 of file wimax-phy.cc.
References DoSetDataRates().
SetDevice()
void ns3::WimaxPhy::SetDevice (Ptr< WimaxNetDevice > device)
Set the device in which this physical layer is installed.
Parameters
device the device in which this physical layer is installed
Definition at line 119 of file wimax-phy.cc.
References m_device.
SetDuplex()
void ns3::WimaxPhy::SetDuplex (uint64_t rxFrequency, uint64_t txFrequency)
configure the physical layer in duplex mode
Parameters
rxFrequency the reception frequency
txFrequency the transmission frequency
Definition at line 161 of file wimax-phy.cc.
References m_rxFrequency, and m_txFrequency.
SetFrameDuration()
void ns3::WimaxPhy::SetFrameDuration (Time frameDuration)
Set the frame duration.
Parameters
frameDuration the frame duration
Definition at line 296 of file wimax-phy.cc.
References m_frameDuration.
Referenced by GetTypeId().
SetFrequency()
void ns3::WimaxPhy::SetFrequency (uint32_t frequency)
set the frequency on which the device should lock
Parameters
frequency the frequency to configure
Definition at line 314 of file wimax-phy.cc.
References m_frequency.
Referenced by GetTypeId().
SetMobility()
void ns3::WimaxPhy::SetMobility (Ptr< Object > mobility) virtual
set the mobility model of the device
Parameters
mobility the mobility model to set
Definition at line 427 of file wimax-phy.cc.
References m_mobility, and third::mobility.
SetNrCarriers()
void ns3::WimaxPhy::SetNrCarriers (uint8_t nrCarriers)
Set the number of carriers in the physical frame.
Set the number of carriers in the physical frame
Parameters
nrCarriers the number of carriers in the frame
Definition at line 284 of file wimax-phy.cc.
References m_nrCarriers.
Referenced by ns3::SimpleOfdmWimaxPhy::InitSimpleOfdmWimaxPhy().
SetPhyParameters()
void ns3::WimaxPhy::SetPhyParameters (void)
computes the Physical parameters and store them
Definition at line 278 of file wimax-phy.cc.
References DoSetPhyParameters().
SetPsDuration()
void ns3::WimaxPhy::SetPsDuration (Time psDuration)
set the physical slot duration
Parameters
psDuration the physical slot duration
Definition at line 356 of file wimax-phy.cc.
References m_psDuration.
Referenced by ns3::SimpleOfdmWimaxPhy::DoSetPhyParameters().
SetPsPerFrame()
void ns3::WimaxPhy::SetPsPerFrame (uint16_t psPerFrame)
set the number of physical slots per frame
Parameters
psPerFrame the number of physical slots per frame
Definition at line 398 of file wimax-phy.cc.
References m_psPerFrame.
Referenced by ns3::SimpleOfdmWimaxPhy::DoSetPhyParameters().
SetPsPerSymbol()
void ns3::WimaxPhy::SetPsPerSymbol (uint16_t psPerSymbol)
set the number of physical slots per symbol
Parameters
psPerSymbol the number of physical slots per symbol
Definition at line 386 of file wimax-phy.cc.
References m_psPerSymbol.
Referenced by ns3::SimpleOfdmWimaxPhy::DoSetPhyParameters().
SetReceiveCallback()
void ns3::WimaxPhy::SetReceiveCallback (Callback< void, Ptr< const PacketBurst > > callback)
set the callback function to call when a burst is received
Parameters
callback the callback function to call when a burst is received
Definition at line 149 of file wimax-phy.cc.
References m_rxCallback.
SetScanningCallback()
void ns3::WimaxPhy::SetScanningCallback (void) const
calls the scanning call back function
Definition at line 216 of file wimax-phy.cc.
References GetScanningFrequency(), and m_scanningCallback.
Referenced by ns3::SimpleOfdmWimaxPhy::StartReceive().
SetSimplex()
void ns3::WimaxPhy::SetSimplex (uint64_t frequency)
configure the physical layer in simplex mode
Parameters
frequency the frequency to be used for reception and transmission process
Definition at line 168 of file wimax-phy.cc.
References m_rxFrequency, and m_txFrequency.
Referenced by ns3::SimpleOfdmWimaxPhy::StartReceive().
SetState()
void ns3::WimaxPhy::SetState (PhyState state)
set the state of the device
Parameters
state the state to be set (PHY_STATE_IDLE, PHY_STATE_SCANNING, PHY_STATE_TX, PHY_STATE_RX)
Definition at line 193 of file wimax-phy.cc.
References m_state.
Referenced by ns3::SimpleOfdmWimaxPhy::EndReceiveFecBlock(), ns3::SimpleOfdmWimaxPhy::EndSend(), ns3::SimpleOfdmWimaxPhy::EndSendFecBlock(), ns3::SimpleOfdmWimaxPhy::StartReceive(), and ns3::SimpleOfdmWimaxPhy::StartSendDummyFecBlock().
SetSymbolDuration()
void ns3::WimaxPhy::SetSymbolDuration (Time symbolDuration)
set the OFDM symbol duration
Parameters
symbolDuration the symbol duration
Definition at line 368 of file wimax-phy.cc.
References m_symbolDuration.
Referenced by ns3::SimpleOfdmWimaxPhy::DoSetPhyParameters().
SetSymbolsPerFrame()
void ns3::WimaxPhy::SetSymbolsPerFrame (uint32_t symbolsPerFrame)
set the number of symbols per frame
Parameters
symbolsPerFrame the number of symbols per frame
Definition at line 410 of file wimax-phy.cc.
References m_symbolsPerFrame.
Referenced by ns3::SimpleOfdmWimaxPhy::DoSetPhyParameters().
StartScanning()
void ns3::WimaxPhy::StartScanning (uint64_t frequency, Time timeout, Callback< void, bool, uint64_t > callback)
scan a frequency for maximum timeout seconds and call the callback if the frequency can be used
Parameters
frequency the frequency to scan
timeout the timeout before considering the channel as unusable
callback the function to call if the channel could be used
Definition at line 131 of file wimax-phy.cc.
References EndScanning(), m_dlChnlSrchTimeoutEvent, m_scanningCallback, m_scanningFrequency, m_state, NS_ASSERT_MSG(), PHY_STATE_IDLE, PHY_STATE_SCANNING, ns3::Simulator::Schedule(), and timeout.
Member Data Documentation
m_channel
Ptr<WimaxChannel> ns3::WimaxPhy::m_channel private
channel
Definition at line 466 of file wimax-phy.h.
Referenced by Attach(), DoDispose(), and GetChannel().
m_channelBandwidth
uint32_t ns3::WimaxPhy::m_channelBandwidth private
in Hz
Definition at line 481 of file wimax-phy.h.
Referenced by GetChannelBandwidth(), and SetChannelBandwidth().
m_device
Ptr<WimaxNetDevice> ns3::WimaxPhy::m_device private
the device
Definition at line 465 of file wimax-phy.h.
Referenced by DoDispose(), GetDevice(), and SetDevice().
m_dlChnlSrchTimeoutEvent
EventId ns3::WimaxPhy::m_dlChnlSrchTimeoutEvent private
DL channel search timeout event.
Definition at line 471 of file wimax-phy.h.
Referenced by GetChnlSrchTimeoutEvent(), and StartScanning().
m_duplex
bool ns3::WimaxPhy::m_duplex private
duplex
Definition at line 472 of file wimax-phy.h.
Referenced by WimaxPhy(), and IsDuplex().
m_frameDuration
Time ns3::WimaxPhy::m_frameDuration private
in seconds
Definition at line 479 of file wimax-phy.h.
Referenced by GetFrameDurationSec(), and SetFrameDuration().
m_frequency
uint32_t ns3::WimaxPhy::m_frequency private
in KHz
Definition at line 480 of file wimax-phy.h.
Referenced by GetFrequency(), and SetFrequency().
m_mobility
Ptr<Object> ns3::WimaxPhy::m_mobility private
modility model
Definition at line 487 of file wimax-phy.h.
Referenced by WimaxPhy(), GetMobility(), and SetMobility().
m_nrCarriers
uint8_t ns3::WimaxPhy::m_nrCarriers private
number of carriers
Definition at line 478 of file wimax-phy.h.
Referenced by GetNrCarriers(), and SetNrCarriers().
m_psDuration
Time ns3::WimaxPhy::m_psDuration private
in seconds
Definition at line 482 of file wimax-phy.h.
Referenced by GetPsDuration(), and SetPsDuration().
m_psPerFrame
uint16_t ns3::WimaxPhy::m_psPerFrame private
ps per framce
Definition at line 485 of file wimax-phy.h.
Referenced by GetPsPerFrame(), and SetPsPerFrame().
m_psPerSymbol
uint16_t ns3::WimaxPhy::m_psPerSymbol private
ps per sumbol
Definition at line 484 of file wimax-phy.h.
Referenced by GetPsPerSymbol(), and SetPsPerSymbol().
m_rxCallback
Callback<void, Ptr<const PacketBurst> > ns3::WimaxPhy::m_rxCallback private
receive callback function
Definition at line 475 of file wimax-phy.h.
Referenced by GetReceiveCallback(), and SetReceiveCallback().
m_rxFrequency
uint64_t ns3::WimaxPhy::m_rxFrequency private
receive frequency
Definition at line 469 of file wimax-phy.h.
Referenced by WimaxPhy(), GetRxFrequency(), SetDuplex(), and SetSimplex().
m_scanningCallback
Callback<void, bool, uint64_t> ns3::WimaxPhy::m_scanningCallback private
scanning callback function
Definition at line 476 of file wimax-phy.h.
Referenced by EndScanning(), SetScanningCallback(), and StartScanning().
m_scanningFrequency
uint64_t ns3::WimaxPhy::m_scanningFrequency private
scanning frequency
Definition at line 470 of file wimax-phy.h.
Referenced by EndScanning(), GetScanningFrequency(), and StartScanning().
m_state
PhyState ns3::WimaxPhy::m_state private
state
Definition at line 473 of file wimax-phy.h.
Referenced by GetState(), SetState(), and StartScanning().
m_symbolDuration
Time ns3::WimaxPhy::m_symbolDuration private
in seconds
Definition at line 483 of file wimax-phy.h.
Referenced by GetSymbolDuration(), and SetSymbolDuration().
m_symbolsPerFrame
uint32_t ns3::WimaxPhy::m_symbolsPerFrame private
symbols per frame
Definition at line 486 of file wimax-phy.h.
Referenced by GetSymbolsPerFrame(), and SetSymbolsPerFrame().
m_txFrequency
uint64_t ns3::WimaxPhy::m_txFrequency private
transmit frequency
Definition at line 468 of file wimax-phy.h.
Referenced by WimaxPhy(), GetTxFrequency(), SetDuplex(), and SetSimplex().
The documentation for this class was generated from the following files:
src/wimax/model/wimax-phy.h
src/wimax/model/wimax-phy.cc