ns-3: ns3::EnergyHarvesterContainer Class Reference
ns3::EnergyHarvesterContainer Class Reference
Energy Models
Holds a vector of ns3::EnergyHarvester pointers.
#include "energy-harvester-container.h"
Public Types
typedef std::vector< Ptr< EnergyHarvester > >::const_iterator Iterator
Public Member Functions
EnergyHarvesterContainer ()
Creates an empty EnergyHarvesterContainer.
EnergyHarvesterContainer (const EnergyHarvesterContainer &a, const EnergyHarvesterContainer &b)
EnergyHarvesterContainer (Ptr< EnergyHarvester > harvester)
EnergyHarvesterContainer (std::string harvesterName)
~EnergyHarvesterContainer ()
void Add (EnergyHarvesterContainer container)
void Add (Ptr< EnergyHarvester > harvester)
Append a single Ptr<EnergyHarvester> to the end of this container.
void Add (std::string harvesterName)
Append a single Ptr<EnergyHarvester> referred to by its object name to the end of this container.
Iterator Begin (void) const
Get an iterator which refers to the first EnergyHarvester pointer in the container.
void Clear (void)
Removes all elements in the container.
Iterator End (void) const
Get an iterator which refers to the last EnergyHarvester pointer in the container.
Ptr< EnergyHarvester > Get (uint32_t i) const
Get the i-th Ptr<EnergyHarvester> stored in this container.
uint32_t GetN (void) const
Get the number of Ptr<EnergyHarvester> stored in this container.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Calls Object::Initialize () for all EnergySource objects.
Private Attributes
std::vector< Ptr< EnergyHarvester > > m_harvesters
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Holds a vector of ns3::EnergyHarvester pointers.
EnergyHarvesterContainer returns a list of EnergyHarvester pointers installed on a node. Users can use this list to access EnergyHarvester objects to obtain the total energy harvested on a node easily.
See also
NetDeviceContainer
Definition at line 45 of file energy-harvester-container.h.
Member Typedef Documentation
Iterator
typedef std::vector< Ptr<EnergyHarvester> >::const_iterator ns3::EnergyHarvesterContainer::Iterator
Definition at line 48 of file energy-harvester-container.h.
Constructor & Destructor Documentation
EnergyHarvesterContainer() [1/4]
ns3::EnergyHarvesterContainer::EnergyHarvesterContainer ()
Creates an empty EnergyHarvesterContainer.
Definition at line 44 of file energy-harvester-container.cc.
References NS_LOG_FUNCTION.
~EnergyHarvesterContainer()
ns3::EnergyHarvesterContainer::~EnergyHarvesterContainer ()
Definition at line 49 of file energy-harvester-container.cc.
References NS_LOG_FUNCTION.
EnergyHarvesterContainer() [2/4]
ns3::EnergyHarvesterContainer::EnergyHarvesterContainer (Ptr< EnergyHarvester > harvester)
Parameters
harvester Pointer to an EnergyHarvester.
Creates a EnergyHarvesterContainer with exactly one EnergyHarvester previously instantiated.
Definition at line 54 of file energy-harvester-container.cc.
References m_harvesters, NS_ASSERT, and NS_LOG_FUNCTION.
EnergyHarvesterContainer() [3/4]
ns3::EnergyHarvesterContainer::EnergyHarvesterContainer (std::string harvesterName)
Parameters
harvesterName Name of EnergyHarvester.
Creates an EnergyHarvesterContainer with exactly one EnergyHarvester previously instantiated and assigned a name using the Object name service. This EnergyHarvester is specified by its assigned name.
Definition at line 61 of file energy-harvester-container.cc.
References m_harvesters, NS_ASSERT, and NS_LOG_FUNCTION.
EnergyHarvesterContainer() [4/4]
ns3::EnergyHarvesterContainer::EnergyHarvesterContainer (const EnergyHarvesterContainer & a, const EnergyHarvesterContainer & b)
Parameters
a A EnergyHarvesterContainer.
b Another EnergyHarvesterContainer.
Creates a EnergyHarvesterContainer by concatenating EnergyHarvesterContainer b to EnergyHarvesterContainer a.
Note
Can be used to concatenate 2 Ptr<EnergyHarvester> directly. C++ will be calling EnergyHarvesterContainer constructor with Ptr<EnergyHarvester> first.
Definition at line 69 of file energy-harvester-container.cc.
References Add(), and NS_LOG_FUNCTION.
Member Function Documentation
Add() [1/3]
void ns3::EnergyHarvesterContainer::Add (EnergyHarvesterContainer container)
Parameters
container Another EnergyHarvesterContainer.
Appends the contents of another EnergyHarvesterContainer to the end of this EnergyHarvesterContainer.
Definition at line 106 of file energy-harvester-container.cc.
References Begin(), End(), m_harvesters, and NS_LOG_FUNCTION.
Referenced by EnergyHarvesterContainer(), and ns3::EnergyHarvesterHelper::Install().
Add() [2/3]
void ns3::EnergyHarvesterContainer::Add (Ptr< EnergyHarvester > harvester)
Append a single Ptr<EnergyHarvester> to the end of this container.
Parameters
harvester Pointer to an EnergyHarvester.
Definition at line 116 of file energy-harvester-container.cc.
References m_harvesters, NS_ASSERT, and NS_LOG_FUNCTION.
Add() [3/3]
void ns3::EnergyHarvesterContainer::Add (std::string harvesterName)
Append a single Ptr<EnergyHarvester> referred to by its object name to the end of this container.
Parameters
harvesterName Name of EnergyHarvester object.
Definition at line 124 of file energy-harvester-container.cc.
References m_harvesters, NS_ASSERT, and NS_LOG_FUNCTION.
Begin()
EnergyHarvesterContainer::Iterator ns3::EnergyHarvesterContainer::Begin (void) const
Get an iterator which refers to the first EnergyHarvester pointer in the container.
Returns
An iterator which refers to the first EnergyHarvester in container.
EnergyHarvesters can be retrieved from the container in two ways. First, directly by an index into the container, and second, using an iterator. This method is used in the iterator method and is typically used in a for-loop to run through the EnergyHarvesters.
EnergyHarvesterContainer::Iterator i;
for (i = container.Begin (); i != container.End (); ++i)
  {
    (*i)->method ();  // some EnergyHarvester method
  }
Definition at line 78 of file energy-harvester-container.cc.
References m_harvesters, and NS_LOG_FUNCTION.
Referenced by Add().
Clear()
void ns3::EnergyHarvesterContainer::Clear (void)
Removes all elements in the container.
Definition at line 133 of file energy-harvester-container.cc.
References m_harvesters, and NS_LOG_FUNCTION.
DoDispose()
void ns3::EnergyHarvesterContainer::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 145 of file energy-harvester-container.cc.
References m_harvesters.
DoInitialize()
void ns3::EnergyHarvesterContainer::DoInitialize (void) private virtual
Calls Object::Initialize () for all EnergySource objects.
Reimplemented from ns3::Object.
Definition at line 157 of file energy-harvester-container.cc.
References m_harvesters.
End()
EnergyHarvesterContainer::Iterator ns3::EnergyHarvesterContainer::End (void) const
Get an iterator which refers to the last EnergyHarvester pointer in the container.
Returns
An iterator which refers to the last EnergyHarvester in container.
EnergyHarvesters can be retrieved from the container in two ways. First, directly by an index into the container, and second, using an iterator. This method is used in the iterator method and is typically used in a for-loop to run through the EnergyHarvesters.
EnergyHarvesterContainer::Iterator i;
for (i = container.Begin (); i != container.End (); ++i)
  {
    (*i)->method ();  // some EnergyHarvester method
  }
Definition at line 85 of file energy-harvester-container.cc.
References m_harvesters, and NS_LOG_FUNCTION.
Referenced by Add().
Get()
Ptr< EnergyHarvester > ns3::EnergyHarvesterContainer::Get (uint32_t i) const
Get the i-th Ptr<EnergyHarvester> stored in this container.
Parameters
i Index of the requested Ptr<EnergyHarvester>.
Returns
The requested Ptr<EnergyHarvester>.
Definition at line 99 of file energy-harvester-container.cc.
References m_harvesters, and NS_LOG_FUNCTION.
GetN()
uint32_t ns3::EnergyHarvesterContainer::GetN (void) const
Get the number of Ptr<EnergyHarvester> stored in this container.
Returns
The number of Ptr<EnergyHarvester> stored in this container.
Definition at line 92 of file energy-harvester-container.cc.
References m_harvesters, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::EnergyHarvesterContainer::GetTypeId (void) static
Definition at line 34 of file energy-harvester-container.cc.
References ns3::TypeId::SetParent().
Member Data Documentation
m_harvesters
std::vector< Ptr<EnergyHarvester> > ns3::EnergyHarvesterContainer::m_harvesters private
Definition at line 183 of file energy-harvester-container.h.
Referenced by EnergyHarvesterContainer(), Add(), Begin(), Clear(), DoDispose(), DoInitialize(), End(), Get(), and GetN().
The documentation for this class was generated from the following files:
src/energy/helper/energy-harvester-container.h
src/energy/helper/energy-harvester-container.cc