ns-3: ns3::DsssErrorRateModel Class Reference
ns3::DsssErrorRateModel Class Reference
Wifi Models
an implementation of DSSS error rate model
#include "dsss-error-rate-model.h"
Static Public Member Functions
static double DqpskFunction (double x)
A function DQPSK.
static double GetDsssDbpskSuccessRate (double sinr, uint64_t nbits)
Return the chunk success rate of the differential BPSK.
static double GetDsssDqpskCck11SuccessRate (double sinr, uint64_t nbits)
Return the chunk success rate of the differential encoded QPSK for 11Mbps data rate.
static double GetDsssDqpskCck5_5SuccessRate (double sinr, uint64_t nbits)
Return the chunk success rate of the differential encoded QPSK for 5.5Mbps data rate.
static double GetDsssDqpskSuccessRate (double sinr, uint64_t nbits)
Return the chunk success rate of the differential encoded QPSK.
Static Protected Attributes
static const double WLAN_SIR_IMPOSSIBLE = 0.1
WLAN impossible.
static const double WLAN_SIR_PERFECT = 10.0
WLAN perfect.
Detailed Description
an implementation of DSSS error rate model
The 802.11b modulations:
1 Mbps mode is based on DBPSK. BER is from equation 5.2-69 from John G. Proakis Digital Communications, 2001 edition
2 Mbps model is based on DQPSK. Equation 8 from "Tight bounds and accurate approximations for DQPSK transmission bit error rate", G. Ferrari and G.E. Corazza ELECTRONICS LETTERS, 40(20):1284-1285, September 2004
5.5 Mbps and 11 Mbps are based on equations (18) and (17) from "Properties and performance of the IEEE 802.11b complementarycode-key signal sets", Michael B. Pursley and Thomas C. Royster. IEEE TRANSACTIONS ON COMMUNICATIONS, 57(2):440-449, February 2009.
This model is designed to run with highest accuracy using the GNU Scientific Library (GSL), but if GSL is not installed on the platform, will fall back to (slightly less accurate) Matlab-derived models for the CCK modulation types.
More detailed description and validation can be found in http://www.nsnam.org/~pei/80211b.pdf
Definition at line 77 of file dsss-error-rate-model.h.
Member Function Documentation
DqpskFunction()
double ns3::DsssErrorRateModel::DqpskFunction (double x) static
A function DQPSK.
Parameters
x the input variable
Returns
DQPSK (x)
Definition at line 35 of file dsss-error-rate-model.cc.
References NS_LOG_FUNCTION_NOARGS, and sample-rng-plot::x.
Referenced by GetDsssDqpskSuccessRate().
GetDsssDbpskSuccessRate()
double ns3::DsssErrorRateModel::GetDsssDbpskSuccessRate (double sinr, uint64_t nbits) static
Return the chunk success rate of the differential BPSK.
Parameters
sinr the SINR ratio (not dB) of the chunk
nbits the size of the chunk
Returns
the chunk success rate of the differential BPSK
Definition at line 43 of file dsss-error-rate-model.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::NistErrorRateModel::GetChunkSuccessRate(), and ns3::YansErrorRateModel::GetChunkSuccessRate().
GetDsssDqpskCck11SuccessRate()
double ns3::DsssErrorRateModel::GetDsssDqpskCck11SuccessRate (double sinr, uint64_t nbits) static
Return the chunk success rate of the differential encoded QPSK for 11Mbps data rate.
Parameters
sinr the SINR ratio (not dB) of the chunk
nbits the size of the chunk
Returns
the chunk success rate of the differential encoded QPSK for
Definition at line 95 of file dsss-error-rate-model.cc.
References min, NS_LOG_DEBUG, NS_LOG_FUNCTION_NOARGS, NS_LOG_WARN, WLAN_SIR_IMPOSSIBLE, and WLAN_SIR_PERFECT.
Referenced by ns3::NistErrorRateModel::GetChunkSuccessRate(), and ns3::YansErrorRateModel::GetChunkSuccessRate().
GetDsssDqpskCck5_5SuccessRate()
double ns3::DsssErrorRateModel::GetDsssDqpskCck5_5SuccessRate (double sinr, uint64_t nbits) static
Return the chunk success rate of the differential encoded QPSK for 5.5Mbps data rate.
Parameters
sinr the SINR ratio (not dB) of the chunk
nbits the size of the chunk
Returns
the chunk success rate of the differential encoded QPSK for
Definition at line 61 of file dsss-error-rate-model.cc.
References min, NS_LOG_FUNCTION_NOARGS, NS_LOG_WARN, WLAN_SIR_IMPOSSIBLE, and WLAN_SIR_PERFECT.
Referenced by ns3::NistErrorRateModel::GetChunkSuccessRate(), and ns3::YansErrorRateModel::GetChunkSuccessRate().
GetDsssDqpskSuccessRate()
double ns3::DsssErrorRateModel::GetDsssDqpskSuccessRate (double sinr, uint64_t nbits) static
Return the chunk success rate of the differential encoded QPSK.
Parameters
sinr the SINR ratio (not dB) of the chunk
nbits the size of the chunk
Returns
the chunk success rate of the differential encoded QPSK.
Definition at line 52 of file dsss-error-rate-model.cc.
References DqpskFunction(), and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::NistErrorRateModel::GetChunkSuccessRate(), and ns3::YansErrorRateModel::GetChunkSuccessRate().
Member Data Documentation
WLAN_SIR_IMPOSSIBLE
const double ns3::DsssErrorRateModel::WLAN_SIR_IMPOSSIBLE = 0.1 static protected
WLAN impossible.
Definition at line 136 of file dsss-error-rate-model.h.
Referenced by GetDsssDqpskCck11SuccessRate(), and GetDsssDqpskCck5_5SuccessRate().
WLAN_SIR_PERFECT
const double ns3::DsssErrorRateModel::WLAN_SIR_PERFECT = 10.0 static protected
WLAN perfect.
Definition at line 134 of file dsss-error-rate-model.h.
Referenced by GetDsssDqpskCck11SuccessRate(), and GetDsssDqpskCck5_5SuccessRate().
The documentation for this class was generated from the following files:
src/wifi/model/dsss-error-rate-model.h
src/wifi/model/dsss-error-rate-model.cc