ns-3: ns3::lorawan::LoraPacketTracker Class Reference
ns3::lorawan::LoraPacketTracker Class Reference
#include "lora-packet-tracker.h"
Public Member Functions
LoraPacketTracker ()
~LoraPacketTracker ()
std::string CountMacPacketsGlobally (Time startTime, Time stopTime)
Count packets to evaluate the global performance at MAC level of the whole network.
std::string CountMacPacketsGloballyCpsr (Time startTime, Time stopTime)
Count packets to evaluate the global performance at MAC level of the whole network.
std::string CountMacPacketsPerGw (Time startTime, Time stopTime, int systemId)
Count packets to evaluate the performance at MAC level of a specific gateway.
std::vector< int > CountPhyPacketsPerGw (Time startTime, Time stopTime, int systemId)
Count packets to evaluate the performance at PHY level of a specific gateway.
std::string CountRetransmissions (Time startTime, Time stopTime)
Count the number of retransmissions that were needed to correctly deliver a packet and receive the corresponding acknowledgment.
void InterferenceCallback (Ptr< Packet const > packet, uint32_t systemId)
bool IsUplink (Ptr< Packet const > packet)
void LostBecauseTxCallback (Ptr< Packet const > packet, uint32_t systemId)
void MacGwReceptionCallback (Ptr< Packet const > packet)
void MacTransmissionCallback (Ptr< Packet const > packet)
void NoMoreReceiversCallback (Ptr< Packet const > packet, uint32_t systemId)
void PacketReceptionCallback (Ptr< Packet const > packet, uint32_t systemId)
std::string PrintMacPacketsPerGw (Time startTime, Time stopTime, int systemId)
Count packets to evaluate the performance at MAC level of a specific gateway.
std::string PrintPhyPacketsPerGw (Time startTime, Time stopTime, int systemId)
Count packets to evaluate the performance at PHY level of a specific gateway.
void RequiredTransmissionsCallback (uint8_t reqTx, bool success, Time firstAttempt, Ptr< Packet > packet)
void TransmissionCallback (Ptr< Packet const > packet, uint32_t systemId)
void UnderSensitivityCallback (Ptr< Packet const > packet, uint32_t systemId)
Private Attributes
MacPacketData m_macPacketTracker
PhyPacketData m_packetTracker
RetransmissionData m_reTransmissionTracker
Detailed Description
Definition at line 73 of file lora-packet-tracker.h.
Constructor & Destructor Documentation
LoraPacketTracker()
ns3::lorawan::LoraPacketTracker::LoraPacketTracker ()
Definition at line 32 of file lora-packet-tracker.cc.
References NS_LOG_FUNCTION.
~LoraPacketTracker()
ns3::lorawan::LoraPacketTracker::~LoraPacketTracker ()
Definition at line 37 of file lora-packet-tracker.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CountMacPacketsGlobally()
std::string ns3::lorawan::LoraPacketTracker::CountMacPacketsGlobally (Time startTime, Time stopTime)
Count packets to evaluate the global performance at MAC level of the whole network.
In this case, a MAC layer packet is labeled as successful if it was successful at at least one of the available gateways.
This returns a string containing the number of sent packets and the number of packets that were received by at least one gateway.
Definition at line 352 of file lora-packet-tracker.cc.
References m_macPacketTracker, NS_LOG_FUNCTION, startTime, and stopTime.
Referenced by ns3::lorawan::LoraHelper::DoPrintGlobalPerformance().
CountMacPacketsGloballyCpsr()
std::string ns3::lorawan::LoraPacketTracker::CountMacPacketsGloballyCpsr (Time startTime, Time stopTime)
Count packets to evaluate the global performance at MAC level of the whole network.
In this case, a MAC layer packet is labeled as successful if it was successful at at least one of the available gateways, and if the corresponding acknowledgment was correctly delivered at the device.
This returns a string containing the number of sent packets and the number of packets that generated a successful acknowledgment.
Definition at line 377 of file lora-packet-tracker.cc.
References m_reTransmissionTracker, NS_LOG_DEBUG, NS_LOG_FUNCTION, startTime, and stopTime.
CountMacPacketsPerGw()
std::string ns3::lorawan::LoraPacketTracker::CountMacPacketsPerGw (Time startTime, Time stopTime, int systemId)
Count packets to evaluate the performance at MAC level of a specific gateway.
CountPhyPacketsPerGw()
std::vector< int > ns3::lorawan::LoraPacketTracker::CountPhyPacketsPerGw (Time startTime, Time stopTime, int systemId)
Count packets to evaluate the performance at PHY level of a specific gateway.
Definition at line 221 of file lora-packet-tracker.cc.
References ns3::lorawan::INTERFERED, ns3::lorawan::LOST_BECAUSE_TX, m_packetTracker, ns3::lorawan::NO_MORE_RECEIVERS, NS_LOG_DEBUG, ns3::lorawan::RECEIVED, startTime, stopTime, ns3::lorawan::UNDER_SENSITIVITY, and ns3::lorawan::UNSET.
CountRetransmissions()
std::string ns3::lorawan::LoraPacketTracker::CountRetransmissions (Time startTime, Time stopTime)
Count the number of retransmissions that were needed to correctly deliver a packet and receive the corresponding acknowledgment.
InterferenceCallback()
void ns3::lorawan::LoraPacketTracker::InterferenceCallback (Ptr< Packet const > packet, uint32_t systemId)
Definition at line 147 of file lora-packet-tracker.cc.
References ns3::lorawan::INTERFERED, IsUplink(), m_packetTracker, and NS_LOG_INFO.
Referenced by ns3::lorawan::LoraHelper::Install().
IsUplink()
bool ns3::lorawan::LoraPacketTracker::IsUplink (Ptr< Packet const > packet)
Definition at line 206 of file lora-packet-tracker.cc.
References ns3::lorawan::LorawanMacHeader::IsUplink(), NS_LOG_FUNCTION, and ns3::Packet::RemoveHeader().
Referenced by InterferenceCallback(), LostBecauseTxCallback(), MacGwReceptionCallback(), MacTransmissionCallback(), NoMoreReceiversCallback(), PacketReceptionCallback(), TransmissionCallback(), and UnderSensitivityCallback().
LostBecauseTxCallback()
void ns3::lorawan::LoraPacketTracker::LostBecauseTxCallback (Ptr< Packet const > packet, uint32_t systemId)
Definition at line 191 of file lora-packet-tracker.cc.
References IsUplink(), ns3::lorawan::LOST_BECAUSE_TX, m_packetTracker, and NS_LOG_INFO.
Referenced by ns3::lorawan::LoraHelper::Install().
MacGwReceptionCallback()
void ns3::lorawan::LoraPacketTracker::MacGwReceptionCallback (Ptr< Packet const > packet)
Definition at line 85 of file lora-packet-tracker.cc.
References ns3::Simulator::GetContext(), IsUplink(), m_macPacketTracker, ns3::Simulator::Now(), NS_ABORT_MSG, and NS_LOG_INFO.
Referenced by ns3::lorawan::LoraHelper::Install().
MacTransmissionCallback()
void ns3::lorawan::LoraPacketTracker::MacTransmissionCallback (Ptr< Packet const > packet)
Definition at line 47 of file lora-packet-tracker.cc.
References ns3::Simulator::GetContext(), IsUplink(), m_macPacketTracker, ns3::Time::Max(), ns3::Simulator::Now(), NS_LOG_INFO, ns3::lorawan::MacPacketStatus::packet, ns3::lorawan::MacPacketStatus::receivedTime, ns3::lorawan::MacPacketStatus::senderId, and ns3::lorawan::MacPacketStatus::sendTime.
Referenced by ns3::lorawan::LoraHelper::Install().
NoMoreReceiversCallback()
void ns3::lorawan::LoraPacketTracker::NoMoreReceiversCallback (Ptr< Packet const > packet, uint32_t systemId)
Definition at line 162 of file lora-packet-tracker.cc.
References IsUplink(), m_packetTracker, ns3::lorawan::NO_MORE_RECEIVERS, and NS_LOG_INFO.
Referenced by ns3::lorawan::LoraHelper::Install().
PacketReceptionCallback()
void ns3::lorawan::LoraPacketTracker::PacketReceptionCallback (Ptr< Packet const > packet, uint32_t systemId)
Definition at line 131 of file lora-packet-tracker.cc.
References IsUplink(), m_packetTracker, NS_LOG_INFO, and ns3::lorawan::RECEIVED.
Referenced by ns3::lorawan::LoraHelper::Install().
PrintMacPacketsPerGw()
std::string ns3::lorawan::LoraPacketTracker::PrintMacPacketsPerGw (Time startTime, Time stopTime, int systemId)
Count packets to evaluate the performance at MAC level of a specific gateway.
PrintPhyPacketsPerGw()
std::string ns3::lorawan::LoraPacketTracker::PrintPhyPacketsPerGw (Time startTime, Time stopTime, int systemId)
Count packets to evaluate the performance at PHY level of a specific gateway.
Definition at line 283 of file lora-packet-tracker.cc.
References ns3::lorawan::INTERFERED, ns3::lorawan::LOST_BECAUSE_TX, m_packetTracker, ns3::lorawan::NO_MORE_RECEIVERS, NS_LOG_DEBUG, ns3::lorawan::RECEIVED, startTime, stopTime, ns3::lorawan::UNDER_SENSITIVITY, and ns3::lorawan::UNSET.
Referenced by ns3::lorawan::LoraHelper::DoPrintPhyPerformance().
RequiredTransmissionsCallback()
void ns3::lorawan::LoraPacketTracker::RequiredTransmissionsCallback (uint8_t reqTx, bool success, Time firstAttempt, Ptr< Packet > packet)
Definition at line 65 of file lora-packet-tracker.cc.
References ns3::lorawan::RetransmissionStatus::finishTime, ns3::lorawan::RetransmissionStatus::firstAttempt, ns3::Time::GetSeconds(), m_reTransmissionTracker, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_INFO, ns3::lorawan::RetransmissionStatus::reTxAttempts, and ns3::lorawan::RetransmissionStatus::successful.
Referenced by ns3::lorawan::LoraHelper::Install().
TransmissionCallback()
void ns3::lorawan::LoraPacketTracker::TransmissionCallback (Ptr< Packet const > packet, uint32_t systemId)
Definition at line 113 of file lora-packet-tracker.cc.
References IsUplink(), m_packetTracker, ns3::Simulator::Now(), NS_LOG_INFO, ns3::lorawan::PacketStatus::packet, ns3::lorawan::PacketStatus::senderId, and ns3::lorawan::PacketStatus::sendTime.
Referenced by ns3::lorawan::LoraHelper::Install().
UnderSensitivityCallback()
void ns3::lorawan::LoraPacketTracker::UnderSensitivityCallback (Ptr< Packet const > packet, uint32_t systemId)
Definition at line 176 of file lora-packet-tracker.cc.
References IsUplink(), m_packetTracker, NS_LOG_INFO, and ns3::lorawan::UNDER_SENSITIVITY.
Referenced by ns3::lorawan::LoraHelper::Install().
Member Data Documentation
m_macPacketTracker
MacPacketData ns3::lorawan::LoraPacketTracker::m_macPacketTracker private
Definition at line 164 of file lora-packet-tracker.h.
Referenced by CountMacPacketsGlobally(), MacGwReceptionCallback(), and MacTransmissionCallback().
m_packetTracker
PhyPacketData ns3::lorawan::LoraPacketTracker::m_packetTracker private
Definition at line 163 of file lora-packet-tracker.h.
Referenced by CountPhyPacketsPerGw(), InterferenceCallback(), LostBecauseTxCallback(), NoMoreReceiversCallback(), PacketReceptionCallback(), PrintPhyPacketsPerGw(), TransmissionCallback(), and UnderSensitivityCallback().
m_reTransmissionTracker
RetransmissionData ns3::lorawan::LoraPacketTracker::m_reTransmissionTracker private
Definition at line 165 of file lora-packet-tracker.h.
Referenced by CountMacPacketsGloballyCpsr(), and RequiredTransmissionsCallback().
The documentation for this class was generated from the following files:
src/lorawan/helper/lora-packet-tracker.h
src/lorawan/helper/lora-packet-tracker.cc