ns-3: ns3::SqliteDataOutput::SqliteOutputCallback Class Reference
ns3::SqliteDataOutput::SqliteOutputCallback Class Reference
Statistics » Data Output
Class to generate OMNeT output.
Public Member Functions
SqliteOutputCallback (const Ptr< SQLiteOutput > &db, std::string run)
Constructor.
~SqliteOutputCallback ()
Destructor.
void OutputSingleton (std::string key, std::string variable, double val)
Generates a single data output.
void OutputSingleton (std::string key, std::string variable, int val)
Generates a single data output.
void OutputSingleton (std::string key, std::string variable, std::string val)
Generates a single data output.
void OutputSingleton (std::string key, std::string variable, Time val)
Generates a single data output.
void OutputSingleton (std::string key, std::string variable, uint32_t val)
Generates a single data output.
void OutputStatistic (std::string key, std::string variable, const StatisticalSummary *statSum)
Generates data statistics.
Public Member Functions inherited from ns3::DataOutputCallback
virtual ~DataOutputCallback ()
Destructor.
Private Attributes
Ptr< SQLiteOutput > m_db
Db.
sqlite3_stmt * m_insertSingletonStatement
std::string m_runLabel
Run label.
Detailed Description
Class to generate OMNeT output.
Definition at line 61 of file sqlite-data-output.h.
Constructor & Destructor Documentation
SqliteOutputCallback()
ns3::SqliteDataOutput::SqliteOutputCallback::SqliteOutputCallback (const Ptr< SQLiteOutput > & db, std::string run)
Constructor.
Parameters
owner pointer to the instance this object belongs to
run experiment descriptor
Definition at line 129 of file sqlite-data-output.cc.
References m_db, m_insertSingletonStatement, m_runLabel, and NS_LOG_FUNCTION.
~SqliteOutputCallback()
ns3::SqliteDataOutput::SqliteOutputCallback::~SqliteOutputCallback ()
Destructor.
Definition at line 145 of file sqlite-data-output.cc.
Member Function Documentation
OutputSingleton() [1/5]
void ns3::SqliteDataOutput::SqliteOutputCallback::OutputSingleton (std::string key, std::string variable, double val) virtual
Generates a single data output.
Parameters
key the SQL key to use
variable the variable name
val the value
Implements ns3::DataOutputCallback.
Definition at line 209 of file sqlite-data-output.cc.
References NS_LOG_FUNCTION, and anonymous_namespace{print-introspected-doxygen.cc}::variable.
OutputSingleton() [2/5]
void ns3::SqliteDataOutput::SqliteOutputCallback::OutputSingleton (std::string key, std::string variable, int val) virtual
Generates a single data output.
Parameters
key the SQL key to use
variable the variable name
val the value
Implements ns3::DataOutputCallback.
Definition at line 182 of file sqlite-data-output.cc.
References NS_LOG_FUNCTION, and anonymous_namespace{print-introspected-doxygen.cc}::variable.
OutputSingleton() [3/5]
void ns3::SqliteDataOutput::SqliteOutputCallback::OutputSingleton (std::string key, std::string variable, std::string val) virtual
Generates a single data output.
Parameters
key the SQL key to use
variable the variable name
val the value
Implements ns3::DataOutputCallback.
Definition at line 223 of file sqlite-data-output.cc.
References NS_LOG_FUNCTION, and anonymous_namespace{print-introspected-doxygen.cc}::variable.
OutputSingleton() [4/5]
void ns3::SqliteDataOutput::SqliteOutputCallback::OutputSingleton (std::string key, std::string variable, Time val) virtual
Generates a single data output.
Parameters
key the SQL key to use
variable the variable name
val the value
Implements ns3::DataOutputCallback.
Definition at line 237 of file sqlite-data-output.cc.
References ns3::Time::GetTimeStep(), NS_LOG_FUNCTION, and anonymous_namespace{print-introspected-doxygen.cc}::variable.
OutputSingleton() [5/5]
void ns3::SqliteDataOutput::SqliteOutputCallback::OutputSingleton (std::string key, std::string variable, uint32_t val) virtual
Generates a single data output.
Parameters
key the SQL key to use
variable the variable name
val the value
Implements ns3::DataOutputCallback.
Definition at line 195 of file sqlite-data-output.cc.
References NS_LOG_FUNCTION, and anonymous_namespace{print-introspected-doxygen.cc}::variable.
OutputStatistic()
void ns3::SqliteDataOutput::SqliteOutputCallback::OutputStatistic (std::string key, std::string variable, const StatisticalSummary * statSum) virtual
Generates data statistics.
Parameters
key the SQL key to use
variable the variable name
statSum the stats to print
Implements ns3::DataOutputCallback.
Definition at line 151 of file sqlite-data-output.cc.
References ns3::StatisticalSummary::getCount(), ns3::StatisticalSummary::getMax(), ns3::StatisticalSummary::getMin(), ns3::StatisticalSummary::getSqrSum(), ns3::StatisticalSummary::getStddev(), ns3::StatisticalSummary::getSum(), ns3::isNaN(), NS_LOG_FUNCTION, and anonymous_namespace{print-introspected-doxygen.cc}::variable.
Member Data Documentation
m_db
Ptr<SQLiteOutput> ns3::SqliteDataOutput::SqliteOutputCallback::m_db private
Db.
Definition at line 137 of file sqlite-data-output.h.
Referenced by SqliteOutputCallback().
m_insertSingletonStatement
sqlite3_stmt* ns3::SqliteDataOutput::SqliteOutputCallback::m_insertSingletonStatement private
Definition at line 141 of file sqlite-data-output.h.
Referenced by SqliteOutputCallback().
m_runLabel
std::string ns3::SqliteDataOutput::SqliteOutputCallback::m_runLabel private
Run label.
Definition at line 138 of file sqlite-data-output.h.
Referenced by SqliteOutputCallback().
The documentation for this class was generated from the following files:
src/stats/model/sqlite-data-output.h
src/stats/model/sqlite-data-output.cc