ns-3: ns3::E2eStatsHeader Class Reference
ns3::E2eStatsHeader Class Reference
Applications
Header with a sequence, a timestamp, and a "size" attribute.
#include "e2e-stats-header.h"
Public Member Functions
E2eStatsHeader ()
SizeHeader constructor.
virtual ~E2eStatsHeader () override
~SizeHeader
virtual uint32_t Deserialize (Buffer::Iterator start) override
virtual TypeId GetInstanceTypeId (void) const override
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize (void) const override
uint64_t GetSize (void) const
Get the size information that the header is carrying.
virtual void Print (std::ostream &os) const override
virtual void Serialize (Buffer::Iterator start) const override
void SetSize (uint64_t size)
Set the size information that the header will carry.
Public Member Functions inherited from ns3::SeqTsHeader
SeqTsHeader ()
uint32_t GetSeq (void) const
Time GetTs (void) const
void SetSeq (uint32_t seq)
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::SeqTsHeader
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint64_t m_size {0}
The 'size' information that the header is carrying.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Header with a sequence, a timestamp, and a "size" attribute.
Sometimes, you would need an header that not only track an application sequence number, or an application timestamp, but also track how big are these application packets.
This header extends SeqTsHeader, adding space to store the information about the size of these packets.
When you will use a protocol like TCP, you will find the answer to the question "isn't SeqTsHeader enough?".
Definition at line 38 of file e2e-stats-header.h.
Constructor & Destructor Documentation
E2eStatsHeader()
ns3::E2eStatsHeader::E2eStatsHeader ()
SizeHeader constructor.
Definition at line 29 of file e2e-stats-header.cc.
References NS_LOG_FUNCTION.
~E2eStatsHeader()
virtual ns3::E2eStatsHeader::~E2eStatsHeader () inline override virtual
~SizeHeader
Nothing much to add here
Definition at line 57 of file e2e-stats-header.h.
Member Function Documentation
Deserialize()
uint32_t ns3::E2eStatsHeader::Deserialize (Buffer::Iterator start) override virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Reimplemented from ns3::SeqTsHeader.
Definition at line 77 of file e2e-stats-header.cc.
References ns3::SeqTsHeader::Deserialize(), GetSerializedSize(), m_size, NS_LOG_FUNCTION, ns3::Buffer::Iterator::ReadNtohU64(), and visualizer.core::start().
GetInstanceTypeId()
TypeId ns3::E2eStatsHeader::GetInstanceTypeId (void) const override virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Reimplemented from ns3::SeqTsHeader.
Definition at line 47 of file e2e-stats-header.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::E2eStatsHeader::GetSerializedSize (void) const override virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Reimplemented from ns3::SeqTsHeader.
Definition at line 61 of file e2e-stats-header.cc.
References ns3::SeqTsHeader::GetSerializedSize(), and NS_LOG_FUNCTION.
Referenced by Deserialize(), ns3::BulkSendApplication::SendData(), and ns3::OnOffApplication::SendPacket().
GetSize()
uint64_t ns3::E2eStatsHeader::GetSize (void) const inline
Get the size information that the header is carrying.
Returns
the size
Definition at line 73 of file e2e-stats-header.h.
References m_size.
Referenced by ns3::PacketSink::PacketReceived().
GetTypeId()
TypeId ns3::E2eStatsHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 36 of file e2e-stats-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::E2eStatsHeader::Print (std::ostream & os) const override virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Reimplemented from ns3::SeqTsHeader.
Definition at line 53 of file e2e-stats-header.cc.
References m_size, NS_LOG_FUNCTION, and ns3::SeqTsHeader::Print().
Serialize()
void ns3::E2eStatsHeader::Serialize (Buffer::Iterator start) const override virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Reimplemented from ns3::SeqTsHeader.
Definition at line 68 of file e2e-stats-header.cc.
References m_size, NS_LOG_FUNCTION, ns3::SeqTsHeader::Serialize(), visualizer.core::start(), and ns3::Buffer::Iterator::WriteHtonU64().
SetSize()
void ns3::E2eStatsHeader::SetSize (uint64_t size) inline
Set the size information that the header will carry.
Parameters
size the size
Definition at line 65 of file e2e-stats-header.h.
References m_size.
Referenced by ns3::BulkSendApplication::SendData(), and ns3::OnOffApplication::SendPacket().
Member Data Documentation
m_size
uint64_t ns3::E2eStatsHeader::m_size {0} private
The 'size' information that the header is carrying.
Definition at line 86 of file e2e-stats-header.h.
Referenced by Deserialize(), GetSize(), Print(), Serialize(), and SetSize().
The documentation for this class was generated from the following files:
src/applications/model/e2e-stats-header.h
src/applications/model/e2e-stats-header.cc