ns-3: BasicTracedCallbackTestCase Class Reference
BasicTracedCallbackTestCase Class Reference
Public Member Functions
BasicTracedCallbackTestCase ()
virtual ~BasicTracedCallbackTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CbOne (uint8_t a, double b)
void CbTwo (uint8_t a, double b)
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
bool m_one
bool m_two
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 25 of file traced-callback-test-suite.cc.
Constructor & Destructor Documentation
BasicTracedCallbackTestCase()
BasicTracedCallbackTestCase::BasicTracedCallbackTestCase ()
Definition at line 42 of file traced-callback-test-suite.cc.
~BasicTracedCallbackTestCase()
virtual BasicTracedCallbackTestCase::~BasicTracedCallbackTestCase () inline virtual
Definition at line 29 of file traced-callback-test-suite.cc.
Member Function Documentation
CbOne()
void BasicTracedCallbackTestCase::CbOne (uint8_t a, double b) private
Definition at line 47 of file traced-callback-test-suite.cc.
References m_one, and NS_UNUSED.
Referenced by DoRun().
CbTwo()
void BasicTracedCallbackTestCase::CbTwo (uint8_t a, double b) private
Definition at line 55 of file traced-callback-test-suite.cc.
References m_two, and NS_UNUSED.
Referenced by DoRun().
DoRun()
void BasicTracedCallbackTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 63 of file traced-callback-test-suite.cc.
References CbOne(), CbTwo(), ns3::TracedCallback< T1, T2, T3, T4, T5, T6, T7, T8 >::ConnectWithoutContext(), ns3::TracedCallback< T1, T2, T3, T4, T5, T6, T7, T8 >::DisconnectWithoutContext(), m_one, m_two, ns3::MakeCallback(), and NS_TEST_ASSERT_MSG_EQ.
Member Data Documentation
m_one
bool BasicTracedCallbackTestCase::m_one private
Definition at line 38 of file traced-callback-test-suite.cc.
Referenced by CbOne(), and DoRun().
m_two
bool BasicTracedCallbackTestCase::m_two private
Definition at line 39 of file traced-callback-test-suite.cc.
Referenced by CbTwo(), and DoRun().
The documentation for this class was generated from the following file:
src/core/test/traced-callback-test-suite.cc