ns-3: ns3::tests::EventGarbageCollectorTestCase Class Reference
ns3::tests::EventGarbageCollectorTestCase Class Reference
Test suites | Core » Core module tests » EventGarbageCollector test suite
Public Member Functions
EventGarbageCollectorTestCase ()
Constructor.
virtual ~EventGarbageCollectorTestCase ()
Destructor.
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void EventGarbageCollectorCallback ()
Callback to record event invocations.
Private Attributes
int m_counter
Counter to trigger deletion of events.
EventGarbageCollector * m_events
Object under test.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Event garbage collector test.
Definition at line 46 of file event-garbage-collector-test-suite.cc.
Constructor & Destructor Documentation
EventGarbageCollectorTestCase()
ns3::tests::EventGarbageCollectorTestCase::EventGarbageCollectorTestCase ()
Constructor.
Definition at line 63 of file event-garbage-collector-test-suite.cc.
~EventGarbageCollectorTestCase()
ns3::tests::EventGarbageCollectorTestCase::~EventGarbageCollectorTestCase () virtual
Destructor.
Definition at line 67 of file event-garbage-collector-test-suite.cc.
Member Function Documentation
DoRun()
void ns3::tests::EventGarbageCollectorTestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 82 of file event-garbage-collector-test-suite.cc.
References ns3::Simulator::Destroy(), EventGarbageCollectorCallback(), m_counter, m_events, sample-rng-plot::n, ns3::Simulator::Now(), NS_TEST_EXPECT_MSG_EQ, ns3::Simulator::Run(), ns3::Simulator::Schedule(), and ns3::EventGarbageCollector::Track().
EventGarbageCollectorCallback()
void ns3::tests::EventGarbageCollectorTestCase::EventGarbageCollectorCallback () private
Callback to record event invocations.
Definition at line 71 of file event-garbage-collector-test-suite.cc.
References m_counter, and m_events.
Referenced by DoRun().
Member Data Documentation
m_counter
int ns3::tests::EventGarbageCollectorTestCase::m_counter private
Counter to trigger deletion of events.
Definition at line 48 of file event-garbage-collector-test-suite.cc.
Referenced by DoRun(), and EventGarbageCollectorCallback().
m_events
EventGarbageCollector* ns3::tests::EventGarbageCollectorTestCase::m_events private
Object under test.
Definition at line 49 of file event-garbage-collector-test-suite.cc.
Referenced by DoRun(), and EventGarbageCollectorCallback().
The documentation for this class was generated from the following file:
src/core/test/event-garbage-collector-test-suite.cc