ns-3: BasicCallbackTestCase Class Reference
BasicCallbackTestCase Class Reference
Public Member Functions
BasicCallbackTestCase ()
virtual ~BasicCallbackTestCase ()
void Target1 (void)
int Target2 (void)
void Target3 (double a)
int Target4 (double a, int b)
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
virtual void DoSetup (void)
Implementation to do any local setup required for this TestCase.
Private Attributes
bool m_test1
bool m_test2
bool m_test3
bool m_test4
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 29 of file callback-test-suite.cc.
Constructor & Destructor Documentation
BasicCallbackTestCase()
BasicCallbackTestCase::BasicCallbackTestCase ()
Definition at line 91 of file callback-test-suite.cc.
~BasicCallbackTestCase()
virtual BasicCallbackTestCase::~BasicCallbackTestCase () inline virtual
Definition at line 33 of file callback-test-suite.cc.
Member Function Documentation
DoRun()
void BasicCallbackTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 108 of file callback-test-suite.cc.
References BasicCallbackTarget5(), BasicCallbackTarget6(), BasicCallbackTarget7(), gBasicCallbackTest5, gBasicCallbackTest6, gBasicCallbackTest7, m_test1, m_test2, m_test3, m_test4, NS_TEST_ASSERT_MSG_EQ, Target1(), Target2(), Target3(), and Target4().
DoSetup()
void BasicCallbackTestCase::DoSetup (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test setup before DoRun is invoked.
Reimplemented from ns3::TestCase.
Definition at line 96 of file callback-test-suite.cc.
References gBasicCallbackTest5, gBasicCallbackTest6, gBasicCallbackTest7, m_test1, m_test2, m_test3, and m_test4.
Target1()
void BasicCallbackTestCase::Target1 (void) inline
Definition at line 36 of file callback-test-suite.cc.
Referenced by DoRun().
Target2()
int BasicCallbackTestCase::Target2 (void) inline
Definition at line 40 of file callback-test-suite.cc.
Referenced by DoRun().
Target3()
void BasicCallbackTestCase::Target3 (double a) inline
Definition at line 45 of file callback-test-suite.cc.
References NS_UNUSED.
Referenced by DoRun().
Target4()
int BasicCallbackTestCase::Target4 (double a, int b) inline
Definition at line 50 of file callback-test-suite.cc.
References NS_UNUSED.
Referenced by DoRun().
Member Data Documentation
m_test1
bool BasicCallbackTestCase::m_test1 private
Definition at line 62 of file callback-test-suite.cc.
Referenced by DoRun(), and DoSetup().
m_test2
bool BasicCallbackTestCase::m_test2 private
Definition at line 63 of file callback-test-suite.cc.
Referenced by DoRun(), and DoSetup().
m_test3
bool BasicCallbackTestCase::m_test3 private
Definition at line 64 of file callback-test-suite.cc.
Referenced by DoRun(), and DoSetup().
m_test4
bool BasicCallbackTestCase::m_test4 private
Definition at line 65 of file callback-test-suite.cc.
Referenced by DoRun(), and DoSetup().
The documentation for this class was generated from the following file:
src/core/test/callback-test-suite.cc