ns-3: ns3::dsr::DsrOptionRerrUnreachHeader Class Reference
ns3::dsr::DsrOptionRerrUnreachHeader Class Reference
DSR Routing
Route Error (RERR) Unreachable node address option Message Format.
#include "dsr-option-header.h"
Public Member Functions
DsrOptionRerrUnreachHeader ()
Constructor.
virtual ~DsrOptionRerrUnreachHeader ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
virtual Alignment GetAlignment () const
Get the Alignment requirement of this option header.
virtual Ipv4Address GetErrorDst () const
Get the error destination ip address.
virtual Ipv4Address GetErrorSrc () const
Get the route error source address.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
Ipv4Address GetOriginalDst () const
Get the unreachable node ip address.
virtual uint8_t GetSalvage () const
Get the salvage value of the packet.
virtual uint32_t GetSerializedSize () const
Get the serialized size of the packet.
Ipv4Address GetUnreachNode () const
Get the unreachable node ip address.
virtual void Print (std::ostream &os) const
Print some information about the packet.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
virtual void SetErrorDst (Ipv4Address errorDstAddress)
Set the error destination ip address.
virtual void SetErrorSrc (Ipv4Address errorSrcAddress)
Set the route error source address.
void SetOriginalDst (Ipv4Address originalDst)
Set the unreachable node ip address.
virtual void SetSalvage (uint8_t salvage)
Set the salvage value of the packet.
void SetUnreachNode (Ipv4Address unreachNode)
Set the unreachable node ip address.
Public Member Functions inherited from ns3::dsr::DsrOptionRerrHeader
DsrOptionRerrHeader ()
Constructor.
virtual ~DsrOptionRerrHeader ()
Destructor.
uint8_t GetErrorType () const
Get the route error type.
void SetErrorType (uint8_t errorType)
Set the route error type.
Public Member Functions inherited from ns3::dsr::DsrOptionHeader
DsrOptionHeader ()
Constructor.
virtual ~DsrOptionHeader ()
Destructor.
uint8_t GetLength () const
Get the option length.
uint8_t GetType () const
Get the type of the option.
void SetLength (uint8_t length)
Set the option length.
void SetType (uint8_t type)
Set the type of the option.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::dsr::DsrOptionRerrHeader
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::dsr::DsrOptionHeader
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Ipv4Address m_errorDstAddress
The error destination address.
Ipv4Address m_errorSrcAddress
The error source address.
uint8_t m_errorType
The error type or route error option.
Ipv4Address m_originalDst
The original destination address.
uint8_t m_salvage
The salavage field.
Ipv4Address m_unreachNode
The unreachable node address.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Route Error (RERR) Unreachable node address option Message Format.
 |      0        |      1        |      2        |      3        |
 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |  Option Type |  Opt Data Len |   Error Type  |Reservd| Salvage|
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                      Error Source Address                     |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                    Error Destination Address                  |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 .                                                               .
 .                    Type-Specific Information                  .
 .                                                               .
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 880 of file dsr-option-header.h.
Constructor & Destructor Documentation
DsrOptionRerrUnreachHeader()
ns3::dsr::DsrOptionRerrUnreachHeader::DsrOptionRerrUnreachHeader ()
Constructor.
Definition at line 802 of file dsr-option-header.cc.
References ns3::dsr::DsrOptionRerrHeader::SetErrorType(), ns3::dsr::DsrOptionHeader::SetLength(), and ns3::dsr::DsrOptionHeader::SetType().
~DsrOptionRerrUnreachHeader()
ns3::dsr::DsrOptionRerrUnreachHeader::~DsrOptionRerrUnreachHeader () virtual
Destructor.
Definition at line 810 of file dsr-option-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::dsr::DsrOptionRerrUnreachHeader::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start Buffer iterator
Returns
size of the packet
Reimplemented from ns3::dsr::DsrOptionRerrHeader.
Definition at line 891 of file dsr-option-header.cc.
References GetSerializedSize(), m_errorDstAddress, m_errorSrcAddress, m_originalDst, m_salvage, m_unreachNode, ns3::ReadFrom(), ns3::Buffer::Iterator::ReadU8(), ns3::dsr::DsrOptionRerrHeader::SetErrorType(), ns3::dsr::DsrOptionHeader::SetLength(), ns3::dsr::DsrOptionHeader::SetType(), and visualizer.core::start().
GetAlignment()
DsrOptionHeader::Alignment ns3::dsr::DsrOptionRerrUnreachHeader::GetAlignment () const virtual
Get the Alignment requirement of this option header.
Returns
The required alignment
Reimplemented from ns3::dsr::DsrOptionRerrHeader.
Definition at line 907 of file dsr-option-header.cc.
GetErrorDst()
Ipv4Address ns3::dsr::DsrOptionRerrUnreachHeader::GetErrorDst () const virtual
Get the error destination ip address.
Returns
The error destination address
Reimplemented from ns3::dsr::DsrOptionRerrHeader.
Definition at line 839 of file dsr-option-header.cc.
References m_errorDstAddress.
Referenced by ns3::dsr::DsrRouting::CheckSendBuffer(), DsrRerrHeaderTest::DoRun(), ns3::dsr::DsrRouting::ForwardErrPacket(), ns3::dsr::DsrOptionRreq::Process(), ns3::dsr::DsrOptionRerr::Process(), ns3::dsr::DsrRouting::SendErrorRequest(), and ns3::dsr::DsrRouting::SendPacketFromBuffer().
GetErrorSrc()
Ipv4Address ns3::dsr::DsrOptionRerrUnreachHeader::GetErrorSrc () const virtual
Get the route error source address.
Returns
The error source address
Reimplemented from ns3::dsr::DsrOptionRerrHeader.
Definition at line 829 of file dsr-option-header.cc.
References m_errorSrcAddress.
Referenced by ns3::dsr::DsrRouting::CheckSendBuffer(), DsrRerrHeaderTest::DoRun(), ns3::dsr::DsrRouting::ForwardErrPacket(), ns3::dsr::DsrOptionRreq::Process(), ns3::dsr::DsrOptionRerr::Process(), ns3::dsr::DsrRouting::SendErrorRequest(), and ns3::dsr::DsrRouting::SendPacketFromBuffer().
GetInstanceTypeId()
TypeId ns3::dsr::DsrOptionRerrUnreachHeader::GetInstanceTypeId () const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::dsr::DsrOptionRerrHeader.
Definition at line 797 of file dsr-option-header.cc.
References GetTypeId().
GetOriginalDst()
Ipv4Address ns3::dsr::DsrOptionRerrUnreachHeader::GetOriginalDst () const
Get the unreachable node ip address.
Returns
The unreachable ip address
Definition at line 859 of file dsr-option-header.cc.
References m_originalDst.
Referenced by ns3::dsr::DsrRouting::SendErrorRequest(), and ns3::dsr::DsrRouting::SendPacketFromBuffer().
GetSalvage()
uint8_t ns3::dsr::DsrOptionRerrUnreachHeader::GetSalvage () const virtual
Get the salvage value of the packet.
Returns
The salvage value of the packet
Reimplemented from ns3::dsr::DsrOptionRerrHeader.
Definition at line 819 of file dsr-option-header.cc.
References m_salvage.
Referenced by ns3::dsr::DsrRouting::CheckSendBuffer(), DsrRerrHeaderTest::DoRun(), ns3::dsr::DsrOptionRreq::Process(), ns3::dsr::DsrRouting::SendErrorRequest(), and ns3::dsr::DsrRouting::SendPacketFromBuffer().
GetSerializedSize()
uint32_t ns3::dsr::DsrOptionRerrUnreachHeader::GetSerializedSize () const virtual
Get the serialized size of the packet.
Returns
size
Reimplemented from ns3::dsr::DsrOptionRerrHeader.
Definition at line 872 of file dsr-option-header.cc.
Referenced by Deserialize(), and ns3::dsr::DsrOptionRerr::Process().
GetTypeId()
TypeId ns3::dsr::DsrOptionRerrUnreachHeader::GetTypeId () static
Get the type identificator.
Returns
type identificator
Definition at line 787 of file dsr-option-header.cc.
References ns3::TypeId::AddConstructor().
Referenced by GetInstanceTypeId().
GetUnreachNode()
Ipv4Address ns3::dsr::DsrOptionRerrUnreachHeader::GetUnreachNode () const
Get the unreachable node ip address.
Returns
The unreachable ip address
Definition at line 849 of file dsr-option-header.cc.
References m_unreachNode.
Referenced by ns3::dsr::DsrRouting::CheckSendBuffer(), DsrRerrHeaderTest::DoRun(), ns3::dsr::DsrOptionRreq::Process(), ns3::dsr::DsrOptionRerr::Process(), ns3::dsr::DsrRouting::SendErrorRequest(), and ns3::dsr::DsrRouting::SendPacketFromBuffer().
Print()
void ns3::dsr::DsrOptionRerrUnreachHeader::Print (std::ostream & os) const virtual
Print some information about the packet.
Parameters
os output stream
Returns
info about this packet
Reimplemented from ns3::dsr::DsrOptionRerrHeader.
Definition at line 864 of file dsr-option-header.cc.
References ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrOptionHeader::GetType(), m_errorDstAddress, m_errorSrcAddress, m_errorType, m_salvage, and m_unreachNode.
Serialize()
void ns3::dsr::DsrOptionRerrUnreachHeader::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start Buffer iterator
Reimplemented from ns3::dsr::DsrOptionRerrHeader.
Definition at line 877 of file dsr-option-header.cc.
References ns3::dsr::DsrOptionRerrHeader::GetErrorType(), ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrOptionHeader::GetType(), m_errorDstAddress, m_errorSrcAddress, m_originalDst, m_salvage, m_unreachNode, visualizer.core::start(), ns3::WriteTo(), and ns3::Buffer::Iterator::WriteU8().
SetErrorDst()
void ns3::dsr::DsrOptionRerrUnreachHeader::SetErrorDst (Ipv4Address errorDstAddress) virtual
Set the error destination ip address.
Parameters
errorDstAddress The error destination address
Reimplemented from ns3::dsr::DsrOptionRerrHeader.
Definition at line 834 of file dsr-option-header.cc.
References m_errorDstAddress.
Referenced by ns3::dsr::DsrRouting::CheckSendBuffer(), DsrRerrHeaderTest::DoRun(), ns3::dsr::DsrOptionRreq::Process(), ns3::dsr::DsrRouting::SendPacketFromBuffer(), and ns3::dsr::DsrRouting::SendUnreachError().
SetErrorSrc()
void ns3::dsr::DsrOptionRerrUnreachHeader::SetErrorSrc (Ipv4Address errorSrcAddress) virtual
Set the route error source address.
Parameters
errorSrcAddress The error source address
Reimplemented from ns3::dsr::DsrOptionRerrHeader.
Definition at line 824 of file dsr-option-header.cc.
References m_errorSrcAddress.
Referenced by ns3::dsr::DsrRouting::CheckSendBuffer(), DsrRerrHeaderTest::DoRun(), ns3::dsr::DsrOptionRreq::Process(), ns3::dsr::DsrRouting::SendPacketFromBuffer(), and ns3::dsr::DsrRouting::SendUnreachError().
SetOriginalDst()
void ns3::dsr::DsrOptionRerrUnreachHeader::SetOriginalDst (Ipv4Address originalDst)
Set the unreachable node ip address.
Parameters
originalDst The unreachable ip address
Definition at line 854 of file dsr-option-header.cc.
References m_originalDst.
Referenced by ns3::dsr::DsrRouting::SendPacketFromBuffer(), and ns3::dsr::DsrRouting::SendUnreachError().
SetSalvage()
void ns3::dsr::DsrOptionRerrUnreachHeader::SetSalvage (uint8_t salvage) virtual
Set the salvage value of the packet.
Parameters
salvage The salvage value of the packet
Reimplemented from ns3::dsr::DsrOptionRerrHeader.
Definition at line 814 of file dsr-option-header.cc.
References m_salvage.
Referenced by ns3::dsr::DsrRouting::CheckSendBuffer(), DsrRerrHeaderTest::DoRun(), ns3::dsr::DsrOptionRreq::Process(), ns3::dsr::DsrRouting::SendPacketFromBuffer(), and ns3::dsr::DsrRouting::SendUnreachError().
SetUnreachNode()
void ns3::dsr::DsrOptionRerrUnreachHeader::SetUnreachNode (Ipv4Address unreachNode)
Set the unreachable node ip address.
Parameters
unreachNode The unreachable ip address
Definition at line 844 of file dsr-option-header.cc.
References m_unreachNode.
Referenced by ns3::dsr::DsrRouting::CheckSendBuffer(), DsrRerrHeaderTest::DoRun(), ns3::dsr::DsrOptionRreq::Process(), ns3::dsr::DsrRouting::SendPacketFromBuffer(), and ns3::dsr::DsrRouting::SendUnreachError().
Member Data Documentation
m_errorDstAddress
Ipv4Address ns3::dsr::DsrOptionRerrUnreachHeader::m_errorDstAddress private
The error destination address.
Definition at line 995 of file dsr-option-header.h.
Referenced by Deserialize(), GetErrorDst(), Print(), Serialize(), and SetErrorDst().
m_errorSrcAddress
Ipv4Address ns3::dsr::DsrOptionRerrUnreachHeader::m_errorSrcAddress private
The error source address.
Definition at line 991 of file dsr-option-header.h.
Referenced by Deserialize(), GetErrorSrc(), Print(), Serialize(), and SetErrorSrc().
m_errorType
uint8_t ns3::dsr::DsrOptionRerrUnreachHeader::m_errorType private
The error type or route error option.
Definition at line 983 of file dsr-option-header.h.
Referenced by Print().
m_originalDst
Ipv4Address ns3::dsr::DsrOptionRerrUnreachHeader::m_originalDst private
The original destination address.
Definition at line 1003 of file dsr-option-header.h.
Referenced by Deserialize(), GetOriginalDst(), Serialize(), and SetOriginalDst().
m_salvage
uint8_t ns3::dsr::DsrOptionRerrUnreachHeader::m_salvage private
The salavage field.
Definition at line 987 of file dsr-option-header.h.
Referenced by Deserialize(), GetSalvage(), Print(), Serialize(), and SetSalvage().
m_unreachNode
Ipv4Address ns3::dsr::DsrOptionRerrUnreachHeader::m_unreachNode private
The unreachable node address.
Definition at line 999 of file dsr-option-header.h.
Referenced by Deserialize(), GetUnreachNode(), Print(), Serialize(), and SetUnreachNode().
The documentation for this class was generated from the following files:
src/dsr/model/dsr-option-header.h
src/dsr/model/dsr-option-header.cc