ns-3: ns3::UcdChannelEncodings Class Reference
ns3::UcdChannelEncodings Class Reference abstract
WiMAX Models
#include "ul-mac-messages.h"
Public Member Functions
UcdChannelEncodings (void)
virtual ~UcdChannelEncodings (void)
uint16_t GetBwReqOppSize (void) const
Get BW request opp size.
uint32_t GetFrequency (void) const
Get frequency.
uint16_t GetRangReqOppSize (void) const
Get range request opp size.
uint16_t GetSize (void) const
Get size.
Buffer::Iterator Read (Buffer::Iterator start)
Read item.
void SetBwReqOppSize (uint16_t bwReqOppSize)
Set BW request opp size.
void SetFrequency (uint32_t frequency)
Set frequency.
void SetRangReqOppSize (uint16_t rangReqOppSize)
Set range request opp size.
Buffer::Iterator Write (Buffer::Iterator start) const
Write item.
Private Member Functions
virtual Buffer::Iterator DoRead (Buffer::Iterator start)=0
Read item.
virtual Buffer::Iterator DoWrite (Buffer::Iterator start) const =0
Write item.
Private Attributes
uint16_t m_bwReqOppSize
BW request opp size.
uint32_t m_frequency
frequency
uint16_t m_rangReqOppSize
range request opp size
Detailed Description
This class implements the UCD channel encodings as described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems" 11.3.1 UCD channel encodings, page 651
Definition at line 39 of file ul-mac-messages.h.
Constructor & Destructor Documentation
UcdChannelEncodings()
ns3::UcdChannelEncodings::UcdChannelEncodings (void)
Definition at line 30 of file ul-mac-messages.cc.
~UcdChannelEncodings()
ns3::UcdChannelEncodings::~UcdChannelEncodings (void) virtual
Definition at line 37 of file ul-mac-messages.cc.
Member Function Documentation
DoRead()
virtual Buffer::Iterator ns3::UcdChannelEncodings::DoRead (Buffer::Iterator start) private pure virtual
Read item.
Parameters
start the iterator
Returns
the updated iterator
Implemented in ns3::OfdmUcdChannelEncodings.
Referenced by Read().
DoWrite()
virtual Buffer::Iterator ns3::UcdChannelEncodings::DoWrite (Buffer::Iterator start) const private pure virtual
Write item.
Parameters
start the iterator
Returns
the updated iterator
Implemented in ns3::OfdmUcdChannelEncodings.
Referenced by Write().
GetBwReqOppSize()
uint16_t ns3::UcdChannelEncodings::GetBwReqOppSize (void) const
Get BW request opp size.
Returns
the bandwidth request opp size
Definition at line 60 of file ul-mac-messages.cc.
References m_bwReqOppSize.
GetFrequency()
uint32_t ns3::UcdChannelEncodings::GetFrequency (void) const
Get frequency.
Returns
the frequency
Definition at line 72 of file ul-mac-messages.cc.
References m_frequency.
GetRangReqOppSize()
uint16_t ns3::UcdChannelEncodings::GetRangReqOppSize (void) const
Get range request opp size.
Returns
the ragning request opp size
Definition at line 66 of file ul-mac-messages.cc.
References m_rangReqOppSize.
GetSize()
uint16_t ns3::UcdChannelEncodings::GetSize (void) const
Get size.
Returns
the size
Definition at line 78 of file ul-mac-messages.cc.
Referenced by ns3::OfdmUcdChannelEncodings::GetSize().
Read()
Buffer::Iterator ns3::UcdChannelEncodings::Read (Buffer::Iterator start)
Read item.
Parameters
start the iterator
Returns
the updated iterator
Definition at line 94 of file ul-mac-messages.cc.
References DoRead(), m_bwReqOppSize, m_frequency, m_rangReqOppSize, ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU32(), and visualizer.core::start().
Referenced by ns3::Ucd::Deserialize().
SetBwReqOppSize()
void ns3::UcdChannelEncodings::SetBwReqOppSize (uint16_t bwReqOppSize)
Set BW request opp size.
Parameters
bwReqOppSize the bandwidth request opp size
Definition at line 42 of file ul-mac-messages.cc.
References m_bwReqOppSize.
Referenced by ns3::BaseStationNetDevice::CreateUcd().
SetFrequency()
void ns3::UcdChannelEncodings::SetFrequency (uint32_t frequency)
Set frequency.
Parameters
frequency the frequency
Definition at line 54 of file ul-mac-messages.cc.
References m_frequency.
Referenced by ns3::BaseStationNetDevice::CreateUcd().
SetRangReqOppSize()
void ns3::UcdChannelEncodings::SetRangReqOppSize (uint16_t rangReqOppSize)
Set range request opp size.
Parameters
rangReqOppSize the ranging request opp size
Definition at line 48 of file ul-mac-messages.cc.
References m_rangReqOppSize.
Referenced by ns3::BaseStationNetDevice::CreateUcd().
Write()
Buffer::Iterator ns3::UcdChannelEncodings::Write (Buffer::Iterator start) const
Write item.
Parameters
start the iterator
Returns
the updated iterator
Definition at line 84 of file ul-mac-messages.cc.
References DoWrite(), m_bwReqOppSize, m_frequency, m_rangReqOppSize, visualizer.core::start(), ns3::Buffer::Iterator::WriteU16(), and ns3::Buffer::Iterator::WriteU32().
Referenced by ns3::Ucd::Serialize().
Member Data Documentation
m_bwReqOppSize
uint16_t ns3::UcdChannelEncodings::m_bwReqOppSize private
BW request opp size.
Definition at line 110 of file ul-mac-messages.h.
Referenced by GetBwReqOppSize(), Read(), SetBwReqOppSize(), and Write().
m_frequency
uint32_t ns3::UcdChannelEncodings::m_frequency private
frequency
Definition at line 112 of file ul-mac-messages.h.
Referenced by GetFrequency(), Read(), SetFrequency(), and Write().
m_rangReqOppSize
uint16_t ns3::UcdChannelEncodings::m_rangReqOppSize private
range request opp size
Definition at line 111 of file ul-mac-messages.h.
Referenced by GetRangReqOppSize(), Read(), SetRangReqOppSize(), and Write().
The documentation for this class was generated from the following files:
src/wimax/model/ul-mac-messages.h
src/wimax/model/ul-mac-messages.cc