ns-3: ns3::DeviceEnergyModelHelper Class Reference
ns3::DeviceEnergyModelHelper Class Reference abstract
Energy Models
Creates DeviceEnergyModel objects.
#include "energy-model-helper.h"
Public Member Functions
virtual ~DeviceEnergyModelHelper ()
DeviceEnergyModelContainer Install (NetDeviceContainer deviceContainer, EnergySourceContainer sourceContainer) const
DeviceEnergyModelContainer Install (Ptr< NetDevice > device, Ptr< EnergySource > source) const
virtual void Set (std::string name, const AttributeValue &v)=0
Private Member Functions
virtual Ptr< DeviceEnergyModel > DoInstall (Ptr< NetDevice > device, Ptr< EnergySource > source) const =0
Detailed Description
Creates DeviceEnergyModel objects.
This class helps to create and install DeviceEnergyModel onto NetDevice. A DeviceEnergyModel is connected to a NetDevice (or PHY object) by callbacks. Note that DeviceEnergyModel objects are not aggregated onto the node. They can be accessed through the EnergySource object, which is aggregated onto the node.
Definition at line 116 of file energy-model-helper.h.
Constructor & Destructor Documentation
~DeviceEnergyModelHelper()
ns3::DeviceEnergyModelHelper::~DeviceEnergyModelHelper () virtual
Definition at line 86 of file energy-model-helper.cc.
Member Function Documentation
DoInstall()
virtual Ptr<DeviceEnergyModel> ns3::DeviceEnergyModelHelper::DoInstall (Ptr< NetDevice > device, Ptr< EnergySource > source) const private pure virtual
Parameters
device The net device corresponding to DeviceEnergyModel object.
source The EnergySource the DeviceEnergyModel will be using.
Returns
Pointer to the created DeviceEnergyModel.
Child classes of DeviceEnergyModelHelper only have to implement this function, to create and aggregate an DeviceEnergyModel object onto a single node. The rest of the installation process (eg. installing EnergySource on set of nodes) is implemented in the DeviceEnergyModelHelper base class.
Implemented in ns3::WifiRadioEnergyModelHelper, ns3::AcousticModemEnergyModelHelper, and ns3::lorawan::LoraRadioEnergyModelHelper.
Referenced by Install().
Install() [1/2]
DeviceEnergyModelContainer ns3::DeviceEnergyModelHelper::Install (NetDeviceContainer deviceContainer, EnergySourceContainer sourceContainer) const
Parameters
deviceContainer List of NetDevices to be install DeviceEnergyModel objects.
sourceContainer List of EnergySource the DeviceEnergyModel will be using.
Returns
An DeviceEnergyModelContainer contains all the DeviceEnergyModels.
Installs DeviceEnergyModels with specified EnergySources onto a list of NetDevices.
Definition at line 103 of file energy-model-helper.cc.
References ns3::DeviceEnergyModelContainer::Add(), ns3::EnergySourceContainer::Begin(), ns3::NetDeviceContainer::Begin(), DoInstall(), ns3::NetDeviceContainer::End(), ns3::EnergySourceContainer::GetN(), ns3::NetDeviceContainer::GetN(), and NS_ASSERT.
Install() [2/2]
DeviceEnergyModelContainer ns3::DeviceEnergyModelHelper::Install (Ptr< NetDevice > device, Ptr< EnergySource > source) const
Parameters
device Pointer to the NetDevice to install DeviceEnergyModel.
source The EnergySource the DeviceEnergyModel will be using.
Returns
An DeviceEnergyModelContainer contains all the DeviceEnergyModels.
Installs an DeviceEnergyModel with a specified EnergySource onto a xNetDevice.
Definition at line 91 of file energy-model-helper.cc.
References DoInstall(), and NS_ASSERT.
Referenced by BatteryLifetimeTest::ConstantLoadTest(), BasicEnergyDepletionTest::DepletionTestCase(), AcousticModemEnergyTestCase::DoRun(), AcousticModemEnergyDepletionTestCase::DoRun(), UanExperiment::SetupCommunications(), and BatteryLifetimeTest::VariableLoadTest().
Set()
virtual void ns3::DeviceEnergyModelHelper::Set (std::string name, const AttributeValue & v) pure virtual
Parameters
name Name of attribute to set.
v Value of the attribute.
Sets one of the attributes of underlying DeviceEnergyModel.
Implemented in ns3::WifiRadioEnergyModelHelper, ns3::AcousticModemEnergyModelHelper, and ns3::lorawan::LoraRadioEnergyModelHelper.
The documentation for this class was generated from the following files:
src/energy/helper/energy-model-helper.h
src/energy/helper/energy-model-helper.cc