ns-3: ns3::EpcTestRrc Class Reference
ns3::EpcTestRrc Class Reference
LTE Models » lte module tests | Test suites
RRC stub providing a testing S1 SAP user to be used with the EpcEnbApplication.
#include "lte-test-entities.h"
Public Member Functions
EpcTestRrc ()
virtual ~EpcTestRrc ()
virtual void DoDispose (void)
Destructor implementation.
EpcEnbS1SapUser * GetS1SapUser ()
void SetS1SapProvider (EpcEnbS1SapProvider *s)
Set the S1 SAP Provider.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void DoDataRadioBearerSetupRequest (EpcEnbS1SapUser::DataRadioBearerSetupRequestParameters params)
Data radio bearer setup request.
void DoInitialContextSetupRequest (EpcEnbS1SapUser::InitialContextSetupRequestParameters params)
Initial context setup request.
void DoPathSwitchRequestAcknowledge (EpcEnbS1SapUser::PathSwitchRequestAcknowledgeParameters params)
Path switch request acknowledge function.
Private Attributes
EpcEnbS1SapProvider * m_s1SapProvider
S1 SAP provider.
EpcEnbS1SapUser * m_s1SapUser
S1 SAP user.
Friends
class MemberEpcEnbS1SapUser< EpcTestRrc >
allow MemberEpcEnbS1SapUser<EpcTestRrc> class friend access
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
RRC stub providing a testing S1 SAP user to be used with the EpcEnbApplication.
Definition at line 416 of file lte-test-entities.h.
Constructor & Destructor Documentation
EpcTestRrc()
ns3::EpcTestRrc::EpcTestRrc ()
Definition at line 684 of file lte-test-entities.cc.
References m_s1SapUser, MemberEpcEnbS1SapUser< EpcTestRrc >, and NS_LOG_FUNCTION.
~EpcTestRrc()
ns3::EpcTestRrc::~EpcTestRrc () virtual
Definition at line 692 of file lte-test-entities.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDataRadioBearerSetupRequest()
void ns3::EpcTestRrc::DoDataRadioBearerSetupRequest (EpcEnbS1SapUser::DataRadioBearerSetupRequestParameters params) private
Data radio bearer setup request.
Parameters
params EpcEnbS1SapUser::DataRadioBearerSetupRequestParameters
Definition at line 735 of file lte-test-entities.cc.
DoDispose()
void ns3::EpcTestRrc::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 699 of file lte-test-entities.cc.
References m_s1SapUser, and NS_LOG_FUNCTION.
DoInitialContextSetupRequest()
void ns3::EpcTestRrc::DoInitialContextSetupRequest (EpcEnbS1SapUser::InitialContextSetupRequestParameters params) private
Initial context setup request.
Parameters
params EpcEnbS1SapUser::InitialContextSetupRequestParameters
Definition at line 729 of file lte-test-entities.cc.
DoPathSwitchRequestAcknowledge()
void ns3::EpcTestRrc::DoPathSwitchRequestAcknowledge (EpcEnbS1SapUser::PathSwitchRequestAcknowledgeParameters params) private
Path switch request acknowledge function.
Parameters
params EpcEnbS1SapUser::PathSwitchRequestAcknowledgeParameters
Definition at line 741 of file lte-test-entities.cc.
GetS1SapUser()
EpcEnbS1SapUser * ns3::EpcTestRrc::GetS1SapUser ()
Returns
the S1 SAP user
Definition at line 723 of file lte-test-entities.cc.
References m_s1SapUser.
Referenced by EpcS1uDlTestCase::DoRun(), and EpcS1uUlTestCase::DoRun().
GetTypeId()
TypeId ns3::EpcTestRrc::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 706 of file lte-test-entities.cc.
References NS_LOG_FUNCTION, and ns3::TypeId::SetParent().
SetS1SapProvider()
void ns3::EpcTestRrc::SetS1SapProvider (EpcEnbS1SapProvider * s)
Set the S1 SAP Provider.
Parameters
s the S1 SAP Provider
Definition at line 716 of file lte-test-entities.cc.
References m_s1SapProvider.
Referenced by EpcS1uDlTestCase::DoRun(), and EpcS1uUlTestCase::DoRun().
Friends And Related Function Documentation
MemberEpcEnbS1SapUser< EpcTestRrc >
friend class MemberEpcEnbS1SapUser< EpcTestRrc > friend
allow MemberEpcEnbS1SapUser<EpcTestRrc> class friend access
Definition at line 404 of file lte-test-entities.h.
Referenced by EpcTestRrc().
Member Data Documentation
m_s1SapProvider
EpcEnbS1SapProvider* ns3::EpcTestRrc::m_s1SapProvider private
S1 SAP provider.
Definition at line 465 of file lte-test-entities.h.
Referenced by SetS1SapProvider().
m_s1SapUser
EpcEnbS1SapUser* ns3::EpcTestRrc::m_s1SapUser private
S1 SAP user.
Definition at line 466 of file lte-test-entities.h.
Referenced by EpcTestRrc(), DoDispose(), and GetS1SapUser().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-entities.h
src/lte/test/lte-test-entities.cc