ns-3: ns3::dsr::DsrPassiveBuffer Class Reference
ns3::dsr::DsrPassiveBuffer Class Reference
DSR Routing
DSR passive buffer.
#include "dsr-passive-buff.h"
Public Member Functions
DsrPassiveBuffer ()
virtual ~DsrPassiveBuffer ()
bool AllEqual (DsrPassiveBuffEntry &entry)
Check if all the entries in passive buffer entry is all equal or not.
bool Dequeue (Ipv4Address dst, DsrPassiveBuffEntry &entry)
Return first found (the earliest) entry for given destination.
bool Enqueue (DsrPassiveBuffEntry &entry)
Push entry in queue, if there is no entry with the same packet and destination address in queue.
bool Find (Ipv4Address dst)
Finds whether a packet with destination dst exists in the queue.
uint32_t GetMaxQueueLen () const
Get maximum queue length.
Time GetPassiveBufferTimeout () const
Get passive buffer timeout.
uint32_t GetSize ()
Number of entries.
void SetMaxQueueLen (uint32_t len)
Set maximum queue length.
void SetPassiveBufferTimeout (Time t)
Set passive buffer timeout.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void Drop (DsrPassiveBuffEntry en, std::string reason)
Notify that packet is dropped from queue by timeout.
void DropLink (DsrPassiveBuffEntry en, std::string reason)
Notify that packet is dropped from queue by timeout.
void Purge ()
Remove all expired entries.
Static Private Member Functions
static bool LinkEqual (DsrPassiveBuffEntry en, const std::vector< Ipv4Address > link)
Check if the send buffer entry is the same or not.
Private Attributes
uint32_t m_maxLen
The maximum number of packets that we allow a routing protocol to buffer.
std::vector< DsrPassiveBuffEntry > m_passiveBuffer
The send buffer to cache unsent packet.
Time m_passiveBufferTimeout
The maximum period of time that a routing protocol is allowed to buffer a packet for, seconds.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
DSR passive buffer.
Definition at line 258 of file dsr-passive-buff.h.
Constructor & Destructor Documentation
DsrPassiveBuffer()
ns3::dsr::DsrPassiveBuffer::DsrPassiveBuffer ()
Definition at line 57 of file dsr-passive-buff.cc.
~DsrPassiveBuffer()
ns3::dsr::DsrPassiveBuffer::~DsrPassiveBuffer () virtual
Definition at line 61 of file dsr-passive-buff.cc.
Member Function Documentation
AllEqual()
bool ns3::dsr::DsrPassiveBuffer::AllEqual (DsrPassiveBuffEntry & entry)
Check if all the entries in passive buffer entry is all equal or not.
Note
For real this function checks if at most one entry is equal. If it is, that entry is removed. Further entries are NOT checked. This could be a bug.
Parameters
entry The Entry to check
Returns
true if an Entry was found and removed.
Definition at line 107 of file dsr-passive-buff.cc.
References ns3::dsr::DsrPassiveBuffEntry::GetDestination(), ns3::dsr::DsrPassiveBuffEntry::GetFragmentOffset(), ns3::dsr::DsrPassiveBuffEntry::GetIdentification(), ns3::dsr::DsrPassiveBuffEntry::GetNextHop(), ns3::dsr::DsrPassiveBuffEntry::GetPacket(), ns3::dsr::DsrPassiveBuffEntry::GetSegsLeft(), ns3::dsr::DsrPassiveBuffEntry::GetSource(), and m_passiveBuffer.
Dequeue()
bool ns3::dsr::DsrPassiveBuffer::Dequeue (Ipv4Address dst, DsrPassiveBuffEntry & entry)
Return first found (the earliest) entry for given destination.
Parameters
[in] dst Entry destination
[out] entry The Entry found (if any).
Returns
true on success
Definition at line 129 of file dsr-passive-buff.cc.
References ns3::dsr::DsrPassiveBuffEntry::GetPacket(), m_passiveBuffer, NS_LOG_DEBUG, and Purge().
Drop()
void ns3::dsr::DsrPassiveBuffer::Drop (DsrPassiveBuffEntry en, std::string reason) private
Notify that packet is dropped from queue by timeout.
Parameters
en BuffEntry Buffer entry
reason Drop reason
Definition at line 204 of file dsr-passive-buff.cc.
References ns3::dsr::DsrPassiveBuffEntry::GetDestination(), ns3::dsr::DsrPassiveBuffEntry::GetPacket(), and NS_LOG_LOGIC().
Referenced by Enqueue(), and Purge().
DropLink()
void ns3::dsr::DsrPassiveBuffer::DropLink (DsrPassiveBuffEntry en, std::string reason) private
Notify that packet is dropped from queue by timeout.
Parameters
en BuffEntry Buffer entry
reason Drop reason
Definition at line 213 of file dsr-passive-buff.cc.
References ns3::dsr::DsrPassiveBuffEntry::GetNextHop(), ns3::dsr::DsrPassiveBuffEntry::GetPacket(), ns3::dsr::DsrPassiveBuffEntry::GetSource(), and NS_LOG_LOGIC().
Enqueue()
bool ns3::dsr::DsrPassiveBuffer::Enqueue (DsrPassiveBuffEntry & entry)
Push entry in queue, if there is no entry with the same packet and destination address in queue.
Parameters
entry Buffer Entry
Returns
true on success adding the Entry.
Definition at line 73 of file dsr-passive-buff.cc.
References Drop(), ns3::dsr::DsrPassiveBuffEntry::GetDestination(), ns3::dsr::DsrPassiveBuffEntry::GetFragmentOffset(), ns3::dsr::DsrPassiveBuffEntry::GetIdentification(), ns3::dsr::DsrPassiveBuffEntry::GetNextHop(), ns3::dsr::DsrPassiveBuffEntry::GetPacket(), ns3::dsr::DsrPassiveBuffEntry::GetSegsLeft(), ns3::dsr::DsrPassiveBuffEntry::GetSource(), m_maxLen, m_passiveBuffer, m_passiveBufferTimeout, Purge(), and ns3::dsr::DsrPassiveBuffEntry::SetExpireTime().
Find()
bool ns3::dsr::DsrPassiveBuffer::Find (Ipv4Address dst)
Finds whether a packet with destination dst exists in the queue.
Parameters
dst Destination.
Returns
true if there is a packet.
Definition at line 149 of file dsr-passive-buff.cc.
References m_passiveBuffer, and NS_LOG_DEBUG.
GetMaxQueueLen()
uint32_t ns3::dsr::DsrPassiveBuffer::GetMaxQueueLen () const inline
Get maximum queue length.
Returns
the maximum queue length
Definition at line 298 of file dsr-passive-buff.h.
References m_maxLen.
GetPassiveBufferTimeout()
Time ns3::dsr::DsrPassiveBuffer::GetPassiveBufferTimeout () const inline
Get passive buffer timeout.
Returns
the passive buffer timeout
Definition at line 314 of file dsr-passive-buff.h.
References m_passiveBufferTimeout.
GetSize()
uint32_t ns3::dsr::DsrPassiveBuffer::GetSize ()
Number of entries.
Returns
The number of entries.
Definition at line 66 of file dsr-passive-buff.cc.
References m_passiveBuffer, and Purge().
GetTypeId()
TypeId ns3::dsr::DsrPassiveBuffer::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 47 of file dsr-passive-buff.cc.
References ns3::TypeId::SetParent().
LinkEqual()
static bool ns3::dsr::DsrPassiveBuffer::LinkEqual (DsrPassiveBuffEntry en, const std::vector< Ipv4Address > link) inline static private
Check if the send buffer entry is the same or not.
Parameters
en The Entry to check
link The link to check
Returns
true if an Entry source and Next hop are equal to the Link parameters
Definition at line 348 of file dsr-passive-buff.h.
References ns3::dsr::DsrPassiveBuffEntry::GetNextHop(), and ns3::dsr::DsrPassiveBuffEntry::GetSource().
Purge()
void ns3::dsr::DsrPassiveBuffer::Purge () private
Remove all expired entries.
Definition at line 183 of file dsr-passive-buff.cc.
References Drop(), m_passiveBuffer, and NS_LOG_DEBUG.
Referenced by Dequeue(), Enqueue(), and GetSize().
SetMaxQueueLen()
void ns3::dsr::DsrPassiveBuffer::SetMaxQueueLen (uint32_t len) inline
Set maximum queue length.
Parameters
len the maximum queue length
Definition at line 306 of file dsr-passive-buff.h.
References m_maxLen.
SetPassiveBufferTimeout()
void ns3::dsr::DsrPassiveBuffer::SetPassiveBufferTimeout (Time t) inline
Set passive buffer timeout.
Parameters
t the passive buffer timeout
Definition at line 322 of file dsr-passive-buff.h.
References m_passiveBufferTimeout.
Member Data Documentation
m_maxLen
uint32_t ns3::dsr::DsrPassiveBuffer::m_maxLen private
The maximum number of packets that we allow a routing protocol to buffer.
Definition at line 341 of file dsr-passive-buff.h.
Referenced by Enqueue(), GetMaxQueueLen(), and SetMaxQueueLen().
m_passiveBuffer
std::vector<DsrPassiveBuffEntry> ns3::dsr::DsrPassiveBuffer::m_passiveBuffer private
The send buffer to cache unsent packet.
Definition at line 329 of file dsr-passive-buff.h.
Referenced by AllEqual(), Dequeue(), Enqueue(), Find(), GetSize(), and Purge().
m_passiveBufferTimeout
Time ns3::dsr::DsrPassiveBuffer::m_passiveBufferTimeout private
The maximum period of time that a routing protocol is allowed to buffer a packet for, seconds.
Definition at line 343 of file dsr-passive-buff.h.
Referenced by Enqueue(), GetPassiveBufferTimeout(), and SetPassiveBufferTimeout().
The documentation for this class was generated from the following files:
src/dsr/model/dsr-passive-buff.h
src/dsr/model/dsr-passive-buff.cc