ns-3: SixlowpanFragmentationTest Class Reference
SixlowpanFragmentationTest Class Reference
6LoWPAN » 6LoWPAN module tests | Test suites
6LoWPAN Fragmentation Test
Public Member Functions
SixlowpanFragmentationTest ()
~SixlowpanFragmentationTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
void HandleReadClient (Ptr< Socket > socket)
Handles incoming packets in the client.
void HandleReadIcmpClient (Ipv6Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo)
Handles incoming ICMP packets in the client.
void HandleReadServer (Ptr< Socket > socket)
Handles incoming packets in the server.
Ptr< Packet > SendClient (void)
Send a packet to the server.
void SetFill (uint8_t *fill, uint32_t fillSize, uint32_t dataSize)
Set the packet optional content.
void StartClient (Ptr< Node > clientNode)
Start the client node.
void StartServer (Ptr< Node > serverNode)
Start the server node.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Attributes
uint8_t * m_data
Data to be carried in the packet.
uint32_t m_dataSize
Size of the data (if any).
uint8_t m_icmpCode
ICMP code.
uint8_t m_icmpType
ICMP type.
Ptr< Packet > m_receivedPacketClient
Packet received by the client.
Ptr< Packet > m_receivedPacketServer
packet received by the server.
Ptr< Packet > m_sentPacketClient
Packet sent by client.
uint32_t m_size
Size of the packet if no data has been provided.
Ptr< Socket > m_socketClient
Socket on the client.
Ptr< Socket > m_socketServer
Socket on the server.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
6LoWPAN Fragmentation Test
Definition at line 53 of file sixlowpan-fragmentation-test.cc.
Constructor & Destructor Documentation
SixlowpanFragmentationTest()
SixlowpanFragmentationTest::SixlowpanFragmentationTest ()
Definition at line 123 of file sixlowpan-fragmentation-test.cc.
References m_data, m_dataSize, m_icmpCode, m_icmpType, m_size, and m_socketServer.
~SixlowpanFragmentationTest()
SixlowpanFragmentationTest::~SixlowpanFragmentationTest ()
Definition at line 134 of file sixlowpan-fragmentation-test.cc.
References m_data, and m_dataSize.
Member Function Documentation
DoRun()
void SixlowpanFragmentationTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 263 of file sixlowpan-fragmentation-test.cc.
References ns3::Ipv6::AddAddress(), ns3::Node::AddDevice(), ns3::Ipv6::AddInterface(), third::channel, ns3::Packet::CopyData(), ns3::ErrorModel::Disable(), ns3::ErrorModel::Enable(), ns3::Node::GetId(), ns3::Socket::GetNode(), ns3::Object::GetObject(), ns3::Packet::GetSize(), ns3::InternetStackHelper::Install(), m_data, m_icmpCode, m_icmpType, m_receivedPacketServer, m_socketClient, NS_TEST_EXPECT_MSG_EQ, packetSize, ns3::ErrorModel::Reset(), ns3::Seconds(), SendClient(), ns3::SimpleNetDevice::SetAddress(), ns3::ObjectBase::SetAttribute(), ns3::SimpleNetDevice::SetChannel(), SetFill(), ns3::InternetStackHelper::SetIpv4StackInstall(), ns3::SimpleNetDevice::SetMtu(), ns3::SixLowPanNetDevice::SetNetDevice(), ns3::SimpleNetDevice::SetReceiveErrorModel(), ns3::Ipv6::SetUp(), StartClient(), and StartServer().
HandleReadClient()
void SixlowpanFragmentationTest::HandleReadClient (Ptr< Socket > socket)
Handles incoming packets in the client.
Parameters
socket The receiving socket.
Definition at line 196 of file sixlowpan-fragmentation-test.cc.
References ns3::Packet::Copy(), m_receivedPacketClient, and ns3::Socket::RecvFrom().
Referenced by StartClient().
HandleReadIcmpClient()
void SixlowpanFragmentationTest::HandleReadIcmpClient (Ipv6Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo)
Handles incoming ICMP packets in the client.
Parameters
icmpSource ICMP sender address.
icmpTtl ICMP TTL.
icmpType ICMP type.
icmpCode ICMP code.
icmpInfo ICMP info.
Definition at line 210 of file sixlowpan-fragmentation-test.cc.
References m_icmpCode, and m_icmpType.
Referenced by StartClient().
HandleReadServer()
void SixlowpanFragmentationTest::HandleReadServer (Ptr< Socket > socket)
Handles incoming packets in the server.
Parameters
socket The receiving socket.
Definition at line 162 of file sixlowpan-fragmentation-test.cc.
References ns3::Packet::Copy(), m_receivedPacketServer, ns3::Socket::RecvFrom(), ns3::Packet::RemoveAllByteTags(), and ns3::Packet::RemoveAllPacketTags().
Referenced by StartServer().
SendClient()
Ptr< Packet > SixlowpanFragmentationTest::SendClient (void)
Send a packet to the server.
Returns
The packet sent.
Definition at line 246 of file sixlowpan-fragmentation-test.cc.
References m_data, m_dataSize, m_size, m_socketClient, and ns3::Socket::Send().
Referenced by DoRun().
SetFill()
void SixlowpanFragmentationTest::SetFill (uint8_t * fill, uint32_t fillSize, uint32_t dataSize)
Set the packet optional content.
Parameters
fill Pointer to an array of data.
fillSize Size of the array of data.
dataSize Size of the packet - if fillSize is less than dataSize, the data is repeated.
Definition at line 219 of file sixlowpan-fragmentation-test.cc.
References m_data, m_dataSize, and m_size.
Referenced by DoRun().
StartClient()
void SixlowpanFragmentationTest::StartClient (Ptr< Node > clientNode)
Start the client node.
Parameters
clientNode The client node.
Definition at line 179 of file sixlowpan-fragmentation-test.cc.
References ns3::Socket::Bind(), ns3::Socket::Connect(), HandleReadClient(), HandleReadIcmpClient(), m_socketClient, ns3::MakeCallback(), ns3::ObjectBase::SetAttribute(), and ns3::Socket::SetRecvCallback().
Referenced by DoRun().
StartServer()
void SixlowpanFragmentationTest::StartServer (Ptr< Node > serverNode)
Start the server node.
Parameters
serverNode The server node.
Definition at line 146 of file sixlowpan-fragmentation-test.cc.
References ns3::Socket::Bind(), HandleReadServer(), m_socketServer, ns3::MakeCallback(), and ns3::Socket::SetRecvCallback().
Referenced by DoRun().
Member Data Documentation
m_data
uint8_t* SixlowpanFragmentationTest::m_data private
Data to be carried in the packet.
Definition at line 62 of file sixlowpan-fragmentation-test.cc.
Referenced by SixlowpanFragmentationTest(), ~SixlowpanFragmentationTest(), DoRun(), SendClient(), and SetFill().
m_dataSize
uint32_t SixlowpanFragmentationTest::m_dataSize private
Size of the data (if any).
Definition at line 61 of file sixlowpan-fragmentation-test.cc.
Referenced by SixlowpanFragmentationTest(), ~SixlowpanFragmentationTest(), SendClient(), and SetFill().
m_icmpCode
uint8_t SixlowpanFragmentationTest::m_icmpCode private
ICMP code.
Definition at line 65 of file sixlowpan-fragmentation-test.cc.
Referenced by SixlowpanFragmentationTest(), DoRun(), and HandleReadIcmpClient().
m_icmpType
uint8_t SixlowpanFragmentationTest::m_icmpType private
ICMP type.
Definition at line 64 of file sixlowpan-fragmentation-test.cc.
Referenced by SixlowpanFragmentationTest(), DoRun(), and HandleReadIcmpClient().
m_receivedPacketClient
Ptr<Packet> SixlowpanFragmentationTest::m_receivedPacketClient private
Packet received by the client.
Definition at line 56 of file sixlowpan-fragmentation-test.cc.
Referenced by HandleReadClient().
m_receivedPacketServer
Ptr<Packet> SixlowpanFragmentationTest::m_receivedPacketServer private
packet received by the server.
Definition at line 57 of file sixlowpan-fragmentation-test.cc.
Referenced by DoRun(), and HandleReadServer().
m_sentPacketClient
Ptr<Packet> SixlowpanFragmentationTest::m_sentPacketClient private
Packet sent by client.
Definition at line 55 of file sixlowpan-fragmentation-test.cc.
m_size
uint32_t SixlowpanFragmentationTest::m_size private
Size of the packet if no data has been provided.
Definition at line 63 of file sixlowpan-fragmentation-test.cc.
Referenced by SixlowpanFragmentationTest(), SendClient(), and SetFill().
m_socketClient
Ptr<Socket> SixlowpanFragmentationTest::m_socketClient private
Socket on the client.
Definition at line 60 of file sixlowpan-fragmentation-test.cc.
Referenced by DoRun(), SendClient(), and StartClient().
m_socketServer
Ptr<Socket> SixlowpanFragmentationTest::m_socketServer private
Socket on the server.
Definition at line 59 of file sixlowpan-fragmentation-test.cc.
Referenced by SixlowpanFragmentationTest(), and StartServer().
The documentation for this class was generated from the following file:
src/sixlowpan/test/sixlowpan-fragmentation-test.cc