ns-3: ns3::TcpNewReno Class Reference
ns3::TcpNewReno Class Reference
The NewReno implementation.
#include "tcp-congestion-ops.h"
Public Member Functions
TcpNewReno ()
TcpNewReno (const TcpNewReno &sock)
Copy constructor.
~TcpNewReno ()
virtual Ptr< TcpCongestionOps > Fork ()
Copy the congestion control algorithm across sockets.
std::string GetName () const
Get the name of the congestion control algorithm.
virtual uint32_t GetSsThresh (Ptr< const TcpSocketState > tcb, uint32_t bytesInFlight)
Get the slow start threshold after a loss event.
virtual void IncreaseWindow (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
Try to increase the cWnd following the NewReno specification.
virtual void ReduceCwnd (Ptr< TcpSocketState > tcb)
Reduces congestion window on receipt of ECN Echo Flag.
Public Member Functions inherited from ns3::TcpCongestionOps
TcpCongestionOps ()
TcpCongestionOps (const TcpCongestionOps &other)
Copy constructor.
virtual ~TcpCongestionOps ()
virtual void CongControl (Ptr< TcpSocketState > tcb, const TcpRateOps::TcpRateConnection &rc, const TcpRateOps::TcpRateSample &rs)
Called when packets are delivered to update cwnd and pacing rate.
virtual void CongestionStateSet (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCongState_t newState)
Trigger events/calculations specific to a congestion state.
virtual void CwndEvent (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCAEvent_t event)
Trigger events/calculations on occurrence of congestion window event.
virtual bool HasCongControl () const
Returns true when Congestion Control Algorithm implements CongControl.
virtual void Init (Ptr< TcpSocketState > tcb)
Set configuration required by congestion control algorithm.
virtual void PktsAcked (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked, const Time &rtt)
Timing information on received ACK.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpCongestionOps
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void CongestionAvoidance (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
NewReno congestion avoidance.
virtual uint32_t SlowStart (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
Tcp NewReno slow start algorithm.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The NewReno implementation.
New Reno introduces partial ACKs inside the well-established Reno algorithm. This and other modifications are described in RFC 6582.
See also
IncreaseWindow
Definition at line 222 of file tcp-congestion-ops.h.
Constructor & Destructor Documentation
TcpNewReno() [1/2]
ns3::TcpNewReno::TcpNewReno ()
Definition at line 108 of file tcp-congestion-ops.cc.
References NS_LOG_FUNCTION.
TcpNewReno() [2/2]
ns3::TcpNewReno::TcpNewReno (const TcpNewReno & sock)
Copy constructor.
Parameters
sock object to copy.
Definition at line 113 of file tcp-congestion-ops.cc.
References NS_LOG_FUNCTION.
~TcpNewReno()
ns3::TcpNewReno::~TcpNewReno ()
Definition at line 119 of file tcp-congestion-ops.cc.
Member Function Documentation
CongestionAvoidance()
void ns3::TcpNewReno::CongestionAvoidance (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked) protected virtual
NewReno congestion avoidance.
During congestion avoidance, cwnd is incremented by roughly 1 full-sized segment per round-trip time (RTT).
Parameters
tcb internal congestion state
segmentsAcked count of segments acked
Reimplemented in ns3::TcpHybla, ns3::TcpScalable, ns3::TcpLp, ns3::TcpLedbat, ns3::TcpHtcp, and ns3::TcpHighSpeed.
Definition at line 190 of file tcp-congestion-ops.cc.
References ns3::TracedValue< T >::Get(), ns3::TcpSocketState::m_cWnd, ns3::TcpSocketState::m_segmentSize, ns3::TcpSocketState::m_ssThresh, max, NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by ns3::TcpLedbat::CongestionAvoidance(), ns3::TcpLp::CongestionAvoidance(), IncreaseWindow(), ns3::TcpVeno::IncreaseWindow(), and ns3::TcpYeah::IncreaseWindow().
Fork()
Ptr< TcpCongestionOps > ns3::TcpNewReno::Fork () virtual
Copy the congestion control algorithm across sockets.
Returns
a pointer of the copied object
Implements ns3::TcpCongestionOps.
Reimplemented in ns3::TcpHybla, ns3::TcpYeah, ns3::TcpWestwood, ns3::TcpVeno, ns3::TcpVegas, ns3::TcpScalable, ns3::TcpLp, ns3::TcpLedbat, ns3::TcpIllinois, ns3::TcpHtcp, ns3::TcpHighSpeed, and ns3::TcpDctcp.
Definition at line 262 of file tcp-congestion-ops.cc.
GetName()
std::string ns3::TcpNewReno::GetName () const virtual
Get the name of the congestion control algorithm.
Returns
A string identifying the name
Implements ns3::TcpCongestionOps.
Reimplemented in ns3::TcpHybla, ns3::TcpYeah, ns3::TcpVeno, ns3::TcpVegas, ns3::TcpScalable, ns3::TcpLp, ns3::TcpLedbat, ns3::TcpIllinois, ns3::TcpHtcp, ns3::TcpHighSpeed, and ns3::TcpDctcp.
Definition at line 239 of file tcp-congestion-ops.cc.
GetSsThresh()
uint32_t ns3::TcpNewReno::GetSsThresh (Ptr< const TcpSocketState > tcb, uint32_t bytesInFlight) virtual
Get the slow start threshold after a loss event.
Is guaranteed that the congestion control state (TcpAckState_t) is changed BEFORE the invocation of this method. The implementator should return the slow start threshold (and not change it directly) because, in the future, the TCP implementation may require to instantly recover from a loss event (e.g. when there is a network with an high reordering factor).
Parameters
tcb internal congestion state
bytesInFlight total bytes in flight
Returns
Slow start threshold
Implements ns3::TcpCongestionOps.
Reimplemented in ns3::TcpYeah, ns3::TcpWestwood, ns3::TcpVeno, ns3::TcpVegas, ns3::TcpScalable, ns3::TcpIllinois, ns3::TcpHtcp, and ns3::TcpHighSpeed.
Definition at line 245 of file tcp-congestion-ops.cc.
References max, and NS_LOG_FUNCTION.
Referenced by ns3::TcpVeno::GetSsThresh().
GetTypeId()
TypeId ns3::TcpNewReno::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 98 of file tcp-congestion-ops.cc.
References ns3::TypeId::SetParent().
Referenced by ns3::TcpL4Protocol::GetTypeId().
IncreaseWindow()
void ns3::TcpNewReno::IncreaseWindow (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked) virtual
Try to increase the cWnd following the NewReno specification.
See also
SlowStart
CongestionAvoidance
Parameters
tcb internal congestion state
segmentsAcked count of segments acked
Reimplemented from ns3::TcpCongestionOps.
Reimplemented in ns3::TcpYeah, ns3::TcpVeno, ns3::TcpVegas, ns3::TcpLedbat, and ns3::TcpIllinois.
Definition at line 214 of file tcp-congestion-ops.cc.
References CongestionAvoidance(), ns3::TcpSocketState::m_cWnd, ns3::TcpSocketState::m_ssThresh, NS_LOG_FUNCTION, and SlowStart().
Referenced by TcpHighSpeedIncrementTest::DoRun(), TcpHtcpIncrementTest::DoRun(), TcpHyblaIncrementTest::DoRun(), TcpScalableIncrementTest::DoRun(), TcpDctcpToNewReno::ExecuteTest(), TcpLedbatToNewReno::ExecuteTest(), ns3::TcpVegas::IncreaseWindow(), and ns3::TcpVeno::IncreaseWindow().
ReduceCwnd()
void ns3::TcpNewReno::ReduceCwnd (Ptr< TcpSocketState > tcb) virtual
Reduces congestion window on receipt of ECN Echo Flag.
Parameters
tcb internal congestion state
Implements ns3::TcpCongestionOps.
Reimplemented in ns3::TcpDctcp.
Definition at line 254 of file tcp-congestion-ops.cc.
References ns3::TracedValue< T >::Get(), ns3::TcpSocketState::m_cWnd, ns3::TcpSocketState::m_segmentSize, max, and NS_LOG_FUNCTION.
SlowStart()
uint32_t ns3::TcpNewReno::SlowStart (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked) protected virtual
Tcp NewReno slow start algorithm.
Defined in RFC 5681 as
During slow start, a TCP increments cwnd by at most SMSS bytes for each ACK received that cumulatively acknowledges new data. Slow start ends when cwnd exceeds ssthresh (or, optionally, when it reaches it, as noted above) or when congestion is observed. While traditionally TCP implementations have increased cwnd by precisely SMSS bytes upon receipt of an ACK covering new data, we RECOMMEND that TCP implementations increase cwnd, per:
cwnd += min (N, SMSS) (2)
where N is the number of previously unacknowledged bytes acknowledged in the incoming ACK.
The ns-3 implementation respect the RFC definition. Linux does something different:
u32 tcp_slow_start(struct tcp_sock *tp, u32 acked)
  {
    u32 cwnd = tp->snd_cwnd + acked;
    if (cwnd > tp->snd_ssthresh)
      cwnd = tp->snd_ssthresh + 1;
    acked -= cwnd - tp->snd_cwnd;
    tp->snd_cwnd = min(cwnd, tp->snd_cwnd_clamp);
    return acked;
  }
As stated, we want to avoid the case when a cumulative ACK increases cWnd more than a segment size, but we keep count of how many segments we have ignored, and return them.
Parameters
tcb internal congestion state
segmentsAcked count of segments acked
Returns
the number of segments not considered for increasing the cWnd
Reimplemented in ns3::TcpHybla.
Definition at line 166 of file tcp-congestion-ops.cc.
References ns3::TcpSocketState::m_cWnd, ns3::TcpSocketState::m_segmentSize, ns3::TcpSocketState::m_ssThresh, NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by IncreaseWindow(), ns3::TcpIllinois::IncreaseWindow(), ns3::TcpLedbat::IncreaseWindow(), ns3::TcpVegas::IncreaseWindow(), ns3::TcpVeno::IncreaseWindow(), and ns3::TcpYeah::IncreaseWindow().
The documentation for this class was generated from the following files:
src/internet/model/tcp-congestion-ops.h
src/internet/model/tcp-congestion-ops.cc