ns-3: LteRadioLinkFailureTestCase Class Reference
LteRadioLinkFailureTestCase Class Reference
LTE Models
Testing the cell reselection procedure by UE at IDLE state.
#include "lte-test-radio-link-failure.h"
Public Member Functions
LteRadioLinkFailureTestCase (uint32_t numEnbs, uint32_t numUes, Time simTime, bool isIdealRrc, std::vector< Vector > uePositionList, std::vector< Vector > enbPositionList, Vector ueJumpAwayPosition, std::vector< Time > checkConnectedList)
Creates an instance of the radio link failure test case.
virtual ~LteRadioLinkFailureTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
std::string BuildNameString (uint32_t numEnbs, uint32_t numUes, bool isIdealRrc)
Builds the test name string based on provided parameter values.
void CheckConnected (Ptr< NetDevice > ueDevice, NetDeviceContainer enbDevices)
Check connected function.
void CheckIdle (Ptr< NetDevice > ueDevice, NetDeviceContainer enbDevices)
Check if the UE is in idle state.
bool CheckUeExistAtEnb (uint16_t rnti, Ptr< NetDevice > enbDevice)
Check if the UE exist at the eNB.
void ConnectionEstablishedEnbCallback (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti)
Connection established at eNodeB callback function.
void ConnectionEstablishedUeCallback (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti)
Connection established at UE callback function.
void ConnectionReleaseAtEnbCallback (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti)
This callback function is executed when UE context is removed at eNodeB.
virtual void DoRun ()
Setup the simulation according to the configuration set by the class constructor, run it, and verify the result.
void JumpAway (Vector UeJumpAwayPositionList)
Jump away function.
void PhySyncDetectionCallback (std::string context, uint64_t imsi, uint16_t rnti, uint16_t cellId, std::string type, uint8_t count)
This callback function is executed when UE RRC receives an in-sync or out-of-sync indication.
void RadioLinkFailureCallback (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti)
This callback function is executed when radio link failure is detected.
void UeStateTransitionCallback (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti, LteUeRrc::State oldState, LteUeRrc::State newState)
State transition callback function.
Private Attributes
std::vector< Time > m_checkConnectedList
the time at which UEs should have an active RRC connection
std::vector< Vector > m_enbPositionList
Position of the eNodeBs.
bool m_isIdealRrc
whether the LTE is configured to use ideal RRC
LteUeRrc::State m_lastState
The current UE RRC state.
uint32_t m_numEnbs
number of eNodeBs
uint32_t m_numOfInSyncIndications
number of in-sync indications detected
uint32_t m_numOfOutOfSyncIndications
number of out-of-sync indications detected
uint32_t m_numUes
number of UEs
bool m_radioLinkFailureDetected
true if radio link fails
Time m_simTime
simulation time
Vector m_ueJumpAwayPosition
Position where the UE(s) would jump.
Ptr< MobilityModel > m_ueMobility
UE mobility model.
std::vector< Vector > m_uePositionList
Position of the UEs.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Testing the cell reselection procedure by UE at IDLE state.
Definition at line 59 of file lte-test-radio-link-failure.h.
Constructor & Destructor Documentation
LteRadioLinkFailureTestCase()
LteRadioLinkFailureTestCase::LteRadioLinkFailureTestCase (uint32_t numEnbs, uint32_t numUes, Time simTime, bool isIdealRrc, std::vector< Vector > uePositionList, std::vector< Vector > enbPositionList, Vector ueJumpAwayPosition, std::vector< Time > checkConnectedList)
Creates an instance of the radio link failure test case.
Parameters
numEnbs number of eNodeBs
numUes number of UEs
simTime the simulation time
isIdealRrc if true, simulation uses Ideal RRC protocol, otherwise simulation uses Real RRC protocol
uePositionList Position of the UEs
enbPositionList Position of the eNodeBs
ueJumpAwayPosition Vector holding the UE jump away coordinates
checkConnectedList the time at which UEs should have an active RRC connection
Definition at line 126 of file lte-test-radio-link-failure.cc.
References ns3::TestCase::GetName(), m_lastState, m_numOfInSyncIndications, m_numOfOutOfSyncIndications, m_radioLinkFailureDetected, and NS_LOG_FUNCTION.
~LteRadioLinkFailureTestCase()
LteRadioLinkFailureTestCase::~LteRadioLinkFailureTestCase () virtual
Definition at line 148 of file lte-test-radio-link-failure.cc.
References ns3::TestCase::GetName(), and NS_LOG_FUNCTION.
Member Function Documentation
BuildNameString()
std::string LteRadioLinkFailureTestCase::BuildNameString (uint32_t numEnbs, uint32_t numUes, bool isIdealRrc) private
Builds the test name string based on provided parameter values.
Parameters
numEnbs the number of eNB nodes
numUes the number of UE nodes
isIdealRrc True if the Ideal RRC protocol is used
Returns
the name string
Definition at line 110 of file lte-test-radio-link-failure.cc.
CheckConnected()
void LteRadioLinkFailureTestCase::CheckConnected (Ptr< NetDevice > ueDevice, NetDeviceContainer enbDevices) private
Check connected function.
Parameters
ueDevice the UE device
enbDevices the ENB devices
Definition at line 402 of file lte-test-radio-link-failure.cc.
References ns3::ObjectPtrContainerValue::Begin(), ns3::NetDeviceContainer::Begin(), ns3::ObjectPtrContainerValue::End(), ns3::NetDeviceContainer::End(), ns3::ObjectBase::GetAttribute(), ns3::LteEnbNetDevice::GetCellId(), ns3::LteEnbNetDevice::GetDlBandwidth(), ns3::LteEnbNetDevice::GetDlEarfcn(), ns3::LteUeNetDevice::GetImsi(), ns3::UeManager::GetImsi(), ns3::ObjectPtrContainerValue::GetN(), ns3::Object::GetObject(), ns3::LteEnbNetDevice::GetRrc(), ns3::LteUeNetDevice::GetRrc(), ns3::UeManager::GetState(), ns3::LteEnbRrc::GetUeManager(), ns3::LteEnbNetDevice::GetUlBandwidth(), ns3::LteEnbNetDevice::GetUlEarfcn(), ns3::LteDataRadioBearerInfo::m_drbIdentity, ns3::LteDataRadioBearerInfo::m_epsBearerIdentity, ns3::LteDataRadioBearerInfo::m_logicalChannelIdentity, NS_ASSERT_MSG(), NS_LOG_FUNCTION, NS_TEST_ASSERT_MSG_EQ, and NS_TEST_ASSERT_MSG_NE.
Referenced by DoRun().
CheckIdle()
void LteRadioLinkFailureTestCase::CheckIdle (Ptr< NetDevice > ueDevice, NetDeviceContainer enbDevices) private
Check if the UE is in idle state.
Parameters
ueDevice the UE device
enbDevices the ENB devices
Definition at line 479 of file lte-test-radio-link-failure.cc.
References CheckUeExistAtEnb(), ns3::NetDeviceContainer::Get(), ns3::NetDeviceContainer::GetN(), ns3::Object::GetObject(), ns3::LteUeNetDevice::GetRrc(), NS_FATAL_ERROR, NS_LOG_FUNCTION, and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
CheckUeExistAtEnb()
bool LteRadioLinkFailureTestCase::CheckUeExistAtEnb (uint16_t rnti, Ptr< NetDevice > enbDevice) private
Check if the UE exist at the eNB.
Parameters
rnti the RNTI of the UE
enbDevice the eNB device
Returns
true if the UE exist at the eNB, otherwise false
Definition at line 510 of file lte-test-radio-link-failure.cc.
References ns3::LteEnbNetDevice::GetRrc(), ns3::LteEnbRrc::HasUeManager(), NS_ABORT_MSG_IF, and NS_LOG_FUNCTION.
Referenced by CheckIdle().
ConnectionEstablishedEnbCallback()
void LteRadioLinkFailureTestCase::ConnectionEstablishedEnbCallback (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti) private
Connection established at eNodeB callback function.
Parameters
context the context string
imsi the IMSI
cellId the cell ID
rnti the RNTI
Definition at line 531 of file lte-test-radio-link-failure.cc.
References NS_LOG_FUNCTION.
Referenced by DoRun().
ConnectionEstablishedUeCallback()
void LteRadioLinkFailureTestCase::ConnectionEstablishedUeCallback (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti) private
Connection established at UE callback function.
Parameters
context the context string
imsi the IMSI
cellId the cell ID
rnti the RNTI
Definition at line 538 of file lte-test-radio-link-failure.cc.
References m_numOfInSyncIndications, m_numOfOutOfSyncIndications, NS_LOG_FUNCTION, and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
ConnectionReleaseAtEnbCallback()
void LteRadioLinkFailureTestCase::ConnectionReleaseAtEnbCallback (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti) private
This callback function is executed when UE context is removed at eNodeB.
Parameters
context the context string
imsi the IMSI
cellId the cell ID
rnti the RNTI
Definition at line 549 of file lte-test-radio-link-failure.cc.
References NS_LOG_FUNCTION.
Referenced by DoRun().
DoRun()
void LteRadioLinkFailureTestCase::DoRun () private virtual
Setup the simulation according to the configuration set by the class constructor, run it, and verify the result.
Implements ns3::TestCase.
Definition at line 155 of file lte-test-radio-link-failure.cc.
References ns3::LteHelper::ActivateDedicatedEpsBearer(), ns3::ApplicationContainer::Add(), ns3::EpcTft::Add(), ns3::ListPositionAllocator::Add(), ns3::Ipv4StaticRouting::AddNetworkRouteTo(), ns3::Ipv4AddressHelper::Assign(), ns3::LteHelper::AssignStreams(), ns3::NoBackhaulEpcHelper::AssignUeIpv4Address(), ns3::LteHelper::Attach(), CheckConnected(), CheckIdle(), ns3::Config::Connect(), ConnectionEstablishedEnbCallback(), ConnectionEstablishedUeCallback(), ConnectionReleaseAtEnbCallback(), ns3::NodeContainer::Create(), ns3::TestCase::CreateTempDirFilename(), ns3::LteHelper::EnableTraces(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::DataRateValue::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::DataRate::GetBitRate(), ns3::TestCase::GetName(), ns3::Object::GetObject(), ns3::NoBackhaulEpcHelper::GetPgwNode(), ns3::Time::GetSeconds(), ns3::Ipv4StaticRoutingHelper::GetStaticRouting(), ns3::NoBackhaulEpcHelper::GetUeDefaultGatewayAddress(), ns3::UdpClientHelper::Install(), ns3::PointToPointHelper::Install(), ns3::PacketSinkHelper::Install(), ns3::InternetStackHelper::Install(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), JumpAway(), ns3::EpcTft::PacketFilter::localPortEnd, ns3::EpcTft::PacketFilter::localPortStart, m_checkConnectedList, m_enbPositionList, m_isIdealRrc, m_numEnbs, m_numUes, m_radioLinkFailureDetected, m_simTime, m_ueJumpAwayPosition, m_ueMobility, m_uePositionList, ns3::MakeCallback(), third::mobility, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC(), NS_TEST_ASSERT_MSG_EQ, packetSize, PhySyncDetectionCallback(), RadioLinkFailureCallback(), ns3::EpcTft::PacketFilter::remotePortEnd, ns3::EpcTft::PacketFilter::remotePortStart, ns3::Seconds(), ns3::UdpClientHelper::SetAttribute(), ns3::Ipv4AddressHelper::SetBase(), ns3::PointToPointHelper::SetChannelAttribute(), ns3::Config::SetDefault(), ns3::Ipv4StaticRouting::SetDefaultRoute(), ns3::PointToPointHelper::SetDeviceAttribute(), ns3::LteHelper::SetEnbDeviceAttribute(), ns3::LteHelper::SetEpcHelper(), ns3::LteHelper::SetPathlossModelAttribute(), ns3::LteHelper::SetPathlossModelType(), ns3::LteHelper::SetSchedulerType(), ns3::ApplicationContainer::Start(), and UeStateTransitionCallback().
JumpAway()
void LteRadioLinkFailureTestCase::JumpAway (Vector UeJumpAwayPositionList) private
Jump away function.
Parameters
UeJumpAwayPositionList A list of positions where UE would jump
Definition at line 393 of file lte-test-radio-link-failure.cc.
References m_ueMobility, NS_LOG_FUNCTION, and ns3::MobilityModel::SetPosition().
Referenced by DoRun().
PhySyncDetectionCallback()
void LteRadioLinkFailureTestCase::PhySyncDetectionCallback (std::string context, uint64_t imsi, uint16_t rnti, uint16_t cellId, std::string type, uint8_t count) private
This callback function is executed when UE RRC receives an in-sync or out-of-sync indication.
Parameters
context the context string
imsi the IMSI
rnti the RNTI
cellId the cell ID
type in-sync or out-of-sync indication
count the number of in-sync or out-of-sync indications
Definition at line 556 of file lte-test-radio-link-failure.cc.
References m_numOfInSyncIndications, m_numOfOutOfSyncIndications, and NS_LOG_FUNCTION.
Referenced by DoRun().
RadioLinkFailureCallback()
void LteRadioLinkFailureTestCase::RadioLinkFailureCallback (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti) private
This callback function is executed when radio link failure is detected.
Parameters
context the context string
imsi the IMSI
rnti the RNTI
cellId the cell ID
Definition at line 570 of file lte-test-radio-link-failure.cc.
References m_numOfInSyncIndications, m_numOfOutOfSyncIndications, m_radioLinkFailureDetected, ns3::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_TEST_ASSERT_MSG_EQ, and NS_TEST_ASSERT_MSG_LT.
Referenced by DoRun().
UeStateTransitionCallback()
void LteRadioLinkFailureTestCase::UeStateTransitionCallback (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti, LteUeRrc::State oldState, LteUeRrc::State newState) private
State transition callback function.
Parameters
context the context string
imsi the IMSI
cellId the cell ID
rnti the RNTI
oldState the old state
newState the new state
Definition at line 521 of file lte-test-radio-link-failure.cc.
References m_lastState, and NS_LOG_FUNCTION.
Referenced by DoRun().
Member Data Documentation
m_checkConnectedList
std::vector<Time> LteRadioLinkFailureTestCase::m_checkConnectedList private
the time at which UEs should have an active RRC connection
Definition at line 195 of file lte-test-radio-link-failure.h.
Referenced by DoRun().
m_enbPositionList
std::vector<Vector> LteRadioLinkFailureTestCase::m_enbPositionList private
Position of the eNodeBs.
Definition at line 194 of file lte-test-radio-link-failure.h.
Referenced by DoRun().
m_isIdealRrc
bool LteRadioLinkFailureTestCase::m_isIdealRrc private
whether the LTE is configured to use ideal RRC
Definition at line 192 of file lte-test-radio-link-failure.h.
Referenced by DoRun().
m_lastState
LteUeRrc::State LteRadioLinkFailureTestCase::m_lastState private
The current UE RRC state.
Definition at line 199 of file lte-test-radio-link-failure.h.
Referenced by LteRadioLinkFailureTestCase(), and UeStateTransitionCallback().
m_numEnbs
uint32_t LteRadioLinkFailureTestCase::m_numEnbs private
number of eNodeBs
Definition at line 189 of file lte-test-radio-link-failure.h.
Referenced by DoRun().
m_numOfInSyncIndications
uint32_t LteRadioLinkFailureTestCase::m_numOfInSyncIndications private
number of in-sync indications detected
Definition at line 202 of file lte-test-radio-link-failure.h.
Referenced by LteRadioLinkFailureTestCase(), ConnectionEstablishedUeCallback(), PhySyncDetectionCallback(), and RadioLinkFailureCallback().
m_numOfOutOfSyncIndications
uint32_t LteRadioLinkFailureTestCase::m_numOfOutOfSyncIndications private
number of out-of-sync indications detected
Definition at line 203 of file lte-test-radio-link-failure.h.
Referenced by LteRadioLinkFailureTestCase(), ConnectionEstablishedUeCallback(), PhySyncDetectionCallback(), and RadioLinkFailureCallback().
m_numUes
uint32_t LteRadioLinkFailureTestCase::m_numUes private
number of UEs
Definition at line 190 of file lte-test-radio-link-failure.h.
Referenced by DoRun().
m_radioLinkFailureDetected
bool LteRadioLinkFailureTestCase::m_radioLinkFailureDetected private
true if radio link fails
Definition at line 201 of file lte-test-radio-link-failure.h.
Referenced by LteRadioLinkFailureTestCase(), DoRun(), and RadioLinkFailureCallback().
m_simTime
Time LteRadioLinkFailureTestCase::m_simTime private
simulation time
Definition at line 191 of file lte-test-radio-link-failure.h.
Referenced by DoRun().
m_ueJumpAwayPosition
Vector LteRadioLinkFailureTestCase::m_ueJumpAwayPosition private
Position where the UE(s) would jump.
Definition at line 196 of file lte-test-radio-link-failure.h.
Referenced by DoRun().
m_ueMobility
Ptr<MobilityModel> LteRadioLinkFailureTestCase::m_ueMobility private
UE mobility model.
Definition at line 204 of file lte-test-radio-link-failure.h.
Referenced by DoRun(), and JumpAway().
m_uePositionList
std::vector<Vector> LteRadioLinkFailureTestCase::m_uePositionList private
Position of the UEs.
Definition at line 193 of file lte-test-radio-link-failure.h.
Referenced by DoRun().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-radio-link-failure.h
src/lte/test/lte-test-radio-link-failure.cc