ns-3: AttributeObjectTest Class Reference
AttributeObjectTest Class Reference
Public Types
enum Test_e { TEST_A, TEST_B, TEST_C }
Public Member Functions
AttributeObjectTest (void)
virtual ~AttributeObjectTest (void)
void AddToMap1 (uint32_t i)
void AddToVector1 (void)
void AddToVector2 (void)
void InvokeCb (double a, int b, float c)
void InvokeCbValue (int8_t a)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef void(* NumericTracedCallback) (double, int, float)
Private Member Functions
Test_e DoGetEnum (void) const
int16_t DoGetInt16 (void) const
int8_t DoGetIntSrc (void) const
bool DoGetTestB (void) const
Ptr< Derived > DoGetVector (std::size_t i) const
std::size_t DoGetVectorN (void) const
bool DoSetEnum (Test_e v)
void DoSetInt16 (int16_t v)
bool DoSetIntSrc (int8_t v)
void DoSetTestB (bool v)
Private Attributes
TracedValue< bool > m_boolSrc
bool m_boolTest
bool m_boolTestA
TracedCallback< double, int, float > m_cb
Callback< void, int8_t > m_cbValue
TracedValue< double > m_doubleSrc
enum Test_e m_enum
enum Test_e m_enumSetGet
TracedValue< enum Test_e > m_enumSrc
float m_float
int16_t m_int16
int16_t m_int16SetGet
int16_t m_int16WithBounds
TracedValue< int8_t > m_intSrc1
TracedValue< int8_t > m_intSrc2
std::map< uint32_t, Ptr< Derived > > m_map1
Ptr< Derived > m_ptr
Ptr< Derived > m_ptrInitialized
Ptr< Derived > m_ptrInitialized2
Ptr< RandomVariableStream > m_random
Time m_timeWithBounds
uint8_t m_uint8
TracedValue< uint8_t > m_uintSrc
TracedValue< ValueClassTest > m_valueSrc
std::vector< Ptr< Derived > > m_vector1
std::vector< Ptr< Derived > > m_vector2
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 98 of file attribute-test-suite.cc.
Member Typedef Documentation
NumericTracedCallback
typedef void(* AttributeObjectTest::NumericTracedCallback) (double, int, float) private
Definition at line 338 of file attribute-test-suite.cc.
Member Enumeration Documentation
Test_e
enum AttributeObjectTest::Test_e
Enumerator
TEST_A
TEST_B
TEST_C
Definition at line 101 of file attribute-test-suite.cc.
Constructor & Destructor Documentation
AttributeObjectTest()
AttributeObjectTest::AttributeObjectTest (void) inline
Definition at line 236 of file attribute-test-suite.cc.
References NS_UNUSED.
~AttributeObjectTest()
virtual AttributeObjectTest::~AttributeObjectTest (void) inline virtual
Definition at line 247 of file attribute-test-suite.cc.
Member Function Documentation
AddToMap1()
void AttributeObjectTest::AddToMap1 (uint32_t i) inline
Definition at line 259 of file attribute-test-suite.cc.
Referenced by ObjectMapAttributeTestCase::DoRun().
AddToVector1()
void AttributeObjectTest::AddToVector1 (void) inline
Definition at line 250 of file attribute-test-suite.cc.
Referenced by ObjectVectorAttributeTestCase::DoRun().
AddToVector2()
void AttributeObjectTest::AddToVector2 (void) inline
Definition at line 254 of file attribute-test-suite.cc.
DoGetEnum()
Test_e AttributeObjectTest::DoGetEnum (void) const inline private
Definition at line 316 of file attribute-test-suite.cc.
Referenced by GetTypeId().
DoGetInt16()
int16_t AttributeObjectTest::DoGetInt16 (void) const inline private
Definition at line 286 of file attribute-test-suite.cc.
Referenced by GetTypeId().
DoGetIntSrc()
int8_t AttributeObjectTest::DoGetIntSrc (void) const inline private
Definition at line 307 of file attribute-test-suite.cc.
Referenced by GetTypeId().
DoGetTestB()
bool AttributeObjectTest::DoGetTestB (void) const inline private
Definition at line 282 of file attribute-test-suite.cc.
Referenced by GetTypeId().
DoGetVector()
Ptr<Derived> AttributeObjectTest::DoGetVector (std::size_t i) const inline private
Definition at line 298 of file attribute-test-suite.cc.
Referenced by GetTypeId().
DoGetVectorN()
std::size_t AttributeObjectTest::DoGetVectorN (void) const inline private
Definition at line 294 of file attribute-test-suite.cc.
Referenced by GetTypeId().
DoSetEnum()
bool AttributeObjectTest::DoSetEnum (Test_e v) inline private
Definition at line 311 of file attribute-test-suite.cc.
Referenced by GetTypeId().
DoSetInt16()
void AttributeObjectTest::DoSetInt16 (int16_t v) inline private
Definition at line 290 of file attribute-test-suite.cc.
Referenced by GetTypeId().
DoSetIntSrc()
bool AttributeObjectTest::DoSetIntSrc (int8_t v) inline private
Definition at line 302 of file attribute-test-suite.cc.
Referenced by GetTypeId().
DoSetTestB()
void AttributeObjectTest::DoSetTestB (bool v) inline private
Definition at line 278 of file attribute-test-suite.cc.
Referenced by GetTypeId().
GetTypeId()
static TypeId AttributeObjectTest::GetTypeId (void) inline static
Definition at line 107 of file attribute-test-suite.cc.
References ns3::TypeId::AddConstructor(), DoGetEnum(), DoGetInt16(), DoGetIntSrc(), DoGetTestB(), DoGetVector(), DoGetVectorN(), DoSetEnum(), DoSetInt16(), DoSetIntSrc(), DoSetTestB(), m_boolSrc, m_boolTest, m_cb, m_cbValue, m_doubleSrc, m_enum, m_enumSrc, m_float, m_int16, m_int16WithBounds, m_intSrc1, m_map1, m_ptr, m_ptrInitialized, m_ptrInitialized2, m_random, m_timeWithBounds, m_uint8, m_uintSrc, m_valueSrc, m_vector1, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeCallbackAccessor(), ns3::MakeCallbackChecker(), ns3::MakeDoubleAccessor(), ns3::MakeEnumAccessor(), ns3::MakeEnumChecker(), ns3::MakeIntegerAccessor(), ns3::MakeObjectMapAccessor(), ns3::MakeObjectVectorAccessor(), ns3::MakePointerAccessor(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), MakeValueClassTestAccessor(), MakeValueClassTestChecker(), and ns3::Seconds().
InvokeCb()
void AttributeObjectTest::InvokeCb (double a, int b, float c) inline
Definition at line 264 of file attribute-test-suite.cc.
Referenced by TracedCallbackTestCase::DoRun().
InvokeCbValue()
void AttributeObjectTest::InvokeCbValue (int8_t a) inline
Definition at line 269 of file attribute-test-suite.cc.
Referenced by CallbackValueTestCase::DoRun().
Member Data Documentation
m_boolSrc
TracedValue<bool> AttributeObjectTest::m_boolSrc private
Definition at line 347 of file attribute-test-suite.cc.
Referenced by GetTypeId().
m_boolTest
bool AttributeObjectTest::m_boolTest private
Definition at line 322 of file attribute-test-suite.cc.
Referenced by GetTypeId().
m_boolTestA
bool AttributeObjectTest::m_boolTestA private
Definition at line 321 of file attribute-test-suite.cc.
m_cb
TracedCallback<double, int, float> AttributeObjectTest::m_cb private
Definition at line 339 of file attribute-test-suite.cc.
Referenced by GetTypeId().
m_cbValue
Callback<void,int8_t> AttributeObjectTest::m_cbValue private
Definition at line 334 of file attribute-test-suite.cc.
Referenced by GetTypeId().
m_doubleSrc
TracedValue<double> AttributeObjectTest::m_doubleSrc private
Definition at line 346 of file attribute-test-suite.cc.
Referenced by GetTypeId().
m_enum
enum Test_e AttributeObjectTest::m_enum private
Definition at line 327 of file attribute-test-suite.cc.
Referenced by GetTypeId().
m_enumSetGet
enum Test_e AttributeObjectTest::m_enumSetGet private
Definition at line 327 of file attribute-test-suite.cc.
m_enumSrc
TracedValue<enum Test_e> AttributeObjectTest::m_enumSrc private
Definition at line 345 of file attribute-test-suite.cc.
Referenced by GetTypeId().
m_float
float AttributeObjectTest::m_float private
Definition at line 327 of file attribute-test-suite.cc.
Referenced by GetTypeId().
m_int16
int16_t AttributeObjectTest::m_int16 private
Definition at line 323 of file attribute-test-suite.cc.
Referenced by GetTypeId().
m_int16SetGet
int16_t AttributeObjectTest::m_int16SetGet private
Definition at line 325 of file attribute-test-suite.cc.
m_int16WithBounds
int16_t AttributeObjectTest::m_int16WithBounds private
Definition at line 324 of file attribute-test-suite.cc.
Referenced by GetTypeId().
m_intSrc1
TracedValue<int8_t> AttributeObjectTest::m_intSrc1 private
Definition at line 335 of file attribute-test-suite.cc.
Referenced by GetTypeId().
m_intSrc2
TracedValue<int8_t> AttributeObjectTest::m_intSrc2 private
Definition at line 336 of file attribute-test-suite.cc.
m_map1
std::map<uint32_t, Ptr<Derived> > AttributeObjectTest::m_map1 private
Definition at line 333 of file attribute-test-suite.cc.
Referenced by GetTypeId().
m_ptr
Ptr<Derived> AttributeObjectTest::m_ptr private
Definition at line 341 of file attribute-test-suite.cc.
Referenced by GetTypeId().
m_ptrInitialized
Ptr<Derived> AttributeObjectTest::m_ptrInitialized private
Definition at line 342 of file attribute-test-suite.cc.
Referenced by GetTypeId().
m_ptrInitialized2
Ptr<Derived> AttributeObjectTest::m_ptrInitialized2 private
Definition at line 343 of file attribute-test-suite.cc.
Referenced by GetTypeId().
m_random
Ptr<RandomVariableStream> AttributeObjectTest::m_random private
Definition at line 330 of file attribute-test-suite.cc.
Referenced by GetTypeId().
m_timeWithBounds
Time AttributeObjectTest::m_timeWithBounds private
Definition at line 348 of file attribute-test-suite.cc.
Referenced by GetTypeId().
m_uint8
uint8_t AttributeObjectTest::m_uint8 private
Definition at line 326 of file attribute-test-suite.cc.
Referenced by GetTypeId().
m_uintSrc
TracedValue<uint8_t> AttributeObjectTest::m_uintSrc private
Definition at line 344 of file attribute-test-suite.cc.
Referenced by GetTypeId().
m_valueSrc
TracedValue<ValueClassTest> AttributeObjectTest::m_valueSrc private
Definition at line 340 of file attribute-test-suite.cc.
Referenced by GetTypeId().
m_vector1
std::vector<Ptr<Derived> > AttributeObjectTest::m_vector1 private
Definition at line 331 of file attribute-test-suite.cc.
Referenced by GetTypeId().
m_vector2
std::vector<Ptr<Derived> > AttributeObjectTest::m_vector2 private
Definition at line 332 of file attribute-test-suite.cc.
The documentation for this class was generated from the following file:
src/core/test/attribute-test-suite.cc