ns-3: Receiver Class Reference
Receiver Class Reference
#include "wifi-example-apps.h"
Public Member Functions
Receiver ()
virtual ~Receiver ()
void SetCounter (Ptr< CounterCalculator<> > calc)
void SetDelayTracker (Ptr< TimeMinMaxAvgTotalCalculator > delay)
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Application
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void Receive (Ptr< Socket > socket)
virtual void StartApplication (void)
Application specific startup code.
virtual void StopApplication (void)
Application specific shutdown code.
Private Attributes
Ptr< CounterCalculator<> > m_calc
Ptr< TimeMinMaxAvgTotalCalculator > m_delay
uint32_t m_port
Ptr< Socket > m_socket
Additional Inherited Members
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 73 of file wifi-example-apps.h.
Constructor & Destructor Documentation
Receiver()
Receiver::Receiver ()
Definition at line 171 of file wifi-example-apps.cc.
References m_socket, and NS_LOG_FUNCTION_NOARGS.
~Receiver()
Receiver::~Receiver () virtual
Definition at line 179 of file wifi-example-apps.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
DoDispose()
void Receiver::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Application.
Definition at line 185 of file wifi-example-apps.cc.
References m_socket, and NS_LOG_FUNCTION_NOARGS.
GetTypeId()
TypeId Receiver::GetTypeId (void) static
Definition at line 158 of file wifi-example-apps.cc.
References m_port, ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
Receive()
void Receiver::Receive (Ptr< Socket > socket) private
Definition at line 239 of file wifi-example-apps.cc.
References ns3::Packet::FindFirstMatchingByteTag(), ns3::Packet::GetSize(), TimestampTag::GetTimestamp(), m_calc, m_delay, ns3::Now(), NS_LOG_INFO, ns3::Socket::RecvFrom(), ns3::CounterCalculator< T >::Update(), and ns3::TimeMinMaxAvgTotalCalculator::Update().
Referenced by StartApplication().
SetCounter()
void Receiver::SetCounter (Ptr< CounterCalculator<> > calc)
Definition at line 226 of file wifi-example-apps.cc.
References m_calc.
SetDelayTracker()
void Receiver::SetDelayTracker (Ptr< TimeMinMaxAvgTotalCalculator > delay)
Definition at line 232 of file wifi-example-apps.cc.
References m_delay.
StartApplication()
void Receiver::StartApplication (void) private virtual
Application specific startup code.
The StartApplication method is called at the start time specified by Start This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 195 of file wifi-example-apps.cc.
References ns3::Socket::Bind(), ns3::SocketFactory::CreateSocket(), ns3::Application::GetNode(), ns3::Object::GetObject(), m_port, m_socket, ns3::MakeCallback(), NS_LOG_FUNCTION_NOARGS, Receive(), and ns3::Socket::SetRecvCallback().
StopApplication()
void Receiver::StopApplication (void) private virtual
Application specific shutdown code.
The StopApplication method is called at the stop time specified by Stop This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 214 of file wifi-example-apps.cc.
References m_socket, ns3::MakeNullCallback(), NS_LOG_FUNCTION_NOARGS, and ns3::Socket::SetRecvCallback().
Member Data Documentation
m_calc
Ptr<CounterCalculator<> > Receiver::m_calc private
Definition at line 95 of file wifi-example-apps.h.
Referenced by Receive(), and SetCounter().
m_delay
Ptr<TimeMinMaxAvgTotalCalculator> Receiver::m_delay private
Definition at line 96 of file wifi-example-apps.h.
Referenced by Receive(), and SetDelayTracker().
m_port
uint32_t Receiver::m_port private
Definition at line 93 of file wifi-example-apps.h.
Referenced by GetTypeId(), and StartApplication().
m_socket
Ptr<Socket> Receiver::m_socket private
Definition at line 91 of file wifi-example-apps.h.
Referenced by Receiver(), DoDispose(), StartApplication(), and StopApplication().
The documentation for this class was generated from the following files:
examples/stats/wifi-example-apps.h
examples/stats/wifi-example-apps.cc