ns-3: RrcHeaderTestCase Class Reference
RrcHeaderTestCase Class Reference abstract
LTE Models » lte module tests | Test suites
This class provides common functions to be inherited by the children TestCases.
Public Member Functions
RrcHeaderTestCase (std::string s)
Constructor.
void AssertEqualRadioResourceConfigDedicated (LteRrcSap::RadioResourceConfigDedicated rrcd1, LteRrcSap::RadioResourceConfigDedicated rrcd2)
Assert equal radio resource config dedicated.
LteRrcSap::RadioResourceConfigDedicated CreateRadioResourceConfigDedicated ()
Create radio resource config dedicated.
virtual void DoRun (void)=0
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Attributes
Ptr< Packet > packet
the packet
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
This class provides common functions to be inherited by the children TestCases.
Definition at line 116 of file test-asn1-encoding.cc.
Constructor & Destructor Documentation
RrcHeaderTestCase()
RrcHeaderTestCase::RrcHeaderTestCase (std::string s)
Constructor.
Parameters
s the reference name
Definition at line 141 of file test-asn1-encoding.cc.
Member Function Documentation
AssertEqualRadioResourceConfigDedicated()
void RrcHeaderTestCase::AssertEqualRadioResourceConfigDedicated (LteRrcSap::RadioResourceConfigDedicated rrcd1, LteRrcSap::RadioResourceConfigDedicated rrcd2)
Assert equal radio resource config dedicated.
Parameters
rrcd1 LteRrcSap::RadioResourceConfigDedicated # 1
rrcd2 LteRrcSap::RadioResourceConfigDedicated # 2
Definition at line 200 of file test-asn1-encoding.cc.
References ns3::LteRrcSap::PhysicalConfigDedicated::antennaInfo, ns3::LteRrcSap::RadioResourceConfigDedicated::drbToAddModList, ns3::LteRrcSap::RadioResourceConfigDedicated::drbToReleaseList, ns3::LteRrcSap::PhysicalConfigDedicated::haveAntennaInfoDedicated, ns3::LteRrcSap::PhysicalConfigDedicated::havePdschConfigDedicated, ns3::LteRrcSap::RadioResourceConfigDedicated::havePhysicalConfigDedicated, ns3::LteRrcSap::PhysicalConfigDedicated::haveSoundingRsUlConfigDedicated, NS_TEST_ASSERT_MSG_EQ, ns3::LteRrcSap::PdschConfigDedicated::pa, ns3::LteRrcSap::PhysicalConfigDedicated::pdschConfigDedicated, ns3::LteRrcSap::RadioResourceConfigDedicated::physicalConfigDedicated, ns3::LteRrcSap::PhysicalConfigDedicated::soundingRsUlConfigDedicated, ns3::LteRrcSap::RadioResourceConfigDedicated::srbToAddModList, ns3::LteRrcSap::SoundingRsUlConfigDedicated::srsBandwidth, ns3::LteRrcSap::SoundingRsUlConfigDedicated::srsConfigIndex, ns3::LteRrcSap::AntennaInfoDedicated::transmissionMode, and ns3::LteRrcSap::SoundingRsUlConfigDedicated::type.
Referenced by RrcConnectionSetupTestCase::DoRun(), RrcConnectionReconfigurationTestCase::DoRun(), HandoverPreparationInfoTestCase::DoRun(), and RrcConnectionReestablishmentTestCase::DoRun().
CreateRadioResourceConfigDedicated()
LteRrcSap::RadioResourceConfigDedicated RrcHeaderTestCase::CreateRadioResourceConfigDedicated ()
Create radio resource config dedicated.
Returns
LteRrcSap::RadioResourceConfigDedicated
Definition at line 146 of file test-asn1-encoding.cc.
References ns3::LteRrcSap::PhysicalConfigDedicated::antennaInfo, ns3::LteRrcSap::LogicalChannelConfig::bucketSizeDurationMs, ns3::LteRrcSap::RlcConfig::choice, ns3::LteRrcSap::DrbToAddMod::drbIdentity, ns3::LteRrcSap::RadioResourceConfigDedicated::drbToAddModList, ns3::LteRrcSap::RadioResourceConfigDedicated::drbToReleaseList, ns3::LteRrcSap::DrbToAddMod::epsBearerIdentity, ns3::LteRrcSap::PhysicalConfigDedicated::haveAntennaInfoDedicated, ns3::LteRrcSap::PhysicalConfigDedicated::havePdschConfigDedicated, ns3::LteRrcSap::RadioResourceConfigDedicated::havePhysicalConfigDedicated, ns3::LteRrcSap::PhysicalConfigDedicated::haveSoundingRsUlConfigDedicated, ns3::LteRrcSap::SrbToAddMod::logicalChannelConfig, ns3::LteRrcSap::DrbToAddMod::logicalChannelConfig, ns3::LteRrcSap::LogicalChannelConfig::logicalChannelGroup, ns3::LteRrcSap::DrbToAddMod::logicalChannelIdentity, ns3::LteRrcSap::PdschConfigDedicated::pa, ns3::LteRrcSap::PhysicalConfigDedicated::pdschConfigDedicated, ns3::LteRrcSap::RadioResourceConfigDedicated::physicalConfigDedicated, ns3::LteRrcSap::LogicalChannelConfig::prioritizedBitRateKbps, ns3::LteRrcSap::LogicalChannelConfig::priority, ns3::LteRrcSap::DrbToAddMod::rlcConfig, ns3::LteRrcSap::PhysicalConfigDedicated::soundingRsUlConfigDedicated, ns3::LteRrcSap::SrbToAddMod::srbIdentity, ns3::LteRrcSap::RadioResourceConfigDedicated::srbToAddModList, ns3::LteRrcSap::SoundingRsUlConfigDedicated::srsBandwidth, ns3::LteRrcSap::SoundingRsUlConfigDedicated::srsConfigIndex, ns3::LteRrcSap::AntennaInfoDedicated::transmissionMode, and ns3::LteRrcSap::SoundingRsUlConfigDedicated::type.
Referenced by RrcConnectionSetupTestCase::DoRun(), RrcConnectionReconfigurationTestCase::DoRun(), HandoverPreparationInfoTestCase::DoRun(), and RrcConnectionReestablishmentTestCase::DoRun().
DoRun()
virtual void RrcHeaderTestCase::DoRun (void) pure virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Implemented in MeasurementReportTestCase, RrcConnectionRejectTestCase, RrcConnectionReestablishmentCompleteTestCase, RrcConnectionReestablishmentTestCase, RrcConnectionReestablishmentRequestTestCase, HandoverPreparationInfoTestCase, RrcConnectionReconfigurationTestCase, RrcConnectionReconfigurationCompleteTestCase, RrcConnectionSetupCompleteTestCase, RrcConnectionSetupTestCase, and RrcConnectionRequestTestCase.
Member Data Documentation
packet
Ptr<Packet> RrcHeaderTestCase::packet protected
the packet
Definition at line 138 of file test-asn1-encoding.cc.
Referenced by RrcConnectionRequestTestCase::DoRun(), RrcConnectionSetupTestCase::DoRun(), RrcConnectionSetupCompleteTestCase::DoRun(), RrcConnectionReconfigurationCompleteTestCase::DoRun(), RrcConnectionReconfigurationTestCase::DoRun(), HandoverPreparationInfoTestCase::DoRun(), RrcConnectionReestablishmentRequestTestCase::DoRun(), RrcConnectionReestablishmentTestCase::DoRun(), RrcConnectionReestablishmentCompleteTestCase::DoRun(), RrcConnectionRejectTestCase::DoRun(), and MeasurementReportTestCase::DoRun().
The documentation for this class was generated from the following file:
src/lte/test/test-asn1-encoding.cc