ns-3: AnnexC_TestCase Class Reference
AnnexC_TestCase Class Reference
WAVE module » wave module tests | Test suites
The Annex C of IEEE 1609.4 : "Avoiding transmission at scheduled guard intervals" This feature is implemented in WaveMacLow::StartTransmission method.
Public Member Functions
AnnexC_TestCase ()
virtual ~AnnexC_TestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
bool Receive (Ptr< NetDevice > dev, Ptr< const Packet > pkt, uint16_t mode, const Address &sender)
Receive function.
void SendPacket (uint32_t packetSize, const TxInfo &txInfo, uint32_t sequence)
Send packet function.
Private Attributes
NetDeviceContainer m_devices
devices
Ptr< WaveNetDevice > m_receiver
receiver
Ptr< WaveNetDevice > m_sender
sender
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
The Annex C of IEEE 1609.4 : "Avoiding transmission at scheduled guard intervals" This feature is implemented in WaveMacLow::StartTransmission method.
Definition at line 1022 of file mac-extension-test-suite.cc.
Constructor & Destructor Documentation
AnnexC_TestCase()
AnnexC_TestCase::AnnexC_TestCase ()
Definition at line 1052 of file mac-extension-test-suite.cc.
~AnnexC_TestCase()
AnnexC_TestCase::~AnnexC_TestCase () virtual
Definition at line 1057 of file mac-extension-test-suite.cc.
Member Function Documentation
DoRun()
void AnnexC_TestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 1146 of file mac-extension-test-suite.cc.
References CCH, TestCaseHelper::CreatWaveDevice(), EXTENDED_ALTERNATING, ns3::NetDeviceContainer::Get(), m_devices, m_receiver, m_sender, ns3::MakeCallback(), ns3::MilliSeconds(), Receive(), SCH1, ns3::Seconds(), SendPacket(), ns3::WaveNetDevice::SetReceiveCallback(), and ns3::WIFI_PREAMBLE_LONG.
Receive()
bool AnnexC_TestCase::Receive (Ptr< NetDevice > dev, Ptr< const Packet > pkt, uint16_t mode, const Address & sender) private
Receive function.
Parameters
dev the device
pkt the packet
mode the mode
sender the sender address
Returns
true if successful
Definition at line 1091 of file mac-extension-test-suite.cc.
References ns3::Packet::CopyData(), data, aloha::duration, ns3::Packet::GetSize(), ns3::Now(), NS_TEST_EXPECT_MSG_GT, NS_TEST_EXPECT_MSG_LT, and ns3::TimeStep().
Referenced by DoRun().
SendPacket()
void AnnexC_TestCase::SendPacket (uint32_t packetSize, const TxInfo & txInfo, uint32_t sequence) private
Send packet function.
Parameters
packetSize the packet size
txInfo the transmit info
sequence the sequence
Definition at line 1062 of file mac-extension-test-suite.cc.
References data, ns3::WaveNetDevice::GetAddress(), ns3::Time::GetTimeStep(), m_receiver, m_sender, ns3::Now(), packetSize, and ns3::WaveNetDevice::SendX().
Referenced by DoRun().
Member Data Documentation
m_devices
NetDeviceContainer AnnexC_TestCase::m_devices private
devices
Definition at line 1047 of file mac-extension-test-suite.cc.
Referenced by DoRun().
m_receiver
Ptr<WaveNetDevice> AnnexC_TestCase::m_receiver private
receiver
Definition at line 1049 of file mac-extension-test-suite.cc.
Referenced by DoRun(), and SendPacket().
m_sender
Ptr<WaveNetDevice> AnnexC_TestCase::m_sender private
sender
Definition at line 1048 of file mac-extension-test-suite.cc.
Referenced by DoRun(), and SendPacket().
The documentation for this class was generated from the following file:
src/wave/test/mac-extension-test-suite.cc