ns-3: SpectrumWifiPhyBasicTest Class Reference
SpectrumWifiPhyBasicTest Class Reference
Wifi Models » wifi module tests | Test suites
Spectrum Wifi Phy Basic Test.
Public Member Functions
SpectrumWifiPhyBasicTest ()
SpectrumWifiPhyBasicTest (std::string name)
Constructor.
virtual ~SpectrumWifiPhyBasicTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Member Functions
virtual void DoSetup (void)
Implementation to do any local setup required for this TestCase.
Ptr< SpectrumSignalParameters > MakeSignal (double txPowerWatts)
Make signal function.
void SendSignal (double txPowerWatts)
Send signal function.
void SpectrumWifiPhyRxFailure (Ptr< WifiPsdu > psdu)
void SpectrumWifiPhyRxSuccess (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector, std::vector< bool > statusPerMpdu)
Spectrum wifi receive success function.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Protected Attributes
uint32_t m_count
count
Ptr< SpectrumWifiPhy > m_phy
Phy.
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Detailed Description
Spectrum Wifi Phy Basic Test.
Definition at line 47 of file spectrum-wifi-phy-test.cc.
Constructor & Destructor Documentation
SpectrumWifiPhyBasicTest() [1/2]
SpectrumWifiPhyBasicTest::SpectrumWifiPhyBasicTest ()
Definition at line 92 of file spectrum-wifi-phy-test.cc.
SpectrumWifiPhyBasicTest() [2/2]
SpectrumWifiPhyBasicTest::SpectrumWifiPhyBasicTest (std::string name)
Constructor.
Parameters
name reference name
Definition at line 98 of file spectrum-wifi-phy-test.cc.
~SpectrumWifiPhyBasicTest()
SpectrumWifiPhyBasicTest::~SpectrumWifiPhyBasicTest () virtual
Definition at line 152 of file spectrum-wifi-phy-test.cc.
Member Function Documentation
DoRun()
void SpectrumWifiPhyBasicTest::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Reimplemented in SpectrumWifiPhyListenerTest.
Definition at line 173 of file spectrum-wifi-phy-test.cc.
References m_count, ns3::MicroSeconds(), NS_TEST_ASSERT_MSG_EQ, ns3::Seconds(), and SendSignal().
DoSetup()
void SpectrumWifiPhyBasicTest::DoSetup (void) protected virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test setup before DoRun is invoked.
Reimplemented from ns3::TestCase.
Reimplemented in SpectrumWifiPhyListenerTest.
Definition at line 159 of file spectrum-wifi-phy-test.cc.
References CHANNEL_NUMBER, ns3::SpectrumWifiPhy::ConfigureStandard(), FREQUENCY, m_phy, ns3::MakeCallback(), ns3::SpectrumWifiPhy::SetChannelNumber(), ns3::WifiPhy::SetErrorRateModel(), ns3::SpectrumWifiPhy::SetFrequency(), ns3::WifiPhy::SetReceiveErrorCallback(), ns3::WifiPhy::SetReceiveOkCallback(), SpectrumWifiPhyRxFailure(), SpectrumWifiPhyRxSuccess(), and ns3::WIFI_PHY_STANDARD_80211n_5GHZ.
Referenced by SpectrumWifiPhyListenerTest::DoSetup().
MakeSignal()
Ptr< SpectrumSignalParameters > SpectrumWifiPhyBasicTest::MakeSignal (double txPowerWatts) protected
Make signal function.
Parameters
txPowerWatts the transmit power in watts
Returns
Ptr<SpectrumSignalParameters>
Definition at line 106 of file spectrum-wifi-phy-test.cc.
References ns3::WifiPhy::CalculateTxDuration(), CHANNEL_WIDTH, ns3::SpectrumSignalParameters::duration, FREQUENCY, ns3::WifiPhy::GetFrequency(), ns3::WifiPsdu::GetSize(), GUARD_WIDTH, m_phy, ns3::WifiSpectrumSignalParameters::ppdu, ns3::SpectrumSignalParameters::psd, ns3::WifiMacHeader::SetQosTid(), ns3::WifiMacHeader::SetType(), ns3::SpectrumSignalParameters::txPhy, ns3::WIFI_MAC_QOSDATA, and ns3::WIFI_PREAMBLE_LONG.
Referenced by SendSignal().
SendSignal()
void SpectrumWifiPhyBasicTest::SendSignal (double txPowerWatts) protected
Send signal function.
Parameters
txPowerWatts the transmit power in watts
Definition at line 133 of file spectrum-wifi-phy-test.cc.
References m_phy, MakeSignal(), and ns3::SpectrumWifiPhy::StartRx().
Referenced by DoRun(), and SpectrumWifiPhyListenerTest::DoRun().
SpectrumWifiPhyRxFailure()
void SpectrumWifiPhyBasicTest::SpectrumWifiPhyRxFailure (Ptr< WifiPsdu > psdu) protected
 Spectrum wifi receive failure function
 \param psdu the PSDU
Definition at line 146 of file spectrum-wifi-phy-test.cc.
References m_count, and NS_LOG_FUNCTION.
Referenced by DoSetup().
SpectrumWifiPhyRxSuccess()
void SpectrumWifiPhyBasicTest::SpectrumWifiPhyRxSuccess (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector, std::vector< bool > statusPerMpdu) protected
Spectrum wifi receive success function.
Parameters
psdu the PSDU
snr the SNR
txVector the transmit vector
statusPerMpdu reception status per MPDU
Definition at line 139 of file spectrum-wifi-phy-test.cc.
References m_count, and NS_LOG_FUNCTION.
Referenced by DoSetup().
Member Data Documentation
m_count
uint32_t SpectrumWifiPhyBasicTest::m_count protected
count
Definition at line 86 of file spectrum-wifi-phy-test.cc.
Referenced by DoRun(), SpectrumWifiPhyListenerTest::DoRun(), SpectrumWifiPhyRxFailure(), and SpectrumWifiPhyRxSuccess().
m_phy
Ptr<SpectrumWifiPhy> SpectrumWifiPhyBasicTest::m_phy protected
Phy.
Definition at line 61 of file spectrum-wifi-phy-test.cc.
Referenced by DoSetup(), SpectrumWifiPhyListenerTest::DoSetup(), MakeSignal(), and SendSignal().
The documentation for this class was generated from the following file:
src/wifi/test/spectrum-wifi-phy-test.cc