ns-3: ns3::LtePdcpHeader Class Reference
ns3::LtePdcpHeader Class Reference
LTE Models
The packet header for the Packet Data Convergence Protocol (PDCP) packets.
#include "lte-pdcp-header.h"
Public Types
enum { CONTROL_PDU = 0, DATA_PDU = 1 }
DcBit_t typedef.
Public Member Functions
LtePdcpHeader ()
Constructor.
~LtePdcpHeader ()
virtual uint32_t Deserialize (Buffer::Iterator start)
uint8_t GetDcBit () const
Get DC bit.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint16_t GetSequenceNumber () const
Get sequence number.
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetDcBit (uint8_t dcBit)
Set DC bit.
void SetSequenceNumber (uint16_t sequenceNumber)
Set sequence number.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Public Attributes
enum ns3::LtePdcpHeader:: { ... } DcBit_t
DcBit_t typedef.
Private Attributes
uint8_t m_dcBit
the DC bit
uint16_t m_sequenceNumber
the sequence number
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The packet header for the Packet Data Convergence Protocol (PDCP) packets.
This class has fields corresponding to those in an PDCP header as well as methods for serialization to and deserialization from a byte buffer. It follows 3GPP TS 36.323 Packet Data Convergence Protocol (PDCP) specification.
Definition at line 38 of file lte-pdcp-header.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
DcBit_t typedef.
Enumerator
CONTROL_PDU
DATA_PDU
Definition at line 77 of file lte-pdcp-header.h.
Constructor & Destructor Documentation
LtePdcpHeader()
ns3::LtePdcpHeader::LtePdcpHeader ()
Constructor.
Creates a null header
Definition at line 31 of file lte-pdcp-header.cc.
~LtePdcpHeader()
ns3::LtePdcpHeader::~LtePdcpHeader ()
Definition at line 37 of file lte-pdcp-header.cc.
References m_dcBit, and m_sequenceNumber.
Member Function Documentation
Deserialize()
uint32_t ns3::LtePdcpHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 104 of file lte-pdcp-header.cc.
References DATA_PDU, GetSerializedSize(), m_dcBit, m_sequenceNumber, NS_ASSERT, ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetDcBit()
uint8_t ns3::LtePdcpHeader::GetDcBit () const
Get DC bit.
Returns
DC bit
Definition at line 56 of file lte-pdcp-header.cc.
References m_dcBit.
GetInstanceTypeId()
TypeId ns3::LtePdcpHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 80 of file lte-pdcp-header.cc.
References GetTypeId().
GetSequenceNumber()
uint16_t ns3::LtePdcpHeader::GetSequenceNumber () const
Get sequence number.
Returns
sequence number
Definition at line 62 of file lte-pdcp-header.cc.
References m_sequenceNumber.
Referenced by ns3::LtePdcp::DoReceivePdu().
GetSerializedSize()
uint32_t ns3::LtePdcpHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 91 of file lte-pdcp-header.cc.
Referenced by Deserialize(), and ns3::LtePdcp::DoTransmitPdcpSdu().
GetTypeId()
TypeId ns3::LtePdcpHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 69 of file lte-pdcp-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::LtePdcpHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 85 of file lte-pdcp-header.cc.
References m_dcBit, and m_sequenceNumber.
Serialize()
void ns3::LtePdcpHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 96 of file lte-pdcp-header.cc.
References m_dcBit, m_sequenceNumber, visualizer.core::start(), and ns3::Buffer::Iterator::WriteU8().
SetDcBit()
void ns3::LtePdcpHeader::SetDcBit (uint8_t dcBit)
Set DC bit.
Parameters
dcBit DC bit to set
Definition at line 44 of file lte-pdcp-header.cc.
References m_dcBit.
Referenced by ns3::LtePdcp::DoTransmitPdcpSdu().
SetSequenceNumber()
void ns3::LtePdcpHeader::SetSequenceNumber (uint16_t sequenceNumber)
Set sequence number.
Parameters
sequenceNumber sequence number
Definition at line 50 of file lte-pdcp-header.cc.
References m_sequenceNumber.
Referenced by ns3::LtePdcp::DoTransmitPdcpSdu().
Member Data Documentation
DcBit_t
enum { ... } ns3::LtePdcpHeader::DcBit_t
DcBit_t typedef.
DcBit_t typedef
m_dcBit
uint8_t ns3::LtePdcpHeader::m_dcBit private
the DC bit
Definition at line 94 of file lte-pdcp-header.h.
Referenced by ~LtePdcpHeader(), Deserialize(), GetDcBit(), Print(), Serialize(), and SetDcBit().
m_sequenceNumber
uint16_t ns3::LtePdcpHeader::m_sequenceNumber private
the sequence number
Definition at line 95 of file lte-pdcp-header.h.
Referenced by ~LtePdcpHeader(), Deserialize(), GetSequenceNumber(), Print(), Serialize(), and SetSequenceNumber().
The documentation for this class was generated from the following files:
src/lte/model/lte-pdcp-header.h
src/lte/model/lte-pdcp-header.cc