ns-3: ns3::LtePdcpSapProvider Class Reference
ns3::LtePdcpSapProvider Class Reference abstract
Service Access Point (SAP) offered by the PDCP entity to the RRC entity See 3GPP 36.323 Packet Data Convergence Protocol (PDCP) specification.
#include "lte-pdcp-sap.h"
Classes
struct TransmitPdcpSduParameters
Parameters for LtePdcpSapProvider::TransmitPdcpSdu.
Public Member Functions
virtual ~LtePdcpSapProvider ()
virtual void TransmitPdcpSdu (TransmitPdcpSduParameters params)=0
Send a RRC PDU to the RDCP for transmission This method is to be called when upper RRC entity has a RRC PDU ready to send
Detailed Description
Service Access Point (SAP) offered by the PDCP entity to the RRC entity See 3GPP 36.323 Packet Data Convergence Protocol (PDCP) specification.
This is the PDCP SAP Provider (i.e. the part of the SAP that contains the PDCP methods called by the RRC)
Definition at line 35 of file lte-pdcp-sap.h.
Constructor & Destructor Documentation
~LtePdcpSapProvider()
ns3::LtePdcpSapProvider::~LtePdcpSapProvider () virtual
Definition at line 25 of file lte-pdcp-sap.cc.
Member Function Documentation
TransmitPdcpSdu()
virtual void ns3::LtePdcpSapProvider::TransmitPdcpSdu (TransmitPdcpSduParameters params) pure virtual
Send a RRC PDU to the RDCP for transmission This method is to be called when upper RRC entity has a RRC PDU ready to send
Parameters
params
Implemented in ns3::LtePdcpSpecificLtePdcpSapProvider< C >.
Referenced by ns3::LteUeRrcProtocolReal::DoSendMeasurementReport(), ns3::LteUeRrcProtocolReal::DoSendRrcConnectionReconfigurationCompleted(), ns3::LteUeRrcProtocolReal::DoSendRrcConnectionReestablishmentComplete(), ns3::LteUeRrcProtocolReal::DoSendRrcConnectionSetupCompleted(), ns3::LteTestRrc::SendData(), ns3::UeManager::SendPacket(), and ns3::LteTestRrc::Start().
The documentation for this class was generated from the following files:
src/lte/model/lte-pdcp-sap.h
src/lte/model/lte-pdcp-sap.cc