ns-3: ns3::AttributeConstructionList Class Reference
ns3::AttributeConstructionList Class Reference
Core » Object
#include "attribute-construction-list.h"
Classes
struct Item
A single Attribute triple.
Public Types
typedef std::list< struct Item >::const_iterator CIterator
Iterator type.
Public Member Functions
AttributeConstructionList ()
Constructor.
void Add (std::string name, Ptr< const AttributeChecker > checker, Ptr< AttributeValue > value)
Add an Attribute to the list.
CIterator Begin (void) const
CIterator End (void) const
Ptr< AttributeValue > Find (Ptr< const AttributeChecker > checker) const
Find an Attribute in the list from its AttributeChecker.
Private Attributes
std::list< struct Item > m_list
The list of Items.
Detailed Description
List of Attribute name, value and checker triples used to construct Objects.
Definition at line 39 of file attribute-construction-list.h.
Member Typedef Documentation
CIterator
typedef std::list<struct Item>::const_iterator ns3::AttributeConstructionList::CIterator
Iterator type.
Definition at line 53 of file attribute-construction-list.h.
Constructor & Destructor Documentation
AttributeConstructionList()
ns3::AttributeConstructionList::AttributeConstructionList ()
Constructor.
Definition at line 33 of file attribute-construction-list.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Add()
void ns3::AttributeConstructionList::Add (std::string name, Ptr< const AttributeChecker > checker, Ptr< AttributeValue > value)
Add an Attribute to the list.
Parameters
[in] name The Attribute name.
[in] checker The checker to use for this Attribute.
[in] value The AttributeValue to add.
Definition at line 39 of file attribute-construction-list.cc.
References ns3::AttributeConstructionList::Item::checker, m_list, ns3::AttributeConstructionList::Item::name, NS_LOG_FUNCTION, and ns3::AttributeConstructionList::Item::value.
Referenced by ns3::operator>>(), and ns3::ObjectFactory::Set().
Begin()
AttributeConstructionList::CIterator ns3::AttributeConstructionList::Begin (void) const
Returns
The first item in the list
Definition at line 77 of file attribute-construction-list.cc.
References m_list, and NS_LOG_FUNCTION.
Referenced by ns3::operator<<().
End()
AttributeConstructionList::CIterator ns3::AttributeConstructionList::End (void) const
Returns
The end of the list (iterator to one past the last).
Definition at line 83 of file attribute-construction-list.cc.
References m_list, and NS_LOG_FUNCTION.
Referenced by ns3::operator<<().
Find()
Ptr< AttributeValue > ns3::AttributeConstructionList::Find (Ptr< const AttributeChecker > checker) const
Find an Attribute in the list from its AttributeChecker.
Parameters
[in] checker The AttributeChecker to find. Typically this is the AttributeChecker from TypeId::AttributeInformation.
Returns
The AttributeValue.
Definition at line 62 of file attribute-construction-list.cc.
References m_list, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by ns3::ObjectBase::ConstructSelf().
Member Data Documentation
m_list
std::list<struct Item> ns3::AttributeConstructionList::m_list private
The list of Items.
Definition at line 85 of file attribute-construction-list.h.
Referenced by Add(), Begin(), End(), and Find().
The documentation for this class was generated from the following files:
src/core/model/attribute-construction-list.h
src/core/model/attribute-construction-list.cc