ns-3: SpectrumWifiPhyListenerTest Class Reference
SpectrumWifiPhyListenerTest Class Reference
Wifi Models » wifi module tests | Test suites
Spectrum Wifi Phy Listener Test.
Public Member Functions
SpectrumWifiPhyListenerTest ()
virtual ~SpectrumWifiPhyListenerTest ()
Public Member Functions inherited from SpectrumWifiPhyBasicTest
SpectrumWifiPhyBasicTest ()
SpectrumWifiPhyBasicTest (std::string name)
Constructor.
virtual ~SpectrumWifiPhyBasicTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
virtual void DoSetup (void)
Implementation to do any local setup required for this TestCase.
Private Attributes
TestPhyListener * m_listener
listener
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from SpectrumWifiPhyBasicTest
Ptr< SpectrumSignalParameters > MakeSignal (double txPowerWatts)
Make signal function.
void SendSignal (double txPowerWatts)
Send signal function.
void SpectrumWifiPhyRxFailure (Ptr< WifiPsdu > psdu)
void SpectrumWifiPhyRxSuccess (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector, std::vector< bool > statusPerMpdu)
Spectrum wifi receive success function.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Protected Attributes inherited from SpectrumWifiPhyBasicTest
uint32_t m_count
count
Ptr< SpectrumWifiPhy > m_phy
Phy.
Detailed Description
Spectrum Wifi Phy Listener Test.
Definition at line 264 of file spectrum-wifi-phy-test.cc.
Constructor & Destructor Documentation
SpectrumWifiPhyListenerTest()
SpectrumWifiPhyListenerTest::SpectrumWifiPhyListenerTest ()
Definition at line 275 of file spectrum-wifi-phy-test.cc.
~SpectrumWifiPhyListenerTest()
SpectrumWifiPhyListenerTest::~SpectrumWifiPhyListenerTest () virtual
Definition at line 280 of file spectrum-wifi-phy-test.cc.
Member Function Documentation
DoRun()
void SpectrumWifiPhyListenerTest::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Reimplemented from SpectrumWifiPhyBasicTest.
Definition at line 293 of file spectrum-wifi-phy-test.cc.
References SpectrumWifiPhyBasicTest::m_count, m_listener, TestPhyListener::m_notifyMaybeCcaBusyStart, TestPhyListener::m_notifyRxEndOk, TestPhyListener::m_notifyRxStart, NS_TEST_ASSERT_MSG_EQ, ns3::Seconds(), and SpectrumWifiPhyBasicTest::SendSignal().
DoSetup()
void SpectrumWifiPhyListenerTest::DoSetup (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test setup before DoRun is invoked.
Reimplemented from SpectrumWifiPhyBasicTest.
Definition at line 285 of file spectrum-wifi-phy-test.cc.
References SpectrumWifiPhyBasicTest::DoSetup(), m_listener, SpectrumWifiPhyBasicTest::m_phy, and ns3::WifiPhy::RegisterListener().
Member Data Documentation
m_listener
TestPhyListener* SpectrumWifiPhyListenerTest::m_listener private
listener
Definition at line 272 of file spectrum-wifi-phy-test.cc.
Referenced by DoRun(), and DoSetup().
The documentation for this class was generated from the following file:
src/wifi/test/spectrum-wifi-phy-test.cc