ns-3: ns3::InfrastructureWifiMac Class Reference
ns3::InfrastructureWifiMac Class Reference abstract
Wifi Models
#include "infrastructure-wifi-mac.h"
Public Member Functions
InfrastructureWifiMac ()
virtual ~InfrastructureWifiMac ()
virtual void Enqueue (Ptr< Packet > packet, Mac48Address to)=0
bool GetPcfSupported () const
Return whether the device supports PCF.
void SetPcfSupported (bool enable)
Enable or disable PCF support for the device.
void SetQosSupported (bool enable)
Enable or disable QoS support for the device.
Public Member Functions inherited from ns3::RegularWifiMac
RegularWifiMac ()
virtual ~RegularWifiMac ()
virtual void Enqueue (Ptr< Packet > packet, Mac48Address to, Mac48Address from)
Time GetAckTimeout (void) const
Mac48Address GetAddress (void) const
Time GetBasicBlockAckTimeout (void) const
Mac48Address GetBssid (void) const
Time GetCompressedBlockAckTimeout (void) const
Time GetEifsNoDifs (void) const
ExtendedCapabilities GetExtendedCapabilities (void) const
Return the extended capabilities of the device.
HeCapabilities GetHeCapabilities (void) const
Return the HE capabilities of the device.
HtCapabilities GetHtCapabilities (void) const
Return the HT capabilities of the device.
Time GetPifs (void) const
Time GetRifs (void) const
bool GetRifsSupported (void) const
bool GetShortSlotTimeSupported (void) const
Time GetSifs (void) const
Time GetSlot (void) const
Ssid GetSsid (void) const
VhtCapabilities GetVhtCapabilities (void) const
Return the VHT capabilities of the device.
Ptr< WifiPhy > GetWifiPhy (void) const
Ptr< WifiRemoteStationManager > GetWifiRemoteStationManager (void) const
void ResetWifiPhy (void)
Remove currently attached WifiPhy device from this MAC.
void SetAckTimeout (Time ackTimeout)
void SetAddress (Mac48Address address)
void SetBasicBlockAckTimeout (Time blockAckTimeout)
void SetBssid (Mac48Address bssid)
void SetCompressedBlockAckTimeout (Time blockAckTimeout)
void SetCtsToSelfSupported (bool enable)
Enable or disable CTS-to-self feature.
void SetEifsNoDifs (Time eifsNoDifs)
void SetForwardUpCallback (ForwardUpCallback upCallback)
void SetLinkDownCallback (Callback< void > linkDown)
void SetLinkUpCallback (Callback< void > linkUp)
void SetPifs (Time pifs)
void SetPromisc (void)
Sets the interface in promiscuous mode.
void SetRifs (Time rifs)
void SetRifsSupported (bool enable)
Enable or disable RIFS feature.
void SetShortSlotTimeSupported (bool enable)
Enable or disable short slot time feature.
void SetSifs (Time sifs)
void SetSlot (Time slotTime)
void SetSsid (Ssid ssid)
virtual void SetWifiPhy (const Ptr< WifiPhy > phy)
virtual void SetWifiRemoteStationManager (const Ptr< WifiRemoteStationManager > stationManager)
virtual bool SupportsSendFrom (void) const
Public Member Functions inherited from ns3::WifiMac
void ConfigureStandard (WifiPhyStandard standard)
Ptr< NetDevice > GetDevice (void) const
Return the device this PHY is associated with.
Ptr< HeConfiguration > GetHeConfiguration (void) const
Ptr< HtConfiguration > GetHtConfiguration (void) const
Ptr< VhtConfiguration > GetVhtConfiguration (void) const
void NotifyPromiscRx (Ptr< const Packet > packet)
void NotifyRx (Ptr< const Packet > packet)
void NotifyRxDrop (Ptr< const Packet > packet)
void NotifyTx (Ptr< const Packet > packet)
void NotifyTxDrop (Ptr< const Packet > packet)
void SetDevice (const Ptr< NetDevice > device)
Sets the device this PHY is associated with.
virtual void SetForwardUpCallback (Callback< void, Ptr< const Packet >, Mac48Address, Mac48Address > upCallback)=0
void SetMaxPropagationDelay (Time delay)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::RegularWifiMac
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::WifiMac
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
bool m_pcfSupported
This Boolean is set true iff this WifiMac support PCF.
Additional Inherited Members
Public Types inherited from ns3::RegularWifiMac
typedef Callback< void, Ptr< const Packet >, Mac48Address, Mac48Address > ForwardUpCallback
This type defines the callback of a higher layer that a WifiMac(-derived) object invokes to pass a packet up the stack.
Protected Types inherited from ns3::RegularWifiMac
typedef std::map< AcIndex, Ptr< QosTxop > > EdcaQueues
This type defines a mapping between an Access Category index, and a pointer to the corresponding channel access function.
Protected Member Functions inherited from ns3::RegularWifiMac
void ConfigureContentionWindow (uint32_t cwMin, uint32_t cwMax)
virtual void DeaggregateAmsduAndForward (Ptr< WifiMacQueueItem > mpdu)
This method can be called to de-aggregate an A-MSDU and forward the constituent packets up the stack.
virtual void DoDispose ()
Destructor implementation.
virtual void DoInitialize ()
Initialize() implementation.
void FinishConfigureStandard (WifiPhyStandard standard)
void ForwardUp (Ptr< const Packet > packet, Mac48Address from, Mac48Address to)
Forward the packet up to the device.
Ptr< QosTxop > GetBEQueue (void) const
Accessor for the AC_BE channel access function.
Ptr< QosTxop > GetBKQueue (void) const
Accessor for the AC_BK channel access function.
bool GetDsssSupported () const
Return whether the device supports DSSS.
bool GetErpSupported () const
Return whether the device supports ERP.
bool GetHeSupported () const
Return whether the device supports HE.
bool GetHtSupported () const
Return whether the device supports HT.
bool GetQosSupported () const
Return whether the device supports QoS.
Ptr< Txop > GetTxop (void) const
Accessor for the DCF object.
bool GetVhtSupported () const
Return whether the device supports VHT.
Ptr< QosTxop > GetVIQueue (void) const
Accessor for the AC_VI channel access function.
Ptr< QosTxop > GetVOQueue (void) const
Accessor for the AC_VO channel access function.
virtual void Receive (Ptr< WifiMacQueueItem > mpdu)
This method acts as the MacRxMiddle receive callback and is invoked to notify us that a frame has been received.
void SendAddBaResponse (const MgtAddBaRequestHeader *reqHdr, Mac48Address originator)
This method can be called to accept a received ADDBA Request.
void SetDsssSupported (bool enable)
Enable or disable DSSS support for the device.
void SetErpSupported (bool enable)
Enable or disable ERP support for the device.
void SetHeSupported (bool enable)
Enable or disable HE support for the device.
void SetHtSupported (bool enable)
Enable or disable HT support for the device.
void SetTypeOfStation (TypeOfStation type)
This method is invoked by a subclass to specify what type of station it is implementing.
void SetVhtSupported (bool enable)
Enable or disable VHT support for the device.
virtual void TxFailed (const WifiMacHeader &hdr)
The packet we sent was successfully received by the receiver (i.e.
virtual void TxOk (const WifiMacHeader &hdr)
The packet we sent was successfully received by the receiver (i.e.
Protected Member Functions inherited from ns3::WifiMac
void ConfigureDcf (Ptr< Txop > dcf, uint32_t cwmin, uint32_t cwmax, bool isDsss, AcIndex ac)
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::RegularWifiMac
Ptr< ChannelAccessManager > m_channelAccessManager
channel access manager
EdcaQueues m_edca
This is a map from Access Category index to the corresponding channel access function.
ForwardUpCallback m_forwardUp
Callback to forward packet up the stack.
Callback< void > m_linkDown
Callback when a link is down.
Callback< void > m_linkUp
Callback when a link is up.
Ptr< MacLow > m_low
MacLow (RTS, CTS, Data, Ack etc.)
Ptr< WifiPhy > m_phy
Wifi PHY.
Ptr< MacRxMiddle > m_rxMiddle
RX middle (defragmentation etc.)
Ssid m_ssid
Service Set ID (SSID)
Ptr< WifiRemoteStationManager > m_stationManager
Remote station manager (rate control, RTS/CTS/fragmentation thresholds etc.)
Ptr< MacTxMiddle > m_txMiddle
TX middle (aggregation etc.)
Ptr< Txop > m_txop
This holds a pointer to the TXOP instance for this WifiMac - used for transmission of frames to non-QoS peers.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The Wifi MAC high model for a STA or AP in a BSS.
Definition at line 33 of file infrastructure-wifi-mac.h.
Constructor & Destructor Documentation
InfrastructureWifiMac()
ns3::InfrastructureWifiMac::InfrastructureWifiMac ()
Definition at line 47 of file infrastructure-wifi-mac.cc.
References NS_LOG_FUNCTION.
~InfrastructureWifiMac()
ns3::InfrastructureWifiMac::~InfrastructureWifiMac () virtual
Definition at line 53 of file infrastructure-wifi-mac.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Enqueue()
virtual void ns3::InfrastructureWifiMac::Enqueue (Ptr< Packet > packet, Mac48Address to) pure virtual
Parameters
packet the packet to send.
to the address to which the packet should be sent.
The packet should be enqueued in a TX queue, and should be dequeued as soon as the channel access function determines that access is granted to this MAC.
Implements ns3::RegularWifiMac.
Implemented in ns3::StaWifiMac, and ns3::ApWifiMac.
GetPcfSupported()
bool ns3::InfrastructureWifiMac::GetPcfSupported () const
Return whether the device supports PCF.
Returns
true if PCF is supported, false otherwise
Definition at line 78 of file infrastructure-wifi-mac.cc.
References m_pcfSupported.
Referenced by ns3::ApWifiMac::GetCapabilities(), ns3::StaWifiMac::GetCapabilities(), ns3::ApWifiMac::GetCfParameterSet(), GetTypeId(), ns3::ApWifiMac::Receive(), ns3::StaWifiMac::Receive(), ns3::ApWifiMac::SendCfEnd(), ns3::ApWifiMac::SendCfPoll(), ns3::StaWifiMac::SendCfPollResponse(), ns3::ApWifiMac::SendNextCfFrame(), ns3::ApWifiMac::SendOneBeacon(), SetQosSupported(), ns3::ApWifiMac::SetWifiRemoteStationManager(), ns3::StaWifiMac::SetWifiRemoteStationManager(), and ns3::ApWifiMac::TxOk().
GetTypeId()
TypeId ns3::InfrastructureWifiMac::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 32 of file infrastructure-wifi-mac.cc.
References GetPcfSupported(), ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::TypeId::SetParent(), and SetPcfSupported().
SetPcfSupported()
void ns3::InfrastructureWifiMac::SetPcfSupported (bool enable)
Enable or disable PCF support for the device.
Parameters
enable whether PCF is supported
Definition at line 66 of file infrastructure-wifi-mac.cc.
References ns3::RegularWifiMac::GetQosSupported(), m_pcfSupported, ns3::RegularWifiMac::m_stationManager, NS_ASSERT_MSG(), NS_LOG_FUNCTION, and ns3::WifiRemoteStationManager::SetPcfSupported().
Referenced by GetTypeId().
SetQosSupported()
void ns3::InfrastructureWifiMac::SetQosSupported (bool enable) virtual
Enable or disable QoS support for the device.
Parameters
enable whether QoS is supported
Reimplemented from ns3::RegularWifiMac.
Definition at line 59 of file infrastructure-wifi-mac.cc.
References GetPcfSupported(), NS_ASSERT_MSG(), and ns3::RegularWifiMac::SetQosSupported().
Member Data Documentation
m_pcfSupported
bool ns3::InfrastructureWifiMac::m_pcfSupported private
This Boolean is set true iff this WifiMac support PCF.
Definition at line 79 of file infrastructure-wifi-mac.h.
Referenced by GetPcfSupported(), and SetPcfSupported().
The documentation for this class was generated from the following files:
src/wifi/model/infrastructure-wifi-mac.h
src/wifi/model/infrastructure-wifi-mac.cc