ns-3: ns3::NormalRandomVariable Class Reference
ns3::NormalRandomVariable Class Reference
Core » Random Variables
The normal (Gaussian) distribution Random Number Generator (RNG) that allows stream numbers to be set deterministically.
#include "random-variable-stream.h"
Public Member Functions
NormalRandomVariable ()
Creates a normal distribution RNG with the default values for the mean, variance, and bound.
double GetBound (void) const
Returns the bound on values that can be returned by this RNG stream.
uint32_t GetInteger (uint32_t mean, uint32_t variance, uint32_t bound)
Returns a random unsigned integer from a normal distribution with the specified mean, variance, and bound.
virtual uint32_t GetInteger (void)
Returns a random unsigned integer from a normal distribution with the current mean, variance, and bound.
double GetMean (void) const
Returns the mean value for the normal distribution returned by this RNG stream.
double GetValue (double mean, double variance, double bound=NormalRandomVariable::INFINITE_VALUE)
Returns a random double from a normal distribution with the specified mean, variance, and bound.
virtual double GetValue (void)
Returns a random double from a normal distribution with the current mean, variance, and bound.
double GetVariance (void) const
Returns the variance value for the normal distribution returned by this RNG stream.
Public Member Functions inherited from ns3::RandomVariableStream
RandomVariableStream ()
Default constructor.
virtual ~RandomVariableStream ()
Destructor.
int64_t GetStream (void) const
Returns the stream number for the RngStream.
bool IsAntithetic (void) const
Check if antithetic values will be generated.
void SetAntithetic (bool isAntithetic)
Specify whether antithetic values should be generated.
void SetStream (int64_t stream)
Specifies the stream number for the RngStream.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::RandomVariableStream
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static const double INFINITE_VALUE = 1e307
Large constant to bound the range.
Private Attributes
double m_bound
The bound on values that can be returned by this RNG stream.
double m_mean
The mean value for the normal distribution returned by this RNG stream.
double m_next
The algorithm produces two values at a time.
bool m_nextValid
True if the next value is valid.
double m_variance
The variance value for the normal distribution returned by this RNG stream.
Additional Inherited Members
Protected Member Functions inherited from ns3::RandomVariableStream
RngStream * Peek (void) const
Get the pointer to the underlying RngStream.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The normal (Gaussian) distribution Random Number Generator (RNG) that allows stream numbers to be set deterministically.
This class supports the creation of objects that return random numbers from a fixed normal distribution. It also supports the generation of single random numbers from various normal distributions.
The density probability function is defined over the interval (,) as: where and
Since normal distributions can theoretically return unbounded values, it is sometimes useful to specify a fixed bound. The NormalRandomVariable is bounded symmetrically about the mean by this bound, i.e. its values are confined to the interval [ , ].
Here is an example of how to use this class:
double mean = 5.0;
double variance = 2.0;
Ptr<NormalRandomVariable> x = CreateObject<NormalRandomVariable> ();
x->SetAttribute ("Mean", DoubleValue (mean));
x->SetAttribute ("Variance", DoubleValue (variance));
// The expected value for the mean of the values returned by a
// normally distributed random variable is equal to mean.
double value = x->GetValue ();
Definition at line 1050 of file random-variable-stream.h.
Constructor & Destructor Documentation
NormalRandomVariable()
ns3::NormalRandomVariable::NormalRandomVariable ()
Creates a normal distribution RNG with the default values for the mean, variance, and bound.
Definition at line 687 of file random-variable-stream.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
GetBound()
double ns3::NormalRandomVariable::GetBound (void) const
Returns the bound on values that can be returned by this RNG stream.
Returns
The bound on values that can be returned by this RNG stream.
Definition at line 709 of file random-variable-stream.cc.
References m_bound, and NS_LOG_FUNCTION.
GetInteger() [1/2]
uint32_t ns3::NormalRandomVariable::GetInteger (uint32_t mean, uint32_t variance, uint32_t bound)
Returns a random unsigned integer from a normal distribution with the specified mean, variance, and bound.
Parameters
[in] mean Mean value for the normal distribution.
[in] variance Variance value for the normal distribution.
[in] bound Bound on values returned.
Returns
A random unsigned integer value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If and are uniform variables over [0,1], then the values that would be returned normally, and , are calculated as follows:
For the antithetic case,) and) are the distances that and would be from . The antithetic values returned, and , are calculated as follows:
which now involves the distances and are from 1.
Definition at line 762 of file random-variable-stream.cc.
References GetValue(), and NS_LOG_FUNCTION.
GetInteger() [2/2]
uint32_t ns3::NormalRandomVariable::GetInteger (void) virtual
Returns a random unsigned integer from a normal distribution with the current mean, variance, and bound.
Returns
A random unsigned integer value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If and are uniform variables over [0,1], then the values that would be returned normally, and , are calculated as follows:
For the antithetic case,) and) are the distances that and would be from . The antithetic values returned, and , are calculated as follows:
which now involves the distances and are from 1.
Implements ns3::RandomVariableStream.
Definition at line 775 of file random-variable-stream.cc.
References GetValue(), m_bound, m_mean, m_variance, and NS_LOG_FUNCTION.
GetMean()
double ns3::NormalRandomVariable::GetMean (void) const
Returns the mean value for the normal distribution returned by this RNG stream.
Returns
The mean value for the normal distribution returned by this RNG stream.
Definition at line 697 of file random-variable-stream.cc.
References m_mean, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::NormalRandomVariable::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 666 of file random-variable-stream.cc.
References INFINITE_VALUE, m_bound, m_mean, m_variance, ns3::MakeDoubleAccessor(), and ns3::TypeId::SetParent().
GetValue() [1/2]
double ns3::NormalRandomVariable::GetValue (double mean, double variance, double bound = NormalRandomVariable::INFINITE_VALUE)
Returns a random double from a normal distribution with the specified mean, variance, and bound.
Parameters
[in] mean Mean value for the normal distribution.
[in] variance Variance value for the normal distribution.
[in] bound Bound on values returned.
Returns
A floating point random value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If and are uniform variables over [0,1], then the values that would be returned normally, and , are calculated as follows:
For the antithetic case,) and) are the distances that and would be from . The antithetic values returned, and , are calculated as follows:
which now involves the distances and are from 1.
Definition at line 716 of file random-variable-stream.cc.
References ns3::RandomVariableStream::IsAntithetic(), m_next, m_nextValid, NS_LOG_FUNCTION, ns3::RandomVariableStream::Peek(), and ns3::RngStream::RandU01().
GetValue() [2/2]
double ns3::NormalRandomVariable::GetValue (void) virtual
Returns a random double from a normal distribution with the current mean, variance, and bound.
Returns
A floating point random value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If and are uniform variables over [0,1], then the values that would be returned normally, and , are calculated as follows:
For the antithetic case,) and) are the distances that and would be from . The antithetic values returned, and , are calculated as follows:
which now involves the distances and are from 1.
Note that we have to re-implement this method here because the method is overloaded above for the three-argument variant and the c++ name resolution rules don't work well with overloads split between parent and child classes.
Implements ns3::RandomVariableStream.
Definition at line 769 of file random-variable-stream.cc.
References m_bound, m_mean, m_variance, and NS_LOG_FUNCTION.
Referenced by GetInteger().
GetVariance()
double ns3::NormalRandomVariable::GetVariance (void) const
Returns the variance value for the normal distribution returned by this RNG stream.
Returns
The variance value for the normal distribution returned by this RNG stream.
Definition at line 703 of file random-variable-stream.cc.
References m_variance, and NS_LOG_FUNCTION.
Member Data Documentation
INFINITE_VALUE
const double ns3::NormalRandomVariable::INFINITE_VALUE = 1e307 static
Large constant to bound the range.
Definition at line 1054 of file random-variable-stream.h.
Referenced by GetTypeId(), and ns3::GammaRandomVariable::GetValue().
m_bound
double ns3::NormalRandomVariable::m_bound private
The bound on values that can be returned by this RNG stream.
Definition at line 1245 of file random-variable-stream.h.
Referenced by GetBound(), GetInteger(), GetTypeId(), and GetValue().
m_mean
double ns3::NormalRandomVariable::m_mean private
The mean value for the normal distribution returned by this RNG stream.
Definition at line 1239 of file random-variable-stream.h.
Referenced by GetInteger(), GetMean(), GetTypeId(), and GetValue().
m_next
double ns3::NormalRandomVariable::m_next private
The algorithm produces two values at a time.
Definition at line 1251 of file random-variable-stream.h.
Referenced by GetValue().
m_nextValid
bool ns3::NormalRandomVariable::m_nextValid private
True if the next value is valid.
Definition at line 1248 of file random-variable-stream.h.
Referenced by GetValue().
m_variance
double ns3::NormalRandomVariable::m_variance private
The variance value for the normal distribution returned by this RNG stream.
Definition at line 1242 of file random-variable-stream.h.
Referenced by GetInteger(), GetTypeId(), GetValue(), and GetVariance().
The documentation for this class was generated from the following files:
src/core/model/random-variable-stream.h
src/core/model/random-variable-stream.cc