ns-3: ns3::MgtAddBaRequestHeader Class Reference
ns3::MgtAddBaRequestHeader Class Reference
Wifi Models
#include "mgt-headers.h"
Public Member Functions
MgtAddBaRequestHeader ()
uint32_t Deserialize (Buffer::Iterator start)
uint16_t GetBufferSize (void) const
Return the buffer size.
TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint32_t GetSerializedSize (void) const
uint16_t GetStartingSequence (void) const
Return the starting sequence number.
uint8_t GetTid (void) const
Return the Traffic ID (TID).
uint16_t GetTimeout (void) const
Return the timeout.
bool IsAmsduSupported (void) const
Return whether A-MSDU capability is supported.
bool IsImmediateBlockAck (void) const
Return whether the Block Ack policy is immediate Block Ack.
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetAmsduSupport (bool supported)
Enable or disable A-MSDU support.
void SetBufferSize (uint16_t size)
Set buffer size.
void SetDelayedBlockAck ()
Enable delayed BlockAck.
void SetImmediateBlockAck ()
Enable immediate BlockAck.
void SetStartingSequence (uint16_t seq)
Set the starting sequence number.
void SetTid (uint8_t tid)
Set Traffic ID (TID).
void SetTimeout (uint16_t timeout)
Set timeout.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
uint16_t GetParameterSet (void) const
Return the raw parameter set.
uint16_t GetStartingSequenceControl (void) const
Return the raw sequence control.
void SetParameterSet (uint16_t params)
Set the parameter set from the given raw value.
void SetStartingSequenceControl (uint16_t seqControl)
Set sequence control with the given raw value.
Private Attributes
uint8_t m_amsduSupport
Flag if A-MSDU is supported.
uint16_t m_bufferSize
Buffer size.
uint8_t m_dialogToken
Not used for now.
uint8_t m_policy
Block Ack policy.
uint16_t m_startingSeq
Starting sequence number.
uint8_t m_tid
Traffic ID.
uint16_t m_timeoutValue
Timeout.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implement the header for management frames of type Add Block Ack request.
Definition at line 1003 of file mgt-headers.h.
Constructor & Destructor Documentation
MgtAddBaRequestHeader()
ns3::MgtAddBaRequestHeader::MgtAddBaRequestHeader ()
Definition at line 1450 of file mgt-headers.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::MgtAddBaRequestHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 1501 of file mgt-headers.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_dialogToken, m_timeoutValue, ns3::Buffer::Iterator::ReadLsbtohU16(), ns3::Buffer::Iterator::ReadU8(), SetParameterSet(), SetStartingSequenceControl(), and visualizer.core::start().
GetBufferSize()
uint16_t ns3::MgtAddBaRequestHeader::GetBufferSize (void) const
Return the buffer size.
Returns
the buffer size.
Definition at line 1579 of file mgt-headers.cc.
References m_bufferSize.
Referenced by ns3::BlockAckManager::CreateAgreement().
GetInstanceTypeId()
TypeId ns3::MgtAddBaRequestHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 1469 of file mgt-headers.cc.
References GetTypeId().
GetParameterSet()
uint16_t ns3::MgtAddBaRequestHeader::GetParameterSet (void) const private
Return the raw parameter set.
Returns
the raw parameter set
Definition at line 1603 of file mgt-headers.cc.
References m_amsduSupport, m_bufferSize, m_policy, and m_tid.
Referenced by Serialize().
GetSerializedSize()
uint32_t ns3::MgtAddBaRequestHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 1480 of file mgt-headers.cc.
GetStartingSequence()
uint16_t ns3::MgtAddBaRequestHeader::GetStartingSequence (void) const
Return the starting sequence number.
Returns
the starting sequence number
Definition at line 1591 of file mgt-headers.cc.
References m_startingSeq.
Referenced by ns3::BlockAckManager::CreateAgreement(), and ns3::RegularWifiMac::SendAddBaResponse().
GetStartingSequenceControl()
uint16_t ns3::MgtAddBaRequestHeader::GetStartingSequenceControl (void) const private
Return the raw sequence control.
Returns
the raw sequence control
Definition at line 1597 of file mgt-headers.cc.
References m_startingSeq.
Referenced by Serialize().
GetTid()
uint8_t ns3::MgtAddBaRequestHeader::GetTid (void) const
Return the Traffic ID (TID).
Returns
TID
Definition at line 1561 of file mgt-headers.cc.
References m_tid.
Referenced by ns3::BlockAckManager::CreateAgreement(), ns3::GetTid(), ns3::QosTxop::GotAck(), and ns3::RegularWifiMac::SendAddBaResponse().
GetTimeout()
uint16_t ns3::MgtAddBaRequestHeader::GetTimeout (void) const
Return the timeout.
Returns
timeout
Definition at line 1573 of file mgt-headers.cc.
References m_timeoutValue.
Referenced by ns3::BlockAckManager::CreateAgreement(), and ns3::RegularWifiMac::SendAddBaResponse().
GetTypeId()
TypeId ns3::MgtAddBaRequestHeader::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 1458 of file mgt-headers.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
IsAmsduSupported()
bool ns3::MgtAddBaRequestHeader::IsAmsduSupported (void) const
Return whether A-MSDU capability is supported.
Returns
true is A-MSDU is supported, false otherwise
Definition at line 1585 of file mgt-headers.cc.
References m_amsduSupport.
Referenced by ns3::BlockAckManager::CreateAgreement(), and ns3::RegularWifiMac::SendAddBaResponse().
IsImmediateBlockAck()
bool ns3::MgtAddBaRequestHeader::IsImmediateBlockAck (void) const
Return whether the Block Ack policy is immediate Block Ack.
Returns
true if immediate Block Ack is being used, false otherwise
Definition at line 1567 of file mgt-headers.cc.
References m_policy.
Referenced by ns3::BlockAckManager::CreateAgreement(), and ns3::RegularWifiMac::SendAddBaResponse().
Print()
void ns3::MgtAddBaRequestHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 1475 of file mgt-headers.cc.
Serialize()
void ns3::MgtAddBaRequestHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 1491 of file mgt-headers.cc.
References GetParameterSet(), GetStartingSequenceControl(), m_dialogToken, m_timeoutValue, visualizer.core::start(), ns3::Buffer::Iterator::WriteHtolsbU16(), and ns3::Buffer::Iterator::WriteU8().
SetAmsduSupport()
void ns3::MgtAddBaRequestHeader::SetAmsduSupport (bool supported)
Enable or disable A-MSDU support.
Parameters
supported enable or disable A-MSDU support
Definition at line 1555 of file mgt-headers.cc.
References m_amsduSupport.
Referenced by ns3::QosTxop::SendAddBaRequest().
SetBufferSize()
void ns3::MgtAddBaRequestHeader::SetBufferSize (uint16_t size)
Set buffer size.
Parameters
size buffer size
Definition at line 1537 of file mgt-headers.cc.
References m_bufferSize.
Referenced by AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), HeAggregationTest::DoRunSubTest(), and ns3::QosTxop::SendAddBaRequest().
SetDelayedBlockAck()
void ns3::MgtAddBaRequestHeader::SetDelayedBlockAck ()
Enable delayed BlockAck.
Definition at line 1512 of file mgt-headers.cc.
References m_policy.
Referenced by ns3::QosTxop::SendAddBaRequest().
SetImmediateBlockAck()
void ns3::MgtAddBaRequestHeader::SetImmediateBlockAck ()
Enable immediate BlockAck.
Definition at line 1518 of file mgt-headers.cc.
References m_policy.
Referenced by AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), HeAggregationTest::DoRunSubTest(), and ns3::QosTxop::SendAddBaRequest().
SetParameterSet()
void ns3::MgtAddBaRequestHeader::SetParameterSet (uint16_t params) private
Set the parameter set from the given raw value.
Parameters
params raw parameter set value
Definition at line 1614 of file mgt-headers.cc.
References m_amsduSupport, m_bufferSize, m_policy, m_tid, and aloha::params.
Referenced by Deserialize().
SetStartingSequence()
void ns3::MgtAddBaRequestHeader::SetStartingSequence (uint16_t seq)
Set the starting sequence number.
Parameters
seq the starting sequence number
Definition at line 1543 of file mgt-headers.cc.
References m_startingSeq.
Referenced by AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), HeAggregationTest::DoRunSubTest(), and ns3::QosTxop::SendAddBaRequest().
SetStartingSequenceControl()
void ns3::MgtAddBaRequestHeader::SetStartingSequenceControl (uint16_t seqControl) private
Set sequence control with the given raw value.
Parameters
seqControl the raw sequence control
Definition at line 1549 of file mgt-headers.cc.
References m_startingSeq.
Referenced by Deserialize().
SetTid()
void ns3::MgtAddBaRequestHeader::SetTid (uint8_t tid)
Set Traffic ID (TID).
Parameters
tid traffic ID
Definition at line 1524 of file mgt-headers.cc.
References m_tid, and NS_ASSERT.
Referenced by AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), HeAggregationTest::DoRunSubTest(), and ns3::QosTxop::SendAddBaRequest().
SetTimeout()
void ns3::MgtAddBaRequestHeader::SetTimeout (uint16_t timeout)
Set timeout.
Parameters
timeout timeout
Definition at line 1531 of file mgt-headers.cc.
References m_timeoutValue, and timeout.
Referenced by AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), HeAggregationTest::DoRunSubTest(), and ns3::QosTxop::SendAddBaRequest().
Member Data Documentation
m_amsduSupport
uint8_t ns3::MgtAddBaRequestHeader::m_amsduSupport private
Flag if A-MSDU is supported.
Definition at line 1122 of file mgt-headers.h.
Referenced by GetParameterSet(), IsAmsduSupported(), SetAmsduSupport(), and SetParameterSet().
m_bufferSize
uint16_t ns3::MgtAddBaRequestHeader::m_bufferSize private
Buffer size.
Definition at line 1125 of file mgt-headers.h.
Referenced by GetBufferSize(), GetParameterSet(), SetBufferSize(), and SetParameterSet().
m_dialogToken
uint8_t ns3::MgtAddBaRequestHeader::m_dialogToken private
Not used for now.
Definition at line 1121 of file mgt-headers.h.
Referenced by Deserialize(), and Serialize().
m_policy
uint8_t ns3::MgtAddBaRequestHeader::m_policy private
Block Ack policy.
Definition at line 1123 of file mgt-headers.h.
Referenced by GetParameterSet(), IsImmediateBlockAck(), SetDelayedBlockAck(), SetImmediateBlockAck(), and SetParameterSet().
m_startingSeq
uint16_t ns3::MgtAddBaRequestHeader::m_startingSeq private
Starting sequence number.
Definition at line 1127 of file mgt-headers.h.
Referenced by GetStartingSequence(), GetStartingSequenceControl(), SetStartingSequence(), and SetStartingSequenceControl().
m_tid
uint8_t ns3::MgtAddBaRequestHeader::m_tid private
Traffic ID.
Definition at line 1124 of file mgt-headers.h.
Referenced by GetParameterSet(), GetTid(), SetParameterSet(), and SetTid().
m_timeoutValue
uint16_t ns3::MgtAddBaRequestHeader::m_timeoutValue private
Timeout.
Definition at line 1126 of file mgt-headers.h.
Referenced by Deserialize(), GetTimeout(), Serialize(), and SetTimeout().
The documentation for this class was generated from the following files:
src/wifi/model/mgt-headers.h
src/wifi/model/mgt-headers.cc