ns-3: ns3::SimpleUeCcmMacSapUser Class Reference
ns3::SimpleUeCcmMacSapUser Class Reference
SimpleUeCcmMacSapUser class.
Public Member Functions
SimpleUeCcmMacSapUser (SimpleUeComponentCarrierManager *mac)
Constructor.
virtual void NotifyHarqDeliveryFailure ()
Called by the MAC to notify the RLC that an HARQ process related to this RLC instance has failed.
virtual void NotifyTxOpportunity (LteMacSapUser::TxOpportunityParameters txOpParams)
Called by the MAC to notify the RLC that the scheduler granted a transmission opportunity to this RLC instance.
virtual void ReceivePdu (LteMacSapUser::ReceivePduParameters rxPduParams)
Called by the MAC to notify the RLC of the reception of a new PDU.
Public Member Functions inherited from ns3::LteMacSapUser
virtual ~LteMacSapUser ()
Private Attributes
SimpleUeComponentCarrierManager * m_mac
the component carrier manager
Detailed Description
SimpleUeCcmMacSapUser class.
Definition at line 82 of file simple-ue-component-carrier-manager.cc.
Constructor & Destructor Documentation
SimpleUeCcmMacSapUser()
ns3::SimpleUeCcmMacSapUser::SimpleUeCcmMacSapUser (SimpleUeComponentCarrierManager * mac)
Constructor.
Parameters
mac the component carrier manager
Definition at line 102 of file simple-ue-component-carrier-manager.cc.
Member Function Documentation
NotifyHarqDeliveryFailure()
void ns3::SimpleUeCcmMacSapUser::NotifyHarqDeliveryFailure () virtual
Called by the MAC to notify the RLC that an HARQ process related to this RLC instance has failed.
Todo:
eventual parameters to be defined
Implements ns3::LteMacSapUser.
Definition at line 122 of file simple-ue-component-carrier-manager.cc.
References ns3::SimpleUeComponentCarrierManager::DoNotifyHarqDeliveryFailure(), and m_mac.
NotifyTxOpportunity()
void ns3::SimpleUeCcmMacSapUser::NotifyTxOpportunity (LteMacSapUser::TxOpportunityParameters params) virtual
Called by the MAC to notify the RLC that the scheduler granted a transmission opportunity to this RLC instance.
Parameters
params the TxOpportunityParameters
Implements ns3::LteMacSapUser.
Definition at line 108 of file simple-ue-component-carrier-manager.cc.
References ns3::LteMacSapUser::TxOpportunityParameters::componentCarrierId, ns3::SimpleUeComponentCarrierManager::DoNotifyTxOpportunity(), m_mac, and NS_LOG_INFO.
ReceivePdu()
void ns3::SimpleUeCcmMacSapUser::ReceivePdu (LteMacSapUser::ReceivePduParameters params) virtual
Called by the MAC to notify the RLC of the reception of a new PDU.
Parameters
params the ReceivePduParameters
Implements ns3::LteMacSapUser.
Definition at line 116 of file simple-ue-component-carrier-manager.cc.
References ns3::SimpleUeComponentCarrierManager::DoReceivePdu(), and m_mac.
Member Data Documentation
m_mac
SimpleUeComponentCarrierManager* ns3::SimpleUeCcmMacSapUser::m_mac private
the component carrier manager
Definition at line 99 of file simple-ue-component-carrier-manager.cc.
Referenced by NotifyHarqDeliveryFailure(), NotifyTxOpportunity(), and ReceivePdu().
The documentation for this class was generated from the following file:
src/lte/model/simple-ue-component-carrier-manager.cc