ns-3: ns3::lorawan::ConfirmedMessagesComponent Class Reference
ns3::lorawan::ConfirmedMessagesComponent Class Reference
#include "network-controller-components.h"
Public Member Functions
ConfirmedMessagesComponent ()
virtual ~ConfirmedMessagesComponent ()
void BeforeSendingReply (Ptr< EndDeviceStatus > status, Ptr< NetworkStatus > networkStatus)
void OnFailedReply (Ptr< EndDeviceStatus > status, Ptr< NetworkStatus > networkStatus)
Method that is called when a packet cannot be sent in the downlink.
void OnReceivedPacket (Ptr< const Packet > packet, Ptr< EndDeviceStatus > status, Ptr< NetworkStatus > networkStatus)
This method checks whether the received packet requires an acknowledgment and sets up the appropriate reply in case it does.
Public Member Functions inherited from ns3::lorawan::NetworkControllerComponent
NetworkControllerComponent ()
virtual ~NetworkControllerComponent ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::lorawan::NetworkControllerComponent
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 83 of file network-controller-components.h.
Constructor & Destructor Documentation
ConfirmedMessagesComponent()
ns3::lorawan::ConfirmedMessagesComponent::ConfirmedMessagesComponent ()
Definition at line 61 of file network-controller-components.cc.
~ConfirmedMessagesComponent()
ns3::lorawan::ConfirmedMessagesComponent::~ConfirmedMessagesComponent () virtual
Definition at line 64 of file network-controller-components.cc.
Member Function Documentation
BeforeSendingReply()
void ns3::lorawan::ConfirmedMessagesComponent::BeforeSendingReply (Ptr< EndDeviceStatus > status, Ptr< NetworkStatus > networkStatus) virtual
Implements ns3::lorawan::NetworkControllerComponent.
Definition at line 108 of file network-controller-components.cc.
References NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::lorawan::ConfirmedMessagesComponent::GetTypeId (void) static
Definition at line 52 of file network-controller-components.cc.
References ns3::TypeId::SetParent().
Referenced by OnReceivedPacket().
OnFailedReply()
void ns3::lorawan::ConfirmedMessagesComponent::OnFailedReply (Ptr< EndDeviceStatus > status, Ptr< NetworkStatus > networkStatus) virtual
Method that is called when a packet cannot be sent in the downlink.
Parameters
status The EndDeviceStatus of the device to which it was impossible to send a reply.
networkStatus A pointer to the NetworkStatus object
Implements ns3::lorawan::NetworkControllerComponent.
Definition at line 116 of file network-controller-components.cc.
References NS_LOG_FUNCTION.
OnReceivedPacket()
void ns3::lorawan::ConfirmedMessagesComponent::OnReceivedPacket (Ptr< const Packet > packet, Ptr< EndDeviceStatus > status, Ptr< NetworkStatus > networkStatus) virtual
This method checks whether the received packet requires an acknowledgment and sets up the appropriate reply in case it does.
Parameters
packet The newly received packet
networkStatus A pointer to the NetworkStatus object
Implements ns3::lorawan::NetworkControllerComponent.
Definition at line 69 of file network-controller-components.cc.
References ns3::lorawan::LorawanMacHeader::CONFIRMED_DATA_UP, ns3::lorawan::LoraFrameHeader::GetAddress(), ns3::lorawan::LorawanMacHeader::GetMType(), GetTypeId(), NS_LOG_FUNCTION, NS_LOG_INFO, ns3::Packet::RemoveHeader(), ns3::lorawan::LoraFrameHeader::SetAsUplink(), and ns3::lorawan::LorawanMacHeader::UNCONFIRMED_DATA_DOWN.
The documentation for this class was generated from the following files:
src/lorawan/model/network-controller-components.h
src/lorawan/model/network-controller-components.cc