ns-3: ns3::SystemWallClockMsPrivate Class Reference
ns3::SystemWallClockMsPrivate Class Reference
Core » System Services
System-dependent implementation for SystemWallClockMs.
Public Member Functions
int64_t End (void)
Stop measuring the time since Start() was called.
int64_t End (void)
Stop measuring the time since Start() was called.
int64_t GetElapsedReal (void) const
int64_t GetElapsedReal (void) const
int64_t GetElapsedSystem (void) const
int64_t GetElapsedSystem (void) const
int64_t GetElapsedUser (void) const
int64_t GetElapsedUser (void) const
void Start (void)
Start a measure.
void Start (void)
Start a measure.
Private Attributes
int64_t m_elapsedReal
Elapsed real time, in ms.
int64_t m_elapsedSystem
Elapsed system time, in ms.
int64_t m_elapsedUser
Elapsed user time, in ms.
clock_t m_startTime
Native real time.
struct tms m_startTimes
The native time structure.
Detailed Description
System-dependent implementation for SystemWallClockMs.
Definition at line 41 of file unix-system-wall-clock-ms.cc.
Member Function Documentation
End() [1/2]
int64_t ns3::SystemWallClockMsPrivate::End (void)
Stop measuring the time since Start() was called.
Returns
the measured elapsed wall clock time (in milliseconds) since Start() was invoked.
It is possible to start a new measurement with Start() after this method returns.
Returns int64_t to avoid dependency on clock_t in ns-3 code.
Definition at line 71 of file unix-system-wall-clock-ms.cc.
References m_elapsedReal, m_elapsedSystem, m_elapsedUser, m_startTime, m_startTimes, NS_ABORT_MSG_IF, and NS_LOG_FUNCTION.
Referenced by ns3::SystemWallClockMs::End().
End() [2/2]
int64_t ns3::SystemWallClockMsPrivate::End (void)
Stop measuring the time since Start() was called.
Returns
the measured elapsed wall clock time (in milliseconds) since Start() was invoked.
It is possible to start a new measurement with Start() after this method returns.
Returns int64_t to avoid dependency on clock_t in ns-3 code.
GetElapsedReal() [1/2]
int64_t ns3::SystemWallClockMsPrivate::GetElapsedReal (void) const
Returns
the measured elapsed wall clock time (in milliseconds) since Start() was invoked.
Returns int64_t to avoid dependency on clock_t in ns-3 code.
Definition at line 126 of file unix-system-wall-clock-ms.cc.
References m_elapsedReal, and NS_LOG_FUNCTION.
Referenced by ns3::SystemWallClockMs::GetElapsedReal().
GetElapsedReal() [2/2]
int64_t ns3::SystemWallClockMsPrivate::GetElapsedReal (void) const
Returns
the measured elapsed wall clock time (in milliseconds) since Start() was invoked.
Returns int64_t to avoid dependency on clock_t in ns-3 code.
GetElapsedSystem() [1/2]
int64_t ns3::SystemWallClockMsPrivate::GetElapsedSystem (void) const
Returns
the measured elapsed 'system' wall clock time (in milliseconds) since Start() was invoked.
Returns int64_t to avoid dependency on clock_t in ns-3 code.
Definition at line 140 of file unix-system-wall-clock-ms.cc.
References m_elapsedSystem, and NS_LOG_FUNCTION.
Referenced by ns3::SystemWallClockMs::GetElapsedSystem().
GetElapsedSystem() [2/2]
int64_t ns3::SystemWallClockMsPrivate::GetElapsedSystem (void) const
Returns
the measured elapsed 'system' wall clock time (in milliseconds) since Start() was invoked.
Returns int64_t to avoid dependency on clock_t in ns-3 code.
GetElapsedUser() [1/2]
int64_t ns3::SystemWallClockMsPrivate::GetElapsedUser (void) const
Returns
the measured elapsed 'user' wall clock time (in milliseconds) since Start() was invoked.
Returns int64_t to avoid dependency on clock_t in ns-3 code.
Definition at line 133 of file unix-system-wall-clock-ms.cc.
References m_elapsedUser, and NS_LOG_FUNCTION.
Referenced by ns3::SystemWallClockMs::GetElapsedUser().
GetElapsedUser() [2/2]
int64_t ns3::SystemWallClockMsPrivate::GetElapsedUser (void) const
Returns
the measured elapsed 'user' wall clock time (in milliseconds) since Start() was invoked.
Returns int64_t to avoid dependency on clock_t in ns-3 code.
Start() [1/2]
void ns3::SystemWallClockMsPrivate::Start (void)
Start a measure.
Definition at line 64 of file unix-system-wall-clock-ms.cc.
References m_startTime, m_startTimes, and NS_LOG_FUNCTION.
Referenced by ns3::SystemWallClockMs::Start().
Start() [2/2]
void ns3::SystemWallClockMsPrivate::Start (void)
Start a measure.
Member Data Documentation
m_elapsedReal
int64_t ns3::SystemWallClockMsPrivate::m_elapsedReal private
Elapsed real time, in ms.
Definition at line 58 of file unix-system-wall-clock-ms.cc.
Referenced by End(), and GetElapsedReal().
m_elapsedSystem
int64_t ns3::SystemWallClockMsPrivate::m_elapsedSystem private
Elapsed system time, in ms.
Definition at line 60 of file unix-system-wall-clock-ms.cc.
Referenced by End(), and GetElapsedSystem().
m_elapsedUser
int64_t ns3::SystemWallClockMsPrivate::m_elapsedUser private
Elapsed user time, in ms.
Definition at line 59 of file unix-system-wall-clock-ms.cc.
Referenced by End(), and GetElapsedUser().
m_startTime
clock_t ns3::SystemWallClockMsPrivate::m_startTime private
Native real time.
The wall clock start time.
Definition at line 57 of file unix-system-wall-clock-ms.cc.
Referenced by End(), and Start().
m_startTimes
struct tms ns3::SystemWallClockMsPrivate::m_startTimes private
The native time structure.
Definition at line 53 of file unix-system-wall-clock-ms.cc.
Referenced by End(), and Start().
The documentation for this class was generated from the following files:
src/core/model/unix-system-wall-clock-ms.cc
src/core/model/win32-system-wall-clock-ms.cc