ns-3: ns3::YansErrorRateModel Class Reference
ns3::YansErrorRateModel Class Reference
Wifi Models
Model the error rate for different modulations.
#include "yans-error-rate-model.h"
Public Member Functions
YansErrorRateModel ()
virtual double GetChunkSuccessRate (WifiMode mode, WifiTxVector txVector, double snr, uint64_t nbits) const
A pure virtual method that must be implemented in the subclass.
Public Member Functions inherited from ns3::ErrorRateModel
double CalculateSnr (WifiTxVector txVector, double ber) const
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ErrorRateModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
double Binomial (uint32_t k, double p, uint32_t n) const
Return Binomial distribution for a given k, p, and n.
double CalculatePd (double ber, unsigned int d) const
double CalculatePdEven (double ber, unsigned int d) const
double CalculatePdOdd (double ber, unsigned int d) const
uint32_t Factorial (uint32_t k) const
Return k!
double GetBpskBer (double snr, uint32_t signalSpread, uint64_t phyRate) const
Return BER of BPSK with the given parameters.
double GetFecBpskBer (double snr, uint64_t nbits, uint32_t signalSpread, uint64_t phyRate, uint32_t dFree, uint32_t adFree) const
double GetFecQamBer (double snr, uint64_t nbits, uint32_t signalSpread, uint64_t phyRate, uint32_t m, uint32_t dfree, uint32_t adFree, uint32_t adFreePlusOne) const
double GetQamBer (double snr, unsigned int m, uint32_t signalSpread, uint64_t phyRate) const
Return BER of QAM-m with the given parameters.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Model the error rate for different modulations.
A packet of interest (e.g., a packet can potentially be received by the MAC) is divided into chunks. Each chunk is related to an start/end receiving event. For each chunk, it calculates the ratio (SINR) between received power of packet of interest and summation of noise and interfering power of all the other incoming packets. Then, it will calculate the success rate of the chunk based on BER of the modulation. The success reception rate of the packet is derived from the success rate of all chunks.
The 802.11b modulations:
1 Mbps mode is based on DBPSK. BER is from equation 5.2-69 from John G. Proakis Digital Communications, 2001 edition
2 Mbps model is based on DQPSK. Equation 8 from "Tight bounds and accurate approximations for DQPSK transmission bit error rate", G. Ferrari and G.E. Corazza ELECTRONICS LETTERS, 40(20):1284-1285, September 2004
5.5 Mbps and 11 Mbps are based on equations (18) and (17) from "Properties and performance of the IEEE 802.11b complementary code-key signal sets", Michael B. Pursley and Thomas C. Royster. IEEE TRANSACTIONS ON COMMUNICATIONS, 57(2):440-449, February 2009.
More detailed description and validation can be found in http://www.nsnam.org/~pei/80211b.pdf
Definition at line 53 of file yans-error-rate-model.h.
Constructor & Destructor Documentation
YansErrorRateModel()
ns3::YansErrorRateModel::YansErrorRateModel ()
Definition at line 45 of file yans-error-rate-model.cc.
Member Function Documentation
Binomial()
double ns3::YansErrorRateModel::Binomial (uint32_t k, double p, uint32_t n) const private
Return Binomial distribution for a given k, p, and n.
Parameters
k
p
n
Returns
a Binomial distribution
Definition at line 86 of file yans-error-rate-model.cc.
References Factorial(), and sample-rng-plot::n.
Referenced by CalculatePdEven(), and CalculatePdOdd().
CalculatePd()
double ns3::YansErrorRateModel::CalculatePd (double ber, unsigned int d) const private
Parameters
ber
d
Returns
double
Definition at line 125 of file yans-error-rate-model.cc.
References CalculatePdEven(), CalculatePdOdd(), and NS_LOG_FUNCTION.
Referenced by GetFecBpskBer(), and GetFecQamBer().
CalculatePdEven()
double ns3::YansErrorRateModel::CalculatePdEven (double ber, unsigned int d) const private
Parameters
ber
d
Returns
double
Definition at line 108 of file yans-error-rate-model.cc.
References Binomial(), and NS_ASSERT.
Referenced by CalculatePd().
CalculatePdOdd()
double ns3::YansErrorRateModel::CalculatePdOdd (double ber, unsigned int d) const private
Parameters
ber
d
Returns
double
Definition at line 93 of file yans-error-rate-model.cc.
References Binomial(), and NS_ASSERT.
Referenced by CalculatePd().
Factorial()
uint32_t ns3::YansErrorRateModel::Factorial (uint32_t k) const private
Return k!
Parameters
k
Returns
k!
Definition at line 74 of file yans-error-rate-model.cc.
Referenced by Binomial().
GetBpskBer()
double ns3::YansErrorRateModel::GetBpskBer (double snr, uint32_t signalSpread, uint64_t phyRate) const private
Return BER of BPSK with the given parameters.
Parameters
snr SNR ratio (not dB)
signalSpread
phyRate
Returns
BER of BPSK at the given SNR
Definition at line 50 of file yans-error-rate-model.cc.
References NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by GetFecBpskBer().
GetChunkSuccessRate()
double ns3::YansErrorRateModel::GetChunkSuccessRate (WifiMode mode, WifiTxVector txVector, double snr, uint64_t nbits) const virtual
A pure virtual method that must be implemented in the subclass.
This method returns the probability that the given 'chunk' of the packet will be successfully received by the PHY.
A chunk can be viewed as a part of a packet with equal SNR. The probability of successfully receiving the chunk depends on the mode, the SNR, and the size of the chunk.
Note that both a WifiMode and a WifiTxVector (which contains a WifiMode) are passed into this method. The WifiTxVector may be from a signal that contains multiple modes (e.g. PHY header sent differently from PHY payload). Consequently, the mode parameter is what the method uses to calculate the chunk error rate, and the txVector is used for other information as needed.
Parameters
mode the Wi-Fi mode applicable to this chunk
txVector TXVECTOR of the overall transmission
snr the SNR of the chunk
nbits the number of bits in this chunk
Returns
probability of successfully receiving the chunk
Implements ns3::ErrorRateModel.
Definition at line 183 of file yans-error-rate-model.cc.
References ns3::WifiTxVector::GetChannelWidth(), ns3::WifiMode::GetCodeRate(), ns3::WifiMode::GetConstellationSize(), ns3::WifiMode::GetDataRate(), ns3::DsssErrorRateModel::GetDsssDbpskSuccessRate(), ns3::DsssErrorRateModel::GetDsssDqpskCck11SuccessRate(), ns3::DsssErrorRateModel::GetDsssDqpskCck5_5SuccessRate(), ns3::DsssErrorRateModel::GetDsssDqpskSuccessRate(), GetFecBpskBer(), GetFecQamBer(), ns3::WifiTxVector::GetMode(), ns3::WifiMode::GetModulationClass(), ns3::WifiMode::GetPhyRate(), NS_ASSERT, NS_LOG_FUNCTION, ns3::WIFI_CODE_RATE_1_2, ns3::WIFI_CODE_RATE_2_3, ns3::WIFI_CODE_RATE_5_6, ns3::WIFI_MOD_CLASS_DSSS, ns3::WIFI_MOD_CLASS_ERP_OFDM, ns3::WIFI_MOD_CLASS_HE, ns3::WIFI_MOD_CLASS_HR_DSSS, ns3::WIFI_MOD_CLASS_HT, ns3::WIFI_MOD_CLASS_OFDM, and ns3::WIFI_MOD_CLASS_VHT.
GetFecBpskBer()
double ns3::YansErrorRateModel::GetFecBpskBer (double snr, uint64_t nbits, uint32_t signalSpread, uint64_t phyRate, uint32_t dFree, uint32_t adFree) const private
Parameters
snr SNR ratio (not dB)
nbits
signalSpread
phyRate
dFree
adFree
Returns
double
Definition at line 141 of file yans-error-rate-model.cc.
References CalculatePd(), GetBpskBer(), min, and NS_LOG_FUNCTION.
Referenced by GetChunkSuccessRate().
GetFecQamBer()
double ns3::YansErrorRateModel::GetFecQamBer (double snr, uint64_t nbits, uint32_t signalSpread, uint64_t phyRate, uint32_t m, uint32_t dfree, uint32_t adFree, uint32_t adFreePlusOne) const private
Parameters
snr SNR ratio (not dB)
nbits
signalSpread
phyRate
m
dfree
adFree
adFreePlusOne
Returns
double
Definition at line 159 of file yans-error-rate-model.cc.
References CalculatePd(), GetQamBer(), min, and NS_LOG_FUNCTION.
Referenced by GetChunkSuccessRate().
GetQamBer()
double ns3::YansErrorRateModel::GetQamBer (double snr, unsigned int m, uint32_t signalSpread, uint64_t phyRate) const private
Return BER of QAM-m with the given parameters.
Parameters
snr SNR ratio (not dB)
m
signalSpread
phyRate
Returns
BER of BPSK at the given SNR
Definition at line 61 of file yans-error-rate-model.cc.
References NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by GetFecQamBer().
GetTypeId()
TypeId ns3::YansErrorRateModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 35 of file yans-error-rate-model.cc.
References ns3::TypeId::SetParent().
The documentation for this class was generated from the following files:
src/wifi/model/yans-error-rate-model.h
src/wifi/model/yans-error-rate-model.cc