ns-3: ns3::FfMacSchedSapProvider Class Reference
ns3::FfMacSchedSapProvider Class Reference abstract
LTE Models » FF MAC Schedulers
Provides the SCHED SAP.
#include "ff-mac-sched-sap.h"
Classes
struct SchedDlCqiInfoReqParameters
Parameters of the SCHED_DL_CQI_INFO_REQ primitive.
struct SchedDlMacBufferReqParameters
Parameters of the SCHED_DL_MAC_BUFFER_REQ primitive.
struct SchedDlPagingBufferReqParameters
Parameters of the SCHED_DL_PAGING_BUFFER_REQ primitive.
struct SchedDlRachInfoReqParameters
Parameters of the SCHED_DL_RACH_INFO_REQ primitive.
struct SchedDlRlcBufferReqParameters
Parameters of the API primitives.
struct SchedDlTriggerReqParameters
Parameters of the SCHED_DL_TRIGGER_REQ primitive.
struct SchedUlCqiInfoReqParameters
Parameters of the SCHED_UL_CQI_INFO_REQ primitive.
struct SchedUlMacCtrlInfoReqParameters
Parameters of the SCHED_UL_MAC_CTRL_INFO_REQ primitive.
struct SchedUlNoiseInterferenceReqParameters
Parameters of the SCHED_UL_NOISE_INTERFERENCE_REQ primitive.
struct SchedUlSrInfoReqParameters
Parameters of the SCHED_UL_SR_INFO_REQ primitive.
struct SchedUlTriggerReqParameters
Parameters of the SCHED_UL_TRIGGER_REQ primitive.
Public Member Functions
virtual ~FfMacSchedSapProvider ()
virtual void SchedDlCqiInfoReq (const struct SchedDlCqiInfoReqParameters &params)=0
SCHED_DL_CQI_INFO_REQ.
virtual void SchedDlMacBufferReq (const struct SchedDlMacBufferReqParameters &params)=0
SCHED_DL_MAC_BUFFER_REQ.
virtual void SchedDlPagingBufferReq (const struct SchedDlPagingBufferReqParameters &params)=0
SCHED_DL_PAGING_BUFFER_REQ.
virtual void SchedDlRachInfoReq (const struct SchedDlRachInfoReqParameters &params)=0
SCHED_DL_RACH_INFO_REQ.
virtual void SchedDlRlcBufferReq (const struct SchedDlRlcBufferReqParameters &params)=0
SCHED_DL_RLC_BUFFER_REQ.
virtual void SchedDlTriggerReq (const struct SchedDlTriggerReqParameters &params)=0
SCHED_DL_TRIGGER_REQ.
virtual void SchedUlCqiInfoReq (const struct SchedUlCqiInfoReqParameters &params)=0
SCHED_UL_CQI_INFO_REQ.
virtual void SchedUlMacCtrlInfoReq (const struct SchedUlMacCtrlInfoReqParameters &params)=0
SCHED_UL_MAC_CTRL_INFO_REQ.
virtual void SchedUlNoiseInterferenceReq (const struct SchedUlNoiseInterferenceReqParameters &params)=0
SCHED_UL_NOISE_INTERFERENCE_REQ.
virtual void SchedUlSrInfoReq (const struct SchedUlSrInfoReqParameters &params)=0
SCHED_UL_SR_INFO_REQ.
virtual void SchedUlTriggerReq (const struct SchedUlTriggerReqParameters &params)=0
SCHED_UL_TRIGGER_REQ.
Detailed Description
Provides the SCHED SAP.
This abstract class defines the MAC Scheduler interface specified in the Femto Forum Technical Document:
LTE MAC Scheduler Interface Specification v1.11
The Technical Document contains a detailed description of the API. The documentation of this class refers to sections of this Technical Document.
You can found an example of the implementation of this interface in the SampleFfMacSchedSapProvider and SampleFfMacSchedSapUser classes
Definition at line 46 of file ff-mac-sched-sap.h.
Constructor & Destructor Documentation
~FfMacSchedSapProvider()
ns3::FfMacSchedSapProvider::~FfMacSchedSapProvider () virtual
Definition at line 26 of file ff-mac-sched-sap.cc.
Member Function Documentation
SchedDlCqiInfoReq()
virtual void ns3::FfMacSchedSapProvider::SchedDlCqiInfoReq (const struct SchedDlCqiInfoReqParameters & params) pure virtual
SCHED_DL_CQI_INFO_REQ.
Parameters
params SchedDlCqiInfoReqParameters
Implemented in ns3::MemberSchedSapProvider< C >.
Referenced by ns3::LteEnbMac::DoSubframeIndication().
SchedDlMacBufferReq()
virtual void ns3::FfMacSchedSapProvider::SchedDlMacBufferReq (const struct SchedDlMacBufferReqParameters & params) pure virtual
SCHED_DL_MAC_BUFFER_REQ.
Parameters
params SchedDlMacBufferReqParameters
Implemented in ns3::MemberSchedSapProvider< C >.
SchedDlPagingBufferReq()
virtual void ns3::FfMacSchedSapProvider::SchedDlPagingBufferReq (const struct SchedDlPagingBufferReqParameters & params) pure virtual
SCHED_DL_PAGING_BUFFER_REQ.
Parameters
params SchedDlPagingBufferReqParameters
Implemented in ns3::MemberSchedSapProvider< C >.
SchedDlRachInfoReq()
virtual void ns3::FfMacSchedSapProvider::SchedDlRachInfoReq (const struct SchedDlRachInfoReqParameters & params) pure virtual
SCHED_DL_RACH_INFO_REQ.
Parameters
params SchedDlRachInfoReqParameters
Implemented in ns3::MemberSchedSapProvider< C >.
Referenced by ns3::LteEnbMac::DoSubframeIndication().
SchedDlRlcBufferReq()
virtual void ns3::FfMacSchedSapProvider::SchedDlRlcBufferReq (const struct SchedDlRlcBufferReqParameters & params) pure virtual
SCHED_DL_RLC_BUFFER_REQ.
Parameters
params SchedDlRlcBufferReqParameters
Implemented in ns3::MemberSchedSapProvider< C >.
Referenced by ns3::LteEnbMac::DoReportBufferStatus().
SchedDlTriggerReq()
virtual void ns3::FfMacSchedSapProvider::SchedDlTriggerReq (const struct SchedDlTriggerReqParameters & params) pure virtual
SCHED_DL_TRIGGER_REQ.
Parameters
params SchedDlTriggerReqParameters
Implemented in ns3::MemberSchedSapProvider< C >.
Referenced by ns3::LteEnbMac::DoSubframeIndication().
SchedUlCqiInfoReq()
virtual void ns3::FfMacSchedSapProvider::SchedUlCqiInfoReq (const struct SchedUlCqiInfoReqParameters & params) pure virtual
SCHED_UL_CQI_INFO_REQ.
Parameters
params SchedUlCqiInfoReqParameters
Implemented in ns3::MemberSchedSapProvider< C >.
Referenced by ns3::LteEnbMac::DoSubframeIndication().
SchedUlMacCtrlInfoReq()
virtual void ns3::FfMacSchedSapProvider::SchedUlMacCtrlInfoReq (const struct SchedUlMacCtrlInfoReqParameters & params) pure virtual
SCHED_UL_MAC_CTRL_INFO_REQ.
Parameters
params SchedUlMacCtrlInfoReqParameters
Implemented in ns3::MemberSchedSapProvider< C >.
Referenced by ns3::LteEnbMac::DoSubframeIndication().
SchedUlNoiseInterferenceReq()
virtual void ns3::FfMacSchedSapProvider::SchedUlNoiseInterferenceReq (const struct SchedUlNoiseInterferenceReqParameters & params) pure virtual
SCHED_UL_NOISE_INTERFERENCE_REQ.
Parameters
params SchedUlNoiseInterferenceReqParameters
Implemented in ns3::MemberSchedSapProvider< C >.
SchedUlSrInfoReq()
virtual void ns3::FfMacSchedSapProvider::SchedUlSrInfoReq (const struct SchedUlSrInfoReqParameters & params) pure virtual
SCHED_UL_SR_INFO_REQ.
Parameters
params SchedUlSrInfoReqParameters
Implemented in ns3::MemberSchedSapProvider< C >.
SchedUlTriggerReq()
virtual void ns3::FfMacSchedSapProvider::SchedUlTriggerReq (const struct SchedUlTriggerReqParameters & params) pure virtual
SCHED_UL_TRIGGER_REQ.
Parameters
params SchedUlTriggerReqParameters
Implemented in ns3::MemberSchedSapProvider< C >.
Referenced by ns3::LteEnbMac::DoSubframeIndication().
The documentation for this class was generated from the following files:
src/lte/model/ff-mac-sched-sap.h
src/lte/model/ff-mac-sched-sap.cc