ns-3: ns3::UeMemberLteUeCmacSapUser Class Reference
ns3::UeMemberLteUeCmacSapUser Class Reference
UeMemberLteUeCmacSapUser class.
Public Member Functions
UeMemberLteUeCmacSapUser (LteUeRrc *rrc)
Constructor.
virtual void NotifyRandomAccessFailed ()
Notify the RRC that the MAC Random Access procedure failed.
virtual void NotifyRandomAccessSuccessful ()
Notify the RRC that the MAC Random Access procedure completed successfully.
virtual void SetTemporaryCellRnti (uint16_t rnti)
Public Member Functions inherited from ns3::LteUeCmacSapUser
virtual ~LteUeCmacSapUser ()
Private Attributes
LteUeRrc * m_rrc
the RRC class
Detailed Description
UeMemberLteUeCmacSapUser class.
Definition at line 53 of file lte-ue-rrc.cc.
Constructor & Destructor Documentation
UeMemberLteUeCmacSapUser()
ns3::UeMemberLteUeCmacSapUser::UeMemberLteUeCmacSapUser (LteUeRrc * rrc)
Constructor.
Parameters
rrc the RRC class
Definition at line 71 of file lte-ue-rrc.cc.
Member Function Documentation
NotifyRandomAccessFailed()
void ns3::UeMemberLteUeCmacSapUser::NotifyRandomAccessFailed () virtual
Notify the RRC that the MAC Random Access procedure failed.
Implements ns3::LteUeCmacSapUser.
Definition at line 90 of file lte-ue-rrc.cc.
References ns3::LteUeRrc::DoNotifyRandomAccessFailed(), and m_rrc.
NotifyRandomAccessSuccessful()
void ns3::UeMemberLteUeCmacSapUser::NotifyRandomAccessSuccessful () virtual
Notify the RRC that the MAC Random Access procedure completed successfully.
Implements ns3::LteUeCmacSapUser.
Definition at line 84 of file lte-ue-rrc.cc.
References ns3::LteUeRrc::DoNotifyRandomAccessSuccessful(), and m_rrc.
SetTemporaryCellRnti()
void ns3::UeMemberLteUeCmacSapUser::SetTemporaryCellRnti (uint16_t rnti) virtual
Parameters
rnti the T-C-RNTI, which will eventually become the C-RNTI after contention resolution
Implements ns3::LteUeCmacSapUser.
Definition at line 77 of file lte-ue-rrc.cc.
References ns3::LteUeRrc::DoSetTemporaryCellRnti(), and m_rrc.
Member Data Documentation
m_rrc
LteUeRrc* ns3::UeMemberLteUeCmacSapUser::m_rrc private
the RRC class
Definition at line 68 of file lte-ue-rrc.cc.
Referenced by NotifyRandomAccessFailed(), NotifyRandomAccessSuccessful(), and SetTemporaryCellRnti().
The documentation for this class was generated from the following file:
src/lte/model/lte-ue-rrc.cc