ns-3: BuildingsPathlossTestCase Class Reference
BuildingsPathlossTestCase Class Reference
#include "buildings-pathloss-test.h"
Public Member Functions
BuildingsPathlossTestCase (double freq, uint16_t m1, uint16_t m2, EnvironmentType env, CitySize city, double refValue, std::string name)
TestCase.
virtual ~BuildingsPathlossTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
Ptr< MobilityModel > CreateMobilityModel (uint16_t index)
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
CitySize m_city
EnvironmentType m_env
double m_freq
double m_lossRef
uint16_t m_mobilityModelIndex1
uint16_t m_mobilityModelIndex2
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 40 of file buildings-pathloss-test.h.
Constructor & Destructor Documentation
BuildingsPathlossTestCase()
BuildingsPathlossTestCase::BuildingsPathlossTestCase (double freq, uint16_t m1, uint16_t m2, EnvironmentType env, CitySize city, double refValue, std::string name)
TestCase.
Definition at line 138 of file buildings-pathloss-test.cc.
~BuildingsPathlossTestCase()
BuildingsPathlossTestCase::~BuildingsPathlossTestCase () virtual
Definition at line 149 of file buildings-pathloss-test.cc.
Member Function Documentation
CreateMobilityModel()
Ptr< MobilityModel > BuildingsPathlossTestCase::CreateMobilityModel (uint16_t index) private
Definition at line 188 of file buildings-pathloss-test.cc.
References ns3::Object::AggregateObject(), ns3::MobilityBuildingInfo::MakeConsistent(), and ns3::MobilityModel::SetPosition().
Referenced by DoRun().
DoRun()
void BuildingsPathlossTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 154 of file buildings-pathloss-test.cc.
References CreateMobilityModel(), ns3::HybridBuildingsPropagationLossModel::GetLoss(), m_city, m_env, m_freq, m_lossRef, m_mobilityModelIndex1, m_mobilityModelIndex2, NS_LOG_FUNCTION, NS_LOG_INFO, NS_TEST_ASSERT_MSG_EQ_TOL, ns3::ObjectBase::SetAttribute(), ns3::Building::SetBoundaries(), ns3::Building::SetBuildingType(), ns3::Building::SetExtWallsType(), and ns3::Building::SetNFloors().
Member Data Documentation
m_city
CitySize BuildingsPathlossTestCase::m_city private
Definition at line 54 of file buildings-pathloss-test.h.
Referenced by DoRun().
m_env
EnvironmentType BuildingsPathlossTestCase::m_env private
Definition at line 53 of file buildings-pathloss-test.h.
Referenced by DoRun().
m_freq
double BuildingsPathlossTestCase::m_freq private
Definition at line 50 of file buildings-pathloss-test.h.
Referenced by DoRun().
m_lossRef
double BuildingsPathlossTestCase::m_lossRef private
Definition at line 55 of file buildings-pathloss-test.h.
Referenced by DoRun().
m_mobilityModelIndex1
uint16_t BuildingsPathlossTestCase::m_mobilityModelIndex1 private
Definition at line 51 of file buildings-pathloss-test.h.
Referenced by DoRun().
m_mobilityModelIndex2
uint16_t BuildingsPathlossTestCase::m_mobilityModelIndex2 private
Definition at line 52 of file buildings-pathloss-test.h.
Referenced by DoRun().
The documentation for this class was generated from the following files:
src/buildings/test/buildings-pathloss-test.h
src/buildings/test/buildings-pathloss-test.cc