ns-3: TxDurationTest Class Reference
TxDurationTest Class Reference
Wifi Models » wifi module tests | Test suites
Tx Duration Test.
Public Member Functions
TxDurationTest ()
virtual ~TxDurationTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
bool CheckPayloadDuration (uint32_t size, WifiMode payloadMode, uint16_t channelWidth, uint16_t guardInterval, WifiPreamble preamble, Time knownDuration)
Check if the payload tx duration returned by InterferenceHelper corresponds to a known value of the pay.
bool CheckTxDuration (uint32_t size, WifiMode payloadMode, uint16_t channelWidth, uint16_t guardInterval, WifiPreamble preamble, Time knownDuration)
Check if the overall tx duration returned by InterferenceHelper corresponds to a known value of the pay.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Tx Duration Test.
Definition at line 39 of file tx-duration-test.cc.
Constructor & Destructor Documentation
TxDurationTest()
TxDurationTest::TxDurationTest ()
Definition at line 80 of file tx-duration-test.cc.
~TxDurationTest()
TxDurationTest::~TxDurationTest () virtual
Definition at line 85 of file tx-duration-test.cc.
Member Function Documentation
CheckPayloadDuration()
bool TxDurationTest::CheckPayloadDuration (uint32_t size, WifiMode payloadMode, uint16_t channelWidth, uint16_t guardInterval, WifiPreamble preamble, Time knownDuration) private
Check if the payload tx duration returned by InterferenceHelper corresponds to a known value of the pay.
Parameters
size size of payload in octets (includes everything after the PHY header)
payloadMode the WifiMode used for the transmission
channelWidth the channel width used for the transmission (in MHz)
guardInterval the guard interval duration used for the transmission (in nanoseconds)
preamble the WifiPreamble used for the transmission
knownDuration the known duration value of the transmission
Returns
true if values correspond, false otherwise
Definition at line 90 of file tx-duration-test.cc.
References CHANNEL_1_MHZ, CHANNEL_36_MHZ, ns3::WifiMode::GetDataRate(), ns3::WifiMode::GetModulationClass(), ns3::MicroSeconds(), third::phy, ns3::WifiTxVector::SetChannelWidth(), ns3::WifiTxVector::SetGuardInterval(), ns3::WifiTxVector::SetMode(), ns3::WifiTxVector::SetNess(), ns3::WifiTxVector::SetNss(), ns3::WifiTxVector::SetPreambleType(), ns3::WifiTxVector::SetStbc(), ns3::WIFI_MOD_CLASS_HE, ns3::WIFI_MOD_CLASS_HT, ns3::WIFI_MOD_CLASS_OFDM, and ns3::WIFI_MOD_CLASS_VHT.
Referenced by DoRun().
CheckTxDuration()
bool TxDurationTest::CheckTxDuration (uint32_t size, WifiMode payloadMode, uint16_t channelWidth, uint16_t guardInterval, WifiPreamble preamble, Time knownDuration) private
Check if the overall tx duration returned by InterferenceHelper corresponds to a known value of the pay.
Parameters
size size of payload in octets (includes everything after the PHY header)
payloadMode the WifiMode used for the transmission
channelWidth the channel width used for the transmission (in MHz)
guardInterval the guard interval duration used for the transmission (in nanoseconds)
preamble the WifiPreamble used for the transmission
knownDuration the known duration value of the transmission
Returns
true if values correspond, false otherwise
Definition at line 145 of file tx-duration-test.cc.
References CHANNEL_1_MHZ, CHANNEL_36_MHZ, ns3::WifiMode::GetDataRate(), ns3::WifiMode::GetModulationClass(), ns3::MicroSeconds(), third::phy, ns3::WifiTxVector::SetChannelWidth(), ns3::WifiTxVector::SetGuardInterval(), ns3::WifiTxVector::SetMode(), ns3::WifiTxVector::SetNess(), ns3::WifiTxVector::SetNss(), ns3::WifiTxVector::SetPreambleType(), ns3::WifiTxVector::SetStbc(), ns3::WIFI_MOD_CLASS_HE, ns3::WIFI_MOD_CLASS_HT, ns3::WIFI_MOD_CLASS_OFDM, and ns3::WIFI_MOD_CLASS_VHT.
Referenced by DoRun().
DoRun()
void TxDurationTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 202 of file tx-duration-test.cc.
References CheckPayloadDuration(), CheckTxDuration(), ns3::MicroSeconds(), ns3::NanoSeconds(), NS_TEST_EXPECT_MSG_EQ, ns3::WIFI_PREAMBLE_HE_SU, ns3::WIFI_PREAMBLE_HT_GF, ns3::WIFI_PREAMBLE_HT_MF, ns3::WIFI_PREAMBLE_LONG, ns3::WIFI_PREAMBLE_SHORT, and ns3::WIFI_PREAMBLE_VHT_SU.
The documentation for this class was generated from the following file:
src/wifi/test/tx-duration-test.cc