ns-3: ns3::RandomPropagationLossModel Class Reference
ns3::RandomPropagationLossModel Class Reference
Propagation Models
The propagation loss follows a random distribution.
#include "propagation-loss-model.h"
Public Member Functions
RandomPropagationLossModel ()
virtual ~RandomPropagationLossModel ()
Public Member Functions inherited from ns3::PropagationLossModel
PropagationLossModel ()
virtual ~PropagationLossModel ()
int64_t AssignStreams (int64_t stream)
If this loss model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
double CalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account all the PropagationLossModel(s) chained to the current one.
Ptr< PropagationLossModel > GetNext ()
Gets the next PropagationLossModel in the chain of loss models that act on the signal.
void SetNext (Ptr< PropagationLossModel > next)
Enables a chain of loss models to act on the signal.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::PropagationLossModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
RandomPropagationLossModel (const RandomPropagationLossModel &)
Copy constructor.
virtual int64_t DoAssignStreams (int64_t stream)
Subclasses must implement this; those not using random variables can return zero.
virtual double DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account only the particular PropagationLossModel.
RandomPropagationLossModel & operator= (const RandomPropagationLossModel &)
Copy constructor.
Private Attributes
Ptr< RandomVariableStream > m_variable
random generator
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The propagation loss follows a random distribution.
Definition at line 151 of file propagation-loss-model.h.
Constructor & Destructor Documentation
RandomPropagationLossModel() [1/2]
ns3::RandomPropagationLossModel::RandomPropagationLossModel ()
Definition at line 115 of file propagation-loss-model.cc.
~RandomPropagationLossModel()
ns3::RandomPropagationLossModel::~RandomPropagationLossModel () virtual
Definition at line 120 of file propagation-loss-model.cc.
RandomPropagationLossModel() [2/2]
ns3::RandomPropagationLossModel::RandomPropagationLossModel (const RandomPropagationLossModel &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Member Function Documentation
DoAssignStreams()
int64_t ns3::RandomPropagationLossModel::DoAssignStreams (int64_t stream) private virtual
Subclasses must implement this; those not using random variables can return zero.
Implements ns3::PropagationLossModel.
Definition at line 135 of file propagation-loss-model.cc.
References m_variable, and ns3::RandomVariableStream::SetStream().
DoCalcRxPower()
double ns3::RandomPropagationLossModel::DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const private virtual
Returns the Rx Power taking into account only the particular PropagationLossModel.
Parameters
txPowerDbm current transmission power (in dBm)
a the mobility model of the source
b the mobility model of the destination
Returns
the reception power after adding/multiplying propagation loss (in dBm)
Implements ns3::PropagationLossModel.
Definition at line 125 of file propagation-loss-model.cc.
References ns3::RandomVariableStream::GetValue(), m_variable, and NS_LOG_DEBUG.
GetTypeId()
TypeId ns3::RandomPropagationLossModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 102 of file propagation-loss-model.cc.
References m_variable, ns3::MakePointerAccessor(), and ns3::TypeId::SetParent().
operator=()
RandomPropagationLossModel& ns3::RandomPropagationLossModel::operator= (const RandomPropagationLossModel &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Returns
Member Data Documentation
m_variable
Ptr<RandomVariableStream> ns3::RandomPropagationLossModel::m_variable private
random generator
Definition at line 181 of file propagation-loss-model.h.
Referenced by DoAssignStreams(), DoCalcRxPower(), and GetTypeId().
The documentation for this class was generated from the following files:
src/propagation/model/propagation-loss-model.h
src/propagation/model/propagation-loss-model.cc