ns-3: anonymous_namespace{packet-metadata-test.cc}::HistoryTrailer< N > Class Template Reference
anonymous_namespace{packet-metadata-test.cc}::HistoryTrailer< N > Class Template Reference
Network » Network module unit tests | Test suites
Template trailer-type class to check the proper trailer concatenation.
Public Member Functions
HistoryTrailer ()
virtual uint32_t Deserialize (Buffer::Iterator start)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
Public Member Functions inherited from anonymous_namespace{packet-metadata-test.cc}::HistoryTrailerBase
HistoryTrailerBase ()
bool IsOk (void) const
Checks if the header has deserialization errors.
Public Member Functions inherited from ns3::Trailer
virtual ~Trailer ()
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from anonymous_namespace{packet-metadata-test.cc}::HistoryTrailerBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Trailer
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Protected Member Functions inherited from anonymous_namespace{packet-metadata-test.cc}::HistoryTrailerBase
void ReportError (void)
Signal that an error has been found in deserialization.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
template<int N>
class anonymous_namespace{packet-metadata-test.cc}::HistoryTrailer< N >
Template trailer-type class to check the proper trailer concatenation.
Note
Class internal to packet-metadata-test.cc
Definition at line 236 of file packet-metadata-test.cc.
Constructor & Destructor Documentation
HistoryTrailer()
template<int N> anonymous_namespace{packet-metadata-test.cc}::HistoryTrailer< N >::HistoryTrailer
Definition at line 254 of file packet-metadata-test.cc.
Member Function Documentation
Deserialize()
template<int N> uint32_t anonymous_namespace{packet-metadata-test.cc}::HistoryTrailer< N >::Deserialize (Buffer::Iterator end) virtual
Parameters
end an iterator which points to the end of the buffer where the trailer should be read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveTrailer to re-create a trailer from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this trailer in real networks. The input iterator points to the end of the area where the data shall be written. This method is thus expected to call Buffer::Iterator::Prev prior to actually reading any data.
Implements ns3::Trailer.
Definition at line 298 of file packet-metadata-test.cc.
References visualizer.core::start().
GetInstanceTypeId()
template<int N> TypeId anonymous_namespace{packet-metadata-test.cc}::HistoryTrailer< N >::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 273 of file packet-metadata-test.cc.
GetSerializedSize()
template<int N> uint32_t anonymous_namespace{packet-metadata-test.cc}::HistoryTrailer< N >::GetSerializedSize (void) const virtual
Returns
the expected size of the trailer.
This method is used by Packet::AddTrailer to store a trailer into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full trailer data by Serialize.
Implements ns3::Trailer.
Definition at line 285 of file packet-metadata-test.cc.
GetTypeId()
template<int N> TypeId anonymous_namespace{packet-metadata-test.cc}::HistoryTrailer< N >::GetTypeId (void) static
Get the type ID.
Returns
The object TypeId.
Definition at line 260 of file packet-metadata-test.cc.
References ns3::TypeId::SetParent().
Print()
template<int N> void anonymous_namespace{packet-metadata-test.cc}::HistoryTrailer< N >::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a trailer as ascii data to a c++ output stream. Although the trailer is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Trailer.
Definition at line 279 of file packet-metadata-test.cc.
References NS_ASSERT.
Serialize()
template<int N> void anonymous_namespace{packet-metadata-test.cc}::HistoryTrailer< N >::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the trailer should be written.
This method is used by Packet::AddTrailer to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this trailer in real networks. The input iterator points to the end of the area where the data shall be written. This method is thus expected to call Buffer::Iterator::Prev prior to actually writing any data.
Implements ns3::Trailer.
Definition at line 291 of file packet-metadata-test.cc.
References visualizer.core::start().
The documentation for this class was generated from the following file:
src/network/test/packet-metadata-test.cc