ns-3: ns3::FqCoDelFlow Class Reference
ns3::FqCoDelFlow Class Reference
Traffic-control
A flow queue used by the FqCoDel queue disc.
#include "fq-codel-queue-disc.h"
Public Types
enum FlowStatus { INACTIVE, NEW_FLOW, OLD_FLOW }
Used to determine the status of this flow queue.
Public Member Functions
FqCoDelFlow ()
FqCoDelFlow constructor.
virtual ~FqCoDelFlow ()
int32_t GetDeficit (void) const
Get the deficit for this flow.
FlowStatus GetStatus (void) const
Get the status of this flow.
void IncreaseDeficit (int32_t deficit)
Increase the deficit for this flow.
void SetDeficit (uint32_t deficit)
Set the deficit for this flow.
void SetStatus (FlowStatus status)
Set the status for this flow.
Public Member Functions inherited from ns3::QueueDiscClass
QueueDiscClass ()
virtual ~QueueDiscClass ()
Ptr< QueueDisc > GetQueueDisc (void) const
Get the queue disc attached to this class.
void SetQueueDisc (Ptr< QueueDisc > qd)
Set the queue disc attached to this class.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::QueueDiscClass
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
int32_t m_deficit
the deficit for this flow
FlowStatus m_status
the status of this flow
Additional Inherited Members
Protected Member Functions inherited from ns3::QueueDiscClass
virtual void DoDispose (void)
Dispose of the object.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A flow queue used by the FqCoDel queue disc.
Definition at line 38 of file fq-codel-queue-disc.h.
Member Enumeration Documentation
FlowStatus
enum ns3::FqCoDelFlow::FlowStatus
Used to determine the status of this flow queue.
Enumerator
INACTIVE
NEW_FLOW
OLD_FLOW
Definition at line 56 of file fq-codel-queue-disc.h.
Constructor & Destructor Documentation
FqCoDelFlow()
ns3::FqCoDelFlow::FqCoDelFlow ()
FqCoDelFlow constructor.
Definition at line 45 of file fq-codel-queue-disc.cc.
References NS_LOG_FUNCTION.
~FqCoDelFlow()
ns3::FqCoDelFlow::~FqCoDelFlow () virtual
Definition at line 52 of file fq-codel-queue-disc.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
GetDeficit()
int32_t ns3::FqCoDelFlow::GetDeficit (void) const
Get the deficit for this flow.
Returns
the deficit for this flow
Definition at line 65 of file fq-codel-queue-disc.cc.
References m_deficit, and NS_LOG_FUNCTION.
Referenced by FqCoDelQueueDiscDeficit::DoRun().
GetStatus()
FqCoDelFlow::FlowStatus ns3::FqCoDelFlow::GetStatus (void) const
Get the status of this flow.
Returns
the status of this flow
Definition at line 86 of file fq-codel-queue-disc.cc.
References m_status, and NS_LOG_FUNCTION.
Referenced by FqCoDelQueueDiscDeficit::DoRun().
GetTypeId()
TypeId ns3::FqCoDelFlow::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 35 of file fq-codel-queue-disc.cc.
References ns3::TypeId::SetParent().
IncreaseDeficit()
void ns3::FqCoDelFlow::IncreaseDeficit (int32_t deficit)
Increase the deficit for this flow.
Parameters
deficit the amount by which the deficit is to be increased
Definition at line 72 of file fq-codel-queue-disc.cc.
References m_deficit, and NS_LOG_FUNCTION.
SetDeficit()
void ns3::FqCoDelFlow::SetDeficit (uint32_t deficit)
Set the deficit for this flow.
Parameters
deficit the deficit for this flow
Definition at line 58 of file fq-codel-queue-disc.cc.
References m_deficit, and NS_LOG_FUNCTION.
SetStatus()
void ns3::FqCoDelFlow::SetStatus (FlowStatus status)
Set the status for this flow.
Parameters
status the status for this flow
Definition at line 79 of file fq-codel-queue-disc.cc.
References m_status, and NS_LOG_FUNCTION.
Member Data Documentation
m_deficit
int32_t ns3::FqCoDelFlow::m_deficit private
the deficit for this flow
Definition at line 90 of file fq-codel-queue-disc.h.
Referenced by GetDeficit(), IncreaseDeficit(), and SetDeficit().
m_status
FlowStatus ns3::FqCoDelFlow::m_status private
the status of this flow
Definition at line 91 of file fq-codel-queue-disc.h.
Referenced by GetStatus(), and SetStatus().
The documentation for this class was generated from the following files:
src/traffic-control/model/fq-codel-queue-disc.h
src/traffic-control/model/fq-codel-queue-disc.cc