ns-3: BuildingsHelperOneTestCase Class Reference
BuildingsHelperOneTestCase Class Reference
Public Member Functions
BuildingsHelperOneTestCase (PositionInBuilding pib, BuildingData bd)
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Static Public Member Functions
static std::string BuildNameString (PositionInBuilding pib, BuildingData bd)
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
BuildingData m_bd
PositionInBuilding m_pib
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 91 of file buildings-helper-test.cc.
Constructor & Destructor Documentation
BuildingsHelperOneTestCase()
BuildingsHelperOneTestCase::BuildingsHelperOneTestCase (PositionInBuilding pib, BuildingData bd)
Definition at line 124 of file buildings-helper-test.cc.
Member Function Documentation
BuildNameString()
std::string BuildingsHelperOneTestCase::BuildNameString (PositionInBuilding pib, BuildingData bd) static
Definition at line 105 of file buildings-helper-test.cc.
References PositionInBuilding::bid, PositionInBuilding::fn, PositionInBuilding::indoor, PositionInBuilding::pos, PositionInBuilding::rx, and PositionInBuilding::ry.
Referenced by DoRun().
DoRun()
void BuildingsHelperOneTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 132 of file buildings-helper-test.cc.
References ns3::Object::AggregateObject(), BuildNameString(), PositionInBuilding::fn, ns3::MobilityBuildingInfo::GetBuilding(), ns3::MobilityBuildingInfo::GetFloorNumber(), ns3::MobilityBuildingInfo::GetRoomNumberX(), ns3::MobilityBuildingInfo::GetRoomNumberY(), PositionInBuilding::indoor, ns3::MobilityBuildingInfo::IsIndoor(), m_bd, m_pib, third::mobility, BuildingData::nf, first::nodes, BuildingData::nrx, BuildingData::nry, NS_LOG_FUNCTION, NS_LOG_LOGIC(), NS_TEST_ASSERT_MSG_EQ, PositionInBuilding::pos, PositionInBuilding::rx, PositionInBuilding::ry, ns3::Building::SetBoundaries(), ns3::Building::SetNFloors(), ns3::Building::SetNRoomsX(), ns3::Building::SetNRoomsY(), ns3::MobilityModel::SetPosition(), BuildingData::xmax, BuildingData::xmin, BuildingData::ymax, BuildingData::ymin, BuildingData::zmax, and BuildingData::zmin.
Member Data Documentation
m_bd
BuildingData BuildingsHelperOneTestCase::m_bd private
Definition at line 101 of file buildings-helper-test.cc.
Referenced by DoRun().
m_pib
PositionInBuilding BuildingsHelperOneTestCase::m_pib private
Definition at line 100 of file buildings-helper-test.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/buildings/test/buildings-helper-test.cc