ns-3: TcpZeroWindowTest Class Reference
TcpZeroWindowTest Class Reference
Internet » internet module tests | Test suites
Testing the congestion avoidance increment on TCP ZeroWindow.
Public Member Functions
TcpZeroWindowTest (const std::string &desc)
Constructor.
Public Member Functions inherited from ns3::TcpGeneralTest
TcpGeneralTest (const std::string &desc)
TcpGeneralTest constructor.
~TcpGeneralTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Member Functions
virtual void ConfigureEnvironment ()
Change the configuration of the environment.
virtual void ConfigureProperties ()
Change the configuration of the socket properties.
virtual Ptr< TcpSocketMsgBase > CreateReceiverSocket (Ptr< Node > node)
Create and install the socket to install on the receiver.
void FinalChecks ()
Performs the (eventual) final checks through test asserts.
void IncreaseBufSize ()
Increase the receiver buffer size.
void NormalClose (SocketWho who)
Socket closed normally.
virtual void ProcessedAck (const Ptr< const TcpSocketState > tcb, const TcpHeader &h, SocketWho who)
Processed ack.
virtual void Rx (const Ptr< const Packet > p, const TcpHeader &h, SocketWho who)
Packet received from IP layer.
virtual void Tx (const Ptr< const Packet > p, const TcpHeader &h, SocketWho who)
Packet transmitted down to IP layer.
Protected Member Functions inherited from ns3::TcpGeneralTest
virtual void AfterRTOExpired (const Ptr< const TcpSocketState > tcb, SocketWho who)
Rto has expired.
virtual void BeforeRTOExpired (const Ptr< const TcpSocketState > tcb, SocketWho who)
Rto has expired.
virtual void BytesInFlightTrace (uint32_t oldValue, uint32_t newValue)
Bytes in flight changes.
virtual void CongStateTrace (const TcpSocketState::TcpCongState_t oldValue, const TcpSocketState::TcpCongState_t newValue)
State on Ack state machine changes.
virtual Ptr< SimpleChannel > CreateChannel ()
Create and return the channel installed between the two socket.
virtual Ptr< ErrorModel > CreateReceiverErrorModel ()
Create and return the error model to install in the receiver node.
virtual Ptr< ErrorModel > CreateSenderErrorModel ()
Create and return the error model to install in the sender node.
virtual Ptr< TcpSocketMsgBase > CreateSenderSocket (Ptr< Node > node)
Create and install the socket to install on the sender.
virtual Ptr< TcpSocketMsgBase > CreateSocket (Ptr< Node > node, TypeId socketType, TypeId congControl)
Create a socket.
virtual Ptr< TcpSocketMsgBase > CreateSocket (Ptr< Node > node, TypeId socketType, TypeId congControl, TypeId recoveryAlgorithm)
Create a socket.
virtual void CWndInflTrace (uint32_t oldValue, uint32_t newValue)
Tracks the inflated congestion window changes.
virtual void CWndTrace (uint32_t oldValue, uint32_t newValue)
Tracks the congestion window changes.
virtual void DataSent (uint32_t size, SocketWho who)
Notifying application for sent data.
void DoConnect ()
Scheduled at 0.0, SENDER starts the connection to RECEIVER.
virtual void DoRun (void)
Execute the tcp test.
virtual void DoTeardown (void)
Teardown the TCP test.
virtual void ErrorClose (SocketWho who)
Socket closed with an error.
Time GetClockGranularity (SocketWho who)
Get the clock granularity attribute.
Time GetConnTimeout (SocketWho who)
Get the retransmission time for the SYN segments.
uint32_t GetDelAckCount (SocketWho who)
Get the number of delayed ack (if present)
Time GetDelAckTimeout (SocketWho who)
Get the timeout of delayed ack (if present)
uint32_t GetDupAckCount (SocketWho who)
Get the number of dupack received.
SequenceNumber32 GetHighestTxMark (SocketWho who)
Get the highest tx mark of the node specified.
uint32_t GetInitialCwnd (SocketWho who)
Get the initial congestion window.
uint32_t GetInitialSsThresh (SocketWho who)
Get the initial slow start threshold.
Time GetMinRto (SocketWho who)
Get the minimum RTO attribute.
uint32_t GetMtu () const
Get the MTU of the environment.
EventId GetPersistentEvent (SocketWho who)
Get the persistent event of the selected socket.
Time GetPersistentTimeout (SocketWho who)
Get the persistent timeout of the selected socket.
uint32_t GetPktCount () const
Get the number of application packets.
Time GetPktInterval () const
Get the interval to wait for each packet sent down from application to TCP.
uint32_t GetPktSize () const
Get the application packet size.
Time GetPropagationDelay () const
Get the channel Propagation Delay.
Ptr< TcpSocketMsgBase > GetReceiverSocket ()
Get the pointer to a previously created receiver socket.
uint32_t GetReTxThreshold (SocketWho who)
Get the retransmission threshold.
Time GetRto (SocketWho who)
Get the retransmission time.
Ptr< RttEstimator > GetRttEstimator (SocketWho who)
Get the Rtt estimator of the socket.
uint32_t GetRWnd (SocketWho who)
Get the rWnd of the selected socket.
Ptr< TcpRxBuffer > GetRxBuffer (SocketWho who)
Get the Rx buffer from selected socket.
uint32_t GetSegSize (SocketWho who)
Get the segment size of the node specified.
Ptr< TcpSocketMsgBase > GetSenderSocket ()
Get the pointer to a previously created sender socket.
Time GetStartTime () const
Get the data start time.
Ptr< TcpSocketState > GetTcb (SocketWho who)
Get the TCB from selected socket.
TcpSocket::TcpStates_t GetTcpState (SocketWho who)
Get the state of the TCP state machine.
Ptr< TcpTxBuffer > GetTxBuffer (SocketWho who)
Get the Tx buffer from selected socket.
virtual void HighestTxSeqTrace (SequenceNumber32 oldValue, SequenceNumber32 newValue)
Highest tx seq changes.
virtual void NextTxSeqTrace (SequenceNumber32 oldValue, SequenceNumber32 newValue)
Next tx seq changes.
virtual void PhyDrop (SocketWho who)
Link drop.
virtual void QueueDrop (SocketWho who)
Drop on the queue.
virtual void RateSampleUpdatedTrace (const TcpRateLinux::TcpRateSample &sample)
Track the rate sample value of TcpRateLinux.
virtual void RateUpdatedTrace (const TcpRateLinux::TcpRateConnection &rate)
Track the rate value of TcpRateLinux.
virtual void RcvAck (const Ptr< const TcpSocketState > tcb, const TcpHeader &h, SocketWho who)
Received ack.
virtual void ReceivePacket (Ptr< Socket > socket)
Packet received.
virtual void RtoTrace (Time oldValue, Time newValue)
RTO changes.
virtual void RttTrace (Time oldTime, Time newTime)
Rtt changes.
void SendPacket (Ptr< Socket > socket, uint32_t pktSize, uint32_t pktCount, Time pktInterval)
Send packets to other endpoint.
void SetAppPktCount (uint32_t pktCount)
Set app packet count.
void SetAppPktInterval (Time pktInterval)
Interval between app-generated packet.
void SetAppPktSize (uint32_t pktSize)
Set app packet size.
void SetCongestionControl (TypeId congControl)
Congestion control of the sender socket.
void SetInitialCwnd (SocketWho who, uint32_t initialCwnd)
Forcefully set the initial cwnd.
void SetInitialSsThresh (SocketWho who, uint32_t initialSsThresh)
Forcefully set the initial ssth.
void SetMTU (uint32_t mtu)
MTU of the bottleneck link.
void SetPropagationDelay (Time propDelay)
Propagation delay of the bottleneck link.
void SetRcvBufSize (SocketWho who, uint32_t size)
Forcefully set a defined size for rx buffer.
void SetRecoveryAlgorithm (TypeId reccovery)
recovery algorithm of the sender socket
void SetSegmentSize (SocketWho who, uint32_t segmentSize)
Forcefully set the segment size.
void SetTransmitStart (Time startTime)
Set the initial time at which the application sends the first data packet.
void SetUseEcn (SocketWho who, TcpSocketState::UseEcn_t useEcn)
Forcefully set the ecn use on.
virtual void SsThreshTrace (uint32_t oldValue, uint32_t newValue)
Slow start threshold changes.
virtual void UpdatedRttHistory (const SequenceNumber32 &seq, uint32_t sz, bool isRetransmission, SocketWho who)
Updated the Rtt history.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Protected Attributes
EventId m_receivePktEvent
Receive packet event.
bool m_receiverFinished
Receiver finished.
bool m_senderFinished
Send finished.
bool m_windowUpdated
Window updated.
bool m_zeroWindowProbe
ZeroWindow probe.
Protected Attributes inherited from ns3::TcpGeneralTest
TypeId m_congControlTypeId
Congestion control.
TypeId m_recoveryTypeId
Recovery.
Additional Inherited Members
Public Types inherited from ns3::TcpGeneralTest
enum SocketWho { SENDER, RECEIVER }
Used as parameter of methods, specifies on what node the caller is interested (e.g.
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Detailed Description
Testing the congestion avoidance increment on TCP ZeroWindow.
Definition at line 36 of file tcp-zero-window-test.cc.
Constructor & Destructor Documentation
TcpZeroWindowTest()
TcpZeroWindowTest::TcpZeroWindowTest (const std::string & desc)
Constructor.
Parameters
desc Test description.
Definition at line 72 of file tcp-zero-window-test.cc.
Member Function Documentation
ConfigureEnvironment()
void TcpZeroWindowTest::ConfigureEnvironment () protected virtual
Change the configuration of the environment.
Reimplemented from ns3::TcpGeneralTest.
Definition at line 82 of file tcp-zero-window-test.cc.
References ns3::MilliSeconds(), ns3::Seconds(), ns3::TcpGeneralTest::SetAppPktCount(), ns3::TcpGeneralTest::SetMTU(), ns3::TcpGeneralTest::SetPropagationDelay(), and ns3::TcpGeneralTest::SetTransmitStart().
ConfigureProperties()
void TcpZeroWindowTest::ConfigureProperties () protected virtual
Change the configuration of the socket properties.
Reimplemented from ns3::TcpGeneralTest.
Definition at line 92 of file tcp-zero-window-test.cc.
References ns3::TcpGeneralTest::SENDER, and ns3::TcpGeneralTest::SetInitialCwnd().
CreateReceiverSocket()
Ptr< TcpSocketMsgBase > TcpZeroWindowTest::CreateReceiverSocket (Ptr< Node > node) protected virtual
Create and install the socket to install on the receiver.
Parameters
node receiver node pointer
Returns
the socket to be installed in the receiver
Reimplemented from ns3::TcpGeneralTest.
Definition at line 105 of file tcp-zero-window-test.cc.
References IncreaseBufSize(), ns3::Seconds(), and ns3::ObjectBase::SetAttribute().
FinalChecks()
void TcpZeroWindowTest::FinalChecks () protected virtual
Performs the (eventual) final checks through test asserts.
Reimplemented from ns3::TcpGeneralTest.
Definition at line 224 of file tcp-zero-window-test.cc.
References m_receiverFinished, m_senderFinished, m_windowUpdated, m_zeroWindowProbe, and NS_TEST_ASSERT_MSG_EQ.
IncreaseBufSize()
void TcpZeroWindowTest::IncreaseBufSize () protected
Increase the receiver buffer size.
Definition at line 99 of file tcp-zero-window-test.cc.
References ns3::TcpGeneralTest::RECEIVER, and ns3::TcpGeneralTest::SetRcvBufSize().
Referenced by CreateReceiverSocket().
NormalClose()
void TcpZeroWindowTest::NormalClose (SocketWho who) protected virtual
Socket closed normally.
Parameters
who the socket closed (SENDER or RECEIVER)
Reimplemented from ns3::TcpGeneralTest.
Definition at line 211 of file tcp-zero-window-test.cc.
References m_receiverFinished, m_senderFinished, ns3::TcpGeneralTest::RECEIVER, and ns3::TcpGeneralTest::SENDER.
ProcessedAck()
void TcpZeroWindowTest::ProcessedAck (const Ptr< const TcpSocketState > tcb, const TcpHeader & h, SocketWho who) protected virtual
Processed ack.
Invoked after the processing of the ACK
Parameters
tcb Transmission Control Block
h the header of segment
who the socket which has processed the ACK (SENDER or RECEIVER)
Reimplemented from ns3::TcpGeneralTest.
Definition at line 237 of file tcp-zero-window-test.cc.
References ns3::TcpHeader::GetFlags(), ns3::TcpGeneralTest::GetPersistentEvent(), ns3::EventId::IsRunning(), NS_TEST_ASSERT_MSG_EQ, ns3::TcpGeneralTest::RECEIVER, and ns3::TcpGeneralTest::SENDER.
Rx()
void TcpZeroWindowTest::Rx (const Ptr< const Packet > p, const TcpHeader & h, SocketWho who) protected virtual
Packet received from IP layer.
Parameters
p packet
h header
who the socket which has received the packet (SENDER or RECEIVER)
Reimplemented from ns3::TcpGeneralTest.
Definition at line 185 of file tcp-zero-window-test.cc.
References ns3::TcpHeader::GetFlags(), ns3::Packet::GetSize(), ns3::TcpHeader::GetWindowSize(), m_windowUpdated, ns3::Now(), NS_LOG_INFO, NS_TEST_ASSERT_MSG_EQ, ns3::TcpGeneralTest::RECEIVER, and ns3::TcpGeneralTest::SENDER.
Tx()
void TcpZeroWindowTest::Tx (const Ptr< const Packet > p, const TcpHeader & h, SocketWho who) protected virtual
Packet transmitted down to IP layer.
Parameters
p packet
h header
who the socket which has received the packet (SENDER or RECEIVER)
Reimplemented from ns3::TcpGeneralTest.
Definition at line 117 of file tcp-zero-window-test.cc.
References ns3::GetCongStateFrom(), ns3::TcpHeader::GetFlags(), ns3::TcpHeader::GetSequenceNumber(), ns3::Packet::GetSize(), ns3::TcpGeneralTest::GetTcb(), ns3::TcpHeader::GetWindowSize(), m_zeroWindowProbe, ns3::Now(), NS_FATAL_ERROR, NS_LOG_INFO, NS_TEST_ASSERT_MSG_EQ, ns3::TcpGeneralTest::RECEIVER, and ns3::TcpGeneralTest::SENDER.
Member Data Documentation
m_receivePktEvent
EventId TcpZeroWindowTest::m_receivePktEvent protected
Receive packet event.
Definition at line 65 of file tcp-zero-window-test.cc.
m_receiverFinished
bool TcpZeroWindowTest::m_receiverFinished protected
Receiver finished.
Definition at line 69 of file tcp-zero-window-test.cc.
Referenced by FinalChecks(), and NormalClose().
m_senderFinished
bool TcpZeroWindowTest::m_senderFinished protected
Send finished.
Definition at line 68 of file tcp-zero-window-test.cc.
Referenced by FinalChecks(), and NormalClose().
m_windowUpdated
bool TcpZeroWindowTest::m_windowUpdated protected
Window updated.
Definition at line 67 of file tcp-zero-window-test.cc.
Referenced by FinalChecks(), and Rx().
m_zeroWindowProbe
bool TcpZeroWindowTest::m_zeroWindowProbe protected
ZeroWindow probe.
Definition at line 66 of file tcp-zero-window-test.cc.
Referenced by FinalChecks(), and Tx().
The documentation for this class was generated from the following file:
src/internet/test/tcp-zero-window-test.cc