ns-3: ns3::AmpduTag Class Reference
ns3::AmpduTag Class Reference
Wifi Models
#include "ampdu-tag.h"
Public Member Functions
AmpduTag ()
Create a AmpduTag with the default =0 no A-MPDU.
void Deserialize (TagBuffer i)
TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
Time GetRemainingAmpduDuration (void) const
uint8_t GetRemainingNbOfMpdus (void) const
uint32_t GetSerializedSize () const
void Print (std::ostream &os) const
void Serialize (TagBuffer i) const
void SetRemainingAmpduDuration (Time duration)
void SetRemainingNbOfMpdus (uint8_t nbOfMpdus)
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Time m_duration
Remaining duration of the A-MPDU.
uint8_t m_nbOfMpdus
Remaining number of MPDUs in the A-MPDU.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The aim of the AmpduTag is to provide means for a MAC to specify that a packet includes A-MPDU since this is done in HT-SIG and there is no HT-SIG representation in ns-3
Definition at line 36 of file ampdu-tag.h.
Constructor & Destructor Documentation
AmpduTag()
ns3::AmpduTag::AmpduTag ()
Create a AmpduTag with the default =0 no A-MPDU.
Definition at line 45 of file ampdu-tag.cc.
Member Function Documentation
Deserialize()
void ns3::AmpduTag::Deserialize (TagBuffer i) virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 79 of file ampdu-tag.cc.
References aloha::duration, m_duration, m_nbOfMpdus, ns3::TagBuffer::Read(), and ns3::TagBuffer::ReadU8().
GetInstanceTypeId()
TypeId ns3::AmpduTag::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 40 of file ampdu-tag.cc.
References GetTypeId().
GetRemainingAmpduDuration()
Time ns3::AmpduTag::GetRemainingAmpduDuration (void) const
Returns
the remaining duration of an A-MPDU
Returns the remaining duration of an A-MPDU
Definition at line 94 of file ampdu-tag.cc.
References m_duration.
GetRemainingNbOfMpdus()
uint8_t ns3::AmpduTag::GetRemainingNbOfMpdus (void) const
Returns
the remaining number of MPDUs in an A-MPDU
Returns the remaining number of MPDUs in an A-MPDU
Definition at line 88 of file ampdu-tag.cc.
References m_nbOfMpdus.
GetSerializedSize()
uint32_t ns3::AmpduTag::GetSerializedSize () const virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 65 of file ampdu-tag.cc.
GetTypeId()
TypeId ns3::AmpduTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 29 of file ampdu-tag.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::AmpduTag::Print (std::ostream & os) const virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 100 of file ampdu-tag.cc.
References m_duration, and m_nbOfMpdus.
Serialize()
void ns3::AmpduTag::Serialize (TagBuffer i) const virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 71 of file ampdu-tag.cc.
References aloha::duration, ns3::Time::GetTimeStep(), m_duration, m_nbOfMpdus, ns3::TagBuffer::Write(), and ns3::TagBuffer::WriteU8().
SetRemainingAmpduDuration()
void ns3::AmpduTag::SetRemainingAmpduDuration (Time duration)
Parameters
duration the remaining duration of the A-MPDU
Set the remaining duration of the A-MPDU.
Definition at line 58 of file ampdu-tag.cc.
References aloha::duration, m_duration, ns3::MilliSeconds(), and NS_ASSERT.
SetRemainingNbOfMpdus()
void ns3::AmpduTag::SetRemainingNbOfMpdus (uint8_t nbOfMpdus)
Parameters
nbOfMpdus the remaining number of MPDUs
Set the remaining number of MPDUs in the A-MPDU.
Definition at line 52 of file ampdu-tag.cc.
References m_nbOfMpdus.
Member Data Documentation
m_duration
Time ns3::AmpduTag::m_duration private
Remaining duration of the A-MPDU.
Definition at line 84 of file ampdu-tag.h.
Referenced by Deserialize(), GetRemainingAmpduDuration(), Print(), Serialize(), and SetRemainingAmpduDuration().
m_nbOfMpdus
uint8_t ns3::AmpduTag::m_nbOfMpdus private
Remaining number of MPDUs in the A-MPDU.
Definition at line 83 of file ampdu-tag.h.
Referenced by Deserialize(), GetRemainingNbOfMpdus(), Print(), Serialize(), and SetRemainingNbOfMpdus().
The documentation for this class was generated from the following files:
src/wifi/model/ampdu-tag.h
src/wifi/model/ampdu-tag.cc