ns-3: IpAddressHelperTestCasev6 Class Reference
IpAddressHelperTestCasev6 Class Reference
Internet » internet module tests | Test suites
IPv6 AddressHelper Test.
Public Member Functions
IpAddressHelperTestCasev6 ()
virtual ~IpAddressHelperTestCasev6 ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
virtual void DoTeardown (void)
Implementation to do any local setup required for this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
IPv6 AddressHelper Test.
Definition at line 37 of file ipv6-address-helper-test-suite.cc.
Constructor & Destructor Documentation
IpAddressHelperTestCasev6()
IpAddressHelperTestCasev6::IpAddressHelperTestCasev6 ()
Definition at line 48 of file ipv6-address-helper-test-suite.cc.
~IpAddressHelperTestCasev6()
IpAddressHelperTestCasev6::~IpAddressHelperTestCasev6 () virtual
Definition at line 53 of file ipv6-address-helper-test-suite.cc.
Member Function Documentation
DoRun()
void IpAddressHelperTestCasev6::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 58 of file ipv6-address-helper-test-suite.cc.
References ns3::NetDeviceContainer::Add(), ns3::Ipv6AddressHelper::Assign(), ns3::Ipv6InterfaceAddress::GetAddress(), ns3::Ipv6InterfaceContainer::GetAddress(), ns3::InternetStackHelper::Install(), sample-rng-plot::n, ns3::Ipv6AddressHelper::NewAddress(), ns3::Ipv6AddressHelper::NewNetwork(), NS_TEST_ASSERT_MSG_EQ, ns3::SimpleNetDevice::SetAddress(), ns3::Ipv6AddressHelper::SetBase(), and ns3::InternetStackHelper::SetIpv4StackInstall().
DoTeardown()
void IpAddressHelperTestCasev6::DoTeardown (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test teardown
Reimplemented from ns3::TestCase.
Definition at line 154 of file ipv6-address-helper-test-suite.cc.
References ns3::Config::Reset().
The documentation for this class was generated from the following file:
src/internet/test/ipv6-address-helper-test-suite.cc