ns-3: ns3::RrcAsn1Header Class Reference
ns3::RrcAsn1Header Class Reference abstract
LTE Models
This class extends Asn1Header functions, adding serialization/deserialization of some Information elements defined in 3GPP TS 36.331.
#include "lte-rrc-header.h"
Public Member Functions
RrcAsn1Header ()
int GetMessageType ()
Get message type.
Public Member Functions inherited from ns3::Asn1Header
Asn1Header ()
virtual ~Asn1Header ()
uint32_t GetSerializedSize (void) const
void Serialize (Buffer::Iterator bIterator) const
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Protected Member Functions
int BandwidthToEnum (uint16_t bandwidth) const
Convert from bandwidth (in RBs) to ENUMERATED value.
uint32_t Deserialize (Buffer::Iterator bIterator)=0
Buffer::Iterator DeserializeCellIdentification (LteRrcSap::CellIdentification *ci, Buffer::Iterator bIterator)
Deserialize cell identification function.
Buffer::Iterator DeserializeDrbToAddModList (std::list< LteRrcSap::DrbToAddMod > *drbToAddModLis, Buffer::Iterator bIterator)
Deserialize DRB to add mod list function.
Buffer::Iterator DeserializeLogicalChannelConfig (LteRrcSap::LogicalChannelConfig *logicalChannelConfig, Buffer::Iterator bIterator)
Deserialize logical channel config function.
Buffer::Iterator DeserializeMeasConfig (LteRrcSap::MeasConfig *measConfig, Buffer::Iterator bIterator)
Deserialize measure config function.
Buffer::Iterator DeserializeMeasResults (LteRrcSap::MeasResults *measResults, Buffer::Iterator bIterator)
Deserialize measure results function.
Buffer::Iterator DeserializeNonCriticalExtensionConfig (LteRrcSap::NonCriticalExtensionConfiguration *nonCriticalExtension, Buffer::Iterator bIterator)
Deserialize non critical extension config function.
Buffer::Iterator DeserializePhysicalConfigDedicated (LteRrcSap::PhysicalConfigDedicated *physicalConfigDedicated, Buffer::Iterator bIterator)
Deserialize physical config dedicated function.
Buffer::Iterator DeserializePhysicalConfigDedicatedSCell (LteRrcSap::PhysicalConfigDedicatedSCell *pcdsc, Buffer::Iterator bIterator)
Deserialize physical config dedicated SCell function.
Buffer::Iterator DeserializePlmnIdentity (uint32_t *plmnId, Buffer::Iterator bIterator)
Deserialize PLMN identity function.
Buffer::Iterator DeserializeQoffsetRange (int8_t *qOffsetRange, Buffer::Iterator bIterator)
Deserialize Qoffset range function.
Buffer::Iterator DeserializeRachConfigCommon (LteRrcSap::RachConfigCommon *rachConfigCommon, Buffer::Iterator bIterator)
Deserialize RACH config common function.
Buffer::Iterator DeserializeRadioResourceConfigCommon (LteRrcSap::RadioResourceConfigCommon *radioResourceConfigCommon, Buffer::Iterator bIterator)
Deserialize radio resource config common function.
Buffer::Iterator DeserializeRadioResourceConfigCommonSCell (LteRrcSap::RadioResourceConfigCommonSCell *rrccsc, Buffer::Iterator bIterator)
Deserialize radio resource config common SCell function.
Buffer::Iterator DeserializeRadioResourceConfigCommonSib (LteRrcSap::RadioResourceConfigCommonSib *radioResourceConfigCommonSib, Buffer::Iterator bIterator)
Deserialize radio resource config common SIB function.
Buffer::Iterator DeserializeRadioResourceConfigDedicated (LteRrcSap::RadioResourceConfigDedicated *radioResourceConfigDedicated, Buffer::Iterator bIterator)
Deserialize radio resource config dedicated function.
Buffer::Iterator DeserializeRadioResourceConfigDedicatedSCell (LteRrcSap::RadioResourceConfigDedicatedSCell *rrcdsc, Buffer::Iterator bIterator)
Deserialize radio resource config dedicated SCell function.
Buffer::Iterator DeserializeSrbToAddModList (std::list< LteRrcSap::SrbToAddMod > *srbToAddModList, Buffer::Iterator bIterator)
Deserialize SRB to add mod list function.
Buffer::Iterator DeserializeSystemInformationBlockType1 (LteRrcSap::SystemInformationBlockType1 *systemInformationBlockType1, Buffer::Iterator bIterator)
Deserialize system information block type 1 function.
Buffer::Iterator DeserializeSystemInformationBlockType2 (LteRrcSap::SystemInformationBlockType2 *systemInformationBlockType2, Buffer::Iterator bIterator)
Deserialize system information block type 2 function.
Buffer::Iterator DeserializeThresholdEutra (LteRrcSap::ThresholdEutra *thresholdEutra, Buffer::Iterator bIterator)
Deserialize threshold eutra function.
uint16_t EnumToBandwidth (int n) const
Convert from ENUMERATED value to bandwidth (in RBs)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual void PreSerialize (void) const =0
This function serializes class attributes to m_serializationResult local Buffer.
void Print (std::ostream &os) const
This function prints the object, for debugging purposes.
void Print (std::ostream &os, LteRrcSap::RadioResourceConfigDedicated radioResourceConfigDedicated) const
This function prints RadioResourceConfigDedicated IE, for debugging purposes.
void SerializeDrbToAddModList (std::list< LteRrcSap::DrbToAddMod > drbToAddModList) const
Serialize DRB to add mod list function.
void SerializeLogicalChannelConfig (LteRrcSap::LogicalChannelConfig logicalChannelConfig) const
Serialize logicala channel config function.
void SerializeMeasConfig (LteRrcSap::MeasConfig measConfig) const
Serialize measure config function.
void SerializeMeasResults (LteRrcSap::MeasResults measResults) const
Serialize measure results function.
void SerializeNonCriticalExtensionConfiguration (LteRrcSap::NonCriticalExtensionConfiguration nonCriticalExtensionConfiguration) const
Serialize non critical extension config function.
void SerializePhysicalConfigDedicated (LteRrcSap::PhysicalConfigDedicated physicalConfigDedicated) const
Serialize physical config dedicated function.
void SerializePhysicalConfigDedicatedSCell (LteRrcSap::PhysicalConfigDedicatedSCell pcdsc) const
Serialize physical config dedicated function.
void SerializePlmnIdentity (uint32_t plmnId) const
Serialize PLMN identity function.
void SerializeQoffsetRange (int8_t qOffsetRange) const
Serialize Q offset range function.
void SerializeRachConfigCommon (LteRrcSap::RachConfigCommon rachConfigCommon) const
Serialize RACH config common function.
void SerializeRadioResourceConfigCommon (LteRrcSap::RadioResourceConfigCommon radioResourceConfigCommon) const
Serialize system information block type 2 function.
void SerializeRadioResourceConfigCommonSCell (LteRrcSap::RadioResourceConfigCommonSCell rrccsc) const
Serialize radio resource config common SCell function.
void SerializeRadioResourceConfigCommonSib (LteRrcSap::RadioResourceConfigCommonSib radioResourceConfigCommonSib) const
Serialize radio resource config common SIB function.
void SerializeRadioResourceConfigDedicated (LteRrcSap::RadioResourceConfigDedicated radioResourceConfigDedicated) const
Serialize radio resource config function.
void SerializeRadioResourceDedicatedSCell (LteRrcSap::RadioResourceConfigDedicatedSCell rrcdsc) const
Serialize radio resource dedicated SCell function.
void SerializeSrbToAddModList (std::list< LteRrcSap::SrbToAddMod > srbToAddModList) const
Serialize SRB to add mod list function.
void SerializeSystemInformationBlockType1 (LteRrcSap::SystemInformationBlockType1 systemInformationBlockType1) const
Serialize system information block type 1 function.
void SerializeSystemInformationBlockType2 (LteRrcSap::SystemInformationBlockType2 systemInformationBlockType2) const
Serialize system information block type 2 function.
void SerializeThresholdEutra (LteRrcSap::ThresholdEutra thresholdEutra) const
Serialize threshold eutra function.
Protected Member Functions inherited from ns3::Asn1Header
Buffer::Iterator DeserializeBitset (std::bitset< 8 > *data, Buffer::Iterator bIterator)
Deserialize a bitset.
template<int N>
Buffer::Iterator DeserializeBitset (std::bitset< N > *data, Buffer::Iterator bIterator)
Deserialize a bitset.
Buffer::Iterator DeserializeBitstring (std::bitset< 1 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 10 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 16 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 2 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 27 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 28 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 32 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 8 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
template<int N>
Buffer::Iterator DeserializeBitstring (std::bitset< N > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBoolean (bool *value, Buffer::Iterator bIterator)
Deserialize a boolean.
Buffer::Iterator DeserializeChoice (int numOptions, bool isExtensionMarkerPresent, int *selectedOption, Buffer::Iterator bIterator)
Deserialize a Choice (set of options)
Buffer::Iterator DeserializeEnum (int numElems, int *selectedElem, Buffer::Iterator bIterator)
Deserialize an Enum.
Buffer::Iterator DeserializeInteger (int *n, int nmin, int nmax, Buffer::Iterator bIterator)
Deserialize an integer.
Buffer::Iterator DeserializeNull (Buffer::Iterator bIterator)
Deserialize nothing (null op)
Buffer::Iterator DeserializeSequence (std::bitset< 0 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 1 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 10 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 11 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 2 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 3 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 4 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 5 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 6 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 7 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 9 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
template<int N>
Buffer::Iterator DeserializeSequence (std::bitset< N > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequenceOf (int *numElems, int nMax, int nMin, Buffer::Iterator bIterator)
Deserialize a Sequence.
void FinalizeSerialization () const
Finalizes an in progress serialization.
template<int N>
void SerializeBitset (std::bitset< N > data) const
Serialize a bitset.
void SerializeBitstring (std::bitset< 1 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 10 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 16 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 2 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 27 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 28 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 32 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 8 > bitstring) const
Serialize a bitstring.
template<int N>
void SerializeBitstring (std::bitset< N > bitstring) const
Serialize a bitstring.
void SerializeBoolean (bool value) const
Serialize a bool.
void SerializeChoice (int numOptions, int selectedOption, bool isExtensionMarkerPresent) const
Serialize a Choice (set of options)
void SerializeEnum (int numElems, int selectedElem) const
Serialize an Enum.
void SerializeInteger (int n, int nmin, int nmax) const
Serialize an Integer.
void SerializeNull () const
Serialize nothing (null op)
void SerializeSequence (std::bitset< 0 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 1 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 10 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 11 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 2 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 3 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 4 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 5 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 6 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 7 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 9 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
template<int N>
void SerializeSequence (std::bitset< N > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequenceOf (int numElems, int nMax, int nMin) const
Serialize a Sequence.
void WriteOctet (uint8_t octet) const
Function to write in m_serializationResult, after resizing its size.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Static Protected Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Protected Attributes
int m_messageType
Stores RRC message type, according to 3GPP TS 36.331.
Protected Attributes inherited from ns3::Asn1Header
bool m_isDataSerialized
true if data is serialized
uint8_t m_numSerializationPendingBits
number of pending bits
uint8_t m_serializationPendingBits
pending bits
Buffer m_serializationResult
serialization result
Additional Inherited Members
Static Public Member Functions inherited from ns3::Asn1Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class extends Asn1Header functions, adding serialization/deserialization of some Information elements defined in 3GPP TS 36.331.
Definition at line 45 of file lte-rrc-header.h.
Constructor & Destructor Documentation
RrcAsn1Header()
ns3::RrcAsn1Header::RrcAsn1Header ()
Definition at line 50 of file lte-rrc-header.cc.
Member Function Documentation
BandwidthToEnum()
int ns3::RrcAsn1Header::BandwidthToEnum (uint16_t bandwidth) const protected
Convert from bandwidth (in RBs) to ENUMERATED value.
Parameters
bandwidth Bandwidth in RBs: 6, 15, 25, 50, 75, 100
Returns
ENUMERATED value: 0, 1, 2, 3, 4, 5
Definition at line 77 of file lte-rrc-header.cc.
References sample-rng-plot::n, and NS_FATAL_ERROR.
Referenced by ns3::RrcConnectionReconfigurationHeader::PreSerialize(), ns3::HandoverPreparationInfoHeader::PreSerialize(), SerializeMeasConfig(), and SerializeSystemInformationBlockType2().
Deserialize()
uint32_t ns3::RrcAsn1Header::Deserialize (Buffer::Iterator start) protected pure virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Asn1Header.
Implemented in ns3::MeasurementReportHeader, ns3::RrcConnectionRejectHeader, ns3::RrcConnectionReleaseHeader, ns3::RrcConnectionReestablishmentRejectHeader, ns3::RrcConnectionReestablishmentCompleteHeader, ns3::RrcConnectionReestablishmentHeader, ns3::RrcConnectionReestablishmentRequestHeader, ns3::HandoverPreparationInfoHeader, ns3::RrcConnectionReconfigurationHeader, ns3::RrcConnectionReconfigurationCompleteHeader, ns3::RrcConnectionSetupCompleteHeader, ns3::RrcConnectionSetupHeader, ns3::RrcConnectionRequestHeader, ns3::RrcDlCcchMessage, ns3::RrcUlCcchMessage, ns3::RrcDlDcchMessage, and ns3::RrcUlDcchMessage.
DeserializeCellIdentification()
Buffer::Iterator ns3::RrcAsn1Header::DeserializeCellIdentification (LteRrcSap::CellIdentification * ci, Buffer::Iterator bIterator) protected
Deserialize cell identification function.
Parameters
ci LteRrcSap::CellIdentification *
bIterator buffer iterator
Returns
buffer iterator
Definition at line 2648 of file lte-rrc-header.cc.
References ns3::Asn1Header::DeserializeInteger(), ns3::Asn1Header::DeserializeSequence(), ns3::LteRrcSap::CellIdentification::dlCarrierFreq, MAX_EARFCN, NS_ASSERT, NS_LOG_FUNCTION, and ns3::LteRrcSap::CellIdentification::physCellId.
Referenced by DeserializeNonCriticalExtensionConfig().
DeserializeDrbToAddModList()
Buffer::Iterator ns3::RrcAsn1Header::DeserializeDrbToAddModList (std::list< LteRrcSap::DrbToAddMod > * drbToAddModLis, Buffer::Iterator bIterator) protected
Deserialize DRB to add mod list function.
Parameters
drbToAddModLis std::list<LteRrcSap::DrbToAddMod> *
bIterator buffer iterator
Returns
buffer iterator
Definition at line 2237 of file lte-rrc-header.cc.
References ns3::LteRrcSap::RlcConfig::AM, ns3::LteRrcSap::RlcConfig::choice, ns3::Asn1Header::DeserializeChoice(), ns3::Asn1Header::DeserializeEnum(), ns3::Asn1Header::DeserializeInteger(), DeserializeLogicalChannelConfig(), ns3::Asn1Header::DeserializeSequence(), ns3::Asn1Header::DeserializeSequenceOf(), ns3::LteRrcSap::DrbToAddMod::drbIdentity, ns3::LteRrcSap::DrbToAddMod::epsBearerIdentity, ns3::LteRrcSap::DrbToAddMod::logicalChannelConfig, ns3::LteRrcSap::DrbToAddMod::logicalChannelIdentity, MAX_DRB, sample-rng-plot::n, ns3::LteRrcSap::DrbToAddMod::rlcConfig, ns3::LteRrcSap::RlcConfig::UM_BI_DIRECTIONAL, ns3::LteRrcSap::RlcConfig::UM_UNI_DIRECTIONAL_DL, and ns3::LteRrcSap::RlcConfig::UM_UNI_DIRECTIONAL_UL.
Referenced by DeserializeRadioResourceConfigDedicated().
DeserializeLogicalChannelConfig()
Buffer::Iterator ns3::RrcAsn1Header::DeserializeLogicalChannelConfig (LteRrcSap::LogicalChannelConfig * logicalChannelConfig, Buffer::Iterator bIterator) protected
Deserialize logical channel config function.
Parameters
logicalChannelConfig LteRrcSap::LogicalChannelConfig *
bIterator buffer iterator
Returns
buffer iterator
Definition at line 2344 of file lte-rrc-header.cc.
References ns3::LteRrcSap::LogicalChannelConfig::bucketSizeDurationMs, ns3::Asn1Header::DeserializeEnum(), ns3::Asn1Header::DeserializeInteger(), ns3::Asn1Header::DeserializeSequence(), ns3::LteRrcSap::LogicalChannelConfig::logicalChannelGroup, sample-rng-plot::n, ns3::LteRrcSap::LogicalChannelConfig::prioritizedBitRateKbps, and ns3::LteRrcSap::LogicalChannelConfig::priority.
Referenced by DeserializeDrbToAddModList(), and DeserializeSrbToAddModList().
DeserializeMeasConfig()
Buffer::Iterator ns3::RrcAsn1Header::DeserializeMeasConfig (LteRrcSap::MeasConfig * measConfig, Buffer::Iterator bIterator) protected
Deserialize measure config function.
Parameters
measConfig LteRrcSap::MeasConfig *
bIterator buffer iterator
Returns
buffer iterator
Definition at line 3747 of file lte-rrc-header.cc.
References ns3::LteRrcSap::ReportConfigEutra::a3Offset, ns3::LteRrcSap::MeasObjectEutra::allowedMeasBandwidth, ns3::LteRrcSap::MeasObjectEutra::blackCellsToAddModList, ns3::LteRrcSap::MeasObjectEutra::blackCellsToRemoveList, ns3::LteRrcSap::ReportConfigEutra::BOTH, ns3::LteRrcSap::MeasObjectEutra::carrierFreq, ns3::LteRrcSap::MeasObjectEutra::cellForWhichToReportCGI, ns3::LteRrcSap::CellsToAddMod::cellIndex, ns3::LteRrcSap::BlackCellsToAddMod::cellIndex, ns3::LteRrcSap::CellsToAddMod::cellIndividualOffset, ns3::LteRrcSap::MeasObjectEutra::cellsToAddModList, ns3::LteRrcSap::MeasObjectEutra::cellsToRemoveList, ns3::Asn1Header::DeserializeBitstring(), ns3::Asn1Header::DeserializeBoolean(), ns3::Asn1Header::DeserializeChoice(), ns3::Asn1Header::DeserializeEnum(), ns3::Asn1Header::DeserializeInteger(), ns3::Asn1Header::DeserializeNull(), DeserializeQoffsetRange(), ns3::Asn1Header::DeserializeSequence(), ns3::Asn1Header::DeserializeSequenceOf(), DeserializeThresholdEutra(), EnumToBandwidth(), ns3::LteRrcSap::ReportConfigEutra::EVENT, ns3::LteRrcSap::ReportConfigEutra::EVENT_A1, ns3::LteRrcSap::ReportConfigEutra::EVENT_A2, ns3::LteRrcSap::ReportConfigEutra::EVENT_A3, ns3::LteRrcSap::ReportConfigEutra::EVENT_A4, ns3::LteRrcSap::ReportConfigEutra::EVENT_A5, ns3::LteRrcSap::ReportConfigEutra::eventId, ns3::LteRrcSap::QuantityConfig::filterCoefficientRSRP, ns3::LteRrcSap::QuantityConfig::filterCoefficientRSRQ, ns3::LteRrcSap::MeasGapConfig::gapOffsetChoice, ns3::LteRrcSap::MeasGapConfig::gapOffsetValue, ns3::LteRrcSap::MeasGapConfig::GP0, ns3::LteRrcSap::MeasGapConfig::GP1, ns3::LteRrcSap::MeasObjectEutra::haveCellForWhichToReportCGI, ns3::LteRrcSap::MeasConfig::haveMeasGapConfig, ns3::LteRrcSap::MeasConfig::haveQuantityConfig, ns3::LteRrcSap::PhysCellIdRange::haveRange, ns3::LteRrcSap::MeasConfig::haveSmeasure, ns3::LteRrcSap::MeasConfig::haveSpeedStatePars, ns3::LteRrcSap::ReportConfigEutra::hysteresis, MAX_CELL_MEAS, MAX_CELL_REPORT, MAX_EARFCN, MAX_MEAS_ID, MAX_OBJECT_ID, MAX_REPORT_CONFIG_ID, ns3::LteRrcSap::ReportConfigEutra::maxReportCells, ns3::LteRrcSap::MeasConfig::measGapConfig, ns3::LteRrcSap::MeasIdToAddMod::measId, ns3::LteRrcSap::MeasConfig::measIdToAddModList, ns3::LteRrcSap::MeasConfig::measIdToRemoveList, ns3::LteRrcSap::MeasObjectToAddMod::measObjectEutra, ns3::LteRrcSap::MeasObjectToAddMod::measObjectId, ns3::LteRrcSap::MeasIdToAddMod::measObjectId, ns3::LteRrcSap::MeasConfig::measObjectToAddModList, ns3::LteRrcSap::MeasConfig::measObjectToRemoveList, ns3::LteRrcSap::ReportConfigEutra::MIN1, ns3::LteRrcSap::ReportConfigEutra::MIN12, ns3::LteRrcSap::ReportConfigEutra::MIN30, ns3::LteRrcSap::ReportConfigEutra::MIN6, ns3::LteRrcSap::ReportConfigEutra::MIN60, ns3::LteRrcSap::SpeedStatePars::mobilityStateParameters, ns3::LteRrcSap::ReportConfigEutra::MS1024, ns3::LteRrcSap::ReportConfigEutra::MS10240, ns3::LteRrcSap::ReportConfigEutra::MS120, ns3::LteRrcSap::ReportConfigEutra::MS2048, ns3::LteRrcSap::ReportConfigEutra::MS240, ns3::LteRrcSap::ReportConfigEutra::MS480, ns3::LteRrcSap::ReportConfigEutra::MS5120, ns3::LteRrcSap::ReportConfigEutra::MS640, sample-rng-plot::n, ns3::LteRrcSap::MobilityStateParameters::nCellChangeHigh, ns3::LteRrcSap::MobilityStateParameters::nCellChangeMedium, ns3::LteRrcSap::MeasObjectEutra::neighCellConfig, ns3::LteRrcSap::MeasObjectEutra::offsetFreq, ns3::LteRrcSap::ReportConfigEutra::PERIODICAL, ns3::LteRrcSap::CellsToAddMod::physCellId, ns3::LteRrcSap::BlackCellsToAddMod::physCellIdRange, ns3::LteRrcSap::MeasObjectEutra::presenceAntennaPort1, ns3::LteRrcSap::ReportConfigEutra::purpose, ns3::LteRrcSap::MeasConfig::quantityConfig, ns3::LteRrcSap::PhysCellIdRange::range, ns3::LteRrcSap::ReportConfigEutra::REPORT_CGI, ns3::LteRrcSap::ReportConfigEutra::REPORT_STRONGEST_CELLS, ns3::LteRrcSap::ReportConfigEutra::reportAmount, ns3::LteRrcSap::ReportConfigToAddMod::reportConfigEutra, ns3::LteRrcSap::ReportConfigToAddMod::reportConfigId, ns3::LteRrcSap::MeasIdToAddMod::reportConfigId, ns3::LteRrcSap::MeasConfig::reportConfigToAddModList, ns3::LteRrcSap::MeasConfig::reportConfigToRemoveList, ns3::LteRrcSap::ReportConfigEutra::reportInterval, ns3::LteRrcSap::ReportConfigEutra::reportOnLeave, ns3::LteRrcSap::ReportConfigEutra::reportQuantity, ns3::LteRrcSap::MeasGapConfig::RESET, ns3::LteRrcSap::SpeedStatePars::RESET, ns3::LteRrcSap::ReportConfigEutra::RSRP, ns3::LteRrcSap::ReportConfigEutra::RSRQ, ns3::LteRrcSap::ReportConfigEutra::SAME_AS_TRIGGER_QUANTITY, ns3::LteRrcSap::MeasGapConfig::SETUP, ns3::LteRrcSap::SpeedStatePars::SETUP, ns3::LteRrcSap::SpeedStateScaleFactors::sfHigh, ns3::LteRrcSap::SpeedStateScaleFactors::sfMedium, ns3::LteRrcSap::MeasConfig::sMeasure, ns3::LteRrcSap::ReportConfigEutra::SPARE1, ns3::LteRrcSap::ReportConfigEutra::SPARE2, ns3::LteRrcSap::ReportConfigEutra::SPARE3, ns3::LteRrcSap::MeasConfig::speedStatePars, ns3::LteRrcSap::PhysCellIdRange::start, ns3::LteRrcSap::MobilityStateParameters::tEvaluation, ns3::LteRrcSap::ReportConfigEutra::threshold1, ns3::LteRrcSap::ReportConfigEutra::threshold2, ns3::LteRrcSap::MobilityStateParameters::tHystNormal, ns3::LteRrcSap::ReportConfigEutra::timeToTrigger, ns3::LteRrcSap::SpeedStatePars::timeToTriggerSf, ns3::LteRrcSap::ReportConfigEutra::triggerQuantity, ns3::LteRrcSap::ReportConfigEutra::triggerType, ns3::LteRrcSap::MeasGapConfig::type, and ns3::LteRrcSap::SpeedStatePars::type.
Referenced by ns3::RrcConnectionReconfigurationHeader::Deserialize(), and ns3::HandoverPreparationInfoHeader::Deserialize().
DeserializeMeasResults()
Buffer::Iterator ns3::RrcAsn1Header::DeserializeMeasResults (LteRrcSap::MeasResults * measResults, Buffer::Iterator bIterator) protected
Deserialize measure results function.
Parameters
measResults LteRrcSap::MeasResults *
bIterator buffer iterator
Returns
buffer iterator
Definition at line 3539 of file lte-rrc-header.cc.
References ns3::LteRrcSap::CgiInfo::cellIdentity, ns3::LteRrcSap::MeasResultEutra::cgiInfo, ns3::Asn1Header::DeserializeBitstring(), ns3::Asn1Header::DeserializeChoice(), ns3::Asn1Header::DeserializeInteger(), DeserializePlmnIdentity(), ns3::Asn1Header::DeserializeSequence(), ns3::Asn1Header::DeserializeSequenceOf(), ns3::LteRrcSap::MeasResultEutra::haveCgiInfo, ns3::LteRrcSap::MeasResults::haveMeasResultNeighCells, ns3::LteRrcSap::MeasResultServFreqList::haveMeasurementResultsNeighCell, ns3::LteRrcSap::MeasResultServFreqList::haveMeasurementResultsServingSCells, ns3::LteRrcSap::MeasResultEutra::haveRsrpResult, ns3::LteRrcSap::MeasResultScell::haveRsrpResult, ns3::LteRrcSap::MeasResultEutra::haveRsrqResult, ns3::LteRrcSap::MeasResultScell::haveRsrqResult, ns3::LteRrcSap::MeasResults::haveScellsMeas, MAX_CELL_REPORT, MAX_MEAS_ID, MAX_SCELL_REPORT, ns3::LteRrcSap::MeasResults::measId, ns3::LteRrcSap::MeasResults::measResultListEutra, ns3::LteRrcSap::MeasResultServFreqList::measResultScell, ns3::LteRrcSap::MeasResults::measScellResultList, sample-rng-plot::n, ns3::LteRrcSap::MeasResultEutra::physCellId, ns3::LteRrcSap::CgiInfo::plmnIdentity, ns3::LteRrcSap::CgiInfo::plmnIdentityList, ns3::LteRrcSap::MeasResultEutra::rsrpResult, ns3::LteRrcSap::MeasResultScell::rsrpResult, ns3::LteRrcSap::MeasResults::rsrpResult, ns3::LteRrcSap::MeasResultEutra::rsrqResult, ns3::LteRrcSap::MeasResultScell::rsrqResult, ns3::LteRrcSap::MeasResults::rsrqResult, ns3::LteRrcSap::MeasResultScell::servFreqId, and ns3::LteRrcSap::CgiInfo::trackingAreaCode.
Referenced by ns3::MeasurementReportHeader::Deserialize().
DeserializeNonCriticalExtensionConfig()
Buffer::Iterator ns3::RrcAsn1Header::DeserializeNonCriticalExtensionConfig (LteRrcSap::NonCriticalExtensionConfiguration * nonCriticalExtension, Buffer::Iterator bIterator) protected
Deserialize non critical extension config function.
Parameters
nonCriticalExtension LteRrcSap::NonCriticalExtensionConfiguration *
bIterator buffer iterator
Returns
buffer iterator
Definition at line 2590 of file lte-rrc-header.cc.
References ns3::LteRrcSap::SCellToAddMod::cellIdentification, DeserializeCellIdentification(), ns3::Asn1Header::DeserializeInteger(), DeserializeRadioResourceConfigCommonSCell(), DeserializeRadioResourceConfigDedicatedSCell(), ns3::Asn1Header::DeserializeSequence(), ns3::Asn1Header::DeserializeSequenceOf(), ns3::LteRrcSap::SCellToAddMod::haveRadioResourceConfigDedicatedSCell, MAX_OBJECT_ID, sample-rng-plot::n, NS_ASSERT, NS_LOG_FUNCTION, ns3::LteRrcSap::SCellToAddMod::radioResourceConfigCommonSCell, ns3::LteRrcSap::SCellToAddMod::radioResourceConfigDedicateSCell, ns3::LteRrcSap::SCellToAddMod::sCellIndex, and ns3::LteRrcSap::NonCriticalExtensionConfiguration::sCellsToAddModList.
Referenced by ns3::RrcConnectionReconfigurationHeader::Deserialize().
DeserializePhysicalConfigDedicated()
Buffer::Iterator ns3::RrcAsn1Header::DeserializePhysicalConfigDedicated (LteRrcSap::PhysicalConfigDedicated * physicalConfigDedicated, Buffer::Iterator bIterator) protected
Deserialize physical config dedicated function.
Parameters
physicalConfigDedicated LteRrcSap::PhysicalConfigDedicated *
bIterator buffer iterator
Returns
buffer iterator
Definition at line 2436 of file lte-rrc-header.cc.
References ns3::LteRrcSap::PhysicalConfigDedicated::antennaInfo, ns3::Asn1Header::DeserializeBoolean(), ns3::Asn1Header::DeserializeChoice(), ns3::Asn1Header::DeserializeEnum(), ns3::Asn1Header::DeserializeInteger(), ns3::Asn1Header::DeserializeNull(), ns3::Asn1Header::DeserializeSequence(), aloha::duration, ns3::LteRrcSap::PhysicalConfigDedicated::haveAntennaInfoDedicated, ns3::LteRrcSap::PhysicalConfigDedicated::havePdschConfigDedicated, ns3::LteRrcSap::PhysicalConfigDedicated::haveSoundingRsUlConfigDedicated, ns3::LteRrcSap::PdschConfigDedicated::pa, ns3::LteRrcSap::PhysicalConfigDedicated::pdschConfigDedicated, ns3::LteRrcSap::SoundingRsUlConfigDedicated::RESET, ns3::LteRrcSap::SoundingRsUlConfigDedicated::SETUP, ns3::LteRrcSap::PhysicalConfigDedicated::soundingRsUlConfigDedicated, ns3::LteRrcSap::SoundingRsUlConfigDedicated::srsBandwidth, ns3::LteRrcSap::SoundingRsUlConfigDedicated::srsConfigIndex, ns3::LteRrcSap::AntennaInfoDedicated::transmissionMode, and ns3::LteRrcSap::SoundingRsUlConfigDedicated::type.
Referenced by DeserializeRadioResourceConfigDedicated().
DeserializePhysicalConfigDedicatedSCell()
Buffer::Iterator ns3::RrcAsn1Header::DeserializePhysicalConfigDedicatedSCell (LteRrcSap::PhysicalConfigDedicatedSCell * pcdsc, Buffer::Iterator bIterator) protected
Deserialize physical config dedicated SCell function.
Parameters
pcdsc LteRrcSap::PhysicalConfigDedicatedSCell *
bIterator buffer iterator
Returns
buffer iterator
Definition at line 2732 of file lte-rrc-header.cc.
References ns3::LteRrcSap::PhysicalConfigDedicatedSCell::antennaInfo, ns3::LteRrcSap::PhysicalConfigDedicatedSCell::antennaInfoUl, ns3::Asn1Header::DeserializeBoolean(), ns3::Asn1Header::DeserializeChoice(), ns3::Asn1Header::DeserializeEnum(), ns3::Asn1Header::DeserializeInteger(), ns3::Asn1Header::DeserializeNull(), ns3::Asn1Header::DeserializeSequence(), aloha::duration, ns3::LteRrcSap::PhysicalConfigDedicatedSCell::haveAntennaInfoDedicated, ns3::LteRrcSap::PhysicalConfigDedicatedSCell::haveAntennaInfoUlDedicated, ns3::LteRrcSap::PhysicalConfigDedicatedSCell::haveNonUlConfiguration, ns3::LteRrcSap::PhysicalConfigDedicatedSCell::havePdschConfigDedicated, ns3::LteRrcSap::PhysicalConfigDedicatedSCell::haveSoundingRsUlConfigDedicated, ns3::LteRrcSap::PhysicalConfigDedicatedSCell::haveUlConfiguration, NS_ASSERT, NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::LteRrcSap::PdschConfigDedicated::pa, ns3::LteRrcSap::PhysicalConfigDedicatedSCell::pdschConfigDedicated, ns3::LteRrcSap::SoundingRsUlConfigDedicated::RESET, ns3::LteRrcSap::SoundingRsUlConfigDedicated::SETUP, ns3::LteRrcSap::PhysicalConfigDedicatedSCell::soundingRsUlConfigDedicated, ns3::LteRrcSap::SoundingRsUlConfigDedicated::srsBandwidth, ns3::LteRrcSap::SoundingRsUlConfigDedicated::srsConfigIndex, ns3::LteRrcSap::AntennaInfoDedicated::transmissionMode, and ns3::LteRrcSap::SoundingRsUlConfigDedicated::type.
Referenced by DeserializeRadioResourceConfigDedicatedSCell().
DeserializePlmnIdentity()
Buffer::Iterator ns3::RrcAsn1Header::DeserializePlmnIdentity (uint32_t * plmnId, Buffer::Iterator bIterator) protected
Deserialize PLMN identity function.
Parameters
plmnId the PLMN ID
bIterator buffer iterator
Returns
buffer iterator
Definition at line 3716 of file lte-rrc-header.cc.
References ns3::Asn1Header::DeserializeEnum(), ns3::Asn1Header::DeserializeInteger(), ns3::Asn1Header::DeserializeSequence(), ns3::Asn1Header::DeserializeSequenceOf(), and sample-rng-plot::n.
Referenced by DeserializeMeasResults(), and DeserializeSystemInformationBlockType1().
DeserializeQoffsetRange()
Buffer::Iterator ns3::RrcAsn1Header::DeserializeQoffsetRange (int8_t * qOffsetRange, Buffer::Iterator bIterator) protected
Deserialize Qoffset range function.
Parameters
qOffsetRange Qoffset range
bIterator buffer iterator
Returns
buffer iterator
Definition at line 2027 of file lte-rrc-header.cc.
References ns3::Asn1Header::DeserializeEnum(), and sample-rng-plot::n.
Referenced by DeserializeMeasConfig().
DeserializeRachConfigCommon()
Buffer::Iterator ns3::RrcAsn1Header::DeserializeRachConfigCommon (LteRrcSap::RachConfigCommon * rachConfigCommon, Buffer::Iterator bIterator) protected
Deserialize RACH config common function.
Parameters
rachConfigCommon LteRrcSap::RachConfigCommon *
bIterator buffer iterator
Returns
buffer iterator
Definition at line 3252 of file lte-rrc-header.cc.
References ns3::LteRrcSap::TxFailParam::connEstFailCount, ns3::Asn1Header::DeserializeEnum(), ns3::Asn1Header::DeserializeInteger(), ns3::Asn1Header::DeserializeSequence(), sample-rng-plot::n, ns3::LteRrcSap::PreambleInfo::numberOfRaPreambles, ns3::LteRrcSap::RachConfigCommon::preambleInfo, ns3::LteRrcSap::RaSupervisionInfo::preambleTransMax, ns3::LteRrcSap::RaSupervisionInfo::raResponseWindowSize, ns3::LteRrcSap::RachConfigCommon::raSupervisionInfo, and ns3::LteRrcSap::RachConfigCommon::txFailParam.
Referenced by DeserializeRadioResourceConfigCommon(), and DeserializeRadioResourceConfigCommonSib().
DeserializeRadioResourceConfigCommon()
Buffer::Iterator ns3::RrcAsn1Header::DeserializeRadioResourceConfigCommon (LteRrcSap::RadioResourceConfigCommon * radioResourceConfigCommon, Buffer::Iterator bIterator) protected
Deserialize radio resource config common function.
Parameters
radioResourceConfigCommon LteRrcSap::RadioResourceConfigCommon *
bIterator buffer iterator
Returns
buffer iterator
Definition at line 3135 of file lte-rrc-header.cc.
References ns3::Asn1Header::DeserializeBoolean(), ns3::Asn1Header::DeserializeEnum(), ns3::Asn1Header::DeserializeInteger(), DeserializeRachConfigCommon(), ns3::Asn1Header::DeserializeSequence(), sample-rng-plot::n, and ns3::LteRrcSap::RadioResourceConfigCommon::rachConfigCommon.
Referenced by ns3::RrcConnectionReconfigurationHeader::Deserialize().
DeserializeRadioResourceConfigCommonSCell()
Buffer::Iterator ns3::RrcAsn1Header::DeserializeRadioResourceConfigCommonSCell (LteRrcSap::RadioResourceConfigCommonSCell * rrccsc, Buffer::Iterator bIterator) protected
Deserialize radio resource config common SCell function.
Parameters
rrccsc LteRrcSap::RadioResourceConfigCommonSCell *
bIterator buffer iterator
Returns
buffer iterator
Definition at line 2666 of file lte-rrc-header.cc.
References ns3::LteRrcSap::UlPowerControlCommonSCell::alpha, ns3::LteRrcSap::NonUlConfiguration::antennaInfoCommon, ns3::LteRrcSap::AntennaInfoCommon::antennaPortsCount, ns3::Asn1Header::DeserializeInteger(), ns3::Asn1Header::DeserializeSequence(), ns3::LteRrcSap::NonUlConfiguration::dlBandwidth, ns3::LteRrcSap::RadioResourceConfigCommonSCell::haveNonUlConfiguration, ns3::LteRrcSap::RadioResourceConfigCommonSCell::haveUlConfiguration, ns3::LteRrcSap::PrachConfigSCell::index, MAX_EARFCN, sample-rng-plot::n, ns3::LteRrcSap::RadioResourceConfigCommonSCell::nonUlConfiguration, NS_LOG_FUNCTION, ns3::LteRrcSap::PdschConfigCommon::pb, ns3::LteRrcSap::NonUlConfiguration::pdschConfigCommon, ns3::LteRrcSap::UlConfiguration::prachConfigSCell, ns3::LteRrcSap::PdschConfigCommon::referenceSignalPower, ns3::LteRrcSap::FreqInfo::ulBandwidth, ns3::LteRrcSap::FreqInfo::ulCarrierFreq, ns3::LteRrcSap::RadioResourceConfigCommonSCell::ulConfiguration, ns3::LteRrcSap::UlConfiguration::ulFreqInfo, and ns3::LteRrcSap::UlConfiguration::ulPowerControlCommonSCell.
Referenced by DeserializeNonCriticalExtensionConfig().
DeserializeRadioResourceConfigCommonSib()
Buffer::Iterator ns3::RrcAsn1Header::DeserializeRadioResourceConfigCommonSib (LteRrcSap::RadioResourceConfigCommonSib * radioResourceConfigCommonSib, Buffer::Iterator bIterator) protected
Deserialize radio resource config common SIB function.
Parameters
radioResourceConfigCommonSib LteRrcSap::RadioResourceConfigCommonSib *
bIterator buffer iterator
Returns
buffer iterator
Definition at line 3430 of file lte-rrc-header.cc.
References ns3::Asn1Header::DeserializeBoolean(), ns3::Asn1Header::DeserializeChoice(), ns3::Asn1Header::DeserializeEnum(), ns3::Asn1Header::DeserializeInteger(), ns3::Asn1Header::DeserializeNull(), DeserializeRachConfigCommon(), ns3::Asn1Header::DeserializeSequence(), sample-rng-plot::n, and ns3::LteRrcSap::RadioResourceConfigCommonSib::rachConfigCommon.
Referenced by DeserializeSystemInformationBlockType2().
DeserializeRadioResourceConfigDedicated()
Buffer::Iterator ns3::RrcAsn1Header::DeserializeRadioResourceConfigDedicated (LteRrcSap::RadioResourceConfigDedicated * radioResourceConfigDedicated, Buffer::Iterator bIterator) protected
Deserialize radio resource config dedicated function.
Parameters
radioResourceConfigDedicated LteRrcSap::RadioResourceConfigDedicated *
bIterator buffer iterator
Returns
buffer iterator
Definition at line 2131 of file lte-rrc-header.cc.
References DeserializeDrbToAddModList(), ns3::Asn1Header::DeserializeInteger(), DeserializePhysicalConfigDedicated(), ns3::Asn1Header::DeserializeSequence(), ns3::Asn1Header::DeserializeSequenceOf(), DeserializeSrbToAddModList(), ns3::LteRrcSap::RadioResourceConfigDedicated::drbToAddModList, ns3::LteRrcSap::RadioResourceConfigDedicated::drbToReleaseList, ns3::LteRrcSap::RadioResourceConfigDedicated::havePhysicalConfigDedicated, MAX_DRB, sample-rng-plot::n, ns3::LteRrcSap::RadioResourceConfigDedicated::physicalConfigDedicated, and ns3::LteRrcSap::RadioResourceConfigDedicated::srbToAddModList.
Referenced by ns3::RrcConnectionSetupHeader::Deserialize(), ns3::RrcConnectionReconfigurationHeader::Deserialize(), ns3::HandoverPreparationInfoHeader::Deserialize(), and ns3::RrcConnectionReestablishmentHeader::Deserialize().
DeserializeRadioResourceConfigDedicatedSCell()
Buffer::Iterator ns3::RrcAsn1Header::DeserializeRadioResourceConfigDedicatedSCell (LteRrcSap::RadioResourceConfigDedicatedSCell * rrcdsc, Buffer::Iterator bIterator) protected
Deserialize radio resource config dedicated SCell function.
Parameters
rrcdsc LteRrcSap::RadioResourceConfigDedicatedSCell *
bIterator buffer iterator
Returns
buffer iterator
Definition at line 2721 of file lte-rrc-header.cc.
References DeserializePhysicalConfigDedicatedSCell(), ns3::Asn1Header::DeserializeSequence(), NS_LOG_FUNCTION, and ns3::LteRrcSap::RadioResourceConfigDedicatedSCell::physicalConfigDedicatedSCell.
Referenced by DeserializeNonCriticalExtensionConfig().
DeserializeSrbToAddModList()
Buffer::Iterator ns3::RrcAsn1Header::DeserializeSrbToAddModList (std::list< LteRrcSap::SrbToAddMod > * srbToAddModList, Buffer::Iterator bIterator) protected
Deserialize SRB to add mod list function.
Parameters
srbToAddModList std::list<LteRrcSap::SrbToAddMod> *
bIterator buffer iterator
Returns
buffer iterator
Definition at line 2185 of file lte-rrc-header.cc.
References ns3::Asn1Header::DeserializeChoice(), ns3::Asn1Header::DeserializeInteger(), DeserializeLogicalChannelConfig(), ns3::Asn1Header::DeserializeNull(), ns3::Asn1Header::DeserializeSequence(), ns3::Asn1Header::DeserializeSequenceOf(), ns3::LteRrcSap::SrbToAddMod::logicalChannelConfig, sample-rng-plot::n, and ns3::LteRrcSap::SrbToAddMod::srbIdentity.
Referenced by DeserializeRadioResourceConfigDedicated().
DeserializeSystemInformationBlockType1()
Buffer::Iterator ns3::RrcAsn1Header::DeserializeSystemInformationBlockType1 (LteRrcSap::SystemInformationBlockType1 * systemInformationBlockType1, Buffer::Iterator bIterator) protected
Deserialize system information block type 1 function.
Parameters
systemInformationBlockType1 LteRrcSap::SystemInformationBlockType1 *
bIterator buffer iterator
Returns
buffer iterator
Definition at line 2973 of file lte-rrc-header.cc.
References ns3::LteRrcSap::SystemInformationBlockType1::cellAccessRelatedInfo, ns3::LteRrcSap::CellAccessRelatedInfo::cellIdentity, ns3::LteRrcSap::CellAccessRelatedInfo::csgIdentity, ns3::LteRrcSap::CellAccessRelatedInfo::csgIndication, ns3::Asn1Header::DeserializeBitstring(), ns3::Asn1Header::DeserializeBoolean(), ns3::Asn1Header::DeserializeEnum(), ns3::Asn1Header::DeserializeInteger(), DeserializePlmnIdentity(), ns3::Asn1Header::DeserializeSequence(), ns3::Asn1Header::DeserializeSequenceOf(), MAX_SI_MESSAGE, MAX_SIB, sample-rng-plot::n, ns3::LteRrcSap::PlmnIdentityInfo::plmnIdentity, and ns3::LteRrcSap::CellAccessRelatedInfo::plmnIdentityInfo.
Referenced by ns3::HandoverPreparationInfoHeader::Deserialize().
DeserializeSystemInformationBlockType2()
Buffer::Iterator ns3::RrcAsn1Header::DeserializeSystemInformationBlockType2 (LteRrcSap::SystemInformationBlockType2 * systemInformationBlockType2, Buffer::Iterator bIterator) protected
Deserialize system information block type 2 function.
Parameters
systemInformationBlockType2 LteRrcSap::SystemInformationBlockType2 *
bIterator buffer iterator
Returns
buffer iterator
Definition at line 3077 of file lte-rrc-header.cc.
References ns3::Asn1Header::DeserializeEnum(), ns3::Asn1Header::DeserializeInteger(), DeserializeRadioResourceConfigCommonSib(), ns3::Asn1Header::DeserializeSequence(), EnumToBandwidth(), ns3::LteRrcSap::SystemInformationBlockType2::freqInfo, MAX_EARFCN, sample-rng-plot::n, ns3::LteRrcSap::SystemInformationBlockType2::radioResourceConfigCommon, ns3::LteRrcSap::FreqInfo::ulBandwidth, and ns3::LteRrcSap::FreqInfo::ulCarrierFreq.
Referenced by ns3::HandoverPreparationInfoHeader::Deserialize().
DeserializeThresholdEutra()
Buffer::Iterator ns3::RrcAsn1Header::DeserializeThresholdEutra (LteRrcSap::ThresholdEutra * thresholdEutra, Buffer::Iterator bIterator) protected
Deserialize threshold eutra function.
Parameters
thresholdEutra LteRrcSap::ThresholdEutra *
bIterator buffer iterator
Returns
buffer iterator
Definition at line 2004 of file lte-rrc-header.cc.
References ns3::LteRrcSap::ThresholdEutra::choice, ns3::Asn1Header::DeserializeChoice(), ns3::Asn1Header::DeserializeInteger(), ns3::LteRrcSap::ThresholdEutra::range, ns3::LteRrcSap::ThresholdEutra::THRESHOLD_RSRP, and ns3::LteRrcSap::ThresholdEutra::THRESHOLD_RSRQ.
Referenced by DeserializeMeasConfig().
EnumToBandwidth()
uint16_t ns3::RrcAsn1Header::EnumToBandwidth (int n) const protected
Convert from ENUMERATED value to bandwidth (in RBs)
Parameters
n ENUMERATED value: 0, 1, 2, 3, 4, 5
Returns
bandwidth Bandwidth in RBs: 6, 15, 25, 50, 75, 100
Definition at line 95 of file lte-rrc-header.cc.
References sample-rng-plot::n, and NS_FATAL_ERROR.
Referenced by ns3::RrcConnectionReconfigurationHeader::Deserialize(), ns3::HandoverPreparationInfoHeader::Deserialize(), DeserializeMeasConfig(), and DeserializeSystemInformationBlockType2().
GetInstanceTypeId()
TypeId ns3::RrcAsn1Header::GetInstanceTypeId (void) const protected virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Reimplemented from ns3::Asn1Header.
Definition at line 65 of file lte-rrc-header.cc.
References GetTypeId().
GetMessageType()
int ns3::RrcAsn1Header::GetMessageType ()
Get message type.
Returns
the message type
Definition at line 71 of file lte-rrc-header.cc.
References m_messageType.
Referenced by ns3::LteUeRrcProtocolReal::DoReceivePdcpPdu(), ns3::LteEnbRrcProtocolReal::DoReceivePdcpPdu(), ns3::LteUeRrcProtocolReal::DoReceivePdcpSdu(), and ns3::LteEnbRrcProtocolReal::DoReceivePdcpSdu().
GetTypeId()
TypeId ns3::RrcAsn1Header::GetTypeId (void) static protected
Get the type ID.
Returns
the object TypeId
Definition at line 55 of file lte-rrc-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
PreSerialize()
virtual void ns3::RrcAsn1Header::PreSerialize (void) const protected pure virtual
This function serializes class attributes to m_serializationResult local Buffer.
As ASN1 encoding produces a bitstream that does not have a fixed length, this function is needed to store the result, so its length can be retrieved with Header::GetSerializedSize() function. This method is pure virtual in this class (needs to be implemented in child classes) as the meaningful information elements are in the subclasses.
Implements ns3::Asn1Header.
Implemented in ns3::MeasurementReportHeader, ns3::RrcConnectionRejectHeader, ns3::RrcConnectionReleaseHeader, ns3::RrcConnectionReestablishmentRejectHeader, ns3::RrcConnectionReestablishmentCompleteHeader, ns3::RrcConnectionReestablishmentHeader, ns3::RrcConnectionReestablishmentRequestHeader, ns3::HandoverPreparationInfoHeader, ns3::RrcConnectionReconfigurationHeader, ns3::RrcConnectionReconfigurationCompleteHeader, ns3::RrcConnectionSetupCompleteHeader, ns3::RrcConnectionSetupHeader, ns3::RrcConnectionRequestHeader, ns3::RrcDlCcchMessage, ns3::RrcUlCcchMessage, ns3::RrcDlDcchMessage, and ns3::RrcUlDcchMessage.
Print() [1/2]
void ns3::RrcAsn1Header::Print (std::ostream & os) const protected virtual
This function prints the object, for debugging purposes.
Parameters
os The output stream to use (i.e. std::cout)
Implements ns3::Asn1Header.
Reimplemented in ns3::MeasurementReportHeader, ns3::RrcConnectionRejectHeader, ns3::RrcConnectionReleaseHeader, ns3::RrcConnectionReestablishmentRejectHeader, ns3::RrcConnectionReestablishmentCompleteHeader, ns3::RrcConnectionReestablishmentHeader, ns3::RrcConnectionReestablishmentRequestHeader, ns3::HandoverPreparationInfoHeader, ns3::RrcConnectionReconfigurationHeader, ns3::RrcConnectionReconfigurationCompleteHeader, ns3::RrcConnectionSetupCompleteHeader, ns3::RrcConnectionSetupHeader, ns3::RrcConnectionRequestHeader, ns3::RrcDlCcchMessage, ns3::RrcUlCcchMessage, ns3::RrcDlDcchMessage, and ns3::RrcUlDcchMessage.
Definition at line 2583 of file lte-rrc-header.cc.
References NS_FATAL_ERROR, and NS_LOG_FUNCTION.
Referenced by ns3::RrcConnectionSetupHeader::Print(), ns3::RrcConnectionReconfigurationHeader::Print(), ns3::HandoverPreparationInfoHeader::Print(), and ns3::RrcConnectionReestablishmentHeader::Print().
Print() [2/2]
void ns3::RrcAsn1Header::Print (std::ostream & os, LteRrcSap::RadioResourceConfigDedicated radioResourceConfigDedicated) const protected
This function prints RadioResourceConfigDedicated IE, for debugging purposes.
Parameters
os The output stream to use (i.e. std::cout)
radioResourceConfigDedicated The information element to be printed
Definition at line 2910 of file lte-rrc-header.cc.
References ns3::LteRrcSap::PhysicalConfigDedicated::antennaInfo, ns3::LteRrcSap::RadioResourceConfigDedicated::drbToAddModList, ns3::LteRrcSap::RadioResourceConfigDedicated::drbToReleaseList, ns3::LteRrcSap::PhysicalConfigDedicated::haveAntennaInfoDedicated, ns3::LteRrcSap::RadioResourceConfigDedicated::havePhysicalConfigDedicated, ns3::LteRrcSap::PhysicalConfigDedicated::haveSoundingRsUlConfigDedicated, ns3::LteRrcSap::RadioResourceConfigDedicated::physicalConfigDedicated, ns3::LteRrcSap::PhysicalConfigDedicated::soundingRsUlConfigDedicated, ns3::LteRrcSap::RadioResourceConfigDedicated::srbToAddModList, ns3::LteRrcSap::SoundingRsUlConfigDedicated::srsBandwidth, ns3::LteRrcSap::SoundingRsUlConfigDedicated::srsConfigIndex, ns3::LteRrcSap::AntennaInfoDedicated::transmissionMode, and ns3::LteRrcSap::SoundingRsUlConfigDedicated::type.
SerializeDrbToAddModList()
void ns3::RrcAsn1Header::SerializeDrbToAddModList (std::list< LteRrcSap::DrbToAddMod > drbToAddModList) const protected
Serialize DRB to add mod list function.
Parameters
drbToAddModList std::list<LteRrcSap::SrbToAddMod>
Definition at line 113 of file lte-rrc-header.cc.
References ns3::LteRrcSap::RlcConfig::AM, MAX_DRB, ns3::Asn1Header::SerializeChoice(), ns3::Asn1Header::SerializeEnum(), ns3::Asn1Header::SerializeInteger(), SerializeLogicalChannelConfig(), ns3::Asn1Header::SerializeSequence(), ns3::Asn1Header::SerializeSequenceOf(), ns3::LteRrcSap::RlcConfig::UM_BI_DIRECTIONAL, ns3::LteRrcSap::RlcConfig::UM_UNI_DIRECTIONAL_DL, and ns3::LteRrcSap::RlcConfig::UM_UNI_DIRECTIONAL_UL.
Referenced by SerializeRadioResourceConfigDedicated().
SerializeLogicalChannelConfig()
void ns3::RrcAsn1Header::SerializeLogicalChannelConfig (LteRrcSap::LogicalChannelConfig logicalChannelConfig) const protected
Serialize logicala channel config function.
Parameters
logicalChannelConfig LteRrcSap::LogicalChannelConfig
Definition at line 230 of file lte-rrc-header.cc.
References ns3::LteRrcSap::LogicalChannelConfig::bucketSizeDurationMs, ns3::LteRrcSap::LogicalChannelConfig::logicalChannelGroup, ns3::LteRrcSap::LogicalChannelConfig::prioritizedBitRateKbps, ns3::LteRrcSap::LogicalChannelConfig::priority, ns3::Asn1Header::SerializeEnum(), ns3::Asn1Header::SerializeInteger(), and ns3::Asn1Header::SerializeSequence().
Referenced by SerializeDrbToAddModList(), and SerializeSrbToAddModList().
SerializeMeasConfig()
void ns3::RrcAsn1Header::SerializeMeasConfig (LteRrcSap::MeasConfig measConfig) const protected
Serialize measure config function.
Parameters
measConfig LteRrcSap::MeasConfig
Definition at line 1071 of file lte-rrc-header.cc.
References BandwidthToEnum(), ns3::LteRrcSap::ReportConfigEutra::EVENT, ns3::LteRrcSap::ReportConfigEutra::EVENT_A1, ns3::LteRrcSap::ReportConfigEutra::EVENT_A2, ns3::LteRrcSap::ReportConfigEutra::EVENT_A3, ns3::LteRrcSap::ReportConfigEutra::EVENT_A4, ns3::LteRrcSap::ReportConfigEutra::EVENT_A5, ns3::LteRrcSap::QuantityConfig::filterCoefficientRSRP, ns3::LteRrcSap::QuantityConfig::filterCoefficientRSRQ, ns3::LteRrcSap::MeasGapConfig::gapOffsetChoice, ns3::LteRrcSap::MeasGapConfig::gapOffsetValue, ns3::LteRrcSap::MeasGapConfig::GP0, ns3::LteRrcSap::MeasGapConfig::GP1, ns3::LteRrcSap::MeasConfig::haveMeasGapConfig, ns3::LteRrcSap::MeasConfig::haveQuantityConfig, ns3::LteRrcSap::MeasConfig::haveSmeasure, ns3::LteRrcSap::MeasConfig::haveSpeedStatePars, MAX_CELL_MEAS, MAX_CELL_REPORT, MAX_EARFCN, MAX_MEAS_ID, MAX_OBJECT_ID, MAX_REPORT_CONFIG_ID, ns3::LteRrcSap::MeasConfig::measGapConfig, ns3::LteRrcSap::MeasConfig::measIdToAddModList, ns3::LteRrcSap::MeasConfig::measIdToRemoveList, ns3::LteRrcSap::MeasConfig::measObjectToAddModList, ns3::LteRrcSap::MeasConfig::measObjectToRemoveList, ns3::LteRrcSap::ReportConfigEutra::MIN1, ns3::LteRrcSap::ReportConfigEutra::MIN12, ns3::LteRrcSap::ReportConfigEutra::MIN30, ns3::LteRrcSap::ReportConfigEutra::MIN6, ns3::LteRrcSap::ReportConfigEutra::MIN60, ns3::LteRrcSap::SpeedStatePars::mobilityStateParameters, ns3::LteRrcSap::ReportConfigEutra::MS1024, ns3::LteRrcSap::ReportConfigEutra::MS10240, ns3::LteRrcSap::ReportConfigEutra::MS120, ns3::LteRrcSap::ReportConfigEutra::MS2048, ns3::LteRrcSap::ReportConfigEutra::MS240, ns3::LteRrcSap::ReportConfigEutra::MS480, ns3::LteRrcSap::ReportConfigEutra::MS5120, ns3::LteRrcSap::ReportConfigEutra::MS640, ns3::LteRrcSap::MobilityStateParameters::nCellChangeHigh, ns3::LteRrcSap::MobilityStateParameters::nCellChangeMedium, ns3::LteRrcSap::ReportConfigEutra::PERIODICAL, ns3::LteRrcSap::MeasConfig::quantityConfig, ns3::LteRrcSap::ReportConfigEutra::REPORT_CGI, ns3::LteRrcSap::ReportConfigEutra::REPORT_STRONGEST_CELLS, ns3::LteRrcSap::MeasConfig::reportConfigToAddModList, ns3::LteRrcSap::MeasConfig::reportConfigToRemoveList, ns3::LteRrcSap::MeasGapConfig::RESET, ns3::LteRrcSap::SpeedStatePars::RESET, ns3::LteRrcSap::ReportConfigEutra::RSRP, ns3::LteRrcSap::ReportConfigEutra::SAME_AS_TRIGGER_QUANTITY, ns3::Asn1Header::SerializeBitstring(), ns3::Asn1Header::SerializeBoolean(), ns3::Asn1Header::SerializeChoice(), ns3::Asn1Header::SerializeEnum(), ns3::Asn1Header::SerializeInteger(), ns3::Asn1Header::SerializeNull(), SerializeQoffsetRange(), ns3::Asn1Header::SerializeSequence(), ns3::Asn1Header::SerializeSequenceOf(), SerializeThresholdEutra(), ns3::LteRrcSap::MeasGapConfig::SETUP, ns3::LteRrcSap::SpeedStatePars::SETUP, ns3::LteRrcSap::SpeedStateScaleFactors::sfHigh, ns3::LteRrcSap::SpeedStateScaleFactors::sfMedium, ns3::LteRrcSap::MeasConfig::sMeasure, ns3::LteRrcSap::ReportConfigEutra::SPARE1, ns3::LteRrcSap::ReportConfigEutra::SPARE2, ns3::LteRrcSap::ReportConfigEutra::SPARE3, ns3::LteRrcSap::MeasConfig::speedStatePars, ns3::LteRrcSap::MobilityStateParameters::tEvaluation, ns3::LteRrcSap::MobilityStateParameters::tHystNormal, ns3::LteRrcSap::SpeedStatePars::timeToTriggerSf, ns3::LteRrcSap::MeasGapConfig::type, and ns3::LteRrcSap::SpeedStatePars::type.
Referenced by ns3::RrcConnectionReconfigurationHeader::PreSerialize(), and ns3::HandoverPreparationInfoHeader::PreSerialize().
SerializeMeasResults()
void ns3::RrcAsn1Header::SerializeMeasResults (LteRrcSap::MeasResults measResults) const protected
Serialize measure results function.
Parameters
measResults LteRrcSap::MeasResults
Definition at line 645 of file lte-rrc-header.cc.
References ns3::LteRrcSap::MeasResults::haveMeasResultNeighCells, ns3::LteRrcSap::MeasResultServFreqList::haveMeasurementResultsNeighCell, ns3::LteRrcSap::MeasResultServFreqList::haveMeasurementResultsServingSCells, ns3::LteRrcSap::MeasResults::haveScellsMeas, MAX_CELL_REPORT, MAX_MEAS_ID, MAX_SCELL_REPORT, ns3::LteRrcSap::MeasResults::measId, ns3::LteRrcSap::MeasResults::measResultListEutra, ns3::LteRrcSap::MeasResultServFreqList::measResultScell, ns3::LteRrcSap::MeasResults::measScellResultList, ns3::LteRrcSap::MeasResults::rsrpResult, ns3::LteRrcSap::MeasResults::rsrqResult, ns3::Asn1Header::SerializeBitstring(), ns3::Asn1Header::SerializeChoice(), ns3::Asn1Header::SerializeInteger(), SerializePlmnIdentity(), ns3::Asn1Header::SerializeSequence(), and ns3::Asn1Header::SerializeSequenceOf().
Referenced by ns3::MeasurementReportHeader::PreSerialize().
SerializeNonCriticalExtensionConfiguration()
void ns3::RrcAsn1Header::SerializeNonCriticalExtensionConfiguration (LteRrcSap::NonCriticalExtensionConfiguration nonCriticalExtensionConfiguration) const protected
Serialize non critical extension config function.
Parameters
nonCriticalExtensionConfiguration LteRrcSap::NonCriticalExtensionConfiguration
Definition at line 1728 of file lte-rrc-header.cc.
References MAX_EARFCN, MAX_OBJECT_ID, ns3::LteRrcSap::NonCriticalExtensionConfiguration::sCellsToAddModList, ns3::Asn1Header::SerializeInteger(), SerializeRadioResourceConfigCommonSCell(), SerializeRadioResourceDedicatedSCell(), ns3::Asn1Header::SerializeSequence(), and ns3::Asn1Header::SerializeSequenceOf().
Referenced by ns3::RrcConnectionReconfigurationHeader::PreSerialize().
SerializePhysicalConfigDedicated()
void ns3::RrcAsn1Header::SerializePhysicalConfigDedicated (LteRrcSap::PhysicalConfigDedicated physicalConfigDedicated) const protected
Serialize physical config dedicated function.
Parameters
physicalConfigDedicated LteRrcSap::PhysicalConfigDedicated
Definition at line 305 of file lte-rrc-header.cc.
References ns3::LteRrcSap::PhysicalConfigDedicated::antennaInfo, ns3::LteRrcSap::PhysicalConfigDedicated::haveAntennaInfoDedicated, ns3::LteRrcSap::PhysicalConfigDedicated::havePdschConfigDedicated, ns3::LteRrcSap::PhysicalConfigDedicated::haveSoundingRsUlConfigDedicated, ns3::LteRrcSap::PdschConfigDedicated::pa, ns3::LteRrcSap::PhysicalConfigDedicated::pdschConfigDedicated, ns3::LteRrcSap::SoundingRsUlConfigDedicated::RESET, ns3::Asn1Header::SerializeBoolean(), ns3::Asn1Header::SerializeChoice(), ns3::Asn1Header::SerializeEnum(), ns3::Asn1Header::SerializeInteger(), ns3::Asn1Header::SerializeNull(), ns3::Asn1Header::SerializeSequence(), ns3::LteRrcSap::SoundingRsUlConfigDedicated::SETUP, ns3::LteRrcSap::PhysicalConfigDedicated::soundingRsUlConfigDedicated, ns3::LteRrcSap::SoundingRsUlConfigDedicated::srsBandwidth, ns3::LteRrcSap::SoundingRsUlConfigDedicated::srsConfigIndex, ns3::LteRrcSap::AntennaInfoDedicated::transmissionMode, and ns3::LteRrcSap::SoundingRsUlConfigDedicated::type.
Referenced by SerializeRadioResourceConfigDedicated().
SerializePhysicalConfigDedicatedSCell()
void ns3::RrcAsn1Header::SerializePhysicalConfigDedicatedSCell (LteRrcSap::PhysicalConfigDedicatedSCell pcdsc) const protected
Serialize physical config dedicated function.
Parameters
pcdsc LteRrcSap::PhysicalConfigDedicatedSCell
Definition at line 1868 of file lte-rrc-header.cc.
References ns3::LteRrcSap::PhysicalConfigDedicatedSCell::antennaInfo, ns3::LteRrcSap::PhysicalConfigDedicatedSCell::antennaInfoUl, ns3::LteRrcSap::PhysicalConfigDedicatedSCell::haveAntennaInfoDedicated, ns3::LteRrcSap::PhysicalConfigDedicatedSCell::haveAntennaInfoUlDedicated, ns3::LteRrcSap::PhysicalConfigDedicatedSCell::haveNonUlConfiguration, ns3::LteRrcSap::PhysicalConfigDedicatedSCell::havePdschConfigDedicated, ns3::LteRrcSap::PhysicalConfigDedicatedSCell::haveSoundingRsUlConfigDedicated, ns3::LteRrcSap::PhysicalConfigDedicatedSCell::haveUlConfiguration, ns3::LteRrcSap::PdschConfigDedicated::pa, ns3::LteRrcSap::PhysicalConfigDedicatedSCell::pdschConfigDedicated, ns3::LteRrcSap::SoundingRsUlConfigDedicated::RESET, ns3::Asn1Header::SerializeBoolean(), ns3::Asn1Header::SerializeChoice(), ns3::Asn1Header::SerializeEnum(), ns3::Asn1Header::SerializeInteger(), ns3::Asn1Header::SerializeNull(), ns3::Asn1Header::SerializeSequence(), ns3::LteRrcSap::SoundingRsUlConfigDedicated::SETUP, ns3::LteRrcSap::PhysicalConfigDedicatedSCell::soundingRsUlConfigDedicated, ns3::LteRrcSap::SoundingRsUlConfigDedicated::srsBandwidth, ns3::LteRrcSap::SoundingRsUlConfigDedicated::srsConfigIndex, ns3::LteRrcSap::AntennaInfoDedicated::transmissionMode, and ns3::LteRrcSap::SoundingRsUlConfigDedicated::type.
Referenced by SerializeRadioResourceDedicatedSCell().
SerializePlmnIdentity()
void ns3::RrcAsn1Header::SerializePlmnIdentity (uint32_t plmnId) const protected
Serialize PLMN identity function.
Parameters
plmnId the PLMN ID
Definition at line 768 of file lte-rrc-header.cc.
References sample-rng-plot::n, ns3::Asn1Header::SerializeEnum(), ns3::Asn1Header::SerializeInteger(), ns3::Asn1Header::SerializeSequence(), and ns3::Asn1Header::SerializeSequenceOf().
Referenced by SerializeMeasResults(), and SerializeSystemInformationBlockType1().
SerializeQoffsetRange()
void ns3::RrcAsn1Header::SerializeQoffsetRange (int8_t qOffsetRange) const protected
Serialize Q offset range function.
Parameters
qOffsetRange q offset range
Definition at line 952 of file lte-rrc-header.cc.
References ns3::Asn1Header::SerializeEnum().
Referenced by SerializeMeasConfig().
SerializeRachConfigCommon()
void ns3::RrcAsn1Header::SerializeRachConfigCommon (LteRrcSap::RachConfigCommon rachConfigCommon) const protected
Serialize RACH config common function.
Parameters
rachConfigCommon LteRrcSap::RachConfigCommon
Definition at line 789 of file lte-rrc-header.cc.
References ns3::LteRrcSap::TxFailParam::connEstFailCount, NS_FATAL_ERROR, ns3::LteRrcSap::PreambleInfo::numberOfRaPreambles, ns3::LteRrcSap::RachConfigCommon::preambleInfo, ns3::LteRrcSap::RaSupervisionInfo::preambleTransMax, ns3::LteRrcSap::RaSupervisionInfo::raResponseWindowSize, ns3::LteRrcSap::RachConfigCommon::raSupervisionInfo, ns3::Asn1Header::SerializeEnum(), ns3::Asn1Header::SerializeInteger(), ns3::Asn1Header::SerializeSequence(), and ns3::LteRrcSap::RachConfigCommon::txFailParam.
Referenced by SerializeRadioResourceConfigCommon(), and SerializeRadioResourceConfigCommonSib().
SerializeRadioResourceConfigCommon()
void ns3::RrcAsn1Header::SerializeRadioResourceConfigCommon (LteRrcSap::RadioResourceConfigCommon radioResourceConfigCommon) const protected
Serialize system information block type 2 function.
Parameters
radioResourceConfigCommon LteRrcSap::RadioResourceConfigCommon
Definition at line 508 of file lte-rrc-header.cc.
References ns3::LteRrcSap::RadioResourceConfigCommon::rachConfigCommon, ns3::Asn1Header::SerializeBoolean(), ns3::Asn1Header::SerializeEnum(), ns3::Asn1Header::SerializeInteger(), SerializeRachConfigCommon(), and ns3::Asn1Header::SerializeSequence().
Referenced by ns3::RrcConnectionReconfigurationHeader::PreSerialize().
SerializeRadioResourceConfigCommonSCell()
void ns3::RrcAsn1Header::SerializeRadioResourceConfigCommonSCell (LteRrcSap::RadioResourceConfigCommonSCell rrccsc) const protected
Serialize radio resource config common SCell function.
Parameters
rrccsc LteRrcSap::RadioResourceConfigCommonSCell
Definition at line 1776 of file lte-rrc-header.cc.
References ns3::LteRrcSap::UlPowerControlCommonSCell::alpha, ns3::LteRrcSap::NonUlConfiguration::antennaInfoCommon, ns3::LteRrcSap::AntennaInfoCommon::antennaPortsCount, ns3::LteRrcSap::NonUlConfiguration::dlBandwidth, ns3::LteRrcSap::RadioResourceConfigCommonSCell::haveNonUlConfiguration, ns3::LteRrcSap::RadioResourceConfigCommonSCell::haveUlConfiguration, ns3::LteRrcSap::PrachConfigSCell::index, MAX_EARFCN, ns3::LteRrcSap::RadioResourceConfigCommonSCell::nonUlConfiguration, ns3::LteRrcSap::PdschConfigCommon::pb, ns3::LteRrcSap::NonUlConfiguration::pdschConfigCommon, ns3::LteRrcSap::UlConfiguration::prachConfigSCell, ns3::LteRrcSap::PdschConfigCommon::referenceSignalPower, ns3::Asn1Header::SerializeInteger(), ns3::Asn1Header::SerializeSequence(), ns3::LteRrcSap::FreqInfo::ulBandwidth, ns3::LteRrcSap::FreqInfo::ulCarrierFreq, ns3::LteRrcSap::RadioResourceConfigCommonSCell::ulConfiguration, ns3::LteRrcSap::UlConfiguration::ulFreqInfo, and ns3::LteRrcSap::UlConfiguration::ulPowerControlCommonSCell.
Referenced by SerializeNonCriticalExtensionConfiguration().
SerializeRadioResourceConfigCommonSib()
void ns3::RrcAsn1Header::SerializeRadioResourceConfigCommonSib (LteRrcSap::RadioResourceConfigCommonSib radioResourceConfigCommonSib) const protected
Serialize radio resource config common SIB function.
Parameters
radioResourceConfigCommonSib LteRrcSap::RadioResourceConfigCommonSib
Definition at line 559 of file lte-rrc-header.cc.
References ns3::LteRrcSap::RadioResourceConfigCommonSib::rachConfigCommon, ns3::Asn1Header::SerializeBoolean(), ns3::Asn1Header::SerializeChoice(), ns3::Asn1Header::SerializeEnum(), ns3::Asn1Header::SerializeInteger(), ns3::Asn1Header::SerializeNull(), SerializeRachConfigCommon(), and ns3::Asn1Header::SerializeSequence().
Referenced by SerializeSystemInformationBlockType2().
SerializeRadioResourceConfigDedicated()
void ns3::RrcAsn1Header::SerializeRadioResourceConfigDedicated (LteRrcSap::RadioResourceConfigDedicated radioResourceConfigDedicated) const protected
Serialize radio resource config function.
Parameters
radioResourceConfigDedicated LteRrcSap::RadioResourceConfigDedicated
Definition at line 402 of file lte-rrc-header.cc.
References ns3::LteRrcSap::RadioResourceConfigDedicated::drbToAddModList, ns3::LteRrcSap::RadioResourceConfigDedicated::drbToReleaseList, ns3::LteRrcSap::RadioResourceConfigDedicated::havePhysicalConfigDedicated, MAX_DRB, ns3::LteRrcSap::RadioResourceConfigDedicated::physicalConfigDedicated, SerializeDrbToAddModList(), ns3::Asn1Header::SerializeInteger(), SerializePhysicalConfigDedicated(), ns3::Asn1Header::SerializeSequence(), ns3::Asn1Header::SerializeSequenceOf(), SerializeSrbToAddModList(), and ns3::LteRrcSap::RadioResourceConfigDedicated::srbToAddModList.
Referenced by ns3::RrcConnectionSetupHeader::PreSerialize(), ns3::RrcConnectionReconfigurationHeader::PreSerialize(), ns3::HandoverPreparationInfoHeader::PreSerialize(), and ns3::RrcConnectionReestablishmentHeader::PreSerialize().
SerializeRadioResourceDedicatedSCell()
void ns3::RrcAsn1Header::SerializeRadioResourceDedicatedSCell (LteRrcSap::RadioResourceConfigDedicatedSCell rrcdsc) const protected
Serialize radio resource dedicated SCell function.
Parameters
rrcdsc LteRrcSap::RadioResourceConfigDedicatedSCell
Definition at line 1856 of file lte-rrc-header.cc.
References ns3::LteRrcSap::RadioResourceConfigDedicatedSCell::physicalConfigDedicatedSCell, SerializePhysicalConfigDedicatedSCell(), and ns3::Asn1Header::SerializeSequence().
Referenced by SerializeNonCriticalExtensionConfiguration().
SerializeSrbToAddModList()
void ns3::RrcAsn1Header::SerializeSrbToAddModList (std::list< LteRrcSap::SrbToAddMod > srbToAddModList) const protected
Serialize SRB to add mod list function.
Parameters
srbToAddModList std::list<LteRrcSap::SrbToAddMod>
Definition at line 201 of file lte-rrc-header.cc.
References ns3::Asn1Header::SerializeChoice(), ns3::Asn1Header::SerializeInteger(), SerializeLogicalChannelConfig(), ns3::Asn1Header::SerializeSequence(), and ns3::Asn1Header::SerializeSequenceOf().
Referenced by SerializeRadioResourceConfigDedicated().
SerializeSystemInformationBlockType1()
void ns3::RrcAsn1Header::SerializeSystemInformationBlockType1 (LteRrcSap::SystemInformationBlockType1 systemInformationBlockType1) const protected
Serialize system information block type 1 function.
Parameters
systemInformationBlockType1 LteRrcSap::SystemInformationBlockType1
Definition at line 449 of file lte-rrc-header.cc.
References ns3::LteRrcSap::SystemInformationBlockType1::cellAccessRelatedInfo, ns3::LteRrcSap::CellAccessRelatedInfo::cellIdentity, ns3::LteRrcSap::CellAccessRelatedInfo::csgIdentity, ns3::LteRrcSap::CellAccessRelatedInfo::csgIndication, MAX_SI_MESSAGE, MAX_SIB, ns3::LteRrcSap::PlmnIdentityInfo::plmnIdentity, ns3::LteRrcSap::CellAccessRelatedInfo::plmnIdentityInfo, ns3::Asn1Header::SerializeBitstring(), ns3::Asn1Header::SerializeBoolean(), ns3::Asn1Header::SerializeEnum(), ns3::Asn1Header::SerializeInteger(), SerializePlmnIdentity(), ns3::Asn1Header::SerializeSequence(), and ns3::Asn1Header::SerializeSequenceOf().
Referenced by ns3::HandoverPreparationInfoHeader::PreSerialize().
SerializeSystemInformationBlockType2()
void ns3::RrcAsn1Header::SerializeSystemInformationBlockType2 (LteRrcSap::SystemInformationBlockType2 systemInformationBlockType2) const protected
Serialize system information block type 2 function.
Parameters
systemInformationBlockType2 LteRrcSap::SystemInformationBlockType2
Definition at line 618 of file lte-rrc-header.cc.
References BandwidthToEnum(), ns3::LteRrcSap::SystemInformationBlockType2::freqInfo, MAX_EARFCN, ns3::LteRrcSap::SystemInformationBlockType2::radioResourceConfigCommon, ns3::Asn1Header::SerializeEnum(), ns3::Asn1Header::SerializeInteger(), SerializeRadioResourceConfigCommonSib(), ns3::Asn1Header::SerializeSequence(), ns3::LteRrcSap::FreqInfo::ulBandwidth, and ns3::LteRrcSap::FreqInfo::ulCarrierFreq.
Referenced by ns3::HandoverPreparationInfoHeader::PreSerialize().
SerializeThresholdEutra()
void ns3::RrcAsn1Header::SerializeThresholdEutra (LteRrcSap::ThresholdEutra thresholdEutra) const protected
Serialize threshold eutra function.
Parameters
thresholdEutra LteRrcSap::ThresholdEutra
Definition at line 1055 of file lte-rrc-header.cc.
References ns3::LteRrcSap::ThresholdEutra::choice, ns3::LteRrcSap::ThresholdEutra::range, ns3::Asn1Header::SerializeChoice(), ns3::Asn1Header::SerializeInteger(), ns3::LteRrcSap::ThresholdEutra::THRESHOLD_RSRP, and ns3::LteRrcSap::ThresholdEutra::THRESHOLD_RSRQ.
Referenced by SerializeMeasConfig().
Member Data Documentation
m_messageType
int ns3::RrcAsn1Header::m_messageType protected
Stores RRC message type, according to 3GPP TS 36.331.
Definition at line 376 of file lte-rrc-header.h.
Referenced by ns3::RrcDlCcchMessage::DeserializeDlCcchMessage(), ns3::RrcDlDcchMessage::DeserializeDlDcchMessage(), ns3::RrcUlCcchMessage::DeserializeUlCcchMessage(), ns3::RrcUlDcchMessage::DeserializeUlDcchMessage(), GetMessageType(), ns3::RrcUlDcchMessage::PreSerialize(), ns3::RrcDlDcchMessage::PreSerialize(), ns3::RrcUlCcchMessage::PreSerialize(), ns3::RrcDlCcchMessage::PreSerialize(), ns3::RrcUlDcchMessage::Print(), ns3::RrcDlDcchMessage::Print(), ns3::RrcUlCcchMessage::Print(), and ns3::RrcDlCcchMessage::Print().
The documentation for this class was generated from the following files:
src/lte/model/lte-rrc-header.h
src/lte/model/lte-rrc-header.cc