ns-3: ns3::Ipv6ListRoutingHelper Class Reference
ns3::Ipv6ListRoutingHelper Class Reference
Internet » IPv6 Helper classes
Helper class that adds ns3::Ipv6ListRouting objects.
#include "ipv6-list-routing-helper.h"
Public Member Functions
Ipv6ListRoutingHelper ()
Construct an Ipv6 Ipv6ListRoutingHelper which is used to make life easier for people wanting to configure routing using Ipv6.
Ipv6ListRoutingHelper (const Ipv6ListRoutingHelper &)
Construct an Ipv6ListRoutingHelper from another previously initialized instance (Copy Constructor).
virtual ~Ipv6ListRoutingHelper ()
Destroy an Ipv6 Ipv6ListRoutingHelper.
void Add (const Ipv6RoutingHelper &routing, int16_t priority)
Ipv6ListRoutingHelper * Copy (void) const
virtual Ptr< Ipv6RoutingProtocol > Create (Ptr< Node > node) const
Public Member Functions inherited from ns3::Ipv6RoutingHelper
virtual ~Ipv6RoutingHelper ()
Destroy an Ipv6 Ipv6RoutingHelper.
Private Member Functions
Ipv6ListRoutingHelper & operator= (const Ipv6ListRoutingHelper &o)
Assignment operator declared private and not implemented to disallow assignment and prevent the compiler from happily inserting its own.
Private Attributes
std::list< std::pair< const Ipv6RoutingHelper *, int16_t > > m_list
Container for pairs of Ipv6RoutingHelper pointer / priority.
Additional Inherited Members
Static Public Member Functions inherited from ns3::Ipv6RoutingHelper
template<class T >
static Ptr< T > GetRouting (Ptr< Ipv6RoutingProtocol > protocol)
Request a specified routing protocol <T> from Ipv6RoutingProtocol protocol.
static void PrintNeighborCacheAllAt (Time printTime, Ptr< OutputStreamWrapper > stream)
prints the neighbor cache of all nodes at a particular time.
static void PrintNeighborCacheAllEvery (Time printInterval, Ptr< OutputStreamWrapper > stream)
prints the neighbor cache of all nodes at regular intervals specified by user.
static void PrintNeighborCacheAt (Time printTime, Ptr< Node > node, Ptr< OutputStreamWrapper > stream)
prints the neighbor cache of a node at a particular time.
static void PrintNeighborCacheEvery (Time printInterval, Ptr< Node > node, Ptr< OutputStreamWrapper > stream)
prints the neighbor cache of a node at regular intervals specified by user.
static void PrintRoutingTableAllAt (Time printTime, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of all nodes at a particular time.
static void PrintRoutingTableAllEvery (Time printInterval, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of all nodes at regular intervals specified by user.
static void PrintRoutingTableAt (Time printTime, Ptr< Node > node, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of a node at a particular time.
static void PrintRoutingTableEvery (Time printInterval, Ptr< Node > node, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of a node at regular intervals specified by user.
Detailed Description
Helper class that adds ns3::Ipv6ListRouting objects.
This class is expected to be used in conjunction with ns3::InternetStackHelper::SetRoutingHelper
Definition at line 39 of file ipv6-list-routing-helper.h.
Constructor & Destructor Documentation
Ipv6ListRoutingHelper() [1/2]
ns3::Ipv6ListRoutingHelper::Ipv6ListRoutingHelper ()
Construct an Ipv6 Ipv6ListRoutingHelper which is used to make life easier for people wanting to configure routing using Ipv6.
Definition at line 28 of file ipv6-list-routing-helper.cc.
Referenced by Copy().
~Ipv6ListRoutingHelper()
ns3::Ipv6ListRoutingHelper::~Ipv6ListRoutingHelper () virtual
Destroy an Ipv6 Ipv6ListRoutingHelper.
Definition at line 32 of file ipv6-list-routing-helper.cc.
References list, and m_list.
Ipv6ListRoutingHelper() [2/2]
ns3::Ipv6ListRoutingHelper::Ipv6ListRoutingHelper (const Ipv6ListRoutingHelper & o)
Construct an Ipv6ListRoutingHelper from another previously initialized instance (Copy Constructor).
Definition at line 40 of file ipv6-list-routing-helper.cc.
References m_list.
Member Function Documentation
Add()
void ns3::Ipv6ListRoutingHelper::Add (const Ipv6RoutingHelper & routing, int16_t priority)
Parameters
routing a routing helper
priority the priority of the associated helper
Store in the internal list a reference to the input routing helper and associated priority. These helpers will be used later by the ns3::Ipv6ListRoutingHelper::Create method to create an ns3::Ipv6ListRouting object and add in it routing protocols created with the helpers.
Definition at line 56 of file ipv6-list-routing-helper.cc.
References ns3::Ipv6RoutingHelper::Copy(), and m_list.
Copy()
Ipv6ListRoutingHelper * ns3::Ipv6ListRoutingHelper::Copy (void) const virtual
Returns
pointer to clone of this Ipv6ListRoutingHelper
This method is mainly for internal use by the other helpers; clients are expected to free the dynamic memory allocated by this method
Implements ns3::Ipv6RoutingHelper.
Definition at line 50 of file ipv6-list-routing-helper.cc.
References Ipv6ListRoutingHelper().
Create()
Ptr< Ipv6RoutingProtocol > ns3::Ipv6ListRoutingHelper::Create (Ptr< Node > node) const virtual
Parameters
node the node on which the routing protocol will run
Returns
a newly-created routing protocol
This method will be called by ns3::InternetStackHelper::Install
Implements ns3::Ipv6RoutingHelper.
Definition at line 61 of file ipv6-list-routing-helper.cc.
References list, and m_list.
operator=()
Ipv6ListRoutingHelper& ns3::Ipv6ListRoutingHelper::operator= (const Ipv6ListRoutingHelper & o) private
Assignment operator declared private and not implemented to disallow assignment and prevent the compiler from happily inserting its own.
Parameters
o object to copy from
Returns
a reference to the new object
Member Data Documentation
m_list
std::list<std::pair<const Ipv6RoutingHelper *,int16_t> > ns3::Ipv6ListRoutingHelper::m_list private
Container for pairs of Ipv6RoutingHelper pointer / priority.
Definition at line 97 of file ipv6-list-routing-helper.h.
Referenced by Ipv6ListRoutingHelper(), ~Ipv6ListRoutingHelper(), Add(), and Create().
The documentation for this class was generated from the following files:
src/internet/helper/ipv6-list-routing-helper.h
src/internet/helper/ipv6-list-routing-helper.cc