ns-3: ThreeGppSpectrumPropagationLossModelTest Class Reference
ThreeGppSpectrumPropagationLossModelTest Class Reference
Test case for the ThreeGppSpectrumPropagationLossModelTest class.
Public Member Functions
ThreeGppSpectrumPropagationLossModelTest ()
Constructor.
virtual ~ThreeGppSpectrumPropagationLossModelTest ()
Destructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CheckLongTermUpdate (Ptr< ThreeGppSpectrumPropagationLossModel > lossModel, Ptr< SpectrumValue > txPsd, Ptr< MobilityModel > txMob, Ptr< MobilityModel > rxMob, Ptr< SpectrumValue > rxPsdOld)
Test of the long term component is correctly updated when the channel matrix is recomputed.
void DoBeamforming (Ptr< NetDevice > thisDevice, Ptr< ThreeGppAntennaArrayModel > thisAntenna, Ptr< NetDevice > otherDevice, Ptr< ThreeGppAntennaArrayModel > otherAntenna)
Points the beam of thisDevice towards otherDevice.
virtual void DoRun (void)
Build the test scenario.
Static Private Member Functions
static bool ArePsdEqual (Ptr< SpectrumValue > first, Ptr< SpectrumValue > second)
Checks if two PSDs are equal.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test case for the ThreeGppSpectrumPropagationLossModelTest class.
1) checks if the long term components for the direct and the reverse link are the same 2) checks if the long term component is updated when changing the beamforming vectors 3) checks if the long term is updated when changing the channel matrix
Definition at line 345 of file three-gpp-channel-test-suite.cc.
Constructor & Destructor Documentation
ThreeGppSpectrumPropagationLossModelTest()
ThreeGppSpectrumPropagationLossModelTest::ThreeGppSpectrumPropagationLossModelTest ()
Constructor.
Definition at line 394 of file three-gpp-channel-test-suite.cc.
~ThreeGppSpectrumPropagationLossModelTest()
ThreeGppSpectrumPropagationLossModelTest::~ThreeGppSpectrumPropagationLossModelTest () virtual
Destructor.
Definition at line 399 of file three-gpp-channel-test-suite.cc.
Member Function Documentation
ArePsdEqual()
bool ThreeGppSpectrumPropagationLossModelTest::ArePsdEqual (Ptr< SpectrumValue > first, Ptr< SpectrumValue > second) static private
Checks if two PSDs are equal.
Parameters
first the first PSD
second the second PSD
Returns
true if first and second are equal, false otherwise
Definition at line 445 of file three-gpp-channel-test-suite.cc.
Referenced by CheckLongTermUpdate(), and DoRun().
CheckLongTermUpdate()
void ThreeGppSpectrumPropagationLossModelTest::CheckLongTermUpdate (Ptr< ThreeGppSpectrumPropagationLossModel > lossModel, Ptr< SpectrumValue > txPsd, Ptr< MobilityModel > txMob, Ptr< MobilityModel > rxMob, Ptr< SpectrumValue > rxPsdOld) private
Test of the long term component is correctly updated when the channel matrix is recomputed.
Parameters
lossModel the ThreeGppSpectrumPropagationLossModel object used to compute the rx PSD
txPsd the PSD of the transmitted signal
txMob the mobility model of the tx device
rxMob the mobility model of the rx device
rxPsdOld the previously received PSD
Definition at line 460 of file three-gpp-channel-test-suite.cc.
References ArePsdEqual(), ns3::ThreeGppSpectrumPropagationLossModel::DoCalcRxPowerSpectralDensity(), and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
DoBeamforming()
void ThreeGppSpectrumPropagationLossModelTest::DoBeamforming (Ptr< NetDevice > thisDevice, Ptr< ThreeGppAntennaArrayModel > thisAntenna, Ptr< NetDevice > otherDevice, Ptr< ThreeGppAntennaArrayModel > otherAntenna) private
Points the beam of thisDevice towards otherDevice.
Parameters
thisDevice the device to configure
thisAntenna the antenna object associated to thisDevice
otherDevice the device to communicate with
otherAntenna the antenna object associated to otherDevice
Definition at line 404 of file three-gpp-channel-test-suite.cc.
References ns3::ThreeGppAntennaArrayModel::GetElementLocation(), ns3::NetDevice::GetNode(), ns3::ThreeGppAntennaArrayModel::GetNumberOfElements(), ns3::Object::GetObject(), GetPosition(), ns3::ThreeGppAntennaArrayModel::SetBeamformingVector(), and ns3::Angles::theta.
Referenced by DoRun().
DoRun()
void ThreeGppSpectrumPropagationLossModelTest::DoRun (void) private virtual
Build the test scenario.
Implements ns3::TestCase.
Definition at line 467 of file three-gpp-channel-test-suite.cc.
References ns3::ThreeGppSpectrumPropagationLossModel::AddDevice(), ArePsdEqual(), CheckLongTermUpdate(), ns3::WifiSpectrumValue5MhzFactory::CreateTxPowerSpectralDensity(), DoBeamforming(), ns3::ThreeGppSpectrumPropagationLossModel::DoCalcRxPowerSpectralDensity(), ns3::ThreeGppAntennaArrayModel::GetBeamformingVector(), ns3::MilliSeconds(), first::nodes, NS_TEST_ASSERT_MSG_EQ, ns3::ThreeGppAntennaArrayModel::SetBeamformingVector(), ns3::ThreeGppSpectrumPropagationLossModel::SetChannelModelAttribute(), ns3::Config::SetDefault(), ns3::SimpleNetDevice::SetNode(), and ns3::MobilityModel::SetPosition().
The documentation for this class was generated from the following file:
src/spectrum/test/three-gpp-channel-test-suite.cc