ns-3: ns3::lorawan::LoraNetDevice Class Reference
ns3::lorawan::LoraNetDevice Class Reference
Hold together all LoRa related objects.
#include "lora-net-device.h"
Public Member Functions
LoraNetDevice ()
virtual ~LoraNetDevice ()
virtual void AddLinkChangeCallback (Callback< void > callback)
virtual Address GetAddress (void) const
virtual Address GetBroadcast (void) const
virtual Ptr< Channel > GetChannel (void) const
virtual uint32_t GetIfIndex (void) const
Ptr< LorawanMac > GetMac (void) const
Get the LorawanMac instance that is linked to this NetDevice.
virtual uint16_t GetMtu (void) const
virtual Address GetMulticast (Ipv4Address multicastGroup) const
Make and return a MAC multicast address using the provided multicast group.
virtual Address GetMulticast (Ipv6Address addr) const
Get the MAC multicast address corresponding to the IPv6 address provided.
virtual Ptr< Node > GetNode (void) const
Ptr< LoraPhy > GetPhy (void) const
Get the LoraPhy instance that is linked to this NetDevice.
virtual bool IsBridge (void) const
Return true if the net device is acting as a bridge.
virtual bool IsBroadcast (void) const
virtual bool IsLinkUp (void) const
virtual bool IsMulticast (void) const
virtual bool IsPointToPoint (void) const
Return true if the net device is on a point-to-point link.
virtual bool NeedsArp (void) const
void Receive (Ptr< Packet > packet)
Callback the Mac layer calls whenever a packet arrives and needs to be forwarded up the stack.
void Send (Ptr< Packet > packet)
Send a packet through the LoRaWAN stack.
bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)
This function is implemented to achieve compliance with the NetDevice interface.
virtual bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
virtual void SetAddress (Address address)
Set the address of this interface.
virtual void SetIfIndex (const uint32_t index)
void SetMac (Ptr< LorawanMac > mac)
Set which LorawanMac instance is linked to this device.
virtual bool SetMtu (const uint16_t mtu)
virtual void SetNode (Ptr< Node > node)
void SetPhy (Ptr< LoraPhy > phy)
Set which LoraPhy instance is linked to this device.
virtual void SetPromiscReceiveCallback (PromiscReceiveCallback cb)
virtual void SetReceiveCallback (NetDevice::ReceiveCallback cb)
virtual bool SupportsSendFrom (void) const
Public Member Functions inherited from ns3::NetDevice
virtual ~NetDevice ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::NetDevice
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
void ForwardUp (Ptr< Packet > packet, Mac48Address from, Mac48Address to)
Receive a packet from the lower layer and pass the packet up the stack.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void CompleteConfig (void)
Complete the configuration of this LoRa device by connecting all lower components (PHY, MAC, Channel) together.
Ptr< LoraChannel > DoGetChannel (void) const
Return the LoraChannel this device is connected to.
Private Attributes
bool m_configComplete
Whether the configuration was already completed.
Ptr< LorawanMac > m_mac
The LorawanMac this NetDevice is connected to.
Ptr< Node > m_node
The Node this NetDevice is connected to.
Ptr< LoraPhy > m_phy
The LoraPhy this NetDevice is connected to.
NetDevice::ReceiveCallback m_receiveCallback
Upper layer callback used for notification of new data packet arrivals.
Additional Inherited Members
Public Types inherited from ns3::NetDevice
typedef void(* LinkChangeTracedCallback) (void)
TracedCallback signature for link changed event.
enum PacketType {
PACKET_HOST = 1, NS3_PACKET_HOST = PACKET_HOST, PACKET_BROADCAST, NS3_PACKET_BROADCAST = PACKET_BROADCAST,
PACKET_MULTICAST, NS3_PACKET_MULTICAST = PACKET_MULTICAST, PACKET_OTHERHOST, NS3_PACKET_OTHERHOST = PACKET_OTHERHOST
}
Packet types are used as they are in Linux.
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address &, const Address &, enum PacketType > PromiscReceiveCallback
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address & > ReceiveCallback
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Hold together all LoRa related objects.
This class holds together pointers to LoraChannel, LoraPhy and LorawanMac, exposing methods through which Application instances can send packets. The Application only needs to craft its packets, the NetDevice will take care of calling the LorawanMac's Send method with the appropriate parameters.
Definition at line 44 of file lora-net-device.h.
Constructor & Destructor Documentation
LoraNetDevice()
ns3::lorawan::LoraNetDevice::LoraNetDevice ()
Definition at line 58 of file lora-net-device.cc.
References NS_LOG_FUNCTION_NOARGS.
~LoraNetDevice()
ns3::lorawan::LoraNetDevice::~LoraNetDevice () virtual
Definition at line 67 of file lora-net-device.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
AddLinkChangeCallback()
void ns3::lorawan::LoraNetDevice::AddLinkChangeCallback (Callback< void > callback) virtual
Parameters
callback the callback to invoke
Add a callback invoked whenever the link status changes to UP. This callback is typically used by the IP/ARP layer to flush the ARP cache and by IPv6 stack to flush NDISC cache whenever the link goes up.
Implements ns3::NetDevice.
Definition at line 202 of file lora-net-device.cc.
References NS_LOG_FUNCTION.
CompleteConfig()
void ns3::lorawan::LoraNetDevice::CompleteConfig (void) private
Complete the configuration of this LoRa device by connecting all lower components (PHY, MAC, Channel) together.
Definition at line 97 of file lora-net-device.cc.
References m_configComplete, m_mac, m_node, m_phy, and NS_LOG_FUNCTION_NOARGS.
Referenced by SetNode().
DoGetChannel()
Ptr< LoraChannel > ns3::lorawan::LoraNetDevice::DoGetChannel (void) const private
Return the LoraChannel this device is connected to.
Definition at line 143 of file lora-net-device.cc.
References m_phy, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
ForwardUp()
void ns3::lorawan::LoraNetDevice::ForwardUp (Ptr< Packet > packet, Mac48Address from, Mac48Address to) protected
Receive a packet from the lower layer and pass the packet up the stack.
Parameters
packet The packet we need to forward.
from The from address.
to The to address.
GetAddress()
Address ns3::lorawan::LoraNetDevice::GetAddress (void) const virtual
Returns
the current Address of this interface.
Implements ns3::NetDevice.
Definition at line 170 of file lora-net-device.cc.
References NS_LOG_FUNCTION.
GetBroadcast()
Address ns3::lorawan::LoraNetDevice::GetBroadcast (void) const virtual
Returns
the broadcast address supported by this netdevice.
Calling this method is invalid if IsBroadcast returns not true.
Implements ns3::NetDevice.
Definition at line 216 of file lora-net-device.cc.
References NS_LOG_FUNCTION.
GetChannel()
Ptr< Channel > ns3::lorawan::LoraNetDevice::GetChannel (void) const virtual
Returns
the channel this NetDevice is connected to. The value returned can be zero if the NetDevice is not yet connected to any channel or if the underlying NetDevice has no concept of a channel. i.e., callers must check for zero and be ready to handle it.
Implements ns3::NetDevice.
Definition at line 136 of file lora-net-device.cc.
References m_phy, and NS_LOG_FUNCTION.
GetIfIndex()
uint32_t ns3::lorawan::LoraNetDevice::GetIfIndex (void) const virtual
Returns
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 156 of file lora-net-device.cc.
References NS_LOG_FUNCTION.
GetMac()
Ptr< LorawanMac > ns3::lorawan::LoraNetDevice::GetMac (void) const
Get the LorawanMac instance that is linked to this NetDevice.
Returns
the mac we are currently using.
Definition at line 79 of file lora-net-device.cc.
References m_mac.
Referenced by GetTypeId().
GetMtu()
uint16_t ns3::lorawan::LoraNetDevice::GetMtu (void) const virtual
Returns
the link-level MTU in bytes for this interface.
This value is typically used by the IP layer to perform IP fragmentation when needed.
Implements ns3::NetDevice.
Definition at line 186 of file lora-net-device.cc.
References NS_LOG_FUNCTION.
GetMulticast() [1/2]
Address ns3::lorawan::LoraNetDevice::GetMulticast (Ipv4Address multicastGroup) const virtual
Make and return a MAC multicast address using the provided multicast group.
RFC 1112 says that an Ipv4 host group address is mapped to an Ethernet multicast address by placing the low-order 23-bits of the IP address into the low-order 23 bits of the Ethernet multicast address 01-00-5E-00-00-00 (hex). Similar RFCs exist for Ipv6 and Eui64 mappings. This method performs the multicast address creation function appropriate to the underlying MAC address of the device. This MAC address is encapsulated in an abstract Address to avoid dependencies on the exact MAC address format.
In the case of net devices that do not support multicast, clients are expected to test NetDevice::IsMulticast and avoid attempting to map multicast packets. Subclasses of NetDevice that do support multicasting are expected to override this method and provide an implementation appropriate to the particular device.
Parameters
multicastGroup The IP address for the multicast group destination of the packet.
Returns
The MAC multicast Address used to send packets to the provided multicast group.
Warning
Calling this method is invalid if IsMulticast returns not true.
See also
IsMulticast()
Implements ns3::NetDevice.
Definition at line 232 of file lora-net-device.cc.
References NS_ABORT_MSG.
GetMulticast() [2/2]
Address ns3::lorawan::LoraNetDevice::GetMulticast (Ipv6Address addr) const virtual
Get the MAC multicast address corresponding to the IPv6 address provided.
Parameters
addr IPv6 address
Returns
the MAC multicast address
Warning
Calling this method is invalid if IsMulticast returns not true.
Implements ns3::NetDevice.
Definition at line 240 of file lora-net-device.cc.
References NS_LOG_FUNCTION.
GetNode()
Ptr< Node > ns3::lorawan::LoraNetDevice::GetNode (void) const virtual
Returns
the node base class which contains this network interface.
When a subclass needs to get access to the underlying node base class to print the nodeid for example, it can invoke this method.
Implements ns3::NetDevice.
Definition at line 287 of file lora-net-device.cc.
References m_node, and NS_LOG_FUNCTION.
GetPhy()
Ptr< LoraPhy > ns3::lorawan::LoraNetDevice::GetPhy (void) const
Get the LoraPhy instance that is linked to this NetDevice.
Returns
the phy we are currently using.
Definition at line 91 of file lora-net-device.cc.
References m_phy.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::lorawan::LoraNetDevice::GetTypeId (void) static
Definition at line 35 of file lora-net-device.cc.
References DoGetChannel(), GetMac(), GetPhy(), ns3::MakePointerAccessor(), SetMac(), ns3::TypeId::SetParent(), and SetPhy().
IsBridge()
bool ns3::lorawan::LoraNetDevice::IsBridge (void) const virtual
Return true if the net device is acting as a bridge.
Returns
value of m_isBridge flag
Implements ns3::NetDevice.
Definition at line 248 of file lora-net-device.cc.
References NS_LOG_FUNCTION.
IsBroadcast()
bool ns3::lorawan::LoraNetDevice::IsBroadcast (void) const virtual
Returns
true if this interface supports a broadcast address, false otherwise.
Implements ns3::NetDevice.
Definition at line 208 of file lora-net-device.cc.
References NS_LOG_FUNCTION.
IsLinkUp()
bool ns3::lorawan::LoraNetDevice::IsLinkUp (void) const virtual
Returns
true if link is up; false otherwise
Implements ns3::NetDevice.
Definition at line 194 of file lora-net-device.cc.
References m_phy, and NS_LOG_FUNCTION.
IsMulticast()
bool ns3::lorawan::LoraNetDevice::IsMulticast (void) const virtual
Returns
value of m_isMulticast flag
Implements ns3::NetDevice.
Definition at line 224 of file lora-net-device.cc.
References NS_LOG_FUNCTION.
IsPointToPoint()
bool ns3::lorawan::LoraNetDevice::IsPointToPoint (void) const virtual
Return true if the net device is on a point-to-point link.
Returns
value of m_isPointToPoint flag
Implements ns3::NetDevice.
Definition at line 256 of file lora-net-device.cc.
References NS_LOG_FUNCTION.
NeedsArp()
bool ns3::lorawan::LoraNetDevice::NeedsArp (void) const virtual
Returns
true if ARP is needed, false otherwise.
Called by higher-layers to check if this NetDevice requires ARP to be used.
Implements ns3::NetDevice.
Definition at line 304 of file lora-net-device.cc.
References NS_LOG_FUNCTION.
Receive()
void ns3::lorawan::LoraNetDevice::Receive (Ptr< Packet > packet)
Callback the Mac layer calls whenever a packet arrives and needs to be forwarded up the stack.
Parameters
packet The packet that was received.
Definition at line 122 of file lora-net-device.cc.
References m_receiveCallback, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Send() [1/2]
void ns3::lorawan::LoraNetDevice::Send (Ptr< Packet > packet)
Send a packet through the LoRaWAN stack.
Parameters
packet The packet to send.
Definition at line 112 of file lora-net-device.cc.
References m_mac, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by Send().
Send() [2/2]
bool ns3::lorawan::LoraNetDevice::Send (Ptr< Packet > packet, const Address & dest, uint16_t protocolNumber) virtual
This function is implemented to achieve compliance with the NetDevice interface.
Note that the dest and protocolNumber args are ignored.
Implements ns3::NetDevice.
Definition at line 264 of file lora-net-device.cc.
References NS_LOG_FUNCTION, and Send().
SendFrom()
bool ns3::lorawan::LoraNetDevice::SendFrom (Ptr< Packet > packet, const Address & source, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
source source mac address (so called "MAC spoofing")
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device with the specified source and destination Addresses.
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 277 of file lora-net-device.cc.
References NS_ABORT_MSG.
SetAddress()
void ns3::lorawan::LoraNetDevice::SetAddress (Address address) virtual
Set the address of this interface.
Parameters
address address to set
Implements ns3::NetDevice.
Definition at line 164 of file lora-net-device.cc.
References NS_LOG_FUNCTION.
SetIfIndex()
void ns3::lorawan::LoraNetDevice::SetIfIndex (const uint32_t index) virtual
Parameters
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 150 of file lora-net-device.cc.
References NS_LOG_FUNCTION.
SetMac()
void ns3::lorawan::LoraNetDevice::SetMac (Ptr< LorawanMac > mac)
Set which LorawanMac instance is linked to this device.
Parameters
mac the mac layer to use.
Definition at line 73 of file lora-net-device.cc.
References m_mac, and third::mac.
Referenced by GetTypeId().
SetMtu()
bool ns3::lorawan::LoraNetDevice::SetMtu (const uint16_t mtu) virtual
Parameters
mtu MTU value, in bytes, to set for the device
Returns
whether the MTU value was within legal bounds
Override for default MTU defined on a per-type basis.
Implements ns3::NetDevice.
Definition at line 178 of file lora-net-device.cc.
References NS_ABORT_MSG.
SetNode()
void ns3::lorawan::LoraNetDevice::SetNode (Ptr< Node > node) virtual
Parameters
node the node associated to this netdevice.
This method is called from ns3::Node::AddDevice.
Implements ns3::NetDevice.
Definition at line 295 of file lora-net-device.cc.
References CompleteConfig(), m_node, and NS_LOG_FUNCTION.
SetPhy()
void ns3::lorawan::LoraNetDevice::SetPhy (Ptr< LoraPhy > phy)
Set which LoraPhy instance is linked to this device.
Parameters
phy the phy layer to use.
Definition at line 85 of file lora-net-device.cc.
References m_phy, and third::phy.
Referenced by GetTypeId().
SetPromiscReceiveCallback()
void ns3::lorawan::LoraNetDevice::SetPromiscReceiveCallback (PromiscReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received in promiscuous mode and must be forwarded to the higher layers.
Enables netdevice promiscuous mode and sets the callback that will handle promiscuous mode packets. Note, promiscuous mode packets means all packets, including those packets that can be sensed by the netdevice but which are intended to be received by other hosts.
Implements ns3::NetDevice.
Definition at line 319 of file lora-net-device.cc.
References NS_LOG_FUNCTION_NOARGS.
SetReceiveCallback()
void ns3::lorawan::LoraNetDevice::SetReceiveCallback (NetDevice::ReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received and must be forwarded to the higher layers.
Set the callback to be used to notify higher layers when a packet has been received.
Implements ns3::NetDevice.
Definition at line 312 of file lora-net-device.cc.
References m_receiveCallback, and NS_LOG_FUNCTION_NOARGS.
SupportsSendFrom()
bool ns3::lorawan::LoraNetDevice::SupportsSendFrom (void) const virtual
Returns
true if this interface supports a bridging mode, false otherwise.
Implements ns3::NetDevice.
Definition at line 325 of file lora-net-device.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Data Documentation
m_configComplete
bool ns3::lorawan::LoraNetDevice::m_configComplete private
Whether the configuration was already completed.
Definition at line 156 of file lora-net-device.h.
Referenced by CompleteConfig().
m_mac
Ptr<LorawanMac> ns3::lorawan::LoraNetDevice::m_mac private
The LorawanMac this NetDevice is connected to.
Definition at line 155 of file lora-net-device.h.
Referenced by CompleteConfig(), GetMac(), Send(), and SetMac().
m_node
Ptr<Node> ns3::lorawan::LoraNetDevice::m_node private
The Node this NetDevice is connected to.
Definition at line 153 of file lora-net-device.h.
Referenced by CompleteConfig(), GetNode(), and SetNode().
m_phy
Ptr<LoraPhy> ns3::lorawan::LoraNetDevice::m_phy private
The LoraPhy this NetDevice is connected to.
Definition at line 154 of file lora-net-device.h.
Referenced by CompleteConfig(), DoGetChannel(), GetChannel(), GetPhy(), IsLinkUp(), and SetPhy().
m_receiveCallback
NetDevice::ReceiveCallback ns3::lorawan::LoraNetDevice::m_receiveCallback private
Upper layer callback used for notification of new data packet arrivals.
Definition at line 161 of file lora-net-device.h.
Referenced by Receive(), and SetReceiveCallback().
The documentation for this class was generated from the following files:
src/lorawan/model/lora-net-device.h
src/lorawan/model/lora-net-device.cc