ns-3: ns3::WimaxChannel Class Reference
ns3::WimaxChannel Class Reference abstract
WiMAX Models
#include "wimax-channel.h"
Public Member Functions
WimaxChannel (void)
virtual ~WimaxChannel (void)
virtual int64_t AssignStreams (int64_t stream)=0
Assign a fixed random variable stream number to the random variables used by this model.
void Attach (Ptr< WimaxPhy > phy)
attach the channel to a physical layer of a device
Ptr< NetDevice > GetDevice (std::size_t i) const
std::size_t GetNDevices (void) const
Public Member Functions inherited from ns3::Channel
Channel ()
virtual ~Channel ()
uint32_t GetId (void) const
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Channel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual void DoAttach (Ptr< WimaxPhy > phy)=0
Attach a phy to the channel.
virtual Ptr< NetDevice > DoGetDevice (std::size_t i) const =0
Get device corresponding to index.
virtual std::size_t DoGetNDevices (void) const =0
Get number of devices on the channel.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The channel object to attach Wimax NetDevices
Definition at line 40 of file wimax-channel.h.
Constructor & Destructor Documentation
WimaxChannel()
ns3::WimaxChannel::WimaxChannel (void)
Definition at line 40 of file wimax-channel.cc.
~WimaxChannel()
ns3::WimaxChannel::~WimaxChannel (void) virtual
Definition at line 44 of file wimax-channel.cc.
Member Function Documentation
AssignStreams()
virtual int64_t ns3::WimaxChannel::AssignStreams (int64_t stream) pure virtual
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Implemented in ns3::SimpleOfdmWimaxChannel.
Attach()
void ns3::WimaxChannel::Attach (Ptr< WimaxPhy > phy)
attach the channel to a physical layer of a device
Parameters
phy the physical layer to which the channel will be attached
Definition at line 49 of file wimax-channel.cc.
References DoAttach(), and third::phy.
DoAttach()
virtual void ns3::WimaxChannel::DoAttach (Ptr< WimaxPhy > phy) private pure virtual
Attach a phy to the channel.
Parameters
phy the phy object to attach
Implemented in ns3::SimpleOfdmWimaxChannel.
Referenced by Attach().
DoGetDevice()
virtual Ptr<NetDevice> ns3::WimaxChannel::DoGetDevice (std::size_t i) const private pure virtual
Get device corresponding to index.
Parameters
i the device index
Returns
the device
Implemented in ns3::SimpleOfdmWimaxChannel.
Referenced by GetDevice().
DoGetNDevices()
virtual std::size_t ns3::WimaxChannel::DoGetNDevices (void) const private pure virtual
Get number of devices on the channel.
Returns
the number of devices
Implemented in ns3::SimpleOfdmWimaxChannel.
Referenced by GetNDevices().
GetDevice()
Ptr< NetDevice > ns3::WimaxChannel::GetDevice (std::size_t i) const virtual
Parameters
i the ith device
Returns
the ith attached device
Implements ns3::Channel.
Definition at line 61 of file wimax-channel.cc.
References DoGetDevice().
GetNDevices()
std::size_t ns3::WimaxChannel::GetNDevices (void) const virtual
Returns
the number of attached devices
Implements ns3::Channel.
Definition at line 55 of file wimax-channel.cc.
References DoGetNDevices().
GetTypeId()
TypeId ns3::WimaxChannel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 32 of file wimax-channel.cc.
References ns3::TypeId::SetParent().
The documentation for this class was generated from the following files:
src/wimax/model/wimax-channel.h
src/wimax/model/wimax-channel.cc