ns-3: ns3::FragmentationSubheader Class Reference
ns3::FragmentationSubheader Class Reference
WiMAX Models
#include "wimax-mac-header.h"
Public Member Functions
FragmentationSubheader (void)
~FragmentationSubheader (void)
uint32_t Deserialize (Buffer::Iterator start)
uint8_t GetFc (void) const
Get FC field.
uint8_t GetFsn (void) const
Get FSN field.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
std::string GetName (void) const
Get name field.
uint32_t GetSerializedSize (void) const
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetFc (uint8_t fc)
Set FC field.
void SetFsn (uint8_t fsn)
Set FSN field.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_fc
Fragment Control.
uint8_t m_fsn
Fragment Sequence Number.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class implements the fragmentation sub-header as described by IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems 6.3.2.2.1 Fragmentation subheader, page 39
Definition at line 457 of file wimax-mac-header.h.
Constructor & Destructor Documentation
FragmentationSubheader()
ns3::FragmentationSubheader::FragmentationSubheader (void)
Definition at line 588 of file wimax-mac-header.cc.
~FragmentationSubheader()
ns3::FragmentationSubheader::~FragmentationSubheader (void)
Definition at line 594 of file wimax-mac-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::FragmentationSubheader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 668 of file wimax-mac-header.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_fc, m_fsn, ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetFc()
uint8_t ns3::FragmentationSubheader::GetFc (void) const
Get FC field.
Returns
the FC
Definition at line 611 of file wimax-mac-header.cc.
References m_fc.
Referenced by ns3::BaseStationNetDevice::DoReceive(), ns3::SubscriberStationNetDevice::DoReceive(), and Ns3WimaxFragmentationTestCase::DoRun().
GetFsn()
uint8_t ns3::FragmentationSubheader::GetFsn (void) const
Get FSN field.
Returns
the FSN
Definition at line 617 of file wimax-mac-header.cc.
References m_fsn.
GetInstanceTypeId()
TypeId ns3::FragmentationSubheader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 641 of file wimax-mac-header.cc.
References GetTypeId().
GetName()
std::string ns3::FragmentationSubheader::GetName (void) const
Get name field.
Returns
the name
Definition at line 624 of file wimax-mac-header.cc.
GetSerializedSize()
uint32_t ns3::FragmentationSubheader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 654 of file wimax-mac-header.cc.
Referenced by ns3::WimaxMacQueue::Dequeue().
GetTypeId()
TypeId ns3::FragmentationSubheader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 630 of file wimax-mac-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::FragmentationSubheader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 647 of file wimax-mac-header.cc.
References m_fc, and m_fsn.
Serialize()
void ns3::FragmentationSubheader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 660 of file wimax-mac-header.cc.
References m_fc, m_fsn, visualizer.core::start(), and ns3::Buffer::Iterator::WriteU8().
SetFc()
void ns3::FragmentationSubheader::SetFc (uint8_t fc)
Set FC field.
Parameters
fc the FC
Definition at line 599 of file wimax-mac-header.cc.
References m_fc.
Referenced by ns3::WimaxMacQueue::Dequeue().
SetFsn()
void ns3::FragmentationSubheader::SetFsn (uint8_t fsn)
Set FSN field.
Parameters
fsn the FSN
Definition at line 605 of file wimax-mac-header.cc.
References m_fsn.
Referenced by ns3::WimaxMacQueue::Dequeue().
Member Data Documentation
m_fc
uint8_t ns3::FragmentationSubheader::m_fc private
Fragment Control.
Definition at line 502 of file wimax-mac-header.h.
Referenced by Deserialize(), GetFc(), Print(), Serialize(), and SetFc().
m_fsn
uint8_t ns3::FragmentationSubheader::m_fsn private
Fragment Sequence Number.
Definition at line 503 of file wimax-mac-header.h.
Referenced by Deserialize(), GetFsn(), Print(), Serialize(), and SetFsn().
The documentation for this class was generated from the following files:
src/wimax/model/wimax-mac-header.h
src/wimax/model/wimax-mac-header.cc