ns-3: BenchTag< N > Class Template Reference
BenchTag< N > Class Template Reference
BenchTag class used for benchmarking packet serialization/deserialization.
Public Member Functions
BenchTag ()
virtual void Deserialize (TagBuffer buf)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer buf) const
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static std::string GetName (void)
Get the bench tag name.
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
template<int N>
class BenchTag< N >
BenchTag class used for benchmarking packet serialization/deserialization.
Definition at line 147 of file bench-packets.cc.
Constructor & Destructor Documentation
BenchTag()
template<int N> BenchTag< N >::BenchTag () inline
Definition at line 193 of file bench-packets.cc.
Member Function Documentation
Deserialize()
template<int N> virtual void BenchTag< N >::Deserialize (TagBuffer i) inline virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 184 of file bench-packets.cc.
References ns3::TagBuffer::ReadU8().
GetInstanceTypeId()
template<int N> virtual TypeId BenchTag< N >::GetInstanceTypeId (void) const inline virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 172 of file bench-packets.cc.
References BenchTag< N >::GetTypeId().
GetName()
template<int N> static std::string BenchTag< N >::GetName (void) inline static
Get the bench tag name.
Returns
the name.
Definition at line 154 of file bench-packets.cc.
Referenced by BenchTag< N >::GetTypeId().
GetSerializedSize()
template<int N> virtual uint32_t BenchTag< N >::GetSerializedSize (void) const inline virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 175 of file bench-packets.cc.
GetTypeId()
template<int N> static TypeId BenchTag< N >::GetTypeId (void) inline static
Register this type.
Returns
The TypeId.
Definition at line 163 of file bench-packets.cc.
References BenchTag< N >::GetName(), and ns3::TypeId::SetParent().
Referenced by BenchTag< N >::GetInstanceTypeId().
Print()
template<int N> virtual void BenchTag< N >::Print (std::ostream & os) const inline virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 190 of file bench-packets.cc.
Serialize()
template<int N> virtual void BenchTag< N >::Serialize (TagBuffer i) const inline virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 178 of file bench-packets.cc.
References ns3::TagBuffer::WriteU8().
The documentation for this class was generated from the following file:
utils/bench-packets.cc