ns-3: ns3::EpcTft Class Reference
ns3::EpcTft Class Reference
This class implements the EPS bearer Traffic Flow Template (TFT), which is the set of all packet filters associated with an EPS bearer.
#include "epc-tft.h"
Classes
struct PacketFilter
Implement the data structure representing a TrafficFlowTemplate Packet Filter.
Public Types
enum Direction { DOWNLINK = 1, UPLINK = 2, BIDIRECTIONAL = 3 }
Indicates the direction of the traffic that is to be classified.
Public Member Functions
EpcTft ()
uint8_t Add (PacketFilter f)
add a PacketFilter to the Traffic Flow Template
std::list< PacketFilter > GetPacketFilters () const
bool Matches (Direction direction, Ipv4Address remoteAddress, Ipv4Address localAddress, uint16_t remotePort, uint16_t localPort, uint8_t typeOfService)
bool Matches (Direction direction, Ipv6Address remoteAddress, Ipv6Address localAddress, uint16_t remotePort, uint16_t localPort, uint8_t typeOfService)
Public Member Functions inherited from ns3::SimpleRefCount< EpcTft >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Static Public Member Functions
static Ptr< EpcTft > Default ()
creates a TFT matching any traffic
Private Attributes
std::list< PacketFilter > m_filters
packet filter list
uint8_t m_numFilters
number of packet filters applied to this TFT
Detailed Description
This class implements the EPS bearer Traffic Flow Template (TFT), which is the set of all packet filters associated with an EPS bearer.
Definition at line 41 of file epc-tft.h.
Member Enumeration Documentation
Direction
enum ns3::EpcTft::Direction
Indicates the direction of the traffic that is to be classified.
Enumerator
DOWNLINK
UPLINK
BIDIRECTIONAL
Definition at line 57 of file epc-tft.h.
Constructor & Destructor Documentation
EpcTft()
ns3::EpcTft::EpcTft ()
Definition at line 233 of file epc-tft.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Add()
uint8_t ns3::EpcTft::Add (PacketFilter f)
add a PacketFilter to the Traffic Flow Template
Parameters
f the PacketFilter to be added
Returns
the id(0 <= id < 16) of the newly added filter, if the addition was successful. Will fail if you try to add more than 15 filters. This is to be compliant with TS 24.008.
Definition at line 240 of file epc-tft.cc.
References f(), m_filters, m_numFilters, NS_ABORT_IF, and NS_LOG_FUNCTION.
Referenced by EpcTftClassifierTestSuite::EpcTftClassifierTestSuite(), LteRadioLinkFailureTestCase::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LteEpcE2eDataTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), and LteX2HandoverTestCase::DoRun().
Default()
Ptr< EpcTft > ns3::EpcTft::Default () static
creates a TFT matching any traffic
Returns
a newly created TFT that will match any traffic
Definition at line 224 of file epc-tft.cc.
Referenced by ns3::LteHelper::Attach(), and ns3::LenaDeactivateBearerTestCase::DoRun().
GetPacketFilters()
std::list< EpcTft::PacketFilter > ns3::EpcTft::GetPacketFilters () const
Definition at line 299 of file epc-tft.cc.
References m_filters, and NS_LOG_FUNCTION.
Matches() [1/2]
bool ns3::EpcTft::Matches (Direction direction, Ipv4Address remoteAddress, Ipv4Address localAddress, uint16_t remotePort, uint16_t localPort, uint8_t typeOfService)
Parameters
direction
remoteAddress
localAddress
remotePort
localPort
typeOfService
Returns
true if any PacketFilter in the TFT matches with the parameters, false otherwise.
Definition at line 257 of file epc-tft.cc.
References m_filters, and NS_LOG_FUNCTION.
Matches() [2/2]
bool ns3::EpcTft::Matches (Direction direction, Ipv6Address remoteAddress, Ipv6Address localAddress, uint16_t remotePort, uint16_t localPort, uint8_t typeOfService)
Parameters
direction
remoteAddress
localAddress
remotePort
localPort
typeOfService
Returns
true if any PacketFilter in the TFT matches with the parameters, false otherwise.
Definition at line 278 of file epc-tft.cc.
References m_filters, and NS_LOG_FUNCTION.
Member Data Documentation
m_filters
std::list<PacketFilter> ns3::EpcTft::m_filters private
packet filter list
Definition at line 202 of file epc-tft.h.
Referenced by Add(), GetPacketFilters(), and Matches().
m_numFilters
uint8_t ns3::EpcTft::m_numFilters private
number of packet filters applied to this TFT
Definition at line 203 of file epc-tft.h.
Referenced by Add().
The documentation for this class was generated from the following files:
src/lte/model/epc-tft.h
src/lte/model/epc-tft.cc