ns-3: ns3::ExponentialRandomVariable Class Reference
ns3::ExponentialRandomVariable Class Reference
Core » Random Variables
The exponential distribution Random Number Generator (RNG).
#include "random-variable-stream.h"
Public Member Functions
ExponentialRandomVariable ()
Creates an exponential distribution RNG with the default values for the mean and upper bound.
double GetBound (void) const
Get the configured upper bound of this RNG.
uint32_t GetInteger (uint32_t mean, uint32_t bound)
Get the next random value, as an unsigned integer from the exponential distribution with the specified mean and upper bound.
virtual uint32_t GetInteger (void)
Get the next random value as an integer drawn from the distribution.
double GetMean (void) const
Get the configured mean value of this RNG.
double GetValue (double mean, double bound)
Get the next random value, as a double from the exponential distribution with the specified mean and upper bound.
virtual double GetValue (void)
Get the next random value as a double drawn from the distribution.
Public Member Functions inherited from ns3::RandomVariableStream
RandomVariableStream ()
Default constructor.
virtual ~RandomVariableStream ()
Destructor.
int64_t GetStream (void) const
Returns the stream number for the RngStream.
bool IsAntithetic (void) const
Check if antithetic values will be generated.
void SetAntithetic (bool isAntithetic)
Specify whether antithetic values should be generated.
void SetStream (int64_t stream)
Specifies the stream number for the RngStream.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::RandomVariableStream
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
double m_bound
The upper bound on values that can be returned by this RNG stream.
double m_mean
The mean value of the unbounded exponential distribution.
Additional Inherited Members
Protected Member Functions inherited from ns3::RandomVariableStream
RngStream * Peek (void) const
Get the pointer to the underlying RngStream.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The exponential distribution Random Number Generator (RNG).
This class supports the creation of objects that return random numbers from a fixed exponential distribution. It also supports the generation of single random numbers from various exponential distributions.
The probability density function of an exponential variable is defined as:
over the interval , where and Mean is a configurable attribute.
The normal RNG value is calculated by
where is a uniform random variable on .
Bounded Distribution
Since exponential distributions can theoretically return unbounded values, it is sometimes useful to specify a fixed upper limit. The bounded version is defined over the interval as:
where the Bound is a configurable attribute.
Note that in this case the true mean of the distribution is smaller than the nominal mean value:
Example
Here is an example of how to use this class:
double mean = 3.14;
double bound = 0.0;
Ptr<ExponentialRandomVariable> x = CreateObject<ExponentialRandomVariable> ();
x->SetAttribute ("Mean", DoubleValue (mean));
x->SetAttribute ("Bound", DoubleValue (bound));
// The expected value for the mean of the values returned by an
// exponentially distributed random variable is equal to mean.
double value = x->GetValue ();
Antithetic Values.
The antithetic value is calculated from
where again is a uniform random variable on .
Definition at line 538 of file random-variable-stream.h.
Constructor & Destructor Documentation
ExponentialRandomVariable()
ns3::ExponentialRandomVariable::ExponentialRandomVariable ()
Creates an exponential distribution RNG with the default values for the mean and upper bound.
Definition at line 386 of file random-variable-stream.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
GetBound()
double ns3::ExponentialRandomVariable::GetBound (void) const
Get the configured upper bound of this RNG.
Returns
The upper bound.
Definition at line 399 of file random-variable-stream.cc.
References m_bound, and NS_LOG_FUNCTION.
GetInteger() [1/2]
uint32_t ns3::ExponentialRandomVariable::GetInteger (uint32_t mean, uint32_t bound)
Get the next random value, as an unsigned integer from the exponential distribution with the specified mean and upper bound.
Parameters
[in] mean Mean value of the unbounded exponential distribution.
[in] bound Upper bound on values returned.
Returns
A random unsigned integer value.
Definition at line 429 of file random-variable-stream.cc.
References GetValue(), and NS_LOG_FUNCTION.
GetInteger() [2/2]
uint32_t ns3::ExponentialRandomVariable::GetInteger (void) virtual
Get the next random value as an integer drawn from the distribution.
Returns
An integer random value.
Implements ns3::RandomVariableStream.
Definition at line 442 of file random-variable-stream.cc.
References GetValue(), m_bound, m_mean, and NS_LOG_FUNCTION.
GetMean()
double ns3::ExponentialRandomVariable::GetMean (void) const
Get the configured mean value of this RNG.
Note
This will not be the actual mean if the distribution is truncated by a bound.
Returns
The configured mean value.
Definition at line 393 of file random-variable-stream.cc.
References m_mean, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::ExponentialRandomVariable::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 369 of file random-variable-stream.cc.
References m_bound, m_mean, ns3::MakeDoubleAccessor(), and ns3::TypeId::SetParent().
GetValue() [1/2]
double ns3::ExponentialRandomVariable::GetValue (double mean, double bound)
Get the next random value, as a double from the exponential distribution with the specified mean and upper bound.
Parameters
[in] mean Mean value of the unbounded exponential distribution.
[in] bound Upper bound on values returned.
Returns
A floating point random value.
Definition at line 406 of file random-variable-stream.cc.
References ns3::RandomVariableStream::IsAntithetic(), NS_LOG_FUNCTION, ns3::RandomVariableStream::Peek(), and ns3::RngStream::RandU01().
Referenced by ns3::UanMacRc::Associate(), ns3::UanMacRc::AssociateTimeout(), RandomVariableStreamExponentialTestCase::ChiSquaredTest(), RandomVariableStreamExponentialAntitheticTestCase::ChiSquaredTest(), RngExponentialTestCase::ChiSquaredTest(), ns3::ThreeGppHttpVariables::GetParsingTime(), ns3::ThreeGppHttpVariables::GetReadingTime(), ns3::UanMacRc::RtsTimeout(), ns3::UanMacRc::ScheduleData(), Experiment::SendMultiDestinations(), and ns3::UanMacRc::SendRts().
GetValue() [2/2]
double ns3::ExponentialRandomVariable::GetValue (void) virtual
Get the next random value as a double drawn from the distribution.
Returns
A floating point random value.
Implements ns3::RandomVariableStream.
Definition at line 436 of file random-variable-stream.cc.
References m_bound, m_mean, and NS_LOG_FUNCTION.
Referenced by GetInteger().
Member Data Documentation
m_bound
double ns3::ExponentialRandomVariable::m_bound private
The upper bound on values that can be returned by this RNG stream.
Definition at line 595 of file random-variable-stream.h.
Referenced by GetBound(), GetInteger(), GetTypeId(), and GetValue().
m_mean
double ns3::ExponentialRandomVariable::m_mean private
The mean value of the unbounded exponential distribution.
Definition at line 592 of file random-variable-stream.h.
Referenced by GetInteger(), GetMean(), GetTypeId(), and GetValue().
The documentation for this class was generated from the following files:
src/core/model/random-variable-stream.h
src/core/model/random-variable-stream.cc