ns-3: ns3::EnbMacMemberFfMacCschedSapUser Class Reference
ns3::EnbMacMemberFfMacCschedSapUser Class Reference
EnbMacMemberFfMacCschedSapUser class.
Public Member Functions
EnbMacMemberFfMacCschedSapUser (LteEnbMac *mac)
Constructor.
virtual void CschedCellConfigCnf (const struct CschedCellConfigCnfParameters &params)
CSCHED_CELL_CONFIG_CNF.
virtual void CschedCellConfigUpdateInd (const struct CschedCellConfigUpdateIndParameters &params)
CSCHED_UE_CONFIG_IND.
virtual void CschedLcConfigCnf (const struct CschedLcConfigCnfParameters &params)
CSCHED_LC_CONFIG_CNF.
virtual void CschedLcReleaseCnf (const struct CschedLcReleaseCnfParameters &params)
CSCHED_LC_RELEASE_CNF.
virtual void CschedUeConfigCnf (const struct CschedUeConfigCnfParameters &params)
CSCHED_UE_CONFIG_CNF.
virtual void CschedUeConfigUpdateInd (const struct CschedUeConfigUpdateIndParameters &params)
CSCHED_UE_UPDATE_IND.
virtual void CschedUeReleaseCnf (const struct CschedUeReleaseCnfParameters &params)
CSCHED_UE_RELEASE_CNF.
Public Member Functions inherited from ns3::FfMacCschedSapUser
virtual ~FfMacCschedSapUser ()
Private Attributes
LteEnbMac * m_mac
the MAC
Detailed Description
EnbMacMemberFfMacCschedSapUser class.
Definition at line 187 of file lte-enb-mac.cc.
Constructor & Destructor Documentation
EnbMacMemberFfMacCschedSapUser()
ns3::EnbMacMemberFfMacCschedSapUser::EnbMacMemberFfMacCschedSapUser (LteEnbMac * mac)
Constructor.
Parameters
mac the MAC
Definition at line 210 of file lte-enb-mac.cc.
Member Function Documentation
CschedCellConfigCnf()
void ns3::EnbMacMemberFfMacCschedSapUser::CschedCellConfigCnf (const struct CschedCellConfigCnfParameters & params) virtual
CSCHED_CELL_CONFIG_CNF.
Parameters
params CschedCellConfigCnfParameters
Implements ns3::FfMacCschedSapUser.
Definition at line 216 of file lte-enb-mac.cc.
References ns3::LteEnbMac::DoCschedCellConfigCnf(), m_mac, and aloha::params.
CschedCellConfigUpdateInd()
void ns3::EnbMacMemberFfMacCschedSapUser::CschedCellConfigUpdateInd (const struct CschedCellConfigUpdateIndParameters & params) virtual
CSCHED_UE_CONFIG_IND.
Parameters
params CschedCellConfigUpdateIndParameters
Implements ns3::FfMacCschedSapUser.
Definition at line 252 of file lte-enb-mac.cc.
References ns3::LteEnbMac::DoCschedCellConfigUpdateInd(), m_mac, and aloha::params.
CschedLcConfigCnf()
void ns3::EnbMacMemberFfMacCschedSapUser::CschedLcConfigCnf (const struct CschedLcConfigCnfParameters & params) virtual
CSCHED_LC_CONFIG_CNF.
Parameters
params CschedLcConfigCnfParameters
Implements ns3::FfMacCschedSapUser.
Definition at line 228 of file lte-enb-mac.cc.
References ns3::LteEnbMac::DoCschedLcConfigCnf(), m_mac, and aloha::params.
CschedLcReleaseCnf()
void ns3::EnbMacMemberFfMacCschedSapUser::CschedLcReleaseCnf (const struct CschedLcReleaseCnfParameters & params) virtual
CSCHED_LC_RELEASE_CNF.
Parameters
params CschedLcReleaseCnfParameters
Implements ns3::FfMacCschedSapUser.
Definition at line 234 of file lte-enb-mac.cc.
References ns3::LteEnbMac::DoCschedLcReleaseCnf(), m_mac, and aloha::params.
CschedUeConfigCnf()
void ns3::EnbMacMemberFfMacCschedSapUser::CschedUeConfigCnf (const struct CschedUeConfigCnfParameters & params) virtual
CSCHED_UE_CONFIG_CNF.
Parameters
params CschedUeConfigCnfParameters
Implements ns3::FfMacCschedSapUser.
Definition at line 222 of file lte-enb-mac.cc.
References ns3::LteEnbMac::DoCschedUeConfigCnf(), m_mac, and aloha::params.
CschedUeConfigUpdateInd()
void ns3::EnbMacMemberFfMacCschedSapUser::CschedUeConfigUpdateInd (const struct CschedUeConfigUpdateIndParameters & params) virtual
CSCHED_UE_UPDATE_IND.
Parameters
params CschedUeConfigUpdateIndParameters
Implements ns3::FfMacCschedSapUser.
Definition at line 246 of file lte-enb-mac.cc.
References ns3::LteEnbMac::DoCschedUeConfigUpdateInd(), m_mac, and aloha::params.
CschedUeReleaseCnf()
void ns3::EnbMacMemberFfMacCschedSapUser::CschedUeReleaseCnf (const struct CschedUeReleaseCnfParameters & params) virtual
CSCHED_UE_RELEASE_CNF.
Parameters
params CschedUeReleaseCnfParameters
Implements ns3::FfMacCschedSapUser.
Definition at line 240 of file lte-enb-mac.cc.
References ns3::LteEnbMac::DoCschedUeReleaseCnf(), m_mac, and aloha::params.
Member Data Documentation
m_mac
LteEnbMac* ns3::EnbMacMemberFfMacCschedSapUser::m_mac private
the MAC
Definition at line 206 of file lte-enb-mac.cc.
Referenced by CschedCellConfigCnf(), CschedCellConfigUpdateInd(), CschedLcConfigCnf(), CschedLcReleaseCnf(), CschedUeConfigCnf(), CschedUeConfigUpdateInd(), and CschedUeReleaseCnf().
The documentation for this class was generated from the following file:
src/lte/model/lte-enb-mac.cc