ns-3: LogicalLoraChannelTest Class Reference
LogicalLoraChannelTest Class Reference
Public Member Functions
LogicalLoraChannelTest ()
virtual ~LogicalLoraChannelTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 713 of file lorawan-test-suite.cc.
Constructor & Destructor Documentation
LogicalLoraChannelTest()
LogicalLoraChannelTest::LogicalLoraChannelTest ()
Definition at line 724 of file lorawan-test-suite.cc.
~LogicalLoraChannelTest()
LogicalLoraChannelTest::~LogicalLoraChannelTest () virtual
Definition at line 730 of file lorawan-test-suite.cc.
Member Function Documentation
DoRun()
void LogicalLoraChannelTest::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 737 of file lorawan-test-suite.cc.
References ns3::lorawan::LogicalLoraChannelHelper::AddChannel(), ns3::lorawan::LogicalLoraChannelHelper::AddEvent(), ns3::lorawan::LogicalLoraChannelHelper::AddSubBand(), ns3::lorawan::SubBand::BelongsToSubBand(), ns3::lorawan::LogicalLoraChannel::GetFrequency(), ns3::lorawan::LogicalLoraChannelHelper::GetWaitingTime(), NS_LOG_DEBUG, NS_TEST_EXPECT_MSG_EQ, NS_TEST_EXPECT_MSG_NE, and ns3::Seconds().
The documentation for this class was generated from the following file:
src/lorawan/test/lorawan-test-suite.cc