ns-3: ns3::Icmpv6OptionMtu Class Reference
ns3::Icmpv6OptionMtu Class Reference
Internet » IPv6 classes and sub-modules » ICMPv6 protocol and associated headers.
ICMPv6 MTU option.
#include "icmpv6-header.h"
Public Member Functions
Icmpv6OptionMtu ()
Constructor.
Icmpv6OptionMtu (uint32_t mtu)
Constructor.
virtual ~Icmpv6OptionMtu ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
uint32_t GetMtu () const
Get the MTU.
uint16_t GetReserved () const
Get the reserved field.
virtual uint32_t GetSerializedSize () const
Get the serialized size.
virtual void Print (std::ostream &os) const
Print information.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetMtu (uint32_t mtu)
Set the MTU.
void SetReserved (uint16_t reserved)
Set the reserved field.
Public Member Functions inherited from ns3::Icmpv6OptionHeader
Icmpv6OptionHeader ()
Constructor.
virtual ~Icmpv6OptionHeader ()
Destructor.
uint8_t GetLength () const
Get the length of the option in 8 bytes unit.
uint8_t GetType () const
Get the type of the option.
void SetLength (uint8_t len)
Set the length of the option.
void SetType (uint8_t type)
Set the type of the option.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the UID of this class.
Static Public Member Functions inherited from ns3::Icmpv6OptionHeader
static TypeId GetTypeId ()
Get the UID of this class.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint32_t m_mtu
The MTU value.
uint16_t m_reserved
The reserved value.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
ICMPv6 MTU option.
Definition at line 1374 of file icmpv6-header.h.
Constructor & Destructor Documentation
Icmpv6OptionMtu() [1/2]
ns3::Icmpv6OptionMtu::Icmpv6OptionMtu ()
Constructor.
Definition at line 1560 of file icmpv6-header.cc.
References ns3::Icmpv6Header::ICMPV6_OPT_MTU, NS_LOG_FUNCTION, ns3::Icmpv6OptionHeader::SetLength(), SetReserved(), and ns3::Icmpv6OptionHeader::SetType().
Icmpv6OptionMtu() [2/2]
ns3::Icmpv6OptionMtu::Icmpv6OptionMtu (uint32_t mtu)
Constructor.
Parameters
mtu MTU used.
Definition at line 1568 of file icmpv6-header.cc.
References ns3::Icmpv6Header::ICMPV6_OPT_MTU, NS_LOG_FUNCTION, ns3::Icmpv6OptionHeader::SetLength(), SetReserved(), and ns3::Icmpv6OptionHeader::SetType().
~Icmpv6OptionMtu()
ns3::Icmpv6OptionMtu::~Icmpv6OptionMtu () virtual
Destructor.
Definition at line 1577 of file icmpv6-header.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Deserialize()
uint32_t ns3::Icmpv6OptionMtu::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start start offset
Returns
length of packet
Reimplemented from ns3::Icmpv6OptionHeader.
Definition at line 1628 of file icmpv6-header.cc.
References GetSerializedSize(), NS_LOG_FUNCTION, ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadNtohU32(), ns3::Buffer::Iterator::ReadU8(), ns3::Icmpv6OptionHeader::SetLength(), SetMtu(), SetReserved(), ns3::Icmpv6OptionHeader::SetType(), and visualizer.core::start().
GetInstanceTypeId()
TypeId ns3::Icmpv6OptionMtu::GetInstanceTypeId () const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::Icmpv6OptionHeader.
Definition at line 1554 of file icmpv6-header.cc.
References GetTypeId(), and NS_LOG_FUNCTION.
GetMtu()
uint32_t ns3::Icmpv6OptionMtu::GetMtu () const
Get the MTU.
Returns
the MTU value
Definition at line 1594 of file icmpv6-header.cc.
References m_mtu, and NS_LOG_FUNCTION.
Referenced by Serialize().
GetReserved()
uint16_t ns3::Icmpv6OptionMtu::GetReserved () const
Get the reserved field.
Returns
the reserved value
Definition at line 1582 of file icmpv6-header.cc.
References m_reserved, and NS_LOG_FUNCTION.
Referenced by Serialize().
GetSerializedSize()
uint32_t ns3::Icmpv6OptionMtu::GetSerializedSize () const virtual
Get the serialized size.
Returns
serialized size
Reimplemented from ns3::Icmpv6OptionHeader.
Definition at line 1612 of file icmpv6-header.cc.
References NS_LOG_FUNCTION.
Referenced by Deserialize().
GetTypeId()
TypeId ns3::Icmpv6OptionMtu::GetTypeId () static
Get the UID of this class.
Returns
UID
Definition at line 1544 of file icmpv6-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::Icmpv6OptionMtu::Print (std::ostream & os) const virtual
Print information.
Parameters
os output stream
Reimplemented from ns3::Icmpv6OptionHeader.
Definition at line 1606 of file icmpv6-header.cc.
References ns3::Icmpv6OptionHeader::GetLength(), ns3::Icmpv6OptionHeader::GetType(), m_mtu, and NS_LOG_FUNCTION.
Serialize()
void ns3::Icmpv6OptionMtu::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start start offset
Reimplemented from ns3::Icmpv6OptionHeader.
Definition at line 1618 of file icmpv6-header.cc.
References ns3::Icmpv6OptionHeader::GetLength(), GetMtu(), GetReserved(), ns3::Icmpv6OptionHeader::GetType(), NS_LOG_FUNCTION, visualizer.core::start(), ns3::Buffer::Iterator::WriteHtonU16(), ns3::Buffer::Iterator::WriteHtonU32(), and ns3::Buffer::Iterator::WriteU8().
SetMtu()
void ns3::Icmpv6OptionMtu::SetMtu (uint32_t mtu)
Set the MTU.
Parameters
mtu the MTU to set
Definition at line 1600 of file icmpv6-header.cc.
References m_mtu, and NS_LOG_FUNCTION.
Referenced by Deserialize().
SetReserved()
void ns3::Icmpv6OptionMtu::SetReserved (uint16_t reserved)
Set the reserved field.
Parameters
reserved the reserved value
Definition at line 1588 of file icmpv6-header.cc.
References m_reserved, and NS_LOG_FUNCTION.
Referenced by Icmpv6OptionMtu(), and Deserialize().
Member Data Documentation
m_mtu
uint32_t ns3::Icmpv6OptionMtu::m_mtu private
The MTU value.
Definition at line 1463 of file icmpv6-header.h.
Referenced by GetMtu(), Print(), and SetMtu().
m_reserved
uint16_t ns3::Icmpv6OptionMtu::m_reserved private
The reserved value.
Definition at line 1458 of file icmpv6-header.h.
Referenced by GetReserved(), and SetReserved().
The documentation for this class was generated from the following files:
src/internet/model/icmpv6-header.h
src/internet/model/icmpv6-header.cc