ns-3: DualStackTestCase Class Reference
DualStackTestCase Class Reference
Internet » internet module tests | Test suites
IPv6 dual stack Test.
Public Member Functions
DualStackTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
virtual void DoTeardown (void)
Implementation to do any local setup required for this TestCase.
void ServerHandleConnectionCreated1 (Ptr< Socket > s, const Address &addr)
Handle connection created (1).
void ServerHandleConnectionCreated2 (Ptr< Socket > s, const Address &addr)
Handle connection created (2).
void ServerHandleConnectionCreated3 (Ptr< Socket > s, const Address &addr)
Handle connection created (3).
void ServerHandleConnectionCreated4 (Ptr< Socket > s, const Address &addr)
Handle connection created (4).
void SetUpSim ()
Setup the test.
Private Attributes
Ptr< Node > node0
Node 0.
Ptr< Node > node1
Node 1.
Address receivedAddr1
Received address (1).
Address receivedAddr2
Received address (2).
Address receivedAddr3
Received address (3).
Address receivedAddr4
Received address (4).
Ptr< Socket > server1
Server socket (1).
Ptr< Socket > server2
Server socket (2).
Ptr< Socket > server3
Server socket (3).
Ptr< Socket > server4
Server socket (4).
Ptr< Socket > source1
Sending socket (1).
Ptr< Socket > source2
Sending socket (2).
Ptr< Socket > source3
Sending socket (3).
Ptr< Socket > source4
Sending socket (4).
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
IPv6 dual stack Test.
Definition at line 61 of file ipv6-dual-stack-test-suite.cc.
Constructor & Destructor Documentation
DualStackTestCase()
DualStackTestCase::DualStackTestCase ()
Definition at line 257 of file ipv6-dual-stack-test-suite.cc.
References receivedAddr1, receivedAddr2, receivedAddr3, and receivedAddr4.
Member Function Documentation
DoRun()
void DualStackTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 267 of file ipv6-dual-stack-test-suite.cc.
References ns3::Socket::Bind(), ns3::Socket::Connect(), ns3::Address::IsInvalid(), ns3::Socket::Listen(), ns3::MakeCallback(), ns3::MakeNullCallback(), NS_TEST_EXPECT_MSG_EQ, receivedAddr1, receivedAddr2, receivedAddr3, receivedAddr4, server1, server2, server3, server4, ServerHandleConnectionCreated1(), ServerHandleConnectionCreated2(), ServerHandleConnectionCreated3(), ServerHandleConnectionCreated4(), ns3::Socket::SetAcceptCallback(), SetUpSim(), source1, source2, source3, and source4.
DoTeardown()
void DualStackTestCase::DoTeardown (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test teardown
Reimplemented from ns3::TestCase.
Definition at line 332 of file ipv6-dual-stack-test-suite.cc.
ServerHandleConnectionCreated1()
void DualStackTestCase::ServerHandleConnectionCreated1 (Ptr< Socket > s, const Address & addr) private
Handle connection created (1).
Parameters
s The socket.
addr The peer address.
Definition at line 229 of file ipv6-dual-stack-test-suite.cc.
Referenced by DoRun().
ServerHandleConnectionCreated2()
void DualStackTestCase::ServerHandleConnectionCreated2 (Ptr< Socket > s, const Address & addr) private
Handle connection created (2).
Parameters
s The socket.
addr The peer address.
Definition at line 236 of file ipv6-dual-stack-test-suite.cc.
Referenced by DoRun().
ServerHandleConnectionCreated3()
void DualStackTestCase::ServerHandleConnectionCreated3 (Ptr< Socket > s, const Address & addr) private
Handle connection created (3).
Parameters
s The socket.
addr The peer address.
Definition at line 243 of file ipv6-dual-stack-test-suite.cc.
Referenced by DoRun().
ServerHandleConnectionCreated4()
void DualStackTestCase::ServerHandleConnectionCreated4 (Ptr< Socket > s, const Address & addr) private
Handle connection created (4).
Parameters
s The socket.
addr The peer address.
Definition at line 250 of file ipv6-dual-stack-test-suite.cc.
Referenced by DoRun().
SetUpSim()
void DualStackTestCase::SetUpSim () private
Setup the test.
Definition at line 198 of file ipv6-dual-stack-test-suite.cc.
References AddSimpleNetDevice(), third::channel, CreateDualStackNode(), ns3::Socket::CreateSocket(), ns3::SocketFactory::CreateSocket(), and ns3::SimpleNetDevice::SetChannel().
Referenced by DoRun().
Member Data Documentation
node0
Ptr<Node> DualStackTestCase::node0 private
Node 0.
Definition at line 74 of file ipv6-dual-stack-test-suite.cc.
node1
Ptr<Node> DualStackTestCase::node1 private
Node 1.
Definition at line 75 of file ipv6-dual-stack-test-suite.cc.
Referenced by wifi_intrastructure_link.WifiLink::destroy(), wifi_intrastructure_link.WifiLink::tooltip_query(), visualizer.core.WiredLink::update_points(), and wifi_intrastructure_link.WifiLink::update_points().
receivedAddr1
Address DualStackTestCase::receivedAddr1 private
Received address (1).
Definition at line 112 of file ipv6-dual-stack-test-suite.cc.
Referenced by DualStackTestCase(), and DoRun().
receivedAddr2
Address DualStackTestCase::receivedAddr2 private
Received address (2).
Definition at line 113 of file ipv6-dual-stack-test-suite.cc.
Referenced by DualStackTestCase(), and DoRun().
receivedAddr3
Address DualStackTestCase::receivedAddr3 private
Received address (3).
Definition at line 114 of file ipv6-dual-stack-test-suite.cc.
Referenced by DualStackTestCase(), and DoRun().
receivedAddr4
Address DualStackTestCase::receivedAddr4 private
Received address (4).
Definition at line 115 of file ipv6-dual-stack-test-suite.cc.
Referenced by DualStackTestCase(), and DoRun().
server1
Ptr<Socket> DualStackTestCase::server1 private
Server socket (1).
Definition at line 102 of file ipv6-dual-stack-test-suite.cc.
Referenced by DoRun().
server2
Ptr<Socket> DualStackTestCase::server2 private
Server socket (2).
Definition at line 103 of file ipv6-dual-stack-test-suite.cc.
Referenced by DoRun().
server3
Ptr<Socket> DualStackTestCase::server3 private
Server socket (3).
Definition at line 104 of file ipv6-dual-stack-test-suite.cc.
Referenced by DoRun().
server4
Ptr<Socket> DualStackTestCase::server4 private
Server socket (4).
Definition at line 105 of file ipv6-dual-stack-test-suite.cc.
Referenced by DoRun().
source1
Ptr<Socket> DualStackTestCase::source1 private
Sending socket (1).
Definition at line 107 of file ipv6-dual-stack-test-suite.cc.
Referenced by DoRun().
source2
Ptr<Socket> DualStackTestCase::source2 private
Sending socket (2).
Definition at line 108 of file ipv6-dual-stack-test-suite.cc.
Referenced by DoRun().
source3
Ptr<Socket> DualStackTestCase::source3 private
Sending socket (3).
Definition at line 109 of file ipv6-dual-stack-test-suite.cc.
Referenced by DoRun().
source4
Ptr<Socket> DualStackTestCase::source4 private
Sending socket (4).
Definition at line 110 of file ipv6-dual-stack-test-suite.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/internet/test/ipv6-dual-stack-test-suite.cc