ns-3: ns3::V4TraceRouteHelper Class Reference
ns3::V4TraceRouteHelper Class Reference
Internet Applications » V4Traceroute
Create a IPv4 traceroute application and associate it to a node.
#include "v4traceroute-helper.h"
Public Member Functions
V4TraceRouteHelper (Ipv4Address remote)
Create a V4TraceRouteHelper which is used to make life easier for people wanting to use TraceRoute.
ApplicationContainer Install (NodeContainer nodes) const
Install a TraceRoute application on each Node in the provided NodeContainer.
ApplicationContainer Install (Ptr< Node > node) const
Install a TraceRoute application on the provided Node.
ApplicationContainer Install (std::string nodeName) const
Install a TraceRoute application on the provided Node.
void SetAttribute (std::string name, const AttributeValue &value)
Configure traceRoute applications attribute.
Static Public Member Functions
static void PrintTraceRouteAt (Ptr< Node > node, Ptr< OutputStreamWrapper > stream)
Print the resulting trace routes from given node.
Private Member Functions
Ptr< Application > InstallPriv (Ptr< Node > node) const
Do the actual application installation in the node.
Private Attributes
ObjectFactory m_factory
Object factory.
Detailed Description
Create a IPv4 traceroute application and associate it to a node.
This class creates one or multiple instances of ns3::V4TraceRoute and associates it/them to one/multiple node(s).
Definition at line 40 of file v4traceroute-helper.h.
Constructor & Destructor Documentation
V4TraceRouteHelper()
ns3::V4TraceRouteHelper::V4TraceRouteHelper (Ipv4Address remote)
Create a V4TraceRouteHelper which is used to make life easier for people wanting to use TraceRoute.
Parameters
remote The address which should be traced
Definition at line 30 of file v4traceroute-helper.cc.
References m_factory, ns3::ObjectFactory::Set(), and ns3::ObjectFactory::SetTypeId().
Member Function Documentation
Install() [1/3]
ApplicationContainer ns3::V4TraceRouteHelper::Install (NodeContainer nodes) const
Install a TraceRoute application on each Node in the provided NodeContainer.
Parameters
nodes The NodeContainer containing all of the nodes to get a V4TraceRoute application.
Returns
A list of TraceRoute applications, one for each input node
Definition at line 56 of file v4traceroute-helper.cc.
References ns3::ApplicationContainer::Add(), ns3::NodeContainer::Begin(), ns3::NodeContainer::End(), and InstallPriv().
Referenced by TracerouteExample::InstallApplications().
Install() [2/3]
ApplicationContainer ns3::V4TraceRouteHelper::Install (Ptr< Node > node) const
Install a TraceRoute application on the provided Node.
The Node is specified directly by a Ptr<Node>
Parameters
node The node to install the V4TraceRouteApplication on.
Returns
An ApplicationContainer holding the TraceRoute application created.
Definition at line 43 of file v4traceroute-helper.cc.
References InstallPriv().
Install() [3/3]
ApplicationContainer ns3::V4TraceRouteHelper::Install (std::string nodeName) const
Install a TraceRoute application on the provided Node.
The Node is specified by a string that must have previously been associated with a Node using the Object Name Service.
Parameters
nodeName The node to install the V4TraceRouteApplication on.
Returns
An ApplicationContainer holding the TraceRoute application created.
Definition at line 49 of file v4traceroute-helper.cc.
References InstallPriv().
InstallPriv()
Ptr< Application > ns3::V4TraceRouteHelper::InstallPriv (Ptr< Node > node) const private
Do the actual application installation in the node.
Parameters
node the node
Returns
a Smart pointer to the installed application
Definition at line 68 of file v4traceroute-helper.cc.
References ns3::Node::AddApplication(), ns3::ObjectFactory::Create(), and m_factory.
Referenced by Install().
PrintTraceRouteAt()
void ns3::V4TraceRouteHelper::PrintTraceRouteAt (Ptr< Node > node, Ptr< OutputStreamWrapper > stream) static
Print the resulting trace routes from given node.
Parameters
node The origin node where the traceroute is initiated.
stream The outputstream used to print the resulting traced routes.
Definition at line 77 of file v4traceroute-helper.cc.
References ns3::Node::GetApplication(), ns3::Node::GetId(), ns3::Node::GetNApplications(), ns3::Object::GetObject(), ns3::OutputStreamWrapper::GetStream(), and NS_ASSERT_MSG().
SetAttribute()
void ns3::V4TraceRouteHelper::SetAttribute (std::string name, const AttributeValue & value)
Configure traceRoute applications attribute.
Parameters
name attribute's name
value attribute's value
Definition at line 37 of file v4traceroute-helper.cc.
References m_factory, and ns3::ObjectFactory::Set().
Referenced by TracerouteExample::InstallApplications().
Member Data Documentation
m_factory
ObjectFactory ns3::V4TraceRouteHelper::m_factory private
Object factory.
Definition at line 104 of file v4traceroute-helper.h.
Referenced by V4TraceRouteHelper(), InstallPriv(), and SetAttribute().
The documentation for this class was generated from the following files:
src/internet-apps/helper/v4traceroute-helper.h
src/internet-apps/helper/v4traceroute-helper.cc