ns-3: ns3::TcpScalable Class Reference
ns3::TcpScalable Class Reference
Internet » TCP » Congestion Control Algorithms.
An implementation of TCP Scalable.
#include "tcp-scalable.h"
Public Member Functions
TcpScalable (const TcpScalable &sock)
Copy constructor.
TcpScalable (void)
Create an unbound tcp socket.
virtual ~TcpScalable (void)
virtual Ptr< TcpCongestionOps > Fork ()
Copy the congestion control algorithm across sockets.
virtual std::string GetName () const
Get the name of the congestion control algorithm.
virtual uint32_t GetSsThresh (Ptr< const TcpSocketState > tcb, uint32_t bytesInFlight)
Get slow start threshold following Scalable principle (Equation 2)
Public Member Functions inherited from ns3::TcpNewReno
TcpNewReno ()
TcpNewReno (const TcpNewReno &sock)
Copy constructor.
~TcpNewReno ()
virtual void IncreaseWindow (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
Try to increase the cWnd following the NewReno specification.
virtual void ReduceCwnd (Ptr< TcpSocketState > tcb)
Reduces congestion window on receipt of ECN Echo Flag.
Public Member Functions inherited from ns3::TcpCongestionOps
TcpCongestionOps ()
TcpCongestionOps (const TcpCongestionOps &other)
Copy constructor.
virtual ~TcpCongestionOps ()
virtual void CongControl (Ptr< TcpSocketState > tcb, const TcpRateOps::TcpRateConnection &rc, const TcpRateOps::TcpRateSample &rs)
Called when packets are delivered to update cwnd and pacing rate.
virtual void CongestionStateSet (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCongState_t newState)
Trigger events/calculations specific to a congestion state.
virtual void CwndEvent (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCAEvent_t event)
Trigger events/calculations on occurrence of congestion window event.
virtual bool HasCongControl () const
Returns true when Congestion Control Algorithm implements CongControl.
virtual void Init (Ptr< TcpSocketState > tcb)
Set configuration required by congestion control algorithm.
virtual void PktsAcked (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked, const Time &rtt)
Timing information on received ACK.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpNewReno
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpCongestionOps
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void CongestionAvoidance (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
Congestion avoidance of TcpScalable (Equation 1)
Protected Member Functions inherited from ns3::TcpNewReno
virtual uint32_t SlowStart (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
Tcp NewReno slow start algorithm.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Attributes
uint32_t m_ackCnt
Number of received ACK.
uint32_t m_aiFactor
Additive increase factor.
double m_mdFactor
Multiplicative decrease factor.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
An implementation of TCP Scalable.
Scalable improves TCP performance to better utilize the available bandwidth of a highspeed wide area network by altering NewReno congestion window adjustment algorithm.
When congestion has not been detected, for each ACK received in an RTT, Scalable increases its cwnd per:
    cwnd = cwnd + 0.01                  (1)
Following Linux implementation of Scalable, we use 50 instead of 100 to account for delayed ACK.
On the first detection of congestion in a given RTT, cwnd is reduced based on the following equation:
    cwnd = cwnd - ceil(0.125 * cwnd)       (2)
More information: http://doi.acm.org/10.1145/956981.956989
Definition at line 64 of file tcp-scalable.h.
Constructor & Destructor Documentation
TcpScalable() [1/2]
ns3::TcpScalable::TcpScalable (void)
Create an unbound tcp socket.
Definition at line 59 of file tcp-scalable.cc.
References NS_LOG_FUNCTION.
TcpScalable() [2/2]
ns3::TcpScalable::TcpScalable (const TcpScalable & sock)
Copy constructor.
Parameters
sock the object to copy
Definition at line 68 of file tcp-scalable.cc.
References NS_LOG_FUNCTION.
~TcpScalable()
ns3::TcpScalable::~TcpScalable (void) virtual
Definition at line 77 of file tcp-scalable.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CongestionAvoidance()
void ns3::TcpScalable::CongestionAvoidance (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked) protected virtual
Congestion avoidance of TcpScalable (Equation 1)
Parameters
tcb internal congestion state
segmentsAcked count of segments acked
Reimplemented from ns3::TcpNewReno.
Definition at line 89 of file tcp-scalable.cc.
References ns3::TcpSocketState::GetCwndInSegments(), m_ackCnt, m_aiFactor, ns3::TcpSocketState::m_cWnd, ns3::TcpSocketState::m_segmentSize, ns3::TcpSocketState::m_ssThresh, min, NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_INFO.
Fork()
Ptr< TcpCongestionOps > ns3::TcpScalable::Fork () virtual
Copy the congestion control algorithm across sockets.
Returns
a pointer of the copied object
Reimplemented from ns3::TcpNewReno.
Definition at line 83 of file tcp-scalable.cc.
GetName()
std::string ns3::TcpScalable::GetName () const virtual
Get the name of the congestion control algorithm.
Returns
A string identifying the name
Reimplemented from ns3::TcpNewReno.
Definition at line 123 of file tcp-scalable.cc.
GetSsThresh()
uint32_t ns3::TcpScalable::GetSsThresh (Ptr< const TcpSocketState > tcb, uint32_t bytesInFlight) virtual
Get slow start threshold following Scalable principle (Equation 2)
Parameters
tcb internal congestion state
bytesInFlight bytes in flight
Returns
the slow start threshold value
Reimplemented from ns3::TcpNewReno.
Definition at line 129 of file tcp-scalable.cc.
References m_mdFactor, max, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by TcpScalableDecrementTest::DoRun().
GetTypeId()
TypeId ns3::TcpScalable::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 41 of file tcp-scalable.cc.
References m_aiFactor, m_mdFactor, ns3::MakeDoubleAccessor(), ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
Member Data Documentation
m_ackCnt
uint32_t ns3::TcpScalable::m_ackCnt private
Number of received ACK.
Definition at line 111 of file tcp-scalable.h.
Referenced by CongestionAvoidance().
m_aiFactor
uint32_t ns3::TcpScalable::m_aiFactor private
Additive increase factor.
Definition at line 112 of file tcp-scalable.h.
Referenced by CongestionAvoidance(), and GetTypeId().
m_mdFactor
double ns3::TcpScalable::m_mdFactor private
Multiplicative decrease factor.
Definition at line 113 of file tcp-scalable.h.
Referenced by GetSsThresh(), and GetTypeId().
The documentation for this class was generated from the following files:
src/internet/model/tcp-scalable.h
src/internet/model/tcp-scalable.cc