ns-3: TestThresholdPreambleDetectionWithoutFrameCapture Class Reference
TestThresholdPreambleDetectionWithoutFrameCapture Class Reference
Wifi Models » wifi module tests | Test suites
Preamble detection test w/o frame capture.
Public Member Functions
TestThresholdPreambleDetectionWithoutFrameCapture ()
virtual ~TestThresholdPreambleDetectionWithoutFrameCapture ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Member Functions
virtual void DoSetup (void)
Implementation to do any local setup required for this TestCase.
void RxFailure (Ptr< WifiPsdu > psdu)
Spectrum wifi receive failure function.
void RxSuccess (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector, std::vector< bool > statusPerMpdu)
Spectrum wifi receive success function.
void SendPacket (double rxPowerDbm)
Send packet function.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Protected Attributes
uint32_t m_countRxFailure
count RX failure
uint32_t m_countRxSuccess
count RX success
Ptr< SpectrumWifiPhy > m_phy
Phy.
Private Member Functions
void CheckPhyState (WifiPhyState expectedState)
Schedule now to check the PHY state.
void CheckRxPacketCount (uint32_t expectedSuccessCount, uint32_t expectedFailureCount)
Check the number of received packets.
void DoCheckPhyState (WifiPhyState expectedState)
Check the PHY state now.
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Detailed Description
Preamble detection test w/o frame capture.
Definition at line 57 of file wifi-phy-reception-test.cc.
Constructor & Destructor Documentation
TestThresholdPreambleDetectionWithoutFrameCapture()
TestThresholdPreambleDetectionWithoutFrameCapture::TestThresholdPreambleDetectionWithoutFrameCapture ()
Definition at line 108 of file wifi-phy-reception-test.cc.
~TestThresholdPreambleDetectionWithoutFrameCapture()
TestThresholdPreambleDetectionWithoutFrameCapture::~TestThresholdPreambleDetectionWithoutFrameCapture () virtual
Definition at line 182 of file wifi-phy-reception-test.cc.
References m_phy.
Member Function Documentation
CheckPhyState()
void TestThresholdPreambleDetectionWithoutFrameCapture::CheckPhyState (WifiPhyState expectedState) private
Schedule now to check the PHY state.
Parameters
expectedState the expected PHY state
Definition at line 143 of file wifi-phy-reception-test.cc.
References DoCheckPhyState().
Referenced by DoRun().
CheckRxPacketCount()
void TestThresholdPreambleDetectionWithoutFrameCapture::CheckRxPacketCount (uint32_t expectedSuccessCount, uint32_t expectedFailureCount) private
Check the number of received packets.
Parameters
expectedSuccessCount the number of successfully received packets
expectedFailureCount the number of unsuccessfully received packets
Definition at line 162 of file wifi-phy-reception-test.cc.
References m_countRxFailure, m_countRxSuccess, and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
DoCheckPhyState()
void TestThresholdPreambleDetectionWithoutFrameCapture::DoCheckPhyState (WifiPhyState expectedState) private
Check the PHY state now.
Parameters
expectedState the expected PHY state
Definition at line 150 of file wifi-phy-reception-test.cc.
References ns3::PointerValue::Get(), ns3::ObjectBase::GetAttribute(), ns3::WifiPhyStateHelper::GetState(), m_phy, ns3::Now(), NS_LOG_FUNCTION, and NS_TEST_ASSERT_MSG_EQ.
Referenced by CheckPhyState().
DoRun()
void TestThresholdPreambleDetectionWithoutFrameCapture::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 206 of file wifi-phy-reception-test.cc.
References ns3::WifiPhy::AssignStreams(), CCA_BUSY, CheckPhyState(), CheckRxPacketCount(), IDLE, m_phy, ns3::MicroSeconds(), ns3::NanoSeconds(), RX, ns3::Seconds(), and SendPacket().
DoSetup()
void TestThresholdPreambleDetectionWithoutFrameCapture::DoSetup (void) protected virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test setup before DoRun is invoked.
Reimplemented from ns3::TestCase.
Definition at line 188 of file wifi-phy-reception-test.cc.
References CHANNEL_NUMBER, ns3::SpectrumWifiPhy::ConfigureStandard(), FREQUENCY, m_phy, ns3::MakeCallback(), RxFailure(), RxSuccess(), ns3::ObjectBase::SetAttribute(), ns3::SpectrumWifiPhy::SetChannelNumber(), ns3::WifiPhy::SetErrorRateModel(), ns3::SpectrumWifiPhy::SetFrequency(), ns3::WifiPhy::SetPreambleDetectionModel(), ns3::WifiPhy::SetReceiveErrorCallback(), ns3::WifiPhy::SetReceiveOkCallback(), and ns3::WIFI_PHY_STANDARD_80211ax_5GHZ.
RxFailure()
void TestThresholdPreambleDetectionWithoutFrameCapture::RxFailure (Ptr< WifiPsdu > psdu) protected
Spectrum wifi receive failure function.
Parameters
psdu the PSDU
Definition at line 176 of file wifi-phy-reception-test.cc.
References m_countRxFailure, and NS_LOG_FUNCTION.
Referenced by DoSetup().
RxSuccess()
void TestThresholdPreambleDetectionWithoutFrameCapture::RxSuccess (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector, std::vector< bool > statusPerMpdu) protected
Spectrum wifi receive success function.
Parameters
psdu the PSDU
snr the SNR
txVector the transmit vector
statusPerMpdu reception status per MPDU
Definition at line 169 of file wifi-phy-reception-test.cc.
References m_countRxSuccess, and NS_LOG_FUNCTION.
Referenced by DoSetup().
SendPacket()
void TestThresholdPreambleDetectionWithoutFrameCapture::SendPacket (double rxPowerDbm) protected
Send packet function.
Parameters
rxPowerDbm the transmit power in dBm
Definition at line 116 of file wifi-phy-reception-test.cc.
References ns3::WifiPhy::CalculateTxDuration(), CHANNEL_WIDTH, ns3::lorawan::DbmToW(), ns3::SpectrumSignalParameters::duration, FREQUENCY, ns3::WifiPhy::GetFrequency(), ns3::WifiPsdu::GetSize(), GUARD_WIDTH, m_phy, ns3::WifiSpectrumSignalParameters::ppdu, ns3::SpectrumSignalParameters::psd, ns3::WifiMacHeader::SetQosTid(), ns3::WifiMacHeader::SetType(), ns3::SpectrumWifiPhy::StartRx(), ns3::SpectrumSignalParameters::txPhy, ns3::WIFI_MAC_QOSDATA, and ns3::WIFI_PREAMBLE_HE_SU.
Referenced by DoRun().
Member Data Documentation
m_countRxFailure
uint32_t TestThresholdPreambleDetectionWithoutFrameCapture::m_countRxFailure protected
count RX failure
Definition at line 85 of file wifi-phy-reception-test.cc.
Referenced by CheckRxPacketCount(), and RxFailure().
m_countRxSuccess
uint32_t TestThresholdPreambleDetectionWithoutFrameCapture::m_countRxSuccess protected
count RX success
Definition at line 84 of file wifi-phy-reception-test.cc.
Referenced by CheckRxPacketCount(), and RxSuccess().
m_phy
Ptr<SpectrumWifiPhy> TestThresholdPreambleDetectionWithoutFrameCapture::m_phy protected
Phy.
Definition at line 65 of file wifi-phy-reception-test.cc.
Referenced by ~TestThresholdPreambleDetectionWithoutFrameCapture(), DoCheckPhyState(), DoRun(), DoSetup(), and SendPacket().
The documentation for this class was generated from the following file:
src/wifi/test/wifi-phy-reception-test.cc