ns-3: ns3::tests::CommandLineTestCaseBase Class Reference
ns3::tests::CommandLineTestCaseBase Class Reference
Test suites | Core » Core module tests » CommandLine test suite
Public Member Functions
CommandLineTestCaseBase (std::string description)
Constructor.
virtual ~CommandLineTestCaseBase ()
Destructor.
void Parse (CommandLine &cmd, int n,...)
Exercise the CommandLine with the provided arguments.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Static Public Attributes
static int m_count = 0
Test iteration counter to give each test a unique name.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
A test base class that drives Command Line parsing
Definition at line 54 of file command-line-test-suite.cc.
Constructor & Destructor Documentation
CommandLineTestCaseBase()
ns3::tests::CommandLineTestCaseBase::CommandLineTestCaseBase (std::string description)
Constructor.
Parameters
description purpose of this TestCase
Definition at line 81 of file command-line-test-suite.cc.
~CommandLineTestCaseBase()
virtual ns3::tests::CommandLineTestCaseBase::~CommandLineTestCaseBase () inline virtual
Destructor.
Definition at line 64 of file command-line-test-suite.cc.
Member Function Documentation
Parse()
void ns3::tests::CommandLineTestCaseBase::Parse (CommandLine & cmd, int n, ...)
Exercise the CommandLine with the provided arguments.
Parameters
cmd the configured CommandLine
n the number of arguments
Definition at line 86 of file command-line-test-suite.cc.
References second::cmd, ns3::TestCase::GetName(), ns3::TestCase::GetParent(), m_count, and sample-rng-plot::n.
Referenced by ns3::tests::CommandLineBooleanTestCase::DoRun(), ns3::tests::CommandLineIntTestCase::DoRun(), ns3::tests::CommandLineUnsignedIntTestCase::DoRun(), ns3::tests::CommandLineStringTestCase::DoRun(), ns3::tests::CommandLineOrderTestCase::DoRun(), ns3::tests::CommandLineInvalidTestCase::DoRun(), and ns3::tests::CommandLineNonOptionTestCase::DoRun().
Member Data Documentation
m_count
int ns3::tests::CommandLineTestCaseBase::m_count = 0 static
Test iteration counter to give each test a unique name.
Definition at line 76 of file command-line-test-suite.cc.
Referenced by Parse().
The documentation for this class was generated from the following file:
src/core/test/command-line-test-suite.cc