ns-3: ns3::LteSignalingRadioBearerInfo Class Reference
ns3::LteSignalingRadioBearerInfo Class Reference
store information on active signaling radio bearer instance
#include "lte-radio-bearer-info.h"
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::LteRadioBearerInfo
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Public Attributes
LteRrcSap::LogicalChannelConfig m_logicalChannelConfig
logical channel config
uint8_t m_srbIdentity
SRB indentity.
Public Attributes inherited from ns3::LteRadioBearerInfo
Ptr< LtePdcp > m_pdcp
PDCP.
Ptr< LteRlc > m_rlc
RLC.
Additional Inherited Members
Public Member Functions inherited from ns3::LteRadioBearerInfo
LteRadioBearerInfo (void)
virtual ~LteRadioBearerInfo (void)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
store information on active signaling radio bearer instance
Definition at line 60 of file lte-radio-bearer-info.h.
Member Function Documentation
GetTypeId()
TypeId ns3::LteSignalingRadioBearerInfo::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 92 of file lte-radio-bearer-info.cc.
References ns3::TypeId::ATTR_GET, ns3::LteRadioBearerInfo::m_pdcp, ns3::LteRadioBearerInfo::m_rlc, m_srbIdentity, ns3::MakePointerAccessor(), ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
Member Data Documentation
m_logicalChannelConfig
LteRrcSap::LogicalChannelConfig ns3::LteSignalingRadioBearerInfo::m_logicalChannelConfig
logical channel config
Definition at line 71 of file lte-radio-bearer-info.h.
m_srbIdentity
uint8_t ns3::LteSignalingRadioBearerInfo::m_srbIdentity
SRB indentity.
Definition at line 70 of file lte-radio-bearer-info.h.
Referenced by GetTypeId().
The documentation for this class was generated from the following files:
src/lte/model/lte-radio-bearer-info.h
src/lte/model/lte-radio-bearer-info.cc