ns-3: ns3::IntegerValue Class Reference
ns3::IntegerValue Class Reference
Hold a signed integer type.
#include "integer.h"
Public Member Functions
IntegerValue ()
IntegerValue (const int64_t &value)
virtual Ptr< AttributeValue > Copy (void) const
virtual bool DeserializeFromString (std::string value, Ptr< const AttributeChecker > checker)
int64_t Get (void) const
template<typename T >
bool GetAccessor (T &value) const
virtual std::string SerializeToString (Ptr< const AttributeChecker > checker) const
void Set (const int64_t &value)
Public Member Functions inherited from ns3::AttributeValue
AttributeValue ()
virtual ~AttributeValue ()
Public Member Functions inherited from ns3::SimpleRefCount< AttributeValue >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
int64_t m_value
Detailed Description
Hold a signed integer type.
This class can be used to hold variables of signed integer type such as int8_t, int16_t, int32_t, int64_t, or, int, etc.
Definition at line 44 of file integer.h.
Constructor & Destructor Documentation
IntegerValue() [1/2]
ns3::IntegerValue::IntegerValue ()
Definition at line 35 of file integer.cc.
IntegerValue() [2/2]
ns3::IntegerValue::IntegerValue (const int64_t & value)
Definition at line 35 of file integer.cc.
Member Function Documentation
Copy()
Ptr< AttributeValue > ns3::IntegerValue::Copy (void) const virtual
Returns
a deep copy of this class, wrapped into an Attribute object.
Implements ns3::AttributeValue.
Definition at line 35 of file integer.cc.
DeserializeFromString()
bool ns3::IntegerValue::DeserializeFromString (std::string value, Ptr< const AttributeChecker > checker) virtual
Parameters
[in] value A string representation of the value
[in] checker A pointer to the checker associated to the attribute.
Returns
true if the input string was correctly-formatted and could be successfully deserialized, false otherwise.
Upon return of this function, this AttributeValue instance contains the deserialized value. In most cases, this method will not make any use of the checker argument. However, in a very limited set of cases, the checker argument is needed to perform proper serialization. A nice example of code which needs it is the EnumValue::SerializeToString code.
Implements ns3::AttributeValue.
Definition at line 35 of file integer.cc.
Get()
int64_t ns3::IntegerValue::Get (void) const
Definition at line 35 of file integer.cc.
Referenced by IntegerTraceSourceAttributeTestCase::DoRun(), ns3::tests::RootNamespaceConfigTestCase::DoRun(), ns3::tests::UnderRootNamespaceConfigTestCase::DoRun(), ns3::tests::ObjectVectorConfigTestCase::DoRun(), ns3::tests::SearchAttributesOfParentObjectsTestCase::DoRun(), and ns3::internal::MakeIntegerChecker().
GetAccessor()
template<typename T > bool ns3::IntegerValue::GetAccessor (T & value) const inline
Definition at line 44 of file integer.h.
SerializeToString()
std::string ns3::IntegerValue::SerializeToString (Ptr< const AttributeChecker > checker) const virtual
Parameters
[in] checker The checker associated to the attribute
Returns
A string representation of this value.
In most cases, this method will not make any use of the checker argument. However, in a very limited set of cases, the checker argument is needed to perform proper serialization. A nice example of code which needs it is the EnumValue::SerializeToString code.
Implements ns3::AttributeValue.
Definition at line 35 of file integer.cc.
Set()
void ns3::IntegerValue::Set (const int64_t & value)
Definition at line 35 of file integer.cc.
Member Data Documentation
m_value
int64_t ns3::IntegerValue::m_value private
Definition at line 44 of file integer.h.
The documentation for this class was generated from the following files:
src/core/model/integer.h
src/core/model/integer.cc