ns-3: ns3::SixLowPanHelper Class Reference
ns3::SixLowPanHelper Class Reference
6LoWPAN
Setup a sixlowpan stack to be used as a shim between IPv6 and a generic NetDevice.
#include "sixlowpan-helper.h"
Public Member Functions
SixLowPanHelper ()
int64_t AssignStreams (NetDeviceContainer c, int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
NetDeviceContainer Install (NetDeviceContainer c)
Install the SixLoWPAN stack on top of an existing NetDevice.
void SetDeviceAttribute (std::string n1, const AttributeValue &v1)
Set an attribute on each ns3::SixlowpanNetDevice created by SixlowpanHelper::Install.
Private Attributes
ObjectFactory m_deviceFactory
Object factory.
Detailed Description
Setup a sixlowpan stack to be used as a shim between IPv6 and a generic NetDevice.
Definition at line 38 of file sixlowpan-helper.h.
Constructor & Destructor Documentation
SixLowPanHelper()
ns3::SixLowPanHelper::SixLowPanHelper ()
Definition at line 34 of file sixlowpan-helper.cc.
References m_deviceFactory, NS_LOG_FUNCTION, and ns3::ObjectFactory::SetTypeId().
Member Function Documentation
AssignStreams()
int64_t ns3::SixLowPanHelper::AssignStreams (NetDeviceContainer c, int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned. The Install() method should have previously been called by the user.
Parameters
[in] c NetDeviceContainer of the set of net devices for which the SixLowPanNetDevice should be modified to use a fixed stream.
[in] stream First stream index to use.
Returns
The number of stream indices assigned by this helper.
Definition at line 69 of file sixlowpan-helper.cc.
References ns3::NetDeviceContainer::Begin(), and ns3::NetDeviceContainer::End().
Install()
NetDeviceContainer ns3::SixLowPanHelper::Install (NetDeviceContainer c)
Install the SixLoWPAN stack on top of an existing NetDevice.
This function requires a set of properly configured NetDevices passed in as the parameter "c". The new NetDevices will have to be used instead of the original ones. In this way these SixLoWPAN devices will behave as shims between the NetDevices passed in and IPv6.
Note that only IPv6 (and related protocols, such as ICMPv6) can be transmitted over a 6LoWPAN interface. Any other protocol (e.g., IPv4) will be discarded by 6LoWPAN.
Other protocols (e.g., IPv4) could be used on the original NetDevices with some limitations. See the manual for a complete discussion.
Note
IPv6 stack must be installed after SixLoWPAN, using the SixLoWPAN NetDevices. See the example in the examples directory.
Parameters
[in] c The NetDevice container.
Returns
A container with the newly created SixLowPanNetDevices.
Definition at line 47 of file sixlowpan-helper.cc.
References ns3::NetDeviceContainer::Add(), ns3::Node::AddDevice(), ns3::ObjectFactory::Create(), ns3::NetDeviceContainer::Get(), ns3::Node::GetId(), ns3::NetDeviceContainer::GetN(), m_deviceFactory, NS_ASSERT_MSG(), NS_LOG_FUNCTION, and NS_LOG_LOGIC().
Referenced by UanExperiment::SetupCommunications().
SetDeviceAttribute()
void ns3::SixLowPanHelper::SetDeviceAttribute (std::string n1, const AttributeValue & v1)
Set an attribute on each ns3::SixlowpanNetDevice created by SixlowpanHelper::Install.
Parameters
n1 [in] The name of the attribute to set.
v1 [in] The value of the attribute to set.
Definition at line 40 of file sixlowpan-helper.cc.
References m_deviceFactory, NS_LOG_FUNCTION, and ns3::ObjectFactory::Set().
Member Data Documentation
m_deviceFactory
ObjectFactory ns3::SixLowPanHelper::m_deviceFactory private
Object factory.
Definition at line 96 of file sixlowpan-helper.h.
Referenced by SixLowPanHelper(), Install(), and SetDeviceAttribute().
The documentation for this class was generated from the following files:
src/sixlowpan/helper/sixlowpan-helper.h
src/sixlowpan/helper/sixlowpan-helper.cc