ns-3: ProbeTestCase1 Class Reference
ProbeTestCase1 Class Reference
Public Member Functions
ProbeTestCase1 ()
virtual ~ProbeTestCase1 ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void TraceSink (std::string context, double oldValue, double newValue)
Private Attributes
uint32_t m_objectProbed
uint32_t m_pathProbed
Ptr< SampleEmitter > m_s
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 72 of file double-probe-test-suite.cc.
Constructor & Destructor Documentation
ProbeTestCase1()
ProbeTestCase1::ProbeTestCase1 ()
Definition at line 86 of file double-probe-test-suite.cc.
~ProbeTestCase1()
ProbeTestCase1::~ProbeTestCase1 () virtual
Definition at line 93 of file double-probe-test-suite.cc.
Member Function Documentation
DoRun()
void ProbeTestCase1::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 116 of file double-probe-test-suite.cc.
References ns3::DoubleProbe::ConnectByObject(), ns3::DoubleProbe::ConnectByPath(), ns3::DataCollectionObject::GetName(), m_objectProbed, m_pathProbed, m_s, ns3::MakeCallback(), NS_TEST_ASSERT_MSG_GT, ns3::Seconds(), ns3::ObjectBase::SetAttribute(), ns3::DataCollectionObject::SetName(), SampleEmitter::Start(), ns3::ObjectBase::TraceConnect(), and TraceSink().
TraceSink()
void ProbeTestCase1::TraceSink (std::string context, double oldValue, double newValue) private
Definition at line 98 of file double-probe-test-suite.cc.
References SampleEmitter::GetValue(), m_objectProbed, m_pathProbed, m_s, ns3::Now(), NS_TEST_ASSERT_MSG_EQ_TOL, NS_TEST_ASSERT_MSG_GT, NS_TEST_ASSERT_MSG_LT, and ns3::Seconds().
Referenced by DoRun().
Member Data Documentation
m_objectProbed
uint32_t ProbeTestCase1::m_objectProbed private
Definition at line 81 of file double-probe-test-suite.cc.
Referenced by DoRun(), and TraceSink().
m_pathProbed
uint32_t ProbeTestCase1::m_pathProbed private
Definition at line 82 of file double-probe-test-suite.cc.
Referenced by DoRun(), and TraceSink().
m_s
Ptr<SampleEmitter> ProbeTestCase1::m_s private
Definition at line 83 of file double-probe-test-suite.cc.
Referenced by DoRun(), and TraceSink().
The documentation for this class was generated from the following file:
src/stats/test/double-probe-test-suite.cc