ns-3: ReceivePathTest Class Reference
ReceivePathTest Class Reference
Public Member Functions
ReceivePathTest ()
virtual ~ReceivePathTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void Interference (Ptr< const Packet > packet, uint32_t node)
void NoMoreDemodulators (Ptr< const Packet > packet, uint32_t node)
void OccupiedReceptionPaths (int oldValue, int newValue)
void ReceivedPacket (Ptr< const Packet > packet, uint32_t node)
void Reset (void)
Private Attributes
double frequency1 = 868.1
double frequency2 = 868.3
double frequency3 = 868.5
double frequency4 = 868.7
Ptr< SimpleGatewayLoraPhy > gatewayPhy
int m_interferenceCalls = 0
int m_maxOccupiedReceptionPaths = 0
int m_noMoreDemodulatorsCalls = 0
int m_receivedPacketCalls = 0
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 352 of file lorawan-test-suite.cc.
Constructor & Destructor Documentation
ReceivePathTest()
ReceivePathTest::ReceivePathTest ()
Definition at line 379 of file lorawan-test-suite.cc.
~ReceivePathTest()
ReceivePathTest::~ReceivePathTest () virtual
Definition at line 385 of file lorawan-test-suite.cc.
Member Function Documentation
DoRun()
void ReceivePathTest::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 455 of file lorawan-test-suite.cc.
References frequency1, frequency2, frequency3, frequency4, gatewayPhy, ns3::Hours(), m_interferenceCalls, m_maxOccupiedReceptionPaths, m_noMoreDemodulatorsCalls, m_receivedPacketCalls, ns3::NanoSeconds(), NS_LOG_DEBUG, NS_TEST_EXPECT_MSG_EQ, Reset(), and ns3::Seconds().
Interference()
void ReceivePathTest::Interference (Ptr< const Packet > packet, uint32_t node) private
Definition at line 437 of file lorawan-test-suite.cc.
References m_interferenceCalls, and NS_LOG_FUNCTION.
Referenced by Reset().
NoMoreDemodulators()
void ReceivePathTest::NoMoreDemodulators (Ptr< const Packet > packet, uint32_t node) private
Definition at line 429 of file lorawan-test-suite.cc.
References m_noMoreDemodulatorsCalls, and NS_LOG_FUNCTION.
Referenced by Reset().
OccupiedReceptionPaths()
void ReceivePathTest::OccupiedReceptionPaths (int oldValue, int newValue) private
Definition at line 418 of file lorawan-test-suite.cc.
References m_maxOccupiedReceptionPaths, and NS_LOG_FUNCTION.
Referenced by Reset().
ReceivedPacket()
void ReceivePathTest::ReceivedPacket (Ptr< const Packet > packet, uint32_t node) private
Definition at line 445 of file lorawan-test-suite.cc.
References m_receivedPacketCalls, and NS_LOG_FUNCTION.
Referenced by Reset().
Reset()
void ReceivePathTest::Reset (void) private
Definition at line 390 of file lorawan-test-suite.cc.
References ns3::lorawan::GatewayLoraPhy::AddReceptionPath(), frequency1, frequency2, frequency3, gatewayPhy, Interference(), m_interferenceCalls, m_maxOccupiedReceptionPaths, m_noMoreDemodulatorsCalls, m_receivedPacketCalls, ns3::MakeCallback(), NoMoreDemodulators(), OccupiedReceptionPaths(), ReceivedPacket(), and ns3::ObjectBase::TraceConnectWithoutContext().
Referenced by DoRun().
Member Data Documentation
frequency1
double ReceivePathTest::frequency1 = 868.1 private
Definition at line 374 of file lorawan-test-suite.cc.
Referenced by DoRun(), and Reset().
frequency2
double ReceivePathTest::frequency2 = 868.3 private
Definition at line 375 of file lorawan-test-suite.cc.
Referenced by DoRun(), and Reset().
frequency3
double ReceivePathTest::frequency3 = 868.5 private
Definition at line 376 of file lorawan-test-suite.cc.
Referenced by DoRun(), and Reset().
frequency4
double ReceivePathTest::frequency4 = 868.7 private
Definition at line 377 of file lorawan-test-suite.cc.
Referenced by DoRun().
gatewayPhy
Ptr<SimpleGatewayLoraPhy> ReceivePathTest::gatewayPhy private
Definition at line 368 of file lorawan-test-suite.cc.
Referenced by DoRun(), and Reset().
m_interferenceCalls
int ReceivePathTest::m_interferenceCalls = 0 private
Definition at line 370 of file lorawan-test-suite.cc.
Referenced by DoRun(), Interference(), and Reset().
m_maxOccupiedReceptionPaths
int ReceivePathTest::m_maxOccupiedReceptionPaths = 0 private
Definition at line 372 of file lorawan-test-suite.cc.
Referenced by DoRun(), OccupiedReceptionPaths(), and Reset().
m_noMoreDemodulatorsCalls
int ReceivePathTest::m_noMoreDemodulatorsCalls = 0 private
Definition at line 369 of file lorawan-test-suite.cc.
Referenced by DoRun(), NoMoreDemodulators(), and Reset().
m_receivedPacketCalls
int ReceivePathTest::m_receivedPacketCalls = 0 private
Definition at line 371 of file lorawan-test-suite.cc.
Referenced by DoRun(), ReceivedPacket(), and Reset().
The documentation for this class was generated from the following file:
src/lorawan/test/lorawan-test-suite.cc