ns-3: ns3::RandomBuildingPositionAllocator Class Reference
ns3::RandomBuildingPositionAllocator Class Reference
Allocate each position by randomly choosing a building from the list of all buildings, and then randomly choosing a position inside the building.
#include "building-position-allocator.h"
Public Member Functions
RandomBuildingPositionAllocator ()
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
virtual Vector GetNext (void) const
Public Member Functions inherited from ns3::PositionAllocator
PositionAllocator ()
virtual ~PositionAllocator ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::PositionAllocator
static TypeId GetTypeId (void)
Register this type with the TypeId system.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
std::vector< Ptr< Building > > m_buildingListWithoutReplacement
Ptr< UniformRandomVariable > m_rand
Provides uniform random variables.
bool m_withReplacement
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Allocate each position by randomly choosing a building from the list of all buildings, and then randomly choosing a position inside the building.
Definition at line 40 of file building-position-allocator.h.
Constructor & Destructor Documentation
RandomBuildingPositionAllocator()
ns3::RandomBuildingPositionAllocator::RandomBuildingPositionAllocator ()
Definition at line 46 of file building-position-allocator.cc.
References m_rand.
Member Function Documentation
AssignStreams()
int64_t ns3::RandomBuildingPositionAllocator::AssignStreams (int64_t stream) virtual
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Implements ns3::PositionAllocator.
Definition at line 103 of file building-position-allocator.cc.
References m_rand, and ns3::RandomVariableStream::SetStream().
GetNext()
Vector ns3::RandomBuildingPositionAllocator::GetNext (void) const virtual
Returns
the next chosen position.
This method must be implement in subclasses.
Implements ns3::PositionAllocator.
Definition at line 70 of file building-position-allocator.cc.
References ns3::BuildingList::Begin(), ns3::BuildingList::End(), ns3::BoxValue::Get(), ns3::BuildingList::GetBuilding(), ns3::UniformRandomVariable::GetInteger(), ns3::BuildingList::GetNBuildings(), ns3::UniformRandomVariable::GetValue(), m_buildingListWithoutReplacement, m_rand, m_withReplacement, sample-rng-plot::n, NS_ASSERT_MSG(), sample-rng-plot::x, ns3::Box::xMax, ns3::Box::xMin, ns3::Box::yMax, ns3::Box::yMin, ns3::Box::zMax, and ns3::Box::zMin.
GetTypeId()
TypeId ns3::RandomBuildingPositionAllocator::GetTypeId (void) static
Definition at line 52 of file building-position-allocator.cc.
References m_withReplacement, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), and ns3::TypeId::SetParent().
Member Data Documentation
m_buildingListWithoutReplacement
std::vector< Ptr<Building> > ns3::RandomBuildingPositionAllocator::m_buildingListWithoutReplacement mutable private
Definition at line 64 of file building-position-allocator.h.
Referenced by GetNext().
m_rand
Ptr<UniformRandomVariable> ns3::RandomBuildingPositionAllocator::m_rand private
Provides uniform random variables.
Definition at line 67 of file building-position-allocator.h.
Referenced by RandomBuildingPositionAllocator(), AssignStreams(), and GetNext().
m_withReplacement
bool ns3::RandomBuildingPositionAllocator::m_withReplacement private
Definition at line 63 of file building-position-allocator.h.
Referenced by GetNext(), and GetTypeId().
The documentation for this class was generated from the following files:
src/buildings/helper/building-position-allocator.h
src/buildings/helper/building-position-allocator.cc