ns-3: ns3::EndDeviceLoraMac Class Reference
ns3::EndDeviceLoraMac Class Reference
Class representing the MAC layer of a LoRaWAN device.
#include "end-device-lora-mac.h"
Public Member Functions
EndDeviceLoraMac ()
virtual ~EndDeviceLoraMac ()
void AddLogicalChannel (double frequency)
Add a logical channel to the helper.
void AddLogicalChannel (Ptr< LogicalLoraChannel > logicalChannel)
Add a logical channel to the helper.
void AddSubBand (double startFrequency, double endFrequency, double dutyCycle, double maxTxPowerDbm)
Add a subband to the logical channel helper.
void ApplyNecessaryOptions (LoraFrameHeader &frameHeader)
Add the necessary options and MAC commands to the LoraFrameHeader.
void ApplyNecessaryOptions (LoraMacHeader &macHeader)
Add the necessary options and MAC commands to the LoraMacHeader.
void CloseFirstReceiveWindow (void)
Perform operations needed to close the first receive window.
void CloseSecondReceiveWindow (void)
Perform operations needed to close the second receive window.
double GetAggregatedDutyCycle (void)
Get the aggregated duty cycle.
uint8_t GetDataRate (void)
Get the data rate this end device is set to use.
LoraDeviceAddress GetDeviceAddress (void)
Get the network address of this device.
uint8_t GetFirstReceiveWindowDataRate (void)
Get the Data Rate that will be used in the first receive window.
uint8_t GetRx1DrOffset (void)
Get the value of the RX1DROffset parameter.
uint8_t GetSecondReceiveWindowDataRate (void)
Get the Data Rate that will be used in the second receive window.
double GetSecondReceiveWindowFrequency (void)
Get the frequency that is used for the second receive window.
void OnDevStatusReq (void)
Perform the actions that need to be taken when receiving a DevStatusReq command.
void OnDutyCycleReq (double dutyCycle)
Perform the actions that need to be taken when receiving a DutyCycleReq command.
void OnLinkAdrReq (uint8_t dataRate, uint8_t txPower, std::list< int > enabledChannels, int repetitions)
Perform the actions that need to be taken when receiving a LinkAdrReq command.
void OnLinkCheckAns (uint8_t margin, uint8_t gwCnt)
Perform the actions that need to be taken when receiving a LinkCheckAns command.
void OnNewChannelReq (uint8_t chIndex, double frequency, uint8_t minDataRate, uint8_t maxDataRate)
Perform the actions that need to be taken when receiving a NewChannelReq command.
void OnRxParamSetupReq (uint8_t rx1DrOffset, uint8_t rx2DataRate, double frequency)
Perform the actions that need to be taken when receiving a RxParamSetupReq command.
void OpenFirstReceiveWindow (void)
Perform operations needed to open the first receive window.
void OpenSecondReceiveWindow (void)
Perform operations needed to open the second receive window.
void ParseCommands (LoraFrameHeader frameHeader)
Parse and take action on the commands contained on this FrameHeader.
virtual void Receive (Ptr< Packet const > packet)
Receive a packet.
virtual void Send (Ptr< Packet > packet)
Send a packet.
void SetDataRate (uint8_t dataRate)
Set the data rate this end device will use when transmitting.
void SetDeviceAddress (LoraDeviceAddress address)
Set the network address of this device.
void SetLogicalChannel (uint8_t chIndex, double frequency, uint8_t minDataRate, uint8_t maxDataRate)
Set a new logical channel in the helper.
void SetMType (LoraMacHeader::MType mType)
Set the message type to send when the Send method is called.
void SetRx1DrOffset (uint8_t rx1DrOffset)
Set a value for the RX1DROffset parameter.
void SetSecondReceiveWindowDataRate (uint8_t dataRate)
Set the Data Rate to be used in the second receive window.
void SetSecondReceiveWindowFrequency (double frequencyMHz)
Set the frequency that will be used for the second receive window.
void TxFinished (Ptr< const Packet > packet)
Perform the actions that are required after a packet send.
Public Member Functions inherited from ns3::LoraMac
LoraMac ()
virtual ~LoraMac ()
double GetBandwidthFromDataRate (uint8_t dataRate)
Get the BW corresponding to a data rate, based on this MAC's region.
double GetDbmForTxPower (uint8_t txPower)
Get the transmission power in dBm that corresponds, in this region, to the encoded 8-bit txPower.
Ptr< NetDevice > GetDevice (void)
Get the device this MAC layer is installed on.
LogicalLoraChannelHelper GetLogicalLoraChannelHelper (void)
Get the logical lora channel helper associated with this MAC.
int GetNPreambleSymbols (void)
Get the number of PHY preamble symbols this MAC is set to use.
Ptr< LoraPhy > GetPhy (void)
Get the underlying PHY layer.
uint8_t GetSfFromDataRate (uint8_t dataRate)
Get the SF corresponding to a data rate, based on this MAC's region.
void SetBandwidthForDataRate (std::vector< double > bandwidthForDataRate)
Set the vector to use to check up correspondence between bandwidth and DataRate.
void SetDevice (Ptr< NetDevice > device)
Set the device this MAC layer is installed on.
void SetLogicalLoraChannelHelper (LogicalLoraChannelHelper helper)
Set the LogicalLoraChannelHelper this MAC instance will use.
void SetMaxAppPayloadForDataRate (std::vector< uint32_t > maxAppPayloadForDataRate)
Set the maximum App layer payload for a set DataRate.
void SetNPreambleSymbols (int nPreambleSymbols)
Set the number of PHY preamble symbols this MAC is set to use.
void SetPhy (Ptr< LoraPhy > phy)
Set the underlying PHY layer.
void SetReplyDataRateMatrix (ReplyDataRateMatrix replyDataRateMatrix)
Set the matrix to use when deciding with which DataRate to respond.
void SetSfForDataRate (std::vector< uint8_t > sfForDataRate)
Set the vector to use to check up correspondence between SF and DataRate.
void SetTxDbmForTxPower (std::vector< double > txDbmForTxPower)
Set the vector to use to check up which transmission power in Dbm corresponds to a certain TxPower value in this MAC's region.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::LoraMac
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
Ptr< LogicalLoraChannel > GetChannelForTx (void)
Find a suitable channel for transmission.
std::vector< Ptr< LogicalLoraChannel > > Shuffle (std::vector< Ptr< LogicalLoraChannel > > vector)
Randomly shuffle a Ptr<LogicalLoraChannel> vector.
Private Attributes
LoraDeviceAddress m_address
The address of this device.
TracedValue< double > m_aggregatedDutyCycle
The aggregated duty cycle this device needs to respect across all sub-bands.
EventId m_closeWindow
The event of the closing of a receive window.
uint8_t m_codingRate
The coding rate used by this device.
TracedValue< uint8_t > m_dataRate
The DataRate this device is using to transmit.
bool m_headerDisabled
Whether or not the header is disabled for communications by this device.
TracedValue< int > m_lastKnownGatewayCount
The last known gateway count (i.e., gateways that are in communication range with this end device)
TracedValue< double > m_lastKnownLinkMargin
The last known link margin.
std::list< Ptr< MacCommand > > m_macCommandList
List of the MAC commands that need to be applied to the next UL packet.
LoraMacHeader::MType m_mType
The message type to apply to packets sent with the Send method.
Time m_receiveDelay1
The interval between when a packet is done sending and when the first receive window is opened.
Time m_receiveDelay2
The interval between when a packet is done sending and when the second receive window is opened.
Time m_receiveWindowDuration
The duration of a receive window.
uint8_t m_rx1DrOffset
The RX1DROffset parameter value.
EventId m_secondReceiveWindow
The event of the second receive window opening.
uint8_t m_secondReceiveWindowDataRate
The Data Rate to listen for during the second downlink transmission.
double m_secondReceiveWindowFrequency
The frequency to listen on for the second receive window.
TracedValue< double > m_txPower
The transmission power this device is using to transmit.
Ptr< UniformRandomVariable > m_uniformRV
An uniform random variable, used by the Shuffle method to randomly reorder the channel list.
Additional Inherited Members
Public Types inherited from ns3::LoraMac
typedef std::array< std::array< uint8_t, 6 >, 8 > ReplyDataRateMatrix
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::LoraMac
std::vector< double > m_bandwidthForDataRate
A vector holding the bandwidth each Data Rate corresponds to.
TracedCallback< Ptr< const Packet > > m_cannotSendBecauseDutyCycle
The trace source that is fired when a packet cannot be sent because of duty cycle limitations.
LogicalLoraChannelHelper m_channelHelper
The LogicalLoraChannelHelper instance that is assigned to this MAC.
Ptr< NetDevice > m_device
The device this MAC layer is installed on.
std::vector< uint32_t > m_maxAppPayloadForDataRate
A vector holding the maximum app payload size that corresponds to a certain DataRate.
int m_nPreambleSymbols
The number of symbols to use in the PHY preamble.
Ptr< LoraPhy > m_phy
The PHY instance that sits under this MAC layer.
TracedCallback< Ptr< const Packet > > m_receivedPacket
Trace source that is fired when a packet reaches the MAC layer.
ReplyDataRateMatrix m_replyDataRateMatrix
The matrix that decides the DR the GW will use in a reply based on the ED's sending DR and on the value of the RX1DROffset parameter.
std::vector< uint8_t > m_sfForDataRate
A vector holding the SF each Data Rate corresponds to.
std::vector< double > m_txDbmForTxPower
A vector holding the power that corresponds to a certain TxPower value.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Class representing the MAC layer of a LoRaWAN device.
Definition at line 36 of file end-device-lora-mac.h.
Constructor & Destructor Documentation
EndDeviceLoraMac()
ns3::EndDeviceLoraMac::EndDeviceLoraMac ()
Definition at line 72 of file end-device-lora-mac.cc.
References ns3::EventId::Cancel(), m_closeWindow, m_secondReceiveWindow, m_uniformRV, and NS_LOG_FUNCTION.
~EndDeviceLoraMac()
ns3::EndDeviceLoraMac::~EndDeviceLoraMac () virtual
Definition at line 102 of file end-device-lora-mac.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
AddLogicalChannel() [1/2]
void ns3::EndDeviceLoraMac::AddLogicalChannel (double frequency)
Add a logical channel to the helper.
Parameters
frequency The channel's center frequency.
Definition at line 831 of file end-device-lora-mac.cc.
References ns3::LogicalLoraChannelHelper::AddChannel(), ns3::LoraMac::m_channelHelper, and NS_LOG_FUNCTION.
AddLogicalChannel() [2/2]
void ns3::EndDeviceLoraMac::AddLogicalChannel (Ptr< LogicalLoraChannel > logicalChannel)
Add a logical channel to the helper.
Parameters
frequency The channel's center frequency.
Definition at line 839 of file end-device-lora-mac.cc.
References ns3::LogicalLoraChannelHelper::AddChannel(), ns3::LoraMac::m_channelHelper, and NS_LOG_FUNCTION.
AddSubBand()
void ns3::EndDeviceLoraMac::AddSubBand (double startFrequency, double endFrequency, double dutyCycle, double maxTxPowerDbm)
Add a subband to the logical channel helper.
Parameters
startFrequency The SubBand's lowest frequency.
endFrequency The SubBand's highest frequency.
dutyCycle The SubBand's duty cycle, in fraction form.
maxTxPowerDbm The maximum transmission power allowed on the SubBand.
Definition at line 858 of file end-device-lora-mac.cc.
References ns3::LogicalLoraChannelHelper::AddSubBand(), ns3::LoraMac::m_channelHelper, and NS_LOG_FUNCTION_NOARGS.
ApplyNecessaryOptions() [1/2]
void ns3::EndDeviceLoraMac::ApplyNecessaryOptions (LoraFrameHeader & frameHeader)
Add the necessary options and MAC commands to the LoraFrameHeader.
Parameters
frameHeader The frame header on which to apply the options.
Definition at line 371 of file end-device-lora-mac.cc.
References frameHeader, ns3::MacCommand::GetCIDFromMacCommand(), m_address, m_macCommandList, NS_LOG_FUNCTION_NOARGS, and NS_LOG_INFO.
Referenced by Send().
ApplyNecessaryOptions() [2/2]
void ns3::EndDeviceLoraMac::ApplyNecessaryOptions (LoraMacHeader & macHeader)
Add the necessary options and MAC commands to the LoraMacHeader.
Parameters
macHeader The mac header on which to apply the options.
Definition at line 398 of file end-device-lora-mac.cc.
References m_mType, macHeader, and NS_LOG_FUNCTION_NOARGS.
CloseFirstReceiveWindow()
void ns3::EndDeviceLoraMac::CloseFirstReceiveWindow (void)
Perform operations needed to close the first receive window.
Definition at line 446 of file end-device-lora-mac.cc.
References ns3::LoraMac::m_phy, NS_ABORT_MSG, NS_LOG_FUNCTION_NOARGS, third::phy, ns3::EndDeviceLoraPhy::RX, ns3::EndDeviceLoraPhy::SLEEP, ns3::EndDeviceLoraPhy::STANDBY, and ns3::EndDeviceLoraPhy::TX.
Referenced by OpenFirstReceiveWindow().
CloseSecondReceiveWindow()
void ns3::EndDeviceLoraMac::CloseSecondReceiveWindow (void)
Perform operations needed to close the second receive window.
Definition at line 507 of file end-device-lora-mac.cc.
References ns3::LoraMac::m_phy, NS_LOG_FUNCTION_NOARGS, third::phy, ns3::EndDeviceLoraPhy::RX, ns3::EndDeviceLoraPhy::SLEEP, ns3::EndDeviceLoraPhy::STANDBY, and ns3::EndDeviceLoraPhy::TX.
Referenced by OpenSecondReceiveWindow().
GetAggregatedDutyCycle()
double ns3::EndDeviceLoraMac::GetAggregatedDutyCycle (void)
Get the aggregated duty cycle.
Returns
A time instance containing the aggregated duty cycle in fractional form.
Definition at line 896 of file end-device-lora-mac.cc.
References m_aggregatedDutyCycle, and NS_LOG_FUNCTION_NOARGS.
GetChannelForTx()
Ptr< LogicalLoraChannel > ns3::EndDeviceLoraMac::GetChannelForTx (void) private
Find a suitable channel for transmission.
The channel is chosen among the ones that are available in the ED's LogicalLoraChannel, based on their duty cycle limitations.
Definition at line 536 of file end-device-lora-mac.cc.
References ns3::LogicalLoraChannelHelper::GetChannelList(), ns3::Time::GetSeconds(), ns3::LogicalLoraChannelHelper::GetWaitingTime(), ns3::LoraMac::m_channelHelper, NS_LOG_DEBUG, NS_LOG_FUNCTION_NOARGS, ns3::Seconds(), and Shuffle().
Referenced by Send().
GetDataRate()
uint8_t ns3::EndDeviceLoraMac::GetDataRate (void)
Get the data rate this end device is set to use.
Returns
The data rate this device uses when transmitting.
Definition at line 606 of file end-device-lora-mac.cc.
References m_dataRate, and NS_LOG_FUNCTION.
GetDeviceAddress()
LoraDeviceAddress ns3::EndDeviceLoraMac::GetDeviceAddress (void)
Get the network address of this device.
Returns
This device's address.
Definition at line 622 of file end-device-lora-mac.cc.
References m_address, and NS_LOG_FUNCTION.
GetFirstReceiveWindowDataRate()
uint8_t ns3::EndDeviceLoraMac::GetFirstReceiveWindowDataRate (void)
Get the Data Rate that will be used in the first receive window.
Returns
The Data Rate
Definition at line 866 of file end-device-lora-mac.cc.
References m_dataRate, ns3::LoraMac::m_replyDataRateMatrix, and m_rx1DrOffset.
Referenced by Send().
GetRx1DrOffset()
uint8_t ns3::EndDeviceLoraMac::GetRx1DrOffset (void)
Get the value of the RX1DROffset parameter.
Returns
The value of the RX1DROffset parameter.
GetSecondReceiveWindowDataRate()
uint8_t ns3::EndDeviceLoraMac::GetSecondReceiveWindowDataRate (void)
Get the Data Rate that will be used in the second receive window.
Returns
The Data Rate
Definition at line 878 of file end-device-lora-mac.cc.
References m_secondReceiveWindowDataRate.
GetSecondReceiveWindowFrequency()
double ns3::EndDeviceLoraMac::GetSecondReceiveWindowFrequency (void)
Get the frequency that is used for the second receive window.
Returns
The frequency, in MHz
Definition at line 890 of file end-device-lora-mac.cc.
References m_secondReceiveWindowFrequency.
GetTypeId()
TypeId ns3::EndDeviceLoraMac::GetTypeId (void) static
Definition at line 34 of file end-device-lora-mac.cc.
References m_aggregatedDutyCycle, m_dataRate, m_lastKnownGatewayCount, m_lastKnownLinkMargin, m_txPower, ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
OnDevStatusReq()
void ns3::EndDeviceLoraMac::OnDevStatusReq (void)
Perform the actions that need to be taken when receiving a DevStatusReq command.
Definition at line 800 of file end-device-lora-mac.cc.
References m_macCommandList, NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by ParseCommands().
OnDutyCycleReq()
void ns3::EndDeviceLoraMac::OnDutyCycleReq (double dutyCycle)
Perform the actions that need to be taken when receiving a DutyCycleReq command.
Parameters
dutyCycle The aggregate duty cycle prescribed by the command, in fraction form.
Definition at line 748 of file end-device-lora-mac.cc.
References m_aggregatedDutyCycle, m_macCommandList, NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by ParseCommands().
OnLinkAdrReq()
void ns3::EndDeviceLoraMac::OnLinkAdrReq (uint8_t dataRate, uint8_t txPower, std::list< int > enabledChannels, int repetitions)
Perform the actions that need to be taken when receiving a LinkAdrReq command.
Parameters
dataRate The data rate value of the command.
txPower The transmission power value of the command.
enabledChannels A list of the enabled channels.
repetitions The number of repetitions prescribed by the command.
Definition at line 639 of file end-device-lora-mac.cc.
References ns3::LoraMac::GetBandwidthFromDataRate(), ns3::LogicalLoraChannelHelper::GetChannelList(), ns3::LoraMac::GetDbmForTxPower(), ns3::LoraMac::GetSfFromDataRate(), ns3::LoraMac::m_channelHelper, m_dataRate, m_macCommandList, m_txPower, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by ParseCommands().
OnLinkCheckAns()
void ns3::EndDeviceLoraMac::OnLinkCheckAns (uint8_t margin, uint8_t gwCnt)
Perform the actions that need to be taken when receiving a LinkCheckAns command.
Parameters
margin The margin value of the command.
gwCnt The gateway count value of the command.
Definition at line 630 of file end-device-lora-mac.cc.
References m_lastKnownGatewayCount, m_lastKnownLinkMargin, and NS_LOG_FUNCTION.
Referenced by ParseCommands().
OnNewChannelReq()
void ns3::EndDeviceLoraMac::OnNewChannelReq (uint8_t chIndex, double frequency, uint8_t minDataRate, uint8_t maxDataRate)
Perform the actions that need to be taken when receiving a NewChannelReq command.
Definition at line 813 of file end-device-lora-mac.cc.
References m_macCommandList, NS_LOG_FUNCTION, NS_LOG_INFO, and SetLogicalChannel().
Referenced by ParseCommands().
OnRxParamSetupReq()
void ns3::EndDeviceLoraMac::OnRxParamSetupReq (uint8_t rx1DrOffset, uint8_t rx2DataRate, double frequency)
Perform the actions that need to be taken when receiving a RxParamSetupReq command.
Parameters
rx1DrOffset The offset to set.
rx2DataRate The data rate to use for the second receive window.
frequency The frequency to use for the second receive window.
Definition at line 764 of file end-device-lora-mac.cc.
References ns3::LoraMac::GetBandwidthFromDataRate(), ns3::LoraMac::GetSfFromDataRate(), m_macCommandList, m_rx1DrOffset, m_secondReceiveWindowDataRate, m_secondReceiveWindowFrequency, NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by ParseCommands().
OpenFirstReceiveWindow()
void ns3::EndDeviceLoraMac::OpenFirstReceiveWindow (void)
Perform operations needed to open the first receive window.
Definition at line 431 of file end-device-lora-mac.cc.
References CloseFirstReceiveWindow(), m_closeWindow, ns3::LoraMac::m_phy, m_receiveWindowDuration, NS_LOG_FUNCTION_NOARGS, and ns3::Simulator::Schedule().
Referenced by TxFinished().
OpenSecondReceiveWindow()
void ns3::EndDeviceLoraMac::OpenSecondReceiveWindow (void)
Perform operations needed to open the second receive window.
Definition at line 474 of file end-device-lora-mac.cc.
References CloseSecondReceiveWindow(), ns3::LoraMac::GetSfFromDataRate(), ns3::EndDeviceLoraPhy::GetState(), m_closeWindow, ns3::LoraMac::m_phy, m_receiveWindowDuration, m_secondReceiveWindowDataRate, m_secondReceiveWindowFrequency, NS_LOG_FUNCTION_NOARGS, NS_LOG_INFO, ns3::EndDeviceLoraPhy::RX, and ns3::Simulator::Schedule().
Referenced by TxFinished().
ParseCommands()
void ns3::EndDeviceLoraMac::ParseCommands (LoraFrameHeader frameHeader)
Parse and take action on the commands contained on this FrameHeader.
Definition at line 260 of file end-device-lora-mac.cc.
References ns3::DEV_STATUS_REQ, ns3::DL_CHANNEL_REQ, ns3::DUTY_CYCLE_REQ, frameHeader, ns3::LINK_ADR_REQ, ns3::LINK_CHECK_ANS, ns3::NEW_CHANNEL_REQ, NS_LOG_DEBUG, NS_LOG_ERROR, NS_LOG_FUNCTION, OnDevStatusReq(), OnDutyCycleReq(), OnLinkAdrReq(), OnLinkCheckAns(), OnNewChannelReq(), OnRxParamSetupReq(), ns3::RX_PARAM_SETUP_REQ, ns3::RX_TIMING_SETUP_REQ, and ns3::TX_PARAM_SETUP_REQ.
Referenced by Receive().
Receive()
void ns3::EndDeviceLoraMac::Receive (Ptr< Packet const > packet) virtual
Receive a packet.
This method is typically registered as a callback in the underlying PHY layer so that it's called when a packet is going up the stack.
Parameters
packet the received packet.
Implements ns3::LoraMac.
Definition at line 212 of file end-device-lora-mac.cc.
References ns3::Simulator::Cancel(), ns3::Packet::Copy(), ns3::LoraFrameHeader::GetAddress(), ns3::LoraMacHeader::IsUplink(), m_address, ns3::LoraMac::m_receivedPacket, m_secondReceiveWindow, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, packet, ParseCommands(), ns3::Packet::RemoveHeader(), and ns3::LoraFrameHeader::SetAsDownlink().
Send()
void ns3::EndDeviceLoraMac::Send (Ptr< Packet > packet) virtual
Send a packet.
The MAC layer of the ED will take care of using the right parameters.
Parameters
packet the packet to send
Implements ns3::LoraMac.
Definition at line 108 of file end-device-lora-mac.cc.
References ns3::LogicalLoraChannelHelper::AddEvent(), ns3::Packet::AddHeader(), ApplyNecessaryOptions(), ns3::LoraTxParameters::bandwidthHz, ns3::LoraTxParameters::codingRate, ns3::LoraTxParameters::crcEnabled, ns3::LogicalLoraChannelHelper::GetAggregatedWaitingTime(), ns3::LoraMac::GetBandwidthFromDataRate(), GetChannelForTx(), GetFirstReceiveWindowDataRate(), ns3::LoraFrameHeader::GetSerializedSize(), ns3::LoraMacHeader::GetSerializedSize(), ns3::LoraMac::GetSfFromDataRate(), ns3::Packet::GetSize(), ns3::LogicalLoraChannelHelper::GetTxPowerForChannel(), ns3::LoraTxParameters::headerDisabled, ns3::EventId::IsExpired(), ns3::LoraTxParameters::lowDataRateOptimizationEnabled, ns3::LoraMac::m_cannotSendBecauseDutyCycle, ns3::LoraMac::m_channelHelper, m_closeWindow, m_codingRate, m_dataRate, m_headerDisabled, ns3::LoraMac::m_maxAppPayloadForDataRate, ns3::LoraMac::m_nPreambleSymbols, ns3::LoraMac::m_phy, m_rx1DrOffset, m_secondReceiveWindow, m_txPower, ns3::LoraTxParameters::nPreamble, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_WARN, packet, ns3::Seconds(), and ns3::LoraTxParameters::sf.
SetDataRate()
void ns3::EndDeviceLoraMac::SetDataRate (uint8_t dataRate)
Set the data rate this end device will use when transmitting.
For End Devices, this value is assumed to be fixed, and can be modified via MAC commands issued by the GW.
Parameters
dataRate The dataRate to use when transmitting.
Definition at line 598 of file end-device-lora-mac.cc.
References m_dataRate, and NS_LOG_FUNCTION.
SetDeviceAddress()
void ns3::EndDeviceLoraMac::SetDeviceAddress (LoraDeviceAddress address)
Set the network address of this device.
Parameters
address The address to set.
Definition at line 614 of file end-device-lora-mac.cc.
References first::address, m_address, and NS_LOG_FUNCTION.
SetLogicalChannel()
void ns3::EndDeviceLoraMac::SetLogicalChannel (uint8_t chIndex, double frequency, uint8_t minDataRate, uint8_t maxDataRate)
Set a new logical channel in the helper.
Parameters
chIndex The channel's new index.
frequency The channel's center frequency.
minDataRate The minimum data rate allowed on the channel.
maxDataRate The maximum data rate allowed on the channel.
Definition at line 847 of file end-device-lora-mac.cc.
References ns3::LoraMac::m_channelHelper, NS_LOG_FUNCTION, and ns3::LogicalLoraChannelHelper::SetChannel().
Referenced by OnNewChannelReq().
SetMType()
void ns3::EndDeviceLoraMac::SetMType (LoraMacHeader::MType mType)
Set the message type to send when the Send method is called.
Definition at line 407 of file end-device-lora-mac.cc.
References m_mType.
SetRx1DrOffset()
void ns3::EndDeviceLoraMac::SetRx1DrOffset (uint8_t rx1DrOffset)
Set a value for the RX1DROffset parameter.
This value decides the offset to use when deciding the DataRate of the downlink transmission during the first receive window from the replyDataRateMatrix.
Parameters
rx1DrOffset The value to set for the offset.
SetSecondReceiveWindowDataRate()
void ns3::EndDeviceLoraMac::SetSecondReceiveWindowDataRate (uint8_t dataRate)
Set the Data Rate to be used in the second receive window.
Parameters
dataRate The Data Rate.
Definition at line 872 of file end-device-lora-mac.cc.
References m_secondReceiveWindowDataRate.
SetSecondReceiveWindowFrequency()
void ns3::EndDeviceLoraMac::SetSecondReceiveWindowFrequency (double frequencyMHz)
Set the frequency that will be used for the second receive window.
Parameters
frequencyMHz the Frequency.
Definition at line 884 of file end-device-lora-mac.cc.
References m_secondReceiveWindowFrequency.
Shuffle()
std::vector< Ptr< LogicalLoraChannel > > ns3::EndDeviceLoraMac::Shuffle (std::vector< Ptr< LogicalLoraChannel > > vector) private
Randomly shuffle a Ptr<LogicalLoraChannel> vector.
Used to pick a random channel on which to send the packet.
Definition at line 576 of file end-device-lora-mac.cc.
References ns3::UniformRandomVariable::GetValue(), m_uniformRV, and NS_LOG_FUNCTION_NOARGS.
Referenced by GetChannelForTx().
TxFinished()
void ns3::EndDeviceLoraMac::TxFinished (Ptr< const Packet > packet) virtual
Perform the actions that are required after a packet send.
This function handles opening of the first receive window.
Implements ns3::LoraMac.
Definition at line 413 of file end-device-lora-mac.cc.
References ns3::LoraMac::m_phy, m_receiveDelay1, m_receiveDelay2, m_secondReceiveWindow, NS_LOG_FUNCTION_NOARGS, OpenFirstReceiveWindow(), OpenSecondReceiveWindow(), and ns3::Simulator::Schedule().
Member Data Documentation
m_address
LoraDeviceAddress ns3::EndDeviceLoraMac::m_address private
The address of this device.
Definition at line 383 of file end-device-lora-mac.h.
Referenced by ApplyNecessaryOptions(), GetDeviceAddress(), Receive(), and SetDeviceAddress().
m_aggregatedDutyCycle
TracedValue<double> ns3::EndDeviceLoraMac::m_aggregatedDutyCycle private
The aggregated duty cycle this device needs to respect across all sub-bands.
Definition at line 425 of file end-device-lora-mac.h.
Referenced by GetAggregatedDutyCycle(), GetTypeId(), and OnDutyCycleReq().
m_closeWindow
EventId ns3::EndDeviceLoraMac::m_closeWindow private
The event of the closing of a receive window.
This Event will be canceled if there's a successful reception of a packet.
Definition at line 370 of file end-device-lora-mac.h.
Referenced by EndDeviceLoraMac(), OpenFirstReceiveWindow(), OpenSecondReceiveWindow(), and Send().
m_codingRate
uint8_t ns3::EndDeviceLoraMac::m_codingRate private
The coding rate used by this device.
Definition at line 341 of file end-device-lora-mac.h.
Referenced by Send().
m_dataRate
TracedValue<uint8_t> ns3::EndDeviceLoraMac::m_dataRate private
The DataRate this device is using to transmit.
Definition at line 331 of file end-device-lora-mac.h.
Referenced by GetDataRate(), GetFirstReceiveWindowDataRate(), GetTypeId(), OnLinkAdrReq(), Send(), and SetDataRate().
m_headerDisabled
bool ns3::EndDeviceLoraMac::m_headerDisabled private
Whether or not the header is disabled for communications by this device.
Definition at line 346 of file end-device-lora-mac.h.
Referenced by Send().
m_lastKnownGatewayCount
TracedValue<int> ns3::EndDeviceLoraMac::m_lastKnownGatewayCount private
The last known gateway count (i.e., gateways that are in communication range with this end device)
This value is obtained (and updated) when a LinkCheckAns Mac command is received.
Definition at line 415 of file end-device-lora-mac.h.
Referenced by GetTypeId(), and OnLinkCheckAns().
m_lastKnownLinkMargin
TracedValue<double> ns3::EndDeviceLoraMac::m_lastKnownLinkMargin private
The last known link margin.
This value is obtained (and updated) when a LinkCheckAns Mac command is received.
Definition at line 406 of file end-device-lora-mac.h.
Referenced by GetTypeId(), and OnLinkCheckAns().
m_macCommandList
std::list<Ptr<MacCommand> > ns3::EndDeviceLoraMac::m_macCommandList private
List of the MAC commands that need to be applied to the next UL packet.
Definition at line 420 of file end-device-lora-mac.h.
Referenced by ApplyNecessaryOptions(), OnDevStatusReq(), OnDutyCycleReq(), OnLinkAdrReq(), OnNewChannelReq(), and OnRxParamSetupReq().
m_mType
LoraMacHeader::MType ns3::EndDeviceLoraMac::m_mType private
The message type to apply to packets sent with the Send method.
Definition at line 430 of file end-device-lora-mac.h.
Referenced by ApplyNecessaryOptions(), and SetMType().
m_receiveDelay1
Time ns3::EndDeviceLoraMac::m_receiveDelay1 private
The interval between when a packet is done sending and when the first receive window is opened.
Definition at line 352 of file end-device-lora-mac.h.
Referenced by TxFinished().
m_receiveDelay2
Time ns3::EndDeviceLoraMac::m_receiveDelay2 private
The interval between when a packet is done sending and when the second receive window is opened.
Definition at line 358 of file end-device-lora-mac.h.
Referenced by TxFinished().
m_receiveWindowDuration
Time ns3::EndDeviceLoraMac::m_receiveWindowDuration private
The duration of a receive window.
Definition at line 363 of file end-device-lora-mac.h.
Referenced by OpenFirstReceiveWindow(), and OpenSecondReceiveWindow().
m_rx1DrOffset
uint8_t ns3::EndDeviceLoraMac::m_rx1DrOffset private
The RX1DROffset parameter value.
Definition at line 398 of file end-device-lora-mac.h.
Referenced by GetFirstReceiveWindowDataRate(), OnRxParamSetupReq(), and Send().
m_secondReceiveWindow
EventId ns3::EndDeviceLoraMac::m_secondReceiveWindow private
The event of the second receive window opening.
This Event is used to cancel the second window in case the first one is successful.
Definition at line 378 of file end-device-lora-mac.h.
Referenced by EndDeviceLoraMac(), Receive(), Send(), and TxFinished().
m_secondReceiveWindowDataRate
uint8_t ns3::EndDeviceLoraMac::m_secondReceiveWindowDataRate private
The Data Rate to listen for during the second downlink transmission.
Definition at line 393 of file end-device-lora-mac.h.
Referenced by GetSecondReceiveWindowDataRate(), OnRxParamSetupReq(), OpenSecondReceiveWindow(), and SetSecondReceiveWindowDataRate().
m_secondReceiveWindowFrequency
double ns3::EndDeviceLoraMac::m_secondReceiveWindowFrequency private
The frequency to listen on for the second receive window.
Definition at line 388 of file end-device-lora-mac.h.
Referenced by GetSecondReceiveWindowFrequency(), OnRxParamSetupReq(), OpenSecondReceiveWindow(), and SetSecondReceiveWindowFrequency().
m_txPower
TracedValue<double> ns3::EndDeviceLoraMac::m_txPower private
The transmission power this device is using to transmit.
Definition at line 336 of file end-device-lora-mac.h.
Referenced by GetTypeId(), OnLinkAdrReq(), and Send().
m_uniformRV
Ptr<UniformRandomVariable> ns3::EndDeviceLoraMac::m_uniformRV private
An uniform random variable, used by the Shuffle method to randomly reorder the channel list.
Definition at line 326 of file end-device-lora-mac.h.
Referenced by EndDeviceLoraMac(), and Shuffle().
The documentation for this class was generated from the following files:
src/lorawan/model/end-device-lora-mac.h
src/lorawan/model/end-device-lora-mac.cc