ns-3: Ns3TcpLossTestCase Class Reference
Ns3TcpLossTestCase Class Reference
Public Member Functions
Ns3TcpLossTestCase ()
Ns3TcpLossTestCase (std::string tcpModel, uint32_t testCase)
virtual ~Ns3TcpLossTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CwndTracer (uint32_t oldval, uint32_t newval)
virtual void DoRun (void)
Implementation to actually run this TestCase.
virtual void DoSetup (void)
Implementation to do any local setup required for this TestCase.
virtual void DoTeardown (void)
Implementation to do any local setup required for this TestCase.
void Ipv4L3Tx (std::string context, Ptr< const Packet > packet, Ptr< Ipv4 > ipv4, uint32_t interface)
void StartFlow (Ptr< Socket > localSocket, Ipv4Address servAddress, uint16_t servPort)
void WriteUntilBufferFull (Ptr< Socket > localSocket, uint32_t txSpace)
Private Attributes
uint32_t m_currentTxBytes
bool m_needToClose
Ptr< OutputStreamWrapper > m_osw
PcapFile m_pcapFile
std::string m_pcapFilename
std::string m_tcpModel
uint32_t m_testCase
uint32_t m_totalTxBytes
bool m_writeLogging
bool m_writeResults
bool m_writeVectors
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 68 of file ns3tcp-loss-test-suite.cc.
Constructor & Destructor Documentation
Ns3TcpLossTestCase() [1/2]
Ns3TcpLossTestCase::Ns3TcpLossTestCase ()
Definition at line 103 of file ns3tcp-loss-test-suite.cc.
Ns3TcpLossTestCase() [2/2]
Ns3TcpLossTestCase::Ns3TcpLossTestCase (std::string tcpModel, uint32_t testCase)
Definition at line 116 of file ns3tcp-loss-test-suite.cc.
~Ns3TcpLossTestCase()
virtual Ns3TcpLossTestCase::~Ns3TcpLossTestCase () inline virtual
Definition at line 73 of file ns3tcp-loss-test-suite.cc.
Member Function Documentation
CwndTracer()
void Ns3TcpLossTestCase::CwndTracer (uint32_t oldval, uint32_t newval) private
Definition at line 230 of file ns3tcp-loss-test-suite.cc.
References ns3::Time::GetSeconds(), ns3::OutputStreamWrapper::GetStream(), m_osw, m_writeLogging, and ns3::Now().
Referenced by DoRun().
DoRun()
void Ns3TcpLossTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 299 of file ns3tcp-loss-test-suite.cc.
References ns3::NodeContainer::Add(), ns3::Ipv4AddressHelper::Assign(), ns3::Socket::Bind(), ns3::Config::Connect(), ns3::Config::ConnectWithoutContext(), ns3::NodeContainer::Create(), ns3::AsciiTraceHelper::CreateFileStream(), CwndTracer(), ns3::AsciiTraceHelperForDevice::EnableAsciiAll(), ns3::PcapHelperForDevice::EnablePcapAll(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::OutputStreamWrapper::GetStream(), ns3::PointToPointHelper::Install(), ns3::InternetStackHelper::InstallAll(), Ipv4L3Tx(), ns3::LOG_LEVEL_ALL, ns3::LOG_LEVEL_DEBUG, ns3::LOG_LEVEL_INFO, ns3::LOG_PREFIX_FUNC, ns3::LogComponentEnable(), ns3::LogComponentEnableAll(), m_osw, m_tcpModel, m_testCase, m_writeLogging, m_writeResults, ns3::MakeCallback(), NS_FATAL_ERROR, ns3::Seconds(), ns3::Ipv4AddressHelper::SetBase(), ns3::PointToPointHelper::SetChannelAttribute(), ns3::Config::SetDefault(), ns3::PointToPointHelper::SetDeviceAttribute(), ns3::ReceiveListErrorModel::SetList(), sink, ns3::ApplicationContainer::Start(), StartFlow(), and ns3::ApplicationContainer::Stop().
DoSetup()
void Ns3TcpLossTestCase::DoSetup (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test setup before DoRun is invoked.
Reimplemented from ns3::TestCase.
Definition at line 130 of file ns3tcp-loss-test-suite.cc.
References ns3::TestCase::CreateDataDirFilename(), ns3::PcapFile::GetDataLinkType(), ns3::PcapFile::Init(), m_pcapFile, m_pcapFilename, m_tcpModel, m_testCase, m_writeVectors, NS_ABORT_MSG_UNLESS, ns3::PcapFile::Open(), PCAP_LINK_TYPE, PCAP_SNAPLEN, and ns3::Config::SetDefault().
DoTeardown()
void Ns3TcpLossTestCase::DoTeardown (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test teardown
Reimplemented from ns3::TestCase.
Definition at line 158 of file ns3tcp-loss-test-suite.cc.
References ns3::PcapFile::Close(), and m_pcapFile.
Ipv4L3Tx()
void Ns3TcpLossTestCase::Ipv4L3Tx (std::string context, Ptr< const Packet > packet, Ptr< Ipv4 > ipv4, uint32_t interface) private
Definition at line 164 of file ns3tcp-loss-test-suite.cc.
References ns3::Packet::Copy(), ns3::Packet::CopyData(), ns3::Time::GetMicroSeconds(), ns3::TestCase::IsStatusSuccess(), m_pcapFile, m_tcpModel, m_testCase, m_writeVectors, ns3::Now(), NS_LOG_DEBUG, NS_LOG_INFO, NS_TEST_EXPECT_MSG_EQ, PCAP_SNAPLEN, ns3::PcapFile::Read(), ns3::Packet::RemoveHeader(), and ns3::PcapFile::Write().
Referenced by DoRun().
StartFlow()
void Ns3TcpLossTestCase::StartFlow (Ptr< Socket > localSocket, Ipv4Address servAddress, uint16_t servPort) private
Definition at line 279 of file ns3tcp-loss-test-suite.cc.
References ns3::Socket::Connect(), ns3::Time::GetSeconds(), ns3::Socket::GetTxAvailable(), m_writeLogging, ns3::MakeCallback(), ns3::Now(), ns3::Socket::SetSendCallback(), and WriteUntilBufferFull().
Referenced by DoRun().
WriteUntilBufferFull()
void Ns3TcpLossTestCase::WriteUntilBufferFull (Ptr< Socket > localSocket, uint32_t txSpace) private
Definition at line 243 of file ns3tcp-loss-test-suite.cc.
References ns3::Socket::Close(), ns3::Time::GetSeconds(), ns3::Socket::GetTxAvailable(), m_currentTxBytes, m_needToClose, m_totalTxBytes, m_writeLogging, min, ns3::Now(), NS_ASSERT, and ns3::Socket::Send().
Referenced by StartFlow().
Member Data Documentation
m_currentTxBytes
uint32_t Ns3TcpLossTestCase::m_currentTxBytes private
Definition at line 87 of file ns3tcp-loss-test-suite.cc.
Referenced by WriteUntilBufferFull().
m_needToClose
bool Ns3TcpLossTestCase::m_needToClose private
Definition at line 91 of file ns3tcp-loss-test-suite.cc.
Referenced by WriteUntilBufferFull().
m_osw
Ptr<OutputStreamWrapper> Ns3TcpLossTestCase::m_osw private
Definition at line 82 of file ns3tcp-loss-test-suite.cc.
Referenced by CwndTracer(), and DoRun().
m_pcapFile
PcapFile Ns3TcpLossTestCase::m_pcapFile private
Definition at line 84 of file ns3tcp-loss-test-suite.cc.
Referenced by DoSetup(), DoTeardown(), and Ipv4L3Tx().
m_pcapFilename
std::string Ns3TcpLossTestCase::m_pcapFilename private
Definition at line 83 of file ns3tcp-loss-test-suite.cc.
Referenced by DoSetup().
m_tcpModel
std::string Ns3TcpLossTestCase::m_tcpModel private
Definition at line 92 of file ns3tcp-loss-test-suite.cc.
Referenced by DoRun(), DoSetup(), and Ipv4L3Tx().
m_testCase
uint32_t Ns3TcpLossTestCase::m_testCase private
Definition at line 85 of file ns3tcp-loss-test-suite.cc.
Referenced by DoRun(), DoSetup(), and Ipv4L3Tx().
m_totalTxBytes
uint32_t Ns3TcpLossTestCase::m_totalTxBytes private
Definition at line 86 of file ns3tcp-loss-test-suite.cc.
Referenced by WriteUntilBufferFull().
m_writeLogging
bool Ns3TcpLossTestCase::m_writeLogging private
Definition at line 90 of file ns3tcp-loss-test-suite.cc.
Referenced by CwndTracer(), DoRun(), StartFlow(), and WriteUntilBufferFull().
m_writeResults
bool Ns3TcpLossTestCase::m_writeResults private
Definition at line 89 of file ns3tcp-loss-test-suite.cc.
Referenced by DoRun().
m_writeVectors
bool Ns3TcpLossTestCase::m_writeVectors private
Definition at line 88 of file ns3tcp-loss-test-suite.cc.
Referenced by DoSetup(), and Ipv4L3Tx().
The documentation for this class was generated from the following file:
src/test/ns3tcp/ns3tcp-loss-test-suite.cc