ns-3: ns3::LteCcmRrcSapUser Class Reference
ns3::LteCcmRrcSapUser Class Reference abstract
Service Access Point (SAP) offered by the eNodeB RRC instance to the component carrier manager (CCM) instance.
#include "lte-ccm-rrc-sap.h"
Public Member Functions
virtual ~LteCcmRrcSapUser ()
virtual void AddLcs (std::vector< LteEnbRrcSapProvider::LogicalChannelConfig > lcConfig)=0
add a new Logical Channel (LC)
virtual uint8_t AddUeMeasReportConfigForComponentCarrier (LteRrcSap::ReportConfigEutra reportConfig)=0
Request a certain reporting configuration to be fulfilled by the UEs attached to the eNodeB entity.
virtual Ptr< UeManager > GetUeManager (uint16_t rnti)=0
Get UE manager by RNTI.
virtual void ReleaseLcs (uint16_t rnti, uint8_t lcid)=0
remove an existing LC
virtual void SetNumberOfComponentCarriers (uint16_t noOfComponentCarriers)=0
Set the number of component carriers.
virtual void TriggerComponentCarrier (uint16_t rnti, uint16_t targetCellId)=0
Instruct the eNodeB RRC entity to prepare a component carrier.
Friends
class LteEnbRrc
allow LteEnbRrc class friend access
Detailed Description
Service Access Point (SAP) offered by the eNodeB RRC instance to the component carrier manager (CCM) instance.
This is the Component Carrier Management SAP User, i.e., the part of the SAP that contains the eNodeB RRC methods called by the CCM.
Definition at line 151 of file lte-ccm-rrc-sap.h.
Constructor & Destructor Documentation
~LteCcmRrcSapUser()
ns3::LteCcmRrcSapUser::~LteCcmRrcSapUser () virtual
Definition at line 32 of file lte-ccm-rrc-sap.cc.
Member Function Documentation
AddLcs()
virtual void ns3::LteCcmRrcSapUser::AddLcs (std::vector< LteEnbRrcSapProvider::LogicalChannelConfig > lcConfig) pure virtual
add a new Logical Channel (LC)
Parameters
lcConfig is a single structure contains logical Channel Id, Logical Channel config and Component Carrier Id
Implemented in ns3::MemberLteCcmRrcSapUser< C >.
AddUeMeasReportConfigForComponentCarrier()
virtual uint8_t ns3::LteCcmRrcSapUser::AddUeMeasReportConfigForComponentCarrier (LteRrcSap::ReportConfigEutra reportConfig) pure virtual
Request a certain reporting configuration to be fulfilled by the UEs attached to the eNodeB entity.
Parameters
reportConfig the UE measurement reporting configuration
Returns
the measurement identity associated with this newly added reporting configuration
The eNodeB RRC entity is expected to configure the same reporting configuration in each of the attached UEs. When later in the simulation a UE measurement report is received from a UE as a result of this configuration, the eNodeB RRC entity shall forward this report to the ComponentCarrier algorithm through the LteCcmRrcSapProvider::ReportUeMeas SAP function.
Note
This function is only valid before the simulation begins.
Implemented in ns3::MemberLteCcmRrcSapUser< C >.
GetUeManager()
virtual Ptr<UeManager> ns3::LteCcmRrcSapUser::GetUeManager (uint16_t rnti) pure virtual
Get UE manager by RNTI.
Parameters
rnti RNTI
Returns
UE manager
Implemented in ns3::MemberLteCcmRrcSapUser< C >.
Referenced by ns3::NoOpComponentCarrierManager::DoReportBufferStatus(), ns3::RrComponentCarrierManager::DoReportBufferStatus(), and ns3::RrComponentCarrierManager::DoUlReceiveMacCe().
ReleaseLcs()
virtual void ns3::LteCcmRrcSapUser::ReleaseLcs (uint16_t rnti, uint8_t lcid) pure virtual
remove an existing LC
Parameters
rnti
lcid
Implemented in ns3::MemberLteCcmRrcSapUser< C >.
SetNumberOfComponentCarriers()
virtual void ns3::LteCcmRrcSapUser::SetNumberOfComponentCarriers (uint16_t noOfComponentCarriers) pure virtual
Set the number of component carriers.
Parameters
noOfComponentCarriers The number of component carriers
Implemented in ns3::MemberLteCcmRrcSapUser< C >.
Referenced by ns3::LteEnbComponentCarrierManager::SetNumberOfComponentCarriers().
TriggerComponentCarrier()
virtual void ns3::LteCcmRrcSapUser::TriggerComponentCarrier (uint16_t rnti, uint16_t targetCellId) pure virtual
Instruct the eNodeB RRC entity to prepare a component carrier.
Parameters
rnti Radio Network Temporary Identity, an integer identifying the UE which shall perform the ComponentCarrier
targetCellId the cell ID of the target eNodeB
This function is used by the ComponentCarrier manager when a decision on component carriers configurations.
The process to produce the decision is up to the implementation of ComponentCarrier algorithm. It is typically based on the reported UE measurements, which are received through the LteCcmRrcSapProvider::ReportUeMeas function.
Implemented in ns3::MemberLteCcmRrcSapUser< C >.
Friends And Related Function Documentation
LteEnbRrc
friend class LteEnbRrc friend
allow LteEnbRrc class friend access
Definition at line 154 of file lte-ccm-rrc-sap.h.
The documentation for this class was generated from the following files:
src/lte/model/lte-ccm-rrc-sap.h
src/lte/model/lte-ccm-rrc-sap.cc