ns-3: ns3::Ipv6FlowProbe Class Reference
ns3::Ipv6FlowProbe Class Reference
Flow Monitor
Class that monitors flows at the IPv6 layer of a Node.
#include "ipv6-flow-probe.h"
Public Types
enum DropReason {
DROP_NO_ROUTE = 0, DROP_TTL_EXPIRE, DROP_BAD_CHECKSUM, DROP_QUEUE,
DROP_QUEUE_DISC, DROP_INTERFACE_DOWN, DROP_ROUTE_ERROR, DROP_UNKNOWN_PROTOCOL,
DROP_UNKNOWN_OPTION, DROP_MALFORMED_HEADER, DROP_FRAGMENT_TIMEOUT, DROP_INVALID_REASON
}
enumeration of possible reasons why a packet may be dropped
Public Types inherited from ns3::FlowProbe
typedef std::map< FlowId, FlowStats > Stats
Container to map FlowId -> FlowStats.
Public Member Functions
Ipv6FlowProbe (Ptr< FlowMonitor > monitor, Ptr< Ipv6FlowClassifier > classifier, Ptr< Node > node)
Constructor.
virtual ~Ipv6FlowProbe ()
Public Member Functions inherited from ns3::FlowProbe
virtual ~FlowProbe ()
void AddPacketDropStats (FlowId flowId, uint32_t packetSize, uint32_t reasonCode)
Add a packet drop data to the flow stats.
void AddPacketStats (FlowId flowId, uint32_t packetSize, Time delayFromFirstProbe)
Add a packet data to the flow stats.
Stats GetStats () const
Get the partial flow statistics stored in this probe.
void SerializeToXmlStream (std::ostream &os, uint16_t indent, uint32_t index) const
Serializes the results to an std::ostream in XML format.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::FlowProbe
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::FlowProbe
FlowProbe (Ptr< FlowMonitor > flowMonitor)
Constructor.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void DropLogger (const Ipv6Header &ipHeader, Ptr< const Packet > ipPayload, Ipv6L3Protocol::DropReason reason, Ptr< Ipv6 > ipv6, uint32_t ifIndex)
Log a packet being dropped.
void ForwardLogger (const Ipv6Header &ipHeader, Ptr< const Packet > ipPayload, uint32_t interface)
Log a packet being forwarded.
void ForwardUpLogger (const Ipv6Header &ipHeader, Ptr< const Packet > ipPayload, uint32_t interface)
Log a packet being received by the destination.
void QueueDiscDropLogger (Ptr< const QueueDiscItem > item)
Log a packet being dropped by a queue disc.
void QueueDropLogger (Ptr< const Packet > ipPayload)
Log a packet being dropped by a queue.
void SendOutgoingLogger (const Ipv6Header &ipHeader, Ptr< const Packet > ipPayload, uint32_t interface)
Log a packet being sent.
Private Attributes
Ptr< Ipv6FlowClassifier > m_classifier
the Ipv6FlowClassifier this probe is associated with
Additional Inherited Members
Protected Attributes inherited from ns3::FlowProbe
Ptr< FlowMonitor > m_flowMonitor
the FlowMonitor instance
Stats m_stats
The flow stats.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Class that monitors flows at the IPv6 layer of a Node.
For each node in the simulation, one instance of the class Ipv4FlowProbe is created to monitor that node. Ipv4FlowProbe accomplishes this by connecting callbacks to trace sources in the Ipv6L3Protocol interface of the node.
Definition at line 42 of file ipv6-flow-probe.h.
Member Enumeration Documentation
DropReason
enum ns3::Ipv6FlowProbe::DropReason
enumeration of possible reasons why a packet may be dropped
Enumerator
DROP_NO_ROUTE
Packet dropped due to missing route to the destination.
DROP_TTL_EXPIRE
Packet dropped due to TTL decremented to zero during IPv4 forwarding.
DROP_BAD_CHECKSUM
Packet dropped due to invalid checksum in the IPv4 header.
DROP_QUEUE
Packet dropped due to queue overflow.
Note: only works for NetDevices that provide a TxQueue attribute of type Queue with a Drop trace source. It currently works with Csma and PointToPoint devices, but not with WiFi or WiMax.
DROP_QUEUE_DISC
Packet dropped by the queue disc.
DROP_INTERFACE_DOWN
Interface is down so can not send packet.
DROP_ROUTE_ERROR
Route error.
DROP_UNKNOWN_PROTOCOL
Unknown L4 protocol.
DROP_UNKNOWN_OPTION
Unknown option.
DROP_MALFORMED_HEADER
Malformed header.
DROP_FRAGMENT_TIMEOUT
Fragment timeout exceeded.
DROP_INVALID_REASON
Fallback reason (no known reason)
Definition at line 58 of file ipv6-flow-probe.h.
Constructor & Destructor Documentation
Ipv6FlowProbe()
ns3::Ipv6FlowProbe::Ipv6FlowProbe (Ptr< FlowMonitor > monitor, Ptr< Ipv6FlowClassifier > classifier, Ptr< Node > node)
Constructor.
Parameters
monitor the FlowMonitor this probe is associated with
classifier the Ipv4FlowClassifier this probe is associated with
node the Node this probe is associated with
Definition at line 193 of file ipv6-flow-probe.cc.
References ns3::Config::ConnectWithoutContext(), DropLogger(), ForwardLogger(), ForwardUpLogger(), ns3::Node::GetId(), ns3::Object::GetObject(), ns3::MakeCallback(), NS_FATAL_ERROR, NS_LOG_FUNCTION, QueueDiscDropLogger(), QueueDropLogger(), and SendOutgoingLogger().
~Ipv6FlowProbe()
ns3::Ipv6FlowProbe::~Ipv6FlowProbe () virtual
Definition at line 248 of file ipv6-flow-probe.cc.
Member Function Documentation
DoDispose()
void ns3::Ipv6FlowProbe::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::FlowProbe.
Definition at line 253 of file ipv6-flow-probe.cc.
References ns3::FlowProbe::DoDispose().
DropLogger()
void ns3::Ipv6FlowProbe::DropLogger (const Ipv6Header & ipHeader, Ptr< const Packet > ipPayload, Ipv6L3Protocol::DropReason reason, Ptr< Ipv6 > ipv6, uint32_t ifIndex) private
Log a packet being dropped.
Parameters
ipHeader IP header
ipPayload IP payload
reason drop reason
ipv6 pointer to the IP object dropping the packet
ifIndex interface index
Definition at line 313 of file ipv6-flow-probe.cc.
References DROP_FRAGMENT_TIMEOUT, ns3::Ipv6L3Protocol::DROP_FRAGMENT_TIMEOUT, DROP_INTERFACE_DOWN, ns3::Ipv6L3Protocol::DROP_INTERFACE_DOWN, DROP_INVALID_REASON, DROP_MALFORMED_HEADER, ns3::Ipv6L3Protocol::DROP_MALFORMED_HEADER, DROP_NO_ROUTE, ns3::Ipv6L3Protocol::DROP_NO_ROUTE, DROP_ROUTE_ERROR, ns3::Ipv6L3Protocol::DROP_ROUTE_ERROR, DROP_TTL_EXPIRE, ns3::Ipv6L3Protocol::DROP_TTL_EXPIRED, DROP_UNKNOWN_OPTION, ns3::Ipv6L3Protocol::DROP_UNKNOWN_OPTION, DROP_UNKNOWN_PROTOCOL, ns3::Ipv6L3Protocol::DROP_UNKNOWN_PROTOCOL, ns3::Ipv6Header::GetDestinationAddress(), ns3::Ipv6FlowProbeTag::GetFlowId(), ns3::Ipv6FlowProbeTag::GetPacketId(), ns3::Ipv6Header::GetSerializedSize(), ns3::FlowProbe::m_flowMonitor, NS_FATAL_ERROR, and NS_LOG_DEBUG.
Referenced by Ipv6FlowProbe().
ForwardLogger()
void ns3::Ipv6FlowProbe::ForwardLogger (const Ipv6Header & ipHeader, Ptr< const Packet > ipPayload, uint32_t interface) private
Log a packet being forwarded.
Parameters
ipHeader IP header
ipPayload IP payload
interface incoming interface
Definition at line 279 of file ipv6-flow-probe.cc.
References ns3::Ipv6FlowProbeTag::GetFlowId(), ns3::Ipv6FlowProbeTag::GetPacketId(), ns3::Ipv6Header::GetSerializedSize(), ns3::FlowProbe::m_flowMonitor, and NS_LOG_DEBUG.
Referenced by Ipv6FlowProbe().
ForwardUpLogger()
void ns3::Ipv6FlowProbe::ForwardUpLogger (const Ipv6Header & ipHeader, Ptr< const Packet > ipPayload, uint32_t interface) private
Log a packet being received by the destination.
Parameters
ipHeader IP header
ipPayload IP payload
interface incoming interface
Definition at line 296 of file ipv6-flow-probe.cc.
References ns3::Ipv6FlowProbeTag::GetFlowId(), ns3::Ipv6FlowProbeTag::GetPacketId(), ns3::Ipv6Header::GetSerializedSize(), ns3::FlowProbe::m_flowMonitor, and NS_LOG_DEBUG.
Referenced by Ipv6FlowProbe().
GetTypeId()
TypeId ns3::Ipv6FlowProbe::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 237 of file ipv6-flow-probe.cc.
References ns3::TypeId::SetParent().
QueueDiscDropLogger()
void ns3::Ipv6FlowProbe::QueueDiscDropLogger (Ptr< const QueueDiscItem > item) private
Log a packet being dropped by a queue disc.
Parameters
item queue disc item
Definition at line 415 of file ipv6-flow-probe.cc.
References DROP_QUEUE_DISC, ns3::Ipv6FlowProbeTag::GetFlowId(), ns3::Ipv6FlowProbeTag::GetPacketId(), ns3::Ipv6FlowProbeTag::GetPacketSize(), ns3::FlowProbe::m_flowMonitor, and NS_LOG_DEBUG.
Referenced by Ipv6FlowProbe().
QueueDropLogger()
void ns3::Ipv6FlowProbe::QueueDropLogger (Ptr< const Packet > ipPayload) private
Log a packet being dropped by a queue.
Parameters
ipPayload IP payload
Definition at line 394 of file ipv6-flow-probe.cc.
References DROP_QUEUE, ns3::Ipv6FlowProbeTag::GetFlowId(), ns3::Ipv6FlowProbeTag::GetPacketId(), ns3::Ipv6FlowProbeTag::GetPacketSize(), ns3::FlowProbe::m_flowMonitor, and NS_LOG_DEBUG.
Referenced by Ipv6FlowProbe().
SendOutgoingLogger()
void ns3::Ipv6FlowProbe::SendOutgoingLogger (const Ipv6Header & ipHeader, Ptr< const Packet > ipPayload, uint32_t interface) private
Log a packet being sent.
Parameters
ipHeader IP header
ipPayload IP payload
interface outgoing interface
Definition at line 259 of file ipv6-flow-probe.cc.
References ns3::Ipv6Header::GetSerializedSize(), m_classifier, ns3::FlowProbe::m_flowMonitor, and NS_LOG_DEBUG.
Referenced by Ipv6FlowProbe().
Member Data Documentation
m_classifier
Ptr<Ipv6FlowClassifier> ns3::Ipv6FlowProbe::m_classifier private
the Ipv6FlowClassifier this probe is associated with
Definition at line 125 of file ipv6-flow-probe.h.
Referenced by SendOutgoingLogger().
The documentation for this class was generated from the following files:
src/flow-monitor/model/ipv6-flow-probe.h
src/flow-monitor/model/ipv6-flow-probe.cc