ns-3: ns3::QueueItem Class Reference
ns3::QueueItem Class Reference
Network » Network Device
Base class to represent items of packet Queues.
#include "queue-item.h"
Public Types
typedef void(* TracedCallback) (Ptr< const QueueItem > item)
TracedCallback signature for Ptr<QueueItem>
enum Uint8Values { IP_DSFIELD }
1-byte fields of the packet whose value can be retrieved, if present
Public Member Functions
QueueItem (Ptr< Packet > p)
Create a queue item containing a packet.
virtual ~QueueItem ()
Ptr< Packet > GetPacket (void) const
virtual uint32_t GetSize (void) const
Use this method (instead of GetPacket ()->GetSize ()) to get the packet size.
virtual bool GetUint8Value (Uint8Values field, uint8_t &value) const
Retrieve the value of a given field from the packet, if present.
virtual void Print (std::ostream &os) const
Print the item contents.
Public Member Functions inherited from ns3::SimpleRefCount< QueueItem >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Member Functions
QueueItem ()
Default constructor.
QueueItem (const QueueItem &)
Copy constructor.
QueueItem & operator= (const QueueItem &)
Assignment operator.
Private Attributes
Ptr< Packet > m_packet
The packet contained in the queue item.
Detailed Description
Base class to represent items of packet Queues.
An item stored in an ns-3 packet Queue contains a packet and possibly other information. An item of the base class only contains a packet. Subclasses can be derived from this base class to allow items to contain additional information.
Definition at line 46 of file queue-item.h.
Member Typedef Documentation
TracedCallback
typedef void(* ns3::QueueItem::TracedCallback) (Ptr< const QueueItem > item)
TracedCallback signature for Ptr<QueueItem>
Parameters
[in] item The queue item.
Definition at line 101 of file queue-item.h.
Member Enumeration Documentation
Uint8Values
enum ns3::QueueItem::Uint8Values
1-byte fields of the packet whose value can be retrieved, if present
Enumerator
IP_DSFIELD
Definition at line 76 of file queue-item.h.
Constructor & Destructor Documentation
QueueItem() [1/3]
ns3::QueueItem::QueueItem (Ptr< Packet > p)
Create a queue item containing a packet.
Parameters
p the packet included in the created item.
Definition at line 29 of file queue-item.cc.
References m_packet, and NS_LOG_FUNCTION.
~QueueItem()
ns3::QueueItem::~QueueItem () virtual
Definition at line 35 of file queue-item.cc.
References m_packet, and NS_LOG_FUNCTION.
QueueItem() [2/3]
ns3::QueueItem::QueueItem () private
Default constructor.
Defined and unimplemented to avoid misuse
QueueItem() [3/3]
ns3::QueueItem::QueueItem (const QueueItem &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Member Function Documentation
GetPacket()
Ptr< Packet > ns3::QueueItem::GetPacket (void) const
Returns
the packet included in this item.
Definition at line 42 of file queue-item.cc.
References m_packet, and NS_LOG_FUNCTION.
Referenced by ns3::ArpQueueDiscItem::AddHeader(), ns3::Ipv4QueueDiscItem::AddHeader(), ns3::Ipv6QueueDiscItem::AddHeader(), CobaltQueueDiscBasicEnqueueDequeue::DoRun(), CoDelQueueDiscBasicEnqueueDequeue::DoRun(), PrioQueueDiscTestCase::DoRun(), FifoQueueDiscTestCase::DoRunFifoTest(), UdpSocketImplTest::GetPriority(), ns3::ArpQueueDiscItem::GetSize(), ns3::Ipv4QueueDiscItem::GetSize(), ns3::Ipv6QueueDiscItem::GetSize(), ns3::Ipv4QueueDiscItem::Hash(), ns3::Ipv6QueueDiscItem::Hash(), ns3::ArpQueueDiscItem::Print(), ns3::Ipv4QueueDiscItem::Print(), ns3::Ipv6QueueDiscItem::Print(), Print(), ns3::QueueDiscItem::Print(), PieQueueDiscTestCase::RunPieTest(), RedQueueDiscTestCase::RunRedTest(), TbfQueueDiscTestCase::RunTbfTest(), ns3::SelectQueueByDSField(), and UdpSocketImplTest::SentPkt().
GetSize()
uint32_t ns3::QueueItem::GetSize (void) const virtual
Use this method (instead of GetPacket ()->GetSize ()) to get the packet size.
Subclasses may keep header and payload separate to allow manipulating the header, so using this method ensures that the correct packet size is returned.
Returns
the size of the packet included in this item.
Reimplemented in ns3::Ipv6QueueDiscItem, ns3::Ipv4QueueDiscItem, and ns3::ArpQueueDiscItem.
Definition at line 49 of file queue-item.cc.
References ns3::Packet::GetSize(), m_packet, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by QueueDiscTracesTestCase::DoRun(), TestCounter::PacketDad(), TestCounter::PacketDbe(), TestCounter::PacketDequeued(), and TestCounter::PacketEnqueued().
GetUint8Value()
bool ns3::QueueItem::GetUint8Value (QueueItem::Uint8Values field, uint8_t & value) const virtual
Retrieve the value of a given field from the packet, if present.
Parameters
field the field whose value has to be retrieved
value the output parameter to store the retrieved value
Returns
true if the requested field is present in the packet, false otherwise.
Reimplemented in ns3::Ipv6QueueDiscItem, and ns3::Ipv4QueueDiscItem.
Definition at line 57 of file queue-item.cc.
References NS_LOG_FUNCTION.
Referenced by WifiAcMappingTest::PacketEnqueuedInQueueDisc(), and ns3::SelectQueueByDSField().
operator=()
QueueItem& ns3::QueueItem::operator= (const QueueItem &) private
Assignment operator.
Defined and unimplemented to avoid misuse
Returns
Print()
void ns3::QueueItem::Print (std::ostream & os) const virtual
Print the item contents.
Parameters
os output stream in which the data should be printed.
Reimplemented in ns3::QueueDiscItem, ns3::Ipv6QueueDiscItem, ns3::Ipv4QueueDiscItem, and ns3::ArpQueueDiscItem.
Definition at line 64 of file queue-item.cc.
References GetPacket().
Referenced by ns3::operator<<().
Member Data Documentation
m_packet
Ptr<Packet> ns3::QueueItem::m_packet private
The packet contained in the queue item.
Definition at line 127 of file queue-item.h.
Referenced by QueueItem(), ~QueueItem(), GetPacket(), and GetSize().
The documentation for this class was generated from the following files:
src/network/utils/queue-item.h
src/network/utils/queue-item.cc