ns-3: ns3::ConstantVelocityMobilityModel Class Reference
ns3::ConstantVelocityMobilityModel Class Reference
Mobility
Mobility model for which the current speed does not change once it has been set and until it is set again explicitly to a new value.
#include "constant-velocity-mobility-model.h"
Public Member Functions
ConstantVelocityMobilityModel ()
Create position located at coordinates (0,0,0) with speed (0,0,0).
virtual ~ConstantVelocityMobilityModel ()
void SetVelocity (const Vector &speed)
Public Member Functions inherited from ns3::MobilityModel
MobilityModel ()
virtual ~MobilityModel ()=0
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
double GetDistanceFrom (Ptr< const MobilityModel > position) const
Vector GetPosition (void) const
double GetRelativeSpeed (Ptr< const MobilityModel > other) const
Vector GetVelocity (void) const
void SetPosition (const Vector &position)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type with the TypeId system.
Static Public Member Functions inherited from ns3::MobilityModel
static TypeId GetTypeId (void)
Register this type with the TypeId system.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual Vector DoGetPosition (void) const
virtual Vector DoGetVelocity (void) const
virtual void DoSetPosition (const Vector &position)
Private Attributes
ConstantVelocityHelper m_helper
helper object for this model
Additional Inherited Members
Public Types inherited from ns3::MobilityModel
typedef void(* TracedCallback) (Ptr< const MobilityModel > model)
TracedCallback signature.
Protected Member Functions inherited from ns3::MobilityModel
void NotifyCourseChange (void) const
Must be invoked by subclasses when the course of the position changes to notify course change listeners.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Mobility model for which the current speed does not change once it has been set and until it is set again explicitly to a new value.
Definition at line 35 of file constant-velocity-mobility-model.h.
Constructor & Destructor Documentation
ConstantVelocityMobilityModel()
ns3::ConstantVelocityMobilityModel::ConstantVelocityMobilityModel ()
Create position located at coordinates (0,0,0) with speed (0,0,0).
Definition at line 36 of file constant-velocity-mobility-model.cc.
~ConstantVelocityMobilityModel()
ns3::ConstantVelocityMobilityModel::~ConstantVelocityMobilityModel () virtual
Definition at line 40 of file constant-velocity-mobility-model.cc.
Member Function Documentation
DoGetPosition()
Vector ns3::ConstantVelocityMobilityModel::DoGetPosition (void) const private virtual
Returns
the current position.
Concrete subclasses of this base class must implement this method.
Implements ns3::MobilityModel.
Definition at line 55 of file constant-velocity-mobility-model.cc.
References ns3::ConstantVelocityHelper::GetCurrentPosition(), m_helper, and ns3::ConstantVelocityHelper::Update().
DoGetVelocity()
Vector ns3::ConstantVelocityMobilityModel::DoGetVelocity (void) const private virtual
Returns
the current velocity.
Concrete subclasses of this base class must implement this method.
Implements ns3::MobilityModel.
Definition at line 67 of file constant-velocity-mobility-model.cc.
References ns3::ConstantVelocityHelper::GetVelocity(), and m_helper.
DoSetPosition()
void ns3::ConstantVelocityMobilityModel::DoSetPosition (const Vector & position) private virtual
Parameters
position the position to set.
Concrete subclasses of this base class must implement this method.
Implements ns3::MobilityModel.
Definition at line 61 of file constant-velocity-mobility-model.cc.
References m_helper, ns3::MobilityModel::NotifyCourseChange(), and ns3::ConstantVelocityHelper::SetPosition().
GetTypeId()
TypeId ns3::ConstantVelocityMobilityModel::GetTypeId (void) static
Register this type with the TypeId system.
Returns
the object TypeId
Definition at line 27 of file constant-velocity-mobility-model.cc.
References ns3::TypeId::SetParent().
SetVelocity()
void ns3::ConstantVelocityMobilityModel::SetVelocity (const Vector & speed)
Parameters
speed the new speed to set.
Set the current speed now to (dx,dy,dz) Unit is meters/s
Definition at line 45 of file constant-velocity-mobility-model.cc.
References m_helper, ns3::MobilityModel::NotifyCourseChange(), ns3::ConstantVelocityHelper::SetVelocity(), ns3::ConstantVelocityHelper::Unpause(), and ns3::ConstantVelocityHelper::Update().
Referenced by ThreeGppShadowingTestCase::RunTest(), and ns3::SetMovement().
Member Data Documentation
m_helper
ConstantVelocityHelper ns3::ConstantVelocityMobilityModel::m_helper private
helper object for this model
Definition at line 61 of file constant-velocity-mobility-model.h.
Referenced by DoGetPosition(), DoGetVelocity(), DoSetPosition(), and SetVelocity().
The documentation for this class was generated from the following files:
src/mobility/model/constant-velocity-mobility-model.h
src/mobility/model/constant-velocity-mobility-model.cc