ns-3: Ipv4DeduplicationTest Class Reference
Ipv4DeduplicationTest Class Reference
Internet » internet module tests | Test suites
IPv4 Deduplication Test.
Public Member Functions
Ipv4DeduplicationTest (bool enable, Time expire=Seconds(1))
virtual void DoRun (void)
Implementation to actually run this TestCase.
void DropPkt (const Ipv4Header &ipHeader, Ptr< const Packet > packet, Ipv4L3Protocol::DropReason reason, Ptr< Ipv4 > ipv4, uint32_t interface)
Register dropped packet.
void ReceivePkt (Ptr< Socket > socket)
Receive data.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Types
enum MODE { ENABLED = 0, DISABLED, DEGENERATE }
Private Member Functions
void CheckDrops (const std::string &name)
Check packet drops.
void CheckPackets (const std::string &name)
Check packet receptions.
void DoSendData (Ptr< Socket > socket, std::string to)
Send data.
void DoSendPacket (Ptr< Socket > socket, Ptr< Packet > packet, std::string to)
Send data.
void SendData (Ptr< Socket > socket, std::string to)
Send data.
void SendPacket (Ptr< Socket > socket, Ptr< Packet > packet, std::string to)
Send data.
Static Private Member Functions
static std::string MakeName (bool enable, Time expire)
Private Attributes
std::map< std::string, uint32_t > m_dropCountMap
Time m_expire
MODE m_mode
std::map< std::string, uint32_t > m_packetCountMap
Static Private Attributes
static const Time DELAY = MilliSeconds (1)
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
IPv4 Deduplication Test.
Tests topology:
   /---- B ----\
A -— | -— D -— E ---- C -—/
This test case counts the number of packets received and dropped at each node across the topology. Every node is configured to forward the multicast packet which originates at node A.
With RFC 6621 de-duplication enabled, one 1 packet is received while some number of duplicate relayed packets are dropped by RFC 6621 at each node.
When RFC6621 is disabled, the original packet has TTL = 4. Multiple packets are received at each node and several packets are dropped due to TTL expiry at each node.
Definition at line 87 of file ipv4-deduplication-test.cc.
Member Enumeration Documentation
MODE
enum Ipv4DeduplicationTest::MODE private
Enumerator
ENABLED
DISABLED
DEGENERATE
Definition at line 132 of file ipv4-deduplication-test.cc.
Constructor & Destructor Documentation
Ipv4DeduplicationTest()
Ipv4DeduplicationTest::Ipv4DeduplicationTest (bool enable, Time expire = Seconds (1))
Definition at line 166 of file ipv4-deduplication-test.cc.
References DEGENERATE, DELAY, DISABLED, m_expire, and m_mode.
Member Function Documentation
CheckDrops()
void Ipv4DeduplicationTest::CheckDrops (const std::string & name) private
Check packet drops.
Parameters
name Node name
Definition at line 437 of file ipv4-deduplication-test.cc.
References DEGENERATE, DISABLED, ENABLED, m_dropCountMap, m_mode, NS_TEST_ASSERT_MSG_NE, and NS_TEST_EXPECT_MSG_EQ.
Referenced by DoRun().
CheckPackets()
void Ipv4DeduplicationTest::CheckPackets (const std::string & name) private
Check packet receptions.
Parameters
name Node name
Definition at line 405 of file ipv4-deduplication-test.cc.
References DEGENERATE, DISABLED, ENABLED, m_mode, m_packetCountMap, NS_TEST_ASSERT_MSG_NE, and NS_TEST_EXPECT_MSG_EQ.
Referenced by DoRun().
DoRun()
void Ipv4DeduplicationTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 266 of file ipv4-deduplication-test.cc.
References ns3::Ipv4ListRoutingHelper::Add(), ns3::Ipv4StaticRoutingHelper::AddMulticastRoute(), ns3::Ipv4AddressHelper::Assign(), third::channel, CheckDrops(), CheckPackets(), ns3::Config::ConnectWithoutContext(), ns3::SocketFactory::CreateSocket(), DELAY, first::devices, DISABLED, DropPkt(), ns3::Object::GetObject(), ns3::Ipv4StaticRoutingHelper::GetStaticRouting(), ns3::SimpleNetDeviceHelper::Install(), ns3::InternetStackHelper::Install(), m_expire, m_mode, m_packetCountMap, ns3::MakeCallback(), ns3::UdpSocket::MulticastJoinGroup(), first::nodes, NS_ASSERT_MSG(), NS_TEST_EXPECT_MSG_EQ, ReceivePkt(), SendData(), ns3::ObjectBase::SetAttribute(), ns3::Ipv4AddressHelper::SetBase(), ns3::Config::SetDefault(), ns3::InternetStackHelper::SetIpv4ArpJitter(), ns3::InternetStackHelper::SetIpv6StackInstall(), and ns3::InternetStackHelper::SetRoutingHelper().
DoSendData()
void Ipv4DeduplicationTest::DoSendData (Ptr< Socket > socket, std::string to) private
Send data.
Parameters
socket The sending socket.
to Destination address.
Definition at line 218 of file ipv4-deduplication-test.cc.
References SendPacket().
Referenced by SendData().
DoSendPacket()
void Ipv4DeduplicationTest::DoSendPacket (Ptr< Socket > socket, Ptr< Packet > packet, std::string to) private
Send data.
Parameters
socket The sending socket.
packet The packet to send.
to Destination address.
Definition at line 224 of file ipv4-deduplication-test.cc.
References NS_TEST_EXPECT_MSG_EQ, and ns3::Socket::SendTo().
Referenced by SendPacket().
DropPkt()
void Ipv4DeduplicationTest::DropPkt (const Ipv4Header & ipHeader, Ptr< const Packet > packet, Ipv4L3Protocol::DropReason reason, Ptr< Ipv4 > ipv4, uint32_t interface)
Register dropped packet.
Parameters
[in] ipHeader IP header
[in] packet Packet that was dropped
[in] reason Reason for dropping packet
[in] ipv4 Ipv4 instance
[in] interface Interface number
Definition at line 195 of file ipv4-deduplication-test.cc.
References DEGENERATE, DISABLED, ENABLED, ns3::Ipv4::GetNetDevice(), m_dropCountMap, m_mode, and NS_TEST_EXPECT_MSG_EQ.
Referenced by DoRun().
MakeName()
std::string Ipv4DeduplicationTest::MakeName (bool enable, Time expire) static private
Definition at line 244 of file ipv4-deduplication-test.cc.
References DELAY, and ns3::Time::ToDouble().
ReceivePkt()
void Ipv4DeduplicationTest::ReceivePkt (Ptr< Socket > socket)
Receive data.
Parameters
[in] socket The receive socket.
Definition at line 181 of file ipv4-deduplication-test.cc.
References ns3::Socket::GetNode(), ns3::Socket::GetRxAvailable(), ns3::Packet::GetSize(), m_packetCountMap, max, NS_ASSERT, and ns3::Socket::Recv().
Referenced by DoRun().
SendData()
void Ipv4DeduplicationTest::SendData (Ptr< Socket > socket, std::string to) private
Send data.
Parameters
socket The sending socket.
to Destination address.
Definition at line 231 of file ipv4-deduplication-test.cc.
References DoSendData().
Referenced by DoRun().
SendPacket()
void Ipv4DeduplicationTest::SendPacket (Ptr< Socket > socket, Ptr< Packet > packet, std::string to) private
Send data.
Parameters
socket The sending socket.
packet The packet to send.
to Destination address.
Definition at line 237 of file ipv4-deduplication-test.cc.
References DoSendPacket(), ns3::Node::GetId(), ns3::Socket::GetNode(), and ns3::MilliSeconds().
Referenced by DoSendData().
Member Data Documentation
DELAY
const Time Ipv4DeduplicationTest::DELAY = MilliSeconds (1) static private
Definition at line 129 of file ipv4-deduplication-test.cc.
Referenced by Ipv4DeduplicationTest(), DoRun(), and MakeName().
m_dropCountMap
std::map<std::string, uint32_t> Ipv4DeduplicationTest::m_dropCountMap private
Definition at line 138 of file ipv4-deduplication-test.cc.
Referenced by CheckDrops(), and DropPkt().
m_expire
Time Ipv4DeduplicationTest::m_expire private
Definition at line 136 of file ipv4-deduplication-test.cc.
Referenced by Ipv4DeduplicationTest(), and DoRun().
m_mode
MODE Ipv4DeduplicationTest::m_mode private
Definition at line 135 of file ipv4-deduplication-test.cc.
Referenced by Ipv4DeduplicationTest(), CheckDrops(), CheckPackets(), DoRun(), and DropPkt().
m_packetCountMap
std::map<std::string, uint32_t> Ipv4DeduplicationTest::m_packetCountMap private
Definition at line 137 of file ipv4-deduplication-test.cc.
Referenced by CheckPackets(), DoRun(), and ReceivePkt().
The documentation for this class was generated from the following file:
src/internet/test/ipv4-deduplication-test.cc