ns-3: AbstractAnimationInterfaceTestCase Class Reference
AbstractAnimationInterfaceTestCase Class Reference abstract
Network Animation » animation module tests | Test suites
Abstract Animation Interface Test Case.
Public Member Functions
AbstractAnimationInterfaceTestCase (std::string name)
Constructor.
virtual ~AbstractAnimationInterfaceTestCase ()
Destructor.
virtual void DoRun (void)
Run unit tests for this class.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Attributes
AnimationInterface * m_anim
animation
NodeContainer m_nodes
the nodes
Private Member Functions
virtual void CheckFileExistence ()
Check file existence.
virtual void CheckLogic ()=0
Check logic function.
virtual void PrepareNetwork ()=0
Prepare network function.
Private Attributes
const char * m_traceFileName
trace file name
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Abstract Animation Interface Test Case.
Definition at line 47 of file netanim-test.cc.
Constructor & Destructor Documentation
AbstractAnimationInterfaceTestCase()
AbstractAnimationInterfaceTestCase::AbstractAnimationInterfaceTestCase (std::string name)
Constructor.
Parameters
name testcase name
Definition at line 86 of file netanim-test.cc.
~AbstractAnimationInterfaceTestCase()
AbstractAnimationInterfaceTestCase::~AbstractAnimationInterfaceTestCase () virtual
Destructor.
Definition at line 91 of file netanim-test.cc.
References m_anim.
Member Function Documentation
CheckFileExistence()
void AbstractAnimationInterfaceTestCase::CheckFileExistence () private virtual
Check file existence.
Definition at line 110 of file netanim-test.cc.
References m_traceFileName, and NS_TEST_ASSERT_MSG_NE.
Referenced by DoRun().
CheckLogic()
virtual void AbstractAnimationInterfaceTestCase::CheckLogic () private pure virtual
Check logic function.
Implemented in AnimationRemainingEnergyTestCase, and AnimationInterfaceTestCase.
Referenced by DoRun().
DoRun()
void AbstractAnimationInterfaceTestCase::DoRun (void) virtual
Run unit tests for this class.
Returns
false if all tests have passed, false otherwise
Implements ns3::TestCase.
Definition at line 97 of file netanim-test.cc.
References CheckFileExistence(), CheckLogic(), m_anim, m_traceFileName, and PrepareNetwork().
PrepareNetwork()
virtual void AbstractAnimationInterfaceTestCase::PrepareNetwork () private pure virtual
Prepare network function.
Implemented in AnimationRemainingEnergyTestCase, and AnimationInterfaceTestCase.
Referenced by DoRun().
Member Data Documentation
m_anim
AnimationInterface* AbstractAnimationInterfaceTestCase::m_anim protected
animation
Definition at line 70 of file netanim-test.cc.
Referenced by ~AbstractAnimationInterfaceTestCase(), AnimationInterfaceTestCase::CheckLogic(), AnimationRemainingEnergyTestCase::CheckLogic(), and DoRun().
m_nodes
NodeContainer AbstractAnimationInterfaceTestCase::m_nodes protected
the nodes
Definition at line 69 of file netanim-test.cc.
Referenced by AnimationRemainingEnergyTestCase::CheckLogic(), AnimationInterfaceTestCase::PrepareNetwork(), and AnimationRemainingEnergyTestCase::PrepareNetwork().
m_traceFileName
const char* AbstractAnimationInterfaceTestCase::m_traceFileName private
trace file name
Definition at line 83 of file netanim-test.cc.
Referenced by CheckFileExistence(), and DoRun().
The documentation for this class was generated from the following file:
src/netanim/test/netanim-test.cc