ns-3: ns3::GtpcIes Class Reference
ns3::GtpcIes Class Reference
#include "epc-gtpc-header.h"
Public Types
enum Cause_t { RESERVED = 0, REQUEST_ACCEPTED = 16 }
Public Member Functions
uint32_t DeserializeBearerContextHeader (Buffer::Iterator &i, uint16_t &length)
uint32_t DeserializeBearerQos (Buffer::Iterator &i, EpsBearer &bearerQos)
uint32_t DeserializeBearerTft (Buffer::Iterator &i, Ptr< EpcTft > epcTft)
uint32_t DeserializeCause (Buffer::Iterator &i, Cause_t &cause)
uint32_t DeserializeEbi (Buffer::Iterator &i, uint8_t &epsBearerId)
uint32_t DeserializeFteid (Buffer::Iterator &i, GtpcHeader::Fteid_t &fteid)
uint32_t DeserializeImsi (Buffer::Iterator &i, uint64_t &imsi)
uint32_t DeserializeUliEcgi (Buffer::Iterator &i, uint32_t &uliEcgi)
uint32_t GetSerializedSizeBearerTft (std::list< EpcTft::PacketFilter > packetFilters) const
uint64_t ReadNtohU40 (Buffer::Iterator &i)
void SerializeBearerContextHeader (Buffer::Iterator &i, uint16_t length) const
void SerializeBearerQos (Buffer::Iterator &i, EpsBearer bearerQos) const
void SerializeBearerTft (Buffer::Iterator &i, std::list< EpcTft::PacketFilter > packetFilters) const
void SerializeCause (Buffer::Iterator &i, Cause_t cause) const
void SerializeEbi (Buffer::Iterator &i, uint8_t epsBearerId) const
void SerializeFteid (Buffer::Iterator &i, GtpcHeader::Fteid_t fteid) const
void SerializeImsi (Buffer::Iterator &i, uint64_t imsi) const
void SerializeUliEcgi (Buffer::Iterator &i, uint32_t uliEcgi) const
void WriteHtonU40 (Buffer::Iterator &i, uint64_t data) const
Public Attributes
const uint32_t serializedSizeBearerContextHeader = 4
const uint32_t serializedSizeBearerQos = 26
const uint32_t serializedSizeCause = 6
const uint32_t serializedSizeEbi = 5
const uint32_t serializedSizeFteid = 13
const uint32_t serializedSizeImsi = 12
const uint32_t serializedSizePacketFilter = 3 + 9 + 9 + 5 + 5 + 3
const uint32_t serializedSizeUliEcgi = 12
Detailed Description
Definition at line 182 of file epc-gtpc-header.h.
Member Enumeration Documentation
Cause_t
enum ns3::GtpcIes::Cause_t
Enumerator
RESERVED
REQUEST_ACCEPTED
Definition at line 185 of file epc-gtpc-header.h.
Member Function Documentation
DeserializeBearerContextHeader()
uint32_t ns3::GtpcIes::DeserializeBearerContextHeader (Buffer::Iterator & i, uint16_t & length)
Definition at line 468 of file epc-gtpc-header.cc.
References NS_ASSERT_MSG(), ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadU8(), and serializedSizeBearerContextHeader.
Referenced by ns3::GtpcCreateSessionRequestMessage::Deserialize(), ns3::GtpcCreateSessionResponseMessage::Deserialize(), ns3::GtpcModifyBearerRequestMessage::Deserialize(), and ns3::GtpcDeleteBearerCommandMessage::Deserialize().
DeserializeBearerQos()
uint32_t ns3::GtpcIes::DeserializeBearerQos (Buffer::Iterator & i, EpsBearer & bearerQos)
Definition at line 312 of file epc-gtpc-header.cc.
References ns3::GbrQosInformation::gbrDl, ns3::EpsBearer::gbrQosInfo, ns3::GbrQosInformation::gbrUl, ns3::GbrQosInformation::mbrDl, ns3::GbrQosInformation::mbrUl, NS_ASSERT_MSG(), ns3::EpsBearer::qci, ns3::Buffer::Iterator::ReadNtohU16(), ReadNtohU40(), ns3::Buffer::Iterator::ReadU8(), and serializedSizeBearerQos.
Referenced by ns3::GtpcCreateSessionRequestMessage::Deserialize(), and ns3::GtpcCreateSessionResponseMessage::Deserialize().
DeserializeBearerTft()
uint32_t ns3::GtpcIes::DeserializeBearerTft (Buffer::Iterator & i, Ptr< EpcTft > epcTft)
Definition at line 362 of file epc-gtpc-header.cc.
References ns3::EpcTft::PacketFilter::direction, GetSerializedSizeBearerTft(), ns3::EpcTft::PacketFilter::localAddress, ns3::EpcTft::PacketFilter::localMask, ns3::EpcTft::PacketFilter::localPortEnd, ns3::EpcTft::PacketFilter::localPortStart, NS_ASSERT_MSG(), ns3::EpcTft::PacketFilter::precedence, ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadNtohU32(), ns3::Buffer::Iterator::ReadU8(), ns3::EpcTft::PacketFilter::remoteAddress, ns3::EpcTft::PacketFilter::remoteMask, ns3::EpcTft::PacketFilter::remotePortEnd, ns3::EpcTft::PacketFilter::remotePortStart, ns3::EpcTft::PacketFilter::typeOfService, and ns3::EpcTft::PacketFilter::typeOfServiceMask.
Referenced by ns3::GtpcCreateSessionRequestMessage::Deserialize(), and ns3::GtpcCreateSessionResponseMessage::Deserialize().
DeserializeCause()
uint32_t ns3::GtpcIes::DeserializeCause (Buffer::Iterator & i, Cause_t & cause)
Definition at line 234 of file epc-gtpc-header.cc.
References NS_ASSERT_MSG(), ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadU8(), and serializedSizeCause.
Referenced by ns3::GtpcCreateSessionResponseMessage::Deserialize(), ns3::GtpcModifyBearerResponseMessage::Deserialize(), and ns3::GtpcDeleteBearerResponseMessage::Deserialize().
DeserializeEbi()
uint32_t ns3::GtpcIes::DeserializeEbi (Buffer::Iterator & i, uint8_t & epsBearerId)
Definition at line 258 of file epc-gtpc-header.cc.
References NS_ASSERT_MSG(), ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadU8(), and serializedSizeEbi.
Referenced by ns3::GtpcCreateSessionRequestMessage::Deserialize(), ns3::GtpcCreateSessionResponseMessage::Deserialize(), ns3::GtpcModifyBearerRequestMessage::Deserialize(), ns3::GtpcDeleteBearerCommandMessage::Deserialize(), ns3::GtpcDeleteBearerRequestMessage::Deserialize(), and ns3::GtpcDeleteBearerResponseMessage::Deserialize().
DeserializeFteid()
uint32_t ns3::GtpcIes::DeserializeFteid (Buffer::Iterator & i, GtpcHeader::Fteid_t & fteid)
Definition at line 443 of file epc-gtpc-header.cc.
References ns3::GtpcHeader::Fteid_t::addr, ns3::GtpcHeader::Fteid_t::interfaceType, NS_ASSERT_MSG(), ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadNtohU32(), ns3::Buffer::Iterator::ReadU8(), serializedSizeFteid, ns3::Ipv4Address::Set(), and ns3::GtpcHeader::Fteid_t::teid.
Referenced by ns3::GtpcCreateSessionRequestMessage::Deserialize(), ns3::GtpcCreateSessionResponseMessage::Deserialize(), and ns3::GtpcModifyBearerRequestMessage::Deserialize().
DeserializeImsi()
uint32_t ns3::GtpcIes::DeserializeImsi (Buffer::Iterator & i, uint64_t & imsi)
Definition at line 210 of file epc-gtpc-header.cc.
References NS_ASSERT_MSG(), ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadNtohU64(), ns3::Buffer::Iterator::ReadU8(), and serializedSizeImsi.
Referenced by ns3::GtpcCreateSessionRequestMessage::Deserialize(), and ns3::GtpcModifyBearerRequestMessage::Deserialize().
DeserializeUliEcgi()
uint32_t ns3::GtpcIes::DeserializeUliEcgi (Buffer::Iterator & i, uint32_t & uliEcgi)
Definition at line 417 of file epc-gtpc-header.cc.
References ns3::Buffer::Iterator::Next(), NS_ASSERT_MSG(), ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadNtohU32(), ns3::Buffer::Iterator::ReadU8(), and serializedSizeUliEcgi.
Referenced by ns3::GtpcCreateSessionRequestMessage::Deserialize(), and ns3::GtpcModifyBearerRequestMessage::Deserialize().
GetSerializedSizeBearerTft()
uint32_t ns3::GtpcIes::GetSerializedSizeBearerTft (std::list< EpcTft::PacketFilter > packetFilters) const
Definition at line 398 of file epc-gtpc-header.cc.
References serializedSizePacketFilter.
Referenced by DeserializeBearerTft(), ns3::GtpcCreateSessionRequestMessage::GetMessageSize(), ns3::GtpcCreateSessionResponseMessage::GetMessageSize(), ns3::GtpcCreateSessionRequestMessage::Serialize(), and ns3::GtpcCreateSessionResponseMessage::Serialize().
ReadNtohU40()
uint64_t ns3::GtpcIes::ReadNtohU40 (Buffer::Iterator & i)
Definition at line 282 of file epc-gtpc-header.cc.
References ns3::Buffer::Iterator::ReadU8().
Referenced by DeserializeBearerQos().
SerializeBearerContextHeader()
void ns3::GtpcIes::SerializeBearerContextHeader (Buffer::Iterator & i, uint16_t length) const
Definition at line 460 of file epc-gtpc-header.cc.
References ns3::Buffer::Iterator::WriteU16(), and ns3::Buffer::Iterator::WriteU8().
Referenced by ns3::GtpcCreateSessionRequestMessage::Serialize(), ns3::GtpcCreateSessionResponseMessage::Serialize(), ns3::GtpcModifyBearerRequestMessage::Serialize(), and ns3::GtpcDeleteBearerCommandMessage::Serialize().
SerializeBearerQos()
void ns3::GtpcIes::SerializeBearerQos (Buffer::Iterator & i, EpsBearer bearerQos) const
Definition at line 298 of file epc-gtpc-header.cc.
References ns3::GbrQosInformation::gbrDl, ns3::EpsBearer::gbrQosInfo, ns3::GbrQosInformation::gbrUl, ns3::GbrQosInformation::mbrDl, ns3::GbrQosInformation::mbrUl, ns3::EpsBearer::qci, ns3::Buffer::Iterator::WriteHtonU16(), WriteHtonU40(), and ns3::Buffer::Iterator::WriteU8().
Referenced by ns3::GtpcCreateSessionRequestMessage::Serialize(), and ns3::GtpcCreateSessionResponseMessage::Serialize().
SerializeBearerTft()
void ns3::GtpcIes::SerializeBearerTft (Buffer::Iterator & i, std::list< EpcTft::PacketFilter > packetFilters) const
Definition at line 330 of file epc-gtpc-header.cc.
References serializedSizePacketFilter, ns3::Buffer::Iterator::WriteHtonU16(), ns3::Buffer::Iterator::WriteHtonU32(), and ns3::Buffer::Iterator::WriteU8().
Referenced by ns3::GtpcCreateSessionRequestMessage::Serialize(), and ns3::GtpcCreateSessionResponseMessage::Serialize().
SerializeCause()
void ns3::GtpcIes::SerializeCause (Buffer::Iterator & i, Cause_t cause) const
Definition at line 224 of file epc-gtpc-header.cc.
References ns3::Buffer::Iterator::WriteHtonU16(), and ns3::Buffer::Iterator::WriteU8().
Referenced by ns3::GtpcCreateSessionResponseMessage::Serialize(), ns3::GtpcModifyBearerResponseMessage::Serialize(), and ns3::GtpcDeleteBearerResponseMessage::Serialize().
SerializeEbi()
void ns3::GtpcIes::SerializeEbi (Buffer::Iterator & i, uint8_t epsBearerId) const
Definition at line 249 of file epc-gtpc-header.cc.
References ns3::Buffer::Iterator::WriteHtonU16(), and ns3::Buffer::Iterator::WriteU8().
Referenced by ns3::GtpcCreateSessionRequestMessage::Serialize(), ns3::GtpcCreateSessionResponseMessage::Serialize(), ns3::GtpcModifyBearerRequestMessage::Serialize(), ns3::GtpcDeleteBearerCommandMessage::Serialize(), ns3::GtpcDeleteBearerRequestMessage::Serialize(), and ns3::GtpcDeleteBearerResponseMessage::Serialize().
SerializeFteid()
void ns3::GtpcIes::SerializeFteid (Buffer::Iterator & i, GtpcHeader::Fteid_t fteid) const
Definition at line 432 of file epc-gtpc-header.cc.
References ns3::GtpcHeader::Fteid_t::addr, ns3::Ipv4Address::Get(), ns3::GtpcHeader::Fteid_t::interfaceType, ns3::GtpcHeader::Fteid_t::teid, ns3::Buffer::Iterator::WriteHtonU16(), ns3::Buffer::Iterator::WriteHtonU32(), and ns3::Buffer::Iterator::WriteU8().
Referenced by ns3::GtpcCreateSessionRequestMessage::Serialize(), ns3::GtpcCreateSessionResponseMessage::Serialize(), and ns3::GtpcModifyBearerRequestMessage::Serialize().
SerializeImsi()
void ns3::GtpcIes::SerializeImsi (Buffer::Iterator & i, uint64_t imsi) const
Definition at line 201 of file epc-gtpc-header.cc.
References ns3::Buffer::Iterator::WriteHtonU16(), ns3::Buffer::Iterator::WriteHtonU64(), and ns3::Buffer::Iterator::WriteU8().
Referenced by ns3::GtpcCreateSessionRequestMessage::Serialize(), and ns3::GtpcModifyBearerRequestMessage::Serialize().
SerializeUliEcgi()
void ns3::GtpcIes::SerializeUliEcgi (Buffer::Iterator & i, uint32_t uliEcgi) const
Definition at line 404 of file epc-gtpc-header.cc.
References ns3::Buffer::Iterator::WriteHtonU16(), ns3::Buffer::Iterator::WriteHtonU32(), and ns3::Buffer::Iterator::WriteU8().
Referenced by ns3::GtpcCreateSessionRequestMessage::Serialize(), and ns3::GtpcModifyBearerRequestMessage::Serialize().
WriteHtonU40()
void ns3::GtpcIes::WriteHtonU40 (Buffer::Iterator & i, uint64_t data) const
Definition at line 272 of file epc-gtpc-header.cc.
References data, and ns3::Buffer::Iterator::WriteU8().
Referenced by SerializeBearerQos().
Member Data Documentation
serializedSizeBearerContextHeader
const uint32_t ns3::GtpcIes::serializedSizeBearerContextHeader = 4
Definition at line 199 of file epc-gtpc-header.h.
Referenced by DeserializeBearerContextHeader(), ns3::GtpcCreateSessionRequestMessage::GetMessageSize(), ns3::GtpcCreateSessionResponseMessage::GetMessageSize(), ns3::GtpcModifyBearerRequestMessage::GetMessageSize(), and ns3::GtpcDeleteBearerCommandMessage::GetMessageSize().
serializedSizeBearerQos
const uint32_t ns3::GtpcIes::serializedSizeBearerQos = 26
Definition at line 194 of file epc-gtpc-header.h.
Referenced by DeserializeBearerQos(), ns3::GtpcCreateSessionRequestMessage::GetMessageSize(), ns3::GtpcCreateSessionResponseMessage::GetMessageSize(), ns3::GtpcCreateSessionRequestMessage::Serialize(), and ns3::GtpcCreateSessionResponseMessage::Serialize().
serializedSizeCause
const uint32_t ns3::GtpcIes::serializedSizeCause = 6
Definition at line 192 of file epc-gtpc-header.h.
Referenced by DeserializeCause(), ns3::GtpcCreateSessionResponseMessage::GetMessageSize(), ns3::GtpcModifyBearerResponseMessage::GetMessageSize(), and ns3::GtpcDeleteBearerResponseMessage::GetMessageSize().
serializedSizeEbi
const uint32_t ns3::GtpcIes::serializedSizeEbi = 5
Definition at line 193 of file epc-gtpc-header.h.
Referenced by DeserializeEbi(), ns3::GtpcCreateSessionRequestMessage::GetMessageSize(), ns3::GtpcCreateSessionResponseMessage::GetMessageSize(), ns3::GtpcModifyBearerRequestMessage::GetMessageSize(), ns3::GtpcDeleteBearerCommandMessage::GetMessageSize(), ns3::GtpcDeleteBearerRequestMessage::GetMessageSize(), ns3::GtpcDeleteBearerResponseMessage::GetMessageSize(), ns3::GtpcCreateSessionRequestMessage::Serialize(), ns3::GtpcCreateSessionResponseMessage::Serialize(), ns3::GtpcModifyBearerRequestMessage::Serialize(), and ns3::GtpcDeleteBearerCommandMessage::Serialize().
serializedSizeFteid
const uint32_t ns3::GtpcIes::serializedSizeFteid = 13
Definition at line 198 of file epc-gtpc-header.h.
Referenced by DeserializeFteid(), ns3::GtpcCreateSessionRequestMessage::GetMessageSize(), ns3::GtpcCreateSessionResponseMessage::GetMessageSize(), ns3::GtpcModifyBearerRequestMessage::GetMessageSize(), ns3::GtpcCreateSessionRequestMessage::Serialize(), ns3::GtpcCreateSessionResponseMessage::Serialize(), and ns3::GtpcModifyBearerRequestMessage::Serialize().
serializedSizeImsi
const uint32_t ns3::GtpcIes::serializedSizeImsi = 12
Definition at line 191 of file epc-gtpc-header.h.
Referenced by DeserializeImsi(), ns3::GtpcCreateSessionRequestMessage::GetMessageSize(), and ns3::GtpcModifyBearerRequestMessage::GetMessageSize().
serializedSizePacketFilter
const uint32_t ns3::GtpcIes::serializedSizePacketFilter = 3 + 9 + 9 + 5 + 5 + 3
Definition at line 195 of file epc-gtpc-header.h.
Referenced by GetSerializedSizeBearerTft(), and SerializeBearerTft().
serializedSizeUliEcgi
const uint32_t ns3::GtpcIes::serializedSizeUliEcgi = 12
Definition at line 197 of file epc-gtpc-header.h.
Referenced by DeserializeUliEcgi(), ns3::GtpcCreateSessionRequestMessage::GetMessageSize(), and ns3::GtpcModifyBearerRequestMessage::GetMessageSize().
The documentation for this class was generated from the following files:
src/lte/model/epc-gtpc-header.h
src/lte/model/epc-gtpc-header.cc