ns-3: ns3::lorawan::LoraRadioEnergyModelHelper Class Reference
ns3::lorawan::LoraRadioEnergyModelHelper Class Reference
Energy Models
Assign LoraRadioEnergyModel to wifi devices.
#include "lora-radio-energy-model-helper.h"
Public Member Functions
LoraRadioEnergyModelHelper ()
Construct a helper which is used to add a radio energy model to a node.
~LoraRadioEnergyModelHelper ()
Destroy a RadioEnergy Helper.
void Set (std::string name, const AttributeValue &v)
void SetTxCurrentModel (std::string name, std::string n0="", const AttributeValue &v0=EmptyAttributeValue(), std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue(), std::string n6="", const AttributeValue &v6=EmptyAttributeValue(), std::string n7="", const AttributeValue &v7=EmptyAttributeValue())
Public Member Functions inherited from ns3::DeviceEnergyModelHelper
virtual ~DeviceEnergyModelHelper ()
DeviceEnergyModelContainer Install (NetDeviceContainer deviceContainer, EnergySourceContainer sourceContainer) const
DeviceEnergyModelContainer Install (Ptr< NetDevice > device, Ptr< EnergySource > source) const
Private Member Functions
virtual Ptr< DeviceEnergyModel > DoInstall (Ptr< NetDevice > device, Ptr< EnergySource > source) const
Private Attributes
ObjectFactory m_radioEnergy
radio energy
ObjectFactory m_txCurrentModel
transmit current model
Detailed Description
Assign LoraRadioEnergyModel to wifi devices.
This installer installs LoraRadioEnergyModel for only LoraNetDevice objects.
Definition at line 36 of file lora-radio-energy-model-helper.h.
Constructor & Destructor Documentation
LoraRadioEnergyModelHelper()
ns3::lorawan::LoraRadioEnergyModelHelper::LoraRadioEnergyModelHelper ()
Construct a helper which is used to add a radio energy model to a node.
Definition at line 28 of file lora-radio-energy-model-helper.cc.
References m_radioEnergy, and ns3::ObjectFactory::SetTypeId().
~LoraRadioEnergyModelHelper()
ns3::lorawan::LoraRadioEnergyModelHelper::~LoraRadioEnergyModelHelper ()
Destroy a RadioEnergy Helper.
Definition at line 33 of file lora-radio-energy-model-helper.cc.
Member Function Documentation
DoInstall()
Ptr< DeviceEnergyModel > ns3::lorawan::LoraRadioEnergyModelHelper::DoInstall (Ptr< NetDevice > device, Ptr< EnergySource > source) const private virtual
Parameters
device Pointer to the NetDevice to install DeviceEnergyModel.
source Pointer to EnergySource to install.
Returns
Ptr<DeviceEnergyModel>
Implements DeviceEnergyModel::Install.
Implements ns3::DeviceEnergyModelHelper.
Definition at line 73 of file lora-radio-energy-model-helper.cc.
References ns3::ObjectFactory::Create(), ns3::Object::GetObject(), ns3::ObjectFactory::GetTypeId(), ns3::TypeId::GetUid(), m_radioEnergy, m_txCurrentModel, NS_ASSERT, and NS_FATAL_ERROR.
Set()
void ns3::lorawan::LoraRadioEnergyModelHelper::Set (std::string name, const AttributeValue & v) virtual
Parameters
name the name of the attribute to set
v the value of the attribute
Sets an attribute of the underlying PHY object.
Implements ns3::DeviceEnergyModelHelper.
Definition at line 38 of file lora-radio-energy-model-helper.cc.
References m_radioEnergy, and ns3::ObjectFactory::Set().
SetTxCurrentModel()
void ns3::lorawan::LoraRadioEnergyModelHelper::SetTxCurrentModel (std::string name, std::string n0 = "", const AttributeValue & v0 = EmptyAttributeValue (), std::string n1 = "", const AttributeValue & v1 = EmptyAttributeValue (), std::string n2 = "", const AttributeValue & v2 = EmptyAttributeValue (), std::string n3 = "", const AttributeValue & v3 = EmptyAttributeValue (), std::string n4 = "", const AttributeValue & v4 = EmptyAttributeValue (), std::string n5 = "", const AttributeValue & v5 = EmptyAttributeValue (), std::string n6 = "", const AttributeValue & v6 = EmptyAttributeValue (), std::string n7 = "", const AttributeValue & v7 = EmptyAttributeValue ())
Parameters
name the name of the model to set
n0 the name of the attribute to set
v0 the value of the attribute to set
n1 the name of the attribute to set
v1 the value of the attribute to set
n2 the name of the attribute to set
v2 the value of the attribute to set
n3 the name of the attribute to set
v3 the value of the attribute to set
n4 the name of the attribute to set
v4 the value of the attribute to set
n5 the name of the attribute to set
v5 the value of the attribute to set
n6 the name of the attribute to set
v6 the value of the attribute to set
n7 the name of the attribute to set
v7 the value of the attribute to set
Configure a Transmission Current model for this EnergySource.
Definition at line 44 of file lora-radio-energy-model-helper.cc.
References m_txCurrentModel, ns3::ObjectFactory::Set(), and ns3::ObjectFactory::SetTypeId().
Member Data Documentation
m_radioEnergy
ObjectFactory ns3::lorawan::LoraRadioEnergyModelHelper::m_radioEnergy private
radio energy
Definition at line 100 of file lora-radio-energy-model-helper.h.
Referenced by LoraRadioEnergyModelHelper(), DoInstall(), and Set().
m_txCurrentModel
ObjectFactory ns3::lorawan::LoraRadioEnergyModelHelper::m_txCurrentModel private
transmit current model
Definition at line 101 of file lora-radio-energy-model-helper.h.
Referenced by DoInstall(), and SetTxCurrentModel().
The documentation for this class was generated from the following files:
src/lorawan/helper/lora-radio-energy-model-helper.h
src/lorawan/helper/lora-radio-energy-model-helper.cc