ns-3: ns3::BulkSendApplication Class Reference
ns3::BulkSendApplication Class Reference
Applications » BulkSendApplication
Send as much traffic as possible, trying to fill the bandwidth.
#include "bulk-send-application.h"
Public Member Functions
BulkSendApplication ()
virtual ~BulkSendApplication ()
Ptr< Socket > GetSocket (void) const
Get the socket this application is attached to.
void SetMaxBytes (uint64_t maxBytes)
Set the upper bound for the total number of bytes to send.
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Application
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void ConnectionFailed (Ptr< Socket > socket)
Connection Failed (called by Socket through a callback)
void ConnectionSucceeded (Ptr< Socket > socket)
Connection Succeeded (called by Socket through a callback)
void DataSend (Ptr< Socket >, uint32_t)
Send more data as soon as some has been transmitted.
void SendData (const Address &from, const Address &to)
Send data until the L4 transmission buffer is full.
virtual void StartApplication (void)
Application specific startup code.
virtual void StopApplication (void)
Application specific shutdown code.
Private Attributes
bool m_connected
True if connected.
bool m_enableE2EStats {false}
Enable or disable the e2e statistic generation.
Address m_local
Local address to bind to.
uint64_t m_maxBytes
Limit total number of bytes sent.
Address m_peer
Peer address.
uint32_t m_sendSize
Size of data to send each time.
uint32_t m_seq {0}
Sequence.
Ptr< Socket > m_socket
Associated socket.
TypeId m_tid
The type of protocol to use.
uint64_t m_totBytes
Total bytes sent so far.
TracedCallback< Ptr< const Packet > > m_txTrace
Traced Callback: sent packets.
TracedCallback< Ptr< const Packet >, const Address &, const Address &, const E2eStatsHeader & > m_txTraceWithStats
Callback for tracing the packet Tx events, includes source, destination, and the packet sent.
Additional Inherited Members
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Send as much traffic as possible, trying to fill the bandwidth.
This traffic generator simply sends data as fast as possible up to MaxBytes or until the application is stopped (if MaxBytes is zero). Once the lower layer send buffer is filled, it waits until space is free to send more data, essentially keeping a constant flow of data. Only SOCK_STREAM and SOCK_SEQPACKET sockets are supported. For example, TCP sockets can be used, but UDP sockets can not be used.
If the attribute "EnableE2EStats" is enabled, the application will use some byte of the payload to store an header with a sequence number, a timestamp, and the size of the packet sent. To get these statistics, please use PacketSink (and enable its "EnableE2EStats" attribute) or extract the header yourself in your application (you can see how PacketSink is working with such headers).
Definition at line 75 of file bulk-send-application.h.
Constructor & Destructor Documentation
BulkSendApplication()
ns3::BulkSendApplication::BulkSendApplication ()
Definition at line 89 of file bulk-send-application.cc.
References NS_LOG_FUNCTION.
~BulkSendApplication()
ns3::BulkSendApplication::~BulkSendApplication () virtual
Definition at line 97 of file bulk-send-application.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
ConnectionFailed()
void ns3::BulkSendApplication::ConnectionFailed (Ptr< Socket > socket) private
Connection Failed (called by Socket through a callback)
Parameters
socket the connected socket
Definition at line 273 of file bulk-send-application.cc.
References NS_LOG_FUNCTION, and NS_LOG_LOGIC().
Referenced by StartApplication().
ConnectionSucceeded()
void ns3::BulkSendApplication::ConnectionSucceeded (Ptr< Socket > socket) private
Connection Succeeded (called by Socket through a callback)
Parameters
socket the connected socket
Definition at line 262 of file bulk-send-application.cc.
References ns3::Socket::GetPeerName(), ns3::Socket::GetSockName(), m_connected, NS_LOG_FUNCTION, NS_LOG_LOGIC(), and SendData().
Referenced by StartApplication().
DataSend()
void ns3::BulkSendApplication::DataSend (Ptr< Socket > socket, uint32_t) private
Send more data as soon as some has been transmitted.
Definition at line 279 of file bulk-send-application.cc.
References ns3::Socket::GetPeerName(), ns3::Socket::GetSockName(), m_connected, NS_LOG_FUNCTION, and SendData().
Referenced by StartApplication().
DoDispose()
void ns3::BulkSendApplication::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Application.
Definition at line 117 of file bulk-send-application.cc.
References ns3::Application::DoDispose(), m_socket, and NS_LOG_FUNCTION.
GetSocket()
Ptr< Socket > ns3::BulkSendApplication::GetSocket (void) const
Get the socket this application is attached to.
Returns
pointer to associated socket
Definition at line 110 of file bulk-send-application.cc.
References m_socket, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::BulkSendApplication::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 42 of file bulk-send-application.cc.
References ns3::TcpSocketFactory::GetTypeId(), m_enableE2EStats, m_local, m_maxBytes, m_peer, m_sendSize, m_tid, m_txTrace, m_txTraceWithStats, ns3::MakeAddressAccessor(), ns3::MakeAddressChecker(), ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeTypeIdAccessor(), ns3::MakeTypeIdChecker(), ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
SendData()
void ns3::BulkSendApplication::SendData (const Address & from, const Address & to) private
Send data until the L4 transmission buffer is full.
Parameters
from From address
to To address
Definition at line 204 of file bulk-send-application.cc.
References ns3::Packet::AddHeader(), ns3::Socket::Close(), ns3::E2eStatsHeader::GetSerializedSize(), m_connected, m_enableE2EStats, m_maxBytes, m_sendSize, m_seq, m_socket, m_totBytes, m_txTrace, m_txTraceWithStats, min, ns3::Simulator::Now(), NS_ABORT_IF, NS_LOG_FUNCTION, NS_LOG_LOGIC(), ns3::Socket::Send(), ns3::SeqTsHeader::SetSeq(), and ns3::E2eStatsHeader::SetSize().
Referenced by ConnectionSucceeded(), DataSend(), and StartApplication().
SetMaxBytes()
void ns3::BulkSendApplication::SetMaxBytes (uint64_t maxBytes)
Set the upper bound for the total number of bytes to send.
Once this bound is reached, no more application bytes are sent. If the application is stopped during the simulation and restarted, the total number of bytes sent is not reset; however, the maxBytes bound is still effective and the application will continue sending up to maxBytes. The value zero for maxBytes means that there is no upper bound; i.e. data is sent until the application or simulation is stopped.
Parameters
maxBytes the upper bound of bytes to send
Definition at line 103 of file bulk-send-application.cc.
References m_maxBytes, and NS_LOG_FUNCTION.
StartApplication()
void ns3::BulkSendApplication::StartApplication (void) private virtual
Application specific startup code.
The StartApplication method is called at the start time specified by Start This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 127 of file bulk-send-application.cc.
References ns3::Socket::Bind(), ns3::Socket::Bind6(), ns3::Socket::Connect(), ConnectionFailed(), ConnectionSucceeded(), ns3::Socket::CreateSocket(), DataSend(), ns3::Application::GetNode(), ns3::Socket::GetSocketType(), ns3::Socket::GetSockName(), ns3::Address::IsInvalid(), ns3::Inet6SocketAddress::IsMatchingType(), ns3::InetSocketAddress::IsMatchingType(), m_connected, m_local, m_peer, m_socket, m_tid, ns3::MakeCallback(), ns3::Socket::NS3_SOCK_SEQPACKET, ns3::Socket::NS3_SOCK_STREAM, NS_ABORT_MSG_IF, NS_FATAL_ERROR, NS_LOG_FUNCTION, SendData(), ns3::Socket::SetConnectCallback(), ns3::Socket::SetSendCallback(), and ns3::Socket::ShutdownRecv().
StopApplication()
void ns3::BulkSendApplication::StopApplication (void) private virtual
Application specific shutdown code.
The StopApplication method is called at the stop time specified by Stop This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 186 of file bulk-send-application.cc.
References ns3::Socket::Close(), m_connected, m_socket, NS_LOG_FUNCTION, and NS_LOG_WARN.
Member Data Documentation
m_connected
bool ns3::BulkSendApplication::m_connected private
True if connected.
Definition at line 126 of file bulk-send-application.h.
Referenced by ConnectionSucceeded(), DataSend(), SendData(), StartApplication(), and StopApplication().
m_enableE2EStats
bool ns3::BulkSendApplication::m_enableE2EStats {false} private
Enable or disable the e2e statistic generation.
Definition at line 132 of file bulk-send-application.h.
Referenced by GetTypeId(), and SendData().
m_local
Address ns3::BulkSendApplication::m_local private
Local address to bind to.
Definition at line 125 of file bulk-send-application.h.
Referenced by GetTypeId(), and StartApplication().
m_maxBytes
uint64_t ns3::BulkSendApplication::m_maxBytes private
Limit total number of bytes sent.
Definition at line 128 of file bulk-send-application.h.
Referenced by GetTypeId(), SendData(), and SetMaxBytes().
m_peer
Address ns3::BulkSendApplication::m_peer private
Peer address.
Definition at line 124 of file bulk-send-application.h.
Referenced by GetTypeId(), and StartApplication().
m_sendSize
uint32_t ns3::BulkSendApplication::m_sendSize private
Size of data to send each time.
Definition at line 127 of file bulk-send-application.h.
Referenced by GetTypeId(), and SendData().
m_seq
uint32_t ns3::BulkSendApplication::m_seq {0} private
Sequence.
Definition at line 131 of file bulk-send-application.h.
Referenced by SendData().
m_socket
Ptr<Socket> ns3::BulkSendApplication::m_socket private
Associated socket.
Definition at line 123 of file bulk-send-application.h.
Referenced by DoDispose(), GetSocket(), SendData(), StartApplication(), and StopApplication().
m_tid
TypeId ns3::BulkSendApplication::m_tid private
The type of protocol to use.
Definition at line 130 of file bulk-send-application.h.
Referenced by GetTypeId(), and StartApplication().
m_totBytes
uint64_t ns3::BulkSendApplication::m_totBytes private
Total bytes sent so far.
Definition at line 129 of file bulk-send-application.h.
Referenced by SendData().
m_txTrace
TracedCallback<Ptr<const Packet> > ns3::BulkSendApplication::m_txTrace private
Traced Callback: sent packets.
Definition at line 136 of file bulk-send-application.h.
Referenced by GetTypeId(), and SendData().
m_txTraceWithStats
TracedCallback<Ptr<const Packet>, const Address &, const Address &, const E2eStatsHeader &> ns3::BulkSendApplication::m_txTraceWithStats private
Callback for tracing the packet Tx events, includes source, destination, and the packet sent.
Definition at line 139 of file bulk-send-application.h.
Referenced by GetTypeId(), and SendData().
The documentation for this class was generated from the following files:
src/applications/model/bulk-send-application.h
src/applications/model/bulk-send-application.cc