ns-3: ns3::CommandPayloadHeader Class Reference
ns3::CommandPayloadHeader Class Reference
LR-WPAN models
#include "lr-wpan-mac-pl-headers.h"
Public Types
enum MacCommand {
ASSOCIATION_REQ = 0x01, ASSOCIATION_RESP = 0x02, DISASSOCIATION_NOTIF = 0x03, DATA_REQ = 0x04,
PANID_CONFLICT = 0x05, ORPHAN_NOTIF = 0x06, BEACON_REQ = 0x07, COOR_REALIGN = 0x08,
GTS_REQ = 0x09, CMD_RESERVED = 0xff
}
The MAC command frames.
Public Member Functions
CommandPayloadHeader (enum MacCommand macCmd)
Constructor.
CommandPayloadHeader (void)
uint32_t Deserialize (Buffer::Iterator start)
MacCommand GetCommandFrameType (void) const
Get the command frame type.
TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint32_t GetSerializedSize (void) const
void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetCommandFrameType (MacCommand macCmd)
Set the command frame type.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_cmdFrameId
The command Frame Identifier.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implements the header for the MAC payload command frame according to the IEEE 802.15.4-2011 Std.
Definition at line 107 of file lr-wpan-mac-pl-headers.h.
Member Enumeration Documentation
MacCommand
enum ns3::CommandPayloadHeader::MacCommand
The MAC command frames.
See IEEE 802.15.4-2011, Table 5
Enumerator
ASSOCIATION_REQ
Association request (RFD true: Tx)
ASSOCIATION_RESP
Association response (RFD true: Rx)
DISASSOCIATION_NOTIF
Disassociation notification (RFD true: TX, Rx)
DATA_REQ
Data Request (RFD true: Tx)
PANID_CONFLICT
Pan ID conflict notification (RFD true: Tx)
ORPHAN_NOTIF
Orphan Notification (RFD true: Tx)
BEACON_REQ
Beacon Request (RFD true: none)
COOR_REALIGN
Coordinator Realignment (RFD true: Rx)
GTS_REQ
GTS Request (RFD true: none)
CMD_RESERVED
Reserved.
Definition at line 115 of file lr-wpan-mac-pl-headers.h.
Constructor & Destructor Documentation
CommandPayloadHeader() [1/2]
ns3::CommandPayloadHeader::CommandPayloadHeader (void)
Definition at line 135 of file lr-wpan-mac-pl-headers.cc.
References CMD_RESERVED, and SetCommandFrameType().
CommandPayloadHeader() [2/2]
ns3::CommandPayloadHeader::CommandPayloadHeader (enum MacCommand macCmd)
Constructor.
Parameters
macCmd the command type of this command header
Definition at line 141 of file lr-wpan-mac-pl-headers.cc.
References SetCommandFrameType().
Member Function Documentation
Deserialize()
uint32_t ns3::CommandPayloadHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 181 of file lr-wpan-mac-pl-headers.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_cmdFrameId, ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetCommandFrameType()
CommandPayloadHeader::MacCommand ns3::CommandPayloadHeader::GetCommandFrameType (void) const
Get the command frame type.
Definition at line 203 of file lr-wpan-mac-pl-headers.cc.
References ASSOCIATION_REQ, ASSOCIATION_RESP, BEACON_REQ, CMD_RESERVED, COOR_REALIGN, DATA_REQ, DISASSOCIATION_NOTIF, GTS_REQ, m_cmdFrameId, ORPHAN_NOTIF, and PANID_CONFLICT.
GetInstanceTypeId()
TypeId ns3::CommandPayloadHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 160 of file lr-wpan-mac-pl-headers.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::CommandPayloadHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 166 of file lr-wpan-mac-pl-headers.cc.
GetTypeId()
TypeId ns3::CommandPayloadHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 149 of file lr-wpan-mac-pl-headers.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::CommandPayloadHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 190 of file lr-wpan-mac-pl-headers.cc.
References m_cmdFrameId.
Serialize()
void ns3::CommandPayloadHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 174 of file lr-wpan-mac-pl-headers.cc.
References m_cmdFrameId, visualizer.core::start(), and ns3::Buffer::Iterator::WriteU8().
SetCommandFrameType()
void ns3::CommandPayloadHeader::SetCommandFrameType (MacCommand macCmd)
Set the command frame type.
Definition at line 196 of file lr-wpan-mac-pl-headers.cc.
References m_cmdFrameId.
Referenced by CommandPayloadHeader().
Member Data Documentation
m_cmdFrameId
uint8_t ns3::CommandPayloadHeader::m_cmdFrameId private
The command Frame Identifier.
Definition at line 159 of file lr-wpan-mac-pl-headers.h.
Referenced by Deserialize(), GetCommandFrameType(), Print(), Serialize(), and SetCommandFrameType().
The documentation for this class was generated from the following files:
src/lr-wpan/model/lr-wpan-mac-pl-headers.h
src/lr-wpan/model/lr-wpan-mac-pl-headers.cc