ns-3: ns3::LteUeRrcSapProvider Class Reference
ns3::LteUeRrcSapProvider Class Reference abstract
Part of the RRC protocol.
#include "lte-rrc-sap.h"
Classes
struct CompleteSetupParameters
CompleteSetupParameters structure.
Public Member Functions
virtual void CompleteSetup (CompleteSetupParameters params)=0
Complete setup function.
virtual void RecvRrcConnectionReconfiguration (RrcConnectionReconfiguration msg)=0
Receive an RRCConnectionReconfiguration message from the serving eNodeB during an RRC connection reconfiguration procedure (Section 5.3.5 of TS 36.331).
virtual void RecvRrcConnectionReestablishment (RrcConnectionReestablishment msg)=0
Receive an RRCConnectionReestablishment message from the serving eNodeB during an RRC connection re-establishment procedure (Section 5.3.7 of TS 36.331).
virtual void RecvRrcConnectionReestablishmentReject (RrcConnectionReestablishmentReject msg)=0
Receive an RRCConnectionReestablishmentReject message from the serving eNodeB during an RRC connection re-establishment procedure (Section 5.3.7 of TS 36.331).
virtual void RecvRrcConnectionReject (RrcConnectionReject msg)=0
Receive an RRCConnectionReject message from the serving eNodeB during an RRC connection establishment procedure (Section 5.3.3 of TS 36.331).
virtual void RecvRrcConnectionRelease (RrcConnectionRelease msg)=0
Receive an RRCConnectionRelease message from the serving eNodeB during an RRC connection release procedure (Section 5.3.8 of TS 36.331).
virtual void RecvRrcConnectionSetup (RrcConnectionSetup msg)=0
Receive an RRCConnectionSetup message from the serving eNodeB during an RRC connection establishment procedure (Section 5.3.3 of TS 36.331).
virtual void RecvSystemInformation (SystemInformation msg)=0
Receive a SystemInformation message from the serving eNodeB during a system information acquisition procedure (Section 5.2.2 of TS 36.331).
Public Member Functions inherited from ns3::LteRrcSap
virtual ~LteRrcSap ()
Additional Inherited Members
Public Types inherited from ns3::LteRrcSap
enum ReestablishmentCause { RECONFIGURATION_FAILURE, HANDOVER_FAILURE, OTHER_FAILURE }
ReestablishmentCause enumeration.
Static Public Member Functions inherited from ns3::LteRrcSap
static double ConvertPdschConfigDedicated2Double (PdschConfigDedicated pdschConfigDedicated)
Convert PDSCH config dedicated function.
Static Public Attributes inherited from ns3::LteRrcSap
static const uint8_t MaxReportCells = 8
Constraint values.
Detailed Description
Part of the RRC protocol.
This Service Access Point (SAP) is used to let the UE RRC receive a message from the eNB RRC. Each method defined in this class corresponds to the reception of a message that is defined in Section 6.2.2 of TS 36.331.
Definition at line 1000 of file lte-rrc-sap.h.
Member Function Documentation
CompleteSetup()
virtual void ns3::LteUeRrcSapProvider::CompleteSetup (CompleteSetupParameters params) pure virtual
Complete setup function.
Parameters
params the complete setup parameters
Implemented in ns3::MemberLteUeRrcSapProvider< C >.
Referenced by ns3::LteUeRrcProtocolReal::DoSetup().
RecvRrcConnectionReconfiguration()
virtual void ns3::LteUeRrcSapProvider::RecvRrcConnectionReconfiguration (RrcConnectionReconfiguration msg) pure virtual
Receive an RRCConnectionReconfiguration message from the serving eNodeB during an RRC connection reconfiguration procedure (Section 5.3.5 of TS 36.331).
Parameters
msg the message
Implemented in ns3::MemberLteUeRrcSapProvider< C >.
Referenced by ns3::LteUeRrcProtocolReal::DoReceivePdcpSdu(), and ns3::LteEnbRrcProtocolIdeal::DoSendRrcConnectionReconfiguration().
RecvRrcConnectionReestablishment()
virtual void ns3::LteUeRrcSapProvider::RecvRrcConnectionReestablishment (RrcConnectionReestablishment msg) pure virtual
Receive an RRCConnectionReestablishment message from the serving eNodeB during an RRC connection re-establishment procedure (Section 5.3.7 of TS 36.331).
Parameters
msg the message
Implemented in ns3::MemberLteUeRrcSapProvider< C >.
Referenced by ns3::LteUeRrcProtocolReal::DoReceivePdcpPdu(), and ns3::LteEnbRrcProtocolIdeal::DoSendRrcConnectionReestablishment().
RecvRrcConnectionReestablishmentReject()
virtual void ns3::LteUeRrcSapProvider::RecvRrcConnectionReestablishmentReject (RrcConnectionReestablishmentReject msg) pure virtual
Receive an RRCConnectionReestablishmentReject message from the serving eNodeB during an RRC connection re-establishment procedure (Section 5.3.7 of TS 36.331).
Parameters
msg the message
Implemented in ns3::MemberLteUeRrcSapProvider< C >.
Referenced by ns3::LteEnbRrcProtocolIdeal::DoSendRrcConnectionReestablishmentReject().
RecvRrcConnectionReject()
virtual void ns3::LteUeRrcSapProvider::RecvRrcConnectionReject (RrcConnectionReject msg) pure virtual
Receive an RRCConnectionReject message from the serving eNodeB during an RRC connection establishment procedure (Section 5.3.3 of TS 36.331).
Parameters
msg the message
Implemented in ns3::MemberLteUeRrcSapProvider< C >.
Referenced by ns3::LteUeRrcProtocolReal::DoReceivePdcpPdu(), and ns3::LteEnbRrcProtocolIdeal::DoSendRrcConnectionReject().
RecvRrcConnectionRelease()
virtual void ns3::LteUeRrcSapProvider::RecvRrcConnectionRelease (RrcConnectionRelease msg) pure virtual
Receive an RRCConnectionRelease message from the serving eNodeB during an RRC connection release procedure (Section 5.3.8 of TS 36.331).
Parameters
msg the message
Implemented in ns3::MemberLteUeRrcSapProvider< C >.
Referenced by ns3::LteEnbRrcProtocolIdeal::DoSendRrcConnectionRelease().
RecvRrcConnectionSetup()
virtual void ns3::LteUeRrcSapProvider::RecvRrcConnectionSetup (RrcConnectionSetup msg) pure virtual
Receive an RRCConnectionSetup message from the serving eNodeB during an RRC connection establishment procedure (Section 5.3.3 of TS 36.331).
Parameters
msg the message
Implemented in ns3::MemberLteUeRrcSapProvider< C >.
Referenced by ns3::LteUeRrcProtocolReal::DoReceivePdcpPdu(), and ns3::LteEnbRrcProtocolIdeal::DoSendRrcConnectionSetup().
RecvSystemInformation()
virtual void ns3::LteUeRrcSapProvider::RecvSystemInformation (SystemInformation msg) pure virtual
Receive a SystemInformation message from the serving eNodeB during a system information acquisition procedure (Section 5.2.2 of TS 36.331).
Parameters
msg the message
Implemented in ns3::MemberLteUeRrcSapProvider< C >.
Referenced by ns3::LteEnbRrcProtocolIdeal::DoSendSystemInformation(), and ns3::LteEnbRrcProtocolReal::DoSendSystemInformation().
The documentation for this class was generated from the following file:
src/lte/model/lte-rrc-sap.h