ns-3: ns3::LteSpectrumValueCatcher Class Reference
ns3::LteSpectrumValueCatcher Class Reference
A sink to be plugged to the callback of LteChunkProcessor allowing to save and later retrieve the latest reported value.
#include "lte-chunk-processor.h"
Public Member Functions
Ptr< SpectrumValue > GetValue ()
void ReportValue (const SpectrumValue &value)
function to be plugged to LteChunkProcessor::AddCallback ()
Private Attributes
Ptr< SpectrumValue > m_value
spectrum value
Detailed Description
A sink to be plugged to the callback of LteChunkProcessor allowing to save and later retrieve the latest reported value.
Definition at line 103 of file lte-chunk-processor.h.
Member Function Documentation
GetValue()
Ptr< SpectrumValue > ns3::LteSpectrumValueCatcher::GetValue ()
Returns
the latest value reported by the LteChunkProcessor
Definition at line 97 of file lte-chunk-processor.cc.
References m_value.
Referenced by LteDownlinkPowerControlTestCase::DoRun(), LteDownlinkDataSinrTestCase::DoRun(), LteDownlinkCtrlSinrTestCase::DoRun(), LteInterferenceHardFrTestCase::DoRun(), LteInterferenceStrictFrTestCase::DoRun(), LteInterferenceTestCase::DoRun(), LteLinkAdaptationTestCase::DoRun(), LtePathlossModelSystemTestCase::DoRun(), LteUplinkDataSinrTestCase::DoRun(), and LteEnbAntennaTestCase::DoRun().
ReportValue()
void ns3::LteSpectrumValueCatcher::ReportValue (const SpectrumValue & value)
function to be plugged to LteChunkProcessor::AddCallback ()
Parameters
value
Definition at line 91 of file lte-chunk-processor.cc.
References ns3::SpectrumValue::Copy(), and m_value.
Member Data Documentation
m_value
Ptr<SpectrumValue> ns3::LteSpectrumValueCatcher::m_value private
spectrum value
Definition at line 122 of file lte-chunk-processor.h.
Referenced by GetValue(), and ReportValue().
The documentation for this class was generated from the following files:
src/lte/model/lte-chunk-processor.h
src/lte/model/lte-chunk-processor.cc