ns-3: ns3::aodv::RrepHeader Class Reference
ns3::aodv::RrepHeader Class Reference
AODV Routing
Route Reply (RREP) Message Format.
#include "aodv-packet.h"
Public Member Functions
RrepHeader (uint8_t prefixSize=0, uint8_t hopCount=0, Ipv4Address dst=Ipv4Address(), uint32_t dstSeqNo=0, Ipv4Address origin=Ipv4Address(), Time lifetime=MilliSeconds(0))
constructor
uint32_t Deserialize (Buffer::Iterator start)
bool GetAckRequired () const
get the ack required flag
Ipv4Address GetDst () const
Get the destination address.
uint32_t GetDstSeqno () const
Get the destination sequence number.
uint8_t GetHopCount () const
Get the hop count.
TypeId GetInstanceTypeId () const
Get the most derived TypeId for this Object.
Time GetLifeTime () const
Get the lifetime.
Ipv4Address GetOrigin () const
Get the origin address.
uint8_t GetPrefixSize () const
Set the pefix size.
uint32_t GetSerializedSize () const
bool operator== (RrepHeader const &o) const
Comparison operator.
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetAckRequired (bool f)
Set the ack required flag.
void SetDst (Ipv4Address a)
Set the destination address.
void SetDstSeqno (uint32_t s)
Set the destination sequence number.
void SetHello (Ipv4Address src, uint32_t srcSeqNo, Time lifetime)
Configure RREP to be a Hello message.
void SetHopCount (uint8_t count)
Set the hop count.
void SetLifeTime (Time t)
Set the lifetime.
void SetOrigin (Ipv4Address a)
Set the origin address.
void SetPrefixSize (uint8_t sz)
Set the prefix size.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Ipv4Address m_dst
Destination IP Address.
uint32_t m_dstSeqNo
Destination Sequence Number.
uint8_t m_flags
A - acknowledgment required flag.
uint8_t m_hopCount
Hop Count.
uint32_t m_lifeTime
Lifetime (in milliseconds)
Ipv4Address m_origin
Source IP Address.
uint8_t m_prefixSize
Prefix Size.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Route Reply (RREP) Message Format.
0                   1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|     Type      |R|A|    Reserved     |Prefix Sz|   Hop Count   |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                     Destination IP address                    |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                  Destination Sequence Number                  |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                    Originator IP address                      |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                           Lifetime                            |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 335 of file aodv-packet.h.
Constructor & Destructor Documentation
RrepHeader()
ns3::aodv::RrepHeader::RrepHeader (uint8_t prefixSize = 0, uint8_t hopCount = 0, Ipv4Address dst = Ipv4Address (), uint32_t dstSeqNo = 0, Ipv4Address origin = Ipv4Address (), Time lifetime = MilliSeconds (0))
constructor
Parameters
prefixSize the prefix size (0)
hopCount the hop count (0)
dst the destination IP address
dstSeqNo the destination sequence number
origin the origin IP address
lifetime the lifetime
Definition at line 299 of file aodv-packet.cc.
References ns3::Time::GetMilliSeconds(), and m_lifeTime.
Member Function Documentation
Deserialize()
uint32_t ns3::aodv::RrepHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 349 of file aodv-packet.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), GetSerializedSize(), m_dst, m_dstSeqNo, m_flags, m_hopCount, m_lifeTime, m_origin, m_prefixSize, NS_ASSERT, ns3::ReadFrom(), ns3::Buffer::Iterator::ReadNtohU32(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetAckRequired()
bool ns3::aodv::RrepHeader::GetAckRequired () const
get the ack required flag
Returns
the ack required flag
Definition at line 405 of file aodv-packet.cc.
References m_flags.
Referenced by ns3::aodv::RrepHeaderTest::DoRun(), and ns3::aodv::RoutingProtocol::RecvReply().
GetDst()
Ipv4Address ns3::aodv::RrepHeader::GetDst () const inline
Get the destination address.
Returns
the destination address
Definition at line 391 of file aodv-packet.h.
References m_dst.
Referenced by ns3::aodv::RrepHeaderTest::DoRun(), ns3::aodv::RoutingProtocol::ProcessHello(), and ns3::aodv::RoutingProtocol::RecvReply().
GetDstSeqno()
uint32_t ns3::aodv::RrepHeader::GetDstSeqno () const inline
Get the destination sequence number.
Returns
the destination sequence number
Definition at line 407 of file aodv-packet.h.
References m_dstSeqNo.
Referenced by ns3::aodv::RrepHeaderTest::DoRun(), ns3::aodv::RoutingProtocol::ProcessHello(), and ns3::aodv::RoutingProtocol::RecvReply().
GetHopCount()
uint8_t ns3::aodv::RrepHeader::GetHopCount () const inline
Get the hop count.
Returns
the hop count
Definition at line 375 of file aodv-packet.h.
References m_hopCount.
Referenced by ns3::aodv::RrepHeaderTest::DoRun(), and ns3::aodv::RoutingProtocol::RecvReply().
GetInstanceTypeId()
TypeId ns3::aodv::RrepHeader::GetInstanceTypeId () const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 325 of file aodv-packet.cc.
References GetTypeId().
GetLifeTime()
Time ns3::aodv::RrepHeader::GetLifeTime () const
Get the lifetime.
Returns
the lifetime
Definition at line 385 of file aodv-packet.cc.
References m_lifeTime, and ns3::MilliSeconds().
Referenced by ns3::aodv::RrepHeaderTest::DoRun(), ns3::aodv::RoutingProtocol::ProcessHello(), and ns3::aodv::RoutingProtocol::RecvReply().
GetOrigin()
Ipv4Address ns3::aodv::RrepHeader::GetOrigin () const inline
Get the origin address.
Returns
the origin address
Definition at line 423 of file aodv-packet.h.
References m_origin.
Referenced by ns3::aodv::RrepHeaderTest::DoRun(), and ns3::aodv::RoutingProtocol::RecvReply().
GetPrefixSize()
uint8_t ns3::aodv::RrepHeader::GetPrefixSize () const
Set the pefix size.
Returns
the prefix size
Definition at line 417 of file aodv-packet.cc.
References m_prefixSize.
Referenced by ns3::aodv::RrepHeaderTest::DoRun().
GetSerializedSize()
uint32_t ns3::aodv::RrepHeader::GetSerializedSize () const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 331 of file aodv-packet.cc.
Referenced by Deserialize().
GetTypeId()
TypeId ns3::aodv::RrepHeader::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 314 of file aodv-packet.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
operator==()
bool ns3::aodv::RrepHeader::operator== (RrepHeader const & o) const
Comparison operator.
Parameters
o RREP header to compare
Returns
true if the RREP headers are equal
Definition at line 423 of file aodv-packet.cc.
References m_dst, m_dstSeqNo, m_flags, m_hopCount, m_lifeTime, m_origin, and m_prefixSize.
Print()
void ns3::aodv::RrepHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 367 of file aodv-packet.cc.
References m_dst, m_dstSeqNo, m_lifeTime, m_origin, and m_prefixSize.
Referenced by ns3::aodv::operator<<().
Serialize()
void ns3::aodv::RrepHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 337 of file aodv-packet.cc.
References m_dst, m_dstSeqNo, m_flags, m_hopCount, m_lifeTime, m_origin, m_prefixSize, ns3::Buffer::Iterator::WriteHtonU32(), ns3::WriteTo(), and ns3::Buffer::Iterator::WriteU8().
SetAckRequired()
void ns3::aodv::RrepHeader::SetAckRequired (bool f)
Set the ack required flag.
Parameters
f the ack required flag
Definition at line 392 of file aodv-packet.cc.
References f(), and m_flags.
Referenced by ns3::aodv::RrepHeaderTest::DoRun(), ns3::aodv::RoutingProtocol::RecvReply(), and ns3::aodv::RoutingProtocol::SendReplyByIntermediateNode().
SetDst()
void ns3::aodv::RrepHeader::SetDst (Ipv4Address a) inline
Set the destination address.
Parameters
a the destination address
Definition at line 383 of file aodv-packet.h.
References m_dst.
Referenced by ns3::aodv::RrepHeaderTest::DoRun().
SetDstSeqno()
void ns3::aodv::RrepHeader::SetDstSeqno (uint32_t s) inline
Set the destination sequence number.
Parameters
s the destination sequence number
Definition at line 399 of file aodv-packet.h.
References m_dstSeqNo.
Referenced by ns3::aodv::RrepHeaderTest::DoRun().
SetHello()
void ns3::aodv::RrepHeader::SetHello (Ipv4Address src, uint32_t srcSeqNo, Time lifetime)
Configure RREP to be a Hello message.
Parameters
src the source IP address
srcSeqNo the source sequence number
lifetime the lifetime of the message
Definition at line 431 of file aodv-packet.cc.
References ns3::Time::GetMilliSeconds(), m_dst, m_dstSeqNo, m_flags, m_hopCount, m_lifeTime, m_origin, and m_prefixSize.
Referenced by ns3::aodv::RrepHeaderTest::DoRun().
SetHopCount()
void ns3::aodv::RrepHeader::SetHopCount (uint8_t count) inline
Set the hop count.
Parameters
count the hop count
Definition at line 367 of file aodv-packet.h.
References m_hopCount.
Referenced by ns3::aodv::RrepHeaderTest::DoRun(), and ns3::aodv::RoutingProtocol::RecvReply().
SetLifeTime()
void ns3::aodv::RrepHeader::SetLifeTime (Time t)
Set the lifetime.
Parameters
t the lifetime
Definition at line 379 of file aodv-packet.cc.
References ns3::Time::GetMilliSeconds(), and m_lifeTime.
Referenced by ns3::aodv::RrepHeaderTest::DoRun().
SetOrigin()
void ns3::aodv::RrepHeader::SetOrigin (Ipv4Address a) inline
Set the origin address.
Parameters
a the origin address
Definition at line 415 of file aodv-packet.h.
References m_origin.
Referenced by ns3::aodv::RrepHeaderTest::DoRun().
SetPrefixSize()
void ns3::aodv::RrepHeader::SetPrefixSize (uint8_t sz)
Set the prefix size.
Parameters
sz the prefix size
Definition at line 411 of file aodv-packet.cc.
References m_prefixSize.
Referenced by ns3::aodv::RrepHeaderTest::DoRun().
Member Data Documentation
m_dst
Ipv4Address ns3::aodv::RrepHeader::m_dst private
Destination IP Address.
Definition at line 479 of file aodv-packet.h.
Referenced by Deserialize(), GetDst(), operator==(), Print(), Serialize(), SetDst(), and SetHello().
m_dstSeqNo
uint32_t ns3::aodv::RrepHeader::m_dstSeqNo private
Destination Sequence Number.
Definition at line 480 of file aodv-packet.h.
Referenced by Deserialize(), GetDstSeqno(), operator==(), Print(), Serialize(), SetDstSeqno(), and SetHello().
m_flags
uint8_t ns3::aodv::RrepHeader::m_flags private
A - acknowledgment required flag.
Definition at line 476 of file aodv-packet.h.
Referenced by Deserialize(), GetAckRequired(), operator==(), Serialize(), SetAckRequired(), and SetHello().
m_hopCount
uint8_t ns3::aodv::RrepHeader::m_hopCount private
Hop Count.
Definition at line 478 of file aodv-packet.h.
Referenced by Deserialize(), GetHopCount(), operator==(), Serialize(), SetHello(), and SetHopCount().
m_lifeTime
uint32_t ns3::aodv::RrepHeader::m_lifeTime private
Lifetime (in milliseconds)
Definition at line 482 of file aodv-packet.h.
Referenced by RrepHeader(), Deserialize(), GetLifeTime(), operator==(), Print(), Serialize(), SetHello(), and SetLifeTime().
m_origin
Ipv4Address ns3::aodv::RrepHeader::m_origin private
Source IP Address.
Definition at line 481 of file aodv-packet.h.
Referenced by Deserialize(), GetOrigin(), operator==(), Print(), Serialize(), SetHello(), and SetOrigin().
m_prefixSize
uint8_t ns3::aodv::RrepHeader::m_prefixSize private
Prefix Size.
Definition at line 477 of file aodv-packet.h.
Referenced by Deserialize(), GetPrefixSize(), operator==(), Print(), Serialize(), SetHello(), and SetPrefixSize().
The documentation for this class was generated from the following files:
src/aodv/model/aodv-packet.h
src/aodv/model/aodv-packet.cc