ns-3: ns3::RxTimingSetupAns Class Reference
ns3::RxTimingSetupAns Class Reference
Implementation of the RxTimingSetupAns LoRaWAN MAC command.
#include "mac-command.h"
Public Member Functions
RxTimingSetupAns ()
virtual uint8_t Deserialize (Buffer::Iterator &start)
Deserialize the buffer into a MAC command.
virtual void Print (std::ostream &os) const
Print the contents of this MAC command in human-readable format.
virtual void Serialize (Buffer::Iterator &start) const
Serialize the contents of this MAC command into a buffer, according to the LoRaWAN standard.
Public Member Functions inherited from ns3::MacCommand
MacCommand ()
virtual ~MacCommand ()
virtual enum MacCommandType GetCommandType (void) const
Get the commandType of this MAC command.
virtual uint8_t GetSerializedSize (void) const
Get serialized length of this MAC command.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Additional Inherited Members
Static Public Member Functions inherited from ns3::MacCommand
static uint8_t GetCIDFromMacCommand (enum MacCommandType commandType)
Get the CID that corresponds to this MAC command.
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::MacCommand
enum MacCommandType m_commandType
The type of this command.
uint8_t m_serializedSize
This MAC command's serialized size.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implementation of the RxTimingSetupAns LoRaWAN MAC command.
This MAC command has an empty payload.
Definition at line 560 of file mac-command.h.
Constructor & Destructor Documentation
RxTimingSetupAns()
ns3::RxTimingSetupAns::RxTimingSetupAns ()
Definition at line 1066 of file mac-command.cc.
References ns3::DEV_STATUS_REQ, ns3::MacCommand::m_commandType, ns3::MacCommand::m_serializedSize, and NS_LOG_FUNCTION.
Member Function Documentation
Deserialize()
uint8_t ns3::RxTimingSetupAns::Deserialize (Buffer::Iterator & start) virtual
Deserialize the buffer into a MAC command.
Parameters
start A pointer to the buffer that contains the serialized command.
Returns
the number of bytes that were consumed.
Implements ns3::MacCommand.
Definition at line 1084 of file mac-command.cc.
References ns3::MacCommand::m_serializedSize, NS_LOG_FUNCTION_NOARGS, and visualizer.core::start().
Print()
void ns3::RxTimingSetupAns::Print (std::ostream & os) const virtual
Print the contents of this MAC command in human-readable format.
Parameters
os The std::ostream instance on which to print the MAC command.
Implements ns3::MacCommand.
Definition at line 1095 of file mac-command.cc.
References NS_LOG_FUNCTION_NOARGS.
Serialize()
void ns3::RxTimingSetupAns::Serialize (Buffer::Iterator & start) const virtual
Serialize the contents of this MAC command into a buffer, according to the LoRaWAN standard.
Parameters
start A pointer to the buffer into which to serialize the command.
Implements ns3::MacCommand.
Definition at line 1075 of file mac-command.cc.
References ns3::MacCommand::GetCIDFromMacCommand(), ns3::MacCommand::m_commandType, NS_LOG_FUNCTION_NOARGS, and visualizer.core::start().
The documentation for this class was generated from the following files:
src/lorawan/model/mac-command.h
src/lorawan/model/mac-command.cc