ns-3: ns3::MemberLteUeRrcSapProvider< C > Class Template Reference
ns3::MemberLteUeRrcSapProvider< C > Class Template Reference
Template for the implementation of the LteUeRrcSapProvider as a member of an owner class of type C to which all methods are forwarded.
#include "lte-rrc-sap.h"
Public Member Functions
MemberLteUeRrcSapProvider (C *owner)
Constructor.
virtual void CompleteSetup (CompleteSetupParameters params)
Complete setup function.
virtual void RecvRrcConnectionReconfiguration (RrcConnectionReconfiguration msg)
Receive an RRCConnectionReconfiguration message from the serving eNodeB during an RRC connection reconfiguration procedure (Section 5.3.5 of TS 36.331).
virtual void RecvRrcConnectionReestablishment (RrcConnectionReestablishment msg)
Receive an RRCConnectionReestablishment message from the serving eNodeB during an RRC connection re-establishment procedure (Section 5.3.7 of TS 36.331).
virtual void RecvRrcConnectionReestablishmentReject (RrcConnectionReestablishmentReject msg)
Receive an RRCConnectionReestablishmentReject message from the serving eNodeB during an RRC connection re-establishment procedure (Section 5.3.7 of TS 36.331).
virtual void RecvRrcConnectionReject (RrcConnectionReject msg)
Receive an RRCConnectionReject message from the serving eNodeB during an RRC connection establishment procedure (Section 5.3.3 of TS 36.331).
virtual void RecvRrcConnectionRelease (RrcConnectionRelease msg)
Receive an RRCConnectionRelease message from the serving eNodeB during an RRC connection release procedure (Section 5.3.8 of TS 36.331).
virtual void RecvRrcConnectionSetup (RrcConnectionSetup msg)
Receive an RRCConnectionSetup message from the serving eNodeB during an RRC connection establishment procedure (Section 5.3.3 of TS 36.331).
virtual void RecvSystemInformation (SystemInformation msg)
Receive a SystemInformation message from the serving eNodeB during a system information acquisition procedure (Section 5.2.2 of TS 36.331).
Public Member Functions inherited from ns3::LteRrcSap
virtual ~LteRrcSap ()
Private Member Functions
MemberLteUeRrcSapProvider ()
Private Attributes
C * m_owner
the owner class
Additional Inherited Members
Public Types inherited from ns3::LteRrcSap
enum ReestablishmentCause { RECONFIGURATION_FAILURE, HANDOVER_FAILURE, OTHER_FAILURE }
ReestablishmentCause enumeration.
Static Public Member Functions inherited from ns3::LteRrcSap
static double ConvertPdschConfigDedicated2Double (PdschConfigDedicated pdschConfigDedicated)
Convert PDSCH config dedicated function.
Static Public Attributes inherited from ns3::LteRrcSap
static const uint8_t MaxReportCells = 8
Constraint values.
Detailed Description
template<class C>
class ns3::MemberLteUeRrcSapProvider< C >
Template for the implementation of the LteUeRrcSapProvider as a member of an owner class of type C to which all methods are forwarded.
Definition at line 1403 of file lte-rrc-sap.h.
Constructor & Destructor Documentation
MemberLteUeRrcSapProvider() [1/2]
template<class C > ns3::MemberLteUeRrcSapProvider< C >::MemberLteUeRrcSapProvider (C * owner)
Constructor.
Parameters
owner the owner class
Definition at line 1429 of file lte-rrc-sap.h.
MemberLteUeRrcSapProvider() [2/2]
template<class C > ns3::MemberLteUeRrcSapProvider< C >::MemberLteUeRrcSapProvider private
Definition at line 1435 of file lte-rrc-sap.h.
Member Function Documentation
CompleteSetup()
template<class C > void ns3::MemberLteUeRrcSapProvider< C >::CompleteSetup (CompleteSetupParameters params) virtual
Complete setup function.
Parameters
params the complete setup parameters
Implements ns3::LteUeRrcSapProvider.
Definition at line 1441 of file lte-rrc-sap.h.
References aloha::params.
RecvRrcConnectionReconfiguration()
template<class C > void ns3::MemberLteUeRrcSapProvider< C >::RecvRrcConnectionReconfiguration (RrcConnectionReconfiguration msg) virtual
Receive an RRCConnectionReconfiguration message from the serving eNodeB during an RRC connection reconfiguration procedure (Section 5.3.5 of TS 36.331).
Parameters
msg the message
Implements ns3::LteUeRrcSapProvider.
Definition at line 1462 of file lte-rrc-sap.h.
References ns3::Simulator::ScheduleNow().
RecvRrcConnectionReestablishment()
template<class C > void ns3::MemberLteUeRrcSapProvider< C >::RecvRrcConnectionReestablishment (RrcConnectionReestablishment msg) virtual
Receive an RRCConnectionReestablishment message from the serving eNodeB during an RRC connection re-establishment procedure (Section 5.3.7 of TS 36.331).
Parameters
msg the message
Implements ns3::LteUeRrcSapProvider.
Definition at line 1469 of file lte-rrc-sap.h.
References ns3::Simulator::ScheduleNow().
RecvRrcConnectionReestablishmentReject()
template<class C > void ns3::MemberLteUeRrcSapProvider< C >::RecvRrcConnectionReestablishmentReject (RrcConnectionReestablishmentReject msg) virtual
Receive an RRCConnectionReestablishmentReject message from the serving eNodeB during an RRC connection re-establishment procedure (Section 5.3.7 of TS 36.331).
Parameters
msg the message
Implements ns3::LteUeRrcSapProvider.
Definition at line 1476 of file lte-rrc-sap.h.
References ns3::Simulator::ScheduleNow().
RecvRrcConnectionReject()
template<class C > void ns3::MemberLteUeRrcSapProvider< C >::RecvRrcConnectionReject (RrcConnectionReject msg) virtual
Receive an RRCConnectionReject message from the serving eNodeB during an RRC connection establishment procedure (Section 5.3.3 of TS 36.331).
Parameters
msg the message
Implements ns3::LteUeRrcSapProvider.
Definition at line 1490 of file lte-rrc-sap.h.
References ns3::Simulator::ScheduleNow().
RecvRrcConnectionRelease()
template<class C > void ns3::MemberLteUeRrcSapProvider< C >::RecvRrcConnectionRelease (RrcConnectionRelease msg) virtual
Receive an RRCConnectionRelease message from the serving eNodeB during an RRC connection release procedure (Section 5.3.8 of TS 36.331).
Parameters
msg the message
Implements ns3::LteUeRrcSapProvider.
Definition at line 1483 of file lte-rrc-sap.h.
References ns3::Simulator::ScheduleNow().
RecvRrcConnectionSetup()
template<class C > void ns3::MemberLteUeRrcSapProvider< C >::RecvRrcConnectionSetup (RrcConnectionSetup msg) virtual
Receive an RRCConnectionSetup message from the serving eNodeB during an RRC connection establishment procedure (Section 5.3.3 of TS 36.331).
Parameters
msg the message
Implements ns3::LteUeRrcSapProvider.
Definition at line 1455 of file lte-rrc-sap.h.
References ns3::Simulator::ScheduleNow().
RecvSystemInformation()
template<class C > void ns3::MemberLteUeRrcSapProvider< C >::RecvSystemInformation (SystemInformation msg) virtual
Receive a SystemInformation message from the serving eNodeB during a system information acquisition procedure (Section 5.2.2 of TS 36.331).
Parameters
msg the message
Implements ns3::LteUeRrcSapProvider.
Definition at line 1448 of file lte-rrc-sap.h.
References ns3::Simulator::ScheduleNow().
Member Data Documentation
m_owner
template<class C > C* ns3::MemberLteUeRrcSapProvider< C >::m_owner private
the owner class
Definition at line 1425 of file lte-rrc-sap.h.
The documentation for this class was generated from the following file:
src/lte/model/lte-rrc-sap.h