ns-3: ns3::Kun2600MhzPropagationLossModel Class Reference
ns3::Kun2600MhzPropagationLossModel Class Reference
Propagation Models
Empirical propagation model for the 2.6 GHz frequency.
#include "kun-2600-mhz-propagation-loss-model.h"
Public Member Functions
Kun2600MhzPropagationLossModel ()
virtual ~Kun2600MhzPropagationLossModel ()
double GetLoss (Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Public Member Functions inherited from ns3::PropagationLossModel
PropagationLossModel ()
virtual ~PropagationLossModel ()
int64_t AssignStreams (int64_t stream)
If this loss model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
double CalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account all the PropagationLossModel(s) chained to the current one.
Ptr< PropagationLossModel > GetNext ()
Gets the next PropagationLossModel in the chain of loss models that act on the signal.
void SetNext (Ptr< PropagationLossModel > next)
Enables a chain of loss models to act on the signal.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::PropagationLossModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
Kun2600MhzPropagationLossModel (const Kun2600MhzPropagationLossModel &)
Copy constructor.
virtual int64_t DoAssignStreams (int64_t stream)
Subclasses must implement this; those not using random variables can return zero.
virtual double DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account only the particular PropagationLossModel.
Kun2600MhzPropagationLossModel & operator= (const Kun2600MhzPropagationLossModel &)
Copy constructor.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Empirical propagation model for the 2.6 GHz frequency.
This class implements the empirical model for 2.6 GHz taken from this paper: Sun Kun, Wang Ping, Li Yingze "Path Loss Models for Suburban Scenario at 2.3GHz, 2.6GHz and 3.5GHz" 8th International Symposium on Antennas, Propagation and EM Theory (ISAPE), 2008.
Definition at line 41 of file kun-2600-mhz-propagation-loss-model.h.
Constructor & Destructor Documentation
Kun2600MhzPropagationLossModel() [1/2]
ns3::Kun2600MhzPropagationLossModel::Kun2600MhzPropagationLossModel ()
Definition at line 49 of file kun-2600-mhz-propagation-loss-model.cc.
~Kun2600MhzPropagationLossModel()
ns3::Kun2600MhzPropagationLossModel::~Kun2600MhzPropagationLossModel () virtual
Definition at line 54 of file kun-2600-mhz-propagation-loss-model.cc.
Kun2600MhzPropagationLossModel() [2/2]
ns3::Kun2600MhzPropagationLossModel::Kun2600MhzPropagationLossModel (const Kun2600MhzPropagationLossModel &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Member Function Documentation
DoAssignStreams()
int64_t ns3::Kun2600MhzPropagationLossModel::DoAssignStreams (int64_t stream) private virtual
Subclasses must implement this; those not using random variables can return zero.
Implements ns3::PropagationLossModel.
Definition at line 75 of file kun-2600-mhz-propagation-loss-model.cc.
DoCalcRxPower()
double ns3::Kun2600MhzPropagationLossModel::DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const private virtual
Returns the Rx Power taking into account only the particular PropagationLossModel.
Parameters
txPowerDbm current transmission power (in dBm)
a the mobility model of the source
b the mobility model of the destination
Returns
the reception power after adding/multiplying propagation loss (in dBm)
Implements ns3::PropagationLossModel.
Definition at line 67 of file kun-2600-mhz-propagation-loss-model.cc.
References GetLoss().
GetLoss()
double ns3::Kun2600MhzPropagationLossModel::GetLoss (Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Parameters
a the first mobility model
b the second mobility model
Returns
the loss in dBm for the propagation between the two given mobility models
Definition at line 59 of file kun-2600-mhz-propagation-loss-model.cc.
References ns3::MobilityModel::GetDistanceFrom().
Referenced by DoCalcRxPower(), and Kun2600MhzPropagationLossModelTestCase::DoRun().
GetTypeId()
TypeId ns3::Kun2600MhzPropagationLossModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 38 of file kun-2600-mhz-propagation-loss-model.cc.
References ns3::TypeId::SetParent().
operator=()
Kun2600MhzPropagationLossModel& ns3::Kun2600MhzPropagationLossModel::operator= (const Kun2600MhzPropagationLossModel &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Returns
The documentation for this class was generated from the following files:
src/propagation/model/kun-2600-mhz-propagation-loss-model.h
src/propagation/model/kun-2600-mhz-propagation-loss-model.cc