ns-3: LteUplinkClosedLoopPowerControlAbsoluteModeTestCase Class Reference
LteUplinkClosedLoopPowerControlAbsoluteModeTestCase Class Reference
LTE Models » lte module tests | Test suites
Lte Uplink Closed Loop Power Control Absolute Mode Test Case.
#include "lte-test-uplink-power-control.h"
Public Member Functions
LteUplinkClosedLoopPowerControlAbsoluteModeTestCase (std::string name)
Constructor.
virtual ~LteUplinkClosedLoopPowerControlAbsoluteModeTestCase ()
Public Member Functions inherited from LteUplinkPowerControlTestCase
LteUplinkPowerControlTestCase (std::string name)
Constructor.
virtual ~LteUplinkPowerControlTestCase ()
void PucchTxPowerTrace (uint16_t cellId, uint16_t rnti, double txPower)
PUCCH transmit power trace funcction.
void PuschTxPowerTrace (uint16_t cellId, uint16_t rnti, double txPower)
PUSCH transmit power trace funcction.
void SetTpcConfiguration (uint32_t tpc, uint32_t tpcNum, double expectedPuschTxPower, double expectedPucchTxPower, double expectedSrsTxPower)
Set TPC configuration funcction.
void SrsTxPowerTrace (uint16_t cellId, uint16_t rnti, double txPower)
SRS transmit power trace funcction.
void TeleportUe (uint32_t x, uint32_t y, double expectedPuschTxPower, double expectedPucchTxPower, double expectedSrsTxPower)
Teleport UE funcction.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Protected Attributes inherited from LteUplinkPowerControlTestCase
bool m_accumulatedMode
indicates whether accumulated mode is being used
double m_expectedPucchTxPower
expected PUCCH transmit power
double m_expectedPuschTxPower
expected PUSCH transmit power
double m_expectedSrsTxPower
expected SRS transmit power
Ptr< LteFfrSimple > m_ffrSimple
FFR simple.
Time m_teleportTime
teleport time
Ptr< MobilityModel > m_ueMobility
UE mobility model.
Ptr< LteUePowerControl > m_ueUpc
UE power control.
Detailed Description
Lte Uplink Closed Loop Power Control Absolute Mode Test Case.
Definition at line 153 of file lte-test-uplink-power-control.h.
Constructor & Destructor Documentation
LteUplinkClosedLoopPowerControlAbsoluteModeTestCase()
LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::LteUplinkClosedLoopPowerControlAbsoluteModeTestCase (std::string name)
Constructor.
Parameters
name the reference name
Definition at line 295 of file lte-test-uplink-power-control.cc.
References NS_LOG_INFO.
~LteUplinkClosedLoopPowerControlAbsoluteModeTestCase()
LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::~LteUplinkClosedLoopPowerControlAbsoluteModeTestCase () virtual
Definition at line 301 of file lte-test-uplink-power-control.cc.
Member Function Documentation
DoRun()
void LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Reimplemented from LteUplinkPowerControlTestCase.
Definition at line 306 of file lte-test-uplink-power-control.cc.
References ns3::LteHelper::ActivateDataRadioBearer(), ns3::ListPositionAllocator::Add(), ns3::LteHelper::Attach(), ns3::NodeContainer::Create(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::PointerValue::Get(), ns3::Object::GetObject(), ns3::PointerValue::GetObject(), ns3::LteUeNetDevice::GetPhy(), ns3::LteUePhy::GetUplinkPowerControl(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), LteUplinkPowerControlTestCase::m_accumulatedMode, LteUplinkPowerControlTestCase::m_ffrSimple, LteUplinkPowerControlTestCase::m_ueMobility, LteUplinkPowerControlTestCase::m_ueUpc, ns3::MakeBoundCallback(), ns3::MilliSeconds(), third::mobility, PucchTxPowerNofitication(), PuschTxPowerNofitication(), ns3::Config::Reset(), ns3::Seconds(), ns3::Config::SetDefault(), ns3::LteHelper::SetEnbDeviceAttribute(), ns3::LteHelper::SetFfrAlgorithmType(), ns3::LteHelper::SetSchedulerType(), LteUplinkPowerControlTestCase::SetTpcConfiguration(), SrsTxPowerNofitication(), and ns3::ObjectBase::TraceConnectWithoutContext().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-uplink-power-control.h
src/lte/test/lte-test-uplink-power-control.cc