ns-3: RandomVariableStreamExponentialAntitheticTestCase Class Reference
RandomVariableStreamExponentialAntitheticTestCase Class Reference
Public Member Functions
RandomVariableStreamExponentialAntitheticTestCase ()
virtual ~RandomVariableStreamExponentialAntitheticTestCase ()
double ChiSquaredTest (Ptr< ExponentialRandomVariable > e)
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Static Public Attributes
static const uint32_t N_BINS = 50
static const uint32_t N_MEASUREMENTS = 1000000
static const uint32_t N_RUNS = 5
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 860 of file random-variable-stream-test-suite.cc.
Constructor & Destructor Documentation
RandomVariableStreamExponentialAntitheticTestCase()
RandomVariableStreamExponentialAntitheticTestCase::RandomVariableStreamExponentialAntitheticTestCase ()
Definition at line 876 of file random-variable-stream-test-suite.cc.
~RandomVariableStreamExponentialAntitheticTestCase()
RandomVariableStreamExponentialAntitheticTestCase::~RandomVariableStreamExponentialAntitheticTestCase () virtual
Definition at line 880 of file random-variable-stream-test-suite.cc.
Member Function Documentation
ChiSquaredTest()
double RandomVariableStreamExponentialAntitheticTestCase::ChiSquaredTest (Ptr< ExponentialRandomVariable > e)
Definition at line 884 of file random-variable-stream-test-suite.cc.
References FillHistoRangeUniformly(), ns3::ExponentialRandomVariable::GetValue(), max, N_BINS, and N_MEASUREMENTS.
Referenced by DoRun().
DoRun()
void RandomVariableStreamExponentialAntitheticTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 934 of file random-variable-stream-test-suite.cc.
References ChiSquaredTest(), N_BINS, N_MEASUREMENTS, N_RUNS, NS_TEST_ASSERT_MSG_EQ_TOL, NS_TEST_ASSERT_MSG_LT, ns3::ObjectBase::SetAttribute(), anonymous_namespace{random-variable-stream-test-suite.cc}::SetTestSuiteSeed(), TOLERANCE, and sample-rng-plot::x.
Member Data Documentation
N_BINS
const uint32_t RandomVariableStreamExponentialAntitheticTestCase::N_BINS = 50 static
Definition at line 864 of file random-variable-stream-test-suite.cc.
Referenced by ChiSquaredTest(), and DoRun().
N_MEASUREMENTS
const uint32_t RandomVariableStreamExponentialAntitheticTestCase::N_MEASUREMENTS = 1000000 static
Definition at line 865 of file random-variable-stream-test-suite.cc.
Referenced by ChiSquaredTest(), and DoRun().
N_RUNS
const uint32_t RandomVariableStreamExponentialAntitheticTestCase::N_RUNS = 5 static
Definition at line 863 of file random-variable-stream-test-suite.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/core/test/random-variable-stream-test-suite.cc