ns-3: LrWpanPlmeAndPdInterfaceTestCase Class Reference
LrWpanPlmeAndPdInterfaceTestCase Class Reference
LR-WPAN models » LrWpan module tests | Test suites
LrWpan PLME and PD Interfaces Test.
Public Member Functions
LrWpanPlmeAndPdInterfaceTestCase ()
virtual ~LrWpanPlmeAndPdInterfaceTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void ReceivePdDataIndication (uint32_t psduLength, Ptr< Packet > p, uint8_t lqi)
Receives a PdData indication.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
LrWpan PLME and PD Interfaces Test.
Definition at line 36 of file lr-wpan-pd-plme-sap-test.cc.
Constructor & Destructor Documentation
LrWpanPlmeAndPdInterfaceTestCase()
LrWpanPlmeAndPdInterfaceTestCase::LrWpanPlmeAndPdInterfaceTestCase ()
Definition at line 54 of file lr-wpan-pd-plme-sap-test.cc.
~LrWpanPlmeAndPdInterfaceTestCase()
LrWpanPlmeAndPdInterfaceTestCase::~LrWpanPlmeAndPdInterfaceTestCase () virtual
Definition at line 59 of file lr-wpan-pd-plme-sap-test.cc.
Member Function Documentation
DoRun()
void LrWpanPlmeAndPdInterfaceTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 74 of file lr-wpan-pd-plme-sap-test.cc.
References third::channel, ns3::Packet::GetSize(), ns3::LOG_LEVEL_ALL, ns3::LOG_PREFIX_FUNC, ns3::LogComponentEnable(), ns3::LogComponentEnableAll(), ns3::MakeCallback(), sample-rng-plot::n, ns3::LrWpanPhy::PdDataRequest(), ReceivePdDataIndication(), ns3::LrWpanPhy::SetChannel(), and ns3::LrWpanPhy::SetPdDataIndicationCallback().
ReceivePdDataIndication()
void LrWpanPlmeAndPdInterfaceTestCase::ReceivePdDataIndication (uint32_t psduLength, Ptr< Packet > p, uint8_t lqi) private
Receives a PdData indication.
Parameters
psduLength The PSDU length.
p The packet.
lqi The LQI.
Definition at line 64 of file lr-wpan-pd-plme-sap-test.cc.
References ns3::Now(), and NS_LOG_UNCOND.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/lr-wpan/test/lr-wpan-pd-plme-sap-test.cc