ns-3: ns3::A2A4RsrqHandoverAlgorithm Class Reference
ns3::A2A4RsrqHandoverAlgorithm Class Reference
Handover algorithm implementation based on RSRQ measurements, Event A2 and Event A4.
#include "a2-a4-rsrq-handover-algorithm.h"
Classes
class UeMeasure
Measurements reported by a UE for a cell ID.
Public Member Functions
A2A4RsrqHandoverAlgorithm ()
Creates an A2-A4-RSRQ handover algorithm instance.
virtual ~A2A4RsrqHandoverAlgorithm ()
virtual LteHandoverManagementSapProvider * GetLteHandoverManagementSapProvider ()
Export the "provider" part of the Handover Management SAP interface.
virtual void SetLteHandoverManagementSapUser (LteHandoverManagementSapUser *s)
Set the "user" part of the Handover Management SAP interface that this handover algorithm instance will interact with.
Public Member Functions inherited from ns3::LteHandoverAlgorithm
LteHandoverAlgorithm ()
virtual ~LteHandoverAlgorithm ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::LteHandoverAlgorithm
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose ()
Destructor implementation.
virtual void DoInitialize ()
Initialize() implementation.
void DoReportUeMeas (uint16_t rnti, LteRrcSap::MeasResults measResults)
Implementation of LteHandoverManagementSapProvider::ReportUeMeas.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
typedef std::map< uint16_t, Ptr< UeMeasure > > MeasurementRow_t
Measurements reported by a UE for several cells.
typedef std::map< uint16_t, MeasurementRow_t > MeasurementTable_t
Measurements reported by several UEs.
Private Member Functions
void EvaluateHandover (uint16_t rnti, uint8_t servingCellRsrq)
Called when Event A2 is detected, then trigger a handover if needed.
bool IsValidNeighbour (uint16_t cellId)
Determines if a neighbour cell is a valid destination for handover.
void UpdateNeighbourMeasurements (uint16_t rnti, uint16_t cellId, uint8_t rsrq)
Called when Event A4 is reported, then update the measurements table.
Private Attributes
uint8_t m_a2MeasId
The expected measurement identity for A2 measurements.
uint8_t m_a4MeasId
The expected measurement identity for A4 measurements.
LteHandoverManagementSapProvider * m_handoverManagementSapProvider
Receive API calls from the eNodeB RRC instance.
LteHandoverManagementSapUser * m_handoverManagementSapUser
Interface to the eNodeB RRC instance.
MeasurementTable_t m_neighbourCellMeasures
Table of measurement reports from all UEs.
uint8_t m_neighbourCellOffset
The NeighbourCellOffset attribute.
uint8_t m_servingCellThreshold
The ServingCellThreshold attribute.
Friends
class MemberLteHandoverManagementSapProvider< A2A4RsrqHandoverAlgorithm >
let the forwarder class access the protected and private members
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Handover algorithm implementation based on RSRQ measurements, Event A2 and Event A4.
Handover decision made by this algorithm is primarily based on Event A2 measurements (serving cell's RSRQ becomes worse than threshold). When the event is triggered, the first condition of handover is fulfilled.
Event A4 measurements (neighbour cell's RSRQ becomes better than threshold) are used to detect neighbouring cells and their respective RSRQ. When a neighbouring cell's RSRQ is higher than the serving cell's RSRQ by a certain offset, then the second condition of handover is fulfilled.
When the first and second conditions above are fulfilled, the algorithm informs the eNodeB RRC to trigger a handover.
The threshold for Event A2 can be configured in the ServingCellThreshold attribute. The offset used in the second condition can also be configured by setting the NeighbourCellOffset attribute.
The following code snippet is an example of using and configuring the handover algorithm in a simulation program:
Ptr<LteHelper> lteHelper = CreateObject<LteHelper> ();
NodeContainer enbNodes;
// configure the nodes here...
lteHelper->SetHandoverAlgorithmType ("ns3::A2A4RsrqHandoverAlgorithm");
lteHelper->SetHandoverAlgorithmAttribute ("ServingCellThreshold",
                                          UintegerValue (30));
lteHelper->SetHandoverAlgorithmAttribute ("NeighbourCellOffset",
                                          UintegerValue (1));
NetDeviceContainer enbLteDevs = lteHelper->InstallEnbDevice (enbNodes);
Note
Setting the handover algorithm type and attributes after the call to LteHelper::InstallEnbDevice does not have any effect to the devices that have already been installed.
Definition at line 80 of file a2-a4-rsrq-handover-algorithm.h.
Member Typedef Documentation
MeasurementRow_t
typedef std::map<uint16_t, Ptr<UeMeasure> > ns3::A2A4RsrqHandoverAlgorithm::MeasurementRow_t private
Measurements reported by a UE for several cells.
The structure is a map indexed by the cell ID.
Definition at line 161 of file a2-a4-rsrq-handover-algorithm.h.
MeasurementTable_t
typedef std::map<uint16_t, MeasurementRow_t> ns3::A2A4RsrqHandoverAlgorithm::MeasurementTable_t private
Measurements reported by several UEs.
The structure is a map indexed by the RNTI of the UE.
Definition at line 167 of file a2-a4-rsrq-handover-algorithm.h.
Constructor & Destructor Documentation
A2A4RsrqHandoverAlgorithm()
ns3::A2A4RsrqHandoverAlgorithm::A2A4RsrqHandoverAlgorithm ()
Creates an A2-A4-RSRQ handover algorithm instance.
Definition at line 44 of file a2-a4-rsrq-handover-algorithm.cc.
References m_handoverManagementSapProvider, MemberLteHandoverManagementSapProvider< A2A4RsrqHandoverAlgorithm >, and NS_LOG_FUNCTION.
~A2A4RsrqHandoverAlgorithm()
ns3::A2A4RsrqHandoverAlgorithm::~A2A4RsrqHandoverAlgorithm () virtual
Definition at line 56 of file a2-a4-rsrq-handover-algorithm.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::A2A4RsrqHandoverAlgorithm::DoDispose () protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::LteHandoverAlgorithm.
Definition at line 135 of file a2-a4-rsrq-handover-algorithm.cc.
References m_handoverManagementSapProvider, and NS_LOG_FUNCTION.
DoInitialize()
void ns3::A2A4RsrqHandoverAlgorithm::DoInitialize () protected virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 106 of file a2-a4-rsrq-handover-algorithm.cc.
References ns3::LteHandoverManagementSapUser::AddUeMeasReportConfigForHandover(), ns3::LteRrcSap::ThresholdEutra::choice, ns3::Object::DoInitialize(), ns3::LteRrcSap::ReportConfigEutra::EVENT_A2, ns3::LteRrcSap::ReportConfigEutra::EVENT_A4, ns3::LteRrcSap::ReportConfigEutra::eventId, m_a2MeasId, m_a4MeasId, m_handoverManagementSapUser, m_servingCellThreshold, ns3::LteRrcSap::ReportConfigEutra::MS240, ns3::LteRrcSap::ReportConfigEutra::MS480, NS_LOG_FUNCTION, NS_LOG_LOGIC(), ns3::LteRrcSap::ThresholdEutra::range, ns3::LteRrcSap::ReportConfigEutra::reportInterval, ns3::LteRrcSap::ReportConfigEutra::RSRQ, ns3::LteRrcSap::ReportConfigEutra::threshold1, ns3::LteRrcSap::ThresholdEutra::THRESHOLD_RSRQ, and ns3::LteRrcSap::ReportConfigEutra::triggerQuantity.
DoReportUeMeas()
void ns3::A2A4RsrqHandoverAlgorithm::DoReportUeMeas (uint16_t rnti, LteRrcSap::MeasResults measResults) protected virtual
Implementation of LteHandoverManagementSapProvider::ReportUeMeas.
Parameters
rnti Radio Network Temporary Identity, an integer identifying the UE where the report originates from
measResults a single report of one measurement identity
Implements ns3::LteHandoverAlgorithm.
Definition at line 143 of file a2-a4-rsrq-handover-algorithm.cc.
References EvaluateHandover(), ns3::LteRrcSap::MeasResults::haveMeasResultNeighCells, m_a2MeasId, m_a4MeasId, m_servingCellThreshold, ns3::LteRrcSap::MeasResults::measId, ns3::LteRrcSap::MeasResults::measResultListEutra, NS_ASSERT_MSG(), NS_LOG_FUNCTION, NS_LOG_WARN, ns3::LteRrcSap::MeasResults::rsrqResult, and UpdateNeighbourMeasurements().
EvaluateHandover()
void ns3::A2A4RsrqHandoverAlgorithm::EvaluateHandover (uint16_t rnti, uint8_t servingCellRsrq) private
Called when Event A2 is detected, then trigger a handover if needed.
Parameters
rnti The RNTI of the UE who reported the event.
servingCellRsrq The RSRQ of this cell as reported by the UE.
Definition at line 182 of file a2-a4-rsrq-handover-algorithm.cc.
References IsValidNeighbour(), m_handoverManagementSapUser, m_neighbourCellMeasures, m_neighbourCellOffset, NS_LOG_FUNCTION, NS_LOG_LOGIC(), NS_LOG_WARN, and ns3::LteHandoverManagementSapUser::TriggerHandover().
Referenced by DoReportUeMeas().
GetLteHandoverManagementSapProvider()
LteHandoverManagementSapProvider * ns3::A2A4RsrqHandoverAlgorithm::GetLteHandoverManagementSapProvider () virtual
Export the "provider" part of the Handover Management SAP interface.
Returns
the reference to the "provider" part of the interface, typically to be kept by an LteEnbRrc instance
Implements ns3::LteHandoverAlgorithm.
Definition at line 98 of file a2-a4-rsrq-handover-algorithm.cc.
References m_handoverManagementSapProvider, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::A2A4RsrqHandoverAlgorithm::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 63 of file a2-a4-rsrq-handover-algorithm.cc.
References m_neighbourCellOffset, m_servingCellThreshold, ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
IsValidNeighbour()
bool ns3::A2A4RsrqHandoverAlgorithm::IsValidNeighbour (uint16_t cellId) private
Determines if a neighbour cell is a valid destination for handover.
Currently always return true.
Parameters
cellId The cell ID of the neighbour cell.
Returns
True if the cell is a valid destination for handover.
Todo:
In the future, this function can be expanded to validate whether the neighbour cell is a valid target cell, e.g., taking into account the NRT in ANR and whether it is a CSG cell with closed access.
Definition at line 234 of file a2-a4-rsrq-handover-algorithm.cc.
References NS_LOG_FUNCTION.
Referenced by EvaluateHandover().
SetLteHandoverManagementSapUser()
void ns3::A2A4RsrqHandoverAlgorithm::SetLteHandoverManagementSapUser (LteHandoverManagementSapUser * s) virtual
Set the "user" part of the Handover Management SAP interface that this handover algorithm instance will interact with.
Parameters
s a reference to the "user" part of the interface, typically a member of an LteEnbRrc instance
Implements ns3::LteHandoverAlgorithm.
Definition at line 90 of file a2-a4-rsrq-handover-algorithm.cc.
References m_handoverManagementSapUser, and NS_LOG_FUNCTION.
UpdateNeighbourMeasurements()
void ns3::A2A4RsrqHandoverAlgorithm::UpdateNeighbourMeasurements (uint16_t rnti, uint16_t cellId, uint8_t rsrq) private
Called when Event A4 is reported, then update the measurements table.
If the RNTI and/or cell ID is not found in the table, a corresponding entry will be created. Only the latest measurements are stored in the table.
Parameters
rnti The RNTI of the UE who reported the event.
cellId The cell ID of the measured cell.
rsrq The RSRQ of the cell as measured by the UE.
Definition at line 249 of file a2-a4-rsrq-handover-algorithm.cc.
References ns3::A2A4RsrqHandoverAlgorithm::UeMeasure::m_cellId, m_neighbourCellMeasures, ns3::A2A4RsrqHandoverAlgorithm::UeMeasure::m_rsrp, ns3::A2A4RsrqHandoverAlgorithm::UeMeasure::m_rsrq, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by DoReportUeMeas().
Friends And Related Function Documentation
MemberLteHandoverManagementSapProvider< A2A4RsrqHandoverAlgorithm >
friend class MemberLteHandoverManagementSapProvider< A2A4RsrqHandoverAlgorithm > friend
let the forwarder class access the protected and private members
Definition at line 96 of file a2-a4-rsrq-handover-algorithm.h.
Referenced by A2A4RsrqHandoverAlgorithm().
Member Data Documentation
m_a2MeasId
uint8_t ns3::A2A4RsrqHandoverAlgorithm::m_a2MeasId private
The expected measurement identity for A2 measurements.
Definition at line 141 of file a2-a4-rsrq-handover-algorithm.h.
Referenced by DoInitialize(), and DoReportUeMeas().
m_a4MeasId
uint8_t ns3::A2A4RsrqHandoverAlgorithm::m_a4MeasId private
The expected measurement identity for A4 measurements.
Definition at line 143 of file a2-a4-rsrq-handover-algorithm.h.
Referenced by DoInitialize(), and DoReportUeMeas().
m_handoverManagementSapProvider
LteHandoverManagementSapProvider* ns3::A2A4RsrqHandoverAlgorithm::m_handoverManagementSapProvider private
Receive API calls from the eNodeB RRC instance.
Definition at line 190 of file a2-a4-rsrq-handover-algorithm.h.
Referenced by A2A4RsrqHandoverAlgorithm(), DoDispose(), and GetLteHandoverManagementSapProvider().
m_handoverManagementSapUser
LteHandoverManagementSapUser* ns3::A2A4RsrqHandoverAlgorithm::m_handoverManagementSapUser private
Interface to the eNodeB RRC instance.
Definition at line 188 of file a2-a4-rsrq-handover-algorithm.h.
Referenced by DoInitialize(), EvaluateHandover(), and SetLteHandoverManagementSapUser().
m_neighbourCellMeasures
MeasurementTable_t ns3::A2A4RsrqHandoverAlgorithm::m_neighbourCellMeasures private
Table of measurement reports from all UEs.
Definition at line 170 of file a2-a4-rsrq-handover-algorithm.h.
Referenced by EvaluateHandover(), and UpdateNeighbourMeasurements().
m_neighbourCellOffset
uint8_t ns3::A2A4RsrqHandoverAlgorithm::m_neighbourCellOffset private
The NeighbourCellOffset attribute.
Minimum offset between the serving and the best neighbour cell to trigger the handover. Expressed in quantized range of [0..34] as per Section 9.1.7 of 3GPP TS 36.133.
Definition at line 185 of file a2-a4-rsrq-handover-algorithm.h.
Referenced by EvaluateHandover(), and GetTypeId().
m_servingCellThreshold
uint8_t ns3::A2A4RsrqHandoverAlgorithm::m_servingCellThreshold private
The ServingCellThreshold attribute.
If the RSRQ of the serving cell is worse than this threshold, neighbour cells are consider for handover. Expressed in quantized range of [0..34] as per Section 9.1.7 of 3GPP TS 36.133.
Definition at line 178 of file a2-a4-rsrq-handover-algorithm.h.
Referenced by DoInitialize(), DoReportUeMeas(), and GetTypeId().
The documentation for this class was generated from the following files:
src/lte/model/a2-a4-rsrq-handover-algorithm.h
src/lte/model/a2-a4-rsrq-handover-algorithm.cc