ns-3: ns3::PhyListener Class Reference
ns3::PhyListener Class Reference
Listener for PHY events.
Public Member Functions
PhyListener (ns3::ChannelAccessManager *cam)
Create a PhyListener for the given ChannelAccessManager.
virtual ~PhyListener ()
void NotifyMaybeCcaBusyStart (Time duration)
void NotifyOff (void)
Notify listeners that we went to switch off.
void NotifyOn (void)
Notify listeners that we went to switch on.
void NotifyRxEndError (void)
We have received the last bit of a packet for which NotifyRxStart was invoked first and, the packet has not been successfully received.
void NotifyRxEndOk (void)
We have received the last bit of a packet for which NotifyRxStart was invoked first and, the packet has been successfully received.
void NotifyRxStart (Time duration)
void NotifySleep (void)
Notify listeners that we went to sleep.
void NotifySwitchingStart (Time duration)
void NotifyTxStart (Time duration, double txPowerDbm)
void NotifyWakeup (void)
Notify listeners that we woke up.
Public Member Functions inherited from ns3::WifiPhyListener
virtual ~WifiPhyListener ()
Private Attributes
ns3::ChannelAccessManager * m_cam
ChannelAccessManager to forward events to.
Detailed Description
Listener for PHY events.
Forwards to ChannelAccessManager
Definition at line 36 of file channel-access-manager.cc.
Constructor & Destructor Documentation
PhyListener()
ns3::PhyListener::PhyListener (ns3::ChannelAccessManager * cam) inline
Create a PhyListener for the given ChannelAccessManager.
Parameters
cam the ChannelAccessManager
Definition at line 44 of file channel-access-manager.cc.
~PhyListener()
virtual ns3::PhyListener::~PhyListener () inline virtual
Definition at line 48 of file channel-access-manager.cc.
Member Function Documentation
NotifyMaybeCcaBusyStart()
void ns3::PhyListener::NotifyMaybeCcaBusyStart (Time duration) inline virtual
Parameters
duration the expected busy duration.
This method does not really report a real state change as opposed to the other methods in this class. It merely reports that, unless the medium is reported busy through NotifyTxStart or NotifyRxStart/End, it will be busy as defined by the currently selected CCA mode.
Typical client code which wants to have a clear picture of the CCA state will need to keep track of the time at which the last NotifyCcaBusyStart method is called and what duration it reported.
Implements ns3::WifiPhyListener.
Definition at line 67 of file channel-access-manager.cc.
References aloha::duration, m_cam, and ns3::ChannelAccessManager::NotifyMaybeCcaBusyStartNow().
NotifyOff()
void ns3::PhyListener::NotifyOff (void) inline virtual
Notify listeners that we went to switch off.
Implements ns3::WifiPhyListener.
Definition at line 79 of file channel-access-manager.cc.
References m_cam, and ns3::ChannelAccessManager::NotifyOffNow().
NotifyOn()
void ns3::PhyListener::NotifyOn (void) inline virtual
Notify listeners that we went to switch on.
Implements ns3::WifiPhyListener.
Definition at line 87 of file channel-access-manager.cc.
References m_cam, and ns3::ChannelAccessManager::NotifyOnNow().
NotifyRxEndError()
void ns3::PhyListener::NotifyRxEndError (void) inline virtual
We have received the last bit of a packet for which NotifyRxStart was invoked first and, the packet has not been successfully received.
Implements ns3::WifiPhyListener.
Definition at line 59 of file channel-access-manager.cc.
References m_cam, and ns3::ChannelAccessManager::NotifyRxEndErrorNow().
NotifyRxEndOk()
void ns3::PhyListener::NotifyRxEndOk (void) inline virtual
We have received the last bit of a packet for which NotifyRxStart was invoked first and, the packet has been successfully received.
Implements ns3::WifiPhyListener.
Definition at line 55 of file channel-access-manager.cc.
References m_cam, and ns3::ChannelAccessManager::NotifyRxEndOkNow().
NotifyRxStart()
void ns3::PhyListener::NotifyRxStart (Time duration) inline virtual
Parameters
duration the expected duration of the packet reception.
We have received the first bit of a packet. We decided that we could synchronize on this packet. It does not mean we will be able to successfully receive completely the whole packet. It means that we will report a BUSY status until one of the following happens:
NotifyRxEndOk
NotifyRxEndError
NotifyTxStart
Implements ns3::WifiPhyListener.
Definition at line 51 of file channel-access-manager.cc.
References aloha::duration, m_cam, and ns3::ChannelAccessManager::NotifyRxStartNow().
NotifySleep()
void ns3::PhyListener::NotifySleep (void) inline virtual
Notify listeners that we went to sleep.
Implements ns3::WifiPhyListener.
Definition at line 75 of file channel-access-manager.cc.
References m_cam, and ns3::ChannelAccessManager::NotifySleepNow().
NotifySwitchingStart()
void ns3::PhyListener::NotifySwitchingStart (Time duration) inline virtual
Parameters
duration the expected channel switching duration.
We do not send any event to notify the end of channel switching. Listeners should assume that the channel implicitly reverts to the idle or busy states.
Implements ns3::WifiPhyListener.
Definition at line 71 of file channel-access-manager.cc.
References aloha::duration, m_cam, and ns3::ChannelAccessManager::NotifySwitchingStartNow().
NotifyTxStart()
void ns3::PhyListener::NotifyTxStart (Time duration, double txPowerDbm) inline virtual
Parameters
duration the expected transmission duration.
txPowerDbm the nominal TX power in dBm
We are about to send the first bit of the packet. We do not send any event to notify the end of transmission. Listeners should assume that the channel implicitly reverts to the idle state unless they have received a CCA busy report.
Implements ns3::WifiPhyListener.
Definition at line 63 of file channel-access-manager.cc.
References aloha::duration, m_cam, and ns3::ChannelAccessManager::NotifyTxStartNow().
NotifyWakeup()
void ns3::PhyListener::NotifyWakeup (void) inline virtual
Notify listeners that we woke up.
Implements ns3::WifiPhyListener.
Definition at line 83 of file channel-access-manager.cc.
References m_cam, and ns3::ChannelAccessManager::NotifyWakeupNow().
Member Data Documentation
m_cam
ns3::ChannelAccessManager* ns3::PhyListener::m_cam private
ChannelAccessManager to forward events to.
Definition at line 93 of file channel-access-manager.cc.
Referenced by NotifyMaybeCcaBusyStart(), NotifyOff(), NotifyOn(), NotifyRxEndError(), NotifyRxEndOk(), NotifyRxStart(), NotifySleep(), NotifySwitchingStart(), NotifyTxStart(), and NotifyWakeup().
The documentation for this class was generated from the following file:
src/wifi/model/channel-access-manager.cc