ns-3: ns3::LteSimpleHelper Class Reference
ns3::LteSimpleHelper Class Reference
LTE Models » lte module tests | Test suites
A simplified version of LteHelper, that is used for creation and configuration of LTE entities for testing purposes when just a limited LteHelper functionality is wanted.
#include "lte-simple-helper.h"
Public Member Functions
LteSimpleHelper (void)
virtual ~LteSimpleHelper (void)
virtual void DoDispose (void)
Destructor implementation.
void EnableDlPdcpTraces (void)
Enable trace sinks for DL PDCP layer.
void EnableDlRlcTraces (void)
Enable trace sinks for DL RLC layer.
void EnableLogComponents (void)
Enables logging for all components of the LENA architecture.
void EnablePdcpTraces (void)
Enable trace sinks for PDCP layer.
void EnableRlcTraces (void)
Enable trace sinks for RLC layer.
void EnableTraces (void)
Enables trace sinks for MAC, RLC and PDCP.
void EnableUlPdcpTraces (void)
Enable trace sinks for UL PDCP layer.
void EnableUlRlcTraces (void)
Enable trace sinks for UL RLC layer.
NetDeviceContainer InstallEnbDevice (NodeContainer c)
create a set of eNB devices
NetDeviceContainer InstallUeDevice (NodeContainer c)
create a set of UE devices
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Public Attributes
Ptr< LteTestMac > m_enbMac
ENB MAC.
Ptr< LteTestRrc > m_enbRrc
ENB RRC.
Ptr< LteTestMac > m_ueMac
UE MAC.
Ptr< LteTestRrc > m_ueRrc
UE RRC.
Protected Member Functions
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
enum LteRlcEntityType_t { RLC_UM = 1, RLC_AM = 2 }
LteRlcEntityType_t enumeration.
Private Member Functions
Ptr< NetDevice > InstallSingleEnbDevice (Ptr< Node > n)
Install single ENB device.
Ptr< NetDevice > InstallSingleUeDevice (Ptr< Node > n)
Install single UE device.
Private Attributes
ObjectFactory m_enbDeviceFactory
ENB device factory.
Ptr< LtePdcp > m_enbPdcp
ENB PDCP.
Ptr< LteRlc > m_enbRlc
ENB RLC.
enum ns3::LteSimpleHelper::LteRlcEntityType_t m_lteRlcEntityType
RLC entity type.
Ptr< SimpleChannel > m_phyChannel
the physical channel
ObjectFactory m_ueDeviceFactory
UE device factory.
Ptr< LtePdcp > m_uePdcp
UE PDCP.
Ptr< LteRlc > m_ueRlc
UE RLC.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A simplified version of LteHelper, that is used for creation and configuration of LTE entities for testing purposes when just a limited LteHelper functionality is wanted.
Definition at line 48 of file lte-simple-helper.h.
Member Enumeration Documentation
LteRlcEntityType_t
enum ns3::LteSimpleHelper::LteRlcEntityType_t private
LteRlcEntityType_t enumeration.
Enumerator
RLC_UM
RLC_AM
Definition at line 166 of file lte-simple-helper.h.
Constructor & Destructor Documentation
LteSimpleHelper()
ns3::LteSimpleHelper::LteSimpleHelper (void)
Definition at line 39 of file lte-simple-helper.cc.
References ns3::LteSimpleNetDevice::GetTypeId(), m_enbDeviceFactory, m_ueDeviceFactory, NS_LOG_FUNCTION, and ns3::ObjectFactory::SetTypeId().
~LteSimpleHelper()
ns3::LteSimpleHelper::~LteSimpleHelper (void) virtual
Definition at line 56 of file lte-simple-helper.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::LteSimpleHelper::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 79 of file lte-simple-helper.cc.
References ns3::Object::Dispose(), ns3::Object::DoDispose(), m_enbMac, m_phyChannel, m_ueMac, and NS_LOG_FUNCTION.
DoInitialize()
void ns3::LteSimpleHelper::DoInitialize (void) protected virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 47 of file lte-simple-helper.cc.
References ns3::Object::DoInitialize(), m_phyChannel, and NS_LOG_FUNCTION.
EnableDlPdcpTraces()
void ns3::LteSimpleHelper::EnableDlPdcpTraces (void)
Enable trace sinks for DL PDCP layer.
Definition at line 359 of file lte-simple-helper.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by EnablePdcpTraces().
EnableDlRlcTraces()
void ns3::LteSimpleHelper::EnableDlRlcTraces (void)
Enable trace sinks for DL RLC layer.
Definition at line 289 of file lte-simple-helper.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by EnableRlcTraces().
EnableLogComponents()
void ns3::LteSimpleHelper::EnableLogComponents (void)
Enables logging for all components of the LENA architecture.
Definition at line 217 of file lte-simple-helper.cc.
References ns3::LOG_LEVEL_ALL, ns3::LOG_PREFIX_FUNC, ns3::LOG_PREFIX_NODE, ns3::LOG_PREFIX_TIME, and ns3::LogComponentEnable().
EnablePdcpTraces()
void ns3::LteSimpleHelper::EnablePdcpTraces (void)
Enable trace sinks for PDCP layer.
Definition at line 352 of file lte-simple-helper.cc.
References EnableDlPdcpTraces(), and EnableUlPdcpTraces().
Referenced by EnableTraces().
EnableRlcTraces()
void ns3::LteSimpleHelper::EnableRlcTraces (void)
Enable trace sinks for RLC layer.
Definition at line 242 of file lte-simple-helper.cc.
References EnableDlRlcTraces(), and EnableUlRlcTraces().
Referenced by EnableTraces().
EnableTraces()
void ns3::LteSimpleHelper::EnableTraces (void)
Enables trace sinks for MAC, RLC and PDCP.
Definition at line 234 of file lte-simple-helper.cc.
References EnablePdcpTraces(), and EnableRlcTraces().
EnableUlPdcpTraces()
void ns3::LteSimpleHelper::EnableUlPdcpTraces (void)
Enable trace sinks for UL PDCP layer.
Definition at line 370 of file lte-simple-helper.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by EnablePdcpTraces().
EnableUlRlcTraces()
void ns3::LteSimpleHelper::EnableUlRlcTraces (void)
Enable trace sinks for UL RLC layer.
Definition at line 340 of file lte-simple-helper.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by EnableRlcTraces().
GetTypeId()
TypeId ns3::LteSimpleHelper::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 61 of file lte-simple-helper.cc.
References m_lteRlcEntityType, ns3::MakeEnumAccessor(), ns3::MakeEnumChecker(), RLC_AM, RLC_UM, and ns3::TypeId::SetParent().
InstallEnbDevice()
NetDeviceContainer ns3::LteSimpleHelper::InstallEnbDevice (NodeContainer c)
create a set of eNB devices
Parameters
c the node container where the devices are to be installed
Returns
the NetDeviceContainer with the newly created devices
Definition at line 94 of file lte-simple-helper.cc.
References ns3::NodeContainer::Begin(), first::devices, ns3::NodeContainer::End(), ns3::Object::Initialize(), InstallSingleEnbDevice(), and NS_LOG_FUNCTION.
Referenced by LteRlcAmE2eTestCase::DoRun(), and LteRlcUmE2eTestCase::DoRun().
InstallSingleEnbDevice()
Ptr< NetDevice > ns3::LteSimpleHelper::InstallSingleEnbDevice (Ptr< Node > n) private
Install single ENB device.
Parameters
n the node
Returns
the device
Definition at line 124 of file lte-simple-helper.cc.
References ns3::Mac48Address::Allocate(), ns3::ObjectFactory::Create(), ns3::LteTestMac::GetLteMacSapProvider(), ns3::LteRlc::GetLteMacSapUser(), ns3::LteRlc::GetLteRlcSapProvider(), m_enbDeviceFactory, m_enbMac, m_enbPdcp, m_enbRlc, m_enbRrc, m_lteRlcEntityType, m_phyChannel, ns3::MakeCallback(), sample-rng-plot::n, NS_LOG_FUNCTION, ns3::LteTestMac::Receive(), RLC_UM, ns3::LteTestMac::SetDevice(), ns3::LteRlc::SetLcId(), ns3::LteRlc::SetLteMacSapProvider(), ns3::LteTestMac::SetLteMacSapUser(), ns3::LteRlc::SetLteRlcSapUser(), and ns3::LteRlc::SetRnti().
Referenced by InstallEnbDevice().
InstallSingleUeDevice()
Ptr< NetDevice > ns3::LteSimpleHelper::InstallSingleUeDevice (Ptr< Node > n) private
Install single UE device.
Parameters
n the node
Returns
the device
Definition at line 171 of file lte-simple-helper.cc.
References ns3::Mac48Address::Allocate(), ns3::ObjectFactory::Create(), ns3::LteTestMac::GetLteMacSapProvider(), ns3::LteRlc::GetLteMacSapUser(), ns3::LteRlc::GetLteRlcSapProvider(), m_lteRlcEntityType, m_phyChannel, m_ueDeviceFactory, m_ueMac, m_uePdcp, m_ueRlc, m_ueRrc, ns3::MakeCallback(), sample-rng-plot::n, NS_LOG_FUNCTION, ns3::LteTestMac::Receive(), RLC_UM, ns3::LteTestMac::SetDevice(), ns3::LteRlc::SetLcId(), ns3::LteRlc::SetLteMacSapProvider(), ns3::LteTestMac::SetLteMacSapUser(), ns3::LteRlc::SetLteRlcSapUser(), and ns3::LteRlc::SetRnti().
Referenced by InstallUeDevice().
InstallUeDevice()
NetDeviceContainer ns3::LteSimpleHelper::InstallUeDevice (NodeContainer c)
create a set of UE devices
Parameters
c the node container where the devices are to be installed
Returns
the NetDeviceContainer with the newly created devices
Definition at line 109 of file lte-simple-helper.cc.
References ns3::NodeContainer::Begin(), first::devices, ns3::NodeContainer::End(), InstallSingleUeDevice(), and NS_LOG_FUNCTION.
Referenced by LteRlcAmE2eTestCase::DoRun(), and LteRlcUmE2eTestCase::DoRun().
Member Data Documentation
m_enbDeviceFactory
ObjectFactory ns3::LteSimpleHelper::m_enbDeviceFactory private
ENB device factory.
Definition at line 162 of file lte-simple-helper.h.
Referenced by LteSimpleHelper(), and InstallSingleEnbDevice().
m_enbMac
Ptr<LteTestMac> ns3::LteSimpleHelper::m_enbMac
ENB MAC.
Definition at line 151 of file lte-simple-helper.h.
Referenced by DoDispose(), LteRlcAmE2eTestCase::DoRun(), LteRlcUmE2eTestCase::DoRun(), and InstallSingleEnbDevice().
m_enbPdcp
Ptr<LtePdcp> ns3::LteSimpleHelper::m_enbPdcp private
ENB PDCP.
Definition at line 156 of file lte-simple-helper.h.
Referenced by InstallSingleEnbDevice().
m_enbRlc
Ptr<LteRlc> ns3::LteSimpleHelper::m_enbRlc private
ENB RLC.
Definition at line 157 of file lte-simple-helper.h.
Referenced by InstallSingleEnbDevice().
m_enbRrc
Ptr<LteTestRrc> ns3::LteSimpleHelper::m_enbRrc
ENB RRC.
Definition at line 148 of file lte-simple-helper.h.
Referenced by LteRlcAmE2eTestCase::DoRun(), LteRlcUmE2eTestCase::DoRun(), and InstallSingleEnbDevice().
m_lteRlcEntityType
enum ns3::LteSimpleHelper::LteRlcEntityType_t ns3::LteSimpleHelper::m_lteRlcEntityType private
RLC entity type.
Referenced by GetTypeId(), InstallSingleEnbDevice(), and InstallSingleUeDevice().
m_phyChannel
Ptr<SimpleChannel> ns3::LteSimpleHelper::m_phyChannel private
the physical channel
Definition at line 144 of file lte-simple-helper.h.
Referenced by DoDispose(), DoInitialize(), InstallSingleEnbDevice(), and InstallSingleUeDevice().
m_ueDeviceFactory
ObjectFactory ns3::LteSimpleHelper::m_ueDeviceFactory private
UE device factory.
Definition at line 163 of file lte-simple-helper.h.
Referenced by LteSimpleHelper(), and InstallSingleUeDevice().
m_ueMac
Ptr<LteTestMac> ns3::LteSimpleHelper::m_ueMac
UE MAC.
Definition at line 152 of file lte-simple-helper.h.
Referenced by DoDispose(), LteRlcAmE2eTestCase::DoRun(), LteRlcUmE2eTestCase::DoRun(), and InstallSingleUeDevice().
m_uePdcp
Ptr<LtePdcp> ns3::LteSimpleHelper::m_uePdcp private
UE PDCP.
Definition at line 159 of file lte-simple-helper.h.
Referenced by InstallSingleUeDevice().
m_ueRlc
Ptr<LteRlc> ns3::LteSimpleHelper::m_ueRlc private
UE RLC.
Definition at line 160 of file lte-simple-helper.h.
Referenced by InstallSingleUeDevice().
m_ueRrc
Ptr<LteTestRrc> ns3::LteSimpleHelper::m_ueRrc
UE RRC.
Definition at line 149 of file lte-simple-helper.h.
Referenced by LteRlcAmE2eTestCase::DoRun(), LteRlcUmE2eTestCase::DoRun(), and InstallSingleUeDevice().
The documentation for this class was generated from the following files:
src/lte/test/lte-simple-helper.h
src/lte/test/lte-simple-helper.cc