ns-3: ns3::MacStatsCalculator Class Reference
ns3::MacStatsCalculator Class Reference
LTE Models
#include "mac-stats-calculator.h"
Public Member Functions
MacStatsCalculator ()
Constructor.
virtual ~MacStatsCalculator ()
Destructor.
void DlScheduling (uint16_t cellId, uint64_t imsi, DlSchedulingCallbackInfo dlSchedulingCallbackInfo)
Notifies the stats calculator that an downlink scheduling has occurred.
std::string GetDlOutputFilename (void)
Get the name of the file where the downlink statistics will be stored.
std::string GetUlOutputFilename (void)
Get the name of the file where the uplink statistics will be stored.
void SetDlOutputFilename (std::string outputFilename)
Set the name of the file where the downlink statistics will be stored.
void SetUlOutputFilename (std::string outputFilename)
Set the name of the file where the uplink statistics will be stored.
void UlScheduling (uint16_t cellId, uint64_t imsi, uint32_t frameNo, uint32_t subframeNo, uint16_t rnti, uint8_t mcsTb, uint16_t sizeTb, uint8_t componentCarrierId)
Notifies the stats calculator that an uplink scheduling has occurred.
Public Member Functions inherited from ns3::LteStatsCalculator
LteStatsCalculator ()
Constructor.
virtual ~LteStatsCalculator ()
Destructor.
bool ExistsCellIdPath (std::string path)
Checks if there is an already stored cell id for the given path.
bool ExistsImsiPath (std::string path)
Checks if there is an already stored IMSI for the given path.
uint16_t GetCellIdPath (std::string path)
Retrieves the cell id information for the given path.
std::string GetDlOutputFilename (void)
Get the name of the file where the downlink statistics will be stored.
uint64_t GetImsiPath (std::string path)
Retrieves the imsi information for the given path.
std::string GetUlOutputFilename (void)
Get the name of the file where the uplink statistics will be stored.
void SetCellIdPath (std::string path, uint16_t cellId)
Stores the (path, cellId) pairs in a map.
void SetDlOutputFilename (std::string outputFilename)
Set the name of the file where the downlink statistics will be stored.
void SetImsiPath (std::string path, uint64_t imsi)
Stores the (path, imsi) pairs in a map.
void SetUlOutputFilename (std::string outputFilename)
Set the name of the file where the uplink statistics will be stored.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static void DlSchedulingCallback (Ptr< MacStatsCalculator > macStats, std::string path, DlSchedulingCallbackInfo dlSchedulingCallbackInfo)
Trace sink for the ns3::LteEnbMac::DlScheduling trace source.
static TypeId GetTypeId (void)
Register this type.
static void UlSchedulingCallback (Ptr< MacStatsCalculator > macStats, std::string path, uint32_t frameNo, uint32_t subframeNo, uint16_t rnti, uint8_t mcs, uint16_t size, uint8_t componentCarrierId)
Trace sink for the ns3::LteEnbMac::UlScheduling trace source.
Static Public Member Functions inherited from ns3::LteStatsCalculator
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
bool m_dlFirstWrite
When writing DL MAC statistics first time to file, columns description is added.
bool m_ulFirstWrite
When writing UL MAC statistics first time to file, columns description is added.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Static Protected Member Functions inherited from ns3::LteStatsCalculator
static uint16_t FindCellIdFromEnbMac (std::string path, uint16_t rnti)
Retrieves CellId from Enb MAC path in the attribute system.
static uint16_t FindCellIdFromEnbRlcPath (std::string path)
Retrieves CellId from Enb RLC path in the attribute system.
static uint64_t FindImsiForEnb (std::string path, uint16_t rnti)
Retrieves IMSI from path for Enb in the attribute system.
static uint64_t FindImsiForUe (std::string path, uint16_t rnti)
Retrieves IMSI from path for Ue in the attribute system.
static uint64_t FindImsiFromEnbMac (std::string path, uint16_t rnti)
Retrieves IMSI from Enb MAC path in the attribute system.
static uint64_t FindImsiFromEnbRlcPath (std::string path)
Retrieves IMSI from Enb RLC path in the attribute system.
static uint64_t FindImsiFromLteNetDevice (std::string path)
Retrieves IMSI from LteNetDevice path in the attribute system.
static uint64_t FindImsiFromUePhy (std::string path)
Retrieves IMSI from Ue PHY path in the attribute system.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Takes care of storing the information generated at MAC layer. Metrics saved are:
Timestamp (in seconds)
Frame index
Subframe index
C-RNTI
MCS for transport block 1
Size of transport block 1
MCS for transport block 2 (0 if not used)
Size of transport block 2 (0 if not used)
Definition at line 48 of file mac-stats-calculator.h.
Constructor & Destructor Documentation
MacStatsCalculator()
ns3::MacStatsCalculator::MacStatsCalculator ()
Constructor.
Definition at line 34 of file mac-stats-calculator.cc.
References NS_LOG_FUNCTION.
~MacStatsCalculator()
ns3::MacStatsCalculator::~MacStatsCalculator () virtual
Destructor.
Definition at line 42 of file mac-stats-calculator.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DlScheduling()
void ns3::MacStatsCalculator::DlScheduling (uint16_t cellId, uint64_t imsi, DlSchedulingCallbackInfo dlSchedulingCallbackInfo)
Notifies the stats calculator that an downlink scheduling has occurred.
Parameters
cellId Cell ID of the attached Enb
imsi IMSI of the scheduled UE
dlSchedulingCallbackInfo the structure that contains downlink scheduling fields: frameNo Frame number subframeNo Subframe number rnti C-RNTI scheduled mcsTb1 MCS for transport block 1 sizeTb1 Size of transport block 1 mcsTb2 MCS for transport block 2 (0 if not used) sizeTb2 Size of transport block 2 (0 if not used) componentCarrierId component carrier ID
Definition at line 93 of file mac-stats-calculator.cc.
References ns3::DlSchedulingCallbackInfo::componentCarrierId, ns3::DlSchedulingCallbackInfo::frameNo, GetDlOutputFilename(), ns3::Time::GetNanoSeconds(), m_dlFirstWrite, ns3::DlSchedulingCallbackInfo::mcsTb1, ns3::DlSchedulingCallbackInfo::mcsTb2, ns3::Simulator::Now(), NS_LOG_ERROR, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::DlSchedulingCallbackInfo::rnti, ns3::DlSchedulingCallbackInfo::sizeTb1, ns3::DlSchedulingCallbackInfo::sizeTb2, and ns3::DlSchedulingCallbackInfo::subframeNo.
DlSchedulingCallback()
void ns3::MacStatsCalculator::DlSchedulingCallback (Ptr< MacStatsCalculator > macStats, std::string path, DlSchedulingCallbackInfo dlSchedulingCallbackInfo) static
Trace sink for the ns3::LteEnbMac::DlScheduling trace source.
Parameters
macStats
path
dlSchedulingCallbackInfo DlSchedulingCallbackInfo structure containing all downlink information that is generated what DlScheduling traces is fired
Definition at line 179 of file mac-stats-calculator.cc.
References ns3::LteStatsCalculator::FindCellIdFromEnbRlcPath(), ns3::LteStatsCalculator::FindImsiFromEnbRlcPath(), NS_LOG_FUNCTION, and ns3::DlSchedulingCallbackInfo::rnti.
Referenced by ns3::LteHelper::EnableDlMacTraces().
GetDlOutputFilename()
std::string ns3::MacStatsCalculator::GetDlOutputFilename (void)
Get the name of the file where the downlink statistics will be stored.
Returns
the name of the file where the downlink statistics will be stored
Definition at line 87 of file mac-stats-calculator.cc.
References ns3::LteStatsCalculator::GetDlOutputFilename().
Referenced by DlScheduling().
GetTypeId()
TypeId ns3::MacStatsCalculator::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 48 of file mac-stats-calculator.cc.
References ns3::MakeStringAccessor(), ns3::MakeStringChecker(), SetDlOutputFilename(), ns3::TypeId::SetParent(), and SetUlOutputFilename().
GetUlOutputFilename()
std::string ns3::MacStatsCalculator::GetUlOutputFilename (void)
Get the name of the file where the uplink statistics will be stored.
Returns
the name of the file where the uplink statistics will be stored
Definition at line 75 of file mac-stats-calculator.cc.
References ns3::LteStatsCalculator::GetUlOutputFilename().
Referenced by UlScheduling().
SetDlOutputFilename()
void ns3::MacStatsCalculator::SetDlOutputFilename (std::string outputFilename)
Set the name of the file where the downlink statistics will be stored.
Parameters
outputFilename string with the name of the file
Definition at line 81 of file mac-stats-calculator.cc.
References ns3::LteStatsCalculator::SetDlOutputFilename().
Referenced by GetTypeId().
SetUlOutputFilename()
void ns3::MacStatsCalculator::SetUlOutputFilename (std::string outputFilename)
Set the name of the file where the uplink statistics will be stored.
Parameters
outputFilename string with the name of the file
Definition at line 69 of file mac-stats-calculator.cc.
References ns3::LteStatsCalculator::SetUlOutputFilename().
Referenced by GetTypeId().
UlScheduling()
void ns3::MacStatsCalculator::UlScheduling (uint16_t cellId, uint64_t imsi, uint32_t frameNo, uint32_t subframeNo, uint16_t rnti, uint8_t mcsTb, uint16_t sizeTb, uint8_t componentCarrierId)
Notifies the stats calculator that an uplink scheduling has occurred.
Parameters
cellId Cell ID of the attached Enb
imsi IMSI of the scheduled UE
frameNo Frame number
subframeNo Subframe number
rnti C-RNTI scheduled
mcsTb MCS for transport block
sizeTb Size of transport block
componentCarrierId component carrier ID
Definition at line 137 of file mac-stats-calculator.cc.
References ns3::Time::GetNanoSeconds(), GetUlOutputFilename(), m_ulFirstWrite, ns3::Simulator::Now(), NS_LOG_ERROR, NS_LOG_FUNCTION, and NS_LOG_INFO.
UlSchedulingCallback()
void ns3::MacStatsCalculator::UlSchedulingCallback (Ptr< MacStatsCalculator > macStats, std::string path, uint32_t frameNo, uint32_t subframeNo, uint16_t rnti, uint8_t mcs, uint16_t size, uint8_t componentCarrierId) static
Trace sink for the ns3::LteEnbMac::UlScheduling trace source.
Parameters
macStats
path
frameNo
subframeNo
rnti
mcs
size
componentCarrierId
Definition at line 210 of file mac-stats-calculator.cc.
References ns3::LteStatsCalculator::FindCellIdFromEnbRlcPath(), ns3::LteStatsCalculator::FindImsiFromEnbRlcPath(), and NS_LOG_FUNCTION.
Referenced by ns3::LteHelper::EnableUlMacTraces().
Member Data Documentation
m_dlFirstWrite
bool ns3::MacStatsCalculator::m_dlFirstWrite private
When writing DL MAC statistics first time to file, columns description is added.
Then next lines are appended to file. This value is true if output files have not been opened yet
Definition at line 159 of file mac-stats-calculator.h.
Referenced by DlScheduling().
m_ulFirstWrite
bool ns3::MacStatsCalculator::m_ulFirstWrite private
When writing UL MAC statistics first time to file, columns description is added.
Then next lines are appended to file. This value is true if output files have not been opened yet
Definition at line 167 of file mac-stats-calculator.h.
Referenced by UlScheduling().
The documentation for this class was generated from the following files:
src/lte/helper/mac-stats-calculator.h
src/lte/helper/mac-stats-calculator.cc