ns-3: ns3::CounterCalculator< T > Class Template Reference
ns3::CounterCalculator< T > Class Template Reference
Statistics
Template class CounterCalculator.
#include "basic-data-calculators.h"
Public Member Functions
CounterCalculator ()
virtual ~CounterCalculator ()
T GetCount () const
Returns the count of the CounterCalculator.
virtual void Output (DataOutputCallback &callback) const
Outputs the data based on the provided callback.
void Update ()
Increments count by 1.
void Update (const T i)
Increments count by i.
Public Member Functions inherited from ns3::DataCalculator
DataCalculator ()
virtual ~DataCalculator ()
void Disable ()
Disables DataCalculator when simulation stops.
void Enable ()
Enables DataCalculator when simulation starts.
std::string GetContext () const
Gets the DataCalculator context.
bool GetEnabled () const
Returns whether the DataCalculator is enabled.
std::string GetKey () const
Gets the DataCalculator key.
void SetContext (const std::string context)
Sets the DataCalculator context to the provided context.
void SetKey (const std::string key)
Sets the DataCalculator key to the provided key.
virtual void Start (const Time &startTime)
Starts DataCalculator at a given time in the simulation.
virtual void Stop (const Time &stopTime)
Stops DataCalculator at a given time in the simulation.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::DataCalculator
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes
T m_count
Count value of CounterCalculator.
Protected Attributes inherited from ns3::DataCalculator
std::string m_context
Context value.
bool m_enabled
Descendant classes must check & respect m_enabled!
std::string m_key
Key value.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
template<typename T = uint32_t>
class ns3::CounterCalculator< T >
Template class CounterCalculator.
Definition at line 268 of file basic-data-calculators.h.
Constructor & Destructor Documentation
CounterCalculator()
template<typename T > ns3::CounterCalculator< T >::CounterCalculator
Definition at line 312 of file basic-data-calculators.h.
~CounterCalculator()
template<typename T > ns3::CounterCalculator< T >::~CounterCalculator virtual
Definition at line 318 of file basic-data-calculators.h.
Member Function Documentation
DoDispose()
template<typename T > void ns3::CounterCalculator< T >::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::DataCalculator.
Reimplemented in ns3::PacketCounterCalculator.
Definition at line 338 of file basic-data-calculators.h.
References ns3::DataCalculator::DoDispose().
Referenced by ns3::PacketCounterCalculator::DoDispose().
GetCount()
template<typename T > T ns3::CounterCalculator< T >::GetCount
Returns the count of the CounterCalculator.
Returns
Count as a value of type T
Definition at line 366 of file basic-data-calculators.h.
GetTypeId()
template<typename T > TypeId ns3::CounterCalculator< T >::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 324 of file basic-data-calculators.h.
References ns3::TypeId::SetParent().
Output()
template<typename T > void ns3::CounterCalculator< T >::Output (DataOutputCallback & callback) const virtual
Outputs the data based on the provided callback.
Parameters
callback
Implements ns3::DataCalculator.
Definition at line 374 of file basic-data-calculators.h.
References ns3::DataOutputCallback::OutputSingleton().
Update() [1/2]
template<typename T > void ns3::CounterCalculator< T >::Update
Increments count by 1.
Definition at line 346 of file basic-data-calculators.h.
Referenced by ns3::PacketCounterCalculator::FrameUpdate(), ns3::PacketCounterCalculator::PacketUpdate(), and Receiver::Receive().
Update() [2/2]
template<typename T > void ns3::CounterCalculator< T >::Update (const T i)
Increments count by i.
Parameters
i value of type T to increment count
Definition at line 356 of file basic-data-calculators.h.
Member Data Documentation
m_count
template<typename T = uint32_t> T ns3::CounterCalculator< T >::m_count protected
Count value of CounterCalculator.
Definition at line 304 of file basic-data-calculators.h.
The documentation for this class was generated from the following file:
src/stats/model/basic-data-calculators.h