ns-3: ns3::UdpEchoServer Class Reference
ns3::UdpEchoServer Class Reference
Applications » UdpEcho
A Udp Echo server.
#include "udp-echo-server.h"
Public Member Functions
UdpEchoServer ()
virtual ~UdpEchoServer ()
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Application
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void HandleRead (Ptr< Socket > socket)
Handle a packet reception.
virtual void StartApplication (void)
Application specific startup code.
virtual void StopApplication (void)
Application specific shutdown code.
Private Attributes
Address m_local
local multicast address
uint16_t m_port
Port on which we listen for incoming packets.
TracedCallback< Ptr< const Packet > > m_rxTrace
Callbacks for tracing the packet Rx events.
TracedCallback< Ptr< const Packet >, const Address &, const Address & > m_rxTraceWithAddresses
Callbacks for tracing the packet Rx events, includes source and destination addresses.
Ptr< Socket > m_socket
IPv4 Socket.
Ptr< Socket > m_socket6
IPv6 Socket.
Additional Inherited Members
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A Udp Echo server.
Every packet received is sent back.
Definition at line 44 of file udp-echo-server.h.
Constructor & Destructor Documentation
UdpEchoServer()
ns3::UdpEchoServer::UdpEchoServer ()
Definition at line 62 of file udp-echo-server.cc.
References NS_LOG_FUNCTION.
~UdpEchoServer()
ns3::UdpEchoServer::~UdpEchoServer () virtual
Definition at line 67 of file udp-echo-server.cc.
References m_socket, m_socket6, and NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::UdpEchoServer::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Application.
Definition at line 75 of file udp-echo-server.cc.
References ns3::Application::DoDispose(), and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::UdpEchoServer::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 42 of file udp-echo-server.cc.
References m_port, m_rxTrace, m_rxTraceWithAddresses, ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
Referenced by ns3::UdpEchoServerHelper::UdpEchoServerHelper().
HandleRead()
void ns3::UdpEchoServer::HandleRead (Ptr< Socket > socket) private
Handle a packet reception.
This function is called by lower layers.
Parameters
socket the socket the packet was received to.
Definition at line 156 of file udp-echo-server.cc.
References ns3::Inet6SocketAddress::ConvertFrom(), ns3::InetSocketAddress::ConvertFrom(), ns3::InetSocketAddress::GetIpv4(), ns3::Inet6SocketAddress::GetIpv6(), ns3::InetSocketAddress::GetPort(), ns3::Inet6SocketAddress::GetPort(), ns3::Packet::GetSize(), ns3::Socket::GetSockName(), ns3::Inet6SocketAddress::IsMatchingType(), ns3::InetSocketAddress::IsMatchingType(), m_rxTrace, m_rxTraceWithAddresses, ns3::Simulator::Now(), NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC(), ns3::Socket::RecvFrom(), ns3::Packet::RemoveAllByteTags(), ns3::Packet::RemoveAllPacketTags(), and ns3::Socket::SendTo().
Referenced by StartApplication().
StartApplication()
void ns3::UdpEchoServer::StartApplication (void) private virtual
Application specific startup code.
The StartApplication method is called at the start time specified by Start This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 82 of file udp-echo-server.cc.
References ns3::Socket::Bind(), ns3::Socket::CreateSocket(), ns3::Ipv6Address::GetAny(), ns3::Ipv4Address::GetAny(), ns3::Application::GetNode(), HandleRead(), ns3::addressUtils::IsMulticast(), ns3::TypeId::LookupByName(), m_local, m_port, m_socket, m_socket6, ns3::MakeCallback(), NS_FATAL_ERROR, NS_LOG_FUNCTION, and ns3::Socket::SetRecvCallback().
StopApplication()
void ns3::UdpEchoServer::StopApplication (void) private virtual
Application specific shutdown code.
The StopApplication method is called at the stop time specified by Stop This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 139 of file udp-echo-server.cc.
References ns3::Socket::Close(), m_socket, m_socket6, ns3::MakeNullCallback(), NS_LOG_FUNCTION, and ns3::Socket::SetRecvCallback().
Member Data Documentation
m_local
Address ns3::UdpEchoServer::m_local private
local multicast address
Definition at line 75 of file udp-echo-server.h.
Referenced by StartApplication().
m_port
uint16_t ns3::UdpEchoServer::m_port private
Port on which we listen for incoming packets.
Definition at line 72 of file udp-echo-server.h.
Referenced by GetTypeId(), and StartApplication().
m_rxTrace
TracedCallback<Ptr<const Packet> > ns3::UdpEchoServer::m_rxTrace private
Callbacks for tracing the packet Rx events.
Definition at line 78 of file udp-echo-server.h.
Referenced by GetTypeId(), and HandleRead().
m_rxTraceWithAddresses
TracedCallback<Ptr<const Packet>, const Address &, const Address &> ns3::UdpEchoServer::m_rxTraceWithAddresses private
Callbacks for tracing the packet Rx events, includes source and destination addresses.
Definition at line 81 of file udp-echo-server.h.
Referenced by GetTypeId(), and HandleRead().
m_socket
Ptr<Socket> ns3::UdpEchoServer::m_socket private
IPv4 Socket.
Definition at line 73 of file udp-echo-server.h.
Referenced by ~UdpEchoServer(), StartApplication(), and StopApplication().
m_socket6
Ptr<Socket> ns3::UdpEchoServer::m_socket6 private
IPv6 Socket.
Definition at line 74 of file udp-echo-server.h.
Referenced by ~UdpEchoServer(), StartApplication(), and StopApplication().
The documentation for this class was generated from the following files:
src/applications/model/udp-echo-server.h
src/applications/model/udp-echo-server.cc