ns-3: ns3::SpectrumValue Class Reference
ns3::SpectrumValue Class Reference
Spectrum Models
Set of values corresponding to a given SpectrumModel.
#include "spectrum-value.h"
Public Types
typedef void(* TracedCallback) (Ptr< SpectrumValue > value)
TracedCallback signature for SpectrumValue.
Public Member Functions
SpectrumValue ()
SpectrumValue (Ptr< const SpectrumModel > sm)
SpectrumValue constructor.
Bands::const_iterator ConstBandsBegin () const
Bands::const_iterator ConstBandsEnd () const
Values::const_iterator ConstValuesBegin () const
Values::const_iterator ConstValuesEnd () const
Ptr< SpectrumValue > Copy () const
Ptr< const SpectrumModel > GetSpectrumModel () const
SpectrumModelUid_t GetSpectrumModelUid () const
uint32_t GetValuesN () const
Get the number of values stored in the array.
SpectrumValue & operator*= (const SpectrumValue &rhs)
Multiply *this by the Right Hand Side of the operator, component by component.
SpectrumValue & operator*= (double rhs)
Multiply every component of *this by the value of the Right Hand Side of the operator.
SpectrumValue & operator+= (const SpectrumValue &rhs)
Add the Right Hand Side of the operator to *this, component by component.
SpectrumValue & operator+= (double rhs)
Add the value of the Right Hand Side of the operator to all components of *this.
SpectrumValue & operator-= (const SpectrumValue &rhs)
Subtract the Right Hand Side of the operator from *this, component by component.
SpectrumValue & operator-= (double rhs)
Subtract the value of the Right Hand Side of the operator from all components of *this.
SpectrumValue & operator/= (const SpectrumValue &rhs)
Divide *this by the Right Hand Side of the operator, component by component.
SpectrumValue & operator/= (double rhs)
Divide every component of *this by the value of the Right Hand Side of the operator.
SpectrumValue operator<< (int n) const
left shift operator
SpectrumValue & operator= (double rhs)
Assign each component of *this to the value of the Right Hand Side of the operator.
SpectrumValue operator>> (int n) const
right shift operator
double & operator[] (size_t index)
Access value at given frequency index.
const double & operator[] (size_t index) const
Access value at given frequency index.
const double & ValuesAt (uint32_t pos) const
Get the value element at the position.
Values::iterator ValuesBegin ()
Values::iterator ValuesEnd ()
Public Member Functions inherited from ns3::SimpleRefCount< SpectrumValue >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Member Functions
void Add (const SpectrumValue &x)
Add a SpectrumValue (element to element addition)
void Add (double s)
Add a flat value to all the current elements.
void ChangeSign ()
Change the values sign.
void Divide (const SpectrumValue &x)
Divides by a SpectrumValue (element to element division)
void Divide (double s)
Divides by a flat value to all the current elements.
void Exp (double base)
Modifies each element so that it is the base raised to each element value.
void Log ()
Applies a Log to each the elements.
void Log10 ()
Applies a Log10 to each the elements.
void Log2 ()
Applies a Log2 to each the elements.
void Multiply (const SpectrumValue &x)
Multiplies for a SpectrumValue (element to element multiplication)
void Multiply (double s)
Multiplies for a flat value to all the current elements.
void Pow (double exp)
Modifies each element so that it each element is raised to the exponent.
void ShiftLeft (int n)
Shift the values to the left.
void ShiftRight (int n)
Shift the values to the right.
void Subtract (const SpectrumValue &x)
Subtracts a SpectrumValue (element by element subtraction)
void Subtract (double s)
Subtracts a flat value to all the current elements.
Private Attributes
Ptr< const SpectrumModel > m_spectrumModel
The spectrum model.
Values m_values
Set of values which implement the codomain of the functions in the Function Space defined by SpectrumValue.
Friends
double Integral (const SpectrumValue &arg)
SpectrumValue Log (const SpectrumValue &arg)
SpectrumValue Log10 (const SpectrumValue &arg)
SpectrumValue Log2 (const SpectrumValue &arg)
double Norm (const SpectrumValue &x)
SpectrumValue operator* (const SpectrumValue &lhs, const SpectrumValue &rhs)
multiplication component-by-component (Schur product)
SpectrumValue operator* (const SpectrumValue &lhs, double rhs)
multiplication by a scalar
SpectrumValue operator* (double lhs, const SpectrumValue &rhs)
multiplication of a scalar
SpectrumValue operator+ (const SpectrumValue &lhs, const SpectrumValue &rhs)
addition operator
SpectrumValue operator+ (const SpectrumValue &lhs, double rhs)
addition operator
SpectrumValue operator+ (const SpectrumValue &rhs)
unary plus operator
SpectrumValue operator+ (double lhs, const SpectrumValue &rhs)
addition operator
SpectrumValue operator- (const SpectrumValue &lhs, const SpectrumValue &rhs)
subtraction operator
SpectrumValue operator- (const SpectrumValue &lhs, double rhs)
subtraction operator
SpectrumValue operator- (const SpectrumValue &rhs)
unary minus operator
SpectrumValue operator- (double lhs, const SpectrumValue &rhs)
subtraction operator
SpectrumValue operator/ (const SpectrumValue &lhs, const SpectrumValue &rhs)
division component-by-component
SpectrumValue operator/ (const SpectrumValue &lhs, double rhs)
division by a scalar
SpectrumValue operator/ (double lhs, const SpectrumValue &rhs)
division of a scalar
SpectrumValue Pow (const SpectrumValue &lhs, double rhs)
SpectrumValue Pow (double lhs, const SpectrumValue &rhs)
double Prod (const SpectrumValue &x)
double Sum (const SpectrumValue &x)
Detailed Description
Set of values corresponding to a given SpectrumModel.
This class implements a Function Space which can represent any function
Every instance of this class represent a particular function . The domain of the function space, i.e., , is implemented by Bands. The codomain of the function space is implemented by Values.
To every possible value of corresponds a different Function Space. Mathematical operations are defined in this Function Space; these operations are implemented by means of operator overloading.
The intended use of this class is to represent frequency-dependent things, such as power spectral densities, frequency-dependent propagation losses, spectral masks, etc.
Definition at line 58 of file spectrum-value.h.
Member Typedef Documentation
TracedCallback
typedef void(* ns3::SpectrumValue::TracedCallback) (Ptr< SpectrumValue > value)
TracedCallback signature for SpectrumValue.
Parameters
[in] value Value of the traced variable.
Deprecated:
The non-const Ptr<SpectrumPhy> argument is deprecated and will be changed to Ptr<const SpectrumPhy> in a future release.
Definition at line 525 of file spectrum-value.h.
Constructor & Destructor Documentation
SpectrumValue() [1/2]
ns3::SpectrumValue::SpectrumValue (Ptr< const SpectrumModel > sm)
SpectrumValue constructor.
Parameters
sm pointer to the SpectrumModel which implements the set of frequencies to which the values will be referring.
Warning
the intended use if that sm points to a static object which will be there for the whole simulation. This is reasonable since the set of frequencies which are to be used in the simulation is normally known before the simulation starts. Make sure that the SpectrumModel instance which sm points to has already been initialized by the time this method is invoked. The main reason is that if you initialize the SpectrumModel instance afterwards, and the memory for the underlying std::vector gets reallocated, then sm will not be a valid reference anymore. Another reason is that m_values could end up having the wrong size.
Definition at line 34 of file spectrum-value.cc.
SpectrumValue() [2/2]
ns3::SpectrumValue::SpectrumValue ()
Definition at line 30 of file spectrum-value.cc.
Member Function Documentation
Add() [1/2]
void ns3::SpectrumValue::Add (const SpectrumValue & x) private
Add a SpectrumValue (element to element addition)
Parameters
x SpectrumValue
Definition at line 107 of file spectrum-value.cc.
References m_spectrumModel, m_values, NS_ASSERT, and sample-rng-plot::x.
Referenced by ns3::operator+(), operator+=(), ns3::operator-(), and Subtract().
Add() [2/2]
void ns3::SpectrumValue::Add (double s) private
Add a flat value to all the current elements.
Parameters
s flat value
Definition at line 125 of file spectrum-value.cc.
References m_values.
ChangeSign()
void ns3::SpectrumValue::ChangeSign () private
Change the values sign.
Definition at line 232 of file spectrum-value.cc.
References m_values.
Referenced by ns3::operator-().
ConstBandsBegin()
Bands::const_iterator ns3::SpectrumValue::ConstBandsBegin () const
Returns
a const iterator pointing to the beginning of the embedded Bands
Definition at line 94 of file spectrum-value.cc.
References ns3::SpectrumModel::Begin(), and m_spectrumModel.
Referenced by ns3::ThreeGppSpectrumPropagationLossModel::CalcBeamformingGain(), ns3::WifiSpectrumValueHelper::CreateDsssTxPowerSpectralDensity(), ns3::WifiSpectrumValueHelper::CreateRfFilter(), ns3::WifiSpectrumValueHelper::CreateSpectrumMaskForOfdm(), ns3::ConstantSpectrumPropagationLossModel::DoCalcRxPowerSpectralDensity(), ns3::FriisSpectrumPropagationLossModel::DoCalcRxPowerSpectralDensity(), TvSpectrumTransmitterTestCase::DoRun(), ns3::ShannonSpectrumErrorModel::EvaluateChunk(), ns3::Integral(), and ns3::WriteAveragePowerSpectralDensityReport().
ConstBandsEnd()
Bands::const_iterator ns3::SpectrumValue::ConstBandsEnd () const
Returns
a const iterator pointing to the end of the embedded Bands
Definition at line 100 of file spectrum-value.cc.
References ns3::SpectrumModel::End(), and m_spectrumModel.
Referenced by ns3::ConstantSpectrumPropagationLossModel::DoCalcRxPowerSpectralDensity(), ns3::FriisSpectrumPropagationLossModel::DoCalcRxPowerSpectralDensity(), TvSpectrumTransmitterTestCase::DoRun(), ns3::ShannonSpectrumErrorModel::EvaluateChunk(), ns3::Integral(), and ns3::WriteAveragePowerSpectralDensityReport().
ConstValuesBegin()
Values::const_iterator ns3::SpectrumValue::ConstValuesBegin () const
Returns
a const iterator pointing to the beginning of the embedded Values
Definition at line 69 of file spectrum-value.cc.
References m_values.
Referenced by ns3::LteUePhy::ComputeAvgSinr(), ns3::LteAmc::CreateCqiFeedbacks(), ns3::LteEnbPhy::CreatePuschCqiReport(), ns3::LteEnbPhy::CreateSrsCqiReport(), LteFrTestCase::DlDataRxStart(), LteFrAreaTestCase::DlDataRxStart(), TvSpectrumTransmitterTestCase::DoRun(), WifiOfdmMaskSlopesTestCase::DoRun(), ns3::ShannonSpectrumErrorModel::EvaluateChunk(), ns3::LteUePhy::GenerateCqiRsrpRsrq(), ns3::Integral(), ns3::operator<<(), ns3::LteUePhy::ReceivePss(), ns3::LteUePhy::ReportRsReceivedPower(), LteFrTestCase::UlDataRxStart(), LteFrAreaTestCase::UlDataRxStart(), and ns3::WriteAveragePowerSpectralDensityReport().
ConstValuesEnd()
Values::const_iterator ns3::SpectrumValue::ConstValuesEnd () const
Returns
a const iterator pointing to the end of the embedded Values
Definition at line 75 of file spectrum-value.cc.
References m_values.
Referenced by ns3::LteUePhy::ComputeAvgSinr(), ns3::LteAmc::CreateCqiFeedbacks(), ns3::LteEnbPhy::CreatePuschCqiReport(), ns3::LteEnbPhy::CreateSrsCqiReport(), LteFrTestCase::DlDataRxStart(), LteFrAreaTestCase::DlDataRxStart(), TvSpectrumTransmitterTestCase::DoRun(), WifiOfdmMaskSlopesTestCase::DoRun(), ns3::ShannonSpectrumErrorModel::EvaluateChunk(), ns3::LteUePhy::GenerateCqiRsrpRsrq(), ns3::Integral(), ns3::operator<<(), ns3::LteUePhy::ReceivePss(), ns3::LteUePhy::ReportRsReceivedPower(), LteFrTestCase::UlDataRxStart(), LteFrAreaTestCase::UlDataRxStart(), and ns3::WriteAveragePowerSpectralDensityReport().
Copy()
Ptr< SpectrumValue > ns3::SpectrumValue::Copy () const
Returns
a Ptr to a copy of this instance
Definition at line 409 of file spectrum-value.cc.
References m_spectrumModel.
Referenced by ns3::SpectrumSignalParameters::SpectrumSignalParameters(), ComputeSnr(), ns3::LrWpanInterferenceHelper::GetSignalPsd(), LteUplinkSrsSinrTestCase::ReportSinr(), and ns3::LteSpectrumValueCatcher::ReportValue().
Divide() [1/2]
void ns3::SpectrumValue::Divide (const SpectrumValue & x) private
Divides by a SpectrumValue (element to element division)
Parameters
x SpectrumValue
Definition at line 198 of file spectrum-value.cc.
References m_spectrumModel, m_values, NS_ASSERT, and sample-rng-plot::x.
Referenced by ns3::operator/(), and operator/=().
Divide() [2/2]
void ns3::SpectrumValue::Divide (double s) private
Divides by a flat value to all the current elements.
Parameters
s flat value
Definition at line 216 of file spectrum-value.cc.
References m_values, and NS_LOG_FUNCTION.
Exp()
void ns3::SpectrumValue::Exp (double base) private
Modifies each element so that it is the base raised to each element value.
Parameters
base the base
Definition at line 294 of file spectrum-value.cc.
References m_values, and NS_LOG_FUNCTION.
Referenced by ns3::Pow().
GetSpectrumModel()
Ptr< const SpectrumModel > ns3::SpectrumValue::GetSpectrumModel () const
Returns
the embedded SpectrumModel
Definition at line 62 of file spectrum-value.cc.
References m_spectrumModel.
Referenced by ns3::WifiSpectrumValueHelper::CreateDsssTxPowerSpectralDensity(), ns3::WifiSpectrumValueHelper::CreateHeOfdmTxPowerSpectralDensity(), ns3::WifiSpectrumValueHelper::CreateHtOfdmTxPowerSpectralDensity(), ns3::WifiSpectrumValueHelper::CreateOfdmTxPowerSpectralDensity(), ns3::WifiSpectrumValueHelper::CreateRfFilter(), ns3::WifiSpectrumValueHelper::CreateSpectrumMaskForOfdm(), SpectrumValueTestCase::DoRun(), ns3::LteChunkProcessor::EvaluateChunk(), ns3::SpectrumAnalyzer::GenerateReport(), ns3::HalfDuplexIdealPhy::GetRxSpectrumModel(), ns3::LrWpanPhy::GetRxSpectrumModel(), ns3::WifiSpectrumValueHelper::NormalizeSpectrumMask(), ns3::SpectrumWifiPhy::StartTx(), and Bug2843TestCase::StoreDistinctTuple().
GetSpectrumModelUid()
SpectrumModelUid_t ns3::SpectrumValue::GetSpectrumModelUid () const
Returns
the uid of the embedded SpectrumModel
Definition at line 55 of file spectrum-value.cc.
References ns3::SpectrumModel::GetUid(), and m_spectrumModel.
Referenced by LteDownlinkPowerControlSpectrumValueTestCase::DoRun(), LteNoisePsdTestCase::DoRun(), and LteTxPsdTestCase::DoRun().
GetValuesN()
uint32_t ns3::SpectrumValue::GetValuesN () const
Get the number of values stored in the array.
Returns
the values array size
Definition at line 696 of file spectrum-value.cc.
References m_values.
Log()
void ns3::SpectrumValue::Log () private
Applies a Log to each the elements.
Definition at line 335 of file spectrum-value.cc.
References m_values, and NS_LOG_FUNCTION.
Log10()
void ns3::SpectrumValue::Log10 () private
Applies a Log10 to each the elements.
Definition at line 308 of file spectrum-value.cc.
References m_values, and NS_LOG_FUNCTION.
Log2()
void ns3::SpectrumValue::Log2 () private
Applies a Log2 to each the elements.
Definition at line 321 of file spectrum-value.cc.
References m_values, and NS_LOG_FUNCTION.
Multiply() [1/2]
void ns3::SpectrumValue::Multiply (const SpectrumValue & x) private
Multiplies for a SpectrumValue (element to element multiplication)
Parameters
x SpectrumValue
Definition at line 165 of file spectrum-value.cc.
References m_spectrumModel, m_values, NS_ASSERT, and sample-rng-plot::x.
Referenced by ns3::operator*(), and operator*=().
Multiply() [2/2]
void ns3::SpectrumValue::Multiply (double s) private
Multiplies for a flat value to all the current elements.
Parameters
s flat value
Definition at line 183 of file spectrum-value.cc.
References m_values.
operator*=() [1/2]
SpectrumValue & ns3::SpectrumValue::operator*= (const SpectrumValue & rhs)
Multiply *this by the Right Hand Side of the operator, component by component.
Parameters
rhs the Right Hand Side
Returns
a reference to *this
Definition at line 621 of file spectrum-value.cc.
References Multiply().
operator*=() [2/2]
SpectrumValue & ns3::SpectrumValue::operator*= (double rhs)
Multiply every component of *this by the value of the Right Hand Side of the operator.
Parameters
rhs the Right Hand Side
Returns
a reference to *this
Definition at line 650 of file spectrum-value.cc.
References Multiply().
operator+=() [1/2]
SpectrumValue & ns3::SpectrumValue::operator+= (const SpectrumValue & rhs)
Add the Right Hand Side of the operator to *this, component by component.
Parameters
rhs the Right Hand Side
Returns
a reference to *this
Definition at line 607 of file spectrum-value.cc.
References Add().
operator+=() [2/2]
SpectrumValue & ns3::SpectrumValue::operator+= (double rhs)
Add the value of the Right Hand Side of the operator to all components of *this.
Parameters
rhs the Right Hand Side
Returns
a reference to *this
Definition at line 636 of file spectrum-value.cc.
References Add().
operator-=() [1/2]
SpectrumValue & ns3::SpectrumValue::operator-= (const SpectrumValue & rhs)
Subtract the Right Hand Side of the operator from *this, component by component.
Parameters
rhs the Right Hand Side
Returns
a reference to *this
Definition at line 614 of file spectrum-value.cc.
References Subtract().
operator-=() [2/2]
SpectrumValue & ns3::SpectrumValue::operator-= (double rhs)
Subtract the value of the Right Hand Side of the operator from all components of *this.
Parameters
rhs the Right Hand Side
Returns
a reference to *this
Definition at line 643 of file spectrum-value.cc.
References Subtract().
operator/=() [1/2]
SpectrumValue & ns3::SpectrumValue::operator/= (const SpectrumValue & rhs)
Divide *this by the Right Hand Side of the operator, component by component.
Parameters
rhs the Right Hand Side
Returns
a reference to *this
Definition at line 628 of file spectrum-value.cc.
References Divide().
operator/=() [2/2]
SpectrumValue & ns3::SpectrumValue::operator/= (double rhs)
Divide every component of *this by the value of the Right Hand Side of the operator.
Parameters
rhs the Right Hand Side
Returns
a reference to *this
Definition at line 657 of file spectrum-value.cc.
References Divide().
operator<<()
SpectrumValue ns3::SpectrumValue::operator<< (int n) const
left shift operator
Parameters
n position to shift
Returns
the value of *this left shifted by n positions. In other words, the function of the set of frequencies represented by *this is left-shifted in frequency by n positions.
Definition at line 679 of file spectrum-value.cc.
References sample-rng-plot::n, and ShiftLeft().
operator=()
SpectrumValue & ns3::SpectrumValue::operator= (double rhs)
Assign each component of *this to the value of the Right Hand Side of the operator.
Parameters
rhs
Returns
Definition at line 665 of file spectrum-value.cc.
References m_values.
operator>>()
SpectrumValue ns3::SpectrumValue::operator>> (int n) const
right shift operator
Parameters
n position to shift
Returns
the value of *this right shifted by n positions. In other words, the function of the set of frequencies represented by *this is left-shifted in frequency by n positions.
Definition at line 688 of file spectrum-value.cc.
References sample-rng-plot::n, and ShiftRight().
operator[]() [1/2]
double & ns3::SpectrumValue::operator[] (size_t index)
Access value at given frequency index.
Parameters
index the given frequency index
Returns
reference to the value
Definition at line 42 of file spectrum-value.cc.
References m_values.
operator[]() [2/2]
const double & ns3::SpectrumValue::operator[] (size_t index) const
Access value at given frequency index.
Parameters
index the given frequency index
Returns
const reference to the value
Definition at line 48 of file spectrum-value.cc.
References m_values.
Pow()
void ns3::SpectrumValue::Pow (double exp) private
Modifies each element so that it each element is raised to the exponent.
Parameters
exp the exponent
Definition at line 280 of file spectrum-value.cc.
References m_values, and NS_LOG_FUNCTION.
ShiftLeft()
void ns3::SpectrumValue::ShiftLeft (int n) private
Shift the values to the left.
Definition at line 245 of file spectrum-value.cc.
References m_values, and sample-rng-plot::n.
Referenced by operator<<().
ShiftRight()
void ns3::SpectrumValue::ShiftRight (int n) private
Shift the values to the right.
Definition at line 262 of file spectrum-value.cc.
References m_values, and sample-rng-plot::n.
Referenced by operator>>().
Subtract() [1/2]
void ns3::SpectrumValue::Subtract (const SpectrumValue & x) private
Subtracts a SpectrumValue (element by element subtraction)
Parameters
x SpectrumValue
Definition at line 139 of file spectrum-value.cc.
References m_spectrumModel, m_values, NS_ASSERT, and sample-rng-plot::x.
Referenced by ns3::operator-(), and operator-=().
Subtract() [2/2]
void ns3::SpectrumValue::Subtract (double s) private
Subtracts a flat value to all the current elements.
Parameters
s flat value
Definition at line 157 of file spectrum-value.cc.
References Add().
ValuesAt()
const double & ns3::SpectrumValue::ValuesAt (uint32_t pos) const
Get the value element at the position.
Parameters
pos position
Returns
the value element in that position (with bounds checking)
Definition at line 702 of file spectrum-value.cc.
References m_values.
ValuesBegin()
Values::iterator ns3::SpectrumValue::ValuesBegin ()
Returns
an iterator pointing to the beginning of the embedded Values
Definition at line 82 of file spectrum-value.cc.
References m_values.
Referenced by ns3::ThreeGppSpectrumPropagationLossModel::CalcBeamformingGain(), ns3::SpectrumConverter::Convert(), ns3::WifiSpectrumValueHelper::CreateDsssTxPowerSpectralDensity(), ns3::WifiSpectrumValueHelper::CreateRfFilter(), ns3::WifiSpectrumValueHelper::CreateSpectrumMaskForOfdm(), ns3::ConstantSpectrumPropagationLossModel::DoCalcRxPowerSpectralDensity(), ns3::FriisSpectrumPropagationLossModel::DoCalcRxPowerSpectralDensity(), ns3::TraceFadingLossModel::DoCalcRxPowerSpectralDensity(), ns3::LteMiErrorModel::GetPcfichPdcchError(), and ns3::WifiSpectrumValueHelper::NormalizeSpectrumMask().
ValuesEnd()
Values::iterator ns3::SpectrumValue::ValuesEnd ()
Returns
an iterator pointing to the end of the embedded Values
Definition at line 88 of file spectrum-value.cc.
References m_values.
Referenced by ns3::ThreeGppSpectrumPropagationLossModel::CalcBeamformingGain(), ns3::ConstantSpectrumPropagationLossModel::DoCalcRxPowerSpectralDensity(), ns3::FriisSpectrumPropagationLossModel::DoCalcRxPowerSpectralDensity(), ns3::TraceFadingLossModel::DoCalcRxPowerSpectralDensity(), and ns3::LteMiErrorModel::GetPcfichPdcchError().
Friends And Related Function Documentation
Integral
double Integral (const SpectrumValue & arg) friend
Parameters
arg the argument
Returns
the value of the integral
Definition at line 390 of file spectrum-value.cc.
Log
SpectrumValue Log (const SpectrumValue & arg) friend
Parameters
arg the argument
Returns
the logarithm in base e of all values in the argument
Definition at line 599 of file spectrum-value.cc.
Referenced by ns3::Log().
Log10
SpectrumValue Log10 (const SpectrumValue & arg) friend
Parameters
arg the argument
Returns
the logarithm in base 10 of all values in the argument
Definition at line 583 of file spectrum-value.cc.
Referenced by ns3::Log10().
Log2
SpectrumValue Log2 (const SpectrumValue & arg) friend
Parameters
arg the argument
Returns
the logarithm in base 2 of all values in the argument
Definition at line 591 of file spectrum-value.cc.
Referenced by ns3::Log2().
Norm
double Norm (const SpectrumValue & x) friend
Parameters
x the operand
Returns
the euclidean norm, i.e., the sum of the squares of all the values in x
Definition at line 348 of file spectrum-value.cc.
operator* [1/3]
SpectrumValue operator* (const SpectrumValue & lhs, const SpectrumValue & rhs) friend
multiplication component-by-component (Schur product)
Parameters
lhs Left Hand Side of the operator
rhs Right Hand Side of the operator
Returns
the value of lhs * rhs
Definition at line 496 of file spectrum-value.cc.
operator* [2/3]
SpectrumValue operator* (const SpectrumValue & lhs, double rhs) friend
multiplication by a scalar
Parameters
lhs Left Hand Side of the operator
rhs Right Hand Side of the operator
Returns
the value of lhs * rhs
Definition at line 505 of file spectrum-value.cc.
operator* [3/3]
SpectrumValue operator* (double lhs, const SpectrumValue & rhs) friend
multiplication of a scalar
Parameters
lhs Left Hand Side of the operator
rhs Right Hand Side of the operator
Returns
the value of lhs * rhs
Definition at line 514 of file spectrum-value.cc.
operator+ [1/4]
SpectrumValue operator+ (const SpectrumValue & lhs, const SpectrumValue & rhs) friend
addition operator
Parameters
lhs Left Hand Side of the operator
rhs Right Hand Side of the operator
Returns
the value of lhs + rhs
Definition at line 441 of file spectrum-value.cc.
operator+ [2/4]
SpectrumValue operator+ (const SpectrumValue & lhs, double rhs) friend
addition operator
Parameters
lhs Left Hand Side of the operator
rhs Right Hand Side of the operator
Returns
the value of lhs + rhs
Definition at line 450 of file spectrum-value.cc.
operator+ [3/4]
SpectrumValue operator+ (const SpectrumValue & rhs) friend
unary plus operator
Parameters
rhs Right Hand Side of the operator
Returns
the value of *this
Definition at line 550 of file spectrum-value.cc.
operator+ [4/4]
SpectrumValue operator+ (double lhs, const SpectrumValue & rhs) friend
addition operator
Parameters
lhs Left Hand Side of the operator
rhs Right Hand Side of the operator
Returns
the value of lhs + rhs
Definition at line 459 of file spectrum-value.cc.
operator- [1/4]
SpectrumValue operator- (const SpectrumValue & lhs, const SpectrumValue & rhs) friend
subtraction operator
Parameters
lhs Left Hand Side of the operator
rhs Right Hand Side of the operator
Returns
the value of lhs - rhs
Definition at line 468 of file spectrum-value.cc.
operator- [2/4]
SpectrumValue operator- (const SpectrumValue & lhs, double rhs) friend
subtraction operator
Parameters
lhs Left Hand Side of the operator
rhs Right Hand Side of the operator
Returns
the value of lhs - rhs
Definition at line 479 of file spectrum-value.cc.
operator- [3/4]
SpectrumValue operator- (const SpectrumValue & rhs) friend
unary minus operator
Parameters
rhs Right Hand Side of the operator
Returns
the value of - *this
Definition at line 556 of file spectrum-value.cc.
operator- [4/4]
SpectrumValue operator- (double lhs, const SpectrumValue & rhs) friend
subtraction operator
Parameters
lhs Left Hand Side of the operator
rhs Right Hand Side of the operator
Returns
the value of lhs - rhs
Definition at line 488 of file spectrum-value.cc.
operator/ [1/3]
SpectrumValue operator/ (const SpectrumValue & lhs, const SpectrumValue & rhs) friend
division component-by-component
Parameters
lhs Left Hand Side of the operator
rhs Right Hand Side of the operator
Returns
the value of lhs / rhs
Definition at line 523 of file spectrum-value.cc.
operator/ [2/3]
SpectrumValue operator/ (const SpectrumValue & lhs, double rhs) friend
division by a scalar
Parameters
lhs Left Hand Side of the operator
rhs Right Hand Side of the operator
Returns
the value of *this / rhs
Definition at line 532 of file spectrum-value.cc.
operator/ [3/3]
SpectrumValue operator/ (double lhs, const SpectrumValue & rhs) friend
division of a scalar
Parameters
lhs Left Hand Side of the operator
rhs Right Hand Side of the operator
Returns
the value of *this / rhs
Definition at line 541 of file spectrum-value.cc.
Pow [1/2]
SpectrumValue Pow (const SpectrumValue & lhs, double rhs) friend
Parameters
lhs the base
rhs the exponent
Returns
each value in base raised to the exponent
Definition at line 574 of file spectrum-value.cc.
Referenced by ns3::Pow().
Pow [2/2]
SpectrumValue Pow (double lhs, const SpectrumValue & rhs) friend
Parameters
lhs the base
rhs the exponent
Returns
the value in base raised to each value in the exponent
Definition at line 565 of file spectrum-value.cc.
Prod
double Prod (const SpectrumValue & x) friend
Parameters
x the operand
Returns
the product of all the values in x
Definition at line 377 of file spectrum-value.cc.
Sum
double Sum (const SpectrumValue & x) friend
Parameters
x the operand
Returns
the sum of all the values in x
Definition at line 362 of file spectrum-value.cc.
Member Data Documentation
m_spectrumModel
Ptr<const SpectrumModel> ns3::SpectrumValue::m_spectrumModel private
The spectrum model.
Definition at line 607 of file spectrum-value.h.
Referenced by Add(), ConstBandsBegin(), ConstBandsEnd(), Copy(), Divide(), GetSpectrumModel(), GetSpectrumModelUid(), Multiply(), and Subtract().
m_values
Values ns3::SpectrumValue::m_values private
Set of values which implement the codomain of the functions in the Function Space defined by SpectrumValue.
There is no restriction on what these values represent (a transmission power density, a propagation loss, etc.).
Definition at line 617 of file spectrum-value.h.
Referenced by Add(), ChangeSign(), ConstValuesBegin(), ConstValuesEnd(), Divide(), Exp(), GetValuesN(), Log(), Log10(), Log2(), Multiply(), operator=(), operator[](), Pow(), ShiftLeft(), ShiftRight(), Subtract(), ValuesAt(), ValuesBegin(), and ValuesEnd().
The documentation for this class was generated from the following files:
src/spectrum/model/spectrum-value.h
src/spectrum/model/spectrum-value.cc