ns-3: ns3::LoopbackNetDevice Class Reference
ns3::LoopbackNetDevice Class Reference
Network » Network Device | Internet
Virtual network interface that loops back any data sent to it to be immediately received on the same interface.
#include "loopback-net-device.h"
Public Member Functions
LoopbackNetDevice ()
virtual void AddLinkChangeCallback (Callback< void > callback)
virtual Address GetAddress (void) const
virtual Address GetBroadcast (void) const
virtual Ptr< Channel > GetChannel (void) const
virtual uint32_t GetIfIndex (void) const
virtual uint16_t GetMtu (void) const
virtual Address GetMulticast (Ipv4Address multicastGroup) const
Make and return a MAC multicast address using the provided multicast group.
virtual Address GetMulticast (Ipv6Address addr) const
Get the MAC multicast address corresponding to the IPv6 address provided.
virtual Ptr< Node > GetNode (void) const
virtual bool IsBridge (void) const
Return true if the net device is acting as a bridge.
virtual bool IsBroadcast (void) const
virtual bool IsLinkUp (void) const
virtual bool IsMulticast (void) const
virtual bool IsPointToPoint (void) const
Return true if the net device is on a point-to-point link.
virtual bool NeedsArp (void) const
virtual bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)
virtual bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
virtual void SetAddress (Address address)
Set the address of this interface.
virtual void SetIfIndex (const uint32_t index)
virtual bool SetMtu (const uint16_t mtu)
virtual void SetNode (Ptr< Node > node)
virtual void SetPromiscReceiveCallback (PromiscReceiveCallback cb)
virtual void SetReceiveCallback (NetDevice::ReceiveCallback cb)
virtual bool SupportsSendFrom (void) const
Public Member Functions inherited from ns3::NetDevice
virtual ~NetDevice ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::NetDevice
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void Receive (Ptr< Packet > packet, uint16_t protocol, Mac48Address to, Mac48Address from)
Receive a packet from tge Loopback NetDevice.
Private Attributes
Mac48Address m_address
NetDevice MAC address.
uint32_t m_ifIndex
interface index
uint16_t m_mtu
device MTU
Ptr< Node > m_node
the node this NetDevice is associated with
NetDevice::PromiscReceiveCallback m_promiscCallback
The callback used to notify higher layers that a packet has been received in promiscuous mode.
NetDevice::ReceiveCallback m_rxCallback
The callback used to notify higher layers that a packet has been received.
Additional Inherited Members
Public Types inherited from ns3::NetDevice
typedef void(* LinkChangeTracedCallback) (void)
TracedCallback signature for link changed event.
enum PacketType {
PACKET_HOST = 1, NS3_PACKET_HOST = PACKET_HOST, PACKET_BROADCAST, NS3_PACKET_BROADCAST = PACKET_BROADCAST,
PACKET_MULTICAST, NS3_PACKET_MULTICAST = PACKET_MULTICAST, PACKET_OTHERHOST, NS3_PACKET_OTHERHOST = PACKET_OTHERHOST
}
Packet types are used as they are in Linux.
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address &, const Address &, enum PacketType > PromiscReceiveCallback
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address & > ReceiveCallback
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Virtual network interface that loops back any data sent to it to be immediately received on the same interface.
This NetDevice is automatically added to any node as soon as the Internet stack is initialized.
Definition at line 42 of file loopback-net-device.h.
Constructor & Destructor Documentation
LoopbackNetDevice()
ns3::LoopbackNetDevice::LoopbackNetDevice ()
Definition at line 44 of file loopback-net-device.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
AddLinkChangeCallback()
void ns3::LoopbackNetDevice::AddLinkChangeCallback (Callback< void > callback) virtual
Parameters
callback the callback to invoke
Add a callback invoked whenever the link status changes to UP. This callback is typically used by the IP/ARP layer to flush the ARP cache and by IPv6 stack to flush NDISC cache whenever the link goes up.
Implements ns3::NetDevice.
Definition at line 132 of file loopback-net-device.cc.
DoDispose()
void ns3::LoopbackNetDevice::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 225 of file loopback-net-device.cc.
References ns3::Object::DoDispose(), and m_node.
GetAddress()
Address ns3::LoopbackNetDevice::GetAddress (void) const virtual
Returns
the current Address of this interface.
Implements ns3::NetDevice.
Definition at line 107 of file loopback-net-device.cc.
References m_address.
GetBroadcast()
Address ns3::LoopbackNetDevice::GetBroadcast (void) const virtual
Returns
the broadcast address supported by this netdevice.
Calling this method is invalid if IsBroadcast returns not true.
Implements ns3::NetDevice.
Definition at line 142 of file loopback-net-device.cc.
Referenced by Send().
GetChannel()
Ptr< Channel > ns3::LoopbackNetDevice::GetChannel (void) const virtual
Returns
the channel this NetDevice is connected to. The value returned can be zero if the NetDevice is not yet connected to any channel or if the underlying NetDevice has no concept of a channel. i.e., callers must check for zero and be ready to handle it.
Implements ns3::NetDevice.
Definition at line 95 of file loopback-net-device.cc.
GetIfIndex()
uint32_t ns3::LoopbackNetDevice::GetIfIndex (void) const virtual
Returns
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 89 of file loopback-net-device.cc.
References m_ifIndex.
GetMtu()
uint16_t ns3::LoopbackNetDevice::GetMtu (void) const virtual
Returns
the link-level MTU in bytes for this interface.
This value is typically used by the IP layer to perform IP fragmentation when needed.
Implements ns3::NetDevice.
Definition at line 120 of file loopback-net-device.cc.
References m_mtu.
GetMulticast() [1/2]
Address ns3::LoopbackNetDevice::GetMulticast (Ipv4Address multicastGroup) const virtual
Make and return a MAC multicast address using the provided multicast group.
RFC 1112 says that an Ipv4 host group address is mapped to an Ethernet multicast address by placing the low-order 23-bits of the IP address into the low-order 23 bits of the Ethernet multicast address 01-00-5E-00-00-00 (hex). Similar RFCs exist for Ipv6 and Eui64 mappings. This method performs the multicast address creation function appropriate to the underlying MAC address of the device. This MAC address is encapsulated in an abstract Address to avoid dependencies on the exact MAC address format.
In the case of net devices that do not support multicast, clients are expected to test NetDevice::IsMulticast and avoid attempting to map multicast packets. Subclasses of NetDevice that do support multicasting are expected to override this method and provide an implementation appropriate to the particular device.
Parameters
multicastGroup The IP address for the multicast group destination of the packet.
Returns
The MAC multicast Address used to send packets to the provided multicast group.
Warning
Calling this method is invalid if IsMulticast returns not true.
See also
IsMulticast()
Implements ns3::NetDevice.
Definition at line 157 of file loopback-net-device.cc.
References ns3::Mac48Address::GetMulticast().
GetMulticast() [2/2]
Address ns3::LoopbackNetDevice::GetMulticast (Ipv6Address addr) const virtual
Get the MAC multicast address corresponding to the IPv6 address provided.
Parameters
addr IPv6 address
Returns
the MAC multicast address
Warning
Calling this method is invalid if IsMulticast returns not true.
Implements ns3::NetDevice.
Definition at line 162 of file loopback-net-device.cc.
References ns3::Mac48Address::GetMulticast().
GetNode()
Ptr< Node > ns3::LoopbackNetDevice::GetNode (void) const virtual
Returns
the node base class which contains this network interface.
When a subclass needs to get access to the underlying node base class to print the nodeid for example, it can invoke this method.
Implements ns3::NetDevice.
Definition at line 201 of file loopback-net-device.cc.
References m_node.
GetTypeId()
TypeId ns3::LoopbackNetDevice::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 34 of file loopback-net-device.cc.
References ns3::TypeId::SetParent().
IsBridge()
bool ns3::LoopbackNetDevice::IsBridge (void) const virtual
Return true if the net device is acting as a bridge.
Returns
value of m_isBridge flag
Implements ns3::NetDevice.
Definition at line 174 of file loopback-net-device.cc.
IsBroadcast()
bool ns3::LoopbackNetDevice::IsBroadcast (void) const virtual
Returns
true if this interface supports a broadcast address, false otherwise.
Implements ns3::NetDevice.
Definition at line 136 of file loopback-net-device.cc.
IsLinkUp()
bool ns3::LoopbackNetDevice::IsLinkUp (void) const virtual
Returns
true if link is up; false otherwise
Implements ns3::NetDevice.
Definition at line 126 of file loopback-net-device.cc.
IsMulticast()
bool ns3::LoopbackNetDevice::IsMulticast (void) const virtual
Returns
value of m_isMulticast flag
Implements ns3::NetDevice.
Definition at line 149 of file loopback-net-device.cc.
IsPointToPoint()
bool ns3::LoopbackNetDevice::IsPointToPoint (void) const virtual
Return true if the net device is on a point-to-point link.
Returns
value of m_isPointToPoint flag
Implements ns3::NetDevice.
Definition at line 168 of file loopback-net-device.cc.
NeedsArp()
bool ns3::LoopbackNetDevice::NeedsArp (void) const virtual
Returns
true if ARP is needed, false otherwise.
Called by higher-layers to check if this NetDevice requires ARP to be used.
Implements ns3::NetDevice.
Definition at line 213 of file loopback-net-device.cc.
Receive()
void ns3::LoopbackNetDevice::Receive (Ptr< Packet > packet, uint16_t protocol, Mac48Address to, Mac48Address from) private
Receive a packet from tge Loopback NetDevice.
Parameters
packet a reference to the received packet
protocol the protocol
to destination address
from source address
Definition at line 54 of file loopback-net-device.cc.
References ns3::Mac48Address::IsBroadcast(), ns3::Mac48Address::IsGroup(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_address, m_promiscCallback, m_rxCallback, NS_LOG_FUNCTION, ns3::NetDevice::PACKET_HOST, ns3::NetDevice::PACKET_MULTICAST, and ns3::NetDevice::PACKET_OTHERHOST.
Referenced by Send(), and SendFrom().
Send()
bool ns3::LoopbackNetDevice::Send (Ptr< Packet > packet, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device to the specified destination Address
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 180 of file loopback-net-device.cc.
References ns3::Mac48Address::ConvertFrom(), GetBroadcast(), ns3::Node::GetId(), m_address, m_node, NS_ASSERT_MSG(), NS_LOG_FUNCTION, Receive(), ns3::Simulator::ScheduleWithContext(), and ns3::Seconds().
SendFrom()
bool ns3::LoopbackNetDevice::SendFrom (Ptr< Packet > packet, const Address & source, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
source source mac address (so called "MAC spoofing")
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device with the specified source and destination Addresses.
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 190 of file loopback-net-device.cc.
References ns3::Mac48Address::ConvertFrom(), ns3::Node::GetId(), ns3::Mac48Address::IsBroadcast(), m_address, m_node, NS_ASSERT_MSG(), NS_LOG_FUNCTION, Receive(), ns3::Simulator::ScheduleWithContext(), and ns3::Seconds().
SetAddress()
void ns3::LoopbackNetDevice::SetAddress (Address address) virtual
Set the address of this interface.
Parameters
address address to set
Implements ns3::NetDevice.
Definition at line 101 of file loopback-net-device.cc.
References first::address, ns3::Mac48Address::ConvertFrom(), and m_address.
SetIfIndex()
void ns3::LoopbackNetDevice::SetIfIndex (const uint32_t index) virtual
Parameters
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 83 of file loopback-net-device.cc.
References m_ifIndex.
SetMtu()
bool ns3::LoopbackNetDevice::SetMtu (const uint16_t mtu) virtual
Parameters
mtu MTU value, in bytes, to set for the device
Returns
whether the MTU value was within legal bounds
Override for default MTU defined on a per-type basis.
Implements ns3::NetDevice.
Definition at line 113 of file loopback-net-device.cc.
References m_mtu.
SetNode()
void ns3::LoopbackNetDevice::SetNode (Ptr< Node > node) virtual
Parameters
node the node associated to this netdevice.
This method is called from ns3::Node::AddDevice.
Implements ns3::NetDevice.
Definition at line 207 of file loopback-net-device.cc.
References m_node.
SetPromiscReceiveCallback()
void ns3::LoopbackNetDevice::SetPromiscReceiveCallback (PromiscReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received in promiscuous mode and must be forwarded to the higher layers.
Enables netdevice promiscuous mode and sets the callback that will handle promiscuous mode packets. Note, promiscuous mode packets means all packets, including those packets that can be sensed by the netdevice but which are intended to be received by other hosts.
Implements ns3::NetDevice.
Definition at line 233 of file loopback-net-device.cc.
References m_promiscCallback.
SetReceiveCallback()
void ns3::LoopbackNetDevice::SetReceiveCallback (NetDevice::ReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received and must be forwarded to the higher layers.
Set the callback to be used to notify higher layers when a packet has been received.
Implements ns3::NetDevice.
Definition at line 219 of file loopback-net-device.cc.
References m_rxCallback.
SupportsSendFrom()
bool ns3::LoopbackNetDevice::SupportsSendFrom (void) const virtual
Returns
true if this interface supports a bridging mode, false otherwise.
Implements ns3::NetDevice.
Definition at line 239 of file loopback-net-device.cc.
Member Data Documentation
m_address
Mac48Address ns3::LoopbackNetDevice::m_address private
NetDevice MAC address.
Definition at line 106 of file loopback-net-device.h.
Referenced by GetAddress(), Receive(), Send(), SendFrom(), and SetAddress().
m_ifIndex
uint32_t ns3::LoopbackNetDevice::m_ifIndex private
interface index
Definition at line 105 of file loopback-net-device.h.
Referenced by GetIfIndex(), and SetIfIndex().
m_mtu
uint16_t ns3::LoopbackNetDevice::m_mtu private
device MTU
Definition at line 104 of file loopback-net-device.h.
Referenced by GetMtu(), and SetMtu().
m_node
Ptr<Node> ns3::LoopbackNetDevice::m_node private
the node this NetDevice is associated with
Definition at line 103 of file loopback-net-device.h.
Referenced by DoDispose(), GetNode(), Send(), SendFrom(), and SetNode().
m_promiscCallback
NetDevice::PromiscReceiveCallback ns3::LoopbackNetDevice::m_promiscCallback private
The callback used to notify higher layers that a packet has been received in promiscuous mode.
Definition at line 101 of file loopback-net-device.h.
Referenced by Receive(), and SetPromiscReceiveCallback().
m_rxCallback
NetDevice::ReceiveCallback ns3::LoopbackNetDevice::m_rxCallback private
The callback used to notify higher layers that a packet has been received.
Definition at line 96 of file loopback-net-device.h.
Referenced by Receive(), and SetReceiveCallback().
The documentation for this class was generated from the following files:
src/internet/model/loopback-net-device.h
src/internet/model/loopback-net-device.cc