ns-3: ns3::TcpGeneralErrorModel Class Reference
ns3::TcpGeneralErrorModel Class Reference abstract
Internet » internet module tests | Test suites
A general (TCP-aware) error model.
#include "tcp-error-model.h"
Public Member Functions
TcpGeneralErrorModel ()
void SetDropCallback (Callback< void, const Ipv4Header &, const TcpHeader &, Ptr< const Packet > > cb)
Set the drop callback.
Public Member Functions inherited from ns3::ErrorModel
ErrorModel ()
virtual ~ErrorModel ()
void Disable (void)
Disable the error model.
void Enable (void)
Enable the error model.
bool IsCorrupt (Ptr< Packet > pkt)
Note: Depending on the error model, this function may or may not alter the contents of the packet upon returning true.
bool IsEnabled (void) const
void Reset (void)
Reset any state associated with the error model.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ErrorModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual bool ShouldDrop (const Ipv4Header &ipHeader, const TcpHeader &tcpHeader, uint32_t packetSize)=0
Check if the packet should be dropped.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
virtual bool DoCorrupt (Ptr< Packet > p)
Corrupt a packet according to the specified model.
Private Attributes
Callback< void, const Ipv4Header &, const TcpHeader &, Ptr< const Packet > > m_dropCallback
Drop callback.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A general (TCP-aware) error model.
The class is responsible to take away the IP and TCP header from the packet, and then to interrogate the method ShouldDrop, dropping the packet accordingly to the returned value.
Definition at line 38 of file tcp-error-model.h.
Constructor & Destructor Documentation
TcpGeneralErrorModel()
ns3::TcpGeneralErrorModel::TcpGeneralErrorModel ()
Definition at line 38 of file tcp-error-model.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoCorrupt()
bool ns3::TcpGeneralErrorModel::DoCorrupt (Ptr< Packet > p) private virtual
Corrupt a packet according to the specified model.
Parameters
p the packet to corrupt
Returns
true if the packet is corrupted
Implements ns3::ErrorModel.
Definition at line 44 of file tcp-error-model.cc.
References ns3::Packet::AddHeader(), ns3::Packet::GetSize(), ns3::ErrorModel::IsEnabled(), m_dropCallback, NS_LOG_FUNCTION, ns3::Packet::RemoveHeader(), and ShouldDrop().
GetTypeId()
TypeId ns3::TcpGeneralErrorModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 30 of file tcp-error-model.cc.
References ns3::TypeId::SetParent().
SetDropCallback()
void ns3::TcpGeneralErrorModel::SetDropCallback (Callback< void, const Ipv4Header &, const TcpHeader &, Ptr< const Packet > > cb) inline
Set the drop callback.
Parameters
cb The callback to be set.
Definition at line 52 of file tcp-error-model.h.
References m_dropCallback.
Referenced by TcpBytesInFlightTest::CreateReceiverErrorModel(), ns3::TcpCloseWithLossTestCase::CreateReceiverErrorModel(), TcpFastRetrTest::CreateReceiverErrorModel(), TcpRateLinuxWithSocketsTest::CreateReceiverErrorModel(), TcpSsThreshRtoTest::CreateReceiverErrorModel(), and TcpTimeRtoTest::CreateReceiverErrorModel().
ShouldDrop()
virtual bool ns3::TcpGeneralErrorModel::ShouldDrop (const Ipv4Header & ipHeader, const TcpHeader & tcpHeader, uint32_t packetSize) protected pure virtual
Check if the packet should be dropped.
Parameters
ipHeader The packet IPv4 header.
tcpHeader The packet TCP header.
packetSize The packet size.
Returns
True if the packet should be dropped.
Implemented in ns3::TcpFlagErrorModel, ns3::TcpSeqErrorModel, and TcpDropRatioErrorModel.
Referenced by DoCorrupt().
Member Data Documentation
m_dropCallback
Callback<void, const Ipv4Header&, const TcpHeader&, Ptr<const Packet> > ns3::TcpGeneralErrorModel::m_dropCallback private
Drop callback.
Definition at line 71 of file tcp-error-model.h.
Referenced by DoCorrupt(), and SetDropCallback().
The documentation for this class was generated from the following files:
src/internet/test/tcp-error-model.h
src/internet/test/tcp-error-model.cc