ns-3: ns3::RealtimeSimulatorImpl Class Reference
ns3::RealtimeSimulatorImpl Class Reference
Core » Simulator » Realtime Simulator
#include "realtime-simulator-impl.h"
Public Types
enum SynchronizationMode { SYNC_BEST_EFFORT, SYNC_HARD_LIMIT }
What to do when we can't maintain real time synchrony.
Public Member Functions
RealtimeSimulatorImpl ()
Constructor.
~RealtimeSimulatorImpl ()
Destructor.
virtual void Cancel (const EventId &ev)
Set the cancel bit on this event: the event's associated function will not be invoked when it expires.
virtual void Destroy ()
Execute the events scheduled with ScheduleDestroy().
virtual uint32_t GetContext (void) const
Get the current simulation context.
virtual Time GetDelayLeft (const EventId &id) const
Get the remaining time until this event will execute.
virtual uint64_t GetEventCount (void) const
Get the number of events executed.
Time GetHardLimit (void) const
Get the current fatal error threshold for SynchronizationMode SYNC_HARD_LIMIT.
virtual Time GetMaximumSimulationTime (void) const
Get the maximum representable simulation time.
RealtimeSimulatorImpl::SynchronizationMode GetSynchronizationMode (void) const
Get the SynchronizationMode.
virtual uint32_t GetSystemId (void) const
Get the system id of this simulator.
virtual bool IsExpired (const EventId &ev) const
Check if an event has already run or been cancelled.
virtual bool IsFinished (void) const
Check if the simulation should finish.
virtual Time Now (void) const
Return the current simulation virtual time.
Time RealtimeNow (void) const
Get the current real time from the synchronizer.
virtual void Remove (const EventId &ev)
Remove an event from the event list.
virtual void Run (void)
Run the simulation.
virtual EventId Schedule (const Time &delay, EventImpl *event)
Schedule a future event execution (in the same context).
virtual EventId ScheduleDestroy (EventImpl *event)
Schedule an event to run at the end of the simulation, after the Stop() time or condition has been reached.
virtual EventId ScheduleNow (EventImpl *event)
Schedule an event to run at the current virtual time.
void ScheduleRealtime (const Time &delay, EventImpl *event)
Schedule a future event execution (in the same context).
void ScheduleRealtimeNow (EventImpl *event)
Schedule an event to run at the current virtual time.
void ScheduleRealtimeNowWithContext (uint32_t context, EventImpl *event)
Schedule an event to run at the current virtual time.
void ScheduleRealtimeWithContext (uint32_t context, const Time &delay, EventImpl *event)
Schedule a future event execution (in a different context).
virtual void ScheduleWithContext (uint32_t context, const Time &delay, EventImpl *event)
Schedule a future event execution (in a different context).
void SetHardLimit (Time limit)
Set the fatal error threshold for SynchronizationMode SYNC_HARD_LIMIT.
virtual void SetScheduler (ObjectFactory schedulerFactory)
Set the Scheduler to be used to manage the event list.
void SetSynchronizationMode (RealtimeSimulatorImpl::SynchronizationMode mode)
Set the SynchronizationMode.
virtual void Stop (const Time &delay)
Schedule the time delay until the Simulator should stop.
virtual void Stop (void)
Tell the Simulator the calling event should be the last one executed.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the registered TypeId for this class.
Static Public Member Functions inherited from ns3::SimulatorImpl
static TypeId GetTypeId (void)
Get the registered TypeId for this class.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef std::list< EventId > DestroyEvents
Container type for events to be run at destroy time.
Private Member Functions
virtual void DoDispose (void)
Destructor implementation.
uint64_t NextTs (void) const
Get the timestep of the next event.
void ProcessOneEvent (void)
Process the next event.
bool Realtime (void) const
Check that the Synchronizer is locked to the real time clock.
bool Running (void) const
Is the simulator running?
Private Attributes
DestroyEvents m_destroyEvents
Container for events to be run at destroy time.
Time m_hardLimit
The maximum allowable drift from real-time in SYNC_HARD_LIMIT mode.
SystemThread::ThreadId m_main
Main SystemThread.
SystemMutex m_mutex
Mutex to control access to key state.
bool m_running
Is the simulator currently running.
bool m_stop
Has the stopping condition been reached?
SynchronizationMode m_synchronizationMode
SynchronizationMode policy.
Ptr< Synchronizer > m_synchronizer
The synchronizer in use to track real time.
Mutex-protected variables.
These variables are protected by m_mutex.
Ptr< Scheduler > m_events
The event list.
int m_unscheduledEvents
Unique id for the next event to be scheduled.
uint32_t m_uid
Unique id of the current event.
uint32_t m_currentUid
Timestep of the current event.
uint64_t m_currentTs
Execution context.
uint32_t m_currentContext
The event list.
uint64_t m_eventCount
The event count.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Realtime version of SimulatorImpl.
Definition at line 56 of file realtime-simulator-impl.h.
Member Typedef Documentation
DestroyEvents
typedef std::list<EventId> ns3::RealtimeSimulatorImpl::DestroyEvents private
Container type for events to be run at destroy time.
Definition at line 181 of file realtime-simulator-impl.h.
Member Enumeration Documentation
SynchronizationMode
enum ns3::RealtimeSimulatorImpl::SynchronizationMode
What to do when we can't maintain real time synchrony.
Enumerator
SYNC_BEST_EFFORT
Make a best effort to keep synced to real-time.
If we fall behind, keep going.
SYNC_HARD_LIMIT
Keep to real time within the hard limit tolerance configured with SetHardLimit, or die trying.
Falling behind by more than the hard limit tolerance triggers a fatal error.
See also
SetHardLimit
Definition at line 68 of file realtime-simulator-impl.h.
Constructor & Destructor Documentation
RealtimeSimulatorImpl()
ns3::RealtimeSimulatorImpl::RealtimeSimulatorImpl ()
Constructor.
Definition at line 77 of file realtime-simulator-impl.cc.
References m_currentContext, m_currentTs, m_currentUid, m_eventCount, m_main, m_running, m_stop, m_synchronizer, m_uid, m_unscheduledEvents, ns3::Simulator::NO_CONTEXT, NS_LOG_FUNCTION, and ns3::SystemThread::Self().
~RealtimeSimulatorImpl()
ns3::RealtimeSimulatorImpl::~RealtimeSimulatorImpl ()
Destructor.
Definition at line 102 of file realtime-simulator-impl.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Cancel()
void ns3::RealtimeSimulatorImpl::Cancel (const EventId & id) virtual
Set the cancel bit on this event: the event's associated function will not be invoked when it expires.
This method has the same visible effect as the ns3::Simulator::Remove method but its algorithmic complexity is much lower: it has O(1) complexity. This method has the exact same semantics as ns3::EventId::Cancel. Note that it is not possible to cancel events which were scheduled for the "destroy" time. Doing so will result in a program error (crash).
Parameters
[in] id the event to cancel
Implements ns3::SimulatorImpl.
Definition at line 752 of file realtime-simulator-impl.cc.
References IsExpired().
Destroy()
void ns3::RealtimeSimulatorImpl::Destroy () virtual
Execute the events scheduled with ScheduleDestroy().
This method is typically invoked at the end of a simulation to avoid false-positive reports by a leak checker. After this method has been invoked, it is actually possible to restart a new simulation with a set of calls to Simulator::Run, Simulator::Schedule and Simulator::ScheduleWithContext.
Implements ns3::SimulatorImpl.
Definition at line 122 of file realtime-simulator-impl.cc.
References m_destroyEvents, NS_LOG_FUNCTION, and NS_LOG_LOGIC().
DoDispose()
void ns3::RealtimeSimulatorImpl::DoDispose (void) private virtual
Destructor implementation.
Reimplemented from ns3::Object.
Definition at line 108 of file realtime-simulator-impl.cc.
References ns3::Object::DoDispose(), ns3::Scheduler::Event::impl, m_events, m_synchronizer, NS_LOG_FUNCTION, and ns3::SimpleRefCount< T, PARENT, DELETER >::Unref().
GetContext()
uint32_t ns3::RealtimeSimulatorImpl::GetContext (void) const virtual
Get the current simulation context.
The simulation context is the ns-3 notion of a Logical Process. Events in a single context should only modify state associated with that context. Events for objects in other contexts should be scheduled with ScheduleWithContext() to track the context switches. In other words, events in different contexts should be mutually thread safe, by not modify overlapping model state.
In circumstances where the context can't be determined, such as during object initialization, the enum value NO_CONTEXT should be used.
Returns
The current simulation context
Implements ns3::SimulatorImpl.
Definition at line 817 of file realtime-simulator-impl.cc.
References m_currentContext.
Referenced by Schedule(), ScheduleNow(), ScheduleRealtime(), and ScheduleRealtimeNow().
GetDelayLeft()
Time ns3::RealtimeSimulatorImpl::GetDelayLeft (const EventId & id) const virtual
Get the remaining time until this event will execute.
Parameters
[in] id The event id to analyse.
Returns
The delay left until the input event id expires. if the event is not running, this method returns zero.
Implements ns3::SimulatorImpl.
Definition at line 698 of file realtime-simulator-impl.cc.
References IsExpired(), m_currentTs, and ns3::TimeStep().
GetEventCount()
uint64_t ns3::RealtimeSimulatorImpl::GetEventCount (void) const virtual
Get the number of events executed.
Returns
The total number of events executed.
Implements ns3::SimulatorImpl.
Definition at line 823 of file realtime-simulator-impl.cc.
References m_eventCount.
GetHardLimit()
Time ns3::RealtimeSimulatorImpl::GetHardLimit (void) const
Get the current fatal error threshold for SynchronizationMode SYNC_HARD_LIMIT.
Returns
The hard limit threshold.
Definition at line 850 of file realtime-simulator-impl.cc.
References m_hardLimit, and NS_LOG_FUNCTION.
GetMaximumSimulationTime()
Time ns3::RealtimeSimulatorImpl::GetMaximumSimulationTime (void) const virtual
Get the maximum representable simulation time.
Returns
The maximum simulation time at which an event can be scheduled.
The returned value will always be bigger than or equal to Simulator::Now.
Implements ns3::SimulatorImpl.
Definition at line 804 of file realtime-simulator-impl.cc.
References ns3::TimeStep().
GetSynchronizationMode()
RealtimeSimulatorImpl::SynchronizationMode ns3::RealtimeSimulatorImpl::GetSynchronizationMode (void) const
Get the SynchronizationMode.
Returns
The current SynchronizationMode.
Definition at line 836 of file realtime-simulator-impl.cc.
References m_synchronizationMode, and NS_LOG_FUNCTION.
GetSystemId()
uint32_t ns3::RealtimeSimulatorImpl::GetSystemId (void) const virtual
Get the system id of this simulator.
The system id is the identifier for this simulator instance in a distributed simulation. For MPI this is the MPI rank.
Returns
The system id for this simulator.
Implements ns3::SimulatorImpl.
Definition at line 811 of file realtime-simulator-impl.cc.
GetTypeId()
TypeId ns3::RealtimeSimulatorImpl::GetTypeId (void) static
Get the registered TypeId for this class.
Returns
The TypeId.
Definition at line 55 of file realtime-simulator-impl.cc.
References m_hardLimit, ns3::MakeEnumAccessor(), ns3::MakeEnumChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::Seconds(), ns3::TypeId::SetParent(), SetSynchronizationMode(), SYNC_BEST_EFFORT, and SYNC_HARD_LIMIT.
IsExpired()
bool ns3::RealtimeSimulatorImpl::IsExpired (const EventId & id) const virtual
Check if an event has already run or been cancelled.
This method has O(1) complexity. Note that it is not possible to test for the expiration of events which were scheduled for the "destroy" time. Doing so will result in a program error (crash). An event is said to "expire" when it starts being scheduled which means that if the code executed by the event calls this function, it will get true.
Parameters
[in] id The event to test for expiration.
Returns
true if the event has expired, false otherwise.
Implements ns3::SimulatorImpl.
Definition at line 761 of file realtime-simulator-impl.cc.
References m_currentTs, m_currentUid, and m_destroyEvents.
Referenced by Cancel(), GetDelayLeft(), and Remove().
IsFinished()
bool ns3::RealtimeSimulatorImpl::IsFinished (void) const virtual
Check if the simulation should finish.
Reasons to finish are because there are no more events lefts to be scheduled, or if simulation time has already reached the "stop time" (see Simulator::Stop()).
Returns
true if no more events or stop time reached.
Implements ns3::SimulatorImpl.
Definition at line 399 of file realtime-simulator-impl.cc.
References m_events, m_mutex, and m_stop.
NextTs()
uint64_t ns3::RealtimeSimulatorImpl::NextTs (void) const private
Get the timestep of the next event.
Returns
The timestep of the next event.
Definition at line 414 of file realtime-simulator-impl.cc.
References ns3::Scheduler::Event::key, m_events, ns3::Scheduler::EventKey::m_ts, and NS_ASSERT_MSG().
Referenced by ProcessOneEvent().
Now()
Time ns3::RealtimeSimulatorImpl::Now (void) const virtual
Return the current simulation virtual time.
Returns
The current virtual time.
Implements ns3::SimulatorImpl.
Definition at line 600 of file realtime-simulator-impl.cc.
References m_currentTs, and ns3::TimeStep().
ProcessOneEvent()
void ns3::RealtimeSimulatorImpl::ProcessOneEvent (void) private
Process the next event.
Definition at line 169 of file realtime-simulator-impl.cc.
References ns3::Time::GetTimeStep(), ns3::Scheduler::Event::impl, ns3::Scheduler::Event::key, ns3::Scheduler::EventKey::m_context, m_currentContext, m_currentTs, m_currentUid, m_eventCount, m_events, m_hardLimit, m_mutex, m_synchronizationMode, m_synchronizer, ns3::Scheduler::EventKey::m_ts, ns3::Scheduler::EventKey::m_uid, m_unscheduledEvents, NextTs(), NS_ASSERT_MSG(), NS_FATAL_ERROR, NS_LOG_LOGIC(), and SYNC_HARD_LIMIT.
Referenced by Run().
Realtime()
bool ns3::RealtimeSimulatorImpl::Realtime (void) const private
Check that the Synchronizer is locked to the real time clock.
Returns
true if the Synchronizer is locked.
Definition at line 491 of file realtime-simulator-impl.cc.
References m_synchronizer.
RealtimeNow()
Time ns3::RealtimeSimulatorImpl::RealtimeNow (void) const
Get the current real time from the synchronizer.
Returns
The current real time.
Definition at line 670 of file realtime-simulator-impl.cc.
References m_synchronizer, and ns3::TimeStep().
Remove()
void ns3::RealtimeSimulatorImpl::Remove (const EventId & id) virtual
Remove an event from the event list.
This method has the same visible effect as the ns3::EventId::Cancel method but its algorithmic complexity is much higher: it has often O(log(n)) complexity, sometimes O(n), sometimes worse. Note that it is not possible to remove events which were scheduled for the "destroy" time. Doing so will result in a program error (crash).
Parameters
[in] id The event to remove from the list of scheduled events.
Implements ns3::SimulatorImpl.
Definition at line 713 of file realtime-simulator-impl.cc.
References ns3::Scheduler::Event::impl, IsExpired(), m_destroyEvents, m_events, m_mutex, and m_unscheduledEvents.
Run()
void ns3::RealtimeSimulatorImpl::Run (void) virtual
Run the simulation.
The simulation will run until one of:
No events are present anymore
The user called Simulator::Stop
The user called Simulator::Stop with a stop time and the expiration time of the next event to be processed is greater than or equal to the stop time.
Implements ns3::SimulatorImpl.
Definition at line 423 of file realtime-simulator-impl.cc.
References m_currentTs, m_events, m_main, m_mutex, m_running, m_stop, m_synchronizer, m_unscheduledEvents, NS_ASSERT_MSG(), NS_LOG_FUNCTION, ProcessOneEvent(), and ns3::SystemThread::Self().
Running()
bool ns3::RealtimeSimulatorImpl::Running (void) const private
Is the simulator running?
Returns
true if we are running.
Definition at line 485 of file realtime-simulator-impl.cc.
References m_running.
Schedule()
EventId ns3::RealtimeSimulatorImpl::Schedule (const Time & delay, EventImpl * event) virtual
Schedule a future event execution (in the same context).
Parameters
[in] delay Delay until the event expires.
[in] event The event to schedule.
Returns
A unique identifier for the newly-scheduled event.
Implements ns3::SimulatorImpl.
Definition at line 514 of file realtime-simulator-impl.cc.
References GetContext(), ns3::Time::GetTimeStep(), ns3::Scheduler::Event::impl, ns3::Time::IsPositive(), ns3::Scheduler::Event::key, ns3::Scheduler::EventKey::m_context, m_events, m_mutex, m_synchronizer, ns3::Scheduler::EventKey::m_ts, m_uid, ns3::Scheduler::EventKey::m_uid, m_unscheduledEvents, ns3::Simulator::Now(), NS_ASSERT_MSG(), and NS_LOG_FUNCTION.
ScheduleDestroy()
EventId ns3::RealtimeSimulatorImpl::ScheduleDestroy (EventImpl * event) virtual
Schedule an event to run at the end of the simulation, after the Stop() time or condition has been reached.
Parameters
[in] event The event to schedule.
Returns
A unique identifier for the newly-scheduled event.
Implements ns3::SimulatorImpl.
Definition at line 676 of file realtime-simulator-impl.cc.
References m_currentTs, m_destroyEvents, m_mutex, m_uid, and NS_LOG_FUNCTION.
ScheduleNow()
EventId ns3::RealtimeSimulatorImpl::ScheduleNow (EventImpl * event) virtual
Schedule an event to run at the current virtual time.
Parameters
[in] event The event to schedule.
Returns
A unique identifier for the newly-scheduled event.
Implements ns3::SimulatorImpl.
Definition at line 579 of file realtime-simulator-impl.cc.
References GetContext(), ns3::Scheduler::Event::impl, ns3::Scheduler::Event::key, ns3::Scheduler::EventKey::m_context, m_currentTs, m_events, m_mutex, m_synchronizer, ns3::Scheduler::EventKey::m_ts, m_uid, ns3::Scheduler::EventKey::m_uid, m_unscheduledEvents, and NS_LOG_FUNCTION.
ScheduleRealtime()
void ns3::RealtimeSimulatorImpl::ScheduleRealtime (const Time & delay, EventImpl * event)
Schedule a future event execution (in the same context).
Parameters
[in] delay Delay until the event expires.
[in] event The event to schedule.
Returns
A unique identifier for the newly-scheduled event.
Definition at line 630 of file realtime-simulator-impl.cc.
References GetContext(), NS_LOG_FUNCTION, and ScheduleRealtimeWithContext().
ScheduleRealtimeNow()
void ns3::RealtimeSimulatorImpl::ScheduleRealtimeNow (EventImpl * event)
Schedule an event to run at the current virtual time.
Parameters
[in] event The event to schedule.
Returns
A unique identifier for the newly-scheduled event.
Definition at line 663 of file realtime-simulator-impl.cc.
References GetContext(), NS_LOG_FUNCTION, and ScheduleRealtimeNowWithContext().
ScheduleRealtimeNowWithContext()
void ns3::RealtimeSimulatorImpl::ScheduleRealtimeNowWithContext (uint32_t context, EventImpl * event)
Schedule an event to run at the current virtual time.
Parameters
[in] context Event context.
[in] event The event to schedule.
Definition at line 637 of file realtime-simulator-impl.cc.
References ns3::Scheduler::Event::impl, ns3::Scheduler::Event::key, ns3::Scheduler::EventKey::m_context, m_currentTs, m_events, m_mutex, m_running, m_synchronizer, ns3::Scheduler::EventKey::m_ts, m_uid, ns3::Scheduler::EventKey::m_uid, m_unscheduledEvents, NS_ASSERT_MSG(), and NS_LOG_FUNCTION.
Referenced by ScheduleRealtimeNow().
ScheduleRealtimeWithContext()
void ns3::RealtimeSimulatorImpl::ScheduleRealtimeWithContext (uint32_t context, const Time & delay, EventImpl * event)
Schedule a future event execution (in a different context).
This method is thread-safe: it can be called from any thread.
Parameters
[in] delay Delay until the event expires.
[in] context Event context.
[in] event The event to schedule.
Returns
A unique identifier for the newly-scheduled event.
Definition at line 609 of file realtime-simulator-impl.cc.
References ns3::Time::GetTimeStep(), ns3::Scheduler::Event::impl, ns3::Scheduler::Event::key, m_currentTs, m_events, m_mutex, m_synchronizer, ns3::Scheduler::EventKey::m_ts, m_uid, ns3::Scheduler::EventKey::m_uid, m_unscheduledEvents, NS_ASSERT_MSG(), and NS_LOG_FUNCTION.
Referenced by ScheduleRealtime().
ScheduleWithContext()
void ns3::RealtimeSimulatorImpl::ScheduleWithContext (uint32_t context, const Time & delay, EventImpl * event) virtual
Schedule a future event execution (in a different context).
This method is thread-safe: it can be called from any thread.
Parameters
[in] delay Delay until the event expires.
[in] context Event context.
[in] event The event to schedule.
Returns
A unique identifier for the newly-scheduled event.
Implements ns3::SimulatorImpl.
Definition at line 543 of file realtime-simulator-impl.cc.
References ns3::SystemThread::Equals(), ns3::Time::GetTimeStep(), ns3::Scheduler::Event::impl, ns3::Scheduler::Event::key, ns3::Scheduler::EventKey::m_context, m_currentTs, m_events, m_main, m_mutex, m_running, m_synchronizer, ns3::Scheduler::EventKey::m_ts, m_uid, ns3::Scheduler::EventKey::m_uid, m_unscheduledEvents, NS_ASSERT_MSG(), and NS_LOG_FUNCTION.
SetHardLimit()
void ns3::RealtimeSimulatorImpl::SetHardLimit (Time limit)
Set the fatal error threshold for SynchronizationMode SYNC_HARD_LIMIT.
Parameters
[in] limit The maximum amount of real time we are allowed to fall behind before we trigger a fatal error.
Definition at line 843 of file realtime-simulator-impl.cc.
References m_hardLimit, and NS_LOG_FUNCTION.
SetScheduler()
void ns3::RealtimeSimulatorImpl::SetScheduler (ObjectFactory schedulerFactory) virtual
Set the Scheduler to be used to manage the event list.
Parameters
[in] schedulerFactory A new event scheduler factory.
The event scheduler can be set at any time: the events scheduled in the previous scheduler will be transferred to the new scheduler before we start to use it.
Implements ns3::SimulatorImpl.
Definition at line 147 of file realtime-simulator-impl.cc.
References ns3::ObjectFactory::Create(), m_events, m_mutex, and NS_LOG_FUNCTION.
SetSynchronizationMode()
void ns3::RealtimeSimulatorImpl::SetSynchronizationMode (RealtimeSimulatorImpl::SynchronizationMode mode)
Set the SynchronizationMode.
Parameters
[in] mode The new SynchronizationMode.
Definition at line 829 of file realtime-simulator-impl.cc.
References m_synchronizationMode, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
Stop() [1/2]
void ns3::RealtimeSimulatorImpl::Stop (const Time & delay) virtual
Schedule the time delay until the Simulator should stop.
Force the Simulator::Run method to return to the caller when the expiration time of the next event to be processed is greater than or equal to the stop time. The stop time is relative to the current simulation time.
Parameters
[in] delay The stop time, relative to the current time.
Implements ns3::SimulatorImpl.
Definition at line 504 of file realtime-simulator-impl.cc.
References NS_LOG_FUNCTION, ns3::Simulator::Schedule(), and ns3::Simulator::Stop().
Stop() [2/2]
void ns3::RealtimeSimulatorImpl::Stop (void) virtual
Tell the Simulator the calling event should be the last one executed.
If a running event invokes this method, it will be the last event executed by the Simulator::Run method before returning to the caller.
Implements ns3::SimulatorImpl.
Definition at line 497 of file realtime-simulator-impl.cc.
References m_stop, and NS_LOG_FUNCTION.
Member Data Documentation
m_currentContext
uint32_t ns3::RealtimeSimulatorImpl::m_currentContext private
The event list.
Number of events in the event list.
Definition at line 206 of file realtime-simulator-impl.h.
Referenced by RealtimeSimulatorImpl(), GetContext(), and ProcessOneEvent().
m_currentTs
uint64_t ns3::RealtimeSimulatorImpl::m_currentTs private
Execution context.
Definition at line 204 of file realtime-simulator-impl.h.
Referenced by RealtimeSimulatorImpl(), GetDelayLeft(), IsExpired(), Now(), ProcessOneEvent(), Run(), ScheduleDestroy(), ScheduleNow(), ScheduleRealtimeNowWithContext(), ScheduleRealtimeWithContext(), and ScheduleWithContext().
m_currentUid
uint32_t ns3::RealtimeSimulatorImpl::m_currentUid private
Timestep of the current event.
Definition at line 202 of file realtime-simulator-impl.h.
Referenced by RealtimeSimulatorImpl(), IsExpired(), and ProcessOneEvent().
m_destroyEvents
DestroyEvents ns3::RealtimeSimulatorImpl::m_destroyEvents private
Container for events to be run at destroy time.
Definition at line 183 of file realtime-simulator-impl.h.
Referenced by Destroy(), IsExpired(), Remove(), and ScheduleDestroy().
m_eventCount
uint64_t ns3::RealtimeSimulatorImpl::m_eventCount private
The event count.
Definition at line 208 of file realtime-simulator-impl.h.
Referenced by RealtimeSimulatorImpl(), GetEventCount(), and ProcessOneEvent().
m_events
Ptr<Scheduler> ns3::RealtimeSimulatorImpl::m_events private
The event list.
Number of events in the event list.
Definition at line 196 of file realtime-simulator-impl.h.
Referenced by DoDispose(), IsFinished(), NextTs(), ProcessOneEvent(), Remove(), Run(), Schedule(), ScheduleNow(), ScheduleRealtimeNowWithContext(), ScheduleRealtimeWithContext(), ScheduleWithContext(), and SetScheduler().
m_hardLimit
Time ns3::RealtimeSimulatorImpl::m_hardLimit private
The maximum allowable drift from real-time in SYNC_HARD_LIMIT mode.
Definition at line 221 of file realtime-simulator-impl.h.
Referenced by GetHardLimit(), GetTypeId(), ProcessOneEvent(), and SetHardLimit().
m_main
SystemThread::ThreadId ns3::RealtimeSimulatorImpl::m_main private
Main SystemThread.
Definition at line 224 of file realtime-simulator-impl.h.
Referenced by RealtimeSimulatorImpl(), Run(), and ScheduleWithContext().
m_mutex
SystemMutex ns3::RealtimeSimulatorImpl::m_mutex mutable private
Mutex to control access to key state.
Definition at line 212 of file realtime-simulator-impl.h.
Referenced by IsFinished(), ProcessOneEvent(), Remove(), Run(), Schedule(), ScheduleDestroy(), ScheduleNow(), ScheduleRealtimeNowWithContext(), ScheduleRealtimeWithContext(), ScheduleWithContext(), and SetScheduler().
m_running
bool ns3::RealtimeSimulatorImpl::m_running private
Is the simulator currently running.
Definition at line 187 of file realtime-simulator-impl.h.
Referenced by RealtimeSimulatorImpl(), Run(), Running(), ScheduleRealtimeNowWithContext(), and ScheduleWithContext().
m_stop
bool ns3::RealtimeSimulatorImpl::m_stop private
Has the stopping condition been reached?
Definition at line 185 of file realtime-simulator-impl.h.
Referenced by RealtimeSimulatorImpl(), IsFinished(), Run(), and Stop().
m_synchronizationMode
SynchronizationMode ns3::RealtimeSimulatorImpl::m_synchronizationMode private
SynchronizationMode policy.
Definition at line 218 of file realtime-simulator-impl.h.
Referenced by GetSynchronizationMode(), ProcessOneEvent(), and SetSynchronizationMode().
m_synchronizer
Ptr<Synchronizer> ns3::RealtimeSimulatorImpl::m_synchronizer private
The synchronizer in use to track real time.
Definition at line 215 of file realtime-simulator-impl.h.
Referenced by RealtimeSimulatorImpl(), DoDispose(), ProcessOneEvent(), Realtime(), RealtimeNow(), Run(), Schedule(), ScheduleNow(), ScheduleRealtimeNowWithContext(), ScheduleRealtimeWithContext(), and ScheduleWithContext().
m_uid
uint32_t ns3::RealtimeSimulatorImpl::m_uid private
Unique id of the current event.
Definition at line 200 of file realtime-simulator-impl.h.
Referenced by RealtimeSimulatorImpl(), Schedule(), ScheduleDestroy(), ScheduleNow(), ScheduleRealtimeNowWithContext(), ScheduleRealtimeWithContext(), and ScheduleWithContext().
m_unscheduledEvents
int ns3::RealtimeSimulatorImpl::m_unscheduledEvents private
Unique id for the next event to be scheduled.
Definition at line 198 of file realtime-simulator-impl.h.
Referenced by RealtimeSimulatorImpl(), ProcessOneEvent(), Remove(), Run(), Schedule(), ScheduleNow(), ScheduleRealtimeNowWithContext(), ScheduleRealtimeWithContext(), and ScheduleWithContext().
The documentation for this class was generated from the following files:
src/core/model/realtime-simulator-impl.h
src/core/model/realtime-simulator-impl.cc