ns-3: ns3::RadvdHelper Class Reference
ns3::RadvdHelper Class Reference
Internet Applications » Radvd
Radvd application helper.
#include "radvd-helper.h"
Public Member Functions
RadvdHelper ()
Constructor.
void AddAnnouncedPrefix (uint32_t interface, Ipv6Address prefix, uint32_t prefixLength)
Add a new prefix to be announced through an interface.
void ClearPrefixes ()
Clear the stored Prefixes.
void DisableDefaultRouterForInterface (uint32_t interface)
Disable the router as default router for the interface.
void EnableDefaultRouterForInterface (uint32_t interface)
Enable the router as default router for the interface.
Ptr< RadvdInterface > GetRadvdInterface (uint32_t interface)
Get the low-level RadvdInterface specification for an interface.
ApplicationContainer Install (Ptr< Node > node)
Install the application in a Node.
void SetAttribute (std::string name, const AttributeValue &value)
Set some attributes.
Private Types
typedef std::map< uint32_t, Ptr< RadvdInterface > > RadvdInterfaceMap
Container: interface index, RadvdInterface.
typedef std::map< uint32_t, Ptr< RadvdInterface > >::iterator RadvdInterfaceMapI
Container Iterator: interface index, RadvdInterface.
Private Attributes
ObjectFactory m_factory
An object factory.
RadvdInterfaceMap m_radvdInterfaces
RadvdInterface(s)
Detailed Description
Radvd application helper.
Definition at line 41 of file radvd-helper.h.
Member Typedef Documentation
RadvdInterfaceMap
typedef std::map<uint32_t, Ptr<RadvdInterface> > ns3::RadvdHelper::RadvdInterfaceMap private
Container: interface index, RadvdInterface.
Definition at line 105 of file radvd-helper.h.
RadvdInterfaceMapI
typedef std::map<uint32_t, Ptr<RadvdInterface> >::iterator ns3::RadvdHelper::RadvdInterfaceMapI private
Container Iterator: interface index, RadvdInterface.
Definition at line 107 of file radvd-helper.h.
Constructor & Destructor Documentation
RadvdHelper()
ns3::RadvdHelper::RadvdHelper ()
Constructor.
Definition at line 34 of file radvd-helper.cc.
References ns3::Radvd::GetTypeId(), m_factory, and ns3::ObjectFactory::SetTypeId().
Member Function Documentation
AddAnnouncedPrefix()
void ns3::RadvdHelper::AddAnnouncedPrefix (uint32_t interface, Ipv6Address prefix, uint32_t prefixLength)
Add a new prefix to be announced through an interface.
Parameters
interface outgoing interface
prefix announced IPv6 prefix
prefixLength announced IPv6 prefix length
Definition at line 39 of file radvd-helper.cc.
References m_radvdInterfaces, NS_LOG_FUNCTION, NS_LOG_LOGIC(), and NS_LOG_WARN.
ClearPrefixes()
void ns3::RadvdHelper::ClearPrefixes ()
Clear the stored Prefixes.
Definition at line 101 of file radvd-helper.cc.
References m_radvdInterfaces.
DisableDefaultRouterForInterface()
void ns3::RadvdHelper::DisableDefaultRouterForInterface (uint32_t interface)
Disable the router as default router for the interface.
The effect is to set the Router Lifetime to zero
Parameters
interface outgoing interface
Definition at line 83 of file radvd-helper.cc.
References m_radvdInterfaces.
EnableDefaultRouterForInterface()
void ns3::RadvdHelper::EnableDefaultRouterForInterface (uint32_t interface)
Enable the router as default router for the interface.
The effect is to set the Router Lifetime to the default value (30 minutes)
Parameters
interface outgoing interface
Definition at line 73 of file radvd-helper.cc.
References m_radvdInterfaces.
GetRadvdInterface()
Ptr< RadvdInterface > ns3::RadvdHelper::GetRadvdInterface (uint32_t interface)
Get the low-level RadvdInterface specification for an interface.
This method is provided to enable fine-grain parameter setup.
Parameters
interface outgoing interface
Returns
the RadvdInterface
Definition at line 92 of file radvd-helper.cc.
References m_radvdInterfaces.
Install()
ApplicationContainer ns3::RadvdHelper::Install (Ptr< Node > node)
Install the application in a Node.
Parameters
node the Node
Returns
application container
Definition at line 111 of file radvd-helper.cc.
References ns3::ApplicationContainer::Add(), ns3::Node::AddApplication(), ns3::ObjectFactory::Create(), m_factory, and m_radvdInterfaces.
SetAttribute()
void ns3::RadvdHelper::SetAttribute (std::string name, const AttributeValue & value)
Set some attributes.
Parameters
name attribute name
value attribute value
Definition at line 106 of file radvd-helper.cc.
References m_factory, and ns3::ObjectFactory::Set().
Member Data Documentation
m_factory
ObjectFactory ns3::RadvdHelper::m_factory private
An object factory.
Definition at line 102 of file radvd-helper.h.
Referenced by RadvdHelper(), Install(), and SetAttribute().
m_radvdInterfaces
RadvdInterfaceMap ns3::RadvdHelper::m_radvdInterfaces private
RadvdInterface(s)
Definition at line 109 of file radvd-helper.h.
Referenced by AddAnnouncedPrefix(), ClearPrefixes(), DisableDefaultRouterForInterface(), EnableDefaultRouterForInterface(), GetRadvdInterface(), and Install().
The documentation for this class was generated from the following files:
src/internet-apps/helper/radvd-helper.h
src/internet-apps/helper/radvd-helper.cc