ns-3: ns3::EnbMemberLteEnbPhySapProvider Class Reference
ns3::EnbMemberLteEnbPhySapProvider Class Reference
Public Member Functions
EnbMemberLteEnbPhySapProvider (LteEnbPhy *phy)
Constructor.
virtual uint8_t GetMacChTtiDelay ()
Get the delay from MAC to Channel expressed in TTIs.
virtual void SendLteControlMessage (Ptr< LteControlMessage > msg)
Send SendLteControlMessage (PDCCH map, CQI feedbacks) using the ideal control channel.
virtual void SendMacPdu (Ptr< Packet > p)
Send the MAC PDU to the channel.
virtual void SetBandwidth (uint16_t ulBandwidth, uint16_t dlBandwidth)
Set bandwidth function.
virtual void SetCellId (uint16_t cellId)
Set Cell ID function.
Public Member Functions inherited from ns3::LteEnbPhySapProvider
virtual ~LteEnbPhySapProvider ()
Private Attributes
LteEnbPhy * m_phy
the ENB Phy
Detailed Description
Todo:
SetBandwidth() and SetCellId() can be removed.
Definition at line 74 of file lte-enb-phy.cc.
Constructor & Destructor Documentation
EnbMemberLteEnbPhySapProvider()
ns3::EnbMemberLteEnbPhySapProvider::EnbMemberLteEnbPhySapProvider (LteEnbPhy * phy)
Constructor.
Parameters
phy the ENB Phy
Definition at line 107 of file lte-enb-phy.cc.
Member Function Documentation
GetMacChTtiDelay()
uint8_t ns3::EnbMemberLteEnbPhySapProvider::GetMacChTtiDelay () virtual
Get the delay from MAC to Channel expressed in TTIs.
Returns
MAC channel TTI delay
Implements ns3::LteEnbPhySapProvider.
Definition at line 137 of file lte-enb-phy.cc.
References ns3::LteEnbPhy::DoGetMacChTtiDelay(), and m_phy.
SendLteControlMessage()
void ns3::EnbMemberLteEnbPhySapProvider::SendLteControlMessage (Ptr< LteControlMessage > msg) virtual
Send SendLteControlMessage (PDCCH map, CQI feedbacks) using the ideal control channel.
Parameters
msg the Ideal Control Message to send
Implements ns3::LteEnbPhySapProvider.
Definition at line 131 of file lte-enb-phy.cc.
References ns3::LteEnbPhy::DoSendLteControlMessage(), and m_phy.
SendMacPdu()
void ns3::EnbMemberLteEnbPhySapProvider::SendMacPdu (Ptr< Packet > p) virtual
Send the MAC PDU to the channel.
Parameters
p the MAC PDU to send
Returns
true if
Implements ns3::LteEnbPhySapProvider.
Definition at line 113 of file lte-enb-phy.cc.
References ns3::LteEnbPhy::DoSendMacPdu(), and m_phy.
SetBandwidth()
void ns3::EnbMemberLteEnbPhySapProvider::SetBandwidth (uint16_t ulBandwidth, uint16_t dlBandwidth) virtual
Set bandwidth function.
Parameters
ulBandwidth the UL bandwidth
dlBandwidth the DL bandwidth
Definition at line 119 of file lte-enb-phy.cc.
References ns3::LteEnbPhy::DoSetBandwidth(), and m_phy.
SetCellId()
void ns3::EnbMemberLteEnbPhySapProvider::SetCellId (uint16_t cellId) virtual
Set Cell ID function.
Parameters
cellId the cell ID
Definition at line 125 of file lte-enb-phy.cc.
References ns3::LtePhy::DoSetCellId(), and m_phy.
Member Data Documentation
m_phy
LteEnbPhy* ns3::EnbMemberLteEnbPhySapProvider::m_phy private
the ENB Phy
Definition at line 104 of file lte-enb-phy.cc.
Referenced by GetMacChTtiDelay(), SendLteControlMessage(), SendMacPdu(), SetBandwidth(), and SetCellId().
The documentation for this class was generated from the following file:
src/lte/model/lte-enb-phy.cc