ns-3: SpectrumIdealPhyTestCase Class Reference
SpectrumIdealPhyTestCase Class Reference
Public Member Functions
SpectrumIdealPhyTestCase (double snrLinear, uint64_t phyRate, bool rateIsAchievable, std::string channelType)
virtual ~SpectrumIdealPhyTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Static Private Member Functions
static std::string Name (std::string channelType, double snrLinear, uint64_t phyRate)
Private Attributes
std::string m_channelType
uint64_t m_phyRate
bool m_rateIsAchievable
double m_snrLinear
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 67 of file spectrum-ideal-phy-test.cc.
Constructor & Destructor Documentation
SpectrumIdealPhyTestCase()
SpectrumIdealPhyTestCase::SpectrumIdealPhyTestCase (double snrLinear, uint64_t phyRate, bool rateIsAchievable, std::string channelType)
Definition at line 97 of file spectrum-ideal-phy-test.cc.
~SpectrumIdealPhyTestCase()
SpectrumIdealPhyTestCase::~SpectrumIdealPhyTestCase () virtual
Definition at line 109 of file spectrum-ideal-phy-test.cc.
Member Function Documentation
DoRun()
void SpectrumIdealPhyTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 115 of file spectrum-ideal-phy-test.cc.
References ns3::ListPositionAllocator::Add(), ns3::Node::AddApplication(), ns3::SpectrumChannelHelper::AddPropagationLoss(), third::channel, ns3::Config::Connect(), ns3::NodeContainer::Create(), ns3::SpectrumChannelHelper::Create(), ns3::WifiSpectrumValue5MhzFactory::CreateConstant(), ns3::WifiSpectrumValue5MhzFactory::CreateTxPowerSpectralDensity(), first::devices, g_bandwidth, g_rxBytes, ns3::NodeContainer::Get(), ns3::Object::GetObject(), ns3::AdhocAlohaNoackIdealPhyHelper::Install(), ns3::PacketSocketHelper::Install(), m_channelType, m_phyRate, m_rateIsAchievable, m_snrLinear, ns3::MakeCallback(), third::mobility, NS_LOG_FUNCTION, NS_LOG_INFO, NS_TEST_ASSERT_MSG_EQ, NS_TEST_ASSERT_MSG_EQ_TOL, PhyRxEndOkTrace(), ns3::Seconds(), ns3::ObjectBase::SetAttribute(), ns3::AdhocAlohaNoackIdealPhyHelper::SetChannel(), ns3::SpectrumChannelHelper::SetChannel(), ns3::MatrixPropagationLossModel::SetLoss(), ns3::AdhocAlohaNoackIdealPhyHelper::SetNoisePowerSpectralDensity(), ns3::AdhocAlohaNoackIdealPhyHelper::SetPhyAttribute(), ns3::PacketSocketAddress::SetPhysicalAddress(), ns3::SpectrumChannelHelper::SetPropagationDelay(), ns3::PacketSocketAddress::SetProtocol(), ns3::PacketSocketClient::SetRemote(), ns3::PacketSocketAddress::SetSingleDevice(), ns3::Application::SetStartTime(), ns3::Application::SetStopTime(), and ns3::AdhocAlohaNoackIdealPhyHelper::SetTxPowerSpectralDensity().
Name()
std::string SpectrumIdealPhyTestCase::Name (std::string channelType, double snrLinear, uint64_t phyRate) static private
Definition at line 87 of file spectrum-ideal-phy-test.cc.
Member Data Documentation
m_channelType
std::string SpectrumIdealPhyTestCase::m_channelType private
Definition at line 83 of file spectrum-ideal-phy-test.cc.
Referenced by DoRun().
m_phyRate
uint64_t SpectrumIdealPhyTestCase::m_phyRate private
Definition at line 81 of file spectrum-ideal-phy-test.cc.
Referenced by DoRun().
m_rateIsAchievable
bool SpectrumIdealPhyTestCase::m_rateIsAchievable private
Definition at line 82 of file spectrum-ideal-phy-test.cc.
Referenced by DoRun().
m_snrLinear
double SpectrumIdealPhyTestCase::m_snrLinear private
Definition at line 80 of file spectrum-ideal-phy-test.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/spectrum/test/spectrum-ideal-phy-test.cc