ns-3: ns3::WaveformGeneratorHelper Class Reference
ns3::WaveformGeneratorHelper Class Reference
Spectrum Models
#include "waveform-generator-helper.h"
Public Member Functions
WaveformGeneratorHelper ()
~WaveformGeneratorHelper ()
NetDeviceContainer Install (NodeContainer c) const
NetDeviceContainer Install (Ptr< Node > node) const
NetDeviceContainer Install (std::string nodeName) const
void SetAntenna (std::string type, std::string n0="", const AttributeValue &v0=EmptyAttributeValue(), std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue(), std::string n6="", const AttributeValue &v6=EmptyAttributeValue(), std::string n7="", const AttributeValue &v7=EmptyAttributeValue())
void SetChannel (Ptr< SpectrumChannel > channel)
set the SpectrumChannel that will be used by SpectrumPhy instances created by this helper
void SetChannel (std::string channelName)
set the SpectrumChannel that will be used by SpectrumPhy instances created by this helper
void SetDeviceAttribute (std::string n1, const AttributeValue &v1)
void SetPhyAttribute (std::string name, const AttributeValue &v)
void SetTxPowerSpectralDensity (Ptr< SpectrumValue > txPsd)
Protected Attributes
ObjectFactory m_antenna
Object factory for the Antenna objects.
Ptr< SpectrumChannel > m_channel
Channel.
ObjectFactory m_device
Object factory for the NetDevice objects.
ObjectFactory m_phy
Object factory for the phy objects.
Ptr< SpectrumValue > m_txPsd
Tx power spectral density.
Detailed Description
Create a Waveform generator, which can be used to inject specific noise in the channel.
Definition at line 45 of file waveform-generator-helper.h.
Constructor & Destructor Documentation
WaveformGeneratorHelper()
ns3::WaveformGeneratorHelper::WaveformGeneratorHelper ()
Definition at line 40 of file waveform-generator-helper.cc.
References m_antenna, m_device, m_phy, and ns3::ObjectFactory::SetTypeId().
~WaveformGeneratorHelper()
ns3::WaveformGeneratorHelper::~WaveformGeneratorHelper ()
Definition at line 47 of file waveform-generator-helper.cc.
Member Function Documentation
Install() [1/3]
NetDeviceContainer ns3::WaveformGeneratorHelper::Install (NodeContainer c) const
Parameters
c the set of nodes on which a device must be created
Returns
a device container which contains all the devices created by this method.
Definition at line 110 of file waveform-generator-helper.cc.
References ns3::Node::AddDevice(), ns3::NodeContainer::Begin(), ns3::ObjectFactory::Create(), first::devices, ns3::NodeContainer::End(), ns3::Object::GetObject(), m_antenna, m_channel, m_device, m_phy, m_txPsd, NS_ASSERT, NS_ASSERT_MSG(), and third::phy.
Referenced by WaveformGeneratorTestCase::DoRun(), and Install().
Install() [2/3]
NetDeviceContainer ns3::WaveformGeneratorHelper::Install (Ptr< Node > node) const
Parameters
node the node on which a device must be created
Returns
a device container which contains all the devices created by this method.
Definition at line 148 of file waveform-generator-helper.cc.
References Install().
Install() [3/3]
NetDeviceContainer ns3::WaveformGeneratorHelper::Install (std::string nodeName) const
Parameters
nodeName the name of node on which a device must be created
Returns
a device container which contains all the devices created by this method.
Definition at line 154 of file waveform-generator-helper.cc.
References Install().
SetAntenna()
void ns3::WaveformGeneratorHelper::SetAntenna (std::string type, std::string n0 = "", const AttributeValue & v0 = EmptyAttributeValue (), std::string n1 = "", const AttributeValue & v1 = EmptyAttributeValue (), std::string n2 = "", const AttributeValue & v2 = EmptyAttributeValue (), std::string n3 = "", const AttributeValue & v3 = EmptyAttributeValue (), std::string n4 = "", const AttributeValue & v4 = EmptyAttributeValue (), std::string n5 = "", const AttributeValue & v5 = EmptyAttributeValue (), std::string n6 = "", const AttributeValue & v6 = EmptyAttributeValue (), std::string n7 = "", const AttributeValue & v7 = EmptyAttributeValue ())
Parameters
type the type of the model to set
n0 the name of the attribute to set
v0 the value of the attribute to set
n1 the name of the attribute to set
v1 the value of the attribute to set
n2 the name of the attribute to set
v2 the value of the attribute to set
n3 the name of the attribute to set
v3 the value of the attribute to set
n4 the name of the attribute to set
v4 the value of the attribute to set
n5 the name of the attribute to set
v5 the value of the attribute to set
n6 the name of the attribute to set
v6 the value of the attribute to set
n7 the name of the attribute to set
v7 the value of the attribute to set
Configure the AntennaModel instance for each new device to be created
Definition at line 86 of file waveform-generator-helper.cc.
References m_antenna, ns3::ObjectFactory::Set(), and ns3::ObjectFactory::SetTypeId().
SetChannel() [1/2]
void ns3::WaveformGeneratorHelper::SetChannel (Ptr< SpectrumChannel > channel)
set the SpectrumChannel that will be used by SpectrumPhy instances created by this helper
Parameters
channel
Definition at line 52 of file waveform-generator-helper.cc.
References third::channel, and m_channel.
Referenced by WaveformGeneratorTestCase::DoRun().
SetChannel() [2/2]
void ns3::WaveformGeneratorHelper::SetChannel (std::string channelName)
set the SpectrumChannel that will be used by SpectrumPhy instances created by this helper
Parameters
channelName
Definition at line 58 of file waveform-generator-helper.cc.
References third::channel, and m_channel.
SetDeviceAttribute()
void ns3::WaveformGeneratorHelper::SetDeviceAttribute (std::string n1, const AttributeValue & v1)
Parameters
n1 the name of the attribute to set
v1 the value of the attribute to set
Set these attributes on each AlohaNoackNetDevice created
Definition at line 80 of file waveform-generator-helper.cc.
References m_device, and ns3::ObjectFactory::Set().
SetPhyAttribute()
void ns3::WaveformGeneratorHelper::SetPhyAttribute (std::string name, const AttributeValue & v)
Parameters
name the name of the attribute to set
v the value of the attribute
Set these attributes on each HdOfdmSpectrumPhy instance to be created
Definition at line 73 of file waveform-generator-helper.cc.
References m_phy, and ns3::ObjectFactory::Set().
Referenced by WaveformGeneratorTestCase::DoRun().
SetTxPowerSpectralDensity()
void ns3::WaveformGeneratorHelper::SetTxPowerSpectralDensity (Ptr< SpectrumValue > txPsd)
Parameters
txPsd the Power Spectral Density to be used for transmission by all created PHY instances
Definition at line 65 of file waveform-generator-helper.cc.
References m_txPsd, and NS_LOG_FUNCTION.
Referenced by WaveformGeneratorTestCase::DoRun().
Member Data Documentation
m_antenna
ObjectFactory ns3::WaveformGeneratorHelper::m_antenna protected
Object factory for the Antenna objects.
Definition at line 140 of file waveform-generator-helper.h.
Referenced by WaveformGeneratorHelper(), Install(), and SetAntenna().
m_channel
Ptr<SpectrumChannel> ns3::WaveformGeneratorHelper::m_channel protected
Channel.
Definition at line 141 of file waveform-generator-helper.h.
Referenced by Install(), and SetChannel().
m_device
ObjectFactory ns3::WaveformGeneratorHelper::m_device protected
Object factory for the NetDevice objects.
Definition at line 139 of file waveform-generator-helper.h.
Referenced by WaveformGeneratorHelper(), Install(), and SetDeviceAttribute().
m_phy
ObjectFactory ns3::WaveformGeneratorHelper::m_phy protected
Object factory for the phy objects.
Definition at line 138 of file waveform-generator-helper.h.
Referenced by WaveformGeneratorHelper(), Install(), and SetPhyAttribute().
m_txPsd
Ptr<SpectrumValue> ns3::WaveformGeneratorHelper::m_txPsd protected
Tx power spectral density.
Definition at line 142 of file waveform-generator-helper.h.
Referenced by Install(), and SetTxPowerSpectralDensity().
The documentation for this class was generated from the following files:
src/spectrum/helper/waveform-generator-helper.h
src/spectrum/helper/waveform-generator-helper.cc