ns-3: ns3::lorawan::SimpleGatewayLoraPhy Class Reference
ns3::lorawan::SimpleGatewayLoraPhy Class Reference
Class modeling a Lora SX1301 chip.
#include "simple-gateway-lora-phy.h"
Public Member Functions
SimpleGatewayLoraPhy ()
virtual ~SimpleGatewayLoraPhy ()
virtual void EndReceive (Ptr< Packet > packet, Ptr< LoraInterferenceHelper::Event > event)
Finish reception of a packet.
virtual void Send (Ptr< Packet > packet, LoraTxParameters txParams, double frequencyMHz, double txPowerDbm)
Instruct the PHY to send a packet according to some parameters.
virtual void StartReceive (Ptr< Packet > packet, double rxPowerDbm, uint8_t sf, Time duration, double frequencyMHz)
Start receiving a packet.
Public Member Functions inherited from ns3::lorawan::GatewayLoraPhy
GatewayLoraPhy ()
virtual ~GatewayLoraPhy ()
void AddReceptionPath (double frequencyMHz)
Add a reception path, locked on a specific frequency.
virtual bool IsOnFrequency (double frequencyMHz)
Whether this device is listening on the specified frequency or not.
bool IsTransmitting (void)
Whether this device is transmitting or not.
void ResetReceptionPaths (void)
Reset the list of reception paths.
virtual void TxFinished (Ptr< Packet > packet)
Public Member Functions inherited from ns3::lorawan::LoraPhy
LoraPhy ()
Constructor and destructor.
virtual ~LoraPhy ()
Ptr< LoraChannel > GetChannel (void) const
Get the channel instance associated to this PHY.
Ptr< NetDevice > GetDevice (void) const
Get the NetDevice associated to this PHY.
Ptr< MobilityModel > GetMobility ()
Get the mobility model associated to this PHY.
void SetChannel (Ptr< LoraChannel > channel)
Set the LoraChannel instance PHY transmits on.
void SetDevice (Ptr< NetDevice > device)
Set the NetDevice that owns this PHY.
void SetMobility (Ptr< MobilityModel > mobility)
Set the mobility model associated to this PHY.
void SetReceiveFailedCallback (RxFailedCallback callback)
Set the callback to call upon failed reception of a packet we were previously locked on.
void SetReceiveOkCallback (RxOkCallback callback)
Set the callback to call upon successful reception of a packet.
void SetTxFinishedCallback (TxFinishedCallback callback)
Set the callback to call after transmission of a packet.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::lorawan::GatewayLoraPhy
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::lorawan::LoraPhy
static Time GetOnAirTime (Ptr< Packet > packet, LoraTxParameters txParams)
Compute the time that a packet with certain characteristics will take to be transmitted.
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Public Types inherited from ns3::lorawan::LoraPhy
typedef Callback< void, Ptr< const Packet > > RxFailedCallback
Type definition for a callback for when a packet reception fails.
typedef Callback< void, Ptr< const Packet > > RxOkCallback
Type definition for a callback for when a packet is correctly received.
typedef Callback< void, Ptr< const Packet > > TxFinishedCallback
Type definition for a callback to call when a packet has finished sending.
Static Public Attributes inherited from ns3::lorawan::GatewayLoraPhy
static const double sensitivity [6]
A vector containing the sensitivities required to correctly decode different spreading factors.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::lorawan::GatewayLoraPhy
bool m_isTransmitting
Flag indicating whether a transmission is going on.
TracedCallback< Ptr< const Packet >, uint32_t > m_noMoreDemodulators
Trace source that is fired when a packet cannot be received because all available ReceivePath instances are busy.
TracedCallback< Ptr< const Packet >, uint32_t > m_noReceptionBecauseTransmitting
Trace source that is fired when a packet cannot be received because the Gateway is in transmission state.
TracedValue< int > m_occupiedReceptionPaths
The number of occupied reception paths.
std::list< Ptr< ReceptionPath > > m_receptionPaths
A list containing the various parallel receivers that are managed by this Gateway.
Protected Attributes inherited from ns3::lorawan::LoraPhy
Ptr< LoraChannel > m_channel
The channel this PHY transmits on.
Ptr< NetDevice > m_device
The net device this PHY is attached to.
TracedCallback< Ptr< const Packet >, uint32_t > m_interferedPacket
The trace source fired when a packet cannot be correctly received because of interference.
LoraInterferenceHelper m_interference
The LoraInterferenceHelper.
TracedCallback< Ptr< const Packet > > m_phyRxBeginTrace
The trace source fired when a packet begins the reception process from the medium.
TracedCallback< Ptr< const Packet > > m_phyRxEndTrace
The trace source fired when a packet reception ends.
RxFailedCallback m_rxFailedCallback
The callback to perform upon failed reception of a packet we were locked on.
RxOkCallback m_rxOkCallback
The callback to perform upon correct reception of a packet.
TracedCallback< Ptr< const Packet >, uint32_t > m_startSending
associated to this PHY.
TracedCallback< Ptr< const Packet >, uint32_t > m_successfullyReceivedPacket
The trace source fired when a packet was correctly received.
TxFinishedCallback m_txFinishedCallback
The callback to perform upon the end of a transmission.
TracedCallback< Ptr< const Packet >, uint32_t > m_underSensitivity
The trace source fired when a packet cannot be received because its power is below the sensitivity threshold.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Class modeling a Lora SX1301 chip.
Definition at line 41 of file simple-gateway-lora-phy.h.
Constructor & Destructor Documentation
SimpleGatewayLoraPhy()
ns3::lorawan::SimpleGatewayLoraPhy::SimpleGatewayLoraPhy ()
Definition at line 48 of file simple-gateway-lora-phy.cc.
References NS_LOG_FUNCTION_NOARGS.
~SimpleGatewayLoraPhy()
ns3::lorawan::SimpleGatewayLoraPhy::~SimpleGatewayLoraPhy () virtual
Definition at line 53 of file simple-gateway-lora-phy.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
EndReceive()
void ns3::lorawan::SimpleGatewayLoraPhy::EndReceive (Ptr< Packet > packet, Ptr< LoraInterferenceHelper::Event > event) virtual
Finish reception of a packet.
This method is scheduled by StartReceive, based on the packet duration. By passing a LoraInterferenceHelper Event to this method, the class will be able to identify the packet that is being received among all those that were registered as interference by StartReceive.
Parameters
packet The received packet.
event The event that is tied to this packet in the LoraInterferenceHelper.
Implements ns3::lorawan::GatewayLoraPhy.
Definition at line 232 of file simple-gateway-lora-phy.cc.
References ns3::Packet::AddPacketTag(), ns3::lorawan::LoraInterferenceHelper::IsDestroyedByInterference(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), ns3::lorawan::LoraPhy::m_device, ns3::lorawan::LoraPhy::m_interferedPacket, ns3::lorawan::LoraPhy::m_interference, ns3::lorawan::GatewayLoraPhy::m_occupiedReceptionPaths, ns3::lorawan::LoraPhy::m_phyRxEndTrace, ns3::lorawan::GatewayLoraPhy::m_receptionPaths, ns3::lorawan::LoraPhy::m_rxOkCallback, ns3::lorawan::LoraPhy::m_successfullyReceivedPacket, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::Packet::RemovePacketTag(), ns3::lorawan::LoraTag::SetDestroyedBy(), ns3::lorawan::LoraTag::SetFrequency(), and ns3::lorawan::LoraTag::SetReceivePower().
GetTypeId()
TypeId ns3::lorawan::SimpleGatewayLoraPhy::GetTypeId (void) static
Definition at line 38 of file simple-gateway-lora-phy.cc.
References ns3::TypeId::SetParent().
Send()
void ns3::lorawan::SimpleGatewayLoraPhy::Send (Ptr< Packet > packet, LoraTxParameters txParams, double frequencyMHz, double txPowerDbm) virtual
Instruct the PHY to send a packet according to some parameters.
Parameters
packet The packet to send.
txParams The desired transmission parameters.
frequencyMHz The frequency on which to transmit.
txPowerDbm The power in dBm with which to transmit the packet.
Implements ns3::lorawan::GatewayLoraPhy.
Definition at line 59 of file simple-gateway-lora-phy.cc.
References ns3::Simulator::Cancel(), aloha::duration, ns3::lorawan::LoraPhy::GetOnAirTime(), ns3::lorawan::LoraPhy::m_channel, ns3::lorawan::LoraPhy::m_device, ns3::lorawan::GatewayLoraPhy::m_isTransmitting, ns3::lorawan::GatewayLoraPhy::m_noReceptionBecauseTransmitting, ns3::lorawan::GatewayLoraPhy::m_receptionPaths, ns3::lorawan::LoraPhy::m_startSending, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), ns3::lorawan::LoraTxParameters::sf, and ns3::lorawan::GatewayLoraPhy::TxFinished().
StartReceive()
void ns3::lorawan::SimpleGatewayLoraPhy::StartReceive (Ptr< Packet > packet, double rxPowerDbm, uint8_t sf, Time duration, double frequencyMHz) virtual
Start receiving a packet.
This method is typically called by LoraChannel.
Parameters
packet The packet that is arriving at this PHY layer.
rxPowerDbm The power of the arriving packet (assumed to be constant for the whole reception).
sf The Spreading Factor of the arriving packet.
duration The on air time of this packet.
frequencyMHz The frequency this packet is being transmitted on.
Implements ns3::lorawan::GatewayLoraPhy.
Definition at line 120 of file simple-gateway-lora-phy.cc.
References ns3::lorawan::LoraInterferenceHelper::Add(), aloha::duration, ns3::lorawan::LoraPhy::EndReceive(), ns3::lorawan::LoraPhy::m_device, ns3::lorawan::LoraPhy::m_interference, ns3::lorawan::GatewayLoraPhy::m_isTransmitting, ns3::lorawan::GatewayLoraPhy::m_noMoreDemodulators, ns3::lorawan::GatewayLoraPhy::m_noReceptionBecauseTransmitting, ns3::lorawan::GatewayLoraPhy::m_occupiedReceptionPaths, ns3::lorawan::LoraPhy::m_phyRxBeginTrace, ns3::lorawan::LoraPhy::m_phyRxEndTrace, ns3::lorawan::GatewayLoraPhy::m_receptionPaths, ns3::lorawan::LoraPhy::m_underSensitivity, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::Simulator::Schedule(), and ns3::lorawan::GatewayLoraPhy::sensitivity.
The documentation for this class was generated from the following files:
src/lorawan/model/simple-gateway-lora-phy.h
src/lorawan/model/simple-gateway-lora-phy.cc