ns-3: ns3::dsr::DsrOptionPadnHeader Class Reference
ns3::dsr::DsrOptionPadnHeader Class Reference
Header of Dsr Option Padn.
#include "dsr-option-header.h"
Public Member Functions
DsrOptionPadnHeader (uint32_t pad=2)
Constructor.
virtual ~DsrOptionPadnHeader ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
virtual uint32_t GetSerializedSize () const
Get the serialized size of the packet.
virtual void Print (std::ostream &os) const
Print some information about the packet.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
Public Member Functions inherited from ns3::dsr::DsrOptionHeader
DsrOptionHeader ()
Constructor.
virtual ~DsrOptionHeader ()
Destructor.
virtual Alignment GetAlignment () const
Get the Alignment requirement of this option header.
uint8_t GetLength () const
Get the option length.
uint8_t GetType () const
Get the type of the option.
void SetLength (uint8_t length)
Set the option length.
void SetType (uint8_t type)
Set the type of the option.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::dsr::DsrOptionHeader
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Header of Dsr Option Padn.
Definition at line 199 of file dsr-option-header.h.
Constructor & Destructor Documentation
DsrOptionPadnHeader()
ns3::dsr::DsrOptionPadnHeader::DsrOptionPadnHeader (uint32_t pad = 2)
Constructor.
Parameters
pad Number of bytes to pad (>=2)
Definition at line 205 of file dsr-option-header.cc.
References NS_ASSERT_MSG(), ns3::dsr::DsrOptionHeader::SetLength(), and ns3::dsr::DsrOptionHeader::SetType().
~DsrOptionPadnHeader()
ns3::dsr::DsrOptionPadnHeader::~DsrOptionPadnHeader () virtual
Destructor.
Definition at line 212 of file dsr-option-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::dsr::DsrOptionPadnHeader::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start Buffer iterator
Returns
size of the packet
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 239 of file dsr-option-header.cc.
References GetSerializedSize(), ns3::Buffer::Iterator::ReadU8(), ns3::dsr::DsrOptionHeader::SetLength(), ns3::dsr::DsrOptionHeader::SetType(), and visualizer.core::start().
GetInstanceTypeId()
TypeId ns3::dsr::DsrOptionPadnHeader::GetInstanceTypeId () const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 200 of file dsr-option-header.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::dsr::DsrOptionPadnHeader::GetSerializedSize () const virtual
Get the serialized size of the packet.
Returns
size
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 221 of file dsr-option-header.cc.
References ns3::dsr::DsrOptionHeader::GetLength().
Referenced by Deserialize(), and ns3::dsr::DsrOptionPadn::Process().
GetTypeId()
TypeId ns3::dsr::DsrOptionPadnHeader::GetTypeId () static
Get the type identificator.
Returns
type identificator
Definition at line 190 of file dsr-option-header.cc.
References ns3::TypeId::AddConstructor().
Referenced by GetInstanceTypeId().
Print()
void ns3::dsr::DsrOptionPadnHeader::Print (std::ostream & os) const virtual
Print some information about the packet.
Parameters
os output stream
Returns
info about this packet
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 216 of file dsr-option-header.cc.
References ns3::dsr::DsrOptionHeader::GetLength(), and ns3::dsr::DsrOptionHeader::GetType().
Serialize()
void ns3::dsr::DsrOptionPadnHeader::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start Buffer iterator
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 226 of file dsr-option-header.cc.
References ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrOptionHeader::GetType(), visualizer.core::start(), and ns3::Buffer::Iterator::WriteU8().
Referenced by ns3::dsr::DsrOptionField::Serialize().
The documentation for this class was generated from the following files:
src/dsr/model/dsr-option-header.h
src/dsr/model/dsr-option-header.cc