ns-3: ns3::EndDeviceLoraPhy Class Reference
ns3::EndDeviceLoraPhy Class Reference
Class representing a LoRa transceiver.
#include "end-device-lora-phy.h"
Public Types
enum State { SLEEP, STANDBY, TX, RX }
An enumeration of the possible states of an EndDeviceLoraPhy.
Public Types inherited from ns3::LoraPhy
typedef Callback< void, Ptr< const Packet > > RxOkCallback
Type definition for a callback for when a packet is correctly received.
typedef Callback< void, Ptr< const Packet > > TxFinishedCallback
Type definition for a callback to call when a packet has finished sending.
Public Member Functions
EndDeviceLoraPhy ()
virtual ~EndDeviceLoraPhy ()
virtual void EndReceive (Ptr< Packet > packet, Ptr< LoraInterferenceHelper::Event > event)
Finish reception of a packet.
uint8_t GetSpreadingFactor (void)
Get the Spreading Factor this EndDevice is listening for.
EndDeviceLoraPhy::State GetState (void)
Return the state this End Device is currently in.
virtual bool IsOnFrequency (double frequencyMHz)
Whether this device is listening on the specified frequency or not.
virtual bool IsTransmitting (void)
Whether this device is transmitting or not.
virtual void Send (Ptr< Packet > packet, LoraTxParameters txParams, double frequencyMHz, double txPowerDbm)
Instruct the PHY to send a packet according to some parameters.
void SetFrequency (double frequencyMHz)
Set the frequency this EndDevice will listen on.
void SetSpreadingFactor (uint8_t sf)
Set the Spreading Factor this EndDevice will listen for.
virtual void StartReceive (Ptr< Packet > packet, double rxPowerDbm, uint8_t sf, Time duration, double frequencyMHz)
Start receiving a packet.
void SwitchToSleep (void)
Switch to the SLEEP state.
void SwitchToStandby (void)
Switch to the STANDBY state.
Public Member Functions inherited from ns3::LoraPhy
LoraPhy ()
Constructor and destructor.
virtual ~LoraPhy ()
Ptr< LoraChannel > GetChannel (void) const
Get the channel instance associated to this PHY.
Ptr< NetDevice > GetDevice (void) const
Get the NetDevice associated to this PHY.
Ptr< MobilityModel > GetMobility ()
Get the mobility model associated to this PHY.
void SetChannel (Ptr< LoraChannel > channel)
Set the LoraChannel instance PHY transmits on.
void SetDevice (Ptr< NetDevice > device)
Set the NetDevice that owns this PHY.
void SetMobility (Ptr< MobilityModel > mobility)
Set the mobility model associated to this PHY.
void SetReceiveOkCallback (RxOkCallback callback)
Set the callback to call upon successful reception of a packet.
void SetTxFinishedCallback (TxFinishedCallback callback)
Set the callback to call after transmission of a packet.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::LoraPhy
static Time GetOnAirTime (Ptr< Packet > packet, LoraTxParameters txParams)
Compute the time that a packet with certain characteristics will take to be transmitted.
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void SwitchToRx (void)
Switch to the RX state.
void SwitchToTx (void)
Switch to the TX state.
Private Attributes
double m_frequency
The frequency this device is listening on.
uint8_t m_sf
The Spreading Factor this device is listening for.
TracedValue< State > m_state
The state this PHY is currently in.
TracedCallback< Ptr< const Packet >, uint32_t > m_wrongFrequency
Trace source for when a packet is lost because it was transmitted on a frequency different from the one this EndDeviceLoraPhy was configured to listen on.
TracedCallback< Ptr< const Packet >, uint32_t > m_wrongSf
Trace source for when a packet is lost because it was using a SF different from the one this EndDeviceLoraPhy was configured to listen for.
Static Private Attributes
static const double sensitivity [6]
The sensitivity vector of this device to different SFs.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::LoraPhy
Ptr< LoraChannel > m_channel
The channel this PHY transmits on.
Ptr< NetDevice > m_device
The net device this PHY is attached to.
TracedCallback< Ptr< const Packet >, uint32_t > m_interferedPacket
The trace source fired when a packet cannot be correctly received because of interference.
LoraInterferenceHelper m_interference
The LoraInterferenceHelper associated to this PHY.
TracedCallback< Ptr< const Packet > > m_phyRxBeginTrace
The trace source fired when a packet begins the reception process from the medium.
TracedCallback< Ptr< const Packet > > m_phyRxEndTrace
The trace source fired when a packet reception ends.
RxOkCallback m_rxOkCallback
The callback to perform upon correct reception of a packet.
TracedCallback< Ptr< const Packet >, uint32_t > m_startSending
The trace source fired when a packet is sent.
TracedCallback< Ptr< const Packet >, uint32_t > m_successfullyReceivedPacket
The trace source fired when a packet was correctly received.
TxFinishedCallback m_txFinishedCallback
The callback to perform upon the end of a transmission.
TracedCallback< Ptr< const Packet >, uint32_t > m_underSensitivity
The trace source fired when a packet cannot be received because its power is below the sensitivity threshold.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Class representing a LoRa transceiver.
This class inherits some functionality by LoraPhy, like the GetOnAirTime function, and extends it to represent the behavior of a LoRa chip, like the SX1272.
Additional behaviors featured in this class include a State member variable that expresses the current state of the device (SLEEP, TX, RX or STANDBY), and a frequency and Spreading Factor this device is listening to when in STANDBY mode. After transmission and reception, the device returns automatically to STANDBY mode. The decision of when to go into SLEEP mode is delegateed to an upper layer, which can modify the state of the device through the public SwitchToSleep and SwitchToStandby methods. In SLEEP mode, the device cannot lock on a packet and start reception.
Definition at line 52 of file end-device-lora-phy.h.
Member Enumeration Documentation
State
enum ns3::EndDeviceLoraPhy::State
An enumeration of the possible states of an EndDeviceLoraPhy.
It makes sense to define a state for End Devices since there's only one demodulator which can either send, receive, stay idle or go in a deep sleep state.
Enumerator
SLEEP
The PHY layer is sleeping.
During sleep, the device is not listening for incoming messages.
STANDBY
The PHY layer is in STANDBY.
When the PHY is in this state, it's listening to the channel, and it's also ready to transmit data passed to it by the MAC layer.
TX
The PHY layer is sending a packet.
During transmission, the device cannot receive any packet or send any additional packet.
RX
The PHY layer is receiving a packet.
While the device is locked on an incoming packet, transmission is not possible.
Definition at line 61 of file end-device-lora-phy.h.
Constructor & Destructor Documentation
EndDeviceLoraPhy()
ns3::EndDeviceLoraPhy::EndDeviceLoraPhy ()
Definition at line 62 of file end-device-lora-phy.cc.
~EndDeviceLoraPhy()
ns3::EndDeviceLoraPhy::~EndDeviceLoraPhy () virtual
Definition at line 69 of file end-device-lora-phy.cc.
Member Function Documentation
EndReceive()
void ns3::EndDeviceLoraPhy::EndReceive (Ptr< Packet > packet, Ptr< LoraInterferenceHelper::Event > event) virtual
Finish reception of a packet.
This method is scheduled by StartReceive, based on the packet duration. By passing a LoraInterferenceHelper Event to this method, the class will be able to identify the packet that is being received among all those that were registered as interference by StartReceive.
Parameters
packet The received packet.
event The event that is tied to this packet in the LoraInterferenceHelper.
Implements ns3::LoraPhy.
Definition at line 290 of file end-device-lora-phy.cc.
References ns3::LoraInterferenceHelper::IsDestroyedByInterference(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), ns3::LoraPhy::m_device, ns3::LoraPhy::m_interferedPacket, ns3::LoraPhy::m_interference, ns3::LoraPhy::m_phyRxEndTrace, ns3::LoraPhy::m_rxOkCallback, ns3::LoraPhy::m_successfullyReceivedPacket, NS_LOG_FUNCTION, NS_LOG_INFO, packet, and SwitchToStandby().
GetSpreadingFactor()
uint8_t ns3::EndDeviceLoraPhy::GetSpreadingFactor (void)
Get the Spreading Factor this EndDevice is listening for.
Returns
The Spreading Factor we are listening for.
Definition at line 86 of file end-device-lora-phy.cc.
References m_sf.
GetState()
EndDeviceLoraPhy::State ns3::EndDeviceLoraPhy::GetState (void)
Return the state this End Device is currently in.
Returns
The state this EndDeviceLoraPhy is currently in.
Definition at line 398 of file end-device-lora-phy.cc.
References m_state, and NS_LOG_FUNCTION_NOARGS.
Referenced by PhyConnectivityTest::DoRun(), and ns3::EndDeviceLoraMac::OpenSecondReceiveWindow().
GetTypeId()
TypeId ns3::EndDeviceLoraPhy::GetTypeId (void) static
Definition at line 34 of file end-device-lora-phy.cc.
References m_state, m_wrongFrequency, m_wrongSf, ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
IsOnFrequency()
bool ns3::EndDeviceLoraPhy::IsOnFrequency (double frequency) virtual
Whether this device is listening on the specified frequency or not.
Parameters
frequency The frequency to query.
Returns
true if the device is listening on that frequency, false otherwise.
Implements ns3::LoraPhy.
Definition at line 348 of file end-device-lora-phy.cc.
References m_frequency.
Referenced by StartReceive().
IsTransmitting()
bool ns3::EndDeviceLoraPhy::IsTransmitting (void) virtual
Whether this device is transmitting or not.
Returns
true if the device is currently transmitting a packet, false otherwise.
Implements ns3::LoraPhy.
Definition at line 342 of file end-device-lora-phy.cc.
References m_state, and TX.
Send()
void ns3::EndDeviceLoraPhy::Send (Ptr< Packet > packet, LoraTxParameters txParams, double frequencyMHz, double txPowerDbm) virtual
Instruct the PHY to send a packet according to some parameters.
Parameters
packet The packet to send.
txParams The desired transmission parameters.
frequencyMHz The frequency on which to transmit.
txPowerDbm The power in dBm with which to transmit the packet.
Implements ns3::LoraPhy.
Definition at line 92 of file end-device-lora-phy.cc.
References ns3::Packet::AddPacketTag(), ns3::LoraPhy::GetOnAirTime(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), ns3::LoraPhy::m_channel, ns3::LoraPhy::m_device, ns3::LoraPhy::m_startSending, m_state, ns3::LoraPhy::m_txFinishedCallback, ns3::NanoSeconds(), NS_LOG_FUNCTION, NS_LOG_INFO, packet, ns3::Packet::RemovePacketTag(), ns3::Simulator::Schedule(), ns3::LoraChannel::Send(), ns3::LoraTag::SetSpreadingFactor(), SLEEP, STANDBY, SwitchToStandby(), SwitchToTx(), and txParams.
SetFrequency()
void ns3::EndDeviceLoraPhy::SetFrequency (double frequencyMHz)
Set the frequency this EndDevice will listen on.
Should a packet be transmitted on a frequency different than that the EndDeviceLoraPhy is listening on, the packet will be discarded.
Parameters
The frequency [MHz] to listen to.
Definition at line 354 of file end-device-lora-phy.cc.
References m_frequency.
Referenced by PhyConnectivityTest::Reset(), and Reset().
SetSpreadingFactor()
void ns3::EndDeviceLoraPhy::SetSpreadingFactor (uint8_t sf)
Set the Spreading Factor this EndDevice will listen for.
The EndDeviceLoraPhy object will not be able to lock on transmissions that use a different SF than the one it's listening for.
Parameters
sf The spreading factor to listen for.
Definition at line 80 of file end-device-lora-phy.cc.
References m_sf.
Referenced by PhyConnectivityTest::DoRun(), and PhyConnectivityTest::Reset().
StartReceive()
void ns3::EndDeviceLoraPhy::StartReceive (Ptr< Packet > packet, double rxPowerDbm, uint8_t sf, Time duration, double frequencyMHz) virtual
Start receiving a packet.
This method is typically called by LoraChannel.
Parameters
packet The packet that is arriving at this PHY layer.
rxPowerDbm The power of the arriving packet (assumed to be constant for the whole reception).
sf The Spreading Factor of the arriving packet.
duration The on air time of this packet.
frequencyMHz The frequency this packet is being transmitted on.
Implements ns3::LoraPhy.
Definition at line 150 of file end-device-lora-phy.cc.
References ns3::LoraInterferenceHelper::Add(), ns3::LoraPhy::EndReceive(), ns3::Time::GetSeconds(), IsOnFrequency(), ns3::LoraPhy::m_device, m_frequency, ns3::LoraPhy::m_interference, ns3::LoraPhy::m_phyRxBeginTrace, m_sf, m_state, ns3::LoraPhy::m_underSensitivity, m_wrongFrequency, m_wrongSf, NS_LOG_FUNCTION, NS_LOG_INFO, packet, RX, ns3::Simulator::Schedule(), sensitivity, SLEEP, STANDBY, SwitchToRx(), and TX.
SwitchToRx()
void ns3::EndDeviceLoraPhy::SwitchToRx (void) private
Switch to the RX state.
Definition at line 368 of file end-device-lora-phy.cc.
References m_state, NS_ASSERT, NS_LOG_FUNCTION_NOARGS, RX, and STANDBY.
Referenced by StartReceive().
SwitchToSleep()
void ns3::EndDeviceLoraPhy::SwitchToSleep (void)
Switch to the SLEEP state.
Definition at line 388 of file end-device-lora-phy.cc.
References m_state, NS_ASSERT, NS_LOG_FUNCTION_NOARGS, SLEEP, and STANDBY.
Referenced by PhyConnectivityTest::DoRun().
SwitchToStandby()
void ns3::EndDeviceLoraPhy::SwitchToStandby (void)
Switch to the STANDBY state.
Definition at line 360 of file end-device-lora-phy.cc.
References m_state, NS_LOG_FUNCTION_NOARGS, and STANDBY.
Referenced by EndReceive(), PhyConnectivityTest::Reset(), Reset(), and Send().
SwitchToTx()
void ns3::EndDeviceLoraPhy::SwitchToTx (void) private
Switch to the TX state.
Definition at line 378 of file end-device-lora-phy.cc.
References m_state, NS_ASSERT, NS_LOG_FUNCTION_NOARGS, RX, and TX.
Referenced by Send().
Member Data Documentation
m_frequency
double ns3::EndDeviceLoraPhy::m_frequency private
The frequency this device is listening on.
Definition at line 187 of file end-device-lora-phy.h.
Referenced by IsOnFrequency(), SetFrequency(), and StartReceive().
m_sf
uint8_t ns3::EndDeviceLoraPhy::m_sf private
The Spreading Factor this device is listening for.
Definition at line 189 of file end-device-lora-phy.h.
Referenced by GetSpreadingFactor(), SetSpreadingFactor(), and StartReceive().
m_state
TracedValue<State> ns3::EndDeviceLoraPhy::m_state private
The state this PHY is currently in.
Definition at line 183 of file end-device-lora-phy.h.
Referenced by GetState(), GetTypeId(), IsTransmitting(), Send(), StartReceive(), SwitchToRx(), SwitchToSleep(), SwitchToStandby(), and SwitchToTx().
m_wrongFrequency
TracedCallback<Ptr<const Packet>, uint32_t> ns3::EndDeviceLoraPhy::m_wrongFrequency private
Trace source for when a packet is lost because it was transmitted on a frequency different from the one this EndDeviceLoraPhy was configured to listen on.
Definition at line 181 of file end-device-lora-phy.h.
Referenced by GetTypeId(), and StartReceive().
m_wrongSf
TracedCallback<Ptr<const Packet>, uint32_t> ns3::EndDeviceLoraPhy::m_wrongSf private
Trace source for when a packet is lost because it was using a SF different from the one this EndDeviceLoraPhy was configured to listen for.
Definition at line 174 of file end-device-lora-phy.h.
Referenced by GetTypeId(), and StartReceive().
sensitivity
const double ns3::EndDeviceLoraPhy::sensitivity static private
Initial value:
=
{-124, -127, -130, -133, -135, -137}
The sensitivity vector of this device to different SFs.
Definition at line 185 of file end-device-lora-phy.h.
Referenced by StartReceive().
The documentation for this class was generated from the following files:
src/lorawan/model/end-device-lora-phy.h
src/lorawan/model/end-device-lora-phy.cc