ns-3: Ipv6FragmentationTest Class Reference
Ipv6FragmentationTest Class Reference
Internet » internet module tests | Test suites
IPv6 Fragmentation Test.
Public Member Functions
Ipv6FragmentationTest ()
~Ipv6FragmentationTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
void HandleReadClient (Ptr< Socket > socket)
Handle incoming packets.
void HandleReadIcmpClient (Ipv6Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo)
Handle incoming ICMP packets.
void HandleReadServer (Ptr< Socket > socket)
Handle incoming packets.
Ptr< Packet > SendClient (void)
Send a packet.
void SetFill (uint8_t *fill, uint32_t fillSize, uint32_t dataSize)
Set the packet fill.
void StartClient (Ptr< Node > ClientNode)
Start the client.
void StartServer (Ptr< Node > ServerNode)
Start the server.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Attributes
uint8_t * m_data
Data.
uint32_t m_dataSize
Data size.
uint8_t m_icmpCode
ICMP code.
uint8_t m_icmpType
ICMP type.
Ptr< Packet > m_receivedPacketClient
Packet received by client.
Ptr< Packet > m_receivedPacketServer
Packet received by server.
Ptr< Packet > m_sentPacketClient
Packet sent by client.
uint32_t m_size
packet size.
Ptr< Socket > m_socketClient
Client socket.
Ptr< Socket > m_socketServer
Server socket.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
IPv6 Fragmentation Test.
Definition at line 110 of file ipv6-fragmentation-test.cc.
Constructor & Destructor Documentation
Ipv6FragmentationTest()
Ipv6FragmentationTest::Ipv6FragmentationTest ()
Definition at line 182 of file ipv6-fragmentation-test.cc.
References m_data, m_dataSize, m_icmpCode, m_icmpType, m_size, and m_socketServer.
~Ipv6FragmentationTest()
Ipv6FragmentationTest::~Ipv6FragmentationTest ()
Definition at line 193 of file ipv6-fragmentation-test.cc.
References m_data, and m_dataSize.
Member Function Documentation
DoRun()
void Ipv6FragmentationTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 324 of file ipv6-fragmentation-test.cc.
References ns3::Ipv6::AddAddress(), ns3::Node::AddDevice(), ns3::Ipv6::AddInterface(), third::channel, ns3::Packet::CopyData(), ns3::ErrorModel::Disable(), ns3::ErrorModel::Enable(), ns3::Packet::GetByteTagIterator(), ns3::TypeId::GetConstructor(), ns3::ByteTagIterator::Item::GetEnd(), ns3::Node::GetId(), ns3::TypeId::GetName(), ns3::Socket::GetNode(), ns3::Object::GetObject(), ns3::Packet::GetSize(), ns3::ByteTagIterator::Item::GetStart(), ns3::ByteTagIterator::Item::GetTag(), IPv6TestTag::GetToken(), ns3::ByteTagIterator::Item::GetTypeId(), ns3::ByteTagIterator::HasNext(), ns3::InternetStackHelper::Install(), m_data, m_icmpCode, m_icmpType, m_receivedPacketServer, m_socketClient, ns3::ByteTagIterator::Next(), NS_TEST_EXPECT_MSG_EQ, NS_TEST_EXPECT_MSG_NE, packetSize, ns3::Packet::PeekPacketTag(), ns3::ErrorModel::Reset(), ns3::Seconds(), SendClient(), ns3::SimpleNetDevice::SetAddress(), ns3::SimpleNetDevice::SetChannel(), SetFill(), ns3::InternetStackHelper::SetIpv4StackInstall(), ns3::SimpleNetDevice::SetMtu(), ns3::SimpleNetDevice::SetReceiveErrorModel(), ns3::Ipv6::SetUp(), StartClient(), and StartServer().
HandleReadClient()
void Ipv6FragmentationTest::HandleReadClient (Ptr< Socket > socket)
Handle incoming packets.
Parameters
socket The receiving socket.
Definition at line 252 of file ipv6-fragmentation-test.cc.
References ns3::Packet::Copy(), m_receivedPacketClient, and ns3::Socket::RecvFrom().
Referenced by StartClient().
HandleReadIcmpClient()
void Ipv6FragmentationTest::HandleReadIcmpClient (Ipv6Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo)
Handle incoming ICMP packets.
Parameters
icmpSource The ICMP sender.
icmpTtl The ICMP TTL.
icmpType The ICMP Type.
icmpCode The ICMP Code.
icmpInfo The ICMP Info.
Definition at line 266 of file ipv6-fragmentation-test.cc.
References m_icmpCode, and m_icmpType.
Referenced by StartClient().
HandleReadServer()
void Ipv6FragmentationTest::HandleReadServer (Ptr< Socket > socket)
Handle incoming packets.
Parameters
socket The receiving socket.
Definition at line 221 of file ipv6-fragmentation-test.cc.
References ns3::Packet::Copy(), m_receivedPacketServer, and ns3::Socket::RecvFrom().
Referenced by StartServer().
SendClient()
Ptr< Packet > Ipv6FragmentationTest::SendClient (void)
Send a packet.
Returns
The sent packet.
Definition at line 302 of file ipv6-fragmentation-test.cc.
References ns3::Packet::AddByteTag(), ns3::Packet::AddPacketTag(), m_data, m_dataSize, m_size, m_socketClient, ns3::Socket::Send(), and IPv6TestTag::SetToken().
Referenced by DoRun().
SetFill()
void Ipv6FragmentationTest::SetFill (uint8_t * fill, uint32_t fillSize, uint32_t dataSize)
Set the packet fill.
Parameters
fill The fill.
fillSize The fill size.
dataSize The packet size.
Definition at line 275 of file ipv6-fragmentation-test.cc.
References m_data, m_dataSize, and m_size.
Referenced by DoRun().
StartClient()
void Ipv6FragmentationTest::StartClient (Ptr< Node > ClientNode)
Start the client.
Parameters
ClientNode The client.
Definition at line 235 of file ipv6-fragmentation-test.cc.
References ns3::Socket::Bind(), ns3::Socket::Connect(), HandleReadClient(), HandleReadIcmpClient(), m_socketClient, ns3::MakeCallback(), ns3::ObjectBase::SetAttribute(), and ns3::Socket::SetRecvCallback().
Referenced by DoRun().
StartServer()
void Ipv6FragmentationTest::StartServer (Ptr< Node > ServerNode)
Start the server.
Parameters
ServerNode The server.
Definition at line 205 of file ipv6-fragmentation-test.cc.
References ns3::Socket::Bind(), HandleReadServer(), m_socketServer, ns3::MakeCallback(), and ns3::Socket::SetRecvCallback().
Referenced by DoRun().
Member Data Documentation
m_data
uint8_t* Ipv6FragmentationTest::m_data private
Data.
Definition at line 120 of file ipv6-fragmentation-test.cc.
Referenced by Ipv6FragmentationTest(), ~Ipv6FragmentationTest(), DoRun(), SendClient(), and SetFill().
m_dataSize
uint32_t Ipv6FragmentationTest::m_dataSize private
Data size.
Definition at line 119 of file ipv6-fragmentation-test.cc.
Referenced by Ipv6FragmentationTest(), ~Ipv6FragmentationTest(), SendClient(), and SetFill().
m_icmpCode
uint8_t Ipv6FragmentationTest::m_icmpCode private
ICMP code.
Definition at line 123 of file ipv6-fragmentation-test.cc.
Referenced by Ipv6FragmentationTest(), DoRun(), and HandleReadIcmpClient().
m_icmpType
uint8_t Ipv6FragmentationTest::m_icmpType private
ICMP type.
Definition at line 122 of file ipv6-fragmentation-test.cc.
Referenced by Ipv6FragmentationTest(), DoRun(), and HandleReadIcmpClient().
m_receivedPacketClient
Ptr<Packet> Ipv6FragmentationTest::m_receivedPacketClient private
Packet received by client.
Definition at line 113 of file ipv6-fragmentation-test.cc.
Referenced by HandleReadClient().
m_receivedPacketServer
Ptr<Packet> Ipv6FragmentationTest::m_receivedPacketServer private
Packet received by server.
Definition at line 114 of file ipv6-fragmentation-test.cc.
Referenced by DoRun(), and HandleReadServer().
m_sentPacketClient
Ptr<Packet> Ipv6FragmentationTest::m_sentPacketClient private
Packet sent by client.
Definition at line 112 of file ipv6-fragmentation-test.cc.
m_size
uint32_t Ipv6FragmentationTest::m_size private
packet size.
Definition at line 121 of file ipv6-fragmentation-test.cc.
Referenced by Ipv6FragmentationTest(), SendClient(), and SetFill().
m_socketClient
Ptr<Socket> Ipv6FragmentationTest::m_socketClient private
Client socket.
Definition at line 118 of file ipv6-fragmentation-test.cc.
Referenced by DoRun(), SendClient(), and StartClient().
m_socketServer
Ptr<Socket> Ipv6FragmentationTest::m_socketServer private
Server socket.
Definition at line 117 of file ipv6-fragmentation-test.cc.
Referenced by Ipv6FragmentationTest(), and StartServer().
The documentation for this class was generated from the following file:
src/internet/test/ipv6-fragmentation-test.cc