ns-3: ns3::ArpHeader Class Reference
ns3::ArpHeader Class Reference
Internet » IPv4 classes and sub-modules » ARP protocol.
The packet header for an ARP packet.
#include "arp-header.h"
Public Types
enum ArpType_e { ARP_TYPE_REQUEST = 1, ARP_TYPE_REPLY = 2 }
Enumeration listing the possible ARP types.
Public Member Functions
virtual uint32_t Deserialize (Buffer::Iterator start)
Address GetDestinationHardwareAddress (void) const
Returns the destination hardware address.
Ipv4Address GetDestinationIpv4Address (void) const
Returns the destination IP address.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize (void) const
Address GetSourceHardwareAddress (void) const
Returns the source hardware address.
Ipv4Address GetSourceIpv4Address (void) const
Returns the source IP address.
bool IsReply (void) const
Check if the ARP is a reply.
bool IsRequest (void) const
Check if the ARP is a request.
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetReply (Address sourceHardwareAddress, Ipv4Address sourceProtocolAddress, Address destinationHardwareAddress, Ipv4Address destinationProtocolAddress)
Set the ARP reply parameters.
void SetRequest (Address sourceHardwareAddress, Ipv4Address sourceProtocolAddress, Address destinationHardwareAddress, Ipv4Address destinationProtocolAddress)
Set the ARP request parameters.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Public Attributes
Ipv4Address m_ipv4Dest
IP destination address.
Ipv4Address m_ipv4Source
IP source address.
Address m_macDest
hardware destination address
Address m_macSource
hardware source address
uint16_t m_type
type of the ICMP (ARP_TYPE_REQUEST)
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The packet header for an ARP packet.
Definition at line 34 of file arp-header.h.
Member Enumeration Documentation
ArpType_e
enum ns3::ArpHeader::ArpType_e
Enumeration listing the possible ARP types.
Enumerator
ARP_TYPE_REQUEST
ARP_TYPE_REPLY
Definition at line 110 of file arp-header.h.
Member Function Documentation
Deserialize()
uint32_t ns3::ArpHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 169 of file arp-header.cc.
References GetSerializedSize(), m_ipv4Dest, m_ipv4Source, m_macDest, m_macSource, m_type, ns3::Buffer::Iterator::Next(), NS_LOG_FUNCTION, ns3::ReadFrom(), ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetDestinationHardwareAddress()
Address ns3::ArpHeader::GetDestinationHardwareAddress (void) const
Returns the destination hardware address.
Returns
the destination hardware address
Definition at line 77 of file arp-header.cc.
References m_macDest, and NS_LOG_FUNCTION.
Referenced by ns3::ArpQueueDiscItem::Hash(), and ns3::ArpL3Protocol::Receive().
GetDestinationIpv4Address()
Ipv4Address ns3::ArpHeader::GetDestinationIpv4Address (void) const
Returns the destination IP address.
Returns
the destination IP address
Definition at line 89 of file arp-header.cc.
References m_ipv4Dest, and NS_LOG_FUNCTION.
Referenced by ns3::ArpQueueDiscItem::Hash(), and ns3::ArpL3Protocol::Receive().
GetInstanceTypeId()
TypeId ns3::ArpHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 107 of file arp-header.cc.
References GetTypeId(), and NS_LOG_FUNCTION.
GetSerializedSize()
uint32_t ns3::ArpHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 136 of file arp-header.cc.
References ns3::Address::GetLength(), m_macDest, m_macSource, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by Deserialize(), and ns3::ArpQueueDiscItem::GetSize().
GetSourceHardwareAddress()
Address ns3::ArpHeader::GetSourceHardwareAddress (void) const
Returns the source hardware address.
Returns
the source hardware address
Definition at line 71 of file arp-header.cc.
References m_macSource, and NS_LOG_FUNCTION.
Referenced by ns3::ArpQueueDiscItem::Hash(), and ns3::ArpL3Protocol::Receive().
GetSourceIpv4Address()
Ipv4Address ns3::ArpHeader::GetSourceIpv4Address (void) const
Returns the source IP address.
Returns
the source IP address
Definition at line 83 of file arp-header.cc.
References m_ipv4Source, and NS_LOG_FUNCTION.
Referenced by ns3::ArpQueueDiscItem::Hash(), and ns3::ArpL3Protocol::Receive().
GetTypeId()
TypeId ns3::ArpHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 97 of file arp-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
IsReply()
bool ns3::ArpHeader::IsReply (void) const
Check if the ARP is a reply.
Returns
true if it is a reply
Definition at line 65 of file arp-header.cc.
References ARP_TYPE_REPLY, m_type, and NS_LOG_FUNCTION.
Referenced by Print(), and ns3::ArpL3Protocol::Receive().
IsRequest()
bool ns3::ArpHeader::IsRequest (void) const
Check if the ARP is a request.
Returns
true if it is a request
Definition at line 59 of file arp-header.cc.
References ARP_TYPE_REQUEST, m_type, and NS_LOG_FUNCTION.
Referenced by ns3::ArpQueueDiscItem::Hash(), Print(), and ns3::ArpL3Protocol::Receive().
Print()
void ns3::ArpHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 113 of file arp-header.cc.
References IsReply(), IsRequest(), m_ipv4Dest, m_ipv4Source, m_macDest, m_macSource, NS_ASSERT, and NS_LOG_FUNCTION.
Serialize()
void ns3::ArpHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 149 of file arp-header.cc.
References ns3::Address::GetLength(), m_ipv4Dest, m_ipv4Source, m_macDest, m_macSource, m_type, NS_ASSERT, NS_LOG_FUNCTION, visualizer.core::start(), ns3::Buffer::Iterator::WriteHtonU16(), ns3::WriteTo(), and ns3::Buffer::Iterator::WriteU8().
SetReply()
void ns3::ArpHeader::SetReply (Address sourceHardwareAddress, Ipv4Address sourceProtocolAddress, Address destinationHardwareAddress, Ipv4Address destinationProtocolAddress)
Set the ARP reply parameters.
Parameters
sourceHardwareAddress the source hardware address
sourceProtocolAddress the source IP address
destinationHardwareAddress the destination hardware address (usually the broadcast address)
destinationProtocolAddress the destination IP address
Definition at line 46 of file arp-header.cc.
References ARP_TYPE_REPLY, m_ipv4Dest, m_ipv4Source, m_macDest, m_macSource, m_type, and NS_LOG_FUNCTION.
Referenced by ns3::ArpL3Protocol::SendArpReply().
SetRequest()
void ns3::ArpHeader::SetRequest (Address sourceHardwareAddress, Ipv4Address sourceProtocolAddress, Address destinationHardwareAddress, Ipv4Address destinationProtocolAddress)
Set the ARP request parameters.
Parameters
sourceHardwareAddress the source hardware address
sourceProtocolAddress the source IP address
destinationHardwareAddress the destination hardware address (usually the broadcast address)
destinationProtocolAddress the destination IP address
Definition at line 33 of file arp-header.cc.
References ARP_TYPE_REQUEST, m_ipv4Dest, m_ipv4Source, m_macDest, m_macSource, m_type, and NS_LOG_FUNCTION.
Referenced by ns3::ArpL3Protocol::SendArpRequest().
Member Data Documentation
m_ipv4Dest
Ipv4Address ns3::ArpHeader::m_ipv4Dest
IP destination address.
Definition at line 118 of file arp-header.h.
Referenced by Deserialize(), GetDestinationIpv4Address(), Print(), Serialize(), SetReply(), and SetRequest().
m_ipv4Source
Ipv4Address ns3::ArpHeader::m_ipv4Source
IP source address.
Definition at line 117 of file arp-header.h.
Referenced by Deserialize(), GetSourceIpv4Address(), Print(), Serialize(), SetReply(), and SetRequest().
m_macDest
Address ns3::ArpHeader::m_macDest
hardware destination address
Definition at line 116 of file arp-header.h.
Referenced by Deserialize(), GetDestinationHardwareAddress(), GetSerializedSize(), Print(), Serialize(), SetReply(), and SetRequest().
m_macSource
Address ns3::ArpHeader::m_macSource
hardware source address
Definition at line 115 of file arp-header.h.
Referenced by Deserialize(), GetSerializedSize(), GetSourceHardwareAddress(), Print(), Serialize(), SetReply(), and SetRequest().
m_type
uint16_t ns3::ArpHeader::m_type
type of the ICMP (ARP_TYPE_REQUEST)
Definition at line 114 of file arp-header.h.
Referenced by Deserialize(), IsReply(), IsRequest(), Serialize(), SetReply(), and SetRequest().
The documentation for this class was generated from the following files:
src/internet/model/arp-header.h
src/internet/model/arp-header.cc