ns-3: ns3::ExtendedSupportedRatesIE Class Reference
ns3::ExtendedSupportedRatesIE Class Reference
Wifi Models
The Extended Supported Rates Information Element.
#include "supported-rates.h"
Public Member Functions
ExtendedSupportedRatesIE ()
ExtendedSupportedRatesIE (SupportedRates *rates)
Create an extended supported rates information element from the given rates.
uint8_t DeserializeInformationField (Buffer::Iterator start, uint8_t length)
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
WifiInformationElementId ElementId () const
uint8_t GetInformationFieldSize () const
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
uint16_t GetSerializedSize () const
Buffer::Iterator Serialize (Buffer::Iterator start) const
void SerializeInformationField (Buffer::Iterator start) const
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
void SetSupportedRates (SupportedRates *rates)
Set supported rates.
Public Member Functions inherited from ns3::WifiInformationElement
virtual ~WifiInformationElement ()
Buffer::Iterator Deserialize (Buffer::Iterator i)
Deserialize entire IE, which must be present.
Buffer::Iterator DeserializeIfPresent (Buffer::Iterator i)
Deserialize entire IE if it is present.
virtual WifiInformationElementId ElementIdExt () const
uint16_t GetSerializedSize () const
Get the size of the serialized IE including Element ID and length fields.
virtual bool operator== (WifiInformationElement const &a) const
Compare two IEs for equality by ID & Length, and then through memcmp of serialised version.
virtual void Print (std::ostream &os) const
Generate human-readable form of IE.
Buffer::Iterator Serialize (Buffer::Iterator i) const
Serialize entire IE including Element ID and length fields.
Public Member Functions inherited from ns3::SimpleRefCount< WifiInformationElement >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
SupportedRates * m_supportedRates
This member points to the SupportedRates object that contains the actual rate details.
Detailed Description
The Extended Supported Rates Information Element.
This class knows how to serialise and deserialise the Extended Supported Rates Element that holds (non-HT) rates beyond the 8 that the original Supported Rates element can carry.
The SupportedRates class still records all the rates, and an instance of ExtendedSupportedRatesIE lies within SupportedRates.
Definition at line 42 of file supported-rates.h.
Constructor & Destructor Documentation
ExtendedSupportedRatesIE() [1/2]
ns3::ExtendedSupportedRatesIE::ExtendedSupportedRatesIE ()
Definition at line 207 of file supported-rates.cc.
ExtendedSupportedRatesIE() [2/2]
ns3::ExtendedSupportedRatesIE::ExtendedSupportedRatesIE (SupportedRates * rates)
Create an extended supported rates information element from the given rates.
Parameters
rates the extended supported rates
Definition at line 211 of file supported-rates.cc.
References m_supportedRates.
Member Function Documentation
DeserializeInformationField()
uint8_t ns3::ExtendedSupportedRatesIE::DeserializeInformationField (Buffer::Iterator start, uint8_t length) virtual
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
length
Returns
the number of bytes read
Implements ns3::WifiInformationElement.
Definition at line 287 of file supported-rates.cc.
References ns3::SupportedRates::m_nRates, ns3::SupportedRates::m_rates, m_supportedRates, ns3::SupportedRates::MAX_SUPPORTED_RATES, NS_ASSERT, and visualizer.core::start().
ElementId()
WifiInformationElementId ns3::ExtendedSupportedRatesIE::ElementId () const virtual
Returns
Own unique Element ID
Implements ns3::WifiInformationElement.
Definition at line 217 of file supported-rates.cc.
References IE_EXTENDED_SUPPORTED_RATES.
GetInformationFieldSize()
uint8_t ns3::ExtendedSupportedRatesIE::GetInformationFieldSize () const virtual
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
This is the value that will appear in the second octet of the entire IE - the length field)
Returns
the length of serialized information
Implements ns3::WifiInformationElement.
Definition at line 229 of file supported-rates.cc.
References ns3::SupportedRates::m_nRates, m_supportedRates, and NS_ASSERT.
GetSerializedSize()
uint16_t ns3::ExtendedSupportedRatesIE::GetSerializedSize () const
Definition at line 272 of file supported-rates.cc.
References ns3::WifiInformationElement::GetSerializedSize(), ns3::SupportedRates::m_nRates, and m_supportedRates.
Referenced by ns3::dot11s::PeerLinkOpenStart::GetSerializedSize(), ns3::dot11s::PeerLinkConfirmStart::GetSerializedSize(), ns3::MgtAssocRequestHeader::GetSerializedSize(), ns3::MgtReassocRequestHeader::GetSerializedSize(), ns3::MgtAssocResponseHeader::GetSerializedSize(), ns3::MgtProbeRequestHeader::GetSerializedSize(), and ns3::MgtProbeResponseHeader::GetSerializedSize().
Serialize()
Buffer::Iterator ns3::ExtendedSupportedRatesIE::Serialize (Buffer::Iterator start) const
Definition at line 258 of file supported-rates.cc.
References ns3::SupportedRates::m_nRates, m_supportedRates, ns3::WifiInformationElement::Serialize(), and visualizer.core::start().
Referenced by ns3::dot11s::PeerLinkOpenStart::Serialize(), ns3::dot11s::PeerLinkConfirmStart::Serialize(), ns3::MgtAssocRequestHeader::Serialize(), ns3::MgtReassocRequestHeader::Serialize(), ns3::MgtAssocResponseHeader::Serialize(), ns3::MgtProbeRequestHeader::Serialize(), and ns3::MgtProbeResponseHeader::Serialize().
SerializeInformationField()
void ns3::ExtendedSupportedRatesIE::SerializeInformationField (Buffer::Iterator start) const virtual
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
Implements ns3::WifiInformationElement.
Definition at line 244 of file supported-rates.cc.
References ns3::SupportedRates::m_nRates, ns3::SupportedRates::m_rates, m_supportedRates, NS_ASSERT, and visualizer.core::start().
SetSupportedRates()
void ns3::ExtendedSupportedRatesIE::SetSupportedRates (SupportedRates * rates)
Set supported rates.
Parameters
rates the supported rates
Definition at line 223 of file supported-rates.cc.
References m_supportedRates.
Referenced by ns3::SupportedRates::SupportedRates(), and ns3::SupportedRates::operator=().
Member Data Documentation
m_supportedRates
SupportedRates* ns3::ExtendedSupportedRatesIE::m_supportedRates private
This member points to the SupportedRates object that contains the actual rate details.
This class is a friend of that, so we have access to all the private data we need.
Definition at line 81 of file supported-rates.h.
Referenced by ExtendedSupportedRatesIE(), DeserializeInformationField(), GetInformationFieldSize(), GetSerializedSize(), Serialize(), SerializeInformationField(), and SetSupportedRates().
The documentation for this class was generated from the following files:
src/wifi/model/supported-rates.h
src/wifi/model/supported-rates.cc