ns-3: ns3::UanPropModel Class Reference
ns3::UanPropModel Class Reference abstract
UAN Models
#include "uan-prop-model.h"
Public Member Functions
virtual void Clear (void)
Clear all pointer references.
virtual void DoDispose (void)
Destructor implementation.
virtual Time GetDelay (Ptr< MobilityModel > a, Ptr< MobilityModel > b, UanTxMode mode)=0
Finds propagation delay between nodes a and b.
virtual double GetPathLossDb (Ptr< MobilityModel > a, Ptr< MobilityModel > b, UanTxMode txMode)=0
Computes pathloss between nodes a and b.
virtual UanPdp GetPdp (Ptr< MobilityModel > a, Ptr< MobilityModel > b, UanTxMode mode)=0
Get the PDP for the path between two nodes.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Base class for implemented underwater propagation models
Definition at line 286 of file uan-prop-model.h.
Member Function Documentation
Clear()
void ns3::UanPropModel::Clear (void) virtual
Clear all pointer references.
Definition at line 372 of file uan-prop-model.cc.
Referenced by DoDispose().
DoDispose()
void ns3::UanPropModel::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 377 of file uan-prop-model.cc.
References Clear(), and ns3::Object::DoDispose().
GetDelay()
virtual Time ns3::UanPropModel::GetDelay (Ptr< MobilityModel > a, Ptr< MobilityModel > b, UanTxMode mode) pure virtual
Finds propagation delay between nodes a and b.
Parameters
a Ptr to mobility model of node a.
b Ptr to mobility model of node b.
mode TX mode of transmission.
Returns
Propagation delay.
Implemented in ns3::UanPropModelThorp, and ns3::UanPropModelIdeal.
GetPathLossDb()
virtual double ns3::UanPropModel::GetPathLossDb (Ptr< MobilityModel > a, Ptr< MobilityModel > b, UanTxMode txMode) pure virtual
Computes pathloss between nodes a and b.
Parameters
a Ptr to mobility model of node a
b Ptr to mobility model of node b
txMode TX mode of transmission between a and b
Returns
Pathloss in dB re 1 uPa
Implemented in ns3::UanPropModelThorp, and ns3::UanPropModelIdeal.
GetPdp()
virtual UanPdp ns3::UanPropModel::GetPdp (Ptr< MobilityModel > a, Ptr< MobilityModel > b, UanTxMode mode) pure virtual
Get the PDP for the path between two nodes.
Parameters
a Ptr to mobility model of node a.
b Ptr to mobility model of node b.
mode TX mode of transmission from a to b.
Returns
PDP for link between nodes a and b.
Implemented in ns3::UanPropModelThorp, and ns3::UanPropModelIdeal.
GetTypeId()
TypeId ns3::UanPropModel::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 362 of file uan-prop-model.cc.
References ns3::TypeId::SetParent().
The documentation for this class was generated from the following files:
src/uan/model/uan-prop-model.h
src/uan/model/uan-prop-model.cc