ns-3: ns3::LtePdcp Class Reference
ns3::LtePdcp Class Reference
LTE PDCP entity, see 3GPP TS 36.323.
#include "lte-pdcp.h"
Classes
struct Status
Status variables of the PDCP.
Public Types
typedef void(* PduRxTracedCallback) (const uint16_t rnti, const uint8_t lcid, const uint32_t size, const uint64_t delay)
TracedCallback signature for PDU receive event.
typedef void(* PduTxTracedCallback) (uint16_t rnti, uint8_t lcid, uint32_t size)
TracedCallback for PDU transmission event.
Public Member Functions
LtePdcp ()
virtual ~LtePdcp ()
virtual void DoDispose ()
Destructor implementation.
LtePdcpSapProvider * GetLtePdcpSapProvider ()
LteRlcSapUser * GetLteRlcSapUser ()
Status GetStatus ()
void SetLcId (uint8_t lcId)
void SetLtePdcpSapUser (LtePdcpSapUser *s)
void SetLteRlcSapProvider (LteRlcSapProvider *s)
void SetRnti (uint16_t rnti)
void SetStatus (Status s)
Set the status of the PDCP.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static const uint16_t MAX_PDCP_SN = 4096
maximum PDCP SN
Protected Member Functions
virtual void DoReceivePdu (Ptr< Packet > p)
Interface provided to lower RLC entity.
virtual void DoTransmitPdcpSdu (Ptr< Packet > p)
Interface provided to upper RRC entity.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes
uint8_t m_lcid
LCID.
LtePdcpSapProvider * m_pdcpSapProvider
PDCP SAP provider.
LtePdcpSapUser * m_pdcpSapUser
PDCP SAP user.
LteRlcSapProvider * m_rlcSapProvider
RLC SAP provider.
LteRlcSapUser * m_rlcSapUser
RLC SAP user.
uint16_t m_rnti
RNTI.
TracedCallback< uint16_t, uint8_t, uint32_t, uint64_t > m_rxPdu
Used to inform of a PDU reception from the RLC SAP user.
TracedCallback< uint16_t, uint8_t, uint32_t > m_txPdu
Used to inform of a PDU delivery to the RLC SAP provider.
Private Attributes
uint16_t m_rxSequenceNumber
State variables.
uint16_t m_txSequenceNumber
State variables.
Static Private Attributes
static const uint16_t m_maxPdcpSn = 4095
Constants.
Friends
class LtePdcpSpecificLtePdcpSapProvider< LtePdcp >
allow LtePdcpSpecificLtePdcpSapProvider<LtePdcp> class friend access
class LtePdcpSpecificLteRlcSapUser
allow LtePdcpSpecificLteRlcSapUser class friend access
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
LTE PDCP entity, see 3GPP TS 36.323.
Definition at line 37 of file lte-pdcp.h.
Member Typedef Documentation
PduRxTracedCallback
typedef void(* ns3::LtePdcp::PduRxTracedCallback) (const uint16_t rnti, const uint8_t lcid, const uint32_t size, const uint64_t delay)
TracedCallback signature for PDU receive event.
Parameters
[in] rnti The C-RNTI identifying the UE.
[in] lcid The logical channel id corresponding to the sending RLC instance.
[in] size Packet size.
[in] delay Delay since packet sent, in ns..
Definition at line 140 of file lte-pdcp.h.
PduTxTracedCallback
typedef void(* ns3::LtePdcp::PduTxTracedCallback) (uint16_t rnti, uint8_t lcid, uint32_t size)
TracedCallback for PDU transmission event.
Parameters
[in] rnti The C-RNTI identifying the UE.
[in] lcid The logical channel id corresponding to the sending RLC instance.
[in] size Packet size.
Definition at line 128 of file lte-pdcp.h.
Constructor & Destructor Documentation
LtePdcp()
ns3::LtePdcp::LtePdcp ()
Definition at line 71 of file lte-pdcp.cc.
References LtePdcpSpecificLtePdcpSapProvider< LtePdcp >, LtePdcpSpecificLteRlcSapUser, m_pdcpSapProvider, m_rlcSapUser, and NS_LOG_FUNCTION.
~LtePdcp()
ns3::LtePdcp::~LtePdcp () virtual
Definition at line 84 of file lte-pdcp.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::LtePdcp::DoDispose () virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 108 of file lte-pdcp.cc.
References m_pdcpSapProvider, m_rlcSapUser, and NS_LOG_FUNCTION.
DoReceivePdu()
void ns3::LtePdcp::DoReceivePdu (Ptr< Packet > p) protected virtual
Interface provided to lower RLC entity.
Parameters
p packet
Definition at line 210 of file lte-pdcp.cc.
References ns3::Packet::FindFirstMatchingByteTag(), ns3::Time::GetNanoSeconds(), ns3::PdcpTag::GetSenderTimestamp(), ns3::LtePdcpHeader::GetSequenceNumber(), ns3::Packet::GetSize(), m_lcid, m_maxPdcpSn, m_pdcpSapUser, m_rnti, m_rxPdu, m_rxSequenceNumber, ns3::Simulator::Now(), NS_LOG_FUNCTION, NS_LOG_LOGIC(), aloha::params, ns3::LtePdcpSapUser::ReceivePdcpSdu(), and ns3::Packet::RemoveHeader().
Referenced by ns3::LtePdcpSpecificLteRlcSapUser::ReceivePdcpPdu().
DoTransmitPdcpSdu()
void ns3::LtePdcp::DoTransmitPdcpSdu (Ptr< Packet > p) protected virtual
Interface provided to upper RRC entity.
Parameters
p packet
Definition at line 177 of file lte-pdcp.cc.
References ns3::Packet::AddByteTag(), ns3::Packet::AddHeader(), ns3::LtePdcpHeader::DATA_PDU, ns3::LtePdcpHeader::GetSerializedSize(), ns3::Packet::GetSize(), m_lcid, m_maxPdcpSn, m_rlcSapProvider, m_rnti, m_txPdu, m_txSequenceNumber, ns3::Simulator::Now(), NS_LOG_FUNCTION, NS_LOG_LOGIC(), aloha::params, ns3::LtePdcpHeader::SetDcBit(), ns3::LtePdcpHeader::SetSequenceNumber(), and ns3::LteRlcSapProvider::TransmitPdcpPdu().
GetLtePdcpSapProvider()
LtePdcpSapProvider * ns3::LtePdcp::GetLtePdcpSapProvider ()
Returns
the PDCP SAP Provider interface offered to the RRC by this LTE_PDCP
Definition at line 138 of file lte-pdcp.cc.
References m_pdcpSapProvider, and NS_LOG_FUNCTION.
GetLteRlcSapUser()
LteRlcSapUser * ns3::LtePdcp::GetLteRlcSapUser ()
Returns
the RLC SAP User interface offered to the RLC by this LTE_PDCP
Definition at line 152 of file lte-pdcp.cc.
References m_rlcSapUser, and NS_LOG_FUNCTION.
GetStatus()
LtePdcp::Status ns3::LtePdcp::GetStatus ()
Returns
the current status of the PDCP
Definition at line 159 of file lte-pdcp.cc.
References m_rxSequenceNumber, m_txSequenceNumber, ns3::LtePdcp::Status::rxSn, and ns3::LtePdcp::Status::txSn.
GetTypeId()
TypeId ns3::LtePdcp::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 90 of file lte-pdcp.cc.
References m_rxPdu, m_txPdu, ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
SetLcId()
void ns3::LtePdcp::SetLcId (uint8_t lcId)
Parameters
lcId
Definition at line 124 of file lte-pdcp.cc.
References m_lcid, and NS_LOG_FUNCTION.
SetLtePdcpSapUser()
void ns3::LtePdcp::SetLtePdcpSapUser (LtePdcpSapUser * s)
Parameters
s the PDCP SAP user to be used by this LTE_PDCP
Definition at line 131 of file lte-pdcp.cc.
References m_pdcpSapUser, and NS_LOG_FUNCTION.
SetLteRlcSapProvider()
void ns3::LtePdcp::SetLteRlcSapProvider (LteRlcSapProvider * s)
Parameters
s the RLC SAP Provider to be used by this LTE_PDCP
Definition at line 145 of file lte-pdcp.cc.
References m_rlcSapProvider, and NS_LOG_FUNCTION.
SetRnti()
void ns3::LtePdcp::SetRnti (uint16_t rnti)
Parameters
rnti
Definition at line 117 of file lte-pdcp.cc.
References m_rnti, and NS_LOG_FUNCTION.
SetStatus()
void ns3::LtePdcp::SetStatus (Status s)
Set the status of the PDCP.
Parameters
s
Definition at line 168 of file lte-pdcp.cc.
References m_rxSequenceNumber, m_txSequenceNumber, ns3::LtePdcp::Status::rxSn, and ns3::LtePdcp::Status::txSn.
Friends And Related Function Documentation
LtePdcpSpecificLtePdcpSapProvider< LtePdcp >
friend class LtePdcpSpecificLtePdcpSapProvider< LtePdcp > friend
allow LtePdcpSpecificLtePdcpSapProvider<LtePdcp> class friend access
Definition at line 40 of file lte-pdcp.h.
Referenced by LtePdcp().
LtePdcpSpecificLteRlcSapUser
friend class LtePdcpSpecificLteRlcSapUser friend
allow LtePdcpSpecificLteRlcSapUser class friend access
Definition at line 40 of file lte-pdcp.h.
Referenced by LtePdcp().
Member Data Documentation
m_lcid
uint8_t ns3::LtePdcp::m_lcid protected
LCID.
Definition at line 166 of file lte-pdcp.h.
Referenced by DoReceivePdu(), DoTransmitPdcpSdu(), and SetLcId().
m_maxPdcpSn
const uint16_t ns3::LtePdcp::m_maxPdcpSn = 4095 static private
Constants.
See section 7.2 in TS 36.323
Definition at line 192 of file lte-pdcp.h.
Referenced by DoReceivePdu(), and DoTransmitPdcpSdu().
m_pdcpSapProvider
LtePdcpSapProvider* ns3::LtePdcp::m_pdcpSapProvider protected
PDCP SAP provider.
Definition at line 153 of file lte-pdcp.h.
Referenced by LtePdcp(), DoDispose(), and GetLtePdcpSapProvider().
m_pdcpSapUser
LtePdcpSapUser* ns3::LtePdcp::m_pdcpSapUser protected
PDCP SAP user.
Definition at line 152 of file lte-pdcp.h.
Referenced by DoReceivePdu(), and SetLtePdcpSapUser().
m_rlcSapProvider
LteRlcSapProvider* ns3::LtePdcp::m_rlcSapProvider protected
RLC SAP provider.
Definition at line 163 of file lte-pdcp.h.
Referenced by DoTransmitPdcpSdu(), and SetLteRlcSapProvider().
m_rlcSapUser
LteRlcSapUser* ns3::LtePdcp::m_rlcSapUser protected
RLC SAP user.
Definition at line 162 of file lte-pdcp.h.
Referenced by LtePdcp(), DoDispose(), and GetLteRlcSapUser().
m_rnti
uint16_t ns3::LtePdcp::m_rnti protected
RNTI.
Definition at line 165 of file lte-pdcp.h.
Referenced by DoReceivePdu(), DoTransmitPdcpSdu(), and SetRnti().
m_rxPdu
TracedCallback<uint16_t, uint8_t, uint32_t, uint64_t> ns3::LtePdcp::m_rxPdu protected
Used to inform of a PDU reception from the RLC SAP user.
The parameters are RNTI, LCID, bytes delivered and delivery delay in nanoseconds.
Definition at line 177 of file lte-pdcp.h.
Referenced by DoReceivePdu(), and GetTypeId().
m_rxSequenceNumber
uint16_t ns3::LtePdcp::m_rxSequenceNumber private
State variables.
See section 7.1 in TS 36.323
Definition at line 187 of file lte-pdcp.h.
Referenced by DoReceivePdu(), GetStatus(), and SetStatus().
m_txPdu
TracedCallback<uint16_t, uint8_t, uint32_t> ns3::LtePdcp::m_txPdu protected
Used to inform of a PDU delivery to the RLC SAP provider.
The parameters are RNTI, LCID and bytes delivered
Definition at line 172 of file lte-pdcp.h.
Referenced by DoTransmitPdcpSdu(), and GetTypeId().
m_txSequenceNumber
uint16_t ns3::LtePdcp::m_txSequenceNumber private
State variables.
See section 7.1 in TS 36.323
Definition at line 183 of file lte-pdcp.h.
Referenced by DoTransmitPdcpSdu(), GetStatus(), and SetStatus().
MAX_PDCP_SN
const uint16_t ns3::LtePdcp::MAX_PDCP_SN = 4096 static
maximum PDCP SN
Definition at line 96 of file lte-pdcp.h.
The documentation for this class was generated from the following files:
src/lte/model/lte-pdcp.h
src/lte/model/lte-pdcp.cc