ns-3: LookupTimeTestCase Class Reference
LookupTimeTestCase Class Reference
Public Member Functions
LookupTimeTestCase ()
virtual ~LookupTimeTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Types
enum { REPETITIONS = 100000 }
Private Member Functions
void DoRun (void)
Implementation to actually run this TestCase.
void DoSetup (void)
Implementation to do any local setup required for this TestCase.
void Report (const std::string how, const uint32_t delta) const
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 341 of file type-id-test-suite.cc.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
REPETITIONS
Definition at line 352 of file type-id-test-suite.cc.
Constructor & Destructor Documentation
LookupTimeTestCase()
LookupTimeTestCase::LookupTimeTestCase ()
Definition at line 358 of file type-id-test-suite.cc.
~LookupTimeTestCase()
LookupTimeTestCase::~LookupTimeTestCase () virtual
Definition at line 362 of file type-id-test-suite.cc.
Member Function Documentation
DoRun()
void LookupTimeTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 366 of file type-id-test-suite.cc.
References ns3::TypeId::GetHash(), ns3::TestCase::GetName(), ns3::TypeId::GetName(), REPETITIONS, Report(), visualizer.core::start(), and suite().
DoSetup()
void LookupTimeTestCase::DoSetup (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test setup before DoRun is invoked.
Reimplemented from ns3::TestCase.
Definition at line 400 of file type-id-test-suite.cc.
References REPETITIONS, and suite().
Report()
void LookupTimeTestCase::Report (const std::string how, const uint32_t delta) const private
Definition at line 411 of file type-id-test-suite.cc.
References REPETITIONS, and suite().
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/core/test/type-id-test-suite.cc