ns-3: ns3::BandwidthManager Class Reference
ns3::BandwidthManager Class Reference
WiMAX Models
This class manage the bandwidth request and grant mechanism. The bandwidth request and grant mechanism is supported by the Bandwidth Manager. Both BS and SS maintain a bandwidth manager. Furthermore BS's bandwidth manager works together with the uplink scheduler to determine total bandwidth available and allocation size for each service flow. Bandwidth request mechanism is a key feature of the WiMAX scheduler since all three non-UGS services explicitly request for bandwidth by sending a bandwidth request to BS.
#include "bandwidth-manager.h"
Public Member Functions
BandwidthManager (Ptr< WimaxNetDevice > device)
Constructor.
~BandwidthManager (void)
uint32_t CalculateAllocationSize (const SSRecord *ssRecord, const ServiceFlow *serviceFlow)
Calculate allocation size function.
void DoDispose (void)
Destructor implementation.
uint32_t GetSymbolsPerFrameAllocated (void)
Get symbols per frame allocated.
void ProcessBandwidthRequest (const BandwidthRequestHeader &bwRequestHdr)
Process bandwidth request.
ServiceFlow * SelectFlowForRequest (uint32_t &bytesToRequest)
Select flow for request function.
void SendBandwidthRequest (uint8_t uiuc, uint16_t allocationSize)
Send bandwidth request.
void SetSubframeRatio (void)
Set subframe ratio.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
BandwidthManager (const BandwidthManager &)
Bandwidth manager type conversion operator.
BandwidthManager & operator= (const BandwidthManager &)
Bandwidth manager assignment operator.
Private Attributes
Ptr< WimaxNetDevice > m_device
the device
uint16_t m_nrBwReqsSent
bandwidth requests sent
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class manage the bandwidth request and grant mechanism. The bandwidth request and grant mechanism is supported by the Bandwidth Manager. Both BS and SS maintain a bandwidth manager. Furthermore BS's bandwidth manager works together with the uplink scheduler to determine total bandwidth available and allocation size for each service flow. Bandwidth request mechanism is a key feature of the WiMAX scheduler since all three non-UGS services explicitly request for bandwidth by sending a bandwidth request to BS.
Definition at line 54 of file bandwidth-manager.h.
Constructor & Destructor Documentation
BandwidthManager() [1/2]
ns3::BandwidthManager::BandwidthManager (Ptr< WimaxNetDevice > device)
Constructor.
Parameters
device WIMAX device
Definition at line 50 of file bandwidth-manager.cc.
~BandwidthManager()
ns3::BandwidthManager::~BandwidthManager (void)
Definition at line 56 of file bandwidth-manager.cc.
BandwidthManager() [2/2]
ns3::BandwidthManager::BandwidthManager (const BandwidthManager &) private
Bandwidth manager type conversion operator.
Member Function Documentation
CalculateAllocationSize()
uint32_t ns3::BandwidthManager::CalculateAllocationSize (const SSRecord * ssRecord, const ServiceFlow * serviceFlow)
Calculate allocation size function.
Parameters
ssRecord the SS record
serviceFlow the service flow
Returns
the allocation size
Definition at line 67 of file bandwidth-manager.cc.
References ns3::ServiceFlowRecord::GetGrantSize(), ns3::ServiceFlowRecord::GetGrantTimeStamp(), ns3::SSRecord::GetHasServiceFlowUgs(), ns3::SSRecord::GetPollMeBit(), ns3::ServiceFlow::GetRecord(), ns3::ServiceFlow::GetSchedulingType(), ns3::ServiceFlow::GetUnsolicitedGrantInterval(), ns3::ServiceFlow::GetUnsolicitedPollingInterval(), m_device, ns3::Simulator::Now(), NS_FATAL_ERROR, ns3::ServiceFlowRecord::SetGrantTimeStamp(), ns3::ServiceFlow::SF_TYPE_BE, ns3::ServiceFlow::SF_TYPE_NRTPS, ns3::ServiceFlow::SF_TYPE_RTPS, and ns3::ServiceFlow::SF_TYPE_UGS.
DoDispose()
void ns3::BandwidthManager::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 61 of file bandwidth-manager.cc.
References m_device.
GetSymbolsPerFrameAllocated()
uint32_t ns3::BandwidthManager::GetSymbolsPerFrameAllocated (void)
Get symbols per frame allocated.
Returns
the symbols per the frame allocated
Definition at line 218 of file bandwidth-manager.cc.
References m_device, and ns3::ServiceFlow::SF_TYPE_ALL.
GetTypeId()
TypeId ns3::BandwidthManager::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 42 of file bandwidth-manager.cc.
References ns3::TypeId::SetParent().
operator=()
BandwidthManager& ns3::BandwidthManager::operator= (const BandwidthManager &) private
Bandwidth manager assignment operator.
Returns
the bandwidth manager
ProcessBandwidthRequest()
void ns3::BandwidthManager::ProcessBandwidthRequest (const BandwidthRequestHeader & bwRequestHdr)
Process bandwidth request.
Parameters
bwRequestHdr the bandwidth request
Definition at line 184 of file bandwidth-manager.cc.
References ns3::BandwidthRequestHeader::GetBr(), ns3::BandwidthRequestHeader::GetCid(), ns3::BandwidthRequestHeader::GetType(), ns3::BandwidthRequestHeader::HEADER_TYPE_INCREMENTAL, and m_device.
SelectFlowForRequest()
ServiceFlow * ns3::BandwidthManager::SelectFlowForRequest (uint32_t & bytesToRequest)
Select flow for request function.
Parameters
bytesToRequest bytes to request
Returns
a service flow
Definition at line 127 of file bandwidth-manager.cc.
References ns3::ServiceFlow::GetQueue(), ns3::ServiceFlow::GetSchedulingType(), ns3::ServiceFlow::HasPackets(), ns3::MacHeaderType::HEADER_TYPE_GENERIC, m_device, ns3::ServiceFlow::SF_TYPE_ALL, ns3::ServiceFlow::SF_TYPE_BE, ns3::ServiceFlow::SF_TYPE_NRTPS, and ns3::ServiceFlow::SF_TYPE_RTPS.
Referenced by SendBandwidthRequest().
SendBandwidthRequest()
void ns3::BandwidthManager::SendBandwidthRequest (uint8_t uiuc, uint16_t allocationSize)
Send bandwidth request.
Parameters
uiuc the UIUC
allocationSize the allocation size
Definition at line 155 of file bandwidth-manager.cc.
References ns3::Packet::AddHeader(), ns3::ServiceFlow::GetConnection(), ns3::BandwidthRequestHeader::HEADER_TYPE_AGGREGATE, ns3::MacHeaderType::HEADER_TYPE_BANDWIDTH, m_device, m_nrBwReqsSent, NS_ASSERT_MSG(), SelectFlowForRequest(), ns3::BandwidthRequestHeader::SetBr(), ns3::BandwidthRequestHeader::SetCid(), ns3::BandwidthRequestHeader::SetType(), and ns3::OfdmUlBurstProfile::UIUC_REQ_REGION_FULL.
Referenced by ns3::SubscriberStationNetDevice::ProcessUlMap().
SetSubframeRatio()
void ns3::BandwidthManager::SetSubframeRatio (void)
Set subframe ratio.
Definition at line 204 of file bandwidth-manager.cc.
References m_device.
Member Data Documentation
m_device
Ptr<WimaxNetDevice> ns3::BandwidthManager::m_device private
the device
Definition at line 111 of file bandwidth-manager.h.
Referenced by CalculateAllocationSize(), DoDispose(), GetSymbolsPerFrameAllocated(), ProcessBandwidthRequest(), SelectFlowForRequest(), SendBandwidthRequest(), and SetSubframeRatio().
m_nrBwReqsSent
uint16_t ns3::BandwidthManager::m_nrBwReqsSent private
bandwidth requests sent
Definition at line 112 of file bandwidth-manager.h.
Referenced by SendBandwidthRequest().
The documentation for this class was generated from the following files:
src/wimax/model/bandwidth-manager.h
src/wimax/model/bandwidth-manager.cc