ns-3: ns3::GtpcDeleteBearerResponseMessage Class Reference
ns3::GtpcDeleteBearerResponseMessage Class Reference
#include "epc-gtpc-header.h"
Public Member Functions
GtpcDeleteBearerResponseMessage ()
virtual ~GtpcDeleteBearerResponseMessage ()
virtual uint32_t Deserialize (Buffer::Iterator start)
Cause_t GetCause () const
std::list< uint8_t > GetEpsBearerIds () const
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetMessageSize (void) const
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetCause (Cause_t cause)
void SetEpsBearerIds (std::list< uint8_t > epsBearerIds)
Public Member Functions inherited from ns3::GtpcHeader
GtpcHeader ()
virtual ~GtpcHeader ()
void ComputeMessageLength (void)
uint16_t GetMessageLength () const
Get message length.
uint8_t GetMessageType () const
Get message type.
uint32_t GetSequenceNumber () const
Get sequence number.
uint32_t GetTeid () const
Get TEID.
void SetIesLength (uint16_t iesLength)
Set IEs length.
void SetMessageLength (uint16_t messageLength)
Set message length.
void SetMessageType (uint8_t messageType)
Set message type.
void SetSequenceNumber (uint32_t sequenceNumber)
Set sequence number.
void SetTeid (uint32_t teid)
Set TEID.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Public Member Functions inherited from ns3::GtpcIes
uint32_t DeserializeBearerContextHeader (Buffer::Iterator &i, uint16_t &length)
uint32_t DeserializeBearerQos (Buffer::Iterator &i, EpsBearer &bearerQos)
uint32_t DeserializeBearerTft (Buffer::Iterator &i, Ptr< EpcTft > epcTft)
uint32_t DeserializeCause (Buffer::Iterator &i, Cause_t &cause)
uint32_t DeserializeEbi (Buffer::Iterator &i, uint8_t &epsBearerId)
uint32_t DeserializeFteid (Buffer::Iterator &i, GtpcHeader::Fteid_t &fteid)
uint32_t DeserializeImsi (Buffer::Iterator &i, uint64_t &imsi)
uint32_t DeserializeUliEcgi (Buffer::Iterator &i, uint32_t &uliEcgi)
uint32_t GetSerializedSizeBearerTft (std::list< EpcTft::PacketFilter > packetFilters) const
uint64_t ReadNtohU40 (Buffer::Iterator &i)
void SerializeBearerContextHeader (Buffer::Iterator &i, uint16_t length) const
void SerializeBearerQos (Buffer::Iterator &i, EpsBearer bearerQos) const
void SerializeBearerTft (Buffer::Iterator &i, std::list< EpcTft::PacketFilter > packetFilters) const
void SerializeCause (Buffer::Iterator &i, Cause_t cause) const
void SerializeEbi (Buffer::Iterator &i, uint8_t epsBearerId) const
void SerializeFteid (Buffer::Iterator &i, GtpcHeader::Fteid_t fteid) const
void SerializeImsi (Buffer::Iterator &i, uint64_t imsi) const
void SerializeUliEcgi (Buffer::Iterator &i, uint32_t uliEcgi) const
void WriteHtonU40 (Buffer::Iterator &i, uint64_t data) const
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::GtpcHeader
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Cause_t m_cause
std::list< uint8_t > m_epsBearerIds
Additional Inherited Members
Public Types inherited from ns3::GtpcHeader
enum InterfaceType_t {
S1U_ENB_GTPU = 0, S5_SGW_GTPU = 4, S5_PGW_GTPU = 5, S5_SGW_GTPC = 6,
S5_PGW_GTPC = 7, S11_MME_GTPC = 10
}
Interface Type enumeration.
enum MessageType_t {
Reserved = 0, CreateSessionRequest = 32, CreateSessionResponse = 33, ModifyBearerRequest = 34,
ModifyBearerResponse = 35, DeleteSessionRequest = 36, DeleteSessionResponse = 37, DeleteBearerCommand = 66,
DeleteBearerRequest = 99, DeleteBearerResponse = 100
}
Message Type enumeration.
Public Types inherited from ns3::GtpcIes
enum Cause_t { RESERVED = 0, REQUEST_ACCEPTED = 16 }
Public Attributes inherited from ns3::GtpcIes
const uint32_t serializedSizeBearerContextHeader = 4
const uint32_t serializedSizeBearerQos = 26
const uint32_t serializedSizeCause = 6
const uint32_t serializedSizeEbi = 5
const uint32_t serializedSizeFteid = 13
const uint32_t serializedSizeImsi = 12
const uint32_t serializedSizePacketFilter = 3 + 9 + 9 + 5 + 5 + 3
const uint32_t serializedSizeUliEcgi = 12
Protected Member Functions inherited from ns3::GtpcHeader
uint32_t PreDeserialize (Buffer::Iterator &i)
Deserialize the GTP-C header in the GTP-C messages.
void PreSerialize (Buffer::Iterator &i) const
Serialize the GTP-C header in the GTP-C messages.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 440 of file epc-gtpc-header.h.
Constructor & Destructor Documentation
GtpcDeleteBearerResponseMessage()
ns3::GtpcDeleteBearerResponseMessage::GtpcDeleteBearerResponseMessage ()
Definition at line 1194 of file epc-gtpc-header.cc.
References ns3::GtpcHeader::DeleteBearerResponse, ns3::GtpcHeader::SetMessageType(), and ns3::GtpcHeader::SetSequenceNumber().
~GtpcDeleteBearerResponseMessage()
ns3::GtpcDeleteBearerResponseMessage::~GtpcDeleteBearerResponseMessage () virtual
Definition at line 1200 of file epc-gtpc-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::GtpcDeleteBearerResponseMessage::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Reimplemented from ns3::GtpcHeader.
Definition at line 1238 of file epc-gtpc-header.cc.
References ns3::GtpcIes::DeserializeCause(), ns3::GtpcIes::DeserializeEbi(), ns3::Buffer::Iterator::GetRemainingSize(), GetSerializedSize(), m_cause, m_epsBearerIds, ns3::GtpcHeader::PreDeserialize(), and visualizer.core::start().
GetCause()
GtpcDeleteBearerResponseMessage::Cause_t ns3::GtpcDeleteBearerResponseMessage::GetCause () const
Definition at line 1267 of file epc-gtpc-header.cc.
References m_cause.
GetEpsBearerIds()
std::list< uint8_t > ns3::GtpcDeleteBearerResponseMessage::GetEpsBearerIds () const
Definition at line 1279 of file epc-gtpc-header.cc.
References m_epsBearerIds.
Referenced by ns3::EpcPgwApplication::DoRecvDeleteBearerResponse(), and ns3::EpcSgwApplication::DoRecvDeleteBearerResponse().
GetInstanceTypeId()
TypeId ns3::GtpcDeleteBearerResponseMessage::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Reimplemented from ns3::GtpcHeader.
Definition at line 1205 of file epc-gtpc-header.cc.
References GetTypeId().
GetMessageSize()
uint32_t ns3::GtpcDeleteBearerResponseMessage::GetMessageSize (void) const virtual
Reimplemented from ns3::GtpcHeader.
Definition at line 1211 of file epc-gtpc-header.cc.
References m_epsBearerIds, ns3::GtpcIes::serializedSizeCause, and ns3::GtpcIes::serializedSizeEbi.
Referenced by GetSerializedSize().
GetSerializedSize()
uint32_t ns3::GtpcDeleteBearerResponseMessage::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Reimplemented from ns3::GtpcHeader.
Definition at line 1218 of file epc-gtpc-header.cc.
References GetMessageSize(), and ns3::GtpcHeader::GetSerializedSize().
Referenced by Deserialize().
GetTypeId()
TypeId ns3::GtpcDeleteBearerResponseMessage::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 1185 of file epc-gtpc-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::GtpcDeleteBearerResponseMessage::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Reimplemented from ns3::GtpcHeader.
Definition at line 1256 of file epc-gtpc-header.cc.
References m_cause, and m_epsBearerIds.
Serialize()
void ns3::GtpcDeleteBearerResponseMessage::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Reimplemented from ns3::GtpcHeader.
Definition at line 1224 of file epc-gtpc-header.cc.
References m_cause, m_epsBearerIds, ns3::GtpcHeader::PreSerialize(), ns3::GtpcIes::SerializeCause(), ns3::GtpcIes::SerializeEbi(), and visualizer.core::start().
SetCause()
void ns3::GtpcDeleteBearerResponseMessage::SetCause (GtpcDeleteBearerResponseMessage::Cause_t cause)
Definition at line 1273 of file epc-gtpc-header.cc.
References m_cause.
SetEpsBearerIds()
void ns3::GtpcDeleteBearerResponseMessage::SetEpsBearerIds (std::list< uint8_t > epsBearerIds)
Definition at line 1285 of file epc-gtpc-header.cc.
References m_epsBearerIds.
Referenced by ns3::EpcMmeApplication::DoRecvDeleteBearerRequest(), and ns3::EpcSgwApplication::DoRecvDeleteBearerResponse().
Member Data Documentation
m_cause
Cause_t ns3::GtpcDeleteBearerResponseMessage::m_cause private
Definition at line 464 of file epc-gtpc-header.h.
Referenced by Deserialize(), GetCause(), Print(), Serialize(), and SetCause().
m_epsBearerIds
std::list<uint8_t> ns3::GtpcDeleteBearerResponseMessage::m_epsBearerIds private
Definition at line 465 of file epc-gtpc-header.h.
Referenced by Deserialize(), GetEpsBearerIds(), GetMessageSize(), Print(), Serialize(), and SetEpsBearerIds().
The documentation for this class was generated from the following files:
src/lte/model/epc-gtpc-header.h
src/lte/model/epc-gtpc-header.cc