ns-3: ns3::PrioQueueDisc Class Reference
ns3::PrioQueueDisc Class Reference
Traffic-control
#include "prio-queue-disc.h"
Public Member Functions
PrioQueueDisc ()
PrioQueueDisc constructor.
virtual ~PrioQueueDisc ()
uint16_t GetBandForPriority (uint8_t prio) const
Get the band (class) assigned to packets with specified priority.
void SetBandForPriority (uint8_t prio, uint16_t band)
Set the band (class) assigned to packets with specified priority.
Public Member Functions inherited from ns3::QueueDisc
QueueDisc (QueueDiscSizePolicy policy, QueueSizeUnit unit)
Constructor.
QueueDisc (QueueDiscSizePolicy policy=QueueDiscSizePolicy::SINGLE_INTERNAL_QUEUE)
Constructor.
virtual ~QueueDisc ()
void AddInternalQueue (Ptr< InternalQueue > queue)
Add an internal queue to the tail of the list of queues.
void AddPacketFilter (Ptr< PacketFilter > filter)
Add a packet filter to the tail of the list of filters used to classify packets.
void AddQueueDiscClass (Ptr< QueueDiscClass > qdClass)
Add a queue disc class to the tail of the list of classes.
int32_t Classify (Ptr< QueueDiscItem > item)
Classify a packet by calling the packet filters, one at a time, until either a filter able to classify the packet is found or all the filters have been processed.
Ptr< QueueDiscItem > Dequeue (void)
Extract from the queue disc the packet that has been dequeued by calling Peek, if any, or call the private DoDequeue method (which must be implemented by derived classes) to dequeue a packet, otherwise.
bool Enqueue (Ptr< QueueDiscItem > item)
Pass a packet to store to the queue discipline.
QueueSize GetCurrentSize (void)
Get the current size of the queue disc in bytes, if operating in bytes mode, or packets, otherwise.
Ptr< InternalQueue > GetInternalQueue (std::size_t i) const
Get the i-th internal queue.
QueueSize GetMaxSize (void) const
Get the maximum size of the queue disc.
uint32_t GetNBytes (void) const
Get the amount of bytes stored by the queue disc.
Ptr< NetDeviceQueueInterface > GetNetDeviceQueueInterface (void) const
std::size_t GetNInternalQueues (void) const
Get the number of internal queues.
std::size_t GetNPacketFilters (void) const
Get the number of packet filters.
uint32_t GetNPackets (void) const
Get the number of packets stored by the queue disc.
std::size_t GetNQueueDiscClasses (void) const
Get the number of queue disc classes.
Ptr< PacketFilter > GetPacketFilter (std::size_t i) const
Get the i-th packet filter.
Ptr< QueueDiscClass > GetQueueDiscClass (std::size_t i) const
Get the i-th queue disc class.
virtual uint32_t GetQuota (void) const
Get the maximum number of dequeue operations following a packet enqueue.
SendCallback GetSendCallback (void) const
const Stats & GetStats (void)
Retrieve all the collected statistics.
virtual WakeMode GetWakeMode (void) const
When setting up the wake callbacks on the netdevice queues, it is necessary to determine which queue disc (the root queue disc or one of its children) should be activated when the netdevice wakes one of its transmission queues.
Ptr< const QueueDiscItem > Peek (void)
Get a copy of the next packet the queue discipline will extract.
void Run (void)
Modelled after the Linux function __qdisc_run (net/sched/sch_generic.c) Dequeues multiple packets, until a quota is exceeded or sending a packet to the device failed.
bool SetMaxSize (QueueSize size)
Set the maximum size of the queue disc.
void SetNetDeviceQueueInterface (Ptr< NetDeviceQueueInterface > ndqi)
virtual void SetQuota (const uint32_t quota)
Set the maximum number of dequeue operations following a packet enqueue.
void SetSendCallback (SendCallback func)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::QueueDisc
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual bool CheckConfig (void)
Check whether the current configuration is correct.
virtual Ptr< QueueDiscItem > DoDequeue (void)
This function actually extracts a packet from the queue disc.
virtual bool DoEnqueue (Ptr< QueueDiscItem > item)
This function actually enqueues a packet into the queue disc.
virtual Ptr< const QueueDiscItem > DoPeek (void)
Return a copy of the next packet the queue disc will extract.
virtual void InitializeParams (void)
Initialize parameters (if any) before the first packet is enqueued.
Private Attributes
Priomap m_prio2band
Priority to band mapping.
Additional Inherited Members
Public Types inherited from ns3::QueueDisc
typedef Queue< QueueDiscItem > InternalQueue
Internal queues store QueueDiscItem objects.
typedef std::function< void(Ptr< QueueDiscItem >)> SendCallback
Callback invoked to send a packet to the receiving object when Run is called.
enum WakeMode { WAKE_ROOT = 0x00, WAKE_CHILD = 0x01 }
Used to determine whether the queue disc itself or its children must be activated when a netdevice wakes a transmission queue.
Static Public Attributes inherited from ns3::QueueDisc
static constexpr const char * CHILD_QUEUE_DISC_DROP = "(Dropped by child queue disc) "
Packet dropped by a child queue disc.
static constexpr const char * CHILD_QUEUE_DISC_MARK = "(Marked by child queue disc) "
Packet marked by a child queue disc.
static constexpr const char * INTERNAL_QUEUE_DROP = "Dropped by internal queue"
Packet dropped by an internal queue.
Protected Member Functions inherited from ns3::QueueDisc
virtual void DoDispose (void)
Dispose of the object.
void DoInitialize (void)
Check whether the configuration is correct and initialize parameters.
void DropAfterDequeue (Ptr< const QueueDiscItem > item, const char *reason)
Perform the actions required when the queue disc is notified of a packet dropped after dequeue.
void DropBeforeEnqueue (Ptr< const QueueDiscItem > item, const char *reason)
Perform the actions required when the queue disc is notified of a packet dropped before enqueue.
bool Mark (Ptr< QueueDiscItem > item, const char *reason)
Marks the given packet and, if successful, updates the counters associated with the given reason.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The Prio qdisc is a simple classful queueing discipline that contains an arbitrary number of classes of differing priority. The classes are dequeued in numerical descending order of priority. By default, three Fifo queue discs are created, unless the user provides (at least two) child queue discs.
If no packet filter is installed or able to classify a packet, then the packet is assigned a priority band based on its priority (modulo 16), which is used as an index into an array called priomap. If a packet is classified by a packet filter and the returned value is non-negative and less than the number of priority bands, then the packet is assigned the priority band corresponding to the value returned by the packet filter. Otherwise, the packet is assigned the priority band specified by the first element of the priomap array.
Definition at line 49 of file prio-queue-disc.h.
Constructor & Destructor Documentation
PrioQueueDisc()
ns3::PrioQueueDisc::PrioQueueDisc ()
PrioQueueDisc constructor.
Definition at line 71 of file prio-queue-disc.cc.
References NS_LOG_FUNCTION.
~PrioQueueDisc()
ns3::PrioQueueDisc::~PrioQueueDisc () virtual
Definition at line 77 of file prio-queue-disc.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CheckConfig()
bool ns3::PrioQueueDisc::CheckConfig (void) private virtual
Check whether the current configuration is correct.
Default objects (such as internal queues) might be created by this method to ensure the configuration is correct. This method is automatically called at simulation initialization time, and it is called before the InitializeParams () method. It is appropriate to promote parameter initialization to this method if it aids in checking for correct configuration.
See also
QueueDisc::InitializeParams
Returns
true if the configuration is correct, false otherwise
Implements ns3::QueueDisc.
Definition at line 185 of file prio-queue-disc.cc.
References ns3::QueueDisc::AddQueueDiscClass(), ns3::ObjectFactory::Create(), ns3::QueueDisc::GetNInternalQueues(), ns3::QueueDisc::GetNQueueDiscClasses(), ns3::Object::Initialize(), NS_LOG_ERROR, NS_LOG_FUNCTION, and ns3::ObjectFactory::SetTypeId().
DoDequeue()
Ptr< QueueDiscItem > ns3::PrioQueueDisc::DoDequeue (void) private virtual
This function actually extracts a packet from the queue disc.
Returns
0 if the operation was not successful; the item otherwise.
Implements ns3::QueueDisc.
Definition at line 143 of file prio-queue-disc.cc.
References ns3::QueueDisc::Dequeue(), ns3::QueueDisc::GetNPackets(), ns3::QueueDisc::GetNQueueDiscClasses(), ns3::QueueDisc::GetQueueDiscClass(), NS_LOG_FUNCTION, and NS_LOG_LOGIC().
DoEnqueue()
bool ns3::PrioQueueDisc::DoEnqueue (Ptr< QueueDiscItem > item) private virtual
This function actually enqueues a packet into the queue disc.
Parameters
item item to enqueue
Returns
True if the operation was successful; false otherwise
Implements ns3::QueueDisc.
Definition at line 103 of file prio-queue-disc.cc.
References ns3::QueueDisc::Classify(), ns3::QueueDisc::GetNPackets(), ns3::QueueDisc::GetNQueueDiscClasses(), ns3::SocketPriorityTag::GetPriority(), ns3::QueueDisc::GetQueueDiscClass(), m_prio2band, NS_ASSERT_MSG(), NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC(), and ns3::PacketFilter::PF_NO_MATCH.
DoPeek()
Ptr< const QueueDiscItem > ns3::PrioQueueDisc::DoPeek (void) private virtual
Return a copy of the next packet the queue disc will extract.
The implementation of this method is based on the qdisc_peek_dequeued function of the Linux kernel, which dequeues a packet and retains it in the queue disc as a requeued packet. The packet is not traced as requeued, nor is the total count of requeued packets increased. The packet is still considered to be part of the queue disc and the dequeue trace is fired when Dequeue is called and the packet is actually extracted from the queue disc.
This approach is especially recommended for queue discs for which it is not obvious what is the next packet that will be dequeued (e.g., queue discs having multiple internal queues or child queue discs or queue discs that drop packets after dequeue). Subclasses can however provide their own implementation of this method that overrides the default one.
Returns
0 if the operation was not successful; the packet otherwise.
Reimplemented from ns3::QueueDisc.
Definition at line 164 of file prio-queue-disc.cc.
References ns3::QueueDisc::GetNPackets(), ns3::QueueDisc::GetNQueueDiscClasses(), ns3::QueueDisc::GetQueueDiscClass(), NS_LOG_FUNCTION, NS_LOG_LOGIC(), and ns3::QueueDisc::Peek().
GetBandForPriority()
uint16_t ns3::PrioQueueDisc::GetBandForPriority (uint8_t prio) const
Get the band (class) assigned to packets with specified priority.
Parameters
prio the priority of packets (a value between 0 and 15).
Returns
the band assigned to packets.
Definition at line 93 of file prio-queue-disc.cc.
References m_prio2band, NS_ASSERT_MSG(), and NS_LOG_FUNCTION.
Referenced by PrioQueueDiscTestCase::DoRun().
GetTypeId()
TypeId ns3::PrioQueueDisc::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 57 of file prio-queue-disc.cc.
References m_prio2band, ns3::MakePriomapChecker(), and ns3::TypeId::SetParent().
InitializeParams()
void ns3::PrioQueueDisc::InitializeParams (void) private virtual
Initialize parameters (if any) before the first packet is enqueued.
This method is automatically called at simulation initialization time, after the CheckConfig() method has been called.
See also
QueueDisc::CheckConfig
Implements ns3::QueueDisc.
Definition at line 219 of file prio-queue-disc.cc.
References NS_LOG_FUNCTION.
SetBandForPriority()
void ns3::PrioQueueDisc::SetBandForPriority (uint8_t prio, uint16_t band)
Set the band (class) assigned to packets with specified priority.
Parameters
prio the priority of packets (a value between 0 and 15).
band the band assigned to packets.
Definition at line 83 of file prio-queue-disc.cc.
References m_prio2band, NS_ASSERT_MSG(), and NS_LOG_FUNCTION.
Member Data Documentation
m_prio2band
Priomap ns3::PrioQueueDisc::m_prio2band private
Priority to band mapping.
Definition at line 86 of file prio-queue-disc.h.
Referenced by DoEnqueue(), GetBandForPriority(), GetTypeId(), and SetBandForPriority().
The documentation for this class was generated from the following files:
src/traffic-control/model/prio-queue-disc.h
src/traffic-control/model/prio-queue-disc.cc