ns-3: Ipv6RipngCountToInfinityTest Class Reference
Ipv6RipngCountToInfinityTest Class Reference
Internet » internet module tests | Test suites
IPv6 RIPng count to infinity Test.
Public Member Functions
Ipv6RipngCountToInfinityTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
void ReceivePkt (Ptr< Socket > socket)
Receive data.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void DoSendData (Ptr< Socket > socket, std::string to)
Send data.
void SendData (Ptr< Socket > socket, std::string to)
Send data.
Private Attributes
Ptr< Packet > m_receivedPacket
Received packet.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
IPv6 RIPng count to infinity Test.
Definition at line 278 of file ipv6-ripng-test.cc.
Constructor & Destructor Documentation
Ipv6RipngCountToInfinityTest()
Ipv6RipngCountToInfinityTest::Ipv6RipngCountToInfinityTest ()
Definition at line 306 of file ipv6-ripng-test.cc.
Member Function Documentation
DoRun()
void Ipv6RipngCountToInfinityTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 341 of file ipv6-ripng-test.cc.
References ns3::NetDeviceContainer::Add(), ns3::Node::AddDevice(), ns3::Ipv6AddressHelper::Assign(), ns3::Ipv6AddressHelper::AssignWithoutAddress(), ns3::SocketFactory::CreateSocket(), ns3::Object::GetObject(), ns3::Packet::GetSize(), ns3::InternetStackHelper::Install(), m_receivedPacket, ns3::MakeCallback(), first::nodes, NS_TEST_EXPECT_MSG_EQ, ReceivePkt(), SendData(), ns3::SimpleNetDevice::SetAddress(), ns3::Socket::SetAllowBroadcast(), ns3::Ipv6AddressHelper::SetBase(), ns3::SimpleNetDevice::SetChannel(), ns3::Ipv6InterfaceContainer::SetDefaultRouteInAllNodes(), ns3::Ipv6InterfaceContainer::SetForwarding(), ns3::RipNgHelper::SetInterfaceMetric(), and ns3::InternetStackHelper::SetRoutingHelper().
DoSendData()
void Ipv6RipngCountToInfinityTest::DoSendData (Ptr< Socket > socket, std::string to) private
Send data.
Parameters
socket The sending socket.
to Destination address.
Definition at line 323 of file ipv6-ripng-test.cc.
References NS_TEST_EXPECT_MSG_EQ, and ns3::Socket::SendTo().
Referenced by SendData().
ReceivePkt()
void Ipv6RipngCountToInfinityTest::ReceivePkt (Ptr< Socket > socket)
Receive data.
Parameters
socket The receiving socket.
Definition at line 311 of file ipv6-ripng-test.cc.
References ns3::Socket::GetRxAvailable(), ns3::Packet::GetSize(), m_receivedPacket, max, NS_ASSERT, and ns3::Socket::Recv().
Referenced by DoRun().
SendData()
void Ipv6RipngCountToInfinityTest::SendData (Ptr< Socket > socket, std::string to) private
Send data.
Parameters
socket The sending socket.
to Destination address.
Definition at line 331 of file ipv6-ripng-test.cc.
References DoSendData(), ns3::Node::GetId(), ns3::Socket::GetNode(), m_receivedPacket, and ns3::Seconds().
Referenced by DoRun().
Member Data Documentation
m_receivedPacket
Ptr<Packet> Ipv6RipngCountToInfinityTest::m_receivedPacket private
Received packet.
Definition at line 280 of file ipv6-ripng-test.cc.
Referenced by DoRun(), ReceivePkt(), and SendData().
The documentation for this class was generated from the following file:
src/internet/test/ipv6-ripng-test.cc