ns-3: LteStrictFrTestCase Class Reference
LteStrictFrTestCase Class Reference
LTE Models » lte module tests | Test suites
Test stric frequency reuse algorithm. Test fails if the muted frequencies are being used.
#include "lte-test-frequency-reuse.h"
Public Member Functions
LteStrictFrTestCase (std::string name, uint32_t userNum, std::string schedulerType, uint16_t dlBandwidth, uint16_t ulBandwidth, uint16_t dlCommonSubBandwidth, uint8_t dlEdgeSubBandOffset, uint16_t dlEdgeSubBandwidth, uint16_t ulCommonSubBandwidth, uint8_t ulEdgeSubBandOffset, uint16_t ulEdgeSubBandwidth, std::vector< bool > availableDlRb, std::vector< bool > availableUlRb)
Constructor.
virtual ~LteStrictFrTestCase ()
Public Member Functions inherited from LteFrTestCase
LteFrTestCase (std::string name, uint32_t userNum, uint16_t dlBandwidth, uint16_t ulBandwidth, std::vector< bool > availableDlRb, std::vector< bool > availableUlRb)
Constructor.
virtual ~LteFrTestCase ()
void DlDataRxStart (Ptr< const SpectrumValue > spectrumValue)
DL data receive start function.
void UlDataRxStart (Ptr< const SpectrumValue > spectrumValue)
UL data receive start function.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
uint16_t m_dlCommonSubBandwidth
DL common subbandwidth.
uint8_t m_dlEdgeSubBandOffset
DL edge subband offset.
uint16_t m_dlEdgeSubBandwidth
DL edge subbandwidth.
std::string m_schedulerType
scheduler type
uint16_t m_ulCommonSubBandwidth
UL common subbandwidth.
uint8_t m_ulEdgeSubBandOffset
UL edge subband offset.
uint16_t m_ulEdgeSubBandwidth
UL edge subbandwidth.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Protected Attributes inherited from LteFrTestCase
std::vector< bool > m_availableDlRb
the available DL for each RB
std::vector< bool > m_availableUlRb
the available UL for each RB
uint16_t m_dlBandwidth
the DL bandwidth
uint16_t m_ulBandwidth
the UL bandwidth
bool m_usedMutedDlRbg
used muted DL RBG?
bool m_usedMutedUlRbg
used muted UL RBG?
uint32_t m_userNum
the number of UE nodes
Detailed Description
Test stric frequency reuse algorithm. Test fails if the muted frequencies are being used.
Definition at line 149 of file lte-test-frequency-reuse.h.
Constructor & Destructor Documentation
LteStrictFrTestCase()
LteStrictFrTestCase::LteStrictFrTestCase (std::string name, uint32_t userNum, std::string schedulerType, uint16_t dlBandwidth, uint16_t ulBandwidth, uint16_t dlCommonSubBandwidth, uint8_t dlEdgeSubBandOffset, uint16_t dlEdgeSubBandwidth, uint16_t ulCommonSubBandwidth, uint8_t ulEdgeSubBandOffset, uint16_t ulEdgeSubBandwidth, std::vector< bool > availableDlRb, std::vector< bool > availableUlRb)
Constructor.
Parameters
name the reference name
userNum the number of UE nodes
schedulerType the scheduler type
dlBandwidth the DL bandwidth
ulBandwidth the UL bandwidth
dlCommonSubBandwidth DL common bandwidth
dlEdgeSubBandOffset DL edge subband offset
dlEdgeSubBandwidth DL edge subbandwidth
ulCommonSubBandwidth UL common subbandwidth
ulEdgeSubBandOffset UL subband offset
ulEdgeSubBandwidth UL subbandwidth
availableDlRb the available DL per RB
availableUlRb the avaialbel UL per RB
Definition at line 358 of file lte-test-frequency-reuse.cc.
References NS_LOG_INFO.
~LteStrictFrTestCase()
LteStrictFrTestCase::~LteStrictFrTestCase () virtual
Definition at line 376 of file lte-test-frequency-reuse.cc.
Member Function Documentation
DoRun()
void LteStrictFrTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Simulation Topology
Reimplemented from LteFrTestCase.
Definition at line 381 of file lte-test-frequency-reuse.cc.
References ns3::LteHelper::ActivateDataRadioBearer(), ns3::LteHelper::Attach(), ns3::NodeContainer::Create(), DlDataRxStartNofitication(), ns3::GbrQosInformation::gbrDl, ns3::GbrQosInformation::gbrUl, ns3::NetDeviceContainer::Get(), ns3::LteSpectrumPhy::GetChannel(), ns3::LteEnbNetDevice::GetDlEarfcn(), ns3::Object::GetObject(), ns3::LteEnbNetDevice::GetUlEarfcn(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), LteFrTestCase::m_dlBandwidth, m_dlCommonSubBandwidth, m_dlEdgeSubBandOffset, m_dlEdgeSubBandwidth, m_schedulerType, LteFrTestCase::m_ulBandwidth, m_ulCommonSubBandwidth, m_ulEdgeSubBandOffset, m_ulEdgeSubBandwidth, LteFrTestCase::m_usedMutedDlRbg, LteFrTestCase::m_usedMutedUlRbg, LteFrTestCase::m_userNum, ns3::MakeBoundCallback(), ns3::GbrQosInformation::mbrDl, ns3::GbrQosInformation::mbrUl, third::mobility, NS_LOG_DEBUG, NS_TEST_ASSERT_MSG_EQ, ns3::Config::Reset(), ns3::Seconds(), ns3::Config::SetDefault(), ns3::LteHelper::SetFfrAlgorithmAttribute(), ns3::LteHelper::SetFfrAlgorithmType(), ns3::LteSimpleSpectrumPhy::SetRxSpectrumModel(), ns3::LteHelper::SetSchedulerType(), ns3::ObjectBase::TraceConnectWithoutContext(), and UlDataRxStartNofitication().
Member Data Documentation
m_dlCommonSubBandwidth
uint16_t LteStrictFrTestCase::m_dlCommonSubBandwidth private
DL common subbandwidth.
Definition at line 182 of file lte-test-frequency-reuse.h.
Referenced by DoRun().
m_dlEdgeSubBandOffset
uint8_t LteStrictFrTestCase::m_dlEdgeSubBandOffset private
DL edge subband offset.
Definition at line 183 of file lte-test-frequency-reuse.h.
Referenced by DoRun().
m_dlEdgeSubBandwidth
uint16_t LteStrictFrTestCase::m_dlEdgeSubBandwidth private
DL edge subbandwidth.
Definition at line 184 of file lte-test-frequency-reuse.h.
Referenced by DoRun().
m_schedulerType
std::string LteStrictFrTestCase::m_schedulerType private
scheduler type
Definition at line 180 of file lte-test-frequency-reuse.h.
Referenced by DoRun().
m_ulCommonSubBandwidth
uint16_t LteStrictFrTestCase::m_ulCommonSubBandwidth private
UL common subbandwidth.
Definition at line 186 of file lte-test-frequency-reuse.h.
Referenced by DoRun().
m_ulEdgeSubBandOffset
uint8_t LteStrictFrTestCase::m_ulEdgeSubBandOffset private
UL edge subband offset.
Definition at line 187 of file lte-test-frequency-reuse.h.
Referenced by DoRun().
m_ulEdgeSubBandwidth
uint16_t LteStrictFrTestCase::m_ulEdgeSubBandwidth private
UL edge subbandwidth.
Definition at line 188 of file lte-test-frequency-reuse.h.
Referenced by DoRun().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-frequency-reuse.h
src/lte/test/lte-test-frequency-reuse.cc