ns-3: ns3::PcapHelperForIpv6 Class Reference
ns3::PcapHelperForIpv6 Class Reference abstract
Internet » IPv6 Helper classes
Base class providing common user-level pcap operations for helpers representing IPv6 protocols .
#include "internet-trace-helper.h"
Public Member Functions
PcapHelperForIpv6 ()
Construct a PcapHelperForIpv6.
virtual ~PcapHelperForIpv6 ()
Destroy a PcapHelperForIpv6.
void EnablePcapIpv6 (std::string prefix, Ipv6InterfaceContainer c)
Enable pcap output on each Ipv6 and interface pair in the container.
void EnablePcapIpv6 (std::string prefix, NodeContainer n)
Enable pcap output on all Ipv6 and interface pairs existing in the nodes provided in the container.
void EnablePcapIpv6 (std::string prefix, Ptr< Ipv6 > ipv6, uint32_t interface, bool explicitFilename=false)
Enable pcap output the indicated Ipv6 and interface pair.
void EnablePcapIpv6 (std::string prefix, std::string ipv6Name, uint32_t interface, bool explicitFilename=false)
Enable pcap output the indicated Ipv6 and interface pair using a Ptr<Ipv6> previously named using the ns-3 object name service.
void EnablePcapIpv6 (std::string prefix, uint32_t nodeid, uint32_t interface, bool explicitFilename)
Enable pcap output on the Ipv6 and interface pair specified by a global node-id (of a previously created node) and interface.
void EnablePcapIpv6All (std::string prefix)
Enable pcap output on all Ipv6 and interface pairs existing in the set of all nodes created in the simulation.
virtual void EnablePcapIpv6Internal (std::string prefix, Ptr< Ipv6 > ipv6, uint32_t interface, bool explicitFilename)=0
Enable pcap output the indicated Ipv6 and interface pair.
Detailed Description
Base class providing common user-level pcap operations for helpers representing IPv6 protocols .
Definition at line 397 of file internet-trace-helper.h.
Constructor & Destructor Documentation
PcapHelperForIpv6()
ns3::PcapHelperForIpv6::PcapHelperForIpv6 () inline
Construct a PcapHelperForIpv6.
Definition at line 403 of file internet-trace-helper.h.
~PcapHelperForIpv6()
virtual ns3::PcapHelperForIpv6::~PcapHelperForIpv6 () inline virtual
Destroy a PcapHelperForIpv6.
Definition at line 408 of file internet-trace-helper.h.
Member Function Documentation
EnablePcapIpv6() [1/5]
void ns3::PcapHelperForIpv6::EnablePcapIpv6 (std::string prefix, Ipv6InterfaceContainer c)
Enable pcap output on each Ipv6 and interface pair in the container.
Parameters
prefix Filename prefix to use for pcap files.
c Ipv6InterfaceContainer of Ipv6 and interface pairs
Definition at line 315 of file internet-trace-helper.cc.
References ns3::Ipv6InterfaceContainer::Begin(), EnablePcapIpv6(), and ns3::Ipv6InterfaceContainer::End().
EnablePcapIpv6() [2/5]
void ns3::PcapHelperForIpv6::EnablePcapIpv6 (std::string prefix, NodeContainer n)
Enable pcap output on all Ipv6 and interface pairs existing in the nodes provided in the container.
Parameters
prefix Filename prefix to use for pcap files.
n container of nodes.
Definition at line 325 of file internet-trace-helper.cc.
References EnablePcapIpv6(), ns3::Object::GetObject(), and sample-rng-plot::n.
EnablePcapIpv6() [3/5]
void ns3::PcapHelperForIpv6::EnablePcapIpv6 (std::string prefix, Ptr< Ipv6 > ipv6, uint32_t interface, bool explicitFilename = false)
Enable pcap output the indicated Ipv6 and interface pair.
Parameters
prefix Filename prefix to use for pcap files.
ipv6 Ptr<Ipv6> on which you want to enable tracing.
interface Interface on ipv6 on which you want to enable tracing.
explicitFilename Treat the prefix as an explicit filename if true.
Definition at line 302 of file internet-trace-helper.cc.
References EnablePcapIpv6Internal().
Referenced by EnablePcapIpv6(), and EnablePcapIpv6All().
EnablePcapIpv6() [4/5]
void ns3::PcapHelperForIpv6::EnablePcapIpv6 (std::string prefix, std::string ipv6Name, uint32_t interface, bool explicitFilename = false)
Enable pcap output the indicated Ipv6 and interface pair using a Ptr<Ipv6> previously named using the ns-3 object name service.
Parameters
prefix filename prefix to use for pcap files.
ipv6Name Name of the Ptr<Ipv6> on which you want to enable tracing.
interface Interface on ipv6 on which you want to enable tracing.
explicitFilename Treat the prefix as an explicit filename if true.
Definition at line 308 of file internet-trace-helper.cc.
References EnablePcapIpv6().
EnablePcapIpv6() [5/5]
void ns3::PcapHelperForIpv6::EnablePcapIpv6 (std::string prefix, uint32_t nodeid, uint32_t interface, bool explicitFilename)
Enable pcap output on the Ipv6 and interface pair specified by a global node-id (of a previously created node) and interface.
Since there can be only one Ipv6 aggregated to a node, the node-id unambiguously determines the Ipv6.
Parameters
prefix Filename prefix to use for pcap files.
nodeid The node identifier/number of the node on which to enable tracing.
interface Interface on ipv6 on which you want to enable tracing.
explicitFilename Treat the prefix as an explicit filename if true
Definition at line 348 of file internet-trace-helper.cc.
References EnablePcapIpv6(), ns3::NodeContainer::GetGlobal(), ns3::Node::GetId(), ns3::Object::GetObject(), and sample-rng-plot::n.
EnablePcapIpv6All()
void ns3::PcapHelperForIpv6::EnablePcapIpv6All (std::string prefix)
Enable pcap output on all Ipv6 and interface pairs existing in the set of all nodes created in the simulation.
Parameters
prefix Filename prefix to use for pcap files.
Definition at line 342 of file internet-trace-helper.cc.
References EnablePcapIpv6(), and ns3::NodeContainer::GetGlobal().
EnablePcapIpv6Internal()
virtual void ns3::PcapHelperForIpv6::EnablePcapIpv6Internal (std::string prefix, Ptr< Ipv6 > ipv6, uint32_t interface, bool explicitFilename) pure virtual
Enable pcap output the indicated Ipv6 and interface pair.
Parameters
prefix Filename prefix to use for pcap files.
ipv6 Ptr<Ipv6> on which you want to enable tracing.
interface Interface on ipv6 on which you want to enable tracing.
explicitFilename Treat the prefix as an explicit filename if true.
Implemented in ns3::InternetStackHelper.
Referenced by EnablePcapIpv6().
The documentation for this class was generated from the following files:
src/internet/helper/internet-trace-helper.h
src/internet/helper/internet-trace-helper.cc