ns-3: ns3::WifiSpectrumPhyInterface Class Reference
ns3::WifiSpectrumPhyInterface Class Reference
Wifi Models
#include "wifi-spectrum-phy-interface.h"
Public Member Functions
WifiSpectrumPhyInterface ()
Ptr< NetDevice > GetDevice () const
Get the associated NetDevice instance.
Ptr< MobilityModel > GetMobility ()
Get the associated MobilityModel instance.
Ptr< AntennaModel > GetRxAntenna ()
Get the AntennaModel used by the NetDevice for reception.
Ptr< const SpectrumModel > GetRxSpectrumModel () const
void SetChannel (const Ptr< SpectrumChannel > c)
Set the channel attached to this device.
void SetDevice (const Ptr< NetDevice > d)
Set the associated NetDevice instance.
void SetMobility (const Ptr< MobilityModel > m)
Set the mobility model associated with this device.
void SetSpectrumWifiPhy (const Ptr< SpectrumWifiPhy > phy)
Connect SpectrumWifiPhy object.
void StartRx (Ptr< SpectrumSignalParameters > params)
Notify the SpectrumPhy instance of an incoming signal.
Public Member Functions inherited from ns3::SpectrumPhy
SpectrumPhy ()
virtual ~SpectrumPhy ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::SpectrumPhy
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual void DoDispose (void)
Destructor implementation.
Private Attributes
Ptr< SpectrumChannel > m_channel
spectrum channel
Ptr< NetDevice > m_netDevice
the device
Ptr< SpectrumWifiPhy > m_spectrumWifiPhy
spectrum PHY
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class is an adaptor between class SpectrumWifiPhy (which inherits from WifiPhy) and class SpectrumChannel (which expects objects derived from class SpectrumPhy to be connected to it).
The adaptor is used only in the receive direction; in the transmit direction, the class SpectrumWifiPhy constructs signal parameters and directly accesses the SpectrumChannel
Definition at line 41 of file wifi-spectrum-phy-interface.h.
Constructor & Destructor Documentation
WifiSpectrumPhyInterface()
ns3::WifiSpectrumPhyInterface::WifiSpectrumPhyInterface ()
Definition at line 43 of file wifi-spectrum-phy-interface.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::WifiSpectrumPhyInterface::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 49 of file wifi-spectrum-phy-interface.cc.
References m_channel, m_netDevice, m_spectrumWifiPhy, and NS_LOG_FUNCTION.
GetDevice()
Ptr< NetDevice > ns3::WifiSpectrumPhyInterface::GetDevice () const virtual
Get the associated NetDevice instance.
Returns
a Ptr to the associated NetDevice instance
Implements ns3::SpectrumPhy.
Definition at line 63 of file wifi-spectrum-phy-interface.cc.
References m_netDevice.
GetMobility()
Ptr< MobilityModel > ns3::WifiSpectrumPhyInterface::GetMobility () virtual
Get the associated MobilityModel instance.
Returns
a Ptr to the associated MobilityModel instance
Implements ns3::SpectrumPhy.
Definition at line 69 of file wifi-spectrum-phy-interface.cc.
References ns3::WifiPhy::GetMobility(), and m_spectrumWifiPhy.
GetRxAntenna()
Ptr< AntennaModel > ns3::WifiSpectrumPhyInterface::GetRxAntenna () virtual
Get the AntennaModel used by the NetDevice for reception.
Returns
a Ptr to the AntennaModel used by the NetDevice for reception
Implements ns3::SpectrumPhy.
Definition at line 100 of file wifi-spectrum-phy-interface.cc.
References ns3::SpectrumWifiPhy::GetRxAntenna(), m_spectrumWifiPhy, and NS_LOG_FUNCTION.
GetRxSpectrumModel()
Ptr< const SpectrumModel > ns3::WifiSpectrumPhyInterface::GetRxSpectrumModel () const virtual
Returns
returns the SpectrumModel that this SpectrumPhy expects to be used for all SpectrumValues that are passed to StartRx. If 0 is returned, it means that any model will be accepted.
Implements ns3::SpectrumPhy.
Definition at line 94 of file wifi-spectrum-phy-interface.cc.
References ns3::SpectrumWifiPhy::GetRxSpectrumModel(), and m_spectrumWifiPhy.
GetTypeId()
TypeId ns3::WifiSpectrumPhyInterface::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 35 of file wifi-spectrum-phy-interface.cc.
References ns3::TypeId::SetParent().
SetChannel()
void ns3::WifiSpectrumPhyInterface::SetChannel (const Ptr< SpectrumChannel > c) virtual
Set the channel attached to this device.
Parameters
c the channel
Implements ns3::SpectrumPhy.
Definition at line 87 of file wifi-spectrum-phy-interface.cc.
References m_channel, and NS_LOG_FUNCTION.
SetDevice()
void ns3::WifiSpectrumPhyInterface::SetDevice (const Ptr< NetDevice > d) virtual
Set the associated NetDevice instance.
Parameters
d the NetDevice instance
Implements ns3::SpectrumPhy.
Definition at line 75 of file wifi-spectrum-phy-interface.cc.
References m_netDevice.
SetMobility()
void ns3::WifiSpectrumPhyInterface::SetMobility (const Ptr< MobilityModel > m) virtual
Set the mobility model associated with this device.
Parameters
m the mobility model
Implements ns3::SpectrumPhy.
Definition at line 81 of file wifi-spectrum-phy-interface.cc.
References m_spectrumWifiPhy, and ns3::WifiPhy::SetMobility().
SetSpectrumWifiPhy()
void ns3::WifiSpectrumPhyInterface::SetSpectrumWifiPhy (const Ptr< SpectrumWifiPhy > phy)
Connect SpectrumWifiPhy object.
Parameters
phy SpectrumWifiPhy object to be connected to this object
Definition at line 57 of file wifi-spectrum-phy-interface.cc.
References m_spectrumWifiPhy.
StartRx()
void ns3::WifiSpectrumPhyInterface::StartRx (Ptr< SpectrumSignalParameters > params) virtual
Notify the SpectrumPhy instance of an incoming signal.
Parameters
params the parameters of the signals being received
Implements ns3::SpectrumPhy.
Definition at line 107 of file wifi-spectrum-phy-interface.cc.
References m_spectrumWifiPhy, aloha::params, and ns3::SpectrumWifiPhy::StartRx().
Member Data Documentation
m_channel
Ptr<SpectrumChannel> ns3::WifiSpectrumPhyInterface::m_channel private
spectrum channel
Definition at line 71 of file wifi-spectrum-phy-interface.h.
Referenced by DoDispose(), and SetChannel().
m_netDevice
Ptr<NetDevice> ns3::WifiSpectrumPhyInterface::m_netDevice private
the device
Definition at line 70 of file wifi-spectrum-phy-interface.h.
Referenced by DoDispose(), GetDevice(), and SetDevice().
m_spectrumWifiPhy
Ptr<SpectrumWifiPhy> ns3::WifiSpectrumPhyInterface::m_spectrumWifiPhy private
spectrum PHY
Definition at line 69 of file wifi-spectrum-phy-interface.h.
Referenced by DoDispose(), GetMobility(), GetRxAntenna(), GetRxSpectrumModel(), SetMobility(), SetSpectrumWifiPhy(), and StartRx().
The documentation for this class was generated from the following files:
src/wifi/model/wifi-spectrum-phy-interface.h
src/wifi/model/wifi-spectrum-phy-interface.cc