ns-3: ns3::AttributeDefaultIterator Class Reference
ns3::AttributeDefaultIterator Class Reference abstract
Configuration Store/Load
Iterator to iterate on the default values of attributes of an ns3::Object.
#include "attribute-default-iterator.h"
Public Member Functions
virtual ~AttributeDefaultIterator ()=0
void Iterate (void)
This function will go through all the TypeIds and get only the attributes which are explicit values (not vectors or pointer or arrays) and apply StartVisitTypeId and VisitAttribute on the attributes in one TypeId.
Private Member Functions
virtual void DoVisitAttribute (std::string name, std::string defaultValue)
This method is just an interface and needs to be implemented.
virtual void EndVisitTypeId (void)
Just an interface that needs to be implemented.
virtual void StartVisitTypeId (std::string name)
Just an interface that needs to be implemented.
virtual void VisitAttribute (TypeId tid, std::string name, std::string defaultValue, uint32_t index)
This method can be implemented, otherwise, it will call DoVisitAttribute.
Detailed Description
Iterator to iterate on the default values of attributes of an ns3::Object.
Definition at line 33 of file attribute-default-iterator.h.
Constructor & Destructor Documentation
~AttributeDefaultIterator()
ns3::AttributeDefaultIterator::~AttributeDefaultIterator () pure virtual
Definition at line 31 of file attribute-default-iterator.cc.
Member Function Documentation
DoVisitAttribute()
void ns3::AttributeDefaultIterator::DoVisitAttribute (std::string name, std::string defaultValue) private virtual
This method is just an interface and needs to be implemented.
Definition at line 117 of file attribute-default-iterator.cc.
Referenced by VisitAttribute().
EndVisitTypeId()
void ns3::AttributeDefaultIterator::EndVisitTypeId (void) private virtual
Just an interface that needs to be implemented.
Reimplemented in ns3::ModelTypeidCreator.
Definition at line 112 of file attribute-default-iterator.cc.
Referenced by Iterate().
Iterate()
void ns3::AttributeDefaultIterator::Iterate (void)
This function will go through all the TypeIds and get only the attributes which are explicit values (not vectors or pointer or arrays) and apply StartVisitTypeId and VisitAttribute on the attributes in one TypeId.
At the end of each TypeId EndVisitTypeId is called.
Definition at line 35 of file attribute-default-iterator.cc.
References ns3::TypeId::AttributeInformation::accessor, ns3::TypeId::ATTR_CONSTRUCT, ns3::TypeId::AttributeInformation::checker, EndVisitTypeId(), ns3::TypeId::AttributeInformation::flags, ns3::TypeId::GetAttribute(), ns3::TypeId::GetAttributeN(), ns3::TypeId::GetName(), ns3::TypeId::GetRegistered(), ns3::TypeId::GetRegisteredN(), ns3::TypeId::AttributeInformation::initialValue, ns3::TypeId::MustHideFromDocumentation(), ns3::TypeId::AttributeInformation::name, StartVisitTypeId(), and VisitAttribute().
Referenced by ns3::ModelTypeidCreator::Build().
StartVisitTypeId()
void ns3::AttributeDefaultIterator::StartVisitTypeId (std::string name) private virtual
Just an interface that needs to be implemented.
Reimplemented in ns3::ModelTypeidCreator.
Definition at line 108 of file attribute-default-iterator.cc.
Referenced by Iterate().
VisitAttribute()
void ns3::AttributeDefaultIterator::VisitAttribute (TypeId tid, std::string name, std::string defaultValue, uint32_t index) private virtual
This method can be implemented, otherwise, it will call DoVisitAttribute.
Reimplemented in ns3::ModelTypeidCreator.
Definition at line 122 of file attribute-default-iterator.cc.
References DoVisitAttribute().
Referenced by Iterate().
The documentation for this class was generated from the following files:
src/config-store/model/attribute-default-iterator.h
src/config-store/model/attribute-default-iterator.cc