ns-3: ns3::LteAsSapUser Class Reference
ns3::LteAsSapUser Class Reference abstract
This class implements the Access Stratum (AS) Service Access Point (SAP), i.e., the interface between the EpcUeNas and the LteUeRrc In particular, this class implements the User part of the SAP, i.e., the methods exported by the EpcUeNas and called by the LteUeRrc.
#include "lte-as-sap.h"
Public Member Functions
virtual ~LteAsSapUser ()
virtual void NotifyConnectionFailed ()=0
Notify the NAS that RRC Connection Establishment failed.
virtual void NotifyConnectionReleased ()=0
Notify the NAS that RRC Connection was released.
virtual void NotifyConnectionSuccessful ()=0
Notify the NAS that RRC Connection Establishment was successful.
virtual void RecvData (Ptr< Packet > packet)=0
receive a data packet
Detailed Description
This class implements the Access Stratum (AS) Service Access Point (SAP), i.e., the interface between the EpcUeNas and the LteUeRrc In particular, this class implements the User part of the SAP, i.e., the methods exported by the EpcUeNas and called by the LteUeRrc.
Definition at line 105 of file lte-as-sap.h.
Constructor & Destructor Documentation
~LteAsSapUser()
ns3::LteAsSapUser::~LteAsSapUser () virtual
Definition at line 29 of file lte-as-sap.cc.
Member Function Documentation
NotifyConnectionFailed()
virtual void ns3::LteAsSapUser::NotifyConnectionFailed () pure virtual
Notify the NAS that RRC Connection Establishment failed.
Implemented in ns3::MemberLteAsSapUser< C >.
Referenced by ns3::LteUeRrc::ConnectionTimeout(), ns3::LteUeRrc::DoNotifyRandomAccessFailed(), and ns3::LteUeRrc::DoRecvRrcConnectionReject().
NotifyConnectionReleased()
virtual void ns3::LteAsSapUser::NotifyConnectionReleased () pure virtual
Notify the NAS that RRC Connection was released.
Implemented in ns3::MemberLteAsSapUser< C >.
Referenced by ns3::LteUeRrc::ConnectionTimeout(), ns3::LteUeRrc::DoRecvRrcConnectionReestablishmentReject(), and ns3::LteUeRrc::RadioLinkFailureDetected().
NotifyConnectionSuccessful()
virtual void ns3::LteAsSapUser::NotifyConnectionSuccessful () pure virtual
Notify the NAS that RRC Connection Establishment was successful.
Implemented in ns3::MemberLteAsSapUser< C >.
Referenced by ns3::LteUeRrc::DoRecvRrcConnectionSetup().
RecvData()
virtual void ns3::LteAsSapUser::RecvData (Ptr< Packet > packet) pure virtual
receive a data packet
Parameters
packet the packet
Implemented in ns3::MemberLteAsSapUser< C >.
Referenced by ns3::LteUeRrc::DoReceivePdcpSdu().
The documentation for this class was generated from the following files:
src/lte/model/lte-as-sap.h
src/lte/model/lte-as-sap.cc