ns-3: ns3::DataCollectionObject Class Reference
ns3::DataCollectionObject Class Reference
Statistics » Data Aggregators
#include "data-collection-object.h"
Public Member Functions
DataCollectionObject ()
virtual ~DataCollectionObject ()
void Disable (void)
Unset the status of an individual object.
void Enable (void)
Set the status of an individual object.
std::string GetName (void) const
Get the object's name.
virtual bool IsEnabled (void) const
Check the status of an individual object.
void SetName (std::string name)
Set the object's name. All spaces are replaced by underscores.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Attributes
bool m_enabled
Object's activation state.
std::string m_name
Name of the object within the data collection framework.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Base class for data collection framework objects.
All data collection objects have 1) a string name, and 2) enabled or disabled status.
Definition at line 37 of file data-collection-object.h.
Constructor & Destructor Documentation
DataCollectionObject()
ns3::DataCollectionObject::DataCollectionObject ()
Definition at line 50 of file data-collection-object.cc.
~DataCollectionObject()
ns3::DataCollectionObject::~DataCollectionObject () virtual
Definition at line 54 of file data-collection-object.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Disable()
void ns3::DataCollectionObject::Disable (void)
Unset the status of an individual object.
Definition at line 91 of file data-collection-object.cc.
References m_enabled, and NS_LOG_FUNCTION.
Referenced by anonymous_namespace{gnuplot-aggregator-example.cc}::Create2dPlot(), anonymous_namespace{file-aggregator-example.cc}::CreateCommaSeparatedFile(), anonymous_namespace{file-aggregator-example.cc}::CreateFormattedFile(), and anonymous_namespace{file-aggregator-example.cc}::CreateSpaceSeparatedFile().
Enable()
void ns3::DataCollectionObject::Enable (void)
Set the status of an individual object.
Definition at line 84 of file data-collection-object.cc.
References m_enabled, and NS_LOG_FUNCTION.
Referenced by anonymous_namespace{gnuplot-aggregator-example.cc}::Create2dPlot(), anonymous_namespace{file-aggregator-example.cc}::CreateCommaSeparatedFile(), anonymous_namespace{file-aggregator-example.cc}::CreateFormattedFile(), and anonymous_namespace{file-aggregator-example.cc}::CreateSpaceSeparatedFile().
GetName()
std::string ns3::DataCollectionObject::GetName (void) const
Get the object's name.
Definition at line 66 of file data-collection-object.cc.
References m_name.
Referenced by ProbeTestCase1::DoRun(), and GetTypeId().
GetTypeId()
TypeId ns3::DataCollectionObject::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 34 of file data-collection-object.cc.
References GetName(), m_enabled, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeStringAccessor(), ns3::MakeStringChecker(), SetName(), and ns3::TypeId::SetParent().
IsEnabled()
bool ns3::DataCollectionObject::IsEnabled (void) const virtual
Check the status of an individual object.
Reimplemented in ns3::Probe.
Definition at line 60 of file data-collection-object.cc.
References m_enabled.
Referenced by ns3::Probe::IsEnabled(), and ns3::TimeSeriesAdaptor::TraceSinkDouble().
SetName()
void ns3::DataCollectionObject::SetName (std::string name)
Set the object's name. All spaces are replaced by underscores.
Definition at line 72 of file data-collection-object.cc.
References m_name, and NS_LOG_FUNCTION.
Referenced by ProbeTestCase1::DoRun(), and GetTypeId().
Member Data Documentation
m_enabled
bool ns3::DataCollectionObject::m_enabled protected
Object's activation state.
Definition at line 65 of file data-collection-object.h.
Referenced by Disable(), Enable(), GetTypeId(), IsEnabled(), ns3::FileAggregator::Write10d(), ns3::FileAggregator::Write1d(), ns3::FileAggregator::Write2d(), ns3::GnuplotAggregator::Write2d(), ns3::GnuplotAggregator::Write2dDatasetEmptyLine(), ns3::GnuplotAggregator::Write2dWithXErrorDelta(), ns3::GnuplotAggregator::Write2dWithXYErrorDelta(), ns3::GnuplotAggregator::Write2dWithYErrorDelta(), ns3::FileAggregator::Write3d(), ns3::FileAggregator::Write4d(), ns3::FileAggregator::Write5d(), ns3::FileAggregator::Write6d(), ns3::FileAggregator::Write7d(), ns3::FileAggregator::Write8d(), and ns3::FileAggregator::Write9d().
m_name
std::string ns3::DataCollectionObject::m_name protected
Name of the object within the data collection framework.
Definition at line 68 of file data-collection-object.h.
Referenced by GetName(), and SetName().
The documentation for this class was generated from the following files:
src/stats/model/data-collection-object.h
src/stats/model/data-collection-object.cc