ns-3: RandomVariableStreamDeterministicTestCase Class Reference
RandomVariableStreamDeterministicTestCase Class Reference
Public Member Functions
RandomVariableStreamDeterministicTestCase ()
virtual ~RandomVariableStreamDeterministicTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Static Public Attributes
static const double TOLERANCE = 1e-8
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 2643 of file random-variable-stream-test-suite.cc.
Constructor & Destructor Documentation
RandomVariableStreamDeterministicTestCase()
RandomVariableStreamDeterministicTestCase::RandomVariableStreamDeterministicTestCase ()
Definition at line 2657 of file random-variable-stream-test-suite.cc.
~RandomVariableStreamDeterministicTestCase()
RandomVariableStreamDeterministicTestCase::~RandomVariableStreamDeterministicTestCase () virtual
Definition at line 2661 of file random-variable-stream-test-suite.cc.
Member Function Documentation
DoRun()
void RandomVariableStreamDeterministicTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 2665 of file random-variable-stream-test-suite.cc.
References ns3::DeterministicRandomVariable::GetValue(), NS_TEST_ASSERT_MSG_EQ_TOL, anonymous_namespace{random-variable-stream-test-suite.cc}::SetTestSuiteSeed(), ns3::DeterministicRandomVariable::SetValueArray(), and TOLERANCE.
Member Data Documentation
TOLERANCE
const double RandomVariableStreamDeterministicTestCase::TOLERANCE = 1e-8 static
Definition at line 2646 of file random-variable-stream-test-suite.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/core/test/random-variable-stream-test-suite.cc