ns-3: HwmpReactiveRegressionTest Class Reference
HwmpReactiveRegressionTest Class Reference
Mesh Device » mesh module tests » dot11s sub-module tests | Test suites
test for multihop path establishing and path error procedures Initiate scenario with 6 stations. Procedure of opening peer link is the following: (PMP routines are not shown)
#include "hwmp-reactive-regression.h"
Public Member Functions
HwmpReactiveRegressionTest ()
virtual ~HwmpReactiveRegressionTest ()
void CheckResults ()
Check results function.
virtual void DoRun ()
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CreateDevices ()
Create devices function.
void CreateNodes ()
Create nodes function.
void HandleReadClient (Ptr< Socket > socket)
Handle a packet reception.
void HandleReadServer (Ptr< Socket > socket)
Handle a packet reception.
void InstallApplications ()
Install application function.
void ResetPosition ()
Reset position function.
void SendData (Ptr< Socket > socket)
Send data.
Private Attributes
Ptr< Socket > m_clientSocket
Client-side socket.
Ipv4InterfaceContainer m_interfaces
interfaces
NodeContainer * m_nodes
uint32_t m_sentPktsCounter
sent packets counter
Ptr< Socket > m_serverSocket
Server-side socket.
Time m_time
Simulation time.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
test for multihop path establishing and path error procedures Initiate scenario with 6 stations. Procedure of opening peer link is the following: (PMP routines are not shown)
*      1    2    3    4    5    6
*      |    |    |    |    |<---|--->  ARP request (first attempt has failed!)
*      |....|....|....|....|....|      ARP request
*      |<---|--->|    |    |    |      ARP request
*  <---|--->|    |    |    |    |      PREQ       } This order is broken
*  <---|--->|    |    |    |    |      ARP request} due to BroadcastDca
*      |<---|--->|    |    |    |      PREQ
*      |....|....|....|....|....|      ARP request
*      |    |    |    |<---|--->|      PREQ
*      |    |    |    |    |<---|      PREP
*      |....|....|....|....|....|      PREP
*      |<---|    |    |    |    |      PREP
*      |--->|    |    |    |    |      ARP response
*      |....|....|....|....|....|      ARP response
*      |    |    |    |    |--->|      ARP response
*      |    |    |    |    |<---|      Data
*      |....|....|....|....|....|      Data
*      |<---|    |    |    |    |      Data
*  <---|--->|    |    |    |    |      ARP request
*      |....|....|....|....|....|      ARP request
*      |    |    |    |    |<---|--->  ARP request
*      |    |    |    |    |<---|      ARP response
*      |....|....|....|....|....|      ARP response
*      |<---|    |    |    |    |      ARP response
*      |--->|    |    |    |    |      Data
* At 5 station number 4 disappears, and PERR is forwarded from 3 to 1
* and from 5 to 6, and station 6 starts path discovery procedure
* again:
*      |    |<---|         |--->|      PERR (one due to beacon loss and one due to TX error)
*      |<---|    |         |    |      PERR
*      |    |    |         |<---|--->  PREQ
*      |    |    |     <---|--->|      PREQ
*      |....|....|.........|....|      Repeated attempts of PREQ
*
Definition at line 73 of file hwmp-reactive-regression.h.
Constructor & Destructor Documentation
HwmpReactiveRegressionTest()
HwmpReactiveRegressionTest::HwmpReactiveRegressionTest ()
Definition at line 42 of file hwmp-reactive-regression.cc.
~HwmpReactiveRegressionTest()
HwmpReactiveRegressionTest::~HwmpReactiveRegressionTest () virtual
Definition at line 48 of file hwmp-reactive-regression.cc.
References m_nodes.
Member Function Documentation
CheckResults()
void HwmpReactiveRegressionTest::CheckResults ()
Check results function.
Definition at line 142 of file hwmp-reactive-regression.cc.
References NS_PCAP_TEST_EXPECT_EQ, and PREFIX.
Referenced by DoRun().
CreateDevices()
void HwmpReactiveRegressionTest::CreateDevices () private
Create devices function.
Definition at line 107 of file hwmp-reactive-regression.cc.
References first::address, ns3::MeshHelper::AssignStreams(), ns3::InternetStackHelper::AssignStreams(), ns3::YansWifiChannelHelper::AssignStreams(), ns3::YansWifiChannelHelper::Create(), ns3::TestCase::CreateTempDirFilename(), ns3::PcapHelperForDevice::EnablePcapAll(), ns3::NetDeviceContainer::GetN(), ns3::MeshHelper::Install(), ns3::InternetStackHelper::Install(), m_interfaces, m_nodes, NS_TEST_EXPECT_MSG_EQ, PREFIX, ns3::Seconds(), ns3::YansWifiPhyHelper::SetChannel(), ns3::WifiPhyHelper::SetErrorRateModel(), ns3::MeshHelper::SetMacType(), ns3::MeshHelper::SetNumberOfInterfaces(), and ns3::MeshHelper::SetStackInstaller().
Referenced by DoRun().
CreateNodes()
void HwmpReactiveRegressionTest::CreateNodes () private
Create nodes function.
Definition at line 73 of file hwmp-reactive-regression.cc.
References ns3::ListPositionAllocator::Add(), ns3::NodeContainer::Create(), m_nodes, third::mobility, ResetPosition(), and ns3::Seconds().
Referenced by DoRun().
DoRun()
void HwmpReactiveRegressionTest::DoRun () virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 53 of file hwmp-reactive-regression.cc.
References CheckResults(), CreateDevices(), CreateNodes(), InstallApplications(), m_nodes, and m_time.
HandleReadClient()
void HwmpReactiveRegressionTest::HandleReadClient (Ptr< Socket > socket) private
Handle a packet reception.
This function is called by lower layers.
Parameters
socket the socket the packet was received to.
Definition at line 189 of file hwmp-reactive-regression.cc.
References ns3::Socket::RecvFrom().
Referenced by InstallApplications().
HandleReadServer()
void HwmpReactiveRegressionTest::HandleReadServer (Ptr< Socket > socket) private
Handle a packet reception.
This function is called by lower layers.
Parameters
socket the socket the packet was received to.
Definition at line 175 of file hwmp-reactive-regression.cc.
References ns3::Socket::RecvFrom(), ns3::Packet::RemoveAllByteTags(), ns3::Packet::RemoveAllPacketTags(), and ns3::Socket::SendTo().
Referenced by InstallApplications().
InstallApplications()
void HwmpReactiveRegressionTest::InstallApplications () private
Install application function.
Definition at line 91 of file hwmp-reactive-regression.cc.
References ns3::Socket::Bind(), ns3::Socket::Connect(), ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::Node::GetId(), ns3::Socket::GetNode(), HandleReadClient(), HandleReadServer(), m_clientSocket, m_interfaces, m_nodes, m_serverSocket, ns3::MakeCallback(), ns3::Seconds(), SendData(), and ns3::Socket::SetRecvCallback().
Referenced by DoRun().
ResetPosition()
void HwmpReactiveRegressionTest::ResetPosition () private
Reset position function.
Definition at line 151 of file hwmp-reactive-regression.cc.
References ns3::NodeContainer::Get(), ns3::Object::GetObject(), m_nodes, and ns3::MobilityModel::SetPosition().
Referenced by CreateNodes().
SendData()
void HwmpReactiveRegressionTest::SendData (Ptr< Socket > socket) private
Send data.
Parameters
socket the sending socket
Definition at line 163 of file hwmp-reactive-regression.cc.
References ns3::Node::GetId(), ns3::Socket::GetNode(), m_sentPktsCounter, m_time, ns3::Now(), ns3::Seconds(), and ns3::Socket::Send().
Referenced by InstallApplications().
Member Data Documentation
m_clientSocket
Ptr<Socket> HwmpReactiveRegressionTest::m_clientSocket private
Client-side socket.
Definition at line 101 of file hwmp-reactive-regression.h.
Referenced by InstallApplications().
m_interfaces
Ipv4InterfaceContainer HwmpReactiveRegressionTest::m_interfaces private
interfaces
Definition at line 87 of file hwmp-reactive-regression.h.
Referenced by CreateDevices(), and InstallApplications().
m_nodes
NodeContainer* HwmpReactiveRegressionTest::m_nodes private
Internal: It is important to have pointers here
Definition at line 84 of file hwmp-reactive-regression.h.
Referenced by ~HwmpReactiveRegressionTest(), CreateDevices(), CreateNodes(), DoRun(), InstallApplications(), and ResetPosition().
m_sentPktsCounter
uint32_t HwmpReactiveRegressionTest::m_sentPktsCounter private
sent packets counter
Definition at line 104 of file hwmp-reactive-regression.h.
Referenced by SendData().
m_serverSocket
Ptr<Socket> HwmpReactiveRegressionTest::m_serverSocket private
Server-side socket.
Definition at line 99 of file hwmp-reactive-regression.h.
Referenced by InstallApplications().
m_time
Time HwmpReactiveRegressionTest::m_time private
Simulation time.
Definition at line 86 of file hwmp-reactive-regression.h.
Referenced by DoRun(), and SendData().
The documentation for this class was generated from the following files:
src/mesh/test/dot11s/hwmp-reactive-regression.h
src/mesh/test/dot11s/hwmp-reactive-regression.cc