ns-3: Ns3WimaxSNRtoBLERTestCase Class Reference
Ns3WimaxSNRtoBLERTestCase Class Reference
WiMAX Models » wimax module tests | Test suites
Test the SNr tom block error rate module.
Public Member Functions
Ns3WimaxSNRtoBLERTestCase ()
virtual ~Ns3WimaxSNRtoBLERTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
bool DoRunOnce (uint8_t modulationType)
Run once function.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test the SNr tom block error rate module.
Definition at line 128 of file phy-test.cc.
Constructor & Destructor Documentation
Ns3WimaxSNRtoBLERTestCase()
Ns3WimaxSNRtoBLERTestCase::Ns3WimaxSNRtoBLERTestCase ()
Definition at line 145 of file phy-test.cc.
~Ns3WimaxSNRtoBLERTestCase()
Ns3WimaxSNRtoBLERTestCase::~Ns3WimaxSNRtoBLERTestCase () virtual
Definition at line 150 of file phy-test.cc.
Member Function Documentation
DoRun()
void Ns3WimaxSNRtoBLERTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 171 of file phy-test.cc.
References DoRunOnce().
DoRunOnce()
bool Ns3WimaxSNRtoBLERTestCase::DoRunOnce (uint8_t modulationType) private
Run once function.
Parameters
modulationType the modulation type
Returns
true if successful
Definition at line 154 of file phy-test.cc.
References ns3::SNRToBlockErrorRateManager::GetSNRToBlockErrorRateRecord(), and ns3::SNRToBlockErrorRateManager::LoadTraces().
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/wimax/test/phy-test.cc