ns-3: ns3::SocketPriorityTag Class Reference
ns3::SocketPriorityTag Class Reference
indicates whether the socket has a priority set.
#include "socket.h"
Public Member Functions
SocketPriorityTag ()
virtual void Deserialize (TagBuffer i)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint8_t GetPriority (void) const
Get the tag's priority.
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer i) const
void SetPriority (uint8_t priority)
Set the tag's priority.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_priority
the priority carried by the tag
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
indicates whether the socket has a priority set.
Definition at line 1307 of file socket.h.
Constructor & Destructor Documentation
SocketPriorityTag()
ns3::SocketPriorityTag::SocketPriorityTag ()
Definition at line 837 of file socket.cc.
Member Function Documentation
Deserialize()
void ns3::SocketPriorityTag::Deserialize (TagBuffer i) virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 883 of file socket.cc.
References m_priority, and ns3::TagBuffer::ReadU8().
GetInstanceTypeId()
TypeId ns3::SocketPriorityTag::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 865 of file socket.cc.
References GetTypeId().
GetPriority()
uint8_t ns3::SocketPriorityTag::GetPriority (void) const
Get the tag's priority.
Returns
the priority
Definition at line 848 of file socket.cc.
References m_priority.
Referenced by ns3::PfifoFastQueueDisc::DoEnqueue(), ns3::PrioQueueDisc::DoEnqueue(), ns3::MeshWifiInterfaceMac::ForwardDown(), UdpSocketImplTest::GetPriority(), and ns3::QosUtilsGetTidForPacket().
GetSerializedSize()
uint32_t ns3::SocketPriorityTag::GetSerializedSize (void) const virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 871 of file socket.cc.
GetTypeId()
TypeId ns3::SocketPriorityTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 854 of file socket.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::SocketPriorityTag::Print (std::ostream & os) const virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 889 of file socket.cc.
References m_priority.
Serialize()
void ns3::SocketPriorityTag::Serialize (TagBuffer i) const virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 877 of file socket.cc.
References m_priority, and ns3::TagBuffer::WriteU8().
SetPriority()
void ns3::SocketPriorityTag::SetPriority (uint8_t priority)
Set the tag's priority.
Parameters
priority the priority
Definition at line 842 of file socket.cc.
References m_priority.
Referenced by PrioQueueDiscTestItem::PrioQueueDiscTestItem(), PfifoFastQueueDiscOverflow::AddPacket(), ns3::TcpSocketBase::AddSocketTags(), ns3::UdpSocketImpl::DoSendTo(), ns3::VsaManager::DoSendVsa(), ns3::Ipv4L3Protocol::IpForward(), ns3::MeshWifiInterfaceMac::Receive(), ns3::SelectQueueByDSField(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), Issue169TestCase::SendPackets(), ns3::Ipv4RawSocketImpl::SendTo(), ns3::PacketSocket::SendTo(), ns3::WaveNetDevice::SendX(), PfifoFastQueueDiscDscpPrioritization::TestDscpValue(), and PfifoFastQueueDiscTosPrioritization::TestTosValue().
Member Data Documentation
m_priority
uint8_t ns3::SocketPriorityTag::m_priority private
the priority carried by the tag
Definition at line 1347 of file socket.h.
Referenced by Deserialize(), GetPriority(), Print(), Serialize(), and SetPriority().
The documentation for this class was generated from the following files:
src/network/model/socket.h
src/network/model/socket.cc