ns-3: TestPhyHeadersReception Class Reference
TestPhyHeadersReception Class Reference
Wifi Models » wifi module tests | Test suites
Test PHY state upon success or failure of L-SIG and SIG-A.
Public Member Functions
TestPhyHeadersReception ()
virtual ~TestPhyHeadersReception ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Member Functions
virtual void DoSetup (void)
Implementation to do any local setup required for this TestCase.
void SendPacket (double rxPowerDbm)
Send packet function.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Protected Attributes
Ptr< SpectrumWifiPhy > m_phy
Phy.
Private Member Functions
void CheckPhyState (WifiPhyState expectedState)
Schedule now to check the PHY state.
void DoCheckPhyState (WifiPhyState expectedState)
Check the PHY state now.
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Detailed Description
Test PHY state upon success or failure of L-SIG and SIG-A.
Definition at line 1141 of file wifi-phy-reception-test.cc.
Constructor & Destructor Documentation
TestPhyHeadersReception()
TestPhyHeadersReception::TestPhyHeadersReception ()
Definition at line 1171 of file wifi-phy-reception-test.cc.
~TestPhyHeadersReception()
TestPhyHeadersReception::~TestPhyHeadersReception () virtual
Definition at line 1223 of file wifi-phy-reception-test.cc.
References m_phy.
Member Function Documentation
CheckPhyState()
void TestPhyHeadersReception::CheckPhyState (WifiPhyState expectedState) private
Schedule now to check the PHY state.
Parameters
expectedState the expected PHY state
Definition at line 1204 of file wifi-phy-reception-test.cc.
References DoCheckPhyState().
Referenced by DoRun().
DoCheckPhyState()
void TestPhyHeadersReception::DoCheckPhyState (WifiPhyState expectedState) private
Check the PHY state now.
Parameters
expectedState the expected PHY state
Definition at line 1211 of file wifi-phy-reception-test.cc.
References ns3::PointerValue::Get(), ns3::ObjectBase::GetAttribute(), ns3::WifiPhyStateHelper::GetState(), m_phy, ns3::Now(), NS_LOG_FUNCTION, and NS_TEST_ASSERT_MSG_EQ.
Referenced by CheckPhyState().
DoRun()
void TestPhyHeadersReception::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 1240 of file wifi-phy-reception-test.cc.
References ns3::WifiPhy::AssignStreams(), CCA_BUSY, CheckPhyState(), IDLE, m_phy, ns3::MicroSeconds(), ns3::NanoSeconds(), RX, ns3::Seconds(), and SendPacket().
DoSetup()
void TestPhyHeadersReception::DoSetup (void) protected virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test setup before DoRun is invoked.
Reimplemented from ns3::TestCase.
Definition at line 1229 of file wifi-phy-reception-test.cc.
References CHANNEL_NUMBER, ns3::SpectrumWifiPhy::ConfigureStandard(), FREQUENCY, m_phy, ns3::SpectrumWifiPhy::SetChannelNumber(), ns3::WifiPhy::SetErrorRateModel(), ns3::SpectrumWifiPhy::SetFrequency(), and ns3::WIFI_PHY_STANDARD_80211ax_5GHZ.
SendPacket()
void TestPhyHeadersReception::SendPacket (double rxPowerDbm) protected
Send packet function.
Parameters
rxPowerDbm the transmit power in dBm
Definition at line 1177 of file wifi-phy-reception-test.cc.
References ns3::WifiPhy::CalculateTxDuration(), CHANNEL_WIDTH, ns3::lorawan::DbmToW(), ns3::SpectrumSignalParameters::duration, FREQUENCY, ns3::WifiPhy::GetFrequency(), ns3::WifiPsdu::GetSize(), GUARD_WIDTH, m_phy, ns3::WifiSpectrumSignalParameters::ppdu, ns3::SpectrumSignalParameters::psd, ns3::WifiMacHeader::SetQosTid(), ns3::WifiMacHeader::SetType(), ns3::SpectrumWifiPhy::StartRx(), ns3::SpectrumSignalParameters::txPhy, ns3::WIFI_MAC_QOSDATA, and ns3::WIFI_PREAMBLE_HE_SU.
Referenced by DoRun().
Member Data Documentation
m_phy
Ptr<SpectrumWifiPhy> TestPhyHeadersReception::m_phy protected
Phy.
Definition at line 1149 of file wifi-phy-reception-test.cc.
Referenced by ~TestPhyHeadersReception(), DoCheckPhyState(), DoRun(), DoSetup(), and SendPacket().
The documentation for this class was generated from the following file:
src/wifi/test/wifi-phy-reception-test.cc