ns-3: ns3::Icmpv6Echo Class Reference
ns3::Icmpv6Echo Class Reference
Internet » IPv6 classes and sub-modules » ICMPv6 protocol and associated headers.
ICMPv6 Echo message.
#include "icmpv6-header.h"
Public Member Functions
Icmpv6Echo ()
Default constructor.
Icmpv6Echo (bool request)
Constructor.
virtual ~Icmpv6Echo ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
uint16_t GetId () const
Get the ID of the packet.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
uint16_t GetSeq () const
Get the sequence number.
virtual uint32_t GetSerializedSize () const
Get the serialized size.
virtual void Print (std::ostream &os) const
Print information.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetId (uint16_t id)
Set the ID of the packet.
void SetSeq (uint16_t seq)
Set the sequence number.
Public Member Functions inherited from ns3::Icmpv6Header
Icmpv6Header ()
Constructor.
virtual ~Icmpv6Header ()
Destructor.
void CalculatePseudoHeaderChecksum (Ipv6Address src, Ipv6Address dst, uint16_t length, uint8_t protocol)
Calculate pseudo header checksum for IPv6.
uint16_t GetChecksum () const
Get the checksum.
uint8_t GetCode () const
Get the code field.
uint8_t GetType () const
Get the type field.
void SetChecksum (uint16_t checksum)
Set the checksum.
void SetCode (uint8_t code)
Set the code field.
void SetType (uint8_t type)
Set the type.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the UID of this class.
Static Public Member Functions inherited from ns3::Icmpv6Header
static TypeId GetTypeId ()
Get the UID of this class.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint16_t m_id
ID of the packet (to distinguish response between many ping program).
uint16_t m_seq
Sequence number (to distinguish response).
Additional Inherited Members
Public Types inherited from ns3::Icmpv6Header
enum ErrorDestinationUnreachable_e {
ICMPV6_NO_ROUTE = 0, ICMPV6_ADM_PROHIBITED, ICMPV6_NOT_NEIGHBOUR, ICMPV6_ADDR_UNREACHABLE,
ICMPV6_PORT_UNREACHABLE
}
ICMPv6 error code : Destination Unreachable.
enum ErrorParameterError_e { ICMPV6_MALFORMED_HEADER = 0, ICMPV6_UNKNOWN_NEXT_HEADER, ICMPV6_UNKNOWN_OPTION }
ICMPv6 error code : Parameter Error.
enum ErrorTimeExceeded_e { ICMPV6_HOPLIMIT = 0, ICMPV6_FRAGTIME }
ICMPv6 error code : Time Exceeded.
enum OptionType_e {
ICMPV6_OPT_LINK_LAYER_SOURCE = 1, ICMPV6_OPT_LINK_LAYER_TARGET, ICMPV6_OPT_PREFIX, ICMPV6_OPT_REDIRECTED,
ICMPV6_OPT_MTU
}
ICMPv6 Option type code.
enum Type_e {
ICMPV6_ERROR_DESTINATION_UNREACHABLE = 1, ICMPV6_ERROR_PACKET_TOO_BIG, ICMPV6_ERROR_TIME_EXCEEDED, ICMPV6_ERROR_PARAMETER_ERROR,
ICMPV6_ECHO_REQUEST = 128, ICMPV6_ECHO_REPLY, ICMPV6_SUBSCRIBE_REQUEST, ICMPV6_SUBSCRIBE_REPORT,
ICMPV6_SUBSCRIVE_END, ICMPV6_ND_ROUTER_SOLICITATION, ICMPV6_ND_ROUTER_ADVERTISEMENT, ICMPV6_ND_NEIGHBOR_SOLICITATION,
ICMPV6_ND_NEIGHBOR_ADVERTISEMENT, ICMPV6_ND_REDIRECTION, ICMPV6_ROUTER_RENUMBER, ICMPV6_INFORMATION_REQUEST,
ICMPV6_INFORMATION_RESPONSE, ICMPV6_INVERSE_ND_SOLICITATION, ICMPV6_INVERSE_ND_ADVERSTISEMENT, ICMPV6_MLDV2_SUBSCRIBE_REPORT,
ICMPV6_MOBILITY_HA_DISCOVER_REQUEST, ICMPV6_MOBILITY_HA_DISCOVER_RESPONSE, ICMPV6_MOBILITY_MOBILE_PREFIX_SOLICITATION, ICMPV6_SECURE_ND_CERTIFICATE_PATH_SOLICITATION,
ICMPV6_SECURE_ND_CERTIFICATE_PATH_ADVERTISEMENT, ICMPV6_EXPERIMENTAL_MOBILITY
}
ICMPv6 type code.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Icmpv6Header
bool m_calcChecksum
Checksum enable or not.
uint16_t m_checksum
The checksum.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
ICMPv6 Echo message.
Definition at line 944 of file icmpv6-header.h.
Constructor & Destructor Documentation
Icmpv6Echo() [1/2]
ns3::Icmpv6Echo::Icmpv6Echo ()
Default constructor.
Definition at line 943 of file icmpv6-header.cc.
References ns3::Icmpv6Header::ICMPV6_ECHO_REQUEST, ns3::Icmpv6Header::m_checksum, NS_LOG_FUNCTION, ns3::Icmpv6Header::SetCode(), SetId(), SetSeq(), and ns3::Icmpv6Header::SetType().
Icmpv6Echo() [2/2]
ns3::Icmpv6Echo::Icmpv6Echo (bool request)
Constructor.
Parameters
request request or reply message
Definition at line 953 of file icmpv6-header.cc.
References ns3::Icmpv6Header::ICMPV6_ECHO_REPLY, ns3::Icmpv6Header::ICMPV6_ECHO_REQUEST, ns3::Icmpv6Header::m_checksum, NS_LOG_FUNCTION, ns3::Icmpv6Header::SetCode(), SetId(), SetSeq(), and ns3::Icmpv6Header::SetType().
~Icmpv6Echo()
ns3::Icmpv6Echo::~Icmpv6Echo () virtual
Destructor.
Definition at line 963 of file icmpv6-header.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Deserialize()
uint32_t ns3::Icmpv6Echo::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start start offset
Returns
length of packet
Reimplemented from ns3::Icmpv6Header.
Definition at line 1029 of file icmpv6-header.cc.
References GetSerializedSize(), ns3::Icmpv6Header::m_checksum, m_id, m_seq, NS_LOG_FUNCTION, ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU8(), ns3::Icmpv6Header::SetCode(), ns3::Icmpv6Header::SetType(), and visualizer.core::start().
GetId()
uint16_t ns3::Icmpv6Echo::GetId () const
Get the ID of the packet.
Returns
id
Definition at line 968 of file icmpv6-header.cc.
References m_id, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::HandleEchoRequest(), and ns3::Ping6::HandleRead().
GetInstanceTypeId()
TypeId ns3::Icmpv6Echo::GetInstanceTypeId () const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::Icmpv6Header.
Definition at line 937 of file icmpv6-header.cc.
References GetTypeId(), and NS_LOG_FUNCTION.
GetSeq()
uint16_t ns3::Icmpv6Echo::GetSeq () const
Get the sequence number.
Returns
sequence number
Definition at line 980 of file icmpv6-header.cc.
References m_seq, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::HandleEchoRequest(), and ns3::Ping6::HandleRead().
GetSerializedSize()
uint32_t ns3::Icmpv6Echo::GetSerializedSize () const virtual
Get the serialized size.
Returns
serialized size
Reimplemented from ns3::Icmpv6Header.
Definition at line 1000 of file icmpv6-header.cc.
References NS_LOG_FUNCTION.
Referenced by Deserialize(), ns3::Icmpv6L4Protocol::ForgeEchoRequest(), ns3::Icmpv6L4Protocol::SendEchoReply(), and ns3::Ipv6RawSocketImpl::SendTo().
GetTypeId()
TypeId ns3::Icmpv6Echo::GetTypeId () static
Get the UID of this class.
Returns
UID
Definition at line 927 of file icmpv6-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::Icmpv6Echo::Print (std::ostream & os) const virtual
Print information.
Parameters
os output stream
Reimplemented from ns3::Icmpv6Header.
Definition at line 992 of file icmpv6-header.cc.
References ns3::Icmpv6Header::GetChecksum(), ns3::Icmpv6Header::GetCode(), ns3::Icmpv6Header::GetType(), and NS_LOG_FUNCTION.
Serialize()
void ns3::Icmpv6Echo::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start start offset
Reimplemented from ns3::Icmpv6Header.
Definition at line 1006 of file icmpv6-header.cc.
References ns3::Buffer::Iterator::CalculateIpChecksum(), ns3::Icmpv6Header::GetChecksum(), ns3::Icmpv6Header::GetCode(), ns3::Buffer::Iterator::GetSize(), ns3::Icmpv6Header::GetType(), ns3::Icmpv6Header::m_calcChecksum, m_id, m_seq, ns3::Buffer::Iterator::Next(), NS_LOG_FUNCTION, visualizer.core::start(), ns3::Buffer::Iterator::WriteHtonU16(), ns3::Buffer::Iterator::WriteU16(), and ns3::Buffer::Iterator::WriteU8().
SetId()
void ns3::Icmpv6Echo::SetId (uint16_t id)
Set the ID of the packet.
Parameters
id id to set
Definition at line 974 of file icmpv6-header.cc.
References m_id, and NS_LOG_FUNCTION.
Referenced by Icmpv6Echo(), IcmpV6EchoReplyTestCase::DoSendData(), IcmpV6TimeExceedTestCase::DoSendData(), ns3::Icmpv6L4Protocol::ForgeEchoRequest(), ns3::Ping6::Send(), and ns3::Icmpv6L4Protocol::SendEchoReply().
SetSeq()
void ns3::Icmpv6Echo::SetSeq (uint16_t seq)
Set the sequence number.
Parameters
seq sequence to set
Definition at line 986 of file icmpv6-header.cc.
References m_seq, and NS_LOG_FUNCTION.
Referenced by Icmpv6Echo(), IcmpV6EchoReplyTestCase::DoSendData(), IcmpV6TimeExceedTestCase::DoSendData(), ns3::Icmpv6L4Protocol::ForgeEchoRequest(), ns3::Ping6::Send(), and ns3::Icmpv6L4Protocol::SendEchoReply().
Member Data Documentation
m_id
uint16_t ns3::Icmpv6Echo::m_id private
ID of the packet (to distinguish response between many ping program).
Definition at line 1028 of file icmpv6-header.h.
Referenced by Deserialize(), GetId(), Serialize(), and SetId().
m_seq
uint16_t ns3::Icmpv6Echo::m_seq private
Sequence number (to distinguish response).
Definition at line 1033 of file icmpv6-header.h.
Referenced by Deserialize(), GetSeq(), Serialize(), and SetSeq().
The documentation for this class was generated from the following files:
src/internet/model/icmpv6-header.h
src/internet/model/icmpv6-header.cc