ns-3: BufferTest Class Reference
BufferTest Class Reference
Network » Network module unit tests | Test suites
Public Member Functions
BufferTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void EnsureWrittenBytes (Buffer b, uint32_t n, uint8_t array[], const char *file, int line)
Checks the buffer content.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Buffer unit tests.
Definition at line 39 of file buffer-test.cc.
Constructor & Destructor Documentation
BufferTest()
BufferTest::BufferTest ()
Definition at line 56 of file buffer-test.cc.
Member Function Documentation
DoRun()
void BufferTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Internal:
See Bug 54
Internal: See Bug 1001
Internal: See Bug 2044 Will not pass without bug2044 fix.
Implements ns3::TestCase.
Definition at line 108 of file buffer-test.cc.
References ns3::Buffer::AddAtEnd(), ns3::Buffer::AddAtStart(), ns3::Buffer::Begin(), ns3::Buffer::CopyData(), ns3::Buffer::CreateFragment(), ns3::Buffer::End(), ENSURE_WRITTEN_BYTES, ns3::Buffer::GetSize(), ns3::UniformRandomVariable::GetValue(), ns3::Buffer::Iterator::Next(), NS_TEST_ASSERT_MSG_EQ, NS_TEST_ASSERT_MSG_NE, NS_TEST_EXPECT_MSG_EQ, ns3::Buffer::PeekData(), ns3::Buffer::Iterator::Prev(), ns3::Buffer::Iterator::ReadLsbtohU64(), ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadNtohU64(), ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU64(), ns3::Buffer::Iterator::ReadU8(), ns3::Buffer::RemoveAtEnd(), ns3::Buffer::RemoveAtStart(), ns3::ObjectBase::SetAttribute(), ns3::Buffer::Iterator::Write(), ns3::Buffer::Iterator::WriteHtolsbU64(), ns3::Buffer::Iterator::WriteHtonU16(), ns3::Buffer::Iterator::WriteHtonU32(), ns3::Buffer::Iterator::WriteHtonU64(), ns3::Buffer::Iterator::WriteU16(), ns3::Buffer::Iterator::WriteU64(), and ns3::Buffer::Iterator::WriteU8().
EnsureWrittenBytes()
void BufferTest::EnsureWrittenBytes (Buffer b, uint32_t n, uint8_t array[], const char * file, int line) private
Checks the buffer content.
Parameters
b The buffer to check
n The number of bytes to check
array The array of bytes that should be in the buffer
file The file name
line The line number
Definition at line 61 of file buffer-test.cc.
References anonymous_namespace{print-introspected-doxygen.cc}::file, sample-rng-plot::n, NS_TEST_ASSERT_MSG_EQ_INTERNAL, and ns3::Buffer::PeekData().
The documentation for this class was generated from the following file:
src/network/test/buffer-test.cc