ns-3: LteRlcUmTransmitterSegmentationTestCase Class Reference
LteRlcUmTransmitterSegmentationTestCase Class Reference
LTE Models » lte module tests | Test suites
Test 4.1.1.2 Segmentation (One SDU => n PDUs)
#include "lte-test-rlc-um-transmitter.h"
Public Member Functions
LteRlcUmTransmitterSegmentationTestCase ()
LteRlcUmTransmitterSegmentationTestCase (std::string name)
Constructor.
virtual ~LteRlcUmTransmitterSegmentationTestCase ()
Public Member Functions inherited from LteRlcUmTransmitterTestCase
LteRlcUmTransmitterTestCase ()
LteRlcUmTransmitterTestCase (std::string name)
Constructor.
virtual ~LteRlcUmTransmitterTestCase ()
void CheckDataReceived (Time time, std::string shouldReceived, std::string assertMsg)
Check data received function.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Protected Attributes inherited from LteRlcUmTransmitterTestCase
Ptr< LteTestMac > txMac
the MAC
Ptr< LteTestPdcp > txPdcp
the transmit PDCP
Ptr< LteRlc > txRlc
the RLC
Detailed Description
Test 4.1.1.2 Segmentation (One SDU => n PDUs)
Definition at line 122 of file lte-test-rlc-um-transmitter.h.
Constructor & Destructor Documentation
LteRlcUmTransmitterSegmentationTestCase() [1/2]
LteRlcUmTransmitterSegmentationTestCase::LteRlcUmTransmitterSegmentationTestCase (std::string name)
Constructor.
Test 4.1.1.2 Segmentation (One SDU => n PDUs)
Parameters
name the reference name
Definition at line 153 of file lte-test-rlc-um-transmitter.cc.
LteRlcUmTransmitterSegmentationTestCase() [2/2]
LteRlcUmTransmitterSegmentationTestCase::LteRlcUmTransmitterSegmentationTestCase ()
~LteRlcUmTransmitterSegmentationTestCase()
LteRlcUmTransmitterSegmentationTestCase::~LteRlcUmTransmitterSegmentationTestCase () virtual
Definition at line 158 of file lte-test-rlc-um-transmitter.cc.
Member Function Documentation
DoRun()
void LteRlcUmTransmitterSegmentationTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Reimplemented from LteRlcUmTransmitterTestCase.
Definition at line 163 of file lte-test-rlc-um-transmitter.cc.
References LteRlcUmTransmitterTestCase::CheckDataReceived(), LteRlcUmTransmitterTestCase::DoRun(), ns3::Seconds(), ns3::LteTestPdcp::SendData(), ns3::LteTestMac::SendTxOpportunity(), LteRlcUmTransmitterTestCase::txMac, and LteRlcUmTransmitterTestCase::txPdcp.
The documentation for this class was generated from the following files:
src/lte/test/lte-test-rlc-um-transmitter.h
src/lte/test/lte-test-rlc-um-transmitter.cc