ns-3: WifiPhyStats Class Reference
WifiPhyStats Class Reference
WAVE module
The WifiPhyStats class collects Wifi MAC/PHY statistics.
Public Member Functions
WifiPhyStats ()
Constructor.
virtual ~WifiPhyStats ()
Destructor.
uint32_t GetTxBytes ()
Returns the number of bytes that have been transmitted (this includes MAC/PHY overhead)
void PhyRxDrop (std::string context, Ptr< const Packet > packet)
Callback signiture for Phy/RxDrop.
void PhyTxDrop (std::string context, Ptr< const Packet > packet)
Callback signiture for Phy/TxDrop.
void PhyTxTrace (std::string context, Ptr< const Packet > packet, WifiMode mode, WifiPreamble preamble, uint8_t txPower)
Callback signiture for Phy/Tx trace.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Gets the class TypeId.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint32_t m_phyTxBytes
phy transmit bytes
uint32_t m_phyTxPkts
phy transmit packets
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The WifiPhyStats class collects Wifi MAC/PHY statistics.
Definition at line 722 of file vanet-routing-compare.cc.
Constructor & Destructor Documentation
WifiPhyStats()
WifiPhyStats::WifiPhyStats ()
Constructor.
Returns
none
Definition at line 793 of file vanet-routing-compare.cc.
~WifiPhyStats()
WifiPhyStats::~WifiPhyStats () virtual
Destructor.
Returns
none
Definition at line 799 of file vanet-routing-compare.cc.
Member Function Documentation
GetTxBytes()
uint32_t WifiPhyStats::GetTxBytes ()
Returns the number of bytes that have been transmitted (this includes MAC/PHY overhead)
Returns
the number of bytes transmitted
Definition at line 827 of file vanet-routing-compare.cc.
References m_phyTxBytes.
Referenced by VanetRoutingExperiment::CheckThroughput(), and VanetRoutingExperiment::ProcessOutputs().
GetTypeId()
TypeId WifiPhyStats::GetTypeId (void) static
Gets the class TypeId.
Returns
the class TypeId
Definition at line 785 of file vanet-routing-compare.cc.
References ns3::TypeId::SetParent().
PhyRxDrop()
void WifiPhyStats::PhyRxDrop (std::string context, Ptr< const Packet > packet)
Callback signiture for Phy/RxDrop.
Parameters
context this object
packet the rx packet being dropped
Returns
none
Definition at line 821 of file vanet-routing-compare.cc.
References NS_LOG_UNCOND.
Referenced by VanetRoutingExperiment::ConfigureDevices().
PhyTxDrop()
void WifiPhyStats::PhyTxDrop (std::string context, Ptr< const Packet > packet)
Callback signiture for Phy/TxDrop.
Parameters
context this object
packet the tx packet being dropped
Returns
none
Definition at line 815 of file vanet-routing-compare.cc.
References NS_LOG_UNCOND.
Referenced by VanetRoutingExperiment::ConfigureDevices().
PhyTxTrace()
void WifiPhyStats::PhyTxTrace (std::string context, Ptr< const Packet > packet, WifiMode mode, WifiPreamble preamble, uint8_t txPower)
Callback signiture for Phy/Tx trace.
Parameters
context this object
packet packet transmitted
mode wifi mode
preamble wifi preamble
txPower transmission power
Returns
none
Definition at line 804 of file vanet-routing-compare.cc.
References ns3::Packet::GetSize(), m_phyTxBytes, m_phyTxPkts, and NS_LOG_FUNCTION.
Referenced by VanetRoutingExperiment::ConfigureDevices().
Member Data Documentation
m_phyTxBytes
uint32_t WifiPhyStats::m_phyTxBytes private
phy transmit bytes
Definition at line 779 of file vanet-routing-compare.cc.
Referenced by GetTxBytes(), and PhyTxTrace().
m_phyTxPkts
uint32_t WifiPhyStats::m_phyTxPkts private
phy transmit packets
Definition at line 778 of file vanet-routing-compare.cc.
Referenced by PhyTxTrace().
The documentation for this class was generated from the following file:
src/wave/examples/vanet-routing-compare.cc