ns-3: LteX2HandoverTestCase Class Reference
LteX2HandoverTestCase Class Reference
LTE Models » lte module tests | Test suites
Test X2 Handover. In this test is used NoOpHandoverAlgorithm and the request for handover is generated manually, and it is not based on measurements.
Classes
struct BearerData
BearerData structure.
struct UeData
UeData structure.
Public Member Functions
LteX2HandoverTestCase (uint32_t nUes, uint32_t nDedicatedBearers, std::list< HandoverEvent > handoverEventList, std::string handoverEventListName, std::string schedulerType, bool admitHo, bool useIdealRrc)
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CheckConnected (Ptr< NetDevice > ueDevice, Ptr< NetDevice > enbDevice)
Check connected function.
void CheckStatsAWhileAfterHandover (uint32_t ueIndex)
Check stats a while after handover function.
virtual void DoRun (void)
Implementation to actually run this TestCase.
void SaveStatsAfterHandover (uint32_t ueIndex)
Save stats after handover function.
void TeleportUeNearTargetEnb (Ptr< Node > ueNode, Ptr< Node > enbNode)
Teleport UE near the target eNB of the handover.
void TeleportUeToMiddle (Ptr< Node > ueNode)
Teleport UE between both eNBs of the test.
Static Private Member Functions
static std::string BuildNameString (uint32_t nUes, uint32_t nDedicatedBearers, std::string handoverEventListName, std::string schedulerType, bool admitHo, bool useIdealRrc)
Build name string.
Private Attributes
bool m_admitHo
whether to admit the handover request
bool m_epc
whether to use EPC
Ptr< PointToPointEpcHelper > m_epcHelper
EPC helper.
std::list< HandoverEvent > m_handoverEventList
handover event list
std::string m_handoverEventListName
handover event list name
Ptr< LteHelper > m_lteHelper
LTE helper.
const Time m_maxHoDuration
maximum HO duration
uint32_t m_nDedicatedBearers
number of UEs in the test
uint32_t m_nUes
number of UEs in the test
std::string m_schedulerType
scheduler type
const Time m_statsDuration
stats duration
const Time m_udpClientInterval
UDP client interval.
const uint32_t m_udpClientPktSize
UDP client packet size.
std::vector< UeData > m_ueDataVector
UE data vector.
bool m_useIdealRrc
whether to use the ideal RRC
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test X2 Handover. In this test is used NoOpHandoverAlgorithm and the request for handover is generated manually, and it is not based on measurements.
Definition at line 56 of file test-lte-x2-handover.cc.
Constructor & Destructor Documentation
LteX2HandoverTestCase()
LteX2HandoverTestCase::LteX2HandoverTestCase (uint32_t nUes, uint32_t nDedicatedBearers, std::list< HandoverEvent > handoverEventList, std::string handoverEventListName, std::string schedulerType, bool admitHo, bool useIdealRrc)
Parameters
nUes number of UEs in the test
nDedicatedBearers number of bearers to be activated per UE
handoverEventList
handoverEventListName
schedulerType the scheduler type
admitHo
useIdealRrc true if the ideal RRC should be used
Definition at line 184 of file test-lte-x2-handover.cc.
Member Function Documentation
BuildNameString()
std::string LteX2HandoverTestCase::BuildNameString (uint32_t nUes, uint32_t nDedicatedBearers, std::string handoverEventListName, std::string schedulerType, bool admitHo, bool useIdealRrc) static private
Build name string.
Parameters
nUes number of UEs in the test
nDedicatedBearers number of bearers to be activated per UE
handoverEventListName
schedulerType the scheduler type
admitHo
useIdealRrc true if the ideal RRC should be used
Returns
the name string
Definition at line 165 of file test-lte-x2-handover.cc.
Referenced by DoRun().
CheckConnected()
void LteX2HandoverTestCase::CheckConnected (Ptr< NetDevice > ueDevice, Ptr< NetDevice > enbDevice) private
Check connected function.
Parameters
ueDevice the UE device
enbDevice the ENB device
Definition at line 484 of file test-lte-x2-handover.cc.
References ns3::ObjectPtrContainerValue::Begin(), ns3::ObjectPtrContainerValue::End(), ns3::ObjectBase::GetAttribute(), ns3::LteEnbNetDevice::GetCellId(), ns3::LteEnbNetDevice::GetDlBandwidth(), ns3::LteEnbNetDevice::GetDlEarfcn(), ns3::LteUeNetDevice::GetImsi(), ns3::UeManager::GetImsi(), ns3::ObjectPtrContainerValue::GetN(), ns3::Object::GetObject(), ns3::LteEnbNetDevice::GetRrc(), ns3::LteUeNetDevice::GetRrc(), ns3::UeManager::GetState(), ns3::LteEnbNetDevice::GetUlBandwidth(), ns3::LteEnbNetDevice::GetUlEarfcn(), ns3::LteDataRadioBearerInfo::m_drbIdentity, ns3::LteDataRadioBearerInfo::m_epsBearerIdentity, ns3::LteDataRadioBearerInfo::m_logicalChannelIdentity, m_nDedicatedBearers, NS_ASSERT_MSG(), NS_TEST_ASSERT_MSG_EQ, and NS_TEST_ASSERT_MSG_NE.
Referenced by DoRun().
CheckStatsAWhileAfterHandover()
void LteX2HandoverTestCase::CheckStatsAWhileAfterHandover (uint32_t ueIndex) private
Check stats a while after handover function.
Parameters
ueIndex the index of the UE
Definition at line 580 of file test-lte-x2-handover.cc.
References ns3::Time::GetSeconds(), m_statsDuration, m_udpClientInterval, m_udpClientPktSize, m_ueDataVector, and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
DoRun()
void LteX2HandoverTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 203 of file test-lte-x2-handover.cc.
References ns3::LteHelper::ActivateDataRadioBearer(), ns3::LteHelper::ActivateDedicatedEpsBearer(), ns3::EpcTft::Add(), ns3::ListPositionAllocator::Add(), ns3::Ipv4StaticRouting::AddNetworkRouteTo(), ns3::LteHelper::AddX2Interface(), ns3::Ipv4AddressHelper::Assign(), ns3::LteHelper::AssignStreams(), ns3::NoBackhaulEpcHelper::AssignUeIpv4Address(), ns3::LteHelper::Attach(), LteX2HandoverTestCase::UeData::bearerDataList, ns3::NetDeviceContainer::Begin(), BuildNameString(), CheckConnected(), CheckStatsAWhileAfterHandover(), first::clientApps, ns3::NodeContainer::Create(), LteX2HandoverTestCase::BearerData::dlSink, ns3::NetDeviceContainer::End(), ns3::ApplicationContainer::Get(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::NetDeviceContainer::GetN(), ns3::NodeContainer::GetN(), ns3::Object::GetObject(), ns3::NoBackhaulEpcHelper::GetPgwNode(), ns3::Ipv4StaticRoutingHelper::GetStaticRouting(), ns3::NoBackhaulEpcHelper::GetUeDefaultGatewayAddress(), ns3::UniformRandomVariable::GetValue(), ns3::LteHelper::HandoverRequest(), ns3::UdpClientHelper::Install(), ns3::PointToPointHelper::Install(), ns3::PacketSinkHelper::Install(), ns3::InternetStackHelper::Install(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), ns3::EpcTft::PacketFilter::localPortEnd, ns3::EpcTft::PacketFilter::localPortStart, m_admitHo, m_epc, m_epcHelper, m_handoverEventList, m_handoverEventListName, m_lteHelper, m_maxHoDuration, m_nDedicatedBearers, m_nUes, m_schedulerType, m_statsDuration, m_udpClientInterval, m_udpClientPktSize, m_ueDataVector, m_useIdealRrc, ns3::MilliSeconds(), third::mobility, NS_LOG_FUNCTION, ns3::EpcTft::PacketFilter::remotePortEnd, ns3::EpcTft::PacketFilter::remotePortStart, ns3::Config::Reset(), SaveStatsAfterHandover(), ns3::Seconds(), first::serverApps, ns3::ObjectBase::SetAttribute(), ns3::Ipv4AddressHelper::SetBase(), ns3::PointToPointHelper::SetChannelAttribute(), ns3::Config::SetDefault(), ns3::Ipv4StaticRouting::SetDefaultRoute(), ns3::PointToPointHelper::SetDeviceAttribute(), ns3::LteHelper::SetEpcHelper(), ns3::LteHelper::SetHandoverAlgorithmType(), ns3::LteHelper::SetSchedulerType(), ns3::RandomVariableStream::SetStream(), startTime, stopTime, TeleportUeNearTargetEnb(), TeleportUeToMiddle(), and LteX2HandoverTestCase::BearerData::ulSink.
SaveStatsAfterHandover()
void LteX2HandoverTestCase::SaveStatsAfterHandover (uint32_t ueIndex) private
Save stats after handover function.
Parameters
ueIndex the index of the UE
Definition at line 568 of file test-lte-x2-handover.cc.
References m_ueDataVector.
Referenced by DoRun().
TeleportUeNearTargetEnb()
void LteX2HandoverTestCase::TeleportUeNearTargetEnb (Ptr< Node > ueNode, Ptr< Node > enbNode) private
Teleport UE near the target eNB of the handover.
Parameters
ueNode the UE node
enbNode the target eNB node
Definition at line 558 of file test-lte-x2-handover.cc.
References ns3::Object::GetObject(), ns3::MobilityModel::GetPosition(), and ns3::MobilityModel::SetPosition().
Referenced by DoRun().
TeleportUeToMiddle()
void LteX2HandoverTestCase::TeleportUeToMiddle (Ptr< Node > ueNode) private
Teleport UE between both eNBs of the test.
Parameters
ueNode the UE node
Definition at line 551 of file test-lte-x2-handover.cc.
References ns3::Object::GetObject(), and ns3::MobilityModel::SetPosition().
Referenced by DoRun().
Member Data Documentation
m_admitHo
bool LteX2HandoverTestCase::m_admitHo private
whether to admit the handover request
Definition at line 112 of file test-lte-x2-handover.cc.
Referenced by DoRun().
m_epc
bool LteX2HandoverTestCase::m_epc private
whether to use EPC
Definition at line 110 of file test-lte-x2-handover.cc.
Referenced by DoRun().
m_epcHelper
Ptr<PointToPointEpcHelper> LteX2HandoverTestCase::m_epcHelper private
EPC helper.
Definition at line 115 of file test-lte-x2-handover.cc.
Referenced by DoRun().
m_handoverEventList
std::list<HandoverEvent> LteX2HandoverTestCase::m_handoverEventList private
handover event list
Definition at line 108 of file test-lte-x2-handover.cc.
Referenced by DoRun().
m_handoverEventListName
std::string LteX2HandoverTestCase::m_handoverEventListName private
handover event list name
Definition at line 109 of file test-lte-x2-handover.cc.
Referenced by DoRun().
m_lteHelper
Ptr<LteHelper> LteX2HandoverTestCase::m_lteHelper private
LTE helper.
Definition at line 114 of file test-lte-x2-handover.cc.
Referenced by DoRun().
m_maxHoDuration
const Time LteX2HandoverTestCase::m_maxHoDuration private
maximum HO duration
Definition at line 157 of file test-lte-x2-handover.cc.
Referenced by DoRun().
m_nDedicatedBearers
uint32_t LteX2HandoverTestCase::m_nDedicatedBearers private
number of UEs in the test
Definition at line 107 of file test-lte-x2-handover.cc.
Referenced by CheckConnected(), and DoRun().
m_nUes
uint32_t LteX2HandoverTestCase::m_nUes private
number of UEs in the test
Definition at line 106 of file test-lte-x2-handover.cc.
Referenced by DoRun().
m_schedulerType
std::string LteX2HandoverTestCase::m_schedulerType private
scheduler type
Definition at line 111 of file test-lte-x2-handover.cc.
Referenced by DoRun().
m_statsDuration
const Time LteX2HandoverTestCase::m_statsDuration private
stats duration
Definition at line 158 of file test-lte-x2-handover.cc.
Referenced by CheckStatsAWhileAfterHandover(), and DoRun().
m_udpClientInterval
const Time LteX2HandoverTestCase::m_udpClientInterval private
UDP client interval.
Definition at line 159 of file test-lte-x2-handover.cc.
Referenced by CheckStatsAWhileAfterHandover(), and DoRun().
m_udpClientPktSize
const uint32_t LteX2HandoverTestCase::m_udpClientPktSize private
UDP client packet size.
Definition at line 160 of file test-lte-x2-handover.cc.
Referenced by CheckStatsAWhileAfterHandover(), and DoRun().
m_ueDataVector
std::vector<UeData> LteX2HandoverTestCase::m_ueDataVector private
UE data vector.
Definition at line 155 of file test-lte-x2-handover.cc.
Referenced by CheckStatsAWhileAfterHandover(), DoRun(), and SaveStatsAfterHandover().
m_useIdealRrc
bool LteX2HandoverTestCase::m_useIdealRrc private
whether to use the ideal RRC
Definition at line 113 of file test-lte-x2-handover.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/lte/test/test-lte-x2-handover.cc