ns-3: ns3::lorawan::LinearLoraTxCurrentModel Class Reference
ns3::lorawan::LinearLoraTxCurrentModel Class Reference
A linear model of the transmission current for a LoRa device, based on the WiFi model.
#include "lora-tx-current-model.h"
Public Member Functions
LinearLoraTxCurrentModel ()
virtual ~LinearLoraTxCurrentModel ()
double CalcTxCurrent (double txPowerDbm) const
Get the current for transmission at this power.
double GetEta (void) const
double GetStandbyCurrent (void) const
double GetVoltage (void) const
void SetEta (double eta)
void SetStandbyCurrent (double idleCurrent)
void SetVoltage (double voltage)
Public Member Functions inherited from ns3::lorawan::LoraTxCurrentModel
LoraTxCurrentModel ()
virtual ~LoraTxCurrentModel ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::lorawan::LoraTxCurrentModel
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
double m_eta
ETA.
double m_idleCurrent
Standby current.
double m_voltage
Voltage.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A linear model of the transmission current for a LoRa device, based on the WiFi model.
Definition at line 52 of file lora-tx-current-model.h.
Constructor & Destructor Documentation
LinearLoraTxCurrentModel()
ns3::lorawan::LinearLoraTxCurrentModel::LinearLoraTxCurrentModel ()
Definition at line 75 of file lora-tx-current-model.cc.
References NS_LOG_FUNCTION.
~LinearLoraTxCurrentModel()
ns3::lorawan::LinearLoraTxCurrentModel::~LinearLoraTxCurrentModel () virtual
Definition at line 80 of file lora-tx-current-model.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CalcTxCurrent()
double ns3::lorawan::LinearLoraTxCurrentModel::CalcTxCurrent (double txPowerDbm) const virtual
Get the current for transmission at this power.
Parameters
txPowerDbm The nominal tx power in dBm
Returns
The transmit current (in Ampere)
Implements ns3::lorawan::LoraTxCurrentModel.
Definition at line 125 of file lora-tx-current-model.cc.
References ns3::lorawan::DbmToW(), m_eta, m_idleCurrent, m_voltage, and NS_LOG_FUNCTION.
GetEta()
double ns3::lorawan::LinearLoraTxCurrentModel::GetEta (void) const
Returns
the power amplifier efficiency.
Definition at line 107 of file lora-tx-current-model.cc.
References m_eta.
Referenced by GetTypeId().
GetStandbyCurrent()
double ns3::lorawan::LinearLoraTxCurrentModel::GetStandbyCurrent (void) const
Returns
the current in the STANDBY state.
Definition at line 119 of file lora-tx-current-model.cc.
References m_idleCurrent.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::lorawan::LinearLoraTxCurrentModel::GetTypeId (void) static
Definition at line 50 of file lora-tx-current-model.cc.
References GetEta(), GetStandbyCurrent(), GetVoltage(), ns3::MakeDoubleAccessor(), SetEta(), ns3::TypeId::SetParent(), SetStandbyCurrent(), and SetVoltage().
GetVoltage()
double ns3::lorawan::LinearLoraTxCurrentModel::GetVoltage (void) const
Returns
the supply voltage.
Definition at line 113 of file lora-tx-current-model.cc.
References m_voltage.
Referenced by GetTypeId().
SetEta()
void ns3::lorawan::LinearLoraTxCurrentModel::SetEta (double eta)
Parameters
eta (dimension-less)
Set the power amplifier efficiency.
Definition at line 86 of file lora-tx-current-model.cc.
References m_eta, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetStandbyCurrent()
void ns3::lorawan::LinearLoraTxCurrentModel::SetStandbyCurrent (double idleCurrent)
Parameters
idleCurrent (Ampere)
Set the current in the STANDBY state.
Definition at line 100 of file lora-tx-current-model.cc.
References m_idleCurrent, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetVoltage()
void ns3::lorawan::LinearLoraTxCurrentModel::SetVoltage (double voltage)
Parameters
voltage (Volts)
Set the supply voltage.
Definition at line 93 of file lora-tx-current-model.cc.
References m_voltage, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
Member Data Documentation
m_eta
double ns3::lorawan::LinearLoraTxCurrentModel::m_eta private
ETA.
Definition at line 99 of file lora-tx-current-model.h.
Referenced by CalcTxCurrent(), GetEta(), and SetEta().
m_idleCurrent
double ns3::lorawan::LinearLoraTxCurrentModel::m_idleCurrent private
Standby current.
Definition at line 101 of file lora-tx-current-model.h.
Referenced by CalcTxCurrent(), GetStandbyCurrent(), and SetStandbyCurrent().
m_voltage
double ns3::lorawan::LinearLoraTxCurrentModel::m_voltage private
Voltage.
Definition at line 100 of file lora-tx-current-model.h.
Referenced by CalcTxCurrent(), GetVoltage(), and SetVoltage().
The documentation for this class was generated from the following files:
src/lorawan/model/lora-tx-current-model.h
src/lorawan/model/lora-tx-current-model.cc