ns-3: ns3::BandwidthRequestHeader Class Reference
ns3::BandwidthRequestHeader Class Reference
WiMAX Models
#include "wimax-mac-header.h"
Public Types
enum HeaderType { HEADER_TYPE_INCREMENTAL, HEADER_TYPE_AGGREGATE }
Header type enumeration.
Public Member Functions
BandwidthRequestHeader (void)
~BandwidthRequestHeader (void)
bool check_hcs (void) const
Check HCS.
uint32_t Deserialize (Buffer::Iterator start)
uint32_t GetBr (void) const
Get BR field.
Cid GetCid (void) const
Get CID field.
uint8_t GetEc (void) const
Get EC field.
uint8_t GetHcs (void) const
Get HCS field.
uint8_t GetHt (void) const
Get HT field.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
std::string GetName (void) const
Get name field.
uint32_t GetSerializedSize (void) const
uint8_t GetType (void) const
Get type field.
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetBr (uint32_t br)
Set BR field.
void SetCid (Cid cid)
Set CID field.
void SetEc (uint8_t ec)
Set EC field.
void SetHcs (uint8_t hcs)
Set HCS field.
void SetHt (uint8_t ht)
Set HT field.
void SetType (uint8_t type)
Set type field.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t c_hcs
calculated header check sequence; this is used to check if the received header is correct or not
uint32_t m_br
Bandwidth Request.
Cid m_cid
Connection identifier.
uint8_t m_ec
Encryption Control.
uint8_t m_hcs
Header Check Sequence.
uint8_t m_ht
Header type.
uint8_t m_type
type
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class implements the bandwidth-request mac Header as described by IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems 6.3.2.1.2 Bandwidth request header, page 38
Definition at line 251 of file wimax-mac-header.h.
Member Enumeration Documentation
HeaderType
enum ns3::BandwidthRequestHeader::HeaderType
Header type enumeration.
Enumerator
HEADER_TYPE_INCREMENTAL
HEADER_TYPE_AGGREGATE
Definition at line 255 of file wimax-mac-header.h.
Constructor & Destructor Documentation
BandwidthRequestHeader()
ns3::BandwidthRequestHeader::BandwidthRequestHeader (void)
Definition at line 309 of file wimax-mac-header.cc.
~BandwidthRequestHeader()
ns3::BandwidthRequestHeader::~BandwidthRequestHeader (void)
Definition at line 319 of file wimax-mac-header.cc.
Member Function Documentation
check_hcs()
bool ns3::BandwidthRequestHeader::check_hcs (void) const
Check HCS.
Returns
true if HCS is validated
Definition at line 485 of file wimax-mac-header.cc.
References c_hcs, and m_hcs.
Referenced by ns3::BaseStationNetDevice::DoReceive().
Deserialize()
uint32_t ns3::BandwidthRequestHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 448 of file wimax-mac-header.cc.
References c_hcs, ns3::CRC8Calculate(), ns3::Buffer::Iterator::GetDistanceFrom(), m_br, m_cid, m_ec, m_hcs, m_ht, m_type, ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetBr()
uint32_t ns3::BandwidthRequestHeader::GetBr (void) const
Get BR field.
Returns
the BR
Definition at line 368 of file wimax-mac-header.cc.
References m_br.
Referenced by ns3::BandwidthManager::ProcessBandwidthRequest(), and ns3::UplinkSchedulerMBQoS::ProcessBandwidthRequest().
GetCid()
Cid ns3::BandwidthRequestHeader::GetCid (void) const
Get CID field.
Returns
the CID
Definition at line 373 of file wimax-mac-header.cc.
References m_cid.
Referenced by ns3::BaseStationNetDevice::DoReceive(), ns3::BandwidthManager::ProcessBandwidthRequest(), and ns3::UplinkSchedulerMBQoS::ProcessBandwidthRequest().
GetEc()
uint8_t ns3::BandwidthRequestHeader::GetEc (void) const
Get EC field.
Returns
the EC
Definition at line 358 of file wimax-mac-header.cc.
References m_ec.
GetHcs()
uint8_t ns3::BandwidthRequestHeader::GetHcs (void) const
Get HCS field.
Returns
the HCS
Definition at line 378 of file wimax-mac-header.cc.
References m_hcs.
GetHt()
uint8_t ns3::BandwidthRequestHeader::GetHt (void) const
Get HT field.
Returns
the HT
Definition at line 353 of file wimax-mac-header.cc.
References m_ht.
Referenced by ns3::BaseStationNetDevice::DoReceive().
GetInstanceTypeId()
TypeId ns3::BandwidthRequestHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 398 of file wimax-mac-header.cc.
References GetTypeId().
GetName()
std::string ns3::BandwidthRequestHeader::GetName (void) const
Get name field.
Returns
the name
Definition at line 383 of file wimax-mac-header.cc.
GetSerializedSize()
uint32_t ns3::BandwidthRequestHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 411 of file wimax-mac-header.cc.
GetType()
uint8_t ns3::BandwidthRequestHeader::GetType (void) const
Get type field.
Returns
the type
Definition at line 363 of file wimax-mac-header.cc.
References m_type.
Referenced by ns3::BandwidthManager::ProcessBandwidthRequest().
GetTypeId()
TypeId ns3::BandwidthRequestHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 388 of file wimax-mac-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::BandwidthRequestHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 403 of file wimax-mac-header.cc.
References ns3::Cid::GetIdentifier(), m_br, m_cid, m_ec, m_hcs, and m_type.
Serialize()
void ns3::BandwidthRequestHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 419 of file wimax-mac-header.cc.
References ns3::CRC8Calculate(), ns3::Cid::GetIdentifier(), m_br, m_cid, m_ec, m_ht, m_type, visualizer.core::start(), and ns3::Buffer::Iterator::WriteU8().
SetBr()
void ns3::BandwidthRequestHeader::SetBr (uint32_t br)
Set BR field.
Parameters
br the BR
Definition at line 338 of file wimax-mac-header.cc.
References m_br.
Referenced by ns3::BandwidthManager::SendBandwidthRequest().
SetCid()
void ns3::BandwidthRequestHeader::SetCid (Cid cid)
Set CID field.
Parameters
cid the CID
Definition at line 343 of file wimax-mac-header.cc.
References m_cid.
Referenced by ns3::BandwidthManager::SendBandwidthRequest().
SetEc()
void ns3::BandwidthRequestHeader::SetEc (uint8_t ec)
Set EC field.
Parameters
ec the EC
Definition at line 328 of file wimax-mac-header.cc.
References m_ec.
SetHcs()
void ns3::BandwidthRequestHeader::SetHcs (uint8_t hcs)
Set HCS field.
Parameters
hcs the HCS
Definition at line 348 of file wimax-mac-header.cc.
References m_hcs.
SetHt()
void ns3::BandwidthRequestHeader::SetHt (uint8_t ht)
Set HT field.
Parameters
ht the HT
Definition at line 323 of file wimax-mac-header.cc.
References m_ht.
SetType()
void ns3::BandwidthRequestHeader::SetType (uint8_t type)
Set type field.
Parameters
type the type
Definition at line 333 of file wimax-mac-header.cc.
References m_type.
Referenced by ns3::BandwidthManager::SendBandwidthRequest().
Member Data Documentation
c_hcs
uint8_t ns3::BandwidthRequestHeader::c_hcs private
calculated header check sequence; this is used to check if the received header is correct or not
Definition at line 352 of file wimax-mac-header.h.
Referenced by check_hcs(), and Deserialize().
m_br
uint32_t ns3::BandwidthRequestHeader::m_br private
Bandwidth Request.
Definition at line 349 of file wimax-mac-header.h.
Referenced by Deserialize(), GetBr(), Print(), Serialize(), and SetBr().
m_cid
Cid ns3::BandwidthRequestHeader::m_cid private
Connection identifier.
Definition at line 350 of file wimax-mac-header.h.
Referenced by Deserialize(), GetCid(), Print(), Serialize(), and SetCid().
m_ec
uint8_t ns3::BandwidthRequestHeader::m_ec private
Encryption Control.
Definition at line 347 of file wimax-mac-header.h.
Referenced by Deserialize(), GetEc(), Print(), Serialize(), and SetEc().
m_hcs
uint8_t ns3::BandwidthRequestHeader::m_hcs private
Header Check Sequence.
Definition at line 351 of file wimax-mac-header.h.
Referenced by check_hcs(), Deserialize(), GetHcs(), Print(), and SetHcs().
m_ht
uint8_t ns3::BandwidthRequestHeader::m_ht private
Header type.
Definition at line 346 of file wimax-mac-header.h.
Referenced by Deserialize(), GetHt(), Serialize(), and SetHt().
m_type
uint8_t ns3::BandwidthRequestHeader::m_type private
type
Definition at line 348 of file wimax-mac-header.h.
Referenced by Deserialize(), GetType(), Print(), Serialize(), and SetType().
The documentation for this class was generated from the following files:
src/wimax/model/wimax-mac-header.h
src/wimax/model/wimax-mac-header.cc