ns-3: LteDownlinkPowerControlRrcConnectionReconfigurationTestCase Class Reference
LteDownlinkPowerControlRrcConnectionReconfigurationTestCase Class Reference
LTE Models » lte module tests | Test suites
Test if RRC connection reconfiguration messages are properly generated upon the change in the downlink power.
#include "lte-test-downlink-power-control.h"
Public Member Functions
LteDownlinkPowerControlRrcConnectionReconfigurationTestCase (bool useIdealRrc, std::string name)
Constructor.
virtual ~LteDownlinkPowerControlRrcConnectionReconfigurationTestCase ()
void ChangePdschConfigDedicated (uint16_t rnti, uint8_t pa)
Change PDSCH config dedicated.
void ConnectionReconfigurationEnb (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
Connection Reconfiguration ENB.
void ConnectionReconfigurationUe (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
Connection Reconfiguration UE.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
bool m_changePdschConfigDedicatedTriggered
change PDSCH config dedicated triggered?
bool m_connectionReconfigurationEnbCompleted
connection reconfiguration ENB completed?
bool m_connectionReconfigurationUeReceived
connection reconfiguration UE received?
bool m_useIdealRrc
use ideal RRC?
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test if RRC connection reconfiguration messages are properly generated upon the change in the downlink power.
Definition at line 128 of file lte-test-downlink-power-control.h.
Constructor & Destructor Documentation
LteDownlinkPowerControlRrcConnectionReconfigurationTestCase()
LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::LteDownlinkPowerControlRrcConnectionReconfigurationTestCase (bool useIdealRrc, std::string name)
Constructor.
Parameters
useIdealRrc if true use ideal RRC
name the reference name
Definition at line 496 of file lte-test-downlink-power-control.cc.
~LteDownlinkPowerControlRrcConnectionReconfigurationTestCase()
LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::~LteDownlinkPowerControlRrcConnectionReconfigurationTestCase () virtual
Definition at line 506 of file lte-test-downlink-power-control.cc.
Member Function Documentation
ChangePdschConfigDedicated()
void LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::ChangePdschConfigDedicated (uint16_t rnti, uint8_t pa)
Change PDSCH config dedicated.
Parameters
rnti the RNTI
pa the PA
Definition at line 531 of file lte-test-downlink-power-control.cc.
References m_changePdschConfigDedicatedTriggered, and NS_LOG_DEBUG.
Referenced by ChangePdschConfigDedicatedCallback().
ConnectionReconfigurationEnb()
void LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::ConnectionReconfigurationEnb (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
Connection Reconfiguration ENB.
Parameters
context the context name
imsi the IMSI
cellid the cell ID
rnti the RNTI
Definition at line 511 of file lte-test-downlink-power-control.cc.
References m_connectionReconfigurationEnbCompleted, ns3::MilliSeconds(), ns3::Now(), and NS_LOG_DEBUG.
Referenced by NotifyConnectionReconfigurationEnb().
ConnectionReconfigurationUe()
void LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::ConnectionReconfigurationUe (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
Connection Reconfiguration UE.
Parameters
context the context name
imsi the IMSI
cellid the cell ID
rnti the RNTI
Definition at line 521 of file lte-test-downlink-power-control.cc.
References m_connectionReconfigurationUeReceived, ns3::MilliSeconds(), ns3::Now(), and NS_LOG_DEBUG.
Referenced by NotifyConnectionReconfigurationUe().
DoRun()
void LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Simulation Topology
Implements ns3::TestCase.
Definition at line 538 of file lte-test-downlink-power-control.cc.
References ns3::LteHelper::ActivateDataRadioBearer(), ns3::LteHelper::Attach(), ns3::LteFfrSimple::ChangePdschConfigDedicated(), ChangePdschConfigDedicatedCallback(), ns3::Config::Connect(), ns3::NodeContainer::Create(), ns3::NetDeviceContainer::Get(), ns3::PointerValue::GetObject(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), m_changePdschConfigDedicatedTriggered, m_connectionReconfigurationEnbCompleted, m_connectionReconfigurationUeReceived, m_useIdealRrc, ns3::MakeBoundCallback(), third::mobility, NotifyConnectionReconfigurationEnb(), NotifyConnectionReconfigurationUe(), NS_TEST_ASSERT_MSG_EQ, ns3::LteRrcSap::PdschConfigDedicated::pa, ns3::Config::Reset(), ns3::Seconds(), ns3::Config::SetDefault(), ns3::LteHelper::SetFfrAlgorithmType(), ns3::LteFfrSimple::SetPdschConfigDedicated(), and ns3::LteHelper::SetSchedulerType().
Member Data Documentation
m_changePdschConfigDedicatedTriggered
bool LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::m_changePdschConfigDedicatedTriggered private
change PDSCH config dedicated triggered?
Definition at line 171 of file lte-test-downlink-power-control.h.
Referenced by ChangePdschConfigDedicated(), and DoRun().
m_connectionReconfigurationEnbCompleted
bool LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::m_connectionReconfigurationEnbCompleted private
connection reconfiguration ENB completed?
Definition at line 173 of file lte-test-downlink-power-control.h.
Referenced by ConnectionReconfigurationEnb(), and DoRun().
m_connectionReconfigurationUeReceived
bool LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::m_connectionReconfigurationUeReceived private
connection reconfiguration UE received?
Definition at line 172 of file lte-test-downlink-power-control.h.
Referenced by ConnectionReconfigurationUe(), and DoRun().
m_useIdealRrc
bool LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::m_useIdealRrc private
use ideal RRC?
Definition at line 169 of file lte-test-downlink-power-control.h.
Referenced by DoRun().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-downlink-power-control.h
src/lte/test/lte-test-downlink-power-control.cc