ns-3: Ipv4DeduplicationPerformanceTest Class Reference
Ipv4DeduplicationPerformanceTest Class Reference
Internet » internet module tests | Test suites
IPv4 Deduplication Performance Test.
Public Member Functions
Ipv4DeduplicationPerformanceTest (void)
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void DoSendData (Ptr< Socket > socket, Address to, uint8_t socketIndex)
Private Attributes
std::vector< Ptr< Socket > > m_sockets
uint8_t m_target
std::vector< uint8_t > m_txPackets
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
IPv4 Deduplication Performance Test.
This test case sets up a fully connected network of 10 nodes. Each node transmits 2 packets / second for about 20 seconds. Packets are relayed from every receiver. The test outputs the number of events that have been processed during the course of the simulation. Test runtime is also a metric.
The de-duplication cache entry expiration algorithm has evolved from an event-per-expiry (EPE) algorithm to a periodic event, batch purge (PBP) algorithm. The current metrics are taken from tests on the development box. Periodic batch purge period defaults to 1s.
   Events        Runtime
EVE 656140 29s PBP 337420 29s
Definition at line 529 of file ipv4-deduplication-test.cc.
Constructor & Destructor Documentation
Ipv4DeduplicationPerformanceTest()
Ipv4DeduplicationPerformanceTest::Ipv4DeduplicationPerformanceTest (void)
Definition at line 541 of file ipv4-deduplication-test.cc.
References m_target.
Member Function Documentation
DoRun()
void Ipv4DeduplicationPerformanceTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 548 of file ipv4-deduplication-test.cc.
References ns3::Ipv4ListRoutingHelper::Add(), ns3::Ipv4StaticRoutingHelper::AddMulticastRoute(), ns3::Ipv4AddressHelper::Assign(), ns3::SocketFactory::CreateSocket(), first::devices, DoSendData(), ns3::Ipv4StaticRoutingHelper::GetStaticRouting(), ns3::UniformRandomVariable::GetValue(), ns3::SimpleNetDeviceHelper::Install(), ns3::InternetStackHelper::Install(), m_sockets, m_txPackets, first::nodes, NS_ASSERT_MSG(), NS_LOG_UNCOND, ns3::Seconds(), ns3::Ipv4AddressHelper::SetBase(), ns3::Config::SetDefault(), ns3::InternetStackHelper::SetIpv4ArpJitter(), ns3::InternetStackHelper::SetIpv6StackInstall(), and ns3::InternetStackHelper::SetRoutingHelper().
DoSendData()
void Ipv4DeduplicationPerformanceTest::DoSendData (Ptr< Socket > socket, Address to, uint8_t socketIndex) private
Definition at line 628 of file ipv4-deduplication-test.cc.
References m_sockets, m_target, m_txPackets, ns3::Seconds(), and ns3::Socket::SendTo().
Referenced by DoRun().
Member Data Documentation
m_sockets
std::vector<Ptr<Socket> > Ipv4DeduplicationPerformanceTest::m_sockets private
Definition at line 535 of file ipv4-deduplication-test.cc.
Referenced by DoRun(), and DoSendData().
m_target
uint8_t Ipv4DeduplicationPerformanceTest::m_target private
Definition at line 537 of file ipv4-deduplication-test.cc.
Referenced by Ipv4DeduplicationPerformanceTest(), and DoSendData().
m_txPackets
std::vector<uint8_t> Ipv4DeduplicationPerformanceTest::m_txPackets private
Definition at line 536 of file ipv4-deduplication-test.cc.
Referenced by DoRun(), and DoSendData().
The documentation for this class was generated from the following file:
src/internet/test/ipv4-deduplication-test.cc