ns-3: ns3::AthstatsWifiTraceSink Class Reference
ns3::AthstatsWifiTraceSink Class Reference
trace sink for wifi device that mimics madwifi's athstats tool.
#include "athstats-helper.h"
Public Member Functions
AthstatsWifiTraceSink ()
virtual ~AthstatsWifiTraceSink ()
void DevRxTrace (std::string context, Ptr< const Packet > p)
function to be called when the net device receives a packet
void DevTxTrace (std::string context, Ptr< const Packet > p)
function to be called when the net device transmits a packet
void Open (std::string const &name)
Open a file for output.
void PhyRxErrorTrace (std::string context, Ptr< const Packet > packet, double snr)
Function to be called when a frame reception by the PHY layer of the considered device resulted in an error due to a failure in the CRC check of the frame.
void PhyRxOkTrace (std::string context, Ptr< const Packet > packet, double snr, WifiMode mode, WifiPreamble preamble)
Function to be called when the PHY layer of the considered device receives a frame.
void PhyStateTrace (std::string context, Time start, Time duration, WifiPhyState state)
Function to be called when the PHY layer of the considered device changes state.
void PhyTxTrace (std::string context, Ptr< const Packet > packet, WifiMode mode, WifiPreamble preamble, uint8_t txPower)
Function to be called when a frame is being transmitted by the PHY layer of the considered device.
void TxDataFailedTrace (std::string context, Mac48Address address)
Function to be called when a data frame transmission by the considered device has failed.
void TxFinalDataFailedTrace (std::string context, Mac48Address address)
Function to be called when the transmission of a data frame has exceeded the retry limit.
void TxFinalRtsFailedTrace (std::string context, Mac48Address address)
Function to be called when the transmission of a RTS frame has exceeded the retry limit.
void TxRtsFailedTrace (std::string context, Mac48Address address)
Function to be called when a RTS frame transmission by the considered device has failed.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void ResetCounters ()
Reset counters function.
void WriteStats ()
Write status function.
Private Attributes
uint32_t m_exceededRetryCount
exceeded retry count
Time m_interval
interval
uint32_t m_longRetryCount
long retry count
uint32_t m_phyRxErrorCount
PHY receive error count.
uint32_t m_phyRxOkCount
PHY receive OK count.
uint32_t m_phyTxCount
PHY transmit count.
uint32_t m_rxCount
receive count
uint32_t m_shortRetryCount
short retry count
uint32_t m_txCount
transmit count
std::ofstream * m_writer
output stream
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
trace sink for wifi device that mimics madwifi's athstats tool.
The AthstatsWifiTraceSink class is a trace sink to be connected to several of the traces available within a wifi device. The purpose of AthstatsWifiTraceSink is to mimic the behavior of the athstats tool distributed with the madwifi driver. In particular, the reproduced behavior is that obtained when executing athstats without parameters: a report written in text format is produced every fixed interval, based on the events observed by the wifi device.
Differences with the "real" athstats:
AthstatsWifiTraceSink is expected to write its output to a file (not to stdout).
only a subset of the metrics supported by athstats is supported by AthstatsWifiTraceSink
AthstatsWifiTraceSink does never produce a cumulative report.
Definition at line 95 of file athstats-helper.h.
Constructor & Destructor Documentation
AthstatsWifiTraceSink()
ns3::AthstatsWifiTraceSink::AthstatsWifiTraceSink ()
Definition at line 119 of file athstats-helper.cc.
References ns3::Simulator::ScheduleNow(), and WriteStats().
~AthstatsWifiTraceSink()
ns3::AthstatsWifiTraceSink::~AthstatsWifiTraceSink () virtual
Definition at line 133 of file athstats-helper.cc.
References m_writer, NS_LOG_FUNCTION, and NS_LOG_LOGIC().
Member Function Documentation
DevRxTrace()
void ns3::AthstatsWifiTraceSink::DevRxTrace (std::string context, Ptr< const Packet > p)
function to be called when the net device receives a packet
Parameters
context the calling context
p the packet being received
Definition at line 179 of file athstats-helper.cc.
References m_rxCount, and NS_LOG_FUNCTION.
Referenced by ns3::AthstatsHelper::EnableAthstats().
DevTxTrace()
void ns3::AthstatsWifiTraceSink::DevTxTrace (std::string context, Ptr< const Packet > p)
function to be called when the net device transmits a packet
Parameters
context the calling context
p the packet being transmitted
Definition at line 172 of file athstats-helper.cc.
References m_txCount, and NS_LOG_FUNCTION.
Referenced by ns3::AthstatsHelper::EnableAthstats().
GetTypeId()
TypeId ns3::AthstatsWifiTraceSink::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 104 of file athstats-helper.cc.
References m_interval, ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::Seconds(), and ns3::TypeId::SetParent().
Open()
void ns3::AthstatsWifiTraceSink::Open (std::string const & name)
Open a file for output.
Parameters
name the name of the file to be opened.
Definition at line 241 of file athstats-helper.cc.
References m_writer, NS_ABORT_MSG_IF, NS_ABORT_MSG_UNLESS, NS_ASSERT_MSG(), NS_LOG_FUNCTION, and NS_LOG_LOGIC().
PhyRxErrorTrace()
void ns3::AthstatsWifiTraceSink::PhyRxErrorTrace (std::string context, Ptr< const Packet > packet, double snr)
Function to be called when a frame reception by the PHY layer of the considered device resulted in an error due to a failure in the CRC check of the frame.
Parameters
context the calling context
packet the packet
snr the SNR in linear scale
Definition at line 221 of file athstats-helper.cc.
References m_phyRxErrorCount, and NS_LOG_FUNCTION.
Referenced by ns3::AthstatsHelper::EnableAthstats().
PhyRxOkTrace()
void ns3::AthstatsWifiTraceSink::PhyRxOkTrace (std::string context, Ptr< const Packet > packet, double snr, WifiMode mode, WifiPreamble preamble)
Function to be called when the PHY layer of the considered device receives a frame.
Parameters
context the calling context
packet the packet
snr the SNR in linear scale
mode the WifiMode
preamble the wifi preamble
Definition at line 214 of file athstats-helper.cc.
References m_phyRxOkCount, and NS_LOG_FUNCTION.
Referenced by ns3::AthstatsHelper::EnableAthstats().
PhyStateTrace()
void ns3::AthstatsWifiTraceSink::PhyStateTrace (std::string context, Time start, Time duration, WifiPhyState state)
Function to be called when the PHY layer of the considered device changes state.
Parameters
context the calling context
start the time at which the state changed
duration the duration of the state
state the PHY layer state
Definition at line 235 of file athstats-helper.cc.
References aloha::duration, NS_LOG_FUNCTION, and visualizer.core::start().
Referenced by ns3::AthstatsHelper::EnableAthstats().
PhyTxTrace()
void ns3::AthstatsWifiTraceSink::PhyTxTrace (std::string context, Ptr< const Packet > packet, WifiMode mode, WifiPreamble preamble, uint8_t txPower)
Function to be called when a frame is being transmitted by the PHY layer of the considered device.
Parameters
context the calling context
packet the packet
mode the WifiMode
preamble the wifi preamble
txPower the transmit power level
Definition at line 228 of file athstats-helper.cc.
References m_phyTxCount, and NS_LOG_FUNCTION.
Referenced by ns3::AthstatsHelper::EnableAthstats().
ResetCounters()
void ns3::AthstatsWifiTraceSink::ResetCounters () private
Reset counters function.
Definition at line 159 of file athstats-helper.cc.
References m_exceededRetryCount, m_longRetryCount, m_phyRxErrorCount, m_phyRxOkCount, m_phyTxCount, m_rxCount, m_shortRetryCount, and m_txCount.
Referenced by WriteStats().
TxDataFailedTrace()
void ns3::AthstatsWifiTraceSink::TxDataFailedTrace (std::string context, Mac48Address address)
Function to be called when a data frame transmission by the considered device has failed.
Parameters
context the calling context
address the MAC address of the remote station
Definition at line 193 of file athstats-helper.cc.
References first::address, m_longRetryCount, and NS_LOG_FUNCTION.
Referenced by ns3::AthstatsHelper::EnableAthstats().
TxFinalDataFailedTrace()
void ns3::AthstatsWifiTraceSink::TxFinalDataFailedTrace (std::string context, Mac48Address address)
Function to be called when the transmission of a data frame has exceeded the retry limit.
Parameters
context the calling context
address the MAC address of the remote station
Definition at line 207 of file athstats-helper.cc.
References first::address, m_exceededRetryCount, and NS_LOG_FUNCTION.
Referenced by ns3::AthstatsHelper::EnableAthstats().
TxFinalRtsFailedTrace()
void ns3::AthstatsWifiTraceSink::TxFinalRtsFailedTrace (std::string context, Mac48Address address)
Function to be called when the transmission of a RTS frame has exceeded the retry limit.
Parameters
context the calling context
address the MAC address of the remote station
Definition at line 200 of file athstats-helper.cc.
References first::address, m_exceededRetryCount, and NS_LOG_FUNCTION.
Referenced by ns3::AthstatsHelper::EnableAthstats().
TxRtsFailedTrace()
void ns3::AthstatsWifiTraceSink::TxRtsFailedTrace (std::string context, Mac48Address address)
Function to be called when a RTS frame transmission by the considered device has failed.
Parameters
context the calling context
address the MAC address of the remote station
Definition at line 186 of file athstats-helper.cc.
References first::address, m_shortRetryCount, and NS_LOG_FUNCTION.
Referenced by ns3::AthstatsHelper::EnableAthstats().
WriteStats()
void ns3::AthstatsWifiTraceSink::WriteStats () private
Write status function.
Definition at line 260 of file athstats-helper.cc.
References m_exceededRetryCount, m_interval, m_longRetryCount, m_phyRxErrorCount, m_rxCount, m_shortRetryCount, m_txCount, m_writer, NS_LOG_FUNCTION, ResetCounters(), and ns3::Simulator::Schedule().
Referenced by AthstatsWifiTraceSink().
Member Data Documentation
m_exceededRetryCount
uint32_t ns3::AthstatsWifiTraceSink::m_exceededRetryCount private
exceeded retry count
Definition at line 222 of file athstats-helper.h.
Referenced by ResetCounters(), TxFinalDataFailedTrace(), TxFinalRtsFailedTrace(), and WriteStats().
m_interval
Time ns3::AthstatsWifiTraceSink::m_interval private
interval
Definition at line 229 of file athstats-helper.h.
Referenced by GetTypeId(), and WriteStats().
m_longRetryCount
uint32_t ns3::AthstatsWifiTraceSink::m_longRetryCount private
long retry count
Definition at line 221 of file athstats-helper.h.
Referenced by ResetCounters(), TxDataFailedTrace(), and WriteStats().
m_phyRxErrorCount
uint32_t ns3::AthstatsWifiTraceSink::m_phyRxErrorCount private
PHY receive error count.
Definition at line 224 of file athstats-helper.h.
Referenced by PhyRxErrorTrace(), ResetCounters(), and WriteStats().
m_phyRxOkCount
uint32_t ns3::AthstatsWifiTraceSink::m_phyRxOkCount private
PHY receive OK count.
Definition at line 223 of file athstats-helper.h.
Referenced by PhyRxOkTrace(), and ResetCounters().
m_phyTxCount
uint32_t ns3::AthstatsWifiTraceSink::m_phyTxCount private
PHY transmit count.
Definition at line 225 of file athstats-helper.h.
Referenced by PhyTxTrace(), and ResetCounters().
m_rxCount
uint32_t ns3::AthstatsWifiTraceSink::m_rxCount private
receive count
Definition at line 219 of file athstats-helper.h.
Referenced by DevRxTrace(), ResetCounters(), and WriteStats().
m_shortRetryCount
uint32_t ns3::AthstatsWifiTraceSink::m_shortRetryCount private
short retry count
Definition at line 220 of file athstats-helper.h.
Referenced by ResetCounters(), TxRtsFailedTrace(), and WriteStats().
m_txCount
uint32_t ns3::AthstatsWifiTraceSink::m_txCount private
transmit count
Definition at line 218 of file athstats-helper.h.
Referenced by DevTxTrace(), ResetCounters(), and WriteStats().
m_writer
std::ofstream* ns3::AthstatsWifiTraceSink::m_writer private
output stream
Definition at line 227 of file athstats-helper.h.
Referenced by ~AthstatsWifiTraceSink(), Open(), and WriteStats().
The documentation for this class was generated from the following files:
src/wifi/helper/athstats-helper.h
src/wifi/helper/athstats-helper.cc