ns-3: ns3::SocketFactory Class Reference
ns3::SocketFactory Class Reference abstract
Network » Socket
Object to create transport layer instances that provide a socket API to applications.
#include "socket-factory.h"
Public Member Functions
SocketFactory ()
virtual Ptr< Socket > CreateSocket (void)=0
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Object to create transport layer instances that provide a socket API to applications.
This base class defines the API for creating sockets. The socket factory also can hold the global variables used to initialize newly created sockets, such as values that are set through the sysctl or proc interfaces in Linux.
If you want to write a new transport protocol accessible through sockets, you need to subclass this factory class, implement CreateSocket, instantiate the object, and aggregate it to the node.
See also
Udp
UdpImpl
Definition at line 48 of file socket-factory.h.
Constructor & Destructor Documentation
SocketFactory()
ns3::SocketFactory::SocketFactory ()
Definition at line 37 of file socket-factory.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CreateSocket()
virtual Ptr<Socket> ns3::SocketFactory::CreateSocket (void) pure virtual
Returns
smart pointer to Socket
Base class method for creating socket instances.
Implemented in ns3::PacketSocketFactory, ns3::UdpSocketFactoryImpl, ns3::TcpSocketFactoryImpl, ns3::NscTcpSocketFactoryImpl, ns3::Ipv4RawSocketFactoryImpl, and ns3::Ipv6RawSocketFactoryImpl.
Referenced by Ipv4DeduplicationTest::DoRun(), Ipv4DeduplicationPerformanceTest::DoRun(), Ipv4ForwardingTest::DoRun(), Ipv4GlobalRoutingSlash32TestCase::DoRun(), Ipv4HeaderTest::DoRun(), Ipv4PacketInfoTagTest::DoRun(), Ipv4RawSocketImplTest::DoRun(), Ipv4RipTest::DoRun(), Ipv4RipCountToInfinityTest::DoRun(), Ipv4RipSplitHorizonStrategyTest::DoRun(), Ipv4StaticRoutingSlash32TestCase::DoRun(), Ipv6ForwardingTest::DoRun(), Ipv6PacketInfoTagTest::DoRun(), Ipv6RawSocketImplTest::DoRun(), Ipv6RipngTest::DoRun(), Ipv6RipngCountToInfinityTest::DoRun(), Ipv6RipngSplitHorizonStrategyTest::DoRun(), UdpSocketLoopbackTest::DoRun(), Udp6SocketLoopbackTest::DoRun(), UdpSocketImplTest::DoRun(), Udp6SocketImplTest::DoRun(), SixlowpanHc1ImplTest::DoRun(), SixlowpanIphcImplTest::DoRun(), TcpTestCase::SetupDefaultSim(), TcpTestCase::SetupDefaultSim6(), DualStackTestCase::SetUpSim(), Sender::StartApplication(), and Receiver::StartApplication().
GetTypeId()
TypeId ns3::SocketFactory::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 29 of file socket-factory.cc.
References ns3::TypeId::SetParent().
The documentation for this class was generated from the following files:
src/network/model/socket-factory.h
src/network/model/socket-factory.cc