ns-3: TcpFastRetrTest Class Reference
TcpFastRetrTest Class Reference
Internet » internet module tests | Test suites
Test the fast retransmission.
Public Member Functions
TcpFastRetrTest (TypeId congControl, uint32_t seqToKill, const std::string &msg)
Constructor.
virtual Ptr< ErrorModel > CreateReceiverErrorModel ()
Create and return the error model to install in the receiver node.
virtual Ptr< ErrorModel > CreateSenderErrorModel ()
Create and return the error model to install in the sender node.
virtual Ptr< TcpSocketMsgBase > CreateSenderSocket (Ptr< Node > node)
Create and install the socket to install on the sender.
Public Member Functions inherited from ns3::TcpGeneralTest
TcpGeneralTest (const std::string &desc)
TcpGeneralTest constructor.
~TcpGeneralTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Member Functions
virtual void AfterRTOExpired (const Ptr< const TcpSocketState > tcb, SocketWho who)
Rto has expired.
virtual void ConfigureEnvironment ()
Change the configuration of the environment.
virtual void ConfigureProperties ()
Change the configuration of the socket properties.
virtual void CongStateTrace (const TcpSocketState::TcpCongState_t oldValue, const TcpSocketState::TcpCongState_t newValue)
State on Ack state machine changes.
virtual void FinalChecks ()
Performs the (eventual) final checks through test asserts.
void PktDropped (const Ipv4Header &ipH, const TcpHeader &tcpH, Ptr< const Packet > p)
Check if the packet being dropped is the right one.
virtual void ProcessedAck (const Ptr< const TcpSocketState > tcb, const TcpHeader &h, SocketWho who)
Processed ack.
virtual void RcvAck (const Ptr< const TcpSocketState > tcb, const TcpHeader &h, SocketWho who)
Received ack.
virtual void Rx (const Ptr< const Packet > p, const TcpHeader &h, SocketWho who)
Packet received from IP layer.
virtual void Tx (const Ptr< const Packet > p, const TcpHeader &h, SocketWho who)
Packet transmitted down to IP layer.
Protected Member Functions inherited from ns3::TcpGeneralTest
virtual void BeforeRTOExpired (const Ptr< const TcpSocketState > tcb, SocketWho who)
Rto has expired.
virtual void BytesInFlightTrace (uint32_t oldValue, uint32_t newValue)
Bytes in flight changes.
virtual Ptr< SimpleChannel > CreateChannel ()
Create and return the channel installed between the two socket.
virtual Ptr< TcpSocketMsgBase > CreateReceiverSocket (Ptr< Node > node)
Create and install the socket to install on the receiver.
virtual Ptr< TcpSocketMsgBase > CreateSocket (Ptr< Node > node, TypeId socketType, TypeId congControl)
Create a socket.
virtual Ptr< TcpSocketMsgBase > CreateSocket (Ptr< Node > node, TypeId socketType, TypeId congControl, TypeId recoveryAlgorithm)
Create a socket.
virtual void CWndInflTrace (uint32_t oldValue, uint32_t newValue)
Tracks the inflated congestion window changes.
virtual void CWndTrace (uint32_t oldValue, uint32_t newValue)
Tracks the congestion window changes.
virtual void DataSent (uint32_t size, SocketWho who)
Notifying application for sent data.
void DoConnect ()
Scheduled at 0.0, SENDER starts the connection to RECEIVER.
virtual void DoRun (void)
Execute the tcp test.
virtual void DoTeardown (void)
Teardown the TCP test.
virtual void ErrorClose (SocketWho who)
Socket closed with an error.
Time GetClockGranularity (SocketWho who)
Get the clock granularity attribute.
Time GetConnTimeout (SocketWho who)
Get the retransmission time for the SYN segments.
uint32_t GetDelAckCount (SocketWho who)
Get the number of delayed ack (if present)
Time GetDelAckTimeout (SocketWho who)
Get the timeout of delayed ack (if present)
uint32_t GetDupAckCount (SocketWho who)
Get the number of dupack received.
SequenceNumber32 GetHighestTxMark (SocketWho who)
Get the highest tx mark of the node specified.
uint32_t GetInitialCwnd (SocketWho who)
Get the initial congestion window.
uint32_t GetInitialSsThresh (SocketWho who)
Get the initial slow start threshold.
Time GetMinRto (SocketWho who)
Get the minimum RTO attribute.
uint32_t GetMtu () const
Get the MTU of the environment.
EventId GetPersistentEvent (SocketWho who)
Get the persistent event of the selected socket.
Time GetPersistentTimeout (SocketWho who)
Get the persistent timeout of the selected socket.
uint32_t GetPktCount () const
Get the number of application packets.
Time GetPktInterval () const
Get the interval to wait for each packet sent down from application to TCP.
uint32_t GetPktSize () const
Get the application packet size.
Time GetPropagationDelay () const
Get the channel Propagation Delay.
Ptr< TcpSocketMsgBase > GetReceiverSocket ()
Get the pointer to a previously created receiver socket.
uint32_t GetReTxThreshold (SocketWho who)
Get the retransmission threshold.
Time GetRto (SocketWho who)
Get the retransmission time.
Ptr< RttEstimator > GetRttEstimator (SocketWho who)
Get the Rtt estimator of the socket.
uint32_t GetRWnd (SocketWho who)
Get the rWnd of the selected socket.
Ptr< TcpRxBuffer > GetRxBuffer (SocketWho who)
Get the Rx buffer from selected socket.
uint32_t GetSegSize (SocketWho who)
Get the segment size of the node specified.
Ptr< TcpSocketMsgBase > GetSenderSocket ()
Get the pointer to a previously created sender socket.
Time GetStartTime () const
Get the data start time.
Ptr< TcpSocketState > GetTcb (SocketWho who)
Get the TCB from selected socket.
TcpSocket::TcpStates_t GetTcpState (SocketWho who)
Get the state of the TCP state machine.
Ptr< TcpTxBuffer > GetTxBuffer (SocketWho who)
Get the Tx buffer from selected socket.
virtual void HighestTxSeqTrace (SequenceNumber32 oldValue, SequenceNumber32 newValue)
Highest tx seq changes.
virtual void NextTxSeqTrace (SequenceNumber32 oldValue, SequenceNumber32 newValue)
Next tx seq changes.
virtual void NormalClose (SocketWho who)
Socket closed normally.
virtual void PhyDrop (SocketWho who)
Link drop.
virtual void QueueDrop (SocketWho who)
Drop on the queue.
virtual void RateSampleUpdatedTrace (const TcpRateLinux::TcpRateSample &sample)
Track the rate sample value of TcpRateLinux.
virtual void RateUpdatedTrace (const TcpRateLinux::TcpRateConnection &rate)
Track the rate value of TcpRateLinux.
virtual void ReceivePacket (Ptr< Socket > socket)
Packet received.
virtual void RtoTrace (Time oldValue, Time newValue)
RTO changes.
virtual void RttTrace (Time oldTime, Time newTime)
Rtt changes.
void SendPacket (Ptr< Socket > socket, uint32_t pktSize, uint32_t pktCount, Time pktInterval)
Send packets to other endpoint.
void SetAppPktCount (uint32_t pktCount)
Set app packet count.
void SetAppPktInterval (Time pktInterval)
Interval between app-generated packet.
void SetAppPktSize (uint32_t pktSize)
Set app packet size.
void SetCongestionControl (TypeId congControl)
Congestion control of the sender socket.
void SetInitialCwnd (SocketWho who, uint32_t initialCwnd)
Forcefully set the initial cwnd.
void SetInitialSsThresh (SocketWho who, uint32_t initialSsThresh)
Forcefully set the initial ssth.
void SetMTU (uint32_t mtu)
MTU of the bottleneck link.
void SetPropagationDelay (Time propDelay)
Propagation delay of the bottleneck link.
void SetRcvBufSize (SocketWho who, uint32_t size)
Forcefully set a defined size for rx buffer.
void SetRecoveryAlgorithm (TypeId reccovery)
recovery algorithm of the sender socket
void SetSegmentSize (SocketWho who, uint32_t segmentSize)
Forcefully set the segment size.
void SetTransmitStart (Time startTime)
Set the initial time at which the application sends the first data packet.
void SetUseEcn (SocketWho who, TcpSocketState::UseEcn_t useEcn)
Forcefully set the ecn use on.
virtual void SsThreshTrace (uint32_t oldValue, uint32_t newValue)
Slow start threshold changes.
virtual void UpdatedRttHistory (const SequenceNumber32 &seq, uint32_t sz, bool isRetransmission, SocketWho who)
Updated the Rtt history.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Protected Attributes
uint32_t m_bytesRcvButNotAcked
Number of bytes received but not acked.
uint32_t m_countRetr
Retry counter.
uint32_t m_dupAckReceived
DipACk received.
Ptr< TcpSeqErrorModel > m_errorModel
Error model.
bool m_pktDropped
The packet has been dropped.
bool m_pktWasDropped
The packet was dropped (according to the receiver).
SequenceNumber32 m_previousAck
Previous ACK received.
SequenceNumber32 m_rcvNextExpAck
Receiver next expected sequence number.
uint32_t m_seqToKill
Sequence number to drop.
SequenceNumber32 m_sndNextExpSeq
Sender next expected sequence number.
Protected Attributes inherited from ns3::TcpGeneralTest
TypeId m_congControlTypeId
Congestion control.
TypeId m_recoveryTypeId
Recovery.
Additional Inherited Members
Public Types inherited from ns3::TcpGeneralTest
enum SocketWho { SENDER, RECEIVER }
Used as parameter of methods, specifies on what node the caller is interested (e.g.
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Detailed Description
Test the fast retransmission.
Checking what is happening is not so easy, so there are a lot of variables which helps to keep track on what is happening. The idea is following sequence and ack numbers which are exchanged, testing if they are the same as the implementation transmits.
Definition at line 41 of file tcp-fast-retr-test.cc.
Constructor & Destructor Documentation
TcpFastRetrTest()
TcpFastRetrTest::TcpFastRetrTest (TypeId congControl, uint32_t seqToKill, const std::string & msg)
Constructor.
Parameters
congControl Type of congestion control.
seqToKill Sequence number of the packet to drop.
msg Test message.
Definition at line 99 of file tcp-fast-retr-test.cc.
References ns3::TcpGeneralTest::m_congControlTypeId.
Member Function Documentation
AfterRTOExpired()
void TcpFastRetrTest::AfterRTOExpired (const Ptr< const TcpSocketState > tcb, SocketWho who) protected virtual
Rto has expired.
Parameters
tcb Transmission control block
who where the RTO has expired (SENDER or RECEIVER)
Reimplemented from ns3::TcpGeneralTest.
Definition at line 376 of file tcp-fast-retr-test.cc.
References NS_ASSERT_MSG().
ConfigureEnvironment()
void TcpFastRetrTest::ConfigureEnvironment () protected virtual
Change the configuration of the environment.
Reimplemented from ns3::TcpGeneralTest.
Definition at line 122 of file tcp-fast-retr-test.cc.
References ns3::TcpGeneralTest::SetAppPktCount().
ConfigureProperties()
void TcpFastRetrTest::ConfigureProperties () protected virtual
Change the configuration of the socket properties.
Reimplemented from ns3::TcpGeneralTest.
Definition at line 115 of file tcp-fast-retr-test.cc.
References ns3::TcpGeneralTest::SENDER, and ns3::TcpGeneralTest::SetInitialSsThresh().
CongStateTrace()
void TcpFastRetrTest::CongStateTrace (const TcpSocketState::TcpCongState_t oldValue, const TcpSocketState::TcpCongState_t newValue) protected virtual
State on Ack state machine changes.
Parameters
oldValue old value
newValue new value
Reimplemented from ns3::TcpGeneralTest.
Definition at line 382 of file tcp-fast-retr-test.cc.
References ns3::TcpGeneralTest::GetDupAckCount(), ns3::TcpGeneralTest::GetReTxThreshold(), NS_LOG_FUNCTION, NS_TEST_ASSERT_MSG_EQ, and ns3::TcpGeneralTest::SENDER.
CreateReceiverErrorModel()
Ptr< ErrorModel > TcpFastRetrTest::CreateReceiverErrorModel () virtual
Create and return the error model to install in the receiver node.
Returns
receiver error model
Reimplemented from ns3::TcpGeneralTest.
Definition at line 135 of file tcp-fast-retr-test.cc.
References ns3::TcpSeqErrorModel::AddSeqToKill(), m_errorModel, m_seqToKill, ns3::MakeCallback(), PktDropped(), and ns3::TcpGeneralErrorModel::SetDropCallback().
CreateSenderErrorModel()
Ptr< ErrorModel > TcpFastRetrTest::CreateSenderErrorModel () virtual
Create and return the error model to install in the sender node.
Returns
sender error model
Reimplemented from ns3::TcpGeneralTest.
Definition at line 129 of file tcp-fast-retr-test.cc.
CreateSenderSocket()
Ptr< TcpSocketMsgBase > TcpFastRetrTest::CreateSenderSocket (Ptr< Node > node) virtual
Create and install the socket to install on the sender.
Parameters
node sender node pointer
Returns
the socket to be installed in the sender
Reimplemented from ns3::TcpGeneralTest.
Definition at line 146 of file tcp-fast-retr-test.cc.
References ns3::Seconds(), and ns3::ObjectBase::SetAttribute().
FinalChecks()
void TcpFastRetrTest::FinalChecks () protected virtual
Performs the (eventual) final checks through test asserts.
Reimplemented from ns3::TcpGeneralTest.
Definition at line 420 of file tcp-fast-retr-test.cc.
References ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::GetValue(), m_countRetr, m_pktWasDropped, m_rcvNextExpAck, and NS_TEST_ASSERT_MSG_EQ.
PktDropped()
void TcpFastRetrTest::PktDropped (const Ipv4Header & ipH, const TcpHeader & tcpH, Ptr< const Packet > p) protected
Check if the packet being dropped is the right one.
Parameters
ipH IPv4 header.
tcpH TCP header.
p The packet.
Definition at line 408 of file tcp-fast-retr-test.cc.
References ns3::TcpHeader::GetSequenceNumber(), m_pktDropped, m_rcvNextExpAck, m_seqToKill, NS_LOG_FUNCTION, and NS_TEST_ASSERT_MSG_EQ.
Referenced by CreateReceiverErrorModel().
ProcessedAck()
void TcpFastRetrTest::ProcessedAck (const Ptr< const TcpSocketState > tcb, const TcpHeader & h, SocketWho who) protected virtual
Processed ack.
Invoked after the processing of the ACK
Parameters
tcb Transmission Control Block
h the header of segment
who the socket which has processed the ACK (SENDER or RECEIVER)
Reimplemented from ns3::TcpGeneralTest.
Definition at line 333 of file tcp-fast-retr-test.cc.
References ns3::TcpHeader::GetAckNumber(), ns3::GetCongStateFrom(), ns3::TcpGeneralTest::GetDupAckCount(), ns3::TcpGeneralTest::GetReTxThreshold(), ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::GetValue(), m_dupAckReceived, m_pktWasDropped, m_previousAck, NS_LOG_FUNCTION, NS_TEST_ASSERT_MSG_EQ, NS_TEST_ASSERT_MSG_GT_OR_EQ, ns3::TcpGeneralTest::RECEIVER, and ns3::TcpGeneralTest::SENDER.
RcvAck()
void TcpFastRetrTest::RcvAck (const Ptr< const TcpSocketState > tcb, const TcpHeader & h, SocketWho who) protected virtual
Received ack.
Invoked when an ACK is received (no processing is done yet)
Parameters
tcb Transmission Control Block
h the header of segment
who the socket which has received the ACK (SENDER or RECEIVER)
Reimplemented from ns3::TcpGeneralTest.
Definition at line 287 of file tcp-fast-retr-test.cc.
References ns3::TcpHeader::GetAckNumber(), ns3::GetCongStateFrom(), ns3::TcpGeneralTest::GetDupAckCount(), ns3::TcpGeneralTest::GetReTxThreshold(), ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::GetValue(), m_dupAckReceived, m_seqToKill, NS_LOG_FUNCTION, NS_TEST_ASSERT_MSG_EQ, ns3::TcpGeneralTest::RECEIVER, and ns3::TcpGeneralTest::SENDER.
Rx()
void TcpFastRetrTest::Rx (const Ptr< const Packet > p, const TcpHeader & h, SocketWho who) protected virtual
Packet received from IP layer.
Parameters
p packet
h header
who the socket which has received the packet (SENDER or RECEIVER)
Reimplemented from ns3::TcpGeneralTest.
Definition at line 155 of file tcp-fast-retr-test.cc.
References ns3::TcpGeneralTest::GetSegSize(), ns3::TcpHeader::GetSequenceNumber(), ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::GetValue(), m_bytesRcvButNotAcked, m_pktDropped, m_rcvNextExpAck, m_seqToKill, NS_LOG_INFO, ns3::TcpGeneralTest::RECEIVER, and ns3::TcpGeneralTest::SENDER.
Tx()
void TcpFastRetrTest::Tx (const Ptr< const Packet > p, const TcpHeader & h, SocketWho who) protected virtual
Packet transmitted down to IP layer.
Parameters
p packet
h header
who the socket which has received the packet (SENDER or RECEIVER)
Reimplemented from ns3::TcpGeneralTest.
Definition at line 186 of file tcp-fast-retr-test.cc.
References ns3::TcpHeader::GetAckNumber(), ns3::TcpGeneralTest::GetDelAckCount(), ns3::TcpHeader::GetFlags(), ns3::TcpGeneralTest::GetSegSize(), ns3::TcpHeader::GetSequenceNumber(), ns3::Packet::GetSize(), ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::GetValue(), m_countRetr, m_pktDropped, m_rcvNextExpAck, m_seqToKill, m_sndNextExpSeq, NS_LOG_INFO, NS_TEST_ASSERT_MSG_EQ, ns3::TcpGeneralTest::RECEIVER, and ns3::TcpGeneralTest::SENDER.
Member Data Documentation
m_bytesRcvButNotAcked
uint32_t TcpFastRetrTest::m_bytesRcvButNotAcked protected
Number of bytes received but not acked.
Definition at line 94 of file tcp-fast-retr-test.cc.
Referenced by Rx().
m_countRetr
uint32_t TcpFastRetrTest::m_countRetr protected
Retry counter.
Definition at line 92 of file tcp-fast-retr-test.cc.
Referenced by FinalChecks(), and Tx().
m_dupAckReceived
uint32_t TcpFastRetrTest::m_dupAckReceived protected
DipACk received.
Definition at line 86 of file tcp-fast-retr-test.cc.
Referenced by ProcessedAck(), and RcvAck().
m_errorModel
Ptr<TcpSeqErrorModel> TcpFastRetrTest::m_errorModel protected
Error model.
Definition at line 96 of file tcp-fast-retr-test.cc.
Referenced by CreateReceiverErrorModel().
m_pktDropped
bool TcpFastRetrTest::m_pktDropped protected
The packet has been dropped.
Definition at line 83 of file tcp-fast-retr-test.cc.
Referenced by PktDropped(), Rx(), and Tx().
m_pktWasDropped
bool TcpFastRetrTest::m_pktWasDropped protected
The packet was dropped (according to the receiver).
Definition at line 84 of file tcp-fast-retr-test.cc.
Referenced by FinalChecks(), and ProcessedAck().
m_previousAck
SequenceNumber32 TcpFastRetrTest::m_previousAck protected
Previous ACK received.
Definition at line 88 of file tcp-fast-retr-test.cc.
Referenced by ProcessedAck().
m_rcvNextExpAck
SequenceNumber32 TcpFastRetrTest::m_rcvNextExpAck protected
Receiver next expected sequence number.
Definition at line 90 of file tcp-fast-retr-test.cc.
Referenced by FinalChecks(), PktDropped(), Rx(), and Tx().
m_seqToKill
uint32_t TcpFastRetrTest::m_seqToKill protected
Sequence number to drop.
Definition at line 85 of file tcp-fast-retr-test.cc.
Referenced by CreateReceiverErrorModel(), PktDropped(), RcvAck(), Rx(), and Tx().
m_sndNextExpSeq
SequenceNumber32 TcpFastRetrTest::m_sndNextExpSeq protected
Sender next expected sequence number.
Definition at line 89 of file tcp-fast-retr-test.cc.
Referenced by Tx().
The documentation for this class was generated from the following file:
src/internet/test/tcp-fast-retr-test.cc