ns-3: TcpVegasTest Class Reference
TcpVegasTest Class Reference
TcpVegas congestion control algorithm test.
Public Member Functions
TcpVegasTest (uint32_t cWnd, uint32_t segmentSize, uint32_t ssThresh, Time rtt, uint32_t segmentsAcked, SequenceNumber32 nextTxSeq, SequenceNumber32 lastAckedSeq, const std::string &name)
Constructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void GetSsThresh (Ptr< TcpVegas > cong)
brief Get and check the SSH threshold.
void IncreaseWindow (Ptr< TcpVegas > cong)
Increases the TCP window.
Private Attributes
uint32_t m_cWnd
Congestion window.
SequenceNumber32 m_lastAckedSeq
Last ACKed sequence number.
SequenceNumber32 m_nextTxSeq
Next Tx sequence number.
Time m_rtt
RTT.
uint32_t m_segmentsAcked
Number of segments ACKed.
uint32_t m_segmentSize
Segment size.
uint32_t m_ssThresh
Slow Start Threshold.
Ptr< TcpSocketState > m_state
TCP socket state.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
TcpVegas congestion control algorithm test.
Definition at line 40 of file tcp-vegas-test.cc.
Constructor & Destructor Documentation
TcpVegasTest()
TcpVegasTest::TcpVegasTest (uint32_t cWnd, uint32_t segmentSize, uint32_t ssThresh, Time rtt, uint32_t segmentsAcked, SequenceNumber32 nextTxSeq, SequenceNumber32 lastAckedSeq, const std::string & name)
Constructor.
Parameters
cWnd Congestion window.
segmentSize Segment size.
ssThresh Slow Start Threshold.
rtt The RTT.
segmentsAcked Number of segments ACKed.
nextTxSeq Next Tx sequence number.
lastAckedSeq Last ACKed sequence number.
name Test description.
Definition at line 87 of file tcp-vegas-test.cc.
Member Function Documentation
DoRun()
void TcpVegasTest::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 107 of file tcp-vegas-test.cc.
References ns3::TcpVegas::CongestionStateSet(), ns3::TracedValue< T >::Get(), ns3::TcpVegas::IncreaseWindow(), IncreaseWindow(), ns3::TcpSocketState::m_cWnd, m_cWnd, ns3::TcpSocketState::m_lastAckedSeq, m_lastAckedSeq, ns3::TcpSocketState::m_minRtt, m_nextTxSeq, ns3::TcpSocketState::m_nextTxSequence, m_rtt, m_segmentsAcked, ns3::TcpSocketState::m_segmentSize, m_segmentSize, ns3::TcpSocketState::m_ssThresh, m_ssThresh, m_state, ns3::MilliSeconds(), NS_TEST_ASSERT_MSG_EQ, and ns3::TcpVegas::PktsAcked().
GetSsThresh()
void TcpVegasTest::GetSsThresh (Ptr< TcpVegas > cong) private
brief Get and check the SSH threshold.
Parameters
cong The congestion control.
Definition at line 196 of file tcp-vegas-test.cc.
References m_cWnd, m_segmentSize, m_ssThresh, max, and min.
Referenced by IncreaseWindow().
IncreaseWindow()
void TcpVegasTest::IncreaseWindow (Ptr< TcpVegas > cong) private
Increases the TCP window.
Parameters
cong The congestion control.
Definition at line 144 of file tcp-vegas-test.cc.
References sample-rng-plot::alpha, ns3::UintegerValue::Get(), ns3::ObjectBase::GetAttribute(), ns3::Time::GetMilliSeconds(), GetSsThresh(), m_cWnd, m_rtt, m_segmentsAcked, m_segmentSize, m_ssThresh, max, ns3::MilliSeconds(), and min.
Referenced by DoRun().
Member Data Documentation
m_cWnd
uint32_t TcpVegasTest::m_cWnd private
Congestion window.
Definition at line 76 of file tcp-vegas-test.cc.
Referenced by DoRun(), GetSsThresh(), and IncreaseWindow().
m_lastAckedSeq
SequenceNumber32 TcpVegasTest::m_lastAckedSeq private
Last ACKed sequence number.
Definition at line 82 of file tcp-vegas-test.cc.
Referenced by DoRun().
m_nextTxSeq
SequenceNumber32 TcpVegasTest::m_nextTxSeq private
Next Tx sequence number.
Definition at line 81 of file tcp-vegas-test.cc.
Referenced by DoRun().
m_rtt
Time TcpVegasTest::m_rtt private
RTT.
Definition at line 79 of file tcp-vegas-test.cc.
Referenced by DoRun(), and IncreaseWindow().
m_segmentsAcked
uint32_t TcpVegasTest::m_segmentsAcked private
Number of segments ACKed.
Definition at line 80 of file tcp-vegas-test.cc.
Referenced by DoRun(), and IncreaseWindow().
m_segmentSize
uint32_t TcpVegasTest::m_segmentSize private
Segment size.
Definition at line 77 of file tcp-vegas-test.cc.
Referenced by DoRun(), GetSsThresh(), and IncreaseWindow().
m_ssThresh
uint32_t TcpVegasTest::m_ssThresh private
Slow Start Threshold.
Definition at line 78 of file tcp-vegas-test.cc.
Referenced by DoRun(), GetSsThresh(), and IncreaseWindow().
m_state
Ptr<TcpSocketState> TcpVegasTest::m_state private
TCP socket state.
Definition at line 84 of file tcp-vegas-test.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/internet/test/tcp-vegas-test.cc