ns-3: ns3::LogDistancePropagationLossModel Class Reference
ns3::LogDistancePropagationLossModel Class Reference
Propagation Models
a log distance propagation model.
#include "propagation-loss-model.h"
Public Member Functions
LogDistancePropagationLossModel ()
double GetPathLossExponent (void) const
void SetPathLossExponent (double n)
void SetReference (double referenceDistance, double referenceLoss)
Set the reference path loss at a given distance.
Public Member Functions inherited from ns3::PropagationLossModel
PropagationLossModel ()
virtual ~PropagationLossModel ()
int64_t AssignStreams (int64_t stream)
If this loss model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
double CalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account all the PropagationLossModel(s) chained to the current one.
Ptr< PropagationLossModel > GetNext ()
Gets the next PropagationLossModel in the chain of loss models that act on the signal.
void SetNext (Ptr< PropagationLossModel > next)
Enables a chain of loss models to act on the signal.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::PropagationLossModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
LogDistancePropagationLossModel (const LogDistancePropagationLossModel &)
Copy constructor.
virtual int64_t DoAssignStreams (int64_t stream)
Subclasses must implement this; those not using random variables can return zero.
virtual double DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account only the particular PropagationLossModel.
LogDistancePropagationLossModel & operator= (const LogDistancePropagationLossModel &)
Copy constructor.
Static Private Member Functions
static Ptr< PropagationLossModel > CreateDefaultReference (void)
Creates a default reference loss model.
Private Attributes
double m_exponent
model exponent
double m_referenceDistance
reference distance
double m_referenceLoss
reference loss
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
a log distance propagation model.
This model calculates the reception power with a so-called log-distance propagation model:
where:
: the path loss distance exponent
: reference distance (m)
: path loss at reference distance (dB)
: distance (m)
: path loss (dB)
When the path loss is requested at a distance smaller than the reference distance, the tx power is returned.
Definition at line 487 of file propagation-loss-model.h.
Constructor & Destructor Documentation
LogDistancePropagationLossModel() [1/2]
ns3::LogDistancePropagationLossModel::LogDistancePropagationLossModel ()
Definition at line 485 of file propagation-loss-model.cc.
LogDistancePropagationLossModel() [2/2]
ns3::LogDistancePropagationLossModel::LogDistancePropagationLossModel (const LogDistancePropagationLossModel &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Member Function Documentation
CreateDefaultReference()
static Ptr<PropagationLossModel> ns3::LogDistancePropagationLossModel::CreateDefaultReference (void) static private
Creates a default reference loss model.
Returns
a default reference loss model
DoAssignStreams()
int64_t ns3::LogDistancePropagationLossModel::DoAssignStreams (int64_t stream) private virtual
Subclasses must implement this; those not using random variables can return zero.
Implements ns3::PropagationLossModel.
Definition at line 538 of file propagation-loss-model.cc.
DoCalcRxPower()
double ns3::LogDistancePropagationLossModel::DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const private virtual
Returns the Rx Power taking into account only the particular PropagationLossModel.
Parameters
txPowerDbm current transmission power (in dBm)
a the mobility model of the source
b the mobility model of the destination
Returns
the reception power after adding/multiplying propagation loss (in dBm)
The formula is: rx = 10 * log (Pr0(tx)) - n * 10 * log (d/d0)
Pr0: rx power at reference distance d0 (W) d0: reference distance: 1.0 (m) d: distance (m) tx: tx power (dB) rx: dB
Which, in our case is:
rx = rx0(tx) - 10 * n * log (d/d0)
Implements ns3::PropagationLossModel.
Definition at line 507 of file propagation-loss-model.cc.
References ns3::MobilityModel::GetDistanceFrom(), m_exponent, m_referenceDistance, m_referenceLoss, and NS_LOG_DEBUG.
GetPathLossExponent()
double ns3::LogDistancePropagationLossModel::GetPathLossExponent (void) const
Returns
the current path loss exponent.
Definition at line 501 of file propagation-loss-model.cc.
References m_exponent.
GetTypeId()
TypeId ns3::LogDistancePropagationLossModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 459 of file propagation-loss-model.cc.
References m_exponent, m_referenceDistance, m_referenceLoss, ns3::MakeDoubleAccessor(), and ns3::TypeId::SetParent().
operator=()
LogDistancePropagationLossModel& ns3::LogDistancePropagationLossModel::operator= (const LogDistancePropagationLossModel &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Returns
SetPathLossExponent()
void ns3::LogDistancePropagationLossModel::SetPathLossExponent (double n)
Parameters
n the path loss exponent. Set the path loss exponent.
Definition at line 490 of file propagation-loss-model.cc.
References m_exponent, and sample-rng-plot::n.
Referenced by LrWpanCcaTestCase::DoRun(), and PhyConnectivityTest::Reset().
SetReference()
void ns3::LogDistancePropagationLossModel::SetReference (double referenceDistance, double referenceLoss)
Set the reference path loss at a given distance.
Parameters
referenceDistance reference distance
referenceLoss reference path loss
Definition at line 495 of file propagation-loss-model.cc.
References m_referenceDistance, and m_referenceLoss.
Referenced by LrWpanCcaTestCase::DoRun(), and PhyConnectivityTest::Reset().
Member Data Documentation
m_exponent
double ns3::LogDistancePropagationLossModel::m_exponent private
model exponent
Definition at line 540 of file propagation-loss-model.h.
Referenced by DoCalcRxPower(), GetPathLossExponent(), GetTypeId(), and SetPathLossExponent().
m_referenceDistance
double ns3::LogDistancePropagationLossModel::m_referenceDistance private
reference distance
Definition at line 541 of file propagation-loss-model.h.
Referenced by DoCalcRxPower(), GetTypeId(), and SetReference().
m_referenceLoss
double ns3::LogDistancePropagationLossModel::m_referenceLoss private
reference loss
Definition at line 542 of file propagation-loss-model.h.
Referenced by DoCalcRxPower(), GetTypeId(), and SetReference().
The documentation for this class was generated from the following files:
src/propagation/model/propagation-loss-model.h
src/propagation/model/propagation-loss-model.cc