ns-3: FlameRtableTest Class Reference
FlameRtableTest Class Reference
Mesh Device » mesh module tests » flame sub-module tests | Test suites
Unit test for FlameRtable.
Public Member Functions
FlameRtableTest ()
void DoRun ()
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void TestAddPath ()
Test add path and try to lookup after entry has expired.
void TestExpire ()
Test add path and try to lookup after entry has expired.
void TestLookup ()
Test Add apth and lookup path;.
Private Attributes
uint8_t cost
cost
Mac48Address dst
destination address
Mac48Address hop
hop address
uint32_t iface
interface
uint16_t seqnum
sequence number
Ptr< FlameRtable > table
table
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Unit test for FlameRtable.
Definition at line 69 of file flame-test-suite.cc.
Constructor & Destructor Documentation
FlameRtableTest()
FlameRtableTest::FlameRtableTest ()
Definition at line 96 of file flame-test-suite.cc.
Member Function Documentation
DoRun()
void FlameRtableTest::DoRun () virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 130 of file flame-test-suite.cc.
References ns3::Seconds(), table, TestAddPath(), TestExpire(), and TestLookup().
TestAddPath()
void FlameRtableTest::TestAddPath () private
Test add path and try to lookup after entry has expired.
Definition at line 116 of file flame-test-suite.cc.
References ns3::flame::FlameRtable::AddPath(), cost, dst, hop, iface, seqnum, and table.
Referenced by DoRun().
TestExpire()
void FlameRtableTest::TestExpire () private
Test add path and try to lookup after entry has expired.
Definition at line 122 of file flame-test-suite.cc.
References cost, dst, hop, iface, ns3::flame::FlameRtable::LookupResult::IsValid(), ns3::flame::FlameRtable::Lookup(), NS_TEST_EXPECT_MSG_EQ, seqnum, and table.
Referenced by DoRun().
TestLookup()
void FlameRtableTest::TestLookup () private
Test Add apth and lookup path;.
Definition at line 107 of file flame-test-suite.cc.
References ns3::flame::FlameRtable::AddPath(), cost, dst, hop, iface, ns3::flame::FlameRtable::Lookup(), NS_TEST_EXPECT_MSG_EQ, seqnum, and table.
Referenced by DoRun().
Member Data Documentation
cost
uint8_t FlameRtableTest::cost private
cost
Definition at line 88 of file flame-test-suite.cc.
Referenced by TestAddPath(), TestExpire(), and TestLookup().
dst
Mac48Address FlameRtableTest::dst private
destination address
Definition at line 85 of file flame-test-suite.cc.
Referenced by check-style.PatchChunk::dst_len(), TestAddPath(), TestExpire(), and TestLookup().
hop
Mac48Address FlameRtableTest::hop private
hop address
Definition at line 86 of file flame-test-suite.cc.
Referenced by TestAddPath(), TestExpire(), and TestLookup().
iface
uint32_t FlameRtableTest::iface private
interface
Definition at line 87 of file flame-test-suite.cc.
Referenced by TestAddPath(), TestExpire(), and TestLookup().
seqnum
uint16_t FlameRtableTest::seqnum private
sequence number
Definition at line 89 of file flame-test-suite.cc.
Referenced by TestAddPath(), TestExpire(), and TestLookup().
table
Ptr<FlameRtable> FlameRtableTest::table private
table
Definition at line 90 of file flame-test-suite.cc.
Referenced by DoRun(), TestAddPath(), TestExpire(), and TestLookup().
The documentation for this class was generated from the following file:
src/mesh/test/flame/flame-test-suite.cc