ns-3: ns3::EpcX2LoadInformationHeader Class Reference
ns3::EpcX2LoadInformationHeader Class Reference
EpcX2LoadInformationHeader.
#include "epc-x2-header.h"
Public Member Functions
EpcX2LoadInformationHeader ()
virtual ~EpcX2LoadInformationHeader ()
virtual uint32_t Deserialize (Buffer::Iterator start)
std::vector< EpcX2Sap::CellInformationItem > GetCellInformationList () const
Get cell information list function.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint32_t GetLengthOfIes () const
Get length of IEs function.
uint32_t GetNumberOfIes () const
Get number of IEs function.
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetCellInformationList (std::vector< EpcX2Sap::CellInformationItem > cellInformationList)
Set cell information list function.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
std::vector< EpcX2Sap::CellInformationItem > m_cellInformationList
cell information list
uint32_t m_headerLength
length of IEs
uint32_t m_numberOfIes
number of IEs
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
EpcX2LoadInformationHeader.
Definition at line 534 of file epc-x2-header.h.
Constructor & Destructor Documentation
EpcX2LoadInformationHeader()
ns3::EpcX2LoadInformationHeader::EpcX2LoadInformationHeader ()
Definition at line 1092 of file epc-x2-header.cc.
References m_cellInformationList.
~EpcX2LoadInformationHeader()
ns3::EpcX2LoadInformationHeader::~EpcX2LoadInformationHeader () virtual
Definition at line 1099 of file epc-x2-header.cc.
References m_cellInformationList, m_headerLength, and m_numberOfIes.
Member Function Documentation
Deserialize()
uint32_t ns3::EpcX2LoadInformationHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 1189 of file epc-x2-header.cc.
References ns3::EpcX2Sap::RelativeNarrowbandTxBand::antennaPorts, GetSerializedSize(), m_cellInformationList, m_headerLength, m_numberOfIes, ns3::EpcX2Sap::RelativeNarrowbandTxBand::pB, ns3::EpcX2Sap::RelativeNarrowbandTxBand::pdcchInterferenceImpact, ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadU8(), ns3::EpcX2Sap::CellInformationItem::relativeNarrowbandTxBand, ns3::EpcX2Sap::RelativeNarrowbandTxBand::rntpPerPrbList, ns3::EpcX2Sap::RelativeNarrowbandTxBand::rntpThreshold, ns3::EpcX2Sap::CellInformationItem::sourceCellId, visualizer.core::start(), ns3::EpcX2Sap::UlHighInterferenceInformationItem::targetCellId, ns3::EpcX2Sap::UlHighInterferenceInformationItem::ulHighInterferenceIndicationList, ns3::EpcX2Sap::CellInformationItem::ulHighInterferenceInformationList, and ns3::EpcX2Sap::CellInformationItem::ulInterferenceOverloadIndicationList.
GetCellInformationList()
std::vector< EpcX2Sap::CellInformationItem > ns3::EpcX2LoadInformationHeader::GetCellInformationList () const
Get cell information list function.
Returns
std::vector <EpcX2Sap::CellInformationItem>
Definition at line 1264 of file epc-x2-header.cc.
References m_cellInformationList.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
GetInstanceTypeId()
TypeId ns3::EpcX2LoadInformationHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 1118 of file epc-x2-header.cc.
References GetTypeId().
GetLengthOfIes()
uint32_t ns3::EpcX2LoadInformationHeader::GetLengthOfIes () const
Get length of IEs function.
Returns
the length of IEs
Definition at line 1302 of file epc-x2-header.cc.
References m_headerLength.
Referenced by ns3::EpcX2::DoSendLoadInformation().
GetNumberOfIes()
uint32_t ns3::EpcX2LoadInformationHeader::GetNumberOfIes () const
Get number of IEs function.
Returns
the number of IEs
Definition at line 1308 of file epc-x2-header.cc.
References m_numberOfIes.
Referenced by ns3::EpcX2::DoSendLoadInformation().
GetSerializedSize()
uint32_t ns3::EpcX2LoadInformationHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 1124 of file epc-x2-header.cc.
References m_headerLength.
Referenced by Deserialize().
GetTypeId()
TypeId ns3::EpcX2LoadInformationHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 1107 of file epc-x2-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::EpcX2LoadInformationHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 1258 of file epc-x2-header.cc.
References m_cellInformationList.
Serialize()
void ns3::EpcX2LoadInformationHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 1130 of file epc-x2-header.cc.
References m_cellInformationList, visualizer.core::start(), ns3::Buffer::Iterator::WriteHtonU16(), and ns3::Buffer::Iterator::WriteU8().
SetCellInformationList()
void ns3::EpcX2LoadInformationHeader::SetCellInformationList (std::vector< EpcX2Sap::CellInformationItem > cellInformationList)
Set cell information list function.
Parameters
cellInformationList std::vector <EpcX2Sap::CellInformationItem>
Definition at line 1270 of file epc-x2-header.cc.
References m_cellInformationList, and m_headerLength.
Referenced by ns3::EpcX2::DoSendLoadInformation().
Member Data Documentation
m_cellInformationList
std::vector<EpcX2Sap::CellInformationItem> ns3::EpcX2LoadInformationHeader::m_cellInformationList private
cell information list
Definition at line 578 of file epc-x2-header.h.
Referenced by EpcX2LoadInformationHeader(), ~EpcX2LoadInformationHeader(), Deserialize(), GetCellInformationList(), Print(), Serialize(), and SetCellInformationList().
m_headerLength
uint32_t ns3::EpcX2LoadInformationHeader::m_headerLength private
length of IEs
Definition at line 576 of file epc-x2-header.h.
Referenced by ~EpcX2LoadInformationHeader(), Deserialize(), GetLengthOfIes(), GetSerializedSize(), and SetCellInformationList().
m_numberOfIes
uint32_t ns3::EpcX2LoadInformationHeader::m_numberOfIes private
number of IEs
Definition at line 575 of file epc-x2-header.h.
Referenced by ~EpcX2LoadInformationHeader(), Deserialize(), and GetNumberOfIes().
The documentation for this class was generated from the following files:
src/lte/model/epc-x2-header.h
src/lte/model/epc-x2-header.cc