ns-3: TimerStateTestCase Class Reference
TimerStateTestCase Class Reference
Public Member Functions
TimerStateTestCase ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 41 of file timer-test-suite.cc.
Constructor & Destructor Documentation
TimerStateTestCase()
TimerStateTestCase::TimerStateTestCase ()
Definition at line 48 of file timer-test-suite.cc.
Member Function Documentation
DoRun()
void TimerStateTestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 52 of file timer-test-suite.cc.
References anonymous_namespace{timer-test-suite.cc}::bari(), ns3::Timer::Cancel(), ns3::Timer::GetState(), ns3::Timer::IsExpired(), ns3::Timer::IsRunning(), ns3::Timer::IsSuspended(), NS_TEST_ASSERT_MSG_EQ, ns3::Timer::Resume(), ns3::Timer::Schedule(), ns3::Seconds(), ns3::Timer::SetArguments(), ns3::Timer::SetDelay(), ns3::Timer::SetFunction(), and ns3::Timer::Suspend().
The documentation for this class was generated from the following file:
src/core/test/timer-test-suite.cc