ns-3: ns3::LinearWifiTxCurrentModel Class Reference
ns3::LinearWifiTxCurrentModel Class Reference
Energy Models
a linear model of the Wifi transmit current
#include "wifi-tx-current-model.h"
Public Member Functions
LinearWifiTxCurrentModel ()
virtual ~LinearWifiTxCurrentModel ()
double CalcTxCurrent (double txPowerDbm) const
Public Member Functions inherited from ns3::WifiTxCurrentModel
WifiTxCurrentModel ()
virtual ~WifiTxCurrentModel ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::WifiTxCurrentModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
double m_eta
ETA.
double m_idleCurrent
idle current in Amperes
double m_voltage
voltage in Volts
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
a linear model of the Wifi transmit current
This model assumes that the transmit current is a linear function of the nominal transmit power used to send the frame. In particular, the power absorbed during the transmission of a frame is given by the power absorbed by the power amplifier plus the power absorbed by the RF subsystem. The latter is assumed to be the same as the power absorbed in the IDLE state .
The efficiency of the power amplifier is given by , where is the output power, i.e., the nominal transmit power. Hence,
It turns out that . By dividing both sides by the supply voltage : , where and are, respectively, the transmit current and the idle current.
For more information, refer to: Francesco Ivan Di Piazza, Stefano Mangione, and Ilenia Tinnirello. "On the Effects of Transmit Power Control on the Energy Consumption of WiFi Network Cards", Proceedings of ICST QShine 2009, pp. 463–475
If the TX current corresponding to a given nominal transmit power is known, the efficiency of the power amplifier is given by the above formula:
Definition at line 84 of file wifi-tx-current-model.h.
Constructor & Destructor Documentation
LinearWifiTxCurrentModel()
ns3::LinearWifiTxCurrentModel::LinearWifiTxCurrentModel ()
Definition at line 75 of file wifi-tx-current-model.cc.
References NS_LOG_FUNCTION.
~LinearWifiTxCurrentModel()
ns3::LinearWifiTxCurrentModel::~LinearWifiTxCurrentModel () virtual
Definition at line 80 of file wifi-tx-current-model.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CalcTxCurrent()
double ns3::LinearWifiTxCurrentModel::CalcTxCurrent (double txPowerDbm) const virtual
Parameters
txPowerDbm the nominal TX power in dBm
Returns
the transmit current (in Ampere)
Implements ns3::WifiTxCurrentModel.
Definition at line 86 of file wifi-tx-current-model.cc.
References ns3::DbmToW(), m_eta, m_idleCurrent, m_voltage, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::LinearWifiTxCurrentModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 53 of file wifi-tx-current-model.cc.
References m_eta, m_idleCurrent, m_voltage, ns3::MakeDoubleAccessor(), and ns3::TypeId::SetParent().
Member Data Documentation
m_eta
double ns3::LinearWifiTxCurrentModel::m_eta private
ETA.
Definition at line 100 of file wifi-tx-current-model.h.
Referenced by CalcTxCurrent(), and GetTypeId().
m_idleCurrent
double ns3::LinearWifiTxCurrentModel::m_idleCurrent private
idle current in Amperes
Definition at line 102 of file wifi-tx-current-model.h.
Referenced by CalcTxCurrent(), and GetTypeId().
m_voltage
double ns3::LinearWifiTxCurrentModel::m_voltage private
voltage in Volts
Definition at line 101 of file wifi-tx-current-model.h.
Referenced by CalcTxCurrent(), and GetTypeId().
The documentation for this class was generated from the following files:
src/wifi/model/wifi-tx-current-model.h
src/wifi/model/wifi-tx-current-model.cc