ns-3: ns3::Cid Class Reference
ns3::Cid Class Reference
WiMAX Models
Cid class.
#include "cid.h"
Public Types
enum Type {
BROADCAST = 1, INITIAL_RANGING, BASIC, PRIMARY,
TRANSPORT, MULTICAST, PADDING
}
Type enumeration.
Public Member Functions
Cid (uint16_t cid)
Constructor.
Cid (void)
Create a cid of unknown type.
~Cid (void)
uint16_t GetIdentifier (void) const
bool IsBroadcast (void) const
bool IsInitialRanging (void) const
bool IsMulticast (void) const
bool IsPadding (void) const
Static Public Member Functions
static Cid Broadcast (void)
static Cid InitialRanging (void)
static Cid Padding (void)
Private Attributes
uint16_t m_identifier
identiifier
Friends
class CidFactory
allow CidFactory class friend access
bool operator== (const Cid &lhs, const Cid &rhs)
equality operator
Detailed Description
Cid class.
Definition at line 37 of file cid.h.
Member Enumeration Documentation
Type
enum ns3::Cid::Type
Type enumeration.
Enumerator
BROADCAST
INITIAL_RANGING
BASIC
PRIMARY
TRANSPORT
MULTICAST
PADDING
Definition at line 41 of file cid.h.
Constructor & Destructor Documentation
Cid() [1/2]
ns3::Cid::Cid (void)
Create a cid of unknown type.
Definition at line 30 of file cid.cc.
References CID_UNINITIALIZED, and m_identifier.
Cid() [2/2]
ns3::Cid::Cid (uint16_t cid)
Constructor.
Parameters
cid
Definition at line 35 of file cid.cc.
References m_identifier.
~Cid()
ns3::Cid::~Cid (void)
Definition at line 40 of file cid.cc.
Member Function Documentation
Broadcast()
Cid ns3::Cid::Broadcast (void) static
Returns
the broadcast cid
Definition at line 72 of file cid.cc.
Referenced by ns3::CidFactory::Allocate(), ns3::WimaxNetDevice::CreateDefaultConnections(), and IsBroadcast().
GetIdentifier()
uint16_t ns3::Cid::GetIdentifier (void) const
Returns
the identifier of the cid
Definition at line 45 of file cid.cc.
References m_identifier.
Referenced by ns3::BSSchedulerRtps::BSSchedulerBroadcastConnection(), ns3::ServiceFlowManager::GetServiceFlow(), ns3::operator<<(), ns3::BandwidthRequestHeader::Print(), ns3::RngRsp::Serialize(), ns3::GenericMacHeader::Serialize(), ns3::BandwidthRequestHeader::Serialize(), ns3::OfdmDlMapIe::Write(), and ns3::OfdmUlMapIe::Write().
InitialRanging()
Cid ns3::Cid::InitialRanging (void) static
Returns
the initial ranging cid
Definition at line 82 of file cid.cc.
Referenced by ns3::BsServiceFlowManager::BsServiceFlowManager(), ns3::CidFactory::Allocate(), ns3::WimaxNetDevice::CreateDefaultConnections(), ns3::BaseStationNetDevice::CreateDlMap(), IsInitialRanging(), ns3::UplinkSchedulerRtps::Schedule(), and ns3::UplinkSchedulerSimple::Schedule().
IsBroadcast()
bool ns3::Cid::IsBroadcast (void) const
Returns
true if the cid is a broadcast cid, false otherwise
Definition at line 56 of file cid.cc.
References Broadcast().
Referenced by ns3::BaseStationNetDevice::DoReceive(), and ns3::BaseStationNetDevice::GetConnection().
IsInitialRanging()
bool ns3::Cid::IsInitialRanging (void) const
Returns
true if the cid is an initial ranging cid, false otherwise
Definition at line 66 of file cid.cc.
References InitialRanging().
Referenced by ns3::BaseStationNetDevice::DoReceive(), ns3::BaseStationNetDevice::GetConnection(), and ns3::BSLinkManager::PerformRanging().
IsMulticast()
bool ns3::Cid::IsMulticast (void) const
Returns
true if the cid is a multicast cid, false otherwise
Definition at line 51 of file cid.cc.
References m_identifier.
Referenced by ns3::SubscriberStationNetDevice::DoReceive().
IsPadding()
bool ns3::Cid::IsPadding (void) const
Returns
true if the cid is a padding cid, false otherwise
Definition at line 61 of file cid.cc.
References Padding().
Padding()
Cid ns3::Cid::Padding (void) static
Returns
the padding cid
Definition at line 77 of file cid.cc.
Referenced by ns3::CidFactory::Allocate(), and IsPadding().
Friends And Related Function Documentation
CidFactory
friend class CidFactory friend
allow CidFactory class friend access
Definition at line 96 of file cid.h.
operator==
bool operator== (const Cid & lhs, const Cid & rhs) friend
equality operator
Parameters
lhs left hand side
rhs right hand side
Returns
true if equal
Definition at line 93 of file cid.cc.
Member Data Documentation
m_identifier
uint16_t ns3::Cid::m_identifier private
identiifier
Definition at line 99 of file cid.h.
Referenced by Cid(), GetIdentifier(), ns3::CidFactory::IsBasic(), IsMulticast(), ns3::CidFactory::IsPrimary(), ns3::CidFactory::IsTransport(), and ns3::operator==().
The documentation for this class was generated from the following files:
src/wimax/model/cid.h
src/wimax/model/cid.cc