ns-3: ns3::PbbMessageIpv4 Class Reference
ns3::PbbMessageIpv4 Class Reference
Concrete IPv4 specific PbbMessage.
#include "packetbb.h"
Public Member Functions
PbbMessageIpv4 ()
virtual ~PbbMessageIpv4 ()
Public Member Functions inherited from ns3::PbbMessage
PbbMessage ()
virtual ~PbbMessage ()
Ptr< PbbAddressBlock > AddressBlockBack (void)
const Ptr< PbbAddressBlock > AddressBlockBack (void) const
AddressBlockIterator AddressBlockBegin ()
ConstAddressBlockIterator AddressBlockBegin () const
void AddressBlockClear (void)
Removes all address blocks from this message.
bool AddressBlockEmpty (void) const
AddressBlockIterator AddressBlockEnd ()
ConstAddressBlockIterator AddressBlockEnd () const
AddressBlockIterator AddressBlockErase (AddressBlockIterator first, AddressBlockIterator last)
Removes all address blocks from [first, last) (includes first, not includes last).
AddressBlockIterator AddressBlockErase (AddressBlockIterator position)
Removes the address block at the specified position.
Ptr< PbbAddressBlock > AddressBlockFront (void)
const Ptr< PbbAddressBlock > AddressBlockFront (void) const
void AddressBlockPopBack (void)
Removes an address block from the back of this message.
void AddressBlockPopFront (void)
Removes an address block from the front of this message.
void AddressBlockPushBack (Ptr< PbbAddressBlock > block)
Appends an address block to the front of this message.
void AddressBlockPushFront (Ptr< PbbAddressBlock > block)
Prepends an address block to the front of this message.
int AddressBlockSize (void) const
void Deserialize (Buffer::Iterator &start)
Deserializes a message from the specified buffer.
uint8_t GetHopCount (void) const
uint8_t GetHopLimit (void) const
Address GetOriginatorAddress (void) const
uint16_t GetSequenceNumber (void) const
uint32_t GetSerializedSize (void) const
uint8_t GetType (void) const
bool HasHopCount (void) const
Tests whether or not this message has a hop count.
bool HasHopLimit (void) const
Tests whether or not this message has a hop limit.
bool HasOriginatorAddress (void) const
Tests whether or not this message has an originator address.
bool HasSequenceNumber (void) const
Tests whether or not this message has a sequence number.
bool operator!= (const PbbMessage &other) const
Inequality operator for PbbMessage.
bool operator== (const PbbMessage &other) const
Equality operator for PbbMessage.
void Print (std::ostream &os) const
Pretty-prints the contents of this message.
void Print (std::ostream &os, int level) const
Pretty-prints the contents of this message, with specified indentation.
void Serialize (Buffer::Iterator &start) const
Serializes this message into the specified buffer.
void SetHopCount (uint8_t hopcount)
Sets the current number of hops this message has traveled.
void SetHopLimit (uint8_t hoplimit)
Sets the maximum number of hops this message should travel.
void SetOriginatorAddress (Address address)
Sets the address for the node that created this packet.
void SetSequenceNumber (uint16_t seqnum)
Sets the sequence number of this message.
void SetType (uint8_t type)
Sets the type for this message.
Ptr< PbbTlv > TlvBack (void)
const Ptr< PbbTlv > TlvBack (void) const
TlvIterator TlvBegin ()
ConstTlvIterator TlvBegin () const
void TlvClear (void)
Removes all message TLVs from this block.
bool TlvEmpty (void) const
TlvIterator TlvEnd ()
ConstTlvIterator TlvEnd () const
TlvIterator TlvErase (TlvIterator first, TlvIterator last)
Removes all message TLVs from [first, last) (includes first, not includes last).
TlvIterator TlvErase (TlvIterator position)
Removes the message TLV at the specified position.
Ptr< PbbTlv > TlvFront (void)
const Ptr< PbbTlv > TlvFront (void) const
void TlvPopBack (void)
Removes a message TLV from the back of this message.
void TlvPopFront (void)
Removes a message TLV from the front of this message.
void TlvPushBack (Ptr< PbbTlv > tlv)
Appends a message TLV to the back of this message.
void TlvPushFront (Ptr< PbbTlv > tlv)
Prepends a message TLV to the front of this message.
int TlvSize (void) const
Public Member Functions inherited from ns3::SimpleRefCount< PbbMessage >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Protected Member Functions
virtual Ptr< PbbAddressBlock > AddressBlockDeserialize (Buffer::Iterator &start) const
Deserialize an address block.
virtual Address DeserializeOriginatorAddress (Buffer::Iterator &start) const
Deserialize the originator address.
virtual PbbAddressLength GetAddressLength (void) const
Returns address length (IPV4 3 or IPV6 15)
virtual void PrintOriginatorAddress (std::ostream &os) const
Print the originator address.
virtual void SerializeOriginatorAddress (Buffer::Iterator &start) const
Serialize the originator address.
Additional Inherited Members
Public Types inherited from ns3::PbbMessage
typedef std::list< Ptr< PbbAddressBlock > >::iterator AddressBlockIterator
PbbAddressBlock iterator.
typedef std::list< Ptr< PbbAddressBlock > >::const_iterator ConstAddressBlockIterator
PbbAddressBlock const iterator.
typedef std::list< Ptr< PbbTlv > >::const_iterator ConstTlvIterator
PbbTlv const iterator.
typedef std::list< Ptr< PbbTlv > >::iterator TlvIterator
PbbTlv iterator.
Static Public Member Functions inherited from ns3::PbbMessage
static Ptr< PbbMessage > DeserializeMessage (Buffer::Iterator &start)
Deserializes a message, returning the correct object depending on whether it is an IPv4 message or an IPv6 message.
Detailed Description
Concrete IPv4 specific PbbMessage.
This message will only contain IPv4 addresses.
Definition at line 1127 of file packetbb.h.
Constructor & Destructor Documentation
PbbMessageIpv4()
ns3::PbbMessageIpv4::PbbMessageIpv4 ()
Definition at line 1726 of file packetbb.cc.
References NS_LOG_FUNCTION.
~PbbMessageIpv4()
ns3::PbbMessageIpv4::~PbbMessageIpv4 () virtual
Definition at line 1731 of file packetbb.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddressBlockDeserialize()
Ptr< PbbAddressBlock > ns3::PbbMessageIpv4::AddressBlockDeserialize (Buffer::Iterator & start) const protected virtual
Deserialize an address block.
Parameters
start the buffer iterator start
Returns
the deserialized address block
Implements ns3::PbbMessage.
Definition at line 1772 of file packetbb.cc.
References NS_LOG_FUNCTION, and visualizer.core::start().
DeserializeOriginatorAddress()
Address ns3::PbbMessageIpv4::DeserializeOriginatorAddress (Buffer::Iterator & start) const protected virtual
Deserialize the originator address.
Parameters
start the buffer iterator start
Returns
the deserialized address
Implements ns3::PbbMessage.
Definition at line 1754 of file packetbb.cc.
References ns3::Ipv4Address::Deserialize(), GetAddressLength(), NS_LOG_FUNCTION, and visualizer.core::start().
GetAddressLength()
PbbAddressLength ns3::PbbMessageIpv4::GetAddressLength (void) const protected virtual
Returns address length (IPV4 3 or IPV6 15)
Returns message size in bytes - 1 IPv4 = 4 - 1 = 3, IPv6 = 16 - 1 = 15
Returns
Address length (IPV4 3 or IPV6 15)
Implements ns3::PbbMessage.
Definition at line 1737 of file packetbb.cc.
References ns3::IPV4, and NS_LOG_FUNCTION.
Referenced by DeserializeOriginatorAddress(), and SerializeOriginatorAddress().
PrintOriginatorAddress()
void ns3::PbbMessageIpv4::PrintOriginatorAddress (std::ostream & os) const protected virtual
Print the originator address.
Parameters
os the output stream
Implements ns3::PbbMessage.
Definition at line 1765 of file packetbb.cc.
References ns3::Ipv4Address::ConvertFrom(), ns3::PbbMessage::GetOriginatorAddress(), NS_LOG_FUNCTION, and ns3::Ipv4Address::Print().
SerializeOriginatorAddress()
void ns3::PbbMessageIpv4::SerializeOriginatorAddress (Buffer::Iterator & start) const protected virtual
Serialize the originator address.
Parameters
start the buffer iterator start
Implements ns3::PbbMessage.
Definition at line 1744 of file packetbb.cc.
References ns3::Ipv4Address::ConvertFrom(), GetAddressLength(), ns3::PbbMessage::GetOriginatorAddress(), NS_LOG_FUNCTION, ns3::Ipv4Address::Serialize(), and visualizer.core::start().
The documentation for this class was generated from the following files:
src/network/utils/packetbb.h
src/network/utils/packetbb.cc