ns-3: ns3::VendorSpecificContentManager Class Reference
ns3::VendorSpecificContentManager Class Reference
WAVE module
#include "vendor-specific-action.h"
Public Member Functions
VendorSpecificContentManager (void)
virtual ~VendorSpecificContentManager (void)
void DeregisterVscCallback (OrganizationIdentifier &oi)
VscCallback FindVscCallback (OrganizationIdentifier &oi)
bool IsVscCallbackRegistered (OrganizationIdentifier &oi)
void RegisterVscCallback (OrganizationIdentifier oi, VscCallback cb)
Private Types
typedef std::map< OrganizationIdentifier, VscCallback > VscCallbacks
VSC callback typedef.
typedef std::map< OrganizationIdentifier, VscCallback >::iterator VscCallbacksI
VSC callback iterator typedef.
Private Attributes
VscCallbacks m_callbacks
VSC callbacks.
Detailed Description
VendorSpecificContentManager class
Definition at line 205 of file vendor-specific-action.h.
Member Typedef Documentation
VscCallbacks
typedef std::map<OrganizationIdentifier,VscCallback> ns3::VendorSpecificContentManager::VscCallbacks private
VSC callback typedef.
Definition at line 236 of file vendor-specific-action.h.
VscCallbacksI
typedef std::map<OrganizationIdentifier,VscCallback>::iterator ns3::VendorSpecificContentManager::VscCallbacksI private
VSC callback iterator typedef.
Definition at line 238 of file vendor-specific-action.h.
Constructor & Destructor Documentation
VendorSpecificContentManager()
ns3::VendorSpecificContentManager::VendorSpecificContentManager (void)
Definition at line 341 of file vendor-specific-action.cc.
References NS_LOG_FUNCTION.
~VendorSpecificContentManager()
ns3::VendorSpecificContentManager::~VendorSpecificContentManager (void) virtual
Definition at line 346 of file vendor-specific-action.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DeregisterVscCallback()
void ns3::VendorSpecificContentManager::DeregisterVscCallback (OrganizationIdentifier & oi)
Parameters
oi the specific OrganizationIdentifier when receive management information by VendorSpecificAction management frame.
Definition at line 363 of file vendor-specific-action.cc.
References m_callbacks, and NS_LOG_FUNCTION.
Referenced by ns3::OcbWifiMac::RemoveReceiveVscCallback().
FindVscCallback()
VscCallback ns3::VendorSpecificContentManager::FindVscCallback (OrganizationIdentifier & oi)
Parameters
oi the specific OrganizationIdentifier when receive management information by VendorSpecificAction management frame.
Returns
VscCallback
Definition at line 385 of file vendor-specific-action.cc.
References m_callbacks, NS_LOG_FUNCTION, and ns3::null_callback.
Referenced by ns3::OcbWifiMac::Receive().
IsVscCallbackRegistered()
bool ns3::VendorSpecificContentManager::IsVscCallbackRegistered (OrganizationIdentifier & oi)
Parameters
oi the specific OrganizationIdentifier when receive management information by VendorSpecificAction management frame.
Returns
true if registered
Definition at line 370 of file vendor-specific-action.cc.
References m_callbacks, NS_LOG_FUNCTION, and ns3::OrganizationIdentifiers.
Referenced by RegisterVscCallback().
RegisterVscCallback()
void ns3::VendorSpecificContentManager::RegisterVscCallback (OrganizationIdentifier oi, VscCallback cb)
Parameters
oi the specific OrganizationIdentifier when receive management information by VendorSpecificAction management frame.
cb the receive callback when oi related management packets are received
Definition at line 352 of file vendor-specific-action.cc.
References IsVscCallbackRegistered(), m_callbacks, NS_LOG_FUNCTION, and NS_LOG_WARN.
Referenced by ns3::OcbWifiMac::AddReceiveVscCallback().
Member Data Documentation
m_callbacks
VscCallbacks ns3::VendorSpecificContentManager::m_callbacks private
VSC callbacks.
Definition at line 240 of file vendor-specific-action.h.
Referenced by DeregisterVscCallback(), FindVscCallback(), IsVscCallbackRegistered(), and RegisterVscCallback().
The documentation for this class was generated from the following files:
src/wave/model/vendor-specific-action.h
src/wave/model/vendor-specific-action.cc