ns-3: ns3::LteRlcAmHeader Class Reference
ns3::LteRlcAmHeader Class Reference
LTE Models
The packet header for the AM Radio Link Control (RLC) protocol packets.
#include "lte-rlc-am-header.h"
Public Types
enum ControPduType_t { STATUS_PDU = 000 }
ControlPduType_t enumeration.
enum DataControlPdu_t { CONTROL_PDU = 0, DATA_PDU = 1 }
DataControlPdu_t enumeration.
enum ExtensionBit_t { DATA_FIELD_FOLLOWS = 0, E_LI_FIELDS_FOLLOWS = 1 }
ExtensionBit_t typedef.
enum FramingInfoFirstByte_t { FIRST_BYTE = 0x00, NO_FIRST_BYTE = 0x02 }
FramingInfoFirstByte_t enumeration.
enum FramingInfoLastByte_t { LAST_BYTE = 0x00, NO_LAST_BYTE = 0x01 }
FramingInfoLastByte_t enumeration.
enum LastSegmentFlag_t { NO_LAST_PDU_SEGMENT = 0, LAST_PDU_SEGMENT = 1 }
LastSegmentFlag_t typedef.
enum PollingBit_t { STATUS_REPORT_NOT_REQUESTED = 0, STATUS_REPORT_IS_REQUESTED = 1 }
PollingBit_t enumeration.
enum ResegmentationFlag_t { PDU = 0, SEGMENT = 1 }
ResegmentationFlag_t typedef.
Public Member Functions
LteRlcAmHeader ()
Constructor.
~LteRlcAmHeader ()
virtual uint32_t Deserialize (Buffer::Iterator start)
SequenceNumber10 GetAckSn () const
Get ack sn function.
uint8_t GetFramingInfo () const
Get framing info.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint16_t GetLastOffset () const
Get last offset function.
uint8_t GetLastSegmentFlag () const
Get last segment flag function.
uint8_t GetPollingBit () const
Get polling bit function.
uint8_t GetResegmentationFlag () const
Get resegmentation flag function.
uint16_t GetSegmentOffset () const
Get segment offset function.
SequenceNumber10 GetSequenceNumber () const
Get sequence number.
virtual uint32_t GetSerializedSize (void) const
bool IsControlPdu (void) const
Is control PDU function.
bool IsDataPdu (void) const
Is data PDU function.
bool IsNackPresent (SequenceNumber10 nack)
bool OneMoreNackWouldFitIn (uint16_t bytes)
uint8_t PopExtensionBit (void)
Pop extension bit function.
uint16_t PopLengthIndicator (void)
Pop length indicator function.
int PopNack (void)
Retrieve one NACK from the CONTROL PDU.
virtual void Print (std::ostream &os) const
void PushExtensionBit (uint8_t extensionBit)
Push extension bit function.
void PushLengthIndicator (uint16_t lengthIndicator)
Push length indicator function.
void PushNack (int nack)
Add one more NACK to the CONTROL PDU.
virtual void Serialize (Buffer::Iterator start) const
void SetAckSn (SequenceNumber10 ackSn)
Set ack sn function.
void SetControlPdu (uint8_t controlPduType)
Set control PDU function.
void SetDataPdu (void)
Set data PDU function.
void SetFramingInfo (uint8_t framingInfo)
Set sequence number.
void SetLastSegmentFlag (uint8_t lsf)
Set last segment flag function.
void SetPollingBit (uint8_t pollingBit)
Set polling bit function.
void SetResegmentationFlag (uint8_t resegFlag)
Pop extension bit function.
void SetSegmentOffset (uint16_t segmentOffset)
Set segment offset function.
void SetSequenceNumber (SequenceNumber10 sequenceNumber)
Set sequence number.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
SequenceNumber10 m_ackSn
ack sn
uint8_t m_controlPduType
control PDU type
uint8_t m_dataControlBit
data control bit
std::list< uint8_t > m_extensionBits
Includes extensionBit of the fixed part.
std::list< uint8_t > m_extensionBits1
Includes E1 after ACK_SN.
std::list< uint8_t > m_extensionBits2
extension bits 2
uint8_t m_framingInfo
2 bits
uint16_t m_headerLength
header length
uint16_t m_lastOffset
last offset
uint8_t m_lastSegmentFlag
last segment flag
std::list< uint16_t > m_lengthIndicators
length indicators
std::list< int > m_nackSnList
nack sn list
uint8_t m_pollingBit
polling bit
uint8_t m_resegmentationFlag
resegmentation flag
uint16_t m_segmentOffset
segment offset
SequenceNumber10 m_sequenceNumber
sequence number
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The packet header for the AM Radio Link Control (RLC) protocol packets.
This class has fields corresponding to those in an RLC header as well as methods for serialization to and deserialization from a byte buffer. It follows 3GPP TS 36.322 Radio Link Control (RLC) protocol specification.
Definition at line 39 of file lte-rlc-am-header.h.
Member Enumeration Documentation
ControPduType_t
enum ns3::LteRlcAmHeader::ControPduType_t
ControlPduType_t enumeration.
Enumerator
STATUS_PDU
Definition at line 77 of file lte-rlc-am-header.h.
DataControlPdu_t
enum ns3::LteRlcAmHeader::DataControlPdu_t
DataControlPdu_t enumeration.
Enumerator
CONTROL_PDU
DATA_PDU
Definition at line 71 of file lte-rlc-am-header.h.
ExtensionBit_t
enum ns3::LteRlcAmHeader::ExtensionBit_t
ExtensionBit_t typedef.
Enumerator
DATA_FIELD_FOLLOWS
E_LI_FIELDS_FOLLOWS
Definition at line 150 of file lte-rlc-am-header.h.
FramingInfoFirstByte_t
enum ns3::LteRlcAmHeader::FramingInfoFirstByte_t
FramingInfoFirstByte_t enumeration.
Enumerator
FIRST_BYTE
NO_FIRST_BYTE
Definition at line 112 of file lte-rlc-am-header.h.
FramingInfoLastByte_t
enum ns3::LteRlcAmHeader::FramingInfoLastByte_t
FramingInfoLastByte_t enumeration.
Enumerator
LAST_BYTE
NO_LAST_BYTE
Definition at line 118 of file lte-rlc-am-header.h.
LastSegmentFlag_t
enum ns3::LteRlcAmHeader::LastSegmentFlag_t
LastSegmentFlag_t typedef.
Enumerator
NO_LAST_PDU_SEGMENT
LAST_PDU_SEGMENT
Definition at line 207 of file lte-rlc-am-header.h.
PollingBit_t
enum ns3::LteRlcAmHeader::PollingBit_t
PollingBit_t enumeration.
Enumerator
STATUS_REPORT_NOT_REQUESTED
STATUS_REPORT_IS_REQUESTED
Definition at line 188 of file lte-rlc-am-header.h.
ResegmentationFlag_t
enum ns3::LteRlcAmHeader::ResegmentationFlag_t
ResegmentationFlag_t typedef.
Enumerator
PDU
SEGMENT
Definition at line 169 of file lte-rlc-am-header.h.
Constructor & Destructor Documentation
LteRlcAmHeader()
ns3::LteRlcAmHeader::LteRlcAmHeader ()
Constructor.
Creates a null header
Definition at line 31 of file lte-rlc-am-header.cc.
~LteRlcAmHeader()
ns3::LteRlcAmHeader::~LteRlcAmHeader ()
Definition at line 45 of file lte-rlc-am-header.cc.
References m_ackSn, m_controlPduType, m_dataControlBit, m_framingInfo, m_headerLength, m_lastOffset, m_pollingBit, m_resegmentationFlag, m_segmentOffset, and m_sequenceNumber.
Member Function Documentation
Deserialize()
uint32_t ns3::LteRlcAmHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 502 of file lte-rlc-am-header.cc.
References DATA_FIELD_FOLLOWS, DATA_PDU, E_LI_FIELDS_FOLLOWS, GetSerializedSize(), m_ackSn, m_controlPduType, m_dataControlBit, m_extensionBits, m_framingInfo, m_headerLength, m_lastOffset, m_lastSegmentFlag, m_lengthIndicators, m_nackSnList, m_pollingBit, m_resegmentationFlag, m_segmentOffset, m_sequenceNumber, ns3::Buffer::Iterator::ReadU8(), SEGMENT, and visualizer.core::start().
GetAckSn()
SequenceNumber10 ns3::LteRlcAmHeader::GetAckSn () const
Get ack sn function.
Returns
sequence numbr
Definition at line 286 of file lte-rlc-am-header.cc.
References m_ackSn.
Referenced by ns3::LteRlcAm::DoReceivePdu(), and ns3::RlcAmStatusPduTestCase::DoRun().
GetFramingInfo()
uint8_t ns3::LteRlcAmHeader::GetFramingInfo () const
Get framing info.
Returns
framing info
Definition at line 96 of file lte-rlc-am-header.cc.
References m_framingInfo.
Referenced by ns3::LteRlcAm::ReassembleAndDeliver().
GetInstanceTypeId()
TypeId ns3::LteRlcAmHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 304 of file lte-rlc-am-header.cc.
References GetTypeId().
GetLastOffset()
uint16_t ns3::LteRlcAmHeader::GetLastOffset () const
Get last offset function.
Returns
last offset
Definition at line 203 of file lte-rlc-am-header.cc.
References m_lastOffset.
GetLastSegmentFlag()
uint8_t ns3::LteRlcAmHeader::GetLastSegmentFlag () const
Get last segment flag function.
Returns
last segment flag
Definition at line 184 of file lte-rlc-am-header.cc.
References m_lastSegmentFlag.
GetPollingBit()
uint8_t ns3::LteRlcAmHeader::GetPollingBit () const
Get polling bit function.
Returns
polling bit
Definition at line 171 of file lte-rlc-am-header.cc.
References m_pollingBit.
Referenced by ns3::LteRlcAm::DoReceivePdu().
GetResegmentationFlag()
uint8_t ns3::LteRlcAmHeader::GetResegmentationFlag () const
Get resegmentation flag function.
Returns
resegmentation flag
Definition at line 158 of file lte-rlc-am-header.cc.
References m_resegmentationFlag.
Referenced by ns3::LteRlcAm::DoReceivePdu().
GetSegmentOffset()
uint16_t ns3::LteRlcAmHeader::GetSegmentOffset () const
Get segment offset function.
Returns
segment offset
Definition at line 197 of file lte-rlc-am-header.cc.
References m_segmentOffset.
GetSequenceNumber()
SequenceNumber10 ns3::LteRlcAmHeader::GetSequenceNumber () const
Get sequence number.
Returns
sequence number
Definition at line 102 of file lte-rlc-am-header.cc.
References m_sequenceNumber.
Referenced by ns3::LteRlcAm::DoNotifyTxOpportunity(), ns3::LteRlcAm::DoReceivePdu(), and ns3::LteRlcAm::ReassembleAndDeliver().
GetSerializedSize()
uint32_t ns3::LteRlcAmHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 364 of file lte-rlc-am-header.cc.
References m_headerLength.
Referenced by Deserialize(), and ns3::LteRlcAm::DoNotifyTxOpportunity().
GetTypeId()
TypeId ns3::LteRlcAmHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 293 of file lte-rlc-am-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
IsControlPdu()
bool ns3::LteRlcAmHeader::IsControlPdu (void) const
Is control PDU function.
Returns
true if control PDU
Definition at line 78 of file lte-rlc-am-header.cc.
References CONTROL_PDU, and m_dataControlBit.
Referenced by ns3::LteRlcAm::DoReceivePdu().
IsDataPdu()
bool ns3::LteRlcAmHeader::IsDataPdu (void) const
Is data PDU function.
Returns
true if data PDU
Definition at line 73 of file lte-rlc-am-header.cc.
References DATA_PDU, and m_dataControlBit.
Referenced by ns3::LteRlcAm::DoReceivePdu().
IsNackPresent()
bool ns3::LteRlcAmHeader::IsNackPresent (SequenceNumber10 nack)
Parameters
nack SN of the NACK
Returns
true if the NACK is present in the STATUS PDU, false otherwise
Definition at line 250 of file lte-rlc-am-header.cc.
References CONTROL_PDU, ns3::SequenceNumber10::GetValue(), m_controlPduType, m_dataControlBit, m_nackSnList, NS_ASSERT_MSG(), NS_LOG_FUNCTION, and STATUS_PDU.
Referenced by ns3::LteRlcAm::DoReceivePdu().
OneMoreNackWouldFitIn()
bool ns3::LteRlcAmHeader::OneMoreNackWouldFitIn (uint16_t bytes)
Parameters
bytes max allowed CONTROL PDU size
Returns
true if one more NACK would fit in the CONTROL PDU; false otherwise
Definition at line 216 of file lte-rlc-am-header.cc.
References CONTROL_PDU, m_controlPduType, m_dataControlBit, m_headerLength, m_nackSnList, NS_ASSERT_MSG(), NS_LOG_FUNCTION, and STATUS_PDU.
Referenced by ns3::LteRlcAm::DoNotifyTxOpportunity().
PopExtensionBit()
uint8_t ns3::LteRlcAmHeader::PopExtensionBit (void)
Pop extension bit function.
Returns
the extension bit
Definition at line 133 of file lte-rlc-am-header.cc.
References m_extensionBits.
Referenced by ns3::LteRlcAm::ReassembleAndDeliver().
PopLengthIndicator()
uint16_t ns3::LteRlcAmHeader::PopLengthIndicator (void)
Pop length indicator function.
Returns
the length indicator
Definition at line 142 of file lte-rlc-am-header.cc.
References m_lengthIndicators.
Referenced by ns3::LteRlcAm::ReassembleAndDeliver().
PopNack()
int ns3::LteRlcAmHeader::PopNack (void)
Retrieve one NACK from the CONTROL PDU.
Returns
the SN >= 0 of the next nack; returns -1 if no NACK is left
Definition at line 268 of file lte-rlc-am-header.cc.
References CONTROL_PDU, m_controlPduType, m_dataControlBit, m_nackSnList, NS_ASSERT_MSG(), NS_LOG_FUNCTION, and STATUS_PDU.
Referenced by ns3::RlcAmStatusPduTestCase::DoRun().
Print()
void ns3::LteRlcAmHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 310 of file lte-rlc-am-header.cc.
References DATA_PDU, m_ackSn, m_dataControlBit, m_extensionBits, m_framingInfo, m_headerLength, m_lastSegmentFlag, m_lengthIndicators, m_nackSnList, m_pollingBit, m_resegmentationFlag, m_segmentOffset, and m_sequenceNumber.
PushExtensionBit()
void ns3::LteRlcAmHeader::PushExtensionBit (uint8_t extensionBit)
Push extension bit function.
Parameters
extensionBit the extension bit
Definition at line 109 of file lte-rlc-am-header.cc.
References m_extensionBits, and m_headerLength.
Referenced by ns3::LteRlcAm::DoNotifyTxOpportunity().
PushLengthIndicator()
void ns3::LteRlcAmHeader::PushLengthIndicator (uint16_t lengthIndicator)
Push length indicator function.
Parameters
lengthIndicator the length indicator
Definition at line 126 of file lte-rlc-am-header.cc.
References m_lengthIndicators.
Referenced by ns3::LteRlcAm::DoNotifyTxOpportunity().
PushNack()
void ns3::LteRlcAmHeader::PushNack (int nack)
Add one more NACK to the CONTROL PDU.
Parameters
nack
Definition at line 232 of file lte-rlc-am-header.cc.
References CONTROL_PDU, m_controlPduType, m_dataControlBit, m_headerLength, m_nackSnList, NS_ASSERT_MSG(), NS_LOG_FUNCTION, and STATUS_PDU.
Referenced by ns3::LteRlcAm::DoNotifyTxOpportunity(), and ns3::RlcAmStatusPduTestCase::DoRun().
Serialize()
void ns3::LteRlcAmHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 369 of file lte-rlc-am-header.cc.
References CONTROL_PDU, DATA_PDU, ns3::SequenceNumber10::GetValue(), m_ackSn, m_controlPduType, m_dataControlBit, m_extensionBits, m_framingInfo, m_lastSegmentFlag, m_lengthIndicators, m_nackSnList, m_pollingBit, m_resegmentationFlag, m_segmentOffset, m_sequenceNumber, NS_LOG_LOGIC(), visualizer.core::start(), and ns3::Buffer::Iterator::WriteU8().
SetAckSn()
void ns3::LteRlcAmHeader::SetAckSn (SequenceNumber10 ackSn)
Set ack sn function.
Parameters
ackSn ack sn
Definition at line 210 of file lte-rlc-am-header.cc.
References m_ackSn.
Referenced by ns3::LteRlcAm::DoNotifyTxOpportunity(), and ns3::RlcAmStatusPduTestCase::DoRun().
SetControlPdu()
void ns3::LteRlcAmHeader::SetControlPdu (uint8_t controlPduType)
Set control PDU function.
Parameters
controlPduType
Definition at line 66 of file lte-rlc-am-header.cc.
References CONTROL_PDU, m_controlPduType, m_dataControlBit, and m_headerLength.
Referenced by ns3::LteRlcAm::DoNotifyTxOpportunity(), and ns3::RlcAmStatusPduTestCase::DoRun().
SetDataPdu()
void ns3::LteRlcAmHeader::SetDataPdu (void)
Set data PDU function.
Definition at line 60 of file lte-rlc-am-header.cc.
References DATA_PDU, m_dataControlBit, and m_headerLength.
Referenced by ns3::LteRlcAm::DoNotifyTxOpportunity().
SetFramingInfo()
void ns3::LteRlcAmHeader::SetFramingInfo (uint8_t framingInfo)
Set sequence number.
Parameters
framingInfo framing info
Definition at line 84 of file lte-rlc-am-header.cc.
References m_framingInfo.
Referenced by ns3::LteRlcAm::DoNotifyTxOpportunity().
SetLastSegmentFlag()
void ns3::LteRlcAmHeader::SetLastSegmentFlag (uint8_t lsf)
Set last segment flag function.
Parameters
lsf last segment flag
Definition at line 178 of file lte-rlc-am-header.cc.
References m_lastSegmentFlag.
Referenced by ns3::LteRlcAm::DoNotifyTxOpportunity().
SetPollingBit()
void ns3::LteRlcAmHeader::SetPollingBit (uint8_t pollingBit)
Set polling bit function.
Parameters
pollingBit polling bit
Definition at line 165 of file lte-rlc-am-header.cc.
References m_pollingBit.
Referenced by ns3::LteRlcAm::DoNotifyTxOpportunity().
SetResegmentationFlag()
void ns3::LteRlcAmHeader::SetResegmentationFlag (uint8_t resegFlag)
Pop extension bit function.
Parameters
resegFlag resegmentation flag
Definition at line 152 of file lte-rlc-am-header.cc.
References m_resegmentationFlag.
Referenced by ns3::LteRlcAm::DoNotifyTxOpportunity().
SetSegmentOffset()
void ns3::LteRlcAmHeader::SetSegmentOffset (uint16_t segmentOffset)
Set segment offset function.
Parameters
segmentOffset segment offset
Definition at line 191 of file lte-rlc-am-header.cc.
References m_segmentOffset.
Referenced by ns3::LteRlcAm::DoNotifyTxOpportunity().
SetSequenceNumber()
void ns3::LteRlcAmHeader::SetSequenceNumber (SequenceNumber10 sequenceNumber)
Set sequence number.
Parameters
sequenceNumber sequence number
Definition at line 90 of file lte-rlc-am-header.cc.
References m_sequenceNumber.
Referenced by ns3::LteRlcAm::DoNotifyTxOpportunity().
Member Data Documentation
m_ackSn
SequenceNumber10 ns3::LteRlcAmHeader::m_ackSn private
ack sn
Definition at line 315 of file lte-rlc-am-header.h.
Referenced by ~LteRlcAmHeader(), Deserialize(), GetAckSn(), Print(), Serialize(), and SetAckSn().
m_controlPduType
uint8_t ns3::LteRlcAmHeader::m_controlPduType private
control PDU type
Definition at line 312 of file lte-rlc-am-header.h.
Referenced by ~LteRlcAmHeader(), Deserialize(), IsNackPresent(), OneMoreNackWouldFitIn(), PopNack(), PushNack(), Serialize(), and SetControlPdu().
m_dataControlBit
uint8_t ns3::LteRlcAmHeader::m_dataControlBit private
data control bit
Definition at line 297 of file lte-rlc-am-header.h.
Referenced by ~LteRlcAmHeader(), Deserialize(), IsControlPdu(), IsDataPdu(), IsNackPresent(), OneMoreNackWouldFitIn(), PopNack(), Print(), PushNack(), Serialize(), SetControlPdu(), and SetDataPdu().
m_extensionBits
std::list<uint8_t> ns3::LteRlcAmHeader::m_extensionBits private
Includes extensionBit of the fixed part.
Definition at line 308 of file lte-rlc-am-header.h.
Referenced by Deserialize(), PopExtensionBit(), Print(), PushExtensionBit(), and Serialize().
m_extensionBits1
std::list<uint8_t> ns3::LteRlcAmHeader::m_extensionBits1 private
Includes E1 after ACK_SN.
Definition at line 318 of file lte-rlc-am-header.h.
m_extensionBits2
std::list<uint8_t> ns3::LteRlcAmHeader::m_extensionBits2 private
extension bits 2
Definition at line 319 of file lte-rlc-am-header.h.
m_framingInfo
uint8_t ns3::LteRlcAmHeader::m_framingInfo private
2 bits
Definition at line 302 of file lte-rlc-am-header.h.
Referenced by ~LteRlcAmHeader(), Deserialize(), GetFramingInfo(), Print(), Serialize(), and SetFramingInfo().
m_headerLength
uint16_t ns3::LteRlcAmHeader::m_headerLength private
header length
Definition at line 296 of file lte-rlc-am-header.h.
Referenced by ~LteRlcAmHeader(), Deserialize(), GetSerializedSize(), OneMoreNackWouldFitIn(), Print(), PushExtensionBit(), PushNack(), SetControlPdu(), and SetDataPdu().
m_lastOffset
uint16_t ns3::LteRlcAmHeader::m_lastOffset private
last offset
Definition at line 306 of file lte-rlc-am-header.h.
Referenced by ~LteRlcAmHeader(), Deserialize(), and GetLastOffset().
m_lastSegmentFlag
uint8_t ns3::LteRlcAmHeader::m_lastSegmentFlag private
last segment flag
Definition at line 304 of file lte-rlc-am-header.h.
Referenced by Deserialize(), GetLastSegmentFlag(), Print(), Serialize(), and SetLastSegmentFlag().
m_lengthIndicators
std::list<uint16_t> ns3::LteRlcAmHeader::m_lengthIndicators private
length indicators
Definition at line 309 of file lte-rlc-am-header.h.
Referenced by Deserialize(), PopLengthIndicator(), Print(), PushLengthIndicator(), and Serialize().
m_nackSnList
std::list<int> ns3::LteRlcAmHeader::m_nackSnList private
nack sn list
Definition at line 316 of file lte-rlc-am-header.h.
Referenced by Deserialize(), IsNackPresent(), OneMoreNackWouldFitIn(), PopNack(), Print(), PushNack(), and Serialize().
m_pollingBit
uint8_t ns3::LteRlcAmHeader::m_pollingBit private
polling bit
Definition at line 301 of file lte-rlc-am-header.h.
Referenced by ~LteRlcAmHeader(), Deserialize(), GetPollingBit(), Print(), Serialize(), and SetPollingBit().
m_resegmentationFlag
uint8_t ns3::LteRlcAmHeader::m_resegmentationFlag private
resegmentation flag
Definition at line 300 of file lte-rlc-am-header.h.
Referenced by ~LteRlcAmHeader(), Deserialize(), GetResegmentationFlag(), Print(), Serialize(), and SetResegmentationFlag().
m_segmentOffset
uint16_t ns3::LteRlcAmHeader::m_segmentOffset private
segment offset
Definition at line 305 of file lte-rlc-am-header.h.
Referenced by ~LteRlcAmHeader(), Deserialize(), GetSegmentOffset(), Print(), Serialize(), and SetSegmentOffset().
m_sequenceNumber
SequenceNumber10 ns3::LteRlcAmHeader::m_sequenceNumber private
sequence number
Definition at line 303 of file lte-rlc-am-header.h.
Referenced by ~LteRlcAmHeader(), Deserialize(), GetSequenceNumber(), Print(), Serialize(), and SetSequenceNumber().
The documentation for this class was generated from the following files:
src/lte/model/lte-rlc-am-header.h
src/lte/model/lte-rlc-am-header.cc