ns-3: ns3::SpectrumPropagationLossModel Class Reference
ns3::SpectrumPropagationLossModel Class Reference abstract
Spectrum Models
spectrum-aware propagation loss model
#include "spectrum-propagation-loss-model.h"
Public Member Functions
SpectrumPropagationLossModel ()
virtual ~SpectrumPropagationLossModel ()
Ptr< SpectrumValue > CalcRxPowerSpectralDensity (Ptr< const SpectrumValue > txPsd, Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const
This method is to be called to calculate.
void SetNext (Ptr< SpectrumPropagationLossModel > next)
Used to chain various instances of SpectrumPropagationLossModel.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose ()
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
virtual Ptr< SpectrumValue > DoCalcRxPowerSpectralDensity (Ptr< const SpectrumValue > txPsd, Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const =0
Private Attributes
Ptr< SpectrumPropagationLossModel > m_next
SpectrumPropagationLossModel chained to this one.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
spectrum-aware propagation loss model
Interface for propagation loss models to be adopted when transmissions are modeled with a power spectral density by means of the SpectrumValue class.
Definition at line 44 of file spectrum-propagation-loss-model.h.
Constructor & Destructor Documentation
SpectrumPropagationLossModel()
ns3::SpectrumPropagationLossModel::SpectrumPropagationLossModel ()
Definition at line 31 of file spectrum-propagation-loss-model.cc.
~SpectrumPropagationLossModel()
ns3::SpectrumPropagationLossModel::~SpectrumPropagationLossModel () virtual
Definition at line 36 of file spectrum-propagation-loss-model.cc.
Member Function Documentation
CalcRxPowerSpectralDensity()
Ptr< SpectrumValue > ns3::SpectrumPropagationLossModel::CalcRxPowerSpectralDensity (Ptr< const SpectrumValue > txPsd, Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const
This method is to be called to calculate.
Parameters
txPsd the SpectrumValue representing the power spectral density of the transmission. Watt units are to be used for radio communications, and Pascal units for acoustic communications (e.g., underwater).
a sender mobility
b receiver mobility
Returns
set of values Vs frequency representing the received power in the same units used for the txPower parameter.
Definition at line 64 of file spectrum-propagation-loss-model.cc.
References DoCalcRxPowerSpectralDensity(), and m_next.
DoCalcRxPowerSpectralDensity()
virtual Ptr<SpectrumValue> ns3::SpectrumPropagationLossModel::DoCalcRxPowerSpectralDensity (Ptr< const SpectrumValue > txPsd, Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const private pure virtual
Parameters
txPsd set of values Vs frequency representing the transmission power. See SpectrumChannel for details.
a sender mobility
b receiver mobility
Returns
set of values Vs frequency representing the received power in the same units used for the txPower parameter.
Implemented in ns3::TraceFadingLossModel, ns3::ThreeGppSpectrumPropagationLossModel, ns3::FriisSpectrumPropagationLossModel, and ns3::ConstantSpectrumPropagationLossModel.
Referenced by CalcRxPowerSpectralDensity().
DoDispose()
void ns3::SpectrumPropagationLossModel::DoDispose () protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 41 of file spectrum-propagation-loss-model.cc.
References m_next.
GetTypeId()
TypeId ns3::SpectrumPropagationLossModel::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 47 of file spectrum-propagation-loss-model.cc.
References ns3::TypeId::SetParent().
SetNext()
void ns3::SpectrumPropagationLossModel::SetNext (Ptr< SpectrumPropagationLossModel > next)
Used to chain various instances of SpectrumPropagationLossModel.
Parameters
next
Definition at line 57 of file spectrum-propagation-loss-model.cc.
References m_next.
Referenced by ns3::TraceFadingLossModel::TraceFadingLossModel().
Member Data Documentation
m_next
Ptr<SpectrumPropagationLossModel> ns3::SpectrumPropagationLossModel::m_next private
SpectrumPropagationLossModel chained to this one.
Definition at line 100 of file spectrum-propagation-loss-model.h.
Referenced by CalcRxPowerSpectralDensity(), DoDispose(), and SetNext().
The documentation for this class was generated from the following files:
src/spectrum/model/spectrum-propagation-loss-model.h
src/spectrum/model/spectrum-propagation-loss-model.cc