ns-3: ns3::ComponentCarrier Class Reference
ns3::ComponentCarrier Class Reference
LTE Models
#include "component-carrier.h"
Public Member Functions
ComponentCarrier ()
virtual ~ComponentCarrier (void)
virtual void DoDispose (void)
Destructor implementation.
uint32_t GetCsgId () const
Returns the CSG ID of the eNodeB.
bool GetCsgIndication () const
Returns the CSG indication flag of the eNodeB.
uint16_t GetDlBandwidth () const
uint32_t GetDlEarfcn () const
uint16_t GetUlBandwidth () const
uint32_t GetUlEarfcn () const
bool IsPrimary () const
Checks if the carrier is the primary carrier.
void SetAsPrimary (bool primaryCarrier)
Set as primary carrier.
void SetCsgId (uint32_t csgId)
Associate the eNodeB device with a particular CSG.
void SetCsgIndication (bool csgIndication)
Enable or disable the CSG indication flag.
virtual void SetDlBandwidth (uint16_t bw)
void SetDlEarfcn (uint32_t earfcn)
virtual void SetUlBandwidth (uint16_t bw)
void SetUlEarfcn (uint32_t earfcn)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Attributes
uint32_t m_csgId {0}
CSG ID.
bool m_csgIndication {false}
CSG indication.
uint16_t m_dlBandwidth {0}
downlink bandwidth in RBs *‍/
uint32_t m_dlEarfcn {0}
downlink carrier frequency *‍/
bool m_primaryCarrier {false}
whether the carrier is primary
uint16_t m_ulBandwidth {0}
uplink bandwidth in RBs *‍/
uint32_t m_ulEarfcn {0}
uplink carrier frequency *‍/
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
ComponentCarrier Object, it defines a single Carrier This is the parent class for both ComponentCarrierBaseStation and ComponentCarrierUe. This class contains the main physical configuration parameters for a carrier. Does not contain pointers to the MAC/PHY objects of the carrier.
Definition at line 39 of file component-carrier.h.
Constructor & Destructor Documentation
ComponentCarrier()
ns3::ComponentCarrier::ComponentCarrier ()
Definition at line 90 of file component-carrier.cc.
References NS_LOG_FUNCTION.
~ComponentCarrier()
ns3::ComponentCarrier::~ComponentCarrier (void) virtual
Definition at line 95 of file component-carrier.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::ComponentCarrier::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Reimplemented in ns3::ComponentCarrierUe, and ns3::ComponentCarrierEnb.
Definition at line 101 of file component-carrier.cc.
References ns3::Object::DoDispose(), and NS_LOG_FUNCTION.
GetCsgId()
uint32_t ns3::ComponentCarrier::GetCsgId () const
Returns the CSG ID of the eNodeB.
Returns
the Closed Subscriber Group identity
See also
LteEnbNetDevice::SetCsgId
Definition at line 188 of file component-carrier.cc.
References m_csgId.
Referenced by GetTypeId().
GetCsgIndication()
bool ns3::ComponentCarrier::GetCsgIndication () const
Returns the CSG indication flag of the eNodeB.
Returns
the CSG indication flag
See also
LteEnbNetDevice::SetCsgIndication
Definition at line 201 of file component-carrier.cc.
References m_csgIndication.
Referenced by GetTypeId().
GetDlBandwidth()
uint16_t ns3::ComponentCarrier::GetDlBandwidth () const
Returns
the downlink bandwidth in RBs
Definition at line 135 of file component-carrier.cc.
References m_dlBandwidth.
Referenced by GetTypeId(), and Print().
GetDlEarfcn()
uint32_t ns3::ComponentCarrier::GetDlEarfcn () const
Returns
the downlink carrier frequency (EARFCN)
Definition at line 162 of file component-carrier.cc.
References m_dlEarfcn.
Referenced by ns3::CcHelper::CreateSingleCc(), GetTypeId(), and Print().
GetTypeId()
TypeId ns3::ComponentCarrier::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 33 of file component-carrier.cc.
References GetCsgId(), GetCsgIndication(), GetDlBandwidth(), GetDlEarfcn(), GetUlBandwidth(), GetUlEarfcn(), IsPrimary(), ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeUintegerAccessor(), SetAsPrimary(), SetCsgId(), SetCsgIndication(), SetDlBandwidth(), SetDlEarfcn(), ns3::TypeId::SetParent(), SetUlBandwidth(), and SetUlEarfcn().
Referenced by ns3::CcHelper::CcHelper().
GetUlBandwidth()
uint16_t ns3::ComponentCarrier::GetUlBandwidth () const
Returns
the uplink bandwidth in RBs
Definition at line 108 of file component-carrier.cc.
References m_ulBandwidth.
Referenced by GetTypeId(), and Print().
GetUlEarfcn()
uint32_t ns3::ComponentCarrier::GetUlEarfcn () const
Returns
the uplink carrier frequency (EARFCN)
Definition at line 175 of file component-carrier.cc.
References m_ulEarfcn.
Referenced by ns3::CcHelper::CreateSingleCc(), GetTypeId(), and Print().
IsPrimary()
bool ns3::ComponentCarrier::IsPrimary () const
Checks if the carrier is the primary carrier.
Returns
true if the carrier is primary
Definition at line 214 of file component-carrier.cc.
References m_primaryCarrier.
Referenced by GetTypeId(), and Print().
SetAsPrimary()
void ns3::ComponentCarrier::SetAsPrimary (bool primaryCarrier)
Set as primary carrier.
Parameters
primaryCarrier true to set as primary carrier
Definition at line 220 of file component-carrier.cc.
References m_primaryCarrier, and NS_LOG_FUNCTION.
Referenced by ns3::CcHelper::CreateSingleCc(), and GetTypeId().
SetCsgId()
void ns3::ComponentCarrier::SetCsgId (uint32_t csgId)
Associate the eNodeB device with a particular CSG.
Parameters
csgId the intended Closed Subscriber Group identity
CSG identity is a number identifying a Closed Subscriber Group which the cell belongs to. eNodeB is associated with a single CSG identity.
The same CSG identity can also be associated to several UEs, which is equivalent as enlisting these UEs as the members of this particular CSG.
See also
LteEnbNetDevice::SetCsgIndication
Definition at line 194 of file component-carrier.cc.
References m_csgId, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetCsgIndication()
void ns3::ComponentCarrier::SetCsgIndication (bool csgIndication)
Enable or disable the CSG indication flag.
Parameters
csgIndication if TRUE, only CSG members are allowed to access this cell
When the CSG indication field is set to TRUE, only UEs which are members of the CSG (i.e. same CSG ID) can gain access to the eNodeB, therefore enforcing closed access mode. Otherwise, the eNodeB operates as a non-CSG cell and implements open access mode.
Note
This restriction only applies to initial cell selection and EPC-enabled simulation.
See also
LteEnbNetDevice::SetCsgIndication
Definition at line 207 of file component-carrier.cc.
References m_csgIndication, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetDlBandwidth()
void ns3::ComponentCarrier::SetDlBandwidth (uint16_t bw) virtual
Parameters
bw the downlink bandwidth in RBs
Definition at line 141 of file component-carrier.cc.
References m_dlBandwidth, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
Referenced by ns3::CcHelper::CreateSingleCc(), and GetTypeId().
SetDlEarfcn()
void ns3::ComponentCarrier::SetDlEarfcn (uint32_t earfcn)
Parameters
earfcn the downlink carrier frequency (EARFCN)
Definition at line 168 of file component-carrier.cc.
References m_dlEarfcn, and NS_LOG_FUNCTION.
Referenced by ns3::CcHelper::CreateSingleCc(), and GetTypeId().
SetUlBandwidth()
void ns3::ComponentCarrier::SetUlBandwidth (uint16_t bw) virtual
Parameters
bw the uplink bandwidth in RBs
Definition at line 114 of file component-carrier.cc.
References m_ulBandwidth, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
Referenced by ns3::CcHelper::CreateSingleCc(), and GetTypeId().
SetUlEarfcn()
void ns3::ComponentCarrier::SetUlEarfcn (uint32_t earfcn)
Parameters
earfcn the uplink carrier frequency (EARFCN)
Definition at line 181 of file component-carrier.cc.
References m_ulEarfcn, and NS_LOG_FUNCTION.
Referenced by ns3::CcHelper::CreateSingleCc(), and GetTypeId().
Member Data Documentation
m_csgId
uint32_t ns3::ComponentCarrier::m_csgId {0} protected
CSG ID.
Definition at line 151 of file component-carrier.h.
Referenced by GetCsgId(), and SetCsgId().
m_csgIndication
bool ns3::ComponentCarrier::m_csgIndication {false} protected
CSG indication.
Definition at line 152 of file component-carrier.h.
Referenced by GetCsgIndication(), and SetCsgIndication().
m_dlBandwidth
uint16_t ns3::ComponentCarrier::m_dlBandwidth {0} protected
downlink bandwidth in RBs *‍/
Definition at line 156 of file component-carrier.h.
Referenced by GetDlBandwidth(), and SetDlBandwidth().
m_dlEarfcn
uint32_t ns3::ComponentCarrier::m_dlEarfcn {0} protected
downlink carrier frequency *‍/
Definition at line 159 of file component-carrier.h.
Referenced by GetDlEarfcn(), and SetDlEarfcn().
m_primaryCarrier
bool ns3::ComponentCarrier::m_primaryCarrier {false} protected
whether the carrier is primary
Definition at line 154 of file component-carrier.h.
Referenced by IsPrimary(), and SetAsPrimary().
m_ulBandwidth
uint16_t ns3::ComponentCarrier::m_ulBandwidth {0} protected
uplink bandwidth in RBs *‍/
Definition at line 157 of file component-carrier.h.
Referenced by GetUlBandwidth(), and SetUlBandwidth().
m_ulEarfcn
uint32_t ns3::ComponentCarrier::m_ulEarfcn {0} protected
uplink carrier frequency *‍/
Definition at line 160 of file component-carrier.h.
Referenced by GetUlEarfcn(), and SetUlEarfcn().
The documentation for this class was generated from the following files:
src/lte/model/component-carrier.h
src/lte/model/component-carrier.cc