ns-3: ns3::ChannelListPriv Class Reference
ns3::ChannelListPriv Class Reference
Network
private implementation detail of the ChannelList API.
Public Member Functions
ChannelListPriv ()
~ChannelListPriv ()
uint32_t Add (Ptr< Channel > channel)
ChannelList::Iterator Begin (void) const
ChannelList::Iterator End (void) const
Ptr< Channel > GetChannel (uint32_t n)
uint32_t GetNChannels (void)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static Ptr< ChannelListPriv > Get (void)
Get the channel list object.
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual void DoDispose (void)
Dispose the channels in the list.
Static Private Member Functions
static void Delete (void)
Delete the channel list object.
static Ptr< ChannelListPriv > * DoGet (void)
Get the channel list object.
Private Attributes
std::vector< Ptr< Channel > > m_channels
channel objects container
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
private implementation detail of the ChannelList API.
Definition at line 36 of file channel-list.cc.
Constructor & Destructor Documentation
ChannelListPriv()
ns3::ChannelListPriv::ChannelListPriv ()
Definition at line 149 of file channel-list.cc.
References NS_LOG_FUNCTION.
~ChannelListPriv()
ns3::ChannelListPriv::~ChannelListPriv ()
Definition at line 154 of file channel-list.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Add()
uint32_t ns3::ChannelListPriv::Add (Ptr< Channel > channel)
Parameters
channel channel to add
Returns
index of channel in list.
This method is called automatically from Channel::Channel so the user has little reason to call it himself.
Definition at line 174 of file channel-list.cc.
References third::channel, m_channels, and NS_LOG_FUNCTION.
Begin()
ChannelList::Iterator ns3::ChannelListPriv::Begin (void) const
Returns
a C++ iterator located at the beginning of this list.
Definition at line 184 of file channel-list.cc.
References m_channels, and NS_LOG_FUNCTION.
Delete()
void ns3::ChannelListPriv::Delete (void) static private
Delete the channel list object.
Definition at line 142 of file channel-list.cc.
References DoGet(), Get(), NS_LOG_FUNCTION_NOARGS, and ns3::Config::UnregisterRootNamespaceObject().
Referenced by DoGet().
DoDispose()
void ns3::ChannelListPriv::DoDispose (void) private virtual
Dispose the channels in the list.
Reimplemented from ns3::Object.
Definition at line 159 of file channel-list.cc.
References third::channel, ns3::Object::DoDispose(), m_channels, and NS_LOG_FUNCTION.
DoGet()
Ptr< ChannelListPriv > * ns3::ChannelListPriv::DoGet (void) static private
Get the channel list object.
Returns
the channel list
Definition at line 128 of file channel-list.cc.
References Delete(), NS_LOG_FUNCTION_NOARGS, ns3::Config::RegisterRootNamespaceObject(), and ns3::Simulator::ScheduleDestroy().
Referenced by Delete(), and Get().
End()
ChannelList::Iterator ns3::ChannelListPriv::End (void) const
Returns
a C++ iterator located at the end of this list.
Definition at line 191 of file channel-list.cc.
References m_channels, and NS_LOG_FUNCTION.
Get()
Ptr< ChannelListPriv > ns3::ChannelListPriv::Get (void) static
Get the channel list object.
Returns
the channel list
Definition at line 121 of file channel-list.cc.
References DoGet(), and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::ChannelList::Add(), ns3::ChannelList::Begin(), Delete(), ns3::ChannelList::End(), ns3::ChannelList::GetChannel(), and ns3::ChannelList::GetNChannels().
GetChannel()
Ptr< Channel > ns3::ChannelListPriv::GetChannel (uint32_t n)
Parameters
n index of requested channel.
Returns
the Channel associated to index n.
Definition at line 205 of file channel-list.cc.
References m_channels, sample-rng-plot::n, NS_ASSERT_MSG(), and NS_LOG_FUNCTION.
GetNChannels()
uint32_t ns3::ChannelListPriv::GetNChannels (void)
Returns
the number of channels currently in the list.
Definition at line 198 of file channel-list.cc.
References m_channels, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::ChannelListPriv::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 107 of file channel-list.cc.
References m_channels, ns3::MakeObjectVectorAccessor(), and ns3::TypeId::SetParent().
Member Data Documentation
m_channels
std::vector<Ptr<Channel> > ns3::ChannelListPriv::m_channels private
channel objects container
Definition at line 101 of file channel-list.cc.
Referenced by Add(), Begin(), DoDispose(), End(), GetChannel(), GetNChannels(), and GetTypeId().
The documentation for this class was generated from the following file:
src/network/model/channel-list.cc