ns-3: ns3::LteHandoverManagementSapUser Class Reference
ns3::LteHandoverManagementSapUser Class Reference abstract
Service Access Point (SAP) offered by the eNodeB RRC instance to the handover algorithm instance.
#include "lte-handover-management-sap.h"
Public Member Functions
virtual ~LteHandoverManagementSapUser ()
virtual uint8_t AddUeMeasReportConfigForHandover (LteRrcSap::ReportConfigEutra reportConfig)=0
Request a certain reporting configuration to be fulfilled by the UEs attached to the eNodeB entity.
virtual void TriggerHandover (uint16_t rnti, uint16_t targetCellId)=0
Instruct the eNodeB RRC entity to prepare a handover.
Detailed Description
Service Access Point (SAP) offered by the eNodeB RRC instance to the handover algorithm instance.
This is the Handover Management SAP User, i.e., the part of the SAP that contains the eNodeB RRC methods called by the handover algorithm instance.
Definition at line 67 of file lte-handover-management-sap.h.
Constructor & Destructor Documentation
~LteHandoverManagementSapUser()
ns3::LteHandoverManagementSapUser::~LteHandoverManagementSapUser () virtual
Definition at line 32 of file lte-handover-management-sap.cc.
Member Function Documentation
AddUeMeasReportConfigForHandover()
virtual uint8_t ns3::LteHandoverManagementSapUser::AddUeMeasReportConfigForHandover (LteRrcSap::ReportConfigEutra reportConfig) pure virtual
Request a certain reporting configuration to be fulfilled by the UEs attached to the eNodeB entity.
Parameters
reportConfig the UE measurement reporting configuration
Returns
the measurement identity associated with this newly added reporting configuration
The eNodeB RRC entity is expected to configure the same reporting configuration in each of the attached UEs. When later in the simulation a UE measurement report is received from a UE as a result of this configuration, the eNodeB RRC entity shall forward this report to the handover algorithm through the LteHandoverManagementSapProvider::ReportUeMeas SAP function.
Note
This function is only valid before the simulation begins.
Implemented in ns3::MemberLteHandoverManagementSapUser< C >.
Referenced by ns3::A2A4RsrqHandoverAlgorithm::DoInitialize(), and ns3::A3RsrpHandoverAlgorithm::DoInitialize().
TriggerHandover()
virtual void ns3::LteHandoverManagementSapUser::TriggerHandover (uint16_t rnti, uint16_t targetCellId) pure virtual
Instruct the eNodeB RRC entity to prepare a handover.
Parameters
rnti Radio Network Temporary Identity, an integer identifying the UE which shall perform the handover
targetCellId the cell ID of the target eNodeB
This function is used by the handover algorithm entity when a handover decision has been reached.
The process to produce the decision is up to the implementation of handover algorithm. It is typically based on the reported UE measurements, which are received through the LteHandoverManagementSapProvider::ReportUeMeas function.
Implemented in ns3::MemberLteHandoverManagementSapUser< C >.
Referenced by ns3::A3RsrpHandoverAlgorithm::DoReportUeMeas(), and ns3::A2A4RsrqHandoverAlgorithm::EvaluateHandover().
The documentation for this class was generated from the following files:
src/lte/model/lte-handover-management-sap.h
src/lte/model/lte-handover-management-sap.cc