ns-3: ns3::PlanetLabFdNetDeviceHelper Class Reference
ns3::PlanetLabFdNetDeviceHelper Class Reference
File Descriptor Network Device
build a set of FdNetDevice objects attached to a virtual TAP network interface
#include "planetlab-fd-net-device-helper.h"
Public Member Functions
PlanetLabFdNetDeviceHelper ()
Construct a PlanetLabFdNetDeviceHelper.
virtual ~PlanetLabFdNetDeviceHelper ()
void SetTapIpAddress (Ipv4Address address)
Set the device IPv4 address.
void SetTapMask (Ipv4Mask mask)
Set the network mask for the TAP device.
Public Member Functions inherited from ns3::EmuFdNetDeviceHelper
EmuFdNetDeviceHelper ()
Construct a EmuFdNetDeviceHelper.
virtual ~EmuFdNetDeviceHelper ()
std::string GetDeviceName (void)
Get the device name of this device.
void SetDeviceName (std::string deviceName)
Set the device name of this device.
Public Member Functions inherited from ns3::FdNetDeviceHelper
FdNetDeviceHelper ()
Construct a FdNetDeviceHelper.
virtual ~FdNetDeviceHelper ()
virtual NetDeviceContainer Install (const NodeContainer &c) const
This method creates a FdNetDevice and associates it to a node.
virtual NetDeviceContainer Install (Ptr< Node > node) const
This method creates a FdNetDevice and associates it to a node.
virtual NetDeviceContainer Install (std::string name) const
This method creates a FdNetDevice and associates it to a node.
void SetAttribute (std::string n1, const AttributeValue &v1)
Public Member Functions inherited from ns3::PcapHelperForDevice
PcapHelperForDevice ()
Construct a PcapHelperForDevice.
virtual ~PcapHelperForDevice ()
Destroy a PcapHelperForDevice.
void EnablePcap (std::string prefix, NetDeviceContainer d, bool promiscuous=false)
Enable pcap output on each device in the container which is of the appropriate type.
void EnablePcap (std::string prefix, NodeContainer n, bool promiscuous=false)
Enable pcap output on each device (which is of the appropriate type) in the nodes provided in the container.
void EnablePcap (std::string prefix, Ptr< NetDevice > nd, bool promiscuous=false, bool explicitFilename=false)
Enable pcap output the indicated net device.
void EnablePcap (std::string prefix, std::string ndName, bool promiscuous=false, bool explicitFilename=false)
Enable pcap output the indicated net device using a device previously named using the ns-3 object name service.
void EnablePcap (std::string prefix, uint32_t nodeid, uint32_t deviceid, bool promiscuous=false)
Enable pcap output on the device specified by a global node-id (of a previously created node) and associated device-id.
void EnablePcapAll (std::string prefix, bool promiscuous=false)
Enable pcap output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
Public Member Functions inherited from ns3::AsciiTraceHelperForDevice
AsciiTraceHelperForDevice ()
Construct an AsciiTraceHelperForDevice.
virtual ~AsciiTraceHelperForDevice ()
Destroy an AsciiTraceHelperForDevice.
void EnableAscii (Ptr< OutputStreamWrapper > stream, NetDeviceContainer d)
Enable ascii trace output on each device in the container which is of the appropriate type.
void EnableAscii (Ptr< OutputStreamWrapper > stream, NodeContainer n)
Enable ascii trace output on each device (which is of the appropriate type) in the nodes provided in the container.
void EnableAscii (Ptr< OutputStreamWrapper > stream, Ptr< NetDevice > nd)
Enable ascii trace output on the indicated net device.
void EnableAscii (Ptr< OutputStreamWrapper > stream, std::string ndName)
Enable ascii trace output the indicated net device using a device previously named using the ns-3 object name service.
void EnableAscii (Ptr< OutputStreamWrapper > stream, uint32_t nodeid, uint32_t deviceid)
Enable ascii trace output on the device specified by a global node-id (of a previously created node) and associated device-id.
void EnableAscii (std::string prefix, NetDeviceContainer d)
Enable ascii trace output on each device in the container which is of the appropriate type.
void EnableAscii (std::string prefix, NodeContainer n)
Enable ascii trace output on each device (which is of the appropriate type) in the nodes provided in the container.
void EnableAscii (std::string prefix, Ptr< NetDevice > nd, bool explicitFilename=false)
Enable ascii trace output on the indicated net device.
void EnableAscii (std::string prefix, std::string ndName, bool explicitFilename=false)
Enable ascii trace output the indicated net device using a device previously named using the ns-3 object name service.
void EnableAscii (std::string prefix, uint32_t nodeid, uint32_t deviceid, bool explicitFilename)
Enable ascii trace output on the device specified by a global node-id (of a previously created node) and associated device-id.
void EnableAsciiAll (Ptr< OutputStreamWrapper > stream)
Enable ascii trace output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
void EnableAsciiAll (std::string prefix)
Enable ascii trace output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
Protected Member Functions
virtual int CreateFileDescriptor (void) const
Call out to a separate process running as suid root in order to create a TAP device and obtain the file descriptor associated to it.
Ptr< NetDevice > InstallPriv (Ptr< Node > node) const
This method creates an ns3::FdNetDevice attached to a virtual TAP network interface.
virtual void SetFileDescriptor (Ptr< FdNetDevice > device) const
Sets a file descriptor on the FileDescriptorNetDevice.
Protected Attributes
Ipv4Address m_tapIp
The IP address for the TAP device.
Ipv4Mask m_tapMask
The network mask for the TAP device.
Protected Attributes inherited from ns3::EmuFdNetDeviceHelper
std::string m_deviceName
The unix/linux name of the underlying device (e.g., eth0)
Detailed Description
build a set of FdNetDevice objects attached to a virtual TAP network interface
Definition at line 44 of file planetlab-fd-net-device-helper.h.
Constructor & Destructor Documentation
PlanetLabFdNetDeviceHelper()
ns3::PlanetLabFdNetDeviceHelper::PlanetLabFdNetDeviceHelper ()
Construct a PlanetLabFdNetDeviceHelper.
Definition at line 67 of file planetlab-fd-net-device-helper.cc.
References m_tapIp, and m_tapMask.
~PlanetLabFdNetDeviceHelper()
virtual ns3::PlanetLabFdNetDeviceHelper::~PlanetLabFdNetDeviceHelper () inline virtual
Definition at line 51 of file planetlab-fd-net-device-helper.h.
Member Function Documentation
CreateFileDescriptor()
int ns3::PlanetLabFdNetDeviceHelper::CreateFileDescriptor (void) const protected virtual
Call out to a separate process running as suid root in order to create a TAP device and obtain the file descriptor associated to it.
Reimplemented from ns3::EmuFdNetDeviceHelper.
Definition at line 120 of file planetlab-fd-net-device-helper.cc.
References ns3::BufferToString(), ns3::Ipv4Mask::GetPrefixLength(), m_tapIp, m_tapMask, NS_ABORT_MSG_IF, NS_ASSERT_MSG(), NS_FATAL_ERROR, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, and PLANETLAB_MAGIC.
Referenced by SetFileDescriptor().
InstallPriv()
Ptr< NetDevice > ns3::PlanetLabFdNetDeviceHelper::InstallPriv (Ptr< Node > node) const protected virtual
This method creates an ns3::FdNetDevice attached to a virtual TAP network interface.
Parameters
node The node to install the device in
Returns
A container holding the added net device.
Reimplemented from ns3::EmuFdNetDeviceHelper.
Definition at line 86 of file planetlab-fd-net-device-helper.cc.
References ns3::FdNetDevice::DIXPI, ns3::FdNetDeviceHelper::InstallPriv(), ns3::FdNetDevice::SetEncapsulationMode(), and SetFileDescriptor().
SetFileDescriptor()
void ns3::PlanetLabFdNetDeviceHelper::SetFileDescriptor (Ptr< FdNetDevice > device) const protected virtual
Sets a file descriptor on the FileDescriptorNetDevice.
Reimplemented from ns3::EmuFdNetDeviceHelper.
Definition at line 107 of file planetlab-fd-net-device-helper.cc.
References CreateFileDescriptor(), and NS_LOG_LOGIC().
Referenced by InstallPriv().
SetTapIpAddress()
void ns3::PlanetLabFdNetDeviceHelper::SetTapIpAddress (Ipv4Address address)
Set the device IPv4 address.
Parameters
address The IPv4 address for the TAP device.
Definition at line 74 of file planetlab-fd-net-device-helper.cc.
References first::address, and m_tapIp.
SetTapMask()
void ns3::PlanetLabFdNetDeviceHelper::SetTapMask (Ipv4Mask mask)
Set the network mask for the TAP device.
Parameters
mask The network mask for the TAP device.
Definition at line 80 of file planetlab-fd-net-device-helper.cc.
References m_tapMask.
Member Data Documentation
m_tapIp
Ipv4Address ns3::PlanetLabFdNetDeviceHelper::m_tapIp protected
The IP address for the TAP device.
Definition at line 94 of file planetlab-fd-net-device-helper.h.
Referenced by PlanetLabFdNetDeviceHelper(), CreateFileDescriptor(), and SetTapIpAddress().
m_tapMask
Ipv4Mask ns3::PlanetLabFdNetDeviceHelper::m_tapMask protected
The network mask for the TAP device.
Definition at line 99 of file planetlab-fd-net-device-helper.h.
Referenced by PlanetLabFdNetDeviceHelper(), CreateFileDescriptor(), and SetTapMask().
The documentation for this class was generated from the following files:
src/fd-net-device/helper/planetlab-fd-net-device-helper.h
src/fd-net-device/helper/planetlab-fd-net-device-helper.cc