ns-3: ns3::HigherLayerTxVectorTag Class Reference
ns3::HigherLayerTxVectorTag Class Reference
Network » Packet | WAVE module
This tag will be used to support higher layer control DataRate and TxPwr_Level for transmission. If the high layer enables adaptable mode, DataRate will be the minimum allowable value and TxPwr_Level will be the maximum allowable value for transmission. If the higher layer does not enable adaptable parameter, the DataRate and TxPwr_Level will be actual values for transmission. However, if this tag is not used and inserted in the packet, the actual DataRate and TxPwr_Level for transmission will be determined by MAC layer.
#include "higher-tx-tag.h"
Public Member Functions
HigherLayerTxVectorTag (void)
HigherLayerTxVectorTag (WifiTxVector txVector, bool adaptable)
Constructor.
virtual void Deserialize (TagBuffer i)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize (void) const
WifiTxVector GetTxVector (void) const
bool IsAdaptable (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer i) const
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
bool m_adaptable
adaptable
WifiTxVector m_txVector
transmit vector
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This tag will be used to support higher layer control DataRate and TxPwr_Level for transmission. If the high layer enables adaptable mode, DataRate will be the minimum allowable value and TxPwr_Level will be the maximum allowable value for transmission. If the higher layer does not enable adaptable parameter, the DataRate and TxPwr_Level will be actual values for transmission. However, if this tag is not used and inserted in the packet, the actual DataRate and TxPwr_Level for transmission will be determined by MAC layer.
Definition at line 47 of file higher-tx-tag.h.
Constructor & Destructor Documentation
HigherLayerTxVectorTag() [1/2]
ns3::HigherLayerTxVectorTag::HigherLayerTxVectorTag (void)
Definition at line 49 of file higher-tx-tag.cc.
References NS_LOG_FUNCTION.
HigherLayerTxVectorTag() [2/2]
ns3::HigherLayerTxVectorTag::HigherLayerTxVectorTag (WifiTxVector txVector, bool adaptable)
Constructor.
Parameters
txVector wifi transmit vector
adaptable is adaptable?
Definition at line 55 of file higher-tx-tag.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Deserialize()
void ns3::HigherLayerTxVectorTag::Deserialize (TagBuffer i) virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 92 of file higher-tx-tag.cc.
References m_adaptable, m_txVector, NS_LOG_FUNCTION, ns3::TagBuffer::Read(), and ns3::TagBuffer::ReadU8().
GetInstanceTypeId()
TypeId ns3::HigherLayerTxVectorTag::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 43 of file higher-tx-tag.cc.
References GetTypeId(), and NS_LOG_FUNCTION.
GetSerializedSize()
uint32_t ns3::HigherLayerTxVectorTag::GetSerializedSize (void) const virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 77 of file higher-tx-tag.cc.
References NS_LOG_FUNCTION.
GetTxVector()
WifiTxVector ns3::HigherLayerTxVectorTag::GetTxVector (void) const
Returns
the tx vector for transmission
Definition at line 63 of file higher-tx-tag.cc.
References m_txVector, and NS_LOG_FUNCTION.
Referenced by ns3::WaveMacLow::GetDataTxVector().
GetTypeId()
TypeId ns3::HigherLayerTxVectorTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 32 of file higher-tx-tag.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
IsAdaptable()
bool ns3::HigherLayerTxVectorTag::IsAdaptable (void) const
Returns
the adaptable mode for transmission
Definition at line 70 of file higher-tx-tag.cc.
References m_adaptable, and NS_LOG_FUNCTION.
Referenced by ns3::WaveMacLow::GetDataTxVector().
Print()
void ns3::HigherLayerTxVectorTag::Print (std::ostream & os) const virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 100 of file higher-tx-tag.cc.
References m_adaptable, m_txVector, and NS_LOG_FUNCTION.
Serialize()
void ns3::HigherLayerTxVectorTag::Serialize (TagBuffer i) const virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 84 of file higher-tx-tag.cc.
References m_adaptable, m_txVector, NS_LOG_FUNCTION, ns3::TagBuffer::Write(), and ns3::TagBuffer::WriteU8().
Member Data Documentation
m_adaptable
bool ns3::HigherLayerTxVectorTag::m_adaptable private
adaptable
Definition at line 81 of file higher-tx-tag.h.
Referenced by Deserialize(), IsAdaptable(), Print(), and Serialize().
m_txVector
WifiTxVector ns3::HigherLayerTxVectorTag::m_txVector private
transmit vector
Definition at line 80 of file higher-tx-tag.h.
Referenced by Deserialize(), GetTxVector(), Print(), and Serialize().
The documentation for this class was generated from the following files:
src/wave/model/higher-tx-tag.h
src/wave/model/higher-tx-tag.cc