ns-3: Ipv4RawSocketImplTest Class Reference
Ipv4RawSocketImplTest Class Reference
Internet » internet module tests | Test suites
IPv4 RAW Socket Test.
Public Member Functions
Ipv4RawSocketImplTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
void ReceivePacket (Ptr< Socket > socket, Ptr< Packet > packet, const Address &from)
Receive data.
void ReceivePacket2 (Ptr< Socket > socket, Ptr< Packet > packet, const Address &from)
Receive data.
void ReceivePkt (Ptr< Socket > socket)
Receive data.
void ReceivePkt2 (Ptr< Socket > socket)
Receive data.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void DoSendData (Ptr< Socket > socket, std::string to)
Send data.
void DoSendData_IpHdr (Ptr< Socket > socket, std::string to)
Send data.
void SendData (Ptr< Socket > socket, std::string to)
Send data.
void SendData_IpHdr (Ptr< Socket > socket, std::string to)
Send data.
Private Attributes
Ptr< Packet > m_receivedPacket
Received packet (1).
Ptr< Packet > m_receivedPacket2
Received packet (2).
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
IPv4 RAW Socket Test.
Definition at line 60 of file ipv4-raw-test.cc.
Constructor & Destructor Documentation
Ipv4RawSocketImplTest()
Ipv4RawSocketImplTest::Ipv4RawSocketImplTest ()
Definition at line 121 of file ipv4-raw-test.cc.
Member Function Documentation
DoRun()
void Ipv4RawSocketImplTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 204 of file ipv4-raw-test.cc.
References ns3::Ipv4::AddAddress(), ns3::Ipv4::AddInterface(), ns3::Socket::Bind(), ns3::SocketFactory::CreateSocket(), ns3::Object::Dispose(), ns3::NetDeviceContainer::Get(), ns3::Object::GetObject(), ns3::Packet::GetSize(), ns3::SimpleNetDeviceHelper::Install(), ns3::InternetStackHelper::Install(), m_receivedPacket, m_receivedPacket2, ns3::MakeCallback(), first::nodes, NS_TEST_EXPECT_MSG_EQ, ReceivePkt(), ReceivePkt2(), ns3::Packet::RemoveAllByteTags(), SendData(), SendData_IpHdr(), ns3::SimpleNetDeviceHelper::SetNetDevicePointToPointMode(), ns3::InetSocketAddress::SetPort(), ns3::Socket::SetRecvCallback(), and ns3::Ipv4::SetUp().
DoSendData()
void Ipv4RawSocketImplTest::DoSendData (Ptr< Socket > socket, std::string to) private
Send data.
Parameters
socket The sending socket.
to Destination address.
Definition at line 157 of file ipv4-raw-test.cc.
References NS_TEST_EXPECT_MSG_EQ, and ns3::Socket::SendTo().
Referenced by SendData().
DoSendData_IpHdr()
void Ipv4RawSocketImplTest::DoSendData_IpHdr (Ptr< Socket > socket, std::string to) private
Send data.
Parameters
socket The sending socket.
to Destination address.
Definition at line 175 of file ipv4-raw-test.cc.
References ns3::Packet::AddHeader(), ns3::Packet::GetSize(), NS_TEST_EXPECT_MSG_EQ, ns3::Socket::SendTo(), ns3::ObjectBase::SetAttribute(), ns3::Ipv4Header::SetDestination(), ns3::Ipv4Header::SetPayloadSize(), ns3::Ipv4Header::SetProtocol(), ns3::Ipv4Header::SetSource(), and ns3::Ipv4Header::SetTtl().
Referenced by SendData_IpHdr().
ReceivePacket()
void Ipv4RawSocketImplTest::ReceivePacket (Ptr< Socket > socket, Ptr< Packet > packet, const Address & from)
Receive data.
Parameters
socket The receiving socket.
packet The received packet.
from The sender.
Definition at line 126 of file ipv4-raw-test.cc.
References m_receivedPacket.
ReceivePacket2()
void Ipv4RawSocketImplTest::ReceivePacket2 (Ptr< Socket > socket, Ptr< Packet > packet, const Address & from)
Receive data.
Parameters
socket The receiving socket.
packet The received packet.
from The sender.
Definition at line 131 of file ipv4-raw-test.cc.
References m_receivedPacket2.
ReceivePkt()
void Ipv4RawSocketImplTest::ReceivePkt (Ptr< Socket > socket)
Receive data.
Parameters
socket The receiving socket.
Definition at line 136 of file ipv4-raw-test.cc.
References ns3::Socket::GetRxAvailable(), ns3::Packet::GetSize(), m_receivedPacket, max, NS_ASSERT, and ns3::Socket::Recv().
Referenced by DoRun().
ReceivePkt2()
void Ipv4RawSocketImplTest::ReceivePkt2 (Ptr< Socket > socket)
Receive data.
Parameters
socket The receiving socket.
Definition at line 146 of file ipv4-raw-test.cc.
References ns3::Socket::GetRxAvailable(), ns3::Packet::GetSize(), m_receivedPacket2, max, NS_ASSERT, and ns3::Socket::Recv().
Referenced by DoRun().
SendData()
void Ipv4RawSocketImplTest::SendData (Ptr< Socket > socket, std::string to) private
Send data.
Parameters
socket The sending socket.
to Destination address.
Definition at line 165 of file ipv4-raw-test.cc.
References DoSendData(), ns3::Node::GetId(), ns3::Socket::GetNode(), m_receivedPacket, m_receivedPacket2, and ns3::Seconds().
Referenced by DoRun().
SendData_IpHdr()
void Ipv4RawSocketImplTest::SendData_IpHdr (Ptr< Socket > socket, std::string to) private
Send data.
Parameters
socket The sending socket.
to Destination address.
Definition at line 194 of file ipv4-raw-test.cc.
References DoSendData_IpHdr(), ns3::Node::GetId(), ns3::Socket::GetNode(), m_receivedPacket, m_receivedPacket2, and ns3::Seconds().
Referenced by DoRun().
Member Data Documentation
m_receivedPacket
Ptr<Packet> Ipv4RawSocketImplTest::m_receivedPacket private
Received packet (1).
Definition at line 62 of file ipv4-raw-test.cc.
Referenced by DoRun(), ReceivePacket(), ReceivePkt(), SendData(), and SendData_IpHdr().
m_receivedPacket2
Ptr<Packet> Ipv4RawSocketImplTest::m_receivedPacket2 private
Received packet (2).
Definition at line 63 of file ipv4-raw-test.cc.
Referenced by DoRun(), ReceivePacket2(), ReceivePkt2(), SendData(), and SendData_IpHdr().
The documentation for this class was generated from the following file:
src/internet/test/ipv4-raw-test.cc