ns-3: CollisionExperiment Class Reference
CollisionExperiment Class Reference
CollisionExperiment.
Classes
struct Input
Input structure.
struct Output
Output struture.
Public Member Functions
CollisionExperiment ()
struct CollisionExperiment::Output Run (struct CollisionExperiment::Input input)
Run function.
Private Member Functions
void Receive (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector, std::vector< bool > statusPerMpdu)
Receive function.
void SendA (void) const
Send A function.
void SendB (void) const
Send B function.
Private Attributes
uint32_t m_flowIdA
flow ID A
uint32_t m_flowIdB
flow ID B
struct Input m_input
input
struct Output m_output
output
Ptr< WifiPhy > m_txA
transmit A
Ptr< WifiPhy > m_txB
transmit B
Detailed Description
CollisionExperiment.
Definition at line 151 of file wifi-phy-test.cc.
Constructor & Destructor Documentation
CollisionExperiment()
CollisionExperiment::CollisionExperiment ()
Definition at line 245 of file wifi-phy-test.cc.
Member Function Documentation
Receive()
void CollisionExperiment::Receive (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector, std::vector< bool > statusPerMpdu) private
Receive function.
Parameters
psdu the PSDU
snr the SNR
txVector the wifi transmit vector
statusPerMpdu reception status per MPDU
Definition at line 229 of file wifi-phy-test.cc.
References ns3::WifiPsdu::begin(), ns3::FlowIdTag::GetFlowId(), m_flowIdA, m_flowIdB, m_output, CollisionExperiment::Output::receivedA, and CollisionExperiment::Output::receivedB.
Run()
struct CollisionExperiment::Output CollisionExperiment::Run (struct CollisionExperiment::Input input)
Run function.
Parameters
input the collision experiment data
Returns
the experiment output
Definition at line 248 of file wifi-phy-test.cc.
SendA()
void CollisionExperiment::SendA (void) const private
Send A function.
Definition at line 205 of file wifi-phy-test.cc.
References ns3::WifiPsdu::begin(), m_flowIdA, m_input, m_txA, CollisionExperiment::Input::packetSizeA, ns3::WifiPhy::Send(), ns3::WifiTxVector::SetMode(), ns3::WifiTxVector::SetPreambleType(), ns3::WifiTxVector::SetTxPowerLevel(), CollisionExperiment::Input::txModeA, CollisionExperiment::Input::txPowerLevelA, and ns3::WIFI_PREAMBLE_LONG.
SendB()
void CollisionExperiment::SendB (void) const private
Send B function.
Definition at line 217 of file wifi-phy-test.cc.
References ns3::WifiPsdu::begin(), m_flowIdB, m_input, m_txB, CollisionExperiment::Input::packetSizeB, ns3::WifiPhy::Send(), ns3::WifiTxVector::SetMode(), ns3::WifiTxVector::SetPreambleType(), ns3::WifiTxVector::SetTxPowerLevel(), CollisionExperiment::Input::txModeB, CollisionExperiment::Input::txPowerLevelB, and ns3::WIFI_PREAMBLE_LONG.
Member Data Documentation
m_flowIdA
uint32_t CollisionExperiment::m_flowIdA private
flow ID A
Definition at line 198 of file wifi-phy-test.cc.
Referenced by Receive(), and SendA().
m_flowIdB
uint32_t CollisionExperiment::m_flowIdB private
flow ID B
Definition at line 199 of file wifi-phy-test.cc.
Referenced by Receive(), and SendB().
m_input
struct Input CollisionExperiment::m_input private
input
Definition at line 199 of file wifi-phy-test.cc.
Referenced by SendA(), and SendB().
m_output
struct Output CollisionExperiment::m_output private
output
Definition at line 199 of file wifi-phy-test.cc.
Referenced by Receive().
m_txA
Ptr<WifiPhy> CollisionExperiment::m_txA private
transmit A
Definition at line 196 of file wifi-phy-test.cc.
Referenced by SendA().
m_txB
Ptr<WifiPhy> CollisionExperiment::m_txB private
transmit B
Definition at line 197 of file wifi-phy-test.cc.
Referenced by SendB().
The documentation for this class was generated from the following file:
src/wifi/examples/wifi-phy-test.cc