ns-3: ns3::Buffer Class Reference
ns3::Buffer Class Reference
Network » Packet
automatically resized byte buffer
#include "buffer.h"
Classes
struct Data
This data structure is variable-sized through its last member whose size is determined at allocation time and stored in the m_size field.
class Iterator
iterator in a Buffer instance
struct LocalStaticDestructor
Local static destructor structure.
Public Member Functions
Buffer ()
Buffer (Buffer const &o)
Copy constructor.
Buffer (uint32_t dataSize)
Constructor.
Buffer (uint32_t dataSize, bool initialize)
Constructor.
~Buffer ()
void AddAtEnd (const Buffer &o)
void AddAtEnd (uint32_t end)
void AddAtStart (uint32_t start)
Buffer::Iterator Begin (void) const
void CopyData (std::ostream *os, uint32_t size) const
Copy the specified amount of data from the buffer to the given output stream.
uint32_t CopyData (uint8_t *buffer, uint32_t size) const
Copy the specified amount of data from the buffer to the given buffer.
Buffer CreateFragment (uint32_t start, uint32_t length) const
uint32_t Deserialize (const uint8_t *buffer, uint32_t size)
Buffer::Iterator End (void) const
uint32_t GetSerializedSize (void) const
Return the number of bytes required for serialization.
uint32_t GetSize (void) const
Buffer & operator= (Buffer const &o)
Assignment operator.
uint8_t const * PeekData (void) const
void RemoveAtEnd (uint32_t end)
void RemoveAtStart (uint32_t start)
uint32_t Serialize (uint8_t *buffer, uint32_t maxSize) const
Private Types
typedef std::vector< struct Buffer::Data * > FreeList
Container for buffer data.
Private Member Functions
bool CheckInternalState (void) const
Checks the internal buffer structures consistency.
Buffer CreateFullCopy (void) const
Create a full copy of the buffer, including all the internal structures.
uint32_t GetInternalEnd (void) const
Get the buffer end position.
uint32_t GetInternalSize (void) const
Get the buffer real size.
void Initialize (uint32_t zeroSize)
Initializes the buffer with a number of zeroes.
void TransformIntoRealBuffer (void) const
Transform a "Virtual byte buffer" into a "Real byte buffer".
Static Private Member Functions
static struct Buffer::Data * Allocate (uint32_t reqSize)
Allocate a buffer data storage.
static struct Buffer::Data * Create (uint32_t size)
Create a buffer data storage.
static void Deallocate (struct Buffer::Data *data)
Deallocate the buffer memory.
static void Recycle (struct Buffer::Data *data)
Recycle the buffer memory.
Private Attributes
struct Data * m_data
the buffer data storage
uint32_t m_end
offset to the end of the data referenced by this Buffer instance from the start of m_data->m_data
uint32_t m_maxZeroAreaStart
keep track of the maximum value of m_zeroAreaStart across the lifetime of a Buffer instance.
uint32_t m_start
offset to the start of the data referenced by this Buffer instance from the start of m_data->m_data
uint32_t m_zeroAreaEnd
offset to the end of the virtual zero area from the start of m_data->m_data
uint32_t m_zeroAreaStart
offset to the start of the virtual zero area from the start of m_data->m_data
Static Private Attributes
static FreeList * g_freeList = 0
Buffer data container.
static struct LocalStaticDestructor g_localStaticDestructor
Local static destructor.
static uint32_t g_maxSize = 0
Max observed data size.
static uint32_t g_recommendedStart = 0
location in a newly-allocated buffer where you should start writing data.
Detailed Description
automatically resized byte buffer
This represents a buffer of bytes. Its size is automatically adjusted to hold any data prepended or appended by the user. Its implementation is optimized to ensure that the number of buffer resizes is minimized, by creating new Buffers of the maximum size ever used. The correct maximum size is learned at runtime during use by recording the maximum size of each packet.
Internal:
The implementation of the Buffer class uses a COW (Copy On Write) technique to ensure that the underlying data buffer which holds the data bytes is shared among a lot of Buffer instances despite data being added or removed from them.
When multiple Buffer instances hold a reference to the same underlying BufferData object, they must be able to detect when the operation they want to perform should trigger a copy of the BufferData. If the BufferData::m_count field is one, it means that there exist only one instance of Buffer which references the BufferData instance so, it is safe to modify it. It is also safe to modify the content of a BufferData if the modification falls outside of the "dirty area" defined by the BufferData. In every other case, the BufferData must be copied before being modified.
To understand the way the Buffer::Add and Buffer::Remove methods work, you first need to understand the "virtual offsets" used to keep track of the content of buffers. Each Buffer instance contains real data bytes in its BufferData instance but it also contains "virtual zero data" which typically is used to represent application-level payload. No memory is allocated to store the zero bytes of application-level payload unless the user fragments a Buffer: this application-level payload is kept track of with a pair of integers which describe where in the buffer content the "virtual zero area" starts and ends.
* ***: unused bytes
* xxx: bytes "added" at the front of the zero area
* ...: bytes "added" at the back of the zero area
* 000: virtual zero bytes
*
* Real byte buffer:      |********xxxxxxxxxxxx.........*****|
*                        |--------^ m_start
*                        |-------------------^ m_zeroAreaStart
*                        |-----------------------------^ m_end - (m_zeroAreaEnd - m_zeroAreaStart)
* Virtual byte buffer:           |xxxxxxxxxxxx0000000000000.........|
*                        |--------^ m_start
*                        |--------------------^ m_zeroAreaStart
*                        |---------------------------------^ m_zeroAreaEnd
*                        |------------------------------------------^ m_end
*
A simple state invariant is that m_start <= m_zeroStart <= m_zeroEnd <= m_end
Definition at line 92 of file buffer.h.
Member Typedef Documentation
FreeList
typedef std::vector<struct Buffer::Data*> ns3::Buffer::FreeList private
Container for buffer data.
Definition at line 795 of file buffer.h.
Constructor & Destructor Documentation
Buffer() [1/4]
ns3::Buffer::Buffer (Buffer const & o) inline
Copy constructor.
Parameters
o the buffer to copy
Definition at line 1050 of file buffer.h.
References CheckInternalState(), ns3::Buffer::Data::m_count, m_data, and NS_ASSERT.
Buffer() [2/4]
ns3::Buffer::Buffer ()
Definition at line 188 of file buffer.cc.
References Initialize(), and NS_LOG_FUNCTION.
Buffer() [3/4]
ns3::Buffer::Buffer (uint32_t dataSize)
Constructor.
The buffer will be initialized with zeroes up to its size.
Parameters
dataSize the buffer size
Definition at line 194 of file buffer.cc.
References Initialize(), and NS_LOG_FUNCTION.
Buffer() [4/4]
ns3::Buffer::Buffer (uint32_t dataSize, bool initialize)
Constructor.
If initialize is set to true, the buffer will be initialized with zeroes up to its size.
Parameters
dataSize the buffer size.
initialize initialize the buffer with zeroes.
Definition at line 200 of file buffer.cc.
References Initialize(), and NS_LOG_FUNCTION.
~Buffer()
ns3::Buffer::~Buffer ()
Definition at line 283 of file buffer.cc.
References CheckInternalState(), g_recommendedStart, ns3::Buffer::Data::m_count, m_data, m_maxZeroAreaStart, max, NS_ASSERT, NS_LOG_FUNCTION, and Recycle().
Member Function Documentation
AddAtEnd() [1/2]
void ns3::Buffer::AddAtEnd (const Buffer & o)
Parameters
o the buffer to append to the end of this buffer.
Add bytes at the end of the Buffer. Any call to this method invalidates any Iterator pointing to this Buffer.
This is an optimization which kicks in when we attempt to aggregate two buffers which contain adjacent zero areas.
Definition at line 400 of file buffer.cc.
References AddAtEnd(), Begin(), CheckInternalState(), CreateFullCopy(), End(), GetSize(), ns3::Buffer::Data::m_count, m_data, ns3::Buffer::Data::m_dirtyEnd, m_end, m_start, m_zeroAreaEnd, m_zeroAreaStart, NS_ASSERT, NS_LOG_FUNCTION, ns3::Buffer::Iterator::Prev(), and ns3::Buffer::Iterator::Write().
AddAtEnd() [2/2]
void ns3::Buffer::AddAtEnd (uint32_t end)
Parameters
end size to reserve
Add bytes at the end of the Buffer. The content of these bytes is undefined but debugging builds initialize them to 0x33. Any call to this method invalidates any Iterator pointing to this Buffer.
Definition at line 354 of file buffer.cc.
References CheckInternalState(), Create(), GetInternalEnd(), GetInternalSize(), LOG_INTERNAL_STATE, ns3::Buffer::Data::m_count, ns3::Buffer::Data::m_data, m_data, ns3::Buffer::Data::m_dirtyEnd, ns3::Buffer::Data::m_dirtyStart, m_end, m_maxZeroAreaStart, m_start, m_zeroAreaEnd, m_zeroAreaStart, max, NS_ASSERT, NS_LOG_FUNCTION, and Recycle().
Referenced by AddAtEnd(), ns3::Packet::AddAtEnd(), ns3::dsr::DsrOptionField::AddDsrOption(), ns3::OptionField::AddOption(), ns3::Packet::AddPaddingAtEnd(), ns3::Packet::AddTrailer(), CreateFullCopy(), ns3::dsr::DsrFsHeader::Deserialize(), ns3::dsr::DsrOptionHeader::Deserialize(), ns3::dsr::DsrOptionRerrHeader::Deserialize(), ns3::Ipv6ExtensionHeader::Deserialize(), ns3::Ipv6OptionHeader::Deserialize(), ns3::dsr::DsrOptionField::Deserialize(), ns3::OptionField::Deserialize(), Deserialize(), BufferTest::DoRun(), ns3::WifiInformationElement::operator==(), and ns3::Asn1Header::WriteOctet().
AddAtStart()
void ns3::Buffer::AddAtStart (uint32_t start)
Parameters
start size to reserve
Add bytes at the start of the Buffer. The content of these bytes is undefined but debugging builds initialize them to 0x33. Any call to this method invalidates any Iterator pointing to this Buffer.
Definition at line 309 of file buffer.cc.
References CheckInternalState(), Create(), GetInternalSize(), LOG_INTERNAL_STATE, ns3::Buffer::Data::m_count, ns3::Buffer::Data::m_data, m_data, ns3::Buffer::Data::m_dirtyEnd, ns3::Buffer::Data::m_dirtyStart, m_end, m_maxZeroAreaStart, m_start, m_zeroAreaEnd, m_zeroAreaStart, max, NS_ASSERT, NS_LOG_FUNCTION, Recycle(), and visualizer.core::start().
Referenced by ns3::Packet::Packet(), PbbTestCase::PbbTestCase(), ns3::Packet::AddHeader(), ns3::TcpHeader::CalculateHeaderChecksum(), ns3::UdpHeader::CalculateHeaderChecksum(), ns3::Icmpv6Header::CalculatePseudoHeaderChecksum(), TcpHeaderWithRFC793OptionTestCase::CheckCorrectDeserialize(), TcpHeaderWithRFC793OptionTestCase::CheckNoPadding(), ns3::SixLowPanNetDevice::CompressLowPanNhc(), CreateFullCopy(), ns3::SixLowPanNetDevice::DecompressLowPanNhc(), ns3::PbbTlv::Deserialize(), Deserialize(), TestEmptyOptionField::DoRun(), TestOptionWithoutAlignment::DoRun(), TestOptionWithAlignment::DoRun(), TestFulfilledAlignment::DoRun(), DsrFsHeaderTest::DoRun(), TcpHeaderGetSetTestCase::DoRun(), HeaderTest::DoRun(), BufferTest::DoRun(), TcpHeaderWithRFC793OptionTestCase::OneOptionAtTime(), ns3::Ipv6ExtensionLooseRouting::Process(), ns3::PbbTlv::SetValue(), TcpOptionWSTestCase::TestSerialize(), TcpOptionTSTestCase::TestSerialize(), PbbTestCase::TestSerialize(), and ns3::PcapFile::Write().
Allocate()
struct Buffer::Data * ns3::Buffer::Allocate (uint32_t reqSize) static private
Allocate a buffer data storage.
Parameters
reqSize the storage size to create
Returns
a pointer to the allocated buffer storage
Definition at line 163 of file buffer.cc.
References data, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by Create().
Begin()
Buffer::Iterator ns3::Buffer::Begin (void) const inline
Returns
an Iterator which points to the start of this Buffer.
Definition at line 1069 of file buffer.h.
References CheckInternalState(), and NS_ASSERT.
Referenced by ns3::Packet::Packet(), PbbTestCase::PbbTestCase(), AddAtEnd(), ns3::Packet::AddHeader(), ns3::TcpHeader::CalculateHeaderChecksum(), ns3::UdpHeader::CalculateHeaderChecksum(), ns3::Icmpv6Header::CalculatePseudoHeaderChecksum(), TcpHeaderWithRFC793OptionTestCase::CheckCorrectDeserialize(), TcpHeaderWithRFC793OptionTestCase::CheckNoPadding(), ns3::SixLowPanNetDevice::CompressLowPanNhc(), CreateFullCopy(), ns3::SixLowPanNetDevice::DecompressLowPanNhc(), ns3::PbbTlv::Deserialize(), ns3::dsr::DsrFsHeader::Deserialize(), ns3::dsr::DsrOptionHeader::Deserialize(), ns3::dsr::DsrOptionRerrHeader::Deserialize(), ns3::Ipv6ExtensionHeader::Deserialize(), ns3::Ipv6OptionHeader::Deserialize(), ns3::dsr::DsrOptionField::Deserialize(), ns3::OptionField::Deserialize(), Deserialize(), TestEmptyOptionField::DoRun(), TestOptionWithoutAlignment::DoRun(), TestOptionWithAlignment::DoRun(), TestFulfilledAlignment::DoRun(), DsrFsHeaderTest::DoRun(), TcpHeaderGetSetTestCase::DoRun(), HeaderTest::DoRun(), BufferTest::DoRun(), TcpHeaderWithRFC793OptionTestCase::OneOptionAtTime(), ns3::WifiInformationElement::operator==(), ns3::Packet::PeekHeader(), ns3::Ipv6ExtensionLooseRouting::Process(), ns3::Packet::RemoveHeader(), ns3::Asn1Header::Serialize(), ns3::dsr::DsrOptionField::Serialize(), ns3::dsr::DsrOptionHeader::Serialize(), ns3::dsr::DsrOptionRerrHeader::Serialize(), ns3::OptionField::Serialize(), ns3::Ipv6OptionHeader::Serialize(), ns3::PbbTlv::SetValue(), TcpOptionWSTestCase::TestDeserialize(), TcpOptionTSTestCase::TestDeserialize(), PbbTestCase::TestDeserialize(), TcpOptionWSTestCase::TestSerialize(), TcpOptionTSTestCase::TestSerialize(), PbbTestCase::TestSerialize(), and ns3::PcapFile::Write().
CheckInternalState()
bool ns3::Buffer::CheckInternalState (void) const private
Checks the internal buffer structures consistency.
Used only for debugging purposes.
Returns
true if the buffer status is consistent.
Definition at line 210 of file buffer.cc.
References ns3::if(), LOG_INTERNAL_STATE, ns3::Buffer::Data::m_count, m_data, ns3::Buffer::Data::m_dirtyEnd, ns3::Buffer::Data::m_dirtyStart, m_end, ns3::Buffer::Data::m_size, m_start, m_zeroAreaEnd, m_zeroAreaStart, and NS_LOG_FUNCTION.
Referenced by Buffer(), ~Buffer(), AddAtEnd(), AddAtStart(), Begin(), CreateFragment(), CreateFullCopy(), End(), Initialize(), operator=(), PeekData(), RemoveAtEnd(), RemoveAtStart(), and TransformIntoRealBuffer().
CopyData() [1/2]
void ns3::Buffer::CopyData (std::ostream * os, uint32_t size) const
Copy the specified amount of data from the buffer to the given output stream.
Parameters
os the output stream
size the maximum amount of bytes to copy. If zero, nothing is copied.
Definition at line 715 of file buffer.cc.
References anonymous_namespace{buffer.cc}::Zeroes::buffer, anonymous_namespace{buffer.cc}::g_zeroes, ns3::Buffer::Data::m_data, m_data, m_end, m_start, m_zeroAreaEnd, m_zeroAreaStart, min, NS_LOG_FUNCTION, and anonymous_namespace{buffer.cc}::Zeroes::size.
Referenced by ns3::Packet::CopyData(), BufferTest::DoRun(), and ns3::PcapFile::Write().
CopyData() [2/2]
uint32_t ns3::Buffer::CopyData (uint8_t * buffer, uint32_t size) const
Copy the specified amount of data from the buffer to the given buffer.
Parameters
buffer the output buffer
size the maximum amount of bytes to copy. If zero, nothing is copied.
Returns
the amount of bytes copied
Definition at line 744 of file buffer.cc.
References anonymous_namespace{buffer.cc}::Zeroes::buffer, anonymous_namespace{buffer.cc}::g_zeroes, ns3::Buffer::Data::m_data, m_data, m_end, m_start, m_zeroAreaEnd, m_zeroAreaStart, min, NS_LOG_FUNCTION, and anonymous_namespace{buffer.cc}::Zeroes::size.
Create()
Buffer::Data * ns3::Buffer::Create (uint32_t size) static private
Create a buffer data storage.
Parameters
size the storage size to create
Returns
a pointer to the created buffer storage
Definition at line 119 of file buffer.cc.
References Allocate(), data, Deallocate(), g_freeList, IS_INITIALIZED, IS_UNINITIALIZED, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by AddAtEnd(), AddAtStart(), and Initialize().
CreateFragment()
Buffer ns3::Buffer::CreateFragment (uint32_t start, uint32_t length) const
Parameters
start offset from start of packet
length
Returns
a fragment of size length starting at offset start.
Definition at line 519 of file buffer.cc.
References CheckInternalState(), GetSize(), NS_ASSERT, NS_LOG_FUNCTION, RemoveAtEnd(), RemoveAtStart(), and visualizer.core::start().
Referenced by ns3::Packet::CreateFragment(), and BufferTest::DoRun().
CreateFullCopy()
Buffer ns3::Buffer::CreateFullCopy (void) const private
Create a full copy of the buffer, including all the internal structures.
Returns
a copy of the buffer
Definition at line 531 of file buffer.cc.
References AddAtEnd(), AddAtStart(), Begin(), CheckInternalState(), End(), ns3::Buffer::Data::m_data, m_data, m_end, m_start, m_zeroAreaEnd, m_zeroAreaStart, NS_ASSERT, NS_LOG_FUNCTION, ns3::Buffer::Iterator::Prev(), ns3::Buffer::Iterator::Write(), and ns3::Buffer::Iterator::WriteU8().
Referenced by AddAtEnd(), and TransformIntoRealBuffer().
Deallocate()
void ns3::Buffer::Deallocate (struct Buffer::Data * data) static private
Deallocate the buffer memory.
Parameters
data the buffer data storage
Definition at line 180 of file buffer.cc.
References data, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::Buffer::LocalStaticDestructor::~LocalStaticDestructor(), Create(), and Recycle().
Deserialize()
uint32_t ns3::Buffer::Deserialize (const uint8_t * buffer, uint32_t size)
Returns
zero if a complete buffer is not deserialized
Parameters
buffer points to buffer for deserialization
size number of bytes to deserialize
The raw character buffer is deserialized and all the data is placed into this buffer.
Definition at line 648 of file buffer.cc.
References AddAtEnd(), AddAtStart(), Begin(), End(), Initialize(), NS_ASSERT, NS_LOG_FUNCTION, ns3::Buffer::Iterator::Prev(), and ns3::Buffer::Iterator::Write().
Referenced by ns3::Packet::Deserialize().
End()
Buffer::Iterator ns3::Buffer::End (void) const inline
Returns
an Iterator which points to the end of this Buffer.
Definition at line 1075 of file buffer.h.
References CheckInternalState(), and NS_ASSERT.
Referenced by AddAtEnd(), ns3::dsr::DsrOptionField::AddDsrOption(), ns3::OptionField::AddOption(), ns3::Packet::AddTrailer(), CreateFullCopy(), Deserialize(), BufferTest::DoRun(), ns3::Packet::PeekTrailer(), ns3::Packet::RemoveTrailer(), ns3::Asn1Header::Serialize(), ns3::dsr::DsrOptionField::Serialize(), ns3::dsr::DsrOptionHeader::Serialize(), ns3::dsr::DsrOptionRerrHeader::Serialize(), ns3::OptionField::Serialize(), ns3::Ipv6OptionHeader::Serialize(), and ns3::Asn1Header::WriteOctet().
GetInternalEnd()
uint32_t ns3::Buffer::GetInternalEnd (void) const private
Get the buffer end position.
Returns
the buffer end index.
Definition at line 302 of file buffer.cc.
References m_end, m_zeroAreaEnd, m_zeroAreaStart, and NS_LOG_FUNCTION.
Referenced by AddAtEnd().
GetInternalSize()
uint32_t ns3::Buffer::GetInternalSize (void) const private
Get the buffer real size.
Warning
The real size is the actual memory used by the buffer.
Returns
the memory used by the buffer.
Definition at line 296 of file buffer.cc.
References m_end, m_start, m_zeroAreaEnd, m_zeroAreaStart, and NS_LOG_FUNCTION.
Referenced by AddAtEnd(), and AddAtStart().
GetSerializedSize()
uint32_t ns3::Buffer::GetSerializedSize (void) const
Return the number of bytes required for serialization.
Returns
the number of bytes.
Definition at line 556 of file buffer.cc.
References m_end, m_start, m_zeroAreaEnd, m_zeroAreaStart, and NS_LOG_FUNCTION.
Referenced by ns3::Packet::GetSerializedSize(), and ns3::Packet::Serialize().
GetSize()
uint32_t ns3::Buffer::GetSize (void) const inline
Returns
the number of bytes stored in this buffer.
Definition at line 1063 of file buffer.h.
References m_end, and m_start.
Referenced by ns3::PbbTlv::~PbbTlv(), AddAtEnd(), ns3::dsr::DsrOptionField::CalculatePad(), ns3::OptionField::CalculatePad(), TcpHeaderWithRFC793OptionTestCase::CheckNoPadding(), ns3::SixLowPanNetDevice::CompressLowPanNhc(), CreateFragment(), ns3::Packet::CreateFragment(), ns3::dsr::DsrFsHeader::Deserialize(), ns3::Ipv6ExtensionHeader::Deserialize(), BufferTest::DoRun(), ns3::dsr::DsrOptionField::GetSerializedSize(), ns3::OptionField::GetSerializedSize(), ns3::Asn1Header::GetSerializedSize(), ns3::PbbTlv::GetSerializedSize(), TcpHeaderWithRFC793OptionTestCase::OneOptionAtTime(), ns3::PbbTlv::operator==(), ns3::PbbTlv::Print(), ns3::PbbTlv::Serialize(), ns3::dsr::DsrFsHeader::Serialize(), ns3::Ipv6ExtensionHeader::Serialize(), PbbTestCase::TestDeserialize(), and PbbTestCase::TestSerialize().
Initialize()
void ns3::Buffer::Initialize (uint32_t zeroSize) private
Initializes the buffer with a number of zeroes.
Parameters
zeroSize the zeroes size
Definition at line 244 of file buffer.cc.
References CheckInternalState(), Create(), g_recommendedStart, m_data, ns3::Buffer::Data::m_dirtyEnd, ns3::Buffer::Data::m_dirtyStart, m_end, m_maxZeroAreaStart, ns3::Buffer::Data::m_size, m_start, m_zeroAreaEnd, m_zeroAreaStart, min, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by Buffer(), and Deserialize().
operator=()
Buffer & ns3::Buffer::operator= (Buffer const & o)
Assignment operator.
Parameters
o the buffer to copy
Returns
a reference to the buffer
Definition at line 259 of file buffer.cc.
References CheckInternalState(), g_recommendedStart, ns3::Buffer::Data::m_count, m_data, m_end, m_maxZeroAreaStart, m_start, m_zeroAreaEnd, m_zeroAreaStart, max, NS_ASSERT, and Recycle().
PeekData()
uint8_t const * ns3::Buffer::PeekData (void) const
Returns
a pointer to the start of the internal byte buffer.
The returned pointer points to an area of memory which is ns3::Buffer::GetSize () bytes big. Please, try to never ever use this method. It is really evil and is present only for a few specific uses.
Definition at line 705 of file buffer.cc.
References CheckInternalState(), ns3::Buffer::Data::m_data, m_data, m_start, NS_ASSERT, NS_LOG_FUNCTION, and TransformIntoRealBuffer().
Referenced by ns3::SixLowPanNetDevice::CompressLowPanNhc(), TestEmptyOptionField::DoRun(), TestOptionWithoutAlignment::DoRun(), TestOptionWithAlignment::DoRun(), TestFulfilledAlignment::DoRun(), DsrFsHeaderTest::DoRun(), BufferTest::DoRun(), BufferTest::EnsureWrittenBytes(), ns3::PbbTlv::operator==(), ns3::WifiInformationElement::operator==(), ns3::dsr::DsrFsHeader::Serialize(), ns3::Ipv6ExtensionHeader::Serialize(), and PbbTestCase::TestSerialize().
Recycle()
void ns3::Buffer::Recycle (struct Buffer::Data * data) static private
Recycle the buffer memory.
Parameters
data the buffer data storage
Definition at line 98 of file buffer.cc.
References data, Deallocate(), g_freeList, g_maxSize, IS_DESTROYED, IS_INITIALIZED, IS_UNINITIALIZED, max, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ~Buffer(), AddAtEnd(), AddAtStart(), and operator=().
RemoveAtEnd()
void ns3::Buffer::RemoveAtEnd (uint32_t end)
Parameters
end size to remove
Remove bytes at the end of the Buffer. Any call to this method invalidates any Iterator pointing to this Buffer.
Definition at line 483 of file buffer.cc.
References CheckInternalState(), LOG_INTERNAL_STATE, m_end, m_maxZeroAreaStart, m_start, m_zeroAreaEnd, m_zeroAreaStart, max, min, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::PbbTlv::~PbbTlv(), CreateFragment(), ns3::dsr::DsrFsHeader::Deserialize(), ns3::Ipv6ExtensionHeader::Deserialize(), BufferTest::DoRun(), ns3::Packet::RemoveAtEnd(), and ns3::Packet::RemoveTrailer().
RemoveAtStart()
void ns3::Buffer::RemoveAtStart (uint32_t start)
Parameters
start size to remove
Remove bytes at the start of the Buffer. Any call to this method invalidates any Iterator pointing to this Buffer.
Definition at line 438 of file buffer.cc.
References CheckInternalState(), LOG_INTERNAL_STATE, m_end, m_maxZeroAreaStart, m_start, m_zeroAreaEnd, m_zeroAreaStart, max, NS_ASSERT, NS_LOG_FUNCTION, and visualizer.core::start().
Referenced by ns3::SixLowPanNetDevice::CompressLowPanNhc(), CreateFragment(), BufferTest::DoRun(), ns3::Packet::RemoveAtStart(), and ns3::Packet::RemoveHeader().
Serialize()
uint32_t ns3::Buffer::Serialize (uint8_t * buffer, uint32_t maxSize) const
Returns
zero if buffer not large enough
Parameters
buffer points to serialization buffer
maxSize max number of bytes to write
This buffer's contents are serialized into the raw character buffer parameter. Note: The zero length data is not copied entirely. Only the length of zero byte data is serialized.
Definition at line 576 of file buffer.cc.
References ns3::Buffer::Data::m_data, m_data, m_end, m_start, m_zeroAreaEnd, m_zeroAreaStart, and NS_LOG_FUNCTION.
Referenced by ns3::Packet::Serialize().
TransformIntoRealBuffer()
void ns3::Buffer::TransformIntoRealBuffer (void) const private
Transform a "Virtual byte buffer" into a "Real byte buffer".
Definition at line 694 of file buffer.cc.
References CheckInternalState(), CreateFullCopy(), NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by PeekData().
Member Data Documentation
g_freeList
Buffer::FreeList * ns3::Buffer::g_freeList = 0 static private
Buffer data container.
Definition at line 802 of file buffer.h.
Referenced by ns3::Buffer::LocalStaticDestructor::~LocalStaticDestructor(), Create(), and Recycle().
g_localStaticDestructor
struct LocalStaticDestructor ns3::Buffer::g_localStaticDestructor static private
Local static destructor.
Definition at line 802 of file buffer.h.
g_maxSize
uint32_t ns3::Buffer::g_maxSize = 0 static private
Max observed data size.
Definition at line 801 of file buffer.h.
Referenced by Recycle().
g_recommendedStart
uint32_t ns3::Buffer::g_recommendedStart = 0 static private
location in a newly-allocated buffer where you should start writing data.
i.e., m_start should be initialized to this value.
Definition at line 770 of file buffer.h.
Referenced by ~Buffer(), Initialize(), and operator=().
m_data
struct Data* ns3::Buffer::m_data private
the buffer data storage
Definition at line 752 of file buffer.h.
Referenced by Buffer(), ~Buffer(), AddAtEnd(), AddAtStart(), CheckInternalState(), ns3::Buffer::Iterator::Construct(), CopyData(), CreateFullCopy(), Initialize(), operator=(), PeekData(), ns3::Buffer::Iterator::PeekU8(), ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadNtohU32(), Serialize(), ns3::Buffer::Iterator::Write(), ns3::Buffer::Iterator::WriteHtonU16(), ns3::Buffer::Iterator::WriteHtonU32(), and ns3::Buffer::Iterator::WriteU8().
m_end
uint32_t ns3::Buffer::m_end private
offset to the end of the data referenced by this Buffer instance from the start of m_data->m_data
Definition at line 791 of file buffer.h.
Referenced by AddAtEnd(), AddAtStart(), CheckInternalState(), ns3::Buffer::Iterator::Construct(), CopyData(), CreateFullCopy(), GetInternalEnd(), GetInternalSize(), GetSerializedSize(), GetSize(), Initialize(), operator=(), RemoveAtEnd(), RemoveAtStart(), and Serialize().
m_maxZeroAreaStart
uint32_t ns3::Buffer::m_maxZeroAreaStart private
keep track of the maximum value of m_zeroAreaStart across the lifetime of a Buffer instance.
This variable is used purely as a source of information for the heuristics which decide on the position of the zero area in new buffers. It is read from the Buffer destructor to update the global heuristic data and these global heuristic data are used from the Buffer constructor to choose an initial value for m_zeroAreaStart.
Definition at line 764 of file buffer.h.
Referenced by ~Buffer(), AddAtEnd(), AddAtStart(), Initialize(), operator=(), RemoveAtEnd(), and RemoveAtStart().
m_start
uint32_t ns3::Buffer::m_start private
offset to the start of the data referenced by this Buffer instance from the start of m_data->m_data
Definition at line 786 of file buffer.h.
Referenced by AddAtEnd(), AddAtStart(), CheckInternalState(), ns3::Buffer::Iterator::Construct(), CopyData(), CreateFullCopy(), GetInternalSize(), GetSerializedSize(), GetSize(), Initialize(), operator=(), PeekData(), RemoveAtEnd(), RemoveAtStart(), and Serialize().
m_zeroAreaEnd
uint32_t ns3::Buffer::m_zeroAreaEnd private
offset to the end of the virtual zero area from the start of m_data->m_data
Definition at line 781 of file buffer.h.
Referenced by AddAtEnd(), AddAtStart(), CheckInternalState(), ns3::Buffer::Iterator::Construct(), CopyData(), CreateFullCopy(), GetInternalEnd(), GetInternalSize(), GetSerializedSize(), Initialize(), operator=(), RemoveAtEnd(), RemoveAtStart(), and Serialize().
m_zeroAreaStart
uint32_t ns3::Buffer::m_zeroAreaStart private
offset to the start of the virtual zero area from the start of m_data->m_data
Definition at line 776 of file buffer.h.
Referenced by AddAtEnd(), AddAtStart(), CheckInternalState(), ns3::Buffer::Iterator::Construct(), CopyData(), CreateFullCopy(), GetInternalEnd(), GetInternalSize(), GetSerializedSize(), Initialize(), operator=(), RemoveAtEnd(), RemoveAtStart(), and Serialize().
The documentation for this class was generated from the following files:
src/network/model/buffer.h
src/network/model/buffer.cc