ns-3: ns3::Socket Class Reference
ns3::Socket Class Reference abstract
Network » Socket
A low-level Socket API based loosely on the BSD Socket API.
#include "socket.h"
Public Types
enum Ipv6MulticastFilterMode { INCLUDE =1, EXCLUDE }
Enumeration of the possible filter of a socket.
enum SocketErrno {
ERROR_NOTERROR, ERROR_ISCONN, ERROR_NOTCONN, ERROR_MSGSIZE,
ERROR_AGAIN, ERROR_SHUTDOWN, ERROR_OPNOTSUPP, ERROR_AFNOSUPPORT,
ERROR_INVAL, ERROR_BADF, ERROR_NOROUTETOHOST, ERROR_NODEV,
ERROR_ADDRNOTAVAIL, ERROR_ADDRINUSE, SOCKET_ERRNO_LAST
}
Enumeration of the possible errors returned by a socket.
enum SocketPriority {
NS3_PRIO_BESTEFFORT = 0, NS3_PRIO_FILLER = 1, NS3_PRIO_BULK = 2, NS3_PRIO_INTERACTIVE_BULK = 4,
NS3_PRIO_INTERACTIVE = 6, NS3_PRIO_CONTROL = 7
}
Enumeration of the possible socket priorities.
enum SocketType { NS3_SOCK_STREAM, NS3_SOCK_SEQPACKET, NS3_SOCK_DGRAM, NS3_SOCK_RAW }
Enumeration of the possible socket types.
Public Member Functions
Socket (void)
virtual ~Socket (void)
virtual int Bind ()=0
Allocate a local IPv4 endpoint for this socket.
virtual int Bind (const Address &address)=0
Allocate a local endpoint for this socket.
virtual int Bind6 ()=0
Allocate a local IPv6 endpoint for this socket.
virtual void BindToNetDevice (Ptr< NetDevice > netdevice)
Bind a socket to specific device.
virtual int Close (void)=0
Close a socket.
virtual int Connect (const Address &address)=0
Initiate a connection to a remote host.
virtual bool GetAllowBroadcast () const =0
Query whether broadcast datagram transmissions are allowed.
Ptr< NetDevice > GetBoundNetDevice ()
Returns socket's bound NetDevice, if any.
virtual enum Socket::SocketErrno GetErrno (void) const =0
Get last error number.
uint8_t GetIpTos (void) const
Query the value of IP Type of Service of this socket.
virtual uint8_t GetIpTtl (void) const
Query the value of IP Time to Live field of this socket.
virtual uint8_t GetIpv6HopLimit (void) const
Query the value of IP Hop Limit field of this socket.
uint8_t GetIpv6Tclass (void) const
Query the value of IPv6 Traffic Class field of this socket.
virtual Ptr< Node > GetNode (void) const =0
Return the node this socket is associated with.
virtual int GetPeerName (Address &address) const =0
Get the peer address of a connected socket.
uint8_t GetPriority (void) const
Query the priority value of this socket.
virtual uint32_t GetRxAvailable (void) const =0
Return number of bytes which can be returned from one or multiple calls to Recv.
virtual enum Socket::SocketType GetSocketType (void) const =0
virtual int GetSockName (Address &address) const =0
Get socket address.
virtual uint32_t GetTxAvailable (void) const =0
Returns the number of bytes which can be sent in a single call to Send.
virtual void Ipv6JoinGroup (Ipv6Address address)
Joins a IPv6 multicast group without filters.
virtual void Ipv6JoinGroup (Ipv6Address address, Ipv6MulticastFilterMode filterMode, std::vector< Ipv6Address > sourceAddresses)
Joins a IPv6 multicast group.
virtual void Ipv6LeaveGroup (void)
Leaves IPv6 multicast group this socket is joined to.
bool IsIpRecvTos (void) const
Ask if the socket is currently passing information about IP Type of Service up the stack.
bool IsIpRecvTtl (void) const
Ask if the socket is currently passing information about IP_TTL up the stack.
bool IsIpv6RecvHopLimit (void) const
Ask if the socket is currently passing information about IPv6 Hop Limit up the stack.
bool IsIpv6RecvTclass (void) const
Ask if the socket is currently passing information about IPv6 Traffic Class up the stack.
bool IsRecvPktInfo () const
Get status indicating whether enable/disable packet information to socket.
virtual int Listen (void)=0
Listen for incoming connections.
virtual Ptr< Packet > Recv (uint32_t maxSize, uint32_t flags)=0
Read data from the socket.
int Recv (uint8_t *buf, uint32_t size, uint32_t flags)
Recv data (or dummy data) from the remote host.
Ptr< Packet > Recv (void)
Read a single packet from the socket.
Ptr< Packet > RecvFrom (Address &fromAddress)
Read a single packet from the socket and retrieve the sender address.
virtual Ptr< Packet > RecvFrom (uint32_t maxSize, uint32_t flags, Address &fromAddress)=0
Read a single packet from the socket and retrieve the sender address.
int RecvFrom (uint8_t *buf, uint32_t size, uint32_t flags, Address &fromAddress)
Read a single packet from the socket and retrieve the sender address.
int Send (const uint8_t *buf, uint32_t size, uint32_t flags)
Send data (or dummy data) to the remote host.
int Send (Ptr< Packet > p)
Send data (or dummy data) to the remote host.
virtual int Send (Ptr< Packet > p, uint32_t flags)=0
Send data (or dummy data) to the remote host.
int SendTo (const uint8_t *buf, uint32_t size, uint32_t flags, const Address &address)
Send data to a specified peer.
virtual int SendTo (Ptr< Packet > p, uint32_t flags, const Address &toAddress)=0
Send data to a specified peer.
void SetAcceptCallback (Callback< bool, Ptr< Socket >, const Address & > connectionRequest, Callback< void, Ptr< Socket >, const Address & > newConnectionCreated)
Accept connection requests from remote hosts.
virtual bool SetAllowBroadcast (bool allowBroadcast)=0
Configure whether broadcast datagram transmissions are allowed.
void SetCloseCallbacks (Callback< void, Ptr< Socket > > normalClose, Callback< void, Ptr< Socket > > errorClose)
Detect socket recv() events such as graceful shutdown or error.
void SetConnectCallback (Callback< void, Ptr< Socket > > connectionSucceeded, Callback< void, Ptr< Socket > > connectionFailed)
Specify callbacks to allow the caller to determine if the connection succeeds of fails.
void SetDataSentCallback (Callback< void, Ptr< Socket >, uint32_t > dataSent)
Notify application when a packet has been sent from transport protocol (non-standard socket call)
void SetIpRecvTos (bool ipv4RecvTos)
Tells a socket to pass information about IP Type of Service up the stack.
void SetIpRecvTtl (bool ipv4RecvTtl)
Tells a socket to pass information about IP_TTL up the stack.
void SetIpTos (uint8_t ipTos)
Manually set IP Type of Service field.
virtual void SetIpTtl (uint8_t ipTtl)
Manually set IP Time to Live field.
virtual void SetIpv6HopLimit (uint8_t ipHopLimit)
Manually set IPv6 Hop Limit.
void SetIpv6RecvHopLimit (bool ipv6RecvHopLimit)
Tells a socket to pass information about IPv6 Hop Limit up the stack.
void SetIpv6RecvTclass (bool ipv6RecvTclass)
Tells a socket to pass information about IPv6 Traffic Class up the stack.
void SetIpv6Tclass (int ipTclass)
Manually set IPv6 Traffic Class field.
void SetPriority (uint8_t priority)
Manually set the socket priority.
void SetRecvCallback (Callback< void, Ptr< Socket > >)
Notify application when new data is available to be read.
void SetRecvPktInfo (bool flag)
Enable/Disable receive packet information to socket.
void SetSendCallback (Callback< void, Ptr< Socket >, uint32_t > sendCb)
Notify application when space in transmit buffer is added.
virtual int ShutdownRecv (void)=0
virtual int ShutdownSend (void)=0
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static Ptr< Socket > CreateSocket (Ptr< Node > node, TypeId tid)
This method wraps the creation of sockets that is performed on a given node by a SocketFactory specified by TypeId.
static TypeId GetTypeId (void)
Get the type ID.
static uint8_t IpTos2Priority (uint8_t ipTos)
Return the priority corresponding to a given TOS value.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
bool IsManualIpTtl (void) const
Checks if the socket has a specific IPv4 TTL set.
bool IsManualIpv6HopLimit (void) const
Checks if the socket has a specific IPv6 Hop Limit set.
bool IsManualIpv6Tclass (void) const
Checks if the socket has a specific IPv6 Tclass set.
void NotifyConnectionFailed (void)
Notify through the callback (if set) that the connection has not been established due to an error.
bool NotifyConnectionRequest (const Address &from)
Notify through the callback (if set) that an incoming connection is being requested by a remote host.
void NotifyConnectionSucceeded (void)
Notify through the callback (if set) that the connection has been established.
void NotifyDataRecv (void)
Notify through the callback (if set) that some data have been received.
void NotifyDataSent (uint32_t size)
Notify through the callback (if set) that some data have been sent.
void NotifyErrorClose (void)
Notify through the callback (if set) that the connection has been closed due to an error.
void NotifyNewConnectionCreated (Ptr< Socket > socket, const Address &from)
Notify through the callback (if set) that a new connection has been created.
void NotifyNormalClose (void)
Notify through the callback (if set) that the connection has been closed.
void NotifySend (uint32_t spaceAvailable)
Notify through the callback (if set) that some data have been sent.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes
Ptr< NetDevice > m_boundnetdevice
the device this socket is bound to (might be null).
Ipv6Address m_ipv6MulticastGroupAddress
IPv6 multicast group address.
bool m_recvPktInfo
if the socket should add packet info tags to the packet forwarded to L4.
Private Attributes
Callback< void, Ptr< Socket > > m_connectionFailed
connection failed callback
Callback< bool, Ptr< Socket >, const Address & > m_connectionRequest
connection request callback
Callback< void, Ptr< Socket > > m_connectionSucceeded
connection succeeded callback
Callback< void, Ptr< Socket >, uint32_t > m_dataSent
data sent callback
Callback< void, Ptr< Socket > > m_errorClose
connection closed due to errors callback
bool m_ipRecvTos
socket forwards IPv4 TOS tag to L4
bool m_ipRecvTtl
socket forwards IPv4 TTL tag to L4
uint8_t m_ipTos
the socket IPv4 TOS
uint8_t m_ipTtl
the socket IPv4 TTL
uint8_t m_ipv6HopLimit
the socket IPv6 Hop Limit
bool m_ipv6RecvHopLimit
socket forwards IPv6 Hop Limit tag to L4
bool m_ipv6RecvTclass
socket forwards IPv6 Tclass tag to L4
uint8_t m_ipv6Tclass
the socket IPv6 Tclass
bool m_manualIpTtl
socket has IPv4 TTL set
bool m_manualIpv6HopLimit
socket has IPv6 Hop Limit set
bool m_manualIpv6Tclass
socket has IPv6 Tclass set
Callback< void, Ptr< Socket >, const Address & > m_newConnectionCreated
connection created callback
Callback< void, Ptr< Socket > > m_normalClose
connection closed callback
uint8_t m_priority
the socket priority
Callback< void, Ptr< Socket > > m_receivedData
data received callback
Callback< void, Ptr< Socket >, uint32_t > m_sendCb
packet sent callback
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A low-level Socket API based loosely on the BSD Socket API.
A few things to keep in mind about this type of socket:
it uses ns-3 API constructs such as class ns3::Address instead of C-style structs
in contrast to the original BSD socket API, this API is asynchronous: it does not contain blocking calls. Sending and receiving operations must make use of the callbacks provided.
It also uses class ns3::Packet as a fancy byte buffer, allowing data to be passed across the API using an ns-3 Packet instead of a raw data pointer.
Not all of the full POSIX sockets API is supported
Other than that, it tries to stick to the BSD API to make it easier for those who know the BSD API to use this API. More details are provided in the ns-3 tutorial.
Definition at line 66 of file socket.h.
Member Enumeration Documentation
Ipv6MulticastFilterMode
enum ns3::Socket::Ipv6MulticastFilterMode
Enumeration of the possible filter of a socket.
A socket can have filters on specific sources to include only packets incoming from them, or to exclude packets incoming from specific sources. Moreover, inclusion and exclusion also works as a leave, since "joining" a group without allowed sources is equivalent to leaving it.
Enumerator
INCLUDE
EXCLUDE
Definition at line 138 of file socket.h.
SocketErrno
enum ns3::Socket::SocketErrno
Enumeration of the possible errors returned by a socket.
Enumerator
ERROR_NOTERROR
ERROR_ISCONN
ERROR_NOTCONN
ERROR_MSGSIZE
ERROR_AGAIN
ERROR_SHUTDOWN
ERROR_OPNOTSUPP
ERROR_AFNOSUPPORT
ERROR_INVAL
ERROR_BADF
ERROR_NOROUTETOHOST
ERROR_NODEV
ERROR_ADDRNOTAVAIL
ERROR_ADDRINUSE
SOCKET_ERRNO_LAST
Definition at line 82 of file socket.h.
SocketPriority
enum ns3::Socket::SocketPriority
Enumeration of the possible socket priorities.
Names and corresponding values are derived from the Linux TC_PRIO_* macros
Enumerator
NS3_PRIO_BESTEFFORT
NS3_PRIO_FILLER
NS3_PRIO_BULK
NS3_PRIO_INTERACTIVE_BULK
NS3_PRIO_INTERACTIVE
NS3_PRIO_CONTROL
Definition at line 118 of file socket.h.
SocketType
enum ns3::Socket::SocketType
Enumeration of the possible socket types.
Enumerator
NS3_SOCK_STREAM
NS3_SOCK_SEQPACKET
NS3_SOCK_DGRAM
NS3_SOCK_RAW
Definition at line 104 of file socket.h.
Constructor & Destructor Documentation
Socket()
ns3::Socket::Socket (void)
Definition at line 45 of file socket.cc.
References m_boundnetdevice, m_ipTos, m_ipTtl, m_ipv6HopLimit, m_ipv6Tclass, m_priority, m_recvPktInfo, and NS_LOG_FUNCTION_NOARGS.
~Socket()
ns3::Socket::~Socket (void) virtual
Definition at line 65 of file socket.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Bind() [1/2]
virtual int ns3::Socket::Bind () pure virtual
Allocate a local IPv4 endpoint for this socket.
Returns
0 on success, -1 on failure.
Implemented in ns3::PacketSocket, ns3::UdpSocketImpl, ns3::TcpSocketBase, ns3::NscTcpSocketImpl, ns3::Ipv6RawSocketImpl, and ns3::Ipv4RawSocketImpl.
Bind() [2/2]
virtual int ns3::Socket::Bind (const Address & address) pure virtual
Allocate a local endpoint for this socket.
Parameters
address the address to try to allocate
Returns
0 on success, -1 on failure.
Implemented in ns3::PacketSocket, ns3::UdpSocketImpl, ns3::TcpSocketBase, ns3::NscTcpSocketImpl, ns3::Ipv6RawSocketImpl, and ns3::Ipv4RawSocketImpl.
Referenced by ns3::NoBackhaulEpcHelper::NoBackhaulEpcHelper(), Tunnel::Tunnel(), ns3::NoBackhaulEpcHelper::AddEnb(), ns3::NoBackhaulEpcHelper::AddS1Interface(), ns3::EpcX2::AddX2Interface(), ChainRegressionTest::CreateDevices(), Bug772ChainTest::CreateDevices(), ns3::olsr::Bug780Test::CreateNodes(), ns3::Rip::DoInitialize(), ns3::RipNg::DoInitialize(), ns3::olsr::RoutingProtocol::DoInitialize(), ns3::aodv::LoopbackTestCase::DoRun(), TcpEndPointBug2211Test::DoRun(), IcmpEchoReplyTestCase::DoRun(), IcmpTimeExceedTestCase::DoRun(), IcmpV6EchoReplyTestCase::DoRun(), IcmpV6TimeExceedTestCase::DoRun(), Ipv4DynamicGlobalRoutingTestCase::DoRun(), Ipv4RawSocketImplTest::DoRun(), DualStackTestCase::DoRun(), Ipv6RawSocketImplTest::DoRun(), UdpSocketLoopbackTest::DoRun(), Udp6SocketLoopbackTest::DoRun(), UdpSocketImplTest::DoRun(), Udp6SocketImplTest::DoRun(), Ns3TcpLossTestCase::DoRun(), Ns3TcpStateTestCase::DoRun(), HwmpProactiveRegressionTest::InstallApplications(), HwmpReactiveRegressionTest::InstallApplications(), HwmpSimplestRegressionTest::InstallApplications(), HwmpDoRfRegressionTest::InstallApplications(), FlameRegressionTest::InstallApplications(), ns3::aodv::RoutingProtocol::NotifyAddAddress(), ns3::dsdv::RoutingProtocol::NotifyAddAddress(), ns3::aodv::RoutingProtocol::NotifyInterfaceUp(), ns3::dsdv::RoutingProtocol::NotifyInterfaceUp(), ns3::Rip::NotifyInterfaceUp(), ns3::RipNg::NotifyInterfaceUp(), ns3::aodv::RoutingProtocol::NotifyRemoveAddress(), ns3::dsdv::RoutingProtocol::NotifyRemoveAddress(), ns3::ThreeGppHttpClient::OpenConnection(), NetAnimExperiment::Run(), Experiment::Run(), ns3::Ping6::Send(), ns3::ThreeGppHttpServer::StartApplication(), ns3::Ping6::StartApplication(), ns3::Radvd::StartApplication(), Receiver::StartApplication(), MyApp::StartApplication(), ns3::BulkSendApplication::StartApplication(), ns3::OnOffApplication::StartApplication(), ns3::PacketSink::StartApplication(), ns3::UdpClient::StartApplication(), ns3::UdpEchoClient::StartApplication(), ns3::UdpEchoServer::StartApplication(), ns3::UdpServer::StartApplication(), ns3::UdpTraceClient::StartApplication(), ns3::DhcpClient::StartApplication(), ns3::DhcpServer::StartApplication(), ns3::V4Ping::StartApplication(), ns3::V4TraceRoute::StartApplication(), EpsBearerTagUdpClient::StartApplication(), ns3::PacketSocketClient::StartApplication(), ns3::PacketSocketServer::StartApplication(), SimpleSource::StartApplication(), ns3::SocketWriter::StartApplication(), ns3::BsmApplication::StartApplication(), Ipv4FragmentationTest::StartClient(), Ipv6FragmentationTest::StartClient(), SixlowpanFragmentationTest::StartClient(), StartFlow(), Ipv4FragmentationTest::StartServer(), Ipv6FragmentationTest::StartServer(), SixlowpanFragmentationTest::StartServer(), and WifiInterferenceTestCase::WifiSimpleInterference().
Bind6()
virtual int ns3::Socket::Bind6 () pure virtual
Allocate a local IPv6 endpoint for this socket.
Returns
0 on success, -1 on failure.
Implemented in ns3::PacketSocket, ns3::UdpSocketImpl, ns3::TcpSocketBase, ns3::NscTcpSocketImpl, ns3::Ipv6RawSocketImpl, and ns3::Ipv4RawSocketImpl.
Referenced by ns3::ThreeGppHttpClient::OpenConnection(), ns3::BulkSendApplication::StartApplication(), ns3::OnOffApplication::StartApplication(), ns3::UdpClient::StartApplication(), ns3::UdpEchoClient::StartApplication(), and ns3::UdpTraceClient::StartApplication().
BindToNetDevice()
void ns3::Socket::BindToNetDevice (Ptr< NetDevice > netdevice) virtual
Bind a socket to specific device.
This method corresponds to using setsockopt() SO_BINDTODEVICE of real network or BSD sockets. If set on a socket, this option will force packets to leave the bound device regardless of the device that IP routing would naturally choose. In the receive direction, only packets received from the bound interface will be delivered.
This option has no particular relationship to binding sockets to an address via Socket::Bind (). It is possible to bind sockets to a specific IP address on the bound interface by calling both Socket::Bind (address) and Socket::BindToNetDevice (device), but it is also possible to bind to mismatching device and address, even if the socket can not receive any packets as a result.
Parameters
netdevice Pointer to NetDevice of desired interface
Returns
nothing
Reimplemented in ns3::UdpSocketImpl, ns3::TcpSocketBase, and ns3::NscTcpSocketImpl.
Definition at line 330 of file socket.cc.
References ns3::Node::GetDevice(), ns3::Node::GetNDevices(), GetNode(), m_boundnetdevice, NS_ASSERT_MSG(), and NS_LOG_FUNCTION.
Referenced by BindSock(), ns3::NscTcpSocketImpl::BindToNetDevice(), ns3::TcpSocketBase::BindToNetDevice(), ns3::UdpSocketImpl::BindToNetDevice(), ns3::Rip::DoInitialize(), ns3::RipNg::DoInitialize(), ns3::olsr::RoutingProtocol::DoInitialize(), Ipv4RipSplitHorizonStrategyTest::DoRun(), Ipv6RipngSplitHorizonStrategyTest::DoRun(), ns3::aodv::RoutingProtocol::NotifyAddAddress(), ns3::dsdv::RoutingProtocol::NotifyAddAddress(), ns3::aodv::RoutingProtocol::NotifyInterfaceUp(), ns3::dsdv::RoutingProtocol::NotifyInterfaceUp(), ns3::Rip::NotifyInterfaceUp(), ns3::RipNg::NotifyInterfaceUp(), ns3::aodv::RoutingProtocol::NotifyRemoveAddress(), ns3::DhcpClient::StartApplication(), ns3::DhcpServer::StartApplication(), and ns3::BsmApplication::StartApplication().
Close()
virtual int ns3::Socket::Close (void) pure virtual
Close a socket.
Returns
zero on success, -1 on failure.
After the Close call, the socket is no longer valid, and cannot safely be used for subsequent operations.
Implemented in ns3::PacketSocket, ns3::UdpSocketImpl, ns3::TcpSocketBase, ns3::NscTcpSocketImpl, ns3::Ipv4RawSocketImpl, and ns3::Ipv6RawSocketImpl.
Referenced by ns3::SocketWriter::Close(), ns3::Radvd::DoDispose(), ns3::Rip::DoDispose(), ns3::RipNg::DoDispose(), ns3::olsr::RoutingProtocol::DoDispose(), ns3::aodv::LoopbackTestCase::DoRun(), GenerateTraffic(), Experiment::GenerateTraffic(), WifiInterferenceTestCase::GenerateTraffic(), ns3::BsmApplication::GenerateWaveTraffic(), TcpEndPointBug2211Test::HandleConnect(), ns3::aodv::RoutingProtocol::NotifyInterfaceDown(), ns3::dsdv::RoutingProtocol::NotifyInterfaceDown(), ns3::aodv::RoutingProtocol::NotifyRemoveAddress(), TcpEndPointBug2211Test::Recv(), ns3::BulkSendApplication::SendData(), SendPacket(), ns3::TcpGeneralTest::SendPacket(), TcpTestCase::ServerHandleSend(), TcpTestCase::SourceHandleRecv(), ns3::ThreeGppHttpClient::StopApplication(), ns3::ThreeGppHttpServer::StopApplication(), MyApp::StopApplication(), ns3::BulkSendApplication::StopApplication(), ns3::OnOffApplication::StopApplication(), ns3::PacketSink::StopApplication(), ns3::UdpEchoClient::StopApplication(), ns3::UdpEchoServer::StopApplication(), ns3::DhcpClient::StopApplication(), ns3::V4Ping::StopApplication(), ns3::V4TraceRoute::StopApplication(), ns3::PacketSocketClient::StopApplication(), ns3::PacketSocketServer::StopApplication(), SimpleSource::StopApplication(), Ns3TcpLossTestCase::WriteUntilBufferFull(), Ns3TcpStateTestCase::WriteUntilBufferFull(), and WriteUntilBufferFull().
Connect()
virtual int ns3::Socket::Connect (const Address & address) pure virtual
Initiate a connection to a remote host.
Parameters
address Address of remote.
Returns
0 on success, -1 on error (in which case errno is set).
Implemented in ns3::PacketSocket, ns3::UdpSocketImpl, ns3::TcpSocketBase, ns3::NscTcpSocketImpl, ns3::Ipv6RawSocketImpl, and ns3::Ipv4RawSocketImpl.
Referenced by ns3::DhcpClient::AcceptAck(), ns3::NoBackhaulEpcHelper::AddEnb(), ns3::SocketWriter::Connect(), ChainRegressionTest::CreateDevices(), Bug772ChainTest::CreateDevices(), ns3::olsr::Bug780Test::CreateNodes(), TcpEndPointBug2211Test::DoRun(), DualStackTestCase::DoRun(), HwmpProactiveRegressionTest::InstallApplications(), HwmpReactiveRegressionTest::InstallApplications(), HwmpSimplestRegressionTest::InstallApplications(), HwmpDoRfRegressionTest::InstallApplications(), FlameRegressionTest::InstallApplications(), ns3::ThreeGppHttpClient::OpenConnection(), RunSimulation(), TcpTestCase::SetupDefaultSim(), TcpTestCase::SetupDefaultSim6(), MyApp::StartApplication(), ns3::BulkSendApplication::StartApplication(), ns3::OnOffApplication::StartApplication(), ns3::UdpClient::StartApplication(), ns3::UdpEchoClient::StartApplication(), ns3::UdpTraceClient::StartApplication(), ns3::V4Ping::StartApplication(), EpsBearerTagUdpClient::StartApplication(), ns3::PacketSocketClient::StartApplication(), SimpleSource::StartApplication(), ns3::BsmApplication::StartApplication(), Ipv4FragmentationTest::StartClient(), Ipv6FragmentationTest::StartClient(), SixlowpanFragmentationTest::StartClient(), Ns3TcpLossTestCase::StartFlow(), Ns3TcpStateTestCase::StartFlow(), StartFlow(), and WifiInterferenceTestCase::WifiSimpleInterference().
CreateSocket()
Ptr< Socket > ns3::Socket::CreateSocket (Ptr< Node > node, TypeId tid) static
This method wraps the creation of sockets that is performed on a given node by a SocketFactory specified by TypeId.
Returns
A smart pointer to a newly created socket.
Parameters
node The node on which to create the socket
tid The TypeId of a SocketFactory class to use
Definition at line 71 of file socket.cc.
References ns3::Object::GetObject(), NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::NoBackhaulEpcHelper::NoBackhaulEpcHelper(), Tunnel::Tunnel(), ns3::NoBackhaulEpcHelper::AddEnb(), ns3::NoBackhaulEpcHelper::AddS1Interface(), ns3::EpcX2::AddX2Interface(), ns3::olsr::Bug780Test::CreateNodes(), ns3::Rip::DoInitialize(), ns3::RipNg::DoInitialize(), ns3::olsr::RoutingProtocol::DoInitialize(), ns3::aodv::RoutingProtocol::NotifyAddAddress(), ns3::dsdv::RoutingProtocol::NotifyAddAddress(), ns3::aodv::RoutingProtocol::NotifyInterfaceUp(), ns3::dsdv::RoutingProtocol::NotifyInterfaceUp(), ns3::Rip::NotifyInterfaceUp(), ns3::RipNg::NotifyInterfaceUp(), ns3::aodv::RoutingProtocol::NotifyRemoveAddress(), ns3::dsdv::RoutingProtocol::NotifyRemoveAddress(), ns3::ThreeGppHttpClient::OpenConnection(), RunSimulation(), UanExperiment::SetupApplications(), TcpTestCase::SetupDefaultSim(), TcpTestCase::SetupDefaultSim6(), SetupPacketReceive(), DualStackTestCase::SetUpSim(), ns3::ThreeGppHttpServer::StartApplication(), ns3::Ping6::StartApplication(), ns3::Radvd::StartApplication(), ns3::BulkSendApplication::StartApplication(), ns3::OnOffApplication::StartApplication(), ns3::PacketSink::StartApplication(), ns3::UdpClient::StartApplication(), ns3::UdpEchoClient::StartApplication(), ns3::UdpEchoServer::StartApplication(), ns3::UdpServer::StartApplication(), ns3::UdpTraceClient::StartApplication(), ns3::DhcpClient::StartApplication(), ns3::DhcpServer::StartApplication(), ns3::V4Ping::StartApplication(), ns3::V4TraceRoute::StartApplication(), ns3::PacketSocketClient::StartApplication(), ns3::PacketSocketServer::StartApplication(), ns3::SocketWriter::StartApplication(), and ns3::BsmApplication::StartApplication().
DoDispose()
void ns3::Socket::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Reimplemented in ns3::PacketSocket, ns3::Ipv4RawSocketImpl, and ns3::Ipv6RawSocketImpl.
Definition at line 315 of file socket.cc.
References m_connectionFailed, m_connectionRequest, m_connectionSucceeded, m_dataSent, m_errorClose, m_newConnectionCreated, m_normalClose, m_receivedData, m_sendCb, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv6RawSocketImpl::DoDispose(), and ns3::Ipv4RawSocketImpl::GetSocketType().
GetAllowBroadcast()
virtual bool ns3::Socket::GetAllowBroadcast () const pure virtual
Query whether broadcast datagram transmissions are allowed.
This method corresponds to using getsockopt() SO_BROADCAST of real network or BSD sockets.
Returns
true if broadcast is allowed, false otherwise
Implemented in ns3::TcpSocketBase, ns3::PacketSocket, ns3::UdpSocketImpl, ns3::NscTcpSocketImpl, ns3::Ipv6RawSocketImpl, and ns3::Ipv4RawSocketImpl.
GetBoundNetDevice()
Ptr< NetDevice > ns3::Socket::GetBoundNetDevice ()
Returns socket's bound NetDevice, if any.
This method corresponds to using getsockopt() SO_BINDTODEVICE of real network or BSD sockets.
Returns
Pointer to interface.
Definition at line 351 of file socket.cc.
References m_boundnetdevice, and NS_LOG_FUNCTION.
Referenced by ns3::NscTcpSocketImpl::Bind(), ns3::TcpSocketBase::Bind(), ns3::UdpSocketImpl::Bind(), ns3::TcpSocketBase::CompleteFork(), ns3::Ipv4RawSocketImpl::ForwardUp(), ns3::Ipv6RawSocketImpl::ForwardUp(), and srcSocketRecv().
GetErrno()
virtual enum Socket::SocketErrno ns3::Socket::GetErrno (void) const pure virtual
Get last error number.
Returns
the errno associated to the last call which failed in this socket. Each socket's errno is initialized to zero when the socket is created.
Implemented in ns3::PacketSocket, ns3::UdpSocketImpl, ns3::TcpSocketBase, ns3::NscTcpSocketImpl, ns3::Ipv6RawSocketImpl, and ns3::Ipv4RawSocketImpl.
Referenced by ns3::ThreeGppHttpClient::ErrorCloseCallback(), ns3::ThreeGppHttpClient::NormalCloseCallback(), ns3::ThreeGppHttpClient::OpenConnection(), ns3::ThreeGppHttpClient::RequestEmbeddedObject(), ns3::ThreeGppHttpClient::RequestMainObject(), ns3::ThreeGppHttpServer::ServeFromTxBuffer(), TcpTestCase::ServerHandleRecv(), TcpTestCase::SetupDefaultSim(), TcpTestCase::SetupDefaultSim6(), TcpTestCase::SourceHandleRecv(), and ns3::ThreeGppHttpServer::StartApplication().
GetIpTos()
uint8_t ns3::Socket::GetIpTos (void) const
Query the value of IP Type of Service of this socket.
This method corresponds to using getsockopt () IP_TOS of real network or BSD sockets.
Returns
The raw IP TOS value
Definition at line 453 of file socket.cc.
References m_ipTos.
Referenced by ns3::TcpSocketBase::AddSocketTags(), ns3::UdpSocketImpl::DoSend(), ns3::UdpSocketImpl::GetPeerName(), ns3::Ipv4RawSocketImpl::Send(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), and ns3::TcpSocketSmallAcks::SendEmptyPacket().
GetIpTtl()
uint8_t ns3::Socket::GetIpTtl (void) const virtual
Query the value of IP Time to Live field of this socket.
This method corresponds to using getsockopt () IP_TTL of real network or BSD sockets.
Returns
The raw IP TTL value
Definition at line 520 of file socket.cc.
References m_ipTtl.
Referenced by ns3::TcpSocketBase::AddSocketTags(), ns3::UdpSocketImpl::DoSendTo(), ns3::UdpSocket::GetTypeId(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), and ns3::Ipv4RawSocketImpl::SendTo().
GetIpv6HopLimit()
uint8_t ns3::Socket::GetIpv6HopLimit (void) const virtual
Query the value of IP Hop Limit field of this socket.
This method corresponds to using getsockopt () IPV6_HOPLIMIT of real network or BSD sockets.
Returns
The raw IPv6 Hop Limit value
Definition at line 545 of file socket.cc.
References m_ipv6HopLimit.
Referenced by ns3::TcpSocketBase::AddSocketTags(), ns3::UdpSocketImpl::DoSendTo(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), and ns3::Ipv6RawSocketImpl::SendTo().
GetIpv6Tclass()
uint8_t ns3::Socket::GetIpv6Tclass (void) const
Query the value of IPv6 Traffic Class field of this socket.
This method corresponds to using getsockopt () IPV6_TCLASS of real network or BSD sockets.
Returns
The raw IPV6_TCLASS value
Definition at line 495 of file socket.cc.
References m_ipv6Tclass.
Referenced by ns3::TcpSocketBase::AddSocketTags(), ns3::UdpSocketImpl::DoSendTo(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), and ns3::Ipv6RawSocketImpl::SendTo().
GetNode()
virtual Ptr<Node> ns3::Socket::GetNode (void) const pure virtual
Return the node this socket is associated with.
Returns
the node
Implemented in ns3::PacketSocket, ns3::UdpSocketImpl, ns3::TcpSocketBase, ns3::NscTcpSocketImpl, ns3::Ipv4RawSocketImpl, and ns3::Ipv6RawSocketImpl.
Referenced by BindToNetDevice(), Bug772ChainTest::CreateDevices(), ns3::TcpGeneralTest::DataSentCb(), ns3::aodv::LoopbackTestCase::DoRun(), Ipv4FragmentationTest::DoRun(), Ipv6FragmentationTest::DoRun(), SixlowpanFragmentationTest::DoRun(), ns3::TcpGeneralTest::ErrorCloseCb(), ns3::BsmApplication::GenerateWaveTraffic(), HwmpProactiveRegressionTest::InstallApplications(), HwmpReactiveRegressionTest::InstallApplications(), HwmpSimplestRegressionTest::InstallApplications(), HwmpDoRfRegressionTest::InstallApplications(), FlameRegressionTest::InstallApplications(), ns3::TcpGeneralTest::NormalCloseCb(), PrintReceivedPacket(), PrintReceivedRoutingPacket(), Ipv4DeduplicationTest::ReceivePkt(), ns3::BsmApplication::ReceiveWavePacket(), Bug772ChainTest::SendData(), ns3::aodv::LoopbackTestCase::SendData(), UdpSocketImplTest::SendData(), HwmpProactiveRegressionTest::SendData(), HwmpReactiveRegressionTest::SendData(), HwmpSimplestRegressionTest::SendData(), FlameRegressionTest::SendData(), IcmpEchoReplyTestCase::SendData(), IcmpTimeExceedTestCase::SendData(), IcmpV6EchoReplyTestCase::SendData(), IcmpV6TimeExceedTestCase::SendData(), Ipv4ForwardingTest::SendData(), Ipv4GlobalRoutingSlash32TestCase::SendData(), Ipv4RawSocketImplTest::SendData(), Ipv4RipTest::SendData(), Ipv4RipCountToInfinityTest::SendData(), Ipv4StaticRoutingSlash32TestCase::SendData(), Ipv6ForwardingTest::SendData(), Ipv6RawSocketImplTest::SendData(), Ipv6RipngTest::SendData(), Ipv6RipngCountToInfinityTest::SendData(), SixlowpanHc1ImplTest::SendData(), SixlowpanIphcImplTest::SendData(), Ipv4RawSocketImplTest::SendData_IpHdr(), Ipv4HeaderTest::SendData_IpHdr_Dscp(), HwmpDoRfRegressionTest::SendDataA(), HwmpDoRfRegressionTest::SendDataB(), HwmpDoRfRegressionTest::SendDataC(), UdpSocketImplTest::SendDataTo(), Udp6SocketImplTest::SendDataTo(), Ipv4DeduplicationTest::SendPacket(), ns3::BsmApplication::StartApplication(), and WifiInterferenceTestCase::WifiSimpleInterference().
GetPeerName()
virtual int ns3::Socket::GetPeerName (Address & address) const pure virtual
Get the peer address of a connected socket.
Parameters
address the address this socket is connected to.
Returns
0 if success, -1 otherwise
Implemented in ns3::PacketSocket, ns3::UdpSocketImpl, ns3::TcpSocketBase, ns3::NscTcpSocketImpl, ns3::Ipv6RawSocketImpl, and ns3::Ipv4RawSocketImpl.
Referenced by ns3::BulkSendApplication::ConnectionSucceeded(), ns3::BulkSendApplication::DataSend(), ns3::OnOffApplication::SendPacket(), TcpTestCase::SetupDefaultSim(), and TcpTestCase::SetupDefaultSim6().
GetPriority()
uint8_t ns3::Socket::GetPriority (void) const
Query the priority value of this socket.
This method corresponds to using getsockopt () SO_PRIORITY of real network or BSD sockets.
Returns
The priority value
Definition at line 396 of file socket.cc.
References m_priority.
Referenced by ns3::TcpSocketBase::AddSocketTags(), ns3::UdpSocketImpl::DoSendTo(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), ns3::Ipv4RawSocketImpl::SendTo(), and ns3::PacketSocket::SendTo().
GetRxAvailable()
virtual uint32_t ns3::Socket::GetRxAvailable (void) const pure virtual
Return number of bytes which can be returned from one or multiple calls to Recv.
Must be possible to call this method from the Recv callback.
Returns
the number of bytes which can be returned from one or multiple Recv calls.
Implemented in ns3::PacketSocket, ns3::UdpSocketImpl, ns3::TcpSocketBase, ns3::NscTcpSocketImpl, ns3::Ipv4RawSocketImpl, and ns3::Ipv6RawSocketImpl.
Referenced by UanExperiment::PrintReceivedPacket(), ns3::V4Ping::Receive(), ns3::V4TraceRoute::Receive(), ns3::olsr::Bug780Test::Receive(), Ipv4DeduplicationTest::ReceivePkt(), Ipv4ForwardingTest::ReceivePkt(), Ipv4GlobalRoutingSlash32TestCase::ReceivePkt(), Ipv4HeaderTest::ReceivePkt(), Ipv4RawSocketImplTest::ReceivePkt(), Ipv4RipTest::ReceivePkt(), Ipv4RipCountToInfinityTest::ReceivePkt(), Ipv4StaticRoutingSlash32TestCase::ReceivePkt(), Ipv6ForwardingTest::ReceivePkt(), Ipv6RawSocketImplTest::ReceivePkt(), Ipv6RipngTest::ReceivePkt(), Ipv6RipngCountToInfinityTest::ReceivePkt(), UdpSocketLoopbackTest::ReceivePkt(), Udp6SocketLoopbackTest::ReceivePkt(), UdpSocketImplTest::ReceivePkt(), Udp6SocketImplTest::ReceivePkt(), SixlowpanHc1ImplTest::ReceivePkt(), SixlowpanIphcImplTest::ReceivePkt(), Ipv4RawSocketImplTest::ReceivePkt2(), Ipv6RawSocketImplTest::ReceivePkt2(), UdpSocketImplTest::ReceivePkt2(), Udp6SocketImplTest::ReceivePkt2(), Ipv4RipSplitHorizonStrategyTest::ReceivePktProbe(), Ipv6RipngSplitHorizonStrategyTest::ReceivePktProbe(), ns3::olsr::HelloRegressionTest::ReceivePktProbeA(), ns3::olsr::TcRegressionTest::ReceivePktProbeA(), ns3::olsr::HelloRegressionTest::ReceivePktProbeB(), ns3::olsr::TcRegressionTest::ReceivePktProbeB(), ns3::olsr::TcRegressionTest::ReceivePktProbeC(), TcpEndPointBug2211Test::Recv(), Ipv4PacketInfoTagTest::RxCb(), Ipv6PacketInfoTagTest::RxCb(), TcpTestCase::ServerHandleRecv(), and TcpTestCase::SourceHandleRecv().
GetSocketType()
virtual enum Socket::SocketType ns3::Socket::GetSocketType (void) const pure virtual
Returns
the socket type, analogous to getsockopt (SO_TYPE)
Implemented in ns3::PacketSocket, ns3::UdpSocketImpl, ns3::TcpSocketBase, ns3::NscTcpSocketImpl, ns3::Ipv4RawSocketImpl, and ns3::Ipv6RawSocketImpl.
Referenced by SetIpTos(), and ns3::BulkSendApplication::StartApplication().
GetSockName()
virtual int ns3::Socket::GetSockName (Address & address) const pure virtual
Get socket address.
Parameters
address the address name this socket is associated with.
Returns
0 if success, -1 otherwise
Implemented in ns3::PacketSocket, ns3::UdpSocketImpl, ns3::TcpSocketBase, ns3::NscTcpSocketImpl, ns3::Ipv6RawSocketImpl, and ns3::Ipv4RawSocketImpl.
Referenced by ns3::BulkSendApplication::ConnectionSucceeded(), ns3::BulkSendApplication::DataSend(), ns3::PacketSink::HandleRead(), ns3::UdpEchoClient::HandleRead(), ns3::UdpEchoServer::HandleRead(), ns3::UdpServer::HandleRead(), PrintReceivedPacket(), ns3::UdpEchoClient::Send(), ns3::OnOffApplication::SendPacket(), SetIpTos(), SetIpv6Tclass(), and ns3::BulkSendApplication::StartApplication().
GetTxAvailable()
virtual uint32_t ns3::Socket::GetTxAvailable (void) const pure virtual
Returns the number of bytes which can be sent in a single call to Send.
For datagram sockets, this returns the number of bytes that can be passed atomically through the underlying protocol.
For stream sockets, this returns the available space in bytes left in the transmit buffer.
Returns
The number of bytes which can be sent in a single Send call.
Implemented in ns3::PacketSocket, ns3::UdpSocketImpl, ns3::TcpSocketBase, ns3::NscTcpSocketImpl, ns3::Ipv4RawSocketImpl, and ns3::Ipv6RawSocketImpl.
Referenced by ns3::ThreeGppHttpServer::ServeFromTxBuffer(), TcpTestCase::ServerHandleRecv(), TcpTestCase::ServerHandleSend(), TcpTestCase::SourceHandleSend(), Ns3TcpLossTestCase::StartFlow(), Ns3TcpStateTestCase::StartFlow(), StartFlow(), Ns3TcpLossTestCase::WriteUntilBufferFull(), Ns3TcpStateTestCase::WriteUntilBufferFull(), and WriteUntilBufferFull().
GetTypeId()
TypeId ns3::Socket::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 37 of file socket.cc.
References ns3::TypeId::SetParent().
IpTos2Priority()
uint8_t ns3::Socket::IpTos2Priority (uint8_t ipTos) static
Return the priority corresponding to a given TOS value.
This function is implemented after the Linux rt_tos2priority function. The usage of the TOS byte has been originally defined by RFC 1349 (http://www.ietf.org/rfc/rfc1349.txt):
          0     1     2     3     4     5     6     7
      +-----+-----+-----+-----+-----+-----+-----+-----+
      |   PRECEDENCE    |          TOS          | MBZ |
      +-----+-----+-----+-----+-----+-----+-----+-----+
where MBZ stands for 'must be zero'.
The Linux rt_tos2priority function ignores the precedence bits and maps each of the 16 values coded in bits 3-6 as follows:
Bits 3-6 Means Linux Priority
0 Normal Service Best Effort (0)
1 Minimize Monetary Cost Best Effort (0)
2 Maximize Reliability Best Effort (0)
3 mmc+mr Best Effort (0)
4 Maximize Throughput Bulk (2)
5 mmc+mt Bulk (2)
6 mr+mt Bulk (2)
7 mmc+mr+mt Bulk (2)
8 Minimize Delay Interactive (6)
9 mmc+md Interactive (6)
10 mr+md Interactive (6)
11 mmc+mr+md Interactive (6)
12 mt+md Int. Bulk (4)
13 mmc+mt+md Int. Bulk (4)
14 mr+mt+md Int. Bulk (4)
15 mmc+mr+mt+md Int. Bulk (4)
RFC 2474 (http://www.ietf.org/rfc/rfc2474.txt) redefines the TOS byte:
          0     1     2     3     4     5     6     7
      +-----+-----+-----+-----+-----+-----+-----+-----+
      |              DSCP                 |     CU    |
      +-----+-----+-----+-----+-----+-----+-----+-----+
where DSCP is the Differentiated Services Code Point and CU stands for 'currently unused' (actually, RFC 3168 proposes to use these two bits for ECN purposes). The table above allows to determine how the Linux rt_tos2priority function maps each DSCP value to a priority value. Such a mapping is shown below.
DSCP Hex TOS (binary) bits 3-6 Linux Priority
EF 0x2E 101110xx 12-13 Int. Bulk (4)
AF11 0x0A 001010xx 4-5 Bulk (2)
AF21 0x12 010010xx 4-5 Bulk (2)
AF31 0x1A 011010xx 4-5 Bulk (2)
AF41 0x22 100010xx 4-5 Bulk (2)
AF12 0x0C 001100xx 8-9 Interactive (6)
AF22 0x14 010100xx 8-9 Interactive (6)
AF32 0x1C 011100xx 8-9 Interactive (6)
AF42 0x24 100100xx 8-9 Interactive (6)
AF13 0x0E 001110xx 12-13 Int. Bulk (4)
AF23 0x16 010110xx 12-13 Int. Bulk (4)
AF33 0x1E 011110xx 12-13 Int. Bulk (4)
AF43 0x26 100110xx 12-13 Int. Bulk (4)
CS0 0x00 000000xx 0-1 Best Effort (0)
CS1 0x08 001000xx 0-1 Best Effort (0)
CS2 0x10 010000xx 0-1 Best Effort (0)
CS3 0x18 011000xx 0-1 Best Effort (0)
CS4 0x20 100000xx 0-1 Best Effort (0)
CS5 0x28 101000xx 0-1 Best Effort (0)
CS6 0x30 110000xx 0-1 Best Effort (0)
CS7 0x38 111000xx 0-1 Best Effort (0)
Parameters
ipTos the TOS value (in the range 0..255)
Returns
The priority value corresponding to the given TOS value
Definition at line 402 of file socket.cc.
References NS3_PRIO_BESTEFFORT, NS3_PRIO_BULK, NS3_PRIO_INTERACTIVE, and NS3_PRIO_INTERACTIVE_BULK.
Referenced by ns3::UdpSocketImpl::DoSendTo(), ns3::Ipv4L3Protocol::IpForward(), ns3::Ipv4RawSocketImpl::SendTo(), and SetIpTos().
Ipv6JoinGroup() [1/2]
void ns3::Socket::Ipv6JoinGroup (Ipv6Address address) virtual
Joins a IPv6 multicast group without filters.
A socket can join only one multicast group. Any attempt to join another group will remove the old one.
Parameters
address Group address on which socket wants to join.
Definition at line 570 of file socket.cc.
References first::address, EXCLUDE, Ipv6JoinGroup(), and NS_LOG_FUNCTION.
Ipv6JoinGroup() [2/2]
void ns3::Socket::Ipv6JoinGroup (Ipv6Address address, Ipv6MulticastFilterMode filterMode, std::vector< Ipv6Address > sourceAddresses) virtual
Joins a IPv6 multicast group.
Based on the filter mode and source addresses this can be interpreted as a join, leave, or modification to source filtering on a multicast group.
Mind that a socket can join only one multicast group. Any attempt to join another group will remove the old one.
Parameters
address Requested multicast address.
filterMode Socket filtering mode (INCLUDE | EXCLUDE).
sourceAddresses All the source addresses on which socket is interested or not interested.
Reimplemented in ns3::UdpSocketImpl, and ns3::Ipv6RawSocketImpl.
Definition at line 563 of file socket.cc.
References first::address, NS_ASSERT_MSG(), and NS_LOG_FUNCTION.
Referenced by Ipv6JoinGroup(), and Ipv6LeaveGroup().
Ipv6LeaveGroup()
void ns3::Socket::Ipv6LeaveGroup (void) virtual
Leaves IPv6 multicast group this socket is joined to.
Definition at line 580 of file socket.cc.
References ns3::Ipv6Address::GetAny(), INCLUDE, Ipv6JoinGroup(), ns3::Ipv6Address::IsAny(), m_ipv6MulticastGroupAddress, NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by ns3::Ipv6RawSocketImpl::Close(), and ns3::UdpSocketImpl::Close().
IsIpRecvTos()
bool ns3::Socket::IsIpRecvTos (void) const
Ask if the socket is currently passing information about IP Type of Service up the stack.
This method corresponds to using getsockopt () IP_RECVTOS of real network or BSD sockets.
Returns
Whether the IP_RECVTOS is set
Definition at line 465 of file socket.cc.
References m_ipRecvTos.
Referenced by ns3::Ipv4RawSocketImpl::ForwardUp(), and ns3::UdpSocketImpl::ForwardUp().
IsIpRecvTtl()
bool ns3::Socket::IsIpRecvTtl (void) const
Ask if the socket is currently passing information about IP_TTL up the stack.
This method corresponds to using getsockopt () IP_RECVTTL of real network or BSD sockets.
Returns
Whether the IP_RECVTTL is set
Definition at line 532 of file socket.cc.
References m_ipRecvTtl.
Referenced by ns3::Ipv4RawSocketImpl::ForwardUp(), and ns3::UdpSocketImpl::ForwardUp().
IsIpv6RecvHopLimit()
bool ns3::Socket::IsIpv6RecvHopLimit (void) const
Ask if the socket is currently passing information about IPv6 Hop Limit up the stack.
This method corresponds to using getsockopt () IPV6_RECVHOPLIMIT of real network or BSD sockets.
Returns
Whether the IPV6_RECVHOPLIMIT is set
Definition at line 557 of file socket.cc.
References m_ipv6RecvHopLimit.
Referenced by ns3::Ipv6RawSocketImpl::ForwardUp(), and ns3::UdpSocketImpl::ForwardUp6().
IsIpv6RecvTclass()
bool ns3::Socket::IsIpv6RecvTclass (void) const
Ask if the socket is currently passing information about IPv6 Traffic Class up the stack.
This method corresponds to using getsockopt () IPV6_RECVTCLASS of real network or BSD sockets.
Returns
Whether the IPV6_RECVTCLASS is set
Definition at line 507 of file socket.cc.
References m_ipv6RecvTclass.
Referenced by ns3::Ipv6RawSocketImpl::ForwardUp(), and ns3::UdpSocketImpl::ForwardUp6().
IsManualIpTtl()
bool ns3::Socket::IsManualIpTtl (void) const protected
Checks if the socket has a specific IPv4 TTL set.
Returns
true if the socket has a IPv4 TTL set, false otherwise.
Definition at line 377 of file socket.cc.
References m_manualIpTtl.
Referenced by ns3::TcpSocketBase::AddSocketTags(), ns3::UdpSocketImpl::DoSendTo(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), and ns3::Ipv4RawSocketImpl::SendTo().
IsManualIpv6HopLimit()
bool ns3::Socket::IsManualIpv6HopLimit (void) const protected
Checks if the socket has a specific IPv6 Hop Limit set.
Returns
true if the socket has a IPv6 Hop Limit set, false otherwise.
Definition at line 383 of file socket.cc.
References m_manualIpv6HopLimit.
Referenced by ns3::TcpSocketBase::AddSocketTags(), ns3::UdpSocketImpl::DoSendTo(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), and ns3::Ipv6RawSocketImpl::SendTo().
IsManualIpv6Tclass()
bool ns3::Socket::IsManualIpv6Tclass (void) const protected
Checks if the socket has a specific IPv6 Tclass set.
Returns
true if the socket has a IPv6 Tclass set, false otherwise.
Definition at line 371 of file socket.cc.
References m_manualIpv6Tclass.
Referenced by ns3::TcpSocketBase::AddSocketTags(), ns3::UdpSocketImpl::DoSendTo(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), and ns3::Ipv6RawSocketImpl::SendTo().
IsRecvPktInfo()
bool ns3::Socket::IsRecvPktInfo () const
Get status indicating whether enable/disable packet information to socket.
Returns
True if packet information should be sent to socket
Definition at line 364 of file socket.cc.
References m_recvPktInfo, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4RawSocketImpl::ForwardUp(), ns3::Ipv6RawSocketImpl::ForwardUp(), ns3::UdpSocketImpl::ForwardUp(), and ns3::UdpSocketImpl::ForwardUp6().
Listen()
virtual int ns3::Socket::Listen (void) pure virtual
Listen for incoming connections.
Returns
0 on success, -1 on error (in which case errno is set).
Implemented in ns3::PacketSocket, ns3::UdpSocketImpl, ns3::TcpSocketBase, ns3::NscTcpSocketImpl, ns3::Ipv4RawSocketImpl, and ns3::Ipv6RawSocketImpl.
Referenced by Bug772ChainTest::CreateDevices(), Ipv4DynamicGlobalRoutingTestCase::DoRun(), DualStackTestCase::DoRun(), ns3::ThreeGppHttpServer::StartApplication(), and ns3::PacketSink::StartApplication().
NotifyConnectionFailed()
void ns3::Socket::NotifyConnectionFailed (void) protected
Notify through the callback (if set) that the connection has not been established due to an error.
Definition at line 227 of file socket.cc.
References m_connectionFailed, and NS_LOG_FUNCTION.
Referenced by ns3::UdpSocketImpl::Connect(), ns3::PacketSocket::Connect(), and ns3::TcpSocketBase::ReTxTimeout().
NotifyConnectionRequest()
bool ns3::Socket::NotifyConnectionRequest (const Address & from) protected
Notify through the callback (if set) that an incoming connection is being requested by a remote host.
This function returns true by default (i.e., accept all the incoming connections). The callback (if set) might restrict this behaviour by returning zero for a connection that should be refused.
Parameters
from the address the connection is incoming from
Returns
true if the connection must be accepted, false otherwise.
Definition at line 257 of file socket.cc.
References m_connectionRequest, and NS_LOG_FUNCTION.
Referenced by ns3::TcpSocketBase::ProcessListen().
NotifyConnectionSucceeded()
void ns3::Socket::NotifyConnectionSucceeded (void) protected
Notify through the callback (if set) that the connection has been established.
Definition at line 217 of file socket.cc.
References m_connectionSucceeded, and NS_LOG_FUNCTION.
Referenced by ns3::UdpSocketImpl::Connect(), ns3::PacketSocket::Connect(), ns3::NscTcpSocketImpl::ConnectionSucceeded(), and ns3::TcpSocketBase::ConnectionSucceeded().
NotifyDataRecv()
void ns3::Socket::NotifyDataRecv (void) protected
Notify through the callback (if set) that some data have been received.
Definition at line 305 of file socket.cc.
References m_receivedData, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4RawSocketImpl::ForwardUp(), ns3::Ipv6RawSocketImpl::ForwardUp(), ns3::PacketSocket::ForwardUp(), ns3::UdpSocketImpl::ForwardUp(), ns3::UdpSocketImpl::ForwardUp6(), ns3::TcpSocketBase::ProcessWait(), ns3::NscTcpSocketImpl::ReadPendingData(), and ns3::TcpSocketBase::ReceivedData().
NotifyDataSent()
void ns3::Socket::NotifyDataSent (uint32_t size) protected
Notify through the callback (if set) that some data have been sent.
Parameters
size number of sent bytes.
Definition at line 285 of file socket.cc.
References m_dataSent, and NS_LOG_FUNCTION.
Referenced by ns3::UdpSocketImpl::DoSendTo(), ns3::TcpSocketBase::SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), ns3::NscTcpSocketImpl::SendPendingData(), ns3::Ipv4RawSocketImpl::SendTo(), ns3::Ipv6RawSocketImpl::SendTo(), and ns3::PacketSocket::SendTo().
NotifyErrorClose()
void ns3::Socket::NotifyErrorClose (void) protected
Notify through the callback (if set) that the connection has been closed due to an error.
Definition at line 247 of file socket.cc.
References m_errorClose, and NS_LOG_FUNCTION.
Referenced by ns3::TcpSocketBase::ReTxTimeout(), and ns3::TcpSocketBase::SendRST().
NotifyNewConnectionCreated()
void ns3::Socket::NotifyNewConnectionCreated (Ptr< Socket > socket, const Address & from) protected
Notify through the callback (if set) that a new connection has been created.
Parameters
socket The socket receiving the new connection.
from The address of the node initiating the connection.
Definition at line 275 of file socket.cc.
References m_newConnectionCreated, and NS_LOG_FUNCTION.
Referenced by ns3::NscTcpSocketImpl::CompleteFork(), and ns3::TcpSocketBase::ProcessSynRcvd().
NotifyNormalClose()
void ns3::Socket::NotifyNormalClose (void) protected
Notify through the callback (if set) that the connection has been closed.
Definition at line 237 of file socket.cc.
References m_normalClose, and NS_LOG_FUNCTION.
Referenced by ns3::TcpSocketBase::CloseAndNotify(), ns3::TcpSocketBase::DoPeerClose(), and ns3::TcpSocketBase::TimeWait().
NotifySend()
void ns3::Socket::NotifySend (uint32_t spaceAvailable) protected
Notify through the callback (if set) that some data have been sent.
Parameters
spaceAvailable the number of bytes available in the transmission buffer.
Definition at line 295 of file socket.cc.
References m_sendCb, and NS_LOG_FUNCTION.
Referenced by ns3::TcpSocketBase::ConnectionSucceeded(), ns3::UdpSocketImpl::DoSendTo(), ns3::TcpSocketBase::NewAck(), ns3::NscTcpSocketImpl::NSCWakeup(), ns3::TcpSocketBase::ProcessSynRcvd(), ns3::TcpSocketBase::SendPendingData(), ns3::Ipv4RawSocketImpl::SendTo(), ns3::Ipv6RawSocketImpl::SendTo(), and ns3::PacketSocket::SendTo().
Recv() [1/3]
virtual Ptr<Packet> ns3::Socket::Recv (uint32_t maxSize, uint32_t flags) pure virtual
Read data from the socket.
This function matches closely in semantics to the recv() function call in the standard C library (libc): ssize_t recv (int s, void *buf, size_t len, int flags); except that the receive I/O is asynchronous. This is the primary Recv method at this low-level API and must be implemented by subclasses.
This method is normally used only on a connected socket. In a typical blocking sockets model, this call would block until at least one byte is returned or the connection closes. In ns-3 at this API, the call returns immediately in such a case and returns 0 if nothing is available to be read. However, an application can set a callback, ns3::SetRecvCallback, to be notified of data being available to be read (when it conceptually unblocks); this is an asynchronous I/O model for recv().
This variant of Recv() uses class ns3::Packet to encapsulate data, rather than providing a raw pointer and length field. This allows an ns-3 application to attach tags if desired (such as a flow ID) and may allow the simulator to avoid some data copies. Despite the appearance of receiving Packets on a stream socket, just think of it as a fancy byte buffer with streaming semantics.
The semantics depend on the type of socket. For a datagram socket, each Recv() returns the data from at most one Send(), and order is not necessarily preserved. For a stream socket, the bytes are delivered in order, and on-the-wire packet boundaries are not preserved.
The flags argument is formed by or'ing one or more of the values: MSG_OOB process out-of-band data MSG_PEEK peek at incoming message None of these flags are supported for now.
Some variants of Recv() are supported as additional API, including RecvFrom(), overloaded Recv() without arguments, and variants that use raw character buffers.
Parameters
maxSize reader will accept packet up to maxSize
flags Socket control flags
Returns
Ptr<Packet> of the next in-sequence packet. Returns 0 if the socket cannot return a next in-sequence packet conforming to the maxSize and flags.
See also
SetRecvCallback
Implemented in ns3::PacketSocket, ns3::UdpSocketImpl, ns3::TcpSocketBase, ns3::NscTcpSocketImpl, ns3::Ipv6RawSocketImpl, and ns3::Ipv4RawSocketImpl.
Referenced by Tunnel::N0SocketRecv(), Tunnel::N1SocketRecv(), Tunnel::N3SocketRecv(), PrintReceivedPacket(), ReceivePacket(), Experiment::ReceivePacket(), DsdvManetExample::ReceivePacket(), NetAnimExperiment::ReceivePacket(), ns3::aodv::LoopbackTestCase::ReceivePkt(), Ipv4DeduplicationTest::ReceivePkt(), Ipv4ForwardingTest::ReceivePkt(), Ipv4GlobalRoutingSlash32TestCase::ReceivePkt(), Ipv4HeaderTest::ReceivePkt(), Ipv4RawSocketImplTest::ReceivePkt(), Ipv4RipTest::ReceivePkt(), Ipv4RipCountToInfinityTest::ReceivePkt(), Ipv4StaticRoutingSlash32TestCase::ReceivePkt(), Ipv6ForwardingTest::ReceivePkt(), Ipv6RawSocketImplTest::ReceivePkt(), Ipv6RipngTest::ReceivePkt(), Ipv6RipngCountToInfinityTest::ReceivePkt(), UdpSocketLoopbackTest::ReceivePkt(), Udp6SocketLoopbackTest::ReceivePkt(), UdpSocketImplTest::ReceivePkt(), Udp6SocketImplTest::ReceivePkt(), SixlowpanHc1ImplTest::ReceivePkt(), SixlowpanIphcImplTest::ReceivePkt(), Ipv4RawSocketImplTest::ReceivePkt2(), Ipv6RawSocketImplTest::ReceivePkt2(), UdpSocketImplTest::ReceivePkt2(), Udp6SocketImplTest::ReceivePkt2(), ns3::olsr::HelloRegressionTest::ReceivePktProbeA(), ns3::olsr::TcRegressionTest::ReceivePktProbeA(), ns3::olsr::HelloRegressionTest::ReceivePktProbeB(), ns3::olsr::TcRegressionTest::ReceivePktProbeB(), ns3::olsr::TcRegressionTest::ReceivePktProbeC(), ns3::EpcEnbApplication::RecvFromLteSocket(), ns3::EpcMmeApplication::RecvFromS11Socket(), ns3::EpcSgwApplication::RecvFromS11Socket(), ns3::EpcEnbApplication::RecvFromS1uSocket(), ns3::EpcSgwApplication::RecvFromS1uSocket(), ns3::EpcPgwApplication::RecvFromS5cSocket(), ns3::EpcSgwApplication::RecvFromS5cSocket(), ns3::EpcPgwApplication::RecvFromS5uSocket(), ns3::EpcSgwApplication::RecvFromS5uSocket(), ns3::EpcX2::RecvFromX2cSocket(), ns3::EpcX2::RecvFromX2uSocket(), Ipv4PacketInfoTagTest::RxCb(), Ipv6PacketInfoTagTest::RxCb(), TcpTestCase::ServerHandleRecv(), SocketPrinter(), and TcpTestCase::SourceHandleRecv().
Recv() [2/3]
int ns3::Socket::Recv (uint8_t * buf, uint32_t size, uint32_t flags)
Recv data (or dummy data) from the remote host.
This method is provided so as to have an API which is closer in appearance to that of real network or BSD sockets.
If the underlying packet was carring null (fake) data, this buffer will be zeroed up to the length specified by the return value.
Parameters
buf A pointer to a raw byte buffer to write the data to.
size Number of bytes (at most) to copy to buf
flags any flags to pass to the socket
Returns
number of bytes copied into buf
Definition at line 182 of file socket.cc.
References ns3::Packet::CopyData(), ns3::Packet::GetSize(), NS_LOG_FUNCTION, and Recv().
Recv() [3/3]
Ptr< Packet > ns3::Socket::Recv (void)
Read a single packet from the socket.
Overloaded version of Recv(maxSize, flags) with maxSize implicitly set to maximum sized integer, and flags set to zero.
Returns
Ptr<Packet> of the next in-sequence packet. Returns 0 if the socket cannot return a next in-sequence packet.
Definition at line 175 of file socket.cc.
References max, and NS_LOG_FUNCTION.
Referenced by Recv(), ns3::NscTcpSocketImpl::RecvFrom(), and ns3::TcpSocketBase::RecvFrom().
RecvFrom() [1/3]
Ptr< Packet > ns3::Socket::RecvFrom (Address & fromAddress)
Read a single packet from the socket and retrieve the sender address.
Calls RecvFrom (maxSize, flags, fromAddress) with maxSize implicitly set to maximum sized integer, and flags set to zero.
Parameters
fromAddress output parameter that will return the address of the sender of the received packet, if any. Remains untouched if no packet is received.
Returns
Ptr<Packet> of the next in-sequence packet. Returns 0 if the socket cannot return a next in-sequence packet.
Definition at line 195 of file socket.cc.
References max, NS_LOG_FUNCTION, and RecvFrom().
RecvFrom() [2/3]
virtual Ptr<Packet> ns3::Socket::RecvFrom (uint32_t maxSize, uint32_t flags, Address & fromAddress) pure virtual
Read a single packet from the socket and retrieve the sender address.
Calls Recv(maxSize, flags) with maxSize implicitly set to maximum sized integer, and flags set to zero.
This method has similar semantics to Recv () but subclasses may want to provide checks on socket state, so the implementation is pushed to subclasses.
Parameters
maxSize reader will accept packet up to maxSize
flags Socket control flags
fromAddress output parameter that will return the address of the sender of the received packet, if any. Remains untouched if no packet is received.
Returns
Ptr<Packet> of the next in-sequence packet. Returns 0 if the socket cannot return a next in-sequence packet.
Implemented in ns3::PacketSocket, ns3::UdpSocketImpl, ns3::TcpSocketBase, ns3::NscTcpSocketImpl, ns3::Ipv6RawSocketImpl, and ns3::Ipv4RawSocketImpl.
Referenced by dstSocketRecv(), ns3::aodv::LoopbackTestCase::EchoData(), ns3::PacketSink::HandleRead(), ns3::UdpEchoClient::HandleRead(), ns3::UdpEchoServer::HandleRead(), ns3::UdpServer::HandleRead(), ns3::Ping6::HandleRead(), ns3::Radvd::HandleRead(), Ipv4DynamicGlobalRoutingTestCase::HandleRead(), ns3::PacketSocketServer::HandleRead(), Ipv4FragmentationTest::HandleReadClient(), Ipv6FragmentationTest::HandleReadClient(), HwmpProactiveRegressionTest::HandleReadClient(), HwmpReactiveRegressionTest::HandleReadClient(), HwmpSimplestRegressionTest::HandleReadClient(), HwmpDoRfRegressionTest::HandleReadClient(), FlameRegressionTest::HandleReadClient(), SixlowpanFragmentationTest::HandleReadClient(), Ipv4FragmentationTest::HandleReadServer(), Ipv6FragmentationTest::HandleReadServer(), HwmpProactiveRegressionTest::HandleReadServer(), HwmpReactiveRegressionTest::HandleReadServer(), HwmpSimplestRegressionTest::HandleReadServer(), HwmpDoRfRegressionTest::HandleReadServer(), FlameRegressionTest::HandleReadServer(), SixlowpanFragmentationTest::HandleReadServer(), ns3::DhcpClient::NetHandler(), ns3::DhcpServer::NetHandler(), UanExperiment::PrintReceivedPacket(), Receiver::Receive(), ns3::V4Ping::Receive(), ns3::V4TraceRoute::Receive(), ns3::Rip::Receive(), ns3::RipNg::Receive(), ns3::olsr::Bug780Test::Receive(), ns3::ThreeGppHttpClient::ReceivedDataCallback(), ns3::ThreeGppHttpServer::ReceivedDataCallback(), ReceivePacket(), RoutingExperiment::ReceivePacket(), ns3::TcpGeneralTest::ReceivePacket(), IcmpEchoReplyTestCase::ReceivePkt(), IcmpTimeExceedTestCase::ReceivePkt(), IcmpV6EchoReplyTestCase::ReceivePkt(), IcmpV6TimeExceedTestCase::ReceivePkt(), Ipv6RawSocketImplTest::ReceivePkt2(), Ipv4RipSplitHorizonStrategyTest::ReceivePktProbe(), Ipv6RipngSplitHorizonStrategyTest::ReceivePktProbe(), RoutingHelper::ReceiveRoutingPacket(), ns3::BsmApplication::ReceiveWavePacket(), ns3::aodv::RoutingProtocol::RecvAodv(), ns3::dsdv::RoutingProtocol::RecvDsdv(), RecvFrom(), ns3::olsr::RoutingProtocol::RecvOlsr(), and srcSocketRecv().
RecvFrom() [3/3]
int ns3::Socket::RecvFrom (uint8_t * buf, uint32_t size, uint32_t flags, Address & fromAddress)
Read a single packet from the socket and retrieve the sender address.
This method is provided so as to have an API which is closer in appearance to that of real network or BSD sockets.
Parameters
buf A pointer to a raw byte buffer to write the data to. If the underlying packet was carring null (fake) data, this buffer will be zeroed up to the length specified by the return value.
size Number of bytes (at most) to copy to buf
flags any flags to pass to the socket
fromAddress output parameter that will return the address of the sender of the received packet, if any. Remains untouched if no packet is received.
Returns
number of bytes copied into buf
Definition at line 202 of file socket.cc.
References ns3::Packet::CopyData(), ns3::Packet::GetSize(), NS_LOG_FUNCTION, and RecvFrom().
Send() [1/3]
int ns3::Socket::Send (const uint8_t * buf, uint32_t size, uint32_t flags)
Send data (or dummy data) to the remote host.
This method is provided so as to have an API which is closer in appearance to that of real network or BSD sockets.
Parameters
buf A pointer to a raw byte buffer of some data to send. If this buffer is 0, we send dummy data whose size is specified by the second parameter
size the number of bytes to copy from the buffer
flags Socket control flags
Returns
the number of bytes accepted for transmission if no error occurs, and -1 otherwise.
Definition at line 142 of file socket.cc.
References NS_LOG_FUNCTION, and Send().
Send() [2/3]
int ns3::Socket::Send (Ptr< Packet > p)
Send data (or dummy data) to the remote host.
Overloaded version of Send(..., flags) with flags set to zero.
Parameters
p ns3::Packet to send
Returns
the number of bytes accepted for transmission if no error occurs, and -1 otherwise.
Definition at line 135 of file socket.cc.
References NS_LOG_FUNCTION, and Send().
Send() [3/3]
virtual int ns3::Socket::Send (Ptr< Packet > p, uint32_t flags) pure virtual
Send data (or dummy data) to the remote host.
This function matches closely in semantics to the send() function call in the standard C library (libc): ssize_t send (int s, const void *msg, size_t len, int flags); except that the send I/O is asynchronous. This is the primary Send method at this low-level API and must be implemented by subclasses.
In a typical blocking sockets model, this call would block upon lack of space to hold the message to be sent. In ns-3 at this API, the call returns immediately in such a case, but the callback registered with SetSendCallback() is invoked when the socket has space (when it conceptually unblocks); this is an asynchronous I/O model for send().
This variant of Send() uses class ns3::Packet to encapsulate data, rather than providing a raw pointer and length field. This allows an ns-3 application to attach tags if desired (such as a flow ID) and may allow the simulator to avoid some data copies. Despite the appearance of sending Packets on a stream socket, just think of it as a fancy byte buffer with streaming semantics.
If either the message buffer within the Packet is too long to pass atomically through the underlying protocol (for datagram sockets), or the message buffer cannot entirely fit in the transmit buffer (for stream sockets), -1 is returned and SocketErrno is set to ERROR_MSGSIZE. If the packet does not fit, the caller can split the Packet (based on information obtained from GetTxAvailable) and reattempt to send the data.
The flags argument is formed by or'ing one or more of the values: MSG_OOB process out-of-band data MSG_DONTROUTE bypass routing, use direct interface These flags are unsupported as of ns-3.1.
Parameters
p ns3::Packet to send
flags Socket control flags
Returns
the number of bytes accepted for transmission if no error occurs, and -1 otherwise.
See also
SetSendCallback
Implemented in ns3::PacketSocket, ns3::UdpSocketImpl, ns3::TcpSocketBase, ns3::NscTcpSocketImpl, ns3::Ipv6RawSocketImpl, and ns3::Ipv4RawSocketImpl.
Referenced by UdpSocketImplTest::DoSendData(), GenerateTraffic(), Experiment::GenerateTraffic(), WifiInterferenceTestCase::GenerateTraffic(), ns3::BsmApplication::GenerateWaveTraffic(), TcpEndPointBug2211Test::HandleConnect(), ns3::ThreeGppHttpClient::RequestEmbeddedObject(), ns3::ThreeGppHttpClient::RequestMainObject(), ns3::V4Ping::Send(), Send(), ns3::UdpClient::Send(), ns3::UdpEchoClient::Send(), EpsBearerTagUdpClient::Send(), ns3::PacketSocketClient::Send(), Ipv4FragmentationTest::SendClient(), Ipv6FragmentationTest::SendClient(), SixlowpanFragmentationTest::SendClient(), ns3::BulkSendApplication::SendData(), Bug772ChainTest::SendData(), HwmpProactiveRegressionTest::SendData(), HwmpReactiveRegressionTest::SendData(), HwmpSimplestRegressionTest::SendData(), FlameRegressionTest::SendData(), HwmpDoRfRegressionTest::SendDataA(), HwmpDoRfRegressionTest::SendDataB(), HwmpDoRfRegressionTest::SendDataC(), ns3::OnOffApplication::SendPacket(), SendPacket(), ns3::TcpGeneralTest::SendPacket(), ns3::UdpTraceClient::SendPacket(), MyApp::SendPacket(), SimpleSource::SendPacket(), ns3::dsdv::RoutingProtocol::SendPeriodicUpdate(), ChainRegressionTest::SendPing(), ns3::olsr::Bug780Test::SendPing(), ns3::EpcEnbApplication::SendToLteSocket(), ns3::ThreeGppHttpServer::ServeFromTxBuffer(), TcpTestCase::ServerHandleSend(), TcpTestCase::SourceHandleSend(), ns3::SocketWriter::Write(), Ns3TcpLossTestCase::WriteUntilBufferFull(), Ns3TcpStateTestCase::WriteUntilBufferFull(), and WriteUntilBufferFull().
SendTo() [1/2]
int ns3::Socket::SendTo (const uint8_t * buf, uint32_t size, uint32_t flags, const Address & address)
Send data to a specified peer.
This method is provided so as to have an API which is closer in appearance to that of real network or BSD sockets.
Parameters
buf A pointer to a raw byte buffer of some data to send. If this is 0, we send dummy data whose size is specified by the third parameter
size the number of bytes to copy from the buffer
flags Socket control flags
address IP Address of remote host
Returns
-1 in case of error or the number of bytes copied in the internal buffer and accepted for transmission.
Definition at line 158 of file socket.cc.
References NS_LOG_FUNCTION, and SendTo().
SendTo() [2/2]
virtual int ns3::Socket::SendTo (Ptr< Packet > p, uint32_t flags, const Address & toAddress) pure virtual
Send data to a specified peer.
This method has similar semantics to Send () but subclasses may want to provide checks on socket state, so the implementation is pushed to subclasses.
Parameters
p packet to send
flags Socket control flags
toAddress IP Address of remote host
Returns
-1 in case of error or the number of bytes copied in the internal buffer and accepted for transmission.
Implemented in ns3::PacketSocket, ns3::TcpSocketBase, ns3::NscTcpSocketImpl, ns3::Ipv6RawSocketImpl, ns3::Ipv4RawSocketImpl, and ns3::UdpSocketImpl.
Referenced by ns3::DhcpClient::Boot(), ns3::EpcMmeApplication::DoErabReleaseIndication(), ns3::EpcMmeApplication::DoInitialUeMessage(), ns3::EpcMmeApplication::DoPathSwitchRequest(), ns3::EpcPgwApplication::DoRecvCreateSessionRequest(), ns3::EpcSgwApplication::DoRecvCreateSessionRequest(), ns3::EpcSgwApplication::DoRecvCreateSessionResponse(), ns3::EpcPgwApplication::DoRecvDeleteBearerCommand(), ns3::EpcSgwApplication::DoRecvDeleteBearerCommand(), ns3::EpcMmeApplication::DoRecvDeleteBearerRequest(), ns3::EpcSgwApplication::DoRecvDeleteBearerRequest(), ns3::EpcSgwApplication::DoRecvDeleteBearerResponse(), ns3::EpcPgwApplication::DoRecvModifyBearerRequest(), ns3::EpcSgwApplication::DoRecvModifyBearerRequest(), ns3::EpcSgwApplication::DoRecvModifyBearerResponse(), UdpSocketLoopbackTest::DoRun(), Udp6SocketLoopbackTest::DoRun(), Ipv4DeduplicationPerformanceTest::DoSendData(), IcmpEchoReplyTestCase::DoSendData(), IcmpTimeExceedTestCase::DoSendData(), IcmpV6EchoReplyTestCase::DoSendData(), IcmpV6TimeExceedTestCase::DoSendData(), Ipv4ForwardingTest::DoSendData(), Ipv4GlobalRoutingSlash32TestCase::DoSendData(), Ipv4PacketInfoTagTest::DoSendData(), Ipv4RawSocketImplTest::DoSendData(), Ipv4RipTest::DoSendData(), Ipv4RipCountToInfinityTest::DoSendData(), Ipv4StaticRoutingSlash32TestCase::DoSendData(), Ipv6ForwardingTest::DoSendData(), Ipv6PacketInfoTagTest::DoSendData(), Ipv6RawSocketImplTest::DoSendData(), Ipv6RipngTest::DoSendData(), Ipv6RipngCountToInfinityTest::DoSendData(), SixlowpanHc1ImplTest::DoSendData(), SixlowpanIphcImplTest::DoSendData(), Ipv4RawSocketImplTest::DoSendData_IpHdr(), Ipv4HeaderTest::DoSendData_IpHdr_Dscp(), UdpSocketImplTest::DoSendDataTo(), Udp6SocketImplTest::DoSendDataTo(), ns3::EpcX2::DoSendHandoverPreparationFailure(), ns3::EpcX2::DoSendHandoverRequest(), ns3::EpcX2::DoSendHandoverRequestAck(), ns3::EpcX2::DoSendLoadInformation(), Ipv4DeduplicationTest::DoSendPacket(), ns3::EpcX2::DoSendResourceStatusUpdate(), ns3::EpcX2::DoSendSnStatusTransfer(), ns3::EpcX2::DoSendUeContextRelease(), ns3::EpcX2::DoSendUeData(), ns3::aodv::LoopbackTestCase::EchoData(), ns3::UdpEchoServer::HandleRead(), HwmpProactiveRegressionTest::HandleReadServer(), HwmpReactiveRegressionTest::HandleReadServer(), HwmpSimplestRegressionTest::HandleReadServer(), HwmpDoRfRegressionTest::HandleReadServer(), FlameRegressionTest::HandleReadServer(), ns3::Rip::HandleRequests(), ns3::RipNg::HandleRequests(), Tunnel::N0VirtualSend(), Tunnel::N1VirtualSend(), Tunnel::N3VirtualSend(), ns3::aodv::RoutingProtocol::RecvReply(), ns3::DhcpClient::Request(), ns3::Ping6::Send(), ns3::V4TraceRoute::Send(), ns3::DhcpServer::SendAck(), ns3::aodv::LoopbackTestCase::SendData(), ns3::DhcpServer::SendOffer(), ns3::dsdv::RoutingProtocol::SendPeriodicUpdate(), ns3::aodv::RoutingProtocol::SendReply(), ns3::aodv::RoutingProtocol::SendReplyAck(), ns3::aodv::RoutingProtocol::SendReplyByIntermediateNode(), ns3::aodv::RoutingProtocol::SendRerrWhenNoRouteToForward(), SendStuff(), SendTo(), ns3::aodv::RoutingProtocol::SendTo(), ns3::EpcSgwApplication::SendToS1uSocket(), ns3::EpcEnbApplication::SendToS1uSocket(), ns3::EpcSgwApplication::SendToS5uSocket(), ns3::EpcPgwApplication::SendToS5uSocket(), and ns3::dsdv::RoutingProtocol::SendTriggeredUpdate().
SetAcceptCallback()
void ns3::Socket::SetAcceptCallback (Callback< bool, Ptr< Socket >, const Address & > connectionRequest, Callback< void, Ptr< Socket >, const Address & > newConnectionCreated)
Accept connection requests from remote hosts.
Parameters
connectionRequest Callback for connection request from peer. This user callback is passed a pointer to this socket, the ip address and the port number of the connection originator. This callback must return true to accept the incoming connection, false otherwise. If the connection is accepted, the "newConnectionCreated" callback will be invoked later to give access to the user to the socket created to match this new connection. If the user does not explicitly specify this callback, all incoming connections will be refused.
newConnectionCreated Callback for new connection: when a new is accepted, it is created and the corresponding socket is passed back to the user through this callback. This user callback is passed a pointer to the new socket, and the ip address and port number of the connection originator.
Definition at line 104 of file socket.cc.
References m_connectionRequest, m_newConnectionCreated, and NS_LOG_FUNCTION.
Referenced by DualStackTestCase::DoRun(), ns3::ThreeGppHttpServer::StartApplication(), ns3::PacketSink::StartApplication(), and ns3::ThreeGppHttpServer::StopApplication().
SetAllowBroadcast()
virtual bool ns3::Socket::SetAllowBroadcast (bool allowBroadcast) pure virtual
Configure whether broadcast datagram transmissions are allowed.
This method corresponds to using setsockopt() SO_BROADCAST of real network or BSD sockets. If set on a socket, this option will enable or disable packets to be transmitted to broadcast destination addresses.
Parameters
allowBroadcast Whether broadcast is allowed
Returns
true if operation succeeds
Implemented in ns3::PacketSocket, ns3::UdpSocketImpl, ns3::TcpSocketBase, ns3::NscTcpSocketImpl, ns3::Ipv6RawSocketImpl, and ns3::Ipv4RawSocketImpl.
Referenced by Bug772ChainTest::CreateDevices(), ns3::olsr::RoutingProtocol::DoInitialize(), Ipv4ForwardingTest::DoRun(), Ipv4GlobalRoutingSlash32TestCase::DoRun(), Ipv4RipTest::DoRun(), Ipv4RipCountToInfinityTest::DoRun(), Ipv4StaticRoutingSlash32TestCase::DoRun(), Ipv6ForwardingTest::DoRun(), Ipv6RipngTest::DoRun(), Ipv6RipngCountToInfinityTest::DoRun(), UdpSocketImplTest::DoRun(), Udp6SocketImplTest::DoRun(), SixlowpanHc1ImplTest::DoRun(), SixlowpanIphcImplTest::DoRun(), ns3::aodv::RoutingProtocol::NotifyAddAddress(), ns3::dsdv::RoutingProtocol::NotifyAddAddress(), ns3::aodv::RoutingProtocol::NotifyInterfaceUp(), ns3::dsdv::RoutingProtocol::NotifyInterfaceUp(), ns3::aodv::RoutingProtocol::NotifyRemoveAddress(), ns3::dsdv::RoutingProtocol::NotifyRemoveAddress(), ns3::OnOffApplication::StartApplication(), ns3::UdpClient::StartApplication(), ns3::UdpEchoClient::StartApplication(), ns3::UdpTraceClient::StartApplication(), ns3::DhcpClient::StartApplication(), ns3::DhcpServer::StartApplication(), and ns3::BsmApplication::StartApplication().
SetCloseCallbacks()
void ns3::Socket::SetCloseCallbacks (Callback< void, Ptr< Socket > > normalClose, Callback< void, Ptr< Socket > > errorClose)
Detect socket recv() events such as graceful shutdown or error.
For connection-oriented sockets, the first callback is used to signal that the remote side has gracefully shut down the connection, and the second callback denotes an error corresponding to cases in which a traditional recv() socket call might return -1 (error), such as a connection reset. For datagram sockets, these callbacks may never be invoked.
Parameters
normalClose this callback is invoked when the peer closes the connection gracefully
errorClose this callback is invoked when the connection closes abnormally
Definition at line 94 of file socket.cc.
References m_errorClose, m_normalClose, and NS_LOG_FUNCTION.
Referenced by ns3::TcpGeneralTest::HandleAccept(), ns3::ThreeGppHttpServer::NewConnectionCreatedCallback(), ns3::ThreeGppHttpClient::NormalCloseCallback(), ns3::ThreeGppHttpClient::OpenConnection(), ns3::ThreeGppHttpServer::StartApplication(), ns3::PacketSink::StartApplication(), and ns3::ThreeGppHttpServer::StopApplication().
SetConnectCallback()
void ns3::Socket::SetConnectCallback (Callback< void, Ptr< Socket > > connectionSucceeded, Callback< void, Ptr< Socket > > connectionFailed)
Specify callbacks to allow the caller to determine if the connection succeeds of fails.
Parameters
connectionSucceeded this callback is invoked when the connection request initiated by the user is successfully completed. The callback is passed back a pointer to the same socket object.
connectionFailed this callback is invoked when the connection request initiated by the user is unsuccessfully completed. The callback is passed back a pointer to the same socket object.
Definition at line 84 of file socket.cc.
References m_connectionFailed, m_connectionSucceeded, and NS_LOG_FUNCTION.
Referenced by ns3::TcpSocketBase::TcpSocketBase(), TcpEndPointBug2211Test::DoRun(), ns3::ThreeGppHttpClient::OpenConnection(), ns3::BulkSendApplication::StartApplication(), ns3::OnOffApplication::StartApplication(), and ns3::ThreeGppHttpClient::StopApplication().
SetDataSentCallback()
void ns3::Socket::SetDataSentCallback (Callback< void, Ptr< Socket >, uint32_t > dataSent)
Notify application when a packet has been sent from transport protocol (non-standard socket call)
Parameters
dataSent Callback for the event that data is sent from the underlying transport protocol. This callback is passed a pointer to the socket, and the number of bytes sent.
Definition at line 114 of file socket.cc.
References m_dataSent, and NS_LOG_FUNCTION.
Referenced by ns3::TcpSocketBase::TcpSocketBase().
SetIpRecvTos()
void ns3::Socket::SetIpRecvTos (bool ipv4RecvTos)
Tells a socket to pass information about IP Type of Service up the stack.
This method corresponds to using setsockopt () IP_RECVTOS of real network or BSD sockets. In our implementation, the socket simply adds a SocketIpTosTag tag to the packet before passing the packet up the stack.
Parameters
ipv4RecvTos Whether the socket should add SocketIpv4TosTag tag to the packet
Definition at line 459 of file socket.cc.
References m_ipRecvTos.
SetIpRecvTtl()
void ns3::Socket::SetIpRecvTtl (bool ipv4RecvTtl)
Tells a socket to pass information about IP_TTL up the stack.
This method corresponds to using setsockopt () IP_RECVTTL of real network or BSD sockets. In our implementation, the socket simply adds a SocketIpTtlTag tag to the packet before passing the packet up the stack.
Parameters
ipv4RecvTtl Whether the socket should add SocketIpv4TtlTag tag to the packet
Definition at line 526 of file socket.cc.
References m_ipRecvTtl.
Referenced by ns3::Rip::DoInitialize(), ns3::aodv::RoutingProtocol::NotifyAddAddress(), ns3::aodv::RoutingProtocol::NotifyInterfaceUp(), ns3::Rip::NotifyInterfaceUp(), and ns3::aodv::RoutingProtocol::NotifyRemoveAddress().
SetIpTos()
void ns3::Socket::SetIpTos (uint8_t ipTos)
Manually set IP Type of Service field.
This method corresponds to using setsockopt () IP_TOS of real network or BSD sockets. This option is for IPv4 only. Setting the IP TOS also changes the socket priority as stated in the man page.
Parameters
ipTos The desired TOS value for IP headers
Definition at line 437 of file socket.cc.
References first::address, GetSocketType(), GetSockName(), IpTos2Priority(), m_ipTos, m_priority, and NS3_SOCK_STREAM.
Referenced by ns3::TcpSocketBase::Bind(), ns3::UdpSocketImpl::Bind(), ns3::Ipv4RawSocketImpl::Connect(), ns3::TcpSocketBase::Connect(), and ns3::UdpSocketImpl::Connect().
SetIpTtl()
void ns3::Socket::SetIpTtl (uint8_t ipTtl) virtual
Manually set IP Time to Live field.
This method corresponds to using setsockopt () IP_TTL of real network or BSD sockets.
Parameters
ipTtl The desired TTL value for IP headers
Definition at line 513 of file socket.cc.
References m_ipTtl, and m_manualIpTtl.
Referenced by IcmpEchoReplyTestCase::DoRun(), IcmpTimeExceedTestCase::DoRun(), IcmpV6EchoReplyTestCase::DoRun(), ns3::UdpSocket::GetTypeId(), and ns3::V4TraceRoute::Send().
SetIpv6HopLimit()
void ns3::Socket::SetIpv6HopLimit (uint8_t ipHopLimit) virtual
Manually set IPv6 Hop Limit.
This method corresponds to using setsockopt () IPV6_HOPLIMIT of real network or BSD sockets.
Parameters
ipHopLimit The desired Hop Limit value for IPv6 headers
Definition at line 538 of file socket.cc.
References m_ipv6HopLimit, and m_manualIpv6HopLimit.
Referenced by IcmpV6TimeExceedTestCase::DoRun().
SetIpv6RecvHopLimit()
void ns3::Socket::SetIpv6RecvHopLimit (bool ipv6RecvHopLimit)
Tells a socket to pass information about IPv6 Hop Limit up the stack.
This method corresponds to using setsockopt () IPV6_RECVHOPLIMIT of real network or BSD sockets. In our implementation, the socket simply adds a SocketIpv6HopLimitTag tag to the packet before passing the packet up the stack.
Parameters
ipv6RecvHopLimit Whether the socket should add SocketIpv6HopLimitTag tag to the packet
Definition at line 551 of file socket.cc.
References m_ipv6RecvHopLimit.
Referenced by ns3::RipNg::DoInitialize(), and ns3::RipNg::NotifyInterfaceUp().
SetIpv6RecvTclass()
void ns3::Socket::SetIpv6RecvTclass (bool ipv6RecvTclass)
Tells a socket to pass information about IPv6 Traffic Class up the stack.
This method corresponds to using setsockopt () IPV6_RECVTCLASS of real network or BSD sockets. In our implementation, the socket simply adds a SocketIpv6TclasssTag tag to the packet before passing the packet up the stack.
Parameters
ipv6RecvTclass Whether the socket should add SocketIpv6TclassTag tag to the packet
Definition at line 501 of file socket.cc.
References m_ipv6RecvTclass.
SetIpv6Tclass()
void ns3::Socket::SetIpv6Tclass (int ipTclass)
Manually set IPv6 Traffic Class field.
This method corresponds to using setsockopt () IPV6_TCLASS of real network or BSD sockets. This option is for IPv6 only. Setting the IPV6_TCLASSS to -1 clears the option and let the socket uses the default value.
Parameters
ipTclass The desired TCLASS value for IPv6 headers
Definition at line 471 of file socket.cc.
References first::address, GetSockName(), m_ipv6Tclass, m_manualIpv6Tclass, and NS_LOG_WARN.
SetPriority()
void ns3::Socket::SetPriority (uint8_t priority)
Manually set the socket priority.
This method corresponds to using setsockopt () SO_PRIORITY of real network or BSD sockets. On Linux, the socket priority can be set to a value in the range [0..6], unless the user process has the CAP_NET_ADMIN capability (see the man page for socket). ns-3 allows users to set the socket priority to any 8-bit non-negative value, which is equivalent to assuming that the CAP_NET_ADMIN capability is set.
Parameters
priority The socket priority
Definition at line 389 of file socket.cc.
References m_priority, and NS_LOG_FUNCTION.
Referenced by ns3::PacketSocketClient::SetPriority(), and ns3::PacketSocketClient::StartApplication().
SetRecvCallback()
void ns3::Socket::SetRecvCallback (Callback< void, Ptr< Socket > > receivedData)
Notify application when new data is available to be read.
   This callback is intended to notify a socket that would
   have been blocked in a blocking socket model that data
   is available to be read.
Definition at line 128 of file socket.cc.
References m_receivedData, and NS_LOG_FUNCTION.
Referenced by ns3::EpcEnbApplication::EpcEnbApplication(), ns3::EpcPgwApplication::EpcPgwApplication(), ns3::EpcSgwApplication::EpcSgwApplication(), ns3::TcpSocketBase::TcpSocketBase(), Tunnel::Tunnel(), ns3::EpcSgwApplication::AddMme(), ns3::EpcEnbApplication::AddS1Interface(), ns3::EpcMmeApplication::AddSgw(), ns3::EpcX2::AddX2Interface(), ns3::ThreeGppHttpClient::ConnectionSucceededCallback(), Bug772ChainTest::CreateDevices(), ns3::olsr::Bug780Test::CreateNodes(), ns3::olsr::HelloRegressionTest::CreateNodes(), ns3::olsr::TcRegressionTest::CreateNodes(), ns3::EpcPgwApplication::DoDispose(), ns3::EpcSgwApplication::DoDispose(), ns3::Rip::DoInitialize(), ns3::RipNg::DoInitialize(), ns3::olsr::RoutingProtocol::DoInitialize(), ns3::aodv::LoopbackTestCase::DoRun(), IcmpEchoReplyTestCase::DoRun(), IcmpTimeExceedTestCase::DoRun(), IcmpV6EchoReplyTestCase::DoRun(), IcmpV6TimeExceedTestCase::DoRun(), Ipv4DynamicGlobalRoutingTestCase::DoRun(), Ipv4RawSocketImplTest::DoRun(), Ipv6RawSocketImplTest::DoRun(), UdpSocketImplTest::DoRun(), Udp6SocketImplTest::DoRun(), TcpEndPointBug2211Test::HandleAccept(), ns3::PacketSink::HandleAccept(), ns3::TcpGeneralTest::HandleAccept(), HwmpProactiveRegressionTest::InstallApplications(), HwmpReactiveRegressionTest::InstallApplications(), HwmpSimplestRegressionTest::InstallApplications(), HwmpDoRfRegressionTest::InstallApplications(), FlameRegressionTest::InstallApplications(), ns3::DhcpClient::LinkStateHandler(), ns3::ThreeGppHttpServer::NewConnectionCreatedCallback(), ns3::aodv::RoutingProtocol::NotifyAddAddress(), ns3::dsdv::RoutingProtocol::NotifyAddAddress(), ns3::aodv::RoutingProtocol::NotifyInterfaceUp(), ns3::dsdv::RoutingProtocol::NotifyInterfaceUp(), ns3::Rip::NotifyInterfaceUp(), ns3::RipNg::NotifyInterfaceUp(), ns3::aodv::RoutingProtocol::NotifyRemoveAddress(), ns3::dsdv::RoutingProtocol::NotifyRemoveAddress(), ns3::ThreeGppHttpClient::OpenConnection(), PrintTraffic(), NetAnimExperiment::Run(), Experiment::Run(), TcpTestCase::ServerHandleConnectionCreated(), TcpTestCase::SetupDefaultSim(), TcpTestCase::SetupDefaultSim6(), ns3::ThreeGppHttpServer::StartApplication(), ns3::Ping6::StartApplication(), ns3::Radvd::StartApplication(), Receiver::StartApplication(), ns3::PacketSink::StartApplication(), ns3::UdpClient::StartApplication(), ns3::UdpEchoClient::StartApplication(), ns3::UdpEchoServer::StartApplication(), ns3::UdpServer::StartApplication(), ns3::UdpTraceClient::StartApplication(), ns3::DhcpClient::StartApplication(), ns3::DhcpServer::StartApplication(), ns3::V4Ping::StartApplication(), ns3::V4TraceRoute::StartApplication(), EpsBearerTagUdpClient::StartApplication(), ns3::PacketSocketClient::StartApplication(), ns3::PacketSocketServer::StartApplication(), ns3::BsmApplication::StartApplication(), Ipv4FragmentationTest::StartClient(), Ipv6FragmentationTest::StartClient(), SixlowpanFragmentationTest::StartClient(), Ipv4FragmentationTest::StartServer(), Ipv6FragmentationTest::StartServer(), SixlowpanFragmentationTest::StartServer(), ns3::ThreeGppHttpClient::StopApplication(), ns3::ThreeGppHttpServer::StopApplication(), ns3::Ping6::StopApplication(), ns3::Radvd::StopApplication(), Receiver::StopApplication(), ns3::PacketSink::StopApplication(), ns3::UdpEchoClient::StopApplication(), ns3::UdpEchoServer::StopApplication(), ns3::UdpServer::StopApplication(), ns3::DhcpClient::StopApplication(), ns3::DhcpServer::StopApplication(), ns3::PacketSocketServer::StopApplication(), and WifiInterferenceTestCase::WifiSimpleInterference().
SetRecvPktInfo()
void ns3::Socket::SetRecvPktInfo (bool flag)
Enable/Disable receive packet information to socket.
For IP_PKTINFO/IP6_PKTINFO. This method is only usable for Raw socket and Datagram Socket. Not supported for Stream socket.
Method doesn't make distinction between IPv4 and IPv6. If it is enabled, it is enabled for all types of sockets that supports packet information
Parameters
flag Enable/Disable receive information
Returns
nothing
Definition at line 358 of file socket.cc.
References m_recvPktInfo, and NS_LOG_FUNCTION.
Referenced by ns3::Rip::DoInitialize(), ns3::RipNg::DoInitialize(), ns3::olsr::RoutingProtocol::DoInitialize(), Ipv4DynamicGlobalRoutingTestCase::DoRun(), ns3::Rip::NotifyInterfaceUp(), ns3::RipNg::NotifyInterfaceUp(), ns3::Radvd::StartApplication(), and ns3::DhcpServer::StartApplication().
SetSendCallback()
void ns3::Socket::SetSendCallback (Callback< void, Ptr< Socket >, uint32_t > sendCb)
Notify application when space in transmit buffer is added.
   This callback is intended to notify a
   socket that would have been blocked in a blocking socket model
   that space is available in the transmit buffer and that it
   can call Send() again.
Parameters
sendCb Callback for the event that the socket transmit buffer fill level has decreased. This callback is passed a pointer to the socket, and the number of bytes available for writing into the buffer (an absolute value). If there is no transmit buffer limit, a maximum-sized integer is always returned.
Definition at line 121 of file socket.cc.
References m_sendCb, and NS_LOG_FUNCTION.
Referenced by ns3::TcpSocketBase::TcpSocketBase(), ns3::ThreeGppHttpServer::NewConnectionCreatedCallback(), TcpTestCase::ServerHandleConnectionCreated(), TcpTestCase::SetupDefaultSim(), TcpTestCase::SetupDefaultSim6(), ns3::ThreeGppHttpServer::StartApplication(), ns3::BulkSendApplication::StartApplication(), Ns3TcpLossTestCase::StartFlow(), Ns3TcpStateTestCase::StartFlow(), StartFlow(), and ns3::ThreeGppHttpServer::StopApplication().
ShutdownRecv()
virtual int ns3::Socket::ShutdownRecv (void) pure virtual
Returns
zero on success, -1 on failure.
Do not allow any further Recv calls. This method is typically implemented for Tcp sockets by a half close.
Implemented in ns3::PacketSocket, ns3::UdpSocketImpl, ns3::TcpSocketBase, ns3::NscTcpSocketImpl, ns3::Ipv4RawSocketImpl, and ns3::Ipv6RawSocketImpl.
Referenced by ns3::BulkSendApplication::StartApplication(), and ns3::OnOffApplication::StartApplication().
ShutdownSend()
virtual int ns3::Socket::ShutdownSend (void) pure virtual
Returns
zero on success, -1 on failure.
Do not allow any further Send calls. This method is typically implemented for Tcp sockets by a half close.
Implemented in ns3::PacketSocket, ns3::UdpSocketImpl, ns3::TcpSocketBase, ns3::NscTcpSocketImpl, ns3::Ipv4RawSocketImpl, and ns3::Ipv6RawSocketImpl.
Referenced by Bug772ChainTest::CreateDevices(), ns3::olsr::RoutingProtocol::DoInitialize(), Ipv4DynamicGlobalRoutingTestCase::DoRun(), ns3::ThreeGppHttpServer::NormalCloseCallback(), ns3::Radvd::StartApplication(), and ns3::PacketSink::StartApplication().
Member Data Documentation
m_boundnetdevice
Ptr<NetDevice> ns3::Socket::m_boundnetdevice protected
the device this socket is bound to (might be null).
Definition at line 1076 of file socket.h.
Referenced by Socket(), ns3::UdpSocketImpl::Bind(), ns3::UdpSocketImpl::Bind6(), ns3::UdpSocketImpl::BindToNetDevice(), BindToNetDevice(), ns3::PacketSocket::DoBind(), ns3::TcpSocketBase::DoForwardUp(), ns3::UdpSocketImpl::DoSendTo(), GetBoundNetDevice(), ns3::Ipv6RawSocketImpl::Ipv6JoinGroup(), ns3::UdpSocketImpl::Ipv6JoinGroup(), ns3::TcpSocketBase::PersistTimeout(), ns3::TcpSocketBase::SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), ns3::TcpSocketBase::SendEmptyPacket(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), ns3::Ipv4RawSocketImpl::SendTo(), ns3::Ipv6RawSocketImpl::SendTo(), ns3::TcpSocketBase::SetupEndpoint(), and ns3::TcpSocketBase::SetupEndpoint6().
m_connectionFailed
Callback<void, Ptr<Socket> > ns3::Socket::m_connectionFailed private
connection failed callback
Definition at line 1082 of file socket.h.
Referenced by DoDispose(), NotifyConnectionFailed(), and SetConnectCallback().
m_connectionRequest
Callback<bool, Ptr<Socket>, const Address &> ns3::Socket::m_connectionRequest private
connection request callback
Definition at line 1085 of file socket.h.
Referenced by DoDispose(), NotifyConnectionRequest(), and SetAcceptCallback().
m_connectionSucceeded
Callback<void, Ptr<Socket> > ns3::Socket::m_connectionSucceeded private
connection succeeded callback
Definition at line 1081 of file socket.h.
Referenced by DoDispose(), NotifyConnectionSucceeded(), and SetConnectCallback().
m_dataSent
Callback<void, Ptr<Socket>, uint32_t> ns3::Socket::m_dataSent private
data sent callback
Definition at line 1087 of file socket.h.
Referenced by DoDispose(), NotifyDataSent(), and SetDataSentCallback().
m_errorClose
Callback<void, Ptr<Socket> > ns3::Socket::m_errorClose private
connection closed due to errors callback
Definition at line 1084 of file socket.h.
Referenced by DoDispose(), NotifyErrorClose(), and SetCloseCallbacks().
m_ipRecvTos
bool ns3::Socket::m_ipRecvTos private
socket forwards IPv4 TOS tag to L4
Definition at line 1095 of file socket.h.
Referenced by IsIpRecvTos(), and SetIpRecvTos().
m_ipRecvTtl
bool ns3::Socket::m_ipRecvTtl private
socket forwards IPv4 TTL tag to L4
Definition at line 1096 of file socket.h.
Referenced by IsIpRecvTtl(), and SetIpRecvTtl().
m_ipTos
uint8_t ns3::Socket::m_ipTos private
the socket IPv4 TOS
Definition at line 1098 of file socket.h.
Referenced by Socket(), GetIpTos(), and SetIpTos().
m_ipTtl
uint8_t ns3::Socket::m_ipTtl private
the socket IPv4 TTL
Definition at line 1099 of file socket.h.
Referenced by Socket(), GetIpTtl(), and SetIpTtl().
m_ipv6HopLimit
uint8_t ns3::Socket::m_ipv6HopLimit private
the socket IPv6 Hop Limit
Definition at line 1108 of file socket.h.
Referenced by Socket(), GetIpv6HopLimit(), and SetIpv6HopLimit().
m_ipv6MulticastGroupAddress
Ipv6Address ns3::Socket::m_ipv6MulticastGroupAddress protected
IPv6 multicast group address.
Definition at line 1078 of file socket.h.
Referenced by ns3::Ipv6RawSocketImpl::Ipv6JoinGroup(), ns3::UdpSocketImpl::Ipv6JoinGroup(), and Ipv6LeaveGroup().
m_ipv6RecvHopLimit
bool ns3::Socket::m_ipv6RecvHopLimit private
socket forwards IPv6 Hop Limit tag to L4
Definition at line 1105 of file socket.h.
Referenced by IsIpv6RecvHopLimit(), and SetIpv6RecvHopLimit().
m_ipv6RecvTclass
bool ns3::Socket::m_ipv6RecvTclass private
socket forwards IPv6 Tclass tag to L4
Definition at line 1104 of file socket.h.
Referenced by IsIpv6RecvTclass(), and SetIpv6RecvTclass().
m_ipv6Tclass
uint8_t ns3::Socket::m_ipv6Tclass private
the socket IPv6 Tclass
Definition at line 1107 of file socket.h.
Referenced by Socket(), GetIpv6Tclass(), and SetIpv6Tclass().
m_manualIpTtl
bool ns3::Socket::m_manualIpTtl private
socket has IPv4 TTL set
Definition at line 1094 of file socket.h.
Referenced by IsManualIpTtl(), and SetIpTtl().
m_manualIpv6HopLimit
bool ns3::Socket::m_manualIpv6HopLimit private
socket has IPv6 Hop Limit set
Definition at line 1103 of file socket.h.
Referenced by IsManualIpv6HopLimit(), and SetIpv6HopLimit().
m_manualIpv6Tclass
bool ns3::Socket::m_manualIpv6Tclass private
socket has IPv6 Tclass set
Definition at line 1102 of file socket.h.
Referenced by IsManualIpv6Tclass(), and SetIpv6Tclass().
m_newConnectionCreated
Callback<void, Ptr<Socket>, const Address&> ns3::Socket::m_newConnectionCreated private
connection created callback
Definition at line 1086 of file socket.h.
Referenced by DoDispose(), NotifyNewConnectionCreated(), and SetAcceptCallback().
m_normalClose
Callback<void, Ptr<Socket> > ns3::Socket::m_normalClose private
connection closed callback
Definition at line 1083 of file socket.h.
Referenced by DoDispose(), NotifyNormalClose(), and SetCloseCallbacks().
m_priority
uint8_t ns3::Socket::m_priority private
the socket priority
Definition at line 1091 of file socket.h.
Referenced by Socket(), GetPriority(), SetIpTos(), and SetPriority().
m_receivedData
Callback<void, Ptr<Socket> > ns3::Socket::m_receivedData private
data received callback
Definition at line 1089 of file socket.h.
Referenced by DoDispose(), NotifyDataRecv(), and SetRecvCallback().
m_recvPktInfo
bool ns3::Socket::m_recvPktInfo protected
if the socket should add packet info tags to the packet forwarded to L4.
Definition at line 1077 of file socket.h.
Referenced by Socket(), IsRecvPktInfo(), and SetRecvPktInfo().
m_sendCb
Callback<void, Ptr<Socket>, uint32_t > ns3::Socket::m_sendCb private
packet sent callback
Definition at line 1088 of file socket.h.
Referenced by DoDispose(), NotifySend(), and SetSendCallback().
The documentation for this class was generated from the following files:
src/network/model/socket.h
src/network/model/socket.cc