ns-3: LteFrAreaTestCase Class Reference
LteFrAreaTestCase Class Reference
LTE Models » lte module tests | Test suites
Test frequency reuse algorithm by teleporing UEs to different parts of area and checking if the frequency is used according to the frequency pattern for different parts of area. Test fails if the muted frequencies for a given part of area are being used by UE.
#include "lte-test-frequency-reuse.h"
Public Member Functions
LteFrAreaTestCase (std::string name, std::string schedulerType)
Constructor.
virtual ~LteFrAreaTestCase ()
void DlDataRxStart (Ptr< const SpectrumValue > spectrumValue)
DL data receive start function.
void SetDlExpectedValues (double expectedPower, std::vector< bool > expectedDlRb)
Set DL expected values function.
void SetUlExpectedValues (double expectedPower, std::vector< bool > expectedDlRb)
Set UL expected values function.
void SimpleTeleportUe (uint32_t x, uint32_t y)
Simple teleport UE function.
void TeleportUe (uint32_t x, uint32_t y, double expectedPower, std::vector< bool > expectedDlRb)
Teleport UE function.
void TeleportUe2 (Ptr< Node > ueNode, uint32_t x, uint32_t y, double expectedPower, std::vector< bool > expectedDlRb)
Teleport UE 2 function.
void UlDataRxStart (Ptr< const SpectrumValue > spectrumValue)
UL data receive start function.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Protected Attributes
uint16_t m_dlBandwidth
the DL bandwidth
double m_expectedDlPower
the expected DL power
std::vector< bool > m_expectedDlRb
the expected DL per RB
double m_expectedUlPower
expected UL power
std::vector< bool > m_expectedUlRb
expected UL per RB
std::string m_schedulerType
the scheduler type
Time m_teleportTime
the telport time
Ptr< MobilityModel > m_ueMobility
the UE mobility model
uint16_t m_ulBandwidth
the UL bandwidth
bool m_usedWrongDlPower
used wrong DL power?
bool m_usedWrongDlRbg
used wrong DL RBG?
bool m_usedWrongUlPower
used wrong UL power?
bool m_usedWrongUlRbg
used wrong UL RBG?
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Detailed Description
Test frequency reuse algorithm by teleporing UEs to different parts of area and checking if the frequency is used according to the frequency pattern for different parts of area. Test fails if the muted frequencies for a given part of area are being used by UE.
Definition at line 200 of file lte-test-frequency-reuse.h.
Constructor & Destructor Documentation
LteFrAreaTestCase()
LteFrAreaTestCase::LteFrAreaTestCase (std::string name, std::string schedulerType)
Constructor.
Parameters
name the reference name
schedulerType the scheduler type
Definition at line 489 of file lte-test-frequency-reuse.cc.
References m_dlBandwidth, m_ulBandwidth, m_usedWrongDlRbg, and m_usedWrongUlRbg.
~LteFrAreaTestCase()
LteFrAreaTestCase::~LteFrAreaTestCase () virtual
Definition at line 498 of file lte-test-frequency-reuse.cc.
Member Function Documentation
DlDataRxStart()
void LteFrAreaTestCase::DlDataRxStart (Ptr< const SpectrumValue > spectrumValue)
DL data receive start function.
Parameters
spectrumValue the DL receive specturm value
Definition at line 503 of file lte-test-frequency-reuse.cc.
References ns3::SpectrumValue::ConstValuesBegin(), ns3::SpectrumValue::ConstValuesEnd(), m_dlBandwidth, m_expectedDlPower, m_expectedDlRb, m_teleportTime, m_usedWrongDlRbg, ns3::MilliSeconds(), ns3::Now(), NS_LOG_DEBUG, and NS_TEST_ASSERT_MSG_EQ_TOL.
Referenced by DlDataRxStartNofiticationArea().
DoRun()
void LteFrAreaTestCase::DoRun (void) protected virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Reimplemented in LteDistributedFfrAreaTestCase, LteEnhancedFfrAreaTestCase, LteSoftFfrAreaTestCase, LteSoftFrAreaTestCase, and LteStrictFrAreaTestCase.
Definition at line 634 of file lte-test-frequency-reuse.cc.
SetDlExpectedValues()
void LteFrAreaTestCase::SetDlExpectedValues (double expectedPower, std::vector< bool > expectedDlRb)
Set DL expected values function.
Parameters
expectedPower the expected power
expectedDlRb the expected DL pwr RB
Definition at line 618 of file lte-test-frequency-reuse.cc.
References m_expectedDlPower, m_expectedDlRb, and NS_LOG_FUNCTION.
SetUlExpectedValues()
void LteFrAreaTestCase::SetUlExpectedValues (double expectedPower, std::vector< bool > expectedDlRb)
Set UL expected values function.
Parameters
expectedPower the expected power
expectedDlRb the expected DL pwr RB
Definition at line 626 of file lte-test-frequency-reuse.cc.
References m_expectedUlPower, m_expectedUlRb, and NS_LOG_FUNCTION.
Referenced by LteStrictFrAreaTestCase::DoRun(), LteSoftFrAreaTestCase::DoRun(), LteSoftFfrAreaTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), and LteDistributedFfrAreaTestCase::DoRun().
SimpleTeleportUe()
void LteFrAreaTestCase::SimpleTeleportUe (uint32_t x, uint32_t y)
Simple teleport UE function.
Parameters
x the X position
y the Y position
Definition at line 583 of file lte-test-frequency-reuse.cc.
References m_teleportTime, m_ueMobility, ns3::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::MobilityModel::SetPosition(), and sample-rng-plot::x.
TeleportUe()
void LteFrAreaTestCase::TeleportUe (uint32_t x, uint32_t y, double expectedPower, std::vector< bool > expectedDlRb)
Teleport UE function.
Parameters
x the X position
y the Y position
expectedPower the expected power
expectedDlRb the expected DL pwr RB
Definition at line 592 of file lte-test-frequency-reuse.cc.
References m_expectedDlPower, m_expectedDlRb, m_teleportTime, m_ueMobility, ns3::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::MobilityModel::SetPosition(), and sample-rng-plot::x.
Referenced by LteStrictFrAreaTestCase::DoRun(), LteSoftFrAreaTestCase::DoRun(), LteSoftFfrAreaTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), and LteDistributedFfrAreaTestCase::DoRun().
TeleportUe2()
void LteFrAreaTestCase::TeleportUe2 (Ptr< Node > ueNode, uint32_t x, uint32_t y, double expectedPower, std::vector< bool > expectedDlRb)
Teleport UE 2 function.
Parameters
ueNode the UE node
x the X position
y the Y position
expectedPower the expected power
expectedDlRb the expected DL pwr RB
Definition at line 604 of file lte-test-frequency-reuse.cc.
References ns3::Object::GetObject(), m_expectedDlPower, m_expectedDlRb, m_teleportTime, ns3::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::MobilityModel::SetPosition(), and sample-rng-plot::x.
Referenced by LteDistributedFfrAreaTestCase::DoRun().
UlDataRxStart()
void LteFrAreaTestCase::UlDataRxStart (Ptr< const SpectrumValue > spectrumValue)
UL data receive start function.
Parameters
spectrumValue the UL receive specturm value
Definition at line 535 of file lte-test-frequency-reuse.cc.
References ns3::SpectrumValue::ConstValuesBegin(), ns3::SpectrumValue::ConstValuesEnd(), m_expectedUlPower, m_expectedUlRb, m_teleportTime, m_usedWrongUlRbg, ns3::MilliSeconds(), ns3::Now(), NS_LOG_DEBUG, and NS_TEST_ASSERT_MSG_EQ_TOL.
Referenced by UlDataRxStartNofiticationArea().
Member Data Documentation
m_dlBandwidth
uint16_t LteFrAreaTestCase::m_dlBandwidth protected
the DL bandwidth
Definition at line 266 of file lte-test-frequency-reuse.h.
Referenced by LteFrAreaTestCase(), DlDataRxStart(), LteStrictFrAreaTestCase::DoRun(), LteSoftFrAreaTestCase::DoRun(), LteSoftFfrAreaTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), and LteDistributedFfrAreaTestCase::DoRun().
m_expectedDlPower
double LteFrAreaTestCase::m_expectedDlPower protected
the expected DL power
Definition at line 272 of file lte-test-frequency-reuse.h.
Referenced by DlDataRxStart(), SetDlExpectedValues(), TeleportUe(), and TeleportUe2().
m_expectedDlRb
std::vector<bool> LteFrAreaTestCase::m_expectedDlRb protected
the expected DL per RB
Definition at line 273 of file lte-test-frequency-reuse.h.
Referenced by DlDataRxStart(), SetDlExpectedValues(), TeleportUe(), and TeleportUe2().
m_expectedUlPower
double LteFrAreaTestCase::m_expectedUlPower protected
expected UL power
Definition at line 277 of file lte-test-frequency-reuse.h.
Referenced by SetUlExpectedValues(), and UlDataRxStart().
m_expectedUlRb
std::vector<bool> LteFrAreaTestCase::m_expectedUlRb protected
expected UL per RB
Definition at line 278 of file lte-test-frequency-reuse.h.
Referenced by SetUlExpectedValues(), and UlDataRxStart().
m_schedulerType
std::string LteFrAreaTestCase::m_schedulerType protected
the scheduler type
Definition at line 264 of file lte-test-frequency-reuse.h.
Referenced by LteStrictFrAreaTestCase::DoRun(), LteSoftFrAreaTestCase::DoRun(), LteSoftFfrAreaTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), and LteDistributedFfrAreaTestCase::DoRun().
m_teleportTime
Time LteFrAreaTestCase::m_teleportTime protected
the telport time
Definition at line 269 of file lte-test-frequency-reuse.h.
Referenced by DlDataRxStart(), SimpleTeleportUe(), TeleportUe(), TeleportUe2(), and UlDataRxStart().
m_ueMobility
Ptr<MobilityModel> LteFrAreaTestCase::m_ueMobility protected
the UE mobility model
Definition at line 270 of file lte-test-frequency-reuse.h.
Referenced by LteStrictFrAreaTestCase::DoRun(), LteSoftFrAreaTestCase::DoRun(), LteSoftFfrAreaTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), SimpleTeleportUe(), and TeleportUe().
m_ulBandwidth
uint16_t LteFrAreaTestCase::m_ulBandwidth protected
the UL bandwidth
Definition at line 267 of file lte-test-frequency-reuse.h.
Referenced by LteFrAreaTestCase(), LteStrictFrAreaTestCase::DoRun(), LteSoftFrAreaTestCase::DoRun(), LteSoftFfrAreaTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), and LteDistributedFfrAreaTestCase::DoRun().
m_usedWrongDlPower
bool LteFrAreaTestCase::m_usedWrongDlPower protected
used wrong DL power?
Definition at line 275 of file lte-test-frequency-reuse.h.
m_usedWrongDlRbg
bool LteFrAreaTestCase::m_usedWrongDlRbg protected
used wrong DL RBG?
Definition at line 274 of file lte-test-frequency-reuse.h.
Referenced by LteFrAreaTestCase(), DlDataRxStart(), LteStrictFrAreaTestCase::DoRun(), LteSoftFrAreaTestCase::DoRun(), LteSoftFfrAreaTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), and LteDistributedFfrAreaTestCase::DoRun().
m_usedWrongUlPower
bool LteFrAreaTestCase::m_usedWrongUlPower protected
used wrong UL power?
Definition at line 280 of file lte-test-frequency-reuse.h.
m_usedWrongUlRbg
bool LteFrAreaTestCase::m_usedWrongUlRbg protected
used wrong UL RBG?
Definition at line 279 of file lte-test-frequency-reuse.h.
Referenced by LteFrAreaTestCase(), LteStrictFrAreaTestCase::DoRun(), LteSoftFrAreaTestCase::DoRun(), LteSoftFfrAreaTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), and UlDataRxStart().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-frequency-reuse.h
src/lte/test/lte-test-frequency-reuse.cc