ns-3: ns3::PbbMessage Class Reference
ns3::PbbMessage Class Reference abstract
A message within a PbbPacket packet.
#include "packetbb.h"
Public Types
typedef std::list< Ptr< PbbAddressBlock > >::iterator AddressBlockIterator
PbbAddressBlock iterator.
typedef std::list< Ptr< PbbAddressBlock > >::const_iterator ConstAddressBlockIterator
PbbAddressBlock const iterator.
typedef std::list< Ptr< PbbTlv > >::const_iterator ConstTlvIterator
PbbTlv const iterator.
typedef std::list< Ptr< PbbTlv > >::iterator TlvIterator
PbbTlv iterator.
Public Member Functions
PbbMessage ()
virtual ~PbbMessage ()
Ptr< PbbAddressBlock > AddressBlockBack (void)
const Ptr< PbbAddressBlock > AddressBlockBack (void) const
AddressBlockIterator AddressBlockBegin ()
ConstAddressBlockIterator AddressBlockBegin () const
void AddressBlockClear (void)
Removes all address blocks from this message.
bool AddressBlockEmpty (void) const
AddressBlockIterator AddressBlockEnd ()
ConstAddressBlockIterator AddressBlockEnd () const
AddressBlockIterator AddressBlockErase (AddressBlockIterator first, AddressBlockIterator last)
Removes all address blocks from [first, last) (includes first, not includes last).
AddressBlockIterator AddressBlockErase (AddressBlockIterator position)
Removes the address block at the specified position.
Ptr< PbbAddressBlock > AddressBlockFront (void)
const Ptr< PbbAddressBlock > AddressBlockFront (void) const
void AddressBlockPopBack (void)
Removes an address block from the back of this message.
void AddressBlockPopFront (void)
Removes an address block from the front of this message.
void AddressBlockPushBack (Ptr< PbbAddressBlock > block)
Appends an address block to the front of this message.
void AddressBlockPushFront (Ptr< PbbAddressBlock > block)
Prepends an address block to the front of this message.
int AddressBlockSize (void) const
void Deserialize (Buffer::Iterator &start)
Deserializes a message from the specified buffer.
uint8_t GetHopCount (void) const
uint8_t GetHopLimit (void) const
Address GetOriginatorAddress (void) const
uint16_t GetSequenceNumber (void) const
uint32_t GetSerializedSize (void) const
uint8_t GetType (void) const
bool HasHopCount (void) const
Tests whether or not this message has a hop count.
bool HasHopLimit (void) const
Tests whether or not this message has a hop limit.
bool HasOriginatorAddress (void) const
Tests whether or not this message has an originator address.
bool HasSequenceNumber (void) const
Tests whether or not this message has a sequence number.
bool operator!= (const PbbMessage &other) const
Inequality operator for PbbMessage.
bool operator== (const PbbMessage &other) const
Equality operator for PbbMessage.
void Print (std::ostream &os) const
Pretty-prints the contents of this message.
void Print (std::ostream &os, int level) const
Pretty-prints the contents of this message, with specified indentation.
void Serialize (Buffer::Iterator &start) const
Serializes this message into the specified buffer.
void SetHopCount (uint8_t hopcount)
Sets the current number of hops this message has traveled.
void SetHopLimit (uint8_t hoplimit)
Sets the maximum number of hops this message should travel.
void SetOriginatorAddress (Address address)
Sets the address for the node that created this packet.
void SetSequenceNumber (uint16_t seqnum)
Sets the sequence number of this message.
void SetType (uint8_t type)
Sets the type for this message.
Ptr< PbbTlv > TlvBack (void)
const Ptr< PbbTlv > TlvBack (void) const
TlvIterator TlvBegin ()
ConstTlvIterator TlvBegin () const
void TlvClear (void)
Removes all message TLVs from this block.
bool TlvEmpty (void) const
TlvIterator TlvEnd ()
ConstTlvIterator TlvEnd () const
TlvIterator TlvErase (TlvIterator first, TlvIterator last)
Removes all message TLVs from [first, last) (includes first, not includes last).
TlvIterator TlvErase (TlvIterator position)
Removes the message TLV at the specified position.
Ptr< PbbTlv > TlvFront (void)
const Ptr< PbbTlv > TlvFront (void) const
void TlvPopBack (void)
Removes a message TLV from the back of this message.
void TlvPopFront (void)
Removes a message TLV from the front of this message.
void TlvPushBack (Ptr< PbbTlv > tlv)
Appends a message TLV to the back of this message.
void TlvPushFront (Ptr< PbbTlv > tlv)
Prepends a message TLV to the front of this message.
int TlvSize (void) const
Public Member Functions inherited from ns3::SimpleRefCount< PbbMessage >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Static Public Member Functions
static Ptr< PbbMessage > DeserializeMessage (Buffer::Iterator &start)
Deserializes a message, returning the correct object depending on whether it is an IPv4 message or an IPv6 message.
Protected Member Functions
virtual Ptr< PbbAddressBlock > AddressBlockDeserialize (Buffer::Iterator &start) const =0
Deserialize an address block.
virtual Address DeserializeOriginatorAddress (Buffer::Iterator &start) const =0
Deserialize the originator address.
virtual PbbAddressLength GetAddressLength (void) const =0
Returns address length (IPV4 3 or IPV6 15)
virtual void PrintOriginatorAddress (std::ostream &os) const =0
Print the originator address.
virtual void SerializeOriginatorAddress (Buffer::Iterator &start) const =0
Serialize the originator address.
Private Attributes
std::list< Ptr< PbbAddressBlock > > m_addressBlockList
PbbAddressBlock container.
PbbAddressLength m_addrSize
the address size
bool m_hasHopCount
Hop count present.
bool m_hasHopLimit
Hop limit present.
bool m_hasOriginatorAddress
Originator address present.
bool m_hasSequenceNumber
Sequence number present.
uint8_t m_hopCount
Hop count.
uint8_t m_hopLimit
Hop limit.
Address m_originatorAddress
originator address
uint16_t m_sequenceNumber
Sequence number.
PbbTlvBlock m_tlvList
PbbTlvBlock.
uint8_t m_type
the type for this message
Detailed Description
A message within a PbbPacket packet.
There may be any number of messages in one packet packet. This is a pure virtual base class, when creating a message, you should instantiate either PbbMessageIpv4 or PbbMessageIpv6.
Definition at line 695 of file packetbb.h.
Member Typedef Documentation
AddressBlockIterator
typedef std::list< Ptr<PbbAddressBlock> >::iterator ns3::PbbMessage::AddressBlockIterator
PbbAddressBlock iterator.
Definition at line 703 of file packetbb.h.
ConstAddressBlockIterator
typedef std::list< Ptr<PbbAddressBlock> >::const_iterator ns3::PbbMessage::ConstAddressBlockIterator
PbbAddressBlock const iterator.
Definition at line 705 of file packetbb.h.
ConstTlvIterator
typedef std::list< Ptr<PbbTlv> >::const_iterator ns3::PbbMessage::ConstTlvIterator
PbbTlv const iterator.
Definition at line 701 of file packetbb.h.
TlvIterator
typedef std::list< Ptr<PbbTlv> >::iterator ns3::PbbMessage::TlvIterator
PbbTlv iterator.
Definition at line 699 of file packetbb.h.
Constructor & Destructor Documentation
PbbMessage()
ns3::PbbMessage::PbbMessage ()
Definition at line 1025 of file packetbb.cc.
References ns3::IPV4, m_addrSize, m_hasHopCount, m_hasHopLimit, m_hasOriginatorAddress, m_hasSequenceNumber, and NS_LOG_FUNCTION.
~PbbMessage()
ns3::PbbMessage::~PbbMessage () virtual
Definition at line 1036 of file packetbb.cc.
References AddressBlockClear(), and NS_LOG_FUNCTION.
Member Function Documentation
AddressBlockBack() [1/2]
Ptr< PbbAddressBlock > ns3::PbbMessage::AddressBlockBack (void)
Returns
a smart pointer to the last address block in this message.
Definition at line 1335 of file packetbb.cc.
References m_addressBlockList, and NS_LOG_FUNCTION.
AddressBlockBack() [2/2]
const Ptr< PbbAddressBlock > ns3::PbbMessage::AddressBlockBack (void) const
Returns
a const smart pointer to the last address block in this message.
Definition at line 1342 of file packetbb.cc.
References m_addressBlockList, and NS_LOG_FUNCTION.
AddressBlockBegin() [1/2]
PbbMessage::ConstAddressBlockIterator ns3::PbbMessage::AddressBlockBegin ()
Returns
an iterator to the first address block in this message.
Definition at line 1279 of file packetbb.cc.
References m_addressBlockList, and NS_LOG_FUNCTION.
Referenced by AddressBlockClear(), GetSerializedSize(), operator==(), Print(), and Serialize().
AddressBlockBegin() [2/2]
ConstAddressBlockIterator ns3::PbbMessage::AddressBlockBegin () const
Returns
a const iterator to the first address block in this message.
AddressBlockClear()
void ns3::PbbMessage::AddressBlockClear (void)
Removes all address blocks from this message.
Definition at line 1392 of file packetbb.cc.
References AddressBlockBegin(), AddressBlockEnd(), m_addressBlockList, and NS_LOG_FUNCTION.
Referenced by ~PbbMessage().
AddressBlockDeserialize()
virtual Ptr<PbbAddressBlock> ns3::PbbMessage::AddressBlockDeserialize (Buffer::Iterator & start) const protected pure virtual
Deserialize an address block.
Parameters
start the buffer iterator start
Returns
the deserialized address block
Implemented in ns3::PbbMessageIpv6, and ns3::PbbMessageIpv4.
Referenced by Deserialize().
AddressBlockEmpty()
bool ns3::PbbMessage::AddressBlockEmpty (void) const
Returns
true if there are no address blocks in this message, false otherwise.
Definition at line 1314 of file packetbb.cc.
References m_addressBlockList, and NS_LOG_FUNCTION.
AddressBlockEnd() [1/2]
PbbMessage::ConstAddressBlockIterator ns3::PbbMessage::AddressBlockEnd ()
Returns
an iterator to the past-the-end address block element in this message.
Definition at line 1293 of file packetbb.cc.
References m_addressBlockList, and NS_LOG_FUNCTION.
Referenced by AddressBlockClear(), GetSerializedSize(), operator==(), Print(), and Serialize().
AddressBlockEnd() [2/2]
ConstAddressBlockIterator ns3::PbbMessage::AddressBlockEnd () const
Returns
a const iterator to the past-the-end address block element in this message.
AddressBlockErase() [1/2]
PbbMessage::AddressBlockIterator ns3::PbbMessage::AddressBlockErase (PbbMessage::AddressBlockIterator first, PbbMessage::AddressBlockIterator last)
Removes all address blocks from [first, last) (includes first, not includes last).
Parameters
first an Iterator pointing to the first address block to erase (inclusive).
last an Iterator pointing to the element past the last address block to erase.
Returns
an iterator pointing to the next address block in the message.
Definition at line 1384 of file packetbb.cc.
References m_addressBlockList, and NS_LOG_FUNCTION.
AddressBlockErase() [2/2]
PbbMessage::AddressBlockIterator ns3::PbbMessage::AddressBlockErase (PbbMessage::AddressBlockIterator position)
Removes the address block at the specified position.
Parameters
position an Iterator pointing to the address block to erase.
Returns
an iterator pointing to the next address block in the message.
Definition at line 1377 of file packetbb.cc.
References m_addressBlockList, and NS_LOG_FUNCTION.
AddressBlockFront() [1/2]
Ptr< PbbAddressBlock > ns3::PbbMessage::AddressBlockFront (void)
Returns
a smart pointer to the first address block in this message.
Definition at line 1321 of file packetbb.cc.
References m_addressBlockList, and NS_LOG_FUNCTION.
AddressBlockFront() [2/2]
const Ptr< PbbAddressBlock > ns3::PbbMessage::AddressBlockFront (void) const
Returns
a const smart pointer to the first address block in this message.
Definition at line 1328 of file packetbb.cc.
References m_addressBlockList, and NS_LOG_FUNCTION.
AddressBlockPopBack()
void ns3::PbbMessage::AddressBlockPopBack (void)
Removes an address block from the back of this message.
Definition at line 1370 of file packetbb.cc.
References m_addressBlockList, and NS_LOG_FUNCTION.
AddressBlockPopFront()
void ns3::PbbMessage::AddressBlockPopFront (void)
Removes an address block from the front of this message.
Definition at line 1356 of file packetbb.cc.
References m_addressBlockList, and NS_LOG_FUNCTION.
AddressBlockPushBack()
void ns3::PbbMessage::AddressBlockPushBack (Ptr< PbbAddressBlock > block)
Appends an address block to the front of this message.
Parameters
block a smart pointer to the address block to append.
Definition at line 1363 of file packetbb.cc.
References m_addressBlockList, and NS_LOG_FUNCTION.
Referenced by PbbTestSuite::PbbTestSuite(), and Deserialize().
AddressBlockPushFront()
void ns3::PbbMessage::AddressBlockPushFront (Ptr< PbbAddressBlock > block)
Prepends an address block to the front of this message.
Parameters
block a smart pointer to the address block to prepend.
Definition at line 1349 of file packetbb.cc.
References m_addressBlockList, and NS_LOG_FUNCTION.
AddressBlockSize()
int ns3::PbbMessage::AddressBlockSize (void) const
Returns
the number of address blocks in this message.
Definition at line 1307 of file packetbb.cc.
References m_addressBlockList, and NS_LOG_FUNCTION.
Referenced by operator==().
Deserialize()
void ns3::PbbMessage::Deserialize (Buffer::Iterator & start)
Deserializes a message from the specified buffer.
Parameters
start a reference to the point in a buffer to begin deserializing.
Users should not need to call this. Blocks will be deserialized by their containing packet.
Definition at line 1534 of file packetbb.cc.
References AddressBlockDeserialize(), AddressBlockPushBack(), ns3::PbbTlvBlock::Deserialize(), DeserializeOriginatorAddress(), m_tlvList, MHAS_HOP_COUNT, MHAS_HOP_LIMIT, MHAS_ORIG, MHAS_SEQ_NUM, NS_LOG_FUNCTION, SetHopCount(), SetHopLimit(), SetOriginatorAddress(), SetSequenceNumber(), SetType(), and visualizer.core::start().
DeserializeMessage()
Ptr< PbbMessage > ns3::PbbMessage::DeserializeMessage (Buffer::Iterator & start) static
Deserializes a message, returning the correct object depending on whether it is an IPv4 message or an IPv6 message.
Parameters
start a reference to the point in a buffer to begin deserializing.
Returns
A pointer to the deserialized message, or 0 on error.
Users should not need to call this. Blocks will be deserialized by their containing packet.
Definition at line 1501 of file packetbb.cc.
References ns3::IPV4, ns3::IPV6, NS_LOG_FUNCTION, and visualizer.core::start().
Referenced by ns3::PbbPacket::Deserialize().
DeserializeOriginatorAddress()
virtual Address ns3::PbbMessage::DeserializeOriginatorAddress (Buffer::Iterator & start) const protected pure virtual
Deserialize the originator address.
Parameters
start the buffer iterator start
Returns
the deserialized address
Implemented in ns3::PbbMessageIpv6, and ns3::PbbMessageIpv4.
Referenced by Deserialize().
GetAddressLength()
PbbAddressLength ns3::PbbMessage::GetAddressLength (void) const protected pure virtual
Returns address length (IPV4 3 or IPV6 15)
Returns message size in bytes - 1 IPv4 = 4 - 1 = 3, IPv6 = 16 - 1 = 15
Returns
Address length (IPV4 3 or IPV6 15)
Implemented in ns3::PbbMessageIpv6, and ns3::PbbMessageIpv4.
Definition at line 1057 of file packetbb.cc.
References m_addrSize, and NS_LOG_FUNCTION.
Referenced by GetSerializedSize(), operator==(), Print(), and Serialize().
GetHopCount()
uint8_t ns3::PbbMessage::GetHopCount (void) const
Returns
the current number of hops this message has traveled.
Calling this while HasHopCount is False is undefined. Make sure you check it first. This will be checked by an assert in debug builds.
Definition at line 1118 of file packetbb.cc.
References HasHopCount(), m_hopCount, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by operator==(), Print(), and Serialize().
GetHopLimit()
uint8_t ns3::PbbMessage::GetHopLimit (void) const
Returns
the maximum number of hops this message should travel.
Calling this while HasHopLimit is False is undefined. Make sure you check it first. This will be checked by an assert in debug builds.
Definition at line 1095 of file packetbb.cc.
References HasHopLimit(), m_hopLimit, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by operator==(), Print(), and Serialize().
GetOriginatorAddress()
Address ns3::PbbMessage::GetOriginatorAddress (void) const
Returns
the address of the node that created this packet.
Calling this while HasOriginatorAddress is False is undefined. Make sure you check it first. This will be checked by an assert in debug builds.
Definition at line 1072 of file packetbb.cc.
References HasOriginatorAddress(), m_originatorAddress, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by operator==(), ns3::PbbMessageIpv4::PrintOriginatorAddress(), ns3::PbbMessageIpv6::PrintOriginatorAddress(), ns3::PbbMessageIpv4::SerializeOriginatorAddress(), and ns3::PbbMessageIpv6::SerializeOriginatorAddress().
GetSequenceNumber()
uint16_t ns3::PbbMessage::GetSequenceNumber (void) const
Returns
the sequence number of this message.
Calling this while HasSequenceNumber is False is undefined. Make sure you check it first. This will be checked by an assert in debug builds.
Definition at line 1141 of file packetbb.cc.
References HasSequenceNumber(), m_sequenceNumber, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by operator==(), Print(), and Serialize().
GetSerializedSize()
uint32_t ns3::PbbMessage::GetSerializedSize (void) const
Returns
The size (in bytes) needed to serialize this message.
Definition at line 1405 of file packetbb.cc.
References AddressBlockBegin(), AddressBlockEnd(), GetAddressLength(), ns3::PbbTlvBlock::GetSerializedSize(), HasHopCount(), HasHopLimit(), HasOriginatorAddress(), HasSequenceNumber(), m_tlvList, and NS_LOG_FUNCTION.
GetType()
uint8_t ns3::PbbMessage::GetType (void) const
Returns
the type assigned to this packet
Definition at line 1050 of file packetbb.cc.
References m_type, and NS_LOG_FUNCTION.
Referenced by operator==(), Print(), and Serialize().
HasHopCount()
bool ns3::PbbMessage::HasHopCount (void) const
Tests whether or not this message has a hop count.
Returns
true if this message has a hop limit, false otherwise.
Definition at line 1126 of file packetbb.cc.
References m_hasHopCount, and NS_LOG_FUNCTION.
Referenced by GetHopCount(), GetSerializedSize(), operator==(), Print(), and Serialize().
HasHopLimit()
bool ns3::PbbMessage::HasHopLimit (void) const
Tests whether or not this message has a hop limit.
Returns
true if this message has a hop limit, false otherwise.
If this is set, messages should not hop further than this limit.
Definition at line 1103 of file packetbb.cc.
References m_hasHopLimit, and NS_LOG_FUNCTION.
Referenced by GetHopLimit(), GetSerializedSize(), operator==(), Print(), and Serialize().
HasOriginatorAddress()
bool ns3::PbbMessage::HasOriginatorAddress (void) const
Tests whether or not this message has an originator address.
Returns
true if this message has an originator address, false otherwise.
Definition at line 1080 of file packetbb.cc.
References m_hasOriginatorAddress, and NS_LOG_FUNCTION.
Referenced by GetOriginatorAddress(), GetSerializedSize(), operator==(), Print(), and Serialize().
HasSequenceNumber()
bool ns3::PbbMessage::HasSequenceNumber (void) const
Tests whether or not this message has a sequence number.
Returns
true if this message has a sequence number, false otherwise.
Definition at line 1149 of file packetbb.cc.
References m_hasSequenceNumber, and NS_LOG_FUNCTION.
Referenced by GetSequenceNumber(), GetSerializedSize(), operator==(), Print(), and Serialize().
operator!=()
bool ns3::PbbMessage::operator!= (const PbbMessage & other) const
Inequality operator for PbbMessage.
Parameters
other PbbMessage to compare to this one
Returns
true if PbbMessages are not equal
Definition at line 1719 of file packetbb.cc.
operator==()
bool ns3::PbbMessage::operator== (const PbbMessage & other) const
Equality operator for PbbMessage.
Parameters
other PbbMessage to compare to this one
Returns
true if PbbMessages are equal
Definition at line 1631 of file packetbb.cc.
References AddressBlockBegin(), AddressBlockEnd(), AddressBlockSize(), GetAddressLength(), GetHopCount(), GetHopLimit(), GetOriginatorAddress(), GetSequenceNumber(), GetType(), HasHopCount(), HasHopLimit(), HasOriginatorAddress(), HasSequenceNumber(), and m_tlvList.
Print() [1/2]
void ns3::PbbMessage::Print (std::ostream & os) const
Pretty-prints the contents of this message.
Parameters
os a stream object to print to.
Definition at line 1576 of file packetbb.cc.
References NS_LOG_FUNCTION.
Print() [2/2]
void ns3::PbbMessage::Print (std::ostream & os, int level) const
Pretty-prints the contents of this message, with specified indentation.
Parameters
os a stream object to print to.
level level of indentation.
This probably never needs to be called by users. This is used when recursively printing sub-objects.
Definition at line 1583 of file packetbb.cc.
References AddressBlockBegin(), AddressBlockEnd(), GetAddressLength(), GetHopCount(), GetHopLimit(), GetSequenceNumber(), GetType(), HasHopCount(), HasHopLimit(), HasOriginatorAddress(), HasSequenceNumber(), m_tlvList, NS_LOG_FUNCTION, ns3::PbbTlvBlock::Print(), and PrintOriginatorAddress().
PrintOriginatorAddress()
virtual void ns3::PbbMessage::PrintOriginatorAddress (std::ostream & os) const protected pure virtual
Print the originator address.
Parameters
os the output stream
Implemented in ns3::PbbMessageIpv6, and ns3::PbbMessageIpv4.
Referenced by Print().
Serialize()
void ns3::PbbMessage::Serialize (Buffer::Iterator & start) const
Serializes this message into the specified buffer.
Parameters
start a reference to the point in a buffer to begin serializing.
Users should not need to call this. Blocks will be deserialized by their containing packet.
Definition at line 1444 of file packetbb.cc.
References AddressBlockBegin(), AddressBlockEnd(), GetAddressLength(), ns3::Buffer::Iterator::GetDistanceFrom(), GetHopCount(), GetHopLimit(), GetSequenceNumber(), GetType(), HasHopCount(), HasHopLimit(), HasOriginatorAddress(), HasSequenceNumber(), m_tlvList, MHAS_HOP_COUNT, MHAS_HOP_LIMIT, MHAS_ORIG, MHAS_SEQ_NUM, NS_LOG_FUNCTION, ns3::PbbTlvBlock::Serialize(), SerializeOriginatorAddress(), visualizer.core::start(), ns3::Buffer::Iterator::WriteHtonU16(), and ns3::Buffer::Iterator::WriteU8().
SerializeOriginatorAddress()
virtual void ns3::PbbMessage::SerializeOriginatorAddress (Buffer::Iterator & start) const protected pure virtual
Serialize the originator address.
Parameters
start the buffer iterator start
Implemented in ns3::PbbMessageIpv6, and ns3::PbbMessageIpv4.
Referenced by Serialize().
SetHopCount()
void ns3::PbbMessage::SetHopCount (uint8_t hopcount)
Sets the current number of hops this message has traveled.
Parameters
hopcount the current number of hops
Definition at line 1110 of file packetbb.cc.
References m_hasHopCount, m_hopCount, and NS_LOG_FUNCTION.
Referenced by PbbTestSuite::PbbTestSuite(), and Deserialize().
SetHopLimit()
void ns3::PbbMessage::SetHopLimit (uint8_t hoplimit)
Sets the maximum number of hops this message should travel.
Parameters
hoplimit the limit to set
Definition at line 1087 of file packetbb.cc.
References m_hasHopLimit, m_hopLimit, and NS_LOG_FUNCTION.
Referenced by PbbTestSuite::PbbTestSuite(), and Deserialize().
SetOriginatorAddress()
void ns3::PbbMessage::SetOriginatorAddress (Address address)
Sets the address for the node that created this packet.
Parameters
address the originator address.
Definition at line 1064 of file packetbb.cc.
References first::address, m_hasOriginatorAddress, m_originatorAddress, and NS_LOG_FUNCTION.
Referenced by PbbTestSuite::PbbTestSuite(), and Deserialize().
SetSequenceNumber()
void ns3::PbbMessage::SetSequenceNumber (uint16_t seqnum)
Sets the sequence number of this message.
Parameters
seqnum the sequence number to set.
Definition at line 1133 of file packetbb.cc.
References m_hasSequenceNumber, m_sequenceNumber, and NS_LOG_FUNCTION.
Referenced by PbbTestSuite::PbbTestSuite(), and Deserialize().
SetType()
void ns3::PbbMessage::SetType (uint8_t type)
Sets the type for this message.
Parameters
type the type to set.
Definition at line 1043 of file packetbb.cc.
References m_type, and NS_LOG_FUNCTION.
Referenced by PbbTestSuite::PbbTestSuite(), and Deserialize().
TlvBack() [1/2]
Ptr< PbbTlv > ns3::PbbMessage::TlvBack (void)
Returns
a smart pointer to the last message TLV in this message.
Definition at line 1214 of file packetbb.cc.
References ns3::PbbTlvBlock::Back(), m_tlvList, and NS_LOG_FUNCTION.
TlvBack() [2/2]
const Ptr< PbbTlv > ns3::PbbMessage::TlvBack (void) const
Returns
a const smart pointer to the last message TLV in this message.
Definition at line 1221 of file packetbb.cc.
References ns3::PbbTlvBlock::Back(), m_tlvList, and NS_LOG_FUNCTION.
TlvBegin() [1/2]
PbbMessage::ConstTlvIterator ns3::PbbMessage::TlvBegin ()
Returns
an iterator to the first message TLV in this message.
Definition at line 1158 of file packetbb.cc.
References ns3::PbbTlvBlock::Begin(), m_tlvList, and NS_LOG_FUNCTION.
TlvBegin() [2/2]
ConstTlvIterator ns3::PbbMessage::TlvBegin () const
Returns
a const iterator to the first message TLV in this message.
TlvClear()
void ns3::PbbMessage::TlvClear (void)
Removes all message TLVs from this block.
Definition at line 1270 of file packetbb.cc.
References ns3::PbbTlvBlock::Clear(), m_tlvList, and NS_LOG_FUNCTION.
TlvEmpty()
bool ns3::PbbMessage::TlvEmpty (void) const
Returns
true if there are no message TLVs in this message, false otherwise.
Definition at line 1193 of file packetbb.cc.
References ns3::PbbTlvBlock::Empty(), m_tlvList, and NS_LOG_FUNCTION.
TlvEnd() [1/2]
PbbMessage::ConstTlvIterator ns3::PbbMessage::TlvEnd ()
Returns
an iterator to the past-the-end message TLV element in this message.
Definition at line 1172 of file packetbb.cc.
References ns3::PbbTlvBlock::End(), m_tlvList, and NS_LOG_FUNCTION.
TlvEnd() [2/2]
ConstTlvIterator ns3::PbbMessage::TlvEnd () const
Returns
a const iterator to the past-the-end message TLV element in this message.
TlvErase() [1/2]
PbbMessage::TlvIterator ns3::PbbMessage::TlvErase (PbbMessage::TlvIterator first, PbbMessage::TlvIterator last)
Removes all message TLVs from [first, last) (includes first, not includes last).
Parameters
first an Iterator pointing to the first message TLV to erase (inclusive).
last an Iterator pointing to the element past the last message TLV to erase.
Returns
an iterator pointing to the next message TLV in the message.
Definition at line 1263 of file packetbb.cc.
References ns3::PbbTlvBlock::Erase(), m_tlvList, and NS_LOG_FUNCTION.
TlvErase() [2/2]
PbbMessage::TlvIterator ns3::PbbMessage::TlvErase (PbbMessage::TlvIterator position)
Removes the message TLV at the specified position.
Parameters
position an Iterator pointing to the message TLV to erase.
Returns
an iterator pointing to the next TLV in the block.
Definition at line 1256 of file packetbb.cc.
References ns3::PbbTlvBlock::Erase(), m_tlvList, and NS_LOG_FUNCTION.
TlvFront() [1/2]
Ptr< PbbTlv > ns3::PbbMessage::TlvFront (void)
Returns
a smart pointer to the first message TLV in this message.
Definition at line 1200 of file packetbb.cc.
References ns3::PbbTlvBlock::Front(), m_tlvList, and NS_LOG_FUNCTION.
TlvFront() [2/2]
const Ptr< PbbTlv > ns3::PbbMessage::TlvFront (void) const
Returns
a const smart pointer to the first message TLV in this message.
Definition at line 1207 of file packetbb.cc.
References ns3::PbbTlvBlock::Front(), m_tlvList, and NS_LOG_FUNCTION.
TlvPopBack()
void ns3::PbbMessage::TlvPopBack (void)
Removes a message TLV from the back of this message.
Definition at line 1249 of file packetbb.cc.
References m_tlvList, NS_LOG_FUNCTION, and ns3::PbbTlvBlock::PopBack().
TlvPopFront()
void ns3::PbbMessage::TlvPopFront (void)
Removes a message TLV from the front of this message.
Definition at line 1235 of file packetbb.cc.
References m_tlvList, NS_LOG_FUNCTION, and ns3::PbbTlvBlock::PopFront().
TlvPushBack()
void ns3::PbbMessage::TlvPushBack (Ptr< PbbTlv > tlv)
Appends a message TLV to the back of this message.
Parameters
tlv a smart pointer to the message TLV to append.
Definition at line 1242 of file packetbb.cc.
References m_tlvList, NS_LOG_FUNCTION, and ns3::PbbTlvBlock::PushBack().
Referenced by PbbTestSuite::PbbTestSuite().
TlvPushFront()
void ns3::PbbMessage::TlvPushFront (Ptr< PbbTlv > tlv)
Prepends a message TLV to the front of this message.
Parameters
tlv a smart pointer to the message TLV to prepend.
Definition at line 1228 of file packetbb.cc.
References m_tlvList, NS_LOG_FUNCTION, and ns3::PbbTlvBlock::PushFront().
TlvSize()
int ns3::PbbMessage::TlvSize (void) const
Returns
the number of message TLVs in this message.
Definition at line 1186 of file packetbb.cc.
References m_tlvList, NS_LOG_FUNCTION, and ns3::PbbTlvBlock::Size().
Member Data Documentation
m_addressBlockList
std::list< Ptr<PbbAddressBlock> > ns3::PbbMessage::m_addressBlockList private
PbbAddressBlock container.
Definition at line 1104 of file packetbb.h.
Referenced by AddressBlockBack(), AddressBlockBegin(), AddressBlockClear(), AddressBlockEmpty(), AddressBlockEnd(), AddressBlockErase(), AddressBlockFront(), AddressBlockPopBack(), AddressBlockPopFront(), AddressBlockPushBack(), AddressBlockPushFront(), and AddressBlockSize().
m_addrSize
PbbAddressLength ns3::PbbMessage::m_addrSize private
the address size
Definition at line 1107 of file packetbb.h.
Referenced by PbbMessage(), and GetAddressLength().
m_hasHopCount
bool ns3::PbbMessage::m_hasHopCount private
Hop count present.
Definition at line 1115 of file packetbb.h.
Referenced by PbbMessage(), HasHopCount(), and SetHopCount().
m_hasHopLimit
bool ns3::PbbMessage::m_hasHopLimit private
Hop limit present.
Definition at line 1112 of file packetbb.h.
Referenced by PbbMessage(), HasHopLimit(), and SetHopLimit().
m_hasOriginatorAddress
bool ns3::PbbMessage::m_hasOriginatorAddress private
Originator address present.
Definition at line 1109 of file packetbb.h.
Referenced by PbbMessage(), HasOriginatorAddress(), and SetOriginatorAddress().
m_hasSequenceNumber
bool ns3::PbbMessage::m_hasSequenceNumber private
Sequence number present.
Definition at line 1118 of file packetbb.h.
Referenced by PbbMessage(), HasSequenceNumber(), and SetSequenceNumber().
m_hopCount
uint8_t ns3::PbbMessage::m_hopCount private
Hop count.
Definition at line 1116 of file packetbb.h.
Referenced by GetHopCount(), and SetHopCount().
m_hopLimit
uint8_t ns3::PbbMessage::m_hopLimit private
Hop limit.
Definition at line 1113 of file packetbb.h.
Referenced by GetHopLimit(), and SetHopLimit().
m_originatorAddress
Address ns3::PbbMessage::m_originatorAddress private
originator address
Definition at line 1110 of file packetbb.h.
Referenced by GetOriginatorAddress(), and SetOriginatorAddress().
m_sequenceNumber
uint16_t ns3::PbbMessage::m_sequenceNumber private
Sequence number.
Definition at line 1119 of file packetbb.h.
Referenced by GetSequenceNumber(), and SetSequenceNumber().
m_tlvList
PbbTlvBlock ns3::PbbMessage::m_tlvList private
PbbTlvBlock.
Definition at line 1103 of file packetbb.h.
Referenced by Deserialize(), GetSerializedSize(), operator==(), Print(), Serialize(), TlvBack(), TlvBegin(), TlvClear(), TlvEmpty(), TlvEnd(), TlvErase(), TlvFront(), TlvPopBack(), TlvPopFront(), TlvPushBack(), TlvPushFront(), and TlvSize().
m_type
uint8_t ns3::PbbMessage::m_type private
the type for this message
Definition at line 1106 of file packetbb.h.
Referenced by GetType(), and SetType().
The documentation for this class was generated from the following files:
src/network/utils/packetbb.h
src/network/utils/packetbb.cc