ns-3: ns3::SimpleUeComponentCarrierManager Class Reference
ns3::SimpleUeComponentCarrierManager Class Reference
Component carrier manager implementation which simply does nothing.
#include "simple-ue-component-carrier-manager.h"
Public Member Functions
SimpleUeComponentCarrierManager ()
Creates a No-op CCS algorithm instance.
virtual ~SimpleUeComponentCarrierManager ()
virtual LteMacSapProvider * GetLteMacSapProvider ()
Returns the MAC sap provider interface that if forwarding calls to the instance of the LteUeComponentCarrierManager.
Public Member Functions inherited from ns3::LteUeComponentCarrierManager
LteUeComponentCarrierManager ()
virtual ~LteUeComponentCarrierManager ()
virtual LteUeCcmRrcSapProvider * GetLteCcmRrcSapProvider ()
Exports the "provider" part of the ComponentCarrier Management SAP interface.
bool SetComponentCarrierMacSapProviders (uint8_t componentCarrierId, LteMacSapProvider *sap)
Sets a pointer to SAP interface of MAC instance for the specified carrier.
virtual void SetLteCcmRrcSapUser (LteUeCcmRrcSapUser *s)
Set the "user" part of the ComponentCarrier Management SAP interface that this UE component carrier manager will interact with.
void SetNumberOfComponentCarriers (uint8_t noOfComponentCarriers)
Sets number of component carriers that are supported by this UE.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::LteUeComponentCarrierManager
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual std::vector< LteUeCcmRrcSapProvider::LcsConfig > DoAddLc (uint8_t lcId, LteUeCmacSapProvider::LogicalChannelConfig lcConfig, LteMacSapUser *msu)
Add LC function.
virtual LteMacSapUser * DoConfigureSignalBearer (uint8_t lcId, LteUeCmacSapProvider::LogicalChannelConfig lcConfig, LteMacSapUser *msu)
Configure signal bearer function.
virtual void DoDispose ()
Destructor implementation.
virtual void DoInitialize ()
Initialize() implementation.
void DoNotifyHarqDeliveryFailure ()
Notify HARQ deliver failure.
void DoNotifyTxOpportunity (LteMacSapUser::TxOpportunityParameters txOpParams)
Notify TX opportunity function.
void DoReceivePdu (LteMacSapUser::ReceivePduParameters rxPduParams)
Receive PDU function.
std::vector< uint16_t > DoRemoveLc (uint8_t lcid)
Remove LC function.
virtual void DoReportBufferStatus (LteMacSapProvider::ReportBufferStatusParameters params)
Report buffer status function.
void DoReportUeMeas (uint16_t rnti, LteRrcSap::MeasResults measResults)
Report Ue Measure function.
void DoReset ()
Reset LC map.
void DoTransmitPdu (LteMacSapProvider::TransmitPduParameters params)
Transmit PDU function.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes
LteMacSapProvider * m_ccmMacSapProvider
Receive API calls from the UE RLC instance.
LteMacSapUser * m_ccmMacSapUser
Interface to the UE RLC instance.
Protected Attributes inherited from ns3::LteUeComponentCarrierManager
LteUeCcmRrcSapProvider * m_ccmRrcSapProvider
Receive API calls from the UE RRC instance.
LteUeCcmRrcSapUser * m_ccmRrcSapUser
Interface to the UE RRC instance.
std::map< uint8_t, std::map< uint8_t, LteMacSapProvider * > > m_componentCarrierLcMap
Flow configuration per flow Id of this UE.
std::map< uint8_t, LteMacSapUser * > m_lcAttached
Map of pointers to SAP interfaces of the RLC instance of the flows of this UE.
std::map< uint8_t, LteMacSapProvider * > m_macSapProvidersMap
Map of pointers to SAP to interfaces of the MAC instance if the flows of this UE.
uint16_t m_noOfComponentCarriers
// The number of component carriers that this UE can support.
Friends
class MemberLteUeCcmRrcSapProvider< SimpleUeComponentCarrierManager >
let the forwarder class access the protected and private members
class SimpleUeCcmMacSapProvider
allow SimpleUeCcmMacSapProvider class friend access
class SimpleUeCcmMacSapUser
allow SimpleUeCcmMacSapUser class friend access
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Component carrier manager implementation which simply does nothing.
Selecting this component carrier selection algorithm is equivalent to disabling automatic triggering of component carrier selection. This is the default choice.
Definition at line 40 of file simple-ue-component-carrier-manager.h.
Constructor & Destructor Documentation
SimpleUeComponentCarrierManager()
ns3::SimpleUeComponentCarrierManager::SimpleUeComponentCarrierManager ()
Creates a No-op CCS algorithm instance.
Definition at line 131 of file simple-ue-component-carrier-manager.cc.
References m_ccmMacSapProvider, m_ccmMacSapUser, ns3::LteUeComponentCarrierManager::m_ccmRrcSapProvider, MemberLteUeCcmRrcSapProvider< SimpleUeComponentCarrierManager >, NS_LOG_FUNCTION, SimpleUeCcmMacSapProvider, and SimpleUeCcmMacSapUser.
~SimpleUeComponentCarrierManager()
ns3::SimpleUeComponentCarrierManager::~SimpleUeComponentCarrierManager () virtual
Definition at line 140 of file simple-ue-component-carrier-manager.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoAddLc()
std::vector< LteUeCcmRrcSapProvider::LcsConfig > ns3::SimpleUeComponentCarrierManager::DoAddLc (uint8_t lcId, LteUeCmacSapProvider::LogicalChannelConfig lcConfig, LteMacSapUser * msu) protected virtual
Add LC function.
Parameters
lcId the LCID
lcConfig the logical channel config
msu the MSU
Returns
updated LC config list
Definition at line 305 of file simple-ue-component-carrier-manager.cc.
References ns3::LteUeCcmRrcSapProvider::LcsConfig::componentCarrierId, ns3::LteUeCcmRrcSapProvider::LcsConfig::lcConfig, m_ccmMacSapUser, ns3::LteUeComponentCarrierManager::m_componentCarrierLcMap, ns3::LteUeComponentCarrierManager::m_lcAttached, ns3::LteUeComponentCarrierManager::m_macSapProvidersMap, ns3::LteUeComponentCarrierManager::m_noOfComponentCarriers, ns3::LteUeCcmRrcSapProvider::LcsConfig::msu, NS_ABORT_MSG_IF, and NS_LOG_FUNCTION.
DoConfigureSignalBearer()
LteMacSapUser * ns3::SimpleUeComponentCarrierManager::DoConfigureSignalBearer (uint8_t lcId, LteUeCmacSapProvider::LogicalChannelConfig lcConfig, LteMacSapUser * msu) protected virtual
Configure signal bearer function.
Parameters
lcId the LCID
lcConfig the logical channel config
msu the MSU
Returns
LteMacSapUser *
Definition at line 341 of file simple-ue-component-carrier-manager.cc.
References m_ccmMacSapUser, ns3::LteUeComponentCarrierManager::m_componentCarrierLcMap, ns3::LteUeComponentCarrierManager::m_lcAttached, ns3::LteUeComponentCarrierManager::m_macSapProvidersMap, ns3::LteUeComponentCarrierManager::m_noOfComponentCarriers, NS_ABORT_MSG_IF, and NS_LOG_FUNCTION.
DoDispose()
void ns3::SimpleUeComponentCarrierManager::DoDispose () protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::LteUeComponentCarrierManager.
Definition at line 147 of file simple-ue-component-carrier-manager.cc.
References m_ccmMacSapProvider, m_ccmMacSapUser, ns3::LteUeComponentCarrierManager::m_ccmRrcSapProvider, and NS_LOG_FUNCTION.
DoInitialize()
void ns3::SimpleUeComponentCarrierManager::DoInitialize () protected virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 176 of file simple-ue-component-carrier-manager.cc.
References ns3::Object::DoInitialize(), and NS_LOG_FUNCTION.
DoNotifyHarqDeliveryFailure()
void ns3::SimpleUeComponentCarrierManager::DoNotifyHarqDeliveryFailure () protected
Notify HARQ deliver failure.
Definition at line 224 of file simple-ue-component-carrier-manager.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::SimpleUeCcmMacSapUser::NotifyHarqDeliveryFailure().
DoNotifyTxOpportunity()
void ns3::SimpleUeComponentCarrierManager::DoNotifyTxOpportunity (LteMacSapUser::TxOpportunityParameters txOpParams) protected
Notify TX opportunity function.
Parameters
txOpParams the LteMacSapUser::TxOpportunityParameters
Definition at line 231 of file simple-ue-component-carrier-manager.cc.
References ns3::LteMacSapUser::TxOpportunityParameters::bytes, ns3::LteMacSapUser::TxOpportunityParameters::componentCarrierId, ns3::LteMacSapUser::TxOpportunityParameters::layer, ns3::LteMacSapUser::TxOpportunityParameters::lcid, ns3::LteUeComponentCarrierManager::m_lcAttached, NS_ABORT_MSG_IF, NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::LteMacSapUser::TxOpportunityParameters::rnti.
Referenced by ns3::SimpleUeCcmMacSapUser::NotifyTxOpportunity().
DoReceivePdu()
void ns3::SimpleUeComponentCarrierManager::DoReceivePdu (LteMacSapUser::ReceivePduParameters rxPduParams) protected
Receive PDU function.
Parameters
rxPduParams the LteMacSapUser::ReceivePduParameters
Definition at line 245 of file simple-ue-component-carrier-manager.cc.
References ns3::LteMacSapUser::ReceivePduParameters::lcid, ns3::LteUeComponentCarrierManager::m_lcAttached, NS_ABORT_MSG_IF, and NS_LOG_FUNCTION.
Referenced by ns3::SimpleUeCcmMacSapUser::ReceivePdu().
DoRemoveLc()
std::vector< uint16_t > ns3::SimpleUeComponentCarrierManager::DoRemoveLc (uint8_t lcid) protected
Remove LC function.
Parameters
lcid the LCID
Returns
updated LC list
Definition at line 260 of file simple-ue-component-carrier-manager.cc.
References ns3::LteUeComponentCarrierManager::m_componentCarrierLcMap, ns3::LteUeComponentCarrierManager::m_lcAttached, NS_ABORT_MSG_IF, and NS_LOG_FUNCTION.
DoReportBufferStatus()
void ns3::SimpleUeComponentCarrierManager::DoReportBufferStatus (LteMacSapProvider::ReportBufferStatusParameters params) protected virtual
Report buffer status function.
Parameters
params LteMacSapProvider::ReportBufferStatusParameters
Definition at line 202 of file simple-ue-component-carrier-manager.cc.
References ns3::LteUeComponentCarrierManager::m_componentCarrierLcMap, ns3::LteUeComponentCarrierManager::m_macSapProvidersMap, NS_ABORT_MSG_IF, NS_LOG_DEBUG, NS_LOG_FUNCTION, and aloha::params.
Referenced by ns3::SimpleUeCcmMacSapProvider::ReportBufferStatus().
DoReportUeMeas()
void ns3::SimpleUeComponentCarrierManager::DoReportUeMeas (uint16_t rnti, LteRrcSap::MeasResults measResults) protected
Report Ue Measure function.
Parameters
rnti the RNTI
measResults the measure results
Definition at line 184 of file simple-ue-component-carrier-manager.cc.
References ns3::LteRrcSap::MeasResults::measId, and NS_LOG_FUNCTION.
DoReset()
void ns3::SimpleUeComponentCarrierManager::DoReset () protected
Reset LC map.
Definition at line 284 of file simple-ue-component-carrier-manager.cc.
References ns3::LteUeComponentCarrierManager::m_lcAttached, and NS_LOG_FUNCTION.
DoTransmitPdu()
void ns3::SimpleUeComponentCarrierManager::DoTransmitPdu (LteMacSapProvider::TransmitPduParameters params) protected
Transmit PDU function.
Parameters
params LteMacSapProvider::TransmitPduParameters
Definition at line 192 of file simple-ue-component-carrier-manager.cc.
References ns3::LteUeComponentCarrierManager::m_macSapProvidersMap, NS_ABORT_MSG_IF, NS_LOG_FUNCTION, and aloha::params.
Referenced by ns3::SimpleUeCcmMacSapProvider::TransmitPdu().
GetLteMacSapProvider()
LteMacSapProvider * ns3::SimpleUeComponentCarrierManager::GetLteMacSapProvider () virtual
Returns the MAC sap provider interface that if forwarding calls to the instance of the LteUeComponentCarrierManager.
Returns
the reference to the "provider" part of the interface
Implements ns3::LteUeComponentCarrierManager.
Definition at line 168 of file simple-ue-component-carrier-manager.cc.
References m_ccmMacSapProvider, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::SimpleUeComponentCarrierManager::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 157 of file simple-ue-component-carrier-manager.cc.
References ns3::TypeId::SetParent().
Friends And Related Function Documentation
MemberLteUeCcmRrcSapProvider< SimpleUeComponentCarrierManager >
friend class MemberLteUeCcmRrcSapProvider< SimpleUeComponentCarrierManager > friend
let the forwarder class access the protected and private members
Definition at line 55 of file simple-ue-component-carrier-manager.h.
Referenced by SimpleUeComponentCarrierManager().
SimpleUeCcmMacSapProvider
friend class SimpleUeCcmMacSapProvider friend
allow SimpleUeCcmMacSapProvider class friend access
Definition at line 64 of file simple-ue-component-carrier-manager.h.
Referenced by SimpleUeComponentCarrierManager().
SimpleUeCcmMacSapUser
friend class SimpleUeCcmMacSapUser friend
allow SimpleUeCcmMacSapUser class friend access
Definition at line 66 of file simple-ue-component-carrier-manager.h.
Referenced by SimpleUeComponentCarrierManager().
Member Data Documentation
m_ccmMacSapProvider
LteMacSapProvider* ns3::SimpleUeComponentCarrierManager::m_ccmMacSapProvider protected
Receive API calls from the UE RLC instance.
Definition at line 138 of file simple-ue-component-carrier-manager.h.
Referenced by SimpleUeComponentCarrierManager(), DoDispose(), and GetLteMacSapProvider().
m_ccmMacSapUser
LteMacSapUser* ns3::SimpleUeComponentCarrierManager::m_ccmMacSapUser protected
Interface to the UE RLC instance.
Definition at line 137 of file simple-ue-component-carrier-manager.h.
Referenced by SimpleUeComponentCarrierManager(), DoAddLc(), DoConfigureSignalBearer(), and DoDispose().
The documentation for this class was generated from the following files:
src/lte/model/simple-ue-component-carrier-manager.h
src/lte/model/simple-ue-component-carrier-manager.cc