ns-3: ns3::aodv::LoopbackTestCase Class Reference
ns3::aodv::LoopbackTestCase Class Reference
AODV Routing
AODV loopback UDP echo test case.
Public Member Functions
LoopbackTestCase ()
void DoRun ()
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void EchoData (Ptr< Socket > socket)
Echo data function.
void ReceivePkt (Ptr< Socket > socket)
Receive packet function.
void SendData (Ptr< Socket > socket)
Send data function.
Private Attributes
uint32_t m_count
number of packet received;
uint16_t m_echoReplyPort
echo reply port;
uint16_t m_echoSendPort
echo send port;
Ptr< Socket > m_echoSocket
echo socket;
Ptr< Socket > m_rxSocket
receive socket;
Ptr< Socket > m_txSocket
transmit socket;
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
AODV loopback UDP echo test case.
Definition at line 52 of file loopback.cc.
Constructor & Destructor Documentation
LoopbackTestCase()
ns3::aodv::LoopbackTestCase::LoopbackTestCase ()
Definition at line 82 of file loopback.cc.
References m_echoReplyPort, and m_echoSendPort.
Member Function Documentation
DoRun()
void ns3::aodv::LoopbackTestCase::DoRun () virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 123 of file loopback.cc.
References first::address, ns3::Socket::Bind(), ns3::Socket::Close(), ns3::YansWifiChannelHelper::Create(), ns3::YansWifiChannelHelper::Default(), ns3::YansWifiPhyHelper::Default(), ns3::Simulator::Destroy(), first::devices, EchoData(), ns3::Node::GetId(), ns3::Ipv4Address::GetLoopback(), ns3::Socket::GetNode(), ns3::InternetStackHelper::Install(), first::interfaces, m_count, m_echoReplyPort, m_echoSendPort, m_echoSocket, m_rxSocket, m_txSocket, ns3::MakeCallback(), first::nodes, NS_TEST_ASSERT_MSG_EQ, ReceivePkt(), ns3::Simulator::Run(), ns3::Simulator::ScheduleWithContext(), ns3::Seconds(), SendData(), ns3::YansWifiPhyHelper::SetChannel(), ns3::MobilityModel::SetPosition(), ns3::Socket::SetRecvCallback(), ns3::InternetStackHelper::SetRoutingHelper(), ns3::WifiMacHelper::SetType(), ns3::Simulator::Stop(), and third::wifi.
EchoData()
void ns3::aodv::LoopbackTestCase::EchoData (Ptr< Socket > socket) private
Echo data function.
Parameters
socket The socket to echo data
Definition at line 98 of file loopback.cc.
References ns3::InetSocketAddress::ConvertFrom(), ns3::InetSocketAddress::GetIpv4(), m_echoReplyPort, max, ns3::Socket::RecvFrom(), ns3::Packet::RemoveAllByteTags(), ns3::Packet::RemoveAllPacketTags(), and ns3::Socket::SendTo().
Referenced by DoRun().
ReceivePkt()
void ns3::aodv::LoopbackTestCase::ReceivePkt (Ptr< Socket > socket) private
Receive packet function.
Parameters
socket The socket to receive data
Definition at line 90 of file loopback.cc.
References m_count, max, and ns3::Socket::Recv().
Referenced by DoRun().
SendData()
void ns3::aodv::LoopbackTestCase::SendData (Ptr< Socket > socket) private
Send data function.
Parameters
socket The socket to send data
Definition at line 113 of file loopback.cc.
References ns3::Node::GetId(), ns3::Ipv4Address::GetLoopback(), ns3::Socket::GetNode(), m_echoSendPort, ns3::Simulator::ScheduleWithContext(), ns3::Seconds(), and ns3::Socket::SendTo().
Referenced by DoRun().
Member Data Documentation
m_count
uint32_t ns3::aodv::LoopbackTestCase::m_count private
number of packet received;
Definition at line 54 of file loopback.cc.
Referenced by DoRun(), and ReceivePkt().
m_echoReplyPort
uint16_t ns3::aodv::LoopbackTestCase::m_echoReplyPort private
echo reply port;
Definition at line 59 of file loopback.cc.
Referenced by LoopbackTestCase(), DoRun(), and EchoData().
m_echoSendPort
uint16_t ns3::aodv::LoopbackTestCase::m_echoSendPort private
echo send port;
Definition at line 58 of file loopback.cc.
Referenced by LoopbackTestCase(), DoRun(), and SendData().
m_echoSocket
Ptr<Socket> ns3::aodv::LoopbackTestCase::m_echoSocket private
echo socket;
Definition at line 56 of file loopback.cc.
Referenced by DoRun().
m_rxSocket
Ptr<Socket> ns3::aodv::LoopbackTestCase::m_rxSocket private
receive socket;
Definition at line 57 of file loopback.cc.
Referenced by DoRun().
m_txSocket
Ptr<Socket> ns3::aodv::LoopbackTestCase::m_txSocket private
transmit socket;
Definition at line 55 of file loopback.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/aodv/test/loopback.cc