ns-3: TcpPktsAckedOpenTest Class Reference
TcpPktsAckedOpenTest Class Reference
Internet » internet module tests | Test suites
Check the number of times that PktsAcked is called.
Public Member Functions
TcpPktsAckedOpenTest (const std::string &desc)
Constructor.
void PktsAckedCalled (uint32_t segmentsAcked)
Called when an ACK is received.
Public Member Functions inherited from ns3::TcpGeneralTest
TcpGeneralTest (const std::string &desc)
TcpGeneralTest constructor.
~TcpGeneralTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Member Functions
virtual void ConfigureEnvironment ()
Change the configuration of the environment.
virtual Ptr< TcpSocketMsgBase > CreateSenderSocket (Ptr< Node > node)
Create and install the socket to install on the sender.
void FinalChecks ()
Performs the (eventual) final checks through test asserts.
virtual void Rx (const Ptr< const Packet > p, const TcpHeader &h, SocketWho who)
Packet received from IP layer.
Protected Member Functions inherited from ns3::TcpGeneralTest
virtual void AfterRTOExpired (const Ptr< const TcpSocketState > tcb, SocketWho who)
Rto has expired.
virtual void BeforeRTOExpired (const Ptr< const TcpSocketState > tcb, SocketWho who)
Rto has expired.
virtual void BytesInFlightTrace (uint32_t oldValue, uint32_t newValue)
Bytes in flight changes.
virtual void ConfigureProperties (void)
Change the configuration of the socket properties.
virtual void CongStateTrace (const TcpSocketState::TcpCongState_t oldValue, const TcpSocketState::TcpCongState_t newValue)
State on Ack state machine changes.
virtual Ptr< SimpleChannel > CreateChannel ()
Create and return the channel installed between the two socket.
virtual Ptr< ErrorModel > CreateReceiverErrorModel ()
Create and return the error model to install in the receiver node.
virtual Ptr< TcpSocketMsgBase > CreateReceiverSocket (Ptr< Node > node)
Create and install the socket to install on the receiver.
virtual Ptr< ErrorModel > CreateSenderErrorModel ()
Create and return the error model to install in the sender node.
virtual Ptr< TcpSocketMsgBase > CreateSocket (Ptr< Node > node, TypeId socketType, TypeId congControl)
Create a socket.
virtual Ptr< TcpSocketMsgBase > CreateSocket (Ptr< Node > node, TypeId socketType, TypeId congControl, TypeId recoveryAlgorithm)
Create a socket.
virtual void CWndInflTrace (uint32_t oldValue, uint32_t newValue)
Tracks the inflated congestion window changes.
virtual void CWndTrace (uint32_t oldValue, uint32_t newValue)
Tracks the congestion window changes.
virtual void DataSent (uint32_t size, SocketWho who)
Notifying application for sent data.
void DoConnect ()
Scheduled at 0.0, SENDER starts the connection to RECEIVER.
virtual void DoRun (void)
Execute the tcp test.
virtual void DoTeardown (void)
Teardown the TCP test.
virtual void ErrorClose (SocketWho who)
Socket closed with an error.
Time GetClockGranularity (SocketWho who)
Get the clock granularity attribute.
Time GetConnTimeout (SocketWho who)
Get the retransmission time for the SYN segments.
uint32_t GetDelAckCount (SocketWho who)
Get the number of delayed ack (if present)
Time GetDelAckTimeout (SocketWho who)
Get the timeout of delayed ack (if present)
uint32_t GetDupAckCount (SocketWho who)
Get the number of dupack received.
SequenceNumber32 GetHighestTxMark (SocketWho who)
Get the highest tx mark of the node specified.
uint32_t GetInitialCwnd (SocketWho who)
Get the initial congestion window.
uint32_t GetInitialSsThresh (SocketWho who)
Get the initial slow start threshold.
Time GetMinRto (SocketWho who)
Get the minimum RTO attribute.
uint32_t GetMtu () const
Get the MTU of the environment.
EventId GetPersistentEvent (SocketWho who)
Get the persistent event of the selected socket.
Time GetPersistentTimeout (SocketWho who)
Get the persistent timeout of the selected socket.
uint32_t GetPktCount () const
Get the number of application packets.
Time GetPktInterval () const
Get the interval to wait for each packet sent down from application to TCP.
uint32_t GetPktSize () const
Get the application packet size.
Time GetPropagationDelay () const
Get the channel Propagation Delay.
Ptr< TcpSocketMsgBase > GetReceiverSocket ()
Get the pointer to a previously created receiver socket.
uint32_t GetReTxThreshold (SocketWho who)
Get the retransmission threshold.
Time GetRto (SocketWho who)
Get the retransmission time.
Ptr< RttEstimator > GetRttEstimator (SocketWho who)
Get the Rtt estimator of the socket.
uint32_t GetRWnd (SocketWho who)
Get the rWnd of the selected socket.
Ptr< TcpRxBuffer > GetRxBuffer (SocketWho who)
Get the Rx buffer from selected socket.
uint32_t GetSegSize (SocketWho who)
Get the segment size of the node specified.
Ptr< TcpSocketMsgBase > GetSenderSocket ()
Get the pointer to a previously created sender socket.
Time GetStartTime () const
Get the data start time.
Ptr< TcpSocketState > GetTcb (SocketWho who)
Get the TCB from selected socket.
TcpSocket::TcpStates_t GetTcpState (SocketWho who)
Get the state of the TCP state machine.
Ptr< TcpTxBuffer > GetTxBuffer (SocketWho who)
Get the Tx buffer from selected socket.
virtual void HighestTxSeqTrace (SequenceNumber32 oldValue, SequenceNumber32 newValue)
Highest tx seq changes.
virtual void NextTxSeqTrace (SequenceNumber32 oldValue, SequenceNumber32 newValue)
Next tx seq changes.
virtual void NormalClose (SocketWho who)
Socket closed normally.
virtual void PhyDrop (SocketWho who)
Link drop.
virtual void ProcessedAck (const Ptr< const TcpSocketState > tcb, const TcpHeader &h, SocketWho who)
Processed ack.
virtual void QueueDrop (SocketWho who)
Drop on the queue.
virtual void RateSampleUpdatedTrace (const TcpRateLinux::TcpRateSample &sample)
Track the rate sample value of TcpRateLinux.
virtual void RateUpdatedTrace (const TcpRateLinux::TcpRateConnection &rate)
Track the rate value of TcpRateLinux.
virtual void RcvAck (const Ptr< const TcpSocketState > tcb, const TcpHeader &h, SocketWho who)
Received ack.
virtual void ReceivePacket (Ptr< Socket > socket)
Packet received.
virtual void RtoTrace (Time oldValue, Time newValue)
RTO changes.
virtual void RttTrace (Time oldTime, Time newTime)
Rtt changes.
void SendPacket (Ptr< Socket > socket, uint32_t pktSize, uint32_t pktCount, Time pktInterval)
Send packets to other endpoint.
void SetAppPktCount (uint32_t pktCount)
Set app packet count.
void SetAppPktInterval (Time pktInterval)
Interval between app-generated packet.
void SetAppPktSize (uint32_t pktSize)
Set app packet size.
void SetCongestionControl (TypeId congControl)
Congestion control of the sender socket.
void SetInitialCwnd (SocketWho who, uint32_t initialCwnd)
Forcefully set the initial cwnd.
void SetInitialSsThresh (SocketWho who, uint32_t initialSsThresh)
Forcefully set the initial ssth.
void SetMTU (uint32_t mtu)
MTU of the bottleneck link.
void SetPropagationDelay (Time propDelay)
Propagation delay of the bottleneck link.
void SetRcvBufSize (SocketWho who, uint32_t size)
Forcefully set a defined size for rx buffer.
void SetRecoveryAlgorithm (TypeId reccovery)
recovery algorithm of the sender socket
void SetSegmentSize (SocketWho who, uint32_t segmentSize)
Forcefully set the segment size.
void SetTransmitStart (Time startTime)
Set the initial time at which the application sends the first data packet.
void SetUseEcn (SocketWho who, TcpSocketState::UseEcn_t useEcn)
Forcefully set the ecn use on.
virtual void SsThreshTrace (uint32_t oldValue, uint32_t newValue)
Slow start threshold changes.
virtual void Tx (const Ptr< const Packet > p, const TcpHeader &h, SocketWho who)
Packet transmitted down to IP layer.
virtual void UpdatedRttHistory (const SequenceNumber32 &seq, uint32_t sz, bool isRetransmission, SocketWho who)
Updated the Rtt history.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Private Attributes
Ptr< DummyCongControl > m_congCtl
Dummy congestion control.
uint32_t m_segmentsAcked
Contains the number of times PktsAcked is called.
uint32_t m_segmentsReceived
Contains the ack number received.
Additional Inherited Members
Public Types inherited from ns3::TcpGeneralTest
enum SocketWho { SENDER, RECEIVER }
Used as parameter of methods, specifies on what node the caller is interested (e.g.
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Attributes inherited from ns3::TcpGeneralTest
TypeId m_congControlTypeId
Congestion control.
TypeId m_recoveryTypeId
Recovery.
Detailed Description
Check the number of times that PktsAcked is called.
Set a custom congestion control class, which calls PktsAckedCalled each time the TCP implementation calls PktsAcked.
The checks are performed in FinalChecks: the number of bytes acked divided by segment size should be the same as the number of segments passed through PktsAcked in the congestion control.
See also
DummyCongControl
FinalChecks
Definition at line 47 of file tcp-pkts-acked-test.cc.
Constructor & Destructor Documentation
TcpPktsAckedOpenTest()
TcpPktsAckedOpenTest::TcpPktsAckedOpenTest (const std::string & desc)
Constructor.
Parameters
desc Test description.
Definition at line 127 of file tcp-pkts-acked-test.cc.
Member Function Documentation
ConfigureEnvironment()
void TcpPktsAckedOpenTest::ConfigureEnvironment () protected virtual
Change the configuration of the environment.
Reimplemented from ns3::TcpGeneralTest.
Definition at line 135 of file tcp-pkts-acked-test.cc.
References ns3::TcpGeneralTest::SetAppPktCount(), and ns3::TcpGeneralTest::SetMTU().
CreateSenderSocket()
Ptr< TcpSocketMsgBase > TcpPktsAckedOpenTest::CreateSenderSocket (Ptr< Node > node) protected virtual
Create and install the socket to install on the sender.
Parameters
node sender node pointer
Returns
the socket to be installed in the sender
Reimplemented from ns3::TcpGeneralTest.
Definition at line 143 of file tcp-pkts-acked-test.cc.
References m_congCtl, ns3::MakeCallback(), PktsAckedCalled(), DummyCongControl::SetCallback(), and ns3::TcpSocketBase::SetCongestionControlAlgorithm().
FinalChecks()
void TcpPktsAckedOpenTest::FinalChecks () protected virtual
Performs the (eventual) final checks through test asserts.
Reimplemented from ns3::TcpGeneralTest.
Definition at line 169 of file tcp-pkts-acked-test.cc.
References ns3::TcpGeneralTest::GetSegSize(), m_segmentsAcked, m_segmentsReceived, NS_TEST_ASSERT_MSG_EQ, and ns3::TcpGeneralTest::SENDER.
PktsAckedCalled()
void TcpPktsAckedOpenTest::PktsAckedCalled (uint32_t segmentsAcked)
Called when an ACK is received.
Parameters
segmentsAcked The segment ACKed.
Definition at line 154 of file tcp-pkts-acked-test.cc.
References m_segmentsAcked.
Referenced by CreateSenderSocket().
Rx()
void TcpPktsAckedOpenTest::Rx (const Ptr< const Packet > p, const TcpHeader & h, SocketWho who) protected virtual
Packet received from IP layer.
Parameters
p packet
h header
who the socket which has received the packet (SENDER or RECEIVER)
Reimplemented from ns3::TcpGeneralTest.
Definition at line 160 of file tcp-pkts-acked-test.cc.
References ns3::TcpHeader::GetAckNumber(), ns3::TcpHeader::GetFlags(), ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::GetValue(), m_segmentsReceived, and ns3::TcpGeneralTest::SENDER.
Member Data Documentation
m_congCtl
Ptr<DummyCongControl> TcpPktsAckedOpenTest::m_congCtl private
Dummy congestion control.
Definition at line 74 of file tcp-pkts-acked-test.cc.
Referenced by CreateSenderSocket().
m_segmentsAcked
uint32_t TcpPktsAckedOpenTest::m_segmentsAcked private
Contains the number of times PktsAcked is called.
Definition at line 71 of file tcp-pkts-acked-test.cc.
Referenced by FinalChecks(), and PktsAckedCalled().
m_segmentsReceived
uint32_t TcpPktsAckedOpenTest::m_segmentsReceived private
Contains the ack number received.
Definition at line 72 of file tcp-pkts-acked-test.cc.
Referenced by FinalChecks(), and Rx().
The documentation for this class was generated from the following file:
src/internet/test/tcp-pkts-acked-test.cc