ns-3: ns3::Ipv6OptionJumbogramHeader Class Reference
ns3::Ipv6OptionJumbogramHeader Class Reference
Internet » IPv6 classes and sub-modules » IPV6 Header extension system.
Header of IPv6 Option Jumbogram.
#include "ipv6-option-header.h"
Public Member Functions
Ipv6OptionJumbogramHeader ()
Constructor.
virtual ~Ipv6OptionJumbogramHeader ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
virtual Alignment GetAlignment () const
Get the Alignment requirement of this option header.
uint32_t GetDataLength () const
Get the data length.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
virtual uint32_t GetSerializedSize () const
Get the serialized size of the packet.
virtual void Print (std::ostream &os) const
Print some information about the packet.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetDataLength (uint32_t dataLength)
Set the data length.
Public Member Functions inherited from ns3::Ipv6OptionHeader
Ipv6OptionHeader ()
Constructor.
virtual ~Ipv6OptionHeader ()
Destructor.
uint8_t GetLength () const
Get the option length.
uint8_t GetType () const
Get the type of the option.
void SetLength (uint8_t length)
Set the option length.
void SetType (uint8_t type)
Set the type of the option.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Ipv6OptionHeader
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint32_t m_dataLength
The data length.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Header of IPv6 Option Jumbogram.
Definition at line 271 of file ipv6-option-header.h.
Constructor & Destructor Documentation
Ipv6OptionJumbogramHeader()
ns3::Ipv6OptionJumbogramHeader::Ipv6OptionJumbogramHeader ()
Constructor.
Definition at line 250 of file ipv6-option-header.cc.
References m_dataLength, ns3::Ipv6OptionHeader::SetLength(), and ns3::Ipv6OptionHeader::SetType().
~Ipv6OptionJumbogramHeader()
ns3::Ipv6OptionJumbogramHeader::~Ipv6OptionJumbogramHeader () virtual
Destructor.
Definition at line 257 of file ipv6-option-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::Ipv6OptionJumbogramHeader::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start Buffer iterator
Returns
size of the packet
Reimplemented from ns3::Ipv6OptionHeader.
Definition at line 290 of file ipv6-option-header.cc.
References GetSerializedSize(), m_dataLength, ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadU8(), ns3::Ipv6OptionHeader::SetLength(), ns3::Ipv6OptionHeader::SetType(), and visualizer.core::start().
GetAlignment()
Ipv6OptionHeader::Alignment ns3::Ipv6OptionJumbogramHeader::GetAlignment () const virtual
Get the Alignment requirement of this option header.
Returns
The required alignment
Reimplemented from ns3::Ipv6OptionHeader.
Definition at line 301 of file ipv6-option-header.cc.
GetDataLength()
uint32_t ns3::Ipv6OptionJumbogramHeader::GetDataLength () const
Get the data length.
Returns
the data length
Definition at line 266 of file ipv6-option-header.cc.
References m_dataLength.
GetInstanceTypeId()
TypeId ns3::Ipv6OptionJumbogramHeader::GetInstanceTypeId () const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::Ipv6OptionHeader.
Definition at line 245 of file ipv6-option-header.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::Ipv6OptionJumbogramHeader::GetSerializedSize () const virtual
Get the serialized size of the packet.
Returns
size
Reimplemented from ns3::Ipv6OptionHeader.
Definition at line 276 of file ipv6-option-header.cc.
References ns3::Ipv6OptionHeader::GetLength().
Referenced by Deserialize(), and ns3::Ipv6OptionJumbogram::Process().
GetTypeId()
TypeId ns3::Ipv6OptionJumbogramHeader::GetTypeId () static
Get the type identificator.
Returns
type identificator
Definition at line 235 of file ipv6-option-header.cc.
References ns3::TypeId::AddConstructor().
Referenced by GetInstanceTypeId().
Print()
void ns3::Ipv6OptionJumbogramHeader::Print (std::ostream & os) const virtual
Print some information about the packet.
Parameters
os output stream
Returns
info about this packet
Reimplemented from ns3::Ipv6OptionHeader.
Definition at line 271 of file ipv6-option-header.cc.
References ns3::Ipv6OptionHeader::GetLength(), ns3::Ipv6OptionHeader::GetType(), and m_dataLength.
Serialize()
void ns3::Ipv6OptionJumbogramHeader::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start Buffer iterator
Reimplemented from ns3::Ipv6OptionHeader.
Definition at line 281 of file ipv6-option-header.cc.
References ns3::Ipv6OptionHeader::GetLength(), ns3::Ipv6OptionHeader::GetType(), m_dataLength, visualizer.core::start(), ns3::Buffer::Iterator::WriteHtonU32(), and ns3::Buffer::Iterator::WriteU8().
SetDataLength()
void ns3::Ipv6OptionJumbogramHeader::SetDataLength (uint32_t dataLength)
Set the data length.
Parameters
dataLength the data length
Definition at line 261 of file ipv6-option-header.cc.
References m_dataLength.
Member Data Documentation
m_dataLength
uint32_t ns3::Ipv6OptionJumbogramHeader::m_dataLength private
The data length.
Definition at line 344 of file ipv6-option-header.h.
Referenced by Ipv6OptionJumbogramHeader(), Deserialize(), GetDataLength(), Print(), Serialize(), and SetDataLength().
The documentation for this class was generated from the following files:
src/internet/model/ipv6-option-header.h
src/internet/model/ipv6-option-header.cc