ns-3: visualizer.ipython_view.IterableIPShell Class Reference
visualizer.ipython_view.IterableIPShell Class Reference
IterableIPShell class.
Public Member Functions
def __init__ (self, argv=None, user_ns=None, user_global_ns=None, cin=None, cout=None, cerr=None, input_func=None)
Initializer.
def complete (self, line)
Returns an auto completed line and/or possibilities for completion.
def execute (self)
Executes the current line provided by the shell object.
def generatePrompt (self, is_continuation)
Generate prompt depending on is_continuation value.
def historyBack (self)
Provides one history command back.
def historyForward (self)
Provides one history command forward.
def shell (self, cmd, verbose=0, debug=0, header='')
Replacement method to allow shell commands without them blocking.
def updateNamespace (self, ns_dict)
Add the current dictionary to the shell namespace.
Public Attributes
complete_sep
history_level
IP
iter_more
prompt
Private Member Functions
def __update_namespace (self)
Update self.IP namespace for autocompletion with sys.modules.
def _getHistory (self)
Gets the command string of the current history level.
Detailed Description
IterableIPShell class.
Definition at line 35 of file ipython_view.py.
Constructor & Destructor Documentation
__init__()
def visualizer.ipython_view.IterableIPShell.__init__ (self, argv = None, user_ns = None, user_global_ns = None, cin = None, cout = None, cerr = None, input_func = None)
Initializer.
Parameters
self this object
argv Command line options for IPython
user_ns User namespace.
user_global_ns User global namespace.
cin Console standard input.
cout Console standard output.
cerr Console standard error.
input_func Replacement for builtin raw_input()
Returns
none
Definition at line 75 of file ipython_view.py.
Member Function Documentation
__update_namespace()
def visualizer.ipython_view.IterableIPShell.__update_namespace (self) private
Update self.IP namespace for autocompletion with sys.modules.
Definition at line 149 of file ipython_view.py.
References visualizer.ipython_view.IterableIPShell.IP, and list.
_getHistory()
def visualizer.ipython_view.IterableIPShell._getHistory (self) private
Gets the command string of the current history level.
Parameters
self this object
Returns
: Historic command string.
Definition at line 254 of file ipython_view.py.
References visualizer.ipython_view.IterableIPShell.history_level, and visualizer.ipython_view.IterableIPShell.IP.
Referenced by visualizer.ipython_view.IterableIPShell.historyBack(), and visualizer.ipython_view.IterableIPShell.historyForward().
complete()
def visualizer.ipython_view.IterableIPShell.complete (self, line)
Returns an auto completed line and/or possibilities for completion.
Parameters
line Given line so far.
Returns
: Line completed as for as possible, and possible further completions.
Definition at line 276 of file ipython_view.py.
References visualizer.ipython_view.IterableIPShell.complete_sep, and visualizer.ipython_view.IterableIPShell.IP.
Referenced by visualizer.ipython_view.IPythonView.onKeyPressExtend().
execute()
def visualizer.ipython_view.IterableIPShell.execute (self)
Executes the current line provided by the shell object.
Definition at line 157 of file ipython_view.py.
References visualizer.ipython_view.IterableIPShell.history_level.
generatePrompt()
def visualizer.ipython_view.IterableIPShell.generatePrompt (self, is_continuation)
Generate prompt depending on is_continuation value.
Parameters
is_continuation
Returns
: The prompt string representation
Definition at line 208 of file ipython_view.py.
References visualizer.ipython_view.IterableIPShell.IP.
historyBack()
def visualizer.ipython_view.IterableIPShell.historyBack (self)
Provides one history command back.
Parameters
self this object
Returns
: The command string.
Definition at line 231 of file ipython_view.py.
References visualizer.ipython_view.IterableIPShell._getHistory(), and visualizer.ipython_view.IterableIPShell.history_level.
Referenced by visualizer.ipython_view.IPythonView.onKeyPressExtend().
historyForward()
def visualizer.ipython_view.IterableIPShell.historyForward (self)
Provides one history command forward.
Parameters
self this object
Returns
: The command string.
Definition at line 243 of file ipython_view.py.
References visualizer.ipython_view.IterableIPShell._getHistory(), and visualizer.ipython_view.IterableIPShell.history_level.
Referenced by visualizer.ipython_view.IPythonView.onKeyPressExtend().
shell()
def visualizer.ipython_view.IterableIPShell.shell (self, cmd, verbose = 0, debug = 0, header = '')
Replacement method to allow shell commands without them blocking.
Parameters
cmd Shell command to execute.
verbose Verbosity
debug Debug level
header Header to be printed before output
Returns
none
Definition at line 312 of file ipython_view.py.
References print.
updateNamespace()
def visualizer.ipython_view.IterableIPShell.updateNamespace (self, ns_dict)
Add the current dictionary to the shell namespace.
Parameters
ns_dict A dictionary of symbol-values.
Returns
none
Definition at line 267 of file ipython_view.py.
References visualizer.ipython_view.IterableIPShell.IP.
Member Data Documentation
complete_sep
visualizer.ipython_view.IterableIPShell.complete_sep
separators
Definition at line 140 of file ipython_view.py.
Referenced by visualizer.ipython_view.IterableIPShell.complete().
history_level
visualizer.ipython_view.IterableIPShell.history_level
history level
Definition at line 139 of file ipython_view.py.
Referenced by visualizer.ipython_view.IterableIPShell._getHistory(), visualizer.ipython_view.IterableIPShell.execute(), visualizer.ipython_view.IterableIPShell.historyBack(), and visualizer.ipython_view.IterableIPShell.historyForward().
IP
visualizer.ipython_view.IterableIPShell.IP
IP
Definition at line 122 of file ipython_view.py.
Referenced by visualizer.ipython_view.IterableIPShell.__update_namespace(), visualizer.ipython_view.IterableIPShell._getHistory(), visualizer.ipython_view.ConsoleView._showReturned(), visualizer.ipython_view.IterableIPShell.complete(), visualizer.ipython_view.IterableIPShell.generatePrompt(), and visualizer.ipython_view.IterableIPShell.updateNamespace().
iter_more
visualizer.ipython_view.IterableIPShell.iter_more
iterate more
Definition at line 138 of file ipython_view.py.
prompt
visualizer.ipython_view.IterableIPShell.prompt
prompt
Definition at line 167 of file ipython_view.py.
Referenced by visualizer.ipython_view.ConsoleView._showReturned(), and visualizer.ipython_view.IPythonView.onKeyPressExtend().
The documentation for this class was generated from the following file:
src/visualizer/visualizer/ipython_view.py