ns-3: ns3::LteFfrSapProvider Class Reference
ns3::LteFfrSapProvider Class Reference abstract
Service Access Point (SAP) offered by the Frequency Reuse algorithm instance to the MAC Scheduler instance.
#include "lte-ffr-sap.h"
Public Member Functions
virtual ~LteFfrSapProvider ()
virtual std::vector< bool > GetAvailableDlRbg ()=0
Get vector of available RBG in DL for this Cell.
virtual std::vector< bool > GetAvailableUlRbg ()=0
Get vector of available RB in UL for this Cell.
virtual uint16_t GetMinContinuousUlBandwidth ()=0
Get the minimum continuous Ul bandwidth.
virtual uint8_t GetTpc (uint16_t rnti)=0
GetTpc.
virtual bool IsDlRbgAvailableForUe (int i, uint16_t rnti)=0
Check if UE can be served on i-th RB in DL.
virtual bool IsUlRbgAvailableForUe (int i, uint16_t rnti)=0
Check if UE can be served on i-th RB in UL.
virtual void ReportDlCqiInfo (const struct FfMacSchedSapProvider::SchedDlCqiInfoReqParameters &params)=0
ReportDlCqiInfo.
virtual void ReportUlCqiInfo (const struct FfMacSchedSapProvider::SchedUlCqiInfoReqParameters &params)=0
ReportUlCqiInfo.
virtual void ReportUlCqiInfo (std::map< uint16_t, std::vector< double > > ulCqiMap)=0
ReportUlCqiInfo.
Detailed Description
Service Access Point (SAP) offered by the Frequency Reuse algorithm instance to the MAC Scheduler instance.
This is the LteFfrSapProvider, i.e., the part of the SAP that contains the Frequency Reuse algorithm methods called by the MAC Scheduler instance.
Definition at line 39 of file lte-ffr-sap.h.
Constructor & Destructor Documentation
~LteFfrSapProvider()
ns3::LteFfrSapProvider::~LteFfrSapProvider () virtual
Definition at line 28 of file lte-ffr-sap.cc.
Member Function Documentation
GetAvailableDlRbg()
virtual std::vector<bool> ns3::LteFfrSapProvider::GetAvailableDlRbg () pure virtual
Get vector of available RBG in DL for this Cell.
Returns
vector of size (m_dlBandwidth/RbgSize); false indicates that RBG is free to use, true otherwise
This function is called by MAC Scheduler in the beginning of DL scheduling process. Frequency Reuse Algorithm based on its policy generates vector of RBG which can be used and which can not be used by Scheduler to schedule transmission.
Implemented in ns3::MemberLteFfrSapProvider< C >.
Referenced by ns3::CqaFfMacScheduler::DoSchedDlTriggerReq(), ns3::FdTbfqFfMacScheduler::DoSchedDlTriggerReq(), ns3::PfFfMacScheduler::DoSchedDlTriggerReq(), ns3::PssFfMacScheduler::DoSchedDlTriggerReq(), and ns3::TdTbfqFfMacScheduler::DoSchedDlTriggerReq().
GetAvailableUlRbg()
virtual std::vector<bool> ns3::LteFfrSapProvider::GetAvailableUlRbg () pure virtual
Get vector of available RB in UL for this Cell.
Returns
vector of size m_ulBandwidth; false indicates that RB is free to use, true otherwise
This function is called by MAC Scheduler in the beginning of UL scheduling process. Frequency Reuse Algorithm based on its policy generates vector of RB which can be used and which can not be used by Scheduler to schedule transmission.
Implemented in ns3::MemberLteFfrSapProvider< C >.
Referenced by ns3::CqaFfMacScheduler::DoSchedDlTriggerReq(), ns3::FdTbfqFfMacScheduler::DoSchedDlTriggerReq(), ns3::PfFfMacScheduler::DoSchedDlTriggerReq(), ns3::PssFfMacScheduler::DoSchedDlTriggerReq(), ns3::TdTbfqFfMacScheduler::DoSchedDlTriggerReq(), ns3::CqaFfMacScheduler::DoSchedUlTriggerReq(), ns3::FdTbfqFfMacScheduler::DoSchedUlTriggerReq(), ns3::PfFfMacScheduler::DoSchedUlTriggerReq(), ns3::PssFfMacScheduler::DoSchedUlTriggerReq(), and ns3::TdTbfqFfMacScheduler::DoSchedUlTriggerReq().
GetMinContinuousUlBandwidth()
virtual uint16_t ns3::LteFfrSapProvider::GetMinContinuousUlBandwidth () pure virtual
Get the minimum continuous Ul bandwidth.
Returns
the minimum continuous UL bandwidth
Implemented in ns3::MemberLteFfrSapProvider< C >.
Referenced by ns3::CqaFfMacScheduler::DoSchedUlTriggerReq(), ns3::FdTbfqFfMacScheduler::DoSchedUlTriggerReq(), ns3::PfFfMacScheduler::DoSchedUlTriggerReq(), ns3::PssFfMacScheduler::DoSchedUlTriggerReq(), and ns3::TdTbfqFfMacScheduler::DoSchedUlTriggerReq().
GetTpc()
virtual uint8_t ns3::LteFfrSapProvider::GetTpc (uint16_t rnti) pure virtual
GetTpc.
Parameters
rnti the RNTI
Returns
the TCP
Implemented in ns3::MemberLteFfrSapProvider< C >.
Referenced by ns3::CqaFfMacScheduler::DoSchedDlTriggerReq(), ns3::FdTbfqFfMacScheduler::DoSchedDlTriggerReq(), ns3::PfFfMacScheduler::DoSchedDlTriggerReq(), ns3::PssFfMacScheduler::DoSchedDlTriggerReq(), and ns3::TdTbfqFfMacScheduler::DoSchedDlTriggerReq().
IsDlRbgAvailableForUe()
virtual bool ns3::LteFfrSapProvider::IsDlRbgAvailableForUe (int i, uint16_t rnti) pure virtual
Check if UE can be served on i-th RB in DL.
Parameters
i RBG ID
rnti Radio Network Temporary Identity, an integer identifying the UE where the report originates from
Returns
true if UE can be served on i-th RB, false otherwise
This function is called by MAC Scheduler during DL scheduling process to check if UE is allowed to be served with i-th RBG. Frequency Reuse Algorithm based on its policy decides if RBG is allowed to UE. If yes, Scheduler will try to allocate this RBG for UE, if not this UE will not be served with this RBG.
Implemented in ns3::MemberLteFfrSapProvider< C >.
Referenced by ns3::CqaFfMacScheduler::DoSchedDlTriggerReq(), ns3::FdTbfqFfMacScheduler::DoSchedDlTriggerReq(), ns3::PfFfMacScheduler::DoSchedDlTriggerReq(), ns3::PssFfMacScheduler::DoSchedDlTriggerReq(), and ns3::TdTbfqFfMacScheduler::DoSchedDlTriggerReq().
IsUlRbgAvailableForUe()
virtual bool ns3::LteFfrSapProvider::IsUlRbgAvailableForUe (int i, uint16_t rnti) pure virtual
Check if UE can be served on i-th RB in UL.
Parameters
i RB ID
rnti Radio Network Temporary Identity, an integer identifying the UE where the report originates from
Returns
true if UE can be served on i-th RB, false otherwise
This function is called by MAC Scheduler during UL scheduling process to check if UE is allowed to be served with i-th RB. Frequency Reuse Algorithm based on its policy decides if RB is allowed to UE. If yes, Scheduler will try to allocate this RB for UE, if not this UE will not be served with this RB.
Implemented in ns3::MemberLteFfrSapProvider< C >.
Referenced by ns3::CqaFfMacScheduler::DoSchedUlTriggerReq(), ns3::FdTbfqFfMacScheduler::DoSchedUlTriggerReq(), ns3::PfFfMacScheduler::DoSchedUlTriggerReq(), ns3::PssFfMacScheduler::DoSchedUlTriggerReq(), and ns3::TdTbfqFfMacScheduler::DoSchedUlTriggerReq().
ReportDlCqiInfo()
virtual void ns3::LteFfrSapProvider::ReportDlCqiInfo (const struct FfMacSchedSapProvider::SchedDlCqiInfoReqParameters & params) pure virtual
ReportDlCqiInfo.
Parameters
params the struct FfMacSchedSapProvider::SchedDlCqiInfoReqParameters
Implemented in ns3::MemberLteFfrSapProvider< C >.
Referenced by ns3::CqaFfMacScheduler::DoSchedDlCqiInfoReq(), ns3::FdTbfqFfMacScheduler::DoSchedDlCqiInfoReq(), ns3::PfFfMacScheduler::DoSchedDlCqiInfoReq(), ns3::PssFfMacScheduler::DoSchedDlCqiInfoReq(), and ns3::TdTbfqFfMacScheduler::DoSchedDlCqiInfoReq().
ReportUlCqiInfo() [1/2]
virtual void ns3::LteFfrSapProvider::ReportUlCqiInfo (const struct FfMacSchedSapProvider::SchedUlCqiInfoReqParameters & params) pure virtual
ReportUlCqiInfo.
Parameters
params the struct FfMacSchedSapProvider::SchedUlCqiInfoReqParameters
Implemented in ns3::MemberLteFfrSapProvider< C >.
Referenced by ns3::PfFfMacScheduler::DoSchedUlCqiInfoReq(), ns3::CqaFfMacScheduler::DoSchedUlTriggerReq(), ns3::FdTbfqFfMacScheduler::DoSchedUlTriggerReq(), ns3::PfFfMacScheduler::DoSchedUlTriggerReq(), ns3::PssFfMacScheduler::DoSchedUlTriggerReq(), and ns3::TdTbfqFfMacScheduler::DoSchedUlTriggerReq().
ReportUlCqiInfo() [2/2]
virtual void ns3::LteFfrSapProvider::ReportUlCqiInfo (std::map< uint16_t, std::vector< double > > ulCqiMap) pure virtual
ReportUlCqiInfo.
Parameters
ulCqiMap the UL CQI map
Implemented in ns3::MemberLteFfrSapProvider< C >.
The documentation for this class was generated from the following files:
src/lte/model/lte-ffr-sap.h
src/lte/model/lte-ffr-sap.cc