ns-3: ns3::Icmpv4Header Class Reference
ns3::Icmpv4Header Class Reference
Internet » IPv4 classes and sub-modules » ICMP protocol and associated headers.
Base class for all the ICMP packet headers.
#include "icmpv4.h"
Public Types
enum Type_e { ICMPV4_ECHO_REPLY = 0, ICMPV4_DEST_UNREACH = 3, ICMPV4_ECHO = 8, ICMPV4_TIME_EXCEEDED = 11 }
ICMP type code.
Public Member Functions
Icmpv4Header ()
virtual ~Icmpv4Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)
void EnableChecksum (void)
Enables ICMP Checksum calculation.
uint8_t GetCode (void) const
Get ICMP code.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize (void) const
uint8_t GetType (void) const
Get ICMP type.
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetCode (uint8_t code)
Set ICMP code.
void SetType (uint8_t type)
Set ICMP type.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
bool m_calcChecksum
true if checksum is calculated
uint8_t m_code
ICMP code.
uint8_t m_type
ICMP type.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Base class for all the ICMP packet headers.
This header is the common part in all the ICMP packets.
Definition at line 40 of file icmpv4.h.
Member Enumeration Documentation
Type_e
enum ns3::Icmpv4Header::Type_e
ICMP type code.
Enumerator
ICMPV4_ECHO_REPLY
ICMPV4_DEST_UNREACH
ICMPV4_ECHO
ICMPV4_TIME_EXCEEDED
Definition at line 47 of file icmpv4.h.
Constructor & Destructor Documentation
Icmpv4Header()
ns3::Icmpv4Header::Icmpv4Header ()
Definition at line 45 of file icmpv4.cc.
References NS_LOG_FUNCTION.
~Icmpv4Header()
ns3::Icmpv4Header::~Icmpv4Header () virtual
Definition at line 52 of file icmpv4.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Deserialize()
uint32_t ns3::Icmpv4Header::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 93 of file icmpv4.cc.
References m_code, m_type, NS_LOG_FUNCTION, and visualizer.core::start().
EnableChecksum()
void ns3::Icmpv4Header::EnableChecksum (void)
Enables ICMP Checksum calculation.
Definition at line 57 of file icmpv4.cc.
References m_calcChecksum, and NS_LOG_FUNCTION.
Referenced by ns3::V4Ping::Send(), ns3::V4TraceRoute::Send(), ns3::Icmpv4L4Protocol::SendMessage(), ChainRegressionTest::SendPing(), and ns3::olsr::Bug780Test::SendPing().
GetCode()
uint8_t ns3::Icmpv4Header::GetCode (void) const
Get ICMP code.
Returns
the ICMP code
Definition at line 127 of file icmpv4.cc.
References m_code, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv4L4Protocol::Forward().
GetInstanceTypeId()
TypeId ns3::Icmpv4Header::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 63 of file icmpv4.cc.
References GetTypeId(), and NS_LOG_FUNCTION.
GetSerializedSize()
uint32_t ns3::Icmpv4Header::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 69 of file icmpv4.cc.
References NS_LOG_FUNCTION.
GetType()
uint8_t ns3::Icmpv4Header::GetType (void) const
Get ICMP type.
Returns
the ICMP type
Definition at line 121 of file icmpv4.cc.
References m_type, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv4L4Protocol::Forward(), ns3::Ipv4RawSocketImpl::ForwardUp(), ns3::V4Ping::Receive(), ns3::V4TraceRoute::Receive(), ns3::olsr::Bug780Test::Receive(), IcmpEchoReplyTestCase::ReceivePkt(), and IcmpTimeExceedTestCase::ReceivePkt().
GetTypeId()
TypeId ns3::Icmpv4Header::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 36 of file icmpv4.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::Icmpv4Header::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 102 of file icmpv4.cc.
References m_code, m_type, and NS_LOG_FUNCTION.
Serialize()
void ns3::Icmpv4Header::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 75 of file icmpv4.cc.
References ns3::Buffer::Iterator::CalculateIpChecksum(), ns3::Buffer::Iterator::GetSize(), m_calcChecksum, m_code, m_type, ns3::Buffer::Iterator::Next(), NS_LOG_FUNCTION, visualizer.core::start(), ns3::Buffer::Iterator::WriteHtonU16(), ns3::Buffer::Iterator::WriteU16(), and ns3::Buffer::Iterator::WriteU8().
SetCode()
void ns3::Icmpv4Header::SetCode (uint8_t code)
Set ICMP code.
Parameters
code the ICMP code
Definition at line 115 of file icmpv4.cc.
References m_code, and NS_LOG_FUNCTION.
Referenced by IcmpEchoReplyTestCase::DoSendData(), IcmpTimeExceedTestCase::DoSendData(), ns3::V4Ping::Send(), ns3::V4TraceRoute::Send(), ns3::Icmpv4L4Protocol::SendMessage(), ChainRegressionTest::SendPing(), and ns3::olsr::Bug780Test::SendPing().
SetType()
void ns3::Icmpv4Header::SetType (uint8_t type)
Set ICMP type.
Parameters
type the ICMP type
Definition at line 109 of file icmpv4.cc.
References m_type, and NS_LOG_FUNCTION.
Referenced by IcmpEchoReplyTestCase::DoSendData(), IcmpTimeExceedTestCase::DoSendData(), ns3::V4Ping::Send(), ns3::V4TraceRoute::Send(), ns3::Icmpv4L4Protocol::SendMessage(), ChainRegressionTest::SendPing(), and ns3::olsr::Bug780Test::SendPing().
Member Data Documentation
m_calcChecksum
bool ns3::Icmpv4Header::m_calcChecksum private
true if checksum is calculated
Definition at line 99 of file icmpv4.h.
Referenced by EnableChecksum(), and Serialize().
m_code
uint8_t ns3::Icmpv4Header::m_code private
ICMP code.
Definition at line 98 of file icmpv4.h.
Referenced by Deserialize(), GetCode(), Print(), Serialize(), and SetCode().
m_type
uint8_t ns3::Icmpv4Header::m_type private
ICMP type.
Definition at line 97 of file icmpv4.h.
Referenced by Deserialize(), GetType(), Print(), Serialize(), and SetType().
The documentation for this class was generated from the following files:
src/internet/model/icmpv4.h
src/internet/model/icmpv4.cc