ns-3: WaypointMobilityModelViaHelper Class Reference
WaypointMobilityModelViaHelper Class Reference
Mobility » mobility module tests | Test suites
Waypoint Mobility Model Via Helper Test.
Public Member Functions
WaypointMobilityModelViaHelper ()
virtual ~WaypointMobilityModelViaHelper ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void TestXPosition (Ptr< const WaypointMobilityModel > mob, double expectedXPos)
Text X position function.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Waypoint Mobility Model Via Helper Test.
Definition at line 330 of file mobility-test-suite.cc.
Constructor & Destructor Documentation
WaypointMobilityModelViaHelper()
WaypointMobilityModelViaHelper::WaypointMobilityModelViaHelper ()
Definition at line 346 of file mobility-test-suite.cc.
~WaypointMobilityModelViaHelper()
WaypointMobilityModelViaHelper::~WaypointMobilityModelViaHelper () virtual
Definition at line 351 of file mobility-test-suite.cc.
Member Function Documentation
DoRun()
void WaypointMobilityModelViaHelper::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 364 of file mobility-test-suite.cc.
References ns3::ListPositionAllocator::Add(), ns3::WaypointMobilityModel::AddWaypoint(), ns3::NodeContainer::Create(), ns3::NodeContainer::Get(), ns3::Object::GetObject(), ns3::MobilityHelper::Install(), third::mobility, ns3::Seconds(), ns3::MobilityHelper::SetMobilityModel(), ns3::MobilityHelper::SetPositionAllocator(), and TestXPosition().
TestXPosition()
void WaypointMobilityModelViaHelper::TestXPosition (Ptr< const WaypointMobilityModel > mob, double expectedXPos) private
Text X position function.
Parameters
mob the mobility model
expectedXPos the expected X position
Definition at line 356 of file mobility-test-suite.cc.
References ns3::MobilityModel::GetPosition(), and NS_TEST_EXPECT_MSG_EQ_TOL_INTERNAL.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/mobility/test/mobility-test-suite.cc