ns-3: ns3::dot11s::IePeeringProtocol Class Reference
ns3::dot11s::IePeeringProtocol Class Reference
Mesh Device » IEEE 802.11s draft
Mesh Peering Protocol Identifier information element Note that it does not permit to set any value besides zero (corresponding to mesh peering management protocol)
#include "ie-dot11s-peering-protocol.h"
Public Member Functions
IePeeringProtocol ()
virtual uint8_t DeserializeInformationField (Buffer::Iterator i, uint8_t length)
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
virtual WifiInformationElementId ElementId () const
virtual uint8_t GetInformationFieldSize () const
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
virtual void Print (std::ostream &os) const
Generate human-readable form of IE.
virtual void SerializeInformationField (Buffer::Iterator i) const
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
Public Member Functions inherited from ns3::WifiInformationElement
virtual ~WifiInformationElement ()
Buffer::Iterator Deserialize (Buffer::Iterator i)
Deserialize entire IE, which must be present.
Buffer::Iterator DeserializeIfPresent (Buffer::Iterator i)
Deserialize entire IE if it is present.
virtual WifiInformationElementId ElementIdExt () const
uint16_t GetSerializedSize () const
Get the size of the serialized IE including Element ID and length fields.
virtual bool operator== (WifiInformationElement const &a) const
Compare two IEs for equality by ID & Length, and then through memcmp of serialised version.
Buffer::Iterator Serialize (Buffer::Iterator i) const
Serialize entire IE including Element ID and length fields.
Public Member Functions inherited from ns3::SimpleRefCount< WifiInformationElement >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
uint8_t m_protocol
the protocol
Detailed Description
Mesh Peering Protocol Identifier information element Note that it does not permit to set any value besides zero (corresponding to mesh peering management protocol)
Definition at line 38 of file ie-dot11s-peering-protocol.h.
Constructor & Destructor Documentation
IePeeringProtocol()
ns3::dot11s::IePeeringProtocol::IePeeringProtocol ()
Definition at line 29 of file ie-dot11s-peering-protocol.cc.
Member Function Documentation
DeserializeInformationField()
uint8_t ns3::dot11s::IePeeringProtocol::DeserializeInformationField (Buffer::Iterator start, uint8_t length) virtual
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
length
Returns
the number of bytes read
Implements ns3::WifiInformationElement.
Definition at line 44 of file ie-dot11s-peering-protocol.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_protocol, ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
ElementId()
WifiInformationElementId ns3::dot11s::IePeeringProtocol::ElementId () const virtual
Returns
Own unique Element ID
Implements ns3::WifiInformationElement.
Definition at line 34 of file ie-dot11s-peering-protocol.cc.
References IE11S_MESH_PEERING_PROTOCOL_VERSION.
GetInformationFieldSize()
uint8_t ns3::dot11s::IePeeringProtocol::GetInformationFieldSize () const virtual
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
This is the value that will appear in the second octet of the entire IE - the length field)
Returns
the length of serialized information
Implements ns3::WifiInformationElement.
Definition at line 25 of file ie-dot11s-peering-protocol.cc.
Print()
void ns3::dot11s::IePeeringProtocol::Print (std::ostream & os) const virtual
Generate human-readable form of IE.
Parameters
os output stream
Reimplemented from ns3::WifiInformationElement.
Definition at line 51 of file ie-dot11s-peering-protocol.cc.
References m_protocol.
Referenced by ns3::dot11s::operator<<().
SerializeInformationField()
void ns3::dot11s::IePeeringProtocol::SerializeInformationField (Buffer::Iterator start) const virtual
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
Implements ns3::WifiInformationElement.
Definition at line 39 of file ie-dot11s-peering-protocol.cc.
References m_protocol, and ns3::Buffer::Iterator::WriteU8().
Member Data Documentation
m_protocol
uint8_t ns3::dot11s::IePeeringProtocol::m_protocol private
the protocol
Definition at line 51 of file ie-dot11s-peering-protocol.h.
Referenced by DeserializeInformationField(), Print(), and SerializeInformationField().
The documentation for this class was generated from the following files:
src/mesh/model/dot11s/ie-dot11s-peering-protocol.h
src/mesh/model/dot11s/ie-dot11s-peering-protocol.cc