ns-3: ns3::EpcX2HandoverRequestAckHeader Class Reference
ns3::EpcX2HandoverRequestAckHeader Class Reference
EpcX2HandoverRequestAckHeader.
#include "epc-x2-header.h"
Public Member Functions
EpcX2HandoverRequestAckHeader ()
virtual ~EpcX2HandoverRequestAckHeader ()
virtual uint32_t Deserialize (Buffer::Iterator start)
std::vector< EpcX2Sap::ErabAdmittedItem > GetAdmittedBearers () const
Get admittied bearers function.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint32_t GetLengthOfIes () const
Get length of IEs function.
uint16_t GetNewEnbUeX2apId () const
Get new ENB UE X2 AP ID function.
std::vector< EpcX2Sap::ErabNotAdmittedItem > GetNotAdmittedBearers () const
Get not admitted bearers function.
uint32_t GetNumberOfIes () const
Get number of IEs function.
uint16_t GetOldEnbUeX2apId () const
Get old ENB UE X2 AP ID function.
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetAdmittedBearers (std::vector< EpcX2Sap::ErabAdmittedItem > bearers)
Set admitted bearers function.
void SetNewEnbUeX2apId (uint16_t x2apId)
Set new ENB UE X2 AP ID function.
void SetNotAdmittedBearers (std::vector< EpcX2Sap::ErabNotAdmittedItem > bearers)
Set not admitted bearers function.
void SetOldEnbUeX2apId (uint16_t x2apId)
Set old ENB UE X2 AP ID function.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
std::vector< EpcX2Sap::ErabAdmittedItem > m_erabsAdmittedList
ERABs admitted list.
std::vector< EpcX2Sap::ErabNotAdmittedItem > m_erabsNotAdmittedList
ERABs not admitted list.
uint32_t m_headerLength
header length
uint16_t m_newEnbUeX2apId
new ENB UE X2 AP ID
uint32_t m_numberOfIes
number of IEs
uint16_t m_oldEnbUeX2apId
old ENB UE X2 AP ID
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
EpcX2HandoverRequestAckHeader.
Definition at line 235 of file epc-x2-header.h.
Constructor & Destructor Documentation
EpcX2HandoverRequestAckHeader()
ns3::EpcX2HandoverRequestAckHeader::EpcX2HandoverRequestAckHeader ()
Definition at line 439 of file epc-x2-header.cc.
~EpcX2HandoverRequestAckHeader()
ns3::EpcX2HandoverRequestAckHeader::~EpcX2HandoverRequestAckHeader () virtual
Definition at line 447 of file epc-x2-header.cc.
References m_erabsAdmittedList, m_erabsNotAdmittedList, m_headerLength, m_newEnbUeX2apId, m_numberOfIes, and m_oldEnbUeX2apId.
Member Function Documentation
Deserialize()
uint32_t ns3::EpcX2HandoverRequestAckHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 507 of file epc-x2-header.cc.
References ns3::EpcX2Sap::ErabNotAdmittedItem::cause, ns3::EpcX2Sap::ErabAdmittedItem::dlGtpTeid, ns3::EpcX2Sap::ErabAdmittedItem::erabId, ns3::EpcX2Sap::ErabNotAdmittedItem::erabId, GetSerializedSize(), m_erabsAdmittedList, m_erabsNotAdmittedList, m_headerLength, m_newEnbUeX2apId, m_numberOfIes, m_oldEnbUeX2apId, ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadNtohU32(), visualizer.core::start(), and ns3::EpcX2Sap::ErabAdmittedItem::ulGtpTeid.
GetAdmittedBearers()
std::vector< EpcX2Sap::ErabAdmittedItem > ns3::EpcX2HandoverRequestAckHeader::GetAdmittedBearers () const
Get admittied bearers function.
Returns
<EpcX2Sap::ErabAdmittedItem>
Definition at line 624 of file epc-x2-header.cc.
References m_erabsAdmittedList.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
GetInstanceTypeId()
TypeId ns3::EpcX2HandoverRequestAckHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 469 of file epc-x2-header.cc.
References GetTypeId().
GetLengthOfIes()
uint32_t ns3::EpcX2HandoverRequestAckHeader::GetLengthOfIes () const
Get length of IEs function.
Returns
the length of IEs
Definition at line 650 of file epc-x2-header.cc.
References m_headerLength.
Referenced by ns3::EpcX2::DoSendHandoverRequestAck().
GetNewEnbUeX2apId()
uint16_t ns3::EpcX2HandoverRequestAckHeader::GetNewEnbUeX2apId () const
Get new ENB UE X2 AP ID function.
Returns
the new ENB UE X2 AP ID
Definition at line 612 of file epc-x2-header.cc.
References m_newEnbUeX2apId.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
GetNotAdmittedBearers()
std::vector< EpcX2Sap::ErabNotAdmittedItem > ns3::EpcX2HandoverRequestAckHeader::GetNotAdmittedBearers () const
Get not admitted bearers function.
Returns
the not admitted bearers
Definition at line 637 of file epc-x2-header.cc.
References m_erabsNotAdmittedList.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
GetNumberOfIes()
uint32_t ns3::EpcX2HandoverRequestAckHeader::GetNumberOfIes () const
Get number of IEs function.
Returns
the number of IEs
Definition at line 656 of file epc-x2-header.cc.
References m_numberOfIes.
Referenced by ns3::EpcX2::DoSendHandoverRequestAck().
GetOldEnbUeX2apId()
uint16_t ns3::EpcX2HandoverRequestAckHeader::GetOldEnbUeX2apId () const
Get old ENB UE X2 AP ID function.
Returns
the old ENB UE X2 AP ID
Definition at line 600 of file epc-x2-header.cc.
References m_oldEnbUeX2apId.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
GetSerializedSize()
uint32_t ns3::EpcX2HandoverRequestAckHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 475 of file epc-x2-header.cc.
References m_headerLength.
Referenced by Deserialize().
GetTypeId()
TypeId ns3::EpcX2HandoverRequestAckHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 458 of file epc-x2-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::EpcX2HandoverRequestAckHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 554 of file epc-x2-header.cc.
References m_erabsAdmittedList, m_erabsNotAdmittedList, m_newEnbUeX2apId, and m_oldEnbUeX2apId.
Serialize()
void ns3::EpcX2HandoverRequestAckHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 481 of file epc-x2-header.cc.
References m_erabsAdmittedList, m_erabsNotAdmittedList, m_newEnbUeX2apId, m_oldEnbUeX2apId, visualizer.core::start(), ns3::Buffer::Iterator::WriteHtonU16(), and ns3::Buffer::Iterator::WriteHtonU32().
SetAdmittedBearers()
void ns3::EpcX2HandoverRequestAckHeader::SetAdmittedBearers (std::vector< EpcX2Sap::ErabAdmittedItem > bearers)
Set admitted bearers function.
Parameters
bearers the admitted bearers
Definition at line 630 of file epc-x2-header.cc.
References m_erabsAdmittedList, and m_headerLength.
Referenced by ns3::EpcX2::DoSendHandoverRequestAck().
SetNewEnbUeX2apId()
void ns3::EpcX2HandoverRequestAckHeader::SetNewEnbUeX2apId (uint16_t x2apId)
Set new ENB UE X2 AP ID function.
Parameters
x2apId the new ENB UE X2 AP ID
Definition at line 618 of file epc-x2-header.cc.
References m_newEnbUeX2apId.
Referenced by ns3::EpcX2::DoSendHandoverRequestAck().
SetNotAdmittedBearers()
void ns3::EpcX2HandoverRequestAckHeader::SetNotAdmittedBearers (std::vector< EpcX2Sap::ErabNotAdmittedItem > bearers)
Set not admitted bearers function.
Parameters
bearers the not admitted bearers
Definition at line 643 of file epc-x2-header.cc.
References m_erabsNotAdmittedList, and m_headerLength.
Referenced by ns3::EpcX2::DoSendHandoverRequestAck().
SetOldEnbUeX2apId()
void ns3::EpcX2HandoverRequestAckHeader::SetOldEnbUeX2apId (uint16_t x2apId)
Set old ENB UE X2 AP ID function.
Parameters
x2apId the old ENB UE X2 AP ID
Definition at line 606 of file epc-x2-header.cc.
References m_oldEnbUeX2apId.
Referenced by ns3::EpcX2::DoSendHandoverRequestAck().
Member Data Documentation
m_erabsAdmittedList
std::vector<EpcX2Sap::ErabAdmittedItem> ns3::EpcX2HandoverRequestAckHeader::m_erabsAdmittedList private
ERABs admitted list.
Definition at line 314 of file epc-x2-header.h.
Referenced by ~EpcX2HandoverRequestAckHeader(), Deserialize(), GetAdmittedBearers(), Print(), Serialize(), and SetAdmittedBearers().
m_erabsNotAdmittedList
std::vector<EpcX2Sap::ErabNotAdmittedItem> ns3::EpcX2HandoverRequestAckHeader::m_erabsNotAdmittedList private
ERABs not admitted list.
Definition at line 315 of file epc-x2-header.h.
Referenced by ~EpcX2HandoverRequestAckHeader(), Deserialize(), GetNotAdmittedBearers(), Print(), Serialize(), and SetNotAdmittedBearers().
m_headerLength
uint32_t ns3::EpcX2HandoverRequestAckHeader::m_headerLength private
header length
Definition at line 310 of file epc-x2-header.h.
Referenced by ~EpcX2HandoverRequestAckHeader(), Deserialize(), GetLengthOfIes(), GetSerializedSize(), SetAdmittedBearers(), and SetNotAdmittedBearers().
m_newEnbUeX2apId
uint16_t ns3::EpcX2HandoverRequestAckHeader::m_newEnbUeX2apId private
new ENB UE X2 AP ID
Definition at line 313 of file epc-x2-header.h.
Referenced by ~EpcX2HandoverRequestAckHeader(), Deserialize(), GetNewEnbUeX2apId(), Print(), Serialize(), and SetNewEnbUeX2apId().
m_numberOfIes
uint32_t ns3::EpcX2HandoverRequestAckHeader::m_numberOfIes private
number of IEs
Definition at line 309 of file epc-x2-header.h.
Referenced by ~EpcX2HandoverRequestAckHeader(), Deserialize(), and GetNumberOfIes().
m_oldEnbUeX2apId
uint16_t ns3::EpcX2HandoverRequestAckHeader::m_oldEnbUeX2apId private
old ENB UE X2 AP ID
Definition at line 312 of file epc-x2-header.h.
Referenced by ~EpcX2HandoverRequestAckHeader(), Deserialize(), GetOldEnbUeX2apId(), Print(), Serialize(), and SetOldEnbUeX2apId().
The documentation for this class was generated from the following files:
src/lte/model/epc-x2-header.h
src/lte/model/epc-x2-header.cc