ns-3: ns3::NistErrorRateModel Class Reference
ns3::NistErrorRateModel Class Reference
Wifi Models
#include "nist-error-rate-model.h"
Public Member Functions
NistErrorRateModel ()
double GetChunkSuccessRate (WifiMode mode, WifiTxVector txVector, double snr, uint64_t nbits) const
A pure virtual method that must be implemented in the subclass.
Public Member Functions inherited from ns3::ErrorRateModel
double CalculateSnr (WifiTxVector txVector, double ber) const
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ErrorRateModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
double CalculatePe (double p, uint32_t bValue) const
Return the coded BER for the given p and b.
double Get1024QamBer (double snr) const
Return BER of QAM1024 at the given SNR.
double Get16QamBer (double snr) const
Return BER of QAM16 at the given SNR.
double Get256QamBer (double snr) const
Return BER of QAM256 at the given SNR.
double Get64QamBer (double snr) const
Return BER of QAM64 at the given SNR.
double GetBpskBer (double snr) const
Return BER of BPSK at the given SNR.
double GetFec1024QamBer (double snr, uint64_t nbits, uint32_t bValue) const
Return BER of QAM1024 at the given SNR after applying FEC.
double GetFec16QamBer (double snr, uint64_t nbits, uint32_t bValue) const
Return BER of QAM16 at the given SNR after applying FEC.
double GetFec256QamBer (double snr, uint64_t nbits, uint32_t bValue) const
Return BER of QAM256 at the given SNR after applying FEC.
double GetFec64QamBer (double snr, uint64_t nbits, uint32_t bValue) const
Return BER of QAM64 at the given SNR after applying FEC.
double GetFecBpskBer (double snr, uint64_t nbits, uint32_t bValue) const
Return BER of BPSK at the given SNR after applying FEC.
double GetFecQpskBer (double snr, uint64_t nbits, uint32_t bValue) const
Return BER of QPSK at the given SNR after applying FEC.
double GetQpskBer (double snr) const
Return BER of QPSK at the given SNR.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A model for the error rate for different modulations. For OFDM modulation, the model description and validation can be found in http://www.nsnam.org/~pei/80211ofdm.pdf. For DSSS modulations (802.11b), the model uses the DsssErrorRateModel.
Definition at line 36 of file nist-error-rate-model.h.
Constructor & Destructor Documentation
NistErrorRateModel()
ns3::NistErrorRateModel::NistErrorRateModel ()
Definition at line 44 of file nist-error-rate-model.cc.
Member Function Documentation
CalculatePe()
double ns3::NistErrorRateModel::CalculatePe (double p, uint32_t bValue) const private
Return the coded BER for the given p and b.
Parameters
p the SNR ratio (not dB)
bValue such that coding rate = bValue / (bValue + 1)
Returns
the coded BER
Definition at line 141 of file nist-error-rate-model.cc.
References NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by GetFec1024QamBer(), GetFec16QamBer(), GetFec256QamBer(), GetFec64QamBer(), GetFecBpskBer(), and GetFecQpskBer().
Get1024QamBer()
double ns3::NistErrorRateModel::Get1024QamBer (double snr) const private
Return BER of QAM1024 at the given SNR.
Parameters
snr SNR ratio (not dB)
Returns
BER of QAM1024 at the given SNR
Definition at line 99 of file nist-error-rate-model.cc.
References NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by GetFec1024QamBer().
Get16QamBer()
double ns3::NistErrorRateModel::Get16QamBer (double snr) const private
Return BER of QAM16 at the given SNR.
Parameters
snr SNR ratio (not dB)
Returns
BER of QAM16 at the given SNR
Definition at line 69 of file nist-error-rate-model.cc.
References NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by GetFec16QamBer().
Get256QamBer()
double ns3::NistErrorRateModel::Get256QamBer (double snr) const private
Return BER of QAM256 at the given SNR.
Parameters
snr SNR ratio (not dB)
Returns
BER of QAM256 at the given SNR
Definition at line 89 of file nist-error-rate-model.cc.
References NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by GetFec256QamBer().
Get64QamBer()
double ns3::NistErrorRateModel::Get64QamBer (double snr) const private
Return BER of QAM64 at the given SNR.
Parameters
snr SNR ratio (not dB)
Returns
BER of QAM64 at the given SNR
Definition at line 79 of file nist-error-rate-model.cc.
References NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by GetFec64QamBer().
GetBpskBer()
double ns3::NistErrorRateModel::GetBpskBer (double snr) const private
Return BER of BPSK at the given SNR.
Parameters
snr SNR ratio (not dB)
Returns
BER of BPSK at the given SNR
Definition at line 49 of file nist-error-rate-model.cc.
References NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by GetFecBpskBer().
GetChunkSuccessRate()
double ns3::NistErrorRateModel::GetChunkSuccessRate (WifiMode mode, WifiTxVector txVector, double snr, uint64_t nbits) const virtual
A pure virtual method that must be implemented in the subclass.
This method returns the probability that the given 'chunk' of the packet will be successfully received by the PHY.
A chunk can be viewed as a part of a packet with equal SNR. The probability of successfully receiving the chunk depends on the mode, the SNR, and the size of the chunk.
Note that both a WifiMode and a WifiTxVector (which contains a WifiMode) are passed into this method. The WifiTxVector may be from a signal that contains multiple modes (e.g. PHY header sent differently from PHY payload). Consequently, the mode parameter is what the method uses to calculate the chunk error rate, and the txVector is used for other information as needed.
Parameters
mode the Wi-Fi mode applicable to this chunk
txVector TXVECTOR of the overall transmission
snr the SNR of the chunk
nbits the number of bits in this chunk
Returns
probability of successfully receiving the chunk
Implements ns3::ErrorRateModel.
Definition at line 277 of file nist-error-rate-model.cc.
References ns3::WifiMode::GetCodeRate(), ns3::WifiMode::GetConstellationSize(), ns3::WifiMode::GetDataRate(), ns3::DsssErrorRateModel::GetDsssDbpskSuccessRate(), ns3::DsssErrorRateModel::GetDsssDqpskCck11SuccessRate(), ns3::DsssErrorRateModel::GetDsssDqpskCck5_5SuccessRate(), ns3::DsssErrorRateModel::GetDsssDqpskSuccessRate(), GetFec1024QamBer(), GetFec16QamBer(), GetFec256QamBer(), GetFec64QamBer(), GetFecBpskBer(), GetFecQpskBer(), ns3::WifiTxVector::GetMode(), ns3::WifiMode::GetModulationClass(), NS_ASSERT, NS_LOG_FUNCTION, ns3::WIFI_CODE_RATE_1_2, ns3::WIFI_CODE_RATE_2_3, ns3::WIFI_CODE_RATE_5_6, ns3::WIFI_MOD_CLASS_DSSS, ns3::WIFI_MOD_CLASS_ERP_OFDM, ns3::WIFI_MOD_CLASS_HE, ns3::WIFI_MOD_CLASS_HR_DSSS, ns3::WIFI_MOD_CLASS_HT, ns3::WIFI_MOD_CLASS_OFDM, and ns3::WIFI_MOD_CLASS_VHT.
Referenced by WifiErrorRateModelsTestCaseNist::DoRun().
GetFec1024QamBer()
double ns3::NistErrorRateModel::GetFec1024QamBer (double snr, uint64_t nbits, uint32_t bValue) const private
Return BER of QAM1024 at the given SNR after applying FEC.
Parameters
snr SNR ratio (not dB)
nbits the number of bits in the chunk
bValue such that coding rate = bValue / (bValue + 1)
Returns
BER of QAM1024 at the given SNR after applying FEC
Definition at line 261 of file nist-error-rate-model.cc.
References CalculatePe(), Get1024QamBer(), min, and NS_LOG_FUNCTION.
Referenced by GetChunkSuccessRate().
GetFec16QamBer()
double ns3::NistErrorRateModel::GetFec16QamBer (double snr, uint64_t nbits, uint32_t bValue) const private
Return BER of QAM16 at the given SNR after applying FEC.
Parameters
snr SNR ratio (not dB)
nbits the number of bits in the chunk
bValue such that coding rate = bValue / (bValue + 1)
Returns
BER of QAM16 at the given SNR after applying FEC
Definition at line 213 of file nist-error-rate-model.cc.
References CalculatePe(), Get16QamBer(), min, and NS_LOG_FUNCTION.
Referenced by GetChunkSuccessRate().
GetFec256QamBer()
double ns3::NistErrorRateModel::GetFec256QamBer (double snr, uint64_t nbits, uint32_t bValue) const private
Return BER of QAM256 at the given SNR after applying FEC.
Parameters
snr SNR ratio (not dB)
nbits the number of bits in the chunk
bValue such that coding rate = bValue / (bValue + 1)
Returns
BER of QAM256 at the given SNR after applying FEC
Definition at line 245 of file nist-error-rate-model.cc.
References CalculatePe(), Get256QamBer(), min, and NS_LOG_FUNCTION.
Referenced by GetChunkSuccessRate().
GetFec64QamBer()
double ns3::NistErrorRateModel::GetFec64QamBer (double snr, uint64_t nbits, uint32_t bValue) const private
Return BER of QAM64 at the given SNR after applying FEC.
Parameters
snr SNR ratio (not dB)
nbits the number of bits in the chunk
bValue such that coding rate = bValue / (bValue + 1)
Returns
BER of QAM64 at the given SNR after applying FEC
Definition at line 229 of file nist-error-rate-model.cc.
References CalculatePe(), Get64QamBer(), min, and NS_LOG_FUNCTION.
Referenced by GetChunkSuccessRate().
GetFecBpskBer()
double ns3::NistErrorRateModel::GetFecBpskBer (double snr, uint64_t nbits, uint32_t bValue) const private
Return BER of BPSK at the given SNR after applying FEC.
Parameters
snr SNR ratio (not dB)
nbits the number of bits in the chunk
bValue such that coding rate = bValue / (bValue + 1)
Returns
BER of BPSK at the given SNR after applying FEC
Definition at line 109 of file nist-error-rate-model.cc.
References CalculatePe(), GetBpskBer(), min, and NS_LOG_FUNCTION.
Referenced by GetChunkSuccessRate().
GetFecQpskBer()
double ns3::NistErrorRateModel::GetFecQpskBer (double snr, uint64_t nbits, uint32_t bValue) const private
Return BER of QPSK at the given SNR after applying FEC.
Parameters
snr SNR ratio (not dB)
nbits the number of bits in the chunk
bValue such that coding rate = bValue / (bValue + 1)
Returns
BER of QPSK at the given SNR after applying FEC
Definition at line 125 of file nist-error-rate-model.cc.
References CalculatePe(), GetQpskBer(), min, and NS_LOG_FUNCTION.
Referenced by GetChunkSuccessRate().
GetQpskBer()
double ns3::NistErrorRateModel::GetQpskBer (double snr) const private
Return BER of QPSK at the given SNR.
Parameters
snr SNR ratio (not dB)
Returns
BER of QPSK at the given SNR
Definition at line 59 of file nist-error-rate-model.cc.
References NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by GetFecQpskBer().
GetTypeId()
TypeId ns3::NistErrorRateModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 34 of file nist-error-rate-model.cc.
References ns3::TypeId::SetParent().
The documentation for this class was generated from the following files:
src/wifi/model/nist-error-rate-model.h
src/wifi/model/nist-error-rate-model.cc