ns-3: ns3::YansWifiChannel Class Reference
ns3::YansWifiChannel Class Reference
Wifi Models
a channel to interconnect ns3::YansWifiPhy objects.
#include "yans-wifi-channel.h"
Public Member Functions
YansWifiChannel ()
virtual ~YansWifiChannel ()
void Add (Ptr< YansWifiPhy > phy)
Adds the given YansWifiPhy to the PHY list.
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
virtual Ptr< NetDevice > GetDevice (std::size_t i) const
virtual std::size_t GetNDevices (void) const
void Send (Ptr< YansWifiPhy > sender, Ptr< const WifiPpdu > ppdu, double txPowerDbm) const
void SetPropagationDelayModel (const Ptr< PropagationDelayModel > delay)
void SetPropagationLossModel (const Ptr< PropagationLossModel > loss)
Public Member Functions inherited from ns3::Channel
Channel ()
virtual ~Channel ()
uint32_t GetId (void) const
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Channel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef std::vector< Ptr< YansWifiPhy > > PhyList
A vector of pointers to YansWifiPhy.
Static Private Member Functions
static void Receive (Ptr< YansWifiPhy > receiver, Ptr< WifiPpdu > ppdu, double txPowerDbm)
This method is scheduled by Send for each associated YansWifiPhy.
Private Attributes
Ptr< PropagationDelayModel > m_delay
Propagation delay model.
Ptr< PropagationLossModel > m_loss
Propagation loss model.
PhyList m_phyList
List of YansWifiPhys connected to this YansWifiChannel.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
a channel to interconnect ns3::YansWifiPhy objects.
This class is expected to be used in tandem with the ns3::YansWifiPhy class and supports an ns3::PropagationLossModel and an ns3::PropagationDelayModel. By default, no propagation models are set; it is the caller's responsibility to set them before using the channel.
Definition at line 45 of file yans-wifi-channel.h.
Member Typedef Documentation
PhyList
typedef std::vector<Ptr<YansWifiPhy> > ns3::YansWifiChannel::PhyList private
A vector of pointers to YansWifiPhy.
Definition at line 105 of file yans-wifi-channel.h.
Constructor & Destructor Documentation
YansWifiChannel()
ns3::YansWifiChannel::YansWifiChannel ()
Definition at line 60 of file yans-wifi-channel.cc.
References NS_LOG_FUNCTION.
~YansWifiChannel()
ns3::YansWifiChannel::~YansWifiChannel () virtual
Definition at line 65 of file yans-wifi-channel.cc.
References m_phyList, and NS_LOG_FUNCTION.
Member Function Documentation
Add()
void ns3::YansWifiChannel::Add (Ptr< YansWifiPhy > phy)
Adds the given YansWifiPhy to the PHY list.
Parameters
phy the YansWifiPhy to be added to the PHY list
Definition at line 152 of file yans-wifi-channel.cc.
References m_phyList, NS_LOG_FUNCTION, and third::phy.
AssignStreams()
int64_t ns3::YansWifiChannel::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 159 of file yans-wifi-channel.cc.
References ns3::PropagationLossModel::AssignStreams(), m_loss, and NS_LOG_FUNCTION.
GetDevice()
Ptr< NetDevice > ns3::YansWifiChannel::GetDevice (std::size_t i) const virtual
Parameters
i index of NetDevice to retrieve
Returns
one of the NetDevices connected to this channel.
This method must be implemented by subclasses.
Implements ns3::Channel.
Definition at line 146 of file yans-wifi-channel.cc.
References m_phyList.
GetNDevices()
std::size_t ns3::YansWifiChannel::GetNDevices (void) const virtual
Returns
the number of NetDevices connected to this Channel.
This method must be implemented by subclasses.
Implements ns3::Channel.
Definition at line 140 of file yans-wifi-channel.cc.
References m_phyList.
GetTypeId()
TypeId ns3::YansWifiChannel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 42 of file yans-wifi-channel.cc.
References m_delay, m_loss, ns3::MakePointerAccessor(), and ns3::TypeId::SetParent().
Receive()
void ns3::YansWifiChannel::Receive (Ptr< YansWifiPhy > receiver, Ptr< WifiPpdu > ppdu, double txPowerDbm) static private
This method is scheduled by Send for each associated YansWifiPhy.
The method then calls the corresponding YansWifiPhy that the first bit of the PPDU has arrived.
Parameters
receiver the device to which the packet is destined
ppdu the PPDU being sent
txPowerDbm the TX power associated to the packet being sent (dBm)
Definition at line 126 of file yans-wifi-channel.cc.
References ns3::DbmToW(), NS_LOG_FUNCTION, NS_LOG_INFO, and third::phy.
Referenced by Send().
Send()
void ns3::YansWifiChannel::Send (Ptr< YansWifiPhy > sender, Ptr< const WifiPpdu > ppdu, double txPowerDbm) const
Parameters
sender the PHY object from which the packet is originating.
ppdu the PPDU to send
txPowerDbm the TX power associated to the packet, in dBm
This method should not be invoked by normal users. It is currently invoked only from YansWifiPhy::StartTx. The channel attempts to deliver the PPDU to all other YansWifiPhy objects on the channel (except for the sender).
Definition at line 86 of file yans-wifi-channel.cc.
References ns3::PropagationLossModel::CalcRxPower(), ns3::Copy(), ns3::WifiPhy::GetChannelNumber(), ns3::MobilityModel::GetDistanceFrom(), ns3::WifiPhy::GetMobility(), ns3::Object::GetObject(), m_delay, m_loss, m_phyList, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, Receive(), and ns3::Simulator::ScheduleWithContext().
SetPropagationDelayModel()
void ns3::YansWifiChannel::SetPropagationDelayModel (const Ptr< PropagationDelayModel > delay)
Parameters
delay the new propagation delay model.
Definition at line 79 of file yans-wifi-channel.cc.
References m_delay, and NS_LOG_FUNCTION.
Referenced by experiment().
SetPropagationLossModel()
void ns3::YansWifiChannel::SetPropagationLossModel (const Ptr< PropagationLossModel > loss)
Parameters
loss the new propagation loss model.
Definition at line 72 of file yans-wifi-channel.cc.
References m_loss, and NS_LOG_FUNCTION.
Referenced by experiment().
Member Data Documentation
m_delay
Ptr<PropagationDelayModel> ns3::YansWifiChannel::m_delay private
Propagation delay model.
Definition at line 120 of file yans-wifi-channel.h.
Referenced by GetTypeId(), Send(), and SetPropagationDelayModel().
m_loss
Ptr<PropagationLossModel> ns3::YansWifiChannel::m_loss private
Propagation loss model.
Definition at line 119 of file yans-wifi-channel.h.
Referenced by AssignStreams(), GetTypeId(), Send(), and SetPropagationLossModel().
m_phyList
PhyList ns3::YansWifiChannel::m_phyList private
List of YansWifiPhys connected to this YansWifiChannel.
Definition at line 118 of file yans-wifi-channel.h.
Referenced by ~YansWifiChannel(), Add(), GetDevice(), GetNDevices(), and Send().
The documentation for this class was generated from the following files:
src/wifi/model/yans-wifi-channel.h
src/wifi/model/yans-wifi-channel.cc