ns-3: ThreeGppChannelConditionModelTestCase Class Reference
ThreeGppChannelConditionModelTestCase Class Reference
Test case for the 3GPP channel condition models.
Classes
struct TestVector
Struct containing the parameters for each test.
Public Member Functions
ThreeGppChannelConditionModelTestCase ()
Constructor.
virtual ~ThreeGppChannelConditionModelTestCase ()
Destructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Builds the simulation scenario and perform the tests.
void EvaluateChannelCondition (Ptr< MobilityModel > a, Ptr< MobilityModel > b)
Evaluates the channel condition between two nodes by calling the method GetChannelCondition on m_condModel.
Private Attributes
Ptr< ThreeGppChannelConditionModel > m_condModel
the channel condition model
uint64_t m_numLos
the number of LOS occurrences
TestVectors< TestVector > m_testVectors
array containing all the test vectors
double m_tolerance
tolerance
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test case for the 3GPP channel condition models.
It determines the channel condition multiple times, estimates the LOS probability and compares it with the value given by the formulas in 3GPP TR 38.901, Table Table 7.4.2-1.
Definition at line 40 of file channel-condition-model-test-suite.cc.
Constructor & Destructor Documentation
ThreeGppChannelConditionModelTestCase()
ThreeGppChannelConditionModelTestCase::ThreeGppChannelConditionModelTestCase ()
Constructor.
Definition at line 85 of file channel-condition-model-test-suite.cc.
~ThreeGppChannelConditionModelTestCase()
ThreeGppChannelConditionModelTestCase::~ThreeGppChannelConditionModelTestCase () virtual
Destructor.
Definition at line 92 of file channel-condition-model-test-suite.cc.
Member Function Documentation
DoRun()
void ThreeGppChannelConditionModelTestCase::DoRun (void) private virtual
Builds the simulation scenario and perform the tests.
Implements ns3::TestCase.
Definition at line 107 of file channel-condition-model-test-suite.cc.
References ns3::ObjectFactory::Create(), EvaluateChannelCondition(), m_condModel, m_numLos, ThreeGppChannelConditionModelTestCase::TestVector::m_pLos, ThreeGppChannelConditionModelTestCase::TestVector::m_positionA, ThreeGppChannelConditionModelTestCase::TestVector::m_positionB, m_testVectors, m_tolerance, ThreeGppChannelConditionModelTestCase::TestVector::m_typeId, ns3::MilliSeconds(), first::nodes, NS_LOG_DEBUG, NS_TEST_EXPECT_MSG_EQ_TOL, ns3::ObjectBase::SetAttribute(), ns3::MobilityModel::SetPosition(), and ns3::ObjectFactory::SetTypeId().
EvaluateChannelCondition()
void ThreeGppChannelConditionModelTestCase::EvaluateChannelCondition (Ptr< MobilityModel > a, Ptr< MobilityModel > b) private
Evaluates the channel condition between two nodes by calling the method GetChannelCondition on m_condModel.
If the channel condition is LOS it increments m_numLos
Parameters
a the mobility model of the first node
b the mobility model of the second node
Definition at line 97 of file channel-condition-model-test-suite.cc.
References ns3::ThreeGppChannelConditionModel::GetChannelCondition(), ns3::ChannelCondition::GetLosCondition(), m_condModel, and m_numLos.
Referenced by DoRun().
Member Data Documentation
m_condModel
Ptr<ThreeGppChannelConditionModel> ThreeGppChannelConditionModelTestCase::m_condModel private
the channel condition model
Definition at line 80 of file channel-condition-model-test-suite.cc.
Referenced by DoRun(), and EvaluateChannelCondition().
m_numLos
uint64_t ThreeGppChannelConditionModelTestCase::m_numLos private
the number of LOS occurrences
Definition at line 81 of file channel-condition-model-test-suite.cc.
Referenced by DoRun(), and EvaluateChannelCondition().
m_testVectors
TestVectors<TestVector> ThreeGppChannelConditionModelTestCase::m_testVectors private
array containing all the test vectors
Definition at line 79 of file channel-condition-model-test-suite.cc.
Referenced by DoRun().
m_tolerance
double ThreeGppChannelConditionModelTestCase::m_tolerance private
tolerance
Definition at line 82 of file channel-condition-model-test-suite.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/propagation/test/channel-condition-model-test-suite.cc