ns-3: ns3::CallbackBase Class Reference
ns3::CallbackBase Class Reference
Core » Callbacks » Callback Implementation
#include "callback.h"
Inherited by ns3::Callback< bool, ns3::Ptr< const ns3::Packet >, const ns3::Address &, uint32_t, uint32_t >, ns3::Callback< bool, ns3::Ptr< ns3::Socket >, const ns3::Address & >, ns3::Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address & >, ns3::Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address &, const Address &, enum PacketType >, ns3::Callback< bool, Ptr< Packet > >, ns3::Callback< bool, Ptr< Packet >, const Address &, const Address &, uint16_t >, ns3::Callback< bool, std::string >, ns3::Callback< ns3::ObjectBase * >, ns3::Callback< std::vector< ns3::Mac48Address >, uint32_t >, ns3::Callback< uint32_t, ns3::Mac48Address, ns3::Ptr< ns3::MeshWifiInterfaceMac > >, ns3::Callback< void >, ns3::Callback< void, bool, bool, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, bool, uint32_t, double, ns3::Time, empty, empty, empty, empty >, ns3::Callback< void, bool, uint64_t >, ns3::Callback< void, const ns3::dsr::DsrOptionSRHeader &, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, const ns3::Ipv4Address &, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, const ns3::Ipv4Header &, const ns3::TcpHeader &, ns3::Ptr< const ns3::Packet > >, ns3::Callback< void, const ns3::Ipv4Header &, ns3::Ptr< const ns3::Packet >, DropReason, ns3::Ptr< ns3::Ipv4 >, uint32_t, empty, empty, empty >, ns3::Callback< void, const ns3::Ipv4Header &, ns3::Ptr< const ns3::Packet >, uint32_t, empty, empty, empty, empty, empty >, ns3::Callback< void, const ns3::Ipv6Header &, ns3::Ptr< const ns3::Packet >, DropReason, ns3::Ptr< ns3::Ipv6 >, uint32_t, empty, empty, empty >, ns3::Callback< void, const ns3::Ipv6Header &, ns3::Ptr< const ns3::Packet >, uint32_t, empty, empty, empty, empty, empty >, ns3::Callback< void, const ns3::olsr::PacketHeader &, const MessageList &, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, const ns3::Time &, const ns3::Address &, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, const ns3::WifiMacHeader &, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, const std::string &, const std::string &, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, const TcpRateConnection &, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, const TcpRateSample &, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, const WifiMacHeader & >, ns3::Callback< void, DlInfoListElement_s >, ns3::Callback< void, double >, ns3::Callback< void, double, double, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, double, double, ns3::Mac48Address, empty, empty, empty, empty, empty >, ns3::Callback< void, DropReason, ns3::Ptr< const ns3::Packet >, ns3::Ptr< ns3::SixLowPanNetDevice >, uint32_t, empty, empty, empty, empty >, ns3::Callback< void, EcnState_t, EcnState_t, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, empty, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, int >, ns3::Callback< void, int, int, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, int16_t, int16_t, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, int64_t, int64_t, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, int8_t >, ns3::Callback< void, LrWpanMacState >, ns3::Callback< void, LrWpanMacState, LrWpanMacState, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, LrWpanPhyEnumeration >, ns3::Callback< void, LrWpanPhyEnumeration, LrWpanPhyEnumeration, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, LrWpanPhyEnumeration, LrWpanPibAttributeIdentifier >, ns3::Callback< void, LrWpanPhyEnumeration, LrWpanPibAttributeIdentifier, LrWpanPhyPibAttributes * >, ns3::Callback< void, LrWpanPhyEnumeration, uint8_t >, ns3::Callback< void, Mac48Address, Mac48Address, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, McpsDataConfirmParams >, ns3::Callback< void, McpsDataIndicationParams, Ptr< Packet > >, ns3::Callback< void, MlmeBeaconNotifyIndicationParams, Ptr< Packet > >, ns3::Callback< void, MlmePollConfirmParams >, ns3::Callback< void, MlmeStartConfirmParams >, ns3::Callback< void, MlmeSyncLossIndicationParams >, ns3::Callback< void, ns3::Address, ns3::Address, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::DataRate, ns3::DataRate, ns3::Mac48Address, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::DlSchedulingCallbackInfo, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::HePreambleParameters, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ipv4Address >, ns3::Callback< void, ns3::Ipv4Address, uint8_t >, ns3::Callback< void, ns3::Ipv4Address, uint8_t, uint8_t, uint8_t, uint32_t >, ns3::Callback< void, ns3::Ipv6Address, uint8_t, uint8_t, uint8_t, uint32_t >, ns3::Callback< void, ns3::Mac48Address, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Mac48Address, ns3::Mac48Address, uint32_t, bool >, ns3::Callback< void, ns3::Mac48Address, uint8_t >, ns3::Callback< void, ns3::Mac48Address, uint8_t, bool >, ns3::Callback< void, ns3::PhyReceptionStatParameters, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::PhyTransmissionStatParameters, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const Item >, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::ArpCache >, ns3::Ipv4Address >, ns3::Callback< void, ns3::Ptr< const ns3::MobilityModel >, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::MobilityModel >, ns3::Ptr< const ns3::MobilityModel >, double, double, double, double, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, const ns3::Address &, const ns3::Address &, const ns3::E2eStatsHeader &, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, const ns3::Address &, const ns3::Address &, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, const ns3::Address &, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, const ns3::Mac48Address &, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, const ns3::TcpHeader &, ns3::Ptr< const ns3::TcpSocketBase >, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, double, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, double, ns3::UanTxMode, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, double, ns3::WifiMode, WifiPreamble, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, ns3::Mac48Address, const ns3::Cid &, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, ns3::Mac48Address, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, ns3::Mac48Address, ns3::Cid, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, ns3::Mac8Address, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, ns3::Ptr< ns3::Ipv4 >, uint32_t, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, ns3::Ptr< ns3::Ipv6 >, uint32_t, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, ns3::Ptr< ns3::NetDevice >, ns3::Ptr< ns3::NetDevice >, ns3::Time, ns3::Time, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, ns3::Ptr< ns3::SixLowPanNetDevice >, uint32_t, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, ns3::UanTxMode, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, ns3::WifiMode, WifiPreamble, uint8_t, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, uint16_t, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, uint16_t, ns3::WifiTxVector, ns3::MpduInfo, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, uint16_t, ns3::WifiTxVector, ns3::MpduInfo, ns3::SignalNoiseDbm, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, uint32_t, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, uint8_t, uint8_t, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::Packet >, WifiPhyRxfailureReason, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::PacketBurst > >, ns3::Callback< void, ns3::Ptr< const ns3::PacketBurst >, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::QueueDiscItem >, const char *, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::QueueDiscItem >, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::SpectrumPhy >, ns3::Ptr< const ns3::SpectrumPhy >, double, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::SpectrumValue >, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::ThreeGppHttpClient >, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::ThreeGppHttpClient >, ns3::Ptr< const ns3::Packet >, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::ThreeGppHttpServer >, ns3::Ptr< ns3::Socket >, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::WifiMacQueueItem >, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const ns3::WifiPsdu >, ns3::WifiTxVector, double, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< const WifiMacQueueItem >, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< ns3::LteUeRrc >, std::list< ns3::LteRrcSap::SCellToAddMod >, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< ns3::Packet > >, ns3::Callback< void, ns3::Ptr< ns3::Packet >, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< ns3::Packet >, ns3::Ipv4Header, uint16_t, ns3::Ptr< ns3::Ipv4Interface > >, ns3::Callback< void, ns3::Ptr< ns3::Packet >, ns3::Ipv6Header, uint16_t, ns3::Ptr< ns3::Ipv6Interface > >, ns3::Callback< void, ns3::Ptr< ns3::Packet >, uint16_t, const ns3::Mac8Address & >, ns3::Callback< void, ns3::Ptr< ns3::Packet const >, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< ns3::PacketBurst >, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< ns3::Socket > >, ns3::Callback< void, ns3::Ptr< ns3::Socket >, const ns3::Address & >, ns3::Callback< void, ns3::Ptr< ns3::Socket >, uint32_t >, ns3::Callback< void, ns3::Ptr< ns3::SpectrumSignalParameters >, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Ptr< ns3::TcpSocketMsgBase > >, ns3::Callback< void, ns3::SequenceNumber, ns3::SequenceNumber, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::TcpTxItem * >, ns3::Callback< void, ns3::Time, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Time, LrWpanPhyEnumeration, LrWpanPhyEnumeration, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Time, ns3::Mac48Address, uint8_t, OriginatorBlockAckAgreement::State, empty, empty, empty, empty >, ns3::Callback< void, ns3::Time, ns3::Time, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::Time, ns3::Time, uint32_t, uint32_t, double, uint32_t, double, empty >, ns3::Callback< void, ns3::Time, ns3::Time, WifiPhyState, empty, empty, empty, empty, empty >, ns3::Callback< void, ns3::WifiMacHeader const & >, ns3::Callback< void, ns3::WifiTxVector, ns3::Time, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, Ptr< const Packet > >, ns3::Callback< void, Ptr< const Packet >, const TcpHeader &, Ptr< const TcpSocketBase > >, ns3::Callback< void, Ptr< const Packet >, Mac48Address, Mac48Address >, ns3::Callback< void, Ptr< const TcpSocketBase >, const SequenceNumber32 &, uint32_t, bool >, ns3::Callback< void, Ptr< const TcpSocketState >, Ptr< const TcpSocketBase > >, ns3::Callback< void, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address &, const Address &, NetDevice::PacketType >, ns3::Callback< void, Ptr< Packet > >, ns3::Callback< void, Ptr< Packet >, Ipv4Address, Ipv4Address, uint8_t, Ptr< Ipv4Route > >, ns3::Callback< void, Ptr< Packet >, Ipv6Address, Ipv6Address, uint8_t, Ptr< Ipv6Route > >, ns3::Callback< void, Ptr< WifiMacQueueItem > >, ns3::Callback< void, Ptr< WifiPsdu > >, ns3::Callback< void, Ptr< WifiPsdu >, double, WifiTxVector, std::vector< bool > >, ns3::Callback< void, State, State, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, std::list< Ptr< LteControlMessage > > >, ns3::Callback< void, struct ns3::dot11s::RouteChange, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, SuperframeStatus, SuperframeStatus, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, T, T, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, TcpCongState_t, TcpCongState_t, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, TcpSocketState::EcnState_t, TcpSocketState::EcnState_t, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, TcpSocketState::TcpCongState_t, TcpSocketState::TcpCongState_t, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, TcpStates_t, TcpStates_t, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, uint16_t, ns3::Ptr< ns3::SpectrumValue >, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, uint16_t, Ptr< SpectrumValue > >, ns3::Callback< void, uint16_t, uint16_t >, ns3::Callback< void, uint16_t, uint16_t, double, double, bool, uint8_t, empty, empty >, ns3::Callback< void, uint16_t, uint16_t, double, double, uint8_t, empty, empty, empty >, ns3::Callback< void, uint16_t, uint16_t, double, empty, empty, empty, empty, empty >, ns3::Callback< void, uint16_t, uint16_t, double, uint8_t, empty, empty, empty, empty >, ns3::Callback< void, uint16_t, uint16_t, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, uint16_t, uint16_t, State, State, empty, empty, empty, empty >, ns3::Callback< void, uint16_t, uint8_t, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, uint16_t, uint8_t, uint32_t, empty, empty, empty, empty, empty >, ns3::Callback< void, uint16_t, uint8_t, uint32_t, uint64_t, empty, empty, empty, empty >, ns3::Callback< void, uint32_t >, ns3::Callback< void, uint32_t, empty, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, uint32_t, Mac48Address, Mac48Address, PeerLink::PeerState, PeerLink::PeerState >, ns3::Callback< void, uint32_t, Ptr< Packet >, uint8_t >, ns3::Callback< void, uint32_t, uint32_t, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, uint32_t, uint32_t, uint16_t, uint8_t, uint16_t, uint8_t, empty, empty >, ns3::Callback< void, uint64_t, bool, uint8_t, uint8_t, empty, empty, empty, empty >, ns3::Callback< void, uint64_t, uint16_t, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, uint64_t, uint16_t, uint16_t, empty, empty, empty, empty, empty >, ns3::Callback< void, uint64_t, uint16_t, uint16_t, ns3::LteRrcSap::MeasurementReport, empty, empty, empty, empty >, ns3::Callback< void, uint64_t, uint16_t, uint16_t, State, State, empty, empty, empty >, ns3::Callback< void, uint64_t, uint16_t, uint16_t, std::string, empty, empty, empty, empty >, ns3::Callback< void, uint64_t, uint16_t, uint16_t, std::string, uint8_t, empty, empty, empty >, ns3::Callback< void, uint64_t, uint16_t, uint16_t, uint16_t, empty, empty, empty, empty >, ns3::Callback< void, uint64_t, uint16_t, uint16_t, uint8_t, empty, empty, empty, empty >, ns3::Callback< void, uint64_t, uint64_t, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, uint8_t *, ssize_t >, ns3::Callback< void, uint8_t >, ns3::Callback< void, uint8_t, bool, ns3::Time, ns3::Ptr< ns3::Packet >, empty, empty, empty, empty >, ns3::Callback< void, uint8_t, double, bool, double, double, empty, empty, empty >, ns3::Callback< void, uint8_t, uint8_t, empty, empty, empty, empty, empty, empty >, ns3::Callback< void, UlInfoListElement_s >, and ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >.
Public Member Functions
CallbackBase ()
Ptr< CallbackImplBase > GetImpl (void) const
Protected Member Functions
CallbackBase (Ptr< CallbackImplBase > impl)
Construct from a pimpl.
Protected Attributes
Ptr< CallbackImplBase > m_impl
the pimpl
Detailed Description
Base class for Callback class. Provides pimpl abstraction.
Definition at line 1194 of file callback.h.
Constructor & Destructor Documentation
CallbackBase() [1/2]
ns3::CallbackBase::CallbackBase () inline
Definition at line 1197 of file callback.h.
CallbackBase() [2/2]
ns3::CallbackBase::CallbackBase (Ptr< CallbackImplBase > impl) inline protected
Construct from a pimpl.
Parameters
[in] impl The CallbackImplBase Ptr
Definition at line 1210 of file callback.h.
Member Function Documentation
GetImpl()
Ptr<CallbackImplBase> ns3::CallbackBase::GetImpl (void) const inline
Returns
The impl pointer
Definition at line 1200 of file callback.h.
References m_impl.
Referenced by ns3::Callback< void, ns3::Time, ns3::Time, WifiPhyState, empty, empty, empty, empty, empty >::Assign(), ns3::Callback< void, ns3::Time, ns3::Time, WifiPhyState, empty, empty, empty, empty, empty >::CheckType(), ns3::Callback< void, ns3::Time, ns3::Time, WifiPhyState, empty, empty, empty, empty, empty >::IsEqual(), and ns3::CallbackValue::SerializeToString().
Member Data Documentation
m_impl
Ptr<CallbackImplBase> ns3::CallbackBase::m_impl protected
the pimpl
Definition at line 1212 of file callback.h.
Referenced by ns3::Callback< void, ns3::Time, ns3::Time, WifiPhyState, empty, empty, empty, empty, empty >::DoAssign(), ns3::Callback< void, ns3::Time, ns3::Time, WifiPhyState, empty, empty, empty, empty, empty >::DoPeekImpl(), GetImpl(), ns3::Callback< void, ns3::Time, ns3::Time, WifiPhyState, empty, empty, empty, empty, empty >::IsEqual(), and ns3::Callback< void, ns3::Time, ns3::Time, WifiPhyState, empty, empty, empty, empty, empty >::Nullify().
The documentation for this class was generated from the following file:
src/core/model/callback.h