ns-3: ns3::FlowIdTag Class Reference
ns3::FlowIdTag Class Reference
#include "flow-id-tag.h"
Public Member Functions
FlowIdTag ()
FlowIdTag (uint32_t flowId)
Constructs a FlowIdTag with the given flow id.
virtual void Deserialize (TagBuffer buf)
uint32_t GetFlowId (void) const
Gets the flow id for the tag.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer buf) const
void SetFlowId (uint32_t flowId)
Sets the flow id for the tag.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static uint32_t AllocateFlowId (void)
Uses a static variable to generate sequential flow id.
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint32_t m_flowId
Flow ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 27 of file flow-id-tag.h.
Constructor & Destructor Documentation
FlowIdTag() [1/2]
ns3::FlowIdTag::FlowIdTag ()
Definition at line 68 of file flow-id-tag.cc.
References NS_LOG_FUNCTION.
FlowIdTag() [2/2]
ns3::FlowIdTag::FlowIdTag (uint32_t flowId)
Constructs a FlowIdTag with the given flow id.
Parameters
flowId Id to use for the tag
Definition at line 74 of file flow-id-tag.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AllocateFlowId()
uint32_t ns3::FlowIdTag::AllocateFlowId (void) static
Uses a static variable to generate sequential flow id.
Returns
flow id allocated
Definition at line 95 of file flow-id-tag.cc.
References NS_LOG_FUNCTION_NOARGS.
Deserialize()
void ns3::FlowIdTag::Deserialize (TagBuffer i) virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 57 of file flow-id-tag.cc.
References m_flowId, NS_LOG_FUNCTION, and ns3::TagBuffer::ReadU32().
GetFlowId()
uint32_t ns3::FlowIdTag::GetFlowId (void) const
Gets the flow id for the tag.
Returns
current flow id for this tag
Definition at line 88 of file flow-id-tag.cc.
References m_flowId, and NS_LOG_FUNCTION.
Referenced by CollisionExperiment::Receive().
GetInstanceTypeId()
TypeId ns3::FlowIdTag::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 40 of file flow-id-tag.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::FlowIdTag::GetSerializedSize (void) const virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 45 of file flow-id-tag.cc.
References NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::FlowIdTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 30 of file flow-id-tag.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::FlowIdTag::Print (std::ostream & os) const virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 63 of file flow-id-tag.cc.
References m_flowId, and NS_LOG_FUNCTION.
Serialize()
void ns3::FlowIdTag::Serialize (TagBuffer i) const virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 51 of file flow-id-tag.cc.
References m_flowId, NS_LOG_FUNCTION, and ns3::TagBuffer::WriteU32().
SetFlowId()
void ns3::FlowIdTag::SetFlowId (uint32_t flowId)
Sets the flow id for the tag.
Parameters
flowId Id to assign to the tag
Definition at line 82 of file flow-id-tag.cc.
References m_flowId, and NS_LOG_FUNCTION.
Member Data Documentation
m_flowId
uint32_t ns3::FlowIdTag::m_flowId private
Flow ID.
Definition at line 64 of file flow-id-tag.h.
Referenced by Deserialize(), GetFlowId(), Print(), Serialize(), and SetFlowId().
The documentation for this class was generated from the following files:
src/network/utils/flow-id-tag.h
src/network/utils/flow-id-tag.cc