ns-3: FqCoDelQueueDiscIPFlowsSeparationAndPacketLimit Class Reference
FqCoDelQueueDiscIPFlowsSeparationAndPacketLimit Class Reference
This class tests the IP flows separation and the packet limit.
Public Member Functions
FqCoDelQueueDiscIPFlowsSeparationAndPacketLimit ()
virtual ~FqCoDelQueueDiscIPFlowsSeparationAndPacketLimit ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void AddPacket (Ptr< FqCoDelQueueDisc > queue, Ipv4Header hdr)
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
This class tests the IP flows separation and the packet limit.
Definition at line 136 of file fq-codel-queue-disc-test-suite.cc.
Constructor & Destructor Documentation
FqCoDelQueueDiscIPFlowsSeparationAndPacketLimit()
FqCoDelQueueDiscIPFlowsSeparationAndPacketLimit::FqCoDelQueueDiscIPFlowsSeparationAndPacketLimit ()
Definition at line 147 of file fq-codel-queue-disc-test-suite.cc.
~FqCoDelQueueDiscIPFlowsSeparationAndPacketLimit()
FqCoDelQueueDiscIPFlowsSeparationAndPacketLimit::~FqCoDelQueueDiscIPFlowsSeparationAndPacketLimit () virtual
Definition at line 152 of file fq-codel-queue-disc-test-suite.cc.
Member Function Documentation
AddPacket()
void FqCoDelQueueDiscIPFlowsSeparationAndPacketLimit::AddPacket (Ptr< FqCoDelQueueDisc > queue, Ipv4Header hdr) private
Definition at line 157 of file fq-codel-queue-disc-test-suite.cc.
References ns3::QueueDisc::Enqueue().
Referenced by DoRun().
DoRun()
void FqCoDelQueueDiscIPFlowsSeparationAndPacketLimit::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 166 of file fq-codel-queue-disc-test-suite.cc.
References AddPacket(), ns3::QueueDisc::GetQueueDiscClass(), ns3::Object::Initialize(), NS_TEST_ASSERT_MSG_EQ, ns3::Ipv4Header::SetDestination(), ns3::Ipv4Header::SetPayloadSize(), ns3::Ipv4Header::SetProtocol(), ns3::FqCoDelQueueDisc::SetQuantum(), and ns3::Ipv4Header::SetSource().
The documentation for this class was generated from the following file:
src/test/ns3tc/fq-codel-queue-disc-test-suite.cc