ns-3: ns3::RttEstimator Class Reference
ns3::RttEstimator Class Reference abstract
Internet » TCP
Base class for all RTT Estimators.
#include "rtt-estimator.h"
Public Member Functions
RttEstimator ()
RttEstimator (const RttEstimator &r)
Copy constructor.
virtual ~RttEstimator ()
virtual Ptr< RttEstimator > Copy () const =0
Copy object (including current internal state)
Time GetEstimate (void) const
gets the RTT estimate.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint32_t GetNSamples (void) const
gets the number of samples used in the estimates
Time GetVariation (void) const
Note that this is not a formal statistical variance; it has the the same units as the estimate.
virtual void Measurement (Time t)=0
Add a new measurement to the estimator.
virtual void Reset ()
Resets the estimation to its initial state.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Attributes
Time m_estimatedRtt
Current estimate.
Time m_estimatedVariation
Current estimate variation.
uint32_t m_nSamples
Number of samples.
Private Attributes
Time m_initialEstimatedRtt
Initial RTT estimation.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Base class for all RTT Estimators.
The RTT Estimator class computes an estimate of the round trip time observed in a series of Time measurements. The estimate is provided in the form of an estimate and a sample variation. Subclasses can implement different algorithms to provide values for the estimate and variation.
Definition at line 43 of file rtt-estimator.h.
Constructor & Destructor Documentation
RttEstimator() [1/2]
ns3::RttEstimator::RttEstimator ()
Definition at line 74 of file rtt-estimator.cc.
References ns3::ObjectBase::ConstructSelf(), ns3::Time::GetSeconds(), m_estimatedRtt, m_estimatedVariation, m_initialEstimatedRtt, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
RttEstimator() [2/2]
ns3::RttEstimator::RttEstimator (const RttEstimator & r)
Copy constructor.
Parameters
r the object to copy
Definition at line 87 of file rtt-estimator.cc.
References NS_LOG_FUNCTION.
~RttEstimator()
ns3::RttEstimator::~RttEstimator () virtual
Definition at line 97 of file rtt-estimator.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Copy()
virtual Ptr<RttEstimator> ns3::RttEstimator::Copy () const pure virtual
Copy object (including current internal state)
Returns
a copy of itself
Implemented in ns3::RttMeanDeviation.
GetEstimate()
Time ns3::RttEstimator::GetEstimate (void) const
gets the RTT estimate.
Returns
The RTT estimate.
Definition at line 60 of file rtt-estimator.cc.
References m_estimatedRtt.
Referenced by RttEstimatorTestCase::CheckValues(), RttEstimatorTestCase::CheckValuesWithTolerance(), RttEstimatorTestCase::DoRun(), TcpTimeRtoTest::Tx(), and TcpRttEstimationTest::Tx().
GetInstanceTypeId()
TypeId ns3::RttEstimator::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Reimplemented from ns3::Object.
Reimplemented in ns3::RttMeanDeviation.
Definition at line 103 of file rtt-estimator.cc.
References GetTypeId().
GetNSamples()
uint32_t ns3::RttEstimator::GetNSamples (void) const
gets the number of samples used in the estimates
Returns
the number of samples used in the estimates
Definition at line 118 of file rtt-estimator.cc.
References m_nSamples.
Referenced by RttEstimatorTestCase::DoRun().
GetTypeId()
TypeId ns3::RttEstimator::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 45 of file rtt-estimator.cc.
References m_initialEstimatedRtt, ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::Seconds(), and ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
GetVariation()
Time ns3::RttEstimator::GetVariation (void) const
Note that this is not a formal statistical variance; it has the the same units as the estimate.
Mean deviation or standard deviation are example quantities that could be provided here.
gets the RTT estimate variation.
Returns
The RTT estimate variation.
Definition at line 66 of file rtt-estimator.cc.
References m_estimatedVariation.
Referenced by RttEstimatorTestCase::CheckValues(), RttEstimatorTestCase::CheckValuesWithTolerance(), RttEstimatorTestCase::DoRun(), and TcpTimeRtoTest::Tx().
Measurement()
virtual void ns3::RttEstimator::Measurement (Time t) pure virtual
Add a new measurement to the estimator.
Pure virtual function.
Parameters
t the new RTT measure.
Implemented in ns3::RttMeanDeviation.
Referenced by RttEstimatorTestCase::CheckValues(), and RttEstimatorTestCase::CheckValuesWithTolerance().
Reset()
void ns3::RttEstimator::Reset () virtual
Resets the estimation to its initial state.
Reimplemented in ns3::RttMeanDeviation.
Definition at line 108 of file rtt-estimator.cc.
References m_estimatedRtt, m_estimatedVariation, m_initialEstimatedRtt, m_nSamples, and NS_LOG_FUNCTION.
Referenced by ns3::RttMeanDeviation::Reset().
Member Data Documentation
m_estimatedRtt
Time ns3::RttEstimator::m_estimatedRtt protected
Current estimate.
Definition at line 105 of file rtt-estimator.h.
Referenced by RttEstimator(), ns3::RttMeanDeviation::FloatingPointUpdate(), GetEstimate(), ns3::RttMeanDeviation::IntegerUpdate(), ns3::RttMeanDeviation::Measurement(), and Reset().
m_estimatedVariation
Time ns3::RttEstimator::m_estimatedVariation protected
Current estimate variation.
Definition at line 106 of file rtt-estimator.h.
Referenced by RttEstimator(), ns3::RttMeanDeviation::FloatingPointUpdate(), GetVariation(), ns3::RttMeanDeviation::IntegerUpdate(), ns3::RttMeanDeviation::Measurement(), and Reset().
m_initialEstimatedRtt
Time ns3::RttEstimator::m_initialEstimatedRtt private
Initial RTT estimation.
Definition at line 102 of file rtt-estimator.h.
Referenced by RttEstimator(), GetTypeId(), and Reset().
m_nSamples
uint32_t ns3::RttEstimator::m_nSamples protected
Number of samples.
Definition at line 107 of file rtt-estimator.h.
Referenced by GetNSamples(), ns3::RttMeanDeviation::Measurement(), and Reset().
The documentation for this class was generated from the following files:
src/internet/model/rtt-estimator.h
src/internet/model/rtt-estimator.cc