ns-3: ns3::TcpOptionSackPermitted Class Reference
ns3::TcpOptionSackPermitted Class Reference
Defines the TCP option of kind 4 (selective acknowledgment permitted option) as in RFC 2018
#include "tcp-option-sack-permitted.h"
Public Member Functions
TcpOptionSackPermitted ()
virtual ~TcpOptionSackPermitted ()
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the Option from a buffer iterator.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint8_t GetKind (void) const
Get the ‘kind’ (as in RFC 793) of this option.
virtual uint32_t GetSerializedSize (void) const
Returns number of bytes required for Option serialization.
virtual void Print (std::ostream &os) const
Print the Option contents.
virtual void Serialize (Buffer::Iterator start) const
Serialize the Option to a buffer iterator.
Public Member Functions inherited from ns3::TcpOption
TcpOption ()
virtual ~TcpOption ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpOption
static Ptr< TcpOption > CreateOption (uint8_t kind)
Creates an option.
static TypeId GetTypeId (void)
Get the type ID.
static bool IsKindKnown (uint8_t kind)
Check if the option is implemented.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Public Types inherited from ns3::TcpOption
enum Kind {
END = 0, NOP = 1, MSS = 2, WINSCALE = 3,
SACKPERMITTED = 4, SACK = 5, TS = 8, UNKNOWN = 255
}
The option Kind, as defined in the respective RFCs.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Defines the TCP option of kind 4 (selective acknowledgment permitted option) as in RFC 2018
TCP Sack-Permitted Option is 2-byte in length and sent in a SYN segment by a TCP host that can recognize and process SACK option during the lifetime of a connection.
Definition at line 42 of file tcp-option-sack-permitted.h.
Constructor & Destructor Documentation
TcpOptionSackPermitted()
ns3::TcpOptionSackPermitted::TcpOptionSackPermitted ()
Definition at line 35 of file tcp-option-sack-permitted.cc.
~TcpOptionSackPermitted()
ns3::TcpOptionSackPermitted::~TcpOptionSackPermitted () virtual
Definition at line 40 of file tcp-option-sack-permitted.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::TcpOptionSackPermitted::Deserialize (Buffer::Iterator start) virtual
Deserialize the Option from a buffer iterator.
Parameters
start the buffer iterator
Returns
the number of deserialized bytes
Implements ns3::TcpOption.
Definition at line 82 of file tcp-option-sack-permitted.cc.
References GetKind(), GetSerializedSize(), NS_LOG_WARN, ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetInstanceTypeId()
TypeId ns3::TcpOptionSackPermitted::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Reimplemented from ns3::TcpOption.
Definition at line 56 of file tcp-option-sack-permitted.cc.
References GetTypeId().
GetKind()
uint8_t ns3::TcpOptionSackPermitted::GetKind (void) const virtual
Get the ‘kind’ (as in RFC 793) of this option.
Returns
the Option Kind
Implements ns3::TcpOption.
Definition at line 103 of file tcp-option-sack-permitted.cc.
References ns3::TcpOption::SACKPERMITTED.
Referenced by Deserialize(), and Serialize().
GetSerializedSize()
uint32_t ns3::TcpOptionSackPermitted::GetSerializedSize (void) const virtual
Returns number of bytes required for Option serialization.
Returns
number of bytes required for Option serialization
Implements ns3::TcpOption.
Definition at line 68 of file tcp-option-sack-permitted.cc.
Referenced by Deserialize().
GetTypeId()
TypeId ns3::TcpOptionSackPermitted::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 45 of file tcp-option-sack-permitted.cc.
References ns3::TypeId::SetParent().
Referenced by ns3::TcpOption::CreateOption(), and GetInstanceTypeId().
Print()
void ns3::TcpOptionSackPermitted::Print (std::ostream & os) const virtual
Print the Option contents.
Parameters
os the output stream
Implements ns3::TcpOption.
Definition at line 62 of file tcp-option-sack-permitted.cc.
Serialize()
void ns3::TcpOptionSackPermitted::Serialize (Buffer::Iterator start) const virtual
Serialize the Option to a buffer iterator.
Parameters
start the buffer iterator
Implements ns3::TcpOption.
Definition at line 74 of file tcp-option-sack-permitted.cc.
References GetKind(), visualizer.core::start(), and ns3::Buffer::Iterator::WriteU8().
The documentation for this class was generated from the following files:
src/internet/model/tcp-option-sack-permitted.h
src/internet/model/tcp-option-sack-permitted.cc