ns-3: EpcS1uDlTestCase Class Reference
EpcS1uDlTestCase Class Reference
LTE Models » lte module tests | Test suites
EpcS1uDlTestCase class.
Public Member Functions
EpcS1uDlTestCase (std::string name, std::vector< EnbDlTestData > v)
Constructor.
virtual ~EpcS1uDlTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
std::vector< EnbDlTestData > m_enbDlTestData
ENB DL test data.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
EpcS1uDlTestCase class.
Definition at line 98 of file epc-test-s1u-downlink.cc.
Constructor & Destructor Documentation
EpcS1uDlTestCase()
EpcS1uDlTestCase::EpcS1uDlTestCase (std::string name, std::vector< EnbDlTestData > v)
Constructor.
Parameters
name the name of the test case instance
v list of eNodeB downlink test data information
Definition at line 116 of file epc-test-s1u-downlink.cc.
~EpcS1uDlTestCase()
EpcS1uDlTestCase::~EpcS1uDlTestCase () virtual
Definition at line 122 of file epc-test-s1u-downlink.cc.
Member Function Documentation
DoRun()
void EpcS1uDlTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 126 of file epc-test-s1u-downlink.cc.
References ns3::NoBackhaulEpcHelper::ActivateEpsBearer(), ns3::NodeContainer::Add(), ns3::PointToPointEpcHelper::AddEnb(), ns3::Ipv4StaticRouting::AddNetworkRouteTo(), ns3::NoBackhaulEpcHelper::AddUe(), ns3::Object::AggregateObject(), ns3::Ipv4AddressHelper::Assign(), ns3::NoBackhaulEpcHelper::AssignUeIpv4Address(), ns3::NodeContainer::Create(), ns3::ApplicationContainer::Get(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::Node::GetApplication(), ns3::NetDeviceContainer::GetN(), ns3::NodeContainer::GetN(), ns3::Object::GetObject(), ns3::NoBackhaulEpcHelper::GetPgwNode(), ns3::EpcEnbApplication::GetS1SapProvider(), ns3::EpcTestRrc::GetS1SapUser(), ns3::Ipv4StaticRoutingHelper::GetStaticRouting(), ns3::PointToPointHelper::Install(), ns3::PacketSinkHelper::Install(), ns3::UdpEchoClientHelper::Install(), ns3::CsmaHelper::Install(), ns3::InternetStackHelper::Install(), m_enbDlTestData, ns3::MilliSeconds(), NS_ASSERT_MSG(), NS_TEST_ASSERT_MSG_EQ, port, ns3::Seconds(), ns3::UdpEchoClientHelper::SetAttribute(), ns3::ObjectBase::SetAttribute(), ns3::Ipv4AddressHelper::SetBase(), ns3::Config::SetDefault(), ns3::PointToPointHelper::SetDeviceAttribute(), ns3::EpcTestRrc::SetS1SapProvider(), ns3::EpcEnbApplication::SetS1SapUser(), ns3::ApplicationContainer::Start(), and ns3::ApplicationContainer::Stop().
Member Data Documentation
m_enbDlTestData
std::vector<EnbDlTestData> EpcS1uDlTestCase::m_enbDlTestData private
ENB DL test data.
Definition at line 112 of file epc-test-s1u-downlink.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/lte/test/epc-test-s1u-downlink.cc