ns-3: ns3::ForwarderHelper Class Reference
ns3::ForwarderHelper Class Reference
This class can be used to install Forwarder applications on a set of gateways.
#include "forwarder-helper.h"
Public Member Functions
ForwarderHelper ()
~ForwarderHelper ()
ApplicationContainer Install (NodeContainer c) const
ApplicationContainer Install (Ptr< Node > node) const
void SetAttribute (std::string name, const AttributeValue &value)
Private Member Functions
Ptr< Application > InstallPriv (Ptr< Node > node) const
Private Attributes
ObjectFactory m_factory
Detailed Description
This class can be used to install Forwarder applications on a set of gateways.
Definition at line 40 of file forwarder-helper.h.
Constructor & Destructor Documentation
ForwarderHelper()
ns3::ForwarderHelper::ForwarderHelper ()
Definition at line 34 of file forwarder-helper.cc.
References m_factory, and ns3::ObjectFactory::SetTypeId().
~ForwarderHelper()
ns3::ForwarderHelper::~ForwarderHelper ()
Definition at line 39 of file forwarder-helper.cc.
Member Function Documentation
Install() [1/2]
ApplicationContainer ns3::ForwarderHelper::Install (NodeContainer c) const
Definition at line 56 of file forwarder-helper.cc.
References ns3::ApplicationContainer::Add(), ns3::NodeContainer::Begin(), ns3::NodeContainer::End(), and InstallPriv().
Install() [2/2]
ApplicationContainer ns3::ForwarderHelper::Install (Ptr< Node > node) const
Definition at line 50 of file forwarder-helper.cc.
References InstallPriv().
InstallPriv()
Ptr< Application > ns3::ForwarderHelper::InstallPriv (Ptr< Node > node) const private
Definition at line 68 of file forwarder-helper.cc.
References ns3::Node::AddApplication(), ns3::ObjectFactory::Create(), ns3::Node::GetDevice(), ns3::Node::GetNDevices(), m_factory, ns3::MakeCallback(), NS_LOG_ERROR, NS_LOG_FUNCTION, ns3::Forwarder::ReceiveFromLora(), and ns3::Forwarder::ReceiveFromPointToPoint().
Referenced by Install().
SetAttribute()
void ns3::ForwarderHelper::SetAttribute (std::string name, const AttributeValue & value)
Definition at line 44 of file forwarder-helper.cc.
References m_factory, and ns3::ObjectFactory::Set().
Member Data Documentation
m_factory
ObjectFactory ns3::ForwarderHelper::m_factory private
Definition at line 56 of file forwarder-helper.h.
Referenced by ForwarderHelper(), InstallPriv(), and SetAttribute().
The documentation for this class was generated from the following files:
src/lorawan/helper/forwarder-helper.h
src/lorawan/helper/forwarder-helper.cc