ns-3: HwmpDoRfRegressionTest Class Reference
HwmpDoRfRegressionTest Class Reference
Mesh Device » mesh module tests » dot11s sub-module tests | Test suites
This is a test for intermediate reply and saving routing information about neighbour. 4 stations and 3 UDP ping streams are initiated.
#include "hwmp-target-flags-regression.h"
Public Member Functions
HwmpDoRfRegressionTest ()
virtual ~HwmpDoRfRegressionTest ()
void CheckResults ()
Check results function.
virtual void DoRun ()
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CreateDevices ()
Create devices function.
void CreateNodes ()
Create nodes function.
void HandleReadClient (Ptr< Socket > socket)
Handle a packet reception.
void HandleReadServer (Ptr< Socket > socket)
Handle a packet reception.
void InstallApplications ()
Install application function.
void ResetPosition ()
Reset position function.
void SendDataA (Ptr< Socket > socket)
Send data A.
void SendDataB (Ptr< Socket > socket)
Send data B.
void SendDataC (Ptr< Socket > socket)
Send data C.
Private Attributes
Ptr< Socket > m_clientSocketA
Client-side socket.
Ptr< Socket > m_clientSocketB
Client-side socket.
Ptr< Socket > m_clientSocketC
Client-side socket.
Ipv4InterfaceContainer m_interfaces
interfaces
NodeContainer * m_nodes
uint32_t m_sentPktsCounterA
sent packets counter A
uint32_t m_sentPktsCounterB
sent packets counter B
uint32_t m_sentPktsCounterC
sent packets counter C
Ptr< Socket > m_serverSocketA
Server-side socket.
Ptr< Socket > m_serverSocketB
Server-side socket.
Time m_time
Simulation time.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
This is a test for intermediate reply and saving routing information about neighbour. 4 stations and 3 UDP ping streams are initiated.
*  <-----------|----------->   Broadcast frame
*              |----------->|  Unicast frame
*            10          11            12           13
*             |            |<-----------|----------->|             ARP request (12 asks who has 10)
*             |            |            |<-----------|-----------> ARP request
*             |<-----------|----------->|            |             ARP request
* <-----------|----------->|            |            |             PREQ
*             |<-----------|----------->|            |             PREQ
*             |            |<-----------|            |             PREP
*             |<-----------|            |            |             PREP
*             |----------->|            |            |             ARP reply
*             |            |----------->|            |             ARP REPLY
*             |            |<-----------|            |             Data
*             |............|............|............|
*             |<-----------|----------->|            |             ARP request (11 asks who has 10)
*             |............|............|............|
*             |----------->|            |            |             ARP reply
*                  ^ Note, that this arp reply goes without route
*                  discovery procedure, because route is known from
*                  previous PREQ/PREP exchange
*             |<-----------|            |            |             DATA
*             |............|............|............|
* <-----------|----------->|            |            |             ARP request (10 asks who has 13)
*             |............|............|............|
*             |            |            |<-----------|-----------> PREQ (13 asks about 10) DO=0 RF=1
*             |            |            |----------->|             PREP (intermediate reply - 12 knows about 10)
*             |            |<-----------|----------->|             PREQ DO=1 RF=0
*             |............|............|............|
*             |----------->|            |            |             PREP
*             |            |----------->|            |             PREP
*             |            |            |----------->|             PREP
*
Definition at line 69 of file hwmp-target-flags-regression.h.
Constructor & Destructor Documentation
HwmpDoRfRegressionTest()
HwmpDoRfRegressionTest::HwmpDoRfRegressionTest ()
Definition at line 45 of file hwmp-target-flags-regression.cc.
~HwmpDoRfRegressionTest()
HwmpDoRfRegressionTest::~HwmpDoRfRegressionTest () virtual
Definition at line 54 of file hwmp-target-flags-regression.cc.
References m_nodes.
Member Function Documentation
CheckResults()
void HwmpDoRfRegressionTest::CheckResults ()
Check results function.
Definition at line 168 of file hwmp-target-flags-regression.cc.
References NS_PCAP_TEST_EXPECT_EQ, and PREFIX.
Referenced by DoRun().
CreateDevices()
void HwmpDoRfRegressionTest::CreateDevices () private
Create devices function.
Definition at line 133 of file hwmp-target-flags-regression.cc.
References first::address, ns3::MeshHelper::AssignStreams(), ns3::InternetStackHelper::AssignStreams(), ns3::YansWifiChannelHelper::AssignStreams(), ns3::YansWifiChannelHelper::Create(), ns3::TestCase::CreateTempDirFilename(), ns3::PcapHelperForDevice::EnablePcapAll(), ns3::NetDeviceContainer::GetN(), ns3::MeshHelper::Install(), ns3::InternetStackHelper::Install(), m_interfaces, m_nodes, NS_TEST_ASSERT_MSG_EQ, PREFIX, ns3::Seconds(), ns3::YansWifiPhyHelper::SetChannel(), ns3::WifiPhyHelper::SetErrorRateModel(), ns3::MeshHelper::SetMacType(), ns3::MeshHelper::SetNumberOfInterfaces(), and ns3::MeshHelper::SetStackInstaller().
Referenced by DoRun().
CreateNodes()
void HwmpDoRfRegressionTest::CreateNodes () private
Create nodes function.
Definition at line 78 of file hwmp-target-flags-regression.cc.
References ns3::NodeContainer::Create(), m_nodes, and third::mobility.
Referenced by DoRun().
DoRun()
void HwmpDoRfRegressionTest::DoRun () virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 60 of file hwmp-target-flags-regression.cc.
References CheckResults(), CreateDevices(), CreateNodes(), InstallApplications(), m_nodes, and m_time.
HandleReadClient()
void HwmpDoRfRegressionTest::HandleReadClient (Ptr< Socket > socket) private
Handle a packet reception.
This function is called by lower layers.
Parameters
socket the socket the packet was received to.
Definition at line 227 of file hwmp-target-flags-regression.cc.
References ns3::Socket::RecvFrom().
Referenced by InstallApplications().
HandleReadServer()
void HwmpDoRfRegressionTest::HandleReadServer (Ptr< Socket > socket) private
Handle a packet reception.
This function is called by lower layers.
Parameters
socket the socket the packet was received to.
Definition at line 213 of file hwmp-target-flags-regression.cc.
References ns3::Socket::RecvFrom(), ns3::Packet::RemoveAllByteTags(), ns3::Packet::RemoveAllPacketTags(), and ns3::Socket::SendTo().
Referenced by InstallApplications().
InstallApplications()
void HwmpDoRfRegressionTest::InstallApplications () private
Install application function.
Definition at line 95 of file hwmp-target-flags-regression.cc.
References ns3::Socket::Bind(), ns3::Socket::Connect(), ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::Node::GetId(), ns3::Socket::GetNode(), HandleReadClient(), HandleReadServer(), m_clientSocketA, m_clientSocketB, m_interfaces, m_nodes, m_serverSocketA, m_serverSocketB, ns3::MakeCallback(), ns3::Seconds(), SendDataA(), SendDataB(), SendDataC(), and ns3::Socket::SetRecvCallback().
Referenced by DoRun().
ResetPosition()
void HwmpDoRfRegressionTest::ResetPosition () private
Reset position function.
SendDataA()
void HwmpDoRfRegressionTest::SendDataA (Ptr< Socket > socket) private
Send data A.
Parameters
socket the sending socket
Definition at line 177 of file hwmp-target-flags-regression.cc.
References ns3::Node::GetId(), ns3::Socket::GetNode(), m_sentPktsCounterA, m_time, ns3::Now(), ns3::Seconds(), and ns3::Socket::Send().
Referenced by InstallApplications().
SendDataB()
void HwmpDoRfRegressionTest::SendDataB (Ptr< Socket > socket) private
Send data B.
Parameters
socket the sending socket
Definition at line 189 of file hwmp-target-flags-regression.cc.
References ns3::Node::GetId(), ns3::Socket::GetNode(), m_sentPktsCounterA, m_sentPktsCounterB, m_time, ns3::Now(), ns3::Seconds(), and ns3::Socket::Send().
Referenced by InstallApplications().
SendDataC()
void HwmpDoRfRegressionTest::SendDataC (Ptr< Socket > socket) private
Send data C.
Parameters
socket the sending socket
Definition at line 201 of file hwmp-target-flags-regression.cc.
References ns3::Node::GetId(), ns3::Socket::GetNode(), m_sentPktsCounterA, m_sentPktsCounterC, m_time, ns3::Now(), ns3::Seconds(), and ns3::Socket::Send().
Referenced by InstallApplications().
Member Data Documentation
m_clientSocketA
Ptr<Socket> HwmpDoRfRegressionTest::m_clientSocketA private
Client-side socket.
Definition at line 100 of file hwmp-target-flags-regression.h.
Referenced by InstallApplications().
m_clientSocketB
Ptr<Socket> HwmpDoRfRegressionTest::m_clientSocketB private
Client-side socket.
Definition at line 102 of file hwmp-target-flags-regression.h.
Referenced by InstallApplications().
m_clientSocketC
Ptr<Socket> HwmpDoRfRegressionTest::m_clientSocketC private
Client-side socket.
Definition at line 104 of file hwmp-target-flags-regression.h.
m_interfaces
Ipv4InterfaceContainer HwmpDoRfRegressionTest::m_interfaces private
interfaces
Definition at line 84 of file hwmp-target-flags-regression.h.
Referenced by CreateDevices(), and InstallApplications().
m_nodes
NodeContainer* HwmpDoRfRegressionTest::m_nodes private
Internal: It is important to have pointers here
Definition at line 81 of file hwmp-target-flags-regression.h.
Referenced by ~HwmpDoRfRegressionTest(), CreateDevices(), CreateNodes(), DoRun(), and InstallApplications().
m_sentPktsCounterA
uint32_t HwmpDoRfRegressionTest::m_sentPktsCounterA private
sent packets counter A
Definition at line 107 of file hwmp-target-flags-regression.h.
Referenced by SendDataA(), SendDataB(), and SendDataC().
m_sentPktsCounterB
uint32_t HwmpDoRfRegressionTest::m_sentPktsCounterB private
sent packets counter B
Definition at line 109 of file hwmp-target-flags-regression.h.
Referenced by SendDataB().
m_sentPktsCounterC
uint32_t HwmpDoRfRegressionTest::m_sentPktsCounterC private
sent packets counter C
Definition at line 111 of file hwmp-target-flags-regression.h.
Referenced by SendDataC().
m_serverSocketA
Ptr<Socket> HwmpDoRfRegressionTest::m_serverSocketA private
Server-side socket.
Definition at line 96 of file hwmp-target-flags-regression.h.
Referenced by InstallApplications().
m_serverSocketB
Ptr<Socket> HwmpDoRfRegressionTest::m_serverSocketB private
Server-side socket.
Definition at line 98 of file hwmp-target-flags-regression.h.
Referenced by InstallApplications().
m_time
Time HwmpDoRfRegressionTest::m_time private
Simulation time.
Definition at line 83 of file hwmp-target-flags-regression.h.
Referenced by DoRun(), SendDataA(), SendDataB(), and SendDataC().
The documentation for this class was generated from the following files:
src/mesh/test/dot11s/hwmp-target-flags-regression.h
src/mesh/test/dot11s/hwmp-target-flags-regression.cc