ns-3: ns3::PppHeader Class Reference
ns3::PppHeader Class Reference
Point-To-Point Network Device
Packet header for PPP.
#include "ppp-header.h"
Public Member Functions
PppHeader ()
Construct a PPP header.
virtual ~PppHeader ()
Destroy a PPP header.
virtual uint32_t Deserialize (Buffer::Iterator start)
virtual TypeId GetInstanceTypeId (void) const
Get the TypeId of the instance.
uint16_t GetProtocol (void)
Get the protocol type carried by this PPP packet.
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetProtocol (uint16_t protocol)
Set the protocol type carried by this PPP packet.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the TypeId.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint16_t m_protocol
The PPP protocol type of the payload packet.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Packet header for PPP.
This class can be used to add a header to PPP packet. Currently we do not implement any of the state machine in RFC 1661, we just encapsulate the inbound packet send it on. The goal here is not really to implement the point-to-point protocol, but to encapsulate our packets in a known protocol so packet sniffers can parse them.
if PPP is transmitted over a serial link, it will typically be framed in some way derivative of IBM SDLC (HDLC) with all that that entails. Thankfully, we don't have to deal with all of that – we can use our own protocol for getting bits across the serial link which we call an ns3 Packet. What we do have to worry about is being able to capture PPP frames which are understandable by Wireshark. All this means is that we need to teach the PcapWriter about the appropriate data link type (DLT_PPP = 9), and we need to add a PPP header to each packet. Since we are not using framed PPP, this just means prepending the sixteen bit PPP protocol number to the packet. The ns-3 way to do this is via a class that inherits from class Header.
Definition at line 48 of file ppp-header.h.
Constructor & Destructor Documentation
PppHeader()
ns3::PppHeader::PppHeader ()
Construct a PPP header.
Definition at line 32 of file ppp-header.cc.
~PppHeader()
ns3::PppHeader::~PppHeader () virtual
Destroy a PPP header.
Definition at line 36 of file ppp-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::PppHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 89 of file ppp-header.cc.
References GetSerializedSize(), m_protocol, and visualizer.core::start().
GetInstanceTypeId()
TypeId ns3::PppHeader::GetInstanceTypeId (void) const virtual
Get the TypeId of the instance.
Returns
The TypeId for this instance
Implements ns3::ObjectBase.
Definition at line 52 of file ppp-header.cc.
References GetTypeId().
GetProtocol()
uint16_t ns3::PppHeader::GetProtocol (void)
Get the protocol type carried by this PPP packet.
The type numbers to be used are defined in RFC 3818
Returns
the protocol type being carried
Definition at line 102 of file ppp-header.cc.
References m_protocol.
Referenced by ns3::PointToPointNetDevice::ProcessHeader().
GetSerializedSize()
uint32_t ns3::PppHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 77 of file ppp-header.cc.
Referenced by Deserialize().
GetTypeId()
TypeId ns3::PppHeader::GetTypeId (void) static
Get the TypeId.
Returns
The TypeId for this class
Definition at line 41 of file ppp-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::PppHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 58 of file ppp-header.cc.
References m_protocol, and NS_ASSERT_MSG().
Serialize()
void ns3::PppHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 83 of file ppp-header.cc.
References m_protocol, and visualizer.core::start().
SetProtocol()
void ns3::PppHeader::SetProtocol (uint16_t protocol)
Set the protocol type carried by this PPP packet.
The type numbers to be used are defined in RFC 3818
Parameters
protocol the protocol type being carried
Definition at line 96 of file ppp-header.cc.
References m_protocol.
Referenced by ns3::PointToPointNetDevice::AddHeader().
Member Data Documentation
m_protocol
uint16_t ns3::PppHeader::m_protocol private
The PPP protocol type of the payload packet.
Definition at line 105 of file ppp-header.h.
Referenced by Deserialize(), GetProtocol(), Print(), Serialize(), and SetProtocol().
The documentation for this class was generated from the following files:
src/point-to-point/model/ppp-header.h
src/point-to-point/model/ppp-header.cc