ns-3: ns3::SixLowPanBc0 Class Reference
ns3::SixLowPanBc0 Class Reference
6LoWPAN
6LoWPAN BC0 header - see RFC 4944.
#include "sixlowpan-header.h"
Public Member Functions
SixLowPanBc0 (void)
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
virtual TypeId GetInstanceTypeId (void) const
Return the instance type identifier.
uint8_t GetSequenceNumber (void) const
Get the "Sequence Number" field.
virtual uint32_t GetSerializedSize (void) const
Get the serialized size of the packet.
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetSequenceNumber (uint8_t seqNumber)
Set the "Sequence Number" field.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_seqNumber
Sequence number.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
6LoWPAN BC0 header - see RFC 4944.
Definition at line 1243 of file sixlowpan-header.h.
Constructor & Destructor Documentation
SixLowPanBc0()
ns3::SixLowPanBc0::SixLowPanBc0 (void)
Definition at line 1816 of file sixlowpan-header.cc.
References m_seqNumber.
Member Function Documentation
Deserialize()
uint32_t ns3::SixLowPanBc0::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
[in] start Buffer iterator.
Returns
Size of the packet.
Implements ns3::Header.
Definition at line 1853 of file sixlowpan-header.cc.
References GetSerializedSize(), m_seqNumber, ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetInstanceTypeId()
TypeId ns3::SixLowPanBc0::GetInstanceTypeId (void) const virtual
Return the instance type identifier.
Returns
Instance type ID.
Implements ns3::ObjectBase.
Definition at line 1830 of file sixlowpan-header.cc.
References GetTypeId().
GetSequenceNumber()
uint8_t ns3::SixLowPanBc0::GetSequenceNumber (void) const
Get the "Sequence Number" field.
Returns
The sequence number value.
Definition at line 1873 of file sixlowpan-header.cc.
References m_seqNumber.
Referenced by ns3::SixLowPanNetDevice::ReceiveFromDevice().
GetSerializedSize()
uint32_t ns3::SixLowPanBc0::GetSerializedSize (void) const virtual
Get the serialized size of the packet.
Returns
Size.
Implements ns3::Header.
Definition at line 1840 of file sixlowpan-header.cc.
Referenced by Deserialize(), and ns3::SixLowPanNetDevice::DoSend().
GetTypeId()
TypeId ns3::SixLowPanBc0::GetTypeId (void) static
Get the type ID.
Returns
The object TypeId.
Definition at line 1821 of file sixlowpan-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::SixLowPanBc0::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 1835 of file sixlowpan-header.cc.
References m_seqNumber.
Referenced by ns3::operator<<().
Serialize()
void ns3::SixLowPanBc0::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
[in] start Buffer iterator.
Implements ns3::Header.
Definition at line 1845 of file sixlowpan-header.cc.
References m_seqNumber, visualizer.core::start(), and ns3::Buffer::Iterator::WriteU8().
SetSequenceNumber()
void ns3::SixLowPanBc0::SetSequenceNumber (uint8_t seqNumber)
Set the "Sequence Number" field.
Parameters
[in] seqNumber The sequence number value.
Definition at line 1868 of file sixlowpan-header.cc.
References m_seqNumber.
Referenced by ns3::SixLowPanNetDevice::DoSend().
Member Data Documentation
m_seqNumber
uint8_t ns3::SixLowPanBc0::m_seqNumber private
Sequence number.
Definition at line 1294 of file sixlowpan-header.h.
Referenced by SixLowPanBc0(), Deserialize(), GetSequenceNumber(), Print(), Serialize(), and SetSequenceNumber().
The documentation for this class was generated from the following files:
src/sixlowpan/model/sixlowpan-header.h
src/sixlowpan/model/sixlowpan-header.cc