ns-3: ns3::UanModesList Class Reference
ns3::UanModesList Class Reference
UAN Models
#include "uan-tx-mode.h"
Public Member Functions
UanModesList ()
Constructor.
virtual ~UanModesList ()
Destructor.
void AppendMode (UanTxMode mode)
Add mode to this list.
void DeleteMode (uint32_t num)
Delete the mode at given index.
uint32_t GetNModes (void) const
Get the number of modes in this list.
UanTxMode operator[] (uint32_t index) const
Retrieve a mode by index.
Private Attributes
std::vector< UanTxMode > m_modes
The vector of modes in this list.
Friends
std::ostream & operator<< (std::ostream &os, const UanModesList &ml)
Write UanModesList to stream os.
std::istream & operator>> (std::istream &is, UanModesList &ml)
Read UanModesList from stream is.
Detailed Description
Container for UanTxModes.
See also
attribute_UanModesList
Definition at line 257 of file uan-tx-mode.h.
Constructor & Destructor Documentation
UanModesList()
ns3::UanModesList::UanModesList ()
Constructor.
Definition at line 222 of file uan-tx-mode.cc.
~UanModesList()
ns3::UanModesList::~UanModesList () virtual
Destructor.
Definition at line 226 of file uan-tx-mode.cc.
References m_modes.
Member Function Documentation
AppendMode()
void ns3::UanModesList::AppendMode (UanTxMode mode)
Add mode to this list.
Parameters
mode The mode to add.
Definition at line 232 of file uan-tx-mode.cc.
References m_modes.
Referenced by Experiment::CreateDualModes(), UanTest::DoPhyTests(), and ns3::UanPhyGen::GetDefaultModes().
DeleteMode()
void ns3::UanModesList::DeleteMode (uint32_t num)
Delete the mode at given index.
Parameters
num Index of mode to delete.
Definition at line 238 of file uan-tx-mode.cc.
References m_modes, and NS_ASSERT.
GetNModes()
uint32_t ns3::UanModesList::GetNModes (void) const
Get the number of modes in this list.
Returns
Number of modes.
Definition at line 259 of file uan-tx-mode.cc.
References m_modes.
Referenced by ns3::UanPhyGen::GetMode(), ns3::UanPhyGen::GetNModes(), and ns3::operator<<().
operator[]()
UanTxMode ns3::UanModesList::operator[] (uint32_t index) const
Retrieve a mode by index.
Parameters
index Mode index.
Returns
Mode at given index.
Definition at line 252 of file uan-tx-mode.cc.
References m_modes, and NS_ASSERT.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const UanModesList & ml) friend
Write UanModesList to stream os.
Parameters
os The output stream.
ml The mode list.
Returns
The stream.
Definition at line 264 of file uan-tx-mode.cc.
operator>>
std::istream& operator>> (std::istream & is, UanModesList & ml) friend
Read UanModesList from stream is.
Parameters
is The input stream.
ml The mode list to fill.
Returns
The stream.
Definition at line 277 of file uan-tx-mode.cc.
Member Data Documentation
m_modes
std::vector<UanTxMode> ns3::UanModesList::m_modes private
The vector of modes in this list.
Definition at line 290 of file uan-tx-mode.h.
Referenced by ~UanModesList(), AppendMode(), DeleteMode(), GetNModes(), ns3::operator<<(), ns3::operator>>(), and operator[]().
The documentation for this class was generated from the following files:
src/uan/model/uan-tx-mode.h
src/uan/model/uan-tx-mode.cc