ns-3: ns3::MobilityBuildingInfo Class Reference
ns3::MobilityBuildingInfo Class Reference
mobility buildings information (to be used by mobility models)
#include "mobility-building-info.h"
Public Member Functions
MobilityBuildingInfo ()
MobilityBuildingInfo (Ptr< Building > building)
Parameterized constructor.
Ptr< Building > GetBuilding ()
Get the building in which the MobilityBuildingInfo instance is located.
uint8_t GetFloorNumber (void)
Get the floor number at which the MobilityBuildingInfo instance is located.
uint8_t GetRoomNumberX (void)
Get the room number along x-axis at which the MobilityBuildingInfo instance is located.
uint8_t GetRoomNumberY (void)
Get the room number along y-axis at which the MobilityBuildingInfo instance is located.
bool IsIndoor (void)
Is indoor method.
NS_DEPRECATED bool IsOutdoor (void)
Is outdoor function.
void MakeConsistent (Ptr< MobilityModel > mm)
Make the given mobility model consistent, by determining whether its position falls inside any of the building in BuildingList, and updating accordingly the BuildingInfo aggregated with the MobilityModel.
void SetIndoor (Ptr< Building > building, uint8_t nfloor, uint8_t nroomx, uint8_t nroomy)
Mark this MobilityBuildingInfo instance as indoor.
void SetIndoor (uint8_t nfloor, uint8_t nroomx, uint8_t nroomy)
Mark this MobilityBuildingInfo instance as indoor.
void SetOutdoor ()
Mark this MobilityBuildingInfo instance as outdoor.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoInitialize ()
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Attributes
Vector m_cachedPosition
The node position cached after making its mobility model consistent.
bool m_indoor
Node position (indoor/outdoor) ?
Ptr< Building > m_myBuilding
Building.
uint8_t m_nFloor
The floor number at which the MobilityBuildingInfo instance is located.
uint8_t m_roomX
The room number along x-axis at which the MobilityBuildingInfo instance is located.
uint8_t m_roomY
The room number along y-axis at which the MobilityBuildingInfo instance is located.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
mobility buildings information (to be used by mobility models)
This model implements the management of scenarios where users might be either indoor (e.g., houses, offices, etc.) and outdoor.
Definition at line 48 of file mobility-building-info.h.
Constructor & Destructor Documentation
MobilityBuildingInfo() [1/2]
ns3::MobilityBuildingInfo::MobilityBuildingInfo ()
Definition at line 56 of file mobility-building-info.cc.
References m_cachedPosition, m_indoor, m_nFloor, m_roomX, m_roomY, and NS_LOG_FUNCTION.
MobilityBuildingInfo() [2/2]
ns3::MobilityBuildingInfo::MobilityBuildingInfo (Ptr< Building > building)
Parameterized constructor.
Parameters
building The building in which the MobilityBuildingInfo instance would be placed
Definition at line 67 of file mobility-building-info.cc.
References m_indoor, m_nFloor, m_roomX, m_roomY, and NS_LOG_FUNCTION.
Member Function Documentation
DoInitialize()
void ns3::MobilityBuildingInfo::DoInitialize () protected virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 48 of file mobility-building-info.cc.
References MakeConsistent(), and NS_LOG_FUNCTION.
GetBuilding()
Ptr< Building > ns3::MobilityBuildingInfo::GetBuilding ()
Get the building in which the MobilityBuildingInfo instance is located.
Returns
The building in which the MobilityBuildingInfo instance is located
Definition at line 171 of file mobility-building-info.cc.
References m_myBuilding, and NS_LOG_FUNCTION.
Referenced by BuildingsHelperOneTestCase::DoRun().
GetFloorNumber()
uint8_t ns3::MobilityBuildingInfo::GetFloorNumber (void)
Get the floor number at which the MobilityBuildingInfo instance is located.
Returns
The floor number
Definition at line 149 of file mobility-building-info.cc.
References m_nFloor, and NS_LOG_FUNCTION.
Referenced by RandomRoomPositionAllocatorTestCase::DoRun(), SameRoomPositionAllocatorTestCase::DoRun(), and BuildingsHelperOneTestCase::DoRun().
GetRoomNumberX()
uint8_t ns3::MobilityBuildingInfo::GetRoomNumberX (void)
Get the room number along x-axis at which the MobilityBuildingInfo instance is located.
Returns
The room number
Definition at line 156 of file mobility-building-info.cc.
References m_roomX, and NS_LOG_FUNCTION.
Referenced by RandomRoomPositionAllocatorTestCase::DoRun(), SameRoomPositionAllocatorTestCase::DoRun(), and BuildingsHelperOneTestCase::DoRun().
GetRoomNumberY()
uint8_t ns3::MobilityBuildingInfo::GetRoomNumberY (void)
Get the room number along y-axis at which the MobilityBuildingInfo instance is located.
Returns
The room number
Definition at line 163 of file mobility-building-info.cc.
References m_roomY, and NS_LOG_FUNCTION.
Referenced by RandomRoomPositionAllocatorTestCase::DoRun(), SameRoomPositionAllocatorTestCase::DoRun(), and BuildingsHelperOneTestCase::DoRun().
GetTypeId()
TypeId ns3::MobilityBuildingInfo::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 37 of file mobility-building-info.cc.
References ns3::TypeId::SetParent().
IsIndoor()
bool ns3::MobilityBuildingInfo::IsIndoor (void)
Is indoor method.
Returns
true if the MobilityBuildingInfo instance is indoor, false otherwise
Definition at line 78 of file mobility-building-info.cc.
References ns3::MobilityModel::GetPosition(), m_cachedPosition, m_indoor, MakeConsistent(), and NS_LOG_FUNCTION.
Referenced by RandomRoomPositionAllocatorTestCase::DoRun(), SameRoomPositionAllocatorTestCase::DoRun(), BuildingsHelperOneTestCase::DoRun(), and IsOutdoor().
IsOutdoor()
bool ns3::MobilityBuildingInfo::IsOutdoor (void)
Is outdoor function.
Returns
true if the MobilityBuildingInfo instance is outdoor, false otherwise
Deprecated:
This method will go away in a future release of ns-3. Calling IsIndoor () method of MobilityBuildingInfo class will satisfy the need to determine if a node is inside or outside a building.
Definition at line 93 of file mobility-building-info.cc.
References IsIndoor(), and NS_LOG_FUNCTION.
MakeConsistent()
void ns3::MobilityBuildingInfo::MakeConsistent (Ptr< MobilityModel > mm)
Make the given mobility model consistent, by determining whether its position falls inside any of the building in BuildingList, and updating accordingly the BuildingInfo aggregated with the MobilityModel.
Parameters
mm the mobility model to be made consistent
Definition at line 178 of file mobility-building-info.cc.
References ns3::BuildingList::Begin(), ns3::BuildingList::End(), ns3::MobilityModel::GetPosition(), m_cachedPosition, NS_ABORT_MSG_UNLESS, NS_LOG_LOGIC(), SetIndoor(), and SetOutdoor().
Referenced by BuildingsPathlossTestCase::CreateMobilityModel(), BuildingsShadowingTestCase::CreateMobilityModel(), DoInitialize(), BuildingsChannelConditionModelTestCase::DoRun(), and IsIndoor().
SetIndoor() [1/2]
void ns3::MobilityBuildingInfo::SetIndoor (Ptr< Building > building, uint8_t nfloor, uint8_t nroomx, uint8_t nroomy)
Mark this MobilityBuildingInfo instance as indoor.
Parameters
building the building into which the MobilityBuildingInfo instance is located
nfloor the floor number 1...nFloors at which the MobilityBuildingInfo instance is located
nroomx the X room number 1...nRoomsX at which the MobilityBuildingInfo instance is located
nroomy the Y room number 1...nRoomsY at which the MobilityBuildingInfo instance is located
Definition at line 101 of file mobility-building-info.cc.
References m_indoor, m_myBuilding, m_nFloor, m_roomX, m_roomY, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by MakeConsistent().
SetIndoor() [2/2]
void ns3::MobilityBuildingInfo::SetIndoor (uint8_t nfloor, uint8_t nroomx, uint8_t nroomy)
Mark this MobilityBuildingInfo instance as indoor.
Parameters
nfloor the floor number 1...nFloors at which the MobilityBuildingInfo instance is located
nroomx the X room number 1...nRoomsX at which the MobilityBuildingInfo instance is located
nroomy the Y room number 1...nRoomsY at which the MobilityBuildingInfo instance is located
Definition at line 122 of file mobility-building-info.cc.
References m_indoor, m_myBuilding, m_nFloor, m_roomX, m_roomY, NS_ASSERT, NS_ASSERT_MSG(), and NS_LOG_FUNCTION.
SetOutdoor()
void ns3::MobilityBuildingInfo::SetOutdoor ()
Mark this MobilityBuildingInfo instance as outdoor.
Definition at line 142 of file mobility-building-info.cc.
References m_indoor, and NS_LOG_FUNCTION.
Referenced by MakeConsistent().
Member Data Documentation
m_cachedPosition
Vector ns3::MobilityBuildingInfo::m_cachedPosition private
The node position cached after making its mobility model consistent.
Definition at line 161 of file mobility-building-info.h.
Referenced by MobilityBuildingInfo(), IsIndoor(), and MakeConsistent().
m_indoor
bool ns3::MobilityBuildingInfo::m_indoor private
Node position (indoor/outdoor) ?
Definition at line 157 of file mobility-building-info.h.
Referenced by MobilityBuildingInfo(), IsIndoor(), SetIndoor(), and SetOutdoor().
m_myBuilding
Ptr<Building> ns3::MobilityBuildingInfo::m_myBuilding private
Building.
Definition at line 156 of file mobility-building-info.h.
Referenced by GetBuilding(), and SetIndoor().
m_nFloor
uint8_t ns3::MobilityBuildingInfo::m_nFloor private
The floor number at which the MobilityBuildingInfo instance is located.
Definition at line 158 of file mobility-building-info.h.
Referenced by MobilityBuildingInfo(), GetFloorNumber(), and SetIndoor().
m_roomX
uint8_t ns3::MobilityBuildingInfo::m_roomX private
The room number along x-axis at which the MobilityBuildingInfo instance is located.
Definition at line 159 of file mobility-building-info.h.
Referenced by MobilityBuildingInfo(), GetRoomNumberX(), and SetIndoor().
m_roomY
uint8_t ns3::MobilityBuildingInfo::m_roomY private
The room number along y-axis at which the MobilityBuildingInfo instance is located.
Definition at line 160 of file mobility-building-info.h.
Referenced by MobilityBuildingInfo(), GetRoomNumberY(), and SetIndoor().
The documentation for this class was generated from the following files:
src/buildings/model/mobility-building-info.h
src/buildings/model/mobility-building-info.cc