ns-3: ns3::aodv::RerrHeader Class Reference
ns3::aodv::RerrHeader Class Reference
AODV Routing
Route Error (RERR) Message Format.
#include "aodv-packet.h"
Public Member Functions
RerrHeader ()
constructor
bool AddUnDestination (Ipv4Address dst, uint32_t seqNo)
Add unreachable node address and its sequence number in RERR header.
void Clear ()
Clear header.
uint32_t Deserialize (Buffer::Iterator start)
uint8_t GetDestCount () const
TypeId GetInstanceTypeId () const
Get the most derived TypeId for this Object.
bool GetNoDelete () const
Get the no delete flag.
uint32_t GetSerializedSize () const
bool operator== (RerrHeader const &o) const
Comparison operator.
void Print (std::ostream &os) const
bool RemoveUnDestination (std::pair< Ipv4Address, uint32_t > &un)
Delete pair (address + sequence number) from REER header, if the number of unreachable destinations > 0.
void Serialize (Buffer::Iterator i) const
void SetNoDelete (bool f)
Set the no delete flag.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_flag
No delete flag.
uint8_t m_reserved
Not used (must be 0)
std::map< Ipv4Address, uint32_t > m_unreachableDstSeqNo
List of Unreachable destination: IP addresses and sequence numbers.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Route Error (RERR) Message Format.
0                   1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|     Type      |N|          Reserved           |   DestCount   |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|            Unreachable Destination IP Address (1)             |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|         Unreachable Destination Sequence Number (1)           |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-|
|  Additional Unreachable Destination IP Addresses (if needed)  |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|Additional Unreachable Destination Sequence Numbers (if needed)|
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 557 of file aodv-packet.h.
Constructor & Destructor Documentation
RerrHeader()
ns3::aodv::RerrHeader::RerrHeader ()
constructor
Definition at line 520 of file aodv-packet.cc.
Member Function Documentation
AddUnDestination()
bool ns3::aodv::RerrHeader::AddUnDestination (Ipv4Address dst, uint32_t seqNo)
Add unreachable node address and its sequence number in RERR header.
Parameters
dst unreachable IPv4 address
seqNo unreachable sequence number
Returns
false if we already added maximum possible number of unreachable destinations
Definition at line 619 of file aodv-packet.cc.
References GetDestCount(), m_unreachableDstSeqNo, and NS_ASSERT.
Referenced by ns3::aodv::RerrHeaderTest::DoRun(), ns3::aodv::RoutingProtocol::RecvError(), ns3::aodv::RoutingProtocol::SendRerrWhenBreaksLinkToNextHop(), and ns3::aodv::RoutingProtocol::SendRerrWhenNoRouteToForward().
Clear()
void ns3::aodv::RerrHeader::Clear ()
Clear header.
Definition at line 645 of file aodv-packet.cc.
References m_flag, m_reserved, and m_unreachableDstSeqNo.
Referenced by ns3::aodv::RoutingProtocol::RecvError(), and ns3::aodv::RoutingProtocol::SendRerrWhenBreaksLinkToNextHop().
Deserialize()
uint32_t ns3::aodv::RerrHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 566 of file aodv-packet.cc.
References first::address, ns3::Buffer::Iterator::GetDistanceFrom(), GetSerializedSize(), m_flag, m_reserved, m_unreachableDstSeqNo, NS_ASSERT, ns3::ReadFrom(), ns3::Buffer::Iterator::ReadNtohU32(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetDestCount()
uint8_t ns3::aodv::RerrHeader::GetDestCount () const inline
Returns
number of unreachable destinations in RERR message
Definition at line 604 of file aodv-packet.h.
References m_unreachableDstSeqNo.
Referenced by AddUnDestination(), ns3::aodv::RerrHeaderTest::DoRun(), GetSerializedSize(), operator==(), ns3::aodv::RoutingProtocol::RecvError(), ns3::aodv::RoutingProtocol::SendRerrWhenBreaksLinkToNextHop(), and Serialize().
GetInstanceTypeId()
TypeId ns3::aodv::RerrHeader::GetInstanceTypeId () const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 540 of file aodv-packet.cc.
References GetTypeId().
GetNoDelete()
bool ns3::aodv::RerrHeader::GetNoDelete () const
Get the no delete flag.
Returns
the no delete flag
Definition at line 613 of file aodv-packet.cc.
References m_flag.
Referenced by ns3::aodv::RerrHeaderTest::DoRun().
GetSerializedSize()
uint32_t ns3::aodv::RerrHeader::GetSerializedSize () const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 546 of file aodv-packet.cc.
References GetDestCount().
Referenced by Deserialize(), and ns3::aodv::RerrHeaderTest::DoRun().
GetTypeId()
TypeId ns3::aodv::RerrHeader::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 529 of file aodv-packet.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
operator==()
bool ns3::aodv::RerrHeader::operator== (RerrHeader const & o) const
Comparison operator.
Parameters
o RERR header to compare
Returns
true if the RERR headers are equal
Definition at line 653 of file aodv-packet.cc.
References GetDestCount(), m_flag, m_reserved, and m_unreachableDstSeqNo.
Print()
void ns3::aodv::RerrHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 588 of file aodv-packet.cc.
References m_unreachableDstSeqNo.
Referenced by ns3::aodv::operator<<().
RemoveUnDestination()
bool ns3::aodv::RerrHeader::RemoveUnDestination (std::pair< Ipv4Address, uint32_t > & un)
Delete pair (address + sequence number) from REER header, if the number of unreachable destinations > 0.
Parameters
un unreachable pair (address + sequence number)
Returns
true on success
Definition at line 632 of file aodv-packet.cc.
References m_unreachableDstSeqNo.
Referenced by ns3::aodv::RoutingProtocol::RecvError().
Serialize()
void ns3::aodv::RerrHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 552 of file aodv-packet.cc.
References GetDestCount(), m_flag, m_reserved, m_unreachableDstSeqNo, ns3::Buffer::Iterator::WriteHtonU32(), ns3::WriteTo(), and ns3::Buffer::Iterator::WriteU8().
SetNoDelete()
void ns3::aodv::RerrHeader::SetNoDelete (bool f)
Set the no delete flag.
Parameters
f the no delete flag
Definition at line 600 of file aodv-packet.cc.
References f(), and m_flag.
Referenced by ns3::aodv::RerrHeaderTest::DoRun().
Member Data Documentation
m_flag
uint8_t ns3::aodv::RerrHeader::m_flag private
No delete flag.
Definition at line 616 of file aodv-packet.h.
Referenced by Clear(), Deserialize(), GetNoDelete(), operator==(), Serialize(), and SetNoDelete().
m_reserved
uint8_t ns3::aodv::RerrHeader::m_reserved private
Not used (must be 0)
Definition at line 617 of file aodv-packet.h.
Referenced by Clear(), Deserialize(), operator==(), and Serialize().
m_unreachableDstSeqNo
std::map<Ipv4Address, uint32_t> ns3::aodv::RerrHeader::m_unreachableDstSeqNo private
List of Unreachable destination: IP addresses and sequence numbers.
Definition at line 620 of file aodv-packet.h.
Referenced by AddUnDestination(), Clear(), Deserialize(), GetDestCount(), operator==(), Print(), RemoveUnDestination(), and Serialize().
The documentation for this class was generated from the following files:
src/aodv/model/aodv-packet.h
src/aodv/model/aodv-packet.cc