ns-3: ns3::DcdChannelEncodings Class Reference
ns3::DcdChannelEncodings Class Reference abstract
WiMAX Models
#include "dl-mac-messages.h"
Public Member Functions
DcdChannelEncodings (void)
virtual ~DcdChannelEncodings (void)
uint16_t GetBsEirp (void) const
Get BS EIRP field.
uint16_t GetEirxPIrMax (void) const
Get EIRX IR MAX field.
uint32_t GetFrequency (void) const
Get frequency function.
uint16_t GetSize (void) const
Get size field.
Buffer::Iterator Read (Buffer::Iterator start)
Read item.
void SetBsEirp (uint16_t bs_eirp)
Set BS EIRP field.
void SetEirxPIrMax (uint16_t rss_ir_max)
Set EIRX IR MAX field.
void SetFrequency (uint32_t frequency)
Set frequency field.
Buffer::Iterator Write (Buffer::Iterator start) const
Write item.
Private Member Functions
virtual Buffer::Iterator DoRead (Buffer::Iterator start)=0
Read item.
virtual Buffer::Iterator DoWrite (Buffer::Iterator start) const =0
Write item.
Private Attributes
uint16_t m_bsEirp
BS EIRP.
uint16_t m_eirXPIrMax
EIRX IR MAX.
uint32_t m_frequency
frequency
Detailed Description
This class implements the DCD channel encodings as described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems" 11.4.1 DCD channel encodings, page 659
Definition at line 38 of file dl-mac-messages.h.
Constructor & Destructor Documentation
DcdChannelEncodings()
ns3::DcdChannelEncodings::DcdChannelEncodings (void)
Definition at line 30 of file dl-mac-messages.cc.
~DcdChannelEncodings()
ns3::DcdChannelEncodings::~DcdChannelEncodings (void) virtual
Definition at line 37 of file dl-mac-messages.cc.
Member Function Documentation
DoRead()
virtual Buffer::Iterator ns3::DcdChannelEncodings::DoRead (Buffer::Iterator start) private pure virtual
Read item.
Parameters
start the iterator
Returns
the updated iterator
Implemented in ns3::OfdmDcdChannelEncodings.
Referenced by Read().
DoWrite()
virtual Buffer::Iterator ns3::DcdChannelEncodings::DoWrite (Buffer::Iterator start) const private pure virtual
Write item.
Parameters
start iterator
Returns
the updated iterator
Implemented in ns3::OfdmDcdChannelEncodings.
Referenced by Write().
GetBsEirp()
uint16_t ns3::DcdChannelEncodings::GetBsEirp (void) const
Get BS EIRP field.
Returns
the BS EIRP
Definition at line 60 of file dl-mac-messages.cc.
References m_bsEirp.
Referenced by ns3::SubscriberStationNetDevice::ProcessDcd().
GetEirxPIrMax()
uint16_t ns3::DcdChannelEncodings::GetEirxPIrMax (void) const
Get EIRX IR MAX field.
Returns
the EIRX IR MAX
Definition at line 66 of file dl-mac-messages.cc.
References m_eirXPIrMax.
Referenced by ns3::SubscriberStationNetDevice::ProcessDcd().
GetFrequency()
uint32_t ns3::DcdChannelEncodings::GetFrequency (void) const
Get frequency function.
Returns
the frequency
Definition at line 72 of file dl-mac-messages.cc.
References m_frequency.
GetSize()
uint16_t ns3::DcdChannelEncodings::GetSize (void) const
Get size field.
Returns
the size
Definition at line 78 of file dl-mac-messages.cc.
Referenced by ns3::OfdmDcdChannelEncodings::GetSize().
Read()
Buffer::Iterator ns3::DcdChannelEncodings::Read (Buffer::Iterator start)
Read item.
Parameters
start the iterator
Returns
the updated iterator
Definition at line 94 of file dl-mac-messages.cc.
References DoRead(), m_bsEirp, m_eirXPIrMax, m_frequency, ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU32(), and visualizer.core::start().
Referenced by ns3::Dcd::Deserialize().
SetBsEirp()
void ns3::DcdChannelEncodings::SetBsEirp (uint16_t bs_eirp)
Set BS EIRP field.
Parameters
bs_eirp the BS EIRP
Definition at line 42 of file dl-mac-messages.cc.
References m_bsEirp.
Referenced by ns3::BaseStationNetDevice::CreateDcd().
SetEirxPIrMax()
void ns3::DcdChannelEncodings::SetEirxPIrMax (uint16_t rss_ir_max)
Set EIRX IR MAX field.
Parameters
rss_ir_max the EIRRX IR MAX
Definition at line 48 of file dl-mac-messages.cc.
References m_eirXPIrMax.
Referenced by ns3::BaseStationNetDevice::CreateDcd().
SetFrequency()
void ns3::DcdChannelEncodings::SetFrequency (uint32_t frequency)
Set frequency field.
Parameters
frequency the frequency
Definition at line 54 of file dl-mac-messages.cc.
References m_frequency.
Referenced by ns3::BaseStationNetDevice::CreateDcd().
Write()
Buffer::Iterator ns3::DcdChannelEncodings::Write (Buffer::Iterator start) const
Write item.
Parameters
start the iterator
Returns
the updated iterator
Definition at line 84 of file dl-mac-messages.cc.
References DoWrite(), m_bsEirp, m_eirXPIrMax, m_frequency, visualizer.core::start(), ns3::Buffer::Iterator::WriteU16(), and ns3::Buffer::Iterator::WriteU32().
Referenced by ns3::Dcd::Serialize().
Member Data Documentation
m_bsEirp
uint16_t ns3::DcdChannelEncodings::m_bsEirp private
BS EIRP.
Definition at line 108 of file dl-mac-messages.h.
Referenced by GetBsEirp(), Read(), SetBsEirp(), and Write().
m_eirXPIrMax
uint16_t ns3::DcdChannelEncodings::m_eirXPIrMax private
EIRX IR MAX.
Definition at line 109 of file dl-mac-messages.h.
Referenced by GetEirxPIrMax(), Read(), SetEirxPIrMax(), and Write().
m_frequency
uint32_t ns3::DcdChannelEncodings::m_frequency private
frequency
Definition at line 110 of file dl-mac-messages.h.
Referenced by GetFrequency(), Read(), SetFrequency(), and Write().
The documentation for this class was generated from the following files:
src/wimax/model/dl-mac-messages.h
src/wimax/model/dl-mac-messages.cc