ns-3: ns3::AsciiTraceHelperForIpv6 Class Reference
ns3::AsciiTraceHelperForIpv6 Class Reference abstract
Internet » IPv6 Helper classes
Base class providing common user-level ascii trace operations for helpers representing IPv6 protocols .
#include "internet-trace-helper.h"
Public Member Functions
AsciiTraceHelperForIpv6 ()
Construct an AsciiTraceHelperForIpv6.
virtual ~AsciiTraceHelperForIpv6 ()
Destroy an AsciiTraceHelperForIpv6.
void EnableAsciiIpv6 (Ptr< OutputStreamWrapper > stream, Ipv6InterfaceContainer c)
Enable ascii trace output on each device in the container which is of the appropriate type.
void EnableAsciiIpv6 (Ptr< OutputStreamWrapper > stream, NodeContainer n)
Enable ascii trace output on all Ipv6 and interface pairs existing in the nodes provided in the container.
void EnableAsciiIpv6 (Ptr< OutputStreamWrapper > stream, Ptr< Ipv6 > ipv6, uint32_t interface)
Enable ascii trace output on the indicated Ipv6 and interface pair.
void EnableAsciiIpv6 (Ptr< OutputStreamWrapper > stream, std::string ipv6Name, uint32_t interface)
Enable ascii trace output the indicated net device using a device previously named using the ns-3 object name service.
void EnableAsciiIpv6 (Ptr< OutputStreamWrapper > stream, uint32_t nodeid, uint32_t interface)
Enable ascii trace output on the Ipv6 and interface pair specified by a global node-id (of a previously created node) and interface.
void EnableAsciiIpv6 (std::string prefix, Ipv6InterfaceContainer c)
Enable ascii trace output on each Ipv6 and interface pair in the container.
void EnableAsciiIpv6 (std::string prefix, NodeContainer n)
Enable ascii trace output on all Ipv6 and interface pairs existing in the nodes provided in the container.
void EnableAsciiIpv6 (std::string prefix, Ptr< Ipv6 > ipv6, uint32_t interface, bool explicitFilename=false)
Enable ascii trace output on the indicated Ipv6 and interface pair.
void EnableAsciiIpv6 (std::string prefix, std::string ipv6Name, uint32_t interface, bool explicitFilename=false)
Enable ascii trace output the indicated Ipv6 and interface pair using an Ipv6 previously named using the ns-3 object name service.
void EnableAsciiIpv6 (std::string prefix, uint32_t nodeid, uint32_t interface, bool explicitFilename)
Enable ascii trace output on the Ipv6 and interface pair specified by a global node-id (of a previously created node) and interface.
void EnableAsciiIpv6All (Ptr< OutputStreamWrapper > stream)
Enable ascii trace output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
void EnableAsciiIpv6All (std::string prefix)
Enable ascii trace output on all Ipv6 and interface pairs existing in the set of all nodes created in the simulation.
virtual void EnableAsciiIpv6Internal (Ptr< OutputStreamWrapper > stream, std::string prefix, Ptr< Ipv6 > ipv6, uint32_t interface, bool explicitFilename)=0
Enable ascii trace output on the indicated Ipv6 and interface pair.
Private Member Functions
void EnableAsciiIpv6Impl (Ptr< OutputStreamWrapper > stream, std::string prefix, Ipv6InterfaceContainer c)
Enable ascii trace output on the Ipv6 and interface pair specified by a global node-id (of a previously created node) and interface.
void EnableAsciiIpv6Impl (Ptr< OutputStreamWrapper > stream, std::string prefix, NodeContainer n)
Enable ascii trace output on the Ipv6 and interface pair specified by a global node-id (of a previously created node) and interface.
void EnableAsciiIpv6Impl (Ptr< OutputStreamWrapper > stream, std::string prefix, Ptr< Ipv6 > ipv6, uint32_t interface, bool explicitFilename)
Enable ascii trace output on the Ipv6 and interface pair specified by a global node-id (of a previously created node) and interface.
void EnableAsciiIpv6Impl (Ptr< OutputStreamWrapper > stream, std::string prefix, std::string ipv6Name, uint32_t interface, bool explicitFilename)
Enable ascii trace output on the Ipv6 and interface pair specified by a global node-id (of a previously created node) and interface.
void EnableAsciiIpv6Impl (Ptr< OutputStreamWrapper > stream, std::string prefix, uint32_t nodeid, uint32_t interface, bool explicitFilename)
Enable ascii trace output on the Ipv6 and interface pair specified by a global node-id (of a previously created node) and interface.
Detailed Description
Base class providing common user-level ascii trace operations for helpers representing IPv6 protocols .
Definition at line 489 of file internet-trace-helper.h.
Constructor & Destructor Documentation
AsciiTraceHelperForIpv6()
ns3::AsciiTraceHelperForIpv6::AsciiTraceHelperForIpv6 () inline
Construct an AsciiTraceHelperForIpv6.
Definition at line 495 of file internet-trace-helper.h.
~AsciiTraceHelperForIpv6()
virtual ns3::AsciiTraceHelperForIpv6::~AsciiTraceHelperForIpv6 () inline virtual
Destroy an AsciiTraceHelperForIpv6.
Definition at line 500 of file internet-trace-helper.h.
Member Function Documentation
EnableAsciiIpv6() [1/10]
void ns3::AsciiTraceHelperForIpv6::EnableAsciiIpv6 (Ptr< OutputStreamWrapper > stream, Ipv6InterfaceContainer c)
Enable ascii trace output on each device in the container which is of the appropriate type.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
c Ipv6InterfaceContainer of Ipv6 and interface pairs on which to enable tracing.
Definition at line 433 of file internet-trace-helper.cc.
References EnableAsciiIpv6Impl().
EnableAsciiIpv6() [2/10]
void ns3::AsciiTraceHelperForIpv6::EnableAsciiIpv6 (Ptr< OutputStreamWrapper > stream, NodeContainer n)
Enable ascii trace output on all Ipv6 and interface pairs existing in the nodes provided in the container.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
n container of nodes.
Definition at line 464 of file internet-trace-helper.cc.
References EnableAsciiIpv6Impl(), and sample-rng-plot::n.
EnableAsciiIpv6() [3/10]
void ns3::AsciiTraceHelperForIpv6::EnableAsciiIpv6 (Ptr< OutputStreamWrapper > stream, Ptr< Ipv6 > ipv6, uint32_t interface)
Enable ascii trace output on the indicated Ipv6 and interface pair.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
ipv6 Ptr<Ipv6> on which you want to enable tracing.
interface The interface on which you want to enable tracing.
Definition at line 382 of file internet-trace-helper.cc.
References EnableAsciiIpv6Internal().
EnableAsciiIpv6() [4/10]
void ns3::AsciiTraceHelperForIpv6::EnableAsciiIpv6 (Ptr< OutputStreamWrapper > stream, std::string ipv6Name, uint32_t interface)
Enable ascii trace output the indicated net device using a device previously named using the ns-3 object name service.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
ipv6Name The name of the Ipv6 on which you want to enable tracing.
interface The interface on which you want to enable tracing.
Definition at line 400 of file internet-trace-helper.cc.
References EnableAsciiIpv6Impl().
EnableAsciiIpv6() [5/10]
void ns3::AsciiTraceHelperForIpv6::EnableAsciiIpv6 (Ptr< OutputStreamWrapper > stream, uint32_t nodeid, uint32_t interface)
Enable ascii trace output on the Ipv6 and interface pair specified by a global node-id (of a previously created node) and interface.
Since there can be only one Ipv6 aggregated to a node, the node-id unambiguously determines the Ipv6.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
nodeid The node identifier/number of the node on which to enable ascii tracing
interface The interface on which you want to enable tracing.
Definition at line 511 of file internet-trace-helper.cc.
References EnableAsciiIpv6Impl().
EnableAsciiIpv6() [6/10]
void ns3::AsciiTraceHelperForIpv6::EnableAsciiIpv6 (std::string prefix, Ipv6InterfaceContainer c)
Enable ascii trace output on each Ipv6 and interface pair in the container.
Parameters
prefix Filename prefix to use for ascii files.
c Ipv6InterfaceContainer of Ipv6 and interface pairs on which to enable tracing.
Definition at line 424 of file internet-trace-helper.cc.
References EnableAsciiIpv6Impl().
EnableAsciiIpv6() [7/10]
void ns3::AsciiTraceHelperForIpv6::EnableAsciiIpv6 (std::string prefix, NodeContainer n)
Enable ascii trace output on all Ipv6 and interface pairs existing in the nodes provided in the container.
Parameters
prefix Filename prefix to use for ascii files.
n container of nodes.
Definition at line 455 of file internet-trace-helper.cc.
References EnableAsciiIpv6Impl(), and sample-rng-plot::n.
EnableAsciiIpv6() [8/10]
void ns3::AsciiTraceHelperForIpv6::EnableAsciiIpv6 (std::string prefix, Ptr< Ipv6 > ipv6, uint32_t interface, bool explicitFilename = false)
Enable ascii trace output on the indicated Ipv6 and interface pair.
Parameters
prefix Filename prefix to use for ascii files.
ipv6 Ptr<Ipv6> on which you want to enable tracing.
interface The interface on which you want to enable tracing.
explicitFilename Treat the prefix as an explicit filename if true.
Definition at line 373 of file internet-trace-helper.cc.
References EnableAsciiIpv6Internal().
EnableAsciiIpv6() [9/10]
void ns3::AsciiTraceHelperForIpv6::EnableAsciiIpv6 (std::string prefix, std::string ipv6Name, uint32_t interface, bool explicitFilename = false)
Enable ascii trace output the indicated Ipv6 and interface pair using an Ipv6 previously named using the ns-3 object name service.
Parameters
prefix filename prefix to use for ascii files.
ipv6Name The name of the Ipv6 on which you want to enable tracing.
interface The interface on which you want to enable tracing.
explicitFilename Treat the prefix as an explicit filename if true.
Definition at line 391 of file internet-trace-helper.cc.
References EnableAsciiIpv6Impl().
EnableAsciiIpv6() [10/10]
void ns3::AsciiTraceHelperForIpv6::EnableAsciiIpv6 (std::string prefix, uint32_t nodeid, uint32_t interface, bool explicitFilename)
Enable ascii trace output on the Ipv6 and interface pair specified by a global node-id (of a previously created node) and interface.
Since there can be only one Ipv6 aggregated to a node, the node-id unambiguously determines the Ipv6.
Parameters
prefix Filename prefix to use when creating ascii trace files
nodeid The node identifier/number of the node on which to enable ascii tracing
interface The device identifier/index of the device on which to enable ascii tracing
explicitFilename Treat the prefix as an explicit filename if true.
Definition at line 520 of file internet-trace-helper.cc.
References EnableAsciiIpv6Impl().
EnableAsciiIpv6All() [1/2]
void ns3::AsciiTraceHelperForIpv6::EnableAsciiIpv6All (Ptr< OutputStreamWrapper > stream)
Enable ascii trace output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
Definition at line 502 of file internet-trace-helper.cc.
References EnableAsciiIpv6Impl(), and ns3::NodeContainer::GetGlobal().
EnableAsciiIpv6All() [2/2]
void ns3::AsciiTraceHelperForIpv6::EnableAsciiIpv6All (std::string prefix)
Enable ascii trace output on all Ipv6 and interface pairs existing in the set of all nodes created in the simulation.
Parameters
prefix Filename prefix to use for ascii files.
Definition at line 493 of file internet-trace-helper.cc.
References EnableAsciiIpv6Impl(), and ns3::NodeContainer::GetGlobal().
EnableAsciiIpv6Impl() [1/5]
void ns3::AsciiTraceHelperForIpv6::EnableAsciiIpv6Impl (Ptr< OutputStreamWrapper > stream, std::string prefix, Ipv6InterfaceContainer c) private
Enable ascii trace output on the Ipv6 and interface pair specified by a global node-id (of a previously created node) and interface.
Since there can be only one Ipv6 aggregated to a node, the node-id unambiguously determines the Ipv6.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
prefix Filename prefix to use when creating ascii trace files
c Ipv6InterfaceContainer of Ipv6 and interface pairs
Definition at line 442 of file internet-trace-helper.cc.
References ns3::Ipv6InterfaceContainer::Begin(), EnableAsciiIpv6Internal(), and ns3::Ipv6InterfaceContainer::End().
EnableAsciiIpv6Impl() [2/5]
void ns3::AsciiTraceHelperForIpv6::EnableAsciiIpv6Impl (Ptr< OutputStreamWrapper > stream, std::string prefix, NodeContainer n) private
Enable ascii trace output on the Ipv6 and interface pair specified by a global node-id (of a previously created node) and interface.
Since there can be only one Ipv6 aggregated to a node, the node-id unambiguously determines the Ipv6.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
prefix Filename prefix to use when creating ascii trace files
n container of nodes.
Definition at line 473 of file internet-trace-helper.cc.
References EnableAsciiIpv6Internal(), ns3::Object::GetObject(), and sample-rng-plot::n.
EnableAsciiIpv6Impl() [3/5]
void ns3::AsciiTraceHelperForIpv6::EnableAsciiIpv6Impl (Ptr< OutputStreamWrapper > stream, std::string prefix, Ptr< Ipv6 > ipv6, uint32_t interface, bool explicitFilename) private
Enable ascii trace output on the Ipv6 and interface pair specified by a global node-id (of a previously created node) and interface.
Since there can be only one Ipv6 aggregated to a node, the node-id unambiguously determines the Ipv6.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
prefix Filename prefix to use when creating ascii trace files
ipv6 Ptr<Ipv6> on which you want to enable tracing.
interface The device identifier/index of the device on which to enable ascii tracing
explicitFilename Treat the prefix as an explicit filename if true.
EnableAsciiIpv6Impl() [4/5]
void ns3::AsciiTraceHelperForIpv6::EnableAsciiIpv6Impl (Ptr< OutputStreamWrapper > stream, std::string prefix, std::string ipv6Name, uint32_t interface, bool explicitFilename) private
Enable ascii trace output on the Ipv6 and interface pair specified by a global node-id (of a previously created node) and interface.
Since there can be only one Ipv6 aggregated to a node, the node-id unambiguously determines the Ipv6.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
prefix Filename prefix to use when creating ascii trace files
ipv6Name Name of the Ptr<Ipv6> on which you want to enable tracing.
interface The device identifier/index of the device on which to enable ascii tracing
explicitFilename Treat the prefix as an explicit filename if true.
Definition at line 409 of file internet-trace-helper.cc.
References EnableAsciiIpv6Internal().
EnableAsciiIpv6Impl() [5/5]
void ns3::AsciiTraceHelperForIpv6::EnableAsciiIpv6Impl (Ptr< OutputStreamWrapper > stream, std::string prefix, uint32_t nodeid, uint32_t interface, bool explicitFilename) private
Enable ascii trace output on the Ipv6 and interface pair specified by a global node-id (of a previously created node) and interface.
Since there can be only one Ipv6 aggregated to a node, the node-id unambiguously determines the Ipv6.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
prefix Filename prefix to use when creating ascii trace files
nodeid The node identifier/number of the node on which to enable ascii tracing
interface The device identifier/index of the device on which to enable ascii tracing
explicitFilename Treat the prefix as an explicit filename if true.
Definition at line 529 of file internet-trace-helper.cc.
References EnableAsciiIpv6Internal(), ns3::NodeContainer::GetGlobal(), ns3::Node::GetId(), ns3::Object::GetObject(), and sample-rng-plot::n.
Referenced by EnableAsciiIpv6(), and EnableAsciiIpv6All().
EnableAsciiIpv6Internal()
virtual void ns3::AsciiTraceHelperForIpv6::EnableAsciiIpv6Internal (Ptr< OutputStreamWrapper > stream, std::string prefix, Ptr< Ipv6 > ipv6, uint32_t interface, bool explicitFilename) pure virtual
Enable ascii trace output on the indicated Ipv6 and interface pair.
The implementation is expected to use a provided Ptr<OutputStreamWrapper> if it is non-null. If the OutputStreamWrapper is null, the implementation is expected to use a provided prefix to construct a new file name for each net device using the rules described in the class overview.
If the prefix is provided, there will be one file per Ipv6 and interface pair created. In this case, adding a trace context to the file would be pointless, so the helper implementation is expected to TraceConnectWithoutContext.
If the output stream object is provided, there may be many different Ipv6 and interface pairs writing to a single file. In this case, the trace context could be important, so the helper implementation is expected to TraceConnect.
Parameters
stream An OutputStreamWrapper representing an existing file to use when writing trace data.
prefix Filename prefix to use for ascii trace files.
ipv6 Ptr<Ipv6> on which you want to enable tracing.
interface The interface on which you want to enable tracing.
explicitFilename Treat the prefix as an explicit filename if true.
Implemented in ns3::InternetStackHelper.
Referenced by EnableAsciiIpv6(), and EnableAsciiIpv6Impl().
The documentation for this class was generated from the following files:
src/internet/helper/internet-trace-helper.h
src/internet/helper/internet-trace-helper.cc