ns-3: UdpSocketImplTest Class Reference
UdpSocketImplTest Class Reference
Internet » internet module tests | Test suites
UDP Socket over IPv4 Test.
Public Member Functions
UdpSocketImplTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
void ReceivePkt (Ptr< Socket > socket)
Receive packets (1).
void ReceivePkt2 (Ptr< Socket > socket)
Receive packets (2).
void SentPkt (Ptr< const QueueDiscItem > item)
Adds a packet to the list of sent packets.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void DoSendData (Ptr< Socket > socket)
Send data.
void DoSendDataTo (Ptr< Socket > socket, std::string to)
Send data.
uint32_t GetPriority (void)
Get the priority of the received packet.
uint32_t GetTos (void)
Get the TOS of the received packet.
void SendData (Ptr< Socket > socket)
Send data.
void SendDataTo (Ptr< Socket > socket, std::string to)
Send data.
Private Attributes
Ptr< Packet > m_receivedPacket
Received packet (1).
Ptr< Packet > m_receivedPacket2
Received packet (2).
Ptr< Ipv4QueueDiscItem > m_sentPacket
Sent packet.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
UDP Socket over IPv4 Test.
Definition at line 175 of file udp-test.cc.
Constructor & Destructor Documentation
UdpSocketImplTest()
UdpSocketImplTest::UdpSocketImplTest ()
Definition at line 238 of file udp-test.cc.
Member Function Documentation
DoRun()
void UdpSocketImplTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 313 of file udp-test.cc.
References ns3::Ipv4::AddAddress(), ns3::Ipv4::AddInterface(), ns3::Socket::Bind(), ns3::SocketFactory::CreateSocket(), ns3::Object::Dispose(), ns3::QueueDiscContainer::Get(), ns3::NetDeviceContainer::Get(), ns3::Object::GetObject(), GetPriority(), ns3::Packet::GetSize(), GetTos(), ns3::TrafficControlHelper::Install(), ns3::SimpleNetDeviceHelper::Install(), ns3::InternetStackHelper::Install(), m_receivedPacket, m_receivedPacket2, ns3::MakeCallback(), first::nodes, NS_TEST_EXPECT_MSG_EQ, ReceivePkt(), ReceivePkt2(), ns3::Packet::RemoveAllByteTags(), SendData(), SendDataTo(), SentPkt(), ns3::Socket::SetAllowBroadcast(), ns3::SimpleNetDeviceHelper::SetNetDevicePointToPointMode(), ns3::Socket::SetRecvCallback(), ns3::InetSocketAddress::SetTos(), ns3::Ipv4::SetUp(), and ns3::ObjectBase::TraceConnectWithoutContext().
DoSendData()
void UdpSocketImplTest::DoSendData (Ptr< Socket > socket) private
Send data.
Parameters
socket The sending socket.
Definition at line 299 of file udp-test.cc.
References NS_TEST_EXPECT_MSG_EQ, and ns3::Socket::Send().
Referenced by SendData().
DoSendDataTo()
void UdpSocketImplTest::DoSendDataTo (Ptr< Socket > socket, std::string to) private
Send data.
Parameters
socket The sending socket.
to The destination address.
Definition at line 281 of file udp-test.cc.
References NS_TEST_EXPECT_MSG_EQ, and ns3::Socket::SendTo().
Referenced by SendDataTo().
GetPriority()
uint32_t UdpSocketImplTest::GetPriority (void) private
Get the priority of the received packet.
Returns
The priority.
Definition at line 272 of file udp-test.cc.
References ns3::QueueItem::GetPacket(), ns3::SocketPriorityTag::GetPriority(), m_sentPacket, NS_TEST_EXPECT_MSG_EQ, and ns3::Packet::PeekPacketTag().
Referenced by DoRun().
GetTos()
uint32_t UdpSocketImplTest::GetTos (void) private
Get the TOS of the received packet.
Returns
The TOS.
Definition at line 267 of file udp-test.cc.
References ns3::Ipv4QueueDiscItem::GetHeader(), ns3::Ipv4Header::GetTos(), and m_sentPacket.
Referenced by DoRun().
ReceivePkt()
void UdpSocketImplTest::ReceivePkt (Ptr< Socket > socket)
Receive packets (1).
Parameters
socket The receiving socket.
Definition at line 243 of file udp-test.cc.
References ns3::Socket::GetRxAvailable(), ns3::Packet::GetSize(), m_receivedPacket, max, NS_ASSERT, and ns3::Socket::Recv().
Referenced by DoRun().
ReceivePkt2()
void UdpSocketImplTest::ReceivePkt2 (Ptr< Socket > socket)
Receive packets (2).
Parameters
socket The receiving socket.
Definition at line 251 of file udp-test.cc.
References ns3::Socket::GetRxAvailable(), ns3::Packet::GetSize(), m_receivedPacket2, max, NS_ASSERT, and ns3::Socket::Recv().
Referenced by DoRun().
SendData()
void UdpSocketImplTest::SendData (Ptr< Socket > socket) private
Send data.
Parameters
socket The sending socket.
Definition at line 305 of file udp-test.cc.
References DoSendData(), ns3::Node::GetId(), ns3::Socket::GetNode(), and ns3::Seconds().
Referenced by DoRun().
SendDataTo()
void UdpSocketImplTest::SendDataTo (Ptr< Socket > socket, std::string to) private
Send data.
Parameters
socket The sending socket.
to The destination address.
Definition at line 289 of file udp-test.cc.
References DoSendDataTo(), ns3::Node::GetId(), ns3::Socket::GetNode(), m_receivedPacket, m_receivedPacket2, and ns3::Seconds().
Referenced by DoRun().
SentPkt()
void UdpSocketImplTest::SentPkt (Ptr< const QueueDiscItem > item)
Adds a packet to the list of sent packets.
Parameters
item The sent packet.
Definition at line 259 of file udp-test.cc.
References ns3::Packet::Copy(), ns3::Ipv4QueueDiscItem::GetHeader(), ns3::QueueItem::GetPacket(), m_sentPacket, and NS_TEST_EXPECT_MSG_NE.
Referenced by DoRun().
Member Data Documentation
m_receivedPacket
Ptr<Packet> UdpSocketImplTest::m_receivedPacket private
Received packet (1).
Definition at line 177 of file udp-test.cc.
Referenced by DoRun(), ReceivePkt(), and SendDataTo().
m_receivedPacket2
Ptr<Packet> UdpSocketImplTest::m_receivedPacket2 private
Received packet (2).
Definition at line 178 of file udp-test.cc.
Referenced by DoRun(), ReceivePkt2(), and SendDataTo().
m_sentPacket
Ptr<Ipv4QueueDiscItem> UdpSocketImplTest::m_sentPacket private
Sent packet.
Definition at line 179 of file udp-test.cc.
Referenced by GetPriority(), GetTos(), and SentPkt().
The documentation for this class was generated from the following file:
src/internet/test/udp-test.cc