ns-3: ns3::lorawan::PeriodicSenderHelper Class Reference
ns3::lorawan::PeriodicSenderHelper Class Reference
This class can be used to install PeriodicSender applications on a wide range of nodes.
#include "periodic-sender-helper.h"
Public Member Functions
PeriodicSenderHelper ()
~PeriodicSenderHelper ()
ApplicationContainer Install (NodeContainer c) const
ApplicationContainer Install (Ptr< Node > node) const
void SetAttribute (std::string name, const AttributeValue &value)
void SetPacketSize (uint8_t size)
void SetPacketSizeRandomVariable (Ptr< RandomVariableStream > rv)
void SetPeriod (Time period)
Set the period to be used by the applications created by this helper.
Private Member Functions
Ptr< Application > InstallPriv (Ptr< Node > node) const
Private Attributes
ObjectFactory m_factory
Ptr< UniformRandomVariable > m_initialDelay
Ptr< UniformRandomVariable > m_intervalProb
Time m_period
The period with which the application will be set to send.
uint8_t m_pktSize
Ptr< RandomVariableStream > m_pktSizeRV
Detailed Description
This class can be used to install PeriodicSender applications on a wide range of nodes.
Definition at line 41 of file periodic-sender-helper.h.
Constructor & Destructor Documentation
PeriodicSenderHelper()
ns3::lorawan::PeriodicSenderHelper::PeriodicSenderHelper ()
Definition at line 35 of file periodic-sender-helper.cc.
References m_factory, m_initialDelay, m_intervalProb, m_pktSize, m_pktSizeRV, ns3::ObjectBase::SetAttribute(), and ns3::ObjectFactory::SetTypeId().
~PeriodicSenderHelper()
ns3::lorawan::PeriodicSenderHelper::~PeriodicSenderHelper ()
Definition at line 53 of file periodic-sender-helper.cc.
Member Function Documentation
Install() [1/2]
ApplicationContainer ns3::lorawan::PeriodicSenderHelper::Install (NodeContainer c) const
Definition at line 70 of file periodic-sender-helper.cc.
References ns3::ApplicationContainer::Add(), ns3::NodeContainer::Begin(), ns3::NodeContainer::End(), and InstallPriv().
Install() [2/2]
ApplicationContainer ns3::lorawan::PeriodicSenderHelper::Install (Ptr< Node > node) const
Definition at line 64 of file periodic-sender-helper.cc.
References InstallPriv().
InstallPriv()
Ptr< Application > ns3::lorawan::PeriodicSenderHelper::InstallPriv (Ptr< Node > node) const private
Definition at line 82 of file periodic-sender-helper.cc.
References ns3::Node::AddApplication(), ns3::ObjectFactory::Create(), ns3::Days(), ns3::UniformRandomVariable::GetValue(), ns3::Hours(), m_factory, m_initialDelay, m_intervalProb, m_period, m_pktSize, m_pktSizeRV, ns3::Minutes(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::Seconds().
Referenced by Install().
SetAttribute()
void ns3::lorawan::PeriodicSenderHelper::SetAttribute (std::string name, const AttributeValue & value)
Definition at line 58 of file periodic-sender-helper.cc.
References m_factory, and ns3::ObjectFactory::Set().
SetPacketSize()
void ns3::lorawan::PeriodicSenderHelper::SetPacketSize (uint8_t size)
Definition at line 147 of file periodic-sender-helper.cc.
References m_pktSize.
SetPacketSizeRandomVariable()
void ns3::lorawan::PeriodicSenderHelper::SetPacketSizeRandomVariable (Ptr< RandomVariableStream > rv)
Definition at line 141 of file periodic-sender-helper.cc.
References m_pktSizeRV.
SetPeriod()
void ns3::lorawan::PeriodicSenderHelper::SetPeriod (Time period)
Set the period to be used by the applications created by this helper.
A value of Seconds (0) results in randomly generated periods according to the model contained in the TR 45.820 document.
Parameters
period The period to set
Definition at line 135 of file periodic-sender-helper.cc.
References m_period.
Member Data Documentation
m_factory
ObjectFactory ns3::lorawan::PeriodicSenderHelper::m_factory private
Definition at line 72 of file periodic-sender-helper.h.
Referenced by PeriodicSenderHelper(), InstallPriv(), and SetAttribute().
m_initialDelay
Ptr<UniformRandomVariable> ns3::lorawan::PeriodicSenderHelper::m_initialDelay private
Definition at line 74 of file periodic-sender-helper.h.
Referenced by PeriodicSenderHelper(), and InstallPriv().
m_intervalProb
Ptr<UniformRandomVariable> ns3::lorawan::PeriodicSenderHelper::m_intervalProb private
Definition at line 76 of file periodic-sender-helper.h.
Referenced by PeriodicSenderHelper(), and InstallPriv().
m_period
Time ns3::lorawan::PeriodicSenderHelper::m_period private
The period with which the application will be set to send.
Definition at line 78 of file periodic-sender-helper.h.
Referenced by InstallPriv(), and SetPeriod().
m_pktSize
uint8_t ns3::lorawan::PeriodicSenderHelper::m_pktSize private
Definition at line 83 of file periodic-sender-helper.h.
Referenced by PeriodicSenderHelper(), InstallPriv(), and SetPacketSize().
m_pktSizeRV
Ptr<RandomVariableStream> ns3::lorawan::PeriodicSenderHelper::m_pktSizeRV private
Definition at line 81 of file periodic-sender-helper.h.
Referenced by PeriodicSenderHelper(), InstallPriv(), and SetPacketSizeRandomVariable().
The documentation for this class was generated from the following files:
src/lorawan/helper/periodic-sender-helper.h
src/lorawan/helper/periodic-sender-helper.cc