ns-3: ns3::lorawan::PeriodicSender Class Reference
ns3::lorawan::PeriodicSender Class Reference
#include "periodic-sender.h"
Public Member Functions
PeriodicSender ()
~PeriodicSender ()
Time GetInterval (void) const
Get the sending inteval.
void SendPacket (void)
Send a packet using the LoraNetDevice's Send method.
void SetInitialDelay (Time delay)
Set the initial delay of this application.
void SetInterval (Time interval)
Set the sending interval.
void SetPacketSize (uint8_t size)
Set packet size.
void SetPacketSizeRandomVariable (Ptr< RandomVariableStream > rv)
Set if using randomness in the packet size.
void StartApplication (void)
Start the application by scheduling the first SendPacket event.
void StopApplication (void)
Stop the application.
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_basePktSize
The packet size.
Time m_initialDelay
The initial delay of this application.
Time m_interval
The interval between to consecutive send events.
Ptr< LorawanMac > m_mac
The MAC layer of this node.
Ptr< RandomVariableStream > m_pktSizeRV
The random variable that adds bytes to the packet size.
EventId m_sendEvent
The sending event scheduled as next.
Additional Inherited Members
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Protected Member Functions inherited from ns3::Application
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 32 of file periodic-sender.h.
Constructor & Destructor Documentation
PeriodicSender()
ns3::lorawan::PeriodicSender::PeriodicSender ()
Definition at line 54 of file periodic-sender.cc.
References NS_LOG_FUNCTION_NOARGS.
~PeriodicSender()
ns3::lorawan::PeriodicSender::~PeriodicSender ()
Definition at line 64 of file periodic-sender.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
GetInterval()
Time ns3::lorawan::PeriodicSender::GetInterval (void) const
Get the sending inteval.
Returns
the interval between two packet sends
Definition at line 77 of file periodic-sender.cc.
References m_interval, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::lorawan::PeriodicSender::GetTypeId (void) static
Definition at line 36 of file periodic-sender.cc.
References GetInterval(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::Seconds(), SetInterval(), and ns3::TypeId::SetParent().
SendPacket()
void ns3::lorawan::PeriodicSender::SendPacket (void)
Send a packet using the LoraNetDevice's Send method.
Definition at line 106 of file periodic-sender.cc.
References ns3::RandomVariableStream::GetInteger(), ns3::Packet::GetSize(), m_basePktSize, m_interval, m_mac, m_pktSizeRV, m_sendEvent, NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::Simulator::Schedule().
Referenced by StartApplication().
SetInitialDelay()
void ns3::lorawan::PeriodicSender::SetInitialDelay (Time delay)
Set the initial delay of this application.
Definition at line 84 of file periodic-sender.cc.
References m_initialDelay, and NS_LOG_FUNCTION.
SetInterval()
void ns3::lorawan::PeriodicSender::SetInterval (Time interval)
Set the sending interval.
Parameters
interval the interval between two packet sendings
Definition at line 70 of file periodic-sender.cc.
References m_interval, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetPacketSize()
void ns3::lorawan::PeriodicSender::SetPacketSize (uint8_t size)
Set packet size.
Definition at line 99 of file periodic-sender.cc.
References m_basePktSize.
SetPacketSizeRandomVariable()
void ns3::lorawan::PeriodicSender::SetPacketSizeRandomVariable (Ptr< RandomVariableStream > rv)
Set if using randomness in the packet size.
Definition at line 92 of file periodic-sender.cc.
References m_pktSizeRV.
StartApplication()
void ns3::lorawan::PeriodicSender::StartApplication (void) virtual
Start the application by scheduling the first SendPacket event.
Reimplemented from ns3::Application.
Definition at line 131 of file periodic-sender.cc.
References ns3::Simulator::Cancel(), ns3::Node::GetDevice(), ns3::Time::GetSeconds(), ns3::EventId::GetUid(), m_initialDelay, m_mac, ns3::Application::m_node, m_sendEvent, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), and SendPacket().
StopApplication()
void ns3::lorawan::PeriodicSender::StopApplication (void) virtual
Stop the application.
Reimplemented from ns3::Application.
Definition at line 155 of file periodic-sender.cc.
References ns3::Simulator::Cancel(), m_sendEvent, and NS_LOG_FUNCTION_NOARGS.
Member Data Documentation
m_basePktSize
uint8_t ns3::lorawan::PeriodicSender::m_basePktSize private
The packet size.
Definition at line 106 of file periodic-sender.h.
Referenced by SendPacket(), and SetPacketSize().
m_initialDelay
Time ns3::lorawan::PeriodicSender::m_initialDelay private
The initial delay of this application.
Definition at line 91 of file periodic-sender.h.
Referenced by SetInitialDelay(), and StartApplication().
m_interval
Time ns3::lorawan::PeriodicSender::m_interval private
The interval between to consecutive send events.
Definition at line 86 of file periodic-sender.h.
Referenced by GetInterval(), SendPacket(), and SetInterval().
m_mac
Ptr<LorawanMac> ns3::lorawan::PeriodicSender::m_mac private
The MAC layer of this node.
Definition at line 101 of file periodic-sender.h.
Referenced by SendPacket(), and StartApplication().
m_pktSizeRV
Ptr<RandomVariableStream> ns3::lorawan::PeriodicSender::m_pktSizeRV private
The random variable that adds bytes to the packet size.
Definition at line 112 of file periodic-sender.h.
Referenced by SendPacket(), and SetPacketSizeRandomVariable().
m_sendEvent
EventId ns3::lorawan::PeriodicSender::m_sendEvent private
The sending event scheduled as next.
Definition at line 96 of file periodic-sender.h.
Referenced by SendPacket(), StartApplication(), and StopApplication().
The documentation for this class was generated from the following files:
src/lorawan/model/periodic-sender.h
src/lorawan/model/periodic-sender.cc