ns-3: ns3::ParabolicAntennaModel Class Reference
ns3::ParabolicAntennaModel Class Reference
Antenna model based on a parabolic approximation of the main lobe radiation pattern.
#include "parabolic-antenna-model.h"
Public Member Functions
double GetBeamwidth () const
virtual double GetGainDb (Angles a)
this method is expected to be re-implemented by each antenna model
double GetOrientation () const
void SetBeamwidth (double beamwidthDegrees)
void SetOrientation (double orientationDegrees)
Public Member Functions inherited from ns3::AntennaModel
AntennaModel ()
virtual ~AntennaModel ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Static Public Member Functions inherited from ns3::AntennaModel
static TypeId GetTypeId ()
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
double m_beamwidthRadians
double m_maxAttenuation
double m_orientationRadians
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Antenna model based on a parabolic approximation of the main lobe radiation pattern.
This class implements the parabolic model as described in some 3GPP document, e.g., R4-092042
A similar model appears in
George Calcev and Matt Dillon, "Antenna Tilt Control in CDMA Networks" in Proc. of the 2nd Annual International Wireless Internet Conference (WICON), 2006
though the latter addresses also the elevation plane, which the present model doesn't.
Definition at line 45 of file parabolic-antenna-model.h.
Member Function Documentation
GetBeamwidth()
double ns3::ParabolicAntennaModel::GetBeamwidth () const
Definition at line 73 of file parabolic-antenna-model.cc.
References m_beamwidthRadians, and ns3::RadiansToDegrees().
Referenced by GetTypeId().
GetGainDb()
double ns3::ParabolicAntennaModel::GetGainDb (Angles a) virtual
this method is expected to be re-implemented by each antenna model
Parameters
a the spherical angles at which the radiation pattern should be evaluated
Returns
the power gain in dBi of the antenna radiation pattern at the specified angles; dBi means dB with respect to the gain of an isotropic radiator. Since a power gain is used, the efficiency of the antenna is expected to be included in the gain value.
Implements ns3::AntennaModel.
Definition at line 92 of file parabolic-antenna-model.cc.
References m_beamwidthRadians, m_maxAttenuation, m_orientationRadians, min, NS_LOG_FUNCTION, NS_LOG_LOGIC(), and ns3::Angles::phi.
Referenced by ParabolicAntennaModelTestCase::DoRun().
GetOrientation()
double ns3::ParabolicAntennaModel::GetOrientation () const
Definition at line 86 of file parabolic-antenna-model.cc.
References m_orientationRadians, and ns3::RadiansToDegrees().
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::ParabolicAntennaModel::GetTypeId () static
Definition at line 38 of file parabolic-antenna-model.cc.
References GetBeamwidth(), GetOrientation(), m_maxAttenuation, ns3::MakeDoubleAccessor(), SetBeamwidth(), SetOrientation(), and ns3::TypeId::SetParent().
SetBeamwidth()
void ns3::ParabolicAntennaModel::SetBeamwidth (double beamwidthDegrees)
Definition at line 66 of file parabolic-antenna-model.cc.
References ns3::DegreesToRadians(), m_beamwidthRadians, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetOrientation()
void ns3::ParabolicAntennaModel::SetOrientation (double orientationDegrees)
Definition at line 79 of file parabolic-antenna-model.cc.
References ns3::DegreesToRadians(), m_orientationRadians, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
Member Data Documentation
m_beamwidthRadians
double ns3::ParabolicAntennaModel::m_beamwidthRadians private
Definition at line 64 of file parabolic-antenna-model.h.
Referenced by GetBeamwidth(), GetGainDb(), and SetBeamwidth().
m_maxAttenuation
double ns3::ParabolicAntennaModel::m_maxAttenuation private
Definition at line 68 of file parabolic-antenna-model.h.
Referenced by GetGainDb(), and GetTypeId().
m_orientationRadians
double ns3::ParabolicAntennaModel::m_orientationRadians private
Definition at line 66 of file parabolic-antenna-model.h.
Referenced by GetGainDb(), GetOrientation(), and SetOrientation().
The documentation for this class was generated from the following files:
src/antenna/model/parabolic-antenna-model.h
src/antenna/model/parabolic-antenna-model.cc