ns-3: InterferenceExperiment Class Reference
InterferenceExperiment Class Reference
InterferenceExperiment.
Classes
struct Input
Input structure.
Public Member Functions
InterferenceExperiment ()
void Run (struct InterferenceExperiment::Input input)
Run function.
Private Member Functions
void PacketDropped (Ptr< const Packet > packet, WifiPhyRxfailureReason reason)
Function triggered when a packet is dropped.
void SendA (void) const
Send A function.
void SendB (void) const
Send B function.
Private Attributes
bool m_droppedA
flag to indicate whether packet A has been dropped
bool m_droppedB
flag to indicate whether packet B has been dropped
struct Input m_input
input
Ptr< SpectrumWifiPhy > m_txA
transmit A function
Ptr< SpectrumWifiPhy > m_txB
transmit B function
uint64_t m_uidA
uint64_t m_uidB
Detailed Description
InterferenceExperiment.
Definition at line 79 of file wifi-test-interference-helper.cc.
Constructor & Destructor Documentation
InterferenceExperiment()
InterferenceExperiment::InterferenceExperiment ()
Definition at line 182 of file wifi-test-interference-helper.cc.
Member Function Documentation
PacketDropped()
void InterferenceExperiment::PacketDropped (Ptr< const Packet > packet, WifiPhyRxfailureReason reason) private
Function triggered when a packet is dropped.
Parameters
packet the packet that was dropped
reason the reason why it was dropped
Definition at line 165 of file wifi-test-interference-helper.cc.
References ns3::Packet::GetUid(), and NS_LOG_ERROR.
Referenced by Run().
Run()
void InterferenceExperiment::Run (struct InterferenceExperiment::Input input)
Run function.
Parameters
input the interference experiment data
Definition at line 212 of file wifi-test-interference-helper.cc.
References ns3::Node::AddDevice(), InterferenceExperiment::Input::captureEnabled, InterferenceExperiment::Input::captureMargin, third::channel, InterferenceExperiment::Input::channelA, InterferenceExperiment::Input::channelB, checkResults, ns3::SpectrumWifiPhy::ConfigureStandard(), ns3::SpectrumWifiPhy::CreateWifiSpectrumPhyInterface(), ns3::Object::Dispose(), expectRxASuccessfull, expectRxBSuccessfull, InterferenceExperiment::Input::interval, m_droppedA, m_droppedB, m_input, m_txA, m_txB, ns3::MakeCallback(), max, NS_LOG_ERROR, PacketDropped(), ns3::Seconds(), SendA(), SendB(), ns3::SpectrumWifiPhy::SetChannel(), ns3::SpectrumWifiPhy::SetChannelNumber(), ns3::Config::SetDefault(), ns3::WifiPhy::SetDevice(), ns3::WifiPhy::SetErrorRateModel(), ns3::WifiPhy::SetFrameCaptureModel(), ns3::SimpleFrameCaptureModel::SetMargin(), ns3::WifiPhy::SetMobility(), ns3::WifiNetDevice::SetPhy(), ns3::MobilityModel::SetPosition(), ns3::WifiPhy::SetTxPowerEnd(), ns3::WifiPhy::SetTxPowerStart(), InterferenceExperiment::Input::standard, ns3::ObjectBase::TraceConnectWithoutContext(), InterferenceExperiment::Input::txPowerLevelA, InterferenceExperiment::Input::txPowerLevelB, InterferenceExperiment::Input::xA, and InterferenceExperiment::Input::xB.
SendA()
void InterferenceExperiment::SendA (void) const private
Send A function.
Definition at line 133 of file wifi-test-interference-helper.cc.
References ns3::WifiMacHeader::GetSerializedSize(), ns3::Packet::GetUid(), ns3::WifiTxVector::SetChannelWidth(), ns3::WifiTxVector::SetMode(), ns3::WifiTxVector::SetPreambleType(), ns3::WifiTxVector::SetTxPowerLevel(), ns3::WifiMacHeader::SetType(), ns3::WIFI_MAC_CTL_ACK, and ns3::WIFI_MAC_FCS_LENGTH.
Referenced by Run().
SendB()
void InterferenceExperiment::SendB (void) const private
Send B function.
Definition at line 149 of file wifi-test-interference-helper.cc.
References ns3::WifiMacHeader::GetSerializedSize(), ns3::Packet::GetUid(), ns3::WifiTxVector::SetChannelWidth(), ns3::WifiTxVector::SetMode(), ns3::WifiTxVector::SetPreambleType(), ns3::WifiTxVector::SetTxPowerLevel(), ns3::WifiMacHeader::SetType(), ns3::WIFI_MAC_CTL_ACK, and ns3::WIFI_MAC_FCS_LENGTH.
Referenced by Run().
Member Data Documentation
m_droppedA
bool InterferenceExperiment::m_droppedA private
flag to indicate whether packet A has been dropped
Definition at line 126 of file wifi-test-interference-helper.cc.
Referenced by Run().
m_droppedB
bool InterferenceExperiment::m_droppedB private
flag to indicate whether packet B has been dropped
Definition at line 127 of file wifi-test-interference-helper.cc.
Referenced by Run().
m_input
struct Input InterferenceExperiment::m_input private
input
Definition at line 124 of file wifi-test-interference-helper.cc.
Referenced by Run().
m_txA
Ptr<SpectrumWifiPhy> InterferenceExperiment::m_txA private
transmit A function
Definition at line 123 of file wifi-test-interference-helper.cc.
Referenced by Run().
m_txB
Ptr<SpectrumWifiPhy> InterferenceExperiment::m_txB private
transmit B function
Definition at line 124 of file wifi-test-interference-helper.cc.
Referenced by Run().
m_uidA
uint64_t InterferenceExperiment::m_uidA mutable private
Definition at line 128 of file wifi-test-interference-helper.cc.
m_uidB
uint64_t InterferenceExperiment::m_uidB mutable private
Definition at line 129 of file wifi-test-interference-helper.cc.
The documentation for this class was generated from the following file:
src/wifi/examples/wifi-test-interference-helper.cc