ns-3: ns3::EnbMacMemberLteEnbPhySapUser Class Reference
ns3::EnbMacMemberLteEnbPhySapUser Class Reference
-------— PHY-SAP
Public Member Functions
EnbMacMemberLteEnbPhySapUser (LteEnbMac *mac)
Constructor.
virtual void DlInfoListElementHarqFeeback (DlInfoListElement_s params)
Notify the HARQ on the DL tranmission status.
virtual void ReceiveLteControlMessage (Ptr< LteControlMessage > msg)
Receive SendLteControlMessage (PDCCH map, CQI feedbacks) using the ideal control channel.
virtual void ReceivePhyPdu (Ptr< Packet > p)
Called by the Phy to notify the MAC of the reception of a new PHY-PDU.
virtual void ReceiveRachPreamble (uint32_t prachId)
notify the reception of a RACH preamble on the PRACH
virtual void SubframeIndication (uint32_t frameNo, uint32_t subframeNo)
Trigger the start from a new frame (input from Phy layer)
virtual void UlCqiReport (FfMacSchedSapProvider::SchedUlCqiInfoReqParameters ulcqi)
Returns to MAC level the UL-CQI evaluated.
virtual void UlInfoListElementHarqFeeback (UlInfoListElement_s params)
Notify the HARQ on the UL tranmission status.
Public Member Functions inherited from ns3::LteEnbPhySapUser
virtual ~LteEnbPhySapUser ()
Private Attributes
LteEnbMac * m_mac
the MAC
Detailed Description
-------— PHY-SAP
Definition at line 260 of file lte-enb-mac.cc.
Constructor & Destructor Documentation
EnbMacMemberLteEnbPhySapUser()
ns3::EnbMacMemberLteEnbPhySapUser::EnbMacMemberLteEnbPhySapUser (LteEnbMac * mac)
Constructor.
Parameters
mac the MAC
Definition at line 283 of file lte-enb-mac.cc.
Member Function Documentation
DlInfoListElementHarqFeeback()
void ns3::EnbMacMemberLteEnbPhySapUser::DlInfoListElementHarqFeeback (DlInfoListElement_s params) virtual
Notify the HARQ on the DL tranmission status.
Parameters
params
Implements ns3::LteEnbPhySapUser.
Definition at line 325 of file lte-enb-mac.cc.
References ns3::LteEnbMac::DoDlInfoListElementHarqFeeback(), m_mac, and aloha::params.
ReceiveLteControlMessage()
void ns3::EnbMacMemberLteEnbPhySapUser::ReceiveLteControlMessage (Ptr< LteControlMessage > msg) virtual
Receive SendLteControlMessage (PDCCH map, CQI feedbacks) using the ideal control channel.
Parameters
msg the Ideal Control Message to receive
Implements ns3::LteEnbPhySapUser.
Definition at line 301 of file lte-enb-mac.cc.
References ns3::LteEnbMac::DoReceiveLteControlMessage(), and m_mac.
ReceivePhyPdu()
void ns3::EnbMacMemberLteEnbPhySapUser::ReceivePhyPdu (Ptr< Packet > p) virtual
Called by the Phy to notify the MAC of the reception of a new PHY-PDU.
Parameters
p
Implements ns3::LteEnbPhySapUser.
Definition at line 289 of file lte-enb-mac.cc.
References ns3::LteEnbMac::DoReceivePhyPdu(), and m_mac.
ReceiveRachPreamble()
void ns3::EnbMacMemberLteEnbPhySapUser::ReceiveRachPreamble (uint32_t prachId) virtual
notify the reception of a RACH preamble on the PRACH
Parameters
prachId the ID of the preamble
Implements ns3::LteEnbPhySapUser.
Definition at line 307 of file lte-enb-mac.cc.
References ns3::LteEnbMac::DoReceiveRachPreamble(), and m_mac.
SubframeIndication()
void ns3::EnbMacMemberLteEnbPhySapUser::SubframeIndication (uint32_t frameNo, uint32_t subframeNo) virtual
Trigger the start from a new frame (input from Phy layer)
Parameters
frameNo frame number
subframeNo subframe number
Implements ns3::LteEnbPhySapUser.
Definition at line 295 of file lte-enb-mac.cc.
References ns3::LteEnbMac::DoSubframeIndication(), and m_mac.
UlCqiReport()
void ns3::EnbMacMemberLteEnbPhySapUser::UlCqiReport (FfMacSchedSapProvider::SchedUlCqiInfoReqParameters ulcqi) virtual
Returns to MAC level the UL-CQI evaluated.
Parameters
ulcqi the UL-CQI (see FF MAC API 4.3.29)
Implements ns3::LteEnbPhySapUser.
Definition at line 313 of file lte-enb-mac.cc.
References ns3::LteEnbMac::DoUlCqiReport(), and m_mac.
UlInfoListElementHarqFeeback()
void ns3::EnbMacMemberLteEnbPhySapUser::UlInfoListElementHarqFeeback (UlInfoListElement_s params) virtual
Notify the HARQ on the UL tranmission status.
Parameters
params
Implements ns3::LteEnbPhySapUser.
Definition at line 319 of file lte-enb-mac.cc.
References ns3::LteEnbMac::DoUlInfoListElementHarqFeeback(), m_mac, and aloha::params.
Member Data Documentation
m_mac
LteEnbMac* ns3::EnbMacMemberLteEnbPhySapUser::m_mac private
the MAC
Definition at line 280 of file lte-enb-mac.cc.
Referenced by DlInfoListElementHarqFeeback(), ReceiveLteControlMessage(), ReceivePhyPdu(), ReceiveRachPreamble(), SubframeIndication(), UlCqiReport(), and UlInfoListElementHarqFeeback().
The documentation for this class was generated from the following file:
src/lte/model/lte-enb-mac.cc