ns-3: IcmpV6TimeExceedTestCase Class Reference
IcmpV6TimeExceedTestCase Class Reference
Internet Applications » ICMP protocol tests | Test suites
ICMPV6 Time Exceed response test.
Public Member Functions
IcmpV6TimeExceedTestCase ()
virtual ~IcmpV6TimeExceedTestCase ()
void DoSendData (Ptr< Socket > socket, Ipv6Address dst)
void ReceivePkt (Ptr< Socket > socket)
void SendData (Ptr< Socket > socket, Ipv6Address dst)
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
Ptr< Packet > m_receivedPacket
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
ICMPV6 Time Exceed response test.
Definition at line 515 of file icmp-test.cc.
Constructor & Destructor Documentation
IcmpV6TimeExceedTestCase()
IcmpV6TimeExceedTestCase::IcmpV6TimeExceedTestCase ()
Definition at line 532 of file icmp-test.cc.
~IcmpV6TimeExceedTestCase()
IcmpV6TimeExceedTestCase::~IcmpV6TimeExceedTestCase () virtual
Definition at line 539 of file icmp-test.cc.
Member Function Documentation
DoRun()
void IcmpV6TimeExceedTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 608 of file icmp-test.cc.
References ns3::NodeContainer::Add(), first::address, ns3::Socket::Bind(), third::channel, first::devices, ns3::Ipv6InterfaceContainer::GetAddress(), ns3::Packet::GetSize(), ns3::SimpleNetDeviceHelper::Install(), ns3::InternetStackHelper::Install(), first::interfaces, m_receivedPacket, ns3::MakeCallback(), sample-rng-plot::n, n1n2, NS_TEST_EXPECT_MSG_EQ, ReceivePkt(), SendData(), ns3::ObjectBase::SetAttribute(), ns3::Ipv6InterfaceContainer::SetDefaultRouteInAllNodes(), ns3::Ipv6InterfaceContainer::SetForwarding(), ns3::Socket::SetIpv6HopLimit(), ns3::SimpleNetDeviceHelper::SetNetDevicePointToPointMode(), and ns3::Socket::SetRecvCallback().
DoSendData()
void IcmpV6TimeExceedTestCase::DoSendData (Ptr< Socket > socket, Ipv6Address dst)
Definition at line 546 of file icmp-test.cc.
References ns3::Packet::AddHeader(), ns3::Socket::SendTo(), ns3::Icmpv6Header::SetCode(), ns3::Icmpv6Echo::SetId(), ns3::Icmpv6Echo::SetSeq(), and ns3::Icmpv6Header::SetType().
Referenced by SendData().
ReceivePkt()
void IcmpV6TimeExceedTestCase::ReceivePkt (Ptr< Socket > socket)
Definition at line 577 of file icmp-test.cc.
References ns3::Packet::Copy(), ns3::Ipv6Header::GetNextHeader(), ns3::Icmpv6Header::GetType(), m_receivedPacket, NS_TEST_EXPECT_MSG_EQ, ns3::Socket::RecvFrom(), and ns3::Packet::RemoveHeader().
Referenced by DoRun().
SendData()
void IcmpV6TimeExceedTestCase::SendData (Ptr< Socket > socket, Ipv6Address dst)
Definition at line 568 of file icmp-test.cc.
References DoSendData(), ns3::Node::GetId(), ns3::Socket::GetNode(), m_receivedPacket, and ns3::Seconds().
Referenced by DoRun().
Member Data Documentation
m_receivedPacket
Ptr<Packet> IcmpV6TimeExceedTestCase::m_receivedPacket private
Definition at line 527 of file icmp-test.cc.
Referenced by DoRun(), ReceivePkt(), and SendData().
The documentation for this class was generated from the following file:
src/internet/test/icmp-test.cc