ns-3: GlobalRouteManagerImplTestCase Class Reference
GlobalRouteManagerImplTestCase Class Reference
Internet » internet module tests | Test suites
Global Route Manager Test.
Public Member Functions
GlobalRouteManagerImplTestCase ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Global Route Manager Test.
Definition at line 45 of file global-route-manager-impl-test-suite.cc.
Constructor & Destructor Documentation
GlobalRouteManagerImplTestCase()
GlobalRouteManagerImplTestCase::GlobalRouteManagerImplTestCase ()
Definition at line 52 of file global-route-manager-impl-test-suite.cc.
Member Function Documentation
DoRun()
void GlobalRouteManagerImplTestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Todo:
here we should do some verification of the routes built
Todo:
Testing
Implements ns3::TestCase.
Definition at line 57 of file global-route-manager-impl-test-suite.cc.
References ns3::GlobalRoutingLSA::AddLinkRecord(), ns3::GlobalRouteManagerImpl::DebugSPFCalculate(), ns3::GlobalRouteManagerImpl::DebugUseLsdb(), ns3::GlobalRoutingLSA::GetLinkStateId(), ns3::GlobalRouteManagerLSDB::GetLSA(), ns3::GlobalRouteManagerLSDB::Insert(), NS_ASSERT, ns3::CandidateQueue::Pop(), ns3::CandidateQueue::Push(), ns3::GlobalRoutingLSA::SetAdvertisingRouter(), ns3::SPFVertex::SetDistanceFromRoot(), ns3::GlobalRoutingLSA::SetLinkStateId(), and ns3::GlobalRoutingLSA::SetLSType().
The documentation for this class was generated from the following file:
src/internet/test/global-route-manager-impl-test-suite.cc