ns-3: CtrlBAckResponseHeaderTest Class Reference
CtrlBAckResponseHeaderTest Class Reference
Wifi Models » wifi module tests | Test suites
Test for block ack header.
Public Member Functions
CtrlBAckResponseHeaderTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun ()
Implementation to actually run this TestCase.
Private Attributes
CtrlBAckResponseHeader m_blockAckHdr
block ack header
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test for block ack header.
Definition at line 555 of file block-ack-test-suite.cc.
Constructor & Destructor Documentation
CtrlBAckResponseHeaderTest()
CtrlBAckResponseHeaderTest::CtrlBAckResponseHeaderTest ()
Definition at line 564 of file block-ack-test-suite.cc.
Member Function Documentation
DoRun()
void CtrlBAckResponseHeaderTest::DoRun () private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 570 of file block-ack-test-suite.cc.
References ns3::COMPRESSED_BLOCK_ACK, ns3::CtrlBAckResponseHeader::GetCompressedBitmap(), ns3::CtrlBAckResponseHeader::IsPacketReceived(), m_blockAckHdr, NS_TEST_EXPECT_MSG_EQ, ns3::CtrlBAckResponseHeader::ResetBitmap(), ns3::CtrlBAckResponseHeader::SetReceivedPacket(), ns3::CtrlBAckResponseHeader::SetStartingSequence(), and ns3::CtrlBAckResponseHeader::SetType().
Member Data Documentation
m_blockAckHdr
CtrlBAckResponseHeader CtrlBAckResponseHeaderTest::m_blockAckHdr private
block ack header
Definition at line 561 of file block-ack-test-suite.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/wifi/test/block-ack-test-suite.cc