ns-3: ns3::SocketIpTtlTag Class Reference
ns3::SocketIpTtlTag Class Reference
This class implements a tag that carries the socket-specific TTL of a packet to the IP layer.
#include "socket.h"
Public Member Functions
SocketIpTtlTag ()
virtual void Deserialize (TagBuffer i)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize (void) const
uint8_t GetTtl (void) const
Get the tag's TTL.
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer i) const
void SetTtl (uint8_t ttl)
Set the tag's TTL.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_ttl
the ttl carried by the tag
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class implements a tag that carries the socket-specific TTL of a packet to the IP layer.
Definition at line 1115 of file socket.h.
Constructor & Destructor Documentation
SocketIpTtlTag()
ns3::SocketIpTtlTag::SocketIpTtlTag ()
Definition at line 598 of file socket.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Deserialize()
void ns3::SocketIpTtlTag::Deserialize (TagBuffer i) virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 648 of file socket.cc.
References m_ttl, NS_LOG_FUNCTION, and ns3::TagBuffer::ReadU8().
GetInstanceTypeId()
TypeId ns3::SocketIpTtlTag::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 630 of file socket.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::SocketIpTtlTag::GetSerializedSize (void) const virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 636 of file socket.cc.
References NS_LOG_FUNCTION.
GetTtl()
uint8_t ns3::SocketIpTtlTag::GetTtl (void) const
Get the tag's TTL.
Returns
the TTL
Definition at line 611 of file socket.cc.
References m_ttl, and NS_LOG_FUNCTION.
Referenced by ns3::Rip::Receive(), ReceivePacket(), ns3::aodv::RoutingProtocol::RecvReply(), ns3::aodv::RoutingProtocol::RecvRequest(), and ns3::Ipv4L3Protocol::Send().
GetTypeId()
TypeId ns3::SocketIpTtlTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 620 of file socket.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::SocketIpTtlTag::Print (std::ostream & os) const virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 654 of file socket.cc.
References m_ttl, and NS_LOG_FUNCTION.
Serialize()
void ns3::SocketIpTtlTag::Serialize (TagBuffer i) const virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 642 of file socket.cc.
References m_ttl, NS_LOG_FUNCTION, and ns3::TagBuffer::WriteU8().
SetTtl()
void ns3::SocketIpTtlTag::SetTtl (uint8_t ttl)
Set the tag's TTL.
Parameters
ttl the TTL
Definition at line 604 of file socket.cc.
References m_ttl, and NS_LOG_FUNCTION.
Referenced by ns3::TcpSocketBase::AddSocketTags(), ns3::Rip::DoSendRouteUpdate(), ns3::UdpSocketImpl::DoSendTo(), ns3::Ipv4RawSocketImpl::ForwardUp(), ns3::UdpSocketImpl::ForwardUp(), ns3::Rip::HandleRequests(), ns3::dsr::DsrOptionRreq::Process(), ns3::aodv::RoutingProtocol::RecvError(), ns3::aodv::RoutingProtocol::RecvReply(), ns3::aodv::RoutingProtocol::RecvRequest(), ns3::dsr::DsrRouting::RouteRequestTimerExpire(), ns3::Radvd::Send(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), ns3::dsr::DsrRouting::SendErrorRequest(), ns3::aodv::RoutingProtocol::SendHello(), ns3::dsr::DsrRouting::SendInitialRequest(), ns3::aodv::RoutingProtocol::SendReply(), ns3::aodv::RoutingProtocol::SendReplyAck(), ns3::aodv::RoutingProtocol::SendReplyByIntermediateNode(), ns3::aodv::RoutingProtocol::SendRequest(), ns3::aodv::RoutingProtocol::SendRerrWhenBreaksLinkToNextHop(), ns3::aodv::RoutingProtocol::SendRerrWhenNoRouteToForward(), ns3::Rip::SendRouteRequest(), and ns3::Ipv4RawSocketImpl::SendTo().
Member Data Documentation
m_ttl
uint8_t ns3::SocketIpTtlTag::m_ttl private
the ttl carried by the tag
Definition at line 1156 of file socket.h.
Referenced by Deserialize(), GetTtl(), Print(), Serialize(), and SetTtl().
The documentation for this class was generated from the following files:
src/network/model/socket.h
src/network/model/socket.cc