ns-3: ns3::DataOutputCallback Class Reference
ns3::DataOutputCallback Class Reference abstract
Statistics » Data Output
Callback class for the DataOutput classes.
#include "data-output-interface.h"
Public Member Functions
virtual ~DataOutputCallback ()
Destructor.
virtual void OutputSingleton (std::string key, std::string variable, double val)=0
Associates the double value with the variable name for a specific output format.
virtual void OutputSingleton (std::string key, std::string variable, int val)=0
Associates the integer value with the variable name for a specific output format.
virtual void OutputSingleton (std::string key, std::string variable, std::string val)=0
Associates the string value with the variable name for a specific output format.
virtual void OutputSingleton (std::string key, std::string variable, Time val)=0
Associates the Time value with the variable name for a specific output format.
virtual void OutputSingleton (std::string key, std::string variable, uint32_t val)=0
Associates the uint32_t value with the variable name for a specific output format.
virtual void OutputStatistic (std::string key, std::string variable, const StatisticalSummary *statSum)=0
Outputs the data from the specified StatisticalSummary.
Detailed Description
Callback class for the DataOutput classes.
Definition at line 81 of file data-output-interface.h.
Constructor & Destructor Documentation
~DataOutputCallback()
virtual ns3::DataOutputCallback::~DataOutputCallback () inline virtual
Destructor.
Definition at line 86 of file data-output-interface.h.
Member Function Documentation
OutputSingleton() [1/5]
virtual void ns3::DataOutputCallback::OutputSingleton (std::string key, std::string variable, double val) pure virtual
Associates the double value with the variable name for a specific output format.
Parameters
key Key value of a DataCalculator
variable Name of the variable for which statistics are being provided
val Value to be stored
Implemented in ns3::SqliteDataOutput::SqliteOutputCallback, and ns3::OmnetDataOutput::OmnetOutputCallback.
OutputSingleton() [2/5]
virtual void ns3::DataOutputCallback::OutputSingleton (std::string key, std::string variable, int val) pure virtual
Associates the integer value with the variable name for a specific output format.
Parameters
key Key value of a DataCalculator
variable Name of the variable for which statistics are being provided
val Value to be stored
Implemented in ns3::SqliteDataOutput::SqliteOutputCallback, and ns3::OmnetDataOutput::OmnetOutputCallback.
Referenced by ns3::CounterCalculator< T >::Output(), and ns3::TimeMinMaxAvgTotalCalculator::Output().
OutputSingleton() [3/5]
virtual void ns3::DataOutputCallback::OutputSingleton (std::string key, std::string variable, std::string val) pure virtual
Associates the string value with the variable name for a specific output format.
Parameters
key Key value of a DataCalculator
variable Name of the variable for which statistics are being provided
val Value to be stored
Implemented in ns3::SqliteDataOutput::SqliteOutputCallback, and ns3::OmnetDataOutput::OmnetOutputCallback.
OutputSingleton() [4/5]
virtual void ns3::DataOutputCallback::OutputSingleton (std::string key, std::string variable, Time val) pure virtual
Associates the Time value with the variable name for a specific output format.
Parameters
key Key value of a DataCalculator
variable Name of the variable for which statistics are being provided
val Value to be stored
Implemented in ns3::SqliteDataOutput::SqliteOutputCallback, and ns3::OmnetDataOutput::OmnetOutputCallback.
OutputSingleton() [5/5]
virtual void ns3::DataOutputCallback::OutputSingleton (std::string key, std::string variable, uint32_t val) pure virtual
Associates the uint32_t value with the variable name for a specific output format.
Parameters
key Key value of a DataCalculator
variable Name of the variable for which statistics are being provided
val Value to be stored
Implemented in ns3::SqliteDataOutput::SqliteOutputCallback, and ns3::OmnetDataOutput::OmnetOutputCallback.
OutputStatistic()
virtual void ns3::DataOutputCallback::OutputStatistic (std::string key, std::string variable, const StatisticalSummary * statSum) pure virtual
Outputs the data from the specified StatisticalSummary.
Parameters
key Key value of a DataCalculator
variable Name of the variable for which statistics are being provided
statSum Pointer to a StatisticalSummary object
Implemented in ns3::SqliteDataOutput::SqliteOutputCallback, and ns3::OmnetDataOutput::OmnetOutputCallback.
Referenced by ns3::MinMaxAvgTotalCalculator< T >::Output().
The documentation for this class was generated from the following file:
src/stats/model/data-output-interface.h