ns-3: ns3::TcpClassicRecovery Class Reference
ns3::TcpClassicRecovery Class Reference
The Classic recovery implementation.
#include "tcp-recovery-ops.h"
Public Member Functions
TcpClassicRecovery ()
Constructor.
TcpClassicRecovery (const TcpClassicRecovery &recovery)
Copy constructor.
virtual ~TcpClassicRecovery () override
Constructor.
virtual void DoRecovery (Ptr< TcpSocketState > tcb, uint32_t deliveredBytes) override
Performs recovery based on the recovery algorithm.
virtual void EnterRecovery (Ptr< TcpSocketState > tcb, uint32_t dupAckCount, uint32_t unAckDataCount, uint32_t deliveredBytes) override
Performs variable initialization at the start of recovery.
virtual void ExitRecovery (Ptr< TcpSocketState > tcb) override
Performs cwnd adjustments at the end of recovery.
virtual Ptr< TcpRecoveryOps > Fork () override
Copy the recovery algorithm across socket.
virtual std::string GetName () const override
Get the name of the recovery algorithm.
Public Member Functions inherited from ns3::TcpRecoveryOps
TcpRecoveryOps ()
Constructor.
TcpRecoveryOps (const TcpRecoveryOps &other)
Copy constructor.
virtual ~TcpRecoveryOps ()
Deconstructor.
virtual void UpdateBytesSent (uint32_t bytesSent)
Keeps track of bytes sent during recovery phase.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpRecoveryOps
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The Classic recovery implementation.
Classic recovery refers to the two well-established recovery algorithms, namely, NewReno (RFC 6582) and SACK based recovery (RFC 6675).
The idea of the algorithm is that when we enter recovery, we set the congestion window value to the slow start threshold and maintain it at such value until we are fully recovered (in other words, until the highest sequence transmitted at time of detecting the loss is ACKed by the receiver).
See also
DoRecovery
Definition at line 159 of file tcp-recovery-ops.h.
Constructor & Destructor Documentation
TcpClassicRecovery() [1/2]
ns3::TcpClassicRecovery::TcpClassicRecovery ()
Constructor.
Definition at line 80 of file tcp-recovery-ops.cc.
References NS_LOG_FUNCTION.
TcpClassicRecovery() [2/2]
ns3::TcpClassicRecovery::TcpClassicRecovery (const TcpClassicRecovery & recovery)
Copy constructor.
Parameters
recovery object to copy.
Definition at line 85 of file tcp-recovery-ops.cc.
References NS_LOG_FUNCTION.
~TcpClassicRecovery()
ns3::TcpClassicRecovery::~TcpClassicRecovery () override virtual
Constructor.
Definition at line 91 of file tcp-recovery-ops.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoRecovery()
void ns3::TcpClassicRecovery::DoRecovery (Ptr< TcpSocketState > tcb, uint32_t deliveredBytes) override virtual
Performs recovery based on the recovery algorithm.
The function is called on arrival of every ack when TcpSocketState is set to CA_RECOVERY. It performs the necessary cwnd changes as per the recovery algorithm.
Parameters
tcb internal congestion state
deliveredBytes bytes (S)ACKed in the last (S)ACK
Implements ns3::TcpRecoveryOps.
Reimplemented in ns3::TcpPrrRecovery.
Definition at line 108 of file tcp-recovery-ops.cc.
References ns3::TcpSocketState::m_cWndInfl, ns3::TcpSocketState::m_segmentSize, NS_LOG_FUNCTION, and NS_UNUSED.
Referenced by ClassicRecoveryTest::DoRun().
EnterRecovery()
void ns3::TcpClassicRecovery::EnterRecovery (Ptr< TcpSocketState > tcb, uint32_t dupAckCount, uint32_t unAckDataCount, uint32_t deliveredBytes) override virtual
Performs variable initialization at the start of recovery.
The function is called when the TcpSocketState is changed to CA_RECOVERY.
Parameters
tcb internal congestion state
dupAckCount duplicate acknowldgement count
unAckDataCount total bytes of data unacknowledged
deliveredBytes bytes (S)ACKed in the last (S)ACK
Implements ns3::TcpRecoveryOps.
Reimplemented in ns3::TcpPrrRecovery.
Definition at line 97 of file tcp-recovery-ops.cc.
References ns3::TcpSocketState::m_cWnd, ns3::TcpSocketState::m_cWndInfl, ns3::TcpSocketState::m_segmentSize, ns3::TcpSocketState::m_ssThresh, NS_LOG_FUNCTION, and NS_UNUSED.
Referenced by ClassicRecoveryTest::DoRun().
ExitRecovery()
void ns3::TcpClassicRecovery::ExitRecovery (Ptr< TcpSocketState > tcb) override virtual
Performs cwnd adjustments at the end of recovery.
The function is called when the TcpSocketState is changed from CA_RECOVERY.
Parameters
tcb internal congestion state
isSackEnabled
Implements ns3::TcpRecoveryOps.
Reimplemented in ns3::TcpPrrRecovery.
Definition at line 116 of file tcp-recovery-ops.cc.
References ns3::TracedValue< T >::Get(), ns3::TcpSocketState::m_cWndInfl, ns3::TcpSocketState::m_ssThresh, and NS_LOG_FUNCTION.
Referenced by ClassicRecoveryTest::DoRun().
Fork()
Ptr< TcpRecoveryOps > ns3::TcpClassicRecovery::Fork () override virtual
Copy the recovery algorithm across socket.
Returns
a pointer of the copied object
Implements ns3::TcpRecoveryOps.
Reimplemented in ns3::TcpPrrRecovery.
Definition at line 134 of file tcp-recovery-ops.cc.
GetName()
std::string ns3::TcpClassicRecovery::GetName () const override virtual
Get the name of the recovery algorithm.
Returns
A string identifying the name
Implements ns3::TcpRecoveryOps.
Reimplemented in ns3::TcpPrrRecovery.
Definition at line 128 of file tcp-recovery-ops.cc.
Referenced by ClassicRecoveryTest::DoRun().
GetTypeId()
TypeId ns3::TcpClassicRecovery::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 70 of file tcp-recovery-ops.cc.
References ns3::TypeId::SetParent().
Referenced by ns3::TcpL4Protocol::GetTypeId().
The documentation for this class was generated from the following files:
src/internet/model/tcp-recovery-ops.h
src/internet/model/tcp-recovery-ops.cc