ns-3: TwoLevelAggregationTest Class Reference
TwoLevelAggregationTest Class Reference
Wifi Models » wifi module tests | Test suites
Two Level Aggregation Test.
Public Member Functions
TwoLevelAggregationTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
Ptr< WifiNetDevice > m_device
WifiNetDevice.
ObjectFactory m_factory
factory
Ptr< StaWifiMac > m_mac
Mac.
Ptr< WifiRemoteStationManager > m_manager
remote station manager
Ptr< YansWifiPhy > m_phy
Phy.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Two Level Aggregation Test.
Definition at line 259 of file wifi-aggregation-test.cc.
Constructor & Destructor Documentation
TwoLevelAggregationTest()
TwoLevelAggregationTest::TwoLevelAggregationTest ()
Definition at line 273 of file wifi-aggregation-test.cc.
Member Function Documentation
DoRun()
void TwoLevelAggregationTest::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 279 of file wifi-aggregation-test.cc.
References ns3::WifiRemoteStationManager::AddStationHtCapabilities(), ns3::WifiMac::ConfigureStandard(), ns3::WifiPhy::ConfigureStandard(), ns3::ObjectFactory::Create(), ns3::Object::Dispose(), ns3::WifiMacHeader::GetAddr1(), ns3::RegularWifiMac::GetBEQueue(), ns3::Txop::GetLow(), ns3::WifiMacQueueItem::GetPacket(), ns3::Packet::GetSize(), ns3::WifiPsdu::GetSize(), ns3::Txop::GetTxopLimit(), ns3::RegularWifiMac::GetVIQueue(), ns3::Txop::GetWifiMacQueue(), ns3::QosTxop::m_baManager, m_device, m_factory, m_mac, m_manager, m_phy, NS_TEST_EXPECT_MSG_EQ, ns3::ObjectFactory::Set(), ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetAddr2(), ns3::RegularWifiMac::SetAddress(), ns3::ObjectBase::SetAttribute(), ns3::MgtAddBaRequestHeader::SetBufferSize(), ns3::WifiMac::SetDevice(), ns3::WifiPhy::SetDevice(), ns3::WifiNetDevice::SetHtConfiguration(), ns3::MgtAddBaRequestHeader::SetImmediateBlockAck(), ns3::WifiNetDevice::SetMac(), ns3::HtCapabilities::SetMaxAmpduLength(), ns3::HtCapabilities::SetMaxAmsduLength(), ns3::WifiNetDevice::SetPhy(), ns3::WifiMacHeader::SetQosTid(), ns3::WifiNetDevice::SetRemoteStationManager(), ns3::MgtAddBaRequestHeader::SetStartingSequence(), ns3::MgtAddBaRequestHeader::SetTid(), ns3::MgtAddBaRequestHeader::SetTimeout(), ns3::WifiMacHeader::SetType(), ns3::ObjectFactory::SetTypeId(), ns3::WifiRemoteStationManager::SetupPhy(), ns3::StaWifiMac::SetWifiPhy(), ns3::StaWifiMac::SetWifiRemoteStationManager(), ns3::WIFI_MAC_QOSDATA, and ns3::WIFI_PHY_STANDARD_80211n_5GHZ.
Member Data Documentation
m_device
Ptr<WifiNetDevice> TwoLevelAggregationTest::m_device private
WifiNetDevice.
Definition at line 266 of file wifi-aggregation-test.cc.
Referenced by DoRun().
m_factory
ObjectFactory TwoLevelAggregationTest::m_factory private
factory
Definition at line 270 of file wifi-aggregation-test.cc.
Referenced by DoRun().
m_mac
Ptr<StaWifiMac> TwoLevelAggregationTest::m_mac private
Mac.
Definition at line 267 of file wifi-aggregation-test.cc.
Referenced by DoRun().
m_manager
Ptr<WifiRemoteStationManager> TwoLevelAggregationTest::m_manager private
remote station manager
Definition at line 269 of file wifi-aggregation-test.cc.
Referenced by DoRun().
m_phy
Ptr<YansWifiPhy> TwoLevelAggregationTest::m_phy private
Phy.
Definition at line 268 of file wifi-aggregation-test.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/wifi/test/wifi-aggregation-test.cc