ns-3: ns3::MgtDelBaHeader Class Reference
ns3::MgtDelBaHeader Class Reference
Wifi Models
#include "mgt-headers.h"
Public Member Functions
MgtDelBaHeader ()
uint32_t Deserialize (Buffer::Iterator start)
TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint32_t GetSerializedSize (void) const
uint8_t GetTid (void) const
Return the Traffic ID (TID).
bool IsByOriginator (void) const
Check if the initiator bit in the DELBA is set.
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetByOriginator (void)
Set the initiator bit in the DELBA.
void SetByRecipient (void)
Un-set the initiator bit in the DELBA.
void SetTid (uint8_t tid)
Set Traffic ID (TID).
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
uint16_t GetParameterSet (void) const
Return the raw parameter set.
void SetParameterSet (uint16_t params)
Set the parameter set from the given raw value.
Private Attributes
uint16_t m_initiator
initiator
uint16_t m_reasonCode
Not used for now.
uint16_t m_tid
Traffic ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implement the header for management frames of type Delete Block Ack.
Definition at line 1256 of file mgt-headers.h.
Constructor & Destructor Documentation
MgtDelBaHeader()
ns3::MgtDelBaHeader::MgtDelBaHeader ()
Definition at line 1797 of file mgt-headers.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::MgtDelBaHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 1842 of file mgt-headers.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_reasonCode, ns3::Buffer::Iterator::ReadLsbtohU16(), SetParameterSet(), and visualizer.core::start().
GetInstanceTypeId()
TypeId ns3::MgtDelBaHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 1814 of file mgt-headers.cc.
References GetTypeId().
GetParameterSet()
uint16_t ns3::MgtDelBaHeader::GetParameterSet (void) const private
Return the raw parameter set.
Returns
the raw parameter set
Definition at line 1884 of file mgt-headers.cc.
References m_initiator, and m_tid.
Referenced by Serialize().
GetSerializedSize()
uint32_t ns3::MgtDelBaHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 1825 of file mgt-headers.cc.
GetTid()
uint8_t ns3::MgtDelBaHeader::GetTid (void) const
Return the Traffic ID (TID).
Returns
TID
Definition at line 1857 of file mgt-headers.cc.
References m_tid, and NS_ASSERT.
Referenced by ns3::GetTid(), ns3::QosTxop::GotAck(), ns3::QosTxop::GotDelBaFrame(), and ns3::RegularWifiMac::Receive().
GetTypeId()
TypeId ns3::MgtDelBaHeader::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 1803 of file mgt-headers.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
IsByOriginator()
bool ns3::MgtDelBaHeader::IsByOriginator (void) const
Check if the initiator bit in the DELBA is set.
Returns
true if the initiator bit in the DELBA is set, false otherwise
Definition at line 1851 of file mgt-headers.cc.
References m_initiator.
Referenced by ns3::QosTxop::GotAck(), and ns3::RegularWifiMac::Receive().
Print()
void ns3::MgtDelBaHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 1820 of file mgt-headers.cc.
Serialize()
void ns3::MgtDelBaHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 1834 of file mgt-headers.cc.
References GetParameterSet(), m_reasonCode, visualizer.core::start(), and ns3::Buffer::Iterator::WriteHtolsbU16().
SetByOriginator()
void ns3::MgtDelBaHeader::SetByOriginator (void)
Set the initiator bit in the DELBA.
Definition at line 1865 of file mgt-headers.cc.
References m_initiator.
Referenced by ns3::QosTxop::SendDelbaFrame().
SetByRecipient()
void ns3::MgtDelBaHeader::SetByRecipient (void)
Un-set the initiator bit in the DELBA.
Definition at line 1871 of file mgt-headers.cc.
References m_initiator.
Referenced by ns3::QosTxop::SendDelbaFrame().
SetParameterSet()
void ns3::MgtDelBaHeader::SetParameterSet (uint16_t params) private
Set the parameter set from the given raw value.
Parameters
params raw parameter set value
Definition at line 1893 of file mgt-headers.cc.
References m_initiator, m_tid, and aloha::params.
Referenced by Deserialize().
SetTid()
void ns3::MgtDelBaHeader::SetTid (uint8_t tid)
Set Traffic ID (TID).
Parameters
tid traffic ID
Definition at line 1877 of file mgt-headers.cc.
References m_tid, and NS_ASSERT.
Referenced by ns3::QosTxop::SendDelbaFrame().
Member Data Documentation
m_initiator
uint16_t ns3::MgtDelBaHeader::m_initiator private
initiator
Definition at line 1316 of file mgt-headers.h.
Referenced by GetParameterSet(), IsByOriginator(), SetByOriginator(), SetByRecipient(), and SetParameterSet().
m_reasonCode
uint16_t ns3::MgtDelBaHeader::m_reasonCode private
Not used for now.
Always set to 1: "Unspecified reason"
Definition at line 1318 of file mgt-headers.h.
Referenced by Deserialize(), and Serialize().
m_tid
uint16_t ns3::MgtDelBaHeader::m_tid private
Traffic ID.
Definition at line 1317 of file mgt-headers.h.
Referenced by GetParameterSet(), GetTid(), SetParameterSet(), and SetTid().
The documentation for this class was generated from the following files:
src/wifi/model/mgt-headers.h
src/wifi/model/mgt-headers.cc