ns-3: ns3::ThreeGppRmaPropagationLossModel Class Reference
ns3::ThreeGppRmaPropagationLossModel Class Reference
Propagation Models
Implements the pathloss model defined in 3GPP TR 38.901, Table 7.4.1-1 for the RMa scenario.
#include "three-gpp-propagation-loss-model.h"
Public Member Functions
ThreeGppRmaPropagationLossModel ()
Constructor.
ThreeGppRmaPropagationLossModel (const ThreeGppRmaPropagationLossModel &)=delete
Copy constructor.
virtual ~ThreeGppRmaPropagationLossModel () override
Destructor.
ThreeGppRmaPropagationLossModel & operator= (const ThreeGppRmaPropagationLossModel &)=delete
Copy constructor.
Public Member Functions inherited from ns3::ThreeGppPropagationLossModel
ThreeGppPropagationLossModel ()
Constructor.
ThreeGppPropagationLossModel (const ThreeGppPropagationLossModel &)=delete
Copy constructor.
virtual ~ThreeGppPropagationLossModel () override
Destructor.
Ptr< ChannelConditionModel > GetChannelConditionModel (void) const
Returns the associated channel condition model.
double GetFrequency (void) const
Return the current central frequency.
ThreeGppPropagationLossModel & operator= (const ThreeGppPropagationLossModel &)=delete
Copy constructor.
void SetChannelConditionModel (Ptr< ChannelConditionModel > model)
Set the channel condition model used to determine the channel state (e.g., the LOS/NLOS condition)
void SetFrequency (double f)
Set the central frequency of the model.
Public Member Functions inherited from ns3::PropagationLossModel
PropagationLossModel ()
virtual ~PropagationLossModel ()
int64_t AssignStreams (int64_t stream)
If this loss model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
double CalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account all the PropagationLossModel(s) chained to the current one.
Ptr< PropagationLossModel > GetNext ()
Gets the next PropagationLossModel in the chain of loss models that act on the signal.
void SetNext (Ptr< PropagationLossModel > next)
Enables a chain of loss models to act on the signal.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ThreeGppPropagationLossModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::PropagationLossModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual double GetLossLos (double distance2D, double distance3D, double hUt, double hBs) const override
Computes the pathloss between a and b considering that the line of sight is not obstructed.
virtual double GetLossNlos (double distance2D, double distance3D, double hUt, double hBs) const override
Computes the pathloss between a and b considering that the line of sight is obstructed.
virtual double GetShadowingCorrelationDistance (ChannelCondition::LosConditionValue cond) const override
Returns the shadow fading correlation distance.
virtual double GetShadowingStd (Ptr< MobilityModel > a, Ptr< MobilityModel > b, ChannelCondition::LosConditionValue cond) const override
Returns the shadow fading standard deviation.
Static Private Member Functions
static double GetBpDistance (double frequency, double hA, double hB)
Computes the breakpoint distance for the RMa scenario.
static double Pl1 (double frequency, double distance3D, double h, double w)
Computes the PL1 formula for the RMa scenario.
Private Attributes
double m_h
average building height in meters
double m_w
average street width in meters
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Static Protected Member Functions inherited from ns3::ThreeGppPropagationLossModel
static double Calculate2dDistance (Vector a, Vector b)
Computes the 2D distance between two 3D vectors.
Protected Attributes inherited from ns3::ThreeGppPropagationLossModel
Ptr< ChannelConditionModel > m_channelConditionModel
pointer to the channel condition model
double m_frequency
operating frequency in Hz
Ptr< NormalRandomVariable > m_normRandomVariable
normal random variable
bool m_shadowingEnabled
enable/disable shadowing
std::unordered_map< uint32_t, ShadowingMapItem > m_shadowingMap
map to store the shadowing values
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implements the pathloss model defined in 3GPP TR 38.901, Table 7.4.1-1 for the RMa scenario.
Definition at line 232 of file three-gpp-propagation-loss-model.h.
Constructor & Destructor Documentation
ThreeGppRmaPropagationLossModel() [1/2]
ns3::ThreeGppRmaPropagationLossModel::ThreeGppRmaPropagationLossModel ()
Constructor.
Definition at line 291 of file three-gpp-propagation-loss-model.cc.
References ns3::ThreeGppPropagationLossModel::m_channelConditionModel, and NS_LOG_FUNCTION.
~ThreeGppRmaPropagationLossModel()
ns3::ThreeGppRmaPropagationLossModel::~ThreeGppRmaPropagationLossModel () override virtual
Destructor.
Definition at line 300 of file three-gpp-propagation-loss-model.cc.
References NS_LOG_FUNCTION.
ThreeGppRmaPropagationLossModel() [2/2]
ns3::ThreeGppRmaPropagationLossModel::ThreeGppRmaPropagationLossModel (const ThreeGppRmaPropagationLossModel &) delete
Copy constructor.
Defined and unimplemented to avoid misuse
Member Function Documentation
GetBpDistance()
double ns3::ThreeGppRmaPropagationLossModel::GetBpDistance (double frequency, double hA, double hB) static private
Computes the breakpoint distance for the RMa scenario.
Parameters
frequency the operating frequency in Hz
hA height of the tx node in meters
hB height of the rx node in meters
Returns
the breakpoint distance in meters
Definition at line 463 of file three-gpp-propagation-loss-model.cc.
References ns3::M_C.
Referenced by GetLossLos(), and GetShadowingStd().
GetLossLos()
double ns3::ThreeGppRmaPropagationLossModel::GetLossLos (double distance2D, double distance3D, double hUt, double hBs) const override private virtual
Computes the pathloss between a and b considering that the line of sight is not obstructed.
Parameters
distance2D the 2D distance between tx and rx in meters
distance3D the 3D distance between tx and rx in meters
hUt the height of the UT in meters
hBs the height of the BS in meters
Returns
pathloss value in dB
Implements ns3::ThreeGppPropagationLossModel.
Definition at line 306 of file three-gpp-propagation-loss-model.cc.
References GetBpDistance(), ns3::ThreeGppPropagationLossModel::m_frequency, m_h, m_w, NS_ASSERT_MSG(), NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_WARN, and Pl1().
Referenced by GetLossNlos().
GetLossNlos()
double ns3::ThreeGppRmaPropagationLossModel::GetLossNlos (double distance2D, double distance3D, double hUt, double hBs) const override private virtual
Computes the pathloss between a and b considering that the line of sight is obstructed.
Parameters
distance2D the 2D distance between tx and rx in meters
distance3D the 3D distance between tx and rx in meters
hUt the height of the UT in meters
hBs the height of the BS in meters
Returns
pathloss value in dB
Implements ns3::ThreeGppPropagationLossModel.
Definition at line 357 of file three-gpp-propagation-loss-model.cc.
References GetLossLos(), ns3::ThreeGppPropagationLossModel::m_frequency, m_h, m_w, max, NS_ASSERT_MSG(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and NS_LOG_WARN.
GetShadowingCorrelationDistance()
double ns3::ThreeGppRmaPropagationLossModel::GetShadowingCorrelationDistance (ChannelCondition::LosConditionValue cond) const override private virtual
Returns the shadow fading correlation distance.
Parameters
cond the LOS/NLOS channel condition
Returns
shadowing correlation distance in meters
Implements ns3::ThreeGppPropagationLossModel.
Definition at line 432 of file three-gpp-propagation-loss-model.cc.
References NS_FATAL_ERROR, and NS_LOG_FUNCTION.
GetShadowingStd()
double ns3::ThreeGppRmaPropagationLossModel::GetShadowingStd (Ptr< MobilityModel > a, Ptr< MobilityModel > b, ChannelCondition::LosConditionValue cond) const override private virtual
Returns the shadow fading standard deviation.
Parameters
a tx mobility model
b rx mobility model
cond the LOS/NLOS channel condition
Returns
shadowing std in dB
Implements ns3::ThreeGppPropagationLossModel.
Definition at line 397 of file three-gpp-propagation-loss-model.cc.
References ns3::ThreeGppPropagationLossModel::Calculate2dDistance(), GetBpDistance(), ns3::MobilityModel::GetPosition(), ns3::ThreeGppPropagationLossModel::m_frequency, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::ThreeGppRmaPropagationLossModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 273 of file three-gpp-propagation-loss-model.cc.
References m_h, m_w, ns3::MakeDoubleAccessor(), and ns3::TypeId::SetParent().
operator=()
ThreeGppRmaPropagationLossModel& ns3::ThreeGppRmaPropagationLossModel::operator= (const ThreeGppRmaPropagationLossModel &) delete
Copy constructor.
Defined and unimplemented to avoid misuse
Returns
the ThreeGppRmaPropagationLossModel instance
Pl1()
double ns3::ThreeGppRmaPropagationLossModel::Pl1 (double frequency, double distance3D, double h, double w) static private
Computes the PL1 formula for the RMa scenario.
Parameters
frequency the operating frequency in Hz
distance3D the 3D distance between the tx and the rx nodes in meters
h the average building height in meters
w the average street width in meters
Returns
result of the PL1 formula
Definition at line 455 of file three-gpp-propagation-loss-model.cc.
References min, and NS_UNUSED.
Referenced by GetLossLos().
Member Data Documentation
m_h
double ns3::ThreeGppRmaPropagationLossModel::m_h private
average building height in meters
Definition at line 324 of file three-gpp-propagation-loss-model.h.
Referenced by GetLossLos(), GetLossNlos(), and GetTypeId().
m_w
double ns3::ThreeGppRmaPropagationLossModel::m_w private
average street width in meters
Definition at line 325 of file three-gpp-propagation-loss-model.h.
Referenced by GetLossLos(), GetLossNlos(), and GetTypeId().
The documentation for this class was generated from the following files:
src/propagation/model/three-gpp-propagation-loss-model.h
src/propagation/model/three-gpp-propagation-loss-model.cc