ns-3: ns3::ApplicationPacketProbe Class Reference
ns3::ApplicationPacketProbe Class Reference
Probe to translate from a TraceSource to two more easily parsed TraceSources.
#include "application-packet-probe.h"
Public Member Functions
ApplicationPacketProbe ()
virtual ~ApplicationPacketProbe ()
virtual bool ConnectByObject (std::string traceSource, Ptr< Object > obj)
connect to a trace source attribute provided by a given object
virtual void ConnectByPath (std::string path)
connect to a trace source provided by a config path
void SetValue (Ptr< const Packet > packet, const Address &address)
Set a probe value.
Public Member Functions inherited from ns3::Probe
Probe ()
virtual ~Probe ()
virtual bool IsEnabled (void) const
Public Member Functions inherited from ns3::DataCollectionObject
DataCollectionObject ()
virtual ~DataCollectionObject ()
void Disable (void)
Unset the status of an individual object.
void Enable (void)
Set the status of an individual object.
std::string GetName (void) const
Get the object's name.
void SetName (std::string name)
Set the object's name. All spaces are replaced by underscores.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
static void SetValueByPath (std::string path, Ptr< const Packet > packet, const Address &address)
Set a probe value by its name in the Config system.
Static Public Member Functions inherited from ns3::Probe
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::DataCollectionObject
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void TraceSink (Ptr< const Packet > packet, const Address &address)
Method to connect to an underlying ns3::TraceSource with arguments of type Ptr<const Packet> and const Address&.
Private Attributes
Address m_address
The socket address for the traced packet.
TracedCallback< Ptr< const Packet >, const Address & > m_output
Output trace, packet and source address.
TracedCallback< uint32_t, uint32_t > m_outputBytes
Output trace, previous packet size and current packet size.
Ptr< const Packet > m_packet
The traced packet.
uint32_t m_packetSizeOld
The size of the traced packet.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Probe
Time m_start
Time when logging starts.
Time m_stop
Time when logging stops.
Protected Attributes inherited from ns3::DataCollectionObject
bool m_enabled
Object's activation state.
std::string m_name
Name of the object within the data collection framework.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Probe to translate from a TraceSource to two more easily parsed TraceSources.
This class is designed to probe an underlying ns3 TraceSource exporting a packet and a socket address. This probe exports a trace source "Output" with arguments of type Ptr<const Packet> and const Address&. This probe exports another trace source "OutputBytes" with arguments of type uint32_t, which is the number of bytes in the packet. The trace sources emit values when either the probed trace source emits a new value, or when SetValue () is called.
Definition at line 51 of file application-packet-probe.h.
Constructor & Destructor Documentation
ApplicationPacketProbe()
ns3::ApplicationPacketProbe::ApplicationPacketProbe ()
Definition at line 57 of file application-packet-probe.cc.
References m_packet, and NS_LOG_FUNCTION.
~ApplicationPacketProbe()
ns3::ApplicationPacketProbe::~ApplicationPacketProbe () virtual
Definition at line 63 of file application-packet-probe.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
ConnectByObject()
bool ns3::ApplicationPacketProbe::ConnectByObject (std::string traceSource, Ptr< Object > obj) virtual
connect to a trace source attribute provided by a given object
Parameters
traceSource the name of the attribute TraceSource to connect to
obj ns3::Object to connect to
Returns
true if the trace source was successfully connected
Implements ns3::Probe.
Definition at line 91 of file application-packet-probe.cc.
References ns3::Names::FindPath(), ns3::MakeCallback(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::ObjectBase::TraceConnectWithoutContext(), and TraceSink().
ConnectByPath()
void ns3::ApplicationPacketProbe::ConnectByPath (std::string path) virtual
connect to a trace source provided by a config path
Parameters
path Config path to bind to
Note, if an invalid path is provided, the probe will not be connected to anything.
Implements ns3::Probe.
Definition at line 100 of file application-packet-probe.cc.
References ns3::Config::ConnectWithoutContext(), ns3::MakeCallback(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and TraceSink().
GetTypeId()
TypeId ns3::ApplicationPacketProbe::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 38 of file application-packet-probe.cc.
References m_output, m_outputBytes, ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
SetValue()
void ns3::ApplicationPacketProbe::SetValue (Ptr< const Packet > packet, const Address & address)
Set a probe value.
Parameters
packet set the traced packet equal to this
address set the socket address for the traced packet equal to this
Definition at line 69 of file application-packet-probe.cc.
References first::address, m_address, m_output, m_outputBytes, m_packet, m_packetSizeOld, and NS_LOG_FUNCTION.
SetValueByPath()
void ns3::ApplicationPacketProbe::SetValueByPath (std::string path, Ptr< const Packet > packet, const Address & address) static
Set a probe value by its name in the Config system.
Parameters
path config path to access the probe
packet set the traced packet equal to this
address set the socket address for the traced packet equal to this
Definition at line 82 of file application-packet-probe.cc.
References first::address, NS_ASSERT_MSG(), and NS_LOG_FUNCTION.
TraceSink()
void ns3::ApplicationPacketProbe::TraceSink (Ptr< const Packet > packet, const Address & address) private
Method to connect to an underlying ns3::TraceSource with arguments of type Ptr<const Packet> and const Address&.
Parameters
packet the traced packet
address the socket address for the traced packet
Definition at line 108 of file application-packet-probe.cc.
References first::address, ns3::Probe::IsEnabled(), m_address, m_output, m_outputBytes, m_packet, m_packetSizeOld, and NS_LOG_FUNCTION.
Referenced by ConnectByObject(), and ConnectByPath().
Member Data Documentation
m_address
Address ns3::ApplicationPacketProbe::m_address private
The socket address for the traced packet.
Definition at line 118 of file application-packet-probe.h.
Referenced by SetValue(), and TraceSink().
m_output
TracedCallback<Ptr<const Packet>, const Address&> ns3::ApplicationPacketProbe::m_output private
Output trace, packet and source address.
Definition at line 110 of file application-packet-probe.h.
Referenced by GetTypeId(), SetValue(), and TraceSink().
m_outputBytes
TracedCallback<uint32_t, uint32_t> ns3::ApplicationPacketProbe::m_outputBytes private
Output trace, previous packet size and current packet size.
Definition at line 112 of file application-packet-probe.h.
Referenced by GetTypeId(), SetValue(), and TraceSink().
m_packet
Ptr<const Packet> ns3::ApplicationPacketProbe::m_packet private
The traced packet.
Definition at line 115 of file application-packet-probe.h.
Referenced by ApplicationPacketProbe(), SetValue(), and TraceSink().
m_packetSizeOld
uint32_t ns3::ApplicationPacketProbe::m_packetSizeOld private
The size of the traced packet.
Definition at line 121 of file application-packet-probe.h.
Referenced by SetValue(), and TraceSink().
The documentation for this class was generated from the following files:
src/applications/model/application-packet-probe.h
src/applications/model/application-packet-probe.cc