ns-3: visualizer.ipython_view.ConsoleView Class Reference
visualizer.ipython_view.ConsoleView Class Reference
ConsoleView class.
Public Member Functions
def __init__ (self)
def changeLine (self, text)
Replace currently entered command line with given text.
def getCurrentLine (self)
Get text in current command line.
def onKeyPress (self, widget, event)
Key press callback used for correcting behavior for console-like interfaces.
def onKeyPressExtend (self, event)
For some reason we can't extend onKeyPress directly (bug #500900).
def showPrompt (self, prompt)
Prints prompt at start of line.
def showReturned (self, text)
Show returned text from last command and print new prompt.
def write (self, text, editable=False)
Write given text to buffer.
Public Attributes
color_pat
line_start
mark
text_buffer
Static Public Attributes
dictionary ANSI_COLORS
Private Member Functions
def _changeLine (self, text)
Replace currently entered command line with given text.
def _showPrompt (self, prompt)
Prints prompt at start of line.
def _showReturned (self, text)
Show returned text from last command and print new prompt.
def _write (self, text, editable=False)
Write given text to buffer.
Detailed Description
ConsoleView class.
Definition at line 332 of file ipython_view.py.
Constructor & Destructor Documentation
__init__()
def visualizer.ipython_view.ConsoleView.__init__ (self)
Initialize console view.
Reimplemented in visualizer.ipython_view.IPythonView.
Definition at line 367 of file ipython_view.py.
Member Function Documentation
_changeLine()
def visualizer.ipython_view.ConsoleView._changeLine (self, text) private
Replace currently entered command line with given text.
Parameters
text Text to use as replacement.
Returns
none
Definition at line 458 of file ipython_view.py.
References visualizer.ipython_view.ConsoleView._write(), delete, visualizer.ipython_view.ConsoleView.line_start, and visualizer.ipython_view.ConsoleView.text_buffer.
Referenced by visualizer.ipython_view.ConsoleView.changeLine().
_showPrompt()
def visualizer.ipython_view.ConsoleView._showPrompt (self, prompt) private
Prints prompt at start of line.
Parameters
prompt Prompt to print.
Returns
none
Definition at line 438 of file ipython_view.py.
References visualizer.ipython_view.ConsoleView._write(), visualizer.ipython_view.ConsoleView.line_start, and visualizer.ipython_view.ConsoleView.text_buffer.
Referenced by visualizer.ipython_view.ConsoleView._showReturned(), and visualizer.ipython_view.ConsoleView.showPrompt().
_showReturned()
def visualizer.ipython_view.ConsoleView._showReturned (self, text) private
Show returned text from last command and print new prompt.
Parameters
text Text to show.
Returns
none
Definition at line 490 of file ipython_view.py.
References visualizer.ipython_view.ConsoleView._showPrompt(), visualizer.ipython_view.ConsoleView._write(), visualizer.ipython_view.IterableIPShell.IP, visualizer.ipython_view.ConsoleView.line_start, visualizer.ipython_view.IterableIPShell.prompt, visualizer.ipython_view.IPythonView.prompt, and visualizer.ipython_view.ConsoleView.text_buffer.
Referenced by visualizer.ipython_view.ConsoleView.showReturned().
_write()
def visualizer.ipython_view.ConsoleView._write (self, text, editable = False) private
Write given text to buffer.
Parameters
text Text to append.
editable If true, added text is editable.
Returns
none
Definition at line 400 of file ipython_view.py.
References visualizer.ipython_view.ConsoleView.color_pat, visualizer.ipython_view.ConsoleView.mark, and visualizer.ipython_view.ConsoleView.text_buffer.
Referenced by visualizer.ipython_view.ConsoleView._changeLine(), visualizer.ipython_view.ConsoleView._showPrompt(), visualizer.ipython_view.ConsoleView._showReturned(), and visualizer.ipython_view.ConsoleView.write().
changeLine()
def visualizer.ipython_view.ConsoleView.changeLine (self, text)
Replace currently entered command line with given text.
Parameters
text Text to use as replacement.
Returns
none
Definition at line 449 of file ipython_view.py.
References visualizer.ipython_view.ConsoleView._changeLine().
Referenced by visualizer.ipython_view.IPythonView.onKeyPressExtend().
getCurrentLine()
def visualizer.ipython_view.ConsoleView.getCurrentLine (self)
Get text in current command line.
Returns
Text of current command line.
Definition at line 470 of file ipython_view.py.
References visualizer.ipython_view.ConsoleView.line_start, and visualizer.ipython_view.ConsoleView.text_buffer.
Referenced by visualizer.ipython_view.IPythonView.onKeyPressExtend(), and visualizer.ipython_view.IPythonView.raw_input().
onKeyPress()
def visualizer.ipython_view.ConsoleView.onKeyPress (self, widget, event)
Key press callback used for correcting behavior for console-like interfaces.
For example 'home' should go to prompt, not to beginning of line.
Parameters
widget Widget that key press accored in.
event Event object
Returns
Return True if event should not trickle.
Definition at line 514 of file ipython_view.py.
References visualizer.ipython_view.ConsoleView.line_start, visualizer.ipython_view.ConsoleView.onKeyPressExtend(), and visualizer.ipython_view.ConsoleView.text_buffer.
onKeyPressExtend()
def visualizer.ipython_view.ConsoleView.onKeyPressExtend (self, event)
For some reason we can't extend onKeyPress directly (bug #500900).
Parameters
event key press
Returns
none
Reimplemented in visualizer.ipython_view.IPythonView.
Definition at line 557 of file ipython_view.py.
Referenced by visualizer.ipython_view.ConsoleView.onKeyPress().
showPrompt()
def visualizer.ipython_view.ConsoleView.showPrompt (self, prompt)
Prints prompt at start of line.
Parameters
prompt Prompt to print.
Returns
none
Definition at line 429 of file ipython_view.py.
References visualizer.ipython_view.ConsoleView._showPrompt().
Referenced by visualizer.ipython_view.IPythonView.onKeyPressExtend().
showReturned()
def visualizer.ipython_view.ConsoleView.showReturned (self, text)
Show returned text from last command and print new prompt.
Parameters
text Text to show.
Returns
none
Definition at line 481 of file ipython_view.py.
References visualizer.ipython_view.ConsoleView._showReturned().
write()
def visualizer.ipython_view.ConsoleView.write (self, text, editable = False)
Write given text to buffer.
Parameters
text Text to append.
editable If true, added text is editable.
Returns
none
Definition at line 390 of file ipython_view.py.
References visualizer.ipython_view.ConsoleView._write().
Referenced by visualizer.ipython_view.IPythonView.onKeyPressExtend().
Member Data Documentation
ANSI_COLORS
visualizer.ipython_view.ConsoleView.ANSI_COLORS static
Initial value:
=   {'0;30': 'Black',     '0;31': 'Red',
                  '0;32': 'Green',     '0;33': 'Brown',
                  '0;34': 'Blue',      '0;35': 'Purple',
                  '0;36': 'Cyan',      '0;37': 'LightGray',
                  '1;30': 'DarkGray',  '1;31': 'DarkRed',
                  '1;32': 'SeaGreen',  '1;33': 'Yellow',
                  '1;34': 'LightBlue', '1;35': 'MediumPurple',
                  '1;36': 'LightCyan', '1;37': 'White'}
color list
Definition at line 358 of file ipython_view.py.
color_pat
visualizer.ipython_view.ConsoleView.color_pat
color pattern
Definition at line 384 of file ipython_view.py.
Referenced by visualizer.ipython_view.ConsoleView._write().
line_start
visualizer.ipython_view.ConsoleView.line_start
line start
Definition at line 385 of file ipython_view.py.
Referenced by visualizer.ipython_view.ConsoleView._changeLine(), visualizer.ipython_view.ConsoleView._showPrompt(), visualizer.ipython_view.ConsoleView._showReturned(), visualizer.ipython_view.ConsoleView.getCurrentLine(), and visualizer.ipython_view.ConsoleView.onKeyPress().
mark
visualizer.ipython_view.ConsoleView.mark
scroll mark
Definition at line 375 of file ipython_view.py.
Referenced by visualizer.ipython_view.ConsoleView._write().
text_buffer
visualizer.ipython_view.ConsoleView.text_buffer
text buffer
Definition at line 374 of file ipython_view.py.
Referenced by visualizer.ipython_view.ConsoleView._changeLine(), visualizer.ipython_view.ConsoleView._showPrompt(), visualizer.ipython_view.ConsoleView._showReturned(), visualizer.ipython_view.ConsoleView._write(), visualizer.ipython_view.ConsoleView.getCurrentLine(), and visualizer.ipython_view.ConsoleView.onKeyPress().
The documentation for this class was generated from the following file:
src/visualizer/visualizer/ipython_view.py