ns-3: ns3::DsrMainHelper Class Reference
ns3::DsrMainHelper Class Reference
DSR Routing
Helper class that adds DSR routing to nodes.
#include "dsr-main-helper.h"
Public Member Functions
DsrMainHelper ()
Create an DsrMainHelper that makes life easier for people who want to install DSR routing to nodes.
DsrMainHelper (const DsrMainHelper &)
Construct an DsrMainHelper from another previously initialized instance (Copy Constructor).
~DsrMainHelper ()
void Install (DsrHelper &dsrHelper, NodeContainer nodes)
Install routing to the nodes.
void SetDsrHelper (DsrHelper &dsrHelper)
Set the helper class.
Private Member Functions
void Install (Ptr< Node > node)
Install routing to a node.
DsrMainHelper & operator= (const DsrMainHelper &o)
Assignment operator declared private and not implemented to disallow assignment and prevent the compiler from happily inserting its own.
Private Attributes
const DsrHelper * m_dsrHelper
helper class
Detailed Description
Helper class that adds DSR routing to nodes.
Definition at line 48 of file dsr-main-helper.h.
Constructor & Destructor Documentation
DsrMainHelper() [1/2]
ns3::DsrMainHelper::DsrMainHelper ()
Create an DsrMainHelper that makes life easier for people who want to install DSR routing to nodes.
Definition at line 47 of file dsr-main-helper.cc.
References NS_LOG_FUNCTION.
~DsrMainHelper()
ns3::DsrMainHelper::~DsrMainHelper ()
Definition at line 59 of file dsr-main-helper.cc.
References m_dsrHelper, and NS_LOG_FUNCTION.
DsrMainHelper() [2/2]
ns3::DsrMainHelper::DsrMainHelper (const DsrMainHelper & o)
Construct an DsrMainHelper from another previously initialized instance (Copy Constructor).
Definition at line 53 of file dsr-main-helper.cc.
References ns3::DsrHelper::Copy(), m_dsrHelper, and NS_LOG_FUNCTION.
Member Function Documentation
Install() [1/2]
void ns3::DsrMainHelper::Install (DsrHelper & dsrHelper, NodeContainer nodes)
Install routing to the nodes.
Parameters
dsrHelper The DSR helper class
nodes the collection of nodes
Definition at line 77 of file dsr-main-helper.cc.
References ns3::DsrHelper::Copy(), m_dsrHelper, first::nodes, and NS_LOG_DEBUG.
Referenced by RoutingExperiment::Run(), and RoutingHelper::SetupRoutingProtocol().
Install() [2/2]
void ns3::DsrMainHelper::Install (Ptr< Node > node) private
Install routing to a node.
Parameters
node the node to install DSR routing
Definition at line 89 of file dsr-main-helper.cc.
References ns3::DsrHelper::Create(), m_dsrHelper, NS_LOG_FUNCTION, and ns3::dsr::DsrRouting::SetNode().
operator=()
DsrMainHelper & ns3::DsrMainHelper::operator= (const DsrMainHelper & o) private
Assignment operator declared private and not implemented to disallow assignment and prevent the compiler from happily inserting its own.
Parameters
o source object to assign
Returns
DsrHelper object
Definition at line 66 of file dsr-main-helper.cc.
References ns3::DsrHelper::Copy(), and m_dsrHelper.
SetDsrHelper()
void ns3::DsrMainHelper::SetDsrHelper (DsrHelper & dsrHelper)
Set the helper class.
Parameters
dsrHelper the DSR helper class
Definition at line 103 of file dsr-main-helper.cc.
References ns3::DsrHelper::Copy(), m_dsrHelper, and NS_LOG_FUNCTION.
Member Data Documentation
m_dsrHelper
const DsrHelper* ns3::DsrMainHelper::m_dsrHelper private
helper class
Definition at line 87 of file dsr-main-helper.h.
Referenced by DsrMainHelper(), ~DsrMainHelper(), Install(), operator=(), and SetDsrHelper().
The documentation for this class was generated from the following files:
src/dsr/helper/dsr-main-helper.h
src/dsr/helper/dsr-main-helper.cc