ns-3: ThreeGppUmiPropagationLossModelTestCase Class Reference
ThreeGppUmiPropagationLossModelTestCase Class Reference
Test case for the class ThreeGppUmiStreetCanyonPropagationLossModel.
Classes
struct TestVector
Struct containing the parameters for each test.
Public Member Functions
ThreeGppUmiPropagationLossModelTestCase ()
Constructor.
virtual ~ThreeGppUmiPropagationLossModelTestCase ()
Destructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Build the simulation scenario and run the tests.
Private Attributes
TestVectors< TestVector > m_testVectors
array containing all the test vectors
double m_tolerance
tolerance
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test case for the class ThreeGppUmiStreetCanyonPropagationLossModel.
It computes the pathloss between two nodes and compares it with the value obtained using the formula in 3GPP TR 38.901, Table 7.4.1-1.
Definition at line 356 of file three-gpp-propagation-loss-model-test-suite.cc.
Constructor & Destructor Documentation
ThreeGppUmiPropagationLossModelTestCase()
ThreeGppUmiPropagationLossModelTestCase::ThreeGppUmiPropagationLossModelTestCase ()
Constructor.
Definition at line 391 of file three-gpp-propagation-loss-model-test-suite.cc.
~ThreeGppUmiPropagationLossModelTestCase()
ThreeGppUmiPropagationLossModelTestCase::~ThreeGppUmiPropagationLossModelTestCase () virtual
Destructor.
Definition at line 398 of file three-gpp-propagation-loss-model-test-suite.cc.
Member Function Documentation
DoRun()
void ThreeGppUmiPropagationLossModelTestCase::DoRun (void) private virtual
Build the simulation scenario and run the tests.
Implements ns3::TestCase.
Definition at line 403 of file three-gpp-propagation-loss-model-test-suite.cc.
References ns3::PropagationLossModel::CalcRxPower(), ThreeGppUmiPropagationLossModelTestCase::TestVector::m_distance, ThreeGppUmiPropagationLossModelTestCase::TestVector::m_frequency, ThreeGppUmiPropagationLossModelTestCase::TestVector::m_isLos, ThreeGppUmiPropagationLossModelTestCase::TestVector::m_pr, ThreeGppUmiPropagationLossModelTestCase::TestVector::m_pt, m_testVectors, m_tolerance, first::nodes, NS_TEST_EXPECT_MSG_EQ_TOL, ns3::ObjectBase::SetAttribute(), ns3::ThreeGppPropagationLossModel::SetChannelConditionModel(), and ns3::MobilityModel::SetPosition().
Member Data Documentation
m_testVectors
TestVectors<TestVector> ThreeGppUmiPropagationLossModelTestCase::m_testVectors private
array containing all the test vectors
Definition at line 387 of file three-gpp-propagation-loss-model-test-suite.cc.
Referenced by DoRun().
m_tolerance
double ThreeGppUmiPropagationLossModelTestCase::m_tolerance private
tolerance
Definition at line 388 of file three-gpp-propagation-loss-model-test-suite.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/propagation/test/three-gpp-propagation-loss-model-test-suite.cc