ns-3: RrcConnectionRejectTestCase Class Reference
RrcConnectionRejectTestCase Class Reference
LTE Models » lte module tests | Test suites
Rrc Connection Reject Test Case.
Public Member Functions
RrcConnectionRejectTestCase ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from RrcHeaderTestCase
RrcHeaderTestCase (std::string s)
Constructor.
void AssertEqualRadioResourceConfigDedicated (LteRrcSap::RadioResourceConfigDedicated rrcd1, LteRrcSap::RadioResourceConfigDedicated rrcd2)
Assert equal radio resource config dedicated.
LteRrcSap::RadioResourceConfigDedicated CreateRadioResourceConfigDedicated ()
Create radio resource config dedicated.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Protected Attributes inherited from RrcHeaderTestCase
Ptr< Packet > packet
the packet
Detailed Description
Rrc Connection Reject Test Case.
Definition at line 957 of file test-asn1-encoding.cc.
Constructor & Destructor Documentation
RrcConnectionRejectTestCase()
RrcConnectionRejectTestCase::RrcConnectionRejectTestCase ()
Definition at line 964 of file test-asn1-encoding.cc.
Member Function Documentation
DoRun()
void RrcConnectionRejectTestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements RrcHeaderTestCase.
Definition at line 969 of file test-asn1-encoding.cc.
References ns3::Packet::AddHeader(), ns3::RrcConnectionRejectHeader::GetMessage(), TestUtils::LogPacketContents(), NS_LOG_DEBUG, NS_TEST_ASSERT_MSG_EQ, RrcHeaderTestCase::packet, ns3::Packet::RemoveHeader(), ns3::RrcConnectionRejectHeader::SetMessage(), and ns3::LteRrcSap::RrcConnectionReject::waitTime.
The documentation for this class was generated from the following file:
src/lte/test/test-asn1-encoding.cc