ns-3: ns3::DataOutputInterface Class Reference
ns3::DataOutputInterface Class Reference abstract
Statistics » Data Output
Abstract Data Output Interface class s.
#include "data-output-interface.h"
Public Member Functions
DataOutputInterface ()
virtual ~DataOutputInterface ()
std::string GetFilePrefix () const
Gets the file prefix of the DataOutputInterface.
virtual void Output (DataCollector &dc)=0
Outputs information from the provided DataCollector.
void SetFilePrefix (const std::string prefix)
Sets the DataOutputInterface prefix to the provided prefix.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose ()
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes
std::string m_filePrefix
File prefix for the DataOutputInterface.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Abstract Data Output Interface class s.
Definition at line 39 of file data-output-interface.h.
Constructor & Destructor Documentation
DataOutputInterface()
DataOutputInterface::DataOutputInterface ()
Definition at line 31 of file data-output-interface.cc.
References NS_LOG_FUNCTION.
~DataOutputInterface()
DataOutputInterface::~DataOutputInterface () virtual
Definition at line 35 of file data-output-interface.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void DataOutputInterface::DoDispose () protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Reimplemented in ns3::OmnetDataOutput.
Definition at line 52 of file data-output-interface.cc.
References ns3::Object::DoDispose(), and NS_LOG_FUNCTION.
Referenced by ns3::OmnetDataOutput::DoDispose().
GetFilePrefix()
std::string DataOutputInterface::GetFilePrefix () const
Gets the file prefix of the DataOutputInterface.
Returns
File prefix as a string
Definition at line 69 of file data-output-interface.cc.
References m_filePrefix, and NS_LOG_FUNCTION.
GetTypeId()
TypeId DataOutputInterface::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 41 of file data-output-interface.cc.
References ns3::TypeId::SetParent().
Output()
virtual void ns3::DataOutputInterface::Output (DataCollector & dc) pure virtual
Outputs information from the provided DataCollector.
Parameters
dc DataCollector object
Implemented in ns3::SqliteDataOutput, and ns3::OmnetDataOutput.
SetFilePrefix()
void DataOutputInterface::SetFilePrefix (const std::string prefix)
Sets the DataOutputInterface prefix to the provided prefix.
Parameters
prefix prefix as a string
Definition at line 61 of file data-output-interface.cc.
References m_filePrefix, and NS_LOG_FUNCTION.
Member Data Documentation
m_filePrefix
std::string ns3::DataOutputInterface::m_filePrefix protected
File prefix for the DataOutputInterface.
Definition at line 70 of file data-output-interface.h.
Referenced by ns3::OmnetDataOutput::OmnetDataOutput(), ns3::SqliteDataOutput::SqliteDataOutput(), GetFilePrefix(), ns3::OmnetDataOutput::Output(), ns3::SqliteDataOutput::Output(), and SetFilePrefix().
The documentation for this class was generated from the following files:
src/stats/model/data-output-interface.h
src/stats/model/data-output-interface.cc