ns-3: ns3::LteTestMac Class Reference
ns3::LteTestMac Class Reference
LTE Models » lte module tests | Test suites
This class implements a testing loopback MAC layer.
#include "lte-test-entities.h"
Public Types
enum RlcHeaderType_t { UM_RLC_HEADER = 0, AM_RLC_HEADER = 1 }
RCL Header Type enumeration.
enum TxOpportunityMode_t { MANUAL_MODE = 0, AUTOMATIC_MODE = 1, RANDOM_MODE = 2 }
Transmit opportunity mode enumeration.
Public Member Functions
LteTestMac (void)
virtual ~LteTestMac (void)
virtual void DoDispose (void)
Destructor implementation.
std::string GetDataReceived (void)
Get data received function.
LteMacSapProvider * GetLteMacSapProvider (void)
Get the MAC SAP provider.
uint32_t GetRxBytes (void)
Get the receive bytes.
uint32_t GetRxPdus (void)
Get the receive PDUs.
uint32_t GetTxBytes (void)
Get the transmit bytes.
uint32_t GetTxPdus (void)
Get the transmit PDUs.
bool Receive (Ptr< NetDevice > nd, Ptr< const Packet > p, uint16_t protocol, const Address &addr)
the Receive function
void SendTxOpportunity (Time time, uint32_t bytes)
Send transmit opportunity function.
void SetDevice (Ptr< NetDevice > device)
Set the device function.
void SetLteMacLoopback (Ptr< LteTestMac > s)
Set the other side of the MAC Loopback.
void SetLteMacSapUser (LteMacSapUser *s)
Set the MAC SAP user.
void SetPdcpHeaderPresent (bool present)
Set PDCP header present function.
void SetRlcHeaderType (uint8_t rlcHeaderType)
Set RLC header type.
void SetTxOpportunityMode (uint8_t mode)
Set transmit opportunity mode.
void SetTxOppSize (uint32_t txOppSize)
Set transmit opportunity time.
void SetTxOppTime (Time txOppTime)
Set transmit opportunity time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void DoReportBufferStatus (LteMacSapProvider::ReportBufferStatusParameters params)
Report buffer status function.
void DoTransmitPdu (LteMacSapProvider::TransmitPduParameters params)
Transmit PDU.
Private Attributes
Ptr< NetDevice > m_device
the device
Ptr< LteTestMac > m_macLoopback
MAC loopback.
LteMacSapProvider * m_macSapProvider
MAC SAP provider.
LteMacSapUser * m_macSapUser
MAC SAP user.
EventId m_nextTxOpp
next transmit opportunity event
std::list< EventId > m_nextTxOppList
next transmit opportunity list
bool m_pdcpHeaderPresent
PDCP header present?
std::string m_receivedData
the received data string
uint8_t m_rlcHeaderType
RLC header type.
uint32_t m_rxBytes
the number of receive bytes
uint32_t m_rxPdus
the number of receive PDUs
uint32_t m_txBytes
the number of transmit bytes
uint8_t m_txOpportunityMode
transmit opportunity mode
uint32_t m_txOppSize
transmit opportunity size
Time m_txOppTime
transmit opportunity time
uint32_t m_txPdus
the number of transmit PDUs
Friends
class EnbMacMemberLteMacSapProvider< LteTestMac >
allow EnbMacMemberLteMacSapProvider<LteTestMac> class friend access
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class implements a testing loopback MAC layer.
Definition at line 240 of file lte-test-entities.h.
Member Enumeration Documentation
RlcHeaderType_t
enum ns3::LteTestMac::RlcHeaderType_t
RCL Header Type enumeration.
Enumerator
UM_RLC_HEADER
AM_RLC_HEADER
Definition at line 318 of file lte-test-entities.h.
TxOpportunityMode_t
enum ns3::LteTestMac::TxOpportunityMode_t
Transmit opportunity mode enumeration.
Enumerator
MANUAL_MODE
AUTOMATIC_MODE
RANDOM_MODE
Definition at line 330 of file lte-test-entities.h.
Constructor & Destructor Documentation
LteTestMac()
ns3::LteTestMac::LteTestMac (void)
Definition at line 370 of file lte-test-entities.cc.
References EnbMacMemberLteMacSapProvider< LteTestMac >, m_device, m_macLoopback, m_macSapProvider, m_macSapUser, m_pdcpHeaderPresent, m_rlcHeaderType, m_rxBytes, m_rxPdus, m_txBytes, m_txOpportunityMode, m_txOppSize, m_txOppTime, m_txPdus, MANUAL_MODE, NS_LOG_FUNCTION, ns3::Seconds(), and UM_RLC_HEADER.
~LteTestMac()
ns3::LteTestMac::~LteTestMac (void) virtual
Definition at line 394 of file lte-test-entities.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::LteTestMac::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 400 of file lte-test-entities.cc.
References m_device, m_macSapProvider, and NS_LOG_FUNCTION.
DoReportBufferStatus()
void ns3::LteTestMac::DoReportBufferStatus (LteMacSapProvider::ReportBufferStatusParameters params) private
Report buffer status function.
Parameters
params LteMacSapProvider::ReportBufferStatusParameters
Definition at line 621 of file lte-test-entities.cc.
References AUTOMATIC_MODE, ns3::LteMacSapUser::TxOpportunityParameters::bytes, ns3::LteMacSapUser::TxOpportunityParameters::componentCarrierId, ns3::LteMacSapUser::TxOpportunityParameters::harqId, ns3::LteMacSapUser::TxOpportunityParameters::layer, ns3::LteMacSapUser::TxOpportunityParameters::lcid, m_macSapUser, m_nextTxOppList, m_txOpportunityMode, m_txOppSize, m_txOppTime, ns3::LteMacSapUser::NotifyTxOpportunity(), NS_LOG_FUNCTION, aloha::params, ns3::LteMacSapUser::TxOpportunityParameters::rnti, and ns3::Simulator::Schedule().
DoTransmitPdu()
void ns3::LteTestMac::DoTransmitPdu (LteMacSapProvider::TransmitPduParameters params) private
Transmit PDU.
MAC SAP.
Parameters
params LteMacSapProvider::TransmitPduParameters
Definition at line 562 of file lte-test-entities.cc.
References AM_RLC_HEADER, ns3::LteMacSapUser::ReceivePduParameters::lcid, m_device, m_macLoopback, m_macSapUser, m_pdcpHeaderPresent, m_receivedData, m_rlcHeaderType, m_txBytes, m_txPdus, NS_LOG_FUNCTION, NS_LOG_LOGIC(), ns3::LteMacSapUser::ReceivePduParameters::p, aloha::params, ns3::LteMacSapUser::ReceivePdu(), ns3::LteMacSapUser::ReceivePduParameters::rnti, ns3::Simulator::Schedule(), and ns3::Seconds().
GetDataReceived()
std::string ns3::LteTestMac::GetDataReceived (void)
Get data received function.
Returns
the received data string
Definition at line 437 of file lte-test-entities.cc.
References m_receivedData, and NS_LOG_FUNCTION.
Referenced by LteRlcAmTransmitterTestCase::DoCheckDataReceived(), and LteRlcUmTransmitterTestCase::DoCheckDataReceived().
GetLteMacSapProvider()
LteMacSapProvider * ns3::LteTestMac::GetLteMacSapProvider (void)
Get the MAC SAP provider.
Returns
a pointer to the SAP provider of the MAC
Definition at line 425 of file lte-test-entities.cc.
References m_macSapProvider.
Referenced by LteRlcAmTransmitterTestCase::DoRun(), LteRlcUmTransmitterTestCase::DoRun(), ns3::LteSimpleHelper::InstallSingleEnbDevice(), and ns3::LteSimpleHelper::InstallSingleUeDevice().
GetRxBytes()
uint32_t ns3::LteTestMac::GetRxBytes (void)
Get the receive bytes.
Returns
the number of bytes received
Definition at line 466 of file lte-test-entities.cc.
References m_rxBytes, and NS_LOG_FUNCTION.
GetRxPdus()
uint32_t ns3::LteTestMac::GetRxPdus (void)
Get the receive PDUs.
Returns
the number of receive PDUS
Definition at line 459 of file lte-test-entities.cc.
References m_rxPdus, and NS_LOG_FUNCTION.
Referenced by LteRlcAmE2eTestCase::DoRun().
GetTxBytes()
uint32_t ns3::LteTestMac::GetTxBytes (void)
Get the transmit bytes.
Returns
the number of bytes transmitted
Definition at line 452 of file lte-test-entities.cc.
References m_txBytes, and NS_LOG_FUNCTION.
GetTxPdus()
uint32_t ns3::LteTestMac::GetTxPdus (void)
Get the transmit PDUs.
Returns
the number of transmit PDUS
Definition at line 445 of file lte-test-entities.cc.
References m_txPdus, and NS_LOG_FUNCTION.
Referenced by LteRlcAmE2eTestCase::DoRun().
GetTypeId()
TypeId ns3::LteTestMac::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 360 of file lte-test-entities.cc.
References ns3::TypeId::SetParent().
Receive()
bool ns3::LteTestMac::Receive (Ptr< NetDevice > nd, Ptr< const Packet > p, uint16_t protocol, const Address & addr)
the Receive function
Parameters
nd the device
p the packet
protocol the protocol
addr the address
Returns
true if successful
Definition at line 659 of file lte-test-entities.cc.
References ns3::LteMacSapUser::ReceivePduParameters::lcid, m_macSapUser, m_rxBytes, m_rxPdus, NS_LOG_FUNCTION, ns3::LteMacSapUser::ReceivePduParameters::p, ns3::LteMacSapUser::ReceivePdu(), and ns3::LteMacSapUser::ReceivePduParameters::rnti.
Referenced by ns3::LteSimpleHelper::InstallSingleEnbDevice(), and ns3::LteSimpleHelper::InstallSingleUeDevice().
SendTxOpportunity()
void ns3::LteTestMac::SendTxOpportunity (Time time, uint32_t bytes)
Send transmit opportunity function.
Parameters
time the time
bytes the number of bytes
Definition at line 474 of file lte-test-entities.cc.
References ns3::LteMacSapUser::TxOpportunityParameters::bytes, ns3::LteMacSapUser::TxOpportunityParameters::componentCarrierId, ns3::Node::GetId(), ns3::LteMacSapUser::TxOpportunityParameters::harqId, ns3::LteMacSapUser::TxOpportunityParameters::layer, ns3::LteMacSapUser::TxOpportunityParameters::lcid, m_device, m_macSapUser, m_txOpportunityMode, m_txOppSize, m_txOppTime, ns3::LteMacSapUser::NotifyTxOpportunity(), NS_LOG_FUNCTION, RANDOM_MODE, ns3::LteMacSapUser::TxOpportunityParameters::rnti, ns3::Simulator::Schedule(), ns3::Simulator::ScheduleWithContext(), and ns3::Seconds().
Referenced by LteRlcAmTransmitterOneSduTestCase::DoRun(), LteRlcAmTransmitterSegmentationTestCase::DoRun(), LteRlcAmTransmitterConcatenationTestCase::DoRun(), LteRlcAmTransmitterReportBufferStatusTestCase::DoRun(), LteRlcUmTransmitterOneSduTestCase::DoRun(), LteRlcUmTransmitterSegmentationTestCase::DoRun(), LteRlcUmTransmitterConcatenationTestCase::DoRun(), LteRlcUmTransmitterReportBufferStatusTestCase::DoRun(), and SetTxOpportunityMode().
SetDevice()
void ns3::LteTestMac::SetDevice (Ptr< NetDevice > device)
Set the device function.
Parameters
device the device
Definition at line 413 of file lte-test-entities.cc.
References m_device.
Referenced by ns3::LteSimpleHelper::InstallSingleEnbDevice(), and ns3::LteSimpleHelper::InstallSingleUeDevice().
SetLteMacLoopback()
void ns3::LteTestMac::SetLteMacLoopback (Ptr< LteTestMac > s)
Set the other side of the MAC Loopback.
Parameters
s a pointer to the other side of the MAC loopback
Definition at line 431 of file lte-test-entities.cc.
References m_macLoopback.
SetLteMacSapUser()
void ns3::LteTestMac::SetLteMacSapUser (LteMacSapUser * s)
Set the MAC SAP user.
Parameters
s a pointer to the MAC SAP user
Definition at line 419 of file lte-test-entities.cc.
References m_macSapUser.
Referenced by LteRlcAmTransmitterTestCase::DoRun(), LteRlcUmTransmitterTestCase::DoRun(), ns3::LteSimpleHelper::InstallSingleEnbDevice(), and ns3::LteSimpleHelper::InstallSingleUeDevice().
SetPdcpHeaderPresent()
void ns3::LteTestMac::SetPdcpHeaderPresent (bool present)
Set PDCP header present function.
Parameters
present true iif PDCP header present
Definition at line 514 of file lte-test-entities.cc.
References m_pdcpHeaderPresent, and NS_LOG_FUNCTION.
SetRlcHeaderType()
void ns3::LteTestMac::SetRlcHeaderType (uint8_t rlcHeaderType)
Set RLC header type.
Parameters
rlcHeaderType the RLC header type
Definition at line 521 of file lte-test-entities.cc.
References m_rlcHeaderType, and NS_LOG_FUNCTION.
Referenced by LteRlcAmTransmitterTestCase::DoRun(), and LteRlcUmTransmitterTestCase::DoRun().
SetTxOpportunityMode()
void ns3::LteTestMac::SetTxOpportunityMode (uint8_t mode)
Set transmit opportunity mode.
Parameters
mode the transmit opportunity mode
Definition at line 528 of file lte-test-entities.cc.
References m_txOpportunityMode, m_txOppSize, m_txOppTime, NS_LOG_FUNCTION, RANDOM_MODE, ns3::Seconds(), and SendTxOpportunity().
Referenced by LteRlcAmE2eTestCase::DoRun(), and LteRlcUmE2eTestCase::DoRun().
SetTxOppSize()
void ns3::LteTestMac::SetTxOppSize (uint32_t txOppSize)
Set transmit opportunity time.
Parameters
txOppSize the transmit opportunity size
Definition at line 550 of file lte-test-entities.cc.
References m_txOppSize, and NS_LOG_FUNCTION.
Referenced by LteRlcAmE2eTestCase::DoRun(), and LteRlcUmE2eTestCase::DoRun().
SetTxOppTime()
void ns3::LteTestMac::SetTxOppTime (Time txOppTime)
Set transmit opportunity time.
Parameters
txOppTime the transmit opportunity time
Definition at line 543 of file lte-test-entities.cc.
References m_txOppTime, and NS_LOG_FUNCTION.
Referenced by LteRlcAmE2eTestCase::DoRun(), and LteRlcUmE2eTestCase::DoRun().
Friends And Related Function Documentation
EnbMacMemberLteMacSapProvider< LteTestMac >
friend class EnbMacMemberLteMacSapProvider< LteTestMac > friend
allow EnbMacMemberLteMacSapProvider<LteTestMac> class friend access
Definition at line 229 of file lte-test-entities.h.
Referenced by LteTestMac().
Member Data Documentation
m_device
Ptr<NetDevice> ns3::LteTestMac::m_device private
the device
Definition at line 392 of file lte-test-entities.h.
Referenced by LteTestMac(), DoDispose(), DoTransmitPdu(), SendTxOpportunity(), and SetDevice().
m_macLoopback
Ptr<LteTestMac> ns3::LteTestMac::m_macLoopback private
MAC loopback.
Definition at line 384 of file lte-test-entities.h.
Referenced by LteTestMac(), DoTransmitPdu(), and SetLteMacLoopback().
m_macSapProvider
LteMacSapProvider* ns3::LteTestMac::m_macSapProvider private
MAC SAP provider.
Definition at line 382 of file lte-test-entities.h.
Referenced by LteTestMac(), DoDispose(), and GetLteMacSapProvider().
m_macSapUser
LteMacSapUser* ns3::LteTestMac::m_macSapUser private
MAC SAP user.
Definition at line 383 of file lte-test-entities.h.
Referenced by LteTestMac(), DoReportBufferStatus(), DoTransmitPdu(), Receive(), SendTxOpportunity(), and SetLteMacSapUser().
m_nextTxOpp
EventId ns3::LteTestMac::m_nextTxOpp private
next transmit opportunity event
Definition at line 395 of file lte-test-entities.h.
m_nextTxOppList
std::list<EventId> ns3::LteTestMac::m_nextTxOppList private
next transmit opportunity list
Definition at line 398 of file lte-test-entities.h.
Referenced by DoReportBufferStatus().
m_pdcpHeaderPresent
bool ns3::LteTestMac::m_pdcpHeaderPresent private
PDCP header present?
Definition at line 389 of file lte-test-entities.h.
Referenced by LteTestMac(), DoTransmitPdu(), and SetPdcpHeaderPresent().
m_receivedData
std::string ns3::LteTestMac::m_receivedData private
the received data string
Definition at line 386 of file lte-test-entities.h.
Referenced by DoTransmitPdu(), and GetDataReceived().
m_rlcHeaderType
uint8_t ns3::LteTestMac::m_rlcHeaderType private
RLC header type.
Definition at line 388 of file lte-test-entities.h.
Referenced by LteTestMac(), DoTransmitPdu(), and SetRlcHeaderType().
m_rxBytes
uint32_t ns3::LteTestMac::m_rxBytes private
the number of receive bytes
Definition at line 404 of file lte-test-entities.h.
Referenced by LteTestMac(), GetRxBytes(), and Receive().
m_rxPdus
uint32_t ns3::LteTestMac::m_rxPdus private
the number of receive PDUs
Definition at line 403 of file lte-test-entities.h.
Referenced by LteTestMac(), GetRxPdus(), and Receive().
m_txBytes
uint32_t ns3::LteTestMac::m_txBytes private
the number of transmit bytes
Definition at line 402 of file lte-test-entities.h.
Referenced by LteTestMac(), DoTransmitPdu(), and GetTxBytes().
m_txOpportunityMode
uint8_t ns3::LteTestMac::m_txOpportunityMode private
transmit opportunity mode
Definition at line 390 of file lte-test-entities.h.
Referenced by LteTestMac(), DoReportBufferStatus(), SendTxOpportunity(), and SetTxOpportunityMode().
m_txOppSize
uint32_t ns3::LteTestMac::m_txOppSize private
transmit opportunity size
Definition at line 397 of file lte-test-entities.h.
Referenced by LteTestMac(), DoReportBufferStatus(), SendTxOpportunity(), SetTxOpportunityMode(), and SetTxOppSize().
m_txOppTime
Time ns3::LteTestMac::m_txOppTime private
transmit opportunity time
Definition at line 396 of file lte-test-entities.h.
Referenced by LteTestMac(), DoReportBufferStatus(), SendTxOpportunity(), SetTxOpportunityMode(), and SetTxOppTime().
m_txPdus
uint32_t ns3::LteTestMac::m_txPdus private
the number of transmit PDUs
Definition at line 401 of file lte-test-entities.h.
Referenced by LteTestMac(), DoTransmitPdu(), and GetTxPdus().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-entities.h
src/lte/test/lte-test-entities.cc