ns-3: ns3::CoordinationListener Class Reference
ns3::CoordinationListener Class Reference
WAVE module
CoordinationListener class.
Public Member Functions
CoordinationListener (DefaultChannelScheduler *scheduler)
Constructor.
virtual ~CoordinationListener ()
virtual void NotifyCchSlotStart (Time duration)
virtual void NotifyGuardSlotStart (Time duration, bool cchi)
virtual void NotifySchSlotStart (Time duration)
Public Member Functions inherited from ns3::ChannelCoordinationListener
virtual ~ChannelCoordinationListener (void)
Public Member Functions inherited from ns3::SimpleRefCount< ChannelCoordinationListener >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
DefaultChannelScheduler * m_scheduler
the scheduler
Detailed Description
CoordinationListener class.
Definition at line 33 of file default-channel-scheduler.cc.
Constructor & Destructor Documentation
CoordinationListener()
ns3::CoordinationListener::CoordinationListener (DefaultChannelScheduler * scheduler) inline
Constructor.
Parameters
scheduler channel scheduler
Definition at line 41 of file default-channel-scheduler.cc.
~CoordinationListener()
virtual ns3::CoordinationListener::~CoordinationListener () inline virtual
Definition at line 45 of file default-channel-scheduler.cc.
Member Function Documentation
NotifyCchSlotStart()
virtual void ns3::CoordinationListener::NotifyCchSlotStart (Time duration) inline virtual
Parameters
duration the CCH access time (CCHI - GI) continues,
Implements ns3::ChannelCoordinationListener.
Definition at line 48 of file default-channel-scheduler.cc.
References aloha::duration, m_scheduler, and ns3::DefaultChannelScheduler::NotifyCchSlotStart().
NotifyGuardSlotStart()
virtual void ns3::CoordinationListener::NotifyGuardSlotStart (Time duration, bool cchi) inline virtual
Parameters
duration the time Guard access time (GI) continues
cchi indicate whether the guard slot is in the GI of CCHI or SCHI.
Implements ns3::ChannelCoordinationListener.
Definition at line 56 of file default-channel-scheduler.cc.
References aloha::duration, m_scheduler, and ns3::DefaultChannelScheduler::NotifyGuardSlotStart().
NotifySchSlotStart()
virtual void ns3::CoordinationListener::NotifySchSlotStart (Time duration) inline virtual
Parameters
duration the SCH access time (SCHI - GI) continues,
Implements ns3::ChannelCoordinationListener.
Definition at line 52 of file default-channel-scheduler.cc.
References aloha::duration, m_scheduler, and ns3::DefaultChannelScheduler::NotifySchSlotStart().
Member Data Documentation
m_scheduler
DefaultChannelScheduler* ns3::CoordinationListener::m_scheduler private
the scheduler
Definition at line 61 of file default-channel-scheduler.cc.
Referenced by NotifyCchSlotStart(), NotifyGuardSlotStart(), and NotifySchSlotStart().
The documentation for this class was generated from the following file:
src/wave/model/default-channel-scheduler.cc