ns-3: BatteryLifetimeTest Class Reference
BatteryLifetimeTest Class Reference
This example was originally devised as a test, then it was converted to an example.
Public Member Functions
BatteryLifetimeTest ()
virtual ~BatteryLifetimeTest ()
bool ConstantLoadTest (double load, Time expLifetime)
void CreateLoadProfiles (void)
Creates load profiles according to D.
bool VariableLoadTest (std::vector< double > loads, std::vector< Time > timeStamps, Time expLifetime)
Public Attributes
double m_alpha
double m_beta
std::vector< LoadProfile > m_loadProfiles
Detailed Description
This example was originally devised as a test, then it was converted to an example.
The script tests the remaining energy for RvBatteryModel and WifiRadioEnergyModel updates. It does so by mimicking the procedure and results published in D. Rakhmatov, S. Vrudhula, D.A. Wallach, "Battery lifetime prediction for energy-aware computing," Proceedings of the 2002 International Symposium on Low Power Electronics and Design, 2002. ISLPED '02. doi: 10.1109/LPE.2002.146729
Definition at line 52 of file rv-battery-model-test.cc.
Constructor & Destructor Documentation
BatteryLifetimeTest()
BatteryLifetimeTest::BatteryLifetimeTest ()
Definition at line 102 of file rv-battery-model-test.cc.
~BatteryLifetimeTest()
BatteryLifetimeTest::~BatteryLifetimeTest () virtual
Definition at line 109 of file rv-battery-model-test.cc.
Member Function Documentation
ConstantLoadTest()
bool BatteryLifetimeTest::ConstantLoadTest (double load, Time expLifetime)
Parameters
load Load value, in Amperes (A).
expLifetime Expected lifetime.
Returns
False if no error occurs.
Runs simulation with constant load and checks the battery lifetime with known results.
Definition at line 715 of file rv-battery-model-test.cc.
References ns3::NodeContainer::Create(), ns3::YansWifiChannelHelper::Create(), ns3::YansWifiPhyHelper::Default(), ns3::Simulator::Destroy(), first::devices, ns3::WifiPhyHelper::DLT_IEEE802_11_RADIO, ns3::EnergySourceContainer::Get(), ns3::RvBatteryModel::GetLifetime(), ns3::Time::GetSeconds(), ns3::DeviceEnergyModelHelper::Install(), ns3::EnergySourceHelper::Install(), NS_LOG_DEBUG, ns3::Simulator::Run(), ns3::Seconds(), ns3::RvBatteryModelHelper::Set(), ns3::WifiPhyHelper::Set(), ns3::WifiRadioEnergyModelHelper::Set(), ns3::YansWifiPhyHelper::SetChannel(), ns3::Config::SetDefault(), ns3::WifiPhyHelper::SetPcapDataLinkType(), ns3::YansWifiChannelHelper::SetPropagationDelay(), ns3::WifiMacHelper::SetType(), ns3::Simulator::Stop(), third::wifi, and ns3::WIFI_PHY_STANDARD_80211b.
CreateLoadProfiles()
void BatteryLifetimeTest::CreateLoadProfiles (void)
Creates load profiles according to D.
Rakhmatov, S. Vrudhula, D.A. Wallach, "Battery lifetime prediction for energy-aware computing," Proceedings of the 2002 International Symposium on Low Power Electronics and Design, 2002. ISLPED '02. doi: 10.1109/LPE.2002.146729
Definition at line 114 of file rv-battery-model-test.cc.
References LoadProfile::dualFoilLifeTime, LoadProfile::itsyLifetime, LoadProfile::loads, ns3::Seconds(), and LoadProfile::timeStamps.
VariableLoadTest()
bool BatteryLifetimeTest::VariableLoadTest (std::vector< double > loads, std::vector< Time > timeStamps, Time expLifetime)
Parameters
loads Load profile.
timeStamps Time stamps.
expLifetime Expected lifetime.
Returns
False if no error occurs.
Runs simulation with variable load and checks the battery lifetime with known results.
Definition at line 798 of file rv-battery-model-test.cc.
References ns3::NodeContainer::Create(), ns3::YansWifiChannelHelper::Create(), ns3::YansWifiPhyHelper::Default(), ns3::Simulator::Destroy(), first::devices, ns3::WifiPhyHelper::DLT_IEEE802_11_RADIO, ns3::EnergySourceContainer::Get(), ns3::DeviceEnergyModelContainer::Get(), ns3::RvBatteryModel::GetLifetime(), ns3::Time::GetSeconds(), ns3::DeviceEnergyModelHelper::Install(), ns3::EnergySourceHelper::Install(), NS_ASSERT, NS_LOG_DEBUG, ns3::Simulator::Run(), ns3::Simulator::Schedule(), ns3::Seconds(), ns3::RvBatteryModelHelper::Set(), ns3::WifiPhyHelper::Set(), ns3::WifiRadioEnergyModelHelper::Set(), ns3::YansWifiPhyHelper::SetChannel(), ns3::Config::SetDefault(), ns3::WifiRadioEnergyModel::SetIdleCurrentA(), ns3::WifiPhyHelper::SetPcapDataLinkType(), ns3::YansWifiChannelHelper::SetPropagationDelay(), ns3::WifiMacHelper::SetType(), ns3::Simulator::Stop(), third::wifi, and ns3::WIFI_PHY_STANDARD_80211b.
Member Data Documentation
m_alpha
double BatteryLifetimeTest::m_alpha
Definition at line 98 of file rv-battery-model-test.cc.
m_beta
double BatteryLifetimeTest::m_beta
Definition at line 99 of file rv-battery-model-test.cc.
m_loadProfiles
std::vector<LoadProfile> BatteryLifetimeTest::m_loadProfiles
Definition at line 97 of file rv-battery-model-test.cc.
The documentation for this class was generated from the following file:
src/energy/examples/rv-battery-model-test.cc