ns-3: ns3::DataCalculator Class Reference
ns3::DataCalculator Class Reference abstract
Statistics
Calculates data during a simulation.
#include "data-calculator.h"
Public Member Functions
DataCalculator ()
virtual ~DataCalculator ()
void Disable ()
Disables DataCalculator when simulation stops.
void Enable ()
Enables DataCalculator when simulation starts.
std::string GetContext () const
Gets the DataCalculator context.
bool GetEnabled () const
Returns whether the DataCalculator is enabled.
std::string GetKey () const
Gets the DataCalculator key.
virtual void Output (DataOutputCallback &callback) const =0
Outputs data based on the provided callback.
void SetContext (const std::string context)
Sets the DataCalculator context to the provided context.
void SetKey (const std::string key)
Sets the DataCalculator key to the provided key.
virtual void Start (const Time &startTime)
Starts DataCalculator at a given time in the simulation.
virtual void Stop (const Time &stopTime)
Stops DataCalculator at a given time in the simulation.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes
std::string m_context
Context value.
bool m_enabled
Descendant classes must check & respect m_enabled!
std::string m_key
Key value.
Private Attributes
EventId m_startEvent
Start event.
EventId m_stopEvent
Stop event.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Calculates data during a simulation.
Definition at line 111 of file data-calculator.h.
Constructor & Destructor Documentation
DataCalculator()
DataCalculator::DataCalculator ()
Definition at line 35 of file data-calculator.cc.
References NS_LOG_FUNCTION.
~DataCalculator()
DataCalculator::~DataCalculator () virtual
Definition at line 41 of file data-calculator.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Disable()
void DataCalculator::Disable ()
Disables DataCalculator when simulation stops.
Definition at line 118 of file data-calculator.cc.
References m_enabled, and NS_LOG_FUNCTION.
Referenced by Stop().
DoDispose()
void DataCalculator::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Reimplemented in ns3::TimeMinMaxAvgTotalCalculator, ns3::CounterCalculator< T >, ns3::CounterCalculator< uint32_t >, ns3::CounterCalculator<>, ns3::MinMaxAvgTotalCalculator< T >, ns3::MinMaxAvgTotalCalculator< uint32_t >, ns3::MinMaxAvgTotalCalculator< double >, ns3::MinMaxAvgTotalCalculator< uint64_t >, ns3::PacketSizeMinMaxAvgTotalCalculator, and ns3::PacketCounterCalculator.
Definition at line 59 of file data-calculator.cc.
References ns3::Simulator::Cancel(), ns3::Object::DoDispose(), m_startEvent, m_stopEvent, and NS_LOG_FUNCTION.
Referenced by ns3::MinMaxAvgTotalCalculator< T >::DoDispose(), ns3::CounterCalculator< T >::DoDispose(), and ns3::TimeMinMaxAvgTotalCalculator::DoDispose().
Enable()
void DataCalculator::Enable ()
Enables DataCalculator when simulation starts.
Definition at line 109 of file data-calculator.cc.
References m_enabled, and NS_LOG_FUNCTION.
Referenced by Start().
GetContext()
std::string DataCalculator::GetContext () const
Gets the DataCalculator context.
Returns
Context value as a string
Definition at line 100 of file data-calculator.cc.
References m_context, and NS_LOG_FUNCTION.
GetEnabled()
bool DataCalculator::GetEnabled () const
Returns whether the DataCalculator is enabled.
Returns
true if DataCalculator is enabled
Definition at line 127 of file data-calculator.cc.
References m_enabled, and NS_LOG_FUNCTION.
GetKey()
std::string DataCalculator::GetKey () const
Gets the DataCalculator key.
Returns
Key value as a string
Definition at line 81 of file data-calculator.cc.
References m_key, and NS_LOG_FUNCTION.
GetTypeId()
TypeId DataCalculator::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 48 of file data-calculator.cc.
References ns3::TypeId::SetParent().
Output()
virtual void ns3::DataCalculator::Output (DataOutputCallback & callback) const pure virtual
Outputs data based on the provided callback.
Parameters
callback
Implemented in ns3::TimeMinMaxAvgTotalCalculator, ns3::CounterCalculator< T >, ns3::CounterCalculator< uint32_t >, ns3::CounterCalculator<>, ns3::MinMaxAvgTotalCalculator< T >, ns3::MinMaxAvgTotalCalculator< uint32_t >, ns3::MinMaxAvgTotalCalculator< double >, and ns3::MinMaxAvgTotalCalculator< uint64_t >.
SetContext()
void DataCalculator::SetContext (const std::string context)
Sets the DataCalculator context to the provided context.
Parameters
context Context value as a string
Definition at line 91 of file data-calculator.cc.
References m_context, and NS_LOG_FUNCTION.
SetKey()
void DataCalculator::SetKey (const std::string key)
Sets the DataCalculator key to the provided key.
Parameters
key Key value as a string
Definition at line 72 of file data-calculator.cc.
References m_key, and NS_LOG_FUNCTION.
Start()
void DataCalculator::Start (const Time & startTime) virtual
Starts DataCalculator at a given time in the simulation.
Parameters
startTime
Definition at line 137 of file data-calculator.cc.
References Enable(), m_startEvent, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), and startTime.
Stop()
void DataCalculator::Stop (const Time & stopTime) virtual
Stops DataCalculator at a given time in the simulation.
Parameters
stopTime
Definition at line 148 of file data-calculator.cc.
References Disable(), m_stopEvent, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), and stopTime.
Member Data Documentation
m_context
std::string ns3::DataCalculator::m_context protected
Context value.
Definition at line 178 of file data-calculator.h.
Referenced by GetContext(), ns3::TimeMinMaxAvgTotalCalculator::Output(), and SetContext().
m_enabled
bool ns3::DataCalculator::m_enabled protected
Descendant classes must check & respect m_enabled!
Definition at line 175 of file data-calculator.h.
Referenced by Disable(), Enable(), GetEnabled(), and ns3::TimeMinMaxAvgTotalCalculator::Update().
m_key
std::string ns3::DataCalculator::m_key protected
Key value.
Definition at line 177 of file data-calculator.h.
Referenced by GetKey(), ns3::TimeMinMaxAvgTotalCalculator::Output(), and SetKey().
m_startEvent
EventId ns3::DataCalculator::m_startEvent private
Start event.
Definition at line 183 of file data-calculator.h.
Referenced by DoDispose(), and Start().
m_stopEvent
EventId ns3::DataCalculator::m_stopEvent private
Stop event.
Definition at line 184 of file data-calculator.h.
Referenced by DoDispose(), and Stop().
The documentation for this class was generated from the following files:
src/stats/model/data-calculator.h
src/stats/model/data-calculator.cc