ns-3: ns3::aodv::DeferredRouteOutputTag Class Reference
ns3::aodv::DeferredRouteOutputTag Class Reference
AODV Routing
Tag used by AODV implementation.
Public Member Functions
DeferredRouteOutputTag (int32_t o=-1)
Constructor.
void Deserialize (TagBuffer i)
TypeId GetInstanceTypeId () const
Get the most derived TypeId for this Object.
int32_t GetInterface () const
Get the output interface.
uint32_t GetSerializedSize () const
void Print (std::ostream &os) const
void Serialize (TagBuffer i) const
void SetInterface (int32_t oif)
Set the output interface.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
int32_t m_oif
Positive if output device is fixed in RouteOutput.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Tag used by AODV implementation.
Definition at line 61 of file aodv-routing-protocol.cc.
Constructor & Destructor Documentation
DeferredRouteOutputTag()
ns3::aodv::DeferredRouteOutputTag::DeferredRouteOutputTag (int32_t o = -1) inline
Constructor.
Parameters
o the output interface
Definition at line 69 of file aodv-routing-protocol.cc.
Member Function Documentation
Deserialize()
void ns3::aodv::DeferredRouteOutputTag::Deserialize (TagBuffer i) inline virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 121 of file aodv-routing-protocol.cc.
References m_oif, and ns3::TagBuffer::ReadU32().
GetInstanceTypeId()
TypeId ns3::aodv::DeferredRouteOutputTag::GetInstanceTypeId () const inline virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 88 of file aodv-routing-protocol.cc.
References GetTypeId().
GetInterface()
int32_t ns3::aodv::DeferredRouteOutputTag::GetInterface () const inline
Get the output interface.
Returns
the output interface
Definition at line 97 of file aodv-routing-protocol.cc.
References m_oif.
Referenced by ns3::aodv::RoutingProtocol::SendPacketFromQueue().
GetSerializedSize()
uint32_t ns3::aodv::DeferredRouteOutputTag::GetSerializedSize () const inline virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 111 of file aodv-routing-protocol.cc.
GetTypeId()
static TypeId ns3::aodv::DeferredRouteOutputTag::GetTypeId () inline static
Get the type ID.
Returns
the object TypeId
Definition at line 78 of file aodv-routing-protocol.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::aodv::DeferredRouteOutputTag::Print (std::ostream & os) const inline virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 126 of file aodv-routing-protocol.cc.
References m_oif.
Serialize()
void ns3::aodv::DeferredRouteOutputTag::Serialize (TagBuffer i) const inline virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 116 of file aodv-routing-protocol.cc.
References m_oif, and ns3::TagBuffer::WriteU32().
SetInterface()
void ns3::aodv::DeferredRouteOutputTag::SetInterface (int32_t oif) inline
Set the output interface.
Parameters
oif the output interface
Definition at line 106 of file aodv-routing-protocol.cc.
References m_oif.
Member Data Documentation
m_oif
int32_t ns3::aodv::DeferredRouteOutputTag::m_oif private
Positive if output device is fixed in RouteOutput.
Definition at line 133 of file aodv-routing-protocol.cc.
Referenced by Deserialize(), GetInterface(), Print(), Serialize(), and SetInterface().
The documentation for this class was generated from the following file:
src/aodv/model/aodv-routing-protocol.cc