ns-3: ns3::Ipv4PacketInfoTag Class Reference
ns3::Ipv4PacketInfoTag Class Reference
Internet » IPv4 classes and sub-modules
This class implements Linux struct pktinfo in order to deliver ancillary information to the socket interface. This is used with socket option such as IP_PKTINFO, IP_RECVTTL, IP_RECVTOS. See linux manpage ip(7).
#include "ipv4-packet-info-tag.h"
Public Member Functions
Ipv4PacketInfoTag ()
virtual void Deserialize (TagBuffer i)
Ipv4Address GetAddress (void) const
Get the tag's address.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
Ipv4Address GetLocalAddress (void) const
Get the tag's local address.
uint32_t GetRecvIf (void) const
Get the tag's receiving interface.
virtual uint32_t GetSerializedSize (void) const
uint8_t GetTtl (void) const
Get the tag's Time to Live Implemented, but not used in the stack yet.
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer i) const
void SetAddress (Ipv4Address addr)
Set the tag's address.
void SetLocalAddress (Ipv4Address addr)
Set the tag's local address.
void SetRecvIf (uint32_t ifindex)
Set the tag's receiving interface.
void SetTtl (uint8_t ttl)
Set the tag's Time to Live Implemented, but not used in the stack yet.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Ipv4Address m_addr
Header destination address.
uint32_t m_ifindex
interface index
Ipv4Address m_spec_dst
Local address.
uint8_t m_ttl
Time to Live.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class implements Linux struct pktinfo in order to deliver ancillary information to the socket interface. This is used with socket option such as IP_PKTINFO, IP_RECVTTL, IP_RECVTOS. See linux manpage ip(7).
This tag in the send direction is presently not enabled but we would accept a patch along those lines in the future.
Definition at line 44 of file ipv4-packet-info-tag.h.
Constructor & Destructor Documentation
Ipv4PacketInfoTag()
ns3::Ipv4PacketInfoTag::Ipv4PacketInfoTag ()
Definition at line 31 of file ipv4-packet-info-tag.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Deserialize()
void ns3::Ipv4PacketInfoTag::Deserialize (TagBuffer i) virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 136 of file ipv4-packet-info-tag.cc.
References ns3::Ipv4Address::Deserialize(), m_addr, m_ifindex, m_spec_dst, m_ttl, NS_LOG_FUNCTION, ns3::TagBuffer::Read(), ns3::TagBuffer::ReadU32(), and ns3::TagBuffer::ReadU8().
GetAddress()
Ipv4Address ns3::Ipv4PacketInfoTag::GetAddress (void) const
Get the tag's address.
Returns
the address
Definition at line 48 of file ipv4-packet-info-tag.cc.
References m_addr, and NS_LOG_FUNCTION.
GetInstanceTypeId()
TypeId ns3::Ipv4PacketInfoTag::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 109 of file ipv4-packet-info-tag.cc.
References GetTypeId(), and NS_LOG_FUNCTION.
GetLocalAddress()
Ipv4Address ns3::Ipv4PacketInfoTag::GetLocalAddress (void) const
Get the tag's local address.
This corresponds to "ipi_spec_dst" in struct in_pktinfo. Implemented, but not used in the stack yet
Returns
the address
Definition at line 62 of file ipv4-packet-info-tag.cc.
References m_spec_dst, and NS_LOG_FUNCTION.
GetRecvIf()
uint32_t ns3::Ipv4PacketInfoTag::GetRecvIf (void) const
Get the tag's receiving interface.
Returns
the interface index
Definition at line 76 of file ipv4-packet-info-tag.cc.
References m_ifindex, and NS_LOG_FUNCTION.
Referenced by Ipv4DynamicGlobalRoutingTestCase::HandleRead(), ns3::DhcpServer::NetHandler(), ns3::Rip::Receive(), and ns3::olsr::RoutingProtocol::RecvOlsr().
GetSerializedSize()
uint32_t ns3::Ipv4PacketInfoTag::GetSerializedSize (void) const virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 116 of file ipv4-packet-info-tag.cc.
References NS_LOG_FUNCTION.
GetTtl()
uint8_t ns3::Ipv4PacketInfoTag::GetTtl (void) const
Get the tag's Time to Live Implemented, but not used in the stack yet.
Returns
the TTL
Definition at line 90 of file ipv4-packet-info-tag.cc.
References m_ttl, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::Ipv4PacketInfoTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 99 of file ipv4-packet-info-tag.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::Ipv4PacketInfoTag::Print (std::ostream & os) const virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 148 of file ipv4-packet-info-tag.cc.
References m_addr, m_ifindex, m_spec_dst, m_ttl, and NS_LOG_FUNCTION.
Serialize()
void ns3::Ipv4PacketInfoTag::Serialize (TagBuffer i) const virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 124 of file ipv4-packet-info-tag.cc.
References m_addr, m_ifindex, m_spec_dst, m_ttl, NS_LOG_FUNCTION, ns3::Ipv4Address::Serialize(), ns3::TagBuffer::Write(), ns3::TagBuffer::WriteU32(), and ns3::TagBuffer::WriteU8().
SetAddress()
void ns3::Ipv4PacketInfoTag::SetAddress (Ipv4Address addr)
Set the tag's address.
Parameters
addr the address
Definition at line 41 of file ipv4-packet-info-tag.cc.
References m_addr, and NS_LOG_FUNCTION.
SetLocalAddress()
void ns3::Ipv4PacketInfoTag::SetLocalAddress (Ipv4Address addr)
Set the tag's local address.
This corresponds to "ipi_spec_dst" in struct in_pktinfo. Implemented, but not used in the stack yet
Parameters
addr the address
Definition at line 55 of file ipv4-packet-info-tag.cc.
References m_spec_dst, and NS_LOG_FUNCTION.
SetRecvIf()
void ns3::Ipv4PacketInfoTag::SetRecvIf (uint32_t ifindex)
Set the tag's receiving interface.
Parameters
ifindex the interface index
Definition at line 69 of file ipv4-packet-info-tag.cc.
References m_ifindex, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv4RawSocketImpl::ForwardUp(), and ns3::UdpSocketImpl::ForwardUp().
SetTtl()
void ns3::Ipv4PacketInfoTag::SetTtl (uint8_t ttl)
Set the tag's Time to Live Implemented, but not used in the stack yet.
Parameters
ttl the TTL
Definition at line 83 of file ipv4-packet-info-tag.cc.
References m_ttl, and NS_LOG_FUNCTION.
Member Data Documentation
m_addr
Ipv4Address ns3::Ipv4PacketInfoTag::m_addr private
Header destination address.
Definition at line 126 of file ipv4-packet-info-tag.h.
Referenced by Deserialize(), GetAddress(), Print(), Serialize(), and SetAddress().
m_ifindex
uint32_t ns3::Ipv4PacketInfoTag::m_ifindex private
interface index
Definition at line 128 of file ipv4-packet-info-tag.h.
Referenced by Deserialize(), GetRecvIf(), Print(), Serialize(), and SetRecvIf().
m_spec_dst
Ipv4Address ns3::Ipv4PacketInfoTag::m_spec_dst private
Local address.
Definition at line 127 of file ipv4-packet-info-tag.h.
Referenced by Deserialize(), GetLocalAddress(), Print(), Serialize(), and SetLocalAddress().
m_ttl
uint8_t ns3::Ipv4PacketInfoTag::m_ttl private
Time to Live.
Definition at line 131 of file ipv4-packet-info-tag.h.
Referenced by Deserialize(), GetTtl(), Print(), Serialize(), and SetTtl().
The documentation for this class was generated from the following files:
src/internet/model/ipv4-packet-info-tag.h
src/internet/model/ipv4-packet-info-tag.cc