ns-3: ns3::Ipv6ExtensionRoutingDemux Class Reference
ns3::Ipv6ExtensionRoutingDemux Class Reference
Internet » IPv6 classes and sub-modules » IPV6 Header extension system.
IPv6 Extension Routing Demux.
#include "ipv6-extension.h"
Public Member Functions
Ipv6ExtensionRoutingDemux ()
Constructor.
virtual ~Ipv6ExtensionRoutingDemux ()
Destructor.
Ptr< Ipv6ExtensionRouting > GetExtensionRouting (uint8_t typeRouting)
Get the routing extension corresponding to typeRouting.
void Insert (Ptr< Ipv6ExtensionRouting > extensionRouting)
Insert a new IPv6 Routing Extension.
void Remove (Ptr< Ipv6ExtensionRouting > extensionRouting)
Remove a routing extension from this demux.
void SetNode (Ptr< Node > node)
Set the node.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
The interface ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose ()
Dispose this object.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
typedef std::list< Ptr< Ipv6ExtensionRouting > > Ipv6ExtensionRoutingList_t
Container for the extension routing.
Private Attributes
Ipv6ExtensionRoutingList_t m_extensionsRouting
List of IPv6 Routing Extensions supported.
Ptr< Node > m_node
The node.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
IPv6 Extension Routing Demux.
Definition at line 530 of file ipv6-extension.h.
Member Typedef Documentation
Ipv6ExtensionRoutingList_t
typedef std::list<Ptr<Ipv6ExtensionRouting> > ns3::Ipv6ExtensionRoutingDemux::Ipv6ExtensionRoutingList_t private
Container for the extension routing.
Definition at line 584 of file ipv6-extension.h.
Constructor & Destructor Documentation
Ipv6ExtensionRoutingDemux()
ns3::Ipv6ExtensionRoutingDemux::Ipv6ExtensionRoutingDemux ()
Constructor.
Definition at line 890 of file ipv6-extension.cc.
~Ipv6ExtensionRoutingDemux()
ns3::Ipv6ExtensionRoutingDemux::~Ipv6ExtensionRoutingDemux () virtual
Destructor.
Definition at line 894 of file ipv6-extension.cc.
Member Function Documentation
DoDispose()
void ns3::Ipv6ExtensionRoutingDemux::DoDispose () protected virtual
Dispose this object.
Reimplemented from ns3::Object.
Definition at line 898 of file ipv6-extension.cc.
References ns3::Object::DoDispose(), and ns3::Ipv6Extension::m_node.
GetExtensionRouting()
Ptr< Ipv6ExtensionRouting > ns3::Ipv6ExtensionRoutingDemux::GetExtensionRouting (uint8_t typeRouting)
Get the routing extension corresponding to typeRouting.
Parameters
typeRouting the number of the routing extension to retrieve
Returns
a matching IPv6 routing extension
Definition at line 920 of file ipv6-extension.cc.
GetTypeId()
TypeId ns3::Ipv6ExtensionRoutingDemux::GetTypeId () static
The interface ID.
Returns
type ID
Definition at line 877 of file ipv6-extension.cc.
References m_extensionsRouting, ns3::MakeObjectVectorAccessor(), and ns3::TypeId::SetParent().
Insert()
void ns3::Ipv6ExtensionRoutingDemux::Insert (Ptr< Ipv6ExtensionRouting > extensionRouting)
Insert a new IPv6 Routing Extension.
Parameters
extensionRouting the routing extension to insert
Definition at line 915 of file ipv6-extension.cc.
Remove()
void ns3::Ipv6ExtensionRoutingDemux::Remove (Ptr< Ipv6ExtensionRouting > extensionRouting)
Remove a routing extension from this demux.
Parameters
extensionRouting pointer on the extension to remove
Definition at line 932 of file ipv6-extension.cc.
SetNode()
void ns3::Ipv6ExtensionRoutingDemux::SetNode (Ptr< Node > node)
Set the node.
Parameters
node the node to set
Definition at line 910 of file ipv6-extension.cc.
References ns3::Ipv6Extension::m_node.
Member Data Documentation
m_extensionsRouting
Ipv6ExtensionRoutingList_t ns3::Ipv6ExtensionRoutingDemux::m_extensionsRouting private
List of IPv6 Routing Extensions supported.
Definition at line 589 of file ipv6-extension.h.
Referenced by GetTypeId().
m_node
Ptr<Node> ns3::Ipv6ExtensionRoutingDemux::m_node private
The node.
Definition at line 594 of file ipv6-extension.h.
The documentation for this class was generated from the following files:
src/internet/model/ipv6-extension.h
src/internet/model/ipv6-extension.cc