ns-3: BriteTopologyStructureTestCase Class Reference
BriteTopologyStructureTestCase Class Reference
Public Member Functions
BriteTopologyStructureTestCase ()
virtual ~BriteTopologyStructureTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 34 of file brite-test-topology.cc.
Constructor & Destructor Documentation
BriteTopologyStructureTestCase()
BriteTopologyStructureTestCase::BriteTopologyStructureTestCase ()
Definition at line 45 of file brite-test-topology.cc.
~BriteTopologyStructureTestCase()
BriteTopologyStructureTestCase::~BriteTopologyStructureTestCase () virtual
Definition at line 50 of file brite-test-topology.cc.
Member Function Documentation
DoRun()
void BriteTopologyStructureTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 54 of file brite-test-topology.cc.
References ns3::BriteTopologyHelper::AssignStreams(), ns3::BriteTopologyHelper::BuildBriteTopology(), ns3::BriteTopologyHelper::GetNAs(), ns3::BriteTopologyHelper::GetNEdgesTopology(), ns3::BriteTopologyHelper::GetNLeafNodesForAs(), ns3::BriteTopologyHelper::GetNNodesTopology(), NS_TEST_ASSERT_MSG_EQ, and first::stack.
The documentation for this class was generated from the following file:
src/brite/test/brite-test-topology.cc