ns-3: ns3::UplinkSchedulerRtps Class Reference
ns3::UplinkSchedulerRtps Class Reference
WiMAX Models
This class implements a simple uplink scheduler for rtPS flows.
#include "bs-uplink-scheduler-rtps.h"
Public Member Functions
UplinkSchedulerRtps ()
UplinkSchedulerRtps (Ptr< BaseStationNetDevice > bs)
Constructor.
~UplinkSchedulerRtps (void)
void AddUplinkAllocation (OfdmUlMapIe &ulMapIe, const uint32_t &allocationSize, uint32_t &symbolsToAllocation, uint32_t &availableSymbols)
Add Uplink Allocation function.
void AllocateInitialRangingInterval (uint32_t &symbolsToAllocation, uint32_t &availableSymbols)
Allocate Initial Ranging Interval function.
uint32_t CalculateAllocationStartTime (void)
Calculate allocation start time function.
void GetChannelDescriptorsToUpdate (bool &updateDcd, bool &updateUcd, bool &sendDcd, bool &sendUcd)
Determines if channel descriptors sent in the current frame are required to be updated.
std::list< OfdmUlMapIe > GetUplinkAllocations (void) const
Get uplink allocations.
void InitOnce (void)
Init once function.
void OnSetRequestedBandwidth (ServiceFlowRecord *sfr)
Set requested bandwidth function.
void ProcessBandwidthRequest (const BandwidthRequestHeader &bwRequestHdr)
Process bandwidth requet function.
void Schedule (void)
Schedule function.
void ServiceBandwidthRequests (const SSRecord *ssRecord, enum ServiceFlow::SchedulingType schedulingType, OfdmUlMapIe &ulMapIe, const WimaxPhy::ModulationType modulationType, uint32_t &symbolsToAllocation, uint32_t &availableSymbols)
Service Bandwidth Requests function.
bool ServiceBandwidthRequests (ServiceFlow *serviceFlow, enum ServiceFlow::SchedulingType schedulingType, OfdmUlMapIe &ulMapIe, const WimaxPhy::ModulationType modulationType, uint32_t &symbolsToAllocation, uint32_t &availableSymbols)
Service bandwidth requests function.
void ServiceUnsolicitedGrants (const SSRecord *ssRecord, enum ServiceFlow::SchedulingType schedulingType, OfdmUlMapIe &ulMapIe, const WimaxPhy::ModulationType modulationType, uint32_t &symbolsToAllocation, uint32_t &availableSymbols)
Service Unsolicited Grants function.
void SetupServiceFlow (SSRecord *ssRecord, ServiceFlow *serviceFlow)
Setup service flow function.
void ULSchedulerRTPSConnection (uint32_t &symbolsToAllocation, uint32_t &availableSymbols)
Uplink Scheduler for rtPS connections.
Public Member Functions inherited from ns3::UplinkScheduler
UplinkScheduler (Ptr< BaseStationNetDevice > bs)
Constructor.
UplinkScheduler (void)
virtual ~UplinkScheduler (void)
virtual Ptr< BaseStationNetDevice > GetBs (void)
virtual Time GetDcdTimeStamp (void) const
virtual bool GetIsInvIrIntrvlAllocated (void) const
virtual bool GetIsIrIntrvlAllocated (void) const
virtual uint8_t GetNrIrOppsAllocated (void) const
virtual Time GetTimeStampIrInterval (void)
virtual Time GetUcdTimeStamp (void) const
virtual void SetBs (Ptr< BaseStationNetDevice > bs)
Set base station device.
virtual void SetDcdTimeStamp (Time dcdTimeStamp)
Set DCD timestamp.
virtual void SetIsInvIrIntrvlAllocated (bool isInvIrIntrvlAllocated)
Set if the Inv IR interval is allocated.
virtual void SetIsIrIntrvlAllocated (bool isIrIntrvlAllocated)
Set if the IR interval is allocated.
virtual void SetNrIrOppsAllocated (uint8_t nrIrOppsAllocated)
Set the number of IR opps allocated.
virtual void SetTimeStampIrInterval (Time timeStampIrInterval)
Set timestamp IR interval.
virtual void SetUcdTimeStamp (Time ucdTimeStamp)
Set UCD timestamp.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::UplinkScheduler
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
std::list< OfdmUlMapIe > m_uplinkAllocations
uplink allocations
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class implements a simple uplink scheduler for rtPS flows.
The UL-rtPS-Scheduler work in this way: At the beginning of the UL sub-frame some symbols are allocated to the rangingInterval Messages, DSA Messages, UGS grants and UGS/rtPS/nrtPS/BE poll. Then, the remaining available symbols are allocated to the all rtPS flows according to their requestedBandwidth. The bandwidth saturation control has been implemented to redistribute the resource if the sum of requestedBandwidth exceed the available bandwidth. At the end, if there are some free symbols, their are allocated to nrtPS and BE Connections.
Definition at line 53 of file bs-uplink-scheduler-rtps.h.
Constructor & Destructor Documentation
UplinkSchedulerRtps() [1/2]
ns3::UplinkSchedulerRtps::UplinkSchedulerRtps ()
Definition at line 43 of file bs-uplink-scheduler-rtps.cc.
References ns3::Simulator::Now(), ns3::Seconds(), ns3::UplinkScheduler::SetBs(), ns3::UplinkScheduler::SetDcdTimeStamp(), ns3::UplinkScheduler::SetIsInvIrIntrvlAllocated(), ns3::UplinkScheduler::SetIsIrIntrvlAllocated(), ns3::UplinkScheduler::SetNrIrOppsAllocated(), ns3::UplinkScheduler::SetTimeStampIrInterval(), and ns3::UplinkScheduler::SetUcdTimeStamp().
UplinkSchedulerRtps() [2/2]
ns3::UplinkSchedulerRtps::UplinkSchedulerRtps (Ptr< BaseStationNetDevice > bs)
Constructor.
Parameters
bs base station device
Definition at line 54 of file bs-uplink-scheduler-rtps.cc.
References ns3::Simulator::Now(), ns3::Seconds(), ns3::UplinkScheduler::SetBs(), ns3::UplinkScheduler::SetDcdTimeStamp(), ns3::UplinkScheduler::SetIsInvIrIntrvlAllocated(), ns3::UplinkScheduler::SetIsIrIntrvlAllocated(), ns3::UplinkScheduler::SetNrIrOppsAllocated(), ns3::UplinkScheduler::SetTimeStampIrInterval(), and ns3::UplinkScheduler::SetUcdTimeStamp().
~UplinkSchedulerRtps()
ns3::UplinkSchedulerRtps::~UplinkSchedulerRtps (void)
Definition at line 65 of file bs-uplink-scheduler-rtps.cc.
References m_uplinkAllocations, and ns3::UplinkScheduler::SetBs().
Member Function Documentation
AddUplinkAllocation()
void ns3::UplinkSchedulerRtps::AddUplinkAllocation (OfdmUlMapIe & ulMapIe, const uint32_t & allocationSize, uint32_t & symbolsToAllocation, uint32_t & availableSymbols) virtual
Add Uplink Allocation function.
Parameters
ulMapIe the UL map IE
allocationSize the allocation size
symbolsToAllocation the symbols to allocation
availableSymbols the available symbols
Implements ns3::UplinkScheduler.
Definition at line 151 of file bs-uplink-scheduler-rtps.cc.
References m_uplinkAllocations, ns3::OfdmUlMapIe::SetDuration(), and ns3::OfdmUlMapIe::SetStartTime().
Referenced by AllocateInitialRangingInterval(), Schedule(), ServiceBandwidthRequests(), ServiceUnsolicitedGrants(), and ULSchedulerRTPSConnection().
AllocateInitialRangingInterval()
void ns3::UplinkSchedulerRtps::AllocateInitialRangingInterval (uint32_t & symbolsToAllocation, uint32_t & availableSymbols) virtual
Allocate Initial Ranging Interval function.
Parameters
symbolsToAllocation symbols to allocation for UpLink Subframe
availableSymbols available symbols for rtPS flows
Implements ns3::UplinkScheduler.
Definition at line 608 of file bs-uplink-scheduler-rtps.cc.
References AddUplinkAllocation(), CalculateAllocationStartTime(), ns3::UplinkScheduler::GetBs(), ns3::UplinkScheduler::GetNrIrOppsAllocated(), ns3::UplinkScheduler::GetTimeStampIrInterval(), ns3::Simulator::Now(), NS_LOG_DEBUG, ns3::Seconds(), ns3::OfdmUlMapIe::SetCid(), ns3::UplinkScheduler::SetIsIrIntrvlAllocated(), ns3::UplinkScheduler::SetNrIrOppsAllocated(), ns3::OfdmUlMapIe::SetStartTime(), ns3::UplinkScheduler::SetTimeStampIrInterval(), ns3::OfdmUlMapIe::SetUiuc(), and ns3::OfdmUlBurstProfile::UIUC_INITIAL_RANGING.
Referenced by Schedule().
CalculateAllocationStartTime()
uint32_t ns3::UplinkSchedulerRtps::CalculateAllocationStartTime (void) virtual
Calculate allocation start time function.
Returns
the allocation start time value
Implements ns3::UplinkScheduler.
Definition at line 145 of file bs-uplink-scheduler-rtps.cc.
References ns3::UplinkScheduler::GetBs().
Referenced by AllocateInitialRangingInterval().
GetChannelDescriptorsToUpdate()
void ns3::UplinkSchedulerRtps::GetChannelDescriptorsToUpdate (bool & updateDcd, bool & updateUcd, bool & sendDcd, bool & sendUcd) virtual
Determines if channel descriptors sent in the current frame are required to be updated.
Parameters
updateDcd if true update DCD
updateUcd if true update UCD
sendDcd if true send DCD
sendUcd if true send UCD
Implements ns3::UplinkScheduler.
Definition at line 89 of file bs-uplink-scheduler-rtps.cc.
References ns3::UplinkScheduler::GetBs(), ns3::UplinkScheduler::GetDcdTimeStamp(), ns3::UplinkScheduler::GetUcdTimeStamp(), ns3::Simulator::Now(), ns3::UplinkScheduler::SetDcdTimeStamp(), and ns3::UplinkScheduler::SetUcdTimeStamp().
GetTypeId()
TypeId ns3::UplinkSchedulerRtps::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 72 of file bs-uplink-scheduler-rtps.cc.
References ns3::TypeId::SetParent().
GetUplinkAllocations()
std::list< OfdmUlMapIe > ns3::UplinkSchedulerRtps::GetUplinkAllocations (void) const virtual
Get uplink allocations.
Returns
std::list<OfdmUlMapIe>
Reimplemented from ns3::UplinkScheduler.
Definition at line 83 of file bs-uplink-scheduler-rtps.cc.
References m_uplinkAllocations.
InitOnce()
void ns3::UplinkSchedulerRtps::InitOnce (void) virtual
Init once function.
Implements ns3::UplinkScheduler.
Definition at line 704 of file bs-uplink-scheduler-rtps.cc.
OnSetRequestedBandwidth()
void ns3::UplinkSchedulerRtps::OnSetRequestedBandwidth (ServiceFlowRecord * sfr) virtual
Set requested bandwidth function.
Parameters
sfr the service flow record
Implements ns3::UplinkScheduler.
Definition at line 714 of file bs-uplink-scheduler-rtps.cc.
References ns3::ServiceFlowRecord::SetGrantedBandwidth().
ProcessBandwidthRequest()
void ns3::UplinkSchedulerRtps::ProcessBandwidthRequest (const BandwidthRequestHeader & bwRequestHdr) virtual
Process bandwidth requet function.
Parameters
bwRequestHdr the bandwidth request header
Implements ns3::UplinkScheduler.
Definition at line 709 of file bs-uplink-scheduler-rtps.cc.
Schedule()
void ns3::UplinkSchedulerRtps::Schedule (void) virtual
Schedule function.
Implements ns3::UplinkScheduler.
Definition at line 164 of file bs-uplink-scheduler-rtps.cc.
References AddUplinkAllocation(), AllocateInitialRangingInterval(), ns3::WimaxNetDevice::DIRECTION_UPLINK, ns3::SSRecord::GetAreServiceFlowsAllocated(), ns3::SSRecord::GetBasicCid(), ns3::UplinkScheduler::GetBs(), ns3::SSRecord::GetIsBroadcastSS(), ns3::SSRecord::GetModulationType(), ns3::SSRecord::GetPollForRanging(), ns3::SSRecord::GetRangingStatus(), ns3::Cid::InitialRanging(), m_uplinkAllocations, NS_LOG_INFO, ns3::WimaxNetDevice::RANGING_STATUS_CONTINUE, ns3::WimaxNetDevice::RANGING_STATUS_SUCCESS, ServiceBandwidthRequests(), ServiceUnsolicitedGrants(), ns3::OfdmUlMapIe::SetCid(), ns3::OfdmUlMapIe::SetDuration(), ns3::UplinkScheduler::SetIsInvIrIntrvlAllocated(), ns3::UplinkScheduler::SetIsIrIntrvlAllocated(), ns3::OfdmUlMapIe::SetStartTime(), ns3::OfdmUlMapIe::SetUiuc(), ns3::ServiceFlow::SF_TYPE_BE, ns3::ServiceFlow::SF_TYPE_NRTPS, ns3::ServiceFlow::SF_TYPE_RTPS, ns3::ServiceFlow::SF_TYPE_UGS, ns3::OfdmUlBurstProfile::UIUC_END_OF_MAP, ns3::OfdmUlBurstProfile::UIUC_INITIAL_RANGING, and ULSchedulerRTPSConnection().
ServiceBandwidthRequests() [1/2]
void ns3::UplinkSchedulerRtps::ServiceBandwidthRequests (const SSRecord * ssRecord, enum ServiceFlow::SchedulingType schedulingType, OfdmUlMapIe & ulMapIe, const WimaxPhy::ModulationType modulationType, uint32_t & symbolsToAllocation, uint32_t & availableSymbols) virtual
Service Bandwidth Requests function.
Parameters
ssRecord Subscriber station record
schedulingType the scheduling type
ulMapIe the UL map IE
modulationType the modulation type
symbolsToAllocation the symbols to allocation
availableSymbols the available symbols
Implements ns3::UplinkScheduler.
Definition at line 430 of file bs-uplink-scheduler-rtps.cc.
References ns3::SSRecord::GetServiceFlows().
Referenced by Schedule(), and ServiceUnsolicitedGrants().
ServiceBandwidthRequests() [2/2]
bool ns3::UplinkSchedulerRtps::ServiceBandwidthRequests (ServiceFlow * serviceFlow, enum ServiceFlow::SchedulingType schedulingType, OfdmUlMapIe & ulMapIe, const WimaxPhy::ModulationType modulationType, uint32_t & symbolsToAllocation, uint32_t & availableSymbols) virtual
Service bandwidth requests function.
Parameters
serviceFlow the service flow
schedulingType the scheduling type
ulMapIe the UL map IE
modulationType the modulation type
symbolsToAllocation the symbols to allocation
availableSymbols the available symbols
Returns
true if successful
Implements ns3::UplinkScheduler.
Definition at line 454 of file bs-uplink-scheduler-rtps.cc.
References AddUplinkAllocation(), ns3::UplinkScheduler::GetBs(), ns3::ServiceFlow::GetConnection(), ns3::ServiceFlowRecord::GetGrantedBandwidth(), ns3::ServiceFlow::GetRecord(), ns3::ServiceFlowRecord::GetRequestedBandwidth(), ns3::ServiceFlow::GetSchedulingTypeStr(), ns3::ServiceFlow::GetSduSize(), ns3::ServiceFlow::GetSfid(), NS_LOG_DEBUG, ns3::ServiceFlowRecord::SetBwSinceLastExpiry(), ns3::ServiceFlow::SF_TYPE_NRTPS, and ns3::ServiceFlowRecord::UpdateGrantedBandwidth().
ServiceUnsolicitedGrants()
void ns3::UplinkSchedulerRtps::ServiceUnsolicitedGrants (const SSRecord * ssRecord, enum ServiceFlow::SchedulingType schedulingType, OfdmUlMapIe & ulMapIe, const WimaxPhy::ModulationType modulationType, uint32_t & symbolsToAllocation, uint32_t & availableSymbols) virtual
Service Unsolicited Grants function.
Parameters
ssRecord Subscriber station record
schedulingType the scheduling type
ulMapIe the UL map IE
modulationType the modulation type
symbolsToAllocation the symbols to allocation
availableSymbols the available symbols
Implements ns3::UplinkScheduler.
Definition at line 350 of file bs-uplink-scheduler-rtps.cc.
References AddUplinkAllocation(), ns3::UplinkScheduler::GetBs(), ns3::ServiceFlowRecord::GetBwSinceLastExpiry(), ns3::ServiceFlow::GetConnection(), ns3::ServiceFlowRecord::GetGrantTimeStamp(), ns3::ServiceFlow::GetRecord(), ns3::ServiceFlow::GetSchedulingType(), ns3::ServiceFlow::GetSchedulingTypeStr(), ns3::SSRecord::GetServiceFlows(), ns3::ServiceFlow::GetSfid(), ns3::OfdmUlMapIe::GetUiuc(), ns3::Simulator::Now(), NS_LOG_DEBUG, ns3::Seconds(), ServiceBandwidthRequests(), ns3::ServiceFlowRecord::SetBwSinceLastExpiry(), ns3::ServiceFlowRecord::SetGrantTimeStamp(), ns3::OfdmUlMapIe::SetStartTime(), ns3::OfdmUlMapIe::SetUiuc(), ns3::ServiceFlow::SF_TYPE_NRTPS, ns3::ServiceFlow::SF_TYPE_UGS, and ns3::OfdmUlBurstProfile::UIUC_REQ_REGION_FULL.
Referenced by Schedule().
SetupServiceFlow()
void ns3::UplinkSchedulerRtps::SetupServiceFlow (SSRecord * ssRecord, ServiceFlow * serviceFlow) virtual
Setup service flow function.
Parameters
ssRecord Subscriber station record
serviceFlow the service flow
Implements ns3::UplinkScheduler.
Definition at line 642 of file bs-uplink-scheduler-rtps.cc.
References ns3::UplinkScheduler::GetBs(), ns3::ServiceFlow::GetIsMulticast(), ns3::ServiceFlow::GetMinReservedTrafficRate(), ns3::ServiceFlow::GetModulation(), ns3::SSRecord::GetModulationType(), ns3::ServiceFlow::GetRecord(), ns3::ServiceFlow::GetSchedulingType(), ns3::ServiceFlow::GetSduSize(), ns3::ServiceFlow::GetToleratedJitter(), NS_FATAL_ERROR, ns3::ServiceFlowRecord::SetGrantSize(), ns3::ServiceFlow::SetUnsolicitedGrantInterval(), ns3::ServiceFlow::SetUnsolicitedPollingInterval(), ns3::ServiceFlow::SF_TYPE_BE, ns3::ServiceFlow::SF_TYPE_NRTPS, ns3::ServiceFlow::SF_TYPE_RTPS, and ns3::ServiceFlow::SF_TYPE_UGS.
ULSchedulerRTPSConnection()
void ns3::UplinkSchedulerRtps::ULSchedulerRTPSConnection (uint32_t & symbolsToAllocation, uint32_t & availableSymbols)
Uplink Scheduler for rtPS connections.
Parameters
symbolsToAllocation symbols to allocation for UpLink Subframe
availableSymbols available symbols for rtPS flows
This method represent the UL Scheduler for rtPS connections. The scheduler is designed to serve all rtPS connections that have at least one packet to transmit, every UL Subframe. The method selects all rtPS connection that have al least one packet to transmit. To each rtPS connections are allocated, at the beginning, the bandwidth to transmit a quota of data equal to (RequestedBandwidth - GrantedBandwidth). If the sum of all pre-allocated bandwidth exceed the available symbols for rtPS connections, the Channel Saturation Control function is called to redistribute the available bandwidth.
Definition at line 509 of file bs-uplink-scheduler-rtps.cc.
References AddUplinkAllocation(), ns3::WimaxNetDevice::DIRECTION_UPLINK, ns3::SSRecord::GetAreServiceFlowsAllocated(), ns3::SSRecord::GetBasicCid(), ns3::UplinkScheduler::GetBs(), ns3::ServiceFlowRecord::GetGrantedBandwidth(), ns3::SSRecord::GetIsBroadcastSS(), ns3::SSRecord::GetModulationType(), ns3::SSRecord::GetPollForRanging(), ns3::SSRecord::GetRangingStatus(), ns3::ServiceFlowRecord::GetRequestedBandwidth(), ns3::SSRecord::GetServiceFlows(), NS_LOG_INFO, ns3::WimaxNetDevice::RANGING_STATUS_CONTINUE, ns3::OfdmUlMapIe::SetCid(), ns3::ServiceFlowRecord::SetGrantedBandwidth(), ns3::ServiceFlowRecord::SetRequestedBandwidth(), ns3::OfdmUlMapIe::SetUiuc(), ns3::ServiceFlow::SF_TYPE_RTPS, and ns3::ServiceFlowRecord::UpdateGrantedBandwidth().
Referenced by Schedule().
Member Data Documentation
m_uplinkAllocations
std::list<OfdmUlMapIe> ns3::UplinkSchedulerRtps::m_uplinkAllocations private
uplink allocations
Definition at line 200 of file bs-uplink-scheduler-rtps.h.
Referenced by ~UplinkSchedulerRtps(), AddUplinkAllocation(), GetUplinkAllocations(), and Schedule().
The documentation for this class was generated from the following files:
src/wimax/model/bs-uplink-scheduler-rtps.h
src/wimax/model/bs-uplink-scheduler-rtps.cc