ns-3: Bug730TestCase Class Reference
Bug730TestCase Class Reference
Make sure that when changing the fragmentation threshold during the simulation, the TCP transmission does not unexpectedly stop.
Public Member Functions
Bug730TestCase ()
virtual ~Bug730TestCase ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void Receive (std::string context, Ptr< const Packet > p, const Address &adr)
Receive function.
Private Attributes
uint32_t m_received
received
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Make sure that when changing the fragmentation threshold during the simulation, the TCP transmission does not unexpectedly stop.
The scenario considers a TCP transmission between a 802.11b station and a 802.11b access point. After the simulation has begun, the fragmentation threshold is set at a value lower than the packet size. It then checks whether the TCP transmission continues after the fragmentation threshold modification.
See Bug 730
Definition at line 569 of file wifi-test.cc.
Constructor & Destructor Documentation
Bug730TestCase()
Bug730TestCase::Bug730TestCase ()
Definition at line 591 of file wifi-test.cc.
~Bug730TestCase()
Bug730TestCase::~Bug730TestCase () virtual
Definition at line 597 of file wifi-test.cc.
Member Function Documentation
DoRun()
void Bug730TestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 612 of file wifi-test.cc.
References ns3::ListPositionAllocator::Add(), ns3::Node::AddApplication(), third::apDevices, third::channel, ns3::Config::Connect(), ns3::NodeContainer::Create(), ns3::NodeContainer::Get(), ns3::WifiNetDevice::GetAddress(), ns3::WifiNetDevice::GetIfIndex(), ns3::PacketSocketHelper::Install(), m_received, third::mac, ns3::MakeCallback(), third::mobility, NS_TEST_ASSERT_MSG_EQ, third::phy, Receive(), ns3::Seconds(), ns3::Config::Set(), ns3::ObjectBase::SetAttribute(), ns3::PacketSocketServer::SetLocal(), ns3::PacketSocketAddress::SetPhysicalAddress(), ns3::PacketSocketAddress::SetProtocol(), ns3::PacketSocketClient::SetRemote(), ns3::PacketSocketAddress::SetSingleDevice(), ns3::Application::SetStartTime(), ns3::Application::SetStopTime(), third::ssid, third::staDevices, third::wifi, ns3::WIFI_PHY_STANDARD_80211b, and third::wifiApNode.
Receive()
void Bug730TestCase::Receive (std::string context, Ptr< const Packet > p, const Address & adr) private
Receive function.
Parameters
context the context
p the packet
adr the address
Definition at line 602 of file wifi-test.cc.
References ns3::Packet::GetSize(), m_received, ns3::Now(), and ns3::Seconds().
Referenced by DoRun().
Member Data Documentation
m_received
uint32_t Bug730TestCase::m_received private
received
Definition at line 579 of file wifi-test.cc.
Referenced by DoRun(), and Receive().
The documentation for this class was generated from the following file:
src/wifi/test/wifi-test.cc