ns-3: ns3::Ipv6FlowProbeTag Class Reference
ns3::Ipv6FlowProbeTag Class Reference
Flow Monitor
Tag used to allow a fast identification of the packet.
Public Member Functions
Ipv6FlowProbeTag ()
Ipv6FlowProbeTag (uint32_t flowId, uint32_t packetId, uint32_t packetSize)
Consructor.
virtual void Deserialize (TagBuffer buf)
uint32_t GetFlowId (void) const
Set the flow identifier.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint32_t GetPacketId (void) const
Set the packet identifier.
uint32_t GetPacketSize (void) const
Get the packet size.
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer buf) const
void SetFlowId (uint32_t flowId)
Set the flow identifier.
void SetPacketId (uint32_t packetId)
Set the packet identifier.
void SetPacketSize (uint32_t packetSize)
Set the packet size.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint32_t m_flowId
flow identifier
uint32_t m_packetId
packet identifier
uint32_t m_packetSize
packet size
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Tag used to allow a fast identification of the packet.
This tag is added by FlowMonitor when a packet is seen for the first time, and it is then used to classify the packet in the following hops.
Definition at line 49 of file ipv6-flow-probe.cc.
Constructor & Destructor Documentation
Ipv6FlowProbeTag() [1/2]
ns3::Ipv6FlowProbeTag::Ipv6FlowProbeTag ()
Definition at line 148 of file ipv6-flow-probe.cc.
Ipv6FlowProbeTag() [2/2]
ns3::Ipv6FlowProbeTag::Ipv6FlowProbeTag (uint32_t flowId, uint32_t packetId, uint32_t packetSize)
Consructor.
Parameters
flowId the flow identifier
packetId the packet identifier
packetSize the packet size
Definition at line 153 of file ipv6-flow-probe.cc.
Member Function Documentation
Deserialize()
void ns3::Ipv6FlowProbeTag::Deserialize (TagBuffer i) virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 135 of file ipv6-flow-probe.cc.
References m_flowId, m_packetId, m_packetSize, and ns3::TagBuffer::ReadU32().
GetFlowId()
uint32_t ns3::Ipv6FlowProbeTag::GetFlowId (void) const
Set the flow identifier.
Returns
the flow identifier
Definition at line 174 of file ipv6-flow-probe.cc.
References m_flowId.
Referenced by ns3::Ipv6FlowProbe::DropLogger(), ns3::Ipv6FlowProbe::ForwardLogger(), ns3::Ipv6FlowProbe::ForwardUpLogger(), ns3::Ipv6FlowProbe::QueueDiscDropLogger(), and ns3::Ipv6FlowProbe::QueueDropLogger().
GetInstanceTypeId()
TypeId ns3::Ipv6FlowProbeTag::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 118 of file ipv6-flow-probe.cc.
References GetTypeId().
GetPacketId()
uint32_t ns3::Ipv6FlowProbeTag::GetPacketId (void) const
Set the packet identifier.
Returns
the packet identifier
Definition at line 179 of file ipv6-flow-probe.cc.
References m_packetId.
Referenced by ns3::Ipv6FlowProbe::DropLogger(), ns3::Ipv6FlowProbe::ForwardLogger(), ns3::Ipv6FlowProbe::ForwardUpLogger(), ns3::Ipv6FlowProbe::QueueDiscDropLogger(), and ns3::Ipv6FlowProbe::QueueDropLogger().
GetPacketSize()
uint32_t ns3::Ipv6FlowProbeTag::GetPacketSize (void) const
Get the packet size.
Returns
the packet size
Definition at line 184 of file ipv6-flow-probe.cc.
References m_packetSize.
Referenced by ns3::Ipv6FlowProbe::QueueDiscDropLogger(), and ns3::Ipv6FlowProbe::QueueDropLogger().
GetSerializedSize()
uint32_t ns3::Ipv6FlowProbeTag::GetSerializedSize (void) const virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 123 of file ipv6-flow-probe.cc.
GetTypeId()
TypeId ns3::Ipv6FlowProbeTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 108 of file ipv6-flow-probe.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::Ipv6FlowProbeTag::Print (std::ostream & os) const virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 142 of file ipv6-flow-probe.cc.
References m_flowId, m_packetId, and m_packetSize.
Serialize()
void ns3::Ipv6FlowProbeTag::Serialize (TagBuffer i) const virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 128 of file ipv6-flow-probe.cc.
References m_flowId, m_packetId, m_packetSize, and ns3::TagBuffer::WriteU32().
SetFlowId()
void ns3::Ipv6FlowProbeTag::SetFlowId (uint32_t flowId)
Set the flow identifier.
Parameters
flowId the flow identifier
Definition at line 159 of file ipv6-flow-probe.cc.
References m_flowId.
SetPacketId()
void ns3::Ipv6FlowProbeTag::SetPacketId (uint32_t packetId)
Set the packet identifier.
Parameters
packetId the packet identifier
Definition at line 164 of file ipv6-flow-probe.cc.
References m_packetId.
SetPacketSize()
void ns3::Ipv6FlowProbeTag::SetPacketSize (uint32_t packetSize)
Set the packet size.
Parameters
packetSize the packet size
Definition at line 169 of file ipv6-flow-probe.cc.
References m_packetSize.
Member Data Documentation
m_flowId
uint32_t ns3::Ipv6FlowProbeTag::m_flowId private
flow identifier
Definition at line 101 of file ipv6-flow-probe.cc.
Referenced by Deserialize(), GetFlowId(), Print(), Serialize(), and SetFlowId().
m_packetId
uint32_t ns3::Ipv6FlowProbeTag::m_packetId private
packet identifier
Definition at line 102 of file ipv6-flow-probe.cc.
Referenced by Deserialize(), GetPacketId(), Print(), Serialize(), and SetPacketId().
m_packetSize
uint32_t ns3::Ipv6FlowProbeTag::m_packetSize private
packet size
Definition at line 103 of file ipv6-flow-probe.cc.
Referenced by Deserialize(), GetPacketSize(), Print(), Serialize(), and SetPacketSize().
The documentation for this class was generated from the following file:
src/flow-monitor/model/ipv6-flow-probe.cc