ns-3: FileHeaderTestCase Class Reference
FileHeaderTestCase Class Reference
Network » Network module unit tests | Test suites
Test case to make sure that the Pcap File Object can write out correct pcap file headers in both endian cases, and then read them in correctly.
Public Member Functions
FileHeaderTestCase ()
virtual ~FileHeaderTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
virtual void DoSetup (void)
Implementation to do any local setup required for this TestCase.
virtual void DoTeardown (void)
Implementation to do any local setup required for this TestCase.
Private Attributes
std::string m_testFilename
File name.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test case to make sure that the Pcap File Object can write out correct pcap file headers in both endian cases, and then read them in correctly.
Definition at line 427 of file pcap-file-test-suite.cc.
Constructor & Destructor Documentation
FileHeaderTestCase()
FileHeaderTestCase::FileHeaderTestCase ()
Definition at line 441 of file pcap-file-test-suite.cc.
~FileHeaderTestCase()
FileHeaderTestCase::~FileHeaderTestCase () virtual
Definition at line 446 of file pcap-file-test-suite.cc.
Member Function Documentation
DoRun()
void FileHeaderTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 469 of file pcap-file-test-suite.cc.
References f(), m_testFilename, NS_TEST_ASSERT_MSG_EQ, NS_TEST_ASSERT_MSG_NE, and Swap().
DoSetup()
void FileHeaderTestCase::DoSetup (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test setup before DoRun is invoked.
Reimplemented from ns3::TestCase.
Definition at line 451 of file pcap-file-test-suite.cc.
References ns3::TestCase::CreateTempDirFilename(), m_testFilename, and sample-rng-plot::n.
DoTeardown()
void FileHeaderTestCase::DoTeardown (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test teardown
Reimplemented from ns3::TestCase.
Definition at line 460 of file pcap-file-test-suite.cc.
References m_testFilename, and NS_LOG_ERROR.
Member Data Documentation
m_testFilename
std::string FileHeaderTestCase::m_testFilename private
File name.
Definition at line 438 of file pcap-file-test-suite.cc.
Referenced by DoRun(), DoSetup(), and DoTeardown().
The documentation for this class was generated from the following file:
src/network/test/pcap-file-test-suite.cc