ns-3: CsmaStarTestCase Class Reference
CsmaStarTestCase Class Reference
Public Member Functions
CsmaStarTestCase ()
virtual ~CsmaStarTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void DropEvent (Ptr< const Packet > p)
void SinkRx (Ptr< const Packet > p, const Address &ad)
Private Attributes
uint32_t m_count
uint32_t m_drops
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 891 of file csma-system-test-suite.cc.
Constructor & Destructor Documentation
CsmaStarTestCase()
CsmaStarTestCase::CsmaStarTestCase ()
Definition at line 906 of file csma-system-test-suite.cc.
~CsmaStarTestCase()
CsmaStarTestCase::~CsmaStarTestCase () virtual
Definition at line 911 of file csma-system-test-suite.cc.
Member Function Documentation
DoRun()
void CsmaStarTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 945 of file csma-system-test-suite.cc.
References ns3::ApplicationContainer::Add(), ns3::NetDeviceContainer::Add(), ns3::NodeContainer::Add(), first::address, ns3::CsmaStarHelper::AssignIpv4Addresses(), third::channel, ns3::Config::ConnectWithoutContext(), ns3::NodeContainer::Create(), second::csma, ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::CsmaStarHelper::GetHub(), ns3::CsmaStarHelper::GetHubIpv4Address(), ns3::NodeContainer::GetN(), ns3::CsmaStarHelper::GetSpokeDevices(), ns3::CsmaStarHelper::GetSpokeNode(), ns3::OnOffHelper::Install(), ns3::PacketSinkHelper::Install(), ns3::InternetStackHelper::Install(), ns3::CsmaStarHelper::InstallStack(), m_count, ns3::MakeCallback(), NS_TEST_ASSERT_MSG_EQ, port, ns3::Seconds(), ns3::OnOffHelper::SetAttribute(), ns3::OnOffHelper::SetConstantRate(), SinkRx(), ns3::CsmaStarHelper::SpokeCount(), ns3::ApplicationContainer::Start(), and ns3::ApplicationContainer::Stop().
DropEvent()
void CsmaStarTestCase::DropEvent (Ptr< const Packet > p) private
Definition at line 922 of file csma-system-test-suite.cc.
References m_drops.
SinkRx()
void CsmaStarTestCase::SinkRx (Ptr< const Packet > p, const Address & ad) private
Definition at line 916 of file csma-system-test-suite.cc.
References m_count.
Referenced by DoRun().
Member Data Documentation
m_count
uint32_t CsmaStarTestCase::m_count private
Definition at line 901 of file csma-system-test-suite.cc.
Referenced by DoRun(), and SinkRx().
m_drops
uint32_t CsmaStarTestCase::m_drops private
Definition at line 902 of file csma-system-test-suite.cc.
Referenced by DropEvent().
The documentation for this class was generated from the following file:
src/test/csma-system-test-suite.cc