ns-3: ns3::SimpleNetworkServer Class Reference
ns3::SimpleNetworkServer Class Reference
A SimpleNetworkServer is an application standing on top of a node equipped with links that connect it with the gateways.
#include "simple-network-server.h"
Public Member Functions
SimpleNetworkServer ()
virtual ~SimpleNetworkServer ()
void AddGateway (Ptr< Node > gateway, Ptr< NetDevice > netDevice)
Add this gateway to the list of gateways connected to this NS.
void AddNode (Ptr< Node > node)
Inform the SimpleNetworkServer that this node is connected to the network This method will create a DeviceStatus object for the new node (if it doesn't already exist)
void AddNodes (NodeContainer nodes)
Inform the SimpleNetworkServer that these nodes are connected to the network This method will create a DeviceStatus object for each new node, and add it to the list.
uint8_t GetDataRateForReply (uint8_t receivedDataRate)
Get the data rate that should be used when replying in the first receive window.
Address GetGatewayForReply (LoraDeviceAddress deviceAddress, double frequency)
Get the best gateway that is available to reply to this device.
bool HasReply (LoraDeviceAddress address)
Check whether a reply to the device with a certain address already exists.
void ParseCommands (LoraFrameHeader frameHeader)
Parse and take action on the commands contained on the frameHeader.
bool Receive (Ptr< NetDevice > device, Ptr< const Packet > packet, uint16_t protocol, const Address &address)
Receive a packet from a gateway.
void SendOnFirstWindow (LoraDeviceAddress address)
Send a packet through a gateway to an ED, using the first receive window.
void SendOnSecondWindow (LoraDeviceAddress address)
Send a packet through a gateway to an ED, using the second receive window.
void StartApplication (void)
Start the NS application.
void StopApplication (void)
Stop the NS application.
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Attributes
std::map< LoraDeviceAddress, DeviceStatus > m_deviceStatuses
std::map< Address, GatewayStatus > m_gatewayStatuses
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Additional Inherited Members
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Protected Member Functions inherited from ns3::Application
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A SimpleNetworkServer is an application standing on top of a node equipped with links that connect it with the gateways.
This version of the NetworkServer isn't smart enough to handle MAC commands, but can reply correctly with ACKs to confirmed uplink messages.
Definition at line 42 of file simple-network-server.h.
Constructor & Destructor Documentation
SimpleNetworkServer()
ns3::SimpleNetworkServer::SimpleNetworkServer ()
Definition at line 45 of file simple-network-server.cc.
References NS_LOG_FUNCTION_NOARGS.
~SimpleNetworkServer()
ns3::SimpleNetworkServer::~SimpleNetworkServer () virtual
Definition at line 50 of file simple-network-server.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
AddGateway()
void ns3::SimpleNetworkServer::AddGateway (Ptr< Node > gateway, Ptr< NetDevice > netDevice)
Add this gateway to the list of gateways connected to this NS.
Definition at line 68 of file simple-network-server.cc.
References ns3::Node::GetDevice(), ns3::Node::GetNDevices(), ns3::Object::GetObject(), m_gatewayStatuses, NS_ASSERT, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
AddNode()
void ns3::SimpleNetworkServer::AddNode (Ptr< Node > node)
Inform the SimpleNetworkServer that this node is connected to the network This method will create a DeviceStatus object for the new node (if it doesn't already exist)
Definition at line 120 of file simple-network-server.cc.
References ns3::Node::GetDevice(), ns3::Node::GetNDevices(), m_deviceStatuses, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by AddNodes().
AddNodes()
void ns3::SimpleNetworkServer::AddNodes (NodeContainer nodes)
Inform the SimpleNetworkServer that these nodes are connected to the network This method will create a DeviceStatus object for each new node, and add it to the list.
Definition at line 107 of file simple-network-server.cc.
References AddNode(), first::nodes, and NS_LOG_FUNCTION_NOARGS.
GetDataRateForReply()
uint8_t ns3::SimpleNetworkServer::GetDataRateForReply (uint8_t receivedDataRate)
Get the data rate that should be used when replying in the first receive window.
GetGatewayForReply()
Address ns3::SimpleNetworkServer::GetGatewayForReply (LoraDeviceAddress deviceAddress, double frequency)
Get the best gateway that is available to reply to this device.
This method assumes the gateway needs to be available at the time that it is called.
Definition at line 300 of file simple-network-server.cc.
References m_deviceStatuses, m_gatewayStatuses, ns3::Simulator::Now(), and NS_LOG_FUNCTION.
Referenced by SendOnFirstWindow(), and SendOnSecondWindow().
GetTypeId()
TypeId ns3::SimpleNetworkServer::GetTypeId (void) static
Definition at line 36 of file simple-network-server.cc.
References ns3::TypeId::SetParent().
HasReply()
bool ns3::SimpleNetworkServer::HasReply (LoraDeviceAddress address)
Check whether a reply to the device with a certain address already exists.
ParseCommands()
void ns3::SimpleNetworkServer::ParseCommands (LoraFrameHeader frameHeader)
Parse and take action on the commands contained on the frameHeader.
Receive()
bool ns3::SimpleNetworkServer::Receive (Ptr< NetDevice > device, Ptr< const Packet > packet, uint16_t protocol, const Address & address)
Receive a packet from a gateway.
Parameters
packet the received packet
Definition at line 156 of file simple-network-server.cc.
References first::address, ns3::LoraMacHeader::CONFIRMED_DATA_UP, ns3::Packet::Copy(), ns3::DeviceStatus::Reply::frameHeader, ns3::LoraFrameHeader::GetAddress(), ns3::LoraTag::GetFrequency(), ns3::LoraMacHeader::GetMType(), ns3::LoraTag::GetReceivePower(), ns3::DeviceStatus::Reply::hasReply, m_deviceStatuses, ns3::DeviceStatus::Reply::macHeader, NS_LOG_DEBUG, NS_LOG_FUNCTION, packet, ns3::DeviceStatus::Reply::packet, ns3::Packet::RemoveHeader(), ns3::Packet::RemovePacketTag(), ns3::Simulator::Schedule(), ns3::Seconds(), SendOnFirstWindow(), ns3::LoraFrameHeader::SetAck(), ns3::LoraFrameHeader::SetAddress(), ns3::LoraFrameHeader::SetAsDownlink(), ns3::LoraFrameHeader::SetAsUplink(), ns3::LoraMacHeader::SetMajor(), ns3::LoraMacHeader::SetMType(), and ns3::LoraMacHeader::UNCONFIRMED_DATA_DOWN.
Referenced by ns3::NetworkServerHelper::InstallPriv().
SendOnFirstWindow()
void ns3::SimpleNetworkServer::SendOnFirstWindow (LoraDeviceAddress address)
Send a packet through a gateway to an ED, using the first receive window.
Definition at line 213 of file simple-network-server.cc.
References ns3::Packet::AddPacketTag(), first::address, GetGatewayForReply(), ns3::Packet::GetSize(), m_deviceStatuses, m_gatewayStatuses, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::Simulator::Schedule(), ns3::Seconds(), SendOnSecondWindow(), ns3::LoraTag::SetDataRate(), and ns3::LoraTag::SetFrequency().
Referenced by Receive().
SendOnSecondWindow()
void ns3::SimpleNetworkServer::SendOnSecondWindow (LoraDeviceAddress address)
Send a packet through a gateway to an ED, using the second receive window.
Definition at line 259 of file simple-network-server.cc.
References ns3::Packet::AddPacketTag(), first::address, GetGatewayForReply(), ns3::Packet::GetSize(), m_deviceStatuses, m_gatewayStatuses, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::LoraTag::SetDataRate(), and ns3::LoraTag::SetFrequency().
Referenced by SendOnFirstWindow().
StartApplication()
void ns3::SimpleNetworkServer::StartApplication (void) virtual
Start the NS application.
Reimplemented from ns3::Application.
Definition at line 56 of file simple-network-server.cc.
References NS_LOG_FUNCTION_NOARGS.
StopApplication()
void ns3::SimpleNetworkServer::StopApplication (void) virtual
Stop the NS application.
Reimplemented from ns3::Application.
Definition at line 62 of file simple-network-server.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Data Documentation
m_deviceStatuses
std::map<LoraDeviceAddress,DeviceStatus> ns3::SimpleNetworkServer::m_deviceStatuses protected
Definition at line 119 of file simple-network-server.h.
Referenced by AddNode(), GetGatewayForReply(), Receive(), SendOnFirstWindow(), and SendOnSecondWindow().
m_gatewayStatuses
std::map<Address,GatewayStatus> ns3::SimpleNetworkServer::m_gatewayStatuses protected
Definition at line 121 of file simple-network-server.h.
Referenced by AddGateway(), GetGatewayForReply(), SendOnFirstWindow(), and SendOnSecondWindow().
The documentation for this class was generated from the following files:
src/lorawan/model/simple-network-server.h
src/lorawan/model/simple-network-server.cc