ns-3: ns3::dsr::DsrOptionRerrHeader Class Reference
ns3::dsr::DsrOptionRerrHeader Class Reference
Header of Dsr Option Route Error.
#include "dsr-option-header.h"
Public Member Functions
DsrOptionRerrHeader ()
Constructor.
virtual ~DsrOptionRerrHeader ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
virtual Alignment GetAlignment () const
Get the Alignment requirement of this option header.
virtual Ipv4Address GetErrorDst () const
Get the error destination ip address.
virtual Ipv4Address GetErrorSrc () const
Get the route error source address.
uint8_t GetErrorType () const
Get the route error type.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
virtual uint8_t GetSalvage () const
Get the salvage value of the packet.
virtual uint32_t GetSerializedSize () const
Get the serialized size of the packet.
virtual void Print (std::ostream &os) const
Print some information about the packet.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
virtual void SetErrorDst (Ipv4Address errorDstAddress)
Set the error destination ip address.
virtual void SetErrorSrc (Ipv4Address errorSrcAddress)
Set the route error source address.
void SetErrorType (uint8_t errorType)
Set the route error type.
virtual void SetSalvage (uint8_t salvage)
Set the salvage value of the packet.
Public Member Functions inherited from ns3::dsr::DsrOptionHeader
DsrOptionHeader ()
Constructor.
virtual ~DsrOptionHeader ()
Destructor.
uint8_t GetLength () const
Get the option length.
uint8_t GetType () const
Get the type of the option.
void SetLength (uint8_t length)
Set the option length.
void SetType (uint8_t type)
Set the type of the option.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::dsr::DsrOptionHeader
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Buffer m_errorData
The anonymous data of this option.
Ipv4Address m_errorDstAddress
The error destination address.
uint16_t m_errorLength
The specific error message length.
Ipv4Address m_errorSrcAddress
The error source address.
uint8_t m_errorType
The error type or route error option.
uint8_t m_salvage
The salavage field.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Header of Dsr Option Route Error.
Definition at line 734 of file dsr-option-header.h.
Constructor & Destructor Documentation
DsrOptionRerrHeader()
ns3::dsr::DsrOptionRerrHeader::DsrOptionRerrHeader ()
Constructor.
Definition at line 679 of file dsr-option-header.cc.
References ns3::dsr::DsrOptionHeader::SetLength(), and ns3::dsr::DsrOptionHeader::SetType().
~DsrOptionRerrHeader()
ns3::dsr::DsrOptionRerrHeader::~DsrOptionRerrHeader () virtual
Destructor.
Definition at line 688 of file dsr-option-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::dsr::DsrOptionRerrHeader::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start Buffer iterator
Returns
size of the packet
Reimplemented from ns3::dsr::DsrOptionHeader.
Reimplemented in ns3::dsr::DsrOptionRerrUnsupportHeader, and ns3::dsr::DsrOptionRerrUnreachHeader.
Definition at line 758 of file dsr-option-header.cc.
References ns3::Buffer::AddAtEnd(), ns3::Buffer::Begin(), GetSerializedSize(), m_errorData, m_errorDstAddress, m_errorLength, m_errorSrcAddress, m_errorType, m_salvage, ns3::Buffer::Iterator::Next(), ns3::ReadFrom(), ns3::Buffer::Iterator::ReadU8(), ns3::dsr::DsrOptionHeader::SetLength(), ns3::dsr::DsrOptionHeader::SetType(), visualizer.core::start(), and ns3::Buffer::Iterator::Write().
GetAlignment()
DsrOptionHeader::Alignment ns3::dsr::DsrOptionRerrHeader::GetAlignment () const virtual
Get the Alignment requirement of this option header.
Returns
The required alignment
Reimplemented from ns3::dsr::DsrOptionHeader.
Reimplemented in ns3::dsr::DsrOptionRerrUnsupportHeader, and ns3::dsr::DsrOptionRerrUnreachHeader.
Definition at line 779 of file dsr-option-header.cc.
GetErrorDst()
Ipv4Address ns3::dsr::DsrOptionRerrHeader::GetErrorDst () const virtual
Get the error destination ip address.
Returns
The error destination address
Reimplemented in ns3::dsr::DsrOptionRerrUnsupportHeader, and ns3::dsr::DsrOptionRerrUnreachHeader.
Definition at line 727 of file dsr-option-header.cc.
References m_errorDstAddress.
GetErrorSrc()
Ipv4Address ns3::dsr::DsrOptionRerrHeader::GetErrorSrc () const virtual
Get the route error source address.
Returns
The error source address
Reimplemented in ns3::dsr::DsrOptionRerrUnsupportHeader, and ns3::dsr::DsrOptionRerrUnreachHeader.
Definition at line 717 of file dsr-option-header.cc.
References m_errorSrcAddress.
GetErrorType()
uint8_t ns3::dsr::DsrOptionRerrHeader::GetErrorType () const
Get the route error type.
Returns
The error type
Definition at line 697 of file dsr-option-header.cc.
References m_errorType.
Referenced by ns3::dsr::DsrOptionRerrUnreachHeader::Serialize(), and ns3::dsr::DsrOptionRerrUnsupportHeader::Serialize().
GetInstanceTypeId()
TypeId ns3::dsr::DsrOptionRerrHeader::GetInstanceTypeId () const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::dsr::DsrOptionHeader.
Reimplemented in ns3::dsr::DsrOptionRerrUnsupportHeader, and ns3::dsr::DsrOptionRerrUnreachHeader.
Definition at line 674 of file dsr-option-header.cc.
References GetTypeId().
GetSalvage()
uint8_t ns3::dsr::DsrOptionRerrHeader::GetSalvage () const virtual
Get the salvage value of the packet.
Returns
The salvage value of the packet
Reimplemented in ns3::dsr::DsrOptionRerrUnsupportHeader, and ns3::dsr::DsrOptionRerrUnreachHeader.
Definition at line 707 of file dsr-option-header.cc.
References m_salvage.
GetSerializedSize()
uint32_t ns3::dsr::DsrOptionRerrHeader::GetSerializedSize () const virtual
Get the serialized size of the packet.
Returns
size
Reimplemented from ns3::dsr::DsrOptionHeader.
Reimplemented in ns3::dsr::DsrOptionRerrUnsupportHeader, and ns3::dsr::DsrOptionRerrUnreachHeader.
Definition at line 740 of file dsr-option-header.cc.
Referenced by Deserialize().
GetTypeId()
TypeId ns3::dsr::DsrOptionRerrHeader::GetTypeId () static
Get the type identificator.
Returns
type identificator
Definition at line 664 of file dsr-option-header.cc.
References ns3::TypeId::AddConstructor().
Referenced by GetInstanceTypeId().
Print()
void ns3::dsr::DsrOptionRerrHeader::Print (std::ostream & os) const virtual
Print some information about the packet.
Parameters
os output stream
Returns
info about this packet
Reimplemented from ns3::dsr::DsrOptionHeader.
Reimplemented in ns3::dsr::DsrOptionRerrUnsupportHeader, and ns3::dsr::DsrOptionRerrUnreachHeader.
Definition at line 732 of file dsr-option-header.cc.
References ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrOptionHeader::GetType(), m_errorDstAddress, m_errorSrcAddress, m_errorType, and m_salvage.
Serialize()
void ns3::dsr::DsrOptionRerrHeader::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start Buffer iterator
Reimplemented from ns3::dsr::DsrOptionHeader.
Reimplemented in ns3::dsr::DsrOptionRerrUnsupportHeader, and ns3::dsr::DsrOptionRerrUnreachHeader.
Definition at line 745 of file dsr-option-header.cc.
References ns3::Buffer::Begin(), ns3::Buffer::End(), ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrOptionHeader::GetType(), m_errorData, m_errorDstAddress, m_errorSrcAddress, m_errorType, m_salvage, visualizer.core::start(), ns3::Buffer::Iterator::Write(), ns3::WriteTo(), and ns3::Buffer::Iterator::WriteU8().
SetErrorDst()
void ns3::dsr::DsrOptionRerrHeader::SetErrorDst (Ipv4Address errorDstAddress) virtual
Set the error destination ip address.
Parameters
errorDstAddress The error destination address
Reimplemented in ns3::dsr::DsrOptionRerrUnsupportHeader, and ns3::dsr::DsrOptionRerrUnreachHeader.
Definition at line 722 of file dsr-option-header.cc.
References m_errorDstAddress.
SetErrorSrc()
void ns3::dsr::DsrOptionRerrHeader::SetErrorSrc (Ipv4Address errorSrcAddress) virtual
Set the route error source address.
Parameters
errorSrcAddress The error source address
Reimplemented in ns3::dsr::DsrOptionRerrUnsupportHeader, and ns3::dsr::DsrOptionRerrUnreachHeader.
Definition at line 712 of file dsr-option-header.cc.
References m_errorSrcAddress.
SetErrorType()
void ns3::dsr::DsrOptionRerrHeader::SetErrorType (uint8_t errorType)
Set the route error type.
Parameters
errorType The error type
Definition at line 692 of file dsr-option-header.cc.
References m_errorType.
Referenced by ns3::dsr::DsrOptionRerrUnreachHeader::DsrOptionRerrUnreachHeader(), ns3::dsr::DsrOptionRerrUnsupportHeader::DsrOptionRerrUnsupportHeader(), ns3::dsr::DsrRouting::CheckSendBuffer(), ns3::dsr::DsrOptionRerrUnreachHeader::Deserialize(), ns3::dsr::DsrOptionRerrUnsupportHeader::Deserialize(), ns3::dsr::DsrOptionRreq::Process(), ns3::dsr::DsrRouting::SendPacketFromBuffer(), and ns3::dsr::DsrRouting::SendUnreachError().
SetSalvage()
void ns3::dsr::DsrOptionRerrHeader::SetSalvage (uint8_t salvage) virtual
Set the salvage value of the packet.
Parameters
salvage The salvage value of the packet
Reimplemented in ns3::dsr::DsrOptionRerrUnsupportHeader, and ns3::dsr::DsrOptionRerrUnreachHeader.
Definition at line 702 of file dsr-option-header.cc.
References m_salvage.
Member Data Documentation
m_errorData
Buffer ns3::dsr::DsrOptionRerrHeader::m_errorData private
The anonymous data of this option.
Definition at line 847 of file dsr-option-header.h.
Referenced by Deserialize(), and Serialize().
m_errorDstAddress
Ipv4Address ns3::dsr::DsrOptionRerrHeader::m_errorDstAddress private
The error destination address.
Definition at line 843 of file dsr-option-header.h.
Referenced by Deserialize(), GetErrorDst(), Print(), Serialize(), and SetErrorDst().
m_errorLength
uint16_t ns3::dsr::DsrOptionRerrHeader::m_errorLength private
The specific error message length.
Definition at line 835 of file dsr-option-header.h.
Referenced by Deserialize().
m_errorSrcAddress
Ipv4Address ns3::dsr::DsrOptionRerrHeader::m_errorSrcAddress private
The error source address.
Definition at line 839 of file dsr-option-header.h.
Referenced by Deserialize(), GetErrorSrc(), Print(), Serialize(), and SetErrorSrc().
m_errorType
uint8_t ns3::dsr::DsrOptionRerrHeader::m_errorType private
The error type or route error option.
Definition at line 827 of file dsr-option-header.h.
Referenced by Deserialize(), GetErrorType(), Print(), Serialize(), and SetErrorType().
m_salvage
uint8_t ns3::dsr::DsrOptionRerrHeader::m_salvage private
The salavage field.
Definition at line 831 of file dsr-option-header.h.
Referenced by Deserialize(), GetSalvage(), Print(), Serialize(), and SetSalvage().
The documentation for this class was generated from the following files:
src/dsr/model/dsr-option-header.h
src/dsr/model/dsr-option-header.cc