ns-3: ns3::LteRlc Class Reference
ns3::LteRlc Class Reference abstract
This abstract base class defines the API to interact with the Radio Link Control (LTE_RLC) in LTE, see 3GPP TS 36.322.
#include "lte-rlc.h"
Public Types
typedef void(* NotifyTxTracedCallback) (uint16_t rnti, uint8_t lcid, uint32_t bytes)
TracedCallback signature for NotifyTxOpportunity events.
typedef void(* ReceiveTracedCallback) (uint16_t rnti, uint8_t lcid, uint32_t bytes, uint64_t delay)
TracedCallback signature for.
Public Member Functions
LteRlc ()
virtual ~LteRlc ()
virtual void DoDispose ()
Destructor implementation.
LteMacSapUser * GetLteMacSapUser ()
LteRlcSapProvider * GetLteRlcSapProvider ()
void SetLcId (uint8_t lcId)
void SetLteMacSapProvider (LteMacSapProvider *s)
void SetLteRlcSapUser (LteRlcSapUser *s)
void SetRnti (uint16_t rnti)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoNotifyHarqDeliveryFailure ()=0
Notify HARQ delivery failure.
virtual void DoNotifyTxOpportunity (LteMacSapUser::TxOpportunityParameters params)=0
Notify transmit opportunity.
virtual void DoReceivePdu (LteMacSapUser::ReceivePduParameters params)=0
Receive PDU function.
virtual void DoTransmitPdcpPdu (Ptr< Packet > p)=0
Transmit PDCP PDU.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes
uint8_t m_lcid
LCID.
LteMacSapProvider * m_macSapProvider
MAC SAP provider.
LteMacSapUser * m_macSapUser
MAC SAP user.
LteRlcSapProvider * m_rlcSapProvider
RLC SAP provider.
LteRlcSapUser * m_rlcSapUser
RLC SAP user.
uint16_t m_rnti
RNTI.
TracedCallback< uint16_t, uint8_t, uint32_t, uint64_t > m_rxPdu
Used to inform of a PDU reception from the MAC SAP user.
TracedCallback< uint16_t, uint8_t, uint32_t > m_txPdu
Used to inform of a PDU delivery to the MAC SAP provider.
Friends
class LteRlcSpecificLteMacSapUser
allow LteRlcSpecificLteMacSapUser class friend access
class LteRlcSpecificLteRlcSapProvider< LteRlc >
allow LteRlcSpecificLteRlcSapProvider<LteRlc> class friend access
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This abstract base class defines the API to interact with the Radio Link Control (LTE_RLC) in LTE, see 3GPP TS 36.322.
Definition at line 50 of file lte-rlc.h.
Member Typedef Documentation
NotifyTxTracedCallback
typedef void(* ns3::LteRlc::NotifyTxTracedCallback) (uint16_t rnti, uint8_t lcid, uint32_t bytes)
TracedCallback signature for NotifyTxOpportunity events.
Parameters
[in] rnti C-RNTI scheduled.
[in] lcid The logical channel id corresponding to the sending RLC instance.
[in] bytes The number of bytes to transmit
Definition at line 117 of file lte-rlc.h.
ReceiveTracedCallback
typedef void(* ns3::LteRlc::ReceiveTracedCallback) (uint16_t rnti, uint8_t lcid, uint32_t bytes, uint64_t delay)
TracedCallback signature for.
Parameters
[in] rnti C-RNTI scheduled.
[in] lcid The logical channel id corresponding to the sending RLC instance.
[in] bytes The packet size.
[in] delay Delay since sender timestamp, in ns.
Definition at line 129 of file lte-rlc.h.
Constructor & Destructor Documentation
LteRlc()
ns3::LteRlc::LteRlc ()
Definition at line 88 of file lte-rlc.cc.
References LteRlcSpecificLteMacSapUser, LteRlcSpecificLteRlcSapProvider< LteRlc >, m_macSapUser, m_rlcSapProvider, and NS_LOG_FUNCTION.
~LteRlc()
ns3::LteRlc::~LteRlc () virtual
Definition at line 99 of file lte-rlc.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::LteRlc::DoDispose () virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Reimplemented in ns3::LteRlcSm, ns3::LteRlcUm, ns3::LteRlcTm, and ns3::LteRlcAm.
Definition at line 122 of file lte-rlc.cc.
References m_macSapUser, m_rlcSapProvider, and NS_LOG_FUNCTION.
Referenced by ns3::LteRlcAm::DoDispose(), ns3::LteRlcTm::DoDispose(), ns3::LteRlcUm::DoDispose(), and ns3::LteRlcSm::DoDispose().
DoNotifyHarqDeliveryFailure()
virtual void ns3::LteRlc::DoNotifyHarqDeliveryFailure () protected pure virtual
Notify HARQ delivery failure.
Implemented in ns3::LteRlcSm, ns3::LteRlcUm, ns3::LteRlcTm, and ns3::LteRlcAm.
Referenced by ns3::LteRlcSpecificLteMacSapUser::NotifyHarqDeliveryFailure().
DoNotifyTxOpportunity()
virtual void ns3::LteRlc::DoNotifyTxOpportunity (LteMacSapUser::TxOpportunityParameters params) protected pure virtual
Notify transmit opportunity.
Parameters
params LteMacSapUser::TxOpportunityParameters
Implemented in ns3::LteRlcSm, ns3::LteRlcUm, ns3::LteRlcTm, and ns3::LteRlcAm.
Referenced by ns3::LteRlcSpecificLteMacSapUser::NotifyTxOpportunity().
DoReceivePdu()
virtual void ns3::LteRlc::DoReceivePdu (LteMacSapUser::ReceivePduParameters params) protected pure virtual
Receive PDU function.
Parameters
params the LteMacSapUser::ReceivePduParameters
Implemented in ns3::LteRlcSm, ns3::LteRlcUm, ns3::LteRlcTm, and ns3::LteRlcAm.
Referenced by ns3::LteRlcSpecificLteMacSapUser::ReceivePdu().
DoTransmitPdcpPdu()
virtual void ns3::LteRlc::DoTransmitPdcpPdu (Ptr< Packet > p) protected pure virtual
Transmit PDCP PDU.
Todo:
MRE What is the sense to duplicate all the interfaces here???
Parameters
p packet
Implemented in ns3::LteRlcSm, ns3::LteRlcUm, ns3::LteRlcTm, and ns3::LteRlcAm.
GetLteMacSapUser()
LteMacSapUser * ns3::LteRlc::GetLteMacSapUser ()
Returns
the MAC SAP User interface offered to the MAC by this LTE_RLC
Definition at line 165 of file lte-rlc.cc.
References m_macSapUser, and NS_LOG_FUNCTION.
Referenced by ns3::LteUeRrc::ApplyRadioResourceConfigDedicated(), ns3::UeManager::DoInitialize(), ns3::LteUeRrc::DoInitialize(), LteRlcAmTransmitterTestCase::DoRun(), LteRlcUmTransmitterTestCase::DoRun(), ns3::LteSimpleHelper::InstallSingleEnbDevice(), ns3::LteSimpleHelper::InstallSingleUeDevice(), and ns3::UeManager::SetupDataRadioBearer().
GetLteRlcSapProvider()
LteRlcSapProvider * ns3::LteRlc::GetLteRlcSapProvider ()
Returns
the RLC SAP Provider interface offered to the PDCP by this LTE_RLC
Definition at line 151 of file lte-rlc.cc.
References m_rlcSapProvider, and NS_LOG_FUNCTION.
Referenced by ns3::LteUeRrc::ApplyRadioResourceConfigDedicated(), ns3::UeManager::DoInitialize(), LteRlcAmTransmitterTestCase::DoRun(), LteRlcUmTransmitterTestCase::DoRun(), ns3::LteSimpleHelper::InstallSingleEnbDevice(), ns3::LteSimpleHelper::InstallSingleUeDevice(), and ns3::UeManager::SetupDataRadioBearer().
GetTypeId()
TypeId ns3::LteRlc::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 104 of file lte-rlc.cc.
References m_rxPdu, m_txPdu, ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
SetLcId()
void ns3::LteRlc::SetLcId (uint8_t lcId)
Parameters
lcId
Definition at line 137 of file lte-rlc.cc.
References m_lcid, and NS_LOG_FUNCTION.
Referenced by ns3::LteUeRrc::ApplyRadioResourceConfigDedicated(), ns3::UeManager::DoInitialize(), ns3::LteUeRrc::DoInitialize(), LteRlcAmTransmitterTestCase::DoRun(), LteRlcUmTransmitterTestCase::DoRun(), ns3::LteSimpleHelper::InstallSingleEnbDevice(), ns3::LteSimpleHelper::InstallSingleUeDevice(), and ns3::UeManager::SetupDataRadioBearer().
SetLteMacSapProvider()
void ns3::LteRlc::SetLteMacSapProvider (LteMacSapProvider * s)
Parameters
s the MAC SAP Provider to be used by this LTE_RLC
Definition at line 158 of file lte-rlc.cc.
References m_macSapProvider, and NS_LOG_FUNCTION.
Referenced by ns3::LteUeRrc::ApplyRadioResourceConfigDedicated(), ns3::UeManager::DoInitialize(), ns3::LteUeRrc::DoInitialize(), LteRlcAmTransmitterTestCase::DoRun(), LteRlcUmTransmitterTestCase::DoRun(), ns3::LteSimpleHelper::InstallSingleEnbDevice(), ns3::LteSimpleHelper::InstallSingleUeDevice(), and ns3::UeManager::SetupDataRadioBearer().
SetLteRlcSapUser()
void ns3::LteRlc::SetLteRlcSapUser (LteRlcSapUser * s)
Parameters
s the RLC SAP user to be used by this LTE_RLC
Definition at line 144 of file lte-rlc.cc.
References m_rlcSapUser, and NS_LOG_FUNCTION.
Referenced by ns3::LteUeRrc::ApplyRadioResourceConfigDedicated(), ns3::UeManager::DoInitialize(), LteRlcAmTransmitterTestCase::DoRun(), LteRlcUmTransmitterTestCase::DoRun(), ns3::LteSimpleHelper::InstallSingleEnbDevice(), ns3::LteSimpleHelper::InstallSingleUeDevice(), and ns3::UeManager::SetupDataRadioBearer().
SetRnti()
void ns3::LteRlc::SetRnti (uint16_t rnti)
Parameters
rnti
Definition at line 130 of file lte-rlc.cc.
References m_rnti, and NS_LOG_FUNCTION.
Referenced by ns3::LteUeRrc::ApplyRadioResourceConfigDedicated(), ns3::UeManager::DoInitialize(), ns3::LteUeRrc::DoInitialize(), LteRlcAmTransmitterTestCase::DoRun(), LteRlcUmTransmitterTestCase::DoRun(), ns3::LteSimpleHelper::InstallSingleEnbDevice(), ns3::LteSimpleHelper::InstallSingleUeDevice(), and ns3::UeManager::SetupDataRadioBearer().
Friends And Related Function Documentation
LteRlcSpecificLteMacSapUser
friend class LteRlcSpecificLteMacSapUser friend
allow LteRlcSpecificLteMacSapUser class friend access
Definition at line 53 of file lte-rlc.h.
Referenced by LteRlc().
LteRlcSpecificLteRlcSapProvider< LteRlc >
friend class LteRlcSpecificLteRlcSapProvider< LteRlc > friend
allow LteRlcSpecificLteRlcSapProvider<LteRlc> class friend access
Definition at line 53 of file lte-rlc.h.
Referenced by LteRlc().
Member Data Documentation
m_lcid
uint8_t ns3::LteRlc::m_lcid protected
LCID.
Definition at line 169 of file lte-rlc.h.
Referenced by ns3::LteRlcAm::DoNotifyTxOpportunity(), ns3::LteRlcTm::DoNotifyTxOpportunity(), ns3::LteRlcUm::DoNotifyTxOpportunity(), ns3::LteRlcSm::DoNotifyTxOpportunity(), ns3::LteRlcAm::DoReceivePdu(), ns3::LteRlcTm::DoReceivePdu(), ns3::LteRlcUm::DoReceivePdu(), ns3::LteRlcSm::DoReceivePdu(), ns3::LteRlcAm::DoReportBufferStatus(), ns3::LteRlcTm::DoReportBufferStatus(), ns3::LteRlcUm::DoReportBufferStatus(), ns3::LteRlcAm::DoTransmitPdcpPdu(), ns3::LteRlcTm::DoTransmitPdcpPdu(), ns3::LteRlcUm::DoTransmitPdcpPdu(), ns3::LteRlcUm::ExpireReorderingTimer(), ns3::LteRlcSm::ReportBufferStatus(), and SetLcId().
m_macSapProvider
LteMacSapProvider* ns3::LteRlc::m_macSapProvider protected
MAC SAP provider.
Definition at line 166 of file lte-rlc.h.
Referenced by ns3::LteRlcAm::DoNotifyTxOpportunity(), ns3::LteRlcTm::DoNotifyTxOpportunity(), ns3::LteRlcUm::DoNotifyTxOpportunity(), ns3::LteRlcSm::DoNotifyTxOpportunity(), ns3::LteRlcAm::DoReportBufferStatus(), ns3::LteRlcTm::DoReportBufferStatus(), ns3::LteRlcUm::DoReportBufferStatus(), ns3::LteRlcSm::ReportBufferStatus(), and SetLteMacSapProvider().
m_macSapUser
LteMacSapUser* ns3::LteRlc::m_macSapUser protected
MAC SAP user.
Definition at line 165 of file lte-rlc.h.
Referenced by LteRlc(), DoDispose(), and GetLteMacSapUser().
m_rlcSapProvider
LteRlcSapProvider* ns3::LteRlc::m_rlcSapProvider protected
RLC SAP provider.
Definition at line 145 of file lte-rlc.h.
Referenced by LteRlc(), DoDispose(), and GetLteRlcSapProvider().
m_rlcSapUser
LteRlcSapUser* ns3::LteRlc::m_rlcSapUser protected
RLC SAP user.
Definition at line 144 of file lte-rlc.h.
Referenced by ns3::LteRlcTm::DoReceivePdu(), ns3::LteRlcAm::ReassembleAndDeliver(), ns3::LteRlcUm::ReassembleAndDeliver(), and SetLteRlcSapUser().
m_rnti
uint16_t ns3::LteRlc::m_rnti protected
RNTI.
Definition at line 168 of file lte-rlc.h.
Referenced by ns3::LteRlcAm::DoNotifyTxOpportunity(), ns3::LteRlcTm::DoNotifyTxOpportunity(), ns3::LteRlcUm::DoNotifyTxOpportunity(), ns3::LteRlcSm::DoNotifyTxOpportunity(), ns3::LteRlcAm::DoReceivePdu(), ns3::LteRlcTm::DoReceivePdu(), ns3::LteRlcUm::DoReceivePdu(), ns3::LteRlcSm::DoReceivePdu(), ns3::LteRlcAm::DoReportBufferStatus(), ns3::LteRlcTm::DoReportBufferStatus(), ns3::LteRlcUm::DoReportBufferStatus(), ns3::LteRlcAm::DoTransmitPdcpPdu(), ns3::LteRlcTm::DoTransmitPdcpPdu(), ns3::LteRlcUm::DoTransmitPdcpPdu(), ns3::LteRlcUm::ExpireReorderingTimer(), ns3::LteRlcSm::ReportBufferStatus(), and SetRnti().
m_rxPdu
TracedCallback<uint16_t, uint8_t, uint32_t, uint64_t> ns3::LteRlc::m_rxPdu protected
Used to inform of a PDU reception from the MAC SAP user.
Definition at line 178 of file lte-rlc.h.
Referenced by ns3::LteRlcAm::DoReceivePdu(), ns3::LteRlcTm::DoReceivePdu(), ns3::LteRlcUm::DoReceivePdu(), ns3::LteRlcSm::DoReceivePdu(), and GetTypeId().
m_txPdu
TracedCallback<uint16_t, uint8_t, uint32_t> ns3::LteRlc::m_txPdu protected
Used to inform of a PDU delivery to the MAC SAP provider.
Definition at line 174 of file lte-rlc.h.
Referenced by ns3::LteRlcAm::DoNotifyTxOpportunity(), ns3::LteRlcTm::DoNotifyTxOpportunity(), ns3::LteRlcUm::DoNotifyTxOpportunity(), ns3::LteRlcSm::DoNotifyTxOpportunity(), and GetTypeId().
The documentation for this class was generated from the following files:
src/lte/model/lte-rlc.h
src/lte/model/lte-rlc.cc