ns-3: WaypointLazyNotifyFalse Class Reference
WaypointLazyNotifyFalse Class Reference
Mobility » mobility module tests | Test suites
Test whether course change notifications occur regardless of calls to Update() position (which are triggered by calls to GetPosition())
Public Member Functions
WaypointLazyNotifyFalse ()
virtual ~WaypointLazyNotifyFalse ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CourseChangeCallback (std::string path, Ptr< const MobilityModel > model)
Course change callback.
virtual void DoRun (void)
Implementation to actually run this TestCase.
void TestXPosition (double expectedXPos)
Test X position function.
Private Attributes
int m_courseChanges
course changes
Ptr< WaypointMobilityModel > m_mob
modility model
Ptr< Node > m_node
mode
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test whether course change notifications occur regardless of calls to Update() position (which are triggered by calls to GetPosition())
Definition at line 44 of file mobility-test-suite.cc.
Constructor & Destructor Documentation
WaypointLazyNotifyFalse()
WaypointLazyNotifyFalse::WaypointLazyNotifyFalse ()
Definition at line 68 of file mobility-test-suite.cc.
~WaypointLazyNotifyFalse()
WaypointLazyNotifyFalse::~WaypointLazyNotifyFalse () virtual
Definition at line 74 of file mobility-test-suite.cc.
Member Function Documentation
CourseChangeCallback()
void WaypointLazyNotifyFalse::CourseChangeCallback (std::string path, Ptr< const MobilityModel > model) private
Course change callback.
Parameters
path the path
model the mobility model
Definition at line 86 of file mobility-test-suite.cc.
References m_courseChanges, ns3::Now(), and NS_TEST_EXPECT_MSG_EQ_TOL_INTERNAL.
DoRun()
void WaypointLazyNotifyFalse::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 94 of file mobility-test-suite.cc.
References ns3::WaypointMobilityModel::AddWaypoint(), ns3::Object::AggregateObject(), m_mob, m_node, ns3::Seconds(), and TestXPosition().
TestXPosition()
void WaypointLazyNotifyFalse::TestXPosition (double expectedXPos) private
Test X position function.
Parameters
expectedXPos the expected X position
Definition at line 79 of file mobility-test-suite.cc.
References ns3::MobilityModel::GetPosition(), m_mob, and NS_TEST_EXPECT_MSG_EQ_TOL_INTERNAL.
Referenced by DoRun().
Member Data Documentation
m_courseChanges
int WaypointLazyNotifyFalse::m_courseChanges private
course changes
Definition at line 65 of file mobility-test-suite.cc.
Referenced by CourseChangeCallback().
m_mob
Ptr<WaypointMobilityModel> WaypointLazyNotifyFalse::m_mob private
modility model
Definition at line 64 of file mobility-test-suite.cc.
Referenced by DoRun(), and TestXPosition().
m_node
Ptr<Node> WaypointLazyNotifyFalse::m_node private
mode
Definition at line 63 of file mobility-test-suite.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/mobility/test/mobility-test-suite.cc