ns-3: ns3::LteRlcHeader Class Reference
ns3::LteRlcHeader Class Reference
LTE Models
The packet header for the Radio Link Control (RLC) protocol packets.
#include "lte-rlc-header.h"
Public Types
enum ExtensionBit_t { DATA_FIELD_FOLLOWS = 0, E_LI_FIELDS_FOLLOWS = 1 }
ExtensionBit_t typedef.
enum FramingInfoFirstByte_t { FIRST_BYTE = 0x00, NO_FIRST_BYTE = 0x02 }
FramingInfoFirstByte_t typedef.
enum FramingInfoLastByte_t { LAST_BYTE = 0x00, NO_LAST_BYTE = 0x01 }
FramingInfoLastByte_t tyedef.
Public Member Functions
LteRlcHeader ()
Constructor.
~LteRlcHeader ()
virtual uint32_t Deserialize (Buffer::Iterator start)
uint8_t GetFramingInfo () const
Get framing info.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
SequenceNumber10 GetSequenceNumber () const
Get sequence number.
virtual uint32_t GetSerializedSize (void) const
uint8_t PopExtensionBit (void)
Pop extension bit.
uint16_t PopLengthIndicator (void)
Pop length indicator.
virtual void Print (std::ostream &os) const
void PushExtensionBit (uint8_t extensionBit)
Push extension bit.
void PushLengthIndicator (uint16_t lengthIndicator)
Push length indicator.
virtual void Serialize (Buffer::Iterator start) const
void SetFramingInfo (uint8_t framingInfo)
Set framing info.
void SetSequenceNumber (SequenceNumber10 sequenceNumber)
Set sequence number.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
std::list< uint8_t > m_extensionBits
Includes extensionBit of the fixed part.
uint8_t m_framingInfo
2 bits
uint16_t m_headerLength
header length
std::list< uint16_t > m_lengthIndicators
length indicators
SequenceNumber10 m_sequenceNumber
sequence number
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The packet header for the Radio Link Control (RLC) protocol packets.
This class has fields corresponding to those in an RLC header as well as methods for serialization to and deserialization from a byte buffer. It follows 3GPP TS 36.322 Radio Link Control (RLC) protocol specification.
Definition at line 39 of file lte-rlc-header.h.
Member Enumeration Documentation
ExtensionBit_t
enum ns3::LteRlcHeader::ExtensionBit_t
ExtensionBit_t typedef.
Enumerator
DATA_FIELD_FOLLOWS
E_LI_FIELDS_FOLLOWS
Definition at line 104 of file lte-rlc-header.h.
FramingInfoFirstByte_t
enum ns3::LteRlcHeader::FramingInfoFirstByte_t
FramingInfoFirstByte_t typedef.
Enumerator
FIRST_BYTE
NO_FIRST_BYTE
Definition at line 110 of file lte-rlc-header.h.
FramingInfoLastByte_t
enum ns3::LteRlcHeader::FramingInfoLastByte_t
FramingInfoLastByte_t tyedef.
Enumerator
LAST_BYTE
NO_LAST_BYTE
Definition at line 116 of file lte-rlc-header.h.
Constructor & Destructor Documentation
LteRlcHeader()
ns3::LteRlcHeader::LteRlcHeader ()
Constructor.
Creates a null header
Definition at line 31 of file lte-rlc-header.cc.
~LteRlcHeader()
ns3::LteRlcHeader::~LteRlcHeader ()
Definition at line 38 of file lte-rlc-header.cc.
References m_framingInfo, m_headerLength, and m_sequenceNumber.
Member Function Documentation
Deserialize()
uint32_t ns3::LteRlcHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 214 of file lte-rlc-header.cc.
References DATA_FIELD_FOLLOWS, E_LI_FIELDS_FOLLOWS, GetSerializedSize(), m_extensionBits, m_framingInfo, m_headerLength, m_lengthIndicators, m_sequenceNumber, ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetFramingInfo()
uint8_t ns3::LteRlcHeader::GetFramingInfo () const
Get framing info.
Returns
framing info
Definition at line 58 of file lte-rlc-header.cc.
References m_framingInfo.
Referenced by ns3::LteRlcUm::ReassembleAndDeliver().
GetInstanceTypeId()
TypeId ns3::LteRlcHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 126 of file lte-rlc-header.cc.
References GetTypeId().
GetSequenceNumber()
SequenceNumber10 ns3::LteRlcHeader::GetSequenceNumber () const
Get sequence number.
Returns
sequence number
Definition at line 64 of file lte-rlc-header.cc.
References m_sequenceNumber.
Referenced by ns3::LteRlcUm::DoReceivePdu(), and ns3::LteRlcUm::ReassembleAndDeliver().
GetSerializedSize()
uint32_t ns3::LteRlcHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 163 of file lte-rlc-header.cc.
References m_headerLength.
Referenced by Deserialize(), and ns3::LteRlcUm::DoNotifyTxOpportunity().
GetTypeId()
TypeId ns3::LteRlcHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 115 of file lte-rlc-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
PopExtensionBit()
uint8_t ns3::LteRlcHeader::PopExtensionBit (void)
Pop extension bit.
Returns
the extension bit
Definition at line 96 of file lte-rlc-header.cc.
References m_extensionBits.
Referenced by ns3::LteRlcUm::ReassembleAndDeliver().
PopLengthIndicator()
uint16_t ns3::LteRlcHeader::PopLengthIndicator (void)
Pop length indicator.
Returns
the length indicator
Definition at line 105 of file lte-rlc-header.cc.
References m_lengthIndicators.
Referenced by ns3::LteRlcUm::ReassembleAndDeliver().
Print()
void ns3::LteRlcHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 131 of file lte-rlc-header.cc.
References m_extensionBits, m_framingInfo, m_headerLength, m_lengthIndicators, and m_sequenceNumber.
PushExtensionBit()
void ns3::LteRlcHeader::PushExtensionBit (uint8_t extensionBit)
Push extension bit.
Parameters
extensionBit the extension bit
Definition at line 71 of file lte-rlc-header.cc.
References m_extensionBits, and m_headerLength.
Referenced by ns3::LteRlcUm::DoNotifyTxOpportunity().
PushLengthIndicator()
void ns3::LteRlcHeader::PushLengthIndicator (uint16_t lengthIndicator)
Push length indicator.
Parameters
lengthIndicator the length indicator
Definition at line 89 of file lte-rlc-header.cc.
References m_lengthIndicators.
Referenced by ns3::LteRlcUm::DoNotifyTxOpportunity().
Serialize()
void ns3::LteRlcHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 168 of file lte-rlc-header.cc.
References ns3::SequenceNumber10::GetValue(), m_extensionBits, m_framingInfo, m_lengthIndicators, m_sequenceNumber, visualizer.core::start(), and ns3::Buffer::Iterator::WriteU8().
SetFramingInfo()
void ns3::LteRlcHeader::SetFramingInfo (uint8_t framingInfo)
Set framing info.
Parameters
framingInfo framing info
Definition at line 46 of file lte-rlc-header.cc.
References m_framingInfo.
Referenced by ns3::LteRlcUm::DoNotifyTxOpportunity().
SetSequenceNumber()
void ns3::LteRlcHeader::SetSequenceNumber (SequenceNumber10 sequenceNumber)
Set sequence number.
Parameters
sequenceNumber sequence number
Definition at line 52 of file lte-rlc-header.cc.
References m_sequenceNumber.
Referenced by ns3::LteRlcUm::DoNotifyTxOpportunity().
Member Data Documentation
m_extensionBits
std::list<uint8_t> ns3::LteRlcHeader::m_extensionBits private
Includes extensionBit of the fixed part.
Definition at line 138 of file lte-rlc-header.h.
Referenced by Deserialize(), PopExtensionBit(), Print(), PushExtensionBit(), and Serialize().
m_framingInfo
uint8_t ns3::LteRlcHeader::m_framingInfo private
2 bits
Definition at line 135 of file lte-rlc-header.h.
Referenced by ~LteRlcHeader(), Deserialize(), GetFramingInfo(), Print(), Serialize(), and SetFramingInfo().
m_headerLength
uint16_t ns3::LteRlcHeader::m_headerLength private
header length
Definition at line 134 of file lte-rlc-header.h.
Referenced by ~LteRlcHeader(), Deserialize(), GetSerializedSize(), Print(), and PushExtensionBit().
m_lengthIndicators
std::list<uint16_t> ns3::LteRlcHeader::m_lengthIndicators private
length indicators
Definition at line 139 of file lte-rlc-header.h.
Referenced by Deserialize(), PopLengthIndicator(), Print(), PushLengthIndicator(), and Serialize().
m_sequenceNumber
SequenceNumber10 ns3::LteRlcHeader::m_sequenceNumber private
sequence number
Definition at line 136 of file lte-rlc-header.h.
Referenced by ~LteRlcHeader(), Deserialize(), GetSequenceNumber(), Print(), Serialize(), and SetSequenceNumber().
The documentation for this class was generated from the following files:
src/lte/model/lte-rlc-header.h
src/lte/model/lte-rlc-header.cc