ns-3: ns3::ManagementMessageType Class Reference
ns3::ManagementMessageType Class Reference
WiMAX Models
#include "mac-messages.h"
Public Types
enum MessageType {
MESSAGE_TYPE_UCD = 0, MESSAGE_TYPE_DCD = 1, MESSAGE_TYPE_DL_MAP = 2, MESSAGE_TYPE_UL_MAP = 3,
MESSAGE_TYPE_RNG_REQ = 4, MESSAGE_TYPE_RNG_RSP = 5, MESSAGE_TYPE_REG_REQ = 6, MESSAGE_TYPE_REG_RSP = 7,
MESSAGE_TYPE_DSA_REQ = 11, MESSAGE_TYPE_DSA_RSP = 12, MESSAGE_TYPE_DSA_ACK = 13
}
Message type enumeration.
Public Member Functions
ManagementMessageType (uint8_t type)
Constructor.
ManagementMessageType (void)
virtual ~ManagementMessageType (void)
uint32_t Deserialize (Buffer::Iterator start)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
std::string GetName (void) const
uint32_t GetSerializedSize (void) const
uint8_t GetType (void) const
Get type field.
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetType (uint8_t type)
Set type field.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_type
type
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Mac Management messages Section 6.3.2.3 MAC Management messages page 42, Table 14 page 43
Definition at line 43 of file mac-messages.h.
Member Enumeration Documentation
MessageType
enum ns3::ManagementMessageType::MessageType
Message type enumeration.
Enumerator
MESSAGE_TYPE_UCD
MESSAGE_TYPE_DCD
MESSAGE_TYPE_DL_MAP
MESSAGE_TYPE_UL_MAP
MESSAGE_TYPE_RNG_REQ
MESSAGE_TYPE_RNG_RSP
MESSAGE_TYPE_REG_REQ
MESSAGE_TYPE_REG_RSP
MESSAGE_TYPE_DSA_REQ
MESSAGE_TYPE_DSA_RSP
MESSAGE_TYPE_DSA_ACK
Definition at line 47 of file mac-messages.h.
Constructor & Destructor Documentation
ManagementMessageType() [1/2]
ns3::ManagementMessageType::ManagementMessageType (void)
Definition at line 35 of file mac-messages.cc.
ManagementMessageType() [2/2]
ns3::ManagementMessageType::ManagementMessageType (uint8_t type)
Constructor.
Parameters
type message type
Definition at line 40 of file mac-messages.cc.
~ManagementMessageType()
ns3::ManagementMessageType::~ManagementMessageType (void) virtual
Definition at line 45 of file mac-messages.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::ManagementMessageType::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 105 of file mac-messages.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_type, ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetInstanceTypeId()
TypeId ns3::ManagementMessageType::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 80 of file mac-messages.cc.
References GetTypeId().
GetName()
std::string ns3::ManagementMessageType::GetName (void) const
Returns
the name field
Definition at line 62 of file mac-messages.cc.
GetSerializedSize()
uint32_t ns3::ManagementMessageType::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 92 of file mac-messages.cc.
GetType()
uint8_t ns3::ManagementMessageType::GetType (void) const
Get type field.
Returns
the type value
Definition at line 56 of file mac-messages.cc.
References m_type.
Referenced by ns3::BaseStationNetDevice::DoReceive(), and ns3::SubscriberStationNetDevice::DoReceive().
GetTypeId()
TypeId ns3::ManagementMessageType::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 68 of file mac-messages.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::ManagementMessageType::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 86 of file mac-messages.cc.
References m_type.
Serialize()
void ns3::ManagementMessageType::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 98 of file mac-messages.cc.
References m_type, visualizer.core::start(), and ns3::Buffer::Iterator::WriteU8().
SetType()
void ns3::ManagementMessageType::SetType (uint8_t type)
Set type field.
Parameters
type the type
Definition at line 50 of file mac-messages.cc.
References m_type.
Member Data Documentation
m_type
uint8_t ns3::ManagementMessageType::m_type private
type
Definition at line 94 of file mac-messages.h.
Referenced by Deserialize(), GetType(), Print(), Serialize(), and SetType().
The documentation for this class was generated from the following files:
src/wimax/model/mac-messages.h
src/wimax/model/mac-messages.cc