ns-3: ns3::ListPositionAllocator Class Reference
ns3::ListPositionAllocator Class Reference
Mobility
Allocate positions from a deterministic list specified by the user.
#include "position-allocator.h"
Public Member Functions
ListPositionAllocator ()
void Add (Vector v)
Add a position to the list of positions.
virtual int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
virtual Vector GetNext (void) const
uint32_t GetSize (void) const
Return the number of positions stored.
Public Member Functions inherited from ns3::PositionAllocator
PositionAllocator ()
virtual ~PositionAllocator ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type with the TypeId system.
Static Public Member Functions inherited from ns3::PositionAllocator
static TypeId GetTypeId (void)
Register this type with the TypeId system.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
std::vector< Vector >::const_iterator m_current
vector iterator
std::vector< Vector > m_positions
vector of positions
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Allocate positions from a deterministic list specified by the user.
The first call to ListPositionAllocator::GetNext will return the first element of the list, the second call, the second element, and so on.
Definition at line 71 of file position-allocator.h.
Constructor & Destructor Documentation
ListPositionAllocator()
ns3::ListPositionAllocator::ListPositionAllocator ()
Definition at line 64 of file position-allocator.cc.
Member Function Documentation
Add()
void ns3::ListPositionAllocator::Add (Vector v)
Add a position to the list of positions.
Parameters
v the position to append at the end of the list of positions to return from GetNext.
Definition at line 68 of file position-allocator.cc.
References m_current, and m_positions.
Referenced by TestInterBssConstantObssPdAlgo::AllocatePositions(), HwmpReactiveRegressionTest::CreateNodes(), WaveNetDeviceExample::CreateWaveNodes(), LteCellSelectionTestCase::DoRun(), LteRadioLinkFailureTestCase::DoRun(), LteUeMeasurementsPiecewiseTestCase1::DoRun(), LteUeMeasurementsPiecewiseTestCase2::DoRun(), LteUeMeasurementsHandoverTestCase::DoRun(), LteHandoverTargetTestCase::DoRun(), CarrierAggregationConfigTestCase::DoRun(), LteCqiGenerationTestCase::DoRun(), LteCqiGenerationDlPowerControlTestCase::DoRun(), LteStrictFrAreaTestCase::DoRun(), LteSoftFrAreaTestCase::DoRun(), LteSoftFfrAreaTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LteInterferenceHardFrTestCase::DoRun(), LteInterferenceStrictFrTestCase::DoRun(), LteInterferenceTestCase::DoRun(), LteIpv6RoutingTestCase::DoRun(), LteUeMeasurementsTestCase::DoRun(), LteUplinkOpenLoopPowerControlTestCase::DoRun(), LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun(), LteEnbAntennaTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), LteX2HandoverTestCase::DoRun(), WaypointMobilityModelViaHelper::DoRun(), SpectrumIdealPhyTestCase::DoRun(), BlockAckAggregationDisabledTest::DoRun(), PreservePacketsInAmpdus::DoRun(), Bug730TestCase::DoRun(), QosFragmentationTestCase::DoRun(), Bug2222TestCase::DoRun(), Bug2843TestCase::DoRun(), Issue169TestCase::DoRun(), Experiment::Run(), NetAnimExperiment::Run(), Issue40TestCase::RunOne(), Bug2470TestCase::RunSubtest(), StaWifiMacScanningTestCase::Setup(), and WifiInterferenceTestCase::WifiSimpleInterference().
AssignStreams()
int64_t ns3::ListPositionAllocator::AssignStreams (int64_t stream) virtual
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
This method must be implement in subclasses.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Implements ns3::PositionAllocator.
Definition at line 85 of file position-allocator.cc.
GetNext()
Vector ns3::ListPositionAllocator::GetNext (void) const virtual
Returns
the next chosen position.
This method must be implement in subclasses.
Implements ns3::PositionAllocator.
Definition at line 74 of file position-allocator.cc.
References m_current, and m_positions.
GetSize()
uint32_t ns3::ListPositionAllocator::GetSize (void) const
Return the number of positions stored.
Note that this will not change based on calling GetNext(), as the number of positions is not altered by calling GetNext ().
Returns
the number of positions stored
Definition at line 91 of file position-allocator.cc.
References m_positions.
GetTypeId()
TypeId ns3::ListPositionAllocator::GetTypeId (void) static
Register this type with the TypeId system.
Returns
the object TypeId
Definition at line 55 of file position-allocator.cc.
References ns3::TypeId::SetParent().
Member Data Documentation
m_current
std::vector<Vector>::const_iterator ns3::ListPositionAllocator::m_current mutable private
vector iterator
Definition at line 98 of file position-allocator.h.
Referenced by Add(), and GetNext().
m_positions
std::vector<Vector> ns3::ListPositionAllocator::m_positions private
vector of positions
Definition at line 97 of file position-allocator.h.
Referenced by Add(), GetNext(), and GetSize().
The documentation for this class was generated from the following files:
src/mobility/model/position-allocator.h
src/mobility/model/position-allocator.cc