ns-3: ns3::SSRecord Class Reference
ns3::SSRecord Class Reference
WiMAX Models
This class is used by the base station to store some information related to subscriber station in the cell.
#include "ss-record.h"
Public Member Functions
SSRecord (Mac48Address macAddress)
Constructor.
SSRecord (Mac48Address macAddress, Ipv4Address IPaddress)
Constructor.
SSRecord (void)
~SSRecord (void)
void AddServiceFlow (ServiceFlow *serviceFlow)
Add service flow.
void DisablePollForRanging (void)
Disable poll for ranging.
void EnablePollForRanging (void)
Enable poll for ranging function.
bool GetAreServiceFlowsAllocated (void) const
Check if service flows are allocated.
Cid GetBasicCid (void) const
Get basic CID.
DsaRsp GetDsaRsp (void) const
Get DSA response.
uint8_t GetDsaRspRetries (void) const
Get DSA response retries.
bool GetHasServiceFlowBe (void) const
Check if at least one flow has scheduling type SF_TYPE_BE.
bool GetHasServiceFlowNrtps (void) const
Check if at least one flow has scheduling type SF_TYPE_NRTPS.
bool GetHasServiceFlowRtps (void) const
Check if at least one flow has scheduling type SF_TYPE_RTPS.
bool GetHasServiceFlowUgs (void) const
Check if at least one flow has scheduling type SF_TYPE_UGS.
uint8_t GetInvitedRangRetries (void) const
Get invited range retries.
Ipv4Address GetIPAddress (void)
Get IP address.
bool GetIsBroadcastSS (void)
Get is broadcast SS.
Mac48Address GetMacAddress (void) const
Get MAC address.
WimaxPhy::ModulationType GetModulationType (void) const
Get modulation type.
bool GetPollForRanging (void) const
Get poll for ranging.
bool GetPollMeBit (void) const
Get poll ME bit.
Cid GetPrimaryCid (void) const
Get primary CID.
uint8_t GetRangingCorrectionRetries (void) const
Get ranging correction retries.
WimaxNetDevice::RangingStatus GetRangingStatus (void) const
Get ranging status.
std::vector< ServiceFlow * > GetServiceFlows (enum ServiceFlow::SchedulingType schedulingType) const
Get service flows.
uint16_t GetSfTransactionId (void) const
Get SF transaction ID.
void IncrementDsaRspRetries (void)
Increment DAS response retries.
void IncrementInvitedRangingRetries (void)
Increment invited ranging retries.
void IncrementRangingCorrectionRetries (void)
Increment ranging correction retries.
void ResetInvitedRangingRetries (void)
Reset invited ranging retries.
void ResetRangingCorrectionRetries (void)
Reset ranging correction retries.
void SetAreServiceFlowsAllocated (bool val)
Set are service flows allocated.
void SetBasicCid (Cid basicCid)
Set basic CID.
void SetDsaRsp (DsaRsp dsaRsp)
Set DSA response.
void SetDsaRspRetries (uint8_t dsaRspRetries)
Set DSA response retries.
void SetIPAddress (Ipv4Address IPaddress)
Set IP address.
void SetIsBroadcastSS (bool broadcast_enable)
Set is broadcast SS.
void SetMacAddress (Mac48Address macAddress)
Set MAC address.
void SetModulationType (WimaxPhy::ModulationType modulationType)
Set modulation type.
void SetPollMeBit (bool pollMeBit)
Set poll ME bit.
void SetPrimaryCid (Cid primaryCid)
Set primary CID.
void SetRangingStatus (WimaxNetDevice::RangingStatus rangingStatus)
Set ranging status.
void SetSfTransactionId (uint16_t sfTransactionId)
Set SF transaction ID.
Private Member Functions
void Initialize (void)
Initialize.
Private Attributes
bool m_areServiceFlowsAllocated
are service floes allowed
Cid m_basicCid
basic CID
bool m_broadcast
broadcast?
DsaRsp m_dsaRsp
DSA response.
uint8_t m_dsaRspRetries
DAS response retries.
uint8_t m_invitedRangingRetries
invited ranging retries
Ipv4Address m_IPAddress
IP address.
Mac48Address m_macAddress
MAC address.
WimaxPhy::ModulationType m_modulationType
least robust burst profile (modulation type) for this SS
bool m_pollForRanging
poll for ranging
bool m_pollMeBit
if PM (poll me) bit set for this SS
Cid m_primaryCid
primary CID
uint8_t m_rangingCorrectionRetries
ranging correction retries
WimaxNetDevice::RangingStatus m_rangingStatus
ranging status
std::vector< ServiceFlow * > * m_serviceFlows
service flows
uint16_t m_sfTransactionId
SF transaction ID.
Detailed Description
This class is used by the base station to store some information related to subscriber station in the cell.
Definition at line 43 of file ss-record.h.
Constructor & Destructor Documentation
SSRecord() [1/3]
ns3::SSRecord::SSRecord (void)
Definition at line 28 of file ss-record.cc.
References Initialize().
SSRecord() [2/3]
ns3::SSRecord::SSRecord (Mac48Address macAddress)
Constructor.
Parameters
macAddress MAC address
Definition at line 33 of file ss-record.cc.
References Initialize(), and m_macAddress.
SSRecord() [3/3]
ns3::SSRecord::SSRecord (Mac48Address macAddress, Ipv4Address IPaddress)
Constructor.
Parameters
macAddress MAC address
IPaddress IP address
Definition at line 39 of file ss-record.cc.
References Initialize(), m_IPAddress, and m_macAddress.
~SSRecord()
ns3::SSRecord::~SSRecord (void)
Definition at line 68 of file ss-record.cc.
References m_serviceFlows.
Member Function Documentation
AddServiceFlow()
void ns3::SSRecord::AddServiceFlow (ServiceFlow * serviceFlow)
Add service flow.
Parameters
serviceFlow the service flow
Definition at line 224 of file ss-record.cc.
References m_serviceFlows.
DisablePollForRanging()
void ns3::SSRecord::DisablePollForRanging (void)
Disable poll for ranging.
Definition at line 188 of file ss-record.cc.
References m_pollForRanging.
Referenced by ns3::BSLinkManager::AbortRanging(), and ns3::BSLinkManager::AcceptRanging().
EnablePollForRanging()
void ns3::SSRecord::EnablePollForRanging (void)
Enable poll for ranging function.
Definition at line 182 of file ss-record.cc.
References m_pollForRanging.
Referenced by ns3::BSLinkManager::PerformInitialRanging().
GetAreServiceFlowsAllocated()
bool ns3::SSRecord::GetAreServiceFlowsAllocated (void) const
Check if service flows are allocated.
Returns
true if service flows are allocated
Definition at line 206 of file ss-record.cc.
References m_areServiceFlowsAllocated.
Referenced by ns3::UplinkSchedulerMBQoS::Schedule(), ns3::UplinkSchedulerRtps::Schedule(), ns3::UplinkSchedulerSimple::Schedule(), and ns3::UplinkSchedulerRtps::ULSchedulerRTPSConnection().
GetBasicCid()
Cid ns3::SSRecord::GetBasicCid (void) const
Get basic CID.
Returns
the basic CID
Definition at line 92 of file ss-record.cc.
References m_basicCid.
Referenced by ns3::SSManager::DeleteSSRecord(), ns3::SSManager::GetSSRecord(), ns3::BSLinkManager::PerformInitialRanging(), ns3::UplinkSchedulerMBQoS::Schedule(), ns3::UplinkSchedulerRtps::Schedule(), ns3::UplinkSchedulerSimple::Schedule(), ns3::UplinkSchedulerRtps::ULSchedulerRTPSConnection(), and ns3::BSLinkManager::VerifyInvitedRanging().
GetDsaRsp()
DsaRsp ns3::SSRecord::GetDsaRsp (void) const
Get DSA response.
Returns
the DSA response
Definition at line 342 of file ss-record.cc.
References m_dsaRsp.
GetDsaRspRetries()
uint8_t ns3::SSRecord::GetDsaRspRetries (void) const
Get DSA response retries.
Returns
the DSA response retries
Definition at line 330 of file ss-record.cc.
References m_dsaRspRetries.
GetHasServiceFlowBe()
bool ns3::SSRecord::GetHasServiceFlowBe (void) const
Check if at least one flow has scheduling type SF_TYPE_BE.
Returns
true if at least one flow has scheduling type SF_TYPE_BE
Definition at line 294 of file ss-record.cc.
References m_serviceFlows, and ns3::ServiceFlow::SF_TYPE_BE.
Referenced by ns3::UplinkSchedulerMBQoS::Schedule().
GetHasServiceFlowNrtps()
bool ns3::SSRecord::GetHasServiceFlowNrtps (void) const
Check if at least one flow has scheduling type SF_TYPE_NRTPS.
Returns
true if at least one flow has scheduling type SF_TYPE_NRTPS
Definition at line 281 of file ss-record.cc.
References m_serviceFlows, and ns3::ServiceFlow::SF_TYPE_NRTPS.
Referenced by ns3::UplinkSchedulerMBQoS::Schedule().
GetHasServiceFlowRtps()
bool ns3::SSRecord::GetHasServiceFlowRtps (void) const
Check if at least one flow has scheduling type SF_TYPE_RTPS.
Returns
true if at least one flow has scheduling type SF_TYPE_RTPS
Definition at line 268 of file ss-record.cc.
References m_serviceFlows, and ns3::ServiceFlow::SF_TYPE_RTPS.
Referenced by ns3::UplinkSchedulerMBQoS::Schedule().
GetHasServiceFlowUgs()
bool ns3::SSRecord::GetHasServiceFlowUgs (void) const
Check if at least one flow has scheduling type SF_TYPE_UGS.
Returns
true if at least one flow has scheduling type SF_TYPE_UGS
Definition at line 255 of file ss-record.cc.
References m_serviceFlows, and ns3::ServiceFlow::SF_TYPE_UGS.
Referenced by ns3::BandwidthManager::CalculateAllocationSize(), and ns3::UplinkSchedulerMBQoS::Schedule().
GetInvitedRangRetries()
uint8_t ns3::SSRecord::GetInvitedRangRetries (void) const
Get invited range retries.
Returns
the invited range retries
Definition at line 140 of file ss-record.cc.
References m_invitedRangingRetries.
Referenced by ns3::BSLinkManager::VerifyInvitedRanging().
GetIPAddress()
Ipv4Address ns3::SSRecord::GetIPAddress (void)
Get IP address.
Returns
the IP address
Definition at line 80 of file ss-record.cc.
References m_IPAddress.
GetIsBroadcastSS()
bool ns3::SSRecord::GetIsBroadcastSS (void)
Get is broadcast SS.
Returns
the is broadcast SS flag
Definition at line 249 of file ss-record.cc.
References m_broadcast.
Referenced by ns3::UplinkSchedulerMBQoS::Schedule(), ns3::UplinkSchedulerRtps::Schedule(), ns3::UplinkSchedulerSimple::Schedule(), and ns3::UplinkSchedulerRtps::ULSchedulerRTPSConnection().
GetMacAddress()
Mac48Address ns3::SSRecord::GetMacAddress (void) const
Get MAC address.
Returns
the MAC address
Definition at line 116 of file ss-record.cc.
References m_macAddress.
Referenced by ns3::SSManager::GetMacAddress(), and ns3::UplinkSchedulerMBQoS::ProcessBandwidthRequest().
GetModulationType()
WimaxPhy::ModulationType ns3::SSRecord::GetModulationType (void) const
Get modulation type.
Returns
the modulation type
Definition at line 164 of file ss-record.cc.
References m_modulationType.
Referenced by ns3::UplinkSchedulerMBQoS::CountSymbolsJobs(), ns3::UplinkSchedulerMBQoS::Schedule(), ns3::UplinkSchedulerRtps::Schedule(), ns3::UplinkSchedulerSimple::Schedule(), ns3::UplinkSchedulerMBQoS::SetupServiceFlow(), ns3::UplinkSchedulerRtps::SetupServiceFlow(), ns3::UplinkSchedulerSimple::SetupServiceFlow(), and ns3::UplinkSchedulerRtps::ULSchedulerRTPSConnection().
GetPollForRanging()
bool ns3::SSRecord::GetPollForRanging (void) const
Get poll for ranging.
Returns
the poll for ranging flag
Definition at line 194 of file ss-record.cc.
References m_pollForRanging.
Referenced by ns3::UplinkSchedulerMBQoS::Schedule(), ns3::UplinkSchedulerRtps::Schedule(), ns3::UplinkSchedulerSimple::Schedule(), and ns3::UplinkSchedulerRtps::ULSchedulerRTPSConnection().
GetPollMeBit()
bool ns3::SSRecord::GetPollMeBit (void) const
Get poll ME bit.
Returns
the poll me bit
Definition at line 218 of file ss-record.cc.
References m_pollMeBit.
Referenced by ns3::BandwidthManager::CalculateAllocationSize().
GetPrimaryCid()
Cid ns3::SSRecord::GetPrimaryCid (void) const
Get primary CID.
Returns
the CID
Definition at line 104 of file ss-record.cc.
References m_primaryCid.
Referenced by ns3::SSManager::DeleteSSRecord(), and ns3::SSManager::GetSSRecord().
GetRangingCorrectionRetries()
uint8_t ns3::SSRecord::GetRangingCorrectionRetries (void) const
Get ranging correction retries.
Returns
the ranging correction retries
Definition at line 122 of file ss-record.cc.
References m_rangingCorrectionRetries.
Referenced by ns3::BSLinkManager::PerformInvitedRanging().
GetRangingStatus()
WimaxNetDevice::RangingStatus ns3::SSRecord::GetRangingStatus (void) const
Get ranging status.
Returns
the ranging status
Definition at line 176 of file ss-record.cc.
References m_rangingStatus.
Referenced by ns3::SSManager::IsRegistered(), ns3::UplinkSchedulerMBQoS::Schedule(), ns3::UplinkSchedulerRtps::Schedule(), ns3::UplinkSchedulerSimple::Schedule(), and ns3::UplinkSchedulerRtps::ULSchedulerRTPSConnection().
GetServiceFlows()
std::vector< ServiceFlow * > ns3::SSRecord::GetServiceFlows (enum ServiceFlow::SchedulingType schedulingType) const
Get service flows.
Parameters
schedulingType the scheduling type
Returns
the service flow
Definition at line 229 of file ss-record.cc.
References m_serviceFlows, and ns3::ServiceFlow::SF_TYPE_ALL.
Referenced by ns3::UplinkSchedulerMBQoS::CheckMinimumBandwidth(), ns3::UplinkSchedulerMBQoS::CreateUlJob(), ns3::SSManager::DeleteSSRecord(), ns3::SSManager::GetSSRecord(), ns3::UplinkSchedulerMBQoS::Schedule(), ns3::UplinkSchedulerMBQoS::ServiceBandwidthRequests(), ns3::UplinkSchedulerRtps::ServiceBandwidthRequests(), ns3::UplinkSchedulerSimple::ServiceBandwidthRequests(), ns3::UplinkSchedulerMBQoS::ServiceUnsolicitedGrants(), ns3::UplinkSchedulerRtps::ServiceUnsolicitedGrants(), ns3::UplinkSchedulerSimple::ServiceUnsolicitedGrants(), ns3::UplinkSchedulerRtps::ULSchedulerRTPSConnection(), and ns3::UplinkSchedulerMBQoS::UplinkSchedWindowTimer().
GetSfTransactionId()
uint16_t ns3::SSRecord::GetSfTransactionId (void) const
Get SF transaction ID.
Returns
the SF transaction ID
Definition at line 312 of file ss-record.cc.
References m_sfTransactionId.
IncrementDsaRspRetries()
void ns3::SSRecord::IncrementDsaRspRetries (void)
Increment DAS response retries.
Definition at line 324 of file ss-record.cc.
References m_dsaRspRetries.
IncrementInvitedRangingRetries()
void ns3::SSRecord::IncrementInvitedRangingRetries (void)
Increment invited ranging retries.
Definition at line 152 of file ss-record.cc.
References m_invitedRangingRetries.
Referenced by ns3::BSLinkManager::VerifyInvitedRanging().
IncrementRangingCorrectionRetries()
void ns3::SSRecord::IncrementRangingCorrectionRetries (void)
Increment ranging correction retries.
Definition at line 134 of file ss-record.cc.
References m_rangingCorrectionRetries.
Referenced by ns3::BSLinkManager::PerformInvitedRanging().
Initialize()
void ns3::SSRecord::Initialize (void) private
Initialize.
Definition at line 47 of file ss-record.cc.
References m_areServiceFlowsAllocated, m_basicCid, m_broadcast, m_dsaRsp, m_dsaRspRetries, m_invitedRangingRetries, m_modulationType, m_pollForRanging, m_pollMeBit, m_primaryCid, m_rangingCorrectionRetries, m_rangingStatus, m_serviceFlows, m_sfTransactionId, ns3::WimaxPhy::MODULATION_TYPE_BPSK_12, and ns3::WimaxNetDevice::RANGING_STATUS_EXPIRED.
Referenced by SSRecord().
ResetInvitedRangingRetries()
void ns3::SSRecord::ResetInvitedRangingRetries (void)
Reset invited ranging retries.
Definition at line 146 of file ss-record.cc.
References m_invitedRangingRetries.
Referenced by ns3::BSLinkManager::PerformInitialRanging(), and ns3::BSLinkManager::PerformInvitedRanging().
ResetRangingCorrectionRetries()
void ns3::SSRecord::ResetRangingCorrectionRetries (void)
Reset ranging correction retries.
Definition at line 128 of file ss-record.cc.
References m_rangingCorrectionRetries.
Referenced by ns3::BSLinkManager::PerformInitialRanging().
SetAreServiceFlowsAllocated()
void ns3::SSRecord::SetAreServiceFlowsAllocated (bool val)
Set are service flows allocated.
Parameters
val the service flows allocated flag
Definition at line 200 of file ss-record.cc.
References m_areServiceFlowsAllocated.
SetBasicCid()
void ns3::SSRecord::SetBasicCid (Cid basicCid)
Set basic CID.
Parameters
basicCid the basic CID
Definition at line 86 of file ss-record.cc.
References m_basicCid.
Referenced by ns3::ConnectionManager::AllocateManagementConnections().
SetDsaRsp()
void ns3::SSRecord::SetDsaRsp (DsaRsp dsaRsp)
Set DSA response.
Parameters
dsaRsp the DSA response
Definition at line 336 of file ss-record.cc.
References m_dsaRsp.
SetDsaRspRetries()
void ns3::SSRecord::SetDsaRspRetries (uint8_t dsaRspRetries)
Set DSA response retries.
Parameters
dsaRspRetries the DSA response retries
Definition at line 318 of file ss-record.cc.
References m_dsaRspRetries.
SetIPAddress()
void ns3::SSRecord::SetIPAddress (Ipv4Address IPaddress)
Set IP address.
Parameters
IPaddress the IP address
Definition at line 75 of file ss-record.cc.
References m_IPAddress.
SetIsBroadcastSS()
void ns3::SSRecord::SetIsBroadcastSS (bool broadcast_enable)
Set is broadcast SS.
Parameters
broadcast_enable the broadcast enable flag
Definition at line 243 of file ss-record.cc.
References m_broadcast.
SetMacAddress()
void ns3::SSRecord::SetMacAddress (Mac48Address macAddress)
Set MAC address.
Parameters
macAddress the MAC address
Definition at line 110 of file ss-record.cc.
References m_macAddress.
SetModulationType()
void ns3::SSRecord::SetModulationType (WimaxPhy::ModulationType modulationType)
Set modulation type.
Parameters
modulationType the modulation type
Definition at line 158 of file ss-record.cc.
References m_modulationType.
Referenced by ns3::BSLinkManager::PerformInitialRanging().
SetPollMeBit()
void ns3::SSRecord::SetPollMeBit (bool pollMeBit)
Set poll ME bit.
Parameters
pollMeBit the poll me bit
Definition at line 212 of file ss-record.cc.
References m_pollMeBit.
SetPrimaryCid()
void ns3::SSRecord::SetPrimaryCid (Cid primaryCid)
Set primary CID.
Parameters
primaryCid priamry CID
Definition at line 98 of file ss-record.cc.
References m_primaryCid.
Referenced by ns3::ConnectionManager::AllocateManagementConnections().
SetRangingStatus()
void ns3::SSRecord::SetRangingStatus (WimaxNetDevice::RangingStatus rangingStatus)
Set ranging status.
Parameters
rangingStatus the ranging status
Definition at line 170 of file ss-record.cc.
References m_rangingStatus.
Referenced by ns3::BSLinkManager::AbortRanging(), ns3::BSLinkManager::AcceptRanging(), and ns3::BSLinkManager::ContinueRanging().
SetSfTransactionId()
void ns3::SSRecord::SetSfTransactionId (uint16_t sfTransactionId)
Set SF transaction ID.
Parameters
sfTransactionId the SF transaction ID
Definition at line 307 of file ss-record.cc.
References m_sfTransactionId.
Member Data Documentation
m_areServiceFlowsAllocated
bool ns3::SSRecord::m_areServiceFlowsAllocated private
are service floes allowed
Definition at line 270 of file ss-record.h.
Referenced by GetAreServiceFlowsAllocated(), Initialize(), and SetAreServiceFlowsAllocated().
m_basicCid
Cid ns3::SSRecord::m_basicCid private
basic CID
Definition at line 261 of file ss-record.h.
Referenced by GetBasicCid(), Initialize(), and SetBasicCid().
m_broadcast
bool ns3::SSRecord::m_broadcast private
broadcast?
Definition at line 272 of file ss-record.h.
Referenced by GetIsBroadcastSS(), Initialize(), and SetIsBroadcastSS().
m_dsaRsp
DsaRsp ns3::SSRecord::m_dsaRsp private
DSA response.
Definition at line 279 of file ss-record.h.
Referenced by GetDsaRsp(), Initialize(), and SetDsaRsp().
m_dsaRspRetries
uint8_t ns3::SSRecord::m_dsaRspRetries private
DAS response retries.
Definition at line 278 of file ss-record.h.
Referenced by GetDsaRspRetries(), IncrementDsaRspRetries(), Initialize(), and SetDsaRspRetries().
m_invitedRangingRetries
uint8_t ns3::SSRecord::m_invitedRangingRetries private
invited ranging retries
Definition at line 265 of file ss-record.h.
Referenced by GetInvitedRangRetries(), IncrementInvitedRangingRetries(), Initialize(), and ResetInvitedRangingRetries().
m_IPAddress
Ipv4Address ns3::SSRecord::m_IPAddress private
IP address.
Definition at line 259 of file ss-record.h.
Referenced by SSRecord(), GetIPAddress(), and SetIPAddress().
m_macAddress
Mac48Address ns3::SSRecord::m_macAddress private
MAC address.
Definition at line 258 of file ss-record.h.
Referenced by SSRecord(), GetMacAddress(), and SetMacAddress().
m_modulationType
WimaxPhy::ModulationType ns3::SSRecord::m_modulationType private
least robust burst profile (modulation type) for this SS
Definition at line 267 of file ss-record.h.
Referenced by GetModulationType(), Initialize(), and SetModulationType().
m_pollForRanging
bool ns3::SSRecord::m_pollForRanging private
poll for ranging
Definition at line 269 of file ss-record.h.
Referenced by DisablePollForRanging(), EnablePollForRanging(), GetPollForRanging(), and Initialize().
m_pollMeBit
bool ns3::SSRecord::m_pollMeBit private
if PM (poll me) bit set for this SS
Definition at line 271 of file ss-record.h.
Referenced by GetPollMeBit(), Initialize(), and SetPollMeBit().
m_primaryCid
Cid ns3::SSRecord::m_primaryCid private
primary CID
Definition at line 262 of file ss-record.h.
Referenced by GetPrimaryCid(), Initialize(), and SetPrimaryCid().
m_rangingCorrectionRetries
uint8_t ns3::SSRecord::m_rangingCorrectionRetries private
ranging correction retries
Definition at line 264 of file ss-record.h.
Referenced by GetRangingCorrectionRetries(), IncrementRangingCorrectionRetries(), Initialize(), and ResetRangingCorrectionRetries().
m_rangingStatus
WimaxNetDevice::RangingStatus ns3::SSRecord::m_rangingStatus private
ranging status
Definition at line 268 of file ss-record.h.
Referenced by GetRangingStatus(), Initialize(), and SetRangingStatus().
m_serviceFlows
std::vector<ServiceFlow*>* ns3::SSRecord::m_serviceFlows private
service flows
Definition at line 274 of file ss-record.h.
Referenced by ~SSRecord(), AddServiceFlow(), GetHasServiceFlowBe(), GetHasServiceFlowNrtps(), GetHasServiceFlowRtps(), GetHasServiceFlowUgs(), GetServiceFlows(), and Initialize().
m_sfTransactionId
uint16_t ns3::SSRecord::m_sfTransactionId private
SF transaction ID.
Definition at line 277 of file ss-record.h.
Referenced by GetSfTransactionId(), Initialize(), and SetSfTransactionId().
The documentation for this class was generated from the following files:
src/wimax/model/ss-record.h
src/wimax/model/ss-record.cc