ns-3: ThreeGppChannelMatrixUpdateTest Class Reference
ThreeGppChannelMatrixUpdateTest Class Reference
Test case for the ThreeGppChannelModel class.
Public Member Functions
ThreeGppChannelMatrixUpdateTest ()
Constructor.
virtual ~ThreeGppChannelMatrixUpdateTest ()
Destructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void DoGetChannel (Ptr< ThreeGppChannelModel > channelModel, Ptr< MobilityModel > txMob, Ptr< MobilityModel > rxMob, Ptr< ThreeGppAntennaArrayModel > txAntenna, Ptr< ThreeGppAntennaArrayModel > rxAntenna, bool update)
This method is used to schedule the channel matrix computation at different time instants and to check if it correctly updated.
virtual void DoRun (void)
Build the test scenario.
Private Attributes
Ptr< const ThreeGppChannelModel::ThreeGppChannelMatrix > m_currentChannel
used by DoGetChannel to store the current channel matrix
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test case for the ThreeGppChannelModel class.
It checks if the channel realizations are correctly updated during the simulation.
Definition at line 210 of file three-gpp-channel-test-suite.cc.
Constructor & Destructor Documentation
ThreeGppChannelMatrixUpdateTest()
ThreeGppChannelMatrixUpdateTest::ThreeGppChannelMatrixUpdateTest ()
Constructor.
Definition at line 244 of file three-gpp-channel-test-suite.cc.
~ThreeGppChannelMatrixUpdateTest()
ThreeGppChannelMatrixUpdateTest::~ThreeGppChannelMatrixUpdateTest () virtual
Destructor.
Definition at line 249 of file three-gpp-channel-test-suite.cc.
Member Function Documentation
DoGetChannel()
void ThreeGppChannelMatrixUpdateTest::DoGetChannel (Ptr< ThreeGppChannelModel > channelModel, Ptr< MobilityModel > txMob, Ptr< MobilityModel > rxMob, Ptr< ThreeGppAntennaArrayModel > txAntenna, Ptr< ThreeGppAntennaArrayModel > rxAntenna, bool update) private
This method is used to schedule the channel matrix computation at different time instants and to check if it correctly updated.
Parameters
channelModel the ThreeGppChannelModel object used to generate the channel matrix
txMob the mobility model of the first node
rxMob the mobility model of the second node
txAntenna the antenna object associated to the first node
rxAntenna the antenna object associated to the second node
update whether if the channel matrix should be updated or not
Definition at line 254 of file three-gpp-channel-test-suite.cc.
References ns3::ThreeGppChannelModel::GetChannel(), m_currentChannel, ns3::Now(), and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
DoRun()
void ThreeGppChannelMatrixUpdateTest::DoRun (void) private virtual
Build the test scenario.
Implements ns3::TestCase.
Definition at line 273 of file three-gpp-channel-test-suite.cc.
References DoGetChannel(), ns3::MilliSeconds(), first::nodes, ns3::ObjectBase::SetAttribute(), ns3::SimpleNetDevice::SetNode(), and ns3::MobilityModel::SetPosition().
Member Data Documentation
m_currentChannel
Ptr<const ThreeGppChannelModel::ThreeGppChannelMatrix> ThreeGppChannelMatrixUpdateTest::m_currentChannel private
used by DoGetChannel to store the current channel matrix
Definition at line 241 of file three-gpp-channel-test-suite.cc.
Referenced by DoGetChannel().
The documentation for this class was generated from the following file:
src/spectrum/test/three-gpp-channel-test-suite.cc