ns-3: ns3::LteFrSoftAlgorithm Class Reference
ns3::LteFrSoftAlgorithm Class Reference
Soft Frequency Reuse algorithm implementation.
#include "lte-fr-soft-algorithm.h"
Public Member Functions
LteFrSoftAlgorithm ()
Creates a trivial ffr algorithm instance.
virtual ~LteFrSoftAlgorithm ()
virtual LteFfrRrcSapProvider * GetLteFfrRrcSapProvider ()
Export the "provider" part of the LteFfrRrcSap interface.
virtual LteFfrSapProvider * GetLteFfrSapProvider ()
Export the "provider" part of the LteFfrSap interface.
virtual void SetLteFfrRrcSapUser (LteFfrRrcSapUser *s)
Set the "user" part of the LteFfrRrcSap interface that this frequency reuse algorithm instance will interact with.
virtual void SetLteFfrSapUser (LteFfrSapUser *s)
Set the "user" part of the LteFfrSap interface that this frequency reuse algorithm instance will interact with.
Public Member Functions inherited from ns3::LteFfrAlgorithm
LteFfrAlgorithm ()
virtual ~LteFfrAlgorithm ()
uint16_t GetDlBandwidth () const
uint8_t GetFrCellTypeId () const
uint16_t GetUlBandwidth () const
void SetDlBandwidth (uint16_t bw)
void SetFrCellTypeId (uint8_t cellTypeId)
void SetUlBandwidth (uint16_t bw)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::LteFfrAlgorithm
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose ()
Destructor implementation.
virtual std::vector< bool > DoGetAvailableDlRbg ()
Implementation of LteFfrSapProvider::GetAvailableDlRbg.
virtual std::vector< bool > DoGetAvailableUlRbg ()
Implementation of LteFfrSapProvider::GetAvailableUlRbg.
virtual uint16_t DoGetMinContinuousUlBandwidth ()
DoGetMinContinuousUlBandwidth in number of RB.
virtual uint8_t DoGetTpc (uint16_t rnti)
DoGetTpc for UE.
virtual void DoInitialize ()
Initialize() implementation.
virtual bool DoIsDlRbgAvailableForUe (int i, uint16_t rnti)
Implementation of LteFfrSapProvider::IsDlRbgAvailableForUe.
virtual bool DoIsUlRbgAvailableForUe (int i, uint16_t rnti)
Implementation of LteFfrSapProvider::IsUlRbgAvailableForUe.
virtual void DoRecvLoadInformation (EpcX2Sap::LoadInformationParams params)
DoRecvLoadInformation.
virtual void DoReportDlCqiInfo (const struct FfMacSchedSapProvider::SchedDlCqiInfoReqParameters &params)
DoReportDlCqiInfo.
virtual void DoReportUeMeas (uint16_t rnti, LteRrcSap::MeasResults measResults)
Implementation of LteFfrRrcSapProvider::ReportUeMeas.
virtual void DoReportUlCqiInfo (const struct FfMacSchedSapProvider::SchedUlCqiInfoReqParameters &params)
DoReportUlCqiInfo.
virtual void DoReportUlCqiInfo (std::map< uint16_t, std::vector< double > > ulCqiMap)
DoReportUlCqiInfo.
virtual void Reconfigure ()
Automatic FR reconfiguration.
Protected Member Functions inherited from ns3::LteFfrAlgorithm
virtual void DoSetBandwidth (uint16_t ulBandwidth, uint16_t dlBandwidth)
Implementation of LteFfrRrcSapProvider::SetBandwidth.
virtual void DoSetCellId (uint16_t cellId)
SetCellId.
int GetRbgSize (int dlbandwidth)
Get RBG size for DL Bandwidth according to table 7.1.6.1-1 of 36.213.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
enum SubBand { AreaUnset, CellCenter, CellEdge }
SubBand enumeration.
Private Member Functions
void InitializeDownlinkRbgMaps ()
Initialize downlink RBG maps.
void InitializeUplinkRbgMaps ()
Initialize uplink RBG maps.
void SetDownlinkConfiguration (uint16_t cellId, uint8_t bandwidth)
Set downlink configuration.
void SetUplinkConfiguration (uint16_t cellId, uint8_t bandwidth)
Set uplink configuration.
Private Attributes
uint8_t m_centerAreaTpc
center area tpc
uint8_t m_centerPowerOffset
center power offset
std::vector< bool > m_dlEdgeRbgMap
DL edge RBG map.
uint8_t m_dlEdgeSubBandOffset
DL edge subband offset.
uint8_t m_dlEdgeSubBandwidth
DL edge subbandwidth.
std::vector< bool > m_dlRbgMap
DL RBG map.
uint8_t m_edgeAreaTpc
edge area tpc
uint8_t m_edgePowerOffset
edge power offset
uint8_t m_edgeSubBandThreshold
Edge subband threshold.
std::vector< uint16_t > m_edgeUes
Edge UEs.
LteFfrRrcSapProvider * m_ffrRrcSapProvider
FFR RRC SAP provider.
LteFfrRrcSapUser * m_ffrRrcSapUser
FFR RRC SAP user.
LteFfrSapProvider * m_ffrSapProvider
FFR SAP provider.
LteFfrSapUser * m_ffrSapUser
FFR SAP user.
bool m_isEdgeSubBandForCenterUe
is edge subband for center UE?
uint8_t m_measId
The expected measurement identity.
std::map< uint16_t, uint8_t > m_ues
UEs.
std::vector< bool > m_ulEdgeRbgMap
UL edge RBG map.
uint8_t m_ulEdgeSubBandOffset
UL edge subband offset.
uint8_t m_ulEdgeSubBandwidth
UL edge subbandwidth.
std::vector< bool > m_ulRbgMap
UL RBG map.
Friends
class MemberLteFfrRrcSapProvider< LteFrSoftAlgorithm >
let the forwarder class access the protected and private members
class MemberLteFfrSapProvider< LteFrSoftAlgorithm >
let the forwarder class access the protected and private members
Additional Inherited Members
Protected Attributes inherited from ns3::LteFfrAlgorithm
uint16_t m_cellId
cell ID
uint8_t m_dlBandwidth
downlink bandwidth in RBs
bool m_enabledInUplink
If true FR algorithm will also work in Uplink.
uint8_t m_frCellTypeId
FFR cell type ID for automatic configuration.
bool m_needReconfiguration
If true FR algorithm will be reconfigured.
uint8_t m_ulBandwidth
uplink bandwidth in RBs
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Soft Frequency Reuse algorithm implementation.
Definition at line 37 of file lte-fr-soft-algorithm.h.
Member Enumeration Documentation
SubBand
enum ns3::LteFrSoftAlgorithm::SubBand private
SubBand enumeration.
Enumerator
AreaUnset
CellCenter
CellEdge
Definition at line 134 of file lte-fr-soft-algorithm.h.
Constructor & Destructor Documentation
LteFrSoftAlgorithm()
ns3::LteFrSoftAlgorithm::LteFrSoftAlgorithm ()
Creates a trivial ffr algorithm instance.
Definition at line 88 of file lte-fr-soft-algorithm.cc.
References m_ffrRrcSapProvider, m_ffrSapProvider, MemberLteFfrRrcSapProvider< LteFrSoftAlgorithm >, MemberLteFfrSapProvider< LteFrSoftAlgorithm >, and NS_LOG_FUNCTION.
~LteFrSoftAlgorithm()
ns3::LteFrSoftAlgorithm::~LteFrSoftAlgorithm () virtual
Definition at line 103 of file lte-fr-soft-algorithm.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::LteFrSoftAlgorithm::DoDispose () protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::LteFfrAlgorithm.
Definition at line 110 of file lte-fr-soft-algorithm.cc.
References m_ffrRrcSapProvider, m_ffrSapProvider, and NS_LOG_FUNCTION.
DoGetAvailableDlRbg()
std::vector< bool > ns3::LteFrSoftAlgorithm::DoGetAvailableDlRbg () protected virtual
Implementation of LteFfrSapProvider::GetAvailableDlRbg.
Returns
vector of size (m_dlBandwidth/RbgSize); false indicates that RBG is free to use, true otherwise
Implements ns3::LteFfrAlgorithm.
Definition at line 328 of file lte-fr-soft-algorithm.cc.
References InitializeDownlinkRbgMaps(), m_dlRbgMap, ns3::LteFfrAlgorithm::m_needReconfiguration, NS_LOG_FUNCTION, and Reconfigure().
DoGetAvailableUlRbg()
std::vector< bool > ns3::LteFrSoftAlgorithm::DoGetAvailableUlRbg () protected virtual
Implementation of LteFfrSapProvider::GetAvailableUlRbg.
Returns
vector of size m_ulBandwidth; false indicates that RB is free to use, true otherwise
Implements ns3::LteFfrAlgorithm.
Definition at line 374 of file lte-fr-soft-algorithm.cc.
References InitializeUplinkRbgMaps(), m_ulRbgMap, and NS_LOG_FUNCTION.
DoGetMinContinuousUlBandwidth()
uint16_t ns3::LteFrSoftAlgorithm::DoGetMinContinuousUlBandwidth () protected virtual
DoGetMinContinuousUlBandwidth in number of RB.
Returns
number of RB in min continuous UL Bandwidth
Implements ns3::LteFfrAlgorithm.
Definition at line 479 of file lte-fr-soft-algorithm.cc.
References ns3::LteFfrAlgorithm::m_enabledInUplink, ns3::LteFfrAlgorithm::m_ulBandwidth, m_ulEdgeSubBandOffset, m_ulEdgeSubBandwidth, NS_LOG_FUNCTION, and NS_LOG_INFO.
DoGetTpc()
uint8_t ns3::LteFrSoftAlgorithm::DoGetTpc (uint16_t rnti) protected virtual
DoGetTpc for UE.
Parameters
rnti
Returns
TPC value
Implements ns3::LteFfrAlgorithm.
Definition at line 441 of file lte-fr-soft-algorithm.cc.
References CellCenter, CellEdge, m_centerAreaTpc, m_edgeAreaTpc, ns3::LteFfrAlgorithm::m_enabledInUplink, m_ues, and NS_LOG_FUNCTION.
DoInitialize()
void ns3::LteFrSoftAlgorithm::DoInitialize () protected virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 216 of file lte-fr-soft-algorithm.cc.
References ns3::LteFfrRrcSapUser::AddUeMeasReportConfigForFfr(), ns3::LteRrcSap::ThresholdEutra::choice, ns3::Object::DoInitialize(), ns3::LteRrcSap::ReportConfigEutra::EVENT_A1, ns3::LteRrcSap::ReportConfigEutra::eventId, ns3::LteFfrAlgorithm::m_dlBandwidth, m_ffrRrcSapUser, ns3::LteFfrAlgorithm::m_frCellTypeId, m_measId, ns3::LteFfrAlgorithm::m_ulBandwidth, ns3::LteRrcSap::ReportConfigEutra::MS120, NS_ASSERT_MSG(), NS_LOG_FUNCTION, NS_LOG_LOGIC(), ns3::LteRrcSap::ThresholdEutra::range, ns3::LteRrcSap::ReportConfigEutra::reportInterval, ns3::LteRrcSap::ReportConfigEutra::RSRQ, SetDownlinkConfiguration(), SetUplinkConfiguration(), ns3::LteRrcSap::ReportConfigEutra::threshold1, ns3::LteRrcSap::ThresholdEutra::THRESHOLD_RSRQ, and ns3::LteRrcSap::ReportConfigEutra::triggerQuantity.
DoIsDlRbgAvailableForUe()
bool ns3::LteFrSoftAlgorithm::DoIsDlRbgAvailableForUe (int rbId, uint16_t rnti) protected virtual
Implementation of LteFfrSapProvider::IsDlRbgAvailableForUe.
Parameters
rbId
rnti Radio Network Temporary Identity, an integer identifying the UE where the report originates from
Returns
true if UE can be served on i-th RB, false otherwise
Implements ns3::LteFfrAlgorithm.
Definition at line 346 of file lte-fr-soft-algorithm.cc.
References AreaUnset, CellEdge, m_dlEdgeRbgMap, m_isEdgeSubBandForCenterUe, m_ues, and NS_LOG_FUNCTION.
DoIsUlRbgAvailableForUe()
bool ns3::LteFrSoftAlgorithm::DoIsUlRbgAvailableForUe (int rbId, uint16_t rnti) protected virtual
Implementation of LteFfrSapProvider::IsUlRbgAvailableForUe.
Parameters
rbId
rnti Radio Network Temporary Identity, an integer identifying the UE where the report originates from
Returns
true if UE can be served on i-th RB, false otherwise
Implements ns3::LteFfrAlgorithm.
Definition at line 387 of file lte-fr-soft-algorithm.cc.
References AreaUnset, CellEdge, ns3::LteFfrAlgorithm::m_enabledInUplink, m_isEdgeSubBandForCenterUe, m_ues, m_ulEdgeRbgMap, and NS_LOG_FUNCTION.
DoRecvLoadInformation()
void ns3::LteFrSoftAlgorithm::DoRecvLoadInformation (EpcX2Sap::LoadInformationParams params) protected virtual
DoRecvLoadInformation.
Parameters
params
Implements ns3::LteFfrAlgorithm.
Definition at line 558 of file lte-fr-soft-algorithm.cc.
References NS_LOG_FUNCTION, and NS_LOG_WARN.
DoReportDlCqiInfo()
void ns3::LteFrSoftAlgorithm::DoReportDlCqiInfo (const struct FfMacSchedSapProvider::SchedDlCqiInfoReqParameters & params) protected virtual
DoReportDlCqiInfo.
Parameters
params
Implements ns3::LteFfrAlgorithm.
Definition at line 420 of file lte-fr-soft-algorithm.cc.
References NS_LOG_FUNCTION, and NS_LOG_WARN.
DoReportUeMeas()
void ns3::LteFrSoftAlgorithm::DoReportUeMeas (uint16_t rnti, LteRrcSap::MeasResults measResults) protected virtual
Implementation of LteFfrRrcSapProvider::ReportUeMeas.
Parameters
rnti Radio Network Temporary Identity, an integer identifying the UE where the report originates from
measResults a single report of one measurement identity
Implements ns3::LteFfrAlgorithm.
Definition at line 509 of file lte-fr-soft-algorithm.cc.
References AreaUnset, CellCenter, CellEdge, m_centerPowerOffset, m_edgePowerOffset, m_edgeSubBandThreshold, m_ffrRrcSapUser, m_measId, m_ues, ns3::LteRrcSap::MeasResults::measId, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_WARN, ns3::LteRrcSap::PdschConfigDedicated::pa, ns3::LteRrcSap::MeasResults::rsrpResult, ns3::LteRrcSap::MeasResults::rsrqResult, and ns3::LteFfrRrcSapUser::SetPdschConfigDedicated().
DoReportUlCqiInfo() [1/2]
void ns3::LteFrSoftAlgorithm::DoReportUlCqiInfo (const struct FfMacSchedSapProvider::SchedUlCqiInfoReqParameters & params) protected virtual
DoReportUlCqiInfo.
Parameters
params
Implements ns3::LteFfrAlgorithm.
Definition at line 427 of file lte-fr-soft-algorithm.cc.
References NS_LOG_FUNCTION, and NS_LOG_WARN.
DoReportUlCqiInfo() [2/2]
void ns3::LteFrSoftAlgorithm::DoReportUlCqiInfo (std::map< uint16_t, std::vector< double > > ulCqiMap) protected virtual
DoReportUlCqiInfo.
Parameters
ulCqiMap
Implements ns3::LteFfrAlgorithm.
Definition at line 434 of file lte-fr-soft-algorithm.cc.
References NS_LOG_FUNCTION, and NS_LOG_WARN.
GetLteFfrRrcSapProvider()
LteFfrRrcSapProvider * ns3::LteFrSoftAlgorithm::GetLteFfrRrcSapProvider () virtual
Export the "provider" part of the LteFfrRrcSap interface.
Returns
the reference to the "provider" part of the interface, typically to be kept by an LteEnbRrc instance
Implements ns3::LteFfrAlgorithm.
Definition at line 208 of file lte-fr-soft-algorithm.cc.
References m_ffrRrcSapProvider, and NS_LOG_FUNCTION.
GetLteFfrSapProvider()
LteFfrSapProvider * ns3::LteFrSoftAlgorithm::GetLteFfrSapProvider () virtual
Export the "provider" part of the LteFfrSap interface.
Returns
the reference to the "provider" part of the interface, typically to be kept by an Scheduler instance
Implements ns3::LteFfrAlgorithm.
Definition at line 193 of file lte-fr-soft-algorithm.cc.
References m_ffrSapProvider, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::LteFrSoftAlgorithm::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 119 of file lte-fr-soft-algorithm.cc.
References m_centerAreaTpc, m_centerPowerOffset, m_dlEdgeSubBandOffset, m_dlEdgeSubBandwidth, m_edgeAreaTpc, m_edgePowerOffset, m_edgeSubBandThreshold, m_isEdgeSubBandForCenterUe, m_ulEdgeSubBandOffset, m_ulEdgeSubBandwidth, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
InitializeDownlinkRbgMaps()
void ns3::LteFrSoftAlgorithm::InitializeDownlinkRbgMaps () private
Initialize downlink RBG maps.
Definition at line 286 of file lte-fr-soft-algorithm.cc.
References ns3::LteFfrAlgorithm::GetRbgSize(), ns3::LteFfrAlgorithm::m_dlBandwidth, m_dlEdgeRbgMap, m_dlEdgeSubBandOffset, m_dlEdgeSubBandwidth, m_dlRbgMap, and NS_ASSERT_MSG().
Referenced by DoGetAvailableDlRbg(), and Reconfigure().
InitializeUplinkRbgMaps()
void ns3::LteFrSoftAlgorithm::InitializeUplinkRbgMaps () private
Initialize uplink RBG maps.
Definition at line 308 of file lte-fr-soft-algorithm.cc.
References ns3::LteFfrAlgorithm::m_dlBandwidth, ns3::LteFfrAlgorithm::m_ulBandwidth, m_ulEdgeRbgMap, m_ulEdgeSubBandOffset, m_ulEdgeSubBandwidth, m_ulRbgMap, and NS_ASSERT_MSG().
Referenced by DoGetAvailableUlRbg(), and Reconfigure().
Reconfigure()
void ns3::LteFrSoftAlgorithm::Reconfigure () protected virtual
Automatic FR reconfiguration.
Implements ns3::LteFfrAlgorithm.
Definition at line 242 of file lte-fr-soft-algorithm.cc.
References InitializeDownlinkRbgMaps(), InitializeUplinkRbgMaps(), ns3::LteFfrAlgorithm::m_dlBandwidth, ns3::LteFfrAlgorithm::m_frCellTypeId, ns3::LteFfrAlgorithm::m_needReconfiguration, ns3::LteFfrAlgorithm::m_ulBandwidth, NS_LOG_FUNCTION, SetDownlinkConfiguration(), and SetUplinkConfiguration().
Referenced by DoGetAvailableDlRbg().
SetDownlinkConfiguration()
void ns3::LteFrSoftAlgorithm::SetDownlinkConfiguration (uint16_t cellId, uint8_t bandwidth) private
Set downlink configuration.
Parameters
cellId the cell ID
bandwidth the bandwidth
Definition at line 256 of file lte-fr-soft-algorithm.cc.
References ns3::FrSoftDownlinkDefaultConfiguration::dlEdgeSubBandOffset, ns3::FrSoftDownlinkDefaultConfiguration::dlEdgeSubBandwidth, ns3::g_frSoftDownlinkDefaultConfiguration, ns3::LteFfrAlgorithm::m_dlBandwidth, m_dlEdgeSubBandOffset, m_dlEdgeSubBandwidth, NS_LOG_FUNCTION, and ns3::NUM_DOWNLINK_CONFS().
Referenced by DoInitialize(), and Reconfigure().
SetLteFfrRrcSapUser()
void ns3::LteFrSoftAlgorithm::SetLteFfrRrcSapUser (LteFfrRrcSapUser * s) virtual
Set the "user" part of the LteFfrRrcSap interface that this frequency reuse algorithm instance will interact with.
Parameters
s a reference to the "user" part of the interface, typically a member of an LteEnbRrc instance
Implements ns3::LteFfrAlgorithm.
Definition at line 200 of file lte-fr-soft-algorithm.cc.
References m_ffrRrcSapUser, and NS_LOG_FUNCTION.
SetLteFfrSapUser()
void ns3::LteFrSoftAlgorithm::SetLteFfrSapUser (LteFfrSapUser * s) virtual
Set the "user" part of the LteFfrSap interface that this frequency reuse algorithm instance will interact with.
Parameters
s a reference to the "user" part of the interface, typically a member of an Scheduler instance
Implements ns3::LteFfrAlgorithm.
Definition at line 185 of file lte-fr-soft-algorithm.cc.
References m_ffrSapUser, and NS_LOG_FUNCTION.
SetUplinkConfiguration()
void ns3::LteFrSoftAlgorithm::SetUplinkConfiguration (uint16_t cellId, uint8_t bandwidth) private
Set uplink configuration.
Parameters
cellId the cell ID
bandwidth the bandwidth
Definition at line 271 of file lte-fr-soft-algorithm.cc.
References ns3::g_frSoftUplinkDefaultConfiguration, ns3::LteFfrAlgorithm::m_ulBandwidth, m_ulEdgeSubBandOffset, m_ulEdgeSubBandwidth, NS_LOG_FUNCTION, ns3::NUM_UPLINK_CONFS(), ns3::FrSoftUplinkDefaultConfiguration::ulEdgeSubBandOffset, and ns3::FrSoftUplinkDefaultConfiguration::ulEdgeSubBandwidth.
Referenced by DoInitialize(), and Reconfigure().
Friends And Related Function Documentation
MemberLteFfrRrcSapProvider< LteFrSoftAlgorithm >
friend class MemberLteFfrRrcSapProvider< LteFrSoftAlgorithm > friend
let the forwarder class access the protected and private members
Definition at line 58 of file lte-fr-soft-algorithm.h.
Referenced by LteFrSoftAlgorithm().
MemberLteFfrSapProvider< LteFrSoftAlgorithm >
friend class MemberLteFfrSapProvider< LteFrSoftAlgorithm > friend
let the forwarder class access the protected and private members
Definition at line 58 of file lte-fr-soft-algorithm.h.
Referenced by LteFrSoftAlgorithm().
Member Data Documentation
m_centerAreaTpc
uint8_t ns3::LteFrSoftAlgorithm::m_centerAreaTpc private
center area tpc
Definition at line 149 of file lte-fr-soft-algorithm.h.
Referenced by DoGetTpc(), and GetTypeId().
m_centerPowerOffset
uint8_t ns3::LteFrSoftAlgorithm::m_centerPowerOffset private
center power offset
Definition at line 146 of file lte-fr-soft-algorithm.h.
Referenced by DoReportUeMeas(), and GetTypeId().
m_dlEdgeRbgMap
std::vector<bool> ns3::LteFrSoftAlgorithm::m_dlEdgeRbgMap private
DL edge RBG map.
Definition at line 130 of file lte-fr-soft-algorithm.h.
Referenced by DoIsDlRbgAvailableForUe(), and InitializeDownlinkRbgMaps().
m_dlEdgeSubBandOffset
uint8_t ns3::LteFrSoftAlgorithm::m_dlEdgeSubBandOffset private
DL edge subband offset.
Definition at line 121 of file lte-fr-soft-algorithm.h.
Referenced by GetTypeId(), InitializeDownlinkRbgMaps(), and SetDownlinkConfiguration().
m_dlEdgeSubBandwidth
uint8_t ns3::LteFrSoftAlgorithm::m_dlEdgeSubBandwidth private
DL edge subbandwidth.
Definition at line 122 of file lte-fr-soft-algorithm.h.
Referenced by GetTypeId(), InitializeDownlinkRbgMaps(), and SetDownlinkConfiguration().
m_dlRbgMap
std::vector<bool> ns3::LteFrSoftAlgorithm::m_dlRbgMap private
DL RBG map.
Definition at line 127 of file lte-fr-soft-algorithm.h.
Referenced by DoGetAvailableDlRbg(), and InitializeDownlinkRbgMaps().
m_edgeAreaTpc
uint8_t ns3::LteFrSoftAlgorithm::m_edgeAreaTpc private
edge area tpc
Definition at line 150 of file lte-fr-soft-algorithm.h.
Referenced by DoGetTpc(), and GetTypeId().
m_edgePowerOffset
uint8_t ns3::LteFrSoftAlgorithm::m_edgePowerOffset private
edge power offset
Definition at line 147 of file lte-fr-soft-algorithm.h.
Referenced by DoReportUeMeas(), and GetTypeId().
m_edgeSubBandThreshold
uint8_t ns3::LteFrSoftAlgorithm::m_edgeSubBandThreshold private
Edge subband threshold.
Definition at line 144 of file lte-fr-soft-algorithm.h.
Referenced by DoReportUeMeas(), and GetTypeId().
m_edgeUes
std::vector<uint16_t> ns3::LteFrSoftAlgorithm::m_edgeUes private
Edge UEs.
Definition at line 142 of file lte-fr-soft-algorithm.h.
m_ffrRrcSapProvider
LteFfrRrcSapProvider* ns3::LteFrSoftAlgorithm::m_ffrRrcSapProvider private
FFR RRC SAP provider.
Definition at line 117 of file lte-fr-soft-algorithm.h.
Referenced by LteFrSoftAlgorithm(), DoDispose(), and GetLteFfrRrcSapProvider().
m_ffrRrcSapUser
LteFfrRrcSapUser* ns3::LteFrSoftAlgorithm::m_ffrRrcSapUser private
FFR RRC SAP user.
Definition at line 116 of file lte-fr-soft-algorithm.h.
Referenced by DoInitialize(), DoReportUeMeas(), and SetLteFfrRrcSapUser().
m_ffrSapProvider
LteFfrSapProvider* ns3::LteFrSoftAlgorithm::m_ffrSapProvider private
FFR SAP provider.
Definition at line 113 of file lte-fr-soft-algorithm.h.
Referenced by LteFrSoftAlgorithm(), DoDispose(), and GetLteFfrSapProvider().
m_ffrSapUser
LteFfrSapUser* ns3::LteFrSoftAlgorithm::m_ffrSapUser private
FFR SAP user.
Definition at line 112 of file lte-fr-soft-algorithm.h.
Referenced by SetLteFfrSapUser().
m_isEdgeSubBandForCenterUe
bool ns3::LteFrSoftAlgorithm::m_isEdgeSubBandForCenterUe private
is edge subband for center UE?
Definition at line 119 of file lte-fr-soft-algorithm.h.
Referenced by DoIsDlRbgAvailableForUe(), DoIsUlRbgAvailableForUe(), and GetTypeId().
m_measId
uint8_t ns3::LteFrSoftAlgorithm::m_measId private
The expected measurement identity.
Definition at line 153 of file lte-fr-soft-algorithm.h.
Referenced by DoInitialize(), and DoReportUeMeas().
m_ues
std::map< uint16_t, uint8_t > ns3::LteFrSoftAlgorithm::m_ues private
UEs.
Definition at line 141 of file lte-fr-soft-algorithm.h.
Referenced by DoGetTpc(), DoIsDlRbgAvailableForUe(), DoIsUlRbgAvailableForUe(), and DoReportUeMeas().
m_ulEdgeRbgMap
std::vector<bool> ns3::LteFrSoftAlgorithm::m_ulEdgeRbgMap private
UL edge RBG map.
Definition at line 131 of file lte-fr-soft-algorithm.h.
Referenced by DoIsUlRbgAvailableForUe(), and InitializeUplinkRbgMaps().
m_ulEdgeSubBandOffset
uint8_t ns3::LteFrSoftAlgorithm::m_ulEdgeSubBandOffset private
UL edge subband offset.
Definition at line 124 of file lte-fr-soft-algorithm.h.
Referenced by DoGetMinContinuousUlBandwidth(), GetTypeId(), InitializeUplinkRbgMaps(), and SetUplinkConfiguration().
m_ulEdgeSubBandwidth
uint8_t ns3::LteFrSoftAlgorithm::m_ulEdgeSubBandwidth private
UL edge subbandwidth.
Definition at line 125 of file lte-fr-soft-algorithm.h.
Referenced by DoGetMinContinuousUlBandwidth(), GetTypeId(), InitializeUplinkRbgMaps(), and SetUplinkConfiguration().
m_ulRbgMap
std::vector<bool> ns3::LteFrSoftAlgorithm::m_ulRbgMap private
UL RBG map.
Definition at line 128 of file lte-fr-soft-algorithm.h.
Referenced by DoGetAvailableUlRbg(), and InitializeUplinkRbgMaps().
The documentation for this class was generated from the following files:
src/lte/model/lte-fr-soft-algorithm.h
src/lte/model/lte-fr-soft-algorithm.cc