ns-3: RngParetoTestCase Class Reference
RngParetoTestCase Class Reference
Public Member Functions
RngParetoTestCase ()
virtual ~RngParetoTestCase ()
double ChiSquaredTest (Ptr< ParetoRandomVariable > p)
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Static Public Attributes
static const uint32_t N_BINS = 50
static const uint32_t N_MEASUREMENTS = 1000000
static const uint32_t N_RUNS = 5
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 317 of file rng-test-suite.cc.
Constructor & Destructor Documentation
RngParetoTestCase()
RngParetoTestCase::RngParetoTestCase ()
Definition at line 333 of file rng-test-suite.cc.
~RngParetoTestCase()
RngParetoTestCase::~RngParetoTestCase () virtual
Definition at line 337 of file rng-test-suite.cc.
Member Function Documentation
ChiSquaredTest()
double RngParetoTestCase::ChiSquaredTest (Ptr< ParetoRandomVariable > p)
Definition at line 341 of file rng-test-suite.cc.
References FillHistoRangeUniformly(), ns3::ParetoRandomVariable::GetValue(), max, N_BINS, and N_MEASUREMENTS.
Referenced by DoRun().
DoRun()
void RngParetoTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 392 of file rng-test-suite.cc.
References ChiSquaredTest(), N_BINS, N_RUNS, NS_TEST_ASSERT_MSG_LT, and ns3::ObjectBase::SetAttribute().
Member Data Documentation
N_BINS
const uint32_t RngParetoTestCase::N_BINS = 50 static
Definition at line 321 of file rng-test-suite.cc.
Referenced by ChiSquaredTest(), and DoRun().
N_MEASUREMENTS
const uint32_t RngParetoTestCase::N_MEASUREMENTS = 1000000 static
Definition at line 322 of file rng-test-suite.cc.
Referenced by ChiSquaredTest().
N_RUNS
const uint32_t RngParetoTestCase::N_RUNS = 5 static
Definition at line 320 of file rng-test-suite.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/core/test/rng-test-suite.cc