ns-3: BuildingsShadowingTestCase Class Reference
BuildingsShadowingTestCase Class Reference
#include "buildings-shadowing-test.h"
Public Member Functions
BuildingsShadowingTestCase (uint16_t m1, uint16_t m2, double refValue, double sigmaRef, std::string name)
TestCase.
virtual ~BuildingsShadowingTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
Ptr< MobilityModel > CreateMobilityModel (uint16_t index)
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
double m_lossRef
uint16_t m_mobilityModelIndex1
uint16_t m_mobilityModelIndex2
double m_sigmaRef
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 40 of file buildings-shadowing-test.h.
Constructor & Destructor Documentation
BuildingsShadowingTestCase()
BuildingsShadowingTestCase::BuildingsShadowingTestCase (uint16_t m1, uint16_t m2, double refValue, double sigmaRef, std::string name)
TestCase.
Definition at line 75 of file buildings-shadowing-test.cc.
~BuildingsShadowingTestCase()
BuildingsShadowingTestCase::~BuildingsShadowingTestCase () virtual
Definition at line 84 of file buildings-shadowing-test.cc.
Member Function Documentation
CreateMobilityModel()
Ptr< MobilityModel > BuildingsShadowingTestCase::CreateMobilityModel (uint16_t index) private
Definition at line 144 of file buildings-shadowing-test.cc.
References ns3::Object::AggregateObject(), ns3::MobilityBuildingInfo::MakeConsistent(), and ns3::MobilityModel::SetPosition().
Referenced by DoRun().
DoRun()
void BuildingsShadowingTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 89 of file buildings-shadowing-test.cc.
References CreateMobilityModel(), ns3::BuildingsPropagationLossModel::DoCalcRxPower(), m_lossRef, m_mobilityModelIndex1, m_mobilityModelIndex2, m_sigmaRef, NS_LOG_FUNCTION, NS_LOG_INFO, NS_TEST_ASSERT_MSG_EQ_TOL, NS_TEST_ASSERT_MSG_GT, NS_TEST_ASSERT_MSG_LT, ns3::Building::SetBoundaries(), ns3::Building::SetBuildingType(), ns3::Building::SetExtWallsType(), and ns3::Building::SetNFloors().
Member Data Documentation
m_lossRef
double BuildingsShadowingTestCase::m_lossRef private
Definition at line 52 of file buildings-shadowing-test.h.
Referenced by DoRun().
m_mobilityModelIndex1
uint16_t BuildingsShadowingTestCase::m_mobilityModelIndex1 private
Definition at line 50 of file buildings-shadowing-test.h.
Referenced by DoRun().
m_mobilityModelIndex2
uint16_t BuildingsShadowingTestCase::m_mobilityModelIndex2 private
Definition at line 51 of file buildings-shadowing-test.h.
Referenced by DoRun().
m_sigmaRef
double BuildingsShadowingTestCase::m_sigmaRef private
Definition at line 53 of file buildings-shadowing-test.h.
Referenced by DoRun().
The documentation for this class was generated from the following files:
src/buildings/test/buildings-shadowing-test.h
src/buildings/test/buildings-shadowing-test.cc