ns-3: PrioQueueDiscTestCase Class Reference
PrioQueueDiscTestCase Class Reference
Traffic-control » traffic-control module tests | Test suites
Prio Queue Disc Test Case.
Public Member Functions
PrioQueueDiscTestCase ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Prio Queue Disc Test Case.
Definition at line 148 of file prio-queue-disc-test-suite.cc.
Constructor & Destructor Documentation
PrioQueueDiscTestCase()
PrioQueueDiscTestCase::PrioQueueDiscTestCase ()
Definition at line 155 of file prio-queue-disc-test-suite.cc.
Member Function Documentation
DoRun()
void PrioQueueDiscTestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 161 of file prio-queue-disc-test-suite.cc.
References ns3::QueueDisc::AddPacketFilter(), ns3::QueueDisc::AddQueueDiscClass(), ns3::QueueDisc::Dequeue(), ns3::QueueDisc::Enqueue(), ns3::StringValue::Get(), ns3::ObjectBase::GetAttributeFailSafe(), ns3::PrioQueueDisc::GetBandForPriority(), ns3::QueueDisc::GetNQueueDiscClasses(), ns3::QueueItem::GetPacket(), ns3::QueueDisc::GetQueueDiscClass(), ns3::Packet::GetUid(), ns3::Object::Initialize(), NS_TEST_EXPECT_MSG_EQ, ns3::ObjectBase::SetAttributeFailSafe(), ns3::QueueDiscClass::SetQueueDisc(), and PrioQueueDiscTestFilter::SetReturnValue().
The documentation for this class was generated from the following file:
src/traffic-control/test/prio-queue-disc-test-suite.cc