ns-3: LenaFdBetFfMacSchedulerTestCase1 Class Reference
LenaFdBetFfMacSchedulerTestCase1 Class Reference
LTE Models » lte module tests | Test suites
This system test program creates different test cases with a single eNB and several UEs, all having the same Radio Bearer specification. In each test case, the UEs see the same SINR from the eNB; different test cases are implemented obtained by using different SINR values and different numbers of UEs. The test consists on checking that the obtained throughput performance is equal among users is consistent with the definition of blind equal throughput scheduling.
#include "lte-test-fdbet-ff-mac-scheduler.h"
Public Member Functions
LenaFdBetFfMacSchedulerTestCase1 (uint16_t nUser, double dist, double thrRefDl, double thrRefUl, bool errorModelEnabled)
Constructor.
virtual ~LenaFdBetFfMacSchedulerTestCase1 ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Static Private Member Functions
static std::string BuildNameString (uint16_t nUser, double dist)
Builds the test name string based on provided parameter values.
Private Attributes
double m_dist
distance between the nodes
bool m_errorModelEnabled
error model enabled?
uint16_t m_nUser
number of UE nodes
double m_thrRefDl
DL throughput reference.
double m_thrRefUl
UL throughput reference.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
This system test program creates different test cases with a single eNB and several UEs, all having the same Radio Bearer specification. In each test case, the UEs see the same SINR from the eNB; different test cases are implemented obtained by using different SINR values and different numbers of UEs. The test consists on checking that the obtained throughput performance is equal among users is consistent with the definition of blind equal throughput scheduling.
Definition at line 45 of file lte-test-fdbet-ff-mac-scheduler.h.
Constructor & Destructor Documentation
LenaFdBetFfMacSchedulerTestCase1()
LenaFdBetFfMacSchedulerTestCase1::LenaFdBetFfMacSchedulerTestCase1 (uint16_t nUser, double dist, double thrRefDl, double thrRefUl, bool errorModelEnabled)
Constructor.
Parameters
nUser number of UE nodes
dist distance between nodes
thrRefDl DL throughput reference
thrRefUl UL throughput reference
errorModelEnabled error model enabled?
Definition at line 190 of file lte-test-fdbet-ff-mac-scheduler.cc.
~LenaFdBetFfMacSchedulerTestCase1()
LenaFdBetFfMacSchedulerTestCase1::~LenaFdBetFfMacSchedulerTestCase1 () virtual
Definition at line 200 of file lte-test-fdbet-ff-mac-scheduler.cc.
Member Function Documentation
BuildNameString()
std::string LenaFdBetFfMacSchedulerTestCase1::BuildNameString (uint16_t nUser, double dist) static private
Builds the test name string based on provided parameter values.
Parameters
nUser number of UE nodes
dist distance between nodes
Returns
name string
Definition at line 183 of file lte-test-fdbet-ff-mac-scheduler.cc.
DoRun()
void LenaFdBetFfMacSchedulerTestCase1::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Initialize Simulation Scenario: 1 eNB and m_nUser UEs
Check that the downlink assignment is done in a "FD blind equal throughput" manner
Check that the assignment is done in a "FD blind equal throughput" manner among users with equal SINRs: the bandwidth should be distributed according to the ratio of the estimated throughput per TTI of each user; therefore equally partitioning the whole bandwidth achievable from a single users in a TTI
Check that the uplink assignment is done in a "FD blind equal throughput" manner
Check that the assignment is done in a "FD blind equal throughput" manner among users with equal SINRs: the bandwidth should be distributed according to the ratio of the estimated throughput per TTI of each user; therefore equally partitioning the whole bandwidth achievable from a single users in a TTI
Implements ns3::TestCase.
Definition at line 205 of file lte-test-fdbet-ff-mac-scheduler.cc.
References ns3::LteHelper::ActivateDataRadioBearer(), ns3::LteHelper::Attach(), ns3::NodeContainer::Create(), ns3::TestCase::CreateTempDirFilename(), ns3::LteHelper::EnableMacTraces(), ns3::LteHelper::EnableRlcTraces(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::RadioBearerStatsCalculator::GetDlRxData(), ns3::Object::GetObject(), ns3::LteEnbNetDevice::GetPhy(), ns3::LteUeNetDevice::GetPhy(), ns3::LteHelper::GetRlcStats(), ns3::RadioBearerStatsCalculator::GetUlRxData(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), m_dist, m_errorModelEnabled, m_nUser, m_thrRefDl, m_thrRefUl, third::mobility, NS_LOG_INFO, NS_TEST_ASSERT_MSG_EQ_TOL, ns3::Seconds(), ns3::ObjectBase::SetAttribute(), ns3::Config::SetDefault(), ns3::MobilityModel::SetPosition(), ns3::LteHelper::SetSchedulerAttribute(), and ns3::LteHelper::SetSchedulerType().
Member Data Documentation
m_dist
double LenaFdBetFfMacSchedulerTestCase1::m_dist private
distance between the nodes
Definition at line 71 of file lte-test-fdbet-ff-mac-scheduler.h.
Referenced by DoRun().
m_errorModelEnabled
bool LenaFdBetFfMacSchedulerTestCase1::m_errorModelEnabled private
error model enabled?
Definition at line 74 of file lte-test-fdbet-ff-mac-scheduler.h.
Referenced by DoRun().
m_nUser
uint16_t LenaFdBetFfMacSchedulerTestCase1::m_nUser private
number of UE nodes
Definition at line 70 of file lte-test-fdbet-ff-mac-scheduler.h.
Referenced by DoRun().
m_thrRefDl
double LenaFdBetFfMacSchedulerTestCase1::m_thrRefDl private
DL throughput reference.
Definition at line 72 of file lte-test-fdbet-ff-mac-scheduler.h.
Referenced by DoRun().
m_thrRefUl
double LenaFdBetFfMacSchedulerTestCase1::m_thrRefUl private
UL throughput reference.
Definition at line 73 of file lte-test-fdbet-ff-mac-scheduler.h.
Referenced by DoRun().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-fdbet-ff-mac-scheduler.h
src/lte/test/lte-test-fdbet-ff-mac-scheduler.cc