ns-3: Udp6SocketImplTest Class Reference
Udp6SocketImplTest Class Reference
Internet » internet module tests | Test suites
UDP Socket over IPv6 Test.
Public Member Functions
Udp6SocketImplTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
void ReceivePacket (Ptr< Socket > socket, Ptr< Packet > packet, const Address &from)
Receive packets (1).
void ReceivePacket2 (Ptr< Socket > socket, Ptr< Packet > packet, const Address &from)
Receive packets (2).
void ReceivePkt (Ptr< Socket > socket)
Receive packets (1).
void ReceivePkt2 (Ptr< Socket > socket)
Receive packets (2).
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void DoSendDataTo (Ptr< Socket > socket, std::string to)
Send data.
void SendDataTo (Ptr< Socket > socket, std::string to)
Send data.
Private Attributes
Ptr< Packet > m_receivedPacket
Received packet (1).
Ptr< Packet > m_receivedPacket2
Received packet (2).
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
UDP Socket over IPv6 Test.
Definition at line 487 of file udp-test.cc.
Constructor & Destructor Documentation
Udp6SocketImplTest()
Udp6SocketImplTest::Udp6SocketImplTest ()
Definition at line 535 of file udp-test.cc.
Member Function Documentation
DoRun()
void Udp6SocketImplTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 591 of file udp-test.cc.
References ns3::Ipv6::AddAddress(), ns3::Socket::Bind(), ns3::SocketFactory::CreateSocket(), ns3::Object::Dispose(), ns3::NetDeviceContainer::Get(), ns3::Ipv6::GetInterfaceForDevice(), ns3::Object::GetObject(), ns3::Packet::GetSize(), ns3::SimpleNetDeviceHelper::Install(), ns3::InternetStackHelper::Install(), m_receivedPacket, m_receivedPacket2, ns3::MakeCallback(), first::nodes, NS_TEST_EXPECT_MSG_EQ, ReceivePkt(), ReceivePkt2(), ns3::Packet::RemoveAllByteTags(), SendDataTo(), ns3::Socket::SetAllowBroadcast(), ns3::SimpleNetDeviceHelper::SetNetDevicePointToPointMode(), ns3::Socket::SetRecvCallback(), and ns3::Ipv6::SetUp().
DoSendDataTo()
void Udp6SocketImplTest::DoSendDataTo (Ptr< Socket > socket, std::string to) private
Send data.
Parameters
socket The sending socket.
to The destination address.
Definition at line 573 of file udp-test.cc.
References NS_TEST_EXPECT_MSG_EQ, and ns3::Socket::SendTo().
Referenced by SendDataTo().
ReceivePacket()
void Udp6SocketImplTest::ReceivePacket (Ptr< Socket > socket, Ptr< Packet > packet, const Address & from)
Receive packets (1).
Parameters
socket The receiving socket.
packet The received packet.
from The source address.
Definition at line 540 of file udp-test.cc.
References m_receivedPacket.
ReceivePacket2()
void Udp6SocketImplTest::ReceivePacket2 (Ptr< Socket > socket, Ptr< Packet > packet, const Address & from)
Receive packets (2).
Parameters
socket The receiving socket.
packet The received packet.
from The source address.
Definition at line 545 of file udp-test.cc.
References m_receivedPacket2.
ReceivePkt()
void Udp6SocketImplTest::ReceivePkt (Ptr< Socket > socket)
Receive packets (1).
Parameters
socket The receiving socket.
Definition at line 550 of file udp-test.cc.
References ns3::Socket::GetRxAvailable(), ns3::Packet::GetSize(), m_receivedPacket, max, NS_ASSERT, and ns3::Socket::Recv().
Referenced by DoRun().
ReceivePkt2()
void Udp6SocketImplTest::ReceivePkt2 (Ptr< Socket > socket)
Receive packets (2).
Parameters
socket The receiving socket.
Definition at line 561 of file udp-test.cc.
References ns3::Socket::GetRxAvailable(), ns3::Packet::GetSize(), m_receivedPacket2, max, NS_ASSERT, and ns3::Socket::Recv().
Referenced by DoRun().
SendDataTo()
void Udp6SocketImplTest::SendDataTo (Ptr< Socket > socket, std::string to) private
Send data.
Parameters
socket The sending socket.
to The destination address.
Definition at line 581 of file udp-test.cc.
References DoSendDataTo(), ns3::Node::GetId(), ns3::Socket::GetNode(), m_receivedPacket, m_receivedPacket2, and ns3::Seconds().
Referenced by DoRun().
Member Data Documentation
m_receivedPacket
Ptr<Packet> Udp6SocketImplTest::m_receivedPacket private
Received packet (1).
Definition at line 489 of file udp-test.cc.
Referenced by DoRun(), ReceivePacket(), ReceivePkt(), and SendDataTo().
m_receivedPacket2
Ptr<Packet> Udp6SocketImplTest::m_receivedPacket2 private
Received packet (2).
Definition at line 490 of file udp-test.cc.
Referenced by DoRun(), ReceivePacket2(), ReceivePkt2(), and SendDataTo().
The documentation for this class was generated from the following file:
src/internet/test/udp-test.cc