ns-3: SixlowpanHc1ImplTest Class Reference
SixlowpanHc1ImplTest Class Reference
6LoWPAN » 6LoWPAN module tests | Test suites
6LoWPAN HC1 Test
Public Member Functions
SixlowpanHc1ImplTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
void ReceivePacket (Ptr< Socket > socket, Ptr< Packet > packet, const Address &from)
Packet receive function.
void ReceivePkt (Ptr< Socket > socket)
Packet receive function.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void DoSendData (Ptr< Socket > socket, std::string to)
Send data function.
void SendData (Ptr< Socket > socket, std::string to)
Send data function.
Private Attributes
Ptr< Packet > m_receivedPacket
received packet
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
6LoWPAN HC1 Test
Definition at line 48 of file sixlowpan-hc1-test.cc.
Constructor & Destructor Documentation
SixlowpanHc1ImplTest()
SixlowpanHc1ImplTest::SixlowpanHc1ImplTest ()
Definition at line 88 of file sixlowpan-hc1-test.cc.
Member Function Documentation
DoRun()
void SixlowpanHc1ImplTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 130 of file sixlowpan-hc1-test.cc.
References ns3::Ipv6::AddAddress(), ns3::Node::AddDevice(), ns3::Ipv6::AddInterface(), ns3::Packet::CopyData(), ns3::SocketFactory::CreateSocket(), ns3::Object::GetObject(), ns3::Packet::GetSize(), ns3::InternetStackHelper::Install(), m_receivedPacket, ns3::MakeCallback(), NS_TEST_EXPECT_MSG_EQ, ReceivePkt(), ns3::Packet::RemoveAllByteTags(), SendData(), ns3::SimpleNetDevice::SetAddress(), ns3::Socket::SetAllowBroadcast(), ns3::ObjectBase::SetAttribute(), ns3::SimpleNetDevice::SetChannel(), ns3::InternetStackHelper::SetIpv4StackInstall(), ns3::SixLowPanNetDevice::SetNetDevice(), and ns3::Ipv6::SetUp().
DoSendData()
void SixlowpanHc1ImplTest::DoSendData (Ptr< Socket > socket, std::string to) private
Send data function.
Parameters
socket The sending socket.
to The destination.
Definition at line 110 of file sixlowpan-hc1-test.cc.
References NS_TEST_EXPECT_MSG_EQ, and ns3::Socket::SendTo().
Referenced by SendData().
ReceivePacket()
void SixlowpanHc1ImplTest::ReceivePacket (Ptr< Socket > socket, Ptr< Packet > packet, const Address & from)
Packet receive function.
Parameters
socket The receiving socket.
packet The received packet.
from The sender.
Definition at line 93 of file sixlowpan-hc1-test.cc.
References m_receivedPacket.
ReceivePkt()
void SixlowpanHc1ImplTest::ReceivePkt (Ptr< Socket > socket)
Packet receive function.
Parameters
socket The receiving socket.
Definition at line 98 of file sixlowpan-hc1-test.cc.
References ns3::Socket::GetRxAvailable(), ns3::Packet::GetSize(), m_receivedPacket, max, NS_ASSERT, and ns3::Socket::Recv().
Referenced by DoRun().
SendData()
void SixlowpanHc1ImplTest::SendData (Ptr< Socket > socket, std::string to) private
Send data function.
Parameters
socket The sending socket.
to The destination.
Definition at line 121 of file sixlowpan-hc1-test.cc.
References DoSendData(), ns3::Node::GetId(), ns3::Socket::GetNode(), m_receivedPacket, and ns3::Seconds().
Referenced by DoRun().
Member Data Documentation
m_receivedPacket
Ptr<Packet> SixlowpanHc1ImplTest::m_receivedPacket private
received packet
Definition at line 50 of file sixlowpan-hc1-test.cc.
Referenced by DoRun(), ReceivePacket(), ReceivePkt(), and SendData().
The documentation for this class was generated from the following file:
src/sixlowpan/test/sixlowpan-hc1-test.cc