ns-3: ns3::DsrHelper Class Reference
ns3::DsrHelper Class Reference
DSR Routing
DSR helper class to manage creation of DSR routing instance and to insert it on a node as a sublayer between transport and IP layers.
#include "dsr-helper.h"
Public Member Functions
DsrHelper ()
Create an DsrHelper that makes life easier for people who want to install Dsr routing to nodes.
DsrHelper (const DsrHelper &)
Construct an DsrHelper from another previously initialized instance (Copy Constructor).
~DsrHelper ()
DsrHelper * Copy (void) const
Ptr< ns3::dsr::DsrRouting > Create (Ptr< Node > node) const
void Set (std::string name, const AttributeValue &value)
Set attribute values for future instances of DSR that this helper creates.
Private Member Functions
DsrHelper & operator= (const DsrHelper &o)
Assignment operator declared private and not implemented to disallow assignment and prevent the compiler from happily inserting its own.
Private Attributes
ObjectFactory m_agentFactory
DSR factory.
Detailed Description
DSR helper class to manage creation of DSR routing instance and to insert it on a node as a sublayer between transport and IP layers.
Definition at line 52 of file dsr-helper.h.
Constructor & Destructor Documentation
DsrHelper() [1/2]
ns3::DsrHelper::DsrHelper ()
Create an DsrHelper that makes life easier for people who want to install Dsr routing to nodes.
Definition at line 50 of file dsr-helper.cc.
References m_agentFactory, NS_LOG_FUNCTION, and ns3::ObjectFactory::SetTypeId().
Referenced by Copy().
~DsrHelper()
ns3::DsrHelper::~DsrHelper ()
Definition at line 62 of file dsr-helper.cc.
References NS_LOG_FUNCTION.
DsrHelper() [2/2]
ns3::DsrHelper::DsrHelper (const DsrHelper & o)
Construct an DsrHelper from another previously initialized instance (Copy Constructor).
Definition at line 56 of file dsr-helper.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Copy()
DsrHelper * ns3::DsrHelper::Copy (void) const
Returns
pointer to clone of this DsrHelper
This method is mainly for internal use by the other helpers; clients are expected to free the dynamic memory allocated by this method
Definition at line 68 of file dsr-helper.cc.
References DsrHelper(), and NS_LOG_FUNCTION.
Referenced by ns3::DsrMainHelper::DsrMainHelper(), ns3::DsrMainHelper::Install(), ns3::DsrMainHelper::operator=(), and ns3::DsrMainHelper::SetDsrHelper().
Create()
Ptr< ns3::dsr::DsrRouting > ns3::DsrHelper::Create (Ptr< Node > node) const
Parameters
node the node on which the routing protocol will run
Returns
a newly-created L4 protocol
Definition at line 75 of file dsr-helper.cc.
References ns3::Object::AggregateObject(), ns3::ObjectFactory::Create(), ns3::Object::GetObject(), m_agentFactory, ns3::MakeCallback(), NS_LOG_FUNCTION, ns3::dsr::DsrRouting::Send(), and ns3::dsr::DsrRouting::SetDownTarget().
Referenced by ns3::DsrMainHelper::Install().
operator=()
DsrHelper& ns3::DsrHelper::operator= (const DsrHelper & o) private
Assignment operator declared private and not implemented to disallow assignment and prevent the compiler from happily inserting its own.
Parameters
o source object
Returns
DsrHelper object
Set()
void ns3::DsrHelper::Set (std::string name, const AttributeValue & value)
Set attribute values for future instances of DSR that this helper creates.
Parameters
name the node on which the routing protocol will run
value newly-created L4 protocol
Definition at line 92 of file dsr-helper.cc.
References m_agentFactory, and ns3::ObjectFactory::Set().
Member Data Documentation
m_agentFactory
ObjectFactory ns3::DsrHelper::m_agentFactory private
DSR factory.
Definition at line 92 of file dsr-helper.h.
Referenced by DsrHelper(), Create(), and Set().
The documentation for this class was generated from the following files:
src/dsr/helper/dsr-helper.h
src/dsr/helper/dsr-helper.cc