ns-3: ns3::OfdmDownlinkFramePrefix Class Reference
ns3::OfdmDownlinkFramePrefix Class Reference
OfdmDownlinkFramePrefix.
#include "ofdm-downlink-frame-prefix.h"
Public Member Functions
OfdmDownlinkFramePrefix ()
~OfdmDownlinkFramePrefix ()
void AddDlFramePrefixElement (DlFramePrefixIe dlFramePrefixElement)
Add DL frame prefix element field.
uint32_t Deserialize (Buffer::Iterator start)
Mac48Address GetBaseStationId (void) const
Get base station ID field.
uint8_t GetConfigurationChangeCount (void) const
Get configuration change count field.
std::vector< DlFramePrefixIe > GetDlFramePrefixElements (void) const
Get DL frame prefix elements.
uint32_t GetFrameNumber (void) const
Get frame number field.
uint8_t GetHcs (void) const
Get HCS field.
std::string GetName (void) const
Get name field.
uint32_t GetSerializedSize (void) const
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetBaseStationId (Mac48Address baseStationId)
Set base station ID field.
void SetConfigurationChangeCount (uint8_t configurationChangeCount)
Set configuration change count field.
void SetFrameNumber (uint32_t frameNumber)
Set frame number field.
void SetHcs (uint8_t hcs)
Set HCS field.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
virtual TypeId GetInstanceTypeId (void) const =0
Get the most derived TypeId for this Object.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Mac48Address m_baseStationId
base station ID
uint8_t m_configurationChangeCount
shall actually be only 4 LSB of the same field in DCD
std::vector< DlFramePrefixIe > m_dlFramePrefixElements
vector of dl frame prefix elements
uint32_t m_frameNumber
shall actually be only 4 LSB of the same field in OFDM DCD Channel Encodings
uint8_t m_hcs
Header Check Sequence.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
OfdmDownlinkFramePrefix.
Definition at line 137 of file ofdm-downlink-frame-prefix.h.
Constructor & Destructor Documentation
OfdmDownlinkFramePrefix()
ns3::OfdmDownlinkFramePrefix::OfdmDownlinkFramePrefix ()
Definition at line 130 of file ofdm-downlink-frame-prefix.cc.
~OfdmDownlinkFramePrefix()
ns3::OfdmDownlinkFramePrefix::~OfdmDownlinkFramePrefix ()
Definition at line 138 of file ofdm-downlink-frame-prefix.cc.
Member Function Documentation
AddDlFramePrefixElement()
void ns3::OfdmDownlinkFramePrefix::AddDlFramePrefixElement (DlFramePrefixIe dlFramePrefixElement)
Add DL frame prefix element field.
Parameters
dlFramePrefixElement the DL frane prefix element
Definition at line 174 of file ofdm-downlink-frame-prefix.cc.
References m_dlFramePrefixElements.
Referenced by Deserialize().
Deserialize()
uint32_t ns3::OfdmDownlinkFramePrefix::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 266 of file ofdm-downlink-frame-prefix.cc.
References AddDlFramePrefixElement(), ns3::DlFramePrefixIe::GetDiuc(), GetSerializedSize(), m_baseStationId, m_configurationChangeCount, m_frameNumber, m_hcs, ns3::DlFramePrefixIe::Read(), ns3::ReadFrom(), ns3::Buffer::Iterator::ReadU32(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetBaseStationId()
Mac48Address ns3::OfdmDownlinkFramePrefix::GetBaseStationId (void) const
Get base station ID field.
Returns
the base station ID
Definition at line 187 of file ofdm-downlink-frame-prefix.cc.
References m_baseStationId.
GetConfigurationChangeCount()
uint8_t ns3::OfdmDownlinkFramePrefix::GetConfigurationChangeCount (void) const
Get configuration change count field.
Returns
the configuration change count
Definition at line 199 of file ofdm-downlink-frame-prefix.cc.
References m_configurationChangeCount.
GetDlFramePrefixElements()
std::vector< DlFramePrefixIe > ns3::OfdmDownlinkFramePrefix::GetDlFramePrefixElements (void) const
Get DL frame prefix elements.
Returns
the DL frame prefix elements
Definition at line 205 of file ofdm-downlink-frame-prefix.cc.
References m_dlFramePrefixElements.
GetFrameNumber()
uint32_t ns3::OfdmDownlinkFramePrefix::GetFrameNumber (void) const
Get frame number field.
Returns
the frame number
Definition at line 193 of file ofdm-downlink-frame-prefix.cc.
References m_frameNumber.
GetHcs()
uint8_t ns3::OfdmDownlinkFramePrefix::GetHcs (void) const
Get HCS field.
Returns
the HCS
Definition at line 211 of file ofdm-downlink-frame-prefix.cc.
References m_hcs.
GetName()
std::string ns3::OfdmDownlinkFramePrefix::GetName (void) const
Get name field.
Returns
the name
Definition at line 217 of file ofdm-downlink-frame-prefix.cc.
GetSerializedSize()
uint32_t ns3::OfdmDownlinkFramePrefix::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 233 of file ofdm-downlink-frame-prefix.cc.
References ns3::DlFramePrefixIe::GetSize(), and m_dlFramePrefixElements.
Referenced by Deserialize().
GetTypeId()
TypeId ns3::OfdmDownlinkFramePrefix::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 144 of file ofdm-downlink-frame-prefix.cc.
References ns3::TypeId::SetParent().
Print()
void ns3::OfdmDownlinkFramePrefix::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 223 of file ofdm-downlink-frame-prefix.cc.
References m_baseStationId, m_configurationChangeCount, m_dlFramePrefixElements, m_frameNumber, and m_hcs.
Serialize()
void ns3::OfdmDownlinkFramePrefix::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 248 of file ofdm-downlink-frame-prefix.cc.
References m_baseStationId, m_configurationChangeCount, m_dlFramePrefixElements, m_frameNumber, m_hcs, visualizer.core::start(), ns3::DlFramePrefixIe::Write(), ns3::WriteTo(), ns3::Buffer::Iterator::WriteU32(), and ns3::Buffer::Iterator::WriteU8().
SetBaseStationId()
void ns3::OfdmDownlinkFramePrefix::SetBaseStationId (Mac48Address baseStationId)
Set base station ID field.
Parameters
baseStationId the base station ID
Definition at line 155 of file ofdm-downlink-frame-prefix.cc.
References m_baseStationId.
SetConfigurationChangeCount()
void ns3::OfdmDownlinkFramePrefix::SetConfigurationChangeCount (uint8_t configurationChangeCount)
Set configuration change count field.
Parameters
configurationChangeCount the configuration change count
Definition at line 167 of file ofdm-downlink-frame-prefix.cc.
References m_configurationChangeCount.
SetFrameNumber()
void ns3::OfdmDownlinkFramePrefix::SetFrameNumber (uint32_t frameNumber)
Set frame number field.
Parameters
frameNumber the frame number
Definition at line 161 of file ofdm-downlink-frame-prefix.cc.
References m_frameNumber.
SetHcs()
void ns3::OfdmDownlinkFramePrefix::SetHcs (uint8_t hcs)
Set HCS field.
Parameters
hcs the HCS
Definition at line 181 of file ofdm-downlink-frame-prefix.cc.
References m_hcs.
Member Data Documentation
m_baseStationId
Mac48Address ns3::OfdmDownlinkFramePrefix::m_baseStationId private
base station ID
Definition at line 211 of file ofdm-downlink-frame-prefix.h.
Referenced by Deserialize(), GetBaseStationId(), Print(), Serialize(), and SetBaseStationId().
m_configurationChangeCount
uint8_t ns3::OfdmDownlinkFramePrefix::m_configurationChangeCount private
shall actually be only 4 LSB of the same field in DCD
Definition at line 213 of file ofdm-downlink-frame-prefix.h.
Referenced by Deserialize(), GetConfigurationChangeCount(), Print(), Serialize(), and SetConfigurationChangeCount().
m_dlFramePrefixElements
std::vector<DlFramePrefixIe> ns3::OfdmDownlinkFramePrefix::m_dlFramePrefixElements private
vector of dl frame prefix elements
Definition at line 214 of file ofdm-downlink-frame-prefix.h.
Referenced by AddDlFramePrefixElement(), GetDlFramePrefixElements(), GetSerializedSize(), Print(), and Serialize().
m_frameNumber
uint32_t ns3::OfdmDownlinkFramePrefix::m_frameNumber private
shall actually be only 4 LSB of the same field in OFDM DCD Channel Encodings
Definition at line 212 of file ofdm-downlink-frame-prefix.h.
Referenced by Deserialize(), GetFrameNumber(), Print(), Serialize(), and SetFrameNumber().
m_hcs
uint8_t ns3::OfdmDownlinkFramePrefix::m_hcs private
Header Check Sequence.
Definition at line 215 of file ofdm-downlink-frame-prefix.h.
Referenced by Deserialize(), GetHcs(), Print(), Serialize(), and SetHcs().
The documentation for this class was generated from the following files:
src/wimax/model/ofdm-downlink-frame-prefix.h
src/wimax/model/ofdm-downlink-frame-prefix.cc