ns-3: TcpTestCase Class Reference
TcpTestCase Class Reference
Internet » internet module tests | Test suites
TCP Test - send string data from client to server and back.
Public Member Functions
TcpTestCase (uint32_t totalStreamSize, uint32_t sourceWriteSize, uint32_t sourceReadSize, uint32_t serverWriteSize, uint32_t serverReadSize, bool useIpv6)
Constructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
Ptr< SimpleNetDevice > AddSimpleNetDevice (Ptr< Node > node, const char *ipaddr, const char *netmask)
Add a SimpleNetDevice to a node (IPv4 version).
Ptr< SimpleNetDevice > AddSimpleNetDevice6 (Ptr< Node > node, Ipv6Address ipaddr, Ipv6Prefix prefix)
Add a SimpleNetDevice to a node (IPv6 version).
Ptr< Node > CreateInternetNode (void)
Create a node with the Internet stack (IPv4 version).
Ptr< Node > CreateInternetNode6 (void)
Create a node with the Internet stack (IPv6 version).
virtual void DoRun (void)
Implementation to actually run this TestCase.
virtual void DoTeardown (void)
Implementation to do any local setup required for this TestCase.
void ServerHandleConnectionCreated (Ptr< Socket > s, const Address &addr)
Server: Handle connection created.
void ServerHandleRecv (Ptr< Socket > sock)
Server: Receive data.
void ServerHandleSend (Ptr< Socket > sock, uint32_t available)
Server: Send data.
void SetupDefaultSim (void)
Setup the test (IPv4 version).
void SetupDefaultSim6 (void)
Setup the test (IPv6 version).
void SourceHandleRecv (Ptr< Socket > sock)
Client: Receive data.
void SourceHandleSend (Ptr< Socket > sock, uint32_t available)
Client: Send data.
Private Attributes
uint32_t m_currentServerRxBytes
Server Tx bytes.
uint32_t m_currentServerTxBytes
Server Rx bytes.
uint32_t m_currentSourceRxBytes
Client Rx bytes.
uint32_t m_currentSourceTxBytes
Client Tx bytes.
uint32_t m_serverReadSize
Server data size when receiving.
uint8_t * m_serverRxPayload
Server Rx payload.
uint32_t m_serverWriteSize
Server data size when sending.
uint32_t m_sourceReadSize
Client data size when receiving.
uint8_t * m_sourceRxPayload
Client Rx payload.
uint8_t * m_sourceTxPayload
Client Tx payload.
uint32_t m_sourceWriteSize
Client data size when sending.
uint32_t m_totalBytes
Total stream size (in bytes).
bool m_useIpv6
Use IPv6 instead of IPv4.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
TCP Test - send string data from client to server and back.
Definition at line 61 of file tcp-test.cc.
Constructor & Destructor Documentation
TcpTestCase()
TcpTestCase::TcpTestCase (uint32_t totalStreamSize, uint32_t sourceWriteSize, uint32_t sourceReadSize, uint32_t serverWriteSize, uint32_t serverReadSize, bool useIpv6)
Constructor.
Parameters
totalStreamSize Total stream size (in bytes).
sourceWriteSize Client data size when sending.
sourceReadSize Client data size when receiving.
serverWriteSize Server data size when sending.
serverReadSize Server data size when receiving.
useIpv6 Use IPv6 instead of IPv4.
Definition at line 187 of file tcp-test.cc.
Member Function Documentation
AddSimpleNetDevice()
Ptr< SimpleNetDevice > TcpTestCase::AddSimpleNetDevice (Ptr< Node > node, const char * ipaddr, const char * netmask) private
Add a SimpleNetDevice to a node (IPv4 version).
Parameters
node The target node.
ipaddr the SimpleNetDevice IPv4 address.
netmask the SimpleNetDevice IPv4 address netmask.
Returns
The new SimpleNetDevice.
Definition at line 373 of file tcp-test.cc.
References ns3::Ipv4::AddAddress(), ns3::Node::AddDevice(), ns3::Ipv4::AddInterface(), ns3::Object::GetObject(), ns3::SimpleNetDevice::SetAddress(), and ns3::Ipv4::SetUp().
Referenced by SetupDefaultSim().
AddSimpleNetDevice6()
Ptr< SimpleNetDevice > TcpTestCase::AddSimpleNetDevice6 (Ptr< Node > node, Ipv6Address ipaddr, Ipv6Prefix prefix) private
Add a SimpleNetDevice to a node (IPv6 version).
Parameters
node The target node.
ipaddr the SimpleNetDevice IPv6 address.
prefix the SimpleNetDevice IP6 address prefix.
Returns
The new SimpleNetDevice.
Definition at line 509 of file tcp-test.cc.
References ns3::Ipv6::AddAddress(), ns3::Node::AddDevice(), ns3::Ipv6::AddInterface(), ns3::Object::GetObject(), ns3::SimpleNetDevice::SetAddress(), and ns3::Ipv6::SetUp().
Referenced by SetupDefaultSim6().
CreateInternetNode()
Ptr< Node > TcpTestCase::CreateInternetNode (void) private
Create a node with the Internet stack (IPv4 version).
Returns
The new node.
Definition at line 342 of file tcp-test.cc.
References ns3::Ipv4ListRouting::AddRoutingProtocol(), ns3::Object::AggregateObject(), ns3::Ipv4L3Protocol::SetRoutingProtocol(), and ns3::ArpL3Protocol::SetTrafficControl().
Referenced by SetupDefaultSim().
CreateInternetNode6()
Ptr< Node > TcpTestCase::CreateInternetNode6 (void) private
Create a node with the Internet stack (IPv6 version).
Returns
The new node.
Definition at line 479 of file tcp-test.cc.
References ns3::Ipv6ListRouting::AddRoutingProtocol(), ns3::Object::AggregateObject(), ns3::Ipv6L3Protocol::RegisterExtensions(), ns3::Ipv6L3Protocol::RegisterOptions(), and ns3::Ipv6L3Protocol::SetRoutingProtocol().
Referenced by SetupDefaultSim6().
DoRun()
void TcpTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 210 of file tcp-test.cc.
References m_currentServerRxBytes, m_currentServerTxBytes, m_currentSourceRxBytes, m_currentSourceTxBytes, m_serverRxPayload, m_sourceRxPayload, m_sourceTxPayload, m_totalBytes, m_useIpv6, NS_TEST_EXPECT_MSG_EQ, SetupDefaultSim(), and SetupDefaultSim6().
DoTeardown()
void TcpTestCase::DoTeardown (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test teardown
Reimplemented from ns3::TestCase.
Definition at line 247 of file tcp-test.cc.
References m_serverRxPayload, m_sourceRxPayload, and m_sourceTxPayload.
ServerHandleConnectionCreated()
void TcpTestCase::ServerHandleConnectionCreated (Ptr< Socket > s, const Address & addr) private
Server: Handle connection created.
Parameters
s The socket.
addr The other party address.
Definition at line 256 of file tcp-test.cc.
References ns3::MakeCallback(), ServerHandleRecv(), ServerHandleSend(), ns3::Socket::SetRecvCallback(), and ns3::Socket::SetSendCallback().
Referenced by SetupDefaultSim(), and SetupDefaultSim6().
ServerHandleRecv()
void TcpTestCase::ServerHandleRecv (Ptr< Socket > sock) private
Server: Receive data.
Parameters
sock The socket.
Definition at line 263 of file tcp-test.cc.
References ns3::Packet::CopyData(), ns3::Socket::GetErrno(), ns3::Socket::GetRxAvailable(), ns3::Packet::GetSize(), GetString(), ns3::Socket::GetTxAvailable(), m_currentServerRxBytes, m_serverReadSize, m_serverRxPayload, m_totalBytes, min, NS_FATAL_ERROR, NS_LOG_DEBUG, NS_TEST_EXPECT_MSG_EQ, ns3::Socket::Recv(), and ServerHandleSend().
Referenced by ServerHandleConnectionCreated().
ServerHandleSend()
void TcpTestCase::ServerHandleSend (Ptr< Socket > sock, uint32_t available) private
Server: Send data.
Parameters
sock The socket.
available Unused in the test.
Definition at line 283 of file tcp-test.cc.
References ns3::Socket::Close(), GetString(), ns3::Socket::GetTxAvailable(), m_currentServerRxBytes, m_currentServerTxBytes, m_serverRxPayload, m_serverWriteSize, m_totalBytes, min, NS_LOG_DEBUG, NS_TEST_EXPECT_MSG_EQ, and ns3::Socket::Send().
Referenced by ServerHandleConnectionCreated(), and ServerHandleRecv().
SetupDefaultSim()
void TcpTestCase::SetupDefaultSim (void) private
Setup the test (IPv4 version).
Definition at line 387 of file tcp-test.cc.
References AddSimpleNetDevice(), third::channel, ns3::Socket::Connect(), CreateInternetNode(), ns3::Socket::CreateSocket(), ns3::SocketFactory::CreateSocket(), ns3::Socket::GetErrno(), ns3::Object::GetObject(), ns3::Socket::GetPeerName(), ns3::MakeCallback(), ns3::MakeNullCallback(), NS_TEST_EXPECT_MSG_EQ, port, ServerHandleConnectionCreated(), ns3::SimpleNetDevice::SetChannel(), ns3::Socket::SetRecvCallback(), ns3::Socket::SetSendCallback(), SourceHandleRecv(), and SourceHandleSend().
Referenced by DoRun().
SetupDefaultSim6()
void TcpTestCase::SetupDefaultSim6 (void) private
Setup the test (IPv6 version).
Definition at line 433 of file tcp-test.cc.
References AddSimpleNetDevice6(), third::channel, ns3::Socket::Connect(), CreateInternetNode6(), ns3::Socket::CreateSocket(), ns3::SocketFactory::CreateSocket(), ns3::Socket::GetErrno(), ns3::Object::GetObject(), ns3::Socket::GetPeerName(), ns3::MakeCallback(), ns3::MakeNullCallback(), NS_TEST_EXPECT_MSG_EQ, port, ServerHandleConnectionCreated(), ns3::SimpleNetDevice::SetChannel(), ns3::Socket::SetRecvCallback(), ns3::Socket::SetSendCallback(), SourceHandleRecv(), and SourceHandleSend().
Referenced by DoRun().
SourceHandleRecv()
void TcpTestCase::SourceHandleRecv (Ptr< Socket > sock) private
Client: Receive data.
Parameters
sock The socket.
Definition at line 319 of file tcp-test.cc.
References ns3::Socket::Close(), ns3::Packet::CopyData(), ns3::Socket::GetErrno(), ns3::Socket::GetRxAvailable(), ns3::Packet::GetSize(), GetString(), m_currentSourceRxBytes, m_sourceReadSize, m_sourceRxPayload, m_totalBytes, min, NS_FATAL_ERROR, NS_LOG_DEBUG, NS_TEST_EXPECT_MSG_EQ, and ns3::Socket::Recv().
Referenced by SetupDefaultSim(), and SetupDefaultSim6().
SourceHandleSend()
void TcpTestCase::SourceHandleSend (Ptr< Socket > sock, uint32_t available) private
Client: Send data.
Parameters
sock The socket.
available Unused in the test.
Definition at line 303 of file tcp-test.cc.
References GetString(), ns3::Socket::GetTxAvailable(), m_currentSourceTxBytes, m_sourceTxPayload, m_sourceWriteSize, m_totalBytes, min, NS_LOG_DEBUG, NS_TEST_EXPECT_MSG_EQ, and ns3::Socket::Send().
Referenced by SetupDefaultSim(), and SetupDefaultSim6().
Member Data Documentation
m_currentServerRxBytes
uint32_t TcpTestCase::m_currentServerRxBytes private
Server Tx bytes.
Definition at line 157 of file tcp-test.cc.
Referenced by DoRun(), ServerHandleRecv(), and ServerHandleSend().
m_currentServerTxBytes
uint32_t TcpTestCase::m_currentServerTxBytes private
Server Rx bytes.
Definition at line 158 of file tcp-test.cc.
Referenced by DoRun(), and ServerHandleSend().
m_currentSourceRxBytes
uint32_t TcpTestCase::m_currentSourceRxBytes private
Client Rx bytes.
Definition at line 156 of file tcp-test.cc.
Referenced by DoRun(), and SourceHandleRecv().
m_currentSourceTxBytes
uint32_t TcpTestCase::m_currentSourceTxBytes private
Client Tx bytes.
Definition at line 155 of file tcp-test.cc.
Referenced by DoRun(), and SourceHandleSend().
m_serverReadSize
uint32_t TcpTestCase::m_serverReadSize private
Server data size when receiving.
Definition at line 154 of file tcp-test.cc.
Referenced by ServerHandleRecv().
m_serverRxPayload
uint8_t* TcpTestCase::m_serverRxPayload private
Server Rx payload.
Definition at line 161 of file tcp-test.cc.
Referenced by DoRun(), DoTeardown(), ServerHandleRecv(), and ServerHandleSend().
m_serverWriteSize
uint32_t TcpTestCase::m_serverWriteSize private
Server data size when sending.
Definition at line 153 of file tcp-test.cc.
Referenced by ServerHandleSend().
m_sourceReadSize
uint32_t TcpTestCase::m_sourceReadSize private
Client data size when receiving.
Definition at line 152 of file tcp-test.cc.
Referenced by SourceHandleRecv().
m_sourceRxPayload
uint8_t* TcpTestCase::m_sourceRxPayload private
Client Rx payload.
Definition at line 160 of file tcp-test.cc.
Referenced by DoRun(), DoTeardown(), and SourceHandleRecv().
m_sourceTxPayload
uint8_t* TcpTestCase::m_sourceTxPayload private
Client Tx payload.
Definition at line 159 of file tcp-test.cc.
Referenced by DoRun(), DoTeardown(), and SourceHandleSend().
m_sourceWriteSize
uint32_t TcpTestCase::m_sourceWriteSize private
Client data size when sending.
Definition at line 151 of file tcp-test.cc.
Referenced by SourceHandleSend().
m_totalBytes
uint32_t TcpTestCase::m_totalBytes private
Total stream size (in bytes).
Definition at line 150 of file tcp-test.cc.
Referenced by DoRun(), ServerHandleRecv(), ServerHandleSend(), SourceHandleRecv(), and SourceHandleSend().
m_useIpv6
bool TcpTestCase::m_useIpv6 private
Use IPv6 instead of IPv4.
Definition at line 163 of file tcp-test.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/internet/test/tcp-test.cc