ns-3: BriteTopologyFunctionTestCase Class Reference
BriteTopologyFunctionTestCase Class Reference
Public Member Functions
BriteTopologyFunctionTestCase ()
virtual ~BriteTopologyFunctionTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 89 of file brite-test-topology.cc.
Constructor & Destructor Documentation
BriteTopologyFunctionTestCase()
BriteTopologyFunctionTestCase::BriteTopologyFunctionTestCase ()
Definition at line 100 of file brite-test-topology.cc.
~BriteTopologyFunctionTestCase()
BriteTopologyFunctionTestCase::~BriteTopologyFunctionTestCase () virtual
Definition at line 105 of file brite-test-topology.cc.
Member Function Documentation
DoRun()
void BriteTopologyFunctionTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 109 of file brite-test-topology.cc.
References ns3::NodeContainer::Add(), first::address, ns3::BriteTopologyHelper::AssignIpv4Addresses(), ns3::BriteTopologyHelper::BuildBriteTopology(), ns3::NodeContainer::Create(), ns3::ApplicationContainer::Get(), ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::BriteTopologyHelper::GetNNodesForAs(), ns3::BriteTopologyHelper::GetNodeForAs(), ns3::PointToPointHelper::Install(), ns3::OnOffHelper::Install(), ns3::PacketSinkHelper::Install(), port, ns3::Seconds(), ns3::OnOffHelper::SetAttribute(), ns3::PointToPointHelper::SetChannelAttribute(), ns3::PointToPointHelper::SetDeviceAttribute(), sink, first::stack, ns3::ApplicationContainer::Start(), and ns3::ApplicationContainer::Stop().
The documentation for this class was generated from the following file:
src/brite/test/brite-test-topology.cc