ns-3: FifoQueueDiscTestCase Class Reference
FifoQueueDiscTestCase Class Reference
Traffic-control » traffic-control module tests | Test suites
Fifo Queue Disc Test Case.
Public Member Functions
FifoQueueDiscTestCase ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void DoRunFifoTest (Ptr< FifoQueueDisc > q, uint32_t qSize, uint32_t pktSize)
Run test function.
void RunFifoTest (QueueSizeUnit mode)
Run test function.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Fifo Queue Disc Test Case.
Definition at line 97 of file fifo-queue-disc-test-suite.cc.
Constructor & Destructor Documentation
FifoQueueDiscTestCase()
FifoQueueDiscTestCase::FifoQueueDiscTestCase ()
Definition at line 117 of file fifo-queue-disc-test-suite.cc.
Member Function Documentation
DoRun()
void FifoQueueDiscTestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 246 of file fifo-queue-disc-test-suite.cc.
References ns3::BYTES, ns3::PACKETS, and RunFifoTest().
DoRunFifoTest()
void FifoQueueDiscTestCase::DoRunFifoTest (Ptr< FifoQueueDisc > q, uint32_t qSize, uint32_t pktSize) private
Run test function.
Parameters
q the queue disc
qSize the expected size of the queue disc
pktSize the packet size
Definition at line 123 of file fifo-queue-disc-test-suite.cc.
References ns3::QueueDisc::Dequeue(), ns3::QueueDisc::Enqueue(), ns3::QueueDisc::GetCurrentSize(), ns3::QueueDisc::GetMaxSize(), ns3::QueueItem::GetPacket(), ns3::Packet::GetUid(), ns3::QueueSize::GetUnit(), ns3::QueueSize::GetValue(), NS_TEST_EXPECT_MSG_EQ, and ns3::PACKETS.
Referenced by RunFifoTest().
RunFifoTest()
void FifoQueueDiscTestCase::RunFifoTest (QueueSizeUnit mode) private
Run test function.
Parameters
mode the test mode
Definition at line 161 of file fifo-queue-disc-test-suite.cc.
References ns3::QueueDisc::AddInternalQueue(), ns3::BYTES, ns3::ObjectFactory::Create(), DoRunFifoTest(), ns3::QueueDisc::GetInternalQueue(), ns3::QueueDisc::GetNInternalQueues(), ns3::Object::Initialize(), NS_TEST_EXPECT_MSG_EQ, ns3::PACKETS, ns3::ObjectFactory::Set(), ns3::ObjectBase::SetAttributeFailSafe(), and ns3::ObjectFactory::SetTypeId().
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/traffic-control/test/fifo-queue-disc-test-suite.cc