ns-3: ns3::WifiMac Class Reference
ns3::WifiMac Class Reference abstract
Wifi Models
base class for all MAC-level wifi objects.
#include "wifi-mac.h"
Public Member Functions
void ConfigureStandard (WifiPhyStandard standard)
virtual void DoDispose ()
Destructor implementation.
virtual void Enqueue (Ptr< Packet > packet, Mac48Address to)=0
virtual void Enqueue (Ptr< Packet > packet, Mac48Address to, Mac48Address from)=0
virtual Time GetAckTimeout (void) const =0
virtual Mac48Address GetAddress (void) const =0
virtual Time GetBasicBlockAckTimeout (void) const =0
virtual Mac48Address GetBssid (void) const =0
virtual Time GetCompressedBlockAckTimeout (void) const =0
Ptr< NetDevice > GetDevice (void) const
Return the device this PHY is associated with.
virtual Time GetEifsNoDifs (void) const =0
Ptr< HeConfiguration > GetHeConfiguration (void) const
Ptr< HtConfiguration > GetHtConfiguration (void) const
virtual Time GetPifs (void) const =0
virtual Time GetRifs (void) const =0
virtual bool GetShortSlotTimeSupported (void) const =0
virtual Time GetSifs (void) const =0
virtual Time GetSlot (void) const =0
virtual Ssid GetSsid (void) const =0
Ptr< VhtConfiguration > GetVhtConfiguration (void) const
virtual Ptr< WifiPhy > GetWifiPhy (void) const =0
virtual Ptr< WifiRemoteStationManager > GetWifiRemoteStationManager (void) const =0
void NotifyPromiscRx (Ptr< const Packet > packet)
void NotifyRx (Ptr< const Packet > packet)
void NotifyRxDrop (Ptr< const Packet > packet)
void NotifyTx (Ptr< const Packet > packet)
void NotifyTxDrop (Ptr< const Packet > packet)
virtual void ResetWifiPhy (void)=0
Remove currently attached WifiPhy device from this MAC.
virtual void SetAckTimeout (Time ackTimeout)=0
virtual void SetAddress (Mac48Address address)=0
virtual void SetBasicBlockAckTimeout (Time blockAckTimeout)=0
virtual void SetCompressedBlockAckTimeout (Time blockAckTimeout)=0
void SetDevice (const Ptr< NetDevice > device)
Sets the device this PHY is associated with.
virtual void SetEifsNoDifs (Time eifsNoDifs)=0
virtual void SetForwardUpCallback (Callback< void, Ptr< const Packet >, Mac48Address, Mac48Address > upCallback)=0
virtual void SetLinkDownCallback (Callback< void > linkDown)=0
virtual void SetLinkUpCallback (Callback< void > linkUp)=0
void SetMaxPropagationDelay (Time delay)
virtual void SetPifs (Time pifs)=0
virtual void SetPromisc (void)=0
Sets the interface in promiscuous mode.
virtual void SetRifs (Time rifs)=0
virtual void SetShortSlotTimeSupported (bool enable)=0
Enable or disable short slot time feature.
virtual void SetSifs (Time sifs)=0
virtual void SetSlot (Time slotTime)=0
virtual void SetSsid (Ssid ssid)=0
virtual void SetWifiPhy (Ptr< WifiPhy > phy)=0
virtual void SetWifiRemoteStationManager (Ptr< WifiRemoteStationManager > stationManager)=0
virtual bool SupportsSendFrom (void) const =0
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
void ConfigureDcf (Ptr< Txop > dcf, uint32_t cwmin, uint32_t cwmax, bool isDsss, AcIndex ac)
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void Configure80211_10Mhz (void)
This method sets 802.11 with 10 MHz channel spacing standards-compliant defaults for following attributes: SIFS, Slot, EifsNoDifs, PIFS, CtsTimeout, and AckTimeout.
void Configure80211_5Mhz ()
This method sets 802.11 with 5 MHz channel spacing standards-compliant defaults for following attributes: SIFS, Slot, EifsNoDifs, PIFS, CtsTimeout, and AckTimeout.
void Configure80211a (void)
This method sets 802.11a standards-compliant defaults for following attributes: SIFS, Slot, EifsNoDifs, PIFS, CtsTimeout, and AckTimeout.
void Configure80211ac (void)
This method sets 802.11ac standards-compliant defaults for following attributes: SIFS, Slot, EifsNoDifs, PIFS, CtsTimeout, and AckTimeout.
void Configure80211ax_2_4Ghz (void)
This method sets 802.11ax 2.4 GHz standards-compliant defaults for following attributes: SIFS, Slot, EifsNoDifs, PIFS, CtsTimeout, and AckTimeout.
void Configure80211ax_5Ghz (void)
This method sets 802.11ax 5 GHz standards-compliant defaults for following attributes: SIFS, Slot, EifsNoDifs, PIFS, CtsTimeout, and AckTimeout.
void Configure80211b (void)
This method sets 802.11b standards-compliant defaults for following attributes: SIFS, Slot, EifsNoDifs, PIFS, CtsTimeout, and AckTimeout.
void Configure80211g (void)
This method sets 802.11g standards-compliant defaults for following attributes: SIFS, Slot, EifsNoDifs, PIFS, CtsTimeout, and AckTimeout.
void Configure80211n_2_4Ghz (void)
This method sets 802.11n 2.4 GHz standards-compliant defaults for following attributes: SIFS, RIFS, Slot, EifsNoDifs, PIFS, CtsTimeout, and AckTimeout.
void Configure80211n_5Ghz (void)
This method sets 802.11n 5 GHz standards-compliant defaults for following attributes: SIFS, RIFS, Slot, EifsNoDifs, PIFS, CtsTimeout, and AckTimeout.
virtual void FinishConfigureStandard (WifiPhyStandard standard)=0
Static Private Member Functions
static Time GetDefaultBasicBlockAckDelay (void)
Return the default basic BlockAck delay.
static Time GetDefaultBasicBlockAckTimeout (void)
Return the default basic BlockAck timeout.
static Time GetDefaultCompressedBlockAckDelay (void)
Return the default compressed BlockAck delay.
static Time GetDefaultCompressedBlockAckTimeout (void)
Return the default compressed BlockAck timeout.
static Time GetDefaultCtsAckDelay (void)
static Time GetDefaultCtsAckTimeout (void)
static Time GetDefaultEifsNoDifs (void)
static Time GetDefaultMaxPropagationDelay (void)
static Time GetDefaultRifs (void)
static Time GetDefaultSifs (void)
static Time GetDefaultSlot (void)
Private Attributes
Ptr< NetDevice > m_device
Pointer to the device.
TracedCallback< Ptr< const Packet > > m_macPromiscRxTrace
The trace source fired for packets successfully received by the device immediately before being forwarded up to higher layers (at the L2/L3 transition).
TracedCallback< Ptr< const Packet > > m_macRxDropTrace
The trace source fired when packets coming into the "top" of the device are dropped at the MAC layer during reception.
TracedCallback< Ptr< const Packet > > m_macRxTrace
The trace source fired for packets successfully received by the device immediately before being forwarded up to higher layers (at the L2/L3 transition).
TracedCallback< Ptr< const Packet > > m_macTxDropTrace
The trace source fired when packets coming into the "top" of the device are dropped at the MAC layer during transmission.
TracedCallback< Ptr< const Packet > > m_macTxTrace
The trace source fired when packets come into the "top" of the device at the L3/L2 transition, before being queued for transmission.
Time m_maxPropagationDelay
maximum propagation delay
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
base class for all MAC-level wifi objects.
This class encapsulates all the low-level MAC functionality DCA, EDCA, etc) and all the high-level MAC functionality (association/disassociation state machines).
Definition at line 46 of file wifi-mac.h.
Member Function Documentation
Configure80211_10Mhz()
void ns3::WifiMac::Configure80211_10Mhz (void) private
This method sets 802.11 with 10 MHz channel spacing standards-compliant defaults for following attributes: SIFS, Slot, EifsNoDifs, PIFS, CtsTimeout, and AckTimeout.
Definition at line 349 of file wifi-mac.cc.
References GetDefaultMaxPropagationDelay(), ns3::MicroSeconds(), NS_LOG_FUNCTION, SetAckTimeout(), SetEifsNoDifs(), SetPifs(), SetSifs(), and SetSlot().
Referenced by ConfigureStandard().
Configure80211_5Mhz()
void ns3::WifiMac::Configure80211_5Mhz () private
This method sets 802.11 with 5 MHz channel spacing standards-compliant defaults for following attributes: SIFS, Slot, EifsNoDifs, PIFS, CtsTimeout, and AckTimeout.
Definition at line 360 of file wifi-mac.cc.
References GetDefaultMaxPropagationDelay(), ns3::MicroSeconds(), NS_LOG_FUNCTION, SetAckTimeout(), SetEifsNoDifs(), SetPifs(), SetSifs(), and SetSlot().
Referenced by ConfigureStandard().
Configure80211a()
void ns3::WifiMac::Configure80211a (void) private
This method sets 802.11a standards-compliant defaults for following attributes: SIFS, Slot, EifsNoDifs, PIFS, CtsTimeout, and AckTimeout.
Definition at line 312 of file wifi-mac.cc.
References GetDefaultMaxPropagationDelay(), ns3::MicroSeconds(), NS_LOG_FUNCTION, SetAckTimeout(), SetEifsNoDifs(), SetPifs(), SetSifs(), and SetSlot().
Referenced by Configure80211n_5Ghz(), and ConfigureStandard().
Configure80211ac()
void ns3::WifiMac::Configure80211ac (void) private
This method sets 802.11ac standards-compliant defaults for following attributes: SIFS, Slot, EifsNoDifs, PIFS, CtsTimeout, and AckTimeout.
Definition at line 390 of file wifi-mac.cc.
References Configure80211n_5Ghz(), and NS_LOG_FUNCTION.
Referenced by Configure80211ax_5Ghz(), and ConfigureStandard().
Configure80211ax_2_4Ghz()
void ns3::WifiMac::Configure80211ax_2_4Ghz (void) private
This method sets 802.11ax 2.4 GHz standards-compliant defaults for following attributes: SIFS, Slot, EifsNoDifs, PIFS, CtsTimeout, and AckTimeout.
There is no support for short slot time.
Definition at line 397 of file wifi-mac.cc.
References Configure80211n_2_4Ghz(), and NS_LOG_FUNCTION.
Referenced by ConfigureStandard().
Configure80211ax_5Ghz()
void ns3::WifiMac::Configure80211ax_5Ghz (void) private
This method sets 802.11ax 5 GHz standards-compliant defaults for following attributes: SIFS, Slot, EifsNoDifs, PIFS, CtsTimeout, and AckTimeout.
Definition at line 404 of file wifi-mac.cc.
References Configure80211ac(), GetDefaultMaxPropagationDelay(), GetSifs(), GetSlot(), ns3::MicroSeconds(), NS_LOG_FUNCTION, and SetCompressedBlockAckTimeout().
Referenced by ConfigureStandard().
Configure80211b()
void ns3::WifiMac::Configure80211b (void) private
This method sets 802.11b standards-compliant defaults for following attributes: SIFS, Slot, EifsNoDifs, PIFS, CtsTimeout, and AckTimeout.
Definition at line 323 of file wifi-mac.cc.
References GetDefaultMaxPropagationDelay(), ns3::MicroSeconds(), NS_LOG_FUNCTION, SetAckTimeout(), SetEifsNoDifs(), SetPifs(), SetSifs(), and SetSlot().
Referenced by ConfigureStandard().
Configure80211g()
void ns3::WifiMac::Configure80211g (void) private
This method sets 802.11g standards-compliant defaults for following attributes: SIFS, Slot, EifsNoDifs, PIFS, CtsTimeout, and AckTimeout.
There is no support for short slot time.
Definition at line 334 of file wifi-mac.cc.
References GetDefaultMaxPropagationDelay(), ns3::MicroSeconds(), NS_LOG_FUNCTION, SetAckTimeout(), SetEifsNoDifs(), SetPifs(), SetSifs(), and SetSlot().
Referenced by Configure80211n_2_4Ghz(), and ConfigureStandard().
Configure80211n_2_4Ghz()
void ns3::WifiMac::Configure80211n_2_4Ghz (void) private
This method sets 802.11n 2.4 GHz standards-compliant defaults for following attributes: SIFS, RIFS, Slot, EifsNoDifs, PIFS, CtsTimeout, and AckTimeout.
There is no support for short slot time.
Definition at line 371 of file wifi-mac.cc.
References Configure80211g(), GetDefaultBasicBlockAckDelay(), GetDefaultMaxPropagationDelay(), GetSifs(), GetSlot(), ns3::MicroSeconds(), NS_LOG_FUNCTION, SetBasicBlockAckTimeout(), SetCompressedBlockAckTimeout(), and SetRifs().
Referenced by Configure80211ax_2_4Ghz(), and ConfigureStandard().
Configure80211n_5Ghz()
void ns3::WifiMac::Configure80211n_5Ghz (void) private
This method sets 802.11n 5 GHz standards-compliant defaults for following attributes: SIFS, RIFS, Slot, EifsNoDifs, PIFS, CtsTimeout, and AckTimeout.
Definition at line 380 of file wifi-mac.cc.
References Configure80211a(), GetDefaultBasicBlockAckDelay(), GetDefaultCompressedBlockAckDelay(), GetDefaultMaxPropagationDelay(), GetSifs(), GetSlot(), ns3::MicroSeconds(), NS_LOG_FUNCTION, SetBasicBlockAckTimeout(), SetCompressedBlockAckTimeout(), and SetRifs().
Referenced by Configure80211ac(), and ConfigureStandard().
ConfigureDcf()
void ns3::WifiMac::ConfigureDcf (Ptr< Txop > dcf, uint32_t cwmin, uint32_t cwmax, bool isDsss, AcIndex ac) protected
Parameters
dcf the DCF to be configured
cwmin the minimum contention window for the DCF
cwmax the maximum contention window for the DCF
isDsss flag to indicate whether PHY is DSSS or HR/DSSS
ac the access category for the DCF
Configure the DCF with appropriate values depending on the given access category.
Definition at line 412 of file wifi-mac.cc.
References ns3::AC_BE, ns3::AC_BE_NQOS, ns3::AC_BK, ns3::AC_UNDEF, ns3::AC_VI, ns3::AC_VO, ns3::MicroSeconds(), NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::Txop::SetAifsn(), ns3::Txop::SetMaxCw(), ns3::Txop::SetMinCw(), and ns3::Txop::SetTxopLimit().
Referenced by ns3::RegularWifiMac::ConfigureContentionWindow().
ConfigureStandard()
void ns3::WifiMac::ConfigureStandard (WifiPhyStandard standard)
Parameters
standard the wifi standard to be configured
This method sets standards-compliant defaults for WifiMac parameters such as SIFS time, slot time, timeout values, etc., based on the standard selected.
See also
WifiMac::Configure80211a
WifiMac::Configure80211b
WifiMac::Configure80211g
WifiMac::Configure80211_10Mhz
WifiMac::Configure80211_5Mhz
WifiMac::Configure80211n_2_4Ghz
WifiMac::Configure80211n_5Ghz
WifiMac::Configure80211ac
WifiMac::Configure80211ax_2_4Ghz
WifiMac::Configure80211ax_5Ghz
Definition at line 265 of file wifi-mac.cc.
References Configure80211_10Mhz(), Configure80211_5Mhz(), Configure80211a(), Configure80211ac(), Configure80211ax_2_4Ghz(), Configure80211ax_5Ghz(), Configure80211b(), Configure80211g(), Configure80211n_2_4Ghz(), Configure80211n_5Ghz(), FinishConfigureStandard(), NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::WIFI_PHY_STANDARD_80211_10MHZ, ns3::WIFI_PHY_STANDARD_80211_5MHZ, ns3::WIFI_PHY_STANDARD_80211a, ns3::WIFI_PHY_STANDARD_80211ac, ns3::WIFI_PHY_STANDARD_80211ax_2_4GHZ, ns3::WIFI_PHY_STANDARD_80211ax_5GHZ, ns3::WIFI_PHY_STANDARD_80211b, ns3::WIFI_PHY_STANDARD_80211g, ns3::WIFI_PHY_STANDARD_80211n_2_4GHZ, ns3::WIFI_PHY_STANDARD_80211n_5GHZ, ns3::WIFI_PHY_STANDARD_holland, and ns3::WIFI_PHY_STANDARD_UNSPECIFIED.
Referenced by AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), DcfImmediateAccessBroadcastTestCase::DoRun(), Bug2831TestCase::DoRun(), HeAggregationTest::DoRunSubTest(), and ns3::WaveHelper::Install().
DoDispose()
void ns3::WifiMac::DoDispose () virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Reimplemented in ns3::ApWifiMac, ns3::RegularWifiMac, and ns3::MeshWifiInterfaceMac.
Definition at line 210 of file wifi-mac.cc.
References m_device.
Referenced by ns3::RegularWifiMac::DoDispose().
Enqueue() [1/2]
virtual void ns3::WifiMac::Enqueue (Ptr< Packet > packet, Mac48Address to) pure virtual
Parameters
packet the packet to send.
to the address to which the packet should be sent.
The packet should be enqueued in a TX queue, and should be dequeued as soon as the DCF function determines that access it granted to this MAC.
Implemented in ns3::RegularWifiMac, ns3::InfrastructureWifiMac, ns3::StaWifiMac, ns3::ApWifiMac, ns3::AdhocWifiMac, ns3::OcbWifiMac, and ns3::MeshWifiInterfaceMac.
Enqueue() [2/2]
virtual void ns3::WifiMac::Enqueue (Ptr< Packet > packet, Mac48Address to, Mac48Address from) pure virtual
Parameters
packet the packet to send.
to the address to which the packet should be sent.
from the address from which the packet should be sent.
The packet should be enqueued in a TX queue, and should be dequeued as soon as the DCF function determines that access it granted to this MAC. The extra parameter "from" allows this device to operate in a bridged mode, forwarding received frames without altering the source address.
Implemented in ns3::RegularWifiMac, ns3::ApWifiMac, and ns3::MeshWifiInterfaceMac.
FinishConfigureStandard()
virtual void ns3::WifiMac::FinishConfigureStandard (WifiPhyStandard standard) private pure virtual
Parameters
standard the PHY standard to be used
This method is called by ns3::WifiMac::ConfigureStandard to complete the configuration process for a requested PHY standard. Subclasses should implement this method to configure their DCF queues according to the requested standard.
Implemented in ns3::RegularWifiMac, ns3::OcbWifiMac, and ns3::MeshWifiInterfaceMac.
Referenced by ConfigureStandard().
GetAckTimeout()
virtual Time ns3::WifiMac::GetAckTimeout (void) const pure virtual
Returns
the current Ack timeout duration.
Implemented in ns3::RegularWifiMac.
Referenced by GetTypeId().
GetAddress()
virtual Mac48Address ns3::WifiMac::GetAddress (void) const pure virtual
Returns
the MAC address associated to this MAC layer.
Implemented in ns3::RegularWifiMac.
GetBasicBlockAckTimeout()
virtual Time ns3::WifiMac::GetBasicBlockAckTimeout (void) const pure virtual
Returns
the current basic BlockAck timeout duration.
Implemented in ns3::RegularWifiMac.
Referenced by GetTypeId().
GetBssid()
virtual Mac48Address ns3::WifiMac::GetBssid (void) const pure virtual
Returns
the BSSID of the network this device belongs to.
Implemented in ns3::RegularWifiMac, and ns3::OcbWifiMac.
GetCompressedBlockAckTimeout()
virtual Time ns3::WifiMac::GetCompressedBlockAckTimeout (void) const pure virtual
Returns
the current compressed BlockAck timeout duration.
Implemented in ns3::RegularWifiMac.
Referenced by GetTypeId().
GetDefaultBasicBlockAckDelay()
Time ns3::WifiMac::GetDefaultBasicBlockAckDelay (void) static private
Return the default basic BlockAck delay.
Currently it returns 250 microseconds.
Returns
the default basic BlockAck delay
Definition at line 93 of file wifi-mac.cc.
References ns3::MicroSeconds().
Referenced by Configure80211n_2_4Ghz(), Configure80211n_5Ghz(), and GetDefaultBasicBlockAckTimeout().
GetDefaultBasicBlockAckTimeout()
Time ns3::WifiMac::GetDefaultBasicBlockAckTimeout (void) static private
Return the default basic BlockAck timeout.
Returns
the default basic BlockAck timeout
Definition at line 108 of file wifi-mac.cc.
References GetDefaultBasicBlockAckDelay(), GetDefaultMaxPropagationDelay(), GetDefaultSifs(), GetDefaultSlot(), and ns3::MicroSeconds().
Referenced by GetTypeId().
GetDefaultCompressedBlockAckDelay()
Time ns3::WifiMac::GetDefaultCompressedBlockAckDelay (void) static private
Return the default compressed BlockAck delay.
Currently it returns 76 microseconds.
Returns
the default compressed BlockAck delay
Definition at line 100 of file wifi-mac.cc.
References ns3::MicroSeconds().
Referenced by Configure80211n_5Ghz(), and GetDefaultCompressedBlockAckTimeout().
GetDefaultCompressedBlockAckTimeout()
Time ns3::WifiMac::GetDefaultCompressedBlockAckTimeout (void) static private
Return the default compressed BlockAck timeout.
Returns
the default compressed BlockAck timeout
Definition at line 118 of file wifi-mac.cc.
References GetDefaultCompressedBlockAckDelay(), GetDefaultMaxPropagationDelay(), GetDefaultSifs(), GetDefaultSlot(), and ns3::MicroSeconds().
Referenced by GetTypeId().
GetDefaultCtsAckDelay()
Time ns3::WifiMac::GetDefaultCtsAckDelay (void) static private
Returns
the default CTS-Ack delay
Return a default value for 802.11a at 6Mbps (44 microseconds)
Definition at line 72 of file wifi-mac.cc.
References ns3::MicroSeconds().
Referenced by GetDefaultCtsAckTimeout(), and GetDefaultEifsNoDifs().
GetDefaultCtsAckTimeout()
Time ns3::WifiMac::GetDefaultCtsAckTimeout (void) static private
Returns
the default CTS and Ack timeout
Return the default CTS and Ack timeout. Cts_Timeout and Ack_Timeout are specified in the Annex C (Formal description of MAC operation, see details on the Trsp timer setting at page 346)
Definition at line 79 of file wifi-mac.cc.
References GetDefaultCtsAckDelay(), GetDefaultMaxPropagationDelay(), GetDefaultSifs(), GetDefaultSlot(), and ns3::MicroSeconds().
Referenced by GetTypeId().
GetDefaultEifsNoDifs()
Time ns3::WifiMac::GetDefaultEifsNoDifs (void) static private
Returns
the default extended interframe space (EIFS) without DCF interframe space (DIFS)
Return default SIFS + default CTS-Ack delay
Definition at line 66 of file wifi-mac.cc.
References GetDefaultCtsAckDelay(), and GetDefaultSifs().
Referenced by GetTypeId().
GetDefaultMaxPropagationDelay()
Time ns3::WifiMac::GetDefaultMaxPropagationDelay (void) static private
Returns
the default maximum propagation delay
By default, we get the maximum propagation delay from 1000 m and speed of light (3e8 m/s).
Definition at line 38 of file wifi-mac.cc.
References ns3::Seconds().
Referenced by Configure80211_10Mhz(), Configure80211_5Mhz(), Configure80211a(), Configure80211ax_5Ghz(), Configure80211b(), Configure80211g(), Configure80211n_2_4Ghz(), Configure80211n_5Ghz(), GetDefaultBasicBlockAckTimeout(), GetDefaultCompressedBlockAckTimeout(), GetDefaultCtsAckTimeout(), and GetTypeId().
GetDefaultRifs()
Time ns3::WifiMac::GetDefaultRifs (void) static private
Returns
the default reduced interframe space (RIFS)
Return a default RIFS value for 802.11n (2 microseconds).
Definition at line 59 of file wifi-mac.cc.
References ns3::MicroSeconds().
Referenced by GetTypeId().
GetDefaultSifs()
Time ns3::WifiMac::GetDefaultSifs (void) static private
Returns
the default short interframe space (SIFS)
Return a default SIFS value for 802.11a (16 microseconds).
Definition at line 52 of file wifi-mac.cc.
References ns3::MicroSeconds().
Referenced by GetDefaultBasicBlockAckTimeout(), GetDefaultCompressedBlockAckTimeout(), GetDefaultCtsAckTimeout(), GetDefaultEifsNoDifs(), and GetTypeId().
GetDefaultSlot()
Time ns3::WifiMac::GetDefaultSlot (void) static private
Returns
the default slot duration
Return a default slot value for 802.11a (9 microseconds).
Definition at line 45 of file wifi-mac.cc.
References ns3::MicroSeconds().
Referenced by GetDefaultBasicBlockAckTimeout(), GetDefaultCompressedBlockAckTimeout(), GetDefaultCtsAckTimeout(), and GetTypeId().
GetDevice()
Ptr< NetDevice > ns3::WifiMac::GetDevice (void) const
Return the device this PHY is associated with.
Returns
the device this PHY is associated with
Definition at line 222 of file wifi-mac.cc.
References m_device.
Referenced by GetHeConfiguration(), GetHtConfiguration(), ns3::RegularWifiMac::GetRifsSupported(), GetVhtConfiguration(), and ns3::RegularWifiMac::SetRifsSupported().
GetEifsNoDifs()
virtual Time ns3::WifiMac::GetEifsNoDifs (void) const pure virtual
Returns
the current EIFS minus DIFS duration
Implemented in ns3::RegularWifiMac.
Referenced by GetTypeId().
GetHeConfiguration()
Ptr< HeConfiguration > ns3::WifiMac::GetHeConfiguration (void) const
Returns
pointer to HeConfiguration if it exists
Definition at line 483 of file wifi-mac.cc.
References GetDevice(), and ns3::WifiNetDevice::GetHeConfiguration().
Referenced by ns3::RegularWifiMac::GetHeCapabilities(), ns3::ApWifiMac::GetHeOperation(), ns3::RegularWifiMac::GetHeSupported(), ns3::RegularWifiMac::SendAddBaResponse(), and ns3::StaWifiMac::UpdateApInfoFromAssocResp().
GetHtConfiguration()
Ptr< HtConfiguration > ns3::WifiMac::GetHtConfiguration (void) const
Returns
pointer to HtConfiguration if it exists
Definition at line 469 of file wifi-mac.cc.
References GetDevice(), and ns3::WifiNetDevice::GetHtConfiguration().
Referenced by ns3::RegularWifiMac::FinishConfigureStandard(), ns3::RegularWifiMac::GetHtCapabilities(), ns3::ApWifiMac::GetHtOperation(), ns3::RegularWifiMac::GetHtSupported(), ns3::ApWifiMac::GetRifsMode(), ns3::RegularWifiMac::GetVhtCapabilities(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetPifs()
virtual Time ns3::WifiMac::GetPifs (void) const pure virtual
Returns
the current PIFS duration.
Implemented in ns3::RegularWifiMac.
Referenced by GetTypeId().
GetRifs()
virtual Time ns3::WifiMac::GetRifs (void) const pure virtual
Returns
the current RIFS duration.
Implemented in ns3::RegularWifiMac.
Referenced by GetTypeId().
GetShortSlotTimeSupported()
virtual bool ns3::WifiMac::GetShortSlotTimeSupported (void) const pure virtual
Returns
whether the device supports short slot time capability.
Implemented in ns3::RegularWifiMac.
GetSifs()
virtual Time ns3::WifiMac::GetSifs (void) const pure virtual
Returns
the current SIFS duration.
Implemented in ns3::RegularWifiMac.
Referenced by Configure80211ax_5Ghz(), Configure80211n_2_4Ghz(), Configure80211n_5Ghz(), and GetTypeId().
GetSlot()
virtual Time ns3::WifiMac::GetSlot (void) const pure virtual
Returns
the current slot duration.
Implemented in ns3::RegularWifiMac.
Referenced by Configure80211ax_5Ghz(), Configure80211n_2_4Ghz(), Configure80211n_5Ghz(), and GetTypeId().
GetSsid()
virtual Ssid ns3::WifiMac::GetSsid (void) const pure virtual
Returns
the SSID which this MAC layer is going to try to stay in.
Implemented in ns3::RegularWifiMac, and ns3::OcbWifiMac.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::WifiMac::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 128 of file wifi-mac.cc.
References GetAckTimeout(), GetBasicBlockAckTimeout(), GetCompressedBlockAckTimeout(), GetDefaultBasicBlockAckTimeout(), GetDefaultCompressedBlockAckTimeout(), GetDefaultCtsAckTimeout(), GetDefaultEifsNoDifs(), GetDefaultMaxPropagationDelay(), GetDefaultRifs(), GetDefaultSifs(), GetDefaultSlot(), GetEifsNoDifs(), GetPifs(), GetRifs(), GetSifs(), GetSlot(), GetSsid(), m_macPromiscRxTrace, m_macRxDropTrace, m_macRxTrace, m_macTxDropTrace, m_macTxTrace, ns3::MakeSsidAccessor(), ns3::MakeSsidChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), SetAckTimeout(), SetBasicBlockAckTimeout(), SetCompressedBlockAckTimeout(), SetEifsNoDifs(), SetMaxPropagationDelay(), ns3::TypeId::SetParent(), SetPifs(), SetRifs(), SetSifs(), SetSlot(), and SetSsid().
GetVhtConfiguration()
Ptr< VhtConfiguration > ns3::WifiMac::GetVhtConfiguration (void) const
Returns
pointer to VhtConfiguration if it exists
Definition at line 476 of file wifi-mac.cc.
References GetDevice(), and ns3::WifiNetDevice::GetVhtConfiguration().
Referenced by ns3::RegularWifiMac::GetVhtCapabilities(), and ns3::RegularWifiMac::GetVhtSupported().
GetWifiPhy()
virtual Ptr<WifiPhy> ns3::WifiMac::GetWifiPhy (void) const pure virtual
Returns
the physical layer attached to this MAC
Implemented in ns3::RegularWifiMac.
GetWifiRemoteStationManager()
virtual Ptr<WifiRemoteStationManager> ns3::WifiMac::GetWifiRemoteStationManager (void) const pure virtual
Returns
the station manager attached to this MAC.
Implemented in ns3::RegularWifiMac.
NotifyPromiscRx()
void ns3::WifiMac::NotifyPromiscRx (Ptr< const Packet > packet)
Parameters
packet the packet we received promiscuously
Public method used to fire a MacPromiscRx trace. Implemented for encapsulation purposes.
Definition at line 253 of file wifi-mac.cc.
References m_macPromiscRxTrace.
NotifyRx()
void ns3::WifiMac::NotifyRx (Ptr< const Packet > packet)
Parameters
packet the packet we received
Public method used to fire a MacRx trace. Implemented for encapsulation purposes.
Definition at line 247 of file wifi-mac.cc.
References m_macRxTrace.
NotifyRxDrop()
void ns3::WifiMac::NotifyRxDrop (Ptr< const Packet > packet)
Parameters
packet the packet we received but is not destined for us
Public method used to fire a MacRxDrop trace. Implemented for encapsulation purposes.
Definition at line 259 of file wifi-mac.cc.
References m_macRxDropTrace.
Referenced by ns3::OcbWifiMac::Receive(), ns3::ApWifiMac::Receive(), and ns3::StaWifiMac::Receive().
NotifyTx()
void ns3::WifiMac::NotifyTx (Ptr< const Packet > packet)
Parameters
packet the packet being enqueued
Public method used to fire a MacTx trace. Implemented for encapsulation purposes. Note this trace indicates that the packet was accepted by the device only. The packet may be dropped later (e.g. if the queue is full).
Definition at line 235 of file wifi-mac.cc.
References m_macTxTrace.
NotifyTxDrop()
void ns3::WifiMac::NotifyTxDrop (Ptr< const Packet > packet)
Parameters
packet the packet being dropped
Public method used to fire a MacTxDrop trace. Implemented for encapsulation purposes. This trace indicates that the packet was dropped before it was transmitted (e.g. when a STA is not associated with an AP).
Definition at line 241 of file wifi-mac.cc.
References m_macTxDropTrace.
Referenced by ns3::RegularWifiMac::RegularWifiMac(), ns3::StaWifiMac::Enqueue(), ns3::ApWifiMac::Enqueue(), and ns3::RegularWifiMac::SetupEdcaQueue().
ResetWifiPhy()
virtual void ns3::WifiMac::ResetWifiPhy (void) pure virtual
Remove currently attached WifiPhy device from this MAC.
Implemented in ns3::RegularWifiMac.
SetAckTimeout()
virtual void ns3::WifiMac::SetAckTimeout (Time ackTimeout) pure virtual
Parameters
ackTimeout the duration of an Ack timeout.
Implemented in ns3::RegularWifiMac.
Referenced by Configure80211_10Mhz(), Configure80211_5Mhz(), Configure80211a(), Configure80211b(), Configure80211g(), and GetTypeId().
SetAddress()
virtual void ns3::WifiMac::SetAddress (Mac48Address address) pure virtual
Parameters
address the current address of this MAC layer.
Implemented in ns3::RegularWifiMac, ns3::ApWifiMac, and ns3::AdhocWifiMac.
Referenced by DcfImmediateAccessBroadcastTestCase::DoRun(), and Bug2831TestCase::DoRun().
SetBasicBlockAckTimeout()
virtual void ns3::WifiMac::SetBasicBlockAckTimeout (Time blockAckTimeout) pure virtual
Parameters
blockAckTimeout the duration for basic BlockAck timeout.
Sets the timeout for basic BlockAck.
Implemented in ns3::RegularWifiMac.
Referenced by Configure80211n_2_4Ghz(), Configure80211n_5Ghz(), and GetTypeId().
SetCompressedBlockAckTimeout()
virtual void ns3::WifiMac::SetCompressedBlockAckTimeout (Time blockAckTimeout) pure virtual
Parameters
blockAckTimeout the duration for compressed BlockAck timeout
Sets the timeout for compressed BlockAck.
Implemented in ns3::RegularWifiMac.
Referenced by Configure80211ax_5Ghz(), Configure80211n_2_4Ghz(), Configure80211n_5Ghz(), and GetTypeId().
SetDevice()
void ns3::WifiMac::SetDevice (const Ptr< NetDevice > device)
Sets the device this PHY is associated with.
Parameters
device the device this PHY is associated with
Definition at line 216 of file wifi-mac.cc.
References m_device.
Referenced by AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), DcfImmediateAccessBroadcastTestCase::DoRun(), Bug2831TestCase::DoRun(), and HeAggregationTest::DoRunSubTest().
SetEifsNoDifs()
virtual void ns3::WifiMac::SetEifsNoDifs (Time eifsNoDifs) pure virtual
Parameters
eifsNoDifs the duration of an EIFS minus DIFS.
This value is used to calculate the EIFS depending on AIFSN.
Implemented in ns3::RegularWifiMac.
Referenced by Configure80211_10Mhz(), Configure80211_5Mhz(), Configure80211a(), Configure80211b(), Configure80211g(), and GetTypeId().
SetForwardUpCallback()
virtual void ns3::WifiMac::SetForwardUpCallback (Callback< void, Ptr< const Packet >, Mac48Address, Mac48Address > upCallback) pure virtual
Parameters
upCallback the callback to invoke when a packet must be forwarded up the stack.
SetLinkDownCallback()
virtual void ns3::WifiMac::SetLinkDownCallback (Callback< void > linkDown) pure virtual
Parameters
linkDown the callback to invoke when the link becomes down.
Implemented in ns3::RegularWifiMac, and ns3::OcbWifiMac.
SetLinkUpCallback()
virtual void ns3::WifiMac::SetLinkUpCallback (Callback< void > linkUp) pure virtual
Parameters
linkUp the callback to invoke when the link becomes up.
Implemented in ns3::RegularWifiMac, ns3::ApWifiMac, ns3::AdhocWifiMac, ns3::OcbWifiMac, and ns3::MeshWifiInterfaceMac.
SetMaxPropagationDelay()
void ns3::WifiMac::SetMaxPropagationDelay (Time delay)
Parameters
delay the max propagation delay.
Unused for now.
Definition at line 228 of file wifi-mac.cc.
References m_maxPropagationDelay, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetPifs()
virtual void ns3::WifiMac::SetPifs (Time pifs) pure virtual
Parameters
pifs the PIFS duration.
Implemented in ns3::RegularWifiMac.
Referenced by Configure80211_10Mhz(), Configure80211_5Mhz(), Configure80211a(), Configure80211b(), Configure80211g(), and GetTypeId().
SetPromisc()
virtual void ns3::WifiMac::SetPromisc (void) pure virtual
Sets the interface in promiscuous mode.
Enables promiscuous mode on the interface. Note that any further filtering on the incoming frame path may affect the overall behavior.
Implemented in ns3::RegularWifiMac.
SetRifs()
virtual void ns3::WifiMac::SetRifs (Time rifs) pure virtual
Parameters
rifs the RIFS duration.
Implemented in ns3::RegularWifiMac.
Referenced by Configure80211n_2_4Ghz(), Configure80211n_5Ghz(), and GetTypeId().
SetShortSlotTimeSupported()
virtual void ns3::WifiMac::SetShortSlotTimeSupported (bool enable) pure virtual
Enable or disable short slot time feature.
Parameters
enable true if short slot time is to be supported, false otherwise
Implemented in ns3::RegularWifiMac.
SetSifs()
virtual void ns3::WifiMac::SetSifs (Time sifs) pure virtual
Parameters
sifs the SIFS duration
Implemented in ns3::RegularWifiMac.
Referenced by Configure80211_10Mhz(), Configure80211_5Mhz(), Configure80211a(), Configure80211b(), Configure80211g(), and GetTypeId().
SetSlot()
virtual void ns3::WifiMac::SetSlot (Time slotTime) pure virtual
Parameters
slotTime the slot duration
Implemented in ns3::RegularWifiMac.
Referenced by Configure80211_10Mhz(), Configure80211_5Mhz(), Configure80211a(), Configure80211b(), Configure80211g(), and GetTypeId().
SetSsid()
virtual void ns3::WifiMac::SetSsid (Ssid ssid) pure virtual
Parameters
ssid the current SSID of this MAC layer.
Implemented in ns3::RegularWifiMac, and ns3::OcbWifiMac.
Referenced by GetTypeId().
SetWifiPhy()
virtual void ns3::WifiMac::SetWifiPhy (Ptr< WifiPhy > phy) pure virtual
Parameters
phy the physical layer attached to this MAC.
Implemented in ns3::StaWifiMac, and ns3::RegularWifiMac.
SetWifiRemoteStationManager()
virtual void ns3::WifiMac::SetWifiRemoteStationManager (Ptr< WifiRemoteStationManager > stationManager) pure virtual
Parameters
stationManager the station manager attached to this MAC.
Implemented in ns3::StaWifiMac, ns3::RegularWifiMac, and ns3::ApWifiMac.
SupportsSendFrom()
virtual bool ns3::WifiMac::SupportsSendFrom (void) const pure virtual
Returns
if this MAC supports sending from arbitrary address.
The interface may or may not support sending from arbitrary address. This function returns true if sending from arbitrary address is supported, false otherwise.
Implemented in ns3::RegularWifiMac, ns3::ApWifiMac, and ns3::MeshWifiInterfaceMac.
Member Data Documentation
m_device
Ptr<NetDevice> ns3::WifiMac::m_device private
Pointer to the device.
Definition at line 424 of file wifi-mac.h.
Referenced by DoDispose(), GetDevice(), and SetDevice().
m_macPromiscRxTrace
TracedCallback<Ptr<const Packet> > ns3::WifiMac::m_macPromiscRxTrace private
The trace source fired for packets successfully received by the device immediately before being forwarded up to higher layers (at the L2/L3 transition).
This is a promiscuous trace.
See also
class CallBackTraceSource
Definition at line 501 of file wifi-mac.h.
Referenced by GetTypeId(), and NotifyPromiscRx().
m_macRxDropTrace
TracedCallback<Ptr<const Packet> > ns3::WifiMac::m_macRxDropTrace private
The trace source fired when packets coming into the "top" of the device are dropped at the MAC layer during reception.
See also
class CallBackTraceSource
Definition at line 516 of file wifi-mac.h.
Referenced by GetTypeId(), and NotifyRxDrop().
m_macRxTrace
TracedCallback<Ptr<const Packet> > ns3::WifiMac::m_macRxTrace private
The trace source fired for packets successfully received by the device immediately before being forwarded up to higher layers (at the L2/L3 transition).
This is a non- promiscuous trace.
See also
class CallBackTraceSource
Definition at line 509 of file wifi-mac.h.
Referenced by GetTypeId(), and NotifyRx().
m_macTxDropTrace
TracedCallback<Ptr<const Packet> > ns3::WifiMac::m_macTxDropTrace private
The trace source fired when packets coming into the "top" of the device are dropped at the MAC layer during transmission.
See also
class CallBackTraceSource
Definition at line 493 of file wifi-mac.h.
Referenced by GetTypeId(), and NotifyTxDrop().
m_macTxTrace
TracedCallback<Ptr<const Packet> > ns3::WifiMac::m_macTxTrace private
The trace source fired when packets come into the "top" of the device at the L3/L2 transition, before being queued for transmission.
See also
class CallBackTraceSource
Definition at line 486 of file wifi-mac.h.
Referenced by GetTypeId(), and NotifyTx().
m_maxPropagationDelay
Time ns3::WifiMac::m_maxPropagationDelay private
maximum propagation delay
Definition at line 423 of file wifi-mac.h.
Referenced by SetMaxPropagationDelay().
The documentation for this class was generated from the following files:
src/wifi/model/wifi-mac.h
src/wifi/model/wifi-mac.cc