ns-3: ns3::IdealHandoverPreparationInfoHeader Class Reference
ns3::IdealHandoverPreparationInfoHeader Class Reference
This header encodes the map key discussed above.
Public Member Functions
virtual uint32_t Deserialize (Buffer::Iterator start)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint32_t GetMsgId ()
Get the message ID function.
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetMsgId (uint32_t id)
Set the message ID function.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint32_t m_msgId
message ID
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This header encodes the map key discussed above.
We keep this private since it should not be used outside this file.
Definition at line 461 of file lte-rrc-protocol-ideal.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::IdealHandoverPreparationInfoHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 536 of file lte-rrc-protocol-ideal.cc.
References GetSerializedSize(), m_msgId, and visualizer.core::start().
GetInstanceTypeId()
TypeId ns3::IdealHandoverPreparationInfoHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 516 of file lte-rrc-protocol-ideal.cc.
References GetTypeId().
GetMsgId()
uint32_t ns3::IdealHandoverPreparationInfoHeader::GetMsgId ()
Get the message ID function.
Returns
the message ID
Definition at line 492 of file lte-rrc-protocol-ideal.cc.
References m_msgId.
Referenced by ns3::LteEnbRrcProtocolIdeal::DoDecodeHandoverPreparationInformation().
GetSerializedSize()
uint32_t ns3::IdealHandoverPreparationInfoHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 526 of file lte-rrc-protocol-ideal.cc.
Referenced by Deserialize().
GetTypeId()
TypeId ns3::IdealHandoverPreparationInfoHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 505 of file lte-rrc-protocol-ideal.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::IdealHandoverPreparationInfoHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 521 of file lte-rrc-protocol-ideal.cc.
References m_msgId.
Serialize()
void ns3::IdealHandoverPreparationInfoHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 531 of file lte-rrc-protocol-ideal.cc.
References m_msgId, and visualizer.core::start().
SetMsgId()
void ns3::IdealHandoverPreparationInfoHeader::SetMsgId (uint32_t id)
Set the message ID function.
Parameters
id the message ID
Definition at line 498 of file lte-rrc-protocol-ideal.cc.
References m_msgId.
Referenced by ns3::LteEnbRrcProtocolIdeal::DoEncodeHandoverPreparationInformation().
Member Data Documentation
m_msgId
uint32_t ns3::IdealHandoverPreparationInfoHeader::m_msgId private
message ID
Definition at line 488 of file lte-rrc-protocol-ideal.cc.
Referenced by Deserialize(), GetMsgId(), Print(), Serialize(), and SetMsgId().
The documentation for this class was generated from the following file:
src/lte/model/lte-rrc-protocol-ideal.cc