ns-3: Ipv4ForwardingTest Class Reference
Ipv4ForwardingTest Class Reference
Internet » internet module tests | Test suites
IPv4 Forwarding Test.
Public Member Functions
Ipv4ForwardingTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
void ReceivePkt (Ptr< Socket > socket)
Receive data.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void DoSendData (Ptr< Socket > socket, std::string to)
Send data.
void SendData (Ptr< Socket > socket, std::string to)
Send data.
Private Attributes
Ptr< Packet > m_receivedPacket
Received packet.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
IPv4 Forwarding Test.
Definition at line 56 of file ipv4-forwarding-test.cc.
Constructor & Destructor Documentation
Ipv4ForwardingTest()
Ipv4ForwardingTest::Ipv4ForwardingTest ()
Definition at line 84 of file ipv4-forwarding-test.cc.
Member Function Documentation
DoRun()
void Ipv4ForwardingTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 115 of file ipv4-forwarding-test.cc.
References ns3::Ipv4::AddAddress(), ns3::Node::AddDevice(), ns3::Ipv4::AddInterface(), ns3::SocketFactory::CreateSocket(), ns3::Object::GetObject(), ns3::Ipv4::GetRoutingProtocol(), ns3::Packet::GetSize(), ns3::InternetStackHelper::Install(), m_receivedPacket, ns3::MakeCallback(), NS_TEST_EXPECT_MSG_EQ, ReceivePkt(), ns3::Packet::RemoveAllByteTags(), SendData(), ns3::SimpleNetDevice::SetAddress(), ns3::Socket::SetAllowBroadcast(), ns3::ObjectBase::SetAttribute(), ns3::SimpleNetDevice::SetChannel(), ns3::Ipv4StaticRouting::SetDefaultRoute(), ns3::InternetStackHelper::SetIpv6StackInstall(), and ns3::Ipv4::SetUp().
DoSendData()
void Ipv4ForwardingTest::DoSendData (Ptr< Socket > socket, std::string to) private
Send data.
Parameters
socket The sending socket.
to Destination address.
Definition at line 98 of file ipv4-forwarding-test.cc.
References NS_TEST_EXPECT_MSG_EQ, and ns3::Socket::SendTo().
Referenced by SendData().
ReceivePkt()
void Ipv4ForwardingTest::ReceivePkt (Ptr< Socket > socket)
Receive data.
Parameters
socket The receiving socket.
Definition at line 89 of file ipv4-forwarding-test.cc.
References ns3::Socket::GetRxAvailable(), ns3::Packet::GetSize(), m_receivedPacket, max, NS_ASSERT, and ns3::Socket::Recv().
Referenced by DoRun().
SendData()
void Ipv4ForwardingTest::SendData (Ptr< Socket > socket, std::string to) private
Send data.
Parameters
socket The sending socket.
to Destination address.
Definition at line 106 of file ipv4-forwarding-test.cc.
References DoSendData(), ns3::Node::GetId(), ns3::Socket::GetNode(), m_receivedPacket, and ns3::Seconds().
Referenced by DoRun().
Member Data Documentation
m_receivedPacket
Ptr<Packet> Ipv4ForwardingTest::m_receivedPacket private
Received packet.
Definition at line 58 of file ipv4-forwarding-test.cc.
Referenced by DoRun(), ReceivePkt(), and SendData().
The documentation for this class was generated from the following file:
src/internet/test/ipv4-forwarding-test.cc