ns-3: ChannelAccessTestCase Class Reference
ChannelAccessTestCase Class Reference
This test case tests channel access assignments which is done by StartSch and StopSch method of WaveNetDevice.
Public Member Functions
ChannelAccessTestCase (void)
virtual ~ChannelAccessTestCase (void)
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
bool Receive (Ptr< NetDevice > dev, Ptr< const Packet > pkt, uint16_t mode, const Address &sender)
Receive function.
void SendX (uint32_t channel, uint32_t receiverId)
Send X function.
void TestAlternating (SchInfo &info, bool shouldSucceed)
Test aternating function.
void TestAlternatingAfter (uint32_t channelNumber, bool isAccessAssigned)
Test alternating after function.
void TestContinuous (SchInfo &info, bool shouldSucceed)
Test continuous function.
void TestContinuousAfter (uint32_t channelNumber, bool isAccessAssigned)
Test continuous after function.
void TestExtended (SchInfo &info, bool shouldSucceed)
Test extended function.
void TestExtendedAfter (uint32_t channelNumber, bool isAccessAssigned)
Test extended after function.
Private Attributes
NetDeviceContainer m_devices
the devices
uint32_t m_received
received
Ptr< WaveNetDevice > m_sender
sender
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
This test case tests channel access assignments which is done by StartSch and StopSch method of WaveNetDevice.
channel access assignments include ContinuousAccess, ExtendedAccess, and AlternatingAccess. The results of this test case depend on the implementation of ChannelScheduler In this case, the results depend on class "DefaultChannelScheduler".
Definition at line 534 of file mac-extension-test-suite.cc.
Constructor & Destructor Documentation
ChannelAccessTestCase()
ChannelAccessTestCase::ChannelAccessTestCase (void)
Definition at line 600 of file mac-extension-test-suite.cc.
~ChannelAccessTestCase()
ChannelAccessTestCase::~ChannelAccessTestCase (void) virtual
Definition at line 604 of file mac-extension-test-suite.cc.
Member Function Documentation
DoRun()
void ChannelAccessTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 718 of file mac-extension-test-suite.cc.
References CCH, third::channel, TestCaseHelper::CreatWaveDevice(), EXTENDED_ALTERNATING, EXTENDED_CONTINUOUS, ns3::NetDeviceContainer::Get(), m_devices, m_received, m_sender, ns3::MakeCallback(), NS_TEST_EXPECT_MSG_EQ, Receive(), SCH1, SCH2, SCH3, SCH4, SCH5, SCH6, ns3::Seconds(), SendX(), ns3::WaveNetDevice::SetReceiveCallback(), TestAlternating(), TestAlternatingAfter(), TestContinuous(), TestContinuousAfter(), TestExtended(), and TestExtendedAfter().
Receive()
bool ChannelAccessTestCase::Receive (Ptr< NetDevice > dev, Ptr< const Packet > pkt, uint16_t mode, const Address & sender) private
Receive function.
Parameters
dev the device
pkt the packet
mode the mode
sender the sender address
Returns
true if successful
Definition at line 677 of file mac-extension-test-suite.cc.
References ns3::Packet::CopyData(), data, ns3::Node::GetId(), ns3::NetDevice::GetNode(), ns3::Packet::GetSize(), m_received, NS_TEST_EXPECT_MSG_EQ, and ns3::TimeStep().
Referenced by DoRun().
SendX()
void ChannelAccessTestCase::SendX (uint32_t channel, uint32_t receiverId) private
Send X function.
Parameters
channel the channel number
receiverId
Definition at line 647 of file mac-extension-test-suite.cc.
References third::channel, data, ns3::Time::GetTimeStep(), m_sender, ns3::Now(), and ns3::WaveNetDevice::SendX().
Referenced by DoRun().
TestAlternating()
void ChannelAccessTestCase::TestAlternating (SchInfo & info, bool shouldSucceed) private
Test aternating function.
Parameters
info the schedule info
shouldSucceed true if it should succeed
Definition at line 634 of file mac-extension-test-suite.cc.
References m_sender, ns3::Now(), NS_TEST_EXPECT_MSG_EQ, and ns3::WaveNetDevice::StartSch().
Referenced by DoRun().
TestAlternatingAfter()
void ChannelAccessTestCase::TestAlternatingAfter (uint32_t channelNumber, bool isAccessAssigned) private
Test alternating after function.
Parameters
channelNumber the channel number
isAccessAssigned true if access assigned
Definition at line 640 of file mac-extension-test-suite.cc.
References ns3::WaveNetDevice::GetChannelScheduler(), m_sender, ns3::Now(), and NS_TEST_EXPECT_MSG_EQ.
Referenced by DoRun().
TestContinuous()
void ChannelAccessTestCase::TestContinuous (SchInfo & info, bool shouldSucceed) private
Test continuous function.
Parameters
info the schedule info
shouldSucceed true if it should succeed
Definition at line 609 of file mac-extension-test-suite.cc.
References m_sender, ns3::Now(), NS_TEST_EXPECT_MSG_EQ, and ns3::WaveNetDevice::StartSch().
Referenced by DoRun().
TestContinuousAfter()
void ChannelAccessTestCase::TestContinuousAfter (uint32_t channelNumber, bool isAccessAssigned) private
Test continuous after function.
Parameters
channelNumber the channel number
isAccessAssigned true if access assigned
Definition at line 615 of file mac-extension-test-suite.cc.
References ns3::WaveNetDevice::GetChannelScheduler(), m_sender, ns3::Now(), and NS_TEST_EXPECT_MSG_EQ.
Referenced by DoRun().
TestExtended()
void ChannelAccessTestCase::TestExtended (SchInfo & info, bool shouldSucceed) private
Test extended function.
Parameters
info the schedule info
shouldSucceed true if it should succeed
Definition at line 621 of file mac-extension-test-suite.cc.
References m_sender, ns3::Now(), NS_TEST_EXPECT_MSG_EQ, and ns3::WaveNetDevice::StartSch().
Referenced by DoRun().
TestExtendedAfter()
void ChannelAccessTestCase::TestExtendedAfter (uint32_t channelNumber, bool isAccessAssigned) private
Test extended after function.
Parameters
channelNumber the channel number
isAccessAssigned true if access assigned
Definition at line 627 of file mac-extension-test-suite.cc.
References ns3::WaveNetDevice::GetChannelScheduler(), m_sender, ns3::Now(), and NS_TEST_EXPECT_MSG_EQ.
Referenced by DoRun().
Member Data Documentation
m_devices
NetDeviceContainer ChannelAccessTestCase::m_devices private
the devices
Definition at line 595 of file mac-extension-test-suite.cc.
Referenced by DoRun().
m_received
uint32_t ChannelAccessTestCase::m_received private
received
Definition at line 597 of file mac-extension-test-suite.cc.
Referenced by DoRun(), and Receive().
m_sender
Ptr<WaveNetDevice> ChannelAccessTestCase::m_sender private
sender
Definition at line 596 of file mac-extension-test-suite.cc.
Referenced by DoRun(), SendX(), TestAlternating(), TestAlternatingAfter(), TestContinuous(), TestContinuousAfter(), TestExtended(), and TestExtendedAfter().
The documentation for this class was generated from the following file:
src/wave/test/mac-extension-test-suite.cc