ns-3: ns3::HtCapabilities Class Reference
ns3::HtCapabilities Class Reference
Wifi Models
The HT Capabilities Information Element.
#include "ht-capabilities.h"
Public Member Functions
HtCapabilities ()
uint8_t DeserializeInformationField (Buffer::Iterator start, uint8_t length)
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
WifiInformationElementId ElementId () const
uint8_t GetAmpduParameters (void) const
Return the A-MPDU Parameters field in the HT Capabilities information element.
uint8_t GetAntennaSelectionCapabilities (void) const
Return the Antenna Selection (ASEL) Capabilities field in the HT Capabilities information element.
uint16_t GetExtendedHtCapabilities (void) const
Return the Extended HT Capabilities field in the HT Capabilities information element.
uint8_t GetGreenfield (void) const
Return the Greenfield field.
uint16_t GetHtCapabilitiesInfo (void) const
Return the HT Capabilities Info field in the HT Capabilities information element.
uint8_t GetInformationFieldSize () const
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
uint8_t GetLdpc (void) const
Return LDPC.
uint32_t GetMaxAmpduLength (void) const
Return the maximum A-MPDU length.
uint16_t GetMaxAmsduLength (void) const
Return the maximum A-MSDU length.
uint8_t GetRxHighestSupportedAntennas (void) const
Return the receive highest supported antennas.
uint16_t GetSerializedSize () const
uint8_t GetShortGuardInterval20 (void) const
Return the short guard interval 20 value.
uint8_t GetSupportedChannelWidth (void) const
Return the supported channel width.
uint64_t GetSupportedMcsSet1 (void) const
Return the first 64 bytes of the Supported MCS Set field in the HT Capabilities information element.
uint64_t GetSupportedMcsSet2 (void) const
Return the last 64 bytes of the Supported MCS Set field in the HT Capabilities information element.
uint32_t GetTxBfCapabilities (void) const
Return the Transmit Beamforming (TxBF) Capabilities field in the HT Capabilities information element.
bool IsSupportedMcs (uint8_t mcs) const
Return the is MCS supported flag.
Buffer::Iterator Serialize (Buffer::Iterator start) const
void SerializeInformationField (Buffer::Iterator start) const
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
void SetAmpduParameters (uint8_t ctrl)
Set the A-MPDU Parameters field in the HT Capabilities information element.
void SetAntennaSelectionCapabilities (uint8_t ctrl)
Set the the Antenna Selection (ASEL) Capabilities field in the HT Capabilities information element.
void SetExtendedHtCapabilities (uint16_t ctrl)
Set the Extended HT Capabilities field in the HT Capabilities information element.
void SetGreenfield (uint8_t greenfield)
Set the Greenfield field.
void SetHtCapabilitiesInfo (uint16_t ctrl)
Set the HT Capabilities Info field in the HT Capabilities information element.
void SetHtSupported (uint8_t htSupported)
Set the HT supported field.
void SetLdpc (uint8_t ldpc)
Set the LDPC field.
void SetLSigProtectionSupport (uint8_t lSigProtection)
Set the LSIG protection support.
void SetMaxAmpduLength (uint32_t maxAmpduLength)
Set the maximum AMPDU length.
void SetMaxAmsduLength (uint16_t maxAmsduLength)
Set the maximum AMSDU length.
void SetRxHighestSupportedDataRate (uint16_t maxSupportedRate)
Set the receive highest supported data rate.
void SetRxMcsBitmask (uint8_t index)
Set the receive MCS bitmask.
void SetShortGuardInterval20 (uint8_t shortGuardInterval)
Set the short guard interval 20 field.
void SetShortGuardInterval40 (uint8_t shortGuardInterval)
Set the short guard interval 40 field.
void SetSupportedChannelWidth (uint8_t supportedChannelWidth)
Set the supported channel width field.
void SetSupportedMcsSet (uint64_t ctrl1, uint64_t ctrl2)
Set the Supported MCS Set field in the HT Capabilities information element.
void SetTxBfCapabilities (uint32_t ctrl)
Set the Transmit Beamforming (TxBF) Capabilities field in the HT Capabilities information element.
void SetTxMaxNSpatialStreams (uint8_t maxTxSpatialStreams)
Set the transmit maximum N spatial streams.
void SetTxMcsSetDefined (uint8_t txMcsSetDefined)
Set the transmit MCS set defined.
void SetTxRxMcsSetUnequal (uint8_t txRxMcsSetUnequal)
Set the transmit / receive MCS set unequal.
void SetTxUnequalModulation (uint8_t txUnequalModulation)
Set the transmit unequal modulation.
Public Member Functions inherited from ns3::WifiInformationElement
virtual ~WifiInformationElement ()
Buffer::Iterator Deserialize (Buffer::Iterator i)
Deserialize entire IE, which must be present.
Buffer::Iterator DeserializeIfPresent (Buffer::Iterator i)
Deserialize entire IE if it is present.
virtual WifiInformationElementId ElementIdExt () const
uint16_t GetSerializedSize () const
Get the size of the serialized IE including Element ID and length fields.
virtual bool operator== (WifiInformationElement const &a) const
Compare two IEs for equality by ID & Length, and then through memcmp of serialised version.
virtual void Print (std::ostream &os) const
Generate human-readable form of IE.
Buffer::Iterator Serialize (Buffer::Iterator i) const
Serialize entire IE including Element ID and length fields.
Public Member Functions inherited from ns3::SimpleRefCount< WifiInformationElement >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
uint8_t m_ampduReserved
A-MPDU reserved.
uint8_t m_antennaIndicesFeedbackBasedTxASelCapable
antenna indices feedback based transmit antenna selection capable
uint8_t m_antennaIndicesFeedbackCapable
antenna indices feedback capable
uint8_t m_antennaSelectionCapability
antenna selection capability
uint8_t m_calibration
calibration
uint8_t m_channelEstimationCapability
channel estimation capability
uint8_t m_compressedSteeringNBfAntennasSupported
compressed steering NBF antenna supported
uint8_t m_csiMaxNRowsBfSupported
CSI maximum number rows BF supported.
uint8_t m_csiNBfAntennasSupported
CSI NBF antenna supported.
uint8_t m_dssMode40
DSS mode 40.
uint8_t m_explicitCompressedBfFeedbackCapable
explicit compressed BF feedback capable
uint8_t m_explicitCompressedSteeringCapable
explicit compressed steeering capable
uint8_t m_explicitCsiFeedbackBasedTxASelCapable
explicit CSI feedback based transmit antenna selection capable
uint8_t m_explicitCsiFeedbackCapable
explicit CSI feedback capable
uint8_t m_explicitCsiTxBfCapable
explicit CSI transmit BF capable
uint8_t m_explicitNoncompressedBfFeedbackCapable
explicit non compressed BF feedback capable
uint8_t m_explicitNoncompressedSteeringCapable
explicit non compressed steeering capable
uint8_t m_explicitTxBfCsiFeedback
explicit transmit BF CSI feedback
uint8_t m_fortyMhzIntolerant
40 MHz intolerant
uint8_t m_greenField
Greenfield.
uint8_t m_htcSupport
HTC support.
uint8_t m_htDelayedBlockAck
HT delayed block ack.
uint8_t m_htSupported
This is used to decide whether this element should be added to the frame or not.
uint8_t m_implicitRxBfCapable
implicit receive BF capable
uint8_t m_implicitTxBfCapable
implicit transmit BF capable
uint8_t m_ldpc
LDPC.
uint8_t m_lsigProtectionSupport
L-SIG protection support.
uint8_t m_maxAmpduLengthExponent
maximum A-MPDU length
uint8_t m_maxAmsduLength
maximum A-MSDU length
uint8_t m_mcsFeedback
MCS feedback.
uint8_t m_minimalGrouping
minimal grouping
uint8_t m_minMpduStartSpace
minimum MPDU start space
uint8_t m_noncompressedSteeringNBfAntennasSupported
non compressed steering NBF antenna supported
uint8_t m_pco
PCO.
uint8_t m_pcoTransitionTime
PCO transition time.
uint8_t m_psmpSupport
PSMP support.
uint8_t m_reservedASel
reserved ASEL
uint8_t m_reservedExtendedCapabilities
reserved extended capabilities
uint8_t m_reservedExtendedCapabilities2
reserver extended capabilities 2
uint8_t m_reservedMcsSet1
reserved MCS set 1
uint8_t m_reservedMcsSet2
reserved MCS set 2
uint32_t m_reservedMcsSet3
reserved MCS set 3
uint8_t m_reservedTxBf
reserved transmit BF
uint8_t m_reverseDirectionResponder
reverse direction responder
uint8_t m_rxASelCapable
receive antenna selection capable
uint16_t m_rxHighestSupportedDataRate
receive highest supported data rate
uint8_t m_rxMcsBitmask [MAX_SUPPORTED_MCS]
receive MCS bitmask
uint8_t m_rxNdpCapable
receive NDP capable
uint8_t m_rxStaggeredSoundingCapable
receive staggered sounding capable
uint8_t m_rxStbc
receive STBC
uint8_t m_shortGuardInterval20
short guard interval 20 MHz
uint8_t m_shortGuardInterval40
short guard interval 40 MHz
uint8_t m_smPowerSave
SM power save.
uint8_t m_supportedChannelWidth
supported channel width
uint8_t m_txMaxNSpatialStreams
transmit maximum number spatial streams
uint8_t m_txMcsSetDefined
transmit MCS set defined
uint8_t m_txNdpCapable
transmit NDP capable
uint8_t m_txRxMcsSetUnequal
transmit / receive MCS set unequal
uint8_t m_txSoundingPpdusCapable
sounding PPDUS capable
uint8_t m_txStaggeredSoundingCapable
transmit staggered sounding capable
uint8_t m_txStbc
transmit STBC
uint8_t m_txUnequalModulation
transmit unequal modulation
Detailed Description
The HT Capabilities Information Element.
This class knows how to serialise and deserialise the HT Capabilities Information Element
Definition at line 41 of file ht-capabilities.h.
Constructor & Destructor Documentation
HtCapabilities()
ns3::HtCapabilities::HtCapabilities ()
Definition at line 26 of file ht-capabilities.cc.
References m_rxMcsBitmask, and MAX_SUPPORTED_MCS.
Member Function Documentation
DeserializeInformationField()
uint8_t ns3::HtCapabilities::DeserializeInformationField (Buffer::Iterator start, uint8_t length) virtual
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
length
Returns
the number of bytes read
Implements ns3::WifiInformationElement.
Definition at line 532 of file ht-capabilities.cc.
References ns3::Buffer::Iterator::ReadLsbtohU16(), ns3::Buffer::Iterator::ReadLsbtohU64(), ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU32(), ns3::Buffer::Iterator::ReadU8(), SetAmpduParameters(), SetAntennaSelectionCapabilities(), SetExtendedHtCapabilities(), SetHtCapabilitiesInfo(), SetSupportedMcsSet(), SetTxBfCapabilities(), and visualizer.core::start().
ElementId()
WifiInformationElementId ns3::HtCapabilities::ElementId () const virtual
Returns
Own unique Element ID
Implements ns3::WifiInformationElement.
Definition at line 96 of file ht-capabilities.cc.
References IE_HT_CAPABILITIES.
GetAmpduParameters()
uint8_t ns3::HtCapabilities::GetAmpduParameters (void) const
Return the A-MPDU Parameters field in the HT Capabilities information element.
Returns
the A-MPDU Parameters field in the HT Capabilities information element
Definition at line 344 of file ht-capabilities.cc.
References m_ampduReserved, m_maxAmpduLengthExponent, and m_minMpduStartSpace.
Referenced by SerializeInformationField().
GetAntennaSelectionCapabilities()
uint8_t ns3::HtCapabilities::GetAntennaSelectionCapabilities (void) const
Return the Antenna Selection (ASEL) Capabilities field in the HT Capabilities information element.
Returns
the Antenna Selection (ASEL) Capabilities field in the HT Capabilities information element
Definition at line 488 of file ht-capabilities.cc.
References m_antennaIndicesFeedbackBasedTxASelCapable, m_antennaIndicesFeedbackCapable, m_antennaSelectionCapability, m_explicitCsiFeedbackBasedTxASelCapable, m_explicitCsiFeedbackCapable, m_reservedASel, m_rxASelCapable, and m_txSoundingPpdusCapable.
Referenced by SerializeInformationField().
GetExtendedHtCapabilities()
uint16_t ns3::HtCapabilities::GetExtendedHtCapabilities (void) const
Return the Extended HT Capabilities field in the HT Capabilities information element.
Returns
the Extended HT Capabilities field in the HT Capabilities information element
Definition at line 410 of file ht-capabilities.cc.
References m_htcSupport, m_mcsFeedback, m_pco, m_pcoTransitionTime, m_reservedExtendedCapabilities, m_reservedExtendedCapabilities2, and m_reverseDirectionResponder.
Referenced by SerializeInformationField().
GetGreenfield()
uint8_t ns3::HtCapabilities::GetGreenfield (void) const
Return the Greenfield field.
Returns
the Greenfield field
Definition at line 214 of file ht-capabilities.cc.
References m_greenField.
Referenced by ns3::operator<<().
GetHtCapabilitiesInfo()
uint16_t ns3::HtCapabilities::GetHtCapabilitiesInfo (void) const
Return the HT Capabilities Info field in the HT Capabilities information element.
Returns
the HT Capabilities Info field in the HT Capabilities information element
Definition at line 296 of file ht-capabilities.cc.
References m_dssMode40, m_fortyMhzIntolerant, m_greenField, m_htDelayedBlockAck, m_ldpc, m_lsigProtectionSupport, m_maxAmsduLength, m_psmpSupport, m_rxStbc, m_shortGuardInterval20, m_shortGuardInterval40, m_smPowerSave, m_supportedChannelWidth, and m_txStbc.
Referenced by SerializeInformationField().
GetInformationFieldSize()
uint8_t ns3::HtCapabilities::GetInformationFieldSize () const virtual
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
This is the value that will appear in the second octet of the entire IE - the length field)
Returns
the length of serialized information
Implements ns3::WifiInformationElement.
Definition at line 268 of file ht-capabilities.cc.
References m_htSupported, and NS_ASSERT.
GetLdpc()
uint8_t ns3::HtCapabilities::GetLdpc (void) const
Return LDPC.
Returns
the LDPC value
Definition at line 202 of file ht-capabilities.cc.
References m_ldpc.
Referenced by ns3::operator<<().
GetMaxAmpduLength()
uint32_t ns3::HtCapabilities::GetMaxAmpduLength (void) const
Return the maximum A-MPDU length.
Returns
the maximum A-MPDU length
Definition at line 236 of file ht-capabilities.cc.
References m_maxAmpduLengthExponent.
GetMaxAmsduLength()
uint16_t ns3::HtCapabilities::GetMaxAmsduLength (void) const
Return the maximum A-MSDU length.
Returns
the maximum A-MSDU length
Definition at line 226 of file ht-capabilities.cc.
References m_maxAmsduLength.
GetRxHighestSupportedAntennas()
uint8_t ns3::HtCapabilities::GetRxHighestSupportedAntennas (void) const
Return the receive highest supported antennas.
Returns
the receive highest supported antennas
Definition at line 252 of file ht-capabilities.cc.
References IsSupportedMcs().
GetSerializedSize()
uint16_t ns3::HtCapabilities::GetSerializedSize () const
Definition at line 286 of file ht-capabilities.cc.
References ns3::WifiInformationElement::GetSerializedSize(), and m_htSupported.
Referenced by ns3::MgtAssocRequestHeader::GetSerializedSize(), ns3::MgtReassocRequestHeader::GetSerializedSize(), ns3::MgtAssocResponseHeader::GetSerializedSize(), ns3::MgtProbeRequestHeader::GetSerializedSize(), and ns3::MgtProbeResponseHeader::GetSerializedSize().
GetShortGuardInterval20()
uint8_t ns3::HtCapabilities::GetShortGuardInterval20 (void) const
Return the short guard interval 20 value.
Returns
the short guard interval 20 value
Definition at line 220 of file ht-capabilities.cc.
References m_shortGuardInterval20.
Referenced by ns3::operator<<().
GetSupportedChannelWidth()
uint8_t ns3::HtCapabilities::GetSupportedChannelWidth (void) const
Return the supported channel width.
Returns
the supported channel width
Definition at line 208 of file ht-capabilities.cc.
References m_supportedChannelWidth.
Referenced by ns3::WifiRemoteStationManager::AddStationHtCapabilities(), and ns3::operator<<().
GetSupportedMcsSet1()
uint64_t ns3::HtCapabilities::GetSupportedMcsSet1 (void) const
Return the first 64 bytes of the Supported MCS Set field in the HT Capabilities information element.
Returns
the first 64 bytes of the Supported MCS Set field in the HT Capabilities information element
Definition at line 378 of file ht-capabilities.cc.
References m_rxMcsBitmask.
Referenced by SerializeInformationField().
GetSupportedMcsSet2()
uint64_t ns3::HtCapabilities::GetSupportedMcsSet2 (void) const
Return the last 64 bytes of the Supported MCS Set field in the HT Capabilities information element.
Returns
the last 64 bytes of the Supported MCS Set field in the HT Capabilities information element
Definition at line 390 of file ht-capabilities.cc.
References m_reservedMcsSet1, m_reservedMcsSet2, m_reservedMcsSet3, m_rxHighestSupportedDataRate, m_rxMcsBitmask, m_txMaxNSpatialStreams, m_txMcsSetDefined, m_txRxMcsSetUnequal, and m_txUnequalModulation.
Referenced by SerializeInformationField().
GetTxBfCapabilities()
uint32_t ns3::HtCapabilities::GetTxBfCapabilities (void) const
Return the Transmit Beamforming (TxBF) Capabilities field in the HT Capabilities information element.
Returns
the Transmit Beamforming (TxBF) Capabilities field in the HT Capabilities information element
Definition at line 436 of file ht-capabilities.cc.
References m_calibration, m_channelEstimationCapability, m_compressedSteeringNBfAntennasSupported, m_csiMaxNRowsBfSupported, m_csiNBfAntennasSupported, m_explicitCompressedBfFeedbackCapable, m_explicitCompressedSteeringCapable, m_explicitCsiTxBfCapable, m_explicitNoncompressedBfFeedbackCapable, m_explicitNoncompressedSteeringCapable, m_explicitTxBfCsiFeedback, m_implicitRxBfCapable, m_implicitTxBfCapable, m_minimalGrouping, m_noncompressedSteeringNBfAntennasSupported, m_reservedTxBf, m_rxNdpCapable, m_rxStaggeredSoundingCapable, m_txNdpCapable, and m_txStaggeredSoundingCapable.
Referenced by SerializeInformationField().
IsSupportedMcs()
bool ns3::HtCapabilities::IsSupportedMcs (uint8_t mcs) const
Return the is MCS supported flag.
Parameters
mcs is MCS supported flag
Returns
true if successful
Definition at line 242 of file ht-capabilities.cc.
References m_rxMcsBitmask.
Referenced by ns3::WifiRemoteStationManager::AddStationHtCapabilities(), GetRxHighestSupportedAntennas(), ns3::operator<<(), ns3::ApWifiMac::Receive(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
Serialize()
Buffer::Iterator ns3::HtCapabilities::Serialize (Buffer::Iterator start) const
Definition at line 276 of file ht-capabilities.cc.
References m_htSupported, and ns3::WifiInformationElement::Serialize().
Referenced by ns3::MgtAssocRequestHeader::Serialize(), ns3::MgtReassocRequestHeader::Serialize(), ns3::MgtAssocResponseHeader::Serialize(), ns3::MgtProbeRequestHeader::Serialize(), and ns3::MgtProbeResponseHeader::Serialize().
SerializeInformationField()
void ns3::HtCapabilities::SerializeInformationField (Buffer::Iterator start) const virtual
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
Implements ns3::WifiInformationElement.
Definition at line 516 of file ht-capabilities.cc.
References GetAmpduParameters(), GetAntennaSelectionCapabilities(), GetExtendedHtCapabilities(), GetHtCapabilitiesInfo(), GetSupportedMcsSet1(), GetSupportedMcsSet2(), GetTxBfCapabilities(), m_htSupported, and visualizer.core::start().
SetAmpduParameters()
void ns3::HtCapabilities::SetAmpduParameters (uint8_t ctrl)
Set the A-MPDU Parameters field in the HT Capabilities information element.
Parameters
ctrl the A-MPDU Parameters field in the HT Capabilities information element
Definition at line 336 of file ht-capabilities.cc.
References m_ampduReserved, m_maxAmpduLengthExponent, and m_minMpduStartSpace.
Referenced by DeserializeInformationField().
SetAntennaSelectionCapabilities()
void ns3::HtCapabilities::SetAntennaSelectionCapabilities (uint8_t ctrl)
Set the the Antenna Selection (ASEL) Capabilities field in the HT Capabilities information element.
Parameters
ctrl the Antenna Selection (ASEL) Capabilities field in the HT Capabilities information element
Definition at line 503 of file ht-capabilities.cc.
References m_antennaIndicesFeedbackBasedTxASelCapable, m_antennaIndicesFeedbackCapable, m_antennaSelectionCapability, m_explicitCsiFeedbackBasedTxASelCapable, m_explicitCsiFeedbackCapable, m_reservedASel, m_rxASelCapable, and m_txSoundingPpdusCapable.
Referenced by DeserializeInformationField().
SetExtendedHtCapabilities()
void ns3::HtCapabilities::SetExtendedHtCapabilities (uint16_t ctrl)
Set the Extended HT Capabilities field in the HT Capabilities information element.
Parameters
ctrl the Extended HT Capabilities field in the HT Capabilities information element
Definition at line 424 of file ht-capabilities.cc.
References m_htcSupport, m_mcsFeedback, m_pco, m_pcoTransitionTime, m_reservedExtendedCapabilities, m_reservedExtendedCapabilities2, and m_reverseDirectionResponder.
Referenced by DeserializeInformationField().
SetGreenfield()
void ns3::HtCapabilities::SetGreenfield (uint8_t greenfield)
Set the Greenfield field.
Parameters
greenfield the Greenfield field
Definition at line 120 of file ht-capabilities.cc.
References m_greenField.
Referenced by ns3::RegularWifiMac::GetHtCapabilities().
SetHtCapabilitiesInfo()
void ns3::HtCapabilities::SetHtCapabilitiesInfo (uint16_t ctrl)
Set the HT Capabilities Info field in the HT Capabilities information element.
Parameters
ctrl the HT Capabilities Info field in the HT Capabilities information element
Definition at line 317 of file ht-capabilities.cc.
References m_dssMode40, m_fortyMhzIntolerant, m_greenField, m_htDelayedBlockAck, m_ldpc, m_lsigProtectionSupport, m_maxAmsduLength, m_psmpSupport, m_rxStbc, m_shortGuardInterval20, m_shortGuardInterval40, m_smPowerSave, m_supportedChannelWidth, and m_txStbc.
Referenced by DeserializeInformationField().
SetHtSupported()
void ns3::HtCapabilities::SetHtSupported (uint8_t htSupported)
Set the HT supported field.
Parameters
htSupported the HT supported field
Definition at line 102 of file ht-capabilities.cc.
References m_htSupported.
Referenced by ns3::RegularWifiMac::GetHtCapabilities().
SetLdpc()
void ns3::HtCapabilities::SetLdpc (uint8_t ldpc)
Set the LDPC field.
Parameters
ldpc the LDPC field
Definition at line 108 of file ht-capabilities.cc.
References m_ldpc.
Referenced by ns3::RegularWifiMac::GetHtCapabilities().
SetLSigProtectionSupport()
void ns3::HtCapabilities::SetLSigProtectionSupport (uint8_t lSigProtection)
Set the LSIG protection support.
Parameters
lSigProtection the LSIG protection support field
Definition at line 146 of file ht-capabilities.cc.
References m_lsigProtectionSupport.
Referenced by ns3::RegularWifiMac::GetHtCapabilities().
SetMaxAmpduLength()
void ns3::HtCapabilities::SetMaxAmpduLength (uint32_t maxAmpduLength)
Set the maximum AMPDU length.
Parameters
maxAmpduLength 2^(13 + x) - 1, x in the range 0 to 3
Definition at line 152 of file ht-capabilities.cc.
References m_maxAmpduLengthExponent, and NS_ABORT_MSG.
Referenced by AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), and ns3::RegularWifiMac::GetHtCapabilities().
SetMaxAmsduLength()
void ns3::HtCapabilities::SetMaxAmsduLength (uint16_t maxAmsduLength)
Set the maximum AMSDU length.
Parameters
maxAmsduLength Either 3839 or 7935
Definition at line 138 of file ht-capabilities.cc.
References m_maxAmsduLength, and NS_ABORT_MSG_IF.
Referenced by TwoLevelAggregationTest::DoRun(), and ns3::RegularWifiMac::GetHtCapabilities().
SetRxHighestSupportedDataRate()
void ns3::HtCapabilities::SetRxHighestSupportedDataRate (uint16_t maxSupportedRate)
Set the receive highest supported data rate.
Parameters
maxSupportedRate the maximum supported data rate
Definition at line 172 of file ht-capabilities.cc.
References m_rxHighestSupportedDataRate.
Referenced by ns3::RegularWifiMac::GetHtCapabilities().
SetRxMcsBitmask()
void ns3::HtCapabilities::SetRxMcsBitmask (uint8_t index)
Set the receive MCS bitmask.
Parameters
index the index of the receive MCS
Definition at line 166 of file ht-capabilities.cc.
References m_rxMcsBitmask.
Referenced by ns3::RegularWifiMac::GetHtCapabilities().
SetShortGuardInterval20()
void ns3::HtCapabilities::SetShortGuardInterval20 (uint8_t shortGuardInterval)
Set the short guard interval 20 field.
Parameters
shortGuardInterval the short guard interval
Definition at line 126 of file ht-capabilities.cc.
References m_shortGuardInterval20.
Referenced by ns3::RegularWifiMac::GetHtCapabilities().
SetShortGuardInterval40()
void ns3::HtCapabilities::SetShortGuardInterval40 (uint8_t shortGuardInterval)
Set the short guard interval 40 field.
Parameters
shortGuardInterval the short guard interval
Definition at line 132 of file ht-capabilities.cc.
References m_shortGuardInterval40.
Referenced by ns3::RegularWifiMac::GetHtCapabilities().
SetSupportedChannelWidth()
void ns3::HtCapabilities::SetSupportedChannelWidth (uint8_t supportedChannelWidth)
Set the supported channel width field.
Parameters
supportedChannelWidth the supported channel width field
Definition at line 114 of file ht-capabilities.cc.
References m_supportedChannelWidth.
Referenced by ns3::RegularWifiMac::GetHtCapabilities().
SetSupportedMcsSet()
void ns3::HtCapabilities::SetSupportedMcsSet (uint64_t ctrl1, uint64_t ctrl2)
Set the Supported MCS Set field in the HT Capabilities information element.
Parameters
ctrl1 the first 64 bytes of the Supported MCS Set field in the HT Capabilities information element
ctrl2 the last 64 bytes of the Supported MCS Set field in the HT Capabilities information element
Definition at line 354 of file ht-capabilities.cc.
References m_reservedMcsSet1, m_reservedMcsSet2, m_reservedMcsSet3, m_rxHighestSupportedDataRate, m_rxMcsBitmask, m_txMaxNSpatialStreams, m_txMcsSetDefined, m_txRxMcsSetUnequal, and m_txUnequalModulation.
Referenced by DeserializeInformationField().
SetTxBfCapabilities()
void ns3::HtCapabilities::SetTxBfCapabilities (uint32_t ctrl)
Set the Transmit Beamforming (TxBF) Capabilities field in the HT Capabilities information element.
Parameters
ctrl the Transmit Beamforming (TxBF) Capabilities field in the HT Capabilities information element
Definition at line 463 of file ht-capabilities.cc.
References m_calibration, m_channelEstimationCapability, m_compressedSteeringNBfAntennasSupported, m_csiMaxNRowsBfSupported, m_csiNBfAntennasSupported, m_explicitCompressedBfFeedbackCapable, m_explicitCompressedSteeringCapable, m_explicitCsiTxBfCapable, m_explicitNoncompressedBfFeedbackCapable, m_explicitNoncompressedSteeringCapable, m_explicitTxBfCsiFeedback, m_implicitRxBfCapable, m_implicitTxBfCapable, m_minimalGrouping, m_noncompressedSteeringNBfAntennasSupported, m_reservedTxBf, m_rxNdpCapable, m_rxStaggeredSoundingCapable, m_txNdpCapable, and m_txStaggeredSoundingCapable.
Referenced by DeserializeInformationField().
SetTxMaxNSpatialStreams()
void ns3::HtCapabilities::SetTxMaxNSpatialStreams (uint8_t maxTxSpatialStreams)
Set the transmit maximum N spatial streams.
Parameters
maxTxSpatialStreams the maximum number of TX SSs
Definition at line 190 of file ht-capabilities.cc.
References m_txMaxNSpatialStreams.
Referenced by ns3::RegularWifiMac::GetHtCapabilities().
SetTxMcsSetDefined()
void ns3::HtCapabilities::SetTxMcsSetDefined (uint8_t txMcsSetDefined)
Set the transmit MCS set defined.
Parameters
txMcsSetDefined the TX MCS set defined
Definition at line 178 of file ht-capabilities.cc.
References m_txMcsSetDefined.
Referenced by ns3::RegularWifiMac::GetHtCapabilities().
SetTxRxMcsSetUnequal()
void ns3::HtCapabilities::SetTxRxMcsSetUnequal (uint8_t txRxMcsSetUnequal)
Set the transmit / receive MCS set unequal.
Parameters
txRxMcsSetUnequal the TX/RX MCS set unequal field
Definition at line 184 of file ht-capabilities.cc.
References m_txRxMcsSetUnequal.
Referenced by ns3::RegularWifiMac::GetHtCapabilities().
SetTxUnequalModulation()
void ns3::HtCapabilities::SetTxUnequalModulation (uint8_t txUnequalModulation)
Set the transmit unequal modulation.
Parameters
txUnequalModulation the TX unequal modulation field
Definition at line 196 of file ht-capabilities.cc.
References m_txUnequalModulation.
Referenced by ns3::RegularWifiMac::GetHtCapabilities().
Member Data Documentation
m_ampduReserved
uint8_t ns3::HtCapabilities::m_ampduReserved private
A-MPDU reserved.
Definition at line 306 of file ht-capabilities.h.
Referenced by GetAmpduParameters(), and SetAmpduParameters().
m_antennaIndicesFeedbackBasedTxASelCapable
uint8_t ns3::HtCapabilities::m_antennaIndicesFeedbackBasedTxASelCapable private
antenna indices feedback based transmit antenna selection capable
Definition at line 353 of file ht-capabilities.h.
Referenced by GetAntennaSelectionCapabilities(), and SetAntennaSelectionCapabilities().
m_antennaIndicesFeedbackCapable
uint8_t ns3::HtCapabilities::m_antennaIndicesFeedbackCapable private
antenna indices feedback capable
Definition at line 355 of file ht-capabilities.h.
Referenced by GetAntennaSelectionCapabilities(), and SetAntennaSelectionCapabilities().
m_antennaSelectionCapability
uint8_t ns3::HtCapabilities::m_antennaSelectionCapability private
antenna selection capability
Definition at line 351 of file ht-capabilities.h.
Referenced by GetAntennaSelectionCapabilities(), and SetAntennaSelectionCapabilities().
m_calibration
uint8_t ns3::HtCapabilities::m_calibration private
calibration
Definition at line 335 of file ht-capabilities.h.
Referenced by GetTxBfCapabilities(), and SetTxBfCapabilities().
m_channelEstimationCapability
uint8_t ns3::HtCapabilities::m_channelEstimationCapability private
channel estimation capability
Definition at line 347 of file ht-capabilities.h.
Referenced by GetTxBfCapabilities(), and SetTxBfCapabilities().
m_compressedSteeringNBfAntennasSupported
uint8_t ns3::HtCapabilities::m_compressedSteeringNBfAntennasSupported private
compressed steering NBF antenna supported
Definition at line 345 of file ht-capabilities.h.
Referenced by GetTxBfCapabilities(), and SetTxBfCapabilities().
m_csiMaxNRowsBfSupported
uint8_t ns3::HtCapabilities::m_csiMaxNRowsBfSupported private
CSI maximum number rows BF supported.
Definition at line 346 of file ht-capabilities.h.
Referenced by GetTxBfCapabilities(), and SetTxBfCapabilities().
m_csiNBfAntennasSupported
uint8_t ns3::HtCapabilities::m_csiNBfAntennasSupported private
CSI NBF antenna supported.
Definition at line 343 of file ht-capabilities.h.
Referenced by GetTxBfCapabilities(), and SetTxBfCapabilities().
m_dssMode40
uint8_t ns3::HtCapabilities::m_dssMode40 private
DSS mode 40.
Definition at line 298 of file ht-capabilities.h.
Referenced by GetHtCapabilitiesInfo(), and SetHtCapabilitiesInfo().
m_explicitCompressedBfFeedbackCapable
uint8_t ns3::HtCapabilities::m_explicitCompressedBfFeedbackCapable private
explicit compressed BF feedback capable
Definition at line 341 of file ht-capabilities.h.
Referenced by GetTxBfCapabilities(), and SetTxBfCapabilities().
m_explicitCompressedSteeringCapable
uint8_t ns3::HtCapabilities::m_explicitCompressedSteeringCapable private
explicit compressed steeering capable
Definition at line 338 of file ht-capabilities.h.
Referenced by GetTxBfCapabilities(), and SetTxBfCapabilities().
m_explicitCsiFeedbackBasedTxASelCapable
uint8_t ns3::HtCapabilities::m_explicitCsiFeedbackBasedTxASelCapable private
explicit CSI feedback based transmit antenna selection capable
Definition at line 352 of file ht-capabilities.h.
Referenced by GetAntennaSelectionCapabilities(), and SetAntennaSelectionCapabilities().
m_explicitCsiFeedbackCapable
uint8_t ns3::HtCapabilities::m_explicitCsiFeedbackCapable private
explicit CSI feedback capable
Definition at line 354 of file ht-capabilities.h.
Referenced by GetAntennaSelectionCapabilities(), and SetAntennaSelectionCapabilities().
m_explicitCsiTxBfCapable
uint8_t ns3::HtCapabilities::m_explicitCsiTxBfCapable private
explicit CSI transmit BF capable
Definition at line 336 of file ht-capabilities.h.
Referenced by GetTxBfCapabilities(), and SetTxBfCapabilities().
m_explicitNoncompressedBfFeedbackCapable
uint8_t ns3::HtCapabilities::m_explicitNoncompressedBfFeedbackCapable private
explicit non compressed BF feedback capable
Definition at line 340 of file ht-capabilities.h.
Referenced by GetTxBfCapabilities(), and SetTxBfCapabilities().
m_explicitNoncompressedSteeringCapable
uint8_t ns3::HtCapabilities::m_explicitNoncompressedSteeringCapable private
explicit non compressed steeering capable
Definition at line 337 of file ht-capabilities.h.
Referenced by GetTxBfCapabilities(), and SetTxBfCapabilities().
m_explicitTxBfCsiFeedback
uint8_t ns3::HtCapabilities::m_explicitTxBfCsiFeedback private
explicit transmit BF CSI feedback
Definition at line 339 of file ht-capabilities.h.
Referenced by GetTxBfCapabilities(), and SetTxBfCapabilities().
m_fortyMhzIntolerant
uint8_t ns3::HtCapabilities::m_fortyMhzIntolerant private
40 MHz intolerant
Definition at line 300 of file ht-capabilities.h.
Referenced by GetHtCapabilitiesInfo(), and SetHtCapabilitiesInfo().
m_greenField
uint8_t ns3::HtCapabilities::m_greenField private
Greenfield.
Definition at line 291 of file ht-capabilities.h.
Referenced by GetGreenfield(), GetHtCapabilitiesInfo(), SetGreenfield(), and SetHtCapabilitiesInfo().
m_htcSupport
uint8_t ns3::HtCapabilities::m_htcSupport private
HTC support.
Definition at line 324 of file ht-capabilities.h.
Referenced by GetExtendedHtCapabilities(), and SetExtendedHtCapabilities().
m_htDelayedBlockAck
uint8_t ns3::HtCapabilities::m_htDelayedBlockAck private
HT delayed block ack.
Definition at line 296 of file ht-capabilities.h.
Referenced by GetHtCapabilitiesInfo(), and SetHtCapabilitiesInfo().
m_htSupported
uint8_t ns3::HtCapabilities::m_htSupported private
This is used to decide whether this element should be added to the frame or not.
Definition at line 361 of file ht-capabilities.h.
Referenced by GetInformationFieldSize(), GetSerializedSize(), Serialize(), SerializeInformationField(), and SetHtSupported().
m_implicitRxBfCapable
uint8_t ns3::HtCapabilities::m_implicitRxBfCapable private
implicit receive BF capable
Definition at line 329 of file ht-capabilities.h.
Referenced by GetTxBfCapabilities(), and SetTxBfCapabilities().
m_implicitTxBfCapable
uint8_t ns3::HtCapabilities::m_implicitTxBfCapable private
implicit transmit BF capable
Definition at line 334 of file ht-capabilities.h.
Referenced by GetTxBfCapabilities(), and SetTxBfCapabilities().
m_ldpc
uint8_t ns3::HtCapabilities::m_ldpc private
LDPC.
Definition at line 288 of file ht-capabilities.h.
Referenced by GetHtCapabilitiesInfo(), GetLdpc(), SetHtCapabilitiesInfo(), and SetLdpc().
m_lsigProtectionSupport
uint8_t ns3::HtCapabilities::m_lsigProtectionSupport private
L-SIG protection support.
Definition at line 301 of file ht-capabilities.h.
Referenced by GetHtCapabilitiesInfo(), SetHtCapabilitiesInfo(), and SetLSigProtectionSupport().
m_maxAmpduLengthExponent
uint8_t ns3::HtCapabilities::m_maxAmpduLengthExponent private
maximum A-MPDU length
Definition at line 304 of file ht-capabilities.h.
Referenced by GetAmpduParameters(), GetMaxAmpduLength(), SetAmpduParameters(), and SetMaxAmpduLength().
m_maxAmsduLength
uint8_t ns3::HtCapabilities::m_maxAmsduLength private
maximum A-MSDU length
Definition at line 297 of file ht-capabilities.h.
Referenced by GetHtCapabilitiesInfo(), GetMaxAmsduLength(), SetHtCapabilitiesInfo(), and SetMaxAmsduLength().
m_mcsFeedback
uint8_t ns3::HtCapabilities::m_mcsFeedback private
MCS feedback.
Definition at line 323 of file ht-capabilities.h.
Referenced by GetExtendedHtCapabilities(), and SetExtendedHtCapabilities().
m_minimalGrouping
uint8_t ns3::HtCapabilities::m_minimalGrouping private
minimal grouping
Definition at line 342 of file ht-capabilities.h.
Referenced by GetTxBfCapabilities(), and SetTxBfCapabilities().
m_minMpduStartSpace
uint8_t ns3::HtCapabilities::m_minMpduStartSpace private
minimum MPDU start space
Definition at line 305 of file ht-capabilities.h.
Referenced by GetAmpduParameters(), and SetAmpduParameters().
m_noncompressedSteeringNBfAntennasSupported
uint8_t ns3::HtCapabilities::m_noncompressedSteeringNBfAntennasSupported private
non compressed steering NBF antenna supported
Definition at line 344 of file ht-capabilities.h.
Referenced by GetTxBfCapabilities(), and SetTxBfCapabilities().
m_pco
uint8_t ns3::HtCapabilities::m_pco private
PCO.
Definition at line 320 of file ht-capabilities.h.
Referenced by GetExtendedHtCapabilities(), and SetExtendedHtCapabilities().
m_pcoTransitionTime
uint8_t ns3::HtCapabilities::m_pcoTransitionTime private
PCO transition time.
Definition at line 321 of file ht-capabilities.h.
Referenced by GetExtendedHtCapabilities(), and SetExtendedHtCapabilities().
m_psmpSupport
uint8_t ns3::HtCapabilities::m_psmpSupport private
PSMP support.
Definition at line 299 of file ht-capabilities.h.
Referenced by GetHtCapabilitiesInfo(), and SetHtCapabilitiesInfo().
m_reservedASel
uint8_t ns3::HtCapabilities::m_reservedASel private
reserved ASEL
Definition at line 358 of file ht-capabilities.h.
Referenced by GetAntennaSelectionCapabilities(), and SetAntennaSelectionCapabilities().
m_reservedExtendedCapabilities
uint8_t ns3::HtCapabilities::m_reservedExtendedCapabilities private
reserved extended capabilities
Definition at line 322 of file ht-capabilities.h.
Referenced by GetExtendedHtCapabilities(), and SetExtendedHtCapabilities().
m_reservedExtendedCapabilities2
uint8_t ns3::HtCapabilities::m_reservedExtendedCapabilities2 private
reserver extended capabilities 2
Definition at line 326 of file ht-capabilities.h.
Referenced by GetExtendedHtCapabilities(), and SetExtendedHtCapabilities().
m_reservedMcsSet1
uint8_t ns3::HtCapabilities::m_reservedMcsSet1 private
reserved MCS set 1
Definition at line 309 of file ht-capabilities.h.
Referenced by GetSupportedMcsSet2(), and SetSupportedMcsSet().
m_reservedMcsSet2
uint8_t ns3::HtCapabilities::m_reservedMcsSet2 private
reserved MCS set 2
Definition at line 311 of file ht-capabilities.h.
Referenced by GetSupportedMcsSet2(), and SetSupportedMcsSet().
m_reservedMcsSet3
uint32_t ns3::HtCapabilities::m_reservedMcsSet3 private
reserved MCS set 3
Definition at line 316 of file ht-capabilities.h.
Referenced by GetSupportedMcsSet2(), and SetSupportedMcsSet().
m_reservedTxBf
uint8_t ns3::HtCapabilities::m_reservedTxBf private
reserved transmit BF
Definition at line 348 of file ht-capabilities.h.
Referenced by GetTxBfCapabilities(), and SetTxBfCapabilities().
m_reverseDirectionResponder
uint8_t ns3::HtCapabilities::m_reverseDirectionResponder private
reverse direction responder
Definition at line 325 of file ht-capabilities.h.
Referenced by GetExtendedHtCapabilities(), and SetExtendedHtCapabilities().
m_rxASelCapable
uint8_t ns3::HtCapabilities::m_rxASelCapable private
receive antenna selection capable
Definition at line 356 of file ht-capabilities.h.
Referenced by GetAntennaSelectionCapabilities(), and SetAntennaSelectionCapabilities().
m_rxHighestSupportedDataRate
uint16_t ns3::HtCapabilities::m_rxHighestSupportedDataRate private
receive highest supported data rate
Definition at line 310 of file ht-capabilities.h.
Referenced by GetSupportedMcsSet2(), SetRxHighestSupportedDataRate(), and SetSupportedMcsSet().
m_rxMcsBitmask
uint8_t ns3::HtCapabilities::m_rxMcsBitmask[MAX_SUPPORTED_MCS] private
receive MCS bitmask
Definition at line 317 of file ht-capabilities.h.
Referenced by HtCapabilities(), GetSupportedMcsSet1(), GetSupportedMcsSet2(), IsSupportedMcs(), SetRxMcsBitmask(), and SetSupportedMcsSet().
m_rxNdpCapable
uint8_t ns3::HtCapabilities::m_rxNdpCapable private
receive NDP capable
Definition at line 332 of file ht-capabilities.h.
Referenced by GetTxBfCapabilities(), and SetTxBfCapabilities().
m_rxStaggeredSoundingCapable
uint8_t ns3::HtCapabilities::m_rxStaggeredSoundingCapable private
receive staggered sounding capable
Definition at line 330 of file ht-capabilities.h.
Referenced by GetTxBfCapabilities(), and SetTxBfCapabilities().
m_rxStbc
uint8_t ns3::HtCapabilities::m_rxStbc private
receive STBC
Definition at line 295 of file ht-capabilities.h.
Referenced by GetHtCapabilitiesInfo(), and SetHtCapabilitiesInfo().
m_shortGuardInterval20
uint8_t ns3::HtCapabilities::m_shortGuardInterval20 private
short guard interval 20 MHz
Definition at line 292 of file ht-capabilities.h.
Referenced by GetHtCapabilitiesInfo(), GetShortGuardInterval20(), SetHtCapabilitiesInfo(), and SetShortGuardInterval20().
m_shortGuardInterval40
uint8_t ns3::HtCapabilities::m_shortGuardInterval40 private
short guard interval 40 MHz
Definition at line 293 of file ht-capabilities.h.
Referenced by GetHtCapabilitiesInfo(), SetHtCapabilitiesInfo(), and SetShortGuardInterval40().
m_smPowerSave
uint8_t ns3::HtCapabilities::m_smPowerSave private
SM power save.
Definition at line 290 of file ht-capabilities.h.
Referenced by GetHtCapabilitiesInfo(), and SetHtCapabilitiesInfo().
m_supportedChannelWidth
uint8_t ns3::HtCapabilities::m_supportedChannelWidth private
supported channel width
Definition at line 289 of file ht-capabilities.h.
Referenced by GetHtCapabilitiesInfo(), GetSupportedChannelWidth(), SetHtCapabilitiesInfo(), and SetSupportedChannelWidth().
m_txMaxNSpatialStreams
uint8_t ns3::HtCapabilities::m_txMaxNSpatialStreams private
transmit maximum number spatial streams
Definition at line 314 of file ht-capabilities.h.
Referenced by GetSupportedMcsSet2(), SetSupportedMcsSet(), and SetTxMaxNSpatialStreams().
m_txMcsSetDefined
uint8_t ns3::HtCapabilities::m_txMcsSetDefined private
transmit MCS set defined
Definition at line 312 of file ht-capabilities.h.
Referenced by GetSupportedMcsSet2(), SetSupportedMcsSet(), and SetTxMcsSetDefined().
m_txNdpCapable
uint8_t ns3::HtCapabilities::m_txNdpCapable private
transmit NDP capable
Definition at line 333 of file ht-capabilities.h.
Referenced by GetTxBfCapabilities(), and SetTxBfCapabilities().
m_txRxMcsSetUnequal
uint8_t ns3::HtCapabilities::m_txRxMcsSetUnequal private
transmit / receive MCS set unequal
Definition at line 313 of file ht-capabilities.h.
Referenced by GetSupportedMcsSet2(), SetSupportedMcsSet(), and SetTxRxMcsSetUnequal().
m_txSoundingPpdusCapable
uint8_t ns3::HtCapabilities::m_txSoundingPpdusCapable private
sounding PPDUS capable
Definition at line 357 of file ht-capabilities.h.
Referenced by GetAntennaSelectionCapabilities(), and SetAntennaSelectionCapabilities().
m_txStaggeredSoundingCapable
uint8_t ns3::HtCapabilities::m_txStaggeredSoundingCapable private
transmit staggered sounding capable
Definition at line 331 of file ht-capabilities.h.
Referenced by GetTxBfCapabilities(), and SetTxBfCapabilities().
m_txStbc
uint8_t ns3::HtCapabilities::m_txStbc private
transmit STBC
Definition at line 294 of file ht-capabilities.h.
Referenced by GetHtCapabilitiesInfo(), and SetHtCapabilitiesInfo().
m_txUnequalModulation
uint8_t ns3::HtCapabilities::m_txUnequalModulation private
transmit unequal modulation
Definition at line 315 of file ht-capabilities.h.
Referenced by GetSupportedMcsSet2(), SetSupportedMcsSet(), and SetTxUnequalModulation().
The documentation for this class was generated from the following files:
src/wifi/model/ht-capabilities.h
src/wifi/model/ht-capabilities.cc