ns-3: TestCounter Class Reference
TestCounter Class Reference
Traffic-control » traffic-control module tests | Test suites
Keep statistics based on traces.
Public Member Functions
TestCounter ()
Constructor.
virtual ~TestCounter ()
void ConnectTraces (Ptr< QueueDisc > qd)
Connect private methods to the queue disc traces.
Private Member Functions
void PacketDad (Ptr< const QueueDiscItem > item, const char *reason)
Update statistics after a packet has been dropped after dequeue.
void PacketDbe (Ptr< const QueueDiscItem > item, const char *reason)
Update statistics after a packet has been dropped before enqueue.
void PacketDequeued (Ptr< const QueueDiscItem > item)
Update statistics after a packet has been dequeued.
void PacketEnqueued (Ptr< const QueueDiscItem > item)
Update statistics after a packet has been enqueued.
Private Attributes
uint32_t m_nBytes
Number of queued bytes.
uint32_t m_nDadBytes
Number of packets dropped after dequeue.
uint32_t m_nDadPackets
Number of packets dropped after dequeue.
uint32_t m_nDbeBytes
Number of packets dropped before enqueue.
uint32_t m_nDbePackets
Number of packets dropped before enqueue.
uint32_t m_nPackets
Number of queued packets.
Friends
class QueueDiscTracesTestCase
Needs to access private members.
Detailed Description
Keep statistics based on traces.
Definition at line 207 of file queue-disc-traces-test-suite.cc.
Constructor & Destructor Documentation
TestCounter()
TestCounter::TestCounter ()
Constructor.
Definition at line 256 of file queue-disc-traces-test-suite.cc.
~TestCounter()
TestCounter::~TestCounter () virtual
Definition at line 266 of file queue-disc-traces-test-suite.cc.
Member Function Documentation
ConnectTraces()
void TestCounter::ConnectTraces (Ptr< QueueDisc > qd)
Connect private methods to the queue disc traces.
Parameters
qd the queue disc
Definition at line 300 of file queue-disc-traces-test-suite.cc.
References ns3::MakeCallback(), PacketDad(), PacketDbe(), PacketDequeued(), PacketEnqueued(), and ns3::ObjectBase::TraceConnectWithoutContext().
PacketDad()
void TestCounter::PacketDad (Ptr< const QueueDiscItem > item, const char * reason) private
Update statistics after a packet has been dropped after dequeue.
Parameters
item the dropped packet
reason the reason why the packet was dropped
Definition at line 293 of file queue-disc-traces-test-suite.cc.
References ns3::QueueItem::GetSize(), m_nDadBytes, and m_nDadPackets.
Referenced by ConnectTraces().
PacketDbe()
void TestCounter::PacketDbe (Ptr< const QueueDiscItem > item, const char * reason) private
Update statistics after a packet has been dropped before enqueue.
Parameters
item the dropped packet
reason the reason why the packet was dropped
Definition at line 285 of file queue-disc-traces-test-suite.cc.
References ns3::QueueItem::GetSize(), m_nDbeBytes, and m_nDbePackets.
Referenced by ConnectTraces().
PacketDequeued()
void TestCounter::PacketDequeued (Ptr< const QueueDiscItem > item) private
Update statistics after a packet has been dequeued.
Parameters
item the dequeued packet
Definition at line 278 of file queue-disc-traces-test-suite.cc.
References ns3::QueueItem::GetSize(), m_nBytes, and m_nPackets.
Referenced by ConnectTraces().
PacketEnqueued()
void TestCounter::PacketEnqueued (Ptr< const QueueDiscItem > item) private
Update statistics after a packet has been enqueued.
Parameters
item the enqueued packet
Definition at line 271 of file queue-disc-traces-test-suite.cc.
References ns3::QueueItem::GetSize(), m_nBytes, and m_nPackets.
Referenced by ConnectTraces().
Friends And Related Function Documentation
QueueDiscTracesTestCase
friend class QueueDiscTracesTestCase friend
Needs to access private members.
Definition at line 253 of file queue-disc-traces-test-suite.cc.
Member Data Documentation
m_nBytes
uint32_t TestCounter::m_nBytes private
Number of queued bytes.
Definition at line 247 of file queue-disc-traces-test-suite.cc.
Referenced by PacketDequeued(), and PacketEnqueued().
m_nDadBytes
uint32_t TestCounter::m_nDadBytes private
Number of packets dropped after dequeue.
Definition at line 251 of file queue-disc-traces-test-suite.cc.
Referenced by PacketDad().
m_nDadPackets
uint32_t TestCounter::m_nDadPackets private
Number of packets dropped after dequeue.
Definition at line 250 of file queue-disc-traces-test-suite.cc.
Referenced by PacketDad().
m_nDbeBytes
uint32_t TestCounter::m_nDbeBytes private
Number of packets dropped before enqueue.
Definition at line 249 of file queue-disc-traces-test-suite.cc.
Referenced by PacketDbe().
m_nDbePackets
uint32_t TestCounter::m_nDbePackets private
Number of packets dropped before enqueue.
Definition at line 248 of file queue-disc-traces-test-suite.cc.
Referenced by PacketDbe().
m_nPackets
uint32_t TestCounter::m_nPackets private
Number of queued packets.
Definition at line 246 of file queue-disc-traces-test-suite.cc.
Referenced by PacketDequeued(), and PacketEnqueued().
The documentation for this class was generated from the following file:
src/traffic-control/test/queue-disc-traces-test-suite.cc