ns-3: PointerAttributeTestCase Class Reference
PointerAttributeTestCase Class Reference
Public Member Functions
PointerAttributeTestCase (std::string description)
virtual ~PointerAttributeTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void NotifySource2 (double a, int b, float c)
Private Attributes
double m_got2
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 1272 of file attribute-test-suite.cc.
Constructor & Destructor Documentation
PointerAttributeTestCase()
PointerAttributeTestCase::PointerAttributeTestCase (std::string description)
Definition at line 1292 of file attribute-test-suite.cc.
~PointerAttributeTestCase()
virtual PointerAttributeTestCase::~PointerAttributeTestCase () inline virtual
Definition at line 1276 of file attribute-test-suite.cc.
Member Function Documentation
DoRun()
void PointerAttributeTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 1297 of file attribute-test-suite.cc.
References ns3::ObjectFactory::Create(), ns3::PointerValue::Get(), ns3::ObjectBase::GetAttribute(), ns3::Object::GetObject(), NS_TEST_ASSERT_MSG_EQ, NS_TEST_ASSERT_MSG_NE, ns3::ObjectFactory::Set(), ns3::ObjectBase::SetAttributeFailSafe(), ns3::ObjectFactory::SetTypeId(), and sample-rng-plot::x.
NotifySource2()
void PointerAttributeTestCase::NotifySource2 (double a, int b, float c) inline private
Definition at line 1282 of file attribute-test-suite.cc.
References m_got2, and NS_UNUSED.
Member Data Documentation
m_got2
double PointerAttributeTestCase::m_got2 private
Definition at line 1289 of file attribute-test-suite.cc.
Referenced by NotifySource2().
The documentation for this class was generated from the following file:
src/core/test/attribute-test-suite.cc