ns-3: ns3::AttributeChecker Class Reference
ns3::AttributeChecker Class Reference abstract
Core » Attributes
Represent the type of an attribute.
#include "attribute.h"
Public Member Functions
AttributeChecker ()
virtual ~AttributeChecker ()
virtual bool Check (const AttributeValue &value) const =0
virtual bool Copy (const AttributeValue &source, AttributeValue &destination) const =0
Copy the source to the destination.
virtual Ptr< AttributeValue > Create (void) const =0
Ptr< AttributeValue > CreateValidValue (const AttributeValue &value) const
Create a valid value from the argument value, or reinterpret the argument as a string.
virtual std::string GetUnderlyingTypeInformation (void) const =0
virtual std::string GetValueTypeName (void) const =0
virtual bool HasUnderlyingTypeInformation (void) const =0
Public Member Functions inherited from ns3::SimpleRefCount< AttributeChecker >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Detailed Description
Represent the type of an attribute.
Each type of attribute has an associated unique AttributeChecker subclass. The type of the subclass can be safely used by users to infer the type of the associated attribute. i.e., we expect binding authors to use the checker associated to an attribute to detect the type of the associated attribute.
Most subclasses of this base class are implemented by the ATTRIBUTE_HELPER_HEADER and ATTRIBUTE_HELPER_CPP macros.
Definition at line 166 of file attribute.h.
Constructor & Destructor Documentation
AttributeChecker()
ns3::AttributeChecker::AttributeChecker ()
Definition at line 48 of file attribute.cc.
~AttributeChecker()
ns3::AttributeChecker::~AttributeChecker () virtual
Definition at line 50 of file attribute.cc.
Member Function Documentation
Check()
virtual bool ns3::AttributeChecker::Check (const AttributeValue & value) const pure virtual
Parameters
[in] value A pointer to the value to check
Returns
true if the input value is both of the right type and if its value is within the requested range. Returns false otherwise.
Implemented in ns3::internal::ObjectPtrContainerChecker< T >, ns3::EnumChecker, ns3::EmptyAttributeChecker, and ns3::internal::PointerChecker< T >.
Referenced by CreateValidValue().
Copy()
virtual bool ns3::AttributeChecker::Copy (const AttributeValue & source, AttributeValue & destination) const pure virtual
Copy the source to the destination.
Parameters
[in] source Source AttributeValue
[out] destination Destination AttributeValue
Returns
true if copy was successful
Implemented in ns3::EnumChecker, ns3::internal::PointerChecker< T >, ns3::internal::ObjectPtrContainerChecker< T >, and ns3::EmptyAttributeChecker.
Create()
virtual Ptr<AttributeValue> ns3::AttributeChecker::Create (void) const pure virtual
Returns
a new instance of an AttributeValue (wrapper in an Attribute instance) which matches the type of the underlying attribute.
This method is typically used to create a temporary variable prior to calling Attribute::DeserializeFromString.
Implemented in ns3::internal::PointerChecker< T >, ns3::internal::ObjectPtrContainerChecker< T >, ns3::EnumChecker, and ns3::EmptyAttributeChecker.
Referenced by CreateValidValue().
CreateValidValue()
Ptr< AttributeValue > ns3::AttributeChecker::CreateValidValue (const AttributeValue & value) const
Create a valid value from the argument value, or reinterpret the argument as a string.
Parameters
[in] value The AttributeValue to check
Returns
Ptr to a valid value
Definition at line 54 of file attribute.cc.
References Check(), ns3::AttributeValue::Copy(), Create(), ns3::StringValue::Get(), and NS_LOG_FUNCTION.
GetUnderlyingTypeInformation()
virtual std::string ns3::AttributeChecker::GetUnderlyingTypeInformation (void) const pure virtual
Returns
a human-readable representation of information about the underlying C++ type.
Implemented in ns3::internal::PointerChecker< T >, ns3::internal::ObjectPtrContainerChecker< T >, ns3::EnumChecker, and ns3::EmptyAttributeChecker.
Referenced by ns3::cell_tooltip_callback(), and ns3::cell_tooltip_callback_config_default().
GetValueTypeName()
virtual std::string ns3::AttributeChecker::GetValueTypeName (void) const pure virtual
Returns
the c++ fully-qualified typename of the subclass of the ns3::AttributeValue base class which is associated to this checker.
A typical return value here is FooValue where Foo is the name of the type being wrapped.
Implemented in ns3::internal::PointerChecker< T >, ns3::internal::ObjectPtrContainerChecker< T >, ns3::EnumChecker, and ns3::EmptyAttributeChecker.
Referenced by ns3::cell_tooltip_callback(), and ns3::cell_tooltip_callback_config_default().
HasUnderlyingTypeInformation()
virtual bool ns3::AttributeChecker::HasUnderlyingTypeInformation (void) const pure virtual
Returns
true if this checker has information about the underlying C++ type, false otherwise.
If this method returns false, the return value of the GetUnderlyingTypeInformation method cannot be relied upon.
Implemented in ns3::internal::PointerChecker< T >, ns3::internal::ObjectPtrContainerChecker< T >, ns3::EnumChecker, and ns3::EmptyAttributeChecker.
Referenced by ns3::cell_tooltip_callback(), and ns3::cell_tooltip_callback_config_default().
The documentation for this class was generated from the following files:
src/core/model/attribute.h
src/core/model/attribute.cc