ns-3: Bug2843TestCase Class Reference
Bug2843TestCase Class Reference
Make sure that the correct channel width and center frequency have been set for OFDM basic rate transmissions and BSS channel widths larger than 20 MHz.
Public Member Functions
Bug2843TestCase ()
virtual ~Bug2843TestCase ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Types
typedef std::tuple< double, uint16_t, uint32_t, WifiModulationClass > FreqWidthSubbandModulationTuple
A tuple of {starting frequency, channelWidth, Number of subbands in SpectrumModel, modulation type}.
Private Member Functions
void SendPacketBurst (uint8_t numPackets, Ptr< NetDevice > sourceDevice, Address &destination) const
Triggers the arrival of a burst of 1000 Byte-long packets in the source device.
void StoreDistinctTuple (std::string context, Ptr< SpectrumSignalParameters > txParams)
Stores the distinct {starting frequency, channelWidth, Number of subbands in SpectrumModel, modulation type} tuples that have been used during the testcase run.
Private Attributes
uint16_t m_channelWidth
channel width (in MHz)
std::vector< FreqWidthSubbandModulationTuple > m_distinctTuples
vector of distinct {starting frequency, channelWidth, Number of subbands in SpectrumModel, modulation type} tuples
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Make sure that the correct channel width and center frequency have been set for OFDM basic rate transmissions and BSS channel widths larger than 20 MHz.
The scenario considers a UDP transmission between a 40 MHz 802.11ac station and a 40 MHz 802.11ac access point. All transmission parameters are checked so as to ensure that only 2 {starting frequency, channelWidth, Number of subbands in SpectrumModel, modulation type} tuples are used.
See Bug 2843
Definition at line 1347 of file wifi-test.cc.
Member Typedef Documentation
FreqWidthSubbandModulationTuple
typedef std::tuple<double, uint16_t, uint32_t, WifiModulationClass> Bug2843TestCase::FreqWidthSubbandModulationTuple private
A tuple of {starting frequency, channelWidth, Number of subbands in SpectrumModel, modulation type}.
Definition at line 1358 of file wifi-test.cc.
Constructor & Destructor Documentation
Bug2843TestCase()
Bug2843TestCase::Bug2843TestCase ()
Definition at line 1379 of file wifi-test.cc.
~Bug2843TestCase()
Bug2843TestCase::~Bug2843TestCase () virtual
Definition at line 1385 of file wifi-test.cc.
Member Function Documentation
DoRun()
void Bug2843TestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 1433 of file wifi-test.cc.
References ns3::ListPositionAllocator::Add(), ns3::SpectrumChannel::AddPropagationLossModel(), ns3::Config::Connect(), ns3::NodeContainer::Create(), ns3::NetDeviceContainer::Get(), m_distinctTuples, third::mac, ns3::MakeCallback(), third::mobility, NS_TEST_ASSERT_MSG_EQ, ns3::Seconds(), SendPacketBurst(), ns3::WifiPhyHelper::Set(), ns3::SpectrumWifiPhyHelper::SetChannel(), ns3::WifiPhyHelper::SetErrorRateModel(), ns3::FriisPropagationLossModel::SetFrequency(), ns3::SpectrumChannel::SetPropagationDelayModel(), StoreDistinctTuple(), third::wifi, ns3::WIFI_MOD_CLASS_OFDM, ns3::WIFI_MOD_CLASS_VHT, ns3::WIFI_PHY_STANDARD_80211ac, and third::wifiApNode.
SendPacketBurst()
void Bug2843TestCase::SendPacketBurst (uint8_t numPackets, Ptr< NetDevice > sourceDevice, Address & destination) const private
Triggers the arrival of a burst of 1000 Byte-long packets in the source device.
Parameters
numPackets number of packets in burst
sourceDevice pointer to the source NetDevice
destination address of the destination device
Definition at line 1422 of file wifi-test.cc.
References ns3::NetDevice::Send().
Referenced by DoRun().
StoreDistinctTuple()
void Bug2843TestCase::StoreDistinctTuple (std::string context, Ptr< SpectrumSignalParameters > txParams) private
Stores the distinct {starting frequency, channelWidth, Number of subbands in SpectrumModel, modulation type} tuples that have been used during the testcase run.
Parameters
context the context
txParams spectrum signal parameters set by transmitter
Definition at line 1390 of file wifi-test.cc.
References ns3::SpectrumModel::Begin(), ns3::Copy(), ns3::WifiTxVector::GetChannelWidth(), ns3::WifiTxVector::GetMode(), ns3::WifiMode::GetModulationClass(), ns3::SpectrumModel::GetNumBands(), ns3::SpectrumValue::GetSpectrumModel(), ns3::WifiPpdu::GetTxVector(), m_channelWidth, m_distinctTuples, ns3::WifiSpectrumSignalParameters::ppdu, and ns3::SpectrumSignalParameters::psd.
Referenced by DoRun().
Member Data Documentation
m_channelWidth
uint16_t Bug2843TestCase::m_channelWidth private
channel width (in MHz)
Definition at line 1376 of file wifi-test.cc.
Referenced by StoreDistinctTuple().
m_distinctTuples
std::vector<FreqWidthSubbandModulationTuple> Bug2843TestCase::m_distinctTuples private
vector of distinct {starting frequency, channelWidth, Number of subbands in SpectrumModel, modulation type} tuples
Definition at line 1359 of file wifi-test.cc.
Referenced by DoRun(), and StoreDistinctTuple().
The documentation for this class was generated from the following file:
src/wifi/test/wifi-test.cc