ns-3: ns3::SSScheduler Class Reference
ns3::SSScheduler Class Reference
WiMAX Models
#include "ss-scheduler.h"
Public Member Functions
SSScheduler (Ptr< SubscriberStationNetDevice > ss)
Constructor.
~SSScheduler (void)
void DoDispose (void)
Destructor implementation.
bool GetPollMe (void) const
Get the poll me value.
Ptr< PacketBurst > Schedule (uint16_t availableSymbols, WimaxPhy::ModulationType modulationType, MacHeaderType::HeaderType packetType, Ptr< WimaxConnection > &connection)
void SetPollMe (bool pollMe)
Set poll me value.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
SSScheduler (const SSScheduler &)
type conversion operator
SSScheduler & operator= (const SSScheduler &)
assignment operator
Ptr< WimaxConnection > SelectConnection (void)
Select connection.
Private Attributes
bool m_pollMe
poll me flag
Ptr< SubscriberStationNetDevice > m_ss
the subscriber station
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Parameters
SSScheduler class
Definition at line 41 of file ss-scheduler.h.
Constructor & Destructor Documentation
SSScheduler() [1/2]
ns3::SSScheduler::SSScheduler (Ptr< SubscriberStationNetDevice > ss)
Constructor.
Parameters
ss subscriber station device
Definition at line 48 of file ss-scheduler.cc.
~SSScheduler()
ns3::SSScheduler::~SSScheduler (void)
Definition at line 54 of file ss-scheduler.cc.
SSScheduler() [2/2]
ns3::SSScheduler::SSScheduler (const SSScheduler &) private
type conversion operator
Member Function Documentation
DoDispose()
void ns3::SSScheduler::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 59 of file ss-scheduler.cc.
References m_ss.
GetPollMe()
bool ns3::SSScheduler::GetPollMe (void) const
Get the poll me value.
Returns
the poll me flag
Definition at line 71 of file ss-scheduler.cc.
References m_pollMe.
GetTypeId()
TypeId ns3::SSScheduler::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 40 of file ss-scheduler.cc.
References ns3::TypeId::SetParent().
operator=()
SSScheduler& ns3::SSScheduler::operator= (const SSScheduler &) private
assignment operator
Returns
the SS scheduler
Schedule()
Ptr< PacketBurst > ns3::SSScheduler::Schedule (uint16_t availableSymbols, WimaxPhy::ModulationType modulationType, MacHeaderType::HeaderType packetType, Ptr< WimaxConnection > & connection)
Returns
a list of packet to be sent in the next opportunity
Parameters
availableSymbols the available resources in symbols
modulationType the used modulation
packetType the type of packets to select from
connection the connection from which packets will be selected
Definition at line 77 of file ss-scheduler.cc.
References ns3::Packet::GetSize(), m_ss, NS_ASSERT_MSG(), NS_LOG_INFO, SelectConnection(), and ns3::Cid::TRANSPORT.
SelectConnection()
Ptr< WimaxConnection > ns3::SSScheduler::SelectConnection (void) private
Select connection.
Returns
pointer to the wimax connection
Definition at line 167 of file ss-scheduler.cc.
References ns3::MacHeaderType::HEADER_TYPE_GENERIC, m_ss, ns3::MilliSeconds(), ns3::Simulator::Now(), NS_LOG_INFO, ns3::ServiceFlow::SF_TYPE_BE, ns3::ServiceFlow::SF_TYPE_NRTPS, ns3::ServiceFlow::SF_TYPE_RTPS, and ns3::ServiceFlow::SF_TYPE_UGS.
Referenced by Schedule().
SetPollMe()
void ns3::SSScheduler::SetPollMe (bool pollMe)
Set poll me value.
Parameters
pollMe the poll me flag
Definition at line 65 of file ss-scheduler.cc.
References m_pollMe.
Member Data Documentation
m_pollMe
bool ns3::SSScheduler::m_pollMe private
poll me flag
Definition at line 97 of file ss-scheduler.h.
Referenced by GetPollMe(), and SetPollMe().
m_ss
Ptr<SubscriberStationNetDevice> ns3::SSScheduler::m_ss private
the subscriber station
Definition at line 96 of file ss-scheduler.h.
Referenced by DoDispose(), Schedule(), and SelectConnection().
The documentation for this class was generated from the following files:
src/wimax/model/ss-scheduler.h
src/wimax/model/ss-scheduler.cc