ns-3: ns3::lorawan::EndDeviceLoraPhy Class Reference
ns3::lorawan::EndDeviceLoraPhy Class Reference abstract
Class representing a LoRa transceiver.
#include "end-device-lora-phy.h"
Public Types
enum State { SLEEP, STANDBY, TX, RX }
An enumeration of the possible states of an EndDeviceLoraPhy.
Public Types inherited from ns3::lorawan::LoraPhy
typedef Callback< void, Ptr< const Packet > > RxFailedCallback
Type definition for a callback for when a packet reception fails.
typedef Callback< void, Ptr< const Packet > > RxOkCallback
Type definition for a callback for when a packet is correctly received.
typedef Callback< void, Ptr< const Packet > > TxFinishedCallback
Type definition for a callback to call when a packet has finished sending.
Public Member Functions
EndDeviceLoraPhy ()
virtual ~EndDeviceLoraPhy ()
virtual void EndReceive (Ptr< Packet > packet, Ptr< LoraInterferenceHelper::Event > event)=0
Finish reception of a packet.
uint8_t GetSpreadingFactor (void)
Get the Spreading Factor this EndDevice is listening for.
EndDeviceLoraPhy::State GetState (void)
Return the state this End Device is currently in.
virtual bool IsOnFrequency (double frequencyMHz)
Whether this device is listening on the specified frequency or not.
virtual bool IsTransmitting (void)
Whether this device is transmitting or not.
void RegisterListener (EndDeviceLoraPhyListener *listener)
Add the input listener to the list of objects to be notified of PHY-level events.
virtual void Send (Ptr< Packet > packet, LoraTxParameters txParams, double frequencyMHz, double txPowerDbm)=0
Instruct the PHY to send a packet according to some parameters.
void SetFrequency (double frequencyMHz)
Set the frequency this EndDevice will listen on.
void SetSpreadingFactor (uint8_t sf)
Set the Spreading Factor this EndDevice will listen for.
virtual void StartReceive (Ptr< Packet > packet, double rxPowerDbm, uint8_t sf, Time duration, double frequencyMHz)=0
Start receiving a packet.
void SwitchToSleep (void)
Switch to the SLEEP state.
void SwitchToStandby (void)
Switch to the STANDBY state.
void UnregisterListener (EndDeviceLoraPhyListener *listener)
Remove the input listener from the list of objects to be notified of PHY-level events.
Public Member Functions inherited from ns3::lorawan::LoraPhy
LoraPhy ()
Constructor and destructor.
virtual ~LoraPhy ()
Ptr< LoraChannel > GetChannel (void) const
Get the channel instance associated to this PHY.
Ptr< NetDevice > GetDevice (void) const
Get the NetDevice associated to this PHY.
Ptr< MobilityModel > GetMobility ()
Get the mobility model associated to this PHY.
void SetChannel (Ptr< LoraChannel > channel)
Set the LoraChannel instance PHY transmits on.
void SetDevice (Ptr< NetDevice > device)
Set the NetDevice that owns this PHY.
void SetMobility (Ptr< MobilityModel > mobility)
Set the mobility model associated to this PHY.
void SetReceiveFailedCallback (RxFailedCallback callback)
Set the callback to call upon failed reception of a packet we were previously locked on.
void SetReceiveOkCallback (RxOkCallback callback)
Set the callback to call upon successful reception of a packet.
void SetTxFinishedCallback (TxFinishedCallback callback)
Set the callback to call after transmission of a packet.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::lorawan::LoraPhy
static Time GetOnAirTime (Ptr< Packet > packet, LoraTxParameters txParams)
Compute the time that a packet with certain characteristics will take to be transmitted.
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static const double sensitivity [6]
The sensitivity vector of this device to different SFs.
Protected Types
typedef std::vector< EndDeviceLoraPhyListener * > Listeners
typedef for a list of EndDeviceLoraPhyListener
typedef std::vector< EndDeviceLoraPhyListener * >::iterator ListenersI
typedef for a list of EndDeviceLoraPhyListener iterator
Protected Member Functions
void SwitchToRx ()
Switch to the RX state.
void SwitchToTx (double txPowerDbm)
Switch to the TX state.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes
double m_frequency
The frequency this device is listening on.
Listeners m_listeners
PHY listeners.
uint8_t m_sf
The Spreading Factor this device is listening for.
TracedValue< State > m_state
The state this PHY is currently in.
TracedCallback< Ptr< const Packet >, uint32_t > m_wrongFrequency
Trace source for when a packet is lost because it was transmitted on a frequency different from the one this EndDeviceLoraPhy was configured to listen on.
TracedCallback< Ptr< const Packet >, uint32_t > m_wrongSf
Trace source for when a packet is lost because it was using a SF different from the one this EndDeviceLoraPhy was configured to listen for.
Protected Attributes inherited from ns3::lorawan::LoraPhy
Ptr< LoraChannel > m_channel
The channel this PHY transmits on.
Ptr< NetDevice > m_device
The net device this PHY is attached to.
TracedCallback< Ptr< const Packet >, uint32_t > m_interferedPacket
The trace source fired when a packet cannot be correctly received because of interference.
LoraInterferenceHelper m_interference
The LoraInterferenceHelper.
TracedCallback< Ptr< const Packet > > m_phyRxBeginTrace
The trace source fired when a packet begins the reception process from the medium.
TracedCallback< Ptr< const Packet > > m_phyRxEndTrace
The trace source fired when a packet reception ends.
RxFailedCallback m_rxFailedCallback
The callback to perform upon failed reception of a packet we were locked on.
RxOkCallback m_rxOkCallback
The callback to perform upon correct reception of a packet.
TracedCallback< Ptr< const Packet >, uint32_t > m_startSending
associated to this PHY.
TracedCallback< Ptr< const Packet >, uint32_t > m_successfullyReceivedPacket
The trace source fired when a packet was correctly received.
TxFinishedCallback m_txFinishedCallback
The callback to perform upon the end of a transmission.
TracedCallback< Ptr< const Packet >, uint32_t > m_underSensitivity
The trace source fired when a packet cannot be received because its power is below the sensitivity threshold.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Class representing a LoRa transceiver.
This class inherits some functionality by LoraPhy, like the GetOnAirTime function, and extends it to represent the behavior of a LoRa chip, like the SX1272.
Additional behaviors featured in this class include a State member variable that expresses the current state of the device (SLEEP, TX, RX or STANDBY), and a frequency and Spreading Factor this device is listening to when in STANDBY mode. After transmission and reception, the device returns automatically to STANDBY mode. The decision of when to go into SLEEP mode is delegateed to an upper layer, which can modify the state of the device through the public SwitchToSleep and SwitchToStandby methods. In SLEEP mode, the device cannot lock on a packet and start reception.
Peculiarities about the error model and about how errors are handled are supposed to be handled by classes extending this one, like SimpleEndDeviceLoraPhy or SpectrumEndDeviceLoraPhy. These classes need to
Definition at line 104 of file end-device-lora-phy.h.
Member Typedef Documentation
Listeners
typedef std::vector<EndDeviceLoraPhyListener *> ns3::lorawan::EndDeviceLoraPhy::Listeners protected
typedef for a list of EndDeviceLoraPhyListener
Definition at line 265 of file end-device-lora-phy.h.
ListenersI
typedef std::vector<EndDeviceLoraPhyListener *>::iterator ns3::lorawan::EndDeviceLoraPhy::ListenersI protected
typedef for a list of EndDeviceLoraPhyListener iterator
Definition at line 269 of file end-device-lora-phy.h.
Member Enumeration Documentation
State
enum ns3::lorawan::EndDeviceLoraPhy::State
An enumeration of the possible states of an EndDeviceLoraPhy.
It makes sense to define a state for End Devices since there's only one demodulator which can either send, receive, stay idle or go in a deep sleep state.
Enumerator
SLEEP
The PHY layer is sleeping.
During sleep, the device is not listening for incoming messages.
STANDBY
The PHY layer is in STANDBY.
When the PHY is in this state, it's listening to the channel, and it's also ready to transmit data passed to it by the MAC layer.
TX
The PHY layer is sending a packet.
During transmission, the device cannot receive any packet or send any additional packet.
RX
The PHY layer is receiving a packet.
While the device is locked on an incoming packet, transmission is not possible.
Definition at line 113 of file end-device-lora-phy.h.
Constructor & Destructor Documentation
EndDeviceLoraPhy()
ns3::lorawan::EndDeviceLoraPhy::EndDeviceLoraPhy ()
Definition at line 70 of file end-device-lora-phy.cc.
~EndDeviceLoraPhy()
ns3::lorawan::EndDeviceLoraPhy::~EndDeviceLoraPhy () virtual
Definition at line 77 of file end-device-lora-phy.cc.
Member Function Documentation
EndReceive()
virtual void ns3::lorawan::EndDeviceLoraPhy::EndReceive (Ptr< Packet > packet, Ptr< LoraInterferenceHelper::Event > event) pure virtual
Finish reception of a packet.
This method is scheduled by StartReceive, based on the packet duration. By passing a LoraInterferenceHelper Event to this method, the class will be able to identify the packet that is being received among all those that were registered as interference by StartReceive.
Parameters
packet The received packet.
event The event that is tied to this packet in the LoraInterferenceHelper.
Implements ns3::lorawan::LoraPhy.
Implemented in ns3::lorawan::SimpleEndDeviceLoraPhy.
GetSpreadingFactor()
uint8_t ns3::lorawan::EndDeviceLoraPhy::GetSpreadingFactor (void)
Get the Spreading Factor this EndDevice is listening for.
Returns
The Spreading Factor we are listening for.
Definition at line 94 of file end-device-lora-phy.cc.
References m_sf.
GetState()
EndDeviceLoraPhy::State ns3::lorawan::EndDeviceLoraPhy::GetState (void)
Return the state this End Device is currently in.
Returns
The state this EndDeviceLoraPhy is currently in.
Definition at line 180 of file end-device-lora-phy.cc.
References m_state, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::lorawan::ClassAEndDeviceLorawanMac::CloseSecondReceiveWindow(), PhyConnectivityTest::DoRun(), and ns3::lorawan::ClassAEndDeviceLorawanMac::OpenSecondReceiveWindow().
GetTypeId()
TypeId ns3::lorawan::EndDeviceLoraPhy::GetTypeId (void) static
Definition at line 43 of file end-device-lora-phy.cc.
References m_state, m_wrongFrequency, m_wrongSf, ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
IsOnFrequency()
bool ns3::lorawan::EndDeviceLoraPhy::IsOnFrequency (double frequency) virtual
Whether this device is listening on the specified frequency or not.
Parameters
frequency The frequency to query.
Returns
true if the device is listening on that frequency, false otherwise.
Implements ns3::lorawan::LoraPhy.
Definition at line 106 of file end-device-lora-phy.cc.
References m_frequency.
Referenced by ns3::lorawan::SimpleEndDeviceLoraPhy::StartReceive().
IsTransmitting()
bool ns3::lorawan::EndDeviceLoraPhy::IsTransmitting (void) virtual
Whether this device is transmitting or not.
Returns
true if the device is currently transmitting a packet, false otherwise.
Implements ns3::lorawan::LoraPhy.
Definition at line 100 of file end-device-lora-phy.cc.
References m_state, and TX.
RegisterListener()
void ns3::lorawan::EndDeviceLoraPhy::RegisterListener (EndDeviceLoraPhyListener * listener)
Add the input listener to the list of objects to be notified of PHY-level events.
Parameters
listener the new listener
Definition at line 188 of file end-device-lora-phy.cc.
References m_listeners.
Send()
virtual void ns3::lorawan::EndDeviceLoraPhy::Send (Ptr< Packet > packet, LoraTxParameters txParams, double frequencyMHz, double txPowerDbm) pure virtual
Instruct the PHY to send a packet according to some parameters.
Parameters
packet The packet to send.
txParams The desired transmission parameters.
frequencyMHz The frequency on which to transmit.
txPowerDbm The power in dBm with which to transmit the packet.
Implements ns3::lorawan::LoraPhy.
Implemented in ns3::lorawan::SimpleEndDeviceLoraPhy.
SetFrequency()
void ns3::lorawan::EndDeviceLoraPhy::SetFrequency (double frequencyMHz)
Set the frequency this EndDevice will listen on.
Should a packet be transmitted on a frequency different than that the EndDeviceLoraPhy is listening on, the packet will be discarded.
Parameters
The frequency [MHz] to listen to.
Definition at line 112 of file end-device-lora-phy.cc.
References m_frequency.
Referenced by PhyConnectivityTest::Reset().
SetSpreadingFactor()
void ns3::lorawan::EndDeviceLoraPhy::SetSpreadingFactor (uint8_t sf)
Set the Spreading Factor this EndDevice will listen for.
The EndDeviceLoraPhy object will not be able to lock on transmissions that use a different SF than the one it's listening for.
Parameters
sf The spreading factor to listen for.
Definition at line 88 of file end-device-lora-phy.cc.
References m_sf.
Referenced by PhyConnectivityTest::DoRun(), and PhyConnectivityTest::Reset().
StartReceive()
virtual void ns3::lorawan::EndDeviceLoraPhy::StartReceive (Ptr< Packet > packet, double rxPowerDbm, uint8_t sf, Time duration, double frequencyMHz) pure virtual
Start receiving a packet.
This method is typically called by LoraChannel.
Parameters
packet The packet that is arriving at this PHY layer.
rxPowerDbm The power of the arriving packet (assumed to be constant for the whole reception).
sf The Spreading Factor of the arriving packet.
duration The on air time of this packet.
frequencyMHz The frequency this packet is being transmitted on.
Implements ns3::lorawan::LoraPhy.
Implemented in ns3::lorawan::SimpleEndDeviceLoraPhy.
SwitchToRx()
void ns3::lorawan::EndDeviceLoraPhy::SwitchToRx () protected
Switch to the RX state.
Definition at line 132 of file end-device-lora-phy.cc.
References m_listeners, m_state, NS_ASSERT, NS_LOG_FUNCTION_NOARGS, RX, and STANDBY.
Referenced by ns3::lorawan::SimpleEndDeviceLoraPhy::StartReceive().
SwitchToSleep()
void ns3::lorawan::EndDeviceLoraPhy::SwitchToSleep (void)
Switch to the SLEEP state.
Definition at line 164 of file end-device-lora-phy.cc.
References m_listeners, m_state, NS_ASSERT, NS_LOG_FUNCTION_NOARGS, SLEEP, and STANDBY.
Referenced by PhyConnectivityTest::DoRun().
SwitchToStandby()
void ns3::lorawan::EndDeviceLoraPhy::SwitchToStandby (void)
Switch to the STANDBY state.
Definition at line 118 of file end-device-lora-phy.cc.
References m_listeners, m_state, NS_LOG_FUNCTION_NOARGS, and STANDBY.
Referenced by ns3::lorawan::SimpleEndDeviceLoraPhy::EndReceive(), PhyConnectivityTest::Reset(), and ns3::lorawan::SimpleEndDeviceLoraPhy::Send().
SwitchToTx()
void ns3::lorawan::EndDeviceLoraPhy::SwitchToTx (double txPowerDbm) protected
Switch to the TX state.
Definition at line 148 of file end-device-lora-phy.cc.
References m_listeners, m_state, NS_ASSERT, NS_LOG_FUNCTION_NOARGS, RX, and TX.
Referenced by ns3::lorawan::SimpleEndDeviceLoraPhy::Send().
UnregisterListener()
void ns3::lorawan::EndDeviceLoraPhy::UnregisterListener (EndDeviceLoraPhyListener * listener)
Remove the input listener from the list of objects to be notified of PHY-level events.
Parameters
listener the listener to be unregistered
Definition at line 194 of file end-device-lora-phy.cc.
References m_listeners.
Member Data Documentation
m_frequency
double ns3::lorawan::EndDeviceLoraPhy::m_frequency protected
The frequency this device is listening on.
Definition at line 258 of file end-device-lora-phy.h.
Referenced by IsOnFrequency(), SetFrequency(), and ns3::lorawan::SimpleEndDeviceLoraPhy::StartReceive().
m_listeners
Listeners ns3::lorawan::EndDeviceLoraPhy::m_listeners protected
PHY listeners.
Definition at line 271 of file end-device-lora-phy.h.
Referenced by RegisterListener(), SwitchToRx(), SwitchToSleep(), SwitchToStandby(), SwitchToTx(), and UnregisterListener().
m_sf
uint8_t ns3::lorawan::EndDeviceLoraPhy::m_sf protected
The Spreading Factor this device is listening for.
Definition at line 260 of file end-device-lora-phy.h.
Referenced by GetSpreadingFactor(), SetSpreadingFactor(), and ns3::lorawan::SimpleEndDeviceLoraPhy::StartReceive().
m_state
TracedValue<State> ns3::lorawan::EndDeviceLoraPhy::m_state protected
The state this PHY is currently in.
Definition at line 254 of file end-device-lora-phy.h.
Referenced by GetState(), GetTypeId(), IsTransmitting(), ns3::lorawan::SimpleEndDeviceLoraPhy::Send(), ns3::lorawan::SimpleEndDeviceLoraPhy::StartReceive(), SwitchToRx(), SwitchToSleep(), SwitchToStandby(), and SwitchToTx().
m_wrongFrequency
TracedCallback<Ptr<const Packet>, uint32_t> ns3::lorawan::EndDeviceLoraPhy::m_wrongFrequency protected
Trace source for when a packet is lost because it was transmitted on a frequency different from the one this EndDeviceLoraPhy was configured to listen on.
Definition at line 252 of file end-device-lora-phy.h.
Referenced by GetTypeId(), and ns3::lorawan::SimpleEndDeviceLoraPhy::StartReceive().
m_wrongSf
TracedCallback<Ptr<const Packet>, uint32_t> ns3::lorawan::EndDeviceLoraPhy::m_wrongSf protected
Trace source for when a packet is lost because it was using a SF different from the one this EndDeviceLoraPhy was configured to listen for.
Definition at line 245 of file end-device-lora-phy.h.
Referenced by GetTypeId(), and ns3::lorawan::SimpleEndDeviceLoraPhy::StartReceive().
sensitivity
const double ns3::lorawan::EndDeviceLoraPhy::sensitivity static
Initial value:
=
{-124, -127, -130, -133, -135, -137}
The sensitivity vector of this device to different SFs.
Definition at line 227 of file end-device-lora-phy.h.
Referenced by ns3::lorawan::SimpleEndDeviceLoraPhy::StartReceive().
The documentation for this class was generated from the following files:
src/lorawan/model/end-device-lora-phy.h
src/lorawan/model/end-device-lora-phy.cc