ns-3: ns3::TcpHybla Class Reference
ns3::TcpHybla Class Reference
Internet » TCP » Congestion Control Algorithms.
Implementation of the TCP Hybla algorithm.
#include "tcp-hybla.h"
Public Member Functions
TcpHybla (const TcpHybla &sock)
Copy constructor.
TcpHybla (void)
Create an unbound tcp socket.
virtual ~TcpHybla (void) override
virtual Ptr< TcpCongestionOps > Fork () override
Copy the congestion control algorithm across sockets.
virtual std::string GetName () const override
Get the name of the congestion control algorithm.
virtual void PktsAcked (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked, const Time &rtt) override
Timing information on received ACK.
Public Member Functions inherited from ns3::TcpNewReno
TcpNewReno ()
TcpNewReno (const TcpNewReno &sock)
Copy constructor.
~TcpNewReno ()
virtual uint32_t GetSsThresh (Ptr< const TcpSocketState > tcb, uint32_t bytesInFlight)
Get the slow start threshold after a loss event.
virtual void IncreaseWindow (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
Try to increase the cWnd following the NewReno specification.
virtual void ReduceCwnd (Ptr< TcpSocketState > tcb)
Reduces congestion window on receipt of ECN Echo Flag.
Public Member Functions inherited from ns3::TcpCongestionOps
TcpCongestionOps ()
TcpCongestionOps (const TcpCongestionOps &other)
Copy constructor.
virtual ~TcpCongestionOps ()
virtual void CongControl (Ptr< TcpSocketState > tcb, const TcpRateOps::TcpRateConnection &rc, const TcpRateOps::TcpRateSample &rs)
Called when packets are delivered to update cwnd and pacing rate.
virtual void CongestionStateSet (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCongState_t newState)
Trigger events/calculations specific to a congestion state.
virtual void CwndEvent (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCAEvent_t event)
Trigger events/calculations on occurrence of congestion window event.
virtual bool HasCongControl () const
Returns true when Congestion Control Algorithm implements CongControl.
virtual void Init (Ptr< TcpSocketState > tcb)
Set configuration required by congestion control algorithm.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpNewReno
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpCongestionOps
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void CongestionAvoidance (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked) override
NewReno congestion avoidance.
virtual uint32_t SlowStart (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked) override
Tcp NewReno slow start algorithm.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void RecalcParam (const Ptr< TcpSocketState > &tcb)
Recalculate algorithm parameters.
Private Attributes
double m_cWndCnt
cWnd integer-to-float counter
TracedValue< double > m_rho
Rho parameter.
Time m_rRtt
Reference RTT.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implementation of the TCP Hybla algorithm.
The key idea behind TCP Hybla is to obtain for long RTT connections the same instantaneous transmission rate of a reference TCP connection with lower RTT. With analytical steps, it is shown that this goal can be achieved by modifying the time scale, in order for the throughput to be independent from the RTT. This independence is obtained through the use of a coefficient rho.
This coefficient is used to calculate both the slow start threshold and the congestion window when in slow start and in congestion avoidance, respectively.
More information: http://dl.acm.org/citation.cfm?id=2756518
Definition at line 46 of file tcp-hybla.h.
Constructor & Destructor Documentation
TcpHybla() [1/2]
ns3::TcpHybla::TcpHybla (void)
Create an unbound tcp socket.
Definition at line 49 of file tcp-hybla.cc.
References NS_LOG_FUNCTION.
TcpHybla() [2/2]
ns3::TcpHybla::TcpHybla (const TcpHybla & sock)
Copy constructor.
Parameters
sock the object to copy
Definition at line 57 of file tcp-hybla.cc.
References NS_LOG_FUNCTION.
~TcpHybla()
ns3::TcpHybla::~TcpHybla (void) override virtual
Definition at line 65 of file tcp-hybla.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CongestionAvoidance()
void ns3::TcpHybla::CongestionAvoidance (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked) override protected virtual
NewReno congestion avoidance.
During congestion avoidance, cwnd is incremented by roughly 1 full-sized segment per round-trip time (RTT).
Parameters
tcb internal congestion state
segmentsAcked count of segments acked
Reimplemented from ns3::TcpNewReno.
Definition at line 125 of file tcp-hybla.cc.
References ns3::TcpSocketState::GetCwndInSegments(), ns3::TcpSocketState::m_cWnd, m_cWndCnt, m_rho, ns3::TcpSocketState::m_segmentSize, ns3::TcpSocketState::m_ssThresh, NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_INFO.
Fork()
Ptr< TcpCongestionOps > ns3::TcpHybla::Fork () override virtual
Copy the congestion control algorithm across sockets.
Returns
a pointer of the copied object
Reimplemented from ns3::TcpNewReno.
Definition at line 167 of file tcp-hybla.cc.
GetName()
std::string ns3::TcpHybla::GetName () const override virtual
Get the name of the congestion control algorithm.
Returns
A string identifying the name
Reimplemented from ns3::TcpNewReno.
Definition at line 173 of file tcp-hybla.cc.
GetTypeId()
TypeId ns3::TcpHybla::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 31 of file tcp-hybla.cc.
References m_rho, m_rRtt, ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::MilliSeconds(), and ns3::TypeId::SetParent().
PktsAcked()
void ns3::TcpHybla::PktsAcked (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked, const Time & rtt) override virtual
Timing information on received ACK.
The function is called every time an ACK is received (only one time also for cumulative ACKs) and contains timing information. It is optional (congestion controls need not implement it) and the default implementation does nothing.
Parameters
tcb internal congestion state
segmentsAcked count of segments acked
rtt last rtt
Reimplemented from ns3::TcpCongestionOps.
Definition at line 82 of file tcp-hybla.cc.
References ns3::TcpSocketState::m_minRtt, NS_LOG_DEBUG, NS_LOG_FUNCTION, and RecalcParam().
Referenced by TcpHyblaIncrementTest::DoRun().
RecalcParam()
void ns3::TcpHybla::RecalcParam (const Ptr< TcpSocketState > & tcb) private
Recalculate algorithm parameters.
Parameters
tcb the socket state.
Definition at line 71 of file tcp-hybla.cc.
References ns3::Time::GetMilliSeconds(), ns3::TcpSocketState::m_minRtt, m_rho, m_rRtt, max, NS_ASSERT, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by PktsAcked().
SlowStart()
uint32_t ns3::TcpHybla::SlowStart (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked) override protected virtual
Tcp NewReno slow start algorithm.
Defined in RFC 5681 as
During slow start, a TCP increments cwnd by at most SMSS bytes for each ACK received that cumulatively acknowledges new data. Slow start ends when cwnd exceeds ssthresh (or, optionally, when it reaches it, as noted above) or when congestion is observed. While traditionally TCP implementations have increased cwnd by precisely SMSS bytes upon receipt of an ACK covering new data, we RECOMMEND that TCP implementations increase cwnd, per:
cwnd += min (N, SMSS) (2)
where N is the number of previously unacknowledged bytes acknowledged in the incoming ACK.
The ns-3 implementation respect the RFC definition. Linux does something different:
u32 tcp_slow_start(struct tcp_sock *tp, u32 acked)
  {
    u32 cwnd = tp->snd_cwnd + acked;
    if (cwnd > tp->snd_ssthresh)
      cwnd = tp->snd_ssthresh + 1;
    acked -= cwnd - tp->snd_cwnd;
    tp->snd_cwnd = min(cwnd, tp->snd_cwnd_clamp);
    return acked;
  }
As stated, we want to avoid the case when a cumulative ACK increases cWnd more than a segment size, but we keep count of how many segments we have ignored, and return them.
Parameters
tcb internal congestion state
segmentsAcked count of segments acked
Returns
the number of segments not considered for increasing the cWnd
Reimplemented from ns3::TcpNewReno.
Definition at line 95 of file tcp-hybla.cc.
References ns3::TcpSocketState::m_cWnd, m_rho, ns3::TcpSocketState::m_segmentSize, ns3::TcpSocketState::m_ssThresh, min, NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_INFO.
Member Data Documentation
m_cWndCnt
double ns3::TcpHybla::m_cWndCnt private
cWnd integer-to-float counter
Definition at line 81 of file tcp-hybla.h.
Referenced by CongestionAvoidance().
m_rho
TracedValue<double> ns3::TcpHybla::m_rho private
Rho parameter.
Definition at line 79 of file tcp-hybla.h.
Referenced by CongestionAvoidance(), GetTypeId(), RecalcParam(), and SlowStart().
m_rRtt
Time ns3::TcpHybla::m_rRtt private
Reference RTT.
Definition at line 80 of file tcp-hybla.h.
Referenced by GetTypeId(), and RecalcParam().
The documentation for this class was generated from the following files:
src/internet/model/tcp-hybla.h
src/internet/model/tcp-hybla.cc