ns-3: ns3::VirtualNetDevice Class Reference
ns3::VirtualNetDevice Class Reference
Virtual Device
A virtual device, similar to Linux TUN/TAP interfaces.
#include "virtual-net-device.h"
Public Types
typedef Callback< bool, Ptr< Packet >, const Address &, const Address &, uint16_t > SendCallback
Callback the be invoked when the VirtualNetDevice is asked to queue/transmit a packet.
Public Types inherited from ns3::NetDevice
typedef void(* LinkChangeTracedCallback) (void)
TracedCallback signature for link changed event.
enum PacketType {
PACKET_HOST = 1, NS3_PACKET_HOST = PACKET_HOST, PACKET_BROADCAST, NS3_PACKET_BROADCAST = PACKET_BROADCAST,
PACKET_MULTICAST, NS3_PACKET_MULTICAST = PACKET_MULTICAST, PACKET_OTHERHOST, NS3_PACKET_OTHERHOST = PACKET_OTHERHOST
}
Packet types are used as they are in Linux.
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address &, const Address &, enum PacketType > PromiscReceiveCallback
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address & > ReceiveCallback
Public Member Functions
VirtualNetDevice ()
virtual ~VirtualNetDevice ()
virtual void AddLinkChangeCallback (Callback< void > callback)
virtual Address GetAddress (void) const
virtual Address GetBroadcast (void) const
virtual Ptr< Channel > GetChannel (void) const
virtual uint32_t GetIfIndex (void) const
virtual uint16_t GetMtu (void) const
virtual Address GetMulticast (Ipv4Address multicastGroup) const
Make and return a MAC multicast address using the provided multicast group.
virtual Address GetMulticast (Ipv6Address addr) const
Get the MAC multicast address corresponding to the IPv6 address provided.
virtual Ptr< Node > GetNode (void) const
virtual bool IsBridge (void) const
Return true if the net device is acting as a bridge.
virtual bool IsBroadcast (void) const
virtual bool IsLinkUp (void) const
virtual bool IsMulticast (void) const
virtual bool IsPointToPoint (void) const
Return true if the net device is on a point-to-point link.
virtual bool NeedsArp (void) const
bool Receive (Ptr< Packet > packet, uint16_t protocol, const Address &source, const Address &destination, PacketType packetType)
virtual bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)
virtual bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
virtual void SetAddress (Address address)
Set the address of this interface.
virtual void SetIfIndex (const uint32_t index)
void SetIsPointToPoint (bool isPointToPoint)
Configure whether the virtual device is point-to-point.
bool SetMtu (const uint16_t mtu)
Configure the reported MTU for the virtual device.
void SetNeedsArp (bool needsArp)
Configure whether the virtual device needs ARP.
virtual void SetNode (Ptr< Node > node)
virtual void SetPromiscReceiveCallback (NetDevice::PromiscReceiveCallback cb)
virtual void SetReceiveCallback (NetDevice::ReceiveCallback cb)
void SetSendCallback (SendCallback transmitCb)
Set the user callback to be called when a L2 packet is to be transmitted.
void SetSupportsSendFrom (bool supportsSendFrom)
Configure whether the virtual device supports SendFrom.
virtual bool SupportsSendFrom () const
Public Member Functions inherited from ns3::NetDevice
virtual ~NetDevice ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::NetDevice
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Attributes
uint32_t m_index
bool m_isPointToPoint
TracedCallback< Ptr< const Packet > > m_macPromiscRxTrace
TracedCallback< Ptr< const Packet > > m_macRxTrace
TracedCallback< Ptr< const Packet > > m_macTxTrace
uint16_t m_mtu
Address m_myAddress
std::string m_name
bool m_needsArp
Ptr< Node > m_node
PromiscReceiveCallback m_promiscRxCallback
TracedCallback< Ptr< const Packet > > m_promiscSnifferTrace
ReceiveCallback m_rxCallback
SendCallback m_sendCb
TracedCallback< Ptr< const Packet > > m_snifferTrace
bool m_supportsSendFrom
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A virtual device, similar to Linux TUN/TAP interfaces.
A VirtualNetDevice is a "virtual" NetDevice implementation which delegates to a user callback (see method SetSendCallback()) the task of actually transmitting a packet. It also allows the user code to inject the packet as if it had been received by the VirtualNetDevice. Together, these features allow one to build tunnels. For instance, by transmitting packets into a UDP socket we end up building an IP-over-UDP-over-IP tunnel, or IP-over-IP tunnels.
The same thing could be accomplished by subclassing NetDevice directly. However, VirtualNetDevice is usually much simpler to program than a NetDevice subclass.
Definition at line 58 of file virtual-net-device.h.
Member Typedef Documentation
SendCallback
typedef Callback<bool, Ptr<Packet>, const Address&, const Address&, uint16_t> ns3::VirtualNetDevice::SendCallback
Callback the be invoked when the VirtualNetDevice is asked to queue/transmit a packet.
For more information, consult the documentation of NetDevice::SendFrom().
Definition at line 65 of file virtual-net-device.h.
Constructor & Destructor Documentation
VirtualNetDevice()
ns3::VirtualNetDevice::VirtualNetDevice ()
Definition at line 86 of file virtual-net-device.cc.
References m_isPointToPoint, m_needsArp, and m_supportsSendFrom.
~VirtualNetDevice()
ns3::VirtualNetDevice::~VirtualNetDevice () virtual
Definition at line 126 of file virtual-net-device.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
AddLinkChangeCallback()
void ns3::VirtualNetDevice::AddLinkChangeCallback (Callback< void > callback) virtual
Parameters
callback the callback to invoke
Add a callback invoked whenever the link status changes to UP. This callback is typically used by the IP/ARP layer to flush the ARP cache and by IPv6 stack to flush NDISC cache whenever the link goes up.
Implements ns3::NetDevice.
Definition at line 214 of file virtual-net-device.cc.
DoDispose()
void ns3::VirtualNetDevice::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 132 of file virtual-net-device.cc.
References ns3::Object::DoDispose(), m_node, and NS_LOG_FUNCTION_NOARGS.
GetAddress()
Address ns3::VirtualNetDevice::GetAddress (void) const virtual
Returns
the current Address of this interface.
Implements ns3::NetDevice.
Definition at line 190 of file virtual-net-device.cc.
References m_myAddress.
Referenced by Tunnel::N0SocketRecv(), Tunnel::N1SocketRecv(), Tunnel::N3SocketRecv(), Send(), and ns3::EpcPgwApplication::SendToTunDevice().
GetBroadcast()
Address ns3::VirtualNetDevice::GetBroadcast (void) const virtual
Returns
the broadcast address supported by this netdevice.
Calling this method is invalid if IsBroadcast returns not true.
Implements ns3::NetDevice.
Definition at line 225 of file virtual-net-device.cc.
GetChannel()
Ptr< Channel > ns3::VirtualNetDevice::GetChannel (void) const virtual
Returns
the channel this NetDevice is connected to. The value returned can be zero if the NetDevice is not yet connected to any channel or if the underlying NetDevice has no concept of a channel. i.e., callers must check for zero and be ready to handle it.
Implements ns3::NetDevice.
Definition at line 184 of file virtual-net-device.cc.
GetIfIndex()
uint32_t ns3::VirtualNetDevice::GetIfIndex (void) const virtual
Returns
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 178 of file virtual-net-device.cc.
References m_index.
GetMtu()
uint16_t ns3::VirtualNetDevice::GetMtu (void) const virtual
Returns
the link-level MTU in bytes for this interface.
This value is typically used by the IP layer to perform IP fragmentation when needed.
Implements ns3::NetDevice.
Definition at line 202 of file virtual-net-device.cc.
References m_mtu.
Referenced by GetTypeId().
GetMulticast() [1/2]
Address ns3::VirtualNetDevice::GetMulticast (Ipv4Address multicastGroup) const virtual
Make and return a MAC multicast address using the provided multicast group.
RFC 1112 says that an Ipv4 host group address is mapped to an Ethernet multicast address by placing the low-order 23-bits of the IP address into the low-order 23 bits of the Ethernet multicast address 01-00-5E-00-00-00 (hex). Similar RFCs exist for Ipv6 and Eui64 mappings. This method performs the multicast address creation function appropriate to the underlying MAC address of the device. This MAC address is encapsulated in an abstract Address to avoid dependencies on the exact MAC address format.
In the case of net devices that do not support multicast, clients are expected to test NetDevice::IsMulticast and avoid attempting to map multicast packets. Subclasses of NetDevice that do support multicasting are expected to override this method and provide an implementation appropriate to the particular device.
Parameters
multicastGroup The IP address for the multicast group destination of the packet.
Returns
The MAC multicast Address used to send packets to the provided multicast group.
Warning
Calling this method is invalid if IsMulticast returns not true.
See also
IsMulticast()
Implements ns3::NetDevice.
Definition at line 236 of file virtual-net-device.cc.
GetMulticast() [2/2]
Address ns3::VirtualNetDevice::GetMulticast (Ipv6Address addr) const virtual
Get the MAC multicast address corresponding to the IPv6 address provided.
Parameters
addr IPv6 address
Returns
the MAC multicast address
Warning
Calling this method is invalid if IsMulticast returns not true.
Implements ns3::NetDevice.
Definition at line 241 of file virtual-net-device.cc.
GetNode()
Ptr< Node > ns3::VirtualNetDevice::GetNode (void) const virtual
Returns
the node base class which contains this network interface.
When a subclass needs to get access to the underlying node base class to print the nodeid for example, it can invoke this method.
Implements ns3::NetDevice.
Definition at line 277 of file virtual-net-device.cc.
References m_node.
GetTypeId()
TypeId ns3::VirtualNetDevice::GetTypeId (void) static
Definition at line 39 of file virtual-net-device.cc.
References GetMtu(), m_macPromiscRxTrace, m_macRxTrace, m_macTxTrace, m_promiscSnifferTrace, m_snifferTrace, ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), SetMtu(), and ns3::TypeId::SetParent().
IsBridge()
bool ns3::VirtualNetDevice::IsBridge (void) const virtual
Return true if the net device is acting as a bridge.
Returns
value of m_isBridge flag
Implements ns3::NetDevice.
Definition at line 312 of file virtual-net-device.cc.
IsBroadcast()
bool ns3::VirtualNetDevice::IsBroadcast (void) const virtual
Returns
true if this interface supports a broadcast address, false otherwise.
Implements ns3::NetDevice.
Definition at line 219 of file virtual-net-device.cc.
IsLinkUp()
bool ns3::VirtualNetDevice::IsLinkUp (void) const virtual
Returns
true if link is up; false otherwise
Implements ns3::NetDevice.
Definition at line 208 of file virtual-net-device.cc.
IsMulticast()
bool ns3::VirtualNetDevice::IsMulticast (void) const virtual
Returns
value of m_isMulticast flag
Implements ns3::NetDevice.
Definition at line 231 of file virtual-net-device.cc.
IsPointToPoint()
bool ns3::VirtualNetDevice::IsPointToPoint (void) const virtual
Return true if the net device is on a point-to-point link.
Returns
value of m_isPointToPoint flag
Implements ns3::NetDevice.
Definition at line 248 of file virtual-net-device.cc.
References m_isPointToPoint.
NeedsArp()
bool ns3::VirtualNetDevice::NeedsArp (void) const virtual
Returns
true if ARP is needed, false otherwise.
Called by higher-layers to check if this NetDevice requires ARP to be used.
Implements ns3::NetDevice.
Definition at line 289 of file virtual-net-device.cc.
References m_needsArp.
Receive()
bool ns3::VirtualNetDevice::Receive (Ptr< Packet > packet, uint16_t protocol, const Address & source, const Address & destination, PacketType packetType)
Parameters
packet packet sent from below up to Network Device
protocol Protocol type
source the address of the sender of this packet.
destination the address of the receiver of this packet.
packetType type of packet received (broadcast/multicast/unicast/otherhost)
Returns
true if the packet was forwarded successfully, false otherwise.
Forward a "virtually received" packet up the node's protocol stack.
Definition at line 140 of file virtual-net-device.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_macPromiscRxTrace, m_macRxTrace, m_promiscRxCallback, m_promiscSnifferTrace, m_rxCallback, m_snifferTrace, and ns3::NetDevice::PACKET_OTHERHOST.
Referenced by Tunnel::N0SocketRecv(), Tunnel::N1SocketRecv(), Tunnel::N3SocketRecv(), and ns3::EpcPgwApplication::SendToTunDevice().
Send()
bool ns3::VirtualNetDevice::Send (Ptr< Packet > packet, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device to the specified destination Address
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 254 of file virtual-net-device.cc.
References GetAddress(), m_macTxTrace, and m_sendCb.
SendFrom()
bool ns3::VirtualNetDevice::SendFrom (Ptr< Packet > packet, const Address & source, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
source source mac address (so called "MAC spoofing")
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device with the specified source and destination Addresses.
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 265 of file virtual-net-device.cc.
References m_macTxTrace, m_sendCb, m_supportsSendFrom, and NS_ASSERT.
SetAddress()
void ns3::VirtualNetDevice::SetAddress (Address address) virtual
Set the address of this interface.
Parameters
address address to set
Implements ns3::NetDevice.
Definition at line 196 of file virtual-net-device.cc.
References m_myAddress.
Referenced by ns3::NoBackhaulEpcHelper::NoBackhaulEpcHelper(), and Tunnel::Tunnel().
SetIfIndex()
void ns3::VirtualNetDevice::SetIfIndex (const uint32_t index) virtual
Parameters
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 172 of file virtual-net-device.cc.
References m_index.
SetIsPointToPoint()
void ns3::VirtualNetDevice::SetIsPointToPoint (bool isPointToPoint)
Configure whether the virtual device is point-to-point.
Parameters
isPointToPoint the value that should be returned by the IsPointToPoint method for this instance.
Definition at line 113 of file virtual-net-device.cc.
References m_isPointToPoint.
SetMtu()
bool ns3::VirtualNetDevice::SetMtu (const uint16_t mtu) virtual
Configure the reported MTU for the virtual device.
Parameters
mtu MTU value to set
Returns
whether the MTU value was within legal bounds
Implements ns3::NetDevice.
Definition at line 119 of file virtual-net-device.cc.
References m_mtu.
Referenced by GetTypeId().
SetNeedsArp()
void ns3::VirtualNetDevice::SetNeedsArp (bool needsArp)
Configure whether the virtual device needs ARP.
Parameters
needsArp the the 'needs arp' value that will be returned by the NeedsArp() method. The method IsBroadcast() will also return this value.
Definition at line 101 of file virtual-net-device.cc.
References m_needsArp.
SetNode()
void ns3::VirtualNetDevice::SetNode (Ptr< Node > node) virtual
Parameters
node the node associated to this netdevice.
This method is called from ns3::Node::AddDevice.
Implements ns3::NetDevice.
Definition at line 283 of file virtual-net-device.cc.
References m_node.
SetPromiscReceiveCallback()
void ns3::VirtualNetDevice::SetPromiscReceiveCallback (NetDevice::PromiscReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received in promiscuous mode and must be forwarded to the higher layers.
Enables netdevice promiscuous mode and sets the callback that will handle promiscuous mode packets. Note, promiscuous mode packets means all packets, including those packets that can be sensed by the netdevice but which are intended to be received by other hosts.
Implements ns3::NetDevice.
Definition at line 301 of file virtual-net-device.cc.
References m_promiscRxCallback.
SetReceiveCallback()
void ns3::VirtualNetDevice::SetReceiveCallback (NetDevice::ReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received and must be forwarded to the higher layers.
Set the callback to be used to notify higher layers when a packet has been received.
Implements ns3::NetDevice.
Definition at line 295 of file virtual-net-device.cc.
References m_rxCallback.
SetSendCallback()
void ns3::VirtualNetDevice::SetSendCallback (SendCallback transmitCb)
Set the user callback to be called when a L2 packet is to be transmitted.
Parameters
transmitCb the new transmit callback
Definition at line 95 of file virtual-net-device.cc.
References m_sendCb.
Referenced by ns3::NoBackhaulEpcHelper::NoBackhaulEpcHelper(), Tunnel::Tunnel(), and ns3::NoBackhaulEpcHelper::DoDispose().
SetSupportsSendFrom()
void ns3::VirtualNetDevice::SetSupportsSendFrom (bool supportsSendFrom)
Configure whether the virtual device supports SendFrom.
Definition at line 107 of file virtual-net-device.cc.
References m_supportsSendFrom.
SupportsSendFrom()
bool ns3::VirtualNetDevice::SupportsSendFrom () const virtual
Returns
true if this interface supports a bridging mode, false otherwise.
Implements ns3::NetDevice.
Definition at line 307 of file virtual-net-device.cc.
References m_supportsSendFrom.
Member Data Documentation
m_index
uint32_t ns3::VirtualNetDevice::m_index private
Definition at line 166 of file virtual-net-device.h.
Referenced by GetIfIndex(), and SetIfIndex().
m_isPointToPoint
bool ns3::VirtualNetDevice::m_isPointToPoint private
Definition at line 170 of file virtual-net-device.h.
Referenced by VirtualNetDevice(), IsPointToPoint(), and SetIsPointToPoint().
m_macPromiscRxTrace
TracedCallback<Ptr<const Packet> > ns3::VirtualNetDevice::m_macPromiscRxTrace private
Definition at line 159 of file virtual-net-device.h.
Referenced by GetTypeId(), and Receive().
m_macRxTrace
TracedCallback<Ptr<const Packet> > ns3::VirtualNetDevice::m_macRxTrace private
Definition at line 157 of file virtual-net-device.h.
Referenced by GetTypeId(), and Receive().
m_macTxTrace
TracedCallback<Ptr<const Packet> > ns3::VirtualNetDevice::m_macTxTrace private
Definition at line 158 of file virtual-net-device.h.
Referenced by GetTypeId(), Send(), and SendFrom().
m_mtu
uint16_t ns3::VirtualNetDevice::m_mtu private
Definition at line 167 of file virtual-net-device.h.
Referenced by GetMtu(), and SetMtu().
m_myAddress
Address ns3::VirtualNetDevice::m_myAddress private
Definition at line 155 of file virtual-net-device.h.
Referenced by GetAddress(), and SetAddress().
m_name
std::string ns3::VirtualNetDevice::m_name private
Definition at line 165 of file virtual-net-device.h.
m_needsArp
bool ns3::VirtualNetDevice::m_needsArp private
Definition at line 168 of file virtual-net-device.h.
Referenced by VirtualNetDevice(), NeedsArp(), and SetNeedsArp().
m_node
Ptr<Node> ns3::VirtualNetDevice::m_node private
Definition at line 162 of file virtual-net-device.h.
Referenced by DoDispose(), GetNode(), and SetNode().
m_promiscRxCallback
PromiscReceiveCallback ns3::VirtualNetDevice::m_promiscRxCallback private
Definition at line 164 of file virtual-net-device.h.
Referenced by Receive(), and SetPromiscReceiveCallback().
m_promiscSnifferTrace
TracedCallback<Ptr<const Packet> > ns3::VirtualNetDevice::m_promiscSnifferTrace private
Definition at line 161 of file virtual-net-device.h.
Referenced by GetTypeId(), and Receive().
m_rxCallback
ReceiveCallback ns3::VirtualNetDevice::m_rxCallback private
Definition at line 163 of file virtual-net-device.h.
Referenced by Receive(), and SetReceiveCallback().
m_sendCb
SendCallback ns3::VirtualNetDevice::m_sendCb private
Definition at line 156 of file virtual-net-device.h.
Referenced by Send(), SendFrom(), and SetSendCallback().
m_snifferTrace
TracedCallback<Ptr<const Packet> > ns3::VirtualNetDevice::m_snifferTrace private
Definition at line 160 of file virtual-net-device.h.
Referenced by GetTypeId(), and Receive().
m_supportsSendFrom
bool ns3::VirtualNetDevice::m_supportsSendFrom private
Definition at line 169 of file virtual-net-device.h.
Referenced by VirtualNetDevice(), SendFrom(), SetSupportsSendFrom(), and SupportsSendFrom().
The documentation for this class was generated from the following files:
src/virtual-net-device/model/virtual-net-device.h
src/virtual-net-device/model/virtual-net-device.cc