ns-3: LteRlcUmTransmitterTestCase Class Reference
LteRlcUmTransmitterTestCase Class Reference
LTE Models » lte module tests | Test suites
Test case used by LteRlcUmTransmitterOneSduTestCase to create topology and to implement functionalities and check if data received corresponds to data sent.
#include "lte-test-rlc-um-transmitter.h"
Public Member Functions
LteRlcUmTransmitterTestCase ()
LteRlcUmTransmitterTestCase (std::string name)
Constructor.
virtual ~LteRlcUmTransmitterTestCase ()
void CheckDataReceived (Time time, std::string shouldReceived, std::string assertMsg)
Check data received function.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Protected Attributes
Ptr< LteTestMac > txMac
the MAC
Ptr< LteTestPdcp > txPdcp
the transmit PDCP
Ptr< LteRlc > txRlc
the RLC
Private Member Functions
void DoCheckDataReceived (std::string shouldReceived, std::string assertMsg)
Check data received function.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Detailed Description
Test case used by LteRlcUmTransmitterOneSduTestCase to create topology and to implement functionalities and check if data received corresponds to data sent.
Definition at line 56 of file lte-test-rlc-um-transmitter.h.
Constructor & Destructor Documentation
LteRlcUmTransmitterTestCase() [1/2]
LteRlcUmTransmitterTestCase::LteRlcUmTransmitterTestCase (std::string name)
Constructor.
Parameters
name the test name
Definition at line 56 of file lte-test-rlc-um-transmitter.cc.
LteRlcUmTransmitterTestCase() [2/2]
LteRlcUmTransmitterTestCase::LteRlcUmTransmitterTestCase ()
~LteRlcUmTransmitterTestCase()
LteRlcUmTransmitterTestCase::~LteRlcUmTransmitterTestCase () virtual
Definition at line 62 of file lte-test-rlc-um-transmitter.cc.
Member Function Documentation
CheckDataReceived()
void LteRlcUmTransmitterTestCase::CheckDataReceived (Time time, std::string shouldReceived, std::string assertMsg)
Check data received function.
Parameters
time the time to check
shouldReceived shoul dhave received indicator
assertMsg the assert message
Definition at line 105 of file lte-test-rlc-um-transmitter.cc.
References DoCheckDataReceived().
Referenced by LteRlcUmTransmitterOneSduTestCase::DoRun(), LteRlcUmTransmitterSegmentationTestCase::DoRun(), LteRlcUmTransmitterConcatenationTestCase::DoRun(), and LteRlcUmTransmitterReportBufferStatusTestCase::DoRun().
DoCheckDataReceived()
void LteRlcUmTransmitterTestCase::DoCheckDataReceived (std::string shouldReceived, std::string assertMsg) private
Check data received function.
Parameters
shouldReceived should have received indicator
assertMsg the assert message
Definition at line 111 of file lte-test-rlc-um-transmitter.cc.
References ns3::LteTestMac::GetDataReceived(), NS_TEST_ASSERT_MSG_EQ, and txMac.
Referenced by CheckDataReceived().
DoRun()
void LteRlcUmTransmitterTestCase::DoRun (void) protected virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Reimplemented in LteRlcUmTransmitterReportBufferStatusTestCase, LteRlcUmTransmitterConcatenationTestCase, LteRlcUmTransmitterSegmentationTestCase, and LteRlcUmTransmitterOneSduTestCase.
Definition at line 67 of file lte-test-rlc-um-transmitter.cc.
References ns3::LteTestMac::GetLteMacSapProvider(), ns3::LteRlc::GetLteMacSapUser(), ns3::LteRlc::GetLteRlcSapProvider(), ns3::LteTestPdcp::GetLteRlcSapUser(), ns3::LteRlc::SetLcId(), ns3::LteRlc::SetLteMacSapProvider(), ns3::LteTestMac::SetLteMacSapUser(), ns3::LteTestPdcp::SetLteRlcSapProvider(), ns3::LteRlc::SetLteRlcSapUser(), ns3::LteTestMac::SetRlcHeaderType(), ns3::LteRlc::SetRnti(), txMac, txPdcp, and txRlc.
Referenced by LteRlcUmTransmitterOneSduTestCase::DoRun(), LteRlcUmTransmitterSegmentationTestCase::DoRun(), LteRlcUmTransmitterConcatenationTestCase::DoRun(), and LteRlcUmTransmitterReportBufferStatusTestCase::DoRun().
Member Data Documentation
txMac
Ptr<LteTestMac> LteRlcUmTransmitterTestCase::txMac protected
the MAC
Definition at line 81 of file lte-test-rlc-um-transmitter.h.
Referenced by DoCheckDataReceived(), DoRun(), LteRlcUmTransmitterOneSduTestCase::DoRun(), LteRlcUmTransmitterSegmentationTestCase::DoRun(), LteRlcUmTransmitterConcatenationTestCase::DoRun(), and LteRlcUmTransmitterReportBufferStatusTestCase::DoRun().
txPdcp
Ptr<LteTestPdcp> LteRlcUmTransmitterTestCase::txPdcp protected
the transmit PDCP
Definition at line 79 of file lte-test-rlc-um-transmitter.h.
Referenced by DoRun(), LteRlcUmTransmitterOneSduTestCase::DoRun(), LteRlcUmTransmitterSegmentationTestCase::DoRun(), LteRlcUmTransmitterConcatenationTestCase::DoRun(), and LteRlcUmTransmitterReportBufferStatusTestCase::DoRun().
txRlc
Ptr<LteRlc> LteRlcUmTransmitterTestCase::txRlc protected
the RLC
Definition at line 80 of file lte-test-rlc-um-transmitter.h.
Referenced by DoRun().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-rlc-um-transmitter.h
src/lte/test/lte-test-rlc-um-transmitter.cc