ns-3: ns3::OmnetDataOutput::OmnetOutputCallback Class Reference
ns3::OmnetDataOutput::OmnetOutputCallback Class Reference
Statistics » Data Output
Class to generate OMNeT output.
Public Member Functions
OmnetOutputCallback (std::ostream *scalar)
Constructor.
void OutputSingleton (std::string context, std::string name, double val)
Generates a single data output.
void OutputSingleton (std::string context, std::string name, int val)
Generates a single data output.
void OutputSingleton (std::string context, std::string name, std::string val)
Generates a single data output.
void OutputSingleton (std::string context, std::string name, Time val)
Generates a single data output.
void OutputSingleton (std::string context, std::string name, uint32_t val)
Generates a single data output.
void OutputStatistic (std::string context, std::string name, const StatisticalSummary *statSum)
Generates data statistics.
Public Member Functions inherited from ns3::DataOutputCallback
virtual ~DataOutputCallback ()
Destructor.
Private Attributes
std::ostream * m_scalar
output stream
Detailed Description
Class to generate OMNeT output.
Definition at line 61 of file omnet-data-output.h.
Constructor & Destructor Documentation
OmnetOutputCallback()
OmnetDataOutput::OmnetOutputCallback::OmnetOutputCallback (std::ostream * scalar)
Constructor.
Parameters
scalar the output stream
Definition at line 150 of file omnet-data-output.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
OutputSingleton() [1/5]
void OmnetDataOutput::OmnetOutputCallback::OutputSingleton (std::string context, std::string name, double val) virtual
Generates a single data output.
Parameters
context the output context
name the output name
val the value
Implements ns3::DataOutputCallback.
Definition at line 216 of file omnet-data-output.cc.
References NS_LOG_FUNCTION.
OutputSingleton() [2/5]
void OmnetDataOutput::OmnetOutputCallback::OutputSingleton (std::string context, std::string name, int val) virtual
Generates a single data output.
Parameters
context the output context
name the output name
val the value
Implements ns3::DataOutputCallback.
Definition at line 186 of file omnet-data-output.cc.
References NS_LOG_FUNCTION.
OutputSingleton() [3/5]
void OmnetDataOutput::OmnetOutputCallback::OutputSingleton (std::string context, std::string name, std::string val) virtual
Generates a single data output.
Parameters
context the output context
name the output name
val the value
Implements ns3::DataOutputCallback.
Definition at line 231 of file omnet-data-output.cc.
References NS_LOG_FUNCTION.
OutputSingleton() [4/5]
void OmnetDataOutput::OmnetOutputCallback::OutputSingleton (std::string context, std::string name, Time val) virtual
Generates a single data output.
Parameters
context the output context
name the output name
val the value
Implements ns3::DataOutputCallback.
Definition at line 246 of file omnet-data-output.cc.
References ns3::Time::GetTimeStep(), and NS_LOG_FUNCTION.
OutputSingleton() [5/5]
void OmnetDataOutput::OmnetOutputCallback::OutputSingleton (std::string context, std::string name, uint32_t val) virtual
Generates a single data output.
Parameters
context the output context
name the output name
val the value
Implements ns3::DataOutputCallback.
Definition at line 201 of file omnet-data-output.cc.
References NS_LOG_FUNCTION.
OutputStatistic()
void OmnetDataOutput::OmnetOutputCallback::OutputStatistic (std::string context, std::string name, const StatisticalSummary * statSum) virtual
Generates data statistics.
Parameters
context the output context
name the output name
statSum the stats to print
Implements ns3::DataOutputCallback.
Definition at line 158 of file omnet-data-output.cc.
References ns3::StatisticalSummary::getCount(), ns3::StatisticalSummary::getMax(), ns3::StatisticalSummary::getMean(), ns3::StatisticalSummary::getMin(), ns3::StatisticalSummary::getSqrSum(), ns3::StatisticalSummary::getStddev(), ns3::StatisticalSummary::getSum(), ns3::isNaN(), and NS_LOG_FUNCTION.
Member Data Documentation
m_scalar
std::ostream* ns3::OmnetDataOutput::OmnetOutputCallback::m_scalar private
output stream
Definition at line 130 of file omnet-data-output.h.
The documentation for this class was generated from the following files:
src/stats/model/omnet-data-output.h
src/stats/model/omnet-data-output.cc