ns-3: ns3::tests::FullyQualifiedAddTestCase Class Reference
ns3::tests::FullyQualifiedAddTestCase Class Reference
Test suites | Core » Core module tests » Object Names test suite
Public Member Functions
FullyQualifiedAddTestCase ()
Constructor.
virtual ~FullyQualifiedAddTestCase ()
Destructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
virtual void DoTeardown (void)
Implementation to do any local setup required for this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test the Object Name Service can correctly use a fully qualified path to add associations.
Add (std::string name, Ptr<Object> object);
Definition at line 231 of file names-test-suite.cc.
Constructor & Destructor Documentation
FullyQualifiedAddTestCase()
ns3::tests::FullyQualifiedAddTestCase::FullyQualifiedAddTestCase ()
Constructor.
Definition at line 244 of file names-test-suite.cc.
~FullyQualifiedAddTestCase()
ns3::tests::FullyQualifiedAddTestCase::~FullyQualifiedAddTestCase () virtual
Destructor.
Definition at line 249 of file names-test-suite.cc.
Member Function Documentation
DoRun()
void ns3::tests::FullyQualifiedAddTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 259 of file names-test-suite.cc.
References ns3::Names::Add(), ns3::Names::FindName(), and NS_TEST_ASSERT_MSG_EQ.
DoTeardown()
void ns3::tests::FullyQualifiedAddTestCase::DoTeardown (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test teardown
Reimplemented from ns3::TestCase.
Definition at line 253 of file names-test-suite.cc.
References ns3::Names::Clear().
The documentation for this class was generated from the following file:
src/core/test/names-test-suite.cc