ns-3: grid.TimelineDataRange Class Reference
grid.TimelineDataRange Class Reference
TimelineDataRange.
Public Member Functions
def __init__ (self, name='')
Initializer.
def add_range (self, range)
Add range.
def get_all (self)
Get all ranges.
def get_bounds (self)
Get bounds.
def get_ranges (self, start, end)
Get selected ranges.
def get_ranges_bounds (self, start, end)
Get ranges bounds.
def sort (self)
Sort ranges.
Public Attributes
name
ranges
Private Member Functions
def __search (self, key)
Search.
Detailed Description
TimelineDataRange.
Definition at line 91 of file grid.py.
Constructor & Destructor Documentation
__init__()
def grid.TimelineDataRange.__init__ (self, name = '')
Initializer.
Parameters
self this object
name name
Returns
none
Definition at line 96 of file grid.py.
Member Function Documentation
__search()
def grid.TimelineDataRange.__search (self, key) private
Search.
Parameters
self this object
key key
Returns
index if found or -1 if not found
Definition at line 105 of file grid.py.
References grid.TimelineDataRange.ranges.
Referenced by grid.TimelineEvent.get_events(), grid.TimelineEvent.get_events_bounds(), grid.TimelineDataRange.get_ranges(), and grid.TimelineDataRange.get_ranges_bounds().
add_range()
def grid.TimelineDataRange.add_range (self, range)
Add range.
Parameters
self this object
range range
Returns
none
Definition at line 123 of file grid.py.
References grid.TimelineDataRange.ranges.
get_all()
def grid.TimelineDataRange.get_all (self)
Get all ranges.
Parameters
self this object
Returns
the ranges
Definition at line 130 of file grid.py.
References grid.TimelineDataRange.ranges.
get_bounds()
def grid.TimelineDataRange.get_bounds (self)
Get bounds.
Parameters
self this object
Returns
the bounds
Definition at line 176 of file grid.py.
References grid.TimelineDataRange.ranges, and return.
get_ranges()
def grid.TimelineDataRange.get_ranges (self, start, end)
Get selected ranges.
Parameters
self this object
start range start
end range end
Returns
the range or and empty list
Definition at line 136 of file grid.py.
References grid.TimelineDataRange.__search(), and grid.TimelineDataRange.ranges.
get_ranges_bounds()
def grid.TimelineDataRange.get_ranges_bounds (self, start, end)
Get ranges bounds.
Parameters
self this object
start range start
end range end
Returns
range
Definition at line 153 of file grid.py.
References grid.TimelineDataRange.__search(), grid.TimelineDataRange.ranges, and return.
sort()
def grid.TimelineDataRange.sort (self)
Sort ranges.
Parameters
self this object
Returns
none
Definition at line 170 of file grid.py.
References grid.TimelineDataRange.ranges.
Member Data Documentation
name
grid.TimelineDataRange.name
name
Definition at line 102 of file grid.py.
ranges
grid.TimelineDataRange.ranges
ranges
Definition at line 103 of file grid.py.
Referenced by grid.TimelineDataRange.__search(), grid.TimelineDataRange.add_range(), grid.TimelineDataRange.get_all(), grid.TimelineDataRange.get_bounds(), grid.Timeline.get_bounds(), grid.Timeline.get_range(), grid.Timeline.get_ranges(), grid.TimelineDataRange.get_ranges(), grid.TimelineDataRange.get_ranges_bounds(), grid.TimelineDataRange.sort(), and grid.Timeline.sort().
The documentation for this class was generated from the following file:
utils/grid.py