ns-3: anonymous_namespace{packet-test-suite.cc}::ATestTag< N > Class Template Reference
anonymous_namespace{packet-test-suite.cc}::ATestTag< N > Class Template Reference
Network » Network module unit tests | Test suites
Template class for Test tags.
Public Member Functions
ATestTag ()
ATestTag (uint8_t data)
Constructor.
virtual void Deserialize (TagBuffer buf)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer buf) const
Public Member Functions inherited from anonymous_namespace{packet-test-suite.cc}::ATestTagBase
ATestTagBase ()
ATestTagBase (uint8_t data)
Constructor.
int GetData () const
Get the tag data.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from anonymous_namespace{packet-test-suite.cc}::ATestTagBase
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Public Attributes inherited from anonymous_namespace{packet-test-suite.cc}::ATestTagBase
uint8_t m_data
Tag data.
bool m_error
Error in the Tag.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
template<int N>
class anonymous_namespace{packet-test-suite.cc}::ATestTag< N >
Template class for Test tags.
Note
Class internal to packet-test-suite.cc
Definition at line 86 of file packet-test-suite.cc.
Constructor & Destructor Documentation
ATestTag() [1/2]
template<int N> anonymous_namespace{packet-test-suite.cc}::ATestTag< N >::ATestTag () inline
Definition at line 131 of file packet-test-suite.cc.
ATestTag() [2/2]
template<int N> anonymous_namespace{packet-test-suite.cc}::ATestTag< N >::ATestTag (uint8_t data) inline
Constructor.
Parameters
data Tag data
Definition at line 135 of file packet-test-suite.cc.
Member Function Documentation
Deserialize()
template<int N> virtual void anonymous_namespace{packet-test-suite.cc}::ATestTag< N >::Deserialize (TagBuffer i) inline virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 117 of file packet-test-suite.cc.
References ns3::TagBuffer::ReadU8().
GetInstanceTypeId()
template<int N> virtual TypeId anonymous_namespace{packet-test-suite.cc}::ATestTag< N >::GetInstanceTypeId (void) const inline virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 104 of file packet-test-suite.cc.
GetSerializedSize()
template<int N> virtual uint32_t anonymous_namespace{packet-test-suite.cc}::ATestTag< N >::GetSerializedSize (void) const inline virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 107 of file packet-test-suite.cc.
GetTypeId()
template<int N> static TypeId anonymous_namespace{packet-test-suite.cc}::ATestTag< N >::GetTypeId (void) inline static
Register this type.
Returns
The TypeId.
Definition at line 93 of file packet-test-suite.cc.
References ns3::TypeId::SetParent().
Print()
template<int N> virtual void anonymous_namespace{packet-test-suite.cc}::ATestTag< N >::Print (std::ostream & os) const inline virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 128 of file packet-test-suite.cc.
Serialize()
template<int N> virtual void anonymous_namespace{packet-test-suite.cc}::ATestTag< N >::Serialize (TagBuffer i) const inline virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 110 of file packet-test-suite.cc.
References ns3::TagBuffer::WriteU8().
The documentation for this class was generated from the following file:
src/network/test/packet-test-suite.cc