ns-3: QueueDiscTracesTestCase Class Reference
QueueDiscTracesTestCase Class Reference
Traffic-control » traffic-control module tests | Test suites
Queue Disc Traces Test Case.
Public Member Functions
QueueDiscTracesTestCase ()
void CheckDroppedAfterDequeue (Ptr< QueueDisc > qd, uint32_t nDadPackets, uint32_t nDadBytes)
Check that packets/bytes dropped after dequeue are consistent with what is expected.
void CheckDroppedBeforeEnqueue (Ptr< QueueDisc > qd, uint32_t nDbePackets, uint32_t nDbeBytes)
Check that packets/bytes dropped before enqueue are consistent with what is expected.
void CheckQueued (Ptr< QueueDisc > qd, uint32_t nPackets, uint32_t nBytes)
Check that queued packets/bytes are consistent with what is expected.
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Attributes
std::map< Ptr< QueueDisc >, TestCounter > m_counter
counters for the queue discs
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Queue Disc Traces Test Case.
This test case makes use of a test queue disc acting as root queue disc and having a single child queue disc, which has a single DropTail queue. The Enqueue, Dequeue, DropBeforeEnqueue and DropAfterDequeue traces of both queue discs are connected to the methods of TestCounter objects that keep track of the amount of packets/bytes queued inside each queue disc and the cumulative amount of packets/bytes dropped before enqueue and after dequeue. A series of enqueue, dequeue and peek operations are performed on the root queue disc and both the statistics kept by the QueueDisc class and the values computed by the TestCounter objects are compared with the expected values.
Definition at line 325 of file queue-disc-traces-test-suite.cc.
Constructor & Destructor Documentation
QueueDiscTracesTestCase()
QueueDiscTracesTestCase::QueueDiscTracesTestCase ()
Definition at line 357 of file queue-disc-traces-test-suite.cc.
Member Function Documentation
CheckDroppedAfterDequeue()
void QueueDiscTracesTestCase::CheckDroppedAfterDequeue (Ptr< QueueDisc > qd, uint32_t nDadPackets, uint32_t nDadBytes)
Check that packets/bytes dropped after dequeue are consistent with what is expected.
Parameters
qd the queue disc
nDadPackets the expected number of packets
nDadBytes the expected number of bytes
Definition at line 393 of file queue-disc-traces-test-suite.cc.
References ns3::QueueDisc::GetStats(), m_counter, NS_TEST_EXPECT_MSG_EQ, ns3::QueueDisc::Stats::nTotalDroppedBytesAfterDequeue, and ns3::QueueDisc::Stats::nTotalDroppedPacketsAfterDequeue.
Referenced by DoRun().
CheckDroppedBeforeEnqueue()
void QueueDiscTracesTestCase::CheckDroppedBeforeEnqueue (Ptr< QueueDisc > qd, uint32_t nDbePackets, uint32_t nDbeBytes)
Check that packets/bytes dropped before enqueue are consistent with what is expected.
Parameters
qd the queue disc
nDbePackets the expected number of packets
nDbeBytes the expected number of bytes
Definition at line 377 of file queue-disc-traces-test-suite.cc.
References ns3::QueueDisc::GetStats(), m_counter, NS_TEST_EXPECT_MSG_EQ, ns3::QueueDisc::Stats::nTotalDroppedBytesBeforeEnqueue, and ns3::QueueDisc::Stats::nTotalDroppedPacketsBeforeEnqueue.
Referenced by DoRun().
CheckQueued()
void QueueDiscTracesTestCase::CheckQueued (Ptr< QueueDisc > qd, uint32_t nPackets, uint32_t nBytes)
Check that queued packets/bytes are consistent with what is expected.
Parameters
qd the queue disc
nPackets the expected number of packets
nBytes the expected number of bytes
Definition at line 363 of file queue-disc-traces-test-suite.cc.
References ns3::QueueDisc::GetNBytes(), ns3::QueueDisc::GetNPackets(), m_counter, and NS_TEST_EXPECT_MSG_EQ.
Referenced by DoRun().
DoRun()
void QueueDiscTracesTestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 409 of file queue-disc-traces-test-suite.cc.
References CheckDroppedAfterDequeue(), CheckDroppedBeforeEnqueue(), CheckQueued(), ns3::QueueDisc::Dequeue(), ns3::QueueDisc::Enqueue(), ns3::QueueDisc::GetQueueDiscClass(), ns3::QueueItem::GetSize(), ns3::Object::Initialize(), m_counter, NS_TEST_EXPECT_MSG_EQ, NS_TEST_EXPECT_MSG_NE, and ns3::QueueDisc::Peek().
Member Data Documentation
m_counter
std::map<Ptr<QueueDisc>,TestCounter> QueueDiscTracesTestCase::m_counter private
counters for the queue discs
Definition at line 354 of file queue-disc-traces-test-suite.cc.
Referenced by CheckDroppedAfterDequeue(), CheckDroppedBeforeEnqueue(), CheckQueued(), and DoRun().
The documentation for this class was generated from the following file:
src/traffic-control/test/queue-disc-traces-test-suite.cc