ns-3: QosFragmentationTestCase Class Reference
QosFragmentationTestCase Class Reference
Make sure that fragmentation works with QoS stations.
Public Member Functions
QosFragmentationTestCase ()
virtual ~QosFragmentationTestCase ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void Receive (std::string context, Ptr< const Packet > p, const Address &adr)
Receive function.
void Transmit (std::string context, Ptr< const Packet > p, double power)
Callback invoked when PHY transmits a packet.
Private Attributes
uint32_t m_fragments
transmitted fragments
uint32_t m_received
received packets
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Make sure that fragmentation works with QoS stations.
The scenario considers a TCP transmission between an 802.11n station and an 802.11n access point.
Definition at line 706 of file wifi-test.cc.
Constructor & Destructor Documentation
QosFragmentationTestCase()
QosFragmentationTestCase::QosFragmentationTestCase ()
Definition at line 736 of file wifi-test.cc.
~QosFragmentationTestCase()
QosFragmentationTestCase::~QosFragmentationTestCase () virtual
Definition at line 743 of file wifi-test.cc.
Member Function Documentation
DoRun()
void QosFragmentationTestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 769 of file wifi-test.cc.
References ns3::ListPositionAllocator::Add(), ns3::Node::AddApplication(), third::apDevices, third::channel, ns3::Config::Connect(), ns3::NodeContainer::Create(), ns3::NodeContainer::Get(), ns3::PointerValue::Get(), ns3::WifiNetDevice::GetAddress(), ns3::ObjectBase::GetAttribute(), ns3::WifiNetDevice::GetIfIndex(), ns3::WifiNetDevice::GetMac(), ns3::PacketSocketHelper::Install(), m_fragments, m_received, third::mac, ns3::MakeCallback(), ns3::MicroSeconds(), third::mobility, NS_ASSERT, NS_TEST_ASSERT_MSG_EQ, third::phy, Receive(), ns3::Seconds(), ns3::Config::Set(), ns3::ObjectBase::SetAttribute(), ns3::PacketSocketServer::SetLocal(), ns3::PacketSocketClient::SetRemote(), ns3::PacketSocketAddress::SetSingleDevice(), ns3::Application::SetStartTime(), ns3::Application::SetStopTime(), third::ssid, third::staDevices, Transmit(), third::wifi, ns3::WIFI_PHY_STANDARD_80211n_5GHZ, and third::wifiApNode.
Receive()
void QosFragmentationTestCase::Receive (std::string context, Ptr< const Packet > p, const Address & adr) private
Receive function.
Parameters
context the context
p the packet
adr the address
Definition at line 748 of file wifi-test.cc.
References ns3::Packet::GetSize(), and m_received.
Referenced by DoRun().
Transmit()
void QosFragmentationTestCase::Transmit (std::string context, Ptr< const Packet > p, double power) private
Callback invoked when PHY transmits a packet.
Parameters
context the context
p the packet
power the tx power
Definition at line 757 of file wifi-test.cc.
References ns3::Packet::GetSize(), ns3::WifiMacHeader::IsQosData(), m_fragments, NS_TEST_EXPECT_MSG_LT_OR_EQ, and ns3::Packet::PeekHeader().
Referenced by DoRun().
Member Data Documentation
m_fragments
uint32_t QosFragmentationTestCase::m_fragments private
transmitted fragments
Definition at line 717 of file wifi-test.cc.
Referenced by DoRun(), and Transmit().
m_received
uint32_t QosFragmentationTestCase::m_received private
received packets
Definition at line 716 of file wifi-test.cc.
Referenced by DoRun(), and Receive().
The documentation for this class was generated from the following file:
src/wifi/test/wifi-test.cc