ns-3: ns3::Histogram Class Reference
ns3::Histogram Class Reference
Class used to store data and make an histogram of the data frequency.
#include "histogram.h"
Public Member Functions
Histogram ()
Histogram (double binWidth)
Constructor.
void AddValue (double value)
Add a value to the histogram.
uint32_t GetBinCount (uint32_t index)
Get the number of data added to the bin.
double GetBinEnd (uint32_t index)
Returns the bin end, i.e., (index+1)*binWidth.
double GetBinStart (uint32_t index)
Returns the bin start, i.e., index*binWidth.
double GetBinWidth (uint32_t index) const
Returns the bin width.
uint32_t GetNBins () const
Returns the number of bins in the histogram.
void SerializeToXmlStream (std::ostream &os, uint16_t indent, std::string elementName) const
Serializes the results to an std::ostream in XML format.
void SetDefaultBinWidth (double binWidth)
Set the bin width.
Private Attributes
double m_binWidth
Bin width.
std::vector< uint32_t > m_histogram
Histogram data.
Detailed Description
Class used to store data and make an histogram of the data frequency.
Data are grouped in "bins", i.e., intervals. Each value is assigned to the bin according to the following formula: floor(value/binWidth). Hence, bin i groups the data from [i*binWidth, (i+1)binWidth).
This class only handles positive bins, i.e., it does not handles negative data.
Todo:
Add support for negative data.
Todo:
Add method(s) to estimate parameters from the histogram, see http://www.dspguide.com/ch2/4.htm
Definition at line 45 of file histogram.h.
Constructor & Destructor Documentation
Histogram() [1/2]
ns3::Histogram::Histogram (double binWidth)
Constructor.
Parameters
binWidth width of the histogram "bin".
Definition at line 94 of file histogram.cc.
References m_binWidth.
Histogram() [2/2]
ns3::Histogram::Histogram ()
Definition at line 99 of file histogram.cc.
References DEFAULT_BIN_WIDTH, and m_binWidth.
Member Function Documentation
AddValue()
void ns3::Histogram::AddValue (double value)
Add a value to the histogram.
Parameters
value the value to add
Definition at line 80 of file histogram.cc.
References m_binWidth, m_histogram, and NS_LOG_DEBUG.
Referenced by HistogramTestCase::DoRun(), and ns3::FlowMonitor::ReportLastRx().
GetBinCount()
uint32_t ns3::Histogram::GetBinCount (uint32_t index)
Get the number of data added to the bin.
Parameters
index the bin index
Returns
the number of data added to the bin
Definition at line 73 of file histogram.cc.
References m_histogram, and NS_ASSERT.
Referenced by HistogramTestCase::DoRun().
GetBinEnd()
double ns3::Histogram::GetBinEnd (uint32_t index)
Returns the bin end, i.e., (index+1)*binWidth.
Parameters
index the bin index
Returns
the bin start
Definition at line 54 of file histogram.cc.
References m_binWidth.
GetBinStart()
double ns3::Histogram::GetBinStart (uint32_t index)
Returns the bin start, i.e., index*binWidth.
Parameters
index the bin index
Returns
the bin start
Definition at line 48 of file histogram.cc.
References m_binWidth.
Referenced by HistogramTestCase::DoRun().
GetBinWidth()
double ns3::Histogram::GetBinWidth (uint32_t index) const
Returns the bin width.
Note that all the bins have the same width.
Parameters
index the bin index
Returns
the bin width
Definition at line 60 of file histogram.cc.
References m_binWidth.
Referenced by HistogramTestCase::DoRun().
GetNBins()
uint32_t ns3::Histogram::GetNBins () const
Returns the number of bins in the histogram.
Returns
the number of bins in the histogram
Definition at line 42 of file histogram.cc.
References m_histogram.
Referenced by HistogramTestCase::DoRun().
SerializeToXmlStream()
void ns3::Histogram::SerializeToXmlStream (std::ostream & os, uint16_t indent, std::string elementName) const
Serializes the results to an std::ostream in XML format.
Parameters
os the output stream
indent number of spaces to use as base indentation level
elementName name of the element to serialize.
Definition at line 105 of file histogram.cc.
References check-style::indent(), m_binWidth, and m_histogram.
SetDefaultBinWidth()
void ns3::Histogram::SetDefaultBinWidth (double binWidth)
Set the bin width.
Note that you can change the bin width only if the histogram is empty.
Parameters
binWidth the bin width
Definition at line 66 of file histogram.cc.
References m_binWidth, m_histogram, and NS_ASSERT.
Referenced by ns3::FlowMonitor::GetStatsForFlow().
Member Data Documentation
m_binWidth
double ns3::Histogram::m_binWidth private
Bin width.
Definition at line 117 of file histogram.h.
Referenced by Histogram(), AddValue(), GetBinEnd(), GetBinStart(), GetBinWidth(), SerializeToXmlStream(), and SetDefaultBinWidth().
m_histogram
std::vector<uint32_t> ns3::Histogram::m_histogram private
Histogram data.
Definition at line 116 of file histogram.h.
Referenced by AddValue(), GetBinCount(), GetNBins(), SerializeToXmlStream(), and SetDefaultBinWidth().
The documentation for this class was generated from the following files:
src/flow-monitor/model/histogram.h
src/flow-monitor/model/histogram.cc