ns-3: TracedValueCallbackTestCase::CheckTvCb< T > Class Template Reference
TracedValueCallbackTestCase::CheckTvCb< T > Class Template Reference
A class to check that the callback function typedef will actually connect to the TracedValue.
Public Member Functions
CheckTvCb (void)
Constructor.
template<typename U >
void Invoke (U cb)
Check the sink function against the actual TracedValue invocation.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
TracedValue< T > m_value
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
template<typename T>
class TracedValueCallbackTestCase::CheckTvCb< T >
A class to check that the callback function typedef will actually connect to the TracedValue.
Definition at line 124 of file traced-value-callback-typedef-test-suite.cc.
Constructor & Destructor Documentation
CheckTvCb()
template<typename T > TracedValueCallbackTestCase::CheckTvCb< T >::CheckTvCb (void) inline
Constructor.
Definition at line 130 of file traced-value-callback-typedef-test-suite.cc.
Member Function Documentation
GetTypeId()
template<typename T > static TypeId TracedValueCallbackTestCase::CheckTvCb< T >::GetTypeId (void) inline static
Register this type.
Definition at line 133 of file traced-value-callback-typedef-test-suite.cc.
References ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
Invoke()
template<typename T > template<typename U > void TracedValueCallbackTestCase::CheckTvCb< T >::Invoke (U cb) inline
Check the sink function against the actual TracedValue invocation.
We connect the TracedValue to the sink. If the types aren't compatible, the connection will fail.
Just to make sure, we increment the TracedValue, which calls the sink..
Definition at line 156 of file traced-value-callback-typedef-test-suite.cc.
References anonymous_namespace{traced-value-callback-typedef-test-suite.cc}::g_Result, and ns3::MakeCallback().
Member Data Documentation
m_value
template<typename T > TracedValue<T> TracedValueCallbackTestCase::CheckTvCb< T >::m_value private
Definition at line 126 of file traced-value-callback-typedef-test-suite.cc.
The documentation for this class was generated from the following file:
src/test/traced/traced-value-callback-typedef-test-suite.cc