ns-3: Ns3TcpStateTestCase Class Reference
Ns3TcpStateTestCase Class Reference
Public Member Functions
Ns3TcpStateTestCase ()
Ns3TcpStateTestCase (uint32_t testCase)
virtual ~Ns3TcpStateTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
virtual void DoSetup (void)
Implementation to do any local setup required for this TestCase.
virtual void DoTeardown (void)
Implementation to do any local setup required for this TestCase.
void Ipv4L3Rx (std::string context, Ptr< const Packet > packet, Ptr< Ipv4 > ipv4, uint32_t interface)
void Ipv4L3Tx (std::string context, Ptr< const Packet > packet, Ptr< Ipv4 > ipv4, uint32_t interface)
void StartFlow (Ptr< Socket > localSocket, Ipv4Address servAddress, uint16_t servPort)
void WriteUntilBufferFull (Ptr< Socket > localSocket, uint32_t txSpace)
Private Attributes
uint32_t m_currentTxBytes
bool m_needToClose
PcapFile m_pcapFile
std::string m_pcapFilename
uint32_t m_testCase
uint32_t m_totalTxBytes
bool m_writeLogging
bool m_writeResults
bool m_writeVectors
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 70 of file ns3tcp-state-test-suite.cc.
Constructor & Destructor Documentation
Ns3TcpStateTestCase() [1/2]
Ns3TcpStateTestCase::Ns3TcpStateTestCase ()
Definition at line 103 of file ns3tcp-state-test-suite.cc.
Ns3TcpStateTestCase() [2/2]
Ns3TcpStateTestCase::Ns3TcpStateTestCase (uint32_t testCase)
Definition at line 115 of file ns3tcp-state-test-suite.cc.
~Ns3TcpStateTestCase()
virtual Ns3TcpStateTestCase::~Ns3TcpStateTestCase () inline virtual
Definition at line 75 of file ns3tcp-state-test-suite.cc.
Member Function Documentation
DoRun()
void Ns3TcpStateTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 298 of file ns3tcp-state-test-suite.cc.
References ns3::NodeContainer::Add(), ns3::Ipv4AddressHelper::Assign(), ns3::Socket::Bind(), ns3::Config::Connect(), ns3::NodeContainer::Create(), ns3::AsciiTraceHelperForDevice::EnableAsciiAll(), ns3::PcapHelperForDevice::EnablePcapAll(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::OutputStreamWrapper::GetStream(), ns3::TrafficControlHelper::Install(), ns3::PointToPointHelper::Install(), ns3::InternetStackHelper::InstallAll(), Ipv4L3Rx(), Ipv4L3Tx(), ns3::LOG_LEVEL_DEBUG, ns3::LOG_LEVEL_INFO, ns3::LOG_PREFIX_FUNC, ns3::LogComponentEnable(), ns3::LogComponentEnableAll(), m_needToClose, m_testCase, m_totalTxBytes, m_writeLogging, m_writeResults, ns3::MakeCallback(), n1n2, NS_FATAL_ERROR, ns3::Seconds(), ns3::Ipv4AddressHelper::SetBase(), ns3::PointToPointHelper::SetChannelAttribute(), ns3::Config::SetDefault(), ns3::PointToPointHelper::SetDeviceAttribute(), ns3::ReceiveListErrorModel::SetList(), ns3::TrafficControlHelper::SetRootQueueDisc(), sink, ns3::ApplicationContainer::Start(), StartFlow(), and ns3::ApplicationContainer::Stop().
DoSetup()
void Ns3TcpStateTestCase::DoSetup (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test setup before DoRun is invoked.
Reimplemented from ns3::TestCase.
Definition at line 128 of file ns3tcp-state-test-suite.cc.
References ns3::TestCase::CreateDataDirFilename(), ns3::PcapFile::GetDataLinkType(), ns3::PcapFile::Init(), m_pcapFile, m_pcapFilename, m_testCase, m_writeVectors, NS_ABORT_MSG_UNLESS, NS_LOG_INFO, ns3::PcapFile::Open(), PCAP_LINK_TYPE, and PCAP_SNAPLEN.
DoTeardown()
void Ns3TcpStateTestCase::DoTeardown (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test teardown
Reimplemented from ns3::TestCase.
Definition at line 154 of file ns3tcp-state-test-suite.cc.
References ns3::PcapFile::Close(), and m_pcapFile.
Ipv4L3Rx()
void Ns3TcpStateTestCase::Ipv4L3Rx (std::string context, Ptr< const Packet > packet, Ptr< Ipv4 > ipv4, uint32_t interface) private
Definition at line 160 of file ns3tcp-state-test-suite.cc.
References ns3::Packet::Copy(), NS_LOG_DEBUG, and ns3::Packet::RemoveHeader().
Referenced by DoRun().
Ipv4L3Tx()
void Ns3TcpStateTestCase::Ipv4L3Tx (std::string context, Ptr< const Packet > packet, Ptr< Ipv4 > ipv4, uint32_t interface) private
Definition at line 172 of file ns3tcp-state-test-suite.cc.
References ns3::Packet::Copy(), ns3::Packet::CopyData(), ns3::Time::GetMicroSeconds(), ns3::TestCase::IsStatusSuccess(), m_pcapFile, m_writeVectors, ns3::Now(), NS_LOG_DEBUG, NS_LOG_INFO, NS_TEST_EXPECT_MSG_EQ, PCAP_SNAPLEN, ns3::PcapFile::Read(), ns3::Packet::RemoveHeader(), and ns3::PcapFile::Write().
Referenced by DoRun().
StartFlow()
void Ns3TcpStateTestCase::StartFlow (Ptr< Socket > localSocket, Ipv4Address servAddress, uint16_t servPort) private
Definition at line 276 of file ns3tcp-state-test-suite.cc.
References ns3::Socket::Connect(), ns3::Time::GetSeconds(), ns3::Socket::GetTxAvailable(), m_writeLogging, ns3::MakeCallback(), ns3::Now(), ns3::Socket::SetSendCallback(), and WriteUntilBufferFull().
Referenced by DoRun().
WriteUntilBufferFull()
void Ns3TcpStateTestCase::WriteUntilBufferFull (Ptr< Socket > localSocket, uint32_t txSpace) private
Definition at line 239 of file ns3tcp-state-test-suite.cc.
References ns3::Socket::Close(), ns3::Time::GetSeconds(), ns3::Socket::GetTxAvailable(), m_currentTxBytes, m_needToClose, m_totalTxBytes, m_writeLogging, min, ns3::Now(), NS_ASSERT, and ns3::Socket::Send().
Referenced by StartFlow().
Member Data Documentation
m_currentTxBytes
uint32_t Ns3TcpStateTestCase::m_currentTxBytes private
Definition at line 88 of file ns3tcp-state-test-suite.cc.
Referenced by WriteUntilBufferFull().
m_needToClose
bool Ns3TcpStateTestCase::m_needToClose private
Definition at line 92 of file ns3tcp-state-test-suite.cc.
Referenced by DoRun(), and WriteUntilBufferFull().
m_pcapFile
PcapFile Ns3TcpStateTestCase::m_pcapFile private
Definition at line 85 of file ns3tcp-state-test-suite.cc.
Referenced by DoSetup(), DoTeardown(), and Ipv4L3Tx().
m_pcapFilename
std::string Ns3TcpStateTestCase::m_pcapFilename private
Definition at line 84 of file ns3tcp-state-test-suite.cc.
Referenced by DoSetup().
m_testCase
uint32_t Ns3TcpStateTestCase::m_testCase private
Definition at line 86 of file ns3tcp-state-test-suite.cc.
Referenced by DoRun(), and DoSetup().
m_totalTxBytes
uint32_t Ns3TcpStateTestCase::m_totalTxBytes private
Definition at line 87 of file ns3tcp-state-test-suite.cc.
Referenced by DoRun(), and WriteUntilBufferFull().
m_writeLogging
bool Ns3TcpStateTestCase::m_writeLogging private
Definition at line 91 of file ns3tcp-state-test-suite.cc.
Referenced by DoRun(), StartFlow(), and WriteUntilBufferFull().
m_writeResults
bool Ns3TcpStateTestCase::m_writeResults private
Definition at line 90 of file ns3tcp-state-test-suite.cc.
Referenced by DoRun().
m_writeVectors
bool Ns3TcpStateTestCase::m_writeVectors private
Definition at line 89 of file ns3tcp-state-test-suite.cc.
Referenced by DoSetup(), and Ipv4L3Tx().
The documentation for this class was generated from the following file:
src/test/ns3tcp/ns3tcp-state-test-suite.cc