ns-3: ns3::dsr::DsrOptionAckHeader Class Reference
ns3::dsr::DsrOptionAckHeader Class Reference
DSR Routing
Acknowledgement (ACK) Message Format.
#include "dsr-option-header.h"
Public Member Functions
DsrOptionAckHeader ()
Constructor.
virtual ~DsrOptionAckHeader ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
uint16_t GetAckId () const
Set the Ack id number.
virtual Alignment GetAlignment () const
Get the Alignment requirement of this option header.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
Ipv4Address GetRealDst () const
Get Error source ip address.
Ipv4Address GetRealSrc () const
Get Error source ip address.
virtual uint32_t GetSerializedSize () const
Get the serialized size of the packet.
virtual void Print (std::ostream &os) const
Print some information about the packet.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetAckId (uint16_t identification)
Set the Ack id number.
void SetRealDst (Ipv4Address realDstAddress)
Set Error source ip address.
void SetRealSrc (Ipv4Address realSrcAddress)
Set Error source ip address.
Public Member Functions inherited from ns3::dsr::DsrOptionHeader
DsrOptionHeader ()
Constructor.
virtual ~DsrOptionHeader ()
Destructor.
uint8_t GetLength () const
Get the option length.
uint8_t GetType () const
Get the type of the option.
void SetLength (uint8_t length)
Set the option length.
void SetType (uint8_t type)
Set the type of the option.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::dsr::DsrOptionHeader
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint16_t m_identification
identification field
Ipv4Address m_realDstAddress
ack destination address
Ipv4Address m_realSrcAddress
ack source address
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Acknowledgement (ACK) Message Format.
Header of Dsr Option ack.
 |      0        |      1        |      2        |      3        |
 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |  Option Type |  Opt Data Len |         Identification         |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                        ACK Source Address                     |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                     ACK Destination Address                   |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 1253 of file dsr-option-header.h.
Constructor & Destructor Documentation
DsrOptionAckHeader()
ns3::dsr::DsrOptionAckHeader::DsrOptionAckHeader ()
Constructor.
Definition at line 1124 of file dsr-option-header.cc.
References ns3::dsr::DsrOptionHeader::SetLength(), and ns3::dsr::DsrOptionHeader::SetType().
~DsrOptionAckHeader()
ns3::dsr::DsrOptionAckHeader::~DsrOptionAckHeader () virtual
Destructor.
Definition at line 1131 of file dsr-option-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::dsr::DsrOptionAckHeader::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start Buffer iterator
Returns
size of the packet
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 1189 of file dsr-option-header.cc.
References GetSerializedSize(), m_identification, m_realDstAddress, m_realSrcAddress, ns3::ReadFrom(), ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU8(), ns3::dsr::DsrOptionHeader::SetLength(), ns3::dsr::DsrOptionHeader::SetType(), and visualizer.core::start().
GetAckId()
uint16_t ns3::dsr::DsrOptionAckHeader::GetAckId () const
Set the Ack id number.
Returns
request id number
Definition at line 1140 of file dsr-option-header.cc.
References m_identification.
Referenced by DsrAckHeaderTest::DoRun(), and ns3::dsr::DsrOptionAck::Process().
GetAlignment()
DsrOptionHeader::Alignment ns3::dsr::DsrOptionAckHeader::GetAlignment () const virtual
Get the Alignment requirement of this option header.
Returns
The required alignment
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 1202 of file dsr-option-header.cc.
GetInstanceTypeId()
TypeId ns3::dsr::DsrOptionAckHeader::GetInstanceTypeId () const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 1119 of file dsr-option-header.cc.
References GetTypeId().
GetRealDst()
Ipv4Address ns3::dsr::DsrOptionAckHeader::GetRealDst () const
Get Error source ip address.
Returns
The real dst address
Definition at line 1160 of file dsr-option-header.cc.
References m_realDstAddress.
Referenced by DsrAckHeaderTest::DoRun(), and ns3::dsr::DsrOptionAck::Process().
GetRealSrc()
Ipv4Address ns3::dsr::DsrOptionAckHeader::GetRealSrc () const
Get Error source ip address.
Returns
The real source address
Definition at line 1150 of file dsr-option-header.cc.
References m_realSrcAddress.
Referenced by DsrAckHeaderTest::DoRun(), and ns3::dsr::DsrOptionAck::Process().
GetSerializedSize()
uint32_t ns3::dsr::DsrOptionAckHeader::GetSerializedSize () const virtual
Get the serialized size of the packet.
Returns
size
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 1173 of file dsr-option-header.cc.
Referenced by Deserialize(), and ns3::dsr::DsrOptionAck::Process().
GetTypeId()
TypeId ns3::dsr::DsrOptionAckHeader::GetTypeId () static
Get the type identificator.
Returns
type identificator
Definition at line 1109 of file dsr-option-header.cc.
References ns3::TypeId::AddConstructor().
Referenced by GetInstanceTypeId().
Print()
void ns3::dsr::DsrOptionAckHeader::Print (std::ostream & os) const virtual
Print some information about the packet.
Parameters
os output stream
Returns
info about this packet
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 1165 of file dsr-option-header.cc.
References ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrOptionHeader::GetType(), m_identification, m_realDstAddress, and m_realSrcAddress.
Serialize()
void ns3::dsr::DsrOptionAckHeader::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start Buffer iterator
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 1178 of file dsr-option-header.cc.
References ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrOptionHeader::GetType(), m_identification, m_realDstAddress, m_realSrcAddress, visualizer.core::start(), ns3::WriteTo(), ns3::Buffer::Iterator::WriteU16(), and ns3::Buffer::Iterator::WriteU8().
SetAckId()
void ns3::dsr::DsrOptionAckHeader::SetAckId (uint16_t identification)
Set the Ack id number.
Parameters
identification the identification number
Definition at line 1135 of file dsr-option-header.cc.
References m_identification.
Referenced by DsrAckHeaderTest::DoRun(), and ns3::dsr::DsrRouting::SendAck().
SetRealDst()
void ns3::dsr::DsrOptionAckHeader::SetRealDst (Ipv4Address realDstAddress)
Set Error source ip address.
Parameters
realDstAddress The real dst address
Definition at line 1155 of file dsr-option-header.cc.
References m_realDstAddress.
Referenced by DsrAckHeaderTest::DoRun(), and ns3::dsr::DsrRouting::SendAck().
SetRealSrc()
void ns3::dsr::DsrOptionAckHeader::SetRealSrc (Ipv4Address realSrcAddress)
Set Error source ip address.
Parameters
realSrcAddress The real source address
Definition at line 1145 of file dsr-option-header.cc.
References m_realSrcAddress.
Referenced by DsrAckHeaderTest::DoRun(), and ns3::dsr::DsrRouting::SendAck().
Member Data Documentation
m_identification
uint16_t ns3::dsr::DsrOptionAckHeader::m_identification private
identification field
Definition at line 1336 of file dsr-option-header.h.
Referenced by Deserialize(), GetAckId(), Print(), Serialize(), and SetAckId().
m_realDstAddress
Ipv4Address ns3::dsr::DsrOptionAckHeader::m_realDstAddress private
ack destination address
Definition at line 1344 of file dsr-option-header.h.
Referenced by Deserialize(), GetRealDst(), Print(), Serialize(), and SetRealDst().
m_realSrcAddress
Ipv4Address ns3::dsr::DsrOptionAckHeader::m_realSrcAddress private
ack source address
Definition at line 1340 of file dsr-option-header.h.
Referenced by Deserialize(), GetRealSrc(), Print(), Serialize(), and SetRealSrc().
The documentation for this class was generated from the following files:
src/dsr/model/dsr-option-header.h
src/dsr/model/dsr-option-header.cc