ns-3: TestOptionWithAlignment Class Reference
TestOptionWithAlignment Class Reference
Internet » internet module tests | Test suites
IPv6 extensions Test: Test the option with alignment.
Public Member Functions
TestOptionWithAlignment ()
virtual void DoRun ()
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
IPv6 extensions Test: Test the option with alignment.
Definition at line 179 of file ipv6-extension-header-test-suite.cc.
Constructor & Destructor Documentation
TestOptionWithAlignment()
TestOptionWithAlignment::TestOptionWithAlignment () inline
Definition at line 182 of file ipv6-extension-header-test-suite.cc.
Member Function Documentation
DoRun()
virtual void TestOptionWithAlignment::DoRun () inline virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 184 of file ipv6-extension-header-test-suite.cc.
References ns3::Buffer::AddAtStart(), ns3::OptionField::AddOption(), ns3::Buffer::Begin(), data, ns3::Ipv6ExtensionDestinationHeader::GetSerializedSize(), ns3::Ipv6OptionHeader::GetType(), NS_TEST_EXPECT_MSG_EQ, ns3::Buffer::PeekData(), ns3::Ipv6ExtensionDestinationHeader::Serialize(), and OptionWithAlignmentHeader::TYPE.
The documentation for this class was generated from the following file:
src/internet/test/ipv6-extension-header-test-suite.cc