ns-3: ns3::Ipv6ExtensionRoutingHeader Class Reference
ns3::Ipv6ExtensionRoutingHeader Class Reference
Internet » IPv6 classes and sub-modules » IPV6 Header extension system.
Header of IPv6 Extension Routing.
#include "ipv6-extension-header.h"
Public Member Functions
Ipv6ExtensionRoutingHeader ()
Constructor.
virtual ~Ipv6ExtensionRoutingHeader ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
uint8_t GetSegmentsLeft () const
Get the field "Segments left".
virtual uint32_t GetSerializedSize () const
Get the serialized size of the packet.
uint8_t GetTypeRouting () const
Get the field "Type of Routing".
virtual void Print (std::ostream &os) const
Print some information about the packet.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetSegmentsLeft (uint8_t segmentsLeft)
Set the "Segments left" field.
void SetTypeRouting (uint8_t typeRouting)
Set the "Type of Routing" field.
Public Member Functions inherited from ns3::Ipv6ExtensionHeader
Ipv6ExtensionHeader ()
Constructor.
virtual ~Ipv6ExtensionHeader ()
Destructor.
uint16_t GetLength () const
Get the length of the extension.
uint8_t GetNextHeader () const
Get the next header.
void SetLength (uint16_t length)
brief Set the length of the extension.
void SetNextHeader (uint8_t nextHeader)
Set the "Next header" field.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Ipv6ExtensionHeader
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_segmentsLeft
Number of left segments.
uint8_t m_typeRouting
Type of routing.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Ipv6ExtensionHeader
uint8_t m_length
The "length" field.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Header of IPv6 Extension Routing.
Definition at line 441 of file ipv6-extension-header.h.
Constructor & Destructor Documentation
Ipv6ExtensionRoutingHeader()
ns3::Ipv6ExtensionRoutingHeader::Ipv6ExtensionRoutingHeader ()
Constructor.
Definition at line 431 of file ipv6-extension-header.cc.
~Ipv6ExtensionRoutingHeader()
ns3::Ipv6ExtensionRoutingHeader::~Ipv6ExtensionRoutingHeader () virtual
Destructor.
Definition at line 437 of file ipv6-extension-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::Ipv6ExtensionRoutingHeader::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start Buffer iterator
Returns
size of the packet
Reimplemented from ns3::Ipv6ExtensionHeader.
Reimplemented in ns3::Ipv6ExtensionLooseRoutingHeader.
Definition at line 482 of file ipv6-extension-header.cc.
References GetSerializedSize(), ns3::Ipv6ExtensionHeader::m_length, m_segmentsLeft, m_typeRouting, ns3::Buffer::Iterator::ReadU8(), ns3::Ipv6ExtensionHeader::SetNextHeader(), and visualizer.core::start().
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanNhc().
GetInstanceTypeId()
TypeId ns3::Ipv6ExtensionRoutingHeader::GetInstanceTypeId () const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::Ipv6ExtensionHeader.
Reimplemented in ns3::Ipv6ExtensionLooseRoutingHeader.
Definition at line 426 of file ipv6-extension-header.cc.
References GetTypeId().
GetSegmentsLeft()
uint8_t ns3::Ipv6ExtensionRoutingHeader::GetSegmentsLeft () const
Get the field "Segments left".
Returns
the number of segments left
Definition at line 456 of file ipv6-extension-header.cc.
References m_segmentsLeft.
Referenced by ns3::Ipv6ExtensionLooseRoutingHeader::Print(), ns3::Ipv6ExtensionLooseRouting::Process(), and ns3::Ipv6ExtensionLooseRoutingHeader::Serialize().
GetSerializedSize()
uint32_t ns3::Ipv6ExtensionRoutingHeader::GetSerializedSize () const virtual
Get the serialized size of the packet.
Returns
size
Reimplemented from ns3::Ipv6ExtensionHeader.
Reimplemented in ns3::Ipv6ExtensionLooseRoutingHeader.
Definition at line 467 of file ipv6-extension-header.cc.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanNhc(), and Deserialize().
GetTypeId()
TypeId ns3::Ipv6ExtensionRoutingHeader::GetTypeId () static
Get the type identificator.
Returns
type identificator
Definition at line 416 of file ipv6-extension-header.cc.
References ns3::TypeId::AddConstructor().
Referenced by GetInstanceTypeId().
GetTypeRouting()
uint8_t ns3::Ipv6ExtensionRoutingHeader::GetTypeRouting () const
Get the field "Type of Routing".
Returns
the type of routing
Definition at line 446 of file ipv6-extension-header.cc.
References m_typeRouting.
Referenced by ns3::Ipv6ExtensionLooseRoutingHeader::Print(), and ns3::Ipv6ExtensionLooseRoutingHeader::Serialize().
Print()
void ns3::Ipv6ExtensionRoutingHeader::Print (std::ostream & os) const virtual
Print some information about the packet.
Parameters
os output stream
Returns
info about this packet
Reimplemented from ns3::Ipv6ExtensionHeader.
Reimplemented in ns3::Ipv6ExtensionLooseRoutingHeader.
Definition at line 461 of file ipv6-extension-header.cc.
References ns3::Ipv6ExtensionHeader::GetLength(), ns3::Ipv6ExtensionHeader::GetNextHeader(), m_segmentsLeft, and m_typeRouting.
Serialize()
void ns3::Ipv6ExtensionRoutingHeader::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start Buffer iterator
Reimplemented from ns3::Ipv6ExtensionHeader.
Reimplemented in ns3::Ipv6ExtensionLooseRoutingHeader.
Definition at line 472 of file ipv6-extension-header.cc.
References ns3::Ipv6ExtensionHeader::GetNextHeader(), ns3::Ipv6ExtensionHeader::m_length, m_segmentsLeft, m_typeRouting, visualizer.core::start(), and ns3::Buffer::Iterator::WriteU8().
Referenced by ns3::SixLowPanNetDevice::CompressLowPanNhc().
SetSegmentsLeft()
void ns3::Ipv6ExtensionRoutingHeader::SetSegmentsLeft (uint8_t segmentsLeft)
Set the "Segments left" field.
Parameters
segmentsLeft the number of segments left
Definition at line 451 of file ipv6-extension-header.cc.
References m_segmentsLeft.
Referenced by ns3::Ipv6ExtensionLooseRoutingHeader::Deserialize(), ns3::Ipv6ExtensionLooseRouting::Process(), and ns3::Ping6::Send().
SetTypeRouting()
void ns3::Ipv6ExtensionRoutingHeader::SetTypeRouting (uint8_t typeRouting)
Set the "Type of Routing" field.
Parameters
typeRouting the type of routing
Definition at line 441 of file ipv6-extension-header.cc.
References m_typeRouting.
Referenced by ns3::Ipv6ExtensionLooseRoutingHeader::Deserialize(), and ns3::Ping6::Send().
Member Data Documentation
m_segmentsLeft
uint8_t ns3::Ipv6ExtensionRoutingHeader::m_segmentsLeft private
Number of left segments.
Definition at line 525 of file ipv6-extension-header.h.
Referenced by Deserialize(), GetSegmentsLeft(), Print(), Serialize(), and SetSegmentsLeft().
m_typeRouting
uint8_t ns3::Ipv6ExtensionRoutingHeader::m_typeRouting private
Type of routing.
Definition at line 520 of file ipv6-extension-header.h.
Referenced by Deserialize(), GetTypeRouting(), Print(), Serialize(), and SetTypeRouting().
The documentation for this class was generated from the following files:
src/internet/model/ipv6-extension-header.h
src/internet/model/ipv6-extension-header.cc