ns-3: ns3::EpcX2HandoverRequestHeader Class Reference
ns3::EpcX2HandoverRequestHeader Class Reference
EpcX2HandoverRequestHeader.
#include "epc-x2-header.h"
Public Member Functions
EpcX2HandoverRequestHeader ()
virtual ~EpcX2HandoverRequestHeader ()
virtual uint32_t Deserialize (Buffer::Iterator start)
std::vector< EpcX2Sap::ErabToBeSetupItem > GetBearers () const
Get bearers function.
uint16_t GetCause () const
Get cause function.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint32_t GetLengthOfIes () const
Get length of IEs.
uint32_t GetMmeUeS1apId () const
Get MME UE S1 AP ID function.
uint32_t GetNumberOfIes () const
Get number of IEs.
uint16_t GetOldEnbUeX2apId () const
Get old ENB X2 AP ID function.
virtual uint32_t GetSerializedSize (void) const
uint16_t GetTargetCellId () const
Get target cell id function.
uint64_t GetUeAggregateMaxBitRateDownlink () const
Get UE Aggregate Max Bit Rate Downlink function.
uint64_t GetUeAggregateMaxBitRateUplink () const
Get UE Aggregrate Max Bit Rate Uplik function.
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetBearers (std::vector< EpcX2Sap::ErabToBeSetupItem > bearers)
Set bearers function.
void SetCause (uint16_t cause)
Set cause function.
void SetMmeUeS1apId (uint32_t mmeUeS1apId)
Set MME UE S1 AP ID function.
void SetOldEnbUeX2apId (uint16_t x2apId)
Set old ENB X2 AP ID function.
void SetTargetCellId (uint16_t targetCellId)
Set target cell id function.
void SetUeAggregateMaxBitRateDownlink (uint64_t bitRate)
Set UE Aggregrate Max Bit Rate Downlink function.
void SetUeAggregateMaxBitRateUplink (uint64_t bitRate)
Set UE Aggregrate Max Bit Rate Uplik function.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint16_t m_cause
cause
std::vector< EpcX2Sap::ErabToBeSetupItem > m_erabsToBeSetupList
ERAB to be setup list.
uint32_t m_headerLength
header length
uint32_t m_mmeUeS1apId
MME UE S1 AP ID.
uint32_t m_numberOfIes
number of IEs
uint16_t m_oldEnbUeX2apId
old ENB UE X1 AP ID
uint16_t m_targetCellId
target cell ID
uint64_t m_ueAggregateMaxBitRateDownlink
aggregate max bit rate downlink
uint64_t m_ueAggregateMaxBitRateUplink
aggregate max bit rate uplink
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
EpcX2HandoverRequestHeader.
Definition at line 113 of file epc-x2-header.h.
Constructor & Destructor Documentation
EpcX2HandoverRequestHeader()
ns3::EpcX2HandoverRequestHeader::EpcX2HandoverRequestHeader ()
Definition at line 150 of file epc-x2-header.cc.
References m_erabsToBeSetupList.
~EpcX2HandoverRequestHeader()
ns3::EpcX2HandoverRequestHeader::~EpcX2HandoverRequestHeader () virtual
Definition at line 161 of file epc-x2-header.cc.
References m_cause, m_erabsToBeSetupList, m_headerLength, m_mmeUeS1apId, m_numberOfIes, m_oldEnbUeX2apId, and m_targetCellId.
Member Function Documentation
Deserialize()
uint32_t ns3::EpcX2HandoverRequestHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 244 of file epc-x2-header.cc.
References ns3::EpsBearer::arp, ns3::EpcX2Sap::ErabToBeSetupItem::dlForwarding, ns3::EpcX2Sap::ErabToBeSetupItem::erabId, ns3::EpcX2Sap::ErabToBeSetupItem::erabLevelQosParameters, ns3::GbrQosInformation::gbrDl, ns3::EpsBearer::gbrQosInfo, ns3::GbrQosInformation::gbrUl, GetSerializedSize(), ns3::EpcX2Sap::ErabToBeSetupItem::gtpTeid, m_cause, m_erabsToBeSetupList, m_headerLength, m_mmeUeS1apId, m_numberOfIes, m_oldEnbUeX2apId, m_targetCellId, m_ueAggregateMaxBitRateDownlink, m_ueAggregateMaxBitRateUplink, ns3::GbrQosInformation::mbrDl, ns3::GbrQosInformation::mbrUl, ns3::AllocationRetentionPriority::preemptionCapability, ns3::AllocationRetentionPriority::preemptionVulnerability, ns3::AllocationRetentionPriority::priorityLevel, ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadNtohU32(), ns3::Buffer::Iterator::ReadNtohU64(), ns3::Buffer::Iterator::ReadU8(), visualizer.core::start(), and ns3::EpcX2Sap::ErabToBeSetupItem::transportLayerAddress.
GetBearers()
std::vector< EpcX2Sap::ErabToBeSetupItem > ns3::EpcX2HandoverRequestHeader::GetBearers () const
Get bearers function.
Returns
<EpcX2Sap::ErabToBeSetupItem>
Definition at line 387 of file epc-x2-header.cc.
References m_erabsToBeSetupList.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
GetCause()
uint16_t ns3::EpcX2HandoverRequestHeader::GetCause () const
Get cause function.
Returns
the cause
Definition at line 351 of file epc-x2-header.cc.
References m_cause.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
GetInstanceTypeId()
TypeId ns3::EpcX2HandoverRequestHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 184 of file epc-x2-header.cc.
References GetTypeId().
GetLengthOfIes()
uint32_t ns3::EpcX2HandoverRequestHeader::GetLengthOfIes () const
Get length of IEs.
Returns
the length of IEs
Definition at line 424 of file epc-x2-header.cc.
References m_headerLength.
Referenced by ns3::EpcX2::DoSendHandoverRequest().
GetMmeUeS1apId()
uint32_t ns3::EpcX2HandoverRequestHeader::GetMmeUeS1apId () const
Get MME UE S1 AP ID function.
Returns
the MME UE S1 AP ID
Definition at line 375 of file epc-x2-header.cc.
References m_mmeUeS1apId.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
GetNumberOfIes()
uint32_t ns3::EpcX2HandoverRequestHeader::GetNumberOfIes () const
Get number of IEs.
Returns
the number of IEs
Definition at line 430 of file epc-x2-header.cc.
References m_numberOfIes.
Referenced by ns3::EpcX2::DoSendHandoverRequest().
GetOldEnbUeX2apId()
uint16_t ns3::EpcX2HandoverRequestHeader::GetOldEnbUeX2apId () const
Get old ENB X2 AP ID function.
Returns
the old ENB UE X2 AP ID
Definition at line 339 of file epc-x2-header.cc.
References m_oldEnbUeX2apId.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
GetSerializedSize()
uint32_t ns3::EpcX2HandoverRequestHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 190 of file epc-x2-header.cc.
References m_headerLength.
Referenced by Deserialize().
GetTargetCellId()
uint16_t ns3::EpcX2HandoverRequestHeader::GetTargetCellId () const
Get target cell id function.
Returns
the target cell ID
Definition at line 363 of file epc-x2-header.cc.
References m_targetCellId.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
GetTypeId()
TypeId ns3::EpcX2HandoverRequestHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 173 of file epc-x2-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
GetUeAggregateMaxBitRateDownlink()
uint64_t ns3::EpcX2HandoverRequestHeader::GetUeAggregateMaxBitRateDownlink () const
Get UE Aggregate Max Bit Rate Downlink function.
Returns
the UE aggregate max bit rate downlink
Definition at line 400 of file epc-x2-header.cc.
References m_ueAggregateMaxBitRateDownlink.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
GetUeAggregateMaxBitRateUplink()
uint64_t ns3::EpcX2HandoverRequestHeader::GetUeAggregateMaxBitRateUplink () const
Get UE Aggregrate Max Bit Rate Uplik function.
Returns
the UE aggregate max bit rate uplink
Definition at line 412 of file epc-x2-header.cc.
References m_ueAggregateMaxBitRateUplink.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
Print()
void ns3::EpcX2HandoverRequestHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 309 of file epc-x2-header.cc.
References m_cause, m_erabsToBeSetupList, m_mmeUeS1apId, m_oldEnbUeX2apId, m_targetCellId, m_ueAggregateMaxBitRateDownlink, and m_ueAggregateMaxBitRateUplink.
Serialize()
void ns3::EpcX2HandoverRequestHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 196 of file epc-x2-header.cc.
References m_cause, m_erabsToBeSetupList, m_mmeUeS1apId, m_oldEnbUeX2apId, m_targetCellId, m_ueAggregateMaxBitRateDownlink, m_ueAggregateMaxBitRateUplink, visualizer.core::start(), ns3::Buffer::Iterator::WriteHtonU16(), ns3::Buffer::Iterator::WriteHtonU32(), ns3::Buffer::Iterator::WriteHtonU64(), and ns3::Buffer::Iterator::WriteU8().
SetBearers()
void ns3::EpcX2HandoverRequestHeader::SetBearers (std::vector< EpcX2Sap::ErabToBeSetupItem > bearers)
Set bearers function.
Parameters
bearers std::vector <EpcX2Sap::ErabToBeSetupItem>
Definition at line 393 of file epc-x2-header.cc.
References m_erabsToBeSetupList, and m_headerLength.
Referenced by ns3::EpcX2::DoSendHandoverRequest().
SetCause()
void ns3::EpcX2HandoverRequestHeader::SetCause (uint16_t cause)
Set cause function.
Parameters
cause
Definition at line 357 of file epc-x2-header.cc.
References m_cause.
Referenced by ns3::EpcX2::DoSendHandoverRequest().
SetMmeUeS1apId()
void ns3::EpcX2HandoverRequestHeader::SetMmeUeS1apId (uint32_t mmeUeS1apId)
Set MME UE S1 AP ID function.
Parameters
mmeUeS1apId the MME UE S1 AP ID
Definition at line 381 of file epc-x2-header.cc.
References m_mmeUeS1apId.
Referenced by ns3::EpcX2::DoSendHandoverRequest().
SetOldEnbUeX2apId()
void ns3::EpcX2HandoverRequestHeader::SetOldEnbUeX2apId (uint16_t x2apId)
Set old ENB X2 AP ID function.
Parameters
x2apId the X2 AP ID
Definition at line 345 of file epc-x2-header.cc.
References m_oldEnbUeX2apId.
Referenced by ns3::EpcX2::DoSendHandoverRequest().
SetTargetCellId()
void ns3::EpcX2HandoverRequestHeader::SetTargetCellId (uint16_t targetCellId)
Set target cell id function.
Parameters
targetCellId the target cell ID
Definition at line 369 of file epc-x2-header.cc.
References m_targetCellId.
Referenced by ns3::EpcX2::DoSendHandoverRequest().
SetUeAggregateMaxBitRateDownlink()
void ns3::EpcX2HandoverRequestHeader::SetUeAggregateMaxBitRateDownlink (uint64_t bitRate)
Set UE Aggregrate Max Bit Rate Downlink function.
Parameters
bitRate the bit rate
Definition at line 406 of file epc-x2-header.cc.
References m_ueAggregateMaxBitRateDownlink.
Referenced by ns3::EpcX2::DoSendHandoverRequest().
SetUeAggregateMaxBitRateUplink()
void ns3::EpcX2HandoverRequestHeader::SetUeAggregateMaxBitRateUplink (uint64_t bitRate)
Set UE Aggregrate Max Bit Rate Uplik function.
Parameters
bitRate the bit rate
Definition at line 418 of file epc-x2-header.cc.
References m_ueAggregateMaxBitRateUplink.
Referenced by ns3::EpcX2::DoSendHandoverRequest().
Member Data Documentation
m_cause
uint16_t ns3::EpcX2HandoverRequestHeader::m_cause private
cause
Definition at line 224 of file epc-x2-header.h.
Referenced by ~EpcX2HandoverRequestHeader(), Deserialize(), GetCause(), Print(), Serialize(), and SetCause().
m_erabsToBeSetupList
std::vector<EpcX2Sap::ErabToBeSetupItem> ns3::EpcX2HandoverRequestHeader::m_erabsToBeSetupList private
ERAB to be setup list.
Definition at line 229 of file epc-x2-header.h.
Referenced by EpcX2HandoverRequestHeader(), ~EpcX2HandoverRequestHeader(), Deserialize(), GetBearers(), Print(), Serialize(), and SetBearers().
m_headerLength
uint32_t ns3::EpcX2HandoverRequestHeader::m_headerLength private
header length
Definition at line 221 of file epc-x2-header.h.
Referenced by ~EpcX2HandoverRequestHeader(), Deserialize(), GetLengthOfIes(), GetSerializedSize(), and SetBearers().
m_mmeUeS1apId
uint32_t ns3::EpcX2HandoverRequestHeader::m_mmeUeS1apId private
MME UE S1 AP ID.
Definition at line 226 of file epc-x2-header.h.
Referenced by ~EpcX2HandoverRequestHeader(), Deserialize(), GetMmeUeS1apId(), Print(), Serialize(), and SetMmeUeS1apId().
m_numberOfIes
uint32_t ns3::EpcX2HandoverRequestHeader::m_numberOfIes private
number of IEs
Definition at line 220 of file epc-x2-header.h.
Referenced by ~EpcX2HandoverRequestHeader(), Deserialize(), and GetNumberOfIes().
m_oldEnbUeX2apId
uint16_t ns3::EpcX2HandoverRequestHeader::m_oldEnbUeX2apId private
old ENB UE X1 AP ID
Definition at line 223 of file epc-x2-header.h.
Referenced by ~EpcX2HandoverRequestHeader(), Deserialize(), GetOldEnbUeX2apId(), Print(), Serialize(), and SetOldEnbUeX2apId().
m_targetCellId
uint16_t ns3::EpcX2HandoverRequestHeader::m_targetCellId private
target cell ID
Definition at line 225 of file epc-x2-header.h.
Referenced by ~EpcX2HandoverRequestHeader(), Deserialize(), GetTargetCellId(), Print(), Serialize(), and SetTargetCellId().
m_ueAggregateMaxBitRateDownlink
uint64_t ns3::EpcX2HandoverRequestHeader::m_ueAggregateMaxBitRateDownlink private
aggregate max bit rate downlink
Definition at line 227 of file epc-x2-header.h.
Referenced by Deserialize(), GetUeAggregateMaxBitRateDownlink(), Print(), Serialize(), and SetUeAggregateMaxBitRateDownlink().
m_ueAggregateMaxBitRateUplink
uint64_t ns3::EpcX2HandoverRequestHeader::m_ueAggregateMaxBitRateUplink private
aggregate max bit rate uplink
Definition at line 228 of file epc-x2-header.h.
Referenced by Deserialize(), GetUeAggregateMaxBitRateUplink(), Print(), Serialize(), and SetUeAggregateMaxBitRateUplink().
The documentation for this class was generated from the following files:
src/lte/model/epc-x2-header.h
src/lte/model/epc-x2-header.cc