ns-3: ns3::lorawan::LorawanMacHelper Class Reference
ns3::lorawan::LorawanMacHelper Class Reference
#include "lorawan-mac-helper.h"
Public Types
enum DeviceType { GW, ED_A }
Define the kind of device.
enum Regions {
EU, US, China, EU433MHz,
Australia, CN, AS923MHz, SouthKorea,
ALOHA
}
Define the operational region.
Public Member Functions
LorawanMacHelper ()
Create a mac helper without any parameter set.
Ptr< LorawanMac > Create (Ptr< Node > node, Ptr< NetDevice > device) const
Create the LorawanMac instance and connect it to a device.
void Set (std::string name, const AttributeValue &v)
Set an attribute of the underlying MAC object.
void SetAddressGenerator (Ptr< LoraDeviceAddressGenerator > addrGen)
Set the address generator to use for creation of these nodes.
void SetDeviceType (enum DeviceType dt)
Set the kind of MAC this helper will create.
void SetRegion (enum Regions region)
Set the region in which the device is to operate.
Static Public Member Functions
static std::vector< int > SetSpreadingFactorsGivenDistribution (NodeContainer endDevices, NodeContainer gateways, std::vector< double > distribution)
Set up the end device's data rates according to the given distribution.
static std::vector< int > SetSpreadingFactorsUp (NodeContainer endDevices, NodeContainer gateways, Ptr< LoraChannel > channel)
Set up the end device's data rates This function assumes we are using the following convention: SF7 -> DR5 SF8 -> DR4 SF9 -> DR3 SF10 -> DR2 SF11 -> DR1 SF12 -> DR0.
Private Member Functions
void ApplyCommonAlohaConfigurations (Ptr< LorawanMac > lorawanMac) const
Apply configurations that are common both for the GatewayLorawanMac and the ClassAEndDeviceLorawanMac classes.
void ApplyCommonEuConfigurations (Ptr< LorawanMac > lorawanMac) const
Apply configurations that are common both for the GatewayLorawanMac and the ClassAEndDeviceLorawanMac classes.
void ConfigureForAlohaRegion (Ptr< ClassAEndDeviceLorawanMac > edMac) const
Perform region-specific configurations for the ALOHA band.
void ConfigureForAlohaRegion (Ptr< GatewayLorawanMac > gwMac) const
Perform region-specific configurations for the ALOHA band.
void ConfigureForEuRegion (Ptr< ClassAEndDeviceLorawanMac > edMac) const
Perform region-specific configurations for the 868 MHz EU band.
void ConfigureForEuRegion (Ptr< GatewayLorawanMac > gwMac) const
Perform region-specific configurations for the 868 MHz EU band.
Private Attributes
Ptr< LoraDeviceAddressGenerator > m_addrGen
Pointer to the address generator to use.
enum DeviceType m_deviceType
The kind of device to install.
ObjectFactory m_mac
enum Regions m_region
The region in which the device will operate.
Detailed Description
Definition at line 37 of file lorawan-mac-helper.h.
Member Enumeration Documentation
DeviceType
enum ns3::lorawan::LorawanMacHelper::DeviceType
Define the kind of device.
Can be either GW (Gateway) or ED (End Device).
Enumerator
GW
ED_A
Definition at line 43 of file lorawan-mac-helper.h.
Regions
enum ns3::lorawan::LorawanMacHelper::Regions
Define the operational region.
Enumerator
EU
US
China
EU433MHz
Australia
CN
AS923MHz
SouthKorea
ALOHA
Definition at line 48 of file lorawan-mac-helper.h.
Constructor & Destructor Documentation
LorawanMacHelper()
ns3::lorawan::LorawanMacHelper::LorawanMacHelper ()
Create a mac helper without any parameter set.
The user must set them all to be able to call Install later.
Definition at line 33 of file lorawan-mac-helper.cc.
Member Function Documentation
ApplyCommonAlohaConfigurations()
void ns3::lorawan::LorawanMacHelper::ApplyCommonAlohaConfigurations (Ptr< LorawanMac > lorawanMac) const private
Apply configurations that are common both for the GatewayLorawanMac and the ClassAEndDeviceLorawanMac classes.
Definition at line 210 of file lorawan-mac-helper.cc.
References ns3::lorawan::LogicalLoraChannelHelper::AddChannel(), ns3::lorawan::LogicalLoraChannelHelper::AddSubBand(), and NS_LOG_FUNCTION_NOARGS.
Referenced by ConfigureForAlohaRegion().
ApplyCommonEuConfigurations()
void ns3::lorawan::LorawanMacHelper::ApplyCommonEuConfigurations (Ptr< LorawanMac > lorawanMac) const private
Apply configurations that are common both for the GatewayLorawanMac and the ClassAEndDeviceLorawanMac classes.
Definition at line 318 of file lorawan-mac-helper.cc.
References ns3::lorawan::LogicalLoraChannelHelper::AddChannel(), ns3::lorawan::LogicalLoraChannelHelper::AddSubBand(), and NS_LOG_FUNCTION_NOARGS.
Referenced by ConfigureForEuRegion().
ConfigureForAlohaRegion() [1/2]
void ns3::lorawan::LorawanMacHelper::ConfigureForAlohaRegion (Ptr< ClassAEndDeviceLorawanMac > edMac) const private
Perform region-specific configurations for the ALOHA band.
Definition at line 135 of file lorawan-mac-helper.cc.
References ApplyCommonAlohaConfigurations(), and NS_LOG_FUNCTION_NOARGS.
Referenced by Create().
ConfigureForAlohaRegion() [2/2]
void ns3::lorawan::LorawanMacHelper::ConfigureForAlohaRegion (Ptr< GatewayLorawanMac > gwMac) const private
Perform region-specific configurations for the ALOHA band.
Definition at line 172 of file lorawan-mac-helper.cc.
References ApplyCommonAlohaConfigurations(), ns3::Object::GetObject(), NS_LOG_DEBUG, and NS_LOG_FUNCTION_NOARGS.
ConfigureForEuRegion() [1/2]
void ns3::lorawan::LorawanMacHelper::ConfigureForEuRegion (Ptr< ClassAEndDeviceLorawanMac > edMac) const private
Perform region-specific configurations for the 868 MHz EU band.
Definition at line 241 of file lorawan-mac-helper.cc.
References ApplyCommonEuConfigurations(), and NS_LOG_FUNCTION_NOARGS.
Referenced by Create().
ConfigureForEuRegion() [2/2]
void ns3::lorawan::LorawanMacHelper::ConfigureForEuRegion (Ptr< GatewayLorawanMac > gwMac) const private
Perform region-specific configurations for the 868 MHz EU band.
Definition at line 278 of file lorawan-mac-helper.cc.
References ApplyCommonEuConfigurations(), ns3::Object::GetObject(), NS_LOG_DEBUG, and NS_LOG_FUNCTION_NOARGS.
Create()
Ptr< LorawanMac > ns3::lorawan::LorawanMacHelper::Create (Ptr< Node > node, Ptr< NetDevice > device) const
Create the LorawanMac instance and connect it to a device.
Parameters
node the node on which we wish to create a wifi MAC.
device the device within which this MAC will be created.
Returns
a newly-created LorawanMac object.
Definition at line 74 of file lorawan-mac-helper.cc.
References ALOHA, ConfigureForAlohaRegion(), ConfigureForEuRegion(), ns3::ObjectFactory::Create(), ED_A, EU, m_addrGen, m_deviceType, m_mac, m_region, third::mac, and NS_LOG_ERROR.
Referenced by ns3::lorawan::LoraHelper::Install().
Set()
void ns3::lorawan::LorawanMacHelper::Set (std::string name, const AttributeValue & v)
Set an attribute of the underlying MAC object.
Parameters
name the name of the attribute to set.
v the value of the attribute.
Definition at line 38 of file lorawan-mac-helper.cc.
References m_mac, and ns3::ObjectFactory::Set().
SetAddressGenerator()
void ns3::lorawan::LorawanMacHelper::SetAddressGenerator (Ptr< LoraDeviceAddressGenerator > addrGen)
Set the address generator to use for creation of these nodes.
Definition at line 60 of file lorawan-mac-helper.cc.
References m_addrGen, and NS_LOG_FUNCTION.
SetDeviceType()
void ns3::lorawan::LorawanMacHelper::SetDeviceType (enum DeviceType dt)
Set the kind of MAC this helper will create.
Parameters
dt the device type (either gateway or end device).
Definition at line 44 of file lorawan-mac-helper.cc.
References ED_A, GW, m_deviceType, m_mac, NS_LOG_FUNCTION, and ns3::ObjectFactory::SetTypeId().
Referenced by ns3::lorawan::CreateEndDevices(), and ns3::lorawan::CreateGateways().
SetRegion()
void ns3::lorawan::LorawanMacHelper::SetRegion (enum Regions region)
Set the region in which the device is to operate.
Definition at line 68 of file lorawan-mac-helper.cc.
References m_region.
SetSpreadingFactorsGivenDistribution()
std::vector< int > ns3::lorawan::LorawanMacHelper::SetSpreadingFactorsGivenDistribution (NodeContainer endDevices, NodeContainer gateways, std::vector< double > distribution) static
Set up the end device's data rates according to the given distribution.
Definition at line 497 of file lorawan-mac-helper.cc.
References ns3::NodeContainer::Begin(), ns3::NodeContainer::End(), ns3::Object::GetObject(), ns3::UniformRandomVariable::GetValue(), third::mac, NS_ASSERT, NS_LOG_DEBUG, and NS_LOG_FUNCTION_NOARGS.
SetSpreadingFactorsUp()
std::vector< int > ns3::lorawan::LorawanMacHelper::SetSpreadingFactorsUp (NodeContainer endDevices, NodeContainer gateways, Ptr< LoraChannel > channel) static
Set up the end device's data rates This function assumes we are using the following convention: SF7 -> DR5 SF8 -> DR4 SF9 -> DR3 SF10 -> DR2 SF11 -> DR1 SF12 -> DR0.
Definition at line 355 of file lorawan-mac-helper.cc.
References ns3::NodeContainer::Begin(), third::channel, ns3::NodeContainer::End(), ns3::NodeContainer::Get(), ns3::Object::GetObject(), third::mac, NS_ASSERT, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::lorawan::InitializeNetwork().
Member Data Documentation
m_addrGen
Ptr<LoraDeviceAddressGenerator> ns3::lorawan::LorawanMacHelper::m_addrGen private
Pointer to the address generator to use.
Definition at line 143 of file lorawan-mac-helper.h.
Referenced by Create(), and SetAddressGenerator().
m_deviceType
enum DeviceType ns3::lorawan::LorawanMacHelper::m_deviceType private
The kind of device to install.
Definition at line 143 of file lorawan-mac-helper.h.
Referenced by Create(), and SetDeviceType().
m_mac
ObjectFactory ns3::lorawan::LorawanMacHelper::m_mac private
Definition at line 142 of file lorawan-mac-helper.h.
Referenced by Create(), Set(), and SetDeviceType().
m_region
enum Regions ns3::lorawan::LorawanMacHelper::m_region private
The region in which the device will operate.
Definition at line 143 of file lorawan-mac-helper.h.
Referenced by Create(), and SetRegion().
The documentation for this class was generated from the following files:
src/lorawan/helper/lorawan-mac-helper.h
src/lorawan/helper/lorawan-mac-helper.cc