ns-3: ns3::LteUeRrcSapUser Class Reference
ns3::LteUeRrcSapUser Class Reference abstract
Part of the RRC protocol.
#include "lte-rrc-sap.h"
Classes
struct SetupParameters
SetupParameters structure.
Public Member Functions
virtual void SendIdealUeContextRemoveRequest (uint16_t rnti)=0
Send UE context remove request function.
virtual void SendMeasurementReport (MeasurementReport msg)=0
Send a MeasurementReport message to the serving eNodeB during a measurement reporting procedure (Section 5.5.5 of TS 36.331).
virtual void SendRrcConnectionReconfigurationCompleted (RrcConnectionReconfigurationCompleted msg)=0
Send an RRCConnectionReconfigurationComplete message to the serving eNodeB during an RRC connection reconfiguration procedure (Section 5.3.5 of TS 36.331).
virtual void SendRrcConnectionReestablishmentComplete (RrcConnectionReestablishmentComplete msg)=0
Send an RRCConnectionReestablishmentComplete message to the serving eNodeB during an RRC connection re-establishment procedure (Section 5.3.7 of TS 36.331).
virtual void SendRrcConnectionReestablishmentRequest (RrcConnectionReestablishmentRequest msg)=0
Send an RRCConnectionReestablishmentRequest message to the serving eNodeB during an RRC connection re-establishment procedure (Section 5.3.7 of TS 36.331).
virtual void SendRrcConnectionRequest (RrcConnectionRequest msg)=0
Send an _RRCConnectionRequest message to the serving eNodeB during an RRC connection establishment procedure (Section 5.3.3 of TS 36.331).
virtual void SendRrcConnectionSetupCompleted (RrcConnectionSetupCompleted msg)=0
Send an RRCConnectionSetupComplete message to the serving eNodeB during an RRC connection establishment procedure (Section 5.3.3 of TS 36.331).
virtual void Setup (SetupParameters params)=0
Setup function.
Public Member Functions inherited from ns3::LteRrcSap
virtual ~LteRrcSap ()
Additional Inherited Members
Public Types inherited from ns3::LteRrcSap
enum ReestablishmentCause { RECONFIGURATION_FAILURE, HANDOVER_FAILURE, OTHER_FAILURE }
ReestablishmentCause enumeration.
Static Public Member Functions inherited from ns3::LteRrcSap
static double ConvertPdschConfigDedicated2Double (PdschConfigDedicated pdschConfigDedicated)
Convert PDSCH config dedicated function.
Static Public Attributes inherited from ns3::LteRrcSap
static const uint8_t MaxReportCells = 8
Constraint values.
Detailed Description
Part of the RRC protocol.
This Service Access Point (SAP) is used by the UE RRC to send messages to the eNB. Each method defined in this class corresponds to the transmission of a message that is defined in Section 6.2.2 of TS 36.331.
Definition at line 916 of file lte-rrc-sap.h.
Member Function Documentation
SendIdealUeContextRemoveRequest()
virtual void ns3::LteUeRrcSapUser::SendIdealUeContextRemoveRequest (uint16_t rnti) pure virtual
Send UE context remove request function.
Request eNodeB to remove UE context once radio link failure or random access failure is detected. It is needed since no RLF detection mechanism at eNodeB is implemented.
Parameters
rnti the C-RNTI of the UE
Implemented in ns3::MemberLteUeRrcSapUser< C >.
Referenced by ns3::LteUeRrc::RadioLinkFailureDetected().
SendMeasurementReport()
virtual void ns3::LteUeRrcSapUser::SendMeasurementReport (MeasurementReport msg) pure virtual
Send a MeasurementReport message to the serving eNodeB during a measurement reporting procedure (Section 5.5.5 of TS 36.331).
Parameters
msg the message
Implemented in ns3::MemberLteUeRrcSapUser< C >.
Referenced by ns3::LteUeRrc::SendMeasurementReport().
SendRrcConnectionReconfigurationCompleted()
virtual void ns3::LteUeRrcSapUser::SendRrcConnectionReconfigurationCompleted (RrcConnectionReconfigurationCompleted msg) pure virtual
Send an RRCConnectionReconfigurationComplete message to the serving eNodeB during an RRC connection reconfiguration procedure (Section 5.3.5 of TS 36.331).
Parameters
msg the message
Implemented in ns3::MemberLteUeRrcSapUser< C >.
Referenced by ns3::LteUeRrc::DoNotifyRandomAccessSuccessful(), and ns3::LteUeRrc::DoRecvRrcConnectionReconfiguration().
SendRrcConnectionReestablishmentComplete()
virtual void ns3::LteUeRrcSapUser::SendRrcConnectionReestablishmentComplete (RrcConnectionReestablishmentComplete msg) pure virtual
Send an RRCConnectionReestablishmentComplete message to the serving eNodeB during an RRC connection re-establishment procedure (Section 5.3.7 of TS 36.331).
Parameters
msg the message
Implemented in ns3::MemberLteUeRrcSapUser< C >.
SendRrcConnectionReestablishmentRequest()
virtual void ns3::LteUeRrcSapUser::SendRrcConnectionReestablishmentRequest (RrcConnectionReestablishmentRequest msg) pure virtual
Send an RRCConnectionReestablishmentRequest message to the serving eNodeB during an RRC connection re-establishment procedure (Section 5.3.7 of TS 36.331).
Parameters
msg the message
Implemented in ns3::MemberLteUeRrcSapUser< C >.
SendRrcConnectionRequest()
virtual void ns3::LteUeRrcSapUser::SendRrcConnectionRequest (RrcConnectionRequest msg) pure virtual
Send an _RRCConnectionRequest message to the serving eNodeB during an RRC connection establishment procedure (Section 5.3.3 of TS 36.331).
Parameters
msg the message
Implemented in ns3::MemberLteUeRrcSapUser< C >.
Referenced by ns3::LteUeRrc::DoNotifyRandomAccessSuccessful().
SendRrcConnectionSetupCompleted()
virtual void ns3::LteUeRrcSapUser::SendRrcConnectionSetupCompleted (RrcConnectionSetupCompleted msg) pure virtual
Send an RRCConnectionSetupComplete message to the serving eNodeB during an RRC connection establishment procedure (Section 5.3.3 of TS 36.331).
Parameters
msg the message
Implemented in ns3::MemberLteUeRrcSapUser< C >.
Referenced by ns3::LteUeRrc::DoRecvRrcConnectionSetup().
Setup()
virtual void ns3::LteUeRrcSapUser::Setup (SetupParameters params) pure virtual
Setup function.
Parameters
params the setup parameters
Implemented in ns3::MemberLteUeRrcSapUser< C >.
Referenced by ns3::LteUeRrc::ApplyRadioResourceConfigDedicated(), and ns3::LteUeRrc::DoInitialize().
The documentation for this class was generated from the following file:
src/lte/model/lte-rrc-sap.h