ns-3: TcpRateLinuxWithSocketsTest Class Reference
TcpRateLinuxWithSocketsTest Class Reference
Test suites
The TcpRateLinux Test uses sender-receiver model to test its functionality. This test case uses the bytes inflight trace to check whether rate sample correctly sets the value of m_deliveredTime and m_firstSentTime. This is done using rate trace. Further, Using Rx trace, m_isDupAck is maintained to track duplicate acknowledgments. This, in turn, is used to see whether rate sample is updated properly (in case of SACK) or not (in case of non SACK).
Public Member Functions
TcpRateLinuxWithSocketsTest (const std::string &desc, bool sackEnabled, std::vector< uint32_t > &toDrop)
Constructor.
Public Member Functions inherited from ns3::TcpGeneralTest
TcpGeneralTest (const std::string &desc)
TcpGeneralTest constructor.
~TcpGeneralTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Member Functions
virtual void BytesInFlightTrace (uint32_t oldValue, uint32_t newValue)
Track the bytes in flight.
void ConfigureEnvironment ()
Configure the test.
virtual Ptr< ErrorModel > CreateReceiverErrorModel ()
Create a receiver error model.
virtual Ptr< TcpSocketMsgBase > CreateSenderSocket (Ptr< Node > node)
Create and install the socket to install on the sender.
void FinalChecks ()
Do the final checks.
void PktDropped (const Ipv4Header &ipH, const TcpHeader &tcpH, Ptr< const Packet > p)
Called when a packet is dropped.
virtual void RateSampleUpdatedTrace (const TcpRateLinux::TcpRateSample &sample)
Track the rate sample value of TcpRateLinux.
virtual void RateUpdatedTrace (const TcpRateLinux::TcpRateConnection &rate)
Track the rate value of TcpRateLinux.
virtual void Rx (const Ptr< const Packet > p, const TcpHeader &h, SocketWho who)
Receive a packet.
Protected Member Functions inherited from ns3::TcpGeneralTest
virtual void AfterRTOExpired (const Ptr< const TcpSocketState > tcb, SocketWho who)
Rto has expired.
virtual void BeforeRTOExpired (const Ptr< const TcpSocketState > tcb, SocketWho who)
Rto has expired.
virtual void ConfigureProperties (void)
Change the configuration of the socket properties.
virtual void CongStateTrace (const TcpSocketState::TcpCongState_t oldValue, const TcpSocketState::TcpCongState_t newValue)
State on Ack state machine changes.
virtual Ptr< SimpleChannel > CreateChannel ()
Create and return the channel installed between the two socket.
virtual Ptr< TcpSocketMsgBase > CreateReceiverSocket (Ptr< Node > node)
Create and install the socket to install on the receiver.
virtual Ptr< ErrorModel > CreateSenderErrorModel ()
Create and return the error model to install in the sender node.
virtual Ptr< TcpSocketMsgBase > CreateSocket (Ptr< Node > node, TypeId socketType, TypeId congControl)
Create a socket.
virtual Ptr< TcpSocketMsgBase > CreateSocket (Ptr< Node > node, TypeId socketType, TypeId congControl, TypeId recoveryAlgorithm)
Create a socket.
virtual void CWndInflTrace (uint32_t oldValue, uint32_t newValue)
Tracks the inflated congestion window changes.
virtual void CWndTrace (uint32_t oldValue, uint32_t newValue)
Tracks the congestion window changes.
virtual void DataSent (uint32_t size, SocketWho who)
Notifying application for sent data.
void DoConnect ()
Scheduled at 0.0, SENDER starts the connection to RECEIVER.
virtual void DoRun (void)
Execute the tcp test.
virtual void DoTeardown (void)
Teardown the TCP test.
virtual void ErrorClose (SocketWho who)
Socket closed with an error.
Time GetClockGranularity (SocketWho who)
Get the clock granularity attribute.
Time GetConnTimeout (SocketWho who)
Get the retransmission time for the SYN segments.
uint32_t GetDelAckCount (SocketWho who)
Get the number of delayed ack (if present)
Time GetDelAckTimeout (SocketWho who)
Get the timeout of delayed ack (if present)
uint32_t GetDupAckCount (SocketWho who)
Get the number of dupack received.
SequenceNumber32 GetHighestTxMark (SocketWho who)
Get the highest tx mark of the node specified.
uint32_t GetInitialCwnd (SocketWho who)
Get the initial congestion window.
uint32_t GetInitialSsThresh (SocketWho who)
Get the initial slow start threshold.
Time GetMinRto (SocketWho who)
Get the minimum RTO attribute.
uint32_t GetMtu () const
Get the MTU of the environment.
EventId GetPersistentEvent (SocketWho who)
Get the persistent event of the selected socket.
Time GetPersistentTimeout (SocketWho who)
Get the persistent timeout of the selected socket.
uint32_t GetPktCount () const
Get the number of application packets.
Time GetPktInterval () const
Get the interval to wait for each packet sent down from application to TCP.
uint32_t GetPktSize () const
Get the application packet size.
Time GetPropagationDelay () const
Get the channel Propagation Delay.
Ptr< TcpSocketMsgBase > GetReceiverSocket ()
Get the pointer to a previously created receiver socket.
uint32_t GetReTxThreshold (SocketWho who)
Get the retransmission threshold.
Time GetRto (SocketWho who)
Get the retransmission time.
Ptr< RttEstimator > GetRttEstimator (SocketWho who)
Get the Rtt estimator of the socket.
uint32_t GetRWnd (SocketWho who)
Get the rWnd of the selected socket.
Ptr< TcpRxBuffer > GetRxBuffer (SocketWho who)
Get the Rx buffer from selected socket.
uint32_t GetSegSize (SocketWho who)
Get the segment size of the node specified.
Ptr< TcpSocketMsgBase > GetSenderSocket ()
Get the pointer to a previously created sender socket.
Time GetStartTime () const
Get the data start time.
Ptr< TcpSocketState > GetTcb (SocketWho who)
Get the TCB from selected socket.
TcpSocket::TcpStates_t GetTcpState (SocketWho who)
Get the state of the TCP state machine.
Ptr< TcpTxBuffer > GetTxBuffer (SocketWho who)
Get the Tx buffer from selected socket.
virtual void HighestTxSeqTrace (SequenceNumber32 oldValue, SequenceNumber32 newValue)
Highest tx seq changes.
virtual void NextTxSeqTrace (SequenceNumber32 oldValue, SequenceNumber32 newValue)
Next tx seq changes.
virtual void NormalClose (SocketWho who)
Socket closed normally.
virtual void PhyDrop (SocketWho who)
Link drop.
virtual void ProcessedAck (const Ptr< const TcpSocketState > tcb, const TcpHeader &h, SocketWho who)
Processed ack.
virtual void QueueDrop (SocketWho who)
Drop on the queue.
virtual void RateSampleUpdatedTrace (const TcpRateLinux::TcpRateSample &sample)
Track the rate sample value of TcpRateLinux.
virtual void RateUpdatedTrace (const TcpRateLinux::TcpRateConnection &rate)
Track the rate value of TcpRateLinux.
virtual void RcvAck (const Ptr< const TcpSocketState > tcb, const TcpHeader &h, SocketWho who)
Received ack.
virtual void ReceivePacket (Ptr< Socket > socket)
Packet received.
virtual void RtoTrace (Time oldValue, Time newValue)
RTO changes.
virtual void RttTrace (Time oldTime, Time newTime)
Rtt changes.
void SendPacket (Ptr< Socket > socket, uint32_t pktSize, uint32_t pktCount, Time pktInterval)
Send packets to other endpoint.
void SetAppPktCount (uint32_t pktCount)
Set app packet count.
void SetAppPktInterval (Time pktInterval)
Interval between app-generated packet.
void SetAppPktSize (uint32_t pktSize)
Set app packet size.
void SetCongestionControl (TypeId congControl)
Congestion control of the sender socket.
void SetInitialCwnd (SocketWho who, uint32_t initialCwnd)
Forcefully set the initial cwnd.
void SetInitialSsThresh (SocketWho who, uint32_t initialSsThresh)
Forcefully set the initial ssth.
void SetMTU (uint32_t mtu)
MTU of the bottleneck link.
void SetPropagationDelay (Time propDelay)
Propagation delay of the bottleneck link.
void SetRcvBufSize (SocketWho who, uint32_t size)
Forcefully set a defined size for rx buffer.
void SetRecoveryAlgorithm (TypeId reccovery)
recovery algorithm of the sender socket
void SetSegmentSize (SocketWho who, uint32_t segmentSize)
Forcefully set the segment size.
void SetTransmitStart (Time startTime)
Set the initial time at which the application sends the first data packet.
void SetUseEcn (SocketWho who, TcpSocketState::UseEcn_t useEcn)
Forcefully set the ecn use on.
virtual void SsThreshTrace (uint32_t oldValue, uint32_t newValue)
Slow start threshold changes.
virtual void Tx (const Ptr< const Packet > p, const TcpHeader &h, SocketWho who)
Packet transmitted down to IP layer.
virtual void UpdatedRttHistory (const SequenceNumber32 &seq, uint32_t sz, bool isRetransmission, SocketWho who)
Updated the Rtt history.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Private Attributes
uint32_t m_bytesInFlight {0}
Bytes inflight.
Ptr< MimicCongControl > m_congCtl
Dummy congestion control.
bool m_isDupAck
Whether ACK is DupAck.
SequenceNumber32 m_lastAckRecv {SequenceNumber32 (1)}
Last ACK received.
TcpRateLinux::TcpRateConnection m_prevRate
Previous rate.
TcpRateLinux::TcpRateSample m_prevRateSample
Previous rate sample.
bool m_sackEnabled
Sack Variable.
std::vector< uint32_t > m_toDrop
List of SequenceNumber to drop.
Additional Inherited Members
Public Types inherited from ns3::TcpGeneralTest
enum SocketWho { SENDER, RECEIVER }
Used as parameter of methods, specifies on what node the caller is interested (e.g.
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Attributes inherited from ns3::TcpGeneralTest
TypeId m_congControlTypeId
Congestion control.
TypeId m_recoveryTypeId
Recovery.
Detailed Description
The TcpRateLinux Test uses sender-receiver model to test its functionality. This test case uses the bytes inflight trace to check whether rate sample correctly sets the value of m_deliveredTime and m_firstSentTime. This is done using rate trace. Further, Using Rx trace, m_isDupAck is maintained to track duplicate acknowledgments. This, in turn, is used to see whether rate sample is updated properly (in case of SACK) or not (in case of non SACK).
Definition at line 195 of file tcp-rate-ops-test.cc.
Constructor & Destructor Documentation
TcpRateLinuxWithSocketsTest()
TcpRateLinuxWithSocketsTest::TcpRateLinuxWithSocketsTest (const std::string & desc, bool sackEnabled, std::vector< uint32_t > & toDrop)
Constructor.
Parameters
desc Description.
sackEnabled To use SACK or not
toDrop Packets to drop.
Definition at line 277 of file tcp-rate-ops-test.cc.
Member Function Documentation
BytesInFlightTrace()
void TcpRateLinuxWithSocketsTest::BytesInFlightTrace (uint32_t oldValue, uint32_t newValue) protected virtual
Track the bytes in flight.
Parameters
oldValue previous value.
newValue actual value.
Reimplemented from ns3::TcpGeneralTest.
Definition at line 346 of file tcp-rate-ops-test.cc.
References m_bytesInFlight, and NS_UNUSED.
ConfigureEnvironment()
void TcpRateLinuxWithSocketsTest::ConfigureEnvironment () protected virtual
Configure the test.
Reimplemented from ns3::TcpGeneralTest.
Definition at line 295 of file tcp-rate-ops-test.cc.
References m_sackEnabled, ns3::MilliSeconds(), ns3::Seconds(), ns3::TcpGeneralTest::SetAppPktCount(), ns3::Config::SetDefault(), ns3::TcpGeneralTest::SetPropagationDelay(), and ns3::TcpGeneralTest::SetTransmitStart().
CreateReceiverErrorModel()
Ptr< ErrorModel > TcpRateLinuxWithSocketsTest::CreateReceiverErrorModel () protected virtual
Create a receiver error model.
Returns
The receiver error model.
Reimplemented from ns3::TcpGeneralTest.
Definition at line 306 of file tcp-rate-ops-test.cc.
References ns3::TcpSeqErrorModel::AddSeqToKill(), m_toDrop, ns3::MakeCallback(), PktDropped(), and ns3::TcpGeneralErrorModel::SetDropCallback().
CreateSenderSocket()
Ptr< TcpSocketMsgBase > TcpRateLinuxWithSocketsTest::CreateSenderSocket (Ptr< Node > node) protected virtual
Create and install the socket to install on the sender.
Parameters
node sender node pointer
Returns
the socket to be installed in the sender
Reimplemented from ns3::TcpGeneralTest.
Definition at line 286 of file tcp-rate-ops-test.cc.
References m_congCtl, and ns3::TcpSocketBase::SetCongestionControlAlgorithm().
FinalChecks()
void TcpRateLinuxWithSocketsTest::FinalChecks () protected virtual
Do the final checks.
Reimplemented from ns3::TcpGeneralTest.
Definition at line 387 of file tcp-rate-ops-test.cc.
PktDropped()
void TcpRateLinuxWithSocketsTest::PktDropped (const Ipv4Header & ipH, const TcpHeader & tcpH, Ptr< const Packet > p) protected
Called when a packet is dropped.
Parameters
ipH The IP header.
tcpH The TCP header.
p The packet.
Definition at line 320 of file tcp-rate-ops-test.cc.
References ns3::TcpHeader::GetSequenceNumber(), ns3::Packet::GetSize(), and NS_LOG_DEBUG.
Referenced by CreateReceiverErrorModel().
RateSampleUpdatedTrace()
void TcpRateLinuxWithSocketsTest::RateSampleUpdatedTrace (const TcpRateLinux::TcpRateSample & sample) protected virtual
Track the rate sample value of TcpRateLinux.
Parameters
sample updated value of TcpRateSample.
Definition at line 366 of file tcp-rate-ops-test.cc.
References m_isDupAck, m_prevRateSample, m_sackEnabled, NS_LOG_DEBUG, and NS_TEST_ASSERT_MSG_EQ.
RateUpdatedTrace()
void TcpRateLinuxWithSocketsTest::RateUpdatedTrace (const TcpRateLinux::TcpRateConnection & rate) protected virtual
Track the rate value of TcpRateLinux.
Parameters
rate updated value of TcpRate.
Definition at line 353 of file tcp-rate-ops-test.cc.
References m_bytesInFlight, m_prevRate, ns3::Now(), NS_LOG_DEBUG, NS_TEST_ASSERT_MSG_EQ, and NS_TEST_ASSERT_MSG_GT_OR_EQ.
Rx()
void TcpRateLinuxWithSocketsTest::Rx (const Ptr< const Packet > p, const TcpHeader & h, SocketWho who) protected virtual
Receive a packet.
Parameters
p The packet.
h The TCP header.
who Who the socket belongs to (sender or receiver).
Reimplemented from ns3::TcpGeneralTest.
Definition at line 327 of file tcp-rate-ops-test.cc.
References ns3::TcpHeader::GetAckNumber(), ns3::TcpHeader::GetFlags(), m_isDupAck, m_lastAckRecv, and ns3::TcpGeneralTest::SENDER.
Member Data Documentation
m_bytesInFlight
uint32_t TcpRateLinuxWithSocketsTest::m_bytesInFlight {0} private
Bytes inflight.
Definition at line 270 of file tcp-rate-ops-test.cc.
Referenced by BytesInFlightTrace(), and RateUpdatedTrace().
m_congCtl
Ptr<MimicCongControl> TcpRateLinuxWithSocketsTest::m_congCtl private
Dummy congestion control.
Definition at line 267 of file tcp-rate-ops-test.cc.
Referenced by CreateSenderSocket().
m_isDupAck
bool TcpRateLinuxWithSocketsTest::m_isDupAck private
Whether ACK is DupAck.
Definition at line 272 of file tcp-rate-ops-test.cc.
Referenced by RateSampleUpdatedTrace(), and Rx().
m_lastAckRecv
SequenceNumber32 TcpRateLinuxWithSocketsTest::m_lastAckRecv {SequenceNumber32 (1)} private
Last ACK received.
Definition at line 271 of file tcp-rate-ops-test.cc.
Referenced by Rx().
m_prevRate
TcpRateLinux::TcpRateConnection TcpRateLinuxWithSocketsTest::m_prevRate private
Previous rate.
Definition at line 273 of file tcp-rate-ops-test.cc.
Referenced by RateUpdatedTrace().
m_prevRateSample
TcpRateLinux::TcpRateSample TcpRateLinuxWithSocketsTest::m_prevRateSample private
Previous rate sample.
Definition at line 274 of file tcp-rate-ops-test.cc.
Referenced by RateSampleUpdatedTrace().
m_sackEnabled
bool TcpRateLinuxWithSocketsTest::m_sackEnabled private
Sack Variable.
Definition at line 268 of file tcp-rate-ops-test.cc.
Referenced by ConfigureEnvironment(), and RateSampleUpdatedTrace().
m_toDrop
std::vector<uint32_t> TcpRateLinuxWithSocketsTest::m_toDrop private
List of SequenceNumber to drop.
Definition at line 269 of file tcp-rate-ops-test.cc.
Referenced by CreateReceiverErrorModel().
The documentation for this class was generated from the following file:
src/internet/test/tcp-rate-ops-test.cc