ns-3: TestSimpleFrameCaptureModel Class Reference
TestSimpleFrameCaptureModel Class Reference
Wifi Models » wifi module tests | Test suites
Simple frame capture model test.
Public Member Functions
TestSimpleFrameCaptureModel ()
virtual ~TestSimpleFrameCaptureModel ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Member Functions
virtual void DoSetup (void)
Implementation to do any local setup required for this TestCase.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void Expect1000BPacketDropped ()
Verify whether 1000 bytes packet has been dropped.
void Expect1000BPacketReceived ()
Verify whether 1000 bytes packet has been received.
void Expect1500BPacketDropped ()
Verify whether 1500 bytes packet has been dropped.
void Expect1500BPacketReceived ()
Verify whether 1500 bytes packet has been received.
void Reset (void)
Reset function.
void RxDropped (Ptr< const Packet > p, WifiPhyRxfailureReason reason)
RX dropped function.
void RxSuccess (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector, std::vector< bool > statusPerMpdu)
Spectrum wifi receive success function.
void SendPacket (double rxPowerDbm, uint32_t packetSize)
Send packet function.
Private Attributes
Ptr< SpectrumWifiPhy > m_phy
Phy.
bool m_rxDropped1000B
count dropped packets with 1000B payload
bool m_rxDropped1500B
count dropped packets with 1500B payload
bool m_rxSuccess1000B
count received packets with 1000B payload
bool m_rxSuccess1500B
count received packets with 1500B payload
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Detailed Description
Simple frame capture model test.
Definition at line 901 of file wifi-phy-reception-test.cc.
Constructor & Destructor Documentation
TestSimpleFrameCaptureModel()
TestSimpleFrameCaptureModel::TestSimpleFrameCaptureModel ()
Definition at line 963 of file wifi-phy-reception-test.cc.
~TestSimpleFrameCaptureModel()
TestSimpleFrameCaptureModel::~TestSimpleFrameCaptureModel () virtual
Definition at line 1060 of file wifi-phy-reception-test.cc.
References m_phy.
Member Function Documentation
DoRun()
void TestSimpleFrameCaptureModel::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 1089 of file wifi-phy-reception-test.cc.
References ns3::WifiPhy::AssignStreams(), Expect1000BPacketDropped(), Expect1000BPacketReceived(), Expect1500BPacketDropped(), Expect1500BPacketReceived(), m_phy, ns3::MicroSeconds(), Reset(), ns3::Seconds(), and SendPacket().
DoSetup()
void TestSimpleFrameCaptureModel::DoSetup (void) protected virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test setup before DoRun is invoked.
Reimplemented from ns3::TestCase.
Definition at line 1066 of file wifi-phy-reception-test.cc.
References CHANNEL_NUMBER, ns3::SpectrumWifiPhy::ConfigureStandard(), FREQUENCY, m_phy, ns3::MakeCallback(), ns3::MicroSeconds(), RxDropped(), RxSuccess(), ns3::ObjectBase::SetAttribute(), ns3::SpectrumWifiPhy::SetChannelNumber(), ns3::WifiPhy::SetErrorRateModel(), ns3::WifiPhy::SetFrameCaptureModel(), ns3::SpectrumWifiPhy::SetFrequency(), ns3::WifiPhy::SetPreambleDetectionModel(), ns3::WifiPhy::SetReceiveOkCallback(), ns3::ObjectBase::TraceConnectWithoutContext(), and ns3::WIFI_PHY_STANDARD_80211ax_5GHZ.
Expect1000BPacketDropped()
void TestSimpleFrameCaptureModel::Expect1000BPacketDropped () private
Verify whether 1000 bytes packet has been dropped.
Definition at line 1049 of file wifi-phy-reception-test.cc.
References m_rxDropped1000B, and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
Expect1000BPacketReceived()
void TestSimpleFrameCaptureModel::Expect1000BPacketReceived () private
Verify whether 1000 bytes packet has been received.
Definition at line 1038 of file wifi-phy-reception-test.cc.
References m_rxSuccess1000B, and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
Expect1500BPacketDropped()
void TestSimpleFrameCaptureModel::Expect1500BPacketDropped () private
Verify whether 1500 bytes packet has been dropped.
Definition at line 1055 of file wifi-phy-reception-test.cc.
References m_rxDropped1500B, and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
Expect1500BPacketReceived()
void TestSimpleFrameCaptureModel::Expect1500BPacketReceived () private
Verify whether 1500 bytes packet has been received.
Definition at line 1044 of file wifi-phy-reception-test.cc.
References m_rxSuccess1500B, and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
Reset()
void TestSimpleFrameCaptureModel::Reset (void) private
Reset function.
Definition at line 1029 of file wifi-phy-reception-test.cc.
References m_rxDropped1000B, m_rxDropped1500B, m_rxSuccess1000B, and m_rxSuccess1500B.
Referenced by DoRun().
RxDropped()
void TestSimpleFrameCaptureModel::RxDropped (Ptr< const Packet > p, WifiPhyRxfailureReason reason) private
RX dropped function.
Parameters
p the packet
reason the reason
Definition at line 1015 of file wifi-phy-reception-test.cc.
References ns3::Packet::GetSize(), m_rxDropped1000B, m_rxDropped1500B, and NS_LOG_FUNCTION.
Referenced by DoSetup().
RxSuccess()
void TestSimpleFrameCaptureModel::RxSuccess (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector, std::vector< bool > statusPerMpdu) private
Spectrum wifi receive success function.
Parameters
psdu the PSDU
snr the SNR
txVector the transmit vector
statusPerMpdu reception status per MPDU
Definition at line 1000 of file wifi-phy-reception-test.cc.
References ns3::WifiPsdu::GetSize(), ns3::WifiPsdu::IsAggregate(), ns3::WifiPsdu::IsSingle(), m_rxSuccess1000B, m_rxSuccess1500B, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by DoSetup().
SendPacket()
void TestSimpleFrameCaptureModel::SendPacket (double rxPowerDbm, uint32_t packetSize) private
Send packet function.
Parameters
rxPowerDbm the transmit power in dBm
packetSize the size of the packet in bytes
Definition at line 973 of file wifi-phy-reception-test.cc.
References ns3::WifiPhy::CalculateTxDuration(), CHANNEL_WIDTH, ns3::lorawan::DbmToW(), ns3::SpectrumSignalParameters::duration, FREQUENCY, ns3::WifiPhy::GetFrequency(), ns3::WifiPsdu::GetSize(), GUARD_WIDTH, m_phy, packetSize, ns3::WifiSpectrumSignalParameters::ppdu, ns3::SpectrumSignalParameters::psd, ns3::WifiMacHeader::SetQosTid(), ns3::WifiMacHeader::SetType(), ns3::SpectrumWifiPhy::StartRx(), ns3::SpectrumSignalParameters::txPhy, ns3::WIFI_MAC_QOSDATA, and ns3::WIFI_PREAMBLE_HE_SU.
Referenced by DoRun().
Member Data Documentation
m_phy
Ptr<SpectrumWifiPhy> TestSimpleFrameCaptureModel::m_phy private
Phy.
Definition at line 955 of file wifi-phy-reception-test.cc.
Referenced by ~TestSimpleFrameCaptureModel(), DoRun(), DoSetup(), and SendPacket().
m_rxDropped1000B
bool TestSimpleFrameCaptureModel::m_rxDropped1000B private
count dropped packets with 1000B payload
Definition at line 959 of file wifi-phy-reception-test.cc.
Referenced by Expect1000BPacketDropped(), Reset(), and RxDropped().
m_rxDropped1500B
bool TestSimpleFrameCaptureModel::m_rxDropped1500B private
count dropped packets with 1500B payload
Definition at line 960 of file wifi-phy-reception-test.cc.
Referenced by Expect1500BPacketDropped(), Reset(), and RxDropped().
m_rxSuccess1000B
bool TestSimpleFrameCaptureModel::m_rxSuccess1000B private
count received packets with 1000B payload
Definition at line 957 of file wifi-phy-reception-test.cc.
Referenced by Expect1000BPacketReceived(), Reset(), and RxSuccess().
m_rxSuccess1500B
bool TestSimpleFrameCaptureModel::m_rxSuccess1500B private
count received packets with 1500B payload
Definition at line 958 of file wifi-phy-reception-test.cc.
Referenced by Expect1500BPacketReceived(), Reset(), and RxSuccess().
The documentation for this class was generated from the following file:
src/wifi/test/wifi-phy-reception-test.cc