ns-3: ns3::PbbAddressBlockIpv6 Class Reference
ns3::PbbAddressBlockIpv6 Class Reference
Concrete IPv6 specific PbbAddressBlock.
#include "packetbb.h"
Public Member Functions
PbbAddressBlockIpv6 ()
virtual ~PbbAddressBlockIpv6 ()
Public Member Functions inherited from ns3::PbbAddressBlock
PbbAddressBlock ()
virtual ~PbbAddressBlock ()
Address AddressBack (void) const
AddressIterator AddressBegin (void)
ConstAddressIterator AddressBegin (void) const
void AddressClear (void)
Removes all addresses from this block.
bool AddressEmpty (void) const
AddressIterator AddressEnd (void)
ConstAddressIterator AddressEnd (void) const
AddressIterator AddressErase (AddressIterator first, AddressIterator last)
Removes all addresses from [first, last) (includes first, not includes last).
AddressIterator AddressErase (AddressIterator position)
Removes the address at the specified position.
Address AddressFront (void) const
AddressIterator AddressInsert (AddressIterator position, const Address value)
Inserts an address at the specified position in this block.
void AddressPopBack (void)
Removes an address from the back of this block.
void AddressPopFront (void)
Removes an address from the front of this block.
void AddressPushBack (Address address)
Appends an address to the back of this block.
void AddressPushFront (Address address)
Prepends an address to the front of this block.
int AddressSize (void) const
void Deserialize (Buffer::Iterator &start)
Deserializes an address block from the specified buffer.
uint32_t GetSerializedSize (void) const
bool operator!= (const PbbAddressBlock &other) const
Inequality operator for PbbAddressBlock.
bool operator== (const PbbAddressBlock &other) const
Equality operator for PbbAddressBlock.
uint8_t PrefixBack (void) const
PrefixIterator PrefixBegin (void)
ConstPrefixIterator PrefixBegin (void) const
void PrefixClear (void)
Removes all prefixes from this block.
bool PrefixEmpty (void) const
PrefixIterator PrefixEnd (void)
ConstPrefixIterator PrefixEnd (void) const
PrefixIterator PrefixErase (PrefixIterator first, PrefixIterator last)
Removes all prefixes from [first, last) (includes first, not includes last).
PrefixIterator PrefixErase (PrefixIterator position)
Removes the prefix at the specified position.
uint8_t PrefixFront (void) const
PrefixIterator PrefixInsert (PrefixIterator position, const uint8_t value)
Inserts a prefix at the specified position in this block.
void PrefixPopBack (void)
Removes a prefix from the back of this block.
void PrefixPopFront (void)
Removes a prefix from the front of this block.
void PrefixPushBack (uint8_t prefix)
Appends a prefix to the back of this block.
void PrefixPushFront (uint8_t prefix)
Prepends a prefix to the front of this block.
int PrefixSize (void) const
void Print (std::ostream &os) const
Pretty-prints the contents of this address block.
void Print (std::ostream &os, int level) const
Pretty-prints the contents of this address block, with specified indentation.
void Serialize (Buffer::Iterator &start) const
Serializes this address block into the specified buffer.
Ptr< PbbAddressTlv > TlvBack (void)
const Ptr< PbbAddressTlv > TlvBack (void) const
TlvIterator TlvBegin (void)
ConstTlvIterator TlvBegin (void) const
void TlvClear (void)
Removes all address TLVs from this block.
bool TlvEmpty (void) const
TlvIterator TlvEnd (void)
ConstTlvIterator TlvEnd (void) const
TlvIterator TlvErase (TlvIterator first, TlvIterator last)
Removes all address TLVs from [first, last) (includes first, not includes last).
TlvIterator TlvErase (TlvIterator position)
Removes the address TLV at the specified position.
Ptr< PbbAddressTlv > TlvFront (void)
const Ptr< PbbAddressTlv > TlvFront (void) const
TlvIterator TlvInsert (TlvIterator position, const Ptr< PbbTlv > value)
Inserts an address TLV at the specified position in this block.
void TlvPopBack (void)
Removes an address TLV from the back of this message.
void TlvPopFront (void)
Removes an address TLV from the front of this message.
void TlvPushBack (Ptr< PbbAddressTlv > address)
Appends an address TLV to the back of this message.
void TlvPushFront (Ptr< PbbAddressTlv > address)
Prepends an address TLV to the front of this message.
int TlvSize (void) const
Public Member Functions inherited from ns3::SimpleRefCount< PbbAddressBlock >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Protected Member Functions
virtual Address DeserializeAddress (uint8_t *buffer) const
Deserialize one address.
virtual uint8_t GetAddressLength (void) const
Returns address length.
virtual void PrintAddress (std::ostream &os, ConstAddressIterator iter) const
Print one or more addresses.
virtual void SerializeAddress (uint8_t *buffer, ConstAddressIterator iter) const
Serialize one or more addresses.
Additional Inherited Members
Public Types inherited from ns3::PbbAddressBlock
typedef std::list< Address >::iterator AddressIterator
Address iterator.
typedef std::list< Address >::const_iterator ConstAddressIterator
Address const iterator.
typedef std::list< uint8_t >::const_iterator ConstPrefixIterator
Prefix const iterator.
typedef PbbAddressTlvBlock::ConstIterator ConstTlvIterator
tlvblock const iterator
typedef std::list< uint8_t >::iterator PrefixIterator
Prefix iterator.
typedef PbbAddressTlvBlock::Iterator TlvIterator
tlvblock iterator
Detailed Description
Concrete IPv6 specific PbbAddressBlock.
This address block will only contain IPv6 addresses.
Definition at line 1639 of file packetbb.h.
Constructor & Destructor Documentation
PbbAddressBlockIpv6()
ns3::PbbAddressBlockIpv6::PbbAddressBlockIpv6 ()
Definition at line 2608 of file packetbb.cc.
References NS_LOG_FUNCTION.
~PbbAddressBlockIpv6()
ns3::PbbAddressBlockIpv6::~PbbAddressBlockIpv6 () virtual
Definition at line 2613 of file packetbb.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DeserializeAddress()
Address ns3::PbbAddressBlockIpv6::DeserializeAddress (uint8_t * buffer) const protected virtual
Deserialize one address.
Parameters
buffer the buffer to deserialize from
Returns
the address
Implements ns3::PbbAddressBlock.
Definition at line 2633 of file packetbb.cc.
References ns3::Ipv6Address::Deserialize(), and NS_LOG_FUNCTION.
GetAddressLength()
uint8_t ns3::PbbAddressBlockIpv6::GetAddressLength (void) const protected virtual
Returns address length.
Returns
Address length
Implements ns3::PbbAddressBlock.
Definition at line 2619 of file packetbb.cc.
References NS_LOG_FUNCTION.
PrintAddress()
void ns3::PbbAddressBlockIpv6::PrintAddress (std::ostream & os, ConstAddressIterator iter) const protected virtual
Print one or more addresses.
Parameters
os the output stream
iter the iterator to the addresses
Implements ns3::PbbAddressBlock.
Definition at line 2640 of file packetbb.cc.
References ns3::Ipv6Address::ConvertFrom(), NS_LOG_FUNCTION, and ns3::Ipv6Address::Print().
SerializeAddress()
void ns3::PbbAddressBlockIpv6::SerializeAddress (uint8_t * buffer, ConstAddressIterator iter) const protected virtual
Serialize one or more addresses.
Parameters
buffer the buffer to serialize to
iter the iterator to the addresses
Implements ns3::PbbAddressBlock.
Definition at line 2626 of file packetbb.cc.
References ns3::Ipv6Address::ConvertFrom(), NS_LOG_FUNCTION, and ns3::Ipv6Address::Serialize().
The documentation for this class was generated from the following files:
src/network/utils/packetbb.h
src/network/utils/packetbb.cc