ns-3: ns3::Icmpv6ParameterError Class Reference
ns3::Icmpv6ParameterError Class Reference
Internet » IPv6 classes and sub-modules » ICMPv6 protocol and associated headers.
ICMPv6 Error Parameter Error header.
#include "icmpv6-header.h"
Public Member Functions
Icmpv6ParameterError ()
Constructor.
virtual ~Icmpv6ParameterError ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
Ptr< Packet > GetPacket () const
Get the incorrect packet.
uint32_t GetPtr () const
Get the pointer field.
virtual uint32_t GetSerializedSize () const
Get the serialized size.
virtual void Print (std::ostream &os) const
Print information.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetPacket (Ptr< Packet > p)
Set the incorrect packet.
void SetPtr (uint32_t ptr)
Set the pointer field.
Public Member Functions inherited from ns3::Icmpv6Header
Icmpv6Header ()
Constructor.
virtual ~Icmpv6Header ()
Destructor.
void CalculatePseudoHeaderChecksum (Ipv6Address src, Ipv6Address dst, uint16_t length, uint8_t protocol)
Calculate pseudo header checksum for IPv6.
uint16_t GetChecksum () const
Get the checksum.
uint8_t GetCode () const
Get the code field.
uint8_t GetType () const
Get the type field.
void SetChecksum (uint16_t checksum)
Set the checksum.
void SetCode (uint8_t code)
Set the code field.
void SetType (uint8_t type)
Set the type.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the UID of this class.
Static Public Member Functions inherited from ns3::Icmpv6Header
static TypeId GetTypeId ()
Get the UID of this class.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Ptr< Packet > m_packet
The incorrect packet.
uint32_t m_ptr
The pointer field.
Additional Inherited Members
Public Types inherited from ns3::Icmpv6Header
enum ErrorDestinationUnreachable_e {
ICMPV6_NO_ROUTE = 0, ICMPV6_ADM_PROHIBITED, ICMPV6_NOT_NEIGHBOUR, ICMPV6_ADDR_UNREACHABLE,
ICMPV6_PORT_UNREACHABLE
}
ICMPv6 error code : Destination Unreachable.
enum ErrorParameterError_e { ICMPV6_MALFORMED_HEADER = 0, ICMPV6_UNKNOWN_NEXT_HEADER, ICMPV6_UNKNOWN_OPTION }
ICMPv6 error code : Parameter Error.
enum ErrorTimeExceeded_e { ICMPV6_HOPLIMIT = 0, ICMPV6_FRAGTIME }
ICMPv6 error code : Time Exceeded.
enum OptionType_e {
ICMPV6_OPT_LINK_LAYER_SOURCE = 1, ICMPV6_OPT_LINK_LAYER_TARGET, ICMPV6_OPT_PREFIX, ICMPV6_OPT_REDIRECTED,
ICMPV6_OPT_MTU
}
ICMPv6 Option type code.
enum Type_e {
ICMPV6_ERROR_DESTINATION_UNREACHABLE = 1, ICMPV6_ERROR_PACKET_TOO_BIG, ICMPV6_ERROR_TIME_EXCEEDED, ICMPV6_ERROR_PARAMETER_ERROR,
ICMPV6_ECHO_REQUEST = 128, ICMPV6_ECHO_REPLY, ICMPV6_SUBSCRIBE_REQUEST, ICMPV6_SUBSCRIBE_REPORT,
ICMPV6_SUBSCRIVE_END, ICMPV6_ND_ROUTER_SOLICITATION, ICMPV6_ND_ROUTER_ADVERTISEMENT, ICMPV6_ND_NEIGHBOR_SOLICITATION,
ICMPV6_ND_NEIGHBOR_ADVERTISEMENT, ICMPV6_ND_REDIRECTION, ICMPV6_ROUTER_RENUMBER, ICMPV6_INFORMATION_REQUEST,
ICMPV6_INFORMATION_RESPONSE, ICMPV6_INVERSE_ND_SOLICITATION, ICMPV6_INVERSE_ND_ADVERSTISEMENT, ICMPV6_MLDV2_SUBSCRIBE_REPORT,
ICMPV6_MOBILITY_HA_DISCOVER_REQUEST, ICMPV6_MOBILITY_HA_DISCOVER_RESPONSE, ICMPV6_MOBILITY_MOBILE_PREFIX_SOLICITATION, ICMPV6_SECURE_ND_CERTIFICATE_PATH_SOLICITATION,
ICMPV6_SECURE_ND_CERTIFICATE_PATH_ADVERTISEMENT, ICMPV6_EXPERIMENTAL_MOBILITY
}
ICMPv6 type code.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Icmpv6Header
bool m_calcChecksum
Checksum enable or not.
uint16_t m_checksum
The checksum.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
ICMPv6 Error Parameter Error header.
Definition at line 1282 of file icmpv6-header.h.
Constructor & Destructor Documentation
Icmpv6ParameterError()
ns3::Icmpv6ParameterError::Icmpv6ParameterError ()
Constructor.
Definition at line 1370 of file icmpv6-header.cc.
References ns3::Icmpv6Header::ICMPV6_ERROR_PARAMETER_ERROR, NS_LOG_FUNCTION, and ns3::Icmpv6Header::SetType().
~Icmpv6ParameterError()
ns3::Icmpv6ParameterError::~Icmpv6ParameterError () virtual
Destructor.
Definition at line 1378 of file icmpv6-header.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Deserialize()
uint32_t ns3::Icmpv6ParameterError::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start start offset
Returns
length of packet
Reimplemented from ns3::Icmpv6Header.
Definition at line 1445 of file icmpv6-header.cc.
References data, GetSerializedSize(), ns3::Icmpv6Header::m_checksum, m_packet, NS_LOG_FUNCTION, ns3::Buffer::Iterator::Read(), ns3::Buffer::Iterator::ReadNtohU32(), ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU8(), ns3::Icmpv6Header::SetCode(), SetPtr(), ns3::Icmpv6Header::SetType(), and visualizer.core::start().
GetInstanceTypeId()
TypeId ns3::Icmpv6ParameterError::GetInstanceTypeId () const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::Icmpv6Header.
Definition at line 1364 of file icmpv6-header.cc.
References GetTypeId(), and NS_LOG_FUNCTION.
GetPacket()
Ptr< Packet > ns3::Icmpv6ParameterError::GetPacket () const
Get the incorrect packet.
Returns
the incorrect packet
Definition at line 1383 of file icmpv6-header.cc.
References m_packet, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::HandleParameterError().
GetPtr()
uint32_t ns3::Icmpv6ParameterError::GetPtr () const
Get the pointer field.
Returns
pointer value
Definition at line 1396 of file icmpv6-header.cc.
References m_ptr, and NS_LOG_FUNCTION.
Referenced by Print(), and Serialize().
GetSerializedSize()
uint32_t ns3::Icmpv6ParameterError::GetSerializedSize () const virtual
Get the serialized size.
Returns
serialized size
Reimplemented from ns3::Icmpv6Header.
Definition at line 1414 of file icmpv6-header.cc.
References ns3::Packet::GetSize(), m_packet, and NS_LOG_FUNCTION.
Referenced by Deserialize().
GetTypeId()
TypeId ns3::Icmpv6ParameterError::GetTypeId () static
Get the UID of this class.
Returns
UID
Definition at line 1354 of file icmpv6-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::Icmpv6ParameterError::Print (std::ostream & os) const virtual
Print information.
Parameters
os output stream
Reimplemented from ns3::Icmpv6Header.
Definition at line 1408 of file icmpv6-header.cc.
References ns3::Icmpv6Header::GetChecksum(), ns3::Icmpv6Header::GetCode(), GetPtr(), ns3::Icmpv6Header::GetType(), and NS_LOG_FUNCTION.
Serialize()
void ns3::Icmpv6ParameterError::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start start offset
Reimplemented from ns3::Icmpv6Header.
Definition at line 1420 of file icmpv6-header.cc.
References ns3::Buffer::Iterator::CalculateIpChecksum(), ns3::Packet::CopyData(), ns3::Icmpv6Header::GetChecksum(), ns3::Icmpv6Header::GetCode(), GetPtr(), ns3::Buffer::Iterator::GetSize(), ns3::Packet::GetSize(), ns3::Icmpv6Header::GetType(), m_packet, ns3::Buffer::Iterator::Next(), NS_LOG_FUNCTION, visualizer.core::start(), ns3::Buffer::Iterator::Write(), ns3::Buffer::Iterator::WriteHtonU16(), ns3::Buffer::Iterator::WriteHtonU32(), ns3::Buffer::Iterator::WriteU16(), and ns3::Buffer::Iterator::WriteU8().
SetPacket()
void ns3::Icmpv6ParameterError::SetPacket (Ptr< Packet > p)
Set the incorrect packet.
Parameters
p the incorrect packet
Definition at line 1389 of file icmpv6-header.cc.
References ns3::Packet::GetSize(), m_packet, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::SendErrorParameterError().
SetPtr()
void ns3::Icmpv6ParameterError::SetPtr (uint32_t ptr)
Set the pointer field.
Parameters
ptr byte where the error is located in the incorrect packet
Definition at line 1402 of file icmpv6-header.cc.
References m_ptr, and NS_LOG_FUNCTION.
Referenced by Deserialize(), and ns3::Icmpv6L4Protocol::SendErrorParameterError().
Member Data Documentation
m_packet
Ptr<Packet> ns3::Icmpv6ParameterError::m_packet private
The incorrect packet.
Definition at line 1361 of file icmpv6-header.h.
Referenced by Deserialize(), GetPacket(), GetSerializedSize(), Serialize(), and SetPacket().
m_ptr
uint32_t ns3::Icmpv6ParameterError::m_ptr private
The pointer field.
Definition at line 1366 of file icmpv6-header.h.
Referenced by GetPtr(), and SetPtr().
The documentation for this class was generated from the following files:
src/internet/model/icmpv6-header.h
src/internet/model/icmpv6-header.cc