ns-3: BasicEnergyUpdateTest Class Reference
BasicEnergyUpdateTest Class Reference
Test case of update remaining energy for BasicEnergySource and WifiRadioEnergyModel.
Public Member Functions
BasicEnergyUpdateTest ()
virtual ~BasicEnergyUpdateTest ()
bool DoRun (void)
Performs some tests involving state updates and the relative energy consumption.
Private Member Functions
bool StateSwitchTest (WifiPhyState state)
Private Attributes
ObjectFactory m_deviceEnergyModel
ObjectFactory m_energySource
double m_timeS
double m_tolerance
Detailed Description
Test case of update remaining energy for BasicEnergySource and WifiRadioEnergyModel.
Definition at line 44 of file basic-energy-model-test.cc.
Constructor & Destructor Documentation
BasicEnergyUpdateTest()
BasicEnergyUpdateTest::BasicEnergyUpdateTest ()
Definition at line 74 of file basic-energy-model-test.cc.
~BasicEnergyUpdateTest()
BasicEnergyUpdateTest::~BasicEnergyUpdateTest () virtual
Definition at line 80 of file basic-energy-model-test.cc.
Member Function Documentation
DoRun()
bool BasicEnergyUpdateTest::DoRun (void)
Performs some tests involving state updates and the relative energy consumption.
Returns
true is some error happened.
Definition at line 85 of file basic-energy-model-test.cc.
References CCA_BUSY, IDLE, RX, SLEEP, SWITCHING, and TX.
StateSwitchTest()
bool BasicEnergyUpdateTest::StateSwitchTest (WifiPhyState state) private
Parameters
state Radio state to switch to.
Returns
False if no error occurs.
Runs simulation for a while, check if final state & remaining energy is correctly updated.
Definition at line 126 of file basic-energy-model-test.cc.
References ns3::Object::AggregateObject(), ns3::EnergySource::AppendDeviceEnergyModel(), CCA_BUSY, ns3::WifiRadioEnergyModel::ChangeState(), ns3::Simulator::Destroy(), ns3::EnergySource::FindDeviceEnergyModels(), ns3::DeviceEnergyModelContainer::Get(), ns3::WifiRadioEnergyModel::GetCcaBusyCurrentA(), ns3::WifiRadioEnergyModel::GetCurrentState(), ns3::WifiRadioEnergyModel::GetIdleCurrentA(), ns3::BasicEnergySource::GetInitialEnergy(), ns3::DeviceEnergyModelContainer::GetN(), ns3::BasicEnergySource::GetRemainingEnergy(), ns3::WifiRadioEnergyModel::GetRxCurrentA(), ns3::WifiRadioEnergyModel::GetSleepCurrentA(), ns3::BasicEnergySource::GetSupplyVoltage(), ns3::WifiRadioEnergyModel::GetSwitchingCurrentA(), ns3::WifiRadioEnergyModel::GetTxCurrentA(), IDLE, max, NS_FATAL_ERROR, NS_LOG_DEBUG, OFF, ns3::Simulator::Run(), RX, ns3::Simulator::Schedule(), ns3::Seconds(), ns3::WifiRadioEnergyModel::SetEnergySource(), ns3::BasicEnergySource::SetInitialEnergy(), ns3::EnergySource::SetNode(), SLEEP, ns3::Simulator::Stop(), SWITCHING, TX, and ns3::BasicEnergySource::UpdateEnergySource().
Member Data Documentation
m_deviceEnergyModel
ObjectFactory BasicEnergyUpdateTest::m_deviceEnergyModel private
Definition at line 71 of file basic-energy-model-test.cc.
m_energySource
ObjectFactory BasicEnergyUpdateTest::m_energySource private
Definition at line 70 of file basic-energy-model-test.cc.
m_timeS
double BasicEnergyUpdateTest::m_timeS private
Definition at line 67 of file basic-energy-model-test.cc.
m_tolerance
double BasicEnergyUpdateTest::m_tolerance private
Definition at line 68 of file basic-energy-model-test.cc.
The documentation for this class was generated from the following file:
src/energy/examples/basic-energy-model-test.cc