ns-3: ns3::PacketSocketHelper Class Reference
ns3::PacketSocketHelper Class Reference
Give ns3::PacketSocket powers to ns3::Node.
#include "packet-socket-helper.h"
Public Member Functions
void Install (NodeContainer c) const
For each node in the provided container, aggregate an instance of a ns3::PacketSocketFactory.
void Install (Ptr< Node > node) const
Aggregate an instance of a ns3::PacketSocketFactory onto the provided node.
void Install (std::string nodeName) const
Aggregate an instance of a ns3::PacketSocketFactory onto the provided node.
Detailed Description
Give ns3::PacketSocket powers to ns3::Node.
Definition at line 31 of file packet-socket-helper.h.
Member Function Documentation
Install() [1/3]
void ns3::PacketSocketHelper::Install (NodeContainer c) const
For each node in the provided container, aggregate an instance of a ns3::PacketSocketFactory.
Parameters
c NodeContainer of the set of nodes to aggregate the ns3::PacketSocketFactory on.
Definition at line 28 of file packet-socket-helper.cc.
References ns3::NodeContainer::Begin(), ns3::NodeContainer::End(), and Install().
Install() [2/3]
void ns3::PacketSocketHelper::Install (Ptr< Node > node) const
Aggregate an instance of a ns3::PacketSocketFactory onto the provided node.
Parameters
node Node on which to aggregate the ns3::PacketSocketFactory.
Definition at line 37 of file packet-socket-helper.cc.
References ns3::Object::AggregateObject().
Referenced by PacketSocketAppsTest::DoRun(), SpectrumIdealPhyTestCase::DoRun(), CsmaPacketSocketTestCase::DoRun(), BlockAckAggregationDisabledTest::DoRun(), PreservePacketsInAmpdus::DoRun(), Bug730TestCase::DoRun(), QosFragmentationTestCase::DoRun(), Bug2222TestCase::DoRun(), Install(), OcbWifiMacTestCase::PostDeviceConfiguration(), Experiment::Run(), and NetAnimExperiment::Run().
Install() [3/3]
void ns3::PacketSocketHelper::Install (std::string nodeName) const
Aggregate an instance of a ns3::PacketSocketFactory onto the provided node.
Parameters
nodeName The name of the node on which to aggregate the ns3::PacketSocketFactory.
Definition at line 44 of file packet-socket-helper.cc.
References Install().
The documentation for this class was generated from the following files:
src/network/helper/packet-socket-helper.h
src/network/helper/packet-socket-helper.cc