ns-3: ns3::LteEnbRrcSapUser Class Reference
ns3::LteEnbRrcSapUser Class Reference abstract
Part of the RRC protocol.
#include "lte-rrc-sap.h"
Classes
struct SetupUeParameters
SetupUeParameters structure.
Public Member Functions
virtual RrcConnectionReconfiguration DecodeHandoverCommand (Ptr< Packet > p)=0
Decode handover command.
virtual HandoverPreparationInfo DecodeHandoverPreparationInformation (Ptr< Packet > p)=0
Decode handover prepration information.
virtual Ptr< Packet > EncodeHandoverCommand (RrcConnectionReconfiguration msg)=0
Encode handover command.
virtual Ptr< Packet > EncodeHandoverPreparationInformation (HandoverPreparationInfo msg)=0
Encode handover prepration information.
virtual void RemoveUe (uint16_t rnti)=0
Remove UE function.
virtual void SendRrcConnectionReconfiguration (uint16_t rnti, RrcConnectionReconfiguration msg)=0
Send an RRCConnectionReconfiguration message to a UE during an RRC connection reconfiguration procedure (Section 5.3.5 of TS 36.331).
virtual void SendRrcConnectionReestablishment (uint16_t rnti, RrcConnectionReestablishment msg)=0
Send an RRCConnectionReestablishment message to a UE during an RRC connection re-establishment procedure (Section 5.3.7 of TS 36.331).
virtual void SendRrcConnectionReestablishmentReject (uint16_t rnti, RrcConnectionReestablishmentReject msg)=0
Send an RRCConnectionReestablishmentReject message to a UE during an RRC connection re-establishment procedure (Section 5.3.7 of TS 36.331).
virtual void SendRrcConnectionReject (uint16_t rnti, RrcConnectionReject msg)=0
Send an RRCConnectionReject message to a UE during an RRC connection establishment procedure (Section 5.3.3 of TS 36.331).
virtual void SendRrcConnectionRelease (uint16_t rnti, RrcConnectionRelease msg)=0
Send an RRCConnectionRelease message to a UE during an RRC connection release procedure (Section 5.3.8 of TS 36.331).
virtual void SendRrcConnectionSetup (uint16_t rnti, RrcConnectionSetup msg)=0
Send an RRCConnectionSetup message to a UE during an RRC connection establishment procedure (Section 5.3.3 of TS 36.331).
virtual void SendSystemInformation (uint16_t cellId, SystemInformation msg)=0
Send a SystemInformation message to all attached UEs during a system information acquisition procedure (Section 5.2.2 of TS 36.331).
virtual void SetupUe (uint16_t rnti, SetupUeParameters params)=0
Setup UE function.
Public Member Functions inherited from ns3::LteRrcSap
virtual ~LteRrcSap ()
Additional Inherited Members
Public Types inherited from ns3::LteRrcSap
enum ReestablishmentCause { RECONFIGURATION_FAILURE, HANDOVER_FAILURE, OTHER_FAILURE }
ReestablishmentCause enumeration.
Static Public Member Functions inherited from ns3::LteRrcSap
static double ConvertPdschConfigDedicated2Double (PdschConfigDedicated pdschConfigDedicated)
Convert PDSCH config dedicated function.
Static Public Attributes inherited from ns3::LteRrcSap
static const uint8_t MaxReportCells = 8
Constraint values.
Detailed Description
Part of the RRC protocol.
This Service Access Point (SAP) is used by the eNB RRC to send messages to the UE RRC. Each method defined in this class corresponds to the transmission of a message that is defined in Section 6.2.2 of TS 36.331.
Definition at line 1081 of file lte-rrc-sap.h.
Member Function Documentation
DecodeHandoverCommand()
virtual RrcConnectionReconfiguration ns3::LteEnbRrcSapUser::DecodeHandoverCommand (Ptr< Packet > p) pure virtual
Decode handover command.
Parameters
p the packet
Returns
RrcConnectionReconfiguration
Implemented in ns3::MemberLteEnbRrcSapUser< C >.
DecodeHandoverPreparationInformation()
virtual HandoverPreparationInfo ns3::LteEnbRrcSapUser::DecodeHandoverPreparationInformation (Ptr< Packet > p) pure virtual
Decode handover prepration information.
Parameters
p the packet
Returns
HandoverPreparationInfo
Implemented in ns3::MemberLteEnbRrcSapUser< C >.
EncodeHandoverCommand()
virtual Ptr<Packet> ns3::LteEnbRrcSapUser::EncodeHandoverCommand (RrcConnectionReconfiguration msg) pure virtual
Encode handover command.
Parameters
msg RrcConnectionReconfiguration
Returns
the packet
Implemented in ns3::MemberLteEnbRrcSapUser< C >.
Referenced by ns3::LteEnbRrc::DoRecvHandoverRequest().
EncodeHandoverPreparationInformation()
virtual Ptr<Packet> ns3::LteEnbRrcSapUser::EncodeHandoverPreparationInformation (HandoverPreparationInfo msg) pure virtual
Encode handover prepration information.
Parameters
msg HandoverPreparationInfo
Returns
the packet
Implemented in ns3::MemberLteEnbRrcSapUser< C >.
RemoveUe()
virtual void ns3::LteEnbRrcSapUser::RemoveUe (uint16_t rnti) pure virtual
Remove UE function.
Parameters
rnti the RNTI
Implemented in ns3::MemberLteEnbRrcSapUser< C >.
Referenced by ns3::LteEnbRrc::RemoveUe().
SendRrcConnectionReconfiguration()
virtual void ns3::LteEnbRrcSapUser::SendRrcConnectionReconfiguration (uint16_t rnti, RrcConnectionReconfiguration msg) pure virtual
Send an RRCConnectionReconfiguration message to a UE during an RRC connection reconfiguration procedure (Section 5.3.5 of TS 36.331).
Parameters
rnti the RNTI of the destination UE
msg the message
Implemented in ns3::MemberLteEnbRrcSapUser< C >.
SendRrcConnectionReestablishment()
virtual void ns3::LteEnbRrcSapUser::SendRrcConnectionReestablishment (uint16_t rnti, RrcConnectionReestablishment msg) pure virtual
Send an RRCConnectionReestablishment message to a UE during an RRC connection re-establishment procedure (Section 5.3.7 of TS 36.331).
Parameters
rnti the RNTI of the destination UE
msg the message
Implemented in ns3::MemberLteEnbRrcSapUser< C >.
SendRrcConnectionReestablishmentReject()
virtual void ns3::LteEnbRrcSapUser::SendRrcConnectionReestablishmentReject (uint16_t rnti, RrcConnectionReestablishmentReject msg) pure virtual
Send an RRCConnectionReestablishmentReject message to a UE during an RRC connection re-establishment procedure (Section 5.3.7 of TS 36.331).
Parameters
rnti the RNTI of the destination UE
msg the message
Implemented in ns3::MemberLteEnbRrcSapUser< C >.
SendRrcConnectionReject()
virtual void ns3::LteEnbRrcSapUser::SendRrcConnectionReject (uint16_t rnti, RrcConnectionReject msg) pure virtual
Send an RRCConnectionReject message to a UE during an RRC connection establishment procedure (Section 5.3.3 of TS 36.331).
Parameters
rnti the RNTI of the destination UE
msg the message
Implemented in ns3::MemberLteEnbRrcSapUser< C >.
SendRrcConnectionRelease()
virtual void ns3::LteEnbRrcSapUser::SendRrcConnectionRelease (uint16_t rnti, RrcConnectionRelease msg) pure virtual
Send an RRCConnectionRelease message to a UE during an RRC connection release procedure (Section 5.3.8 of TS 36.331).
Parameters
rnti the RNTI of the destination UE
msg the message
Implemented in ns3::MemberLteEnbRrcSapUser< C >.
SendRrcConnectionSetup()
virtual void ns3::LteEnbRrcSapUser::SendRrcConnectionSetup (uint16_t rnti, RrcConnectionSetup msg) pure virtual
Send an RRCConnectionSetup message to a UE during an RRC connection establishment procedure (Section 5.3.3 of TS 36.331).
Parameters
rnti the RNTI of the destination UE
msg the message
Implemented in ns3::MemberLteEnbRrcSapUser< C >.
SendSystemInformation()
virtual void ns3::LteEnbRrcSapUser::SendSystemInformation (uint16_t cellId, SystemInformation msg) pure virtual
Send a SystemInformation message to all attached UEs during a system information acquisition procedure (Section 5.2.2 of TS 36.331).
Parameters
cellId cell ID
msg the message
Implemented in ns3::MemberLteEnbRrcSapUser< C >.
Referenced by ns3::LteEnbRrc::SendSystemInformation().
SetupUe()
virtual void ns3::LteEnbRrcSapUser::SetupUe (uint16_t rnti, SetupUeParameters params) pure virtual
Setup UE function.
Parameters
rnti the RNTI
params the setup UE parameters
Implemented in ns3::MemberLteEnbRrcSapUser< C >.
The documentation for this class was generated from the following file:
src/lte/model/lte-rrc-sap.h