ns-3: ns3::DlFramePrefixIe Class Reference
ns3::DlFramePrefixIe Class Reference
WiMAX Models
This class implements the DL Frame Prefix IE as described by IEEE-802.16 standard.
#include "ofdm-downlink-frame-prefix.h"
Public Member Functions
DlFramePrefixIe ()
~DlFramePrefixIe ()
uint8_t GetDiuc (void) const
Get DIUC field.
uint16_t GetLength (void) const
Get length field.
uint8_t GetPreamblePresent (void) const
Get preamble present field.
uint8_t GetRateId (void) const
Get rate ID field.
uint16_t GetSize (void) const
Get size field.
uint16_t GetStartTime (void) const
Get start time field.
Buffer::Iterator Read (Buffer::Iterator start)
Read item function.
void SetDiuc (uint8_t diuc)
Set DIUC field.
void SetLength (uint16_t length)
Set length field.
void SetPreamblePresent (uint8_t preamblePresent)
Set preamble present field.
void SetRateId (uint8_t rateId)
Set rate ID field.
void SetStartTime (uint16_t startTime)
Set start time field.
Buffer::Iterator Write (Buffer::Iterator start) const
Write item function.
Private Attributes
uint8_t m_diuc
DIUC.
uint16_t m_length
length
uint8_t m_preamblePresent
preamble present
uint8_t m_rateId
rate ID
uint16_t m_startTime
start time
Detailed Description
This class implements the DL Frame Prefix IE as described by IEEE-802.16 standard.
The DL Frame Prefix IE is contained in DLFP (Downlink Frame Prefix) in OFDM PHY
Definition at line 34 of file ofdm-downlink-frame-prefix.h.
Constructor & Destructor Documentation
DlFramePrefixIe()
ns3::DlFramePrefixIe::DlFramePrefixIe ()
Definition at line 27 of file ofdm-downlink-frame-prefix.cc.
~DlFramePrefixIe()
ns3::DlFramePrefixIe::~DlFramePrefixIe ()
Definition at line 36 of file ofdm-downlink-frame-prefix.cc.
Member Function Documentation
GetDiuc()
uint8_t ns3::DlFramePrefixIe::GetDiuc (void) const
Get DIUC field.
Returns
the DIUC
Definition at line 77 of file ofdm-downlink-frame-prefix.cc.
References m_diuc.
Referenced by ns3::OfdmDownlinkFramePrefix::Deserialize().
GetLength()
uint16_t ns3::DlFramePrefixIe::GetLength (void) const
Get length field.
Returns
the length
Definition at line 89 of file ofdm-downlink-frame-prefix.cc.
References m_length.
GetPreamblePresent()
uint8_t ns3::DlFramePrefixIe::GetPreamblePresent (void) const
Get preamble present field.
Returns
the preamble present
Definition at line 83 of file ofdm-downlink-frame-prefix.cc.
References m_preamblePresent.
GetRateId()
uint8_t ns3::DlFramePrefixIe::GetRateId (void) const
Get rate ID field.
Returns
the rate ID
Definition at line 71 of file ofdm-downlink-frame-prefix.cc.
References m_rateId.
GetSize()
uint16_t ns3::DlFramePrefixIe::GetSize (void) const
Get size field.
Returns
the size
Definition at line 101 of file ofdm-downlink-frame-prefix.cc.
Referenced by ns3::OfdmDownlinkFramePrefix::GetSerializedSize().
GetStartTime()
uint16_t ns3::DlFramePrefixIe::GetStartTime (void) const
Get start time field.
Returns
the start time
Definition at line 95 of file ofdm-downlink-frame-prefix.cc.
References m_startTime.
Read()
Buffer::Iterator ns3::DlFramePrefixIe::Read (Buffer::Iterator start)
Read item function.
Parameters
start the iterator
Returns
the updated iterator
Definition at line 119 of file ofdm-downlink-frame-prefix.cc.
References m_diuc, m_length, m_preamblePresent, m_rateId, m_startTime, ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
Referenced by ns3::OfdmDownlinkFramePrefix::Deserialize().
SetDiuc()
void ns3::DlFramePrefixIe::SetDiuc (uint8_t diuc)
Set DIUC field.
Parameters
diuc the DIUC
Definition at line 47 of file ofdm-downlink-frame-prefix.cc.
References m_diuc.
SetLength()
void ns3::DlFramePrefixIe::SetLength (uint16_t length)
Set length field.
Parameters
length the length
Definition at line 59 of file ofdm-downlink-frame-prefix.cc.
References m_length.
SetPreamblePresent()
void ns3::DlFramePrefixIe::SetPreamblePresent (uint8_t preamblePresent)
Set preamble present field.
Parameters
preamblePresent the preambel present
Definition at line 53 of file ofdm-downlink-frame-prefix.cc.
References m_preamblePresent.
SetRateId()
void ns3::DlFramePrefixIe::SetRateId (uint8_t rateId)
Set rate ID field.
Parameters
rateId the rate ID
Definition at line 41 of file ofdm-downlink-frame-prefix.cc.
References m_rateId.
SetStartTime()
void ns3::DlFramePrefixIe::SetStartTime (uint16_t startTime)
Set start time field.
Parameters
startTime the start time
Definition at line 65 of file ofdm-downlink-frame-prefix.cc.
References m_startTime, and startTime.
Write()
Buffer::Iterator ns3::DlFramePrefixIe::Write (Buffer::Iterator start) const
Write item function.
Parameters
start the iterator
Returns
the updated iterator
Definition at line 107 of file ofdm-downlink-frame-prefix.cc.
References m_diuc, m_length, m_preamblePresent, m_rateId, m_startTime, visualizer.core::start(), ns3::Buffer::Iterator::WriteU16(), and ns3::Buffer::Iterator::WriteU8().
Referenced by ns3::OfdmDownlinkFramePrefix::Serialize().
Member Data Documentation
m_diuc
uint8_t ns3::DlFramePrefixIe::m_diuc private
DIUC.
Definition at line 112 of file ofdm-downlink-frame-prefix.h.
Referenced by GetDiuc(), Read(), SetDiuc(), and Write().
m_length
uint16_t ns3::DlFramePrefixIe::m_length private
length
Definition at line 114 of file ofdm-downlink-frame-prefix.h.
Referenced by GetLength(), Read(), SetLength(), and Write().
m_preamblePresent
uint8_t ns3::DlFramePrefixIe::m_preamblePresent private
preamble present
Definition at line 113 of file ofdm-downlink-frame-prefix.h.
Referenced by GetPreamblePresent(), Read(), SetPreamblePresent(), and Write().
m_rateId
uint8_t ns3::DlFramePrefixIe::m_rateId private
rate ID
Definition at line 111 of file ofdm-downlink-frame-prefix.h.
Referenced by GetRateId(), Read(), SetRateId(), and Write().
m_startTime
uint16_t ns3::DlFramePrefixIe::m_startTime private
start time
Definition at line 115 of file ofdm-downlink-frame-prefix.h.
Referenced by GetStartTime(), Read(), SetStartTime(), and Write().
The documentation for this class was generated from the following files:
src/wimax/model/ofdm-downlink-frame-prefix.h
src/wimax/model/ofdm-downlink-frame-prefix.cc