ns-3: ns3::FileConfig Class Reference
ns3::FileConfig Class Reference abstract
Configuration Store/Load
base class for ConfigStore classes using files
#include "file-config.h"
Public Member Functions
virtual ~FileConfig ()
virtual void Attributes (void)=0
Load or save the attributes values.
virtual void Default (void)=0
Load or save the default values.
virtual void Global (void)=0
Load or save the global values.
virtual void SetFilename (std::string filename)=0
Set the file name.
Detailed Description
base class for ConfigStore classes using files
Definition at line 33 of file file-config.h.
Constructor & Destructor Documentation
~FileConfig()
ns3::FileConfig::~FileConfig () virtual
Definition at line 25 of file file-config.cc.
Member Function Documentation
Attributes()
virtual void ns3::FileConfig::Attributes (void) pure virtual
Load or save the attributes values.
Implemented in ns3::XmlConfigLoad, ns3::XmlConfigSave, ns3::RawTextConfigLoad, ns3::RawTextConfigSave, and ns3::NoneFileConfig.
Referenced by ns3::ConfigStore::ConfigureAttributes().
Default()
virtual void ns3::FileConfig::Default (void) pure virtual
Load or save the default values.
Implemented in ns3::XmlConfigLoad, ns3::XmlConfigSave, ns3::RawTextConfigLoad, ns3::RawTextConfigSave, and ns3::NoneFileConfig.
Referenced by ns3::ConfigStore::ConfigureDefaults().
Global()
virtual void ns3::FileConfig::Global (void) pure virtual
Load or save the global values.
Implemented in ns3::XmlConfigLoad, ns3::XmlConfigSave, ns3::RawTextConfigLoad, ns3::RawTextConfigSave, and ns3::NoneFileConfig.
Referenced by ns3::ConfigStore::ConfigureDefaults().
SetFilename()
virtual void ns3::FileConfig::SetFilename (std::string filename) pure virtual
Set the file name.
Parameters
filename the filename
Implemented in ns3::XmlConfigLoad, ns3::XmlConfigSave, ns3::RawTextConfigLoad, ns3::RawTextConfigSave, and ns3::NoneFileConfig.
Referenced by ns3::ConfigStore::ConfigStore().
The documentation for this class was generated from the following files:
src/config-store/model/file-config.h
src/config-store/model/file-config.cc