ns-3: ns3::lorawan::LoraInterferenceHelper Class Reference
ns3::lorawan::LoraInterferenceHelper Class Reference
Helper for LoraPhy that manages interference calculations.
#include "lora-interference-helper.h"
Classes
class Event
A class representing a signal in time.
Public Types
enum CollisionMatrix { GOURSAUD, ALOHA }
Public Member Functions
LoraInterferenceHelper ()
virtual ~LoraInterferenceHelper ()
Ptr< LoraInterferenceHelper::Event > Add (Time duration, double rxPower, uint8_t spreadingFactor, Ptr< Packet > packet, double frequencyMHz)
Add an event to the InterferenceHelper.
void CleanOldEvents (void)
Delete old events in this LoraInterferenceHelper.
void ClearAllEvents (void)
Delete all events in the LoraInterferenceHelper.
std::list< Ptr< LoraInterferenceHelper::Event > > GetInterferers ()
Get a list of the interferers currently registered at this InterferenceHelper.
Time GetOverlapTime (Ptr< LoraInterferenceHelper::Event > event1, Ptr< LoraInterferenceHelper::Event > event2)
Compute the time duration in which two given events are overlapping.
uint8_t IsDestroyedByInterference (Ptr< LoraInterferenceHelper::Event > event)
Determine whether the event was destroyed by interference or not.
void PrintEvents (std::ostream &stream)
Print the events that are saved in this helper in a human readable format.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Attributes
static CollisionMatrix collisionMatrix
static std::vector< std::vector< double > > collisionSnirAloha
static std::vector< std::vector< double > > collisionSnirGoursaud
Private Member Functions
void SetCollisionMatrix (enum CollisionMatrix collisionMatrix)
Private Attributes
std::vector< std::vector< double > > m_collisionSnir
std::list< Ptr< LoraInterferenceHelper::Event > > m_events
A list of the events this LoraInterferenceHelper is keeping track of.
Static Private Attributes
static Time oldEventThreshold = Seconds (2)
The matrix containing information about how packets survive interference.
Detailed Description
Helper for LoraPhy that manages interference calculations.
This class keeps a list of signals that are impinging on the antenna of the device, in order to compute which ones can be correctly received and which ones are lost due to interference.
Definition at line 43 of file lora-interference-helper.h.
Member Enumeration Documentation
CollisionMatrix
enum ns3::lorawan::LoraInterferenceHelper::CollisionMatrix
Enumerator
GOURSAUD
ALOHA
Definition at line 132 of file lora-interference-helper.h.
Constructor & Destructor Documentation
LoraInterferenceHelper()
ns3::lorawan::LoraInterferenceHelper::LoraInterferenceHelper ()
Definition at line 174 of file lora-interference-helper.cc.
References collisionMatrix, NS_LOG_FUNCTION, and SetCollisionMatrix().
~LoraInterferenceHelper()
ns3::lorawan::LoraInterferenceHelper::~LoraInterferenceHelper () virtual
Definition at line 181 of file lora-interference-helper.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Add()
Ptr< LoraInterferenceHelper::Event > ns3::lorawan::LoraInterferenceHelper::Add (Time duration, double rxPower, uint8_t spreadingFactor, Ptr< Packet > packet, double frequencyMHz)
Add an event to the InterferenceHelper.
Parameters
duration the duration of the packet.
rxPower the received power in dBm.
spreadingFactor the spreading factor used by the transmission.
packet The packet carried by this transmission.
frequencyMHz The frequency this event was sent at.
Returns
the newly created event
Definition at line 189 of file lora-interference-helper.cc.
References CleanOldEvents(), aloha::duration, m_events, and NS_LOG_FUNCTION.
Referenced by InterferenceTest::DoRun(), ns3::lorawan::SimpleEndDeviceLoraPhy::StartReceive(), and ns3::lorawan::SimpleGatewayLoraPhy::StartReceive().
CleanOldEvents()
void ns3::lorawan::LoraInterferenceHelper::CleanOldEvents (void)
Delete old events in this LoraInterferenceHelper.
Definition at line 213 of file lora-interference-helper.cc.
References m_events, ns3::Simulator::Now(), NS_LOG_FUNCTION, and oldEventThreshold.
Referenced by Add().
ClearAllEvents()
void ns3::lorawan::LoraInterferenceHelper::ClearAllEvents (void)
Delete all events in the LoraInterferenceHelper.
Definition at line 362 of file lora-interference-helper.cc.
References m_events, and NS_LOG_FUNCTION_NOARGS.
Referenced by InterferenceTest::DoRun().
GetInterferers()
std::list< Ptr< LoraInterferenceHelper::Event > > ns3::lorawan::LoraInterferenceHelper::GetInterferers ()
Get a list of the interferers currently registered at this InterferenceHelper.
Definition at line 229 of file lora-interference-helper.cc.
References m_events.
GetOverlapTime()
Time ns3::lorawan::LoraInterferenceHelper::GetOverlapTime (Ptr< LoraInterferenceHelper::Event > event1, Ptr< LoraInterferenceHelper::Event > event2)
Compute the time duration in which two given events are overlapping.
Parameters
event1 The first event
event2 The second event
Returns
The overlap time
Definition at line 370 of file lora-interference-helper.cc.
References NS_LOG_FUNCTION_NOARGS, and ns3::Seconds().
Referenced by InterferenceTest::DoRun(), and IsDestroyedByInterference().
GetTypeId()
TypeId ns3::lorawan::LoraInterferenceHelper::GetTypeId (void) static
Definition at line 166 of file lora-interference-helper.cc.
References ns3::TypeId::SetParent().
IsDestroyedByInterference()
uint8_t ns3::lorawan::LoraInterferenceHelper::IsDestroyedByInterference (Ptr< LoraInterferenceHelper::Event > event)
Determine whether the event was destroyed by interference or not.
This is the method where the SNIR tables come into play and the computations regarding power are performed.
Parameters
event The event for which to check the outcome.
Returns
The sf of the packets that caused the loss, or 0 if there was no loss.
Definition at line 249 of file lora-interference-helper.cc.
References aloha::duration, GetOverlapTime(), ns3::Time::GetSeconds(), m_collisionSnir, m_events, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by InterferenceTest::DoRun(), ns3::lorawan::SimpleEndDeviceLoraPhy::EndReceive(), and ns3::lorawan::SimpleGatewayLoraPhy::EndReceive().
PrintEvents()
void ns3::lorawan::LoraInterferenceHelper::PrintEvents (std::ostream & stream)
Print the events that are saved in this helper in a human readable format.
Definition at line 235 of file lora-interference-helper.cc.
References m_events, and NS_LOG_FUNCTION_NOARGS.
SetCollisionMatrix()
void ns3::lorawan::LoraInterferenceHelper::SetCollisionMatrix (enum CollisionMatrix collisionMatrix) private
Definition at line 149 of file lora-interference-helper.cc.
References ALOHA, collisionMatrix, collisionSnirAloha, collisionSnirGoursaud, GOURSAUD, m_collisionSnir, and NS_LOG_DEBUG.
Referenced by LoraInterferenceHelper().
Member Data Documentation
collisionMatrix
LoraInterferenceHelper::CollisionMatrix ns3::lorawan::LoraInterferenceHelper::collisionMatrix static
Initial value:
=
    LoraInterferenceHelper::GOURSAUD
Definition at line 199 of file lora-interference-helper.h.
Referenced by LoraInterferenceHelper(), and SetCollisionMatrix().
collisionSnirAloha
std::vector< std::vector< double > > ns3::lorawan::LoraInterferenceHelper::collisionSnirAloha static
Initial value:
= {
    {inf, minf, minf, minf, minf, minf},
    {minf, inf, minf, minf, minf, minf},
    {minf, minf, inf, minf, minf, minf},
    {minf, minf, minf, inf, minf, minf},
    {minf, minf, minf, minf, inf, minf},
    {minf, minf, minf, minf, minf, inf}
}
Definition at line 201 of file lora-interference-helper.h.
Referenced by SetCollisionMatrix().
collisionSnirGoursaud
std::vector< std::vector< double > > ns3::lorawan::LoraInterferenceHelper::collisionSnirGoursaud static
Initial value:
= {
    {6, -16, -18, -19, -19, -20},
    {-24, 6, -20, -22, -22, -22},
    {-27, -27, 6, -23, -25, -25},
    {-30, -30, -30, 6, -26, -28},
    {-33, -33, -33, -33, 6, -29},
    {-36, -36, -36, -36, -36, 6}
}
Definition at line 202 of file lora-interference-helper.h.
Referenced by SetCollisionMatrix().
m_collisionSnir
std::vector<std::vector<double> > ns3::lorawan::LoraInterferenceHelper::m_collisionSnir private
Definition at line 207 of file lora-interference-helper.h.
Referenced by IsDestroyedByInterference(), and SetCollisionMatrix().
m_events
std::list<Ptr<LoraInterferenceHelper::Event> > ns3::lorawan::LoraInterferenceHelper::m_events private
A list of the events this LoraInterferenceHelper is keeping track of.
Definition at line 212 of file lora-interference-helper.h.
Referenced by Add(), CleanOldEvents(), ClearAllEvents(), GetInterferers(), IsDestroyedByInterference(), and PrintEvents().
oldEventThreshold
Time ns3::lorawan::LoraInterferenceHelper::oldEventThreshold = Seconds (2) static private
The matrix containing information about how packets survive interference.
The threshold after which an event is considered old and removed from the list.
Definition at line 221 of file lora-interference-helper.h.
Referenced by CleanOldEvents().
The documentation for this class was generated from the following files:
src/lorawan/model/lora-interference-helper.h
src/lorawan/model/lora-interference-helper.cc