ns-3: ns3::TcpSocketMsgBase Class Reference
ns3::TcpSocketMsgBase Class Reference
Internet » internet module tests | Test suites
Class for inserting callbacks special points of the flow of TCP sockets.
#include "tcp-general-test.h"
Public Types
typedef Callback< void, Ptr< const Packet >, const TcpHeader &, Ptr< const TcpSocketBase > > AckManagementCb
Callback for the ACK management.
typedef Callback< void, Ptr< const TcpSocketState >, Ptr< const TcpSocketBase > > RetrCb
Callback for the packet retransmission management.
typedef Callback< void, Ptr< const TcpSocketBase >, const SequenceNumber32 &, uint32_t, bool > UpdateRttCallback
Callback for the RTT update management.
Public Types inherited from ns3::TcpSocketBase
typedef void(* TcpTxRxTracedCallback) (const Ptr< const Packet > packet, const TcpHeader &header, const Ptr< const TcpSocketBase > socket)
TracedCallback signature for tcp packet transmission or reception events.
Public Types inherited from ns3::TcpSocket
enum TcpStates_t {
CLOSED = 0, LISTEN, SYN_SENT, SYN_RCVD,
ESTABLISHED, CLOSE_WAIT, LAST_ACK, FIN_WAIT_1,
FIN_WAIT_2, CLOSING, TIME_WAIT, LAST_STATE
}
Names of the 11 TCP states.
Public Types inherited from ns3::Socket
enum Ipv6MulticastFilterMode { INCLUDE =1, EXCLUDE }
Enumeration of the possible filter of a socket.
enum SocketErrno {
ERROR_NOTERROR, ERROR_ISCONN, ERROR_NOTCONN, ERROR_MSGSIZE,
ERROR_AGAIN, ERROR_SHUTDOWN, ERROR_OPNOTSUPP, ERROR_AFNOSUPPORT,
ERROR_INVAL, ERROR_BADF, ERROR_NOROUTETOHOST, ERROR_NODEV,
ERROR_ADDRNOTAVAIL, ERROR_ADDRINUSE, SOCKET_ERRNO_LAST
}
Enumeration of the possible errors returned by a socket.
enum SocketPriority {
NS3_PRIO_BESTEFFORT = 0, NS3_PRIO_FILLER = 1, NS3_PRIO_BULK = 2, NS3_PRIO_INTERACTIVE_BULK = 4,
NS3_PRIO_INTERACTIVE = 6, NS3_PRIO_CONTROL = 7
}
Enumeration of the possible socket priorities.
enum SocketType { NS3_SOCK_STREAM, NS3_SOCK_SEQPACKET, NS3_SOCK_DGRAM, NS3_SOCK_RAW }
Enumeration of the possible socket types.
Public Member Functions
TcpSocketMsgBase ()
TcpSocketMsgBase (const TcpSocketMsgBase &other)
Constructor.
void SetAfterRetransmitCb (RetrCb cb)
Set the callback invoked after the processing of a retransmit timeout.
void SetBeforeRetransmitCb (RetrCb cb)
Set the callback invoked before the processing of a retransmit timeout.
void SetForkCb (Callback< void, Ptr< TcpSocketMsgBase > > cb)
Set the callback invoked after the forking.
void SetProcessedAckCb (AckManagementCb cb)
Set the callback invoked when an ACK is received and processed (at the end of the processing)
void SetRcvAckCb (AckManagementCb cb)
Set the callback invoked when an ACK is received (at the beginning of the processing)
void SetUpdateRttHistoryCb (UpdateRttCallback cb)
Set the callback invoked when we update rtt history.
Public Member Functions inherited from ns3::TcpSocketBase
TcpSocketBase (const TcpSocketBase &sock)
Clone a TCP socket, for use upon receiving a connection request in LISTEN state.
TcpSocketBase (void)
Create an unbound TCP socket.
virtual ~TcpSocketBase (void)
virtual int Bind (const Address &address)
Allocate a local endpoint for this socket.
virtual int Bind (void)
Allocate a local IPv4 endpoint for this socket.
virtual int Bind6 (void)
Allocate a local IPv6 endpoint for this socket.
virtual void BindToNetDevice (Ptr< NetDevice > netdevice)
Bind a socket to specific device.
bool CheckEcnCe (uint8_t tos) const
Checks for CE bits.
bool CheckEcnEct0 (uint8_t tos) const
Checks for ECT(0) bits.
bool CheckEcnEct1 (uint8_t tos) const
Checks for ECT(1) bits.
bool CheckNoEcn (uint8_t tos) const
Checks if TOS has no ECN bits.
uint8_t ClearEcnBits (uint8_t tos) const
Clears ECN bits from TOS.
virtual int Close (void)
Close a socket.
virtual int Connect (const Address &address)
Initiate a connection to a remote host.
Time GetClockGranularity (void) const
Get the Clock Granularity (used in RTO calcs).
virtual enum SocketErrno GetErrno (void) const
Get last error number.
virtual TypeId GetInstanceTypeId () const
Get the instance TypeId.
Time GetMinRto (void) const
Get the Minimum RTO.
virtual Ptr< Node > GetNode (void) const
Return the node this socket is associated with.
virtual int GetPeerName (Address &address) const
Get the peer address of a connected socket.
uint32_t GetRetxThresh (void) const
Get the retransmission threshold (dup ack threshold for a fast retransmit)
virtual uint32_t GetRxAvailable (void) const
Return number of bytes which can be returned from one or multiple calls to Recv.
Ptr< TcpRxBuffer > GetRxBuffer (void) const
Get a pointer to the Rx buffer.
virtual enum SocketType GetSocketType (void) const
virtual int GetSockName (Address &address) const
Get socket address.
virtual uint32_t GetTxAvailable (void) const
Returns the number of bytes which can be sent in a single call to Send.
Ptr< TcpTxBuffer > GetTxBuffer (void) const
Get a pointer to the Tx buffer.
virtual int Listen (void)
Listen for incoming connections.
uint8_t MarkEcnCe (uint8_t tos) const
Mark CE.
uint8_t MarkEcnCodePoint (const uint8_t tos, const TcpSocketState::EcnCodePoint_t codePoint) const
mark ECN code point
uint8_t MarkEcnEct0 (uint8_t tos) const
Mark ECT(0)
uint8_t MarkEcnEct1 (uint8_t tos) const
Mark ECT(1)
virtual Ptr< Packet > Recv (uint32_t maxSize, uint32_t flags)
Read data from the socket.
virtual Ptr< Packet > RecvFrom (uint32_t maxSize, uint32_t flags, Address &fromAddress)
Read a single packet from the socket and retrieve the sender address.
virtual int Send (Ptr< Packet > p, uint32_t flags)
Send data (or dummy data) to the remote host.
virtual int SendTo (Ptr< Packet > p, uint32_t flags, const Address &toAddress)
Send data to a specified peer.
void SetClockGranularity (Time clockGranularity)
Sets the Clock Granularity (used in RTO calcs).
void SetCongestionControlAlgorithm (Ptr< TcpCongestionOps > algo)
Install a congestion control algorithm on this socket.
void SetMinRto (Time minRto)
Sets the Minimum RTO.
virtual void SetNode (Ptr< Node > node)
Set the associated node.
void SetRecoveryAlgorithm (Ptr< TcpRecoveryOps > recovery)
Install a recovery algorithm on this socket.
void SetRetxThresh (uint32_t retxThresh)
Set the retransmission threshold (dup ack threshold for a fast retransmit)
virtual void SetRtt (Ptr< RttEstimator > rtt)
Set the associated RTT estimator.
virtual void SetTcp (Ptr< TcpL4Protocol > tcp)
Set the associated TCP L4 protocol.
void SetUseEcn (TcpSocketState::UseEcn_t useEcn)
Set use of ECN on the socket.
virtual int ShutdownRecv (void)
virtual int ShutdownSend (void)
void UpdateBytesInFlight (uint32_t oldValue, uint32_t newValue)
Callback function to hook to TcpSocketState bytes inflight.
void UpdateCongState (TcpSocketState::TcpCongState_t oldValue, TcpSocketState::TcpCongState_t newValue)
Callback function to hook to TcpSocketState congestion state.
void UpdateCwnd (uint32_t oldValue, uint32_t newValue)
Callback function to hook to TcpSocketState congestion window.
void UpdateCwndInfl (uint32_t oldValue, uint32_t newValue)
Callback function to hook to TcpSocketState inflated congestion window.
void UpdateEcnState (TcpSocketState::EcnState_t oldValue, TcpSocketState::EcnState_t newValue)
Callback function to hook to EcnState state.
void UpdateHighTxMark (SequenceNumber32 oldValue, SequenceNumber32 newValue)
Callback function to hook to TcpSocketState high tx mark.
void UpdateNextTxSequence (SequenceNumber32 oldValue, SequenceNumber32 newValue)
Callback function to hook to TcpSocketState next tx sequence.
void UpdateRtt (Time oldValue, Time newValue)
Callback function to hook to TcpSocketState rtt.
void UpdateSsThresh (uint32_t oldValue, uint32_t newValue)
Callback function to hook to TcpSocketState slow start threshold.
Public Member Functions inherited from ns3::TcpSocket
TcpSocket (void)
virtual ~TcpSocket (void)
Public Member Functions inherited from ns3::Socket
Socket (void)
virtual ~Socket (void)
Ptr< NetDevice > GetBoundNetDevice ()
Returns socket's bound NetDevice, if any.
uint8_t GetIpTos (void) const
Query the value of IP Type of Service of this socket.
virtual uint8_t GetIpTtl (void) const
Query the value of IP Time to Live field of this socket.
virtual uint8_t GetIpv6HopLimit (void) const
Query the value of IP Hop Limit field of this socket.
uint8_t GetIpv6Tclass (void) const
Query the value of IPv6 Traffic Class field of this socket.
uint8_t GetPriority (void) const
Query the priority value of this socket.
virtual void Ipv6JoinGroup (Ipv6Address address)
Joins a IPv6 multicast group without filters.
virtual void Ipv6JoinGroup (Ipv6Address address, Ipv6MulticastFilterMode filterMode, std::vector< Ipv6Address > sourceAddresses)
Joins a IPv6 multicast group.
virtual void Ipv6LeaveGroup (void)
Leaves IPv6 multicast group this socket is joined to.
bool IsIpRecvTos (void) const
Ask if the socket is currently passing information about IP Type of Service up the stack.
bool IsIpRecvTtl (void) const
Ask if the socket is currently passing information about IP_TTL up the stack.
bool IsIpv6RecvHopLimit (void) const
Ask if the socket is currently passing information about IPv6 Hop Limit up the stack.
bool IsIpv6RecvTclass (void) const
Ask if the socket is currently passing information about IPv6 Traffic Class up the stack.
bool IsRecvPktInfo () const
Get status indicating whether enable/disable packet information to socket.
int Recv (uint8_t *buf, uint32_t size, uint32_t flags)
Recv data (or dummy data) from the remote host.
Ptr< Packet > Recv (void)
Read a single packet from the socket.
Ptr< Packet > RecvFrom (Address &fromAddress)
Read a single packet from the socket and retrieve the sender address.
int RecvFrom (uint8_t *buf, uint32_t size, uint32_t flags, Address &fromAddress)
Read a single packet from the socket and retrieve the sender address.
int Send (const uint8_t *buf, uint32_t size, uint32_t flags)
Send data (or dummy data) to the remote host.
int Send (Ptr< Packet > p)
Send data (or dummy data) to the remote host.
int SendTo (const uint8_t *buf, uint32_t size, uint32_t flags, const Address &address)
Send data to a specified peer.
void SetAcceptCallback (Callback< bool, Ptr< Socket >, const Address & > connectionRequest, Callback< void, Ptr< Socket >, const Address & > newConnectionCreated)
Accept connection requests from remote hosts.
void SetCloseCallbacks (Callback< void, Ptr< Socket > > normalClose, Callback< void, Ptr< Socket > > errorClose)
Detect socket recv() events such as graceful shutdown or error.
void SetConnectCallback (Callback< void, Ptr< Socket > > connectionSucceeded, Callback< void, Ptr< Socket > > connectionFailed)
Specify callbacks to allow the caller to determine if the connection succeeds of fails.
void SetDataSentCallback (Callback< void, Ptr< Socket >, uint32_t > dataSent)
Notify application when a packet has been sent from transport protocol (non-standard socket call)
void SetIpRecvTos (bool ipv4RecvTos)
Tells a socket to pass information about IP Type of Service up the stack.
void SetIpRecvTtl (bool ipv4RecvTtl)
Tells a socket to pass information about IP_TTL up the stack.
void SetIpTos (uint8_t ipTos)
Manually set IP Type of Service field.
virtual void SetIpTtl (uint8_t ipTtl)
Manually set IP Time to Live field.
virtual void SetIpv6HopLimit (uint8_t ipHopLimit)
Manually set IPv6 Hop Limit.
void SetIpv6RecvHopLimit (bool ipv6RecvHopLimit)
Tells a socket to pass information about IPv6 Hop Limit up the stack.
void SetIpv6RecvTclass (bool ipv6RecvTclass)
Tells a socket to pass information about IPv6 Traffic Class up the stack.
void SetIpv6Tclass (int ipTclass)
Manually set IPv6 Traffic Class field.
void SetPriority (uint8_t priority)
Manually set the socket priority.
void SetRecvCallback (Callback< void, Ptr< Socket > >)
Notify application when new data is available to be read.
void SetRecvPktInfo (bool flag)
Enable/Disable receive packet information to socket.
void SetSendCallback (Callback< void, Ptr< Socket >, uint32_t > sendCb)
Notify application when space in transmit buffer is added.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpSocketBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpSocket
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Socket
static Ptr< Socket > CreateSocket (Ptr< Node > node, TypeId tid)
This method wraps the creation of sockets that is performed on a given node by a SocketFactory specified by TypeId.
static TypeId GetTypeId (void)
Get the type ID.
static uint8_t IpTos2Priority (uint8_t ipTos)
Return the priority corresponding to a given TOS value.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void CompleteFork (Ptr< Packet > p, const TcpHeader &tcpHeader, const Address &fromAddress, const Address &toAddress)
Complete a connection by forking the socket.
virtual Ptr< TcpSocketBase > Fork (void)
Call CopyObject<> to clone me.
virtual void ReceivedAck (Ptr< Packet > packet, const TcpHeader &tcpHeader)
Received an ACK packet.
virtual void ReTxTimeout (void)
An RTO event happened.
virtual void UpdateRttHistory (const SequenceNumber32 &seq, uint32_t sz, bool isRetransmission)
Update the RTT history, when we send TCP segments.
Protected Member Functions inherited from ns3::TcpSocketBase
void AddOptions (TcpHeader &tcpHeader)
Add options to TcpHeader.
void AddOptionSack (TcpHeader &header)
Add the SACK option to the header.
void AddOptionSackPermitted (TcpHeader &header)
Add the SACK PERMITTED option to the header.
void AddOptionTimestamp (TcpHeader &header)
Add the timestamp option to the header.
void AddOptionWScale (TcpHeader &header)
Add the window scale option to the header.
void AddSocketTags (const Ptr< Packet > &p) const
Add Tags for the Socket.
virtual uint16_t AdvertisedWindowSize (bool scale=true) const
The amount of Rx window announced to the peer.
virtual uint32_t AvailableWindow (void) const
Return unfilled portion of window.
virtual uint32_t BytesInFlight (void) const
Return total bytes in flight.
uint8_t CalculateWScale () const
Calculate window scale value based on receive buffer space.
void CancelAllTimers (void)
Cancel all timer when endpoint is deleted.
void CloseAndNotify (void)
Peacefully close the socket by notifying the upper layer and deallocate end point.
void ConnectionSucceeded (void)
Schedule-friendly wrapper for Socket::NotifyConnectionSucceeded()
void DeallocateEndPoint (void)
Deallocate m_endPoint and m_endPoint6.
virtual void DelAckTimeout (void)
Action upon delay ACK timeout, i.e.
void Destroy (void)
Kill this socket by zeroing its attributes (IPv4)
void Destroy6 (void)
Kill this socket by zeroing its attributes (IPv6)
int DoClose (void)
Close a socket by sending RST, FIN, or FIN+ACK, depend on the current state.
int DoConnect (void)
Perform the real connection tasks: Send SYN if allowed, RST if invalid.
virtual void DoForwardUp (Ptr< Packet > packet, const Address &fromAddress, const Address &toAddress)
Called by TcpSocketBase::ForwardUp{,6}().
void DoPeerClose (void)
FIN is in sequence, notify app and respond with a FIN.
void DoRetransmit (void)
Retransmit the first segment marked as lost, without considering available window nor pacing.
void DupAck (uint32_t currentDelivered)
Dupack management.
void EnterRecovery (uint32_t currentDelivered)
Enter the CA_RECOVERY, and retransmit the head.
virtual void EstimateRtt (const TcpHeader &tcpHeader)
Take into account the packet for RTT estimation.
void ForwardIcmp (Ipv4Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo)
Called by the L3 protocol when it received an ICMP packet to pass on to TCP.
void ForwardIcmp6 (Ipv6Address icmpSource, uint8_t icmpTtl, uint8_t icmpType, uint8_t icmpCode, uint32_t icmpInfo)
Called by the L3 protocol when it received an ICMPv6 packet to pass on to TCP.
void ForwardUp (Ptr< Packet > packet, Ipv4Header header, uint16_t port, Ptr< Ipv4Interface > incomingInterface)
Called by the L3 protocol when it received a packet to pass on to TCP.
void ForwardUp6 (Ptr< Packet > packet, Ipv6Header header, uint16_t port, Ptr< Ipv6Interface > incomingInterface)
Called by the L3 protocol when it received a packet to pass on to TCP.
virtual bool GetAllowBroadcast (void) const
Query whether broadcast datagram transmissions are allowed.
virtual Time GetConnTimeout (void) const
Get the connection timeout.
virtual uint32_t GetDataRetries (void) const
Get the number of data transmission retries before giving up.
virtual uint32_t GetDelAckMaxCount (void) const
Get the number of packet to fire an ACK before delay timeout.
virtual Time GetDelAckTimeout (void) const
Get the time to delay an ACK.
virtual uint32_t GetInitialCwnd (void) const
Get the initial Congestion Window.
virtual uint32_t GetInitialSSThresh (void) const
Get the initial Slow Start Threshold.
virtual Time GetPersistTimeout (void) const
Get the timeout for persistent connection.
virtual uint32_t GetRcvBufSize (void) const
Get the receive buffer size.
virtual uint32_t GetSegSize (void) const
Get the segment size.
virtual uint32_t GetSndBufSize (void) const
Get the send buffer size.
virtual uint32_t GetSynRetries (void) const
Get the number of connection retries before giving up.
virtual bool GetTcpNoDelay (void) const
Check if Nagle's algorithm is enabled or not.
bool IsTcpOptionEnabled (uint8_t kind) const
Return true if the specified option is enabled.
bool IsValidTcpSegment (const SequenceNumber32 seq, const uint32_t tcpHeaderSize, const uint32_t tcpPayloadSize)
Checks whether the given TCP segment is valid or not.
virtual void LastAckTimeout (void)
Timeout at LAST_ACK, close the connection.
virtual void NewAck (SequenceNumber32 const &seq, bool resetRTO)
Update buffers w.r.t.
void NotifyPacingPerformed (void)
Notify Pacing.
bool OutOfRange (SequenceNumber32 head, SequenceNumber32 tail) const
Check if a sequence number range is within the rx window.
void PeerClose (Ptr< Packet > p, const TcpHeader &tcpHeader)
Received a FIN from peer, notify rx buffer.
virtual void PersistTimeout (void)
Send 1 byte probe to get an updated window size.
virtual void ProcessAck (const SequenceNumber32 &ackNumber, bool scoreboardUpdated, uint32_t currentDelivered, const SequenceNumber32 &oldHeadSequence)
Process a received ack.
void ProcessClosing (Ptr< Packet > packet, const TcpHeader &tcpHeader)
Received a packet upon CLOSING.
void ProcessEstablished (Ptr< Packet > packet, const TcpHeader &tcpHeader)
Received a packet upon ESTABLISHED state.
void ProcessLastAck (Ptr< Packet > packet, const TcpHeader &tcpHeader)
Received a packet upon LAST_ACK.
void ProcessListen (Ptr< Packet > packet, const TcpHeader &tcpHeader, const Address &fromAddress, const Address &toAddress)
Received a packet upon LISTEN state.
uint32_t ProcessOptionSack (const Ptr< const TcpOption > option)
Read the SACK option.
void ProcessOptionSackPermitted (const Ptr< const TcpOption > option)
Read the SACK PERMITTED option.
void ProcessOptionTimestamp (const Ptr< const TcpOption > option, const SequenceNumber32 &seq)
Process the timestamp option from other side.
void ProcessOptionWScale (const Ptr< const TcpOption > option)
Read and parse the Window scale option.
void ProcessSynRcvd (Ptr< Packet > packet, const TcpHeader &tcpHeader, const Address &fromAddress, const Address &toAddress)
Received a packet upon SYN_RCVD.
void ProcessSynSent (Ptr< Packet > packet, const TcpHeader &tcpHeader)
Received a packet upon SYN_SENT.
void ProcessWait (Ptr< Packet > packet, const TcpHeader &tcpHeader)
Received a packet upon CLOSE_WAIT, FIN_WAIT_1, FIN_WAIT_2.
void ReadOptions (const TcpHeader &tcpHeader, uint32_t *bytesSacked)
Read TCP options before Ack processing.
virtual void ReceivedData (Ptr< Packet > packet, const TcpHeader &tcpHeader)
Recv of a data, put into buffer, call L7 to get it if necessary.
virtual uint32_t SendDataPacket (SequenceNumber32 seq, uint32_t maxSize, bool withAck)
Extract at most maxSize bytes from the TxBuffer at sequence seq, add the TCP header, and send to TcpL4Protocol.
virtual void SendEmptyPacket (uint8_t flags)
Send a empty packet that carries a flag, e.g., ACK.
uint32_t SendPendingData (bool withAck=false)
Send as much pending data as possible according to the Tx window.
void SendRST (void)
Send reset and tear down this socket.
virtual bool SetAllowBroadcast (bool allowBroadcast)
Configure whether broadcast datagram transmissions are allowed.
virtual void SetConnTimeout (Time timeout)
Set the connection timeout.
virtual void SetDataRetries (uint32_t retries)
Set the number of data transmission retries before giving up.
virtual void SetDelAckMaxCount (uint32_t count)
Set the number of packet to fire an ACK before delay timeout.
virtual void SetDelAckTimeout (Time timeout)
Set the time to delay an ACK.
virtual void SetInitialCwnd (uint32_t cwnd)
Set the initial Congestion Window.
virtual void SetInitialSSThresh (uint32_t threshold)
Set the initial Slow Start Threshold.
virtual void SetPersistTimeout (Time timeout)
Set the timeout for persistent connection.
virtual void SetRcvBufSize (uint32_t size)
Set the receive buffer size.
virtual void SetSegSize (uint32_t size)
Set the segment size.
virtual void SetSndBufSize (uint32_t size)
Set the send buffer size.
virtual void SetSynRetries (uint32_t count)
Set the number of connection retries before giving up.
virtual void SetTcpNoDelay (bool noDelay)
Enable/Disable Nagle's algorithm.
int SetupCallback (void)
Common part of the two Bind(), i.e.
int SetupEndpoint (void)
Configure the endpoint to a local address.
int SetupEndpoint6 (void)
Configure the endpoint v6 to a local address.
void TimeWait (void)
Move from CLOSING or FIN_WAIT_2 to TIME_WAIT state.
virtual uint32_t UnAckDataCount (void) const
Return count of number of unacked bytes.
void UpdateWindowSize (const TcpHeader &header)
Update the receiver window (RWND) based on the value of the window field in the header.
virtual uint32_t Window (void) const
Return the max possible number of unacked bytes.
Protected Member Functions inherited from ns3::Socket
virtual void DoDispose (void)
Destructor implementation.
bool IsManualIpTtl (void) const
Checks if the socket has a specific IPv4 TTL set.
bool IsManualIpv6HopLimit (void) const
Checks if the socket has a specific IPv6 Hop Limit set.
bool IsManualIpv6Tclass (void) const
Checks if the socket has a specific IPv6 Tclass set.
void NotifyConnectionFailed (void)
Notify through the callback (if set) that the connection has not been established due to an error.
bool NotifyConnectionRequest (const Address &from)
Notify through the callback (if set) that an incoming connection is being requested by a remote host.
void NotifyConnectionSucceeded (void)
Notify through the callback (if set) that the connection has been established.
void NotifyDataRecv (void)
Notify through the callback (if set) that some data have been received.
void NotifyDataSent (uint32_t size)
Notify through the callback (if set) that some data have been sent.
void NotifyErrorClose (void)
Notify through the callback (if set) that the connection has been closed due to an error.
void NotifyNewConnectionCreated (Ptr< Socket > socket, const Address &from)
Notify through the callback (if set) that a new connection has been created.
void NotifyNormalClose (void)
Notify through the callback (if set) that the connection has been closed.
void NotifySend (uint32_t spaceAvailable)
Notify through the callback (if set) that some data have been sent.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Attributes
RetrCb m_afterRetrCallback
After retransmission callback.
RetrCb m_beforeRetrCallback
Before retransmission callback.
Callback< void, Ptr< TcpSocketMsgBase > > m_forkCb
Fork callback.
AckManagementCb m_processedAckCb
Processed ACK callback.
AckManagementCb m_rcvAckCb
Receive ACK callback.
UpdateRttCallback m_updateRttCb
Update RTT callback.
Additional Inherited Members
Public Attributes inherited from ns3::TcpSocketBase
TracedCallback< uint32_t, uint32_t > m_bytesInFlightTrace
Callback pointer for bytesInFlight trace chaining.
TracedCallback< TcpSocketState::TcpCongState_t, TcpSocketState::TcpCongState_t > m_congStateTrace
Callback pointer for congestion state trace chaining.
TracedCallback< uint32_t, uint32_t > m_cWndInflTrace
Callback pointer for cWndInfl trace chaining.
TracedCallback< uint32_t, uint32_t > m_cWndTrace
Callback pointer for cWnd trace chaining.
TracedCallback< TcpSocketState::EcnState_t, TcpSocketState::EcnState_t > m_ecnStateTrace
Callback pointer for ECN state trace chaining.
TracedCallback< SequenceNumber32, SequenceNumber32 > m_highTxMarkTrace
Callback pointer for high tx mark chaining.
TracedCallback< Time, Time > m_lastRttTrace
Callback pointer for RTT trace chaining.
TracedCallback< SequenceNumber32, SequenceNumber32 > m_nextTxSequenceTrace
Callback pointer for next tx sequence chaining.
TracedCallback< uint32_t, uint32_t > m_ssThTrace
Callback pointer for ssTh trace chaining.
Static Public Attributes inherited from ns3::TcpSocket
static const char *const TcpStateName [TcpSocket::LAST_STATE]
Literal names of TCP states for use in log messages.
Static Protected Member Functions inherited from ns3::TcpSocketBase
static uint32_t SafeSubtraction (uint32_t a, uint32_t b)
Performs a safe subtraction between a and b (a-b)
Protected Attributes inherited from ns3::TcpSocketBase
TracedValue< uint32_t > m_advWnd {0}
Advertised Window size.
uint32_t m_bytesAckedNotProcessed {0}
Bytes acked, but not processed.
Time m_clockGranularity {Seconds (0.001)}
Clock Granularity used in RTO calcs.
bool m_closeNotified {false}
Told app to close socket.
bool m_closeOnEmpty {false}
Close socket upon tx buffer emptied.
Time m_cnTimeout {Seconds (0.0)}
Timeout for connection retry.
Ptr< TcpCongestionOps > m_congestionControl
Congestion control.
bool m_connected {false}
Connection established.
uint32_t m_dataRetrCount {0}
Count of remaining data retransmission attempts.
uint32_t m_dataRetries {0}
Number of data retransmission attempts.
uint32_t m_delAckCount {0}
Delayed ACK counter.
EventId m_delAckEvent {}
Delayed ACK timeout event.
uint32_t m_delAckMaxCount {0}
Number of packet to fire an ACK before delay timeout.
Time m_delAckTimeout {Seconds (0.0)}
Time to delay an ACK.
uint32_t m_dupAckCount {0}
Dupack counter.
TracedValue< SequenceNumber32 > m_ecnCESeq {0}
Sequence number of the last received Congestion Experienced.
TracedValue< SequenceNumber32 > m_ecnCWRSeq {0}
Sequence number of the last sent CWR.
TracedValue< SequenceNumber32 > m_ecnEchoSeq {0}
Sequence number of the last received ECN Echo.
Ipv4EndPoint * m_endPoint {nullptr}
the IPv4 endpoint
Ipv6EndPoint * m_endPoint6 {nullptr}
the IPv6 endpoint
TracedValue< SequenceNumber32 > m_highRxAckMark {0}
Highest ack received.
TracedValue< SequenceNumber32 > m_highRxMark {0}
Highest seqno received.
SequenceNumber32 m_highTxAck {0}
Highest ack sent.
std::deque< RttHistory > m_history
List of sent packet.
Callback< void, Ipv4Address, uint8_t, uint8_t, uint8_t, uint32_t > m_icmpCallback
ICMP callback.
Callback< void, Ipv6Address, uint8_t, uint8_t, uint8_t, uint32_t > m_icmpCallback6
ICMPv6 callback.
bool m_isFirstPartialAck {true}
First partial ACK during RECOVERY.
EventId m_lastAckEvent {}
Last ACK timeout event.
bool m_limitedTx {true}
perform limited transmit
uint16_t m_maxWinSize {0}
Maximum window size to advertise.
Time m_minRto {Time::Max ()}
minimum value of the Retransmit timeout
double m_msl {0.0}
Max segment lifetime.
Ptr< Node > m_node
the associated node
bool m_noDelay {false}
Set to true to disable Nagle's algorithm.
Timer m_pacingTimer {Timer::REMOVE_ON_DESTROY}
Pacing Event.
EventId m_persistEvent {}
Persist event: Send 1 byte to probe for a non-zero Rx window.
Time m_persistTimeout {Seconds (0.0)}
Time between sending 1-byte probes.
Ptr< TcpRateOps > m_rateOps
Rate operations.
uint8_t m_rcvWindShift {0}
Window shift to apply to outgoing segments.
SequenceNumber32 m_recover {0}
Previous highest Tx seqnum for fast recovery (set it to initial seq number)
Ptr< TcpRecoveryOps > m_recoveryOps
Recovery Algorithm.
EventId m_retxEvent {}
Retransmission event.
uint32_t m_retxThresh {3}
Fast Retransmit threshold.
TracedValue< Time > m_rto {Seconds (0.0)}
Retransmit timeout.
Ptr< RttEstimator > m_rtt
Round trip time estimator.
TracedValue< uint32_t > m_rWnd {0}
Receiver window (RCV.WND in RFC793)
TracedCallback< Ptr< const Packet >, const TcpHeader &, Ptr< const TcpSocketBase > > m_rxTrace
Trace of received packets.
bool m_sackEnabled {true}
RFC SACK option enabled.
EventId m_sendPendingDataEvent {}
micro-delay event to send pending data
bool m_shutdownRecv {false}
Receive no longer allowed.
bool m_shutdownSend {false}
Send no longer allowed.
uint8_t m_sndWindShift {0}
Window shift to apply to incoming segments.
TracedValue< TcpStates_t > m_state {CLOSED}
TCP state.
uint32_t m_synCount {0}
Count of remaining connection retries.
uint32_t m_synRetries {0}
Number of connection attempts.
Ptr< TcpSocketState > m_tcb
Congestion control information.
Ptr< TcpL4Protocol > m_tcp
the associated TCP L4 protocol
bool m_timestampEnabled {true}
Timestamp option enabled.
uint32_t m_timestampToEcho {0}
Timestamp to echo.
EventId m_timewaitEvent {}
TIME_WAIT expiration event: Move this socket to CLOSED state.
Ptr< TcpTxBuffer > m_txBuffer
Tx buffer.
TracedCallback< Ptr< const Packet >, const TcpHeader &, Ptr< const TcpSocketBase > > m_txTrace
Trace of transmitted packets.
bool m_winScalingEnabled {true}
Window Scale option enabled (RFC 7323)
Protected Attributes inherited from ns3::Socket
Ptr< NetDevice > m_boundnetdevice
the device this socket is bound to (might be null).
Ipv6Address m_ipv6MulticastGroupAddress
IPv6 multicast group address.
bool m_recvPktInfo
if the socket should add packet info tags to the packet forwarded to L4.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Class for inserting callbacks special points of the flow of TCP sockets.
This subclass is born to extend TcpSocketBase, inserting callbacks in certain points of the flow, to be used in testing to check certain values or flow directions.
There isn't the necessity to fill TcpSocketBase of TracedCallbacks; the rationale is to maintain the base class as clean as possible.
To be fair with testing, this class should NOT modify the behavior of TcpSocketBase.
See also
SetRcvAckCb
SetProcessedAckCb
SetAfterRetransmitCb
SetBeforeRetransmitCb
Definition at line 52 of file tcp-general-test.h.
Member Typedef Documentation
AckManagementCb
typedef Callback<void, Ptr<const Packet>, const TcpHeader&, Ptr<const TcpSocketBase> > ns3::TcpSocketMsgBase::AckManagementCb
Callback for the ACK management.
Definition at line 81 of file tcp-general-test.h.
RetrCb
typedef Callback<void, Ptr<const TcpSocketState>, Ptr<const TcpSocketBase> > ns3::TcpSocketMsgBase::RetrCb
Callback for the packet retransmission management.
Definition at line 84 of file tcp-general-test.h.
UpdateRttCallback
typedef Callback<void, Ptr<const TcpSocketBase>, const SequenceNumber32&, uint32_t, bool> ns3::TcpSocketMsgBase::UpdateRttCallback
Callback for the RTT update management.
Definition at line 87 of file tcp-general-test.h.
Constructor & Destructor Documentation
TcpSocketMsgBase() [1/2]
ns3::TcpSocketMsgBase::TcpSocketMsgBase () inline
Definition at line 61 of file tcp-general-test.h.
TcpSocketMsgBase() [2/2]
ns3::TcpSocketMsgBase::TcpSocketMsgBase (const TcpSocketMsgBase & other) inline
Constructor.
Parameters
other The object to copy from.
Definition at line 69 of file tcp-general-test.h.
References m_afterRetrCallback, m_beforeRetrCallback, m_forkCb, m_processedAckCb, m_rcvAckCb, and m_updateRttCb.
Member Function Documentation
CompleteFork()
void TcpSocketMsgBase::CompleteFork (Ptr< Packet > p, const TcpHeader & tcpHeader, const Address & fromAddress, const Address & toAddress) protected virtual
Complete a connection by forking the socket.
This function is called only if a SYN received in LISTEN state. After TcpSocketBase cloned, allocate a new end point to handle the incoming connection and send a SYN+ACK to complete the handshake.
Parameters
p the packet triggering the fork
tcpHeader the TCP header of the triggering packet
fromAddress the address of the remote host
toAddress the address the connection is directed to
Reimplemented from ns3::TcpSocketBase.
Definition at line 1080 of file tcp-general-test.cc.
References ns3::TcpSocketBase::CompleteFork(), and m_forkCb.
Fork()
Ptr< TcpSocketBase > TcpSocketMsgBase::Fork (void) protected virtual
Call CopyObject<> to clone me.
Returns
a copy of the socket
Reimplemented from ns3::TcpSocketBase.
Reimplemented in ns3::TcpSocketSmallAcks, ns3::TcpSocketCongestedRouter, TcpDctcpCongestedRouter, TcpSocketHalfAck, and TcpSocketAdvertisedWindowProxy.
Definition at line 1002 of file tcp-general-test.cc.
GetTypeId()
TypeId TcpSocketMsgBase::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 991 of file tcp-general-test.cc.
References ns3::TypeId::SetParent().
Referenced by ns3::TcpGeneralTest::CreateReceiverSocket(), and ns3::TcpGeneralTest::CreateSenderSocket().
ReceivedAck()
void TcpSocketMsgBase::ReceivedAck (Ptr< Packet > packet, const TcpHeader & tcpHeader) protected virtual
Received an ACK packet.
Parameters
packet the packet
tcpHeader the packet's TCP header
Reimplemented from ns3::TcpSocketBase.
Definition at line 1036 of file tcp-general-test.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_processedAckCb, m_rcvAckCb, NS_ASSERT, and ns3::TcpSocketBase::ReceivedAck().
ReTxTimeout()
void TcpSocketMsgBase::ReTxTimeout (void) protected virtual
An RTO event happened.
Reimplemented from ns3::TcpSocketBase.
Reimplemented in ns3::TcpSocketCongestedRouter, and TcpDctcpCongestedRouter.
Definition at line 1047 of file tcp-general-test.cc.
References m_afterRetrCallback, m_beforeRetrCallback, ns3::TcpSocketBase::m_tcb, and ns3::TcpSocketBase::ReTxTimeout().
SetAfterRetransmitCb()
void TcpSocketMsgBase::SetAfterRetransmitCb (RetrCb cb)
Set the callback invoked after the processing of a retransmit timeout.
Parameters
cb callback
Definition at line 1022 of file tcp-general-test.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_afterRetrCallback, and NS_ASSERT.
SetBeforeRetransmitCb()
void TcpSocketMsgBase::SetBeforeRetransmitCb (RetrCb cb)
Set the callback invoked before the processing of a retransmit timeout.
Parameters
cb callback
Definition at line 1029 of file tcp-general-test.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_beforeRetrCallback, and NS_ASSERT.
SetForkCb()
void TcpSocketMsgBase::SetForkCb (Callback< void, Ptr< TcpSocketMsgBase > > cb)
Set the callback invoked after the forking.
Parameters
cb callback
Definition at line 1055 of file tcp-general-test.cc.
References m_forkCb, and NS_ASSERT.
SetProcessedAckCb()
void TcpSocketMsgBase::SetProcessedAckCb (AckManagementCb cb)
Set the callback invoked when an ACK is received and processed (at the end of the processing)
Parameters
cb callback
Definition at line 1015 of file tcp-general-test.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_processedAckCb, and NS_ASSERT.
SetRcvAckCb()
void TcpSocketMsgBase::SetRcvAckCb (AckManagementCb cb)
Set the callback invoked when an ACK is received (at the beginning of the processing)
Parameters
cb callback
Definition at line 1008 of file tcp-general-test.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_rcvAckCb, and NS_ASSERT.
SetUpdateRttHistoryCb()
void TcpSocketMsgBase::SetUpdateRttHistoryCb (UpdateRttCallback cb)
Set the callback invoked when we update rtt history.
Parameters
cb callback
Definition at line 1062 of file tcp-general-test.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_updateRttCb, and NS_ASSERT.
UpdateRttHistory()
void TcpSocketMsgBase::UpdateRttHistory (const SequenceNumber32 & seq, uint32_t sz, bool isRetransmission) protected virtual
Update the RTT history, when we send TCP segments.
Parameters
seq The sequence number of the TCP segment
sz The segment's size
isRetransmission Whether or not the segment is a retransmission
Reimplemented from ns3::TcpSocketBase.
Definition at line 1069 of file tcp-general-test.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_updateRttCb, and ns3::TcpSocketBase::UpdateRttHistory().
Referenced by TcpDctcpCongestedRouter::SendDataPacket(), and ns3::TcpSocketCongestedRouter::SendDataPacket().
Member Data Documentation
m_afterRetrCallback
RetrCb ns3::TcpSocketMsgBase::m_afterRetrCallback private
After retransmission callback.
Definition at line 145 of file tcp-general-test.h.
Referenced by TcpSocketMsgBase(), ReTxTimeout(), and SetAfterRetransmitCb().
m_beforeRetrCallback
RetrCb ns3::TcpSocketMsgBase::m_beforeRetrCallback private
Before retransmission callback.
Definition at line 144 of file tcp-general-test.h.
Referenced by TcpSocketMsgBase(), ReTxTimeout(), and SetBeforeRetransmitCb().
m_forkCb
Callback<void, Ptr<TcpSocketMsgBase> > ns3::TcpSocketMsgBase::m_forkCb private
Fork callback.
Definition at line 146 of file tcp-general-test.h.
Referenced by TcpSocketMsgBase(), CompleteFork(), and SetForkCb().
m_processedAckCb
AckManagementCb ns3::TcpSocketMsgBase::m_processedAckCb private
Processed ACK callback.
Definition at line 143 of file tcp-general-test.h.
Referenced by TcpSocketMsgBase(), ReceivedAck(), and SetProcessedAckCb().
m_rcvAckCb
AckManagementCb ns3::TcpSocketMsgBase::m_rcvAckCb private
Receive ACK callback.
Definition at line 142 of file tcp-general-test.h.
Referenced by TcpSocketMsgBase(), ReceivedAck(), and SetRcvAckCb().
m_updateRttCb
UpdateRttCallback ns3::TcpSocketMsgBase::m_updateRttCb private
Update RTT callback.
Definition at line 147 of file tcp-general-test.h.
Referenced by TcpSocketMsgBase(), SetUpdateRttHistoryCb(), and UpdateRttHistory().
The documentation for this class was generated from the following files:
src/internet/test/tcp-general-test.h
src/internet/test/tcp-general-test.cc