ns-3: ns3::GatewayStatus Class Reference
ns3::GatewayStatus Class Reference
#include "gateway-status.h"
Public Member Functions
GatewayStatus ()
GatewayStatus (Address address, Ptr< NetDevice > netDevice, Ptr< GatewayLoraMac > gwMac)
virtual ~GatewayStatus ()
Address GetAddress ()
Get this gateway's P2P link address.
Ptr< GatewayLoraMac > GetGatewayMac (void)
Get a pointer to this gateway's MAC instance.
Ptr< NetDevice > GetNetDevice ()
Get the NetDevice through which it's possible to contact this gateway.
Time GetNextTransmissionTime (void)
bool IsAvailableForTransmission (double frequency)
Query whether or not this gateway is available for immediate transmission on this frequency.
void SetAddress (Address address)
Set this gateway's P2P link address.
void SetGatewayMac (Ptr< GatewayLoraMac > gwMac)
Set a pointer to this gateway's MAC instance.
void SetNetDevice (Ptr< NetDevice > netDevice)
Set the NetDevice through which it's possible to contact this gateway.
void SetNextTransmissionTime (Time nextTransmissionTime)
Private Attributes
Address m_address
The Address of the P2PNetDevice of this gateway.
Ptr< GatewayLoraMac > m_gatewayMac
The Mac layer of the gateway.
bool m_isTransmitting
Whether this gateway is already booked for transmission or not.
Ptr< NetDevice > m_netDevice
The NetDevice through which to reach this gateway.
Time m_nextTransmissionTime
This gateway's next transmission time.
Detailed Description
Definition at line 31 of file gateway-status.h.
Constructor & Destructor Documentation
GatewayStatus() [1/2]
ns3::GatewayStatus::GatewayStatus ()
Definition at line 28 of file gateway-status.cc.
References NS_LOG_FUNCTION.
~GatewayStatus()
ns3::GatewayStatus::~GatewayStatus () virtual
Definition at line 33 of file gateway-status.cc.
References NS_LOG_FUNCTION.
GatewayStatus() [2/2]
ns3::GatewayStatus::GatewayStatus (Address address, Ptr< NetDevice > netDevice, Ptr< GatewayLoraMac > gwMac)
Definition at line 38 of file gateway-status.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
GetAddress()
Address ns3::GatewayStatus::GetAddress ()
Get this gateway's P2P link address.
Definition at line 49 of file gateway-status.cc.
References m_address, and NS_LOG_FUNCTION.
GetGatewayMac()
Ptr< GatewayLoraMac > ns3::GatewayStatus::GetGatewayMac (void)
Get a pointer to this gateway's MAC instance.
Definition at line 77 of file gateway-status.cc.
References m_gatewayMac.
GetNetDevice()
Ptr< NetDevice > ns3::GatewayStatus::GetNetDevice ()
Get the NetDevice through which it's possible to contact this gateway.
Definition at line 65 of file gateway-status.cc.
References m_netDevice.
GetNextTransmissionTime()
Time ns3::GatewayStatus::GetNextTransmissionTime (void)
IsAvailableForTransmission()
bool ns3::GatewayStatus::IsAvailableForTransmission (double frequency)
Query whether or not this gateway is available for immediate transmission on this frequency.
Parameters
frequency The frequency at which the gateway's availability should be queried.
Returns
True if the gateway's available, false otherwise.
Definition at line 83 of file gateway-status.cc.
References ns3::Time::GetSeconds(), m_gatewayMac, m_nextTransmissionTime, ns3::MilliSeconds(), ns3::Simulator::Now(), NS_LOG_INFO, and ns3::Seconds().
SetAddress()
void ns3::GatewayStatus::SetAddress (Address address)
Set this gateway's P2P link address.
Definition at line 57 of file gateway-status.cc.
References first::address, m_address, and NS_LOG_FUNCTION.
SetGatewayMac()
void ns3::GatewayStatus::SetGatewayMac (Ptr< GatewayLoraMac > gwMac)
Set a pointer to this gateway's MAC instance.
SetNetDevice()
void ns3::GatewayStatus::SetNetDevice (Ptr< NetDevice > netDevice)
Set the NetDevice through which it's possible to contact this gateway.
Definition at line 71 of file gateway-status.cc.
References m_netDevice.
SetNextTransmissionTime()
void ns3::GatewayStatus::SetNextTransmissionTime (Time nextTransmissionTime)
Definition at line 116 of file gateway-status.cc.
References m_nextTransmissionTime.
Member Data Documentation
m_address
Address ns3::GatewayStatus::m_address private
The Address of the P2PNetDevice of this gateway.
Definition at line 84 of file gateway-status.h.
Referenced by GetAddress(), and SetAddress().
m_gatewayMac
Ptr<GatewayLoraMac> ns3::GatewayStatus::m_gatewayMac private
The Mac layer of the gateway.
Definition at line 88 of file gateway-status.h.
Referenced by GetGatewayMac(), and IsAvailableForTransmission().
m_isTransmitting
bool ns3::GatewayStatus::m_isTransmitting private
Whether this gateway is already booked for transmission or not.
Definition at line 90 of file gateway-status.h.
m_netDevice
Ptr<NetDevice> ns3::GatewayStatus::m_netDevice private
The NetDevice through which to reach this gateway.
Definition at line 86 of file gateway-status.h.
Referenced by GetNetDevice(), and SetNetDevice().
m_nextTransmissionTime
Time ns3::GatewayStatus::m_nextTransmissionTime private
This gateway's next transmission time.
Definition at line 93 of file gateway-status.h.
Referenced by IsAvailableForTransmission(), and SetNextTransmissionTime().
The documentation for this class was generated from the following files:
src/lorawan/model/gateway-status.h
src/lorawan/model/gateway-status.cc