ns-3: ns3::SixLowPanMesh Class Reference
ns3::SixLowPanMesh Class Reference
6LoWPAN
6LoWPAN Mesh header - see RFC 4944.
#include "sixlowpan-header.h"
Public Member Functions
SixLowPanMesh (void)
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
Address GetFinalDst (void) const
Get the "Final Destination" address.
uint8_t GetHopsLeft (void) const
Get the "Hops Left" field.
virtual TypeId GetInstanceTypeId (void) const
Return the instance type identifier.
Address GetOriginator (void) const
Get the "Originator" address.
virtual uint32_t GetSerializedSize (void) const
Get the serialized size of the packet.
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetFinalDst (Address finalDst)
Set the "Final Destination" address.
void SetHopsLeft (uint8_t hopsLeft)
Set the "Hops Left" field.
void SetOriginator (Address originator)
Set the "Originator" address.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Address m_dst
Destination (final) address.
bool m_f
True if Destination address is 16 bit.
uint8_t m_hopsLeft
Hops left.
Address m_src
Originator (source) address.
bool m_v
True if Originator address is 16 bit.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
6LoWPAN Mesh header - see RFC 4944.
Definition at line 1310 of file sixlowpan-header.h.
Constructor & Destructor Documentation
SixLowPanMesh()
ns3::SixLowPanMesh::SixLowPanMesh (void)
Definition at line 1889 of file sixlowpan-header.cc.
References m_dst, m_f, m_hopsLeft, m_src, and m_v.
Member Function Documentation
Deserialize()
uint32_t ns3::SixLowPanMesh::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
[in] start Buffer iterator.
Returns
Size of the packet.
Implements ns3::Header.
Definition at line 2014 of file sixlowpan-header.cc.
References ns3::Address::CopyFrom(), GetSerializedSize(), m_dst, m_f, m_hopsLeft, m_src, m_v, ns3::Buffer::Iterator::Read(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetFinalDst()
Address ns3::SixLowPanMesh::GetFinalDst (void) const
Get the "Final Destination" address.
Returns
The Final Destination address (Mac64Address or Mac16Address).
Definition at line 2102 of file sixlowpan-header.cc.
References m_dst.
Referenced by ns3::SixLowPanNetDevice::ReceiveFromDevice().
GetHopsLeft()
uint8_t ns3::SixLowPanMesh::GetHopsLeft (void) const
Get the "Hops Left" field.
Returns
The number of hops left.
Definition at line 2112 of file sixlowpan-header.cc.
References m_hopsLeft.
Referenced by ns3::SixLowPanNetDevice::ReceiveFromDevice().
GetInstanceTypeId()
TypeId ns3::SixLowPanMesh::GetInstanceTypeId (void) const virtual
Return the instance type identifier.
Returns
Instance type ID.
Implements ns3::ObjectBase.
Definition at line 1907 of file sixlowpan-header.cc.
References GetTypeId().
GetOriginator()
Address ns3::SixLowPanMesh::GetOriginator (void) const
Get the "Originator" address.
Returns
The Originator address (Mac64Address or Mac16Address).
Definition at line 2079 of file sixlowpan-header.cc.
References m_src.
Referenced by ns3::SixLowPanNetDevice::ReceiveFromDevice().
GetSerializedSize()
uint32_t ns3::SixLowPanMesh::GetSerializedSize (void) const virtual
Get the serialized size of the packet.
Returns
Size.
Implements ns3::Header.
Definition at line 1934 of file sixlowpan-header.cc.
References m_f, m_hopsLeft, and m_v.
Referenced by Deserialize(), and ns3::SixLowPanNetDevice::DoSend().
GetTypeId()
TypeId ns3::SixLowPanMesh::GetTypeId (void) static
Get the type ID.
Returns
The object TypeId.
Definition at line 1898 of file sixlowpan-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::SixLowPanMesh::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 1912 of file sixlowpan-header.cc.
References ns3::Mac16Address::ConvertFrom(), ns3::Mac64Address::ConvertFrom(), ns3::Mac64Address::IsMatchingType(), m_dst, m_hopsLeft, and m_src.
Referenced by ns3::operator<<().
Serialize()
void ns3::SixLowPanMesh::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
[in] start Buffer iterator.
Implements ns3::Header.
Definition at line 1964 of file sixlowpan-header.cc.
References ns3::Address::CopyTo(), m_dst, m_f, m_hopsLeft, m_src, m_v, visualizer.core::start(), ns3::Buffer::Iterator::Write(), and ns3::Buffer::Iterator::WriteU8().
SetFinalDst()
void ns3::SixLowPanMesh::SetFinalDst (Address finalDst)
Set the "Final Destination" address.
Parameters
[in] finalDst The Final Destination address (Mac64Address or Mac16Address).
Definition at line 2084 of file sixlowpan-header.cc.
References ns3::Mac16Address::IsMatchingType(), ns3::Mac64Address::IsMatchingType(), m_dst, m_f, and NS_ABORT_MSG.
Referenced by ns3::SixLowPanNetDevice::DoSend().
SetHopsLeft()
void ns3::SixLowPanMesh::SetHopsLeft (uint8_t hopsLeft)
Set the "Hops Left" field.
Parameters
[in] hopsLeft The number of hops left.
Definition at line 2107 of file sixlowpan-header.cc.
References m_hopsLeft.
Referenced by ns3::SixLowPanNetDevice::DoSend(), and ns3::SixLowPanNetDevice::ReceiveFromDevice().
SetOriginator()
void ns3::SixLowPanMesh::SetOriginator (Address originator)
Set the "Originator" address.
Parameters
[in] originator The Originator address (Mac64Address or Mac16Address).
Definition at line 2061 of file sixlowpan-header.cc.
References ns3::Mac16Address::IsMatchingType(), ns3::Mac64Address::IsMatchingType(), m_src, m_v, and NS_ABORT_MSG.
Referenced by ns3::SixLowPanNetDevice::DoSend().
Member Data Documentation
m_dst
Address ns3::SixLowPanMesh::m_dst private
Destination (final) address.
Definition at line 1389 of file sixlowpan-header.h.
Referenced by SixLowPanMesh(), Deserialize(), GetFinalDst(), Print(), Serialize(), and SetFinalDst().
m_f
bool ns3::SixLowPanMesh::m_f private
True if Destination address is 16 bit.
Definition at line 1387 of file sixlowpan-header.h.
Referenced by SixLowPanMesh(), Deserialize(), GetSerializedSize(), Serialize(), and SetFinalDst().
m_hopsLeft
uint8_t ns3::SixLowPanMesh::m_hopsLeft private
Hops left.
Definition at line 1385 of file sixlowpan-header.h.
Referenced by SixLowPanMesh(), Deserialize(), GetHopsLeft(), GetSerializedSize(), Print(), Serialize(), and SetHopsLeft().
m_src
Address ns3::SixLowPanMesh::m_src private
Originator (source) address.
Definition at line 1388 of file sixlowpan-header.h.
Referenced by SixLowPanMesh(), Deserialize(), GetOriginator(), Print(), Serialize(), and SetOriginator().
m_v
bool ns3::SixLowPanMesh::m_v private
True if Originator address is 16 bit.
Definition at line 1386 of file sixlowpan-header.h.
Referenced by SixLowPanMesh(), Deserialize(), GetSerializedSize(), Serialize(), and SetOriginator().
The documentation for this class was generated from the following files:
src/sixlowpan/model/sixlowpan-header.h
src/sixlowpan/model/sixlowpan-header.cc