ns-3: ns3::Icmpv4DestinationUnreachable Class Reference
ns3::Icmpv4DestinationUnreachable Class Reference
Internet » IPv4 classes and sub-modules » ICMP protocol and associated headers.
ICMP Destination Unreachable header.
#include "icmpv4.h"
Public Types
enum ErrorDestinationUnreachable_e {
ICMPV4_NET_UNREACHABLE = 0, ICMPV4_HOST_UNREACHABLE = 1, ICMPV4_PROTOCOL_UNREACHABLE = 2, ICMPV4_PORT_UNREACHABLE = 3,
ICMPV4_FRAG_NEEDED = 4, ICMPV4_SOURCE_ROUTE_FAILED = 5
}
ICMP error code : Destination Unreachable.
Public Member Functions
Icmpv4DestinationUnreachable ()
virtual ~Icmpv4DestinationUnreachable ()
void GetData (uint8_t payload[8]) const
Get the ICMP carried data.
Ipv4Header GetHeader (void) const
Get the ICMP carried IPv4 header.
uint16_t GetNextHopMtu (void) const
Get the next hop MTU.
void SetData (Ptr< const Packet > data)
Set the ICMP carried data.
void SetHeader (Ipv4Header header)
Set the ICMP carried IPv4 header.
void SetNextHopMtu (uint16_t mtu)
Set the next hop MTU.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get ICMP type.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual uint32_t Deserialize (Buffer::Iterator start)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
Private Attributes
uint8_t m_data [8]
carried data
Ipv4Header m_header
carried IPv4 header
uint16_t m_nextHopMtu
next hop MTU
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
ICMP Destination Unreachable header.
Definition at line 172 of file icmpv4.h.
Member Enumeration Documentation
ErrorDestinationUnreachable_e
enum ns3::Icmpv4DestinationUnreachable::ErrorDestinationUnreachable_e
ICMP error code : Destination Unreachable.
Enumerator
ICMPV4_NET_UNREACHABLE
ICMPV4_HOST_UNREACHABLE
ICMPV4_PROTOCOL_UNREACHABLE
ICMPV4_PORT_UNREACHABLE
ICMPV4_FRAG_NEEDED
ICMPV4_SOURCE_ROUTE_FAILED
Definition at line 178 of file icmpv4.h.
Constructor & Destructor Documentation
Icmpv4DestinationUnreachable()
ns3::Icmpv4DestinationUnreachable::Icmpv4DestinationUnreachable ()
Definition at line 289 of file icmpv4.cc.
References m_data, and NS_LOG_FUNCTION.
~Icmpv4DestinationUnreachable()
ns3::Icmpv4DestinationUnreachable::~Icmpv4DestinationUnreachable () virtual
Definition at line 339 of file icmpv4.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::Icmpv4DestinationUnreachable::Deserialize (Buffer::Iterator start) private virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 367 of file icmpv4.cc.
References ns3::Ipv4Header::Deserialize(), ns3::Buffer::Iterator::GetDistanceFrom(), m_data, m_header, m_nextHopMtu, ns3::Buffer::Iterator::Next(), NS_LOG_FUNCTION, ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetData()
void ns3::Icmpv4DestinationUnreachable::GetData (uint8_t payload[8]) const
Get the ICMP carried data.
Parameters
payload the data (filled)
Definition at line 326 of file icmpv4.cc.
References m_data, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv4L4Protocol::HandleDestUnreach().
GetHeader()
Ipv4Header ns3::Icmpv4DestinationUnreachable::GetHeader (void) const
Get the ICMP carried IPv4 header.
Returns
the header
Definition at line 332 of file icmpv4.cc.
References m_header, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv4L4Protocol::HandleDestUnreach().
GetInstanceTypeId()
TypeId ns3::Icmpv4DestinationUnreachable::GetInstanceTypeId (void) const private virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 343 of file icmpv4.cc.
References GetTypeId(), and NS_LOG_FUNCTION.
GetNextHopMtu()
uint16_t ns3::Icmpv4DestinationUnreachable::GetNextHopMtu (void) const
Get the next hop MTU.
Returns
the MTU
Definition at line 307 of file icmpv4.cc.
References m_nextHopMtu, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv4L4Protocol::HandleDestUnreach().
GetSerializedSize()
uint32_t ns3::Icmpv4DestinationUnreachable::GetSerializedSize (void) const private virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 349 of file icmpv4.cc.
References ns3::Ipv4Header::GetSerializedSize(), m_header, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::Icmpv4DestinationUnreachable::GetTypeId (void) static
Get ICMP type.
Returns
the ICMP type
Definition at line 280 of file icmpv4.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::Icmpv4DestinationUnreachable::Print (std::ostream & os) const private virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 382 of file icmpv4.cc.
References m_data, m_header, NS_LOG_FUNCTION, and ns3::Ipv4Header::Print().
Serialize()
void ns3::Icmpv4DestinationUnreachable::Serialize (Buffer::Iterator start) const private virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 355 of file icmpv4.cc.
References ns3::Ipv4Header::GetSerializedSize(), m_data, m_header, m_nextHopMtu, NS_LOG_FUNCTION, ns3::Ipv4Header::Serialize(), and visualizer.core::start().
SetData()
void ns3::Icmpv4DestinationUnreachable::SetData (Ptr< const Packet > data)
Set the ICMP carried data.
Parameters
data the data
Definition at line 314 of file icmpv4.cc.
References data, m_data, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv4L4Protocol::SendDestUnreach().
SetHeader()
void ns3::Icmpv4DestinationUnreachable::SetHeader (Ipv4Header header)
Set the ICMP carried IPv4 header.
Parameters
header the header
Definition at line 320 of file icmpv4.cc.
References m_header, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv4L4Protocol::SendDestUnreach().
SetNextHopMtu()
void ns3::Icmpv4DestinationUnreachable::SetNextHopMtu (uint16_t mtu)
Set the next hop MTU.
Parameters
mtu the MTU
Definition at line 301 of file icmpv4.cc.
References m_nextHopMtu, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv4L4Protocol::SendDestUnreach().
Member Data Documentation
m_data
uint8_t ns3::Icmpv4DestinationUnreachable::m_data[8] private
carried data
Definition at line 237 of file icmpv4.h.
Referenced by Icmpv4DestinationUnreachable(), Deserialize(), GetData(), Print(), Serialize(), and SetData().
m_header
Ipv4Header ns3::Icmpv4DestinationUnreachable::m_header private
carried IPv4 header
Definition at line 236 of file icmpv4.h.
Referenced by Deserialize(), GetHeader(), GetSerializedSize(), Print(), Serialize(), and SetHeader().
m_nextHopMtu
uint16_t ns3::Icmpv4DestinationUnreachable::m_nextHopMtu private
next hop MTU
Definition at line 235 of file icmpv4.h.
Referenced by Deserialize(), GetNextHopMtu(), Serialize(), and SetNextHopMtu().
The documentation for this class was generated from the following files:
src/internet/model/icmpv4.h
src/internet/model/icmpv4.cc