ns-3: SetChannelFrequencyTest Class Reference
SetChannelFrequencyTest Class Reference
Wifi Models » wifi module tests | Test suites
Set Channel Frequency Test.
Public Member Functions
SetChannelFrequencyTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
Ptr< YansWifiPhy > GetYansWifiPhyPtr (const NetDeviceContainer &nc) const
Get yans wifi phy function.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Set Channel Frequency Test.
Definition at line 867 of file wifi-test.cc.
Constructor & Destructor Documentation
SetChannelFrequencyTest()
SetChannelFrequencyTest::SetChannelFrequencyTest ()
Definition at line 885 of file wifi-test.cc.
Member Function Documentation
DoRun()
void SetChannelFrequencyTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 899 of file wifi-test.cc.
References third::channel, ns3::NodeContainer::Create(), ns3::WifiPhy::DefineChannelNumber(), ns3::NodeContainer::Get(), ns3::WifiPhy::GetChannelNumber(), ns3::WifiPhy::GetChannelWidth(), ns3::WifiPhy::GetFrequency(), GetYansWifiPhyPtr(), NS_TEST_ASSERT_MSG_EQ, third::phy, ns3::Config::Set(), ns3::ObjectBase::SetAttribute(), ns3::WifiMacHelper::SetType(), third::ssid, third::wifi, ns3::WIFI_PHY_STANDARD_80211_10MHZ, ns3::WIFI_PHY_STANDARD_80211_5MHZ, ns3::WIFI_PHY_STANDARD_80211ac, ns3::WIFI_PHY_STANDARD_80211b, ns3::WIFI_PHY_STANDARD_80211g, ns3::WIFI_PHY_STANDARD_80211n_2_4GHZ, ns3::WIFI_PHY_STANDARD_80211n_5GHZ, ns3::WIFI_PHY_STANDARD_holland, and third::wifiApNode.
GetYansWifiPhyPtr()
Ptr< YansWifiPhy > SetChannelFrequencyTest::GetYansWifiPhyPtr (const NetDeviceContainer & nc) const private
Get yans wifi phy function.
Parameters
nc the device collection
Returns
the wifi phy
Definition at line 891 of file wifi-test.cc.
References ns3::NetDeviceContainer::Get(), ns3::Object::GetObject(), and ns3::WifiNetDevice::GetPhy().
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/wifi/test/wifi-test.cc