ns-3: ns3::TcpLpInferenceTest2 Class Reference
ns3::TcpLpInferenceTest2 Class Reference
Testing TcpLp when it is inference phase.
Public Member Functions
TcpLpInferenceTest2 (uint32_t cWnd, uint32_t segmentSize, uint32_t segmentsAcked, Time rtt, const std::string &name)
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void ExecuteTest (void)
Private Attributes
uint32_t m_cWnd
Time m_rtt
uint32_t m_segmentsAcked
uint32_t m_segmentSize
Ptr< TcpSocketState > m_state
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Testing TcpLp when it is inference phase.
Definition at line 165 of file tcp-lp-test.cc.
Constructor & Destructor Documentation
TcpLpInferenceTest2()
ns3::TcpLpInferenceTest2::TcpLpInferenceTest2 (uint32_t cWnd, uint32_t segmentSize, uint32_t segmentsAcked, Time rtt, const std::string & name)
Definition at line 182 of file tcp-lp-test.cc.
Member Function Documentation
DoRun()
void ns3::TcpLpInferenceTest2::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 192 of file tcp-lp-test.cc.
References ns3::Simulator::Destroy(), ExecuteTest(), ns3::Simulator::Run(), ns3::Simulator::Schedule(), and ns3::Seconds().
ExecuteTest()
void ns3::TcpLpInferenceTest2::ExecuteTest (void) private
Definition at line 200 of file tcp-lp-test.cc.
References ns3::TracedValue< T >::Get(), ns3::TcpSocketState::m_cWnd, m_cWnd, ns3::TcpSocketState::m_rcvTimestampEchoReply, ns3::TcpSocketState::m_rcvTimestampValue, m_rtt, m_segmentsAcked, ns3::TcpSocketState::m_segmentSize, m_segmentSize, m_state, and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
Member Data Documentation
m_cWnd
uint32_t ns3::TcpLpInferenceTest2::m_cWnd private
Definition at line 175 of file tcp-lp-test.cc.
Referenced by ExecuteTest().
m_rtt
Time ns3::TcpLpInferenceTest2::m_rtt private
Definition at line 178 of file tcp-lp-test.cc.
Referenced by ExecuteTest().
m_segmentsAcked
uint32_t ns3::TcpLpInferenceTest2::m_segmentsAcked private
Definition at line 177 of file tcp-lp-test.cc.
Referenced by ExecuteTest().
m_segmentSize
uint32_t ns3::TcpLpInferenceTest2::m_segmentSize private
Definition at line 176 of file tcp-lp-test.cc.
Referenced by ExecuteTest().
m_state
Ptr<TcpSocketState> ns3::TcpLpInferenceTest2::m_state private
Definition at line 179 of file tcp-lp-test.cc.
Referenced by ExecuteTest().
The documentation for this class was generated from the following file:
src/internet/test/tcp-lp-test.cc