ns-3: Issue40TestCase Class Reference
Issue40TestCase Class Reference
Make sure that Ideal rate manager recovers when the station is moving away from the access point.
Public Member Functions
Issue40TestCase ()
virtual ~Issue40TestCase ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void RunOne (bool useAmpdu)
Run one function.
void RxSuccessCallback (std::string context, Ptr< const Packet > p)
Callback when packet is successfully received.
void SendPackets (uint8_t numPackets, Ptr< NetDevice > sourceDevice, Address &destination)
Triggers the arrival of 1000 Byte-long packets in the source device.
void TxFinalDataFailedCallback (std::string context, Mac48Address address)
Transmit final data failed function.
Private Attributes
uint16_t m_rxCount
Count number of successfully received data packets.
uint16_t m_txCount
Count number of transmitted data packets.
uint16_t m_txMacFinalDataFailedCount
Count number of unsuccessfully transmitted data packets.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Make sure that Ideal rate manager recovers when the station is moving away from the access point.
The scenario considers an access point and a moving station. Initially, the station is located at 1 meter from the access point. After 1s, the station moves away from the access for 0.5s to reach a point away of 50 meters from the access point. The tests checks the Ideal rate manager is reset once it has failed to transmit a data packet, so that the next data packets can be successfully transmitted using a lower modulation.
See \issueid{40}
Definition at line 2183 of file wifi-test.cc.
Constructor & Destructor Documentation
Issue40TestCase()
Issue40TestCase::Issue40TestCase ()
Definition at line 2222 of file wifi-test.cc.
~Issue40TestCase()
Issue40TestCase::~Issue40TestCase () virtual
Definition at line 2230 of file wifi-test.cc.
Member Function Documentation
DoRun()
void Issue40TestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 2348 of file wifi-test.cc.
References RunOne().
RunOne()
void Issue40TestCase::RunOne (bool useAmpdu) private
Run one function.
Parameters
useAmpdu flag to indicate whether the test should be run with A-MPDU
Definition at line 2258 of file wifi-test.cc.
References ns3::ListPositionAllocator::Add(), ns3::WaypointMobilityModel::AddWaypoint(), third::channel, ns3::Config::Connect(), ns3::NodeContainer::Create(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::PointerValue::Get(), ns3::ObjectBase::GetAttribute(), ns3::WifiNetDevice::GetMac(), ns3::Object::GetObject(), m_rxCount, m_txCount, m_txMacFinalDataFailedCount, third::mac, ns3::MakeCallback(), third::mobility, NS_ASSERT, NS_TEST_ASSERT_MSG_EQ, third::phy, RxSuccessCallback(), ns3::Seconds(), SendPackets(), ns3::Config::Set(), TxFinalDataFailedCallback(), third::wifi, ns3::WIFI_PHY_STANDARD_80211ac, and third::wifiApNode.
Referenced by DoRun().
RxSuccessCallback()
void Issue40TestCase::RxSuccessCallback (std::string context, Ptr< const Packet > p) private
Callback when packet is successfully received.
Parameters
context node context
p the received packet
Definition at line 2235 of file wifi-test.cc.
References m_rxCount.
Referenced by RunOne().
SendPackets()
void Issue40TestCase::SendPackets (uint8_t numPackets, Ptr< NetDevice > sourceDevice, Address & destination) private
Triggers the arrival of 1000 Byte-long packets in the source device.
Parameters
numPackets number of packets in burst
sourceDevice pointer to the source NetDevice
destination address of the destination device
Definition at line 2241 of file wifi-test.cc.
References m_txCount, and ns3::NetDevice::Send().
Referenced by RunOne().
TxFinalDataFailedCallback()
void Issue40TestCase::TxFinalDataFailedCallback (std::string context, Mac48Address address) private
Transmit final data failed function.
Parameters
context the context
adr the MAC address
Definition at line 2252 of file wifi-test.cc.
References m_txMacFinalDataFailedCount.
Referenced by RunOne().
Member Data Documentation
m_rxCount
uint16_t Issue40TestCase::m_rxCount private
Count number of successfully received data packets.
Definition at line 2217 of file wifi-test.cc.
Referenced by RunOne(), and RxSuccessCallback().
m_txCount
uint16_t Issue40TestCase::m_txCount private
Count number of transmitted data packets.
Definition at line 2218 of file wifi-test.cc.
Referenced by RunOne(), and SendPackets().
m_txMacFinalDataFailedCount
uint16_t Issue40TestCase::m_txMacFinalDataFailedCount private
Count number of unsuccessfully transmitted data packets.
Definition at line 2219 of file wifi-test.cc.
Referenced by RunOne(), and TxFinalDataFailedCallback().
The documentation for this class was generated from the following file:
src/wifi/test/wifi-test.cc