ns-3: ns3::FlowClassifier Class Reference
ns3::FlowClassifier Class Reference abstract
Flow Monitor
#include "flow-classifier.h"
Public Member Functions
FlowClassifier ()
virtual ~FlowClassifier ()
virtual void SerializeToXmlStream (std::ostream &os, uint16_t indent) const =0
Serializes the results to an std::ostream in XML format.
Public Member Functions inherited from ns3::SimpleRefCount< FlowClassifier >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Protected Member Functions
FlowId GetNewFlowId ()
Returns a new, unique Flow Identifier.
void Indent (std::ostream &os, uint16_t level) const
Add a number of spaces for indentation purposes.
Private Member Functions
FlowClassifier (FlowClassifier const &)
Defined and not implemented to avoid misuse.
FlowClassifier & operator= (FlowClassifier const &)
Defined and not implemented to avoid misuse.
Private Attributes
FlowId m_lastNewFlowId
Last known Flow ID.
Detailed Description
Provides a method to translate raw packet data into abstract flow identifier and packet identifier parameters. These identifiers are unsigned 32-bit integers that uniquely identify a flow and a packet within that flow, respectively, for the whole simulation, regardless of the point in which the packet was captured. These abstract identifiers are used in the communication between FlowProbe and FlowMonitor, and all collected statistics reference only those abstract identifiers in order to keep the core architecture generic and not tied down to any particular flow capture method or classification system.
Definition at line 53 of file flow-classifier.h.
Constructor & Destructor Documentation
FlowClassifier() [1/2]
ns3::FlowClassifier::FlowClassifier (FlowClassifier const &) private
Defined and not implemented to avoid misuse.
FlowClassifier() [2/2]
ns3::FlowClassifier::FlowClassifier ()
Definition at line 25 of file flow-classifier.cc.
~FlowClassifier()
ns3::FlowClassifier::~FlowClassifier () virtual
Definition at line 31 of file flow-classifier.cc.
Member Function Documentation
GetNewFlowId()
FlowId ns3::FlowClassifier::GetNewFlowId () protected
Returns a new, unique Flow Identifier.
Returns
a new FlowId
Definition at line 36 of file flow-classifier.cc.
References m_lastNewFlowId.
Referenced by ns3::Ipv4FlowClassifier::Classify(), and ns3::Ipv6FlowClassifier::Classify().
Indent()
void ns3::FlowClassifier::Indent (std::ostream & os, uint16_t level) const inline protected
Add a number of spaces for indentation purposes.
Parameters
os The stream to write to.
level The number of spaces to add.
Definition at line 88 of file flow-classifier.h.
Referenced by ns3::Ipv4FlowClassifier::SerializeToXmlStream(), and ns3::Ipv6FlowClassifier::SerializeToXmlStream().
operator=()
FlowClassifier& ns3::FlowClassifier::operator= (FlowClassifier const &) private
Defined and not implemented to avoid misuse.
Returns
SerializeToXmlStream()
virtual void ns3::FlowClassifier::SerializeToXmlStream (std::ostream & os, uint16_t indent) const pure virtual
Serializes the results to an std::ostream in XML format.
Parameters
os the output stream
indent number of spaces to use as base indentation level
Implemented in ns3::Ipv6FlowClassifier, and ns3::Ipv4FlowClassifier.
Member Data Documentation
m_lastNewFlowId
FlowId ns3::FlowClassifier::m_lastNewFlowId private
Last known Flow ID.
Definition at line 56 of file flow-classifier.h.
Referenced by GetNewFlowId().
The documentation for this class was generated from the following files:
src/flow-monitor/model/flow-classifier.h
src/flow-monitor/model/flow-classifier.cc