ns-3: ns3::DsssParameterSet Class Reference
ns3::DsssParameterSet Class Reference
Wifi Models
The DSSS Parameter Set.
#include "dsss-parameter-set.h"
Public Member Functions
DsssParameterSet ()
uint8_t DeserializeInformationField (Buffer::Iterator start, uint8_t length)
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
WifiInformationElementId ElementId () const
uint8_t GetInformationFieldSize () const
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
uint16_t GetSerializedSize () const
Buffer::Iterator Serialize (Buffer::Iterator start) const
void SerializeInformationField (Buffer::Iterator start) const
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
void SetCurrentChannel (uint8_t currentChannel)
Set the Current Channel field in the DsssParameterSet information element.
void SetDsssSupported (uint8_t dsssSupported)
Set DSSS supported.
Public Member Functions inherited from ns3::WifiInformationElement
virtual ~WifiInformationElement ()
Buffer::Iterator Deserialize (Buffer::Iterator i)
Deserialize entire IE, which must be present.
Buffer::Iterator DeserializeIfPresent (Buffer::Iterator i)
Deserialize entire IE if it is present.
virtual WifiInformationElementId ElementIdExt () const
uint16_t GetSerializedSize () const
Get the size of the serialized IE including Element ID and length fields.
virtual bool operator== (WifiInformationElement const &a) const
Compare two IEs for equality by ID & Length, and then through memcmp of serialised version.
virtual void Print (std::ostream &os) const
Generate human-readable form of IE.
Buffer::Iterator Serialize (Buffer::Iterator i) const
Serialize entire IE including Element ID and length fields.
Public Member Functions inherited from ns3::SimpleRefCount< WifiInformationElement >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
uint8_t m_currentChannel
current channel number
bool m_dsssSupported
This is used to decide whether this element should be added to the frame or not.
Detailed Description
The DSSS Parameter Set.
This class knows how to serialise and deserialise the DSSS Parameter Set.
Definition at line 34 of file dsss-parameter-set.h.
Constructor & Destructor Documentation
DsssParameterSet()
ns3::DsssParameterSet::DsssParameterSet ()
Definition at line 25 of file dsss-parameter-set.cc.
Member Function Documentation
DeserializeInformationField()
uint8_t ns3::DsssParameterSet::DeserializeInformationField (Buffer::Iterator start, uint8_t length) virtual
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
length
Returns
the number of bytes read
Implements ns3::WifiInformationElement.
Definition at line 86 of file dsss-parameter-set.cc.
References m_currentChannel, ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
ElementId()
WifiInformationElementId ns3::DsssParameterSet::ElementId () const virtual
Returns
Own unique Element ID
Implements ns3::WifiInformationElement.
Definition at line 32 of file dsss-parameter-set.cc.
References IE_DSSS_PARAMETER_SET.
GetInformationFieldSize()
uint8_t ns3::DsssParameterSet::GetInformationFieldSize () const virtual
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
This is the value that will appear in the second octet of the entire IE - the length field)
Returns
the length of serialized information
Implements ns3::WifiInformationElement.
Definition at line 50 of file dsss-parameter-set.cc.
References m_dsssSupported, and NS_ASSERT.
GetSerializedSize()
uint16_t ns3::DsssParameterSet::GetSerializedSize () const
Definition at line 67 of file dsss-parameter-set.cc.
References ns3::WifiInformationElement::GetSerializedSize(), and m_dsssSupported.
Referenced by ns3::MgtProbeResponseHeader::GetSerializedSize().
Serialize()
Buffer::Iterator ns3::DsssParameterSet::Serialize (Buffer::Iterator start) const
Definition at line 57 of file dsss-parameter-set.cc.
References m_dsssSupported, and ns3::WifiInformationElement::Serialize().
Referenced by ns3::MgtProbeResponseHeader::Serialize().
SerializeInformationField()
void ns3::DsssParameterSet::SerializeInformationField (Buffer::Iterator start) const virtual
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
Implements ns3::WifiInformationElement.
Definition at line 77 of file dsss-parameter-set.cc.
References m_currentChannel, m_dsssSupported, and visualizer.core::start().
SetCurrentChannel()
void ns3::DsssParameterSet::SetCurrentChannel (uint8_t currentChannel)
Set the Current Channel field in the DsssParameterSet information element.
Parameters
currentChannel the CurrentChannel field in the DsssParameterSet information element
Definition at line 44 of file dsss-parameter-set.cc.
References m_currentChannel.
Referenced by ns3::ApWifiMac::GetDsssParameterSet().
SetDsssSupported()
void ns3::DsssParameterSet::SetDsssSupported (uint8_t dsssSupported)
Set DSSS supported.
Parameters
dsssSupported the DSSS supported indicator
Definition at line 38 of file dsss-parameter-set.cc.
References m_dsssSupported.
Referenced by ns3::ApWifiMac::GetDsssParameterSet().
Member Data Documentation
m_currentChannel
uint8_t ns3::DsssParameterSet::m_currentChannel private
current channel number
Definition at line 66 of file dsss-parameter-set.h.
Referenced by DeserializeInformationField(), SerializeInformationField(), and SetCurrentChannel().
m_dsssSupported
bool ns3::DsssParameterSet::m_dsssSupported private
This is used to decide whether this element should be added to the frame or not.
Definition at line 69 of file dsss-parameter-set.h.
Referenced by GetInformationFieldSize(), GetSerializedSize(), Serialize(), SerializeInformationField(), and SetDsssSupported().
The documentation for this class was generated from the following files:
src/wifi/model/dsss-parameter-set.h
src/wifi/model/dsss-parameter-set.cc