ns-3: ns3::SequentialRandomVariable Class Reference
ns3::SequentialRandomVariable Class Reference
Core » Random Variables
The Random Number Generator (RNG) that returns a pattern of sequential values.
#include "random-variable-stream.h"
Public Member Functions
SequentialRandomVariable ()
Creates a sequential RNG with the default values for the sequence parameters.
uint32_t GetConsecutive (void) const
Get the number of times each distinct value of the sequence is repeated before incrementing to the next value.
Ptr< RandomVariableStream > GetIncrement (void) const
Get the increment for the sequence.
virtual uint32_t GetInteger (void)
Get the next random value as an integer drawn from the distribution.
double GetMax (void) const
Get the limit of the sequence, which is (at least) one more than the last value of the sequence.
double GetMin (void) const
Get the first value of the sequence.
virtual double GetValue (void)
Get the next random value as a double drawn from the distribution.
Public Member Functions inherited from ns3::RandomVariableStream
RandomVariableStream ()
Default constructor.
virtual ~RandomVariableStream ()
Destructor.
int64_t GetStream (void) const
Returns the stream number for the RngStream.
bool IsAntithetic (void) const
Check if antithetic values will be generated.
void SetAntithetic (bool isAntithetic)
Specify whether antithetic values should be generated.
void SetStream (int64_t stream)
Specifies the stream number for the RngStream.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::RandomVariableStream
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint32_t m_consecutive
The number of times each distinct value is repeated.
double m_current
The current sequence value.
uint32_t m_currentConsecutive
The number of times the current distinct value has been repeated.
Ptr< RandomVariableStream > m_increment
Increment between distinct values.
bool m_isCurrentSet
Indicates if the current sequence value has been properly initialized.
double m_max
Strict upper bound on the sequence.
double m_min
The first value of the sequence.
Additional Inherited Members
Protected Member Functions inherited from ns3::RandomVariableStream
RngStream * Peek (void) const
Get the pointer to the underlying RngStream.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The Random Number Generator (RNG) that returns a pattern of sequential values.
This RNG has four configuration attributes:
An increment, Increment.
A consecutive repeat numer, Consecutive.
The minimum value, Min.
The maximum value, Max.
The RNG starts at the Min value. Each return value is repeated Consecutive times, before advancing by the Increment. When the Increment would cause the value to equal or exceed Max it is reset to Min first.
For example, if an instance is configured with:
Attribute Value
Min 2
Max 13
Increment 4
Consecutive 3
The sequence will repeat this pattern: 2 2 2 6 6 6 10 10 10.
Notice that Max will be a strict upper bound on the values: all values in the sequence will be less than Max.
Antithetic Values.
This RNG ignores the antithetic setting.
Definition at line 399 of file random-variable-stream.h.
Constructor & Destructor Documentation
SequentialRandomVariable()
ns3::SequentialRandomVariable::SequentialRandomVariable ()
Creates a sequential RNG with the default values for the sequence parameters.
Definition at line 294 of file random-variable-stream.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
GetConsecutive()
uint32_t ns3::SequentialRandomVariable::GetConsecutive (void) const
Get the number of times each distinct value of the sequence is repeated before incrementing to the next value.
Returns
The number of times each value is repeated.
Definition at line 327 of file random-variable-stream.cc.
References m_consecutive, and NS_LOG_FUNCTION.
GetIncrement()
Ptr< RandomVariableStream > ns3::SequentialRandomVariable::GetIncrement (void) const
Get the increment for the sequence.
Returns
The increment between distinct values for the sequence.
Definition at line 320 of file random-variable-stream.cc.
References m_increment, and NS_LOG_FUNCTION.
GetInteger()
uint32_t ns3::SequentialRandomVariable::GetInteger (void) virtual
Get the next random value as an integer drawn from the distribution.
Returns
An integer random value.
Implements ns3::RandomVariableStream.
Definition at line 360 of file random-variable-stream.cc.
References GetValue(), and NS_LOG_FUNCTION.
GetMax()
double ns3::SequentialRandomVariable::GetMax (void) const
Get the limit of the sequence, which is (at least) one more than the last value of the sequence.
Returns
The limit of the sequence.
Definition at line 313 of file random-variable-stream.cc.
References m_max, and NS_LOG_FUNCTION.
GetMin()
double ns3::SequentialRandomVariable::GetMin (void) const
Get the first value of the sequence.
Returns
The first value of the sequence.
Definition at line 306 of file random-variable-stream.cc.
References m_min, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::SequentialRandomVariable::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 270 of file random-variable-stream.cc.
References m_consecutive, m_increment, m_max, m_min, ns3::MakeDoubleAccessor(), ns3::MakeIntegerAccessor(), ns3::MakePointerAccessor(), and ns3::TypeId::SetParent().
GetValue()
double ns3::SequentialRandomVariable::GetValue (void) virtual
Get the next random value as a double drawn from the distribution.
Returns
A floating point random value.
Implements ns3::RandomVariableStream.
Definition at line 334 of file random-variable-stream.cc.
References ns3::RandomVariableStream::GetValue(), m_consecutive, m_current, m_currentConsecutive, m_increment, m_isCurrentSet, m_max, m_min, and NS_LOG_FUNCTION.
Referenced by RandomVariableStreamSequentialTestCase::DoRun(), and GetInteger().
Member Data Documentation
m_consecutive
uint32_t ns3::SequentialRandomVariable::m_consecutive private
The number of times each distinct value is repeated.
Definition at line 455 of file random-variable-stream.h.
Referenced by GetConsecutive(), GetTypeId(), and GetValue().
m_current
double ns3::SequentialRandomVariable::m_current private
The current sequence value.
Definition at line 458 of file random-variable-stream.h.
Referenced by GetValue().
m_currentConsecutive
uint32_t ns3::SequentialRandomVariable::m_currentConsecutive private
The number of times the current distinct value has been repeated.
Definition at line 461 of file random-variable-stream.h.
Referenced by GetValue().
m_increment
Ptr<RandomVariableStream> ns3::SequentialRandomVariable::m_increment private
Increment between distinct values.
Definition at line 452 of file random-variable-stream.h.
Referenced by GetIncrement(), GetTypeId(), and GetValue().
m_isCurrentSet
bool ns3::SequentialRandomVariable::m_isCurrentSet private
Indicates if the current sequence value has been properly initialized.
Definition at line 464 of file random-variable-stream.h.
Referenced by GetValue().
m_max
double ns3::SequentialRandomVariable::m_max private
Strict upper bound on the sequence.
Definition at line 449 of file random-variable-stream.h.
Referenced by GetMax(), GetTypeId(), and GetValue().
m_min
double ns3::SequentialRandomVariable::m_min private
The first value of the sequence.
Definition at line 446 of file random-variable-stream.h.
Referenced by GetMin(), GetTypeId(), and GetValue().
The documentation for this class was generated from the following files:
src/core/model/random-variable-stream.h
src/core/model/random-variable-stream.cc