ns-3: ns3::tests::ObjectVectorTraceConfigTestCase Class Reference
ns3::tests::ObjectVectorTraceConfigTestCase Class Reference
Test suites | Core » Core module tests » Config test suite
Public Member Functions
ObjectVectorTraceConfigTestCase ()
Constructor.
virtual ~ObjectVectorTraceConfigTestCase ()
Destructor.
void Trace (int16_t oldValue, int16_t newValue)
Trace callback without context.
void TraceWithPath (std::string path, int16_t old, int16_t newValue)
Trace callback with context path.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
int16_t m_newValue
Flag to detect tracing result.
std::string m_path
The context path.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test for the ability to trace configure with vectors of objects.
Definition at line 622 of file config-test-suite.cc.
Constructor & Destructor Documentation
ObjectVectorTraceConfigTestCase()
ns3::tests::ObjectVectorTraceConfigTestCase::ObjectVectorTraceConfigTestCase ()
Constructor.
Definition at line 661 of file config-test-suite.cc.
~ObjectVectorTraceConfigTestCase()
virtual ns3::tests::ObjectVectorTraceConfigTestCase::~ObjectVectorTraceConfigTestCase () inline virtual
Destructor.
Definition at line 628 of file config-test-suite.cc.
Member Function Documentation
DoRun()
void ns3::tests::ObjectVectorTraceConfigTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 666 of file config-test-suite.cc.
References ns3::Config::Connect(), ns3::Config::ConnectWithoutContext(), m_newValue, m_path, ns3::MakeCallback(), NS_TEST_ASSERT_MSG_EQ, ns3::Config::RegisterRootNamespaceObject(), Trace(), and TraceWithPath().
Trace()
void ns3::tests::ObjectVectorTraceConfigTestCase::Trace (int16_t oldValue, int16_t newValue) inline
Trace callback without context.
Parameters
oldValue The old value.
newValue The new value.
Definition at line 636 of file config-test-suite.cc.
References m_newValue, and NS_UNUSED.
Referenced by DoRun().
TraceWithPath()
void ns3::tests::ObjectVectorTraceConfigTestCase::TraceWithPath (std::string path, int16_t old, int16_t newValue) inline
Trace callback with context path.
Parameters
path The context path.
old The old value.
newValue The new value.
Definition at line 647 of file config-test-suite.cc.
References m_newValue, m_path, and NS_UNUSED.
Referenced by DoRun().
Member Data Documentation
m_newValue
int16_t ns3::tests::ObjectVectorTraceConfigTestCase::m_newValue private
Flag to detect tracing result.
Definition at line 657 of file config-test-suite.cc.
Referenced by DoRun(), Trace(), and TraceWithPath().
m_path
std::string ns3::tests::ObjectVectorTraceConfigTestCase::m_path private
The context path.
Definition at line 658 of file config-test-suite.cc.
Referenced by DoRun(), and TraceWithPath().
The documentation for this class was generated from the following file:
src/core/test/config-test-suite.cc