ns-3: TcpOptionWSTestCase Class Reference
TcpOptionWSTestCase Class Reference
Internet » internet module tests | Test suites
TCP Window Scaling option Test.
Public Member Functions
TcpOptionWSTestCase (std::string name, uint8_t scale)
Constructor.
void TestDeserialize ()
Deserialization test.
void TestSerialize ()
Serialization test.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
virtual void DoTeardown (void)
Implementation to do any local setup required for this TestCase.
Private Attributes
Buffer m_buffer
Buffer.
uint8_t m_scale
Window scaling.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
TCP Window Scaling option Test.
Definition at line 36 of file tcp-option-test.cc.
Constructor & Destructor Documentation
TcpOptionWSTestCase()
TcpOptionWSTestCase::TcpOptionWSTestCase (std::string name, uint8_t scale)
Constructor.
Parameters
name Test description.
scale Window scaling.
Definition at line 64 of file tcp-option-test.cc.
References m_scale.
Member Function Documentation
DoRun()
void TcpOptionWSTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 71 of file tcp-option-test.cc.
References TestDeserialize(), and TestSerialize().
DoTeardown()
void TcpOptionWSTestCase::DoTeardown (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test teardown
Reimplemented from ns3::TestCase.
Definition at line 106 of file tcp-option-test.cc.
TestDeserialize()
void TcpOptionWSTestCase::TestDeserialize ()
Deserialization test.
Definition at line 91 of file tcp-option-test.cc.
References ns3::Buffer::Begin(), ns3::TcpOptionWinScale::Deserialize(), ns3::TcpOptionWinScale::GetScale(), m_buffer, m_scale, NS_TEST_EXPECT_MSG_EQ, and visualizer.core::start().
Referenced by DoRun().
TestSerialize()
void TcpOptionWSTestCase::TestSerialize ()
Serialization test.
Definition at line 78 of file tcp-option-test.cc.
References ns3::Buffer::AddAtStart(), ns3::Buffer::Begin(), ns3::TcpOptionWinScale::GetScale(), ns3::TcpOptionWinScale::GetSerializedSize(), m_buffer, m_scale, NS_TEST_EXPECT_MSG_EQ, ns3::TcpOptionWinScale::Serialize(), and ns3::TcpOptionWinScale::SetScale().
Referenced by DoRun().
Member Data Documentation
m_buffer
Buffer TcpOptionWSTestCase::m_buffer private
Buffer.
Definition at line 60 of file tcp-option-test.cc.
Referenced by TestDeserialize(), and TestSerialize().
m_scale
uint8_t TcpOptionWSTestCase::m_scale private
Window scaling.
Definition at line 59 of file tcp-option-test.cc.
Referenced by TcpOptionWSTestCase(), TestDeserialize(), and TestSerialize().
The documentation for this class was generated from the following file:
src/internet/test/tcp-option-test.cc