ns-3: WifiAcMappingTest Class Reference
WifiAcMappingTest Class Reference
Public Member Functions
WifiAcMappingTest (uint8_t tos, uint8_t expectedQueue)
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Static Private Member Functions
static void PacketEnqueuedInQueueDisc (uint8_t tos, uint16_t *count, Ptr< const QueueDiscItem > item)
static void PacketEnqueuedInWifiMacQueue (uint8_t tos, uint16_t *count, Ptr< const WifiMacQueueItem > item)
Private Attributes
uint16_t m_expectedQueue
uint16_t m_QueueDiscCount [4]
uint8_t m_tos
uint16_t m_WifiMacQueueCount [4]
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 44 of file wifi-ac-mapping-test-suite.cc.
Constructor & Destructor Documentation
WifiAcMappingTest()
WifiAcMappingTest::WifiAcMappingTest (uint8_t tos, uint8_t expectedQueue)
Definition at line 59 of file wifi-ac-mapping-test-suite.cc.
References m_QueueDiscCount, and m_WifiMacQueueCount.
Member Function Documentation
DoRun()
void WifiAcMappingTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 102 of file wifi-ac-mapping-test-suite.cc.
References ns3::TrafficControlHelper::AddChildQueueDiscs(), ns3::TrafficControlHelper::AddQueueDiscClasses(), first::address, ns3::NodeContainer::Create(), ns3::YansWifiChannelHelper::Create(), ns3::ApplicationContainer::Get(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::PointerValue::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::ObjectBase::GetAttribute(), ns3::QueueDisc::GetNQueueDiscClasses(), ns3::Object::GetObject(), ns3::QueueDisc::GetQueueDiscClass(), ns3::TrafficControlHelper::Install(), ns3::OnOffHelper::Install(), ns3::PacketSinkHelper::Install(), m_expectedQueue, m_QueueDiscCount, m_tos, m_WifiMacQueueCount, ns3::MakeBoundCallback(), third::mobility, NS_TEST_ASSERT_MSG_EQ, NS_TEST_ASSERT_MSG_GT_OR_EQ, PacketEnqueuedInQueueDisc(), PacketEnqueuedInWifiMacQueue(), ns3::Seconds(), ns3::YansWifiPhyHelper::SetChannel(), ns3::OnOffHelper::SetConstantRate(), ns3::TrafficControlHelper::SetRootQueueDisc(), ns3::InetSocketAddress::SetTos(), ns3::WifiMacHelper::SetType(), third::ssid, first::stack, ns3::ApplicationContainer::Start(), ns3::ApplicationContainer::Stop(), ns3::ObjectBase::TraceConnectWithoutContext(), and third::wifi.
PacketEnqueuedInQueueDisc()
void WifiAcMappingTest::PacketEnqueuedInQueueDisc (uint8_t tos, uint16_t * count, Ptr< const QueueDiscItem > item) static private
Definition at line 74 of file wifi-ac-mapping-test-suite.cc.
References ns3::QueueItem::GetUint8Value().
Referenced by DoRun().
PacketEnqueuedInWifiMacQueue()
void WifiAcMappingTest::PacketEnqueuedInWifiMacQueue (uint8_t tos, uint16_t * count, Ptr< const WifiMacQueueItem > item) static private
Definition at line 84 of file wifi-ac-mapping-test-suite.cc.
References ns3::WifiMacQueueItem::GetPacket(), ns3::Ipv4Header::GetTos(), ns3::LlcSnapHeader::GetType(), ns3::Packet::PeekHeader(), and ns3::Packet::RemoveHeader().
Referenced by DoRun().
Member Data Documentation
m_expectedQueue
uint16_t WifiAcMappingTest::m_expectedQueue private
Definition at line 54 of file wifi-ac-mapping-test-suite.cc.
Referenced by DoRun().
m_QueueDiscCount
uint16_t WifiAcMappingTest::m_QueueDiscCount[4] private
Definition at line 55 of file wifi-ac-mapping-test-suite.cc.
Referenced by WifiAcMappingTest(), and DoRun().
m_tos
uint8_t WifiAcMappingTest::m_tos private
Definition at line 53 of file wifi-ac-mapping-test-suite.cc.
Referenced by DoRun().
m_WifiMacQueueCount
uint16_t WifiAcMappingTest::m_WifiMacQueueCount[4] private
Definition at line 56 of file wifi-ac-mapping-test-suite.cc.
Referenced by WifiAcMappingTest(), and DoRun().
The documentation for this class was generated from the following file:
src/test/ns3wifi/wifi-ac-mapping-test-suite.cc