ns-3: ns3::OfdmUcdChannelEncodings Class Reference
ns3::OfdmUcdChannelEncodings Class Reference
This class implements the OFDM UCD channel encodings as described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems" 11.3.1 UCD channel encodings, page 651.
#include "ul-mac-messages.h"
Public Member Functions
OfdmUcdChannelEncodings (void)
~OfdmUcdChannelEncodings (void)
uint8_t GetSbchnlFocContCodes (void) const
Get SB channel for control codes.
uint8_t GetSbchnlReqRegionFullParams (void) const
Get SB channel request region full parameters.
uint16_t GetSize (void) const
Get size.
void SetSbchnlFocContCodes (uint8_t sbchnlFocContCodes)
Set SB channel for control codes.
void SetSbchnlReqRegionFullParams (uint8_t sbchnlReqRegionFullParams)
Set SB channel reguest region full parameters.
Public Member Functions inherited from ns3::UcdChannelEncodings
UcdChannelEncodings (void)
virtual ~UcdChannelEncodings (void)
uint16_t GetBwReqOppSize (void) const
Get BW request opp size.
uint32_t GetFrequency (void) const
Get frequency.
uint16_t GetRangReqOppSize (void) const
Get range request opp size.
uint16_t GetSize (void) const
Get size.
Buffer::Iterator Read (Buffer::Iterator start)
Read item.
void SetBwReqOppSize (uint16_t bwReqOppSize)
Set BW request opp size.
void SetFrequency (uint32_t frequency)
Set frequency.
void SetRangReqOppSize (uint16_t rangReqOppSize)
Set range request opp size.
Buffer::Iterator Write (Buffer::Iterator start) const
Write item.
Private Member Functions
virtual Buffer::Iterator DoRead (Buffer::Iterator start)
Read item.
virtual Buffer::Iterator DoWrite (Buffer::Iterator start) const
Write item.
Private Attributes
uint8_t m_sbchnlFocContCodes
SB channel for control codes.
uint8_t m_sbchnlReqRegionFullParams
SB channel request region full parameters.
Detailed Description
This class implements the OFDM UCD channel encodings as described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems" 11.3.1 UCD channel encodings, page 651.
Definition at line 133 of file ul-mac-messages.h.
Constructor & Destructor Documentation
OfdmUcdChannelEncodings()
ns3::OfdmUcdChannelEncodings::OfdmUcdChannelEncodings (void)
Definition at line 105 of file ul-mac-messages.cc.
~OfdmUcdChannelEncodings()
ns3::OfdmUcdChannelEncodings::~OfdmUcdChannelEncodings (void)
Definition at line 111 of file ul-mac-messages.cc.
Member Function Documentation
DoRead()
Buffer::Iterator ns3::OfdmUcdChannelEncodings::DoRead (Buffer::Iterator start) private virtual
Read item.
Parameters
start the iterator
Returns
the updated iterator
Implements ns3::UcdChannelEncodings.
Definition at line 156 of file ul-mac-messages.cc.
References m_sbchnlFocContCodes, m_sbchnlReqRegionFullParams, ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
DoWrite()
Buffer::Iterator ns3::OfdmUcdChannelEncodings::DoWrite (Buffer::Iterator start) const private virtual
Write item.
Parameters
start the iterator
Returns
the updated iterator
Implements ns3::UcdChannelEncodings.
Definition at line 147 of file ul-mac-messages.cc.
References m_sbchnlFocContCodes, m_sbchnlReqRegionFullParams, visualizer.core::start(), and ns3::Buffer::Iterator::WriteU8().
GetSbchnlFocContCodes()
uint8_t ns3::OfdmUcdChannelEncodings::GetSbchnlFocContCodes (void) const
Get SB channel for control codes.
Returns
the channel for control codes
Definition at line 135 of file ul-mac-messages.cc.
References m_sbchnlFocContCodes.
GetSbchnlReqRegionFullParams()
uint8_t ns3::OfdmUcdChannelEncodings::GetSbchnlReqRegionFullParams (void) const
Get SB channel request region full parameters.
Returns
the channel request region full parameters
Definition at line 129 of file ul-mac-messages.cc.
References m_sbchnlReqRegionFullParams.
GetSize()
uint16_t ns3::OfdmUcdChannelEncodings::GetSize (void) const
Get size.
Returns
the size
Definition at line 141 of file ul-mac-messages.cc.
References ns3::UcdChannelEncodings::GetSize().
Referenced by ns3::Ucd::GetSerializedSize().
SetSbchnlFocContCodes()
void ns3::OfdmUcdChannelEncodings::SetSbchnlFocContCodes (uint8_t sbchnlFocContCodes)
Set SB channel for control codes.
Parameters
sbchnlFocContCodes the channel control codes
Definition at line 123 of file ul-mac-messages.cc.
References m_sbchnlFocContCodes.
Referenced by ns3::BaseStationNetDevice::CreateUcd().
SetSbchnlReqRegionFullParams()
void ns3::OfdmUcdChannelEncodings::SetSbchnlReqRegionFullParams (uint8_t sbchnlReqRegionFullParams)
Set SB channel reguest region full parameters.
Parameters
sbchnlReqRegionFullParams the channel request region full parameters
Definition at line 116 of file ul-mac-messages.cc.
References m_sbchnlReqRegionFullParams.
Referenced by ns3::BaseStationNetDevice::CreateUcd().
Member Data Documentation
m_sbchnlFocContCodes
uint8_t ns3::OfdmUcdChannelEncodings::m_sbchnlFocContCodes private
SB channel for control codes.
Definition at line 181 of file ul-mac-messages.h.
Referenced by DoRead(), DoWrite(), GetSbchnlFocContCodes(), and SetSbchnlFocContCodes().
m_sbchnlReqRegionFullParams
uint8_t ns3::OfdmUcdChannelEncodings::m_sbchnlReqRegionFullParams private
SB channel request region full parameters.
Definition at line 180 of file ul-mac-messages.h.
Referenced by DoRead(), DoWrite(), GetSbchnlReqRegionFullParams(), and SetSbchnlReqRegionFullParams().
The documentation for this class was generated from the following files:
src/wimax/model/ul-mac-messages.h
src/wimax/model/ul-mac-messages.cc