ns-3: ns3::RvBatteryModelHelper Class Reference
ns3::RvBatteryModelHelper Class Reference
Energy Models
Creates a RvBatteryModel object.
#include "rv-battery-model-helper.h"
Public Member Functions
RvBatteryModelHelper ()
~RvBatteryModelHelper ()
void Set (std::string name, const AttributeValue &v)
Public Member Functions inherited from ns3::EnergySourceHelper
virtual ~EnergySourceHelper ()
EnergySourceContainer Install (NodeContainer c) const
EnergySourceContainer Install (Ptr< Node > node) const
EnergySourceContainer Install (std::string nodeName) const
EnergySourceContainer InstallAll (void) const
This function installs an EnergySource on all nodes in simulation.
Private Member Functions
virtual Ptr< EnergySource > DoInstall (Ptr< Node > node) const
Private Attributes
ObjectFactory m_rvBatteryModel
Detailed Description
Creates a RvBatteryModel object.
Definition at line 34 of file rv-battery-model-helper.h.
Constructor & Destructor Documentation
RvBatteryModelHelper()
ns3::RvBatteryModelHelper::RvBatteryModelHelper ()
Definition at line 26 of file rv-battery-model-helper.cc.
References m_rvBatteryModel, and ns3::ObjectFactory::SetTypeId().
~RvBatteryModelHelper()
ns3::RvBatteryModelHelper::~RvBatteryModelHelper ()
Definition at line 31 of file rv-battery-model-helper.cc.
Member Function Documentation
DoInstall()
Ptr< EnergySource > ns3::RvBatteryModelHelper::DoInstall (Ptr< Node > node) const private virtual
Parameters
node Pointer to node where the energy source is to be installed.
Returns
Pointer to the created EnergySource.
Child classes of EnergySourceHelper only have to implement this function, to create and aggregate an EnergySource object onto a single node. Rest of the installation process (eg. installing EnergySource on set of nodes) is implemented in the EnergySourceHelper base class.
Implements ns3::EnergySourceHelper.
Definition at line 42 of file rv-battery-model-helper.cc.
References ns3::ObjectFactory::Create(), m_rvBatteryModel, and NS_ASSERT.
Set()
void ns3::RvBatteryModelHelper::Set (std::string name, const AttributeValue & v) virtual
Parameters
name Name of attribute to set.
v Value of the attribute.
Sets one of the attributes of underlying EnergySource.
Implements ns3::EnergySourceHelper.
Definition at line 36 of file rv-battery-model-helper.cc.
References m_rvBatteryModel, and ns3::ObjectFactory::Set().
Referenced by BatteryLifetimeTest::ConstantLoadTest(), and BatteryLifetimeTest::VariableLoadTest().
Member Data Documentation
m_rvBatteryModel
ObjectFactory ns3::RvBatteryModelHelper::m_rvBatteryModel private
Definition at line 46 of file rv-battery-model-helper.h.
Referenced by RvBatteryModelHelper(), DoInstall(), and Set().
The documentation for this class was generated from the following files:
src/energy/helper/rv-battery-model-helper.h
src/energy/helper/rv-battery-model-helper.cc