ns-3: ns3::ParetoRandomVariable Class Reference
ns3::ParetoRandomVariable Class Reference
Core » Random Variables
The Pareto distribution Random Number Generator (RNG).
#include "random-variable-stream.h"
Public Member Functions
ParetoRandomVariable ()
Creates a Pareto distribution RNG with the default values for the mean, the shape, and upper bound.
double GetBound (void) const
Returns the upper bound on values that can be returned by this RNG stream.
uint32_t GetInteger (uint32_t scale, uint32_t shape, uint32_t bound)
Returns a random unsigned integer from a Pareto distribution with the specified mean, shape, and upper bound.
virtual uint32_t GetInteger (void)
Returns a random unsigned integer from a Pareto distribution with the current mean, shape, and upper bound.
NS_DEPRECATED double GetMean (void) const
Returns the mean parameter for the Pareto distribution returned by this RNG stream.
double GetScale (void) const
Returns the scale parameter for the Pareto distribution returned by this RNG stream.
double GetShape (void) const
Returns the shape parameter for the Pareto distribution returned by this RNG stream.
double GetValue (double scale, double shape, double bound)
Returns a random double from a Pareto distribution with the specified scale, shape, and upper bound.
virtual double GetValue (void)
Returns a random double from a Pareto distribution with the current mean, shape, and upper bound.
Public Member Functions inherited from ns3::RandomVariableStream
RandomVariableStream ()
Default constructor.
virtual ~RandomVariableStream ()
Destructor.
int64_t GetStream (void) const
Returns the stream number for the RngStream.
bool IsAntithetic (void) const
Check if antithetic values will be generated.
void SetAntithetic (bool isAntithetic)
Specify whether antithetic values should be generated.
void SetStream (int64_t stream)
Specifies the stream number for the RngStream.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::RandomVariableStream
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
double m_bound
The upper bound on values that can be returned by this RNG stream.
double m_mean
The mean parameter for the Pareto distribution returned by this RNG stream.
double m_scale
The scale parameter for the Pareto distribution returned by this RNG stream.
double m_shape
The shape parameter for the Pareto distribution returned by this RNG stream.
Additional Inherited Members
Protected Member Functions inherited from ns3::RandomVariableStream
RngStream * Peek (void) const
Get the pointer to the underlying RngStream.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The Pareto distribution Random Number Generator (RNG).
This class supports the creation of objects that return random numbers from a fixed Pareto distribution. It also supports the generation of single random numbers from various Pareto distributions.
The probability density function of a Pareto variable is defined over the range [ ,) as: where is called the scale parameter and is called the Pareto index or shape.
The parameter can be inferred from the mean and the parameter with the equation .
Since Pareto distributions can theoretically return unbounded values, it is sometimes useful to specify a fixed upper limit. Note however when the upper limit is specified, the true mean of the distribution is slightly smaller than the mean value specified.
Here is an example of how to use this class:
double scale = 5.0;
double shape = 2.0;
Ptr<ParetoRandomVariable> x = CreateObject<ParetoRandomVariable> ();
x->SetAttribute ("Scale", DoubleValue (scale));
x->SetAttribute ("Shape", DoubleValue (shape));
// The expected value for the mean of the values returned by a
// Pareto distributed random variable is
//
//                   shape * scale
//     E[value]  =  ---------------  ,
//                     shape - 1
double value = x->GetValue ();
Definition at line 640 of file random-variable-stream.h.
Constructor & Destructor Documentation
ParetoRandomVariable()
ns3::ParetoRandomVariable::ParetoRandomVariable ()
Creates a Pareto distribution RNG with the default values for the mean, the shape, and upper bound.
Definition at line 478 of file random-variable-stream.cc.
References m_mean, NS_LOG_FUNCTION, and NS_UNUSED.
Member Function Documentation
GetBound()
double ns3::ParetoRandomVariable::GetBound (void) const
Returns the upper bound on values that can be returned by this RNG stream.
Returns
The upper bound on values that can be returned by this RNG stream.
Definition at line 516 of file random-variable-stream.cc.
References m_bound, and NS_LOG_FUNCTION.
GetInteger() [1/2]
uint32_t ns3::ParetoRandomVariable::GetInteger (uint32_t scale, uint32_t shape, uint32_t bound)
Returns a random unsigned integer from a Pareto distribution with the specified mean, shape, and upper bound.
Parameters
[in] scale Scale parameter for the Pareto distribution.
[in] shape Shape parameter for the Pareto distribution.
[in] bound Upper bound on values returned.
Returns
A random unsigned integer value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If is a uniform variable over [0,1] and
is a value that would be returned normally.
The value returned in the antithetic case, , is calculated as
which now involves the distance is from 1 in the denominator.
Definition at line 548 of file random-variable-stream.cc.
References GetValue(), and NS_LOG_FUNCTION.
GetInteger() [2/2]
uint32_t ns3::ParetoRandomVariable::GetInteger (void) virtual
Returns a random unsigned integer from a Pareto distribution with the current mean, shape, and upper bound.
Returns
A random unsigned integer value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If is a uniform variable over [0,1] and
is a value that would be returned normally.
The value returned in the antithetic case, , is calculated as
which now involves the distance is from 1 in the denominator.
Implements ns3::RandomVariableStream.
Definition at line 561 of file random-variable-stream.cc.
References GetValue(), m_bound, m_scale, m_shape, and NS_LOG_FUNCTION.
GetMean()
double ns3::ParetoRandomVariable::GetMean (void) const
Returns the mean parameter for the Pareto distribution returned by this RNG stream.
Returns
The mean parameter for the Pareto distribution returned by this RNG stream.
Definition at line 487 of file random-variable-stream.cc.
References m_scale, m_shape, and NS_LOG_FUNCTION.
GetScale()
double ns3::ParetoRandomVariable::GetScale (void) const
Returns the scale parameter for the Pareto distribution returned by this RNG stream.
Returns
The scale parameter for the Pareto distribution returned by this RNG stream.
Definition at line 502 of file random-variable-stream.cc.
References m_scale, and NS_LOG_FUNCTION.
GetShape()
double ns3::ParetoRandomVariable::GetShape (void) const
Returns the shape parameter for the Pareto distribution returned by this RNG stream.
Returns
The shape parameter for the Pareto distribution returned by this RNG stream.
Definition at line 509 of file random-variable-stream.cc.
References m_shape, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::ParetoRandomVariable::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 451 of file random-variable-stream.cc.
References ns3::TypeId::DEPRECATED, m_bound, m_mean, m_scale, m_shape, ns3::MakeDoubleAccessor(), and ns3::TypeId::SetParent().
GetValue() [1/2]
double ns3::ParetoRandomVariable::GetValue (double scale, double shape, double bound)
Returns a random double from a Pareto distribution with the specified scale, shape, and upper bound.
Parameters
[in] scale Mean parameter for the Pareto distribution.
[in] shape Shape parameter for the Pareto distribution.
[in] bound Upper bound on values returned.
Returns
A floating point random value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If is a uniform variable over [0,1] and
is a value that would be returned normally.
The value returned in the antithetic case, , is calculated as
which now involves the distance is from 1 in the denominator.
Definition at line 523 of file random-variable-stream.cc.
References ns3::RandomVariableStream::IsAntithetic(), NS_LOG_FUNCTION, ns3::RandomVariableStream::Peek(), and ns3::RngStream::RandU01().
Referenced by RandomVariableStreamParetoTestCase::ChiSquaredTest(), RandomVariableStreamParetoAntitheticTestCase::ChiSquaredTest(), and RngParetoTestCase::ChiSquaredTest().
GetValue() [2/2]
double ns3::ParetoRandomVariable::GetValue (void) virtual
Returns a random double from a Pareto distribution with the current mean, shape, and upper bound.
Returns
A floating point random value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If is a uniform variable over [0,1] and
is a value that would be returned normally, where
The value returned in the antithetic case, , is calculated as
which now involves the distance is from 1 in the denominator.
Note that we have to re-implement this method here because the method is overloaded above for the three-argument variant and the c++ name resolution rules don't work well with overloads split between parent and child classes.
Implements ns3::RandomVariableStream.
Definition at line 555 of file random-variable-stream.cc.
References m_bound, m_scale, m_shape, and NS_LOG_FUNCTION.
Referenced by GetInteger().
Member Data Documentation
m_bound
double ns3::ParetoRandomVariable::m_bound private
The upper bound on values that can be returned by this RNG stream.
Definition at line 806 of file random-variable-stream.h.
Referenced by GetBound(), GetInteger(), GetTypeId(), and GetValue().
m_mean
double ns3::ParetoRandomVariable::m_mean private
The mean parameter for the Pareto distribution returned by this RNG stream.
Definition at line 797 of file random-variable-stream.h.
Referenced by ParetoRandomVariable(), and GetTypeId().
m_scale
double ns3::ParetoRandomVariable::m_scale private
The scale parameter for the Pareto distribution returned by this RNG stream.
Definition at line 800 of file random-variable-stream.h.
Referenced by GetInteger(), GetMean(), GetScale(), GetTypeId(), and GetValue().
m_shape
double ns3::ParetoRandomVariable::m_shape private
The shape parameter for the Pareto distribution returned by this RNG stream.
Definition at line 803 of file random-variable-stream.h.
Referenced by GetInteger(), GetMean(), GetShape(), GetTypeId(), and GetValue().
The documentation for this class was generated from the following files:
src/core/model/random-variable-stream.h
src/core/model/random-variable-stream.cc