ns-3: ns3::dot11s::IeLinkMetricReport Class Reference
ns3::dot11s::IeLinkMetricReport Class Reference
a IEEE 802.11s Mesh ID 7.3.2.88 of 802.11s draft 3.0
#include "ie-dot11s-metric-report.h"
Public Member Functions
IeLinkMetricReport ()
IeLinkMetricReport (uint32_t metric)
Constructor.
virtual uint8_t DeserializeInformationField (Buffer::Iterator start, uint8_t length)
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
virtual WifiInformationElementId ElementId () const
virtual uint8_t GetInformationFieldSize () const
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
uint32_t GetMetric ()
Get metric value.
virtual void Print (std::ostream &os) const
Generate human-readable form of IE.
virtual void SerializeInformationField (Buffer::Iterator i) const
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
void SetMetric (uint32_t metric)
Set metric value.
Public Member Functions inherited from ns3::WifiInformationElement
virtual ~WifiInformationElement ()
Buffer::Iterator Deserialize (Buffer::Iterator i)
Deserialize entire IE, which must be present.
Buffer::Iterator DeserializeIfPresent (Buffer::Iterator i)
Deserialize entire IE if it is present.
virtual WifiInformationElementId ElementIdExt () const
uint16_t GetSerializedSize () const
Get the size of the serialized IE including Element ID and length fields.
virtual bool operator== (WifiInformationElement const &a) const
Compare two IEs for equality by ID & Length, and then through memcmp of serialised version.
Buffer::Iterator Serialize (Buffer::Iterator i) const
Serialize entire IE including Element ID and length fields.
Public Member Functions inherited from ns3::SimpleRefCount< WifiInformationElement >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
uint32_t m_metric
metric
Friends
bool operator< (const IeLinkMetricReport &a, const IeLinkMetricReport &b)
less than operator
bool operator== (const IeLinkMetricReport &a, const IeLinkMetricReport &b)
equality operator
bool operator> (const IeLinkMetricReport &a, const IeLinkMetricReport &b)
greater than operator
Detailed Description
a IEEE 802.11s Mesh ID 7.3.2.88 of 802.11s draft 3.0
Definition at line 34 of file ie-dot11s-metric-report.h.
Constructor & Destructor Documentation
IeLinkMetricReport() [1/2]
ns3::dot11s::IeLinkMetricReport::IeLinkMetricReport ()
Definition at line 26 of file ie-dot11s-metric-report.cc.
IeLinkMetricReport() [2/2]
ns3::dot11s::IeLinkMetricReport::IeLinkMetricReport (uint32_t metric)
Constructor.
Parameters
metric the metric
Definition at line 30 of file ie-dot11s-metric-report.cc.
References m_metric.
Member Function Documentation
DeserializeInformationField()
uint8_t ns3::dot11s::IeLinkMetricReport::DeserializeInformationField (Buffer::Iterator start, uint8_t length) virtual
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
length
Returns
the number of bytes read
Implements ns3::WifiInformationElement.
Definition at line 60 of file ie-dot11s-metric-report.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_metric, ns3::Buffer::Iterator::ReadLsbtohU32(), and visualizer.core::start().
ElementId()
WifiInformationElementId ns3::dot11s::IeLinkMetricReport::ElementId () const virtual
Returns
Own unique Element ID
Implements ns3::WifiInformationElement.
Definition at line 35 of file ie-dot11s-metric-report.cc.
References IE_MESH_LINK_METRIC_REPORT.
GetInformationFieldSize()
uint8_t ns3::dot11s::IeLinkMetricReport::GetInformationFieldSize () const virtual
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
This is the value that will appear in the second octet of the entire IE - the length field)
Returns
the length of serialized information
Implements ns3::WifiInformationElement.
Definition at line 40 of file ie-dot11s-metric-report.cc.
GetMetric()
uint32_t ns3::dot11s::IeLinkMetricReport::GetMetric ()
Get metric value.
Returns
the metric
Definition at line 45 of file ie-dot11s-metric-report.cc.
References m_metric.
Print()
void ns3::dot11s::IeLinkMetricReport::Print (std::ostream & os) const virtual
Generate human-readable form of IE.
Parameters
os output stream
Reimplemented from ns3::WifiInformationElement.
Definition at line 67 of file ie-dot11s-metric-report.cc.
References m_metric.
Referenced by ns3::dot11s::operator<<().
SerializeInformationField()
void ns3::dot11s::IeLinkMetricReport::SerializeInformationField (Buffer::Iterator start) const virtual
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
Implements ns3::WifiInformationElement.
Definition at line 55 of file ie-dot11s-metric-report.cc.
References m_metric, and ns3::Buffer::Iterator::WriteHtolsbU32().
SetMetric()
void ns3::dot11s::IeLinkMetricReport::SetMetric (uint32_t metric)
Set metric value.
Parameters
metric the metric
Definition at line 50 of file ie-dot11s-metric-report.cc.
References m_metric.
Friends And Related Function Documentation
operator<
bool operator< (const IeLinkMetricReport & a, const IeLinkMetricReport & b) friend
less than operator
Parameters
a lhs
b lhs
Returns
true if equal
Definition at line 76 of file ie-dot11s-metric-report.cc.
operator==
bool operator== (const IeLinkMetricReport & a, const IeLinkMetricReport & b) friend
equality operator
Parameters
a lhs
b lhs
Returns
true if equal
Definition at line 72 of file ie-dot11s-metric-report.cc.
operator>
bool operator> (const IeLinkMetricReport & a, const IeLinkMetricReport & b) friend
greater than operator
Parameters
a lhs
b lhs
Returns
true if equal
Definition at line 82 of file ie-dot11s-metric-report.cc.
Member Data Documentation
m_metric
uint32_t ns3::dot11s::IeLinkMetricReport::m_metric private
metric
Definition at line 63 of file ie-dot11s-metric-report.h.
Referenced by IeLinkMetricReport(), DeserializeInformationField(), GetMetric(), ns3::dot11s::operator<(), ns3::dot11s::operator==(), ns3::dot11s::operator>(), Print(), SerializeInformationField(), and SetMetric().
The documentation for this class was generated from the following files:
src/mesh/model/dot11s/ie-dot11s-metric-report.h
src/mesh/model/dot11s/ie-dot11s-metric-report.cc