ns-3: ns3::TwoRayGroundPropagationLossModel Class Reference
ns3::TwoRayGroundPropagationLossModel Class Reference
Propagation Models
a Two-Ray Ground propagation loss model ported from NS2
#include "propagation-loss-model.h"
Public Member Functions
TwoRayGroundPropagationLossModel ()
double GetFrequency (void) const
double GetMinDistance (void) const
double GetSystemLoss (void) const
void SetFrequency (double frequency)
void SetHeightAboveZ (double heightAboveZ)
void SetMinDistance (double minDistance)
void SetSystemLoss (double systemLoss)
Public Member Functions inherited from ns3::PropagationLossModel
PropagationLossModel ()
virtual ~PropagationLossModel ()
int64_t AssignStreams (int64_t stream)
If this loss model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
double CalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account all the PropagationLossModel(s) chained to the current one.
Ptr< PropagationLossModel > GetNext ()
Gets the next PropagationLossModel in the chain of loss models that act on the signal.
void SetNext (Ptr< PropagationLossModel > next)
Enables a chain of loss models to act on the signal.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::PropagationLossModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
TwoRayGroundPropagationLossModel (const TwoRayGroundPropagationLossModel &)
Copy constructor.
double DbmFromW (double w) const
Transforms a Watt value to Dbm.
double DbmToW (double dbm) const
Transforms a Dbm value to Watt.
virtual int64_t DoAssignStreams (int64_t stream)
Subclasses must implement this; those not using random variables can return zero.
virtual double DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account only the particular PropagationLossModel.
TwoRayGroundPropagationLossModel & operator= (const TwoRayGroundPropagationLossModel &)
Copy constructor.
Private Attributes
double m_frequency
the carrier frequency
double m_heightAboveZ
antenna height above the node's Z coordinate
double m_lambda
the carrier wavelength
double m_minDistance
minimum distance for the model
double m_systemLoss
the system loss
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
a Two-Ray Ground propagation loss model ported from NS2
Two-ray ground reflection model.
The original equation in Rappaport's book assumes L = 1. To be consistent with the free space equation, L is added here.
Ht and Hr are set at the respective nodes z coordinate plus a model parameter set via SetHeightAboveZ.
The two-ray model does not give a good result for short distances, due to the oscillation caused by constructive and destructive combination of the two rays. Instead the Friis free-space model is used for small distances.
The crossover distance, below which Friis is used, is calculated as follows:
In the implementation, is calculated as , where m/s is the speed of light in vacuum, and is the frequency in Hz which can be configured by the user via the Frequency attribute.
Definition at line 374 of file propagation-loss-model.h.
Constructor & Destructor Documentation
TwoRayGroundPropagationLossModel() [1/2]
ns3::TwoRayGroundPropagationLossModel::TwoRayGroundPropagationLossModel ()
Definition at line 317 of file propagation-loss-model.cc.
TwoRayGroundPropagationLossModel() [2/2]
ns3::TwoRayGroundPropagationLossModel::TwoRayGroundPropagationLossModel (const TwoRayGroundPropagationLossModel &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Member Function Documentation
DbmFromW()
double ns3::TwoRayGroundPropagationLossModel::DbmFromW (double w) const private
Transforms a Watt value to Dbm.
Parameters
w the Watt value
Returns
the Dbm
Definition at line 368 of file propagation-loss-model.cc.
DbmToW()
double ns3::TwoRayGroundPropagationLossModel::DbmToW (double dbm) const private
Transforms a Dbm value to Watt.
Parameters
dbm the Dbm value
Returns
the Watts
Definition at line 361 of file propagation-loss-model.cc.
DoAssignStreams()
int64_t ns3::TwoRayGroundPropagationLossModel::DoAssignStreams (int64_t stream) private virtual
Subclasses must implement this; those not using random variables can return zero.
Implements ns3::PropagationLossModel.
Definition at line 449 of file propagation-loss-model.cc.
DoCalcRxPower()
double ns3::TwoRayGroundPropagationLossModel::DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const private virtual
Returns the Rx Power taking into account only the particular PropagationLossModel.
Parameters
txPowerDbm current transmission power (in dBm)
a the mobility model of the source
b the mobility model of the destination
Returns
the reception power after adding/multiplying propagation loss (in dBm)
Implements ns3::PropagationLossModel.
Definition at line 375 of file propagation-loss-model.cc.
References ns3::MobilityModel::GetDistanceFrom(), ns3::MobilityModel::GetPosition(), m_heightAboveZ, m_lambda, m_minDistance, m_systemLoss, and NS_LOG_DEBUG.
GetFrequency()
double ns3::TwoRayGroundPropagationLossModel::GetFrequency (void) const
Returns
the current frequency (Hz)
Definition at line 355 of file propagation-loss-model.cc.
References m_frequency.
Referenced by GetTypeId().
GetMinDistance()
double ns3::TwoRayGroundPropagationLossModel::GetMinDistance (void) const
Returns
the minimum distance.
Definition at line 336 of file propagation-loss-model.cc.
References m_minDistance.
Referenced by GetTypeId().
GetSystemLoss()
double ns3::TwoRayGroundPropagationLossModel::GetSystemLoss (void) const
Returns
the current system loss (dimension-less)
Definition at line 326 of file propagation-loss-model.cc.
References m_systemLoss.
GetTypeId()
TypeId ns3::TwoRayGroundPropagationLossModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 286 of file propagation-loss-model.cc.
References GetFrequency(), GetMinDistance(), m_heightAboveZ, m_systemLoss, ns3::MakeDoubleAccessor(), SetFrequency(), SetMinDistance(), and ns3::TypeId::SetParent().
operator=()
TwoRayGroundPropagationLossModel& ns3::TwoRayGroundPropagationLossModel::operator= (const TwoRayGroundPropagationLossModel &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Returns
SetFrequency()
void ns3::TwoRayGroundPropagationLossModel::SetFrequency (double frequency)
Parameters
frequency (Hz)
Set the carrier frequency used in the TwoRayGround model calculation.
Definition at line 347 of file propagation-loss-model.cc.
References m_frequency, and m_lambda.
Referenced by GetTypeId().
SetHeightAboveZ()
void ns3::TwoRayGroundPropagationLossModel::SetHeightAboveZ (double heightAboveZ)
Parameters
heightAboveZ the model antenna height above the node's Z coordinate
Set the model antenna height above the node's Z coordinate
Definition at line 341 of file propagation-loss-model.cc.
References m_heightAboveZ.
SetMinDistance()
void ns3::TwoRayGroundPropagationLossModel::SetMinDistance (double minDistance)
Parameters
minDistance the minimum distance
Below this distance, the txpower is returned unmodified as the rxpower.
Definition at line 331 of file propagation-loss-model.cc.
References m_minDistance.
Referenced by GetTypeId().
SetSystemLoss()
void ns3::TwoRayGroundPropagationLossModel::SetSystemLoss (double systemLoss)
Parameters
systemLoss (dimension-less)
Set the system loss used by the TwoRayGround propagation model.
Definition at line 321 of file propagation-loss-model.cc.
References m_systemLoss.
Member Data Documentation
m_frequency
double ns3::TwoRayGroundPropagationLossModel::m_frequency private
the carrier frequency
Definition at line 461 of file propagation-loss-model.h.
Referenced by GetFrequency(), and SetFrequency().
m_heightAboveZ
double ns3::TwoRayGroundPropagationLossModel::m_heightAboveZ private
antenna height above the node's Z coordinate
Definition at line 464 of file propagation-loss-model.h.
Referenced by DoCalcRxPower(), GetTypeId(), and SetHeightAboveZ().
m_lambda
double ns3::TwoRayGroundPropagationLossModel::m_lambda private
the carrier wavelength
Definition at line 460 of file propagation-loss-model.h.
Referenced by DoCalcRxPower(), and SetFrequency().
m_minDistance
double ns3::TwoRayGroundPropagationLossModel::m_minDistance private
minimum distance for the model
Definition at line 463 of file propagation-loss-model.h.
Referenced by DoCalcRxPower(), GetMinDistance(), and SetMinDistance().
m_systemLoss
double ns3::TwoRayGroundPropagationLossModel::m_systemLoss private
the system loss
Definition at line 462 of file propagation-loss-model.h.
Referenced by DoCalcRxPower(), GetSystemLoss(), GetTypeId(), and SetSystemLoss().
The documentation for this class was generated from the following files:
src/propagation/model/propagation-loss-model.h
src/propagation/model/propagation-loss-model.cc