ns-3: Ns3TcpNoDelayTestCase Class Reference
Ns3TcpNoDelayTestCase Class Reference
Public Member Functions
Ns3TcpNoDelayTestCase (bool noDelay)
virtual ~Ns3TcpNoDelayTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void SinkRx (std::string path, Ptr< const Packet > p, const Address &address)
Private Attributes
TestVectors< uint32_t > m_inputs
bool m_noDelay
TestVectors< uint32_t > m_responses
bool m_writeResults
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 47 of file ns3tcp-no-delay-test-suite.cc.
Constructor & Destructor Documentation
Ns3TcpNoDelayTestCase()
Ns3TcpNoDelayTestCase::Ns3TcpNoDelayTestCase (bool noDelay)
Definition at line 64 of file ns3tcp-no-delay-test-suite.cc.
~Ns3TcpNoDelayTestCase()
virtual Ns3TcpNoDelayTestCase::~Ns3TcpNoDelayTestCase () inline virtual
Definition at line 51 of file ns3tcp-no-delay-test-suite.cc.
Member Function Documentation
DoRun()
void Ns3TcpNoDelayTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 78 of file ns3tcp-no-delay-test-suite.cc.
References ns3::TestVectors< T >::Add(), ns3::Node::AddApplication(), first::address, ns3::Config::Connect(), first::devices, ns3::TestVectors< T >::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::TestVectors< T >::GetN(), ns3::InternetStackHelper::InstallAll(), m_inputs, m_noDelay, m_responses, m_writeResults, ns3::MakeCallback(), NS_TEST_ASSERT_MSG_EQ, first::pointToPoint, ns3::Seconds(), ns3::Config::SetDefault(), ns3::Application::SetStartTime(), ns3::Application::SetStopTime(), ns3::SocketWriter::Setup(), sink, SinkRx(), ns3::ApplicationContainer::Start(), and ns3::ApplicationContainer::Stop().
SinkRx()
void Ns3TcpNoDelayTestCase::SinkRx (std::string path, Ptr< const Packet > p, const Address & address) private
Definition at line 72 of file ns3tcp-no-delay-test-suite.cc.
References ns3::TestVectors< T >::Add(), ns3::Packet::GetSize(), and m_responses.
Referenced by DoRun().
Member Data Documentation
m_inputs
TestVectors<uint32_t> Ns3TcpNoDelayTestCase::m_inputs private
Definition at line 60 of file ns3tcp-no-delay-test-suite.cc.
Referenced by DoRun().
m_noDelay
bool Ns3TcpNoDelayTestCase::m_noDelay private
Definition at line 55 of file ns3tcp-no-delay-test-suite.cc.
Referenced by DoRun().
m_responses
TestVectors<uint32_t> Ns3TcpNoDelayTestCase::m_responses private
Definition at line 61 of file ns3tcp-no-delay-test-suite.cc.
Referenced by DoRun(), and SinkRx().
m_writeResults
bool Ns3TcpNoDelayTestCase::m_writeResults private
Definition at line 56 of file ns3tcp-no-delay-test-suite.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/test/ns3tcp/ns3tcp-no-delay-test-suite.cc