ns-3: ns3::Ipv4EndPointDemux Class Reference
ns3::Ipv4EndPointDemux Class Reference
Internet » IPv4 classes and sub-modules
Demultiplexes packets to various transport layer endpoints.
#include "ipv4-end-point-demux.h"
Public Types
typedef std::list< Ipv4EndPoint * > EndPoints
Container of the IPv4 endpoints.
typedef std::list< Ipv4EndPoint * >::iterator EndPointsI
Iterator to the container of the IPv4 endpoints.
Public Member Functions
Ipv4EndPointDemux ()
~Ipv4EndPointDemux ()
Ipv4EndPoint * Allocate (Ipv4Address address)
Allocate a Ipv4EndPoint.
Ipv4EndPoint * Allocate (Ptr< NetDevice > boundNetDevice, Ipv4Address address, uint16_t port)
Allocate a Ipv4EndPoint.
Ipv4EndPoint * Allocate (Ptr< NetDevice > boundNetDevice, Ipv4Address localAddress, uint16_t localPort, Ipv4Address peerAddress, uint16_t peerPort)
Allocate a Ipv4EndPoint.
Ipv4EndPoint * Allocate (Ptr< NetDevice > boundNetDevice, uint16_t port)
Allocate a Ipv4EndPoint.
Ipv4EndPoint * Allocate (void)
Allocate a Ipv4EndPoint.
void DeAllocate (Ipv4EndPoint *endPoint)
Remove a end point.
EndPoints GetAllEndPoints (void)
Get the entire list of end points registered.
EndPoints Lookup (Ipv4Address daddr, uint16_t dport, Ipv4Address saddr, uint16_t sport, Ptr< Ipv4Interface > incomingInterface)
lookup for a match with all the parameters.
bool LookupLocal (Ptr< NetDevice > boundNetDevice, Ipv4Address addr, uint16_t port)
Lookup for address and port.
bool LookupPortLocal (uint16_t port)
Lookup for port local.
Ipv4EndPoint * SimpleLookup (Ipv4Address daddr, uint16_t dport, Ipv4Address saddr, uint16_t sport)
simple lookup for a match with all the parameters.
Private Member Functions
uint16_t AllocateEphemeralPort (void)
Allocate an ephemeral port.
Private Attributes
EndPoints m_endPoints
A list of IPv4 end points.
uint16_t m_ephemeral
The ephemeral port.
uint16_t m_portFirst
The first ephemeral port.
uint16_t m_portLast
The last ephemeral port.
Detailed Description
Demultiplexes packets to various transport layer endpoints.
This class serves as a lookup table to match partial or full information about a four-tuple to an ns3::Ipv4EndPoint. It internally contains a list of endpoints, and has APIs to add and find endpoints in this demux. This code is shared in common to TCP and UDP protocols in ns3. This demux sits between ns3's layer four and the socket layer
Definition at line 45 of file ipv4-end-point-demux.h.
Member Typedef Documentation
EndPoints
typedef std::list<Ipv4EndPoint *> ns3::Ipv4EndPointDemux::EndPoints
Container of the IPv4 endpoints.
Definition at line 50 of file ipv4-end-point-demux.h.
EndPointsI
typedef std::list<Ipv4EndPoint *>::iterator ns3::Ipv4EndPointDemux::EndPointsI
Iterator to the container of the IPv4 endpoints.
Definition at line 55 of file ipv4-end-point-demux.h.
Constructor & Destructor Documentation
Ipv4EndPointDemux()
ns3::Ipv4EndPointDemux::Ipv4EndPointDemux ()
Definition at line 31 of file ipv4-end-point-demux.cc.
References NS_LOG_FUNCTION.
~Ipv4EndPointDemux()
ns3::Ipv4EndPointDemux::~Ipv4EndPointDemux ()
Definition at line 37 of file ipv4-end-point-demux.cc.
References m_endPoints, and NS_LOG_FUNCTION.
Member Function Documentation
Allocate() [1/5]
Ipv4EndPoint * ns3::Ipv4EndPointDemux::Allocate (Ipv4Address address)
Allocate a Ipv4EndPoint.
Parameters
address IPv4 address
Returns
an Ipv4EndPoint instance
Definition at line 95 of file ipv4-end-point-demux.cc.
References first::address, AllocateEphemeralPort(), m_endPoints, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_WARN, and port.
Allocate() [2/5]
Ipv4EndPoint * ns3::Ipv4EndPointDemux::Allocate (Ptr< NetDevice > boundNetDevice, Ipv4Address address, uint16_t port)
Allocate a Ipv4EndPoint.
Parameters
boundNetDevice Bound NetDevice (if any)
address local address
port local port
Returns
an Ipv4EndPoint instance
Definition at line 119 of file ipv4-end-point-demux.cc.
References first::address, LookupLocal(), m_endPoints, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_WARN, and port.
Allocate() [3/5]
Ipv4EndPoint * ns3::Ipv4EndPointDemux::Allocate (Ptr< NetDevice > boundNetDevice, Ipv4Address localAddress, uint16_t localPort, Ipv4Address peerAddress, uint16_t peerPort)
Allocate a Ipv4EndPoint.
Parameters
boundNetDevice Bound NetDevice (if any)
localAddress local address
localPort local port
peerAddress peer address
peerPort peer port
Returns
an Ipv4EndPoint instance
Definition at line 134 of file ipv4-end-point-demux.cc.
References m_endPoints, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_WARN, and ns3::Ipv4EndPoint::SetPeer().
Allocate() [4/5]
Ipv4EndPoint * ns3::Ipv4EndPointDemux::Allocate (Ptr< NetDevice > boundNetDevice, uint16_t port)
Allocate a Ipv4EndPoint.
Parameters
boundNetDevice Bound NetDevice (if any)
port local port
Returns
an Ipv4EndPoint instance
Definition at line 111 of file ipv4-end-point-demux.cc.
References Allocate(), ns3::Ipv4Address::GetAny(), NS_LOG_FUNCTION, and port.
Allocate() [5/5]
Ipv4EndPoint * ns3::Ipv4EndPointDemux::Allocate (void)
Allocate a Ipv4EndPoint.
Returns
an empty Ipv4EndPoint instance
Definition at line 79 of file ipv4-end-point-demux.cc.
References AllocateEphemeralPort(), ns3::Ipv4Address::GetAny(), m_endPoints, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_WARN, and port.
Referenced by Allocate(), ns3::NscTcpL4Protocol::Allocate(), ns3::TcpL4Protocol::Allocate(), and ns3::UdpL4Protocol::Allocate().
AllocateEphemeralPort()
uint16_t ns3::Ipv4EndPointDemux::AllocateEphemeralPort (void) private
Allocate an ephemeral port.
Returns
the ephemeral port
Definition at line 381 of file ipv4-end-point-demux.cc.
References LookupPortLocal(), m_ephemeral, m_portFirst, m_portLast, NS_LOG_FUNCTION, and port.
Referenced by Allocate().
DeAllocate()
void ns3::Ipv4EndPointDemux::DeAllocate (Ipv4EndPoint * endPoint)
Remove a end point.
Parameters
endPoint the end point to remove
Definition at line 161 of file ipv4-end-point-demux.cc.
References m_endPoints, and NS_LOG_FUNCTION.
Referenced by ns3::TcpL4Protocol::DeAllocate(), and ns3::UdpL4Protocol::DeAllocate().
GetAllEndPoints()
Ipv4EndPointDemux::EndPoints ns3::Ipv4EndPointDemux::GetAllEndPoints (void)
Get the entire list of end points registered.
Returns
list of Ipv4EndPoint
Definition at line 179 of file ipv4-end-point-demux.cc.
References m_endPoints, and NS_LOG_FUNCTION.
Referenced by ns3::NscTcpL4Protocol::wakeup().
Lookup()
Ipv4EndPointDemux::EndPoints ns3::Ipv4EndPointDemux::Lookup (Ipv4Address daddr, uint16_t dport, Ipv4Address saddr, uint16_t sport, Ptr< Ipv4Interface > incomingInterface)
lookup for a match with all the parameters.
The function will return a list of most-matching EndPoints, in this order:
Full match
All but local address
Only local port and local address match
Only local port match
EndPoint with disabled Rx are skipped.
Parameters
daddr destination address to test
dport destination port to test
saddr source address to test
sport source port to test
incomingInterface the incoming interface
Returns
list of IPv4EndPoints (could be 0 element)
Definition at line 199 of file ipv4-end-point-demux.cc.
References ns3::Ipv4Address::CombineMask(), ns3::Ipv4Interface::GetAddress(), ns3::Ipv4Address::GetAny(), ns3::Ipv4EndPoint::GetBoundNetDevice(), ns3::Ipv4Interface::GetDevice(), ns3::Ipv4InterfaceAddress::GetLocal(), ns3::Ipv4EndPoint::GetLocalAddress(), ns3::Ipv4EndPoint::GetLocalPort(), ns3::Ipv4InterfaceAddress::GetMask(), ns3::Ipv4Interface::GetNAddresses(), ns3::Ipv4EndPoint::GetPeerAddress(), ns3::Ipv4EndPoint::GetPeerPort(), ns3::Ipv4Mask::GetPrefixLength(), ns3::Ipv4EndPoint::IsRxEnabled(), m_endPoints, NS_ABORT_MSG_IF, NS_LOG_DEBUG, NS_LOG_FUNCTION, and NS_LOG_LOGIC().
LookupLocal()
bool ns3::Ipv4EndPointDemux::LookupLocal (Ptr< NetDevice > boundNetDevice, Ipv4Address addr, uint16_t port)
Lookup for address and port.
Parameters
boundNetDevice Bound NetDevice (if any)
addr address to test
port port to test
Returns
true if there is a match in EndPoints, false otherwise
Definition at line 63 of file ipv4-end-point-demux.cc.
References m_endPoints, NS_LOG_FUNCTION, and port.
Referenced by Allocate().
LookupPortLocal()
bool ns3::Ipv4EndPointDemux::LookupPortLocal (uint16_t port)
Lookup for port local.
Parameters
port port to test
Returns
true if a port local is in EndPoints, false otherwise
Definition at line 49 of file ipv4-end-point-demux.cc.
References m_endPoints, NS_LOG_FUNCTION, and port.
Referenced by AllocateEphemeralPort().
SimpleLookup()
Ipv4EndPoint * ns3::Ipv4EndPointDemux::SimpleLookup (Ipv4Address daddr, uint16_t dport, Ipv4Address saddr, uint16_t sport)
simple lookup for a match with all the parameters.
Parameters
daddr destination address to test
dport destination port to test
saddr source address to test
sport source port to test
Returns
IPv4EndPoint (0 if not found)
Definition at line 339 of file ipv4-end-point-demux.cc.
References ns3::Ipv4Address::GetAny(), m_endPoints, and NS_LOG_FUNCTION.
Referenced by ns3::TcpL4Protocol::ReceiveIcmp(), and ns3::UdpL4Protocol::ReceiveIcmp().
Member Data Documentation
m_endPoints
EndPoints ns3::Ipv4EndPointDemux::m_endPoints private
A list of IPv4 end points.
Definition at line 194 of file ipv4-end-point-demux.h.
Referenced by ~Ipv4EndPointDemux(), Allocate(), DeAllocate(), GetAllEndPoints(), Lookup(), LookupLocal(), LookupPortLocal(), and SimpleLookup().
m_ephemeral
uint16_t ns3::Ipv4EndPointDemux::m_ephemeral private
The ephemeral port.
Definition at line 179 of file ipv4-end-point-demux.h.
Referenced by AllocateEphemeralPort().
m_portFirst
uint16_t ns3::Ipv4EndPointDemux::m_portFirst private
The first ephemeral port.
Definition at line 189 of file ipv4-end-point-demux.h.
Referenced by AllocateEphemeralPort().
m_portLast
uint16_t ns3::Ipv4EndPointDemux::m_portLast private
The last ephemeral port.
Definition at line 184 of file ipv4-end-point-demux.h.
Referenced by AllocateEphemeralPort().
The documentation for this class was generated from the following files:
src/internet/model/ipv4-end-point-demux.h
src/internet/model/ipv4-end-point-demux.cc