ns-3: ns3::BuildingsChannelConditionModel Class Reference
ns3::BuildingsChannelConditionModel Class Reference
Determines the channel condition based on the buildings deployed in the scenario.
#include "buildings-channel-condition-model.h"
Public Member Functions
BuildingsChannelConditionModel ()
Constructor for the BuildingsChannelConditionModel class.
virtual ~BuildingsChannelConditionModel () override
Destructor for the BuildingsChannelConditionModel class.
virtual int64_t AssignStreams (int64_t stream) override
If this model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
virtual Ptr< ChannelCondition > GetChannelCondition (Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const override
Computes the condition of the channel between a and b.
Public Member Functions inherited from ns3::ChannelConditionModel
ChannelConditionModel ()
Constructor for the ChannelConditionModel class.
ChannelConditionModel (const ChannelConditionModel &)=delete
Copy constructor.
virtual ~ChannelConditionModel ()
Destructor for the ChannelConditionModel class.
ChannelConditionModel & operator= (const ChannelConditionModel &)=delete
Copy constructor.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ChannelConditionModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
bool IsLineOfSightBlocked (const Vector &l1, const Vector &l2) const
Checks if the line of sight between position l1 and position l2 is blocked by a building.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Determines the channel condition based on the buildings deployed in the scenario.
Code adapted from MmWave3gppBuildingsPropagationLossModel
Definition at line 39 of file buildings-channel-condition-model.h.
Constructor & Destructor Documentation
BuildingsChannelConditionModel()
ns3::BuildingsChannelConditionModel::BuildingsChannelConditionModel ()
Constructor for the BuildingsChannelConditionModel class.
Definition at line 45 of file buildings-channel-condition-model.cc.
~BuildingsChannelConditionModel()
ns3::BuildingsChannelConditionModel::~BuildingsChannelConditionModel () override virtual
Destructor for the BuildingsChannelConditionModel class.
Definition at line 50 of file buildings-channel-condition-model.cc.
Member Function Documentation
AssignStreams()
int64_t ns3::BuildingsChannelConditionModel::AssignStreams (int64_t stream) override virtual
If this model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream
Returns
the number of stream indices assigned by this model
Implements ns3::ChannelConditionModel.
Definition at line 125 of file buildings-channel-condition-model.cc.
References NS_UNUSED.
GetChannelCondition()
Ptr< ChannelCondition > ns3::BuildingsChannelConditionModel::GetChannelCondition (Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const override virtual
Computes the condition of the channel between a and b.
Parameters
a mobility model
b mobility model
Returns
the condition of the channel between a and b
Implements ns3::ChannelConditionModel.
Definition at line 55 of file buildings-channel-condition-model.cc.
References IsLineOfSightBlocked(), and NS_ASSERT_MSG().
Referenced by BuildingsChannelConditionModelTestCase::DoRun().
GetTypeId()
TypeId ns3::BuildingsChannelConditionModel::GetTypeId (void) static
Get the type ID.
Get the type ID.
Returns
the object TypeId
Definition at line 35 of file buildings-channel-condition-model.cc.
References ns3::TypeId::SetParent().
IsLineOfSightBlocked()
bool ns3::BuildingsChannelConditionModel::IsLineOfSightBlocked (const Vector & l1, const Vector & l2) const private
Checks if the line of sight between position l1 and position l2 is blocked by a building.
Parameters
l1 position
l2 position
Returns
true if the line of sight is blocked, false otherwise
Definition at line 107 of file buildings-channel-condition-model.cc.
References ns3::BuildingList::Begin(), and ns3::BuildingList::End().
Referenced by GetChannelCondition().
The documentation for this class was generated from the following files:
src/buildings/model/buildings-channel-condition-model.h
src/buildings/model/buildings-channel-condition-model.cc