ns-3: ns3::SixLowPanFragN Class Reference
ns3::SixLowPanFragN Class Reference
6LoWPAN
6LoWPAN FRAGN header - see RFC 4944.
#include "sixlowpan-header.h"
Public Member Functions
SixLowPanFragN (void)
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
uint8_t GetDatagramOffset (void) const
Get the datagram offset.
uint16_t GetDatagramSize (void) const
Get the datagram size.
uint16_t GetDatagramTag (void) const
Get the datagram tag.
virtual TypeId GetInstanceTypeId (void) const
Return the instance type identifier.
virtual uint32_t GetSerializedSize (void) const
Get the serialized size of the packet.
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetDatagramOffset (uint8_t datagramOffset)
Set the datagram offset.
void SetDatagramSize (uint16_t datagramSize)
Set the datagram size.
void SetDatagramTag (uint16_t datagramTag)
Set the datagram tag.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_datagramOffset
Datagram offset.
uint16_t m_datagramSize
Datagram size.
uint16_t m_datagramTag
Datagram tag.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
6LoWPAN FRAGN header - see RFC 4944.
Definition at line 453 of file sixlowpan-header.h.
Constructor & Destructor Documentation
SixLowPanFragN()
ns3::SixLowPanFragN::SixLowPanFragN (void)
Definition at line 636 of file sixlowpan-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::SixLowPanFragN::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
[in] start Buffer iterator.
Returns
Size of the packet.
Implements ns3::Header.
Definition at line 682 of file sixlowpan-header.cc.
References GetSerializedSize(), m_datagramOffset, m_datagramSize, m_datagramTag, ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetDatagramOffset()
uint8_t ns3::SixLowPanFragN::GetDatagramOffset (void) const
Get the datagram offset.
Returns
The datagram offset.
Definition at line 721 of file sixlowpan-header.cc.
References m_datagramOffset.
Referenced by ns3::SixLowPanNetDevice::ProcessFragment().
GetDatagramSize()
uint16_t ns3::SixLowPanFragN::GetDatagramSize (void) const
Get the datagram size.
Returns
The datagram size.
Definition at line 701 of file sixlowpan-header.cc.
References m_datagramSize.
Referenced by ns3::SixLowPanNetDevice::ProcessFragment().
GetDatagramTag()
uint16_t ns3::SixLowPanFragN::GetDatagramTag (void) const
Get the datagram tag.
Returns
The datagram tag.
Definition at line 711 of file sixlowpan-header.cc.
References m_datagramTag.
Referenced by ns3::SixLowPanNetDevice::ProcessFragment().
GetInstanceTypeId()
TypeId ns3::SixLowPanFragN::GetInstanceTypeId (void) const virtual
Return the instance type identifier.
Returns
Instance type ID.
Implements ns3::ObjectBase.
Definition at line 654 of file sixlowpan-header.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::SixLowPanFragN::GetSerializedSize (void) const virtual
Get the serialized size of the packet.
Returns
Size.
Implements ns3::Header.
Definition at line 664 of file sixlowpan-header.cc.
Referenced by Deserialize(), and ns3::SixLowPanNetDevice::DoFragmentation().
GetTypeId()
TypeId ns3::SixLowPanFragN::GetTypeId (void) static
Get the type ID.
Returns
The object TypeId.
Definition at line 645 of file sixlowpan-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::SixLowPanFragN::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 659 of file sixlowpan-header.cc.
References m_datagramOffset, m_datagramSize, and m_datagramTag.
Referenced by ns3::operator<<().
Serialize()
void ns3::SixLowPanFragN::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
[in] start Buffer iterator.
Implements ns3::Header.
Definition at line 669 of file sixlowpan-header.cc.
References ns3::SixLowPanDispatch::LOWPAN_FRAGN, m_datagramOffset, m_datagramSize, m_datagramTag, visualizer.core::start(), ns3::Buffer::Iterator::WriteU16(), and ns3::Buffer::Iterator::WriteU8().
SetDatagramOffset()
void ns3::SixLowPanFragN::SetDatagramOffset (uint8_t datagramOffset)
Set the datagram offset.
Parameters
[in] datagramOffset The datagram offset.
Definition at line 716 of file sixlowpan-header.cc.
References m_datagramOffset.
Referenced by ns3::SixLowPanNetDevice::DoFragmentation().
SetDatagramSize()
void ns3::SixLowPanFragN::SetDatagramSize (uint16_t datagramSize)
Set the datagram size.
Parameters
[in] datagramSize The datagram size.
Definition at line 696 of file sixlowpan-header.cc.
References m_datagramSize.
Referenced by ns3::SixLowPanNetDevice::DoFragmentation().
SetDatagramTag()
void ns3::SixLowPanFragN::SetDatagramTag (uint16_t datagramTag)
Set the datagram tag.
Parameters
[in] datagramTag The datagram tag.
Definition at line 706 of file sixlowpan-header.cc.
References m_datagramTag.
Referenced by ns3::SixLowPanNetDevice::DoFragmentation().
Member Data Documentation
m_datagramOffset
uint8_t ns3::SixLowPanFragN::m_datagramOffset private
Datagram offset.
Definition at line 530 of file sixlowpan-header.h.
Referenced by Deserialize(), GetDatagramOffset(), Print(), Serialize(), and SetDatagramOffset().
m_datagramSize
uint16_t ns3::SixLowPanFragN::m_datagramSize private
Datagram size.
Definition at line 528 of file sixlowpan-header.h.
Referenced by Deserialize(), GetDatagramSize(), Print(), Serialize(), and SetDatagramSize().
m_datagramTag
uint16_t ns3::SixLowPanFragN::m_datagramTag private
Datagram tag.
Definition at line 529 of file sixlowpan-header.h.
Referenced by Deserialize(), GetDatagramTag(), Print(), Serialize(), and SetDatagramTag().
The documentation for this class was generated from the following files:
src/sixlowpan/model/sixlowpan-header.h
src/sixlowpan/model/sixlowpan-header.cc