ns-3: ns3::EpcX2ResourceStatusUpdateHeader Class Reference
ns3::EpcX2ResourceStatusUpdateHeader Class Reference
EpcX2ResourceStatusUpdateHeader.
#include "epc-x2-header.h"
Public Member Functions
EpcX2ResourceStatusUpdateHeader ()
virtual ~EpcX2ResourceStatusUpdateHeader ()
virtual uint32_t Deserialize (Buffer::Iterator start)
std::vector< EpcX2Sap::CellMeasurementResultItem > GetCellMeasurementResultList () const
Get cell measurement results list function.
uint16_t GetEnb1MeasurementId () const
Get ENB1 measurement ID function.
uint16_t GetEnb2MeasurementId () const
Get ENB2 measurement ID function.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint32_t GetLengthOfIes () const
Get length of IEs function.
uint32_t GetNumberOfIes () const
Get number of IEs function.
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetCellMeasurementResultList (std::vector< EpcX2Sap::CellMeasurementResultItem > cellMeasurementResultList)
Set cell measurement results list function.
void SetEnb1MeasurementId (uint16_t enb1MeasurementId)
Set ENB1 measurement ID function.
void SetEnb2MeasurementId (uint16_t enb2MeasurementId)
Set ENB2 measurement ID function.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
std::vector< EpcX2Sap::CellMeasurementResultItem > m_cellMeasurementResultList
cell measurement result list
uint16_t m_enb1MeasurementId
ENB1 measurement.
uint16_t m_enb2MeasurementId
ENB2 measurement.
uint32_t m_headerLength
header length
uint32_t m_numberOfIes
number of IEs
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
EpcX2ResourceStatusUpdateHeader.
Definition at line 585 of file epc-x2-header.h.
Constructor & Destructor Documentation
EpcX2ResourceStatusUpdateHeader()
ns3::EpcX2ResourceStatusUpdateHeader::EpcX2ResourceStatusUpdateHeader ()
Definition at line 1317 of file epc-x2-header.cc.
References m_cellMeasurementResultList.
~EpcX2ResourceStatusUpdateHeader()
ns3::EpcX2ResourceStatusUpdateHeader::~EpcX2ResourceStatusUpdateHeader () virtual
Definition at line 1326 of file epc-x2-header.cc.
References m_cellMeasurementResultList, m_enb1MeasurementId, m_enb2MeasurementId, m_headerLength, and m_numberOfIes.
Member Function Documentation
Deserialize()
uint32_t ns3::EpcX2ResourceStatusUpdateHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 1394 of file epc-x2-header.cc.
References ns3::EpcX2Sap::CompositeAvailCapacity::capacityValue, ns3::EpcX2Sap::CompositeAvailCapacity::cellCapacityClassValue, ns3::EpcX2Sap::CellMeasurementResultItem::dlCompositeAvailableCapacity, ns3::EpcX2Sap::CellMeasurementResultItem::dlGbrPrbUsage, ns3::EpcX2Sap::CellMeasurementResultItem::dlHardwareLoadIndicator, ns3::EpcX2Sap::CellMeasurementResultItem::dlNonGbrPrbUsage, ns3::EpcX2Sap::CellMeasurementResultItem::dlS1TnlLoadIndicator, ns3::EpcX2Sap::CellMeasurementResultItem::dlTotalPrbUsage, GetSerializedSize(), m_cellMeasurementResultList, m_enb1MeasurementId, m_enb2MeasurementId, m_headerLength, m_numberOfIes, ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadU8(), ns3::EpcX2Sap::CellMeasurementResultItem::sourceCellId, visualizer.core::start(), ns3::EpcX2Sap::CellMeasurementResultItem::ulCompositeAvailableCapacity, ns3::EpcX2Sap::CellMeasurementResultItem::ulGbrPrbUsage, ns3::EpcX2Sap::CellMeasurementResultItem::ulHardwareLoadIndicator, ns3::EpcX2Sap::CellMeasurementResultItem::ulNonGbrPrbUsage, ns3::EpcX2Sap::CellMeasurementResultItem::ulS1TnlLoadIndicator, and ns3::EpcX2Sap::CellMeasurementResultItem::ulTotalPrbUsage.
GetCellMeasurementResultList()
std::vector< EpcX2Sap::CellMeasurementResultItem > ns3::EpcX2ResourceStatusUpdateHeader::GetCellMeasurementResultList () const
Get cell measurement results list function.
Returns
the cell measurement results list
Definition at line 1466 of file epc-x2-header.cc.
References m_cellMeasurementResultList.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
GetEnb1MeasurementId()
uint16_t ns3::EpcX2ResourceStatusUpdateHeader::GetEnb1MeasurementId () const
Get ENB1 measurement ID function.
Returns
the ENB1 measurement ID
Definition at line 1442 of file epc-x2-header.cc.
References m_enb1MeasurementId.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
GetEnb2MeasurementId()
uint16_t ns3::EpcX2ResourceStatusUpdateHeader::GetEnb2MeasurementId () const
Get ENB2 measurement ID function.
Returns
the ENB2 measurement ID
Definition at line 1454 of file epc-x2-header.cc.
References m_enb2MeasurementId.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
GetInstanceTypeId()
TypeId ns3::EpcX2ResourceStatusUpdateHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 1347 of file epc-x2-header.cc.
References GetTypeId().
GetLengthOfIes()
uint32_t ns3::EpcX2ResourceStatusUpdateHeader::GetLengthOfIes () const
Get length of IEs function.
Returns
the length of IEs
Definition at line 1481 of file epc-x2-header.cc.
References m_headerLength.
Referenced by ns3::EpcX2::DoSendResourceStatusUpdate().
GetNumberOfIes()
uint32_t ns3::EpcX2ResourceStatusUpdateHeader::GetNumberOfIes () const
Get number of IEs function.
Returns
the number of IEs
Definition at line 1487 of file epc-x2-header.cc.
References m_numberOfIes.
Referenced by ns3::EpcX2::DoSendResourceStatusUpdate().
GetSerializedSize()
uint32_t ns3::EpcX2ResourceStatusUpdateHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 1353 of file epc-x2-header.cc.
References m_headerLength.
Referenced by Deserialize().
GetTypeId()
TypeId ns3::EpcX2ResourceStatusUpdateHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 1336 of file epc-x2-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::EpcX2ResourceStatusUpdateHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 1434 of file epc-x2-header.cc.
References m_cellMeasurementResultList, m_enb1MeasurementId, and m_enb2MeasurementId.
Serialize()
void ns3::EpcX2ResourceStatusUpdateHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 1359 of file epc-x2-header.cc.
References ns3::EpcX2Sap::CompositeAvailCapacity::capacityValue, ns3::EpcX2Sap::CompositeAvailCapacity::cellCapacityClassValue, ns3::EpcX2Sap::CellMeasurementResultItem::dlCompositeAvailableCapacity, ns3::EpcX2Sap::CellMeasurementResultItem::dlGbrPrbUsage, ns3::EpcX2Sap::CellMeasurementResultItem::dlHardwareLoadIndicator, ns3::EpcX2Sap::CellMeasurementResultItem::dlNonGbrPrbUsage, ns3::EpcX2Sap::CellMeasurementResultItem::dlS1TnlLoadIndicator, ns3::EpcX2Sap::CellMeasurementResultItem::dlTotalPrbUsage, m_cellMeasurementResultList, m_enb1MeasurementId, m_enb2MeasurementId, ns3::EpcX2Sap::CellMeasurementResultItem::sourceCellId, visualizer.core::start(), ns3::EpcX2Sap::CellMeasurementResultItem::ulCompositeAvailableCapacity, ns3::EpcX2Sap::CellMeasurementResultItem::ulGbrPrbUsage, ns3::EpcX2Sap::CellMeasurementResultItem::ulHardwareLoadIndicator, ns3::EpcX2Sap::CellMeasurementResultItem::ulNonGbrPrbUsage, ns3::EpcX2Sap::CellMeasurementResultItem::ulS1TnlLoadIndicator, ns3::EpcX2Sap::CellMeasurementResultItem::ulTotalPrbUsage, ns3::Buffer::Iterator::WriteHtonU16(), and ns3::Buffer::Iterator::WriteU8().
SetCellMeasurementResultList()
void ns3::EpcX2ResourceStatusUpdateHeader::SetCellMeasurementResultList (std::vector< EpcX2Sap::CellMeasurementResultItem > cellMeasurementResultList)
Set cell measurement results list function.
Parameters
cellMeasurementResultList the cell measurement results list
Definition at line 1472 of file epc-x2-header.cc.
References m_cellMeasurementResultList, and m_headerLength.
Referenced by ns3::EpcX2::DoSendResourceStatusUpdate().
SetEnb1MeasurementId()
void ns3::EpcX2ResourceStatusUpdateHeader::SetEnb1MeasurementId (uint16_t enb1MeasurementId)
Set ENB1 measurement ID function.
Parameters
enb1MeasurementId the ENB1 measurement ID
Definition at line 1448 of file epc-x2-header.cc.
References m_enb1MeasurementId.
Referenced by ns3::EpcX2::DoSendResourceStatusUpdate().
SetEnb2MeasurementId()
void ns3::EpcX2ResourceStatusUpdateHeader::SetEnb2MeasurementId (uint16_t enb2MeasurementId)
Set ENB2 measurement ID function.
Parameters
enb2MeasurementId ENB2 measruement ID
Definition at line 1460 of file epc-x2-header.cc.
References m_enb2MeasurementId.
Referenced by ns3::EpcX2::DoSendResourceStatusUpdate().
Member Data Documentation
m_cellMeasurementResultList
std::vector<EpcX2Sap::CellMeasurementResultItem> ns3::EpcX2ResourceStatusUpdateHeader::m_cellMeasurementResultList private
cell measurement result list
Definition at line 653 of file epc-x2-header.h.
Referenced by EpcX2ResourceStatusUpdateHeader(), ~EpcX2ResourceStatusUpdateHeader(), Deserialize(), GetCellMeasurementResultList(), Print(), Serialize(), and SetCellMeasurementResultList().
m_enb1MeasurementId
uint16_t ns3::EpcX2ResourceStatusUpdateHeader::m_enb1MeasurementId private
ENB1 measurement.
Definition at line 651 of file epc-x2-header.h.
Referenced by ~EpcX2ResourceStatusUpdateHeader(), Deserialize(), GetEnb1MeasurementId(), Print(), Serialize(), and SetEnb1MeasurementId().
m_enb2MeasurementId
uint16_t ns3::EpcX2ResourceStatusUpdateHeader::m_enb2MeasurementId private
ENB2 measurement.
Definition at line 652 of file epc-x2-header.h.
Referenced by ~EpcX2ResourceStatusUpdateHeader(), Deserialize(), GetEnb2MeasurementId(), Print(), Serialize(), and SetEnb2MeasurementId().
m_headerLength
uint32_t ns3::EpcX2ResourceStatusUpdateHeader::m_headerLength private
header length
Definition at line 649 of file epc-x2-header.h.
Referenced by ~EpcX2ResourceStatusUpdateHeader(), Deserialize(), GetLengthOfIes(), GetSerializedSize(), and SetCellMeasurementResultList().
m_numberOfIes
uint32_t ns3::EpcX2ResourceStatusUpdateHeader::m_numberOfIes private
number of IEs
Definition at line 648 of file epc-x2-header.h.
Referenced by ~EpcX2ResourceStatusUpdateHeader(), Deserialize(), and GetNumberOfIes().
The documentation for this class was generated from the following files:
src/lte/model/epc-x2-header.h
src/lte/model/epc-x2-header.cc