ns-3: BasicEnergyHarvesterTestCase Class Reference
BasicEnergyHarvesterTestCase Class Reference
Public Member Functions
BasicEnergyHarvesterTestCase ()
~BasicEnergyHarvesterTestCase ()
void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Public Attributes
ObjectFactory m_energyHarvester
ObjectFactory m_energySource
double m_timeS
double m_tolerance
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 36 of file basic-energy-harvester-test.cc.
Constructor & Destructor Documentation
BasicEnergyHarvesterTestCase()
BasicEnergyHarvesterTestCase::BasicEnergyHarvesterTestCase ()
Definition at line 52 of file basic-energy-harvester-test.cc.
References m_timeS, and m_tolerance.
~BasicEnergyHarvesterTestCase()
BasicEnergyHarvesterTestCase::~BasicEnergyHarvesterTestCase ()
Definition at line 59 of file basic-energy-harvester-test.cc.
Member Function Documentation
DoRun()
void BasicEnergyHarvesterTestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 64 of file basic-energy-harvester-test.cc.
References ns3::Object::AggregateObject(), ns3::EnergySource::ConnectEnergyHarvester(), ns3::ObjectFactory::Create(), ns3::BasicEnergySource::GetInitialEnergy(), ns3::EnergyHarvester::GetPower(), ns3::BasicEnergySource::GetRemainingEnergy(), m_energyHarvester, m_energySource, m_timeS, m_tolerance, ns3::Now(), NS_LOG_DEBUG, NS_TEST_ASSERT_MSG_EQ_TOL, ns3::Seconds(), ns3::EnergyHarvester::SetEnergySource(), ns3::BasicEnergyHarvester::SetHarvestedPowerUpdateInterval(), ns3::EnergyHarvester::SetNode(), and ns3::ObjectFactory::SetTypeId().
Member Data Documentation
m_energyHarvester
ObjectFactory BasicEnergyHarvesterTestCase::m_energyHarvester
Definition at line 48 of file basic-energy-harvester-test.cc.
Referenced by DoRun().
m_energySource
ObjectFactory BasicEnergyHarvesterTestCase::m_energySource
Definition at line 47 of file basic-energy-harvester-test.cc.
Referenced by DoRun().
m_timeS
double BasicEnergyHarvesterTestCase::m_timeS
Definition at line 44 of file basic-energy-harvester-test.cc.
Referenced by BasicEnergyHarvesterTestCase(), and DoRun().
m_tolerance
double BasicEnergyHarvesterTestCase::m_tolerance
Definition at line 45 of file basic-energy-harvester-test.cc.
Referenced by BasicEnergyHarvesterTestCase(), and DoRun().
The documentation for this class was generated from the following file:
src/energy/test/basic-energy-harvester-test.cc