ns-3: LteAggregationThroughputScaleTestCase Class Reference
LteAggregationThroughputScaleTestCase Class Reference
LTE Models
Testing that UE throughput scales linearly with number of component carriers. Also attaches UE to last component carrier to make sure no code assumes that primary carrier is first.
#include "lte-test-aggregation-throughput-scale.h"
Public Member Functions
LteAggregationThroughputScaleTestCase (std::string name)
Creates an instance of the carrier aggregation throughput scaling test case.
virtual ~LteAggregationThroughputScaleTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun ()
Setup the simulation, run it, and verify the result.
double GetThroughput (uint8_t numberOfComponentCarriers)
Get throughput function.
Private Attributes
uint16_t m_actualCellId
Cell ID UE has attached to.
uint16_t m_expectedCellId
Cell ID UE is expected to attach to.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Testing that UE throughput scales linearly with number of component carriers. Also attaches UE to last component carrier to make sure no code assumes that primary carrier is first.
Definition at line 47 of file lte-test-aggregation-throughput-scale.h.
Constructor & Destructor Documentation
LteAggregationThroughputScaleTestCase()
LteAggregationThroughputScaleTestCase::LteAggregationThroughputScaleTestCase (std::string name)
Creates an instance of the carrier aggregation throughput scaling test case.
Parameters
name name of this test
Definition at line 59 of file lte-test-aggregation-throughput-scale.cc.
References ns3::TestCase::GetName(), and NS_LOG_FUNCTION.
~LteAggregationThroughputScaleTestCase()
LteAggregationThroughputScaleTestCase::~LteAggregationThroughputScaleTestCase () virtual
Definition at line 66 of file lte-test-aggregation-throughput-scale.cc.
References ns3::TestCase::GetName(), and NS_LOG_FUNCTION.
Member Function Documentation
DoRun()
void LteAggregationThroughputScaleTestCase::DoRun () private virtual
Setup the simulation, run it, and verify the result.
Implements ns3::TestCase.
Definition at line 153 of file lte-test-aggregation-throughput-scale.cc.
References GetThroughput(), m_actualCellId, m_expectedCellId, NS_TEST_ASSERT_MSG_EQ, and NS_TEST_ASSERT_MSG_EQ_TOL.
GetThroughput()
double LteAggregationThroughputScaleTestCase::GetThroughput (uint8_t numberOfComponentCarriers) private
Get throughput function.
Parameters
numberOfComponentCarriers Number of component carriers
Returns
The total data received (in Megabits)
Definition at line 72 of file lte-test-aggregation-throughput-scale.cc.
References ns3::ApplicationContainer::Add(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::TestCase::GetName(), ns3::Ipv4StaticRoutingHelper::GetStaticRouting(), ns3::PacketSink::GetTotalRx(), ns3::FriisSpectrumPropagationLossModel::GetTypeId(), ns3::InternetStackHelper::Install(), m_actualCellId, m_expectedCellId, third::mobility, NS_LOG_FUNCTION, port, ns3::Seconds(), ns3::ObjectBase::SetAttribute(), ns3::Ipv4AddressHelper::SetBase(), ns3::Config::SetDefault(), sink, and ns3::ApplicationContainer::Start().
Referenced by DoRun().
Member Data Documentation
m_actualCellId
uint16_t LteAggregationThroughputScaleTestCase::m_actualCellId private
Cell ID UE has attached to.
Definition at line 73 of file lte-test-aggregation-throughput-scale.h.
Referenced by DoRun(), and GetThroughput().
m_expectedCellId
uint16_t LteAggregationThroughputScaleTestCase::m_expectedCellId private
Cell ID UE is expected to attach to.
Definition at line 72 of file lte-test-aggregation-throughput-scale.h.
Referenced by DoRun(), and GetThroughput().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-aggregation-throughput-scale.h
src/lte/test/lte-test-aggregation-throughput-scale.cc