ns-3: LrWpanCcaTestCase Class Reference
LrWpanCcaTestCase Class Reference
LR-WPAN models » LrWpan module tests | Test suites
LrWpan CCA Test.
Public Member Functions
LrWpanCcaTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Static Private Member Functions
static void PhyRxBegin (LrWpanCcaTestCase *testcase, Ptr< LrWpanNetDevice > device, Ptr< const Packet > packet)
Function called when PhyRxBegin is hit.
static void PhyRxDrop (LrWpanCcaTestCase *testcase, Ptr< LrWpanNetDevice > device, Ptr< const Packet > packet)
Function called when PhyRxDrop is hit.
static void PhyRxEnd (LrWpanCcaTestCase *testcase, Ptr< LrWpanNetDevice > device, Ptr< const Packet > packet, double sinr)
Function called when PhyRxEnd is hit.
static void PhyTxBegin (LrWpanCcaTestCase *testcase, Ptr< LrWpanNetDevice > device, Ptr< const Packet > packet)
Function called when PhyTxBegin is hit.
static void PhyTxEnd (LrWpanCcaTestCase *testcase, Ptr< LrWpanNetDevice > device, Ptr< const Packet > packet)
Function called when PhyTxEnd is hit.
static void PlmeCcaConfirm (LrWpanCcaTestCase *testcase, Ptr< LrWpanNetDevice > device, LrWpanPhyEnumeration status)
Function called when PlmeCcaConfirm is hit.
Private Attributes
LrWpanPhyEnumeration m_status
PHY status.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
LrWpan CCA Test.
Definition at line 46 of file lr-wpan-cca-test.cc.
Constructor & Destructor Documentation
LrWpanCcaTestCase()
LrWpanCcaTestCase::LrWpanCcaTestCase ()
Definition at line 103 of file lr-wpan-cca-test.cc.
References ns3::IEEE_802_15_4_PHY_UNSPECIFIED, and m_status.
Member Function Documentation
DoRun()
void LrWpanCcaTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 160 of file lr-wpan-cca-test.cc.
References ns3::Node::AddDevice(), ns3::LrWpanNetDevice::AssignStreams(), third::channel, ns3::LrWpanNetDevice::GetCsmaCa(), ns3::LrWpanNetDevice::GetMac(), ns3::LrWpanNetDevice::GetPhy(), ns3::IEEE_802_15_4_PHY_BUSY, ns3::IEEE_802_15_4_PHY_IDLE, ns3::IEEE_802_15_4_PHY_UNSPECIFIED, ns3::McpsDataRequestParams::m_dstAddr, ns3::McpsDataRequestParams::m_dstAddrMode, ns3::McpsDataRequestParams::m_dstPanId, ns3::McpsDataRequestParams::m_msduHandle, ns3::McpsDataRequestParams::m_srcAddrMode, m_status, ns3::McpsDataRequestParams::m_txOptions, ns3::MakeBoundCallback(), NS_TEST_EXPECT_MSG_EQ, PhyRxBegin(), PhyRxDrop(), PhyRxEnd(), PhyTxBegin(), PhyTxEnd(), PlmeCcaConfirm(), ns3::LrWpanNetDevice::SetAddress(), ns3::LrWpanNetDevice::SetChannel(), ns3::LogDistancePropagationLossModel::SetPathLossExponent(), ns3::MobilityModel::SetPosition(), ns3::LogDistancePropagationLossModel::SetReference(), ns3::SHORT_ADDR, and ns3::TX_OPTION_NONE.
PhyRxBegin()
void LrWpanCcaTestCase::PhyRxBegin (LrWpanCcaTestCase * testcase, Ptr< LrWpanNetDevice > device, Ptr< const Packet > packet) static private
Function called when PhyRxBegin is hit.
Parameters
testcase The TestCase.
device The LrWpanNetDevice.
packet The packet.
Definition at line 134 of file lr-wpan-cca-test.cc.
References ns3::LrWpanNetDevice::GetMac(), ns3::Time::GetSeconds(), ns3::Now(), and ns3::Packet::Print().
Referenced by DoRun().
PhyRxDrop()
void LrWpanCcaTestCase::PhyRxDrop (LrWpanCcaTestCase * testcase, Ptr< LrWpanNetDevice > device, Ptr< const Packet > packet) static private
Function called when PhyRxDrop is hit.
Parameters
testcase The TestCase.
device The LrWpanNetDevice.
packet The packet.
Definition at line 152 of file lr-wpan-cca-test.cc.
References ns3::LrWpanNetDevice::GetMac(), ns3::Time::GetSeconds(), ns3::Now(), and ns3::Packet::Print().
Referenced by DoRun().
PhyRxEnd()
void LrWpanCcaTestCase::PhyRxEnd (LrWpanCcaTestCase * testcase, Ptr< LrWpanNetDevice > device, Ptr< const Packet > packet, double sinr) static private
Function called when PhyRxEnd is hit.
Parameters
testcase The TestCase.
device The LrWpanNetDevice.
packet The packet.
sinr The received SINR.
Definition at line 142 of file lr-wpan-cca-test.cc.
References ns3::LrWpanNetDevice::GetMac(), ns3::LrWpanNetDevice::GetPhy(), ns3::Time::GetSeconds(), ns3::Now(), and ns3::Packet::Print().
Referenced by DoRun().
PhyTxBegin()
void LrWpanCcaTestCase::PhyTxBegin (LrWpanCcaTestCase * testcase, Ptr< LrWpanNetDevice > device, Ptr< const Packet > packet) static private
Function called when PhyTxBegin is hit.
Parameters
testcase The TestCase.
device The LrWpanNetDevice.
packet The packet.
Definition at line 118 of file lr-wpan-cca-test.cc.
References ns3::LrWpanNetDevice::GetMac(), ns3::Time::GetSeconds(), ns3::Now(), and ns3::Packet::Print().
Referenced by DoRun().
PhyTxEnd()
void LrWpanCcaTestCase::PhyTxEnd (LrWpanCcaTestCase * testcase, Ptr< LrWpanNetDevice > device, Ptr< const Packet > packet) static private
Function called when PhyTxEnd is hit.
Parameters
testcase The TestCase.
device The LrWpanNetDevice.
packet The packet.
Definition at line 126 of file lr-wpan-cca-test.cc.
References ns3::LrWpanNetDevice::GetMac(), ns3::Time::GetSeconds(), ns3::Now(), and ns3::Packet::Print().
Referenced by DoRun().
PlmeCcaConfirm()
void LrWpanCcaTestCase::PlmeCcaConfirm (LrWpanCcaTestCase * testcase, Ptr< LrWpanNetDevice > device, LrWpanPhyEnumeration status) static private
Function called when PlmeCcaConfirm is hit.
Parameters
testcase The TestCase.
device The LrWpanNetDevice.
status The device status.
Definition at line 110 of file lr-wpan-cca-test.cc.
References ns3::LrWpanNetDevice::GetMac(), ns3::Time::GetSeconds(), m_status, and ns3::Now().
Referenced by DoRun().
Member Data Documentation
m_status
LrWpanPhyEnumeration LrWpanCcaTestCase::m_status private
PHY status.
Definition at line 99 of file lr-wpan-cca-test.cc.
Referenced by LrWpanCcaTestCase(), DoRun(), and PlmeCcaConfirm().
The documentation for this class was generated from the following file:
src/lr-wpan/test/lr-wpan-cca-test.cc