ns-3: ns3::lorawan::NetworkScheduler Class Reference
ns3::lorawan::NetworkScheduler Class Reference
#include "network-scheduler.h"
Public Member Functions
NetworkScheduler ()
NetworkScheduler (Ptr< NetworkStatus > status, Ptr< NetworkController > controller)
virtual ~NetworkScheduler ()
void OnReceivedPacket (Ptr< const Packet > packet)
Method called by NetworkServer to inform the Scheduler of a newly arrived uplink packet.
void OnReceiveWindowOpportunity (LoraDeviceAddress deviceAddress, int window)
Method that is scheduled after packet arrivals in order to act on receive windows 1 and 2 seconds later receptions.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Ptr< NetworkController > m_controller
TracedCallback< Ptr< const Packet > > m_receiveWindowOpened
Ptr< NetworkStatus > m_status
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 39 of file network-scheduler.h.
Constructor & Destructor Documentation
NetworkScheduler() [1/2]
ns3::lorawan::NetworkScheduler::NetworkScheduler ()
Definition at line 24 of file network-scheduler.cc.
NetworkScheduler() [2/2]
ns3::lorawan::NetworkScheduler::NetworkScheduler (Ptr< NetworkStatus > status, Ptr< NetworkController > controller)
Definition at line 28 of file network-scheduler.cc.
~NetworkScheduler()
ns3::lorawan::NetworkScheduler::~NetworkScheduler () virtual
Definition at line 35 of file network-scheduler.cc.
Member Function Documentation
GetTypeId()
TypeId ns3::lorawan::NetworkScheduler::GetTypeId (void) static
Definition at line 11 of file network-scheduler.cc.
References m_receiveWindowOpened, ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
OnReceivedPacket()
void ns3::lorawan::NetworkScheduler::OnReceivedPacket (Ptr< const Packet > packet)
Method called by NetworkServer to inform the Scheduler of a newly arrived uplink packet.
This function schedules the OnReceiveWindowOpportunity events 1 and 2 seconds later.
Definition at line 40 of file network-scheduler.cc.
References ns3::lorawan::LoraFrameHeader::GetAddress(), ns3::lorawan::LoraFrameHeader::GetFCnt(), m_status, NS_LOG_DEBUG, NS_LOG_FUNCTION, OnReceiveWindowOpportunity(), ns3::Packet::RemoveHeader(), ns3::Simulator::Schedule(), ns3::Seconds(), and ns3::lorawan::LoraFrameHeader::SetAsUplink().
OnReceiveWindowOpportunity()
void ns3::lorawan::NetworkScheduler::OnReceiveWindowOpportunity (LoraDeviceAddress deviceAddress, int window)
Method that is scheduled after packet arrivals in order to act on receive windows 1 and 2 seconds later receptions.
Definition at line 87 of file network-scheduler.cc.
References m_controller, m_status, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::Simulator::Schedule(), ns3::Seconds(), and visualizer.ipython_view::window.
Referenced by OnReceivedPacket().
Member Data Documentation
m_controller
Ptr<NetworkController> ns3::lorawan::NetworkScheduler::m_controller private
Definition at line 65 of file network-scheduler.h.
Referenced by OnReceiveWindowOpportunity().
m_receiveWindowOpened
TracedCallback<Ptr<const Packet> > ns3::lorawan::NetworkScheduler::m_receiveWindowOpened private
Definition at line 63 of file network-scheduler.h.
Referenced by GetTypeId().
m_status
Ptr<NetworkStatus> ns3::lorawan::NetworkScheduler::m_status private
Definition at line 64 of file network-scheduler.h.
Referenced by OnReceivedPacket(), and OnReceiveWindowOpportunity().
The documentation for this class was generated from the following files:
src/lorawan/model/network-scheduler.h
src/lorawan/model/network-scheduler.cc