ns-3: ns3::lorawan::LoraDeviceAddressGenerator Class Reference
ns3::lorawan::LoraDeviceAddressGenerator Class Reference
This class generates sequential LoraDeviceAddress instances.
#include "lora-device-address-generator.h"
Public Member Functions
LoraDeviceAddressGenerator (const uint8_t nwkId=0, const uint32_t nwkAddr=0)
Initialise the base NwkID and the first NwkAddr to be used by the generator.
LoraDeviceAddress GetNextAddress (void)
Get the LoraDeviceAddress that will be allocated upon a call to NextAddress.
LoraDeviceAddress NextAddress (void)
Allocate the next LoraDeviceAddress.
LoraDeviceAddress NextNetwork (void)
Get the first address from the next network.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
NwkAddr m_currentNwkAddr
The current Network Address value.
NwkID m_currentNwkId
The current Network Id value.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class generates sequential LoraDeviceAddress instances.
Definition at line 33 of file lora-device-address-generator.h.
Constructor & Destructor Documentation
LoraDeviceAddressGenerator()
ns3::lorawan::LoraDeviceAddressGenerator::LoraDeviceAddressGenerator (const uint8_t nwkId = 0, const uint32_t nwkAddr = 0)
Initialise the base NwkID and the first NwkAddr to be used by the generator.
The first call to NextAddress() or GetAddress() will return these values.
Parameters
nwkId The first network id.
nwkAddr The first address.
Definition at line 39 of file lora-device-address-generator.cc.
References m_currentNwkAddr, m_currentNwkId, NS_LOG_FUNCTION, ns3::lorawan::NwkAddr::Set(), and ns3::lorawan::NwkID::Set().
Member Function Documentation
GetNextAddress()
LoraDeviceAddress ns3::lorawan::LoraDeviceAddressGenerator::GetNextAddress (void)
Get the LoraDeviceAddress that will be allocated upon a call to NextAddress.
Does not change the internal state; is just used to peek at the next address that will be allocated upon a call to NextAddress
Returns
the LoraDeviceAddress
Definition at line 71 of file lora-device-address-generator.cc.
References ns3::lorawan::NwkID::Get(), ns3::lorawan::NwkAddr::Get(), m_currentNwkAddr, m_currentNwkId, and NS_LOG_FUNCTION_NOARGS.
Referenced by AddressTest::DoRun().
GetTypeId()
TypeId ns3::lorawan::LoraDeviceAddressGenerator::GetTypeId (void) static
Definition at line 30 of file lora-device-address-generator.cc.
References ns3::TypeId::SetParent().
NextAddress()
LoraDeviceAddress ns3::lorawan::LoraDeviceAddressGenerator::NextAddress (void)
Allocate the next LoraDeviceAddress.
This operation is a post-increment, meaning that the first address allocated will be the one that was initially configured.
This keeps the nwkId constant, only incrementing nwkAddr.
Returns
the LoraDeviceAddress address
Definition at line 60 of file lora-device-address-generator.cc.
References ns3::lorawan::NwkAddr::Get(), m_currentNwkAddr, m_currentNwkId, NS_LOG_FUNCTION_NOARGS, and ns3::lorawan::NwkAddr::Set().
Referenced by AddressTest::DoRun().
NextNetwork()
LoraDeviceAddress ns3::lorawan::LoraDeviceAddressGenerator::NextNetwork (void)
Get the first address from the next network.
This resets the address to the base address that was used for initialization.
Returns
the LoraDeviceAddress address of the next network
Definition at line 49 of file lora-device-address-generator.cc.
References ns3::lorawan::NwkID::Get(), m_currentNwkAddr, m_currentNwkId, NS_LOG_FUNCTION_NOARGS, ns3::lorawan::NwkAddr::Set(), and ns3::lorawan::NwkID::Set().
Member Data Documentation
m_currentNwkAddr
NwkAddr ns3::lorawan::LoraDeviceAddressGenerator::m_currentNwkAddr private
The current Network Address value.
Definition at line 85 of file lora-device-address-generator.h.
Referenced by LoraDeviceAddressGenerator(), GetNextAddress(), NextAddress(), and NextNetwork().
m_currentNwkId
NwkID ns3::lorawan::LoraDeviceAddressGenerator::m_currentNwkId private
The current Network Id value.
Definition at line 84 of file lora-device-address-generator.h.
Referenced by LoraDeviceAddressGenerator(), GetNextAddress(), NextAddress(), and NextNetwork().
The documentation for this class was generated from the following files:
src/lorawan/model/lora-device-address-generator.h
src/lorawan/model/lora-device-address-generator.cc