ns-3: ns3::PeriodicSenderHelper Class Reference
ns3::PeriodicSenderHelper Class Reference
This class can be used to install PeriodicSender applications on a wide range of nodes.
#include "periodic-sender-helper.h"
Public Member Functions
PeriodicSenderHelper ()
~PeriodicSenderHelper ()
ApplicationContainer Install (NodeContainer c) const
ApplicationContainer Install (Ptr< Node > node) const
void SetAttribute (std::string name, const AttributeValue &value)
void SetPeriod (Time period)
Set the period to be used by the applications created by this helper.
Private Member Functions
Ptr< Application > InstallPriv (Ptr< Node > node) const
Private Attributes
ObjectFactory m_factory
Ptr< UniformRandomVariable > m_initialDelay
Ptr< UniformRandomVariable > m_intervalProb
Time m_period
The period with which the application will be set to send.
Detailed Description
This class can be used to install PeriodicSender applications on a wide range of nodes.
Definition at line 40 of file periodic-sender-helper.h.
Constructor & Destructor Documentation
PeriodicSenderHelper()
ns3::PeriodicSenderHelper::PeriodicSenderHelper ()
Definition at line 34 of file periodic-sender-helper.cc.
References m_factory, m_initialDelay, m_intervalProb, ns3::ObjectFactory::Set(), ns3::ObjectBase::SetAttribute(), and ns3::ObjectFactory::SetTypeId().
~PeriodicSenderHelper()
ns3::PeriodicSenderHelper::~PeriodicSenderHelper ()
Definition at line 49 of file periodic-sender-helper.cc.
Member Function Documentation
Install() [1/2]
ApplicationContainer ns3::PeriodicSenderHelper::Install (NodeContainer c) const
Definition at line 66 of file periodic-sender-helper.cc.
References ns3::ApplicationContainer::Add(), ns3::NodeContainer::Begin(), ns3::NodeContainer::End(), and InstallPriv().
Install() [2/2]
ApplicationContainer ns3::PeriodicSenderHelper::Install (Ptr< Node > node) const
Definition at line 60 of file periodic-sender-helper.cc.
References InstallPriv().
InstallPriv()
Ptr< Application > ns3::PeriodicSenderHelper::InstallPriv (Ptr< Node > node) const private
Definition at line 78 of file periodic-sender-helper.cc.
References ns3::Node::AddApplication(), ns3::ObjectFactory::Create(), ns3::Days(), ns3::UniformRandomVariable::GetValue(), ns3::Hours(), m_factory, m_initialDelay, m_intervalProb, m_period, ns3::Minutes(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::Seconds().
Referenced by Install().
SetAttribute()
void ns3::PeriodicSenderHelper::SetAttribute (std::string name, const AttributeValue & value)
Definition at line 54 of file periodic-sender-helper.cc.
References m_factory, and ns3::ObjectFactory::Set().
SetPeriod()
void ns3::PeriodicSenderHelper::SetPeriod (Time period)
Set the period to be used by the applications created by this helper.
A value of Seconds (0) results in randomly generated periods according to the model contained in the TR 45.820 document.
Parameters
period The period to set
Definition at line 120 of file periodic-sender-helper.cc.
References m_period.
Member Data Documentation
m_factory
ObjectFactory ns3::PeriodicSenderHelper::m_factory private
Definition at line 66 of file periodic-sender-helper.h.
Referenced by PeriodicSenderHelper(), InstallPriv(), and SetAttribute().
m_initialDelay
Ptr<UniformRandomVariable> ns3::PeriodicSenderHelper::m_initialDelay private
Definition at line 68 of file periodic-sender-helper.h.
Referenced by PeriodicSenderHelper(), and InstallPriv().
m_intervalProb
Ptr<UniformRandomVariable> ns3::PeriodicSenderHelper::m_intervalProb private
Definition at line 70 of file periodic-sender-helper.h.
Referenced by PeriodicSenderHelper(), and InstallPriv().
m_period
Time ns3::PeriodicSenderHelper::m_period private
The period with which the application will be set to send.
Definition at line 72 of file periodic-sender-helper.h.
Referenced by InstallPriv(), and SetPeriod().
The documentation for this class was generated from the following files:
src/lorawan/helper/periodic-sender-helper.h
src/lorawan/helper/periodic-sender-helper.cc