ns-3: ns3::lorawan::OneShotSender Class Reference
ns3::lorawan::OneShotSender Class Reference
#include "one-shot-sender.h"
Public Member Functions
OneShotSender ()
OneShotSender (Time sendTime)
~OneShotSender ()
void SendPacket (void)
Send a packet using the LoraNetDevice's Send method.
void SetSendTime (Time sendTime)
Set the time at which this app will send a packet.
void StartApplication (void)
Start the application by scheduling the first SendPacket event.
void StopApplication (void)
Stop the application.
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Ptr< LorawanMac > m_mac
The MAC layer of this node.
EventId m_sendEvent
The sending event.
Time m_sendTime
The time at which to send the packet.
Additional Inherited Members
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Protected Member Functions inherited from ns3::Application
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 32 of file one-shot-sender.h.
Constructor & Destructor Documentation
OneShotSender() [1/2]
ns3::lorawan::OneShotSender::OneShotSender ()
Definition at line 46 of file one-shot-sender.cc.
References NS_LOG_FUNCTION_NOARGS.
OneShotSender() [2/2]
ns3::lorawan::OneShotSender::OneShotSender (Time sendTime)
Definition at line 51 of file one-shot-sender.cc.
References NS_LOG_FUNCTION_NOARGS.
~OneShotSender()
ns3::lorawan::OneShotSender::~OneShotSender ()
Definition at line 57 of file one-shot-sender.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
GetTypeId()
TypeId ns3::lorawan::OneShotSender::GetTypeId (void) static
Definition at line 37 of file one-shot-sender.cc.
References ns3::TypeId::SetParent().
SendPacket()
void ns3::lorawan::OneShotSender::SendPacket (void)
Send a packet using the LoraNetDevice's Send method.
Definition at line 71 of file one-shot-sender.cc.
References m_mac, and NS_LOG_FUNCTION.
Referenced by StartApplication().
SetSendTime()
void ns3::lorawan::OneShotSender::SetSendTime (Time sendTime)
Set the time at which this app will send a packet.
Definition at line 63 of file one-shot-sender.cc.
References m_sendTime, and NS_LOG_FUNCTION.
StartApplication()
void ns3::lorawan::OneShotSender::StartApplication (void) virtual
Start the application by scheduling the first SendPacket event.
Reimplemented from ns3::Application.
Definition at line 81 of file one-shot-sender.cc.
References ns3::Simulator::Cancel(), ns3::Node::GetDevice(), m_mac, ns3::Application::m_node, m_sendEvent, m_sendTime, NS_ASSERT, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), and SendPacket().
StopApplication()
void ns3::lorawan::OneShotSender::StopApplication (void) virtual
Stop the application.
Reimplemented from ns3::Application.
Definition at line 102 of file one-shot-sender.cc.
References ns3::Simulator::Cancel(), m_sendEvent, and NS_LOG_FUNCTION_NOARGS.
Member Data Documentation
m_mac
Ptr<LorawanMac> ns3::lorawan::OneShotSender::m_mac private
The MAC layer of this node.
Definition at line 75 of file one-shot-sender.h.
Referenced by SendPacket(), and StartApplication().
m_sendEvent
EventId ns3::lorawan::OneShotSender::m_sendEvent private
The sending event.
Definition at line 70 of file one-shot-sender.h.
Referenced by StartApplication(), and StopApplication().
m_sendTime
Time ns3::lorawan::OneShotSender::m_sendTime private
The time at which to send the packet.
Definition at line 65 of file one-shot-sender.h.
Referenced by SetSendTime(), and StartApplication().
The documentation for this class was generated from the following files:
src/lorawan/model/one-shot-sender.h
src/lorawan/model/one-shot-sender.cc