ns-3: ns3::MacTxMiddle Class Reference
ns3::MacTxMiddle Class Reference
Wifi Models
#include "mac-tx-middle.h"
Public Member Functions
MacTxMiddle ()
~MacTxMiddle ()
uint16_t GetNextSeqNumberByTidAndAddress (uint8_t tid, Mac48Address addr) const
Return the next sequence number for the Traffic ID and destination.
uint16_t GetNextSequenceNumberFor (const WifiMacHeader *hdr)
Return the next sequence number for the given header.
uint16_t PeekNextSequenceNumberFor (const WifiMacHeader *hdr)
Return the next sequence number for the Traffic ID and destination, but do not pick it (i.e.
Public Member Functions inherited from ns3::SimpleRefCount< MacTxMiddle >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
std::map< Mac48Address, uint16_t * > m_qosSequences
QOS sequences.
uint16_t m_sequence
current sequence number
Detailed Description
Handles sequence numbering of IEEE 802.11 data frames
Definition at line 39 of file mac-tx-middle.h.
Constructor & Destructor Documentation
MacTxMiddle()
ns3::MacTxMiddle::MacTxMiddle ()
Definition at line 32 of file mac-tx-middle.cc.
References NS_LOG_FUNCTION.
~MacTxMiddle()
ns3::MacTxMiddle::~MacTxMiddle ()
Definition at line 38 of file mac-tx-middle.cc.
References m_qosSequences, and NS_LOG_FUNCTION.
Member Function Documentation
GetNextSeqNumberByTidAndAddress()
uint16_t ns3::MacTxMiddle::GetNextSeqNumberByTidAndAddress (uint8_t tid, Mac48Address addr) const
Return the next sequence number for the Traffic ID and destination.
Parameters
tid Traffic ID
addr destination address
Returns
the next sequence number
Definition at line 114 of file mac-tx-middle.cc.
References m_qosSequences, NS_ASSERT, and NS_LOG_FUNCTION.
GetNextSequenceNumberFor()
uint16_t ns3::MacTxMiddle::GetNextSequenceNumberFor (const WifiMacHeader * hdr)
Return the next sequence number for the given header.
Parameters
hdr Wi-Fi header
Returns
the next sequence number
Definition at line 48 of file mac-tx-middle.cc.
References ns3::WifiMacHeader::GetAddr1(), ns3::WifiMacHeader::GetQosTid(), ns3::Mac48Address::IsGroup(), ns3::WifiMacHeader::IsQosData(), m_qosSequences, m_sequence, NS_ASSERT, and NS_LOG_FUNCTION.
PeekNextSequenceNumberFor()
uint16_t ns3::MacTxMiddle::PeekNextSequenceNumberFor (const WifiMacHeader * hdr)
Return the next sequence number for the Traffic ID and destination, but do not pick it (i.e.
the current sequence number remains unchanged). This functions is used for A-MPDU aggregation.
Parameters
hdr Wi-Fi header
Returns
the next sequence number
Definition at line 87 of file mac-tx-middle.cc.
References ns3::WifiMacHeader::GetAddr1(), ns3::WifiMacHeader::GetQosTid(), ns3::Mac48Address::IsGroup(), ns3::WifiMacHeader::IsQosData(), m_qosSequences, m_sequence, NS_ASSERT, and NS_LOG_FUNCTION.
Member Data Documentation
m_qosSequences
std::map<Mac48Address,uint16_t*> ns3::MacTxMiddle::m_qosSequences private
QOS sequences.
Definition at line 71 of file mac-tx-middle.h.
Referenced by ~MacTxMiddle(), GetNextSeqNumberByTidAndAddress(), GetNextSequenceNumberFor(), and PeekNextSequenceNumberFor().
m_sequence
uint16_t ns3::MacTxMiddle::m_sequence private
current sequence number
Definition at line 72 of file mac-tx-middle.h.
Referenced by GetNextSequenceNumberFor(), and PeekNextSequenceNumberFor().
The documentation for this class was generated from the following files:
src/wifi/model/mac-tx-middle.h
src/wifi/model/mac-tx-middle.cc