ns-3: ns3::FlameStack Class Reference
ns3::FlameStack Class Reference
Mesh Device » FLAME
Helper class used to install FLAME mesh stack (actually single protocol in this stack)
#include "flame-installer.h"
Public Member Functions
FlameStack ()
Construct a FlameStack helper class.
~FlameStack ()
Destroy a FlameStack helper class.
void DoDispose ()
Break any reference cycles in the installer helper.
bool InstallStack (Ptr< MeshPointDevice > mp)
Install a flame stack on the given MeshPointDevice.
void Report (const Ptr< MeshPointDevice > mp, std::ostream &)
Print flame protocol statistics.
void ResetStats (const Ptr< MeshPointDevice > mp)
Reset the statistics.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::MeshStack
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Helper class used to install FLAME mesh stack (actually single protocol in this stack)
Definition at line 34 of file flame-installer.h.
Constructor & Destructor Documentation
FlameStack()
ns3::FlameStack::FlameStack ()
Construct a FlameStack helper class.
Definition at line 39 of file flame-installer.cc.
~FlameStack()
ns3::FlameStack::~FlameStack ()
Destroy a FlameStack helper class.
Definition at line 42 of file flame-installer.cc.
Member Function Documentation
DoDispose()
void ns3::FlameStack::DoDispose () virtual
Break any reference cycles in the installer helper.
Required for ns-3 Object support.
Reimplemented from ns3::Object.
Definition at line 46 of file flame-installer.cc.
GetTypeId()
TypeId ns3::FlameStack::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 31 of file flame-installer.cc.
References ns3::TypeId::SetParent().
InstallStack()
bool ns3::FlameStack::InstallStack (Ptr< MeshPointDevice > mp) virtual
Install a flame stack on the given MeshPointDevice.
Parameters
mp The Ptr<MeshPointDevice> to use.
Returns
true if successful
Implements ns3::MeshStack.
Definition at line 50 of file flame-installer.cc.
References ns3::flame::FlameProtocol::Install().
Report()
void ns3::FlameStack::Report (const Ptr< MeshPointDevice > mp, std::ostream & os) virtual
Print flame protocol statistics.
Parameters
mp The Ptr<MeshPointDevice> to use.
os The output stream
Todo:
report flame counters
Implements ns3::MeshStack.
Definition at line 56 of file flame-installer.cc.
References NS_ASSERT, and ns3::flame::FlameProtocol::Report().
ResetStats()
void ns3::FlameStack::ResetStats (const Ptr< MeshPointDevice > mp) virtual
Reset the statistics.
Parameters
mp The Ptr<MeshPointDevice> to use.
Todo:
reset flame counters
Implements ns3::MeshStack.
Definition at line 65 of file flame-installer.cc.
References NS_ASSERT, and ns3::flame::FlameProtocol::ResetStats().
The documentation for this class was generated from the following files:
src/mesh/helper/flame/flame-installer.h
src/mesh/helper/flame/flame-installer.cc