ns-3: ns3::Icmpv6OptionLinkLayerAddress Class Reference
ns3::Icmpv6OptionLinkLayerAddress Class Reference
Internet » IPv6 classes and sub-modules » ICMPv6 protocol and associated headers.
ICMPv6 link-layer address option.
#include "icmpv6-header.h"
Public Member Functions
Icmpv6OptionLinkLayerAddress ()
Constructor.
Icmpv6OptionLinkLayerAddress (bool source)
Constructor.
Icmpv6OptionLinkLayerAddress (bool source, Address addr)
Constructor.
virtual ~Icmpv6OptionLinkLayerAddress ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
Address GetAddress () const
Get the hardware address.
virtual TypeId GetInstanceTypeId (void) const
Get the instance type ID.
virtual uint32_t GetSerializedSize () const
Get the serialized size.
virtual void Print (std::ostream &os) const
Print information.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetAddress (Address addr)
Set the hardware address.
Public Member Functions inherited from ns3::Icmpv6OptionHeader
Icmpv6OptionHeader ()
Constructor.
virtual ~Icmpv6OptionHeader ()
Destructor.
uint8_t GetLength () const
Get the length of the option in 8 bytes unit.
uint8_t GetType () const
Get the type of the option.
void SetLength (uint8_t len)
Set the length of the option.
void SetType (uint8_t type)
Set the type of the option.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the UID of this class.
Static Public Member Functions inherited from ns3::Icmpv6OptionHeader
static TypeId GetTypeId ()
Get the UID of this class.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Address m_addr
The hardware address.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
ICMPv6 link-layer address option.
Definition at line 1637 of file icmpv6-header.h.
Constructor & Destructor Documentation
Icmpv6OptionLinkLayerAddress() [1/3]
ns3::Icmpv6OptionLinkLayerAddress::Icmpv6OptionLinkLayerAddress (bool source)
Constructor.
Parameters
source source hardware address or target hardware address for the option
Definition at line 1831 of file icmpv6-header.cc.
References ns3::Icmpv6Header::ICMPV6_OPT_LINK_LAYER_SOURCE, ns3::Icmpv6Header::ICMPV6_OPT_LINK_LAYER_TARGET, NS_LOG_FUNCTION, and ns3::Icmpv6OptionHeader::SetType().
Icmpv6OptionLinkLayerAddress() [2/3]
ns3::Icmpv6OptionLinkLayerAddress::Icmpv6OptionLinkLayerAddress (bool source, Address addr)
Constructor.
Parameters
source source hardware address or target hardware address for the option
addr hardware address
Definition at line 1843 of file icmpv6-header.cc.
References ns3::Address::GetLength(), ns3::Icmpv6Header::ICMPV6_OPT_LINK_LAYER_SOURCE, ns3::Icmpv6Header::ICMPV6_OPT_LINK_LAYER_TARGET, m_addr, NS_LOG_FUNCTION, SetAddress(), ns3::Icmpv6OptionHeader::SetLength(), and ns3::Icmpv6OptionHeader::SetType().
Icmpv6OptionLinkLayerAddress() [3/3]
ns3::Icmpv6OptionLinkLayerAddress::Icmpv6OptionLinkLayerAddress ()
Constructor.
Definition at line 1837 of file icmpv6-header.cc.
References ns3::Icmpv6Header::ICMPV6_OPT_LINK_LAYER_SOURCE, NS_LOG_FUNCTION, and ns3::Icmpv6OptionHeader::SetType().
~Icmpv6OptionLinkLayerAddress()
ns3::Icmpv6OptionLinkLayerAddress::~Icmpv6OptionLinkLayerAddress () virtual
Destructor.
Definition at line 1857 of file icmpv6-header.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Deserialize()
uint32_t ns3::Icmpv6OptionLinkLayerAddress::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start start offset
Returns
length of packet
Reimplemented from ns3::Icmpv6OptionHeader.
Definition at line 1905 of file icmpv6-header.cc.
References ns3::Address::CopyFrom(), ns3::Icmpv6OptionHeader::GetLength(), GetSerializedSize(), m_addr, third::mac, NS_ASSERT, NS_LOG_FUNCTION, ns3::Buffer::Iterator::Read(), ns3::Buffer::Iterator::ReadU8(), ns3::Icmpv6OptionHeader::SetLength(), ns3::Icmpv6OptionHeader::SetType(), and visualizer.core::start().
GetAddress()
Address ns3::Icmpv6OptionLinkLayerAddress::GetAddress () const
Get the hardware address.
Returns
the hardware address
Definition at line 1862 of file icmpv6-header.cc.
References m_addr, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::HandleNA(), ns3::Icmpv6L4Protocol::HandleNS(), ns3::Icmpv6L4Protocol::HandleRedirection(), ns3::Icmpv6L4Protocol::HandleRS(), and ns3::Icmpv6L4Protocol::ReceiveLLA().
GetInstanceTypeId()
TypeId ns3::Icmpv6OptionLinkLayerAddress::GetInstanceTypeId (void) const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::Icmpv6OptionHeader.
Definition at line 1825 of file icmpv6-header.cc.
References GetTypeId(), and NS_LOG_FUNCTION.
GetSerializedSize()
uint32_t ns3::Icmpv6OptionLinkLayerAddress::GetSerializedSize () const virtual
Get the serialized size.
Returns
serialized size
Reimplemented from ns3::Icmpv6OptionHeader.
Definition at line 1880 of file icmpv6-header.cc.
References ns3::Icmpv6OptionHeader::GetLength(), and NS_LOG_FUNCTION.
Referenced by Deserialize(), and ns3::Icmpv6L4Protocol::SendRedirection().
GetTypeId()
TypeId ns3::Icmpv6OptionLinkLayerAddress::GetTypeId () static
Get the UID of this class.
Returns
UID
Definition at line 1815 of file icmpv6-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::Icmpv6OptionLinkLayerAddress::Print (std::ostream & os) const virtual
Print information.
Parameters
os output stream
Reimplemented from ns3::Icmpv6OptionHeader.
Definition at line 1874 of file icmpv6-header.cc.
References ns3::Icmpv6OptionHeader::GetLength(), ns3::Icmpv6OptionHeader::GetType(), m_addr, and NS_LOG_FUNCTION.
Serialize()
void ns3::Icmpv6OptionLinkLayerAddress::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start start offset
Reimplemented from ns3::Icmpv6OptionHeader.
Definition at line 1887 of file icmpv6-header.cc.
References ns3::Address::CopyTo(), ns3::Icmpv6OptionHeader::GetLength(), ns3::Address::GetLength(), ns3::Icmpv6OptionHeader::GetType(), m_addr, third::mac, NS_LOG_FUNCTION, visualizer.core::start(), ns3::Buffer::Iterator::Write(), and ns3::Buffer::Iterator::WriteU8().
SetAddress()
void ns3::Icmpv6OptionLinkLayerAddress::SetAddress (Address addr)
Set the hardware address.
Parameters
addr the address to set
Definition at line 1868 of file icmpv6-header.cc.
References m_addr, and NS_LOG_FUNCTION.
Referenced by Icmpv6OptionLinkLayerAddress(), and ns3::Icmpv6L4Protocol::SendRedirection().
Member Data Documentation
m_addr
Address ns3::Icmpv6OptionLinkLayerAddress::m_addr private
The hardware address.
Definition at line 1716 of file icmpv6-header.h.
Referenced by Icmpv6OptionLinkLayerAddress(), Deserialize(), GetAddress(), Print(), Serialize(), and SetAddress().
The documentation for this class was generated from the following files:
src/internet/model/icmpv6-header.h
src/internet/model/icmpv6-header.cc