ns-3: ns3::FriisSpectrumPropagationLossModel Class Reference
ns3::FriisSpectrumPropagationLossModel Class Reference
Spectrum Models
Friis spectrum propagation loss model.
#include "friis-spectrum-propagation-loss.h"
Public Member Functions
FriisSpectrumPropagationLossModel ()
~FriisSpectrumPropagationLossModel ()
double CalculateLoss (double f, double d) const
Return the propagation loss L according to a simplified version of Friis' formula in which antenna gains are unitary.
virtual Ptr< SpectrumValue > DoCalcRxPowerSpectralDensity (Ptr< const SpectrumValue > txPsd, Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const
Public Member Functions inherited from ns3::SpectrumPropagationLossModel
SpectrumPropagationLossModel ()
virtual ~SpectrumPropagationLossModel ()
Ptr< SpectrumValue > CalcRxPowerSpectralDensity (Ptr< const SpectrumValue > txPsd, Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const
This method is to be called to calculate.
void SetNext (Ptr< SpectrumPropagationLossModel > next)
Used to chain various instances of SpectrumPropagationLossModel.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::SpectrumPropagationLossModel
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::SpectrumPropagationLossModel
virtual void DoDispose ()
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Friis spectrum propagation loss model.
The propagation loss is calculated according to a simplified version of Friis' formula in which antenna gains are unitary:
where C = 3e8 m/s is the light speed in the vacuum. The intended use is to calculate Prx = Ptx * G
Definition at line 45 of file friis-spectrum-propagation-loss.h.
Constructor & Destructor Documentation
FriisSpectrumPropagationLossModel()
ns3::FriisSpectrumPropagationLossModel::FriisSpectrumPropagationLossModel ()
Definition at line 31 of file friis-spectrum-propagation-loss.cc.
~FriisSpectrumPropagationLossModel()
ns3::FriisSpectrumPropagationLossModel::~FriisSpectrumPropagationLossModel ()
Definition at line 35 of file friis-spectrum-propagation-loss.cc.
Member Function Documentation
CalculateLoss()
double ns3::FriisSpectrumPropagationLossModel::CalculateLoss (double f, double d) const
Return the propagation loss L according to a simplified version of Friis' formula in which antenna gains are unitary.
Parameters
f frequency in Hz
d distance in m
Returns
if Prx < Ptx then return Prx; else return Ptx
Definition at line 78 of file friis-spectrum-propagation-loss.cc.
References f(), and NS_ASSERT.
Referenced by DoCalcRxPowerSpectralDensity().
DoCalcRxPowerSpectralDensity()
Ptr< SpectrumValue > ns3::FriisSpectrumPropagationLossModel::DoCalcRxPowerSpectralDensity (Ptr< const SpectrumValue > txPsd, Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const virtual
Parameters
txPsd set of values Vs frequency representing the transmission power. See SpectrumChannel for details.
a sender mobility
b receiver mobility
Returns
set of values Vs frequency representing the received power in the same units used for the txPower parameter.
Implements ns3::SpectrumPropagationLossModel.
Definition at line 53 of file friis-spectrum-propagation-loss.cc.
References CalculateLoss(), ns3::SpectrumValue::ConstBandsBegin(), ns3::SpectrumValue::ConstBandsEnd(), NS_ASSERT, ns3::SpectrumValue::ValuesBegin(), and ns3::SpectrumValue::ValuesEnd().
GetTypeId()
TypeId ns3::FriisSpectrumPropagationLossModel::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 41 of file friis-spectrum-propagation-loss.cc.
References ns3::TypeId::SetParent().
Referenced by LteSecondaryCellSelectionTestCase::DoRun(), and LteAggregationThroughputScaleTestCase::GetThroughput().
The documentation for this class was generated from the following files:
src/spectrum/model/friis-spectrum-propagation-loss.h
src/spectrum/model/friis-spectrum-propagation-loss.cc