ns-3: ns3::MatrixPropagationLossModel Class Reference
ns3::MatrixPropagationLossModel Class Reference
Propagation Models
The propagation loss is fixed for each pair of nodes and doesn't depend on their actual positions.
#include "propagation-loss-model.h"
Public Member Functions
MatrixPropagationLossModel ()
virtual ~MatrixPropagationLossModel ()
void SetDefaultLoss (double defaultLoss)
Set the default propagation loss (in dB, positive) to be used, infinity if not set.
void SetLoss (Ptr< MobilityModel > a, Ptr< MobilityModel > b, double loss, bool symmetric=true)
Set loss (in dB, positive) between pair of ns-3 objects (typically, nodes).
Public Member Functions inherited from ns3::PropagationLossModel
PropagationLossModel ()
virtual ~PropagationLossModel ()
int64_t AssignStreams (int64_t stream)
If this loss model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
double CalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account all the PropagationLossModel(s) chained to the current one.
Ptr< PropagationLossModel > GetNext ()
Gets the next PropagationLossModel in the chain of loss models that act on the signal.
void SetNext (Ptr< PropagationLossModel > next)
Enables a chain of loss models to act on the signal.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::PropagationLossModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef std::pair< Ptr< MobilityModel >, Ptr< MobilityModel > > MobilityPair
Typedef: Mobility models pair.
Private Member Functions
MatrixPropagationLossModel (const MatrixPropagationLossModel &)
Copy constructor.
virtual int64_t DoAssignStreams (int64_t stream)
Subclasses must implement this; those not using random variables can return zero.
virtual double DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account only the particular PropagationLossModel.
MatrixPropagationLossModel & operator= (const MatrixPropagationLossModel &)
Copy constructor.
Private Attributes
double m_default
default loss
std::map< MobilityPair, double > m_loss
Propagation loss between pair of nodes.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The propagation loss is fixed for each pair of nodes and doesn't depend on their actual positions.
This is supposed to be used by synthetic tests. Note that by default propagation loss is assumed to be symmetric.
Definition at line 760 of file propagation-loss-model.h.
Member Typedef Documentation
MobilityPair
typedef std::pair< Ptr<MobilityModel>, Ptr<MobilityModel> > ns3::MatrixPropagationLossModel::MobilityPair private
Typedef: Mobility models pair.
Definition at line 813 of file propagation-loss-model.h.
Constructor & Destructor Documentation
MatrixPropagationLossModel() [1/2]
ns3::MatrixPropagationLossModel::MatrixPropagationLossModel ()
Definition at line 826 of file propagation-loss-model.cc.
~MatrixPropagationLossModel()
ns3::MatrixPropagationLossModel::~MatrixPropagationLossModel () virtual
Definition at line 831 of file propagation-loss-model.cc.
MatrixPropagationLossModel() [2/2]
ns3::MatrixPropagationLossModel::MatrixPropagationLossModel (const MatrixPropagationLossModel &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Member Function Documentation
DoAssignStreams()
int64_t ns3::MatrixPropagationLossModel::DoAssignStreams (int64_t stream) private virtual
Subclasses must implement this; those not using random variables can return zero.
Implements ns3::PropagationLossModel.
Definition at line 882 of file propagation-loss-model.cc.
DoCalcRxPower()
double ns3::MatrixPropagationLossModel::DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const private virtual
Returns the Rx Power taking into account only the particular PropagationLossModel.
Parameters
txPowerDbm current transmission power (in dBm)
a the mobility model of the source
b the mobility model of the destination
Returns
the reception power after adding/multiplying propagation loss (in dBm)
Implements ns3::PropagationLossModel.
Definition at line 865 of file propagation-loss-model.cc.
References m_default, and m_loss.
GetTypeId()
TypeId ns3::MatrixPropagationLossModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 812 of file propagation-loss-model.cc.
References m_default, ns3::MakeDoubleAccessor(), max, and ns3::TypeId::SetParent().
operator=()
MatrixPropagationLossModel& ns3::MatrixPropagationLossModel::operator= (const MatrixPropagationLossModel &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Returns
SetDefaultLoss()
void ns3::MatrixPropagationLossModel::SetDefaultLoss (double defaultLoss)
Set the default propagation loss (in dB, positive) to be used, infinity if not set.
Parameters
defaultLoss the default proagation loss
Definition at line 836 of file propagation-loss-model.cc.
References m_default.
Referenced by MatrixPropagationLossModelTestCase::DoRun(), experiment(), and TestInterBssConstantObssPdAlgo::RunOne().
SetLoss()
void ns3::MatrixPropagationLossModel::SetLoss (Ptr< MobilityModel > a, Ptr< MobilityModel > b, double loss, bool symmetric = true)
Set loss (in dB, positive) between pair of ns-3 objects (typically, nodes).
Parameters
a ma Source mobility model
b mb Destination mobility model
loss a -> b path loss, positive in dB
symmetric If true (default), both a->b and b->a paths will be affected
Definition at line 842 of file propagation-loss-model.cc.
References m_loss, and NS_ASSERT.
Referenced by MatrixPropagationLossModelTestCase::DoRun(), SpectrumIdealPhyTestCase::DoRun(), experiment(), and TestInterBssConstantObssPdAlgo::RunOne().
Member Data Documentation
m_default
double ns3::MatrixPropagationLossModel::m_default private
default loss
Definition at line 810 of file propagation-loss-model.h.
Referenced by DoCalcRxPower(), GetTypeId(), and SetDefaultLoss().
m_loss
std::map<MobilityPair, double> ns3::MatrixPropagationLossModel::m_loss private
Propagation loss between pair of nodes.
Definition at line 815 of file propagation-loss-model.h.
Referenced by DoCalcRxPower(), and SetLoss().
The documentation for this class was generated from the following files:
src/propagation/model/propagation-loss-model.h
src/propagation/model/propagation-loss-model.cc