ns-3: ns3::UanPdp Class Reference
ns3::UanPdp Class Reference
UAN Models
#include "uan-prop-model.h"
Public Types
typedef std::vector< Tap >::const_iterator Iterator
Convenience iterator typedef.
Public Member Functions
UanPdp ()
Create empty PDP object.
UanPdp (std::vector< double > arrivals, Time resolution)
Create PDP object from real valued arrival amplitudes.
UanPdp (std::vector< std::complex< double > > arrivals, Time resolution)
Create PDP object from vector of arrival amplitudes.
UanPdp (std::vector< Tap > taps, Time resolution)
Create PDP object from a vector of Tap objects.
~UanPdp ()
Dummy destructor, see DoDispose.
Iterator GetBegin (void) const
Get the beginning of the tap vector.
Iterator GetEnd (void) const
Get the end of the tap list (one beyond the last entry).
uint32_t GetNTaps (void) const
Get the number of taps.
Time GetResolution (void) const
Get the delay time resolution (time duration between arrivals).
const Tap & GetTap (uint32_t i) const
Get the Tap at the specified delay index.
UanPdp NormalizeToSumNc (void) const
Creates a new UanPdp normalized to its non coherent sum.
void SetNTaps (uint32_t nTaps)
Resize the tap vector.
void SetResolution (Time resolution)
Set the time duration (resolution) between arrivals.
void SetTap (std::complex< double > arrival, uint32_t index)
Set the arrival value for a tap.
std::complex< double > SumTapsC (Time begin, Time end) const
Compute the coherent sum of tap amplitudes between a start and end time.
std::complex< double > SumTapsFromMaxC (Time delay, Time duration) const
Compute the coherent sum of tap amplitudes starting after a delay from the maximum amplitude for a total duration.
double SumTapsFromMaxNc (Time delay, Time duration) const
Compute the non-coherent sum of tap amplitudes starting after a delay from the maximum amplitude for a total time duration.
double SumTapsNc (Time begin, Time end) const
Compute the non-coherent sum of tap amplitudes between a start and end time.
Static Public Member Functions
static UanPdp CreateImpulsePdp (void)
Get a unit impulse PDP at time 0.
Private Attributes
Time m_resolution
The time resolution.
std::vector< Tap > m_taps
The vector of Taps.
Friends
std::ostream & operator<< (std::ostream &os, const UanPdp &pdp)
std::istream & operator>> (std::istream &is, UanPdp &pdp)
Detailed Description
The power delay profile returned by propagation models.
Container class to describe power delay profile returned from UAN propagation models using tapped delay line model. This should model a channel impulse response as a set of equally spaced signal arrivals.
Generally, the profile should be normalized, such that the sum of all taps should equal 1. The received signal power on any interval (t1, t2) can then be found from summing the taps on the interval and multiplying by the total received power at the receiver.
Definition at line 91 of file uan-prop-model.h.
Member Typedef Documentation
Iterator
typedef std::vector<Tap>::const_iterator ns3::UanPdp::Iterator
Convenience iterator typedef.
Definition at line 97 of file uan-prop-model.h.
Constructor & Destructor Documentation
UanPdp() [1/4]
ns3::UanPdp::UanPdp ()
Create empty PDP object.
Definition at line 108 of file uan-prop-model.cc.
Referenced by NormalizeToSumNc().
UanPdp() [2/4]
ns3::UanPdp::UanPdp (std::vector< Tap > taps, Time resolution)
Create PDP object from a vector of Tap objects.
Parameters
taps Taps to include in this PDP.
resolution Resolution of PDP object.
Definition at line 113 of file uan-prop-model.cc.
UanPdp() [3/4]
ns3::UanPdp::UanPdp (std::vector< std::complex< double > > arrivals, Time resolution)
Create PDP object from vector of arrival amplitudes.
Parameters
arrivals Vector of complex amplitude arrivals.
resolution Time duration between arrivals in vector.
Definition at line 119 of file uan-prop-model.cc.
References m_resolution, m_taps, and ns3::Seconds().
UanPdp() [4/4]
ns3::UanPdp::UanPdp (std::vector< double > arrivals, Time resolution)
Create PDP object from real valued arrival amplitudes.
Parameters
arrivals Vector of real valued arrivals.
resolution Time duration between arrivals in vector.
Definition at line 131 of file uan-prop-model.cc.
References m_resolution, m_taps, and ns3::Seconds().
~UanPdp()
ns3::UanPdp::~UanPdp ()
Dummy destructor, see DoDispose.
Definition at line 143 of file uan-prop-model.cc.
References m_taps.
Member Function Documentation
CreateImpulsePdp()
UanPdp ns3::UanPdp::CreateImpulsePdp (void) static
Get a unit impulse PDP at time 0.
Returns
The unit impulse.
Definition at line 352 of file uan-prop-model.cc.
References ns3::Seconds(), SetResolution(), and SetTap().
Referenced by ns3::UanPropModelIdeal::GetPdp(), and ns3::UanPropModelThorp::GetPdp().
GetBegin()
UanPdp::Iterator ns3::UanPdp::GetBegin (void) const
Get the beginning of the tap vector.
Returns
Iterator positioned at first arrival.
Definition at line 176 of file uan-prop-model.cc.
References m_taps.
Referenced by ns3::UanPhyCalcSinrFhFsk::CalcSinrDb().
GetEnd()
UanPdp::Iterator ns3::UanPdp::GetEnd (void) const
Get the end of the tap list (one beyond the last entry).
Returns
Iterator positioned after last arrival
Definition at line 182 of file uan-prop-model.cc.
References m_taps.
Referenced by ns3::UanPhyCalcSinrFhFsk::CalcSinrDb().
GetNTaps()
uint32_t ns3::UanPdp::GetNTaps (void) const
Get the number of taps.
Returns
Number of taps in PDP.
Definition at line 188 of file uan-prop-model.cc.
References m_taps.
Referenced by GetTap(), NormalizeToSumNc(), ns3::operator<<(), SumTapsC(), SumTapsFromMaxC(), SumTapsFromMaxNc(), and SumTapsNc().
GetResolution()
Time ns3::UanPdp::GetResolution (void) const
Get the delay time resolution (time duration between arrivals).
Returns
Resolution of PDP.
Definition at line 194 of file uan-prop-model.cc.
References m_resolution.
Referenced by ns3::operator<<().
GetTap()
const Tap & ns3::UanPdp::GetTap (uint32_t i) const
Get the Tap at the specified delay index.
Parameters
i Index number of tap to return (0 based).
Returns
Tap object at index i.
Definition at line 160 of file uan-prop-model.cc.
References GetNTaps(), m_taps, and NS_ASSERT_MSG().
Referenced by ns3::UanPhyCalcSinrFhFsk::CalcSinrDb().
NormalizeToSumNc()
UanPdp ns3::UanPdp::NormalizeToSumNc (void) const
Creates a new UanPdp normalized to its non coherent sum.
See also
SumTapsNc
Returns
the new PDP
Definition at line 333 of file uan-prop-model.cc.
References UanPdp(), GetNTaps(), m_resolution, and m_taps.
SetNTaps()
void ns3::UanPdp::SetNTaps (uint32_t nTaps)
Resize the tap vector.
Parameters
nTaps Number of taps in this PDP
Definition at line 166 of file uan-prop-model.cc.
References m_taps.
SetResolution()
void ns3::UanPdp::SetResolution (Time resolution)
Set the time duration (resolution) between arrivals.
Parameters
resolution The resolution.
Definition at line 171 of file uan-prop-model.cc.
References m_resolution.
Referenced by CreateImpulsePdp().
SetTap()
void ns3::UanPdp::SetTap (std::complex< double > arrival, uint32_t index)
Set the arrival value for a tap.
The delay time is the index multiplied by the resolution. The tap vector will be expanded to accommodate the requested index.
Parameters
arrival Complex arrival value.
index Index of arrival.
Definition at line 149 of file uan-prop-model.cc.
References m_resolution, and m_taps.
Referenced by CreateImpulsePdp().
SumTapsC()
std::complex< double > ns3::UanPdp::SumTapsC (Time begin, Time end) const
Compute the coherent sum of tap amplitudes between a start and end time.
Assuming that Tap at index 0 arrives at time 0, this function sums coherently (sums amplitude of arrivals considering phase difference) all arrivals between a start and end time.
Parameters
begin Time value to begin summing arrivals.
end Time value to end summing arrivals.
Returns
Coherent sum of arrivals between two time values.
Definition at line 302 of file uan-prop-model.cc.
References GetNTaps(), ns3::Time::GetSeconds(), m_resolution, m_taps, min, NS_ASSERT_MSG(), and ns3::Seconds().
SumTapsFromMaxC()
std::complex< double > ns3::UanPdp::SumTapsFromMaxC (Time delay, Time duration) const
Compute the coherent sum of tap amplitudes starting after a delay from the maximum amplitude for a total duration.
this function sums coherently (sums amplitude of arrivals considering phase difference) all arrivals in a given duration starting the given time after the maximum amplitude arrival received
Parameters
delay Time duratation after max to begin summing arrivals.
duration Time duration to sum arrivals for.
Returns
Coherent sum of arrivals after max in given window.
Definition at line 200 of file uan-prop-model.cc.
References aloha::duration, GetNTaps(), ns3::Time::GetSeconds(), ns3::Time::IsZero(), m_resolution, m_taps, min, NS_ASSERT_MSG(), ns3::Seconds(), and visualizer.core::start().
SumTapsFromMaxNc()
double ns3::UanPdp::SumTapsFromMaxNc (Time delay, Time duration) const
Compute the non-coherent sum of tap amplitudes starting after a delay from the maximum amplitude for a total time duration.
This function sums non-coherently (sums amplitude of arrivals ignoring phase difference) all arrivals in a given duration starting the given time after the maximum amplitude arrival received.
Parameters
delay Time duratation after max to begin summing arrivals.
duration Time duration to sum arrivals for.
Returns
Non-coherent sum of arrivals after max in given window.
Definition at line 233 of file uan-prop-model.cc.
References aloha::duration, GetNTaps(), ns3::Time::GetSeconds(), ns3::Time::IsZero(), m_resolution, m_taps, min, NS_ASSERT_MSG(), ns3::Seconds(), and visualizer.core::start().
Referenced by ns3::UanPhyCalcSinrFhFsk::CalcSinrDb().
SumTapsNc()
double ns3::UanPdp::SumTapsNc (Time begin, Time end) const
Compute the non-coherent sum of tap amplitudes between a start and end time.
Assuming that Tap at index 0 arrives at time 0, this function sums non-coherently (sums amplitude of arrivals ignoring phase difference) all arrivals between a start and end time.
Parameters
begin Time value to begin summing arrivals.
end Time value to end summing arrivals.
Returns
Non-coherent sum of arrivals between two time values.
Definition at line 269 of file uan-prop-model.cc.
References GetNTaps(), ns3::Time::GetSeconds(), m_resolution, m_taps, min, NS_ASSERT_MSG(), and ns3::Seconds().
Referenced by ns3::UanPhyCalcSinrFhFsk::CalcSinrDb().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const UanPdp & pdp) friend
Writes PDP to stream as list of arrivals
Parameters
os The output stream.
pdp The PDP.
Returns
The output stream.
Definition at line 29 of file uan-prop-model.cc.
operator>>
std::istream& operator>> (std::istream & is, UanPdp & pdp) friend
Reads in list of arrivals from stream is
Parameters
is The input stream.
pdp The PDP variable to set.
Returns
The input stream.
Definition at line 44 of file uan-prop-model.cc.
Member Data Documentation
m_resolution
Time ns3::UanPdp::m_resolution private
The time resolution.
Definition at line 254 of file uan-prop-model.h.
Referenced by UanPdp(), GetResolution(), NormalizeToSumNc(), ns3::operator>>(), SetResolution(), SetTap(), SumTapsC(), SumTapsFromMaxC(), SumTapsFromMaxNc(), and SumTapsNc().
m_taps
std::vector<Tap> ns3::UanPdp::m_taps private
The vector of Taps.
Definition at line 253 of file uan-prop-model.h.
Referenced by UanPdp(), ~UanPdp(), GetBegin(), GetEnd(), GetNTaps(), GetTap(), NormalizeToSumNc(), ns3::operator<<(), ns3::operator>>(), SetNTaps(), SetTap(), SumTapsC(), SumTapsFromMaxC(), SumTapsFromMaxNc(), and SumTapsNc().
The documentation for this class was generated from the following files:
src/uan/model/uan-prop-model.h
src/uan/model/uan-prop-model.cc