ns-3: BurstErrorModelSimple Class Reference
BurstErrorModelSimple Class Reference
Network » Network module unit tests | Test suites
Public Member Functions
BurstErrorModelSimple ()
virtual ~BurstErrorModelSimple ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void DropEvent (Ptr< const Packet > p)
Register a Drop.
bool Receive (Ptr< NetDevice > nd, Ptr< const Packet > p, uint16_t protocol, const Address &addr)
Receive form a NetDevice.
Private Attributes
uint32_t m_count
The received packets counter.
uint32_t m_drops
The dropped packets counter.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
BurstErrorModel unit tests.
Definition at line 170 of file error-model-test-suite.cc.
Constructor & Destructor Documentation
BurstErrorModelSimple()
BurstErrorModelSimple::BurstErrorModelSimple ()
Definition at line 198 of file error-model-test-suite.cc.
~BurstErrorModelSimple()
BurstErrorModelSimple::~BurstErrorModelSimple () virtual
Definition at line 203 of file error-model-test-suite.cc.
Member Function Documentation
DoRun()
void BurstErrorModelSimple::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 221 of file error-model-test-suite.cc.
References ns3::BurstErrorModel::AssignStreams(), BuildSimpleTopology(), third::channel, DropEvent(), ns3::SimpleNetDevice::GetAddress(), m_count, m_drops, ns3::MakeCallback(), NS_TEST_ASSERT_MSG_EQ, Receive(), ns3::Seconds(), SendPacket(), ns3::ObjectBase::SetAttribute(), ns3::BurstErrorModel::SetRandomVariable(), ns3::SimpleNetDevice::SetReceiveCallback(), ns3::RandomVariableStream::SetStream(), and ns3::ObjectBase::TraceConnectWithoutContext().
DropEvent()
void BurstErrorModelSimple::DropEvent (Ptr< const Packet > p) private
Register a Drop.
Parameters
p The dropped packet
Definition at line 215 of file error-model-test-suite.cc.
References m_drops.
Referenced by DoRun().
Receive()
bool BurstErrorModelSimple::Receive (Ptr< NetDevice > nd, Ptr< const Packet > p, uint16_t protocol, const Address & addr) private
Receive form a NetDevice.
Parameters
nd The NetDevice.
p The received packet.
protocol The protocol received.
addr The sender address.
Returns
True on success.
Definition at line 208 of file error-model-test-suite.cc.
References m_count.
Referenced by DoRun().
Member Data Documentation
m_count
uint32_t BurstErrorModelSimple::m_count private
The received packets counter.
Definition at line 193 of file error-model-test-suite.cc.
Referenced by DoRun(), and Receive().
m_drops
uint32_t BurstErrorModelSimple::m_drops private
The dropped packets counter.
Definition at line 194 of file error-model-test-suite.cc.
Referenced by DoRun(), and DropEvent().
The documentation for this class was generated from the following file:
src/network/test/error-model-test-suite.cc