ns-3: ns3::Ipv6Interface Class Reference
ns3::Ipv6Interface Class Reference
Internet » IPv6 classes and sub-modules
The IPv6 representation of a network interface.
#include "ipv6-interface.h"
Public Member Functions
Ipv6Interface ()
Constructs an Ipv6Interface.
virtual ~Ipv6Interface ()
Destructor.
bool AddAddress (Ipv6InterfaceAddress iface)
Add an IPv6 address.
Ipv6InterfaceAddress GetAddress (uint32_t index) const
Get an address from IPv6 interface.
Ipv6InterfaceAddress GetAddressMatchingDestination (Ipv6Address dst)
Get an address which is in the same network prefix as destination.
uint16_t GetBaseReachableTime () const
Get the base reachable time.
uint8_t GetCurHopLimit () const
Get the current hop limit value.
virtual Ptr< NetDevice > GetDevice () const
Get the NetDevice.
Ipv6InterfaceAddress GetLinkLocalAddress () const
Get link-local address from IPv6 interface.
uint16_t GetMetric () const
Get the metric.
uint32_t GetNAddresses (void) const
Get number of addresses on this IPv6 interface.
Ptr< NdiscCache > GetNdiscCache () const
uint16_t GetReachableTime () const
Get the reachable time.
uint16_t GetRetransTimer () const
Get the retransmission timer.
bool IsDown () const
Is the interface DOWN ?
bool IsForwarding () const
If the interface allows forwarding packets.
bool IsSolicitedMulticastAddress (Ipv6Address address) const
Checks if the address is a Solicited Multicast address for this interface.
bool IsUp () const
Is the interface UP ?
Ipv6InterfaceAddress RemoveAddress (Ipv6Address address)
Remove the given Ipv6 address from the interface.
Ipv6InterfaceAddress RemoveAddress (uint32_t index)
Remove an address from interface.
void Send (Ptr< Packet > p, const Ipv6Header &hdr, Ipv6Address dest)
Send a packet through this interface.
void SetBaseReachableTime (uint16_t baseReachableTime)
Set the base reachable time.
void SetCurHopLimit (uint8_t curHopLimit)
Set the current hop limit.
void SetDevice (Ptr< NetDevice > device)
Set the NetDevice.
void SetDown ()
Disable this interface.
void SetForwarding (bool forward)
Set forwarding enabled or not.
void SetMetric (uint16_t metric)
Set the metric.
void SetNode (Ptr< Node > node)
Set node associated with interface.
void SetNsDadUid (Ipv6Address address, uint32_t uid)
Update NS DAD packet UID of an interface address.
void SetReachableTime (uint16_t reachableTime)
Set the reachable time.
void SetRetransTimer (uint16_t retransTimer)
Set the retransmission timer.
void SetState (Ipv6Address address, Ipv6InterfaceAddress::State_e state)
Update state of an interface address.
void SetTrafficControl (Ptr< TrafficControlLayer > tc)
Set the TrafficControlLayer.
void SetUp ()
Enable this interface.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose ()
Dispose this object.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
typedef std::list< std::pair< Ipv6InterfaceAddress, Ipv6Address > > Ipv6InterfaceAddressList
Container for the Ipv6InterfaceAddresses.
typedef std::list< std::pair< Ipv6InterfaceAddress, Ipv6Address > >::const_iterator Ipv6InterfaceAddressListCI
Const Container Iterator for the Ipv6InterfaceAddresses.
typedef std::list< std::pair< Ipv6InterfaceAddress, Ipv6Address > >::iterator Ipv6InterfaceAddressListI
Container Iterator for the Ipv6InterfaceAddresses.
Private Member Functions
Ipv6Interface (const Ipv6Interface &o)
Copy constructor.
void DoSetup ()
Initialize interface.
Ipv6Interface & operator= (const Ipv6Interface &o)
Assignment operator.
Private Attributes
Ipv6InterfaceAddressList m_addresses
The addresses assigned to this interface.
uint16_t m_baseReachableTime
Base value used for computing the random reachable time value (in millisecond).
uint8_t m_curHopLimit
Current hop limit.
Ptr< NetDevice > m_device
NetDevice associated with this interface.
bool m_forwarding
Forwarding state.
bool m_ifup
The state of this interface.
Ipv6InterfaceAddress m_linkLocalAddress
The link-local addresses assigned to this interface.
uint16_t m_metric
The metric.
Ptr< NdiscCache > m_ndCache
Neighbor cache.
Ptr< Node > m_node
Node associated with this interface.
uint16_t m_reachableTime
Reachable time (in millisecond).
uint16_t m_retransTimer
Retransmission timer (in millisecond).
Ptr< TrafficControlLayer > m_tc
TrafficControlLayer associated with this interface.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The IPv6 representation of a network interface.
By default IPv6 interfaces are created in the "down" state with IP "fe80::1" and a /64 prefix. Before becoming usable, the user must invoke SetUp on them once the final IPv6 address and mask has been set.
Definition at line 51 of file ipv6-interface.h.
Member Typedef Documentation
Ipv6InterfaceAddressList
typedef std::list<std::pair<Ipv6InterfaceAddress, Ipv6Address> > ns3::Ipv6Interface::Ipv6InterfaceAddressList private
Container for the Ipv6InterfaceAddresses.
Definition at line 302 of file ipv6-interface.h.
Ipv6InterfaceAddressListCI
typedef std::list<std::pair<Ipv6InterfaceAddress, Ipv6Address> >::const_iterator ns3::Ipv6Interface::Ipv6InterfaceAddressListCI private
Const Container Iterator for the Ipv6InterfaceAddresses.
Definition at line 312 of file ipv6-interface.h.
Ipv6InterfaceAddressListI
typedef std::list<std::pair<Ipv6InterfaceAddress, Ipv6Address> >::iterator ns3::Ipv6Interface::Ipv6InterfaceAddressListI private
Container Iterator for the Ipv6InterfaceAddresses.
Definition at line 307 of file ipv6-interface.h.
Constructor & Destructor Documentation
Ipv6Interface() [1/2]
ns3::Ipv6Interface::Ipv6Interface ()
Constructs an Ipv6Interface.
Definition at line 53 of file ipv6-interface.cc.
References NS_LOG_FUNCTION.
~Ipv6Interface()
ns3::Ipv6Interface::~Ipv6Interface () virtual
Destructor.
Definition at line 69 of file ipv6-interface.cc.
References NS_LOG_FUNCTION_NOARGS.
Ipv6Interface() [2/2]
ns3::Ipv6Interface::Ipv6Interface (const Ipv6Interface & o) private
Copy constructor.
Parameters
o object to copy
Defined and unimplemented to avoid misuse
Member Function Documentation
AddAddress()
bool ns3::Ipv6Interface::AddAddress (Ipv6InterfaceAddress iface)
Add an IPv6 address.
Parameters
iface address to add
Returns
true if address was added, false otherwise
Definition at line 221 of file ipv6-interface.cc.
References ns3::Icmpv6L4Protocol::DoDAD(), ns3::Icmpv6L4Protocol::FunctionDadTimeout(), ns3::Ipv6InterfaceAddress::GetAddress(), ns3::Object::GetObject(), ns3::Ipv6::GetProtocol(), ns3::Icmpv6L4Protocol::GetStaticProtocolNumber(), ns3::Ipv6Address::IsAny(), ns3::Ipv6Address::IsLocalhost(), m_addresses, m_device, m_node, ns3::Ipv6Address::MakeSolicitedAddress(), NS_LOG_FUNCTION_NOARGS, ns3::Simulator::Schedule(), and ns3::Seconds().
Referenced by ns3::Ipv6L3Protocol::AddAddress(), and DoSetup().
DoDispose()
void ns3::Ipv6Interface::DoDispose () protected virtual
Dispose this object.
Reimplemented from ns3::Object.
Definition at line 74 of file ipv6-interface.cc.
References ns3::Object::DoDispose(), m_device, m_ndCache, m_node, m_tc, and NS_LOG_FUNCTION_NOARGS.
DoSetup()
void ns3::Ipv6Interface::DoSetup () private
Initialize interface.
Definition at line 84 of file ipv6-interface.cc.
References AddAddress(), ns3::Mac16Address::ConvertFrom(), ns3::Mac48Address::ConvertFrom(), ns3::Mac64Address::ConvertFrom(), ns3::Mac8Address::ConvertFrom(), GetDevice(), ns3::Object::GetObject(), ns3::Ipv6::GetProtocol(), ns3::Icmpv6L4Protocol::GetStaticProtocolNumber(), ns3::Mac16Address::IsMatchingType(), ns3::Mac48Address::IsMatchingType(), ns3::Mac64Address::IsMatchingType(), ns3::Mac8Address::IsMatchingType(), m_device, m_linkLocalAddress, m_ndCache, m_node, ns3::Ipv6Address::MakeAutoconfiguredLinkLocalAddress(), NS_FATAL_ERROR, and NS_LOG_FUNCTION_NOARGS.
Referenced by SetUp().
GetAddress()
Ipv6InterfaceAddress ns3::Ipv6Interface::GetAddress (uint32_t index) const
Get an address from IPv6 interface.
Parameters
index index
Returns
Ipv6InterfaceAddress address whose index is i
Definition at line 291 of file ipv6-interface.cc.
References m_addresses, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::FunctionDadTimeout(), ns3::Ipv6L3Protocol::GetAddress(), ns3::Icmpv6L4Protocol::HandleNA(), ns3::Icmpv6L4Protocol::HandleNS(), and ns3::Ipv6L3Protocol::RemoveAutoconfiguredAddress().
GetAddressMatchingDestination()
Ipv6InterfaceAddress ns3::Ipv6Interface::GetAddressMatchingDestination (Ipv6Address dst)
Get an address which is in the same network prefix as destination.
Parameters
dst destination address
Returns
Corresponding Ipv6InterfaceAddress or assert if not found
Definition at line 370 of file ipv6-interface.cc.
References ns3::Ipv6InterfaceAddress::GetAddress(), ns3::Ipv6InterfaceAddress::GetPrefix(), ns3::Ipv6Prefix::IsMatch(), m_addresses, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::Lookup().
GetBaseReachableTime()
uint16_t ns3::Ipv6Interface::GetBaseReachableTime () const
Get the base reachable time.
Returns
base reachable time
Definition at line 486 of file ipv6-interface.cc.
References m_baseReachableTime, and NS_LOG_FUNCTION_NOARGS.
GetCurHopLimit()
uint8_t ns3::Ipv6Interface::GetCurHopLimit () const
Get the current hop limit value.
Returns
current hop limit
Definition at line 474 of file ipv6-interface.cc.
References m_curHopLimit, and NS_LOG_FUNCTION_NOARGS.
GetDevice()
Ptr< NetDevice > ns3::Ipv6Interface::GetDevice () const virtual
Get the NetDevice.
Returns
the NetDevice associated with this interface
Definition at line 159 of file ipv6-interface.cc.
References m_device, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Ipv6L3Protocol::AddAutoconfiguredAddress(), ns3::Ipv6L3Protocol::AddIpv6Interface(), DoSetup(), ns3::UdpSocketImpl::ForwardUp6(), ns3::Icmpv6L4Protocol::FunctionDadTimeout(), ns3::Ipv6L3Protocol::GetMtu(), ns3::Ipv6L3Protocol::GetNetDevice(), ns3::Icmpv6L4Protocol::HandleNA(), ns3::Icmpv6L4Protocol::HandleNS(), ns3::Icmpv6L4Protocol::HandleRA(), ns3::Icmpv6L4Protocol::HandleRedirection(), ns3::Icmpv6L4Protocol::HandleRS(), ns3::Ipv6EndPointDemux::Lookup(), ns3::Icmpv6L4Protocol::Receive(), ns3::Icmpv6L4Protocol::ReceiveLLA(), ns3::Ipv6L3Protocol::RemoveAutoconfiguredAddress(), and Send().
GetLinkLocalAddress()
Ipv6InterfaceAddress ns3::Ipv6Interface::GetLinkLocalAddress () const
Get link-local address from IPv6 interface.
Returns
link-local Ipv6InterfaceAddress, assert if not found
Definition at line 267 of file ipv6-interface.cc.
References m_linkLocalAddress, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Icmpv6L4Protocol::HandleEchoRequest(), ns3::Icmpv6L4Protocol::HandleNS(), ns3::Ipv6L3Protocol::IpForward(), and ns3::Icmpv6L4Protocol::Lookup().
GetMetric()
uint16_t ns3::Ipv6Interface::GetMetric () const
Get the metric.
Returns
the metric
Definition at line 171 of file ipv6-interface.cc.
References m_metric, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Ipv6L3Protocol::GetMetric().
GetNAddresses()
uint32_t ns3::Ipv6Interface::GetNAddresses (void) const
Get number of addresses on this IPv6 interface.
Returns
number of address
Definition at line 315 of file ipv6-interface.cc.
References m_addresses, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Icmpv6L4Protocol::FunctionDadTimeout(), ns3::Ipv6L3Protocol::GetNAddresses(), ns3::Icmpv6L4Protocol::HandleNA(), ns3::Icmpv6L4Protocol::HandleNS(), ns3::Icmpv6L4Protocol::Lookup(), and ns3::Ipv6L3Protocol::RemoveAutoconfiguredAddress().
GetNdiscCache()
Ptr< NdiscCache > ns3::Ipv6Interface::GetNdiscCache () const
Returns
NDISC cache used by this interface
Definition at line 546 of file ipv6-interface.cc.
References m_ndCache, and NS_LOG_FUNCTION.
GetReachableTime()
uint16_t ns3::Ipv6Interface::GetReachableTime () const
Get the reachable time.
Returns
reachable time
Definition at line 498 of file ipv6-interface.cc.
References m_reachableTime, and NS_LOG_FUNCTION_NOARGS.
GetRetransTimer()
uint16_t ns3::Ipv6Interface::GetRetransTimer () const
Get the retransmission timer.
Returns
retransmission timer
Definition at line 510 of file ipv6-interface.cc.
References m_retransTimer, and NS_LOG_FUNCTION_NOARGS.
GetTypeId()
TypeId ns3::Ipv6Interface::GetTypeId () static
Get the type ID.
Returns
type ID
Definition at line 44 of file ipv6-interface.cc.
References ns3::TypeId::SetParent().
IsDown()
bool ns3::Ipv6Interface::IsDown () const
Is the interface DOWN ?
Returns
true if interface is disabled, false otherwise.
Definition at line 183 of file ipv6-interface.cc.
References m_ifup, and NS_LOG_FUNCTION_NOARGS.
IsForwarding()
bool ns3::Ipv6Interface::IsForwarding () const
If the interface allows forwarding packets.
Returns
true if forwarding is enabled, false otherwise
Definition at line 209 of file ipv6-interface.cc.
References m_forwarding, and NS_LOG_FUNCTION_NOARGS.
IsSolicitedMulticastAddress()
bool ns3::Ipv6Interface::IsSolicitedMulticastAddress (Ipv6Address address) const
Checks if the address is a Solicited Multicast address for this interface.
Parameters
address the address to check.
Returns
true if it is a solicited multicast address.
Definition at line 275 of file ipv6-interface.cc.
References first::address, m_addresses, and NS_LOG_FUNCTION.
IsUp()
bool ns3::Ipv6Interface::IsUp () const
Is the interface UP ?
Returns
true if interface is enabled, false otherwise.
Definition at line 177 of file ipv6-interface.cc.
References m_ifup, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Ipv6L3Protocol::IsUp(), Send(), and ns3::Ipv6L3Protocol::SendRealOut().
operator=()
Ipv6Interface& ns3::Ipv6Interface::operator= (const Ipv6Interface & o) private
Assignment operator.
Parameters
o object to copy
Returns
the copied object
Defined and unimplemented to avoid misuse
RemoveAddress() [1/2]
Ipv6InterfaceAddress ns3::Ipv6Interface::RemoveAddress (Ipv6Address address)
Remove the given Ipv6 address from the interface.
Parameters
address The Ipv6 address to remove
Returns
The removed Ipv6 interface address
The null interface address if the interface did not contain the address or if loopback address was passed as argument
Definition at line 348 of file ipv6-interface.cc.
References first::address, m_addresses, NS_LOG_FUNCTION, and NS_LOG_WARN.
RemoveAddress() [2/2]
Ipv6InterfaceAddress ns3::Ipv6Interface::RemoveAddress (uint32_t index)
Remove an address from interface.
Parameters
index index to remove
Returns
Ipv6InterfaceAddress address whose index is index
Definition at line 321 of file ipv6-interface.cc.
References m_addresses, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
Send()
void ns3::Ipv6Interface::Send (Ptr< Packet > p, const Ipv6Header & hdr, Ipv6Address dest)
Send a packet through this interface.
Parameters
p packet to send
hdr IPv6 header
dest next hop address of packet.
Note
This method will eventually call the private SendTo method which must be implemented by subclasses.
Todo:
additional checks needed here (such as whether multicast goes to loopback)?
Definition at line 389 of file ipv6-interface.cc.
References ns3::Packet::AddHeader(), GetDevice(), ns3::Object::GetObject(), ns3::Ipv6::GetProtocol(), ns3::Icmpv6L4Protocol::GetStaticProtocolNumber(), ns3::Ipv6Address::IsMulticast(), IsUp(), m_addresses, m_device, m_ndCache, m_node, m_tc, NS_ASSERT, NS_ASSERT_MSG(), NS_LOG_FUNCTION, NS_LOG_LOGIC(), ns3::NetDevice::PACKET_HOST, and ns3::Ipv6L3Protocol::PROT_NUMBER.
Referenced by ns3::Icmpv6L4Protocol::HandleNA(), ns3::Icmpv6L4Protocol::HandleNS(), ns3::Icmpv6L4Protocol::Receive(), ns3::Icmpv6L4Protocol::ReceiveLLA(), and ns3::Ipv6L3Protocol::SendRealOut().
SetBaseReachableTime()
void ns3::Ipv6Interface::SetBaseReachableTime (uint16_t baseReachableTime)
Set the base reachable time.
Parameters
baseReachableTime the value to set
Definition at line 480 of file ipv6-interface.cc.
References m_baseReachableTime, and NS_LOG_FUNCTION.
SetCurHopLimit()
void ns3::Ipv6Interface::SetCurHopLimit (uint8_t curHopLimit)
Set the current hop limit.
Parameters
curHopLimit the value to set
Definition at line 468 of file ipv6-interface.cc.
References m_curHopLimit, and NS_LOG_FUNCTION.
SetDevice()
void ns3::Ipv6Interface::SetDevice (Ptr< NetDevice > device)
Set the NetDevice.
Parameters
device NetDevice
Definition at line 146 of file ipv6-interface.cc.
References m_device, and NS_LOG_FUNCTION.
SetDown()
void ns3::Ipv6Interface::SetDown ()
Disable this interface.
Definition at line 201 of file ipv6-interface.cc.
References ns3::NdiscCache::Flush(), m_addresses, m_ifup, m_ndCache, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Ipv6L3Protocol::SetDown().
SetForwarding()
void ns3::Ipv6Interface::SetForwarding (bool forward)
Set forwarding enabled or not.
Parameters
forward forwarding state
Definition at line 215 of file ipv6-interface.cc.
References m_forwarding, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv6L3Protocol::SetForwarding().
SetMetric()
void ns3::Ipv6Interface::SetMetric (uint16_t metric)
Set the metric.
Parameters
metric configured routing metric (cost) of this interface
Definition at line 165 of file ipv6-interface.cc.
References m_metric, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv6L3Protocol::SetMetric().
SetNode()
void ns3::Ipv6Interface::SetNode (Ptr< Node > node)
Set node associated with interface.
Parameters
node node
Definition at line 140 of file ipv6-interface.cc.
References m_node, and NS_LOG_FUNCTION.
SetNsDadUid()
void ns3::Ipv6Interface::SetNsDadUid (Ipv6Address address, uint32_t uid)
Update NS DAD packet UID of an interface address.
Parameters
address IPv6 address
uid packet UID
Definition at line 531 of file ipv6-interface.cc.
References first::address, m_addresses, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::Receive().
SetReachableTime()
void ns3::Ipv6Interface::SetReachableTime (uint16_t reachableTime)
Set the reachable time.
Parameters
reachableTime value to set
Definition at line 492 of file ipv6-interface.cc.
References m_reachableTime, and NS_LOG_FUNCTION.
SetRetransTimer()
void ns3::Ipv6Interface::SetRetransTimer (uint16_t retransTimer)
Set the retransmission timer.
Parameters
retransTimer value to set
Definition at line 504 of file ipv6-interface.cc.
References m_retransTimer, and NS_LOG_FUNCTION.
SetState()
void ns3::Ipv6Interface::SetState (Ipv6Address address, Ipv6InterfaceAddress::State_e state)
Update state of an interface address.
Parameters
address IPv6 address
state new state
Definition at line 516 of file ipv6-interface.cc.
References first::address, m_addresses, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::FunctionDadTimeout(), and ns3::Icmpv6L4Protocol::HandleNA().
SetTrafficControl()
void ns3::Ipv6Interface::SetTrafficControl (Ptr< TrafficControlLayer > tc)
Set the TrafficControlLayer.
Parameters
tc TrafficControlLayer object
Definition at line 153 of file ipv6-interface.cc.
References m_tc, and NS_LOG_FUNCTION.
SetUp()
void ns3::Ipv6Interface::SetUp ()
Enable this interface.
Definition at line 189 of file ipv6-interface.cc.
References DoSetup(), m_ifup, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Ipv6L3Protocol::SetUp().
Member Data Documentation
m_addresses
Ipv6InterfaceAddressList ns3::Ipv6Interface::m_addresses private
The addresses assigned to this interface.
Definition at line 322 of file ipv6-interface.h.
Referenced by AddAddress(), GetAddress(), GetAddressMatchingDestination(), GetNAddresses(), IsSolicitedMulticastAddress(), RemoveAddress(), Send(), SetDown(), SetNsDadUid(), and SetState().
m_baseReachableTime
uint16_t ns3::Ipv6Interface::m_baseReachableTime private
Base value used for computing the random reachable time value (in millisecond).
Definition at line 372 of file ipv6-interface.h.
Referenced by GetBaseReachableTime(), and SetBaseReachableTime().
m_curHopLimit
uint8_t ns3::Ipv6Interface::m_curHopLimit private
Current hop limit.
Definition at line 367 of file ipv6-interface.h.
Referenced by GetCurHopLimit(), and SetCurHopLimit().
m_device
Ptr<NetDevice> ns3::Ipv6Interface::m_device private
NetDevice associated with this interface.
Definition at line 352 of file ipv6-interface.h.
Referenced by AddAddress(), DoDispose(), DoSetup(), GetDevice(), Send(), and SetDevice().
m_forwarding
bool ns3::Ipv6Interface::m_forwarding private
Forwarding state.
Definition at line 337 of file ipv6-interface.h.
Referenced by IsForwarding(), and SetForwarding().
m_ifup
bool ns3::Ipv6Interface::m_ifup private
The state of this interface.
Definition at line 332 of file ipv6-interface.h.
Referenced by IsDown(), IsUp(), SetDown(), and SetUp().
m_linkLocalAddress
Ipv6InterfaceAddress ns3::Ipv6Interface::m_linkLocalAddress private
The link-local addresses assigned to this interface.
Definition at line 327 of file ipv6-interface.h.
Referenced by DoSetup(), and GetLinkLocalAddress().
m_metric
uint16_t ns3::Ipv6Interface::m_metric private
The metric.
Definition at line 342 of file ipv6-interface.h.
Referenced by GetMetric(), and SetMetric().
m_ndCache
Ptr<NdiscCache> ns3::Ipv6Interface::m_ndCache private
Neighbor cache.
Definition at line 362 of file ipv6-interface.h.
Referenced by DoDispose(), DoSetup(), GetNdiscCache(), Send(), and SetDown().
m_node
Ptr<Node> ns3::Ipv6Interface::m_node private
Node associated with this interface.
Definition at line 347 of file ipv6-interface.h.
Referenced by AddAddress(), DoDispose(), DoSetup(), Send(), and SetNode().
m_reachableTime
uint16_t ns3::Ipv6Interface::m_reachableTime private
Reachable time (in millisecond).
The time a neighbor is considered reachable after receiving a reachability confirmation.
Definition at line 378 of file ipv6-interface.h.
Referenced by GetReachableTime(), and SetReachableTime().
m_retransTimer
uint16_t ns3::Ipv6Interface::m_retransTimer private
Retransmission timer (in millisecond).
Time between retransmission of NS.
Definition at line 384 of file ipv6-interface.h.
Referenced by GetRetransTimer(), and SetRetransTimer().
m_tc
Ptr<TrafficControlLayer> ns3::Ipv6Interface::m_tc private
TrafficControlLayer associated with this interface.
Definition at line 357 of file ipv6-interface.h.
Referenced by DoDispose(), Send(), and SetTrafficControl().
The documentation for this class was generated from the following files:
src/internet/model/ipv6-interface.h
src/internet/model/ipv6-interface.cc