ns-3: ns3::EpcEnbS1SapUser Class Reference
ns3::EpcEnbS1SapUser Class Reference abstract
This class implements the Service Access Point (SAP) between the LteEnbRrc and the EpcEnbApplication.
#include "epc-enb-s1-sap.h"
Classes
struct DataRadioBearerSetupRequestParameters
Parameters passed to DataRadioBearerSetupRequest ()
struct InitialContextSetupRequestParameters
Parameters passed to InitialContextSetupRequest ()
struct PathSwitchRequestAcknowledgeParameters
PathSwitchRequestAcknowledgeParameters structure.
Public Member Functions
virtual ~EpcEnbS1SapUser ()
virtual void DataRadioBearerSetupRequest (DataRadioBearerSetupRequestParameters params)=0
request the setup of a DataRadioBearer
virtual void InitialContextSetupRequest (InitialContextSetupRequestParameters params)=0
Initial context setup request.
virtual void PathSwitchRequestAcknowledge (PathSwitchRequestAcknowledgeParameters params)=0
request a path switch acknowledge
Detailed Description
This class implements the Service Access Point (SAP) between the LteEnbRrc and the EpcEnbApplication.
In particular, this class implements the User part of the SAP, i.e., the methods exported by the LteEnbRrc and called by the EpcEnbApplication.
Definition at line 103 of file epc-enb-s1-sap.h.
Constructor & Destructor Documentation
~EpcEnbS1SapUser()
ns3::EpcEnbS1SapUser::~EpcEnbS1SapUser () virtual
Definition at line 29 of file epc-enb-s1-sap.cc.
Member Function Documentation
DataRadioBearerSetupRequest()
virtual void ns3::EpcEnbS1SapUser::DataRadioBearerSetupRequest (DataRadioBearerSetupRequestParameters params) pure virtual
request the setup of a DataRadioBearer
Parameters
params
Implemented in ns3::MemberEpcEnbS1SapUser< C >.
Referenced by ns3::EpcEnbApplication::DoInitialContextSetupRequest().
InitialContextSetupRequest()
virtual void ns3::EpcEnbS1SapUser::InitialContextSetupRequest (InitialContextSetupRequestParameters params) pure virtual
Initial context setup request.
Parameters
params
Implemented in ns3::MemberEpcEnbS1SapUser< C >.
Referenced by ns3::EpcEnbApplication::DoInitialContextSetupRequest().
PathSwitchRequestAcknowledge()
virtual void ns3::EpcEnbS1SapUser::PathSwitchRequestAcknowledge (PathSwitchRequestAcknowledgeParameters params) pure virtual
request a path switch acknowledge
Parameters
params
Implemented in ns3::MemberEpcEnbS1SapUser< C >.
Referenced by ns3::EpcEnbApplication::DoPathSwitchRequestAcknowledge().
The documentation for this class was generated from the following files:
src/lte/model/epc-enb-s1-sap.h
src/lte/model/epc-enb-s1-sap.cc