ns-3: ns3::ConnectionManager Class Reference
ns3::ConnectionManager Class Reference
WiMAX Models
#include "connection-manager.h"
Public Member Functions
ConnectionManager (void)
~ConnectionManager (void)
void AddConnection (Ptr< WimaxConnection > connection, Cid::Type type)
add a connection to the list of managed connections
void AllocateManagementConnections (SSRecord *ssRecord, RngRsp *rngrsp)
allocates the management connection for an ss record.
Ptr< WimaxConnection > CreateConnection (Cid::Type type)
create a connection of type type
void DoDispose (void)
Destructor implementation.
Ptr< WimaxConnection > GetConnection (Cid cid)
std::vector< Ptr< WimaxConnection > > GetConnections (Cid::Type type) const
uint32_t GetNPackets (Cid::Type type, ServiceFlow::SchedulingType schedulingType) const
get number of packets
bool HasPackets (void) const
void SetCidFactory (CidFactory *cidFactory)
Set CID factory.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
std::vector< Ptr< WimaxConnection > > m_basicConnections
basic connections
CidFactory * m_cidFactory
the factory
std::vector< Ptr< WimaxConnection > > m_multicastConnections
multicast connections
std::vector< Ptr< WimaxConnection > > m_primaryConnections
primary connections
std::vector< Ptr< WimaxConnection > > m_transportConnections
transport connections
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The same connection manager class serves both for BS and SS though some functions are exclusive to only one of them.
Definition at line 44 of file connection-manager.h.
Constructor & Destructor Documentation
ConnectionManager()
ns3::ConnectionManager::ConnectionManager (void)
Definition at line 48 of file connection-manager.cc.
~ConnectionManager()
ns3::ConnectionManager::~ConnectionManager (void)
Definition at line 58 of file connection-manager.cc.
Member Function Documentation
AddConnection()
void ns3::ConnectionManager::AddConnection (Ptr< WimaxConnection > connection, Cid::Type type)
add a connection to the list of managed connections
Parameters
connection the connection to add
type the type of connection to add
Definition at line 105 of file connection-manager.cc.
References ns3::Cid::BASIC, m_basicConnections, m_multicastConnections, m_primaryConnections, m_transportConnections, ns3::Cid::MULTICAST, NS_FATAL_ERROR, ns3::Cid::PRIMARY, and ns3::Cid::TRANSPORT.
Referenced by CreateConnection().
AllocateManagementConnections()
void ns3::ConnectionManager::AllocateManagementConnections (SSRecord * ssRecord, RngRsp * rngrsp)
allocates the management connection for an ss record.
This method is only used by BS
Parameters
ssRecord the ss record to which the management connection will be allocated
rngrsp the ranging response message
Definition at line 69 of file connection-manager.cc.
References ns3::Cid::BASIC, CreateConnection(), ns3::Cid::PRIMARY, ns3::RngRsp::SetBasicCid(), ns3::SSRecord::SetBasicCid(), ns3::RngRsp::SetPrimaryCid(), and ns3::SSRecord::SetPrimaryCid().
CreateConnection()
Ptr< WimaxConnection > ns3::ConnectionManager::CreateConnection (Cid::Type type)
create a connection of type type
Parameters
type type of the connection to create
Returns
a smart pointer to the created WimaxConnection
Definition at line 82 of file connection-manager.cc.
References AddConnection(), ns3::CidFactory::Allocate(), ns3::CidFactory::AllocateTransportOrSecondary(), ns3::Cid::BASIC, m_cidFactory, ns3::Cid::MULTICAST, NS_FATAL_ERROR, ns3::Cid::PRIMARY, and ns3::Cid::TRANSPORT.
Referenced by AllocateManagementConnections().
DoDispose()
void ns3::ConnectionManager::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 54 of file connection-manager.cc.
GetConnection()
Ptr< WimaxConnection > ns3::ConnectionManager::GetConnection (Cid cid)
Parameters
cid the connection identifier
Returns
the connection corresponding to cid
Definition at line 128 of file connection-manager.cc.
References m_basicConnections, m_primaryConnections, and m_transportConnections.
GetConnections()
std::vector< Ptr< WimaxConnection > > ns3::ConnectionManager::GetConnections (Cid::Type type) const
Parameters
type the type of connection to add
Returns
a vector of all connections matching the input type
Definition at line 160 of file connection-manager.cc.
References ns3::Cid::BASIC, m_basicConnections, m_primaryConnections, m_transportConnections, NS_FATAL_ERROR, ns3::Cid::PRIMARY, and ns3::Cid::TRANSPORT.
GetNPackets()
uint32_t ns3::ConnectionManager::GetNPackets (Cid::Type type, ServiceFlow::SchedulingType schedulingType) const
get number of packets
Parameters
type the type of connection to add
schedulingType the scheduling type
Returns
number of packets
Definition at line 184 of file connection-manager.cc.
References ns3::Cid::BASIC, m_basicConnections, m_primaryConnections, m_transportConnections, NS_FATAL_ERROR, ns3::Cid::PRIMARY, ns3::ServiceFlow::SF_TYPE_ALL, and ns3::Cid::TRANSPORT.
GetTypeId()
TypeId ns3::ConnectionManager::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 40 of file connection-manager.cc.
References ns3::TypeId::SetParent().
HasPackets()
bool ns3::ConnectionManager::HasPackets (void) const
Returns
true if one of the managed connection has at least one packet to send, false otherwise
Definition at line 229 of file connection-manager.cc.
References m_basicConnections, m_primaryConnections, and m_transportConnections.
SetCidFactory()
void ns3::ConnectionManager::SetCidFactory (CidFactory * cidFactory)
Set CID factory.
Parameters
cidFactory the CID factory
Definition at line 63 of file connection-manager.cc.
References m_cidFactory.
Member Data Documentation
m_basicConnections
std::vector<Ptr<WimaxConnection> > ns3::ConnectionManager::m_basicConnections private
basic connections
Definition at line 100 of file connection-manager.h.
Referenced by AddConnection(), GetConnection(), GetConnections(), GetNPackets(), and HasPackets().
m_cidFactory
CidFactory* ns3::ConnectionManager::m_cidFactory private
the factory
Definition at line 105 of file connection-manager.h.
Referenced by CreateConnection(), and SetCidFactory().
m_multicastConnections
std::vector<Ptr<WimaxConnection> > ns3::ConnectionManager::m_multicastConnections private
multicast connections
Definition at line 103 of file connection-manager.h.
Referenced by AddConnection().
m_primaryConnections
std::vector<Ptr<WimaxConnection> > ns3::ConnectionManager::m_primaryConnections private
primary connections
Definition at line 101 of file connection-manager.h.
Referenced by AddConnection(), GetConnection(), GetConnections(), GetNPackets(), and HasPackets().
m_transportConnections
std::vector<Ptr<WimaxConnection> > ns3::ConnectionManager::m_transportConnections private
transport connections
Definition at line 102 of file connection-manager.h.
Referenced by AddConnection(), GetConnection(), GetConnections(), GetNPackets(), and HasPackets().
The documentation for this class was generated from the following files:
src/wimax/model/connection-manager.h
src/wimax/model/connection-manager.cc