ns-3: ns3::EnergySourceHelper Class Reference
ns3::EnergySourceHelper Class Reference abstract
Energy Models
Creates EnergySource objects.
#include "energy-model-helper.h"
Public Member Functions
virtual ~EnergySourceHelper ()
EnergySourceContainer Install (NodeContainer c) const
EnergySourceContainer Install (Ptr< Node > node) const
EnergySourceContainer Install (std::string nodeName) const
EnergySourceContainer InstallAll (void) const
This function installs an EnergySource on all nodes in simulation.
virtual void Set (std::string name, const AttributeValue &v)=0
Private Member Functions
virtual Ptr< EnergySource > DoInstall (Ptr< Node > node) const =0
Detailed Description
Creates EnergySource objects.
This class creates and installs an energy source onto network nodes. Multiple sources can exist on a network node.
Definition at line 45 of file energy-model-helper.h.
Constructor & Destructor Documentation
~EnergySourceHelper()
ns3::EnergySourceHelper::~EnergySourceHelper () virtual
Definition at line 30 of file energy-model-helper.cc.
Member Function Documentation
DoInstall()
virtual Ptr<EnergySource> ns3::EnergySourceHelper::DoInstall (Ptr< Node > node) const private pure virtual
Parameters
node Pointer to node where the energy source is to be installed.
Returns
Pointer to the created EnergySource.
Child classes of EnergySourceHelper only have to implement this function, to create and aggregate an EnergySource object onto a single node. Rest of the installation process (eg. installing EnergySource on set of nodes) is implemented in the EnergySourceHelper base class.
Implemented in ns3::RvBatteryModelHelper, ns3::LiIonEnergySourceHelper, and ns3::BasicEnergySourceHelper.
Referenced by Install().
Install() [1/3]
EnergySourceContainer ns3::EnergySourceHelper::Install (NodeContainer c) const
Parameters
c List of nodes where EnergySource will be installed.
Returns
An EnergySourceContainer which contains all the EnergySources.
This function installs an EnergySource onto a list of nodes.
Definition at line 41 of file energy-model-helper.cc.
References ns3::EnergySourceContainer::Add(), ns3::NodeContainer::Begin(), ns3::ObjectFactory::Create(), DoInstall(), ns3::NodeContainer::End(), and ns3::ObjectFactory::SetTypeId().
Install() [2/3]
EnergySourceContainer ns3::EnergySourceHelper::Install (Ptr< Node > node) const
Parameters
node Pointer to the node where EnergySource will be installed.
Returns
An EnergySourceContainer which contains all the EnergySources.
This function installs an EnergySource onto a node.
Definition at line 35 of file energy-model-helper.cc.
Referenced by BatteryLifetimeTest::ConstantLoadTest(), BasicEnergyDepletionTest::DepletionTestCase(), AcousticModemEnergyTestCase::DoRun(), AcousticModemEnergyDepletionTestCase::DoRun(), Install(), InstallAll(), UanExperiment::SetupEnergy(), and BatteryLifetimeTest::VariableLoadTest().
Install() [3/3]
EnergySourceContainer ns3::EnergySourceHelper::Install (std::string nodeName) const
Parameters
nodeName Name of node where EnergySource will be installed.
Returns
An EnergySourceContainer which contains all the EnergySources.
This function installs an EnergySource onto a node.
Definition at line 71 of file energy-model-helper.cc.
References Install().
InstallAll()
EnergySourceContainer ns3::EnergySourceHelper::InstallAll (void) const
This function installs an EnergySource on all nodes in simulation.
Returns
An EnergySourceContainer which contains all the EnergySources.
Definition at line 78 of file energy-model-helper.cc.
References ns3::NodeContainer::GetGlobal(), and Install().
Set()
virtual void ns3::EnergySourceHelper::Set (std::string name, const AttributeValue & v) pure virtual
Parameters
name Name of attribute to set.
v Value of the attribute.
Sets one of the attributes of underlying EnergySource.
Implemented in ns3::RvBatteryModelHelper, ns3::LiIonEnergySourceHelper, and ns3::BasicEnergySourceHelper.
The documentation for this class was generated from the following files:
src/energy/helper/energy-model-helper.h
src/energy/helper/energy-model-helper.cc