ns-3: ns3::ThreeGppUmaPropagationLossModel Class Reference
ns3::ThreeGppUmaPropagationLossModel Class Reference
Propagation Models
Implements the pathloss model defined in 3GPP TR 38.901, Table 7.4.1-1 for the UMa scenario.
#include "three-gpp-propagation-loss-model.h"
Public Member Functions
ThreeGppUmaPropagationLossModel ()
Constructor.
ThreeGppUmaPropagationLossModel (const ThreeGppUmaPropagationLossModel &)=delete
Copy constructor.
virtual ~ThreeGppUmaPropagationLossModel () override
Destructor.
ThreeGppUmaPropagationLossModel & operator= (const ThreeGppUmaPropagationLossModel &)=delete
Copy constructor.
Public Member Functions inherited from ns3::ThreeGppPropagationLossModel
ThreeGppPropagationLossModel ()
Constructor.
ThreeGppPropagationLossModel (const ThreeGppPropagationLossModel &)=delete
Copy constructor.
virtual ~ThreeGppPropagationLossModel () override
Destructor.
Ptr< ChannelConditionModel > GetChannelConditionModel (void) const
Returns the associated channel condition model.
double GetFrequency (void) const
Return the current central frequency.
ThreeGppPropagationLossModel & operator= (const ThreeGppPropagationLossModel &)=delete
Copy constructor.
void SetChannelConditionModel (Ptr< ChannelConditionModel > model)
Set the channel condition model used to determine the channel state (e.g., the LOS/NLOS condition)
void SetFrequency (double f)
Set the central frequency of the model.
Public Member Functions inherited from ns3::PropagationLossModel
PropagationLossModel ()
virtual ~PropagationLossModel ()
int64_t AssignStreams (int64_t stream)
If this loss model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
double CalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account all the PropagationLossModel(s) chained to the current one.
Ptr< PropagationLossModel > GetNext ()
Gets the next PropagationLossModel in the chain of loss models that act on the signal.
void SetNext (Ptr< PropagationLossModel > next)
Enables a chain of loss models to act on the signal.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ThreeGppPropagationLossModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::PropagationLossModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual int64_t DoAssignStreams (int64_t stream) override
If this model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
double GetBpDistance (double hUt, double hBs, double distance2D) const
Computes the breakpoint distance.
double GetLossLos (double distance2D, double distance3D, double hUt, double hBs) const override
Computes the pathloss between a and b considering that the line of sight is not obstructed.
double GetLossNlos (double distance2D, double distance3D, double hUt, double hBs) const override
Computes the pathloss between a and b considering that the line of sight is obstructed.
virtual double GetShadowingCorrelationDistance (ChannelCondition::LosConditionValue cond) const override
Returns the shadow fading correlation distance.
virtual double GetShadowingStd (Ptr< MobilityModel > a, Ptr< MobilityModel > b, ChannelCondition::LosConditionValue cond) const override
Returns the shadow fading standard deviation.
Private Attributes
Ptr< UniformRandomVariable > m_uniformVar
a uniform random variable used for the computation of the breakpoint distance
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Static Protected Member Functions inherited from ns3::ThreeGppPropagationLossModel
static double Calculate2dDistance (Vector a, Vector b)
Computes the 2D distance between two 3D vectors.
Protected Attributes inherited from ns3::ThreeGppPropagationLossModel
Ptr< ChannelConditionModel > m_channelConditionModel
pointer to the channel condition model
double m_frequency
operating frequency in Hz
Ptr< NormalRandomVariable > m_normRandomVariable
normal random variable
bool m_shadowingEnabled
enable/disable shadowing
std::unordered_map< uint32_t, ShadowingMapItem > m_shadowingMap
map to store the shadowing values
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implements the pathloss model defined in 3GPP TR 38.901, Table 7.4.1-1 for the UMa scenario.
Definition at line 334 of file three-gpp-propagation-loss-model.h.
Constructor & Destructor Documentation
ThreeGppUmaPropagationLossModel() [1/2]
ns3::ThreeGppUmaPropagationLossModel::ThreeGppUmaPropagationLossModel ()
Constructor.
Definition at line 484 of file three-gpp-propagation-loss-model.cc.
References ns3::ThreeGppPropagationLossModel::m_channelConditionModel, m_uniformVar, and NS_LOG_FUNCTION.
~ThreeGppUmaPropagationLossModel()
ns3::ThreeGppUmaPropagationLossModel::~ThreeGppUmaPropagationLossModel () override virtual
Destructor.
Definition at line 494 of file three-gpp-propagation-loss-model.cc.
References NS_LOG_FUNCTION.
ThreeGppUmaPropagationLossModel() [2/2]
ns3::ThreeGppUmaPropagationLossModel::ThreeGppUmaPropagationLossModel (const ThreeGppUmaPropagationLossModel &) delete
Copy constructor.
Defined and unimplemented to avoid misuse
Member Function Documentation
DoAssignStreams()
int64_t ns3::ThreeGppUmaPropagationLossModel::DoAssignStreams (int64_t stream) override private virtual
If this model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream
Returns
the number of stream indices assigned by this model
Reimplemented from ns3::ThreeGppPropagationLossModel.
Definition at line 673 of file three-gpp-propagation-loss-model.cc.
References ns3::ThreeGppPropagationLossModel::m_normRandomVariable, m_uniformVar, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
GetBpDistance()
double ns3::ThreeGppUmaPropagationLossModel::GetBpDistance (double hUt, double hBs, double distance2D) const private
Computes the breakpoint distance.
Parameters
hUt height of the UT in meters
hBs height of the BS in meters
distance2D distance between the two nodes in meters
Returns
the breakpoint distance in meters
Definition at line 500 of file three-gpp-propagation-loss-model.cc.
References ns3::UniformRandomVariable::GetInteger(), ns3::UniformRandomVariable::GetValue(), ns3::M_C, ns3::ThreeGppPropagationLossModel::m_frequency, m_uniformVar, and NS_LOG_FUNCTION.
Referenced by GetLossLos().
GetLossLos()
double ns3::ThreeGppUmaPropagationLossModel::GetLossLos (double distance2D, double distance3D, double hUt, double hBs) const override private virtual
Computes the pathloss between a and b considering that the line of sight is not obstructed.
Parameters
distance2D the 2D distance between tx and rx in meters
distance3D the 3D distance between tx and rx in meters
hUt the height of the UT in meters
hBs the height of the BS in meters
Returns
pathloss value in dB
Implements ns3::ThreeGppPropagationLossModel.
Definition at line 538 of file three-gpp-propagation-loss-model.cc.
References GetBpDistance(), ns3::ThreeGppPropagationLossModel::m_frequency, NS_LOG_DEBUG, NS_LOG_FUNCTION, and NS_LOG_WARN.
Referenced by GetLossNlos().
GetLossNlos()
double ns3::ThreeGppUmaPropagationLossModel::GetLossNlos (double distance2D, double distance3D, double hUt, double hBs) const override private virtual
Computes the pathloss between a and b considering that the line of sight is obstructed.
Parameters
distance2D the 2D distance between tx and rx in meters
distance3D the 3D distance between tx and rx in meters
hUt the height of the UT in meters
hBs the height of the BS in meters
Returns
pathloss value in dB
Implements ns3::ThreeGppPropagationLossModel.
Definition at line 589 of file three-gpp-propagation-loss-model.cc.
References GetLossLos(), ns3::ThreeGppPropagationLossModel::m_frequency, max, NS_LOG_DEBUG, NS_LOG_FUNCTION, and NS_LOG_WARN.
GetShadowingCorrelationDistance()
double ns3::ThreeGppUmaPropagationLossModel::GetShadowingCorrelationDistance (ChannelCondition::LosConditionValue cond) const override private virtual
Returns the shadow fading correlation distance.
Parameters
cond the LOS/NLOS channel condition
Returns
shadowing correlation distance in meters
Implements ns3::ThreeGppPropagationLossModel.
Definition at line 650 of file three-gpp-propagation-loss-model.cc.
References NS_FATAL_ERROR, and NS_LOG_FUNCTION.
GetShadowingStd()
double ns3::ThreeGppUmaPropagationLossModel::GetShadowingStd (Ptr< MobilityModel > a, Ptr< MobilityModel > b, ChannelCondition::LosConditionValue cond) const override private virtual
Returns the shadow fading standard deviation.
Parameters
a tx mobility model
b rx mobility model
cond the LOS/NLOS channel condition
Returns
shadowing std in dB
Implements ns3::ThreeGppPropagationLossModel.
Definition at line 626 of file three-gpp-propagation-loss-model.cc.
References NS_FATAL_ERROR, NS_LOG_FUNCTION, and NS_UNUSED.
GetTypeId()
TypeId ns3::ThreeGppUmaPropagationLossModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 474 of file three-gpp-propagation-loss-model.cc.
References ns3::TypeId::SetParent().
operator=()
ThreeGppUmaPropagationLossModel& ns3::ThreeGppUmaPropagationLossModel::operator= (const ThreeGppUmaPropagationLossModel &) delete
Copy constructor.
Defined and unimplemented to avoid misuse
Returns
the ThreeGppUmaPropagationLossModel instance
Member Data Documentation
m_uniformVar
Ptr<UniformRandomVariable> ns3::ThreeGppUmaPropagationLossModel::m_uniformVar private
a uniform random variable used for the computation of the breakpoint distance
Definition at line 427 of file three-gpp-propagation-loss-model.h.
Referenced by ThreeGppUmaPropagationLossModel(), DoAssignStreams(), and GetBpDistance().
The documentation for this class was generated from the following files:
src/propagation/model/three-gpp-propagation-loss-model.h
src/propagation/model/three-gpp-propagation-loss-model.cc