ns-3: ns3::BoxValue Class Reference
ns3::BoxValue Class Reference
#include "box.h"
Public Member Functions
BoxValue ()
BoxValue (const Box &value)
virtual Ptr< AttributeValue > Copy (void) const
virtual bool DeserializeFromString (std::string value, Ptr< const AttributeChecker > checker)
Box Get (void) const
template<typename T >
bool GetAccessor (T &value) const
virtual std::string SerializeToString (Ptr< const AttributeChecker > checker) const
void Set (const Box &value)
Public Member Functions inherited from ns3::AttributeValue
AttributeValue ()
virtual ~AttributeValue ()
Public Member Functions inherited from ns3::SimpleRefCount< AttributeValue >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
Box m_value
Detailed Description
Definition at line 126 of file box.h.
Constructor & Destructor Documentation
BoxValue() [1/2]
ns3::BoxValue::BoxValue ()
Definition at line 207 of file box.cc.
BoxValue() [2/2]
ns3::BoxValue::BoxValue (const Box & value)
Definition at line 207 of file box.cc.
Member Function Documentation
Copy()
Ptr< AttributeValue > ns3::BoxValue::Copy (void) const virtual
Returns
a deep copy of this class, wrapped into an Attribute object.
Implements ns3::AttributeValue.
Definition at line 207 of file box.cc.
DeserializeFromString()
bool ns3::BoxValue::DeserializeFromString (std::string value, Ptr< const AttributeChecker > checker) virtual
Parameters
[in] value A string representation of the value
[in] checker A pointer to the checker associated to the attribute.
Returns
true if the input string was correctly-formatted and could be successfully deserialized, false otherwise.
Upon return of this function, this AttributeValue instance contains the deserialized value. In most cases, this method will not make any use of the checker argument. However, in a very limited set of cases, the checker argument is needed to perform proper serialization. A nice example of code which needs it is the EnumValue::SerializeToString code.
Implements ns3::AttributeValue.
Definition at line 207 of file box.cc.
Get()
Box ns3::BoxValue::Get (void) const
Definition at line 207 of file box.cc.
Referenced by ns3::RandomBuildingPositionAllocator::GetNext(), ns3::RandomRoomPositionAllocator::GetNext(), and ns3::SameRoomPositionAllocator::GetNext().
GetAccessor()
template<typename T > bool ns3::BoxValue::GetAccessor (T & value) const inline
Definition at line 126 of file box.h.
SerializeToString()
std::string ns3::BoxValue::SerializeToString (Ptr< const AttributeChecker > checker) const virtual
Parameters
[in] checker The checker associated to the attribute
Returns
A string representation of this value.
In most cases, this method will not make any use of the checker argument. However, in a very limited set of cases, the checker argument is needed to perform proper serialization. A nice example of code which needs it is the EnumValue::SerializeToString code.
Implements ns3::AttributeValue.
Definition at line 207 of file box.cc.
Set()
void ns3::BoxValue::Set (const Box & value)
Definition at line 207 of file box.cc.
Member Data Documentation
m_value
Box ns3::BoxValue::m_value private
Definition at line 126 of file box.h.
The documentation for this class was generated from the following files:
src/mobility/model/box.h
src/mobility/model/box.cc