ns-3: ns3::LteRrcSap Class Reference
ns3::LteRrcSap Class Reference
LTE Models
Class holding definition common to all UE/eNodeB SAP Users/Providers.
#include "lte-rrc-sap.h"
Classes
struct AntennaInfoCommon
AntennaInfoCommon structure.
struct AntennaInfoDedicated
AntennaInfoDedicated structure.
struct AntennaInfoUl
AntennaInfoUl structure.
struct AsConfig
AsConfig structure.
struct BlackCellsToAddMod
BlackCellsToAddMod structure.
struct CarrierBandwidthEutra
CarrierBandwidthEutra structure.
struct CarrierFreqEutra
CarrierFreqEutra structure.
struct CellAccessRelatedInfo
CellAccessRelatedInfo structure.
struct CellIdentification
CellIdentification structure.
struct CellSelectionInfo
CellSelectionInfo structure.
struct CellsToAddMod
CellsToAddMod structure.
struct CgiInfo
CgiInfo structure.
struct DrbToAddMod
DrbToAddMod structure.
struct FreqInfo
FreqInfo structure.
struct HandoverPreparationInfo
HandoverPreparationInfo structure.
struct LogicalChannelConfig
LogicalChannelConfig structure.
struct MasterInformationBlock
MasterInformationBlock structure.
struct MeasConfig
MeasConfig structure.
struct MeasGapConfig
MeasGapConfig structure.
struct MeasIdToAddMod
MeasIdToAddMod structure.
struct MeasObjectEutra
MeasObjectEutra structure.
struct MeasObjectToAddMod
MeasObjectToAddMod structure.
struct MeasResultBestNeighCell
MeasResultBestNeighCell structure.
struct MeasResultEutra
MeasResultEutra structure.
struct MeasResults
MeasResults structure.
struct MeasResultScell
MeasResultScell structure.
struct MeasResultServFreqList
MeasResultServFreqList.
struct MeasurementReport
MeasurementReport structure.
struct MobilityControlInfo
MobilityControlInfo structure.
struct MobilityStateParameters
MobilityStateParameters structure.
struct NonCriticalExtensionConfiguration
NonCriticalExtensionConfiguration structure.
struct NonUlConfiguration
NonUlConfiguration structure.
struct PdschConfigCommon
PdschConfigCommon structure.
struct PdschConfigDedicated
PdschConfigDedicated structure.
struct PhysCellIdRange
PhysCellIdRange structure.
struct PhysicalConfigDedicated
PhysicalConfigDedicated structure.
struct PhysicalConfigDedicatedSCell
PhysicalConfigDedicatedSCell structure.
struct PlmnIdentityInfo
PlmnIdentityInfo structure.
struct PrachConfigSCell
PrachConfigSCell structure.
struct PreambleInfo
PreambleInfo structure.
struct PuschConfigDedicatedSCell
PuschConfigDedicatedSCell structure.
struct QuantityConfig
QuantityConfig structure.
struct RachConfigCommon
RachConfigCommon structure.
struct RachConfigDedicated
RachConfigDedicated structure.
struct RadioResourceConfigCommon
RadioResourceConfigCommon structure.
struct RadioResourceConfigCommonSCell
RadioResourceConfigCommonSCell.
struct RadioResourceConfigCommonSib
RadioResourceConfigCommonSib structure.
struct RadioResourceConfigDedicated
RadioResourceConfigDedicated structure.
struct RadioResourceConfigDedicatedSCell
RadioResourceConfigDedicatedSCell structure.
struct RaSupervisionInfo
RaSupervisionInfo structure.
struct ReestabUeIdentity
ReestabUeIdentity structure.
struct ReportConfigEutra
Specifies criteria for triggering of an E-UTRA measurement reporting event.
struct ReportConfigToAddMod
ReportConfigToAddMod structure.
struct RlcConfig
RlcConfig structure.
struct RrcConnectionReconfiguration
RrcConnectionReconfiguration structure.
struct RrcConnectionReconfigurationCompleted
RrcConnectionReconfigurationCompleted structure.
struct RrcConnectionReestablishment
RrcConnectionReestablishment structure.
struct RrcConnectionReestablishmentComplete
RrcConnectionReestablishmentComplete structure.
struct RrcConnectionReestablishmentReject
RrcConnectionReestablishmentReject structure.
struct RrcConnectionReestablishmentRequest
RrcConnectionReestablishmentRequest structure.
struct RrcConnectionReject
RrcConnectionReject structure.
struct RrcConnectionRelease
RrcConnectionRelease structure.
struct RrcConnectionRequest
RrcConnectionRequest structure.
struct RrcConnectionSetup
RrcConnectionSetup structure.
struct RrcConnectionSetupCompleted
RrcConnectionSetupCompleted structure.
struct SCellToAddMod
SCellToAddMod structure.
struct SoundingRsUlConfigCommon
SoundingRsUlConfigCommon structure.
struct SoundingRsUlConfigDedicated
SoundingRsUlConfigDedicated structure.
struct SpeedStatePars
SpeedStatePars structure.
struct SpeedStateScaleFactors
SpeedStateScaleFactors structure.
struct SrbToAddMod
SrbToAddMod structure.
struct SystemInformation
SystemInformation structure.
struct SystemInformationBlockType1
SystemInformationBlockType1 structure.
struct SystemInformationBlockType2
SystemInformationBlockType2 structure.
struct ThresholdEutra
Threshold for event evaluation.
struct TxFailParam
TxFailParams structure.
struct UlConfiguration
UlConfiguration structure.
struct UlPowerControlCommonSCell
UlPowerControlCommonSCell structure.
struct UlPowerControlDedicatedSCell
UlPowerControlDedicatedSCell structure.
Public Types
enum ReestablishmentCause { RECONFIGURATION_FAILURE, HANDOVER_FAILURE, OTHER_FAILURE }
ReestablishmentCause enumeration.
Public Member Functions
virtual ~LteRrcSap ()
Static Public Member Functions
static double ConvertPdschConfigDedicated2Double (PdschConfigDedicated pdschConfigDedicated)
Convert PDSCH config dedicated function.
Static Public Attributes
static const uint8_t MaxReportCells = 8
Constraint values.
Detailed Description
Class holding definition common to all UE/eNodeB SAP Users/Providers.
See 3GPP TS 36.331 for reference.
Note that only those values that are (expected to be) used by the ns-3 model are mentioned here. The naming of the variables that are defined here is the same of 36.331, except for removal of "-" and conversion to CamelCase or ALL_CAPS where needed in order to follow the ns-3 coding style. Due to the 1-to-1 mapping with TS 36.331, detailed doxygen documentation is omitted, so please refer to 36.331 for the meaning of these data structures / fields.
Definition at line 56 of file lte-rrc-sap.h.
Member Enumeration Documentation
ReestablishmentCause
enum ns3::LteRrcSap::ReestablishmentCause
ReestablishmentCause enumeration.
Enumerator
RECONFIGURATION_FAILURE
HANDOVER_FAILURE
OTHER_FAILURE
Definition at line 579 of file lte-rrc-sap.h.
Constructor & Destructor Documentation
~LteRrcSap()
ns3::LteRrcSap::~LteRrcSap () virtual
Definition at line 25 of file lte-rrc-sap.cc.
Member Function Documentation
ConvertPdschConfigDedicated2Double()
static double ns3::LteRrcSap::ConvertPdschConfigDedicated2Double (PdschConfigDedicated pdschConfigDedicated) inline static
Convert PDSCH config dedicated function.
Parameters
pdschConfigDedicated PdschConfigDedicated
Returns
double value
Definition at line 180 of file lte-rrc-sap.h.
References ns3::LteRrcSap::PdschConfigDedicated::dB0, ns3::LteRrcSap::PdschConfigDedicated::dB1, ns3::LteRrcSap::PdschConfigDedicated::dB2, ns3::LteRrcSap::PdschConfigDedicated::dB3, ns3::LteRrcSap::PdschConfigDedicated::dB_1dot77, ns3::LteRrcSap::PdschConfigDedicated::dB_3, ns3::LteRrcSap::PdschConfigDedicated::dB_4dot77, ns3::LteRrcSap::PdschConfigDedicated::dB_6, and ns3::LteRrcSap::PdschConfigDedicated::pa.
Referenced by ns3::LteUeRrc::ApplyRadioResourceConfigDedicated(), ns3::LteUeRrc::ApplyRadioResourceConfigDedicatedSecondaryCarrier(), and ns3::UeManager::RecvRrcConnectionReconfigurationCompleted().
Member Data Documentation
MaxReportCells
const uint8_t ns3::LteRrcSap::MaxReportCells = 8 static
Constraint values.
Definition at line 62 of file lte-rrc-sap.h.
Referenced by ns3::LteRrcSap::ReportConfigEutra::ReportConfigEutra().
The documentation for this class was generated from the following files:
src/lte/model/lte-rrc-sap.h
src/lte/model/lte-rrc-sap.cc