ns-3: ns3::LteFrHardAlgorithm Class Reference
ns3::LteFrHardAlgorithm Class Reference
Hard Frequency Reuse algorithm implementation which uses only 1 sub-band.
#include "lte-fr-hard-algorithm.h"
Public Member Functions
LteFrHardAlgorithm ()
Creates a trivial ffr algorithm instance.
virtual ~LteFrHardAlgorithm ()
virtual LteFfrRrcSapProvider * GetLteFfrRrcSapProvider ()
Export the "provider" part of the LteFfrRrcSap interface.
virtual LteFfrSapProvider * GetLteFfrSapProvider ()
Export the "provider" part of the LteFfrSap interface.
virtual void SetLteFfrRrcSapUser (LteFfrRrcSapUser *s)
Set the "user" part of the LteFfrRrcSap interface that this frequency reuse algorithm instance will interact with.
virtual void SetLteFfrSapUser (LteFfrSapUser *s)
Set the "user" part of the LteFfrSap interface that this frequency reuse algorithm instance will interact with.
Public Member Functions inherited from ns3::LteFfrAlgorithm
LteFfrAlgorithm ()
virtual ~LteFfrAlgorithm ()
uint16_t GetDlBandwidth () const
uint8_t GetFrCellTypeId () const
uint16_t GetUlBandwidth () const
void SetDlBandwidth (uint16_t bw)
void SetFrCellTypeId (uint8_t cellTypeId)
void SetUlBandwidth (uint16_t bw)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::LteFfrAlgorithm
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose ()
Destructor implementation.
virtual std::vector< bool > DoGetAvailableDlRbg ()
Implementation of LteFfrSapProvider::GetAvailableDlRbg.
virtual std::vector< bool > DoGetAvailableUlRbg ()
Implementation of LteFfrSapProvider::GetAvailableUlRbg.
virtual uint16_t DoGetMinContinuousUlBandwidth ()
DoGetMinContinuousUlBandwidth in number of RB.
virtual uint8_t DoGetTpc (uint16_t rnti)
DoGetTpc for UE.
virtual void DoInitialize ()
Initialize() implementation.
virtual bool DoIsDlRbgAvailableForUe (int i, uint16_t rnti)
Implementation of LteFfrSapProvider::IsDlRbgAvailableForUe.
virtual bool DoIsUlRbgAvailableForUe (int i, uint16_t rnti)
Implementation of LteFfrSapProvider::IsUlRbgAvailableForUe.
virtual void DoRecvLoadInformation (EpcX2Sap::LoadInformationParams params)
DoRecvLoadInformation.
virtual void DoReportDlCqiInfo (const struct FfMacSchedSapProvider::SchedDlCqiInfoReqParameters &params)
DoReportDlCqiInfo.
virtual void DoReportUeMeas (uint16_t rnti, LteRrcSap::MeasResults measResults)
Implementation of LteFfrRrcSapProvider::ReportUeMeas.
virtual void DoReportUlCqiInfo (const struct FfMacSchedSapProvider::SchedUlCqiInfoReqParameters &params)
DoReportUlCqiInfo.
virtual void DoReportUlCqiInfo (std::map< uint16_t, std::vector< double > > ulCqiMap)
DoReportUlCqiInfo.
virtual void Reconfigure ()
Automatic FR reconfiguration.
Protected Member Functions inherited from ns3::LteFfrAlgorithm
virtual void DoSetBandwidth (uint16_t ulBandwidth, uint16_t dlBandwidth)
Implementation of LteFfrRrcSapProvider::SetBandwidth.
virtual void DoSetCellId (uint16_t cellId)
SetCellId.
int GetRbgSize (int dlbandwidth)
Get RBG size for DL Bandwidth according to table 7.1.6.1-1 of 36.213.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
void InitializeDownlinkRbgMaps ()
Initialize downlink rbg maps.
void InitializeUplinkRbgMaps ()
Initialize uplink rbg maps.
void SetDownlinkConfiguration (uint16_t cellId, uint8_t bandwidth)
Set downlink configuration.
void SetUplinkConfiguration (uint16_t cellId, uint8_t bandwidth)
Set uplink configuration.
Private Attributes
uint8_t m_dlOffset
DL offset.
std::vector< bool > m_dlRbgMap
DL RBG Map.
uint8_t m_dlSubBand
DL subband.
LteFfrRrcSapProvider * m_ffrRrcSapProvider
FFR RRC SAP provider.
LteFfrRrcSapUser * m_ffrRrcSapUser
FFR RRC SAP user.
LteFfrSapProvider * m_ffrSapProvider
FFR SAP provider.
LteFfrSapUser * m_ffrSapUser
FFR SAP user.
uint8_t m_ulOffset
UL offset.
std::vector< bool > m_ulRbgMap
UL RBG Map.
uint8_t m_ulSubBand
UL subband.
Friends
class MemberLteFfrRrcSapProvider< LteFrHardAlgorithm >
let the forwarder class access the protected and private members
class MemberLteFfrSapProvider< LteFrHardAlgorithm >
let the forwarder class access the protected and private members
Additional Inherited Members
Protected Attributes inherited from ns3::LteFfrAlgorithm
uint16_t m_cellId
cell ID
uint8_t m_dlBandwidth
downlink bandwidth in RBs
bool m_enabledInUplink
If true FR algorithm will also work in Uplink.
uint8_t m_frCellTypeId
FFR cell type ID for automatic configuration.
bool m_needReconfiguration
If true FR algorithm will be reconfigured.
uint8_t m_ulBandwidth
uplink bandwidth in RBs
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Hard Frequency Reuse algorithm implementation which uses only 1 sub-band.
Definition at line 36 of file lte-fr-hard-algorithm.h.
Constructor & Destructor Documentation
LteFrHardAlgorithm()
ns3::LteFrHardAlgorithm::LteFrHardAlgorithm ()
Creates a trivial ffr algorithm instance.
Definition at line 86 of file lte-fr-hard-algorithm.cc.
References m_ffrRrcSapProvider, m_ffrSapProvider, MemberLteFfrRrcSapProvider< LteFrHardAlgorithm >, MemberLteFfrSapProvider< LteFrHardAlgorithm >, and NS_LOG_FUNCTION.
~LteFrHardAlgorithm()
ns3::LteFrHardAlgorithm::~LteFrHardAlgorithm () virtual
Definition at line 100 of file lte-fr-hard-algorithm.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::LteFrHardAlgorithm::DoDispose () protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::LteFfrAlgorithm.
Definition at line 107 of file lte-fr-hard-algorithm.cc.
References m_ffrRrcSapProvider, m_ffrSapProvider, and NS_LOG_FUNCTION.
DoGetAvailableDlRbg()
std::vector< bool > ns3::LteFrHardAlgorithm::DoGetAvailableDlRbg () protected virtual
Implementation of LteFfrSapProvider::GetAvailableDlRbg.
Returns
vector of size (m_dlBandwidth/RbgSize); false indicates that RBG is free to use, true otherwise
Implements ns3::LteFfrAlgorithm.
Definition at line 284 of file lte-fr-hard-algorithm.cc.
References InitializeDownlinkRbgMaps(), m_dlRbgMap, ns3::LteFfrAlgorithm::m_needReconfiguration, NS_LOG_FUNCTION, and Reconfigure().
DoGetAvailableUlRbg()
std::vector< bool > ns3::LteFrHardAlgorithm::DoGetAvailableUlRbg () protected virtual
Implementation of LteFfrSapProvider::GetAvailableUlRbg.
Returns
vector of size m_ulBandwidth; false indicates that RB is free to use, true otherwise
Implements ns3::LteFfrAlgorithm.
Definition at line 309 of file lte-fr-hard-algorithm.cc.
References InitializeUplinkRbgMaps(), m_ulRbgMap, and NS_LOG_FUNCTION.
DoGetMinContinuousUlBandwidth()
uint16_t ns3::LteFrHardAlgorithm::DoGetMinContinuousUlBandwidth () protected virtual
DoGetMinContinuousUlBandwidth in number of RB.
Returns
number of RB in min continuous UL Bandwidth
Implements ns3::LteFfrAlgorithm.
Definition at line 363 of file lte-fr-hard-algorithm.cc.
References ns3::LteFfrAlgorithm::m_enabledInUplink, ns3::LteFfrAlgorithm::m_ulBandwidth, m_ulSubBand, and NS_LOG_FUNCTION.
DoGetTpc()
uint8_t ns3::LteFrHardAlgorithm::DoGetTpc (uint16_t rnti) protected virtual
DoGetTpc for UE.
Parameters
rnti
Returns
TPC value
Implements ns3::LteFfrAlgorithm.
Definition at line 356 of file lte-fr-hard-algorithm.cc.
References NS_LOG_FUNCTION.
DoInitialize()
void ns3::LteFrHardAlgorithm::DoInitialize () protected virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 179 of file lte-fr-hard-algorithm.cc.
References ns3::Object::DoInitialize(), ns3::LteFfrAlgorithm::m_dlBandwidth, ns3::LteFfrAlgorithm::m_frCellTypeId, ns3::LteFfrAlgorithm::m_ulBandwidth, NS_ASSERT_MSG(), NS_LOG_FUNCTION, SetDownlinkConfiguration(), and SetUplinkConfiguration().
DoIsDlRbgAvailableForUe()
bool ns3::LteFrHardAlgorithm::DoIsDlRbgAvailableForUe (int rbId, uint16_t rnti) protected virtual
Implementation of LteFfrSapProvider::IsDlRbgAvailableForUe.
Parameters
rbId
rnti Radio Network Temporary Identity, an integer identifying the UE where the report originates from
Returns
true if UE can be served on i-th RB, false otherwise
Implements ns3::LteFfrAlgorithm.
Definition at line 302 of file lte-fr-hard-algorithm.cc.
References m_dlRbgMap, and NS_LOG_FUNCTION.
DoIsUlRbgAvailableForUe()
bool ns3::LteFrHardAlgorithm::DoIsUlRbgAvailableForUe (int rbId, uint16_t rnti) protected virtual
Implementation of LteFfrSapProvider::IsUlRbgAvailableForUe.
Parameters
rbId
rnti Radio Network Temporary Identity, an integer identifying the UE where the report originates from
Returns
true if UE can be served on i-th RB, false otherwise
Implements ns3::LteFfrAlgorithm.
Definition at line 322 of file lte-fr-hard-algorithm.cc.
References ns3::LteFfrAlgorithm::m_enabledInUplink, m_ulRbgMap, and NS_LOG_FUNCTION.
DoRecvLoadInformation()
void ns3::LteFrHardAlgorithm::DoRecvLoadInformation (EpcX2Sap::LoadInformationParams params) protected virtual
DoRecvLoadInformation.
Parameters
params
Implements ns3::LteFfrAlgorithm.
Definition at line 384 of file lte-fr-hard-algorithm.cc.
References NS_LOG_FUNCTION, and NS_LOG_WARN.
DoReportDlCqiInfo()
void ns3::LteFrHardAlgorithm::DoReportDlCqiInfo (const struct FfMacSchedSapProvider::SchedDlCqiInfoReqParameters & params) protected virtual
DoReportDlCqiInfo.
Parameters
params
Implements ns3::LteFfrAlgorithm.
Definition at line 335 of file lte-fr-hard-algorithm.cc.
References NS_LOG_FUNCTION, and NS_LOG_WARN.
DoReportUeMeas()
void ns3::LteFrHardAlgorithm::DoReportUeMeas (uint16_t rnti, LteRrcSap::MeasResults measResults) protected virtual
Implementation of LteFfrRrcSapProvider::ReportUeMeas.
Parameters
rnti Radio Network Temporary Identity, an integer identifying the UE where the report originates from
measResults a single report of one measurement identity
Implements ns3::LteFfrAlgorithm.
Definition at line 376 of file lte-fr-hard-algorithm.cc.
References ns3::LteRrcSap::MeasResults::measId, NS_LOG_FUNCTION, and NS_LOG_WARN.
DoReportUlCqiInfo() [1/2]
void ns3::LteFrHardAlgorithm::DoReportUlCqiInfo (const struct FfMacSchedSapProvider::SchedUlCqiInfoReqParameters & params) protected virtual
DoReportUlCqiInfo.
Parameters
params
Implements ns3::LteFfrAlgorithm.
Definition at line 342 of file lte-fr-hard-algorithm.cc.
References NS_LOG_FUNCTION, and NS_LOG_WARN.
DoReportUlCqiInfo() [2/2]
void ns3::LteFrHardAlgorithm::DoReportUlCqiInfo (std::map< uint16_t, std::vector< double > > ulCqiMap) protected virtual
DoReportUlCqiInfo.
Parameters
ulCqiMap
Implements ns3::LteFfrAlgorithm.
Definition at line 349 of file lte-fr-hard-algorithm.cc.
References NS_LOG_FUNCTION, and NS_LOG_WARN.
GetLteFfrRrcSapProvider()
LteFfrRrcSapProvider * ns3::LteFrHardAlgorithm::GetLteFfrRrcSapProvider () virtual
Export the "provider" part of the LteFfrRrcSap interface.
Returns
the reference to the "provider" part of the interface, typically to be kept by an LteEnbRrc instance
Implements ns3::LteFfrAlgorithm.
Definition at line 171 of file lte-fr-hard-algorithm.cc.
References m_ffrRrcSapProvider, and NS_LOG_FUNCTION.
GetLteFfrSapProvider()
LteFfrSapProvider * ns3::LteFrHardAlgorithm::GetLteFfrSapProvider () virtual
Export the "provider" part of the LteFfrSap interface.
Returns
the reference to the "provider" part of the interface, typically to be kept by an Scheduler instance
Implements ns3::LteFfrAlgorithm.
Definition at line 156 of file lte-fr-hard-algorithm.cc.
References m_ffrSapProvider, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::LteFrHardAlgorithm::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 116 of file lte-fr-hard-algorithm.cc.
References m_dlOffset, m_dlSubBand, m_ulOffset, m_ulSubBand, ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
InitializeDownlinkRbgMaps()
void ns3::LteFrHardAlgorithm::InitializeDownlinkRbgMaps () private
Initialize downlink rbg maps.
Definition at line 240 of file lte-fr-hard-algorithm.cc.
References ns3::LteFfrAlgorithm::GetRbgSize(), ns3::LteFfrAlgorithm::m_dlBandwidth, m_dlOffset, m_dlRbgMap, m_dlSubBand, and NS_ASSERT_MSG().
Referenced by DoGetAvailableDlRbg(), and Reconfigure().
InitializeUplinkRbgMaps()
void ns3::LteFrHardAlgorithm::InitializeUplinkRbgMaps () private
Initialize uplink rbg maps.
Definition at line 260 of file lte-fr-hard-algorithm.cc.
References ns3::LteFfrAlgorithm::m_enabledInUplink, ns3::LteFfrAlgorithm::m_ulBandwidth, m_ulOffset, m_ulRbgMap, m_ulSubBand, and NS_ASSERT_MSG().
Referenced by DoGetAvailableUlRbg(), and Reconfigure().
Reconfigure()
void ns3::LteFrHardAlgorithm::Reconfigure () protected virtual
Automatic FR reconfiguration.
Implements ns3::LteFfrAlgorithm.
Definition at line 196 of file lte-fr-hard-algorithm.cc.
References InitializeDownlinkRbgMaps(), InitializeUplinkRbgMaps(), ns3::LteFfrAlgorithm::m_dlBandwidth, ns3::LteFfrAlgorithm::m_frCellTypeId, ns3::LteFfrAlgorithm::m_needReconfiguration, ns3::LteFfrAlgorithm::m_ulBandwidth, NS_LOG_FUNCTION, SetDownlinkConfiguration(), and SetUplinkConfiguration().
Referenced by DoGetAvailableDlRbg().
SetDownlinkConfiguration()
void ns3::LteFrHardAlgorithm::SetDownlinkConfiguration (uint16_t cellId, uint8_t bandwidth) private
Set downlink configuration.
Parameters
cellId the cell ID
bandwidth the bandwidth
Definition at line 210 of file lte-fr-hard-algorithm.cc.
References ns3::g_frHardDownlinkDefaultConfiguration, ns3::LteFfrAlgorithm::m_cellId, ns3::LteFfrAlgorithm::m_dlBandwidth, ns3::FrHardDownlinkDefaultConfiguration::m_dlOffset, m_dlOffset, ns3::FrHardDownlinkDefaultConfiguration::m_dlSubBand, m_dlSubBand, NS_LOG_FUNCTION, and ns3::NUM_DOWNLINK_CONFS().
Referenced by DoInitialize(), and Reconfigure().
SetLteFfrRrcSapUser()
void ns3::LteFrHardAlgorithm::SetLteFfrRrcSapUser (LteFfrRrcSapUser * s) virtual
Set the "user" part of the LteFfrRrcSap interface that this frequency reuse algorithm instance will interact with.
Parameters
s a reference to the "user" part of the interface, typically a member of an LteEnbRrc instance
Implements ns3::LteFfrAlgorithm.
Definition at line 163 of file lte-fr-hard-algorithm.cc.
References m_ffrRrcSapUser, and NS_LOG_FUNCTION.
SetLteFfrSapUser()
void ns3::LteFrHardAlgorithm::SetLteFfrSapUser (LteFfrSapUser * s) virtual
Set the "user" part of the LteFfrSap interface that this frequency reuse algorithm instance will interact with.
Parameters
s a reference to the "user" part of the interface, typically a member of an Scheduler instance
Implements ns3::LteFfrAlgorithm.
Definition at line 148 of file lte-fr-hard-algorithm.cc.
References m_ffrSapUser, and NS_LOG_FUNCTION.
SetUplinkConfiguration()
void ns3::LteFrHardAlgorithm::SetUplinkConfiguration (uint16_t cellId, uint8_t bandwidth) private
Set uplink configuration.
Parameters
cellId the cell ID
bandwidth the bandwidth
Definition at line 225 of file lte-fr-hard-algorithm.cc.
References ns3::g_frHardUplinkDefaultConfiguration, ns3::LteFfrAlgorithm::m_cellId, ns3::LteFfrAlgorithm::m_ulBandwidth, ns3::FrHardUplinkDefaultConfiguration::m_ulOffset, m_ulOffset, ns3::FrHardUplinkDefaultConfiguration::m_ulSubBand, m_ulSubBand, NS_LOG_FUNCTION, and ns3::NUM_UPLINK_CONFS().
Referenced by DoInitialize(), and Reconfigure().
Friends And Related Function Documentation
MemberLteFfrRrcSapProvider< LteFrHardAlgorithm >
friend class MemberLteFfrRrcSapProvider< LteFrHardAlgorithm > friend
let the forwarder class access the protected and private members
Definition at line 57 of file lte-fr-hard-algorithm.h.
Referenced by LteFrHardAlgorithm().
MemberLteFfrSapProvider< LteFrHardAlgorithm >
friend class MemberLteFfrSapProvider< LteFrHardAlgorithm > friend
let the forwarder class access the protected and private members
Definition at line 57 of file lte-fr-hard-algorithm.h.
Referenced by LteFrHardAlgorithm().
Member Data Documentation
m_dlOffset
uint8_t ns3::LteFrHardAlgorithm::m_dlOffset private
DL offset.
Definition at line 118 of file lte-fr-hard-algorithm.h.
Referenced by GetTypeId(), InitializeDownlinkRbgMaps(), and SetDownlinkConfiguration().
m_dlRbgMap
std::vector<bool> ns3::LteFrHardAlgorithm::m_dlRbgMap private
DL RBG Map.
Definition at line 124 of file lte-fr-hard-algorithm.h.
Referenced by DoGetAvailableDlRbg(), DoIsDlRbgAvailableForUe(), and InitializeDownlinkRbgMaps().
m_dlSubBand
uint8_t ns3::LteFrHardAlgorithm::m_dlSubBand private
DL subband.
Definition at line 119 of file lte-fr-hard-algorithm.h.
Referenced by GetTypeId(), InitializeDownlinkRbgMaps(), and SetDownlinkConfiguration().
m_ffrRrcSapProvider
LteFfrRrcSapProvider* ns3::LteFrHardAlgorithm::m_ffrRrcSapProvider private
FFR RRC SAP provider.
Definition at line 116 of file lte-fr-hard-algorithm.h.
Referenced by LteFrHardAlgorithm(), DoDispose(), and GetLteFfrRrcSapProvider().
m_ffrRrcSapUser
LteFfrRrcSapUser* ns3::LteFrHardAlgorithm::m_ffrRrcSapUser private
FFR RRC SAP user.
Definition at line 115 of file lte-fr-hard-algorithm.h.
Referenced by SetLteFfrRrcSapUser().
m_ffrSapProvider
LteFfrSapProvider* ns3::LteFrHardAlgorithm::m_ffrSapProvider private
FFR SAP provider.
Definition at line 112 of file lte-fr-hard-algorithm.h.
Referenced by LteFrHardAlgorithm(), DoDispose(), and GetLteFfrSapProvider().
m_ffrSapUser
LteFfrSapUser* ns3::LteFrHardAlgorithm::m_ffrSapUser private
FFR SAP user.
Definition at line 111 of file lte-fr-hard-algorithm.h.
Referenced by SetLteFfrSapUser().
m_ulOffset
uint8_t ns3::LteFrHardAlgorithm::m_ulOffset private
UL offset.
Definition at line 121 of file lte-fr-hard-algorithm.h.
Referenced by GetTypeId(), InitializeUplinkRbgMaps(), and SetUplinkConfiguration().
m_ulRbgMap
std::vector<bool> ns3::LteFrHardAlgorithm::m_ulRbgMap private
UL RBG Map.
Definition at line 125 of file lte-fr-hard-algorithm.h.
Referenced by DoGetAvailableUlRbg(), DoIsUlRbgAvailableForUe(), and InitializeUplinkRbgMaps().
m_ulSubBand
uint8_t ns3::LteFrHardAlgorithm::m_ulSubBand private
UL subband.
Definition at line 122 of file lte-fr-hard-algorithm.h.
Referenced by DoGetMinContinuousUlBandwidth(), GetTypeId(), InitializeUplinkRbgMaps(), and SetUplinkConfiguration().
The documentation for this class was generated from the following files:
src/lte/model/lte-fr-hard-algorithm.h
src/lte/model/lte-fr-hard-algorithm.cc