ns-3: ns3::NetworkServerHelper Class Reference
ns3::NetworkServerHelper Class Reference
This class can install Network Server applications on multiple nodes at once.
#include "network-server-helper.h"
Public Member Functions
NetworkServerHelper ()
~NetworkServerHelper ()
ApplicationContainer Install (NodeContainer c)
ApplicationContainer Install (Ptr< Node > node)
void SetAttribute (std::string name, const AttributeValue &value)
void SetEndDevices (NodeContainer endDevices)
Set which end devices will be managed by this NS.
void SetGateways (NodeContainer gateways)
Set which gateways will need to be connected to this NS.
Private Member Functions
Ptr< Application > InstallPriv (Ptr< Node > node)
Private Attributes
NodeContainer m_endDevices
Set of endDevices to connect to this NS.
ObjectFactory m_factory
NodeContainer m_gateways
Set of gateways to connect to this NS.
PointToPointHelper p2pHelper
Helper to create PointToPoint links.
Detailed Description
This class can install Network Server applications on multiple nodes at once.
Definition at line 39 of file network-server-helper.h.
Constructor & Destructor Documentation
NetworkServerHelper()
ns3::NetworkServerHelper::NetworkServerHelper ()
Definition at line 33 of file network-server-helper.cc.
References m_factory, p2pHelper, ns3::PointToPointHelper::SetChannelAttribute(), ns3::PointToPointHelper::SetDeviceAttribute(), and ns3::ObjectFactory::SetTypeId().
~NetworkServerHelper()
ns3::NetworkServerHelper::~NetworkServerHelper ()
Definition at line 40 of file network-server-helper.cc.
Member Function Documentation
Install() [1/2]
ApplicationContainer ns3::NetworkServerHelper::Install (NodeContainer c)
Definition at line 69 of file network-server-helper.cc.
References ns3::ApplicationContainer::Add(), ns3::NodeContainer::Begin(), ns3::NodeContainer::End(), and InstallPriv().
Install() [2/2]
ApplicationContainer ns3::NetworkServerHelper::Install (Ptr< Node > node)
Definition at line 63 of file network-server-helper.cc.
References InstallPriv().
InstallPriv()
Ptr< Application > ns3::NetworkServerHelper::InstallPriv (Ptr< Node > node) private
Definition at line 81 of file network-server-helper.cc.
References ns3::Node::AddApplication(), ns3::NodeContainer::Begin(), ns3::ObjectFactory::Create(), ns3::NodeContainer::End(), ns3::NetDeviceContainer::Get(), ns3::Node::GetDevice(), ns3::Node::GetNDevices(), ns3::PointToPointHelper::Install(), m_endDevices, m_factory, m_gateways, ns3::MakeCallback(), NS_LOG_FUNCTION, p2pHelper, and ns3::SimpleNetworkServer::Receive().
Referenced by Install().
SetAttribute()
void ns3::NetworkServerHelper::SetAttribute (std::string name, const AttributeValue & value)
Definition at line 45 of file network-server-helper.cc.
References m_factory, and ns3::ObjectFactory::Set().
SetEndDevices()
void ns3::NetworkServerHelper::SetEndDevices (NodeContainer endDevices)
Set which end devices will be managed by this NS.
Definition at line 57 of file network-server-helper.cc.
References endDevices, and m_endDevices.
SetGateways()
void ns3::NetworkServerHelper::SetGateways (NodeContainer gateways)
Set which gateways will need to be connected to this NS.
Definition at line 51 of file network-server-helper.cc.
References gateways, and m_gateways.
Member Data Documentation
m_endDevices
NodeContainer ns3::NetworkServerHelper::m_endDevices private
Set of endDevices to connect to this NS.
Definition at line 69 of file network-server-helper.h.
Referenced by InstallPriv(), and SetEndDevices().
m_factory
ObjectFactory ns3::NetworkServerHelper::m_factory private
Definition at line 65 of file network-server-helper.h.
Referenced by NetworkServerHelper(), InstallPriv(), and SetAttribute().
m_gateways
NodeContainer ns3::NetworkServerHelper::m_gateways private
Set of gateways to connect to this NS.
Definition at line 67 of file network-server-helper.h.
Referenced by InstallPriv(), and SetGateways().
p2pHelper
PointToPointHelper ns3::NetworkServerHelper::p2pHelper private
Helper to create PointToPoint links.
Definition at line 71 of file network-server-helper.h.
Referenced by NetworkServerHelper(), and InstallPriv().
The documentation for this class was generated from the following files:
src/lorawan/helper/network-server-helper.h
src/lorawan/helper/network-server-helper.cc