ns-3: ns3::LteRadioBearerTag Class Reference
ns3::LteRadioBearerTag Class Reference
Tag used to define the RNTI and LC id for each MAC packet trasmitted.
#include "lte-radio-bearer-tag.h"
Public Member Functions
LteRadioBearerTag ()
Create an empty LteRadioBearerTag.
LteRadioBearerTag (uint16_t rnti, uint8_t lcId)
Create a LteRadioBearerTag with the given RNTI and LC id.
LteRadioBearerTag (uint16_t rnti, uint8_t lcId, uint8_t layer)
Create a LteRadioBearerTag with the given RNTI, LC id and layer.
virtual void Deserialize (TagBuffer i)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint8_t GetLayer (void) const
Get layer function.
uint8_t GetLcid (void) const
Get LCID function.
uint16_t GetRnti (void) const
Get RNTI function.
virtual uint32_t GetSerializedSize () const
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer i) const
void SetLayer (uint8_t layer)
Set the layer id to the given value.
void SetLcid (uint8_t lcid)
Set the LC id to the given value.
void SetRnti (uint16_t rnti)
Set the RNTI to the given value.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_layer
layer
uint8_t m_lcid
LCID.
uint16_t m_rnti
RNTI.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Tag used to define the RNTI and LC id for each MAC packet trasmitted.
Definition at line 34 of file lte-radio-bearer-tag.h.
Constructor & Destructor Documentation
LteRadioBearerTag() [1/3]
ns3::LteRadioBearerTag::LteRadioBearerTag ()
Create an empty LteRadioBearerTag.
Definition at line 55 of file lte-radio-bearer-tag.cc.
LteRadioBearerTag() [2/3]
ns3::LteRadioBearerTag::LteRadioBearerTag (uint16_t rnti, uint8_t lcId)
Create a LteRadioBearerTag with the given RNTI and LC id.
Parameters
rnti the RNTI
lcId the LCID
Definition at line 61 of file lte-radio-bearer-tag.cc.
LteRadioBearerTag() [3/3]
ns3::LteRadioBearerTag::LteRadioBearerTag (uint16_t rnti, uint8_t lcId, uint8_t layer)
Create a LteRadioBearerTag with the given RNTI, LC id and layer.
Parameters
rnti the RNTI
lcId the LCID
layer the layer
Definition at line 67 of file lte-radio-bearer-tag.cc.
Member Function Documentation
Deserialize()
void ns3::LteRadioBearerTag::Deserialize (TagBuffer i) virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 107 of file lte-radio-bearer-tag.cc.
References m_layer, m_lcid, m_rnti, ns3::TagBuffer::ReadU16(), and ns3::TagBuffer::ReadU8().
GetInstanceTypeId()
TypeId ns3::LteRadioBearerTag::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 50 of file lte-radio-bearer-tag.cc.
References GetTypeId().
GetLayer()
uint8_t ns3::LteRadioBearerTag::GetLayer (void) const
Get layer function.
Returns
layer
Definition at line 127 of file lte-radio-bearer-tag.cc.
References m_layer.
Referenced by ns3::LteEnbMac::DoTransmitPdu(), and ns3::LteSpectrumPhy::EndRxData().
GetLcid()
uint8_t ns3::LteRadioBearerTag::GetLcid (void) const
Get LCID function.
Returns
LCID
Definition at line 121 of file lte-radio-bearer-tag.cc.
References m_lcid.
Referenced by ns3::LteEnbMac::DoReceivePhyPdu(), ns3::LteUeMac::DoReceivePhyPdu(), and GetTypeId().
GetRnti()
uint16_t ns3::LteRadioBearerTag::GetRnti (void) const
Get RNTI function.
Returns
RNTI
Definition at line 115 of file lte-radio-bearer-tag.cc.
References m_rnti.
Referenced by ns3::LteEnbMac::DoReceivePhyPdu(), ns3::LteUeMac::DoReceivePhyPdu(), ns3::LteSpectrumPhy::EndRxData(), and GetTypeId().
GetSerializedSize()
uint32_t ns3::LteRadioBearerTag::GetSerializedSize () const virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 93 of file lte-radio-bearer-tag.cc.
GetTypeId()
TypeId ns3::LteRadioBearerTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 31 of file lte-radio-bearer-tag.cc.
References GetLcid(), GetRnti(), ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::LteRadioBearerTag::Print (std::ostream & os) const virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 133 of file lte-radio-bearer-tag.cc.
References m_layer, m_lcid, and m_rnti.
Serialize()
void ns3::LteRadioBearerTag::Serialize (TagBuffer i) const virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 99 of file lte-radio-bearer-tag.cc.
References m_layer, m_lcid, m_rnti, ns3::TagBuffer::WriteU16(), and ns3::TagBuffer::WriteU8().
SetLayer()
void ns3::LteRadioBearerTag::SetLayer (uint8_t layer)
Set the layer id to the given value.
Parameters
layer the value of the layer to set
Definition at line 87 of file lte-radio-bearer-tag.cc.
References m_layer.
SetLcid()
void ns3::LteRadioBearerTag::SetLcid (uint8_t lcid)
Set the LC id to the given value.
Parameters
lcid the value of the RNTI to set
Definition at line 81 of file lte-radio-bearer-tag.cc.
References m_lcid.
SetRnti()
void ns3::LteRadioBearerTag::SetRnti (uint16_t rnti)
Set the RNTI to the given value.
Parameters
rnti the value of the RNTI to set
Definition at line 75 of file lte-radio-bearer-tag.cc.
References m_rnti.
Member Data Documentation
m_layer
uint8_t ns3::LteRadioBearerTag::m_layer private
layer
Definition at line 113 of file lte-radio-bearer-tag.h.
Referenced by Deserialize(), GetLayer(), Print(), Serialize(), and SetLayer().
m_lcid
uint8_t ns3::LteRadioBearerTag::m_lcid private
LCID.
Definition at line 112 of file lte-radio-bearer-tag.h.
Referenced by Deserialize(), GetLcid(), Print(), Serialize(), and SetLcid().
m_rnti
uint16_t ns3::LteRadioBearerTag::m_rnti private
RNTI.
Definition at line 111 of file lte-radio-bearer-tag.h.
Referenced by Deserialize(), GetRnti(), Print(), Serialize(), and SetRnti().
The documentation for this class was generated from the following files:
src/lte/model/lte-radio-bearer-tag.h
src/lte/model/lte-radio-bearer-tag.cc