ns-3: ns3::UanHeaderCommon Class Reference
ns3::UanHeaderCommon Class Reference
UAN Models
#include "uan-header-common.h"
Public Member Functions
UanHeaderCommon ()
Default constructor.
UanHeaderCommon (const Mac8Address src, const Mac8Address dest, uint8_t type, uint8_t protocolNumber)
Create UanHeaderCommon object with given source and destination address and header type.
virtual ~UanHeaderCommon ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Mac8Address GetDest (void) const
Get the destination address.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint16_t GetProtocolNumber (void) const
Get the packet type value.
virtual uint32_t GetSerializedSize (void) const
Mac8Address GetSrc (void) const
Get the source address.
uint8_t GetType (void) const
Get the header type value.
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetDest (Mac8Address dest)
Set the destination address.
void SetProtocolNumber (uint16_t protocolNumber)
Set the packet type.
void SetSrc (Mac8Address src)
Set the source address.
void SetType (uint8_t type)
Set the header type.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Mac8Address m_dest
The destination address.
Mac8Address m_src
The source address.
UanProtocolBits m_uanProtocolBits {0}
The type and protocol bits.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Common packet header fields.
1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ | src addr | dst addr | prtcl | type | +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
src addr: The MAC8 source address
dst addr: The MAC8 destination address
prtcl: The layer 3 protocol prtcl=1 (IPv4) prtcl=2 (ARP) prtcl=3 (IPv6)
type: The type field is MAC protocol specific
Definition at line 59 of file uan-header-common.h.
Constructor & Destructor Documentation
UanHeaderCommon() [1/2]
ns3::UanHeaderCommon::UanHeaderCommon ()
Default constructor.
Definition at line 32 of file uan-header-common.cc.
UanHeaderCommon() [2/2]
ns3::UanHeaderCommon::UanHeaderCommon (const Mac8Address src, const Mac8Address dest, uint8_t type, uint8_t protocolNumber)
Create UanHeaderCommon object with given source and destination address and header type.
Parameters
src Source address defined in header.
dest Destination address defined in header.
type Header type.
protocolNumber the layer 3 protocol number
Definition at line 36 of file uan-header-common.cc.
References ns3::UanProtocolBits::m_type, m_uanProtocolBits, and SetProtocolNumber().
~UanHeaderCommon()
ns3::UanHeaderCommon::~UanHeaderCommon () virtual
Destructor.
Definition at line 61 of file uan-header-common.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::UanHeaderCommon::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 149 of file uan-header-common.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_dest, ns3::UanProtocolBits::m_protocolNumber, m_src, ns3::UanProtocolBits::m_type, m_uanProtocolBits, ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetDest()
Mac8Address ns3::UanHeaderCommon::GetDest (void) const
Get the destination address.
Returns
Mac8Address in destination field.
Definition at line 99 of file uan-header-common.cc.
References m_dest.
Referenced by ns3::UanMacRc::IsPhy1Ok(), ns3::UanMacCw::PhyRxPacketGood(), ns3::UanMacRc::ReceiveOkFromPhy(), ns3::UanMacRcGw::ReceivePacket(), ns3::UanMacAloha::RxPacketGood(), ns3::UanMacRcGw::SendPacket(), and ns3::UanMacRc::SendPacket().
GetInstanceTypeId()
TypeId ns3::UanHeaderCommon::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 57 of file uan-header-common.cc.
References GetTypeId().
GetProtocolNumber()
uint16_t ns3::UanHeaderCommon::GetProtocolNumber (void) const
Get the packet type value.
Returns
value of protocolNumber field.
Definition at line 115 of file uan-header-common.cc.
References ARP_PROT_NUMBER, IPV4_PROT_NUMBER, IPV6_PROT_NUMBER, ns3::UanProtocolBits::m_protocolNumber, and m_uanProtocolBits.
Referenced by ns3::UanMacCw::PhyRxPacketGood(), ns3::UanMacRc::ReceiveOkFromPhy(), ns3::UanMacRcGw::ReceivePacket(), and ns3::UanMacAloha::RxPacketGood().
GetSerializedSize()
uint32_t ns3::UanHeaderCommon::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 129 of file uan-header-common.cc.
Referenced by ns3::Reservation::Reservation(), ns3::UanMacRc::UanMacRc(), ns3::UanMacRcGw::UanMacRcGw(), ns3::UanMacRcGw::ComputeExpS(), AcousticModemEnergyTestCase::DoRun(), and ns3::UanMacRc::ReceiveOkFromPhy().
GetSrc()
Mac8Address ns3::UanHeaderCommon::GetSrc (void) const
Get the source address.
Returns
Mac8Address in source field.
Definition at line 104 of file uan-header-common.cc.
References m_src.
Referenced by ns3::UanPhyCalcSinrDual::CalcSinrDb(), ns3::UanMacCw::PhyRxPacketGood(), ns3::UanMacRc::ReceiveOkFromPhy(), ns3::UanMacRcGw::ReceivePacket(), and ns3::UanMacAloha::RxPacketGood().
GetType()
uint8_t ns3::UanHeaderCommon::GetType (void) const
Get the header type value.
Returns
value of type field.
Definition at line 109 of file uan-header-common.cc.
References ns3::UanProtocolBits::m_type, and m_uanProtocolBits.
Referenced by ns3::UanPhyCalcSinrDual::CalcSinrDb(), ns3::UanMacRc::IsPhy1Ok(), ns3::UanMacRc::ReceiveOkFromPhy(), ns3::UanMacRcGw::ReceivePacket(), ns3::UanMacRcGw::SendPacket(), and ns3::UanMacRc::SendPacket().
GetTypeId()
TypeId ns3::UanHeaderCommon::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 46 of file uan-header-common.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::UanHeaderCommon::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 163 of file uan-header-common.cc.
References m_dest, ns3::UanProtocolBits::m_protocolNumber, m_src, ns3::UanProtocolBits::m_type, and m_uanProtocolBits.
Serialize()
void ns3::UanHeaderCommon::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 135 of file uan-header-common.cc.
References first::address, ns3::Mac8Address::CopyTo(), m_dest, ns3::UanProtocolBits::m_protocolNumber, m_src, ns3::UanProtocolBits::m_type, m_uanProtocolBits, and visualizer.core::start().
SetDest()
void ns3::UanHeaderCommon::SetDest (Mac8Address dest)
Set the destination address.
Parameters
dest Address of destination node.
Definition at line 67 of file uan-header-common.cc.
References m_dest.
Referenced by ns3::UanMacRcGw::EndCycle(), ns3::UanMacAloha::Enqueue(), ns3::UanMacCw::Enqueue(), ns3::UanMacRc::ScheduleData(), and ns3::UanMacRcGw::StartCycle().
SetProtocolNumber()
void ns3::UanHeaderCommon::SetProtocolNumber (uint16_t protocolNumber)
Set the packet type.
Used to indicate the layer 3 protocol
Parameters
protocolNumber The layer 3 protocol number value.
Definition at line 84 of file uan-header-common.cc.
References ARP_PROT_NUMBER, IPV4_PROT_NUMBER, IPV6_PROT_NUMBER, ns3::UanProtocolBits::m_protocolNumber, m_uanProtocolBits, and NS_ASSERT_MSG().
Referenced by UanHeaderCommon(), ns3::UanMacAloha::Enqueue(), ns3::UanMacCw::Enqueue(), and ns3::UanMacRcGw::StartCycle().
SetSrc()
void ns3::UanHeaderCommon::SetSrc (Mac8Address src)
Set the source address.
Parameters
src Address of packet source node.
Definition at line 72 of file uan-header-common.cc.
References m_src.
Referenced by ns3::UanMacRcGw::EndCycle(), ns3::UanMacAloha::Enqueue(), ns3::UanMacCw::Enqueue(), ns3::UanMacRc::ScheduleData(), and ns3::UanMacRcGw::StartCycle().
SetType()
void ns3::UanHeaderCommon::SetType (uint8_t type)
Set the header type.
Use of this value is protocol specific.
Parameters
type The type value.
Definition at line 78 of file uan-header-common.cc.
References ns3::UanProtocolBits::m_type, and m_uanProtocolBits.
Referenced by ns3::UanMacRcGw::EndCycle(), ns3::UanMacAloha::Enqueue(), ns3::UanMacCw::Enqueue(), ns3::UanMacRc::ScheduleData(), and ns3::UanMacRcGw::StartCycle().
Member Data Documentation
m_dest
Mac8Address ns3::UanHeaderCommon::m_dest private
The destination address.
Definition at line 142 of file uan-header-common.h.
Referenced by Deserialize(), GetDest(), Print(), Serialize(), and SetDest().
m_src
Mac8Address ns3::UanHeaderCommon::m_src private
The source address.
Definition at line 143 of file uan-header-common.h.
Referenced by Deserialize(), GetSrc(), Print(), Serialize(), and SetSrc().
m_uanProtocolBits
UanProtocolBits ns3::UanHeaderCommon::m_uanProtocolBits {0} private
The type and protocol bits.
Definition at line 144 of file uan-header-common.h.
Referenced by UanHeaderCommon(), Deserialize(), GetProtocolNumber(), GetType(), Print(), Serialize(), SetProtocolNumber(), and SetType().
The documentation for this class was generated from the following files:
src/uan/model/uan-header-common.h
src/uan/model/uan-header-common.cc