ns-3: ns3::lorawan::LoraTag Class Reference
ns3::lorawan::LoraTag Class Reference
Tag used to save various data about a packet, like its Spreading Factor and data about interference.
#include "lora-tag.h"
Public Member Functions
LoraTag (uint8_t sf=0, uint8_t destroyedBy=0)
Create a LoraTag with a given spreading factor and collision.
virtual ~LoraTag ()
virtual void Deserialize (TagBuffer i)
uint8_t GetDataRate (void)
Get the data rate for this packet.
uint8_t GetDestroyedBy () const
Read which Spreading Factor this packet was destroyed by.
double GetFrequency (void)
Get the frequency of the packet.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
double GetReceivePower () const
Read the power this packet arrived with.
virtual uint32_t GetSerializedSize () const
uint8_t GetSpreadingFactor () const
Read which Spreading Factor this packet was transmitted with.
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer i) const
void SetDataRate (uint8_t dataRate)
Set the data rate for this packet.
void SetDestroyedBy (uint8_t sf)
Set which Spreading Factor this packet was destroyed by.
void SetFrequency (double frequency)
Set the frequency of the packet.
void SetReceivePower (double receivePower)
Set the power this packet was received with.
void SetSpreadingFactor (uint8_t sf)
Set which Spreading Factor this packet was transmitted with.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_dataRate
The Data Rate that needs to be used to send this.
uint8_t m_destroyedBy
The Spreading Factor that destroyed the packet.
double m_frequency
packet.
double m_receivePower
The reception power of this packet.
uint8_t m_sf
The Spreading Factor used by the packet.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Tag used to save various data about a packet, like its Spreading Factor and data about interference.
Definition at line 33 of file lora-tag.h.
Constructor & Destructor Documentation
LoraTag()
ns3::lorawan::LoraTag::LoraTag (uint8_t sf = 0, uint8_t destroyedBy = 0)
Create a LoraTag with a given spreading factor and collision.
Parameters
sf The Spreading Factor.
destroyedBy The SF this tag's packet was destroyed by.
Definition at line 47 of file lora-tag.cc.
~LoraTag()
ns3::lorawan::LoraTag::~LoraTag () virtual
Definition at line 56 of file lora-tag.cc.
Member Function Documentation
Deserialize()
void ns3::lorawan::LoraTag::Deserialize (TagBuffer i) virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 79 of file lora-tag.cc.
References m_dataRate, m_destroyedBy, m_frequency, m_receivePower, m_sf, ns3::TagBuffer::ReadDouble(), and ns3::TagBuffer::ReadU8().
GetDataRate()
uint8_t ns3::lorawan::LoraTag::GetDataRate (void)
Get the data rate for this packet.
Returns
The data rate that needs to be employed for this packet.
Definition at line 144 of file lora-tag.cc.
References m_dataRate.
Referenced by ns3::lorawan::GatewayLorawanMac::Send().
GetDestroyedBy()
uint8_t ns3::lorawan::LoraTag::GetDestroyedBy () const
Read which Spreading Factor this packet was destroyed by.
Returns
The SF this packet was destroyed by.
Definition at line 102 of file lora-tag.cc.
References m_destroyedBy.
GetFrequency()
double ns3::lorawan::LoraTag::GetFrequency (void)
Get the frequency of the packet.
Definition at line 138 of file lora-tag.cc.
References m_frequency.
Referenced by ns3::lorawan::EndDeviceStatus::InsertReceivedPacket(), and ns3::lorawan::GatewayLorawanMac::Send().
GetInstanceTypeId()
TypeId ns3::lorawan::LoraTag::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 42 of file lora-tag.cc.
References GetTypeId().
GetReceivePower()
double ns3::lorawan::LoraTag::GetReceivePower () const
Read the power this packet arrived with.
Returns
This tag's packet received power.
Definition at line 108 of file lora-tag.cc.
References m_receivePower.
Referenced by ns3::lorawan::EndDeviceStatus::InsertReceivedPacket().
GetSerializedSize()
uint32_t ns3::lorawan::LoraTag::GetSerializedSize () const virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 61 of file lora-tag.cc.
GetSpreadingFactor()
uint8_t ns3::lorawan::LoraTag::GetSpreadingFactor () const
Read which Spreading Factor this packet was transmitted with.
Returns
This tag's packet's SF.
Definition at line 96 of file lora-tag.cc.
References m_sf.
Referenced by ns3::lorawan::EndDeviceStatus::InsertReceivedPacket().
GetTypeId()
TypeId ns3::lorawan::LoraTag::GetTypeId (void) static
Definition at line 31 of file lora-tag.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::lorawan::LoraTag::Print (std::ostream & os) const virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 89 of file lora-tag.cc.
References m_dataRate, m_destroyedBy, m_receivePower, and m_sf.
Serialize()
void ns3::lorawan::LoraTag::Serialize (TagBuffer i) const virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 69 of file lora-tag.cc.
References m_dataRate, m_destroyedBy, m_frequency, m_receivePower, m_sf, ns3::TagBuffer::WriteDouble(), and ns3::TagBuffer::WriteU8().
SetDataRate()
void ns3::lorawan::LoraTag::SetDataRate (uint8_t dataRate)
Set the data rate for this packet.
Parameters
dataRate The data rate.
Definition at line 150 of file lora-tag.cc.
References m_dataRate.
Referenced by ns3::lorawan::NetworkStatus::GetReplyForDevice().
SetDestroyedBy()
void ns3::lorawan::LoraTag::SetDestroyedBy (uint8_t sf)
Set which Spreading Factor this packet was destroyed by.
Parameters
sf The Spreading Factor.
Definition at line 114 of file lora-tag.cc.
References m_destroyedBy.
Referenced by ns3::lorawan::SimpleGatewayLoraPhy::EndReceive().
SetFrequency()
void ns3::lorawan::LoraTag::SetFrequency (double frequency)
Set the frequency of the packet.
This value works in two ways:
It is used by the GW to signal to the NS the frequency of the uplink packet
It is used by the NS to signal to the GW the freqeuncy of a downlink packet
Definition at line 132 of file lora-tag.cc.
References m_frequency.
Referenced by ns3::lorawan::SimpleGatewayLoraPhy::EndReceive(), and ns3::lorawan::NetworkStatus::GetReplyForDevice().
SetReceivePower()
void ns3::lorawan::LoraTag::SetReceivePower (double receivePower)
Set the power this packet was received with.
Parameters
receivePower The power, in dBm.
Definition at line 126 of file lora-tag.cc.
References m_receivePower.
Referenced by ns3::lorawan::SimpleGatewayLoraPhy::EndReceive().
SetSpreadingFactor()
void ns3::lorawan::LoraTag::SetSpreadingFactor (uint8_t sf)
Set which Spreading Factor this packet was transmitted with.
Parameters
sf The Spreading Factor.
Definition at line 120 of file lora-tag.cc.
References m_sf.
Referenced by ns3::lorawan::SimpleEndDeviceLoraPhy::Send().
Member Data Documentation
m_dataRate
uint8_t ns3::lorawan::LoraTag::m_dataRate private
The Data Rate that needs to be used to send this.
Definition at line 130 of file lora-tag.h.
Referenced by Deserialize(), GetDataRate(), Print(), Serialize(), and SetDataRate().
m_destroyedBy
uint8_t ns3::lorawan::LoraTag::m_destroyedBy private
The Spreading Factor that destroyed the packet.
Definition at line 128 of file lora-tag.h.
Referenced by Deserialize(), GetDestroyedBy(), Print(), Serialize(), and SetDestroyedBy().
m_frequency
double ns3::lorawan::LoraTag::m_frequency private
packet.
The frequency of this packet
Definition at line 132 of file lora-tag.h.
Referenced by Deserialize(), GetFrequency(), Serialize(), and SetFrequency().
m_receivePower
double ns3::lorawan::LoraTag::m_receivePower private
The reception power of this packet.
Definition at line 129 of file lora-tag.h.
Referenced by Deserialize(), GetReceivePower(), Print(), Serialize(), and SetReceivePower().
m_sf
uint8_t ns3::lorawan::LoraTag::m_sf private
The Spreading Factor used by the packet.
Definition at line 127 of file lora-tag.h.
Referenced by Deserialize(), GetSpreadingFactor(), Print(), Serialize(), and SetSpreadingFactor().
The documentation for this class was generated from the following files:
src/lorawan/model/lora-tag.h
src/lorawan/model/lora-tag.cc