ns-3: TcpHyblaIncrementTest Class Reference
TcpHyblaIncrementTest Class Reference
Internet » internet module tests | Test suites
Testing the congestion avoidance increment on TcpHybla.
Public Member Functions
TcpHyblaIncrementTest (uint32_t cWnd, uint32_t ssThresh, uint32_t segmentSize, const Time &rtt, const std::string &name)
Constructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void RhoUpdated (double oldVal, double newVal)
Tracks TCP Hybla rho parameter changes.
Private Attributes
uint32_t m_cWnd
Congestion window.
double m_rho
TCP Hybla rho parameter.
Time m_rtt
Round trip time.
uint32_t m_segmentSize
Segment size.
uint32_t m_ssThresh
Slow Start Threshold.
Ptr< TcpSocketState > m_state
TCP socket state.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Testing the congestion avoidance increment on TcpHybla.
Definition at line 36 of file tcp-hybla-test.cc.
Constructor & Destructor Documentation
TcpHyblaIncrementTest()
TcpHyblaIncrementTest::TcpHyblaIncrementTest (uint32_t cWnd, uint32_t ssThresh, uint32_t segmentSize, const Time & rtt, const std::string & name)
Constructor.
Parameters
cWnd Congestion window.
ssThresh Slow Start Threshold.
segmentSize Segment size.
rtt Round trip time.
name Test description.
Definition at line 69 of file tcp-hybla-test.cc.
Member Function Documentation
DoRun()
void TcpHyblaIncrementTest::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 89 of file tcp-hybla-test.cc.
References ns3::TimeValue::Get(), ns3::TracedValue< T >::Get(), ns3::ObjectBase::GetAttribute(), ns3::Time::GetSeconds(), ns3::TcpNewReno::IncreaseWindow(), ns3::TcpSocketState::m_cWnd, m_cWnd, ns3::TcpSocketState::m_minRtt, m_rho, m_rtt, ns3::TcpSocketState::m_segmentSize, m_segmentSize, ns3::TcpSocketState::m_ssThresh, m_ssThresh, m_state, ns3::MakeCallback(), max, NS_TEST_ASSERT_MSG_EQ, NS_TEST_ASSERT_MSG_EQ_TOL, NS_TEST_ASSERT_MSG_LT_OR_EQ, NS_TEST_ASSERT_MSG_NE, ns3::TcpHybla::PktsAcked(), RhoUpdated(), and ns3::ObjectBase::TraceConnectWithoutContext().
RhoUpdated()
void TcpHyblaIncrementTest::RhoUpdated (double oldVal, double newVal) private
Tracks TCP Hybla rho parameter changes.
Parameters
oldVal Previous value.
newVal Actual value.
Definition at line 82 of file tcp-hybla-test.cc.
References m_rho, and NS_UNUSED.
Referenced by DoRun().
Member Data Documentation
m_cWnd
uint32_t TcpHyblaIncrementTest::m_cWnd private
Congestion window.
Definition at line 61 of file tcp-hybla-test.cc.
Referenced by DoRun().
m_rho
double TcpHyblaIncrementTest::m_rho private
TCP Hybla rho parameter.
Definition at line 65 of file tcp-hybla-test.cc.
Referenced by DoRun(), and RhoUpdated().
m_rtt
Time TcpHyblaIncrementTest::m_rtt private
Round trip time.
Definition at line 64 of file tcp-hybla-test.cc.
Referenced by DoRun().
m_segmentSize
uint32_t TcpHyblaIncrementTest::m_segmentSize private
Segment size.
Definition at line 63 of file tcp-hybla-test.cc.
Referenced by DoRun().
m_ssThresh
uint32_t TcpHyblaIncrementTest::m_ssThresh private
Slow Start Threshold.
Definition at line 62 of file tcp-hybla-test.cc.
Referenced by DoRun().
m_state
Ptr<TcpSocketState> TcpHyblaIncrementTest::m_state private
TCP socket state.
Definition at line 66 of file tcp-hybla-test.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/internet/test/tcp-hybla-test.cc