ns-3: ns3::NetDevice Class Reference
ns3::NetDevice Class Reference abstract
Network » Network Device
Network layer to device interface.
#include "net-device.h"
Public Types
typedef void(* LinkChangeTracedCallback) (void)
TracedCallback signature for link changed event.
enum PacketType {
PACKET_HOST = 1, NS3_PACKET_HOST = PACKET_HOST, PACKET_BROADCAST, NS3_PACKET_BROADCAST = PACKET_BROADCAST,
PACKET_MULTICAST, NS3_PACKET_MULTICAST = PACKET_MULTICAST, PACKET_OTHERHOST, NS3_PACKET_OTHERHOST = PACKET_OTHERHOST
}
Packet types are used as they are in Linux.
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address &, const Address &, enum PacketType > PromiscReceiveCallback
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address & > ReceiveCallback
Public Member Functions
virtual ~NetDevice ()
virtual void AddLinkChangeCallback (Callback< void > callback)=0
virtual Address GetAddress (void) const =0
virtual Address GetBroadcast (void) const =0
virtual Ptr< Channel > GetChannel (void) const =0
virtual uint32_t GetIfIndex (void) const =0
virtual uint16_t GetMtu (void) const =0
virtual Address GetMulticast (Ipv4Address multicastGroup) const =0
Make and return a MAC multicast address using the provided multicast group.
virtual Address GetMulticast (Ipv6Address addr) const =0
Get the MAC multicast address corresponding to the IPv6 address provided.
virtual Ptr< Node > GetNode (void) const =0
virtual bool IsBridge (void) const =0
Return true if the net device is acting as a bridge.
virtual bool IsBroadcast (void) const =0
virtual bool IsLinkUp (void) const =0
virtual bool IsMulticast (void) const =0
virtual bool IsPointToPoint (void) const =0
Return true if the net device is on a point-to-point link.
virtual bool NeedsArp (void) const =0
virtual bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)=0
virtual bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)=0
virtual void SetAddress (Address address)=0
Set the address of this interface.
virtual void SetIfIndex (const uint32_t index)=0
virtual bool SetMtu (const uint16_t mtu)=0
virtual void SetNode (Ptr< Node > node)=0
virtual void SetPromiscReceiveCallback (PromiscReceiveCallback cb)=0
virtual void SetReceiveCallback (ReceiveCallback cb)=0
virtual bool SupportsSendFrom (void) const =0
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Network layer to device interface.
This interface defines the API which the IP and ARP layers need to access to manage an instance of a network device layer. It currently does not support MAC-level multicast but this should not be too hard to add by adding extra methods to register MAC multicast addresses to filter out unwanted packets before handing them to the higher layers.
In Linux, this interface is analogous to the interface just above dev_queue_xmit() (i.e., IP packet is fully constructed with destination MAC address already selected).
If you want to write a new MAC layer, you need to subclass this base class and implement your own version of the pure virtual methods in this class.
This class was designed to hide as many MAC-level details as possible from the perspective of layer 3 to allow a single layer 3 to work with any kind of MAC layer. Specifically, this class encapsulates the specific format of MAC addresses used by a device such that the layer 3 does not need any modification to handle new address formats. This means obviously that the NetDevice class must know about the address format of all potential layer 3 protocols through its GetMulticast methods: the current API has been optimized to make it easy to add new MAC protocols, not to add new layer 3 protocols.
Devices aiming to support flow control and dynamic queue limits must perform the following operations:
in the NotifyNewAggregate method
cache the pointer to the netdevice queue interface aggregated to the device
set the select queue callback through the netdevice queue interface, if the device is multi-queue
anytime before initialization
set the number of device transmission queues (and optionally create them) through the netdevice queue interface, if the device is multi-queue
when the device queues have been created, invoke NetDeviceQueueInterface::ConnectQueueTraces, which
connects the Enqueue traced callback of the device queues to the PacketEnqueued static method of the NetDeviceQueue class
connects the Dequeue and DropAfterDequeue traced callback of the device queues to the PacketDequeued static method of the NetDeviceQueue class
connects the DropBeforeEnqueue traced callback of the device queues to the PacketDiscarded static method of the NetDeviceQueue class
Definition at line 95 of file net-device.h.
Member Typedef Documentation
LinkChangeTracedCallback
typedef void(* ns3::NetDevice::LinkChangeTracedCallback) (void)
TracedCallback signature for link changed event.
Definition at line 156 of file net-device.h.
PromiscReceiveCallback
typedef Callback< bool, Ptr<NetDevice>, Ptr<const Packet>, uint16_t, const Address &, const Address &, enum PacketType > ns3::NetDevice::PromiscReceiveCallback
Parameters
device a pointer to the net device which is calling this callback
packet the packet received
protocol the 16 bit protocol number associated with this packet. This protocol number is expected to be the same protocol number given to the Send method by the user on the sender side.
sender the address of the sender
receiver the address of the receiver
packetType type of packet received (broadcast/multicast/unicast/otherhost)
Returns
true if the callback could handle the packet successfully, false otherwise.
Definition at line 343 of file net-device.h.
ReceiveCallback
typedef Callback< bool, Ptr<NetDevice>, Ptr<const Packet>, uint16_t, const Address & > ns3::NetDevice::ReceiveCallback
Parameters
device a pointer to the net device which is calling this callback
packet the packet received
protocol the 16 bit protocol number associated with this packet. This protocol number is expected to be the same protocol number given to the Send method by the user on the sender side.
sender the address of the sender
Returns
true if the callback could handle the packet successfully, false otherwise.
Definition at line 318 of file net-device.h.
Member Enumeration Documentation
PacketType
enum ns3::NetDevice::PacketType
Packet types are used as they are in Linux.
GCC name resolution on typedef enum {} PacketType is broken for the foreseeable future, so if you need to use ns-3 PacketType in a driver that also uses the Linux packet types you're hosed unless we define a shadow type, which we do here.
Enumerator
PACKET_HOST
Packet addressed oo us.
NS3_PACKET_HOST
PACKET_BROADCAST
Packet addressed to all.
NS3_PACKET_BROADCAST
PACKET_MULTICAST
Packet addressed to multicast group.
NS3_PACKET_MULTICAST
PACKET_OTHERHOST
Packet addressed to someone else.
NS3_PACKET_OTHERHOST
Definition at line 296 of file net-device.h.
Constructor & Destructor Documentation
~NetDevice()
ns3::NetDevice::~NetDevice () virtual
Definition at line 39 of file net-device.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddLinkChangeCallback()
virtual void ns3::NetDevice::AddLinkChangeCallback (Callback< void > callback) pure virtual
Parameters
callback the callback to invoke
Add a callback invoked whenever the link status changes to UP. This callback is typically used by the IP/ARP layer to flush the ARP cache and by IPv6 stack to flush NDISC cache whenever the link goes up.
Implemented in ns3::WimaxNetDevice, ns3::WifiNetDevice, ns3::WaveNetDevice, ns3::VirtualNetDevice, ns3::UanNetDevice, ns3::TapBridge, ns3::NonCommunicatingNetDevice, ns3::AlohaNoackNetDevice, ns3::SixLowPanNetDevice, ns3::PointToPointNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::SimpleNetDevice, ns3::MeshPointDevice, ns3::LteNetDevice, ns3::LrWpanNetDevice, ns3::lorawan::LoraNetDevice, ns3::LoopbackNetDevice, ns3::FdNetDevice, ns3::CsmaNetDevice, and ns3::BridgeNetDevice.
GetAddress()
virtual Address ns3::NetDevice::GetAddress (void) const pure virtual
Returns
the current Address of this interface.
Implemented in ns3::WimaxNetDevice, ns3::WifiNetDevice, ns3::WaveNetDevice, ns3::VirtualNetDevice, ns3::UanNetDevice, ns3::TapBridge, ns3::NonCommunicatingNetDevice, ns3::AlohaNoackNetDevice, ns3::SixLowPanNetDevice, ns3::PointToPointNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::SimpleNetDevice, ns3::LteNetDevice, ns3::LrWpanNetDevice, ns3::lorawan::LoraNetDevice, ns3::LoopbackNetDevice, ns3::FdNetDevice, ns3::CsmaNetDevice, ns3::BridgeNetDevice, and ns3::MeshPointDevice.
Referenced by ns3::aodv::RoutingProtocol::RouteInput(), and ns3::dsdv::RoutingProtocol::RouteInput().
GetBroadcast()
virtual Address ns3::NetDevice::GetBroadcast (void) const pure virtual
Returns
the broadcast address supported by this netdevice.
Calling this method is invalid if IsBroadcast returns not true.
Implemented in ns3::WimaxNetDevice, ns3::WifiNetDevice, ns3::WaveNetDevice, ns3::VirtualNetDevice, ns3::UanNetDevice, ns3::TapBridge, ns3::NonCommunicatingNetDevice, ns3::AlohaNoackNetDevice, ns3::SixLowPanNetDevice, ns3::PointToPointNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::SimpleNetDevice, ns3::LteNetDevice, ns3::LrWpanNetDevice, ns3::lorawan::LoraNetDevice, ns3::LoopbackNetDevice, ns3::FdNetDevice, ns3::CsmaNetDevice, ns3::BridgeNetDevice, and ns3::MeshPointDevice.
GetChannel()
virtual Ptr<Channel> ns3::NetDevice::GetChannel (void) const pure virtual
Returns
the channel this NetDevice is connected to. The value returned can be zero if the NetDevice is not yet connected to any channel or if the underlying NetDevice has no concept of a channel. i.e., callers must check for zero and be ready to handle it.
Implemented in ns3::WimaxNetDevice, ns3::WifiNetDevice, ns3::WaveNetDevice, ns3::VirtualNetDevice, ns3::UanNetDevice, ns3::TapBridge, ns3::NonCommunicatingNetDevice, ns3::AlohaNoackNetDevice, ns3::SixLowPanNetDevice, ns3::PointToPointNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::SimpleNetDevice, ns3::LteNetDevice, ns3::LrWpanNetDevice, ns3::lorawan::LoraNetDevice, ns3::LoopbackNetDevice, ns3::FdNetDevice, ns3::CsmaNetDevice, ns3::BridgeNetDevice, and ns3::MeshPointDevice.
GetIfIndex()
virtual uint32_t ns3::NetDevice::GetIfIndex (void) const pure virtual
Returns
index ifIndex of the device
Implemented in ns3::WimaxNetDevice, ns3::WifiNetDevice, ns3::WaveNetDevice, ns3::VirtualNetDevice, ns3::UanNetDevice, ns3::TapBridge, ns3::NonCommunicatingNetDevice, ns3::AlohaNoackNetDevice, ns3::SixLowPanNetDevice, ns3::PointToPointNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::SimpleNetDevice, ns3::LteNetDevice, ns3::LrWpanNetDevice, ns3::lorawan::LoraNetDevice, ns3::LoopbackNetDevice, ns3::FdNetDevice, ns3::CsmaNetDevice, ns3::BridgeNetDevice, and ns3::MeshPointDevice.
GetMtu()
virtual uint16_t ns3::NetDevice::GetMtu (void) const pure virtual
Returns
the link-level MTU in bytes for this interface.
This value is typically used by the IP layer to perform IP fragmentation when needed.
Implemented in ns3::WimaxNetDevice, ns3::WifiNetDevice, ns3::WaveNetDevice, ns3::VirtualNetDevice, ns3::UanNetDevice, ns3::TapBridge, ns3::NonCommunicatingNetDevice, ns3::AlohaNoackNetDevice, ns3::SixLowPanNetDevice, ns3::PointToPointNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::SimpleNetDevice, ns3::LteNetDevice, ns3::LrWpanNetDevice, ns3::lorawan::LoraNetDevice, ns3::LoopbackNetDevice, ns3::FdNetDevice, ns3::CsmaNetDevice, ns3::BridgeNetDevice, and ns3::MeshPointDevice.
GetMulticast() [1/2]
virtual Address ns3::NetDevice::GetMulticast (Ipv4Address multicastGroup) const pure virtual
Make and return a MAC multicast address using the provided multicast group.
RFC 1112 says that an Ipv4 host group address is mapped to an Ethernet multicast address by placing the low-order 23-bits of the IP address into the low-order 23 bits of the Ethernet multicast address 01-00-5E-00-00-00 (hex). Similar RFCs exist for Ipv6 and Eui64 mappings. This method performs the multicast address creation function appropriate to the underlying MAC address of the device. This MAC address is encapsulated in an abstract Address to avoid dependencies on the exact MAC address format.
In the case of net devices that do not support multicast, clients are expected to test NetDevice::IsMulticast and avoid attempting to map multicast packets. Subclasses of NetDevice that do support multicasting are expected to override this method and provide an implementation appropriate to the particular device.
Parameters
multicastGroup The IP address for the multicast group destination of the packet.
Returns
The MAC multicast Address used to send packets to the provided multicast group.
Warning
Calling this method is invalid if IsMulticast returns not true.
See also
IsMulticast()
Implemented in ns3::WimaxNetDevice, ns3::WifiNetDevice, ns3::WaveNetDevice, ns3::VirtualNetDevice, ns3::UanNetDevice, ns3::TapBridge, ns3::SixLowPanNetDevice, ns3::PointToPointNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::SimpleNetDevice, ns3::MeshPointDevice, ns3::LrWpanNetDevice, ns3::lorawan::LoraNetDevice, ns3::LoopbackNetDevice, ns3::FdNetDevice, ns3::CsmaNetDevice, ns3::BridgeNetDevice, ns3::NonCommunicatingNetDevice, ns3::AlohaNoackNetDevice, and ns3::LteNetDevice.
GetMulticast() [2/2]
virtual Address ns3::NetDevice::GetMulticast (Ipv6Address addr) const pure virtual
Get the MAC multicast address corresponding to the IPv6 address provided.
Parameters
addr IPv6 address
Returns
the MAC multicast address
Warning
Calling this method is invalid if IsMulticast returns not true.
Implemented in ns3::WimaxNetDevice, ns3::WifiNetDevice, ns3::WaveNetDevice, ns3::VirtualNetDevice, ns3::UanNetDevice, ns3::TapBridge, ns3::NonCommunicatingNetDevice, ns3::AlohaNoackNetDevice, ns3::SixLowPanNetDevice, ns3::PointToPointNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::SimpleNetDevice, ns3::MeshPointDevice, ns3::LteNetDevice, ns3::LrWpanNetDevice, ns3::lorawan::LoraNetDevice, ns3::LoopbackNetDevice, ns3::FdNetDevice, ns3::CsmaNetDevice, and ns3::BridgeNetDevice.
GetNode()
virtual Ptr<Node> ns3::NetDevice::GetNode (void) const pure virtual
Returns
the node base class which contains this network interface.
When a subclass needs to get access to the underlying node base class to print the nodeid for example, it can invoke this method.
Implemented in ns3::WimaxNetDevice, ns3::WifiNetDevice, ns3::WaveNetDevice, ns3::VirtualNetDevice, ns3::UanNetDevice, ns3::TapBridge, ns3::NonCommunicatingNetDevice, ns3::AlohaNoackNetDevice, ns3::SixLowPanNetDevice, ns3::PointToPointNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::SimpleNetDevice, ns3::LteNetDevice, ns3::LrWpanNetDevice, ns3::lorawan::LoraNetDevice, ns3::LoopbackNetDevice, ns3::FdNetDevice, ns3::CsmaNetDevice, ns3::BridgeNetDevice, and ns3::MeshPointDevice.
Referenced by TcFlowControlTestCase::CheckPacketsInQueueDisc(), DoBeamforming(), ThreeGppSpectrumPropagationLossModelTest::DoBeamforming(), ns3::AnimationInterface::OutputCsmaPacket(), ns3::AnimationInterface::OutputWirelessPacketRxInfo(), ns3::AnimationInterface::OutputWirelessPacketTxInfo(), ns3::AnimationInterface::AnimPacketInfo::ProcessRxBegin(), and ChannelAccessTestCase::Receive().
GetTypeId()
TypeId ns3::NetDevice::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 30 of file net-device.cc.
References ns3::TypeId::SetParent().
IsBridge()
virtual bool ns3::NetDevice::IsBridge (void) const pure virtual
Return true if the net device is acting as a bridge.
Returns
value of m_isBridge flag
Implemented in ns3::WimaxNetDevice, ns3::WifiNetDevice, ns3::WaveNetDevice, ns3::VirtualNetDevice, ns3::UanNetDevice, ns3::TapBridge, ns3::NonCommunicatingNetDevice, ns3::AlohaNoackNetDevice, ns3::SixLowPanNetDevice, ns3::PointToPointNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::SimpleNetDevice, ns3::LteNetDevice, ns3::LrWpanNetDevice, ns3::lorawan::LoraNetDevice, ns3::LoopbackNetDevice, ns3::FdNetDevice, ns3::CsmaNetDevice, ns3::BridgeNetDevice, and ns3::MeshPointDevice.
IsBroadcast()
virtual bool ns3::NetDevice::IsBroadcast (void) const pure virtual
Returns
true if this interface supports a broadcast address, false otherwise.
Implemented in ns3::WimaxNetDevice, ns3::WifiNetDevice, ns3::WaveNetDevice, ns3::VirtualNetDevice, ns3::UanNetDevice, ns3::TapBridge, ns3::NonCommunicatingNetDevice, ns3::AlohaNoackNetDevice, ns3::SixLowPanNetDevice, ns3::PointToPointNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::SimpleNetDevice, ns3::LteNetDevice, ns3::LrWpanNetDevice, ns3::lorawan::LoraNetDevice, ns3::LoopbackNetDevice, ns3::FdNetDevice, ns3::CsmaNetDevice, ns3::BridgeNetDevice, and ns3::MeshPointDevice.
IsLinkUp()
virtual bool ns3::NetDevice::IsLinkUp (void) const pure virtual
Returns
true if link is up; false otherwise
Implemented in ns3::WimaxNetDevice, ns3::WifiNetDevice, ns3::WaveNetDevice, ns3::VirtualNetDevice, ns3::UanNetDevice, ns3::TapBridge, ns3::NonCommunicatingNetDevice, ns3::AlohaNoackNetDevice, ns3::SixLowPanNetDevice, ns3::PointToPointNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::SimpleNetDevice, ns3::LteNetDevice, ns3::LrWpanNetDevice, ns3::lorawan::LoraNetDevice, ns3::LoopbackNetDevice, ns3::FdNetDevice, ns3::CsmaNetDevice, ns3::BridgeNetDevice, and ns3::MeshPointDevice.
IsMulticast()
virtual bool ns3::NetDevice::IsMulticast (void) const pure virtual
Returns
value of m_isMulticast flag
Implemented in ns3::WimaxNetDevice, ns3::WifiNetDevice, ns3::WaveNetDevice, ns3::VirtualNetDevice, ns3::UanNetDevice, ns3::TapBridge, ns3::NonCommunicatingNetDevice, ns3::AlohaNoackNetDevice, ns3::SixLowPanNetDevice, ns3::PointToPointNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::SimpleNetDevice, ns3::LteNetDevice, ns3::LrWpanNetDevice, ns3::lorawan::LoraNetDevice, ns3::LoopbackNetDevice, ns3::FdNetDevice, ns3::CsmaNetDevice, ns3::BridgeNetDevice, and ns3::MeshPointDevice.
IsPointToPoint()
virtual bool ns3::NetDevice::IsPointToPoint (void) const pure virtual
Return true if the net device is on a point-to-point link.
Returns
value of m_isPointToPoint flag
Implemented in ns3::WimaxNetDevice, ns3::WifiNetDevice, ns3::WaveNetDevice, ns3::VirtualNetDevice, ns3::UanNetDevice, ns3::TapBridge, ns3::NonCommunicatingNetDevice, ns3::AlohaNoackNetDevice, ns3::SixLowPanNetDevice, ns3::PointToPointNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::SimpleNetDevice, ns3::LteNetDevice, ns3::LrWpanNetDevice, ns3::lorawan::LoraNetDevice, ns3::LoopbackNetDevice, ns3::FdNetDevice, ns3::CsmaNetDevice, ns3::BridgeNetDevice, and ns3::MeshPointDevice.
NeedsArp()
virtual bool ns3::NetDevice::NeedsArp (void) const pure virtual
Returns
true if ARP is needed, false otherwise.
Called by higher-layers to check if this NetDevice requires ARP to be used.
Implemented in ns3::WimaxNetDevice, ns3::WifiNetDevice, ns3::WaveNetDevice, ns3::VirtualNetDevice, ns3::UanNetDevice, ns3::TapBridge, ns3::NonCommunicatingNetDevice, ns3::AlohaNoackNetDevice, ns3::SixLowPanNetDevice, ns3::PointToPointNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::SimpleNetDevice, ns3::LteNetDevice, ns3::LrWpanNetDevice, ns3::lorawan::LoraNetDevice, ns3::LoopbackNetDevice, ns3::FdNetDevice, ns3::CsmaNetDevice, ns3::BridgeNetDevice, and ns3::MeshPointDevice.
Send()
virtual bool ns3::NetDevice::Send (Ptr< Packet > packet, const Address & dest, uint16_t protocolNumber) pure virtual
Parameters
packet packet sent from above down to Network Device
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device to the specified destination Address
Returns
whether the Send operation succeeded
Implemented in ns3::WimaxNetDevice, ns3::WifiNetDevice, ns3::WaveNetDevice, ns3::VirtualNetDevice, ns3::UanNetDevice, ns3::TapBridge, ns3::NonCommunicatingNetDevice, ns3::AlohaNoackNetDevice, ns3::SixLowPanNetDevice, ns3::PointToPointNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::SimpleNetDevice, ns3::MeshPointDevice, ns3::LteSimpleNetDevice, ns3::LteUeNetDevice, ns3::LteEnbNetDevice, ns3::LrWpanNetDevice, ns3::lorawan::LoraNetDevice, ns3::LoopbackNetDevice, ns3::FdNetDevice, ns3::CsmaNetDevice, and ns3::BridgeNetDevice.
Referenced by ns3::SixLowPanNetDevice::ReceiveFromDevice(), SendPacket(), Bug2470TestCase::SendPacketBurst(), Bug2843TestCase::SendPacketBurst(), Issue40TestCase::SendPackets(), and Issue169TestCase::SendPackets().
SendFrom()
virtual bool ns3::NetDevice::SendFrom (Ptr< Packet > packet, const Address & source, const Address & dest, uint16_t protocolNumber) pure virtual
Parameters
packet packet sent from above down to Network Device
source source mac address (so called "MAC spoofing")
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device with the specified source and destination Addresses.
Returns
whether the Send operation succeeded
Implemented in ns3::WimaxNetDevice, ns3::WifiNetDevice, ns3::WaveNetDevice, ns3::VirtualNetDevice, ns3::UanNetDevice, ns3::TapBridge, ns3::NonCommunicatingNetDevice, ns3::AlohaNoackNetDevice, ns3::SixLowPanNetDevice, ns3::PointToPointNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::SimpleNetDevice, ns3::MeshPointDevice, ns3::LteNetDevice, ns3::LrWpanNetDevice, ns3::lorawan::LoraNetDevice, ns3::LoopbackNetDevice, ns3::FdNetDevice, ns3::CsmaNetDevice, and ns3::BridgeNetDevice.
SetAddress()
virtual void ns3::NetDevice::SetAddress (Address address) pure virtual
Set the address of this interface.
Parameters
address address to set
Implemented in ns3::WimaxNetDevice, ns3::WifiNetDevice, ns3::WaveNetDevice, ns3::VirtualNetDevice, ns3::UanNetDevice, ns3::TapBridge, ns3::NonCommunicatingNetDevice, ns3::AlohaNoackNetDevice, ns3::SixLowPanNetDevice, ns3::PointToPointNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::SimpleNetDevice, ns3::LteNetDevice, ns3::LrWpanNetDevice, ns3::lorawan::LoraNetDevice, ns3::LoopbackNetDevice, ns3::FdNetDevice, ns3::CsmaNetDevice, ns3::BridgeNetDevice, and ns3::MeshPointDevice.
SetIfIndex()
virtual void ns3::NetDevice::SetIfIndex (const uint32_t index) pure virtual
Parameters
index ifIndex of the device
Implemented in ns3::WimaxNetDevice, ns3::WifiNetDevice, ns3::WaveNetDevice, ns3::VirtualNetDevice, ns3::UanNetDevice, ns3::TapBridge, ns3::NonCommunicatingNetDevice, ns3::AlohaNoackNetDevice, ns3::SixLowPanNetDevice, ns3::PointToPointNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::SimpleNetDevice, ns3::MeshPointDevice, ns3::LteNetDevice, ns3::LrWpanNetDevice, ns3::lorawan::LoraNetDevice, ns3::LoopbackNetDevice, ns3::FdNetDevice, ns3::CsmaNetDevice, and ns3::BridgeNetDevice.
SetMtu()
virtual bool ns3::NetDevice::SetMtu (const uint16_t mtu) pure virtual
Parameters
mtu MTU value, in bytes, to set for the device
Returns
whether the MTU value was within legal bounds
Override for default MTU defined on a per-type basis.
Implemented in ns3::WimaxNetDevice, ns3::WifiNetDevice, ns3::WaveNetDevice, ns3::VirtualNetDevice, ns3::UanNetDevice, ns3::TapBridge, ns3::NonCommunicatingNetDevice, ns3::AlohaNoackNetDevice, ns3::SixLowPanNetDevice, ns3::PointToPointNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::SimpleNetDevice, ns3::MeshPointDevice, ns3::LteNetDevice, ns3::LrWpanNetDevice, ns3::lorawan::LoraNetDevice, ns3::LoopbackNetDevice, ns3::FdNetDevice, ns3::CsmaNetDevice, and ns3::BridgeNetDevice.
Referenced by TcFlowControlTestCase::DoRun().
SetNode()
virtual void ns3::NetDevice::SetNode (Ptr< Node > node) pure virtual
Parameters
node the node associated to this netdevice.
This method is called from ns3::Node::AddDevice.
Implemented in ns3::WimaxNetDevice, ns3::WaveNetDevice, ns3::VirtualNetDevice, ns3::UanNetDevice, ns3::TapBridge, ns3::NonCommunicatingNetDevice, ns3::AlohaNoackNetDevice, ns3::SixLowPanNetDevice, ns3::PointToPointNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::SimpleNetDevice, ns3::MeshPointDevice, ns3::LteNetDevice, ns3::LrWpanNetDevice, ns3::lorawan::LoraNetDevice, ns3::LoopbackNetDevice, ns3::FdNetDevice, ns3::CsmaNetDevice, ns3::BridgeNetDevice, and ns3::WifiNetDevice.
SetPromiscReceiveCallback()
virtual void ns3::NetDevice::SetPromiscReceiveCallback (PromiscReceiveCallback cb) pure virtual
Parameters
cb callback to invoke whenever a packet has been received in promiscuous mode and must be forwarded to the higher layers.
Enables netdevice promiscuous mode and sets the callback that will handle promiscuous mode packets. Note, promiscuous mode packets means all packets, including those packets that can be sensed by the netdevice but which are intended to be received by other hosts.
Implemented in ns3::WimaxNetDevice, ns3::WifiNetDevice, ns3::WaveNetDevice, ns3::UanNetDevice, ns3::NonCommunicatingNetDevice, ns3::AlohaNoackNetDevice, ns3::PointToPointNetDevice, ns3::SimpleNetDevice, ns3::LteNetDevice, ns3::LrWpanNetDevice, ns3::lorawan::LoraNetDevice, ns3::LoopbackNetDevice, ns3::CsmaNetDevice, ns3::VirtualNetDevice, ns3::TapBridge, ns3::SixLowPanNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::MeshPointDevice, ns3::FdNetDevice, and ns3::BridgeNetDevice.
SetReceiveCallback()
virtual void ns3::NetDevice::SetReceiveCallback (ReceiveCallback cb) pure virtual
Parameters
cb callback to invoke whenever a packet has been received and must be forwarded to the higher layers.
Set the callback to be used to notify higher layers when a packet has been received.
Implemented in ns3::WimaxNetDevice, ns3::WifiNetDevice, ns3::WaveNetDevice, ns3::VirtualNetDevice, ns3::UanNetDevice, ns3::TapBridge, ns3::NonCommunicatingNetDevice, ns3::AlohaNoackNetDevice, ns3::SixLowPanNetDevice, ns3::PointToPointNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::SimpleNetDevice, ns3::MeshPointDevice, ns3::LteNetDevice, ns3::LrWpanNetDevice, ns3::lorawan::LoraNetDevice, ns3::LoopbackNetDevice, ns3::FdNetDevice, ns3::CsmaNetDevice, and ns3::BridgeNetDevice.
Referenced by AcousticModemEnergyTestCase::DoRun().
SupportsSendFrom()
virtual bool ns3::NetDevice::SupportsSendFrom (void) const pure virtual
Returns
true if this interface supports a bridging mode, false otherwise.
Implemented in ns3::WimaxNetDevice, ns3::WifiNetDevice, ns3::WaveNetDevice, ns3::UanNetDevice, ns3::NonCommunicatingNetDevice, ns3::AlohaNoackNetDevice, ns3::PointToPointNetDevice, ns3::SimpleNetDevice, ns3::LteNetDevice, ns3::LrWpanNetDevice, ns3::lorawan::LoraNetDevice, ns3::LoopbackNetDevice, ns3::CsmaNetDevice, ns3::VirtualNetDevice, ns3::TapBridge, ns3::SixLowPanNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::MeshPointDevice, ns3::FdNetDevice, and ns3::BridgeNetDevice.
The documentation for this class was generated from the following files:
src/network/model/net-device.h
src/network/model/net-device.cc