ns-3: python-unit-tests.TestSimulator Class Reference
python-unit-tests.TestSimulator Class Reference
TestSimulator class.
Public Member Functions
def testAttributes (self)
Test attributes function.
def testCommandLine (self)
Test command line.
def testConfig (self)
Test configuration.
def testIdentity (self)
Test identify.
def testSchedule (self)
Test schedule.
def testScheduleDestroy (self)
Test schedule destroy.
def testScheduleNow (self)
Test schedule now.
def testScheduleWithContext (self)
Test schedule with context.
def testSocket (self)
Test socket.
def testSubclass (self)
Test subclass.
def testTimeComparison (self)
Test time comparison.
def testTimeNumericOperations (self)
Test numeric operations.
def testTypeId (self)
Test type ID.
Private Attributes
_args_received
_cb_time
_context_received
_received_packet
Detailed Description
TestSimulator class.
Definition at line 12 of file python-unit-tests.py.
Member Function Documentation
testAttributes()
def python-unit-tests.TestSimulator.testAttributes (self)
Test attributes function.
Parameters
self this object
Returns
none Yes, I know, the GetAttribute interface for Python is horrible, we should fix this soon, I hope.
Definition at line 169 of file python-unit-tests.py.
testCommandLine()
def python-unit-tests.TestSimulator.testCommandLine (self)
Test command line.
Parameters
self this object
Returns
none
Definition at line 223 of file python-unit-tests.py.
testConfig()
def python-unit-tests.TestSimulator.testConfig (self)
Test configuration.
Parameters
self this object
Returns
none
Definition at line 131 of file python-unit-tests.py.
testIdentity()
def python-unit-tests.TestSimulator.testIdentity (self)
Test identify.
Parameters
self this object
Returns
none
Definition at line 199 of file python-unit-tests.py.
testSchedule()
def python-unit-tests.TestSimulator.testSchedule (self)
Test schedule.
Parameters
self this object
Returns
none
Definition at line 42 of file python-unit-tests.py.
References python-unit-tests.TestSimulator._args_received, python-unit-tests.TestSimulator._cb_time, and ns3.Seconds().
testScheduleDestroy()
def python-unit-tests.TestSimulator.testScheduleDestroy (self)
Test schedule destroy.
Parameters
self this object
Returns
none
Definition at line 62 of file python-unit-tests.py.
References python-unit-tests.TestSimulator._args_received, python-unit-tests.TestSimulator._cb_time, and ns3.Seconds().
testScheduleNow()
def python-unit-tests.TestSimulator.testScheduleNow (self)
Test schedule now.
Parameters
self this object
Returns
none
Definition at line 22 of file python-unit-tests.py.
testScheduleWithContext()
def python-unit-tests.TestSimulator.testScheduleWithContext (self)
Test schedule with context.
Parameters
self this object
Returns
none
Definition at line 85 of file python-unit-tests.py.
testSocket()
def python-unit-tests.TestSimulator.testSocket (self)
Test socket.
Parameters
self
Returns
none
Definition at line 139 of file python-unit-tests.py.
testSubclass()
def python-unit-tests.TestSimulator.testSubclass (self)
Test subclass.
Parameters
self this object
Returns
none
Definition at line 248 of file python-unit-tests.py.
testTimeComparison()
def python-unit-tests.TestSimulator.testTimeComparison (self)
Test time comparison.
Parameters
self this object
Returns
none
Definition at line 109 of file python-unit-tests.py.
References ns3.Seconds().
testTimeNumericOperations()
def python-unit-tests.TestSimulator.testTimeNumericOperations (self)
Test numeric operations.
Parameters
self this object
Returns
none
Definition at line 120 of file python-unit-tests.py.
References ns3.Seconds().
testTypeId()
def python-unit-tests.TestSimulator.testTypeId (self)
Test type ID.
Parameters
self this object
Returns
none
Definition at line 213 of file python-unit-tests.py.
Member Data Documentation
_args_received
python-unit-tests.TestSimulator._args_received private
args
Definition at line 32 of file python-unit-tests.py.
Referenced by python-unit-tests.TestSimulator.testSchedule(), and python-unit-tests.TestSimulator.testScheduleDestroy().
_cb_time
python-unit-tests.TestSimulator._cb_time private
current time
Definition at line 33 of file python-unit-tests.py.
Referenced by python-unit-tests.TestSimulator.testSchedule(), and python-unit-tests.TestSimulator.testScheduleDestroy().
_context_received
python-unit-tests.TestSimulator._context_received private
context
Definition at line 96 of file python-unit-tests.py.
_received_packet
python-unit-tests.TestSimulator._received_packet private
received packet
Definition at line 147 of file python-unit-tests.py.
The documentation for this class was generated from the following file:
utils/python-unit-tests.py