ns-3: WifiPhyThresholdsTest Class Reference
WifiPhyThresholdsTest Class Reference
Wifi Models » wifi module tests | Test suites
Wifi Phy Threshold Test base class.
Public Member Functions
WifiPhyThresholdsTest (std::string test_name)
Constructor.
virtual ~WifiPhyThresholdsTest ()
Destructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Member Functions
virtual Ptr< SpectrumSignalParameters > MakeForeignSignal (double txPowerWatts)
Make foreign signal function.
virtual Ptr< SpectrumSignalParameters > MakeWifiSignal (double txPowerWatts)
Make wifi signal function.
virtual void PhyStateChanged (Time start, Time duration, WifiPhyState newState)
PHY state changed callback function.
void RxDropped (Ptr< const Packet > p, WifiPhyRxfailureReason reason)
PHY dropped packet callback function.
virtual void RxFailure (Ptr< WifiPsdu > psdu)
PHY receive failure callback function.
virtual void RxSuccess (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector, std::vector< bool > statusPerMpdu)
PHY receive success callback function.
virtual void SendSignal (double txPowerWatts, bool wifiSignal)
Send signal function.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Protected Attributes
uint32_t m_ccabusyStateCount
count number of PHY state change to CCA_BUSY state
uint32_t m_idleStateCount
count number of PHY state change to IDLE state
Ptr< SpectrumWifiPhy > m_phy
PHY object.
uint32_t m_rxDropped
count number of dropped packets
uint32_t m_rxFailure
count number of unsuccessfully received packets
uint32_t m_rxStateCount
count number of PHY state change to RX state
uint32_t m_rxSuccess
count number of successfully received packets
uint32_t m_stateChanged
count number of PHY state change
Private Member Functions
virtual void DoSetup (void)
Implementation to do any local setup required for this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Detailed Description
Wifi Phy Threshold Test base class.
Definition at line 47 of file wifi-phy-thresholds-test.cc.
Constructor & Destructor Documentation
WifiPhyThresholdsTest()
WifiPhyThresholdsTest::WifiPhyThresholdsTest (std::string test_name)
Constructor.
Parameters
test_name the test name
Definition at line 120 of file wifi-phy-thresholds-test.cc.
~WifiPhyThresholdsTest()
WifiPhyThresholdsTest::~WifiPhyThresholdsTest () virtual
Destructor.
Definition at line 132 of file wifi-phy-thresholds-test.cc.
Member Function Documentation
DoSetup()
void WifiPhyThresholdsTest::DoSetup (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test setup before DoRun is invoked.
Reimplemented from ns3::TestCase.
Definition at line 226 of file wifi-phy-thresholds-test.cc.
References CHANNEL_NUMBER, ns3::SpectrumWifiPhy::ConfigureStandard(), FREQUENCY, ns3::WifiPhy::GetState(), m_phy, ns3::MakeCallback(), PhyStateChanged(), RxDropped(), RxFailure(), RxSuccess(), ns3::SpectrumWifiPhy::SetChannelNumber(), ns3::WifiPhy::SetErrorRateModel(), ns3::SpectrumWifiPhy::SetFrequency(), ns3::WifiPhy::SetReceiveErrorCallback(), ns3::WifiPhy::SetReceiveOkCallback(), ns3::ObjectBase::TraceConnectWithoutContext(), and ns3::WIFI_PHY_STANDARD_80211ax_5GHZ.
MakeForeignSignal()
Ptr< SpectrumSignalParameters > WifiPhyThresholdsTest::MakeForeignSignal (double txPowerWatts) protected virtual
Make foreign signal function.
Parameters
txPowerWatts the transmit power in watts
Returns
Ptr<SpectrumSignalParameters>
Definition at line 162 of file wifi-phy-thresholds-test.cc.
References CHANNEL_WIDTH, ns3::SpectrumSignalParameters::duration, FREQUENCY, ns3::SpectrumSignalParameters::psd, ns3::Seconds(), and ns3::SpectrumSignalParameters::txPhy.
Referenced by SendSignal().
MakeWifiSignal()
Ptr< SpectrumSignalParameters > WifiPhyThresholdsTest::MakeWifiSignal (double txPowerWatts) protected virtual
Make wifi signal function.
Parameters
txPowerWatts the transmit power in watts
Returns
Ptr<SpectrumSignalParameters>
Definition at line 137 of file wifi-phy-thresholds-test.cc.
References ns3::WifiPhy::CalculateTxDuration(), CHANNEL_WIDTH, ns3::SpectrumSignalParameters::duration, FREQUENCY, ns3::WifiPhy::GetFrequency(), ns3::WifiPsdu::GetSize(), m_phy, ns3::WifiSpectrumSignalParameters::ppdu, ns3::SpectrumSignalParameters::psd, ns3::WifiMacHeader::SetQosTid(), ns3::WifiMacHeader::SetType(), ns3::SpectrumSignalParameters::txPhy, ns3::WIFI_MAC_QOSDATA, and ns3::WIFI_PREAMBLE_LONG.
Referenced by SendSignal().
PhyStateChanged()
void WifiPhyThresholdsTest::PhyStateChanged (Time start, Time duration, WifiPhyState newState) protected virtual
PHY state changed callback function.
Parameters
start the start time of the new state
duration the duration of the new state
newState the new state
Definition at line 207 of file wifi-phy-thresholds-test.cc.
References CCA_BUSY, aloha::duration, IDLE, m_ccabusyStateCount, m_idleStateCount, m_rxStateCount, m_stateChanged, NS_LOG_FUNCTION, RX, and visualizer.core::start().
Referenced by DoSetup().
RxDropped()
void WifiPhyThresholdsTest::RxDropped (Ptr< const Packet > p, WifiPhyRxfailureReason reason) protected
PHY dropped packet callback function.
Parameters
p the packet
reason the reason
Definition at line 200 of file wifi-phy-thresholds-test.cc.
References m_rxDropped, and NS_LOG_FUNCTION.
Referenced by DoSetup().
RxFailure()
void WifiPhyThresholdsTest::RxFailure (Ptr< WifiPsdu > psdu) protected virtual
PHY receive failure callback function.
Parameters
psdu the PSDU
Definition at line 193 of file wifi-phy-thresholds-test.cc.
References m_rxFailure, and NS_LOG_FUNCTION.
Referenced by DoSetup().
RxSuccess()
void WifiPhyThresholdsTest::RxSuccess (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector, std::vector< bool > statusPerMpdu) protected virtual
PHY receive success callback function.
Parameters
psdu the PSDU
snr the SNR
txVector the transmit vector
statusPerMpdu reception status per MPDU
Definition at line 186 of file wifi-phy-thresholds-test.cc.
References m_rxSuccess, and NS_LOG_FUNCTION.
Referenced by DoSetup().
SendSignal()
void WifiPhyThresholdsTest::SendSignal (double txPowerWatts, bool wifiSignal) protected virtual
Send signal function.
Parameters
txPowerWatts the transmit power in watts
wifiSignal whether the signal is a wifi signal or not
Definition at line 173 of file wifi-phy-thresholds-test.cc.
References m_phy, MakeForeignSignal(), MakeWifiSignal(), and ns3::SpectrumWifiPhy::StartRx().
Referenced by WifiPhyThresholdsWeakWifiSignalTest::DoRun(), WifiPhyThresholdsWeakForeignSignalTest::DoRun(), WifiPhyThresholdsStrongWifiSignalTest::DoRun(), and WifiPhyThresholdsStrongForeignSignalTest::DoRun().
Member Data Documentation
m_ccabusyStateCount
uint32_t WifiPhyThresholdsTest::m_ccabusyStateCount protected
count number of PHY state change to CCA_BUSY state
Definition at line 114 of file wifi-phy-thresholds-test.cc.
Referenced by WifiPhyThresholdsStrongWifiSignalTest::DoRun(), and PhyStateChanged().
m_idleStateCount
uint32_t WifiPhyThresholdsTest::m_idleStateCount protected
count number of PHY state change to IDLE state
Definition at line 113 of file wifi-phy-thresholds-test.cc.
Referenced by WifiPhyThresholdsStrongWifiSignalTest::DoRun(), WifiPhyThresholdsStrongForeignSignalTest::DoRun(), and PhyStateChanged().
m_phy
Ptr<SpectrumWifiPhy> WifiPhyThresholdsTest::m_phy protected
PHY object.
Definition at line 107 of file wifi-phy-thresholds-test.cc.
Referenced by DoSetup(), MakeWifiSignal(), and SendSignal().
m_rxDropped
uint32_t WifiPhyThresholdsTest::m_rxDropped protected
count number of dropped packets
Definition at line 110 of file wifi-phy-thresholds-test.cc.
Referenced by WifiPhyThresholdsWeakWifiSignalTest::DoRun(), WifiPhyThresholdsWeakForeignSignalTest::DoRun(), WifiPhyThresholdsStrongWifiSignalTest::DoRun(), WifiPhyThresholdsStrongForeignSignalTest::DoRun(), and RxDropped().
m_rxFailure
uint32_t WifiPhyThresholdsTest::m_rxFailure protected
count number of unsuccessfully received packets
Definition at line 109 of file wifi-phy-thresholds-test.cc.
Referenced by WifiPhyThresholdsWeakWifiSignalTest::DoRun(), WifiPhyThresholdsWeakForeignSignalTest::DoRun(), WifiPhyThresholdsStrongWifiSignalTest::DoRun(), WifiPhyThresholdsStrongForeignSignalTest::DoRun(), and RxFailure().
m_rxStateCount
uint32_t WifiPhyThresholdsTest::m_rxStateCount protected
count number of PHY state change to RX state
Definition at line 112 of file wifi-phy-thresholds-test.cc.
Referenced by WifiPhyThresholdsStrongWifiSignalTest::DoRun(), and PhyStateChanged().
m_rxSuccess
uint32_t WifiPhyThresholdsTest::m_rxSuccess protected
count number of successfully received packets
Definition at line 108 of file wifi-phy-thresholds-test.cc.
Referenced by WifiPhyThresholdsWeakWifiSignalTest::DoRun(), WifiPhyThresholdsWeakForeignSignalTest::DoRun(), WifiPhyThresholdsStrongWifiSignalTest::DoRun(), WifiPhyThresholdsStrongForeignSignalTest::DoRun(), and RxSuccess().
m_stateChanged
uint32_t WifiPhyThresholdsTest::m_stateChanged protected
count number of PHY state change
Definition at line 111 of file wifi-phy-thresholds-test.cc.
Referenced by WifiPhyThresholdsWeakWifiSignalTest::DoRun(), WifiPhyThresholdsWeakForeignSignalTest::DoRun(), WifiPhyThresholdsStrongWifiSignalTest::DoRun(), and PhyStateChanged().
The documentation for this class was generated from the following file:
src/wifi/test/wifi-phy-thresholds-test.cc