ns-3: ns3::SpectrumModel Class Reference
ns3::SpectrumModel Class Reference
Set of frequency values implementing the domain of the functions in the Function Space defined by SpectrumValue.
#include "spectrum-model.h"
Public Member Functions
SpectrumModel (Bands bands)
This construct a SpectrumModel based on the explicit values of center frequencies and boundaries of each subband.
SpectrumModel (std::vector< double > centerFreqs)
This constructs a SpectrumModel based on a given set of frequencies, which is assumed to be sorted by increasing frequency.
Bands::const_iterator Begin () const
Const Iterator to the model Bands container start.
Bands::const_iterator End () const
Const Iterator to the model Bands container end.
size_t GetNumBands () const
SpectrumModelUid_t GetUid () const
bool IsOrthogonal (const SpectrumModel &other) const
Check if another SpectrumModels has bands orthogonal to our bands.
Public Member Functions inherited from ns3::SimpleRefCount< SpectrumModel >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
Bands m_bands
Actual definition of frequency bands within this SpectrumModel.
SpectrumModelUid_t m_uid
unique id for a given set of frequencies
Static Private Attributes
static SpectrumModelUid_t m_uidCount = 0
counter to assign m_uids
Friends
bool operator== (const SpectrumModel &lhs, const SpectrumModel &rhs)
Comparison operator.
Detailed Description
Set of frequency values implementing the domain of the functions in the Function Space defined by SpectrumValue.
Frequency values are in Hz. It is intended that frequency values are non-negative, though this is not enforced.
Definition at line 66 of file spectrum-model.h.
Constructor & Destructor Documentation
SpectrumModel() [1/2]
ns3::SpectrumModel::SpectrumModel (std::vector< double > centerFreqs)
This constructs a SpectrumModel based on a given set of frequencies, which is assumed to be sorted by increasing frequency.
The lower (resp. upper) frequency band limit is determined as the mean value between the center frequency of the considered band and the center frequency of the adjacent lower (resp. upper) band.
Parameters
centerFreqs the vector of center frequencies.
Returns
Definition at line 41 of file spectrum-model.cc.
References ns3::BandInfo::fc, ns3::BandInfo::fh, ns3::BandInfo::fl, m_bands, m_uid, m_uidCount, and NS_ASSERT.
SpectrumModel() [2/2]
ns3::SpectrumModel::SpectrumModel (Bands bands)
This construct a SpectrumModel based on the explicit values of center frequencies and boundaries of each subband.
Parameters
bands
Returns
Definition at line 73 of file spectrum-model.cc.
References m_bands, m_uid, m_uidCount, and NS_LOG_INFO.
Member Function Documentation
Begin()
Bands::const_iterator ns3::SpectrumModel::Begin () const
Const Iterator to the model Bands container start.
Definition at line 81 of file spectrum-model.cc.
References m_bands.
Referenced by ns3::SpectrumConverter::SpectrumConverter(), ns3::SpectrumValue::ConstBandsBegin(), IsOrthogonal(), and Bug2843TestCase::StoreDistinctTuple().
End()
Bands::const_iterator ns3::SpectrumModel::End () const
Const Iterator to the model Bands container end.
Definition at line 87 of file spectrum-model.cc.
References m_bands.
Referenced by ns3::SpectrumConverter::SpectrumConverter(), ns3::SpectrumValue::ConstBandsEnd(), and IsOrthogonal().
GetNumBands()
size_t ns3::SpectrumModel::GetNumBands () const
Returns
the number of frequencies in this SpectrumModel
Definition at line 93 of file spectrum-model.cc.
References m_bands.
Referenced by ns3::WifiSpectrumValueHelper::CreateDsssTxPowerSpectralDensity(), ns3::WifiSpectrumValueHelper::CreateHeOfdmTxPowerSpectralDensity(), ns3::WifiSpectrumValueHelper::CreateHtOfdmTxPowerSpectralDensity(), ns3::WifiSpectrumValueHelper::CreateOfdmTxPowerSpectralDensity(), ns3::WifiSpectrumValueHelper::CreateRfFilter(), ns3::WifiSpectrumValueHelper::CreateSpectrumMaskForOfdm(), and Bug2843TestCase::StoreDistinctTuple().
GetUid()
SpectrumModelUid_t ns3::SpectrumModel::GetUid () const
Returns
the unique id of this SpectrumModel
Definition at line 99 of file spectrum-model.cc.
References m_uid.
Referenced by ns3::MultiModelSpectrumChannel::AddRx(), ns3::MultiModelSpectrumChannel::FindAndEventuallyAddTxSpectrumModel(), ns3::WifiSpectrumValueHelper::GetSpectrumModel(), ns3::LteSpectrumValueHelper::GetSpectrumModel(), ns3::SpectrumValue::GetSpectrumModelUid(), and ns3::SpectrumWifiPhy::StartTx().
IsOrthogonal()
bool ns3::SpectrumModel::IsOrthogonal (const SpectrumModel & other) const
Check if another SpectrumModels has bands orthogonal to our bands.
Parameters
other another SpectrumModel
Returns
true if bands are orthogonal
Definition at line 105 of file spectrum-model.cc.
References Begin(), End(), max, and min.
Referenced by ns3::MultiModelSpectrumChannel::AddRx(), and ns3::MultiModelSpectrumChannel::FindAndEventuallyAddTxSpectrumModel().
Friends And Related Function Documentation
operator==
bool operator== (const SpectrumModel & lhs, const SpectrumModel & rhs) friend
Comparison operator.
Returns true if the two SpectumModels are identical
Parameters
lhs left operand
rhs right operand
Returns
true if the two operands are identical
Definition at line 34 of file spectrum-model.cc.
Member Data Documentation
m_bands
Bands ns3::SpectrumModel::m_bands private
Actual definition of frequency bands within this SpectrumModel.
Definition at line 132 of file spectrum-model.h.
Referenced by SpectrumModel(), Begin(), End(), and GetNumBands().
m_uid
SpectrumModelUid_t ns3::SpectrumModel::m_uid private
unique id for a given set of frequencies
Definition at line 133 of file spectrum-model.h.
Referenced by SpectrumModel(), GetUid(), and ns3::operator==().
m_uidCount
SpectrumModelUid_t ns3::SpectrumModel::m_uidCount = 0 static private
counter to assign m_uids
Definition at line 134 of file spectrum-model.h.
Referenced by SpectrumModel().
The documentation for this class was generated from the following files:
src/spectrum/model/spectrum-model.h
src/spectrum/model/spectrum-model.cc