ns-3: CobaltQueueDiscDropTest Class Reference
CobaltQueueDiscDropTest Class Reference
Traffic-control » traffic-control module tests | Test suites
Test 2: Cobalt Queue Disc Drop Test Item.
Public Member Functions
CobaltQueueDiscDropTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
void Enqueue (Ptr< CobaltQueueDisc > queue, uint32_t size, uint32_t nPkt)
Enqueue function.
void EnqueueWithDelay (Ptr< CobaltQueueDisc > queue, uint32_t size, uint32_t nPkt)
void RunDropTest (QueueSizeUnit mode)
Run Cobalt test function.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test 2: Cobalt Queue Disc Drop Test Item.
Definition at line 228 of file cobalt-queue-disc-test-suite.cc.
Constructor & Destructor Documentation
CobaltQueueDiscDropTest()
CobaltQueueDiscDropTest::CobaltQueueDiscDropTest ()
Definition at line 250 of file cobalt-queue-disc-test-suite.cc.
Member Function Documentation
DoRun()
void CobaltQueueDiscDropTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 319 of file cobalt-queue-disc-test-suite.cc.
References ns3::BYTES, ns3::PACKETS, and RunDropTest().
Enqueue()
void CobaltQueueDiscDropTest::Enqueue (Ptr< CobaltQueueDisc > queue, uint32_t size, uint32_t nPkt)
Enqueue function.
Parameters
queue the queue disc
size the size
nPkt the number of packets
Definition at line 309 of file cobalt-queue-disc-test-suite.cc.
References ns3::QueueDisc::Enqueue().
Referenced by EnqueueWithDelay().
EnqueueWithDelay()
void CobaltQueueDiscDropTest::EnqueueWithDelay (Ptr< CobaltQueueDisc > queue, uint32_t size, uint32_t nPkt)
Definition at line 298 of file cobalt-queue-disc-test-suite.cc.
References Enqueue(), and ns3::Seconds().
Referenced by RunDropTest().
RunDropTest()
void CobaltQueueDiscDropTest::RunDropTest (QueueSizeUnit mode)
Run Cobalt test function.
Parameters
mode the mode
Definition at line 256 of file cobalt-queue-disc-test-suite.cc.
References ns3::BYTES, EnqueueWithDelay(), ns3::QueueDisc::Stats::GetNDroppedPackets(), ns3::CobaltQueueDisc::GetPdrop(), ns3::QueueDisc::GetStats(), ns3::Object::Initialize(), NS_TEST_EXPECT_MSG_EQ, NS_TEST_EXPECT_MSG_NE, ns3::PACKETS, ns3::Seconds(), and ns3::ObjectBase::SetAttributeFailSafe().
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/traffic-control/test/cobalt-queue-disc-test-suite.cc