ns-3: Ipv4HeaderTest Class Reference
Ipv4HeaderTest Class Reference
Internet » internet module tests | Test suites
IPv4 Header Test.
Public Member Functions
Ipv4HeaderTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
void ReceivePacket (Ptr< Socket > socket, Ptr< Packet > packet, const Address &from)
Receives a packet.
void ReceivePkt (Ptr< Socket > socket)
Receives a packet.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void DoSendData_IpHdr_Dscp (Ptr< Socket > socket, std::string to, Ipv4Header::DscpType dscp, Ipv4Header::EcnType ecn)
Send a packet with speciic DSCP and ECN fields.
void SendData_IpHdr_Dscp (Ptr< Socket > socket, std::string to, Ipv4Header::DscpType dscp, Ipv4Header::EcnType ecn)
Send a packet with speciic DSCP and ECN fields.
Private Attributes
Ipv4Header m_receivedHeader
Received header.
Ptr< Packet > m_receivedPacket
Received packet.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
IPv4 Header Test.
Definition at line 59 of file ipv4-header-test.cc.
Constructor & Destructor Documentation
Ipv4HeaderTest()
Ipv4HeaderTest::Ipv4HeaderTest ()
Definition at line 101 of file ipv4-header-test.cc.
Member Function Documentation
DoRun()
void Ipv4HeaderTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 153 of file ipv4-header-test.cc.
References ns3::Ipv4::AddAddress(), ns3::Node::AddDevice(), ns3::Ipv4::AddInterface(), ns3::SocketFactory::CreateSocket(), ns3::Ipv4Header::GetDscp(), ns3::Ipv4Header::GetEcn(), ns3::Object::GetObject(), ns3::Packet::GetSize(), ns3::InternetStackHelper::Install(), m_receivedHeader, m_receivedPacket, ns3::MakeCallback(), NS_TEST_EXPECT_MSG_EQ, ns3::Ipv4Header::Print(), ReceivePkt(), ns3::Packet::RemoveAllByteTags(), SendData_IpHdr_Dscp(), ns3::SimpleNetDevice::SetAddress(), ns3::SimpleNetDevice::SetChannel(), ns3::InternetStackHelper::SetIpv6StackInstall(), and ns3::Ipv4::SetUp().
DoSendData_IpHdr_Dscp()
void Ipv4HeaderTest::DoSendData_IpHdr_Dscp (Ptr< Socket > socket, std::string to, Ipv4Header::DscpType dscp, Ipv4Header::EcnType ecn) private
Send a packet with speciic DSCP and ECN fields.
Parameters
socket The source socket.
to The destination address.
dscp The DSCP field.
ecn The ECN field.
Definition at line 123 of file ipv4-header-test.cc.
References ns3::Packet::AddHeader(), ns3::Packet::GetSize(), NS_TEST_EXPECT_MSG_EQ, ns3::Socket::SendTo(), ns3::ObjectBase::SetAttribute(), ns3::Ipv4Header::SetDestination(), ns3::Ipv4Header::SetDscp(), ns3::Ipv4Header::SetEcn(), ns3::Ipv4Header::SetPayloadSize(), ns3::Ipv4Header::SetProtocol(), ns3::Ipv4Header::SetSource(), and ns3::Ipv4Header::SetTtl().
Referenced by SendData_IpHdr_Dscp().
ReceivePacket()
void Ipv4HeaderTest::ReceivePacket (Ptr< Socket > socket, Ptr< Packet > packet, const Address & from)
Receives a packet.
Parameters
socket The receiving socket.
packet The packet.
from The source address.
Definition at line 106 of file ipv4-header-test.cc.
References m_receivedPacket.
ReceivePkt()
void Ipv4HeaderTest::ReceivePkt (Ptr< Socket > socket)
Receives a packet.
Parameters
socket The receiving socket.
Definition at line 111 of file ipv4-header-test.cc.
References ns3::Socket::GetRxAvailable(), ns3::Packet::GetSize(), m_receivedHeader, m_receivedPacket, max, NS_ASSERT, ns3::Packet::PeekHeader(), and ns3::Socket::Recv().
Referenced by DoRun().
SendData_IpHdr_Dscp()
void Ipv4HeaderTest::SendData_IpHdr_Dscp (Ptr< Socket > socket, std::string to, Ipv4Header::DscpType dscp, Ipv4Header::EcnType ecn) private
Send a packet with speciic DSCP and ECN fields.
Parameters
socket The source socket.
to The destination address.
dscp The DSCP field.
ecn The ECN field.
Definition at line 144 of file ipv4-header-test.cc.
References DoSendData_IpHdr_Dscp(), ns3::Node::GetId(), ns3::Socket::GetNode(), m_receivedPacket, and ns3::Seconds().
Referenced by DoRun().
Member Data Documentation
m_receivedHeader
Ipv4Header Ipv4HeaderTest::m_receivedHeader private
Received header.
Definition at line 62 of file ipv4-header-test.cc.
Referenced by DoRun(), and ReceivePkt().
m_receivedPacket
Ptr<Packet> Ipv4HeaderTest::m_receivedPacket private
Received packet.
Definition at line 61 of file ipv4-header-test.cc.
Referenced by DoRun(), ReceivePacket(), ReceivePkt(), and SendData_IpHdr_Dscp().
The documentation for this class was generated from the following file:
src/internet/test/ipv4-header-test.cc