ns-3: BasicEnergyDepletionTest Class Reference
BasicEnergyDepletionTest Class Reference
Test case of energy depletion handling for BasicEnergySource and WifiRadioEnergyModel.
Public Member Functions
BasicEnergyDepletionTest ()
virtual ~BasicEnergyDepletionTest ()
bool DoRun (void)
Performs some tests involving energy depletion.
Private Member Functions
void DepletionHandler (void)
Callback invoked when energy is drained from source.
bool DepletionTestCase (double simTimeS, double updateIntervalS)
Private Attributes
int m_callbackCount
int m_numOfNodes
double m_simTimeS
double m_timeStepS
double m_updateIntervalS
Detailed Description
Test case of energy depletion handling for BasicEnergySource and WifiRadioEnergyModel.
Definition at line 256 of file basic-energy-model-test.cc.
Constructor & Destructor Documentation
BasicEnergyDepletionTest()
BasicEnergyDepletionTest::BasicEnergyDepletionTest ()
Definition at line 292 of file basic-energy-model-test.cc.
~BasicEnergyDepletionTest()
BasicEnergyDepletionTest::~BasicEnergyDepletionTest () virtual
Definition at line 301 of file basic-energy-model-test.cc.
Member Function Documentation
DepletionHandler()
void BasicEnergyDepletionTest::DepletionHandler (void) private
Callback invoked when energy is drained from source.
Definition at line 331 of file basic-energy-model-test.cc.
Referenced by DepletionTestCase().
DepletionTestCase()
bool BasicEnergyDepletionTest::DepletionTestCase (double simTimeS, double updateIntervalS) private
Parameters
simTimeS Simulation time, in seconds.
updateIntervalS Device model update interval, in seconds.
Returns
False if all is good.
Runs simulation with specified simulation time and update interval.
Definition at line 337 of file basic-energy-model-test.cc.
References ns3::NodeContainer::Create(), ns3::YansWifiChannelHelper::Create(), ns3::YansWifiPhyHelper::Default(), DepletionHandler(), ns3::Simulator::Destroy(), first::devices, ns3::WifiPhyHelper::DLT_IEEE802_11_RADIO, ns3::DeviceEnergyModelHelper::Install(), ns3::EnergySourceHelper::Install(), ns3::MakeCallback(), NS_LOG_DEBUG, ns3::Simulator::Run(), ns3::Seconds(), ns3::BasicEnergySourceHelper::Set(), ns3::WifiPhyHelper::Set(), ns3::YansWifiPhyHelper::SetChannel(), ns3::Config::SetDefault(), ns3::WifiRadioEnergyModelHelper::SetDepletionCallback(), ns3::WifiPhyHelper::SetPcapDataLinkType(), ns3::YansWifiChannelHelper::SetPropagationDelay(), ns3::WifiMacHelper::SetType(), ns3::Simulator::Stop(), third::wifi, and ns3::WIFI_PHY_STANDARD_80211b.
DoRun()
bool BasicEnergyDepletionTest::DoRun (void)
Performs some tests involving energy depletion.
Returns
true is some error happened.
Definition at line 306 of file basic-energy-model-test.cc.
Member Data Documentation
m_callbackCount
int BasicEnergyDepletionTest::m_callbackCount private
Definition at line 285 of file basic-energy-model-test.cc.
m_numOfNodes
int BasicEnergyDepletionTest::m_numOfNodes private
Definition at line 284 of file basic-energy-model-test.cc.
m_simTimeS
double BasicEnergyDepletionTest::m_simTimeS private
Definition at line 286 of file basic-energy-model-test.cc.
m_timeStepS
double BasicEnergyDepletionTest::m_timeStepS private
Definition at line 287 of file basic-energy-model-test.cc.
m_updateIntervalS
double BasicEnergyDepletionTest::m_updateIntervalS private
Definition at line 288 of file basic-energy-model-test.cc.
The documentation for this class was generated from the following file:
src/energy/examples/basic-energy-model-test.cc