ns-3: ns3::ServiceFlowManager Class Reference
ns3::ServiceFlowManager Class Reference
WiMAX Models
#include "service-flow-manager.h"
Public Types
enum ConfirmationCode { CONFIRMATION_CODE_SUCCESS, CONFIRMATION_CODE_REJECT }
confirmation code enumeration as per Table 384 (not all codes implemented)
Public Member Functions
ServiceFlowManager ()
~ServiceFlowManager (void)
void AddServiceFlow (ServiceFlow *serviceFlow)
Add service flow function.
bool AreServiceFlowsAllocated ()
bool AreServiceFlowsAllocated (std::vector< ServiceFlow * > *serviceFlows)
bool AreServiceFlowsAllocated (std::vector< ServiceFlow * > serviceFlows)
ServiceFlow * DoClassify (Ipv4Address SrcAddress, Ipv4Address DstAddress, uint16_t SrcPort, uint16_t DstPort, uint8_t Proto, ServiceFlow::Direction dir) const
void DoDispose (void)
Destructor implementation.
ServiceFlow * GetNextServiceFlowToAllocate ()
uint32_t GetNrServiceFlows (void) const
ServiceFlow * GetServiceFlow (Cid cid) const
Get service flow by CID.
ServiceFlow * GetServiceFlow (uint32_t sfid) const
Get service flow by flow id.
std::vector< ServiceFlow * > GetServiceFlows (enum ServiceFlow::SchedulingType schedulingType) const
Get service flows function.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
std::vector< ServiceFlow * > * m_serviceFlows
the service flows
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The same service flow manager class serves both for BS and SS though some functions are exclusive to only one of them.
Definition at line 42 of file service-flow-manager.h.
Member Enumeration Documentation
ConfirmationCode
enum ns3::ServiceFlowManager::ConfirmationCode
confirmation code enumeration as per Table 384 (not all codes implemented)
Enumerator
CONFIRMATION_CODE_SUCCESS
CONFIRMATION_CODE_REJECT
Definition at line 46 of file service-flow-manager.h.
Constructor & Destructor Documentation
ServiceFlowManager()
ns3::ServiceFlowManager::ServiceFlowManager ()
Definition at line 57 of file service-flow-manager.cc.
References m_serviceFlows.
~ServiceFlowManager()
ns3::ServiceFlowManager::~ServiceFlowManager (void)
Definition at line 62 of file service-flow-manager.cc.
Member Function Documentation
AddServiceFlow()
void ns3::ServiceFlowManager::AddServiceFlow (ServiceFlow * serviceFlow)
Add service flow function.
Parameters
serviceFlow the service flow
Definition at line 78 of file service-flow-manager.cc.
References m_serviceFlows.
Referenced by ns3::BsServiceFlowManager::AddServiceFlow(), and ns3::SsServiceFlowManager::AddServiceFlow().
AreServiceFlowsAllocated() [1/3]
bool ns3::ServiceFlowManager::AreServiceFlowsAllocated ()
Returns
true if all service flows are allocated, false otherwise
Definition at line 148 of file service-flow-manager.cc.
References m_serviceFlows.
Referenced by AreServiceFlowsAllocated(), and ns3::BsServiceFlowManager::ProcessDsaAck().
AreServiceFlowsAllocated() [2/3]
bool ns3::ServiceFlowManager::AreServiceFlowsAllocated (std::vector< ServiceFlow * > * serviceFlows)
Parameters
serviceFlows vector of pointers to service flows to be checked
Returns
true if all service flows are allocated, false otherwise
Definition at line 154 of file service-flow-manager.cc.
References AreServiceFlowsAllocated().
AreServiceFlowsAllocated() [3/3]
bool ns3::ServiceFlowManager::AreServiceFlowsAllocated (std::vector< ServiceFlow * > serviceFlows)
Parameters
serviceFlows vector of pointers to service flows to be checked
Returns
true if all service flows are allocated, false otherwise
Definition at line 160 of file service-flow-manager.cc.
DoClassify()
ServiceFlow * ns3::ServiceFlowManager::DoClassify (Ipv4Address SrcAddress, Ipv4Address DstAddress, uint16_t SrcPort, uint16_t DstPort, uint8_t Proto, ServiceFlow::Direction dir) const
Parameters
SrcAddress the source ip address
DstAddress the destination ip address
SrcPort the source port
DstPort the destination port
Proto the protocol
dir the direction of the service flow
Returns
the service flow to which this ip flow is associated
Definition at line 83 of file service-flow-manager.cc.
References dir, and m_serviceFlows.
DoDispose()
void ns3::ServiceFlowManager::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Reimplemented in ns3::SsServiceFlowManager.
Definition at line 67 of file service-flow-manager.cc.
References m_serviceFlows.
Referenced by ns3::BsServiceFlowManager::DoDispose(), and ns3::SsServiceFlowManager::DoDispose().
GetNextServiceFlowToAllocate()
ServiceFlow * ns3::ServiceFlowManager::GetNextServiceFlowToAllocate ()
Returns
pointer to the next service flow to be allocated
Definition at line 173 of file service-flow-manager.cc.
References m_serviceFlows.
Referenced by ns3::SsServiceFlowManager::InitiateServiceFlows(), and ns3::SsServiceFlowManager::ProcessDsaRsp().
GetNrServiceFlows()
uint32_t ns3::ServiceFlowManager::GetNrServiceFlows (void) const
Returns
the number of all service flows
Definition at line 187 of file service-flow-manager.cc.
References m_serviceFlows.
GetServiceFlow() [1/2]
ServiceFlow * ns3::ServiceFlowManager::GetServiceFlow (Cid cid) const
Get service flow by CID.
Parameters
cid the CID
Returns
pointer to the service flow object corresponding to the CID
Definition at line 119 of file service-flow-manager.cc.
References ns3::Cid::GetIdentifier(), m_serviceFlows, and NS_LOG_DEBUG.
GetServiceFlow() [2/2]
ServiceFlow * ns3::ServiceFlowManager::GetServiceFlow (uint32_t sfid) const
Get service flow by flow id.
Parameters
sfid the service flow id
Returns
pointer to the service flow object corresponding to the flow id
Definition at line 104 of file service-flow-manager.cc.
References m_serviceFlows, and NS_LOG_DEBUG.
Referenced by ns3::BsServiceFlowManager::GetServiceFlow().
GetServiceFlows()
std::vector< ServiceFlow * > ns3::ServiceFlowManager::GetServiceFlows (enum ServiceFlow::SchedulingType schedulingType) const
Get service flows function.
Parameters
schedulingType the scheduling type
Returns
vector of pointers to service flows corresponding to the schedulin type
Definition at line 134 of file service-flow-manager.cc.
References m_serviceFlows, and ns3::ServiceFlow::SF_TYPE_ALL.
Referenced by ns3::BsServiceFlowManager::GetServiceFlows().
GetTypeId()
TypeId ns3::ServiceFlowManager::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 49 of file service-flow-manager.cc.
References ns3::TypeId::SetParent().
Member Data Documentation
m_serviceFlows
std::vector<ServiceFlow*>* ns3::ServiceFlowManager::m_serviceFlows private
the service flows
Definition at line 126 of file service-flow-manager.h.
Referenced by ServiceFlowManager(), AddServiceFlow(), AreServiceFlowsAllocated(), DoClassify(), DoDispose(), GetNextServiceFlowToAllocate(), GetNrServiceFlows(), GetServiceFlow(), and GetServiceFlows().
The documentation for this class was generated from the following files:
src/wimax/model/service-flow-manager.h
src/wimax/model/service-flow-manager.cc