ns-3: ns3::LteMacSapProvider Class Reference
ns3::LteMacSapProvider Class Reference abstract
Service Access Point (SAP) offered by the MAC to the RLC See Femto Forum MAC Scheduler Interface Specification v 1.11, Figure 1.
#include "lte-mac-sap.h"
Classes
struct ReportBufferStatusParameters
Parameters for LteMacSapProvider::ReportBufferStatus.
struct TransmitPduParameters
Parameters for LteMacSapProvider::TransmitPdu.
Public Member Functions
virtual ~LteMacSapProvider ()
virtual void ReportBufferStatus (ReportBufferStatusParameters params)=0
Report the RLC buffer status to the MAC.
virtual void TransmitPdu (TransmitPduParameters params)=0
send an RLC PDU to the MAC for transmission.
Detailed Description
Service Access Point (SAP) offered by the MAC to the RLC See Femto Forum MAC Scheduler Interface Specification v 1.11, Figure 1.
This is the MAC SAP Provider, i.e., the part of the SAP that contains the MAC methods called by the RLC
Definition at line 36 of file lte-mac-sap.h.
Constructor & Destructor Documentation
~LteMacSapProvider()
ns3::LteMacSapProvider::~LteMacSapProvider () virtual
Definition at line 28 of file lte-mac-sap.cc.
Member Function Documentation
ReportBufferStatus()
virtual void ns3::LteMacSapProvider::ReportBufferStatus (ReportBufferStatusParameters params) pure virtual
Report the RLC buffer status to the MAC.
Parameters
params ReportBufferStatusParameters
Implemented in ns3::UeMemberLteMacSapProvider, ns3::EnbMacMemberLteMacSapProvider< C >, and ns3::SimpleUeCcmMacSapProvider.
Referenced by ns3::LteRlcAm::DoReportBufferStatus(), ns3::LteRlcTm::DoReportBufferStatus(), ns3::LteRlcUm::DoReportBufferStatus(), and ns3::LteRlcSm::ReportBufferStatus().
TransmitPdu()
virtual void ns3::LteMacSapProvider::TransmitPdu (TransmitPduParameters params) pure virtual
send an RLC PDU to the MAC for transmission.
This method is to be called as a response to LteMacSapUser::NotifyTxOpportunity
Parameters
params TransmitPduParameters
Implemented in ns3::UeMemberLteMacSapProvider, ns3::EnbMacMemberLteMacSapProvider< C >, and ns3::SimpleUeCcmMacSapProvider.
Referenced by ns3::LteRlcAm::DoNotifyTxOpportunity(), ns3::LteRlcTm::DoNotifyTxOpportunity(), ns3::LteRlcUm::DoNotifyTxOpportunity(), and ns3::LteRlcSm::DoNotifyTxOpportunity().
The documentation for this class was generated from the following files:
src/lte/model/lte-mac-sap.h
src/lte/model/lte-mac-sap.cc