ns-3: ns3::ObjectPtrContainerAccessor Class Reference
ns3::ObjectPtrContainerAccessor Class Reference abstract
#include "object-ptr-container.h"
Public Member Functions
virtual bool Get (const ObjectBase *object, AttributeValue &value) const
virtual bool HasGetter (void) const
virtual bool HasSetter (void) const
virtual bool Set (ObjectBase *object, const AttributeValue &value) const
Public Member Functions inherited from ns3::AttributeAccessor
AttributeAccessor ()
virtual ~AttributeAccessor ()
Public Member Functions inherited from ns3::SimpleRefCount< AttributeAccessor >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Member Functions
virtual Ptr< Object > DoGet (const ObjectBase *object, std::size_t i, std::size_t *index) const =0
Get an instance from the container, identified by index.
virtual bool DoGetN (const ObjectBase *object, std::size_t *n) const =0
Get the number of instances in the container.
Detailed Description
AttributeAccessor implementation for ObjectPtrContainerValue.
Definition at line 226 of file object-ptr-container.h.
Member Function Documentation
DoGet()
virtual Ptr<Object> ns3::ObjectPtrContainerAccessor::DoGet (const ObjectBase * object, std::size_t i, std::size_t * index) const private pure virtual
Get an instance from the container, identified by index.
Parameters
[in] object The container object.
[in] i The desired instance index.
[out] index The index retrieved.
Returns
The index requested.
Referenced by Get().
DoGetN()
virtual bool ns3::ObjectPtrContainerAccessor::DoGetN (const ObjectBase * object, std::size_t * n) const private pure virtual
Get the number of instances in the container.
Parameters
[in] object The container object.
[out] n The number of instances in the container.
Returns
true if the value could be obtained successfully.
Referenced by Get().
Get()
bool ns3::ObjectPtrContainerAccessor::Get (const ObjectBase * object, AttributeValue & attribute) const virtual
Parameters
[in,out] object The object instance to get the value from
[out] attribute A pointer to where the value should be set.
Returns
true if the value could be read successfully, and stored in the input value, false otherwise.
This method expects that the caller has checked that the input value is valid with AttributeChecker::Check.
Implements ns3::AttributeAccessor.
Definition at line 107 of file object-ptr-container.cc.
References DoGet(), DoGetN(), ns3::ObjectPtrContainerValue::m_objects, sample-rng-plot::n, and NS_LOG_FUNCTION.
HasGetter()
bool ns3::ObjectPtrContainerAccessor::HasGetter (void) const virtual
Returns
true if this accessor supports the Get operation, false otherwise.
Implements ns3::AttributeAccessor.
Definition at line 131 of file object-ptr-container.cc.
References NS_LOG_FUNCTION.
HasSetter()
bool ns3::ObjectPtrContainerAccessor::HasSetter (void) const virtual
Returns
true if this accessor supports the Set operation, false otherwise.
Implements ns3::AttributeAccessor.
Definition at line 137 of file object-ptr-container.cc.
References NS_LOG_FUNCTION.
Set()
bool ns3::ObjectPtrContainerAccessor::Set (ObjectBase * object, const AttributeValue & value) const virtual
Parameters
[in,out] object The object instance to set the value in
[in] value The value to set
Returns
true if the value could be set successfully, false otherwise.
This method expects that the caller has checked that the input value is valid with AttributeChecker::Check.
Implements ns3::AttributeAccessor.
Definition at line 100 of file object-ptr-container.cc.
References NS_LOG_FUNCTION.
The documentation for this class was generated from the following files:
src/core/model/object-ptr-container.h
src/core/model/object-ptr-container.cc