ns-3: ns3::RrcConnectionReestablishmentHeader Class Reference
ns3::RrcConnectionReestablishmentHeader Class Reference
This class manages the serialization/deserialization of RrcConnectionReestablishment IE.
#include "lte-rrc-header.h"
Public Member Functions
RrcConnectionReestablishmentHeader ()
~RrcConnectionReestablishmentHeader ()
uint32_t Deserialize (Buffer::Iterator bIterator)
LteRrcSap::RrcConnectionReestablishment GetMessage () const
Returns a RrcConnectionReestablishment IE from the values in the class attributes.
LteRrcSap::RadioResourceConfigDedicated GetRadioResourceConfigDedicated () const
Getter for m_radioResourceConfigDedicated attribute.
uint8_t GetRrcTransactionIdentifier () const
Getter for m_rrcTransactionIdentifier attribute.
void PreSerialize () const
This function serializes class attributes to m_serializationResult local Buffer.
void Print (std::ostream &os) const
This function prints the object, for debugging purposes.
void SetMessage (LteRrcSap::RrcConnectionReestablishment msg)
Receives a RrcConnectionReestablishment IE and stores the contents into the class attributes.
Public Member Functions inherited from ns3::RrcDlCcchMessage
RrcDlCcchMessage ()
~RrcDlCcchMessage ()
Public Member Functions inherited from ns3::RrcAsn1Header
RrcAsn1Header ()
int GetMessageType ()
Get message type.
Public Member Functions inherited from ns3::Asn1Header
Asn1Header ()
virtual ~Asn1Header ()
uint32_t GetSerializedSize (void) const
void Serialize (Buffer::Iterator bIterator) const
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Private Attributes
LteRrcSap::RadioResourceConfigDedicated m_radioResourceConfigDedicated
radio resource config dedicated
uint8_t m_rrcTransactionIdentifier
RRC transaction identifier.
Additional Inherited Members
Static Public Member Functions inherited from ns3::Asn1Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions inherited from ns3::RrcDlCcchMessage
Buffer::Iterator DeserializeDlCcchMessage (Buffer::Iterator bIterator)
Deserialize DL CCCH message function.
void SerializeDlCcchMessage (int msgType) const
Serialize DL CCCH message function.
Protected Member Functions inherited from ns3::RrcAsn1Header
int BandwidthToEnum (uint16_t bandwidth) const
Convert from bandwidth (in RBs) to ENUMERATED value.
Buffer::Iterator DeserializeCellIdentification (LteRrcSap::CellIdentification *ci, Buffer::Iterator bIterator)
Deserialize cell identification function.
Buffer::Iterator DeserializeDrbToAddModList (std::list< LteRrcSap::DrbToAddMod > *drbToAddModLis, Buffer::Iterator bIterator)
Deserialize DRB to add mod list function.
Buffer::Iterator DeserializeLogicalChannelConfig (LteRrcSap::LogicalChannelConfig *logicalChannelConfig, Buffer::Iterator bIterator)
Deserialize logical channel config function.
Buffer::Iterator DeserializeMeasConfig (LteRrcSap::MeasConfig *measConfig, Buffer::Iterator bIterator)
Deserialize measure config function.
Buffer::Iterator DeserializeMeasResults (LteRrcSap::MeasResults *measResults, Buffer::Iterator bIterator)
Deserialize measure results function.
Buffer::Iterator DeserializeNonCriticalExtensionConfig (LteRrcSap::NonCriticalExtensionConfiguration *nonCriticalExtension, Buffer::Iterator bIterator)
Deserialize non critical extension config function.
Buffer::Iterator DeserializePhysicalConfigDedicated (LteRrcSap::PhysicalConfigDedicated *physicalConfigDedicated, Buffer::Iterator bIterator)
Deserialize physical config dedicated function.
Buffer::Iterator DeserializePhysicalConfigDedicatedSCell (LteRrcSap::PhysicalConfigDedicatedSCell *pcdsc, Buffer::Iterator bIterator)
Deserialize physical config dedicated SCell function.
Buffer::Iterator DeserializePlmnIdentity (uint32_t *plmnId, Buffer::Iterator bIterator)
Deserialize PLMN identity function.
Buffer::Iterator DeserializeQoffsetRange (int8_t *qOffsetRange, Buffer::Iterator bIterator)
Deserialize Qoffset range function.
Buffer::Iterator DeserializeRachConfigCommon (LteRrcSap::RachConfigCommon *rachConfigCommon, Buffer::Iterator bIterator)
Deserialize RACH config common function.
Buffer::Iterator DeserializeRadioResourceConfigCommon (LteRrcSap::RadioResourceConfigCommon *radioResourceConfigCommon, Buffer::Iterator bIterator)
Deserialize radio resource config common function.
Buffer::Iterator DeserializeRadioResourceConfigCommonSCell (LteRrcSap::RadioResourceConfigCommonSCell *rrccsc, Buffer::Iterator bIterator)
Deserialize radio resource config common SCell function.
Buffer::Iterator DeserializeRadioResourceConfigCommonSib (LteRrcSap::RadioResourceConfigCommonSib *radioResourceConfigCommonSib, Buffer::Iterator bIterator)
Deserialize radio resource config common SIB function.
Buffer::Iterator DeserializeRadioResourceConfigDedicated (LteRrcSap::RadioResourceConfigDedicated *radioResourceConfigDedicated, Buffer::Iterator bIterator)
Deserialize radio resource config dedicated function.
Buffer::Iterator DeserializeRadioResourceConfigDedicatedSCell (LteRrcSap::RadioResourceConfigDedicatedSCell *rrcdsc, Buffer::Iterator bIterator)
Deserialize radio resource config dedicated SCell function.
Buffer::Iterator DeserializeSrbToAddModList (std::list< LteRrcSap::SrbToAddMod > *srbToAddModList, Buffer::Iterator bIterator)
Deserialize SRB to add mod list function.
Buffer::Iterator DeserializeSystemInformationBlockType1 (LteRrcSap::SystemInformationBlockType1 *systemInformationBlockType1, Buffer::Iterator bIterator)
Deserialize system information block type 1 function.
Buffer::Iterator DeserializeSystemInformationBlockType2 (LteRrcSap::SystemInformationBlockType2 *systemInformationBlockType2, Buffer::Iterator bIterator)
Deserialize system information block type 2 function.
Buffer::Iterator DeserializeThresholdEutra (LteRrcSap::ThresholdEutra *thresholdEutra, Buffer::Iterator bIterator)
Deserialize threshold eutra function.
uint16_t EnumToBandwidth (int n) const
Convert from ENUMERATED value to bandwidth (in RBs)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
void Print (std::ostream &os, LteRrcSap::RadioResourceConfigDedicated radioResourceConfigDedicated) const
This function prints RadioResourceConfigDedicated IE, for debugging purposes.
void SerializeDrbToAddModList (std::list< LteRrcSap::DrbToAddMod > drbToAddModList) const
Serialize DRB to add mod list function.
void SerializeLogicalChannelConfig (LteRrcSap::LogicalChannelConfig logicalChannelConfig) const
Serialize logicala channel config function.
void SerializeMeasConfig (LteRrcSap::MeasConfig measConfig) const
Serialize measure config function.
void SerializeMeasResults (LteRrcSap::MeasResults measResults) const
Serialize measure results function.
void SerializeNonCriticalExtensionConfiguration (LteRrcSap::NonCriticalExtensionConfiguration nonCriticalExtensionConfiguration) const
Serialize non critical extension config function.
void SerializePhysicalConfigDedicated (LteRrcSap::PhysicalConfigDedicated physicalConfigDedicated) const
Serialize physical config dedicated function.
void SerializePhysicalConfigDedicatedSCell (LteRrcSap::PhysicalConfigDedicatedSCell pcdsc) const
Serialize physical config dedicated function.
void SerializePlmnIdentity (uint32_t plmnId) const
Serialize PLMN identity function.
void SerializeQoffsetRange (int8_t qOffsetRange) const
Serialize Q offset range function.
void SerializeRachConfigCommon (LteRrcSap::RachConfigCommon rachConfigCommon) const
Serialize RACH config common function.
void SerializeRadioResourceConfigCommon (LteRrcSap::RadioResourceConfigCommon radioResourceConfigCommon) const
Serialize system information block type 2 function.
void SerializeRadioResourceConfigCommonSCell (LteRrcSap::RadioResourceConfigCommonSCell rrccsc) const
Serialize radio resource config common SCell function.
void SerializeRadioResourceConfigCommonSib (LteRrcSap::RadioResourceConfigCommonSib radioResourceConfigCommonSib) const
Serialize radio resource config common SIB function.
void SerializeRadioResourceConfigDedicated (LteRrcSap::RadioResourceConfigDedicated radioResourceConfigDedicated) const
Serialize radio resource config function.
void SerializeRadioResourceDedicatedSCell (LteRrcSap::RadioResourceConfigDedicatedSCell rrcdsc) const
Serialize radio resource dedicated SCell function.
void SerializeSrbToAddModList (std::list< LteRrcSap::SrbToAddMod > srbToAddModList) const
Serialize SRB to add mod list function.
void SerializeSystemInformationBlockType1 (LteRrcSap::SystemInformationBlockType1 systemInformationBlockType1) const
Serialize system information block type 1 function.
void SerializeSystemInformationBlockType2 (LteRrcSap::SystemInformationBlockType2 systemInformationBlockType2) const
Serialize system information block type 2 function.
void SerializeThresholdEutra (LteRrcSap::ThresholdEutra thresholdEutra) const
Serialize threshold eutra function.
Protected Member Functions inherited from ns3::Asn1Header
Buffer::Iterator DeserializeBitset (std::bitset< 8 > *data, Buffer::Iterator bIterator)
Deserialize a bitset.
template<int N>
Buffer::Iterator DeserializeBitset (std::bitset< N > *data, Buffer::Iterator bIterator)
Deserialize a bitset.
Buffer::Iterator DeserializeBitstring (std::bitset< 1 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 10 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 16 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 2 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 27 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 28 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 32 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 8 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
template<int N>
Buffer::Iterator DeserializeBitstring (std::bitset< N > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBoolean (bool *value, Buffer::Iterator bIterator)
Deserialize a boolean.
Buffer::Iterator DeserializeChoice (int numOptions, bool isExtensionMarkerPresent, int *selectedOption, Buffer::Iterator bIterator)
Deserialize a Choice (set of options)
Buffer::Iterator DeserializeEnum (int numElems, int *selectedElem, Buffer::Iterator bIterator)
Deserialize an Enum.
Buffer::Iterator DeserializeInteger (int *n, int nmin, int nmax, Buffer::Iterator bIterator)
Deserialize an integer.
Buffer::Iterator DeserializeNull (Buffer::Iterator bIterator)
Deserialize nothing (null op)
Buffer::Iterator DeserializeSequence (std::bitset< 0 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 1 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 10 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 11 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 2 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 3 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 4 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 5 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 6 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 7 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 9 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
template<int N>
Buffer::Iterator DeserializeSequence (std::bitset< N > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequenceOf (int *numElems, int nMax, int nMin, Buffer::Iterator bIterator)
Deserialize a Sequence.
void FinalizeSerialization () const
Finalizes an in progress serialization.
template<int N>
void SerializeBitset (std::bitset< N > data) const
Serialize a bitset.
void SerializeBitstring (std::bitset< 1 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 10 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 16 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 2 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 27 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 28 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 32 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 8 > bitstring) const
Serialize a bitstring.
template<int N>
void SerializeBitstring (std::bitset< N > bitstring) const
Serialize a bitstring.
void SerializeBoolean (bool value) const
Serialize a bool.
void SerializeChoice (int numOptions, int selectedOption, bool isExtensionMarkerPresent) const
Serialize a Choice (set of options)
void SerializeEnum (int numElems, int selectedElem) const
Serialize an Enum.
void SerializeInteger (int n, int nmin, int nmax) const
Serialize an Integer.
void SerializeNull () const
Serialize nothing (null op)
void SerializeSequence (std::bitset< 0 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 1 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 10 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 11 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 2 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 3 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 4 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 5 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 6 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 7 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 9 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
template<int N>
void SerializeSequence (std::bitset< N > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequenceOf (int numElems, int nMax, int nMin) const
Serialize a Sequence.
void WriteOctet (uint8_t octet) const
Function to write in m_serializationResult, after resizing its size.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Static Protected Member Functions inherited from ns3::RrcAsn1Header
static TypeId GetTypeId (void)
Get the type ID.
Protected Attributes inherited from ns3::RrcAsn1Header
int m_messageType
Stores RRC message type, according to 3GPP TS 36.331.
Protected Attributes inherited from ns3::Asn1Header
bool m_isDataSerialized
true if data is serialized
uint8_t m_numSerializationPendingBits
number of pending bits
uint8_t m_serializationPendingBits
pending bits
Buffer m_serializationResult
serialization result
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class manages the serialization/deserialization of RrcConnectionReestablishment IE.
Definition at line 915 of file lte-rrc-header.h.
Constructor & Destructor Documentation
RrcConnectionReestablishmentHeader()
ns3::RrcConnectionReestablishmentHeader::RrcConnectionReestablishmentHeader ()
Definition at line 6118 of file lte-rrc-header.cc.
~RrcConnectionReestablishmentHeader()
ns3::RrcConnectionReestablishmentHeader::~RrcConnectionReestablishmentHeader ()
Definition at line 6122 of file lte-rrc-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::RrcConnectionReestablishmentHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Reimplemented from ns3::RrcDlCcchMessage.
Definition at line 6161 of file lte-rrc-header.cc.
References ns3::Asn1Header::DeserializeChoice(), ns3::RrcDlCcchMessage::DeserializeDlCcchMessage(), ns3::Asn1Header::DeserializeInteger(), ns3::Asn1Header::DeserializeNull(), ns3::RrcAsn1Header::DeserializeRadioResourceConfigDedicated(), ns3::Asn1Header::DeserializeSequence(), ns3::Asn1Header::GetSerializedSize(), m_radioResourceConfigDedicated, m_rrcTransactionIdentifier, and sample-rng-plot::n.
GetMessage()
LteRrcSap::RrcConnectionReestablishment ns3::RrcConnectionReestablishmentHeader::GetMessage () const
Returns a RrcConnectionReestablishment IE from the values in the class attributes.
Returns
A RrcConnectionReestablishment, as defined in LteRrcSap
Definition at line 6228 of file lte-rrc-header.cc.
References m_radioResourceConfigDedicated, m_rrcTransactionIdentifier, ns3::LteRrcSap::RrcConnectionReestablishment::radioResourceConfigDedicated, and ns3::LteRrcSap::RrcConnectionReestablishment::rrcTransactionIdentifier.
Referenced by ns3::LteUeRrcProtocolReal::DoReceivePdcpPdu().
GetRadioResourceConfigDedicated()
LteRrcSap::RadioResourceConfigDedicated ns3::RrcConnectionReestablishmentHeader::GetRadioResourceConfigDedicated () const
Getter for m_radioResourceConfigDedicated attribute.
Returns
m_radioResourceConfigDedicated
Definition at line 6243 of file lte-rrc-header.cc.
References m_radioResourceConfigDedicated.
Referenced by RrcConnectionReestablishmentTestCase::DoRun().
GetRrcTransactionIdentifier()
uint8_t ns3::RrcConnectionReestablishmentHeader::GetRrcTransactionIdentifier () const
Getter for m_rrcTransactionIdentifier attribute.
Returns
m_rrcTransactionIdentifier
Definition at line 6237 of file lte-rrc-header.cc.
References m_rrcTransactionIdentifier.
Referenced by RrcConnectionReestablishmentTestCase::DoRun().
PreSerialize()
void ns3::RrcConnectionReestablishmentHeader::PreSerialize () const virtual
This function serializes class attributes to m_serializationResult local Buffer.
As ASN1 encoding produces a bitstream that does not have a fixed length, this function is needed to store the result, so its length can be retrieved with Header::GetSerializedSize() function. This method is pure virtual in this class (needs to be implemented in child classes) as the meaningful information elements are in the subclasses.
Reimplemented from ns3::RrcDlCcchMessage.
Definition at line 6127 of file lte-rrc-header.cc.
References ns3::Asn1Header::FinalizeSerialization(), m_radioResourceConfigDedicated, m_rrcTransactionIdentifier, ns3::Asn1Header::m_serializationResult, ns3::Asn1Header::SerializeChoice(), ns3::RrcDlCcchMessage::SerializeDlCcchMessage(), ns3::Asn1Header::SerializeInteger(), ns3::RrcAsn1Header::SerializeRadioResourceConfigDedicated(), and ns3::Asn1Header::SerializeSequence().
Print()
void ns3::RrcConnectionReestablishmentHeader::Print (std::ostream & os) const virtual
This function prints the object, for debugging purposes.
Parameters
os The output stream to use (i.e. std::cout)
Reimplemented from ns3::RrcDlCcchMessage.
Definition at line 6212 of file lte-rrc-header.cc.
References m_radioResourceConfigDedicated, m_rrcTransactionIdentifier, and ns3::RrcAsn1Header::Print().
SetMessage()
void ns3::RrcConnectionReestablishmentHeader::SetMessage (LteRrcSap::RrcConnectionReestablishment msg)
Receives a RrcConnectionReestablishment IE and stores the contents into the class attributes.
Parameters
msg The information element to parse
Definition at line 6220 of file lte-rrc-header.cc.
References ns3::Asn1Header::m_isDataSerialized, m_radioResourceConfigDedicated, m_rrcTransactionIdentifier, ns3::LteRrcSap::RrcConnectionReestablishment::radioResourceConfigDedicated, and ns3::LteRrcSap::RrcConnectionReestablishment::rrcTransactionIdentifier.
Referenced by RrcConnectionReestablishmentTestCase::DoRun(), and ns3::LteEnbRrcProtocolReal::DoSendRrcConnectionReestablishment().
Member Data Documentation
m_radioResourceConfigDedicated
LteRrcSap::RadioResourceConfigDedicated ns3::RrcConnectionReestablishmentHeader::m_radioResourceConfigDedicated private
radio resource config dedicated
Definition at line 952 of file lte-rrc-header.h.
Referenced by Deserialize(), GetMessage(), GetRadioResourceConfigDedicated(), PreSerialize(), Print(), and SetMessage().
m_rrcTransactionIdentifier
uint8_t ns3::RrcConnectionReestablishmentHeader::m_rrcTransactionIdentifier private
RRC transaction identifier.
Definition at line 951 of file lte-rrc-header.h.
Referenced by Deserialize(), GetMessage(), GetRrcTransactionIdentifier(), PreSerialize(), Print(), and SetMessage().
The documentation for this class was generated from the following files:
src/lte/model/lte-rrc-header.h
src/lte/model/lte-rrc-header.cc