ns-3: ns3::LogNormalRandomVariable Class Reference
ns3::LogNormalRandomVariable Class Reference
Core » Random Variables
The log-normal distribution Random Number Generator (RNG) that allows stream numbers to be set deterministically.
#include "random-variable-stream.h"
Public Member Functions
LogNormalRandomVariable ()
Creates a log-normal distribution RNG with the default values for mu and sigma.
uint32_t GetInteger (uint32_t mu, uint32_t sigma)
Returns a random unsigned integer from a log-normal distribution with the specified mu and sigma.
virtual uint32_t GetInteger (void)
Returns a random unsigned integer from a log-normal distribution with the current mu and sigma.
double GetMu (void) const
Returns the mu value for the log-normal distribution returned by this RNG stream.
double GetSigma (void) const
Returns the sigma value for the log-normal distribution returned by this RNG stream.
double GetValue (double mu, double sigma)
Returns a random double from a log-normal distribution with the specified mu and sigma.
virtual double GetValue (void)
Returns a random double from a log-normal distribution with the current mu and sigma.
Public Member Functions inherited from ns3::RandomVariableStream
RandomVariableStream ()
Default constructor.
virtual ~RandomVariableStream ()
Destructor.
int64_t GetStream (void) const
Returns the stream number for the RngStream.
bool IsAntithetic (void) const
Check if antithetic values will be generated.
void SetAntithetic (bool isAntithetic)
Specify whether antithetic values should be generated.
void SetStream (int64_t stream)
Specifies the stream number for the RngStream.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::RandomVariableStream
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
double m_mu
The mu value for the log-normal distribution returned by this RNG stream.
double m_sigma
The sigma value for the log-normal distribution returned by this RNG stream.
Additional Inherited Members
Protected Member Functions inherited from ns3::RandomVariableStream
RngStream * Peek (void) const
Get the pointer to the underlying RngStream.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The log-normal distribution Random Number Generator (RNG) that allows stream numbers to be set deterministically.
This class supports the creation of objects that return random numbers from a fixed log-normal distribution. It also supports the generation of single random numbers from various log-normal distributions.
LogNormalRandomVariable defines a random variable with a log-normal distribution. If one takes the natural logarithm of random variable following the log-normal distribution, the obtained values follow a normal distribution.
The probability density function is defined over the interval [0,) as: where and
The and parameters can be calculated instead if the mean and variance are known with the following equations: , and,
Here is an example of how to use this class:
double mu = 5.0;
double sigma = 2.0;
Ptr<LogNormalRandomVariable> x = CreateObject<LogNormalRandomVariable> ();
x->SetAttribute ("Mu", DoubleValue (mu));
x->SetAttribute ("Sigma", DoubleValue (sigma));
// The expected value for the mean of the values returned by a
// log-normally distributed random variable is equal to
//
//                             2
//                   mu + sigma  / 2
//     E[value]  =  e                 .
//
double value = x->GetValue ();
Definition at line 1299 of file random-variable-stream.h.
Constructor & Destructor Documentation
LogNormalRandomVariable()
ns3::LogNormalRandomVariable::LogNormalRandomVariable ()
Creates a log-normal distribution RNG with the default values for mu and sigma.
Definition at line 801 of file random-variable-stream.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
GetInteger() [1/2]
uint32_t ns3::LogNormalRandomVariable::GetInteger (uint32_t mu, uint32_t sigma)
Returns a random unsigned integer from a log-normal distribution with the specified mu and sigma.
Parameters
[in] mu Mu value for the log-normal distribution.
[in] sigma Sigma value for the log-normal distribution.
Returns
A random unsigned integer value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If and are uniform variables over [0,1], then the value that would be returned normally, , is calculated as follows:
For the antithetic case,) and) are the distances that and would be from . The antithetic value returned, , is calculated as follows:
which now involves the distances and are from 1.
Definition at line 882 of file random-variable-stream.cc.
References GetValue(), and NS_LOG_FUNCTION.
GetInteger() [2/2]
uint32_t ns3::LogNormalRandomVariable::GetInteger (void) virtual
Returns a random unsigned integer from a log-normal distribution with the current mu and sigma.
Returns
A random unsigned integer value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If and are uniform variables over [0,1], then the value that would be returned normally, , is calculated as follows:
For the antithetic case,) and) are the distances that and would be from . The antithetic value returned, , is calculated as follows:
which now involves the distances and are from 1.
Implements ns3::RandomVariableStream.
Definition at line 895 of file random-variable-stream.cc.
References GetValue(), m_mu, m_sigma, and NS_LOG_FUNCTION.
GetMu()
double ns3::LogNormalRandomVariable::GetMu (void) const
Returns the mu value for the log-normal distribution returned by this RNG stream.
Returns
The mu value for the log-normal distribution returned by this RNG stream.
Definition at line 809 of file random-variable-stream.cc.
References m_mu, and NS_LOG_FUNCTION.
GetSigma()
double ns3::LogNormalRandomVariable::GetSigma (void) const
Returns the sigma value for the log-normal distribution returned by this RNG stream.
Returns
The sigma value for the log-normal distribution returned by this RNG stream.
Definition at line 815 of file random-variable-stream.cc.
References m_sigma, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::LogNormalRandomVariable::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 784 of file random-variable-stream.cc.
References m_mu, m_sigma, ns3::MakeDoubleAccessor(), and ns3::TypeId::SetParent().
GetValue() [1/2]
double ns3::LogNormalRandomVariable::GetValue (double mu, double sigma)
Returns a random double from a log-normal distribution with the specified mu and sigma.
Parameters
[in] mu Mu value for the log-normal distribution.
[in] sigma Sigma value for the log-normal distribution.
Returns
A floating point random value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If and are uniform variables over [0,1], then the value that would be returned normally, , is calculated as follows:
For the antithetic case,) and) are the distances that and would be from . The antithetic value returned, , is calculated as follows:
which now involves the distances and are from 1.
Definition at line 848 of file random-variable-stream.cc.
References ns3::RandomVariableStream::IsAntithetic(), ns3::normal, NS_LOG_FUNCTION, ns3::RandomVariableStream::Peek(), ns3::RngStream::RandU01(), and sample-rng-plot::x.
GetValue() [2/2]
double ns3::LogNormalRandomVariable::GetValue (void) virtual
Returns a random double from a log-normal distribution with the current mu and sigma.
Returns
A floating point random value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If and are uniform variables over [0,1], then the value that would be returned normally, , is calculated as follows:
For the antithetic case,) and) are the distances that and would be from . The antithetic value returned, , is calculated as follows:
which now involves the distances and are from 1.
Note that we have to re-implement this method here because the method is overloaded above for the two-argument variant and the c++ name resolution rules don't work well with overloads split between parent and child classes.
Implements ns3::RandomVariableStream.
Definition at line 889 of file random-variable-stream.cc.
References m_mu, m_sigma, and NS_LOG_FUNCTION.
Referenced by GetInteger().
Member Data Documentation
m_mu
double ns3::LogNormalRandomVariable::m_mu private
The mu value for the log-normal distribution returned by this RNG stream.
Definition at line 1469 of file random-variable-stream.h.
Referenced by GetInteger(), GetMu(), GetTypeId(), and GetValue().
m_sigma
double ns3::LogNormalRandomVariable::m_sigma private
The sigma value for the log-normal distribution returned by this RNG stream.
Definition at line 1472 of file random-variable-stream.h.
Referenced by GetInteger(), GetSigma(), GetTypeId(), and GetValue().
The documentation for this class was generated from the following files:
src/core/model/random-variable-stream.h
src/core/model/random-variable-stream.cc