ns-3: ns3::dot11s::MeshHeader Class Reference
ns3::dot11s::MeshHeader Class Reference
Mesh Device » IEEE 802.11s draft
Mesh Control field, see Section 8.2.4.7.3 IEEE 802.11-2012.
#include "dot11s-mac-header.h"
Public Member Functions
MeshHeader ()
~MeshHeader ()
virtual uint32_t Deserialize (Buffer::Iterator start)
Mac48Address GetAddr4 () const
Get extended address 4.
Mac48Address GetAddr5 () const
Get extended address 5.
Mac48Address GetAddr6 () const
Get extended address 6.
uint8_t GetAddressExt () const
Get Address Extension Mode.
virtual TypeId GetInstanceTypeId () const
Get the most derived TypeId for this Object.
uint32_t GetMeshSeqno () const
Get the four-byte mesh sequence number.
uint8_t GetMeshTtl () const
Get mesh TTL function subfield value.
virtual uint32_t GetSerializedSize () const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetAddr4 (Mac48Address address)
Set extended address 4.
void SetAddr5 (Mac48Address address)
Set extended address 5.
void SetAddr6 (Mac48Address address)
Set extended address 6.
void SetAddressExt (uint8_t num_of_addresses)
Set Address Extension Mode.
void SetMeshSeqno (uint32_t seqno)
Set four-byte mesh sequence number.
void SetMeshTtl (uint8_t TTL)
Set mesh TTL subfield corresponding to the remaining number of hops the MSDU/MMPDU is forwarded.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Mac48Address m_addr4
MAC address 4.
Mac48Address m_addr5
MAC address 5.
Mac48Address m_addr6
MAC address 6.
uint8_t m_meshFlags
mesh flags
uint32_t m_meshSeqno
mesh sequence no
uint8_t m_meshTtl
mesh TTL
Friends
bool operator== (const MeshHeader &a, const MeshHeader &b)
equality operator
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Mesh Control field, see Section 8.2.4.7.3 IEEE 802.11-2012.
Header format: | Mesh flags: 1 | TTL: 1 | Sequence number: 4 | Address ext.: 0, 6, or 12 |
Definition at line 37 of file dot11s-mac-header.h.
Constructor & Destructor Documentation
MeshHeader()
ns3::dot11s::MeshHeader::MeshHeader ()
Definition at line 40 of file dot11s-mac-header.cc.
~MeshHeader()
ns3::dot11s::MeshHeader::~MeshHeader ()
Definition at line 45 of file dot11s-mac-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::dot11s::MeshHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 142 of file dot11s-mac-header.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_addr4, m_addr5, m_addr6, m_meshFlags, m_meshSeqno, m_meshTtl, ns3::ReadFrom(), ns3::Buffer::Iterator::ReadLsbtohU32(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetAddr4()
Mac48Address ns3::dot11s::MeshHeader::GetAddr4 () const
Get extended address 4.
Returns
the MAC address
Definition at line 69 of file dot11s-mac-header.cc.
References m_addr4.
GetAddr5()
Mac48Address ns3::dot11s::MeshHeader::GetAddr5 () const
Get extended address 5.
Returns
the MAC address
Definition at line 74 of file dot11s-mac-header.cc.
References m_addr5.
GetAddr6()
Mac48Address ns3::dot11s::MeshHeader::GetAddr6 () const
Get extended address 6.
Returns
the MAC address
Definition at line 79 of file dot11s-mac-header.cc.
References m_addr6.
GetAddressExt()
uint8_t ns3::dot11s::MeshHeader::GetAddressExt () const
Get Address Extension Mode.
Returns
the address extension mode value
Definition at line 110 of file dot11s-mac-header.cc.
References m_meshFlags.
Referenced by GetSerializedSize(), ns3::dot11s::HwmpProtocolMac::ReceiveData(), and Serialize().
GetInstanceTypeId()
TypeId ns3::dot11s::MeshHeader::GetInstanceTypeId () const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 49 of file dot11s-mac-header.cc.
References GetTypeId().
GetMeshSeqno()
uint32_t ns3::dot11s::MeshHeader::GetMeshSeqno () const
Get the four-byte mesh sequence number.
Returns
the sequence number
Definition at line 89 of file dot11s-mac-header.cc.
References m_meshSeqno.
Referenced by ns3::dot11s::HwmpProtocolMac::ReceiveData().
GetMeshTtl()
uint8_t ns3::dot11s::MeshHeader::GetMeshTtl () const
Get mesh TTL function subfield value.
Returns
the TTL value
Definition at line 99 of file dot11s-mac-header.cc.
References m_meshTtl.
Referenced by ns3::dot11s::HwmpProtocolMac::ReceiveData().
GetSerializedSize()
uint32_t ns3::dot11s::MeshHeader::GetSerializedSize () const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 115 of file dot11s-mac-header.cc.
References GetAddressExt().
GetTypeId()
TypeId ns3::dot11s::MeshHeader::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 32 of file dot11s-mac-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::dot11s::MeshHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 165 of file dot11s-mac-header.cc.
References m_addr4, m_addr5, m_addr6, m_meshFlags, m_meshSeqno, and m_meshTtl.
Serialize()
void ns3::dot11s::MeshHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 120 of file dot11s-mac-header.cc.
References GetAddressExt(), m_addr4, m_addr5, m_addr6, m_meshFlags, m_meshSeqno, m_meshTtl, visualizer.core::start(), ns3::Buffer::Iterator::WriteHtolsbU32(), ns3::WriteTo(), and ns3::Buffer::Iterator::WriteU8().
SetAddr4()
void ns3::dot11s::MeshHeader::SetAddr4 (Mac48Address address)
Set extended address 4.
Parameters
address the MAC address to set
Definition at line 54 of file dot11s-mac-header.cc.
References first::address, and m_addr4.
Referenced by MeshHeaderTest::DoRun().
SetAddr5()
void ns3::dot11s::MeshHeader::SetAddr5 (Mac48Address address)
Set extended address 5.
Parameters
address the MAC address
Definition at line 59 of file dot11s-mac-header.cc.
References first::address, and m_addr5.
Referenced by MeshHeaderTest::DoRun().
SetAddr6()
void ns3::dot11s::MeshHeader::SetAddr6 (Mac48Address address)
Set extended address 6.
Parameters
address the MAC address
Definition at line 64 of file dot11s-mac-header.cc.
References first::address, and m_addr6.
Referenced by MeshHeaderTest::DoRun().
SetAddressExt()
void ns3::dot11s::MeshHeader::SetAddressExt (uint8_t num_of_addresses)
Set Address Extension Mode.
Parameters
num_of_addresses value between 0 and 3 for the two-bit field
Definition at line 104 of file dot11s-mac-header.cc.
References m_meshFlags, and NS_ASSERT.
Referenced by MeshHeaderTest::DoRun().
SetMeshSeqno()
void ns3::dot11s::MeshHeader::SetMeshSeqno (uint32_t seqno)
Set four-byte mesh sequence number.
Parameters
seqno the sequence number to set
Definition at line 84 of file dot11s-mac-header.cc.
References m_meshSeqno.
Referenced by MeshHeaderTest::DoRun(), and ns3::dot11s::HwmpProtocolMac::UpdateOutcomingFrame().
SetMeshTtl()
void ns3::dot11s::MeshHeader::SetMeshTtl (uint8_t TTL)
Set mesh TTL subfield corresponding to the remaining number of hops the MSDU/MMPDU is forwarded.
Parameters
TTL the TTL value to set
Definition at line 94 of file dot11s-mac-header.cc.
References m_meshTtl.
Referenced by MeshHeaderTest::DoRun(), and ns3::dot11s::HwmpProtocolMac::UpdateOutcomingFrame().
Friends And Related Function Documentation
operator==
bool operator== (const MeshHeader & a, const MeshHeader & b) friend
equality operator
Parameters
a left hand side
b right hand side
Returns
true if equal
Definition at line 172 of file dot11s-mac-header.cc.
Member Data Documentation
m_addr4
Mac48Address ns3::dot11s::MeshHeader::m_addr4 private
MAC address 4.
Definition at line 123 of file dot11s-mac-header.h.
Referenced by Deserialize(), GetAddr4(), ns3::dot11s::operator==(), Print(), Serialize(), and SetAddr4().
m_addr5
Mac48Address ns3::dot11s::MeshHeader::m_addr5 private
MAC address 5.
Definition at line 124 of file dot11s-mac-header.h.
Referenced by Deserialize(), GetAddr5(), ns3::dot11s::operator==(), Print(), Serialize(), and SetAddr5().
m_addr6
Mac48Address ns3::dot11s::MeshHeader::m_addr6 private
MAC address 6.
Definition at line 125 of file dot11s-mac-header.h.
Referenced by Deserialize(), GetAddr6(), ns3::dot11s::operator==(), Print(), Serialize(), and SetAddr6().
m_meshFlags
uint8_t ns3::dot11s::MeshHeader::m_meshFlags private
mesh flags
Definition at line 120 of file dot11s-mac-header.h.
Referenced by Deserialize(), GetAddressExt(), ns3::dot11s::operator==(), Print(), Serialize(), and SetAddressExt().
m_meshSeqno
uint32_t ns3::dot11s::MeshHeader::m_meshSeqno private
mesh sequence no
Definition at line 122 of file dot11s-mac-header.h.
Referenced by Deserialize(), GetMeshSeqno(), ns3::dot11s::operator==(), Print(), Serialize(), and SetMeshSeqno().
m_meshTtl
uint8_t ns3::dot11s::MeshHeader::m_meshTtl private
mesh TTL
Definition at line 121 of file dot11s-mac-header.h.
Referenced by Deserialize(), GetMeshTtl(), ns3::dot11s::operator==(), Print(), Serialize(), and SetMeshTtl().
The documentation for this class was generated from the following files:
src/mesh/model/dot11s/dot11s-mac-header.h
src/mesh/model/dot11s/dot11s-mac-header.cc