ns-3: ns3::WifiRemoteStationInfo Class Reference
ns3::WifiRemoteStationInfo Class Reference
TID independent remote station statistics.
#include "wifi-remote-station-info.h"
Public Member Functions
WifiRemoteStationInfo ()
virtual ~WifiRemoteStationInfo ()
double GetFrameErrorRate () const
Return frame error rate (probability that frame is corrupted due to transmission error).
void NotifyTxFailed ()
Updates average frame error rate when final data or RTS has failed.
void NotifyTxSuccess (uint32_t retryCounter)
Updates average frame error rate when data or RTS was transmitted successfully.
Private Member Functions
double CalculateAveragingCoefficient ()
Calculate averaging coefficient for frame error rate.
Private Attributes
double m_failAvg
moving percentage of failed frames
Time m_lastUpdate
when last update has occurred
Time m_memoryTime
averaging coefficient depends on the memory time
Detailed Description
TID independent remote station statistics.
Structure is similar to struct sta_info in Linux kernel (see net/mac80211/sta_info.h)
Definition at line 35 of file wifi-remote-station-info.h.
Constructor & Destructor Documentation
WifiRemoteStationInfo()
ns3::WifiRemoteStationInfo::WifiRemoteStationInfo ()
Definition at line 26 of file wifi-remote-station-info.cc.
~WifiRemoteStationInfo()
ns3::WifiRemoteStationInfo::~WifiRemoteStationInfo () virtual
Definition at line 33 of file wifi-remote-station-info.cc.
Member Function Documentation
CalculateAveragingCoefficient()
double ns3::WifiRemoteStationInfo::CalculateAveragingCoefficient () private
Calculate averaging coefficient for frame error rate.
Depends on time of the last update.
Attention
Calling this method twice gives different results, because it resets time of last update.
Returns
average coefficient for frame error rate
Definition at line 38 of file wifi-remote-station-info.cc.
References ns3::Time::GetMicroSeconds(), m_lastUpdate, m_memoryTime, and ns3::Simulator::Now().
Referenced by NotifyTxFailed(), and NotifyTxSuccess().
GetFrameErrorRate()
double ns3::WifiRemoteStationInfo::GetFrameErrorRate () const
Return frame error rate (probability that frame is corrupted due to transmission error).
Returns
the frame error rate
Definition at line 60 of file wifi-remote-station-info.cc.
References m_failAvg.
NotifyTxFailed()
void ns3::WifiRemoteStationInfo::NotifyTxFailed ()
Updates average frame error rate when final data or RTS has failed.
Definition at line 53 of file wifi-remote-station-info.cc.
References CalculateAveragingCoefficient(), and m_failAvg.
Referenced by ns3::WifiRemoteStationManager::ReportFinalDataFailed(), and ns3::WifiRemoteStationManager::ReportFinalRtsFailed().
NotifyTxSuccess()
void ns3::WifiRemoteStationInfo::NotifyTxSuccess (uint32_t retryCounter)
Updates average frame error rate when data or RTS was transmitted successfully.
Parameters
retryCounter is SLRC or SSRC value at the moment of success transmission.
Definition at line 46 of file wifi-remote-station-info.cc.
References CalculateAveragingCoefficient(), and m_failAvg.
Referenced by ns3::WifiRemoteStationManager::ReportDataOk(), and ns3::WifiRemoteStationManager::ReportRtsOk().
Member Data Documentation
m_failAvg
double ns3::WifiRemoteStationInfo::m_failAvg private
moving percentage of failed frames
Definition at line 69 of file wifi-remote-station-info.h.
Referenced by GetFrameErrorRate(), NotifyTxFailed(), and NotifyTxSuccess().
m_lastUpdate
Time ns3::WifiRemoteStationInfo::m_lastUpdate private
when last update has occurred
Definition at line 68 of file wifi-remote-station-info.h.
Referenced by CalculateAveragingCoefficient().
m_memoryTime
Time ns3::WifiRemoteStationInfo::m_memoryTime private
averaging coefficient depends on the memory time
Definition at line 67 of file wifi-remote-station-info.h.
Referenced by CalculateAveragingCoefficient().
The documentation for this class was generated from the following files:
src/wifi/model/wifi-remote-station-info.h
src/wifi/model/wifi-remote-station-info.cc