ns-3: ns3::lorawan::GatewayLorawanMac Class Reference
ns3::lorawan::GatewayLorawanMac Class Reference
#include "gateway-lorawan-mac.h"
Public Member Functions
GatewayLorawanMac ()
virtual ~GatewayLorawanMac ()
virtual void FailedReception (Ptr< Packet const > packet)
Function called by lower layers to inform this layer that reception of a packet we were locked on failed.
Time GetWaitingTime (double frequency)
Return the next time at which we will be able to transmit.
bool IsTransmitting (void)
virtual void Receive (Ptr< Packet const > packet)
Receive a packet from the lower layer.
virtual void Send (Ptr< Packet > packet)
Send a packet.
virtual void TxFinished (Ptr< Packet const > packet)
Perform actions after sending a packet.
Public Member Functions inherited from ns3::lorawan::LorawanMac
LorawanMac ()
virtual ~LorawanMac ()
double GetBandwidthFromDataRate (uint8_t dataRate)
Get the BW corresponding to a data rate, based on this MAC's region.
double GetDbmForTxPower (uint8_t txPower)
Get the transmission power in dBm that corresponds, in this region, to the encoded 8-bit txPower.
Ptr< NetDevice > GetDevice (void)
Get the device this MAC layer is installed on.
LogicalLoraChannelHelper GetLogicalLoraChannelHelper (void)
Get the logical lora channel helper associated with this MAC.
int GetNPreambleSymbols (void)
Get the number of PHY preamble symbols this MAC is set to use.
Ptr< LoraPhy > GetPhy (void)
Get the underlying PHY layer.
uint8_t GetSfFromDataRate (uint8_t dataRate)
Get the SF corresponding to a data rate, based on this MAC's region.
void SetBandwidthForDataRate (std::vector< double > bandwidthForDataRate)
Set the vector to use to check up correspondence between bandwidth and DataRate.
void SetDevice (Ptr< NetDevice > device)
Set the device this MAC layer is installed on.
void SetLogicalLoraChannelHelper (LogicalLoraChannelHelper helper)
Set the LogicalLoraChannelHelper this MAC instance will use.
void SetMaxAppPayloadForDataRate (std::vector< uint32_t > maxAppPayloadForDataRate)
Set the maximum App layer payload for a set DataRate.
void SetNPreambleSymbols (int nPreambleSymbols)
Set the number of PHY preamble symbols this MAC is set to use.
void SetPhy (Ptr< LoraPhy > phy)
Set the underlying PHY layer.
void SetReplyDataRateMatrix (ReplyDataRateMatrix replyDataRateMatrix)
Set the matrix to use when deciding with which DataRate to respond.
void SetSfForDataRate (std::vector< uint8_t > sfForDataRate)
Set the vector to use to check up correspondence between SF and DataRate.
void SetTxDbmForTxPower (std::vector< double > txDbmForTxPower)
Set the vector to use to check up which transmission power in Dbm corresponds to a certain TxPower value in this MAC's region.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::lorawan::LorawanMac
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Public Types inherited from ns3::lorawan::LorawanMac
typedef std::array< std::array< uint8_t, 6 >, 8 > ReplyDataRateMatrix
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::lorawan::LorawanMac
std::vector< double > m_bandwidthForDataRate
A vector holding the bandwidth each Data Rate corresponds to.
TracedCallback< Ptr< const Packet > > m_cannotSendBecauseDutyCycle
The trace source that is fired when a packet cannot be sent because of duty cycle limitations.
LogicalLoraChannelHelper m_channelHelper
The LogicalLoraChannelHelper instance that is assigned to this MAC.
Ptr< NetDevice > m_device
The device this MAC layer is installed on.
std::vector< uint32_t > m_maxAppPayloadForDataRate
A vector holding the maximum app payload size that corresponds to a certain DataRate.
int m_nPreambleSymbols
The number of symbols to use in the PHY preamble.
Ptr< LoraPhy > m_phy
The PHY instance that sits under this MAC layer.
TracedCallback< Ptr< const Packet > > m_receivedPacket
Trace source that is fired when a packet reaches the MAC layer.
ReplyDataRateMatrix m_replyDataRateMatrix
The matrix that decides the DR the GW will use in a reply based on the ED's sending DR and on the value of the RX1DROffset parameter.
TracedCallback< Ptr< Packet const > > m_sentNewPacket
Trace source that is fired when a new APP layer packet arrives at the MAC layer.
std::vector< uint8_t > m_sfForDataRate
A vector holding the SF each Data Rate corresponds to.
std::vector< double > m_txDbmForTxPower
A vector holding the power that corresponds to a certain TxPower value.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 30 of file gateway-lorawan-mac.h.
Constructor & Destructor Documentation
GatewayLorawanMac()
ns3::lorawan::GatewayLorawanMac::GatewayLorawanMac ()
Definition at line 44 of file gateway-lorawan-mac.cc.
References NS_LOG_FUNCTION.
~GatewayLorawanMac()
ns3::lorawan::GatewayLorawanMac::~GatewayLorawanMac () virtual
Definition at line 49 of file gateway-lorawan-mac.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
FailedReception()
void ns3::lorawan::GatewayLorawanMac::FailedReception (Ptr< Packet const > packet) virtual
Function called by lower layers to inform this layer that reception of a packet we were locked on failed.
Parameters
packet the packet we failed to receive
Implements ns3::lorawan::LorawanMac.
Definition at line 139 of file gateway-lorawan-mac.cc.
References NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::lorawan::GatewayLorawanMac::GetTypeId (void) static
Definition at line 35 of file gateway-lorawan-mac.cc.
References ns3::TypeId::SetParent().
GetWaitingTime()
Time ns3::lorawan::GatewayLorawanMac::GetWaitingTime (double frequency)
Return the next time at which we will be able to transmit.
Returns
The next transmission time.
Definition at line 151 of file gateway-lorawan-mac.cc.
References ns3::lorawan::LogicalLoraChannelHelper::GetWaitingTime(), ns3::lorawan::LorawanMac::m_channelHelper, and NS_LOG_FUNCTION_NOARGS.
IsTransmitting()
bool ns3::lorawan::GatewayLorawanMac::IsTransmitting (void)
Definition at line 107 of file gateway-lorawan-mac.cc.
References ns3::lorawan::LorawanMac::m_phy.
Receive()
void ns3::lorawan::GatewayLorawanMac::Receive (Ptr< Packet const > packet) virtual
Receive a packet from the lower layer.
Parameters
packet the received packet
Implements ns3::lorawan::LorawanMac.
Definition at line 113 of file gateway-lorawan-mac.cc.
References ns3::lorawan::LorawanMacHeader::IsUplink(), ns3::lorawan::LorawanMac::m_device, ns3::lorawan::LorawanMac::m_receivedPacket, NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::Packet::PeekHeader().
Send()
void ns3::lorawan::GatewayLorawanMac::Send (Ptr< Packet > packet) virtual
Send a packet.
Parameters
packet The packet to send.
Implements ns3::lorawan::LorawanMac.
Definition at line 55 of file gateway-lorawan-mac.cc.
References ns3::lorawan::LogicalLoraChannelHelper::AddEvent(), ns3::Packet::AddPacketTag(), aloha::duration, ns3::lorawan::LorawanMac::GetBandwidthFromDataRate(), ns3::lorawan::LoraTag::GetDataRate(), ns3::lorawan::LoraTag::GetFrequency(), ns3::lorawan::LorawanMac::GetSfFromDataRate(), ns3::lorawan::LogicalLoraChannelHelper::GetTxPowerForChannel(), ns3::lorawan::LogicalLoraChannelHelper::GetWaitingTime(), ns3::lorawan::LorawanMac::m_channelHelper, ns3::lorawan::LorawanMac::m_phy, ns3::lorawan::LorawanMac::m_sentNewPacket, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_WARN, aloha::params, and ns3::Packet::RemovePacketTag().
TxFinished()
void ns3::lorawan::GatewayLorawanMac::TxFinished (Ptr< Packet const > packet) virtual
Perform actions after sending a packet.
Parameters
packet The packet that just finished transmission.
Implements ns3::lorawan::LorawanMac.
Definition at line 145 of file gateway-lorawan-mac.cc.
References NS_LOG_FUNCTION_NOARGS.
The documentation for this class was generated from the following files:
src/lorawan/model/gateway-lorawan-mac.h
src/lorawan/model/gateway-lorawan-mac.cc