ns-3: ns3::PacketSocketTag Class Reference
ns3::PacketSocketTag Class Reference
This class implements a tag that carries the dest address of a packet and the packet type.
#include "packet-socket.h"
Public Member Functions
PacketSocketTag ()
Create an empty PacketSocketTag.
virtual void Deserialize (TagBuffer i)
Address GetDestAddress (void) const
Get the destination address of the corresponding packet.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
NetDevice::PacketType GetPacketType (void) const
Get the packet type.
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer i) const
void SetDestAddress (Address a)
Set the destination address of the corresponding packet.
void SetPacketType (NetDevice::PacketType t)
Set the packet type.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Address m_destAddr
Destination address.
NetDevice::PacketType m_packetType
Packet type.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class implements a tag that carries the dest address of a packet and the packet type.
Definition at line 219 of file packet-socket.h.
Constructor & Destructor Documentation
PacketSocketTag()
ns3::PacketSocketTag::PacketSocketTag ()
Create an empty PacketSocketTag.
Definition at line 534 of file packet-socket.cc.
Member Function Documentation
Deserialize()
void ns3::PacketSocketTag::Deserialize (TagBuffer i) virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 591 of file packet-socket.cc.
References ns3::Address::Deserialize(), m_destAddr, m_packetType, and ns3::TagBuffer::ReadU8().
GetDestAddress()
Address ns3::PacketSocketTag::GetDestAddress (void) const
Get the destination address of the corresponding packet.
Returns
the destination address of the corresponding packet
Definition at line 557 of file packet-socket.cc.
References m_destAddr.
GetInstanceTypeId()
TypeId ns3::PacketSocketTag::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 575 of file packet-socket.cc.
References GetTypeId().
GetPacketType()
NetDevice::PacketType ns3::PacketSocketTag::GetPacketType (void) const
Get the packet type.
Returns
the packet type of the corresponding packet
Definition at line 545 of file packet-socket.cc.
References m_packetType.
GetSerializedSize()
uint32_t ns3::PacketSocketTag::GetSerializedSize (void) const virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 580 of file packet-socket.cc.
References ns3::Address::GetSerializedSize(), and m_destAddr.
GetTypeId()
TypeId ns3::PacketSocketTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 565 of file packet-socket.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::PacketSocketTag::Print (std::ostream & os) const virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 597 of file packet-socket.cc.
References m_packetType.
Serialize()
void ns3::PacketSocketTag::Serialize (TagBuffer i) const virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 585 of file packet-socket.cc.
References m_destAddr, m_packetType, ns3::Address::Serialize(), and ns3::TagBuffer::WriteU8().
SetDestAddress()
void ns3::PacketSocketTag::SetDestAddress (Address a)
Set the destination address of the corresponding packet.
Parameters
a the destination address of the corresponding packet
Definition at line 551 of file packet-socket.cc.
References m_destAddr.
Referenced by ns3::PacketSocket::ForwardUp().
SetPacketType()
void ns3::PacketSocketTag::SetPacketType (NetDevice::PacketType t)
Set the packet type.
Parameters
t the packet type of the corresponding packet
Definition at line 539 of file packet-socket.cc.
References m_packetType.
Referenced by ns3::PacketSocket::ForwardUp().
Member Data Documentation
m_destAddr
Address ns3::PacketSocketTag::m_destAddr private
Destination address.
Definition at line 260 of file packet-socket.h.
Referenced by Deserialize(), GetDestAddress(), GetSerializedSize(), Serialize(), and SetDestAddress().
m_packetType
NetDevice::PacketType ns3::PacketSocketTag::m_packetType private
Packet type.
Definition at line 259 of file packet-socket.h.
Referenced by Deserialize(), GetPacketType(), Print(), Serialize(), and SetPacketType().
The documentation for this class was generated from the following files:
src/network/utils/packet-socket.h
src/network/utils/packet-socket.cc