ns-3: ns3::VhtCapabilities Class Reference
ns3::VhtCapabilities Class Reference
Wifi Models
#include "vht-capabilities.h"
Public Member Functions
VhtCapabilities ()
uint8_t DeserializeInformationField (Buffer::Iterator start, uint8_t length)
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
WifiInformationElementId ElementId () const
uint8_t GetInformationFieldSize () const
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
uint32_t GetMaxAmpduLength (void) const
Return the maximum A-MPDU length.
uint16_t GetMaxMpduLength (void) const
Get the maximum MPDU length.
uint16_t GetRxHighestSupportedLgiDataRate () const
Get the receive highest supported LGI data rate.
uint8_t GetRxLdpc () const
Get the receive LDPC.
uint8_t GetRxStbc () const
Get the receive STBC.
uint16_t GetSerializedSize () const
uint8_t GetSupportedChannelWidthSet () const
Get the supported channel width set.
uint64_t GetSupportedMcsAndNssSet () const
Return the MCS and NSS field in the VHT Capabilities information element.
uint8_t GetTxStbc () const
Get the transmit STBC.
uint32_t GetVhtCapabilitiesInfo () const
Return the VHT Capabilities Info field in the VHT Capabilities information element.
bool IsSupportedMcs (uint8_t mcs, uint8_t nss) const
Get the is MCS supported.
bool IsSupportedRxMcs (uint8_t mcs) const
Returns true if receive MCS is supported.
bool IsSupportedTxMcs (uint8_t mcs) const
Returns true if transmit MCS is supported.
Buffer::Iterator Serialize (Buffer::Iterator start) const
void SerializeInformationField (Buffer::Iterator start) const
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
void SetMaxAmpduLength (uint32_t maxAmpduLength)
Set the maximum AMPDU length.
void SetMaxMpduLength (uint16_t length)
Set the maximum MPDU length.
void SetRxHighestSupportedLgiDataRate (uint16_t supportedDatarate)
Set the receive highest supported LGI data rate.
void SetRxLdpc (uint8_t rxLdpc)
Set the receive LDPC.
void SetRxMcsMap (uint8_t mcs, uint8_t nss)
void SetRxStbc (uint8_t rxStbc)
Set the receive STBC.
void SetShortGuardIntervalFor160Mhz (uint8_t shortGuardInterval)
Set the short guard interval 160 MHz.
void SetShortGuardIntervalFor80Mhz (uint8_t shortGuardInterval)
Set the short guard interval 80 MHz.
void SetSupportedChannelWidthSet (uint8_t channelWidthSet)
Set the supported channel width set.
void SetSupportedMcsAndNssSet (uint64_t ctrl)
Set the MCS and NSS field in the VHT Capabilities information element.
void SetTxHighestSupportedLgiDataRate (uint16_t supportedDatarate)
Set the transmit highest supported LGI data rate.
void SetTxMcsMap (uint8_t mcs, uint8_t nss)
void SetTxStbc (uint8_t txStbc)
Set the transmit STBC.
void SetVhtCapabilitiesInfo (uint32_t ctrl)
Set the VHT Capabilities Info field in the VHT Capabilities information element.
void SetVhtSupported (uint8_t vhtSupported)
Set the VHT supported field.
Public Member Functions inherited from ns3::WifiInformationElement
virtual ~WifiInformationElement ()
Buffer::Iterator Deserialize (Buffer::Iterator i)
Deserialize entire IE, which must be present.
Buffer::Iterator DeserializeIfPresent (Buffer::Iterator i)
Deserialize entire IE if it is present.
virtual WifiInformationElementId ElementIdExt () const
uint16_t GetSerializedSize () const
Get the size of the serialized IE including Element ID and length fields.
virtual bool operator== (WifiInformationElement const &a) const
Compare two IEs for equality by ID & Length, and then through memcmp of serialised version.
virtual void Print (std::ostream &os) const
Generate human-readable form of IE.
Buffer::Iterator Serialize (Buffer::Iterator i) const
Serialize entire IE including Element ID and length fields.
Public Member Functions inherited from ns3::SimpleRefCount< WifiInformationElement >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
uint8_t m_beamformeeStsCapable
beamformee STS capable
uint8_t m_htcVhtCapable
HTC VHT capable.
uint8_t m_maxAmpduLengthExponent
maximum A-MPDU length exponent
uint8_t m_maxMpduLength
maximum MPDU length
uint8_t m_muBeamformeeCapable
MU beamformee capable.
uint8_t m_muBeamformerCapable
MU beamformer capable.
uint8_t m_numberOfSoundingDimensions
number of sounding dimensions
uint8_t m_rxAntennaPatternConsistency
receive antenna pattern consistency
uint16_t m_rxHighestSupportedLongGuardIntervalDataRate
receive highest supported long guard interval data rate
uint8_t m_rxLdpc
receive LDPC
std::vector< uint8_t > m_rxMcsMap
receive MCS map
uint8_t m_rxStbc
receive STBC
uint8_t m_shortGuardIntervalFor160Mhz
short guard interval for 160 MHz
uint8_t m_shortGuardIntervalFor80Mhz
short guard interval for 80 MHz
uint8_t m_suBeamformeeCapable
SU beamformee capable.
uint8_t m_suBeamformerCapable
SU beamformer capable.
uint8_t m_supportedChannelWidthSet
supported channel width set
uint8_t m_txAntennaPatternConsistency
transmit antenna pattern consistency
uint16_t m_txHighestSupportedLongGuardIntervalDataRate
transmit highest supported long guard interval data rate
std::vector< uint8_t > m_txMcsMap
transmit MCS map
uint8_t m_txStbc
transmit STBC
uint8_t m_vhtLinkAdaptationCapable
VHT link adaptation capable.
uint8_t m_vhtSupported
This is used to decide if this element should be added to the frame or not.
uint8_t m_vhtTxopPs
VHT TXOP PS.
Detailed Description
The IEEE 802.11ac VHT Capabilities
Definition at line 34 of file vht-capabilities.h.
Constructor & Destructor Documentation
VhtCapabilities()
ns3::VhtCapabilities::VhtCapabilities ()
Definition at line 26 of file vht-capabilities.cc.
References m_rxMcsMap, and m_txMcsMap.
Member Function Documentation
DeserializeInformationField()
uint8_t ns3::VhtCapabilities::DeserializeInformationField (Buffer::Iterator start, uint8_t length) virtual
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
length
Returns
the number of bytes read
Implements ns3::WifiInformationElement.
Definition at line 111 of file vht-capabilities.cc.
References ns3::Buffer::Iterator::ReadLsbtohU32(), ns3::Buffer::Iterator::ReadLsbtohU64(), SetSupportedMcsAndNssSet(), SetVhtCapabilitiesInfo(), and visualizer.core::start().
ElementId()
WifiInformationElementId ns3::VhtCapabilities::ElementId () const virtual
Returns
Own unique Element ID
Implements ns3::WifiInformationElement.
Definition at line 60 of file vht-capabilities.cc.
References IE_VHT_CAPABILITIES.
GetInformationFieldSize()
uint8_t ns3::VhtCapabilities::GetInformationFieldSize () const virtual
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
This is the value that will appear in the second octet of the entire IE - the length field)
Returns
the length of serialized information
Implements ns3::WifiInformationElement.
Definition at line 72 of file vht-capabilities.cc.
References m_vhtSupported, and NS_ASSERT.
GetMaxAmpduLength()
uint32_t ns3::VhtCapabilities::GetMaxAmpduLength (void) const
Return the maximum A-MPDU length.
Returns
the maximum A-MPDU length in bytes
Definition at line 388 of file vht-capabilities.cc.
References m_maxAmpduLengthExponent.
GetMaxMpduLength()
uint16_t ns3::VhtCapabilities::GetMaxMpduLength (void) const
Get the maximum MPDU length.
Returns
the maximum MPDU length in bytes
Definition at line 346 of file vht-capabilities.cc.
References m_maxMpduLength, and NS_ABORT_MSG.
GetRxHighestSupportedLgiDataRate()
uint16_t ns3::VhtCapabilities::GetRxHighestSupportedLgiDataRate () const
Get the receive highest supported LGI data rate.
Returns
the receive highest supported LGI data rate.
Definition at line 413 of file vht-capabilities.cc.
References m_rxHighestSupportedLongGuardIntervalDataRate.
Referenced by ns3::ApWifiMac::Receive(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetRxLdpc()
uint8_t ns3::VhtCapabilities::GetRxLdpc () const
Get the receive LDPC.
Returns
the receive LDPC
Definition at line 370 of file vht-capabilities.cc.
References m_rxLdpc.
GetRxStbc()
uint8_t ns3::VhtCapabilities::GetRxStbc () const
Get the receive STBC.
Returns
the receive STBC
Definition at line 376 of file vht-capabilities.cc.
References m_rxStbc.
GetSerializedSize()
uint16_t ns3::VhtCapabilities::GetSerializedSize () const
Definition at line 90 of file vht-capabilities.cc.
References ns3::WifiInformationElement::GetSerializedSize(), and m_vhtSupported.
Referenced by ns3::MgtAssocRequestHeader::GetSerializedSize(), ns3::MgtReassocRequestHeader::GetSerializedSize(), ns3::MgtAssocResponseHeader::GetSerializedSize(), ns3::MgtProbeRequestHeader::GetSerializedSize(), and ns3::MgtProbeResponseHeader::GetSerializedSize().
GetSupportedChannelWidthSet()
uint8_t ns3::VhtCapabilities::GetSupportedChannelWidthSet () const
Get the supported channel width set.
Returns
the supported channel width set
Definition at line 364 of file vht-capabilities.cc.
References m_supportedChannelWidthSet.
Referenced by ns3::WifiRemoteStationManager::AddStationVhtCapabilities().
GetSupportedMcsAndNssSet()
uint64_t ns3::VhtCapabilities::GetSupportedMcsAndNssSet () const
Return the MCS and NSS field in the VHT Capabilities information element.
Returns
the MCS and NSS field in the VHT Capabilities information element
Definition at line 191 of file vht-capabilities.cc.
References m_rxHighestSupportedLongGuardIntervalDataRate, m_rxMcsMap, m_txHighestSupportedLongGuardIntervalDataRate, m_txMcsMap, and sample-rng-plot::n.
Referenced by ns3::operator<<(), and SerializeInformationField().
GetTxStbc()
uint8_t ns3::VhtCapabilities::GetTxStbc () const
Get the transmit STBC.
Returns
the transmit STBC
Definition at line 382 of file vht-capabilities.cc.
References m_txStbc.
GetVhtCapabilitiesInfo()
uint32_t ns3::VhtCapabilities::GetVhtCapabilitiesInfo () const
Return the VHT Capabilities Info field in the VHT Capabilities information element.
Returns
the VHT Capabilities Info field in the VHT Capabilities information element
Definition at line 147 of file vht-capabilities.cc.
References m_beamformeeStsCapable, m_htcVhtCapable, m_maxAmpduLengthExponent, m_maxMpduLength, m_muBeamformeeCapable, m_muBeamformerCapable, m_numberOfSoundingDimensions, m_rxAntennaPatternConsistency, m_rxLdpc, m_rxStbc, m_shortGuardIntervalFor160Mhz, m_shortGuardIntervalFor80Mhz, m_suBeamformeeCapable, m_suBeamformerCapable, m_supportedChannelWidthSet, m_txAntennaPatternConsistency, m_txStbc, m_vhtLinkAdaptationCapable, and m_vhtTxopPs.
Referenced by ns3::operator<<(), ns3::ApWifiMac::Receive(), and SerializeInformationField().
IsSupportedMcs()
bool ns3::VhtCapabilities::IsSupportedMcs (uint8_t mcs, uint8_t nss) const
Get the is MCS supported.
Parameters
mcs the MCS
nss the NSS
Returns
the is MCS supported
Definition at line 394 of file vht-capabilities.cc.
References m_rxMcsMap.
Referenced by ns3::WifiRemoteStationManager::AddStationVhtCapabilities().
IsSupportedRxMcs()
bool ns3::VhtCapabilities::IsSupportedRxMcs (uint8_t mcs) const
Returns true if receive MCS is supported.
Parameters
mcs the MCS
Returns
whether receive MCS is supported
Definition at line 315 of file vht-capabilities.cc.
References m_rxMcsMap, and NS_ASSERT.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
IsSupportedTxMcs()
bool ns3::VhtCapabilities::IsSupportedTxMcs (uint8_t mcs) const
Returns true if transmit MCS is supported.
Parameters
mcs the MCS
Returns
whether transmit MCS is supported
Definition at line 296 of file vht-capabilities.cc.
References m_txMcsMap, and NS_ASSERT.
Referenced by ns3::ApWifiMac::Receive().
Serialize()
Buffer::Iterator ns3::VhtCapabilities::Serialize (Buffer::Iterator start) const
Definition at line 80 of file vht-capabilities.cc.
References m_vhtSupported, and ns3::WifiInformationElement::Serialize().
Referenced by ns3::MgtAssocRequestHeader::Serialize(), ns3::MgtReassocRequestHeader::Serialize(), ns3::MgtAssocResponseHeader::Serialize(), ns3::MgtProbeRequestHeader::Serialize(), and ns3::MgtProbeResponseHeader::Serialize().
SerializeInformationField()
void ns3::VhtCapabilities::SerializeInformationField (Buffer::Iterator start) const virtual
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
Implements ns3::WifiInformationElement.
Definition at line 100 of file vht-capabilities.cc.
References GetSupportedMcsAndNssSet(), GetVhtCapabilitiesInfo(), m_vhtSupported, and visualizer.core::start().
SetMaxAmpduLength()
void ns3::VhtCapabilities::SetMaxAmpduLength (uint32_t maxAmpduLength)
Set the maximum AMPDU length.
Parameters
maxAmpduLength 2^(13 + x) - 1, x in the range 0 to 7
Definition at line 266 of file vht-capabilities.cc.
References m_maxAmpduLengthExponent, and NS_ABORT_MSG.
Referenced by ns3::RegularWifiMac::GetVhtCapabilities().
SetMaxMpduLength()
void ns3::VhtCapabilities::SetMaxMpduLength (uint16_t length)
Set the maximum MPDU length.
Parameters
length the maximum MPDU length (3895, 7991 or 11454)
Definition at line 211 of file vht-capabilities.cc.
References m_maxMpduLength, and NS_ABORT_MSG_IF.
Referenced by ns3::RegularWifiMac::GetVhtCapabilities().
SetRxHighestSupportedLgiDataRate()
void ns3::VhtCapabilities::SetRxHighestSupportedLgiDataRate (uint16_t supportedDatarate)
Set the receive highest supported LGI data rate.
Parameters
supportedDatarate receive highest supported LGI data rate
Definition at line 334 of file vht-capabilities.cc.
References m_rxHighestSupportedLongGuardIntervalDataRate.
Referenced by ns3::RegularWifiMac::GetVhtCapabilities().
SetRxLdpc()
void ns3::VhtCapabilities::SetRxLdpc (uint8_t rxLdpc)
Set the receive LDPC.
Parameters
rxLdpc the receive LDPC
Definition at line 236 of file vht-capabilities.cc.
References m_rxLdpc.
Referenced by ns3::RegularWifiMac::GetVhtCapabilities().
SetRxMcsMap()
void ns3::VhtCapabilities::SetRxMcsMap (uint8_t mcs, uint8_t nss)
Parameters
mcs Max MCS value (between 7 and 9)
nss Spatial stream for which the Max MCS value is being set
Definition at line 280 of file vht-capabilities.cc.
References m_rxMcsMap, and NS_ASSERT.
Referenced by ns3::RegularWifiMac::GetVhtCapabilities().
SetRxStbc()
void ns3::VhtCapabilities::SetRxStbc (uint8_t rxStbc)
Set the receive STBC.
Parameters
rxStbc the receive STBC
Definition at line 254 of file vht-capabilities.cc.
References m_rxStbc.
Referenced by ns3::RegularWifiMac::GetVhtCapabilities().
SetShortGuardIntervalFor160Mhz()
void ns3::VhtCapabilities::SetShortGuardIntervalFor160Mhz (uint8_t shortGuardInterval)
Set the short guard interval 160 MHz.
Parameters
shortGuardInterval the short guard interval 160 MHz
Definition at line 248 of file vht-capabilities.cc.
References m_shortGuardIntervalFor160Mhz.
Referenced by ns3::RegularWifiMac::GetVhtCapabilities().
SetShortGuardIntervalFor80Mhz()
void ns3::VhtCapabilities::SetShortGuardIntervalFor80Mhz (uint8_t shortGuardInterval)
Set the short guard interval 80 MHz.
Parameters
shortGuardInterval the short guard interval 80 MHz
Definition at line 242 of file vht-capabilities.cc.
References m_shortGuardIntervalFor80Mhz.
Referenced by ns3::RegularWifiMac::GetVhtCapabilities().
SetSupportedChannelWidthSet()
void ns3::VhtCapabilities::SetSupportedChannelWidthSet (uint8_t channelWidthSet)
Set the supported channel width set.
Parameters
channelWidthSet the supported channel width set
Definition at line 230 of file vht-capabilities.cc.
References m_supportedChannelWidthSet.
Referenced by ns3::RegularWifiMac::GetVhtCapabilities().
SetSupportedMcsAndNssSet()
void ns3::VhtCapabilities::SetSupportedMcsAndNssSet (uint64_t ctrl)
Set the MCS and NSS field in the VHT Capabilities information element.
Parameters
ctrl the MCS and NSS field in the VHT Capabilities information element
Definition at line 173 of file vht-capabilities.cc.
References m_rxHighestSupportedLongGuardIntervalDataRate, m_rxMcsMap, m_txHighestSupportedLongGuardIntervalDataRate, m_txMcsMap, and sample-rng-plot::n.
Referenced by DeserializeInformationField().
SetTxHighestSupportedLgiDataRate()
void ns3::VhtCapabilities::SetTxHighestSupportedLgiDataRate (uint16_t supportedDatarate)
Set the transmit highest supported LGI data rate.
Parameters
supportedDatarate transmit highest supported LGI data rate
Definition at line 340 of file vht-capabilities.cc.
References m_txHighestSupportedLongGuardIntervalDataRate.
Referenced by ns3::RegularWifiMac::GetVhtCapabilities().
SetTxMcsMap()
void ns3::VhtCapabilities::SetTxMcsMap (uint8_t mcs, uint8_t nss)
Parameters
mcs Max MCS value (between 7 and 9)
nss Spatial stream for which the Max MCS value is being set
Definition at line 288 of file vht-capabilities.cc.
References m_txMcsMap, and NS_ASSERT.
Referenced by ns3::RegularWifiMac::GetVhtCapabilities().
SetTxStbc()
void ns3::VhtCapabilities::SetTxStbc (uint8_t txStbc)
Set the transmit STBC.
Parameters
txStbc the receive STBC
Definition at line 260 of file vht-capabilities.cc.
References m_txStbc.
Referenced by ns3::RegularWifiMac::GetVhtCapabilities().
SetVhtCapabilitiesInfo()
void ns3::VhtCapabilities::SetVhtCapabilitiesInfo (uint32_t ctrl)
Set the VHT Capabilities Info field in the VHT Capabilities information element.
Parameters
ctrl the VHT Capabilities Info field in the VHT Capabilities information element
Definition at line 123 of file vht-capabilities.cc.
References m_beamformeeStsCapable, m_htcVhtCapable, m_maxAmpduLengthExponent, m_maxMpduLength, m_muBeamformeeCapable, m_muBeamformerCapable, m_numberOfSoundingDimensions, m_rxAntennaPatternConsistency, m_rxLdpc, m_rxStbc, m_shortGuardIntervalFor160Mhz, m_shortGuardIntervalFor80Mhz, m_suBeamformeeCapable, m_suBeamformerCapable, m_supportedChannelWidthSet, m_txAntennaPatternConsistency, m_txStbc, m_vhtLinkAdaptationCapable, and m_vhtTxopPs.
Referenced by DeserializeInformationField().
SetVhtSupported()
void ns3::VhtCapabilities::SetVhtSupported (uint8_t vhtSupported)
Set the VHT supported field.
Parameters
vhtSupported the VHT supported field
Definition at line 66 of file vht-capabilities.cc.
References m_vhtSupported.
Referenced by ns3::RegularWifiMac::GetVhtCapabilities().
Member Data Documentation
m_beamformeeStsCapable
uint8_t ns3::VhtCapabilities::m_beamformeeStsCapable private
beamformee STS capable
Definition at line 237 of file vht-capabilities.h.
Referenced by GetVhtCapabilitiesInfo(), and SetVhtCapabilitiesInfo().
m_htcVhtCapable
uint8_t ns3::VhtCapabilities::m_htcVhtCapable private
HTC VHT capable.
Definition at line 242 of file vht-capabilities.h.
Referenced by GetVhtCapabilitiesInfo(), and SetVhtCapabilitiesInfo().
m_maxAmpduLengthExponent
uint8_t ns3::VhtCapabilities::m_maxAmpduLengthExponent private
maximum A-MPDU length exponent
Definition at line 243 of file vht-capabilities.h.
Referenced by GetMaxAmpduLength(), GetVhtCapabilitiesInfo(), SetMaxAmpduLength(), and SetVhtCapabilitiesInfo().
m_maxMpduLength
uint8_t ns3::VhtCapabilities::m_maxMpduLength private
maximum MPDU length
Definition at line 228 of file vht-capabilities.h.
Referenced by GetMaxMpduLength(), GetVhtCapabilitiesInfo(), SetMaxMpduLength(), and SetVhtCapabilitiesInfo().
m_muBeamformeeCapable
uint8_t ns3::VhtCapabilities::m_muBeamformeeCapable private
MU beamformee capable.
Definition at line 240 of file vht-capabilities.h.
Referenced by GetVhtCapabilitiesInfo(), and SetVhtCapabilitiesInfo().
m_muBeamformerCapable
uint8_t ns3::VhtCapabilities::m_muBeamformerCapable private
MU beamformer capable.
Definition at line 239 of file vht-capabilities.h.
Referenced by GetVhtCapabilitiesInfo(), and SetVhtCapabilitiesInfo().
m_numberOfSoundingDimensions
uint8_t ns3::VhtCapabilities::m_numberOfSoundingDimensions private
number of sounding dimensions
Definition at line 238 of file vht-capabilities.h.
Referenced by GetVhtCapabilitiesInfo(), and SetVhtCapabilitiesInfo().
m_rxAntennaPatternConsistency
uint8_t ns3::VhtCapabilities::m_rxAntennaPatternConsistency private
receive antenna pattern consistency
Definition at line 245 of file vht-capabilities.h.
Referenced by GetVhtCapabilitiesInfo(), and SetVhtCapabilitiesInfo().
m_rxHighestSupportedLongGuardIntervalDataRate
uint16_t ns3::VhtCapabilities::m_rxHighestSupportedLongGuardIntervalDataRate private
receive highest supported long guard interval data rate
Definition at line 250 of file vht-capabilities.h.
Referenced by GetRxHighestSupportedLgiDataRate(), GetSupportedMcsAndNssSet(), SetRxHighestSupportedLgiDataRate(), and SetSupportedMcsAndNssSet().
m_rxLdpc
uint8_t ns3::VhtCapabilities::m_rxLdpc private
receive LDPC
Definition at line 230 of file vht-capabilities.h.
Referenced by GetRxLdpc(), GetVhtCapabilitiesInfo(), SetRxLdpc(), and SetVhtCapabilitiesInfo().
m_rxMcsMap
std::vector<uint8_t> ns3::VhtCapabilities::m_rxMcsMap private
receive MCS map
Definition at line 249 of file vht-capabilities.h.
Referenced by VhtCapabilities(), GetSupportedMcsAndNssSet(), IsSupportedMcs(), IsSupportedRxMcs(), SetRxMcsMap(), and SetSupportedMcsAndNssSet().
m_rxStbc
uint8_t ns3::VhtCapabilities::m_rxStbc private
receive STBC
Definition at line 234 of file vht-capabilities.h.
Referenced by GetRxStbc(), GetVhtCapabilitiesInfo(), SetRxStbc(), and SetVhtCapabilitiesInfo().
m_shortGuardIntervalFor160Mhz
uint8_t ns3::VhtCapabilities::m_shortGuardIntervalFor160Mhz private
short guard interval for 160 MHz
Definition at line 232 of file vht-capabilities.h.
Referenced by GetVhtCapabilitiesInfo(), SetShortGuardIntervalFor160Mhz(), and SetVhtCapabilitiesInfo().
m_shortGuardIntervalFor80Mhz
uint8_t ns3::VhtCapabilities::m_shortGuardIntervalFor80Mhz private
short guard interval for 80 MHz
Definition at line 231 of file vht-capabilities.h.
Referenced by GetVhtCapabilitiesInfo(), SetShortGuardIntervalFor80Mhz(), and SetVhtCapabilitiesInfo().
m_suBeamformeeCapable
uint8_t ns3::VhtCapabilities::m_suBeamformeeCapable private
SU beamformee capable.
Definition at line 236 of file vht-capabilities.h.
Referenced by GetVhtCapabilitiesInfo(), and SetVhtCapabilitiesInfo().
m_suBeamformerCapable
uint8_t ns3::VhtCapabilities::m_suBeamformerCapable private
SU beamformer capable.
Definition at line 235 of file vht-capabilities.h.
Referenced by GetVhtCapabilitiesInfo(), and SetVhtCapabilitiesInfo().
m_supportedChannelWidthSet
uint8_t ns3::VhtCapabilities::m_supportedChannelWidthSet private
supported channel width set
Definition at line 229 of file vht-capabilities.h.
Referenced by GetSupportedChannelWidthSet(), GetVhtCapabilitiesInfo(), SetSupportedChannelWidthSet(), and SetVhtCapabilitiesInfo().
m_txAntennaPatternConsistency
uint8_t ns3::VhtCapabilities::m_txAntennaPatternConsistency private
transmit antenna pattern consistency
Definition at line 246 of file vht-capabilities.h.
Referenced by GetVhtCapabilitiesInfo(), and SetVhtCapabilitiesInfo().
m_txHighestSupportedLongGuardIntervalDataRate
uint16_t ns3::VhtCapabilities::m_txHighestSupportedLongGuardIntervalDataRate private
transmit highest supported long guard interval data rate
Definition at line 252 of file vht-capabilities.h.
Referenced by GetSupportedMcsAndNssSet(), SetSupportedMcsAndNssSet(), and SetTxHighestSupportedLgiDataRate().
m_txMcsMap
std::vector<uint8_t> ns3::VhtCapabilities::m_txMcsMap private
transmit MCS map
Definition at line 251 of file vht-capabilities.h.
Referenced by VhtCapabilities(), GetSupportedMcsAndNssSet(), IsSupportedTxMcs(), SetSupportedMcsAndNssSet(), and SetTxMcsMap().
m_txStbc
uint8_t ns3::VhtCapabilities::m_txStbc private
transmit STBC
Definition at line 233 of file vht-capabilities.h.
Referenced by GetTxStbc(), GetVhtCapabilitiesInfo(), SetTxStbc(), and SetVhtCapabilitiesInfo().
m_vhtLinkAdaptationCapable
uint8_t ns3::VhtCapabilities::m_vhtLinkAdaptationCapable private
VHT link adaptation capable.
Definition at line 244 of file vht-capabilities.h.
Referenced by GetVhtCapabilitiesInfo(), and SetVhtCapabilitiesInfo().
m_vhtSupported
uint8_t ns3::VhtCapabilities::m_vhtSupported private
This is used to decide if this element should be added to the frame or not.
Definition at line 255 of file vht-capabilities.h.
Referenced by GetInformationFieldSize(), GetSerializedSize(), Serialize(), SerializeInformationField(), and SetVhtSupported().
m_vhtTxopPs
uint8_t ns3::VhtCapabilities::m_vhtTxopPs private
VHT TXOP PS.
Definition at line 241 of file vht-capabilities.h.
Referenced by GetVhtCapabilitiesInfo(), and SetVhtCapabilitiesInfo().
The documentation for this class was generated from the following files:
src/wifi/model/vht-capabilities.h
src/wifi/model/vht-capabilities.cc