ns-3: ns3::Object Class Reference
ns3::Object Class Reference
Core » Object
A base class which provides memory management and object aggregation.
#include "object.h"
Inherits ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >.
Inherited by anonymous_namespace{object-test-suite.cc}::BaseA, anonymous_namespace{object-test-suite.cc}::BaseB, anonymous_namespace{sequence-number-test-suite.cc}::SequenceNumberTestObj, anonymous_namespace{test-string-value-formatting.cc}::FormattingTestObject, AttributeObjectTest, ConfigExample, DeprecatedAttribute, Derived, Emitter, MyObject, ns3::AntennaModel, ns3::Application, ns3::ArpCache, ns3::ArpL3Protocol, ns3::AthstatsWifiTraceSink, ns3::BandwidthManager, ns3::BlockAckManager, ns3::BSLinkManager, ns3::BSScheduler, ns3::Building, ns3::BuildingListPriv, ns3::BurstProfileManager, ns3::CcHelper, ns3::Channel, ns3::ChannelAccessManager, ns3::ChannelCondition, ns3::ChannelConditionModel, ns3::ChannelCoordinator, ns3::ChannelListPriv, ns3::ChannelManager, ns3::ChannelScheduler, ns3::ComponentCarrier, ns3::ConnectionManager, ns3::DataCalculator, ns3::DataCollectionObject, ns3::DataCollector, ns3::DataOutputInterface, ns3::DeviceEnergyModel, ns3::dot11s::AirtimeLinkMetricCalculator, ns3::dot11s::HwmpRtable, ns3::dot11s::PeerLink, ns3::dot11s::PeerManagementProtocol, ns3::dsr::DsrGraReply, ns3::dsr::DsrNetworkQueue, ns3::dsr::DsrOptions, ns3::dsr::DsrPassiveBuffer, ns3::dsr::DsrRouteCache, ns3::dsr::DsrRreqTable, ns3::EnergyHarvester, ns3::EnergyHarvesterContainer, ns3::EnergySource, ns3::EnergySourceContainer, ns3::EpcHelper, ns3::EpcTestRrc, ns3::EpcUeNas, ns3::EpcX2, ns3::ErrorModel, ns3::ErrorRateModel, ns3::FfMacScheduler, ns3::flame::FlameRtable, ns3::FlowMonitor, ns3::FlowProbe, ns3::FrameCaptureModel, ns3::GlobalRouter, ns3::GrantedTimeWindowMpiInterface [private], ns3::GridBuildingAllocator, ns3::HeConfiguration, ns3::HtConfiguration, ns3::IpcsClassifier, ns3::IpL4Protocol, ns3::Ipv4, ns3::Ipv4Interface, ns3::Ipv4RoutingProtocol, ns3::Ipv6, ns3::Ipv6AutoconfiguredPrefix, ns3::Ipv6Extension, ns3::Ipv6ExtensionDemux, ns3::Ipv6ExtensionRoutingDemux, ns3::Ipv6Interface, ns3::Ipv6Option, ns3::Ipv6OptionDemux, ns3::Ipv6PmtuCache, ns3::Ipv6RoutingProtocol, ns3::JakesProcess, ns3::lorawan::EndDeviceStatus, ns3::lorawan::GatewayStatus, ns3::lorawan::LogicalLoraChannel, ns3::lorawan::LogicalLoraChannelHelper, ns3::lorawan::LoraDeviceAddressGenerator, ns3::lorawan::LoraPhy, ns3::lorawan::LoraTxCurrentModel, ns3::lorawan::LorawanMac, ns3::lorawan::MacCommand, ns3::lorawan::NetworkController, ns3::lorawan::NetworkControllerComponent, ns3::lorawan::NetworkScheduler, ns3::lorawan::NetworkStatus, ns3::lorawan::SubBand, ns3::LrWpanCsmaCa, ns3::LrWpanErrorModel, ns3::LrWpanMac, ns3::LteAmc, ns3::LteAnr, ns3::LteEnbComponentCarrierManager, ns3::LteEnbMac, ns3::LteEnbRrc, ns3::LteEnbRrcProtocolIdeal, ns3::LteEnbRrcProtocolReal, ns3::LteFfrAlgorithm, ns3::LteHandoverAlgorithm, ns3::LteHelper, ns3::LteHexGridEnbTopologyHelper, ns3::LteInterference, ns3::LtePdcp, ns3::LtePhy, ns3::LteRadioBearerInfo, ns3::LteRlc, ns3::LteSimpleHelper, ns3::LteStatsCalculator, ns3::LteTestMac, ns3::LteTestPdcp, ns3::LteTestRrc, ns3::LteUeComponentCarrierManager, ns3::LteUeMac, ns3::LteUePowerControl, ns3::LteUeRrc, ns3::LteUeRrcProtocolIdeal, ns3::LteUeRrcProtocolReal, ns3::MacLow, ns3::MeshL2RoutingProtocol, ns3::MeshStack, ns3::MobilityBuildingInfo, ns3::MobilityModel, ns3::MpduAggregator, ns3::MpiReceiver, ns3::MsduAggregator, ns3::NdiscCache, ns3::NetDevice, ns3::NetDeviceQueueInterface, ns3::Node, ns3::NodeListPriv, ns3::Ns3NscStack, ns3::ObssPdAlgorithm, ns3::ofi::Controller, ns3::PacketBurst, ns3::PacketFilter, ns3::PcapFileWrapper, ns3::PositionAllocator, ns3::PreambleDetectionModel, ns3::PriorityUlJob, ns3::PropagationDelayModel, ns3::PropagationLossModel, ns3::QueueBase, ns3::QueueDisc, ns3::QueueDiscClass, ns3::QueueLimits, ns3::RadioEnvironmentMapHelper, ns3::RandomVariableStream, ns3::RemoteChannelBundle, ns3::RttEstimator, ns3::Scheduler, ns3::ServiceFlowManager, ns3::SimulatorImpl, ns3::Socket, ns3::SocketFactory, ns3::SpectrumErrorModel, ns3::SpectrumInterference, ns3::SpectrumPhy, ns3::SpectrumPropagationLossModel, ns3::SSLinkManager, ns3::SSManager, ns3::SSScheduler, ns3::Synchronizer, ns3::TcpCongestionOps, ns3::TcpOption, ns3::TcpRateOps, ns3::TcpRecoveryOps, ns3::TcpRxBuffer, ns3::TcpSocketState, ns3::TcpTxBuffer, ns3::tests::AlternateTestObject, ns3::tests::BaseConfigObject, ns3::tests::ConfigTestObject, ns3::tests::TestObject, ns3::ThreeGppAntennaArrayModel, ns3::ThreeGppChannelModel, ns3::ThreeGppHttpVariables, ns3::TopologyReader, ns3::TrafficControlLayer, ns3::Txop, ns3::UanMac, ns3::UanNoiseModel, ns3::UanPhy, ns3::UanPhyCalcSinr, ns3::UanPhyPer, ns3::UanPropModel, ns3::UanTransducer, ns3::UeManager, ns3::UlJob, ns3::UplinkScheduler, ns3::VhtConfiguration, ns3::VsaManager, ns3::WaveBsmStats, ns3::WifiAckPolicySelector, ns3::WifiMac, ns3::WifiPhy, ns3::WifiPhyStateHelper, ns3::WifiRemoteStationManager, ns3::WifiTxCurrentModel, ns3::WimaxConnection, ns3::WimaxMacQueue, ns3::WimaxPhy, PtrExample, RoutingHelper, SampleEmitter, TracedValueCallbackTestCase::CheckTvCb< T >, and WifiPhyStats.
Classes
class AggregateIterator
Iterate over the Objects aggregated to an ns3::Object.
struct Aggregates
The list of Objects aggregated to this one.
Public Member Functions
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
bool Check (void) const
Verify that this Object is still live, by checking it's reference count.
bool CheckLoose (void) const
Check if any aggregated Objects have non-zero reference counts.
void Construct (const AttributeConstructionList &attributes)
Initialize all member variables registered as Attributes of this TypeId.
void DoDelete (void)
Attempt to delete this Object.
Ptr< Object > DoGetObject (TypeId tid) const
Find an Object of TypeId tid in the aggregates of this Object.
void SetTypeId (TypeId tid)
Set the TypeId of this Object.
void UpdateSortedArray (struct Aggregates *aggregates, uint32_t i) const
Keep the list of aggregates in most-recently-used order.
Private Attributes
struct Aggregates * m_aggregates
A pointer to an array of 'aggregates'.
bool m_disposed
Set to true when the DoDispose() method of the Object has run, false otherwise.
uint32_t m_getObjectCount
The number of times the Object was accessed with a call to GetObject().
bool m_initialized
Set to true once the DoInitialize() method has run, false otherwise.
TypeId m_tid
Identifies the type of this Object instance.
Friends
template<typename T >
Ptr< T > CompleteConstruct (T *object)
Set the TypeId and construct all Attributes of an Object.
class ObjectFactory
Friends.
class AggregateIterator
Friends.
struct ObjectDeleter
Friends.
template<typename T >
Ptr< T > CopyObject (Ptr< T > object)
Copy an Object.
template<typename T >
Ptr< T > CopyObject (Ptr< const T > object)
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A base class which provides memory management and object aggregation.
The memory management scheme is based on reference-counting with dispose-like functionality to break the reference cycles. The reference count is incremented and decremented with the methods Ref() and Unref(). If a reference cycle is present, the user is responsible for breaking it by calling Dispose() in a single location. This will eventually trigger the invocation of DoDispose() on itself and all its aggregates. The DoDispose() method is always automatically invoked from the Unref() method before destroying the Object, even if the user did not call Dispose() directly.
Definition at line 87 of file object.h.
Constructor & Destructor Documentation
Object() [1/2]
ns3::Object::Object ()
Constructor.
Definition at line 96 of file object.cc.
References ns3::Object::Aggregates::buffer, m_aggregates, ns3::Object::Aggregates::n, and NS_LOG_FUNCTION.
~Object()
ns3::Object::~Object () virtual
Destructor.
Definition at line 107 of file object.cc.
References ns3::Object::Aggregates::buffer, m_aggregates, sample-rng-plot::n, ns3::Object::Aggregates::n, and NS_LOG_FUNCTION.
Object() [2/2]
ns3::Object::Object (const Object & o) protected
Copy an Object.
Parameters
[in] o the Object to copy.
Allow subclasses to implement a copy constructor.
While it is technically possible to implement a copy constructor in a subclass, we strongly discourage you from doing so. If you really want to do it anyway, you have to understand that this copy constructor will not copy aggregated Objects, i.e, if your Object instance is already aggregated to another Object and if you invoke this copy constructor, the new Object instance will be a pristine standalone Object instance not aggregated to any other Object. It is thus your responsibility as a caller of this method to do what needs to be done (if it is needed) to ensure that the Object stays in a valid state.
Definition at line 131 of file object.cc.
References ns3::Object::Aggregates::buffer, m_aggregates, and ns3::Object::Aggregates::n.
Member Function Documentation
AggregateObject()
void ns3::Object::AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
Parameters
[in] other The other Object pointer
This method aggregates the two Objects together: after this method returns, it becomes possible to call GetObject() on one to get the other, and vice-versa.
This method calls the virtual method NotifyNewAggregates() to notify all aggregated Objects that they have been aggregated together.
See also
NotifyNewAggregate()
Definition at line 252 of file object.cc.
References ns3::Object::Aggregates::buffer, CheckLoose(), DoGetObject(), GetInstanceTypeId(), m_aggregates, m_disposed, sample-rng-plot::n, ns3::Object::Aggregates::n, NotifyNewAggregate(), NS_ASSERT, NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::PeekPointer(), and UpdateSortedArray().
Referenced by ns3::Ipv6L3Protocol::Ipv6L3Protocol(), ns3::NoBackhaulEpcHelper::AddEnb(), ns3::PointToPointDumbbellHelper::BoundingBox(), ns3::PointToPointGridHelper::BoundingBox(), ns3::PointToPointStarHelper::BoundingBox(), ns3::AodvHelper::Create(), ns3::DsdvHelper::Create(), ns3::DsrHelper::Create(), ns3::Ipv4GlobalRoutingHelper::Create(), ns3::RipHelper::Create(), ns3::RipNgHelper::Create(), ns3::Ipv4NixVectorHelper::Create(), ns3::OlsrHelper::Create(), ns3::InternetStackHelper::CreateAndAggregateObjectFromTypeId(), CreateDualStackNode(), TcpTestCase::CreateInternetNode(), TcpTestCase::CreateInternetNode6(), BuildingsPathlossTestCase::CreateMobilityModel(), BuildingsShadowingTestCase::CreateMobilityModel(), WifiTest::CreateOne(), InterferenceHelperSequenceTest::CreateOne(), ns3::RadioEnvironmentMapHelper::DelayedInstall(), Ipv6L3ProtocolTestCase::DoRun(), BuildingsHelperOneTestCase::DoRun(), BasicEnergyHarvesterTestCase::DoRun(), LiIonEnergyTestCase::DoRun(), LrWpanCollisionTestCase::DoRun(), EpcS1uDlTestCase::DoRun(), EpcS1uUlTestCase::DoRun(), WaypointLazyNotifyFalse::DoRun(), WaypointLazyNotifyTrue::DoRun(), AcousticModemEnergyTestCase::DoRun(), AcousticModemEnergyDepletionTestCase::DoRun(), DcfImmediateAccessBroadcastTestCase::DoRun(), Bug2831TestCase::DoRun(), ns3::WifiHelper::Install(), ns3::EnergyHarvesterHelper::Install(), ns3::BuildingsHelper::Install(), ns3::InternetStackHelper::Install(), ns3::PacketSocketHelper::Install(), ns3::NscTcpL4Protocol::NotifyNewAggregate(), ns3::TcpL4Protocol::NotifyNewAggregate(), ns3::UdpL4Protocol::NotifyNewAggregate(), AnimationRemainingEnergyTestCase::PrepareNetwork(), ns3::Ipv6L3Protocol::RegisterExtensions(), ns3::Ipv6L3Protocol::RegisterOptions(), NetAnimExperiment::Run(), Experiment::Run(), TbfQueueDiscTestCase::RunTbfTest(), ns3::NscTcpL4Protocol::SetNode(), and BasicEnergyUpdateTest::StateSwitchTest().
Check()
bool ns3::Object::Check (void) const private
Verify that this Object is still live, by checking it's reference count.
Returns
true if the reference count is non zero.
Definition at line 360 of file object.cc.
References ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >::GetReferenceCount(), and NS_LOG_FUNCTION.
Referenced by SetTypeId().
CheckLoose()
bool ns3::Object::CheckLoose (void) const private
Check if any aggregated Objects have non-zero reference counts.
Returns
true if any of our aggregates have non zero reference count.
In some cases, when an event is scheduled against a subclass of Object, and if no one owns a reference directly to this Object, the Object is alive, has a refcount of zero and the method run when the event expires runs against the raw pointer, which means that we are manipulating an Object with a refcount of zero. So, instead we check the aggregate reference count.
Definition at line 374 of file object.cc.
References ns3::Object::Aggregates::buffer, ns3::SimpleRefCount< T, PARENT, DELETER >::GetReferenceCount(), m_aggregates, sample-rng-plot::n, ns3::Object::Aggregates::n, and NS_LOG_FUNCTION.
Referenced by AggregateObject(), and DoGetObject().
Construct()
void ns3::Object::Construct (const AttributeConstructionList & attributes) private
Initialize all member variables registered as Attributes of this TypeId.
Parameters
[in] attributes The attribute values used to initialize the member variables of this Object's instance.
Invoked from ns3::ObjectFactory::Create and ns3::CreateObject only. Initialize all the member variables which were registered with the associated TypeId.
Definition at line 142 of file object.cc.
References ns3::ObjectBase::ConstructSelf(), and NS_LOG_FUNCTION.
Referenced by ns3::ObjectFactory::Create().
Dispose()
void ns3::Object::Dispose (void)
Dispose of this Object.
Run the DoDispose() methods of this Object and all the Objects aggregated to it. After calling this method, this Object is expected to be totally unusable except for the Ref() and Unref() methods.
Note
You can call Dispose() many times on the same Object or different Objects aggregated together, and DoDispose() will be called only once for each aggregated Object.
This method is typically used to break reference cycles.
Note: the code here is a bit tricky because we need to protect ourselves from modifications in the aggregate array while DoDispose is called. The user's DoDispose implementation could call GetObject (which could reorder the array) and it could call AggregateObject which would add an object at the end of the array. So, to be safe, we restart the iteration over the array whenever we call some user code.
Definition at line 214 of file object.cc.
References ns3::Object::Aggregates::buffer, DoDispose(), m_aggregates, m_disposed, sample-rng-plot::n, ns3::Object::Aggregates::n, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::DoDispose(), ns3::NoBackhaulEpcHelper::DoDispose(), ns3::RegularWifiMac::DoDispose(), ns3::ArpL3Protocol::DoDispose(), ns3::LteSimpleHelper::DoDispose(), ns3::NodeListPriv::DoDispose(), ns3::Node::DoDispose(), ns3::WaveNetDevice::DoDispose(), ns3::ApWifiMac::DoDispose(), ns3::WifiNetDevice::DoDispose(), Ipv4RawSocketImplTest::DoRun(), Ipv6RawSocketImplTest::DoRun(), UdpSocketImplTest::DoRun(), Udp6SocketImplTest::DoRun(), LteDownlinkDataSinrTestCase::DoRun(), LteDownlinkCtrlSinrTestCase::DoRun(), LteUplinkDataSinrTestCase::DoRun(), LteUplinkSrsSinrTestCase::DoRun(), AmpduAggregationTest::DoRun(), TwoLevelAggregationTest::DoRun(), HeAggregationTest::DoRunSubTest(), and InterferenceExperiment::Run().
DoDelete()
void ns3::Object::DoDelete (void) private
Attempt to delete this Object.
This method iterates over all aggregated Objects to check if they all have a zero refcount. If yes, the Object and all its aggregates are deleted. If not, nothing is done.
Definition at line 391 of file object.cc.
References ns3::Object::Aggregates::buffer, DoDispose(), ns3::SimpleRefCount< T, PARENT, DELETER >::GetReferenceCount(), m_aggregates, m_disposed, sample-rng-plot::n, ns3::Object::Aggregates::n, and NS_LOG_FUNCTION.
DoDispose()
void ns3::Object::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented in ns3::WimaxPhy, ns3::WimaxNetDevice, ns3::WimaxConnection, ns3::SsServiceFlowManager, ns3::SSScheduler, ns3::SubscriberStationNetDevice, ns3::SSLinkManager, ns3::SimpleOfdmWimaxPhy, ns3::ServiceFlowManager, ns3::ConnectionManager, ns3::BurstProfileManager, ns3::BsServiceFlowManager, ns3::BaseStationNetDevice, ns3::BandwidthManager, ns3::YansWifiPhy, ns3::WifiSpectrumPhyInterface, ns3::WifiRemoteStationManager, ns3::WifiRadioEnergyModel, ns3::WifiPhy, ns3::WifiNetDevice, ns3::WifiAckPolicySelector, ns3::Txop, ns3::SpectrumWifiPhy, ns3::QosTxop, ns3::ObssPdAlgorithm, ns3::MacLow, ns3::ChannelAccessManager, ns3::ApWifiMac, ns3::WaveNetDevice, ns3::VsaManager, ns3::DefaultChannelScheduler, ns3::ChannelCoordinator, ns3::BsmApplication, ns3::VirtualNetDevice, ns3::UanPropModel, ns3::UanPhyPer, ns3::UanPhyCalcSinr, ns3::UanNoiseModel, ns3::UanNetDevice, ns3::UanChannel, ns3::AcousticModemEnergyModel, ns3::TrafficControlLayer, ns3::TbfQueueDisc, ns3::RedQueueDisc, ns3::QueueDisc, ns3::QueueDiscClass, ns3::PieQueueDisc, ns3::CobaltQueueDisc, ns3::TapBridge, ns3::TimeMinMaxAvgTotalCalculator, ns3::DataCalculator, ns3::CounterCalculator< T >, ns3::CounterCalculator< uint32_t >, ns3::CounterCalculator<>, ns3::MinMaxAvgTotalCalculator< T >, ns3::MinMaxAvgTotalCalculator< uint32_t >, ns3::MinMaxAvgTotalCalculator< double >, ns3::MinMaxAvgTotalCalculator< uint64_t >, ns3::WaveformGenerator, ns3::SpectrumChannel, ns3::NonCommunicatingNetDevice, ns3::HalfDuplexIdealPhy, ns3::AlohaNoackNetDevice, ns3::SixLowPanNetDevice, ns3::PointToPointNetDevice, ns3::OpenFlowSwitchNetDevice, ns3::Ipv4NixVectorRouting, ns3::SimpleNetDevice, ns3::PacketSocket, ns3::PacketSocketServer, ns3::PacketSocketClient, ns3::PacketSizeMinMaxAvgTotalCalculator, ns3::PacketCounterCalculator, ns3::PacketBurst, ns3::NetDeviceQueueInterface, ns3::Socket, ns3::Node, ns3::NodeListPriv, ns3::ChannelListPriv, ns3::Application, ns3::NullMessageSimulatorImpl, ns3::MpiReceiver, ns3::DistributedSimulatorImpl, ns3::WaypointMobilityModel, ns3::RandomWalk2dMobilityModel, ns3::RandomDirection2dMobilityModel, ns3::GaussMarkovMobilityModel, ns3::EpcTestRrc, ns3::LteTestMac, ns3::LteTestPdcp, ns3::LteTestRrc, ns3::LteSimpleHelper, EpsBearerTagUdpClient, ns3::TtaFfMacScheduler, ns3::TdTbfqFfMacScheduler, ns3::TdMtFfMacScheduler, ns3::TdBetFfMacScheduler, ns3::RrFfMacScheduler, ns3::PssFfMacScheduler, ns3::PfFfMacScheduler, ns3::LteUeRrc, ns3::LteUePowerControl, ns3::LteUePhy, ns3::LteUeMac, ns3::LteEnbRrcProtocolReal, ns3::LteUeRrcProtocolReal, ns3::LteEnbRrcProtocolIdeal, ns3::LteUeRrcProtocolIdeal, ns3::LteNetDevice, ns3::LteEnbRrc, ns3::LteEnbPhy, ns3::LteEnbNetDevice, ns3::LteEnbMac, ns3::FfMacScheduler, ns3::FdTbfqFfMacScheduler, ns3::FdMtFfMacScheduler, ns3::FdBetFfMacScheduler, ns3::EpcX2, ns3::EpcUeNas, ns3::EpcEnbApplication, ns3::CqaFfMacScheduler, ns3::ComponentCarrier, ns3::ComponentCarrierUe, ns3::ComponentCarrierEnb, ns3::RadioEnvironmentMapHelper, ns3::LteHexGridEnbTopologyHelper, ns3::LteHelper, ns3::CcHelper, ns3::LrWpanPhy, ns3::LrWpanNetDevice, ns3::LrWpanMac, ns3::LrWpanCsmaCa, ns3::lorawan::LoraRadioEnergyModel, ns3::UdpSocketFactoryImpl, ns3::UdpL4Protocol, ns3::TcpSocketFactoryImpl, ns3::TcpL4Protocol, ns3::NscTcpSocketFactoryImpl, ns3::NscTcpL4Protocol, ns3::LoopbackNetDevice, ns3::Ipv6ListRouting, ns3::Ipv4StaticRouting, ns3::Ipv4RawSocketImpl, ns3::Ipv4ListRouting, ns3::Ipv4L3Protocol, ns3::Ipv4Interface, ns3::Ipv4GlobalRouting, ns3::Icmpv4L4Protocol, ns3::GlobalRouter, ns3::ArpL3Protocol, ns3::ArpCache, ns3::V4TraceRoute, ns3::V4Ping, ns3::DhcpServer, ns3::DhcpClient, ns3::Ipv6FlowProbe, ns3::Ipv4FlowProbe, ns3::FlowProbe, ns3::FlowMonitor, ns3::FdNetDevice, ns3::SimpleDeviceEnergyModel, ns3::RvBatteryModel, ns3::LiIonEnergySource, ns3::EnergySource, ns3::EnergyHarvester, ns3::BasicEnergySource, ns3::BasicEnergyHarvester, ns3::EnergySourceContainer, ns3::EnergyHarvesterContainer, ns3::dsr::DsrRouting, ns3::CsmaNetDevice, anonymous_namespace{object-test-suite.cc}::DerivedB, anonymous_namespace{object-test-suite.cc}::DerivedA, ns3::RealtimeSimulatorImpl, ns3::DefaultSimulatorImpl, ns3::BuildingListPriv, ns3::BridgeNetDevice, ns3::UdpServer, ns3::UdpEchoServer, ns3::UdpEchoClient, ns3::UdpClient, ns3::PacketSink, ns3::OnOffApplication, ns3::BulkSendApplication, Receiver, Sender, ns3::WifiMac, ns3::RegularWifiMac, ns3::VisualSimulatorImpl, ns3::UanTransducerHd, ns3::UanPhyGen, ns3::UanPhyDual, ns3::UanMacRc, ns3::UanMacRcGw, ns3::UanMacCw, ns3::UanMacAloha, ns3::OmnetDataOutput, ns3::DataOutputInterface, ns3::DataCollector, ns3::SpectrumPropagationLossModel, ns3::SpectrumInterference, ns3::ShannonSpectrumErrorModel, ns3::SpectrumAnalyzer, ns3::SingleModelSpectrumChannel, ns3::MultiModelSpectrumChannel, ns3::JakesProcess, ns3::olsr::RoutingProtocol, ns3::MeshWifiInterfaceMac, ns3::MeshPointDevice, ns3::flame::FlameRtable, ns3::flame::FlameProtocol, ns3::dot11s::PeerManagementProtocol, ns3::dot11s::PeerLink, ns3::dot11s::HwmpRtable, ns3::dot11s::HwmpProtocol, ns3::FlameStack, ns3::Dot11sStack, ns3::LteTestUePhy, ns3::LteSimpleSpectrumPhy, ns3::LteSimpleNetDevice, ns3::LteFfrSimple, ns3::SimpleUeComponentCarrierManager, ns3::RemSpectrumPhy, ns3::NoOpHandoverAlgorithm, ns3::NoOpComponentCarrierManager, ns3::LteUeNetDevice, ns3::LteUeComponentCarrierManager, ns3::LteSpectrumPhy, ns3::LteRlcSm, ns3::LteRlc, ns3::LteRlcUm, ns3::LteRlcTm, ns3::LteRlcAm, ns3::LtePhy, ns3::LtePdcp, ns3::LteInterference, ns3::LteHandoverAlgorithm, ns3::LteFrStrictAlgorithm, ns3::LteFrSoftAlgorithm, ns3::LteFrNoOpAlgorithm, ns3::LteFrHardAlgorithm, ns3::LteFfrSoftAlgorithm, ns3::LteFfrEnhancedAlgorithm, ns3::LteFfrDistributedAlgorithm, ns3::LteFfrAlgorithm, ns3::UeManager, ns3::LteEnbComponentCarrierManager, ns3::LteAnr, ns3::EpcSgwApplication, ns3::EpcPgwApplication, ns3::EpcMmeApplication, ns3::A3RsrpHandoverAlgorithm, ns3::A2A4RsrqHandoverAlgorithm, ns3::RadioBearerStatsCalculator, ns3::PointToPointEpcHelper, ns3::NoBackhaulEpcHelper, ns3::EpcHelper, ns3::EmuEpcHelper, ns3::RipNg, ns3::Rip, ns3::NdiscCache, ns3::Ipv6StaticRouting, ns3::Ipv6RawSocketImpl, ns3::Ipv6PmtuCache, ns3::Ipv6OptionDemux, ns3::Ipv6L3Protocol, ns3::Ipv6Interface, ns3::Ipv6ExtensionRoutingDemux, ns3::Ipv6ExtensionFragment, ns3::Ipv6ExtensionDemux, ns3::Icmpv6L4Protocol, ns3::Radvd, ns3::Ping6, ns3::dsdv::RoutingProtocol, ns3::Building, ns3::ThreeGppHttpServer, ns3::ThreeGppHttpClient, and ns3::aodv::RoutingProtocol.
Definition at line 346 of file object.cc.
References m_disposed, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by Dispose(), DoDelete(), ns3::aodv::RoutingProtocol::DoDispose(), ns3::dsdv::RoutingProtocol::DoDispose(), ns3::Icmpv6L4Protocol::DoDispose(), ns3::Ipv6ExtensionDemux::DoDispose(), ns3::Ipv6ExtensionFragment::DoDispose(), ns3::Ipv6ExtensionRoutingDemux::DoDispose(), ns3::Ipv6Interface::DoDispose(), ns3::Ipv6L3Protocol::DoDispose(), ns3::Ipv6OptionDemux::DoDispose(), ns3::Ipv6StaticRouting::DoDispose(), ns3::NdiscCache::DoDispose(), ns3::Rip::DoDispose(), ns3::RipNg::DoDispose(), ns3::EpcHelper::DoDispose(), ns3::LteInterference::DoDispose(), ns3::LtePhy::DoDispose(), ns3::LteSpectrumPhy::DoDispose(), ns3::RemSpectrumPhy::DoDispose(), ns3::LteSimpleSpectrumPhy::DoDispose(), ns3::MeshPointDevice::DoDispose(), ns3::olsr::RoutingProtocol::DoDispose(), ns3::SpectrumAnalyzer::DoDispose(), ns3::ShannonSpectrumErrorModel::DoDispose(), ns3::SpectrumInterference::DoDispose(), ns3::DataCollector::DoDispose(), ns3::DataOutputInterface::DoDispose(), ns3::UanMacAloha::DoDispose(), ns3::UanMacCw::DoDispose(), ns3::UanMacRcGw::DoDispose(), ns3::UanMacRc::DoDispose(), ns3::UanPhyDual::DoDispose(), ns3::UanPhyGen::DoDispose(), ns3::UanTransducerHd::DoDispose(), ns3::VisualSimulatorImpl::DoDispose(), ns3::BridgeNetDevice::DoDispose(), ns3::BuildingListPriv::DoDispose(), ns3::DefaultSimulatorImpl::DoDispose(), ns3::RealtimeSimulatorImpl::DoDispose(), ns3::CsmaNetDevice::DoDispose(), ns3::dsr::DsrRouting::DoDispose(), ns3::FdNetDevice::DoDispose(), ns3::FlowMonitor::DoDispose(), ns3::FlowProbe::DoDispose(), ns3::ArpCache::DoDispose(), ns3::ArpL3Protocol::DoDispose(), ns3::GlobalRouter::DoDispose(), ns3::Icmpv4L4Protocol::DoDispose(), ns3::Ipv4GlobalRouting::DoDispose(), ns3::Ipv4Interface::DoDispose(), ns3::Ipv4L3Protocol::DoDispose(), ns3::Ipv4StaticRouting::DoDispose(), ns3::LoopbackNetDevice::DoDispose(), ns3::NscTcpL4Protocol::DoDispose(), ns3::NscTcpSocketFactoryImpl::DoDispose(), ns3::TcpL4Protocol::DoDispose(), ns3::TcpSocketFactoryImpl::DoDispose(), ns3::UdpL4Protocol::DoDispose(), ns3::UdpSocketFactoryImpl::DoDispose(), ns3::LrWpanMac::DoDispose(), ns3::LrWpanNetDevice::DoDispose(), ns3::LrWpanPhy::DoDispose(), ns3::CcHelper::DoDispose(), ns3::LteHelper::DoDispose(), ns3::LteHexGridEnbTopologyHelper::DoDispose(), ns3::ComponentCarrierEnb::DoDispose(), ns3::ComponentCarrierUe::DoDispose(), ns3::ComponentCarrier::DoDispose(), ns3::LteNetDevice::DoDispose(), ns3::LteUeMac::DoDispose(), ns3::LteSimpleHelper::DoDispose(), ns3::GaussMarkovMobilityModel::DoDispose(), ns3::RandomDirection2dMobilityModel::DoDispose(), ns3::RandomWalk2dMobilityModel::DoDispose(), ns3::WaypointMobilityModel::DoDispose(), ns3::DistributedSimulatorImpl::DoDispose(), ns3::NullMessageSimulatorImpl::DoDispose(), ns3::Application::DoDispose(), ns3::ChannelListPriv::DoDispose(), ns3::NodeListPriv::DoDispose(), ns3::Node::DoDispose(), ns3::NetDeviceQueueInterface::DoDispose(), ns3::SimpleNetDevice::DoDispose(), ns3::PointToPointNetDevice::DoDispose(), ns3::SixLowPanNetDevice::DoDispose(), ns3::AlohaNoackNetDevice::DoDispose(), ns3::HalfDuplexIdealPhy::DoDispose(), ns3::NonCommunicatingNetDevice::DoDispose(), ns3::DataCalculator::DoDispose(), ns3::TapBridge::DoDispose(), ns3::QueueDiscClass::DoDispose(), ns3::QueueDisc::DoDispose(), ns3::TrafficControlLayer::DoDispose(), ns3::UanChannel::DoDispose(), ns3::UanNetDevice::DoDispose(), ns3::UanNoiseModel::DoDispose(), ns3::UanPhyCalcSinr::DoDispose(), ns3::UanPhyPer::DoDispose(), ns3::UanPropModel::DoDispose(), ns3::VirtualNetDevice::DoDispose(), ns3::DefaultChannelScheduler::DoDispose(), ns3::WaveNetDevice::DoDispose(), ns3::WifiNetDevice::DoDispose(), and ns3::WimaxNetDevice::DoDispose().
DoGetObject()
Ptr< Object > ns3::Object::DoGetObject (TypeId tid) const private
Find an Object of TypeId tid in the aggregates of this Object.
Parameters
[in] tid The TypeId we're looking for
Returns
The matching Object, if it is found
Definition at line 149 of file object.cc.
References ns3::Object::Aggregates::buffer, CheckLoose(), GetInstanceTypeId(), ns3::TypeId::GetParent(), GetTypeId(), m_aggregates, m_getObjectCount, sample-rng-plot::n, ns3::Object::Aggregates::n, NS_ASSERT, NS_LOG_FUNCTION, and UpdateSortedArray().
Referenced by AggregateObject(), and GetObject().
DoInitialize()
void ns3::Object::DoInitialize (void) protected virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented in ns3::WifiPhy, ns3::WifiNetDevice, ns3::Txop, ns3::StaWifiMac, ns3::SpectrumWifiPhy, ns3::RrpaaWifiManager, ns3::RraaWifiManager, ns3::QosTxop, ns3::ParfWifiManager, ns3::OnoeWifiManager, ns3::MinstrelWifiManager, ns3::MinstrelHtWifiManager, ns3::IdealWifiManager, ns3::CaraWifiManager, ns3::ArfWifiManager, ns3::AparfWifiManager, ns3::ApWifiMac, ns3::AmrrWifiManager, ns3::AarfcdWifiManager, ns3::AarfWifiManager, ns3::WaveNetDevice, ns3::VsaManager, ns3::DefaultChannelScheduler, ns3::ChannelScheduler, ns3::ChannelCoordinator, ns3::UanNetDevice, ns3::TrafficControlLayer, ns3::QueueDisc, Emitter, Emitter, Emitter, Emitter, ns3::TraceFadingLossModel, ns3::olsr::RoutingProtocol, ns3::Node, ns3::Application, ns3::SteadyStateRandomWaypointMobilityModel, ns3::RandomWaypointMobilityModel, ns3::RandomWalk2dMobilityModel, ns3::RandomDirection2dMobilityModel, ns3::LteSimpleNetDevice, ns3::LteSimpleHelper, ns3::LteUeRrc, ns3::LteUePowerControl, ns3::LteUePhy, ns3::LteUeNetDevice, ns3::LteEnbPhy, ns3::LteEnbNetDevice, ns3::ComponentCarrierUe, ns3::ComponentCarrierEnb, ns3::LteHelper, ns3::CcHelper, ns3::LrWpanNetDevice, ns3::LrWpanMac, ns3::Ipv4ListRouting, ns3::RvBatteryModel, ns3::LiIonEnergySource, ns3::BasicEnergySource, ns3::BasicEnergyHarvester, ns3::EnergySourceContainer, ns3::EnergyHarvesterContainer, ns3::ThreeGppHttpVariables, ns3::aodv::RoutingProtocol, ns3::RegularWifiMac, ns3::MeshWifiInterfaceMac, ns3::dot11s::PeerManagementProtocol, ns3::dot11s::HwmpProtocol, ns3::LteFfrSimple, ns3::SimpleUeComponentCarrierManager, ns3::NoOpHandoverAlgorithm, ns3::NoOpComponentCarrierManager, ns3::LteRlcSm, ns3::LteFrStrictAlgorithm, ns3::LteFrSoftAlgorithm, ns3::LteFrNoOpAlgorithm, ns3::LteFrHardAlgorithm, ns3::LteFfrSoftAlgorithm, ns3::LteFfrEnhancedAlgorithm, ns3::LteFfrDistributedAlgorithm, ns3::UeManager, ns3::LteAnr, ns3::A3RsrpHandoverAlgorithm, ns3::A2A4RsrqHandoverAlgorithm, ns3::RipNg, ns3::Rip, and ns3::MobilityBuildingInfo.
Definition at line 353 of file object.cc.
References m_initialized, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::LteEnbRrc::ConfigureCarriers(), ns3::Rip::DoInitialize(), ns3::RipNg::DoInitialize(), ns3::A2A4RsrqHandoverAlgorithm::DoInitialize(), ns3::A3RsrpHandoverAlgorithm::DoInitialize(), ns3::LteFfrDistributedAlgorithm::DoInitialize(), ns3::LteFfrEnhancedAlgorithm::DoInitialize(), ns3::LteFfrSoftAlgorithm::DoInitialize(), ns3::LteFrHardAlgorithm::DoInitialize(), ns3::LteFrNoOpAlgorithm::DoInitialize(), ns3::LteFrSoftAlgorithm::DoInitialize(), ns3::LteFrStrictAlgorithm::DoInitialize(), ns3::NoOpComponentCarrierManager::DoInitialize(), ns3::NoOpHandoverAlgorithm::DoInitialize(), ns3::SimpleUeComponentCarrierManager::DoInitialize(), ns3::LteFfrSimple::DoInitialize(), ns3::aodv::RoutingProtocol::DoInitialize(), ns3::Ipv4ListRouting::DoInitialize(), ns3::LrWpanMac::DoInitialize(), ns3::LrWpanNetDevice::DoInitialize(), ns3::LteHelper::DoInitialize(), ns3::LteEnbPhy::DoInitialize(), ns3::LteUePhy::DoInitialize(), ns3::LteSimpleHelper::DoInitialize(), ns3::RandomDirection2dMobilityModel::DoInitialize(), ns3::RandomWalk2dMobilityModel::DoInitialize(), ns3::RandomWaypointMobilityModel::DoInitialize(), ns3::SteadyStateRandomWaypointMobilityModel::DoInitialize(), ns3::Application::DoInitialize(), ns3::Node::DoInitialize(), ns3::QueueDisc::DoInitialize(), ns3::TrafficControlLayer::DoInitialize(), ns3::UanNetDevice::DoInitialize(), ns3::WaveNetDevice::DoInitialize(), ns3::WifiNetDevice::DoInitialize(), and Initialize().
GetAggregateIterator()
Object::AggregateIterator ns3::Object::GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
Returns
An iterator to the first Object aggregated to this Object.
If no Objects are aggregated to this Object, then, the returned iterator will be empty and AggregateIterator::HasNext() will always return false.
Definition at line 331 of file object.cc.
References AggregateIterator, and NS_LOG_FUNCTION.
GetInstanceTypeId()
TypeId ns3::Object::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Reimplemented in ns3::TrafficControlLayer, anonymous_namespace{sequence-number-test-suite.cc}::SequenceNumberTestObj, ns3::TcpOptionUnknown, ns3::TcpOption, ns3::TcpOptionWinScale, ns3::TcpOptionTS, ns3::TcpOptionSack, ns3::TcpOptionSackPermitted, ns3::TcpOptionMSS, ns3::TcpOptionNOP, ns3::TcpOptionEnd, ns3::RttMeanDeviation, ns3::RttEstimator, ns3::Ns3NscStack, ns3::Icmpv6L4Protocol, ns3::PointToPointEpcHelper, ns3::NoBackhaulEpcHelper, ns3::EmuEpcHelper, ns3::TcpSocketBase, ns3::FlowMonitor, ns3::dsr::DsrOptionAck, ns3::dsr::DsrOptionAckReq, ns3::dsr::DsrOptionRerr, ns3::dsr::DsrOptionSR, ns3::dsr::DsrOptionRrep, and ns3::dsr::DsrOptionRreq.
Definition at line 79 of file object.cc.
References m_tid, and NS_LOG_FUNCTION.
Referenced by AggregateObject(), ns3::cell_data_function_col_0(), ns3::cell_tooltip_callback(), DoGetObject(), ns3::AttributeIterator::DoIterate(), ns3::Config::Resolver::DoResolve(), GetTypicalAggregations(), ns3::AttributeIterator::StartVisitArrayItem(), ns3::AttributeIterator::StartVisitObject(), and ns3::AttributeIterator::StartVisitPointerAttribute().
GetObject() [1/2]
template<typename T > Ptr< T > ns3::Object::GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
Parameters
[in] tid The TypeId of the requested Object.
Returns
A pointer to the requested Object, or zero if it could not be found.
Definition at line 484 of file object.h.
References DoGetObject(), and ns3::PeekPointer().
GetObject() [2/2]
template<typename T > Ptr< T > ns3::Object::GetObject (void) const inline
Get a pointer to the requested aggregated Object.
Returns
A pointer to the requested Object, or zero if it could not be found.
Definition at line 464 of file object.h.
References ns3::Object::Aggregates::buffer, DoGetObject(), m_aggregates, and ns3::PeekPointer().
Referenced by ns3::Ipv4FlowProbe::Ipv4FlowProbe(), ns3::Ipv6FlowProbe::Ipv6FlowProbe(), ns3::NoBackhaulEpcHelper::NoBackhaulEpcHelper(), ns3::SameRoomPositionAllocator::SameRoomPositionAllocator(), Tunnel::Tunnel(), ns3::DhcpClient::AcceptAck(), ns3::DrbActivator::ActivateDrb(), ns3::NoBackhaulEpcHelper::ActivateEpsBearer(), ns3::Ipv6Interface::AddAddress(), ns3::EmuEpcHelper::AddEnb(), ns3::NoBackhaulEpcHelper::AddEnb(), ns3::PointToPointEpcHelper::AddEnb(), ns3::lorawan::NetworkServer::AddGateway(), ns3::Ipv4L3Protocol::AddInterface(), ns3::Ipv6L3Protocol::AddInterface(), ns3::NscTcpL4Protocol::AddInterface(), ns3::FileHelper::AddProbe(), ns3::GnuplotHelper::AddProbe(), ns3::NoBackhaulEpcHelper::AddS1Interface(), TcpTestCase::AddSimpleNetDevice(), AddSimpleNetDevice(), TcpTestCase::AddSimpleNetDevice6(), ns3::EmuEpcHelper::AddX2Interface(), ns3::NoBackhaulEpcHelper::AddX2Interface(), OcbWifiMacTestCase::AdvancePosition(), Experiment::ApplicationSetup(), ns3::LteUeRrc::ApplyRadioResourceConfigDedicated(), ns3::Ipv4AddressHelper::Assign(), ns3::Ipv6AddressHelper::Assign(), ns3::AodvHelper::AssignStreams(), ns3::InternetStackHelper::AssignStreams(), ns3::RipHelper::AssignStreams(), ns3::RipNgHelper::AssignStreams(), ns3::MobilityHelper::AssignStreams(), ns3::OlsrHelper::AssignStreams(), ns3::UdpSocketImpl::Bind(), ns3::UdpSocketImpl::BindToNetDevice(), ns3::PointToPointDumbbellHelper::BoundingBox(), ns3::PointToPointGridHelper::BoundingBox(), ns3::PointToPointStarHelper::BoundingBox(), ns3::GlobalRouteManagerImpl::BuildGlobalRoutingDatabase(), ns3::GlobalRouter::BuildNetworkLSAs(), ns3::LteHelper::ChannelModelInitialization(), LteRadioLinkFailureTestCase::CheckConnected(), LteRrcConnectionEstablishmentTestCase::CheckConnected(), LteX2HandoverMeasuresTestCase::CheckConnected(), LteX2HandoverTestCase::CheckConnected(), TcFlowControlTestCase::CheckDeviceQueueStopped(), ns3::GlobalRouteManagerImpl::CheckForStubNode(), LteRadioLinkFailureTestCase::CheckIdle(), Ns2MobilityHelperTest::CheckInitialPositions(), LteRrcConnectionEstablishmentTestCase::CheckNotConnected(), TcFlowControlTestCase::CheckPacketsInQueueDisc(), ns3::Ipv6RawSocketImpl::Close(), ns3::Ipv4RawSocketImpl::Close(), ns3::LrWpanNetDevice::CompleteConfig(), ns3::lorawan::LorawanMacHelper::ConfigureForAlohaRegion(), ns3::lorawan::LorawanMacHelper::ConfigureForEuRegion(), WaypointMobilityModelNotifyTest::CourseChangeCallback(), ns3::DsrHelper::Create(), ns3::SpectrumPhyHelper::Create(), ns3::SpectrumWifiPhyHelper::Create(), ns3::ArpL3Protocol::CreateCache(), ns3::olsr::HelloRegressionTest::CreateNodes(), ns3::olsr::TcRegressionTest::CreateNodes(), ThreeGppHttpObjectTestCase::CreateSimpleInternetNode(), ns3::TcpGeneralTest::CreateSocket(), ns3::Socket::CreateSocket(), TestCaseHelper::CreatWaveDevice(), ns3::GlobalRouteManagerImpl::DeleteGlobalRoutes(), ns3::GlobalRouter::DiscoverLSAs(), DoBeamforming(), ThreeGppSpectrumPropagationLossModelTest::DoBeamforming(), ns3::lorawan::BuildingPenetrationLoss::DoCalcRxPower(), ns3::UeManager::DoInitialize(), ns3::LteUeRrc::DoInitialize(), ns3::lorawan::LoraRadioEnergyModelHelper::DoInstall(), ns3::WifiRadioEnergyModelHelper::DoInstall(), ns3::lorawan::LoraHelper::DoPrintDeviceStatus(), ns3::Config::Resolver::DoResolve(), ChainRegressionTest::DoRun(), ThreeGppHttpObjectTestCase::DoRun(), LteCellSelectionTestCase::DoRun(), LteRadioLinkFailureTestCase::DoRun(), LteUeMeasurementsPiecewiseTestCase1::DoRun(), LteUeMeasurementsPiecewiseTestCase2::DoRun(), LteUeMeasurementsHandoverTestCase::DoRun(), LteHandoverTargetTestCase::DoRun(), RandomRoomPositionAllocatorTestCase::DoRun(), SameRoomPositionAllocatorTestCase::DoRun(), BuildingsChannelConditionModelTestCase::DoRun(), PointerAttributeTestCase::DoRun(), ns3::tests::ObjectFactoryTestCase::DoRun(), Ipv4DeduplicationTest::DoRun(), Ipv4ForwardingTest::DoRun(), Ipv4FragmentationTest::DoRun(), LinkTest::DoRun(), LanTest::DoRun(), TwoLinkTest::DoRun(), TwoLanTest::DoRun(), BridgeTest::DoRun(), TwoBridgeTest::DoRun(), Ipv4DynamicGlobalRoutingTestCase::DoRun(), Ipv4GlobalRoutingSlash32TestCase::DoRun(), Ipv4HeaderTest::DoRun(), Ipv4PacketInfoTagTest::DoRun(), Ipv4RawSocketImplTest::DoRun(), Ipv4RipTest::DoRun(), Ipv4RipCountToInfinityTest::DoRun(), Ipv4RipSplitHorizonStrategyTest::DoRun(), Ipv4StaticRoutingSlash32TestCase::DoRun(), Ipv6ForwardingTest::DoRun(), Ipv6FragmentationTest::DoRun(), Ipv6PacketInfoTagTest::DoRun(), Ipv6RawSocketImplTest::DoRun(), Ipv6RipngTest::DoRun(), Ipv6RipngCountToInfinityTest::DoRun(), Ipv6RipngSplitHorizonStrategyTest::DoRun(), UdpSocketLoopbackTest::DoRun(), Udp6SocketLoopbackTest::DoRun(), UdpSocketImplTest::DoRun(), Udp6SocketImplTest::DoRun(), PhyConnectivityTest::DoRun(), DownlinkPacketTest::DoRun(), LinkCheckTest::DoRun(), EpcS1uDlTestCase::DoRun(), EpcS1uUlTestCase::DoRun(), CarrierAggregationTestCase::DoRun(), LenaCqaFfMacSchedulerTestCase1::DoRun(), LenaCqaFfMacSchedulerTestCase2::DoRun(), ns3::LenaDeactivateBearerTestCase::DoRun(), LteDownlinkPowerControlTestCase::DoRun(), LenaFdBetFfMacSchedulerTestCase1::DoRun(), LenaFdBetFfMacSchedulerTestCase2::DoRun(), LenaFdMtFfMacSchedulerTestCase::DoRun(), LenaFdTbfqFfMacSchedulerTestCase1::DoRun(), LenaFdTbfqFfMacSchedulerTestCase2::DoRun(), LteHardFrTestCase::DoRun(), LteStrictFrTestCase::DoRun(), LteStrictFrAreaTestCase::DoRun(), LteSoftFrAreaTestCase::DoRun(), LteSoftFfrAreaTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LenaHarqTestCase::DoRun(), LteInterferenceHardFrTestCase::DoRun(), LteInterferenceStrictFrTestCase::DoRun(), LteInterferenceTestCase::DoRun(), LteIpv6RoutingTestCase::DoRun(), LteLinkAdaptationTestCase::DoRun(), LenaMimoTestCase::DoRun(), LtePathlossModelSystemTestCase::DoRun(), LenaPfFfMacSchedulerTestCase1::DoRun(), LenaPfFfMacSchedulerTestCase2::DoRun(), LenaDataPhyErrorModelTestCase::DoRun(), LenaDlCtrlPhyErrorModelTestCase::DoRun(), LenaPssFfMacSchedulerTestCase1::DoRun(), LenaPssFfMacSchedulerTestCase2::DoRun(), LenaRrFfMacSchedulerTestCase::DoRun(), LenaTdBetFfMacSchedulerTestCase1::DoRun(), LenaTdBetFfMacSchedulerTestCase2::DoRun(), LenaTdMtFfMacSchedulerTestCase::DoRun(), LenaTdTbfqFfMacSchedulerTestCase1::DoRun(), LenaTdTbfqFfMacSchedulerTestCase2::DoRun(), LenaTtaFfMacSchedulerTestCase::DoRun(), LteUplinkOpenLoopPowerControlTestCase::DoRun(), LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun(), LteEnbAntennaTestCase::DoRun(), LteEpcE2eDataTestCase::DoRun(), LteRrcConnectionEstablishmentTestCase::DoRun(), LteRrcConnectionEstablishmentErrorTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), LteX2HandoverTestCase::DoRun(), WaypointMobilityModelViaHelper::DoRun(), SteadyStateRandomWaypointTest::DoRun(), WaypointMobilityModelNotifyTest::DoRun(), WaypointMobilityModelAddWaypointTest::DoRun(), SixlowpanFragmentationTest::DoRun(), SixlowpanHc1ImplTest::DoRun(), SixlowpanIphcImplTest::DoRun(), SpectrumIdealPhyTestCase::DoRun(), WaveformGeneratorTestCase::DoRun(), WifiAcMappingTest::DoRun(), AcousticModemEnergyTestCase::DoRun(), AcousticModemEnergyDepletionTestCase::DoRun(), InterferenceHelperSequenceTest::DoRun(), ns3::SixLowPanNetDevice::DoSend(), ns3::dsr::DsrOptionRerr::DoSendError(), ns3::UdpSocketImpl::DoSendTo(), ns3::Ipv6Interface::DoSetup(), ns3::Ipv4Interface::DoSetup(), ns3::AsciiTraceHelperForIpv4::EnableAsciiIpv4Impl(), ns3::AsciiTraceHelperForIpv6::EnableAsciiIpv6Impl(), ns3::PcapHelperForIpv4::EnablePcapIpv4(), ns3::PcapHelperForIpv6::EnablePcapIpv6(), ns3::Names::Find(), ns3::LteStatsCalculator::FindCellIdFromEnbRlcPath(), ns3::LteStatsCalculator::FindImsiFromEnbRlcPath(), ns3::LteStatsCalculator::FindImsiFromLteNetDevice(), ns3::LteStatsCalculator::FindImsiFromUePhy(), ns3::GlobalRouteManagerImpl::FindOutgoingInterfaceId(), WaypointMobilityModelNotifyTest::ForceUpdates(), ns3::Icmpv4L4Protocol::Forward(), ns3::Icmpv6L4Protocol::Forward(), ns3::BsmApplication::GenerateWaveTraffic(), OcbWifiMacTestCase::GetCurrentPosition(), ns3::MobilityHelper::GetDistanceSquaredBetween(), ns3::PcapHelper::GetFilenameFromInterfacePair(), ns3::AsciiTraceHelper::GetFilenameFromInterfacePair(), ns3::Ipv6ExtensionFragment::GetFragments(), ns3::MeshWifiInterfaceMac::GetFrequencyChannel(), ns3::Ipv4L3Protocol::GetIcmp(), ns3::Ipv6L3Protocol::GetIcmpv6(), ns3::dsr::DsrOptions::GetIDfromIP(), ns3::dsr::DsrRouting::GetIDfromIP(), ns3::dsr::DsrRouting::GetIPfromID(), ns3::dsr::DsrRouting::GetIPfromMAC(), ns3::AnimationInterface::GetIpv4Address(), ns3::AnimationInterface::GetIpv4Addresses(), ns3::AnimationInterface::GetIpv6Address(), ns3::AnimationInterface::GetIpv6Addresses(), ns3::ThreeGppPropagationLossModel::GetKey(), ns3::HybridBuildingsPropagationLossModel::GetLoss(), ns3::ItuR1238PropagationLossModel::GetLoss(), ns3::OhBuildingsPropagationLossModel::GetLoss(), ns3::lorawan::GetMacLayerFromNode(), ns3::SameRoomPositionAllocator::GetNext(), ns3::BsmApplication::GetNode(), ns3::dsr::DsrOptions::GetNodeWithAddress(), ns3::dsr::DsrRouting::GetNodeWithAddress(), Experiment::GetPosition(), GetPosition(), NodeStatistics::GetPosition(), ns3::BuildingsPropagationLossModel::GetShadowing(), ns3::NoBackhaulEpcHelper::GetUeDefaultGatewayAddress(), ns3::NoBackhaulEpcHelper::GetUeDefaultGatewayAddress6(), ns3::ThreeGppPropagationLossModel::GetVectorDifference(), GetYansWifiPhyPtr(), SetChannelFrequencyTest::GetYansWifiPhyPtr(), ns3::Ipv4L3Protocol::HandleFragmentsTimeout(), ns3::Ipv6ExtensionFragment::HandleFragmentsTimeout(), ns3::SixLowPanNetDevice::HandleFragmentsTimeout(), ns3::Icmpv6L4Protocol::HandleNS(), ns3::Icmpv6L4Protocol::HandlePacketTooBig(), ns3::Icmpv6L4Protocol::HandleRA(), ns3::Radvd::HandleRead(), ns3::BsmApplication::HandleReceivedBsmPacket(), ns3::Icmpv6L4Protocol::HandleRedirection(), ns3::Icmpv6L4Protocol::HandleRS(), ns3::GlobalRouteManagerImpl::InitializeRoutes(), ns3::RadioEnvironmentMapHelper::Install(), ns3::lorawan::LoraHelper::Install(), ns3::WifiHelper::Install(), ns3::EnergyHarvesterHelper::Install(), ns3::WaveBsmHelper::Install(), ns3::AdhocAlohaNoackIdealPhyHelper::Install(), ns3::SpectrumAnalyzerHelper::Install(), ns3::WaveformGeneratorHelper::Install(), ns3::UanHelper::Install(), ns3::TvSpectrumTransmitterHelper::Install(), ns3::dot11s::HwmpProtocol::Install(), ns3::dot11s::PeerManagementProtocol::Install(), ns3::flame::FlameProtocol::Install(), ns3::BuildingsHelper::Install(), ns3::FlowMonitorHelper::Install(), ns3::CsmaHelper::Install(), ns3::InternetStackHelper::Install(), ns3::MobilityHelper::Install(), ns3::TvSpectrumTransmitterHelper::InstallAdjacent(), ns3::FlowMonitorHelper::InstallAll(), AodvExample::InstallApplications(), DsdvManetExample::InstallApplications(), ns3::DhcpHelper::InstallDhcpClientPriv(), ns3::DhcpHelper::InstallDhcpServer(), ns3::DhcpHelper::InstallFixedAddress(), ns3::Ipv6L3Protocol::IpForward(), ns3::Ipv4L3Protocol::IpForward(), ns3::Ipv6L3Protocol::IpMulticastForward(), ns3::Ipv4L3Protocol::IpMulticastForward(), ns3::Ipv6RawSocketImpl::Ipv6JoinGroup(), ns3::UdpSocketImpl::Ipv6JoinGroup(), ns3::DhcpClient::LinkStateHandler(), ns3::Ipv6L3Protocol::LocalDeliver(), ns3::BuildingsHelper::MakeConsistent(), ns3::BuildingsHelper::MakeMobilityModelConsistent(), ns3::dsr::DsrRouting::NotifyNewAggregate(), ns3::TcpL4Protocol::NotifyNewAggregate(), ns3::UdpL4Protocol::NotifyNewAggregate(), OcbWifiMacTestCase::PostDeviceConfiguration(), ns3::Ipv6RoutingHelper::Print(), ns3::Ipv4RoutingHelper::Print(), ns3::Ipv4RoutingHelper::PrintArpCache(), ns3::Ipv4RoutingHelper::PrintArpCacheEvery(), ns3::Ipv6RoutingHelper::PrintEvery(), ns3::Ipv4RoutingHelper::PrintEvery(), PrintGnuplottableEnbListToFile(), PrintGnuplottableUeListToFile(), IpAddressHelper::PrintIpAddresses(), ns3::Ipv6RoutingHelper::PrintNdiscCache(), ns3::Ipv6RoutingHelper::PrintNdiscCacheEvery(), PrintPosition(), ns3::V4TraceRouteHelper::PrintTraceRouteAt(), PrintUePosition(), ns3::Ipv6ExtensionRouting::Process(), ns3::Ipv6ExtensionLooseRouting::Process(), ns3::dsr::DsrOptionRreq::Process(), ns3::dsr::DsrOptionRrep::Process(), ns3::dsr::DsrOptionSR::Process(), ns3::dsr::DsrOptionRerr::Process(), ns3::dsr::DsrOptionAckReq::Process(), ns3::dsr::DsrOptionAck::Process(), ns3::GlobalRouter::ProcessBridgedBroadcastLink(), ns3::SixLowPanNetDevice::ProcessFragment(), ns3::Ipv6Extension::ProcessOptions(), ns3::GlobalRouter::ProcessPointToPointLink(), ns3::GlobalRouter::ProcessSingleBroadcastLink(), ns3::dsr::DsrRouting::PromiscReceive(), ns3::Ipv4L3Protocol::Receive(), ns3::Ipv6L3Protocol::Receive(), ns3::Icmpv6L4Protocol::Receive(), ns3::SixLowPanNetDevice::ReceiveFromDevice(), ns3::AnimationInterface::RecursiveIpv4RoutePathSearch(), ns3::DhcpClient::RemoveAndStart(), ns3::Ipv6AutoconfiguredPrefix::RemoveMe(), ns3::MeshHelper::Report(), ns3::Dot11sStack::Report(), ns3::Ipv6L3Protocol::ReportDrop(), HwmpReactiveRegressionTest::ResetPosition(), HwmpSimplestRegressionTest::ResetPosition(), ns3::MeshHelper::ResetStats(), ns3::Dot11sStack::ResetStats(), ns3::Ipv4L3Protocol::RouteInputError(), ns3::Ipv6L3Protocol::RouteInputError(), RoutingExperiment::Run(), NetAnimExperiment::Run(), Experiment::Run(), TestInterBssConstantObssPdAlgo::RunOne(), Issue40TestCase::RunOne(), ns3::Ping6::Send(), ns3::Ipv4Interface::Send(), ns3::Ipv6Interface::Send(), ns3::Ipv4L3Protocol::Send(), ns3::Ipv6L3Protocol::Send(), ns3::Radvd::Send(), ns3::YansWifiChannel::Send(), ns3::SimpleOfdmWimaxChannel::Send(), ns3::NscTcpL4Protocol::send_callback(), ns3::ArpL3Protocol::SendArpRequest(), ns3::Icmpv4L4Protocol::SendMessage(), ns3::Icmpv6L4Protocol::SendMessage(), ns3::DhcpServer::SendOffer(), DownlinkPacketTest::SendPacket(), LinkCheckTest::SendPacket(), ns3::TcpL4Protocol::SendPacketV4(), ns3::TcpL4Protocol::SendPacketV6(), ns3::Ipv4L3Protocol::SendRealOut(), ns3::Ipv6L3Protocol::SendRealOut(), ns3::Ipv4RawSocketImpl::SendTo(), ns3::Ipv6RawSocketImpl::SendTo(), ns3::RipHelper::SetDefaultRouter(), ns3::RipNgHelper::SetDefaultRouter(), ns3::UdpEchoClientHelper::SetFill(), Experiment::SetPosition(), SetPosition(), NodeStatistics::SetPosition(), ns3::MobilityHelper::SetPositionAllocator(), ns3::LteHexGridEnbTopologyHelper::SetPositionAndInstallEnbDevice(), ns3::lorawan::LorawanMacHelper::SetSpreadingFactorsGivenDistribution(), ns3::lorawan::LorawanMacHelper::SetSpreadingFactorsUp(), VanetRoutingExperiment::SetupAdhocMobilityNodes(), UanExperiment::SetupCommunications(), ns3::UeManager::SetupDataRadioBearer(), TcpTestCase::SetupDefaultSim(), TcpTestCase::SetupDefaultSim6(), ns3::TcpSocketBase::SetupEndpoint(), ns3::TcpSocketBase::SetupEndpoint6(), DsdvManetExample::SetupMobility(), showPosition(), ns3::GlobalRouteManagerImpl::SPFAddASExternal(), ns3::GlobalRouteManagerImpl::SPFIntraAddRouter(), ns3::GlobalRouteManagerImpl::SPFIntraAddStub(), ns3::GlobalRouteManagerImpl::SPFIntraAddTransit(), ns3::Radvd::StartApplication(), Receiver::StartApplication(), ns3::DhcpClient::StartApplication(), ns3::DhcpServer::StartApplication(), ns3::DhcpClient::StopApplication(), ns3::MeshWifiInterfaceMac::SwitchFrequencyChannel(), TearDownLink(), LteFrAreaTestCase::TeleportUe2(), LteX2HandoverTestCase::TeleportUeNearTargetEnb(), LteX2HandoverTestCase::TeleportUeToMiddle(), ns3::AnimationInterface::TrackIpv4RoutePaths(), ns3::UanChannel::TxPacket(), GlobalPathlossDatabase::UpdatePathloss(), NetAnimExperiment::UpdatePositions(), Experiment::UpdatePositions(), and ns3::AnimationInterface::WriteNodeEnergies().
GetTypeId()
TypeId ns3::Object::GetTypeId (void) static
Register this type.
Returns
The Object TypeId.
Definition at line 86 of file object.cc.
References ns3::TypeId::SetParent().
Referenced by DoGetObject().
Initialize()
void ns3::Object::Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
This method calls the virtual DoInitialize() method on all the Objects aggregated to this Object. DoInitialize() will be called only once over the lifetime of an Object, just like DoDispose() is called only once.
See also
DoInitialize()
Note: the code here is a bit tricky because we need to protect ourselves from modifications in the aggregate array while DoInitialize is called. The user's implementation of the DoInitialize method could call GetObject (which could reorder the array) and it could call AggregateObject which would add an object at the end of the array. To be safe, we restart iteration over the array whenever we call some user code, just in case.
Definition at line 183 of file object.cc.
References ns3::Object::Aggregates::buffer, DoInitialize(), m_aggregates, m_initialized, sample-rng-plot::n, ns3::Object::Aggregates::n, and NS_LOG_FUNCTION.
Referenced by ns3::BuildingListPriv::Add(), ns3::NodeListPriv::Add(), ns3::Node::AddApplication(), ns3::Node::AddDevice(), ns3::LteUeRrc::ApplyRadioResourceConfigDedicated(), ns3::PrioQueueDisc::CheckConfig(), ns3::TbfQueueDisc::CheckConfig(), ns3::FqCoDelQueueDisc::DoEnqueue(), ns3::RegularWifiMac::DoInitialize(), ns3::Node::DoInitialize(), ns3::WaveNetDevice::DoInitialize(), ns3::ApWifiMac::DoInitialize(), ns3::WifiNetDevice::DoInitialize(), SteadyStateRandomWaypointTest::DoRun(), WaypointMobilityModelNotifyTest::DoRun(), WaypointMobilityModelAddWaypointTest::DoRun(), FqCoDelQueueDiscNoSuitableFilter::DoRun(), FqCoDelQueueDiscIPFlowsSeparationAndPacketLimit::DoRun(), FqCoDelQueueDiscDeficit::DoRun(), FqCoDelQueueDiscTCPFlowsSeparation::DoRun(), FqCoDelQueueDiscUDPFlowsSeparation::DoRun(), CobaltQueueDiscBasicEnqueueDequeue::DoRun(), CoDelQueueDiscBasicEnqueueDequeue::DoRun(), CoDelQueueDiscBasicOverflow::DoRun(), CoDelQueueDiscBasicDrop::DoRun(), PrioQueueDiscTestCase::DoRun(), QueueDiscTracesTestCase::DoRun(), ns3::LteHelper::InstallEnbDevice(), ns3::LteSimpleHelper::InstallEnbDevice(), ns3::LteHelper::InstallSingleEnbDevice(), AredQueueDiscTestCase::RunAredDiscTest(), CobaltQueueDiscDropTest::RunDropTest(), FifoQueueDiscTestCase::RunFifoTest(), PieQueueDiscTestCase::RunPieTest(), RedQueueDiscTestCase::RunRedTest(), and TbfQueueDiscTestCase::RunTbfTest().
IsInitialized()
bool ns3::Object::IsInitialized (void) const
Check if the object has been initialized.
Returns
true if the object has been initialized.
Definition at line 208 of file object.cc.
References m_initialized, and NS_LOG_FUNCTION.
Referenced by ns3::SpectrumWifiPhy::ConfigureStandard(), ns3::WifiPhy::DoChannelSwitch(), ns3::WifiPhy::DoFrequencySwitch(), ns3::SpectrumWifiPhy::ResetSpectrumModel(), ns3::SpectrumWifiPhy::SetChannelNumber(), ns3::SpectrumWifiPhy::SetChannelWidth(), ns3::ThreeGppHttpVariables::SetEmbeddedObjectSizeMean(), ns3::ThreeGppHttpVariables::SetEmbeddedObjectSizeStdDev(), ns3::SpectrumWifiPhy::SetFrequency(), ns3::ThreeGppHttpVariables::SetMainObjectSizeMean(), and ns3::ThreeGppHttpVariables::SetMainObjectSizeStdDev().
NotifyNewAggregate()
void ns3::Object::NotifyNewAggregate (void) protected virtual
Notify all Objects aggregated to this one of a new Object being aggregated.
This function must be implemented in the stack that needs to notify other stacks connected to the node of their presence in the node.
This method is invoked whenever two sets of Objects are aggregated together. It is invoked exactly once for each Object in both sets. This method can be overridden by subclasses who wish to be notified of aggregation events. These subclasses must chain up to their base class NotifyNewAggregate() method.
It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented in ns3::TrafficControlLayer, ns3::NetDeviceQueueInterface, ns3::UdpL4Protocol, ns3::TcpL4Protocol, ns3::NscTcpL4Protocol, ns3::Ipv6L3Protocol, ns3::Ipv4L3Protocol, ns3::Icmpv6L4Protocol, ns3::Icmpv4L4Protocol, ns3::ArpL3Protocol, and ns3::dsr::DsrRouting.
Definition at line 325 of file object.cc.
References NS_LOG_FUNCTION.
Referenced by AggregateObject(), ns3::dsr::DsrRouting::NotifyNewAggregate(), ns3::ArpL3Protocol::NotifyNewAggregate(), ns3::Icmpv4L4Protocol::NotifyNewAggregate(), ns3::Icmpv6L4Protocol::NotifyNewAggregate(), ns3::Ipv4L3Protocol::NotifyNewAggregate(), ns3::Ipv6L3Protocol::NotifyNewAggregate(), ns3::NscTcpL4Protocol::NotifyNewAggregate(), ns3::TcpL4Protocol::NotifyNewAggregate(), ns3::UdpL4Protocol::NotifyNewAggregate(), ns3::NetDeviceQueueInterface::NotifyNewAggregate(), and ns3::TrafficControlLayer::NotifyNewAggregate().
SetTypeId()
void ns3::Object::SetTypeId (TypeId tid) private
Set the TypeId of this Object.
Parameters
[in] tid The TypeId value to set.
Invoked from ns3::CreateObject only. Initialize the m_tid member variable to keep track of the type of this Object instance.
Definition at line 338 of file object.cc.
References Check(), m_tid, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::ObjectFactory::Create().
UpdateSortedArray()
void ns3::Object::UpdateSortedArray (struct Aggregates * aggregates, uint32_t i) const private
Keep the list of aggregates in most-recently-used order.
Parameters
[in,out] aggregates The list of aggregated Objects.
[in] i The most recently used entry in the list.
Definition at line 239 of file object.cc.
References ns3::Object::Aggregates::buffer, m_getObjectCount, and NS_LOG_FUNCTION.
Referenced by AggregateObject(), and DoGetObject().
Friends And Related Function Documentation
AggregateIterator
friend class AggregateIterator friend
Friends.
Definition at line 323 of file object.h.
Referenced by GetAggregateIterator().
CompleteConstruct
template<typename T > Ptr<T> CompleteConstruct (T * object) friend
Set the TypeId and construct all Attributes of an Object.
Template Parameters
T [explicit] The type of the derived object we are constructing.
Parameters
[in] object The uninitialized object pointer.
Returns
The derived object.
Definition at line 515 of file object.h.
CopyObject [1/2]
template<typename T > Ptr<T> CopyObject (Ptr< const T > object) friend
Parameters
[in] object A pointer to the object to copy.
Returns
A copy of the input object.
This method invoke the copy constructor of the input object and returns the new instance.
Definition at line 499 of file object.h.
CopyObject [2/2]
template<typename T > Ptr<T> CopyObject (Ptr< T > object) friend
Copy an Object.
Parameters
[in] object A pointer to the object to copy.
Returns
A copy of the input object.
This method invoke the copy constructor of the input object and returns the new instance.
Definition at line 499 of file object.h.
Referenced by ns3::TcpSocketBase::TcpSocketBase(), and ns3::TcpYeah::TcpYeah().
ObjectDeleter
friend struct ObjectDeleter friend
Friends.
Definition at line 324 of file object.h.
ObjectFactory
friend class ObjectFactory friend
Friends.
Definition at line 322 of file object.h.
Referenced by ns3::LteHelper::SetEnbComponentCarrierManagerType(), ns3::LteHelper::SetFadingModel(), ns3::LteHelper::SetFfrAlgorithmType(), ns3::LteHelper::SetHandoverAlgorithmType(), ns3::LteHelper::SetPathlossModelType(), ns3::LteHelper::SetSchedulerType(), and ns3::LteHelper::SetUeComponentCarrierManagerType().
Member Data Documentation
m_aggregates
struct Aggregates* ns3::Object::m_aggregates private
A pointer to an array of 'aggregates'.
A pointer to each Object aggregated to this Object is stored in this array. The array is shared by all aggregated Objects so the size of the array is indirectly a reference count.
Definition at line 431 of file object.h.
Referenced by Object(), ~Object(), AggregateObject(), CheckLoose(), Dispose(), DoDelete(), DoGetObject(), GetObject(), Initialize(), and ns3::Object::AggregateIterator::Next().
m_disposed
bool ns3::Object::m_disposed private
Set to true when the DoDispose() method of the Object has run, false otherwise.
Definition at line 418 of file object.h.
Referenced by AggregateObject(), Dispose(), DoDelete(), and DoDispose().
m_getObjectCount
uint32_t ns3::Object::m_getObjectCount private
The number of times the Object was accessed with a call to GetObject().
This integer is used to implement a heuristic to sort the array of aggregates in most-frequently accessed order.
Definition at line 439 of file object.h.
Referenced by DoGetObject(), and UpdateSortedArray().
m_initialized
bool ns3::Object::m_initialized private
Set to true once the DoInitialize() method has run, false otherwise.
Definition at line 423 of file object.h.
Referenced by DoInitialize(), Initialize(), and IsInitialized().
m_tid
TypeId ns3::Object::m_tid private
Identifies the type of this Object instance.
Definition at line 413 of file object.h.
Referenced by GetInstanceTypeId(), and SetTypeId().
The documentation for this class was generated from the following files:
src/core/model/object.h
src/core/model/object.cc