ns-3: ns3::Ipv6ListRouting Class Reference
ns3::Ipv6ListRouting Class Reference
Internet » IPv6 Routing Protocols.
Hold list of Ipv6RoutingProtocol objects.
#include "ipv6-list-routing.h"
Public Member Functions
Ipv6ListRouting ()
Constructor.
virtual ~Ipv6ListRouting ()
Destructor.
virtual void AddRoutingProtocol (Ptr< Ipv6RoutingProtocol > routingProtocol, int16_t priority)
Register a new routing protocol to be used in this IPv4 stack.
virtual uint32_t GetNRoutingProtocols (void) const
Get the number of routing protocols.
virtual Ptr< Ipv6RoutingProtocol > GetRoutingProtocol (uint32_t index, int16_t &priority) const
Get pointer to routing protocol stored at index,.
virtual void NotifyAddAddress (uint32_t interface, Ipv6InterfaceAddress address)
Notify when specified interface add an address.
virtual void NotifyAddRoute (Ipv6Address dst, Ipv6Prefix mask, Ipv6Address nextHop, uint32_t interface, Ipv6Address prefixToUse=Ipv6Address::GetZero())
Notify a new route.
virtual void NotifyInterfaceDown (uint32_t interface)
Notify when specified interface goes DOWN.
virtual void NotifyInterfaceUp (uint32_t interface)
Notify when specified interface goes UP.
virtual void NotifyRemoveAddress (uint32_t interface, Ipv6InterfaceAddress address)
Notify when specified interface add an address.
virtual void NotifyRemoveRoute (Ipv6Address dst, Ipv6Prefix mask, Ipv6Address nextHop, uint32_t interface, Ipv6Address prefixToUse=Ipv6Address::GetZero())
Notify route removing.
virtual void PrintRoutingTable (Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S) const
Print the Routing Table entries.
virtual bool RouteInput (Ptr< const Packet > p, const Ipv6Header &header, Ptr< const NetDevice > idev, UnicastForwardCallback ucb, MulticastForwardCallback mcb, LocalDeliverCallback lcb, ErrorCallback ecb)
Route an input packet (to be forwarded or locally delivered)
virtual Ptr< Ipv6Route > RouteOutput (Ptr< Packet > p, const Ipv6Header &header, Ptr< NetDevice > oif, Socket::SocketErrno &sockerr)
Query routing cache for an existing route, for an outbound packet.
virtual void SetIpv6 (Ptr< Ipv6 > ipv6)
Typically, invoked directly or indirectly from ns3::Ipv6::SetRoutingProtocol.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID of this class.
Static Public Member Functions inherited from ns3::Ipv6RoutingProtocol
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Dispose this object.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
typedef std::pair< int16_t, Ptr< Ipv6RoutingProtocol > > Ipv6RoutingProtocolEntry
Container identifying an IPv6 Routing Protocol entry in the list.
typedef std::list< Ipv6RoutingProtocolEntry > Ipv6RoutingProtocolList
Container of the IPv6 Routing Protocols.
Static Private Member Functions
static bool Compare (const Ipv6RoutingProtocolEntry &a, const Ipv6RoutingProtocolEntry &b)
Compare two routing protocols.
Private Attributes
Ptr< Ipv6 > m_ipv6
Ipv6 this protocol is associated with.
Ipv6RoutingProtocolList m_routingProtocols
List of routing protocols.
Additional Inherited Members
Public Types inherited from ns3::Ipv6RoutingProtocol
typedef Callback< void, Ptr< const Packet >, const Ipv6Header &, Socket::SocketErrno > ErrorCallback
Callback for routing errors (e.g., no route found)
typedef Callback< void, Ptr< const Packet >, const Ipv6Header &, uint32_t > LocalDeliverCallback
Callback for packets to be locally delivered.
typedef Callback< void, Ptr< const NetDevice >, Ptr< Ipv6MulticastRoute >, Ptr< const Packet >, const Ipv6Header & > MulticastForwardCallback
Callback for multicast packets to be forwarded.
typedef Callback< void, Ptr< const NetDevice >, Ptr< Ipv6Route >, Ptr< const Packet >, const Ipv6Header & > UnicastForwardCallback
Callback for unicast packets to be forwarded.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Hold list of Ipv6RoutingProtocol objects.
This class is a specialization of Ipv6RoutingProtocol that allows other instances of Ipv6RoutingProtocol to be inserted in a prioritized list. Routing protocols in the list are consulted one by one, from highest to lowest priority, until a routing protocol is found that will take the packet (this corresponds to a non-zero return value to RouteOutput, or a return value of true to RouteInput). The order by which routing protocols with the same priority value are consulted is undefined.
Definition at line 42 of file ipv6-list-routing.h.
Member Typedef Documentation
Ipv6RoutingProtocolEntry
typedef std::pair<int16_t, Ptr<Ipv6RoutingProtocol> > ns3::Ipv6ListRouting::Ipv6RoutingProtocolEntry private
Container identifying an IPv6 Routing Protocol entry in the list.
Definition at line 113 of file ipv6-list-routing.h.
Ipv6RoutingProtocolList
typedef std::list<Ipv6RoutingProtocolEntry> ns3::Ipv6ListRouting::Ipv6RoutingProtocolList private
Container of the IPv6 Routing Protocols.
Definition at line 118 of file ipv6-list-routing.h.
Constructor & Destructor Documentation
Ipv6ListRouting()
ns3::Ipv6ListRouting::Ipv6ListRouting ()
Constructor.
Definition at line 46 of file ipv6-list-routing.cc.
References NS_LOG_FUNCTION_NOARGS.
~Ipv6ListRouting()
ns3::Ipv6ListRouting::~Ipv6ListRouting () virtual
Destructor.
Definition at line 52 of file ipv6-list-routing.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
AddRoutingProtocol()
void ns3::Ipv6ListRouting::AddRoutingProtocol (Ptr< Ipv6RoutingProtocol > routingProtocol, int16_t priority) virtual
Register a new routing protocol to be used in this IPv4 stack.
Parameters
routingProtocol new routing protocol implementation object
priority priority to give to this routing protocol. Values may range between -32768 and +32767.
Definition at line 245 of file ipv6-list-routing.cc.
References Compare(), m_ipv6, m_routingProtocols, and NS_LOG_FUNCTION.
Referenced by CreateDualStackNode(), TcpTestCase::CreateInternetNode6(), Ipv6ListRoutingNegativeTestCase::DoRun(), and Ipv6ListRoutingPositiveTestCase::DoRun().
Compare()
bool ns3::Ipv6ListRouting::Compare (const Ipv6RoutingProtocolEntry & a, const Ipv6RoutingProtocolEntry & b) static private
Compare two routing protocols.
Parameters
a first object to compare
b second object to compare
Returns
true if they are the same, false otherwise
Definition at line 285 of file ipv6-list-routing.cc.
Referenced by AddRoutingProtocol().
DoDispose()
void ns3::Ipv6ListRouting::DoDispose (void) protected virtual
Dispose this object.
Reimplemented from ns3::Object.
Definition at line 58 of file ipv6-list-routing.cc.
References m_ipv6, m_routingProtocols, and NS_LOG_FUNCTION_NOARGS.
GetNRoutingProtocols()
uint32_t ns3::Ipv6ListRouting::GetNRoutingProtocols (void) const virtual
Get the number of routing protocols.
Returns
number of routing protocols in the list
Definition at line 257 of file ipv6-list-routing.cc.
References m_routingProtocols, and NS_LOG_FUNCTION.
Referenced by Ipv6ListRoutingNegativeTestCase::DoRun(), and Ipv6ListRoutingPositiveTestCase::DoRun().
GetRoutingProtocol()
Ptr< Ipv6RoutingProtocol > ns3::Ipv6ListRouting::GetRoutingProtocol (uint32_t index, int16_t & priority) const virtual
Get pointer to routing protocol stored at index,.
The first protocol (index 0) the highest priority, the next one (index 1) the second highest priority, and so on. The priority parameter is an output parameter and it returns the integer priority of the protocol.
Parameters
index index of protocol to return
priority output parameter, set to the priority of the protocol being returned
Returns
pointer to routing protocol indexed by
Definition at line 264 of file ipv6-list-routing.cc.
References m_routingProtocols, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
Referenced by Ipv6ListRoutingNegativeTestCase::DoRun(), and Ipv6ListRoutingPositiveTestCase::DoRun().
GetTypeId()
TypeId ns3::Ipv6ListRouting::GetTypeId (void) static
Get the type ID of this class.
Returns
type ID
Definition at line 35 of file ipv6-list-routing.cc.
References ns3::TypeId::SetParent().
Referenced by RouteOutput().
NotifyAddAddress()
void ns3::Ipv6ListRouting::NotifyAddAddress (uint32_t interface, Ipv6InterfaceAddress address) virtual
Notify when specified interface add an address.
Protocols are expected to implement this method to be notified whenever a new address is added to an interface. Typically used to add a 'network route' on an interface. Can be invoked on an up or down interface.
Parameters
interface the index of the interface we are being notified about
address a new address being added to an interface
Implements ns3::Ipv6RoutingProtocol.
Definition at line 164 of file ipv6-list-routing.cc.
References first::address, m_routingProtocols, and NS_LOG_FUNCTION.
NotifyAddRoute()
void ns3::Ipv6ListRouting::NotifyAddRoute (Ipv6Address dst, Ipv6Prefix mask, Ipv6Address nextHop, uint32_t interface, Ipv6Address prefixToUse = Ipv6Address::GetZero()) virtual
Notify a new route.
Typically this is used to add another route from IPv6 stack (i.e. ICMPv6 redirect case, ...).
Parameters
dst destination address
mask destination mask
nextHop nextHop for this destination
interface output interface
prefixToUse prefix to use as source with this route
Implements ns3::Ipv6RoutingProtocol.
Definition at line 188 of file ipv6-list-routing.cc.
References m_routingProtocols, and NS_LOG_FUNCTION.
NotifyInterfaceDown()
void ns3::Ipv6ListRouting::NotifyInterfaceDown (uint32_t interface) virtual
Notify when specified interface goes DOWN.
Protocols are expected to implement this method to be notified of the state change of an interface in a node.
Parameters
interface the index of the interface we are being notified about
Implements ns3::Ipv6RoutingProtocol.
Definition at line 152 of file ipv6-list-routing.cc.
References m_routingProtocols, and NS_LOG_FUNCTION.
NotifyInterfaceUp()
void ns3::Ipv6ListRouting::NotifyInterfaceUp (uint32_t interface) virtual
Notify when specified interface goes UP.
Protocols are expected to implement this method to be notified of the state change of an interface in a node.
Parameters
interface the index of the interface we are being notified about
Implements ns3::Ipv6RoutingProtocol.
Definition at line 140 of file ipv6-list-routing.cc.
References m_routingProtocols, and NS_LOG_FUNCTION.
NotifyRemoveAddress()
void ns3::Ipv6ListRouting::NotifyRemoveAddress (uint32_t interface, Ipv6InterfaceAddress address) virtual
Notify when specified interface add an address.
Protocols are expected to implement this method to be notified whenever a new address is removed from an interface. Typically used to remove the 'network route' of an interface. Can be invoked on an up or down interface.
Parameters
interface the index of the interface we are being notified about
address a new address being added to an interface
Implements ns3::Ipv6RoutingProtocol.
Definition at line 176 of file ipv6-list-routing.cc.
References first::address, m_routingProtocols, and NS_LOG_FUNCTION.
NotifyRemoveRoute()
void ns3::Ipv6ListRouting::NotifyRemoveRoute (Ipv6Address dst, Ipv6Prefix mask, Ipv6Address nextHop, uint32_t interface, Ipv6Address prefixToUse = Ipv6Address::GetZero()) virtual
Notify route removing.
Parameters
dst destination address
mask destination mask
nextHop nextHop for this destination
interface output interface
prefixToUse prefix to use as source with this route
Implements ns3::Ipv6RoutingProtocol.
Definition at line 200 of file ipv6-list-routing.cc.
References m_routingProtocols, and NS_LOG_FUNCTION.
PrintRoutingTable()
void ns3::Ipv6ListRouting::PrintRoutingTable (Ptr< OutputStreamWrapper > stream, Time::Unit unit = Time::S) const virtual
Print the Routing Table entries.
Parameters
stream The ostream the Routing table is printed to
unit The time unit to be used in the report
Implements ns3::Ipv6RoutingProtocol.
Definition at line 213 of file ipv6-list-routing.cc.
References ns3::Time::As(), ns3::OutputStreamWrapper::GetStream(), m_ipv6, m_routingProtocols, ns3::Now(), and NS_LOG_FUNCTION.
RouteInput()
bool ns3::Ipv6ListRouting::RouteInput (Ptr< const Packet > p, const Ipv6Header & header, Ptr< const NetDevice > idev, UnicastForwardCallback ucb, MulticastForwardCallback mcb, LocalDeliverCallback lcb, ErrorCallback ecb) virtual
Route an input packet (to be forwarded or locally delivered)
This lookup is used in the forwarding process. The packet is handed over to the Ipv6RoutingProtocol, and will get forwarded onward by one of the callbacks. The Linux equivalent is ip_route_input (). There are four valid outcomes, and a matching callbacks to handle each.
Parameters
p received packet
header input parameter used to form a search key for a route
idev Pointer to ingress network device
ucb Callback for the case in which the packet is to be forwarded as unicast
mcb Callback for the case in which the packet is to be forwarded as multicast
lcb Callback for the case in which the packet is to be locally delivered
ecb Callback to call if there is an error in forwarding
Returns
true if the Ipv6RoutingProtocol takes responsibility for forwarding or delivering the packet, false otherwise
Implements ns3::Ipv6RoutingProtocol.
Definition at line 100 of file ipv6-list-routing.cc.
References ns3::Socket::ERROR_NOROUTETOHOST, ns3::Ipv6Header::GetDestinationAddress(), ns3::Node::GetId(), m_ipv6, m_routingProtocols, NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_LOGIC().
RouteOutput()
Ptr< Ipv6Route > ns3::Ipv6ListRouting::RouteOutput (Ptr< Packet > p, const Ipv6Header & header, Ptr< NetDevice > oif, Socket::SocketErrno & sockerr) virtual
Query routing cache for an existing route, for an outbound packet.
This lookup is used by transport protocols. It does not cause any packet to be forwarded, and is synchronous. Can be used for multicast or unicast. The Linux equivalent is ip_route_output ()
Parameters
p packet to be routed. Note that this method may modify the packet. Callers may also pass in a null pointer.
header input parameter (used to form key to search for the route)
oif Output interface device. May be zero, or may be bound via socket options to a particular output interface.
sockerr Output parameter; socket errno
Returns
a code that indicates what happened in the lookup
Implements ns3::Ipv6RoutingProtocol.
Definition at line 74 of file ipv6-list-routing.cc.
References ns3::Socket::ERROR_NOROUTETOHOST, ns3::Socket::ERROR_NOTERROR, ns3::Ipv6Header::GetDestinationAddress(), ns3::Ipv6Header::GetSourceAddress(), GetTypeId(), m_routingProtocols, NS_LOG_FUNCTION, and NS_LOG_LOGIC().
SetIpv6()
void ns3::Ipv6ListRouting::SetIpv6 (Ptr< Ipv6 > ipv6) virtual
Typically, invoked directly or indirectly from ns3::Ipv6::SetRoutingProtocol.
Parameters
ipv6 the ipv6 object this routing protocol is being associated with
Implements ns3::Ipv6RoutingProtocol.
Definition at line 230 of file ipv6-list-routing.cc.
References m_ipv6, m_routingProtocols, NS_ASSERT, and NS_LOG_FUNCTION.
Member Data Documentation
m_ipv6
Ptr<Ipv6> ns3::Ipv6ListRouting::m_ipv6 private
Ipv6 this protocol is associated with.
Definition at line 129 of file ipv6-list-routing.h.
Referenced by AddRoutingProtocol(), DoDispose(), PrintRoutingTable(), RouteInput(), and SetIpv6().
m_routingProtocols
Ipv6RoutingProtocolList ns3::Ipv6ListRouting::m_routingProtocols private
List of routing protocols.
Definition at line 128 of file ipv6-list-routing.h.
Referenced by AddRoutingProtocol(), DoDispose(), GetNRoutingProtocols(), GetRoutingProtocol(), NotifyAddAddress(), NotifyAddRoute(), NotifyInterfaceDown(), NotifyInterfaceUp(), NotifyRemoveAddress(), NotifyRemoveRoute(), PrintRoutingTable(), RouteInput(), RouteOutput(), and SetIpv6().
The documentation for this class was generated from the following files:
src/internet/model/ipv6-list-routing.h
src/internet/model/ipv6-list-routing.cc