ns-3: Ns3WimaxManagementConnectionsTestCase Class Reference
Ns3WimaxManagementConnectionsTestCase Class Reference
WiMAX Models » wimax module tests | Test suites
Test if the management connections are correctly setup. Create a network with a BS and 10 SS and check that the management connections are correctly setup for all SS.
Public Member Functions
Ns3WimaxManagementConnectionsTestCase ()
virtual ~Ns3WimaxManagementConnectionsTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test if the management connections are correctly setup. Create a network with a BS and 10 SS and check that the management connections are correctly setup for all SS.
Definition at line 100 of file ss-mac-test.cc.
Constructor & Destructor Documentation
Ns3WimaxManagementConnectionsTestCase()
Ns3WimaxManagementConnectionsTestCase::Ns3WimaxManagementConnectionsTestCase ()
Definition at line 111 of file ss-mac-test.cc.
~Ns3WimaxManagementConnectionsTestCase()
Ns3WimaxManagementConnectionsTestCase::~Ns3WimaxManagementConnectionsTestCase () virtual
Definition at line 116 of file ss-mac-test.cc.
Member Function Documentation
DoRun()
void Ns3WimaxManagementConnectionsTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 121 of file ss-mac-test.cc.
References ns3::NodeContainer::Create(), ns3::NetDeviceContainer::Get(), ns3::SubscriberStationNetDevice::GetAreManagementConnectionsAllocated(), ns3::WimaxHelper::Install(), NS_TEST_EXPECT_MSG_EQ, and ns3::Seconds().
The documentation for this class was generated from the following file:
src/wimax/test/ss-mac-test.cc