ns-3: ns3::MinstrelWifiManager Class Reference
ns3::MinstrelWifiManager Class Reference
Wifi Models
Implementation of Minstrel Rate Control Algorithm.
#include "minstrel-wifi-manager.h"
Public Member Functions
MinstrelWifiManager ()
virtual ~MinstrelWifiManager ()
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
void CheckInit (MinstrelWifiRemoteStation *station)
Check for initializations.
uint32_t CountRetries (MinstrelWifiRemoteStation *station)
Get the number of retries.
uint16_t FindRate (MinstrelWifiRemoteStation *station)
Find a rate to use from Minstrel Table.
WifiTxVector GetDataTxVector (MinstrelWifiRemoteStation *station)
Get data transmit vector.
WifiTxVector GetRtsTxVector (MinstrelWifiRemoteStation *station)
Get RTS transmit vector.
void InitSampleTable (MinstrelWifiRemoteStation *station)
Initialize Sample Table.
void SetupMac (const Ptr< WifiMac > mac)
Set up MAC associated with this device since it is the object that knows the full set of timing parameters (e.g.
void SetupPhy (const Ptr< WifiPhy > phy)
Set up PHY associated with this device since it is the object that knows the full set of transmit rates that are supported.
void UpdatePacketCounters (MinstrelWifiRemoteStation *station)
Update packet counters.
void UpdateRate (MinstrelWifiRemoteStation *station)
Update the rate.
void UpdateRetry (MinstrelWifiRemoteStation *station)
Update the number of retries and reset accordingly.
void UpdateStats (MinstrelWifiRemoteStation *station)
Update the Minstrel Table every 1/10 seconds.
Public Member Functions inherited from ns3::WifiRemoteStationManager
WifiRemoteStationManager ()
virtual ~WifiRemoteStationManager ()
void AddAllSupportedMcs (Mac48Address address)
Invoked in a STA or AP to store all of the MCS supported by a destination which is also supported locally.
void AddAllSupportedModes (Mac48Address address)
Invoked in a STA or AP to store all of the modes supported by a destination which is also supported locally.
void AddBasicMcs (WifiMode mcs)
Add a given Modulation and Coding Scheme (MCS) index to the set of basic MCS.
void AddBasicMode (WifiMode mode)
Invoked in a STA upon association to store the set of rates which belong to the BSSBasicRateSet of the associated AP and which are supported locally.
void AddStationHeCapabilities (Mac48Address from, HeCapabilities heCapabilities)
Records HE capabilities of the remote station.
void AddStationHtCapabilities (Mac48Address from, HtCapabilities htCapabilities)
Records HT capabilities of the remote station.
void AddStationVhtCapabilities (Mac48Address from, VhtCapabilities vhtCapabilities)
Records VHT capabilities of the remote station.
void AddSupportedErpSlotTime (Mac48Address address, bool isShortSlotTimeSupported)
Record whether the short ERP slot time is supported by the station.
void AddSupportedMcs (Mac48Address address, WifiMode mcs)
Record the MCS index supported by the station.
void AddSupportedMode (Mac48Address address, WifiMode mode)
Invoked in a STA or AP to store the set of modes supported by a destination which is also supported locally.
void AddSupportedPhyPreamble (Mac48Address address, bool isShortPreambleSupported)
Record whether the short PHY preamble is supported by the station.
WifiTxVector DoGetCtsToSelfTxVector (void)
Since CTS-to-self parameters are not dependent on the station, it is implemented in wifi remote station manager.
WifiMode GetBasicMcs (uint8_t i) const
Return the MCS at the given list index.
WifiMode GetBasicMode (uint8_t i) const
Return a basic mode from the set of basic modes.
uint16_t GetChannelWidthSupported (Mac48Address address) const
Return the channel width supported by the station.
WifiTxVector GetCtsToSelfTxVector (const WifiMacHeader *header, Ptr< const Packet > packet)
WifiTxVector GetDataTxVector (Mac48Address address, const WifiMacHeader *header, Ptr< const Packet > packet)
WifiMode GetDefaultMcs (void) const
Return the default Modulation and Coding Scheme (MCS) index.
WifiMode GetDefaultMode (void) const
Return the default transmission mode.
uint8_t GetDefaultTxPowerLevel (void) const
uint32_t GetFragmentationThreshold (void) const
Return the fragmentation threshold.
uint32_t GetFragmentOffset (Mac48Address address, const WifiMacHeader *header, Ptr< const Packet > packet, uint32_t fragmentNumber)
uint32_t GetFragmentSize (Mac48Address address, const WifiMacHeader *header, Ptr< const Packet > packet, uint32_t fragmentNumber)
bool GetGreenfieldSupported (Mac48Address address) const
Return whether the station supports Greenfield or not.
bool GetGreenfieldSupported (void) const
Return whether the device has HT Greenfield support enabled.
uint16_t GetGuardInterval (void) const
Return the supported HE guard interval duration (in nanoseconds).
bool GetHeSupported (Mac48Address address) const
Return whether the station supports HE or not.
bool GetHeSupported (void) const
Return whether the device has HE capability support enabled.
bool GetHtSupported (Mac48Address address) const
Return whether the station supports HT or not.
bool GetHtSupported (void) const
Return whether the device has HT capability support enabled.
WifiRemoteStationInfo GetInfo (Mac48Address address)
uint8_t GetMaxNumberOfTransmitStreams (void) const
uint8_t GetNBasicMcs (void) const
Return the number of basic MCS index.
uint8_t GetNBasicModes (void) const
Return the number of basic modes we support.
uint8_t GetNMcsSupported (Mac48Address address) const
Return the number of MCS supported by the station.
uint32_t GetNNonErpBasicModes (void) const
Return the number of non-ERP basic modes we support.
WifiMode GetNonErpBasicMode (uint8_t i) const
Return a basic mode from the set of basic modes that is not an ERP mode.
WifiMode GetNonUnicastMode (void) const
Return a mode for non-unicast packets.
uint8_t GetNumberOfAntennas (void) const
uint8_t GetNumberOfSupportedStreams (Mac48Address address) const
Return the number of spatial streams supported by the station.
bool GetPcfSupported (void) const
Return whether the device has PCF capability support enabled.
bool GetQosSupported (Mac48Address address) const
Return whether the given station is QoS capable.
bool GetRifsPermitted (void) const
Return whether the device can use RIFS.
WifiTxVector GetRtsTxVector (Mac48Address address, Ptr< const Packet > packet)
bool GetShortGuardIntervalSupported (Mac48Address address) const
Return whether the station supports HT/VHT short guard interval.
bool GetShortGuardIntervalSupported (void) const
Return whether the device has SGI support enabled.
bool GetShortPreambleEnabled (void) const
Return whether the device uses short PHY preambles.
bool GetShortPreambleSupported (Mac48Address address) const
Return whether the station supports short PHY preamble or not.
bool GetShortSlotTimeEnabled (void) const
Return whether the device uses short slot time.
bool GetShortSlotTimeSupported (Mac48Address address) const
Return whether the station supports short ERP slot time or not.
Ptr< const HeCapabilities > GetStationHeCapabilities (Mac48Address from)
Return the HE capabilities sent by the remote station.
Ptr< const HtCapabilities > GetStationHtCapabilities (Mac48Address from)
Return the HT capabilities sent by the remote station.
Ptr< const VhtCapabilities > GetStationVhtCapabilities (Mac48Address from)
Return the VHT capabilities sent by the remote station.
bool GetUseGreenfieldProtection (void) const
Return whether protection for stations that do not support HT Greenfield format is enabled.
bool GetUseNonErpProtection (void) const
Return whether the device supports protection of non-ERP stations.
bool GetUseNonHtProtection (void) const
Return whether the device supports protection of non-HT stations.
bool GetVhtSupported (Mac48Address address) const
Return whether the station supports VHT or not.
bool GetVhtSupported (void) const
Return whether the device has VHT capability support enabled.
bool IsAssociated (Mac48Address address) const
Return whether the station associated.
bool IsBrandNew (Mac48Address address) const
Return whether the station state is brand new.
bool IsLastFragment (Mac48Address address, const WifiMacHeader *header, Ptr< const Packet > packet, uint32_t fragmentNumber)
bool IsWaitAssocTxOk (Mac48Address address) const
Return whether we are waiting for an ACK for the association response we sent.
bool NeedCtsToSelf (WifiTxVector txVector)
Return if we need to do CTS-to-self before sending a DATA.
bool NeedFragmentation (Mac48Address address, const WifiMacHeader *header, Ptr< const Packet > packet)
bool NeedRetransmission (Mac48Address address, const WifiMacHeader *header, Ptr< const Packet > packet)
bool NeedRts (const WifiMacHeader *header, Ptr< const Packet > packet)
void PrepareForQueue (Mac48Address address, Ptr< const Packet > packet)
void RecordDisassociated (Mac48Address address)
Records that the STA was disassociated.
void RecordGotAssocTxFailed (Mac48Address address)
Records that we missed an ACK for the association response we sent.
void RecordGotAssocTxOk (Mac48Address address)
Records that we got an ACK for the association response we sent.
void RecordWaitAssocTxOk (Mac48Address address)
Records that we are waiting for an ACK for the association response we sent.
void RemoveAllSupportedMcs (Mac48Address address)
Invoked in a STA or AP to delete all of the supported MCS by a destination.
void ReportAmpduTxStatus (Mac48Address address, uint8_t nSuccessfulMpdus, uint8_t nFailedMpdus, double rxSnr, double dataSnr)
Typically called per A-MPDU, either when a Block ACK was successfully received or when a BlockAckTimeout has elapsed.
void ReportDataFailed (Mac48Address address, const WifiMacHeader *header, uint32_t packetSize)
Should be invoked whenever the AckTimeout associated to a transmission attempt expires.
void ReportDataOk (Mac48Address address, const WifiMacHeader *header, double ackSnr, WifiMode ackMode, double dataSnr, uint32_t packetSize)
Should be invoked whenever we receive the ACK associated to a data packet we just sent.
void ReportFinalDataFailed (Mac48Address address, const WifiMacHeader *header, uint32_t packetSize)
Should be invoked after calling ReportDataFailed if NeedRetransmission returns false.
void ReportFinalRtsFailed (Mac48Address address, const WifiMacHeader *header)
Should be invoked after calling ReportRtsFailed if NeedRetransmission returns false.
void ReportRtsFailed (Mac48Address address, const WifiMacHeader *header)
Should be invoked whenever the RtsTimeout associated to a transmission attempt expires.
void ReportRtsOk (Mac48Address address, const WifiMacHeader *header, double ctsSnr, WifiMode ctsMode, double rtsSnr)
Should be invoked whenever we receive the CTS associated to an RTS we just sent.
void ReportRxOk (Mac48Address address, double rxSnr, WifiMode txMode)
void Reset (void)
Reset the station, invoked in a STA upon dis-association or in an AP upon reboot.
void SetDefaultTxPowerLevel (uint8_t txPower)
Set the default transmission power level.
void SetFragmentationThreshold (uint32_t threshold)
Sets a fragmentation threshold.
void SetMaxSlrc (uint32_t maxSlrc)
Sets the maximum STA long retry count (SLRC).
void SetMaxSsrc (uint32_t maxSsrc)
Sets the maximum STA short retry count (SSRC).
void SetPcfSupported (bool enable)
Enable or disable PCF capability support.
void SetQosSupport (Mac48Address from, bool qosSupported)
Records QoS support of the remote station.
void SetRifsPermitted (bool allow)
Permit or prohibit RIFS.
void SetRtsCtsThreshold (uint32_t threshold)
Sets the RTS threshold.
void SetShortPreambleEnabled (bool enable)
Enable or disable short PHY preambles.
void SetShortSlotTimeEnabled (bool enable)
Enable or disable short slot time.
void SetUseGreenfieldProtection (bool enable)
Enable or disable protection for stations that do not support HT Greenfield format.
void SetUseNonErpProtection (bool enable)
Enable or disable protection for non-ERP stations.
void SetUseNonHtProtection (bool enable)
Enable or disable protection for non-HT stations.
void UpdateFragmentationThreshold (void)
Typically called to update the fragmentation threshold at the start of a new transmission.
bool UseGreenfieldForDestination (Mac48Address dest) const
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::WifiRemoteStationManager
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef std::map< WifiMode, Time > TxTime
typedef for a vector of a pair of Time, WifiMode.
Private Member Functions
void AddCalcTxTime (WifiMode mode, Time t)
Add transmission time for the given mode to an internal list.
Time CalculateTimeUnicastPacket (Time dataTransmissionTime, uint32_t shortRetries, uint32_t longRetries)
Estimate the time to transmit the given packet with the given number of retries.
WifiRemoteStation * DoCreateStation (void) const
WifiTxVector DoGetDataTxVector (WifiRemoteStation *station)
WifiTxVector DoGetRtsTxVector (WifiRemoteStation *station)
void DoInitialize (void)
Initialize() implementation.
bool DoNeedRetransmission (WifiRemoteStation *st, Ptr< const Packet > packet, bool normally)
void DoReportDataFailed (WifiRemoteStation *station)
This method is a pure virtual method that must be implemented by the sub-class.
void DoReportDataOk (WifiRemoteStation *station, double ackSnr, WifiMode ackMode, double dataSnr)
This method is a pure virtual method that must be implemented by the sub-class.
void DoReportFinalDataFailed (WifiRemoteStation *station)
This method is a pure virtual method that must be implemented by the sub-class.
void DoReportFinalRtsFailed (WifiRemoteStation *station)
This method is a pure virtual method that must be implemented by the sub-class.
void DoReportRtsFailed (WifiRemoteStation *station)
This method is a pure virtual method that must be implemented by the sub-class.
void DoReportRtsOk (WifiRemoteStation *station, double ctsSnr, WifiMode ctsMode, double rtsSnr)
This method is a pure virtual method that must be implemented by the sub-class.
void DoReportRxOk (WifiRemoteStation *station, double rxSnr, WifiMode txMode)
This method is a pure virtual method that must be implemented by the sub-class.
Time GetCalcTxTime (WifiMode mode) const
Estimate the TxTime of a packet with a given mode.
uint16_t GetNextSample (MinstrelWifiRemoteStation *station)
Get the next sample from Sample Table.
bool IsLowLatency (void) const
void PrintSampleTable (MinstrelWifiRemoteStation *station)
Print Sample Table.
void PrintTable (MinstrelWifiRemoteStation *station)
Print Minstrel Table.
void RateInit (MinstrelWifiRemoteStation *station)
Initialize Minstrel Table.
Private Attributes
TxTime m_calcTxTime
to hold all the calculated TxTime for all modes
TracedValue< uint64_t > m_currentRate
Trace rate changes.
uint8_t m_ewmaLevel
exponential weighted moving average
uint8_t m_lookAroundRate
the % to try other rates than our current rate
uint32_t m_pktLen
packet length used for calculate mode TxTime
bool m_printSamples
whether samples table should be printed.
bool m_printStats
whether statistics table should be printed.
uint8_t m_sampleCol
number of sample columns
Ptr< UniformRandomVariable > m_uniformRandomVariable
Provides uniform random variables.
Time m_updateStats
how frequent do we calculate the stats (1/10 seconds)
Additional Inherited Members
Public Types inherited from ns3::WifiRemoteStationManager
typedef void(* PowerChangeTracedCallback) (double oldPower, double newPower, Mac48Address remoteAddress)
TracedCallback signature for power change events.
enum ProtectionMode { RTS_CTS, CTS_TO_SELF }
ProtectionMode enumeration.
typedef void(* RateChangeTracedCallback) (DataRate oldRate, DataRate newRate, Mac48Address remoteAddress)
TracedCallback signature for rate change events.
typedef std::vector< WifiRemoteStation * > Stations
A vector of WifiRemoteStations.
typedef std::vector< WifiRemoteStationState * > StationStates
A vector of WifiRemoteStationStates.
Protected Member Functions inherited from ns3::WifiRemoteStationManager
virtual void DoDispose (void)
Destructor implementation.
Mac48Address GetAddress (const WifiRemoteStation *station) const
Return the address of the station.
bool GetAggregation (const WifiRemoteStation *station) const
Return whether the given station supports A-MPDU.
uint16_t GetChannelWidth (const WifiRemoteStation *station) const
Return the channel width supported by the station.
bool GetGreenfield (const WifiRemoteStation *station) const
Return whether the station supports Greenfield or not.
uint16_t GetGuardInterval (const WifiRemoteStation *station) const
Return the HE guard interval duration supported by the station.
bool GetHeSupported (const WifiRemoteStation *station) const
Return whether the given station is HE capable.
bool GetHtSupported (const WifiRemoteStation *station) const
Return whether the given station is HT capable.
Ptr< WifiMac > GetMac (void) const
Return the WifiMac.
WifiMode GetMcsSupported (const WifiRemoteStation *station, uint8_t i) const
Return the WifiMode supported by the specified station at the specified index.
uint8_t GetNess (const WifiRemoteStation *station) const
uint8_t GetNMcsSupported (const WifiRemoteStation *station) const
Return the number of MCS supported by the given station.
uint32_t GetNNonErpSupported (const WifiRemoteStation *station) const
Return the number of non-ERP modes supported by the given station.
WifiMode GetNonErpSupported (const WifiRemoteStation *station, uint8_t i) const
Return whether non-ERP mode associated with the specified station at the specified index.
uint8_t GetNSupported (const WifiRemoteStation *station) const
Return the number of modes supported by the given station.
uint8_t GetNumberOfSupportedStreams (const WifiRemoteStation *station) const
Return the number of supported streams the station has.
Ptr< WifiPhy > GetPhy (void) const
Return the WifiPhy.
bool GetQosSupported (const WifiRemoteStation *station) const
Return whether the given station is QoS capable.
bool GetShortGuardIntervalSupported (const WifiRemoteStation *station) const
Return whether the given station supports HT/VHT short guard interval.
WifiMode GetSupported (const WifiRemoteStation *station, uint8_t i) const
Return whether mode associated with the specified station at the specified index.
bool GetVhtSupported (const WifiRemoteStation *station) const
Return whether the given station is VHT capable.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implementation of Minstrel Rate Control Algorithm.
Minstrel is a rate control algorithm implemented in MadWifi and Linux. The basic principle is to probe the environment and adapt the rate based on statistics collected on the probability of successful transmission. The algorithm adapts the rate to the highest rate that it considers successful, and spends a fraction of its time doing 'look around' by trying other rates.
Minstrel is appropriate for non-HT configurations; for HT (i.e. 802.11n or higher), users should use MinstrelHtWifiManager instead. Minstrel will error exit if the user tries to configure it with a Wi-Fi MAC that supports 802.11n or higher.
Some notes on this implementation follow. The implementation has been adapted to bring it closer to the Linux implementation. For each rate, a new parameter samplesSkipped is added. This parameter is intended to solve an issue regarding the sampling of low rates when a high rate is working well, which leads to outdated statistics. This change makes throughput a bit lower in simple, stable scenarios, but may help in dynamic scenarios to react faster and more accurately to changes.
Related to the previous, the logic for deciding when to sample random rates is as follows. When a sample rate is deferred to the second MRR chain stage, a new parameter (numSamplesDeferred) is increased. This parameters is used (jointly with sampleCount) to compare current sample count with the lookaround rate.
Also related with sampling, another parameter sampleLimit is added. This parameter limits the number of times a very low or very high probability rate is sampled, avoiding to try a poorly working sample rate too often.
When updating the EWMA probability of a rate for the first time, it does not apply EWMA but instead assigns the entire probability. Since the EWMA probability is initialized to zero, this generates a more accurate EWMA.
Definition at line 157 of file minstrel-wifi-manager.h.
Member Typedef Documentation
TxTime
typedef std::map<WifiMode, Time> ns3::MinstrelWifiManager::TxTime private
typedef for a vector of a pair of Time, WifiMode.
Essentially a map from WifiMode to its corresponding transmission time to transmit a reference packet.
Definition at line 351 of file minstrel-wifi-manager.h.
Constructor & Destructor Documentation
MinstrelWifiManager()
ns3::MinstrelWifiManager::MinstrelWifiManager ()
Definition at line 99 of file minstrel-wifi-manager.cc.
References m_uniformRandomVariable, and NS_LOG_FUNCTION.
~MinstrelWifiManager()
ns3::MinstrelWifiManager::~MinstrelWifiManager () virtual
Definition at line 107 of file minstrel-wifi-manager.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddCalcTxTime()
void ns3::MinstrelWifiManager::AddCalcTxTime (WifiMode mode, Time t) private
Add transmission time for the given mode to an internal list.
Parameters
mode Wi-Fi mode
t transmission time
Definition at line 171 of file minstrel-wifi-manager.cc.
References m_calcTxTime, and NS_LOG_FUNCTION.
Referenced by SetupPhy().
AssignStreams()
int64_t ns3::MinstrelWifiManager::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 154 of file minstrel-wifi-manager.cc.
References m_uniformRandomVariable, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
CalculateTimeUnicastPacket()
Time ns3::MinstrelWifiManager::CalculateTimeUnicastPacket (Time dataTransmissionTime, uint32_t shortRetries, uint32_t longRetries) private
Estimate the time to transmit the given packet with the given number of retries.
This function is "roughly" the function "calc_usecs_unicast_packet" in minstrel.c in the madwifi implementation.
The basic idea is that, we try to estimate the "average" time used to transmit the packet for the given number of retries while also accounting for the 802.11 congestion window change. The original code in the madwifi seems to estimate the number of backoff slots as the half of the current CW size.
There are four main parts:
wait for DIFS (sense idle channel)
Ack timeouts
Data transmission
backoffs according to CW
Parameters
dataTransmissionTime the data transmission time
shortRetries short retries
longRetries long retries
Returns
the unicast packet time
Definition at line 965 of file minstrel-wifi-manager.cc.
References ns3::WifiRemoteStationManager::GetMac(), min, and NS_LOG_FUNCTION.
Referenced by RateInit().
CheckInit()
void ns3::MinstrelWifiManager::CheckInit (MinstrelWifiRemoteStation * station)
Check for initializations.
Parameters
station the station object
Definition at line 205 of file minstrel-wifi-manager.cc.
References ns3::WifiRemoteStationManager::GetNSupported(), InitSampleTable(), ns3::MinstrelWifiRemoteStation::m_initialized, ns3::MinstrelWifiRemoteStation::m_minstrelTable, ns3::MinstrelWifiRemoteStation::m_nModes, m_sampleCol, ns3::MinstrelWifiRemoteStation::m_sampleTable, NS_LOG_FUNCTION, and RateInit().
Referenced by DoNeedRetransmission(), DoReportDataFailed(), DoReportDataOk(), DoReportFinalDataFailed(), and GetDataTxVector().
CountRetries()
uint32_t ns3::MinstrelWifiManager::CountRetries (MinstrelWifiRemoteStation * station)
Get the number of retries.
Parameters
station the station object
Returns
the number of retries
Definition at line 412 of file minstrel-wifi-manager.cc.
References ns3::MinstrelWifiRemoteStation::m_isSampling, ns3::MinstrelWifiRemoteStation::m_maxProbRate, ns3::MinstrelWifiRemoteStation::m_maxTpRate, ns3::MinstrelWifiRemoteStation::m_maxTpRate2, ns3::MinstrelWifiRemoteStation::m_minstrelTable, and ns3::MinstrelWifiRemoteStation::m_sampleRate.
Referenced by DoNeedRetransmission().
DoCreateStation()
WifiRemoteStation * ns3::MinstrelWifiManager::DoCreateStation (void) const private virtual
Returns
a new station data structure
Implements ns3::WifiRemoteStationManager.
Definition at line 178 of file minstrel-wifi-manager.cc.
References ns3::MinstrelWifiRemoteStation::m_col, ns3::MinstrelWifiRemoteStation::m_index, ns3::MinstrelWifiRemoteStation::m_initialized, ns3::MinstrelWifiRemoteStation::m_isSampling, ns3::MinstrelWifiRemoteStation::m_longRetry, ns3::MinstrelWifiRemoteStation::m_maxProbRate, ns3::MinstrelWifiRemoteStation::m_maxTpRate, ns3::MinstrelWifiRemoteStation::m_maxTpRate2, ns3::MinstrelWifiRemoteStation::m_nextStatsUpdate, ns3::MinstrelWifiRemoteStation::m_nModes, ns3::MinstrelWifiRemoteStation::m_retry, ns3::MinstrelWifiRemoteStation::m_sampleDeferred, ns3::MinstrelWifiRemoteStation::m_samplePacketsCount, ns3::MinstrelWifiRemoteStation::m_sampleRate, ns3::MinstrelWifiRemoteStation::m_shortRetry, ns3::MinstrelWifiRemoteStation::m_totalPacketsCount, ns3::MinstrelWifiRemoteStation::m_txrate, m_updateStats, ns3::Simulator::Now(), and NS_LOG_FUNCTION.
DoGetDataTxVector()
WifiTxVector ns3::MinstrelWifiManager::DoGetDataTxVector (WifiRemoteStation * station) private virtual
Parameters
station the station that we need to communicate
Returns
the TXVECTOR to use to send a packet to the station
Note: This method is called before sending a unicast packet or a fragment of a unicast packet to decide which transmission mode to use.
Implements ns3::WifiRemoteStationManager.
Definition at line 855 of file minstrel-wifi-manager.cc.
References GetDataTxVector(), and NS_LOG_FUNCTION.
DoGetRtsTxVector()
WifiTxVector ns3::MinstrelWifiManager::DoGetRtsTxVector (WifiRemoteStation * station) private virtual
Parameters
station the station that we need to communicate
Returns
the transmission mode to use to send an RTS to the station
Note: This method is called before sending an RTS to a station to decide which transmission mode to use for the RTS.
Implements ns3::WifiRemoteStationManager.
Definition at line 863 of file minstrel-wifi-manager.cc.
References GetRtsTxVector(), and NS_LOG_FUNCTION.
DoInitialize()
void ns3::MinstrelWifiManager::DoInitialize (void) private virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 136 of file minstrel-wifi-manager.cc.
References ns3::WifiRemoteStationManager::GetHeSupported(), ns3::WifiRemoteStationManager::GetHtSupported(), ns3::WifiRemoteStationManager::GetVhtSupported(), NS_FATAL_ERROR, and NS_LOG_FUNCTION.
DoNeedRetransmission()
bool ns3::MinstrelWifiManager::DoNeedRetransmission (WifiRemoteStation * station, Ptr< const Packet > packet, bool normally) private virtual
Parameters
station the station that we need to communicate
packet the packet to send
normally indicates whether the normal 802.11 data retransmission mechanism would request that the data is retransmitted or not.
Returns
true if we want to resend a packet after a failed transmission attempt, false otherwise.
Note: This method is called after any unicast packet transmission (control, management, or data) has been attempted and has failed.
Reimplemented from ns3::WifiRemoteStationManager.
Definition at line 871 of file minstrel-wifi-manager.cc.
References CheckInit(), CountRetries(), ns3::MinstrelWifiRemoteStation::m_initialized, ns3::MinstrelWifiRemoteStation::m_longRetry, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
DoReportDataFailed()
void ns3::MinstrelWifiManager::DoReportDataFailed (WifiRemoteStation * station) private virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that we failed to send DATA
Implements ns3::WifiRemoteStationManager.
Definition at line 744 of file minstrel-wifi-manager.cc.
References CheckInit(), ns3::MinstrelWifiRemoteStation::m_initialized, ns3::MinstrelWifiRemoteStation::m_longRetry, ns3::MinstrelWifiRemoteStation::m_txrate, NS_LOG_DEBUG, NS_LOG_FUNCTION, and UpdateRate().
DoReportDataOk()
void ns3::MinstrelWifiManager::DoReportDataOk (WifiRemoteStation * station, double ackSnr, WifiMode ackMode, double dataSnr) private virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that we successfully sent RTS
ackSnr the SNR of the ACK we received
ackMode the WifiMode the receiver used to send the ACK
dataSnr the SNR of the DATA we sent
Implements ns3::WifiRemoteStationManager.
Definition at line 759 of file minstrel-wifi-manager.cc.
References CheckInit(), FindRate(), ns3::MinstrelWifiRemoteStation::m_initialized, ns3::MinstrelWifiRemoteStation::m_minstrelTable, ns3::MinstrelWifiRemoteStation::m_nModes, ns3::MinstrelWifiRemoteStation::m_txrate, NS_LOG_DEBUG, NS_LOG_FUNCTION, UpdatePacketCounters(), UpdateRetry(), and UpdateStats().
DoReportFinalDataFailed()
void ns3::MinstrelWifiManager::DoReportFinalDataFailed (WifiRemoteStation * station) private virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that we failed to send DATA
Implements ns3::WifiRemoteStationManager.
Definition at line 791 of file minstrel-wifi-manager.cc.
References CheckInit(), FindRate(), ns3::MinstrelWifiRemoteStation::m_initialized, ns3::MinstrelWifiRemoteStation::m_minstrelTable, ns3::MinstrelWifiRemoteStation::m_nModes, ns3::MinstrelWifiRemoteStation::m_txrate, NS_LOG_DEBUG, NS_LOG_FUNCTION, UpdatePacketCounters(), UpdateRetry(), and UpdateStats().
DoReportFinalRtsFailed()
void ns3::MinstrelWifiManager::DoReportFinalRtsFailed (WifiRemoteStation * station) private virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that we failed to send RTS
Implements ns3::WifiRemoteStationManager.
Definition at line 736 of file minstrel-wifi-manager.cc.
References NS_LOG_FUNCTION, and UpdateRetry().
DoReportRtsFailed()
void ns3::MinstrelWifiManager::DoReportRtsFailed (WifiRemoteStation * station) private virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that we failed to send RTS
Implements ns3::WifiRemoteStationManager.
Definition at line 721 of file minstrel-wifi-manager.cc.
References ns3::MinstrelWifiRemoteStation::m_shortRetry, ns3::MinstrelWifiRemoteStation::m_txrate, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
DoReportRtsOk()
void ns3::MinstrelWifiManager::DoReportRtsOk (WifiRemoteStation * station, double ctsSnr, WifiMode ctsMode, double rtsSnr) private virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that we successfully sent RTS
ctsSnr the SNR of the CTS we received
ctsMode the WifiMode the receiver used to send the CTS
rtsSnr the SNR of the RTS we sent
Implements ns3::WifiRemoteStationManager.
Definition at line 730 of file minstrel-wifi-manager.cc.
References NS_LOG_FUNCTION.
DoReportRxOk()
void ns3::MinstrelWifiManager::DoReportRxOk (WifiRemoteStation * station, double rxSnr, WifiMode txMode) private virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that sent the DATA to us
rxSnr the SNR of the DATA we received
txMode the WifiMode the sender used to send the DATA
Implements ns3::WifiRemoteStationManager.
Definition at line 714 of file minstrel-wifi-manager.cc.
References NS_LOG_DEBUG, and NS_LOG_FUNCTION.
FindRate()
uint16_t ns3::MinstrelWifiManager::FindRate (MinstrelWifiRemoteStation * station)
Find a rate to use from Minstrel Table.
Parameters
station the station object
Returns
the rate in bps
Definition at line 431 of file minstrel-wifi-manager.cc.
References GetNextSample(), ns3::WifiRemoteStationManager::GetSupported(), ns3::MinstrelWifiRemoteStation::m_isSampling, m_lookAroundRate, ns3::MinstrelWifiRemoteStation::m_maxTpRate, ns3::MinstrelWifiRemoteStation::m_minstrelTable, ns3::MinstrelWifiRemoteStation::m_nModes, ns3::MinstrelWifiRemoteStation::m_numSamplesDeferred, ns3::MinstrelWifiRemoteStation::m_sampleDeferred, ns3::MinstrelWifiRemoteStation::m_samplePacketsCount, ns3::MinstrelWifiRemoteStation::m_sampleRate, ns3::MinstrelWifiRemoteStation::m_totalPacketsCount, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by DoReportDataOk(), and DoReportFinalDataFailed().
GetCalcTxTime()
Time ns3::MinstrelWifiManager::GetCalcTxTime (WifiMode mode) const private
Estimate the TxTime of a packet with a given mode.
Parameters
mode Wi-Fi mode
Returns
the transmission time
Definition at line 162 of file minstrel-wifi-manager.cc.
References m_calcTxTime, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by RateInit().
GetDataTxVector()
WifiTxVector ns3::MinstrelWifiManager::GetDataTxVector (MinstrelWifiRemoteStation * station)
Get data transmit vector.
Parameters
station the station object
Returns
WifiTxVector
Definition at line 366 of file minstrel-wifi-manager.cc.
References CheckInit(), ns3::WifiRemoteStationManager::GetAddress(), ns3::WifiRemoteStationManager::GetAggregation(), ns3::WifiRemoteStationManager::GetChannelWidth(), ns3::WifiMode::GetDataRate(), ns3::WifiRemoteStationManager::GetDefaultTxPowerLevel(), ns3::WifiMode::GetModulationClass(), ns3::GetPreambleForTransmission(), ns3::WifiRemoteStationManager::GetShortPreambleEnabled(), ns3::WifiRemoteStationManager::GetSupported(), m_currentRate, ns3::MinstrelWifiRemoteStation::m_initialized, ns3::MinstrelWifiRemoteStation::m_isSampling, ns3::MinstrelWifiRemoteStation::m_txrate, NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::WifiRemoteStationManager::UseGreenfieldForDestination().
Referenced by DoGetDataTxVector().
GetNextSample()
uint16_t ns3::MinstrelWifiManager::GetNextSample (MinstrelWifiRemoteStation * station) private
Get the next sample from Sample Table.
Parameters
station the station object
Returns
the next sample
Definition at line 900 of file minstrel-wifi-manager.cc.
References ns3::MinstrelWifiRemoteStation::m_col, ns3::MinstrelWifiRemoteStation::m_index, ns3::MinstrelWifiRemoteStation::m_nModes, m_sampleCol, ns3::MinstrelWifiRemoteStation::m_sampleTable, NS_ABORT_MSG_IF, and NS_LOG_FUNCTION.
Referenced by FindRate().
GetRtsTxVector()
WifiTxVector ns3::MinstrelWifiManager::GetRtsTxVector (MinstrelWifiRemoteStation * station)
Get RTS transmit vector.
Parameters
station the station object
Returns
WifiTxVector
Definition at line 388 of file minstrel-wifi-manager.cc.
References ns3::WifiRemoteStationManager::GetAddress(), ns3::WifiRemoteStationManager::GetAggregation(), ns3::WifiRemoteStationManager::GetChannelWidth(), ns3::WifiRemoteStationManager::GetDefaultTxPowerLevel(), ns3::WifiMode::GetModulationClass(), ns3::WifiRemoteStationManager::GetNonErpSupported(), ns3::GetPreambleForTransmission(), ns3::WifiRemoteStationManager::GetShortPreambleEnabled(), ns3::WifiRemoteStationManager::GetSupported(), ns3::WifiRemoteStationManager::GetUseNonErpProtection(), ns3::MinstrelWifiRemoteStation::m_txrate, NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::WifiRemoteStationManager::UseGreenfieldForDestination().
Referenced by DoGetRtsTxVector().
GetTypeId()
TypeId ns3::MinstrelWifiManager::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 50 of file minstrel-wifi-manager.cc.
References m_currentRate, m_ewmaLevel, m_lookAroundRate, m_pktLen, m_printSamples, m_printStats, m_sampleCol, m_updateStats, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), ns3::Seconds(), and ns3::TypeId::SetParent().
InitSampleTable()
void ns3::MinstrelWifiManager::InitSampleTable (MinstrelWifiRemoteStation * station)
Initialize Sample Table.
Parameters
station the station object
The next two lines basically tries to generate a random number between 0 and the number of available rates
Definition at line 991 of file minstrel-wifi-manager.cc.
References ns3::UniformRandomVariable::GetInteger(), ns3::MinstrelWifiRemoteStation::m_col, ns3::MinstrelWifiRemoteStation::m_index, ns3::MinstrelWifiRemoteStation::m_nModes, m_sampleCol, ns3::MinstrelWifiRemoteStation::m_sampleTable, m_uniformRandomVariable, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by CheckInit().
IsLowLatency()
bool ns3::MinstrelWifiManager::IsLowLatency (void) const private virtual
Returns
whether this manager is a manager designed to work in low-latency environments.
Note: In this context, low vs high latency is defined in IEEE 802.11 Rate Adaptation: A Practical Approach, by M. Lacage, M.H. Manshaei, and T. Turletti.
Implements ns3::WifiRemoteStationManager.
Definition at line 894 of file minstrel-wifi-manager.cc.
PrintSampleTable()
void ns3::MinstrelWifiManager::PrintSampleTable (MinstrelWifiRemoteStation * station) private
Print Sample Table.
Parameters
station the station object
Definition at line 1023 of file minstrel-wifi-manager.cc.
References ns3::MinstrelWifiRemoteStation::m_nModes, m_sampleCol, ns3::MinstrelWifiRemoteStation::m_sampleTable, and NS_LOG_DEBUG.
Referenced by UpdateStats().
PrintTable()
void ns3::MinstrelWifiManager::PrintTable (MinstrelWifiRemoteStation * station) private
Print Minstrel Table.
Parameters
station the station object
Definition at line 1039 of file minstrel-wifi-manager.cc.
References ns3::RateInfo::adjustedRetryCount, ns3::RateInfo::attemptHist, ns3::RateInfo::ewmaProb, ns3::Time::GetMicroSeconds(), ns3::WifiRemoteStationManager::GetSupported(), ns3::WifiRemoteStationState::m_address, ns3::MinstrelWifiRemoteStation::m_maxProbRate, ns3::MinstrelWifiRemoteStation::m_maxTpRate, ns3::MinstrelWifiRemoteStation::m_maxTpRate2, ns3::MinstrelWifiRemoteStation::m_minstrelTable, ns3::MinstrelWifiRemoteStation::m_nModes, ns3::MinstrelWifiRemoteStation::m_samplePacketsCount, ns3::WifiRemoteStation::m_state, ns3::MinstrelWifiRemoteStation::m_statsFile, ns3::MinstrelWifiRemoteStation::m_totalPacketsCount, ns3::RateInfo::perfectTxTime, ns3::RateInfo::prevNumRateAttempt, ns3::RateInfo::prevNumRateSuccess, ns3::RateInfo::prob, ns3::RateInfo::successHist, and ns3::RateInfo::throughput.
Referenced by UpdateStats().
RateInit()
void ns3::MinstrelWifiManager::RateInit (MinstrelWifiRemoteStation * station) private
Initialize Minstrel Table.
Parameters
station the station object
Definition at line 922 of file minstrel-wifi-manager.cc.
References CalculateTimeUnicastPacket(), GetCalcTxTime(), ns3::WifiRemoteStationManager::GetSupported(), ns3::MinstrelWifiRemoteStation::m_minstrelTable, ns3::MinstrelWifiRemoteStation::m_nModes, ns3::MilliSeconds(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Seconds(), and UpdateStats().
Referenced by CheckInit().
SetupMac()
void ns3::MinstrelWifiManager::SetupMac (const Ptr< WifiMac > mac) virtual
Set up MAC associated with this device since it is the object that knows the full set of timing parameters (e.g.
IFS).
Parameters
mac the MAC of this device
Reimplemented from ns3::WifiRemoteStationManager.
Definition at line 129 of file minstrel-wifi-manager.cc.
References third::mac, NS_LOG_FUNCTION, and ns3::WifiRemoteStationManager::SetupMac().
SetupPhy()
void ns3::MinstrelWifiManager::SetupPhy (const Ptr< WifiPhy > phy) virtual
Set up PHY associated with this device since it is the object that knows the full set of transmit rates that are supported.
Parameters
phy the PHY of this device
Reimplemented from ns3::WifiRemoteStationManager.
Definition at line 113 of file minstrel-wifi-manager.cc.
References AddCalcTxTime(), m_pktLen, NS_LOG_FUNCTION, third::phy, ns3::WifiTxVector::SetMode(), ns3::WifiTxVector::SetPreambleType(), ns3::WifiRemoteStationManager::SetupPhy(), and ns3::WIFI_PREAMBLE_LONG.
UpdatePacketCounters()
void ns3::MinstrelWifiManager::UpdatePacketCounters (MinstrelWifiRemoteStation * station)
Update packet counters.
Parameters
station the station object
Definition at line 819 of file minstrel-wifi-manager.cc.
References ns3::MinstrelWifiRemoteStation::m_isSampling, ns3::MinstrelWifiRemoteStation::m_longRetry, ns3::MinstrelWifiRemoteStation::m_maxTpRate, ns3::MinstrelWifiRemoteStation::m_minstrelTable, ns3::MinstrelWifiRemoteStation::m_numSamplesDeferred, ns3::MinstrelWifiRemoteStation::m_sampleDeferred, ns3::MinstrelWifiRemoteStation::m_samplePacketsCount, ns3::MinstrelWifiRemoteStation::m_totalPacketsCount, and NS_LOG_FUNCTION.
Referenced by DoReportDataOk(), and DoReportFinalDataFailed().
UpdateRate()
void ns3::MinstrelWifiManager::UpdateRate (MinstrelWifiRemoteStation * station)
Update the rate.
Retry Chain table is implemented here.
Parameters
station the station object
Try | LOOKAROUND RATE | NORMAL RATE
| random < best | random > best |
1 | Best throughput | Random rate | Best throughput 2 | Random rate | Best throughput | Next best throughput 3 | Best probability | Best probability | Best probability 4 | Lowest base rate | Lowest base rate | Lowest base rate
Note: For clarity, multiple blocks of if's and else's are used After failing max retry times, DoReportFinalDataFailed will be called
Definition at line 238 of file minstrel-wifi-manager.cc.
References ns3::MinstrelWifiRemoteStation::m_isSampling, ns3::MinstrelWifiRemoteStation::m_longRetry, ns3::MinstrelWifiRemoteStation::m_maxProbRate, ns3::MinstrelWifiRemoteStation::m_maxTpRate, ns3::MinstrelWifiRemoteStation::m_maxTpRate2, ns3::MinstrelWifiRemoteStation::m_minstrelTable, ns3::MinstrelWifiRemoteStation::m_sampleDeferred, ns3::MinstrelWifiRemoteStation::m_sampleRate, ns3::MinstrelWifiRemoteStation::m_txrate, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by DoReportDataFailed().
UpdateRetry()
void ns3::MinstrelWifiManager::UpdateRetry (MinstrelWifiRemoteStation * station)
Update the number of retries and reset accordingly.
Parameters
station the station object
Definition at line 846 of file minstrel-wifi-manager.cc.
References ns3::MinstrelWifiRemoteStation::m_longRetry, ns3::MinstrelWifiRemoteStation::m_retry, ns3::MinstrelWifiRemoteStation::m_shortRetry, and NS_LOG_FUNCTION.
Referenced by DoReportDataOk(), DoReportFinalDataFailed(), and DoReportFinalRtsFailed().
UpdateStats()
void ns3::MinstrelWifiManager::UpdateStats (MinstrelWifiRemoteStation * station)
Update the Minstrel Table every 1/10 seconds.
Parameters
station the station object
calculate the probability of success assume probability scales from 0 to 18000
See: http://wireless.kernel.org/en/developers/Documentation/mac80211/RateControl/minstrel/
Analysis of information showed that the system was sampling too hard at some rates. For those rates that never work (54mb, 500m range) there is no point in retrying 10 sample packets (< 6 ms time). Consequently, for the very low probability rates, we try at most twice when fails and not sample more than 4 times.
Definition at line 535 of file minstrel-wifi-manager.cc.
References ns3::Time::GetMicroSeconds(), ns3::WifiRemoteStationManager::GetSupported(), ns3::if(), m_ewmaLevel, ns3::MinstrelWifiRemoteStation::m_initialized, ns3::MinstrelWifiRemoteStation::m_maxProbRate, ns3::MinstrelWifiRemoteStation::m_maxTpRate, ns3::MinstrelWifiRemoteStation::m_maxTpRate2, ns3::MinstrelWifiRemoteStation::m_minstrelTable, ns3::MinstrelWifiRemoteStation::m_nextStatsUpdate, ns3::MinstrelWifiRemoteStation::m_nModes, m_printSamples, m_printStats, ns3::MinstrelWifiRemoteStation::m_txrate, m_updateStats, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, PrintSampleTable(), PrintTable(), and ns3::Seconds().
Referenced by DoReportDataOk(), DoReportFinalDataFailed(), and RateInit().
Member Data Documentation
m_calcTxTime
TxTime ns3::MinstrelWifiManager::m_calcTxTime private
to hold all the calculated TxTime for all modes
Definition at line 353 of file minstrel-wifi-manager.h.
Referenced by AddCalcTxTime(), and GetCalcTxTime().
m_currentRate
TracedValue<uint64_t> ns3::MinstrelWifiManager::m_currentRate private
Trace rate changes.
Definition at line 365 of file minstrel-wifi-manager.h.
Referenced by GetDataTxVector(), and GetTypeId().
m_ewmaLevel
uint8_t ns3::MinstrelWifiManager::m_ewmaLevel private
exponential weighted moving average
Definition at line 356 of file minstrel-wifi-manager.h.
Referenced by GetTypeId(), and UpdateStats().
m_lookAroundRate
uint8_t ns3::MinstrelWifiManager::m_lookAroundRate private
the % to try other rates than our current rate
Definition at line 355 of file minstrel-wifi-manager.h.
Referenced by FindRate(), and GetTypeId().
m_pktLen
uint32_t ns3::MinstrelWifiManager::m_pktLen private
packet length used for calculate mode TxTime
Definition at line 358 of file minstrel-wifi-manager.h.
Referenced by GetTypeId(), and SetupPhy().
m_printSamples
bool ns3::MinstrelWifiManager::m_printSamples private
whether samples table should be printed.
Definition at line 360 of file minstrel-wifi-manager.h.
Referenced by GetTypeId(), and UpdateStats().
m_printStats
bool ns3::MinstrelWifiManager::m_printStats private
whether statistics table should be printed.
Definition at line 359 of file minstrel-wifi-manager.h.
Referenced by GetTypeId(), and UpdateStats().
m_sampleCol
uint8_t ns3::MinstrelWifiManager::m_sampleCol private
number of sample columns
Definition at line 357 of file minstrel-wifi-manager.h.
Referenced by CheckInit(), GetNextSample(), GetTypeId(), InitSampleTable(), and PrintSampleTable().
m_uniformRandomVariable
Ptr<UniformRandomVariable> ns3::MinstrelWifiManager::m_uniformRandomVariable private
Provides uniform random variables.
Definition at line 363 of file minstrel-wifi-manager.h.
Referenced by MinstrelWifiManager(), AssignStreams(), and InitSampleTable().
m_updateStats
Time ns3::MinstrelWifiManager::m_updateStats private
how frequent do we calculate the stats (1/10 seconds)
Definition at line 354 of file minstrel-wifi-manager.h.
Referenced by DoCreateStation(), GetTypeId(), and UpdateStats().
The documentation for this class was generated from the following files:
src/wifi/model/minstrel-wifi-manager.h
src/wifi/model/minstrel-wifi-manager.cc