ns-3: ns3::CsParameters Class Reference
ns3::CsParameters Class Reference
WiMAX Models
CsParameters class.
#include "cs-parameters.h"
Public Types
enum Action { ADD = 0, REPLACE = 1, DELETE = 2 }
Action enumeration.
Public Member Functions
CsParameters ()
CsParameters (enum Action classifierDscAction, IpcsClassifierRecord classifier)
creates a convergence sub-layer parameters from an ipcs classifier record
CsParameters (Tlv tlv)
creates a convergence sub-layer parameters from a tlv
~CsParameters ()
enum Action GetClassifierDscAction (void) const
IpcsClassifierRecord GetPacketClassifierRule (void) const
void SetClassifierDscAction (enum Action action)
sets the dynamic service classifier action to ADD, Change or delete.
void SetPacketClassifierRule (IpcsClassifierRecord packetClassifierRule)
sets the packet classifier rules
Tlv ToTlv (void) const
creates a tlv from the classifier record
Private Attributes
enum Action m_classifierDscAction
classifier DSC action
IpcsClassifierRecord m_packetClassifierRule
packet classifier rule
Detailed Description
CsParameters class.
Definition at line 35 of file cs-parameters.h.
Member Enumeration Documentation
Action
enum ns3::CsParameters::Action
Action enumeration.
Enumerator
ADD
REPLACE
DELETE
Definition at line 39 of file cs-parameters.h.
Constructor & Destructor Documentation
CsParameters() [1/3]
ns3::CsParameters::CsParameters ()
Definition at line 25 of file cs-parameters.cc.
References ADD, and m_classifierDscAction.
~CsParameters()
ns3::CsParameters::~CsParameters ()
Definition at line 29 of file cs-parameters.cc.
CsParameters() [2/3]
ns3::CsParameters::CsParameters (Tlv tlv)
creates a convergence sub-layer parameters from a tlv
Parameters
tlv the TLV
Definition at line 34 of file cs-parameters.cc.
References ns3::VectorTlvValue::Begin(), ns3::CsParamVectorTlvValue::Classifier_DSC_Action, ns3::VectorTlvValue::End(), ns3::Tlv::GetType(), ns3::SfVectorTlvValue::IPV4_CS_Parameters, m_classifierDscAction, m_packetClassifierRule, NS_ASSERT_MSG(), ns3::CsParamVectorTlvValue::Packet_Classification_Rule, and ns3::Tlv::PeekValue().
CsParameters() [3/3]
ns3::CsParameters::CsParameters (enum Action classifierDscAction, IpcsClassifierRecord classifier)
creates a convergence sub-layer parameters from an ipcs classifier record
Parameters
classifierDscAction the DCS action type
classifier the IPCS classifier record
Definition at line 61 of file cs-parameters.cc.
References m_classifierDscAction, and m_packetClassifierRule.
Member Function Documentation
GetClassifierDscAction()
enum CsParameters::Action ns3::CsParameters::GetClassifierDscAction (void) const
Returns
the dynamic service classifier action
Definition at line 73 of file cs-parameters.cc.
GetPacketClassifierRule()
IpcsClassifierRecord ns3::CsParameters::GetPacketClassifierRule (void) const
Returns
the the packet classifier rules
Definition at line 83 of file cs-parameters.cc.
References m_packetClassifierRule.
Referenced by ns3::ServiceFlow::CheckClassifierMatch(), and Ns3WimaxCsParamTlvTestCase::DoRun().
SetClassifierDscAction()
void ns3::CsParameters::SetClassifierDscAction (enum Action action)
sets the dynamic service classifier action to ADD, Change or delete.
Only ADD is supported
Parameters
action the action enumeration
Definition at line 68 of file cs-parameters.cc.
References m_classifierDscAction.
SetPacketClassifierRule()
void ns3::CsParameters::SetPacketClassifierRule (IpcsClassifierRecord packetClassifierRule)
sets the packet classifier rules
Parameters
packetClassifierRule the IPCS classifier record
Definition at line 73 of file cs-parameters.cc.
References m_packetClassifierRule.
ToTlv()
Tlv ns3::CsParameters::ToTlv (void) const
creates a tlv from the classifier record
Returns
the created tlv
Definition at line 88 of file cs-parameters.cc.
References ns3::VectorTlvValue::Add(), ns3::CsParamVectorTlvValue::Classifier_DSC_Action, ns3::VectorTlvValue::GetSerializedSize(), ns3::SfVectorTlvValue::IPV4_CS_Parameters, m_classifierDscAction, m_packetClassifierRule, and ns3::IpcsClassifierRecord::ToTlv().
Referenced by Ns3WimaxCsParamTlvTestCase::DoRun(), and ns3::ServiceFlow::ToTlv().
Member Data Documentation
m_classifierDscAction
enum Action ns3::CsParameters::m_classifierDscAction private
classifier DSC action
Definition at line 80 of file cs-parameters.h.
Referenced by CsParameters(), SetClassifierDscAction(), and ToTlv().
m_packetClassifierRule
IpcsClassifierRecord ns3::CsParameters::m_packetClassifierRule private
packet classifier rule
Definition at line 84 of file cs-parameters.h.
Referenced by CsParameters(), GetPacketClassifierRule(), SetPacketClassifierRule(), and ToTlv().
The documentation for this class was generated from the following files:
src/wimax/model/cs-parameters.h
src/wimax/model/cs-parameters.cc