ns-3: ns3::lorawan::EndDeviceStatus Class Reference
ns3::lorawan::EndDeviceStatus Class Reference
This class represents the Network Server's knowledge about an End Device in the LoRaWAN network it is administering.
#include "end-device-status.h"
Classes
struct PacketInfoPerGw
Structure saving information regarding the packet reception in each gateway.
struct ReceivedPacketInfo
Structure saving information regarding all packet receptions.
struct Reply
Structure representing the reply that the network server will send this device at the first opportunity.
Public Types
typedef std::map< Address, PacketInfoPerGw > GatewayList
typedef std::list< std::pair< Ptr< Packet const >, ReceivedPacketInfo > > ReceivedPacketList
Public Member Functions
EndDeviceStatus ()
EndDeviceStatus (LoraDeviceAddress endDeviceAddress, Ptr< ClassAEndDeviceLorawanMac > endDeviceMac)
virtual ~EndDeviceStatus ()
void AddMACCommand (Ptr< MacCommand > macCommand)
Add MAC command to the list.
Ptr< Packet > GetCompleteReplyPacket (void)
Get the reply packet.
double GetFirstReceiveWindowFrequency (void)
Get the first window frequency of this device.
uint8_t GetFirstReceiveWindowSpreadingFactor (void)
Get the spreading factor this device is using in the first receive window.
Ptr< Packet const > GetLastPacketReceivedFromDevice (void)
Return the last packet that was received from this device.
EndDeviceStatus::ReceivedPacketInfo GetLastReceivedPacketInfo (void)
Return the information about the last packet that was received from the device.
Ptr< ClassAEndDeviceLorawanMac > GetMac (void)
std::map< double, Address > GetPowerGatewayMap (void)
Return an ordered list of the best gateways.
ReceivedPacketList GetReceivedPacketList (void)
Get the received packet list.
LoraFrameHeader GetReplyFrameHeader (void)
Get the reply packet frame header.
LorawanMacHeader GetReplyMacHeader (void)
Get the reply packet mac header.
Ptr< Packet > GetReplyPayload (void)
Get the data of the reply packet.
double GetSecondReceiveWindowFrequency (void)
Return the second window frequency of this device.
uint8_t GetSecondReceiveWindowOffset (void)
Get the offset of spreading factor this device is using in the second receive window with respect to the first receive window.
void InitializeReply (void)
Initialize reply.
void InsertReceivedPacket (Ptr< Packet const > receivedPacket, const Address &gwAddress)
Insert a received packet in the packet list.
bool NeedsReply (void)
Whether the end device needs a reply.
void SetFirstReceiveWindowFrequency (double frequency)
Set the first window frequency of this device.
void SetFirstReceiveWindowSpreadingFactor (uint8_t sf)
Set the spreading factor this device is using in the first receive window.
void SetReplyFrameHeader (LoraFrameHeader frameHeader)
Set the reply packet frame header.
void SetReplyMacHeader (LorawanMacHeader macHeader)
Set the reply packet mac header.
void SetReplyPayload (Ptr< Packet > replyPayload)
Set the packet reply payload.
void SetSecondReceiveWindowFrequency (double frequency)
Set the second window frequency of this device.
void SetSecondReceiveWindowOffset (uint8_t offset)
Set the spreading factor this device is using in the first receive window.
void UpdateGatewayData (GatewayList gwList, Address gwAddress, double rcvPower)
Update Gateway data when more then one gateway receive the same packet.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Public Attributes
LoraDeviceAddress m_endDeviceAddress
struct Reply m_reply
Private Attributes
double m_firstReceiveWindowFrequency = 0
uint8_t m_firstReceiveWindowSpreadingFactor = 0
Ptr< ClassAEndDeviceLorawanMac > m_mac
Pointer to the MAC layer of this device.
ReceivedPacketList m_receivedPacketList
double m_secondReceiveWindowFrequency = 869.525
uint8_t m_secondReceiveWindowOffset = 0
Friends
std::ostream & operator<< (std::ostream &os, const EndDeviceStatus &status)
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class represents the Network Server's knowledge about an End Device in the LoRaWAN network it is administering.
The Network Server's NetworkStatus component contains a list of instances of this class, one for each device in the network. Each instance contains all the parameters and information of the end device and the packets received from it. Furthermore, this class holds the reply packet that the network server will send to this device at the first available receive window. Upon new packet arrivals at the Network Server, the OnReceivedPacket method is called to update the information regarding the last received packet and its parameters.
Definition at line 81 of file end-device-status.h.
Member Typedef Documentation
GatewayList
typedef std::map<Address, PacketInfoPerGw> ns3::lorawan::EndDeviceStatus::GatewayList
Definition at line 162 of file end-device-status.h.
ReceivedPacketList
typedef std::list<std::pair<Ptr<Packet const>, ReceivedPacketInfo> > ns3::lorawan::EndDeviceStatus::ReceivedPacketList
Definition at line 177 of file end-device-status.h.
Constructor & Destructor Documentation
EndDeviceStatus() [1/2]
ns3::lorawan::EndDeviceStatus::EndDeviceStatus ()
Definition at line 60 of file end-device-status.cc.
References m_receivedPacketList, m_reply, and NS_LOG_FUNCTION_NOARGS.
EndDeviceStatus() [2/2]
ns3::lorawan::EndDeviceStatus::EndDeviceStatus (LoraDeviceAddress endDeviceAddress, Ptr< ClassAEndDeviceLorawanMac > endDeviceMac)
Definition at line 50 of file end-device-status.cc.
References NS_LOG_FUNCTION.
~EndDeviceStatus()
ns3::lorawan::EndDeviceStatus::~EndDeviceStatus () virtual
Definition at line 69 of file end-device-status.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
AddMACCommand()
void ns3::lorawan::EndDeviceStatus::AddMACCommand (Ptr< MacCommand > macCommand)
Add MAC command to the list.
Definition at line 363 of file end-device-status.cc.
References ns3::lorawan::LoraFrameHeader::AddCommand(), ns3::lorawan::EndDeviceStatus::Reply::frameHeader, and m_reply.
GetCompleteReplyPacket()
Ptr< Packet > ns3::lorawan::EndDeviceStatus::GetCompleteReplyPacket (void)
Get the reply packet.
Returns
A pointer to the packet reply (data + headers).
Definition at line 110 of file end-device-status.cc.
References ns3::Packet::AddHeader(), ns3::Packet::Copy(), ns3::lorawan::EndDeviceStatus::Reply::frameHeader, ns3::lorawan::LoraFrameHeader::GetFCnt(), GetLastPacketReceivedFromDevice(), m_endDeviceAddress, m_reply, ns3::lorawan::EndDeviceStatus::Reply::macHeader, NS_LOG_DEBUG, NS_LOG_FUNCTION_NOARGS, ns3::lorawan::EndDeviceStatus::Reply::payload, ns3::Packet::RemoveHeader(), ns3::lorawan::LoraFrameHeader::SetAddress(), ns3::lorawan::LoraFrameHeader::SetAsUplink(), ns3::lorawan::LoraFrameHeader::SetFCnt(), ns3::lorawan::LorawanMacHeader::SetMType(), and ns3::lorawan::LorawanMacHeader::UNCONFIRMED_DATA_DOWN.
GetFirstReceiveWindowFrequency()
double ns3::lorawan::EndDeviceStatus::GetFirstReceiveWindowFrequency (void)
Get the first window frequency of this device.
Definition at line 87 of file end-device-status.cc.
References m_firstReceiveWindowFrequency, and NS_LOG_FUNCTION_NOARGS.
GetFirstReceiveWindowSpreadingFactor()
uint8_t ns3::lorawan::EndDeviceStatus::GetFirstReceiveWindowSpreadingFactor (void)
Get the spreading factor this device is using in the first receive window.
Returns
An unsigned 8-bit integer containing the spreading factor.
Definition at line 79 of file end-device-status.cc.
References m_firstReceiveWindowSpreadingFactor, and NS_LOG_FUNCTION_NOARGS.
GetLastPacketReceivedFromDevice()
Ptr< Packet const > ns3::lorawan::EndDeviceStatus::GetLastPacketReceivedFromDevice (void)
Return the last packet that was received from this device.
Definition at line 340 of file end-device-status.cc.
References m_receivedPacketList, and NS_LOG_FUNCTION_NOARGS.
Referenced by GetCompleteReplyPacket().
GetLastReceivedPacketInfo()
EndDeviceStatus::ReceivedPacketInfo ns3::lorawan::EndDeviceStatus::GetLastReceivedPacketInfo (void)
Return the information about the last packet that was received from the device.
Definition at line 325 of file end-device-status.cc.
References m_receivedPacketList, and NS_LOG_FUNCTION_NOARGS.
GetMac()
Ptr< ClassAEndDeviceLorawanMac > ns3::lorawan::EndDeviceStatus::GetMac (void)
Definition at line 176 of file end-device-status.cc.
References m_mac.
GetPowerGatewayMap()
std::map< double, Address > ns3::lorawan::EndDeviceStatus::GetPowerGatewayMap (void)
Return an ordered list of the best gateways.
Definition at line 369 of file end-device-status.cc.
References ns3::lorawan::EndDeviceStatus::ReceivedPacketInfo::gwList, and m_receivedPacketList.
GetReceivedPacketList()
EndDeviceStatus::ReceivedPacketList ns3::lorawan::EndDeviceStatus::GetReceivedPacketList (void)
Get the received packet list.
Returns
The received packet list.
Definition at line 182 of file end-device-status.cc.
References m_receivedPacketList, and NS_LOG_FUNCTION_NOARGS.
GetReplyFrameHeader()
LoraFrameHeader ns3::lorawan::EndDeviceStatus::GetReplyFrameHeader (void)
Get the reply packet frame header.
Returns
The packet reply frame header.
Definition at line 162 of file end-device-status.cc.
References ns3::lorawan::EndDeviceStatus::Reply::frameHeader, m_reply, and NS_LOG_FUNCTION_NOARGS.
GetReplyMacHeader()
LorawanMacHeader ns3::lorawan::EndDeviceStatus::GetReplyMacHeader (void)
Get the reply packet mac header.
Returns
The packet reply mac header.
Definition at line 155 of file end-device-status.cc.
References m_reply, ns3::lorawan::EndDeviceStatus::Reply::macHeader, and NS_LOG_FUNCTION_NOARGS.
GetReplyPayload()
Ptr< Packet > ns3::lorawan::EndDeviceStatus::GetReplyPayload (void)
Get the data of the reply packet.
Returns
A pointer to the packet reply.
Definition at line 169 of file end-device-status.cc.
References ns3::Packet::Copy(), m_reply, NS_LOG_FUNCTION_NOARGS, and ns3::lorawan::EndDeviceStatus::Reply::payload.
GetSecondReceiveWindowFrequency()
double ns3::lorawan::EndDeviceStatus::GetSecondReceiveWindowFrequency (void)
Return the second window frequency of this device.
Definition at line 103 of file end-device-status.cc.
References m_secondReceiveWindowFrequency, and NS_LOG_FUNCTION_NOARGS.
GetSecondReceiveWindowOffset()
uint8_t ns3::lorawan::EndDeviceStatus::GetSecondReceiveWindowOffset (void)
Get the offset of spreading factor this device is using in the second receive window with respect to the first receive window.
Returns
An unsigned 8-bit integer containing the spreading factor.
Definition at line 95 of file end-device-status.cc.
References m_secondReceiveWindowOffset, and NS_LOG_FUNCTION_NOARGS.
GetTypeId()
TypeId ns3::lorawan::EndDeviceStatus::GetTypeId (void) static
Definition at line 41 of file end-device-status.cc.
References ns3::TypeId::SetParent().
InitializeReply()
void ns3::lorawan::EndDeviceStatus::InitializeReply (void)
Initialize reply.
Definition at line 355 of file end-device-status.cc.
References m_reply, ns3::lorawan::EndDeviceStatus::Reply::needsReply, and NS_LOG_FUNCTION_NOARGS.
InsertReceivedPacket()
void ns3::lorawan::EndDeviceStatus::InsertReceivedPacket (Ptr< Packet const > receivedPacket, const Address & gwAddress)
Insert a received packet in the packet list.
Definition at line 242 of file end-device-status.cc.
References ns3::Copy(), ns3::lorawan::EndDeviceStatus::ReceivedPacketInfo::frequency, ns3::lorawan::LoraFrameHeader::GetFCnt(), ns3::lorawan::LoraTag::GetFrequency(), ns3::lorawan::LoraTag::GetReceivePower(), ns3::lorawan::LoraTag::GetSpreadingFactor(), ns3::lorawan::EndDeviceStatus::PacketInfoPerGw::gwAddress, ns3::lorawan::EndDeviceStatus::ReceivedPacketInfo::gwList, m_receivedPacketList, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION_NOARGS, NS_LOG_INFO, ns3::lorawan::EndDeviceStatus::ReceivedPacketInfo::packet, ns3::lorawan::EndDeviceStatus::PacketInfoPerGw::receivedTime, ns3::Packet::RemoveHeader(), ns3::Packet::RemovePacketTag(), ns3::lorawan::EndDeviceStatus::PacketInfoPerGw::rxPower, ns3::lorawan::LoraFrameHeader::SetAsUplink(), SetFirstReceiveWindowFrequency(), SetFirstReceiveWindowSpreadingFactor(), and ns3::lorawan::EndDeviceStatus::ReceivedPacketInfo::sf.
NeedsReply()
bool ns3::lorawan::EndDeviceStatus::NeedsReply (void)
Whether the end device needs a reply.
This is determined by looking at headers and payload of the Reply structure: if they are empty, no reply should be needed.
Returns
A boolean value signaling if the end device needs a reply.
Definition at line 147 of file end-device-status.cc.
References m_reply, ns3::lorawan::EndDeviceStatus::Reply::needsReply, and NS_LOG_FUNCTION_NOARGS.
SetFirstReceiveWindowFrequency()
void ns3::lorawan::EndDeviceStatus::SetFirstReceiveWindowFrequency (double frequency)
Set the first window frequency of this device.
Definition at line 196 of file end-device-status.cc.
References m_firstReceiveWindowFrequency, and NS_LOG_FUNCTION_NOARGS.
Referenced by InsertReceivedPacket().
SetFirstReceiveWindowSpreadingFactor()
void ns3::lorawan::EndDeviceStatus::SetFirstReceiveWindowSpreadingFactor (uint8_t sf)
Set the spreading factor this device is using in the first receive window.
Definition at line 189 of file end-device-status.cc.
References m_firstReceiveWindowSpreadingFactor, and NS_LOG_FUNCTION_NOARGS.
Referenced by InsertReceivedPacket().
SetReplyFrameHeader()
void ns3::lorawan::EndDeviceStatus::SetReplyFrameHeader (LoraFrameHeader frameHeader)
Set the reply packet frame header.
Definition at line 224 of file end-device-status.cc.
References ns3::lorawan::EndDeviceStatus::Reply::frameHeader, m_reply, and NS_LOG_FUNCTION_NOARGS.
SetReplyMacHeader()
void ns3::lorawan::EndDeviceStatus::SetReplyMacHeader (LorawanMacHeader macHeader)
Set the reply packet mac header.
Definition at line 217 of file end-device-status.cc.
References m_reply, ns3::lorawan::EndDeviceStatus::Reply::macHeader, and NS_LOG_FUNCTION_NOARGS.
SetReplyPayload()
void ns3::lorawan::EndDeviceStatus::SetReplyPayload (Ptr< Packet > replyPayload)
Set the packet reply payload.
Definition at line 231 of file end-device-status.cc.
References m_reply, NS_LOG_FUNCTION_NOARGS, and ns3::lorawan::EndDeviceStatus::Reply::payload.
SetSecondReceiveWindowFrequency()
void ns3::lorawan::EndDeviceStatus::SetSecondReceiveWindowFrequency (double frequency)
Set the second window frequency of this device.
Definition at line 210 of file end-device-status.cc.
References m_secondReceiveWindowFrequency, and NS_LOG_FUNCTION_NOARGS.
SetSecondReceiveWindowOffset()
void ns3::lorawan::EndDeviceStatus::SetSecondReceiveWindowOffset (uint8_t offset)
Set the spreading factor this device is using in the first receive window.
Definition at line 203 of file end-device-status.cc.
References m_secondReceiveWindowOffset, and NS_LOG_FUNCTION_NOARGS.
UpdateGatewayData()
void ns3::lorawan::EndDeviceStatus::UpdateGatewayData (GatewayList gwList, Address gwAddress, double rcvPower)
Update Gateway data when more then one gateway receive the same packet.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const EndDeviceStatus & status) friend
Definition at line 389 of file end-device-status.cc.
Member Data Documentation
m_endDeviceAddress
LoraDeviceAddress ns3::lorawan::EndDeviceStatus::m_endDeviceAddress
Definition at line 304 of file end-device-status.h.
Referenced by GetCompleteReplyPacket().
m_firstReceiveWindowFrequency
double ns3::lorawan::EndDeviceStatus::m_firstReceiveWindowFrequency = 0 private
Definition at line 311 of file end-device-status.h.
Referenced by GetFirstReceiveWindowFrequency(), and SetFirstReceiveWindowFrequency().
m_firstReceiveWindowSpreadingFactor
uint8_t ns3::lorawan::EndDeviceStatus::m_firstReceiveWindowSpreadingFactor = 0 private
Definition at line 310 of file end-device-status.h.
Referenced by GetFirstReceiveWindowSpreadingFactor(), and SetFirstReceiveWindowSpreadingFactor().
m_mac
Ptr<ClassAEndDeviceLorawanMac> ns3::lorawan::EndDeviceStatus::m_mac private
Pointer to the MAC layer of this device.
Definition at line 319 of file end-device-status.h.
Referenced by GetMac().
m_receivedPacketList
ReceivedPacketList ns3::lorawan::EndDeviceStatus::m_receivedPacketList private
Definition at line 315 of file end-device-status.h.
Referenced by EndDeviceStatus(), GetLastPacketReceivedFromDevice(), GetLastReceivedPacketInfo(), GetPowerGatewayMap(), GetReceivedPacketList(), InsertReceivedPacket(), and ns3::lorawan::operator<<().
m_reply
struct Reply ns3::lorawan::EndDeviceStatus::m_reply
Definition at line 300 of file end-device-status.h.
Referenced by EndDeviceStatus(), AddMACCommand(), GetCompleteReplyPacket(), GetReplyFrameHeader(), GetReplyMacHeader(), GetReplyPayload(), InitializeReply(), NeedsReply(), SetReplyFrameHeader(), SetReplyMacHeader(), and SetReplyPayload().
m_secondReceiveWindowFrequency
double ns3::lorawan::EndDeviceStatus::m_secondReceiveWindowFrequency = 869.525 private
Definition at line 313 of file end-device-status.h.
Referenced by GetSecondReceiveWindowFrequency(), and SetSecondReceiveWindowFrequency().
m_secondReceiveWindowOffset
uint8_t ns3::lorawan::EndDeviceStatus::m_secondReceiveWindowOffset = 0 private
Definition at line 312 of file end-device-status.h.
Referenced by GetSecondReceiveWindowOffset(), and SetSecondReceiveWindowOffset().
The documentation for this class was generated from the following files:
src/lorawan/model/end-device-status.h
src/lorawan/model/end-device-status.cc