ns-3: ns3::MeshInformationElementVector Class Reference
ns3::MeshInformationElementVector Class Reference
#include "mesh-information-element-vector.h"
Public Member Functions
MeshInformationElementVector ()
~MeshInformationElementVector ()
virtual uint32_t DeserializeSingleIe (Buffer::Iterator start)
Needed when you try to deserialize a lonely IE inside other header.
TypeId GetInstanceTypeId () const
Get the most derived TypeId for this Object.
Public Member Functions inherited from ns3::WifiInformationElementVector
WifiInformationElementVector ()
virtual ~WifiInformationElementVector ()
bool AddInformationElement (Ptr< WifiInformationElement > element)
add an IE, if maxSize has exceeded, returns false
Iterator Begin ()
Returns Begin of the vector.
virtual uint32_t Deserialize (Buffer::Iterator start)
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize a number of WifiInformationElements.
Iterator End ()
Returns End of the vector.
Ptr< WifiInformationElement > FindFirst (WifiInformationElementId id) const
vector of pointers to information elements is the body of IeVector
TypeId GetInstanceTypeId () const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize () const
virtual bool operator== (const WifiInformationElementVector &a) const
Check if the given WifiInformationElementVectors are equivalent.
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::WifiInformationElementVector
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Public Types inherited from ns3::WifiInformationElementVector
typedef std::vector< Ptr< WifiInformationElement > >::iterator Iterator
As soon as this is a vector, we define an Iterator.
Protected Types inherited from ns3::WifiInformationElementVector
typedef std::vector< Ptr< WifiInformationElement > > IE_VECTOR
typedef for a vector of WifiInformationElements.
Protected Member Functions inherited from ns3::WifiInformationElementVector
uint32_t GetSize () const
Current number of bytes.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::WifiInformationElementVector
IE_VECTOR m_elements
Information element vector.
uint16_t m_maxSize
Size in bytes (actually, max packet length)
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 31 of file mesh-information-element-vector.h.
Constructor & Destructor Documentation
MeshInformationElementVector()
ns3::MeshInformationElementVector::MeshInformationElementVector ()
Definition at line 41 of file mesh-information-element-vector.cc.
~MeshInformationElementVector()
ns3::MeshInformationElementVector::~MeshInformationElementVector ()
Definition at line 45 of file mesh-information-element-vector.cc.
Member Function Documentation
DeserializeSingleIe()
uint32_t ns3::MeshInformationElementVector::DeserializeSingleIe (Buffer::Iterator start) virtual
Needed when you try to deserialize a lonely IE inside other header.
Parameters
start is the start of the buffer
Returns
deserialized bytes
Reimplemented from ns3::WifiInformationElementVector.
Definition at line 67 of file mesh-information-element-vector.cc.
References ns3::WifiInformationElement::DeserializeInformationField(), ns3::WifiInformationElementVector::DeserializeSingleIe(), ns3::Buffer::Iterator::GetDistanceFrom(), ns3::WifiInformationElementVector::GetSize(), IE11S_MESH_PEERING_PROTOCOL_VERSION, IE_BEACON_TIMING, IE_MESH_CONFIGURATION, IE_MESH_ID, IE_MESH_LINK_METRIC_REPORT, IE_MESH_PEERING_MANAGEMENT, IE_PERR, IE_PREP, IE_PREQ, IE_RANN, ns3::WifiInformationElementVector::m_elements, ns3::WifiInformationElementVector::m_maxSize, ns3::Buffer::Iterator::Next(), NS_FATAL_ERROR, ns3::Buffer::Iterator::Prev(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetInstanceTypeId()
TypeId ns3::MeshInformationElementVector::GetInstanceTypeId () const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 61 of file mesh-information-element-vector.cc.
References GetTypeId().
GetTypeId()
TypeId ns3::MeshInformationElementVector::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 51 of file mesh-information-element-vector.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
The documentation for this class was generated from the following files:
src/mesh/model/mesh-information-element-vector.h
src/mesh/model/mesh-information-element-vector.cc