ns-3: ns3::EventImpl Class Reference
ns3::EventImpl Class Reference abstract
Core » Scheduler and Events » Events
A simulation event.
#include "event-impl.h"
Public Member Functions
EventImpl ()
Default constructor.
virtual ~EventImpl ()=0
Destructor.
void Cancel (void)
Marks the event as 'canceled'.
void Invoke (void)
Called by the simulation engine to notify the event that it is time to execute.
bool IsCancelled (void)
Public Member Functions inherited from ns3::SimpleRefCount< EventImpl >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Protected Member Functions
virtual void Notify (void)=0
Implementation for Invoke().
Private Attributes
bool m_cancel
Has this event been cancelled.
Detailed Description
A simulation event.
Each subclass of this base class represents a simulation event. The Invoke() method will be called by the simulation engine when it reaches the time associated to this event. Most subclasses are usually created by one of the many Simulator::Schedule methods.
Definition at line 44 of file event-impl.h.
Constructor & Destructor Documentation
EventImpl()
ns3::EventImpl::EventImpl ()
Default constructor.
Definition at line 39 of file event-impl.cc.
References NS_LOG_FUNCTION.
~EventImpl()
ns3::EventImpl::~EventImpl () pure virtual
Destructor.
Definition at line 34 of file event-impl.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Cancel()
void ns3::EventImpl::Cancel (void)
Marks the event as 'canceled'.
The event is not removed from the event list but the simulation engine will check its canceled status before calling Invoke().
Definition at line 56 of file event-impl.cc.
References m_cancel, and NS_LOG_FUNCTION.
Invoke()
void ns3::EventImpl::Invoke (void)
Called by the simulation engine to notify the event that it is time to execute.
Definition at line 46 of file event-impl.cc.
References m_cancel, Notify(), and NS_LOG_FUNCTION.
Referenced by ns3::DefaultSimulatorImpl::ProcessOneEvent(), ns3::DistributedSimulatorImpl::ProcessOneEvent(), and ns3::NullMessageSimulatorImpl::ProcessOneEvent().
IsCancelled()
bool ns3::EventImpl::IsCancelled (void)
Returns
true if the event has been canceled.
Checked by the simulation engine before calling Invoke().
Definition at line 63 of file event-impl.cc.
References m_cancel, and NS_LOG_FUNCTION.
Notify()
virtual void ns3::EventImpl::Notify (void) protected pure virtual
Implementation for Invoke().
This typically calls a method or function pointer with the arguments bound by a call to one of the MakeEvent() functions.
Referenced by Invoke().
Member Data Documentation
m_cancel
bool ns3::EventImpl::m_cancel private
Has this event been cancelled.
Definition at line 79 of file event-impl.h.
Referenced by Cancel(), Invoke(), and IsCancelled().
The documentation for this class was generated from the following files:
src/core/model/event-impl.h
src/core/model/event-impl.cc