ns-3: LenaMimoTestCase Class Reference
LenaMimoTestCase Class Reference
LTE Models » lte module tests | Test suites
This system test program creates different test cases with a single eNB and single UE. The traffic is configured to be in saturation mode. It is checked if the throughput reaches the expected values when MIMO is used.
#include "lte-test-mimo.h"
Public Member Functions
LenaMimoTestCase (uint16_t dist, std::vector< uint32_t > estThrDl, std::string schedulerType, bool useIdealRrc)
Constructor.
virtual ~LenaMimoTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void GetRlcBufferSample (Ptr< RadioBearerStatsCalculator > rlcStats, uint64_t imsi, uint8_t rnti)
Get RLC buffer sample.
Static Private Member Functions
static std::string BuildNameString (uint16_t dist, std::string schedulerType, bool useIdealRrc)
Builds the test name string based on provided parameter values.
Private Attributes
uint16_t m_dist
the distance
std::vector< uint64_t > m_dlDataRxed
DL data received.
std::vector< uint32_t > m_estThrDl
estimated throughput DL
std::string m_schedulerType
the scheduler type
bool m_useIdealRrc
whether to use the ideal RRC
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
This system test program creates different test cases with a single eNB and single UE. The traffic is configured to be in saturation mode. It is checked if the throughput reaches the expected values when MIMO is used.
Definition at line 40 of file lte-test-mimo.h.
Constructor & Destructor Documentation
LenaMimoTestCase()
LenaMimoTestCase::LenaMimoTestCase (uint16_t dist, std::vector< uint32_t > estThrDl, std::string schedulerType, bool useIdealRrc)
Constructor.
Parameters
dist the distance
estThrDl the estimated throughput DL
schedulerType the scheduler type
useIdealRrc true if use ideal RRC
Definition at line 99 of file lte-test-mimo.cc.
~LenaMimoTestCase()
LenaMimoTestCase::~LenaMimoTestCase () virtual
Definition at line 108 of file lte-test-mimo.cc.
Member Function Documentation
BuildNameString()
std::string LenaMimoTestCase::BuildNameString (uint16_t dist, std::string schedulerType, bool useIdealRrc) static private
Builds the test name string based on provided parameter values.
Parameters
dist the distance
schedulerType the scheduler type
useIdealRrc if true use the ideal RRC
Returns
the name string
Definition at line 84 of file lte-test-mimo.cc.
DoRun()
void LenaMimoTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Initialize Simulation Scenario: 1 eNB and m_nUser UEs
Implements ns3::TestCase.
Definition at line 113 of file lte-test-mimo.cc.
References ns3::LteHelper::ActivateDataRadioBearer(), ns3::LteHelper::Attach(), ns3::NodeContainer::Create(), ns3::TestCase::CreateTempDirFilename(), ns3::LteHelper::EnableMacTraces(), ns3::LteHelper::EnableRlcTraces(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::LteEnbNetDevice::GetCcMap(), ns3::TestCase::GetName(), ns3::Object::GetObject(), ns3::LteEnbNetDevice::GetPhy(), ns3::LteUeNetDevice::GetPhy(), GetRlcBufferSample(), ns3::LteHelper::GetRlcStats(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), m_dist, m_dlDataRxed, m_estThrDl, m_schedulerType, m_useIdealRrc, third::mobility, NS_FATAL_ERROR, NS_LOG_FUNCTION, NS_LOG_INFO, NS_TEST_ASSERT_MSG_EQ_TOL, ns3::Seconds(), ns3::ObjectBase::SetAttribute(), ns3::Config::SetDefault(), ns3::LteHelper::SetPathlossModelAttribute(), ns3::MobilityModel::SetPosition(), ns3::LteHelper::SetSchedulerType(), and simulationTime.
GetRlcBufferSample()
void LenaMimoTestCase::GetRlcBufferSample (Ptr< RadioBearerStatsCalculator > rlcStats, uint64_t imsi, uint8_t rnti) private
Get RLC buffer sample.
Parameters
rlcStats Ptr<RadioBearerStatsCalculator>
imsi the IMSI
rnti the RNTI
Definition at line 262 of file lte-test-mimo.cc.
References ns3::RadioBearerStatsCalculator::GetDlRxData(), m_dlDataRxed, ns3::Now(), and NS_LOG_INFO.
Referenced by DoRun().
Member Data Documentation
m_dist
uint16_t LenaMimoTestCase::m_dist private
the distance
Definition at line 73 of file lte-test-mimo.h.
Referenced by DoRun().
m_dlDataRxed
std::vector<uint64_t> LenaMimoTestCase::m_dlDataRxed private
DL data received.
Definition at line 78 of file lte-test-mimo.h.
Referenced by DoRun(), and GetRlcBufferSample().
m_estThrDl
std::vector<uint32_t> LenaMimoTestCase::m_estThrDl private
estimated throughput DL
Definition at line 74 of file lte-test-mimo.h.
Referenced by DoRun().
m_schedulerType
std::string LenaMimoTestCase::m_schedulerType private
the scheduler type
Definition at line 75 of file lte-test-mimo.h.
Referenced by DoRun().
m_useIdealRrc
bool LenaMimoTestCase::m_useIdealRrc private
whether to use the ideal RRC
Definition at line 76 of file lte-test-mimo.h.
Referenced by DoRun().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-mimo.h
src/lte/test/lte-test-mimo.cc