ns-3: ns3::dot11s::IeConfiguration Class Reference
ns3::dot11s::IeConfiguration Class Reference
Mesh Device » IEEE 802.11s draft
Describes Mesh Configuration Element see 7.3.2.86 of 802.11s draft 3.0.
#include "ie-dot11s-configuration.h"
Public Member Functions
IeConfiguration ()
virtual uint8_t DeserializeInformationField (Buffer::Iterator i, uint8_t length)
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
virtual WifiInformationElementId ElementId () const
virtual uint8_t GetInformationFieldSize () const
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
uint8_t GetNeighborCount ()
Get neighbor count.
bool IsAirtime ()
Is airtime function.
bool IsHWMP ()
Is HWMP function.
Dot11sMeshCapability const & MeshCapability ()
Mesh capability.
virtual void Print (std::ostream &os) const
Generate human-readable form of IE.
virtual void SerializeInformationField (Buffer::Iterator i) const
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
void SetMetric (dot11sPathSelectionMetric metricId)
Set metric value.
void SetNeighborCount (uint8_t neighbors)
Set neighbor count.
void SetRouting (dot11sPathSelectionProtocol routingId)
Set routing value.
Public Member Functions inherited from ns3::WifiInformationElement
virtual ~WifiInformationElement ()
Buffer::Iterator Deserialize (Buffer::Iterator i)
Deserialize entire IE, which must be present.
Buffer::Iterator DeserializeIfPresent (Buffer::Iterator i)
Deserialize entire IE if it is present.
virtual WifiInformationElementId ElementIdExt () const
uint16_t GetSerializedSize () const
Get the size of the serialized IE including Element ID and length fields.
virtual bool operator== (WifiInformationElement const &a) const
Compare two IEs for equality by ID & Length, and then through memcmp of serialised version.
Buffer::Iterator Serialize (Buffer::Iterator i) const
Serialize entire IE including Element ID and length fields.
Public Member Functions inherited from ns3::SimpleRefCount< WifiInformationElement >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
dot11sAuthenticationProtocol m_APId
Auth protocol ID.
dot11sPathSelectionMetric m_APSMId
Active Path Metric ID.
dot11sPathSelectionProtocol m_APSPId
Active Path Selection Protocol ID.
dot11sCongestionControlMode m_CCMId
Congestion Control Mode ID.
Dot11sMeshCapability m_meshCap
Mesh capability.
uint8_t m_neighbors
neighbors
dot11sSynchronizationProtocolIdentifier m_SPId
Sync protocol ID.
Friends
bool operator== (const IeConfiguration &a, const IeConfiguration &b)
equality operator
Detailed Description
Describes Mesh Configuration Element see 7.3.2.86 of 802.11s draft 3.0.
Definition at line 127 of file ie-dot11s-configuration.h.
Constructor & Destructor Documentation
IeConfiguration()
ns3::dot11s::IeConfiguration::IeConfiguration ()
Definition at line 102 of file ie-dot11s-configuration.cc.
Member Function Documentation
DeserializeInformationField()
uint8_t ns3::dot11s::IeConfiguration::DeserializeInformationField (Buffer::Iterator start, uint8_t length) virtual
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
length
Returns
the number of bytes read
Implements ns3::WifiInformationElement.
Definition at line 136 of file ie-dot11s-configuration.cc.
References ns3::dot11s::Dot11sMeshCapability::Deserialize(), ns3::Buffer::Iterator::GetDistanceFrom(), m_APId, m_APSMId, m_APSPId, m_CCMId, m_meshCap, m_neighbors, m_SPId, ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
Referenced by ns3::dot11s::PeerLinkOpenStart::Deserialize(), and ns3::dot11s::PeerLinkConfirmStart::Deserialize().
ElementId()
WifiInformationElementId ns3::dot11s::IeConfiguration::ElementId () const virtual
Returns
Own unique Element ID
Implements ns3::WifiInformationElement.
Definition at line 97 of file ie-dot11s-configuration.cc.
References IE_MESH_CONFIGURATION.
Referenced by ns3::dot11s::PeerLinkOpenStart::Deserialize(), and ns3::dot11s::PeerLinkConfirmStart::Deserialize().
GetInformationFieldSize()
uint8_t ns3::dot11s::IeConfiguration::GetInformationFieldSize () const virtual
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
This is the value that will appear in the second octet of the entire IE - the length field)
Returns
the length of serialized information
Implements ns3::WifiInformationElement.
Definition at line 108 of file ie-dot11s-configuration.cc.
References ns3::dot11s::Dot11sMeshCapability::GetSerializedSize(), and m_meshCap.
Referenced by ns3::dot11s::PeerLinkOpenStart::Deserialize(), ns3::dot11s::PeerLinkConfirmStart::Deserialize(), ns3::dot11s::PeerLinkOpenStart::GetSerializedSize(), and ns3::dot11s::PeerLinkConfirmStart::GetSerializedSize().
GetNeighborCount()
uint8_t ns3::dot11s::IeConfiguration::GetNeighborCount ()
Get neighbor count.
Returns
the the neighbor count
Definition at line 189 of file ie-dot11s-configuration.cc.
References m_neighbors.
IsAirtime()
bool ns3::dot11s::IeConfiguration::IsAirtime ()
Is airtime function.
Returns
true if Active Path Selection Metric Identifier is set to airtime link metric
Definition at line 179 of file ie-dot11s-configuration.cc.
References m_APSMId, and ns3::dot11s::METRIC_AIRTIME.
IsHWMP()
bool ns3::dot11s::IeConfiguration::IsHWMP ()
Is HWMP function.
Returns
true if Active Path Selection Protocol Identifier field set to HWMP
Definition at line 174 of file ie-dot11s-configuration.cc.
References m_APSPId, and ns3::dot11s::PROTOCOL_HWMP.
MeshCapability()
Dot11sMeshCapability const & ns3::dot11s::IeConfiguration::MeshCapability ()
Mesh capability.
Returns
the dot11s mesh capability
Definition at line 194 of file ie-dot11s-configuration.cc.
References m_meshCap.
Print()
void ns3::dot11s::IeConfiguration::Print (std::ostream & os) const virtual
Generate human-readable form of IE.
Parameters
os output stream
Reimplemented from ns3::WifiInformationElement.
Definition at line 152 of file ie-dot11s-configuration.cc.
References ns3::dot11s::Dot11sMeshCapability::GetUint8(), m_APId, m_APSMId, m_APSPId, m_CCMId, m_meshCap, m_neighbors, and m_SPId.
Referenced by ns3::dot11s::operator<<(), ns3::dot11s::PeerLinkOpenStart::Print(), and ns3::dot11s::PeerLinkConfirmStart::Print().
SerializeInformationField()
void ns3::dot11s::IeConfiguration::SerializeInformationField (Buffer::Iterator start) const virtual
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
Implements ns3::WifiInformationElement.
Definition at line 120 of file ie-dot11s-configuration.cc.
References m_APId, m_APSMId, m_APSPId, m_CCMId, m_meshCap, m_neighbors, m_SPId, ns3::dot11s::Dot11sMeshCapability::Serialize(), and ns3::Buffer::Iterator::WriteU8().
SetMetric()
void ns3::dot11s::IeConfiguration::SetMetric (dot11sPathSelectionMetric metricId)
Set metric value.
Parameters
metricId the path selection metric
Definition at line 169 of file ie-dot11s-configuration.cc.
References m_APSMId.
SetNeighborCount()
void ns3::dot11s::IeConfiguration::SetNeighborCount (uint8_t neighbors)
Set neighbor count.
Parameters
neighbors the number of neighbors
Definition at line 184 of file ie-dot11s-configuration.cc.
References m_neighbors.
Referenced by ns3::dot11s::PeerManagementProtocolMac::SendPeerLinkManagementFrame().
SetRouting()
void ns3::dot11s::IeConfiguration::SetRouting (dot11sPathSelectionProtocol routingId)
Set routing value.
Parameters
routingId the routing ID
Definition at line 164 of file ie-dot11s-configuration.cc.
References m_APSPId.
Friends And Related Function Documentation
operator==
bool operator== (const IeConfiguration & a, const IeConfiguration & b) friend
equality operator
Parameters
a lhs
b rhs
Returns
true if equal
Definition at line 206 of file ie-dot11s-configuration.cc.
Member Data Documentation
m_APId
dot11sAuthenticationProtocol ns3::dot11s::IeConfiguration::m_APId private
Auth protocol ID.
Definition at line 186 of file ie-dot11s-configuration.h.
Referenced by DeserializeInformationField(), ns3::dot11s::operator==(), Print(), and SerializeInformationField().
m_APSMId
dot11sPathSelectionMetric ns3::dot11s::IeConfiguration::m_APSMId private
Active Path Metric ID.
Definition at line 180 of file ie-dot11s-configuration.h.
Referenced by DeserializeInformationField(), IsAirtime(), ns3::dot11s::operator==(), Print(), SerializeInformationField(), and SetMetric().
m_APSPId
dot11sPathSelectionProtocol ns3::dot11s::IeConfiguration::m_APSPId private
Active Path Selection Protocol ID.
Definition at line 178 of file ie-dot11s-configuration.h.
Referenced by DeserializeInformationField(), IsHWMP(), ns3::dot11s::operator==(), Print(), SerializeInformationField(), and SetRouting().
m_CCMId
dot11sCongestionControlMode ns3::dot11s::IeConfiguration::m_CCMId private
Congestion Control Mode ID.
Definition at line 182 of file ie-dot11s-configuration.h.
Referenced by DeserializeInformationField(), ns3::dot11s::operator==(), Print(), and SerializeInformationField().
m_meshCap
Dot11sMeshCapability ns3::dot11s::IeConfiguration::m_meshCap private
Mesh capability.
Definition at line 188 of file ie-dot11s-configuration.h.
Referenced by DeserializeInformationField(), GetInformationFieldSize(), MeshCapability(), ns3::dot11s::operator==(), Print(), and SerializeInformationField().
m_neighbors
uint8_t ns3::dot11s::IeConfiguration::m_neighbors private
neighbors
Definition at line 189 of file ie-dot11s-configuration.h.
Referenced by DeserializeInformationField(), GetNeighborCount(), ns3::dot11s::operator==(), Print(), SerializeInformationField(), and SetNeighborCount().
m_SPId
dot11sSynchronizationProtocolIdentifier ns3::dot11s::IeConfiguration::m_SPId private
Sync protocol ID.
Definition at line 184 of file ie-dot11s-configuration.h.
Referenced by DeserializeInformationField(), ns3::dot11s::operator==(), Print(), and SerializeInformationField().
The documentation for this class was generated from the following files:
src/mesh/model/dot11s/ie-dot11s-configuration.h
src/mesh/model/dot11s/ie-dot11s-configuration.cc