ns-3: PeerManagementProtocolRegressionTest Class Reference
PeerManagementProtocolRegressionTest Class Reference
Mesh Device » mesh module tests » dot11s sub-module tests | Test suites
Peering Management Protocol regression test.
#include "pmp-regression.h"
Public Member Functions
PeerManagementProtocolRegressionTest ()
~PeerManagementProtocolRegressionTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CheckResults ()
Check results function.
void CreateDevices ()
Create devices function.
void CreateNodes ()
Create nodes function.
void DoRun ()
Implementation to actually run this TestCase.
Private Attributes
NodeContainer * m_nodes
Time m_time
Simulation time.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Peering Management Protocol regression test.
Initiate scenario with 2 stations. Procedure of opening peer link is the following:
* |----------->|  Beacon
* |<-----------|  Peer Link Open frame
* |----------->|  Peer Link Open frame
* |----------->|  Peer Link Confirm frame
* |<-----------|  Peer Link Confirm frame
* |............|
* |<---------->|  Other beacons
*
Definition at line 46 of file pmp-regression.h.
Constructor & Destructor Documentation
PeerManagementProtocolRegressionTest()
PeerManagementProtocolRegressionTest::PeerManagementProtocolRegressionTest ()
Definition at line 42 of file pmp-regression.cc.
~PeerManagementProtocolRegressionTest()
PeerManagementProtocolRegressionTest::~PeerManagementProtocolRegressionTest ()
Definition at line 48 of file pmp-regression.cc.
References m_nodes.
Member Function Documentation
CheckResults()
void PeerManagementProtocolRegressionTest::CheckResults () private
Check results function.
Definition at line 112 of file pmp-regression.cc.
References NS_PCAP_TEST_EXPECT_EQ, and PREFIX.
Referenced by DoRun().
CreateDevices()
void PeerManagementProtocolRegressionTest::CreateDevices () private
Create devices function.
Definition at line 88 of file pmp-regression.cc.
References ns3::MeshHelper::AssignStreams(), ns3::YansWifiChannelHelper::AssignStreams(), ns3::YansWifiChannelHelper::Create(), ns3::TestCase::CreateTempDirFilename(), ns3::PcapHelperForDevice::EnablePcapAll(), ns3::NetDeviceContainer::GetN(), ns3::MeshHelper::Install(), m_nodes, NS_TEST_ASSERT_MSG_EQ, PREFIX, ns3::Seconds(), ns3::YansWifiPhyHelper::SetChannel(), ns3::MeshHelper::SetMacType(), ns3::MeshHelper::SetNumberOfInterfaces(), and ns3::MeshHelper::SetStackInstaller().
Referenced by DoRun().
CreateNodes()
void PeerManagementProtocolRegressionTest::CreateNodes () private
Create nodes function.
Definition at line 71 of file pmp-regression.cc.
References ns3::NodeContainer::Create(), m_nodes, and third::mobility.
Referenced by DoRun().
DoRun()
void PeerManagementProtocolRegressionTest::DoRun () private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 54 of file pmp-regression.cc.
References CheckResults(), CreateDevices(), CreateNodes(), m_nodes, and m_time.
Member Data Documentation
m_nodes
NodeContainer* PeerManagementProtocolRegressionTest::m_nodes private
Internal: It is important to have pointers here
Definition at line 54 of file pmp-regression.h.
Referenced by ~PeerManagementProtocolRegressionTest(), CreateDevices(), CreateNodes(), and DoRun().
m_time
Time PeerManagementProtocolRegressionTest::m_time private
Simulation time.
Definition at line 56 of file pmp-regression.h.
Referenced by DoRun().
The documentation for this class was generated from the following files:
src/mesh/test/dot11s/pmp-regression.h
src/mesh/test/dot11s/pmp-regression.cc