ns-3: ns3::NetDeviceQueue Class Reference
ns3::NetDeviceQueue Class Reference
Network » Network Device
Network device transmission queue.
#include "net-device-queue-interface.h"
Public Types
typedef Callback< void > WakeCallback
Callback invoked by netdevices to wake upper layers.
Public Member Functions
NetDeviceQueue ()
virtual ~NetDeviceQueue ()
template<typename QueueType >
void ConnectQueueTraces (Ptr< QueueType > queue)
Connect the traced callbacks of a queue to the methods providing support for flow control and dynamic queue limits.
Ptr< QueueLimits > GetQueueLimits ()
Get queue limits to this queue.
bool IsStopped (void) const
Get the status of the device transmission queue.
void NotifyAggregatedObject (Ptr< NetDeviceQueueInterface > ndqi)
Notify this NetDeviceQueue that the NetDeviceQueueInterface was aggregated to an object.
void NotifyQueuedBytes (uint32_t bytes)
Called by the netdevice to report the number of bytes queued to the device queue.
void NotifyTransmittedBytes (uint32_t bytes)
Called by the netdevice to report the number of bytes it is going to transmit.
template<typename QueueType >
void PacketDequeued (QueueType *queue, Ptr< const typename QueueType::ItemType > item)
Perform the actions required by flow control and dynamic queue limits when a packet is dequeued (or dropped after dequeue) from the queue of a netdevice.
template<typename QueueType >
void PacketDiscarded (QueueType *queue, Ptr< const typename QueueType::ItemType > item)
Perform the actions required by flow control and dynamic queue limits when a packet is dropped before being enqueued in the queue of a netdevice (which likely indicates that the queue is full)
template<typename QueueType >
void PacketEnqueued (QueueType *queue, Ptr< const typename QueueType::ItemType > item)
Perform the actions required by flow control and dynamic queue limits when a packet is enqueued in the queue of a netdevice.
void ResetQueueLimits ()
Reset queue limits state.
void SetQueueLimits (Ptr< QueueLimits > ql)
Set queue limits to this queue.
virtual void SetWakeCallback (WakeCallback cb)
Set the wake callback.
virtual void Start (void)
Called by the device to start this device transmission queue.
virtual void Stop (void)
Called by the device to stop this device transmission queue.
virtual void Wake (void)
Called by the device to wake the queue disc associated with this device transmission queue.
Public Member Functions inherited from ns3::SimpleRefCount< NetDeviceQueue >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
Ptr< NetDevice > m_device
the netdevice aggregated to the NetDeviceQueueInterface
Ptr< QueueLimits > m_queueLimits
Queue limits object.
bool m_stoppedByDevice
True if the queue has been stopped by the device.
bool m_stoppedByQueueLimits
True if the queue has been stopped by a queue limits object.
WakeCallback m_wakeCallback
Wake callback.
NS_LOG_TEMPLATE_DECLARE
redefinition of the log component
Detailed Description
Network device transmission queue.
This class stores information about a single transmission queue of a network device that is exposed to queue discs. Such information includes the state of the transmission queue (whether it has been stopped or not) and data used by techniques such as Byte Queue Limits.
This class roughly models the struct netdev_queue of Linux.
Definition at line 55 of file net-device-queue-interface.h.
Member Typedef Documentation
WakeCallback
typedef Callback< void > ns3::NetDeviceQueue::WakeCallback
Callback invoked by netdevices to wake upper layers.
Definition at line 101 of file net-device-queue-interface.h.
Constructor & Destructor Documentation
NetDeviceQueue()
ns3::NetDeviceQueue::NetDeviceQueue ()
Definition at line 32 of file net-device-queue-interface.cc.
References NS_LOG_FUNCTION.
~NetDeviceQueue()
ns3::NetDeviceQueue::~NetDeviceQueue () virtual
Definition at line 40 of file net-device-queue-interface.cc.
References m_device, m_queueLimits, m_wakeCallback, NS_LOG_FUNCTION, and ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::Nullify().
Member Function Documentation
ConnectQueueTraces()
template<typename QueueType > void ns3::NetDeviceQueue::ConnectQueueTraces (Ptr< QueueType > queue)
Connect the traced callbacks of a queue to the methods providing support for flow control and dynamic queue limits.
Implementation of the templates declared above.
A queue can be any object providing:
"Enqueue", "Dequeue", "DropBeforeEnqueue" traces
an ItemType typedef for the type of stored items
GetCurrentSize and GetMaxSize methods
Parameters
queue the queue
Definition at line 307 of file net-device-queue-interface.h.
References ns3::MakeCallback(), NS_ASSERT, and ns3::PeekPointer().
GetQueueLimits()
Ptr< QueueLimits > ns3::NetDeviceQueue::GetQueueLimits ()
Get queue limits to this queue.
Returns
the queue limits associated to this queue
Definition at line 157 of file net-device-queue-interface.cc.
References m_queueLimits, and NS_LOG_FUNCTION.
IsStopped()
bool ns3::NetDeviceQueue::IsStopped (void) const
Get the status of the device transmission queue.
Returns
true if the device transmission queue is stopped.
Called by queue discs to enquire about the status of a given transmission queue. This is the analogous to the netif_xmit_stopped function of the Linux kernel.
Definition at line 50 of file net-device-queue-interface.cc.
References m_stoppedByDevice, m_stoppedByQueueLimits, and NS_LOG_FUNCTION.
NotifyAggregatedObject()
void ns3::NetDeviceQueue::NotifyAggregatedObject (Ptr< NetDeviceQueueInterface > ndqi)
Notify this NetDeviceQueue that the NetDeviceQueueInterface was aggregated to an object.
Parameters
ndqi the NetDeviceQueueInterface.
This NetDeviceQueue stores a pointer to the NetDevice the NetDeviceQueueInterface was aggregated to.
Definition at line 86 of file net-device-queue-interface.cc.
References m_device, NS_ABORT_MSG_IF, and NS_LOG_FUNCTION.
NotifyQueuedBytes()
void ns3::NetDeviceQueue::NotifyQueuedBytes (uint32_t bytes)
Called by the netdevice to report the number of bytes queued to the device queue.
Parameters
bytes number of bytes queued to the device queue
Definition at line 101 of file net-device-queue-interface.cc.
References m_queueLimits, m_stoppedByQueueLimits, and NS_LOG_FUNCTION.
Referenced by PacketEnqueued().
NotifyTransmittedBytes()
void ns3::NetDeviceQueue::NotifyTransmittedBytes (uint32_t bytes)
Called by the netdevice to report the number of bytes it is going to transmit.
Parameters
bytes number of bytes the device is going to transmit
Definition at line 117 of file net-device-queue-interface.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_queueLimits, m_stoppedByQueueLimits, m_wakeCallback, NS_LOG_FUNCTION, and ns3::Simulator::ScheduleNow().
Referenced by PacketDequeued().
PacketDequeued()
template<typename QueueType > void ns3::NetDeviceQueue::PacketDequeued (QueueType * queue, Ptr< const typename QueueType::ItemType > item)
Perform the actions required by flow control and dynamic queue limits when a packet is dequeued (or dropped after dequeue) from the queue of a netdevice.
Parameters
queue the device queue
item the dequeued packet
This method must be connected to the "Dequeue" traced callback of a Queue object (through a bound callback) in order for a netdevice to support flow control and dynamic queue limits.
Definition at line 347 of file net-device-queue-interface.h.
References m_device, NotifyTransmittedBytes(), NS_ASSERT_MSG(), NS_LOG_FUNCTION, and Wake().
PacketDiscarded()
template<typename QueueType > void ns3::NetDeviceQueue::PacketDiscarded (QueueType * queue, Ptr< const typename QueueType::ItemType > item)
Perform the actions required by flow control and dynamic queue limits when a packet is dropped before being enqueued in the queue of a netdevice (which likely indicates that the queue is full)
Parameters
queue the device queue
item the dropped packet
This method must be connected to the "DropBeforeEnqueue" traced callback of a Queue object (through a bound callback) in order for a netdevice to support flow control and dynamic queue limits.
Definition at line 369 of file net-device-queue-interface.h.
References NS_LOG_ERROR, NS_LOG_FUNCTION, and Stop().
PacketEnqueued()
template<typename QueueType > void ns3::NetDeviceQueue::PacketEnqueued (QueueType * queue, Ptr< const typename QueueType::ItemType > item)
Perform the actions required by flow control and dynamic queue limits when a packet is enqueued in the queue of a netdevice.
Parameters
queue the device queue
item the enqueued packet
This method must be connected to the "Enqueue" traced callback of a Queue object (through a bound callback) in order for a netdevice to support flow control and dynamic queue limits.
Definition at line 324 of file net-device-queue-interface.h.
References m_device, NotifyQueuedBytes(), NS_ASSERT_MSG(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and Stop().
ResetQueueLimits()
void ns3::NetDeviceQueue::ResetQueueLimits ()
Reset queue limits state.
Definition at line 139 of file net-device-queue-interface.cc.
References m_queueLimits, and NS_LOG_FUNCTION.
SetQueueLimits()
void ns3::NetDeviceQueue::SetQueueLimits (Ptr< QueueLimits > ql)
Set queue limits to this queue.
Parameters
ql the queue limits associated to this queue
Definition at line 150 of file net-device-queue-interface.cc.
References m_queueLimits, and NS_LOG_FUNCTION.
SetWakeCallback()
void ns3::NetDeviceQueue::SetWakeCallback (WakeCallback cb) virtual
Set the wake callback.
Parameters
cb the callback to set
Called by the traffic control layer to set the wake callback. The wake callback is invoked by the device whenever it is needed to "wake" the upper layers (i.e., solicitate the queue disc associated with this transmission queue (in case of multi-queue aware queue discs) or to the network device (otherwise) to send packets down to the device).
Definition at line 95 of file net-device-queue-interface.cc.
References m_wakeCallback.
Start()
void ns3::NetDeviceQueue::Start (void) virtual
Called by the device to start this device transmission queue.
This is the analogous to the netif_tx_start_queue function of the Linux kernel.
Definition at line 57 of file net-device-queue-interface.cc.
References m_stoppedByDevice, and NS_LOG_FUNCTION.
Stop()
void ns3::NetDeviceQueue::Stop (void) virtual
Called by the device to stop this device transmission queue.
This is the analogous to the netif_tx_stop_queue function of the Linux kernel.
Definition at line 64 of file net-device-queue-interface.cc.
References m_stoppedByDevice, and NS_LOG_FUNCTION.
Referenced by PacketDiscarded(), and PacketEnqueued().
Wake()
void ns3::NetDeviceQueue::Wake (void) virtual
Called by the device to wake the queue disc associated with this device transmission queue.
This is done by invoking the wake callback. This is the analogous to the netif_tx_wake_queue function of the Linux kernel.
Definition at line 71 of file net-device-queue-interface.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_stoppedByDevice, m_wakeCallback, NS_LOG_FUNCTION, and ns3::Simulator::ScheduleNow().
Referenced by PacketDequeued().
Member Data Documentation
m_device
Ptr<NetDevice> ns3::NetDeviceQueue::m_device private
the netdevice aggregated to the NetDeviceQueueInterface
Definition at line 204 of file net-device-queue-interface.h.
Referenced by ~NetDeviceQueue(), NotifyAggregatedObject(), PacketDequeued(), and PacketEnqueued().
m_queueLimits
Ptr<QueueLimits> ns3::NetDeviceQueue::m_queueLimits private
Queue limits object.
Definition at line 202 of file net-device-queue-interface.h.
Referenced by ~NetDeviceQueue(), GetQueueLimits(), NotifyQueuedBytes(), NotifyTransmittedBytes(), ResetQueueLimits(), and SetQueueLimits().
m_stoppedByDevice
bool ns3::NetDeviceQueue::m_stoppedByDevice private
True if the queue has been stopped by the device.
Definition at line 200 of file net-device-queue-interface.h.
Referenced by IsStopped(), Start(), Stop(), and Wake().
m_stoppedByQueueLimits
bool ns3::NetDeviceQueue::m_stoppedByQueueLimits private
True if the queue has been stopped by a queue limits object.
Definition at line 201 of file net-device-queue-interface.h.
Referenced by IsStopped(), NotifyQueuedBytes(), and NotifyTransmittedBytes().
m_wakeCallback
WakeCallback ns3::NetDeviceQueue::m_wakeCallback private
Wake callback.
Definition at line 203 of file net-device-queue-interface.h.
Referenced by ~NetDeviceQueue(), NotifyTransmittedBytes(), SetWakeCallback(), and Wake().
NS_LOG_TEMPLATE_DECLARE
ns3::NetDeviceQueue::NS_LOG_TEMPLATE_DECLARE private
redefinition of the log component
Definition at line 206 of file net-device-queue-interface.h.
The documentation for this class was generated from the following files:
src/network/utils/net-device-queue-interface.h
src/network/utils/net-device-queue-interface.cc