ns-3: ns3::U32TlvValue Class Reference
ns3::U32TlvValue Class Reference
WiMAX Models
U32TlvValue class.
#include "wimax-tlv.h"
Public Member Functions
U32TlvValue ()
U32TlvValue (uint32_t value)
Constructor.
~U32TlvValue (void)
virtual U32TlvValue * Copy (void) const
Copy.
uint32_t Deserialize (Buffer::Iterator start)
Deserialize from a buffer.
virtual uint32_t Deserialize (Buffer::Iterator start, uint64_t valueLen)
Deserialize from a buffer.
virtual uint32_t GetSerializedSize (void) const
Get serialized size in bytes.
uint32_t GetValue (void) const
Get value.
virtual void Serialize (Buffer::Iterator start) const
Serialize to a buffer.
Public Member Functions inherited from ns3::TlvValue
virtual ~TlvValue ()
Private Attributes
uint32_t m_value
value
Detailed Description
U32TlvValue class.
Definition at line 248 of file wimax-tlv.h.
Constructor & Destructor Documentation
U32TlvValue() [1/2]
ns3::U32TlvValue::U32TlvValue (uint32_t value)
Constructor.
Parameters
value to encode
Definition at line 599 of file wimax-tlv.cc.
References m_value.
U32TlvValue() [2/2]
ns3::U32TlvValue::U32TlvValue ()
Definition at line 604 of file wimax-tlv.cc.
References m_value.
Referenced by Copy().
~U32TlvValue()
ns3::U32TlvValue::~U32TlvValue (void)
Definition at line 609 of file wimax-tlv.cc.
Member Function Documentation
Copy()
U32TlvValue * ns3::U32TlvValue::Copy (void) const virtual
Copy.
Returns
the U32 TLV Value
Implements ns3::TlvValue.
Definition at line 641 of file wimax-tlv.cc.
References U32TlvValue(), and m_value.
Deserialize() [1/2]
uint32_t ns3::U32TlvValue::Deserialize (Buffer::Iterator start)
Deserialize from a buffer.
Parameters
start the iterator
Returns
the size
Definition at line 629 of file wimax-tlv.cc.
References m_value, and ns3::Buffer::Iterator::ReadNtohU32().
Deserialize() [2/2]
uint32_t ns3::U32TlvValue::Deserialize (Buffer::Iterator start, uint64_t valueLen) virtual
Deserialize from a buffer.
Parameters
start the iterator
valueLen the maximum length of the value
Returns
the
Implements ns3::TlvValue.
Definition at line 623 of file wimax-tlv.cc.
Referenced by ns3::SfVectorTlvValue::Deserialize().
GetSerializedSize()
uint32_t ns3::U32TlvValue::GetSerializedSize (void) const virtual
Get serialized size in bytes.
Returns
the serialized size
Implements ns3::TlvValue.
Definition at line 613 of file wimax-tlv.cc.
GetValue()
uint32_t ns3::U32TlvValue::GetValue (void) const
Get value.
Returns
the value
Definition at line 635 of file wimax-tlv.cc.
References m_value.
Serialize()
void ns3::U32TlvValue::Serialize (Buffer::Iterator start) const virtual
Serialize to a buffer.
Parameters
start the iterator
Implements ns3::TlvValue.
Definition at line 618 of file wimax-tlv.cc.
References m_value, and ns3::Buffer::Iterator::WriteHtonU32().
Member Data Documentation
m_value
uint32_t ns3::U32TlvValue::m_value private
value
Definition at line 280 of file wimax-tlv.h.
Referenced by U32TlvValue(), Copy(), Deserialize(), GetValue(), and Serialize().
The documentation for this class was generated from the following files:
src/wimax/model/wimax-tlv.h
src/wimax/model/wimax-tlv.cc