ns-3: ns3::SfVectorTlvValue Class Reference
ns3::SfVectorTlvValue Class Reference
WiMAX Models
SfVectorTlvValue class.
#include "wimax-tlv.h"
Public Types
enum Type {
SFID = 1, CID = 2, Service_Class_Name = 3, reserved1 = 4,
QoS_Parameter_Set_Type = 5, Traffic_Priority = 6, Maximum_Sustained_Traffic_Rate = 7, Maximum_Traffic_Burst = 8,
Minimum_Reserved_Traffic_Rate = 9, Minimum_Tolerable_Traffic_Rate = 10, Service_Flow_Scheduling_Type = 11, Request_Transmission_Policy = 12,
Tolerated_Jitter = 13, Maximum_Latency = 14, Fixed_length_versus_Variable_length_SDU_Indicator = 15, SDU_Size = 16,
Target_SAID = 17, ARQ_Enable = 18, ARQ_WINDOW_SIZE = 19, ARQ_RETRY_TIMEOUT_Transmitter_Delay = 20,
ARQ_RETRY_TIMEOUT_Receiver_Delay = 21, ARQ_BLOCK_LIFETIME = 22, ARQ_SYNC_LOSS = 23, ARQ_DELIVER_IN_ORDER = 24,
ARQ_PURGE_TIMEOUT = 25, ARQ_BLOCK_SIZE = 26, reserved2 = 27, CS_Specification = 28,
IPV4_CS_Parameters = 100
}
Type enumeration.
Public Types inherited from ns3::VectorTlvValue
typedef std::vector< Tlv * >::const_iterator Iterator
TLV vector iterator typedef.
Public Member Functions
SfVectorTlvValue ()
virtual SfVectorTlvValue * Copy (void) const
Copy.
virtual uint32_t Deserialize (Buffer::Iterator start, uint64_t valueLength)
Deserialize from a buffer.
Public Member Functions inherited from ns3::VectorTlvValue
VectorTlvValue (void)
~VectorTlvValue (void)
void Add (const Tlv &val)
Add a TLV.
Iterator Begin () const
Begin iterator.
Iterator End () const
End iterator.
virtual uint32_t GetSerializedSize (void) const
Get serialized size in bytes.
virtual void Serialize (Buffer::Iterator start) const
Serialize to a buffer.
Public Member Functions inherited from ns3::TlvValue
virtual ~TlvValue ()
Detailed Description
SfVectorTlvValue class.
Definition at line 328 of file wimax-tlv.h.
Member Enumeration Documentation
Type
enum ns3::SfVectorTlvValue::Type
Type enumeration.
Enumerator
SFID
CID
Service_Class_Name
reserved1
QoS_Parameter_Set_Type
Traffic_Priority
Maximum_Sustained_Traffic_Rate
Maximum_Traffic_Burst
Minimum_Reserved_Traffic_Rate
Minimum_Tolerable_Traffic_Rate
Service_Flow_Scheduling_Type
Request_Transmission_Policy
Tolerated_Jitter
Maximum_Latency
Fixed_length_versus_Variable_length_SDU_Indicator
SDU_Size
Target_SAID
ARQ_Enable
ARQ_WINDOW_SIZE
ARQ_RETRY_TIMEOUT_Transmitter_Delay
ARQ_RETRY_TIMEOUT_Receiver_Delay
ARQ_BLOCK_LIFETIME
ARQ_SYNC_LOSS
ARQ_DELIVER_IN_ORDER
ARQ_PURGE_TIMEOUT
ARQ_BLOCK_SIZE
reserved2
CS_Specification
IPV4_CS_Parameters
Definition at line 333 of file wimax-tlv.h.
Constructor & Destructor Documentation
SfVectorTlvValue()
ns3::SfVectorTlvValue::SfVectorTlvValue ()
Definition at line 290 of file wimax-tlv.cc.
Referenced by Copy().
Member Function Documentation
Copy()
SfVectorTlvValue * ns3::SfVectorTlvValue::Copy (void) const virtual
Copy.
Returns
the vector TLV value
Implements ns3::VectorTlvValue.
Definition at line 296 of file wimax-tlv.cc.
References SfVectorTlvValue(), ns3::VectorTlvValue::Add(), ns3::VectorTlvValue::Begin(), and ns3::VectorTlvValue::End().
Referenced by ns3::Tlv::Deserialize().
Deserialize()
uint32_t ns3::SfVectorTlvValue::Deserialize (Buffer::Iterator start, uint64_t valueLen) virtual
Deserialize from a buffer.
Parameters
start the iterator
valueLen the maximum length of the value
Returns
the
Implements ns3::VectorTlvValue.
Definition at line 307 of file wimax-tlv.cc.
References ns3::VectorTlvValue::Add(), ARQ_BLOCK_LIFETIME, ARQ_BLOCK_SIZE, ARQ_DELIVER_IN_ORDER, ARQ_Enable, ARQ_PURGE_TIMEOUT, ARQ_RETRY_TIMEOUT_Receiver_Delay, ARQ_RETRY_TIMEOUT_Transmitter_Delay, ARQ_SYNC_LOSS, ARQ_WINDOW_SIZE, CID, CS_Specification, ns3::U8TlvValue::Deserialize(), ns3::U16TlvValue::Deserialize(), ns3::U32TlvValue::Deserialize(), ns3::CsParamVectorTlvValue::Deserialize(), Fixed_length_versus_Variable_length_SDU_Indicator, IPV4_CS_Parameters, Maximum_Latency, Maximum_Sustained_Traffic_Rate, Maximum_Traffic_Burst, Minimum_Reserved_Traffic_Rate, Minimum_Tolerable_Traffic_Rate, ns3::Buffer::Iterator::Next(), NS_ASSERT_MSG(), NS_FATAL_ERROR, QoS_Parameter_Set_Type, ns3::Buffer::Iterator::ReadU8(), Request_Transmission_Policy, reserved1, reserved2, SDU_Size, Service_Class_Name, Service_Flow_Scheduling_Type, SFID, Target_SAID, Tolerated_Jitter, Traffic_Priority, and WIMAX_TLV_EXTENDED_LENGTH_MASK.
Referenced by ns3::Tlv::Deserialize().
The documentation for this class was generated from the following files:
src/wimax/model/wimax-tlv.h
src/wimax/model/wimax-tlv.cc