ns-3: ns3::AsciiFile Class Reference
ns3::AsciiFile Class Reference
A class representing an ascii file.
#include "ascii-file.h"
Public Member Functions
AsciiFile ()
~AsciiFile ()
void Close (void)
Close the underlying file.
bool Eof (void) const
bool Fail (void) const
void Open (std::string const &filename, std::ios::openmode mode)
Create a new ascii file or open an existing ascii file.
void Read (std::string &line)
Read next line from file.
Static Public Member Functions
static bool Diff (std::string const &f1, std::string const &f2, uint64_t &lineNumber)
Compare two ASCII files line-by-line.
Private Attributes
std::fstream m_file
output file
std::string m_filename
output file name
Detailed Description
A class representing an ascii file.
This class represents an ascii file
Definition at line 38 of file ascii-file.h.
Constructor & Destructor Documentation
AsciiFile()
ns3::AsciiFile::AsciiFile ()
Definition at line 35 of file ascii-file.cc.
References m_file, and ns3::FatalImpl::RegisterStream().
~AsciiFile()
ns3::AsciiFile::~AsciiFile ()
Definition at line 41 of file ascii-file.cc.
References Close(), m_file, and ns3::FatalImpl::UnregisterStream().
Member Function Documentation
Close()
void ns3::AsciiFile::Close (void)
Close the underlying file.
Definition at line 59 of file ascii-file.cc.
References m_file.
Referenced by ~AsciiFile().
Diff()
bool ns3::AsciiFile::Diff (std::string const & f1, std::string const & f2, uint64_t & lineNumber) static
Compare two ASCII files line-by-line.
Returns
true if files are different, false otherwise
Parameters
f1 First ASCII file name
f2 Second ASCII file name
lineNumber [out] Line number of first different line.
Definition at line 83 of file ascii-file.cc.
References Eof(), Fail(), Open(), and Read().
Eof()
bool ns3::AsciiFile::Eof (void) const
Returns
true if the 'eof' bit is set in the underlying iostream, false otherwise.
Definition at line 53 of file ascii-file.cc.
References m_file.
Referenced by Diff().
Fail()
bool ns3::AsciiFile::Fail (void) const
Returns
true if the 'fail' bit is set in the underlying iostream, false otherwise.
Definition at line 48 of file ascii-file.cc.
References m_file.
Referenced by Diff().
Open()
void ns3::AsciiFile::Open (std::string const & filename, std::ios::openmode mode)
Create a new ascii file or open an existing ascii file.
Parameters
filename String containing the name of the file.
mode the access mode for the file.
Definition at line 65 of file ascii-file.cc.
References m_file, and NS_ASSERT.
Referenced by Diff().
Read()
void ns3::AsciiFile::Read (std::string & line)
Read next line from file.
Parameters
line [out] line from file
Definition at line 74 of file ascii-file.cc.
References m_file, and NS_ASSERT.
Referenced by Diff().
Member Data Documentation
m_file
std::fstream ns3::AsciiFile::m_file private
output file
Definition at line 89 of file ascii-file.h.
Referenced by AsciiFile(), ~AsciiFile(), Close(), Eof(), Fail(), Open(), and Read().
m_filename
std::string ns3::AsciiFile::m_filename private
output file name
Definition at line 88 of file ascii-file.h.
The documentation for this class was generated from the following files:
src/network/utils/ascii-file.h
src/network/utils/ascii-file.cc