ns-3: ns3::TypeId Class Reference
ns3::TypeId Class Reference
Core » Object
a unique identifier for an interface.
#include "type-id.h"
Classes
struct AttributeInformation
Attribute implementation.
struct TraceSourceInformation
TraceSource implementation.
Public Types
enum AttributeFlag { ATTR_GET = 1 << 0, ATTR_SET = 1 << 1, ATTR_CONSTRUCT = 1 << 2, ATTR_SGC = ATTR_GET | ATTR_SET | ATTR_CONSTRUCT }
Flags describing when a given attribute can be read or written.
typedef uint32_t hash_t
Type of hash values.
enum SupportLevel { SUPPORTED, DEPRECATED, OBSOLETE }
The level of support or deprecation for attributes or trace sources.
Public Member Functions
TypeId ()
Default constructor.
TypeId (const char *name)
Constructor.
TypeId (const TypeId &o)
Copy constructor.
~TypeId ()
Destructor.
TypeId AddAttribute (std::string name, std::string help, const AttributeValue &initialValue, Ptr< const AttributeAccessor > accessor, Ptr< const AttributeChecker > checker, SupportLevel supportLevel=SUPPORTED, const std::string &supportMsg="")
Record in this TypeId the fact that a new attribute exists.
TypeId AddAttribute (std::string name, std::string help, uint32_t flags, const AttributeValue &initialValue, Ptr< const AttributeAccessor > accessor, Ptr< const AttributeChecker > checker, SupportLevel supportLevel=SUPPORTED, const std::string &supportMsg="")
Record in this TypeId the fact that a new attribute exists.
template<typename T >
TypeId AddConstructor (void)
Record in this TypeId the fact that the default constructor is accessible.
NS_DEPRECATED TypeId AddTraceSource (std::string name, std::string help, Ptr< const TraceSourceAccessor > accessor)
Record a new TraceSource.
TypeId AddTraceSource (std::string name, std::string help, Ptr< const TraceSourceAccessor > accessor, std::string callback, SupportLevel supportLevel=SUPPORTED, const std::string &supportMsg="")
Record a new TraceSource.
struct TypeId::AttributeInformation GetAttribute (std::size_t i) const
Get Attribute information by index.
std::string GetAttributeFullName (std::size_t i) const
Get the Attribute name by index.
std::size_t GetAttributeN (void) const
Get the number of attributes.
Callback< ObjectBase * > GetConstructor (void) const
Get the constructor callback.
std::string GetGroupName (void) const
Get the group name.
hash_t GetHash (void) const
Get the hash.
std::string GetName (void) const
Get the name.
TypeId GetParent (void) const
Get the parent of this TypeId.
std::size_t GetSize (void) const
Get the size of this object.
struct TypeId::TraceSourceInformation GetTraceSource (std::size_t i) const
Get the trace source by index.
std::size_t GetTraceSourceN (void) const
Get the number of Trace sources.
uint16_t GetUid (void) const
Get the internal id of this TypeId.
bool HasConstructor (void) const
Check if this TypeId has a constructor.
bool HasParent (void) const
Check if this TypeId has a parent.
TypeId HideFromDocumentation (void)
Hide this TypeId from documentation.
bool IsChildOf (TypeId other) const
Check if this TypeId is a child of another.
bool LookupAttributeByName (std::string name, struct AttributeInformation *info) const
Find an Attribute by name, retrieving the associated AttributeInformation.
Ptr< const TraceSourceAccessor > LookupTraceSourceByName (std::string name) const
Find a TraceSource by name.
Ptr< const TraceSourceAccessor > LookupTraceSourceByName (std::string name, struct TraceSourceInformation *info) const
Find a TraceSource by name, retrieving the associated TraceSourceInformation.
bool MustHideFromDocumentation (void) const
Check if this TypeId should not be listed in documentation.
TypeId & operator= (const TypeId &o)
Assignment.
bool SetAttributeInitialValue (std::size_t i, Ptr< const AttributeValue > initialValue)
Set the initial value of an Attribute.
TypeId SetGroupName (std::string groupName)
Set the group name.
TypeId SetParent (TypeId tid)
Set the parent TypeId.
template<typename T >
TypeId SetParent (void)
Set the parent TypeId.
TypeId SetSize (std::size_t size)
Set the size of this type.
void SetUid (uint16_t uid)
Set the internal id of this TypeId.
Static Public Member Functions
static TypeId GetRegistered (uint16_t i)
Get a TypeId by index.
static uint16_t GetRegisteredN (void)
Get the number of registered TypeIds.
static TypeId LookupByHash (hash_t hash)
Get a TypeId by hash.
static bool LookupByHashFailSafe (hash_t hash, TypeId *tid)
Get a TypeId by hash.
static TypeId LookupByName (std::string name)
Get a TypeId by name.
static bool LookupByNameFailSafe (std::string name, TypeId *tid)
Get a TypeId by name.
Private Member Functions
TypeId (uint16_t tid)
Construct from an integer value.
void DoAddConstructor (Callback< ObjectBase * > callback)
Implementation for AddConstructor().
Private Attributes
uint16_t m_tid
The TypeId value.
Friends
Comparison operators.
Standard comparison operators.
bool operator== (TypeId a, TypeId b)
Comparison operator.
bool operator!= (TypeId a, TypeId b)
Comparison operator.
bool operator< (TypeId a, TypeId b)
Comparison operator.
Related Functions
(Note that these are not member functions.)
std::ostream & operator<< (std::ostream &os, TypeId tid)
std::istream & operator>> (std::istream &is, TypeId &tid)
Detailed Description
a unique identifier for an interface.
This class records a lot of meta-information about a subclass of the Object base class:
the base class of the subclass
the set of accessible constructors in the subclass
the set of 'attributes' accessible in the subclass
See also
attribute_TypeId
Internal:
See the discussion in IidManager about hash chaining of TypeId's.
Definition at line 58 of file type-id.h.
Member Typedef Documentation
hash_t
typedef uint32_t ns3::TypeId::hash_t
Type of hash values.
Definition at line 116 of file type-id.h.
Member Enumeration Documentation
AttributeFlag
enum ns3::TypeId::AttributeFlag
Flags describing when a given attribute can be read or written.
Enumerator
ATTR_GET
The attribute can be read.
ATTR_SET
The attribute can be written.
ATTR_CONSTRUCT
The attribute can be written at construction-time.
ATTR_SGC
The attribute can be read, and written at any time.
Definition at line 62 of file type-id.h.
SupportLevel
enum ns3::TypeId::SupportLevel
The level of support or deprecation for attributes or trace sources.
Enumerator
SUPPORTED
Attribute or trace source is currently used.
DEPRECATED
Attribute or trace source is deprecated; user is warned.
OBSOLETE
Attribute or trace source is not used anymore; simulation fails.
Definition at line 70 of file type-id.h.
Constructor & Destructor Documentation
TypeId() [1/4]
ns3::TypeId::TypeId (const char * name) explicit
Constructor.
Parameters
[in] name The name of the interface to construct.
No two instances can share the same name. The name is expected to be the full c++ typename of associated c++ object.
Definition at line 814 of file type-id.cc.
References ns3::IidManager::AllocateUid(), ns3::Singleton< IidManager >::Get(), m_tid, NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_LOGIC().
TypeId() [2/4]
ns3::TypeId::TypeId () inline
Default constructor.
This produces an invalid TypeId.
Definition at line 617 of file type-id.h.
Referenced by GetParent(), GetRegistered(), LookupByHash(), LookupByHashFailSafe(), LookupByName(), and LookupByNameFailSafe().
TypeId() [3/4]
ns3::TypeId::TypeId (const TypeId & o) inline
Copy constructor.
Parameters
[in] o The other TypeId.
Definition at line 620 of file type-id.h.
~TypeId()
ns3::TypeId::~TypeId () inline
Destructor.
Definition at line 628 of file type-id.h.
TypeId() [4/4]
ns3::TypeId::TypeId (uint16_t tid) explicit private
Construct from an integer value.
Parameters
[in] tid The TypeId value as an integer.
Definition at line 824 of file type-id.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddAttribute() [1/2]
TypeId ns3::TypeId::AddAttribute (std::string name, std::string help, const AttributeValue & initialValue, Ptr< const AttributeAccessor > accessor, Ptr< const AttributeChecker > checker, SupportLevel supportLevel = SUPPORTED, const std::string & supportMsg = "")
Record in this TypeId the fact that a new attribute exists.
Parameters
[in] name The name of the new attribute
[in] help Some help text which describes the purpose of this attribute.
[in] initialValue The initial value for this attribute.
[in] accessor An instance of the associated AttributeAccessor subclass.
[in] checker An instance of the associated AttributeChecker subclass.
[in] supportLevel Support/deprecation status of the attribute.
[in] supportMsg Upgrade hint if this attribute is no longer supported. If the attribute is DEPRECATED the attribute behavior still exists, but user code should be updated following guidance in the hint. If the attribute is OBSOLETE, the hint should indicate which class the attribute functional has been moved to, or that the functionality is no longer supported. See test file type-id-test-suite.cc for examples.
Returns
This TypeId instance
Definition at line 1014 of file type-id.cc.
References ns3::IidManager::AddAttribute(), ATTR_SGC, ns3::AttributeValue::Copy(), ns3::Singleton< IidManager >::Get(), m_tid, and NS_LOG_FUNCTION.
Referenced by ns3::Ns3NscStack::GetInstanceTypeId().
AddAttribute() [2/2]
TypeId ns3::TypeId::AddAttribute (std::string name, std::string help, uint32_t flags, const AttributeValue & initialValue, Ptr< const AttributeAccessor > accessor, Ptr< const AttributeChecker > checker, SupportLevel supportLevel = SUPPORTED, const std::string & supportMsg = "")
Record in this TypeId the fact that a new attribute exists.
Parameters
[in] name The name of the new attribute
[in] help Some help text which describes the purpose of this attribute
[in] flags Flags which describe how this attribute can be read and/or written.
[in] initialValue The initial value for this attribute.
[in] accessor An instance of the associated AttributeAccessor subclass.
[in] checker An instance of the associated AttributeChecker subclass.
[in] supportLevel Support/deprecation status of the attribute.
[in] supportMsg Upgrade hint if this attribute is no longer supported. If the attribute is DEPRECATED the attribute behavior still exists, but user code should be updated following guidance in the hint.. If the attribute is OBSOLETE, the hint should indicate which class the attribute functional has been moved to, or that the functionality is no longer supported.
Returns
This TypeId instance
Definition at line 1032 of file type-id.cc.
References ns3::IidManager::AddAttribute(), ns3::AttributeValue::Copy(), ns3::Singleton< IidManager >::Get(), m_tid, and NS_LOG_FUNCTION.
AddConstructor()
template<typename T > TypeId ns3::TypeId::AddConstructor (void)
Record in this TypeId the fact that the default constructor is accessible.
Template Parameters
T [explicit] The class name represented by this TypeId.
Returns
This TypeId instance
Definition at line 654 of file type-id.h.
Referenced by ns3::dsr::DsrFsHeader::GetTypeId(), ns3::dsr::DsrRoutingHeader::GetTypeId(), ns3::dsr::DsrOptionHeader::GetTypeId(), ns3::dsr::DsrOptionPad1Header::GetTypeId(), ns3::dsr::DsrOptionPadnHeader::GetTypeId(), ns3::dsr::DsrOptionRreqHeader::GetTypeId(), ns3::dsr::DsrOptionRrepHeader::GetTypeId(), ns3::dsr::DsrOptionSRHeader::GetTypeId(), ns3::dsr::DsrOptionRerrHeader::GetTypeId(), ns3::dsr::DsrOptionRerrUnreachHeader::GetTypeId(), ns3::dsr::DsrOptionRerrUnsupportHeader::GetTypeId(), ns3::dsr::DsrOptionAckReqHeader::GetTypeId(), ns3::dsr::DsrOptionAckHeader::GetTypeId(), ns3::Ipv6ExtensionHeader::GetTypeId(), ns3::Ipv6ExtensionHopByHopHeader::GetTypeId(), ns3::Ipv6ExtensionDestinationHeader::GetTypeId(), ns3::Ipv6ExtensionFragmentHeader::GetTypeId(), ns3::Ipv6ExtensionRoutingHeader::GetTypeId(), ns3::Ipv6ExtensionLooseRoutingHeader::GetTypeId(), ns3::Ipv6ExtensionESPHeader::GetTypeId(), ns3::Ipv6ExtensionAHHeader::GetTypeId(), ns3::Ipv6OptionHeader::GetTypeId(), ns3::Ipv6OptionPad1Header::GetTypeId(), ns3::Ipv6OptionPadnHeader::GetTypeId(), ns3::Ipv6OptionJumbogramHeader::GetTypeId(), ns3::Ipv6OptionRouterAlertHeader::GetTypeId(), Derived::GetTypeId(), AttributeObjectTest::GetTypeId(), anonymous_namespace{object-test-suite.cc}::BaseA::GetTypeId(), anonymous_namespace{object-test-suite.cc}::BaseB::GetTypeId(), ns3::lorawan::AdrComponent::GetTypeId(), ns3::lorawan::GatewayStatus::GetTypeId(), ns3::lorawan::NetworkController::GetTypeId(), and ns3::lorawan::NetworkStatus::GetTypeId().
AddTraceSource() [1/2]
TypeId ns3::TypeId::AddTraceSource (std::string name, std::string help, Ptr< const TraceSourceAccessor > accessor)
Record a new TraceSource.
Parameters
[in] name The name of the new trace source
[in] help Some help text which describes the purpose of this trace source.
[in] accessor A pointer to a TraceSourceAccessor which can be used to connect/disconnect sinks to this trace source.
Returns
this TypeId instance.
Deprecated:
Definition at line 1111 of file type-id.cc.
AddTraceSource() [2/2]
TypeId ns3::TypeId::AddTraceSource (std::string name, std::string help, Ptr< const TraceSourceAccessor > accessor, std::string callback, SupportLevel supportLevel = SUPPORTED, const std::string & supportMsg = "")
Record a new TraceSource.
Parameters
[in] name The name of the new trace source
[in] help Some help text which describes the purpose of this trace source.
[in] accessor A pointer to a TraceSourceAccessor which can be used to connect/disconnect sinks to this trace source.
[in] callback Fully qualified typedef name for the callback signature. Generally this should begin with the "ns3::" namespace qualifier.
[in] supportLevel Support/deprecation status of the attribute.
[in] supportMsg Upgrade hint if this attribute is no longer supported. If the attribute is DEPRECATED the attribute behavior still exists, but user code should be updated following guidance in the hint.. If the attribute is OBSOLETE, the hint should indicate which class the attribute functional has been moved to, or that the functionality is no longer supported. See test file type-id-test-suite.cc for examples.
Returns
This TypeId instance.
Definition at line 1119 of file type-id.cc.
References ns3::IidManager::AddTraceSource(), ns3::Singleton< IidManager >::Get(), m_tid, and NS_LOG_FUNCTION.
DoAddConstructor()
void ns3::TypeId::DoAddConstructor (Callback< ObjectBase * > callback) private
Implementation for AddConstructor().
Parameters
[in] callback Callback which constructs an instance of this TypeId.
Definition at line 1007 of file type-id.cc.
References ns3::IidManager::AddConstructor(), ns3::Singleton< IidManager >::Get(), m_tid, and NS_LOG_FUNCTION.
GetAttribute()
struct TypeId::AttributeInformation ns3::TypeId::GetAttribute (std::size_t i) const
Get Attribute information by index.
Parameters
[in] i Index into attribute array
Returns
The information associated to attribute whose index is i.
Definition at line 1077 of file type-id.cc.
Referenced by ns3::cell_tooltip_callback(), ns3::cell_tooltip_callback_config_default(), ns3::ObjectBase::ConstructSelf(), StaticInformation::DoGather(), ns3::AttributeIterator::DoIterate(), ns3::Config::Resolver::DoResolve(), GetAttributeFullName(), ns3::AttributeDefaultIterator::Iterate(), LookupAttributeByName(), PrintAllAttributes(), ns3::CommandLine::PrintAttributes(), PrintAttributesTid(), ns3::Config::Reset(), ns3::Config::SetDefaultFailSafe(), and ns3::ThreeGppHttpServer::StartApplication().
GetAttributeFullName()
std::string ns3::TypeId::GetAttributeFullName (std::size_t i) const
Get the Attribute name by index.
Parameters
[in] i Index into attribute array
Returns
The full name associated to the attribute whose index is i.
Definition at line 1090 of file type-id.cc.
References GetAttribute(), GetName(), ns3::TypeId::AttributeInformation::name, and NS_LOG_FUNCTION.
Referenced by ns3::cell_edited_callback_config_default(), ns3::ObjectBase::ConstructSelf(), and ns3::CommandLine::PrintAttributes().
GetAttributeN()
std::size_t ns3::TypeId::GetAttributeN (void) const
Get the number of attributes.
Returns
The number of attributes associated to this TypeId
Definition at line 1077 of file type-id.cc.
References ns3::Singleton< IidManager >::Get(), ns3::IidManager::GetAttributeN(), m_tid, sample-rng-plot::n, and NS_LOG_FUNCTION.
Referenced by ns3::cell_tooltip_callback(), ns3::ObjectBase::ConstructSelf(), StaticInformation::DoGather(), ns3::AttributeIterator::DoIterate(), ns3::Config::Resolver::DoResolve(), ns3::AttributeDefaultIterator::Iterate(), LookupAttributeByName(), ns3::Packet::Print(), PrintAllAttributes(), ns3::CommandLine::PrintAttributes(), PrintAttributes(), PrintAttributesTid(), ns3::Config::Reset(), ns3::Config::SetDefaultFailSafe(), and ns3::ThreeGppHttpServer::StartApplication().
GetConstructor()
Callback< ObjectBase * > ns3::TypeId::GetConstructor (void) const
Get the constructor callback.
Returns
A callback which can be used to instantiate an object of this type.
Definition at line 1061 of file type-id.cc.
References ns3::Singleton< IidManager >::Get(), ns3::IidManager::GetConstructor(), m_tid, and NS_LOG_FUNCTION.
Referenced by PacketMetadataTest::CheckHistory(), ns3::ObjectFactory::Create(), PacketTest::DoCheck(), Ipv4FragmentationTest::DoRun(), Ipv6FragmentationTest::DoRun(), ns3::Packet::Print(), ns3::Packet::PrintByteTags(), and ns3::Packet::PrintPacketTags().
GetGroupName()
std::string ns3::TypeId::GetGroupName (void) const
Get the group name.
Returns
The name of the group associated to this TypeId.
Definition at line 969 of file type-id.cc.
References ns3::Singleton< IidManager >::Get(), ns3::IidManager::GetGroupName(), m_tid, and NS_LOG_FUNCTION.
Referenced by ns3::CommandLine::PrintGroup(), and ns3::CommandLine::PrintGroups().
GetHash()
TypeId::hash_t ns3::TypeId::GetHash (void) const
Get the hash.
Returns
The hash of this interface.
Definition at line 985 of file type-id.cc.
References ns3::Singleton< IidManager >::Get(), ns3::IidManager::GetHash(), and m_tid.
Referenced by UniqueTypeIdTestCase::DoRun(), CollisionTestCase::DoRun(), and LookupTimeTestCase::DoRun().
GetName()
std::string ns3::TypeId::GetName (void) const
Get the name.
Returns
The name of this interface.
Definition at line 977 of file type-id.cc.
References ns3::Singleton< IidManager >::Get(), ns3::IidManager::GetName(), m_tid, and NS_LOG_FUNCTION.
Referenced by ns3::Packet::AddByteTag(), ns3::Packet::AddHeader(), ns3::Packet::AddPacketTag(), ns3::Packet::AddTrailer(), ns3::cell_data_function_col_0(), ns3::cell_data_function_col_0_config_default(), ns3::cell_tooltip_callback(), ns3::cell_tooltip_callback_config_default(), ns3::ObjectBase::ConstructSelf(), ns3::lorawan::LoraPhyHelper::Create(), ns3::TcpL4Protocol::CreateSocket(), PacketTest::DoCheck(), StaticInformation::DoGather(), ns3::AttributeIterator::DoIterate(), UniqueTypeIdTestCase::DoRun(), LookupTimeTestCase::DoRun(), Ipv4FragmentationTest::DoRun(), Ipv6FragmentationTest::DoRun(), GetAttributeFullName(), ns3::LteHelper::GetEnbComponentCarrierManagerType(), ns3::LteHelper::GetFfrAlgorithmType(), ns3::LteHelper::GetHandoverAlgorithmType(), ns3::MobilityHelper::GetMobilityModelType(), GetNameMap(), ns3::LteHelper::GetSchedulerType(), ns3::PacketMetadata::GetSerializedSize(), ns3::LteHelper::GetUeComponentCarrierManagerType(), ns3::MobilityHelper::Install(), ns3::AttributeDefaultIterator::Iterate(), ns3::operator<<(), ns3::Packet::PeekHeader(), ns3::Packet::PeekTrailer(), ns3::Packet::Print(), PrintAllAttributes(), PrintAllTraceSources(), PrintAllTypeIds(), ns3::CommandLine::PrintAttributes(), PrintAttributes(), PrintAttributesTid(), ns3::Packet::PrintByteTags(), PrintConfigPaths(), ns3::CommandLine::PrintGroup(), PrintTraceSources(), PrintTypeIdBlocks(), ns3::CommandLine::PrintTypeIds(), ns3::Packet::RemoveHeader(), ns3::Packet::RemovePacketTag(), ns3::Packet::RemoveTrailer(), ns3::Packet::ReplacePacketTag(), ns3::PacketMetadata::Serialize(), ns3::ObjectFactory::Set(), ns3::ObjectFactory::SetTypeId(), ns3::AttributeIterator::StartVisitArrayItem(), ns3::AttributeIterator::StartVisitObject(), and ns3::AttributeIterator::StartVisitPointerAttribute().
GetParent()
TypeId ns3::TypeId::GetParent (void) const
Get the parent of this TypeId.
Returns
The parent of this TypeId
This method cannot fail. It will return itself if this TypeId has no parent. i.e., it is at the top of the TypeId hierarchy. Currently, this is the case for the TypeId associated to the ns3::ObjectBase class only.
Definition at line 944 of file type-id.cc.
References TypeId(), ns3::Singleton< IidManager >::Get(), ns3::IidManager::GetParent(), m_tid, and NS_LOG_FUNCTION.
Referenced by ns3::cell_tooltip_callback(), ns3::ObjectBase::ConstructSelf(), ns3::Object::DoGetObject(), ns3::AttributeIterator::DoIterate(), ns3::Config::Resolver::DoResolve(), IsChildOf(), LookupAttributeByName(), LookupTraceSourceByName(), PrintAttributes(), and PrintTraceSources().
GetRegistered()
TypeId ns3::TypeId::GetRegistered (uint16_t i) static
Get a TypeId by index.
Parameters
[in] i Index of the TypeId.
Returns
The TypeId instance whose index is i.
Definition at line 876 of file type-id.cc.
References TypeId(), ns3::Singleton< IidManager >::Get(), and NS_LOG_FUNCTION.
Referenced by StaticInformation::DoGather(), GetNameMap(), ns3::AttributeDefaultIterator::Iterate(), PrintAllAttributes(), PrintAllTraceSources(), PrintAllTypeIds(), ns3::CommandLine::PrintGroup(), ns3::CommandLine::PrintGroups(), PrintTypeIdBlocks(), ns3::CommandLine::PrintTypeIds(), and ns3::Config::Reset().
GetRegisteredN()
uint16_t ns3::TypeId::GetRegisteredN (void) static
Get the number of registered TypeIds.
Returns
The number of TypeId instances registered.
Definition at line 870 of file type-id.cc.
References ns3::Singleton< IidManager >::Get(), ns3::IidManager::GetRegisteredN(), and NS_LOG_FUNCTION_NOARGS.
Referenced by StaticInformation::DoGather(), GetNameMap(), ns3::AttributeDefaultIterator::Iterate(), ns3::CommandLine::PrintGroup(), ns3::CommandLine::PrintGroups(), ns3::CommandLine::PrintTypeIds(), and ns3::Config::Reset().
GetSize()
std::size_t ns3::TypeId::GetSize (void) const
Get the size of this object.
Returns
The size of this interface.
Definition at line 991 of file type-id.cc.
References ns3::Singleton< IidManager >::Get(), ns3::IidManager::GetSize(), m_tid, and NS_LOG_FUNCTION.
Referenced by PrintSize().
GetTraceSource()
struct TypeId::TraceSourceInformation ns3::TypeId::GetTraceSource (std::size_t i) const
Get the trace source by index.
Parameters
[in] i Index into trace source array.
Returns
Detailed information about the requested trace source.
Definition at line 1098 of file type-id.cc.
Referenced by LookupTraceSourceByName(), PrintAllTraceSources(), and PrintTraceSourcesTid().
GetTraceSourceN()
std::size_t ns3::TypeId::GetTraceSourceN (void) const
Get the number of Trace sources.
Returns
The number of trace sources defined in this TypeId.
Definition at line 1098 of file type-id.cc.
References ns3::Singleton< IidManager >::Get(), ns3::IidManager::GetTraceSourceN(), m_tid, and NS_LOG_FUNCTION.
Referenced by LookupTraceSourceByName(), PrintAllTraceSources(), PrintTraceSources(), and PrintTraceSourcesTid().
GetUid()
uint16_t ns3::TypeId::GetUid (void) const
Get the internal id of this TypeId.
Returns
The internal integer which uniquely identifies this TypeId.
This is really an internal method which users are not expected to use.
Definition at line 1193 of file type-id.cc.
References m_tid, and NS_LOG_FUNCTION.
Referenced by ns3::ByteTagList::Add(), ns3::PacketMetadata::AddHeader(), ns3::PacketMetadata::AddTrailer(), ns3::PacketMetadata::Deserialize(), ns3::lorawan::LoraRadioEnergyModelHelper::DoInstall(), ns3::WifiRadioEnergyModelHelper::DoInstall(), UniqueTypeIdTestCase::DoRun(), DeprecatedAttributeTestCase::DoRun(), ns3::TrafficControlHelper::Install(), IsChildOf(), ns3::ObjectFactory::IsTypeIdSet(), LookupByNameFailSafe(), ns3::PacketMetadata::RemoveHeader(), ns3::PacketMetadata::RemoveTrailer(), and SetParent().
HasConstructor()
bool ns3::TypeId::HasConstructor (void) const
Check if this TypeId has a constructor.
Returns
true if this TypeId has a constructor
Definition at line 999 of file type-id.cc.
References ns3::Singleton< IidManager >::Get(), ns3::IidManager::HasConstructor(), m_tid, and NS_LOG_FUNCTION.
Referenced by ns3::Packet::Print(), and ns3::Packet::PrintPacketTags().
HasParent()
bool ns3::TypeId::HasParent (void) const
Check if this TypeId has a parent.
Returns
true if this TypeId has a parent.
Definition at line 951 of file type-id.cc.
References ns3::Singleton< IidManager >::Get(), ns3::IidManager::GetParent(), m_tid, and NS_LOG_FUNCTION.
Referenced by ns3::cell_tooltip_callback(), and ns3::AttributeIterator::DoIterate().
HideFromDocumentation()
TypeId ns3::TypeId::HideFromDocumentation (void)
Hide this TypeId from documentation.
Returns
This TypeId instance.
Definition at line 1136 of file type-id.cc.
References ns3::Singleton< IidManager >::Get(), ns3::IidManager::HideFromDocumentation(), m_tid, and NS_LOG_FUNCTION.
Referenced by anonymous_namespace{object-test-suite.cc}::BaseA::GetTypeId(), and anonymous_namespace{object-test-suite.cc}::BaseB::GetTypeId().
IsChildOf()
bool ns3::TypeId::IsChildOf (TypeId other) const
Check if this TypeId is a child of another.
Parameters
[in] other A parent TypeId
Returns
true if the input TypeId is really a parent of this TypeId.
Calling this method is roughly similar to calling dynamic_cast except that you do not need object instances: you can do the check with TypeId instances instead.
Definition at line 958 of file type-id.cc.
References GetParent(), GetUid(), and NS_LOG_FUNCTION.
Referenced by StaticInformation::DoGather(), and ns3::PacketMetadata::ItemIterator::Next().
LookupAttributeByName()
bool ns3::TypeId::LookupAttributeByName (std::string name, struct AttributeInformation * info) const
Find an Attribute by name, retrieving the associated AttributeInformation.
Parameters
[in] name The name of the requested attribute
[in,out] info A pointer to the TypeId::AttributeInformation data structure where the result value of this method will be stored.
Returns
true if the requested attribute could be found.
Definition at line 883 of file type-id.cc.
References DEPRECATED, GetAttribute(), GetAttributeN(), GetParent(), ns3::TypeId::AttributeInformation::name, NS_FATAL_ERROR, NS_LOG_FUNCTION, OBSOLETE, SUPPORTED, ns3::TypeId::AttributeInformation::supportLevel, and ns3::TypeId::AttributeInformation::supportMsg.
Referenced by ns3::CommandLine::AddValue(), DeprecatedAttributeTestCase::DoRun(), ns3::operator>>(), and ns3::ObjectFactory::Set().
LookupByHash()
TypeId ns3::TypeId::LookupByHash (hash_t hash) static
Get a TypeId by hash.
Parameters
[in] hash The hash to lookup
Returns
The unique id associated with the requested hash.
This method cannot fail: it will crash if the input hash does not match an existing TypeId.
Definition at line 850 of file type-id.cc.
References TypeId(), ns3::Singleton< IidManager >::Get(), ns3::IidManager::GetUid(), and NS_ASSERT_MSG().
LookupByHashFailSafe()
bool ns3::TypeId::LookupByHashFailSafe (hash_t hash, TypeId * tid) static
Get a TypeId by hash.
Parameters
[in] hash The hash of the requested TypeId
[out] tid A pointer to the TypeId instance where the result of this function should be stored.
Returns
true if the requested hash was found.
Definition at line 858 of file type-id.cc.
References TypeId(), ns3::Singleton< IidManager >::Get(), and ns3::IidManager::GetUid().
LookupByName()
TypeId ns3::TypeId::LookupByName (std::string name) static
Get a TypeId by name.
Parameters
[in] name The name of the requested TypeId
Returns
The unique id associated with the requested name.
This method cannot fail: it will crash if the input name is not a valid TypeId name.
Definition at line 830 of file type-id.cc.
References TypeId(), ns3::Singleton< IidManager >::Get(), ns3::IidManager::GetUid(), NS_ASSERT_MSG(), and NS_LOG_FUNCTION.
Referenced by ns3::NoBackhaulEpcHelper::NoBackhaulEpcHelper(), Tunnel::Tunnel(), ns3::NoBackhaulEpcHelper::AddEnb(), ns3::NoBackhaulEpcHelper::AddS1Interface(), ns3::EpcX2::AddX2Interface(), ns3::olsr::Bug780Test::CreateNodes(), ns3::PacketMetadata::Deserialize(), ns3::Rip::DoInitialize(), ns3::RipNg::DoInitialize(), ns3::Config::Resolver::DoResolve(), ns3::lorawan::LoraHelper::Install(), ns3::Rip::NotifyInterfaceUp(), ns3::RipNg::NotifyInterfaceUp(), ns3::PyViz::RegisterCsmaLikeDevice(), ns3::PyViz::RegisterPointToPointLikeDevice(), ns3::PyViz::RegisterWifiLikeDevice(), RunSimulation(), ns3::ObjectFactory::SetTypeId(), UanExperiment::SetupApplications(), SetupPacketReceive(), ns3::Ping6::StartApplication(), ns3::Radvd::StartApplication(), ns3::UdpClient::StartApplication(), ns3::UdpEchoClient::StartApplication(), ns3::UdpEchoServer::StartApplication(), ns3::UdpServer::StartApplication(), ns3::UdpTraceClient::StartApplication(), ns3::DhcpClient::StartApplication(), ns3::DhcpServer::StartApplication(), ns3::V4Ping::StartApplication(), ns3::V4TraceRoute::StartApplication(), ns3::PacketSocketClient::StartApplication(), ns3::PacketSocketServer::StartApplication(), ns3::BsmApplication::StartApplication(), and ns3::ModelTypeidCreator::StartVisitTypeId().
LookupByNameFailSafe()
bool ns3::TypeId::LookupByNameFailSafe (std::string name, TypeId * tid) static
Get a TypeId by name.
Parameters
[in] name The name of the requested TypeId
[out] tid A pointer to the TypeId instance where the result of this function should be stored.
Returns
true if the requested name was found.
Definition at line 838 of file type-id.cc.
References TypeId(), ns3::Singleton< IidManager >::Get(), ns3::IidManager::GetUid(), GetUid(), and NS_LOG_FUNCTION.
Referenced by ns3::CommandLine::AddValue(), ns3::Ns3NscStack::GetInstanceTypeId(), ns3::operator>>(), ns3::CommandLine::PrintAttributes(), StaticInformation::RecordAggregationInfo(), and ns3::Config::SetDefaultFailSafe().
LookupTraceSourceByName() [1/2]
Ptr< const TraceSourceAccessor > ns3::TypeId::LookupTraceSourceByName (std::string name) const
Find a TraceSource by name.
If no matching trace source is found, this method returns zero.
Parameters
[in] name The name of the requested trace source
Returns
The trace source accessor which can be used to connect and disconnect trace sinks with the requested trace source on an object instance.
Definition at line 1186 of file type-id.cc.
Referenced by DeprecatedAttributeTestCase::DoRun(), ns3::ObjectBase::TraceConnect(), ns3::ObjectBase::TraceConnectWithoutContext(), ns3::ObjectBase::TraceDisconnect(), and ns3::ObjectBase::TraceDisconnectWithoutContext().
LookupTraceSourceByName() [2/2]
Ptr< const TraceSourceAccessor > ns3::TypeId::LookupTraceSourceByName (std::string name, struct TraceSourceInformation * info) const
Find a TraceSource by name, retrieving the associated TraceSourceInformation.
Parameters
[in] name The name of the requested trace source.
[out] info A pointer to the TypeId::TraceSourceInformation data structure where the result value of this method will be stored.
Returns
The trace source accessor which can be used to connect and disconnect trace sinks with the requested trace source on an object instance.
Definition at line 1144 of file type-id.cc.
References ns3::TypeId::TraceSourceInformation::accessor, DEPRECATED, GetParent(), GetTraceSource(), GetTraceSourceN(), ns3::TypeId::TraceSourceInformation::name, NS_FATAL_ERROR, NS_LOG_FUNCTION, OBSOLETE, SUPPORTED, ns3::TypeId::TraceSourceInformation::supportLevel, and ns3::TypeId::TraceSourceInformation::supportMsg.
MustHideFromDocumentation()
bool ns3::TypeId::MustHideFromDocumentation (void) const
Check if this TypeId should not be listed in documentation.
Returns
true if this TypeId should be hidden from the user.
Definition at line 1069 of file type-id.cc.
References ns3::Singleton< IidManager >::Get(), m_tid, ns3::IidManager::MustHideFromDocumentation(), and NS_LOG_FUNCTION.
Referenced by GetNameMap(), and ns3::AttributeDefaultIterator::Iterate().
operator=()
TypeId & ns3::TypeId::operator= (const TypeId & o) inline
Assignment.
Parameters
[in] o The other TypeId.
Returns
The copied TypeId.
Definition at line 623 of file type-id.h.
SetAttributeInitialValue()
bool ns3::TypeId::SetAttributeInitialValue (std::size_t i, Ptr< const AttributeValue > initialValue)
Set the initial value of an Attribute.
Parameters
[in] i The attribute to manipulate
[in] initialValue The new initial value to use for this attribute.
Returns
true if the call was successfully.
Definition at line 1051 of file type-id.cc.
References ns3::Singleton< IidManager >::Get(), m_tid, NS_LOG_FUNCTION, and ns3::IidManager::SetAttributeInitialValue().
Referenced by ns3::Config::Reset(), and ns3::Config::SetDefaultFailSafe().
SetGroupName()
TypeId ns3::TypeId::SetGroupName (std::string groupName)
Set the group name.
Parameters
[in] groupName The name of the group this TypeId belongs to.
Returns
This TypeId instance.
The group name is purely an advisory information used to group together types according to a user-specific grouping scheme.
Definition at line 930 of file type-id.cc.
References ns3::Singleton< IidManager >::Get(), m_tid, NS_LOG_FUNCTION, and ns3::IidManager::SetGroupName().
Referenced by ns3::ObjectBase::GetObjectIid(), and ns3::lorawan::AdrComponent::GetTypeId().
SetParent() [1/2]
TypeId ns3::TypeId::SetParent (TypeId tid)
Set the parent TypeId.
Parameters
[in] tid The TypeId of the base class.
Returns
This TypeId instance.
Record in this TypeId which TypeId is the TypeId of the base class of the subclass.
Definition at line 923 of file type-id.cc.
References ns3::Singleton< IidManager >::Get(), GetUid(), m_tid, NS_LOG_FUNCTION, and ns3::IidManager::SetParent().
Referenced by ns3::Ns3NscStack::GetInstanceTypeId(), ns3::ObjectBase::GetObjectIid(), ns3::AntennaModel::GetTypeId(), ns3::CosineAntennaModel::GetTypeId(), ns3::IsotropicAntennaModel::GetTypeId(), ns3::ParabolicAntennaModel::GetTypeId(), ns3::aodv::TypeHeader::GetTypeId(), ns3::aodv::RreqHeader::GetTypeId(), ns3::aodv::RrepHeader::GetTypeId(), ns3::aodv::RrepAckHeader::GetTypeId(), ns3::aodv::RerrHeader::GetTypeId(), ns3::aodv::DeferredRouteOutputTag::GetTypeId(), ns3::ApplicationPacketProbe::GetTypeId(), ns3::ThreeGppHttpClient::GetTypeId(), ns3::ThreeGppHttpHeader::GetTypeId(), ns3::ThreeGppHttpServer::GetTypeId(), ns3::ThreeGppHttpVariables::GetTypeId(), ns3::dsdv::DeferredRouteOutputTag::GetTypeId(), ns3::dsr::DsrGraReply::GetTypeId(), ns3::dsr::DsrOptionPad1::GetTypeId(), ns3::dsr::DsrOptionPadn::GetTypeId(), ns3::dsr::DsrOptionRreq::GetTypeId(), ns3::dsr::DsrOptionRrep::GetTypeId(), ns3::dsr::DsrOptionSR::GetTypeId(), ns3::dsr::DsrOptionRerr::GetTypeId(), ns3::dsr::DsrOptionAckReq::GetTypeId(), ns3::dsr::DsrOptionAck::GetTypeId(), ns3::dsr::DsrPassiveBuffer::GetTypeId(), ns3::dsr::DsrRouteCache::GetTypeId(), ns3::dsr::DsrRouting::GetTypeId(), ns3::dsr::DsrRreqTable::GetTypeId(), ns3::FlowMonitor::GetTypeId(), ns3::Ping6::GetTypeId(), ns3::Icmpv6Header::GetTypeId(), ns3::Icmpv6OptionHeader::GetTypeId(), ns3::Icmpv6NS::GetTypeId(), ns3::Icmpv6NA::GetTypeId(), ns3::Icmpv6RA::GetTypeId(), ns3::Icmpv6RS::GetTypeId(), ns3::Icmpv6Redirection::GetTypeId(), ns3::Icmpv6Echo::GetTypeId(), ns3::Icmpv6DestinationUnreachable::GetTypeId(), ns3::Icmpv6TooBig::GetTypeId(), ns3::Icmpv6TimeExceeded::GetTypeId(), ns3::Icmpv6ParameterError::GetTypeId(), ns3::Icmpv6OptionMtu::GetTypeId(), ns3::Icmpv6OptionPrefixInformation::GetTypeId(), ns3::Icmpv6OptionLinkLayerAddress::GetTypeId(), ns3::Icmpv6OptionRedirected::GetTypeId(), ns3::Icmpv6L4Protocol::GetTypeId(), ns3::Ipv4PacketProbe::GetTypeId(), ns3::Ipv6Extension::GetTypeId(), ns3::Ipv6ExtensionHopByHop::GetTypeId(), ns3::Ipv6ExtensionDestination::GetTypeId(), ns3::Ipv6ExtensionFragment::GetTypeId(), ns3::Ipv6ExtensionRouting::GetTypeId(), ns3::Ipv6ExtensionRoutingDemux::GetTypeId(), ns3::Ipv6ExtensionLooseRouting::GetTypeId(), ns3::Ipv6ExtensionESP::GetTypeId(), ns3::Ipv6ExtensionAH::GetTypeId(), ns3::Ipv6Interface::GetTypeId(), ns3::Ipv6L3Protocol::GetTypeId(), ns3::Ipv6Option::GetTypeId(), ns3::Ipv6OptionPad1::GetTypeId(), ns3::Ipv6OptionPadn::GetTypeId(), ns3::Ipv6OptionJumbogram::GetTypeId(), ns3::Ipv6OptionRouterAlert::GetTypeId(), ns3::Ipv6PacketProbe::GetTypeId(), ns3::Ipv6PmtuCache::GetTypeId(), ns3::Ipv6RawSocketImpl::GetTypeId(), ns3::Ipv6StaticRouting::GetTypeId(), ns3::NdiscCache::GetTypeId(), IPv4TestTag::GetTypeId(), IPv6TestTag::GetTypeId(), ns3::A2A4RsrqHandoverAlgorithm::GetTypeId(), ns3::A3RsrpHandoverAlgorithm::GetTypeId(), ns3::LteAnr::GetTypeId(), ns3::LteEnbComponentCarrierManager::GetTypeId(), ns3::LteFfrAlgorithm::GetTypeId(), ns3::LteFfrDistributedAlgorithm::GetTypeId(), ns3::LteFfrEnhancedAlgorithm::GetTypeId(), ns3::LteFfrSoftAlgorithm::GetTypeId(), ns3::LteFrHardAlgorithm::GetTypeId(), ns3::LteFrNoOpAlgorithm::GetTypeId(), ns3::LteFrSoftAlgorithm::GetTypeId(), ns3::LteFrStrictAlgorithm::GetTypeId(), ns3::LteHandoverAlgorithm::GetTypeId(), ns3::LteUeComponentCarrierManager::GetTypeId(), ns3::NoOpComponentCarrierManager::GetTypeId(), ns3::RrComponentCarrierManager::GetTypeId(), ns3::NoOpHandoverAlgorithm::GetTypeId(), ns3::SimpleUeComponentCarrierManager::GetTypeId(), ns3::LteFfrSimple::GetTypeId(), ns3::Dot11sStack::GetTypeId(), ns3::FlameStack::GetTypeId(), ns3::dot11s::AirtimeLinkMetricCalculator::GetTypeId(), ns3::dot11s::MeshHeader::GetTypeId(), ns3::dot11s::HwmpProtocol::GetTypeId(), ns3::dot11s::HwmpRtable::GetTypeId(), ns3::dot11s::HwmpTag::GetTypeId(), ns3::dot11s::PeerLinkOpenStart::GetTypeId(), ns3::dot11s::PeerLinkCloseStart::GetTypeId(), ns3::dot11s::PeerLinkConfirmStart::GetTypeId(), ns3::dot11s::PeerLink::GetTypeId(), ns3::dot11s::PeerManagementProtocol::GetTypeId(), ns3::flame::FlameTag::GetTypeId(), ns3::flame::FlameProtocol::GetTypeId(), ns3::flame::FlameRtable::GetTypeId(), ns3::MeshInformationElementVector::GetTypeId(), ns3::MeshL2RoutingProtocol::GetTypeId(), ns3::MeshPointDevice::GetTypeId(), ns3::MeshWifiInterfaceMac::GetTypeId(), ns3::PacketProbe::GetTypeId(), ns3::JakesPropagationLossModel::GetTypeId(), ns3::ConstantSpectrumPropagationLossModel::GetTypeId(), ns3::FriisSpectrumPropagationLossModel::GetTypeId(), ns3::SpectrumErrorModel::GetTypeId(), ns3::SpectrumPropagationLossModel::GetTypeId(), ns3::ThreeGppChannelModel::GetTypeId(), ns3::ThreeGppSpectrumPropagationLossModel::GetTypeId(), ns3::TraceFadingLossModel::GetTypeId(), ns3::BooleanProbe::GetTypeId(), ns3::DataCollectionObject::GetTypeId(), ns3::DoubleProbe::GetTypeId(), ns3::FileAggregator::GetTypeId(), ns3::GnuplotAggregator::GetTypeId(), ns3::Probe::GetTypeId(), ns3::TimeProbe::GetTypeId(), ns3::Uinteger16Probe::GetTypeId(), ns3::Uinteger32Probe::GetTypeId(), ns3::Uinteger8Probe::GetTypeId(), ns3::UanPhyDual::GetTypeId(), ns3::WifiInformationElementVector::GetTypeId(), Sender::GetTypeId(), Receiver::GetTypeId(), TimestampTag::GetTypeId(), MyObject::GetTypeId(), MyApp::GetTypeId(), ns3::ThreeGppAntennaArrayModel::GetTypeId(), ns3::aodv::RoutingProtocol::GetTypeId(), ns3::BulkSendApplication::GetTypeId(), ns3::E2eStatsHeader::GetTypeId(), ns3::OnOffApplication::GetTypeId(), ns3::PacketSink::GetTypeId(), ns3::SeqTsHeader::GetTypeId(), ns3::UdpClient::GetTypeId(), ns3::UdpEchoClient::GetTypeId(), ns3::UdpEchoServer::GetTypeId(), ns3::UdpServer::GetTypeId(), ns3::UdpTraceClient::GetTypeId(), ns3::BridgeChannel::GetTypeId(), ns3::BridgeNetDevice::GetTypeId(), ns3::GridBuildingAllocator::GetTypeId(), ns3::RandomBuildingPositionAllocator::GetTypeId(), ns3::OutdoorPositionAllocator::GetTypeId(), ns3::RandomRoomPositionAllocator::GetTypeId(), ns3::SameRoomPositionAllocator::GetTypeId(), ns3::FixedRoomPositionAllocator::GetTypeId(), ns3::BuildingListPriv::GetTypeId(), ns3::Building::GetTypeId(), ns3::BuildingsChannelConditionModel::GetTypeId(), ns3::BuildingsPropagationLossModel::GetTypeId(), ns3::HybridBuildingsPropagationLossModel::GetTypeId(), ns3::ItuR1238PropagationLossModel::GetTypeId(), ns3::MobilityBuildingInfo::GetTypeId(), ns3::OhBuildingsPropagationLossModel::GetTypeId(), ConfigExample::GetTypeId(), ns3::ConfigStore::GetTypeId(), anonymous_namespace{test-string-value-formatting.cc}::FormattingTestObject::GetTypeId(), ns3::CalendarScheduler::GetTypeId(), ns3::DefaultSimulatorImpl::GetTypeId(), ns3::HeapScheduler::GetTypeId(), ns3::ListScheduler::GetTypeId(), ns3::MapScheduler::GetTypeId(), ns3::Object::GetTypeId(), ns3::RandomVariableStream::GetTypeId(), ns3::UniformRandomVariable::GetTypeId(), ns3::ConstantRandomVariable::GetTypeId(), ns3::SequentialRandomVariable::GetTypeId(), ns3::ExponentialRandomVariable::GetTypeId(), ns3::ParetoRandomVariable::GetTypeId(), ns3::WeibullRandomVariable::GetTypeId(), ns3::NormalRandomVariable::GetTypeId(), ns3::LogNormalRandomVariable::GetTypeId(), ns3::GammaRandomVariable::GetTypeId(), ns3::ErlangRandomVariable::GetTypeId(), ns3::TriangularRandomVariable::GetTypeId(), ns3::ZipfRandomVariable::GetTypeId(), ns3::ZetaRandomVariable::GetTypeId(), ns3::DeterministicRandomVariable::GetTypeId(), ns3::EmpiricalRandomVariable::GetTypeId(), ns3::RealtimeSimulatorImpl::GetTypeId(), ns3::Scheduler::GetTypeId(), ns3::SimulatorImpl::GetTypeId(), ns3::Synchronizer::GetTypeId(), ns3::WallClockSynchronizer::GetTypeId(), ns3::tests::ConfigTestObject::GetTypeId(), ns3::tests::DerivedConfigTestObject::GetTypeId(), ns3::tests::BaseConfigObject::GetTypeId(), ns3::tests::DerivedConfigObject::GetTypeId(), ns3::tests::TestObject::GetTypeId(), ns3::tests::AlternateTestObject::GetTypeId(), anonymous_namespace{object-test-suite.cc}::BaseA::GetTypeId(), anonymous_namespace{object-test-suite.cc}::DerivedA::GetTypeId(), anonymous_namespace{object-test-suite.cc}::BaseB::GetTypeId(), anonymous_namespace{object-test-suite.cc}::DerivedB::GetTypeId(), DeprecatedAttribute::GetTypeId(), ns3::CsmaChannel::GetTypeId(), ns3::CsmaNetDevice::GetTypeId(), ns3::dsdv::DsdvHeader::GetTypeId(), ns3::dsdv::RoutingProtocol::GetTypeId(), ns3::dsr::DsrNetworkQueue::GetTypeId(), ns3::dsr::DsrOptions::GetTypeId(), ns3::EnergyHarvesterContainer::GetTypeId(), ns3::EnergySourceContainer::GetTypeId(), ns3::BasicEnergyHarvester::GetTypeId(), ns3::BasicEnergySource::GetTypeId(), ns3::DeviceEnergyModel::GetTypeId(), ns3::EnergyHarvester::GetTypeId(), ns3::EnergySource::GetTypeId(), ns3::LiIonEnergySource::GetTypeId(), ns3::RvBatteryModel::GetTypeId(), ns3::SimpleDeviceEnergyModel::GetTypeId(), ns3::FdNetDevice::GetTypeId(), ns3::FlowProbe::GetTypeId(), ns3::Ipv4FlowProbeTag::GetTypeId(), ns3::Ipv4FlowProbe::GetTypeId(), ns3::Ipv6FlowProbeTag::GetTypeId(), ns3::Ipv6FlowProbe::GetTypeId(), ns3::DhcpClient::GetTypeId(), ns3::DhcpHeader::GetTypeId(), ns3::DhcpServer::GetTypeId(), ns3::Radvd::GetTypeId(), ns3::V4Ping::GetTypeId(), ns3::V4TraceRoute::GetTypeId(), ns3::ArpCache::GetTypeId(), ns3::ArpHeader::GetTypeId(), ns3::ArpL3Protocol::GetTypeId(), ns3::GlobalRouter::GetTypeId(), ns3::Icmpv4L4Protocol::GetTypeId(), ns3::Icmpv4Header::GetTypeId(), ns3::Icmpv4Echo::GetTypeId(), ns3::Icmpv4DestinationUnreachable::GetTypeId(), ns3::Icmpv4TimeExceeded::GetTypeId(), ns3::IpL4Protocol::GetTypeId(), ns3::Ipv4GlobalRouting::GetTypeId(), ns3::Ipv4Header::GetTypeId(), ns3::Ipv4Interface::GetTypeId(), ns3::Ipv4L3Protocol::GetTypeId(), ns3::Ipv4ListRouting::GetTypeId(), ns3::Ipv4PacketFilter::GetTypeId(), ns3::Ipv4PacketInfoTag::GetTypeId(), ns3::Ipv4RawSocketFactory::GetTypeId(), ns3::Ipv4RawSocketImpl::GetTypeId(), ns3::Ipv4RoutingProtocol::GetTypeId(), ns3::Ipv4StaticRouting::GetTypeId(), ns3::Ipv4::GetTypeId(), ns3::Ipv6ExtensionDemux::GetTypeId(), ns3::Ipv6Header::GetTypeId(), ns3::Ipv6ListRouting::GetTypeId(), ns3::Ipv6OptionDemux::GetTypeId(), ns3::Ipv6PacketFilter::GetTypeId(), ns3::Ipv6PacketInfoTag::GetTypeId(), ns3::Ipv6RawSocketFactory::GetTypeId(), ns3::Ipv6RoutingProtocol::GetTypeId(), ns3::Ipv6::GetTypeId(), ns3::LoopbackNetDevice::GetTypeId(), ns3::NscTcpL4Protocol::GetTypeId(), ns3::NscTcpSocketImpl::GetTypeId(), ns3::RipRte::GetTypeId(), ns3::RipHeader::GetTypeId(), ns3::Rip::GetTypeId(), ns3::RipNgRte::GetTypeId(), ns3::RipNgHeader::GetTypeId(), ns3::RipNg::GetTypeId(), ns3::RttEstimator::GetTypeId(), ns3::RttMeanDeviation::GetTypeId(), ns3::TcpBic::GetTypeId(), ns3::TcpCongestionOps::GetTypeId(), ns3::TcpNewReno::GetTypeId(), ns3::TcpDctcp::GetTypeId(), ns3::TcpHeader::GetTypeId(), ns3::TcpHighSpeed::GetTypeId(), ns3::TcpHtcp::GetTypeId(), ns3::TcpHybla::GetTypeId(), ns3::TcpIllinois::GetTypeId(), ns3::TcpL4Protocol::GetTypeId(), ns3::TcpLedbat::GetTypeId(), ns3::TcpLp::GetTypeId(), ns3::TcpOptionEnd::GetTypeId(), ns3::TcpOptionNOP::GetTypeId(), ns3::TcpOptionMSS::GetTypeId(), ns3::TcpOptionSackPermitted::GetTypeId(), ns3::TcpOptionSack::GetTypeId(), ns3::TcpOptionTS::GetTypeId(), ns3::TcpOptionWinScale::GetTypeId(), ns3::TcpOption::GetTypeId(), ns3::TcpOptionUnknown::GetTypeId(), ns3::TcpPrrRecovery::GetTypeId(), ns3::TcpRateOps::GetTypeId(), ns3::TcpRateLinux::GetTypeId(), ns3::TcpRecoveryOps::GetTypeId(), ns3::TcpClassicRecovery::GetTypeId(), ns3::TcpRxBuffer::GetTypeId(), ns3::TcpScalable::GetTypeId(), ns3::TcpSocketBase::GetTypeId(), ns3::TcpSocketFactory::GetTypeId(), ns3::TcpSocketState::GetTypeId(), ns3::TcpSocket::GetTypeId(), ns3::TcpTxBuffer::GetTypeId(), ns3::TcpVegas::GetTypeId(), ns3::TcpVeno::GetTypeId(), ns3::TcpWestwood::GetTypeId(), ns3::TcpYeah::GetTypeId(), ns3::UdpHeader::GetTypeId(), ns3::UdpL4Protocol::GetTypeId(), ns3::UdpSocketFactory::GetTypeId(), ns3::UdpSocketImpl::GetTypeId(), ns3::UdpSocket::GetTypeId(), TcpSocketAdvertisedWindowProxy::GetTypeId(), TcpDropRatioErrorModel::GetTypeId(), TcpSocketHalfAck::GetTypeId(), TcpDctcpCongestedRouter::GetTypeId(), ns3::TcpSocketCongestedRouter::GetTypeId(), ns3::TcpGeneralErrorModel::GetTypeId(), ns3::TcpSeqErrorModel::GetTypeId(), ns3::TcpFlagErrorModel::GetTypeId(), ns3::TcpSocketMsgBase::GetTypeId(), ns3::TcpSocketSmallAcks::GetTypeId(), DummyCongControl::GetTypeId(), MimicCongControl::GetTypeId(), ns3::lorawan::BuildingPenetrationLoss::GetTypeId(), ns3::lorawan::ClassAEndDeviceLorawanMac::GetTypeId(), ns3::lorawan::CorrelatedShadowingPropagationLossModel::GetTypeId(), ns3::lorawan::EndDeviceLoraPhy::GetTypeId(), ns3::lorawan::EndDeviceLorawanMac::GetTypeId(), ns3::lorawan::EndDeviceStatus::GetTypeId(), ns3::lorawan::Forwarder::GetTypeId(), ns3::lorawan::GatewayLoraPhy::GetTypeId(), ns3::lorawan::GatewayLorawanMac::GetTypeId(), ns3::HexGridPositionAllocator::GetTypeId(), ns3::lorawan::LogicalLoraChannelHelper::GetTypeId(), ns3::lorawan::LogicalLoraChannel::GetTypeId(), ns3::lorawan::LoraChannel::GetTypeId(), ns3::lorawan::LoraDeviceAddressGenerator::GetTypeId(), ns3::lorawan::LoraFrameHeader::GetTypeId(), ns3::lorawan::LoraInterferenceHelper::GetTypeId(), ns3::lorawan::LoraNetDevice::GetTypeId(), ns3::lorawan::LoraPhy::GetTypeId(), ns3::lorawan::LoraRadioEnergyModel::GetTypeId(), ns3::lorawan::LoraTag::GetTypeId(), ns3::lorawan::LoraTxCurrentModel::GetTypeId(), ns3::lorawan::LinearLoraTxCurrentModel::GetTypeId(), ns3::lorawan::ConstantLoraTxCurrentModel::GetTypeId(), ns3::lorawan::LorawanMacHeader::GetTypeId(), ns3::lorawan::LorawanMac::GetTypeId(), ns3::lorawan::MacCommand::GetTypeId(), ns3::lorawan::NetworkControllerComponent::GetTypeId(), ns3::lorawan::ConfirmedMessagesComponent::GetTypeId(), ns3::lorawan::LinkCheckComponent::GetTypeId(), ns3::lorawan::NetworkScheduler::GetTypeId(), ns3::lorawan::NetworkServer::GetTypeId(), ns3::lorawan::OneShotSender::GetTypeId(), ns3::lorawan::PeriodicSender::GetTypeId(), ns3::lorawan::SimpleEndDeviceLoraPhy::GetTypeId(), ns3::lorawan::SimpleGatewayLoraPhy::GetTypeId(), ns3::lorawan::SubBand::GetTypeId(), ns3::LrWpanCsmaCa::GetTypeId(), ns3::LrWpanErrorModel::GetTypeId(), ns3::LrWpanLqiTag::GetTypeId(), ns3::LrWpanMacHeader::GetTypeId(), ns3::BeaconPayloadHeader::GetTypeId(), ns3::CommandPayloadHeader::GetTypeId(), ns3::LrWpanMacTrailer::GetTypeId(), ns3::LrWpanMac::GetTypeId(), ns3::LrWpanNetDevice::GetTypeId(), ns3::LrWpanPhy::GetTypeId(), ns3::CcHelper::GetTypeId(), ns3::EmuEpcHelper::GetTypeId(), ns3::EpcHelper::GetTypeId(), ns3::LteHelper::GetTypeId(), ns3::LteHexGridEnbTopologyHelper::GetTypeId(), ns3::LteStatsCalculator::GetTypeId(), ns3::MacStatsCalculator::GetTypeId(), ns3::NoBackhaulEpcHelper::GetTypeId(), ns3::PhyRxStatsCalculator::GetTypeId(), ns3::PhyStatsCalculator::GetTypeId(), ns3::PhyTxStatsCalculator::GetTypeId(), ns3::PointToPointEpcHelper::GetTypeId(), ns3::RadioBearerStatsCalculator::GetTypeId(), ns3::RadioEnvironmentMapHelper::GetTypeId(), ns3::ComponentCarrierEnb::GetTypeId(), ns3::ComponentCarrierUe::GetTypeId(), ns3::ComponentCarrier::GetTypeId(), ns3::ComponentCarrierBaseStation::GetTypeId(), ns3::CqaFfMacScheduler::GetTypeId(), ns3::EpcEnbApplication::GetTypeId(), ns3::GtpcHeader::GetTypeId(), ns3::GtpcCreateSessionRequestMessage::GetTypeId(), ns3::GtpcCreateSessionResponseMessage::GetTypeId(), ns3::GtpcModifyBearerRequestMessage::GetTypeId(), ns3::GtpcModifyBearerResponseMessage::GetTypeId(), ns3::GtpcDeleteBearerCommandMessage::GetTypeId(), ns3::GtpcDeleteBearerRequestMessage::GetTypeId(), ns3::GtpcDeleteBearerResponseMessage::GetTypeId(), ns3::GtpuHeader::GetTypeId(), ns3::EpcMmeApplication::GetTypeId(), ns3::EpcPgwApplication::GetTypeId(), ns3::EpcSgwApplication::GetTypeId(), ns3::EpcUeNas::GetTypeId(), ns3::EpcX2Header::GetTypeId(), ns3::EpcX2HandoverRequestHeader::GetTypeId(), ns3::EpcX2HandoverRequestAckHeader::GetTypeId(), ns3::EpcX2HandoverPreparationFailureHeader::GetTypeId(), ns3::EpcX2SnStatusTransferHeader::GetTypeId(), ns3::EpcX2UeContextReleaseHeader::GetTypeId(), ns3::EpcX2LoadInformationHeader::GetTypeId(), ns3::EpcX2ResourceStatusUpdateHeader::GetTypeId(), ns3::EpcX2::GetTypeId(), ns3::EpsBearerTag::GetTypeId(), ns3::EpsBearer::GetTypeId(), ns3::FdBetFfMacScheduler::GetTypeId(), ns3::FdMtFfMacScheduler::GetTypeId(), ns3::FdTbfqFfMacScheduler::GetTypeId(), ns3::FfMacScheduler::GetTypeId(), ns3::LteAmc::GetTypeId(), ns3::Asn1Header::GetTypeId(), ns3::LteEnbMac::GetTypeId(), ns3::LteEnbNetDevice::GetTypeId(), ns3::LteEnbPhy::GetTypeId(), ns3::UeManager::GetTypeId(), ns3::LteEnbRrc::GetTypeId(), ns3::LteInterference::GetTypeId(), ns3::LteNetDevice::GetTypeId(), ns3::LtePdcpHeader::GetTypeId(), ns3::PdcpTag::GetTypeId(), ns3::LtePdcp::GetTypeId(), ns3::LtePhyTag::GetTypeId(), ns3::LtePhy::GetTypeId(), ns3::LteRadioBearerInfo::GetTypeId(), ns3::LteSignalingRadioBearerInfo::GetTypeId(), ns3::LteDataRadioBearerInfo::GetTypeId(), ns3::LteRadioBearerTag::GetTypeId(), ns3::LteRlcAmHeader::GetTypeId(), ns3::LteRlcAm::GetTypeId(), ns3::LteRlcHeader::GetTypeId(), ns3::LteRlcSduStatusTag::GetTypeId(), ns3::RlcTag::GetTypeId(), ns3::LteRlcTm::GetTypeId(), ns3::LteRlcUm::GetTypeId(), ns3::LteRlc::GetTypeId(), ns3::LteRlcSm::GetTypeId(), ns3::RrcAsn1Header::GetTypeId(), ns3::RrcConnectionRequestHeader::GetTypeId(), ns3::IdealHandoverPreparationInfoHeader::GetTypeId(), ns3::IdealHandoverCommandHeader::GetTypeId(), ns3::LteUeRrcProtocolIdeal::GetTypeId(), ns3::LteEnbRrcProtocolIdeal::GetTypeId(), ns3::LteUeRrcProtocolReal::GetTypeId(), ns3::LteEnbRrcProtocolReal::GetTypeId(), ns3::LteSpectrumPhy::GetTypeId(), ns3::LteUeMac::GetTypeId(), ns3::LteUeNetDevice::GetTypeId(), ns3::LteUePhy::GetTypeId(), ns3::LteUePowerControl::GetTypeId(), ns3::LteUeRrc::GetTypeId(), ns3::PfFfMacScheduler::GetTypeId(), ns3::PssFfMacScheduler::GetTypeId(), ns3::RemSpectrumPhy::GetTypeId(), ns3::RrFfMacScheduler::GetTypeId(), ns3::TdBetFfMacScheduler::GetTypeId(), ns3::TdMtFfMacScheduler::GetTypeId(), ns3::TdTbfqFfMacScheduler::GetTypeId(), ns3::TtaFfMacScheduler::GetTypeId(), EpsBearerTagUdpClient::GetTypeId(), ns3::LteSimpleHelper::GetTypeId(), ns3::LteSimpleNetDevice::GetTypeId(), ns3::LteSimpleSpectrumPhy::GetTypeId(), ns3::LteTestRrc::GetTypeId(), ns3::LteTestPdcp::GetTypeId(), ns3::LteTestMac::GetTypeId(), ns3::EpcTestRrc::GetTypeId(), ns3::LteTestUePhy::GetTypeId(), ns3::MeshStack::GetTypeId(), ns3::flame::FlameHeader::GetTypeId(), ns3::ConstantAccelerationMobilityModel::GetTypeId(), ns3::ConstantPositionMobilityModel::GetTypeId(), ns3::ConstantVelocityMobilityModel::GetTypeId(), ns3::GaussMarkovMobilityModel::GetTypeId(), ns3::HierarchicalMobilityModel::GetTypeId(), ns3::MobilityModel::GetTypeId(), ns3::PositionAllocator::GetTypeId(), ns3::ListPositionAllocator::GetTypeId(), ns3::GridPositionAllocator::GetTypeId(), ns3::RandomRectanglePositionAllocator::GetTypeId(), ns3::RandomBoxPositionAllocator::GetTypeId(), ns3::RandomDiscPositionAllocator::GetTypeId(), ns3::UniformDiscPositionAllocator::GetTypeId(), ns3::RandomDirection2dMobilityModel::GetTypeId(), ns3::RandomWalk2dMobilityModel::GetTypeId(), ns3::RandomWaypointMobilityModel::GetTypeId(), ns3::SteadyStateRandomWaypointMobilityModel::GetTypeId(), ns3::WaypointMobilityModel::GetTypeId(), ns3::DistributedSimulatorImpl::GetTypeId(), ns3::GrantedTimeWindowMpiInterface::GetTypeId(), ns3::MpiReceiver::GetTypeId(), ns3::NullMessageSimulatorImpl::GetTypeId(), ns3::RemoteChannelBundle::GetTypeId(), ns3::AnimByteTag::GetTypeId(), MyHeader::GetTypeId(), MyTag::GetTypeId(), ns3::DelayJitterEstimationTimestampTag::GetTypeId(), ns3::Application::GetTypeId(), ns3::ChannelListPriv::GetTypeId(), ns3::Channel::GetTypeId(), ns3::Chunk::GetTypeId(), ns3::Header::GetTypeId(), ns3::NetDevice::GetTypeId(), ns3::NodeListPriv::GetTypeId(), ns3::Node::GetTypeId(), ns3::SocketFactory::GetTypeId(), ns3::Socket::GetTypeId(), ns3::SocketIpTtlTag::GetTypeId(), ns3::SocketIpv6HopLimitTag::GetTypeId(), ns3::SocketSetDontFragmentTag::GetTypeId(), ns3::SocketIpTosTag::GetTypeId(), ns3::SocketPriorityTag::GetTypeId(), ns3::SocketIpv6TclassTag::GetTypeId(), ns3::Tag::GetTypeId(), ns3::Trailer::GetTypeId(), anonymous_namespace{packet-metadata-test.cc}::HistoryHeaderBase::GetTypeId(), anonymous_namespace{packet-metadata-test.cc}::HistoryHeader< N >::GetTypeId(), anonymous_namespace{packet-metadata-test.cc}::HistoryTrailerBase::GetTypeId(), anonymous_namespace{packet-metadata-test.cc}::HistoryTrailer< N >::GetTypeId(), anonymous_namespace{packet-test-suite.cc}::ATestTagBase::GetTypeId(), anonymous_namespace{packet-test-suite.cc}::ATestTag< N >::GetTypeId(), anonymous_namespace{packet-test-suite.cc}::ALargeTestTag::GetTypeId(), anonymous_namespace{packet-test-suite.cc}::ATestHeaderBase::GetTypeId(), anonymous_namespace{packet-test-suite.cc}::ATestHeader< N >::GetTypeId(), anonymous_namespace{packet-test-suite.cc}::ATestTrailerBase::GetTypeId(), anonymous_namespace{packet-test-suite.cc}::ATestTrailer< N >::GetTypeId(), anonymous_namespace{sequence-number-test-suite.cc}::SequenceNumberTestObj::GetTypeId(), ns3::DropTailQueue< Item >::GetTypeId(), ns3::DynamicQueueLimits::GetTypeId(), ns3::ErrorChannel::GetTypeId(), ns3::ErrorModel::GetTypeId(), ns3::RateErrorModel::GetTypeId(), ns3::BurstErrorModel::GetTypeId(), ns3::ListErrorModel::GetTypeId(), ns3::ReceiveListErrorModel::GetTypeId(), ns3::BinaryErrorModel::GetTypeId(), ns3::EthernetHeader::GetTypeId(), ns3::EthernetTrailer::GetTypeId(), ns3::FlowIdTag::GetTypeId(), ns3::LlcSnapHeader::GetTypeId(), ns3::NetDeviceQueueInterface::GetTypeId(), ns3::PacketBurst::GetTypeId(), ns3::PacketCounterCalculator::GetTypeId(), ns3::PacketSizeMinMaxAvgTotalCalculator::GetTypeId(), ns3::PacketSocketClient::GetTypeId(), ns3::PacketSocketFactory::GetTypeId(), ns3::PacketSocketServer::GetTypeId(), ns3::PacketSocket::GetTypeId(), ns3::PacketSocketTag::GetTypeId(), ns3::DeviceNameTag::GetTypeId(), ns3::PbbPacket::GetTypeId(), ns3::PcapFileWrapper::GetTypeId(), ns3::QueueLimits::GetTypeId(), ns3::QueueBase::GetTypeId(), ns3::Queue< Item >::GetTypeId(), ns3::RadiotapHeader::GetTypeId(), ns3::SimpleChannel::GetTypeId(), ns3::SimpleTag::GetTypeId(), ns3::SimpleNetDevice::GetTypeId(), ns3::SllHeader::GetTypeId(), ns3::olsr::PacketHeader::GetTypeId(), ns3::olsr::MessageHeader::GetTypeId(), ns3::olsr::RoutingProtocol::GetTypeId(), ns3::PointToPointChannel::GetTypeId(), ns3::PointToPointNetDevice::GetTypeId(), ns3::PointToPointRemoteChannel::GetTypeId(), ns3::PppHeader::GetTypeId(), ns3::ChannelCondition::GetTypeId(), ns3::ChannelConditionModel::GetTypeId(), ns3::AlwaysLosChannelConditionModel::GetTypeId(), ns3::NeverLosChannelConditionModel::GetTypeId(), ns3::ThreeGppChannelConditionModel::GetTypeId(), ns3::ThreeGppRmaChannelConditionModel::GetTypeId(), ns3::ThreeGppUmaChannelConditionModel::GetTypeId(), ns3::ThreeGppUmiStreetCanyonChannelConditionModel::GetTypeId(), ns3::ThreeGppIndoorMixedOfficeChannelConditionModel::GetTypeId(), ns3::ThreeGppIndoorOpenOfficeChannelConditionModel::GetTypeId(), ns3::Cost231PropagationLossModel::GetTypeId(), ns3::ItuR1411LosPropagationLossModel::GetTypeId(), ns3::ItuR1411NlosOverRooftopPropagationLossModel::GetTypeId(), ns3::JakesProcess::GetTypeId(), ns3::Kun2600MhzPropagationLossModel::GetTypeId(), ns3::OkumuraHataPropagationLossModel::GetTypeId(), ns3::PropagationDelayModel::GetTypeId(), ns3::RandomPropagationDelayModel::GetTypeId(), ns3::ConstantSpeedPropagationDelayModel::GetTypeId(), ns3::PropagationLossModel::GetTypeId(), ns3::RandomPropagationLossModel::GetTypeId(), ns3::FriisPropagationLossModel::GetTypeId(), ns3::TwoRayGroundPropagationLossModel::GetTypeId(), ns3::LogDistancePropagationLossModel::GetTypeId(), ns3::ThreeLogDistancePropagationLossModel::GetTypeId(), ns3::NakagamiPropagationLossModel::GetTypeId(), ns3::FixedRssLossModel::GetTypeId(), ns3::MatrixPropagationLossModel::GetTypeId(), ns3::RangePropagationLossModel::GetTypeId(), ns3::ThreeGppPropagationLossModel::GetTypeId(), ns3::ThreeGppRmaPropagationLossModel::GetTypeId(), ns3::ThreeGppUmaPropagationLossModel::GetTypeId(), ns3::ThreeGppUmiStreetCanyonPropagationLossModel::GetTypeId(), ns3::ThreeGppIndoorOfficePropagationLossModel::GetTypeId(), ns3::SixLowPanHc1::GetTypeId(), ns3::SixLowPanFrag1::GetTypeId(), ns3::SixLowPanFragN::GetTypeId(), ns3::SixLowPanIpv6::GetTypeId(), ns3::SixLowPanIphc::GetTypeId(), ns3::SixLowPanNhcExtension::GetTypeId(), ns3::SixLowPanUdpNhcExtension::GetTypeId(), ns3::SixLowPanBc0::GetTypeId(), ns3::SixLowPanMesh::GetTypeId(), ns3::SixLowPanNetDevice::GetTypeId(), ns3::AlohaNoackMacHeader::GetTypeId(), ns3::AlohaNoackNetDevice::GetTypeId(), ns3::HalfDuplexIdealPhy::GetTypeId(), ns3::MultiModelSpectrumChannel::GetTypeId(), ns3::NonCommunicatingNetDevice::GetTypeId(), ns3::SingleModelSpectrumChannel::GetTypeId(), ns3::SpectrumAnalyzer::GetTypeId(), ns3::SpectrumChannel::GetTypeId(), ns3::ShannonSpectrumErrorModel::GetTypeId(), ns3::SpectrumInterference::GetTypeId(), ns3::SpectrumPhy::GetTypeId(), ns3::TvSpectrumTransmitter::GetTypeId(), ns3::WaveformGenerator::GetTypeId(), Emitter::GetTypeId(), ns3::MinMaxAvgTotalCalculator< T >::GetTypeId(), ns3::CounterCalculator< T >::GetTypeId(), ns3::DataCalculator::GetTypeId(), ns3::DataCollector::GetTypeId(), ns3::DataOutputInterface::GetTypeId(), ns3::OmnetDataOutput::GetTypeId(), ns3::SqliteDataOutput::GetTypeId(), ns3::TimeMinMaxAvgTotalCalculator::GetTypeId(), ns3::TimeSeriesAdaptor::GetTypeId(), SampleEmitter::GetTypeId(), ns3::TapBridge::GetTypeId(), Ipv4TestPacketFilter::GetTypeId(), SimpleSource::GetTypeId(), ns3::SocketWriter::GetTypeId(), TracedValueCallbackTestCase::CheckTvCb< T >::GetTypeId(), ns3::InetTopologyReader::GetTypeId(), ns3::OrbisTopologyReader::GetTypeId(), ns3::RocketfuelTopologyReader::GetTypeId(), ns3::TopologyReader::GetTypeId(), ns3::CobaltQueueDisc::GetTypeId(), ns3::CoDelQueueDisc::GetTypeId(), ns3::FifoQueueDisc::GetTypeId(), ns3::FqCoDelFlow::GetTypeId(), ns3::FqCoDelQueueDisc::GetTypeId(), ns3::MqQueueDisc::GetTypeId(), ns3::PacketFilter::GetTypeId(), ns3::PfifoFastQueueDisc::GetTypeId(), ns3::PieQueueDisc::GetTypeId(), ns3::PrioQueueDisc::GetTypeId(), ns3::QueueDiscClass::GetTypeId(), ns3::QueueDisc::GetTypeId(), ns3::RedQueueDisc::GetTypeId(), ns3::TbfQueueDisc::GetTypeId(), ns3::TrafficControlLayer::GetTypeId(), ns3::AcousticModemEnergyModel::GetTypeId(), ns3::UanChannel::GetTypeId(), ns3::UanHeaderCommon::GetTypeId(), ns3::UanHeaderRcData::GetTypeId(), ns3::UanHeaderRcRts::GetTypeId(), ns3::UanHeaderRcCtsGlobal::GetTypeId(), ns3::UanHeaderRcCts::GetTypeId(), ns3::UanHeaderRcAck::GetTypeId(), ns3::UanMacAloha::GetTypeId(), ns3::UanMacCw::GetTypeId(), ns3::UanMacRcGw::GetTypeId(), ns3::UanMacRc::GetTypeId(), ns3::UanMac::GetTypeId(), ns3::UanNetDevice::GetTypeId(), ns3::UanNoiseModelDefault::GetTypeId(), ns3::UanNoiseModel::GetTypeId(), ns3::UanPhyCalcSinrDual::GetTypeId(), ns3::UanPhyPerGenDefault::GetTypeId(), ns3::UanPhyPerUmodem::GetTypeId(), ns3::UanPhyPerCommonModes::GetTypeId(), ns3::UanPhyCalcSinrDefault::GetTypeId(), ns3::UanPhyCalcSinrFhFsk::GetTypeId(), ns3::UanPhyGen::GetTypeId(), ns3::UanPhyCalcSinr::GetTypeId(), ns3::UanPhyPer::GetTypeId(), ns3::UanPhy::GetTypeId(), ns3::UanPropModelIdeal::GetTypeId(), ns3::UanPropModelThorp::GetTypeId(), ns3::UanPropModel::GetTypeId(), ns3::UanTransducerHd::GetTypeId(), ns3::UanTransducer::GetTypeId(), ns3::VirtualNetDevice::GetTypeId(), ns3::PyVizPacketTag::GetTypeId(), ns3::VisualSimulatorImpl::GetTypeId(), RoutingHelper::GetTypeId(), WifiPhyStats::GetTypeId(), ns3::WaveBsmStats::GetTypeId(), ns3::BsmApplication::GetTypeId(), ns3::ChannelCoordinator::GetTypeId(), ns3::ChannelManager::GetTypeId(), ns3::ChannelScheduler::GetTypeId(), ns3::DefaultChannelScheduler::GetTypeId(), ns3::HigherLayerTxVectorTag::GetTypeId(), ns3::OcbWifiMac::GetTypeId(), ns3::VendorSpecificActionHeader::GetTypeId(), ns3::VsaManager::GetTypeId(), ns3::WaveMacLow::GetTypeId(), ns3::WaveNetDevice::GetTypeId(), ns3::AthstatsWifiTraceSink::GetTypeId(), ns3::AarfWifiManager::GetTypeId(), ns3::AarfcdWifiManager::GetTypeId(), ns3::AdhocWifiMac::GetTypeId(), ns3::AmpduSubframeHeader::GetTypeId(), ns3::AmpduTag::GetTypeId(), ns3::AmrrWifiManager::GetTypeId(), ns3::AmsduSubframeHeader::GetTypeId(), ns3::ApWifiMac::GetTypeId(), ns3::AparfWifiManager::GetTypeId(), ns3::ArfWifiManager::GetTypeId(), ns3::BlockAckManager::GetTypeId(), ns3::CaraWifiManager::GetTypeId(), ns3::ConstantObssPdAlgorithm::GetTypeId(), ns3::ConstantRateWifiManager::GetTypeId(), ns3::ConstantWifiAckPolicySelector::GetTypeId(), ns3::CtrlBAckRequestHeader::GetTypeId(), ns3::CtrlBAckResponseHeader::GetTypeId(), ns3::ErrorRateModel::GetTypeId(), ns3::FrameCaptureModel::GetTypeId(), ns3::HeConfiguration::GetTypeId(), ns3::HtConfiguration::GetTypeId(), ns3::IdealWifiManager::GetTypeId(), ns3::InfrastructureWifiMac::GetTypeId(), ns3::MacLow::GetTypeId(), ns3::MgtAssocRequestHeader::GetTypeId(), ns3::MgtReassocRequestHeader::GetTypeId(), ns3::MgtAssocResponseHeader::GetTypeId(), ns3::MgtProbeRequestHeader::GetTypeId(), ns3::MgtProbeResponseHeader::GetTypeId(), ns3::MgtBeaconHeader::GetTypeId(), ns3::WifiActionHeader::GetTypeId(), ns3::MgtAddBaRequestHeader::GetTypeId(), ns3::MgtAddBaResponseHeader::GetTypeId(), ns3::MgtDelBaHeader::GetTypeId(), ns3::MinstrelHtWifiManager::GetTypeId(), ns3::MinstrelWifiManager::GetTypeId(), ns3::MpduAggregator::GetTypeId(), ns3::MsduAggregator::GetTypeId(), ns3::NistErrorRateModel::GetTypeId(), ns3::ObssPdAlgorithm::GetTypeId(), ns3::OnoeWifiManager::GetTypeId(), ns3::ParfWifiManager::GetTypeId(), ns3::PreambleDetectionModel::GetTypeId(), ns3::QosTxop::GetTypeId(), ns3::RegularWifiMac::GetTypeId(), ns3::RraaWifiManager::GetTypeId(), ns3::RrpaaWifiManager::GetTypeId(), ns3::SimpleFrameCaptureModel::GetTypeId(), ns3::SnrTag::GetTypeId(), ns3::SpectrumWifiPhy::GetTypeId(), ns3::StaWifiMac::GetTypeId(), ns3::ThresholdPreambleDetectionModel::GetTypeId(), ns3::Txop::GetTypeId(), ns3::VhtConfiguration::GetTypeId(), ns3::WifiAckPolicySelector::GetTypeId(), ns3::WifiMacHeader::GetTypeId(), ns3::WifiMacQueue::GetTypeId(), ns3::WifiMacTrailer::GetTypeId(), ns3::WifiMac::GetTypeId(), ns3::WifiNetDevice::GetTypeId(), ns3::DsssSigHeader::GetTypeId(), ns3::LSigHeader::GetTypeId(), ns3::HtSigHeader::GetTypeId(), ns3::VhtSigHeader::GetTypeId(), ns3::HeSigHeader::GetTypeId(), ns3::WifiPhyStateHelper::GetTypeId(), ns3::WifiPhyTag::GetTypeId(), ns3::WifiPhy::GetTypeId(), ns3::WifiRadioEnergyModel::GetTypeId(), ns3::WifiRemoteStationManager::GetTypeId(), ns3::WifiSpectrumPhyInterface::GetTypeId(), ns3::WifiTxCurrentModel::GetTypeId(), ns3::LinearWifiTxCurrentModel::GetTypeId(), ns3::YansErrorRateModel::GetTypeId(), ns3::YansWifiChannel::GetTypeId(), ns3::YansWifiPhy::GetTypeId(), ns3::BandwidthManager::GetTypeId(), ns3::BSLinkManager::GetTypeId(), ns3::BaseStationNetDevice::GetTypeId(), ns3::BSSchedulerRtps::GetTypeId(), ns3::BSSchedulerSimple::GetTypeId(), ns3::BSScheduler::GetTypeId(), ns3::BsServiceFlowManager::GetTypeId(), ns3::UplinkSchedulerMBQoS::GetTypeId(), ns3::UplinkSchedulerRtps::GetTypeId(), ns3::UplinkSchedulerSimple::GetTypeId(), ns3::UplinkScheduler::GetTypeId(), ns3::BurstProfileManager::GetTypeId(), ns3::ConnectionManager::GetTypeId(), ns3::Dcd::GetTypeId(), ns3::DlMap::GetTypeId(), ns3::IpcsClassifier::GetTypeId(), ns3::ManagementMessageType::GetTypeId(), ns3::RngRsp::GetTypeId(), ns3::DsaReq::GetTypeId(), ns3::DsaRsp::GetTypeId(), ns3::DsaAck::GetTypeId(), ns3::RngReq::GetTypeId(), ns3::OfdmDownlinkFramePrefix::GetTypeId(), ns3::ServiceFlowManager::GetTypeId(), ns3::SimpleOfdmWimaxChannel::GetTypeId(), ns3::SimpleOfdmWimaxPhy::GetTypeId(), ns3::SSLinkManager::GetTypeId(), ns3::SSManager::GetTypeId(), ns3::SubscriberStationNetDevice::GetTypeId(), ns3::SSScheduler::GetTypeId(), ns3::SsServiceFlowManager::GetTypeId(), ns3::Ucd::GetTypeId(), ns3::UlMap::GetTypeId(), ns3::WimaxChannel::GetTypeId(), ns3::WimaxConnection::GetTypeId(), ns3::MacHeaderType::GetTypeId(), ns3::GenericMacHeader::GetTypeId(), ns3::BandwidthRequestHeader::GetTypeId(), ns3::GrantManagementSubheader::GetTypeId(), ns3::FragmentationSubheader::GetTypeId(), ns3::WimaxMacQueue::GetTypeId(), ns3::WimaxMacToMacHeader::GetTypeId(), ns3::WimaxNetDevice::GetTypeId(), ns3::WimaxPhy::GetTypeId(), ns3::Tlv::GetTypeId(), BenchHeader< N >::GetTypeId(), and BenchTag< N >::GetTypeId().
SetParent() [2/2]
template<typename T > TypeId ns3::TypeId::SetParent (void)
Set the parent TypeId.
Template Parameters
T [explicit] The parent TypeID type.
Returns
This TypeId instance.
Record in this TypeId which TypeId is the TypeId of the base class of the subclass.
Definition at line 647 of file type-id.h.
SetSize()
TypeId ns3::TypeId::SetSize (std::size_t size)
Set the size of this type.
Call this way:
SetSize (sizeof (<typename>));
This is done automatically by NS_LOG_ENSURE_REGISTERED() A ridiculously large reported size is a symptom that the type hasn't been registered.
Parameters
[in] size The size of the object, in bytes.
Returns
This TypeId instance.
Definition at line 937 of file type-id.cc.
References ns3::Singleton< IidManager >::Get(), m_tid, NS_LOG_FUNCTION, and ns3::IidManager::SetSize().
SetUid()
void ns3::TypeId::SetUid (uint16_t uid)
Set the internal id of this TypeId.
Parameters
[in] uid The internal integer which uniquely identifies this TypeId. This TypeId should already have been registered.
Typically this is used in serialization/deserialization.
This method is even more internal than GetUid(). Use at your own risk and don't be surprised that it eats raw babies on full-moon nights.
Definition at line 1199 of file type-id.cc.
References m_tid, and NS_LOG_FUNCTION.
Referenced by ns3::PacketMetadata::GetSerializedSize(), ns3::PacketMetadata::ItemIterator::Next(), and ns3::PacketMetadata::Serialize().
Friends And Related Function Documentation
operator!=
bool operator!= (TypeId a, TypeId b) friend
Comparison operator.
Parameters
[in] a One value.
[in] b The other value.
Returns
The result of the comparison.
Definition at line 635 of file type-id.h.
operator<
bool operator< (TypeId a, TypeId b) friend
Comparison operator.
Parameters
[in] a One value.
[in] b The other value.
Returns
The result of the comparison.
Definition at line 1237 of file type-id.cc.
operator<<()
std::ostream & operator<< (std::ostream & os, TypeId tid) related
Output streamer.
Parameters
[in,out] os The output stream.
[in] tid The TypeId.
Returns
The output stream.
Definition at line 1211 of file type-id.cc.
operator==
bool operator== (TypeId a, TypeId b) friend
Comparison operator.
Parameters
[in] a One value.
[in] b The other value.
Returns
The result of the comparison.
Definition at line 630 of file type-id.h.
operator>>()
std::istream & operator>> (std::istream & is, TypeId & tid) related
Input Streamer.
Parameters
[in,out] is The input stream.
[out] tid The TypeId to set from the stream.
Returns
The input stream.
Definition at line 1222 of file type-id.cc.
Member Data Documentation
m_tid
uint16_t ns3::TypeId::m_tid private
The TypeId value.
Definition at line 578 of file type-id.h.
Referenced by TypeId(), AddAttribute(), AddTraceSource(), DoAddConstructor(), GetAttributeN(), GetConstructor(), GetGroupName(), GetHash(), GetName(), GetParent(), GetSize(), GetTraceSourceN(), GetUid(), HasConstructor(), HasParent(), HideFromDocumentation(), MustHideFromDocumentation(), ns3::operator<(), SetAttributeInitialValue(), SetGroupName(), SetParent(), SetSize(), and SetUid().
The documentation for this class was generated from the following files:
src/core/model/type-id.h
src/core/model/type-id.cc