ns-3: ns3::LteRlcSapUser Class Reference
ns3::LteRlcSapUser Class Reference abstract
Service Access Point (SAP) offered by the UM-RLC and AM-RLC entities to the PDCP entity See 3GPP 36.322 Radio Link Control (RLC) protocol specification.
#include "lte-rlc-sap.h"
Public Member Functions
virtual ~LteRlcSapUser ()
virtual void ReceivePdcpPdu (Ptr< Packet > p)=0
Called by the RLC entity to notify the PDCP entity of the reception of a new PDCP PDU.
Detailed Description
Service Access Point (SAP) offered by the UM-RLC and AM-RLC entities to the PDCP entity See 3GPP 36.322 Radio Link Control (RLC) protocol specification.
This is the RLC SAP User (i.e. the part of the SAP that contains the PDCP methods called by the RLC)
Definition at line 67 of file lte-rlc-sap.h.
Constructor & Destructor Documentation
~LteRlcSapUser()
ns3::LteRlcSapUser::~LteRlcSapUser () virtual
Definition at line 29 of file lte-rlc-sap.cc.
Member Function Documentation
ReceivePdcpPdu()
virtual void ns3::LteRlcSapUser::ReceivePdcpPdu (Ptr< Packet > p) pure virtual
Called by the RLC entity to notify the PDCP entity of the reception of a new PDCP PDU.
Parameters
p the PDCP PDU
Implemented in ns3::RealProtocolRlcSapUser, ns3::LteRlcSpecificLteRlcSapUser< C >, and ns3::LtePdcpSpecificLteRlcSapUser.
Referenced by ns3::LteRlcTm::DoReceivePdu(), ns3::LteRlcAm::ReassembleAndDeliver(), and ns3::LteRlcUm::ReassembleAndDeliver().
The documentation for this class was generated from the following files:
src/lte/model/lte-rlc-sap.h
src/lte/model/lte-rlc-sap.cc