ns-3: ns3::MacHeaderType Class Reference
ns3::MacHeaderType Class Reference
WiMAX Models
#include "wimax-mac-header.h"
Public Types
enum HeaderType { HEADER_TYPE_GENERIC, HEADER_TYPE_BANDWIDTH }
Header type enumeration.
Public Member Functions
MacHeaderType (uint8_t type)
Constructor.
MacHeaderType (void)
Constructor.
virtual ~MacHeaderType (void)
uint32_t Deserialize (Buffer::Iterator start)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
std::string GetName (void) const
Get name field.
uint32_t GetSerializedSize (void) const
uint8_t GetType (void) const
Get type field.
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetType (uint8_t type)
Set type field.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_type
MAC header type.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class Represents the HT (Header Type) field of generic MAC and bandwidth request headers
See also
GenericMacHeader
BandwidthRequestHeader
Definition at line 36 of file wimax-mac-header.h.
Member Enumeration Documentation
HeaderType
enum ns3::MacHeaderType::HeaderType
Header type enumeration.
Enumerator
HEADER_TYPE_GENERIC
HEADER_TYPE_BANDWIDTH
Definition at line 40 of file wimax-mac-header.h.
Constructor & Destructor Documentation
MacHeaderType() [1/2]
ns3::MacHeaderType::MacHeaderType (void)
Constructor.
Definition at line 30 of file wimax-mac-header.cc.
MacHeaderType() [2/2]
ns3::MacHeaderType::MacHeaderType (uint8_t type)
Constructor.
Parameters
type MAC header type
Definition at line 35 of file wimax-mac-header.cc.
~MacHeaderType()
ns3::MacHeaderType::~MacHeaderType (void) virtual
Definition at line 40 of file wimax-mac-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::MacHeaderType::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 92 of file wimax-mac-header.cc.
GetInstanceTypeId()
TypeId ns3::MacHeaderType::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 73 of file wimax-mac-header.cc.
References GetTypeId().
GetName()
std::string ns3::MacHeaderType::GetName (void) const
Get name field.
Returns
the name
Definition at line 57 of file wimax-mac-header.cc.
GetSerializedSize()
uint32_t ns3::MacHeaderType::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 83 of file wimax-mac-header.cc.
Referenced by ns3::WimaxMacQueue::Dequeue(), and ns3::WimaxMacQueue::GetFirstPacketHdrSize().
GetType()
uint8_t ns3::MacHeaderType::GetType (void) const
Get type field.
Returns
the type
Definition at line 51 of file wimax-mac-header.cc.
References m_type.
Referenced by ns3::WimaxMacQueue::CheckForFragmentation(), ns3::WimaxMacQueue::Dequeue(), ns3::WimaxMacQueue::Enqueue(), ns3::SubscriberStationNetDevice::Enqueue(), ns3::WimaxMacQueue::Front(), ns3::WimaxMacQueue::GetFirstPacketHdrSize(), ns3::WimaxMacQueue::GetFirstPacketPayloadSize(), ns3::WimaxMacQueue::Peek(), and ns3::WimaxMacQueue::Pop().
GetTypeId()
TypeId ns3::MacHeaderType::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 63 of file wimax-mac-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::MacHeaderType::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 78 of file wimax-mac-header.cc.
References m_type.
Serialize()
void ns3::MacHeaderType::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 88 of file wimax-mac-header.cc.
SetType()
void ns3::MacHeaderType::SetType (uint8_t type)
Set type field.
Parameters
type the type
Definition at line 45 of file wimax-mac-header.cc.
References m_type.
Member Data Documentation
m_type
uint8_t ns3::MacHeaderType::m_type private
MAC header type.
Definition at line 84 of file wimax-mac-header.h.
Referenced by GetType(), Print(), and SetType().
The documentation for this class was generated from the following files:
src/wimax/model/wimax-mac-header.h
src/wimax/model/wimax-mac-header.cc