ns-3: ns3::NodeListPriv Class Reference
ns3::NodeListPriv Class Reference
Network
private implementation detail of the NodeList API.
Public Member Functions
NodeListPriv ()
~NodeListPriv ()
uint32_t Add (Ptr< Node > node)
NodeList::Iterator Begin (void) const
NodeList::Iterator End (void) const
uint32_t GetNNodes (void)
Ptr< Node > GetNode (uint32_t n)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static Ptr< NodeListPriv > Get (void)
Get the node list object.
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual void DoDispose (void)
Dispose the nodes in the list.
Static Private Member Functions
static void Delete (void)
Delete the nodes list object.
static Ptr< NodeListPriv > * DoGet (void)
Get the node list object.
Private Attributes
std::vector< Ptr< Node > > m_nodes
node objects container
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
private implementation detail of the NodeList API.
Definition at line 38 of file node-list.cc.
Constructor & Destructor Documentation
NodeListPriv()
ns3::NodeListPriv::NodeListPriv ()
Definition at line 151 of file node-list.cc.
References NS_LOG_FUNCTION.
~NodeListPriv()
ns3::NodeListPriv::~NodeListPriv ()
Definition at line 155 of file node-list.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Add()
uint32_t ns3::NodeListPriv::Add (Ptr< Node > node)
Parameters
node node to add
Returns
index of node in list.
This method is called automatically from Node::Node so the user has little reason to call it himself.
Definition at line 176 of file node-list.cc.
References ns3::Object::Initialize(), m_nodes, NS_LOG_FUNCTION, ns3::Simulator::ScheduleWithContext(), and ns3::TimeStep().
Begin()
NodeList::Iterator ns3::NodeListPriv::Begin (void) const
Returns
a C++ iterator located at the beginning of this list.
Definition at line 186 of file node-list.cc.
References m_nodes, and NS_LOG_FUNCTION.
Delete()
void ns3::NodeListPriv::Delete (void) static private
Delete the nodes list object.
Definition at line 143 of file node-list.cc.
References DoGet(), Get(), NS_LOG_FUNCTION_NOARGS, and ns3::Config::UnregisterRootNamespaceObject().
Referenced by DoGet().
DoDispose()
void ns3::NodeListPriv::DoDispose (void) private virtual
Dispose the nodes in the list.
Reimplemented from ns3::Object.
Definition at line 160 of file node-list.cc.
References ns3::Object::Dispose(), ns3::Object::DoDispose(), m_nodes, and NS_LOG_FUNCTION.
DoGet()
Ptr< NodeListPriv > * ns3::NodeListPriv::DoGet (void) static private
Get the node list object.
Returns
the node list
Definition at line 130 of file node-list.cc.
References Delete(), NS_LOG_FUNCTION_NOARGS, ns3::Config::RegisterRootNamespaceObject(), and ns3::Simulator::ScheduleDestroy().
Referenced by Delete(), and Get().
End()
NodeList::Iterator ns3::NodeListPriv::End (void) const
Returns
a C++ iterator located at the end of this list.
Definition at line 192 of file node-list.cc.
References m_nodes, and NS_LOG_FUNCTION.
Get()
Ptr< NodeListPriv > ns3::NodeListPriv::Get (void) static
Get the node list object.
Returns
the node list
Definition at line 124 of file node-list.cc.
References DoGet(), and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::NodeList::Add(), ns3::NodeList::Begin(), Delete(), ns3::NodeList::End(), ns3::NodeList::GetNNodes(), and ns3::NodeList::GetNode().
GetNNodes()
uint32_t ns3::NodeListPriv::GetNNodes (void)
Returns
the number of nodes currently in the list.
Definition at line 198 of file node-list.cc.
References m_nodes, and NS_LOG_FUNCTION.
GetNode()
Ptr< Node > ns3::NodeListPriv::GetNode (uint32_t n)
Parameters
n index of requested node.
Returns
the Node associated to index n.
Definition at line 205 of file node-list.cc.
References m_nodes, sample-rng-plot::n, NS_ASSERT_MSG(), and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::NodeListPriv::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 110 of file node-list.cc.
References m_nodes, ns3::MakeObjectVectorAccessor(), and ns3::TypeId::SetParent().
Member Data Documentation
m_nodes
std::vector<Ptr<Node> > ns3::NodeListPriv::m_nodes private
node objects container
Definition at line 104 of file node-list.cc.
Referenced by Add(), Begin(), DoDispose(), End(), GetNNodes(), GetNode(), and GetTypeId().
The documentation for this class was generated from the following file:
src/network/model/node-list.cc