ns-3: ns3::GammaRandomVariable Class Reference
ns3::GammaRandomVariable Class Reference
Core » Random Variables
The gamma distribution Random Number Generator (RNG) that allows stream numbers to be set deterministically.
#include "random-variable-stream.h"
Public Member Functions
GammaRandomVariable ()
Creates a gamma distribution RNG with the default values for alpha and beta.
double GetAlpha (void) const
Returns the alpha value for the gamma distribution returned by this RNG stream.
double GetBeta (void) const
Returns the beta value for the gamma distribution returned by this RNG stream.
uint32_t GetInteger (uint32_t alpha, uint32_t beta)
Returns a random unsigned integer from a gamma distribution with the specified alpha and beta.
virtual uint32_t GetInteger (void)
Returns a random unsigned integer from a gamma distribution with the current alpha and beta.
double GetValue (double alpha, double beta)
Returns a random double from a gamma distribution with the specified alpha and beta.
virtual double GetValue (void)
Returns a random double from a gamma distribution with the current alpha and beta.
Public Member Functions inherited from ns3::RandomVariableStream
RandomVariableStream ()
Default constructor.
virtual ~RandomVariableStream ()
Destructor.
int64_t GetStream (void) const
Returns the stream number for the RngStream.
bool IsAntithetic (void) const
Check if antithetic values will be generated.
void SetAntithetic (bool isAntithetic)
Specify whether antithetic values should be generated.
void SetStream (int64_t stream)
Specifies the stream number for the RngStream.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::RandomVariableStream
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
double GetNormalValue (double mean, double variance, double bound)
Returns a random double from a normal distribution with the specified mean, variance, and bound.
Private Attributes
double m_alpha
The alpha value for the gamma distribution returned by this RNG stream.
double m_beta
The beta value for the gamma distribution returned by this RNG stream.
double m_next
The algorithm produces two normal values at a time.
bool m_nextValid
True if the next normal value is valid.
Additional Inherited Members
Protected Member Functions inherited from ns3::RandomVariableStream
RngStream * Peek (void) const
Get the pointer to the underlying RngStream.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The gamma distribution Random Number Generator (RNG) that allows stream numbers to be set deterministically.
This class supports the creation of objects that return random numbers from a fixed gamma distribution. It also supports the generation of single random numbers from various gamma distributions.
The probability density function is defined over the interval [0,) as: where and
Here is an example of how to use this class:
double alpha = 5.0;
double beta = 2.0;
Ptr<GammaRandomVariable> x = CreateObject<GammaRandomVariable> ();
x->SetAttribute ("Alpha", DoubleValue (alpha));
x->SetAttribute ("Beta", DoubleValue (beta));
// The expected value for the mean of the values returned by a
// gammaly distributed random variable is equal to
//
//     E[value]  =  alpha * beta  .
//
double value = x->GetValue ();
Definition at line 1508 of file random-variable-stream.h.
Constructor & Destructor Documentation
GammaRandomVariable()
ns3::GammaRandomVariable::GammaRandomVariable ()
Creates a gamma distribution RNG with the default values for alpha and beta.
Definition at line 921 of file random-variable-stream.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
GetAlpha()
double ns3::GammaRandomVariable::GetAlpha (void) const
Returns the alpha value for the gamma distribution returned by this RNG stream.
Returns
The alpha value for the gamma distribution returned by this RNG stream.
Definition at line 931 of file random-variable-stream.cc.
References m_alpha, and NS_LOG_FUNCTION.
GetBeta()
double ns3::GammaRandomVariable::GetBeta (void) const
Returns the beta value for the gamma distribution returned by this RNG stream.
Returns
The beta value for the gamma distribution returned by this RNG stream.
Definition at line 937 of file random-variable-stream.cc.
References m_beta, and NS_LOG_FUNCTION.
GetInteger() [1/2]
uint32_t ns3::GammaRandomVariable::GetInteger (uint32_t alpha, uint32_t beta)
Returns a random unsigned integer from a gamma distribution with the specified alpha and beta.
Parameters
[in] alpha Alpha value for the gamma distribution.
[in] beta Beta value for the gamma distribution.
Returns
A random unsigned integer value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If is a uniform variable over [0,1] and is a value that would be returned normally, then) is the distance that would be from . The value returned in the antithetic case, , uses (1-u), which is the distance is from the 1.
Definition at line 1012 of file random-variable-stream.cc.
References sample-rng-plot::alpha, GetValue(), and NS_LOG_FUNCTION.
GetInteger() [2/2]
uint32_t ns3::GammaRandomVariable::GetInteger (void) virtual
Returns a random unsigned integer from a gamma distribution with the current alpha and beta.
Returns
A random unsigned integer value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If is a uniform variable over [0,1] and is a value that would be returned normally, then) is the distance that would be from . The value returned in the antithetic case, , uses (1-u), which is the distance is from the 1.
Implements ns3::RandomVariableStream.
Definition at line 1025 of file random-variable-stream.cc.
References GetValue(), m_alpha, m_beta, and NS_LOG_FUNCTION.
GetNormalValue()
double ns3::GammaRandomVariable::GetNormalValue (double mean, double variance, double bound) private
Returns a random double from a normal distribution with the specified mean, variance, and bound.
Parameters
[in] mean Mean value for the normal distribution.
[in] variance Variance value for the normal distribution.
[in] bound Bound on values returned.
Returns
A floating point random value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If and are uniform variables over [0,1], then the values that would be returned normally, and , are calculated as follows:
For the antithetic case,) and) are the distances that and would be from . The antithetic values returned, and , are calculated as follows:
which now involves the distances and are from 1.
Definition at line 1032 of file random-variable-stream.cc.
References ns3::RandomVariableStream::IsAntithetic(), m_next, m_nextValid, NS_LOG_FUNCTION, ns3::RandomVariableStream::Peek(), and ns3::RngStream::RandU01().
Referenced by GetValue().
GetTypeId()
TypeId ns3::GammaRandomVariable::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 904 of file random-variable-stream.cc.
References m_alpha, m_beta, ns3::MakeDoubleAccessor(), and ns3::TypeId::SetParent().
GetValue() [1/2]
double ns3::GammaRandomVariable::GetValue (double alpha, double beta)
Returns a random double from a gamma distribution with the specified alpha and beta.
Parameters
[in] alpha Alpha value for the gamma distribution.
[in] beta Beta value for the gamma distribution.
Returns
A floating point random value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If is a uniform variable over [0,1] and is a value that would be returned normally, then) is the distance that would be from . The value returned in the antithetic case, , uses (1-u), which is the distance is from the 1.
Definition at line 960 of file random-variable-stream.cc.
References sample-rng-plot::alpha, GetNormalValue(), GetValue(), ns3::NormalRandomVariable::INFINITE_VALUE, ns3::RandomVariableStream::IsAntithetic(), NS_LOG_FUNCTION, ns3::RandomVariableStream::Peek(), ns3::RngStream::RandU01(), and sample-rng-plot::x.
GetValue() [2/2]
double ns3::GammaRandomVariable::GetValue (void) virtual
Returns a random double from a gamma distribution with the current alpha and beta.
Returns
A floating point random value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If is a uniform variable over [0,1] and is a value that would be returned normally, then) is the distance that would be from . The value returned in the antithetic case, , uses (1-u), which is the distance is from the 1.
Note that we have to re-implement this method here because the method is overloaded above for the two-argument variant and the c++ name resolution rules don't work well with overloads split between parent and child classes.
Implements ns3::RandomVariableStream.
Definition at line 1019 of file random-variable-stream.cc.
References m_alpha, m_beta, and NS_LOG_FUNCTION.
Referenced by GetInteger(), and GetValue().
Member Data Documentation
m_alpha
double ns3::GammaRandomVariable::m_alpha private
The alpha value for the gamma distribution returned by this RNG stream.
Definition at line 1636 of file random-variable-stream.h.
Referenced by GetAlpha(), GetInteger(), GetTypeId(), and GetValue().
m_beta
double ns3::GammaRandomVariable::m_beta private
The beta value for the gamma distribution returned by this RNG stream.
Definition at line 1639 of file random-variable-stream.h.
Referenced by GetBeta(), GetInteger(), GetTypeId(), and GetValue().
m_next
double ns3::GammaRandomVariable::m_next private
The algorithm produces two normal values at a time.
Definition at line 1645 of file random-variable-stream.h.
Referenced by GetNormalValue().
m_nextValid
bool ns3::GammaRandomVariable::m_nextValid private
True if the next normal value is valid.
Definition at line 1642 of file random-variable-stream.h.
Referenced by GetNormalValue().
The documentation for this class was generated from the following files:
src/core/model/random-variable-stream.h
src/core/model/random-variable-stream.cc