ns-3: WifiOfdmMaskSlopesTestCase Class Reference
WifiOfdmMaskSlopesTestCase Class Reference
Wifi Models » wifi module tests | Test suites
Test checks if Wifi spectrum values for OFDM are generated properly. Different test cases are configured by defining different standards and bandwidth.
Public Types
typedef std::pair< uint32_t, double > IndexPowerPair
typedef for a pair of sub-band index and relative power value (dBr)
typedef std::vector< IndexPowerPair > IndexPowerVect
typedef for a vector of pairs of sub-band index and relative power value (dBr)
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Public Member Functions
WifiOfdmMaskSlopesTestCase (const char *str, WifiPhyStandard standard, uint8_t bw, IndexPowerVect maskRefsLeft, IndexPowerVect maskRefsRight, double tol)
Constructor.
virtual ~WifiOfdmMaskSlopesTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Attributes
Ptr< SpectrumValue > m_actualSpectrum
actual spectrum value
IndexPowerVect m_expectedLeftPsd
expected power values for left guard bandwidth
IndexPowerVect m_expectedRightPsd
expected power values for right guard bandwidth
double m_tolerance
tolerance (in dB)
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Static Private Member Functions
static void InterpolateAndAppendValues (IndexPowerVect &vect, IndexPowerPair start, IndexPowerPair stop, double tol)
Interpolate PSD values for indexes between provided start and stop and append to provided vector.
Additional Inherited Members
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test checks if Wifi spectrum values for OFDM are generated properly. Different test cases are configured by defining different standards and bandwidth.
Definition at line 39 of file wifi-transmit-mask-test.cc.
Member Typedef Documentation
IndexPowerPair
typedef std::pair<uint32_t, double> WifiOfdmMaskSlopesTestCase::IndexPowerPair
typedef for a pair of sub-band index and relative power value (dBr)
Definition at line 45 of file wifi-transmit-mask-test.cc.
IndexPowerVect
typedef std::vector<IndexPowerPair> WifiOfdmMaskSlopesTestCase::IndexPowerVect
typedef for a vector of pairs of sub-band index and relative power value (dBr)
Definition at line 50 of file wifi-transmit-mask-test.cc.
Constructor & Destructor Documentation
WifiOfdmMaskSlopesTestCase()
WifiOfdmMaskSlopesTestCase::WifiOfdmMaskSlopesTestCase (const char * str, WifiPhyStandard standard, uint8_t bw, IndexPowerVect maskRefsLeft, IndexPowerVect maskRefsRight, double tol)
Constructor.
Parameters
str test reference name
standard selected standard
bw bandwidth
maskRefsLeft vector of expected power values and corresponding indexes of generated PSD (only start and stop indexes/values given) for left guard bandwidth
maskRefsRight vector of expected power values and corresponding indexes of generated PSD (only start and stop indexes/values given) for right guard bandwidth
tol tolerance (in dB)
Definition at line 90 of file wifi-transmit-mask-test.cc.
References InterpolateAndAppendValues(), m_actualSpectrum, m_expectedLeftPsd, m_expectedRightPsd, m_tolerance, NS_ASSERT, NS_FATAL_ERROR, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::WIFI_PHY_STANDARD_80211_10MHZ, ns3::WIFI_PHY_STANDARD_80211_5MHZ, ns3::WIFI_PHY_STANDARD_80211a, ns3::WIFI_PHY_STANDARD_80211ac, ns3::WIFI_PHY_STANDARD_80211ax_2_4GHZ, ns3::WIFI_PHY_STANDARD_80211ax_5GHZ, ns3::WIFI_PHY_STANDARD_80211g, ns3::WIFI_PHY_STANDARD_80211n_2_4GHZ, ns3::WIFI_PHY_STANDARD_80211n_5GHZ, and ns3::WIFI_PHY_STANDARD_holland.
~WifiOfdmMaskSlopesTestCase()
WifiOfdmMaskSlopesTestCase::~WifiOfdmMaskSlopesTestCase () virtual
Definition at line 171 of file wifi-transmit-mask-test.cc.
Member Function Documentation
DoRun()
void WifiOfdmMaskSlopesTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 202 of file wifi-transmit-mask-test.cc.
References ns3::SpectrumValue::ConstValuesBegin(), ns3::SpectrumValue::ConstValuesEnd(), m_actualSpectrum, m_expectedLeftPsd, m_expectedRightPsd, m_tolerance, max, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC(), and NS_TEST_EXPECT_MSG_EQ_TOL.
InterpolateAndAppendValues()
void WifiOfdmMaskSlopesTestCase::InterpolateAndAppendValues (IndexPowerVect & vect, IndexPowerPair start, IndexPowerPair stop, double tol) static private
Interpolate PSD values for indexes between provided start and stop and append to provided vector.
Parameters
vect vector of sub-band index and relative power value pairs to which interpolated values should be appended
start pair of sub-band index and relative power value (dBr) for interval start
stop pair of sub-band index and relative power value (dBr) for interval stop
tol tolerance (in dB)
Definition at line 176 of file wifi-transmit-mask-test.cc.
References NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC(), visualizer.core::start(), and ns3::TestDoubleIsEqual().
Referenced by WifiOfdmMaskSlopesTestCase().
Member Data Documentation
m_actualSpectrum
Ptr<SpectrumValue> WifiOfdmMaskSlopesTestCase::m_actualSpectrum protected
actual spectrum value
Definition at line 69 of file wifi-transmit-mask-test.cc.
Referenced by WifiOfdmMaskSlopesTestCase(), and DoRun().
m_expectedLeftPsd
IndexPowerVect WifiOfdmMaskSlopesTestCase::m_expectedLeftPsd protected
expected power values for left guard bandwidth
Definition at line 70 of file wifi-transmit-mask-test.cc.
Referenced by WifiOfdmMaskSlopesTestCase(), and DoRun().
m_expectedRightPsd
IndexPowerVect WifiOfdmMaskSlopesTestCase::m_expectedRightPsd protected
expected power values for right guard bandwidth
Definition at line 71 of file wifi-transmit-mask-test.cc.
Referenced by WifiOfdmMaskSlopesTestCase(), and DoRun().
m_tolerance
double WifiOfdmMaskSlopesTestCase::m_tolerance protected
tolerance (in dB)
Definition at line 72 of file wifi-transmit-mask-test.cc.
Referenced by WifiOfdmMaskSlopesTestCase(), and DoRun().
The documentation for this class was generated from the following file:
src/wifi/test/wifi-transmit-mask-test.cc