ns-3: TcpBicDecrementTest Class Reference
TcpBicDecrementTest Class Reference
Internet » internet module tests | Test suites
Testing the congestion avoidance decrement on TcpBic.
Public Member Functions
TcpBicDecrementTest (uint32_t cWnd, uint32_t segmentSize, BooleanValue fastConvergence, uint32_t lastMaxCwnd, const std::string &name)
Constructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void ExecuteTest (void)
Execute the test.
Private Attributes
uint32_t m_cWnd
Congestion window.
BooleanValue m_fastConvergence
Fast convergence.
uint32_t m_lastMaxCwnd
Last max Cwnd.
uint32_t m_segmentSize
Segment size.
Ptr< TcpSocketState > m_state
TCP socket state.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Testing the congestion avoidance decrement on TcpBic.
Definition at line 197 of file tcp-bic-test.cc.
Constructor & Destructor Documentation
TcpBicDecrementTest()
TcpBicDecrementTest::TcpBicDecrementTest (uint32_t cWnd, uint32_t segmentSize, BooleanValue fastConvergence, uint32_t lastMaxCwnd, const std::string & name)
Constructor.
Parameters
cWnd Congestion window.
segmentSize Segment size.
fastConvergence Fast convergence.
lastMaxCwnd Last max Cwnd.
name Test description.
Definition at line 229 of file tcp-bic-test.cc.
Member Function Documentation
DoRun()
void TcpBicDecrementTest::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 243 of file tcp-bic-test.cc.
References ExecuteTest(), ns3::TcpSocketState::m_cWnd, m_cWnd, ns3::TcpSocketState::m_segmentSize, m_segmentSize, m_state, and ns3::Seconds().
ExecuteTest()
void TcpBicDecrementTest::ExecuteTest (void) private
Execute the test.
Definition at line 256 of file tcp-bic-test.cc.
References ns3::BooleanValue::Get(), ns3::DoubleValue::Get(), ns3::UintegerValue::Get(), ns3::ObjectBase::GetAttribute(), ns3::TcpBic::GetSsThresh(), ns3::TcpSocketState::m_cWnd, m_cWnd, m_fastConvergence, ns3::TcpBic::m_lastMaxCwnd, m_lastMaxCwnd, m_segmentSize, m_state, max, NS_TEST_ASSERT_MSG_EQ, and ns3::ObjectBase::SetAttribute().
Referenced by DoRun().
Member Data Documentation
m_cWnd
uint32_t TcpBicDecrementTest::m_cWnd private
Congestion window.
Definition at line 222 of file tcp-bic-test.cc.
Referenced by DoRun(), and ExecuteTest().
m_fastConvergence
BooleanValue TcpBicDecrementTest::m_fastConvergence private
Fast convergence.
Definition at line 224 of file tcp-bic-test.cc.
Referenced by ExecuteTest().
m_lastMaxCwnd
uint32_t TcpBicDecrementTest::m_lastMaxCwnd private
Last max Cwnd.
Definition at line 225 of file tcp-bic-test.cc.
Referenced by ExecuteTest().
m_segmentSize
uint32_t TcpBicDecrementTest::m_segmentSize private
Segment size.
Definition at line 223 of file tcp-bic-test.cc.
Referenced by DoRun(), and ExecuteTest().
m_state
Ptr<TcpSocketState> TcpBicDecrementTest::m_state private
TCP socket state.
Definition at line 226 of file tcp-bic-test.cc.
Referenced by DoRun(), and ExecuteTest().
The documentation for this class was generated from the following file:
src/internet/test/tcp-bic-test.cc