ns-3: ns3::StatisticalSummary Class Reference
ns3::StatisticalSummary Class Reference abstract
Statistics
Abstract class for calculating statistical data.
#include "data-calculator.h"
Public Member Functions
virtual ~StatisticalSummary ()
Destructor.
virtual long getCount () const =0
Returns the number of observations.
virtual double getMax () const =0
Returns the maximum of the values.
virtual double getMean () const =0
Returns the mean of the (weighted) observations.
virtual double getMin () const =0
Returns the minimum of the values.
virtual double getSqrSum () const =0
virtual double getStddev () const =0
Returns the standard deviation of the (weighted) observations.
virtual double getSum () const =0
virtual double getVariance () const =0
Returns the variance of the (weighted) observations.
Detailed Description
Abstract class for calculating statistical data.
Definition at line 46 of file data-calculator.h.
Constructor & Destructor Documentation
~StatisticalSummary()
virtual ns3::StatisticalSummary::~StatisticalSummary () inline virtual
Destructor.
Definition at line 51 of file data-calculator.h.
Member Function Documentation
getCount()
virtual long ns3::StatisticalSummary::getCount () const pure virtual
Returns the number of observations.
Returns
Number of observations
Implemented in ns3::MinMaxAvgTotalCalculator< T >.
Referenced by ns3::OmnetDataOutput::OmnetOutputCallback::OutputStatistic(), and ns3::SqliteDataOutput::SqliteOutputCallback::OutputStatistic().
getMax()
virtual double ns3::StatisticalSummary::getMax () const pure virtual
Returns the maximum of the values.
Returns
Maximum of values
Implemented in ns3::MinMaxAvgTotalCalculator< T >.
Referenced by ns3::OmnetDataOutput::OmnetOutputCallback::OutputStatistic(), and ns3::SqliteDataOutput::SqliteOutputCallback::OutputStatistic().
getMean()
virtual double ns3::StatisticalSummary::getMean () const pure virtual
Returns the mean of the (weighted) observations.
Returns
Mean of (weighted) observations
Implemented in ns3::MinMaxAvgTotalCalculator< T >.
Referenced by ns3::OmnetDataOutput::OmnetOutputCallback::OutputStatistic().
getMin()
virtual double ns3::StatisticalSummary::getMin () const pure virtual
Returns the minimum of the values.
Returns
Minimum of values
Implemented in ns3::MinMaxAvgTotalCalculator< T >.
Referenced by ns3::OmnetDataOutput::OmnetOutputCallback::OutputStatistic(), and ns3::SqliteDataOutput::SqliteOutputCallback::OutputStatistic().
getSqrSum()
virtual double ns3::StatisticalSummary::getSqrSum () const pure virtual
Returns
Sum of squared values
See also
getWeightedSqrSum()
Implemented in ns3::MinMaxAvgTotalCalculator< T >.
Referenced by ns3::OmnetDataOutput::OmnetOutputCallback::OutputStatistic(), and ns3::SqliteDataOutput::SqliteOutputCallback::OutputStatistic().
getStddev()
virtual double ns3::StatisticalSummary::getStddev () const pure virtual
Returns the standard deviation of the (weighted) observations.
Returns
Standard deviation of (weighted) observations
Implemented in ns3::MinMaxAvgTotalCalculator< T >.
Referenced by ns3::OmnetDataOutput::OmnetOutputCallback::OutputStatistic(), and ns3::SqliteDataOutput::SqliteOutputCallback::OutputStatistic().
getSum()
virtual double ns3::StatisticalSummary::getSum () const pure virtual
Returns
Sum of values
See also
getWeightedSum()
Implemented in ns3::MinMaxAvgTotalCalculator< T >.
Referenced by ns3::OmnetDataOutput::OmnetOutputCallback::OutputStatistic(), and ns3::SqliteDataOutput::SqliteOutputCallback::OutputStatistic().
getVariance()
virtual double ns3::StatisticalSummary::getVariance () const pure virtual
Returns the variance of the (weighted) observations.
Returns
Variance of (weighted) observations
Implemented in ns3::MinMaxAvgTotalCalculator< T >.
The documentation for this class was generated from the following file:
src/stats/model/data-calculator.h