ns-3: ns3::lorawan::LorawanMacHeader Class Reference
ns3::lorawan::LorawanMacHeader Class Reference
This class represents the Mac header of a LoRaWAN packet.
#include "lorawan-mac-header.h"
Public Types
enum MType {
JOIN_REQUEST = 0, JOIN_ACCEPT = 1, UNCONFIRMED_DATA_UP = 2, UNCONFIRMED_DATA_DOWN = 3,
CONFIRMED_DATA_UP = 4, CONFIRMED_DATA_DOWN = 5, PROPRIETARY = 7
}
The message type.
Public Member Functions
LorawanMacHeader ()
~LorawanMacHeader ()
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the header.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint8_t GetMajor (void) const
Get the major version from the header.
uint8_t GetMType (void) const
Get the message type from the header.
virtual uint32_t GetSerializedSize (void) const
bool IsConfirmed (void) const
bool IsUplink (void) const
Check whether this header is for an uplink message.
virtual void Print (std::ostream &os) const
Print the header in a human readable format.
virtual void Serialize (Buffer::Iterator start) const
Serialize the header.
void SetMajor (uint8_t major)
Set the major version of this header.
void SetMType (enum MType mtype)
Set the message type.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_major
The major version this header is using.
uint8_t m_mtype
The Message Type.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class represents the Mac header of a LoRaWAN packet.
Definition at line 32 of file lorawan-mac-header.h.
Member Enumeration Documentation
MType
enum ns3::lorawan::LorawanMacHeader::MType
The message type.
The enum value corresponds to the value that will be written in the header by the Serialize method.
Enumerator
JOIN_REQUEST
JOIN_ACCEPT
UNCONFIRMED_DATA_UP
UNCONFIRMED_DATA_DOWN
CONFIRMED_DATA_UP
CONFIRMED_DATA_DOWN
PROPRIETARY
Definition at line 41 of file lorawan-mac-header.h.
Constructor & Destructor Documentation
LorawanMacHeader()
ns3::lorawan::LorawanMacHeader::LorawanMacHeader ()
Definition at line 30 of file lorawan-mac-header.cc.
~LorawanMacHeader()
ns3::lorawan::LorawanMacHeader::~LorawanMacHeader ()
Definition at line 34 of file lorawan-mac-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::lorawan::LorawanMacHeader::Deserialize (Buffer::Iterator start) virtual
Deserialize the header.
Parameters
start A pointer to the buffer we need to deserialize.
Returns
The number of consumed bytes.
Implements ns3::Header.
Definition at line 85 of file lorawan-mac-header.cc.
References m_major, m_mtype, NS_LOG_FUNCTION_NOARGS, and visualizer.core::start().
Referenced by HeaderTest::DoRun().
GetInstanceTypeId()
TypeId ns3::lorawan::LorawanMacHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 49 of file lorawan-mac-header.cc.
References GetTypeId().
GetMajor()
uint8_t ns3::lorawan::LorawanMacHeader::GetMajor (void) const
Get the major version from the header.
Returns
The uint8_t corresponding to this header's major version.
Definition at line 137 of file lorawan-mac-header.cc.
References m_major, and NS_LOG_FUNCTION_NOARGS.
Referenced by HeaderTest::DoRun().
GetMType()
uint8_t ns3::lorawan::LorawanMacHeader::GetMType (void) const
Get the message type from the header.
Returns
The uint8_t corresponding to this header's message type.
Definition at line 119 of file lorawan-mac-header.cc.
References m_mtype, and NS_LOG_FUNCTION_NOARGS.
Referenced by HeaderTest::DoRun(), and ns3::lorawan::ConfirmedMessagesComponent::OnReceivedPacket().
GetSerializedSize()
uint32_t ns3::lorawan::LorawanMacHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 55 of file lorawan-mac-header.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::lorawan::EndDeviceLorawanMac::DoSend().
GetTypeId()
TypeId ns3::lorawan::LorawanMacHeader::GetTypeId (void) static
Definition at line 39 of file lorawan-mac-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
IsConfirmed()
bool ns3::lorawan::LorawanMacHeader::IsConfirmed (void) const
Definition at line 155 of file lorawan-mac-header.cc.
References CONFIRMED_DATA_DOWN, CONFIRMED_DATA_UP, m_mtype, and NS_LOG_FUNCTION_NOARGS.
IsUplink()
bool ns3::lorawan::LorawanMacHeader::IsUplink (void) const
Check whether this header is for an uplink message.
Returns
True if the message is meant to be sent from an ED to a GW, false otherwise.
Definition at line 145 of file lorawan-mac-header.cc.
References CONFIRMED_DATA_UP, JOIN_REQUEST, m_mtype, NS_LOG_FUNCTION_NOARGS, and UNCONFIRMED_DATA_UP.
Referenced by ns3::lorawan::LoraPacketTracker::IsUplink(), ns3::lorawan::ClassAEndDeviceLorawanMac::Receive(), and ns3::lorawan::GatewayLorawanMac::Receive().
Print()
void ns3::lorawan::LorawanMacHeader::Print (std::ostream & os) const virtual
Print the header in a human readable format.
Parameters
os The std::ostream on which to print the header.
Implements ns3::Header.
Definition at line 104 of file lorawan-mac-header.cc.
References m_major, and m_mtype.
Serialize()
void ns3::lorawan::LorawanMacHeader::Serialize (Buffer::Iterator start) const virtual
Serialize the header.
See Page 15 of LoRaWAN specification for a representation of fields.
Parameters
start A pointer to the buffer that will be filled with the serialization.
Implements ns3::Header.
Definition at line 63 of file lorawan-mac-header.cc.
References m_major, m_mtype, NS_LOG_DEBUG, NS_LOG_FUNCTION_NOARGS, and visualizer.core::start().
Referenced by HeaderTest::DoRun().
SetMajor()
void ns3::lorawan::LorawanMacHeader::SetMajor (uint8_t major)
Set the major version of this header.
Parameters
major The uint8_t corresponding to this header's major version.
Definition at line 127 of file lorawan-mac-header.cc.
References m_major, NS_ASSERT, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::lorawan::EndDeviceLorawanMac::ApplyNecessaryOptions(), and HeaderTest::DoRun().
SetMType()
void ns3::lorawan::LorawanMacHeader::SetMType (enum MType mtype)
Set the message type.
Parameters
mtype The message type of this header.
Definition at line 111 of file lorawan-mac-header.cc.
References m_mtype, and NS_LOG_FUNCTION.
Referenced by ns3::lorawan::EndDeviceLorawanMac::ApplyNecessaryOptions(), HeaderTest::DoRun(), and ns3::lorawan::EndDeviceStatus::GetCompleteReplyPacket().
Member Data Documentation
m_major
uint8_t ns3::lorawan::LorawanMacHeader::m_major private
The major version this header is using.
Definition at line 133 of file lorawan-mac-header.h.
Referenced by Deserialize(), GetMajor(), Print(), Serialize(), and SetMajor().
m_mtype
uint8_t ns3::lorawan::LorawanMacHeader::m_mtype private
The Message Type.
Definition at line 128 of file lorawan-mac-header.h.
Referenced by Deserialize(), GetMType(), IsConfirmed(), IsUplink(), Print(), Serialize(), and SetMType().
The documentation for this class was generated from the following files:
src/lorawan/model/lorawan-mac-header.h
src/lorawan/model/lorawan-mac-header.cc