ns-3: ns3::PacketSizeMinMaxAvgTotalCalculator Class Reference
ns3::PacketSizeMinMaxAvgTotalCalculator Class Reference
Statistics
#include "packet-data-calculators.h"
Public Member Functions
PacketSizeMinMaxAvgTotalCalculator ()
virtual ~PacketSizeMinMaxAvgTotalCalculator ()
void FrameUpdate (std::string path, Ptr< const Packet > packet, Mac48Address realto)
Increments the packet stats by the size of the packet.
void PacketUpdate (std::string path, Ptr< const Packet > packet)
Increments the packet stats by the size of the packet.
Public Member Functions inherited from ns3::MinMaxAvgTotalCalculator< uint32_t >
MinMaxAvgTotalCalculator ()
virtual ~MinMaxAvgTotalCalculator ()
long getCount () const
Returns the count.
double getMax () const
Returns the maximum value.
double getMean () const
Returns the mean value.
double getMin () const
Returns the minimum value.
double getSqrSum () const
Returns the sum of squares.
double getStddev () const
Returns the standard deviation.
double getSum () const
Returns the sum.
double getVariance () const
Returns the current variance.
virtual void Output (DataOutputCallback &callback) const
Outputs the data based on the provided callback.
void Reset ()
Reinitializes all variables of MinMaxAvgTotalCalculator.
void Update (const uint32_t i)
Updates all variables of MinMaxAvgTotalCalculator.
Public Member Functions inherited from ns3::DataCalculator
DataCalculator ()
virtual ~DataCalculator ()
void Disable ()
Disables DataCalculator when simulation stops.
void Enable ()
Enables DataCalculator when simulation starts.
std::string GetContext () const
Gets the DataCalculator context.
bool GetEnabled () const
Returns whether the DataCalculator is enabled.
std::string GetKey () const
Gets the DataCalculator key.
void SetContext (const std::string context)
Sets the DataCalculator context to the provided context.
void SetKey (const std::string key)
Sets the DataCalculator key to the provided key.
virtual void Start (const Time &startTime)
Starts DataCalculator at a given time in the simulation.
virtual void Stop (const Time &stopTime)
Stops DataCalculator at a given time in the simulation.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Public Member Functions inherited from ns3::StatisticalSummary
virtual ~StatisticalSummary ()
Destructor.
virtual long getCount () const =0
Returns the number of observations.
virtual double getMax () const =0
Returns the maximum of the values.
virtual double getMean () const =0
Returns the mean of the (weighted) observations.
virtual double getMin () const =0
Returns the minimum of the values.
virtual double getSqrSum () const =0
virtual double getStddev () const =0
Returns the standard deviation of the (weighted) observations.
virtual double getSum () const =0
virtual double getVariance () const =0
Returns the variance of the (weighted) observations.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::MinMaxAvgTotalCalculator< uint32_t >
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::DataCalculator
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Additional Inherited Members
Protected Attributes inherited from ns3::MinMaxAvgTotalCalculator< uint32_t >
uint32_t m_count
Count value of MinMaxAvgTotalCalculator.
uint32_t m_max
Maximum value of MinMaxAvgTotalCalculator.
double m_meanCurr
Current mean of MinMaxAvgTotalCalculator.
double m_meanPrev
Previous mean of MinMaxAvgTotalCalculator.
uint32_t m_min
Minimum value of MinMaxAvgTotalCalculator.
double m_sCurr
Current s of MinMaxAvgTotalCalculator.
double m_sPrev
Previous s of MinMaxAvgTotalCalculator.
uint32_t m_squareTotal
Sum of squares value of MinMaxAvgTotalCalculator.
uint32_t m_total
Total value of MinMaxAvgTotalCalculator.
double m_varianceCurr
Current variance of MinMaxAvgTotalCalculator.
Protected Attributes inherited from ns3::DataCalculator
std::string m_context
Context value.
bool m_enabled
Descendant classes must check & respect m_enabled!
std::string m_key
Key value.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A stat for collecting packet size statistics: min, max and average
Definition at line 80 of file packet-data-calculators.h.
Constructor & Destructor Documentation
PacketSizeMinMaxAvgTotalCalculator()
PacketSizeMinMaxAvgTotalCalculator::PacketSizeMinMaxAvgTotalCalculator ()
Definition at line 90 of file packet-data-calculators.cc.
References NS_LOG_FUNCTION_NOARGS.
~PacketSizeMinMaxAvgTotalCalculator()
PacketSizeMinMaxAvgTotalCalculator::~PacketSizeMinMaxAvgTotalCalculator () virtual
Definition at line 95 of file packet-data-calculators.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
DoDispose()
void PacketSizeMinMaxAvgTotalCalculator::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::MinMaxAvgTotalCalculator< uint32_t >.
Definition at line 111 of file packet-data-calculators.cc.
References ns3::MinMaxAvgTotalCalculator< T >::DoDispose(), and NS_LOG_FUNCTION_NOARGS.
FrameUpdate()
void PacketSizeMinMaxAvgTotalCalculator::FrameUpdate (std::string path, Ptr< const Packet > packet, Mac48Address realto)
Increments the packet stats by the size of the packet.
Parameters
path not used in this method
packet packet size used to update stats
realto not used in this method
Definition at line 130 of file packet-data-calculators.cc.
References ns3::Packet::GetSize(), NS_LOG_FUNCTION_NOARGS, and ns3::MinMaxAvgTotalCalculator< T >::Update().
GetTypeId()
TypeId PacketSizeMinMaxAvgTotalCalculator::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 101 of file packet-data-calculators.cc.
References ns3::TypeId::SetParent().
PacketUpdate()
void PacketSizeMinMaxAvgTotalCalculator::PacketUpdate (std::string path, Ptr< const Packet > packet)
Increments the packet stats by the size of the packet.
Parameters
path not used in this method
packet packet size used to update stats
Definition at line 120 of file packet-data-calculators.cc.
References ns3::Packet::GetSize(), NS_LOG_FUNCTION_NOARGS, and ns3::MinMaxAvgTotalCalculator< T >::Update().
The documentation for this class was generated from the following files:
src/network/utils/packet-data-calculators.h
src/network/utils/packet-data-calculators.cc