ns-3: LenaTdBetFfMacSchedulerTestCase2 Class Reference
LenaTdBetFfMacSchedulerTestCase2 Class Reference
LTE Models » lte module tests | Test suites
Lena TdBet Ff Mac Scheduler Test Case.
#include "lte-test-tdbet-ff-mac-scheduler.h"
Public Member Functions
LenaTdBetFfMacSchedulerTestCase2 (std::vector< double > dist, std::vector< uint32_t > achievableRateDl, std::vector< uint32_t > estThrTdBetUl, bool errorModelEnabled)
Constructor.
virtual ~LenaTdBetFfMacSchedulerTestCase2 ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Static Private Member Functions
static std::string BuildNameString (uint16_t nUser, std::vector< double > dist)
Build name string.
Private Attributes
std::vector< uint32_t > m_achievableRateDl
DL achievable rate.
std::vector< double > m_dist
the distance between nodes
bool m_errorModelEnabled
indicates whether the error model is enabled
std::vector< uint32_t > m_estThrTdBetUl
etimated TDBET UL throughput
uint16_t m_nUser
number of UE nodes
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Lena TdBet Ff Mac Scheduler Test Case.
Definition at line 83 of file lte-test-tdbet-ff-mac-scheduler.h.
Constructor & Destructor Documentation
LenaTdBetFfMacSchedulerTestCase2()
LenaTdBetFfMacSchedulerTestCase2::LenaTdBetFfMacSchedulerTestCase2 (std::vector< double > dist, std::vector< uint32_t > achievableRateDl, std::vector< uint32_t > estThrTdBetUl, bool errorModelEnabled)
Constructor.
Parameters
dist the distance between nodes
achievableRateDl the DL achievable rate
estThrTdBetUl UL reference throughput
errorModelEnabled indicates whether the error model is enabled
Definition at line 362 of file lte-test-tdbet-ff-mac-scheduler.cc.
~LenaTdBetFfMacSchedulerTestCase2()
LenaTdBetFfMacSchedulerTestCase2::~LenaTdBetFfMacSchedulerTestCase2 () virtual
Definition at line 372 of file lte-test-tdbet-ff-mac-scheduler.cc.
Member Function Documentation
BuildNameString()
std::string LenaTdBetFfMacSchedulerTestCase2::BuildNameString (uint16_t nUser, std::vector< double > dist) static private
Build name string.
Parameters
nUser the number of UE nodes
dist the distance between nodes
Returns
the name string
Definition at line 349 of file lte-test-tdbet-ff-mac-scheduler.cc.
DoRun()
void LenaTdBetFfMacSchedulerTestCase2::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Initialize Simulation Scenario: 1 eNB and m_nUser UEs
Check that the assignment is done in a "TD blind equal throughput" manner among users with different SINRs: the bandwidth should be distributed equally in long term
Check that the assignment in uplink is done in a round robin manner.
Implements ns3::TestCase.
Definition at line 377 of file lte-test-tdbet-ff-mac-scheduler.cc.
References ns3::LteHelper::ActivateDataRadioBearer(), ns3::LteHelper::Attach(), ns3::NodeContainer::Create(), ns3::TestCase::CreateTempDirFilename(), ns3::LteHelper::EnableMacTraces(), ns3::LteHelper::EnableRlcTraces(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::RadioBearerStatsCalculator::GetDlRxData(), ns3::Object::GetObject(), ns3::LteEnbNetDevice::GetPhy(), ns3::LteUeNetDevice::GetPhy(), ns3::LteHelper::GetRlcStats(), ns3::RadioBearerStatsCalculator::GetUlRxData(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), m_achievableRateDl, m_dist, m_errorModelEnabled, m_estThrTdBetUl, m_nUser, third::mobility, NS_LOG_FUNCTION, NS_LOG_INFO, NS_TEST_ASSERT_MSG_EQ_TOL, ns3::Seconds(), ns3::ObjectBase::SetAttribute(), ns3::Config::SetDefault(), ns3::MobilityModel::SetPosition(), ns3::LteHelper::SetSchedulerAttribute(), and ns3::LteHelper::SetSchedulerType().
Member Data Documentation
m_achievableRateDl
std::vector<uint32_t> LenaTdBetFfMacSchedulerTestCase2::m_achievableRateDl private
DL achievable rate.
Definition at line 108 of file lte-test-tdbet-ff-mac-scheduler.h.
Referenced by DoRun().
m_dist
std::vector<double> LenaTdBetFfMacSchedulerTestCase2::m_dist private
the distance between nodes
Definition at line 107 of file lte-test-tdbet-ff-mac-scheduler.h.
Referenced by DoRun().
m_errorModelEnabled
bool LenaTdBetFfMacSchedulerTestCase2::m_errorModelEnabled private
indicates whether the error model is enabled
Definition at line 110 of file lte-test-tdbet-ff-mac-scheduler.h.
Referenced by DoRun().
m_estThrTdBetUl
std::vector<uint32_t> LenaTdBetFfMacSchedulerTestCase2::m_estThrTdBetUl private
etimated TDBET UL throughput
Definition at line 109 of file lte-test-tdbet-ff-mac-scheduler.h.
Referenced by DoRun().
m_nUser
uint16_t LenaTdBetFfMacSchedulerTestCase2::m_nUser private
number of UE nodes
Definition at line 106 of file lte-test-tdbet-ff-mac-scheduler.h.
Referenced by DoRun().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-tdbet-ff-mac-scheduler.h
src/lte/test/lte-test-tdbet-ff-mac-scheduler.cc