ns-3: TcpYeahDecrementTest Class Reference
TcpYeahDecrementTest Class Reference
Internet » internet module tests | Test suites
Testing TcpYeah multiplicative decrease algorithm.
Public Member Functions
TcpYeahDecrementTest (uint32_t cWnd, uint32_t ssThresh, uint32_t segmentSize, SequenceNumber32 nextTxSeq, SequenceNumber32 lastAckedSeq, Time minRtt, UintegerValue rho, const std::string &name)
Constructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
uint32_t CalculateSsThresh (Ptr< TcpYeah > cong)
Calculate the Slow Start threshold.
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
Time m_baseRtt
Base RTT.
uint32_t m_cWnd
Congestion window.
uint32_t m_doingRenoNow
TCP Reno fallback.
SequenceNumber32 m_lastAckedSeq
Last ACKed sequence number.
Time m_minRtt
Min RTT.
SequenceNumber32 m_nextTxSeq
Next Tx sequence number.
UintegerValue m_rho
TCP Yeah rho param.
uint32_t m_segmentsAcked
Number of segments ACKed.
uint32_t m_segmentSize
Segment size.
uint32_t m_ssThresh
Slow Start Threshold.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Testing TcpYeah multiplicative decrease algorithm.
Definition at line 229 of file tcp-yeah-test.cc.
Constructor & Destructor Documentation
TcpYeahDecrementTest()
TcpYeahDecrementTest::TcpYeahDecrementTest (uint32_t cWnd, uint32_t ssThresh, uint32_t segmentSize, SequenceNumber32 nextTxSeq, SequenceNumber32 lastAckedSeq, Time minRtt, UintegerValue rho, const std::string & name)
Constructor.
Parameters
cWnd Congestion window.
ssThresh Slow Start Threshold.
segmentSize Segment size.
nextTxSeq Next Tx sequence number.
lastAckedSeq Last ACKed sequence number.
minRtt Minimum RTT.
rho TCP Yeah rho param.
name Test description.
Definition at line 273 of file tcp-yeah-test.cc.
Member Function Documentation
CalculateSsThresh()
uint32_t TcpYeahDecrementTest::CalculateSsThresh (Ptr< TcpYeah > cong) private
Calculate the Slow Start threshold.
Parameters
cong The TCP state.
Returns
The SshThreshold.
Definition at line 335 of file tcp-yeah-test.cc.
References ns3::UintegerValue::Get(), ns3::ObjectBase::GetAttribute(), ns3::Time::GetSeconds(), m_baseRtt, m_cWnd, m_doingRenoNow, m_minRtt, m_rho, m_segmentSize, max, min, NS_LOG_INFO, and NS_LOG_LOGIC().
Referenced by DoRun().
DoRun()
void TcpYeahDecrementTest::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 296 of file tcp-yeah-test.cc.
References CalculateSsThresh(), ns3::TcpYeah::CongestionStateSet(), ns3::TcpYeah::GetSsThresh(), ns3::TcpYeah::IncreaseWindow(), m_baseRtt, ns3::TcpSocketState::m_cWnd, m_cWnd, ns3::TcpSocketState::m_lastAckedSeq, m_lastAckedSeq, m_minRtt, m_nextTxSeq, ns3::TcpSocketState::m_nextTxSequence, m_rho, m_segmentsAcked, ns3::TcpSocketState::m_segmentSize, m_segmentSize, ns3::TcpSocketState::m_ssThresh, m_ssThresh, NS_TEST_ASSERT_MSG_EQ, ns3::TcpYeah::PktsAcked(), and ns3::ObjectBase::SetAttribute().
Member Data Documentation
m_baseRtt
Time TcpYeahDecrementTest::m_baseRtt private
Base RTT.
Definition at line 268 of file tcp-yeah-test.cc.
Referenced by CalculateSsThresh(), and DoRun().
m_cWnd
uint32_t TcpYeahDecrementTest::m_cWnd private
Congestion window.
Definition at line 261 of file tcp-yeah-test.cc.
Referenced by CalculateSsThresh(), and DoRun().
m_doingRenoNow
uint32_t TcpYeahDecrementTest::m_doingRenoNow private
TCP Reno fallback.
Definition at line 264 of file tcp-yeah-test.cc.
Referenced by CalculateSsThresh().
m_lastAckedSeq
SequenceNumber32 TcpYeahDecrementTest::m_lastAckedSeq private
Last ACKed sequence number.
Definition at line 266 of file tcp-yeah-test.cc.
Referenced by DoRun().
m_minRtt
Time TcpYeahDecrementTest::m_minRtt private
Min RTT.
Definition at line 267 of file tcp-yeah-test.cc.
Referenced by CalculateSsThresh(), and DoRun().
m_nextTxSeq
SequenceNumber32 TcpYeahDecrementTest::m_nextTxSeq private
Next Tx sequence number.
Definition at line 265 of file tcp-yeah-test.cc.
Referenced by DoRun().
m_rho
UintegerValue TcpYeahDecrementTest::m_rho private
TCP Yeah rho param.
Definition at line 270 of file tcp-yeah-test.cc.
Referenced by CalculateSsThresh(), and DoRun().
m_segmentsAcked
uint32_t TcpYeahDecrementTest::m_segmentsAcked private
Number of segments ACKed.
Definition at line 269 of file tcp-yeah-test.cc.
Referenced by DoRun().
m_segmentSize
uint32_t TcpYeahDecrementTest::m_segmentSize private
Segment size.
Definition at line 263 of file tcp-yeah-test.cc.
Referenced by CalculateSsThresh(), and DoRun().
m_ssThresh
uint32_t TcpYeahDecrementTest::m_ssThresh private
Slow Start Threshold.
Definition at line 262 of file tcp-yeah-test.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/internet/test/tcp-yeah-test.cc