ns-3: ns3::lorawan::EndDeviceLorawanMac Class Reference
ns3::lorawan::EndDeviceLorawanMac Class Reference
Class representing the MAC layer of a LoRaWAN device.
#include "end-device-lorawan-mac.h"
Classes
struct LoraRetxParameters
Structure representing the parameters that will be used in the retransmission procedure.
Public Member Functions
EndDeviceLorawanMac ()
virtual ~EndDeviceLorawanMac ()
void AddLogicalChannel (double frequency)
Add a logical channel to the helper.
void AddLogicalChannel (Ptr< LogicalLoraChannel > logicalChannel)
Add a logical channel to the helper.
void AddMacCommand (Ptr< MacCommand > macCommand)
Add a MAC command to the list of those that will be sent out in the next packet.
void AddSubBand (double startFrequency, double endFrequency, double dutyCycle, double maxTxPowerDbm)
Add a subband to the logical channel helper.
void ApplyNecessaryOptions (LoraFrameHeader &frameHeader)
Add the necessary options and MAC commands to the LoraFrameHeader.
void ApplyNecessaryOptions (LorawanMacHeader &macHeader)
Add the necessary options and MAC commands to the LorawanMacHeader.
virtual void DoSend (Ptr< Packet > packet)
Checking if we are performing the transmission of a new packet or a retransmission, and call SendToPhy function.
virtual void FailedReception (Ptr< Packet const > packet)
Function called by lower layers to inform this layer that reception of a packet we were locked on failed.
double GetAggregatedDutyCycle (void)
Set a value for the RX1DROffset parameter.
uint8_t GetDataRate (void)
Get the data rate this end device is set to use.
bool GetDataRateAdaptation (void)
Get if data rate adaptation is enabled or not.
LoraDeviceAddress GetDeviceAddress (void)
Get the network address of this device.
uint8_t GetMaxNumberOfTransmissions (void)
Set the maximum number of transmissions allowed.
LorawanMacHeader::MType GetMType (void)
Get the message type to send when the Send method is called.
virtual uint8_t GetTransmissionPower (void)
Get the transmission power this end device is set to use.
void OnDevStatusReq (void)
Perform the actions that need to be taken when receiving a DevStatusReq command.
void OnDutyCycleReq (double dutyCycle)
Perform the actions that need to be taken when receiving a DutyCycleReq command.
void OnLinkAdrReq (uint8_t dataRate, uint8_t txPower, std::list< int > enabledChannels, int repetitions)
Perform the actions that need to be taken when receiving a LinkAdrReq command.
void OnLinkCheckAns (uint8_t margin, uint8_t gwCnt)
Perform the actions that need to be taken when receiving a LinkCheckAns command.
void OnNewChannelReq (uint8_t chIndex, double frequency, uint8_t minDataRate, uint8_t maxDataRate)
Perform the actions that need to be taken when receiving a NewChannelReq command.
virtual void OnRxClassParamSetupReq (Ptr< RxParamSetupReq > rxParamSetupReq)
Perform the actions that need to be taken when receiving a RxParamSetupReq command based on the Device's Class Type.
void OnRxParamSetupReq (Ptr< RxParamSetupReq > rxParamSetupReq)
Perform the actions that need to be taken when receiving a RxParamSetupReq command.
void ParseCommands (LoraFrameHeader frameHeader)
Parse and take action on the commands contained on this FrameHeader.
virtual void postponeTransmission (Time nextTxDelay, Ptr< Packet >)
Postpone transmission to the specified time and delete previously scheduled transmissions if present.
virtual void Receive (Ptr< Packet const > packet)
Receive a packet.
virtual void resetRetransmissionParameters ()
Reset retransmission parameters contained in the structure LoraRetxParams.
virtual void Send (Ptr< Packet > packet)
Send a packet.
virtual void SendToPhy (Ptr< Packet > packet)
Add headers and send a packet with the sending function of the physical layer.
void SetDataRate (uint8_t dataRate)
Set the data rate this end device will use when transmitting.
void SetDataRateAdaptation (bool adapt)
Enable data rate adaptation in the retransmitting procedure.
void SetDeviceAddress (LoraDeviceAddress address)
Set the network address of this device.
void SetLogicalChannel (uint8_t chIndex, double frequency, uint8_t minDataRate, uint8_t maxDataRate)
Set a new logical channel in the helper.
void SetMaxNumberOfTransmissions (uint8_t maxNumbTx)
Set the maximum number of transmissions allowed.
void SetMType (LorawanMacHeader::MType mType)
Set the message type to send when the Send method is called.
virtual void TxFinished (Ptr< const Packet > packet)
Perform the actions that are required after a packet send.
Public Member Functions inherited from ns3::lorawan::LorawanMac
LorawanMac ()
virtual ~LorawanMac ()
double GetBandwidthFromDataRate (uint8_t dataRate)
Get the BW corresponding to a data rate, based on this MAC's region.
double GetDbmForTxPower (uint8_t txPower)
Get the transmission power in dBm that corresponds, in this region, to the encoded 8-bit txPower.
Ptr< NetDevice > GetDevice (void)
Get the device this MAC layer is installed on.
LogicalLoraChannelHelper GetLogicalLoraChannelHelper (void)
Get the logical lora channel helper associated with this MAC.
int GetNPreambleSymbols (void)
Get the number of PHY preamble symbols this MAC is set to use.
Ptr< LoraPhy > GetPhy (void)
Get the underlying PHY layer.
uint8_t GetSfFromDataRate (uint8_t dataRate)
Get the SF corresponding to a data rate, based on this MAC's region.
void SetBandwidthForDataRate (std::vector< double > bandwidthForDataRate)
Set the vector to use to check up correspondence between bandwidth and DataRate.
void SetDevice (Ptr< NetDevice > device)
Set the device this MAC layer is installed on.
void SetLogicalLoraChannelHelper (LogicalLoraChannelHelper helper)
Set the LogicalLoraChannelHelper this MAC instance will use.
void SetMaxAppPayloadForDataRate (std::vector< uint32_t > maxAppPayloadForDataRate)
Set the maximum App layer payload for a set DataRate.
void SetNPreambleSymbols (int nPreambleSymbols)
Set the number of PHY preamble symbols this MAC is set to use.
void SetPhy (Ptr< LoraPhy > phy)
Set the underlying PHY layer.
void SetReplyDataRateMatrix (ReplyDataRateMatrix replyDataRateMatrix)
Set the matrix to use when deciding with which DataRate to respond.
void SetSfForDataRate (std::vector< uint8_t > sfForDataRate)
Set the vector to use to check up correspondence between SF and DataRate.
void SetTxDbmForTxPower (std::vector< double > txDbmForTxPower)
Set the vector to use to check up which transmission power in Dbm corresponds to a certain TxPower value in this MAC's region.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::lorawan::LorawanMac
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
Ptr< LogicalLoraChannel > GetChannelForTx (void)
Find a suitable channel for transmission.
virtual Time GetNextClassTransmissionDelay (Time waitingTime)
Find the minimum waiting time before the next possible transmission based on End Device's Class Type.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes
LoraDeviceAddress m_address
The address of this device.
uint8_t m_codingRate
The coding rate used by this device.
uint8_t m_dataRate
The DataRate this device is using to transmit.
bool m_enableDRAdapt
Enable Data Rate adaptation during the retransmission procedure.
bool m_headerDisabled
Whether or not the header is disabled for communications by this device.
std::list< Ptr< MacCommand > > m_macCommandList
List of the MAC commands that need to be applied to the next UL packet.
uint8_t m_maxNumbTx
Maximum number of transmission allowed.
uint8_t m_receiveWindowDurationInSymbols
The duration of a receive window in number of symbols.
TracedCallback< uint8_t, bool, Time, Ptr< Packet > > m_requiredTxCallback
The trace source fired when the transmission procedure is finished.
struct LoraRetxParameters m_retxParams
TracedValue< double > m_txPower
The transmission power this device is using to transmit.
Ptr< UniformRandomVariable > m_uniformRV
An uniform random variable, used by the Shuffle method to randomly reorder the channel list.
Protected Attributes inherited from ns3::lorawan::LorawanMac
std::vector< double > m_bandwidthForDataRate
A vector holding the bandwidth each Data Rate corresponds to.
TracedCallback< Ptr< const Packet > > m_cannotSendBecauseDutyCycle
The trace source that is fired when a packet cannot be sent because of duty cycle limitations.
LogicalLoraChannelHelper m_channelHelper
The LogicalLoraChannelHelper instance that is assigned to this MAC.
Ptr< NetDevice > m_device
The device this MAC layer is installed on.
std::vector< uint32_t > m_maxAppPayloadForDataRate
A vector holding the maximum app payload size that corresponds to a certain DataRate.
int m_nPreambleSymbols
The number of symbols to use in the PHY preamble.
Ptr< LoraPhy > m_phy
The PHY instance that sits under this MAC layer.
TracedCallback< Ptr< const Packet > > m_receivedPacket
Trace source that is fired when a packet reaches the MAC layer.
ReplyDataRateMatrix m_replyDataRateMatrix
The matrix that decides the DR the GW will use in a reply based on the ED's sending DR and on the value of the RX1DROffset parameter.
TracedCallback< Ptr< Packet const > > m_sentNewPacket
Trace source that is fired when a new APP layer packet arrives at the MAC layer.
std::vector< uint8_t > m_sfForDataRate
A vector holding the SF each Data Rate corresponds to.
std::vector< double > m_txDbmForTxPower
A vector holding the power that corresponds to a certain TxPower value.
Private Member Functions
Time GetNextTransmissionDelay (void)
Find the minimum waiting time before the next possible transmission.
std::vector< Ptr< LogicalLoraChannel > > Shuffle (std::vector< Ptr< LogicalLoraChannel > > vector)
Randomly shuffle a Ptr<LogicalLoraChannel> vector.
Private Attributes
TracedValue< double > m_aggregatedDutyCycle
The aggregated duty cycle this device needs to respect across all sub-bands.
bool m_controlDataRate
Whether this device's data rate should be controlled by the NS.
uint8_t m_currentFCnt
TracedValue< int > m_lastKnownGatewayCount
The last known gateway count (i.e., gateways that are in communication range with this end device)
TracedValue< double > m_lastKnownLinkMargin
The last known link margin.
LorawanMacHeader::MType m_mType
The message type to apply to packets sent with the Send method.
EventId m_nextRetx
The event of transmitting a packet in a consecutive moment, when the duty cycle let us transmit.
EventId m_nextTx
The event of retransmitting a packet in a consecutive moment if an ACK is not received.
Additional Inherited Members
Public Types inherited from ns3::lorawan::LorawanMac
typedef std::array< std::array< uint8_t, 6 >, 8 > ReplyDataRateMatrix
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Class representing the MAC layer of a LoRaWAN device.
Definition at line 40 of file end-device-lorawan-mac.h.
Constructor & Destructor Documentation
EndDeviceLorawanMac()
ns3::lorawan::EndDeviceLorawanMac::EndDeviceLorawanMac ()
Definition at line 106 of file end-device-lorawan-mac.cc.
References ns3::EventId::Cancel(), m_maxNumbTx, m_nextTx, m_retxParams, m_uniformRV, NS_LOG_FUNCTION, and ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::retxLeft.
~EndDeviceLorawanMac()
ns3::lorawan::EndDeviceLorawanMac::~EndDeviceLorawanMac () virtual
Definition at line 141 of file end-device-lorawan-mac.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
AddLogicalChannel() [1/2]
void ns3::lorawan::EndDeviceLorawanMac::AddLogicalChannel (double frequency)
Add a logical channel to the helper.
Parameters
frequency The channel's center frequency.
Definition at line 874 of file end-device-lorawan-mac.cc.
References ns3::lorawan::LogicalLoraChannelHelper::AddChannel(), ns3::lorawan::LorawanMac::m_channelHelper, and NS_LOG_FUNCTION.
AddLogicalChannel() [2/2]
void ns3::lorawan::EndDeviceLorawanMac::AddLogicalChannel (Ptr< LogicalLoraChannel > logicalChannel)
Add a logical channel to the helper.
Parameters
frequency The channel's center frequency.
Definition at line 882 of file end-device-lorawan-mac.cc.
References ns3::lorawan::LogicalLoraChannelHelper::AddChannel(), ns3::lorawan::LorawanMac::m_channelHelper, and NS_LOG_FUNCTION.
AddMacCommand()
void ns3::lorawan::EndDeviceLorawanMac::AddMacCommand (Ptr< MacCommand > macCommand)
Add a MAC command to the list of those that will be sent out in the next packet.
Definition at line 917 of file end-device-lorawan-mac.cc.
References m_macCommandList, and NS_LOG_FUNCTION.
Referenced by LinkCheckTest::SendPacket().
AddSubBand()
void ns3::lorawan::EndDeviceLorawanMac::AddSubBand (double startFrequency, double endFrequency, double dutyCycle, double maxTxPowerDbm)
Add a subband to the logical channel helper.
Parameters
startFrequency The SubBand's lowest frequency.
endFrequency The SubBand's highest frequency.
dutyCycle The SubBand's duty cycle, in fraction form.
maxTxPowerDbm The maximum transmission power allowed on the SubBand.
Definition at line 901 of file end-device-lorawan-mac.cc.
References ns3::lorawan::LogicalLoraChannelHelper::AddSubBand(), ns3::lorawan::LorawanMac::m_channelHelper, and NS_LOG_FUNCTION_NOARGS.
ApplyNecessaryOptions() [1/2]
void ns3::lorawan::EndDeviceLorawanMac::ApplyNecessaryOptions (LoraFrameHeader & frameHeader)
Add the necessary options and MAC commands to the LoraFrameHeader.
Parameters
frameHeader The frame header on which to apply the options.
Definition at line 463 of file end-device-lorawan-mac.cc.
References ns3::lorawan::LoraFrameHeader::AddCommand(), ns3::lorawan::MacCommand::GetCIDFromMacCommand(), m_address, m_controlDataRate, m_currentFCnt, m_macCommandList, NS_LOG_FUNCTION_NOARGS, NS_LOG_INFO, ns3::lorawan::LoraFrameHeader::SetAddress(), ns3::lorawan::LoraFrameHeader::SetAdr(), ns3::lorawan::LoraFrameHeader::SetAdrAckReq(), ns3::lorawan::LoraFrameHeader::SetAsUplink(), ns3::lorawan::LoraFrameHeader::SetFCnt(), and ns3::lorawan::LoraFrameHeader::SetFPort().
Referenced by DoSend().
ApplyNecessaryOptions() [2/2]
void ns3::lorawan::EndDeviceLorawanMac::ApplyNecessaryOptions (LorawanMacHeader & macHeader)
Add the necessary options and MAC commands to the LorawanMacHeader.
Parameters
macHeader The mac header on which to apply the options.
Definition at line 489 of file end-device-lorawan-mac.cc.
References m_mType, NS_LOG_FUNCTION_NOARGS, ns3::lorawan::LorawanMacHeader::SetMajor(), and ns3::lorawan::LorawanMacHeader::SetMType().
DoSend()
void ns3::lorawan::EndDeviceLorawanMac::DoSend (Ptr< Packet > packet) virtual
Checking if we are performing the transmission of a new packet or a retransmission, and call SendToPhy function.
Parameters
packet the packet to send
Definition at line 211 of file end-device-lorawan-mac.cc.
References ns3::Packet::AddHeader(), ApplyNecessaryOptions(), ns3::lorawan::LorawanMacHeader::CONFIRMED_DATA_UP, ns3::Packet::Copy(), ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::firstAttempt, ns3::lorawan::LoraFrameHeader::GetSerializedSize(), ns3::lorawan::LorawanMacHeader::GetSerializedSize(), m_currentFCnt, m_macCommandList, m_maxNumbTx, m_mType, m_requiredTxCallback, m_retxParams, ns3::lorawan::LorawanMac::m_sentNewPacket, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::packet, ns3::Packet::RemoveHeader(), resetRetransmissionParameters(), ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::retxLeft, SendToPhy(), and ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::waitingAck.
Referenced by postponeTransmission(), and Send().
FailedReception()
void ns3::lorawan::EndDeviceLorawanMac::FailedReception (Ptr< Packet const > packet) virtual
Function called by lower layers to inform this layer that reception of a packet we were locked on failed.
Parameters
packet the packet we failed to receive
Implements ns3::lorawan::LorawanMac.
Reimplemented in ns3::lorawan::ClassAEndDeviceLorawanMac.
Definition at line 328 of file end-device-lorawan-mac.cc.
GetAggregatedDutyCycle()
double ns3::lorawan::EndDeviceLorawanMac::GetAggregatedDutyCycle (void)
Set a value for the RX1DROffset parameter.
This value decides the offset to use when deciding the DataRate of the downlink transmission during the first receive window from the replyDataRateMatrix.
Parameters
rx1DrOffset The value to set for the offset. Get the value of the RX1DROffset parameter.
Returns
The value of the RX1DROffset parameter. Get the aggregated duty cycle.
A time instance containing the aggregated duty cycle in fractional form.
Definition at line 909 of file end-device-lorawan-mac.cc.
References m_aggregatedDutyCycle, and NS_LOG_FUNCTION_NOARGS.
GetChannelForTx()
Ptr< LogicalLoraChannel > ns3::lorawan::EndDeviceLorawanMac::GetChannelForTx (void) protected
Find a suitable channel for transmission.
The channel is chosen among the ones that are available in the ED's LogicalLoraChannel, based on their duty cycle limitations.
Definition at line 556 of file end-device-lorawan-mac.cc.
References ns3::lorawan::LogicalLoraChannelHelper::GetEnabledChannelList(), ns3::Time::GetSeconds(), ns3::lorawan::LogicalLoraChannelHelper::GetWaitingTime(), ns3::lorawan::LorawanMac::m_channelHelper, NS_LOG_DEBUG, NS_LOG_FUNCTION_NOARGS, ns3::Seconds(), and Shuffle().
Referenced by Send(), and ns3::lorawan::ClassAEndDeviceLorawanMac::SendToPhy().
GetDataRate()
uint8_t ns3::lorawan::EndDeviceLorawanMac::GetDataRate (void)
Get the data rate this end device is set to use.
Returns
The data rate this device uses when transmitting.
Definition at line 667 of file end-device-lorawan-mac.cc.
References m_dataRate, and NS_LOG_FUNCTION.
GetDataRateAdaptation()
bool ns3::lorawan::EndDeviceLorawanMac::GetDataRateAdaptation (void)
Get if data rate adaptation is enabled or not.
Definition at line 637 of file end-device-lorawan-mac.cc.
References m_enableDRAdapt.
GetDeviceAddress()
LoraDeviceAddress ns3::lorawan::EndDeviceLorawanMac::GetDeviceAddress (void)
Get the network address of this device.
Returns
This device's address.
Definition at line 683 of file end-device-lorawan-mac.cc.
References m_address, and NS_LOG_FUNCTION.
GetMaxNumberOfTransmissions()
uint8_t ns3::lorawan::EndDeviceLorawanMac::GetMaxNumberOfTransmissions (void)
Set the maximum number of transmissions allowed.
Definition at line 651 of file end-device-lorawan-mac.cc.
References m_maxNumbTx, and NS_LOG_FUNCTION.
GetMType()
LorawanMacHeader::MType ns3::lorawan::EndDeviceLorawanMac::GetMType (void)
Get the message type to send when the Send method is called.
Definition at line 505 of file end-device-lorawan-mac.cc.
References m_mType.
GetNextClassTransmissionDelay()
Time ns3::lorawan::EndDeviceLorawanMac::GetNextClassTransmissionDelay (Time waitingTime) protected virtual
Find the minimum waiting time before the next possible transmission based on End Device's Class Type.
Reimplemented in ns3::lorawan::ClassAEndDeviceLorawanMac.
Definition at line 515 of file end-device-lorawan-mac.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by GetNextTransmissionDelay().
GetNextTransmissionDelay()
Time ns3::lorawan::EndDeviceLorawanMac::GetNextTransmissionDelay (void) private
Find the minimum waiting time before the next possible transmission.
Definition at line 522 of file end-device-lorawan-mac.cc.
References ns3::lorawan::LogicalLoraChannelHelper::GetEnabledChannelList(), GetNextClassTransmissionDelay(), ns3::Time::GetSeconds(), ns3::lorawan::LogicalLoraChannelHelper::GetWaitingTime(), ns3::lorawan::LorawanMac::m_channelHelper, ns3::Time::Max(), min, NS_LOG_DEBUG, and NS_LOG_FUNCTION_NOARGS.
Referenced by Send().
GetTransmissionPower()
uint8_t ns3::lorawan::EndDeviceLorawanMac::GetTransmissionPower (void) virtual
Get the transmission power this end device is set to use.
Returns
The transmission power this device uses when transmitting.
Definition at line 925 of file end-device-lorawan-mac.cc.
References m_txPower.
GetTypeId()
TypeId ns3::lorawan::EndDeviceLorawanMac::GetTypeId (void) static
Definition at line 39 of file end-device-lorawan-mac.cc.
References ns3::lorawan::LorawanMacHeader::CONFIRMED_DATA_UP, m_aggregatedDutyCycle, m_controlDataRate, m_dataRate, m_enableDRAdapt, m_lastKnownGatewayCount, m_lastKnownLinkMargin, m_maxNumbTx, m_mType, m_requiredTxCallback, m_txPower, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeEnumAccessor(), ns3::MakeEnumChecker(), ns3::MakeIntegerAccessor(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), ns3::TypeId::SetParent(), and ns3::lorawan::LorawanMacHeader::UNCONFIRMED_DATA_UP.
OnDevStatusReq()
void ns3::lorawan::EndDeviceLorawanMac::OnDevStatusReq (void)
Perform the actions that need to be taken when receiving a DevStatusReq command.
Definition at line 842 of file end-device-lorawan-mac.cc.
References m_macCommandList, NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by ParseCommands().
OnDutyCycleReq()
void ns3::lorawan::EndDeviceLorawanMac::OnDutyCycleReq (double dutyCycle)
Perform the actions that need to be taken when receiving a DutyCycleReq command.
Parameters
dutyCycle The aggregate duty cycle prescribed by the command, in fraction form.
Definition at line 813 of file end-device-lorawan-mac.cc.
References m_aggregatedDutyCycle, m_macCommandList, NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by ParseCommands().
OnLinkAdrReq()
void ns3::lorawan::EndDeviceLorawanMac::OnLinkAdrReq (uint8_t dataRate, uint8_t txPower, std::list< int > enabledChannels, int repetitions)
Perform the actions that need to be taken when receiving a LinkAdrReq command.
Parameters
dataRate The data rate value of the command.
txPower The transmission power value of the command.
enabledChannels A list of the enabled channels.
repetitions The number of repetitions prescribed by the command.
Definition at line 700 of file end-device-lorawan-mac.cc.
References ns3::lorawan::LorawanMac::GetBandwidthFromDataRate(), ns3::lorawan::LogicalLoraChannelHelper::GetChannelList(), ns3::lorawan::LorawanMac::GetDbmForTxPower(), ns3::lorawan::LorawanMac::GetSfFromDataRate(), ns3::lorawan::LorawanMac::m_channelHelper, m_dataRate, m_macCommandList, m_txPower, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by ParseCommands().
OnLinkCheckAns()
void ns3::lorawan::EndDeviceLorawanMac::OnLinkCheckAns (uint8_t margin, uint8_t gwCnt)
Perform the actions that need to be taken when receiving a LinkCheckAns command.
Parameters
margin The margin value of the command.
gwCnt The gateway count value of the command.
Definition at line 691 of file end-device-lorawan-mac.cc.
References m_lastKnownGatewayCount, m_lastKnownLinkMargin, and NS_LOG_FUNCTION.
Referenced by ParseCommands().
OnNewChannelReq()
void ns3::lorawan::EndDeviceLorawanMac::OnNewChannelReq (uint8_t chIndex, double frequency, uint8_t minDataRate, uint8_t maxDataRate)
Perform the actions that need to be taken when receiving a NewChannelReq command.
Definition at line 855 of file end-device-lorawan-mac.cc.
References m_macCommandList, NS_LOG_FUNCTION, NS_LOG_INFO, and SetLogicalChannel().
Referenced by ParseCommands().
OnRxClassParamSetupReq()
void ns3::lorawan::EndDeviceLorawanMac::OnRxClassParamSetupReq (Ptr< RxParamSetupReq > rxParamSetupReq) virtual
Perform the actions that need to be taken when receiving a RxParamSetupReq command based on the Device's Class Type.
Parameters
rxParamSetupReq The Parameter Setup Request
Reimplemented in ns3::lorawan::ClassAEndDeviceLorawanMac.
Definition at line 829 of file end-device-lorawan-mac.cc.
Referenced by OnRxParamSetupReq().
OnRxParamSetupReq()
void ns3::lorawan::EndDeviceLorawanMac::OnRxParamSetupReq (Ptr< RxParamSetupReq > rxParamSetupReq)
Perform the actions that need to be taken when receiving a RxParamSetupReq command.
Parameters
rxParamSetupReq The Parameter Setup Request
Definition at line 833 of file end-device-lorawan-mac.cc.
References NS_LOG_FUNCTION, and OnRxClassParamSetupReq().
Referenced by ParseCommands().
ParseCommands()
void ns3::lorawan::EndDeviceLorawanMac::ParseCommands (LoraFrameHeader frameHeader)
Parse and take action on the commands contained on this FrameHeader.
Definition at line 332 of file end-device-lorawan-mac.cc.
References ns3::lorawan::DEV_STATUS_REQ, ns3::lorawan::DL_CHANNEL_REQ, ns3::lorawan::DUTY_CYCLE_REQ, ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::firstAttempt, ns3::lorawan::LoraFrameHeader::GetAck(), ns3::lorawan::LoraFrameHeader::GetCommands(), ns3::lorawan::LINK_ADR_REQ, ns3::lorawan::LINK_CHECK_ANS, m_maxNumbTx, m_requiredTxCallback, m_retxParams, ns3::lorawan::NEW_CHANNEL_REQ, NS_LOG_DEBUG, NS_LOG_ERROR, NS_LOG_FUNCTION, NS_LOG_INFO, OnDevStatusReq(), OnDutyCycleReq(), OnLinkAdrReq(), OnLinkCheckAns(), OnNewChannelReq(), OnRxParamSetupReq(), ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::packet, resetRetransmissionParameters(), ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::retxLeft, ns3::lorawan::RX_PARAM_SETUP_REQ, ns3::lorawan::RX_TIMING_SETUP_REQ, ns3::lorawan::TX_PARAM_SETUP_REQ, and ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::waitingAck.
Referenced by ns3::lorawan::ClassAEndDeviceLorawanMac::Receive().
postponeTransmission()
void ns3::lorawan::EndDeviceLorawanMac::postponeTransmission (Time nextTxDelay, Ptr< Packet > packet) virtual
Postpone transmission to the specified time and delete previously scheduled transmissions if present.
Parameters
nextTxDelay Delay at which the transmission will be performed.
Definition at line 199 of file end-device-lorawan-mac.cc.
References ns3::Simulator::Cancel(), DoSend(), ns3::Time::GetSeconds(), m_nextTx, NS_LOG_FUNCTION, NS_LOG_WARN, and ns3::Simulator::Schedule().
Referenced by Send().
Receive()
void ns3::lorawan::EndDeviceLorawanMac::Receive (Ptr< Packet const > packet) virtual
Receive a packet.
This method is typically registered as a callback in the underlying PHY layer so that it's called when a packet is going up the stack.
Parameters
packet the received packet.
Implements ns3::lorawan::LorawanMac.
Reimplemented in ns3::lorawan::ClassAEndDeviceLorawanMac.
Definition at line 324 of file end-device-lorawan-mac.cc.
resetRetransmissionParameters()
void ns3::lorawan::EndDeviceLorawanMac::resetRetransmissionParameters () virtual
Reset retransmission parameters contained in the structure LoraRetxParams.
Definition at line 618 of file end-device-lorawan-mac.cc.
References ns3::Simulator::Cancel(), ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::firstAttempt, m_maxNumbTx, m_nextTx, m_retxParams, ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::packet, ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::retxLeft, ns3::Seconds(), and ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::waitingAck.
Referenced by ns3::lorawan::ClassAEndDeviceLorawanMac::CloseSecondReceiveWindow(), DoSend(), ns3::lorawan::ClassAEndDeviceLorawanMac::FailedReception(), ParseCommands(), and ns3::lorawan::ClassAEndDeviceLorawanMac::Receive().
Send()
void ns3::lorawan::EndDeviceLorawanMac::Send (Ptr< Packet > packet) virtual
Send a packet.
The MAC layer of the ED will take care of using the right parameters.
Parameters
packet the packet to send
Implements ns3::lorawan::LorawanMac.
Definition at line 151 of file end-device-lorawan-mac.cc.
References DoSend(), GetChannelForTx(), GetNextTransmissionDelay(), ns3::Packet::GetSize(), ns3::lorawan::LogicalLoraChannelHelper::GetTxPowerForChannel(), ns3::lorawan::LorawanMac::m_cannotSendBecauseDutyCycle, ns3::lorawan::LorawanMac::m_channelHelper, m_dataRate, ns3::lorawan::LorawanMac::m_maxAppPayloadForDataRate, m_retxParams, m_txPower, NS_ASSERT_MSG(), NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_WARN, postponeTransmission(), ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::retxLeft, and ns3::Seconds().
Referenced by ns3::lorawan::ClassAEndDeviceLorawanMac::CloseSecondReceiveWindow(), ns3::lorawan::ClassAEndDeviceLorawanMac::FailedReception(), and ns3::lorawan::ClassAEndDeviceLorawanMac::Receive().
SendToPhy()
void ns3::lorawan::EndDeviceLorawanMac::SendToPhy (Ptr< Packet > packet) virtual
Add headers and send a packet with the sending function of the physical layer.
Parameters
packet the packet to send
Reimplemented in ns3::lorawan::ClassAEndDeviceLorawanMac.
Definition at line 316 of file end-device-lorawan-mac.cc.
Referenced by DoSend().
SetDataRate()
void ns3::lorawan::EndDeviceLorawanMac::SetDataRate (uint8_t dataRate)
Set the data rate this end device will use when transmitting.
For End Devices, this value is assumed to be fixed, and can be modified via MAC commands issued by the GW.
Parameters
dataRate The dataRate to use when transmitting.
Definition at line 659 of file end-device-lorawan-mac.cc.
References m_dataRate, and NS_LOG_FUNCTION.
SetDataRateAdaptation()
void ns3::lorawan::EndDeviceLorawanMac::SetDataRateAdaptation (bool adapt)
Enable data rate adaptation in the retransmitting procedure.
Parameters
adapt If the data rate adaptation is enabled or not.
Definition at line 630 of file end-device-lorawan-mac.cc.
References m_enableDRAdapt, and NS_LOG_FUNCTION.
SetDeviceAddress()
void ns3::lorawan::EndDeviceLorawanMac::SetDeviceAddress (LoraDeviceAddress address)
Set the network address of this device.
Parameters
address The address to set.
Definition at line 675 of file end-device-lorawan-mac.cc.
References first::address, m_address, and NS_LOG_FUNCTION.
SetLogicalChannel()
void ns3::lorawan::EndDeviceLorawanMac::SetLogicalChannel (uint8_t chIndex, double frequency, uint8_t minDataRate, uint8_t maxDataRate)
Set a new logical channel in the helper.
Parameters
chIndex The channel's new index.
frequency The channel's center frequency.
minDataRate The minimum data rate allowed on the channel.
maxDataRate The maximum data rate allowed on the channel.
Definition at line 890 of file end-device-lorawan-mac.cc.
References ns3::lorawan::LorawanMac::m_channelHelper, NS_LOG_FUNCTION, and ns3::lorawan::LogicalLoraChannelHelper::SetChannel().
Referenced by OnNewChannelReq().
SetMaxNumberOfTransmissions()
void ns3::lorawan::EndDeviceLorawanMac::SetMaxNumberOfTransmissions (uint8_t maxNumbTx)
Set the maximum number of transmissions allowed.
Parameters
maxNumbTx The maximum number of transmissions allowed
Definition at line 643 of file end-device-lorawan-mac.cc.
References m_maxNumbTx, m_retxParams, NS_LOG_FUNCTION, and ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::retxLeft.
SetMType()
void ns3::lorawan::EndDeviceLorawanMac::SetMType (LorawanMacHeader::MType mType)
Set the message type to send when the Send method is called.
Definition at line 498 of file end-device-lorawan-mac.cc.
References m_mType, and NS_LOG_DEBUG.
Referenced by LinkCheckTest::SendPacket().
Shuffle()
std::vector< Ptr< LogicalLoraChannel > > ns3::lorawan::EndDeviceLorawanMac::Shuffle (std::vector< Ptr< LogicalLoraChannel > > vector) private
Randomly shuffle a Ptr<LogicalLoraChannel> vector.
Used to pick a random channel on which to send the packet.
Definition at line 597 of file end-device-lorawan-mac.cc.
References ns3::UniformRandomVariable::GetValue(), m_uniformRV, and NS_LOG_FUNCTION_NOARGS.
Referenced by GetChannelForTx().
TxFinished()
void ns3::lorawan::EndDeviceLorawanMac::TxFinished (Ptr< const Packet > packet) virtual
Perform the actions that are required after a packet send.
This function handles opening of the first receive window.
Implements ns3::lorawan::LorawanMac.
Reimplemented in ns3::lorawan::ClassAEndDeviceLorawanMac.
Definition at line 511 of file end-device-lorawan-mac.cc.
Member Data Documentation
m_address
LoraDeviceAddress ns3::lorawan::EndDeviceLorawanMac::m_address protected
The address of this device.
Definition at line 380 of file end-device-lorawan-mac.h.
Referenced by ApplyNecessaryOptions(), GetDeviceAddress(), ns3::lorawan::ClassAEndDeviceLorawanMac::Receive(), and SetDeviceAddress().
m_aggregatedDutyCycle
TracedValue<double> ns3::lorawan::EndDeviceLorawanMac::m_aggregatedDutyCycle private
The aggregated duty cycle this device needs to respect across all sub-bands.
Definition at line 487 of file end-device-lorawan-mac.h.
Referenced by GetAggregatedDutyCycle(), GetTypeId(), and OnDutyCycleReq().
m_codingRate
uint8_t ns3::lorawan::EndDeviceLorawanMac::m_codingRate protected
The coding rate used by this device.
Definition at line 370 of file end-device-lorawan-mac.h.
Referenced by ns3::lorawan::ClassAEndDeviceLorawanMac::SendToPhy().
m_controlDataRate
bool ns3::lorawan::EndDeviceLorawanMac::m_controlDataRate private
Whether this device's data rate should be controlled by the NS.
Definition at line 450 of file end-device-lorawan-mac.h.
Referenced by ApplyNecessaryOptions(), and GetTypeId().
m_currentFCnt
uint8_t ns3::lorawan::EndDeviceLorawanMac::m_currentFCnt private
Definition at line 494 of file end-device-lorawan-mac.h.
Referenced by ApplyNecessaryOptions(), and DoSend().
m_dataRate
uint8_t ns3::lorawan::EndDeviceLorawanMac::m_dataRate protected
The DataRate this device is using to transmit.
Definition at line 360 of file end-device-lorawan-mac.h.
Referenced by GetDataRate(), ns3::lorawan::ClassAEndDeviceLorawanMac::GetFirstReceiveWindowDataRate(), GetTypeId(), OnLinkAdrReq(), Send(), ns3::lorawan::ClassAEndDeviceLorawanMac::SendToPhy(), and SetDataRate().
m_enableDRAdapt
bool ns3::lorawan::EndDeviceLorawanMac::m_enableDRAdapt protected
Enable Data Rate adaptation during the retransmission procedure.
Definition at line 350 of file end-device-lorawan-mac.h.
Referenced by GetDataRateAdaptation(), GetTypeId(), ns3::lorawan::ClassAEndDeviceLorawanMac::SendToPhy(), and SetDataRateAdaptation().
m_headerDisabled
bool ns3::lorawan::EndDeviceLorawanMac::m_headerDisabled protected
Whether or not the header is disabled for communications by this device.
Definition at line 375 of file end-device-lorawan-mac.h.
Referenced by ns3::lorawan::ClassAEndDeviceLorawanMac::SendToPhy().
m_lastKnownGatewayCount
TracedValue<int> ns3::lorawan::EndDeviceLorawanMac::m_lastKnownGatewayCount private
The last known gateway count (i.e., gateways that are in communication range with this end device)
This value is obtained (and updated) when a LinkCheckAns Mac command is received.
Definition at line 482 of file end-device-lorawan-mac.h.
Referenced by GetTypeId(), and OnLinkCheckAns().
m_lastKnownLinkMargin
TracedValue<double> ns3::lorawan::EndDeviceLorawanMac::m_lastKnownLinkMargin private
The last known link margin.
This value is obtained (and updated) when a LinkCheckAns Mac command is received.
Definition at line 473 of file end-device-lorawan-mac.h.
Referenced by GetTypeId(), and OnLinkCheckAns().
m_macCommandList
std::list<Ptr<MacCommand> > ns3::lorawan::EndDeviceLorawanMac::m_macCommandList protected
List of the MAC commands that need to be applied to the next UL packet.
Definition at line 410 of file end-device-lorawan-mac.h.
Referenced by AddMacCommand(), ApplyNecessaryOptions(), DoSend(), OnDevStatusReq(), OnDutyCycleReq(), OnLinkAdrReq(), OnNewChannelReq(), and ns3::lorawan::ClassAEndDeviceLorawanMac::OnRxClassParamSetupReq().
m_maxNumbTx
uint8_t ns3::lorawan::EndDeviceLorawanMac::m_maxNumbTx protected
Maximum number of transmission allowed.
Definition at line 355 of file end-device-lorawan-mac.h.
Referenced by EndDeviceLorawanMac(), ns3::lorawan::ClassAEndDeviceLorawanMac::CloseSecondReceiveWindow(), DoSend(), ns3::lorawan::ClassAEndDeviceLorawanMac::FailedReception(), GetMaxNumberOfTransmissions(), GetTypeId(), ParseCommands(), ns3::lorawan::ClassAEndDeviceLorawanMac::Receive(), resetRetransmissionParameters(), ns3::lorawan::ClassAEndDeviceLorawanMac::SendToPhy(), and SetMaxNumberOfTransmissions().
m_mType
LorawanMacHeader::MType ns3::lorawan::EndDeviceLorawanMac::m_mType private
The message type to apply to packets sent with the Send method.
Definition at line 492 of file end-device-lorawan-mac.h.
Referenced by ApplyNecessaryOptions(), DoSend(), GetMType(), GetTypeId(), and SetMType().
m_nextRetx
EventId ns3::lorawan::EndDeviceLorawanMac::m_nextRetx private
The event of transmitting a packet in a consecutive moment, when the duty cycle let us transmit.
This Event is used to cancel the transmission of this packet if a newer packet is delivered from the application to be sent.
Definition at line 465 of file end-device-lorawan-mac.h.
m_nextTx
EventId ns3::lorawan::EndDeviceLorawanMac::m_nextTx private
The event of retransmitting a packet in a consecutive moment if an ACK is not received.
This Event is used to cancel the retransmission if the ACK is found in ParseCommand function and if a newer packet is delivered from the application to be sent.
Definition at line 458 of file end-device-lorawan-mac.h.
Referenced by EndDeviceLorawanMac(), postponeTransmission(), and resetRetransmissionParameters().
m_receiveWindowDurationInSymbols
uint8_t ns3::lorawan::EndDeviceLorawanMac::m_receiveWindowDurationInSymbols protected
The duration of a receive window in number of symbols.
This should be converted to time based or the reception parameter used.
The downlink preamble transmitted by the gateways contains 8 symbols. The receiver requires 5 symbols to detect the preamble and synchronize. Therefore there must be a 5 symbols overlap between the receive window and the transmitted preamble. (Ref: Recommended SX1272/76 Settings for EU868 LoRaWAN Network Operation)
Definition at line 405 of file end-device-lorawan-mac.h.
Referenced by ns3::lorawan::ClassAEndDeviceLorawanMac::GetNextClassTransmissionDelay(), ns3::lorawan::ClassAEndDeviceLorawanMac::OpenFirstReceiveWindow(), and ns3::lorawan::ClassAEndDeviceLorawanMac::OpenSecondReceiveWindow().
m_requiredTxCallback
TracedCallback<uint8_t, bool, Time, Ptr<Packet> > ns3::lorawan::EndDeviceLorawanMac::m_requiredTxCallback protected
The trace source fired when the transmission procedure is finished.
See also
class CallBackTraceSource
Definition at line 432 of file end-device-lorawan-mac.h.
Referenced by ns3::lorawan::ClassAEndDeviceLorawanMac::CloseSecondReceiveWindow(), DoSend(), ns3::lorawan::ClassAEndDeviceLorawanMac::FailedReception(), GetTypeId(), ParseCommands(), and ns3::lorawan::ClassAEndDeviceLorawanMac::Receive().
m_retxParams
struct LoraRetxParameters ns3::lorawan::EndDeviceLorawanMac::m_retxParams protected
Definition at line 410 of file end-device-lorawan-mac.h.
Referenced by EndDeviceLorawanMac(), ns3::lorawan::ClassAEndDeviceLorawanMac::CloseSecondReceiveWindow(), DoSend(), ns3::lorawan::ClassAEndDeviceLorawanMac::FailedReception(), ns3::lorawan::ClassAEndDeviceLorawanMac::GetNextClassTransmissionDelay(), ParseCommands(), ns3::lorawan::ClassAEndDeviceLorawanMac::Receive(), resetRetransmissionParameters(), Send(), ns3::lorawan::ClassAEndDeviceLorawanMac::SendToPhy(), and SetMaxNumberOfTransmissions().
m_txPower
TracedValue<double> ns3::lorawan::EndDeviceLorawanMac::m_txPower protected
The transmission power this device is using to transmit.
Definition at line 365 of file end-device-lorawan-mac.h.
Referenced by GetTransmissionPower(), GetTypeId(), OnLinkAdrReq(), Send(), and ns3::lorawan::ClassAEndDeviceLorawanMac::SendToPhy().
m_uniformRV
Ptr<UniformRandomVariable> ns3::lorawan::EndDeviceLorawanMac::m_uniformRV protected
An uniform random variable, used by the Shuffle method to randomly reorder the channel list.
Definition at line 421 of file end-device-lorawan-mac.h.
Referenced by EndDeviceLorawanMac(), ns3::lorawan::ClassAEndDeviceLorawanMac::GetNextClassTransmissionDelay(), and Shuffle().
The documentation for this class was generated from the following files:
src/lorawan/model/end-device-lorawan-mac.h
src/lorawan/model/end-device-lorawan-mac.cc