ns-3: TcpSsThreshRtoTest Class Reference
TcpSsThreshRtoTest Class Reference
Internet » internet module tests | Test suites
Testing the ssthresh behavior after the RTO expires.
Public Member Functions
TcpSsThreshRtoTest (TypeId &congControl, uint32_t seqToDrop, Time minRto, const std::string &msg)
Constructor.
Public Member Functions inherited from ns3::TcpGeneralTest
TcpGeneralTest (const std::string &desc)
TcpGeneralTest constructor.
~TcpGeneralTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Member Functions
virtual void AfterRTOExpired (const Ptr< const TcpSocketState > tcb, SocketWho who)
Rto has expired.
virtual void BeforeRTOExpired (const Ptr< const TcpSocketState > tcb, SocketWho who)
Rto has expired.
virtual void BytesInFlightTrace (uint32_t oldValue, uint32_t newValue)
Bytes in flight changes.
virtual void ConfigureEnvironment ()
Change the configuration of the environment.
virtual Ptr< ErrorModel > CreateReceiverErrorModel ()
Create and return the error model to install in the receiver node.
virtual Ptr< TcpSocketMsgBase > CreateSenderSocket (Ptr< Node > node)
Create and install the socket to install on the sender.
void PktDropped (const Ipv4Header &ipH, const TcpHeader &tcpH, Ptr< const Packet > p)
Called when a packet has been dropped.
virtual void SsThreshTrace (uint32_t oldValue, uint32_t newValue)
Slow start threshold changes.
Protected Member Functions inherited from ns3::TcpGeneralTest
virtual void ConfigureProperties (void)
Change the configuration of the socket properties.
virtual void CongStateTrace (const TcpSocketState::TcpCongState_t oldValue, const TcpSocketState::TcpCongState_t newValue)
State on Ack state machine changes.
virtual Ptr< SimpleChannel > CreateChannel ()
Create and return the channel installed between the two socket.
virtual Ptr< TcpSocketMsgBase > CreateReceiverSocket (Ptr< Node > node)
Create and install the socket to install on the receiver.
virtual Ptr< ErrorModel > CreateSenderErrorModel ()
Create and return the error model to install in the sender node.
virtual Ptr< TcpSocketMsgBase > CreateSocket (Ptr< Node > node, TypeId socketType, TypeId congControl)
Create a socket.
virtual Ptr< TcpSocketMsgBase > CreateSocket (Ptr< Node > node, TypeId socketType, TypeId congControl, TypeId recoveryAlgorithm)
Create a socket.
virtual void CWndInflTrace (uint32_t oldValue, uint32_t newValue)
Tracks the inflated congestion window changes.
virtual void CWndTrace (uint32_t oldValue, uint32_t newValue)
Tracks the congestion window changes.
virtual void DataSent (uint32_t size, SocketWho who)
Notifying application for sent data.
void DoConnect ()
Scheduled at 0.0, SENDER starts the connection to RECEIVER.
virtual void DoRun (void)
Execute the tcp test.
virtual void DoTeardown (void)
Teardown the TCP test.
virtual void ErrorClose (SocketWho who)
Socket closed with an error.
virtual void FinalChecks ()
Performs the (eventual) final checks through test asserts.
Time GetClockGranularity (SocketWho who)
Get the clock granularity attribute.
Time GetConnTimeout (SocketWho who)
Get the retransmission time for the SYN segments.
uint32_t GetDelAckCount (SocketWho who)
Get the number of delayed ack (if present)
Time GetDelAckTimeout (SocketWho who)
Get the timeout of delayed ack (if present)
uint32_t GetDupAckCount (SocketWho who)
Get the number of dupack received.
SequenceNumber32 GetHighestTxMark (SocketWho who)
Get the highest tx mark of the node specified.
uint32_t GetInitialCwnd (SocketWho who)
Get the initial congestion window.
uint32_t GetInitialSsThresh (SocketWho who)
Get the initial slow start threshold.
Time GetMinRto (SocketWho who)
Get the minimum RTO attribute.
uint32_t GetMtu () const
Get the MTU of the environment.
EventId GetPersistentEvent (SocketWho who)
Get the persistent event of the selected socket.
Time GetPersistentTimeout (SocketWho who)
Get the persistent timeout of the selected socket.
uint32_t GetPktCount () const
Get the number of application packets.
Time GetPktInterval () const
Get the interval to wait for each packet sent down from application to TCP.
uint32_t GetPktSize () const
Get the application packet size.
Time GetPropagationDelay () const
Get the channel Propagation Delay.
Ptr< TcpSocketMsgBase > GetReceiverSocket ()
Get the pointer to a previously created receiver socket.
uint32_t GetReTxThreshold (SocketWho who)
Get the retransmission threshold.
Time GetRto (SocketWho who)
Get the retransmission time.
Ptr< RttEstimator > GetRttEstimator (SocketWho who)
Get the Rtt estimator of the socket.
uint32_t GetRWnd (SocketWho who)
Get the rWnd of the selected socket.
Ptr< TcpRxBuffer > GetRxBuffer (SocketWho who)
Get the Rx buffer from selected socket.
uint32_t GetSegSize (SocketWho who)
Get the segment size of the node specified.
Ptr< TcpSocketMsgBase > GetSenderSocket ()
Get the pointer to a previously created sender socket.
Time GetStartTime () const
Get the data start time.
Ptr< TcpSocketState > GetTcb (SocketWho who)
Get the TCB from selected socket.
TcpSocket::TcpStates_t GetTcpState (SocketWho who)
Get the state of the TCP state machine.
Ptr< TcpTxBuffer > GetTxBuffer (SocketWho who)
Get the Tx buffer from selected socket.
virtual void HighestTxSeqTrace (SequenceNumber32 oldValue, SequenceNumber32 newValue)
Highest tx seq changes.
virtual void NextTxSeqTrace (SequenceNumber32 oldValue, SequenceNumber32 newValue)
Next tx seq changes.
virtual void NormalClose (SocketWho who)
Socket closed normally.
virtual void PhyDrop (SocketWho who)
Link drop.
virtual void ProcessedAck (const Ptr< const TcpSocketState > tcb, const TcpHeader &h, SocketWho who)
Processed ack.
virtual void QueueDrop (SocketWho who)
Drop on the queue.
virtual void RateSampleUpdatedTrace (const TcpRateLinux::TcpRateSample &sample)
Track the rate sample value of TcpRateLinux.
virtual void RateUpdatedTrace (const TcpRateLinux::TcpRateConnection &rate)
Track the rate value of TcpRateLinux.
virtual void RcvAck (const Ptr< const TcpSocketState > tcb, const TcpHeader &h, SocketWho who)
Received ack.
virtual void ReceivePacket (Ptr< Socket > socket)
Packet received.
virtual void RtoTrace (Time oldValue, Time newValue)
RTO changes.
virtual void RttTrace (Time oldTime, Time newTime)
Rtt changes.
virtual void Rx (const Ptr< const Packet > p, const TcpHeader &h, SocketWho who)
Packet received from IP layer.
void SendPacket (Ptr< Socket > socket, uint32_t pktSize, uint32_t pktCount, Time pktInterval)
Send packets to other endpoint.
void SetAppPktCount (uint32_t pktCount)
Set app packet count.
void SetAppPktInterval (Time pktInterval)
Interval between app-generated packet.
void SetAppPktSize (uint32_t pktSize)
Set app packet size.
void SetCongestionControl (TypeId congControl)
Congestion control of the sender socket.
void SetInitialCwnd (SocketWho who, uint32_t initialCwnd)
Forcefully set the initial cwnd.
void SetInitialSsThresh (SocketWho who, uint32_t initialSsThresh)
Forcefully set the initial ssth.
void SetMTU (uint32_t mtu)
MTU of the bottleneck link.
void SetPropagationDelay (Time propDelay)
Propagation delay of the bottleneck link.
void SetRcvBufSize (SocketWho who, uint32_t size)
Forcefully set a defined size for rx buffer.
void SetRecoveryAlgorithm (TypeId reccovery)
recovery algorithm of the sender socket
void SetSegmentSize (SocketWho who, uint32_t segmentSize)
Forcefully set the segment size.
void SetTransmitStart (Time startTime)
Set the initial time at which the application sends the first data packet.
void SetUseEcn (SocketWho who, TcpSocketState::UseEcn_t useEcn)
Forcefully set the ecn use on.
virtual void Tx (const Ptr< const Packet > p, const TcpHeader &h, SocketWho who)
Packet transmitted down to IP layer.
virtual void UpdatedRttHistory (const SequenceNumber32 &seq, uint32_t sz, bool isRetransmission, SocketWho who)
Updated the Rtt history.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Private Attributes
uint32_t m_bytesInFlight
Store the number of bytes in flight.
uint32_t m_bytesInFlightBeforeRto
Store the number of bytes in flight before the RTO expiration.
Time m_minRtoTime
the minimum RTO time
uint32_t m_seqToDrop
the sequence number to drop
uint32_t m_ssThreshSocket
the ssThresh as computed by the socket
Additional Inherited Members
Public Types inherited from ns3::TcpGeneralTest
enum SocketWho { SENDER, RECEIVER }
Used as parameter of methods, specifies on what node the caller is interested (e.g.
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Attributes inherited from ns3::TcpGeneralTest
TypeId m_congControlTypeId
Congestion control.
TypeId m_recoveryTypeId
Recovery.
Detailed Description
Testing the ssthresh behavior after the RTO expires.
The scope of this test is to be sure that, after an RTO expiration, the TCP implementation sets the correct ssthresh value
Definition at line 181 of file tcp-rto-test.cc.
Constructor & Destructor Documentation
TcpSsThreshRtoTest()
TcpSsThreshRtoTest::TcpSsThreshRtoTest (TypeId & congControl, uint32_t seqToDrop, Time minRto, const std::string & msg)
Constructor.
Parameters
congControl Congestion control type.
seqToDrop sequence number to drop
minRto minimum RTO
msg Test description.
Definition at line 220 of file tcp-rto-test.cc.
References ns3::TcpGeneralTest::m_congControlTypeId.
Member Function Documentation
AfterRTOExpired()
void TcpSsThreshRtoTest::AfterRTOExpired (const Ptr< const TcpSocketState > tcb, SocketWho who) protected virtual
Rto has expired.
Parameters
tcb Transmission control block
who where the RTO has expired (SENDER or RECEIVER)
Reimplemented from ns3::TcpGeneralTest.
Definition at line 300 of file tcp-rto-test.cc.
References ns3::TcpGeneralTest::GetSenderSocket(), m_bytesInFlightBeforeRto, ns3::TcpSocketState::m_segmentSize, m_ssThreshSocket, max, NS_LOG_DEBUG, and NS_TEST_ASSERT_MSG_EQ.
BeforeRTOExpired()
void TcpSsThreshRtoTest::BeforeRTOExpired (const Ptr< const TcpSocketState > tcb, SocketWho who) protected virtual
Rto has expired.
Parameters
tcb Transmission control block
who where the RTO has expired (SENDER or RECEIVER)
Reimplemented from ns3::TcpGeneralTest.
Definition at line 286 of file tcp-rto-test.cc.
References m_bytesInFlight, m_bytesInFlightBeforeRto, NS_LOG_DEBUG, and ns3::TcpGeneralTest::SENDER.
BytesInFlightTrace()
void TcpSsThreshRtoTest::BytesInFlightTrace (uint32_t oldValue, uint32_t newValue) protected virtual
Bytes in flight changes.
This applies only for sender socket.
Parameters
oldValue old value
newValue new value
Reimplemented from ns3::TcpGeneralTest.
Definition at line 272 of file tcp-rto-test.cc.
References m_bytesInFlight, and NS_LOG_DEBUG.
ConfigureEnvironment()
void TcpSsThreshRtoTest::ConfigureEnvironment () protected virtual
Change the configuration of the environment.
Reimplemented from ns3::TcpGeneralTest.
Definition at line 229 of file tcp-rto-test.cc.
References ns3::MicroSeconds(), ns3::MilliSeconds(), ns3::TcpGeneralTest::SetAppPktCount(), ns3::TcpGeneralTest::SetAppPktInterval(), and ns3::TcpGeneralTest::SetPropagationDelay().
CreateReceiverErrorModel()
Ptr< ErrorModel > TcpSsThreshRtoTest::CreateReceiverErrorModel () protected virtual
Create and return the error model to install in the receiver node.
Returns
receiver error model
Reimplemented from ns3::TcpGeneralTest.
Definition at line 248 of file tcp-rto-test.cc.
References ns3::TcpSeqErrorModel::AddSeqToKill(), m_seqToDrop, ns3::MakeCallback(), NS_LOG_DEBUG, PktDropped(), and ns3::TcpGeneralErrorModel::SetDropCallback().
CreateSenderSocket()
Ptr< TcpSocketMsgBase > TcpSsThreshRtoTest::CreateSenderSocket (Ptr< Node > node) protected virtual
Create and install the socket to install on the sender.
Parameters
node sender node pointer
Returns
the socket to be installed in the sender
Reimplemented from ns3::TcpGeneralTest.
Definition at line 238 of file tcp-rto-test.cc.
References m_minRtoTime, NS_LOG_DEBUG, and ns3::ObjectBase::SetAttribute().
PktDropped()
void TcpSsThreshRtoTest::PktDropped (const Ipv4Header & ipH, const TcpHeader & tcpH, Ptr< const Packet > p) protected
Called when a packet has been dropped.
Parameters
ipH IPv4 header.
tcpH TCP header.
p The packet.
Definition at line 265 of file tcp-rto-test.cc.
References NS_LOG_DEBUG.
Referenced by CreateReceiverErrorModel().
SsThreshTrace()
void TcpSsThreshRtoTest::SsThreshTrace (uint32_t oldValue, uint32_t newValue) protected virtual
Slow start threshold changes.
This applies only for sender socket.
Parameters
oldValue old value
newValue new value
Reimplemented from ns3::TcpGeneralTest.
Definition at line 279 of file tcp-rto-test.cc.
References m_ssThreshSocket, and NS_LOG_DEBUG.
Member Data Documentation
m_bytesInFlight
uint32_t TcpSsThreshRtoTest::m_bytesInFlight private
Store the number of bytes in flight.
Definition at line 213 of file tcp-rto-test.cc.
Referenced by BeforeRTOExpired(), and BytesInFlightTrace().
m_bytesInFlightBeforeRto
uint32_t TcpSsThreshRtoTest::m_bytesInFlightBeforeRto private
Store the number of bytes in flight before the RTO expiration.
Definition at line 214 of file tcp-rto-test.cc.
Referenced by AfterRTOExpired(), and BeforeRTOExpired().
m_minRtoTime
Time TcpSsThreshRtoTest::m_minRtoTime private
the minimum RTO time
Definition at line 217 of file tcp-rto-test.cc.
Referenced by CreateSenderSocket().
m_seqToDrop
uint32_t TcpSsThreshRtoTest::m_seqToDrop private
the sequence number to drop
Definition at line 216 of file tcp-rto-test.cc.
Referenced by CreateReceiverErrorModel().
m_ssThreshSocket
uint32_t TcpSsThreshRtoTest::m_ssThreshSocket private
the ssThresh as computed by the socket
Definition at line 215 of file tcp-rto-test.cc.
Referenced by AfterRTOExpired(), and SsThreshTrace().
The documentation for this class was generated from the following file:
src/internet/test/tcp-rto-test.cc