ns-3: LenaHarqTestCase Class Reference
LenaHarqTestCase Class Reference
LTE Models » lte module tests | Test suites
This system test program creates different test cases with a single eNB and several UEs, all having the same Radio Bearer specification. In each test case, the UEs see the same SINR from the eNB; different test cases are implemented obtained by using different SINR values and different numbers of UEs. The test consists on ...
#include "lte-test-harq.h"
Public Member Functions
LenaHarqTestCase (uint16_t nUser, uint16_t dist, uint16_t tbSize, double amcBer, double thrRef)
Constructor.
virtual ~LenaHarqTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Static Private Member Functions
static std::string BuildNameString (uint16_t nUser, uint16_t dist, uint16_t tbSize)
Build name string function.
Private Attributes
double m_amcBer
AMC bit error rate.
uint16_t m_dist
distance between nodes
uint16_t m_nUser
number of UE nodes
double m_throughputRef
throughput reference
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
This system test program creates different test cases with a single eNB and several UEs, all having the same Radio Bearer specification. In each test case, the UEs see the same SINR from the eNB; different test cases are implemented obtained by using different SINR values and different numbers of UEs. The test consists on ...
Definition at line 41 of file lte-test-harq.h.
Constructor & Destructor Documentation
LenaHarqTestCase()
LenaHarqTestCase::LenaHarqTestCase (uint16_t nUser, uint16_t dist, uint16_t tbSize, double amcBer, double thrRef)
Constructor.
Parameters
nUser the number of UE nodes
dist the distance between n odes
tbSize
amcBer the AMC bit error rate
thrRef the throughput reference
Definition at line 91 of file lte-test-harq.cc.
~LenaHarqTestCase()
LenaHarqTestCase::~LenaHarqTestCase () virtual
Definition at line 100 of file lte-test-harq.cc.
Member Function Documentation
BuildNameString()
std::string LenaHarqTestCase::BuildNameString (uint16_t nUser, uint16_t dist, uint16_t tbSize) static private
Build name string function.
Parameters
nUser number of UE nodes
dist distance between nodes
tbSize
Returns
name string
Definition at line 84 of file lte-test-harq.cc.
DoRun()
void LenaHarqTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Initialize Simulation Scenario: 1 eNB and m_nUser UEs
Check that the assignment is done in a RR fashion
Implements ns3::TestCase.
Definition at line 105 of file lte-test-harq.cc.
References ns3::LteHelper::ActivateDataRadioBearer(), ns3::LteHelper::Attach(), ns3::NodeContainer::Create(), ns3::TestCase::CreateTempDirFilename(), ns3::LteHelper::EnableMacTraces(), ns3::LteHelper::EnableRlcTraces(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::RadioBearerStatsCalculator::GetDlRxData(), ns3::RadioBearerStatsCalculator::GetDlTxData(), ns3::Object::GetObject(), ns3::LteEnbNetDevice::GetPhy(), ns3::LteUeNetDevice::GetPhy(), ns3::LteHelper::GetRlcStats(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), m_amcBer, m_dist, m_nUser, m_throughputRef, third::mobility, NS_LOG_INFO, NS_TEST_ASSERT_MSG_EQ_TOL, ns3::Seconds(), ns3::ObjectBase::SetAttribute(), ns3::Config::SetDefault(), ns3::LteHelper::SetPathlossModelAttribute(), ns3::MobilityModel::SetPosition(), ns3::LteHelper::SetSchedulerAttribute(), and ns3::LteHelper::SetSchedulerType().
Member Data Documentation
m_amcBer
double LenaHarqTestCase::m_amcBer private
AMC bit error rate.
Definition at line 69 of file lte-test-harq.h.
Referenced by DoRun().
m_dist
uint16_t LenaHarqTestCase::m_dist private
distance between nodes
Definition at line 68 of file lte-test-harq.h.
Referenced by DoRun().
m_nUser
uint16_t LenaHarqTestCase::m_nUser private
number of UE nodes
Definition at line 67 of file lte-test-harq.h.
Referenced by DoRun().
m_throughputRef
double LenaHarqTestCase::m_throughputRef private
throughput reference
Definition at line 70 of file lte-test-harq.h.
Referenced by DoRun().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-harq.h
src/lte/test/lte-test-harq.cc