ns-3: ns3::TriangularRandomVariable Class Reference
ns3::TriangularRandomVariable Class Reference
Core » Random Variables
The triangular distribution Random Number Generator (RNG) that allows stream numbers to be set deterministically.
#include "random-variable-stream.h"
Public Member Functions
TriangularRandomVariable ()
Creates a triangular distribution RNG with the default values for the mean, lower bound, and upper bound.
uint32_t GetInteger (uint32_t mean, uint32_t min, uint32_t max)
Returns a random unsigned integer from a triangular distribution with the specified mean, min, and max.
virtual uint32_t GetInteger (void)
Returns a random unsigned integer from a triangular distribution with the current mean, min, and max.
double GetMax (void) const
Returns the upper bound on values that can be returned by this RNG stream.
double GetMean (void) const
Returns the mean value for the triangular distribution returned by this RNG stream.
double GetMin (void) const
Returns the lower bound for the triangular distribution returned by this RNG stream.
double GetValue (double mean, double min, double max)
Returns a random double from a triangular distribution with the specified mean, min, and max.
virtual double GetValue (void)
Returns a random double from a triangular distribution with the current mean, min, and max.
Public Member Functions inherited from ns3::RandomVariableStream
RandomVariableStream ()
Default constructor.
virtual ~RandomVariableStream ()
Destructor.
int64_t GetStream (void) const
Returns the stream number for the RngStream.
bool IsAntithetic (void) const
Check if antithetic values will be generated.
void SetAntithetic (bool isAntithetic)
Specify whether antithetic values should be generated.
void SetStream (int64_t stream)
Specifies the stream number for the RngStream.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::RandomVariableStream
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
double m_max
The upper bound on values that can be returned by this RNG stream.
double m_mean
The mean value for the triangular distribution returned by this RNG stream.
double m_min
The lower bound on values that can be returned by this RNG stream.
Additional Inherited Members
Protected Member Functions inherited from ns3::RandomVariableStream
RngStream * Peek (void) const
Get the pointer to the underlying RngStream.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The triangular distribution Random Number Generator (RNG) that allows stream numbers to be set deterministically.
This class supports the creation of objects that return random numbers from a fixed triangular distribution. It also supports the generation of single random numbers from various triangular distributions.
This distribution is a triangular distribution. The probability density is in the shape of a triangle.
Here is an example of how to use this class:
double mean = 5.0;
double min = 2.0;
double max = 10.0;
Ptr<TriangularRandomVariable> x = CreateObject<TriangularRandomVariable> ();
x->SetAttribute ("Mean", DoubleValue (mean));
x->SetAttribute ("Min", DoubleValue (min));
x->SetAttribute ("Max", DoubleValue (max));
// The expected value for the mean of the values returned by a
// triangularly distributed random variable is equal to mean.
double value = x->GetValue ();
Definition at line 1837 of file random-variable-stream.h.
Constructor & Destructor Documentation
TriangularRandomVariable()
ns3::TriangularRandomVariable::TriangularRandomVariable ()
Creates a triangular distribution RNG with the default values for the mean, lower bound, and upper bound.
Definition at line 1213 of file random-variable-stream.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
GetInteger() [1/2]
uint32_t ns3::TriangularRandomVariable::GetInteger (uint32_t mean, uint32_t min, uint32_t max)
Returns a random unsigned integer from a triangular distribution with the specified mean, min, and max.
Parameters
[in] mean Mean value for the triangular distribution.
[in] min Low end of the range.
[in] max High end of the range.
Returns
A random unsigned integer value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If is a uniform variable over [0,1] and
is a value that would be returned normally, where the mode or peak of the triangle is calculated as
Then,) is the distance that would be from . The value returned in the antithetic case, , is calculated as
which now involves the distance is from the 1.
Definition at line 1265 of file random-variable-stream.cc.
References GetValue(), ns3::max(), ns3::min(), and NS_LOG_FUNCTION.
GetInteger() [2/2]
uint32_t ns3::TriangularRandomVariable::GetInteger (void) virtual
Returns a random unsigned integer from a triangular distribution with the current mean, min, and max.
Returns
A random unsigned integer value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If is a uniform variable over [0,1] and
is a value that would be returned normally, where the mode or peak of the triangle is calculated as
Then,) is the distance that would be from . The value returned in the antithetic case, , is calculated as
which now involves the distance is from the 1.
Implements ns3::RandomVariableStream.
Definition at line 1278 of file random-variable-stream.cc.
References GetValue(), m_max, m_mean, m_min, and NS_LOG_FUNCTION.
GetMax()
double ns3::TriangularRandomVariable::GetMax (void) const
Returns the upper bound on values that can be returned by this RNG stream.
Returns
The upper bound on values that can be returned by this RNG stream.
Definition at line 1233 of file random-variable-stream.cc.
References m_max, and NS_LOG_FUNCTION.
GetMean()
double ns3::TriangularRandomVariable::GetMean (void) const
Returns the mean value for the triangular distribution returned by this RNG stream.
Returns
The mean value for the triangular distribution returned by this RNG stream.
Definition at line 1221 of file random-variable-stream.cc.
References m_mean, and NS_LOG_FUNCTION.
GetMin()
double ns3::TriangularRandomVariable::GetMin (void) const
Returns the lower bound for the triangular distribution returned by this RNG stream.
Returns
The lower bound for the triangular distribution returned by this RNG stream.
Definition at line 1227 of file random-variable-stream.cc.
References m_min, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::TriangularRandomVariable::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 1192 of file random-variable-stream.cc.
References m_max, m_mean, m_min, ns3::MakeDoubleAccessor(), and ns3::TypeId::SetParent().
GetValue() [1/2]
double ns3::TriangularRandomVariable::GetValue (double mean, double min, double max)
Returns a random double from a triangular distribution with the specified mean, min, and max.
Parameters
[in] mean Mean value for the triangular distribution.
[in] min Low end of the range.
[in] max High end of the range.
Returns
A floating point random value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If is a uniform variable over [0,1] and
is a value that would be returned normally, where the mode or peak of the triangle is calculated as
Then,) is the distance that would be from . The value returned in the antithetic case, , is calculated as
which now involves the distance is from the 1.
Definition at line 1240 of file random-variable-stream.cc.
References ns3::RandomVariableStream::IsAntithetic(), ns3::max(), ns3::min(), NS_LOG_FUNCTION, ns3::RandomVariableStream::Peek(), and ns3::RngStream::RandU01().
GetValue() [2/2]
double ns3::TriangularRandomVariable::GetValue (void) virtual
Returns a random double from a triangular distribution with the current mean, min, and max.
Returns
A floating point random value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If is a uniform variable over [0,1] and
is a value that would be returned normally, where the mode or peak of the triangle is calculated as
Then,) is the distance that would be from . The value returned in the antithetic case, , is calculated as
which now involves the distance is from the 1.
Note that we have to re-implement this method here because the method is overloaded above for the three-argument variant and the c++ name resolution rules don't work well with overloads split between parent and child classes.
Implements ns3::RandomVariableStream.
Definition at line 1272 of file random-variable-stream.cc.
References m_max, m_mean, m_min, and NS_LOG_FUNCTION.
Referenced by GetInteger().
Member Data Documentation
m_max
double ns3::TriangularRandomVariable::m_max private
The upper bound on values that can be returned by this RNG stream.
Definition at line 2037 of file random-variable-stream.h.
Referenced by GetInteger(), GetMax(), GetTypeId(), and GetValue().
m_mean
double ns3::TriangularRandomVariable::m_mean private
The mean value for the triangular distribution returned by this RNG stream.
Definition at line 2031 of file random-variable-stream.h.
Referenced by GetInteger(), GetMean(), GetTypeId(), and GetValue().
m_min
double ns3::TriangularRandomVariable::m_min private
The lower bound on values that can be returned by this RNG stream.
Definition at line 2034 of file random-variable-stream.h.
Referenced by GetInteger(), GetMin(), GetTypeId(), and GetValue().
The documentation for this class was generated from the following files:
src/core/model/random-variable-stream.h
src/core/model/random-variable-stream.cc