ns-3: ns3::ThreeGppChannelModel Class Reference
ns3::ThreeGppChannelModel Class Reference
Spectrum Models
Channel Matrix Generation following 3GPP TR 38.901.
#include "three-gpp-channel-model.h"
Classes
struct ParamsTable
Data structure that stores the parameters of 3GPP TR 38.901, Table 7.5-6, for a certain scenario.
struct ThreeGppChannelMatrix
Data structure that stores a channel realization.
Public Types
typedef std::vector< ThreeGppAntennaArrayModel::ComplexVector > Complex2DVector
type definition for complex matrices
typedef std::vector< Complex2DVector > Complex3DVector
type definition for complex 3D matrices
typedef std::vector< DoubleVector > Double2DVector
type definition for matrices of doubles
typedef std::vector< Double2DVector > Double3DVector
type definition for 3D matrices of doubles
typedef std::vector< double > DoubleVector
type definition for vectors of doubles
Public Member Functions
ThreeGppChannelModel ()
Constructor.
~ThreeGppChannelModel ()
Destructor.
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Ptr< const ThreeGppChannelMatrix > GetChannel (Ptr< const MobilityModel > aMob, Ptr< const MobilityModel > bMob, Ptr< const ThreeGppAntennaArrayModel > aAntenna, Ptr< const ThreeGppAntennaArrayModel > bAntenna)
Looks for the channel matrix associated to the aMob and bMob pair in m_channelMap.
Ptr< ChannelConditionModel > GetChannelConditionModel () const
Get the associated channel condition model.
double GetFrequency (void) const
Returns the center frequency.
std::string GetScenario (void) const
Returns the propagation scenario.
void SetChannelConditionModel (Ptr< ChannelConditionModel > model)
Set the channel condition model.
void SetFrequency (double f)
Sets the center frequency of the model.
void SetScenario (const std::string &scenario)
Sets the propagation scenario.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static constexpr uint32_t GetKey (uint32_t x1, uint32_t x2)
Calculate the channel key using the Cantor function.
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static const uint8_t AOA_INDEX = 0
index of the AOA value in the m_angle array
static const uint8_t AOD_INDEX = 2
index of the AOD value in the m_angle array
static const uint8_t PHI_INDEX = 0
index of the PHI value in the m_nonSelfBlocking array
static const uint8_t R_INDEX = 4
index of the R value in the m_nonSelfBlocking array
static const uint8_t THETA_INDEX = 2
index of the THETA value in the m_nonSelfBlocking array
static const uint8_t X_INDEX = 1
index of the X value in the m_nonSelfBlocking array
static const uint8_t Y_INDEX = 3
index of the Y value in the m_nonSelfBlocking array
static const uint8_t ZOA_INDEX = 1
index of the ZOA value in the m_angle array
static const uint8_t ZOD_INDEX = 3
index of the ZOD value in the m_angle array
Private Member Functions
DoubleVector CalcAttenuationOfBlockage (Ptr< ThreeGppChannelMatrix > params, const DoubleVector &clusterAOA, const DoubleVector &clusterZOA) const
Applies the blockage model A described in 3GPP TR 38.901.
bool ChannelMatrixNeedsUpdate (Ptr< const ThreeGppChannelMatrix > channelMatrix, bool isLos) const
Check if the channel matrix has to be updated.
Ptr< ThreeGppChannelMatrix > GetNewChannel (Vector locUT, bool los, bool o2i, Ptr< const ThreeGppAntennaArrayModel > sAntenna, Ptr< const ThreeGppAntennaArrayModel > uAntenna, Angles &uAngle, Angles &sAngle, double dis2D, double hBS, double hUT) const
Compute the channel matrix between two devices using the procedure described in 3GPP TR 38.901.
Ptr< const ParamsTable > GetThreeGppTable (bool los, bool o2i, double hBS, double hUT, double distance2D) const
Get the parameters needed to apply the channel generation procedure.
Private Attributes
bool m_blockage
enables the blockage model A
double m_blockerSpeed
the blocker speed
Ptr< ChannelConditionModel > m_channelConditionModel
the channel condition model
std::unordered_map< uint32_t, Ptr< ThreeGppChannelMatrix > > m_channelMap
map containing the channel realizations
double m_frequency
the operating frequency
Ptr< NormalRandomVariable > m_normalRv
normal random variable
uint16_t m_numNonSelfBlocking
number of non-self-blocking regions
bool m_portraitMode
true if potrait mode, false if landscape
std::string m_scenario
the 3GPP scenario
Ptr< UniformRandomVariable > m_uniformRv
uniform random variable
Time m_updatePeriod
the channel update period
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Channel Matrix Generation following 3GPP TR 38.901.
The class implements the channel matrix generation procedure described in 3GPP TR 38.901.
See also
GetChannel
Definition at line 48 of file three-gpp-channel-model.h.
Member Typedef Documentation
Complex2DVector
typedef std::vector<ThreeGppAntennaArrayModel::ComplexVector> ns3::ThreeGppChannelModel::Complex2DVector
type definition for complex matrices
Definition at line 70 of file three-gpp-channel-model.h.
Complex3DVector
typedef std::vector<Complex2DVector> ns3::ThreeGppChannelModel::Complex3DVector
type definition for complex 3D matrices
Definition at line 71 of file three-gpp-channel-model.h.
Double2DVector
typedef std::vector<DoubleVector> ns3::ThreeGppChannelModel::Double2DVector
type definition for matrices of doubles
Definition at line 68 of file three-gpp-channel-model.h.
Double3DVector
typedef std::vector<Double2DVector> ns3::ThreeGppChannelModel::Double3DVector
type definition for 3D matrices of doubles
Definition at line 69 of file three-gpp-channel-model.h.
DoubleVector
typedef std::vector<double> ns3::ThreeGppChannelModel::DoubleVector
type definition for vectors of doubles
Definition at line 67 of file three-gpp-channel-model.h.
Constructor & Destructor Documentation
ThreeGppChannelModel()
ns3::ThreeGppChannelModel::ThreeGppChannelModel ()
Constructor.
Definition at line 163 of file three-gpp-channel-model.cc.
References m_normalRv, m_uniformRv, and NS_LOG_FUNCTION.
~ThreeGppChannelModel()
ns3::ThreeGppChannelModel::~ThreeGppChannelModel ()
Destructor.
Definition at line 173 of file three-gpp-channel-model.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AssignStreams()
int64_t ns3::ThreeGppChannelModel::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 1801 of file three-gpp-channel-model.cc.
References m_normalRv, m_uniformRv, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
CalcAttenuationOfBlockage()
ThreeGppChannelModel::DoubleVector ns3::ThreeGppChannelModel::CalcAttenuationOfBlockage (Ptr< ThreeGppChannelMatrix > params, const DoubleVector & clusterAOA, const DoubleVector & clusterZOA) const private
Applies the blockage model A described in 3GPP TR 38.901.
Parameters
params the channel matrix
clusterAOA vector containing the azimuth angle of arrival for each cluster
clusterZOA vector containing the zenith angle of arrival for each cluster
Returns
vector containing the power attenuation for each cluster
Definition at line 1581 of file three-gpp-channel-model.cc.
References ns3::UniformRandomVariable::GetValue(), m_blockerSpeed, m_frequency, m_normalRv, m_numNonSelfBlocking, m_portraitMode, m_scenario, m_uniformRv, ns3::Now(), NS_ASSERT_MSG(), NS_LOG_FUNCTION, NS_LOG_INFO, aloha::params, PHI_INDEX, R_INDEX, THETA_INDEX, X_INDEX, and Y_INDEX.
Referenced by GetNewChannel().
ChannelMatrixNeedsUpdate()
bool ns3::ThreeGppChannelModel::ChannelMatrixNeedsUpdate (Ptr< const ThreeGppChannelMatrix > channelMatrix, bool isLos) const private
Check if the channel matrix has to be updated.
Parameters
channelMatrix channel matrix
isLos the current los condition
Returns
true if the channel matrix has to be updated, false otherwise
Definition at line 710 of file three-gpp-channel-model.cc.
References ns3::Time::GetNanoSeconds(), ns3::Time::IsZero(), ns3::ThreeGppChannelModel::ThreeGppChannelMatrix::m_generatedTime, ns3::ThreeGppChannelModel::ThreeGppChannelMatrix::m_los, m_updatePeriod, ns3::Simulator::Now(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by GetChannel().
GetChannel()
Ptr< const ThreeGppChannelModel::ThreeGppChannelMatrix > ns3::ThreeGppChannelModel::GetChannel (Ptr< const MobilityModel > aMob, Ptr< const MobilityModel > bMob, Ptr< const ThreeGppAntennaArrayModel > aAntenna, Ptr< const ThreeGppAntennaArrayModel > bAntenna)
Looks for the channel matrix associated to the aMob and bMob pair in m_channelMap.
If found, it checks if it has to be updated. If not found or if it has to be updated, it generates a new uncorrelated channel matrix using the method GetNewChannel and updates m_channelMap.
We assume channel reciprocity between each node pair (i.e., H_ab = H_ba^T), therefore GetChannel (a, b) and GetChannel (b, a) will return the same ThreeGppChannelMatrix object. To understand if the channel matrix corresponds to H_ab or H_ba, we provide the method ThreeGppChannelMatrix::IsReverse. For instance, if the channel matrix corresponds to H_ab, a call to IsReverse (idA, idB) will return false, conversely, IsReverse (idB, idA) will return true.
Parameters
aMob mobility model of the a device
bMob mobility model of the b device
aAntenna antenna of the a device
bAntenna antenna of the b device
Returns
the channel matrix
Definition at line 734 of file three-gpp-channel-model.cc.
References ChannelMatrixNeedsUpdate(), ns3::Node::GetId(), GetKey(), GetNewChannel(), m_channelConditionModel, m_channelMap, ns3::ThreeGppChannelModel::ThreeGppChannelMatrix::m_nodeIds, max, min, NS_LOG_DEBUG, NS_LOG_FUNCTION, and sample-rng-plot::x.
Referenced by ThreeGppChannelMatrixComputationTest::DoComputeNorm(), ThreeGppChannelMatrixUpdateTest::DoGetChannel(), and ThreeGppChannelMatrixComputationTest::DoRun().
GetChannelConditionModel()
Ptr< ChannelConditionModel > ns3::ThreeGppChannelModel::GetChannelConditionModel () const
Get the associated channel condition model.
Returns
a pointer to the ChannelConditionModel object
Definition at line 241 of file three-gpp-channel-model.cc.
References m_channelConditionModel, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetFrequency()
double ns3::ThreeGppChannelModel::GetFrequency (void) const
Returns the center frequency.
Returns
the center frequency in Hz
Definition at line 256 of file three-gpp-channel-model.cc.
References m_frequency, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetKey()
static constexpr uint32_t ns3::ThreeGppChannelModel::GetKey (uint32_t x1, uint32_t x2) inline static constexpr
Calculate the channel key using the Cantor function.
Parameters
x1 first value
x2 second value
Returns
Definition at line 203 of file three-gpp-channel-model.h.
Referenced by GetChannel(), and ns3::ThreeGppSpectrumPropagationLossModel::GetLongTerm().
GetNewChannel()
Ptr< ThreeGppChannelModel::ThreeGppChannelMatrix > ns3::ThreeGppChannelModel::GetNewChannel (Vector locUT, bool los, bool o2i, Ptr< const ThreeGppAntennaArrayModel > sAntenna, Ptr< const ThreeGppAntennaArrayModel > uAntenna, Angles & uAngle, Angles & sAngle, double dis2D, double hBS, double hUT) const private
Compute the channel matrix between two devices using the procedure described in 3GPP TR 38.901.
Parameters
locUT the location of the UT
los the LOS/NLOS condition
o2i whether if it is an outdoor to indoor transmission
sAntenna the s node antenna array
uAntenna the u node antenna array
uAngle the u node angle
sAngle the s node angle
dis2D the 2D distance between tx and rx
hBS the height of the BS
hUT the height of the UT
Returns
the channel realization
Definition at line 805 of file three-gpp-channel-model.cc.
References CalcAttenuationOfBlockage(), GetThreeGppTable(), ns3::UniformRandomVariable::GetValue(), ns3::if(), ns3::ThreeGppChannelModel::ThreeGppChannelMatrix::m_angle, m_blockage, ns3::ThreeGppChannelModel::ParamsTable::m_cASA, ns3::ThreeGppChannelModel::ParamsTable::m_cASD, ns3::ThreeGppChannelModel::ParamsTable::m_cDS, ns3::ThreeGppChannelModel::ThreeGppChannelMatrix::m_channel, ns3::ThreeGppChannelModel::ThreeGppChannelMatrix::m_clusterPhase, ns3::ThreeGppChannelModel::ParamsTable::m_cZSA, ns3::ThreeGppChannelModel::ThreeGppChannelMatrix::m_delay, ns3::ThreeGppChannelModel::ThreeGppChannelMatrix::m_DS, m_frequency, ns3::ThreeGppChannelModel::ThreeGppChannelMatrix::m_generatedTime, ns3::ThreeGppChannelModel::ThreeGppChannelMatrix::m_K, ns3::ThreeGppChannelModel::ThreeGppChannelMatrix::m_los, m_normalRv, ns3::ThreeGppChannelModel::ThreeGppChannelMatrix::m_numCluster, ns3::ThreeGppChannelModel::ParamsTable::m_numOfCluster, ns3::ThreeGppChannelModel::ThreeGppChannelMatrix::m_o2i, ns3::ThreeGppChannelModel::ParamsTable::m_offsetZOD, ns3::ThreeGppChannelModel::ParamsTable::m_perClusterShadowingStd, ns3::ThreeGppChannelModel::ParamsTable::m_raysPerCluster, ns3::ThreeGppChannelModel::ParamsTable::m_rTau, ns3::ThreeGppChannelModel::ParamsTable::m_sigK, ns3::ThreeGppChannelModel::ParamsTable::m_sigLgASA, ns3::ThreeGppChannelModel::ParamsTable::m_sigLgASD, ns3::ThreeGppChannelModel::ParamsTable::m_sigLgDS, ns3::ThreeGppChannelModel::ParamsTable::m_sigLgZSA, ns3::ThreeGppChannelModel::ParamsTable::m_sigLgZSD, ns3::ThreeGppChannelModel::ParamsTable::m_sigXpr, ns3::ThreeGppChannelModel::ParamsTable::m_sqrtC, ns3::ThreeGppChannelModel::ParamsTable::m_uK, ns3::ThreeGppChannelModel::ParamsTable::m_uLgASA, ns3::ThreeGppChannelModel::ParamsTable::m_uLgASD, ns3::ThreeGppChannelModel::ParamsTable::m_uLgDS, ns3::ThreeGppChannelModel::ParamsTable::m_uLgZSA, ns3::ThreeGppChannelModel::ParamsTable::m_uLgZSD, m_uniformRv, ns3::ThreeGppChannelModel::ParamsTable::m_uXpr, ns3::max(), min, ns3::min(), ns3::Simulator::Now(), NS_ASSERT_MSG(), NS_FATAL_ERROR, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::offSetAlpha, ns3::Angles::phi, and ns3::Angles::theta.
Referenced by GetChannel().
GetScenario()
std::string ns3::ThreeGppChannelModel::GetScenario (void) const
Returns the propagation scenario.
Returns
the propagation scenario
Definition at line 273 of file three-gpp-channel-model.cc.
References m_scenario, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetThreeGppTable()
Ptr< const ThreeGppChannelModel::ParamsTable > ns3::ThreeGppChannelModel::GetThreeGppTable (bool los, bool o2i, double hBS, double hUT, double distance2D) const private
Get the parameters needed to apply the channel generation procedure.
Parameters
los the LOS/NLOS condition
o2i whether if it is an outdoor to indoor transmission
hBS the height of the BS
hUT the height of the UT
distance2D the 2D distance between tx and rx
Returns
the parameters table
Definition at line 280 of file three-gpp-channel-model.cc.
References ns3::ThreeGppChannelModel::ParamsTable::m_cASA, ns3::ThreeGppChannelModel::ParamsTable::m_cASD, ns3::ThreeGppChannelModel::ParamsTable::m_cDS, ns3::ThreeGppChannelModel::ParamsTable::m_cZSA, m_frequency, ns3::ThreeGppChannelModel::ParamsTable::m_numOfCluster, ns3::ThreeGppChannelModel::ParamsTable::m_offsetZOD, ns3::ThreeGppChannelModel::ParamsTable::m_perClusterShadowingStd, ns3::ThreeGppChannelModel::ParamsTable::m_raysPerCluster, ns3::ThreeGppChannelModel::ParamsTable::m_rTau, m_scenario, ns3::ThreeGppChannelModel::ParamsTable::m_sigK, ns3::ThreeGppChannelModel::ParamsTable::m_sigLgASA, ns3::ThreeGppChannelModel::ParamsTable::m_sigLgASD, ns3::ThreeGppChannelModel::ParamsTable::m_sigLgDS, ns3::ThreeGppChannelModel::ParamsTable::m_sigLgZSA, ns3::ThreeGppChannelModel::ParamsTable::m_sigLgZSD, ns3::ThreeGppChannelModel::ParamsTable::m_sigXpr, ns3::ThreeGppChannelModel::ParamsTable::m_sqrtC, ns3::ThreeGppChannelModel::ParamsTable::m_uK, ns3::ThreeGppChannelModel::ParamsTable::m_uLgASA, ns3::ThreeGppChannelModel::ParamsTable::m_uLgASD, ns3::ThreeGppChannelModel::ParamsTable::m_uLgDS, ns3::ThreeGppChannelModel::ParamsTable::m_uLgZSA, ns3::ThreeGppChannelModel::ParamsTable::m_uLgZSD, ns3::ThreeGppChannelModel::ParamsTable::m_uXpr, max, NS_ASSERT_MSG(), NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::sqrtC_office_LOS, ns3::sqrtC_office_NLOS, ns3::sqrtC_RMa_LOS, ns3::sqrtC_RMa_NLOS, ns3::sqrtC_RMa_O2I, ns3::sqrtC_UMa_LOS, ns3::sqrtC_UMa_NLOS, ns3::sqrtC_UMa_O2I, ns3::sqrtC_UMi_LOS, ns3::sqrtC_UMi_NLOS, and ns3::sqrtC_UMi_O2I.
Referenced by GetNewChannel().
GetTypeId()
TypeId ns3::ThreeGppChannelModel::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 179 of file three-gpp-channel-model.cc.
References GetChannelConditionModel(), GetFrequency(), GetScenario(), m_blockage, m_blockerSpeed, m_numNonSelfBlocking, m_portraitMode, m_updatePeriod, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeDoubleAccessor(), ns3::MakeIntegerAccessor(), ns3::MakePointerAccessor(), ns3::MakeStringAccessor(), ns3::MakeStringChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MilliSeconds(), SetChannelConditionModel(), SetFrequency(), ns3::TypeId::SetParent(), and SetScenario().
SetChannelConditionModel()
void ns3::ThreeGppChannelModel::SetChannelConditionModel (Ptr< ChannelConditionModel > model)
Set the channel condition model.
Parameters
a pointer to the ChannelConditionModel object
Definition at line 234 of file three-gpp-channel-model.cc.
References m_channelConditionModel, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetFrequency()
void ns3::ThreeGppChannelModel::SetFrequency (double f)
Sets the center frequency of the model.
Parameters
f the center frequency in Hz
Definition at line 248 of file three-gpp-channel-model.cc.
References f(), m_frequency, NS_ASSERT_MSG(), and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetScenario()
void ns3::ThreeGppChannelModel::SetScenario (const std::string & scenario)
Sets the propagation scenario.
Parameters
scenario the propagation scenario
Definition at line 263 of file three-gpp-channel-model.cc.
References m_scenario, NS_ASSERT_MSG(), and NS_LOG_FUNCTION.
Referenced by GetTypeId().
Member Data Documentation
AOA_INDEX
const uint8_t ns3::ThreeGppChannelModel::AOA_INDEX = 0 static
index of the AOA value in the m_angle array
Definition at line 186 of file three-gpp-channel-model.h.
Referenced by ns3::ThreeGppSpectrumPropagationLossModel::CalcBeamformingGain().
AOD_INDEX
const uint8_t ns3::ThreeGppChannelModel::AOD_INDEX = 2 static
index of the AOD value in the m_angle array
Definition at line 188 of file three-gpp-channel-model.h.
Referenced by ns3::ThreeGppSpectrumPropagationLossModel::CalcBeamformingGain().
m_blockage
bool ns3::ThreeGppChannelModel::m_blockage private
enables the blockage model A
Definition at line 302 of file three-gpp-channel-model.h.
Referenced by GetNewChannel(), and GetTypeId().
m_blockerSpeed
double ns3::ThreeGppChannelModel::m_blockerSpeed private
the blocker speed
Definition at line 305 of file three-gpp-channel-model.h.
Referenced by CalcAttenuationOfBlockage(), and GetTypeId().
m_channelConditionModel
Ptr<ChannelConditionModel> ns3::ThreeGppChannelModel::m_channelConditionModel private
the channel condition model
Definition at line 297 of file three-gpp-channel-model.h.
Referenced by GetChannel(), GetChannelConditionModel(), and SetChannelConditionModel().
m_channelMap
std::unordered_map<uint32_t, Ptr<ThreeGppChannelMatrix> > ns3::ThreeGppChannelModel::m_channelMap private
map containing the channel realizations
Definition at line 293 of file three-gpp-channel-model.h.
Referenced by GetChannel().
m_frequency
double ns3::ThreeGppChannelModel::m_frequency private
the operating frequency
Definition at line 295 of file three-gpp-channel-model.h.
Referenced by CalcAttenuationOfBlockage(), GetFrequency(), GetNewChannel(), GetThreeGppTable(), and SetFrequency().
m_normalRv
Ptr<NormalRandomVariable> ns3::ThreeGppChannelModel::m_normalRv private
normal random variable
Definition at line 299 of file three-gpp-channel-model.h.
Referenced by ThreeGppChannelModel(), AssignStreams(), CalcAttenuationOfBlockage(), and GetNewChannel().
m_numNonSelfBlocking
uint16_t ns3::ThreeGppChannelModel::m_numNonSelfBlocking private
number of non-self-blocking regions
Definition at line 303 of file three-gpp-channel-model.h.
Referenced by CalcAttenuationOfBlockage(), and GetTypeId().
m_portraitMode
bool ns3::ThreeGppChannelModel::m_portraitMode private
true if potrait mode, false if landscape
Definition at line 304 of file three-gpp-channel-model.h.
Referenced by CalcAttenuationOfBlockage(), and GetTypeId().
m_scenario
std::string ns3::ThreeGppChannelModel::m_scenario private
the 3GPP scenario
Definition at line 296 of file three-gpp-channel-model.h.
Referenced by CalcAttenuationOfBlockage(), GetScenario(), GetThreeGppTable(), and SetScenario().
m_uniformRv
Ptr<UniformRandomVariable> ns3::ThreeGppChannelModel::m_uniformRv private
uniform random variable
Definition at line 298 of file three-gpp-channel-model.h.
Referenced by ThreeGppChannelModel(), AssignStreams(), CalcAttenuationOfBlockage(), and GetNewChannel().
m_updatePeriod
Time ns3::ThreeGppChannelModel::m_updatePeriod private
the channel update period
Definition at line 294 of file three-gpp-channel-model.h.
Referenced by ChannelMatrixNeedsUpdate(), and GetTypeId().
PHI_INDEX
const uint8_t ns3::ThreeGppChannelModel::PHI_INDEX = 0 static
index of the PHI value in the m_nonSelfBlocking array
Definition at line 191 of file three-gpp-channel-model.h.
Referenced by CalcAttenuationOfBlockage().
R_INDEX
const uint8_t ns3::ThreeGppChannelModel::R_INDEX = 4 static
index of the R value in the m_nonSelfBlocking array
Definition at line 195 of file three-gpp-channel-model.h.
Referenced by CalcAttenuationOfBlockage().
THETA_INDEX
const uint8_t ns3::ThreeGppChannelModel::THETA_INDEX = 2 static
index of the THETA value in the m_nonSelfBlocking array
Definition at line 193 of file three-gpp-channel-model.h.
Referenced by CalcAttenuationOfBlockage().
X_INDEX
const uint8_t ns3::ThreeGppChannelModel::X_INDEX = 1 static
index of the X value in the m_nonSelfBlocking array
Definition at line 192 of file three-gpp-channel-model.h.
Referenced by CalcAttenuationOfBlockage().
Y_INDEX
const uint8_t ns3::ThreeGppChannelModel::Y_INDEX = 3 static
index of the Y value in the m_nonSelfBlocking array
Definition at line 194 of file three-gpp-channel-model.h.
Referenced by CalcAttenuationOfBlockage().
ZOA_INDEX
const uint8_t ns3::ThreeGppChannelModel::ZOA_INDEX = 1 static
index of the ZOA value in the m_angle array
Definition at line 187 of file three-gpp-channel-model.h.
Referenced by ns3::ThreeGppSpectrumPropagationLossModel::CalcBeamformingGain().
ZOD_INDEX
const uint8_t ns3::ThreeGppChannelModel::ZOD_INDEX = 3 static
index of the ZOD value in the m_angle array
Definition at line 189 of file three-gpp-channel-model.h.
Referenced by ns3::ThreeGppSpectrumPropagationLossModel::CalcBeamformingGain().
The documentation for this class was generated from the following files:
src/spectrum/model/three-gpp-channel-model.h
src/spectrum/model/three-gpp-channel-model.cc