ns-3: TcpHeaderWithRFC793OptionTestCase Class Reference
TcpHeaderWithRFC793OptionTestCase Class Reference
Internet » internet module tests | Test suites
TCP header with RFC793 Options test.
Public Member Functions
TcpHeaderWithRFC793OptionTestCase (std::string name)
Constructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CheckCorrectDeserialize ()
Check the correct header deserialization.
void CheckNoPadding ()
Check an header for the correct padding.
virtual void DoRun (void)
Implementation to actually run this TestCase.
virtual void DoTeardown (void)
Implementation to do any local setup required for this TestCase.
void OneOptionAtTime ()
Check an header with only one kind of option.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
TCP header with RFC793 Options test.
Definition at line 155 of file tcp-header-test.cc.
Constructor & Destructor Documentation
TcpHeaderWithRFC793OptionTestCase()
TcpHeaderWithRFC793OptionTestCase::TcpHeaderWithRFC793OptionTestCase (std::string name)
Constructor.
Parameters
name Test description.
Definition at line 183 of file tcp-header-test.cc.
Member Function Documentation
CheckCorrectDeserialize()
void TcpHeaderWithRFC793OptionTestCase::CheckCorrectDeserialize () private
Check the correct header deserialization.
Definition at line 198 of file tcp-header-test.cc.
References ns3::Buffer::AddAtStart(), ns3::TcpHeader::AppendOption(), ns3::Buffer::Begin(), ns3::TcpHeader::Deserialize(), ns3::TcpHeader::HasOption(), NS_TEST_ASSERT_MSG_EQ, ns3::Buffer::Iterator::ReadU8(), ns3::TcpHeader::Serialize(), and ns3::Buffer::Iterator::WriteU8().
Referenced by DoRun().
CheckNoPadding()
void TcpHeaderWithRFC793OptionTestCase::CheckNoPadding () private
Check an header for the correct padding.
Definition at line 220 of file tcp-header-test.cc.
References ns3::Buffer::AddAtStart(), ns3::TcpHeader::AppendOption(), ns3::Buffer::Begin(), ns3::TcpHeader::GetLength(), ns3::TcpHeader::GetSerializedSize(), ns3::Buffer::GetSize(), ns3::Buffer::Iterator::Next(), NS_TEST_ASSERT_MSG_EQ, ns3::Buffer::Iterator::ReadU8(), and ns3::TcpHeader::Serialize().
Referenced by DoRun().
DoRun()
void TcpHeaderWithRFC793OptionTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 190 of file tcp-header-test.cc.
References CheckCorrectDeserialize(), CheckNoPadding(), and OneOptionAtTime().
DoTeardown()
void TcpHeaderWithRFC793OptionTestCase::DoTeardown (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test teardown
Reimplemented from ns3::TestCase.
Definition at line 346 of file tcp-header-test.cc.
OneOptionAtTime()
void TcpHeaderWithRFC793OptionTestCase::OneOptionAtTime () private
Check an header with only one kind of option.
Definition at line 261 of file tcp-header-test.cc.
References ns3::Buffer::AddAtStart(), ns3::TcpHeader::AppendOption(), ns3::Buffer::Begin(), ns3::TcpHeader::Deserialize(), END, ns3::TcpHeader::GetLength(), ns3::TcpHeader::GetOptionLength(), ns3::TcpHeader::GetSerializedSize(), ns3::TcpOptionMSS::GetSerializedSize(), ns3::Buffer::GetSize(), ns3::TcpHeader::HasOption(), ns3::Buffer::Iterator::Next(), NS_TEST_ASSERT_MSG_EQ, ns3::Buffer::Iterator::ReadU8(), ns3::TcpHeader::Serialize(), and ns3::TcpOptionMSS::SetMSS().
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/internet/test/tcp-header-test.cc