ns-3: ns3::LteRlcSduStatusTag Class Reference
ns3::LteRlcSduStatusTag Class Reference
This class implements a tag that carries the status of a RLC SDU for the fragmentation process Status of RLC SDU.
#include "lte-rlc-sdu-status-tag.h"
Public Types
enum SduStatus_t {
FULL_SDU = 1, FIRST_SEGMENT = 2, MIDDLE_SEGMENT = 3, LAST_SEGMENT = 4,
ANY_SEGMENT = 5
}
SduStatus_t typedef.
Public Member Functions
LteRlcSduStatusTag ()
virtual void Deserialize (TagBuffer i)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize (void) const
uint8_t GetStatus (void) const
Get status function.
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer i) const
void SetStatus (uint8_t status)
Set status function.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_sduStatus
SDU status.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class implements a tag that carries the status of a RLC SDU for the fragmentation process Status of RLC SDU.
Definition at line 34 of file lte-rlc-sdu-status-tag.h.
Member Enumeration Documentation
SduStatus_t
enum ns3::LteRlcSduStatusTag::SduStatus_t
SduStatus_t typedef.
Enumerator
FULL_SDU
FIRST_SEGMENT
MIDDLE_SEGMENT
LAST_SEGMENT
ANY_SEGMENT
Definition at line 64 of file lte-rlc-sdu-status-tag.h.
Constructor & Destructor Documentation
LteRlcSduStatusTag()
ns3::LteRlcSduStatusTag::LteRlcSduStatusTag ()
Definition at line 27 of file lte-rlc-sdu-status-tag.cc.
Member Function Documentation
Deserialize()
void ns3::LteRlcSduStatusTag::Deserialize (TagBuffer i) virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 70 of file lte-rlc-sdu-status-tag.cc.
References m_sduStatus, and ns3::TagBuffer::ReadU8().
GetInstanceTypeId()
TypeId ns3::LteRlcSduStatusTag::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 54 of file lte-rlc-sdu-status-tag.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::LteRlcSduStatusTag::GetSerializedSize (void) const virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 60 of file lte-rlc-sdu-status-tag.cc.
GetStatus()
uint8_t ns3::LteRlcSduStatusTag::GetStatus (void) const
Get status function.
Returns
the status
Definition at line 38 of file lte-rlc-sdu-status-tag.cc.
References m_sduStatus.
Referenced by ns3::LteRlcAm::DoNotifyTxOpportunity(), and ns3::LteRlcUm::DoNotifyTxOpportunity().
GetTypeId()
TypeId ns3::LteRlcSduStatusTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 44 of file lte-rlc-sdu-status-tag.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::LteRlcSduStatusTag::Print (std::ostream & os) const virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 75 of file lte-rlc-sdu-status-tag.cc.
References m_sduStatus.
Serialize()
void ns3::LteRlcSduStatusTag::Serialize (TagBuffer i) const virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 65 of file lte-rlc-sdu-status-tag.cc.
References m_sduStatus, and ns3::TagBuffer::WriteU8().
SetStatus()
void ns3::LteRlcSduStatusTag::SetStatus (uint8_t status)
Set status function.
Parameters
status the status
Definition at line 32 of file lte-rlc-sdu-status-tag.cc.
References m_sduStatus.
Referenced by ns3::LteRlcAm::DoNotifyTxOpportunity(), ns3::LteRlcUm::DoNotifyTxOpportunity(), ns3::LteRlcAm::DoTransmitPdcpPdu(), and ns3::LteRlcUm::DoTransmitPdcpPdu().
Member Data Documentation
m_sduStatus
uint8_t ns3::LteRlcSduStatusTag::m_sduStatus private
SDU status.
Definition at line 71 of file lte-rlc-sdu-status-tag.h.
Referenced by Deserialize(), GetStatus(), Print(), Serialize(), and SetStatus().
The documentation for this class was generated from the following files:
src/lte/model/lte-rlc-sdu-status-tag.h
src/lte/model/lte-rlc-sdu-status-tag.cc