ns-3: ns3::UanPropModelThorp Class Reference
ns3::UanPropModelThorp Class Reference
UAN Models
#include "uan-prop-model-thorp.h"
Public Member Functions
UanPropModelThorp ()
Default constructor.
virtual ~UanPropModelThorp ()
Destructor.
virtual Time GetDelay (Ptr< MobilityModel > a, Ptr< MobilityModel > b, UanTxMode mode)
Finds propagation delay between nodes a and b.
virtual double GetPathLossDb (Ptr< MobilityModel > a, Ptr< MobilityModel > b, UanTxMode mode)
Computes pathloss between nodes a and b.
virtual UanPdp GetPdp (Ptr< MobilityModel > a, Ptr< MobilityModel > b, UanTxMode mode)
Get the PDP for the path between two nodes.
Public Member Functions inherited from ns3::UanPropModel
virtual void Clear (void)
Clear all pointer references.
virtual void DoDispose (void)
Destructor implementation.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::UanPropModel
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
double GetAttenDbKm (double freqKhz)
Get the attenuation in dB / km.
double GetAttenDbKyd (double freqKhz)
Get the attenuation in dB / 1000 yards.
Private Attributes
double m_SpreadCoef
Spreading coefficient used in calculation of Thorp's approximation.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Uses Thorp's approximation to compute pathloss. Assumes implulse PDP.
Definition at line 35 of file uan-prop-model-thorp.h.
Constructor & Destructor Documentation
UanPropModelThorp()
ns3::UanPropModelThorp::UanPropModelThorp ()
Default constructor.
Definition at line 31 of file uan-prop-model-thorp.cc.
~UanPropModelThorp()
ns3::UanPropModelThorp::~UanPropModelThorp () virtual
Destructor.
Definition at line 35 of file uan-prop-model-thorp.cc.
Member Function Documentation
GetAttenDbKm()
double ns3::UanPropModelThorp::GetAttenDbKm (double freqKhz) private
Get the attenuation in dB / km.
Parameters
freqKhz The channel center frequency, in kHz.
Returns
The attenuation, in dB/km.
Definition at line 84 of file uan-prop-model-thorp.cc.
Referenced by GetAttenDbKyd(), and GetPathLossDb().
GetAttenDbKyd()
double ns3::UanPropModelThorp::GetAttenDbKyd (double freqKhz) private
Get the attenuation in dB / 1000 yards.
Parameters
freqKhz The channel center frequency, in kHz.
Returns
The attenuation, in dB / 1000 yards.
Definition at line 77 of file uan-prop-model-thorp.cc.
References GetAttenDbKm().
GetDelay()
Time ns3::UanPropModelThorp::GetDelay (Ptr< MobilityModel > a, Ptr< MobilityModel > b, UanTxMode mode) virtual
Finds propagation delay between nodes a and b.
Parameters
a Ptr to mobility model of node a.
b Ptr to mobility model of node b.
mode TX mode of transmission.
Returns
Propagation delay.
Implements ns3::UanPropModel.
Definition at line 71 of file uan-prop-model-thorp.cc.
References ns3::MobilityModel::GetDistanceFrom(), and ns3::Seconds().
GetPathLossDb()
double ns3::UanPropModelThorp::GetPathLossDb (Ptr< MobilityModel > a, Ptr< MobilityModel > b, UanTxMode txMode) virtual
Computes pathloss between nodes a and b.
Parameters
a Ptr to mobility model of node a
b Ptr to mobility model of node b
txMode TX mode of transmission between a and b
Returns
Pathloss in dB re 1 uPa
Implements ns3::UanPropModel.
Definition at line 56 of file uan-prop-model-thorp.cc.
References GetAttenDbKm(), ns3::UanTxMode::GetCenterFreqHz(), ns3::MobilityModel::GetDistanceFrom(), and m_SpreadCoef.
GetPdp()
UanPdp ns3::UanPropModelThorp::GetPdp (Ptr< MobilityModel > a, Ptr< MobilityModel > b, UanTxMode mode) virtual
Get the PDP for the path between two nodes.
Parameters
a Ptr to mobility model of node a.
b Ptr to mobility model of node b.
mode TX mode of transmission from a to b.
Returns
PDP for link between nodes a and b.
Implements ns3::UanPropModel.
Definition at line 65 of file uan-prop-model-thorp.cc.
References ns3::UanPdp::CreateImpulsePdp().
GetTypeId()
TypeId ns3::UanPropModelThorp::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 40 of file uan-prop-model-thorp.cc.
References m_SpreadCoef, ns3::MakeDoubleAccessor(), and ns3::TypeId::SetParent().
Member Data Documentation
m_SpreadCoef
double ns3::UanPropModelThorp::m_SpreadCoef private
Spreading coefficient used in calculation of Thorp's approximation.
Definition at line 68 of file uan-prop-model-thorp.h.
Referenced by GetPathLossDb(), and GetTypeId().
The documentation for this class was generated from the following files:
src/uan/model/uan-prop-model-thorp.h
src/uan/model/uan-prop-model-thorp.cc