ns-3: ns3::dsdv::DsdvHeader Class Reference
ns3::dsdv::DsdvHeader Class Reference
DSDV Routing
DSDV Update Packet Format.
#include "dsdv-packet.h"
Public Member Functions
DsdvHeader (Ipv4Address dst=Ipv4Address(), uint32_t hopcount=0, uint32_t dstSeqNo=0)
Constructor.
virtual ~DsdvHeader ()
virtual uint32_t Deserialize (Buffer::Iterator start)
Ipv4Address GetDst () const
Get destination address.
uint32_t GetDstSeqno () const
Get destination sequence number.
uint32_t GetHopCount () const
Get hop count.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize () const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetDst (Ipv4Address destination)
Set destination address.
void SetDstSeqno (uint32_t sequenceNumber)
Set destination sequence number.
void SetHopCount (uint32_t hopCount)
Set hop count.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Ipv4Address m_dst
Destination IP Address.
uint32_t m_dstSeqNo
Destination Sequence Number.
uint32_t m_hopCount
Number of Hops.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
DSDV Update Packet Format.
|      0        |      1        |      2        |       3       |
 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                      Destination Address                      |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                            HopCount                           |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                       Sequence Number                         |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
*
Definition at line 58 of file dsdv-packet.h.
Constructor & Destructor Documentation
DsdvHeader()
ns3::dsdv::DsdvHeader::DsdvHeader (Ipv4Address dst = Ipv4Address (), uint32_t hopcount = 0, uint32_t dstSeqNo = 0)
Constructor.
Parameters
dst destination IP address
hopcount hop count
dstSeqNo destination sequence number
Definition at line 40 of file dsdv-packet.cc.
~DsdvHeader()
ns3::dsdv::DsdvHeader::~DsdvHeader () virtual
Definition at line 47 of file dsdv-packet.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::dsdv::DsdvHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 83 of file dsdv-packet.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), GetSerializedSize(), m_dst, m_dstSeqNo, m_hopCount, NS_ASSERT, ns3::ReadFrom(), ns3::Buffer::Iterator::ReadNtohU32(), and visualizer.core::start().
GetDst()
Ipv4Address ns3::dsdv::DsdvHeader::GetDst () const inline
Get destination address.
Returns
the destination IPv4 address
Definition at line 95 of file dsdv-packet.h.
References m_dst.
Referenced by DsdvHeaderTestCase::DoRun(), ns3::dsdv::RoutingProtocol::RecvDsdv(), ns3::dsdv::RoutingProtocol::SendPeriodicUpdate(), and ns3::dsdv::RoutingProtocol::SendTriggeredUpdate().
GetDstSeqno()
uint32_t ns3::dsdv::DsdvHeader::GetDstSeqno () const inline
Get destination sequence number.
Returns
the destination sequence number
Definition at line 131 of file dsdv-packet.h.
References m_dstSeqNo.
Referenced by DsdvHeaderTestCase::DoRun(), ns3::dsdv::RoutingProtocol::RecvDsdv(), and ns3::dsdv::RoutingProtocol::SendPeriodicUpdate().
GetHopCount()
uint32_t ns3::dsdv::DsdvHeader::GetHopCount () const inline
Get hop count.
Returns
the hop count
Definition at line 113 of file dsdv-packet.h.
References m_hopCount.
Referenced by DsdvHeaderTestCase::DoRun(), ns3::dsdv::RoutingProtocol::RecvDsdv(), and ns3::dsdv::RoutingProtocol::SendPeriodicUpdate().
GetInstanceTypeId()
TypeId ns3::dsdv::DsdvHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 62 of file dsdv-packet.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::dsdv::DsdvHeader::GetSerializedSize () const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 68 of file dsdv-packet.cc.
Referenced by Deserialize(), and DsdvHeaderTestCase::DoRun().
GetTypeId()
TypeId ns3::dsdv::DsdvHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 52 of file dsdv-packet.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::dsdv::DsdvHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 97 of file dsdv-packet.cc.
References m_dst, m_dstSeqNo, and m_hopCount.
Referenced by ns3::dsdv::operator<<().
Serialize()
void ns3::dsdv::DsdvHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 74 of file dsdv-packet.cc.
References m_dst, m_dstSeqNo, m_hopCount, ns3::Buffer::Iterator::WriteHtonU32(), and ns3::WriteTo().
SetDst()
void ns3::dsdv::DsdvHeader::SetDst (Ipv4Address destination) inline
Set destination address.
Parameters
destination the destination IPv4 address
Definition at line 86 of file dsdv-packet.h.
References m_dst.
Referenced by DsdvHeaderTestCase::DoRun(), ns3::dsdv::RoutingProtocol::SendPeriodicUpdate(), and ns3::dsdv::RoutingProtocol::SendTriggeredUpdate().
SetDstSeqno()
void ns3::dsdv::DsdvHeader::SetDstSeqno (uint32_t sequenceNumber) inline
Set destination sequence number.
Parameters
sequenceNumber The sequence number
Definition at line 122 of file dsdv-packet.h.
References m_dstSeqNo.
Referenced by DsdvHeaderTestCase::DoRun(), ns3::dsdv::RoutingProtocol::SendPeriodicUpdate(), and ns3::dsdv::RoutingProtocol::SendTriggeredUpdate().
SetHopCount()
void ns3::dsdv::DsdvHeader::SetHopCount (uint32_t hopCount) inline
Set hop count.
Parameters
hopCount the hop count
Definition at line 104 of file dsdv-packet.h.
References m_hopCount.
Referenced by DsdvHeaderTestCase::DoRun(), ns3::dsdv::RoutingProtocol::SendPeriodicUpdate(), and ns3::dsdv::RoutingProtocol::SendTriggeredUpdate().
Member Data Documentation
m_dst
Ipv4Address ns3::dsdv::DsdvHeader::m_dst private
Destination IP Address.
Definition at line 136 of file dsdv-packet.h.
Referenced by Deserialize(), GetDst(), Print(), Serialize(), and SetDst().
m_dstSeqNo
uint32_t ns3::dsdv::DsdvHeader::m_dstSeqNo private
Destination Sequence Number.
Definition at line 138 of file dsdv-packet.h.
Referenced by Deserialize(), GetDstSeqno(), Print(), Serialize(), and SetDstSeqno().
m_hopCount
uint32_t ns3::dsdv::DsdvHeader::m_hopCount private
Number of Hops.
Definition at line 137 of file dsdv-packet.h.
Referenced by Deserialize(), GetHopCount(), Print(), Serialize(), and SetHopCount().
The documentation for this class was generated from the following files:
src/dsdv/model/dsdv-packet.h
src/dsdv/model/dsdv-packet.cc