ns-3: ns3::EnbMacMemberLteEnbCmacSapProvider Class Reference
ns3::EnbMacMemberLteEnbCmacSapProvider Class Reference
EnbMacMemberLteEnbCmacSapProvider class.
Public Member Functions
EnbMacMemberLteEnbCmacSapProvider (LteEnbMac *mac)
Constructor.
virtual void AddLc (LcInfo lcinfo, LteMacSapUser *msu)
Add a new logical channel.
virtual void AddUe (uint16_t rnti)
Add UE function.
virtual AllocateNcRaPreambleReturnValue AllocateNcRaPreamble (uint16_t rnti)
Allocate a random access preamble for non-contention based random access (e.g., for handover).
virtual void ConfigureMac (uint16_t ulBandwidth, uint16_t dlBandwidth)
virtual RachConfig GetRachConfig ()
virtual void ReconfigureLc (LcInfo lcinfo)
Reconfigure an existing logical channel.
virtual void ReleaseLc (uint16_t rnti, uint8_t lcid)
release an existing logical channel
virtual void RemoveUe (uint16_t rnti)
remove the UE, e.g., after handover or termination of the RRC connection
virtual void UeUpdateConfigurationReq (UeConfig params)
update the configuration of the UE
Public Member Functions inherited from ns3::LteEnbCmacSapProvider
virtual ~LteEnbCmacSapProvider ()
Private Attributes
LteEnbMac * m_mac
the MAC
Detailed Description
EnbMacMemberLteEnbCmacSapProvider class.
Definition at line 59 of file lte-enb-mac.cc.
Constructor & Destructor Documentation
EnbMacMemberLteEnbCmacSapProvider()
ns3::EnbMacMemberLteEnbCmacSapProvider::EnbMacMemberLteEnbCmacSapProvider (LteEnbMac * mac)
Constructor.
Parameters
mac the MAC
Definition at line 86 of file lte-enb-mac.cc.
Member Function Documentation
AddLc()
void ns3::EnbMacMemberLteEnbCmacSapProvider::AddLc (LcInfo lcinfo, LteMacSapUser * msu) virtual
Add a new logical channel.
Parameters
lcinfo
msu
Implements ns3::LteEnbCmacSapProvider.
Definition at line 110 of file lte-enb-mac.cc.
References ns3::LteEnbMac::DoAddLc(), and m_mac.
AddUe()
void ns3::EnbMacMemberLteEnbCmacSapProvider::AddUe (uint16_t rnti) virtual
Add UE function.
Parameters
rnti
Implements ns3::LteEnbCmacSapProvider.
Definition at line 98 of file lte-enb-mac.cc.
References ns3::LteEnbMac::DoAddUe(), and m_mac.
AllocateNcRaPreamble()
LteEnbCmacSapProvider::AllocateNcRaPreambleReturnValue ns3::EnbMacMemberLteEnbCmacSapProvider::AllocateNcRaPreamble (uint16_t rnti) virtual
Allocate a random access preamble for non-contention based random access (e.g., for handover).
Parameters
rnti the RNTI of the UE who will perform non-contention based random access
Returns
the newly allocated random access preamble
Implements ns3::LteEnbCmacSapProvider.
Definition at line 140 of file lte-enb-mac.cc.
References ns3::LteEnbMac::DoAllocateNcRaPreamble(), and m_mac.
ConfigureMac()
void ns3::EnbMacMemberLteEnbCmacSapProvider::ConfigureMac (uint16_t ulBandwidth, uint16_t dlBandwidth) virtual
Parameters
ulBandwidth
dlBandwidth
Implements ns3::LteEnbCmacSapProvider.
Definition at line 92 of file lte-enb-mac.cc.
References ns3::LteEnbMac::DoConfigureMac(), and m_mac.
GetRachConfig()
LteEnbCmacSapProvider::RachConfig ns3::EnbMacMemberLteEnbCmacSapProvider::GetRachConfig () virtual
Returns
the current RACH configuration of the MAC
Implements ns3::LteEnbCmacSapProvider.
Definition at line 134 of file lte-enb-mac.cc.
References ns3::LteEnbMac::DoGetRachConfig(), and m_mac.
ReconfigureLc()
void ns3::EnbMacMemberLteEnbCmacSapProvider::ReconfigureLc (LcInfo lcinfo) virtual
Reconfigure an existing logical channel.
Parameters
lcinfo
Implements ns3::LteEnbCmacSapProvider.
Definition at line 116 of file lte-enb-mac.cc.
References ns3::LteEnbMac::DoReconfigureLc(), and m_mac.
ReleaseLc()
void ns3::EnbMacMemberLteEnbCmacSapProvider::ReleaseLc (uint16_t rnti, uint8_t lcid) virtual
release an existing logical channel
Parameters
rnti
lcid
Implements ns3::LteEnbCmacSapProvider.
Definition at line 122 of file lte-enb-mac.cc.
References ns3::LteEnbMac::DoReleaseLc(), and m_mac.
RemoveUe()
void ns3::EnbMacMemberLteEnbCmacSapProvider::RemoveUe (uint16_t rnti) virtual
remove the UE, e.g., after handover or termination of the RRC connection
Parameters
rnti
Implements ns3::LteEnbCmacSapProvider.
Definition at line 104 of file lte-enb-mac.cc.
References ns3::LteEnbMac::DoRemoveUe(), and m_mac.
UeUpdateConfigurationReq()
void ns3::EnbMacMemberLteEnbCmacSapProvider::UeUpdateConfigurationReq (UeConfig params) virtual
update the configuration of the UE
Parameters
params
Implements ns3::LteEnbCmacSapProvider.
Definition at line 128 of file lte-enb-mac.cc.
References ns3::LteEnbMac::DoUeUpdateConfigurationReq(), m_mac, and aloha::params.
Member Data Documentation
m_mac
LteEnbMac* ns3::EnbMacMemberLteEnbCmacSapProvider::m_mac private
the MAC
Definition at line 82 of file lte-enb-mac.cc.
Referenced by AddLc(), AddUe(), AllocateNcRaPreamble(), ConfigureMac(), GetRachConfig(), ReconfigureLc(), ReleaseLc(), RemoveUe(), and UeUpdateConfigurationReq().
The documentation for this class was generated from the following file:
src/lte/model/lte-enb-mac.cc