ns-3: LteRlcAmE2eTestCase Class Reference
LteRlcAmE2eTestCase Class Reference
LTE Models » lte module tests | Test suites
#include "lte-test-rlc-am-e2e.h"
Public Member Functions
LteRlcAmE2eTestCase ()
LteRlcAmE2eTestCase (std::string name, uint32_t seed, double losses, bool bulkSduArrival)
Constructor.
virtual ~LteRlcAmE2eTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void DlDropEvent (Ptr< const Packet > p)
DL drop event.
virtual void DoRun (void)
Implementation to actually run this TestCase.
void UlDropEvent (Ptr< const Packet > p)
UL drop event.
Private Attributes
bool m_bulkSduArrival
bulk SDU arrival
uint32_t m_dlDrops
number of Dl drops
double m_losses
error rate
uint32_t m_run
rng run
uint32_t m_ulDrops
number of UL drops
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test cases used for the test suite lte-rlc-am-e2e. See the testing section of the LTE module documentation for details.
Definition at line 50 of file lte-test-rlc-am-e2e.h.
Constructor & Destructor Documentation
LteRlcAmE2eTestCase() [1/2]
LteRlcAmE2eTestCase::LteRlcAmE2eTestCase (std::string name, uint32_t seed, double losses, bool bulkSduArrival)
Constructor.
Parameters
name the reference name
seed the random variable seed
losses the error rate
bulkSduArrival true if bulk SDU arrival
Definition at line 101 of file lte-test-rlc-am-e2e.cc.
References NS_LOG_INFO.
LteRlcAmE2eTestCase() [2/2]
LteRlcAmE2eTestCase::LteRlcAmE2eTestCase ()
~LteRlcAmE2eTestCase()
LteRlcAmE2eTestCase::~LteRlcAmE2eTestCase () virtual
Definition at line 112 of file lte-test-rlc-am-e2e.cc.
Member Function Documentation
DlDropEvent()
void LteRlcAmE2eTestCase::DlDropEvent (Ptr< const Packet > p) private
DL drop event.
Parameters
p the packet
Definition at line 118 of file lte-test-rlc-am-e2e.cc.
References m_dlDrops.
Referenced by DoRun().
DoRun()
void LteRlcAmE2eTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 132 of file lte-test-rlc-am-e2e.cc.
References ns3::RateErrorModel::AssignStreams(), ns3::NodeContainer::Create(), DlDropEvent(), ns3::NetDeviceContainer::Get(), ns3::LteTestMac::GetRxPdus(), ns3::LteTestMac::GetTxPdus(), ns3::LteSimpleHelper::InstallEnbDevice(), ns3::LteSimpleHelper::InstallUeDevice(), m_bulkSduArrival, m_dlDrops, ns3::LteSimpleHelper::m_enbMac, ns3::LteSimpleHelper::m_enbRrc, m_losses, m_run, ns3::LteSimpleHelper::m_ueMac, ns3::LteSimpleHelper::m_ueRrc, ns3::MakeCallback(), max, ns3::MilliSeconds(), min, NS_LOG_INFO, NS_TEST_ASSERT_MSG_EQ, ns3::Seconds(), ns3::ObjectBase::SetAttribute(), ns3::Config::SetDefault(), ns3::Config::SetGlobal(), ns3::LteTestMac::SetTxOpportunityMode(), ns3::LteTestMac::SetTxOppSize(), ns3::LteTestMac::SetTxOppTime(), and stopTime.
UlDropEvent()
void LteRlcAmE2eTestCase::UlDropEvent (Ptr< const Packet > p) private
UL drop event.
Parameters
p the packet
Definition at line 125 of file lte-test-rlc-am-e2e.cc.
References m_ulDrops.
Member Data Documentation
m_bulkSduArrival
bool LteRlcAmE2eTestCase::m_bulkSduArrival private
bulk SDU arrival
Definition at line 81 of file lte-test-rlc-am-e2e.h.
Referenced by DoRun().
m_dlDrops
uint32_t LteRlcAmE2eTestCase::m_dlDrops private
number of Dl drops
Definition at line 83 of file lte-test-rlc-am-e2e.h.
Referenced by DlDropEvent(), and DoRun().
m_losses
double LteRlcAmE2eTestCase::m_losses private
error rate
Definition at line 80 of file lte-test-rlc-am-e2e.h.
Referenced by DoRun().
m_run
uint32_t LteRlcAmE2eTestCase::m_run private
rng run
Definition at line 79 of file lte-test-rlc-am-e2e.h.
Referenced by DoRun().
m_ulDrops
uint32_t LteRlcAmE2eTestCase::m_ulDrops private
number of UL drops
Definition at line 84 of file lte-test-rlc-am-e2e.h.
Referenced by UlDropEvent().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-rlc-am-e2e.h
src/lte/test/lte-test-rlc-am-e2e.cc