ns-3: ns3::lorawan::AdrComponent Class Reference
ns3::lorawan::AdrComponent Class Reference
#include "adr-component.h"
Public Member Functions
AdrComponent ()
virtual ~AdrComponent ()
void BeforeSendingReply (Ptr< EndDeviceStatus > status, Ptr< NetworkStatus > networkStatus)
void OnFailedReply (Ptr< EndDeviceStatus > status, Ptr< NetworkStatus > networkStatus)
Method that is called when a packet cannot be sent in the downlink.
void OnReceivedPacket (Ptr< const Packet > packet, Ptr< EndDeviceStatus > status, Ptr< NetworkStatus > networkStatus)
Method that is called when a new packet is received by the NetworkServer.
Public Member Functions inherited from ns3::lorawan::NetworkControllerComponent
NetworkControllerComponent ()
virtual ~NetworkControllerComponent ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::lorawan::NetworkControllerComponent
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
enum CombiningMethod { AVERAGE, MAXIMUM, MINIMUM }
Private Member Functions
void AdrImplementation (uint8_t *newDataRate, uint8_t *newTxPower, Ptr< EndDeviceStatus > status)
double GetAverageSNR (EndDeviceStatus::ReceivedPacketList packetList, int historyRange)
double GetAverageTxFromGateways (EndDeviceStatus::GatewayList gwList)
double GetMaxSNR (EndDeviceStatus::ReceivedPacketList packetList, int historyRange)
double GetMaxTxFromGateways (EndDeviceStatus::GatewayList gwList)
double GetMinSNR (EndDeviceStatus::ReceivedPacketList packetList, int historyRange)
double GetMinTxFromGateways (EndDeviceStatus::GatewayList gwList)
double GetReceivedPower (EndDeviceStatus::GatewayList gwList)
int GetTxPowerIndex (int txPower)
double RxPowerToSNR (double transmissionPower)
uint8_t SfToDr (uint8_t sf)
Private Attributes
const int B = 125000
enum CombiningMethod historyAveraging
int historyRange
bool m_toggleTxPower
const int max_transmissionPower = 14
const int min_spreadingFactor = 7
const int min_transmissionPower = 2
const int NF = 6
enum CombiningMethod tpAveraging
double treshold [6] = {-20.0, -17.5, -15.0, -12.5, -10.0, -7.5}
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 37 of file adr-component.h.
Member Enumeration Documentation
CombiningMethod
enum ns3::lorawan::AdrComponent::CombiningMethod private
Enumerator
AVERAGE
MAXIMUM
MINIMUM
Definition at line 39 of file adr-component.h.
Constructor & Destructor Documentation
AdrComponent()
ns3::lorawan::AdrComponent::AdrComponent ()
Definition at line 74 of file adr-component.cc.
~AdrComponent()
ns3::lorawan::AdrComponent::~AdrComponent () virtual
Definition at line 78 of file adr-component.cc.
Member Function Documentation
AdrImplementation()
void ns3::lorawan::AdrComponent::AdrImplementation (uint8_t * newDataRate, uint8_t * newTxPower, Ptr< EndDeviceStatus > status) private
Definition at line 177 of file adr-component.cc.
References AVERAGE, GetAverageSNR(), GetMaxSNR(), GetMinSNR(), historyAveraging, historyRange, max_transmissionPower, MAXIMUM, min_spreadingFactor, min_transmissionPower, MINIMUM, NS_LOG_DEBUG, SfToDr(), and treshold.
Referenced by BeforeSendingReply().
BeforeSendingReply()
void ns3::lorawan::AdrComponent::BeforeSendingReply (Ptr< EndDeviceStatus > status, Ptr< NetworkStatus > networkStatus) virtual
Implements ns3::lorawan::NetworkControllerComponent.
Definition at line 93 of file adr-component.cc.
References AdrImplementation(), ns3::lorawan::LoraFrameHeader::GetAdr(), GetTxPowerIndex(), historyRange, m_toggleTxPower, NS_LOG_DEBUG, NS_LOG_ERROR, NS_LOG_FUNCTION, ns3::Packet::RemoveHeader(), ns3::lorawan::LoraFrameHeader::SetAsUplink(), SfToDr(), and ns3::lorawan::LorawanMacHeader::UNCONFIRMED_DATA_DOWN.
GetAverageSNR()
double ns3::lorawan::AdrComponent::GetAverageSNR (EndDeviceStatus::ReceivedPacketList packetList, int historyRange) private
Definition at line 413 of file adr-component.cc.
References GetReceivedPower(), historyRange, NS_LOG_DEBUG, and RxPowerToSNR().
Referenced by AdrImplementation().
GetAverageTxFromGateways()
double ns3::lorawan::AdrComponent::GetAverageTxFromGateways (EndDeviceStatus::GatewayList gwList) private
Definition at line 325 of file adr-component.cc.
References NS_LOG_DEBUG.
Referenced by GetReceivedPower().
GetMaxSNR()
double ns3::lorawan::AdrComponent::GetMaxSNR (EndDeviceStatus::ReceivedPacketList packetList, int historyRange) private
Definition at line 386 of file adr-component.cc.
References GetReceivedPower(), historyRange, ns3::max(), NS_LOG_DEBUG, and RxPowerToSNR().
Referenced by AdrImplementation().
GetMaxTxFromGateways()
double ns3::lorawan::AdrComponent::GetMaxTxFromGateways (EndDeviceStatus::GatewayList gwList) private
Definition at line 308 of file adr-component.cc.
References ns3::max().
Referenced by GetReceivedPower().
GetMinSNR()
double ns3::lorawan::AdrComponent::GetMinSNR (EndDeviceStatus::ReceivedPacketList packetList, int historyRange) private
Definition at line 359 of file adr-component.cc.
References GetReceivedPower(), historyRange, ns3::min(), NS_LOG_DEBUG, and RxPowerToSNR().
Referenced by AdrImplementation().
GetMinTxFromGateways()
double ns3::lorawan::AdrComponent::GetMinTxFromGateways (EndDeviceStatus::GatewayList gwList) private
Definition at line 291 of file adr-component.cc.
References ns3::min().
Referenced by GetReceivedPower().
GetReceivedPower()
double ns3::lorawan::AdrComponent::GetReceivedPower (EndDeviceStatus::GatewayList gwList) private
Definition at line 343 of file adr-component.cc.
References AVERAGE, GetAverageTxFromGateways(), GetMaxTxFromGateways(), GetMinTxFromGateways(), MAXIMUM, MINIMUM, and tpAveraging.
Referenced by GetAverageSNR(), GetMaxSNR(), and GetMinSNR().
GetTxPowerIndex()
int ns3::lorawan::AdrComponent::GetTxPowerIndex (int txPower) private
Definition at line 438 of file adr-component.cc.
Referenced by BeforeSendingReply().
GetTypeId()
TypeId ns3::lorawan::AdrComponent::GetTypeId (void) static
Definition at line 34 of file adr-component.cc.
References ns3::TypeId::AddConstructor(), AVERAGE, historyAveraging, historyRange, m_toggleTxPower, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeEnumAccessor(), ns3::MakeEnumChecker(), ns3::MakeIntegerAccessor(), MAXIMUM, MINIMUM, ns3::TypeId::SetGroupName(), and tpAveraging.
Referenced by OnFailedReply(), and OnReceivedPacket().
OnFailedReply()
void ns3::lorawan::AdrComponent::OnFailedReply (Ptr< EndDeviceStatus > status, Ptr< NetworkStatus > networkStatus) virtual
Method that is called when a packet cannot be sent in the downlink.
Parameters
status The EndDeviceStatus of the device to which it was impossible to send a reply.
networkStatus A pointer to the NetworkStatus object
Implements ns3::lorawan::NetworkControllerComponent.
Definition at line 171 of file adr-component.cc.
References GetTypeId(), and NS_LOG_FUNCTION.
OnReceivedPacket()
void ns3::lorawan::AdrComponent::OnReceivedPacket (Ptr< const Packet > packet, Ptr< EndDeviceStatus > status, Ptr< NetworkStatus > networkStatus) virtual
Method that is called when a new packet is received by the NetworkServer.
Parameters
packet The newly received packet
networkStatus A pointer to the NetworkStatus object
Implements ns3::lorawan::NetworkControllerComponent.
Definition at line 82 of file adr-component.cc.
References GetTypeId(), and NS_LOG_FUNCTION.
RxPowerToSNR()
double ns3::lorawan::AdrComponent::RxPowerToSNR (double transmissionPower) private
Definition at line 284 of file adr-component.cc.
References B, and NF.
Referenced by GetAverageSNR(), GetMaxSNR(), and GetMinSNR().
SfToDr()
uint8_t ns3::lorawan::AdrComponent::SfToDr (uint8_t sf) private
Definition at line 259 of file adr-component.cc.
Referenced by AdrImplementation(), and BeforeSendingReply().
Member Data Documentation
B
const int ns3::lorawan::AdrComponent::B = 125000 private
Definition at line 113 of file adr-component.h.
Referenced by RxPowerToSNR().
historyAveraging
enum CombiningMethod ns3::lorawan::AdrComponent::historyAveraging private
Definition at line 95 of file adr-component.h.
Referenced by AdrImplementation(), and GetTypeId().
historyRange
int ns3::lorawan::AdrComponent::historyRange private
Definition at line 95 of file adr-component.h.
Referenced by AdrImplementation(), BeforeSendingReply(), GetAverageSNR(), GetMaxSNR(), GetMinSNR(), and GetTypeId().
m_toggleTxPower
bool ns3::lorawan::AdrComponent::m_toggleTxPower private
Definition at line 122 of file adr-component.h.
Referenced by BeforeSendingReply(), and GetTypeId().
max_transmissionPower
const int ns3::lorawan::AdrComponent::max_transmissionPower = 14 private
Definition at line 107 of file adr-component.h.
Referenced by AdrImplementation().
min_spreadingFactor
const int ns3::lorawan::AdrComponent::min_spreadingFactor = 7 private
Definition at line 101 of file adr-component.h.
Referenced by AdrImplementation().
min_transmissionPower
const int ns3::lorawan::AdrComponent::min_transmissionPower = 2 private
Definition at line 104 of file adr-component.h.
Referenced by AdrImplementation().
NF
const int ns3::lorawan::AdrComponent::NF = 6 private
Definition at line 116 of file adr-component.h.
Referenced by RxPowerToSNR().
tpAveraging
enum CombiningMethod ns3::lorawan::AdrComponent::tpAveraging private
Definition at line 89 of file adr-component.h.
Referenced by GetReceivedPower(), and GetTypeId().
treshold
double ns3::lorawan::AdrComponent::treshold[6] = {-20.0, -17.5, -15.0, -12.5, -10.0, -7.5} private
Definition at line 120 of file adr-component.h.
Referenced by AdrImplementation().
The documentation for this class was generated from the following files:
src/lorawan/model/adr-component.h
src/lorawan/model/adr-component.cc