ns-3: OlsrHelloTestCase Class Reference
OlsrHelloTestCase Class Reference
OLSR Routing » olsr module tests | Test suites
Public Member Functions
OlsrHelloTestCase ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Check Hello olsr messages
Definition at line 177 of file olsr-header-test-suite.cc.
Constructor & Destructor Documentation
OlsrHelloTestCase()
OlsrHelloTestCase::OlsrHelloTestCase ()
Definition at line 184 of file olsr-header-test-suite.cc.
Member Function Documentation
DoRun()
void OlsrHelloTestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 189 of file olsr-header-test-suite.cc.
References ns3::Packet::AddHeader(), ns3::olsr::MessageHeader::Hello::GetHTime(), ns3::Packet::GetSize(), ns3::olsr::MessageHeader::Hello::LinkMessage::linkCode, ns3::olsr::MessageHeader::Hello::linkMessages, ns3::olsr::MessageHeader::Hello::LinkMessage::neighborInterfaceAddresses, NS_TEST_ASSERT_MSG_EQ, ns3::Packet::RemoveHeader(), ns3::Seconds(), ns3::olsr::MessageHeader::Hello::SetHTime(), and ns3::olsr::MessageHeader::Hello::willingness.
The documentation for this class was generated from the following file:
src/olsr/test/olsr-header-test-suite.cc