ns-3: ns3::lorawan::ClassAEndDeviceLorawanMac Class Reference
ns3::lorawan::ClassAEndDeviceLorawanMac Class Reference
Class representing the MAC layer of a Class A LoRaWAN device.
#include "class-a-end-device-lorawan-mac.h"
Public Member Functions
ClassAEndDeviceLorawanMac ()
virtual ~ClassAEndDeviceLorawanMac ()
void CloseFirstReceiveWindow (void)
Perform operations needed to close the first receive window.
void CloseSecondReceiveWindow (void)
Perform operations needed to close the second receive window.
virtual void FailedReception (Ptr< Packet const > packet)
Function called by lower layers to inform this layer that reception of a packet we were locked on failed.
uint8_t GetFirstReceiveWindowDataRate (void)
Get the Data Rate that will be used in the first receive window.
virtual Time GetNextClassTransmissionDelay (Time waitingTime)
Find the minimum waiting time before the next possible transmission based on End Device's Class Type.
uint8_t GetSecondReceiveWindowDataRate (void)
Get the Data Rate that will be used in the second receive window.
double GetSecondReceiveWindowFrequency (void)
Get the frequency that is used for the second receive window.
virtual void OnRxClassParamSetupReq (Ptr< RxParamSetupReq > rxParamSetupReq)
Perform the actions that need to be taken when receiving a RxParamSetupReq command based on the Device's Class Type.
void OpenFirstReceiveWindow (void)
Perform operations needed to open the first receive window.
void OpenSecondReceiveWindow (void)
Perform operations needed to open the second receive window.
virtual void Receive (Ptr< Packet const > packet)
Receive a packet.
virtual void SendToPhy (Ptr< Packet > packet)
Add headers and send a packet with the sending function of the physical layer.
void SetSecondReceiveWindowDataRate (uint8_t dataRate)
Set the Data Rate to be used in the second receive window.
void SetSecondReceiveWindowFrequency (double frequencyMHz)
Set the frequency that will be used for the second receive window.
virtual void TxFinished (Ptr< const Packet > packet)
Perform the actions that are required after a packet send.
Public Member Functions inherited from ns3::lorawan::EndDeviceLorawanMac
EndDeviceLorawanMac ()
virtual ~EndDeviceLorawanMac ()
void AddLogicalChannel (double frequency)
Add a logical channel to the helper.
void AddLogicalChannel (Ptr< LogicalLoraChannel > logicalChannel)
Add a logical channel to the helper.
void AddMacCommand (Ptr< MacCommand > macCommand)
Add a MAC command to the list of those that will be sent out in the next packet.
void AddSubBand (double startFrequency, double endFrequency, double dutyCycle, double maxTxPowerDbm)
Add a subband to the logical channel helper.
void ApplyNecessaryOptions (LoraFrameHeader &frameHeader)
Add the necessary options and MAC commands to the LoraFrameHeader.
void ApplyNecessaryOptions (LorawanMacHeader &macHeader)
Add the necessary options and MAC commands to the LorawanMacHeader.
virtual void DoSend (Ptr< Packet > packet)
Checking if we are performing the transmission of a new packet or a retransmission, and call SendToPhy function.
double GetAggregatedDutyCycle (void)
Set a value for the RX1DROffset parameter.
uint8_t GetDataRate (void)
Get the data rate this end device is set to use.
bool GetDataRateAdaptation (void)
Get if data rate adaptation is enabled or not.
LoraDeviceAddress GetDeviceAddress (void)
Get the network address of this device.
uint8_t GetMaxNumberOfTransmissions (void)
Set the maximum number of transmissions allowed.
LorawanMacHeader::MType GetMType (void)
Get the message type to send when the Send method is called.
virtual uint8_t GetTransmissionPower (void)
Get the transmission power this end device is set to use.
void OnDevStatusReq (void)
Perform the actions that need to be taken when receiving a DevStatusReq command.
void OnDutyCycleReq (double dutyCycle)
Perform the actions that need to be taken when receiving a DutyCycleReq command.
void OnLinkAdrReq (uint8_t dataRate, uint8_t txPower, std::list< int > enabledChannels, int repetitions)
Perform the actions that need to be taken when receiving a LinkAdrReq command.
void OnLinkCheckAns (uint8_t margin, uint8_t gwCnt)
Perform the actions that need to be taken when receiving a LinkCheckAns command.
void OnNewChannelReq (uint8_t chIndex, double frequency, uint8_t minDataRate, uint8_t maxDataRate)
Perform the actions that need to be taken when receiving a NewChannelReq command.
void OnRxParamSetupReq (Ptr< RxParamSetupReq > rxParamSetupReq)
Perform the actions that need to be taken when receiving a RxParamSetupReq command.
void ParseCommands (LoraFrameHeader frameHeader)
Parse and take action on the commands contained on this FrameHeader.
virtual void postponeTransmission (Time nextTxDelay, Ptr< Packet >)
Postpone transmission to the specified time and delete previously scheduled transmissions if present.
virtual void resetRetransmissionParameters ()
Reset retransmission parameters contained in the structure LoraRetxParams.
virtual void Send (Ptr< Packet > packet)
Send a packet.
void SetDataRate (uint8_t dataRate)
Set the data rate this end device will use when transmitting.
void SetDataRateAdaptation (bool adapt)
Enable data rate adaptation in the retransmitting procedure.
void SetDeviceAddress (LoraDeviceAddress address)
Set the network address of this device.
void SetLogicalChannel (uint8_t chIndex, double frequency, uint8_t minDataRate, uint8_t maxDataRate)
Set a new logical channel in the helper.
void SetMaxNumberOfTransmissions (uint8_t maxNumbTx)
Set the maximum number of transmissions allowed.
void SetMType (LorawanMacHeader::MType mType)
Set the message type to send when the Send method is called.
Public Member Functions inherited from ns3::lorawan::LorawanMac
LorawanMac ()
virtual ~LorawanMac ()
double GetBandwidthFromDataRate (uint8_t dataRate)
Get the BW corresponding to a data rate, based on this MAC's region.
double GetDbmForTxPower (uint8_t txPower)
Get the transmission power in dBm that corresponds, in this region, to the encoded 8-bit txPower.
Ptr< NetDevice > GetDevice (void)
Get the device this MAC layer is installed on.
LogicalLoraChannelHelper GetLogicalLoraChannelHelper (void)
Get the logical lora channel helper associated with this MAC.
int GetNPreambleSymbols (void)
Get the number of PHY preamble symbols this MAC is set to use.
Ptr< LoraPhy > GetPhy (void)
Get the underlying PHY layer.
uint8_t GetSfFromDataRate (uint8_t dataRate)
Get the SF corresponding to a data rate, based on this MAC's region.
void SetBandwidthForDataRate (std::vector< double > bandwidthForDataRate)
Set the vector to use to check up correspondence between bandwidth and DataRate.
void SetDevice (Ptr< NetDevice > device)
Set the device this MAC layer is installed on.
void SetLogicalLoraChannelHelper (LogicalLoraChannelHelper helper)
Set the LogicalLoraChannelHelper this MAC instance will use.
void SetMaxAppPayloadForDataRate (std::vector< uint32_t > maxAppPayloadForDataRate)
Set the maximum App layer payload for a set DataRate.
void SetNPreambleSymbols (int nPreambleSymbols)
Set the number of PHY preamble symbols this MAC is set to use.
void SetPhy (Ptr< LoraPhy > phy)
Set the underlying PHY layer.
void SetReplyDataRateMatrix (ReplyDataRateMatrix replyDataRateMatrix)
Set the matrix to use when deciding with which DataRate to respond.
void SetSfForDataRate (std::vector< uint8_t > sfForDataRate)
Set the vector to use to check up correspondence between SF and DataRate.
void SetTxDbmForTxPower (std::vector< double > txDbmForTxPower)
Set the vector to use to check up which transmission power in Dbm corresponds to a certain TxPower value in this MAC's region.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::lorawan::EndDeviceLorawanMac
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::lorawan::LorawanMac
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
EventId m_closeFirstWindow
The event of the closing the first receive window.
EventId m_closeSecondWindow
The event of the closing the second receive window.
Time m_receiveDelay1
The interval between when a packet is done sending and when the first receive window is opened.
Time m_receiveDelay2
The interval between when a packet is done sending and when the second receive window is opened.
uint8_t m_rx1DrOffset
The RX1DROffset parameter value.
EventId m_secondReceiveWindow
The event of the second receive window opening.
uint8_t m_secondReceiveWindowDataRate
The Data Rate to listen for during the second downlink transmission.
double m_secondReceiveWindowFrequency
The frequency to listen on for the second receive window.
Additional Inherited Members
Public Types inherited from ns3::lorawan::LorawanMac
typedef std::array< std::array< uint8_t, 6 >, 8 > ReplyDataRateMatrix
Protected Member Functions inherited from ns3::lorawan::EndDeviceLorawanMac
Ptr< LogicalLoraChannel > GetChannelForTx (void)
Find a suitable channel for transmission.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::lorawan::EndDeviceLorawanMac
LoraDeviceAddress m_address
The address of this device.
uint8_t m_codingRate
The coding rate used by this device.
uint8_t m_dataRate
The DataRate this device is using to transmit.
bool m_enableDRAdapt
Enable Data Rate adaptation during the retransmission procedure.
bool m_headerDisabled
Whether or not the header is disabled for communications by this device.
std::list< Ptr< MacCommand > > m_macCommandList
List of the MAC commands that need to be applied to the next UL packet.
uint8_t m_maxNumbTx
Maximum number of transmission allowed.
uint8_t m_receiveWindowDurationInSymbols
The duration of a receive window in number of symbols.
TracedCallback< uint8_t, bool, Time, Ptr< Packet > > m_requiredTxCallback
The trace source fired when the transmission procedure is finished.
struct LoraRetxParameters m_retxParams
TracedValue< double > m_txPower
The transmission power this device is using to transmit.
Ptr< UniformRandomVariable > m_uniformRV
An uniform random variable, used by the Shuffle method to randomly reorder the channel list.
Protected Attributes inherited from ns3::lorawan::LorawanMac
std::vector< double > m_bandwidthForDataRate
A vector holding the bandwidth each Data Rate corresponds to.
TracedCallback< Ptr< const Packet > > m_cannotSendBecauseDutyCycle
The trace source that is fired when a packet cannot be sent because of duty cycle limitations.
LogicalLoraChannelHelper m_channelHelper
The LogicalLoraChannelHelper instance that is assigned to this MAC.
Ptr< NetDevice > m_device
The device this MAC layer is installed on.
std::vector< uint32_t > m_maxAppPayloadForDataRate
A vector holding the maximum app payload size that corresponds to a certain DataRate.
int m_nPreambleSymbols
The number of symbols to use in the PHY preamble.
Ptr< LoraPhy > m_phy
The PHY instance that sits under this MAC layer.
TracedCallback< Ptr< const Packet > > m_receivedPacket
Trace source that is fired when a packet reaches the MAC layer.
ReplyDataRateMatrix m_replyDataRateMatrix
The matrix that decides the DR the GW will use in a reply based on the ED's sending DR and on the value of the RX1DROffset parameter.
TracedCallback< Ptr< Packet const > > m_sentNewPacket
Trace source that is fired when a new APP layer packet arrives at the MAC layer.
std::vector< uint8_t > m_sfForDataRate
A vector holding the SF each Data Rate corresponds to.
std::vector< double > m_txDbmForTxPower
A vector holding the power that corresponds to a certain TxPower value.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Class representing the MAC layer of a Class A LoRaWAN device.
Definition at line 40 of file class-a-end-device-lorawan-mac.h.
Constructor & Destructor Documentation
ClassAEndDeviceLorawanMac()
ns3::lorawan::ClassAEndDeviceLorawanMac::ClassAEndDeviceLorawanMac ()
Definition at line 48 of file class-a-end-device-lorawan-mac.cc.
References ns3::EventId::Cancel(), m_closeFirstWindow, m_closeSecondWindow, m_secondReceiveWindow, and NS_LOG_FUNCTION.
~ClassAEndDeviceLorawanMac()
ns3::lorawan::ClassAEndDeviceLorawanMac::~ClassAEndDeviceLorawanMac () virtual
Definition at line 66 of file class-a-end-device-lorawan-mac.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
CloseFirstReceiveWindow()
void ns3::lorawan::ClassAEndDeviceLorawanMac::CloseFirstReceiveWindow (void)
Perform operations needed to close the first receive window.
Definition at line 312 of file class-a-end-device-lorawan-mac.cc.
References ns3::lorawan::LorawanMac::m_phy, NS_ABORT_MSG, NS_LOG_FUNCTION_NOARGS, third::phy, ns3::lorawan::EndDeviceLoraPhy::RX, ns3::lorawan::EndDeviceLoraPhy::SLEEP, ns3::lorawan::EndDeviceLoraPhy::STANDBY, and ns3::lorawan::EndDeviceLoraPhy::TX.
Referenced by OpenFirstReceiveWindow().
CloseSecondReceiveWindow()
void ns3::lorawan::ClassAEndDeviceLorawanMac::CloseSecondReceiveWindow (void)
Perform operations needed to close the second receive window.
Definition at line 380 of file class-a-end-device-lorawan-mac.cc.
References ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::firstAttempt, ns3::lorawan::EndDeviceLoraPhy::GetState(), ns3::lorawan::EndDeviceLorawanMac::m_maxNumbTx, ns3::lorawan::LorawanMac::m_phy, ns3::lorawan::EndDeviceLorawanMac::m_requiredTxCallback, ns3::lorawan::EndDeviceLorawanMac::m_retxParams, NS_ABORT_MSG, NS_LOG_DEBUG, NS_LOG_FUNCTION_NOARGS, NS_LOG_INFO, ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::packet, third::phy, ns3::lorawan::EndDeviceLorawanMac::resetRetransmissionParameters(), ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::retxLeft, ns3::lorawan::EndDeviceLoraPhy::RX, ns3::lorawan::EndDeviceLorawanMac::Send(), ns3::lorawan::EndDeviceLoraPhy::SLEEP, ns3::lorawan::EndDeviceLoraPhy::STANDBY, ns3::lorawan::EndDeviceLoraPhy::TX, and ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::waitingAck.
Referenced by OpenSecondReceiveWindow().
FailedReception()
void ns3::lorawan::ClassAEndDeviceLorawanMac::FailedReception (Ptr< Packet const > packet) virtual
Function called by lower layers to inform this layer that reception of a packet we were locked on failed.
Parameters
packet the packet we failed to receive
Reimplemented from ns3::lorawan::EndDeviceLorawanMac.
Definition at line 240 of file class-a-end-device-lorawan-mac.cc.
References ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::firstAttempt, ns3::EventId::IsExpired(), ns3::lorawan::EndDeviceLorawanMac::m_maxNumbTx, ns3::lorawan::LorawanMac::m_phy, ns3::lorawan::EndDeviceLorawanMac::m_requiredTxCallback, ns3::lorawan::EndDeviceLorawanMac::m_retxParams, m_secondReceiveWindow, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::packet, ns3::lorawan::EndDeviceLorawanMac::resetRetransmissionParameters(), ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::retxLeft, ns3::lorawan::EndDeviceLorawanMac::Send(), and ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::waitingAck.
GetFirstReceiveWindowDataRate()
uint8_t ns3::lorawan::ClassAEndDeviceLorawanMac::GetFirstReceiveWindowDataRate (void)
Get the Data Rate that will be used in the first receive window.
Returns
The Data Rate
Definition at line 489 of file class-a-end-device-lorawan-mac.cc.
References ns3::lorawan::EndDeviceLorawanMac::m_dataRate, ns3::lorawan::LorawanMac::m_replyDataRateMatrix, and m_rx1DrOffset.
Referenced by OpenFirstReceiveWindow(), and SendToPhy().
GetNextClassTransmissionDelay()
Time ns3::lorawan::ClassAEndDeviceLorawanMac::GetNextClassTransmissionDelay (Time waitingTime) virtual
Find the minimum waiting time before the next possible transmission based on End Device's Class Type.
Parameters
waitingTime The minimum waiting time that has to be respected, irrespective of the class (e.g., because of duty cycle limitations).
Reimplemented from ns3::lorawan::EndDeviceLorawanMac.
Definition at line 449 of file class-a-end-device-lorawan-mac.cc.
References ns3::lorawan::LorawanMac::GetBandwidthFromDataRate(), GetSecondReceiveWindowDataRate(), ns3::Time::GetSeconds(), ns3::lorawan::LorawanMac::GetSfFromDataRate(), ns3::EventId::GetTs(), ns3::UniformRandomVariable::GetValue(), ns3::EventId::IsExpired(), m_closeFirstWindow, m_closeSecondWindow, ns3::lorawan::EndDeviceLorawanMac::m_receiveWindowDurationInSymbols, ns3::lorawan::EndDeviceLorawanMac::m_retxParams, m_secondReceiveWindow, ns3::lorawan::EndDeviceLorawanMac::m_uniformRV, max, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION_NOARGS, NS_LOG_WARN, ns3::Seconds(), and ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::waitingAck.
GetSecondReceiveWindowDataRate()
uint8_t ns3::lorawan::ClassAEndDeviceLorawanMac::GetSecondReceiveWindowDataRate (void)
Get the Data Rate that will be used in the second receive window.
Returns
The Data Rate
Definition at line 501 of file class-a-end-device-lorawan-mac.cc.
References m_secondReceiveWindowDataRate.
Referenced by GetNextClassTransmissionDelay(), and OpenSecondReceiveWindow().
GetSecondReceiveWindowFrequency()
double ns3::lorawan::ClassAEndDeviceLorawanMac::GetSecondReceiveWindowFrequency (void)
Get the frequency that is used for the second receive window.
Returns
The frequency, in MHz
Definition at line 513 of file class-a-end-device-lorawan-mac.cc.
References m_secondReceiveWindowFrequency.
GetTypeId()
TypeId ns3::lorawan::ClassAEndDeviceLorawanMac::GetTypeId (void) static
Definition at line 39 of file class-a-end-device-lorawan-mac.cc.
References ns3::TypeId::SetParent().
OnRxClassParamSetupReq()
void ns3::lorawan::ClassAEndDeviceLorawanMac::OnRxClassParamSetupReq (Ptr< RxParamSetupReq > rxParamSetupReq) virtual
Perform the actions that need to be taken when receiving a RxParamSetupReq command based on the Device's Class Type.
Parameters
rxParamSetupReq The Parameter Setup Request, which contains:
The offset to set.
The data rate to use for the second receive window.
The frequency to use for the second receive window.
Reimplemented from ns3::lorawan::EndDeviceLorawanMac.
Definition at line 523 of file class-a-end-device-lorawan-mac.cc.
References ns3::lorawan::LorawanMac::GetBandwidthFromDataRate(), ns3::lorawan::LorawanMac::GetSfFromDataRate(), ns3::lorawan::EndDeviceLorawanMac::m_macCommandList, m_rx1DrOffset, m_secondReceiveWindowDataRate, m_secondReceiveWindowFrequency, NS_LOG_FUNCTION, and NS_LOG_INFO.
OpenFirstReceiveWindow()
void ns3::lorawan::ClassAEndDeviceLorawanMac::OpenFirstReceiveWindow (void)
Perform operations needed to open the first receive window.
Definition at line 293 of file class-a-end-device-lorawan-mac.cc.
References CloseFirstReceiveWindow(), ns3::lorawan::LorawanMac::GetBandwidthFromDataRate(), GetFirstReceiveWindowDataRate(), ns3::lorawan::LorawanMac::GetSfFromDataRate(), m_closeFirstWindow, ns3::lorawan::LorawanMac::m_phy, ns3::lorawan::EndDeviceLorawanMac::m_receiveWindowDurationInSymbols, NS_LOG_FUNCTION_NOARGS, ns3::Simulator::Schedule(), and ns3::Seconds().
Referenced by TxFinished().
OpenSecondReceiveWindow()
void ns3::lorawan::ClassAEndDeviceLorawanMac::OpenSecondReceiveWindow (void)
Perform operations needed to open the second receive window.
Definition at line 343 of file class-a-end-device-lorawan-mac.cc.
References CloseSecondReceiveWindow(), ns3::lorawan::LorawanMac::GetBandwidthFromDataRate(), GetSecondReceiveWindowDataRate(), ns3::lorawan::LorawanMac::GetSfFromDataRate(), ns3::lorawan::EndDeviceLoraPhy::GetState(), m_closeSecondWindow, ns3::lorawan::LorawanMac::m_phy, ns3::lorawan::EndDeviceLorawanMac::m_receiveWindowDurationInSymbols, m_secondReceiveWindowDataRate, m_secondReceiveWindowFrequency, NS_LOG_FUNCTION_NOARGS, NS_LOG_INFO, ns3::lorawan::EndDeviceLoraPhy::RX, ns3::Simulator::Schedule(), and ns3::Seconds().
Referenced by TxFinished().
Receive()
void ns3::lorawan::ClassAEndDeviceLorawanMac::Receive (Ptr< Packet const > packet) virtual
Receive a packet.
This method is typically registered as a callback in the underlying PHY layer so that it's called when a packet is going up the stack.
Parameters
packet the received packet.
Reimplemented from ns3::lorawan::EndDeviceLorawanMac.
Definition at line 143 of file class-a-end-device-lorawan-mac.cc.
References ns3::Simulator::Cancel(), ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::firstAttempt, ns3::lorawan::LoraFrameHeader::GetAddress(), ns3::EventId::IsExpired(), ns3::lorawan::LorawanMacHeader::IsUplink(), ns3::lorawan::EndDeviceLorawanMac::m_address, ns3::lorawan::EndDeviceLorawanMac::m_maxNumbTx, ns3::lorawan::LorawanMac::m_phy, ns3::lorawan::LorawanMac::m_receivedPacket, ns3::lorawan::EndDeviceLorawanMac::m_requiredTxCallback, ns3::lorawan::EndDeviceLorawanMac::m_retxParams, m_secondReceiveWindow, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::packet, ns3::lorawan::EndDeviceLorawanMac::ParseCommands(), ns3::Packet::RemoveHeader(), ns3::lorawan::EndDeviceLorawanMac::resetRetransmissionParameters(), ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::retxLeft, ns3::lorawan::EndDeviceLorawanMac::Send(), ns3::lorawan::LoraFrameHeader::SetAsDownlink(), and ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::waitingAck.
SendToPhy()
void ns3::lorawan::ClassAEndDeviceLorawanMac::SendToPhy (Ptr< Packet > packet) virtual
Add headers and send a packet with the sending function of the physical layer.
Parameters
packet the packet to send
Reimplemented from ns3::lorawan::EndDeviceLorawanMac.
Definition at line 76 of file class-a-end-device-lorawan-mac.cc.
References ns3::lorawan::LogicalLoraChannelHelper::AddEvent(), aloha::duration, ns3::lorawan::LorawanMac::GetBandwidthFromDataRate(), ns3::lorawan::EndDeviceLorawanMac::GetChannelForTx(), GetFirstReceiveWindowDataRate(), ns3::lorawan::LorawanMac::GetSfFromDataRate(), ns3::lorawan::LorawanMac::m_channelHelper, ns3::lorawan::EndDeviceLorawanMac::m_codingRate, ns3::lorawan::EndDeviceLorawanMac::m_dataRate, ns3::lorawan::EndDeviceLorawanMac::m_enableDRAdapt, ns3::lorawan::EndDeviceLorawanMac::m_headerDisabled, ns3::lorawan::EndDeviceLorawanMac::m_maxNumbTx, ns3::lorawan::LorawanMac::m_nPreambleSymbols, ns3::lorawan::LorawanMac::m_phy, ns3::lorawan::EndDeviceLorawanMac::m_retxParams, m_rx1DrOffset, ns3::lorawan::EndDeviceLorawanMac::m_txPower, NS_LOG_DEBUG, aloha::params, and ns3::lorawan::EndDeviceLorawanMac::LoraRetxParameters::retxLeft.
SetSecondReceiveWindowDataRate()
void ns3::lorawan::ClassAEndDeviceLorawanMac::SetSecondReceiveWindowDataRate (uint8_t dataRate)
Set the Data Rate to be used in the second receive window.
Parameters
dataRate The Data Rate.
Definition at line 495 of file class-a-end-device-lorawan-mac.cc.
References m_secondReceiveWindowDataRate.
SetSecondReceiveWindowFrequency()
void ns3::lorawan::ClassAEndDeviceLorawanMac::SetSecondReceiveWindowFrequency (double frequencyMHz)
Set the frequency that will be used for the second receive window.
Parameters
frequencyMHz the Frequency.
Definition at line 507 of file class-a-end-device-lorawan-mac.cc.
References m_secondReceiveWindowFrequency.
TxFinished()
void ns3::lorawan::ClassAEndDeviceLorawanMac::TxFinished (Ptr< const Packet > packet) virtual
Perform the actions that are required after a packet send.
This function handles opening of the first receive window.
Reimplemented from ns3::lorawan::EndDeviceLorawanMac.
Definition at line 267 of file class-a-end-device-lorawan-mac.cc.
References ns3::lorawan::LorawanMac::m_phy, m_receiveDelay1, m_receiveDelay2, m_secondReceiveWindow, NS_LOG_FUNCTION_NOARGS, OpenFirstReceiveWindow(), OpenSecondReceiveWindow(), and ns3::Simulator::Schedule().
Member Data Documentation
m_closeFirstWindow
EventId ns3::lorawan::ClassAEndDeviceLorawanMac::m_closeFirstWindow private
The event of the closing the first receive window.
This Event will be canceled if there's a successful reception of a packet.
Definition at line 184 of file class-a-end-device-lorawan-mac.h.
Referenced by ClassAEndDeviceLorawanMac(), GetNextClassTransmissionDelay(), and OpenFirstReceiveWindow().
m_closeSecondWindow
EventId ns3::lorawan::ClassAEndDeviceLorawanMac::m_closeSecondWindow private
The event of the closing the second receive window.
This Event will be canceled if there's a successful reception of a packet.
Definition at line 191 of file class-a-end-device-lorawan-mac.h.
Referenced by ClassAEndDeviceLorawanMac(), GetNextClassTransmissionDelay(), and OpenSecondReceiveWindow().
m_receiveDelay1
Time ns3::lorawan::ClassAEndDeviceLorawanMac::m_receiveDelay1 private
The interval between when a packet is done sending and when the first receive window is opened.
Definition at line 171 of file class-a-end-device-lorawan-mac.h.
Referenced by TxFinished().
m_receiveDelay2
Time ns3::lorawan::ClassAEndDeviceLorawanMac::m_receiveDelay2 private
The interval between when a packet is done sending and when the second receive window is opened.
Definition at line 177 of file class-a-end-device-lorawan-mac.h.
Referenced by TxFinished().
m_rx1DrOffset
uint8_t ns3::lorawan::ClassAEndDeviceLorawanMac::m_rx1DrOffset private
The RX1DROffset parameter value.
Definition at line 214 of file class-a-end-device-lorawan-mac.h.
Referenced by GetFirstReceiveWindowDataRate(), OnRxClassParamSetupReq(), and SendToPhy().
m_secondReceiveWindow
EventId ns3::lorawan::ClassAEndDeviceLorawanMac::m_secondReceiveWindow private
The event of the second receive window opening.
This Event is used to cancel the second window in case the first one is successful.
Definition at line 199 of file class-a-end-device-lorawan-mac.h.
Referenced by ClassAEndDeviceLorawanMac(), FailedReception(), GetNextClassTransmissionDelay(), Receive(), and TxFinished().
m_secondReceiveWindowDataRate
uint8_t ns3::lorawan::ClassAEndDeviceLorawanMac::m_secondReceiveWindowDataRate private
The Data Rate to listen for during the second downlink transmission.
Definition at line 209 of file class-a-end-device-lorawan-mac.h.
Referenced by GetSecondReceiveWindowDataRate(), OnRxClassParamSetupReq(), OpenSecondReceiveWindow(), and SetSecondReceiveWindowDataRate().
m_secondReceiveWindowFrequency
double ns3::lorawan::ClassAEndDeviceLorawanMac::m_secondReceiveWindowFrequency private
The frequency to listen on for the second receive window.
Definition at line 204 of file class-a-end-device-lorawan-mac.h.
Referenced by GetSecondReceiveWindowFrequency(), OnRxClassParamSetupReq(), OpenSecondReceiveWindow(), and SetSecondReceiveWindowFrequency().
The documentation for this class was generated from the following files:
src/lorawan/model/class-a-end-device-lorawan-mac.h
src/lorawan/model/class-a-end-device-lorawan-mac.cc