ns-3: ns3::Gnuplot Class Reference
ns3::Gnuplot Class Reference
Statistics » Gnuplot
a simple class to generate gnuplot-ready plotting commands from a set of datasets.
#include "gnuplot.h"
Public Member Functions
Gnuplot (const std::string &outputFilename="", const std::string &title="")
void AddDataset (const GnuplotDataset &dataset)
void AppendExtra (const std::string &extra)
void GenerateOutput (std::ostream &os)
Writes gnuplot commands and data values to a single output stream.
void GenerateOutput (std::ostream &osControl, std::ostream &osData, std::string dataFileName)
Writes gnuplot commands and data values to two different outputs streams.
void SetDataFileDatasetIndex (unsigned int index)
Sets the current data stream index in the data file.
void SetExtra (const std::string &extra)
void SetLegend (const std::string &xLegend, const std::string &yLegend)
void SetOutputFilename (const std::string &outputFilename)
void SetTerminal (const std::string &terminal)
void SetTitle (const std::string &title)
Static Public Member Functions
static std::string DetectTerminal (const std::string &filename)
Crude attempt to auto-detect the correct terminal setting by inspecting the filename's extension.
Private Types
typedef std::vector< GnuplotDataset > Datasets
Type for Datasets to be used in plots.
Private Attributes
unsigned int m_dataFileDatasetIndex
Data set index to plot.
Datasets m_datasets
Data sets.
std::string m_extra
extra parameters for the plot
bool m_generateOneOutputFile
true if only one plot will be generated
std::string m_outputFilename
Output file name.
std::string m_terminal
Gnuplot "terminal" to use.
std::string m_title
Plot title.
std::string m_xLegend
X axis legend.
std::string m_yLegend
Y axis legend.
Detailed Description
a simple class to generate gnuplot-ready plotting commands from a set of datasets.
This class really represents a single graph on which multiple datasets can be plotted.
Definition at line 371 of file gnuplot.h.
Member Typedef Documentation
Datasets
typedef std::vector<GnuplotDataset> ns3::Gnuplot::Datasets private
Type for Datasets to be used in plots.
Definition at line 464 of file gnuplot.h.
Constructor & Destructor Documentation
Gnuplot()
ns3::Gnuplot::Gnuplot (const std::string & outputFilename = "", const std::string & title = "")
Parameters
outputFilename the name of the file where the rendering of the graph will be generated if you feed the command stream output by Gnuplot::GenerateOutput to the gnuplot program.
title title line of the plot page
Definition at line 694 of file gnuplot.cc.
Member Function Documentation
AddDataset()
void ns3::Gnuplot::AddDataset (const GnuplotDataset & dataset)
Parameters
dataset add a dataset to the graph to be plotted.
Definition at line 756 of file gnuplot.cc.
References m_datasets.
Referenced by ns3::GnuplotAggregator::Add2dDataset(), anonymous_namespace{gnuplot-example.cc}::Create2DPlotFile(), anonymous_namespace{gnuplot-example.cc}::Create2DPlotWithErrorBarsFile(), anonymous_namespace{gnuplot-example.cc}::Create3DPlotFile(), TestDeterministic(), TestDeterministicByTime(), and TestProbabilistic().
AppendExtra()
void ns3::Gnuplot::AppendExtra (const std::string & extra)
Parameters
extra append extra gnuplot directive for output.
Definition at line 749 of file gnuplot.cc.
References m_extra.
Referenced by ns3::GnuplotAggregator::~GnuplotAggregator(), ns3::GnuplotAggregator::AppendExtra(), anonymous_namespace{gnuplot-example.cc}::Create2DPlotFile(), anonymous_namespace{gnuplot-example.cc}::Create2DPlotWithErrorBarsFile(), anonymous_namespace{gnuplot-example.cc}::Create3DPlotFile(), ns3::GnuplotAggregator::SetKeyLocation(), TestDeterministic(), TestDeterministicByTime(), and TestProbabilistic().
DetectTerminal()
std::string ns3::Gnuplot::DetectTerminal (const std::string & filename) static
Crude attempt to auto-detect the correct terminal setting by inspecting the filename's extension.
Parameters
filename output filename
Returns
File extension of the provided filename
Definition at line 708 of file gnuplot.cc.
GenerateOutput() [1/2]
void ns3::Gnuplot::GenerateOutput (std::ostream & os)
Writes gnuplot commands and data values to a single output stream.
Parameters
os the output stream on which the relevant gnuplot commands should be generated. Including output file and terminal headers.
Definition at line 762 of file gnuplot.cc.
References m_generateOneOutputFile.
Referenced by ns3::GnuplotAggregator::~GnuplotAggregator(), anonymous_namespace{gnuplot-example.cc}::Create2DPlotFile(), anonymous_namespace{gnuplot-example.cc}::Create2DPlotWithErrorBarsFile(), and anonymous_namespace{gnuplot-example.cc}::Create3DPlotFile().
GenerateOutput() [2/2]
void ns3::Gnuplot::GenerateOutput (std::ostream & osControl, std::ostream & osData, std::string dataFileName)
Writes gnuplot commands and data values to two different outputs streams.
Parameters
osControl the output stream on which the relevant gnuplot control commands should be generated. Including output file and terminal headers.
osData the output stream on which the relevant gnuplot data values should be generated.
dataFileName the name for the data file that will be written.
Definition at line 773 of file gnuplot.cc.
References m_dataFileDatasetIndex, m_datasets, m_extra, m_generateOneOutputFile, m_outputFilename, m_terminal, m_title, m_xLegend, m_yLegend, and NS_ASSERT_MSG().
SetDataFileDatasetIndex()
void ns3::Gnuplot::SetDataFileDatasetIndex (unsigned int index)
Sets the current data stream index in the data file.
Parameters
index the index for the data stream in the data file.
Definition at line 848 of file gnuplot.cc.
References m_dataFileDatasetIndex.
SetExtra()
void ns3::Gnuplot::SetExtra (const std::string & extra)
Parameters
extra set extra gnuplot directive for output.
Definition at line 743 of file gnuplot.cc.
References m_extra.
Referenced by ns3::GnuplotAggregator::SetExtra().
SetLegend()
void ns3::Gnuplot::SetLegend (const std::string & xLegend, const std::string & yLegend)
Parameters
xLegend the legend for the x horizontal axis
yLegend the legend for the y vertical axis
Definition at line 736 of file gnuplot.cc.
References m_xLegend, and m_yLegend.
Referenced by anonymous_namespace{gnuplot-example.cc}::Create2DPlotFile(), anonymous_namespace{gnuplot-example.cc}::Create2DPlotWithErrorBarsFile(), and ns3::GnuplotAggregator::SetLegend().
SetOutputFilename()
void ns3::Gnuplot::SetOutputFilename (const std::string & outputFilename)
Parameters
outputFilename the name of the file where the rendering of the graph will be generated if you feed the command stream output by Gnuplot::GenerateOutput to the gnuplot program.
Definition at line 703 of file gnuplot.cc.
References m_outputFilename.
Referenced by ns3::GnuplotAggregator::SetTerminal().
SetTerminal()
void ns3::Gnuplot::SetTerminal (const std::string & terminal)
Parameters
terminal terminal setting string for output. The default terminal string is "png"
Definition at line 724 of file gnuplot.cc.
References m_terminal.
Referenced by anonymous_namespace{gnuplot-example.cc}::Create2DPlotFile(), anonymous_namespace{gnuplot-example.cc}::Create2DPlotWithErrorBarsFile(), anonymous_namespace{gnuplot-example.cc}::Create3DPlotFile(), and ns3::GnuplotAggregator::SetTerminal().
SetTitle()
void ns3::Gnuplot::SetTitle (const std::string & title)
Parameters
title set new plot title string to use for this plot.
Definition at line 730 of file gnuplot.cc.
References m_title.
Referenced by anonymous_namespace{gnuplot-example.cc}::Create2DPlotFile(), anonymous_namespace{gnuplot-example.cc}::Create2DPlotWithErrorBarsFile(), anonymous_namespace{gnuplot-example.cc}::Create3DPlotFile(), and ns3::GnuplotAggregator::SetTitle().
Member Data Documentation
m_dataFileDatasetIndex
unsigned int ns3::Gnuplot::m_dataFileDatasetIndex private
Data set index to plot.
Definition at line 478 of file gnuplot.h.
Referenced by GenerateOutput(), and SetDataFileDatasetIndex().
m_datasets
Datasets ns3::Gnuplot::m_datasets private
Data sets.
Definition at line 469 of file gnuplot.h.
Referenced by AddDataset(), and GenerateOutput().
m_extra
std::string ns3::Gnuplot::m_extra private
extra parameters for the plot
Definition at line 474 of file gnuplot.h.
Referenced by AppendExtra(), GenerateOutput(), and SetExtra().
m_generateOneOutputFile
bool ns3::Gnuplot::m_generateOneOutputFile private
true if only one plot will be generated
Definition at line 476 of file gnuplot.h.
Referenced by GenerateOutput().
m_outputFilename
std::string ns3::Gnuplot::m_outputFilename private
Output file name.
Definition at line 466 of file gnuplot.h.
Referenced by GenerateOutput(), and SetOutputFilename().
m_terminal
std::string ns3::Gnuplot::m_terminal private
Gnuplot "terminal" to use.
Definition at line 467 of file gnuplot.h.
Referenced by GenerateOutput(), and SetTerminal().
m_title
std::string ns3::Gnuplot::m_title private
Plot title.
Definition at line 471 of file gnuplot.h.
Referenced by GenerateOutput(), and SetTitle().
m_xLegend
std::string ns3::Gnuplot::m_xLegend private
X axis legend.
Definition at line 472 of file gnuplot.h.
Referenced by GenerateOutput(), and SetLegend().
m_yLegend
std::string ns3::Gnuplot::m_yLegend private
Y axis legend.
Definition at line 473 of file gnuplot.h.
Referenced by GenerateOutput(), and SetLegend().
The documentation for this class was generated from the following files:
src/stats/model/gnuplot.h
src/stats/model/gnuplot.cc