ns-3: WaypointInitialPositionIsWaypoint Class Reference
WaypointInitialPositionIsWaypoint Class Reference
Mobility » mobility module tests | Test suites
Waypoint Initial Position Is Waypoint Test.
Public Member Functions
WaypointInitialPositionIsWaypoint ()
virtual ~WaypointInitialPositionIsWaypoint ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void TestNumWaypoints (Ptr< const WaypointMobilityModel > model, uint32_t num)
Test number of way points.
void TestXPosition (Ptr< const WaypointMobilityModel > model, double expectedXPos)
Text X position function.
Private Attributes
Ptr< WaypointMobilityModel > m_mob1
mobility model 1
Ptr< WaypointMobilityModel > m_mob2
mobility model 2
Ptr< WaypointMobilityModel > m_mob3
mobility model 3
Ptr< WaypointMobilityModel > m_mob4
mobility model 4
Ptr< WaypointMobilityModel > m_mob5
mobility model 5
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Waypoint Initial Position Is Waypoint Test.
Definition at line 190 of file mobility-test-suite.cc.
Constructor & Destructor Documentation
WaypointInitialPositionIsWaypoint()
WaypointInitialPositionIsWaypoint::WaypointInitialPositionIsWaypoint ()
Definition at line 217 of file mobility-test-suite.cc.
~WaypointInitialPositionIsWaypoint()
WaypointInitialPositionIsWaypoint::~WaypointInitialPositionIsWaypoint () virtual
Definition at line 222 of file mobility-test-suite.cc.
Member Function Documentation
DoRun()
void WaypointInitialPositionIsWaypoint::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 240 of file mobility-test-suite.cc.
References ns3::WaypointMobilityModel::AddWaypoint(), m_mob1, m_mob2, m_mob3, m_mob4, m_mob5, ns3::Seconds(), ns3::ObjectBase::SetAttributeFailSafe(), ns3::MobilityModel::SetPosition(), TestNumWaypoints(), and TestXPosition().
TestNumWaypoints()
void WaypointInitialPositionIsWaypoint::TestNumWaypoints (Ptr< const WaypointMobilityModel > model, uint32_t num) private
Test number of way points.
Parameters
model the mobility model
num the number of way points
Definition at line 234 of file mobility-test-suite.cc.
References NS_TEST_EXPECT_MSG_EQ, and ns3::WaypointMobilityModel::WaypointsLeft().
Referenced by DoRun().
TestXPosition()
void WaypointInitialPositionIsWaypoint::TestXPosition (Ptr< const WaypointMobilityModel > model, double expectedXPos) private
Text X position function.
Parameters
model the mobility model
expectedXPos the expected X position
Definition at line 227 of file mobility-test-suite.cc.
References ns3::MobilityModel::GetPosition(), and NS_TEST_EXPECT_MSG_EQ_TOL_INTERNAL.
Referenced by DoRun().
Member Data Documentation
m_mob1
Ptr<WaypointMobilityModel> WaypointInitialPositionIsWaypoint::m_mob1 private
mobility model 1
Definition at line 210 of file mobility-test-suite.cc.
Referenced by DoRun().
m_mob2
Ptr<WaypointMobilityModel> WaypointInitialPositionIsWaypoint::m_mob2 private
mobility model 2
Definition at line 211 of file mobility-test-suite.cc.
Referenced by DoRun().
m_mob3
Ptr<WaypointMobilityModel> WaypointInitialPositionIsWaypoint::m_mob3 private
mobility model 3
Definition at line 212 of file mobility-test-suite.cc.
Referenced by DoRun().
m_mob4
Ptr<WaypointMobilityModel> WaypointInitialPositionIsWaypoint::m_mob4 private
mobility model 4
Definition at line 213 of file mobility-test-suite.cc.
Referenced by DoRun().
m_mob5
Ptr<WaypointMobilityModel> WaypointInitialPositionIsWaypoint::m_mob5 private
mobility model 5
Definition at line 214 of file mobility-test-suite.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/mobility/test/mobility-test-suite.cc