ns-3: ns3::AthstatsHelper Class Reference
ns3::AthstatsHelper Class Reference
create AthstatsWifiTraceSink instances and connect them to wifi devices
#include "athstats-helper.h"
Public Member Functions
AthstatsHelper ()
void EnableAthstats (std::string filename, NetDeviceContainer d)
Enable athstats.
void EnableAthstats (std::string filename, NodeContainer n)
Enable athstats.
void EnableAthstats (std::string filename, Ptr< NetDevice > nd)
Enable athstats.
void EnableAthstats (std::string filename, uint32_t nodeid, uint32_t deviceid)
Enable athstats.
Private Attributes
Time m_interval
interval
Detailed Description
create AthstatsWifiTraceSink instances and connect them to wifi devices
Definition at line 39 of file athstats-helper.h.
Constructor & Destructor Documentation
AthstatsHelper()
ns3::AthstatsHelper::AthstatsHelper ()
Definition at line 37 of file athstats-helper.cc.
Member Function Documentation
EnableAthstats() [1/4]
void ns3::AthstatsHelper::EnableAthstats (std::string filename, NetDeviceContainer d)
Enable athstats.
Parameters
filename the file name
d the collection of devices
Definition at line 77 of file athstats-helper.cc.
References ns3::NetDeviceContainer::Begin(), EnableAthstats(), and ns3::NetDeviceContainer::End().
EnableAthstats() [2/4]
void ns3::AthstatsHelper::EnableAthstats (std::string filename, NodeContainer n)
Enable athstats.
Parameters
filename the file name
n the collection of nodes
Definition at line 87 of file athstats-helper.cc.
References ns3::NetDeviceContainer::Add(), EnableAthstats(), ns3::Node::GetDevice(), ns3::Node::GetNDevices(), and sample-rng-plot::n.
EnableAthstats() [3/4]
void ns3::AthstatsHelper::EnableAthstats (std::string filename, Ptr< NetDevice > nd)
Enable athstats.
Parameters
filename the file name
nd the device
Definition at line 71 of file athstats-helper.cc.
References EnableAthstats().
EnableAthstats() [4/4]
void ns3::AthstatsHelper::EnableAthstats (std::string filename, uint32_t nodeid, uint32_t deviceid)
Enable athstats.
Parameters
filename the file name
nodeid the node ID
deviceid the device ID
Definition at line 43 of file athstats-helper.cc.
References ns3::Config::Connect(), ns3::AthstatsWifiTraceSink::DevRxTrace(), ns3::AthstatsWifiTraceSink::DevTxTrace(), ns3::MakeCallback(), ns3::AthstatsWifiTraceSink::PhyRxErrorTrace(), ns3::AthstatsWifiTraceSink::PhyRxOkTrace(), ns3::AthstatsWifiTraceSink::PhyStateTrace(), ns3::AthstatsWifiTraceSink::PhyTxTrace(), ns3::AthstatsWifiTraceSink::TxDataFailedTrace(), ns3::AthstatsWifiTraceSink::TxFinalDataFailedTrace(), ns3::AthstatsWifiTraceSink::TxFinalRtsFailedTrace(), and ns3::AthstatsWifiTraceSink::TxRtsFailedTrace().
Referenced by EnableAthstats().
Member Data Documentation
m_interval
Time ns3::AthstatsHelper::m_interval private
interval
Definition at line 70 of file athstats-helper.h.
The documentation for this class was generated from the following files:
src/wifi/helper/athstats-helper.h
src/wifi/helper/athstats-helper.cc