ns-3: ns3::RipRte Class Reference
ns3::RipRte Class Reference
Internet » IPv4 Routing Protocols. » RIP
Rip v2 Routing Table Entry (RTE) - see RFC 2453.
#include "rip-header.h"
Public Member Functions
RipRte (void)
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
virtual TypeId GetInstanceTypeId (void) const
Return the instance type identifier.
Ipv4Address GetNextHop (void) const
Get the next hop.
Ipv4Address GetPrefix (void) const
Get the prefix.
uint32_t GetRouteMetric (void) const
Get the route metric.
uint16_t GetRouteTag (void) const
Get the route tag.
virtual uint32_t GetSerializedSize (void) const
Get the serialized size of the packet.
Ipv4Mask GetSubnetMask (void) const
Get the subnet mask.
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetNextHop (Ipv4Address nextHop)
Set the next hop.
void SetPrefix (Ipv4Address prefix)
Set the prefix.
void SetRouteMetric (uint32_t routeMetric)
Set the route metric.
void SetRouteTag (uint16_t routeTag)
Set the route tag.
void SetSubnetMask (Ipv4Mask subnetMask)
Set the subnet mask.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint32_t m_metric
Route metric.
Ipv4Address m_nextHop
Next hop.
Ipv4Address m_prefix
Advertised prefix.
Ipv4Mask m_subnetMask
Subnet mask.
uint16_t m_tag
Route tag.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Rip v2 Routing Table Entry (RTE) - see RFC 2453.
Definition at line 37 of file rip-header.h.
Constructor & Destructor Documentation
RipRte()
ns3::RipRte::RipRte (void)
Definition at line 32 of file rip-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::RipRte::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start Buffer iterator.
Returns
Size of the packet.
Implements ns3::Header.
Definition at line 73 of file rip-header.cc.
References GetSerializedSize(), m_metric, m_nextHop, m_prefix, m_subnetMask, m_tag, ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadNtohU32(), ns3::Ipv4Address::Set(), and ns3::Ipv4Mask::Set().
Referenced by ns3::RipHeader::Deserialize().
GetInstanceTypeId()
TypeId ns3::RipRte::GetInstanceTypeId (void) const virtual
Return the instance type identifier.
Returns
Instance type ID.
Implements ns3::ObjectBase.
Definition at line 46 of file rip-header.cc.
References GetTypeId().
GetNextHop()
Ipv4Address ns3::RipRte::GetNextHop (void) const
Get the next hop.
Returns
The next hop.
Definition at line 138 of file rip-header.cc.
References m_nextHop.
GetPrefix()
Ipv4Address ns3::RipRte::GetPrefix (void) const
Get the prefix.
Returns
The prefix.
Definition at line 98 of file rip-header.cc.
References m_prefix.
GetRouteMetric()
uint32_t ns3::RipRte::GetRouteMetric (void) const
Get the route metric.
Returns
The route metric.
Definition at line 128 of file rip-header.cc.
References m_metric.
GetRouteTag()
uint16_t ns3::RipRte::GetRouteTag (void) const
Get the route tag.
Returns
The route tag.
Definition at line 118 of file rip-header.cc.
References m_tag.
GetSerializedSize()
uint32_t ns3::RipRte::GetSerializedSize (void) const virtual
Get the serialized size of the packet.
Returns
Size.
Implements ns3::Header.
Definition at line 57 of file rip-header.cc.
Referenced by Deserialize(), ns3::Rip::DoSendRouteUpdate(), ns3::RipHeader::GetSerializedSize(), and ns3::Rip::HandleRequests().
GetSubnetMask()
Ipv4Mask ns3::RipRte::GetSubnetMask (void) const
Get the subnet mask.
Returns
The subnet mask.
Definition at line 108 of file rip-header.cc.
References m_subnetMask.
GetTypeId()
TypeId ns3::RipRte::GetTypeId (void) static
Get the type ID.
Returns
The object TypeId.
Definition at line 37 of file rip-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::RipRte::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 51 of file rip-header.cc.
References ns3::Ipv4Mask::GetPrefixLength(), m_metric, m_nextHop, m_prefix, m_subnetMask, and m_tag.
Referenced by ns3::operator<<().
Serialize()
void ns3::RipRte::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start Buffer iterator.
Implements ns3::Header.
Definition at line 62 of file rip-header.cc.
References ns3::Ipv4Address::Get(), ns3::Ipv4Mask::Get(), m_metric, m_nextHop, m_prefix, m_subnetMask, m_tag, ns3::Buffer::Iterator::WriteHtonU16(), and ns3::Buffer::Iterator::WriteHtonU32().
SetNextHop()
void ns3::RipRte::SetNextHop (Ipv4Address nextHop)
Set the next hop.
Parameters
nextHop The next hop.
Definition at line 133 of file rip-header.cc.
References m_nextHop.
SetPrefix()
void ns3::RipRte::SetPrefix (Ipv4Address prefix)
Set the prefix.
Parameters
prefix The prefix.
Definition at line 93 of file rip-header.cc.
References m_prefix.
Referenced by ns3::Rip::DoSendRouteUpdate(), ns3::Rip::HandleRequests(), and ns3::Rip::SendRouteRequest().
SetRouteMetric()
void ns3::RipRte::SetRouteMetric (uint32_t routeMetric)
Set the route metric.
Parameters
routeMetric The route metric.
Definition at line 123 of file rip-header.cc.
References m_metric.
Referenced by ns3::Rip::DoSendRouteUpdate(), ns3::Rip::HandleRequests(), and ns3::Rip::SendRouteRequest().
SetRouteTag()
void ns3::RipRte::SetRouteTag (uint16_t routeTag)
Set the route tag.
Parameters
routeTag The route tag.
Definition at line 113 of file rip-header.cc.
References m_tag.
Referenced by ns3::Rip::DoSendRouteUpdate(), and ns3::Rip::HandleRequests().
SetSubnetMask()
void ns3::RipRte::SetSubnetMask (Ipv4Mask subnetMask)
Set the subnet mask.
Parameters
subnetMask The subnet mask.
Definition at line 103 of file rip-header.cc.
References m_subnetMask.
Referenced by ns3::Rip::DoSendRouteUpdate(), ns3::Rip::HandleRequests(), and ns3::Rip::SendRouteRequest().
Member Data Documentation
m_metric
uint32_t ns3::RipRte::m_metric private
Route metric.
Definition at line 141 of file rip-header.h.
Referenced by Deserialize(), GetRouteMetric(), Print(), Serialize(), and SetRouteMetric().
m_nextHop
Ipv4Address ns3::RipRte::m_nextHop private
Next hop.
Definition at line 140 of file rip-header.h.
Referenced by Deserialize(), GetNextHop(), Print(), Serialize(), and SetNextHop().
m_prefix
Ipv4Address ns3::RipRte::m_prefix private
Advertised prefix.
Definition at line 138 of file rip-header.h.
Referenced by Deserialize(), GetPrefix(), Print(), Serialize(), and SetPrefix().
m_subnetMask
Ipv4Mask ns3::RipRte::m_subnetMask private
Subnet mask.
Definition at line 139 of file rip-header.h.
Referenced by Deserialize(), GetSubnetMask(), Print(), Serialize(), and SetSubnetMask().
m_tag
uint16_t ns3::RipRte::m_tag private
Route tag.
Definition at line 137 of file rip-header.h.
Referenced by Deserialize(), GetRouteTag(), Print(), Serialize(), and SetRouteTag().
The documentation for this class was generated from the following files:
src/internet/model/rip-header.h
src/internet/model/rip-header.cc