ns-3: Ns3WimaxSchedulingTestCase Class Reference
Ns3WimaxSchedulingTestCase Class Reference
WiMAX Models » wimax module tests | Test suites
Ns3 Wimax Scheduling Test Case.
Public Member Functions
Ns3WimaxSchedulingTestCase ()
virtual ~Ns3WimaxSchedulingTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
bool DoRunOnce (WimaxHelper::SchedulerType scheduler)
Run once function.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Ns3 Wimax Scheduling Test Case.
Definition at line 42 of file qos-test.cc.
Constructor & Destructor Documentation
Ns3WimaxSchedulingTestCase()
Ns3WimaxSchedulingTestCase::Ns3WimaxSchedulingTestCase ()
Definition at line 59 of file qos-test.cc.
~Ns3WimaxSchedulingTestCase()
Ns3WimaxSchedulingTestCase::~Ns3WimaxSchedulingTestCase () virtual
Definition at line 64 of file qos-test.cc.
Member Function Documentation
DoRun()
void Ns3WimaxSchedulingTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 152 of file qos-test.cc.
References DoRunOnce().
DoRunOnce()
bool Ns3WimaxSchedulingTestCase::DoRunOnce (WimaxHelper::SchedulerType scheduler) private
Run once function.
Parameters
scheduler the wimax scheduler type
Returns
true if successful
Definition at line 69 of file qos-test.cc.
References first::address, ns3::NodeContainer::Create(), ns3::WimaxHelper::CreateServiceFlow(), ns3::NetDeviceContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::WimaxHelper::Install(), ns3::Seconds(), and first::stack.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/wimax/test/qos-test.cc