ns-3: RandomRoomPositionAllocatorTestCase Class Reference
RandomRoomPositionAllocatorTestCase Class Reference
Public Member Functions
RandomRoomPositionAllocatorTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 64 of file building-position-allocator-test.cc.
Constructor & Destructor Documentation
RandomRoomPositionAllocatorTestCase()
RandomRoomPositionAllocatorTestCase::RandomRoomPositionAllocatorTestCase ()
Definition at line 75 of file building-position-allocator-test.cc.
Member Function Documentation
DoRun()
void RandomRoomPositionAllocatorTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 81 of file building-position-allocator-test.cc.
References ns3::MobilityBuildingInfo::GetFloorNumber(), ns3::Object::GetObject(), ns3::MobilityModel::GetPosition(), ns3::MobilityBuildingInfo::GetRoomNumberX(), ns3::MobilityBuildingInfo::GetRoomNumberY(), ns3::MobilityBuildingInfo::IsIndoor(), third::mobility, first::nodes, NS_ASSERT_MSG(), NS_LOG_FUNCTION, NS_LOG_LOGIC(), NS_TEST_ASSERT_MSG_EQ, NS_TEST_ASSERT_MSG_GT, NS_TEST_ASSERT_MSG_LT, ns3::Building::SetBoundaries(), ns3::Building::SetNFloors(), ns3::Building::SetNRoomsX(), and ns3::Building::SetNRoomsY().
The documentation for this class was generated from the following file:
src/buildings/test/building-position-allocator-test.cc