ns-3: ThreeGppChannelMatrixComputationTest Class Reference
ThreeGppChannelMatrixComputationTest Class Reference
Test case for the ThreeGppChannelModel class.
Public Member Functions
ThreeGppChannelMatrixComputationTest ()
Constructor.
virtual ~ThreeGppChannelMatrixComputationTest ()
Destructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void DoComputeNorm (Ptr< ThreeGppChannelModel > channelModel, Ptr< MobilityModel > txMob, Ptr< MobilityModel > rxMob, Ptr< ThreeGppAntennaArrayModel > txAntenna, Ptr< ThreeGppAntennaArrayModel > rxAntenna)
Compute the Frobenius norm of the channel matrix and stores it in m_normVector.
virtual void DoRun (void)
Build the test scenario.
Private Attributes
std::vector< double > m_normVector
each element is the norm of a channel realization
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test case for the ThreeGppChannelModel class.
1) check if the channel matrix has the correct dimensions 2) check if the channel matrix is correctly normalized
Definition at line 48 of file three-gpp-channel-test-suite.cc.
Constructor & Destructor Documentation
ThreeGppChannelMatrixComputationTest()
ThreeGppChannelMatrixComputationTest::ThreeGppChannelMatrixComputationTest ()
Constructor.
Definition at line 80 of file three-gpp-channel-test-suite.cc.
~ThreeGppChannelMatrixComputationTest()
ThreeGppChannelMatrixComputationTest::~ThreeGppChannelMatrixComputationTest () virtual
Destructor.
Definition at line 85 of file three-gpp-channel-test-suite.cc.
Member Function Documentation
DoComputeNorm()
void ThreeGppChannelMatrixComputationTest::DoComputeNorm (Ptr< ThreeGppChannelModel > channelModel, Ptr< MobilityModel > txMob, Ptr< MobilityModel > rxMob, Ptr< ThreeGppAntennaArrayModel > txAntenna, Ptr< ThreeGppAntennaArrayModel > rxAntenna) private
Compute the Frobenius norm of the channel matrix and stores it in m_normVector.
Parameters
channelModel the ThreeGppChannelModel object used to generate the channel matrix
txMob the mobility model of the first node
rxMob the mobility model of the second node
txAntenna the antenna object associated to the first node
rxAntenna the antenna object associated to the second node
Definition at line 90 of file three-gpp-channel-test-suite.cc.
References ns3::ThreeGppChannelModel::GetChannel(), ns3::ThreeGppAntennaArrayModel::GetNumberOfElements(), ns3::ThreeGppChannelModel::ThreeGppChannelMatrix::m_channel, and m_normVector.
Referenced by DoRun().
DoRun()
void ThreeGppChannelMatrixComputationTest::DoRun (void) private virtual
Build the test scenario.
Implements ns3::TestCase.
Definition at line 115 of file three-gpp-channel-test-suite.cc.
References DoComputeNorm(), ns3::ThreeGppChannelModel::GetChannel(), ns3::ThreeGppChannelModel::ThreeGppChannelMatrix::m_channel, m_normVector, ns3::MilliSeconds(), first::nodes, NS_TEST_ASSERT_MSG_EQ, NS_TEST_ASSERT_MSG_EQ_TOL, ns3::ObjectBase::SetAttribute(), ns3::SimpleNetDevice::SetNode(), and ns3::MobilityModel::SetPosition().
Member Data Documentation
m_normVector
std::vector<double> ThreeGppChannelMatrixComputationTest::m_normVector private
each element is the norm of a channel realization
Definition at line 77 of file three-gpp-channel-test-suite.cc.
Referenced by DoComputeNorm(), and DoRun().
The documentation for this class was generated from the following file:
src/spectrum/test/three-gpp-channel-test-suite.cc