ns-3: OriginatorBlockAckWindowTest Class Reference
OriginatorBlockAckWindowTest Class Reference
Wifi Models » wifi module tests | Test suites
Test for the originator block ack window.
Public Member Functions
OriginatorBlockAckWindowTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun ()
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test for the originator block ack window.
Definition at line 260 of file block-ack-test-suite.cc.
Constructor & Destructor Documentation
OriginatorBlockAckWindowTest()
OriginatorBlockAckWindowTest::OriginatorBlockAckWindowTest ()
Definition at line 268 of file block-ack-test-suite.cc.
Member Function Documentation
DoRun()
void OriginatorBlockAckWindowTest::DoRun () private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 274 of file block-ack-test-suite.cc.
References ns3::BlockAckWindow::At(), ns3::WifiMacQueueItem::GetHeader(), ns3::OriginatorBlockAckAgreement::GetStartingSequence(), ns3::BlockAckWindow::GetWinEnd(), ns3::BlockAckWindow::GetWinSize(), ns3::BlockAckWindow::GetWinStart(), ns3::OriginatorBlockAckAgreement::InitTxWindow(), ns3::OriginatorBlockAckAgreement::m_txWindow, ns3::OriginatorBlockAckAgreement::NotifyAckedMpdu(), ns3::OriginatorBlockAckAgreement::NotifyDiscardedMpdu(), ns3::OriginatorBlockAckAgreement::NotifyTransmittedMpdu(), NS_TEST_EXPECT_MSG_EQ, ns3::SEQNO_SPACE_SIZE, ns3::BlockAckAgreement::SetBufferSize(), ns3::WifiMacHeader::SetSequenceNumber(), ns3::BlockAckAgreement::SetStartingSequence(), ns3::WifiMacHeader::SetType(), and ns3::WIFI_MAC_QOSDATA.
The documentation for this class was generated from the following file:
src/wifi/test/block-ack-test-suite.cc