ns-3: ns3::lorawan::ForwarderHelper Class Reference
ns3::lorawan::ForwarderHelper Class Reference
This class can be used to install Forwarder applications on a set of gateways.
#include "forwarder-helper.h"
Public Member Functions
ForwarderHelper ()
~ForwarderHelper ()
ApplicationContainer Install (NodeContainer c) const
ApplicationContainer Install (Ptr< Node > node) const
void SetAttribute (std::string name, const AttributeValue &value)
Private Member Functions
Ptr< Application > InstallPriv (Ptr< Node > node) const
Private Attributes
ObjectFactory m_factory
Detailed Description
This class can be used to install Forwarder applications on a set of gateways.
Definition at line 41 of file forwarder-helper.h.
Constructor & Destructor Documentation
ForwarderHelper()
ns3::lorawan::ForwarderHelper::ForwarderHelper ()
Definition at line 35 of file forwarder-helper.cc.
References m_factory, and ns3::ObjectFactory::SetTypeId().
~ForwarderHelper()
ns3::lorawan::ForwarderHelper::~ForwarderHelper ()
Definition at line 40 of file forwarder-helper.cc.
Member Function Documentation
Install() [1/2]
ApplicationContainer ns3::lorawan::ForwarderHelper::Install (NodeContainer c) const
Definition at line 57 of file forwarder-helper.cc.
References ns3::ApplicationContainer::Add(), ns3::NodeContainer::Begin(), ns3::NodeContainer::End(), and InstallPriv().
Referenced by ns3::lorawan::CreateNetworkServer().
Install() [2/2]
ApplicationContainer ns3::lorawan::ForwarderHelper::Install (Ptr< Node > node) const
Definition at line 51 of file forwarder-helper.cc.
References InstallPriv().
InstallPriv()
Ptr< Application > ns3::lorawan::ForwarderHelper::InstallPriv (Ptr< Node > node) const private
Definition at line 69 of file forwarder-helper.cc.
References ns3::Node::AddApplication(), ns3::ObjectFactory::Create(), ns3::Node::GetDevice(), ns3::Node::GetNDevices(), m_factory, ns3::MakeCallback(), NS_LOG_ERROR, NS_LOG_FUNCTION, ns3::lorawan::Forwarder::ReceiveFromLora(), and ns3::lorawan::Forwarder::ReceiveFromPointToPoint().
Referenced by Install().
SetAttribute()
void ns3::lorawan::ForwarderHelper::SetAttribute (std::string name, const AttributeValue & value)
Definition at line 45 of file forwarder-helper.cc.
References m_factory, and ns3::ObjectFactory::Set().
Member Data Documentation
m_factory
ObjectFactory ns3::lorawan::ForwarderHelper::m_factory private
Definition at line 57 of file forwarder-helper.h.
Referenced by ForwarderHelper(), InstallPriv(), and SetAttribute().
The documentation for this class was generated from the following files:
src/lorawan/helper/forwarder-helper.h
src/lorawan/helper/forwarder-helper.cc