ns-3: EpcS1uUlTestCase Class Reference
EpcS1uUlTestCase Class Reference
LTE Models » lte module tests | Test suites
EpcS1uUlTestCase class.
Public Member Functions
EpcS1uUlTestCase (std::string name, std::vector< EnbUlTestData > v)
Constructor.
virtual ~EpcS1uUlTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
std::vector< EnbUlTestData > m_enbUlTestData
ENB UL test data.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
EpcS1uUlTestCase class.
Definition at line 314 of file epc-test-s1u-uplink.cc.
Constructor & Destructor Documentation
EpcS1uUlTestCase()
EpcS1uUlTestCase::EpcS1uUlTestCase (std::string name, std::vector< EnbUlTestData > v)
Constructor.
Parameters
name the reference name
v the list of UE lists
Definition at line 332 of file epc-test-s1u-uplink.cc.
~EpcS1uUlTestCase()
EpcS1uUlTestCase::~EpcS1uUlTestCase () virtual
Definition at line 338 of file epc-test-s1u-uplink.cc.
Member Function Documentation
DoRun()
void EpcS1uUlTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 343 of file epc-test-s1u-uplink.cc.
References ns3::NoBackhaulEpcHelper::ActivateEpsBearer(), ns3::ApplicationContainer::Add(), ns3::ArpCache::Add(), ns3::NodeContainer::Add(), ns3::Node::AddApplication(), ns3::PointToPointEpcHelper::AddEnb(), ns3::Ipv4StaticRouting::AddNetworkRouteTo(), ns3::NoBackhaulEpcHelper::AddUe(), ns3::Object::AggregateObject(), ns3::Ipv4AddressHelper::Assign(), ns3::NoBackhaulEpcHelper::AssignUeIpv4Address(), ns3::NodeContainer::Create(), ns3::ApplicationContainer::Get(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::Node::GetApplication(), ns3::Ipv4L3Protocol::GetInterface(), ns3::Ipv4::GetInterfaceForDevice(), ns3::NetDeviceContainer::GetN(), ns3::NodeContainer::GetN(), ns3::Object::GetObject(), ns3::NoBackhaulEpcHelper::GetPgwNode(), ns3::EpcEnbApplication::GetS1SapProvider(), ns3::EpcTestRrc::GetS1SapUser(), ns3::Ipv4StaticRoutingHelper::GetStaticRouting(), ns3::NoBackhaulEpcHelper::GetUeDefaultGatewayAddress(), ns3::PointToPointHelper::Install(), ns3::PacketSinkHelper::Install(), ns3::CsmaHelper::Install(), ns3::InternetStackHelper::Install(), m_enbUlTestData, ns3::ArpCache::Entry::MarkPermanent(), ns3::MilliSeconds(), NS_ASSERT_MSG(), NS_LOG_INFO, NS_TEST_ASSERT_MSG_EQ, ns3::Seconds(), ns3::ArpCache::SetAliveTimeout(), ns3::ObjectBase::SetAttribute(), ns3::Ipv4AddressHelper::SetBase(), ns3::Config::SetDefault(), ns3::Ipv4StaticRouting::SetDefaultRoute(), ns3::PointToPointHelper::SetDeviceAttribute(), ns3::ArpCache::Entry::SetMacAddress(), ns3::EpcTestRrc::SetS1SapProvider(), ns3::EpcEnbApplication::SetS1SapUser(), ns3::ApplicationContainer::Start(), and ns3::ApplicationContainer::Stop().
Member Data Documentation
m_enbUlTestData
std::vector<EnbUlTestData> EpcS1uUlTestCase::m_enbUlTestData private
ENB UL test data.
Definition at line 328 of file epc-test-s1u-uplink.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/lte/test/epc-test-s1u-uplink.cc