ns-3: ns3::Icmpv6Redirection Class Reference
ns3::Icmpv6Redirection Class Reference
Internet » IPv6 classes and sub-modules » ICMPv6 protocol and associated headers.
ICMPv6 Redirection header.
#include "icmpv6-header.h"
Public Member Functions
Icmpv6Redirection ()
Constructor.
virtual ~Icmpv6Redirection ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
Ipv6Address GetDestination () const
Get the IPv6 destination address.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
uint32_t GetReserved () const
Get the reserved field.
virtual uint32_t GetSerializedSize () const
Get the serialized size.
Ipv6Address GetTarget () const
Get the IPv6 target address.
virtual void Print (std::ostream &os) const
Print information.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetDestination (Ipv6Address destination)
Set the IPv6 destination address.
void SetReserved (uint32_t reserved)
Set the reserved field.
void SetTarget (Ipv6Address target)
Set the IPv6 target address.
Public Member Functions inherited from ns3::Icmpv6Header
Icmpv6Header ()
Constructor.
virtual ~Icmpv6Header ()
Destructor.
void CalculatePseudoHeaderChecksum (Ipv6Address src, Ipv6Address dst, uint16_t length, uint8_t protocol)
Calculate pseudo header checksum for IPv6.
uint16_t GetChecksum () const
Get the checksum.
uint8_t GetCode () const
Get the code field.
uint8_t GetType () const
Get the type field.
void SetChecksum (uint16_t checksum)
Set the checksum.
void SetCode (uint8_t code)
Set the code field.
void SetType (uint8_t type)
Set the type.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the UID of this class.
Static Public Member Functions inherited from ns3::Icmpv6Header
static TypeId GetTypeId ()
Get the UID of this class.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Ipv6Address m_destination
IPv6 destination address.
uint32_t m_reserved
Reserved value.
Ipv6Address m_target
IPv6 target address.
Additional Inherited Members
Public Types inherited from ns3::Icmpv6Header
enum ErrorDestinationUnreachable_e {
ICMPV6_NO_ROUTE = 0, ICMPV6_ADM_PROHIBITED, ICMPV6_NOT_NEIGHBOUR, ICMPV6_ADDR_UNREACHABLE,
ICMPV6_PORT_UNREACHABLE
}
ICMPv6 error code : Destination Unreachable.
enum ErrorParameterError_e { ICMPV6_MALFORMED_HEADER = 0, ICMPV6_UNKNOWN_NEXT_HEADER, ICMPV6_UNKNOWN_OPTION }
ICMPv6 error code : Parameter Error.
enum ErrorTimeExceeded_e { ICMPV6_HOPLIMIT = 0, ICMPV6_FRAGTIME }
ICMPv6 error code : Time Exceeded.
enum OptionType_e {
ICMPV6_OPT_LINK_LAYER_SOURCE = 1, ICMPV6_OPT_LINK_LAYER_TARGET, ICMPV6_OPT_PREFIX, ICMPV6_OPT_REDIRECTED,
ICMPV6_OPT_MTU
}
ICMPv6 Option type code.
enum Type_e {
ICMPV6_ERROR_DESTINATION_UNREACHABLE = 1, ICMPV6_ERROR_PACKET_TOO_BIG, ICMPV6_ERROR_TIME_EXCEEDED, ICMPV6_ERROR_PARAMETER_ERROR,
ICMPV6_ECHO_REQUEST = 128, ICMPV6_ECHO_REPLY, ICMPV6_SUBSCRIBE_REQUEST, ICMPV6_SUBSCRIBE_REPORT,
ICMPV6_SUBSCRIVE_END, ICMPV6_ND_ROUTER_SOLICITATION, ICMPV6_ND_ROUTER_ADVERTISEMENT, ICMPV6_ND_NEIGHBOR_SOLICITATION,
ICMPV6_ND_NEIGHBOR_ADVERTISEMENT, ICMPV6_ND_REDIRECTION, ICMPV6_ROUTER_RENUMBER, ICMPV6_INFORMATION_REQUEST,
ICMPV6_INFORMATION_RESPONSE, ICMPV6_INVERSE_ND_SOLICITATION, ICMPV6_INVERSE_ND_ADVERSTISEMENT, ICMPV6_MLDV2_SUBSCRIBE_REPORT,
ICMPV6_MOBILITY_HA_DISCOVER_REQUEST, ICMPV6_MOBILITY_HA_DISCOVER_RESPONSE, ICMPV6_MOBILITY_MOBILE_PREFIX_SOLICITATION, ICMPV6_SECURE_ND_CERTIFICATE_PATH_SOLICITATION,
ICMPV6_SECURE_ND_CERTIFICATE_PATH_ADVERTISEMENT, ICMPV6_EXPERIMENTAL_MOBILITY
}
ICMPv6 type code.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Icmpv6Header
bool m_calcChecksum
Checksum enable or not.
uint16_t m_checksum
The checksum.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
ICMPv6 Redirection header.
Definition at line 836 of file icmpv6-header.h.
Constructor & Destructor Documentation
Icmpv6Redirection()
ns3::Icmpv6Redirection::Icmpv6Redirection ()
Constructor.
Definition at line 812 of file icmpv6-header.cc.
References ns3::Icmpv6Header::ICMPV6_ND_REDIRECTION, ns3::Icmpv6Header::m_checksum, NS_LOG_FUNCTION, ns3::Icmpv6Header::SetCode(), and ns3::Icmpv6Header::SetType().
~Icmpv6Redirection()
ns3::Icmpv6Redirection::~Icmpv6Redirection () virtual
Destructor.
Definition at line 823 of file icmpv6-header.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Deserialize()
uint32_t ns3::Icmpv6Redirection::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start start offset
Returns
length of packet
Reimplemented from ns3::Icmpv6Header.
Definition at line 905 of file icmpv6-header.cc.
References GetSerializedSize(), ns3::Icmpv6Header::m_checksum, m_destination, m_target, NS_LOG_FUNCTION, ns3::Buffer::Iterator::Read(), ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU32(), ns3::Buffer::Iterator::ReadU8(), ns3::Ipv6Address::Set(), ns3::Icmpv6Header::SetCode(), SetReserved(), ns3::Icmpv6Header::SetType(), and visualizer.core::start().
GetDestination()
Ipv6Address ns3::Icmpv6Redirection::GetDestination () const
Get the IPv6 destination address.
Returns
the IPv6 destination address
Definition at line 852 of file icmpv6-header.cc.
References m_destination, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::HandleRedirection().
GetInstanceTypeId()
TypeId ns3::Icmpv6Redirection::GetInstanceTypeId () const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::Icmpv6Header.
Definition at line 806 of file icmpv6-header.cc.
References GetTypeId(), and NS_LOG_FUNCTION.
GetReserved()
uint32_t ns3::Icmpv6Redirection::GetReserved () const
Get the reserved field.
Returns
reserved value
Definition at line 834 of file icmpv6-header.cc.
References m_reserved, and NS_LOG_FUNCTION.
GetSerializedSize()
uint32_t ns3::Icmpv6Redirection::GetSerializedSize () const virtual
Get the serialized size.
Returns
serialized size
Reimplemented from ns3::Icmpv6Header.
Definition at line 870 of file icmpv6-header.cc.
References NS_LOG_FUNCTION.
Referenced by Deserialize(), and ns3::Icmpv6L4Protocol::SendRedirection().
GetTarget()
Ipv6Address ns3::Icmpv6Redirection::GetTarget () const
Get the IPv6 target address.
Returns
the IPv6 target address
Definition at line 840 of file icmpv6-header.cc.
References m_target, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::HandleRedirection().
GetTypeId()
TypeId ns3::Icmpv6Redirection::GetTypeId () static
Get the UID of this class.
Returns
UID
Definition at line 796 of file icmpv6-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::Icmpv6Redirection::Print (std::ostream & os) const virtual
Print information.
Parameters
os output stream
Reimplemented from ns3::Icmpv6Header.
Definition at line 864 of file icmpv6-header.cc.
References ns3::Icmpv6Header::GetChecksum(), ns3::Icmpv6Header::GetCode(), ns3::Icmpv6Header::GetType(), m_destination, m_target, and NS_LOG_FUNCTION.
Serialize()
void ns3::Icmpv6Redirection::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start start offset
Reimplemented from ns3::Icmpv6Header.
Definition at line 876 of file icmpv6-header.cc.
References ns3::Buffer::Iterator::CalculateIpChecksum(), ns3::Icmpv6Header::GetChecksum(), ns3::Icmpv6Header::GetCode(), ns3::Buffer::Iterator::GetSize(), ns3::Icmpv6Header::GetType(), ns3::Icmpv6Header::m_calcChecksum, m_destination, m_reserved, m_target, ns3::Buffer::Iterator::Next(), NS_LOG_FUNCTION, ns3::Ipv6Address::Serialize(), visualizer.core::start(), ns3::Buffer::Iterator::Write(), ns3::Buffer::Iterator::WriteU16(), ns3::Buffer::Iterator::WriteU32(), and ns3::Buffer::Iterator::WriteU8().
SetDestination()
void ns3::Icmpv6Redirection::SetDestination (Ipv6Address destination)
Set the IPv6 destination address.
Parameters
destination IPv6 destination address
Definition at line 858 of file icmpv6-header.cc.
References m_destination, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::SendRedirection().
SetReserved()
void ns3::Icmpv6Redirection::SetReserved (uint32_t reserved)
Set the reserved field.
Parameters
reserved the reserved value
Definition at line 828 of file icmpv6-header.cc.
References m_reserved, and NS_LOG_FUNCTION.
Referenced by Deserialize().
SetTarget()
void ns3::Icmpv6Redirection::SetTarget (Ipv6Address target)
Set the IPv6 target address.
Parameters
target IPv6 target address
Definition at line 846 of file icmpv6-header.cc.
References m_target, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::SendRedirection().
Member Data Documentation
m_destination
Ipv6Address ns3::Icmpv6Redirection::m_destination private
IPv6 destination address.
Definition at line 931 of file icmpv6-header.h.
Referenced by Deserialize(), GetDestination(), Print(), Serialize(), and SetDestination().
m_reserved
uint32_t ns3::Icmpv6Redirection::m_reserved private
Reserved value.
Definition at line 936 of file icmpv6-header.h.
Referenced by GetReserved(), Serialize(), and SetReserved().
m_target
Ipv6Address ns3::Icmpv6Redirection::m_target private
IPv6 target address.
Definition at line 926 of file icmpv6-header.h.
Referenced by Deserialize(), GetTarget(), Print(), Serialize(), and SetTarget().
The documentation for this class was generated from the following files:
src/internet/model/icmpv6-header.h
src/internet/model/icmpv6-header.cc