ns-3: Ns3WimaxSimpleOFDMTestCase Class Reference
Ns3WimaxSimpleOFDMTestCase Class Reference
WiMAX Models » wimax module tests | Test suites
Ns3 Wimax Simple OFDM Test Case.
Public Member Functions
Ns3WimaxSimpleOFDMTestCase ()
virtual ~Ns3WimaxSimpleOFDMTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
bool DoRunOnce (double FrameDuration)
Run once function.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Ns3 Wimax Simple OFDM Test Case.
Definition at line 46 of file phy-test.cc.
Constructor & Destructor Documentation
Ns3WimaxSimpleOFDMTestCase()
Ns3WimaxSimpleOFDMTestCase::Ns3WimaxSimpleOFDMTestCase ()
Definition at line 63 of file phy-test.cc.
~Ns3WimaxSimpleOFDMTestCase()
Ns3WimaxSimpleOFDMTestCase::~Ns3WimaxSimpleOFDMTestCase () virtual
Definition at line 68 of file phy-test.cc.
Member Function Documentation
DoRun()
void Ns3WimaxSimpleOFDMTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 107 of file phy-test.cc.
References DoRunOnce(), and NS_LOG_DEBUG.
DoRunOnce()
bool Ns3WimaxSimpleOFDMTestCase::DoRunOnce (double FrameDuration) private
Run once function.
Parameters
FrameDuration the frame duration
Returns
true if successful
Definition at line 73 of file phy-test.cc.
References ns3::NodeContainer::Create(), ns3::NetDeviceContainer::Get(), ns3::WimaxHelper::Install(), ns3::SubscriberStationNetDevice::IsRegistered(), NS_LOG_DEBUG, and ns3::Seconds().
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/wimax/test/phy-test.cc