ns-3: ns3::SocketIpv6TclassTag Class Reference
ns3::SocketIpv6TclassTag Class Reference
indicates whether the socket has IPV6_TCLASS set.
#include "socket.h"
Public Member Functions
SocketIpv6TclassTag ()
virtual void Deserialize (TagBuffer i)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize (void) const
uint8_t GetTclass (void) const
Get the tag's Tclass.
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer i) const
void SetTclass (uint8_t tclass)
Set the tag's Tclass.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_ipv6Tclass
the Tclass carried by the tag
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
indicates whether the socket has IPV6_TCLASS set.
This tag is for IPv6 socket.
Definition at line 1354 of file socket.h.
Constructor & Destructor Documentation
SocketIpv6TclassTag()
ns3::SocketIpv6TclassTag::SocketIpv6TclassTag ()
Definition at line 895 of file socket.cc.
Member Function Documentation
Deserialize()
void ns3::SocketIpv6TclassTag::Deserialize (TagBuffer i) virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 941 of file socket.cc.
References m_ipv6Tclass, and ns3::TagBuffer::ReadU8().
GetInstanceTypeId()
TypeId ns3::SocketIpv6TclassTag::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 923 of file socket.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::SocketIpv6TclassTag::GetSerializedSize (void) const virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 929 of file socket.cc.
GetTclass()
uint8_t ns3::SocketIpv6TclassTag::GetTclass (void) const
Get the tag's Tclass.
Returns
the Tclass
Definition at line 906 of file socket.cc.
References m_ipv6Tclass.
Referenced by ReceivePacket(), and ns3::Ipv6L3Protocol::Send().
GetTypeId()
TypeId ns3::SocketIpv6TclassTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 912 of file socket.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::SocketIpv6TclassTag::Print (std::ostream & os) const virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 946 of file socket.cc.
References m_ipv6Tclass.
Serialize()
void ns3::SocketIpv6TclassTag::Serialize (TagBuffer i) const virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 935 of file socket.cc.
References m_ipv6Tclass, and ns3::TagBuffer::WriteU8().
SetTclass()
void ns3::SocketIpv6TclassTag::SetTclass (uint8_t tclass)
Set the tag's Tclass.
Parameters
tclass the Tclass
Definition at line 900 of file socket.cc.
References m_ipv6Tclass.
Referenced by ns3::TcpSocketBase::AddSocketTags(), ns3::UdpSocketImpl::DoSendTo(), ns3::Ipv6RawSocketImpl::ForwardUp(), ns3::UdpSocketImpl::ForwardUp6(), ns3::TcpSocketBase::PersistTimeout(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), and ns3::Ipv6RawSocketImpl::SendTo().
Member Data Documentation
m_ipv6Tclass
uint8_t ns3::SocketIpv6TclassTag::m_ipv6Tclass private
the Tclass carried by the tag
Definition at line 1394 of file socket.h.
Referenced by Deserialize(), GetTclass(), Print(), Serialize(), and SetTclass().
The documentation for this class was generated from the following files:
src/network/model/socket.h
src/network/model/socket.cc