ns-3: ns3::lorawan::LoraHelper Class Reference
ns3::lorawan::LoraHelper Class Reference
Helps to create LoraNetDevice objects.
#include "lora-helper.h"
Public Member Functions
LoraHelper ()
virtual ~LoraHelper ()
void DoPrintDeviceStatus (NodeContainer endDevices, NodeContainer gateways, std::string filename)
Print a summary of the status of all devices in the network.
void DoPrintGlobalPerformance (std::string filename)
void DoPrintPhyPerformance (NodeContainer gateways, std::string filename)
void EnablePacketTracking (void)
Enable tracking of packets via trace sources.
void EnablePeriodicDeviceStatusPrinting (NodeContainer endDevices, NodeContainer gateways, std::string filename, Time interval)
Periodically prints the status of devices in the network to a file.
void EnablePeriodicGlobalPerformancePrinting (std::string filename, Time interval)
Periodically prints global performance.
void EnablePeriodicPhyPerformancePrinting (NodeContainer gateways, std::string filename, Time interval)
Periodically prints PHY-level performance at every gateway in the container.
void EnableSimulationTimePrinting (Time interval)
Periodically prints the simulation time to the standard output.
LoraPacketTracker & GetPacketTracker (void)
virtual NetDeviceContainer Install (const LoraPhyHelper &phyHelper, const LorawanMacHelper &macHelper, NodeContainer c) const
Install LoraNetDevices on a list of nodes.
virtual NetDeviceContainer Install (const LoraPhyHelper &phyHelper, const LorawanMacHelper &macHelper, Ptr< Node > node) const
Install LoraNetDevice on a single node.
Public Attributes
time_t m_oldtime
LoraPacketTracker * m_packetTracker = 0
Private Member Functions
void DoPrintSimulationTime (Time interval)
Actually print the simulation time and re-schedule execution of this function.
Private Attributes
Time m_lastGlobalPerformanceUpdate
Time m_lastPhyPerformanceUpdate
Detailed Description
Helps to create LoraNetDevice objects.
This class can help create a large set of similar LoraNetDevice objects and configure a large set of their attributes during creation.
Definition at line 43 of file lora-helper.h.
Constructor & Destructor Documentation
~LoraHelper()
ns3::lorawan::LoraHelper::~LoraHelper () virtual
Definition at line 37 of file lora-helper.cc.
LoraHelper()
ns3::lorawan::LoraHelper::LoraHelper ()
Definition at line 31 of file lora-helper.cc.
Member Function Documentation
DoPrintDeviceStatus()
void ns3::lorawan::LoraHelper::DoPrintDeviceStatus (NodeContainer endDevices, NodeContainer gateways, std::string filename)
Print a summary of the status of all devices in the network.
Definition at line 199 of file lora-helper.cc.
References ns3::NodeContainer::Begin(), ns3::NodeContainer::End(), ns3::Object::GetObject(), ns3::MobilityModel::GetPosition(), ns3::Time::GetSeconds(), third::mac, ns3::Simulator::Now(), NS_ASSERT, and ns3::Seconds().
Referenced by EnablePeriodicDeviceStatusPrinting().
DoPrintGlobalPerformance()
void ns3::lorawan::LoraHelper::DoPrintGlobalPerformance (std::string filename)
Definition at line 310 of file lora-helper.cc.
References ns3::lorawan::LoraPacketTracker::CountMacPacketsGlobally(), ns3::Time::GetSeconds(), m_lastGlobalPerformanceUpdate, m_packetTracker, ns3::Simulator::Now(), NS_LOG_FUNCTION, and ns3::Seconds().
Referenced by EnablePeriodicGlobalPerformancePrinting().
DoPrintPhyPerformance()
void ns3::lorawan::LoraHelper::DoPrintPhyPerformance (NodeContainer gateways, std::string filename)
Definition at line 262 of file lora-helper.cc.
References ns3::NodeContainer::Begin(), ns3::NodeContainer::End(), ns3::Time::GetSeconds(), m_lastPhyPerformanceUpdate, m_packetTracker, ns3::Simulator::Now(), NS_LOG_FUNCTION, ns3::lorawan::LoraPacketTracker::PrintPhyPacketsPerGw(), and ns3::Seconds().
Referenced by EnablePeriodicPhyPerformancePrinting().
DoPrintSimulationTime()
void ns3::lorawan::LoraHelper::DoPrintSimulationTime (Time interval) private
Actually print the simulation time and re-schedule execution of this function.
Definition at line 338 of file lora-helper.cc.
References ns3::Time::GetHours(), m_oldtime, ns3::Simulator::Now(), and ns3::Simulator::Schedule().
Referenced by EnableSimulationTimePrinting().
EnablePacketTracking()
void ns3::lorawan::LoraHelper::EnablePacketTracking (void)
Enable tracking of packets via trace sources.
This method automatically connects to trace sources to computes relevant metrics.
Definition at line 158 of file lora-helper.cc.
References m_packetTracker, and NS_LOG_FUNCTION.
EnablePeriodicDeviceStatusPrinting()
void ns3::lorawan::LoraHelper::EnablePeriodicDeviceStatusPrinting (NodeContainer endDevices, NodeContainer gateways, std::string filename, Time interval)
Periodically prints the status of devices in the network to a file.
Definition at line 183 of file lora-helper.cc.
References DoPrintDeviceStatus(), NS_LOG_FUNCTION, and ns3::Simulator::Schedule().
EnablePeriodicGlobalPerformancePrinting()
void ns3::lorawan::LoraHelper::EnablePeriodicGlobalPerformancePrinting (std::string filename, Time interval)
Periodically prints global performance.
Definition at line 296 of file lora-helper.cc.
References DoPrintGlobalPerformance(), NS_LOG_FUNCTION, and ns3::Simulator::Schedule().
EnablePeriodicPhyPerformancePrinting()
void ns3::lorawan::LoraHelper::EnablePeriodicPhyPerformancePrinting (NodeContainer gateways, std::string filename, Time interval)
Periodically prints PHY-level performance at every gateway in the container.
Definition at line 247 of file lora-helper.cc.
References DoPrintPhyPerformance(), NS_LOG_FUNCTION, and ns3::Simulator::Schedule().
EnableSimulationTimePrinting()
void ns3::lorawan::LoraHelper::EnableSimulationTimePrinting (Time interval)
Periodically prints the simulation time to the standard output.
Definition at line 175 of file lora-helper.cc.
References DoPrintSimulationTime(), m_oldtime, ns3::Simulator::Schedule(), and ns3::Seconds().
GetPacketTracker()
LoraPacketTracker & ns3::lorawan::LoraHelper::GetPacketTracker (void)
Definition at line 167 of file lora-helper.cc.
References m_packetTracker, and NS_LOG_FUNCTION.
Install() [1/2]
NetDeviceContainer ns3::lorawan::LoraHelper::Install (const LoraPhyHelper & phyHelper, const LorawanMacHelper & macHelper, NodeContainer c) const virtual
Install LoraNetDevices on a list of nodes.
Parameters
phy the PHY helper to create PHY objects
mac the MAC helper to create MAC objects
c the set of nodes on which a lora device must be created
Returns
a device container which contains all the devices created by this method.
Definition at line 42 of file lora-helper.cc.
References ns3::Node::AddDevice(), ns3::NodeContainer::Begin(), ns3::lorawan::LoraPhyHelper::Create(), ns3::lorawan::LorawanMacHelper::Create(), first::devices, ns3::NodeContainer::End(), ns3::lorawan::LoraPhyHelper::GetDeviceType(), ns3::Object::GetObject(), ns3::MobilityModel::GetPosition(), ns3::lorawan::LoraPacketTracker::InterferenceCallback(), ns3::TypeId::LookupByName(), ns3::lorawan::LoraPacketTracker::LostBecauseTxCallback(), m_packetTracker, third::mac, ns3::lorawan::LoraPacketTracker::MacGwReceptionCallback(), ns3::lorawan::LoraPacketTracker::MacTransmissionCallback(), ns3::MakeCallback(), ns3::lorawan::LoraPacketTracker::NoMoreReceiversCallback(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION_NOARGS, ns3::lorawan::LoraPacketTracker::PacketReceptionCallback(), third::phy, ns3::lorawan::LoraPacketTracker::RequiredTransmissionsCallback(), ns3::lorawan::LoraPacketTracker::TransmissionCallback(), and ns3::lorawan::LoraPacketTracker::UnderSensitivityCallback().
Referenced by ns3::lorawan::CreateEndDevices(), ns3::lorawan::CreateGateways(), and Install().
Install() [2/2]
NetDeviceContainer ns3::lorawan::LoraHelper::Install (const LoraPhyHelper & phyHelper, const LorawanMacHelper & macHelper, Ptr< Node > node) const virtual
Install LoraNetDevice on a single node.
Parameters
phy the PHY helper to create PHY objects
mac the MAC helper to create MAC objects
node the node on which a lora device must be created
Returns
a device container which contains all the devices created by this method.
Definition at line 150 of file lora-helper.cc.
References Install(), third::mac, and third::phy.
Member Data Documentation
m_lastGlobalPerformanceUpdate
Time ns3::lorawan::LoraHelper::m_lastGlobalPerformanceUpdate private
Definition at line 134 of file lora-helper.h.
Referenced by DoPrintGlobalPerformance().
m_lastPhyPerformanceUpdate
Time ns3::lorawan::LoraHelper::m_lastPhyPerformanceUpdate private
Definition at line 133 of file lora-helper.h.
Referenced by DoPrintPhyPerformance().
m_oldtime
time_t ns3::lorawan::LoraHelper::m_oldtime
Definition at line 118 of file lora-helper.h.
Referenced by DoPrintSimulationTime(), and EnableSimulationTimePrinting().
m_packetTracker
LoraPacketTracker* ns3::lorawan::LoraHelper::m_packetTracker = 0
Definition at line 116 of file lora-helper.h.
Referenced by DoPrintGlobalPerformance(), DoPrintPhyPerformance(), EnablePacketTracking(), GetPacketTracker(), and Install().
The documentation for this class was generated from the following files:
src/lorawan/helper/lora-helper.h
src/lorawan/helper/lora-helper.cc