ns-3: ns3::BuildingListPriv Class Reference
ns3::BuildingListPriv Class Reference
private implementation detail of the BuildingList API.
Public Member Functions
BuildingListPriv ()
~BuildingListPriv ()
uint32_t Add (Ptr< Building > building)
BuildingList::Iterator Begin (void) const
BuildingList::Iterator End (void) const
Ptr< Building > GetBuilding (uint32_t n)
uint32_t GetNBuildings (void)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static Ptr< BuildingListPriv > Get (void)
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual void DoDispose (void)
Destructor implementation.
Static Private Member Functions
static void Delete (void)
static Ptr< BuildingListPriv > * DoGet (void)
Private Attributes
std::vector< Ptr< Building > > m_buildings
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
private implementation detail of the BuildingList API.
Definition at line 38 of file building-list.cc.
Constructor & Destructor Documentation
BuildingListPriv()
ns3::BuildingListPriv::BuildingListPriv ()
Definition at line 102 of file building-list.cc.
References NS_LOG_FUNCTION_NOARGS.
~BuildingListPriv()
ns3::BuildingListPriv::~BuildingListPriv ()
Definition at line 106 of file building-list.cc.
Member Function Documentation
Add()
uint32_t ns3::BuildingListPriv::Add (Ptr< Building > building)
Definition at line 126 of file building-list.cc.
References ns3::Object::Initialize(), m_buildings, ns3::Simulator::ScheduleWithContext(), and ns3::TimeStep().
Begin()
BuildingList::Iterator ns3::BuildingListPriv::Begin (void) const
Definition at line 135 of file building-list.cc.
References m_buildings.
Delete()
void ns3::BuildingListPriv::Delete (void) static private
Definition at line 94 of file building-list.cc.
References DoGet(), Get(), NS_LOG_FUNCTION_NOARGS, and ns3::Config::UnregisterRootNamespaceObject().
Referenced by DoGet().
DoDispose()
void ns3::BuildingListPriv::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 110 of file building-list.cc.
References ns3::Object::DoDispose(), m_buildings, and NS_LOG_FUNCTION_NOARGS.
DoGet()
Ptr< BuildingListPriv > * ns3::BuildingListPriv::DoGet (void) static private
Definition at line 82 of file building-list.cc.
References Delete(), ns3::Config::RegisterRootNamespaceObject(), and ns3::Simulator::ScheduleDestroy().
Referenced by Delete(), and Get().
End()
BuildingList::Iterator ns3::BuildingListPriv::End (void) const
Definition at line 140 of file building-list.cc.
References m_buildings.
Get()
Ptr< BuildingListPriv > ns3::BuildingListPriv::Get (void) static
Definition at line 77 of file building-list.cc.
References DoGet().
Referenced by ns3::BuildingList::Add(), ns3::BuildingList::Begin(), Delete(), ns3::BuildingList::End(), ns3::BuildingList::GetBuilding(), and ns3::BuildingList::GetNBuildings().
GetBuilding()
Ptr< Building > ns3::BuildingListPriv::GetBuilding (uint32_t n)
Definition at line 151 of file building-list.cc.
References m_buildings, sample-rng-plot::n, and NS_ASSERT_MSG().
GetNBuildings()
uint32_t ns3::BuildingListPriv::GetNBuildings (void)
Definition at line 145 of file building-list.cc.
References m_buildings.
GetTypeId()
TypeId ns3::BuildingListPriv::GetTypeId (void) static
Definition at line 63 of file building-list.cc.
References m_buildings, ns3::MakeObjectVectorAccessor(), and ns3::TypeId::SetParent().
Member Data Documentation
m_buildings
std::vector<Ptr<Building> > ns3::BuildingListPriv::m_buildings private
Definition at line 57 of file building-list.cc.
Referenced by Add(), Begin(), DoDispose(), End(), GetBuilding(), GetNBuildings(), and GetTypeId().
The documentation for this class was generated from the following file:
src/buildings/model/building-list.cc