ns-3: ns3::ChannelManager Class Reference
ns3::ChannelManager Class Reference
WAVE module
manage 7 WaveChannels and the tx information such as data rate and txPowerLevel. for transmitting VSA management frames.
#include "channel-manager.h"
Classes
struct WaveChannel
WaveChannel structure.
Public Member Functions
ChannelManager ()
virtual ~ChannelManager ()
bool GetManagementAdaptable (uint32_t channelNumber)
WifiMode GetManagementDataRate (uint32_t channelNumber)
uint32_t GetManagementPowerLevel (uint32_t channelNumber)
WifiPreamble GetManagementPreamble (uint32_t channelNumber)
uint32_t GetOperatingClass (uint32_t channelNumber)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static uint32_t GetCch (void)
static uint32_t GetNumberOfWaveChannels (void)
static std::vector< uint32_t > GetSchs (void)
static TypeId GetTypeId (void)
Get the type ID.
static std::vector< uint32_t > GetWaveChannels (void)
static bool IsCch (uint32_t channelNumber)
static bool IsSch (uint32_t channelNumber)
static bool IsWaveChannel (uint32_t channelNumber)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
std::map< uint32_t, WaveChannel * > m_channels
list of channels
Static Private Attributes
static const uint32_t DEFAULT_OPERATING_CLASS = 17
1609.4-2010 Annex H
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
manage 7 WaveChannels and the tx information such as data rate and txPowerLevel. for transmitting VSA management frames.
Definition at line 62 of file channel-manager.h.
Constructor & Destructor Documentation
ChannelManager()
ns3::ChannelManager::ChannelManager ()
Definition at line 39 of file channel-manager.cc.
References CCH, m_channels, NS_LOG_FUNCTION, SCH1, SCH2, SCH3, SCH4, SCH5, and SCH6.
~ChannelManager()
ns3::ChannelManager::~ChannelManager () virtual
Definition at line 51 of file channel-manager.cc.
References m_channels, and NS_LOG_FUNCTION.
Member Function Documentation
GetCch()
uint32_t ns3::ChannelManager::GetCch (void) static
Returns
the channel number of WAVE CCH.
Definition at line 63 of file channel-manager.cc.
References CCH, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::WaveHelper::Install().
GetManagementAdaptable()
bool ns3::ChannelManager::GetManagementAdaptable (uint32_t channelNumber)
Parameters
channelNumber the specific channel
Returns
the adaptable mode for management frames
Definition at line 151 of file channel-manager.cc.
References m_channels, and NS_LOG_FUNCTION.
GetManagementDataRate()
WifiMode ns3::ChannelManager::GetManagementDataRate (uint32_t channelNumber)
Parameters
channelNumber the specific channel
Returns
the data rate for management frames
Definition at line 158 of file channel-manager.cc.
References m_channels, and NS_LOG_FUNCTION.
GetManagementPowerLevel()
uint32_t ns3::ChannelManager::GetManagementPowerLevel (uint32_t channelNumber)
Parameters
channelNumber the specific channel
Returns
the tx power level for management frames
Definition at line 172 of file channel-manager.cc.
References m_channels, and NS_LOG_FUNCTION.
GetManagementPreamble()
WifiPreamble ns3::ChannelManager::GetManagementPreamble (uint32_t channelNumber)
Parameters
channelNumber the specific channel
Returns
the preamble for management frames
Definition at line 165 of file channel-manager.cc.
References m_channels, and NS_LOG_FUNCTION.
GetNumberOfWaveChannels()
uint32_t ns3::ChannelManager::GetNumberOfWaveChannels (void) static
Returns
the number of WAVE channels.
Definition at line 99 of file channel-manager.cc.
References GetWaveChannels(), and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::WaveHelper::CreatePhys().
GetOperatingClass()
uint32_t ns3::ChannelManager::GetOperatingClass (uint32_t channelNumber)
Parameters
channelNumber the specific channel
Returns
the operating class on this channel
the operating class is unused in the simulation
Definition at line 144 of file channel-manager.cc.
References m_channels, and NS_LOG_FUNCTION.
GetSchs()
std::vector< uint32_t > ns3::ChannelManager::GetSchs (void) static
Returns
the channel number set of WAVE SCHs.
Definition at line 70 of file channel-manager.cc.
References NS_LOG_FUNCTION_NOARGS, SCH1, SCH2, SCH3, SCH4, SCH5, and SCH6.
GetTypeId()
TypeId ns3::ChannelManager::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 29 of file channel-manager.cc.
References ns3::TypeId::SetParent().
GetWaveChannels()
std::vector< uint32_t > ns3::ChannelManager::GetWaveChannels (void) static
Returns
the channel number set of WAVE channels.
The sequence is CCH, SCH1, SCH2, SCH3, SCH4, SCH5 and SCH6.
Definition at line 84 of file channel-manager.cc.
References CCH, NS_LOG_FUNCTION_NOARGS, SCH1, SCH2, SCH3, SCH4, SCH5, and SCH6.
Referenced by ns3::WaveHelper::Default(), and GetNumberOfWaveChannels().
IsCch()
bool ns3::ChannelManager::IsCch (uint32_t channelNumber) static
Parameters
channelNumber the specific channel
Returns
whether channel is valid CCH channel
Definition at line 107 of file channel-manager.cc.
References CCH, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::ChannelScheduler::StartSch(), and ns3::ChannelScheduler::StopSch().
IsSch()
bool ns3::ChannelManager::IsSch (uint32_t channelNumber) static
Parameters
channelNumber the specific channel
Returns
whether channel is valid SCH channel
Definition at line 114 of file channel-manager.cc.
References CCH, NS_LOG_FUNCTION_NOARGS, and SCH6.
IsWaveChannel()
bool ns3::ChannelManager::IsWaveChannel (uint32_t channelNumber) static
Parameters
channelNumber the specific channel
Returns
whether channel is valid WAVE channel
Definition at line 129 of file channel-manager.cc.
References NS_LOG_FUNCTION_NOARGS, and SCH6.
Referenced by ns3::WaveNetDevice::AddMac(), ns3::WaveHelper::CreateMacForChannel(), and ns3::WaveNetDevice::IsAvailableChannel().
Member Data Documentation
DEFAULT_OPERATING_CLASS
const uint32_t ns3::ChannelManager::DEFAULT_OPERATING_CLASS = 17 static private
1609.4-2010 Annex H
Definition at line 137 of file channel-manager.h.
m_channels
std::map<uint32_t, WaveChannel *> ns3::ChannelManager::m_channels private
list of channels
Definition at line 163 of file channel-manager.h.
Referenced by ChannelManager(), ~ChannelManager(), GetManagementAdaptable(), GetManagementDataRate(), GetManagementPowerLevel(), GetManagementPreamble(), and GetOperatingClass().
The documentation for this class was generated from the following files:
src/wave/model/channel-manager.h
src/wave/model/channel-manager.cc