ns-3: ns3::HierarchicalMobilityModel Class Reference
ns3::HierarchicalMobilityModel Class Reference
Mobility
Hierarchical mobility model.
#include "hierarchical-mobility-model.h"
Public Member Functions
HierarchicalMobilityModel ()
Ptr< MobilityModel > GetChild (void) const
Ptr< MobilityModel > GetParent (void) const
void SetChild (Ptr< MobilityModel > model)
Sets the child mobility model to a new one.
void SetParent (Ptr< MobilityModel > model)
Sets the parent mobility model to a new one.
Public Member Functions inherited from ns3::MobilityModel
MobilityModel ()
virtual ~MobilityModel ()=0
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
double GetDistanceFrom (Ptr< const MobilityModel > position) const
Vector GetPosition (void) const
double GetRelativeSpeed (Ptr< const MobilityModel > other) const
Vector GetVelocity (void) const
void SetPosition (const Vector &position)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type with the TypeId system.
Static Public Member Functions inherited from ns3::MobilityModel
static TypeId GetTypeId (void)
Register this type with the TypeId system.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void ChildChanged (Ptr< const MobilityModel > model)
Callback for when child mobility model course change occurs.
virtual Vector DoGetPosition (void) const
virtual Vector DoGetVelocity (void) const
virtual void DoSetPosition (const Vector &position)
void ParentChanged (Ptr< const MobilityModel > model)
Callback for when parent mobility model course change occurs.
Private Attributes
Ptr< MobilityModel > m_child
pointer to child mobility model
Ptr< MobilityModel > m_parent
pointer to parent mobility model
Additional Inherited Members
Public Types inherited from ns3::MobilityModel
typedef void(* TracedCallback) (Ptr< const MobilityModel > model)
TracedCallback signature.
Protected Member Functions inherited from ns3::MobilityModel
void NotifyCourseChange (void) const
Must be invoked by subclasses when the course of the position changes to notify course change listeners.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Hierarchical mobility model.
This model allows you to specify the position of a child object relative to a parent object.
Basically this is a mobility model that combines two other mobility models: a "parent" model and a "child" model. The position of the hierarchical model is always the vector sum of the parent + child positions, so that if the parent model "moves", then this model will report an equal relative movement. Useful, for instance, if you want to simulate a node inside another node that moves, such as a vehicle.
Setting the position on this model is always done using world absolute coordinates, and it changes only the child mobility model position, never the parent. The child mobility model always uses a coordinate system relative to the parent model position.
Note
: as a special case, the parent model may be NULL, which is semantically equivalent to having a ConstantPositionMobilityModel as parent positioned at origin (0,0,0). In other words, setting the parent model to NULL makes the child model and the hierarchical model start using world absolute coordinates.
Warning
: changing the parent/child mobility models in the middle of a simulation will probably not play very well with the ConfigStore APIs, so do this only if you know what you are doing.
Definition at line 57 of file hierarchical-mobility-model.h.
Constructor & Destructor Documentation
HierarchicalMobilityModel()
ns3::HierarchicalMobilityModel::HierarchicalMobilityModel ()
Definition at line 48 of file hierarchical-mobility-model.cc.
Member Function Documentation
ChildChanged()
void ns3::HierarchicalMobilityModel::ChildChanged (Ptr< const MobilityModel > model) private
Callback for when child mobility model course change occurs.
Definition at line 172 of file hierarchical-mobility-model.cc.
References ns3::MobilityModel::NotifyCourseChange().
Referenced by SetChild().
DoGetPosition()
Vector ns3::HierarchicalMobilityModel::DoGetPosition (void) const private virtual
Returns
the current position.
Concrete subclasses of this base class must implement this method.
Implements ns3::MobilityModel.
Definition at line 113 of file hierarchical-mobility-model.cc.
References ns3::MobilityModel::GetPosition(), m_child, and m_parent.
DoGetVelocity()
Vector ns3::HierarchicalMobilityModel::DoGetVelocity (void) const private virtual
Returns
the current velocity.
Concrete subclasses of this base class must implement this method.
Implements ns3::MobilityModel.
Definition at line 148 of file hierarchical-mobility-model.cc.
References ns3::MobilityModel::GetVelocity(), m_child, and m_parent.
DoSetPosition()
void ns3::HierarchicalMobilityModel::DoSetPosition (const Vector & position) private virtual
Parameters
position the position to set.
Concrete subclasses of this base class must implement this method.
Implements ns3::MobilityModel.
Definition at line 126 of file hierarchical-mobility-model.cc.
References ns3::MobilityModel::GetPosition(), m_child, m_parent, and ns3::MobilityModel::SetPosition().
GetChild()
Ptr< MobilityModel > ns3::HierarchicalMobilityModel::GetChild (void) const
Returns
the child mobility model.
This allows you to get access to the position of the child relative to its parent.
Definition at line 101 of file hierarchical-mobility-model.cc.
References m_child.
Referenced by GetTypeId().
GetParent()
Ptr< MobilityModel > ns3::HierarchicalMobilityModel::GetParent (void) const
Returns
the parent mobility model.
This allows you to get access to the position of the parent mobility model which is used as the reference position by the child mobility model.
Definition at line 107 of file hierarchical-mobility-model.cc.
References m_parent.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::HierarchicalMobilityModel::GetTypeId (void) static
Register this type with the TypeId system.
Returns
the object TypeId
Definition at line 28 of file hierarchical-mobility-model.cc.
References GetChild(), GetParent(), ns3::MakePointerAccessor(), SetChild(), SetParent(), and ns3::TypeId::SetParent().
ParentChanged()
void ns3::HierarchicalMobilityModel::ParentChanged (Ptr< const MobilityModel > model) private
Callback for when parent mobility model course change occurs.
Definition at line 166 of file hierarchical-mobility-model.cc.
References ns3::MobilityModel::NotifyCourseChange().
Referenced by SetParent().
SetChild()
void ns3::HierarchicalMobilityModel::SetChild (Ptr< MobilityModel > model)
Sets the child mobility model to a new one.
If before there already existed a child model, then the child mobility model current position is also modified to ensure that the composite position is preserved.
Parameters
model new mobility model child
Definition at line 55 of file hierarchical-mobility-model.cc.
References ChildChanged(), ns3::MobilityModel::GetPosition(), m_child, ns3::MakeCallback(), ns3::MobilityModel::SetPosition(), ns3::ObjectBase::TraceConnectWithoutContext(), and ns3::ObjectBase::TraceDisconnectWithoutContext().
Referenced by GetTypeId().
SetParent()
void ns3::HierarchicalMobilityModel::SetParent (Ptr< MobilityModel > model)
Sets the parent mobility model to a new one.
If before there already existed a child model, then the child mobility model current position is also modified to ensure that the composite position is preserved.
Parameters
model new mobility model parent
Definition at line 76 of file hierarchical-mobility-model.cc.
References ns3::MobilityModel::GetPosition(), m_child, m_parent, ns3::MakeCallback(), ParentChanged(), ns3::MobilityModel::SetPosition(), ns3::ObjectBase::TraceConnectWithoutContext(), and ns3::ObjectBase::TraceDisconnectWithoutContext().
Referenced by GetTypeId().
Member Data Documentation
m_child
Ptr<MobilityModel> ns3::HierarchicalMobilityModel::m_child private
pointer to child mobility model
Definition at line 114 of file hierarchical-mobility-model.h.
Referenced by DoGetPosition(), DoGetVelocity(), DoSetPosition(), GetChild(), SetChild(), and SetParent().
m_parent
Ptr<MobilityModel> ns3::HierarchicalMobilityModel::m_parent private
pointer to parent mobility model
Definition at line 115 of file hierarchical-mobility-model.h.
Referenced by DoGetPosition(), DoGetVelocity(), DoSetPosition(), GetParent(), and SetParent().
The documentation for this class was generated from the following files:
src/mobility/model/hierarchical-mobility-model.h
src/mobility/model/hierarchical-mobility-model.cc