ns-3: ns3::UanNetDevice Class Reference
ns3::UanNetDevice Class Reference
UAN Models
#include "uan-net-device.h"
Public Types
typedef void(* RxTxTracedCallback) (Ptr< const Packet > packet, Mac8Address address)
TracedCallback signature for MAC send/receive events.
typedef std::list< Ptr< UanPhy > > UanPhyList
List of UanPhy objects.
typedef std::list< Ptr< UanTransducer > > UanTransducerList
List of UanTransducer objects.
Public Types inherited from ns3::NetDevice
typedef void(* LinkChangeTracedCallback) (void)
TracedCallback signature for link changed event.
enum PacketType {
PACKET_HOST = 1, NS3_PACKET_HOST = PACKET_HOST, PACKET_BROADCAST, NS3_PACKET_BROADCAST = PACKET_BROADCAST,
PACKET_MULTICAST, NS3_PACKET_MULTICAST = PACKET_MULTICAST, PACKET_OTHERHOST, NS3_PACKET_OTHERHOST = PACKET_OTHERHOST
}
Packet types are used as they are in Linux.
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address &, const Address &, enum PacketType > PromiscReceiveCallback
typedef Callback< bool, Ptr< NetDevice >, Ptr< const Packet >, uint16_t, const Address & > ReceiveCallback
Public Member Functions
UanNetDevice ()
Default constructor.
virtual ~UanNetDevice ()
Dummy destructor, DoDispose.
virtual void AddLinkChangeCallback (Callback< void > callback)
void Clear (void)
Clear all pointer references.
virtual Address GetAddress (void) const
virtual Address GetBroadcast (void) const
virtual Ptr< Channel > GetChannel (void) const
virtual uint32_t GetIfIndex (void) const
Ptr< UanMac > GetMac (void) const
Get the MAC used by this device.
virtual uint16_t GetMtu (void) const
virtual Address GetMulticast (Ipv4Address multicastGroup) const
Make and return a MAC multicast address using the provided multicast group.
virtual Address GetMulticast (Ipv6Address addr) const
Get the MAC multicast address corresponding to the IPv6 address provided.
virtual Ptr< Node > GetNode (void) const
Ptr< UanPhy > GetPhy (void) const
Get the Phy used by this device.
Ptr< UanTransducer > GetTransducer (void) const
Get the transducer associated with this device.
uint32_t GetTxModeIndex ()
virtual bool IsBridge (void) const
Return true if the net device is acting as a bridge.
virtual bool IsBroadcast (void) const
virtual bool IsLinkUp (void) const
virtual bool IsMulticast (void) const
virtual bool IsPointToPoint (void) const
Return true if the net device is on a point-to-point link.
virtual bool NeedsArp (void) const
virtual bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)
virtual bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
virtual void SetAddress (Address address)
Set the address of this interface.
void SetChannel (Ptr< UanChannel > channel)
Attach a channel.
virtual void SetIfIndex (const uint32_t index)
void SetMac (Ptr< UanMac > mac)
Set the MAC layer for this device.
virtual bool SetMtu (const uint16_t mtu)
virtual void SetNode (Ptr< Node > node)
void SetPhy (Ptr< UanPhy > phy)
Set the Phy layer for this device.
virtual void SetPromiscReceiveCallback (PromiscReceiveCallback cb)
virtual void SetReceiveCallback (NetDevice::ReceiveCallback cb)
void SetSleepMode (bool sleep)
Set the Phy SLEEP mode.
void SetTransducer (Ptr< UanTransducer > trans)
Set the transdcuer used by this device.
void SetTxModeIndex (uint32_t txModeIndex)
virtual bool SupportsSendFrom (void) const
Public Member Functions inherited from ns3::NetDevice
virtual ~NetDevice ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::NetDevice
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
Ptr< UanChannel > DoGetChannel (void) const
virtual void ForwardUp (Ptr< Packet > pkt, uint16_t protocolNumber, const Mac8Address &src)
Forward the packet to a higher level, set with SetReceiveCallback.
Private Attributes
Ptr< UanChannel > m_channel
The channel attached to this device.
bool m_cleared
Flag when we've been cleared.
ReceiveCallback m_forwardUp
The receive callback.
uint32_t m_ifIndex
The interface index of this device.
TracedCallback m_linkChanges
Callback to invoke when the link state changes to UP.
bool m_linkup
The link state, true if up.
Ptr< UanMac > m_mac
The MAC layer attached to this device.
uint16_t m_mtu
The device MTU value, in bytes.
Ptr< Node > m_node
The node hosting this device.
Ptr< UanPhy > m_phy
The PHY layer attached to this device.
TracedCallback< Ptr< const Packet >, Mac8Address > m_rxLogger
Trace source triggered when forwarding up received payload from the MAC layer.
Ptr< UanTransducer > m_trans
The Transducer attached to this device.
TracedCallback< Ptr< const Packet >, Mac8Address > m_txLogger
Trace source triggered when sending to the MAC layer.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Net device for UAN models.
Definition at line 47 of file uan-net-device.h.
Member Typedef Documentation
RxTxTracedCallback
typedef void(* ns3::UanNetDevice::RxTxTracedCallback) (Ptr< const Packet > packet, Mac8Address address)
TracedCallback signature for MAC send/receive events.
Parameters
[in] packet The Packet.
[in] address The source address.
Definition at line 158 of file uan-net-device.h.
UanPhyList
typedef std::list<Ptr<UanPhy> > ns3::UanNetDevice::UanPhyList
List of UanPhy objects.
Definition at line 51 of file uan-net-device.h.
UanTransducerList
typedef std::list<Ptr<UanTransducer> > ns3::UanNetDevice::UanTransducerList
List of UanTransducer objects.
Definition at line 53 of file uan-net-device.h.
Constructor & Destructor Documentation
UanNetDevice()
ns3::UanNetDevice::UanNetDevice ()
Default constructor.
Definition at line 39 of file uan-net-device.cc.
~UanNetDevice()
ns3::UanNetDevice::~UanNetDevice () virtual
Dummy destructor, DoDispose.
Definition at line 46 of file uan-net-device.cc.
Member Function Documentation
AddLinkChangeCallback()
void ns3::UanNetDevice::AddLinkChangeCallback (Callback< void > callback) virtual
Parameters
callback the callback to invoke
Add a callback invoked whenever the link status changes to UP. This callback is typically used by the IP/ARP layer to flush the ARP cache and by IPv6 stack to flush NDISC cache whenever the link goes up.
Implements ns3::NetDevice.
Definition at line 384 of file uan-net-device.cc.
References ns3::TracedCallback< T1, T2, T3, T4, T5, T6, T7, T8 >::ConnectWithoutContext(), and m_linkChanges.
Clear()
void ns3::UanNetDevice::Clear (void)
Clear all pointer references.
Definition at line 51 of file uan-net-device.cc.
References m_channel, m_cleared, m_mac, m_node, m_phy, and m_trans.
Referenced by DoDispose().
DoDispose()
void ns3::UanNetDevice::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 93 of file uan-net-device.cc.
References Clear(), and ns3::Object::DoDispose().
DoGetChannel()
Ptr< UanChannel > ns3::UanNetDevice::DoGetChannel (void) const private
Returns
The channel attached to this device.
Definition at line 197 of file uan-net-device.cc.
References m_channel.
Referenced by GetTypeId().
DoInitialize()
void ns3::UanNetDevice::DoInitialize (void) protected virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 82 of file uan-net-device.cc.
References ns3::Object::DoInitialize(), m_channel, m_mac, m_phy, and m_trans.
ForwardUp()
void ns3::UanNetDevice::ForwardUp (Ptr< Packet > pkt, uint16_t protocolNumber, const Mac8Address & src) private virtual
Forward the packet to a higher level, set with SetReceiveCallback.
Parameters
pkt The packet.
src The source address.
protocolNumber The layer 3 protocol number.
Definition at line 346 of file uan-net-device.cc.
References m_forwardUp, m_rxLogger, and NS_LOG_DEBUG.
Referenced by SetMac().
GetAddress()
Address ns3::UanNetDevice::GetAddress (void) const virtual
Returns
the current Address of this interface.
Implements ns3::NetDevice.
Definition at line 233 of file uan-net-device.cc.
References m_mac.
GetBroadcast()
Address ns3::UanNetDevice::GetBroadcast (void) const virtual
Returns
the broadcast address supported by this netdevice.
Calling this method is invalid if IsBroadcast returns not true.
Implements ns3::NetDevice.
Definition at line 266 of file uan-net-device.cc.
References m_mac.
Referenced by AcousticModemEnergyTestCase::SendOnePacket(), AcousticModemEnergyDepletionTestCase::SendOnePacket(), and UanTest::SendOnePacket().
GetChannel()
Ptr< Channel > ns3::UanNetDevice::GetChannel (void) const virtual
Returns
the channel this NetDevice is connected to. The value returned can be zero if the NetDevice is not yet connected to any channel or if the underlying NetDevice has no concept of a channel. i.e., callers must check for zero and be ready to handle it.
Implements ns3::NetDevice.
Definition at line 227 of file uan-net-device.cc.
References m_channel.
GetIfIndex()
uint32_t ns3::UanNetDevice::GetIfIndex (void) const virtual
Returns
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 221 of file uan-net-device.cc.
References m_ifIndex.
GetMac()
Ptr< UanMac > ns3::UanNetDevice::GetMac (void) const
Get the MAC used by this device.
Returns
The MAC.
Definition at line 203 of file uan-net-device.cc.
References m_mac.
Referenced by GetTypeId().
GetMtu()
uint16_t ns3::UanNetDevice::GetMtu (void) const virtual
Returns
the link-level MTU in bytes for this interface.
This value is typically used by the IP layer to perform IP fragmentation when needed.
Implements ns3::NetDevice.
Definition at line 248 of file uan-net-device.cc.
References m_mtu.
GetMulticast() [1/2]
Address ns3::UanNetDevice::GetMulticast (Ipv4Address multicastGroup) const virtual
Make and return a MAC multicast address using the provided multicast group.
RFC 1112 says that an Ipv4 host group address is mapped to an Ethernet multicast address by placing the low-order 23-bits of the IP address into the low-order 23 bits of the Ethernet multicast address 01-00-5E-00-00-00 (hex). Similar RFCs exist for Ipv6 and Eui64 mappings. This method performs the multicast address creation function appropriate to the underlying MAC address of the device. This MAC address is encapsulated in an abstract Address to avoid dependencies on the exact MAC address format.
In the case of net devices that do not support multicast, clients are expected to test NetDevice::IsMulticast and avoid attempting to map multicast packets. Subclasses of NetDevice that do support multicasting are expected to override this method and provide an implementation appropriate to the particular device.
Parameters
multicastGroup The IP address for the multicast group destination of the packet.
Returns
The MAC multicast Address used to send packets to the provided multicast group.
Warning
Calling this method is invalid if IsMulticast returns not true.
See also
IsMulticast()
Implements ns3::NetDevice.
Definition at line 278 of file uan-net-device.cc.
References m_mac, and NS_UNUSED.
GetMulticast() [2/2]
Address ns3::UanNetDevice::GetMulticast (Ipv6Address addr) const virtual
Get the MAC multicast address corresponding to the IPv6 address provided.
Parameters
addr IPv6 address
Returns
the MAC multicast address
Warning
Calling this method is invalid if IsMulticast returns not true.
Implements ns3::NetDevice.
Definition at line 285 of file uan-net-device.cc.
References m_mac.
GetNode()
Ptr< Node > ns3::UanNetDevice::GetNode (void) const virtual
Returns
the node base class which contains this network interface.
When a subclass needs to get access to the underlying node base class to print the nodeid for example, it can invoke this method.
Implements ns3::NetDevice.
Definition at line 322 of file uan-net-device.cc.
References m_node.
GetPhy()
Ptr< UanPhy > ns3::UanNetDevice::GetPhy (void) const
Get the Phy used by this device.
Returns
The Phy.
Definition at line 209 of file uan-net-device.cc.
References m_phy.
Referenced by AcousticModemEnergyTestCase::DoRun(), and GetTypeId().
GetTransducer()
Ptr< UanTransducer > ns3::UanNetDevice::GetTransducer (void) const
Get the transducer associated with this device.
Returns
The transducer.
Definition at line 355 of file uan-net-device.cc.
References m_trans.
Referenced by GetTypeId().
GetTxModeIndex()
uint32_t ns3::UanNetDevice::GetTxModeIndex ()
Definition at line 423 of file uan-net-device.cc.
References m_mac.
GetTypeId()
TypeId ns3::UanNetDevice::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 100 of file uan-net-device.cc.
References DoGetChannel(), GetMac(), GetPhy(), GetTransducer(), m_rxLogger, m_txLogger, ns3::MakePointerAccessor(), ns3::MakeTraceSourceAccessor(), SetChannel(), SetMac(), ns3::TypeId::SetParent(), SetPhy(), and SetTransducer().
IsBridge()
bool ns3::UanNetDevice::IsBridge (void) const virtual
Return true if the net device is acting as a bridge.
Returns
value of m_isBridge flag
Implements ns3::NetDevice.
Definition at line 291 of file uan-net-device.cc.
IsBroadcast()
bool ns3::UanNetDevice::IsBroadcast (void) const virtual
Returns
true if this interface supports a broadcast address, false otherwise.
Implements ns3::NetDevice.
Definition at line 260 of file uan-net-device.cc.
IsLinkUp()
bool ns3::UanNetDevice::IsLinkUp (void) const virtual
Returns
true if link is up; false otherwise
Implements ns3::NetDevice.
Definition at line 254 of file uan-net-device.cc.
References m_linkup, and m_phy.
IsMulticast()
bool ns3::UanNetDevice::IsMulticast (void) const virtual
Returns
value of m_isMulticast flag
Implements ns3::NetDevice.
Definition at line 272 of file uan-net-device.cc.
IsPointToPoint()
bool ns3::UanNetDevice::IsPointToPoint (void) const virtual
Return true if the net device is on a point-to-point link.
Returns
value of m_isPointToPoint flag
Implements ns3::NetDevice.
Definition at line 296 of file uan-net-device.cc.
NeedsArp()
bool ns3::UanNetDevice::NeedsArp (void) const virtual
Returns
true if ARP is needed, false otherwise.
Called by higher-layers to check if this NetDevice requires ARP to be used.
Implements ns3::NetDevice.
Definition at line 334 of file uan-net-device.cc.
Send()
bool ns3::UanNetDevice::Send (Ptr< Packet > packet, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device to the specified destination Address
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 302 of file uan-net-device.cc.
References ns3::Address::CopyTo(), and m_mac.
Referenced by AcousticModemEnergyTestCase::SendOnePacket(), AcousticModemEnergyDepletionTestCase::SendOnePacket(), and UanTest::SendOnePacket().
SendFrom()
bool ns3::UanNetDevice::SendFrom (Ptr< Packet > packet, const Address & source, const Address & dest, uint16_t protocolNumber) virtual
Parameters
packet packet sent from above down to Network Device
source source mac address (so called "MAC spoofing")
dest mac address of the destination (already resolved)
protocolNumber identifies the type of payload contained in this packet. Used to call the right L3Protocol when the packet is received.
Called from higher layer to send packet into Network Device with the specified source and destination Addresses.
Returns
whether the Send operation succeeded
Implements ns3::NetDevice.
Definition at line 312 of file uan-net-device.cc.
References NS_ASSERT_MSG(), and NS_UNUSED.
SetAddress()
void ns3::UanNetDevice::SetAddress (Address address) virtual
Set the address of this interface.
Parameters
address address to set
Implements ns3::NetDevice.
Definition at line 404 of file uan-net-device.cc.
References first::address, ns3::Mac8Address::ConvertFrom(), m_mac, and NS_ASSERT_MSG().
SetChannel()
void ns3::UanNetDevice::SetChannel (Ptr< UanChannel > channel)
Attach a channel.
Parameters
channel The channel.
Definition at line 175 of file uan-net-device.cc.
References third::channel, m_channel, m_phy, m_trans, and NS_LOG_DEBUG.
Referenced by UanTest::CreateNode(), and GetTypeId().
SetIfIndex()
void ns3::UanNetDevice::SetIfIndex (const uint32_t index) virtual
Parameters
index ifIndex of the device
Implements ns3::NetDevice.
Definition at line 215 of file uan-net-device.cc.
References m_ifIndex.
SetMac()
void ns3::UanNetDevice::SetMac (Ptr< UanMac > mac)
Set the MAC layer for this device.
Parameters
mac The MAC layer.
Definition at line 133 of file uan-net-device.cc.
References ForwardUp(), m_mac, m_phy, third::mac, ns3::MakeCallback(), and NS_LOG_DEBUG.
Referenced by UanTest::CreateNode(), and GetTypeId().
SetMtu()
bool ns3::UanNetDevice::SetMtu (const uint16_t mtu) virtual
Parameters
mtu MTU value, in bytes, to set for the device
Returns
whether the MTU value was within legal bounds
Override for default MTU defined on a per-type basis.
Todo:
Check this in MAC
Implements ns3::NetDevice.
Definition at line 239 of file uan-net-device.cc.
References m_mtu, and NS_LOG_WARN.
SetNode()
void ns3::UanNetDevice::SetNode (Ptr< Node > node) virtual
Parameters
node the node associated to this netdevice.
This method is called from ns3::Node::AddDevice.
Implements ns3::NetDevice.
Definition at line 328 of file uan-net-device.cc.
References m_node.
SetPhy()
void ns3::UanNetDevice::SetPhy (Ptr< UanPhy > phy)
Set the Phy layer for this device.
Parameters
phy The PHY layer.
Definition at line 152 of file uan-net-device.cc.
References m_mac, m_phy, m_trans, NS_LOG_DEBUG, and third::phy.
Referenced by UanTest::CreateNode(), and GetTypeId().
SetPromiscReceiveCallback()
void ns3::UanNetDevice::SetPromiscReceiveCallback (PromiscReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received in promiscuous mode and must be forwarded to the higher layers.
Enables netdevice promiscuous mode and sets the callback that will handle promiscuous mode packets. Note, promiscuous mode packets means all packets, including those packets that can be sensed by the netdevice but which are intended to be received by other hosts.
Implements ns3::NetDevice.
Definition at line 391 of file uan-net-device.cc.
References NS_ASSERT_MSG().
SetReceiveCallback()
void ns3::UanNetDevice::SetReceiveCallback (NetDevice::ReceiveCallback cb) virtual
Parameters
cb callback to invoke whenever a packet has been received and must be forwarded to the higher layers.
Set the callback to be used to notify higher layers when a packet has been received.
Implements ns3::NetDevice.
Definition at line 340 of file uan-net-device.cc.
References m_forwardUp.
Referenced by UanTest::DoOnePhyTest().
SetSleepMode()
void ns3::UanNetDevice::SetSleepMode (bool sleep)
Set the Phy SLEEP mode.
Parameters
sleep SLEEP on or off.
Definition at line 411 of file uan-net-device.cc.
References m_phy.
SetTransducer()
void ns3::UanNetDevice::SetTransducer (Ptr< UanTransducer > trans)
Set the transdcuer used by this device.
Parameters
trans The transducer.
Definition at line 360 of file uan-net-device.cc.
References m_channel, m_phy, m_trans, and NS_LOG_DEBUG.
Referenced by UanTest::CreateNode(), and GetTypeId().
SetTxModeIndex()
void ns3::UanNetDevice::SetTxModeIndex (uint32_t txModeIndex)
Definition at line 417 of file uan-net-device.cc.
References m_mac.
Referenced by UanTest::SendOnePacket().
SupportsSendFrom()
bool ns3::UanNetDevice::SupportsSendFrom (void) const virtual
Returns
true if this interface supports a bridging mode, false otherwise.
Implements ns3::NetDevice.
Definition at line 398 of file uan-net-device.cc.
Member Data Documentation
m_channel
Ptr<UanChannel> ns3::UanNetDevice::m_channel private
The channel attached to this device.
Definition at line 176 of file uan-net-device.h.
Referenced by Clear(), DoGetChannel(), DoInitialize(), GetChannel(), SetChannel(), and SetTransducer().
m_cleared
bool ns3::UanNetDevice::m_cleared private
Flag when we've been cleared.
Definition at line 193 of file uan-net-device.h.
Referenced by Clear().
m_forwardUp
ReceiveCallback ns3::UanNetDevice::m_forwardUp private
The receive callback.
Definition at line 185 of file uan-net-device.h.
Referenced by ForwardUp(), and SetReceiveCallback().
m_ifIndex
uint32_t ns3::UanNetDevice::m_ifIndex private
The interface index of this device.
Definition at line 181 of file uan-net-device.h.
Referenced by GetIfIndex(), and SetIfIndex().
m_linkChanges
TracedCallback ns3::UanNetDevice::m_linkChanges private
Callback to invoke when the link state changes to UP.
Definition at line 184 of file uan-net-device.h.
Referenced by AddLinkChangeCallback().
m_linkup
bool ns3::UanNetDevice::m_linkup private
The link state, true if up.
Definition at line 183 of file uan-net-device.h.
Referenced by IsLinkUp().
m_mac
Ptr<UanMac> ns3::UanNetDevice::m_mac private
The MAC layer attached to this device.
Definition at line 177 of file uan-net-device.h.
Referenced by Clear(), DoInitialize(), GetAddress(), GetBroadcast(), GetMac(), GetMulticast(), GetTxModeIndex(), Send(), SetAddress(), SetMac(), SetPhy(), and SetTxModeIndex().
m_mtu
uint16_t ns3::UanNetDevice::m_mtu private
The device MTU value, in bytes.
Definition at line 182 of file uan-net-device.h.
Referenced by GetMtu(), and SetMtu().
m_node
Ptr<Node> ns3::UanNetDevice::m_node private
The node hosting this device.
Definition at line 175 of file uan-net-device.h.
Referenced by Clear(), GetNode(), and SetNode().
m_phy
Ptr<UanPhy> ns3::UanNetDevice::m_phy private
The PHY layer attached to this device.
Definition at line 178 of file uan-net-device.h.
Referenced by Clear(), DoInitialize(), GetPhy(), IsLinkUp(), SetChannel(), SetMac(), SetPhy(), SetSleepMode(), and SetTransducer().
m_rxLogger
TracedCallback<Ptr<const Packet>, Mac8Address> ns3::UanNetDevice::m_rxLogger private
Trace source triggered when forwarding up received payload from the MAC layer.
Definition at line 188 of file uan-net-device.h.
Referenced by ForwardUp(), and GetTypeId().
m_trans
Ptr<UanTransducer> ns3::UanNetDevice::m_trans private
The Transducer attached to this device.
Definition at line 174 of file uan-net-device.h.
Referenced by Clear(), DoInitialize(), GetTransducer(), SetChannel(), SetPhy(), and SetTransducer().
m_txLogger
TracedCallback<Ptr<const Packet>, Mac8Address> ns3::UanNetDevice::m_txLogger private
Trace source triggered when sending to the MAC layer.
Definition at line 190 of file uan-net-device.h.
Referenced by GetTypeId().
The documentation for this class was generated from the following files:
src/uan/model/uan-net-device.h
src/uan/model/uan-net-device.cc