ns-3: ns3::lorawan::NetworkStatus Class Reference
ns3::lorawan::NetworkStatus Class Reference
This class represents the knowledge about the state of the network that is available at the Network Server.
#include "network-status.h"
Public Member Functions
NetworkStatus ()
virtual ~NetworkStatus ()
void AddGateway (Address &address, Ptr< GatewayStatus > gwStatus)
Add this gateway to the list of gateways connected to the network.
void AddNode (Ptr< ClassAEndDeviceLorawanMac > edMac)
Add a device to the ones that are tracked by this NetworkStatus object.
int CountEndDevices (void)
Return the number of end devices currently managed by the server.
Address GetBestGatewayForDevice (LoraDeviceAddress deviceAddress, int window)
Return whether we have a gateway that is available to send a reply to the specified device.
Ptr< EndDeviceStatus > GetEndDeviceStatus (LoraDeviceAddress address)
Get the EndDeviceStatus corresponding to a LoraDeviceAddress.
Ptr< EndDeviceStatus > GetEndDeviceStatus (Ptr< Packet const > packet)
Get the EndDeviceStatus for the device that sent a packet.
Ptr< Packet > GetReplyForDevice (LoraDeviceAddress edAddress, int windowNumber)
Get the reply for the specified device address.
bool NeedsReply (LoraDeviceAddress deviceAddress)
Return whether the specified device needs a reply.
void OnReceivedPacket (Ptr< const Packet > packet, const Address &gwaddress)
Update network status on the received packet.
void SendThroughGateway (Ptr< Packet > packet, Address gwAddress)
Send a packet through a Gateway.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Public Attributes
std::map< LoraDeviceAddress, Ptr< EndDeviceStatus > > m_endDeviceStatuses
std::map< Address, Ptr< GatewayStatus > > m_gatewayStatuses
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class represents the knowledge about the state of the network that is available at the Network Server.
It is essentially a collection of two maps: one containing DeviceStatus objects, and the other containing GatewayStatus objects.
This class is meant to be queried by NetworkController components, which can decide to take action based on the current status of the network.
Definition at line 45 of file network-status.h.
Constructor & Destructor Documentation
NetworkStatus()
ns3::lorawan::NetworkStatus::NetworkStatus ()
Definition at line 49 of file network-status.cc.
References NS_LOG_FUNCTION_NOARGS.
~NetworkStatus()
ns3::lorawan::NetworkStatus::~NetworkStatus () virtual
Definition at line 54 of file network-status.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
AddGateway()
void ns3::lorawan::NetworkStatus::AddGateway (Address & address, Ptr< GatewayStatus > gwStatus)
Add this gateway to the list of gateways connected to the network.
Each GW is identified by its Address in the NS-GW network.
Definition at line 81 of file network-status.cc.
References first::address, m_gatewayStatuses, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
AddNode()
void ns3::lorawan::NetworkStatus::AddNode (Ptr< ClassAEndDeviceLorawanMac > edMac)
Add a device to the ones that are tracked by this NetworkStatus object.
Definition at line 60 of file network-status.cc.
References m_endDeviceStatuses, NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::lorawan::LoraDeviceAddress::Print().
Referenced by NetworkStatusTest::DoRun().
CountEndDevices()
int ns3::lorawan::NetworkStatus::CountEndDevices (void)
Return the number of end devices currently managed by the server.
Definition at line 244 of file network-status.cc.
References m_endDeviceStatuses, and NS_LOG_FUNCTION.
GetBestGatewayForDevice()
Address ns3::lorawan::NetworkStatus::GetBestGatewayForDevice (LoraDeviceAddress deviceAddress, int window)
Return whether we have a gateway that is available to send a reply to the specified device.
Parameters
deviceAddress the address of the device we are interested in.
Definition at line 127 of file network-status.cc.
References m_endDeviceStatuses, m_gatewayStatuses, NS_ABORT_MSG, and visualizer.ipython_view::window.
GetEndDeviceStatus() [1/2]
Ptr< EndDeviceStatus > ns3::lorawan::NetworkStatus::GetEndDeviceStatus (LoraDeviceAddress address)
Get the EndDeviceStatus corresponding to a LoraDeviceAddress.
Definition at line 227 of file network-status.cc.
References first::address, m_endDeviceStatuses, NS_LOG_ERROR, and NS_LOG_FUNCTION.
GetEndDeviceStatus() [2/2]
Ptr< EndDeviceStatus > ns3::lorawan::NetworkStatus::GetEndDeviceStatus (Ptr< Packet const > packet)
Get the EndDeviceStatus for the device that sent a packet.
Definition at line 204 of file network-status.cc.
References ns3::lorawan::LoraFrameHeader::GetAddress(), m_endDeviceStatuses, NS_LOG_ERROR, NS_LOG_FUNCTION, and ns3::Packet::RemoveHeader().
GetReplyForDevice()
Ptr< Packet > ns3::lorawan::NetworkStatus::GetReplyForDevice (LoraDeviceAddress edAddress, int windowNumber)
Get the reply for the specified device address.
Definition at line 179 of file network-status.cc.
References ns3::Packet::AddPacketTag(), m_endDeviceStatuses, ns3::lorawan::LoraTag::SetDataRate(), and ns3::lorawan::LoraTag::SetFrequency().
GetTypeId()
TypeId ns3::lorawan::NetworkStatus::GetTypeId (void) static
Definition at line 41 of file network-status.cc.
References ns3::TypeId::AddConstructor().
NeedsReply()
bool ns3::lorawan::NetworkStatus::NeedsReply (LoraDeviceAddress deviceAddress)
Return whether the specified device needs a reply.
Parameters
deviceAddress the address of the device we are interested in.
Definition at line 120 of file network-status.cc.
References m_endDeviceStatuses.
OnReceivedPacket()
void ns3::lorawan::NetworkStatus::OnReceivedPacket (Ptr< const Packet > packet, const Address & gwaddress)
Update network status on the received packet.
Parameters
packet the received packet.
address the gateway this packet was received from.
Definition at line 98 of file network-status.cc.
References ns3::lorawan::LoraFrameHeader::GetAddress(), m_endDeviceStatuses, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Packet::RemoveHeader(), and ns3::lorawan::LoraFrameHeader::SetAsUplink().
SendThroughGateway()
void ns3::lorawan::NetworkStatus::SendThroughGateway (Ptr< Packet > packet, Address gwAddress)
Send a packet through a Gateway.
This function assumes that the packet is already tagged with a LoraTag that will inform the gateway of the parameters to use for the transmission.
Definition at line 169 of file network-status.cc.
References m_gatewayStatuses, and NS_LOG_FUNCTION.
Member Data Documentation
m_endDeviceStatuses
std::map<LoraDeviceAddress, Ptr<EndDeviceStatus> > ns3::lorawan::NetworkStatus::m_endDeviceStatuses
Definition at line 118 of file network-status.h.
Referenced by AddNode(), CountEndDevices(), GetBestGatewayForDevice(), GetEndDeviceStatus(), GetReplyForDevice(), NeedsReply(), and OnReceivedPacket().
m_gatewayStatuses
std::map<Address, Ptr<GatewayStatus> > ns3::lorawan::NetworkStatus::m_gatewayStatuses
Definition at line 119 of file network-status.h.
Referenced by AddGateway(), GetBestGatewayForDevice(), and SendThroughGateway().
The documentation for this class was generated from the following files:
src/lorawan/model/network-status.h
src/lorawan/model/network-status.cc