ns-3: RoutingHelper Class Reference
RoutingHelper Class Reference
WAVE module
The RoutingHelper class generates routing data between nodes (vehicles) and uses the RoutingStats class to collect statistics on routing data (application-data packet and byte counts). A routing protocol is configured, and all nodes attempt to send (i.e. route) small packets to another node, which acts as data sinks. Not all nodes act as data sinks. for the vehicular network.
Public Member Functions
RoutingHelper ()
Constructor.
virtual ~RoutingHelper ()
Destructor.
RoutingStats & GetRoutingStats ()
Returns the RoutingStats instance.
void Install (NodeContainer &c, NetDeviceContainer &d, Ipv4InterfaceContainer &i, double totalTime, int protocol, uint32_t nSinks, int routingTables)
Installs routing functionality on nodes and their devices and interfaces.
void OnOffTrace (std::string context, Ptr< const Packet > packet)
Trace the receipt of an on-off-application generated packet.
void SetLogging (int log)
Enable/disable logging.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get class TypeId.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void AssignIpAddresses (NetDeviceContainer &d, Ipv4InterfaceContainer &adhocTxInterfaces)
Assigns IPv4 addresses to net devices and their interfaces.
void ReceiveRoutingPacket (Ptr< Socket > socket)
Process a received routing packet.
void SetupRoutingMessages (NodeContainer &c, Ipv4InterfaceContainer &adhocTxInterfaces)
Sets up routing messages on the nodes and their interfaces.
Ptr< Socket > SetupRoutingPacketReceive (Ipv4Address addr, Ptr< Node > node)
Sets up a routing packet for tranmission.
void SetupRoutingProtocol (NodeContainer &c)
Sets up the protocol protocol on the nodes.
Private Attributes
int m_log
log
uint32_t m_nSinks
number of sink nodes (< all nodes)
uint32_t m_port
port
uint32_t m_protocol
routing protocol; 0=NONE, 1=OLSR, 2=AODV, 3=DSDV, 4=DSR
std::string m_protocolName
protocol name
int m_routingTables
dump routing table (at t=5 sec). 0=No, 1=Yes
double m_TotalSimTime
seconds
RoutingStats routingStats
routing statistics
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The RoutingHelper class generates routing data between nodes (vehicles) and uses the RoutingStats class to collect statistics on routing data (application-data packet and byte counts). A routing protocol is configured, and all nodes attempt to send (i.e. route) small packets to another node, which acts as data sinks. Not all nodes act as data sinks. for the vehicular network.
Definition at line 380 of file vanet-routing-compare.cc.
Constructor & Destructor Documentation
RoutingHelper()
RoutingHelper::RoutingHelper ()
Constructor.
Returns
none
Definition at line 505 of file vanet-routing-compare.cc.
~RoutingHelper()
RoutingHelper::~RoutingHelper () virtual
Destructor.
Returns
none
Definition at line 515 of file vanet-routing-compare.cc.
Member Function Documentation
AssignIpAddresses()
void RoutingHelper::AssignIpAddresses (NetDeviceContainer & d, Ipv4InterfaceContainer & adhocTxInterfaces) private
Assigns IPv4 addresses to net devices and their interfaces.
Parameters
d net device container
adhocTxInterfaces IPv4 interface container
Returns
none
Definition at line 621 of file vanet-routing-compare.cc.
References ns3::Ipv4AddressHelper::Assign(), NS_LOG_INFO, and ns3::Ipv4AddressHelper::SetBase().
Referenced by Install().
GetRoutingStats()
RoutingStats & RoutingHelper::GetRoutingStats ()
Returns the RoutingStats instance.
Returns
the RoutingStats instance
Definition at line 707 of file vanet-routing-compare.cc.
References routingStats.
Referenced by VanetRoutingExperiment::CheckThroughput(), VanetRoutingExperiment::ProcessOutputs(), and ReceiveRoutingPacket().
GetTypeId()
TypeId RoutingHelper::GetTypeId (void) static
Get class TypeId.
Returns
the TypeId for the class
Definition at line 497 of file vanet-routing-compare.cc.
References ns3::TypeId::SetParent().
Install()
void RoutingHelper::Install (NodeContainer & c, NetDeviceContainer & d, Ipv4InterfaceContainer & i, double totalTime, int protocol, uint32_t nSinks, int routingTables)
Installs routing functionality on nodes and their devices and interfaces.
Parameters
c node container
d net device container
i IPv4 interface container
totalTime the total time that nodes should attempt to route data
protocol the routing protocol (1=OLSR;2=AODV;3=DSDV;4=DSR)
nSinks the number of nodes which will act as data sinks
routingTables dump routing tables at t=5 seconds (0=no;1=yes)
Returns
none
Definition at line 520 of file vanet-routing-compare.cc.
References AssignIpAddresses(), m_nSinks, m_protocol, m_routingTables, m_TotalSimTime, SetupRoutingMessages(), and SetupRoutingProtocol().
Referenced by VanetRoutingExperiment::SetupRoutingMessages().
OnOffTrace()
void RoutingHelper::OnOffTrace (std::string context, Ptr< const Packet > packet)
Trace the receipt of an on-off-application generated packet.
Parameters
context this object
packet a received packet
Returns
none
Definition at line 700 of file vanet-routing-compare.cc.
References ns3::Packet::GetSize(), RoutingStats::IncTxBytes(), and routingStats.
Referenced by VanetRoutingExperiment::ConfigureApplications().
ReceiveRoutingPacket()
void RoutingHelper::ReceiveRoutingPacket (Ptr< Socket > socket) private
Process a received routing packet.
Parameters
socket the receiving socket
Returns
none
Definition at line 682 of file vanet-routing-compare.cc.
References GetRoutingStats(), ns3::Packet::GetSize(), RoutingStats::IncRxBytes(), RoutingStats::IncRxPkts(), m_log, m_protocolName, NS_LOG_UNCOND, PrintReceivedRoutingPacket(), and ns3::Socket::RecvFrom().
Referenced by SetupRoutingPacketReceive().
SetLogging()
void RoutingHelper::SetLogging (int log)
Enable/disable logging.
Parameters
log non-zero to enable logging
Returns
none
Definition at line 713 of file vanet-routing-compare.cc.
References m_log.
Referenced by VanetRoutingExperiment::ParseCommandLineArguments().
SetupRoutingMessages()
void RoutingHelper::SetupRoutingMessages (NodeContainer & c, Ipv4InterfaceContainer & adhocTxInterfaces) private
Sets up routing messages on the nodes and their interfaces.
Parameters
c node container
adhocTxInterfaces IPv4 interface container
Returns
none
Definition at line 633 of file vanet-routing-compare.cc.
References ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::UniformRandomVariable::GetValue(), ns3::OnOffHelper::Install(), m_nSinks, m_port, m_protocol, m_TotalSimTime, ns3::Seconds(), ns3::OnOffHelper::SetAttribute(), ns3::RandomVariableStream::SetStream(), SetupRoutingPacketReceive(), sink, ns3::ApplicationContainer::Start(), and ns3::ApplicationContainer::Stop().
Referenced by Install().
SetupRoutingPacketReceive()
Ptr< Socket > RoutingHelper::SetupRoutingPacketReceive (Ipv4Address addr, Ptr< Node > node) private
Sets up a routing packet for tranmission.
Parameters
addr destination address
node source node
Returns
Socket to be used for sending/receiving a routed data packet
Definition at line 539 of file vanet-routing-compare.cc.
References m_port, ns3::MakeCallback(), ReceiveRoutingPacket(), and sink.
Referenced by SetupRoutingMessages().
SetupRoutingProtocol()
void RoutingHelper::SetupRoutingProtocol (NodeContainer & c) private
Sets up the protocol protocol on the nodes.
Parameters
c node container
Returns
none
Definition at line 551 of file vanet-routing-compare.cc.
References ns3::AsciiTraceHelper::CreateFileStream(), ns3::DsrMainHelper::Install(), ns3::InternetStackHelper::Install(), list, m_log, m_protocol, m_protocolName, m_routingTables, NS_FATAL_ERROR, NS_LOG_UNCOND, ns3::Ipv4RoutingHelper::PrintRoutingTableAllAt(), and ns3::InternetStackHelper::SetRoutingHelper().
Referenced by Install().
Member Data Documentation
m_log
int RoutingHelper::m_log private
log
Definition at line 491 of file vanet-routing-compare.cc.
Referenced by ReceiveRoutingPacket(), SetLogging(), and SetupRoutingProtocol().
m_nSinks
uint32_t RoutingHelper::m_nSinks private
number of sink nodes (< all nodes)
Definition at line 487 of file vanet-routing-compare.cc.
Referenced by Install(), and SetupRoutingMessages().
m_port
uint32_t RoutingHelper::m_port private
port
Definition at line 486 of file vanet-routing-compare.cc.
Referenced by SetupRoutingMessages(), and SetupRoutingPacketReceive().
m_protocol
uint32_t RoutingHelper::m_protocol private
routing protocol; 0=NONE, 1=OLSR, 2=AODV, 3=DSDV, 4=DSR
Definition at line 485 of file vanet-routing-compare.cc.
Referenced by Install(), SetupRoutingMessages(), and SetupRoutingProtocol().
m_protocolName
std::string RoutingHelper::m_protocolName private
protocol name
Definition at line 490 of file vanet-routing-compare.cc.
Referenced by ReceiveRoutingPacket(), and SetupRoutingProtocol().
m_routingTables
int RoutingHelper::m_routingTables private
dump routing table (at t=5 sec). 0=No, 1=Yes
Definition at line 488 of file vanet-routing-compare.cc.
Referenced by Install(), and SetupRoutingProtocol().
m_TotalSimTime
double RoutingHelper::m_TotalSimTime private
seconds
Definition at line 484 of file vanet-routing-compare.cc.
Referenced by Install(), and SetupRoutingMessages().
routingStats
RoutingStats RoutingHelper::routingStats private
routing statistics
Definition at line 489 of file vanet-routing-compare.cc.
Referenced by GetRoutingStats(), and OnOffTrace().
The documentation for this class was generated from the following file:
src/wave/examples/vanet-routing-compare.cc