ns-3: ns3::LteUeCmacSapUser Class Reference
ns3::LteUeCmacSapUser Class Reference abstract
Service Access Point (SAP) offered by the UE MAC to the UE RRC.
#include "lte-ue-cmac-sap.h"
Public Member Functions
virtual ~LteUeCmacSapUser ()
virtual void NotifyRandomAccessFailed ()=0
Notify the RRC that the MAC Random Access procedure failed.
virtual void NotifyRandomAccessSuccessful ()=0
Notify the RRC that the MAC Random Access procedure completed successfully.
virtual void SetTemporaryCellRnti (uint16_t rnti)=0
Detailed Description
Service Access Point (SAP) offered by the UE MAC to the UE RRC.
This is the MAC SAP User, i.e., the part of the SAP that contains the RRC methods called by the MAC
Definition at line 137 of file lte-ue-cmac-sap.h.
Constructor & Destructor Documentation
~LteUeCmacSapUser()
ns3::LteUeCmacSapUser::~LteUeCmacSapUser () virtual
Definition at line 32 of file lte-ue-cmac-sap.cc.
Member Function Documentation
NotifyRandomAccessFailed()
virtual void ns3::LteUeCmacSapUser::NotifyRandomAccessFailed () pure virtual
Notify the RRC that the MAC Random Access procedure failed.
Implemented in ns3::UeMemberLteUeCmacSapUser.
Referenced by ns3::LteUeMac::RaResponseTimeout().
NotifyRandomAccessSuccessful()
virtual void ns3::LteUeCmacSapUser::NotifyRandomAccessSuccessful () pure virtual
Notify the RRC that the MAC Random Access procedure completed successfully.
Implemented in ns3::UeMemberLteUeCmacSapUser.
Referenced by ns3::LteUeMac::RecvRaResponse().
SetTemporaryCellRnti()
virtual void ns3::LteUeCmacSapUser::SetTemporaryCellRnti (uint16_t rnti) pure virtual
Parameters
rnti the T-C-RNTI, which will eventually become the C-RNTI after contention resolution
Implemented in ns3::UeMemberLteUeCmacSapUser.
Referenced by ns3::LteUeMac::RecvRaResponse().
The documentation for this class was generated from the following files:
src/lte/model/lte-ue-cmac-sap.h
src/lte/model/lte-ue-cmac-sap.cc