ns-3: LrWpanCollisionTestCase Class Reference
LrWpanCollisionTestCase Class Reference
LR-WPAN models » LrWpan module tests | Test suites
LrWpan Collision Test.
Public Member Functions
LrWpanCollisionTestCase ()
virtual ~LrWpanCollisionTestCase ()
void DataIndication (McpsDataIndicationParams params, Ptr< Packet > p)
Function called when DataIndication is hit.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
uint8_t m_rxPackets
Rx packets counter.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
LrWpan Collision Test.
Definition at line 42 of file lr-wpan-collision-test.cc.
Constructor & Destructor Documentation
LrWpanCollisionTestCase()
LrWpanCollisionTestCase::LrWpanCollisionTestCase ()
Definition at line 60 of file lr-wpan-collision-test.cc.
References m_rxPackets.
~LrWpanCollisionTestCase()
LrWpanCollisionTestCase::~LrWpanCollisionTestCase () virtual
Definition at line 66 of file lr-wpan-collision-test.cc.
Member Function Documentation
DataIndication()
void LrWpanCollisionTestCase::DataIndication (McpsDataIndicationParams params, Ptr< Packet > p)
Function called when DataIndication is hit.
Parameters
params The MCPS params.
p The packet.
Definition at line 70 of file lr-wpan-collision-test.cc.
References m_rxPackets.
Referenced by DoRun().
DoRun()
void LrWpanCollisionTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 77 of file lr-wpan-collision-test.cc.
References ns3::Node::AddDevice(), ns3::Object::AggregateObject(), third::channel, DataIndication(), ns3::LrWpanNetDevice::GetCsmaCa(), ns3::LrWpanNetDevice::GetMac(), ns3::LrWpanNetDevice::GetPhy(), m_rxPackets, ns3::MakeCallback(), NS_TEST_EXPECT_MSG_EQ, aloha::params, ns3::Seconds(), ns3::LrWpanNetDevice::SetAddress(), ns3::LrWpanNetDevice::SetChannel(), ns3::MobilityModel::SetPosition(), ns3::SHORT_ADDR, and ns3::TX_OPTION_ACK.
Member Data Documentation
m_rxPackets
uint8_t LrWpanCollisionTestCase::m_rxPackets private
Rx packets counter.
Definition at line 57 of file lr-wpan-collision-test.cc.
Referenced by LrWpanCollisionTestCase(), DataIndication(), and DoRun().
The documentation for this class was generated from the following file:
src/lr-wpan/test/lr-wpan-collision-test.cc