ns-3: ns3::LenaDeactivateBearerTestCase Class Reference
ns3::LenaDeactivateBearerTestCase Class Reference
LTE Models » lte module tests | Test suites
Test case that for testing the deactivation of the bearer functionality. The test consist in deactivating the bearer and checking if some traffic will appear afterwards on the given bearer. If some traffic is detected the test will fail. Firs the de-activation is performed by using Simulator::Schedule() method which will initiate bearer de-activation after deActivateTime that is specified as the test parameter. Additionally, test instantiate de-activation in sequence.
#include "lte-test-deactivate-bearer.h"
Public Member Functions
LenaDeactivateBearerTestCase (std::vector< uint16_t > dist, std::vector< uint32_t > estThrPssDl, std::vector< uint16_t > packetSize, uint16_t interval, bool errorModelEnabled, bool useIdealRrc)
Constructor.
virtual ~LenaDeactivateBearerTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Static Private Member Functions
static std::string BuildNameString (uint16_t nUser, std::vector< uint16_t > dist)
Build name string function.
Private Attributes
std::vector< uint16_t > m_dist
distance between the nodes
bool m_errorModelEnabled
error mode enabled?
std::vector< uint32_t > m_estThrPssDl
estimated threshold PSS DL
uint16_t m_interval
interval time in ms
uint16_t m_nUser
number of UE nodes
std::vector< uint16_t > m_packetSize
packet size in bytes
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test case that for testing the deactivation of the bearer functionality. The test consist in deactivating the bearer and checking if some traffic will appear afterwards on the given bearer. If some traffic is detected the test will fail. Firs the de-activation is performed by using Simulator::Schedule() method which will initiate bearer de-activation after deActivateTime that is specified as the test parameter. Additionally, test instantiate de-activation in sequence.
Definition at line 25 of file lte-test-deactivate-bearer.h.
Constructor & Destructor Documentation
LenaDeactivateBearerTestCase()
ns3::LenaDeactivateBearerTestCase::LenaDeactivateBearerTestCase (std::vector< uint16_t > dist, std::vector< uint32_t > estThrPssDl, std::vector< uint16_t > packetSize, uint16_t interval, bool errorModelEnabled, bool useIdealRrc)
Constructor.
Parameters
dist distance between the nodes
estThrPssDl estimated throughput PSS DL
packetSize packet size in bytes
interval interval time in ms
errorModelEnabled whether the error model is enabled
useIdealRrc whether to use ideal RRC
Definition at line 113 of file lte-test-deactivate-bearer.cc.
~LenaDeactivateBearerTestCase()
ns3::LenaDeactivateBearerTestCase::~LenaDeactivateBearerTestCase () virtual
Definition at line 124 of file lte-test-deactivate-bearer.cc.
Member Function Documentation
BuildNameString()
std::string ns3::LenaDeactivateBearerTestCase::BuildNameString (uint16_t nUser, std::vector< uint16_t > dist) static private
Build name string function.
Parameters
nUser number of UE nodes
dist distance between nodes
Returns
name string
Definition at line 101 of file lte-test-deactivate-bearer.cc.
DoRun()
void ns3::LenaDeactivateBearerTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 129 of file lte-test-deactivate-bearer.cc.
References ns3::LteHelper::ActivateDedicatedEpsBearer(), ns3::EpsBearer::arp, ns3::Ipv4AddressHelper::Assign(), ns3::NoBackhaulEpcHelper::AssignUeIpv4Address(), ns3::LteHelper::Attach(), first::clientApps, ns3::NodeContainer::Create(), ns3::TestCase::CreateTempDirFilename(), ns3::LteHelper::DeActivateDedicatedEpsBearer(), ns3::EpcTft::Default(), ns3::Simulator::Destroy(), ns3::LteHelper::EnableRlcTraces(), ns3::EpsBearer::GBR_CONV_VOICE, ns3::GbrQosInformation::gbrDl, ns3::GbrQosInformation::gbrUl, ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::Ipv4Address::GetAny(), ns3::NodeContainer::GetN(), ns3::Object::GetObject(), ns3::NoBackhaulEpcHelper::GetPgwNode(), ns3::LteEnbNetDevice::GetPhy(), ns3::LteHelper::GetRlcStats(), ns3::Ipv4StaticRoutingHelper::GetStaticRouting(), ns3::NoBackhaulEpcHelper::GetUeDefaultGatewayAddress(), ns3::UdpClientHelper::Install(), ns3::PointToPointHelper::Install(), ns3::PacketSinkHelper::Install(), ns3::InternetStackHelper::Install(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), m_dist, m_errorModelEnabled, m_estThrPssDl, m_interval, m_nUser, m_packetSize, ns3::GbrQosInformation::mbrDl, ns3::GbrQosInformation::mbrUl, ns3::MilliSeconds(), third::mobility, NS_LOG_INFO, NS_TEST_ASSERT_MSG_EQ, NS_TEST_ASSERT_MSG_EQ_TOL, ns3::AllocationRetentionPriority::preemptionCapability, ns3::AllocationRetentionPriority::preemptionVulnerability, ns3::AllocationRetentionPriority::priorityLevel, ns3::Simulator::Run(), ns3::Simulator::Schedule(), ns3::Seconds(), first::serverApps, ns3::UdpClientHelper::SetAttribute(), ns3::ObjectBase::SetAttribute(), ns3::Ipv4AddressHelper::SetBase(), ns3::PointToPointHelper::SetChannelAttribute(), ns3::Config::SetDefault(), ns3::PointToPointHelper::SetDeviceAttribute(), ns3::LteHelper::SetEpcHelper(), ns3::LteHelper::SetSchedulerType(), and ns3::Simulator::Stop().
Member Data Documentation
m_dist
std::vector<uint16_t> ns3::LenaDeactivateBearerTestCase::m_dist private
distance between the nodes
Definition at line 52 of file lte-test-deactivate-bearer.h.
Referenced by DoRun().
m_errorModelEnabled
bool ns3::LenaDeactivateBearerTestCase::m_errorModelEnabled private
error mode enabled?
Definition at line 56 of file lte-test-deactivate-bearer.h.
Referenced by DoRun().
m_estThrPssDl
std::vector<uint32_t> ns3::LenaDeactivateBearerTestCase::m_estThrPssDl private
estimated threshold PSS DL
Definition at line 55 of file lte-test-deactivate-bearer.h.
Referenced by DoRun().
m_interval
uint16_t ns3::LenaDeactivateBearerTestCase::m_interval private
interval time in ms
Definition at line 54 of file lte-test-deactivate-bearer.h.
Referenced by DoRun().
m_nUser
uint16_t ns3::LenaDeactivateBearerTestCase::m_nUser private
number of UE nodes
Definition at line 51 of file lte-test-deactivate-bearer.h.
Referenced by DoRun().
m_packetSize
std::vector<uint16_t> ns3::LenaDeactivateBearerTestCase::m_packetSize private
packet size in bytes
Definition at line 53 of file lte-test-deactivate-bearer.h.
Referenced by DoRun().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-deactivate-bearer.h
src/lte/test/lte-test-deactivate-bearer.cc