ns-3: ns3::lorawan::LoraDeviceAddress Class Reference
ns3::lorawan::LoraDeviceAddress Class Reference
This class represents the device address of a LoraWAN End Device.
#include "lora-device-address.h"
Public Member Functions
LoraDeviceAddress ()
LoraDeviceAddress (NwkID nwkId, NwkAddr nwkAddr)
Build a new address from a network id and network address.
LoraDeviceAddress (uint32_t address)
Build a new address from a 32-bit integer.
LoraDeviceAddress (uint8_t nwkId, uint32_t nwkAddr)
Build a new address from a network id and network address.
uint32_t Get (void) const
Get the address in 32-bit integer form.
uint32_t GetNwkAddr (void)
Get the NwkAddr of this device.
uint8_t GetNwkID (void)
Get the NwkID of this device.
bool operator!= (const LoraDeviceAddress &other) const
bool operator< (const LoraDeviceAddress &other) const
bool operator== (const LoraDeviceAddress &other) const
bool operator> (const LoraDeviceAddress &other) const
std::string Print (void) const
Print the address bit-by-bit to a human-readable string.
void Serialize (uint8_t buf[4]) const
Convert this address to a buffer.
void Set (uint32_t address)
Set the address as a 32 bit integer.
void Set (uint8_t nwkId, uint32_t nwkAddr)
Set the address, combining a network id and a network address.
void SetNwkAddr (uint32_t nwkAddr)
Set the NwkAddr of this device.
void SetNwkID (uint8_t nwkId)
Set the NwkID of this device.
Static Public Member Functions
static LoraDeviceAddress ConvertFrom (const Address &address)
Convert from an ordinary address to a LoraDeviceAddress instance.
static LoraDeviceAddress Deserialize (const uint8_t buf[4])
Convert the input buffer into a new address.
Private Member Functions
Address ConvertTo (void) const
Convert this instance of LoraDeviceAddress to an Address.
Static Private Member Functions
static uint8_t GetType (void)
Private Attributes
NwkAddr m_nwkAddr
The network address of this address.
NwkID m_nwkId
The network Id of this address.
Detailed Description
This class represents the device address of a LoraWAN End Device.
Definition at line 94 of file lora-device-address.h.
Constructor & Destructor Documentation
LoraDeviceAddress() [1/4]
ns3::lorawan::LoraDeviceAddress::LoraDeviceAddress ()
Definition at line 81 of file lora-device-address.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by Deserialize().
LoraDeviceAddress() [2/4]
ns3::lorawan::LoraDeviceAddress::LoraDeviceAddress (uint32_t address)
Build a new address from a 32-bit integer.
Definition at line 86 of file lora-device-address.cc.
References first::address, NS_LOG_FUNCTION, and Set().
LoraDeviceAddress() [3/4]
ns3::lorawan::LoraDeviceAddress::LoraDeviceAddress (uint8_t nwkId, uint32_t nwkAddr)
Build a new address from a network id and network address.
Definition at line 93 of file lora-device-address.cc.
References m_nwkAddr, m_nwkId, NS_LOG_FUNCTION, ns3::lorawan::NwkAddr::Set(), and ns3::lorawan::NwkID::Set().
LoraDeviceAddress() [4/4]
ns3::lorawan::LoraDeviceAddress::LoraDeviceAddress (NwkID nwkId, NwkAddr nwkAddr)
Build a new address from a network id and network address.
Definition at line 101 of file lora-device-address.cc.
References ns3::lorawan::NwkID::Get(), ns3::lorawan::NwkAddr::Get(), m_nwkAddr, m_nwkId, and NS_LOG_FUNCTION.
Member Function Documentation
ConvertFrom()
LoraDeviceAddress ns3::lorawan::LoraDeviceAddress::ConvertFrom (const Address & address) static
Convert from an ordinary address to a LoraDeviceAddress instance.
Definition at line 151 of file lora-device-address.cc.
References first::address, Deserialize(), GetType(), and NS_ASSERT.
ConvertTo()
Address ns3::lorawan::LoraDeviceAddress::ConvertTo (void) const private
Convert this instance of LoraDeviceAddress to an Address.
Definition at line 141 of file lora-device-address.cc.
References GetType(), NS_LOG_FUNCTION, and Serialize().
Deserialize()
LoraDeviceAddress ns3::lorawan::LoraDeviceAddress::Deserialize (const uint8_t buf[4]) static
Convert the input buffer into a new address.
Definition at line 123 of file lora-device-address.cc.
References LoraDeviceAddress(), first::address, and NS_LOG_FUNCTION.
Referenced by ConvertFrom().
Get()
uint32_t ns3::lorawan::LoraDeviceAddress::Get (void) const
Get the address in 32-bit integer form.
Definition at line 175 of file lora-device-address.cc.
References first::address, ns3::lorawan::NwkID::Get(), ns3::lorawan::NwkAddr::Get(), m_nwkAddr, m_nwkId, NS_LOG_DEBUG, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::lorawan::LoraFrameHeader::Serialize(), and Serialize().
GetNwkAddr()
uint32_t ns3::lorawan::LoraDeviceAddress::GetNwkAddr (void)
Get the NwkAddr of this device.
Remarks
The NwkAddr will be contained on the 25 least significant bits of the uint32_t.
Returns
A 32-bit representation of the Network Address of this Device Address.
Definition at line 205 of file lora-device-address.cc.
References ns3::lorawan::NwkAddr::Get(), m_nwkAddr, and NS_LOG_FUNCTION_NOARGS.
GetNwkID()
uint8_t ns3::lorawan::LoraDeviceAddress::GetNwkID (void)
Get the NwkID of this device.
Remarks
The NwkID bit-by-bit representation will be contained in the 7 least significant bits of the returned uint8_t.
Returns
An 8-bit representation of the Network Id of this Device Address.
Definition at line 197 of file lora-device-address.cc.
References ns3::lorawan::NwkID::Get(), m_nwkId, and NS_LOG_FUNCTION_NOARGS.
GetType()
uint8_t ns3::lorawan::LoraDeviceAddress::GetType (void) static private
Definition at line 166 of file lora-device-address.cc.
References NS_LOG_FUNCTION_NOARGS, and ns3::Address::Register().
Referenced by ConvertFrom(), and ConvertTo().
operator!=()
bool ns3::lorawan::LoraDeviceAddress::operator!= (const LoraDeviceAddress & other) const
Definition at line 246 of file lora-device-address.cc.
operator<()
bool ns3::lorawan::LoraDeviceAddress::operator< (const LoraDeviceAddress & other) const
Definition at line 252 of file lora-device-address.cc.
operator==()
bool ns3::lorawan::LoraDeviceAddress::operator== (const LoraDeviceAddress & other) const
Definition at line 240 of file lora-device-address.cc.
operator>()
bool ns3::lorawan::LoraDeviceAddress::operator> (const LoraDeviceAddress & other) const
Definition at line 258 of file lora-device-address.cc.
Print()
std::string ns3::lorawan::LoraDeviceAddress::Print (void) const
Print the address bit-by-bit to a human-readable string.
Returns
The string containing the network address.
Definition at line 229 of file lora-device-address.cc.
References ns3::lorawan::NwkID::Get(), ns3::lorawan::NwkAddr::Get(), m_nwkAddr, m_nwkId, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::lorawan::NetworkStatus::AddNode(), ns3::lorawan::LoraFrameHeader::Deserialize(), and ns3::lorawan::LoraFrameHeader::Print().
Serialize()
void ns3::lorawan::LoraDeviceAddress::Serialize (uint8_t buf[4]) const
Convert this address to a buffer.
Definition at line 110 of file lora-device-address.cc.
References first::address, Get(), and NS_LOG_FUNCTION.
Referenced by ConvertTo(), and AddressTest::DoRun().
Set() [1/2]
void ns3::lorawan::LoraDeviceAddress::Set (uint32_t address)
Set the address as a 32 bit integer.
Definition at line 188 of file lora-device-address.cc.
References first::address, m_nwkAddr, m_nwkId, NS_LOG_FUNCTION_NOARGS, ns3::lorawan::NwkAddr::Set(), and ns3::lorawan::NwkID::Set().
Referenced by LoraDeviceAddress(), and ns3::lorawan::LoraFrameHeader::Deserialize().
Set() [2/2]
void ns3::lorawan::LoraDeviceAddress::Set (uint8_t nwkId, uint32_t nwkAddr)
Set the address, combining a network id and a network address.
Note that nwkId is 7 bits long, and this function expects the 7 least significant bits to contain the nwkId. Similarly for the nwkAddr, the 25 least signficant bits of the uint32 are those that are expected to contain the nwkAddr.
SetNwkAddr()
void ns3::lorawan::LoraDeviceAddress::SetNwkAddr (uint32_t nwkAddr)
Set the NwkAddr of this device.
Remarks
The NwkAddr is expected to be contained on the least significant bits of the uint32_t.
Parameters
nwkAddr The network address to set.
Definition at line 221 of file lora-device-address.cc.
References m_nwkAddr, NS_LOG_FUNCTION, and ns3::lorawan::NwkAddr::Set().
SetNwkID()
void ns3::lorawan::LoraDeviceAddress::SetNwkID (uint8_t nwkId)
Set the NwkID of this device.
Remarks
The NwkID is expected to be contained on the 7 least significant bits of the uint8_t.
Parameters
nwkId The network id to set.
Definition at line 213 of file lora-device-address.cc.
References m_nwkId, NS_LOG_FUNCTION, and ns3::lorawan::NwkID::Set().
Member Data Documentation
m_nwkAddr
NwkAddr ns3::lorawan::LoraDeviceAddress::m_nwkAddr private
The network address of this address.
Definition at line 208 of file lora-device-address.h.
Referenced by LoraDeviceAddress(), Get(), GetNwkAddr(), Print(), Set(), and SetNwkAddr().
m_nwkId
NwkID ns3::lorawan::LoraDeviceAddress::m_nwkId private
The network Id of this address.
Definition at line 207 of file lora-device-address.h.
Referenced by LoraDeviceAddress(), Get(), GetNwkID(), Print(), Set(), and SetNwkID().
The documentation for this class was generated from the following files:
src/lorawan/model/lora-device-address.h
src/lorawan/model/lora-device-address.cc