ns-3: ns3::tests::IncrementalTestCase Class Reference
ns3::tests::IncrementalTestCase Class Reference
Test suites | Core » Core module tests | Core » Hash Functions » Hash test suite
Public Member Functions
IncrementalTestCase ()
Constructor.
virtual ~IncrementalTestCase ()
Destructor.
Public Member Functions inherited from ns3::tests::HashTestCase
HashTestCase (const std::string name)
Constructor.
virtual ~HashTestCase ()
Destructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void DoHash (const std::string name, Hasher hasher)
Complute the hash test function.
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
std::string key1
test string
std::string key12
test string
std::string key2
test string
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::tests::HashTestCase
void Check (const std::string hashName, const uint32_t hash)
Check function.
void Check (const std::string hashName, const uint64_t hash)
Check function.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Protected Attributes inherited from ns3::tests::HashTestCase
uint32_t hash32Reference
The 32-bit hash of the reference.
uint64_t hash64Reference
The 64-bit hash of the reference.
std::string key
The reference value to hash.
Detailed Description
Test incremental hashing
Definition at line 375 of file hash-test-suite.cc.
Constructor & Destructor Documentation
IncrementalTestCase()
ns3::tests::IncrementalTestCase::IncrementalTestCase ()
Constructor.
Definition at line 396 of file hash-test-suite.cc.
~IncrementalTestCase()
ns3::tests::IncrementalTestCase::~IncrementalTestCase () virtual
Destructor.
Definition at line 400 of file hash-test-suite.cc.
Member Function Documentation
DoHash()
void ns3::tests::IncrementalTestCase::DoHash (const std::string name, Hasher hasher) private
Complute the hash test function.
Parameters
name the hash name
hasher the hash function
Definition at line 404 of file hash-test-suite.cc.
References ns3::tests::HashTestCase::Check(), ns3::Hasher::clear(), ns3::Hasher::GetHash32(), ns3::Hasher::GetHash64(), ns3::tests::HashTestCase::hash32Reference, ns3::tests::HashTestCase::hash64Reference, key1, key12, and key2.
Referenced by DoRun().
DoRun()
void ns3::tests::IncrementalTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Reimplemented from ns3::tests::HashTestCase.
Definition at line 416 of file hash-test-suite.cc.
References DoHash(), ns3::TestCase::GetName(), key1, key12, and key2.
Member Data Documentation
key1
std::string ns3::tests::IncrementalTestCase::key1 private
test string
Definition at line 391 of file hash-test-suite.cc.
Referenced by DoHash(), and DoRun().
key12
std::string ns3::tests::IncrementalTestCase::key12 private
test string
Definition at line 393 of file hash-test-suite.cc.
Referenced by DoHash(), and DoRun().
key2
std::string ns3::tests::IncrementalTestCase::key2 private
test string
Definition at line 392 of file hash-test-suite.cc.
Referenced by DoHash(), and DoRun().
The documentation for this class was generated from the following file:
src/core/test/hash-test-suite.cc