ns-3: ns3::MultiModelSpectrumChannel Class Reference
ns3::MultiModelSpectrumChannel Class Reference
Spectrum Models
#include "multi-model-spectrum-channel.h"
Public Member Functions
MultiModelSpectrumChannel ()
virtual void AddRx (Ptr< SpectrumPhy > phy)
Add a SpectrumPhy to a channel, so it can receive packets.
virtual Ptr< NetDevice > GetDevice (std::size_t i) const
virtual std::size_t GetNDevices (void) const
virtual void StartTx (Ptr< SpectrumSignalParameters > params)
Used by attached PHY instances to transmit signals on the channel.
Public Member Functions inherited from ns3::SpectrumChannel
SpectrumChannel ()
constructor
virtual ~SpectrumChannel ()
destructor
void AddPropagationLossModel (Ptr< PropagationLossModel > loss)
Add the single-frequency propagation loss model to be used.
void AddSpectrumPropagationLossModel (Ptr< SpectrumPropagationLossModel > loss)
Add the frequency-dependent propagation loss model to be used.
Ptr< SpectrumPropagationLossModel > GetSpectrumPropagationLossModel (void)
Get the frequency-dependent propagation loss model.
void SetPropagationDelayModel (Ptr< PropagationDelayModel > delay)
Set the propagation delay model to be used.
Public Member Functions inherited from ns3::Channel
Channel ()
virtual ~Channel ()
uint32_t GetId (void) const
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::SpectrumChannel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Channel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
void DoDispose ()
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Member Functions
TxSpectrumModelInfoMap_t::const_iterator FindAndEventuallyAddTxSpectrumModel (Ptr< const SpectrumModel > txSpectrumModel)
This method checks if m_rxSpectrumModelInfoMap contains an entry for the given TX SpectrumModel.
virtual void StartRx (Ptr< SpectrumSignalParameters > params, Ptr< SpectrumPhy > receiver)
Used internally to reschedule transmission after the propagation delay.
Private Attributes
std::size_t m_numDevices
Number of devices connected to the channel.
RxSpectrumModelInfoMap_t m_rxSpectrumModelInfoMap
Data structure holding, for each RX spectrum model, all the corresponding SpectrumPhy instances.
TxSpectrumModelInfoMap_t m_txSpectrumModelInfoMap
Data structure holding, for each TX SpectrumModel, all the converters to any RX SpectrumModel, and all the corresponding SpectrumPhy instances.
Additional Inherited Members
Public Types inherited from ns3::SpectrumChannel
typedef void(* GainTracedCallback) (Ptr< const MobilityModel > txMobility, Ptr< const MobilityModel > rxMobility, double txAntennaGain, double rxAntennaGain, double propagationGain, double pathloss)
TracedCallback signature for path loss calculation events.
typedef void(* LossTracedCallback) (Ptr< const SpectrumPhy > txPhy, Ptr< const SpectrumPhy > rxPhy, double lossDb)
TracedCallback signature for path loss calculation events.
typedef void(* SignalParametersTracedCallback) (Ptr< SpectrumSignalParameters > params)
TracedCallback signature for Ptr<const SpectrumSignalParameters>.
Protected Attributes inherited from ns3::SpectrumChannel
TracedCallback< Ptr< const MobilityModel >, Ptr< const MobilityModel >, double, double, double, double > m_gainTrace
The Gain trace source.
double m_maxLossDb
Maximum loss [dB].
TracedCallback< Ptr< const SpectrumPhy >, Ptr< const SpectrumPhy >, double > m_pathLossTrace
The PathLoss trace source.
Ptr< PropagationDelayModel > m_propagationDelay
Propagation delay model to be used with this channel.
Ptr< PropagationLossModel > m_propagationLoss
Single-frequency propagation loss model to be used with this channel.
Ptr< SpectrumPropagationLossModel > m_spectrumPropagationLoss
Frequency-dependent propagation loss model to be used with this channel.
TracedCallback< Ptr< SpectrumSignalParameters > > m_txSigParamsTrace
Traced callback for SpectrumSignalParameters in StartTx requests.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This SpectrumChannel implementation can handle the presence of SpectrumPhy instances which can use different spectrum models, i.e., different SpectrumModel.
Note
It is allowed for a receiving SpectrumPhy to switch to a different SpectrumModel during the simulation. The requirement for this to work is that, after the SpectrumPhy switched its SpectrumModel, MultiModelSpectrumChannel::AddRx () is called again passing the pointer to that SpectrumPhy.
Definition at line 106 of file multi-model-spectrum-channel.h.
Constructor & Destructor Documentation
MultiModelSpectrumChannel()
ns3::MultiModelSpectrumChannel::MultiModelSpectrumChannel ()
Definition at line 81 of file multi-model-spectrum-channel.cc.
Member Function Documentation
AddRx()
void ns3::MultiModelSpectrumChannel::AddRx (Ptr< SpectrumPhy > phy) virtual
Add a SpectrumPhy to a channel, so it can receive packets.
This method is used to attach a SpectrumPhy instance to a SpectrumChannel instance, so that the SpectrumPhy can receive packets sent on that channel. Note that a SpectrumPhy that only transmits (without receiving ever) does not need to be added to the channel.
This method is to be implemented by all classes inheriting from SpectrumChannel.
Parameters
phy the SpectrumPhy instance to be added to the channel as a receiver.
Implements ns3::SpectrumChannel.
Definition at line 109 of file multi-model-spectrum-channel.cc.
References ns3::SpectrumModel::GetUid(), ns3::SpectrumModel::IsOrthogonal(), m_numDevices, m_rxSpectrumModelInfoMap, m_txSpectrumModelInfoMap, NS_ASSERT, NS_ASSERT_MSG(), NS_LOG_FUNCTION, NS_LOG_LOGIC(), and third::phy.
DoDispose()
void ns3::MultiModelSpectrumChannel::DoDispose () protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::SpectrumChannel.
Definition at line 88 of file multi-model-spectrum-channel.cc.
References ns3::SpectrumChannel::DoDispose(), m_rxSpectrumModelInfoMap, m_txSpectrumModelInfoMap, and NS_LOG_FUNCTION.
FindAndEventuallyAddTxSpectrumModel()
TxSpectrumModelInfoMap_t::const_iterator ns3::MultiModelSpectrumChannel::FindAndEventuallyAddTxSpectrumModel (Ptr< const SpectrumModel > txSpectrumModel) private
This method checks if m_rxSpectrumModelInfoMap contains an entry for the given TX SpectrumModel.
If such entry exists, it returns an iterator pointing to it. If not, it creates a new entry in m_txSpectrumMpodelInfoMap, and returns an iterator to it.
Parameters
txSpectrumModel The TX SpectrumModel being considered
Returns
An iterator pointing to the corresponding entry in m_txSpectrumModelInfoMap
Definition at line 175 of file multi-model-spectrum-channel.cc.
References ns3::SpectrumModel::GetUid(), ns3::SpectrumModel::IsOrthogonal(), m_rxSpectrumModelInfoMap, m_txSpectrumModelInfoMap, NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_LOGIC().
Referenced by StartTx().
GetDevice()
Ptr< NetDevice > ns3::MultiModelSpectrumChannel::GetDevice (std::size_t i) const virtual
Parameters
i index of NetDevice to retrieve
Returns
one of the NetDevices connected to this channel.
This method must be implemented by subclasses.
Implements ns3::Channel.
Definition at line 365 of file multi-model-spectrum-channel.cc.
References m_numDevices, m_rxSpectrumModelInfoMap, NS_ASSERT, and NS_FATAL_ERROR.
GetNDevices()
std::size_t ns3::MultiModelSpectrumChannel::GetNDevices (void) const virtual
Returns
the number of NetDevices connected to this Channel.
This method must be implemented by subclasses.
Implements ns3::Channel.
Definition at line 359 of file multi-model-spectrum-channel.cc.
References m_numDevices.
GetTypeId()
TypeId ns3::MultiModelSpectrumChannel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 97 of file multi-model-spectrum-channel.cc.
References ns3::TypeId::SetParent().
StartRx()
void ns3::MultiModelSpectrumChannel::StartRx (Ptr< SpectrumSignalParameters > params, Ptr< SpectrumPhy > receiver) private virtual
Used internally to reschedule transmission after the propagation delay.
Parameters
params The signal parameters.
receiver A pointer to the receiver SpectrumPhy.
Definition at line 352 of file multi-model-spectrum-channel.cc.
References NS_LOG_FUNCTION, aloha::params, and ns3::SpectrumPhy::StartRx().
Referenced by StartTx().
StartTx()
void ns3::MultiModelSpectrumChannel::StartTx (Ptr< SpectrumSignalParameters > params) virtual
Used by attached PHY instances to transmit signals on the channel.
Parameters
params the parameters of the signals being transmitted
Implements ns3::SpectrumChannel.
Definition at line 217 of file multi-model-spectrum-channel.cc.
References ns3::PropagationLossModel::CalcRxPower(), FindAndEventuallyAddTxSpectrumModel(), ns3::MobilityModel::GetPosition(), ns3::SpectrumChannel::m_gainTrace, ns3::SpectrumChannel::m_maxLossDb, ns3::SpectrumChannel::m_pathLossTrace, ns3::SpectrumChannel::m_propagationDelay, ns3::SpectrumChannel::m_propagationLoss, m_rxSpectrumModelInfoMap, ns3::SpectrumChannel::m_spectrumPropagationLoss, ns3::SpectrumChannel::m_txSigParamsTrace, m_txSpectrumModelInfoMap, ns3::MicroSeconds(), NS_ASSERT, NS_ASSERT_MSG(), NS_LOG_FUNCTION, NS_LOG_LOGIC(), ns3::Simulator::Schedule(), ns3::Simulator::ScheduleWithContext(), and StartRx().
Member Data Documentation
m_numDevices
std::size_t ns3::MultiModelSpectrumChannel::m_numDevices private
Number of devices connected to the channel.
Definition at line 170 of file multi-model-spectrum-channel.h.
Referenced by AddRx(), GetDevice(), and GetNDevices().
m_rxSpectrumModelInfoMap
RxSpectrumModelInfoMap_t ns3::MultiModelSpectrumChannel::m_rxSpectrumModelInfoMap private
Data structure holding, for each RX spectrum model, all the corresponding SpectrumPhy instances.
Definition at line 165 of file multi-model-spectrum-channel.h.
Referenced by AddRx(), DoDispose(), FindAndEventuallyAddTxSpectrumModel(), GetDevice(), and StartTx().
m_txSpectrumModelInfoMap
TxSpectrumModelInfoMap_t ns3::MultiModelSpectrumChannel::m_txSpectrumModelInfoMap private
Data structure holding, for each TX SpectrumModel, all the converters to any RX SpectrumModel, and all the corresponding SpectrumPhy instances.
Definition at line 158 of file multi-model-spectrum-channel.h.
Referenced by AddRx(), DoDispose(), FindAndEventuallyAddTxSpectrumModel(), and StartTx().
The documentation for this class was generated from the following files:
src/spectrum/model/multi-model-spectrum-channel.h
src/spectrum/model/multi-model-spectrum-channel.cc