ns-3: ns3::Ucd Class Reference
ns3::Ucd Class Reference
This class implements the UCD message as described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems" 6.3.2.3.3 Uplink Channel Descriptor (UCD) message, page 47.
#include "ul-mac-messages.h"
Public Member Functions
Ucd (void)
virtual ~Ucd (void)
void AddUlBurstProfile (OfdmUlBurstProfile ulBurstProfile)
Add UL burst profile.
uint32_t Deserialize (Buffer::Iterator start)
OfdmUcdChannelEncodings GetChannelEncodings (void) const
Get channel encodings.
uint8_t GetConfigurationChangeCount (void) const
Get configuration change count.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
std::string GetName (void) const
Get name.
uint8_t GetNrUlBurstProfiles (void) const
Get number UL burst profiles.
uint8_t GetRangingBackoffEnd (void) const
Get ranging backoff end.
uint8_t GetRangingBackoffStart (void) const
Get ranging backoff start.
uint8_t GetRequestBackoffEnd (void) const
Get request backoff end.
uint8_t GetRequestBackoffStart (void) const
Get request backoff start.
uint32_t GetSerializedSize (void) const
std::vector< OfdmUlBurstProfile > GetUlBurstProfiles (void) const
Get UL burst profiles.
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetChannelEncodings (OfdmUcdChannelEncodings channelEncodings)
Set channel encodings.
void SetConfigurationChangeCount (uint8_t ucdCount)
Set configuration change count.
void SetNrUlBurstProfiles (uint8_t nrUlBurstProfiles)
Set NR UL burst profiles.
void SetRangingBackoffEnd (uint8_t rangingBackoffEnd)
Set ranging backoff end.
void SetRangingBackoffStart (uint8_t rangingBackoffStart)
Set ranging backoff start.
void SetRequestBackoffEnd (uint8_t requestBackoffEnd)
Set request backoff end.
void SetRequestBackoffStart (uint8_t requestBackoffStart)
Set request backoff start.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
OfdmUcdChannelEncodings m_channelEncodings
TLV Encoded information for the overall channel.
uint8_t m_configurationChangeCount
configuration change count
uint8_t m_nrUlBurstProfiles
number UL burst profiles
uint8_t m_rangingBackoffEnd
ranging backoff end
uint8_t m_rangingBackoffStart
ranging backoff start
uint8_t m_requestBackoffEnd
request backoff end
uint8_t m_requestBackoffStart
request backoff start
std::vector< OfdmUlBurstProfile > m_ulBurstProfiles
UL burst profiles.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class implements the UCD message as described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems" 6.3.2.3.3 Uplink Channel Descriptor (UCD) message, page 47.
Definition at line 317 of file ul-mac-messages.h.
Constructor & Destructor Documentation
Ucd()
ns3::Ucd::Ucd (void)
Definition at line 256 of file ul-mac-messages.cc.
~Ucd()
ns3::Ucd::~Ucd (void) virtual
Definition at line 267 of file ul-mac-messages.cc.
Member Function Documentation
AddUlBurstProfile()
void ns3::Ucd::AddUlBurstProfile (OfdmUlBurstProfile ulBurstProfile)
Add UL burst profile.
Parameters
ulBurstProfile the UL burst profile
Definition at line 308 of file ul-mac-messages.cc.
References m_ulBurstProfiles.
Referenced by Deserialize(), and ns3::BaseStationNetDevice::SetUlBurstProfiles().
Deserialize()
uint32_t ns3::Ucd::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 438 of file ul-mac-messages.cc.
References AddUlBurstProfile(), ns3::Buffer::Iterator::GetDistanceFrom(), m_channelEncodings, m_configurationChangeCount, m_nrUlBurstProfiles, m_rangingBackoffEnd, m_rangingBackoffStart, m_requestBackoffEnd, m_requestBackoffStart, ns3::UcdChannelEncodings::Read(), ns3::OfdmUlBurstProfile::Read(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetChannelEncodings()
OfdmUcdChannelEncodings ns3::Ucd::GetChannelEncodings (void) const
Get channel encodings.
Returns
the OFDM UCD channel encodings
Definition at line 351 of file ul-mac-messages.cc.
References m_channelEncodings.
Referenced by ns3::SubscriberStationNetDevice::ProcessUcd().
GetConfigurationChangeCount()
uint8_t ns3::Ucd::GetConfigurationChangeCount (void) const
Get configuration change count.
Returns
the configuration change count
Definition at line 321 of file ul-mac-messages.cc.
References m_configurationChangeCount.
Referenced by ns3::SubscriberStationNetDevice::ProcessUcd().
GetInstanceTypeId()
TypeId ns3::Ucd::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 386 of file ul-mac-messages.cc.
References GetTypeId().
GetName()
std::string ns3::Ucd::GetName (void) const
Get name.
Returns
the name string
Definition at line 369 of file ul-mac-messages.cc.
GetNrUlBurstProfiles()
uint8_t ns3::Ucd::GetNrUlBurstProfiles (void) const
Get number UL burst profiles.
Returns
the number of UL burst profiles
Definition at line 363 of file ul-mac-messages.cc.
References m_nrUlBurstProfiles.
GetRangingBackoffEnd()
uint8_t ns3::Ucd::GetRangingBackoffEnd (void) const
Get ranging backoff end.
Returns
the ranging backoff end value
Definition at line 333 of file ul-mac-messages.cc.
References m_rangingBackoffEnd.
GetRangingBackoffStart()
uint8_t ns3::Ucd::GetRangingBackoffStart (void) const
Get ranging backoff start.
Returns
the ranging backoff start
Definition at line 327 of file ul-mac-messages.cc.
References m_rangingBackoffStart.
Referenced by ns3::SubscriberStationNetDevice::ProcessUcd().
GetRequestBackoffEnd()
uint8_t ns3::Ucd::GetRequestBackoffEnd (void) const
Get request backoff end.
Returns
the request backoff end value
Definition at line 345 of file ul-mac-messages.cc.
References m_requestBackoffEnd.
GetRequestBackoffStart()
uint8_t ns3::Ucd::GetRequestBackoffStart (void) const
Get request backoff start.
Returns
the request backoff start value
Definition at line 339 of file ul-mac-messages.cc.
References m_requestBackoffStart.
GetSerializedSize()
uint32_t ns3::Ucd::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 404 of file ul-mac-messages.cc.
References ns3::OfdmUcdChannelEncodings::GetSize(), ns3::OfdmUlBurstProfile::GetSize(), m_channelEncodings, and m_ulBurstProfiles.
GetTypeId()
TypeId ns3::Ucd::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 375 of file ul-mac-messages.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
GetUlBurstProfiles()
std::vector< OfdmUlBurstProfile > ns3::Ucd::GetUlBurstProfiles (void) const
Get UL burst profiles.
Returns
the UL burst profile
Definition at line 357 of file ul-mac-messages.cc.
References m_ulBurstProfiles.
Referenced by ns3::SubscriberStationNetDevice::ProcessUcd().
Print()
void ns3::Ucd::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 392 of file ul-mac-messages.cc.
References m_configurationChangeCount, m_rangingBackoffEnd, m_rangingBackoffStart, m_requestBackoffEnd, m_requestBackoffStart, and m_ulBurstProfiles.
Serialize()
void ns3::Ucd::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 419 of file ul-mac-messages.cc.
References m_channelEncodings, m_configurationChangeCount, m_rangingBackoffEnd, m_rangingBackoffStart, m_requestBackoffEnd, m_requestBackoffStart, m_ulBurstProfiles, visualizer.core::start(), ns3::UcdChannelEncodings::Write(), ns3::OfdmUlBurstProfile::Write(), and ns3::Buffer::Iterator::WriteU8().
SetChannelEncodings()
void ns3::Ucd::SetChannelEncodings (OfdmUcdChannelEncodings channelEncodings)
Set channel encodings.
Parameters
channelEncodings the channel encodings
Definition at line 302 of file ul-mac-messages.cc.
References m_channelEncodings.
Referenced by ns3::BaseStationNetDevice::CreateUcd().
SetConfigurationChangeCount()
void ns3::Ucd::SetConfigurationChangeCount (uint8_t ucdCount)
Set configuration change count.
Parameters
ucdCount the UCD count
Definition at line 272 of file ul-mac-messages.cc.
References m_configurationChangeCount.
Referenced by ns3::BaseStationNetDevice::CreateUcd().
SetNrUlBurstProfiles()
void ns3::Ucd::SetNrUlBurstProfiles (uint8_t nrUlBurstProfiles)
Set NR UL burst profiles.
Parameters
nrUlBurstProfiles the NR UL burst profiles
Definition at line 314 of file ul-mac-messages.cc.
References m_nrUlBurstProfiles.
Referenced by ns3::SubscriberStationNetDevice::DoReceive().
SetRangingBackoffEnd()
void ns3::Ucd::SetRangingBackoffEnd (uint8_t rangingBackoffEnd)
Set ranging backoff end.
Parameters
rangingBackoffEnd the ranging backoff end
Definition at line 284 of file ul-mac-messages.cc.
References m_rangingBackoffEnd.
Referenced by ns3::BaseStationNetDevice::CreateUcd().
SetRangingBackoffStart()
void ns3::Ucd::SetRangingBackoffStart (uint8_t rangingBackoffStart)
Set ranging backoff start.
Parameters
rangingBackoffStart ranging backoff start
Definition at line 278 of file ul-mac-messages.cc.
References m_rangingBackoffStart.
Referenced by ns3::BaseStationNetDevice::CreateUcd().
SetRequestBackoffEnd()
void ns3::Ucd::SetRequestBackoffEnd (uint8_t requestBackoffEnd)
Set request backoff end.
Parameters
requestBackoffEnd the request backoff end
Definition at line 296 of file ul-mac-messages.cc.
References m_requestBackoffEnd.
Referenced by ns3::BaseStationNetDevice::CreateUcd().
SetRequestBackoffStart()
void ns3::Ucd::SetRequestBackoffStart (uint8_t requestBackoffStart)
Set request backoff start.
Parameters
requestBackoffStart the request backoff start
Definition at line 290 of file ul-mac-messages.cc.
References m_requestBackoffStart.
Referenced by ns3::BaseStationNetDevice::CreateUcd().
Member Data Documentation
m_channelEncodings
OfdmUcdChannelEncodings ns3::Ucd::m_channelEncodings private
TLV Encoded information for the overall channel.
Definition at line 426 of file ul-mac-messages.h.
Referenced by Deserialize(), GetChannelEncodings(), GetSerializedSize(), Serialize(), and SetChannelEncodings().
m_configurationChangeCount
uint8_t ns3::Ucd::m_configurationChangeCount private
configuration change count
Definition at line 421 of file ul-mac-messages.h.
Referenced by Deserialize(), GetConfigurationChangeCount(), Print(), Serialize(), and SetConfigurationChangeCount().
m_nrUlBurstProfiles
uint8_t ns3::Ucd::m_nrUlBurstProfiles private
number UL burst profiles
Definition at line 429 of file ul-mac-messages.h.
Referenced by Deserialize(), GetNrUlBurstProfiles(), and SetNrUlBurstProfiles().
m_rangingBackoffEnd
uint8_t ns3::Ucd::m_rangingBackoffEnd private
ranging backoff end
Definition at line 423 of file ul-mac-messages.h.
Referenced by Deserialize(), GetRangingBackoffEnd(), Print(), Serialize(), and SetRangingBackoffEnd().
m_rangingBackoffStart
uint8_t ns3::Ucd::m_rangingBackoffStart private
ranging backoff start
Definition at line 422 of file ul-mac-messages.h.
Referenced by Deserialize(), GetRangingBackoffStart(), Print(), Serialize(), and SetRangingBackoffStart().
m_requestBackoffEnd
uint8_t ns3::Ucd::m_requestBackoffEnd private
request backoff end
Definition at line 425 of file ul-mac-messages.h.
Referenced by Deserialize(), GetRequestBackoffEnd(), Print(), Serialize(), and SetRequestBackoffEnd().
m_requestBackoffStart
uint8_t ns3::Ucd::m_requestBackoffStart private
request backoff start
Definition at line 424 of file ul-mac-messages.h.
Referenced by Deserialize(), GetRequestBackoffStart(), Print(), Serialize(), and SetRequestBackoffStart().
m_ulBurstProfiles
std::vector<OfdmUlBurstProfile> ns3::Ucd::m_ulBurstProfiles private
UL burst profiles.
Definition at line 427 of file ul-mac-messages.h.
Referenced by AddUlBurstProfile(), GetSerializedSize(), GetUlBurstProfiles(), Print(), and Serialize().
The documentation for this class was generated from the following files:
src/wimax/model/ul-mac-messages.h
src/wimax/model/ul-mac-messages.cc