ns-3: ns3::YansWifiPhyHelper Class Reference
ns3::YansWifiPhyHelper Class Reference
Make it easy to create and manage PHY objects for the YANS model.
#include "yans-wifi-helper.h"
Public Member Functions
YansWifiPhyHelper ()
Create a PHY helper without any parameter set.
void SetChannel (Ptr< YansWifiChannel > channel)
void SetChannel (std::string channelName)
Public Member Functions inherited from ns3::WifiPhyHelper
WifiPhyHelper ()
virtual ~WifiPhyHelper ()
void DisablePreambleDetectionModel ()
Disable the preamble detection model.
PcapHelper::DataLinkType GetPcapDataLinkType (void) const
Get the data link type of PCAP traces to be used.
void Set (std::string name, const AttributeValue &v)
void SetErrorRateModel (std::string name, std::string n0="", const AttributeValue &v0=EmptyAttributeValue(), std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue(), std::string n6="", const AttributeValue &v6=EmptyAttributeValue(), std::string n7="", const AttributeValue &v7=EmptyAttributeValue())
void SetFrameCaptureModel (std::string name, std::string n0="", const AttributeValue &v0=EmptyAttributeValue(), std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue(), std::string n6="", const AttributeValue &v6=EmptyAttributeValue(), std::string n7="", const AttributeValue &v7=EmptyAttributeValue())
void SetPcapDataLinkType (SupportedPcapDataLinkTypes dlt)
Set the data link type of PCAP traces to be used.
void SetPreambleDetectionModel (std::string name, std::string n0="", const AttributeValue &v0=EmptyAttributeValue(), std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue(), std::string n6="", const AttributeValue &v6=EmptyAttributeValue(), std::string n7="", const AttributeValue &v7=EmptyAttributeValue())
Public Member Functions inherited from ns3::PcapHelperForDevice
PcapHelperForDevice ()
Construct a PcapHelperForDevice.
virtual ~PcapHelperForDevice ()
Destroy a PcapHelperForDevice.
void EnablePcap (std::string prefix, NetDeviceContainer d, bool promiscuous=false)
Enable pcap output on each device in the container which is of the appropriate type.
void EnablePcap (std::string prefix, NodeContainer n, bool promiscuous=false)
Enable pcap output on each device (which is of the appropriate type) in the nodes provided in the container.
void EnablePcap (std::string prefix, Ptr< NetDevice > nd, bool promiscuous=false, bool explicitFilename=false)
Enable pcap output the indicated net device.
void EnablePcap (std::string prefix, std::string ndName, bool promiscuous=false, bool explicitFilename=false)
Enable pcap output the indicated net device using a device previously named using the ns-3 object name service.
void EnablePcap (std::string prefix, uint32_t nodeid, uint32_t deviceid, bool promiscuous=false)
Enable pcap output on the device specified by a global node-id (of a previously created node) and associated device-id.
void EnablePcapAll (std::string prefix, bool promiscuous=false)
Enable pcap output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
Public Member Functions inherited from ns3::AsciiTraceHelperForDevice
AsciiTraceHelperForDevice ()
Construct an AsciiTraceHelperForDevice.
virtual ~AsciiTraceHelperForDevice ()
Destroy an AsciiTraceHelperForDevice.
void EnableAscii (Ptr< OutputStreamWrapper > stream, NetDeviceContainer d)
Enable ascii trace output on each device in the container which is of the appropriate type.
void EnableAscii (Ptr< OutputStreamWrapper > stream, NodeContainer n)
Enable ascii trace output on each device (which is of the appropriate type) in the nodes provided in the container.
void EnableAscii (Ptr< OutputStreamWrapper > stream, Ptr< NetDevice > nd)
Enable ascii trace output on the indicated net device.
void EnableAscii (Ptr< OutputStreamWrapper > stream, std::string ndName)
Enable ascii trace output the indicated net device using a device previously named using the ns-3 object name service.
void EnableAscii (Ptr< OutputStreamWrapper > stream, uint32_t nodeid, uint32_t deviceid)
Enable ascii trace output on the device specified by a global node-id (of a previously created node) and associated device-id.
void EnableAscii (std::string prefix, NetDeviceContainer d)
Enable ascii trace output on each device in the container which is of the appropriate type.
void EnableAscii (std::string prefix, NodeContainer n)
Enable ascii trace output on each device (which is of the appropriate type) in the nodes provided in the container.
void EnableAscii (std::string prefix, Ptr< NetDevice > nd, bool explicitFilename=false)
Enable ascii trace output on the indicated net device.
void EnableAscii (std::string prefix, std::string ndName, bool explicitFilename=false)
Enable ascii trace output the indicated net device using a device previously named using the ns-3 object name service.
void EnableAscii (std::string prefix, uint32_t nodeid, uint32_t deviceid, bool explicitFilename)
Enable ascii trace output on the device specified by a global node-id (of a previously created node) and associated device-id.
void EnableAsciiAll (Ptr< OutputStreamWrapper > stream)
Enable ascii trace output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
void EnableAsciiAll (std::string prefix)
Enable ascii trace output on each device (which is of the appropriate type) in the set of all nodes created in the simulation.
Static Public Member Functions
static YansWifiPhyHelper Default (void)
Create a PHY helper in a default working state.
Private Member Functions
virtual Ptr< WifiPhy > Create (Ptr< Node > node, Ptr< NetDevice > device) const
Private Attributes
Ptr< YansWifiChannel > m_channel
YANS wifi channel.
Additional Inherited Members
Public Types inherited from ns3::WifiPhyHelper
enum SupportedPcapDataLinkTypes { DLT_IEEE802_11 = PcapHelper::DLT_IEEE802_11, DLT_PRISM_HEADER = PcapHelper::DLT_PRISM_HEADER, DLT_IEEE802_11_RADIO = PcapHelper::DLT_IEEE802_11_RADIO }
An enumeration of the pcap data link types (DLTs) which this helper supports.
Static Protected Member Functions inherited from ns3::WifiPhyHelper
static void PcapSniffRxEvent (Ptr< PcapFileWrapper > file, Ptr< const Packet > packet, uint16_t channelFreqMhz, WifiTxVector txVector, MpduInfo aMpdu, SignalNoiseDbm signalNoise)
static void PcapSniffTxEvent (Ptr< PcapFileWrapper > file, Ptr< const Packet > packet, uint16_t channelFreqMhz, WifiTxVector txVector, MpduInfo aMpdu)
Protected Attributes inherited from ns3::WifiPhyHelper
ObjectFactory m_errorRateModel
error rate model
ObjectFactory m_frameCaptureModel
frame capture model
ObjectFactory m_phy
PHY object.
ObjectFactory m_preambleDetectionModel
preamble detection model
Detailed Description
Make it easy to create and manage PHY objects for the YANS model.
The YANS PHY model is described in "Yet Another Network Simulator", http://cutebugs.net/files/wns2-yans.pdf
The Pcap and ASCII traces generated by the EnableAscii and EnablePcap methods defined in this class correspond to PHY-level traces and come to us via WifiPhyHelper
Definition at line 160 of file yans-wifi-helper.h.
Constructor & Destructor Documentation
YansWifiPhyHelper()
ns3::YansWifiPhyHelper::YansWifiPhyHelper ()
Create a PHY helper without any parameter set.
The user must set them all to be able to call Install later.
Definition at line 126 of file yans-wifi-helper.cc.
References ns3::WifiPhyHelper::m_phy, and ns3::ObjectFactory::SetTypeId().
Member Function Documentation
Create()
Ptr< WifiPhy > ns3::YansWifiPhyHelper::Create (Ptr< Node > node, Ptr< NetDevice > device) const private virtual
Parameters
node the node on which we wish to create a wifi PHY
device the device within which this PHY will be created
Returns
a newly-created PHY object.
This method implements the pure virtual method defined in ns3::WifiPhyHelper.
Implements ns3::WifiPhyHelper.
Definition at line 154 of file yans-wifi-helper.cc.
References ns3::ObjectFactory::Create(), ns3::ObjectFactory::IsTypeIdSet(), m_channel, ns3::WifiPhyHelper::m_errorRateModel, ns3::WifiPhyHelper::m_frameCaptureModel, ns3::WifiPhyHelper::m_phy, ns3::WifiPhyHelper::m_preambleDetectionModel, and third::phy.
Default()
YansWifiPhyHelper ns3::YansWifiPhyHelper::Default (void) static
Create a PHY helper in a default working state.
Returns
a default YansWifiPhyHelper
Definition at line 133 of file yans-wifi-helper.cc.
References ns3::WifiPhyHelper::SetErrorRateModel().
Referenced by BatteryLifetimeTest::ConstantLoadTest(), BasicEnergyDepletionTest::DepletionTestCase(), ns3::aodv::LoopbackTestCase::DoRun(), experiment(), Experiment::Run(), and BatteryLifetimeTest::VariableLoadTest().
SetChannel() [1/2]
void ns3::YansWifiPhyHelper::SetChannel (Ptr< YansWifiChannel > channel)
Parameters
channel the channel to associate to this helper
Every PHY created by a call to Install is associated to this channel.
Definition at line 141 of file yans-wifi-helper.cc.
References third::channel, and m_channel.
Referenced by OcbWifiMacTestCase::ConfigureAdhocMode(), OcbWifiMacTestCase::ConfigureApStaMode(), OcbWifiMacTestCase::ConfigureOcbMode(), BatteryLifetimeTest::ConstantLoadTest(), AodvExample::CreateDevices(), ChainRegressionTest::CreateDevices(), Bug772ChainTest::CreateDevices(), TracerouteExample::CreateDevices(), HwmpProactiveRegressionTest::CreateDevices(), HwmpReactiveRegressionTest::CreateDevices(), HwmpSimplestRegressionTest::CreateDevices(), HwmpDoRfRegressionTest::CreateDevices(), PeerManagementProtocolRegressionTest::CreateDevices(), FlameRegressionTest::CreateDevices(), DsdvManetExample::CreateDevices(), MeshTest::CreateNodes(), WaveNetDeviceExample::CreateWaveNodes(), TestCaseHelper::CreatWaveDevice(), BasicEnergyDepletionTest::DepletionTestCase(), ns3::aodv::LoopbackTestCase::DoRun(), WifiAcMappingTest::DoRun(), WifiMsduAggregatorThroughputTest::DoRun(), experiment(), RoutingExperiment::Run(), VanetRoutingExperiment::SetupAdhocDevices(), BatteryLifetimeTest::VariableLoadTest(), and WifiInterferenceTestCase::WifiSimpleInterference().
SetChannel() [2/2]
void ns3::YansWifiPhyHelper::SetChannel (std::string channelName)
Parameters
channelName The name of the channel to associate to this helper
Every PHY created by a call to Install is associated to this channel.
Definition at line 147 of file yans-wifi-helper.cc.
References third::channel, and m_channel.
Member Data Documentation
m_channel
Ptr<YansWifiChannel> ns3::YansWifiPhyHelper::m_channel private
YANS wifi channel.
Definition at line 198 of file yans-wifi-helper.h.
Referenced by Create(), and SetChannel().
The documentation for this class was generated from the following files:
src/wifi/helper/yans-wifi-helper.h
src/wifi/helper/yans-wifi-helper.cc