ns-3: ns3::WaveformGenerator Class Reference
ns3::WaveformGenerator Class Reference
Spectrum Models
#include "waveform-generator.h"
Public Member Functions
WaveformGenerator ()
virtual ~WaveformGenerator ()
Ptr< NetDevice > GetDevice () const
Get the associated NetDevice instance.
double GetDutyCycle () const
Ptr< MobilityModel > GetMobility ()
Get the associated MobilityModel instance.
Time GetPeriod () const
Ptr< AntennaModel > GetRxAntenna ()
Get the AntennaModel used by the NetDevice for reception.
Ptr< const SpectrumModel > GetRxSpectrumModel () const
void SetAntenna (Ptr< AntennaModel > a)
set the AntennaModel to be used
void SetChannel (Ptr< SpectrumChannel > c)
Set the channel attached to this device.
void SetDevice (Ptr< NetDevice > d)
Set the associated NetDevice instance.
void SetDutyCycle (double value)
void SetMobility (Ptr< MobilityModel > m)
Set the mobility model associated with this device.
void SetPeriod (Time period)
Set the period according to which the WaveformGenerator switches on and off.
void SetTxPowerSpectralDensity (Ptr< SpectrumValue > txs)
Set the Power Spectral Density used for outgoing waveforms.
virtual void Start ()
Start the waveform generator.
void StartRx (Ptr< SpectrumSignalParameters > params)
Notify the SpectrumPhy instance of an incoming signal.
virtual void Stop ()
Stop the waveform generator.
Public Member Functions inherited from ns3::SpectrumPhy
SpectrumPhy ()
virtual ~SpectrumPhy ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::SpectrumPhy
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual void DoDispose (void)
Destructor implementation.
virtual void GenerateWaveform ()
Generates a waveform.
Private Attributes
Ptr< AntennaModel > m_antenna
Antenna model.
Ptr< SpectrumChannel > m_channel
Channel.
double m_dutyCycle
Duty Cycle (should be in [0,1])
Ptr< MobilityModel > m_mobility
Mobility model.
Ptr< NetDevice > m_netDevice
Owning NetDevice.
EventId m_nextWave
Next waveform generation event.
Time m_period
Period.
TracedCallback< Ptr< const Packet > > m_phyTxEndTrace
TracedCallback: Tx end.
TracedCallback< Ptr< const Packet > > m_phyTxStartTrace
TracedCallback: Tx start.
Time m_startTime
Start time.
Ptr< SpectrumValue > m_txPowerSpectralDensity
Tx PSD.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Simple SpectrumPhy implementation that sends customizable waveform. The generated waveforms have a given Spectrum Power Density and duration (set with the SetResolution()) . The generator activates and deactivates periodically with a given period and with a duty cycle of 1/2.
This PHY model supports a single antenna model instance which is used for both transmission and reception (though received signals are discarded by this PHY).
Definition at line 53 of file waveform-generator.h.
Constructor & Destructor Documentation
WaveformGenerator()
ns3::WaveformGenerator::WaveformGenerator ()
Definition at line 37 of file waveform-generator.cc.
~WaveformGenerator()
ns3::WaveformGenerator::~WaveformGenerator () virtual
Definition at line 48 of file waveform-generator.cc.
Member Function Documentation
DoDispose()
void ns3::WaveformGenerator::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 55 of file waveform-generator.cc.
References ns3::EventId::Cancel(), ns3::EventId::IsRunning(), m_channel, m_mobility, m_netDevice, m_nextWave, and NS_LOG_FUNCTION.
GenerateWaveform()
void ns3::WaveformGenerator::GenerateWaveform () private virtual
Generates a waveform.
Definition at line 198 of file waveform-generator.cc.
References ns3::Time::GetTimeStep(), m_antenna, m_channel, m_dutyCycle, m_nextWave, m_period, m_phyTxStartTrace, m_txPowerSpectralDensity, NS_LOG_FUNCTION, NS_LOG_LOGIC(), and ns3::Simulator::Schedule().
Referenced by Start().
GetDevice()
Ptr< NetDevice > ns3::WaveformGenerator::GetDevice () const virtual
Get the associated NetDevice instance.
Returns
a Ptr to the associated NetDevice instance
Implements ns3::SpectrumPhy.
Definition at line 101 of file waveform-generator.cc.
References m_netDevice.
GetDutyCycle()
double ns3::WaveformGenerator::GetDutyCycle () const
Returns
the value of the duty cycle
Definition at line 190 of file waveform-generator.cc.
References m_dutyCycle.
Referenced by GetTypeId().
GetMobility()
Ptr< MobilityModel > ns3::WaveformGenerator::GetMobility () virtual
Get the associated MobilityModel instance.
Returns
a Ptr to the associated MobilityModel instance
Implements ns3::SpectrumPhy.
Definition at line 108 of file waveform-generator.cc.
References m_mobility.
GetPeriod()
Time ns3::WaveformGenerator::GetPeriod () const
Returns
the value of the period according to which the WaveformGenerator switches on and off
Definition at line 177 of file waveform-generator.cc.
References m_period.
Referenced by GetTypeId().
GetRxAntenna()
Ptr< AntennaModel > ns3::WaveformGenerator::GetRxAntenna () virtual
Get the AntennaModel used by the NetDevice for reception.
Returns
a Ptr to the AntennaModel used by the NetDevice for reception
Implements ns3::SpectrumPhy.
Definition at line 158 of file waveform-generator.cc.
References m_antenna.
GetRxSpectrumModel()
Ptr< const SpectrumModel > ns3::WaveformGenerator::GetRxSpectrumModel () const virtual
Returns
returns the SpectrumModel that this SpectrumPhy expects to be used for all SpectrumValues that are passed to StartRx. If 0 is returned, it means that any model will be accepted.
Implements ns3::SpectrumPhy.
Definition at line 115 of file waveform-generator.cc.
GetTypeId()
TypeId ns3::WaveformGenerator::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 68 of file waveform-generator.cc.
References GetDutyCycle(), GetPeriod(), m_phyTxEndTrace, m_phyTxStartTrace, ns3::MakeDoubleAccessor(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::Seconds(), SetDutyCycle(), ns3::TypeId::SetParent(), and SetPeriod().
SetAntenna()
void ns3::WaveformGenerator::SetAntenna (Ptr< AntennaModel > a)
set the AntennaModel to be used
Parameters
a the Antenna Model
Definition at line 164 of file waveform-generator.cc.
References m_antenna, and NS_LOG_FUNCTION.
SetChannel()
void ns3::WaveformGenerator::SetChannel (Ptr< SpectrumChannel > c) virtual
Set the channel attached to this device.
Parameters
c the channel
Implements ns3::SpectrumPhy.
Definition at line 136 of file waveform-generator.cc.
References m_channel, and NS_LOG_FUNCTION_NOARGS.
SetDevice()
void ns3::WaveformGenerator::SetDevice (Ptr< NetDevice > d) virtual
Set the associated NetDevice instance.
Parameters
d the NetDevice instance
Implements ns3::SpectrumPhy.
Definition at line 122 of file waveform-generator.cc.
References m_netDevice.
SetDutyCycle()
void ns3::WaveformGenerator::SetDutyCycle (double value)
Parameters
value the value of the duty cycle
Definition at line 185 of file waveform-generator.cc.
References m_dutyCycle.
Referenced by GetTypeId().
SetMobility()
void ns3::WaveformGenerator::SetMobility (Ptr< MobilityModel > m) virtual
Set the mobility model associated with this device.
Parameters
m the mobility model
Implements ns3::SpectrumPhy.
Definition at line 129 of file waveform-generator.cc.
References m_mobility.
SetPeriod()
void ns3::WaveformGenerator::SetPeriod (Time period)
Set the period according to which the WaveformGenerator switches on and off.
Parameters
period
Definition at line 171 of file waveform-generator.cc.
References m_period.
Referenced by GetTypeId().
SetTxPowerSpectralDensity()
void ns3::WaveformGenerator::SetTxPowerSpectralDensity (Ptr< SpectrumValue > txs)
Set the Power Spectral Density used for outgoing waveforms.
Parameters
txs the Power Spectral Density
Definition at line 151 of file waveform-generator.cc.
References m_txPowerSpectralDensity, and NS_LOG_FUNCTION.
Start()
void ns3::WaveformGenerator::Start () virtual
Start the waveform generator.
Definition at line 218 of file waveform-generator.cc.
References GenerateWaveform(), ns3::EventId::IsRunning(), m_nextWave, m_startTime, ns3::Now(), NS_LOG_FUNCTION, NS_LOG_LOGIC(), and ns3::Simulator::ScheduleNow().
StartRx()
void ns3::WaveformGenerator::StartRx (Ptr< SpectrumSignalParameters > params) virtual
Notify the SpectrumPhy instance of an incoming signal.
Parameters
params the parameters of the signals being received
Implements ns3::SpectrumPhy.
Definition at line 145 of file waveform-generator.cc.
References NS_LOG_FUNCTION, and aloha::params.
Stop()
void ns3::WaveformGenerator::Stop () virtual
Stop the waveform generator.
Definition at line 231 of file waveform-generator.cc.
References ns3::EventId::Cancel(), ns3::EventId::IsRunning(), m_nextWave, and NS_LOG_FUNCTION.
Member Data Documentation
m_antenna
Ptr<AntennaModel> ns3::WaveformGenerator::m_antenna private
Antenna model.
Definition at line 137 of file waveform-generator.h.
Referenced by GenerateWaveform(), GetRxAntenna(), and SetAntenna().
m_channel
Ptr<SpectrumChannel> ns3::WaveformGenerator::m_channel private
Channel.
Definition at line 139 of file waveform-generator.h.
Referenced by DoDispose(), GenerateWaveform(), and SetChannel().
m_dutyCycle
double ns3::WaveformGenerator::m_dutyCycle private
Duty Cycle (should be in [0,1])
Definition at line 148 of file waveform-generator.h.
Referenced by GenerateWaveform(), GetDutyCycle(), and SetDutyCycle().
m_mobility
Ptr<MobilityModel> ns3::WaveformGenerator::m_mobility private
Mobility model.
Definition at line 136 of file waveform-generator.h.
Referenced by DoDispose(), GetMobility(), and SetMobility().
m_netDevice
Ptr<NetDevice> ns3::WaveformGenerator::m_netDevice private
Owning NetDevice.
Definition at line 138 of file waveform-generator.h.
Referenced by DoDispose(), GetDevice(), and SetDevice().
m_nextWave
EventId ns3::WaveformGenerator::m_nextWave private
Next waveform generation event.
Definition at line 150 of file waveform-generator.h.
Referenced by DoDispose(), GenerateWaveform(), Start(), and Stop().
m_period
Time ns3::WaveformGenerator::m_period private
Period.
Definition at line 147 of file waveform-generator.h.
Referenced by GenerateWaveform(), GetPeriod(), and SetPeriod().
m_phyTxEndTrace
TracedCallback<Ptr<const Packet> > ns3::WaveformGenerator::m_phyTxEndTrace private
TracedCallback: Tx end.
Definition at line 153 of file waveform-generator.h.
Referenced by GetTypeId().
m_phyTxStartTrace
TracedCallback<Ptr<const Packet> > ns3::WaveformGenerator::m_phyTxStartTrace private
TracedCallback: Tx start.
Definition at line 152 of file waveform-generator.h.
Referenced by GenerateWaveform(), and GetTypeId().
m_startTime
Time ns3::WaveformGenerator::m_startTime private
Start time.
Definition at line 149 of file waveform-generator.h.
Referenced by Start().
m_txPowerSpectralDensity
Ptr<SpectrumValue> ns3::WaveformGenerator::m_txPowerSpectralDensity private
Tx PSD.
Definition at line 146 of file waveform-generator.h.
Referenced by GenerateWaveform(), and SetTxPowerSpectralDensity().
The documentation for this class was generated from the following files:
src/spectrum/model/waveform-generator.h
src/spectrum/model/waveform-generator.cc