ns-3: ns3::EpcX2SapUser Class Reference
ns3::EpcX2SapUser Class Reference abstract
These service primitives of this part of the X2 SAP are provided by the RRC entity and issued by the X2 entity.
#include "epc-x2-sap.h"
Public Member Functions
virtual ~EpcX2SapUser ()
virtual void RecvHandoverPreparationFailure (HandoverPreparationFailureParams params)=0
Receive handover preparation failure function.
virtual void RecvHandoverRequest (HandoverRequestParams params)=0
Receive handover request function.
virtual void RecvHandoverRequestAck (HandoverRequestAckParams params)=0
Receive handover request ack function.
virtual void RecvLoadInformation (LoadInformationParams params)=0
Receive load information function.
virtual void RecvResourceStatusUpdate (ResourceStatusUpdateParams params)=0
Receive resource status update function.
virtual void RecvSnStatusTransfer (SnStatusTransferParams params)=0
Receive SN status transfer function.
virtual void RecvUeContextRelease (UeContextReleaseParams params)=0
Receive UE context release function.
virtual void RecvUeData (UeDataParams params)=0
Receive UE data function.
Public Member Functions inherited from ns3::EpcX2Sap
virtual ~EpcX2Sap ()
Additional Inherited Members
Public Types inherited from ns3::EpcX2Sap
enum IdCause { HandoverDesirableForRadioReason, TimeCriticalHandover }
Cause ID enumeration.
enum LoadIndicator { LowLoad, MediumLoad, HighLoad, Overload }
Load Indicator as it is used in the RESOURCE STATUS UPDATE message.
enum UlInterferenceOverloadIndicationItem { HighInterference, MediumInterference, LowInterference }
UL Interference OverloadIndication as it is used in the LOAD INFORMATION message.
Static Public Attributes inherited from ns3::EpcX2Sap
static const uint16_t m_maxPdcpSn = 4096
E-RABs subject to status transfer item as it is used in the SN STATUS TRANSFER message.
Detailed Description
These service primitives of this part of the X2 SAP are provided by the RRC entity and issued by the X2 entity.
Definition at line 406 of file epc-x2-sap.h.
Constructor & Destructor Documentation
~EpcX2SapUser()
ns3::EpcX2SapUser::~EpcX2SapUser () virtual
Definition at line 39 of file epc-x2-sap.cc.
Member Function Documentation
RecvHandoverPreparationFailure()
virtual void ns3::EpcX2SapUser::RecvHandoverPreparationFailure (HandoverPreparationFailureParams params) pure virtual
Receive handover preparation failure function.
Parameters
params the handover preparation failure parameters
Implemented in ns3::EpcX2SpecificEpcX2SapUser< C >.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
RecvHandoverRequest()
virtual void ns3::EpcX2SapUser::RecvHandoverRequest (HandoverRequestParams params) pure virtual
Receive handover request function.
Parameters
params the handover request parameters
Implemented in ns3::EpcX2SpecificEpcX2SapUser< C >.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
RecvHandoverRequestAck()
virtual void ns3::EpcX2SapUser::RecvHandoverRequestAck (HandoverRequestAckParams params) pure virtual
Receive handover request ack function.
Parameters
params the handover request ack parameters
Implemented in ns3::EpcX2SpecificEpcX2SapUser< C >.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
RecvLoadInformation()
virtual void ns3::EpcX2SapUser::RecvLoadInformation (LoadInformationParams params) pure virtual
Receive load information function.
Parameters
params the load information parameters
Implemented in ns3::EpcX2SpecificEpcX2SapUser< C >.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
RecvResourceStatusUpdate()
virtual void ns3::EpcX2SapUser::RecvResourceStatusUpdate (ResourceStatusUpdateParams params) pure virtual
Receive resource status update function.
Parameters
params the resource status update parameters
Implemented in ns3::EpcX2SpecificEpcX2SapUser< C >.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
RecvSnStatusTransfer()
virtual void ns3::EpcX2SapUser::RecvSnStatusTransfer (SnStatusTransferParams params) pure virtual
Receive SN status transfer function.
Parameters
params the SN status transfer parameters
Implemented in ns3::EpcX2SpecificEpcX2SapUser< C >.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
RecvUeContextRelease()
virtual void ns3::EpcX2SapUser::RecvUeContextRelease (UeContextReleaseParams params) pure virtual
Receive UE context release function.
Parameters
params the receive UE context release parameters
Implemented in ns3::EpcX2SpecificEpcX2SapUser< C >.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
RecvUeData()
virtual void ns3::EpcX2SapUser::RecvUeData (UeDataParams params) pure virtual
Receive UE data function.
Parameters
params UE data parameters
Implemented in ns3::EpcX2SpecificEpcX2SapUser< C >.
Referenced by ns3::EpcX2::RecvFromX2uSocket().
The documentation for this class was generated from the following files:
src/lte/model/epc-x2-sap.h
src/lte/model/epc-x2-sap.cc