ns-3: ns3::BSSchedulerSimple Class Reference
ns3::BSSchedulerSimple Class Reference
WiMAX Models
#include "bs-scheduler-simple.h"
Public Member Functions
BSSchedulerSimple ()
BSSchedulerSimple (Ptr< BaseStationNetDevice > bs)
Constructor.
~BSSchedulerSimple (void)
void AddDownlinkBurst (Ptr< const WimaxConnection > connection, uint8_t diuc, WimaxPhy::ModulationType modulationType, Ptr< PacketBurst > burst)
This function adds a downlink burst to the list of downlink bursts scheduled for the next downlink sub-frame.
Ptr< PacketBurst > CreateUgsBurst (ServiceFlow *serviceFlow, WimaxPhy::ModulationType modulationType, uint32_t availableSymbols)
Creates a downlink UGS burst.
std::list< std::pair< OfdmDlMapIe *, Ptr< PacketBurst > > > * GetDownlinkBursts (void) const
This function returns all the downlink bursts scheduled for the next downlink sub-frame.
void Schedule (void)
the scheduling function for the downlink subframe.
bool SelectConnection (Ptr< WimaxConnection > &connection)
Selects a connection from the list of connections having packets to be sent .
Public Member Functions inherited from ns3::BSScheduler
BSScheduler ()
BSScheduler (Ptr< BaseStationNetDevice > bs)
Constructor.
~BSScheduler (void)
bool CheckForFragmentation (Ptr< WimaxConnection > connection, int availableSymbols, WimaxPhy::ModulationType modulationType)
Check if the packet fragmentation is possible for transport connection.
virtual Ptr< BaseStationNetDevice > GetBs (void)
Get the base station.
virtual void SetBs (Ptr< BaseStationNetDevice > bs)
Set the base station.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::BSScheduler
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
std::list< std::pair< OfdmDlMapIe *, Ptr< PacketBurst > > > * m_downlinkBursts
down link bursts
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 43 of file bs-scheduler-simple.h.
Constructor & Destructor Documentation
BSSchedulerSimple() [1/2]
ns3::BSSchedulerSimple::BSSchedulerSimple ()
Definition at line 54 of file bs-scheduler-simple.cc.
References ns3::BSScheduler::SetBs().
BSSchedulerSimple() [2/2]
ns3::BSSchedulerSimple::BSSchedulerSimple (Ptr< BaseStationNetDevice > bs)
Constructor.
Parameters
bs base station device
Definition at line 60 of file bs-scheduler-simple.cc.
References ns3::BSScheduler::SetBs().
~BSSchedulerSimple()
ns3::BSSchedulerSimple::~BSSchedulerSimple (void)
Definition at line 68 of file bs-scheduler-simple.cc.
References m_downlinkBursts, and ns3::BSScheduler::SetBs().
Member Function Documentation
AddDownlinkBurst()
void ns3::BSSchedulerSimple::AddDownlinkBurst (Ptr< const WimaxConnection > connection, uint8_t diuc, WimaxPhy::ModulationType modulationType, Ptr< PacketBurst > burst) virtual
This function adds a downlink burst to the list of downlink bursts scheduled for the next downlink sub-frame.
Parameters
connection a pointer to connection in which the burst will be sent
diuc downlink iuc
modulationType the modulation type of the burst
burst the downlink burst to add to the downlink sub frame
Implements ns3::BSScheduler.
Definition at line 89 of file bs-scheduler-simple.cc.
References m_downlinkBursts, NS_LOG_INFO, ns3::OfdmDlMapIe::SetCid(), ns3::OfdmDlMapIe::SetDiuc(), and ns3::Cid::TRANSPORT.
Referenced by Schedule().
CreateUgsBurst()
Ptr< PacketBurst > ns3::BSSchedulerSimple::CreateUgsBurst (ServiceFlow * serviceFlow, WimaxPhy::ModulationType modulationType, uint32_t availableSymbols) virtual
Creates a downlink UGS burst.
Parameters
serviceFlow the service flow of the burst
modulationType the modulation type to be used for the burst
availableSymbols maximum number of OFDM symbols to be used by the burst
Returns
a Burst (list of packets)
Implements ns3::BSScheduler.
Definition at line 329 of file bs-scheduler-simple.cc.
References ns3::BSScheduler::CheckForFragmentation(), ns3::BSScheduler::GetBs(), ns3::ServiceFlow::GetConnection(), ns3::ServiceFlow::HasPackets(), and ns3::MacHeaderType::HEADER_TYPE_GENERIC.
Referenced by Schedule().
GetDownlinkBursts()
std::list< std::pair< OfdmDlMapIe *, Ptr< PacketBurst > > > * ns3::BSSchedulerSimple::GetDownlinkBursts (void) const virtual
This function returns all the downlink bursts scheduled for the next downlink sub-frame.
Returns
all the downlink bursts scheduled for the next downlink sub-frame
Implements ns3::BSScheduler.
Definition at line 84 of file bs-scheduler-simple.cc.
References m_downlinkBursts.
GetTypeId()
TypeId ns3::BSSchedulerSimple::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 44 of file bs-scheduler-simple.cc.
References ns3::TypeId::SetParent().
Schedule()
void ns3::BSSchedulerSimple::Schedule (void) virtual
the scheduling function for the downlink subframe.
Todo:
Overflows but don't know how to fix
Implements ns3::BSScheduler.
Definition at line 110 of file bs-scheduler-simple.cc.
References AddDownlinkBurst(), ns3::Cid::BASIC, ns3::BSScheduler::CheckForFragmentation(), CreateUgsBurst(), ns3::WimaxNetDevice::DIRECTION_DOWNLINK, ns3::OfdmDlBurstProfile::DIUC_BURST_PROFILE_1, ns3::BSScheduler::GetBs(), ns3::GetSize(), ns3::MacHeaderType::HEADER_TYPE_GENERIC, m_downlinkBursts, ns3::WimaxPhy::MODULATION_TYPE_BPSK_12, ns3::Cid::MULTICAST, NS_LOG_DEBUG, ns3::Cid::PRIMARY, SelectConnection(), ns3::ServiceFlow::SF_TYPE_ALL, ns3::ServiceFlow::SF_TYPE_NONE, ns3::ServiceFlow::SF_TYPE_UGS, and ns3::Cid::TRANSPORT.
SelectConnection()
bool ns3::BSSchedulerSimple::SelectConnection (Ptr< WimaxConnection > & connection) virtual
Selects a connection from the list of connections having packets to be sent .
Parameters
connection will point to a connection that have packets to be sent
Returns
false if no connection has packets to be sent, true otherwise
Implements ns3::BSScheduler.
Definition at line 221 of file bs-scheduler-simple.cc.
References ns3::Cid::BASIC, ns3::BSScheduler::GetBs(), ns3::ServiceFlowRecord::GetDlTimeStamp(), ns3::MilliSeconds(), ns3::Simulator::Now(), NS_LOG_INFO, ns3::Cid::PRIMARY, ns3::ServiceFlowRecord::SetDlTimeStamp(), ns3::ServiceFlow::SF_TYPE_BE, ns3::ServiceFlow::SF_TYPE_NRTPS, ns3::ServiceFlow::SF_TYPE_RTPS, and ns3::ServiceFlow::SF_TYPE_UGS.
Referenced by Schedule().
Member Data Documentation
m_downlinkBursts
std::list<std::pair<OfdmDlMapIe*, Ptr<PacketBurst> > >* ns3::BSSchedulerSimple::m_downlinkBursts private
down link bursts
Definition at line 100 of file bs-scheduler-simple.h.
Referenced by ~BSSchedulerSimple(), AddDownlinkBurst(), GetDownlinkBursts(), and Schedule().
The documentation for this class was generated from the following files:
src/wimax/model/bs-scheduler-simple.h
src/wimax/model/bs-scheduler-simple.cc