ns-3: ns3::LoraPhyHelper Class Reference
ns3::LoraPhyHelper Class Reference
Helper to install LoraPhy instances on multiple Nodes.
#include "lora-phy-helper.h"
Public Types
enum DeviceType { GW, ED }
Enum for the type of device: End Device (ED) or Gateway (GW)
Public Member Functions
LoraPhyHelper ()
Create a phy helper without any parameter set.
Ptr< LoraPhy > Create (Ptr< Node > node, Ptr< NetDevice > device) const
Crate a LoraPhy and connect it to a device on a node.
void Set (std::string name, const AttributeValue &v)
Set an attribute of the underlying PHY object.
void SetChannel (Ptr< LoraChannel > channel)
Set the LoraChannel to connect the PHYs to.
void SetDeviceType (enum DeviceType dt)
Set the kind of PHY this helper will create.
Private Attributes
Ptr< LoraChannel > m_channel
The channel instance the PHYs will be connected to.
ObjectFactory m_phy
The PHY layer factory object.
Detailed Description
Helper to install LoraPhy instances on multiple Nodes.
Definition at line 37 of file lora-phy-helper.h.
Member Enumeration Documentation
DeviceType
enum ns3::LoraPhyHelper::DeviceType
Enum for the type of device: End Device (ED) or Gateway (GW)
Enumerator
GW
ED
Definition at line 44 of file lora-phy-helper.h.
Constructor & Destructor Documentation
LoraPhyHelper()
ns3::LoraPhyHelper::LoraPhyHelper ()
Create a phy helper without any parameter set.
The user must set them all to be able to call Install later.
Definition at line 29 of file lora-phy-helper.cc.
Member Function Documentation
Create()
Ptr< LoraPhy > ns3::LoraPhyHelper::Create (Ptr< Node > node, Ptr< NetDevice > device) const
Crate a LoraPhy and connect it to a device on a node.
Parameters
node the node on which we wish to create a wifi PHY.
device the device within which this PHY will be created.
Returns
a newly-created PHY object.
Definition at line 62 of file lora-phy-helper.cc.
References ns3::LoraChannel::Add(), ns3::ObjectFactory::Create(), ns3::TypeId::GetName(), ns3::ObjectFactory::GetTypeId(), m_channel, m_phy, NS_LOG_FUNCTION, and third::phy.
Referenced by ns3::LoraHelper::Install().
Set()
void ns3::LoraPhyHelper::Set (std::string name, const AttributeValue & v)
Set an attribute of the underlying PHY object.
Parameters
name the name of the attribute to set.
v the value of the attribute.
Definition at line 56 of file lora-phy-helper.cc.
References m_phy, and ns3::ObjectFactory::Set().
SetChannel()
void ns3::LoraPhyHelper::SetChannel (Ptr< LoraChannel > channel)
Set the LoraChannel to connect the PHYs to.
Every PHY created by a call to Install is associated to this channel.
Parameters
channel the channel to associate to this helper.
Definition at line 34 of file lora-phy-helper.cc.
References channel, and m_channel.
Referenced by Reset().
SetDeviceType()
void ns3::LoraPhyHelper::SetDeviceType (enum DeviceType dt)
Set the kind of PHY this helper will create.
Parameters
dt the device type.
Definition at line 40 of file lora-phy-helper.cc.
References ED, GW, m_phy, NS_LOG_FUNCTION, and ns3::ObjectFactory::SetTypeId().
Referenced by Reset().
Member Data Documentation
m_channel
Ptr<LoraChannel> ns3::LoraPhyHelper::m_channel private
The channel instance the PHYs will be connected to.
Definition at line 99 of file lora-phy-helper.h.
Referenced by Create(), and SetChannel().
m_phy
ObjectFactory ns3::LoraPhyHelper::m_phy private
The PHY layer factory object.
Definition at line 94 of file lora-phy-helper.h.
Referenced by Create(), Set(), and SetDeviceType().
The documentation for this class was generated from the following files:
src/lorawan/helper/lora-phy-helper.h
src/lorawan/helper/lora-phy-helper.cc