ns-3: ns3::RttMeanDeviation Class Reference
ns3::RttMeanDeviation Class Reference
Internet » TCP
The "Mean--Deviation" RTT estimator, as discussed by Van Jacobson.
#include "rtt-estimator.h"
Public Member Functions
RttMeanDeviation ()
RttMeanDeviation (const RttMeanDeviation &r)
Copy constructor.
Ptr< RttEstimator > Copy () const
Copy object (including current internal state)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
void Measurement (Time measure)
Add a new measurement to the estimator.
void Reset ()
Resets the estimator.
Public Member Functions inherited from ns3::RttEstimator
RttEstimator ()
RttEstimator (const RttEstimator &r)
Copy constructor.
virtual ~RttEstimator ()
Time GetEstimate (void) const
gets the RTT estimate.
uint32_t GetNSamples (void) const
gets the number of samples used in the estimates
Time GetVariation (void) const
Note that this is not a formal statistical variance; it has the the same units as the estimate.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::RttEstimator
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
uint32_t CheckForReciprocalPowerOfTwo (double val) const
Utility function to check for possible conversion of a double value (0 < value < 1) to a reciprocal power of two.
void FloatingPointUpdate (Time m)
Method to update the rtt and variation estimates using floating point arithmetic, used when the values of Alpha and Beta are not both a reciprocal power of two.
void IntegerUpdate (Time m, uint32_t rttShift, uint32_t variationShift)
Method to update the rtt and variation estimates using integer arithmetic, used when the values of Alpha and Beta support the integer conversion.
Private Attributes
double m_alpha
Filter gain for average.
double m_beta
Filter gain for variation.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::RttEstimator
Time m_estimatedRtt
Current estimate.
Time m_estimatedVariation
Current estimate variation.
uint32_t m_nSamples
Number of samples.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The "Mean--Deviation" RTT estimator, as discussed by Van Jacobson.
This class implements the "Mean--Deviation" RTT estimator, as discussed by Van Jacobson and Michael J. Karels, in "Congestion Avoidance and Control", SIGCOMM 88, Appendix A
The default values for the gain (alpha and beta) are set as documented in RFC 6298.
Definition at line 123 of file rtt-estimator.h.
Constructor & Destructor Documentation
RttMeanDeviation() [1/2]
ns3::RttMeanDeviation::RttMeanDeviation ()
Definition at line 150 of file rtt-estimator.cc.
References NS_LOG_FUNCTION.
RttMeanDeviation() [2/2]
ns3::RttMeanDeviation::RttMeanDeviation (const RttMeanDeviation & r)
Copy constructor.
Parameters
r the object to copy
Definition at line 155 of file rtt-estimator.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CheckForReciprocalPowerOfTwo()
uint32_t ns3::RttMeanDeviation::CheckForReciprocalPowerOfTwo (double val) const private
Utility function to check for possible conversion of a double value (0 < value < 1) to a reciprocal power of two.
Values of 1/32, 1/16, 1/8, 1/4, and 1/2 (i.e., within the possible range of experimentation for this estimator) are supported.
Parameters
val value to check
Returns
log base 2 (1/val) if reciprocal power of 2, or zero if not
Definition at line 168 of file rtt-estimator.cc.
References NS_LOG_FUNCTION, and ns3::TOLERANCE.
Referenced by Measurement().
Copy()
Ptr< RttEstimator > ns3::RttMeanDeviation::Copy () const virtual
Copy object (including current internal state)
Returns
a copy of itself
Implements ns3::RttEstimator.
Definition at line 270 of file rtt-estimator.cc.
References NS_LOG_FUNCTION.
Referenced by RttEstimatorTestCase::DoRun().
FloatingPointUpdate()
void ns3::RttMeanDeviation::FloatingPointUpdate (Time m) private
Method to update the rtt and variation estimates using floating point arithmetic, used when the values of Alpha and Beta are not both a reciprocal power of two.
Parameters
m time measurement
Definition at line 200 of file rtt-estimator.cc.
References ns3::Abs(), ns3::Time::FromDouble(), m_alpha, m_beta, ns3::RttEstimator::m_estimatedRtt, ns3::RttEstimator::m_estimatedVariation, NS_LOG_FUNCTION, ns3::Time::S, and ns3::Time::ToDouble().
Referenced by Measurement().
GetInstanceTypeId()
TypeId ns3::RttMeanDeviation::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Reimplemented from ns3::RttEstimator.
Definition at line 162 of file rtt-estimator.cc.
References GetTypeId().
GetTypeId()
TypeId ns3::RttMeanDeviation::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 130 of file rtt-estimator.cc.
References m_alpha, m_beta, ns3::MakeDoubleAccessor(), and ns3::TypeId::SetParent().
Referenced by ns3::TcpGeneralTest::CreateSocket(), GetInstanceTypeId(), and ns3::TcpL4Protocol::GetTypeId().
IntegerUpdate()
void ns3::RttMeanDeviation::IntegerUpdate (Time m, uint32_t rttShift, uint32_t variationShift) private
Method to update the rtt and variation estimates using integer arithmetic, used when the values of Alpha and Beta support the integer conversion.
Parameters
m time measurement
rttShift value corresponding to log base 2 (1/alpha)
variationShift value corresponding to log base 2 (1/beta)
Definition at line 220 of file rtt-estimator.cc.
References ns3::Time::From(), ns3::Time::GetInteger(), ns3::RttEstimator::m_estimatedRtt, ns3::RttEstimator::m_estimatedVariation, and NS_LOG_FUNCTION.
Referenced by Measurement().
Measurement()
void ns3::RttMeanDeviation::Measurement (Time measure) virtual
Add a new measurement to the estimator.
Parameters
measure the new RTT measure.
Implements ns3::RttEstimator.
Definition at line 240 of file rtt-estimator.cc.
References CheckForReciprocalPowerOfTwo(), FloatingPointUpdate(), IntegerUpdate(), m_alpha, m_beta, ns3::RttEstimator::m_estimatedRtt, ns3::RttEstimator::m_estimatedVariation, ns3::RttEstimator::m_nSamples, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Reset()
void ns3::RttMeanDeviation::Reset () virtual
Resets the estimator.
Reimplemented from ns3::RttEstimator.
Definition at line 277 of file rtt-estimator.cc.
References NS_LOG_FUNCTION, and ns3::RttEstimator::Reset().
Referenced by RttEstimatorTestCase::DoRun().
Member Data Documentation
m_alpha
double ns3::RttMeanDeviation::m_alpha private
Filter gain for average.
Definition at line 184 of file rtt-estimator.h.
Referenced by FloatingPointUpdate(), GetTypeId(), and Measurement().
m_beta
double ns3::RttMeanDeviation::m_beta private
Filter gain for variation.
Definition at line 185 of file rtt-estimator.h.
Referenced by FloatingPointUpdate(), GetTypeId(), and Measurement().
The documentation for this class was generated from the following files:
src/internet/model/rtt-estimator.h
src/internet/model/rtt-estimator.cc