ns-3: OcbWifiMacTestCase Class Reference
OcbWifiMacTestCase Class Reference
WAVE module » wave module tests | Test suites
Ocb Wifi Mac Test Case.
Public Member Functions
OcbWifiMacTestCase (void)
virtual ~OcbWifiMacTestCase (void)
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void AdvancePosition (Ptr< Node > node)
Advance position function.
void ConfigureAdhocMode (Ptr< Node > static_node, Ptr< Node > mobile_node)
Configure adhoc mode function.
void ConfigureApStaMode (Ptr< Node > static_node, Ptr< Node > mobile_node)
Configure AP STA mode function.
void ConfigureOcbMode (Ptr< Node > static_node, Ptr< Node > mobile_node)
Configure OCB mode function.
virtual void DoRun (void)
static-node:0 <-— mobile-node:1
Vector GetCurrentPosition (uint32_t i)
Get current position function.
void MacAssoc (std::string context, Mac48Address bssid)
MAC associate function.
void PhyRxOkTrace (std::string context, Ptr< const Packet > packet, double snr, WifiMode mode, enum WifiPreamble preamble)
Phy receive ok trace function.
void PhyTxTrace (std::string context, Ptr< const Packet > packet, WifiMode mode, WifiPreamble preamble, uint8_t txPower)
Phy transmit trace function.
void PostDeviceConfiguration (Ptr< Node > static_node, Ptr< Node > mobile_node)
Post device configuration function.
void PreRandomConfiguration (void)
Pre random configuration function.
Private Attributes
Vector macassoc_pos
MAC associate position.
Time macassoc_time
MAC associate time.
NodeContainer nodes
the nodes
Vector phyrx_pos
Phy receive position.
Time phyrx_time
Phy receive time.
Vector phytx_pos
Phy transmit position.
Time phytx_time
Phy transmit time.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Ocb Wifi Mac Test Case.
Definition at line 80 of file ocb-test-suite.cc.
Constructor & Destructor Documentation
OcbWifiMacTestCase()
OcbWifiMacTestCase::OcbWifiMacTestCase (void)
Definition at line 165 of file ocb-test-suite.cc.
~OcbWifiMacTestCase()
OcbWifiMacTestCase::~OcbWifiMacTestCase (void) virtual
Definition at line 170 of file ocb-test-suite.cc.
Member Function Documentation
AdvancePosition()
void OcbWifiMacTestCase::AdvancePosition (Ptr< Node > node) private
Advance position function.
Parameters
node the node
Definition at line 177 of file ocb-test-suite.cc.
References ns3::Object::GetObject(), third::mobility, and ns3::Seconds().
Referenced by PostDeviceConfiguration().
ConfigureAdhocMode()
void OcbWifiMacTestCase::ConfigureAdhocMode (Ptr< Node > static_node, Ptr< Node > mobile_node) private
Configure adhoc mode function.
Parameters
static_node the static node
mobile_node the mobile node
Definition at line 271 of file ocb-test-suite.cc.
References ns3::YansWifiChannelHelper::Create(), ns3::YansWifiPhyHelper::SetChannel(), ns3::WifiMacHelper::SetType(), third::wifi, and ns3::WIFI_PHY_STANDARD_80211_10MHZ.
Referenced by DoRun().
ConfigureApStaMode()
void OcbWifiMacTestCase::ConfigureApStaMode (Ptr< Node > static_node, Ptr< Node > mobile_node) private
Configure AP STA mode function.
Parameters
static_node the static node
mobile_node the mobile node
Definition at line 249 of file ocb-test-suite.cc.
References ns3::YansWifiChannelHelper::Create(), ns3::YansWifiPhyHelper::SetChannel(), ns3::WifiMacHelper::SetType(), third::ssid, third::wifi, and ns3::WIFI_PHY_STANDARD_80211_10MHZ.
Referenced by DoRun().
ConfigureOcbMode()
void OcbWifiMacTestCase::ConfigureOcbMode (Ptr< Node > static_node, Ptr< Node > mobile_node) private
Configure OCB mode function.
Parameters
static_node the static node
mobile_node the mobile node
Definition at line 290 of file ocb-test-suite.cc.
References ns3::YansWifiChannelHelper::Create(), ns3::Wifi80211pHelper::Install(), ns3::YansWifiPhyHelper::SetChannel(), and ns3::WifiHelper::SetRemoteStationManager().
Referenced by DoRun().
DoRun()
void OcbWifiMacTestCase::DoRun (void) private virtual
static-node:0 <-— mobile-node:1
---— 350m ----— *
the node transmit range is less than 150m
Ap+Sta mode vs Adhoc mode vs Ocb mode first test the time point when the stationary node is an AP and the mobile node is a Sta then test when one Ad-hoc node and another Ad-hoc node last test when one OCB node and another OCB node
Implements ns3::TestCase.
Definition at line 375 of file ocb-test-suite.cc.
References ConfigureAdhocMode(), ConfigureApStaMode(), ConfigureOcbMode(), ns3::NodeContainer::Create(), ns3::NodeContainer::Get(), ns3::Time::GetNanoSeconds(), macassoc_pos, macassoc_time, nodes, NS_TEST_ASSERT_MSG_EQ, NS_TEST_ASSERT_MSG_GT, NS_TEST_ASSERT_MSG_LT, phyrx_pos, phyrx_time, phytx_pos, phytx_time, PostDeviceConfiguration(), PreRandomConfiguration(), and ns3::Seconds().
GetCurrentPosition()
Vector OcbWifiMacTestCase::GetCurrentPosition (uint32_t i) private
Get current position function.
Parameters
i the current position index
Returns
the current position vector
Definition at line 195 of file ocb-test-suite.cc.
References ns3::NodeContainer::Get(), ns3::Object::GetObject(), third::mobility, nodes, and NS_ASSERT.
Referenced by MacAssoc(), PhyRxOkTrace(), and PhyTxTrace().
MacAssoc()
void OcbWifiMacTestCase::MacAssoc (std::string context, Mac48Address bssid) private
MAC associate function.
Parameters
context the context
bssid the BSSID
Definition at line 205 of file ocb-test-suite.cc.
References GetCurrentPosition(), ns3::Time::GetNanoSeconds(), macassoc_pos, macassoc_time, and ns3::Now().
Referenced by PostDeviceConfiguration().
PhyRxOkTrace()
void OcbWifiMacTestCase::PhyRxOkTrace (std::string context, Ptr< const Packet > packet, double snr, WifiMode mode, enum WifiPreamble preamble) private
Phy receive ok trace function.
Parameters
context the context
packet the packet
snr the SNR
mode the mode
preamble the preamble
Definition at line 220 of file ocb-test-suite.cc.
References GetCurrentPosition(), ns3::Time::GetNanoSeconds(), ns3::Now(), phyrx_pos, and phyrx_time.
Referenced by PostDeviceConfiguration().
PhyTxTrace()
void OcbWifiMacTestCase::PhyTxTrace (std::string context, Ptr< const Packet > packet, WifiMode mode, WifiPreamble preamble, uint8_t txPower) private
Phy transmit trace function.
Parameters
context the context
packet the packet
mode the mode
preamble the preamble
txPower the transmit power
Definition at line 234 of file ocb-test-suite.cc.
References GetCurrentPosition(), ns3::Time::GetNanoSeconds(), ns3::WifiMacHeader::IsData(), ns3::Now(), ns3::Packet::PeekHeader(), phytx_pos, and phytx_time.
Referenced by PostDeviceConfiguration().
PostDeviceConfiguration()
void OcbWifiMacTestCase::PostDeviceConfiguration (Ptr< Node > static_node, Ptr< Node > mobile_node) private
Post device configuration function.
Parameters
static_node the static node
mobile_node the mobile node
Definition at line 307 of file ocb-test-suite.cc.
References ns3::Node::AddApplication(), AdvancePosition(), AssignWifiRandomStreams(), ns3::Config::Connect(), ns3::WifiNetDevice::GetAddress(), ns3::Node::GetDevice(), ns3::WifiNetDevice::GetIfIndex(), ns3::WifiNetDevice::GetMac(), ns3::Object::GetObject(), ns3::MobilityModel::GetPosition(), ns3::PacketSocketHelper::Install(), MacAssoc(), macassoc_pos, macassoc_time, ns3::MakeCallback(), third::mobility, phyrx_pos, phyrx_time, PhyRxOkTrace(), phytx_pos, phytx_time, PhyTxTrace(), ns3::Seconds(), ns3::PacketSocketServer::SetLocal(), ns3::PacketSocketAddress::SetPhysicalAddress(), ns3::MobilityModel::SetPosition(), ns3::PacketSocketAddress::SetProtocol(), ns3::PacketSocketClient::SetRemote(), ns3::PacketSocketAddress::SetSingleDevice(), ns3::Application::SetStartTime(), and ns3::Application::SetStopTime().
Referenced by DoRun().
PreRandomConfiguration()
void OcbWifiMacTestCase::PreRandomConfiguration (void) private
Pre random configuration function.
Definition at line 435 of file ocb-test-suite.cc.
Referenced by DoRun().
Member Data Documentation
macassoc_pos
Vector OcbWifiMacTestCase::macassoc_pos private
MAC associate position.
Definition at line 155 of file ocb-test-suite.cc.
Referenced by DoRun(), MacAssoc(), and PostDeviceConfiguration().
macassoc_time
Time OcbWifiMacTestCase::macassoc_time private
MAC associate time.
Definition at line 154 of file ocb-test-suite.cc.
Referenced by DoRun(), MacAssoc(), and PostDeviceConfiguration().
nodes
NodeContainer OcbWifiMacTestCase::nodes private
the nodes
Definition at line 162 of file ocb-test-suite.cc.
Referenced by DoRun(), and GetCurrentPosition().
phyrx_pos
Vector OcbWifiMacTestCase::phyrx_pos private
Phy receive position.
Definition at line 158 of file ocb-test-suite.cc.
Referenced by DoRun(), PhyRxOkTrace(), and PostDeviceConfiguration().
phyrx_time
Time OcbWifiMacTestCase::phyrx_time private
Phy receive time.
Definition at line 157 of file ocb-test-suite.cc.
Referenced by DoRun(), PhyRxOkTrace(), and PostDeviceConfiguration().
phytx_pos
Vector OcbWifiMacTestCase::phytx_pos private
Phy transmit position.
Definition at line 152 of file ocb-test-suite.cc.
Referenced by DoRun(), PhyTxTrace(), and PostDeviceConfiguration().
phytx_time
Time OcbWifiMacTestCase::phytx_time private
Phy transmit time.
Definition at line 151 of file ocb-test-suite.cc.
Referenced by DoRun(), PhyTxTrace(), and PostDeviceConfiguration().
The documentation for this class was generated from the following file:
src/wave/test/ocb-test-suite.cc