ns-3: TcpBicIncrementTest Class Reference
TcpBicIncrementTest Class Reference
Internet » internet module tests | Test suites
Testing the congestion avoidance increment on TcpBic.
Public Member Functions
TcpBicIncrementTest (uint32_t cWnd, uint32_t segmentSize, uint32_t ssThresh, uint32_t segmentsAcked, uint32_t lastMaxCwnd, const std::string &name)
Constructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void ExecuteTest (void)
Execute the test.
uint32_t Update (Ptr< TcpSocketState > tcb)
Update the TCP socket state.
Private Attributes
uint32_t m_cWnd
Congestion window.
uint32_t m_lastMaxCwnd
Last max Cwnd.
uint32_t m_segmentsAcked
Number of segments acked.
uint32_t m_segmentSize
Segment size.
uint32_t m_ssThresh
Slow Start Threshold.
Ptr< TcpSocketState > m_state
TCP socket state.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Testing the congestion avoidance increment on TcpBic.
Definition at line 36 of file tcp-bic-test.cc.
Constructor & Destructor Documentation
TcpBicIncrementTest()
TcpBicIncrementTest::TcpBicIncrementTest (uint32_t cWnd, uint32_t segmentSize, uint32_t ssThresh, uint32_t segmentsAcked, uint32_t lastMaxCwnd, const std::string & name)
Constructor.
Parameters
cWnd Congestion window.
segmentSize Segment size.
ssThresh Slow Start Threshold.
segmentsAcked Number of segments acked.
lastMaxCwnd Last max Cwnd.
name Test description.
Definition at line 78 of file tcp-bic-test.cc.
Member Function Documentation
DoRun()
void TcpBicIncrementTest::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 94 of file tcp-bic-test.cc.
References ExecuteTest(), ns3::TcpSocketState::m_cWnd, m_cWnd, ns3::TcpSocketState::m_segmentSize, m_segmentSize, ns3::TcpSocketState::m_ssThresh, m_ssThresh, m_state, and ns3::Seconds().
ExecuteTest()
void TcpBicIncrementTest::ExecuteTest (void) private
Execute the test.
Definition at line 108 of file tcp-bic-test.cc.
References ns3::TracedValue< T >::Get(), ns3::TcpSocketState::m_cWnd, m_cWnd, m_segmentsAcked, m_segmentSize, m_state, NS_TEST_ASSERT_MSG_EQ, and Update().
Referenced by DoRun().
Update()
uint32_t TcpBicIncrementTest::Update (Ptr< TcpSocketState > tcb) private
Update the TCP socket state.
Parameters
tcb The TCP socket state.
Returns
The ack counter.
Definition at line 129 of file tcp-bic-test.cc.
References ns3::UintegerValue::Get(), ns3::ObjectBase::GetAttribute(), ns3::TcpBic::IncreaseWindow(), ns3::TcpSocketState::m_cWnd, ns3::TcpBic::m_lastMaxCwnd, m_lastMaxCwnd, m_segmentsAcked, ns3::TcpSocketState::m_segmentSize, and m_state.
Referenced by ExecuteTest().
Member Data Documentation
m_cWnd
uint32_t TcpBicIncrementTest::m_cWnd private
Congestion window.
Definition at line 70 of file tcp-bic-test.cc.
Referenced by DoRun(), and ExecuteTest().
m_lastMaxCwnd
uint32_t TcpBicIncrementTest::m_lastMaxCwnd private
Last max Cwnd.
Definition at line 74 of file tcp-bic-test.cc.
Referenced by Update().
m_segmentsAcked
uint32_t TcpBicIncrementTest::m_segmentsAcked private
Number of segments acked.
Definition at line 73 of file tcp-bic-test.cc.
Referenced by ExecuteTest(), and Update().
m_segmentSize
uint32_t TcpBicIncrementTest::m_segmentSize private
Segment size.
Definition at line 71 of file tcp-bic-test.cc.
Referenced by DoRun(), and ExecuteTest().
m_ssThresh
uint32_t TcpBicIncrementTest::m_ssThresh private
Slow Start Threshold.
Definition at line 72 of file tcp-bic-test.cc.
Referenced by DoRun().
m_state
Ptr<TcpSocketState> TcpBicIncrementTest::m_state private
TCP socket state.
Definition at line 75 of file tcp-bic-test.cc.
Referenced by DoRun(), ExecuteTest(), and Update().
The documentation for this class was generated from the following file:
src/internet/test/tcp-bic-test.cc