ns-3: ns3::int64x64_t Class Reference
ns3::int64x64_t Class Reference
Core » High Precision Q64.64
#include "int64x64-128.h"
Public Types
enum impl_type {
int128_impl, cairo_impl, ld_impl, int128_impl,
cairo_impl, ld_impl, int128_impl, cairo_impl,
ld_impl
}
Type tag for the underlying implementation.
enum impl_type {
int128_impl, cairo_impl, ld_impl, int128_impl,
cairo_impl, ld_impl, int128_impl, cairo_impl,
ld_impl
}
Type tag for the underlying implementation.
enum impl_type {
int128_impl, cairo_impl, ld_impl, int128_impl,
cairo_impl, ld_impl, int128_impl, cairo_impl,
ld_impl
}
Type tag for the underlying implementation.
Public Member Functions
int64x64_t ()
Default constructor.
int64x64_t ()
Default constructor.
int64x64_t ()
Default constructor.
int64x64_t (const int64_t hi, const uint64_t lo)
Construct from explicit high and low values.
int64x64_t (const int64_t hi, const uint64_t lo)
Construct from explicit high and low values.
int64x64_t (const int64x64_t &o)
Copy constructor.
int64x64_t (const int64x64_t &o)
Copy constructor.
int64x64_t (const int64x64_t &o)
Copy constructor.
int64x64_t (int64_t hi, uint64_t lo)
Construct from explicit high and low values.
double GetDouble (void) const
Get this value as a double.
double GetDouble (void) const
Get this value as a double.
double GetDouble (void) const
Get this value as a double.
int64_t GetHigh (void) const
Get the integer portion.
int64_t GetHigh (void) const
Get the integer portion.
int64_t GetHigh (void) const
Get the integer portion.
uint64_t GetLow (void) const
Get the fractional portion of this value, unscaled.
uint64_t GetLow (void) const
Get the fractional portion of this value, unscaled.
uint64_t GetLow (void) const
Get the fractional portion of this value, unscaled.
void MulByInvert (const int64x64_t &o)
Multiply this value by a Q0.128 value, presumably representing an inverse, completing a division operation.
void MulByInvert (const int64x64_t &o)
Multiply this value by a Q0.128 value, presumably representing an inverse, completing a division operation.
void MulByInvert (const int64x64_t &o)
Multiply this value by a Q0.128 value, presumably representing an inverse, completing a division operation.
int64x64_t & operator= (const int64x64_t &o)
Assignment.
int64x64_t & operator= (const int64x64_t &o)
Assignment.
int64x64_t & operator= (const int64x64_t &o)
Assignment.
Construct from a floating point value.
Parameters
[in] value Floating value to represent.
int64x64_t (const double value)
int64x64_t (const long double value)
Construct from an integral type.
Parameters
[in] v Integer value to represent.
int64x64_t (const int v)
int64x64_t (const long int v)
int64x64_t (const long long int v)
int64x64_t (const unsigned int v)
int64x64_t (const unsigned long int v)
int64x64_t (const unsigned long long int v)
int64x64_t (const double value)
Construct from a floating point value.
int64x64_t (const long double value)
Construct from a floating point value.
int64x64_t (const int v)
Construct from an integral type.
int64x64_t (const long int v)
Construct from an integral type.
int64x64_t (const long long int v)
Construct from an integral type.
int64x64_t (const unsigned int v)
Construct from an integral type.
int64x64_t (const unsigned long int v)
Construct from an integral type.
int64x64_t (const unsigned long long int v)
Construct from an integral type.
int64x64_t (double v)
Construct from a floating point value.
int64x64_t (long double v)
Construct from a floating point value.
int64x64_t (int v)
Construct from an integral type.
int64x64_t (long int v)
Construct from an integral type.
int64x64_t (long long int v)
Construct from an integral type.
int64x64_t (unsigned int v)
Construct from an integral type.
int64x64_t (unsigned long int v)
Construct from an integral type.
int64x64_t (unsigned long long int v)
Construct from an integral type.
Static Public Member Functions
static int64x64_t Invert (const uint64_t v)
Compute the inverse of an integer value.
static int64x64_t Invert (const uint64_t v)
Compute the inverse of an integer value.
static int64x64_t Invert (uint64_t v)
Compute the inverse of an integer value.
Static Public Attributes
static enum impl_type implementation = int128_impl
Type tag for this implementation.
Private Member Functions
int64x64_t (const int128_t v)
Construct from an integral type.
void Div (const int64x64_t &o)
Implement /=.
void Div (const int64x64_t &o)
Implement /=.
std::pair< int64_t, uint64_t > GetHighLow (void) const
Get the high and low portions of this value.
void Mul (const int64x64_t &o)
Implement *=.
void Mul (const int64x64_t &o)
Implement *=.
Static Private Member Functions
static cairo_uint128_t Udiv (const cairo_uint128_t a, const cairo_uint128_t b)
Unsigned division of Q64.64 values.
static uint128_t Udiv (const uint128_t a, const uint128_t b)
Unsigned division of Q64.64 values.
static cairo_uint128_t Umul (const cairo_uint128_t a, const cairo_uint128_t b)
Unsigned multiplication of Q64.64 values.
static uint128_t Umul (const uint128_t a, const uint128_t b)
Unsigned multiplication of Q64.64 values.
static cairo_uint128_t UmulByInvert (const cairo_uint128_t a, const cairo_uint128_t b)
Unsigned multiplication of Q64.64 and Q0.128 values.
static uint128_t UmulByInvert (const uint128_t a, const uint128_t b)
Unsigned multiplication of Q64.64 and Q0.128 values.
Private Attributes
int128_t _v
The Q64.64 value.
cairo_int128_t _v
The Q64.64 value.
long double _v
The Q64.64 value.
Static Private Attributes
static const uint128_t HP128_MASK_HI_BIT = (((int128_t)1) << 127)
uint128_t high bit (sign bit).
static const uint64_t HP_MASK_HI = ~HP_MASK_LO
Mask for sign + integer part.
static const uint64_t HP_MASK_LO = 0xffffffffffffffffULL
Mask for fraction part.
static const uint64_t HPCAIRO_MASK_HI_BIT = (((uint64_t)1) << 63)
High bit of fractional part.
Friends
Arithmetic Operators
Arithmetic operators for int64x64_t.
bool operator== (const int64x64_t &lhs, const int64x64_t &rhs)
Arithmetic operator.
bool operator< (const int64x64_t &lhs, const int64x64_t &rhs)
bool operator> (const int64x64_t &lhs, const int64x64_t &rhs)
int64x64_t & operator+= (int64x64_t &lhs, const int64x64_t &rhs)
int64x64_t & operator-= (int64x64_t &lhs, const int64x64_t &rhs)
int64x64_t & operator*= (int64x64_t &lhs, const int64x64_t &rhs)
int64x64_t & operator/= (int64x64_t &lhs, const int64x64_t &rhs)
bool operator== (const int64x64_t &lhs, const int64x64_t &rhs)
Arithmetic operator.
bool operator< (const int64x64_t &lhs, const int64x64_t &rhs)
bool operator> (const int64x64_t &lhs, const int64x64_t &rhs)
int64x64_t & operator+= (int64x64_t &lhs, const int64x64_t &rhs)
int64x64_t & operator-= (int64x64_t &lhs, const int64x64_t &rhs)
int64x64_t & operator*= (int64x64_t &lhs, const int64x64_t &rhs)
int64x64_t & operator/= (int64x64_t &lhs, const int64x64_t &rhs)
bool operator== (const int64x64_t &lhs, const int64x64_t &rhs)
Arithmetic operator.
bool operator< (const int64x64_t &lhs, const int64x64_t &rhs)
bool operator> (const int64x64_t &lhs, const int64x64_t &rhs)
int64x64_t & operator+= (int64x64_t &lhs, const int64x64_t &rhs)
int64x64_t & operator-= (int64x64_t &lhs, const int64x64_t &rhs)
int64x64_t & operator*= (int64x64_t &lhs, const int64x64_t &rhs)
int64x64_t & operator/= (int64x64_t &lhs, const int64x64_t &rhs)
Unary Operators
Unary operators for int64x64_t.
int64x64_t operator- (const int64x64_t &lhs)
Unary operator.
int64x64_t operator! (const int64x64_t &lhs)
int64x64_t operator- (const int64x64_t &lhs)
Unary operator.
int64x64_t operator! (const int64x64_t &lhs)
int64x64_t operator- (const int64x64_t &lhs)
Unary operator.
int64x64_t operator! (const int64x64_t &lhs)
Detailed Description
Internal:
The implementation documented here is based on native 128-bit integers.
Internal:
The implementation documented here uses cairo 128-bit integers.
Internal:
The implementation documented here uses native long double.
High precision numerical type, implementing Q64.64 fixed precision.
Definition at line 45 of file int64x64-128.h.
Member Enumeration Documentation
impl_type [1/3]
enum ns3::int64x64_t::impl_type
Type tag for the underlying implementation.
A few testcases are are sensitive to implementation, specifically the double implementation. To handle this, we expose the underlying implementation type here.
Enumerator
int128_impl
Native int128_t implementation.
Native int128_t implementation.
cairo_impl
Cairo wideint implementation.
cairo wideint implementation
ld_impl
long double implementation.
long double implementation
int128_impl
Native int128_t implementation.
Native int128_t implementation.
cairo_impl
Cairo wideint implementation.
cairo wideint implementation
ld_impl
long double implementation.
long double implementation
int128_impl
Native int128_t implementation.
Native int128_t implementation.
cairo_impl
Cairo wideint implementation.
cairo wideint implementation
ld_impl
long double implementation.
long double implementation
Definition at line 76 of file int64x64-128.h.
impl_type [2/3]
enum ns3::int64x64_t::impl_type
Type tag for the underlying implementation.
A few testcases are sensitive to implementation, specifically the double implementation. To handle this, we expose the underlying implementation type here.
Enumerator
int128_impl
Native int128_t implementation.
Native int128_t implementation.
cairo_impl
Cairo wideint implementation.
cairo wideint implementation
ld_impl
long double implementation.
long double implementation
int128_impl
Native int128_t implementation.
Native int128_t implementation.
cairo_impl
Cairo wideint implementation.
cairo wideint implementation
ld_impl
long double implementation.
long double implementation
int128_impl
Native int128_t implementation.
Native int128_t implementation.
cairo_impl
Cairo wideint implementation.
cairo wideint implementation
ld_impl
long double implementation.
long double implementation
Definition at line 68 of file int64x64-cairo.h.
impl_type [3/3]
enum ns3::int64x64_t::impl_type
Type tag for the underlying implementation.
A few testcases are are sensitive to implementation, specifically the double implementation. To handle this, we expose the underlying implementation type here.
Enumerator
int128_impl
Native int128_t implementation.
Native int128_t implementation.
cairo_impl
Cairo wideint implementation.
cairo wideint implementation
ld_impl
long double implementation.
long double implementation
int128_impl
Native int128_t implementation.
Native int128_t implementation.
cairo_impl
Cairo wideint implementation.
cairo wideint implementation
ld_impl
long double implementation.
long double implementation
int128_impl
Native int128_t implementation.
Native int128_t implementation.
cairo_impl
Cairo wideint implementation.
cairo wideint implementation
ld_impl
long double implementation.
long double implementation
Definition at line 67 of file int64x64-double.h.
Constructor & Destructor Documentation
int64x64_t() [1/34]
ns3::int64x64_t::int64x64_t () inline
Default constructor.
Definition at line 87 of file int64x64-128.h.
Referenced by Invert().
int64x64_t() [2/34]
ns3::int64x64_t::int64x64_t (const double value) inline
Definition at line 96 of file int64x64-128.h.
References _v.
int64x64_t() [3/34]
ns3::int64x64_t::int64x64_t (const long double value) inline
Definition at line 101 of file int64x64-128.h.
References _v, and HP_MAX_64.
int64x64_t() [4/34]
ns3::int64x64_t::int64x64_t (const int v) inline
Definition at line 137 of file int64x64-128.h.
References _v.
int64x64_t() [5/34]
ns3::int64x64_t::int64x64_t (const long int v) inline
Definition at line 142 of file int64x64-128.h.
References _v.
int64x64_t() [6/34]
ns3::int64x64_t::int64x64_t (const long long int v) inline
Definition at line 147 of file int64x64-128.h.
References _v.
int64x64_t() [7/34]
ns3::int64x64_t::int64x64_t (const unsigned int v) inline
Definition at line 152 of file int64x64-128.h.
References _v.
int64x64_t() [8/34]
ns3::int64x64_t::int64x64_t (const unsigned long int v) inline
Definition at line 157 of file int64x64-128.h.
References _v.
int64x64_t() [9/34]
ns3::int64x64_t::int64x64_t (const unsigned long long int v) inline
Definition at line 162 of file int64x64-128.h.
References _v.
int64x64_t() [10/34]
ns3::int64x64_t::int64x64_t (const int64_t hi, const uint64_t lo) inline explicit
Construct from explicit high and low values.
Parameters
[in] hi Integer portion.
[in] lo Fractional portion, already scaled to HP_MAX_64.
Definition at line 175 of file int64x64-128.h.
References _v.
int64x64_t() [11/34]
ns3::int64x64_t::int64x64_t (const int64x64_t & o) inline
Copy constructor.
Parameters
[in] o Value to copy.
Definition at line 186 of file int64x64-128.h.
int64x64_t() [12/34]
ns3::int64x64_t::int64x64_t (const int128_t v) inline private
Construct from an integral type.
Parameters
[in] v Integer value to represent.
Definition at line 362 of file int64x64-128.h.
int64x64_t() [13/34]
ns3::int64x64_t::int64x64_t () inline
Default constructor.
Definition at line 79 of file int64x64-cairo.h.
References _v.
int64x64_t() [14/34]
ns3::int64x64_t::int64x64_t (const double value) inline
Construct from a floating point value.
Parameters
[in] value floating value to represent
Definition at line 90 of file int64x64-cairo.h.
References _v.
int64x64_t() [15/34]
ns3::int64x64_t::int64x64_t (const long double value) inline
Construct from a floating point value.
Parameters
[in] value floating value to represent
Definition at line 95 of file int64x64-cairo.h.
References _cairo_int128_negate, _v, and HP_MAX_64.
int64x64_t() [16/34]
ns3::int64x64_t::int64x64_t (const int v) inline
Construct from an integral type.
Parameters
[in] v Integer value to represent
Definition at line 131 of file int64x64-cairo.h.
References _v.
int64x64_t() [17/34]
ns3::int64x64_t::int64x64_t (const long int v) inline
Construct from an integral type.
Parameters
[in] v Integer value to represent
Definition at line 136 of file int64x64-cairo.h.
References _v.
int64x64_t() [18/34]
ns3::int64x64_t::int64x64_t (const long long int v) inline
Construct from an integral type.
Parameters
[in] v Integer value to represent
Definition at line 141 of file int64x64-cairo.h.
References _v.
int64x64_t() [19/34]
ns3::int64x64_t::int64x64_t (const unsigned int v) inline
Construct from an integral type.
Parameters
[in] v Integer value to represent
Definition at line 146 of file int64x64-cairo.h.
References _v.
int64x64_t() [20/34]
ns3::int64x64_t::int64x64_t (const unsigned long int v) inline
Construct from an integral type.
Parameters
[in] v Integer value to represent
Definition at line 151 of file int64x64-cairo.h.
References _v.
int64x64_t() [21/34]
ns3::int64x64_t::int64x64_t (const unsigned long long int v) inline
Construct from an integral type.
Parameters
[in] v Integer value to represent
Definition at line 156 of file int64x64-cairo.h.
References _v.
int64x64_t() [22/34]
ns3::int64x64_t::int64x64_t (const int64_t hi, const uint64_t lo) inline explicit
Construct from explicit high and low values.
Parameters
[in] hi Integer portion.
[in] lo Fractional portion, already scaled to HP_MAX_64.
Definition at line 168 of file int64x64-cairo.h.
References _v.
int64x64_t() [23/34]
ns3::int64x64_t::int64x64_t (const int64x64_t & o) inline
Copy constructor.
Parameters
[in] o Value to copy.
Definition at line 179 of file int64x64-cairo.h.
int64x64_t() [24/34]
ns3::int64x64_t::int64x64_t () inline
Default constructor.
Definition at line 78 of file int64x64-double.h.
int64x64_t() [25/34]
ns3::int64x64_t::int64x64_t (double v) inline
Construct from a floating point value.
Parameters
[in] v Floating value to represent
Definition at line 87 of file int64x64-double.h.
int64x64_t() [26/34]
ns3::int64x64_t::int64x64_t (long double v) inline
Construct from a floating point value.
Parameters
[in] v Floating value to represent
Definition at line 90 of file int64x64-double.h.
int64x64_t() [27/34]
ns3::int64x64_t::int64x64_t (int v) inline
Construct from an integral type.
Parameters
[in] v Integer value to represent
Definition at line 101 of file int64x64-double.h.
int64x64_t() [28/34]
ns3::int64x64_t::int64x64_t (long int v) inline
Construct from an integral type.
Parameters
[in] v Integer value to represent
Definition at line 104 of file int64x64-double.h.
int64x64_t() [29/34]
ns3::int64x64_t::int64x64_t (long long int v) inline
Construct from an integral type.
Parameters
[in] v Integer value to represent
Definition at line 107 of file int64x64-double.h.
int64x64_t() [30/34]
ns3::int64x64_t::int64x64_t (unsigned int v) inline
Construct from an integral type.
Parameters
[in] v Integer value to represent
Definition at line 110 of file int64x64-double.h.
int64x64_t() [31/34]
ns3::int64x64_t::int64x64_t (unsigned long int v) inline
Construct from an integral type.
Parameters
[in] v Integer value to represent
Definition at line 113 of file int64x64-double.h.
int64x64_t() [32/34]
ns3::int64x64_t::int64x64_t (unsigned long long int v) inline
Construct from an integral type.
Parameters
[in] v Integer value to represent
Definition at line 116 of file int64x64-double.h.
int64x64_t() [33/34]
ns3::int64x64_t::int64x64_t (int64_t hi, uint64_t lo) inline explicit
Construct from explicit high and low values.
Parameters
[in] hi Integer portion.
[in] lo Fractional portion, already scaled to HP_MAX_64.
Definition at line 126 of file int64x64-double.h.
References _v, and HP_MAX_64.
int64x64_t() [34/34]
ns3::int64x64_t::int64x64_t (const int64x64_t & o) inline
Copy constructor.
Parameters
[in] o Value to copy.
Definition at line 142 of file int64x64-double.h.
Member Function Documentation
Div() [1/2]
void ns3::int64x64_t::Div (const int64x64_t & o) private
Implement /=.
Parameters
[in] o The divisor.
Definition at line 113 of file int64x64-128.cc.
References _v, ns3::output_sign(), and Udiv().
Referenced by ns3::operator/=().
Div() [2/2]
void ns3::int64x64_t::Div (const int64x64_t & o) private
Implement /=.
Parameters
[in] o The divisor.
GetDouble() [1/3]
double ns3::int64x64_t::GetDouble (void) const inline
Get this value as a double.
Returns
This value in floating form.
Definition at line 206 of file int64x64-128.h.
References _v, HP_MASK_LO, and HP_MAX_64.
Referenced by ns3::int64x64::test::Int64x64Bug455TestCase::DoRun(), ns3::int64x64::test::Int64x64Bug863TestCase::DoRun(), ns3::ShowProgress::Feedback(), and ns3::Time::ToDouble().
GetDouble() [2/3]
double ns3::int64x64_t::GetDouble (void) const inline
Get this value as a double.
Returns
This value in floating form.
Definition at line 199 of file int64x64-cairo.h.
References _cairo_int128_negate, _cairo_int128_negative, _v, cairo_int128_t::hi, HP_MAX_64, and cairo_int128_t::lo.
GetDouble() [3/3]
double ns3::int64x64_t::GetDouble (void) const inline
Get this value as a double.
Returns
This value in floating form.
Definition at line 162 of file int64x64-double.h.
References _v.
GetHigh() [1/3]
int64_t ns3::int64x64_t::GetHigh (void) const inline
Get the integer portion.
Returns
The integer portion of this value.
Definition at line 222 of file int64x64-128.h.
References _v.
Referenced by ns3::OnOffApplication::CancelEvents(), ns3::int64x64::test::Int64x64HiLoTestCase::Check(), anonymous_namespace{sample-show-progress.cc}::Hold::Event(), ns3::DelayJitterEstimation::GetLastJitter(), Invert(), and ns3::operator<<().
GetHigh() [2/3]
int64_t ns3::int64x64_t::GetHigh (void) const inline
Get the integer portion.
Returns
The integer portion of this value.
Definition at line 215 of file int64x64-cairo.h.
References _v.
GetHigh() [3/3]
int64_t ns3::int64x64_t::GetHigh (void) const inline
Get the integer portion.
Returns
The integer portion of this value.
Definition at line 215 of file int64x64-double.h.
References GetHighLow().
GetHighLow()
std::pair<int64_t, uint64_t> ns3::int64x64_t::GetHighLow (void) const inline private
Get the high and low portions of this value.
Returns
A pair of the high and low words
Definition at line 173 of file int64x64-double.h.
References _v, and HP_MAX_64.
Referenced by GetHigh(), and GetLow().
GetLow() [1/3]
uint64_t ns3::int64x64_t::GetLow (void) const inline
Get the fractional portion of this value, unscaled.
Returns
The fractional portion, unscaled, as an integer.
Definition at line 232 of file int64x64-128.h.
References _v, and HP_MASK_LO.
Referenced by ns3::int64x64::test::Int64x64HiLoTestCase::Check(), ns3::int64x64::test::Int64x64InputTestCase::Check(), ns3::operator<<(), and ns3::ReadLoDigits().
GetLow() [2/3]
uint64_t ns3::int64x64_t::GetLow (void) const inline
Get the fractional portion of this value, unscaled.
Returns
The fractional portion, unscaled, as an integer.
Definition at line 224 of file int64x64-cairo.h.
References _v.
GetLow() [3/3]
uint64_t ns3::int64x64_t::GetLow (void) const inline
Get the fractional portion of this value, unscaled.
Returns
The fractional portion, unscaled, as an integer.
Definition at line 224 of file int64x64-double.h.
References GetHighLow().
Invert() [1/3]
int64x64_t ns3::int64x64_t::Invert (const uint64_t v) static
Compute the inverse of an integer value.
Ordinary division by an integer would be limited to 64 bits of precision. Instead, we multiply by the 128-bit inverse of the divisor. This function computes the inverse to 128-bit precision. MulByInvert() then completes the division.
(Really this should be a separate type representing Q0.128.)
Parameters
[in] v The value to compute the inverse of.
Returns
A Q0.128 representation of the inverse.
Definition at line 217 of file int64x64-128.cc.
References int64x64_t(), _v, GetHigh(), MulByInvert(), NS_ASSERT, and Udiv().
Referenced by ns3::int64x64::test::Int64x64InvertTestCase::Check(), and ns3::Time::SetResolution().
Invert() [2/3]
static int64x64_t ns3::int64x64_t::Invert (const uint64_t v) static
Compute the inverse of an integer value.
Ordinary division by an integer would be limited to 64 bits of precsion. Instead, we multiply by the 128-bit inverse of the divisor. This function computes the inverse to 128-bit precision. MulByInvert() then completes the division.
(Really this should be a separate type representing Q0.128.)
Parameters
[in] v The value to compute the inverse of.
Returns
A Q0.128 representation of the inverse.
Invert() [3/3]
static int64x64_t ns3::int64x64_t::Invert (uint64_t v) inline static
Compute the inverse of an integer value.
Parameters
[in] v The value to compute the inverse of.
Returns
The inverse.
Definition at line 249 of file int64x64-double.h.
Mul() [1/2]
void ns3::int64x64_t::Mul (const int64x64_t & o) private
Implement *=.
Parameters
[in] o The other factor.
Definition at line 64 of file int64x64-128.cc.
References _v, ns3::output_sign(), and Umul().
Referenced by ns3::operator*=().
Mul() [2/2]
void ns3::int64x64_t::Mul (const int64x64_t & o) private
Implement *=.
Parameters
[in] o The other factor.
MulByInvert() [1/3]
void ns3::int64x64_t::MulByInvert (const int64x64_t & o)
Multiply this value by a Q0.128 value, presumably representing an inverse, completing a division operation.
Parameters
[in] o The inverse operand.
See also
Invert()
Definition at line 191 of file int64x64-128.cc.
References _v, and UmulByInvert().
Referenced by ns3::int64x64::test::Int64x64InvertTestCase::Check(), ns3::Time::From(), Invert(), and ns3::Time::To().
MulByInvert() [2/3]
void ns3::int64x64_t::MulByInvert (const int64x64_t & o)
Multiply this value by a Q0.128 value, presumably representing an inverse, completing a division operation.
Parameters
[in] o The inverse operand.
See also
Invert
MulByInvert() [3/3]
void ns3::int64x64_t::MulByInvert (const int64x64_t & o) inline
Multiply this value by a Q0.128 value, presumably representing an inverse, completing a division operation.
Parameters
[in] o The inverse operand.
Note
There is no difference between Q64.64 and Q0.128 in this implementation, so this function is a simple multiply.
Definition at line 238 of file int64x64-double.h.
References _v.
operator=() [1/3]
int64x64_t& ns3::int64x64_t::operator= (const int64x64_t & o) inline
Assignment.
Parameters
[in] o Value to assign to this int64x64_t.
Returns
This int64x64_t.
Definition at line 195 of file int64x64-128.h.
References _v.
operator=() [2/3]
int64x64_t& ns3::int64x64_t::operator= (const int64x64_t & o) inline
Assignment.
Parameters
[in] o Value to assign to this int64x64_t.
Returns
a copy of o
Definition at line 188 of file int64x64-cairo.h.
References _v.
operator=() [3/3]
int64x64_t& ns3::int64x64_t::operator= (const int64x64_t & o) inline
Assignment.
Parameters
[in] o Value to assign to this int64x64_t.
Returns
a copy of o
Definition at line 151 of file int64x64-double.h.
References _v.
Udiv() [1/2]
cairo_uint128_t ns3::int64x64_t::Udiv (const cairo_uint128_t a, const cairo_uint128_t b) static private
Unsigned division of Q64.64 values.
Parameters
[in] a Numerator.
[in] b Denominator.
Returns
The Q64.64 representation of a / b
Definition at line 128 of file int64x64-cairo.cc.
References _cairo_int128_lsl, _cairo_uint128_add(), _cairo_uint128_divrem(), _cairo_uint128_eq(), _cairo_uint128_lsl(), _cairo_uint128_lt(), _cairo_uint128_rsl(), _cairo_uint32_to_uint128(), HPCAIRO_MASK_HI_BIT, NS_ASSERT_MSG(), cairo_uquorem128_t::quo, and cairo_uquorem128_t::rem.
Udiv() [2/2]
uint128_t ns3::int64x64_t::Udiv (const uint128_t a, const uint128_t b) static private
Unsigned division of Q64.64 values.
Parameters
[in] a Numerator.
[in] b Denominator.
Returns
The Q64.64 representation of a / b.
Definition at line 122 of file int64x64-128.cc.
References HP128_MASK_HI_BIT, and NS_ASSERT_MSG().
Referenced by Div(), and Invert().
Umul() [1/2]
cairo_uint128_t ns3::int64x64_t::Umul (const cairo_uint128_t a, const cairo_uint128_t b) static private
Unsigned multiplication of Q64.64 values.
Mathematically this should produce a Q128.128 value; we keep the central 128 bits, representing the Q64.64 result. We assert on integer overflow beyond the 64-bit integer portion.
Parameters
[in] a First factor.
[in] b Second factor.
Returns
The Q64.64 product.
Internal:
It might be tempting to just use a * b and be done with it, but it's not that simple. With a and b as 128-bit integers, a * b mathematically produces a 256-bit result, which the computer truncates to the lowest 128 bits. In our case, where a and b are interpreted as Q64.64 fixed point numbers, the multiplication mathematically produces a Q128.128 fixed point number. We want the middle 128 bits from the result, truncating both the high and low 64 bits. To achieve this, we carry out the multiplication explicitly with 64-bit operands and 128-bit intermediate results.
Definition at line 83 of file int64x64-cairo.cc.
References _cairo_uint128_add(), _cairo_uint128_lsl(), _cairo_uint64_to_uint128(), _cairo_uint64x64_128_mul(), and NS_ABORT_MSG_IF.
Umul() [2/2]
uint128_t ns3::int64x64_t::Umul (const uint128_t a, const uint128_t b) static private
Unsigned multiplication of Q64.64 values.
Mathematically this should produce a Q128.128 value; we keep the central 128 bits, representing the Q64.64 result. We assert on integer overflow beyond the 64-bit integer portion.
Parameters
[in] a First factor.
[in] b Second factor.
Returns
The Q64.64 product.
Internal:
It might be tempting to just use a * b and be done with it, but it's not that simple. With a and b as 128-bit integers, a * b mathematically produces a 256-bit result, which the computer truncates to the lowest 128 bits. In our case, where a and b are interpreted as Q64.64 fixed point numbers, the multiplication mathematically produces a Q128.128 fixed point number. We want the middle 128 bits from the result, truncating both the high and low 64 bits. To achieve this, we carry out the multiplication explicitly with 64-bit operands and 128-bit intermediate results.
Definition at line 73 of file int64x64-128.cc.
References HP_MASK_HI, HP_MASK_LO, and NS_ABORT_MSG_IF.
Referenced by Mul().
UmulByInvert() [1/2]
cairo_uint128_t ns3::int64x64_t::UmulByInvert (const cairo_uint128_t a, const cairo_uint128_t b) static private
Unsigned multiplication of Q64.64 and Q0.128 values.
Parameters
[in] a The numerator, a Q64.64 value.
[in] b The inverse of the denominator, a Q0.128 value
Returns
The product a * b, representing the ration a / b^-1
See also
Invert
Definition at line 204 of file int64x64-cairo.cc.
References _cairo_uint128_add(), and _cairo_uint64x64_128_mul().
UmulByInvert() [2/2]
uint128_t ns3::int64x64_t::UmulByInvert (const uint128_t a, const uint128_t b) static private
Unsigned multiplication of Q64.64 and Q0.128 values.
Parameters
[in] a The numerator, a Q64.64 value.
[in] b The inverse of the denominator, a Q0.128 value
Returns
The product a * b, representing the ration a / b^-1.
See also
Invert()
Definition at line 201 of file int64x64-128.cc.
References HP_MASK_LO.
Referenced by MulByInvert().
Friends And Related Function Documentation
operator! [1/3]
int64x64_t operator! (const int64x64_t & lhs) friend
Logical not operator.
Parameters
[in] lhs Left hand argument
Returns
The result of the operator.
Logical not operator
Parameters
[in] lhs Left hand argument
Returns
The result of the operator.
Definition at line 480 of file int64x64-128.h.
operator! [2/3]
int64x64_t operator! (const int64x64_t & lhs) friend
Logical not operator.
Parameters
[in] lhs Left hand argument
Returns
The result of the operator.
Logical not operator
Parameters
[in] lhs Left hand argument
Returns
The result of the operator.
Definition at line 480 of file int64x64-128.h.
operator! [3/3]
int64x64_t operator! (const int64x64_t & lhs) friend
Logical not operator.
Parameters
[in] lhs Left hand argument
Returns
The result of the operator.
Logical not operator
Parameters
[in] lhs Left hand argument
Returns
The result of the operator.
Definition at line 480 of file int64x64-128.h.
operator*= [1/3]
int64x64_t& operator*= (int64x64_t & lhs, const int64x64_t & rhs) friend
Compound multiplication operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Compound multiplication operator
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 436 of file int64x64-128.h.
operator*= [2/3]
int64x64_t& operator*= (int64x64_t & lhs, const int64x64_t & rhs) friend
Compound multiplication operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Compound multiplication operator
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 436 of file int64x64-128.h.
operator*= [3/3]
int64x64_t& operator*= (int64x64_t & lhs, const int64x64_t & rhs) friend
Compound multiplication operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Compound multiplication operator
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 436 of file int64x64-128.h.
operator+= [1/3]
int64x64_t& operator+= (int64x64_t & lhs, const int64x64_t & rhs) friend
Compound addition operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Compound addition operator
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 412 of file int64x64-128.h.
operator+= [2/3]
int64x64_t& operator+= (int64x64_t & lhs, const int64x64_t & rhs) friend
Compound addition operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Compound addition operator
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 412 of file int64x64-128.h.
operator+= [3/3]
int64x64_t& operator+= (int64x64_t & lhs, const int64x64_t & rhs) friend
Compound addition operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Compound addition operator
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 412 of file int64x64-128.h.
operator- [1/3]
int64x64_t operator- (const int64x64_t & lhs) friend
Unary operator.
Parameters
[in] lhs Left hand argument
Returns
The result of the operator.
Unary negation operator (change sign operator).
Parameters
[in] lhs Left hand argument
Returns
The result of the operator.
Unary negation operator (change sign operator)
Parameters
[in] lhs Left hand argument
Returns
The result of the operator.
Definition at line 470 of file int64x64-128.h.
operator- [2/3]
int64x64_t operator- (const int64x64_t & lhs) friend
Unary operator.
Parameters
[in] lhs Left hand argument
Returns
The result of the operator.
Unary negation operator (change sign operator).
Parameters
[in] lhs Left hand argument
Returns
The result of the operator.
Unary negation operator (change sign operator)
Parameters
[in] lhs Left hand argument
Returns
The result of the operator.
Definition at line 470 of file int64x64-128.h.
operator- [3/3]
int64x64_t operator- (const int64x64_t & lhs) friend
Unary operator.
Parameters
[in] lhs Left hand argument
Returns
The result of the operator.
Unary negation operator (change sign operator).
Parameters
[in] lhs Left hand argument
Returns
The result of the operator.
Unary negation operator (change sign operator)
Parameters
[in] lhs Left hand argument
Returns
The result of the operator.
Definition at line 470 of file int64x64-128.h.
operator-= [1/3]
int64x64_t& operator-= (int64x64_t & lhs, const int64x64_t & rhs) friend
Compound subtraction operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Compound subtraction operator
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 424 of file int64x64-128.h.
operator-= [2/3]
int64x64_t& operator-= (int64x64_t & lhs, const int64x64_t & rhs) friend
Compound subtraction operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Compound subtraction operator
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 424 of file int64x64-128.h.
operator-= [3/3]
int64x64_t& operator-= (int64x64_t & lhs, const int64x64_t & rhs) friend
Compound subtraction operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Compound subtraction operator
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 424 of file int64x64-128.h.
operator/= [1/3]
int64x64_t& operator/= (int64x64_t & lhs, const int64x64_t & rhs) friend
Compound division operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Compound division operator
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 448 of file int64x64-128.h.
operator/= [2/3]
int64x64_t& operator/= (int64x64_t & lhs, const int64x64_t & rhs) friend
Compound division operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Compound division operator
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 448 of file int64x64-128.h.
operator/= [3/3]
int64x64_t& operator/= (int64x64_t & lhs, const int64x64_t & rhs) friend
Compound division operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Compound division operator
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 448 of file int64x64-128.h.
operator< [1/3]
bool operator< (const int64x64_t & lhs, const int64x64_t & rhs) friend
Less than operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Less than operator
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 389 of file int64x64-128.h.
operator< [2/3]
bool operator< (const int64x64_t & lhs, const int64x64_t & rhs) friend
Less than operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Less than operator
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 389 of file int64x64-128.h.
operator< [3/3]
bool operator< (const int64x64_t & lhs, const int64x64_t & rhs) friend
Less than operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Less than operator
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 389 of file int64x64-128.h.
operator== [1/3]
bool operator== (const int64x64_t & lhs, const int64x64_t & rhs) friend
Arithmetic operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Equality operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 378 of file int64x64-128.h.
operator== [2/3]
bool operator== (const int64x64_t & lhs, const int64x64_t & rhs) friend
Arithmetic operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Equality operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 378 of file int64x64-128.h.
operator== [3/3]
bool operator== (const int64x64_t & lhs, const int64x64_t & rhs) friend
Arithmetic operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Equality operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 378 of file int64x64-128.h.
operator> [1/3]
bool operator> (const int64x64_t & lhs, const int64x64_t & rhs) friend
Greater operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Greater operator
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 400 of file int64x64-128.h.
operator> [2/3]
bool operator> (const int64x64_t & lhs, const int64x64_t & rhs) friend
Greater operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Greater operator
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 400 of file int64x64-128.h.
operator> [3/3]
bool operator> (const int64x64_t & lhs, const int64x64_t & rhs) friend
Greater operator.
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Greater operator
Parameters
[in] lhs Left hand argument
[in] rhs Right hand argument
Returns
The result of the operator.
Definition at line 400 of file int64x64-128.h.
Member Data Documentation
_v [1/3]
int128_t ns3::int64x64_t::_v private
The Q64.64 value.
Definition at line 366 of file int64x64-128.h.
Referenced by int64x64_t(), Div(), GetDouble(), GetHigh(), GetHighLow(), GetLow(), Invert(), Mul(), MulByInvert(), ns3::operator!(), ns3::operator+=(), ns3::operator-(), ns3::operator-=(), ns3::operator<(), operator=(), ns3::operator==(), and ns3::operator>().
_v [2/3]
cairo_int128_t ns3::int64x64_t::_v private
The Q64.64 value.
Definition at line 348 of file int64x64-cairo.h.
_v [3/3]
long double ns3::int64x64_t::_v private
The Q64.64 value.
Definition at line 293 of file int64x64-double.h.
HP128_MASK_HI_BIT
const uint128_t ns3::int64x64_t::HP128_MASK_HI_BIT = (((int128_t)1) << 127) static private
uint128_t high bit (sign bit).
Definition at line 48 of file int64x64-128.h.
Referenced by Udiv().
HP_MASK_HI
const uint64_t ns3::int64x64_t::HP_MASK_HI = ~HP_MASK_LO static private
Mask for sign + integer part.
Definition at line 52 of file int64x64-128.h.
Referenced by Umul().
HP_MASK_LO
static const uint64_t ns3::int64x64_t::HP_MASK_LO = 0xffffffffffffffffULL static private
Mask for fraction part.
Definition at line 50 of file int64x64-128.h.
Referenced by GetDouble(), GetLow(), Umul(), and UmulByInvert().
HPCAIRO_MASK_HI_BIT
const uint64_t ns3::int64x64_t::HPCAIRO_MASK_HI_BIT = (((uint64_t)1) << 63) static private
High bit of fractional part.
Definition at line 43 of file int64x64-cairo.h.
Referenced by Udiv().
implementation
static enum impl_type ns3::int64x64_t::implementation = int128_impl static
Type tag for this implementation.
Definition at line 52 of file int64x64-128.h.
Referenced by ns3::int64x64::test::Int64x64InvertTestCase::Check(), ns3::int64x64::test::Int64x64HiLoTestCase::Check(), ns3::int64x64::test::Int64x64DoubleTestCase::Check(), ns3::int64x64::test::Int64x64HiLoTestCase::DoRun(), ns3::int64x64::test::Int64x64InputTestCase::DoRun(), ns3::int64x64::test::Int64x64InputOutputTestCase::DoRun(), ns3::int64x64::test::Int64x64Bug1786TestCase::DoRun(), and ns3::int64x64::test::Int64x64ImplTestCase::DoRun().
The documentation for this class was generated from the following files:
src/core/model/int64x64-128.h
src/core/model/int64x64-cairo.h
src/core/model/int64x64-double.h
src/core/model/int64x64-128.cc
src/core/model/int64x64-cairo.cc