ns-3: ns3::LteUeMac Class Reference
ns3::LteUeMac Class Reference
#include "lte-ue-mac.h"
Classes
struct LcInfo
LcInfo structure.
Public Types
typedef void(* RaResponseTimeoutTracedCallback) (uint64_t imsi, bool contention, uint8_t preambleTxCounter, uint8_t maxPreambleTxLimit)
TracedCallback signature for RA response timeout events exporting IMSI, contention flag, preamble transmission counter and the max limit of preamble transmission.
Public Member Functions
LteUeMac ()
virtual ~LteUeMac ()
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
virtual void DoDispose (void)
Destructor implementation.
void DoSubframeIndication (uint32_t frameNo, uint32_t subframeNo)
Forwarded from LteUePhySapUser: trigger the start from a new frame.
LteMacSapProvider * GetLteMacSapProvider (void)
Get the LTE MAC SAP provider.
LteUeCmacSapProvider * GetLteUeCmacSapProvider (void)
Get the LTE CMAC SAP provider.
LteUePhySapUser * GetLteUePhySapUser ()
Get the PHY SAP user.
void SetComponentCarrierId (uint8_t index)
Set the component carried ID.
void SetLteUeCmacSapUser (LteUeCmacSapUser *s)
Set the LTE UE CMAC SAP user.
void SetLteUePhySapProvider (LteUePhySapProvider *s)
Set the PHY SAP Provider.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void DoAddLc (uint8_t lcId, LteUeCmacSapProvider::LogicalChannelConfig lcConfig, LteMacSapUser *msu)
Add LC function.
void DoConfigureRach (LteUeCmacSapProvider::RachConfig rc)
Configure RACH function.
void DoNotifyConnectionSuccessful ()
Notify MAC about the successful RRC connection establishment.
void DoReceiveLteControlMessage (Ptr< LteControlMessage > msg)
Receive LTE control message function.
void DoReceivePhyPdu (Ptr< Packet > p)
Receive Phy PDU function.
void DoRemoveLc (uint8_t lcId)
Remove LC function.
void DoReportBufferStatus (LteMacSapProvider::ReportBufferStatusParameters params)
Report buffers status function.
void DoReset ()
Reset function.
void DoSetImsi (uint64_t imsi)
Set IMSI.
void DoSetRnti (uint16_t rnti)
Set RNTI.
void DoStartContentionBasedRandomAccessProcedure ()
Start contention based random access procedure function.
void DoStartNonContentionBasedRandomAccessProcedure (uint16_t rnti, uint8_t rapId, uint8_t prachMask)
Start non contention based random access procedure function.
void DoTransmitPdu (LteMacSapProvider::TransmitPduParameters params)
Transmit PDU function.
void RandomlySelectAndSendRaPreamble ()
Randomly select and send RA preamble function.
void RaResponseTimeout (bool contention)
RA response timeout function.
void RecvRaResponse (BuildRarListElement_s raResponse)
Receive the RA response function.
void RefreshHarqProcessesPacketBuffer (void)
Refresh HARQ processes packet buffer function.
void SendRaPreamble (bool contention)
Send RA preamble function.
void SendReportBufferStatus (void)
Send report buffer status.
void StartWaitingForRaResponse ()
Start waiting for RA response function.
Private Attributes
uint16_t m_backoffParameter
backoff parameter
Time m_bsrLast
BSR last.
Time m_bsrPeriodicity
BSR periodicity.
LteUeCmacSapProvider * m_cmacSapProvider
CMAC SAP provider.
LteUeCmacSapUser * m_cmacSapUser
CMAC SAP user.
uint8_t m_componentCarrierId
component carrier Id --> used to address sap
uint32_t m_frameNo
frame number
bool m_freshUlBsr
true when a BSR has been received in the last TTI
uint8_t m_harqProcessId
HARQ process ID.
uint16_t m_imsi
IMSI.
std::map< uint8_t, LcInfo > m_lcInfoMap
logical channel info map
LteMacSapProvider * m_macSapProvider
MAC SAP provider.
std::vector< Ptr< PacketBurst > > m_miUlHarqProcessesPacket
Packets under transmission of the UL HARQ processes.
std::vector< uint8_t > m_miUlHarqProcessesPacketTimer
timer for packet life in the buffer
EventId m_noRaResponseReceivedEvent
no RA response received event ID
uint8_t m_preambleTransmissionCounter
preamble tranamission counter
LteUeCmacSapProvider::RachConfig m_rachConfig
RACH configuration.
bool m_rachConfigured
is RACH configured?
uint8_t m_raPreambleId
RA preamble ID.
Ptr< UniformRandomVariable > m_raPreambleUniformVariable
RA preamble random variable.
TracedCallback< uint64_t, bool, uint8_t, uint8_t > m_raResponseTimeoutTrace
The RaResponseTimeout trace source.
uint8_t m_raRnti
RA RNTI.
uint16_t m_rnti
RNTI.
uint32_t m_subframeNo
subframe number
LteUePhySapProvider * m_uePhySapProvider
UE Phy SAP provider.
LteUePhySapUser * m_uePhySapUser
UE Phy SAP user.
std::map< uint8_t, LteMacSapProvider::ReportBufferStatusParameters > m_ulBsrReceived
BSR received from RLC (the last one)
bool m_waitingForRaResponse
waiting for RA response
Friends
class UeMemberLteMacSapProvider
allow UeMemberLteMacSapProvider class friend access
class UeMemberLteUeCmacSapProvider
allow UeMemberLteUeCmacSapProvider class friend access
class UeMemberLteUePhySapUser
allow UeMemberLteUePhySapUser class friend access
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 44 of file lte-ue-mac.h.
Member Typedef Documentation
RaResponseTimeoutTracedCallback
typedef void(* ns3::LteUeMac::RaResponseTimeoutTracedCallback) (uint64_t imsi, bool contention, uint8_t preambleTxCounter, uint8_t maxPreambleTxLimit)
TracedCallback signature for RA response timeout events exporting IMSI, contention flag, preamble transmission counter and the max limit of preamble transmission.
Parameters
[in] imsi
[in] contention
[in] preambleTxCounter
[in] maxPreambleTxLimit
Definition at line 74 of file lte-ue-mac.h.
Constructor & Destructor Documentation
LteUeMac()
ns3::LteUeMac::LteUeMac ()
Definition at line 249 of file lte-ue-mac.cc.
References HARQ_PERIOD, m_cmacSapProvider, m_componentCarrierId, m_macSapProvider, m_miUlHarqProcessesPacket, m_miUlHarqProcessesPacketTimer, m_raPreambleUniformVariable, m_uePhySapUser, NS_LOG_FUNCTION, UeMemberLteMacSapProvider, UeMemberLteUeCmacSapProvider, and UeMemberLteUePhySapUser.
~LteUeMac()
ns3::LteUeMac::~LteUeMac () virtual
Definition at line 277 of file lte-ue-mac.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AssignStreams()
int64_t ns3::LteUeMac::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 918 of file lte-ue-mac.cc.
References m_raPreambleUniformVariable, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
Referenced by LteCqiGenerationDlPowerControlTestCase::DoRun().
DoAddLc()
void ns3::LteUeMac::DoAddLc (uint8_t lcId, LteUeCmacSapProvider::LogicalChannelConfig lcConfig, LteMacSapUser * msu) private
Add LC function.
Parameters
lcId the LCID
lcConfig the logical channel config
msu the MSU
Definition at line 577 of file lte-ue-mac.cc.
References ns3::LteUeMac::LcInfo::lcConfig, m_lcInfoMap, ns3::LteUeMac::LcInfo::macSapUser, NS_ASSERT_MSG(), and NS_LOG_FUNCTION.
Referenced by ns3::UeMemberLteUeCmacSapProvider::AddLc().
DoConfigureRach()
void ns3::LteUeMac::DoConfigureRach (LteUeCmacSapProvider::RachConfig rc) private
Configure RACH function.
Parameters
rc LteUeCmacSapProvider::RachConfig
Definition at line 530 of file lte-ue-mac.cc.
References m_rachConfig, m_rachConfigured, and NS_LOG_FUNCTION.
Referenced by ns3::UeMemberLteUeCmacSapProvider::ConfigureRach().
DoDispose()
void ns3::LteUeMac::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 283 of file lte-ue-mac.cc.
References ns3::Object::DoDispose(), m_cmacSapProvider, m_macSapProvider, m_miUlHarqProcessesPacket, m_uePhySapUser, and NS_LOG_FUNCTION.
DoNotifyConnectionSuccessful()
void ns3::LteUeMac::DoNotifyConnectionSuccessful () private
Notify MAC about the successful RRC connection establishment.
Definition at line 623 of file lte-ue-mac.cc.
References m_uePhySapProvider, ns3::LteUePhySapProvider::NotifyConnectionSuccessful(), and NS_LOG_FUNCTION.
Referenced by ns3::UeMemberLteUeCmacSapProvider::NotifyConnectionSuccessful().
DoReceiveLteControlMessage()
void ns3::LteUeMac::DoReceiveLteControlMessage (Ptr< LteControlMessage > msg) private
Receive LTE control message function.
Parameters
msg the LTE control message
Todo:
RRC generates the RecvRaResponse messaged for avoiding holes in transmission at PHY layer (which produce erroneous UL CQI evaluation)
Definition at line 655 of file lte-ue-mac.cc.
References ns3::LteMacSapUser::TxOpportunityParameters::bytes, ns3::LteMacSapUser::TxOpportunityParameters::componentCarrierId, ns3::Packet::Copy(), HARQ_PERIOD, ns3::LteMacSapUser::TxOpportunityParameters::harqId, ns3::LteMacSapUser::TxOpportunityParameters::layer, ns3::LteMacSapUser::TxOpportunityParameters::lcid, list, m_componentCarrierId, m_freshUlBsr, m_harqProcessId, m_lcInfoMap, m_miUlHarqProcessesPacket, m_miUlHarqProcessesPacketTimer, ns3::UlDciListElement_s::m_ndi, m_raPreambleId, m_raRnti, m_rnti, ns3::UlDciListElement_s::m_tbSize, m_uePhySapProvider, m_ulBsrReceived, m_waitingForRaResponse, NS_FATAL_ERROR, NS_LOG_DEBUG, NS_LOG_ERROR, NS_LOG_FUNCTION, NS_LOG_LOGIC(), NS_LOG_WARN, ns3::LteControlMessage::RAR, RecvRaResponse(), ns3::LteMacSapUser::TxOpportunityParameters::rnti, ns3::LteUePhySapProvider::SendMacPdu(), and ns3::LteControlMessage::UL_DCI.
Referenced by ns3::UeMemberLteUePhySapUser::ReceiveLteControlMessage().
DoReceivePhyPdu()
void ns3::LteUeMac::DoReceivePhyPdu (Ptr< Packet > p) private
Receive Phy PDU function.
Parameters
p the packet
Definition at line 630 of file lte-ue-mac.cc.
References ns3::LteRadioBearerTag::GetLcid(), ns3::LteRadioBearerTag::GetRnti(), ns3::LteMacSapUser::ReceivePduParameters::lcid, m_lcInfoMap, m_rnti, NS_LOG_WARN, ns3::LteMacSapUser::ReceivePduParameters::p, ns3::Packet::RemovePacketTag(), and ns3::LteMacSapUser::ReceivePduParameters::rnti.
Referenced by ns3::UeMemberLteUePhySapUser::ReceivePhyPdu().
DoRemoveLc()
void ns3::LteUeMac::DoRemoveLc (uint8_t lcId) private
Remove LC function.
Parameters
lcId the LCID
Definition at line 589 of file lte-ue-mac.cc.
References m_lcInfoMap, NS_ASSERT_MSG(), and NS_LOG_FUNCTION.
Referenced by ns3::UeMemberLteUeCmacSapProvider::RemoveLc().
DoReportBufferStatus()
void ns3::LteUeMac::DoReportBufferStatus (LteMacSapProvider::ReportBufferStatusParameters params) private
Report buffers status function.
Parameters
params LteMacSapProvider::ReportBufferStatusParameters
Definition at line 345 of file lte-ue-mac.cc.
References m_freshUlBsr, m_ulBsrReceived, NS_LOG_FUNCTION, and aloha::params.
Referenced by ns3::UeMemberLteMacSapProvider::ReportBufferStatus().
DoReset()
void ns3::LteUeMac::DoReset () private
Reset function.
Definition at line 597 of file lte-ue-mac.cc.
References ns3::EventId::Cancel(), m_freshUlBsr, m_lcInfoMap, m_noRaResponseReceivedEvent, m_rachConfigured, m_rnti, m_ulBsrReceived, and NS_LOG_FUNCTION.
Referenced by ns3::UeMemberLteUeCmacSapProvider::Reset().
DoSetImsi()
void ns3::LteUeMac::DoSetImsi (uint64_t imsi) private
Set IMSI.
Parameters
imsi the IMSI of the UE
Definition at line 557 of file lte-ue-mac.cc.
References m_imsi, and NS_LOG_FUNCTION.
Referenced by ns3::UeMemberLteUeCmacSapProvider::SetImsi().
DoSetRnti()
void ns3::LteUeMac::DoSetRnti (uint16_t rnti) private
Set RNTI.
Parameters
rnti the RNTI
Definition at line 550 of file lte-ue-mac.cc.
References m_rnti, and NS_LOG_FUNCTION.
Referenced by ns3::UeMemberLteUeCmacSapProvider::SetRnti().
DoStartContentionBasedRandomAccessProcedure()
void ns3::LteUeMac::DoStartContentionBasedRandomAccessProcedure () private
Start contention based random access procedure function.
Definition at line 538 of file lte-ue-mac.cc.
References m_backoffParameter, m_preambleTransmissionCounter, m_rachConfigured, NS_ASSERT_MSG(), NS_LOG_FUNCTION, and RandomlySelectAndSendRaPreamble().
Referenced by ns3::UeMemberLteUeCmacSapProvider::StartContentionBasedRandomAccessProcedure().
DoStartNonContentionBasedRandomAccessProcedure()
void ns3::LteUeMac::DoStartNonContentionBasedRandomAccessProcedure (uint16_t rnti, uint8_t rapId, uint8_t prachMask) private
Start non contention based random access procedure function.
Parameters
rnti the RNTI
rapId the RAPID
prachMask the PRACH mask
Definition at line 565 of file lte-ue-mac.cc.
References m_preambleTransmissionCounter, m_raPreambleId, m_rnti, NS_ASSERT_MSG(), NS_LOG_FUNCTION, and SendRaPreamble().
Referenced by ns3::UeMemberLteUeCmacSapProvider::StartNonContentionBasedRandomAccessProcedure().
DoSubframeIndication()
void ns3::LteUeMac::DoSubframeIndication (uint32_t frameNo, uint32_t subframeNo)
Forwarded from LteUePhySapUser: trigger the start from a new frame.
Parameters
frameNo frame number
subframeNo subframe number
Definition at line 897 of file lte-ue-mac.cc.
References HARQ_PERIOD, m_bsrLast, m_bsrPeriodicity, m_componentCarrierId, m_frameNo, m_freshUlBsr, m_harqProcessId, m_subframeNo, ns3::Simulator::Now(), NS_LOG_FUNCTION, RefreshHarqProcessesPacketBuffer(), and SendReportBufferStatus().
Referenced by ns3::UeMemberLteUePhySapUser::SubframeIndication().
DoTransmitPdu()
void ns3::LteUeMac::DoTransmitPdu (LteMacSapProvider::TransmitPduParameters params) private
Transmit PDU function.
Parameters
params LteMacSapProvider::TransmitPduParameters
Definition at line 332 of file lte-ue-mac.cc.
References HARQ_PERIOD, m_harqProcessId, m_miUlHarqProcessesPacket, m_miUlHarqProcessesPacketTimer, m_rnti, m_uePhySapProvider, NS_ASSERT_MSG(), NS_LOG_FUNCTION, aloha::params, and ns3::LteUePhySapProvider::SendMacPdu().
Referenced by ns3::UeMemberLteMacSapProvider::TransmitPdu().
GetLteMacSapProvider()
LteMacSapProvider * ns3::LteUeMac::GetLteMacSapProvider (void)
Get the LTE MAC SAP provider.
Returns
a pointer to the LTE MAC SAP provider
Definition at line 308 of file lte-ue-mac.cc.
References m_macSapProvider.
GetLteUeCmacSapProvider()
LteUeCmacSapProvider * ns3::LteUeMac::GetLteUeCmacSapProvider (void)
Get the LTE CMAC SAP provider.
Returns
a pointer to the LTE CMAC SAP provider
Definition at line 320 of file lte-ue-mac.cc.
References m_cmacSapProvider.
GetLteUePhySapUser()
LteUePhySapUser * ns3::LteUeMac::GetLteUePhySapUser ()
Get the PHY SAP user.
Returns
a pointer to the SAP user of the PHY
Definition at line 295 of file lte-ue-mac.cc.
References m_uePhySapUser.
GetTypeId()
TypeId ns3::LteUeMac::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 233 of file lte-ue-mac.cc.
References m_raResponseTimeoutTrace, ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
RandomlySelectAndSendRaPreamble()
void ns3::LteUeMac::RandomlySelectAndSendRaPreamble () private
Randomly select and send RA preamble function.
Definition at line 417 of file lte-ue-mac.cc.
References ns3::UniformRandomVariable::GetInteger(), m_rachConfig, m_rachConfigured, m_raPreambleId, m_raPreambleUniformVariable, NS_ASSERT_MSG(), NS_LOG_FUNCTION, ns3::LteUeCmacSapProvider::RachConfig::numberOfRaPreambles, and SendRaPreamble().
Referenced by DoStartContentionBasedRandomAccessProcedure(), and RaResponseTimeout().
RaResponseTimeout()
void ns3::LteUeMac::RaResponseTimeout (bool contention) private
RA response timeout function.
Parameters
contention if true randomly select and send the RA preamble
Definition at line 501 of file lte-ue-mac.cc.
References m_cmacSapUser, m_imsi, m_preambleTransmissionCounter, m_rachConfig, m_raResponseTimeoutTrace, m_waitingForRaResponse, ns3::LteUeCmacSapUser::NotifyRandomAccessFailed(), NS_LOG_FUNCTION, NS_LOG_INFO, ns3::LteUeCmacSapProvider::RachConfig::preambleTransMax, RandomlySelectAndSendRaPreamble(), and SendRaPreamble().
Referenced by SendRaPreamble().
RecvRaResponse()
void ns3::LteUeMac::RecvRaResponse (BuildRarListElement_s raResponse) private
Receive the RA response function.
Parameters
raResponse RA response received
Definition at line 458 of file lte-ue-mac.cc.
References ns3::LteMacSapUser::TxOpportunityParameters::bytes, ns3::EventId::Cancel(), ns3::LteMacSapUser::TxOpportunityParameters::componentCarrierId, ns3::LteMacSapUser::TxOpportunityParameters::harqId, ns3::LteMacSapUser::TxOpportunityParameters::layer, ns3::LteMacSapUser::TxOpportunityParameters::lcid, m_cmacSapUser, m_componentCarrierId, ns3::BuildRarListElement_s::m_grant, m_lcInfoMap, m_noRaResponseReceivedEvent, m_raPreambleId, ns3::BuildRarListElement_s::m_rnti, m_rnti, ns3::UlGrant_s::m_tbSize, m_ulBsrReceived, m_waitingForRaResponse, ns3::LteUeCmacSapUser::NotifyRandomAccessSuccessful(), NS_ASSERT, NS_ASSERT_MSG(), NS_FATAL_ERROR, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::LteMacSapUser::TxOpportunityParameters::rnti, and ns3::LteUeCmacSapUser::SetTemporaryCellRnti().
Referenced by DoReceiveLteControlMessage().
RefreshHarqProcessesPacketBuffer()
void ns3::LteUeMac::RefreshHarqProcessesPacketBuffer (void) private
Refresh HARQ processes packet buffer function.
Definition at line 872 of file lte-ue-mac.cc.
References m_miUlHarqProcessesPacket, m_miUlHarqProcessesPacketTimer, NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by DoSubframeIndication().
SendRaPreamble()
void ns3::LteUeMac::SendRaPreamble (bool contention) private
Send RA preamble function.
Parameters
contention if true randomly select and send the RA preamble
Definition at line 429 of file lte-ue-mac.cc.
References m_noRaResponseReceivedEvent, m_rachConfig, m_raPreambleId, m_raRnti, m_subframeNo, m_uePhySapProvider, ns3::MilliSeconds(), NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_INFO, RaResponseTimeout(), ns3::LteUeCmacSapProvider::RachConfig::raResponseWindowSize, ns3::Simulator::Schedule(), ns3::LteUePhySapProvider::SendRachPreamble(), and StartWaitingForRaResponse().
Referenced by DoStartNonContentionBasedRandomAccessProcedure(), RandomlySelectAndSendRaPreamble(), and RaResponseTimeout().
SendReportBufferStatus()
void ns3::LteUeMac::SendReportBufferStatus (void) private
Send report buffer status.
Definition at line 367 of file lte-ue-mac.cc.
References ns3::MacCeListElement_s::BSR, ns3::BufferSizeLevelBsr::BufferSize2BsrId(), ns3::MacCeValue_u::m_bufferStatus, m_lcInfoMap, ns3::MacCeListElement_s::m_macCeType, ns3::MacCeListElement_s::m_macCeValue, ns3::MacCeListElement_s::m_rnti, m_rnti, m_uePhySapProvider, m_ulBsrReceived, NS_ASSERT, NS_ASSERT_MSG(), NS_LOG_FUNCTION, NS_LOG_INFO, and ns3::LteUePhySapProvider::SendLteControlMessage().
Referenced by DoSubframeIndication().
SetComponentCarrierId()
void ns3::LteUeMac::SetComponentCarrierId (uint8_t index)
Set the component carried ID.
Parameters
index the component carrier ID
Definition at line 326 of file lte-ue-mac.cc.
References m_componentCarrierId.
SetLteUeCmacSapUser()
void ns3::LteUeMac::SetLteUeCmacSapUser (LteUeCmacSapUser * s)
Set the LTE UE CMAC SAP user.
Parameters
s the LTE UE CMAC SAP User
Definition at line 314 of file lte-ue-mac.cc.
References m_cmacSapUser.
SetLteUePhySapProvider()
void ns3::LteUeMac::SetLteUePhySapProvider (LteUePhySapProvider * s)
Set the PHY SAP Provider.
Parameters
s a pointer to the PHY SAP Provider
Definition at line 301 of file lte-ue-mac.cc.
References m_uePhySapProvider.
StartWaitingForRaResponse()
void ns3::LteUeMac::StartWaitingForRaResponse () private
Start waiting for RA response function.
Definition at line 451 of file lte-ue-mac.cc.
References m_waitingForRaResponse, and NS_LOG_FUNCTION.
Referenced by SendRaPreamble().
Friends And Related Function Documentation
UeMemberLteMacSapProvider
friend class UeMemberLteMacSapProvider friend
allow UeMemberLteMacSapProvider class friend access
Definition at line 49 of file lte-ue-mac.h.
Referenced by LteUeMac().
UeMemberLteUeCmacSapProvider
friend class UeMemberLteUeCmacSapProvider friend
allow UeMemberLteUeCmacSapProvider class friend access
Definition at line 47 of file lte-ue-mac.h.
Referenced by LteUeMac().
UeMemberLteUePhySapUser
friend class UeMemberLteUePhySapUser friend
allow UeMemberLteUePhySapUser class friend access
Definition at line 51 of file lte-ue-mac.h.
Referenced by LteUeMac().
Member Data Documentation
m_backoffParameter
uint16_t ns3::LteUeMac::m_backoffParameter private
backoff parameter
Definition at line 282 of file lte-ue-mac.h.
Referenced by DoStartContentionBasedRandomAccessProcedure().
m_bsrLast
Time ns3::LteUeMac::m_bsrLast private
BSR last.
Definition at line 267 of file lte-ue-mac.h.
Referenced by DoSubframeIndication().
m_bsrPeriodicity
Time ns3::LteUeMac::m_bsrPeriodicity private
BSR periodicity.
Definition at line 266 of file lte-ue-mac.h.
Referenced by DoSubframeIndication().
m_cmacSapProvider
LteUeCmacSapProvider* ns3::LteUeMac::m_cmacSapProvider private
CMAC SAP provider.
Definition at line 258 of file lte-ue-mac.h.
Referenced by LteUeMac(), DoDispose(), and GetLteUeCmacSapProvider().
m_cmacSapUser
LteUeCmacSapUser* ns3::LteUeMac::m_cmacSapUser private
CMAC SAP user.
Definition at line 257 of file lte-ue-mac.h.
Referenced by RaResponseTimeout(), RecvRaResponse(), and SetLteUeCmacSapUser().
m_componentCarrierId
uint8_t ns3::LteUeMac::m_componentCarrierId private
component carrier Id --> used to address sap
Definition at line 242 of file lte-ue-mac.h.
Referenced by LteUeMac(), DoReceiveLteControlMessage(), DoSubframeIndication(), RecvRaResponse(), and SetComponentCarrierId().
m_frameNo
uint32_t ns3::LteUeMac::m_frameNo private
frame number
Definition at line 286 of file lte-ue-mac.h.
Referenced by DoSubframeIndication().
m_freshUlBsr
bool ns3::LteUeMac::m_freshUlBsr private
true when a BSR has been received in the last TTI
Definition at line 269 of file lte-ue-mac.h.
Referenced by DoReceiveLteControlMessage(), DoReportBufferStatus(), DoReset(), and DoSubframeIndication().
m_harqProcessId
uint8_t ns3::LteUeMac::m_harqProcessId private
HARQ process ID.
Definition at line 271 of file lte-ue-mac.h.
Referenced by DoReceiveLteControlMessage(), DoSubframeIndication(), and DoTransmitPdu().
m_imsi
uint16_t ns3::LteUeMac::m_imsi private
IMSI.
Definition at line 276 of file lte-ue-mac.h.
Referenced by DoSetImsi(), and RaResponseTimeout().
m_lcInfoMap
std::map<uint8_t, LcInfo> ns3::LteUeMac::m_lcInfoMap private
logical channel info map
Definition at line 253 of file lte-ue-mac.h.
Referenced by DoAddLc(), DoReceiveLteControlMessage(), DoReceivePhyPdu(), DoRemoveLc(), DoReset(), RecvRaResponse(), and SendReportBufferStatus().
m_macSapProvider
LteMacSapProvider* ns3::LteUeMac::m_macSapProvider private
MAC SAP provider.
Definition at line 255 of file lte-ue-mac.h.
Referenced by LteUeMac(), DoDispose(), and GetLteMacSapProvider().
m_miUlHarqProcessesPacket
std::vector< Ptr<PacketBurst> > ns3::LteUeMac::m_miUlHarqProcessesPacket private
Packets under transmission of the UL HARQ processes.
Definition at line 272 of file lte-ue-mac.h.
Referenced by LteUeMac(), DoDispose(), DoReceiveLteControlMessage(), DoTransmitPdu(), and RefreshHarqProcessesPacketBuffer().
m_miUlHarqProcessesPacketTimer
std::vector< uint8_t > ns3::LteUeMac::m_miUlHarqProcessesPacketTimer private
timer for packet life in the buffer
Definition at line 273 of file lte-ue-mac.h.
Referenced by LteUeMac(), DoReceiveLteControlMessage(), DoTransmitPdu(), and RefreshHarqProcessesPacketBuffer().
m_noRaResponseReceivedEvent
EventId ns3::LteUeMac::m_noRaResponseReceivedEvent private
no RA response received event ID
Definition at line 283 of file lte-ue-mac.h.
Referenced by DoReset(), RecvRaResponse(), and SendRaPreamble().
m_preambleTransmissionCounter
uint8_t ns3::LteUeMac::m_preambleTransmissionCounter private
preamble tranamission counter
Definition at line 281 of file lte-ue-mac.h.
Referenced by DoStartContentionBasedRandomAccessProcedure(), DoStartNonContentionBasedRandomAccessProcedure(), and RaResponseTimeout().
m_rachConfig
LteUeCmacSapProvider::RachConfig ns3::LteUeMac::m_rachConfig private
RACH configuration.
Definition at line 279 of file lte-ue-mac.h.
Referenced by DoConfigureRach(), RandomlySelectAndSendRaPreamble(), RaResponseTimeout(), and SendRaPreamble().
m_rachConfigured
bool ns3::LteUeMac::m_rachConfigured private
is RACH configured?
Definition at line 278 of file lte-ue-mac.h.
Referenced by DoConfigureRach(), DoReset(), DoStartContentionBasedRandomAccessProcedure(), and RandomlySelectAndSendRaPreamble().
m_raPreambleId
uint8_t ns3::LteUeMac::m_raPreambleId private
RA preamble ID.
Definition at line 280 of file lte-ue-mac.h.
Referenced by DoReceiveLteControlMessage(), DoStartNonContentionBasedRandomAccessProcedure(), RandomlySelectAndSendRaPreamble(), RecvRaResponse(), and SendRaPreamble().
m_raPreambleUniformVariable
Ptr<UniformRandomVariable> ns3::LteUeMac::m_raPreambleUniformVariable private
RA preamble random variable.
Definition at line 284 of file lte-ue-mac.h.
Referenced by LteUeMac(), AssignStreams(), and RandomlySelectAndSendRaPreamble().
m_raResponseTimeoutTrace
TracedCallback<uint64_t, bool, uint8_t, uint8_t> ns3::LteUeMac::m_raResponseTimeoutTrace private
The RaResponseTimeout trace source.
Fired RA response timeout. Exporting IMSI, contention flag, preamble transmission counter and the max limit of preamble transmission.
Definition at line 296 of file lte-ue-mac.h.
Referenced by GetTypeId(), and RaResponseTimeout().
m_raRnti
uint8_t ns3::LteUeMac::m_raRnti private
RA RNTI.
Definition at line 288 of file lte-ue-mac.h.
Referenced by DoReceiveLteControlMessage(), and SendRaPreamble().
m_rnti
uint16_t ns3::LteUeMac::m_rnti private
RNTI.
Definition at line 275 of file lte-ue-mac.h.
Referenced by DoReceiveLteControlMessage(), DoReceivePhyPdu(), DoReset(), DoSetRnti(), DoStartNonContentionBasedRandomAccessProcedure(), DoTransmitPdu(), RecvRaResponse(), and SendReportBufferStatus().
m_subframeNo
uint32_t ns3::LteUeMac::m_subframeNo private
subframe number
Definition at line 287 of file lte-ue-mac.h.
Referenced by DoSubframeIndication(), and SendRaPreamble().
m_uePhySapProvider
LteUePhySapProvider* ns3::LteUeMac::m_uePhySapProvider private
UE Phy SAP provider.
Definition at line 260 of file lte-ue-mac.h.
Referenced by DoNotifyConnectionSuccessful(), DoReceiveLteControlMessage(), DoTransmitPdu(), SendRaPreamble(), SendReportBufferStatus(), and SetLteUePhySapProvider().
m_uePhySapUser
LteUePhySapUser* ns3::LteUeMac::m_uePhySapUser private
UE Phy SAP user.
Definition at line 261 of file lte-ue-mac.h.
Referenced by LteUeMac(), DoDispose(), and GetLteUePhySapUser().
m_ulBsrReceived
std::map<uint8_t, LteMacSapProvider::ReportBufferStatusParameters> ns3::LteUeMac::m_ulBsrReceived private
BSR received from RLC (the last one)
Definition at line 263 of file lte-ue-mac.h.
Referenced by DoReceiveLteControlMessage(), DoReportBufferStatus(), DoReset(), RecvRaResponse(), and SendReportBufferStatus().
m_waitingForRaResponse
bool ns3::LteUeMac::m_waitingForRaResponse private
waiting for RA response
Definition at line 289 of file lte-ue-mac.h.
Referenced by DoReceiveLteControlMessage(), RaResponseTimeout(), RecvRaResponse(), and StartWaitingForRaResponse().
The documentation for this class was generated from the following files:
src/lte/model/lte-ue-mac.h
src/lte/model/lte-ue-mac.cc