ns-3: ns3::CfParameterSet Class Reference
ns3::CfParameterSet Class Reference
Wifi Models
The CF Parameter Set.
#include "cf-parameter-set.h"
Public Member Functions
CfParameterSet ()
uint8_t DeserializeInformationField (Buffer::Iterator start, uint8_t length)
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
WifiInformationElementId ElementId () const
uint8_t GetCFPCount (void) const
Return the CFP Count in DTIM frames unit.
uint64_t GetCFPDurRemainingUs (void) const
Return the remaining CFP duration in microseconds.
uint64_t GetCFPMaxDurationUs (void) const
Return the maximum CFP duration in microseconds.
uint8_t GetCFPPeriod (void) const
Return the CFP Period in DTIM frames unit.
uint8_t GetInformationFieldSize () const
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
uint16_t GetSerializedSize () const
Buffer::Iterator Serialize (Buffer::Iterator start) const
void SerializeInformationField (Buffer::Iterator start) const
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
void SetCFPCount (uint8_t count)
Set the CFP Count in DTIM frames unit.
void SetCFPDurRemainingUs (uint64_t durRemaining)
Set the remaining CFP duration in microseconds.
void SetCFPMaxDurationUs (uint64_t maxDuration)
Set the maximum CFP duration in microseconds.
void SetCFPPeriod (uint8_t period)
Set the CFP Period in DTIM frames unit.
void SetPcfSupported (uint8_t pcfSupported)
Set PCF supported function.
Public Member Functions inherited from ns3::WifiInformationElement
virtual ~WifiInformationElement ()
Buffer::Iterator Deserialize (Buffer::Iterator i)
Deserialize entire IE, which must be present.
Buffer::Iterator DeserializeIfPresent (Buffer::Iterator i)
Deserialize entire IE if it is present.
virtual WifiInformationElementId ElementIdExt () const
uint16_t GetSerializedSize () const
Get the size of the serialized IE including Element ID and length fields.
virtual bool operator== (WifiInformationElement const &a) const
Compare two IEs for equality by ID & Length, and then through memcmp of serialised version.
virtual void Print (std::ostream &os) const
Generate human-readable form of IE.
Buffer::Iterator Serialize (Buffer::Iterator i) const
Serialize entire IE including Element ID and length fields.
Public Member Functions inherited from ns3::SimpleRefCount< WifiInformationElement >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
uint8_t m_CFPCount
CFP Count.
uint64_t m_CFPDurRemaining
CFP remaining duration in microseconds.
uint64_t m_CFPMaxDuration
CFP maximum duration in microseconds.
uint8_t m_CFPPeriod
CFP Period.
uint8_t m_pcfSupported
This is used to decide if this element should be added to the frame or not.
Detailed Description
The CF Parameter Set.
This class knows how to serialise and deserialise the CF Parameter Set.
Definition at line 34 of file cf-parameter-set.h.
Constructor & Destructor Documentation
CfParameterSet()
ns3::CfParameterSet::CfParameterSet ()
Definition at line 25 of file cf-parameter-set.cc.
Member Function Documentation
DeserializeInformationField()
uint8_t ns3::CfParameterSet::DeserializeInformationField (Buffer::Iterator start, uint8_t length) virtual
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
length
Returns
the number of bytes read
Implements ns3::WifiInformationElement.
Definition at line 87 of file cf-parameter-set.cc.
References m_CFPCount, m_CFPDurRemaining, m_CFPMaxDuration, m_CFPPeriod, NS_ASSERT, ns3::Buffer::Iterator::ReadLsbtohU16(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
ElementId()
WifiInformationElementId ns3::CfParameterSet::ElementId () const virtual
Returns
Own unique Element ID
Implements ns3::WifiInformationElement.
Definition at line 35 of file cf-parameter-set.cc.
References IE_CF_PARAMETER_SET.
GetCFPCount()
uint8_t ns3::CfParameterSet::GetCFPCount (void) const
Return the CFP Count in DTIM frames unit.
Returns
the CFP Count in DTIM frames unit
Definition at line 102 of file cf-parameter-set.cc.
References m_CFPCount.
Referenced by ns3::operator<<(), and ns3::StaWifiMac::Receive().
GetCFPDurRemainingUs()
uint64_t ns3::CfParameterSet::GetCFPDurRemainingUs (void) const
Return the remaining CFP duration in microseconds.
Returns
the remaining CFP duration in microseconds
Definition at line 120 of file cf-parameter-set.cc.
References m_CFPDurRemaining.
Referenced by ns3::operator<<(), and ns3::StaWifiMac::Receive().
GetCFPMaxDurationUs()
uint64_t ns3::CfParameterSet::GetCFPMaxDurationUs (void) const
Return the maximum CFP duration in microseconds.
Returns
the maximum CFP duration in microseconds.
Definition at line 114 of file cf-parameter-set.cc.
References m_CFPMaxDuration.
Referenced by ns3::operator<<(), and ns3::StaWifiMac::Receive().
GetCFPPeriod()
uint8_t ns3::CfParameterSet::GetCFPPeriod (void) const
Return the CFP Period in DTIM frames unit.
Returns
the CFP Period in DTIM frames unit
Definition at line 108 of file cf-parameter-set.cc.
References m_CFPPeriod.
Referenced by ns3::operator<<().
GetInformationFieldSize()
uint8_t ns3::CfParameterSet::GetInformationFieldSize () const virtual
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
This is the value that will appear in the second octet of the entire IE - the length field)
Returns
the length of serialized information
Implements ns3::WifiInformationElement.
Definition at line 47 of file cf-parameter-set.cc.
References m_pcfSupported, and NS_ASSERT.
GetSerializedSize()
uint16_t ns3::CfParameterSet::GetSerializedSize () const
Definition at line 65 of file cf-parameter-set.cc.
References ns3::WifiInformationElement::GetSerializedSize(), and m_pcfSupported.
Referenced by ns3::MgtProbeResponseHeader::GetSerializedSize().
Serialize()
Buffer::Iterator ns3::CfParameterSet::Serialize (Buffer::Iterator start) const
Definition at line 55 of file cf-parameter-set.cc.
References m_pcfSupported, and ns3::WifiInformationElement::Serialize().
Referenced by ns3::MgtProbeResponseHeader::Serialize().
SerializeInformationField()
void ns3::CfParameterSet::SerializeInformationField (Buffer::Iterator start) const virtual
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
Implements ns3::WifiInformationElement.
Definition at line 75 of file cf-parameter-set.cc.
References m_CFPCount, m_CFPDurRemaining, m_CFPMaxDuration, m_CFPPeriod, m_pcfSupported, and visualizer.core::start().
SetCFPCount()
void ns3::CfParameterSet::SetCFPCount (uint8_t count)
Set the CFP Count in DTIM frames unit.
Parameters
count the CFP Count in DTIM frames unit
Definition at line 126 of file cf-parameter-set.cc.
References m_CFPCount.
Referenced by ns3::ApWifiMac::GetCfParameterSet().
SetCFPDurRemainingUs()
void ns3::CfParameterSet::SetCFPDurRemainingUs (uint64_t durRemaining)
Set the remaining CFP duration in microseconds.
Parameters
durRemaining the remaining CFP duration in microseconds
Definition at line 144 of file cf-parameter-set.cc.
References m_CFPDurRemaining.
Referenced by ns3::ApWifiMac::GetCfParameterSet().
SetCFPMaxDurationUs()
void ns3::CfParameterSet::SetCFPMaxDurationUs (uint64_t maxDuration)
Set the maximum CFP duration in microseconds.
Parameters
maxDuration the maximum CFP duration in microseconds
Definition at line 138 of file cf-parameter-set.cc.
References m_CFPMaxDuration.
Referenced by ns3::ApWifiMac::GetCfParameterSet().
SetCFPPeriod()
void ns3::CfParameterSet::SetCFPPeriod (uint8_t period)
Set the CFP Period in DTIM frames unit.
Parameters
period the CFP Period in DTIM frames unit
Definition at line 132 of file cf-parameter-set.cc.
References m_CFPPeriod.
Referenced by ns3::ApWifiMac::GetCfParameterSet().
SetPcfSupported()
void ns3::CfParameterSet::SetPcfSupported (uint8_t pcfSupported)
Set PCF supported function.
Parameters
pcfSupported the PCF supported indicator
Definition at line 41 of file cf-parameter-set.cc.
References m_pcfSupported.
Referenced by ns3::ApWifiMac::GetCfParameterSet().
Member Data Documentation
m_CFPCount
uint8_t ns3::CfParameterSet::m_CFPCount private
CFP Count.
Definition at line 109 of file cf-parameter-set.h.
Referenced by DeserializeInformationField(), GetCFPCount(), SerializeInformationField(), and SetCFPCount().
m_CFPDurRemaining
uint64_t ns3::CfParameterSet::m_CFPDurRemaining private
CFP remaining duration in microseconds.
Definition at line 112 of file cf-parameter-set.h.
Referenced by DeserializeInformationField(), GetCFPDurRemainingUs(), SerializeInformationField(), and SetCFPDurRemainingUs().
m_CFPMaxDuration
uint64_t ns3::CfParameterSet::m_CFPMaxDuration private
CFP maximum duration in microseconds.
Definition at line 111 of file cf-parameter-set.h.
Referenced by DeserializeInformationField(), GetCFPMaxDurationUs(), SerializeInformationField(), and SetCFPMaxDurationUs().
m_CFPPeriod
uint8_t ns3::CfParameterSet::m_CFPPeriod private
CFP Period.
Definition at line 110 of file cf-parameter-set.h.
Referenced by DeserializeInformationField(), GetCFPPeriod(), SerializeInformationField(), and SetCFPPeriod().
m_pcfSupported
uint8_t ns3::CfParameterSet::m_pcfSupported private
This is used to decide if this element should be added to the frame or not.
Definition at line 115 of file cf-parameter-set.h.
Referenced by GetInformationFieldSize(), GetSerializedSize(), Serialize(), SerializeInformationField(), and SetPcfSupported().
The documentation for this class was generated from the following files:
src/wifi/model/cf-parameter-set.h
src/wifi/model/cf-parameter-set.cc