ns-3: ns3::tests::WatchdogTestCase Class Reference
ns3::tests::WatchdogTestCase Class Reference
Public Member Functions
WatchdogTestCase ()
Constructor.
virtual void DoRun (void)
Implementation to actually run this TestCase.
void Expire (int arg)
Function to invoke when Watchdog expires.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Public Attributes
bool m_expired
Flag for expired Watchdog.
int m_expiredArgument
Argument supplied to expired Watchdog.
Time m_expiredTime
Time when Watchdog expired.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Watchdog test
Definition at line 40 of file watchdog-test-suite.cc.
Constructor & Destructor Documentation
WatchdogTestCase()
ns3::tests::WatchdogTestCase::WatchdogTestCase ()
Constructor.
Definition at line 56 of file watchdog-test-suite.cc.
Member Function Documentation
DoRun()
void ns3::tests::WatchdogTestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 69 of file watchdog-test-suite.cc.
References ns3::Simulator::Destroy(), Expire(), m_expired, m_expiredArgument, m_expiredTime, ns3::MicroSeconds(), NS_TEST_ASSERT_MSG_EQ, ns3::Watchdog::Ping(), ns3::Simulator::Run(), ns3::Simulator::Schedule(), ns3::Seconds(), ns3::Watchdog::SetArguments(), and ns3::Watchdog::SetFunction().
Expire()
void ns3::tests::WatchdogTestCase::Expire (int arg)
Function to invoke when Watchdog expires.
Parameters
arg The argument passed.
Definition at line 61 of file watchdog-test-suite.cc.
References m_expired, m_expiredArgument, m_expiredTime, and ns3::Simulator::Now().
Referenced by DoRun().
Member Data Documentation
m_expired
bool ns3::tests::WatchdogTestCase::m_expired
Flag for expired Watchdog.
Definition at line 51 of file watchdog-test-suite.cc.
Referenced by DoRun(), and Expire().
m_expiredArgument
int ns3::tests::WatchdogTestCase::m_expiredArgument
Argument supplied to expired Watchdog.
Definition at line 53 of file watchdog-test-suite.cc.
Referenced by DoRun(), and Expire().
m_expiredTime
Time ns3::tests::WatchdogTestCase::m_expiredTime
Time when Watchdog expired.
Definition at line 52 of file watchdog-test-suite.cc.
Referenced by DoRun(), and Expire().
The documentation for this class was generated from the following file:
src/core/test/watchdog-test-suite.cc