ns-3: ns3::SSManager Class Reference
ns3::SSManager Class Reference
WiMAX Models
this class manages a list of SSrecords
#include "ss-manager.h"
Public Member Functions
SSManager (void)
~SSManager (void)
SSRecord * CreateSSRecord (const Mac48Address &macAddress)
Create SS record.
void DeleteSSRecord (Cid cid)
Delete SS record.
Mac48Address GetMacAddress (Cid cid) const
Get MAC address by CID.
uint32_t GetNRegisteredSSs (void) const
Get number of registered SSs.
uint32_t GetNSSs (void) const
Get number of SSs.
SSRecord * GetSSRecord (Cid cid) const
returns the ssrecord which has been assigned this cid.
SSRecord * GetSSRecord (const Mac48Address &macAddress) const
Get SS record.
std::vector< SSRecord * > * GetSSRecords (void) const
Get SS records.
bool IsInRecord (const Mac48Address &macAddress) const
Check if address is in record.
bool IsRegistered (const Mac48Address &macAddress) const
Check if address is registered.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
std::vector< SSRecord * > * m_ssRecords
the SS records
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
this class manages a list of SSrecords
See also
SSrecord
Definition at line 37 of file ss-manager.h.
Constructor & Destructor Documentation
SSManager()
ns3::SSManager::SSManager (void)
Definition at line 42 of file ss-manager.cc.
References m_ssRecords.
~SSManager()
ns3::SSManager::~SSManager (void)
Definition at line 47 of file ss-manager.cc.
References m_ssRecords.
Member Function Documentation
CreateSSRecord()
SSRecord * ns3::SSManager::CreateSSRecord (const Mac48Address & macAddress)
Create SS record.
Parameters
macAddress the MAC address
Returns
pointer to the SS record
Definition at line 58 of file ss-manager.cc.
References m_ssRecords.
DeleteSSRecord()
void ns3::SSManager::DeleteSSRecord (Cid cid)
Delete SS record.
Parameters
cid the CID
Definition at line 134 of file ss-manager.cc.
References ns3::SSRecord::GetBasicCid(), ns3::SSRecord::GetPrimaryCid(), ns3::SSRecord::GetServiceFlows(), m_ssRecords, and ns3::ServiceFlow::SF_TYPE_ALL.
GetMacAddress()
Mac48Address ns3::SSManager::GetMacAddress (Cid cid) const
Get MAC address by CID.
Parameters
cid the CID
Returns
the MAC address
Definition at line 160 of file ss-manager.cc.
References ns3::SSRecord::GetMacAddress(), and GetSSRecord().
GetNRegisteredSSs()
uint32_t ns3::SSManager::GetNRegisteredSSs (void) const
Get number of registered SSs.
Returns
the number of registered SSs
Definition at line 172 of file ss-manager.cc.
References m_ssRecords, and ns3::WimaxNetDevice::RANGING_STATUS_SUCCESS.
GetNSSs()
uint32_t ns3::SSManager::GetNSSs (void) const
Get number of SSs.
Returns
the number of SSs
Definition at line 166 of file ss-manager.cc.
References m_ssRecords.
GetSSRecord() [1/2]
SSRecord * ns3::SSManager::GetSSRecord (Cid cid) const
returns the ssrecord which has been assigned this cid.
Since different types of cids (basic, primary, transport) are assigned different values, all cids (basic, primary and transport) of the ssrecord are matched.
Parameters
cid the cid to be matched
Returns
pointer to the ss record matching the cid
Definition at line 81 of file ss-manager.cc.
References ns3::SSRecord::GetBasicCid(), ns3::SSRecord::GetPrimaryCid(), ns3::SSRecord::GetServiceFlows(), m_ssRecords, NS_LOG_DEBUG, and ns3::ServiceFlow::SF_TYPE_ALL.
GetSSRecord() [2/2]
SSRecord * ns3::SSManager::GetSSRecord (const Mac48Address & macAddress) const
Get SS record.
Parameters
macAddress the MAC address
Returns
pointer to the SS record
Definition at line 66 of file ss-manager.cc.
References m_ssRecords, and NS_LOG_DEBUG.
Referenced by GetMacAddress(), and IsRegistered().
GetSSRecords()
std::vector< SSRecord * > * ns3::SSManager::GetSSRecords (void) const
Get SS records.
Returns
a vector of pointers to the SS records
Definition at line 108 of file ss-manager.cc.
References m_ssRecords.
GetTypeId()
TypeId ns3::SSManager::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 34 of file ss-manager.cc.
References ns3::TypeId::SetParent().
IsInRecord()
bool ns3::SSManager::IsInRecord (const Mac48Address & macAddress) const
Check if address is in record.
Parameters
macAddress the MAC address
Returns
whether the address is in the record
Definition at line 114 of file ss-manager.cc.
References m_ssRecords.
IsRegistered()
bool ns3::SSManager::IsRegistered (const Mac48Address & macAddress) const
Check if address is registered.
Parameters
macAddress the MAC address
Returns
whether the address is registered
Definition at line 127 of file ss-manager.cc.
References ns3::SSRecord::GetRangingStatus(), GetSSRecord(), and ns3::WimaxNetDevice::RANGING_STATUS_SUCCESS.
Member Data Documentation
m_ssRecords
std::vector<SSRecord*>* ns3::SSManager::m_ssRecords private
the SS records
Definition at line 107 of file ss-manager.h.
Referenced by SSManager(), ~SSManager(), CreateSSRecord(), DeleteSSRecord(), GetNRegisteredSSs(), GetNSSs(), GetSSRecord(), GetSSRecords(), and IsInRecord().
The documentation for this class was generated from the following files:
src/wimax/model/ss-manager.h
src/wimax/model/ss-manager.cc