ns-3: WaypointMobilityModelNotifyTest Class Reference
WaypointMobilityModelNotifyTest Class Reference
Mobility » mobility module tests | Test suites
Waypoint Mobility Model Notify Test.
Public Member Functions
WaypointMobilityModelNotifyTest (bool lazy)
Constructor.
virtual ~WaypointMobilityModelNotifyTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CourseChangeCallback (Ptr< const MobilityModel > model)
Course change callback.
virtual void DoRun (void)
Implementation to actually run this TestCase.
virtual void DoTeardown (void)
Implementation to do any local setup required for this TestCase.
void ForceUpdates (void)
Force updates.
Private Attributes
bool lazyNotify
lazy notify?
uint32_t mobilityCount
mobility count
std::vector< Ptr< MobilityModel > > mobilityStack
mobilty model
uint32_t waypointCount
waypoint count
std::deque< Waypoint > waypoints
waypoints
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Waypoint Mobility Model Notify Test.
Definition at line 35 of file waypoint-mobility-model-test.cc.
Constructor & Destructor Documentation
WaypointMobilityModelNotifyTest()
WaypointMobilityModelNotifyTest::WaypointMobilityModelNotifyTest (bool lazy) inline
Constructor.
Parameters
lazy lazy?
Definition at line 43 of file waypoint-mobility-model-test.cc.
~WaypointMobilityModelNotifyTest()
virtual WaypointMobilityModelNotifyTest::~WaypointMobilityModelNotifyTest () inline virtual
Definition at line 49 of file waypoint-mobility-model-test.cc.
Member Function Documentation
CourseChangeCallback()
void WaypointMobilityModelNotifyTest::CourseChangeCallback (Ptr< const MobilityModel > model) private
Course change callback.
Parameters
model the mobility model
Definition at line 142 of file waypoint-mobility-model-test.cc.
References ns3::Object::GetObject(), ns3::Time::GetSeconds(), ns3::WaypointMobilityModel::m_current, ns3::Simulator::Now(), NS_TEST_EXPECT_MSG_EQ, and ns3::Waypoint::time.
Referenced by DoRun().
DoRun()
void WaypointMobilityModelNotifyTest::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 79 of file waypoint-mobility-model-test.cc.
References ns3::WaypointMobilityModel::AddWaypoint(), CourseChangeCallback(), ns3::ObjectFactory::Create(), ns3::Simulator::Destroy(), ForceUpdates(), ns3::Object::GetObject(), ns3::Object::Initialize(), ns3::MakeCallback(), ns3::Simulator::Run(), ns3::Simulator::Schedule(), ns3::Seconds(), ns3::ObjectFactory::Set(), ns3::ObjectFactory::SetTypeId(), ns3::Simulator::Stop(), ns3::Waypoint::time, and ns3::ObjectBase::TraceConnectWithoutContext().
DoTeardown()
void WaypointMobilityModelNotifyTest::DoTeardown (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test teardown
Reimplemented from ns3::TestCase.
Definition at line 72 of file waypoint-mobility-model-test.cc.
ForceUpdates()
void WaypointMobilityModelNotifyTest::ForceUpdates (void) private
Force updates.
Definition at line 132 of file waypoint-mobility-model-test.cc.
References ns3::Object::GetObject(), and ns3::WaypointMobilityModel::Update().
Referenced by DoRun().
Member Data Documentation
lazyNotify
bool WaypointMobilityModelNotifyTest::lazyNotify private
lazy notify?
Definition at line 58 of file waypoint-mobility-model-test.cc.
mobilityCount
uint32_t WaypointMobilityModelNotifyTest::mobilityCount private
mobility count
Definition at line 55 of file waypoint-mobility-model-test.cc.
mobilityStack
std::vector<Ptr<MobilityModel> > WaypointMobilityModelNotifyTest::mobilityStack private
mobilty model
Definition at line 54 of file waypoint-mobility-model-test.cc.
waypointCount
uint32_t WaypointMobilityModelNotifyTest::waypointCount private
waypoint count
Definition at line 56 of file waypoint-mobility-model-test.cc.
waypoints
std::deque<Waypoint> WaypointMobilityModelNotifyTest::waypoints private
waypoints
Definition at line 57 of file waypoint-mobility-model-test.cc.
The documentation for this class was generated from the following file:
src/mobility/test/waypoint-mobility-model-test.cc