ns-3: ns3::LoraMacHelper Class Reference
ns3::LoraMacHelper Class Reference
#include "lora-mac-helper.h"
Public Types
enum DeviceType { GW, ED }
Define the kind of device.
enum Regions {
EU, US, China, EU433MHz,
Australia, CN, AS923MHz, SouthKorea
}
Define the operational region.
Public Member Functions
LoraMacHelper ()
Create a mac helper without any parameter set.
Ptr< LoraMac > Create (Ptr< Node > node, Ptr< NetDevice > device) const
Create the LoRaMac instance and connect it to a device.
void Set (std::string name, const AttributeValue &v)
Set an attribute of the underlying MAC object.
void SetAddressGenerator (Ptr< LoraDeviceAddressGenerator > addrGen)
Set the address generator to use for creation of these nodes.
void SetDeviceType (enum DeviceType dt)
Set the kind of MAC this helper will create.
void SetRegion (enum Regions region)
Set the region in which the device is to operate.
Static Public Member Functions
static void SetSpreadingFactorsUp (NodeContainer endDevices, NodeContainer gateways, Ptr< LoraChannel > channel)
Set up the end device's data rates This function assumes we are using the following convention: SF7 -> DR5 SF8 -> DR4 SF9 -> DR3 SF10 -> DR2 SF11 -> DR1 SF12 -> DR0.
Private Member Functions
void ApplyCommonEuConfigurations (Ptr< LoraMac > loraMac) const
Apply configurations that are common both for the GatewayLoraMac and the EndDeviceLoraMac classes.
void ConfigureForEuRegion (Ptr< EndDeviceLoraMac > edMac) const
Perform region-specific configurations for the 868 MHz EU band.
void ConfigureForEuRegion (Ptr< GatewayLoraMac > gwMac) const
Perform region-specific configurations for the 868 MHz EU band.
Private Attributes
Ptr< LoraDeviceAddressGenerator > m_addrGen
Pointer to the address generator to use.
enum DeviceType m_deviceType
The kind of device to install.
ObjectFactory m_mac
enum Regions m_region
The region in which the device will operate.
Detailed Description
Definition at line 35 of file lora-mac-helper.h.
Member Enumeration Documentation
DeviceType
enum ns3::LoraMacHelper::DeviceType
Define the kind of device.
Can be either GW (Gateway) or ED (End Device).
Enumerator
GW
ED
Definition at line 42 of file lora-mac-helper.h.
Regions
enum ns3::LoraMacHelper::Regions
Define the operational region.
Enumerator
EU
US
China
EU433MHz
Australia
CN
AS923MHz
SouthKorea
Definition at line 51 of file lora-mac-helper.h.
Constructor & Destructor Documentation
LoraMacHelper()
ns3::LoraMacHelper::LoraMacHelper ()
Create a mac helper without any parameter set.
The user must set them all to be able to call Install later.
Definition at line 30 of file lora-mac-helper.cc.
Member Function Documentation
ApplyCommonEuConfigurations()
void ns3::LoraMacHelper::ApplyCommonEuConfigurations (Ptr< LoraMac > loraMac) const private
Apply configurations that are common both for the GatewayLoraMac and the EndDeviceLoraMac classes.
Definition at line 199 of file lora-mac-helper.cc.
References ns3::LogicalLoraChannelHelper::AddChannel(), ns3::LogicalLoraChannelHelper::AddSubBand(), and NS_LOG_FUNCTION_NOARGS.
Referenced by ConfigureForEuRegion().
ConfigureForEuRegion() [1/2]
void ns3::LoraMacHelper::ConfigureForEuRegion (Ptr< EndDeviceLoraMac > edMac) const private
Perform region-specific configurations for the 868 MHz EU band.
Definition at line 124 of file lora-mac-helper.cc.
References ApplyCommonEuConfigurations(), and NS_LOG_FUNCTION_NOARGS.
Referenced by Create().
ConfigureForEuRegion() [2/2]
void ns3::LoraMacHelper::ConfigureForEuRegion (Ptr< GatewayLoraMac > gwMac) const private
Perform region-specific configurations for the 868 MHz EU band.
Definition at line 161 of file lora-mac-helper.cc.
References ApplyCommonEuConfigurations(), ns3::Object::GetObject(), gwPhy, NS_LOG_DEBUG, NS_LOG_FUNCTION_NOARGS, and ns3::GatewayLoraPhy::ResetReceptionPaths().
Create()
Ptr< LoraMac > ns3::LoraMacHelper::Create (Ptr< Node > node, Ptr< NetDevice > device) const
Create the LoRaMac instance and connect it to a device.
Parameters
node the node on which we wish to create a wifi MAC.
device the device within which this MAC will be created.
Returns
a newly-created LoraMac object.
Definition at line 72 of file lora-mac-helper.cc.
References ConfigureForEuRegion(), ns3::ObjectFactory::Create(), ED, EU, m_addrGen, m_deviceType, m_mac, m_region, third::mac, and NS_LOG_ERROR.
Referenced by ns3::LoraHelper::Install().
Set()
void ns3::LoraMacHelper::Set (std::string name, const AttributeValue & v)
Set an attribute of the underlying MAC object.
Parameters
name the name of the attribute to set.
v the value of the attribute.
Definition at line 36 of file lora-mac-helper.cc.
References m_mac, and ns3::ObjectFactory::Set().
SetAddressGenerator()
void ns3::LoraMacHelper::SetAddressGenerator (Ptr< LoraDeviceAddressGenerator > addrGen)
Set the address generator to use for creation of these nodes.
Definition at line 58 of file lora-mac-helper.cc.
References m_addrGen, and NS_LOG_FUNCTION.
Referenced by Reset().
SetDeviceType()
void ns3::LoraMacHelper::SetDeviceType (enum DeviceType dt)
Set the kind of MAC this helper will create.
Parameters
dt the device type (either gateway or end device).
Definition at line 42 of file lora-mac-helper.cc.
References ED, GW, m_deviceType, m_mac, NS_LOG_FUNCTION, and ns3::ObjectFactory::SetTypeId().
Referenced by Reset().
SetRegion()
void ns3::LoraMacHelper::SetRegion (enum Regions region)
Set the region in which the device is to operate.
Definition at line 66 of file lora-mac-helper.cc.
References m_region.
Referenced by Reset().
SetSpreadingFactorsUp()
void ns3::LoraMacHelper::SetSpreadingFactorsUp (NodeContainer endDevices, NodeContainer gateways, Ptr< LoraChannel > channel) static
Set up the end device's data rates This function assumes we are using the following convention: SF7 -> DR5 SF8 -> DR4 SF9 -> DR3 SF10 -> DR2 SF11 -> DR1 SF12 -> DR0.
Definition at line 237 of file lora-mac-helper.cc.
References channel, endDevices, gatewayPhy, gateways, ns3::Node::GetDevice(), ns3::Object::GetObject(), ns3::LoraChannel::GetRxPower(), third::mac, NS_ASSERT, NS_LOG_FUNCTION_NOARGS, and ns3::GatewayLoraPhy::sensitivity.
Member Data Documentation
m_addrGen
Ptr<LoraDeviceAddressGenerator> ns3::LoraMacHelper::m_addrGen private
Pointer to the address generator to use.
Definition at line 136 of file lora-mac-helper.h.
Referenced by Create(), and SetAddressGenerator().
m_deviceType
enum DeviceType ns3::LoraMacHelper::m_deviceType private
The kind of device to install.
Definition at line 136 of file lora-mac-helper.h.
Referenced by Create(), and SetDeviceType().
m_mac
ObjectFactory ns3::LoraMacHelper::m_mac private
Definition at line 135 of file lora-mac-helper.h.
Referenced by Create(), Set(), and SetDeviceType().
m_region
enum Regions ns3::LoraMacHelper::m_region private
The region in which the device will operate.
Definition at line 136 of file lora-mac-helper.h.
Referenced by Create(), and SetRegion().
The documentation for this class was generated from the following files:
src/lorawan/helper/lora-mac-helper.h
src/lorawan/helper/lora-mac-helper.cc