ns-3: ns3::QueueDiscItem Class Reference
ns3::QueueDiscItem Class Reference abstract
Network
#include "queue-item.h"
Public Member Functions
QueueDiscItem (Ptr< Packet > p, const Address &addr, uint16_t protocol)
Create a queue disc item.
virtual ~QueueDiscItem ()
virtual void AddHeader (void)=0
Add the header to the packet.
Address GetAddress (void) const
Get the MAC address included in this item.
uint16_t GetProtocol (void) const
Get the L3 protocol included in this item.
Time GetTimeStamp (void) const
Get the timestamp included in this item.
uint8_t GetTxQueueIndex (void) const
Get the transmission queue index included in this item.
virtual uint32_t Hash (uint32_t perturbation=0) const
Computes the hash of various fields of the packet header.
virtual bool Mark (void)=0
Marks the packet as a substitute for dropping it, such as for Explicit Congestion Notification.
virtual void Print (std::ostream &os) const
Print the item contents.
void SetTimeStamp (Time t)
Set the timestamp included in this item.
void SetTxQueueIndex (uint8_t txq)
Set the transmission queue index to store in this item.
Public Member Functions inherited from ns3::QueueItem
QueueItem (Ptr< Packet > p)
Create a queue item containing a packet.
virtual ~QueueItem ()
Ptr< Packet > GetPacket (void) const
virtual uint32_t GetSize (void) const
Use this method (instead of GetPacket ()->GetSize ()) to get the packet size.
virtual bool GetUint8Value (Uint8Values field, uint8_t &value) const
Retrieve the value of a given field from the packet, if present.
Public Member Functions inherited from ns3::SimpleRefCount< QueueItem >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Member Functions
QueueDiscItem ()
Default constructor.
QueueDiscItem (const QueueDiscItem &)
Copy constructor.
QueueDiscItem & operator= (const QueueDiscItem &)
Assignment operator.
Private Attributes
Address m_address
MAC destination address.
uint16_t m_protocol
L3 Protocol number.
Time m_tstamp
timestamp when the packet was enqueued
uint8_t m_txq
Transmission queue index.
Additional Inherited Members
Public Types inherited from ns3::QueueItem
typedef void(* TracedCallback) (Ptr< const QueueItem > item)
TracedCallback signature for Ptr<QueueItem>
enum Uint8Values { IP_DSFIELD }
1-byte fields of the packet whose value can be retrieved, if present
Detailed Description
QueueDiscItem is the abstract base class for items that are stored in a queue disc. It is derived from QueueItem (which only consists of a Ptr<Packet>) to additionally store the destination MAC address, the L3 protocol number and the transmission queue index,
Definition at line 148 of file queue-item.h.
Constructor & Destructor Documentation
QueueDiscItem() [1/3]
ns3::QueueDiscItem::QueueDiscItem (Ptr< Packet > p, const Address & addr, uint16_t protocol)
Create a queue disc item.
Parameters
p the packet included in the created item.
addr the destination MAC address
protocol the L3 protocol number
Definition at line 76 of file queue-item.cc.
References NS_LOG_FUNCTION.
~QueueDiscItem()
ns3::QueueDiscItem::~QueueDiscItem () virtual
Definition at line 85 of file queue-item.cc.
References NS_LOG_FUNCTION.
QueueDiscItem() [2/3]
ns3::QueueDiscItem::QueueDiscItem () private
Default constructor.
Defined and unimplemented to avoid misuse
QueueDiscItem() [3/3]
ns3::QueueDiscItem::QueueDiscItem (const QueueDiscItem &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Member Function Documentation
AddHeader()
virtual void ns3::QueueDiscItem::AddHeader (void) pure virtual
Add the header to the packet.
Subclasses may keep header and payload separate to allow manipulating the header, so this method allows to add the header to the packet before sending the packet to the device.
Implemented in QueueDiscTestItem, TbfQueueDiscTestItem, RedQueueDiscTestItem, qdTestItem, PrioQueueDiscTestItem, PieQueueDiscTestItem, FifoQueueDiscTestItem, CodelQueueDiscTestItem, CobaltQueueDiscTestItem, AredQueueDiscTestItem, ns3::Ipv6QueueDiscItem, ns3::Ipv4QueueDiscItem, and ns3::ArpQueueDiscItem.
GetAddress()
Address ns3::QueueDiscItem::GetAddress (void) const
Get the MAC address included in this item.
Returns
the MAC address included in this item.
Definition at line 91 of file queue-item.cc.
References m_address, and NS_LOG_FUNCTION.
Referenced by ns3::ArpQueueDiscItem::Print(), ns3::Ipv4QueueDiscItem::Print(), and ns3::Ipv6QueueDiscItem::Print().
GetProtocol()
uint16_t ns3::QueueDiscItem::GetProtocol (void) const
Get the L3 protocol included in this item.
Returns
the L3 protocol included in this item.
Definition at line 98 of file queue-item.cc.
References m_protocol, and NS_LOG_FUNCTION.
Referenced by ns3::ArpQueueDiscItem::Print(), ns3::Ipv4QueueDiscItem::Print(), and ns3::Ipv6QueueDiscItem::Print().
GetTimeStamp()
Time ns3::QueueDiscItem::GetTimeStamp (void) const
Get the timestamp included in this item.
Returns
the timestamp included in this item.
Definition at line 119 of file queue-item.cc.
References m_tstamp, and NS_LOG_FUNCTION.
GetTxQueueIndex()
uint8_t ns3::QueueDiscItem::GetTxQueueIndex (void) const
Get the transmission queue index included in this item.
Returns
the transmission queue index included in this item.
Definition at line 105 of file queue-item.cc.
References m_txq, and NS_LOG_FUNCTION.
Referenced by ns3::ArpQueueDiscItem::Print(), ns3::Ipv4QueueDiscItem::Print(), and ns3::Ipv6QueueDiscItem::Print().
Hash()
uint32_t ns3::QueueDiscItem::Hash (uint32_t perturbation = 0) const virtual
Computes the hash of various fields of the packet header.
This method just returns 0. Subclasses should implement a reasonable hash for their protocol type, such as hashing on the TCP/IP 5-tuple.
Parameters
perturbation hash perturbation value
Returns
the hash of various fields of the packet header
Reimplemented in ns3::Ipv6QueueDiscItem, ns3::Ipv4QueueDiscItem, and ns3::ArpQueueDiscItem.
Definition at line 143 of file queue-item.cc.
References NS_LOG_WARN.
Mark()
virtual bool ns3::QueueDiscItem::Mark (void) pure virtual
Marks the packet as a substitute for dropping it, such as for Explicit Congestion Notification.
Returns
true if the packet gets marked, false otherwise
Implemented in QueueDiscTestItem, TbfQueueDiscTestItem, RedQueueDiscTestItem, qdTestItem, PrioQueueDiscTestItem, PieQueueDiscTestItem, FifoQueueDiscTestItem, CodelQueueDiscTestItem, CobaltQueueDiscTestItem, AredQueueDiscTestItem, ns3::Ipv6QueueDiscItem, ns3::Ipv4QueueDiscItem, and ns3::ArpQueueDiscItem.
operator=()
QueueDiscItem& ns3::QueueDiscItem::operator= (const QueueDiscItem &) private
Assignment operator.
Defined and unimplemented to avoid misuse
Returns
Print()
void ns3::QueueDiscItem::Print (std::ostream & os) const virtual
Print the item contents.
Parameters
os output stream in which the data should be printed.
Reimplemented from ns3::QueueItem.
Reimplemented in ns3::Ipv6QueueDiscItem, ns3::Ipv4QueueDiscItem, and ns3::ArpQueueDiscItem.
Definition at line 133 of file queue-item.cc.
References ns3::QueueItem::GetPacket(), m_address, m_protocol, and m_txq.
SetTimeStamp()
void ns3::QueueDiscItem::SetTimeStamp (Time t)
Set the timestamp included in this item.
Parameters
t the timestamp to include in this item.
Definition at line 126 of file queue-item.cc.
References m_tstamp, and NS_LOG_FUNCTION.
SetTxQueueIndex()
void ns3::QueueDiscItem::SetTxQueueIndex (uint8_t txq)
Set the transmission queue index to store in this item.
Parameters
txq the transmission queue index to store in this item.
Definition at line 112 of file queue-item.cc.
References m_txq, and NS_LOG_FUNCTION.
Member Data Documentation
m_address
Address ns3::QueueDiscItem::m_address private
MAC destination address.
Definition at line 250 of file queue-item.h.
Referenced by GetAddress(), and Print().
m_protocol
uint16_t ns3::QueueDiscItem::m_protocol private
L3 Protocol number.
Definition at line 251 of file queue-item.h.
Referenced by GetProtocol(), and Print().
m_tstamp
Time ns3::QueueDiscItem::m_tstamp private
timestamp when the packet was enqueued
Definition at line 253 of file queue-item.h.
Referenced by GetTimeStamp(), and SetTimeStamp().
m_txq
uint8_t ns3::QueueDiscItem::m_txq private
Transmission queue index.
Definition at line 252 of file queue-item.h.
Referenced by GetTxQueueIndex(), Print(), and SetTxQueueIndex().
The documentation for this class was generated from the following files:
src/network/utils/queue-item.h
src/network/utils/queue-item.cc