ns-3: IpAddressHelper Class Reference
IpAddressHelper Class Reference
Helper to print a node's IP addresses.
Public Member Functions
void PrintIpAddresses (Ptr< Node > &n)
Print the node's IP addresses.
Detailed Description
Helper to print a node's IP addresses.
Definition at line 55 of file radvd-two-prefix.cc.
Member Function Documentation
PrintIpAddresses()
void IpAddressHelper::PrintIpAddresses (Ptr< Node > & n) inline
Print the node's IP addresses.
Parameters
n the node
Definition at line 62 of file radvd-two-prefix.cc.
References ns3::Ipv6::GetAddress(), ns3::Ipv6::GetNAddresses(), ns3::Ipv6::GetNInterfaces(), ns3::Object::GetObject(), ns3::Time::GetSeconds(), sample-rng-plot::n, and ns3::Simulator::Now().
The documentation for this class was generated from the following file:
examples/ipv6/radvd-two-prefix.cc