ns-3: ns3::Forwarder Class Reference
ns3::Forwarder Class Reference
This application forwards packets between NetDevices: LoraNetDevice -> PointToPointNetDevice and vice versa.
#include "forwarder.h"
Public Member Functions
Forwarder ()
~Forwarder ()
bool ReceiveFromLora (Ptr< NetDevice > loraNetDevice, Ptr< const Packet > packet, uint16_t protocol, const Address &sender)
Receive a packet from the LoraNetDevice.
bool ReceiveFromPointToPoint (Ptr< NetDevice > pointToPointNetDevice, Ptr< const Packet > packet, uint16_t protocol, const Address &sender)
Receive a packet from the PointToPointNetDevice.
void SetLoraNetDevice (Ptr< LoraNetDevice > loraNetDevice)
Sets the device to use to communicate with the EDs.
void SetPointToPointNetDevice (Ptr< PointToPointNetDevice > pointToPointNetDevice)
Sets the P2P device to use to communicate with the NS.
void StartApplication (void)
Start the application.
void StopApplication (void)
Stop the application.
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Ptr< LoraNetDevice > m_loraNetDevice
Pointer to the node's LoraNetDevice.
Ptr< PointToPointNetDevice > m_pointToPointNetDevice
Pointer to the P2PNetDevice we use to communicate with the NS.
Additional Inherited Members
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Protected Member Functions inherited from ns3::Application
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This application forwards packets between NetDevices: LoraNetDevice -> PointToPointNetDevice and vice versa.
Definition at line 36 of file forwarder.h.
Constructor & Destructor Documentation
Forwarder()
ns3::Forwarder::Forwarder ()
Definition at line 40 of file forwarder.cc.
References NS_LOG_FUNCTION_NOARGS.
~Forwarder()
ns3::Forwarder::~Forwarder ()
Definition at line 45 of file forwarder.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
GetTypeId()
TypeId ns3::Forwarder::GetTypeId (void) static
Definition at line 31 of file forwarder.cc.
References ns3::TypeId::SetParent().
ReceiveFromLora()
bool ns3::Forwarder::ReceiveFromLora (Ptr< NetDevice > loraNetDevice, Ptr< const Packet > packet, uint16_t protocol, const Address & sender)
Receive a packet from the LoraNetDevice.
Parameters
loraNetDevice The LoraNetDevice we received the packet from.
packet The packet we received.
protocol The protocol number associated to this packet.
sender The address of the sender.
Returns
True if we can handle the packet, false otherwise.
Definition at line 68 of file forwarder.cc.
References ns3::Packet::Copy(), m_pointToPointNetDevice, NS_LOG_FUNCTION, and packet.
Referenced by ns3::ForwarderHelper::InstallPriv().
ReceiveFromPointToPoint()
bool ns3::Forwarder::ReceiveFromPointToPoint (Ptr< NetDevice > pointToPointNetDevice, Ptr< const Packet > packet, uint16_t protocol, const Address & sender)
Receive a packet from the PointToPointNetDevice.
Definition at line 83 of file forwarder.cc.
References ns3::Packet::Copy(), m_loraNetDevice, NS_LOG_FUNCTION, and packet.
Referenced by ns3::ForwarderHelper::InstallPriv().
SetLoraNetDevice()
void ns3::Forwarder::SetLoraNetDevice (Ptr< LoraNetDevice > loraNetDevice)
Sets the device to use to communicate with the EDs.
Parameters
loraNetDevice The LoraNetDevice on this node.
Definition at line 60 of file forwarder.cc.
References m_loraNetDevice, and NS_LOG_FUNCTION.
SetPointToPointNetDevice()
void ns3::Forwarder::SetPointToPointNetDevice (Ptr< PointToPointNetDevice > pointToPointNetDevice)
Sets the P2P device to use to communicate with the NS.
Parameters
pointToPointNetDevice The P2PNetDevice on this node.
Definition at line 51 of file forwarder.cc.
References m_pointToPointNetDevice, and NS_LOG_FUNCTION.
StartApplication()
void ns3::Forwarder::StartApplication (void) virtual
Start the application.
Reimplemented from ns3::Application.
Definition at line 97 of file forwarder.cc.
References NS_LOG_FUNCTION.
StopApplication()
void ns3::Forwarder::StopApplication (void) virtual
Stop the application.
Reimplemented from ns3::Application.
Definition at line 105 of file forwarder.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Data Documentation
m_loraNetDevice
Ptr<LoraNetDevice> ns3::Forwarder::m_loraNetDevice private
Pointer to the node's LoraNetDevice.
Definition at line 89 of file forwarder.h.
Referenced by ReceiveFromPointToPoint(), and SetLoraNetDevice().
m_pointToPointNetDevice
Ptr<PointToPointNetDevice> ns3::Forwarder::m_pointToPointNetDevice private
Pointer to the P2PNetDevice we use to communicate with the NS.
Definition at line 91 of file forwarder.h.
Referenced by ReceiveFromLora(), and SetPointToPointNetDevice().
The documentation for this class was generated from the following files:
src/lorawan/model/forwarder.h
src/lorawan/model/forwarder.cc