ns-3: ns3::ErlangRandomVariable Class Reference
ns3::ErlangRandomVariable Class Reference
Core » Random Variables
The Erlang distribution Random Number Generator (RNG) that allows stream numbers to be set deterministically.
#include "random-variable-stream.h"
Public Member Functions
ErlangRandomVariable ()
Creates an Erlang distribution RNG with the default values for k and lambda.
uint32_t GetInteger (uint32_t k, uint32_t lambda)
Returns a random unsigned integer from an Erlang distribution with the specified k and lambda.
virtual uint32_t GetInteger (void)
Returns a random unsigned integer from an Erlang distribution with the current k and lambda.
uint32_t GetK (void) const
Returns the k value for the Erlang distribution returned by this RNG stream.
double GetLambda (void) const
Returns the lambda value for the Erlang distribution returned by this RNG stream.
double GetValue (uint32_t k, double lambda)
Returns a random double from an Erlang distribution with the specified k and lambda.
virtual double GetValue (void)
Returns a random double from an Erlang distribution with the current k and lambda.
Public Member Functions inherited from ns3::RandomVariableStream
RandomVariableStream ()
Default constructor.
virtual ~RandomVariableStream ()
Destructor.
int64_t GetStream (void) const
Returns the stream number for the RngStream.
bool IsAntithetic (void) const
Check if antithetic values will be generated.
void SetAntithetic (bool isAntithetic)
Specify whether antithetic values should be generated.
void SetStream (int64_t stream)
Specifies the stream number for the RngStream.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::RandomVariableStream
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
double GetExponentialValue (double mean, double bound)
Returns a random double from an exponential distribution with the specified mean and upper bound.
Private Attributes
uint32_t m_k
The k value for the Erlang distribution returned by this RNG stream.
double m_lambda
The lambda value for the Erlang distribution returned by this RNG stream.
Additional Inherited Members
Protected Member Functions inherited from ns3::RandomVariableStream
RngStream * Peek (void) const
Get the pointer to the underlying RngStream.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The Erlang distribution Random Number Generator (RNG) that allows stream numbers to be set deterministically.
This class supports the creation of objects that return random numbers from a fixed Erlang distribution. It also supports the generation of single random numbers from various Erlang distributions.
The Erlang distribution is a special case of the Gamma distribution where k (= alpha) is a non-negative integer. Erlang distributed variables can be generated using a much faster algorithm than gamma variables.
The probability density function is defined over the interval [0,) as: where and
Here is an example of how to use this class:
uint32_t k = 5;
double lambda = 2.0;
Ptr<ErlangRandomVariable> x = CreateObject<ErlangRandomVariable> ();
x->SetAttribute ("K", IntegerValue (k));
x->SetAttribute ("Lambda", DoubleValue (lambda));
// The expected value for the mean of the values returned by a
// Erlangly distributed random variable is equal to
//
//     E[value]  =  k * lambda  .
//
double value = x->GetValue ();
Definition at line 1685 of file random-variable-stream.h.
Constructor & Destructor Documentation
ErlangRandomVariable()
ns3::ErlangRandomVariable::ErlangRandomVariable ()
Creates an Erlang distribution RNG with the default values for k and lambda.
Definition at line 1097 of file random-variable-stream.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
GetExponentialValue()
double ns3::ErlangRandomVariable::GetExponentialValue (double mean, double bound) private
Returns a random double from an exponential distribution with the specified mean and upper bound.
Parameters
[in] mean Mean value of the random variables.
[in] bound Upper bound on values returned.
Returns
A floating point random value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If is a uniform variable over [0,1] and
is a value that would be returned normally, then) is the distance that would be from . The value returned in the antithetic case, , is calculated as
which now involves the log of the distance is from the 1.
Definition at line 1166 of file random-variable-stream.cc.
References ns3::RandomVariableStream::IsAntithetic(), NS_LOG_FUNCTION, ns3::RandomVariableStream::Peek(), and ns3::RngStream::RandU01().
Referenced by GetValue().
GetInteger() [1/2]
uint32_t ns3::ErlangRandomVariable::GetInteger (uint32_t k, uint32_t lambda)
Returns a random unsigned integer from an Erlang distribution with the specified k and lambda.
Parameters
[in] k K value for the Erlang distribution.
[in] lambda Lambda value for the Erlang distribution.
Returns
A random unsigned integer value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If is a uniform variable over [0,1] and is a value that would be returned normally, then) is the distance that would be from . The value returned in the antithetic case, , uses (1-u), which is the distance is from the 1.
Definition at line 1146 of file random-variable-stream.cc.
References GetValue(), and NS_LOG_FUNCTION.
GetInteger() [2/2]
uint32_t ns3::ErlangRandomVariable::GetInteger (void) virtual
Returns a random unsigned integer from an Erlang distribution with the current k and lambda.
Returns
A random unsigned integer value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If is a uniform variable over [0,1] and is a value that would be returned normally, then) is the distance that would be from . The value returned in the antithetic case, , uses (1-u), which is the distance is from the 1.
Implements ns3::RandomVariableStream.
Definition at line 1159 of file random-variable-stream.cc.
References GetValue(), m_k, m_lambda, and NS_LOG_FUNCTION.
GetK()
uint32_t ns3::ErlangRandomVariable::GetK (void) const
Returns the k value for the Erlang distribution returned by this RNG stream.
Returns
The k value for the Erlang distribution returned by this RNG stream.
Definition at line 1104 of file random-variable-stream.cc.
References m_k, and NS_LOG_FUNCTION.
GetLambda()
double ns3::ErlangRandomVariable::GetLambda (void) const
Returns the lambda value for the Erlang distribution returned by this RNG stream.
Returns
The lambda value for the Erlang distribution returned by this RNG stream.
Definition at line 1110 of file random-variable-stream.cc.
References m_lambda, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::ErlangRandomVariable::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 1080 of file random-variable-stream.cc.
References m_k, m_lambda, ns3::MakeDoubleAccessor(), ns3::MakeIntegerAccessor(), and ns3::TypeId::SetParent().
GetValue() [1/2]
double ns3::ErlangRandomVariable::GetValue (uint32_t k, double lambda)
Returns a random double from an Erlang distribution with the specified k and lambda.
Parameters
[in] k K value for the Erlang distribution.
[in] lambda Lambda value for the Erlang distribution.
Returns
A floating point random value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If is a uniform variable over [0,1] and is a value that would be returned normally, then) is the distance that would be from . The value returned in the antithetic case, , uses (1-u), which is the distance is from the 1.
Definition at line 1129 of file random-variable-stream.cc.
References GetExponentialValue(), and NS_LOG_FUNCTION.
GetValue() [2/2]
double ns3::ErlangRandomVariable::GetValue (void) virtual
Returns a random double from an Erlang distribution with the current k and lambda.
Returns
A floating point random value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If is a uniform variable over [0,1] and is a value that would be returned normally, then) is the distance that would be from . The value returned in the antithetic case, , uses (1-u), which is the distance is from the 1.
Note that we have to re-implement this method here because the method is overloaded above for the two-argument variant and the c++ name resolution rules don't work well with overloads split between parent and child classes.
Implements ns3::RandomVariableStream.
Definition at line 1153 of file random-variable-stream.cc.
References m_k, m_lambda, and NS_LOG_FUNCTION.
Referenced by GetInteger().
Member Data Documentation
m_k
uint32_t ns3::ErlangRandomVariable::m_k private
The k value for the Erlang distribution returned by this RNG stream.
Definition at line 1801 of file random-variable-stream.h.
Referenced by GetInteger(), GetK(), GetTypeId(), and GetValue().
m_lambda
double ns3::ErlangRandomVariable::m_lambda private
The lambda value for the Erlang distribution returned by this RNG stream.
Definition at line 1804 of file random-variable-stream.h.
Referenced by GetInteger(), GetLambda(), GetTypeId(), and GetValue().
The documentation for this class was generated from the following files:
src/core/model/random-variable-stream.h
src/core/model/random-variable-stream.cc