ns-3: CallbackTestClass Class Reference
CallbackTestClass Class Reference
Public Member Functions
void CheckParentalRights (void)
void TestCFive (int, int, int, int, int) const
void TestCFour (int, int, int, int) const
void TestCOne (int) const
void TestCSix (int, int, int, int, int, int) const
void TestCThree (int, int, int) const
void TestCTwo (int, int) const
void TestCZero (void) const
void TestFive (int, int, int, int, int)
void TestFour (int, int, int, int)
void TestOne (int)
void TestSix (int, int, int, int, int, int)
void TestThree (int, int, int)
void TestTwo (int, int)
void TestZero (void)
Public Member Functions inherited from CallbackTestParent
void PublicParent (void)
Additional Inherited Members
Protected Member Functions inherited from CallbackTestParent
void ProtectedParent (void)
Static Protected Member Functions inherited from CallbackTestParent
static void StaticProtectedParent (void)
Detailed Description
Definition at line 654 of file callback-test-suite.cc.
Member Function Documentation
CheckParentalRights()
void CallbackTestClass::CheckParentalRights (void) inline
Definition at line 674 of file callback-test-suite.cc.
References ns3::MakeCallback(), CallbackTestParent::ProtectedParent(), CallbackTestParent::PublicParent(), and CallbackTestParent::StaticProtectedParent().
Referenced by MakeCallbackTemplatesTestCase::DoRun().
TestCFive()
void CallbackTestClass::TestCFive (int , int , int , int , int) const inline
Definition at line 670 of file callback-test-suite.cc.
Referenced by MakeCallbackTemplatesTestCase::DoRun().
TestCFour()
void CallbackTestClass::TestCFour (int , int , int , int) const inline
Definition at line 669 of file callback-test-suite.cc.
Referenced by MakeCallbackTemplatesTestCase::DoRun().
TestCOne()
void CallbackTestClass::TestCOne (int) const inline
Definition at line 666 of file callback-test-suite.cc.
Referenced by MakeCallbackTemplatesTestCase::DoRun().
TestCSix()
void CallbackTestClass::TestCSix (int , int , int , int , int , int) const inline
Definition at line 671 of file callback-test-suite.cc.
Referenced by MakeCallbackTemplatesTestCase::DoRun().
TestCThree()
void CallbackTestClass::TestCThree (int , int , int) const inline
Definition at line 668 of file callback-test-suite.cc.
Referenced by MakeCallbackTemplatesTestCase::DoRun().
TestCTwo()
void CallbackTestClass::TestCTwo (int , int) const inline
Definition at line 667 of file callback-test-suite.cc.
Referenced by MakeCallbackTemplatesTestCase::DoRun().
TestCZero()
void CallbackTestClass::TestCZero (void) const inline
Definition at line 665 of file callback-test-suite.cc.
Referenced by MakeCallbackTemplatesTestCase::DoRun().
TestFive()
void CallbackTestClass::TestFive (int , int , int , int , int) inline
Definition at line 663 of file callback-test-suite.cc.
Referenced by MakeCallbackTemplatesTestCase::DoRun().
TestFour()
void CallbackTestClass::TestFour (int , int , int , int) inline
Definition at line 662 of file callback-test-suite.cc.
Referenced by MakeCallbackTemplatesTestCase::DoRun().
TestOne()
void CallbackTestClass::TestOne (int) inline
Definition at line 659 of file callback-test-suite.cc.
Referenced by MakeCallbackTemplatesTestCase::DoRun().
TestSix()
void CallbackTestClass::TestSix (int , int , int , int , int , int) inline
Definition at line 664 of file callback-test-suite.cc.
Referenced by MakeCallbackTemplatesTestCase::DoRun().
TestThree()
void CallbackTestClass::TestThree (int , int , int) inline
Definition at line 661 of file callback-test-suite.cc.
Referenced by MakeCallbackTemplatesTestCase::DoRun().
TestTwo()
void CallbackTestClass::TestTwo (int , int) inline
Definition at line 660 of file callback-test-suite.cc.
Referenced by MakeCallbackTemplatesTestCase::DoRun().
TestZero()
void CallbackTestClass::TestZero (void) inline
Definition at line 658 of file callback-test-suite.cc.
Referenced by MakeCallbackTemplatesTestCase::DoRun().
The documentation for this class was generated from the following file:
src/core/test/callback-test-suite.cc