ns-3: ThreeGppShadowingTestCase Class Reference
ThreeGppShadowingTestCase Class Reference
Classes
struct TestVector
Struct containing the parameters for each test.
Public Member Functions
ThreeGppShadowingTestCase ()
virtual ~ThreeGppShadowingTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void ChangeChannelCondition (Ptr< ChannelConditionModel > ccm)
virtual void DoRun (void)
Implementation to actually run this TestCase.
void EvaluateLoss (Ptr< MobilityModel > a, Ptr< MobilityModel > b, uint8_t testNum)
Compute the propagation loss.
void RunTest (uint16_t testNum, std::string propagationLossModelType, double hBs, double hUt, double distance, bool shadowingEnabled)
Run the experiment.
Private Attributes
Ptr< ThreeGppPropagationLossModel > m_lossModel
the propagation loss model
std::map< uint16_t, std::vector< double > > m_results
used to store the test results
TestVectors< TestVector > m_testVectors
array containing all the test vectors
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 660 of file three-gpp-propagation-loss-model-test-suite.cc.
Constructor & Destructor Documentation
ThreeGppShadowingTestCase()
ThreeGppShadowingTestCase::ThreeGppShadowingTestCase ()
Definition at line 709 of file three-gpp-propagation-loss-model-test-suite.cc.
~ThreeGppShadowingTestCase()
ThreeGppShadowingTestCase::~ThreeGppShadowingTestCase () virtual
Definition at line 714 of file three-gpp-propagation-loss-model-test-suite.cc.
Member Function Documentation
ChangeChannelCondition()
void ThreeGppShadowingTestCase::ChangeChannelCondition (Ptr< ChannelConditionModel > ccm) private
Definition at line 726 of file three-gpp-propagation-loss-model-test-suite.cc.
References m_lossModel, and ns3::ThreeGppPropagationLossModel::SetChannelConditionModel().
Referenced by RunTest().
DoRun()
void ThreeGppShadowingTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 779 of file three-gpp-propagation-loss-model-test-suite.cc.
References ThreeGppShadowingTestCase::TestVector::m_distance, ThreeGppShadowingTestCase::TestVector::m_hBs, ThreeGppShadowingTestCase::TestVector::m_hUt, ThreeGppShadowingTestCase::TestVector::m_propagationLossModelType, m_results, ThreeGppShadowingTestCase::TestVector::m_shadowingStdLos, ThreeGppShadowingTestCase::TestVector::m_shadowingStdNlos, m_testVectors, NS_TEST_EXPECT_MSG_EQ_TOL, and RunTest().
EvaluateLoss()
void ThreeGppShadowingTestCase::EvaluateLoss (Ptr< MobilityModel > a, Ptr< MobilityModel > b, uint8_t testNum) private
Compute the propagation loss.
Parameters
a the first mobility model
b the second mobility model
testNum the index of the experiment
Definition at line 719 of file three-gpp-propagation-loss-model-test-suite.cc.
References ns3::PropagationLossModel::CalcRxPower(), m_lossModel, and m_results.
Referenced by RunTest().
RunTest()
void ThreeGppShadowingTestCase::RunTest (uint16_t testNum, std::string propagationLossModelType, double hBs, double hUt, double distance, bool shadowingEnabled) private
Run the experiment.
Parameters
testNum the index of the experiment
propagationLossModelType the type id of the propagation loss model to be used
hBs the BS height in meters
hUt the UT height in meters
distance the intial distance between the BS and the UT
Definition at line 732 of file three-gpp-propagation-loss-model-test-suite.cc.
References ChangeChannelCondition(), ns3::ObjectFactory::Create(), EvaluateLoss(), m_lossModel, m_results, ns3::MilliSeconds(), first::nodes, ns3::Seconds(), ns3::ObjectBase::SetAttribute(), ns3::ThreeGppPropagationLossModel::SetChannelConditionModel(), ns3::MobilityModel::SetPosition(), and ns3::ConstantVelocityMobilityModel::SetVelocity().
Referenced by DoRun().
Member Data Documentation
m_lossModel
Ptr<ThreeGppPropagationLossModel> ThreeGppShadowingTestCase::m_lossModel private
the propagation loss model
Definition at line 705 of file three-gpp-propagation-loss-model-test-suite.cc.
Referenced by ChangeChannelCondition(), EvaluateLoss(), and RunTest().
m_results
std::map<uint16_t , std::vector<double> > ThreeGppShadowingTestCase::m_results private
used to store the test results
Definition at line 706 of file three-gpp-propagation-loss-model-test-suite.cc.
Referenced by DoRun(), EvaluateLoss(), and RunTest().
m_testVectors
TestVectors<TestVector> ThreeGppShadowingTestCase::m_testVectors private
array containing all the test vectors
Definition at line 704 of file three-gpp-propagation-loss-model-test-suite.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/propagation/test/three-gpp-propagation-loss-model-test-suite.cc