ns-3: ns3::Mac16Address Class Reference
ns3::Mac16Address Class Reference
Network » Address
#include "mac16-address.h"
Public Member Functions
Mac16Address ()
Mac16Address (const char *str)
void CopyFrom (const uint8_t buffer[2])
void CopyTo (uint8_t buffer[2]) const
bool IsBroadcast (void) const
Checks if the address is a broadcast address according to 802.15.4 scheme (i.e., 0xFFFF).
bool IsMulticast (void) const
Checks if the address is a multicast address according to RFC 4944 Section 9 (i.e., if its first 3 bits are 100).
operator Address () const
Static Public Member Functions
static Mac16Address Allocate (void)
Allocate a new Mac16Address.
static Mac16Address ConvertFrom (const Address &address)
static Mac16Address GetBroadcast (void)
static Mac16Address GetMulticast (Ipv6Address address)
Returns the multicast address associated with an IPv6 address according to RFC 4944 Section 9.
static bool IsMatchingType (const Address &address)
Private Member Functions
Address ConvertTo (void) const
Static Private Member Functions
static uint8_t GetType (void)
Return the Type of address.
Private Attributes
uint8_t m_address [2]
address value
Friends
bool operator!= (const Mac16Address &a, const Mac16Address &b)
Not equal to operator.
bool operator< (const Mac16Address &a, const Mac16Address &b)
Less than operator.
std::ostream & operator<< (std::ostream &os, const Mac16Address &address)
Stream insertion operator.
bool operator== (const Mac16Address &a, const Mac16Address &b)
Equal to operator.
std::istream & operator>> (std::istream &is, Mac16Address &address)
Stream extraction operator.
Detailed Description
This class can contain 16 bit addresses.
See also
attribute_Mac16Address
Definition at line 41 of file mac16-address.h.
Constructor & Destructor Documentation
Mac16Address() [1/2]
ns3::Mac16Address::Mac16Address ()
Definition at line 60 of file mac16-address.cc.
References m_address, and NS_LOG_FUNCTION.
Referenced by GetBroadcast().
Mac16Address() [2/2]
ns3::Mac16Address::Mac16Address (const char * str)
Parameters
str a string representing the new Mac16Address
Definition at line 66 of file mac16-address.cc.
References ASCII_a, ASCII_COLON, ASCII_ZERO, ns3::AsciiToLowCase(), m_address, NS_ASSERT, and NS_LOG_FUNCTION.
Member Function Documentation
Allocate()
Mac16Address ns3::Mac16Address::Allocate (void) static
Allocate a new Mac16Address.
Returns
newly allocated mac16Address
Definition at line 140 of file mac16-address.cc.
References first::address, and NS_LOG_FUNCTION_NOARGS.
ConvertFrom()
Mac16Address ns3::Mac16Address::ConvertFrom (const Address & address) static
Parameters
address a polymorphic address
Returns
a new Mac16Address from the polymorphic address
This function performs a type check and asserts if the type of the input address is not compatible with an Mac16Address.
Definition at line 124 of file mac16-address.cc.
References first::address, GetType(), m_address, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv6L3Protocol::AddAutoconfiguredAddress(), ns3::Ipv6Interface::DoSetup(), ns3::Ipv6Address::MakeAutoconfiguredAddress(), ns3::Ipv6Address::MakeAutoconfiguredLinkLocalAddress(), ns3::Ipv6AddressHelper::NewAddress(), ns3::SixLowPanMesh::Print(), ns3::SixLowPanNetDevice::ReceiveFromDevice(), ns3::Ipv6L3Protocol::RemoveAutoconfiguredAddress(), ns3::LrWpanNetDevice::Send(), and ns3::LrWpanNetDevice::SetAddress().
ConvertTo()
Address ns3::Mac16Address::ConvertTo (void) const private
Returns
a new Address instance
Convert an instance of this class to a polymorphic Address instance.
Definition at line 133 of file mac16-address.cc.
References GetType(), m_address, and NS_LOG_FUNCTION.
CopyFrom()
void ns3::Mac16Address::CopyFrom (const uint8_t buffer[2])
Parameters
buffer address in network order
Copy the input address to our internal buffer.
Definition at line 99 of file mac16-address.cc.
References m_address, and NS_LOG_FUNCTION.
Referenced by ns3::SixLowPanNetDevice::Get16MacFrom48Mac(), GetMulticast(), ns3::ReadFrom(), ns3::LrWpanNetDevice::Send(), and ns3::LrWpanNetDevice::SetAddress().
CopyTo()
void ns3::Mac16Address::CopyTo (uint8_t buffer[2]) const
Parameters
buffer address in network order
Copy the internal address to the input buffer.
Definition at line 105 of file mac16-address.cc.
References m_address, and NS_LOG_FUNCTION.
Referenced by ns3::LrWpanNetDevice::BuildPseudoMacAddress(), ns3::Ipv6Address::MakeAutoconfiguredAddress(), ns3::Ipv6Address::MakeAutoconfiguredLinkLocalAddress(), ns3::LrWpanMac::PdDataIndication(), and ns3::WriteTo().
GetBroadcast()
Mac16Address ns3::Mac16Address::GetBroadcast (void) static
Returns
the broadcast address (0xFFFF)
Definition at line 161 of file mac16-address.cc.
References Mac16Address(), and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::LrWpanNetDevice::GetBroadcast().
GetMulticast()
Mac16Address ns3::Mac16Address::GetMulticast (Ipv6Address address) static
Returns the multicast address associated with an IPv6 address according to RFC 4944 Section 9.
An IPv6 packet with a multicast destination address (DST), consisting of the sixteen octets DST[1] through DST[16], is transmitted to the following 802.15.4 16-bit multicast address:
  0                   1
  0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |1 0 0|DST[15]* |   DST[16]     |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Here, DST[15]* refers to the last 5 bits in octet DST[15], that is, bits 3-7 within DST[15]. The initial 3-bit pattern of "100" follows the 16-bit address format for multicast addresses (Section 12).
Returns
the multicast 16-bit address.
Definition at line 170 of file mac16-address.cc.
References first::address, CopyFrom(), and NS_LOG_FUNCTION.
Referenced by ns3::LrWpanNetDevice::GetMulticast().
GetType()
uint8_t ns3::Mac16Address::GetType (void) static private
Return the Type of address.
Returns
type of address
Definition at line 152 of file mac16-address.cc.
References NS_LOG_FUNCTION_NOARGS, and ns3::Address::Register().
Referenced by ConvertFrom(), ConvertTo(), and IsMatchingType().
IsBroadcast()
bool ns3::Mac16Address::IsBroadcast (void) const
Checks if the address is a broadcast address according to 802.15.4 scheme (i.e., 0xFFFF).
Returns
true if the address is 0xFFFF
Definition at line 189 of file mac16-address.cc.
References m_address, and NS_LOG_FUNCTION.
Referenced by ns3::SixLowPanNetDevice::ReceiveFromDevice().
IsMatchingType()
bool ns3::Mac16Address::IsMatchingType (const Address & address) static
Parameters
address address to test
Returns
true if the address matches, false otherwise.
Definition at line 112 of file mac16-address.cc.
References first::address, GetType(), and NS_LOG_FUNCTION.
Referenced by ns3::Ipv6L3Protocol::AddAutoconfiguredAddress(), ns3::Ipv6Interface::DoSetup(), ns3::Ipv6Address::MakeAutoconfiguredAddress(), ns3::Ipv6Address::MakeAutoconfiguredLinkLocalAddress(), ns3::Ipv6AddressHelper::NewAddress(), ns3::SixLowPanNetDevice::ReceiveFromDevice(), ns3::Ipv6L3Protocol::RemoveAutoconfiguredAddress(), ns3::LrWpanNetDevice::SetAddress(), ns3::SixLowPanMesh::SetFinalDst(), and ns3::SixLowPanMesh::SetOriginator().
IsMulticast()
bool ns3::Mac16Address::IsMulticast (void) const
Checks if the address is a multicast address according to RFC 4944 Section 9 (i.e., if its first 3 bits are 100).
Returns
true if the address is in the range 0x8000 - 0x9FFF
Definition at line 200 of file mac16-address.cc.
References m_address, and NS_LOG_FUNCTION.
Referenced by ns3::SixLowPanNetDevice::ReceiveFromDevice().
operator Address()
ns3::Mac16Address::operator Address () const
Returns
a new Address instance
Convert an instance of this class to a polymorphic Address instance.
Definition at line 118 of file mac16-address.cc.
Friends And Related Function Documentation
operator!=
bool operator!= (const Mac16Address & a, const Mac16Address & b) friend
Not equal to operator.
Parameters
a the first operand
b the first operand
Returns
true if the operands are not equal
Definition at line 202 of file mac16-address.h.
operator<
bool operator< (const Mac16Address & a, const Mac16Address & b) friend
Less than operator.
Parameters
a the first operand
b the first operand
Returns
true if the operand a is less than operand b
Definition at line 206 of file mac16-address.h.
operator<<
std::ostream& operator<< (std::ostream & os, const Mac16Address & address) friend
Stream insertion operator.
Parameters
os the stream
address the address
Returns
a reference to the stream
Definition at line 212 of file mac16-address.cc.
operator==
bool operator== (const Mac16Address & a, const Mac16Address & b) friend
Equal to operator.
Parameters
a the first operand
b the first operand
Returns
true if the operands are equal
Definition at line 198 of file mac16-address.h.
operator>>
std::istream& operator>> (std::istream & is, Mac16Address & address) friend
Stream extraction operator.
Parameters
is the stream
address the address
Returns
a reference to the stream
Definition at line 230 of file mac16-address.cc.
Member Data Documentation
m_address
uint8_t ns3::Mac16Address::m_address[2] private
address value
Definition at line 193 of file mac16-address.h.
Referenced by Mac16Address(), ConvertFrom(), ConvertTo(), CopyFrom(), CopyTo(), IsBroadcast(), IsMulticast(), ns3::operator!=(), ns3::operator<(), and ns3::operator==().
The documentation for this class was generated from the following files:
src/network/utils/mac16-address.h
src/network/utils/mac16-address.cc