ns-3: Ipv6L3ProtocolTestCase Class Reference
Ipv6L3ProtocolTestCase Class Reference
Internet » internet module tests | Test suites
IPv6 Test.
Public Member Functions
Ipv6L3ProtocolTestCase ()
virtual ~Ipv6L3ProtocolTestCase ()
virtual void DoRun ()
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
IPv6 Test.
Definition at line 41 of file ipv6-test.cc.
Constructor & Destructor Documentation
Ipv6L3ProtocolTestCase()
Ipv6L3ProtocolTestCase::Ipv6L3ProtocolTestCase ()
Definition at line 50 of file ipv6-test.cc.
~Ipv6L3ProtocolTestCase()
Ipv6L3ProtocolTestCase::~Ipv6L3ProtocolTestCase () virtual
Definition at line 55 of file ipv6-test.cc.
Member Function Documentation
DoRun()
void Ipv6L3ProtocolTestCase::DoRun () virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 60 of file ipv6-test.cc.
References ns3::Node::AddDevice(), ns3::Ipv6L3Protocol::AddIpv6Interface(), ns3::Object::AggregateObject(), ns3::CreateObject(), ns3::Ipv6InterfaceAddress::GetAddress(), ns3::Ipv6L3Protocol::GetInterfaceForAddress(), ns3::Ipv6L3Protocol::GetInterfaceForPrefix(), ns3::Ipv6L3Protocol::Insert(), ns3::Ipv6Address::IsLinkLocal(), NS_TEST_ASSERT_MSG_EQ, ns3::Ipv6L3Protocol::RemoveAddress(), and ns3::ObjectBase::SetAttribute().
The documentation for this class was generated from the following file:
src/internet/test/ipv6-test.cc