ns-3: ns3::DhcpHelper Class Reference
ns3::DhcpHelper Class Reference
Internet Applications » DHCPv4 Client and Server
The helper class used to configure and install DHCP applications on nodes.
#include "dhcp-helper.h"
Public Member Functions
DhcpHelper ()
ApplicationContainer InstallDhcpClient (NetDeviceContainer netDevices) const
Install DHCP client of a set of nodes / NetDevices.
ApplicationContainer InstallDhcpClient (Ptr< NetDevice > netDevice) const
Install DHCP client of a nodes / NetDevice.
ApplicationContainer InstallDhcpServer (Ptr< NetDevice > netDevice, Ipv4Address serverAddr, Ipv4Address poolAddr, Ipv4Mask poolMask, Ipv4Address minAddr, Ipv4Address maxAddr, Ipv4Address gateway=Ipv4Address())
Install DHCP server of a node / NetDevice.
Ipv4InterfaceContainer InstallFixedAddress (Ptr< NetDevice > netDevice, Ipv4Address addr, Ipv4Mask mask)
Assign a fixed IP addresses to a net device.
void SetClientAttribute (std::string name, const AttributeValue &value)
Set DHCP client attributes.
void SetServerAttribute (std::string name, const AttributeValue &value)
Set DHCP server attributes.
Private Member Functions
Ptr< Application > InstallDhcpClientPriv (Ptr< NetDevice > netDevice) const
Function to install DHCP client on a node.
Private Attributes
std::list< std::pair< Ipv4Address, Ipv4Address > > m_addressPools
list of address pools.
ObjectFactory m_clientFactory
DHCP client factory.
std::list< Ipv4Address > m_fixedAddresses
list of fixed addresses already allocated.
ObjectFactory m_serverFactory
DHCP server factory.
Detailed Description
The helper class used to configure and install DHCP applications on nodes.
Definition at line 43 of file dhcp-helper.h.
Constructor & Destructor Documentation
DhcpHelper()
ns3::DhcpHelper::DhcpHelper ()
Definition at line 41 of file dhcp-helper.cc.
References ns3::DhcpClient::GetTypeId(), ns3::DhcpServer::GetTypeId(), m_clientFactory, m_serverFactory, and ns3::ObjectFactory::SetTypeId().
Member Function Documentation
InstallDhcpClient() [1/2]
ApplicationContainer ns3::DhcpHelper::InstallDhcpClient (NetDeviceContainer netDevices) const
Install DHCP client of a set of nodes / NetDevices.
Parameters
netDevices The NetDevices that the DHCP client will use
Returns
The application container with DHCP client installed
Definition at line 66 of file dhcp-helper.cc.
References ns3::ApplicationContainer::Add(), ns3::NetDeviceContainer::Begin(), ns3::NetDeviceContainer::End(), and InstallDhcpClientPriv().
InstallDhcpClient() [2/2]
ApplicationContainer ns3::DhcpHelper::InstallDhcpClient (Ptr< NetDevice > netDevice) const
Install DHCP client of a nodes / NetDevice.
Parameters
netDevice The NetDevice that the DHCP client will use
Returns
The application container with DHCP client installed
Definition at line 61 of file dhcp-helper.cc.
References InstallDhcpClientPriv().
Referenced by DhcpTestCase::DoRun().
InstallDhcpClientPriv()
Ptr< Application > ns3::DhcpHelper::InstallDhcpClientPriv (Ptr< NetDevice > netDevice) const private
Function to install DHCP client on a node.
Parameters
netDevice The NetDevice on which DHCP client application has to be installed
Returns
The pointer to the installed DHCP client
Definition at line 76 of file dhcp-helper.cc.
References ns3::Node::AddApplication(), ns3::ObjectFactory::Create(), ns3::TrafficControlHelper::Default(), ns3::Object::GetObject(), ns3::TrafficControlHelper::Install(), m_clientFactory, NS_ASSERT_MSG(), and NS_LOG_LOGIC().
Referenced by InstallDhcpClient().
InstallDhcpServer()
ApplicationContainer ns3::DhcpHelper::InstallDhcpServer (Ptr< NetDevice > netDevice, Ipv4Address serverAddr, Ipv4Address poolAddr, Ipv4Mask poolMask, Ipv4Address minAddr, Ipv4Address maxAddr, Ipv4Address gateway = Ipv4Address ())
Install DHCP server of a node / NetDevice.
Note: the server address must be coherent with the pool address, because DHCP relays are not yet supported.
Parameters
netDevice The NetDevice on which DHCP server application has to be installed
serverAddr The Ipv4Address of the server
poolAddr The Ipv4Address (network part) of the allocated pool
poolMask The mask of the allocated pool
minAddr The lower bound of the Ipv4Address pool
maxAddr The upper bound of the Ipv4Address pool
gateway The Ipv4Address of default gateway (optional)
Returns
The application container with DHCP server installed
Definition at line 124 of file dhcp-helper.cc.
References ns3::Node::AddApplication(), ns3::ObjectFactory::Create(), ns3::TrafficControlHelper::Default(), ns3::Ipv4Address::Get(), ns3::Object::GetObject(), ns3::TrafficControlHelper::Install(), m_addressPools, m_fixedAddresses, m_serverFactory, NS_ABORT_MSG, NS_ASSERT_MSG(), NS_LOG_LOGIC(), and ns3::ObjectFactory::Set().
Referenced by DhcpTestCase::DoRun().
InstallFixedAddress()
Ipv4InterfaceContainer ns3::DhcpHelper::InstallFixedAddress (Ptr< NetDevice > netDevice, Ipv4Address addr, Ipv4Mask mask)
Assign a fixed IP addresses to a net device.
Parameters
netDevice The NetDevice on which the address has to be installed
addr The Ipv4Address
mask The network mask
Returns
the Ipv4 interface container
Definition at line 192 of file dhcp-helper.cc.
References ns3::Ipv4InterfaceContainer::Add(), ns3::TrafficControlHelper::Default(), ns3::Ipv4Address::Get(), ns3::Object::GetObject(), ns3::TrafficControlHelper::Install(), m_addressPools, m_fixedAddresses, NS_ABORT_MSG, NS_ASSERT_MSG(), and NS_LOG_LOGIC().
SetClientAttribute()
void ns3::DhcpHelper::SetClientAttribute (std::string name, const AttributeValue & value)
Set DHCP client attributes.
Parameters
name Name of the attribute
value Value to be set
Definition at line 47 of file dhcp-helper.cc.
References m_clientFactory, and ns3::ObjectFactory::Set().
SetServerAttribute()
void ns3::DhcpHelper::SetServerAttribute (std::string name, const AttributeValue & value)
Set DHCP server attributes.
Parameters
name Name of the attribute
value Value to be set
Definition at line 54 of file dhcp-helper.cc.
References m_serverFactory, and ns3::ObjectFactory::Set().
Member Data Documentation
m_addressPools
std::list< std::pair <Ipv4Address, Ipv4Address> > ns3::DhcpHelper::m_addressPools private
list of address pools.
Definition at line 114 of file dhcp-helper.h.
Referenced by InstallDhcpServer(), and InstallFixedAddress().
m_clientFactory
ObjectFactory ns3::DhcpHelper::m_clientFactory private
DHCP client factory.
Definition at line 111 of file dhcp-helper.h.
Referenced by DhcpHelper(), InstallDhcpClientPriv(), and SetClientAttribute().
m_fixedAddresses
std::list<Ipv4Address> ns3::DhcpHelper::m_fixedAddresses private
list of fixed addresses already allocated.
Definition at line 113 of file dhcp-helper.h.
Referenced by InstallDhcpServer(), and InstallFixedAddress().
m_serverFactory
ObjectFactory ns3::DhcpHelper::m_serverFactory private
DHCP server factory.
Definition at line 112 of file dhcp-helper.h.
Referenced by DhcpHelper(), InstallDhcpServer(), and SetServerAttribute().
The documentation for this class was generated from the following files:
src/internet-apps/helper/dhcp-helper.h
src/internet-apps/helper/dhcp-helper.cc