ns-3: WaypointMobilityModelAddWaypointTest Class Reference
WaypointMobilityModelAddWaypointTest Class Reference
Mobility » mobility module tests | Test suites
Waypoint Mobility Model Add Waypoint Test.
Public Member Functions
WaypointMobilityModelAddWaypointTest ()
virtual ~WaypointMobilityModelAddWaypointTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CourseChangeCallback (Ptr< const MobilityModel > model)
Course change calback.
virtual void DoRun (void)
Implementation to actually run this TestCase.
virtual void DoTeardown (void)
Implementation to do any local setup required for this TestCase.
Private Attributes
Ptr< MobilityModel > m_mobilityModel
mobility model
Waypoint m_nextWaypoint
next waypoint
uint32_t m_waypointCount
waypoint count
uint32_t m_waypointCounter
waypoint counter
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Waypoint Mobility Model Add Waypoint Test.
Definition at line 170 of file waypoint-mobility-model-test.cc.
Constructor & Destructor Documentation
WaypointMobilityModelAddWaypointTest()
WaypointMobilityModelAddWaypointTest::WaypointMobilityModelAddWaypointTest () inline
Definition at line 173 of file waypoint-mobility-model-test.cc.
~WaypointMobilityModelAddWaypointTest()
virtual WaypointMobilityModelAddWaypointTest::~WaypointMobilityModelAddWaypointTest () inline virtual
Definition at line 177 of file waypoint-mobility-model-test.cc.
Member Function Documentation
CourseChangeCallback()
void WaypointMobilityModelAddWaypointTest::CourseChangeCallback (Ptr< const MobilityModel > model) private
Course change calback.
Parameters
model the mobility model
Definition at line 230 of file waypoint-mobility-model-test.cc.
References ns3::WaypointMobilityModel::AddWaypoint(), ns3::Simulator::Now(), NS_TEST_EXPECT_MSG_EQ, and ns3::Seconds().
Referenced by DoRun().
DoRun()
void WaypointMobilityModelAddWaypointTest::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 204 of file waypoint-mobility-model-test.cc.
References ns3::WaypointMobilityModel::AddWaypoint(), CourseChangeCallback(), ns3::ObjectFactory::Create(), ns3::Simulator::Destroy(), ns3::Object::GetObject(), ns3::Object::Initialize(), ns3::MakeCallback(), ns3::Simulator::Run(), ns3::Simulator::Schedule(), ns3::Seconds(), ns3::ObjectFactory::Set(), ns3::ObjectFactory::SetTypeId(), ns3::Simulator::Stop(), and ns3::ObjectBase::TraceConnectWithoutContext().
DoTeardown()
void WaypointMobilityModelAddWaypointTest::DoTeardown (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test teardown
Reimplemented from ns3::TestCase.
Definition at line 198 of file waypoint-mobility-model-test.cc.
Member Data Documentation
m_mobilityModel
Ptr<MobilityModel> WaypointMobilityModelAddWaypointTest::m_mobilityModel private
mobility model
Definition at line 182 of file waypoint-mobility-model-test.cc.
m_nextWaypoint
Waypoint WaypointMobilityModelAddWaypointTest::m_nextWaypoint private
next waypoint
Definition at line 185 of file waypoint-mobility-model-test.cc.
m_waypointCount
uint32_t WaypointMobilityModelAddWaypointTest::m_waypointCount private
waypoint count
Definition at line 183 of file waypoint-mobility-model-test.cc.
m_waypointCounter
uint32_t WaypointMobilityModelAddWaypointTest::m_waypointCounter private
waypoint counter
Definition at line 184 of file waypoint-mobility-model-test.cc.
The documentation for this class was generated from the following file:
src/mobility/test/waypoint-mobility-model-test.cc