ns-3: ns3::LteTestPdcp Class Reference
ns3::LteTestPdcp Class Reference
LTE Models » lte module tests | Test suites
This class implements a testing PDCP entity.
#include "lte-test-entities.h"
Public Member Functions
LteTestPdcp (void)
virtual ~LteTestPdcp (void)
virtual void DoDispose (void)
Destructor implementation.
std::string GetDataReceived (void)
Get data received function.
LteRlcSapUser * GetLteRlcSapUser (void)
Get the RLC SAP user.
void SendData (Time time, std::string dataToSend)
Send data function.
void SetLteRlcSapProvider (LteRlcSapProvider *s)
Set the RLC SAP provider.
void Start ()
Start function.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual void DoReceivePdcpPdu (Ptr< Packet > p)
Interface forwarded by LteRlcSapUser.
Private Attributes
std::string m_receivedData
the received data
LteRlcSapProvider * m_rlcSapProvider
RLC SAP provider.
LteRlcSapUser * m_rlcSapUser
RLC SAP user.
Friends
class LteRlcSpecificLteRlcSapUser< LteTestPdcp >
allow LteRlcSpecificLteRlcSapUser<LteTestPdcp> class friend access
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class implements a testing PDCP entity.
Definition at line 176 of file lte-test-entities.h.
Constructor & Destructor Documentation
LteTestPdcp()
ns3::LteTestPdcp::LteTestPdcp (void)
Definition at line 270 of file lte-test-entities.cc.
References LteRlcSpecificLteRlcSapUser< LteTestPdcp >, m_rlcSapUser, NS_LOG_FUNCTION, ns3::Simulator::ScheduleNow(), and Start().
~LteTestPdcp()
ns3::LteTestPdcp::~LteTestPdcp (void) virtual
Definition at line 277 of file lte-test-entities.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::LteTestPdcp::DoDispose (void) virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 283 of file lte-test-entities.cc.
References m_rlcSapUser, and NS_LOG_FUNCTION.
DoReceivePdcpPdu()
void ns3::LteTestPdcp::DoReceivePdcpPdu (Ptr< Packet > p) private virtual
Interface forwarded by LteRlcSapUser.
RLC SAP.
Parameters
p the PDCP PDU packet received
Definition at line 316 of file lte-test-entities.cc.
References ns3::Packet::CopyData(), ns3::Packet::GetSize(), m_receivedData, NS_LOG_FUNCTION, and NS_LOG_LOGIC().
GetDataReceived()
std::string ns3::LteTestPdcp::GetDataReceived (void)
Get data received function.
Returns
the received data string
Definition at line 303 of file lte-test-entities.cc.
References m_receivedData, and NS_LOG_FUNCTION.
GetLteRlcSapUser()
LteRlcSapUser * ns3::LteTestPdcp::GetLteRlcSapUser (void)
Get the RLC SAP user.
Returns
a pointer to the SAP user of the RLC
Definition at line 296 of file lte-test-entities.cc.
References m_rlcSapUser.
Referenced by LteRlcAmTransmitterTestCase::DoRun(), and LteRlcUmTransmitterTestCase::DoRun().
GetTypeId()
TypeId ns3::LteTestPdcp::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 260 of file lte-test-entities.cc.
References ns3::TypeId::SetParent().
SendData()
void ns3::LteTestPdcp::SendData (Time time, std::string dataToSend)
Send data function.
Parameters
time the time to send
dataToSend the data to send
Definition at line 342 of file lte-test-entities.cc.
References ns3::Packet::GetSize(), ns3::LteRlcSapProvider::TransmitPdcpPduParameters::lcid, m_rlcSapProvider, NS_LOG_FUNCTION, NS_LOG_LOGIC(), ns3::LteRlcSapProvider::TransmitPdcpPduParameters::pdcpPdu, ns3::LteRlcSapProvider::TransmitPdcpPduParameters::rnti, ns3::Simulator::Schedule(), and ns3::LteRlcSapProvider::TransmitPdcpPdu().
Referenced by LteRlcAmTransmitterOneSduTestCase::DoRun(), LteRlcAmTransmitterSegmentationTestCase::DoRun(), LteRlcAmTransmitterConcatenationTestCase::DoRun(), LteRlcAmTransmitterReportBufferStatusTestCase::DoRun(), LteRlcUmTransmitterOneSduTestCase::DoRun(), LteRlcUmTransmitterSegmentationTestCase::DoRun(), LteRlcUmTransmitterConcatenationTestCase::DoRun(), and LteRlcUmTransmitterReportBufferStatusTestCase::DoRun().
SetLteRlcSapProvider()
void ns3::LteTestPdcp::SetLteRlcSapProvider (LteRlcSapProvider * s)
Set the RLC SAP provider.
Parameters
s a pointer to the RLC SAP provider
Definition at line 290 of file lte-test-entities.cc.
References m_rlcSapProvider.
Referenced by LteRlcAmTransmitterTestCase::DoRun(), and LteRlcUmTransmitterTestCase::DoRun().
Start()
void ns3::LteTestPdcp::Start ()
Start function.
START.
Definition at line 336 of file lte-test-entities.cc.
References NS_LOG_FUNCTION.
Referenced by LteTestPdcp().
Friends And Related Function Documentation
LteRlcSpecificLteRlcSapUser< LteTestPdcp >
friend class LteRlcSpecificLteRlcSapUser< LteTestPdcp > friend
allow LteRlcSpecificLteRlcSapUser<LteTestPdcp> class friend access
Definition at line 165 of file lte-test-entities.h.
Referenced by LteTestPdcp().
Member Data Documentation
m_receivedData
std::string ns3::LteTestPdcp::m_receivedData private
the received data
Definition at line 229 of file lte-test-entities.h.
Referenced by DoReceivePdcpPdu(), and GetDataReceived().
m_rlcSapProvider
LteRlcSapProvider* ns3::LteTestPdcp::m_rlcSapProvider private
RLC SAP provider.
Definition at line 227 of file lte-test-entities.h.
Referenced by SendData(), and SetLteRlcSapProvider().
m_rlcSapUser
LteRlcSapUser* ns3::LteTestPdcp::m_rlcSapUser private
RLC SAP user.
Definition at line 226 of file lte-test-entities.h.
Referenced by LteTestPdcp(), DoDispose(), and GetLteRlcSapUser().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-entities.h
src/lte/test/lte-test-entities.cc