ns-3: ns3::NetDeviceQueueInterface Class Reference
ns3::NetDeviceQueueInterface Class Reference
Network » Network Device
Network device transmission queue interface.
#include "net-device-queue-interface.h"
Public Types
typedef std::function< std::size_t(Ptr< QueueItem >)> SelectQueueCallback
Callback invoked to determine the tx queue selected for a given packet.
Public Member Functions
NetDeviceQueueInterface ()
Constructor.
virtual ~NetDeviceQueueInterface ()
std::size_t GetNTxQueues (void) const
Get the number of device transmission queues.
SelectQueueCallback GetSelectQueueCallback (void) const
Get the select queue callback.
Ptr< NetDeviceQueue > GetTxQueue (std::size_t i) const
Get the i-th transmission queue of the device.
void SetNTxQueues (std::size_t numTxQueues)
Set the number of device transmission queues to create.
void SetSelectQueueCallback (SelectQueueCallback cb)
Set the select queue callback.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Dispose of the object.
virtual void NotifyNewAggregate (void)
Notify that an object was aggregated.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Attributes
SelectQueueCallback m_selectQueueCallback
Select queue callback.
std::vector< Ptr< NetDeviceQueue > > m_txQueuesVector
Device transmission queues.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Network device transmission queue interface.
This interface is used by the traffic control layer and by the aggregated device to access the transmission queues of the device. Additionally, through this interface, traffic control aware netdevices can:
set the number of transmission queues
set the method used (by upper layers) to determine the transmission queue in which the netdevice would enqueue a given packet NetDevice helpers create this interface and aggregate it to the device.
Definition at line 223 of file net-device-queue-interface.h.
Member Typedef Documentation
SelectQueueCallback
typedef std::function<std::size_t (Ptr<QueueItem>)> ns3::NetDeviceQueueInterface::SelectQueueCallback
Callback invoked to determine the tx queue selected for a given packet.
Definition at line 265 of file net-device-queue-interface.h.
Constructor & Destructor Documentation
NetDeviceQueueInterface()
ns3::NetDeviceQueueInterface::NetDeviceQueueInterface ()
Constructor.
Definition at line 183 of file net-device-queue-interface.cc.
References m_selectQueueCallback, and NS_LOG_FUNCTION.
~NetDeviceQueueInterface()
ns3::NetDeviceQueueInterface::~NetDeviceQueueInterface () virtual
Definition at line 191 of file net-device-queue-interface.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoDispose()
void ns3::NetDeviceQueueInterface::DoDispose (void) protected virtual
Dispose of the object.
Reimplemented from ns3::Object.
Definition at line 210 of file net-device-queue-interface.cc.
References ns3::Object::DoDispose(), m_txQueuesVector, and NS_LOG_FUNCTION.
GetNTxQueues()
std::size_t ns3::NetDeviceQueueInterface::GetNTxQueues (void) const
Get the number of device transmission queues.
Returns
the number of device transmission queues.
Definition at line 204 of file net-device-queue-interface.cc.
References m_txQueuesVector.
Referenced by GetTypeId().
GetSelectQueueCallback()
NetDeviceQueueInterface::SelectQueueCallback ns3::NetDeviceQueueInterface::GetSelectQueueCallback (void) const
Get the select queue callback.
Returns
the select queue callback.
Called by the traffic control layer to get the select queue callback set by a multi-queue device.
Definition at line 253 of file net-device-queue-interface.cc.
References m_selectQueueCallback.
GetTxQueue()
Ptr< NetDeviceQueue > ns3::NetDeviceQueueInterface::GetTxQueue (std::size_t i) const
Get the i-th transmission queue of the device.
Parameters
i the index of the requested queue.
Returns
the i-th transmission queue of the device.
The index of the first transmission queue is zero.
Definition at line 197 of file net-device-queue-interface.cc.
References m_txQueuesVector, and NS_ASSERT.
Referenced by TcFlowControlTestCase::CheckDeviceQueueStopped().
GetTypeId()
TypeId ns3::NetDeviceQueueInterface::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 167 of file net-device-queue-interface.cc.
References ns3::TypeId::ATTR_CONSTRUCT, ns3::TypeId::ATTR_GET, GetNTxQueues(), ns3::MakeUintegerAccessor(), SetNTxQueues(), and ns3::TypeId::SetParent().
NotifyNewAggregate()
void ns3::NetDeviceQueueInterface::NotifyNewAggregate (void) protected virtual
Notify that an object was aggregated.
Reimplemented from ns3::Object.
Definition at line 219 of file net-device-queue-interface.cc.
References m_txQueuesVector, ns3::Object::NotifyNewAggregate(), and NS_LOG_FUNCTION.
SetNTxQueues()
void ns3::NetDeviceQueueInterface::SetNTxQueues (std::size_t numTxQueues)
Set the number of device transmission queues to create.
Parameters
numTxQueues number of device transmission queues to create.
This method is called when the NTxQueues attribute is set to create the corresponding number of device transmission queues. It cannot be called again afterwards.
Definition at line 232 of file net-device-queue-interface.cc.
References m_txQueuesVector, NS_ABORT_MSG_IF, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetSelectQueueCallback()
void ns3::NetDeviceQueueInterface::SetSelectQueueCallback (SelectQueueCallback cb)
Set the select queue callback.
Parameters
cb the callback to set.
This method is called to set the select queue callback, i.e., the method used to select a device transmission queue for a given packet.
Definition at line 247 of file net-device-queue-interface.cc.
References m_selectQueueCallback.
Member Data Documentation
m_selectQueueCallback
SelectQueueCallback ns3::NetDeviceQueueInterface::m_selectQueueCallback private
Select queue callback.
Definition at line 297 of file net-device-queue-interface.h.
Referenced by NetDeviceQueueInterface(), GetSelectQueueCallback(), and SetSelectQueueCallback().
m_txQueuesVector
std::vector< Ptr<NetDeviceQueue> > ns3::NetDeviceQueueInterface::m_txQueuesVector private
Device transmission queues.
Definition at line 296 of file net-device-queue-interface.h.
Referenced by DoDispose(), GetNTxQueues(), GetTxQueue(), NotifyNewAggregate(), and SetNTxQueues().
The documentation for this class was generated from the following files:
src/network/utils/net-device-queue-interface.h
src/network/utils/net-device-queue-interface.cc