ns-3: ns3::U16TlvValue Class Reference
ns3::U16TlvValue Class Reference
WiMAX Models
U16TlvValue class.
#include "wimax-tlv.h"
Public Member Functions
U16TlvValue ()
U16TlvValue (uint16_t value)
Constructor.
~U16TlvValue (void)
virtual U16TlvValue * Copy (void) const
Copy.
uint32_t Deserialize (Buffer::Iterator start)
Deserialize from a buffer.
virtual uint32_t Deserialize (Buffer::Iterator start, uint64_t valueLen)
Deserialize from a buffer.
virtual uint32_t GetSerializedSize (void) const
Get serialized size in bytes.
uint16_t GetValue (void) const
Get value.
virtual void Serialize (Buffer::Iterator start) const
Serialize to a buffer.
Public Member Functions inherited from ns3::TlvValue
virtual ~TlvValue ()
Private Attributes
uint16_t m_value
value
Detailed Description
U16TlvValue class.
Definition at line 209 of file wimax-tlv.h.
Constructor & Destructor Documentation
U16TlvValue() [1/2]
ns3::U16TlvValue::U16TlvValue (uint16_t value)
Constructor.
Parameters
value value to encode
Definition at line 549 of file wimax-tlv.cc.
References m_value.
U16TlvValue() [2/2]
ns3::U16TlvValue::U16TlvValue ()
Definition at line 554 of file wimax-tlv.cc.
References m_value.
Referenced by Copy().
~U16TlvValue()
ns3::U16TlvValue::~U16TlvValue (void)
Definition at line 559 of file wimax-tlv.cc.
Member Function Documentation
Copy()
U16TlvValue * ns3::U16TlvValue::Copy (void) const virtual
Copy.
Returns
the U16 TLV value
Implements ns3::TlvValue.
Definition at line 593 of file wimax-tlv.cc.
References U16TlvValue(), and m_value.
Deserialize() [1/2]
uint32_t ns3::U16TlvValue::Deserialize (Buffer::Iterator start)
Deserialize from a buffer.
Parameters
start the iterator
Returns
the size
Definition at line 580 of file wimax-tlv.cc.
References m_value, and ns3::Buffer::Iterator::ReadNtohU16().
Deserialize() [2/2]
uint32_t ns3::U16TlvValue::Deserialize (Buffer::Iterator start, uint64_t valueLen) virtual
Deserialize from a buffer.
Parameters
start the iterator
valueLen the maximum length of the value
Returns
the
Implements ns3::TlvValue.
Definition at line 574 of file wimax-tlv.cc.
Referenced by ns3::SfVectorTlvValue::Deserialize(), and ns3::ClassificationRuleVectorTlvValue::Deserialize().
GetSerializedSize()
uint32_t ns3::U16TlvValue::GetSerializedSize (void) const virtual
Get serialized size in bytes.
Returns
the serialized size
Implements ns3::TlvValue.
Definition at line 564 of file wimax-tlv.cc.
GetValue()
uint16_t ns3::U16TlvValue::GetValue (void) const
Get value.
Returns
the value
Definition at line 587 of file wimax-tlv.cc.
References m_value.
Serialize()
void ns3::U16TlvValue::Serialize (Buffer::Iterator start) const virtual
Serialize to a buffer.
Parameters
start the iterator
Implements ns3::TlvValue.
Definition at line 569 of file wimax-tlv.cc.
References m_value, and ns3::Buffer::Iterator::WriteHtonU16().
Member Data Documentation
m_value
uint16_t ns3::U16TlvValue::m_value private
value
Definition at line 240 of file wimax-tlv.h.
Referenced by U16TlvValue(), Copy(), Deserialize(), GetValue(), and Serialize().
The documentation for this class was generated from the following files:
src/wimax/model/wimax-tlv.h
src/wimax/model/wimax-tlv.cc