ns-3: ns3::NdiscCache::Entry Class Reference
ns3::NdiscCache::Entry Class Reference
Internet » IPv6 classes and sub-modules
A record that holds information about a NdiscCache entry.
#include "ndisc-cache.h"
Public Member Functions
Entry (NdiscCache *nd)
Constructor.
void AddWaitingPacket (Ipv6PayloadHeaderPair p)
Add a packet (or replace old value) in the queue.
void ClearWaitingPacket ()
Clear the waiting packet list.
void FunctionDelayTimeout ()
Function called when delay timer timeout.
void FunctionProbeTimeout ()
Function called when probe timer timeout.
void FunctionReachableTimeout ()
Function called when reachable timer timeout.
void FunctionRetransmitTimeout ()
Function called when retransmit timer timeout.
Time GetLastReachabilityConfirmation () const
Get the time of last reachability confirmation.
Address GetMacAddress () const
Get the MAC address of this entry.
bool IsDelay () const
Is the entry DELAY.
bool IsIncomplete () const
Is the entry INCOMPLETE.
bool IsPermanent () const
Is the entry PERMANENT.
bool IsProbe () const
Is the entry PROBE.
bool IsReachable () const
Is the entry REACHABLE.
bool IsRouter () const
If the entry is a host or a router.
bool IsStale () const
Is the entry STALE.
void MarkDelay ()
Change the state to this entry to DELAY.
void MarkIncomplete (Ipv6PayloadHeaderPair p)
Changes the state to this entry to INCOMPLETE.
void MarkPermanent ()
Change the state to this entry to PERMANENT.
void MarkProbe ()
Changes the state to this entry to PROBE.
void MarkReachable ()
Changes the state to this entry to REACHABLE.
std::list< Ipv6PayloadHeaderPair > MarkReachable (Address mac)
Changes the state to this entry to REACHABLE.
void MarkStale ()
Changes the state to this entry to STALE.
std::list< Ipv6PayloadHeaderPair > MarkStale (Address mac)
Changes the state to this entry to STALE.
void SetIpv6Address (Ipv6Address ipv6Address)
Set the IPv6 address.
void SetMacAddress (Address mac)
Set the MAC address of this entry.
void SetRouter (bool router)
Set the node type.
void StartDelayTimer ()
Start delay timer.
void StartProbeTimer ()
Start probe timer.
void StartReachableTimer ()
Start the reachable timer.
void StartRetransmitTimer ()
Start retransmit timer.
void StopNudTimer ()
Stop NUD timer and reset the NUD retransmission counter.
void UpdateReachableTimer ()
Update the reachable timer.
Private Types
enum NdiscCacheEntryState_e {
INCOMPLETE, REACHABLE, STALE, DELAY,
PROBE, PERMANENT
}
The Entry state enumeration.
Private Attributes
Ipv6Address m_ipv6Address
The IPv6 address.
Time m_lastReachabilityConfirmation
Last time we see a reachability confirmation.
Address m_macAddress
The MAC address.
NdiscCache * m_ndCache
the NdiscCache associated.
uint8_t m_nsRetransmit
Number of NS retransmission.
Timer m_nudTimer
Timer (used for NUD).
bool m_router
Type of node (router or host).
NdiscCacheEntryState_e m_state
The state of the entry.
std::list< Ipv6PayloadHeaderPair > m_waiting
The list of packet waiting.
Detailed Description
A record that holds information about a NdiscCache entry.
Definition at line 156 of file ndisc-cache.h.
Member Enumeration Documentation
NdiscCacheEntryState_e
enum ns3::NdiscCache::Entry::NdiscCacheEntryState_e private
The Entry state enumeration.
Enumerator
INCOMPLETE
No mapping between IPv6 and L2 addresses.
REACHABLE
Mapping exists between IPv6 and L2 addresses.
STALE
Mapping is stale.
DELAY
Try to wait contact from remote host.
PROBE
Try to contact IPv6 address to know again its L2 address.
PERMANENT
Permanent Mapping exists between IPv6 and L2 addresses.
Definition at line 354 of file ndisc-cache.h.
Constructor & Destructor Documentation
Entry()
ns3::NdiscCache::Entry::Entry (NdiscCache * nd)
Constructor.
Parameters
nd The NdiscCache this entry belongs to.
Definition at line 227 of file ndisc-cache.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
AddWaitingPacket()
void ns3::NdiscCache::Entry::AddWaitingPacket (Ipv6PayloadHeaderPair p)
Add a packet (or replace old value) in the queue.
Parameters
p packet to add
Todo:
report packet as 'dropped'
Definition at line 250 of file ndisc-cache.cc.
References ns3::NdiscCache::m_ndCache, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::Lookup().
ClearWaitingPacket()
void ns3::NdiscCache::Entry::ClearWaitingPacket ()
Clear the waiting packet list.
Todo:
report packets as 'dropped'
Definition at line 263 of file ndisc-cache.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Icmpv6L4Protocol::HandleNA(), ns3::Icmpv6L4Protocol::ReceiveLLA(), and ns3::NdiscCache::Remove().
FunctionDelayTimeout()
void ns3::NdiscCache::Entry::FunctionDelayTimeout ()
Function called when delay timer timeout.
Definition at line 325 of file ndisc-cache.cc.
References ns3::Ipv6Address::IsAny(), ns3::NdiscCache::m_ndCache, NS_LOG_FUNCTION_NOARGS, and ns3::Ipv6L3Protocol::PROT_NUMBER.
Referenced by StartDelayTimer().
FunctionProbeTimeout()
void ns3::NdiscCache::Entry::FunctionProbeTimeout ()
Function called when probe timer timeout.
Definition at line 360 of file ndisc-cache.cc.
References ns3::Ipv6Address::IsAny(), ns3::NdiscCache::m_icmpv6, ns3::NdiscCache::m_ndCache, NS_LOG_FUNCTION_NOARGS, and ns3::Ipv6L3Protocol::PROT_NUMBER.
Referenced by StartProbeTimer().
FunctionReachableTimeout()
void ns3::NdiscCache::Entry::FunctionReachableTimeout ()
Function called when reachable timer timeout.
Definition at line 270 of file ndisc-cache.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by StartReachableTimer().
FunctionRetransmitTimeout()
void ns3::NdiscCache::Entry::FunctionRetransmitTimeout ()
Function called when retransmit timer timeout.
It verify that the NS retransmit has reached the max so discard the entry otherwise it retransmit a NS.
Definition at line 276 of file ndisc-cache.cc.
References ns3::Icmpv6Header::ICMPV6_ADDR_UNREACHABLE, ns3::Ipv6Address::IsAny(), ns3::NdiscCache::m_icmpv6, ns3::NdiscCache::m_ndCache, ns3::Ipv6Address::MakeSolicitedAddress(), and NS_LOG_FUNCTION_NOARGS.
Referenced by StartRetransmitTimer().
GetLastReachabilityConfirmation()
Time ns3::NdiscCache::Entry::GetLastReachabilityConfirmation () const
Get the time of last reachability confirmation.
Returns
time
Definition at line 411 of file ndisc-cache.cc.
References NS_LOG_FUNCTION_NOARGS.
GetMacAddress()
Address ns3::NdiscCache::Entry::GetMacAddress () const
Get the MAC address of this entry.
Returns
the L2 address
Definition at line 586 of file ndisc-cache.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Icmpv6L4Protocol::HandleNA(), ns3::Icmpv6L4Protocol::HandleNS(), ns3::Icmpv6L4Protocol::HandleRedirection(), ns3::Icmpv6L4Protocol::HandleRS(), ns3::NdiscCache::Lookup(), ns3::Icmpv6L4Protocol::Lookup(), ns3::NdiscCache::LookupInverse(), and ns3::Icmpv6L4Protocol::ReceiveLLA().
IsDelay()
bool ns3::NdiscCache::Entry::IsDelay () const
Is the entry DELAY.
Returns
true if the entry is in DELAY state, false otherwise
Definition at line 562 of file ndisc-cache.cc.
References DELAY, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Icmpv6L4Protocol::Lookup().
IsIncomplete()
bool ns3::NdiscCache::Entry::IsIncomplete () const
Is the entry INCOMPLETE.
Returns
true if the entry is in INCOMPLETE state, false otherwise
Definition at line 568 of file ndisc-cache.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Icmpv6L4Protocol::HandleNA(), ns3::Icmpv6L4Protocol::HandleRedirection(), and ns3::Icmpv6L4Protocol::ReceiveLLA().
IsPermanent()
bool ns3::NdiscCache::Entry::IsPermanent () const
Is the entry PERMANENT.
Returns
true if the entry is in PERMANENT state, false otherwise
Definition at line 580 of file ndisc-cache.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Icmpv6L4Protocol::HandleNA(), ns3::Icmpv6L4Protocol::Lookup(), and ns3::Icmpv6L4Protocol::ReceiveLLA().
IsProbe()
bool ns3::NdiscCache::Entry::IsProbe () const
Is the entry PROBE.
Returns
true if the entry is in PROBE state, false otherwise
Definition at line 574 of file ndisc-cache.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Icmpv6L4Protocol::HandleNA(), and ns3::Icmpv6L4Protocol::ReceiveLLA().
IsReachable()
bool ns3::NdiscCache::Entry::IsReachable () const
Is the entry REACHABLE.
Returns
true if the entry is in REACHABLE state, false otherwise
Definition at line 556 of file ndisc-cache.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Icmpv6L4Protocol::HandleNA(), ns3::Icmpv6L4Protocol::Lookup(), and ns3::Icmpv6L4Protocol::ReceiveLLA().
IsRouter()
bool ns3::NdiscCache::Entry::IsRouter () const
If the entry is a host or a router.
Returns
true if the node is a router, 0 if it is a host
Definition at line 244 of file ndisc-cache.cc.
References NS_LOG_FUNCTION_NOARGS.
IsStale()
bool ns3::NdiscCache::Entry::IsStale () const
Is the entry STALE.
Returns
true if the entry is in STALE state, false otherwise
Definition at line 550 of file ndisc-cache.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Icmpv6L4Protocol::Lookup().
MarkDelay()
void ns3::NdiscCache::Entry::MarkDelay ()
Change the state to this entry to DELAY.
Definition at line 537 of file ndisc-cache.cc.
References DELAY, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Icmpv6L4Protocol::Lookup().
MarkIncomplete()
void ns3::NdiscCache::Entry::MarkIncomplete (Ipv6PayloadHeaderPair p)
Changes the state to this entry to INCOMPLETE.
Parameters
p packet that wait to be sent
Definition at line 492 of file ndisc-cache.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::Lookup().
MarkPermanent()
void ns3::NdiscCache::Entry::MarkPermanent ()
Change the state to this entry to PERMANENT.
Definition at line 543 of file ndisc-cache.cc.
References NS_LOG_FUNCTION_NOARGS.
MarkProbe()
void ns3::NdiscCache::Entry::MarkProbe ()
Changes the state to this entry to PROBE.
Definition at line 511 of file ndisc-cache.cc.
References NS_LOG_FUNCTION_NOARGS.
MarkReachable() [1/2]
void ns3::NdiscCache::Entry::MarkReachable ()
Changes the state to this entry to REACHABLE.
Definition at line 523 of file ndisc-cache.cc.
References NS_LOG_FUNCTION_NOARGS.
MarkReachable() [2/2]
std::list< NdiscCache::Ipv6PayloadHeaderPair > ns3::NdiscCache::Entry::MarkReachable (Address mac)
Changes the state to this entry to REACHABLE.
Parameters
mac MAC address
Returns
the list of packet waiting
Definition at line 503 of file ndisc-cache.cc.
References third::mac, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::HandleNA(), and ns3::Icmpv6L4Protocol::ReceiveLLA().
MarkStale() [1/2]
void ns3::NdiscCache::Entry::MarkStale ()
Changes the state to this entry to STALE.
Definition at line 517 of file ndisc-cache.cc.
References NS_LOG_FUNCTION_NOARGS.
MarkStale() [2/2]
std::list< NdiscCache::Ipv6PayloadHeaderPair > ns3::NdiscCache::Entry::MarkStale (Address mac)
Changes the state to this entry to STALE.
Parameters
mac L2 address
Returns
the list of packet waiting
Definition at line 529 of file ndisc-cache.cc.
References third::mac, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::HandleNA(), ns3::Icmpv6L4Protocol::HandleNS(), ns3::Icmpv6L4Protocol::HandleRedirection(), ns3::Icmpv6L4Protocol::HandleRS(), and ns3::Icmpv6L4Protocol::ReceiveLLA().
SetIpv6Address()
void ns3::NdiscCache::Entry::SetIpv6Address (Ipv6Address ipv6Address)
Set the IPv6 address.
Parameters
ipv6Address IPv6 address
Definition at line 405 of file ndisc-cache.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::NdiscCache::Add().
SetMacAddress()
void ns3::NdiscCache::Entry::SetMacAddress (Address mac)
Set the MAC address of this entry.
Parameters
mac the MAC address to set
Definition at line 592 of file ndisc-cache.cc.
References third::mac, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::HandleNA(), ns3::Icmpv6L4Protocol::HandleRedirection(), and ns3::Icmpv6L4Protocol::ReceiveLLA().
SetRouter()
void ns3::NdiscCache::Entry::SetRouter (bool router)
Set the node type.
Parameters
router true is a router, false means a host
Definition at line 238 of file ndisc-cache.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::HandleNA(), ns3::Icmpv6L4Protocol::HandleNS(), ns3::Icmpv6L4Protocol::HandleRedirection(), ns3::Icmpv6L4Protocol::HandleRS(), ns3::Icmpv6L4Protocol::Lookup(), and ns3::Icmpv6L4Protocol::ReceiveLLA().
StartDelayTimer()
void ns3::NdiscCache::Entry::StartDelayTimer ()
Start delay timer.
Definition at line 459 of file ndisc-cache.cc.
References FunctionDelayTimeout(), ns3::NdiscCache::m_ndCache, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Icmpv6L4Protocol::Lookup().
StartProbeTimer()
void ns3::NdiscCache::Entry::StartProbeTimer ()
Start probe timer.
Definition at line 446 of file ndisc-cache.cc.
References FunctionProbeTimeout(), ns3::NdiscCache::m_ndCache, and NS_LOG_FUNCTION_NOARGS.
StartReachableTimer()
void ns3::NdiscCache::Entry::StartReachableTimer ()
Start the reachable timer.
Definition at line 417 of file ndisc-cache.cc.
References FunctionReachableTimeout(), ns3::NdiscCache::m_ndCache, ns3::Simulator::Now(), and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Icmpv6L4Protocol::HandleNA(), and ns3::Icmpv6L4Protocol::ReceiveLLA().
StartRetransmitTimer()
void ns3::NdiscCache::Entry::StartRetransmitTimer ()
Start retransmit timer.
Definition at line 472 of file ndisc-cache.cc.
References FunctionRetransmitTimeout(), ns3::NdiscCache::m_ndCache, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Icmpv6L4Protocol::Lookup().
StopNudTimer()
void ns3::NdiscCache::Entry::StopNudTimer ()
Stop NUD timer and reset the NUD retransmission counter.
Definition at line 485 of file ndisc-cache.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Icmpv6L4Protocol::HandleNA(), and ns3::Icmpv6L4Protocol::ReceiveLLA().
UpdateReachableTimer()
void ns3::NdiscCache::Entry::UpdateReachableTimer ()
Update the reachable timer.
Definition at line 431 of file ndisc-cache.cc.
References ns3::Simulator::Now(), and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Ipv6L3Protocol::Receive().
Member Data Documentation
m_ipv6Address
Ipv6Address ns3::NdiscCache::Entry::m_ipv6Address private
The IPv6 address.
Definition at line 349 of file ndisc-cache.h.
m_lastReachabilityConfirmation
Time ns3::NdiscCache::Entry::m_lastReachabilityConfirmation private
Last time we see a reachability confirmation.
Definition at line 397 of file ndisc-cache.h.
m_macAddress
Address ns3::NdiscCache::Entry::m_macAddress private
The MAC address.
Definition at line 377 of file ndisc-cache.h.
m_ndCache
NdiscCache* ns3::NdiscCache::Entry::m_ndCache private
the NdiscCache associated.
Definition at line 372 of file ndisc-cache.h.
m_nsRetransmit
uint8_t ns3::NdiscCache::Entry::m_nsRetransmit private
Number of NS retransmission.
Definition at line 402 of file ndisc-cache.h.
m_nudTimer
Timer ns3::NdiscCache::Entry::m_nudTimer private
Timer (used for NUD).
Definition at line 392 of file ndisc-cache.h.
m_router
bool ns3::NdiscCache::Entry::m_router private
Type of node (router or host).
Definition at line 387 of file ndisc-cache.h.
m_state
NdiscCacheEntryState_e ns3::NdiscCache::Entry::m_state private
The state of the entry.
Definition at line 367 of file ndisc-cache.h.
m_waiting
std::list<Ipv6PayloadHeaderPair> ns3::NdiscCache::Entry::m_waiting private
The list of packet waiting.
Definition at line 382 of file ndisc-cache.h.
The documentation for this class was generated from the following files:
src/internet/model/ndisc-cache.h
src/internet/model/ndisc-cache.cc