ns-3: ns3::ConstantAccelerationMobilityModel Class Reference
ns3::ConstantAccelerationMobilityModel Class Reference
Mobility
Mobility model for which the current acceleration does not change once it has been set and until it is set again explicitly to a new value.
#include "constant-acceleration-mobility-model.h"
Public Member Functions
ConstantAccelerationMobilityModel ()
Create position located at coordinates (0,0,0) with speed (0,0,0).
virtual ~ConstantAccelerationMobilityModel ()
void SetVelocityAndAcceleration (const Vector &velocity, const Vector &acceleration)
Set the model's velocity and acceleration.
Public Member Functions inherited from ns3::MobilityModel
MobilityModel ()
virtual ~MobilityModel ()=0
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
double GetDistanceFrom (Ptr< const MobilityModel > position) const
Vector GetPosition (void) const
double GetRelativeSpeed (Ptr< const MobilityModel > other) const
Vector GetVelocity (void) const
void SetPosition (const Vector &position)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type with the TypeId system.
Static Public Member Functions inherited from ns3::MobilityModel
static TypeId GetTypeId (void)
Register this type with the TypeId system.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual Vector DoGetPosition (void) const
virtual Vector DoGetVelocity (void) const
virtual void DoSetPosition (const Vector &position)
Private Attributes
Vector m_acceleration
the acceleration
Vector m_basePosition
the base position
Time m_baseTime
the base time
Vector m_baseVelocity
the base velocity
Additional Inherited Members
Public Types inherited from ns3::MobilityModel
typedef void(* TracedCallback) (Ptr< const MobilityModel > model)
TracedCallback signature.
Protected Member Functions inherited from ns3::MobilityModel
void NotifyCourseChange (void) const
Must be invoked by subclasses when the course of the position changes to notify course change listeners.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Mobility model for which the current acceleration does not change once it has been set and until it is set again explicitly to a new value.
Definition at line 31 of file constant-acceleration-mobility-model.h.
Constructor & Destructor Documentation
ConstantAccelerationMobilityModel()
ns3::ConstantAccelerationMobilityModel::ConstantAccelerationMobilityModel ()
Create position located at coordinates (0,0,0) with speed (0,0,0).
Definition at line 34 of file constant-acceleration-mobility-model.cc.
~ConstantAccelerationMobilityModel()
ns3::ConstantAccelerationMobilityModel::~ConstantAccelerationMobilityModel () virtual
Definition at line 38 of file constant-acceleration-mobility-model.cc.
Member Function Documentation
DoGetPosition()
Vector ns3::ConstantAccelerationMobilityModel::DoGetPosition (void) const inline private virtual
Returns
the current position.
Concrete subclasses of this base class must implement this method.
Implements ns3::MobilityModel.
Definition at line 52 of file constant-acceleration-mobility-model.cc.
References m_acceleration, m_basePosition, m_baseTime, m_baseVelocity, and ns3::Simulator::Now().
Referenced by SetVelocityAndAcceleration().
DoGetVelocity()
Vector ns3::ConstantAccelerationMobilityModel::DoGetVelocity (void) const inline private virtual
Returns
the current velocity.
Concrete subclasses of this base class must implement this method.
Implements ns3::MobilityModel.
Definition at line 43 of file constant-acceleration-mobility-model.cc.
References m_acceleration, m_baseTime, m_baseVelocity, and ns3::Simulator::Now().
Referenced by DoSetPosition().
DoSetPosition()
void ns3::ConstantAccelerationMobilityModel::DoSetPosition (const Vector & position) private virtual
Parameters
position the position to set.
Concrete subclasses of this base class must implement this method.
Implements ns3::MobilityModel.
Definition at line 62 of file constant-acceleration-mobility-model.cc.
References DoGetVelocity(), m_basePosition, m_baseTime, m_baseVelocity, ns3::MobilityModel::NotifyCourseChange(), and ns3::Simulator::Now().
GetTypeId()
TypeId ns3::ConstantAccelerationMobilityModel::GetTypeId (void) static
Register this type with the TypeId system.
Returns
the object TypeId
Definition at line 25 of file constant-acceleration-mobility-model.cc.
References ns3::TypeId::SetParent().
SetVelocityAndAcceleration()
void ns3::ConstantAccelerationMobilityModel::SetVelocityAndAcceleration (const Vector & velocity, const Vector & acceleration)
Set the model's velocity and acceleration.
Parameters
velocity the velocity (m/s)
acceleration the acceleration (m/s^2)
Definition at line 71 of file constant-acceleration-mobility-model.cc.
References DoGetPosition(), m_acceleration, m_basePosition, m_baseTime, m_baseVelocity, ns3::MobilityModel::NotifyCourseChange(), and ns3::Simulator::Now().
Member Data Documentation
m_acceleration
Vector ns3::ConstantAccelerationMobilityModel::m_acceleration private
the acceleration
Definition at line 60 of file constant-acceleration-mobility-model.h.
Referenced by DoGetPosition(), DoGetVelocity(), and SetVelocityAndAcceleration().
m_basePosition
Vector ns3::ConstantAccelerationMobilityModel::m_basePosition private
the base position
Definition at line 58 of file constant-acceleration-mobility-model.h.
Referenced by DoGetPosition(), DoSetPosition(), and SetVelocityAndAcceleration().
m_baseTime
Time ns3::ConstantAccelerationMobilityModel::m_baseTime private
the base time
Definition at line 57 of file constant-acceleration-mobility-model.h.
Referenced by DoGetPosition(), DoGetVelocity(), DoSetPosition(), and SetVelocityAndAcceleration().
m_baseVelocity
Vector ns3::ConstantAccelerationMobilityModel::m_baseVelocity private
the base velocity
Definition at line 59 of file constant-acceleration-mobility-model.h.
Referenced by DoGetPosition(), DoGetVelocity(), DoSetPosition(), and SetVelocityAndAcceleration().
The documentation for this class was generated from the following files:
src/mobility/model/constant-acceleration-mobility-model.h
src/mobility/model/constant-acceleration-mobility-model.cc