ns-3: ns3::lorawan::BuildingPenetrationLoss Class Reference
ns3::lorawan::BuildingPenetrationLoss Class Reference
A class implementing the TR 45.820 model for building losses.
#include "building-penetration-loss.h"
Public Member Functions
BuildingPenetrationLoss ()
~BuildingPenetrationLoss ()
Public Member Functions inherited from ns3::PropagationLossModel
PropagationLossModel ()
virtual ~PropagationLossModel ()
int64_t AssignStreams (int64_t stream)
If this loss model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
double CalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account all the PropagationLossModel(s) chained to the current one.
Ptr< PropagationLossModel > GetNext ()
Gets the next PropagationLossModel in the chain of loss models that act on the signal.
void SetNext (Ptr< PropagationLossModel > next)
Enables a chain of loss models to act on the signal.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::PropagationLossModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual int64_t DoAssignStreams (int64_t stream)
Subclasses must implement this; those not using random variables can return zero.
virtual double DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Perform the computation of the received power according to the current model.
int GetPValue (void) const
Generate a random p value.
double GetTor1 (Ptr< MobilityModel > b) const
Get the Tor1 value used in the TR 45.820 standard to account for internal wall loss.
double GetWallLoss (Ptr< MobilityModel > b) const
Compute the wall loss associated to this mobility model.
int GetWallLossValue (void) const
Get a value to compute the wall loss.
Private Attributes
std::map< Ptr< MobilityModel >, int > m_pMap
A map linking each mobility model to a p value.
Ptr< UniformRandomVariable > m_uniformRV
An uniform RV.
std::map< Ptr< MobilityModel >, int > m_wallLossMap
A map linking each mobility model to a value deciding its external wall loss.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A class implementing the TR 45.820 model for building losses.
Definition at line 35 of file building-penetration-loss.h.
Constructor & Destructor Documentation
BuildingPenetrationLoss()
ns3::lorawan::BuildingPenetrationLoss::BuildingPenetrationLoss ()
Definition at line 43 of file building-penetration-loss.cc.
References m_uniformRV, and NS_LOG_FUNCTION_NOARGS.
~BuildingPenetrationLoss()
ns3::lorawan::BuildingPenetrationLoss::~BuildingPenetrationLoss ()
Definition at line 51 of file building-penetration-loss.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
DoAssignStreams()
int64_t ns3::lorawan::BuildingPenetrationLoss::DoAssignStreams (int64_t stream) private virtual
Subclasses must implement this; those not using random variables can return zero.
Implements ns3::PropagationLossModel.
Definition at line 134 of file building-penetration-loss.cc.
References m_uniformRV, and ns3::RandomVariableStream::SetStream().
DoCalcRxPower()
double ns3::lorawan::BuildingPenetrationLoss::DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const private virtual
Perform the computation of the received power according to the current model.
Implements ns3::PropagationLossModel.
Definition at line 57 of file building-penetration-loss.cc.
References ns3::Object::GetObject(), GetTor1(), ns3::UniformRandomVariable::GetValue(), GetWallLoss(), m_uniformRV, max, NS_LOG_DEBUG, NS_LOG_FUNCTION, and NS_LOG_INFO.
GetPValue()
int ns3::lorawan::BuildingPenetrationLoss::GetPValue (void) const private
Generate a random p value.
The distribution of the returned value is as specified in TR 45.820.
Returns
A value in the 0-3 range.
Definition at line 141 of file building-penetration-loss.cc.
References ns3::UniformRandomVariable::GetValue(), m_uniformRV, and NS_LOG_FUNCTION_NOARGS.
Referenced by GetTor1().
GetTor1()
double ns3::lorawan::BuildingPenetrationLoss::GetTor1 (Ptr< MobilityModel > b) const private
Get the Tor1 value used in the TR 45.820 standard to account for internal wall loss.
Parameters
b The mobility model of the node we want to compute the value for.
Returns
The tor1 value.
Definition at line 222 of file building-penetration-loss.cc.
References GetPValue(), ns3::UniformRandomVariable::GetValue(), m_pMap, m_uniformRV, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by DoCalcRxPower().
GetTypeId()
TypeId ns3::lorawan::BuildingPenetrationLoss::GetTypeId (void) static
Definition at line 33 of file building-penetration-loss.cc.
References ns3::TypeId::SetParent().
GetWallLoss()
double ns3::lorawan::BuildingPenetrationLoss::GetWallLoss (Ptr< MobilityModel > b) const private
Compute the wall loss associated to this mobility model.
Parameters
b The mobility model associated to the node whose wall loss we need to compute.
Returns
The power loss due to external walls.
Definition at line 191 of file building-penetration-loss.cc.
References ns3::UniformRandomVariable::GetValue(), GetWallLossValue(), m_uniformRV, m_wallLossMap, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by DoCalcRxPower().
GetWallLossValue()
int ns3::lorawan::BuildingPenetrationLoss::GetWallLossValue (void) const private
Get a value to compute the wall loss.
The distribution of the returned value is as specified in TR 45.820.
Returns
A value in the 0-2 range.
Definition at line 168 of file building-penetration-loss.cc.
References ns3::UniformRandomVariable::GetValue(), m_uniformRV, and NS_LOG_FUNCTION_NOARGS.
Referenced by GetWallLoss().
Member Data Documentation
m_pMap
std::map<Ptr<MobilityModel>, int> ns3::lorawan::BuildingPenetrationLoss::m_pMap mutable private
A map linking each mobility model to a p value.
Definition at line 90 of file building-penetration-loss.h.
Referenced by GetTor1().
m_uniformRV
Ptr<UniformRandomVariable> ns3::lorawan::BuildingPenetrationLoss::m_uniformRV private
An uniform RV.
Definition at line 85 of file building-penetration-loss.h.
Referenced by BuildingPenetrationLoss(), DoAssignStreams(), DoCalcRxPower(), GetPValue(), GetTor1(), GetWallLoss(), and GetWallLossValue().
m_wallLossMap
std::map<Ptr<MobilityModel>, int> ns3::lorawan::BuildingPenetrationLoss::m_wallLossMap mutable private
A map linking each mobility model to a value deciding its external wall loss.
Definition at line 96 of file building-penetration-loss.h.
Referenced by GetWallLoss().
The documentation for this class was generated from the following files:
src/lorawan/model/building-penetration-loss.h
src/lorawan/model/building-penetration-loss.cc