ns-3: ns3::LbtsMessage Class Reference
ns3::LbtsMessage Class Reference
MPI Distributed Simulation
Structure used for all-reduce LBTS computation.
#include "distributed-simulator-impl.h"
Public Member Functions
LbtsMessage ()
LbtsMessage (uint32_t rxc, uint32_t txc, uint32_t id, bool isFinished, const Time &t)
~LbtsMessage ()
uint32_t GetMyId ()
uint32_t GetRxCount ()
Time GetSmallestTime ()
uint32_t GetTxCount ()
bool IsFinished ()
Private Attributes
bool m_isFinished
uint32_t m_myId
uint32_t m_rxCount
Time m_smallestTime
uint32_t m_txCount
Detailed Description
Structure used for all-reduce LBTS computation.
Definition at line 37 of file distributed-simulator-impl.h.
Constructor & Destructor Documentation
LbtsMessage() [1/2]
ns3::LbtsMessage::LbtsMessage () inline
Definition at line 40 of file distributed-simulator-impl.h.
LbtsMessage() [2/2]
ns3::LbtsMessage::LbtsMessage (uint32_t rxc, uint32_t txc, uint32_t id, bool isFinished, const Time & t) inline
Parameters
rxc received count
txc transmitted count
id mpi rank
isFinished whether message is finished
t smallest time
Definition at line 55 of file distributed-simulator-impl.h.
~LbtsMessage()
ns3::LbtsMessage::~LbtsMessage ()
Definition at line 46 of file distributed-simulator-impl.cc.
Member Function Documentation
GetMyId()
uint32_t ns3::LbtsMessage::GetMyId ()
Returns
id which corresponds to mpi rank
Definition at line 68 of file distributed-simulator-impl.cc.
References m_myId.
GetRxCount()
uint32_t ns3::LbtsMessage::GetRxCount ()
Returns
received count
Definition at line 63 of file distributed-simulator-impl.cc.
References m_rxCount.
Referenced by ns3::DistributedSimulatorImpl::Run().
GetSmallestTime()
Time ns3::LbtsMessage::GetSmallestTime ()
Returns
smallest time
Definition at line 51 of file distributed-simulator-impl.cc.
References m_smallestTime.
Referenced by ns3::DistributedSimulatorImpl::Run().
GetTxCount()
uint32_t ns3::LbtsMessage::GetTxCount ()
Returns
transmitted count
Definition at line 57 of file distributed-simulator-impl.cc.
References m_txCount.
Referenced by ns3::DistributedSimulatorImpl::Run().
IsFinished()
bool ns3::LbtsMessage::IsFinished ()
Returns
true if system is finished
Definition at line 74 of file distributed-simulator-impl.cc.
References m_isFinished.
Referenced by ns3::DistributedSimulatorImpl::Run().
Member Data Documentation
m_isFinished
bool ns3::LbtsMessage::m_isFinished private
Definition at line 92 of file distributed-simulator-impl.h.
Referenced by IsFinished().
m_myId
uint32_t ns3::LbtsMessage::m_myId private
Definition at line 90 of file distributed-simulator-impl.h.
Referenced by GetMyId().
m_rxCount
uint32_t ns3::LbtsMessage::m_rxCount private
Definition at line 89 of file distributed-simulator-impl.h.
Referenced by GetRxCount().
m_smallestTime
Time ns3::LbtsMessage::m_smallestTime private
Definition at line 91 of file distributed-simulator-impl.h.
Referenced by GetSmallestTime().
m_txCount
uint32_t ns3::LbtsMessage::m_txCount private
Definition at line 88 of file distributed-simulator-impl.h.
Referenced by GetTxCount().
The documentation for this class was generated from the following files:
src/mpi/model/distributed-simulator-impl.h
src/mpi/model/distributed-simulator-impl.cc