ns-3: ns3::PacketCounterCalculator Class Reference
ns3::PacketCounterCalculator Class Reference
Statistics
#include "packet-data-calculators.h"
Public Member Functions
PacketCounterCalculator ()
virtual ~PacketCounterCalculator ()
void FrameUpdate (std::string path, Ptr< const Packet > packet, Mac48Address realto)
Increments the packet counter by one.
void PacketUpdate (std::string path, Ptr< const Packet > packet)
Increments the packet counter by one.
Public Member Functions inherited from ns3::CounterCalculator< uint32_t >
CounterCalculator ()
virtual ~CounterCalculator ()
uint32_t GetCount () const
Returns the count of the CounterCalculator.
virtual void Output (DataOutputCallback &callback) const
Outputs the data based on the provided callback.
void Update ()
Increments count by 1.
void Update (const uint32_t i)
Increments count by i.
Public Member Functions inherited from ns3::DataCalculator
DataCalculator ()
virtual ~DataCalculator ()
void Disable ()
Disables DataCalculator when simulation stops.
void Enable ()
Enables DataCalculator when simulation starts.
std::string GetContext () const
Gets the DataCalculator context.
bool GetEnabled () const
Returns whether the DataCalculator is enabled.
std::string GetKey () const
Gets the DataCalculator key.
void SetContext (const std::string context)
Sets the DataCalculator context to the provided context.
void SetKey (const std::string key)
Sets the DataCalculator key to the provided key.
virtual void Start (const Time &startTime)
Starts DataCalculator at a given time in the simulation.
virtual void Stop (const Time &stopTime)
Stops DataCalculator at a given time in the simulation.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::CounterCalculator< uint32_t >
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::DataCalculator
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Additional Inherited Members
Protected Attributes inherited from ns3::CounterCalculator< uint32_t >
uint32_t m_count
Count value of CounterCalculator.
Protected Attributes inherited from ns3::DataCalculator
std::string m_context
Context value.
bool m_enabled
Descendant classes must check & respect m_enabled!
std::string m_key
Key value.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A stat for counting packets
Definition at line 37 of file packet-data-calculators.h.
Constructor & Destructor Documentation
PacketCounterCalculator()
PacketCounterCalculator::PacketCounterCalculator ()
Definition at line 34 of file packet-data-calculators.cc.
References NS_LOG_FUNCTION_NOARGS.
~PacketCounterCalculator()
PacketCounterCalculator::~PacketCounterCalculator () virtual
Definition at line 39 of file packet-data-calculators.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
DoDispose()
void PacketCounterCalculator::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::CounterCalculator< uint32_t >.
Definition at line 55 of file packet-data-calculators.cc.
References ns3::CounterCalculator< T >::DoDispose(), and NS_LOG_FUNCTION_NOARGS.
FrameUpdate()
void PacketCounterCalculator::FrameUpdate (std::string path, Ptr< const Packet > packet, Mac48Address realto)
Increments the packet counter by one.
Parameters
path not used in this method
packet not used in this method
realto not used in this method
Definition at line 74 of file packet-data-calculators.cc.
References NS_LOG_FUNCTION_NOARGS, and ns3::CounterCalculator< T >::Update().
GetTypeId()
TypeId PacketCounterCalculator::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 45 of file packet-data-calculators.cc.
References ns3::TypeId::SetParent().
PacketUpdate()
void PacketCounterCalculator::PacketUpdate (std::string path, Ptr< const Packet > packet)
Increments the packet counter by one.
Parameters
path not used in this method
packet not used in this method
Definition at line 64 of file packet-data-calculators.cc.
References NS_LOG_FUNCTION_NOARGS, and ns3::CounterCalculator< T >::Update().
The documentation for this class was generated from the following files:
src/network/utils/packet-data-calculators.h
src/network/utils/packet-data-calculators.cc