ns-3: TcpLedbatToNewReno Class Reference
TcpLedbatToNewReno Class Reference
Internet » internet module tests | Test suites
LEDBAT should be same as NewReno during slow start, and when timestamps are disabled.
Public Member Functions
TcpLedbatToNewReno (uint32_t cWnd, uint32_t segmentSize, uint32_t ssThresh, uint32_t segmentsAcked, SequenceNumber32 highTxMark, SequenceNumber32 lastAckedSeq, Time rtt, const std::string &name)
Constructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void ExecuteTest (void)
Execute the test.
Private Attributes
uint32_t m_cWnd
cWnd
SequenceNumber32 m_highTxMark
high tx mark
SequenceNumber32 m_lastAckedSeq
last acked seq
Time m_rtt
rtt
uint32_t m_segmentsAcked
segments acked
uint32_t m_segmentSize
segment size
uint32_t m_ssThresh
ss thresh
Ptr< TcpSocketState > m_state
state
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
LEDBAT should be same as NewReno during slow start, and when timestamps are disabled.
Definition at line 39 of file tcp-ledbat-test.cc.
Constructor & Destructor Documentation
TcpLedbatToNewReno()
TcpLedbatToNewReno::TcpLedbatToNewReno (uint32_t cWnd, uint32_t segmentSize, uint32_t ssThresh, uint32_t segmentsAcked, SequenceNumber32 highTxMark, SequenceNumber32 lastAckedSeq, Time rtt, const std::string & name)
Constructor.
Parameters
cWnd congestion window
segmentSize segment size
ssThresh slow start threshold
segmentsAcked segments acked
highTxMark high tx mark
lastAckedSeq last acked seq
rtt RTT
name Name of the test
Definition at line 74 of file tcp-ledbat-test.cc.
Member Function Documentation
DoRun()
void TcpLedbatToNewReno::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 89 of file tcp-ledbat-test.cc.
References ExecuteTest(), and ns3::Seconds().
ExecuteTest()
void TcpLedbatToNewReno::ExecuteTest (void) private
Execute the test.
Definition at line 97 of file tcp-ledbat-test.cc.
References ns3::TracedValue< T >::Get(), ns3::TcpNewReno::IncreaseWindow(), ns3::TcpLedbat::IncreaseWindow(), ns3::TcpSocketState::m_cWnd, m_cWnd, ns3::TcpSocketState::m_highTxMark, m_highTxMark, ns3::TcpSocketState::m_lastAckedSeq, m_lastAckedSeq, m_segmentsAcked, ns3::TcpSocketState::m_segmentSize, m_segmentSize, ns3::TcpSocketState::m_ssThresh, m_ssThresh, m_state, and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
Member Data Documentation
m_cWnd
uint32_t TcpLedbatToNewReno::m_cWnd private
cWnd
Definition at line 64 of file tcp-ledbat-test.cc.
Referenced by ExecuteTest().
m_highTxMark
SequenceNumber32 TcpLedbatToNewReno::m_highTxMark private
high tx mark
Definition at line 69 of file tcp-ledbat-test.cc.
Referenced by ExecuteTest().
m_lastAckedSeq
SequenceNumber32 TcpLedbatToNewReno::m_lastAckedSeq private
last acked seq
Definition at line 70 of file tcp-ledbat-test.cc.
Referenced by ExecuteTest().
m_rtt
Time TcpLedbatToNewReno::m_rtt private
rtt
Definition at line 68 of file tcp-ledbat-test.cc.
m_segmentsAcked
uint32_t TcpLedbatToNewReno::m_segmentsAcked private
segments acked
Definition at line 66 of file tcp-ledbat-test.cc.
Referenced by ExecuteTest().
m_segmentSize
uint32_t TcpLedbatToNewReno::m_segmentSize private
segment size
Definition at line 65 of file tcp-ledbat-test.cc.
Referenced by ExecuteTest().
m_ssThresh
uint32_t TcpLedbatToNewReno::m_ssThresh private
ss thresh
Definition at line 67 of file tcp-ledbat-test.cc.
Referenced by ExecuteTest().
m_state
Ptr<TcpSocketState> TcpLedbatToNewReno::m_state private
state
Definition at line 71 of file tcp-ledbat-test.cc.
Referenced by ExecuteTest().
The documentation for this class was generated from the following file:
src/internet/test/tcp-ledbat-test.cc