ns-3: ns3::RrcConnectionReconfigurationHeader Class Reference
ns3::RrcConnectionReconfigurationHeader Class Reference
This class manages the serialization/deserialization of RrcConnectionReconfiguration IE.
#include "lte-rrc-header.h"
Public Member Functions
RrcConnectionReconfigurationHeader ()
~RrcConnectionReconfigurationHeader ()
uint32_t Deserialize (Buffer::Iterator bIterator)
std::list< LteRrcSap::DrbToAddMod > GetDrbToAddModList () const
Gets m_radioResourceConfigDedicated.drbToAddModList.
std::list< uint8_t > GetDrbToReleaseList () const
Gets m_radioResourceConfigDedicated.drbToReleaseList.
bool GetHaveMeasConfig ()
Getter for m_haveMeasConfig.
bool GetHaveMobilityControlInfo ()
Getter for m_haveMobilityControlInfo.
bool GetHaveNonCriticalExtensionConfig ()
Getter for m_haveNonCriticalExtension.
bool GetHaveRadioResourceConfigDedicated ()
Getter for m_haveRadioResourceConfigDedicated.
LteRrcSap::MeasConfig GetMeasConfig ()
Getter for m_measConfig.
LteRrcSap::RrcConnectionReconfiguration GetMessage () const
Returns a RrcConnectionReconfiguration IE from the values in the class attributes.
LteRrcSap::MobilityControlInfo GetMobilityControlInfo ()
Getter for m_mobilityControlInfo.
LteRrcSap::NonCriticalExtensionConfiguration GetNonCriticalExtensionConfig ()
Getter for m_nonCriticalExtension.
LteRrcSap::PhysicalConfigDedicated GetPhysicalConfigDedicated () const
Gets m_radioResourceConfigDedicated.physicalConfigDedicated.
LteRrcSap::RadioResourceConfigDedicated GetRadioResourceConfigDedicated ()
Getter for m_radioResourceConfigDedicated.
LteRrcSap::RadioResourceConfigDedicated GetRadioResourceConfigDedicated () const
Getter for m_radioResourceConfigDedicated.
uint8_t GetRrcTransactionIdentifier () const
Getter for m_rrcTransactionIdentifier.
std::list< LteRrcSap::SrbToAddMod > GetSrbToAddModList () const
Gets m_radioResourceConfigDedicated.srbToAddModList.
bool HavePhysicalConfigDedicated () const
Gets m_radioResourceConfigDedicated.havePhysicalConfigDedicated.
void PreSerialize () const
This function serializes class attributes to m_serializationResult local Buffer.
void Print (std::ostream &os) const
This function prints the object, for debugging purposes.
void SetMessage (LteRrcSap::RrcConnectionReconfiguration msg)
Receives a RrcConnectionReconfiguration IE and stores the contents into the class attributes.
Public Member Functions inherited from ns3::RrcDlDcchMessage
RrcDlDcchMessage ()
~RrcDlDcchMessage ()
Public Member Functions inherited from ns3::RrcAsn1Header
RrcAsn1Header ()
int GetMessageType ()
Get message type.
Public Member Functions inherited from ns3::Asn1Header
Asn1Header ()
virtual ~Asn1Header ()
uint32_t GetSerializedSize (void) const
void Serialize (Buffer::Iterator bIterator) const
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Private Attributes
bool m_haveMeasConfig
have measure config?
bool m_haveMobilityControlInfo
have mobility control info?
bool m_haveNonCriticalExtension
Have critical extension.
bool m_haveRadioResourceConfigDedicated
have radio resource config dedicated?
LteRrcSap::MeasConfig m_measConfig
the measure config
LteRrcSap::MobilityControlInfo m_mobilityControlInfo
the modility control info
LteRrcSap::NonCriticalExtensionConfiguration m_nonCriticalExtension
the critical extension
LteRrcSap::RadioResourceConfigDedicated m_radioResourceConfigDedicated
the radio resource config dedicated
uint8_t m_rrcTransactionIdentifier
RRC transaction identifier.
Additional Inherited Members
Static Public Member Functions inherited from ns3::Asn1Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions inherited from ns3::RrcDlDcchMessage
Buffer::Iterator DeserializeDlDcchMessage (Buffer::Iterator bIterator)
Deserialize DL DCCH message function.
void SerializeDlDcchMessage (int msgType) const
Serialize DL DCCH message function.
Protected Member Functions inherited from ns3::RrcAsn1Header
int BandwidthToEnum (uint16_t bandwidth) const
Convert from bandwidth (in RBs) to ENUMERATED value.
Buffer::Iterator DeserializeCellIdentification (LteRrcSap::CellIdentification *ci, Buffer::Iterator bIterator)
Deserialize cell identification function.
Buffer::Iterator DeserializeDrbToAddModList (std::list< LteRrcSap::DrbToAddMod > *drbToAddModLis, Buffer::Iterator bIterator)
Deserialize DRB to add mod list function.
Buffer::Iterator DeserializeLogicalChannelConfig (LteRrcSap::LogicalChannelConfig *logicalChannelConfig, Buffer::Iterator bIterator)
Deserialize logical channel config function.
Buffer::Iterator DeserializeMeasConfig (LteRrcSap::MeasConfig *measConfig, Buffer::Iterator bIterator)
Deserialize measure config function.
Buffer::Iterator DeserializeMeasResults (LteRrcSap::MeasResults *measResults, Buffer::Iterator bIterator)
Deserialize measure results function.
Buffer::Iterator DeserializeNonCriticalExtensionConfig (LteRrcSap::NonCriticalExtensionConfiguration *nonCriticalExtension, Buffer::Iterator bIterator)
Deserialize non critical extension config function.
Buffer::Iterator DeserializePhysicalConfigDedicated (LteRrcSap::PhysicalConfigDedicated *physicalConfigDedicated, Buffer::Iterator bIterator)
Deserialize physical config dedicated function.
Buffer::Iterator DeserializePhysicalConfigDedicatedSCell (LteRrcSap::PhysicalConfigDedicatedSCell *pcdsc, Buffer::Iterator bIterator)
Deserialize physical config dedicated SCell function.
Buffer::Iterator DeserializePlmnIdentity (uint32_t *plmnId, Buffer::Iterator bIterator)
Deserialize PLMN identity function.
Buffer::Iterator DeserializeQoffsetRange (int8_t *qOffsetRange, Buffer::Iterator bIterator)
Deserialize Qoffset range function.
Buffer::Iterator DeserializeRachConfigCommon (LteRrcSap::RachConfigCommon *rachConfigCommon, Buffer::Iterator bIterator)
Deserialize RACH config common function.
Buffer::Iterator DeserializeRadioResourceConfigCommon (LteRrcSap::RadioResourceConfigCommon *radioResourceConfigCommon, Buffer::Iterator bIterator)
Deserialize radio resource config common function.
Buffer::Iterator DeserializeRadioResourceConfigCommonSCell (LteRrcSap::RadioResourceConfigCommonSCell *rrccsc, Buffer::Iterator bIterator)
Deserialize radio resource config common SCell function.
Buffer::Iterator DeserializeRadioResourceConfigCommonSib (LteRrcSap::RadioResourceConfigCommonSib *radioResourceConfigCommonSib, Buffer::Iterator bIterator)
Deserialize radio resource config common SIB function.
Buffer::Iterator DeserializeRadioResourceConfigDedicated (LteRrcSap::RadioResourceConfigDedicated *radioResourceConfigDedicated, Buffer::Iterator bIterator)
Deserialize radio resource config dedicated function.
Buffer::Iterator DeserializeRadioResourceConfigDedicatedSCell (LteRrcSap::RadioResourceConfigDedicatedSCell *rrcdsc, Buffer::Iterator bIterator)
Deserialize radio resource config dedicated SCell function.
Buffer::Iterator DeserializeSrbToAddModList (std::list< LteRrcSap::SrbToAddMod > *srbToAddModList, Buffer::Iterator bIterator)
Deserialize SRB to add mod list function.
Buffer::Iterator DeserializeSystemInformationBlockType1 (LteRrcSap::SystemInformationBlockType1 *systemInformationBlockType1, Buffer::Iterator bIterator)
Deserialize system information block type 1 function.
Buffer::Iterator DeserializeSystemInformationBlockType2 (LteRrcSap::SystemInformationBlockType2 *systemInformationBlockType2, Buffer::Iterator bIterator)
Deserialize system information block type 2 function.
Buffer::Iterator DeserializeThresholdEutra (LteRrcSap::ThresholdEutra *thresholdEutra, Buffer::Iterator bIterator)
Deserialize threshold eutra function.
uint16_t EnumToBandwidth (int n) const
Convert from ENUMERATED value to bandwidth (in RBs)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
void Print (std::ostream &os, LteRrcSap::RadioResourceConfigDedicated radioResourceConfigDedicated) const
This function prints RadioResourceConfigDedicated IE, for debugging purposes.
void SerializeDrbToAddModList (std::list< LteRrcSap::DrbToAddMod > drbToAddModList) const
Serialize DRB to add mod list function.
void SerializeLogicalChannelConfig (LteRrcSap::LogicalChannelConfig logicalChannelConfig) const
Serialize logicala channel config function.
void SerializeMeasConfig (LteRrcSap::MeasConfig measConfig) const
Serialize measure config function.
void SerializeMeasResults (LteRrcSap::MeasResults measResults) const
Serialize measure results function.
void SerializeNonCriticalExtensionConfiguration (LteRrcSap::NonCriticalExtensionConfiguration nonCriticalExtensionConfiguration) const
Serialize non critical extension config function.
void SerializePhysicalConfigDedicated (LteRrcSap::PhysicalConfigDedicated physicalConfigDedicated) const
Serialize physical config dedicated function.
void SerializePhysicalConfigDedicatedSCell (LteRrcSap::PhysicalConfigDedicatedSCell pcdsc) const
Serialize physical config dedicated function.
void SerializePlmnIdentity (uint32_t plmnId) const
Serialize PLMN identity function.
void SerializeQoffsetRange (int8_t qOffsetRange) const
Serialize Q offset range function.
void SerializeRachConfigCommon (LteRrcSap::RachConfigCommon rachConfigCommon) const
Serialize RACH config common function.
void SerializeRadioResourceConfigCommon (LteRrcSap::RadioResourceConfigCommon radioResourceConfigCommon) const
Serialize system information block type 2 function.
void SerializeRadioResourceConfigCommonSCell (LteRrcSap::RadioResourceConfigCommonSCell rrccsc) const
Serialize radio resource config common SCell function.
void SerializeRadioResourceConfigCommonSib (LteRrcSap::RadioResourceConfigCommonSib radioResourceConfigCommonSib) const
Serialize radio resource config common SIB function.
void SerializeRadioResourceConfigDedicated (LteRrcSap::RadioResourceConfigDedicated radioResourceConfigDedicated) const
Serialize radio resource config function.
void SerializeRadioResourceDedicatedSCell (LteRrcSap::RadioResourceConfigDedicatedSCell rrcdsc) const
Serialize radio resource dedicated SCell function.
void SerializeSrbToAddModList (std::list< LteRrcSap::SrbToAddMod > srbToAddModList) const
Serialize SRB to add mod list function.
void SerializeSystemInformationBlockType1 (LteRrcSap::SystemInformationBlockType1 systemInformationBlockType1) const
Serialize system information block type 1 function.
void SerializeSystemInformationBlockType2 (LteRrcSap::SystemInformationBlockType2 systemInformationBlockType2) const
Serialize system information block type 2 function.
void SerializeThresholdEutra (LteRrcSap::ThresholdEutra thresholdEutra) const
Serialize threshold eutra function.
Protected Member Functions inherited from ns3::Asn1Header
Buffer::Iterator DeserializeBitset (std::bitset< 8 > *data, Buffer::Iterator bIterator)
Deserialize a bitset.
template<int N>
Buffer::Iterator DeserializeBitset (std::bitset< N > *data, Buffer::Iterator bIterator)
Deserialize a bitset.
Buffer::Iterator DeserializeBitstring (std::bitset< 1 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 10 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 16 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 2 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 27 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 28 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 32 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBitstring (std::bitset< 8 > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
template<int N>
Buffer::Iterator DeserializeBitstring (std::bitset< N > *bitstring, Buffer::Iterator bIterator)
Deserialize a bitstring.
Buffer::Iterator DeserializeBoolean (bool *value, Buffer::Iterator bIterator)
Deserialize a boolean.
Buffer::Iterator DeserializeChoice (int numOptions, bool isExtensionMarkerPresent, int *selectedOption, Buffer::Iterator bIterator)
Deserialize a Choice (set of options)
Buffer::Iterator DeserializeEnum (int numElems, int *selectedElem, Buffer::Iterator bIterator)
Deserialize an Enum.
Buffer::Iterator DeserializeInteger (int *n, int nmin, int nmax, Buffer::Iterator bIterator)
Deserialize an integer.
Buffer::Iterator DeserializeNull (Buffer::Iterator bIterator)
Deserialize nothing (null op)
Buffer::Iterator DeserializeSequence (std::bitset< 0 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 1 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 10 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 11 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 2 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 3 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 4 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 5 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 6 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 7 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequence (std::bitset< 9 > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
template<int N>
Buffer::Iterator DeserializeSequence (std::bitset< N > *optionalOrDefaultMask, bool isExtensionMarkerPresent, Buffer::Iterator bIterator)
Deserialize a sequence.
Buffer::Iterator DeserializeSequenceOf (int *numElems, int nMax, int nMin, Buffer::Iterator bIterator)
Deserialize a Sequence.
void FinalizeSerialization () const
Finalizes an in progress serialization.
template<int N>
void SerializeBitset (std::bitset< N > data) const
Serialize a bitset.
void SerializeBitstring (std::bitset< 1 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 10 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 16 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 2 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 27 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 28 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 32 > bitstring) const
Serialize a bitstring.
void SerializeBitstring (std::bitset< 8 > bitstring) const
Serialize a bitstring.
template<int N>
void SerializeBitstring (std::bitset< N > bitstring) const
Serialize a bitstring.
void SerializeBoolean (bool value) const
Serialize a bool.
void SerializeChoice (int numOptions, int selectedOption, bool isExtensionMarkerPresent) const
Serialize a Choice (set of options)
void SerializeEnum (int numElems, int selectedElem) const
Serialize an Enum.
void SerializeInteger (int n, int nmin, int nmax) const
Serialize an Integer.
void SerializeNull () const
Serialize nothing (null op)
void SerializeSequence (std::bitset< 0 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 1 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 10 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 11 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 2 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 3 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 4 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 5 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 6 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 7 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequence (std::bitset< 9 > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
template<int N>
void SerializeSequence (std::bitset< N > optionalOrDefaultMask, bool isExtensionMarkerPresent) const
Serialize a sequence.
void SerializeSequenceOf (int numElems, int nMax, int nMin) const
Serialize a Sequence.
void WriteOctet (uint8_t octet) const
Function to write in m_serializationResult, after resizing its size.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Static Protected Member Functions inherited from ns3::RrcAsn1Header
static TypeId GetTypeId (void)
Get the type ID.
Protected Attributes inherited from ns3::RrcAsn1Header
int m_messageType
Stores RRC message type, according to 3GPP TS 36.331.
Protected Attributes inherited from ns3::Asn1Header
bool m_isDataSerialized
true if data is serialized
uint8_t m_numSerializationPendingBits
number of pending bits
uint8_t m_serializationPendingBits
pending bits
Buffer m_serializationResult
serialization result
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class manages the serialization/deserialization of RrcConnectionReconfiguration IE.
Definition at line 709 of file lte-rrc-header.h.
Constructor & Destructor Documentation
RrcConnectionReconfigurationHeader()
ns3::RrcConnectionReconfigurationHeader::RrcConnectionReconfigurationHeader ()
Definition at line 5085 of file lte-rrc-header.cc.
~RrcConnectionReconfigurationHeader()
ns3::RrcConnectionReconfigurationHeader::~RrcConnectionReconfigurationHeader ()
Definition at line 5089 of file lte-rrc-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::RrcConnectionReconfigurationHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Reimplemented from ns3::RrcDlDcchMessage.
Definition at line 5214 of file lte-rrc-header.cc.
References ns3::LteRrcSap::MobilityControlInfo::carrierBandwidth, ns3::LteRrcSap::MobilityControlInfo::carrierFreq, ns3::Asn1Header::DeserializeBitstring(), ns3::Asn1Header::DeserializeChoice(), ns3::RrcDlDcchMessage::DeserializeDlDcchMessage(), ns3::Asn1Header::DeserializeEnum(), ns3::Asn1Header::DeserializeInteger(), ns3::RrcAsn1Header::DeserializeMeasConfig(), ns3::RrcAsn1Header::DeserializeNonCriticalExtensionConfig(), ns3::Asn1Header::DeserializeNull(), ns3::RrcAsn1Header::DeserializeRadioResourceConfigCommon(), ns3::RrcAsn1Header::DeserializeRadioResourceConfigDedicated(), ns3::Asn1Header::DeserializeSequence(), ns3::LteRrcSap::CarrierBandwidthEutra::dlBandwidth, ns3::LteRrcSap::CarrierFreqEutra::dlCarrierFreq, ns3::RrcAsn1Header::EnumToBandwidth(), ns3::Asn1Header::GetSerializedSize(), ns3::LteRrcSap::MobilityControlInfo::haveCarrierBandwidth, ns3::LteRrcSap::MobilityControlInfo::haveCarrierFreq, ns3::LteRrcSap::MobilityControlInfo::haveRachConfigDedicated, m_haveMeasConfig, m_haveMobilityControlInfo, m_haveNonCriticalExtension, m_haveRadioResourceConfigDedicated, m_measConfig, m_mobilityControlInfo, m_nonCriticalExtension, m_radioResourceConfigDedicated, m_rrcTransactionIdentifier, MAX_EARFCN, sample-rng-plot::n, ns3::LteRrcSap::MobilityControlInfo::newUeIdentity, ns3::LteRrcSap::MobilityControlInfo::rachConfigDedicated, ns3::LteRrcSap::MobilityControlInfo::radioResourceConfigCommon, ns3::LteRrcSap::RachConfigDedicated::raPrachMaskIndex, ns3::LteRrcSap::RachConfigDedicated::raPreambleIndex, ns3::LteRrcSap::MobilityControlInfo::targetPhysCellId, ns3::LteRrcSap::CarrierBandwidthEutra::ulBandwidth, and ns3::LteRrcSap::CarrierFreqEutra::ulCarrierFreq.
GetDrbToAddModList()
std::list< LteRrcSap::DrbToAddMod > ns3::RrcConnectionReconfigurationHeader::GetDrbToAddModList () const
Gets m_radioResourceConfigDedicated.drbToAddModList.
Returns
m_radioResourceConfigDedicated.drbToAddModList
Definition at line 5700 of file lte-rrc-header.cc.
References ns3::LteRrcSap::RadioResourceConfigDedicated::drbToAddModList, and m_radioResourceConfigDedicated.
GetDrbToReleaseList()
std::list< uint8_t > ns3::RrcConnectionReconfigurationHeader::GetDrbToReleaseList () const
Gets m_radioResourceConfigDedicated.drbToReleaseList.
Returns
m_radioResourceConfigDedicated.drbToReleaseList
Definition at line 5706 of file lte-rrc-header.cc.
References ns3::LteRrcSap::RadioResourceConfigDedicated::drbToReleaseList, and m_radioResourceConfigDedicated.
GetHaveMeasConfig()
bool ns3::RrcConnectionReconfigurationHeader::GetHaveMeasConfig ()
Getter for m_haveMeasConfig.
Returns
m_haveMeasConfig
Definition at line 5640 of file lte-rrc-header.cc.
References m_haveMeasConfig.
Referenced by RrcConnectionReconfigurationTestCase::DoRun().
GetHaveMobilityControlInfo()
bool ns3::RrcConnectionReconfigurationHeader::GetHaveMobilityControlInfo ()
Getter for m_haveMobilityControlInfo.
Returns
m_haveMobilityControlInfo
Definition at line 5652 of file lte-rrc-header.cc.
References m_haveMobilityControlInfo.
Referenced by RrcConnectionReconfigurationTestCase::DoRun().
GetHaveNonCriticalExtensionConfig()
bool ns3::RrcConnectionReconfigurationHeader::GetHaveNonCriticalExtensionConfig ()
Getter for m_haveNonCriticalExtension.
Returns
m_haveNonCriticalExtension
Definition at line 5676 of file lte-rrc-header.cc.
References m_haveNonCriticalExtension.
GetHaveRadioResourceConfigDedicated()
bool ns3::RrcConnectionReconfigurationHeader::GetHaveRadioResourceConfigDedicated ()
Getter for m_haveRadioResourceConfigDedicated.
Returns
m_haveRadioResourceConfigDedicated
Definition at line 5664 of file lte-rrc-header.cc.
References m_haveRadioResourceConfigDedicated.
Referenced by RrcConnectionReconfigurationTestCase::DoRun().
GetMeasConfig()
LteRrcSap::MeasConfig ns3::RrcConnectionReconfigurationHeader::GetMeasConfig ()
Getter for m_measConfig.
Returns
m_measConfig
Definition at line 5646 of file lte-rrc-header.cc.
References m_measConfig.
GetMessage()
LteRrcSap::RrcConnectionReconfiguration ns3::RrcConnectionReconfigurationHeader::GetMessage () const
Returns a RrcConnectionReconfiguration IE from the values in the class attributes.
Returns
A RrcConnectionReconfiguration, as defined in LteRrcSap
Definition at line 5616 of file lte-rrc-header.cc.
References ns3::LteRrcSap::RrcConnectionReconfiguration::haveMeasConfig, ns3::LteRrcSap::RrcConnectionReconfiguration::haveMobilityControlInfo, ns3::LteRrcSap::RrcConnectionReconfiguration::haveNonCriticalExtension, ns3::LteRrcSap::RrcConnectionReconfiguration::haveRadioResourceConfigDedicated, m_haveMeasConfig, m_haveMobilityControlInfo, m_haveNonCriticalExtension, m_haveRadioResourceConfigDedicated, m_measConfig, m_mobilityControlInfo, m_nonCriticalExtension, m_radioResourceConfigDedicated, m_rrcTransactionIdentifier, ns3::LteRrcSap::RrcConnectionReconfiguration::measConfig, ns3::LteRrcSap::RrcConnectionReconfiguration::mobilityControlInfo, ns3::LteRrcSap::RrcConnectionReconfiguration::nonCriticalExtension, ns3::LteRrcSap::RrcConnectionReconfiguration::radioResourceConfigDedicated, and ns3::LteRrcSap::RrcConnectionReconfiguration::rrcTransactionIdentifier.
Referenced by ns3::LteEnbRrcProtocolReal::DoDecodeHandoverCommand(), and ns3::LteUeRrcProtocolReal::DoReceivePdcpSdu().
GetMobilityControlInfo()
LteRrcSap::MobilityControlInfo ns3::RrcConnectionReconfigurationHeader::GetMobilityControlInfo ()
Getter for m_mobilityControlInfo.
Returns
m_mobilityControlInfo
Definition at line 5658 of file lte-rrc-header.cc.
References m_mobilityControlInfo.
Referenced by RrcConnectionReconfigurationTestCase::DoRun().
GetNonCriticalExtensionConfig()
LteRrcSap::NonCriticalExtensionConfiguration ns3::RrcConnectionReconfigurationHeader::GetNonCriticalExtensionConfig ()
Getter for m_nonCriticalExtension.
Returns
m_nonCriticalExtension
Definition at line 5682 of file lte-rrc-header.cc.
References m_nonCriticalExtension.
GetPhysicalConfigDedicated()
LteRrcSap::PhysicalConfigDedicated ns3::RrcConnectionReconfigurationHeader::GetPhysicalConfigDedicated () const
Gets m_radioResourceConfigDedicated.physicalConfigDedicated.
Returns
m_radioResourceConfigDedicated.physicalConfigDedicated
Definition at line 5712 of file lte-rrc-header.cc.
References m_radioResourceConfigDedicated, and ns3::LteRrcSap::RadioResourceConfigDedicated::physicalConfigDedicated.
GetRadioResourceConfigDedicated() [1/2]
LteRrcSap::RadioResourceConfigDedicated ns3::RrcConnectionReconfigurationHeader::GetRadioResourceConfigDedicated ()
Getter for m_radioResourceConfigDedicated.
Returns
m_radioResourceConfigDedicated
Definition at line 5670 of file lte-rrc-header.cc.
References m_radioResourceConfigDedicated.
Referenced by RrcConnectionReconfigurationTestCase::DoRun().
GetRadioResourceConfigDedicated() [2/2]
LteRrcSap::RadioResourceConfigDedicated ns3::RrcConnectionReconfigurationHeader::GetRadioResourceConfigDedicated () const
Getter for m_radioResourceConfigDedicated.
Returns
m_radioResourceConfigDedicated
GetRrcTransactionIdentifier()
uint8_t ns3::RrcConnectionReconfigurationHeader::GetRrcTransactionIdentifier () const
Getter for m_rrcTransactionIdentifier.
Returns
m_rrcTransactionIdentifier
Definition at line 5634 of file lte-rrc-header.cc.
References m_rrcTransactionIdentifier.
Referenced by RrcConnectionReconfigurationTestCase::DoRun().
GetSrbToAddModList()
std::list< LteRrcSap::SrbToAddMod > ns3::RrcConnectionReconfigurationHeader::GetSrbToAddModList () const
Gets m_radioResourceConfigDedicated.srbToAddModList.
Returns
m_radioResourceConfigDedicated.srbToAddModList
Definition at line 5694 of file lte-rrc-header.cc.
References m_radioResourceConfigDedicated, and ns3::LteRrcSap::RadioResourceConfigDedicated::srbToAddModList.
HavePhysicalConfigDedicated()
bool ns3::RrcConnectionReconfigurationHeader::HavePhysicalConfigDedicated () const
Gets m_radioResourceConfigDedicated.havePhysicalConfigDedicated.
Returns
m_radioResourceConfigDedicated.havePhysicalConfigDedicated
Definition at line 5688 of file lte-rrc-header.cc.
References ns3::LteRrcSap::RadioResourceConfigDedicated::havePhysicalConfigDedicated, and m_radioResourceConfigDedicated.
PreSerialize()
void ns3::RrcConnectionReconfigurationHeader::PreSerialize () const virtual
This function serializes class attributes to m_serializationResult local Buffer.
As ASN1 encoding produces a bitstream that does not have a fixed length, this function is needed to store the result, so its length can be retrieved with Header::GetSerializedSize() function. This method is pure virtual in this class (needs to be implemented in child classes) as the meaningful information elements are in the subclasses.
Reimplemented from ns3::RrcDlDcchMessage.
Definition at line 5094 of file lte-rrc-header.cc.
References ns3::RrcAsn1Header::BandwidthToEnum(), ns3::LteRrcSap::MobilityControlInfo::carrierBandwidth, ns3::LteRrcSap::MobilityControlInfo::carrierFreq, ns3::LteRrcSap::CarrierBandwidthEutra::dlBandwidth, ns3::LteRrcSap::CarrierFreqEutra::dlCarrierFreq, ns3::Asn1Header::FinalizeSerialization(), ns3::LteRrcSap::MobilityControlInfo::haveCarrierBandwidth, ns3::LteRrcSap::MobilityControlInfo::haveCarrierFreq, ns3::LteRrcSap::MobilityControlInfo::haveRachConfigDedicated, m_haveMeasConfig, m_haveMobilityControlInfo, m_haveNonCriticalExtension, m_haveRadioResourceConfigDedicated, m_measConfig, m_mobilityControlInfo, m_nonCriticalExtension, m_radioResourceConfigDedicated, m_rrcTransactionIdentifier, ns3::Asn1Header::m_serializationResult, MAX_EARFCN, ns3::LteRrcSap::MobilityControlInfo::newUeIdentity, ns3::LteRrcSap::MobilityControlInfo::rachConfigDedicated, ns3::LteRrcSap::MobilityControlInfo::radioResourceConfigCommon, ns3::LteRrcSap::RachConfigDedicated::raPrachMaskIndex, ns3::LteRrcSap::RachConfigDedicated::raPreambleIndex, ns3::Asn1Header::SerializeBitstring(), ns3::Asn1Header::SerializeChoice(), ns3::RrcDlDcchMessage::SerializeDlDcchMessage(), ns3::Asn1Header::SerializeEnum(), ns3::Asn1Header::SerializeInteger(), ns3::RrcAsn1Header::SerializeMeasConfig(), ns3::RrcAsn1Header::SerializeNonCriticalExtensionConfiguration(), ns3::RrcAsn1Header::SerializeRadioResourceConfigCommon(), ns3::RrcAsn1Header::SerializeRadioResourceConfigDedicated(), ns3::Asn1Header::SerializeSequence(), ns3::LteRrcSap::MobilityControlInfo::targetPhysCellId, ns3::LteRrcSap::CarrierBandwidthEutra::ulBandwidth, and ns3::LteRrcSap::CarrierFreqEutra::ulCarrierFreq.
Print()
void ns3::RrcConnectionReconfigurationHeader::Print (std::ostream & os) const virtual
This function prints the object, for debugging purposes.
Parameters
os The output stream to use (i.e. std::cout)
Reimplemented from ns3::RrcDlDcchMessage.
Definition at line 5363 of file lte-rrc-header.cc.
References ns3::LteRrcSap::MobilityControlInfo::carrierBandwidth, ns3::LteRrcSap::MobilityControlInfo::carrierFreq, ns3::LteRrcSap::CarrierBandwidthEutra::dlBandwidth, ns3::LteRrcSap::CarrierFreqEutra::dlCarrierFreq, ns3::LteRrcSap::ReportConfigEutra::EVENT, ns3::LteRrcSap::ReportConfigEutra::EVENT_A3, ns3::LteRrcSap::ReportConfigEutra::EVENT_A5, ns3::LteRrcSap::QuantityConfig::filterCoefficientRSRP, ns3::LteRrcSap::QuantityConfig::filterCoefficientRSRQ, ns3::LteRrcSap::MeasGapConfig::gapOffsetChoice, ns3::LteRrcSap::MeasGapConfig::gapOffsetValue, ns3::LteRrcSap::MobilityControlInfo::haveCarrierBandwidth, ns3::LteRrcSap::MobilityControlInfo::haveCarrierFreq, ns3::LteRrcSap::MeasConfig::haveMeasGapConfig, ns3::LteRrcSap::MeasConfig::haveQuantityConfig, ns3::LteRrcSap::MobilityControlInfo::haveRachConfigDedicated, ns3::LteRrcSap::MeasConfig::haveSmeasure, ns3::LteRrcSap::MeasConfig::haveSpeedStatePars, ns3::if(), m_haveMeasConfig, m_haveMobilityControlInfo, m_haveRadioResourceConfigDedicated, m_measConfig, m_mobilityControlInfo, m_radioResourceConfigDedicated, m_rrcTransactionIdentifier, ns3::LteRrcSap::MeasConfig::measGapConfig, ns3::LteRrcSap::MeasConfig::measIdToAddModList, ns3::LteRrcSap::MeasConfig::measIdToRemoveList, ns3::LteRrcSap::MeasConfig::measObjectToAddModList, ns3::LteRrcSap::MeasConfig::measObjectToRemoveList, ns3::LteRrcSap::SpeedStatePars::mobilityStateParameters, ns3::LteRrcSap::MobilityStateParameters::nCellChangeHigh, ns3::LteRrcSap::MobilityStateParameters::nCellChangeMedium, ns3::LteRrcSap::MobilityControlInfo::newUeIdentity, ns3::RrcAsn1Header::Print(), ns3::LteRrcSap::MeasConfig::quantityConfig, ns3::LteRrcSap::MobilityControlInfo::rachConfigDedicated, ns3::LteRrcSap::RachConfigDedicated::raPrachMaskIndex, ns3::LteRrcSap::RachConfigDedicated::raPreambleIndex, ns3::LteRrcSap::MeasConfig::reportConfigToAddModList, ns3::LteRrcSap::MeasConfig::reportConfigToRemoveList, ns3::LteRrcSap::SpeedStateScaleFactors::sfHigh, ns3::LteRrcSap::SpeedStateScaleFactors::sfMedium, ns3::LteRrcSap::MeasConfig::sMeasure, ns3::LteRrcSap::MeasConfig::speedStatePars, ns3::LteRrcSap::MobilityControlInfo::targetPhysCellId, ns3::LteRrcSap::MobilityStateParameters::tEvaluation, ns3::LteRrcSap::MobilityStateParameters::tHystNormal, ns3::LteRrcSap::SpeedStatePars::timeToTriggerSf, ns3::LteRrcSap::MeasGapConfig::type, ns3::LteRrcSap::SpeedStatePars::type, ns3::LteRrcSap::CarrierBandwidthEutra::ulBandwidth, and ns3::LteRrcSap::CarrierFreqEutra::ulCarrierFreq.
SetMessage()
void ns3::RrcConnectionReconfigurationHeader::SetMessage (LteRrcSap::RrcConnectionReconfiguration msg)
Receives a RrcConnectionReconfiguration IE and stores the contents into the class attributes.
Parameters
msg The information element to parse
Definition at line 5600 of file lte-rrc-header.cc.
References ns3::LteRrcSap::RrcConnectionReconfiguration::haveMeasConfig, ns3::LteRrcSap::RrcConnectionReconfiguration::haveMobilityControlInfo, ns3::LteRrcSap::RrcConnectionReconfiguration::haveNonCriticalExtension, ns3::LteRrcSap::RrcConnectionReconfiguration::haveRadioResourceConfigDedicated, m_haveMeasConfig, m_haveMobilityControlInfo, m_haveNonCriticalExtension, m_haveRadioResourceConfigDedicated, ns3::Asn1Header::m_isDataSerialized, m_measConfig, m_mobilityControlInfo, m_nonCriticalExtension, m_radioResourceConfigDedicated, m_rrcTransactionIdentifier, ns3::LteRrcSap::RrcConnectionReconfiguration::measConfig, ns3::LteRrcSap::RrcConnectionReconfiguration::mobilityControlInfo, ns3::LteRrcSap::RrcConnectionReconfiguration::nonCriticalExtension, ns3::LteRrcSap::RrcConnectionReconfiguration::radioResourceConfigDedicated, and ns3::LteRrcSap::RrcConnectionReconfiguration::rrcTransactionIdentifier.
Referenced by ns3::LteEnbRrcProtocolReal::DoEncodeHandoverCommand(), RrcConnectionReconfigurationTestCase::DoRun(), and ns3::LteEnbRrcProtocolReal::DoSendRrcConnectionReconfiguration().
Member Data Documentation
m_haveMeasConfig
bool ns3::RrcConnectionReconfigurationHeader::m_haveMeasConfig private
have measure config?
Definition at line 824 of file lte-rrc-header.h.
Referenced by Deserialize(), GetHaveMeasConfig(), GetMessage(), PreSerialize(), Print(), and SetMessage().
m_haveMobilityControlInfo
bool ns3::RrcConnectionReconfigurationHeader::m_haveMobilityControlInfo private
have mobility control info?
Definition at line 826 of file lte-rrc-header.h.
Referenced by Deserialize(), GetHaveMobilityControlInfo(), GetMessage(), PreSerialize(), Print(), and SetMessage().
m_haveNonCriticalExtension
bool ns3::RrcConnectionReconfigurationHeader::m_haveNonCriticalExtension private
Have critical extension.
Definition at line 830 of file lte-rrc-header.h.
Referenced by Deserialize(), GetHaveNonCriticalExtensionConfig(), GetMessage(), PreSerialize(), and SetMessage().
m_haveRadioResourceConfigDedicated
bool ns3::RrcConnectionReconfigurationHeader::m_haveRadioResourceConfigDedicated private
have radio resource config dedicated?
Definition at line 828 of file lte-rrc-header.h.
Referenced by Deserialize(), GetHaveRadioResourceConfigDedicated(), GetMessage(), PreSerialize(), Print(), and SetMessage().
m_measConfig
LteRrcSap::MeasConfig ns3::RrcConnectionReconfigurationHeader::m_measConfig private
the measure config
Definition at line 825 of file lte-rrc-header.h.
Referenced by Deserialize(), GetMeasConfig(), GetMessage(), PreSerialize(), Print(), and SetMessage().
m_mobilityControlInfo
LteRrcSap::MobilityControlInfo ns3::RrcConnectionReconfigurationHeader::m_mobilityControlInfo private
the modility control info
Definition at line 827 of file lte-rrc-header.h.
Referenced by Deserialize(), GetMessage(), GetMobilityControlInfo(), PreSerialize(), Print(), and SetMessage().
m_nonCriticalExtension
LteRrcSap::NonCriticalExtensionConfiguration ns3::RrcConnectionReconfigurationHeader::m_nonCriticalExtension private
the critical extension
Definition at line 831 of file lte-rrc-header.h.
Referenced by Deserialize(), GetMessage(), GetNonCriticalExtensionConfig(), PreSerialize(), and SetMessage().
m_radioResourceConfigDedicated
LteRrcSap::RadioResourceConfigDedicated ns3::RrcConnectionReconfigurationHeader::m_radioResourceConfigDedicated private
the radio resource config dedicated
Definition at line 829 of file lte-rrc-header.h.
Referenced by Deserialize(), GetDrbToAddModList(), GetDrbToReleaseList(), GetMessage(), GetPhysicalConfigDedicated(), GetRadioResourceConfigDedicated(), GetSrbToAddModList(), HavePhysicalConfigDedicated(), PreSerialize(), Print(), and SetMessage().
m_rrcTransactionIdentifier
uint8_t ns3::RrcConnectionReconfigurationHeader::m_rrcTransactionIdentifier private
RRC transaction identifier.
Definition at line 823 of file lte-rrc-header.h.
Referenced by Deserialize(), GetMessage(), GetRrcTransactionIdentifier(), PreSerialize(), Print(), and SetMessage().
The documentation for this class was generated from the following files:
src/lte/model/lte-rrc-header.h
src/lte/model/lte-rrc-header.cc