ns-3: ns3::TcpSeqErrorModel Class Reference
ns3::TcpSeqErrorModel Class Reference
Internet » internet module tests | Test suites
An error model TCP aware: it drops the sequence number declared.
#include "tcp-error-model.h"
Public Member Functions
TcpSeqErrorModel ()
void AddSeqToKill (const SequenceNumber32 &seq)
Add the sequence number to the list of segments to be killed.
Public Member Functions inherited from ns3::TcpGeneralErrorModel
TcpGeneralErrorModel ()
void SetDropCallback (Callback< void, const Ipv4Header &, const TcpHeader &, Ptr< const Packet > > cb)
Set the drop callback.
Public Member Functions inherited from ns3::ErrorModel
ErrorModel ()
virtual ~ErrorModel ()
void Disable (void)
Disable the error model.
void Enable (void)
Enable the error model.
bool IsCorrupt (Ptr< Packet > pkt)
Note: Depending on the error model, this function may or may not alter the contents of the packet upon returning true.
bool IsEnabled (void) const
void Reset (void)
Reset any state associated with the error model.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpGeneralErrorModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ErrorModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual bool ShouldDrop (const Ipv4Header &ipHeader, const TcpHeader &tcpHeader, uint32_t packetSize)
Check if the packet should be dropped.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes
std::list< SequenceNumber32 > m_seqToKill
List of the sequence numbers to be dropped.
Private Member Functions
virtual void DoReset (void)
Re-initialize any state.
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
An error model TCP aware: it drops the sequence number declared.
See also
AddSeqToKill
Definition at line 82 of file tcp-error-model.h.
Constructor & Destructor Documentation
TcpSeqErrorModel()
ns3::TcpSeqErrorModel::TcpSeqErrorModel () inline
Definition at line 90 of file tcp-error-model.h.
Member Function Documentation
AddSeqToKill()
void ns3::TcpSeqErrorModel::AddSeqToKill (const SequenceNumber32 & seq) inline
Add the sequence number to the list of segments to be killed.
Calling x times this function indicates that you want to kill the segment x times.
Parameters
seq sequence number to be killed
Definition at line 100 of file tcp-error-model.h.
References m_seqToKill.
Referenced by TcpAdvWindowOnLossTest::CreateReceiverErrorModel(), TcpBytesInFlightTest::CreateReceiverErrorModel(), ns3::TcpCloseWithLossTestCase::CreateReceiverErrorModel(), TcpFastRetrTest::CreateReceiverErrorModel(), TcpRateLinuxWithSocketsTest::CreateReceiverErrorModel(), TcpSsThreshRtoTest::CreateReceiverErrorModel(), TcpTimeRtoTest::CreateReceiverErrorModel(), and TcpRttEstimationWithLossTest::CreateReceiverErrorModel().
DoReset()
void ns3::TcpSeqErrorModel::DoReset (void) private virtual
Re-initialize any state.
Implements ns3::ErrorModel.
Definition at line 109 of file tcp-error-model.cc.
References m_seqToKill.
GetTypeId()
TypeId ns3::TcpSeqErrorModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 75 of file tcp-error-model.cc.
References ns3::TypeId::SetParent().
ShouldDrop()
bool ns3::TcpSeqErrorModel::ShouldDrop (const Ipv4Header & ipHeader, const TcpHeader & tcpHeader, uint32_t packetSize) protected virtual
Check if the packet should be dropped.
Parameters
ipHeader The packet IPv4 header.
tcpHeader The packet TCP header.
packetSize The packet size.
Returns
True if the packet should be dropped.
Implements ns3::TcpGeneralErrorModel.
Definition at line 85 of file tcp-error-model.cc.
References ns3::TcpHeader::GetSequenceNumber(), m_seqToKill, NS_LOG_FUNCTION, NS_LOG_INFO, and packetSize.
Member Data Documentation
m_seqToKill
std::list<SequenceNumber32> ns3::TcpSeqErrorModel::m_seqToKill protected
List of the sequence numbers to be dropped.
Definition at line 110 of file tcp-error-model.h.
Referenced by AddSeqToKill(), DoReset(), and ShouldDrop().
The documentation for this class was generated from the following files:
src/internet/test/tcp-error-model.h
src/internet/test/tcp-error-model.cc