ns-3: ns3::V4TraceRoute Class Reference
ns3::V4TraceRoute Class Reference
Internet Applications » V4Traceroute
Traceroute application sends one ICMP ECHO request with TTL=1, and after receiving an ICMP TIME EXCEED reply, it increases the TTL and repeat the process to reveal all the intermediate hops to the destination.
#include "v4traceroute.h"
Public Member Functions
V4TraceRoute ()
virtual ~V4TraceRoute ()
void Print (Ptr< OutputStreamWrapper > stream)
Prints the application traced routes into a given OutputStream.
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual void DoDispose (void)
Destructor implementation.
uint32_t GetApplicationId (void) const
Return the application ID in the node.
void HandleWaitReplyTimeout ()
Triggers an action if an ICMP TIME EXCEED have not being received in the time defined by StartWaitReplyTimer.
void Receive (Ptr< Socket > socket)
Receive an ICMP Echo.
void Send ()
Send one (ICMP ECHO) to the destination.
virtual void StartApplication (void)
Application specific startup code.
void StartWaitReplyTimer ()
Starts a timer after sending an ICMP ECHO.
virtual void StopApplication (void)
Application specific shutdown code.
Private Attributes
Time m_interval
Wait interval seconds between sending each packet.
uint16_t m_maxProbes
The maximum number of probe packets per hop.
uint32_t m_maxTtl
The maximium Ttl (Max number of hops to trace)
EventId m_next
Next packet will be sent.
uint32_t m_probeCount
The Current probe value.
Ipv4Address m_remote
Remote address.
std::map< uint16_t, Time > m_sent
All sent but not answered packets. Map icmp seqno -> when sent.
uint16_t m_seq
ICMP ECHO sequence number.
uint32_t m_size
Specifies the number of data bytes to be sent.
Ptr< Socket > m_socket
The socket we send packets from.
Time m_started
Start time to report total ping time.
uint16_t m_ttl
The current TTL value.
bool m_verbose
produce traceroute style output if true
Time m_waitIcmpReplyTimeout
The wait time until the response is considered lost.
EventId m_waitIcmpReplyTimer
The timer used to wait for the probes ICMP replies.
std::ostringstream os
Stream of characters used for printing the traceroute results.
std::ostringstream osRoute
Stream of characters used for printing a single route.
Ptr< OutputStreamWrapper > printStream
Stream of the traceroute used for the output file.
std::ostringstream routeIpv4
The Ipv4 address of the latest hop found.
Additional Inherited Members
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Protected Member Functions inherited from ns3::Application
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Traceroute application sends one ICMP ECHO request with TTL=1, and after receiving an ICMP TIME EXCEED reply, it increases the TTL and repeat the process to reveal all the intermediate hops to the destination.
Definition at line 50 of file v4traceroute.h.
Constructor & Destructor Documentation
V4TraceRoute()
ns3::V4TraceRoute::V4TraceRoute ()
Definition at line 88 of file v4traceroute.cc.
References osRoute, and routeIpv4.
~V4TraceRoute()
ns3::V4TraceRoute::~V4TraceRoute () virtual
Definition at line 105 of file v4traceroute.cc.
Member Function Documentation
DoDispose()
void ns3::V4TraceRoute::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Application.
Definition at line 188 of file v4traceroute.cc.
References ns3::Application::DoDispose(), ns3::EventId::IsRunning(), m_next, m_socket, m_waitIcmpReplyTimer, NS_LOG_FUNCTION, and StopApplication().
GetApplicationId()
uint32_t ns3::V4TraceRoute::GetApplicationId (void) const private
Return the application ID in the node.
Returns
the application id
Definition at line 203 of file v4traceroute.cc.
References ns3::Node::GetApplication(), ns3::Node::GetNApplications(), ns3::Application::GetNode(), NS_ASSERT_MSG(), and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::V4TraceRoute::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 47 of file v4traceroute.cc.
References m_interval, m_maxProbes, m_maxTtl, m_remote, m_size, m_verbose, m_waitIcmpReplyTimeout, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeIpv4AddressAccessor(), ns3::MakeIpv4AddressChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeUintegerAccessor(), ns3::Seconds(), and ns3::TypeId::SetParent().
HandleWaitReplyTimeout()
void ns3::V4TraceRoute::HandleWaitReplyTimeout () private
Triggers an action if an ICMP TIME EXCEED have not being received in the time defined by StartWaitReplyTimer.
Definition at line 440 of file v4traceroute.cc.
References ns3::OutputStreamWrapper::GetStream(), m_interval, m_maxProbes, m_maxTtl, m_next, m_probeCount, m_ttl, m_verbose, NS_LOG_UNCOND, osRoute, printStream, routeIpv4, ns3::Simulator::Schedule(), and StartWaitReplyTimer().
Referenced by StartWaitReplyTimer().
Print()
void ns3::V4TraceRoute::Print (Ptr< OutputStreamWrapper > stream)
Prints the application traced routes into a given OutputStream.
Definition at line 112 of file v4traceroute.cc.
References printStream.
Receive()
void ns3::V4TraceRoute::Receive (Ptr< Socket > socket) private
Receive an ICMP Echo.
Parameters
socket the receiving socket
This function is called by lower layers through a callback.
Definition at line 219 of file v4traceroute.cc.
References ns3::EventId::Cancel(), ns3::InetSocketAddress::ConvertFrom(), data, ns3::Icmpv4TimeExceeded::GetData(), ns3::Icmpv4Echo::GetData(), ns3::Icmpv4Echo::GetDataSize(), ns3::Icmpv4Echo::GetIdentifier(), ns3::InetSocketAddress::GetIpv4(), ns3::Time::GetMilliSeconds(), ns3::InetSocketAddress::GetPort(), ns3::Ipv4Header::GetProtocol(), ns3::Socket::GetRxAvailable(), ns3::Icmpv4Echo::GetSequenceNumber(), ns3::Packet::GetSize(), ns3::OutputStreamWrapper::GetStream(), ns3::Icmpv4Header::GetType(), ns3::Icmpv4Header::ICMPV4_ECHO_REPLY, ns3::Icmpv4Header::ICMPV4_TIME_EXCEEDED, ns3::InetSocketAddress::IsMatchingType(), m_interval, m_maxProbes, m_maxTtl, m_next, m_probeCount, m_remote, m_sent, m_size, m_socket, m_ttl, m_verbose, m_waitIcmpReplyTimer, ns3::Simulator::Now(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_UNCOND, osRoute, printStream, ns3::Icmpv4L4Protocol::PROT_NUMBER, ns3::Socket::RecvFrom(), ns3::Packet::RemoveHeader(), routeIpv4, ns3::Simulator::Schedule(), StartWaitReplyTimer(), and StopApplication().
Referenced by StartApplication().
Send()
void ns3::V4TraceRoute::Send () private
Send one (ICMP ECHO) to the destination.
Definition at line 366 of file v4traceroute.cc.
References ns3::Packet::AddHeader(), ns3::Node::ChecksumEnabled(), data, ns3::Icmpv4Header::EnableChecksum(), ns3::Icmpv4Header::ICMPV4_ECHO, m_maxProbes, m_probeCount, m_remote, m_sent, m_seq, m_size, m_socket, m_ttl, ns3::Simulator::Now(), NS_ASSERT, NS_LOG_INFO, ns3::Socket::SendTo(), ns3::Icmpv4Header::SetCode(), ns3::Icmpv4Echo::SetData(), ns3::Icmpv4Echo::SetIdentifier(), ns3::Socket::SetIpTtl(), ns3::Icmpv4Echo::SetSequenceNumber(), and ns3::Icmpv4Header::SetType().
Referenced by StartWaitReplyTimer().
StartApplication()
void ns3::V4TraceRoute::StartApplication (void) private virtual
Application specific startup code.
The StartApplication method is called at the start time specified by Start This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 118 of file v4traceroute.cc.
References ns3::Socket::Bind(), ns3::Socket::CreateSocket(), ns3::Ipv4Address::GetAny(), ns3::Application::GetNode(), ns3::OutputStreamWrapper::GetStream(), ns3::TypeId::LookupByName(), m_maxTtl, m_next, m_remote, m_size, m_socket, m_started, m_verbose, ns3::MakeCallback(), ns3::Simulator::Now(), NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC(), NS_LOG_UNCOND, printStream, ns3::Icmpv4L4Protocol::PROT_NUMBER, Receive(), ns3::Simulator::ScheduleNow(), ns3::ObjectBase::SetAttribute(), ns3::Socket::SetRecvCallback(), and StartWaitReplyTimer().
StartWaitReplyTimer()
void ns3::V4TraceRoute::StartWaitReplyTimer () private
Starts a timer after sending an ICMP ECHO.
Definition at line 424 of file v4traceroute.cc.
References HandleWaitReplyTimeout(), ns3::EventId::IsRunning(), m_waitIcmpReplyTimeout, m_waitIcmpReplyTimer, ns3::Simulator::Now(), NS_LOG_FUNCTION, NS_LOG_LOGIC(), ns3::Simulator::Schedule(), and Send().
Referenced by HandleWaitReplyTimeout(), Receive(), and StartApplication().
StopApplication()
void ns3::V4TraceRoute::StopApplication (void) private virtual
Application specific shutdown code.
The StopApplication method is called at the stop time specified by Stop This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 157 of file v4traceroute.cc.
References ns3::EventId::Cancel(), ns3::Socket::Close(), ns3::OutputStreamWrapper::GetStream(), ns3::EventId::IsRunning(), m_next, m_socket, m_verbose, m_waitIcmpReplyTimer, NS_LOG_FUNCTION, NS_LOG_UNCOND, and printStream.
Referenced by DoDispose(), and Receive().
Member Data Documentation
m_interval
Time ns3::V4TraceRoute::m_interval private
Wait interval seconds between sending each packet.
Definition at line 97 of file v4traceroute.h.
Referenced by GetTypeId(), HandleWaitReplyTimeout(), and Receive().
m_maxProbes
uint16_t ns3::V4TraceRoute::m_maxProbes private
The maximum number of probe packets per hop.
Definition at line 117 of file v4traceroute.h.
Referenced by GetTypeId(), HandleWaitReplyTimeout(), Receive(), and Send().
m_maxTtl
uint32_t ns3::V4TraceRoute::m_maxTtl private
The maximium Ttl (Max number of hops to trace)
Definition at line 121 of file v4traceroute.h.
Referenced by GetTypeId(), HandleWaitReplyTimeout(), Receive(), and StartApplication().
m_next
EventId ns3::V4TraceRoute::m_next private
Next packet will be sent.
Definition at line 113 of file v4traceroute.h.
Referenced by DoDispose(), HandleWaitReplyTimeout(), Receive(), StartApplication(), and StopApplication().
m_probeCount
uint32_t ns3::V4TraceRoute::m_probeCount private
The Current probe value.
Definition at line 115 of file v4traceroute.h.
Referenced by HandleWaitReplyTimeout(), Receive(), and Send().
m_remote
Ipv4Address ns3::V4TraceRoute::m_remote private
Remote address.
Definition at line 94 of file v4traceroute.h.
Referenced by GetTypeId(), Receive(), Send(), and StartApplication().
m_sent
std::map<uint16_t, Time> ns3::V4TraceRoute::m_sent private
All sent but not answered packets. Map icmp seqno -> when sent.
Definition at line 127 of file v4traceroute.h.
Referenced by Receive(), and Send().
m_seq
uint16_t ns3::V4TraceRoute::m_seq private
ICMP ECHO sequence number.
Definition at line 107 of file v4traceroute.h.
Referenced by Send().
m_size
uint32_t ns3::V4TraceRoute::m_size private
Specifies the number of data bytes to be sent.
The default is 56, which translates into 64 ICMP data bytes when combined with the 8 bytes of ICMP header data.
Definition at line 103 of file v4traceroute.h.
Referenced by GetTypeId(), Receive(), Send(), and StartApplication().
m_socket
Ptr<Socket> ns3::V4TraceRoute::m_socket private
The socket we send packets from.
Definition at line 105 of file v4traceroute.h.
Referenced by DoDispose(), Receive(), Send(), StartApplication(), and StopApplication().
m_started
Time ns3::V4TraceRoute::m_started private
Start time to report total ping time.
Definition at line 111 of file v4traceroute.h.
Referenced by StartApplication().
m_ttl
uint16_t ns3::V4TraceRoute::m_ttl private
The current TTL value.
Definition at line 119 of file v4traceroute.h.
Referenced by HandleWaitReplyTimeout(), Receive(), and Send().
m_verbose
bool ns3::V4TraceRoute::m_verbose private
produce traceroute style output if true
Definition at line 109 of file v4traceroute.h.
Referenced by GetTypeId(), HandleWaitReplyTimeout(), Receive(), StartApplication(), and StopApplication().
m_waitIcmpReplyTimeout
Time ns3::V4TraceRoute::m_waitIcmpReplyTimeout private
The wait time until the response is considered lost.
Definition at line 123 of file v4traceroute.h.
Referenced by GetTypeId(), and StartWaitReplyTimer().
m_waitIcmpReplyTimer
EventId ns3::V4TraceRoute::m_waitIcmpReplyTimer private
The timer used to wait for the probes ICMP replies.
Definition at line 125 of file v4traceroute.h.
Referenced by DoDispose(), Receive(), StartWaitReplyTimer(), and StopApplication().
os
std::ostringstream ns3::V4TraceRoute::os private
Stream of characters used for printing the traceroute results.
Definition at line 129 of file v4traceroute.h.
osRoute
std::ostringstream ns3::V4TraceRoute::osRoute private
Stream of characters used for printing a single route.
Definition at line 131 of file v4traceroute.h.
Referenced by V4TraceRoute(), HandleWaitReplyTimeout(), and Receive().
printStream
Ptr<OutputStreamWrapper> ns3::V4TraceRoute::printStream private
Stream of the traceroute used for the output file.
Definition at line 135 of file v4traceroute.h.
Referenced by HandleWaitReplyTimeout(), Print(), Receive(), StartApplication(), and StopApplication().
routeIpv4
std::ostringstream ns3::V4TraceRoute::routeIpv4 private
The Ipv4 address of the latest hop found.
Definition at line 133 of file v4traceroute.h.
Referenced by V4TraceRoute(), HandleWaitReplyTimeout(), and Receive().
The documentation for this class was generated from the following files:
src/internet-apps/model/v4traceroute.h
src/internet-apps/model/v4traceroute.cc