ns-3: ns3::EpcX2Header Class Reference
ns3::EpcX2Header Class Reference
#include "epc-x2-header.h"
Public Types
enum ProcedureCode_t {
HandoverPreparation = 0, LoadIndication = 2, SnStatusTransfer = 4, UeContextRelease = 5,
ResourceStatusReporting = 10
}
Procedure code enumeration.
enum TypeOfMessage_t { InitiatingMessage = 0, SuccessfulOutcome = 1, UnsuccessfulOutcome = 2 }
Type of message enumeration.
Public Member Functions
EpcX2Header ()
virtual ~EpcX2Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint8_t GetMessageType () const
Get message type function.
uint8_t GetProcedureCode () const
Get procedure code function.
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetLengthOfIes (uint32_t lengthOfIes)
Set length of IEs function.
void SetMessageType (uint8_t messageType)
Set message type function.
void SetNumberOfIes (uint32_t numberOfIes)
Set number of IEs function.
void SetProcedureCode (uint8_t procedureCode)
Set procedure code function.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint32_t m_lengthOfIes
length of IEs
uint8_t m_messageType
message type
uint32_t m_numberOfIes
number of IEs
uint8_t m_procedureCode
procedure code
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 33 of file epc-x2-header.h.
Member Enumeration Documentation
ProcedureCode_t
enum ns3::EpcX2Header::ProcedureCode_t
Procedure code enumeration.
Enumerator
HandoverPreparation
LoadIndication
SnStatusTransfer
UeContextRelease
ResourceStatusReporting
Definition at line 86 of file epc-x2-header.h.
TypeOfMessage_t
enum ns3::EpcX2Header::TypeOfMessage_t
Type of message enumeration.
Enumerator
InitiatingMessage
SuccessfulOutcome
UnsuccessfulOutcome
Definition at line 95 of file epc-x2-header.h.
Constructor & Destructor Documentation
EpcX2Header()
ns3::EpcX2Header::EpcX2Header ()
Definition at line 31 of file epc-x2-header.cc.
~EpcX2Header()
ns3::EpcX2Header::~EpcX2Header () virtual
Definition at line 39 of file epc-x2-header.cc.
References m_lengthOfIes, m_messageType, m_numberOfIes, and m_procedureCode.
Member Function Documentation
Deserialize()
uint32_t ns3::EpcX2Header::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 85 of file epc-x2-header.cc.
References GetSerializedSize(), m_lengthOfIes, m_messageType, m_numberOfIes, m_procedureCode, ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetInstanceTypeId()
TypeId ns3::EpcX2Header::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 59 of file epc-x2-header.cc.
References GetTypeId().
GetMessageType()
uint8_t ns3::EpcX2Header::GetMessageType () const
Get message type function.
Returns
the message type
Definition at line 110 of file epc-x2-header.cc.
References m_messageType.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
GetProcedureCode()
uint8_t ns3::EpcX2Header::GetProcedureCode () const
Get procedure code function.
Returns
the procedure code
Definition at line 122 of file epc-x2-header.cc.
References m_procedureCode.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
GetSerializedSize()
uint32_t ns3::EpcX2Header::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 65 of file epc-x2-header.cc.
Referenced by Deserialize().
GetTypeId()
TypeId ns3::EpcX2Header::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 48 of file epc-x2-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::EpcX2Header::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 101 of file epc-x2-header.cc.
References m_lengthOfIes, m_messageType, m_numberOfIes, and m_procedureCode.
Serialize()
void ns3::EpcX2Header::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 71 of file epc-x2-header.cc.
References m_lengthOfIes, m_messageType, m_numberOfIes, m_procedureCode, visualizer.core::start(), ns3::Buffer::Iterator::WriteHtonU16(), and ns3::Buffer::Iterator::WriteU8().
SetLengthOfIes()
void ns3::EpcX2Header::SetLengthOfIes (uint32_t lengthOfIes)
Set length of IEs function.
Parameters
lengthOfIes the length of IEs
Definition at line 135 of file epc-x2-header.cc.
References m_lengthOfIes.
Referenced by ns3::EpcX2::DoSendHandoverPreparationFailure(), ns3::EpcX2::DoSendHandoverRequest(), ns3::EpcX2::DoSendHandoverRequestAck(), ns3::EpcX2::DoSendLoadInformation(), ns3::EpcX2::DoSendResourceStatusUpdate(), ns3::EpcX2::DoSendSnStatusTransfer(), and ns3::EpcX2::DoSendUeContextRelease().
SetMessageType()
void ns3::EpcX2Header::SetMessageType (uint8_t messageType)
Set message type function.
Parameters
messageType the message type
Definition at line 116 of file epc-x2-header.cc.
References m_messageType.
Referenced by ns3::EpcX2::DoSendHandoverPreparationFailure(), ns3::EpcX2::DoSendHandoverRequest(), ns3::EpcX2::DoSendHandoverRequestAck(), ns3::EpcX2::DoSendLoadInformation(), ns3::EpcX2::DoSendResourceStatusUpdate(), ns3::EpcX2::DoSendSnStatusTransfer(), and ns3::EpcX2::DoSendUeContextRelease().
SetNumberOfIes()
void ns3::EpcX2Header::SetNumberOfIes (uint32_t numberOfIes)
Set number of IEs function.
Parameters
numberOfIes the number of IEs
Definition at line 141 of file epc-x2-header.cc.
References m_numberOfIes.
Referenced by ns3::EpcX2::DoSendHandoverPreparationFailure(), ns3::EpcX2::DoSendHandoverRequest(), ns3::EpcX2::DoSendHandoverRequestAck(), ns3::EpcX2::DoSendLoadInformation(), ns3::EpcX2::DoSendResourceStatusUpdate(), ns3::EpcX2::DoSendSnStatusTransfer(), and ns3::EpcX2::DoSendUeContextRelease().
SetProcedureCode()
void ns3::EpcX2Header::SetProcedureCode (uint8_t procedureCode)
Set procedure code function.
Parameters
procedureCode the procedure code
Definition at line 128 of file epc-x2-header.cc.
References m_procedureCode.
Referenced by ns3::EpcX2::DoSendHandoverPreparationFailure(), ns3::EpcX2::DoSendHandoverRequest(), ns3::EpcX2::DoSendHandoverRequestAck(), ns3::EpcX2::DoSendLoadInformation(), ns3::EpcX2::DoSendResourceStatusUpdate(), ns3::EpcX2::DoSendSnStatusTransfer(), and ns3::EpcX2::DoSendUeContextRelease().
Member Data Documentation
m_lengthOfIes
uint32_t ns3::EpcX2Header::m_lengthOfIes private
length of IEs
Definition at line 105 of file epc-x2-header.h.
Referenced by ~EpcX2Header(), Deserialize(), Print(), Serialize(), and SetLengthOfIes().
m_messageType
uint8_t ns3::EpcX2Header::m_messageType private
message type
Definition at line 102 of file epc-x2-header.h.
Referenced by ~EpcX2Header(), Deserialize(), GetMessageType(), Print(), Serialize(), and SetMessageType().
m_numberOfIes
uint32_t ns3::EpcX2Header::m_numberOfIes private
number of IEs
Definition at line 106 of file epc-x2-header.h.
Referenced by ~EpcX2Header(), Deserialize(), Print(), Serialize(), and SetNumberOfIes().
m_procedureCode
uint8_t ns3::EpcX2Header::m_procedureCode private
procedure code
Definition at line 103 of file epc-x2-header.h.
Referenced by ~EpcX2Header(), Deserialize(), GetProcedureCode(), Print(), Serialize(), and SetProcedureCode().
The documentation for this class was generated from the following files:
src/lte/model/epc-x2-header.h
src/lte/model/epc-x2-header.cc