ns-3: TcpRateLinuxWithBufferTest Class Reference
TcpRateLinuxWithBufferTest Class Reference
Test suites
The TcpRateLinuxWithBufferTest tests rate sample functionality with arbitary SACK scenario. Check the value of delivered against a home-made guess.
Public Member Functions
TcpRateLinuxWithBufferTest (uint32_t segmentSize, std::string desc)
Constructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
virtual void DoTeardown (void)
Implementation to do any local setup required for this TestCase.
virtual void RateSampleUpdatedTrace (const TcpRateLinux::TcpRateSample &sample)
Track the rate sample value of TcpRateLinux.
virtual void RateUpdatedTrace (const TcpRateLinux::TcpRateConnection &rate)
Track the rate value of TcpRateLinux.
void TestWithSackBlocks ()
Test with arbitary SACK scenario.
void TestWithStraightAcks ()
Test with acks without drop.
Private Attributes
uint32_t m_expectedAckedSacked {0}
Amount of expected acked sacked data.
uint32_t m_expectedDelivered {0}
Amount of expected delivered data.
Ptr< TcpRateOps > m_rateOps
Rate operations.
uint32_t m_segmentSize
Segment size.
TcpTxBuffer m_txBuf
Tcp Tx buffer.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
The TcpRateLinuxWithBufferTest tests rate sample functionality with arbitary SACK scenario. Check the value of delivered against a home-made guess.
Definition at line 398 of file tcp-rate-ops-test.cc.
Constructor & Destructor Documentation
TcpRateLinuxWithBufferTest()
TcpRateLinuxWithBufferTest::TcpRateLinuxWithBufferTest (uint32_t segmentSize, std::string desc)
Constructor.
Parameters
segmentSize Segment size to use.
desc Description.
Definition at line 437 of file tcp-rate-ops-test.cc.
References m_rateOps, ns3::MakeCallback(), RateSampleUpdatedTrace(), RateUpdatedTrace(), and ns3::ObjectBase::TraceConnectWithoutContext().
Member Function Documentation
DoRun()
void TcpRateLinuxWithBufferTest::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 450 of file tcp-rate-ops-test.cc.
References ns3::Seconds(), and TestWithSackBlocks().
DoTeardown()
void TcpRateLinuxWithBufferTest::DoTeardown (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test teardown
Reimplemented from ns3::TestCase.
Definition at line 534 of file tcp-rate-ops-test.cc.
RateSampleUpdatedTrace()
void TcpRateLinuxWithBufferTest::RateSampleUpdatedTrace (const TcpRateLinux::TcpRateSample & sample) private virtual
Track the rate sample value of TcpRateLinux.
Parameters
sample updated value of TcpRateSample.
Definition at line 465 of file tcp-rate-ops-test.cc.
References m_expectedAckedSacked, NS_LOG_DEBUG, and NS_TEST_ASSERT_MSG_EQ.
Referenced by TcpRateLinuxWithBufferTest().
RateUpdatedTrace()
void TcpRateLinuxWithBufferTest::RateUpdatedTrace (const TcpRateLinux::TcpRateConnection & rate) private virtual
Track the rate value of TcpRateLinux.
Parameters
rate updated value of TcpRate.
Definition at line 458 of file tcp-rate-ops-test.cc.
References m_expectedDelivered, NS_LOG_DEBUG, and NS_TEST_ASSERT_MSG_EQ.
Referenced by TcpRateLinuxWithBufferTest().
TestWithSackBlocks()
void TcpRateLinuxWithBufferTest::TestWithSackBlocks () private
Test with arbitary SACK scenario.
Definition at line 472 of file tcp-rate-ops-test.cc.
References ns3::TcpTxBuffer::Add(), ns3::TcpOptionSack::AddSackBlock(), ns3::TcpTxBuffer::BytesInFlight(), ns3::TcpTxBuffer::CopyFromSequence(), ns3::TcpTxBuffer::DiscardUpTo(), ns3::TcpRateOps::GenerateSample(), ns3::TcpOptionSack::GetSackList(), m_expectedAckedSacked, m_expectedDelivered, m_rateOps, m_segmentSize, m_txBuf, ns3::MakeCallback(), ns3::Seconds(), ns3::TcpTxBuffer::SetDupAckThresh(), ns3::TcpTxBuffer::SetHeadSequence(), ns3::TcpTxBuffer::SetSegmentSize(), ns3::TcpRateOps::SkbSent(), and ns3::TcpTxBuffer::Update().
Referenced by DoRun().
TestWithStraightAcks()
void TcpRateLinuxWithBufferTest::TestWithStraightAcks () private
Test with acks without drop.
Member Data Documentation
m_expectedAckedSacked
uint32_t TcpRateLinuxWithBufferTest::m_expectedAckedSacked {0} private
Amount of expected acked sacked data.
Definition at line 431 of file tcp-rate-ops-test.cc.
Referenced by RateSampleUpdatedTrace(), and TestWithSackBlocks().
m_expectedDelivered
uint32_t TcpRateLinuxWithBufferTest::m_expectedDelivered {0} private
Amount of expected delivered data.
Definition at line 430 of file tcp-rate-ops-test.cc.
Referenced by RateUpdatedTrace(), and TestWithSackBlocks().
m_rateOps
Ptr<TcpRateOps> TcpRateLinuxWithBufferTest::m_rateOps private
Rate operations.
Definition at line 434 of file tcp-rate-ops-test.cc.
Referenced by TcpRateLinuxWithBufferTest(), and TestWithSackBlocks().
m_segmentSize
uint32_t TcpRateLinuxWithBufferTest::m_segmentSize private
Segment size.
Definition at line 432 of file tcp-rate-ops-test.cc.
Referenced by TestWithSackBlocks().
m_txBuf
TcpTxBuffer TcpRateLinuxWithBufferTest::m_txBuf private
Tcp Tx buffer.
Definition at line 433 of file tcp-rate-ops-test.cc.
Referenced by TestWithSackBlocks().
The documentation for this class was generated from the following file:
src/internet/test/tcp-rate-ops-test.cc