ns-3: ns3::YansWifiChannelHelper Class Reference
ns3::YansWifiChannelHelper Class Reference
manage and create wifi channel objects for the YANS model.
#include "yans-wifi-helper.h"
Public Member Functions
YansWifiChannelHelper ()
Create a channel helper without any parameter set.
void AddPropagationLoss (std::string name, std::string n0="", const AttributeValue &v0=EmptyAttributeValue(), std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue(), std::string n6="", const AttributeValue &v6=EmptyAttributeValue(), std::string n7="", const AttributeValue &v7=EmptyAttributeValue())
int64_t AssignStreams (Ptr< YansWifiChannel > c, int64_t stream)
Assign a fixed random variable stream number to the random variables used by the channel.
Ptr< YansWifiChannel > Create (void) const
void SetPropagationDelay (std::string name, std::string n0="", const AttributeValue &v0=EmptyAttributeValue(), std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue(), std::string n6="", const AttributeValue &v6=EmptyAttributeValue(), std::string n7="", const AttributeValue &v7=EmptyAttributeValue())
Static Public Member Functions
static YansWifiChannelHelper Default (void)
Create a channel helper in a default working state.
Private Attributes
ObjectFactory m_propagationDelay
propagation delay model
std::vector< ObjectFactory > m_propagationLoss
vector of propagation loss models
Detailed Description
manage and create wifi channel objects for the YANS model.
The intent of this class is to make it easy to create a channel object which implements the YANS channel model. The YANS channel model is described in "Yet Another Network Simulator", http://cutebugs.net/files/wns2-yans.pdf
Definition at line 36 of file yans-wifi-helper.h.
Constructor & Destructor Documentation
YansWifiChannelHelper()
ns3::YansWifiChannelHelper::YansWifiChannelHelper ()
Create a channel helper without any parameter set.
The user must set them all to be able to call Create later.
Definition at line 36 of file yans-wifi-helper.cc.
Member Function Documentation
AddPropagationLoss()
void ns3::YansWifiChannelHelper::AddPropagationLoss (std::string name, std::string n0 = "", const AttributeValue & v0 = EmptyAttributeValue (), std::string n1 = "", const AttributeValue & v1 = EmptyAttributeValue (), std::string n2 = "", const AttributeValue & v2 = EmptyAttributeValue (), std::string n3 = "", const AttributeValue & v3 = EmptyAttributeValue (), std::string n4 = "", const AttributeValue & v4 = EmptyAttributeValue (), std::string n5 = "", const AttributeValue & v5 = EmptyAttributeValue (), std::string n6 = "", const AttributeValue & v6 = EmptyAttributeValue (), std::string n7 = "", const AttributeValue & v7 = EmptyAttributeValue ())
Parameters
name the name of the model to add
n0 the name of the attribute to set
v0 the value of the attribute to set
n1 the name of the attribute to set
v1 the value of the attribute to set
n2 the name of the attribute to set
v2 the value of the attribute to set
n3 the name of the attribute to set
v3 the value of the attribute to set
n4 the name of the attribute to set
v4 the value of the attribute to set
n5 the name of the attribute to set
v5 the value of the attribute to set
n6 the name of the attribute to set
v6 the value of the attribute to set
n7 the name of the attribute to set
v7 the value of the attribute to set
Add a propagation loss model to the set of currently-configured loss models. This method is additive to allow you to construct complex propagation loss models such as a log distance + Jakes model, etc.
The order in which PropagationLossModels are added may be significant. Some propagation models are dependent of the "txPower" (e.g. Nakagami model), and are therefore not commutative. The final receive power (excluding receiver gains) are calculated in the order the models are added.
Definition at line 50 of file yans-wifi-helper.cc.
References m_propagationLoss, ns3::ObjectFactory::Set(), and ns3::ObjectFactory::SetTypeId().
Referenced by DsdvManetExample::CreateDevices(), Default(), RoutingExperiment::Run(), VanetRoutingExperiment::SetupAdhocDevices(), and WifiInterferenceTestCase::WifiSimpleInterference().
AssignStreams()
int64_t ns3::YansWifiChannelHelper::AssignStreams (Ptr< YansWifiChannel > c, int64_t stream)
Assign a fixed random variable stream number to the random variables used by the channel.
Typically this corresponds to random variables used in the propagation loss models. Return the number of streams (possibly zero) that have been assigned.
Parameters
c NetDeviceContainer of the set of net devices for which the WifiNetDevice should be modified to use fixed streams
stream first stream index to use
Returns
the number of stream indices assigned by this helper
Definition at line 121 of file yans-wifi-helper.cc.
Referenced by ChainRegressionTest::CreateDevices(), Bug772ChainTest::CreateDevices(), HwmpProactiveRegressionTest::CreateDevices(), HwmpReactiveRegressionTest::CreateDevices(), HwmpSimplestRegressionTest::CreateDevices(), HwmpDoRfRegressionTest::CreateDevices(), PeerManagementProtocolRegressionTest::CreateDevices(), and FlameRegressionTest::CreateDevices().
Create()
Ptr< YansWifiChannel > ns3::YansWifiChannelHelper::Create (void) const
Returns
a new channel
Create a channel based on the configuration parameters set previously.
Definition at line 98 of file yans-wifi-helper.cc.
References third::channel, ns3::ObjectFactory::Create(), m_propagationDelay, m_propagationLoss, and ns3::PropagationLossModel::SetNext().
Referenced by OcbWifiMacTestCase::ConfigureAdhocMode(), OcbWifiMacTestCase::ConfigureApStaMode(), OcbWifiMacTestCase::ConfigureOcbMode(), BatteryLifetimeTest::ConstantLoadTest(), AodvExample::CreateDevices(), ChainRegressionTest::CreateDevices(), Bug772ChainTest::CreateDevices(), TracerouteExample::CreateDevices(), HwmpProactiveRegressionTest::CreateDevices(), HwmpReactiveRegressionTest::CreateDevices(), HwmpSimplestRegressionTest::CreateDevices(), HwmpDoRfRegressionTest::CreateDevices(), PeerManagementProtocolRegressionTest::CreateDevices(), FlameRegressionTest::CreateDevices(), DsdvManetExample::CreateDevices(), MeshTest::CreateNodes(), WaveNetDeviceExample::CreateWaveNodes(), TestCaseHelper::CreatWaveDevice(), BasicEnergyDepletionTest::DepletionTestCase(), ns3::aodv::LoopbackTestCase::DoRun(), WifiAcMappingTest::DoRun(), WifiMsduAggregatorThroughputTest::DoRun(), Experiment::Run(), RoutingExperiment::Run(), VanetRoutingExperiment::SetupAdhocDevices(), BatteryLifetimeTest::VariableLoadTest(), and WifiInterferenceTestCase::WifiSimpleInterference().
Default()
YansWifiChannelHelper ns3::YansWifiChannelHelper::Default (void) static
Create a channel helper in a default working state.
By default, we create a channel model with a propagation delay equal to a constant, the speed of light, and a propagation loss based on a log distance model with a reference loss of 46.6777 dB at reference distance of 1m.
Returns
YansWifiChannelHelper
Definition at line 41 of file yans-wifi-helper.cc.
References AddPropagationLoss(), and SetPropagationDelay().
Referenced by WaveNetDeviceExample::CreateWaveNodes(), ns3::aodv::LoopbackTestCase::DoRun(), and Experiment::Run().
SetPropagationDelay()
void ns3::YansWifiChannelHelper::SetPropagationDelay (std::string name, std::string n0 = "", const AttributeValue & v0 = EmptyAttributeValue (), std::string n1 = "", const AttributeValue & v1 = EmptyAttributeValue (), std::string n2 = "", const AttributeValue & v2 = EmptyAttributeValue (), std::string n3 = "", const AttributeValue & v3 = EmptyAttributeValue (), std::string n4 = "", const AttributeValue & v4 = EmptyAttributeValue (), std::string n5 = "", const AttributeValue & v5 = EmptyAttributeValue (), std::string n6 = "", const AttributeValue & v6 = EmptyAttributeValue (), std::string n7 = "", const AttributeValue & v7 = EmptyAttributeValue ())
Parameters
name the name of the model to set
n0 the name of the attribute to set
v0 the value of the attribute to set
n1 the name of the attribute to set
v1 the value of the attribute to set
n2 the name of the attribute to set
v2 the value of the attribute to set
n3 the name of the attribute to set
v3 the value of the attribute to set
n4 the name of the attribute to set
v4 the value of the attribute to set
n5 the name of the attribute to set
v5 the value of the attribute to set
n6 the name of the attribute to set
v6 the value of the attribute to set
n7 the name of the attribute to set
v7 the value of the attribute to set
Configure a propagation delay for this channel.
Definition at line 74 of file yans-wifi-helper.cc.
References m_propagationDelay, ns3::ObjectFactory::Set(), and ns3::ObjectFactory::SetTypeId().
Referenced by BatteryLifetimeTest::ConstantLoadTest(), DsdvManetExample::CreateDevices(), Default(), BasicEnergyDepletionTest::DepletionTestCase(), RoutingExperiment::Run(), VanetRoutingExperiment::SetupAdhocDevices(), BatteryLifetimeTest::VariableLoadTest(), and WifiInterferenceTestCase::WifiSimpleInterference().
Member Data Documentation
m_propagationDelay
ObjectFactory ns3::YansWifiChannelHelper::m_propagationDelay private
propagation delay model
Definition at line 146 of file yans-wifi-helper.h.
Referenced by Create(), and SetPropagationDelay().
m_propagationLoss
std::vector<ObjectFactory> ns3::YansWifiChannelHelper::m_propagationLoss private
vector of propagation loss models
Definition at line 145 of file yans-wifi-helper.h.
Referenced by AddPropagationLoss(), and Create().
The documentation for this class was generated from the following files:
src/wifi/helper/yans-wifi-helper.h
src/wifi/helper/yans-wifi-helper.cc