ns-3: PfifoFastQueueDiscDscpPrioritization Class Reference
PfifoFastQueueDiscDscpPrioritization Class Reference
This class tests that each possible DSCP is enqueued in the right band.
Public Member Functions
PfifoFastQueueDiscDscpPrioritization ()
virtual ~PfifoFastQueueDiscDscpPrioritization ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void TestDscpValue (Ptr< PfifoFastQueueDisc > queue, Ipv4Header::DscpType dscp, uint32_t band)
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
This class tests that each possible DSCP is enqueued in the right band.
Definition at line 114 of file pfifo-fast-queue-disc-test-suite.cc.
Constructor & Destructor Documentation
PfifoFastQueueDiscDscpPrioritization()
PfifoFastQueueDiscDscpPrioritization::PfifoFastQueueDiscDscpPrioritization ()
Definition at line 125 of file pfifo-fast-queue-disc-test-suite.cc.
~PfifoFastQueueDiscDscpPrioritization()
PfifoFastQueueDiscDscpPrioritization::~PfifoFastQueueDiscDscpPrioritization () virtual
Definition at line 130 of file pfifo-fast-queue-disc-test-suite.cc.
Member Function Documentation
DoRun()
void PfifoFastQueueDiscDscpPrioritization::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 154 of file pfifo-fast-queue-disc-test-suite.cc.
References ns3::QueueDisc::AddInternalQueue(), ns3::QueueDisc::GetInternalQueue(), NS_TEST_ASSERT_MSG_EQ, and TestDscpValue().
TestDscpValue()
void PfifoFastQueueDiscDscpPrioritization::TestDscpValue (Ptr< PfifoFastQueueDisc > queue, Ipv4Header::DscpType dscp, uint32_t band) private
Definition at line 135 of file pfifo-fast-queue-disc-test-suite.cc.
References ns3::Packet::AddPacketTag(), ns3::QueueDisc::Dequeue(), ns3::QueueDisc::Enqueue(), ns3::QueueDisc::GetInternalQueue(), ns3::Ipv4Header::GetTos(), NS_TEST_ASSERT_MSG_EQ, ns3::Ipv4Header::SetDscp(), ns3::Ipv4Header::SetPayloadSize(), ns3::SocketPriorityTag::SetPriority(), and ns3::Ipv4Header::SetProtocol().
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/test/ns3tc/pfifo-fast-queue-disc-test-suite.cc