ns-3: ns3::RlcAmStatusPduTestCase Class Reference
ns3::RlcAmStatusPduTestCase Class Reference
LTE Models » lte module tests | Test suites
Rlc Am Status Pdu Test Case.
Public Member Functions
RlcAmStatusPduTestCase (SequenceNumber10 ackSn, std::list< SequenceNumber10 > nackSnList, std::string hex)
Constructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Protected Attributes
SequenceNumber10 m_ackSn
ack sequence number
std::string m_hex
hex string
std::list< SequenceNumber10 > m_nackSnList
list of nack sequence numbers
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Detailed Description
Rlc Am Status Pdu Test Case.
Definition at line 116 of file test-lte-rlc-header.cc.
Constructor & Destructor Documentation
RlcAmStatusPduTestCase()
ns3::RlcAmStatusPduTestCase::RlcAmStatusPduTestCase (SequenceNumber10 ackSn, std::list< SequenceNumber10 > nackSnList, std::string hex)
Constructor.
Parameters
ackSn the sequence number
nackSnList list of nack sequence numbers
hex string
Definition at line 140 of file test-lte-rlc-header.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoRun()
void ns3::RlcAmStatusPduTestCase::DoRun (void) protected virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 153 of file test-lte-rlc-header.cc.
References ns3::Packet::AddHeader(), ns3::LteRlcAmHeader::GetAckSn(), ns3::TestUtils::LogPacketContents(), m_ackSn, m_hex, m_nackSnList, NS_LOG_FUNCTION, NS_TEST_ASSERT_MSG_EQ, NS_TEST_ASSERT_MSG_GT, NS_TEST_ASSERT_MSG_LT, ns3::LteRlcAmHeader::PopNack(), ns3::LteRlcAmHeader::PushNack(), ns3::Packet::RemoveHeader(), ns3::LteRlcAmHeader::SetAckSn(), ns3::LteRlcAmHeader::SetControlPdu(), ns3::TestUtils::sprintPacketContentsHex(), and ns3::LteRlcAmHeader::STATUS_PDU.
Member Data Documentation
m_ackSn
SequenceNumber10 ns3::RlcAmStatusPduTestCase::m_ackSn protected
ack sequence number
Definition at line 133 of file test-lte-rlc-header.cc.
Referenced by DoRun().
m_hex
std::string ns3::RlcAmStatusPduTestCase::m_hex protected
hex string
Definition at line 135 of file test-lte-rlc-header.cc.
Referenced by DoRun().
m_nackSnList
std::list<SequenceNumber10> ns3::RlcAmStatusPduTestCase::m_nackSnList protected
list of nack sequence numbers
Definition at line 134 of file test-lte-rlc-header.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/lte/test/test-lte-rlc-header.cc