ns-3: ns3::LteEnbPhySapProvider Class Reference
ns3::LteEnbPhySapProvider Class Reference abstract
Service Access Point (SAP) offered by the eNB-PHY to the eNB-MAC.
#include "lte-enb-phy-sap.h"
Public Member Functions
virtual ~LteEnbPhySapProvider ()
virtual uint8_t GetMacChTtiDelay ()=0
Get the delay from MAC to Channel expressed in TTIs.
virtual void SendLteControlMessage (Ptr< LteControlMessage > msg)=0
Send SendLteControlMessage (PDCCH map, CQI feedbacks) using the ideal control channel.
virtual void SendMacPdu (Ptr< Packet > p)=0
Send the MAC PDU to the channel.
Detailed Description
Service Access Point (SAP) offered by the eNB-PHY to the eNB-MAC.
This is the PHY SAP Provider, i.e., the part of the SAP that contains the PHY methods called by the MAC
Definition at line 40 of file lte-enb-phy-sap.h.
Constructor & Destructor Documentation
~LteEnbPhySapProvider()
ns3::LteEnbPhySapProvider::~LteEnbPhySapProvider () virtual
Definition at line 28 of file lte-enb-phy-sap.cc.
Member Function Documentation
GetMacChTtiDelay()
virtual uint8_t ns3::LteEnbPhySapProvider::GetMacChTtiDelay () pure virtual
Get the delay from MAC to Channel expressed in TTIs.
Returns
MAC channel TTI delay
Implemented in ns3::EnbMemberLteEnbPhySapProvider.
Referenced by ns3::LteEnbMac::DoConfigureMac().
SendLteControlMessage()
virtual void ns3::LteEnbPhySapProvider::SendLteControlMessage (Ptr< LteControlMessage > msg) pure virtual
Send SendLteControlMessage (PDCCH map, CQI feedbacks) using the ideal control channel.
Parameters
msg the Ideal Control Message to send
Implemented in ns3::EnbMemberLteEnbPhySapProvider.
Referenced by ns3::LteEnbMac::DoSchedDlConfigInd(), and ns3::LteEnbMac::DoSchedUlConfigInd().
SendMacPdu()
virtual void ns3::LteEnbPhySapProvider::SendMacPdu (Ptr< Packet > p) pure virtual
Send the MAC PDU to the channel.
Parameters
p the MAC PDU to send
Returns
true if
Implemented in ns3::EnbMemberLteEnbPhySapProvider.
Referenced by ns3::LteEnbMac::DoSchedDlConfigInd(), and ns3::LteEnbMac::DoTransmitPdu().
The documentation for this class was generated from the following files:
src/lte/model/lte-enb-phy-sap.h
src/lte/model/lte-enb-phy-sap.cc