ns-3: ns3::TcpRateOps Class Reference
ns3::TcpRateOps Class Reference abstract
Interface for all operations that involve a Rate monitoring for TCP.
#include "tcp-rate-ops.h"
Classes
struct TcpRateConnection
Information about the connection rate.
struct TcpRateSample
Rate Sample structure.
Public Member Functions
virtual void CalculateAppLimited (uint32_t cWnd, uint32_t in_flight, uint32_t segmentSize, const SequenceNumber32 &tailSeq, const SequenceNumber32 &nextTx, const uint32_t lostOut, const uint32_t retransOut)=0
If a gap is detected between sends, it means we are app-limited.
virtual const TcpRateSample & GenerateSample (uint32_t delivered, uint32_t lost, bool is_sack_reneg, uint32_t priorInFlight, const Time &minRtt)=0
Generate a TcpRateSample to feed a congestion avoidance algorithm.
virtual const TcpRateConnection & GetConnectionRate ()=0
virtual void SkbDelivered (TcpTxItem *skb)=0
Update the Rate information after an item is received.
virtual void SkbSent (TcpTxItem *skb, bool isStartOfTransmission)=0
Put the rate information inside the sent skb.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Interface for all operations that involve a Rate monitoring for TCP.
The interface is meant to take information to generate rate information valid for congestion avoidance algorithm such as BBR.
Please take a look to the TcpRateLinux class for an example.
Definition at line 38 of file tcp-rate-ops.h.
Member Function Documentation
CalculateAppLimited()
virtual void ns3::TcpRateOps::CalculateAppLimited (uint32_t cWnd, uint32_t in_flight, uint32_t segmentSize, const SequenceNumber32 & tailSeq, const SequenceNumber32 & nextTx, const uint32_t lostOut, const uint32_t retransOut) pure virtual
If a gap is detected between sends, it means we are app-limited.
Returns
TODO What the Linux kernel is setting in tp->app_limited? https://elixir.bootlin.com/linux/latest/source/net/ipv4/tcp_rate.c#L177
Parameters
cWnd Congestion Window
in_flight In Flight size (in bytes)
segmentSize Segment size
tailSeq Tail Sequence
nextTx NextTx
lostOut Number of lost bytes
retransOut Number of retransmitted bytes
Implemented in ns3::TcpRateLinux.
Referenced by ns3::TcpSocketBase::Send().
GenerateSample()
virtual const TcpRateSample& ns3::TcpRateOps::GenerateSample (uint32_t delivered, uint32_t lost, bool is_sack_reneg, uint32_t priorInFlight, const Time & minRtt) pure virtual
Generate a TcpRateSample to feed a congestion avoidance algorithm.
This function will be called after an ACK (or a SACK) is received. The (S)ACK carries some implicit information, such as how many segments have been lost or delivered. These values will be this function input.
Parameters
delivered number of delivered segments (e.g., receiving a cumulative ACK means having more than 1 segment delivered) relative to the most recent (S)ACK received
lost number of segments that we detected as lost after the reception of the most recent (S)ACK
is_sack_reneg Is SACK reneged?
minRtt Minimum RTT so far
Returns
The TcpRateSample that will be used for CA
Implemented in ns3::TcpRateLinux.
Referenced by ns3::TcpSocketBase::ReceivedAck(), and TcpRateLinuxWithBufferTest::TestWithSackBlocks().
GetConnectionRate()
virtual const TcpRateConnection& ns3::TcpRateOps::GetConnectionRate () pure virtual
Returns
The information about the rate connection
Implemented in ns3::TcpRateLinux.
Referenced by ns3::TcpSocketBase::ReceivedAck().
GetTypeId()
TypeId ns3::TcpRateOps::GetTypeId (void) static
Get the type ID.
Get the type ID.
Returns
the object TypeId
Definition at line 29 of file tcp-rate-ops.cc.
References ns3::TypeId::SetParent().
SkbDelivered()
virtual void ns3::TcpRateOps::SkbDelivered (TcpTxItem * skb) pure virtual
Update the Rate information after an item is received.
When an skb is sacked or acked, we fill in the rate sample with the (prior) delivery information when the skb was last transmitted.
If an ACK (s)acks multiple skbs (e.g., stretched-acks), this function is called multiple times. We favor the information from the most recently sent skb, i.e., the skb with the highest prior_delivered count.
Parameters
skb The SKB delivered ((s)ACKed)
Implemented in ns3::TcpRateLinux.
Referenced by ns3::TcpSocketBase::ProcessOptionSack(), and ns3::TcpSocketBase::ReceivedAck().
SkbSent()
virtual void ns3::TcpRateOps::SkbSent (TcpTxItem * skb, bool isStartOfTransmission) pure virtual
Put the rate information inside the sent skb.
Snapshot the current delivery information in the skb, to generate a rate sample later when the skb is (s)acked in SkbDelivered ().
Parameters
skb The SKB sent
isStartOfTransmission true if this is a start of transmission (i.e., in_flight == 0)
Implemented in ns3::TcpRateLinux.
Referenced by ns3::TcpSocketBase::SendDataPacket(), and TcpRateLinuxWithBufferTest::TestWithSackBlocks().
The documentation for this class was generated from the following files:
src/internet/model/tcp-rate-ops.h
src/internet/model/tcp-rate-ops.cc