ns-3: AmpduAggregationTest Class Reference
AmpduAggregationTest Class Reference
Wifi Models » wifi module tests | Test suites
Ampdu Aggregation Test.
Public Member Functions
AmpduAggregationTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
Ptr< WifiNetDevice > m_device
WifiNetDevice.
ObjectFactory m_factory
factory
Ptr< StaWifiMac > m_mac
Mac.
Ptr< WifiRemoteStationManager > m_manager
remote station manager
Ptr< YansWifiPhy > m_phy
Phy.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Ampdu Aggregation Test.
Definition at line 53 of file wifi-aggregation-test.cc.
Constructor & Destructor Documentation
AmpduAggregationTest()
AmpduAggregationTest::AmpduAggregationTest ()
Definition at line 67 of file wifi-aggregation-test.cc.
Member Function Documentation
DoRun()
void AmpduAggregationTest::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 73 of file wifi-aggregation-test.cc.
References ns3::WifiRemoteStationManager::AddStationHtCapabilities(), ns3::WifiMac::ConfigureStandard(), ns3::WifiPhy::ConfigureStandard(), ns3::Packet::Copy(), ns3::ObjectFactory::Create(), ns3::Object::Dispose(), ns3::WifiMacHeader::GetAddr1(), ns3::RegularWifiMac::GetBEQueue(), ns3::WifiPsdu::GetHeader(), ns3::Txop::GetLow(), ns3::WifiPsdu::GetNMpdus(), ns3::WifiMacHeader::GetSequenceNumber(), ns3::WifiPsdu::GetSize(), ns3::Txop::GetWifiMacQueue(), ns3::QosTxop::m_baManager, ns3::Txop::m_currentHdr, ns3::Txop::m_currentPacket, m_device, m_factory, m_mac, m_manager, m_phy, ns3::RegularWifiMac::m_txMiddle, ns3::QosTxop::MissedAck(), NS_TEST_EXPECT_MSG_EQ, ns3::ObjectFactory::Set(), ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetAddr2(), ns3::RegularWifiMac::SetAddress(), ns3::ObjectBase::SetAttribute(), ns3::MgtAddBaRequestHeader::SetBufferSize(), ns3::WifiMac::SetDevice(), ns3::WifiPhy::SetDevice(), ns3::WifiMacHeader::SetFragmentNumber(), ns3::WifiNetDevice::SetHtConfiguration(), ns3::MgtAddBaRequestHeader::SetImmediateBlockAck(), ns3::WifiNetDevice::SetMac(), ns3::HtCapabilities::SetMaxAmpduLength(), ns3::WifiRemoteStationManager::SetMaxSsrc(), ns3::WifiMacHeader::SetNoMoreFragments(), ns3::WifiMacHeader::SetNoRetry(), ns3::WifiNetDevice::SetPhy(), ns3::WifiMacHeader::SetQosTid(), ns3::WifiNetDevice::SetRemoteStationManager(), ns3::WifiMacHeader::SetSequenceNumber(), ns3::MgtAddBaRequestHeader::SetStartingSequence(), ns3::MgtAddBaRequestHeader::SetTid(), ns3::MgtAddBaRequestHeader::SetTimeout(), ns3::WifiMacHeader::SetType(), ns3::ObjectFactory::SetTypeId(), ns3::WifiRemoteStationManager::SetupPhy(), ns3::StaWifiMac::SetWifiPhy(), ns3::StaWifiMac::SetWifiRemoteStationManager(), ns3::WIFI_MAC_QOSDATA, and ns3::WIFI_PHY_STANDARD_80211n_5GHZ.
Member Data Documentation
m_device
Ptr<WifiNetDevice> AmpduAggregationTest::m_device private
WifiNetDevice.
Definition at line 60 of file wifi-aggregation-test.cc.
Referenced by DoRun().
m_factory
ObjectFactory AmpduAggregationTest::m_factory private
factory
Definition at line 64 of file wifi-aggregation-test.cc.
Referenced by DoRun().
m_mac
Ptr<StaWifiMac> AmpduAggregationTest::m_mac private
Mac.
Definition at line 61 of file wifi-aggregation-test.cc.
Referenced by DoRun().
m_manager
Ptr<WifiRemoteStationManager> AmpduAggregationTest::m_manager private
remote station manager
Definition at line 63 of file wifi-aggregation-test.cc.
Referenced by DoRun().
m_phy
Ptr<YansWifiPhy> AmpduAggregationTest::m_phy private
Phy.
Definition at line 62 of file wifi-aggregation-test.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/wifi/test/wifi-aggregation-test.cc