ns-3: ns3::aodv::IdCacheTest Class Reference
ns3::aodv::IdCacheTest Class Reference
AODV Routing » AODV module tests | Test suites
Unit test for id cache.
Public Member Functions
IdCacheTest ()
virtual void DoRun ()
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CheckTimeout1 ()
Timeout test function #1.
void CheckTimeout2 ()
Timeout test function #2.
void CheckTimeout3 ()
Timeout test function #3.
Private Attributes
IdCache cache
ID cache.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Unit test for id cache.
Definition at line 46 of file aodv-id-cache-test-suite.cc.
Constructor & Destructor Documentation
IdCacheTest()
ns3::aodv::IdCacheTest::IdCacheTest () inline
Definition at line 49 of file aodv-id-cache-test-suite.cc.
Member Function Documentation
CheckTimeout1()
void ns3::aodv::IdCacheTest::CheckTimeout1 () private
Timeout test function #1.
Definition at line 91 of file aodv-id-cache-test-suite.cc.
References cache, ns3::aodv::IdCache::GetSize(), and NS_TEST_EXPECT_MSG_EQ.
Referenced by DoRun().
CheckTimeout2()
void ns3::aodv::IdCacheTest::CheckTimeout2 () private
Timeout test function #2.
Definition at line 97 of file aodv-id-cache-test-suite.cc.
References cache, ns3::aodv::IdCache::GetSize(), and NS_TEST_EXPECT_MSG_EQ.
Referenced by DoRun().
CheckTimeout3()
void ns3::aodv::IdCacheTest::CheckTimeout3 () private
Timeout test function #3.
Definition at line 103 of file aodv-id-cache-test-suite.cc.
References cache, ns3::aodv::IdCache::GetSize(), and NS_TEST_EXPECT_MSG_EQ.
Referenced by DoRun().
DoRun()
void ns3::aodv::IdCacheTest::DoRun () virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 68 of file aodv-id-cache-test-suite.cc.
References cache, CheckTimeout1(), CheckTimeout2(), CheckTimeout3(), ns3::Simulator::Destroy(), ns3::aodv::IdCache::GetLifeTime(), ns3::aodv::IdCache::GetSize(), ns3::aodv::IdCache::IsDuplicate(), NS_TEST_EXPECT_MSG_EQ, ns3::Simulator::Run(), ns3::Simulator::Schedule(), ns3::Seconds(), and ns3::aodv::IdCache::SetLifetime().
Member Data Documentation
cache
IdCache ns3::aodv::IdCacheTest::cache private
ID cache.
Definition at line 64 of file aodv-id-cache-test-suite.cc.
Referenced by CheckTimeout1(), CheckTimeout2(), CheckTimeout3(), and DoRun().
The documentation for this class was generated from the following file:
src/aodv/test/aodv-id-cache-test-suite.cc