ns-3: PhyConnectivityTest Class Reference
PhyConnectivityTest Class Reference
Public Member Functions
PhyConnectivityTest ()
virtual ~PhyConnectivityTest ()
bool HaveSamePacketContents (Ptr< Packet > packet1, Ptr< Packet > packet2)
void Interference (Ptr< const Packet > packet, uint32_t node)
void NoMoreDemodulators (Ptr< const Packet > packet, uint32_t node)
void ReceivedPacket (Ptr< const Packet > packet, uint32_t node)
void Reset ()
void UnderSensitivity (Ptr< const Packet > packet, uint32_t node)
void WrongFrequency (Ptr< const Packet > packet, uint32_t node)
void WrongSf (Ptr< const Packet > packet, uint32_t node)
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
Ptr< LoraChannel > channel
Ptr< SimpleEndDeviceLoraPhy > edPhy1
Ptr< SimpleEndDeviceLoraPhy > edPhy2
Ptr< SimpleEndDeviceLoraPhy > edPhy3
int m_interferenceCalls = 0
Ptr< Packet > m_latestReceivedPacket
int m_noMoreDemodulatorsCalls = 0
int m_receivedPacketCalls = 0
int m_underSensitivityCalls = 0
int m_wrongFrequencyCalls = 0
int m_wrongSfCalls = 0
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 930 of file lorawan-test-suite.cc.
Constructor & Destructor Documentation
PhyConnectivityTest()
PhyConnectivityTest::PhyConnectivityTest ()
Definition at line 961 of file lorawan-test-suite.cc.
~PhyConnectivityTest()
PhyConnectivityTest::~PhyConnectivityTest () virtual
Definition at line 967 of file lorawan-test-suite.cc.
Member Function Documentation
DoRun()
void PhyConnectivityTest::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 1139 of file lorawan-test-suite.cc.
References edPhy1, edPhy2, edPhy3, ns3::lorawan::LoraPhy::GetMobility(), ns3::Object::GetObject(), ns3::lorawan::EndDeviceLoraPhy::GetState(), HaveSamePacketContents(), ns3::Hours(), m_interferenceCalls, m_latestReceivedPacket, m_receivedPacketCalls, m_underSensitivityCalls, m_wrongFrequencyCalls, m_wrongSfCalls, NS_LOG_DEBUG, NS_TEST_EXPECT_MSG_EQ, Reset(), ns3::Seconds(), SetPosition(), ns3::lorawan::EndDeviceLoraPhy::SetSpreadingFactor(), ns3::lorawan::LoraTxParameters::sf, and ns3::lorawan::EndDeviceLoraPhy::SwitchToSleep().
HaveSamePacketContents()
bool PhyConnectivityTest::HaveSamePacketContents (Ptr< Packet > packet1, Ptr< Packet > packet2)
Definition at line 1022 of file lorawan-test-suite.cc.
References ns3::Packet::GetSerializedSize(), NS_ASSERT, NS_LOG_DEBUG, and ns3::Packet::Serialize().
Referenced by DoRun().
Interference()
void PhyConnectivityTest::Interference (Ptr< const Packet > packet, uint32_t node)
Definition at line 990 of file lorawan-test-suite.cc.
References m_interferenceCalls, and NS_LOG_FUNCTION.
Referenced by Reset().
NoMoreDemodulators()
void PhyConnectivityTest::NoMoreDemodulators (Ptr< const Packet > packet, uint32_t node)
Definition at line 998 of file lorawan-test-suite.cc.
References m_noMoreDemodulatorsCalls, and NS_LOG_FUNCTION.
Referenced by Reset().
ReceivedPacket()
void PhyConnectivityTest::ReceivedPacket (Ptr< const Packet > packet, uint32_t node)
Definition at line 972 of file lorawan-test-suite.cc.
References ns3::Packet::Copy(), m_latestReceivedPacket, m_receivedPacketCalls, and NS_LOG_FUNCTION.
Referenced by Reset().
Reset()
void PhyConnectivityTest::Reset ()
Definition at line 1049 of file lorawan-test-suite.cc.
References ns3::lorawan::LoraChannel::Add(), channel, edPhy1, edPhy2, edPhy3, Interference(), m_interferenceCalls, m_receivedPacketCalls, m_underSensitivityCalls, m_wrongFrequencyCalls, m_wrongSfCalls, ns3::MakeCallback(), NoMoreDemodulators(), ReceivedPacket(), ns3::lorawan::LoraPhy::SetChannel(), ns3::lorawan::EndDeviceLoraPhy::SetFrequency(), ns3::lorawan::LoraPhy::SetMobility(), ns3::LogDistancePropagationLossModel::SetPathLossExponent(), ns3::MobilityModel::SetPosition(), ns3::LogDistancePropagationLossModel::SetReference(), ns3::lorawan::EndDeviceLoraPhy::SetSpreadingFactor(), ns3::lorawan::EndDeviceLoraPhy::SwitchToStandby(), ns3::ObjectBase::TraceConnectWithoutContext(), UnderSensitivity(), WrongFrequency(), and WrongSf().
Referenced by DoRun().
UnderSensitivity()
void PhyConnectivityTest::UnderSensitivity (Ptr< const Packet > packet, uint32_t node)
Definition at line 982 of file lorawan-test-suite.cc.
References m_underSensitivityCalls, and NS_LOG_FUNCTION.
Referenced by Reset().
WrongFrequency()
void PhyConnectivityTest::WrongFrequency (Ptr< const Packet > packet, uint32_t node)
Definition at line 1014 of file lorawan-test-suite.cc.
References m_wrongFrequencyCalls, and NS_LOG_FUNCTION.
Referenced by Reset().
WrongSf()
void PhyConnectivityTest::WrongSf (Ptr< const Packet > packet, uint32_t node)
Definition at line 1006 of file lorawan-test-suite.cc.
References m_wrongSfCalls, and NS_LOG_FUNCTION.
Referenced by Reset().
Member Data Documentation
channel
Ptr<LoraChannel> PhyConnectivityTest::channel private
Definition at line 948 of file lorawan-test-suite.cc.
Referenced by Reset().
edPhy1
Ptr<SimpleEndDeviceLoraPhy> PhyConnectivityTest::edPhy1 private
Definition at line 949 of file lorawan-test-suite.cc.
Referenced by DoRun(), and Reset().
edPhy2
Ptr<SimpleEndDeviceLoraPhy> PhyConnectivityTest::edPhy2 private
Definition at line 950 of file lorawan-test-suite.cc.
Referenced by DoRun(), and Reset().
edPhy3
Ptr<SimpleEndDeviceLoraPhy> PhyConnectivityTest::edPhy3 private
Definition at line 951 of file lorawan-test-suite.cc.
Referenced by DoRun(), and Reset().
m_interferenceCalls
int PhyConnectivityTest::m_interferenceCalls = 0 private
Definition at line 956 of file lorawan-test-suite.cc.
Referenced by DoRun(), Interference(), and Reset().
m_latestReceivedPacket
Ptr<Packet> PhyConnectivityTest::m_latestReceivedPacket private
Definition at line 953 of file lorawan-test-suite.cc.
Referenced by DoRun(), and ReceivedPacket().
m_noMoreDemodulatorsCalls
int PhyConnectivityTest::m_noMoreDemodulatorsCalls = 0 private
Definition at line 957 of file lorawan-test-suite.cc.
Referenced by NoMoreDemodulators().
m_receivedPacketCalls
int PhyConnectivityTest::m_receivedPacketCalls = 0 private
Definition at line 954 of file lorawan-test-suite.cc.
Referenced by DoRun(), ReceivedPacket(), and Reset().
m_underSensitivityCalls
int PhyConnectivityTest::m_underSensitivityCalls = 0 private
Definition at line 955 of file lorawan-test-suite.cc.
Referenced by DoRun(), Reset(), and UnderSensitivity().
m_wrongFrequencyCalls
int PhyConnectivityTest::m_wrongFrequencyCalls = 0 private
Definition at line 959 of file lorawan-test-suite.cc.
Referenced by DoRun(), Reset(), and WrongFrequency().
m_wrongSfCalls
int PhyConnectivityTest::m_wrongSfCalls = 0 private
Definition at line 958 of file lorawan-test-suite.cc.
Referenced by DoRun(), Reset(), and WrongSf().
The documentation for this class was generated from the following file:
src/lorawan/test/lorawan-test-suite.cc