ns-3: ns3::EpcX2HandoverPreparationFailureHeader Class Reference
ns3::EpcX2HandoverPreparationFailureHeader Class Reference
EpcX2HandoverPreparationFailureHeader.
#include "epc-x2-header.h"
Public Member Functions
EpcX2HandoverPreparationFailureHeader ()
virtual ~EpcX2HandoverPreparationFailureHeader ()
virtual uint32_t Deserialize (Buffer::Iterator start)
uint16_t GetCause () const
Get cause function.
uint16_t GetCriticalityDiagnostics () const
Get criticality diagnostics function.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint32_t GetLengthOfIes () const
Get length of IEs function.
uint32_t GetNumberOfIes () const
Get number of IEs function.
uint16_t GetOldEnbUeX2apId () const
Get old ENB UE X2 AP ID function.
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetCause (uint16_t cause)
Set cause function.
void SetCriticalityDiagnostics (uint16_t criticalityDiagnostics)
Set criticality diagnostics function.
void SetOldEnbUeX2apId (uint16_t x2apId)
Set old ENB UE X2 AP ID function.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint16_t m_cause
cause
uint16_t m_criticalityDiagnostics
criticality diagnostics
uint32_t m_headerLength
header length
uint32_t m_numberOfIes
number of IEs
uint16_t m_oldEnbUeX2apId
old ENB UE X2 AP ID
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
EpcX2HandoverPreparationFailureHeader.
Definition at line 322 of file epc-x2-header.h.
Constructor & Destructor Documentation
EpcX2HandoverPreparationFailureHeader()
ns3::EpcX2HandoverPreparationFailureHeader::EpcX2HandoverPreparationFailureHeader ()
Definition at line 665 of file epc-x2-header.cc.
~EpcX2HandoverPreparationFailureHeader()
ns3::EpcX2HandoverPreparationFailureHeader::~EpcX2HandoverPreparationFailureHeader () virtual
Definition at line 674 of file epc-x2-header.cc.
References m_cause, m_criticalityDiagnostics, m_headerLength, m_numberOfIes, and m_oldEnbUeX2apId.
Member Function Documentation
Deserialize()
uint32_t ns3::EpcX2HandoverPreparationFailureHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 717 of file epc-x2-header.cc.
References GetSerializedSize(), m_cause, m_criticalityDiagnostics, m_headerLength, m_numberOfIes, m_oldEnbUeX2apId, ns3::Buffer::Iterator::ReadNtohU16(), and visualizer.core::start().
GetCause()
uint16_t ns3::EpcX2HandoverPreparationFailureHeader::GetCause () const
Get cause function.
Returns
the cause
Definition at line 752 of file epc-x2-header.cc.
References m_cause.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
GetCriticalityDiagnostics()
uint16_t ns3::EpcX2HandoverPreparationFailureHeader::GetCriticalityDiagnostics () const
Get criticality diagnostics function.
Returns
the criticality diagnostics
Definition at line 764 of file epc-x2-header.cc.
References m_criticalityDiagnostics.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
GetInstanceTypeId()
TypeId ns3::EpcX2HandoverPreparationFailureHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 695 of file epc-x2-header.cc.
References GetTypeId().
GetLengthOfIes()
uint32_t ns3::EpcX2HandoverPreparationFailureHeader::GetLengthOfIes () const
Get length of IEs function.
Returns
the length of IEs
Definition at line 776 of file epc-x2-header.cc.
References m_headerLength.
Referenced by ns3::EpcX2::DoSendHandoverPreparationFailure().
GetNumberOfIes()
uint32_t ns3::EpcX2HandoverPreparationFailureHeader::GetNumberOfIes () const
Get number of IEs function.
Returns
the number of IEs
Definition at line 782 of file epc-x2-header.cc.
References m_numberOfIes.
Referenced by ns3::EpcX2::DoSendHandoverPreparationFailure().
GetOldEnbUeX2apId()
uint16_t ns3::EpcX2HandoverPreparationFailureHeader::GetOldEnbUeX2apId () const
Get old ENB UE X2 AP ID function.
Returns
the old ENB UE X2 AP ID
Definition at line 740 of file epc-x2-header.cc.
References m_oldEnbUeX2apId.
Referenced by ns3::EpcX2::RecvFromX2cSocket().
GetSerializedSize()
uint32_t ns3::EpcX2HandoverPreparationFailureHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 701 of file epc-x2-header.cc.
References m_headerLength.
Referenced by Deserialize().
GetTypeId()
TypeId ns3::EpcX2HandoverPreparationFailureHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 684 of file epc-x2-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::EpcX2HandoverPreparationFailureHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 732 of file epc-x2-header.cc.
References m_cause, m_criticalityDiagnostics, and m_oldEnbUeX2apId.
Serialize()
void ns3::EpcX2HandoverPreparationFailureHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 707 of file epc-x2-header.cc.
References m_cause, m_criticalityDiagnostics, m_oldEnbUeX2apId, visualizer.core::start(), and ns3::Buffer::Iterator::WriteHtonU16().
SetCause()
void ns3::EpcX2HandoverPreparationFailureHeader::SetCause (uint16_t cause)
Set cause function.
Parameters
cause
Definition at line 758 of file epc-x2-header.cc.
References m_cause.
Referenced by ns3::EpcX2::DoSendHandoverPreparationFailure().
SetCriticalityDiagnostics()
void ns3::EpcX2HandoverPreparationFailureHeader::SetCriticalityDiagnostics (uint16_t criticalityDiagnostics)
Set criticality diagnostics function.
Parameters
criticalityDiagnostics the criticality diagnostics
Definition at line 770 of file epc-x2-header.cc.
References m_criticalityDiagnostics.
Referenced by ns3::EpcX2::DoSendHandoverPreparationFailure().
SetOldEnbUeX2apId()
void ns3::EpcX2HandoverPreparationFailureHeader::SetOldEnbUeX2apId (uint16_t x2apId)
Set old ENB UE X2 AP ID function.
Parameters
x2apId the old ENB UE X2 AP ID
Definition at line 746 of file epc-x2-header.cc.
References m_oldEnbUeX2apId.
Referenced by ns3::EpcX2::DoSendHandoverPreparationFailure().
Member Data Documentation
m_cause
uint16_t ns3::EpcX2HandoverPreparationFailureHeader::m_cause private
cause
Definition at line 389 of file epc-x2-header.h.
Referenced by ~EpcX2HandoverPreparationFailureHeader(), Deserialize(), GetCause(), Print(), Serialize(), and SetCause().
m_criticalityDiagnostics
uint16_t ns3::EpcX2HandoverPreparationFailureHeader::m_criticalityDiagnostics private
criticality diagnostics
Definition at line 390 of file epc-x2-header.h.
Referenced by ~EpcX2HandoverPreparationFailureHeader(), Deserialize(), GetCriticalityDiagnostics(), Print(), Serialize(), and SetCriticalityDiagnostics().
m_headerLength
uint32_t ns3::EpcX2HandoverPreparationFailureHeader::m_headerLength private
header length
Definition at line 386 of file epc-x2-header.h.
Referenced by ~EpcX2HandoverPreparationFailureHeader(), Deserialize(), GetLengthOfIes(), and GetSerializedSize().
m_numberOfIes
uint32_t ns3::EpcX2HandoverPreparationFailureHeader::m_numberOfIes private
number of IEs
Definition at line 385 of file epc-x2-header.h.
Referenced by ~EpcX2HandoverPreparationFailureHeader(), Deserialize(), and GetNumberOfIes().
m_oldEnbUeX2apId
uint16_t ns3::EpcX2HandoverPreparationFailureHeader::m_oldEnbUeX2apId private
old ENB UE X2 AP ID
Definition at line 388 of file epc-x2-header.h.
Referenced by ~EpcX2HandoverPreparationFailureHeader(), Deserialize(), GetOldEnbUeX2apId(), Print(), Serialize(), and SetOldEnbUeX2apId().
The documentation for this class was generated from the following files:
src/lte/model/epc-x2-header.h
src/lte/model/epc-x2-header.cc