ns-3: IntegerTraceSourceTestCase Class Reference
IntegerTraceSourceTestCase Class Reference
Public Member Functions
IntegerTraceSourceTestCase (std::string description)
virtual ~IntegerTraceSourceTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void NotifySource1 (int8_t old, int8_t n)
Private Attributes
int64_t m_got1
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 1117 of file attribute-test-suite.cc.
Constructor & Destructor Documentation
IntegerTraceSourceTestCase()
IntegerTraceSourceTestCase::IntegerTraceSourceTestCase (std::string description)
Definition at line 1135 of file attribute-test-suite.cc.
~IntegerTraceSourceTestCase()
virtual IntegerTraceSourceTestCase::~IntegerTraceSourceTestCase () inline virtual
Definition at line 1121 of file attribute-test-suite.cc.
Member Function Documentation
DoRun()
void IntegerTraceSourceTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 1140 of file attribute-test-suite.cc.
References m_got1, ns3::MakeCallback(), NotifySource1(), NS_TEST_ASSERT_MSG_EQ, NS_TEST_ASSERT_MSG_NE, ns3::ObjectBase::SetAttributeFailSafe(), ns3::ObjectBase::TraceConnectWithoutContext(), and ns3::ObjectBase::TraceDisconnectWithoutContext().
NotifySource1()
void IntegerTraceSourceTestCase::NotifySource1 (int8_t old, int8_t n) inline private
Definition at line 1127 of file attribute-test-suite.cc.
References m_got1, sample-rng-plot::n, and NS_UNUSED.
Referenced by DoRun().
Member Data Documentation
m_got1
int64_t IntegerTraceSourceTestCase::m_got1 private
Definition at line 1132 of file attribute-test-suite.cc.
Referenced by DoRun(), and NotifySource1().
The documentation for this class was generated from the following file:
src/core/test/attribute-test-suite.cc