ns-3: ns3::Header Class Reference
ns3::Header Class Reference abstract
Network » Packet
Protocol header serialization and deserialization.
#include "header.h"
Inherits ns3::Chunk.
Inherited by anonymous_namespace{packet-metadata-test.cc}::HistoryHeaderBase, anonymous_namespace{packet-test-suite.cc}::ATestHeaderBase, BenchHeader< N >, MyHeader, ns3::AlohaNoackMacHeader, ns3::AmpduSubframeHeader, ns3::AmsduSubframeHeader, ns3::aodv::RerrHeader, ns3::aodv::RrepAckHeader, ns3::aodv::RrepHeader, ns3::aodv::RreqHeader, ns3::aodv::TypeHeader, ns3::ArpHeader, ns3::Asn1Header, ns3::BandwidthRequestHeader, ns3::BeaconPayloadHeader, ns3::CommandPayloadHeader, ns3::CtrlBAckRequestHeader, ns3::CtrlBAckResponseHeader, ns3::Dcd, ns3::DhcpHeader, ns3::DlMap, ns3::dot11s::MeshHeader, ns3::dot11s::PeerLinkCloseStart, ns3::dot11s::PeerLinkConfirmStart, ns3::dot11s::PeerLinkOpenStart, ns3::DsaAck, ns3::DsaReq, ns3::DsaRsp, ns3::dsdv::DsdvHeader, ns3::dsr::DsrFsHeader, ns3::dsr::DsrOptionHeader, ns3::DsssSigHeader, ns3::EpcX2HandoverPreparationFailureHeader, ns3::EpcX2HandoverRequestAckHeader, ns3::EpcX2HandoverRequestHeader, ns3::EpcX2Header, ns3::EpcX2LoadInformationHeader, ns3::EpcX2ResourceStatusUpdateHeader, ns3::EpcX2SnStatusTransferHeader, ns3::EpcX2UeContextReleaseHeader, ns3::EthernetHeader, ns3::flame::FlameHeader, ns3::FragmentationSubheader, ns3::GenericMacHeader, ns3::GrantManagementSubheader, ns3::GtpcHeader, ns3::GtpuHeader, ns3::HeSigHeader, ns3::HtSigHeader, ns3::Icmpv4DestinationUnreachable, ns3::Icmpv4Echo, ns3::Icmpv4Header, ns3::Icmpv4TimeExceeded, ns3::Icmpv6Header, ns3::Icmpv6OptionHeader, ns3::IdealHandoverCommandHeader, ns3::IdealHandoverPreparationInfoHeader, ns3::Ipv4Header, ns3::Ipv6ExtensionHeader, ns3::Ipv6Header, ns3::Ipv6OptionHeader, ns3::LlcSnapHeader, ns3::lorawan::LoraFrameHeader, ns3::lorawan::LorawanMacHeader, ns3::LrWpanMacHeader, ns3::LSigHeader, ns3::LtePdcpHeader, ns3::LteRlcAmHeader, ns3::LteRlcHeader, ns3::MacHeaderType, ns3::ManagementMessageType, ns3::MgtAddBaRequestHeader, ns3::MgtAddBaResponseHeader, ns3::MgtAssocRequestHeader, ns3::MgtAssocResponseHeader, ns3::MgtDelBaHeader, ns3::MgtProbeRequestHeader, ns3::MgtProbeResponseHeader, ns3::MgtReassocRequestHeader, ns3::OfdmDownlinkFramePrefix, ns3::olsr::MessageHeader, ns3::olsr::PacketHeader, ns3::PppHeader, ns3::RadiotapHeader, ns3::RipHeader, ns3::RipNgHeader, ns3::RipNgRte, ns3::RipRte, ns3::RngReq, ns3::RngRsp, ns3::SeqTsHeader, ns3::SixLowPanBc0, ns3::SixLowPanFrag1, ns3::SixLowPanFragN, ns3::SixLowPanHc1, ns3::SixLowPanIphc, ns3::SixLowPanIpv6, ns3::SixLowPanMesh, ns3::SixLowPanNhcExtension, ns3::SixLowPanUdpNhcExtension, ns3::SllHeader, ns3::TcpHeader, ns3::ThreeGppHttpHeader, ns3::Tlv, ns3::UanHeaderCommon, ns3::UanHeaderRcAck, ns3::UanHeaderRcCts, ns3::UanHeaderRcCtsGlobal, ns3::UanHeaderRcData, ns3::UanHeaderRcRts, ns3::Ucd, ns3::UdpHeader, ns3::UlMap, ns3::VendorSpecificActionHeader, ns3::VhtSigHeader, ns3::WifiActionHeader, ns3::WifiInformationElementVector, ns3::WifiMacHeader, ns3::WimaxMacToMacHeader, and ns3::SimpleRefCount< PbbPacket, Header >.
Public Member Functions
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start)=0
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
virtual uint32_t GetSerializedSize (void) const =0
virtual void Print (std::ostream &os) const =0
virtual void Serialize (Buffer::Iterator start) const =0
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
virtual TypeId GetInstanceTypeId (void) const =0
Get the most derived TypeId for this Object.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Protocol header serialization and deserialization.
Every Protocol header which needs to be inserted or removed from a Packet instance must derive from this base class and implement the pure virtual methods defined here.
Sample code which shows how to create a new type of Header, and how to use it, is shown in the sample file samples/main-packet-header.cc
Definition at line 42 of file header.h.
Constructor & Destructor Documentation
~Header()
ns3::Header::~Header () virtual
Definition at line 30 of file header.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Deserialize() [1/3]
virtual uint32_t ns3::Chunk::Deserialize
Deserialize the object from a buffer iterator.
This version of Deserialize can be used when the Chunk has a fixed size. It should not be called for variable-sized Chunk derived types (but must be implemented, for historical reasons).
Parameters
start the buffer iterator
Returns
the number of deserialized bytes
Deserialize() [2/3]
virtual uint32_t ns3::Header::Deserialize (Buffer::Iterator start) pure virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Chunk.
Implemented in ns3::E2eStatsHeader, BenchHeader< N >, ns3::Tlv, ns3::WimaxMacToMacHeader, ns3::FragmentationSubheader, ns3::GrantManagementSubheader, ns3::BandwidthRequestHeader, ns3::GenericMacHeader, ns3::MacHeaderType, ns3::UlMap, ns3::Ucd, ns3::OfdmDownlinkFramePrefix, ns3::RngReq, ns3::DsaAck, ns3::DsaRsp, ns3::DsaReq, ns3::RngRsp, ns3::ManagementMessageType, ns3::DlMap, ns3::Dcd, ns3::HeSigHeader, ns3::VhtSigHeader, ns3::HtSigHeader, ns3::LSigHeader, ns3::DsssSigHeader, ns3::WifiMacHeader, ns3::WifiInformationElementVector, ns3::MgtDelBaHeader, ns3::MgtAddBaResponseHeader, ns3::MgtAddBaRequestHeader, ns3::WifiActionHeader, ns3::MgtProbeResponseHeader, ns3::MgtProbeRequestHeader, ns3::MgtAssocResponseHeader, ns3::MgtReassocRequestHeader, ns3::MgtAssocRequestHeader, ns3::CtrlBAckResponseHeader, ns3::CtrlBAckRequestHeader, ns3::AmsduSubframeHeader, ns3::AmpduSubframeHeader, ns3::VendorSpecificActionHeader, ns3::UanHeaderRcAck, ns3::UanHeaderRcCts, ns3::UanHeaderRcCtsGlobal, ns3::UanHeaderRcRts, ns3::UanHeaderRcData, ns3::UanHeaderCommon, ns3::AlohaNoackMacHeader, ns3::SixLowPanMesh, ns3::SixLowPanBc0, ns3::SixLowPanUdpNhcExtension, ns3::SixLowPanNhcExtension, ns3::SixLowPanIphc, ns3::SixLowPanIpv6, ns3::SixLowPanFragN, ns3::SixLowPanFrag1, ns3::SixLowPanHc1, ns3::PppHeader, ns3::olsr::MessageHeader, ns3::olsr::PacketHeader, ns3::SllHeader, ns3::RadiotapHeader, ns3::PbbPacket, ns3::LlcSnapHeader, ns3::EthernetHeader, anonymous_namespace{packet-metadata-test.cc}::HistoryHeader< N >, MyHeader, ns3::flame::FlameHeader, ns3::dot11s::PeerLinkConfirmStart, ns3::dot11s::PeerLinkCloseStart, ns3::dot11s::PeerLinkOpenStart, ns3::dot11s::MeshHeader, ns3::IdealHandoverCommandHeader, ns3::IdealHandoverPreparationInfoHeader, ns3::LteRlcHeader, ns3::LteRlcAmHeader, ns3::LtePdcpHeader, ns3::EpcX2ResourceStatusUpdateHeader, ns3::EpcX2LoadInformationHeader, ns3::EpcX2UeContextReleaseHeader, ns3::EpcX2SnStatusTransferHeader, ns3::EpcX2HandoverPreparationFailureHeader, ns3::EpcX2HandoverRequestAckHeader, ns3::EpcX2HandoverRequestHeader, ns3::EpcX2Header, ns3::GtpuHeader, ns3::GtpcDeleteBearerResponseMessage, ns3::GtpcDeleteBearerRequestMessage, ns3::GtpcDeleteBearerCommandMessage, ns3::GtpcModifyBearerResponseMessage, ns3::GtpcModifyBearerRequestMessage, ns3::GtpcCreateSessionResponseMessage, ns3::GtpcCreateSessionRequestMessage, ns3::GtpcHeader, ns3::CommandPayloadHeader, ns3::BeaconPayloadHeader, ns3::LrWpanMacHeader, ns3::lorawan::LorawanMacHeader, ns3::lorawan::LoraFrameHeader, ns3::UdpHeader, ns3::TcpHeader, ns3::RipNgHeader, ns3::RipNgRte, ns3::RipHeader, ns3::RipRte, ns3::Ipv6OptionRouterAlertHeader, ns3::Ipv6OptionJumbogramHeader, ns3::Ipv6OptionPadnHeader, ns3::Ipv6OptionPad1Header, ns3::Ipv6OptionHeader, ns3::Ipv6Header, ns3::Ipv6ExtensionAHHeader, ns3::Ipv6ExtensionESPHeader, ns3::Ipv6ExtensionLooseRoutingHeader, ns3::Ipv6ExtensionRoutingHeader, ns3::Ipv6ExtensionFragmentHeader, ns3::Ipv6ExtensionDestinationHeader, ns3::Ipv6ExtensionHopByHopHeader, ns3::Ipv6ExtensionHeader, ns3::Ipv4Header, ns3::Icmpv6OptionRedirected, ns3::Icmpv6OptionLinkLayerAddress, ns3::Icmpv6OptionPrefixInformation, ns3::Icmpv6OptionMtu, ns3::Icmpv6ParameterError, ns3::Icmpv6TimeExceeded, ns3::Icmpv6TooBig, ns3::Icmpv6DestinationUnreachable, ns3::Icmpv6Echo, ns3::Icmpv6Redirection, ns3::Icmpv6RS, ns3::Icmpv6RA, ns3::Icmpv6NA, ns3::Icmpv6NS, ns3::Icmpv6OptionHeader, ns3::Icmpv6Header, ns3::Icmpv4TimeExceeded, ns3::Icmpv4DestinationUnreachable, ns3::Icmpv4Echo, ns3::Icmpv4Header, ns3::ArpHeader, ns3::DhcpHeader, ns3::dsr::DsrOptionAckHeader, ns3::dsr::DsrOptionAckReqHeader, ns3::dsr::DsrOptionRerrUnsupportHeader, ns3::dsr::DsrOptionRerrUnreachHeader, ns3::dsr::DsrOptionRerrHeader, ns3::dsr::DsrOptionSRHeader, ns3::dsr::DsrOptionRrepHeader, ns3::dsr::DsrOptionRreqHeader, ns3::dsr::DsrOptionPadnHeader, ns3::dsr::DsrOptionPad1Header, ns3::dsr::DsrOptionHeader, ns3::dsr::DsrRoutingHeader, ns3::dsr::DsrFsHeader, ns3::dsdv::DsdvHeader, ns3::ThreeGppHttpHeader, ns3::SeqTsHeader, ns3::aodv::RerrHeader, ns3::aodv::RrepAckHeader, ns3::aodv::RrepHeader, ns3::aodv::RreqHeader, ns3::aodv::TypeHeader, anonymous_namespace{packet-test-suite.cc}::ATestHeader< N >, ns3::RrcAsn1Header, ns3::Asn1Header, ns3::MeasurementReportHeader, ns3::RrcConnectionRejectHeader, ns3::RrcConnectionReleaseHeader, ns3::RrcConnectionReestablishmentRejectHeader, ns3::RrcConnectionReestablishmentCompleteHeader, ns3::RrcConnectionReestablishmentHeader, ns3::RrcConnectionReestablishmentRequestHeader, ns3::HandoverPreparationInfoHeader, ns3::RrcConnectionReconfigurationHeader, ns3::RrcConnectionReconfigurationCompleteHeader, ns3::RrcConnectionSetupCompleteHeader, ns3::RrcConnectionSetupHeader, ns3::RrcConnectionRequestHeader, ns3::RrcDlCcchMessage, ns3::RrcUlCcchMessage, ns3::RrcDlDcchMessage, and ns3::RrcUlDcchMessage.
Referenced by ns3::Packet::PeekHeader(), and ns3::Packet::RemoveHeader().
Deserialize() [3/3]
uint32_t ns3::Chunk::Deserialize
Deserialize the object from a buffer iterator.
This version of Deserialize must be used when the Chunk has a variable size, because the bounds of the Chunk may not be known at the point of deserialization (e.g. a sequence of TLV fields).
The size of the chunk should be start.GetDistanceFrom (end);
Parameters
start the starting point
end the ending point
Returns
the number of deserialized bytes
Definition at line 68 of file chunk.cc.
GetSerializedSize()
virtual uint32_t ns3::Header::GetSerializedSize (void) const pure virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implemented in ns3::E2eStatsHeader, BenchHeader< N >, ns3::Tlv, ns3::WimaxMacToMacHeader, ns3::FragmentationSubheader, ns3::GrantManagementSubheader, ns3::BandwidthRequestHeader, ns3::GenericMacHeader, ns3::MacHeaderType, ns3::UlMap, ns3::Ucd, ns3::OfdmDownlinkFramePrefix, ns3::RngReq, ns3::DsaAck, ns3::DsaRsp, ns3::DsaReq, ns3::RngRsp, ns3::ManagementMessageType, ns3::DlMap, ns3::Dcd, ns3::HeSigHeader, ns3::VhtSigHeader, ns3::HtSigHeader, ns3::LSigHeader, ns3::DsssSigHeader, ns3::WifiMacHeader, ns3::MgtDelBaHeader, ns3::MgtAddBaResponseHeader, ns3::MgtAddBaRequestHeader, ns3::MgtProbeResponseHeader, ns3::MgtProbeRequestHeader, ns3::MgtAssocResponseHeader, ns3::MgtReassocRequestHeader, ns3::MgtAssocRequestHeader, ns3::CtrlBAckResponseHeader, ns3::CtrlBAckRequestHeader, ns3::AmsduSubframeHeader, ns3::AmpduSubframeHeader, ns3::VendorSpecificActionHeader, ns3::UanHeaderRcAck, ns3::UanHeaderRcCts, ns3::UanHeaderRcCtsGlobal, ns3::UanHeaderRcRts, ns3::UanHeaderRcData, ns3::UanHeaderCommon, ns3::AlohaNoackMacHeader, ns3::SixLowPanMesh, ns3::SixLowPanBc0, ns3::SixLowPanUdpNhcExtension, ns3::SixLowPanNhcExtension, ns3::SixLowPanIphc, ns3::SixLowPanIpv6, ns3::SixLowPanFragN, ns3::SixLowPanFrag1, ns3::SixLowPanHc1, ns3::PppHeader, ns3::olsr::MessageHeader, ns3::olsr::PacketHeader, ns3::SllHeader, ns3::RadiotapHeader, ns3::PbbPacket, ns3::LlcSnapHeader, ns3::EthernetHeader, anonymous_namespace{packet-test-suite.cc}::ATestHeader< N >, anonymous_namespace{packet-metadata-test.cc}::HistoryHeader< N >, MyHeader, ns3::flame::FlameHeader, ns3::IdealHandoverCommandHeader, ns3::IdealHandoverPreparationInfoHeader, ns3::LteRlcHeader, ns3::LteRlcAmHeader, ns3::LtePdcpHeader, ns3::Asn1Header, ns3::EpcX2ResourceStatusUpdateHeader, ns3::EpcX2LoadInformationHeader, ns3::EpcX2UeContextReleaseHeader, ns3::EpcX2SnStatusTransferHeader, ns3::EpcX2HandoverPreparationFailureHeader, ns3::EpcX2HandoverRequestAckHeader, ns3::EpcX2HandoverRequestHeader, ns3::EpcX2Header, ns3::GtpuHeader, ns3::GtpcDeleteBearerResponseMessage, ns3::GtpcDeleteBearerRequestMessage, ns3::GtpcDeleteBearerCommandMessage, ns3::GtpcModifyBearerResponseMessage, ns3::GtpcModifyBearerRequestMessage, ns3::GtpcCreateSessionResponseMessage, ns3::GtpcCreateSessionRequestMessage, ns3::GtpcHeader, ns3::CommandPayloadHeader, ns3::BeaconPayloadHeader, ns3::LrWpanMacHeader, ns3::lorawan::LorawanMacHeader, ns3::lorawan::LoraFrameHeader, ns3::UdpHeader, ns3::TcpHeader, ns3::RipNgHeader, ns3::RipNgRte, ns3::RipHeader, ns3::RipRte, ns3::Ipv6Header, ns3::Ipv4Header, ns3::Icmpv4TimeExceeded, ns3::Icmpv4DestinationUnreachable, ns3::Icmpv4Echo, ns3::Icmpv4Header, ns3::ArpHeader, ns3::DhcpHeader, ns3::SeqTsHeader, ns3::WifiInformationElementVector, ns3::WifiActionHeader, ns3::dot11s::PeerLinkConfirmStart, ns3::dot11s::PeerLinkCloseStart, ns3::dot11s::PeerLinkOpenStart, ns3::dot11s::MeshHeader, OptionWithAlignmentHeader, OptionWithoutAlignmentHeader, ns3::Ipv6OptionRouterAlertHeader, ns3::Ipv6OptionJumbogramHeader, ns3::Ipv6OptionPadnHeader, ns3::Ipv6OptionPad1Header, ns3::Ipv6OptionHeader, ns3::Ipv6ExtensionAHHeader, ns3::Ipv6ExtensionESPHeader, ns3::Ipv6ExtensionLooseRoutingHeader, ns3::Ipv6ExtensionRoutingHeader, ns3::Ipv6ExtensionFragmentHeader, ns3::Ipv6ExtensionDestinationHeader, ns3::Ipv6ExtensionHopByHopHeader, ns3::Ipv6ExtensionHeader, ns3::Icmpv6OptionRedirected, ns3::Icmpv6OptionLinkLayerAddress, ns3::Icmpv6OptionPrefixInformation, ns3::Icmpv6OptionMtu, ns3::Icmpv6ParameterError, ns3::Icmpv6TimeExceeded, ns3::Icmpv6TooBig, ns3::Icmpv6DestinationUnreachable, ns3::Icmpv6Echo, ns3::Icmpv6Redirection, ns3::Icmpv6RS, ns3::Icmpv6RA, ns3::Icmpv6NA, ns3::Icmpv6NS, ns3::Icmpv6OptionHeader, ns3::Icmpv6Header, ns3::dsr::DsrOptionAckHeader, ns3::dsr::DsrOptionAckReqHeader, ns3::dsr::DsrOptionRerrUnsupportHeader, ns3::dsr::DsrOptionRerrUnreachHeader, ns3::dsr::DsrOptionRerrHeader, ns3::dsr::DsrOptionSRHeader, ns3::dsr::DsrOptionRrepHeader, ns3::dsr::DsrOptionRreqHeader, ns3::dsr::DsrOptionPadnHeader, ns3::dsr::DsrOptionPad1Header, ns3::dsr::DsrOptionHeader, ns3::dsr::DsrRoutingHeader, ns3::dsr::DsrFsHeader, ns3::dsdv::DsdvHeader, ns3::ThreeGppHttpHeader, ns3::aodv::RerrHeader, ns3::aodv::RrepAckHeader, ns3::aodv::RrepHeader, ns3::aodv::RreqHeader, and ns3::aodv::TypeHeader.
Referenced by ns3::Packet::AddHeader(), and ns3::PcapFile::Write().
GetTypeId()
TypeId ns3::Header::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 36 of file header.cc.
References ns3::TypeId::SetParent().
Referenced by ns3::PacketMetadata::ItemIterator::Next().
Print()
virtual void ns3::Header::Print (std::ostream & os) const pure virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Chunk.
Implemented in ns3::E2eStatsHeader, ns3::Asn1Header, BenchHeader< N >, ns3::Tlv, ns3::WimaxMacToMacHeader, ns3::FragmentationSubheader, ns3::GrantManagementSubheader, ns3::BandwidthRequestHeader, ns3::GenericMacHeader, ns3::MacHeaderType, ns3::UlMap, ns3::Ucd, ns3::OfdmDownlinkFramePrefix, ns3::RngReq, ns3::DsaAck, ns3::DsaRsp, ns3::DsaReq, ns3::RngRsp, ns3::ManagementMessageType, ns3::DlMap, ns3::Dcd, ns3::HeSigHeader, ns3::VhtSigHeader, ns3::HtSigHeader, ns3::LSigHeader, ns3::DsssSigHeader, ns3::WifiMacHeader, ns3::WifiInformationElementVector, ns3::MgtDelBaHeader, ns3::MgtAddBaResponseHeader, ns3::MgtAddBaRequestHeader, ns3::WifiActionHeader, ns3::MgtProbeResponseHeader, ns3::MgtProbeRequestHeader, ns3::MgtAssocResponseHeader, ns3::MgtReassocRequestHeader, ns3::MgtAssocRequestHeader, ns3::CtrlBAckResponseHeader, ns3::CtrlBAckRequestHeader, ns3::AmsduSubframeHeader, ns3::AmpduSubframeHeader, ns3::VendorSpecificActionHeader, ns3::UanHeaderRcAck, ns3::UanHeaderRcCts, ns3::UanHeaderRcCtsGlobal, ns3::UanHeaderRcRts, ns3::UanHeaderRcData, ns3::UanHeaderCommon, ns3::AlohaNoackMacHeader, ns3::SixLowPanMesh, ns3::SixLowPanBc0, ns3::SixLowPanUdpNhcExtension, ns3::SixLowPanNhcExtension, ns3::SixLowPanIphc, ns3::SixLowPanIpv6, ns3::SixLowPanFragN, ns3::SixLowPanFrag1, ns3::SixLowPanHc1, ns3::PppHeader, ns3::olsr::MessageHeader, ns3::olsr::PacketHeader, ns3::SllHeader, ns3::RadiotapHeader, ns3::PbbPacket, ns3::LlcSnapHeader, ns3::EthernetHeader, anonymous_namespace{packet-test-suite.cc}::ATestHeader< N >, anonymous_namespace{packet-metadata-test.cc}::HistoryHeader< N >, MyHeader, ns3::flame::FlameHeader, ns3::dot11s::PeerLinkConfirmStart, ns3::dot11s::PeerLinkCloseStart, ns3::dot11s::PeerLinkOpenStart, ns3::dot11s::MeshHeader, ns3::IdealHandoverCommandHeader, ns3::IdealHandoverPreparationInfoHeader, ns3::MeasurementReportHeader, ns3::RrcConnectionRejectHeader, ns3::RrcConnectionReleaseHeader, ns3::RrcConnectionReestablishmentRejectHeader, ns3::RrcConnectionReestablishmentCompleteHeader, ns3::RrcConnectionReestablishmentHeader, ns3::RrcConnectionReestablishmentRequestHeader, ns3::HandoverPreparationInfoHeader, ns3::RrcConnectionReconfigurationHeader, ns3::RrcConnectionReconfigurationCompleteHeader, ns3::RrcConnectionSetupCompleteHeader, ns3::RrcConnectionSetupHeader, ns3::RrcConnectionRequestHeader, ns3::RrcDlCcchMessage, ns3::RrcUlCcchMessage, ns3::RrcDlDcchMessage, ns3::RrcUlDcchMessage, ns3::RrcAsn1Header, ns3::LteRlcHeader, ns3::LteRlcAmHeader, ns3::LtePdcpHeader, ns3::EpcX2ResourceStatusUpdateHeader, ns3::EpcX2LoadInformationHeader, ns3::EpcX2UeContextReleaseHeader, ns3::EpcX2SnStatusTransferHeader, ns3::EpcX2HandoverPreparationFailureHeader, ns3::EpcX2HandoverRequestAckHeader, ns3::EpcX2HandoverRequestHeader, ns3::EpcX2Header, ns3::GtpuHeader, ns3::GtpcDeleteBearerResponseMessage, ns3::GtpcDeleteBearerRequestMessage, ns3::GtpcDeleteBearerCommandMessage, ns3::GtpcModifyBearerResponseMessage, ns3::GtpcModifyBearerRequestMessage, ns3::GtpcCreateSessionResponseMessage, ns3::GtpcCreateSessionRequestMessage, ns3::GtpcHeader, ns3::CommandPayloadHeader, ns3::BeaconPayloadHeader, ns3::LrWpanMacHeader, ns3::lorawan::LorawanMacHeader, ns3::lorawan::LoraFrameHeader, ns3::UdpHeader, ns3::TcpHeader, ns3::RipNgHeader, ns3::RipNgRte, ns3::RipHeader, ns3::RipRte, ns3::Ipv6OptionRouterAlertHeader, ns3::Ipv6OptionJumbogramHeader, ns3::Ipv6OptionPadnHeader, ns3::Ipv6OptionPad1Header, ns3::Ipv6OptionHeader, ns3::Ipv6Header, ns3::Ipv6ExtensionAHHeader, ns3::Ipv6ExtensionESPHeader, ns3::Ipv6ExtensionLooseRoutingHeader, ns3::Ipv6ExtensionRoutingHeader, ns3::Ipv6ExtensionFragmentHeader, ns3::Ipv6ExtensionDestinationHeader, ns3::Ipv6ExtensionHopByHopHeader, ns3::Ipv6ExtensionHeader, ns3::Ipv4Header, ns3::Icmpv6OptionRedirected, ns3::Icmpv6OptionLinkLayerAddress, ns3::Icmpv6OptionPrefixInformation, ns3::Icmpv6OptionMtu, ns3::Icmpv6ParameterError, ns3::Icmpv6TimeExceeded, ns3::Icmpv6TooBig, ns3::Icmpv6DestinationUnreachable, ns3::Icmpv6Echo, ns3::Icmpv6Redirection, ns3::Icmpv6RS, ns3::Icmpv6RA, ns3::Icmpv6NA, ns3::Icmpv6NS, ns3::Icmpv6OptionHeader, ns3::Icmpv6Header, ns3::Icmpv4TimeExceeded, ns3::Icmpv4DestinationUnreachable, ns3::Icmpv4Echo, ns3::Icmpv4Header, ns3::ArpHeader, ns3::DhcpHeader, ns3::dsr::DsrOptionAckHeader, ns3::dsr::DsrOptionAckReqHeader, ns3::dsr::DsrOptionRerrUnsupportHeader, ns3::dsr::DsrOptionRerrUnreachHeader, ns3::dsr::DsrOptionRerrHeader, ns3::dsr::DsrOptionSRHeader, ns3::dsr::DsrOptionRrepHeader, ns3::dsr::DsrOptionRreqHeader, ns3::dsr::DsrOptionPadnHeader, ns3::dsr::DsrOptionPad1Header, ns3::dsr::DsrOptionHeader, ns3::dsr::DsrRoutingHeader, ns3::dsr::DsrFsHeader, ns3::dsdv::DsdvHeader, ns3::ThreeGppHttpHeader, ns3::SeqTsHeader, ns3::aodv::RerrHeader, ns3::aodv::RrepAckHeader, ns3::aodv::RrepHeader, ns3::aodv::RreqHeader, and ns3::aodv::TypeHeader.
Referenced by ns3::operator<<().
Serialize()
virtual void ns3::Header::Serialize (Buffer::Iterator start) const pure virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implemented in ns3::E2eStatsHeader, BenchHeader< N >, ns3::Tlv, ns3::WimaxMacToMacHeader, ns3::FragmentationSubheader, ns3::GrantManagementSubheader, ns3::BandwidthRequestHeader, ns3::GenericMacHeader, ns3::MacHeaderType, ns3::UlMap, ns3::Ucd, ns3::OfdmDownlinkFramePrefix, ns3::RngReq, ns3::DsaAck, ns3::DsaRsp, ns3::DsaReq, ns3::RngRsp, ns3::ManagementMessageType, ns3::DlMap, ns3::Dcd, ns3::HeSigHeader, ns3::VhtSigHeader, ns3::HtSigHeader, ns3::LSigHeader, ns3::DsssSigHeader, ns3::WifiMacHeader, ns3::WifiInformationElementVector, ns3::MgtDelBaHeader, ns3::MgtAddBaResponseHeader, ns3::MgtAddBaRequestHeader, ns3::WifiActionHeader, ns3::MgtProbeResponseHeader, ns3::MgtProbeRequestHeader, ns3::MgtAssocResponseHeader, ns3::MgtReassocRequestHeader, ns3::MgtAssocRequestHeader, ns3::CtrlBAckResponseHeader, ns3::CtrlBAckRequestHeader, ns3::AmsduSubframeHeader, ns3::AmpduSubframeHeader, ns3::VendorSpecificActionHeader, ns3::UanHeaderRcAck, ns3::UanHeaderRcCts, ns3::UanHeaderRcCtsGlobal, ns3::UanHeaderRcRts, ns3::UanHeaderRcData, ns3::UanHeaderCommon, ns3::AlohaNoackMacHeader, ns3::SixLowPanMesh, ns3::SixLowPanBc0, ns3::SixLowPanUdpNhcExtension, ns3::SixLowPanNhcExtension, ns3::SixLowPanIphc, ns3::SixLowPanIpv6, ns3::SixLowPanFragN, ns3::SixLowPanFrag1, ns3::SixLowPanHc1, ns3::PppHeader, ns3::olsr::MessageHeader, ns3::olsr::PacketHeader, ns3::SllHeader, ns3::RadiotapHeader, ns3::PbbPacket, ns3::LlcSnapHeader, ns3::EthernetHeader, anonymous_namespace{packet-metadata-test.cc}::HistoryHeader< N >, MyHeader, ns3::flame::FlameHeader, ns3::dot11s::PeerLinkConfirmStart, ns3::dot11s::PeerLinkCloseStart, ns3::dot11s::PeerLinkOpenStart, ns3::dot11s::MeshHeader, ns3::IdealHandoverCommandHeader, ns3::IdealHandoverPreparationInfoHeader, ns3::LteRlcHeader, ns3::LteRlcAmHeader, ns3::LtePdcpHeader, ns3::EpcX2ResourceStatusUpdateHeader, ns3::EpcX2LoadInformationHeader, ns3::EpcX2UeContextReleaseHeader, ns3::EpcX2SnStatusTransferHeader, ns3::EpcX2HandoverPreparationFailureHeader, ns3::EpcX2HandoverRequestAckHeader, ns3::EpcX2HandoverRequestHeader, ns3::EpcX2Header, ns3::GtpuHeader, ns3::GtpcDeleteBearerResponseMessage, ns3::GtpcDeleteBearerRequestMessage, ns3::GtpcDeleteBearerCommandMessage, ns3::GtpcModifyBearerResponseMessage, ns3::GtpcModifyBearerRequestMessage, ns3::GtpcCreateSessionResponseMessage, ns3::GtpcCreateSessionRequestMessage, ns3::GtpcHeader, ns3::CommandPayloadHeader, ns3::BeaconPayloadHeader, ns3::LrWpanMacHeader, ns3::lorawan::LorawanMacHeader, ns3::lorawan::LoraFrameHeader, OptionWithAlignmentHeader, OptionWithoutAlignmentHeader, ns3::UdpHeader, ns3::TcpHeader, ns3::RipNgHeader, ns3::RipNgRte, ns3::RipHeader, ns3::RipRte, ns3::Ipv6OptionRouterAlertHeader, ns3::Ipv6OptionJumbogramHeader, ns3::Ipv6OptionPadnHeader, ns3::Ipv6OptionPad1Header, ns3::Ipv6OptionHeader, ns3::Ipv6Header, ns3::Ipv6ExtensionAHHeader, ns3::Ipv6ExtensionESPHeader, ns3::Ipv6ExtensionLooseRoutingHeader, ns3::Ipv6ExtensionRoutingHeader, ns3::Ipv6ExtensionFragmentHeader, ns3::Ipv6ExtensionDestinationHeader, ns3::Ipv6ExtensionHopByHopHeader, ns3::Ipv6ExtensionHeader, ns3::Ipv4Header, ns3::Icmpv6OptionRedirected, ns3::Icmpv6OptionLinkLayerAddress, ns3::Icmpv6OptionPrefixInformation, ns3::Icmpv6OptionMtu, ns3::Icmpv6ParameterError, ns3::Icmpv6TimeExceeded, ns3::Icmpv6TooBig, ns3::Icmpv6DestinationUnreachable, ns3::Icmpv6Echo, ns3::Icmpv6Redirection, ns3::Icmpv6RS, ns3::Icmpv6RA, ns3::Icmpv6NA, ns3::Icmpv6NS, ns3::Icmpv6OptionHeader, ns3::Icmpv6Header, ns3::Icmpv4TimeExceeded, ns3::Icmpv4DestinationUnreachable, ns3::Icmpv4Echo, ns3::Icmpv4Header, ns3::ArpHeader, ns3::DhcpHeader, ns3::dsr::DsrOptionAckHeader, ns3::dsr::DsrOptionAckReqHeader, ns3::dsr::DsrOptionRerrUnsupportHeader, ns3::dsr::DsrOptionRerrUnreachHeader, ns3::dsr::DsrOptionRerrHeader, ns3::dsr::DsrOptionSRHeader, ns3::dsr::DsrOptionRrepHeader, ns3::dsr::DsrOptionRreqHeader, ns3::dsr::DsrOptionPadnHeader, ns3::dsr::DsrOptionPad1Header, ns3::dsr::DsrOptionHeader, ns3::dsr::DsrRoutingHeader, ns3::dsr::DsrFsHeader, ns3::dsdv::DsdvHeader, ns3::ThreeGppHttpHeader, ns3::SeqTsHeader, ns3::aodv::RrepAckHeader, ns3::aodv::RrepHeader, ns3::aodv::RreqHeader, ns3::aodv::TypeHeader, anonymous_namespace{packet-test-suite.cc}::ATestHeader< N >, ns3::aodv::RerrHeader, and ns3::Asn1Header.
Referenced by ns3::Packet::AddHeader(), and ns3::PcapFile::Write().
The documentation for this class was generated from the following files:
src/network/model/header.h
src/network/model/header.cc