ns-3: MyHeader Class Reference
MyHeader Class Reference
Network
Public Member Functions
MyHeader ()
virtual ~MyHeader ()
virtual uint32_t Deserialize (Buffer::Iterator start)
uint16_t GetData (void) const
Get the header data.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetData (uint16_t data)
Set the header data.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint16_t m_data
Header data.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A simple example of an Header implementation
Definition at line 13 of file main-packet-header.cc.
Constructor & Destructor Documentation
MyHeader()
MyHeader::MyHeader ()
Definition at line 45 of file main-packet-header.cc.
~MyHeader()
MyHeader::~MyHeader () virtual
Definition at line 50 of file main-packet-header.cc.
Member Function Documentation
Deserialize()
uint32_t MyHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 91 of file main-packet-header.cc.
References visualizer.core::start().
GetData()
uint16_t MyHeader::GetData (void) const
Get the header data.
Returns
The data.
Definition at line 108 of file main-packet-header.cc.
GetInstanceTypeId()
TypeId MyHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 64 of file main-packet-header.cc.
GetSerializedSize()
uint32_t MyHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 78 of file main-packet-header.cc.
GetTypeId()
TypeId MyHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 55 of file main-packet-header.cc.
References ns3::TypeId::SetParent().
Print()
void MyHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 70 of file main-packet-header.cc.
Serialize()
void MyHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 84 of file main-packet-header.cc.
References visualizer.core::start().
SetData()
void MyHeader::SetData (uint16_t data)
Set the header data.
Parameters
data The data.
Definition at line 103 of file main-packet-header.cc.
References data.
Member Data Documentation
m_data
uint16_t MyHeader::m_data private
Header data.
Definition at line 42 of file main-packet-header.cc.
The documentation for this class was generated from the following file:
src/network/examples/main-packet-header.cc