ns-3: ns3::OfdmDlBurstProfile Class Reference
ns3::OfdmDlBurstProfile Class Reference
This class implements the OFDM Downlink burst profile descriptor as described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems" 8.2.1.10 Burst profile formats page 416.
#include "dl-mac-messages.h"
Public Types
enum Diuc {
DIUC_STC_ZONE = 0, DIUC_BURST_PROFILE_1, DIUC_BURST_PROFILE_2, DIUC_BURST_PROFILE_3,
DIUC_BURST_PROFILE_4, DIUC_BURST_PROFILE_5, DIUC_BURST_PROFILE_6, DIUC_BURST_PROFILE_7,
DIUC_BURST_PROFILE_8, DIUC_BURST_PROFILE_9, DIUC_BURST_PROFILE_10, DIUC_BURST_PROFILE_11,
DIUC_GAP = 13, DIUC_END_OF_MAP
}
DIUC enumeration.
Public Member Functions
OfdmDlBurstProfile (void)
~OfdmDlBurstProfile (void)
uint8_t GetDiuc (void) const
uint8_t GetFecCodeType (void) const
uint8_t GetLength (void) const
uint16_t GetSize (void) const
uint8_t GetType (void) const
Get type function.
Buffer::Iterator Read (Buffer::Iterator start)
Read item.
void SetDiuc (uint8_t diuc)
Set DIUC field.
void SetFecCodeType (uint8_t fecCodeType)
Set FEC code type.
void SetLength (uint8_t length)
Set length field.
void SetType (uint8_t type)
Set type field.
Buffer::Iterator Write (Buffer::Iterator start) const
Write item.
Private Attributes
uint8_t m_diuc
diuc
uint8_t m_fecCodeType
FEC code type.
uint8_t m_length
length
uint8_t m_type
type
Detailed Description
This class implements the OFDM Downlink burst profile descriptor as described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems" 8.2.1.10 Burst profile formats page 416.
Definition at line 250 of file dl-mac-messages.h.
Member Enumeration Documentation
Diuc
enum ns3::OfdmDlBurstProfile::Diuc
DIUC enumeration.
Enumerator
DIUC_STC_ZONE
DIUC_BURST_PROFILE_1
DIUC_BURST_PROFILE_2
DIUC_BURST_PROFILE_3
DIUC_BURST_PROFILE_4
DIUC_BURST_PROFILE_5
DIUC_BURST_PROFILE_6
DIUC_BURST_PROFILE_7
DIUC_BURST_PROFILE_8
DIUC_BURST_PROFILE_9
DIUC_BURST_PROFILE_10
DIUC_BURST_PROFILE_11
DIUC_GAP
DIUC_END_OF_MAP
Definition at line 254 of file dl-mac-messages.h.
Constructor & Destructor Documentation
OfdmDlBurstProfile()
ns3::OfdmDlBurstProfile::OfdmDlBurstProfile (void)
Definition at line 225 of file dl-mac-messages.cc.
~OfdmDlBurstProfile()
ns3::OfdmDlBurstProfile::~OfdmDlBurstProfile (void)
Definition at line 233 of file dl-mac-messages.cc.
Member Function Documentation
GetDiuc()
uint8_t ns3::OfdmDlBurstProfile::GetDiuc (void) const
Returns
the DIUC field
Definition at line 274 of file dl-mac-messages.cc.
References m_diuc.
Referenced by ns3::SubscriberStationNetDevice::ProcessDcd().
GetFecCodeType()
uint8_t ns3::OfdmDlBurstProfile::GetFecCodeType (void) const
Returns
the FEC code type
Definition at line 280 of file dl-mac-messages.cc.
References m_fecCodeType.
Referenced by ns3::SubscriberStationNetDevice::ProcessDcd().
GetLength()
uint8_t ns3::OfdmDlBurstProfile::GetLength (void) const
Returns
the length field
Definition at line 268 of file dl-mac-messages.cc.
References m_length.
GetSize()
uint16_t ns3::OfdmDlBurstProfile::GetSize (void) const
Returns
the size
Definition at line 286 of file dl-mac-messages.cc.
Referenced by ns3::Dcd::GetSerializedSize().
GetType()
uint8_t ns3::OfdmDlBurstProfile::GetType (void) const
Get type function.
Returns
the type
Definition at line 262 of file dl-mac-messages.cc.
References m_type.
Read()
Buffer::Iterator ns3::OfdmDlBurstProfile::Read (Buffer::Iterator start)
Read item.
Parameters
start the starting item iterator
Returns
the iterator
Definition at line 303 of file dl-mac-messages.cc.
References m_diuc, m_fecCodeType, m_length, m_type, ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
Referenced by ns3::Dcd::Deserialize().
SetDiuc()
void ns3::OfdmDlBurstProfile::SetDiuc (uint8_t diuc)
Set DIUC field.
Parameters
diuc the DIUC
Definition at line 250 of file dl-mac-messages.cc.
References m_diuc.
Referenced by ns3::SubscriberStationNetDevice::ProcessDcd(), and ns3::BaseStationNetDevice::SetDlBurstProfiles().
SetFecCodeType()
void ns3::OfdmDlBurstProfile::SetFecCodeType (uint8_t fecCodeType)
Set FEC code type.
Parameters
fecCodeType the FEC code type
Definition at line 256 of file dl-mac-messages.cc.
References m_fecCodeType.
Referenced by ns3::SubscriberStationNetDevice::ProcessDcd(), and ns3::BaseStationNetDevice::SetDlBurstProfiles().
SetLength()
void ns3::OfdmDlBurstProfile::SetLength (uint8_t length)
Set length field.
Parameters
length the length to set
Definition at line 244 of file dl-mac-messages.cc.
References m_length.
Referenced by ns3::BaseStationNetDevice::SetDlBurstProfiles().
SetType()
void ns3::OfdmDlBurstProfile::SetType (uint8_t type)
Set type field.
Parameters
type the type to set
Definition at line 238 of file dl-mac-messages.cc.
References m_type.
Referenced by ns3::BaseStationNetDevice::SetDlBurstProfiles().
Write()
Buffer::Iterator ns3::OfdmDlBurstProfile::Write (Buffer::Iterator start) const
Write item.
Parameters
start the starting item iterator
Returns
the iterator
Definition at line 292 of file dl-mac-messages.cc.
References m_diuc, m_fecCodeType, m_length, m_type, visualizer.core::start(), and ns3::Buffer::Iterator::WriteU8().
Referenced by ns3::Dcd::Serialize().
Member Data Documentation
m_diuc
uint8_t ns3::OfdmDlBurstProfile::m_diuc private
diuc
Definition at line 329 of file dl-mac-messages.h.
Referenced by GetDiuc(), Read(), SetDiuc(), and Write().
m_fecCodeType
uint8_t ns3::OfdmDlBurstProfile::m_fecCodeType private
FEC code type.
Definition at line 332 of file dl-mac-messages.h.
Referenced by GetFecCodeType(), Read(), SetFecCodeType(), and Write().
m_length
uint8_t ns3::OfdmDlBurstProfile::m_length private
length
Definition at line 328 of file dl-mac-messages.h.
Referenced by GetLength(), Read(), SetLength(), and Write().
m_type
uint8_t ns3::OfdmDlBurstProfile::m_type private
type
Definition at line 327 of file dl-mac-messages.h.
Referenced by GetType(), Read(), SetType(), and Write().
The documentation for this class was generated from the following files:
src/wimax/model/dl-mac-messages.h
src/wimax/model/dl-mac-messages.cc