ns-3: ns3::Icmpv6OptionHeader Class Reference
ns3::Icmpv6OptionHeader Class Reference
Internet » IPv6 classes and sub-modules » ICMPv6 protocol and associated headers.
ICMPv6 option header.
#include "icmpv6-header.h"
Public Member Functions
Icmpv6OptionHeader ()
Constructor.
virtual ~Icmpv6OptionHeader ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
uint8_t GetLength () const
Get the length of the option in 8 bytes unit.
virtual uint32_t GetSerializedSize () const
Get the serialized size.
uint8_t GetType () const
Get the type of the option.
virtual void Print (std::ostream &os) const
Print information.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetLength (uint8_t len)
Set the length of the option.
void SetType (uint8_t type)
Set the type of the option.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the UID of this class.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_len
The length.
uint8_t m_type
The type.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
ICMPv6 option header.
Definition at line 238 of file icmpv6-header.h.
Constructor & Destructor Documentation
Icmpv6OptionHeader()
ns3::Icmpv6OptionHeader::Icmpv6OptionHeader ()
Constructor.
Todo:
Definition at line 1482 of file icmpv6-header.cc.
References m_len, m_type, and NS_LOG_FUNCTION.
~Icmpv6OptionHeader()
ns3::Icmpv6OptionHeader::~Icmpv6OptionHeader () virtual
Destructor.
Definition at line 1490 of file icmpv6-header.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Deserialize()
uint32_t ns3::Icmpv6OptionHeader::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start start offset
Returns
length of packet
Implements ns3::Header.
Reimplemented in ns3::Icmpv6OptionRedirected, ns3::Icmpv6OptionLinkLayerAddress, ns3::Icmpv6OptionPrefixInformation, and ns3::Icmpv6OptionMtu.
Definition at line 1531 of file icmpv6-header.cc.
References GetSerializedSize(), NS_LOG_FUNCTION, and visualizer.core::start().
GetInstanceTypeId()
TypeId ns3::Icmpv6OptionHeader::GetInstanceTypeId () const virtual
Get the instance type ID.
Returns
instance type ID
Implements ns3::ObjectBase.
Reimplemented in ns3::Icmpv6OptionLinkLayerAddress, ns3::Icmpv6OptionRedirected, ns3::Icmpv6OptionPrefixInformation, and ns3::Icmpv6OptionMtu.
Definition at line 1475 of file icmpv6-header.cc.
References GetTypeId(), and NS_LOG_FUNCTION.
GetLength()
uint8_t ns3::Icmpv6OptionHeader::GetLength () const
Get the length of the option in 8 bytes unit.
Returns
length of the option
Definition at line 1507 of file icmpv6-header.cc.
References m_len, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6OptionLinkLayerAddress::Deserialize(), ns3::Icmpv6OptionRedirected::Deserialize(), ns3::Icmpv6OptionLinkLayerAddress::GetSerializedSize(), Print(), ns3::Icmpv6OptionMtu::Print(), ns3::Icmpv6OptionPrefixInformation::Print(), ns3::Icmpv6OptionLinkLayerAddress::Print(), ns3::Icmpv6OptionRedirected::Print(), ns3::Icmpv6OptionMtu::Serialize(), ns3::Icmpv6OptionPrefixInformation::Serialize(), ns3::Icmpv6OptionLinkLayerAddress::Serialize(), and ns3::Icmpv6OptionRedirected::Serialize().
GetSerializedSize()
uint32_t ns3::Icmpv6OptionHeader::GetSerializedSize () const virtual
Get the serialized size.
Returns
serialized size
Implements ns3::Header.
Reimplemented in ns3::Icmpv6OptionRedirected, ns3::Icmpv6OptionLinkLayerAddress, ns3::Icmpv6OptionPrefixInformation, and ns3::Icmpv6OptionMtu.
Definition at line 1525 of file icmpv6-header.cc.
References m_len, and NS_LOG_FUNCTION.
Referenced by Deserialize().
GetType()
uint8_t ns3::Icmpv6OptionHeader::GetType () const
Get the type of the option.
Returns
type
Definition at line 1495 of file icmpv6-header.cc.
References m_type, and NS_LOG_FUNCTION_NOARGS.
Referenced by Print(), ns3::Icmpv6OptionMtu::Print(), ns3::Icmpv6OptionPrefixInformation::Print(), ns3::Icmpv6OptionLinkLayerAddress::Print(), ns3::Icmpv6OptionRedirected::Print(), ns3::Icmpv6OptionMtu::Serialize(), ns3::Icmpv6OptionPrefixInformation::Serialize(), ns3::Icmpv6OptionLinkLayerAddress::Serialize(), and ns3::Icmpv6OptionRedirected::Serialize().
GetTypeId()
TypeId ns3::Icmpv6OptionHeader::GetTypeId () static
Get the UID of this class.
Returns
UID
Definition at line 1465 of file icmpv6-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::Icmpv6OptionHeader::Print (std::ostream & os) const virtual
Print information.
Parameters
os output stream
Implements ns3::Header.
Reimplemented in ns3::Icmpv6OptionRedirected, ns3::Icmpv6OptionLinkLayerAddress, ns3::Icmpv6OptionPrefixInformation, and ns3::Icmpv6OptionMtu.
Definition at line 1519 of file icmpv6-header.cc.
References GetLength(), GetType(), and NS_LOG_FUNCTION.
Serialize()
void ns3::Icmpv6OptionHeader::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start start offset
Implements ns3::Header.
Reimplemented in ns3::Icmpv6OptionRedirected, ns3::Icmpv6OptionLinkLayerAddress, ns3::Icmpv6OptionPrefixInformation, and ns3::Icmpv6OptionMtu.
Definition at line 1537 of file icmpv6-header.cc.
References NS_LOG_FUNCTION, and visualizer.core::start().
SetLength()
void ns3::Icmpv6OptionHeader::SetLength (uint8_t len)
Set the length of the option.
Parameters
len length value to set
Definition at line 1513 of file icmpv6-header.cc.
References m_len, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6OptionLinkLayerAddress::Icmpv6OptionLinkLayerAddress(), ns3::Icmpv6OptionMtu::Icmpv6OptionMtu(), ns3::Icmpv6OptionPrefixInformation::Icmpv6OptionPrefixInformation(), ns3::Icmpv6OptionMtu::Deserialize(), ns3::Icmpv6OptionPrefixInformation::Deserialize(), ns3::Icmpv6OptionLinkLayerAddress::Deserialize(), ns3::Icmpv6OptionRedirected::Deserialize(), and ns3::Icmpv6OptionRedirected::SetPacket().
SetType()
void ns3::Icmpv6OptionHeader::SetType (uint8_t type)
Set the type of the option.
Parameters
type the type to set
Definition at line 1501 of file icmpv6-header.cc.
References m_type, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6OptionLinkLayerAddress::Icmpv6OptionLinkLayerAddress(), ns3::Icmpv6OptionMtu::Icmpv6OptionMtu(), ns3::Icmpv6OptionPrefixInformation::Icmpv6OptionPrefixInformation(), ns3::Icmpv6OptionRedirected::Icmpv6OptionRedirected(), ns3::Icmpv6OptionMtu::Deserialize(), ns3::Icmpv6OptionPrefixInformation::Deserialize(), ns3::Icmpv6OptionLinkLayerAddress::Deserialize(), and ns3::Icmpv6OptionRedirected::Deserialize().
Member Data Documentation
m_len
uint8_t ns3::Icmpv6OptionHeader::m_len private
The length.
Definition at line 321 of file icmpv6-header.h.
Referenced by Icmpv6OptionHeader(), GetLength(), GetSerializedSize(), and SetLength().
m_type
uint8_t ns3::Icmpv6OptionHeader::m_type private
The type.
Definition at line 316 of file icmpv6-header.h.
Referenced by Icmpv6OptionHeader(), GetType(), and SetType().
The documentation for this class was generated from the following files:
src/internet/model/icmpv6-header.h
src/internet/model/icmpv6-header.cc