ns-3: ns3::PacketLossCounter Class Reference
ns3::PacketLossCounter Class Reference
Applications » UdpClientServer
A class to count the number of lost packets.
#include "packet-loss-counter.h"
Public Member Functions
PacketLossCounter (uint8_t bitmapSize)
Constructor.
~PacketLossCounter ()
uint16_t GetBitMapSize (void) const
Return the size of the window used to compute the packet loss.
uint32_t GetLost (void) const
Get the number of lost packets.
void NotifyReceived (uint32_t seq)
Record a successfully received packet.
void SetBitMapSize (uint16_t size)
Set the size of the window used to compute the packet loss.
Private Member Functions
bool GetBit (uint32_t seqNum)
Check if a sequence number in the window has been received.
void SetBit (uint32_t seqNum, bool val)
Set a sequence number to a given state.
Private Attributes
uint16_t m_bitMapSize
Window size.
uint32_t m_lastMaxSeqNum
Last sequence number seen.
uint32_t m_lost
Lost packets counter.
uint8_t * m_receiveBitMap
Received packets in the window size.
Detailed Description
A class to count the number of lost packets.
This class records the packet lost in a client/server transmission leveraging a sequence number. All the packets outside a given window (i.e., too old with respect to the last sequence number seen) are considered lost,
Definition at line 45 of file packet-loss-counter.h.
Constructor & Destructor Documentation
PacketLossCounter()
ns3::PacketLossCounter::PacketLossCounter (uint8_t bitmapSize)
Constructor.
Parameters
bitmapSize The window size. Must be a multiple of 8.
Definition at line 31 of file packet-loss-counter.cc.
References NS_LOG_FUNCTION, and SetBitMapSize().
~PacketLossCounter()
ns3::PacketLossCounter::~PacketLossCounter ()
Definition at line 41 of file packet-loss-counter.cc.
References m_receiveBitMap, and NS_LOG_FUNCTION.
Member Function Documentation
GetBit()
bool ns3::PacketLossCounter::GetBit (uint32_t seqNum) private
Check if a sequence number in the window has been received.
Parameters
seqNum the sequence number.
Returns
false if the packet has not been received.
Definition at line 77 of file packet-loss-counter.cc.
References m_bitMapSize, m_receiveBitMap, and NS_LOG_FUNCTION.
Referenced by NotifyReceived().
GetBitMapSize()
uint16_t ns3::PacketLossCounter::GetBitMapSize (void) const
Return the size of the window used to compute the packet loss.
Returns
the window size.
Definition at line 48 of file packet-loss-counter.cc.
References m_bitMapSize, and NS_LOG_FUNCTION.
Referenced by ns3::UdpServer::GetPacketWindowSize().
GetLost()
uint32_t ns3::PacketLossCounter::GetLost (void) const
Get the number of lost packets.
Returns
the number of lost packets.
Definition at line 70 of file packet-loss-counter.cc.
References m_lost, and NS_LOG_FUNCTION.
Referenced by PacketLossCounterTestCase::DoRun(), and ns3::UdpServer::GetLost().
NotifyReceived()
void ns3::PacketLossCounter::NotifyReceived (uint32_t seq)
Record a successfully received packet.
Parameters
seq the packet sequence number
Definition at line 110 of file packet-loss-counter.cc.
References GetBit(), m_bitMapSize, m_lastMaxSeqNum, m_lost, NS_LOG_FUNCTION, NS_LOG_INFO, and SetBit().
Referenced by PacketLossCounterTestCase::DoRun(), and ns3::UdpServer::HandleRead().
SetBit()
void ns3::PacketLossCounter::SetBit (uint32_t seqNum, bool val) private
Set a sequence number to a given state.
Parameters
seqNum the sequence number.
val false if the packet has not been received.
Definition at line 84 of file packet-loss-counter.cc.
References m_bitMapSize, m_receiveBitMap, and NS_LOG_FUNCTION.
Referenced by NotifyReceived().
SetBitMapSize()
void ns3::PacketLossCounter::SetBitMapSize (uint16_t size)
Set the size of the window used to compute the packet loss.
Parameters
size The window size. Must be a multiple of 8.
Definition at line 55 of file packet-loss-counter.cc.
References m_bitMapSize, m_receiveBitMap, NS_ASSERT_MSG(), and NS_LOG_FUNCTION.
Referenced by PacketLossCounter(), and ns3::UdpServer::SetPacketWindowSize().
Member Data Documentation
m_bitMapSize
uint16_t ns3::PacketLossCounter::m_bitMapSize private
Window size.
Definition at line 90 of file packet-loss-counter.h.
Referenced by GetBit(), GetBitMapSize(), NotifyReceived(), SetBit(), and SetBitMapSize().
m_lastMaxSeqNum
uint32_t ns3::PacketLossCounter::m_lastMaxSeqNum private
Last sequence number seen.
Definition at line 91 of file packet-loss-counter.h.
Referenced by NotifyReceived().
m_lost
uint32_t ns3::PacketLossCounter::m_lost private
Lost packets counter.
Definition at line 89 of file packet-loss-counter.h.
Referenced by GetLost(), and NotifyReceived().
m_receiveBitMap
uint8_t* ns3::PacketLossCounter::m_receiveBitMap private
Received packets in the window size.
Definition at line 92 of file packet-loss-counter.h.
Referenced by ~PacketLossCounter(), GetBit(), SetBit(), and SetBitMapSize().
The documentation for this class was generated from the following files:
src/applications/model/packet-loss-counter.h
src/applications/model/packet-loss-counter.cc