ns-3: TcFlowControlTestCase Class Reference
TcFlowControlTestCase Class Reference
Traffic-control » traffic-control module tests | Test suites
Traffic Control Flow Control Test Case.
Public Member Functions
TcFlowControlTestCase (QueueSizeUnit tt)
Constructor.
virtual ~TcFlowControlTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CheckDeviceQueueStopped (Ptr< NetDevice > dev, bool value, const char *msg)
Check if the device queue is in the expected status (stopped or not)
void CheckPacketsInDeviceQueue (Ptr< NetDevice > dev, uint16_t nPackets, const char *msg)
Check if the device queue stores the expected number of packets.
void CheckPacketsInQueueDisc (Ptr< NetDevice > dev, uint16_t nPackets, const char *msg)
Check if the queue disc stores the expected number of packets.
virtual void DoRun (void)
Implementation to actually run this TestCase.
void SendPackets (Ptr< Node > n, uint16_t nPackets)
Instruct a node to send a specified number of packets.
Private Attributes
QueueSizeUnit m_type
the test type
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Traffic Control Flow Control Test Case.
Definition at line 99 of file tc-flow-control-test-suite.cc.
Constructor & Destructor Documentation
TcFlowControlTestCase()
TcFlowControlTestCase::TcFlowControlTestCase (QueueSizeUnit tt)
Constructor.
Parameters
tt the test type
Definition at line 141 of file tc-flow-control-test-suite.cc.
~TcFlowControlTestCase()
TcFlowControlTestCase::~TcFlowControlTestCase () virtual
Definition at line 147 of file tc-flow-control-test-suite.cc.
Member Function Documentation
CheckDeviceQueueStopped()
void TcFlowControlTestCase::CheckDeviceQueueStopped (Ptr< NetDevice > dev, bool value, const char * msg) private
Check if the device queue is in the expected status (stopped or not)
Parameters
dev the device
value the expected status of the queue (true means stopped)
msg the message to print if the status of the device queue is different
Definition at line 171 of file tc-flow-control-test-suite.cc.
References ns3::Object::GetObject(), ns3::NetDeviceQueueInterface::GetTxQueue(), NS_ASSERT_MSG(), and NS_TEST_EXPECT_MSG_EQ.
Referenced by DoRun().
CheckPacketsInDeviceQueue()
void TcFlowControlTestCase::CheckPacketsInDeviceQueue (Ptr< NetDevice > dev, uint16_t nPackets, const char * msg) private
Check if the device queue stores the expected number of packets.
Parameters
dev the device
nPackets the expected number of packets stored in the device queue
msg the message to print if a different number of packets are stored
Definition at line 162 of file tc-flow-control-test-suite.cc.
References ns3::PointerValue::Get(), ns3::ObjectBase::GetAttributeFailSafe(), and NS_TEST_EXPECT_MSG_EQ.
Referenced by DoRun().
CheckPacketsInQueueDisc()
void TcFlowControlTestCase::CheckPacketsInQueueDisc (Ptr< NetDevice > dev, uint16_t nPackets, const char * msg) private
Check if the queue disc stores the expected number of packets.
Parameters
dev the device the queue disc is installed on
nPackets the expected number of packets stored in the queue disc
msg the message to print if a different number of packets are stored
Definition at line 179 of file tc-flow-control-test-suite.cc.
References ns3::NetDevice::GetNode(), ns3::Object::GetObject(), ns3::TrafficControlLayer::GetRootQueueDiscOnDevice(), and NS_TEST_EXPECT_MSG_EQ.
Referenced by DoRun().
DoRun()
void TcFlowControlTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 188 of file tc-flow-control-test-suite.cc.
References CheckDeviceQueueStopped(), CheckPacketsInDeviceQueue(), CheckPacketsInQueueDisc(), ns3::NetDeviceContainer::Get(), ns3::TrafficControlHelper::Install(), ns3::SimpleNetDeviceHelper::Install(), m_type, ns3::MilliSeconds(), sample-rng-plot::n, ns3::PACKETS, ns3::Seconds(), SendPackets(), ns3::SimpleNetDeviceHelper::SetDeviceAttribute(), ns3::NetDevice::SetMtu(), and ns3::SimpleNetDeviceHelper::SetQueue().
SendPackets()
void TcFlowControlTestCase::SendPackets (Ptr< Node > n, uint16_t nPackets) private
Instruct a node to send a specified number of packets.
Parameters
n the node
nPackets the number of packets to send
Definition at line 152 of file tc-flow-control-test-suite.cc.
References sample-rng-plot::n, and ns3::TrafficControlLayer::Send().
Referenced by DoRun().
Member Data Documentation
m_type
QueueSizeUnit TcFlowControlTestCase::m_type private
the test type
Definition at line 138 of file tc-flow-control-test-suite.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/traffic-control/test/tc-flow-control-test-suite.cc