ns-3: ns3::lorawan::SimpleEndDeviceLoraPhy Class Reference
ns3::lorawan::SimpleEndDeviceLoraPhy Class Reference
Class representing a simple LoRa transceiver, with an error model based on receiver sensitivity and a SIR table.
#include "simple-end-device-lora-phy.h"
Public Member Functions
SimpleEndDeviceLoraPhy ()
virtual ~SimpleEndDeviceLoraPhy ()
virtual void EndReceive (Ptr< Packet > packet, Ptr< LoraInterferenceHelper::Event > event)
Finish reception of a packet.
virtual void Send (Ptr< Packet > packet, LoraTxParameters txParams, double frequencyMHz, double txPowerDbm)
Instruct the PHY to send a packet according to some parameters.
virtual void StartReceive (Ptr< Packet > packet, double rxPowerDbm, uint8_t sf, Time duration, double frequencyMHz)
Start receiving a packet.
Public Member Functions inherited from ns3::lorawan::EndDeviceLoraPhy
EndDeviceLoraPhy ()
virtual ~EndDeviceLoraPhy ()
uint8_t GetSpreadingFactor (void)
Get the Spreading Factor this EndDevice is listening for.
EndDeviceLoraPhy::State GetState (void)
Return the state this End Device is currently in.
virtual bool IsOnFrequency (double frequencyMHz)
Whether this device is listening on the specified frequency or not.
virtual bool IsTransmitting (void)
Whether this device is transmitting or not.
void RegisterListener (EndDeviceLoraPhyListener *listener)
Add the input listener to the list of objects to be notified of PHY-level events.
void SetFrequency (double frequencyMHz)
Set the frequency this EndDevice will listen on.
void SetSpreadingFactor (uint8_t sf)
Set the Spreading Factor this EndDevice will listen for.
void SwitchToSleep (void)
Switch to the SLEEP state.
void SwitchToStandby (void)
Switch to the STANDBY state.
void UnregisterListener (EndDeviceLoraPhyListener *listener)
Remove the input listener from the list of objects to be notified of PHY-level events.
Public Member Functions inherited from ns3::lorawan::LoraPhy
LoraPhy ()
Constructor and destructor.
virtual ~LoraPhy ()
Ptr< LoraChannel > GetChannel (void) const
Get the channel instance associated to this PHY.
Ptr< NetDevice > GetDevice (void) const
Get the NetDevice associated to this PHY.
Ptr< MobilityModel > GetMobility ()
Get the mobility model associated to this PHY.
void SetChannel (Ptr< LoraChannel > channel)
Set the LoraChannel instance PHY transmits on.
void SetDevice (Ptr< NetDevice > device)
Set the NetDevice that owns this PHY.
void SetMobility (Ptr< MobilityModel > mobility)
Set the mobility model associated to this PHY.
void SetReceiveFailedCallback (RxFailedCallback callback)
Set the callback to call upon failed reception of a packet we were previously locked on.
void SetReceiveOkCallback (RxOkCallback callback)
Set the callback to call upon successful reception of a packet.
void SetTxFinishedCallback (TxFinishedCallback callback)
Set the callback to call after transmission of a packet.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::lorawan::EndDeviceLoraPhy
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::lorawan::LoraPhy
static Time GetOnAirTime (Ptr< Packet > packet, LoraTxParameters txParams)
Compute the time that a packet with certain characteristics will take to be transmitted.
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Public Types inherited from ns3::lorawan::EndDeviceLoraPhy
enum State { SLEEP, STANDBY, TX, RX }
An enumeration of the possible states of an EndDeviceLoraPhy.
Public Types inherited from ns3::lorawan::LoraPhy
typedef Callback< void, Ptr< const Packet > > RxFailedCallback
Type definition for a callback for when a packet reception fails.
typedef Callback< void, Ptr< const Packet > > RxOkCallback
Type definition for a callback for when a packet is correctly received.
typedef Callback< void, Ptr< const Packet > > TxFinishedCallback
Type definition for a callback to call when a packet has finished sending.
Static Public Attributes inherited from ns3::lorawan::EndDeviceLoraPhy
static const double sensitivity [6]
The sensitivity vector of this device to different SFs.
Protected Types inherited from ns3::lorawan::EndDeviceLoraPhy
typedef std::vector< EndDeviceLoraPhyListener * > Listeners
typedef for a list of EndDeviceLoraPhyListener
typedef std::vector< EndDeviceLoraPhyListener * >::iterator ListenersI
typedef for a list of EndDeviceLoraPhyListener iterator
Protected Member Functions inherited from ns3::lorawan::EndDeviceLoraPhy
void SwitchToRx ()
Switch to the RX state.
void SwitchToTx (double txPowerDbm)
Switch to the TX state.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::lorawan::EndDeviceLoraPhy
double m_frequency
The frequency this device is listening on.
Listeners m_listeners
PHY listeners.
uint8_t m_sf
The Spreading Factor this device is listening for.
TracedValue< State > m_state
The state this PHY is currently in.
TracedCallback< Ptr< const Packet >, uint32_t > m_wrongFrequency
Trace source for when a packet is lost because it was transmitted on a frequency different from the one this EndDeviceLoraPhy was configured to listen on.
TracedCallback< Ptr< const Packet >, uint32_t > m_wrongSf
Trace source for when a packet is lost because it was using a SF different from the one this EndDeviceLoraPhy was configured to listen for.
Protected Attributes inherited from ns3::lorawan::LoraPhy
Ptr< LoraChannel > m_channel
The channel this PHY transmits on.
Ptr< NetDevice > m_device
The net device this PHY is attached to.
TracedCallback< Ptr< const Packet >, uint32_t > m_interferedPacket
The trace source fired when a packet cannot be correctly received because of interference.
LoraInterferenceHelper m_interference
The LoraInterferenceHelper.
TracedCallback< Ptr< const Packet > > m_phyRxBeginTrace
The trace source fired when a packet begins the reception process from the medium.
TracedCallback< Ptr< const Packet > > m_phyRxEndTrace
The trace source fired when a packet reception ends.
RxFailedCallback m_rxFailedCallback
The callback to perform upon failed reception of a packet we were locked on.
RxOkCallback m_rxOkCallback
The callback to perform upon correct reception of a packet.
TracedCallback< Ptr< const Packet >, uint32_t > m_startSending
associated to this PHY.
TracedCallback< Ptr< const Packet >, uint32_t > m_successfullyReceivedPacket
The trace source fired when a packet was correctly received.
TxFinishedCallback m_txFinishedCallback
The callback to perform upon the end of a transmission.
TracedCallback< Ptr< const Packet >, uint32_t > m_underSensitivity
The trace source fired when a packet cannot be received because its power is below the sensitivity threshold.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Class representing a simple LoRa transceiver, with an error model based on receiver sensitivity and a SIR table.
Definition at line 41 of file simple-end-device-lora-phy.h.
Constructor & Destructor Documentation
SimpleEndDeviceLoraPhy()
ns3::lorawan::SimpleEndDeviceLoraPhy::SimpleEndDeviceLoraPhy ()
Definition at line 47 of file simple-end-device-lora-phy.cc.
~SimpleEndDeviceLoraPhy()
ns3::lorawan::SimpleEndDeviceLoraPhy::~SimpleEndDeviceLoraPhy () virtual
Definition at line 51 of file simple-end-device-lora-phy.cc.
Member Function Documentation
EndReceive()
void ns3::lorawan::SimpleEndDeviceLoraPhy::EndReceive (Ptr< Packet > packet, Ptr< LoraInterferenceHelper::Event > event) virtual
Finish reception of a packet.
This method is scheduled by StartReceive, based on the packet duration. By passing a LoraInterferenceHelper Event to this method, the class will be able to identify the packet that is being received among all those that were registered as interference by StartReceive.
Parameters
packet The received packet.
event The event that is tied to this packet in the LoraInterferenceHelper.
Implements ns3::lorawan::EndDeviceLoraPhy.
Definition at line 254 of file simple-end-device-lora-phy.cc.
References ns3::lorawan::LoraInterferenceHelper::IsDestroyedByInterference(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), ns3::lorawan::LoraPhy::m_device, ns3::lorawan::LoraPhy::m_interferedPacket, ns3::lorawan::LoraPhy::m_interference, ns3::lorawan::LoraPhy::m_phyRxEndTrace, ns3::lorawan::LoraPhy::m_rxFailedCallback, ns3::lorawan::LoraPhy::m_rxOkCallback, ns3::lorawan::LoraPhy::m_successfullyReceivedPacket, NS_LOG_FUNCTION, NS_LOG_INFO, and ns3::lorawan::EndDeviceLoraPhy::SwitchToStandby().
GetTypeId()
TypeId ns3::lorawan::SimpleEndDeviceLoraPhy::GetTypeId (void) static
Definition at line 35 of file simple-end-device-lora-phy.cc.
References ns3::TypeId::SetParent().
Send()
void ns3::lorawan::SimpleEndDeviceLoraPhy::Send (Ptr< Packet > packet, LoraTxParameters txParams, double frequencyMHz, double txPowerDbm) virtual
Instruct the PHY to send a packet according to some parameters.
Parameters
packet The packet to send.
txParams The desired transmission parameters.
frequencyMHz The frequency on which to transmit.
txPowerDbm The power in dBm with which to transmit the packet.
Implements ns3::lorawan::EndDeviceLoraPhy.
Definition at line 56 of file simple-end-device-lora-phy.cc.
References ns3::Packet::AddPacketTag(), aloha::duration, ns3::lorawan::LoraPhy::GetOnAirTime(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), ns3::lorawan::LoraPhy::m_channel, ns3::lorawan::LoraPhy::m_device, ns3::lorawan::LoraPhy::m_startSending, ns3::lorawan::EndDeviceLoraPhy::m_state, ns3::lorawan::LoraPhy::m_txFinishedCallback, ns3::NanoSeconds(), NS_LOG_FUNCTION, NS_LOG_INFO, ns3::Packet::RemovePacketTag(), ns3::Simulator::Schedule(), ns3::lorawan::LoraTag::SetSpreadingFactor(), ns3::lorawan::LoraTxParameters::sf, ns3::lorawan::EndDeviceLoraPhy::SLEEP, ns3::lorawan::EndDeviceLoraPhy::STANDBY, ns3::lorawan::EndDeviceLoraPhy::SwitchToStandby(), and ns3::lorawan::EndDeviceLoraPhy::SwitchToTx().
StartReceive()
void ns3::lorawan::SimpleEndDeviceLoraPhy::StartReceive (Ptr< Packet > packet, double rxPowerDbm, uint8_t sf, Time duration, double frequencyMHz) virtual
Start receiving a packet.
This method is typically called by LoraChannel.
Parameters
packet The packet that is arriving at this PHY layer.
rxPowerDbm The power of the arriving packet (assumed to be constant for the whole reception).
sf The Spreading Factor of the arriving packet.
duration The on air time of this packet.
frequencyMHz The frequency this packet is being transmitted on.
Implements ns3::lorawan::EndDeviceLoraPhy.
Definition at line 114 of file simple-end-device-lora-phy.cc.
References ns3::lorawan::LoraInterferenceHelper::Add(), aloha::duration, ns3::lorawan::LoraPhy::EndReceive(), ns3::lorawan::EndDeviceLoraPhy::IsOnFrequency(), ns3::lorawan::LoraPhy::m_device, ns3::lorawan::EndDeviceLoraPhy::m_frequency, ns3::lorawan::LoraPhy::m_interference, ns3::lorawan::LoraPhy::m_phyRxBeginTrace, ns3::lorawan::EndDeviceLoraPhy::m_sf, ns3::lorawan::EndDeviceLoraPhy::m_state, ns3::lorawan::LoraPhy::m_underSensitivity, ns3::lorawan::EndDeviceLoraPhy::m_wrongFrequency, ns3::lorawan::EndDeviceLoraPhy::m_wrongSf, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::lorawan::EndDeviceLoraPhy::RX, ns3::Simulator::Schedule(), ns3::lorawan::EndDeviceLoraPhy::sensitivity, ns3::lorawan::EndDeviceLoraPhy::SLEEP, ns3::lorawan::EndDeviceLoraPhy::STANDBY, ns3::lorawan::EndDeviceLoraPhy::SwitchToRx(), and ns3::lorawan::EndDeviceLoraPhy::TX.
The documentation for this class was generated from the following files:
src/lorawan/model/simple-end-device-lora-phy.h
src/lorawan/model/simple-end-device-lora-phy.cc