ns-3: ns3::aodv::RreqHeader Class Reference
ns3::aodv::RreqHeader Class Reference
AODV Routing
Route Request (RREQ) Message Format.
#include "aodv-packet.h"
Public Member Functions
RreqHeader (uint8_t flags=0, uint8_t reserved=0, uint8_t hopCount=0, uint32_t requestID=0, Ipv4Address dst=Ipv4Address(), uint32_t dstSeqNo=0, Ipv4Address origin=Ipv4Address(), uint32_t originSeqNo=0)
constructor
uint32_t Deserialize (Buffer::Iterator start)
bool GetDestinationOnly () const
Get the Destination only flag.
Ipv4Address GetDst () const
Get the destination address.
uint32_t GetDstSeqno () const
Get the destination sequence number.
bool GetGratuitousRrep () const
Get the gratuitous RREP flag.
uint8_t GetHopCount () const
Get the hop count.
uint32_t GetId () const
Get the request ID.
TypeId GetInstanceTypeId () const
Get the most derived TypeId for this Object.
Ipv4Address GetOrigin () const
Get the origin address.
uint32_t GetOriginSeqno () const
Get the origin sequence number.
uint32_t GetSerializedSize () const
bool GetUnknownSeqno () const
Get the unknown sequence number flag.
bool operator== (RreqHeader const &o) const
Comparison operator.
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetDestinationOnly (bool f)
Set the Destination only flag.
void SetDst (Ipv4Address a)
Set the destination address.
void SetDstSeqno (uint32_t s)
Set the destination sequence number.
void SetGratuitousRrep (bool f)
Set the gratuitous RREP flag.
void SetHopCount (uint8_t count)
Set the hop count.
void SetId (uint32_t id)
Set the request ID.
void SetOrigin (Ipv4Address a)
Set the origin address.
void SetOriginSeqno (uint32_t s)
Set the origin sequence number.
void SetUnknownSeqno (bool f)
Set the unknown sequence number flag.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Ipv4Address m_dst
Destination IP Address.
uint32_t m_dstSeqNo
Destination Sequence Number.
uint8_t m_flags
|J|R|G|D|U| bit flags, see RFC
uint8_t m_hopCount
Hop Count.
Ipv4Address m_origin
Originator IP Address.
uint32_t m_originSeqNo
Source Sequence Number.
uint32_t m_requestID
RREQ ID.
uint8_t m_reserved
Not used (must be 0)
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Route Request (RREQ) Message Format.
0                   1                   2                   3
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|     Type      |J|R|G|D|U|   Reserved          |   Hop Count   |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                            RREQ ID                            |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                    Destination IP Address                     |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                  Destination Sequence Number                  |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                    Originator IP Address                      |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                  Originator Sequence Number                   |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 131 of file aodv-packet.h.
Constructor & Destructor Documentation
RreqHeader()
ns3::aodv::RreqHeader::RreqHeader (uint8_t flags = 0, uint8_t reserved = 0, uint8_t hopCount = 0, uint32_t requestID = 0, Ipv4Address dst = Ipv4Address (), uint32_t dstSeqNo = 0, Ipv4Address origin = Ipv4Address (), uint32_t originSeqNo = 0)
constructor
Parameters
flags the message flags (0)
reserved the reserved bits (0)
hopCount the hop count
requestID the request ID
dst the destination IP address
dstSeqNo the destination sequence number
origin the origin IP address
originSeqNo the origin sequence number
Definition at line 142 of file aodv-packet.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::aodv::RreqHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 194 of file aodv-packet.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), GetSerializedSize(), m_dst, m_dstSeqNo, m_flags, m_hopCount, m_origin, m_originSeqNo, m_requestID, m_reserved, NS_ASSERT, ns3::ReadFrom(), ns3::Buffer::Iterator::ReadNtohU32(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetDestinationOnly()
bool ns3::aodv::RreqHeader::GetDestinationOnly () const
Get the Destination only flag.
Returns
the Destination only flag
Definition at line 262 of file aodv-packet.cc.
References m_flags.
Referenced by ns3::aodv::RreqHeaderTest::DoRun(), and ns3::aodv::RoutingProtocol::RecvRequest().
GetDst()
Ipv4Address ns3::aodv::RreqHeader::GetDst () const inline
Get the destination address.
Returns
the destination address
Definition at line 207 of file aodv-packet.h.
References m_dst.
Referenced by ns3::aodv::RreqHeaderTest::DoRun(), ns3::aodv::RoutingProtocol::RecvRequest(), and ns3::aodv::RoutingProtocol::SendReply().
GetDstSeqno()
uint32_t ns3::aodv::RreqHeader::GetDstSeqno () const inline
Get the destination sequence number.
Returns
the destination sequence number
Definition at line 223 of file aodv-packet.h.
References m_dstSeqNo.
Referenced by ns3::aodv::RreqHeaderTest::DoRun(), ns3::aodv::RoutingProtocol::RecvRequest(), and ns3::aodv::RoutingProtocol::SendReply().
GetGratuitousRrep()
bool ns3::aodv::RreqHeader::GetGratuitousRrep () const
Get the gratuitous RREP flag.
Returns
the gratuitous RREP flag
Definition at line 243 of file aodv-packet.cc.
References m_flags.
Referenced by ns3::aodv::RreqHeaderTest::DoRun(), and ns3::aodv::RoutingProtocol::RecvRequest().
GetHopCount()
uint8_t ns3::aodv::RreqHeader::GetHopCount () const inline
Get the hop count.
Returns
the hop count
Definition at line 175 of file aodv-packet.h.
References m_hopCount.
Referenced by ns3::aodv::RreqHeaderTest::DoRun(), and ns3::aodv::RoutingProtocol::RecvRequest().
GetId()
uint32_t ns3::aodv::RreqHeader::GetId () const inline
Get the request ID.
Returns
the request ID
Definition at line 191 of file aodv-packet.h.
References m_requestID.
Referenced by ns3::aodv::RreqHeaderTest::DoRun(), ns3::aodv::RoutingProtocol::RecvRequest(), and ns3::aodv::RoutingProtocol::SendRequest().
GetInstanceTypeId()
TypeId ns3::aodv::RreqHeader::GetInstanceTypeId () const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 169 of file aodv-packet.cc.
References GetTypeId().
GetOrigin()
Ipv4Address ns3::aodv::RreqHeader::GetOrigin () const inline
Get the origin address.
Returns
the origin address
Definition at line 239 of file aodv-packet.h.
References m_origin.
Referenced by ns3::aodv::RreqHeaderTest::DoRun(), and ns3::aodv::RoutingProtocol::RecvRequest().
GetOriginSeqno()
uint32_t ns3::aodv::RreqHeader::GetOriginSeqno () const inline
Get the origin sequence number.
Returns
the origin sequence number
Definition at line 255 of file aodv-packet.h.
References m_originSeqNo.
Referenced by ns3::aodv::RreqHeaderTest::DoRun(), and ns3::aodv::RoutingProtocol::RecvRequest().
GetSerializedSize()
uint32_t ns3::aodv::RreqHeader::GetSerializedSize () const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 175 of file aodv-packet.cc.
Referenced by Deserialize().
GetTypeId()
TypeId ns3::aodv::RreqHeader::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 158 of file aodv-packet.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
GetUnknownSeqno()
bool ns3::aodv::RreqHeader::GetUnknownSeqno () const
Get the unknown sequence number flag.
Returns
the unknown sequence number flag
Definition at line 281 of file aodv-packet.cc.
References m_flags.
Referenced by ns3::aodv::RreqHeaderTest::DoRun(), ns3::aodv::RoutingProtocol::RecvRequest(), and ns3::aodv::RoutingProtocol::SendReply().
operator==()
bool ns3::aodv::RreqHeader::operator== (RreqHeader const & o) const
Comparison operator.
Parameters
o RREQ header to compare
Returns
true if the RREQ headers are equal
Definition at line 287 of file aodv-packet.cc.
References m_dst, m_dstSeqNo, m_flags, m_hopCount, m_origin, m_originSeqNo, m_requestID, and m_reserved.
Print()
void ns3::aodv::RreqHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 212 of file aodv-packet.cc.
References m_dst, m_dstSeqNo, m_origin, m_originSeqNo, and m_requestID.
Referenced by ns3::aodv::operator<<().
Serialize()
void ns3::aodv::RreqHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 181 of file aodv-packet.cc.
References m_dst, m_dstSeqNo, m_flags, m_hopCount, m_origin, m_originSeqNo, m_requestID, m_reserved, ns3::Buffer::Iterator::WriteHtonU32(), ns3::WriteTo(), and ns3::Buffer::Iterator::WriteU8().
SetDestinationOnly()
void ns3::aodv::RreqHeader::SetDestinationOnly (bool f)
Set the Destination only flag.
Parameters
f the Destination only flag
Definition at line 249 of file aodv-packet.cc.
References f(), and m_flags.
Referenced by ns3::aodv::RreqHeaderTest::DoRun(), and ns3::aodv::RoutingProtocol::SendRequest().
SetDst()
void ns3::aodv::RreqHeader::SetDst (Ipv4Address a) inline
Set the destination address.
Parameters
a the destination address
Definition at line 199 of file aodv-packet.h.
References m_dst.
Referenced by ns3::aodv::RreqHeaderTest::DoRun(), and ns3::aodv::RoutingProtocol::SendRequest().
SetDstSeqno()
void ns3::aodv::RreqHeader::SetDstSeqno (uint32_t s) inline
Set the destination sequence number.
Parameters
s the destination sequence number
Definition at line 215 of file aodv-packet.h.
References m_dstSeqNo.
Referenced by ns3::aodv::RreqHeaderTest::DoRun(), ns3::aodv::RoutingProtocol::RecvRequest(), and ns3::aodv::RoutingProtocol::SendRequest().
SetGratuitousRrep()
void ns3::aodv::RreqHeader::SetGratuitousRrep (bool f)
Set the gratuitous RREP flag.
Parameters
f the gratuitous RREP flag
Definition at line 230 of file aodv-packet.cc.
References f(), and m_flags.
Referenced by ns3::aodv::RreqHeaderTest::DoRun(), and ns3::aodv::RoutingProtocol::SendRequest().
SetHopCount()
void ns3::aodv::RreqHeader::SetHopCount (uint8_t count) inline
Set the hop count.
Parameters
count the hop count
Definition at line 167 of file aodv-packet.h.
References m_hopCount.
Referenced by ns3::aodv::RreqHeaderTest::DoRun(), and ns3::aodv::RoutingProtocol::RecvRequest().
SetId()
void ns3::aodv::RreqHeader::SetId (uint32_t id) inline
Set the request ID.
Parameters
id the request ID
Definition at line 183 of file aodv-packet.h.
References m_requestID.
Referenced by ns3::aodv::RreqHeaderTest::DoRun(), and ns3::aodv::RoutingProtocol::SendRequest().
SetOrigin()
void ns3::aodv::RreqHeader::SetOrigin (Ipv4Address a) inline
Set the origin address.
Parameters
a the origin address
Definition at line 231 of file aodv-packet.h.
References m_origin.
Referenced by ns3::aodv::RreqHeaderTest::DoRun(), and ns3::aodv::RoutingProtocol::SendRequest().
SetOriginSeqno()
void ns3::aodv::RreqHeader::SetOriginSeqno (uint32_t s) inline
Set the origin sequence number.
Parameters
s the origin sequence number
Definition at line 247 of file aodv-packet.h.
References m_originSeqNo.
Referenced by ns3::aodv::RreqHeaderTest::DoRun(), and ns3::aodv::RoutingProtocol::SendRequest().
SetUnknownSeqno()
void ns3::aodv::RreqHeader::SetUnknownSeqno (bool f)
Set the unknown sequence number flag.
Parameters
f the unknown sequence number flag
Definition at line 268 of file aodv-packet.cc.
References f(), and m_flags.
Referenced by ns3::aodv::RreqHeaderTest::DoRun(), ns3::aodv::RoutingProtocol::RecvRequest(), and ns3::aodv::RoutingProtocol::SendRequest().
Member Data Documentation
m_dst
Ipv4Address ns3::aodv::RreqHeader::m_dst private
Destination IP Address.
Definition at line 303 of file aodv-packet.h.
Referenced by Deserialize(), GetDst(), operator==(), Print(), Serialize(), and SetDst().
m_dstSeqNo
uint32_t ns3::aodv::RreqHeader::m_dstSeqNo private
Destination Sequence Number.
Definition at line 304 of file aodv-packet.h.
Referenced by Deserialize(), GetDstSeqno(), operator==(), Print(), Serialize(), and SetDstSeqno().
m_flags
uint8_t ns3::aodv::RreqHeader::m_flags private
|J|R|G|D|U| bit flags, see RFC
Definition at line 299 of file aodv-packet.h.
Referenced by Deserialize(), GetDestinationOnly(), GetGratuitousRrep(), GetUnknownSeqno(), operator==(), Serialize(), SetDestinationOnly(), SetGratuitousRrep(), and SetUnknownSeqno().
m_hopCount
uint8_t ns3::aodv::RreqHeader::m_hopCount private
Hop Count.
Definition at line 301 of file aodv-packet.h.
Referenced by Deserialize(), GetHopCount(), operator==(), Serialize(), and SetHopCount().
m_origin
Ipv4Address ns3::aodv::RreqHeader::m_origin private
Originator IP Address.
Definition at line 305 of file aodv-packet.h.
Referenced by Deserialize(), GetOrigin(), operator==(), Print(), Serialize(), and SetOrigin().
m_originSeqNo
uint32_t ns3::aodv::RreqHeader::m_originSeqNo private
Source Sequence Number.
Definition at line 306 of file aodv-packet.h.
Referenced by Deserialize(), GetOriginSeqno(), operator==(), Print(), Serialize(), and SetOriginSeqno().
m_requestID
uint32_t ns3::aodv::RreqHeader::m_requestID private
RREQ ID.
Definition at line 302 of file aodv-packet.h.
Referenced by Deserialize(), GetId(), operator==(), Print(), Serialize(), and SetId().
m_reserved
uint8_t ns3::aodv::RreqHeader::m_reserved private
Not used (must be 0)
Definition at line 300 of file aodv-packet.h.
Referenced by Deserialize(), operator==(), and Serialize().
The documentation for this class was generated from the following files:
src/aodv/model/aodv-packet.h
src/aodv/model/aodv-packet.cc