ns-3: HeaderTest Class Reference
HeaderTest Class Reference
Public Member Functions
HeaderTest ()
virtual ~HeaderTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 234 of file lorawan-test-suite.cc.
Constructor & Destructor Documentation
HeaderTest()
HeaderTest::HeaderTest ()
Definition at line 245 of file lorawan-test-suite.cc.
~HeaderTest()
HeaderTest::~HeaderTest () virtual
Definition at line 251 of file lorawan-test-suite.cc.
Member Function Documentation
DoRun()
void HeaderTest::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 258 of file lorawan-test-suite.cc.
References ns3::Buffer::AddAtStart(), ns3::Packet::AddHeader(), ns3::lorawan::LoraFrameHeader::AddLinkCheckAns(), ns3::Buffer::Begin(), ns3::lorawan::LoraFrameHeader::Deserialize(), ns3::lorawan::LorawanMacHeader::Deserialize(), ns3::lorawan::LoraFrameHeader::GetAck(), ns3::lorawan::LoraFrameHeader::GetAddress(), ns3::lorawan::LoraFrameHeader::GetAdr(), ns3::lorawan::LoraFrameHeader::GetCommands(), ns3::lorawan::LoraFrameHeader::GetFCnt(), ns3::lorawan::LinkCheckAns::GetGwCnt(), ns3::lorawan::LorawanMacHeader::GetMajor(), ns3::lorawan::LinkCheckAns::GetMargin(), ns3::lorawan::LorawanMacHeader::GetMType(), ns3::Packet::GetSize(), NS_LOG_DEBUG, NS_TEST_EXPECT_MSG_EQ, ns3::Packet::RemoveHeader(), ns3::lorawan::LoraFrameHeader::Serialize(), ns3::lorawan::LorawanMacHeader::Serialize(), ns3::lorawan::LoraFrameHeader::SetAck(), ns3::lorawan::LoraFrameHeader::SetAddress(), ns3::lorawan::LoraFrameHeader::SetAdr(), ns3::lorawan::LoraFrameHeader::SetAsDownlink(), ns3::lorawan::LoraFrameHeader::SetFCnt(), ns3::lorawan::LorawanMacHeader::SetMajor(), and ns3::lorawan::LorawanMacHeader::SetMType().
The documentation for this class was generated from the following file:
src/lorawan/test/lorawan-test-suite.cc