ns-3: ns3::LrWpanSpectrumValueHelper Class Reference
ns3::LrWpanSpectrumValueHelper Class Reference
LR-WPAN models
This class defines all functions to create spectrum model for LrWpan.
#include "lr-wpan-spectrum-value-helper.h"
Public Member Functions
LrWpanSpectrumValueHelper (void)
virtual ~LrWpanSpectrumValueHelper (void)
Ptr< SpectrumValue > CreateNoisePowerSpectralDensity (uint32_t channel)
create spectrum value for noise
Ptr< SpectrumValue > CreateTxPowerSpectralDensity (double txPower, uint32_t channel)
create spectrum value
Static Public Member Functions
static double TotalAvgPower (Ptr< const SpectrumValue > psd, uint32_t channel)
total average power of the signal is the integral of the PSD using the limits of the given channel
Private Attributes
double m_noiseFactor
A scaling factor for the noise power.
Detailed Description
This class defines all functions to create spectrum model for LrWpan.
Definition at line 34 of file lr-wpan-spectrum-value-helper.h.
Constructor & Destructor Documentation
LrWpanSpectrumValueHelper()
ns3::LrWpanSpectrumValueHelper::LrWpanSpectrumValueHelper (void)
Definition at line 59 of file lr-wpan-spectrum-value-helper.cc.
References m_noiseFactor, and NS_LOG_FUNCTION.
~LrWpanSpectrumValueHelper()
ns3::LrWpanSpectrumValueHelper::~LrWpanSpectrumValueHelper (void) virtual
Definition at line 65 of file lr-wpan-spectrum-value-helper.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CreateNoisePowerSpectralDensity()
Ptr< SpectrumValue > ns3::LrWpanSpectrumValueHelper::CreateNoisePowerSpectralDensity (uint32_t channel)
create spectrum value for noise
Parameters
channel the channel number per IEEE802.15.4
Returns
a Ptr to a newly created SpectrumValue instance
Definition at line 104 of file lr-wpan-spectrum-value-helper.cc.
References third::channel, ns3::g_LrWpanSpectrumModel, m_noiseFactor, NS_ASSERT_MSG(), and NS_LOG_FUNCTION.
Referenced by ns3::LrWpanPhy::LrWpanPhy().
CreateTxPowerSpectralDensity()
Ptr< SpectrumValue > ns3::LrWpanSpectrumValueHelper::CreateTxPowerSpectralDensity (double txPower, uint32_t channel)
create spectrum value
Parameters
txPower the power transmission in dBm
channel the channel number per IEEE802.15.4
Returns
a Ptr to a newly created SpectrumValue instance
Definition at line 71 of file lr-wpan-spectrum-value-helper.cc.
References third::channel, ns3::g_LrWpanSpectrumModel, NS_ASSERT_MSG(), and NS_LOG_FUNCTION.
Referenced by ns3::LrWpanPhy::LrWpanPhy(), LrWpanSpectrumValueHelperTestCase::DoRun(), and ns3::LrWpanPhy::PlmeSetAttributeRequest().
TotalAvgPower()
double ns3::LrWpanSpectrumValueHelper::TotalAvgPower (Ptr< const SpectrumValue > psd, uint32_t channel) static
total average power of the signal is the integral of the PSD using the limits of the given channel
Parameters
psd spectral density
channel the channel number per IEEE802.15.4
Returns
total power (using composite trap. rule to numerally integrate)
Definition at line 127 of file lr-wpan-spectrum-value-helper.cc.
References third::channel, ns3::g_LrWpanSpectrumModel, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::LrWpanPhy::CheckInterference(), LrWpanSpectrumValueHelperTestCase::DoRun(), ns3::LrWpanPhy::EndCca(), ns3::LrWpanPhy::EndEd(), ns3::LrWpanPhy::EndRx(), and ns3::LrWpanPhy::StartRx().
Member Data Documentation
m_noiseFactor
double ns3::LrWpanSpectrumValueHelper::m_noiseFactor private
A scaling factor for the noise power.
Definition at line 68 of file lr-wpan-spectrum-value-helper.h.
Referenced by LrWpanSpectrumValueHelper(), and CreateNoisePowerSpectralDensity().
The documentation for this class was generated from the following files:
src/lr-wpan/model/lr-wpan-spectrum-value-helper.h
src/lr-wpan/model/lr-wpan-spectrum-value-helper.cc