ns-3: ns3::BooleanValue Class Reference
ns3::BooleanValue Class Reference
#include "boolean.h"
Public Member Functions
BooleanValue ()
BooleanValue (bool value)
Construct from an explicit value.
virtual Ptr< AttributeValue > Copy (void) const
virtual bool DeserializeFromString (std::string value, Ptr< const AttributeChecker > checker)
bool Get (void) const
template<typename T >
bool GetAccessor (T &v) const
operator bool () const
Functor returning the value.
virtual std::string SerializeToString (Ptr< const AttributeChecker > checker) const
void Set (bool value)
Public Member Functions inherited from ns3::AttributeValue
AttributeValue ()
virtual ~AttributeValue ()
Public Member Functions inherited from ns3::SimpleRefCount< AttributeValue >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
bool m_value
Detailed Description
Definition at line 36 of file boolean.h.
Constructor & Destructor Documentation
BooleanValue() [1/2]
ns3::BooleanValue::BooleanValue ()
Definition at line 34 of file boolean.cc.
References NS_LOG_FUNCTION.
BooleanValue() [2/2]
ns3::BooleanValue::BooleanValue (bool value)
Construct from an explicit value.
Parameters
[in] value The boolean value to begin with.
Definition at line 39 of file boolean.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Copy()
Ptr< AttributeValue > ns3::BooleanValue::Copy (void) const virtual
Returns
a deep copy of this class, wrapped into an Attribute object.
Implements ns3::AttributeValue.
Definition at line 75 of file boolean.cc.
References NS_LOG_FUNCTION.
DeserializeFromString()
bool ns3::BooleanValue::DeserializeFromString (std::string value, Ptr< const AttributeChecker > checker) virtual
Parameters
[in] value A string representation of the value
[in] checker A pointer to the checker associated to the attribute.
Returns
true if the input string was correctly-formatted and could be successfully deserialized, false otherwise.
Upon return of this function, this AttributeValue instance contains the deserialized value. In most cases, this method will not make any use of the checker argument. However, in a very limited set of cases, the checker argument is needed to perform proper serialization. A nice example of code which needs it is the EnumValue::SerializeToString code.
Implements ns3::AttributeValue.
Definition at line 96 of file boolean.cc.
References m_value, and NS_LOG_FUNCTION.
Get()
bool ns3::BooleanValue::Get (void) const
Definition at line 51 of file boolean.cc.
References m_value, and NS_LOG_FUNCTION.
Referenced by ns3::Node::ChecksumEnabled(), TcpBicDecrementTest::ExecuteTest(), ns3::WaveHelper::Install(), ns3::WifiHelper::Install(), and ns3::operator<<().
GetAccessor()
template<typename T > bool ns3::BooleanValue::GetAccessor (T & v) const
Definition at line 66 of file boolean.h.
References m_value.
operator bool()
ns3::BooleanValue::operator bool () const
Functor returning the value.
Returns
The value.
Definition at line 56 of file boolean.cc.
SerializeToString()
std::string ns3::BooleanValue::SerializeToString (Ptr< const AttributeChecker > checker) const virtual
Parameters
[in] checker The checker associated to the attribute
Returns
A string representation of this value.
In most cases, this method will not make any use of the checker argument. However, in a very limited set of cases, the checker argument is needed to perform proper serialization. A nice example of code which needs it is the EnumValue::SerializeToString code.
Implements ns3::AttributeValue.
Definition at line 82 of file boolean.cc.
References m_value, and NS_LOG_FUNCTION.
Set()
void ns3::BooleanValue::Set (bool value)
Definition at line 45 of file boolean.cc.
References m_value, and NS_LOG_FUNCTION.
Member Data Documentation
m_value
bool ns3::BooleanValue::m_value private
Definition at line 62 of file boolean.h.
Referenced by DeserializeFromString(), Get(), GetAccessor(), SerializeToString(), and Set().
The documentation for this class was generated from the following files:
src/core/model/boolean.h
src/core/model/boolean.cc