ns-3: ns3::dot11s::IeBeaconTiming Class Reference
ns3::dot11s::IeBeaconTiming Class Reference
Mesh Device » IEEE 802.11s draft
See 7.3.2.89 of 802.11s draft 2.07.
#include "ie-dot11s-beacon-timing.h"
Public Types
typedef std::vector< Ptr< IeBeaconTimingUnit > > NeighboursTimingUnitsList
Public Member Functions
IeBeaconTiming ()
void AddNeighboursTimingElementUnit (uint16_t aid, Time last_beacon, Time beacon_interval)
Add neighbors timing element unit.
void ClearTimingElement ()
Clear timing element.
void DelNeighboursTimingElementUnit (uint16_t aid, Time last_beacon, Time beacon_interval)
Delete neighbors timing element unit.
virtual uint8_t DeserializeInformationField (Buffer::Iterator i, uint8_t length)
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
virtual WifiInformationElementId ElementId () const
virtual uint8_t GetInformationFieldSize () const
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
NeighboursTimingUnitsList GetNeighboursTimingElementsList ()
This methods are needed for beacon collision avoidance module:
bool operator== (WifiInformationElement const &a) const
equality operator
virtual void Print (std::ostream &os) const
Generate human-readable form of IE.
virtual void SerializeInformationField (Buffer::Iterator i) const
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
Public Member Functions inherited from ns3::WifiInformationElement
virtual ~WifiInformationElement ()
Buffer::Iterator Deserialize (Buffer::Iterator i)
Deserialize entire IE, which must be present.
Buffer::Iterator DeserializeIfPresent (Buffer::Iterator i)
Deserialize entire IE if it is present.
virtual WifiInformationElementId ElementIdExt () const
uint16_t GetSerializedSize () const
Get the size of the serialized IE including Element ID and length fields.
Buffer::Iterator Serialize (Buffer::Iterator i) const
Serialize entire IE including Element ID and length fields.
Public Member Functions inherited from ns3::SimpleRefCount< WifiInformationElement >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Static Private Member Functions
static uint8_t AidToU8 (uint16_t x)
Aid to U8 function.
static uint16_t BeaconIntervalToU16 (Time x)
Beacon interval to U16 function.
static uint16_t TimestampToU16 (Time x)
Timestamp to U16 function.
Private Attributes
NeighboursTimingUnitsList m_neighbours
the neighbors
uint16_t m_numOfUnits
Timing element parameters:
Detailed Description
See 7.3.2.89 of 802.11s draft 2.07.
Definition at line 91 of file ie-dot11s-beacon-timing.h.
Constructor & Destructor Documentation
IeBeaconTiming()
ns3::dot11s::IeBeaconTiming::IeBeaconTiming ()
Definition at line 70 of file ie-dot11s-beacon-timing.cc.
Member Function Documentation
AddNeighboursTimingElementUnit()
void ns3::dot11s::IeBeaconTiming::AddNeighboursTimingElementUnit (uint16_t aid, Time last_beacon, Time beacon_interval)
Add neighbors timing element unit.
Parameters
aid the AID
last_beacon the last beacon time
beacon_interval the beacon interval
Definition at line 80 of file ie-dot11s-beacon-timing.cc.
References AidToU8(), BeaconIntervalToU16(), m_neighbours, m_numOfUnits, ns3::dot11s::IeBeaconTimingUnit::SetAid(), ns3::dot11s::IeBeaconTimingUnit::SetBeaconInterval(), ns3::dot11s::IeBeaconTimingUnit::SetLastBeacon(), and TimestampToU16().
Referenced by MeshInformationElementVectorBist::DoRun().
AidToU8()
uint8_t ns3::dot11s::IeBeaconTiming::AidToU8 (uint16_t x) static private
Aid to U8 function.
Parameters
x the U16
Returns
the AID
Definition at line 180 of file ie-dot11s-beacon-timing.cc.
References sample-rng-plot::x.
Referenced by AddNeighboursTimingElementUnit(), and DelNeighboursTimingElementUnit().
BeaconIntervalToU16()
uint16_t ns3::dot11s::IeBeaconTiming::BeaconIntervalToU16 (Time x) static private
Beacon interval to U16 function.
Parameters
x the beacon interval
Returns
the U16
Definition at line 175 of file ie-dot11s-beacon-timing.cc.
References ns3::Time::GetMicroSeconds().
Referenced by AddNeighboursTimingElementUnit(), and DelNeighboursTimingElementUnit().
ClearTimingElement()
void ns3::dot11s::IeBeaconTiming::ClearTimingElement ()
Clear timing element.
Definition at line 117 of file ie-dot11s-beacon-timing.cc.
References m_neighbours.
Referenced by ns3::dot11s::PeerLink::DoDispose().
DelNeighboursTimingElementUnit()
void ns3::dot11s::IeBeaconTiming::DelNeighboursTimingElementUnit (uint16_t aid, Time last_beacon, Time beacon_interval)
Delete neighbors timing element unit.
Parameters
aid the AID
last_beacon the last beacon time
beacon_interval the beacon interval
Definition at line 103 of file ie-dot11s-beacon-timing.cc.
References AidToU8(), BeaconIntervalToU16(), m_neighbours, m_numOfUnits, and TimestampToU16().
DeserializeInformationField()
uint8_t ns3::dot11s::IeBeaconTiming::DeserializeInformationField (Buffer::Iterator start, uint8_t length) virtual
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
length
Returns
the number of bytes read
Implements ns3::WifiInformationElement.
Definition at line 152 of file ie-dot11s-beacon-timing.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_neighbours, m_numOfUnits, ns3::Buffer::Iterator::ReadLsbtohU16(), ns3::Buffer::Iterator::ReadU8(), ns3::dot11s::IeBeaconTimingUnit::SetAid(), ns3::dot11s::IeBeaconTimingUnit::SetBeaconInterval(), ns3::dot11s::IeBeaconTimingUnit::SetLastBeacon(), and visualizer.core::start().
ElementId()
WifiInformationElementId ns3::dot11s::IeBeaconTiming::ElementId () const virtual
Returns
Own unique Element ID
Implements ns3::WifiInformationElement.
Definition at line 66 of file ie-dot11s-beacon-timing.cc.
References IE_BEACON_TIMING.
GetInformationFieldSize()
uint8_t ns3::dot11s::IeBeaconTiming::GetInformationFieldSize () const virtual
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
This is the value that will appear in the second octet of the entire IE - the length field)
Returns
the length of serialized information
Implements ns3::WifiInformationElement.
Definition at line 126 of file ie-dot11s-beacon-timing.cc.
References m_numOfUnits.
GetNeighboursTimingElementsList()
IeBeaconTiming::NeighboursTimingUnitsList ns3::dot11s::IeBeaconTiming::GetNeighboursTimingElementsList ()
This methods are needed for beacon collision avoidance module:
Returns
the neighbor timing elements list
Definition at line 75 of file ie-dot11s-beacon-timing.cc.
References m_neighbours.
operator==()
bool ns3::dot11s::IeBeaconTiming::operator== (WifiInformationElement const & a) const virtual
equality operator
Parameters
a lhs
Returns
true if equal
Reimplemented from ns3::WifiInformationElement.
Definition at line 191 of file ie-dot11s-beacon-timing.cc.
References m_neighbours, m_numOfUnits, and ns3::PeekPointer().
Print()
void ns3::dot11s::IeBeaconTiming::Print (std::ostream & os) const virtual
Generate human-readable form of IE.
Parameters
os output stream
Reimplemented from ns3::WifiInformationElement.
Definition at line 131 of file ie-dot11s-beacon-timing.cc.
References m_neighbours, and m_numOfUnits.
Referenced by ns3::dot11s::operator<<().
SerializeInformationField()
void ns3::dot11s::IeBeaconTiming::SerializeInformationField (Buffer::Iterator start) const virtual
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
Implements ns3::WifiInformationElement.
Definition at line 142 of file ie-dot11s-beacon-timing.cc.
References m_neighbours, ns3::Buffer::Iterator::WriteHtolsbU16(), and ns3::Buffer::Iterator::WriteU8().
TimestampToU16()
uint16_t ns3::dot11s::IeBeaconTiming::TimestampToU16 (Time x) static private
Timestamp to U16 function.
Parameters
x the timestamp
Returns
the U16
Definition at line 168 of file ie-dot11s-beacon-timing.cc.
References ns3::Time::GetMicroSeconds().
Referenced by AddNeighboursTimingElementUnit(), and DelNeighboursTimingElementUnit().
Member Data Documentation
m_neighbours
NeighboursTimingUnitsList ns3::dot11s::IeBeaconTiming::m_neighbours private
the neighbors
Definition at line 167 of file ie-dot11s-beacon-timing.h.
Referenced by AddNeighboursTimingElementUnit(), ClearTimingElement(), DelNeighboursTimingElementUnit(), DeserializeInformationField(), GetNeighboursTimingElementsList(), operator==(), Print(), and SerializeInformationField().
m_numOfUnits
uint16_t ns3::dot11s::IeBeaconTiming::m_numOfUnits private
Timing element parameters:
Definition at line 171 of file ie-dot11s-beacon-timing.h.
Referenced by AddNeighboursTimingElementUnit(), DelNeighboursTimingElementUnit(), DeserializeInformationField(), GetInformationFieldSize(), operator==(), and Print().
The documentation for this class was generated from the following files:
src/mesh/model/dot11s/ie-dot11s-beacon-timing.h
src/mesh/model/dot11s/ie-dot11s-beacon-timing.cc