ns-3: ns3::Ipv6OptionPad1Header Class Reference
ns3::Ipv6OptionPad1Header Class Reference
Internet » IPv6 classes and sub-modules » IPV6 Header extension system.
Header of IPv6 Option Pad1.
#include "ipv6-option-header.h"
Public Member Functions
Ipv6OptionPad1Header ()
Constructor.
virtual ~Ipv6OptionPad1Header ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
virtual uint32_t GetSerializedSize () const
Get the serialized size of the packet.
virtual void Print (std::ostream &os) const
Print some information about the packet.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
Public Member Functions inherited from ns3::Ipv6OptionHeader
Ipv6OptionHeader ()
Constructor.
virtual ~Ipv6OptionHeader ()
Destructor.
virtual Alignment GetAlignment () const
Get the Alignment requirement of this option header.
uint8_t GetLength () const
Get the option length.
uint8_t GetType () const
Get the type of the option.
void SetLength (uint8_t length)
Set the option length.
void SetType (uint8_t type)
Set the type of the option.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Ipv6OptionHeader
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Header of IPv6 Option Pad1.
Definition at line 156 of file ipv6-option-header.h.
Constructor & Destructor Documentation
Ipv6OptionPad1Header()
ns3::Ipv6OptionPad1Header::Ipv6OptionPad1Header ()
Constructor.
Definition at line 137 of file ipv6-option-header.cc.
References ns3::Ipv6OptionHeader::SetType().
~Ipv6OptionPad1Header()
ns3::Ipv6OptionPad1Header::~Ipv6OptionPad1Header () virtual
Destructor.
Definition at line 142 of file ipv6-option-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::Ipv6OptionPad1Header::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start Buffer iterator
Returns
size of the packet
Reimplemented from ns3::Ipv6OptionHeader.
Definition at line 163 of file ipv6-option-header.cc.
References GetSerializedSize(), ns3::Buffer::Iterator::ReadU8(), ns3::Ipv6OptionHeader::SetType(), and visualizer.core::start().
GetInstanceTypeId()
TypeId ns3::Ipv6OptionPad1Header::GetInstanceTypeId () const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::Ipv6OptionHeader.
Definition at line 132 of file ipv6-option-header.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::Ipv6OptionPad1Header::GetSerializedSize () const virtual
Get the serialized size of the packet.
Returns
size
Reimplemented from ns3::Ipv6OptionHeader.
Definition at line 151 of file ipv6-option-header.cc.
Referenced by Deserialize(), and ns3::Ipv6OptionPad1::Process().
GetTypeId()
TypeId ns3::Ipv6OptionPad1Header::GetTypeId () static
Get the type identificator.
Returns
type identificator
Definition at line 122 of file ipv6-option-header.cc.
References ns3::TypeId::AddConstructor().
Referenced by GetInstanceTypeId().
Print()
void ns3::Ipv6OptionPad1Header::Print (std::ostream & os) const virtual
Print some information about the packet.
Parameters
os output stream
Returns
info about this packet
Reimplemented from ns3::Ipv6OptionHeader.
Definition at line 146 of file ipv6-option-header.cc.
References ns3::Ipv6OptionHeader::GetType().
Serialize()
void ns3::Ipv6OptionPad1Header::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start Buffer iterator
Reimplemented from ns3::Ipv6OptionHeader.
Definition at line 156 of file ipv6-option-header.cc.
References ns3::Ipv6OptionHeader::GetType(), visualizer.core::start(), and ns3::Buffer::Iterator::WriteU8().
Referenced by ns3::OptionField::Serialize().
The documentation for this class was generated from the following files:
src/internet/model/ipv6-option-header.h
src/internet/model/ipv6-option-header.cc