ns-3: ns3::CandidateQueue Class Reference
ns3::CandidateQueue Class Reference
Internet » IPv4 Routing Protocols. » Global Routing.
A Candidate Queue used in routing calculations.
#include "candidate-queue.h"
Public Member Functions
CandidateQueue ()
Create an empty SPF Candidate Queue.
virtual ~CandidateQueue ()
Destroy an SPF Candidate Queue and release any resources held by the contents.
void Clear (void)
Empty the Candidate Queue and release all of the resources associated with the Shortest Path First Vertex pointers in the queue.
bool Empty (void) const
Test the Candidate Queue to determine if it is empty.
SPFVertex * Find (const Ipv4Address addr) const
Searches the Candidate Queue for a Shortest Path First Vertex pointer that points to a vertex having the given IP address.
SPFVertex * Pop (void)
Pop the Shortest Path First Vertex pointer at the top of the queue.
void Push (SPFVertex *vNew)
Push a Shortest Path First Vertex pointer onto the queue according to the priority scheme.
void Reorder (void)
Reorders the Candidate Queue according to the priority scheme.
uint32_t Size (void) const
Return the number of Shortest Path First Vertex pointers presently stored in the Candidate Queue.
SPFVertex * Top (void) const
Return the Shortest Path First Vertex pointer at the top of the queue.
Private Types
typedef std::list< SPFVertex * > CandidateList_t
container of SPFVertex pointers
Private Member Functions
CandidateQueue (CandidateQueue &sr)
Candidate Queue copy construction is disallowed (not implemented) to prevent the compiler from slipping in incorrect versions that don't properly deal with deep copies.
CandidateQueue & operator= (CandidateQueue &sr)
Candidate Queue assignment operator is disallowed (not implemented) to prevent the compiler from slipping in incorrect versions that don't properly deal with deep copies.
Static Private Member Functions
static bool CompareSPFVertex (const SPFVertex *v1, const SPFVertex *v2)
return true if v1 < v2
Private Attributes
CandidateList_t m_candidates
SPFVertex candidates.
Friends
std::ostream & operator<< (std::ostream &os, const CandidateQueue &q)
Stream insertion operator.
Detailed Description
A Candidate Queue used in routing calculations.
The CandidateQueue is used in the OSPF shortest path computations. It is a priority queue used to store candidates for the shortest path to a given network.
The queue holds Shortest Path First Vertex pointers and orders them according to the lowest value of the field m_distanceFromRoot. Remaining vertices are ordered according to increasing distance. This implements a priority queue.
Although a STL priority_queue almost does what we want, the requirement for a Find () operation, the dynamic nature of the data and the derived requirement for a Reorder () operation led us to implement this simple enhanced priority queue.
Definition at line 51 of file candidate-queue.h.
Member Typedef Documentation
CandidateList_t
typedef std::list<SPFVertex*> ns3::CandidateQueue::CandidateList_t private
container of SPFVertex pointers
Definition at line 187 of file candidate-queue.h.
Constructor & Destructor Documentation
CandidateQueue() [1/2]
ns3::CandidateQueue::CandidateQueue ()
Create an empty SPF Candidate Queue.
See also
SPFVertex
Definition at line 68 of file candidate-queue.cc.
References NS_LOG_FUNCTION.
~CandidateQueue()
ns3::CandidateQueue::~CandidateQueue () virtual
Destroy an SPF Candidate Queue and release any resources held by the contents.
See also
SPFVertex
Definition at line 74 of file candidate-queue.cc.
References Clear(), and NS_LOG_FUNCTION.
CandidateQueue() [2/2]
ns3::CandidateQueue::CandidateQueue (CandidateQueue & sr) private
Candidate Queue copy construction is disallowed (not implemented) to prevent the compiler from slipping in incorrect versions that don't properly deal with deep copies.
Parameters
sr object to copy
Member Function Documentation
Clear()
void ns3::CandidateQueue::Clear (void)
Empty the Candidate Queue and release all of the resources associated with the Shortest Path First Vertex pointers in the queue.
See also
SPFVertex
Definition at line 81 of file candidate-queue.cc.
References m_candidates, NS_LOG_FUNCTION, and Pop().
Referenced by ~CandidateQueue().
CompareSPFVertex()
bool ns3::CandidateQueue::CompareSPFVertex (const SPFVertex * v1, const SPFVertex * v2) static private
return true if v1 < v2
SPFVertexes are added into the queue according to the ordering defined by this method. If v1 should be popped before v2, this method return true; false otherwise
Parameters
v1 first operand
v2 second operand
Returns
True if v1 should be popped before v2; false otherwise
Definition at line 180 of file candidate-queue.cc.
References ns3::SPFVertex::GetDistanceFromRoot(), ns3::SPFVertex::GetVertexType(), NS_LOG_FUNCTION, ns3::SPFVertex::VertexNetwork, and ns3::SPFVertex::VertexRouter.
Referenced by Push(), and Reorder().
Empty()
bool ns3::CandidateQueue::Empty (void) const
Test the Candidate Queue to determine if it is empty.
Returns
True if the queue is empty, false otherwise.
Definition at line 131 of file candidate-queue.cc.
References m_candidates, and NS_LOG_FUNCTION.
Find()
SPFVertex * ns3::CandidateQueue::Find (const Ipv4Address addr) const
Searches the Candidate Queue for a Shortest Path First Vertex pointer that points to a vertex having the given IP address.
See also
SPFVertex
Parameters
addr The IP address to search for.
Returns
The SPFVertex* pointer corresponding to the given IP address.
Definition at line 145 of file candidate-queue.cc.
References ns3::SPFVertex::GetVertexId(), m_candidates, and NS_LOG_FUNCTION.
Referenced by ns3::GlobalRouteManagerImpl::SPFNext().
operator=()
CandidateQueue& ns3::CandidateQueue::operator= (CandidateQueue & sr) private
Candidate Queue assignment operator is disallowed (not implemented) to prevent the compiler from slipping in incorrect versions that don't properly deal with deep copies.
Parameters
sr object to assign
Returns
copied object
Pop()
SPFVertex * ns3::CandidateQueue::Pop (void)
Pop the Shortest Path First Vertex pointer at the top of the queue.
The caller is given the responsibility for releasing the resources associated with the vertex.
See also
SPFVertex
Top ()
Returns
The Shortest Path First Vertex pointer at the top of the queue.
Definition at line 105 of file candidate-queue.cc.
References m_candidates, and NS_LOG_FUNCTION.
Referenced by Clear(), GlobalRouteManagerImplTestCase::DoRun(), and ns3::GlobalRouteManagerImpl::SPFCalculate().
Push()
void ns3::CandidateQueue::Push (SPFVertex * vNew)
Push a Shortest Path First Vertex pointer onto the queue according to the priority scheme.
On completion, the top of the queue will hold the Shortest Path First Vertex pointer that points to a vertex having lowest value of the field m_distanceFromRoot. Remaining vertices are ordered according to increasing distance.
See also
SPFVertex
Parameters
vNew The Shortest Path First Vertex to add to the queue.
Definition at line 93 of file candidate-queue.cc.
References CompareSPFVertex(), m_candidates, and NS_LOG_FUNCTION.
Referenced by GlobalRouteManagerImplTestCase::DoRun(), and ns3::GlobalRouteManagerImpl::SPFNext().
Reorder()
void ns3::CandidateQueue::Reorder (void)
Reorders the Candidate Queue according to the priority scheme.
On completion, the top of the queue will hold the Shortest Path First Vertex pointer that points to a vertex having lowest value of the field m_distanceFromRoot. Remaining vertices are ordered according to increasing distance.
This method is provided in case the values of m_distanceFromRoot change during the routing calculations.
See also
SPFVertex
Definition at line 163 of file candidate-queue.cc.
References CompareSPFVertex(), m_candidates, NS_LOG_FUNCTION, and NS_LOG_LOGIC().
Referenced by ns3::GlobalRouteManagerImpl::SPFNext().
Size()
uint32_t ns3::CandidateQueue::Size (void) const
Return the number of Shortest Path First Vertex pointers presently stored in the Candidate Queue.
See also
SPFVertex
Returns
The number of SPFVertex* pointers in the Candidate Queue.
Definition at line 138 of file candidate-queue.cc.
References m_candidates, and NS_LOG_FUNCTION.
Referenced by ns3::GlobalRouteManagerImpl::SPFCalculate().
Top()
SPFVertex * ns3::CandidateQueue::Top (void) const
Return the Shortest Path First Vertex pointer at the top of the queue.
This method does not pop the SPFVertex* off of the queue, it simply returns the pointer.
See also
SPFVertex
Pop ()
Returns
The Shortest Path First Vertex pointer at the top of the queue.
Definition at line 119 of file candidate-queue.cc.
References m_candidates, and NS_LOG_FUNCTION.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const CandidateQueue & q) friend
Stream insertion operator.
Parameters
os the reference to the output stream
q the CandidateQueue
Returns
the reference to the output stream
Definition at line 49 of file candidate-queue.cc.
Member Data Documentation
m_candidates
CandidateList_t ns3::CandidateQueue::m_candidates private
SPFVertex candidates.
Definition at line 188 of file candidate-queue.h.
Referenced by Clear(), Empty(), Find(), ns3::operator<<(), Pop(), Push(), Reorder(), Size(), and Top().
The documentation for this class was generated from the following files:
src/internet/model/candidate-queue.h
src/internet/model/candidate-queue.cc