ns-3: TimestampValueTestCase Class Reference
TimestampValueTestCase Class Reference
Internet » internet module tests | Test suites
TCP TimeStamp values Test.
Public Member Functions
TimestampValueTestCase (double startTime, double timeToWait, std::string name)
Constructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void Check ()
Perform the test checks.
virtual void DoRun (void)
Implementation to actually run this TestCase.
virtual void DoTeardown (void)
Implementation to do any local setup required for this TestCase.
void Init ()
Test initialization.
Private Attributes
double m_initValue
Initialization value (Seconds).
double m_startTime
Start time (Seconds).
double m_timeToWait
Time to wait (Seconds).
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
TCP TimeStamp values Test.
Definition at line 211 of file tcp-timestamp-test.cc.
Constructor & Destructor Documentation
TimestampValueTestCase()
TimestampValueTestCase::TimestampValueTestCase (double startTime, double timeToWait, std::string name)
Constructor.
Parameters
startTime Start time (Seconds).
timeToWait Time to wait (Seconds).
name Test description.
Definition at line 241 of file tcp-timestamp-test.cc.
References m_startTime, m_timeToWait, and startTime.
Member Function Documentation
Check()
void TimestampValueTestCase::Check () private
Perform the test checks.
Definition at line 274 of file tcp-timestamp-test.cc.
References m_initValue, m_timeToWait, ns3::MilliSeconds(), NS_TEST_ASSERT_MSG_EQ_TOL, and ns3::Seconds().
Referenced by DoRun().
DoRun()
void TimestampValueTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 251 of file tcp-timestamp-test.cc.
References Check(), Init(), m_startTime, m_timeToWait, and ns3::Seconds().
DoTeardown()
void TimestampValueTestCase::DoTeardown (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test teardown
Reimplemented from ns3::TestCase.
Definition at line 262 of file tcp-timestamp-test.cc.
Init()
void TimestampValueTestCase::Init () private
Test initialization.
Definition at line 268 of file tcp-timestamp-test.cc.
References m_initValue.
Referenced by DoRun().
Member Data Documentation
m_initValue
double TimestampValueTestCase::m_initValue private
Initialization value (Seconds).
Definition at line 238 of file tcp-timestamp-test.cc.
Referenced by Check(), and Init().
m_startTime
double TimestampValueTestCase::m_startTime private
Start time (Seconds).
Definition at line 236 of file tcp-timestamp-test.cc.
Referenced by TimestampValueTestCase(), and DoRun().
m_timeToWait
double TimestampValueTestCase::m_timeToWait private
Time to wait (Seconds).
Definition at line 237 of file tcp-timestamp-test.cc.
Referenced by TimestampValueTestCase(), Check(), and DoRun().
The documentation for this class was generated from the following file:
src/internet/test/tcp-timestamp-test.cc