ns-3: LteRlcUmE2eTestCase Class Reference
LteRlcUmE2eTestCase Class Reference
LTE Models » lte module tests | Test suites
Test end-to-end flow when RLC UM is being used.
#include "lte-test-rlc-um-e2e.h"
Public Member Functions
LteRlcUmE2eTestCase ()
LteRlcUmE2eTestCase (std::string name, uint32_t seed, double losses)
Constructor.
virtual ~LteRlcUmE2eTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void DlDropEvent (Ptr< const Packet > p)
DL drop event.
virtual void DoRun (void)
Implementation to actually run this TestCase.
void UlDropEvent (Ptr< const Packet > p)
UL drop event.
Private Attributes
uint32_t m_dlDrops
number of Dl drops
double m_losses
error rate
uint32_t m_seed
random number seed
uint32_t m_ulDrops
number of UL drops
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test end-to-end flow when RLC UM is being used.
Definition at line 49 of file lte-test-rlc-um-e2e.h.
Constructor & Destructor Documentation
LteRlcUmE2eTestCase() [1/2]
LteRlcUmE2eTestCase::LteRlcUmE2eTestCase (std::string name, uint32_t seed, double losses)
Constructor.
TestCase.
Parameters
name the reference name
seed the random variable seed
losses the error rate
Definition at line 86 of file lte-test-rlc-um-e2e.cc.
References m_dlDrops, m_losses, m_seed, and m_ulDrops.
LteRlcUmE2eTestCase() [2/2]
LteRlcUmE2eTestCase::LteRlcUmE2eTestCase ()
~LteRlcUmE2eTestCase()
LteRlcUmE2eTestCase::~LteRlcUmE2eTestCase () virtual
Definition at line 98 of file lte-test-rlc-um-e2e.cc.
Member Function Documentation
DlDropEvent()
void LteRlcUmE2eTestCase::DlDropEvent (Ptr< const Packet > p) private
DL drop event.
Parameters
p the packet
Definition at line 104 of file lte-test-rlc-um-e2e.cc.
References m_dlDrops.
Referenced by DoRun().
DoRun()
void LteRlcUmE2eTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 118 of file lte-test-rlc-um-e2e.cc.
References ns3::NodeContainer::Create(), DlDropEvent(), ns3::NetDeviceContainer::Get(), ns3::LteSimpleHelper::InstallEnbDevice(), ns3::LteSimpleHelper::InstallUeDevice(), m_dlDrops, ns3::LteSimpleHelper::m_enbMac, ns3::LteSimpleHelper::m_enbRrc, m_losses, m_seed, ns3::LteSimpleHelper::m_ueMac, ns3::LteSimpleHelper::m_ueRrc, m_ulDrops, ns3::MakeCallback(), NS_LOG_INFO, NS_TEST_ASSERT_MSG_EQ, ns3::Seconds(), ns3::ObjectBase::SetAttribute(), ns3::LteTestMac::SetTxOpportunityMode(), ns3::LteTestMac::SetTxOppSize(), ns3::LteTestMac::SetTxOppTime(), and UlDropEvent().
UlDropEvent()
void LteRlcUmE2eTestCase::UlDropEvent (Ptr< const Packet > p) private
UL drop event.
Parameters
p the packet
Definition at line 111 of file lte-test-rlc-um-e2e.cc.
References m_ulDrops.
Referenced by DoRun().
Member Data Documentation
m_dlDrops
uint32_t LteRlcUmE2eTestCase::m_dlDrops private
number of Dl drops
Definition at line 77 of file lte-test-rlc-um-e2e.h.
Referenced by LteRlcUmE2eTestCase(), DlDropEvent(), and DoRun().
m_losses
double LteRlcUmE2eTestCase::m_losses private
error rate
Definition at line 81 of file lte-test-rlc-um-e2e.h.
Referenced by LteRlcUmE2eTestCase(), and DoRun().
m_seed
uint32_t LteRlcUmE2eTestCase::m_seed private
random number seed
Definition at line 80 of file lte-test-rlc-um-e2e.h.
Referenced by LteRlcUmE2eTestCase(), and DoRun().
m_ulDrops
uint32_t LteRlcUmE2eTestCase::m_ulDrops private
number of UL drops
Definition at line 78 of file lte-test-rlc-um-e2e.h.
Referenced by LteRlcUmE2eTestCase(), DoRun(), and UlDropEvent().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-rlc-um-e2e.h
src/lte/test/lte-test-rlc-um-e2e.cc