ns-3: ns3::UanPhyPerCommonModes Class Reference
ns3::UanPhyPerCommonModes Class Reference
UAN Models
#include "uan-phy-gen.h"
Public Member Functions
UanPhyPerCommonModes ()
Constructor.
virtual ~UanPhyPerCommonModes ()
Destructor.
virtual double CalcPer (Ptr< Packet > pkt, double sinrDb, UanTxMode mode)
Calculate the Packet ERror probability based on SINR at the receiver and a tx mode.
Public Member Functions inherited from ns3::UanPhyPer
virtual void Clear (void)
Clear all pointer references.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::UanPhyPer
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::UanPhyPer
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Packet error rate calculation for common tx modes based on UanPhyPerUmodem
Calculates PER for common UanTxMode modulations, by deriving PER from the BER taken from well known literature's formulas.
Definition at line 126 of file uan-phy-gen.h.
Constructor & Destructor Documentation
UanPhyPerCommonModes()
ns3::UanPhyPerCommonModes::UanPhyPerCommonModes ()
Constructor.
Definition at line 252 of file uan-phy-gen.cc.
~UanPhyPerCommonModes()
ns3::UanPhyPerCommonModes::~UanPhyPerCommonModes () virtual
Destructor.
Definition at line 258 of file uan-phy-gen.cc.
Member Function Documentation
CalcPer()
double ns3::UanPhyPerCommonModes::CalcPer (Ptr< Packet > pkt, double sinrDb, UanTxMode mode) virtual
Calculate the Packet ERror probability based on SINR at the receiver and a tx mode.
This implementation calculates PER for common UanTxMode modulations, by deriving PER from the BER taken from literature's formulas.
Parameters
pkt Packet which is under consideration.
sinrDb SINR at receiver.
mode TX mode used to transmit packet.
Returns
Probability of packet error.
Implements ns3::UanPhyPer.
Definition at line 275 of file uan-phy-gen.cc.
References ns3::UanTxMode::FSK, ns3::UanTxMode::GetBandwidthHz(), ns3::UanTxMode::GetConstellationSize(), ns3::UanTxMode::GetDataRateBps(), ns3::UanTxMode::GetModType(), ns3::Packet::GetSize(), NS_FATAL_ERROR, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::UanTxMode::PSK, and ns3::UanTxMode::QAM.
GetTypeId()
TypeId ns3::UanPhyPerCommonModes::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 264 of file uan-phy-gen.cc.
References ns3::TypeId::SetParent().
The documentation for this class was generated from the following files:
src/uan/model/uan-phy-gen.h
src/uan/model/uan-phy-gen.cc