ns-3: ns3::RocketfuelTopologyReader Class Reference
ns3::RocketfuelTopologyReader Class Reference
Topology Input Readers
Topology file reader (Rocketfuel-format type).
#include "rocketfuel-topology-reader.h"
Public Member Functions
RocketfuelTopologyReader ()
virtual ~RocketfuelTopologyReader ()
virtual NodeContainer Read (void)
Main topology reading function.
Public Member Functions inherited from ns3::TopologyReader
TopologyReader ()
virtual ~TopologyReader ()
void AddLink (Link link)
Adds a link to the topology.
std::string GetFileName (void) const
Returns the input file name.
ConstLinksIterator LinksBegin (void) const
Returns an iterator to the the first link in this block.
bool LinksEmpty (void) const
Checks if the block contains any links.
ConstLinksIterator LinksEnd (void) const
Returns an iterator to the the last link in this block.
int LinksSize (void) const
Returns the number of links in this block.
void SetFileName (const std::string &fileName)
Sets the input file name.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TopologyReader
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
enum RF_FileType { RF_MAPS, RF_WEIGHTS, RF_UNKNOWN }
Enum of the possible file types.
Private Member Functions
RocketfuelTopologyReader (const RocketfuelTopologyReader &)
Copy constructor.
NodeContainer GenerateFromMapsFile (int argc, char *argv[])
Topology read function from a file containing the nodes map.
NodeContainer GenerateFromWeightsFile (int argc, char *argv[])
Topology read function from a file containing the nodes weights.
enum RF_FileType GetFileType (const char *)
Classifies the file type according to its content.
RocketfuelTopologyReader & operator= (const RocketfuelTopologyReader &)
Copy constructor.
Private Attributes
int m_linksNumber
Number of links.
std::map< std::string, Ptr< Node > > m_nodeMap
Map of the nodes (name, node).
int m_nodesNumber
Number of nodes.
Additional Inherited Members
Public Types inherited from ns3::TopologyReader
typedef std::list< Link >::const_iterator ConstLinksIterator
Constant iterator to the list of the links.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Topology file reader (Rocketfuel-format type).
http://www.cs.washington.edu/research/networking/rocketfuel/
May 2nd, 2010: Currently only support "weights" file and "cch" file. http://www.cs.washington.edu/research/networking/rocketfuel/maps/weights-dist.tar.gz http://www.cs.washington.edu/research/networking/rocketfuel/maps/rocketfuel_maps_cch.tar.gz
Definition at line 48 of file rocketfuel-topology-reader.h.
Member Enumeration Documentation
RF_FileType
enum ns3::RocketfuelTopologyReader::RF_FileType private
Enum of the possible file types.
Enumerator
RF_MAPS
RF_WEIGHTS
RF_UNKNOWN
Definition at line 100 of file rocketfuel-topology-reader.h.
Constructor & Destructor Documentation
RocketfuelTopologyReader() [1/2]
ns3::RocketfuelTopologyReader::RocketfuelTopologyReader ()
Definition at line 53 of file rocketfuel-topology-reader.cc.
References m_linksNumber, m_nodesNumber, and NS_LOG_FUNCTION.
~RocketfuelTopologyReader()
ns3::RocketfuelTopologyReader::~RocketfuelTopologyReader () virtual
Definition at line 60 of file rocketfuel-topology-reader.cc.
References NS_LOG_FUNCTION.
RocketfuelTopologyReader() [2/2]
ns3::RocketfuelTopologyReader::RocketfuelTopologyReader (const RocketfuelTopologyReader &) private
Copy constructor.
Defined and unimplemented to avoid misuse.
Member Function Documentation
GenerateFromMapsFile()
NodeContainer ns3::RocketfuelTopologyReader::GenerateFromMapsFile (int argc, char * argv[]) private
Topology read function from a file containing the nodes map.
Parser for the *.cch file available at: http://www.cs.washington.edu/research/networking/rocketfuel/maps/rocketfuel_maps_cch.tar.gz
Parameters
[in] argc Argument counter.
[in] argv Argument vector.
Returns
The container of the nodes created (or empty container if there was an error).
Definition at line 110 of file rocketfuel-topology-reader.cc.
References ns3::TopologyReader::AddLink(), m_linksNumber, m_nodeMap, m_nodesNumber, first::nodes, NS_LOG_INFO, NS_LOG_WARN, ns3::PrintNodeInfo(), and radius.
Referenced by Read().
GenerateFromWeightsFile()
NodeContainer ns3::RocketfuelTopologyReader::GenerateFromWeightsFile (int argc, char * argv[]) private
Topology read function from a file containing the nodes weights.
Parser for the weights.* file available at: http://www.cs.washington.edu/research/networking/rocketfuel/maps/weights-dist.tar.gz
Parameters
[in] argc Argument counter.
[in] argv Argument vector.
Returns
The container of the nodes created (or empty container if there was an error).
Definition at line 225 of file rocketfuel-topology-reader.cc.
Referenced by Read().
GetFileType()
enum RocketfuelTopologyReader::RF_FileType ns3::RocketfuelTopologyReader::GetFileType (const char * line) private
Classifies the file type according to its content.
Returns
The file type (RF_MAPS, RF_WEIGHTS, or RF_UNKNOWN)
Definition at line 225 of file rocketfuel-topology-reader.cc.
References ns3::TopologyReader::AddLink(), ns3::TopologyReader::LinksBegin(), ns3::TopologyReader::LinksEnd(), m_linksNumber, m_nodeMap, m_nodesNumber, first::nodes, NS_LOG_INFO, NS_LOG_WARN, and NS_UNUSED.
Referenced by Read().
GetTypeId()
TypeId ns3::RocketfuelTopologyReader::GetTypeId (void) static
Get the type ID.
Returns
The object TypeId
Definition at line 43 of file rocketfuel-topology-reader.cc.
References ns3::TypeId::SetParent().
operator=()
RocketfuelTopologyReader& ns3::RocketfuelTopologyReader::operator= (const RocketfuelTopologyReader &) private
Copy constructor.
Defined and unimplemented to avoid misuse.
Returns
Read()
NodeContainer ns3::RocketfuelTopologyReader::Read (void) virtual
Main topology reading function.
This method opens an input stream and reads the Rocketfuel-format file. Every row represents a topology link (the ids of a couple of nodes), so the input file is read line by line to figure out how many links and nodes are in the topology.
Returns
The container of the nodes created (or empty container if there was an error)
Implements ns3::TopologyReader.
Definition at line 330 of file rocketfuel-topology-reader.cc.
References GenerateFromMapsFile(), GenerateFromWeightsFile(), ns3::TopologyReader::GetFileName(), GetFileType(), first::nodes, NS_LOG_INFO, NS_LOG_WARN, REGMATCH_MAX, RF_MAPS, RF_UNKNOWN, RF_WEIGHTS, ROCKETFUEL_MAPS_LINE, and ROCKETFUEL_WEIGHTS_LINE.
Referenced by RocketfuelTopologyReaderTest::DoRun().
Member Data Documentation
m_linksNumber
int ns3::RocketfuelTopologyReader::m_linksNumber private
Number of links.
Definition at line 115 of file rocketfuel-topology-reader.h.
Referenced by RocketfuelTopologyReader(), GenerateFromMapsFile(), and GetFileType().
m_nodeMap
std::map<std::string, Ptr<Node> > ns3::RocketfuelTopologyReader::m_nodeMap private
Map of the nodes (name, node).
Definition at line 117 of file rocketfuel-topology-reader.h.
Referenced by GenerateFromMapsFile(), and GetFileType().
m_nodesNumber
int ns3::RocketfuelTopologyReader::m_nodesNumber private
Number of nodes.
Definition at line 116 of file rocketfuel-topology-reader.h.
Referenced by RocketfuelTopologyReader(), GenerateFromMapsFile(), and GetFileType().
The documentation for this class was generated from the following files:
src/topology-read/model/rocketfuel-topology-reader.h
src/topology-read/model/rocketfuel-topology-reader.cc