ns-3: FemtocellBlockAllocator Class Reference
FemtocellBlockAllocator Class Reference
Class that takes care of installing blocks of the buildings in a given area.
Public Member Functions
FemtocellBlockAllocator (Box area, uint32_t nApartmentsX, uint32_t nFloors)
Constructor.
void Create ()
Create function.
void Create (uint32_t n)
Function that creates building blocks.
Private Member Functions
bool OverlapsWithAnyPrevious (Box box)
Function that checks if the box area is overlapping with some of previously created building blocks.
Private Attributes
Box m_area
Area.
uint32_t m_nApartmentsX
X apartments.
uint32_t m_nFloors
number of floors
std::list< Box > m_previousBlocks
previous bocks
Ptr< UniformRandomVariable > m_xMinVar
X minimum variance.
double m_xSize
X size.
Ptr< UniformRandomVariable > m_yMinVar
Y minimum variance.
double m_ySize
Y size.
Detailed Description
Class that takes care of installing blocks of the buildings in a given area.
Buildings are installed in pairs as in dual stripe scenario.
Definition at line 55 of file lena-dual-stripe.cc.
Constructor & Destructor Documentation
FemtocellBlockAllocator()
FemtocellBlockAllocator::FemtocellBlockAllocator (Box area, uint32_t nApartmentsX, uint32_t nFloors)
Constructor.
Parameters
area the total area
nApartmentsX the number of apartments in the X direction
nFloors the number of floors
Definition at line 91 of file lena-dual-stripe.cc.
References m_xMinVar, m_xSize, m_yMinVar, m_ySize, ns3::ObjectBase::SetAttribute(), ns3::Box::xMax, ns3::Box::xMin, ns3::Box::yMax, and ns3::Box::yMin.
Member Function Documentation
Create() [1/2]
void FemtocellBlockAllocator::Create ()
Create function.
Definition at line 116 of file lena-dual-stripe.cc.
References ns3::GridBuildingAllocator::Create(), ns3::UniformRandomVariable::GetValue(), m_nApartmentsX, m_nFloors, m_previousBlocks, m_xMinVar, m_xSize, m_yMinVar, m_ySize, NS_ASSERT_MSG(), NS_LOG_LOGIC(), OverlapsWithAnyPrevious(), ns3::ObjectBase::SetAttribute(), ns3::GridBuildingAllocator::SetBuildingAttribute(), ns3::Box::xMax, ns3::Box::xMin, ns3::Box::yMax, and ns3::Box::yMin.
Referenced by Create().
Create() [2/2]
void FemtocellBlockAllocator::Create (uint32_t n)
Function that creates building blocks.
Parameters
n the number of blocks to create
Definition at line 107 of file lena-dual-stripe.cc.
References Create(), and sample-rng-plot::n.
OverlapsWithAnyPrevious()
bool FemtocellBlockAllocator::OverlapsWithAnyPrevious (Box box) private
Function that checks if the box area is overlapping with some of previously created building blocks.
Parameters
box the area to check
Returns
true if there is an overlap
Definition at line 150 of file lena-dual-stripe.cc.
References AreOverlapping(), and m_previousBlocks.
Referenced by Create().
Member Data Documentation
m_area
Box FemtocellBlockAllocator::m_area private
Area.
Definition at line 80 of file lena-dual-stripe.cc.
m_nApartmentsX
uint32_t FemtocellBlockAllocator::m_nApartmentsX private
X apartments.
Definition at line 81 of file lena-dual-stripe.cc.
Referenced by Create().
m_nFloors
uint32_t FemtocellBlockAllocator::m_nFloors private
number of floors
Definition at line 82 of file lena-dual-stripe.cc.
Referenced by Create().
m_previousBlocks
std::list<Box> FemtocellBlockAllocator::m_previousBlocks private
previous bocks
Definition at line 83 of file lena-dual-stripe.cc.
Referenced by Create(), and OverlapsWithAnyPrevious().
m_xMinVar
Ptr<UniformRandomVariable> FemtocellBlockAllocator::m_xMinVar private
X minimum variance.
Definition at line 86 of file lena-dual-stripe.cc.
Referenced by FemtocellBlockAllocator(), and Create().
m_xSize
double FemtocellBlockAllocator::m_xSize private
X size.
Definition at line 84 of file lena-dual-stripe.cc.
Referenced by FemtocellBlockAllocator(), and Create().
m_yMinVar
Ptr<UniformRandomVariable> FemtocellBlockAllocator::m_yMinVar private
Y minimum variance.
Definition at line 87 of file lena-dual-stripe.cc.
Referenced by FemtocellBlockAllocator(), and Create().
m_ySize
double FemtocellBlockAllocator::m_ySize private
Y size.
Definition at line 85 of file lena-dual-stripe.cc.
Referenced by FemtocellBlockAllocator(), and Create().
The documentation for this class was generated from the following file:
src/lte/examples/lena-dual-stripe.cc