ns-3: LteCellSelectionTestCase Class Reference
LteCellSelectionTestCase Class Reference
LTE Models
Testing the initial cell selection procedure by UE at IDLE state in the beginning of simulation.
#include "lte-test-cell-selection.h"
Classes
struct UeSetup_t
A set of input parameters for setting up a UE in the simulation.
Public Member Functions
LteCellSelectionTestCase (std::string name, bool isEpcMode, bool isIdealRrc, double interSiteDistance, std::vector< UeSetup_t > ueSetupList, uint64_t rngRun)
Creates an instance of the initial cell selection test case.
virtual ~LteCellSelectionTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CheckPoint (Ptr< LteUeNetDevice > ueDev, uint16_t expectedCellId1, uint16_t expectedCellId2)
Verifies if the given UE is attached to either of the given two cells and in a CONNECTED_NORMALLY state.
void ConnectionEstablishedCallback (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti)
Connection established callback function.
virtual void DoRun ()
Setup the simulation according to the configuration set by the class constructor, run it, and verify the result.
void InitialCellSelectionEndErrorCallback (std::string context, uint64_t imsi, uint16_t cellId)
Initial cell selection end error callback function.
void InitialCellSelectionEndOkCallback (std::string context, uint64_t imsi, uint16_t cellId)
Initial cell selection end ok callback function.
void StateTransitionCallback (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti, LteUeRrc::State oldState, LteUeRrc::State newState)
State transition callback function.
Private Attributes
double m_interSiteDistance
inter site distance
bool m_isEpcMode
whether the LTE configuration in test is using EPC
bool m_isIdealRrc
whether the LTE is configured to use ideal RRC
std::vector< LteUeRrc::State > m_lastState
The current UE RRC state.
uint64_t m_rngRun
rng run
std::vector< UeSetup_t > m_ueSetupList
UE setup list.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Testing the initial cell selection procedure by UE at IDLE state in the beginning of simulation.
Definition at line 63 of file lte-test-cell-selection.h.
Constructor & Destructor Documentation
LteCellSelectionTestCase()
LteCellSelectionTestCase::LteCellSelectionTestCase (std::string name, bool isEpcMode, bool isIdealRrc, double interSiteDistance, std::vector< UeSetup_t > ueSetupList, uint64_t rngRun)
Creates an instance of the initial cell selection test case.
Parameters
name name of this test
isEpcMode set to true for setting up simulation with EPC enabled
isIdealRrc if true, simulation uses Ideal RRC protocol, otherwise simulation uses Real RRC protocol
interSiteDistance the distance between eNodeB in meters
ueSetupList a list of UE configuration to be installed in the simulation
rngRun the number of run to be used by the random number generator
Definition at line 130 of file lte-test-cell-selection.cc.
References ns3::TestCase::GetName(), m_lastState, m_ueSetupList, and NS_LOG_FUNCTION.
~LteCellSelectionTestCase()
LteCellSelectionTestCase::~LteCellSelectionTestCase () virtual
Definition at line 146 of file lte-test-cell-selection.cc.
References ns3::TestCase::GetName(), and NS_LOG_FUNCTION.
Member Function Documentation
CheckPoint()
void LteCellSelectionTestCase::CheckPoint (Ptr< LteUeNetDevice > ueDev, uint16_t expectedCellId1, uint16_t expectedCellId2) private
Verifies if the given UE is attached to either of the given two cells and in a CONNECTED_NORMALLY state.
Parameters
ueDev the UE device
expectedCellId1 the first cell ID
expectedCellId2 the second cell ID
Definition at line 361 of file lte-test-cell-selection.cc.
References ns3::LteUeNetDevice::GetImsi(), ns3::LteUeNetDevice::GetRrc(), m_lastState, and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
ConnectionEstablishedCallback()
void LteCellSelectionTestCase::ConnectionEstablishedCallback (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti) private
Connection established callback function.
Parameters
context the context string
imsi the IMSI
cellId the cell ID
rnti the RNTI
Definition at line 422 of file lte-test-cell-selection.cc.
References NS_LOG_FUNCTION.
Referenced by DoRun().
DoRun()
void LteCellSelectionTestCase::DoRun () private virtual
Setup the simulation according to the configuration set by the class constructor, run it, and verify the result.
Implements ns3::TestCase.
Definition at line 153 of file lte-test-cell-selection.cc.
References ns3::NetDeviceContainer::Add(), ns3::ListPositionAllocator::Add(), ns3::Ipv4StaticRouting::AddNetworkRouteTo(), ns3::Ipv4AddressHelper::Assign(), ns3::LteHelper::AssignStreams(), ns3::NoBackhaulEpcHelper::AssignUeIpv4Address(), ns3::LteHelper::Attach(), ns3::NetDeviceContainer::Begin(), ns3::NodeContainer::Begin(), CheckPoint(), ns3::Config::Connect(), ConnectionEstablishedCallback(), ns3::NodeContainer::Create(), ns3::NetDeviceContainer::End(), ns3::NodeContainer::End(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::NetDeviceContainer::GetN(), ns3::NodeContainer::GetN(), ns3::TestCase::GetName(), ns3::Object::GetObject(), ns3::NoBackhaulEpcHelper::GetPgwNode(), ns3::Ipv4StaticRoutingHelper::GetStaticRouting(), ns3::NoBackhaulEpcHelper::GetUeDefaultGatewayAddress(), InitialCellSelectionEndErrorCallback(), InitialCellSelectionEndOkCallback(), ns3::PointToPointHelper::Install(), ns3::InternetStackHelper::Install(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), m_interSiteDistance, m_isEpcMode, m_isIdealRrc, m_rngRun, m_ueSetupList, ns3::MakeCallback(), ns3::MilliSeconds(), third::mobility, NS_ASSERT, NS_FATAL_ERROR, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::Seconds(), ns3::ObjectBase::SetAttribute(), ns3::Ipv4AddressHelper::SetBase(), ns3::PointToPointHelper::SetChannelAttribute(), ns3::Ipv4StaticRouting::SetDefaultRoute(), ns3::PointToPointHelper::SetDeviceAttribute(), ns3::LteHelper::SetEnbDeviceAttribute(), ns3::LteHelper::SetEpcHelper(), ns3::Config::SetGlobal(), ns3::LteHelper::SetUeDeviceAttribute(), and StateTransitionCallback().
InitialCellSelectionEndErrorCallback()
void LteCellSelectionTestCase::InitialCellSelectionEndErrorCallback (std::string context, uint64_t imsi, uint16_t cellId) private
Initial cell selection end error callback function.
Parameters
context the context string
imsi the IMSI
cellId the cell ID
Definition at line 414 of file lte-test-cell-selection.cc.
References NS_LOG_FUNCTION.
Referenced by DoRun().
InitialCellSelectionEndOkCallback()
void LteCellSelectionTestCase::InitialCellSelectionEndOkCallback (std::string context, uint64_t imsi, uint16_t cellId) private
Initial cell selection end ok callback function.
Parameters
context the context string
imsi the IMSI
cellId the cell ID
Definition at line 406 of file lte-test-cell-selection.cc.
References NS_LOG_FUNCTION.
Referenced by DoRun().
StateTransitionCallback()
void LteCellSelectionTestCase::StateTransitionCallback (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti, LteUeRrc::State oldState, LteUeRrc::State newState) private
State transition callback function.
Parameters
context the context string
imsi the IMSI
cellId the cell ID
rnti the RNTI
oldState the old state
newState the new state
Definition at line 396 of file lte-test-cell-selection.cc.
References m_lastState, and NS_LOG_FUNCTION.
Referenced by DoRun().
Member Data Documentation
m_interSiteDistance
double LteCellSelectionTestCase::m_interSiteDistance private
inter site distance
Definition at line 164 of file lte-test-cell-selection.h.
Referenced by DoRun().
m_isEpcMode
bool LteCellSelectionTestCase::m_isEpcMode private
whether the LTE configuration in test is using EPC
Definition at line 162 of file lte-test-cell-selection.h.
Referenced by DoRun().
m_isIdealRrc
bool LteCellSelectionTestCase::m_isIdealRrc private
whether the LTE is configured to use ideal RRC
Definition at line 163 of file lte-test-cell-selection.h.
Referenced by DoRun().
m_lastState
std::vector<LteUeRrc::State> LteCellSelectionTestCase::m_lastState private
The current UE RRC state.
Definition at line 169 of file lte-test-cell-selection.h.
Referenced by LteCellSelectionTestCase(), CheckPoint(), and StateTransitionCallback().
m_rngRun
uint64_t LteCellSelectionTestCase::m_rngRun private
rng run
Definition at line 166 of file lte-test-cell-selection.h.
Referenced by DoRun().
m_ueSetupList
std::vector<UeSetup_t> LteCellSelectionTestCase::m_ueSetupList private
UE setup list.
Definition at line 165 of file lte-test-cell-selection.h.
Referenced by LteCellSelectionTestCase(), and DoRun().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-cell-selection.h
src/lte/test/lte-test-cell-selection.cc