ns-3: Ipv6RipngSplitHorizonStrategyTest Class Reference
Ipv6RipngSplitHorizonStrategyTest Class Reference
Internet » internet module tests | Test suites
IPv6 RIPng SplitHorizon strategy Test.
Public Member Functions
Ipv6RipngSplitHorizonStrategyTest (RipNg::SplitHorizonType_e strategy)
Constructor.
virtual void DoRun (void)
Implementation to actually run this TestCase.
void ReceivePktProbe (Ptr< Socket > socket)
Receive data.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Attributes
RipNg::SplitHorizonType_e m_detectedStrategy
Strategy detected.
RipNg::SplitHorizonType_e m_setStrategy
Strategy set.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
IPv6 RIPng SplitHorizon strategy Test.
Definition at line 503 of file ipv6-ripng-test.cc.
Constructor & Destructor Documentation
Ipv6RipngSplitHorizonStrategyTest()
Ipv6RipngSplitHorizonStrategyTest::Ipv6RipngSplitHorizonStrategyTest (RipNg::SplitHorizonType_e strategy)
Constructor.
Parameters
strategy The SplitHorizon strategy.
Definition at line 523 of file ipv6-ripng-test.cc.
References m_setStrategy.
Member Function Documentation
DoRun()
void Ipv6RipngSplitHorizonStrategyTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 572 of file ipv6-ripng-test.cc.
References ns3::NetDeviceContainer::Add(), ns3::Node::AddDevice(), ns3::Ipv6AddressHelper::Assign(), ns3::Ipv6AddressHelper::AssignWithoutAddress(), ns3::Socket::BindToNetDevice(), ns3::SocketFactory::CreateSocket(), ns3::Object::GetObject(), ns3::InternetStackHelper::Install(), m_detectedStrategy, m_setStrategy, ns3::MakeCallback(), NS_TEST_EXPECT_MSG_EQ, ReceivePktProbe(), ns3::Seconds(), ns3::RipNgHelper::Set(), ns3::SimpleNetDevice::SetAddress(), ns3::Ipv6AddressHelper::SetBase(), ns3::SimpleNetDevice::SetChannel(), ns3::Ipv6InterfaceContainer::SetForwarding(), and ns3::InternetStackHelper::SetRoutingHelper().
ReceivePktProbe()
void Ipv6RipngSplitHorizonStrategyTest::ReceivePktProbe (Ptr< Socket > socket)
Receive data.
Parameters
socket The receiving socket.
Definition at line 529 of file ipv6-ripng-test.cc.
References ns3::RipNgHeader::GetRteList(), ns3::Socket::GetRxAvailable(), ns3::Packet::GetSize(), m_detectedStrategy, max, NS_ASSERT, NS_TEST_EXPECT_MSG_EQ, ns3::Socket::RecvFrom(), and ns3::Packet::RemoveHeader().
Referenced by DoRun().
Member Data Documentation
m_detectedStrategy
RipNg::SplitHorizonType_e Ipv6RipngSplitHorizonStrategyTest::m_detectedStrategy private
Strategy detected.
Definition at line 506 of file ipv6-ripng-test.cc.
Referenced by DoRun(), and ReceivePktProbe().
m_setStrategy
RipNg::SplitHorizonType_e Ipv6RipngSplitHorizonStrategyTest::m_setStrategy private
Strategy set.
Definition at line 505 of file ipv6-ripng-test.cc.
Referenced by Ipv6RipngSplitHorizonStrategyTest(), and DoRun().
The documentation for this class was generated from the following file:
src/internet/test/ipv6-ripng-test.cc