ns-3: DsdvHeaderTestCase Class Reference
DsdvHeaderTestCase Class Reference
DSDV module tests | Test suites
DSDV test case to verify the DSDV header.
Public Member Functions
DsdvHeaderTestCase ()
~DsdvHeaderTestCase ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
DSDV test case to verify the DSDV header.
Definition at line 62 of file dsdv-testcase.cc.
Constructor & Destructor Documentation
DsdvHeaderTestCase()
DsdvHeaderTestCase::DsdvHeaderTestCase ()
Definition at line 70 of file dsdv-testcase.cc.
~DsdvHeaderTestCase()
DsdvHeaderTestCase::~DsdvHeaderTestCase ()
Definition at line 74 of file dsdv-testcase.cc.
Member Function Documentation
DoRun()
void DsdvHeaderTestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 78 of file dsdv-testcase.cc.
References ns3::Packet::AddHeader(), ns3::dsdv::DsdvHeader::GetDst(), ns3::dsdv::DsdvHeader::GetDstSeqno(), ns3::dsdv::DsdvHeader::GetHopCount(), ns3::dsdv::DsdvHeader::GetSerializedSize(), ns3::Packet::GetSize(), NS_TEST_ASSERT_MSG_EQ, ns3::Packet::RemoveHeader(), ns3::dsdv::DsdvHeader::SetDst(), ns3::dsdv::DsdvHeader::SetDstSeqno(), and ns3::dsdv::DsdvHeader::SetHopCount().
The documentation for this class was generated from the following file:
src/dsdv/test/dsdv-testcase.cc