ns-3: Bug2831TestCase Class Reference
Bug2831TestCase Class Reference
Make sure that the channel width and the channel number can be changed at runtime.
Public Member Functions
Bug2831TestCase ()
virtual ~Bug2831TestCase ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void ChangeSupportedChannelWidth (void)
Function called to change the supported channel width at runtime.
void RxCallback (std::string context, Ptr< const Packet > p)
Callback triggered when a packet is received by the PHYs.
Private Attributes
Ptr< YansWifiPhy > m_apPhy
AP PHY.
uint8_t m_countOperationalChannelWidth20
count number of beacon frames announcing a 20 MHz operating channel width
uint8_t m_countOperationalChannelWidth40
count number of beacon frames announcing a 40 MHz operating channel width
uint8_t m_reassocReqCount
count number of reassociation requests
uint8_t m_reassocRespCount
count number of reassociation responses
Ptr< YansWifiPhy > m_staPhy
STA PHY.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Make sure that the channel width and the channel number can be changed at runtime.
The scenario considers an access point and a station using a 20 MHz channel width. After 1s, we change the channel width and the channel number to use a 40 MHz channel. The tests checks the operational channel width sent in Beacon frames and verify that a reassociation procedure is executed.
See Bug 2831
Definition at line 1523 of file wifi-test.cc.
Constructor & Destructor Documentation
Bug2831TestCase()
Bug2831TestCase::Bug2831TestCase ()
Definition at line 1551 of file wifi-test.cc.
~Bug2831TestCase()
Bug2831TestCase::~Bug2831TestCase () virtual
Definition at line 1560 of file wifi-test.cc.
Member Function Documentation
ChangeSupportedChannelWidth()
void Bug2831TestCase::ChangeSupportedChannelWidth (void) private
Function called to change the supported channel width at runtime.
Definition at line 1565 of file wifi-test.cc.
References m_apPhy, m_staPhy, ns3::WifiPhy::SetChannelNumber(), and ns3::WifiPhy::SetChannelWidth().
Referenced by DoRun().
DoRun()
void Bug2831TestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 1604 of file wifi-test.cc.
References ns3::Node::AddDevice(), ns3::Object::AggregateObject(), ChangeSupportedChannelWidth(), third::channel, ns3::WifiMac::ConfigureStandard(), ns3::WifiPhy::ConfigureStandard(), ns3::Config::Connect(), ns3::ObjectFactory::Create(), m_apPhy, m_countOperationalChannelWidth20, m_countOperationalChannelWidth40, m_reassocReqCount, m_reassocRespCount, m_staPhy, third::mac, ns3::MakeCallback(), NS_TEST_ASSERT_MSG_EQ, RxCallback(), ns3::Seconds(), ns3::WifiMac::SetAddress(), ns3::YansWifiPhy::SetChannel(), ns3::WifiPhy::SetChannelNumber(), ns3::WifiPhy::SetChannelWidth(), ns3::WifiMac::SetDevice(), ns3::WifiPhy::SetDevice(), ns3::WifiPhy::SetErrorRateModel(), ns3::WifiNetDevice::SetHtConfiguration(), ns3::WifiNetDevice::SetMac(), ns3::WifiPhy::SetMobility(), ns3::WifiNetDevice::SetPhy(), ns3::MobilityModel::SetPosition(), ns3::WifiNetDevice::SetRemoteStationManager(), ns3::ObjectFactory::SetTypeId(), and ns3::WIFI_PHY_STANDARD_80211ax_5GHZ.
RxCallback()
void Bug2831TestCase::RxCallback (std::string context, Ptr< const Packet > p) private
Callback triggered when a packet is received by the PHYs.
Parameters
context the context
p the received packet
Definition at line 1574 of file wifi-test.cc.
References ns3::Packet::Copy(), ns3::MgtProbeResponseHeader::GetHtOperation(), ns3::HtOperation::GetStaChannelWidth(), ns3::WifiMacHeader::IsBeacon(), ns3::WifiMacHeader::IsReassocReq(), ns3::WifiMacHeader::IsReassocResp(), m_countOperationalChannelWidth20, m_countOperationalChannelWidth40, m_reassocReqCount, m_reassocRespCount, and ns3::Packet::RemoveHeader().
Referenced by DoRun().
Member Data Documentation
m_apPhy
Ptr<YansWifiPhy> Bug2831TestCase::m_apPhy private
AP PHY.
Definition at line 1542 of file wifi-test.cc.
Referenced by ChangeSupportedChannelWidth(), and DoRun().
m_countOperationalChannelWidth20
uint8_t Bug2831TestCase::m_countOperationalChannelWidth20 private
count number of beacon frames announcing a 20 MHz operating channel width
Definition at line 1547 of file wifi-test.cc.
Referenced by DoRun(), and RxCallback().
m_countOperationalChannelWidth40
uint8_t Bug2831TestCase::m_countOperationalChannelWidth40 private
count number of beacon frames announcing a 40 MHz operating channel width
Definition at line 1548 of file wifi-test.cc.
Referenced by DoRun(), and RxCallback().
m_reassocReqCount
uint8_t Bug2831TestCase::m_reassocReqCount private
count number of reassociation requests
Definition at line 1545 of file wifi-test.cc.
Referenced by DoRun(), and RxCallback().
m_reassocRespCount
uint8_t Bug2831TestCase::m_reassocRespCount private
count number of reassociation responses
Definition at line 1546 of file wifi-test.cc.
Referenced by DoRun(), and RxCallback().
m_staPhy
Ptr<YansWifiPhy> Bug2831TestCase::m_staPhy private
STA PHY.
Definition at line 1543 of file wifi-test.cc.
Referenced by ChangeSupportedChannelWidth(), and DoRun().
The documentation for this class was generated from the following file:
src/wifi/test/wifi-test.cc