ns-3: ns3::dot11s::AirtimeLinkMetricCalculator Class Reference
ns3::dot11s::AirtimeLinkMetricCalculator Class Reference
Mesh Device » IEEE 802.11s draft
Airtime link metric calculator.
#include "airtime-metric.h"
Public Member Functions
AirtimeLinkMetricCalculator ()
uint32_t CalculateMetric (Mac48Address peerAddress, Ptr< MeshWifiInterfaceMac > mac)
Airtime link metric is defined in Section 13.9 of IEEE 802.11-2012 as:
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void SetHeaderTid (uint8_t tid)
Set header TID from the Dot11MetricTid attribute.
void SetTestLength (uint16_t testLength)
Set number of bytes in test frame (a constant 1024 in the standard)
Private Attributes
Ptr< Packet > m_testFrame
test frame
WifiMacHeader m_testHeader
test header
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Airtime link metric calculator.
Airtime link metric is defined in 11B.10 of 802.11s Draft D3.0 as:
airtime = (O + Bt/r)* (1 + average retry counter), where:
o – the PHY dependent channel access which includes frame headers, training sequences, access protocol frames, etc.
bt – the test packet length in bits (8192 by default),
r – the current bitrate of the packet,
Final result is expressed in units of 0.01 Time Unit = 10.24 us (as required by 802.11s draft)
Definition at line 41 of file airtime-metric.h.
Constructor & Destructor Documentation
AirtimeLinkMetricCalculator()
ns3::dot11s::AirtimeLinkMetricCalculator::AirtimeLinkMetricCalculator ()
Definition at line 52 of file airtime-metric.cc.
Member Function Documentation
CalculateMetric()
uint32_t ns3::dot11s::AirtimeLinkMetricCalculator::CalculateMetric (Mac48Address peerAddress, Ptr< MeshWifiInterfaceMac > mac)
Airtime link metric is defined in Section 13.9 of IEEE 802.11-2012 as:
airtime = (O + Bt/r) / (1 - frame error rate), where o – the PHY dependent channel access which includes frame headers, training sequences, access protocol frames, etc. bt – the test packet length in bits (8192 by default), r – the current bitrate of the packet,
Final result is expressed encoded as an unsigned integer in units of 0.01 TU = 10.24 us
Parameters
peerAddress The peer MAC address
mac The MAC layer
Returns
the calculated metric in units of 0.01 TU
Definition at line 69 of file airtime-metric.cc.
References ns3::Packet::GetSize(), ns3::Mac48Address::IsGroup(), m_testFrame, m_testHeader, third::mac, NS_ASSERT, ns3::WifiTxVector::SetMode(), ns3::WifiTxVector::SetPreambleType(), and ns3::WIFI_PREAMBLE_LONG.
Referenced by ns3::dot11s::HwmpProtocol::Install().
GetTypeId()
TypeId ns3::dot11s::AirtimeLinkMetricCalculator::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 29 of file airtime-metric.cc.
References ns3::MakeUintegerAccessor(), SetHeaderTid(), ns3::TypeId::SetParent(), and SetTestLength().
SetHeaderTid()
void ns3::dot11s::AirtimeLinkMetricCalculator::SetHeaderTid (uint8_t tid) private
Set header TID from the Dot11MetricTid attribute.
Parameters
tid the header TID to use to calculate data rate
Definition at line 56 of file airtime-metric.cc.
References m_testHeader, ns3::WifiMacHeader::SetDsFrom(), ns3::WifiMacHeader::SetDsTo(), ns3::WifiMacHeader::SetQosTid(), ns3::WifiMacHeader::SetType(), and ns3::WIFI_MAC_DATA.
Referenced by GetTypeId().
SetTestLength()
void ns3::dot11s::AirtimeLinkMetricCalculator::SetTestLength (uint16_t testLength) private
Set number of bytes in test frame (a constant 1024 in the standard)
Parameters
testLength the test length in bits
Definition at line 64 of file airtime-metric.cc.
References m_testFrame.
Referenced by GetTypeId().
Member Data Documentation
m_testFrame
Ptr<Packet> ns3::dot11s::AirtimeLinkMetricCalculator::m_testFrame private
test frame
Definition at line 79 of file airtime-metric.h.
Referenced by CalculateMetric(), and SetTestLength().
m_testHeader
WifiMacHeader ns3::dot11s::AirtimeLinkMetricCalculator::m_testHeader private
test header
Definition at line 80 of file airtime-metric.h.
Referenced by CalculateMetric(), and SetHeaderTid().
The documentation for this class was generated from the following files:
src/mesh/model/dot11s/airtime-metric.h
src/mesh/model/dot11s/airtime-metric.cc