ns-3: ns3::EutranMeasurementMapping Class Reference
ns3::EutranMeasurementMapping Class Reference
Implements the E-UTRA measurement mappings defined in 3GPP TS 36.133 section 9.1 E-UTRAN measurements.
#include "lte-common.h"
Static Public Member Functions
static int8_t ActualA3Offset2IeValue (double a3OffsetDb)
Returns the IE value of a3-Offset.
static uint8_t ActualHysteresis2IeValue (double hysteresisDb)
Returns the IE value of hysteresis.
static uint8_t Db2RsrqRange (double db)
convert an RSRQ value in dB to the corresponding range as per 3GPP TS 36.133 section 9.1.7 RSRQ Measurement Report Mapping
static uint8_t Dbm2RsrpRange (double dbm)
convert an RSRP value in dBm to the corresponding range as per 3GPP TS 36.133 section 9.1.4 RSRP Measurement Report Mapping
static double IeValue2ActualA3Offset (int8_t a3OffsetIeValue)
Returns the actual value of an a3-Offset parameter.
static double IeValue2ActualHysteresis (uint8_t hysteresisIeValue)
Returns the actual value of a hysteresis parameter.
static double IeValue2ActualQQualMin (int8_t qQualMinIeValue)
Returns the actual value of an Q-QualMin parameter.
static double IeValue2ActualQRxLevMin (int8_t qRxLevMinIeValue)
Returns the actual value of an Q-RxLevMin parameter.
static double QuantizeRsrp (double v)
Quantize an RSRP value according to the measurement mapping of TS 36.133.
static double QuantizeRsrq (double v)
Quantize an RSRQ value according to the measurement mapping of TS 36.133.
static double RsrpRange2Dbm (uint8_t range)
converts an RSRP range to dBm as per 3GPP TS 36.133 section 9.1.4 RSRP Measurement Report Mapping
static double RsrqRange2Db (uint8_t range)
converts an RSRQ range to dB as per 3GPP TS 36.133 section 9.1.7 RSRQ Measurement Report Mapping
Detailed Description
Implements the E-UTRA measurement mappings defined in 3GPP TS 36.133 section 9.1 E-UTRAN measurements.
Definition at line 256 of file lte-common.h.
Member Function Documentation
ActualA3Offset2IeValue()
int8_t ns3::EutranMeasurementMapping::ActualA3Offset2IeValue (double a3OffsetDb) static
Returns the IE value of a3-Offset.
Parameters
a3OffsetDb actual A3 Offset value in dB
Returns
IE value of a3-Offset in dB, which is actual value * 2, rounded to the nearest integer
The allowed values for A3 Offset are between -15 and 15 dB.
See also
LteRrcSap::ReportConfigEutra
Definition at line 335 of file lte-common.cc.
References NS_ASSERT, and NS_FATAL_ERROR.
ActualHysteresis2IeValue()
uint8_t ns3::EutranMeasurementMapping::ActualHysteresis2IeValue (double hysteresisDb) static
Returns the IE value of hysteresis.
Parameters
hysteresisDb actual hysteresis value in dB
Returns
IE value of hysteresis in dB, which is actual value * 2, rounded to the nearest integer
The allowed values for hysteresis are between 0 and 15 dB.
See also
LteRrcSap::ReportConfigEutra
Definition at line 304 of file lte-common.cc.
References NS_ASSERT, and NS_FATAL_ERROR.
Referenced by ns3::A3RsrpHandoverAlgorithm::DoInitialize().
Db2RsrqRange()
uint8_t ns3::EutranMeasurementMapping::Db2RsrqRange (double db) static
convert an RSRQ value in dB to the corresponding range as per 3GPP TS 36.133 section 9.1.7 RSRQ Measurement Report Mapping
Parameters
db the RSRQ value in dB
Returns
the corresponding range
Definition at line 268 of file lte-common.cc.
References max, and min.
Referenced by QuantizeRsrq(), and ns3::LteUeRrc::SendMeasurementReport().
Dbm2RsrpRange()
uint8_t ns3::EutranMeasurementMapping::Dbm2RsrpRange (double dbm) static
convert an RSRP value in dBm to the corresponding range as per 3GPP TS 36.133 section 9.1.4 RSRP Measurement Report Mapping
Parameters
dbm the RSRP value in dBm
Returns
the corresponding range
Definition at line 252 of file lte-common.cc.
References max, and min.
Referenced by QuantizeRsrp(), and ns3::LteUeRrc::SendMeasurementReport().
IeValue2ActualA3Offset()
double ns3::EutranMeasurementMapping::IeValue2ActualA3Offset (int8_t a3OffsetIeValue) static
Returns the actual value of an a3-Offset parameter.
Parameters
a3OffsetIeValue IE value of a3-Offset
Returns
actual value in dB, which is IE value * 0.5 dB
As per section 6.3.5 of 3GPP TS 36.331.
The allowed values for a3-Offset IE value are between -30 and 30.
See also
LteRrcSap::ReportConfigEutra
Definition at line 319 of file lte-common.cc.
References NS_ASSERT, and NS_FATAL_ERROR.
Referenced by ns3::LteUeRrc::MeasurementReportTriggering().
IeValue2ActualHysteresis()
double ns3::EutranMeasurementMapping::IeValue2ActualHysteresis (uint8_t hysteresisIeValue) static
Returns the actual value of a hysteresis parameter.
Parameters
hysteresisIeValue IE value of hysteresis
Returns
actual value in dB, which is IE value * 0.5 dB
As per section 6.3.5 of 3GPP TS 36.331.
The allowed values for hysteresis IE value are between 0 and 30.
See also
LteRrcSap::ReportConfigEutra
Definition at line 288 of file lte-common.cc.
References NS_ASSERT, and NS_FATAL_ERROR.
Referenced by ns3::LteUeRrc::MeasurementReportTriggering().
IeValue2ActualQQualMin()
double ns3::EutranMeasurementMapping::IeValue2ActualQQualMin (int8_t qQualMinIeValue) static
Returns the actual value of an Q-QualMin parameter.
Parameters
qQualMinIeValue IE value of Q-QualMin
Returns
Q-QualMin actual value in dB, which is IE value dB
As per section 6.3.4 of 3GPP TS 36.331.
See also
LteRrcSap::CellSelectionInfo
Definition at line 367 of file lte-common.cc.
References NS_ASSERT, and NS_FATAL_ERROR.
IeValue2ActualQRxLevMin()
double ns3::EutranMeasurementMapping::IeValue2ActualQRxLevMin (int8_t qRxLevMinIeValue) static
Returns the actual value of an Q-RxLevMin parameter.
Parameters
qRxLevMinIeValue IE value of Q-RxLevMin
Returns
Q-RxLevMin actual value in dBm, which is IE value * 2 dBm
As per section 6.3.4 of 3GPP TS 36.331.
See also
LteRrcSap::CellSelectionInfo
Definition at line 351 of file lte-common.cc.
References NS_ASSERT, and NS_FATAL_ERROR.
Referenced by ns3::LteUeRrc::EvaluateCellForSelection().
QuantizeRsrp()
double ns3::EutranMeasurementMapping::QuantizeRsrp (double v) static
Quantize an RSRP value according to the measurement mapping of TS 36.133.
Parameters
v RSRP value in dBm
Returns
the quantized RSRP value in dBm
Definition at line 276 of file lte-common.cc.
References Dbm2RsrpRange(), and RsrpRange2Dbm().
QuantizeRsrq()
double ns3::EutranMeasurementMapping::QuantizeRsrq (double v) static
Quantize an RSRQ value according to the measurement mapping of TS 36.133.
Parameters
v RSRQ value in dB
Returns
the quantized RSRQ value in dB
Definition at line 282 of file lte-common.cc.
References Db2RsrqRange(), and RsrqRange2Db().
RsrpRange2Dbm()
double ns3::EutranMeasurementMapping::RsrpRange2Dbm (uint8_t range) static
converts an RSRP range to dBm as per 3GPP TS 36.133 section 9.1.4 RSRP Measurement Report Mapping
Parameters
range the RSRP range value
Returns
the corresponding RSRP value in dBm
Definition at line 244 of file lte-common.cc.
References NS_ASSERT_MSG().
Referenced by ns3::LteUeRrc::MeasurementReportTriggering(), and QuantizeRsrp().
RsrqRange2Db()
double ns3::EutranMeasurementMapping::RsrqRange2Db (uint8_t range) static
converts an RSRQ range to dB as per 3GPP TS 36.133 section 9.1.7 RSRQ Measurement Report Mapping
Parameters
range the RSRQ range value
Returns
the corresponding RSRQ value in dB
Definition at line 260 of file lte-common.cc.
References NS_ASSERT_MSG().
Referenced by ns3::LteUeRrc::MeasurementReportTriggering(), and QuantizeRsrq().
The documentation for this class was generated from the following files:
src/lte/model/lte-common.h
src/lte/model/lte-common.cc