ns-3: ns3::TcpDctcp Class Reference
ns3::TcpDctcp Class Reference
Internet » TCP
An implementation of DCTCP. This model implements all the functionalities mentioned in the DCTCP SIGCOMM paper except dynamic buffer allocation in switches.
#include "tcp-dctcp.h"
Public Member Functions
TcpDctcp ()
Create an unbound tcp socket.
TcpDctcp (const TcpDctcp &sock)
Copy constructor.
virtual ~TcpDctcp (void)
Destructor.
virtual void CwndEvent (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCAEvent_t event)
Trigger events/calculations on occurrence of congestion window event.
virtual Ptr< TcpCongestionOps > Fork ()
Copy the congestion control algorithm across sockets.
virtual std::string GetName () const
Get the name of the TCP flavour.
virtual void Init (Ptr< TcpSocketState > tcb)
Set configuration required by congestion control algorithm, This method will force DctcpEcn mode and will force usage of either ECT(0) or ECT(1) (depending on the 'UseEct0' attribute), despite any other configuration in the base classes.
virtual void PktsAcked (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked, const Time &rtt)
Get information from the acked packet.
virtual void ReduceCwnd (Ptr< TcpSocketState > tcb)
Reduce congestion window based on DCTCP algorithm.
Public Member Functions inherited from ns3::TcpNewReno
TcpNewReno ()
TcpNewReno (const TcpNewReno &sock)
Copy constructor.
~TcpNewReno ()
virtual uint32_t GetSsThresh (Ptr< const TcpSocketState > tcb, uint32_t bytesInFlight)
Get the slow start threshold after a loss event.
virtual void IncreaseWindow (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
Try to increase the cWnd following the NewReno specification.
Public Member Functions inherited from ns3::TcpCongestionOps
TcpCongestionOps ()
TcpCongestionOps (const TcpCongestionOps &other)
Copy constructor.
virtual ~TcpCongestionOps ()
virtual void CongControl (Ptr< TcpSocketState > tcb, const TcpRateOps::TcpRateConnection &rc, const TcpRateOps::TcpRateSample &rs)
Called when packets are delivered to update cwnd and pacing rate.
virtual void CongestionStateSet (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCongState_t newState)
Trigger events/calculations specific to a congestion state.
virtual bool HasCongControl () const
Returns true when Congestion Control Algorithm implements CongControl.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpNewReno
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpCongestionOps
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void CeState0to1 (Ptr< TcpSocketState > tcb)
Changes state of m_ceState to true.
void CeState1to0 (Ptr< TcpSocketState > tcb)
Changes state of m_ceState to false.
void Reset (Ptr< TcpSocketState > tcb)
Resets the value of m_ackedBytesEcn, m_ackedBytesTotal and m_nextSeq.
void SetDctcpAlpha (double alpha)
Sets the value of m_alpha.
void UpdateAckReserved (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCAEvent_t event)
Updates the value of m_delayedAckReserved.
Private Attributes
uint32_t m_ackedBytesEcn
Number of acked bytes which are marked.
uint32_t m_ackedBytesTotal
Total number of acked bytes.
double m_alpha
Parameter used to estimate the amount of network congestion.
bool m_ceState
DCTCP Congestion Experienced state.
bool m_delayedAckReserved
Delayed Ack state.
double m_g
Estimation gain.
SequenceNumber32 m_nextSeq
TCP sequence number threshold for beginning a new observation window.
bool m_nextSeqFlag
Variable used in setting the value of m_nextSeq for first time.
SequenceNumber32 m_priorRcvNxt
Sequence number of the first missing byte in data.
bool m_priorRcvNxtFlag
Variable used in setting the value of m_priorRcvNxt for first time.
bool m_useEct0
Use ECT(0) for ECN codepoint.
Additional Inherited Members
Protected Member Functions inherited from ns3::TcpNewReno
virtual void CongestionAvoidance (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
NewReno congestion avoidance.
virtual uint32_t SlowStart (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked)
Tcp NewReno slow start algorithm.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
An implementation of DCTCP. This model implements all the functionalities mentioned in the DCTCP SIGCOMM paper except dynamic buffer allocation in switches.
Definition at line 36 of file tcp-dctcp.h.
Constructor & Destructor Documentation
TcpDctcp() [1/2]
ns3::TcpDctcp::TcpDctcp ()
Create an unbound tcp socket.
Definition at line 63 of file tcp-dctcp.cc.
References m_ackedBytesEcn, m_ackedBytesTotal, m_ceState, m_delayedAckReserved, m_nextSeq, m_nextSeqFlag, m_priorRcvNxt, m_priorRcvNxtFlag, and NS_LOG_FUNCTION.
TcpDctcp() [2/2]
ns3::TcpDctcp::TcpDctcp (const TcpDctcp & sock)
Copy constructor.
Parameters
sock the object to copy
Definition at line 77 of file tcp-dctcp.cc.
References NS_LOG_FUNCTION.
~TcpDctcp()
ns3::TcpDctcp::~TcpDctcp (void) virtual
Destructor.
Definition at line 94 of file tcp-dctcp.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CeState0to1()
void ns3::TcpDctcp::CeState0to1 (Ptr< TcpSocketState > tcb) private
Changes state of m_ceState to true.
Parameters
tcb internal congestion state
Definition at line 167 of file tcp-dctcp.cc.
References ns3::TcpHeader::ACK, ns3::TcpSocketState::ECN_CE_RCVD, m_ceState, m_delayedAckReserved, ns3::TcpSocketState::m_ecnState, m_priorRcvNxt, m_priorRcvNxtFlag, ns3::TcpSocketState::m_rxBuffer, ns3::TcpSocketState::m_sendEmptyPacketCallback, and NS_LOG_FUNCTION.
Referenced by CwndEvent().
CeState1to0()
void ns3::TcpDctcp::CeState1to0 (Ptr< TcpSocketState > tcb) private
Changes state of m_ceState to false.
Parameters
tcb internal congestion state
Definition at line 194 of file tcp-dctcp.cc.
References ns3::TcpHeader::ACK, ns3::TcpHeader::ECE, ns3::TcpSocketState::ECN_CE_RCVD, ns3::TcpSocketState::ECN_IDLE, ns3::TcpSocketState::ECN_SENDING_ECE, m_ceState, m_delayedAckReserved, ns3::TcpSocketState::m_ecnState, m_priorRcvNxt, m_priorRcvNxtFlag, ns3::TcpSocketState::m_rxBuffer, ns3::TcpSocketState::m_sendEmptyPacketCallback, and NS_LOG_FUNCTION.
Referenced by CwndEvent().
CwndEvent()
void ns3::TcpDctcp::CwndEvent (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCAEvent_t event) virtual
Trigger events/calculations on occurrence of congestion window event.
Parameters
tcb internal state
event congestion window event which triggered this function
Reimplemented from ns3::TcpCongestionOps.
Definition at line 250 of file tcp-dctcp.cc.
References ns3::TcpSocketState::CA_EVENT_DELAYED_ACK, ns3::TcpSocketState::CA_EVENT_ECN_IS_CE, ns3::TcpSocketState::CA_EVENT_ECN_NO_CE, ns3::TcpSocketState::CA_EVENT_NON_DELAYED_ACK, CeState0to1(), CeState1to0(), NS_LOG_FUNCTION, and UpdateAckReserved().
Fork()
Ptr< TcpCongestionOps > ns3::TcpDctcp::Fork () virtual
Copy the congestion control algorithm across sockets.
Returns
a pointer of the copied object
Reimplemented from ns3::TcpNewReno.
Definition at line 99 of file tcp-dctcp.cc.
References NS_LOG_FUNCTION.
GetName()
std::string ns3::TcpDctcp::GetName () const virtual
Get the name of the TCP flavour.
Returns
The name of the TCP
Reimplemented from ns3::TcpNewReno.
Definition at line 58 of file tcp-dctcp.cc.
GetTypeId()
TypeId ns3::TcpDctcp::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 33 of file tcp-dctcp.cc.
References m_g, m_useEct0, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeDoubleAccessor(), SetDctcpAlpha(), and ns3::TypeId::SetParent().
Init()
void ns3::TcpDctcp::Init (Ptr< TcpSocketState > tcb) virtual
Set configuration required by congestion control algorithm, This method will force DctcpEcn mode and will force usage of either ECT(0) or ECT(1) (depending on the 'UseEct0' attribute), despite any other configuration in the base classes.
Parameters
ecnMode ECN Mode
Reimplemented from ns3::TcpCongestionOps.
Definition at line 106 of file tcp-dctcp.cc.
References ns3::TcpSocketState::DctcpEcn, ns3::TcpSocketState::Ect0, ns3::TcpSocketState::Ect1, ns3::TcpSocketState::m_ecnMode, ns3::TcpSocketState::m_ectCodePoint, ns3::TcpSocketState::m_useEcn, m_useEct0, NS_LOG_FUNCTION, NS_LOG_INFO, and ns3::TcpSocketState::On.
PktsAcked()
void ns3::TcpDctcp::PktsAcked (Ptr< TcpSocketState > tcb, uint32_t segmentsAcked, const Time & rtt) virtual
Get information from the acked packet.
Parameters
tcb internal congestion state
segmentsAcked count of segments ACKed
rtt The estimated rtt
Reimplemented from ns3::TcpCongestionOps.
Definition at line 124 of file tcp-dctcp.cc.
References ns3::TcpSocketState::ECN_ECE_RCVD, m_ackedBytesEcn, m_ackedBytesTotal, m_alpha, ns3::TcpSocketState::m_ecnState, m_g, ns3::TcpSocketState::m_lastAckedSeq, m_nextSeq, m_nextSeqFlag, ns3::TcpSocketState::m_nextTxSequence, ns3::TcpSocketState::m_segmentSize, NS_LOG_FUNCTION, NS_LOG_INFO, and Reset().
Referenced by TcpDctcpDecrementTest::ExecuteTest().
ReduceCwnd()
void ns3::TcpDctcp::ReduceCwnd (Ptr< TcpSocketState > tcb) virtual
Reduce congestion window based on DCTCP algorithm.
Parameters
tcb internal congestion state
Reimplemented from ns3::TcpNewReno.
Definition at line 116 of file tcp-dctcp.cc.
References m_alpha, ns3::TcpSocketState::m_cWnd, ns3::TcpSocketState::m_segmentSize, max, and NS_LOG_FUNCTION.
Referenced by TcpDctcpDecrementTest::ExecuteTest().
Reset()
void ns3::TcpDctcp::Reset (Ptr< TcpSocketState > tcb) private
Resets the value of m_ackedBytesEcn, m_ackedBytesTotal and m_nextSeq.
Parameters
tcb internal congestion state
Definition at line 158 of file tcp-dctcp.cc.
References m_ackedBytesEcn, m_ackedBytesTotal, m_nextSeq, ns3::TcpSocketState::m_nextTxSequence, and NS_LOG_FUNCTION.
Referenced by PktsAcked().
SetDctcpAlpha()
void ns3::TcpDctcp::SetDctcpAlpha (double alpha) private
Sets the value of m_alpha.
Parameters
alpha DCTCP alpha parameter
Definition at line 151 of file tcp-dctcp.cc.
References sample-rng-plot::alpha, m_alpha, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
UpdateAckReserved()
void ns3::TcpDctcp::UpdateAckReserved (Ptr< TcpSocketState > tcb, const TcpSocketState::TcpCAEvent_t event) private
Updates the value of m_delayedAckReserved.
Parameters
tcb internal congestion state
event the congestion window event
Definition at line 225 of file tcp-dctcp.cc.
References ns3::TcpSocketState::CA_EVENT_DELAYED_ACK, ns3::TcpSocketState::CA_EVENT_NON_DELAYED_ACK, m_delayedAckReserved, and NS_LOG_FUNCTION.
Referenced by CwndEvent().
Member Data Documentation
m_ackedBytesEcn
uint32_t ns3::TcpDctcp::m_ackedBytesEcn private
Number of acked bytes which are marked.
Definition at line 142 of file tcp-dctcp.h.
Referenced by TcpDctcp(), PktsAcked(), and Reset().
m_ackedBytesTotal
uint32_t ns3::TcpDctcp::m_ackedBytesTotal private
Total number of acked bytes.
Definition at line 143 of file tcp-dctcp.h.
Referenced by TcpDctcp(), PktsAcked(), and Reset().
m_alpha
double ns3::TcpDctcp::m_alpha private
Parameter used to estimate the amount of network congestion.
Definition at line 146 of file tcp-dctcp.h.
Referenced by PktsAcked(), ReduceCwnd(), and SetDctcpAlpha().
m_ceState
bool ns3::TcpDctcp::m_ceState private
DCTCP Congestion Experienced state.
Definition at line 149 of file tcp-dctcp.h.
Referenced by TcpDctcp(), CeState0to1(), and CeState1to0().
m_delayedAckReserved
bool ns3::TcpDctcp::m_delayedAckReserved private
Delayed Ack state.
Definition at line 150 of file tcp-dctcp.h.
Referenced by TcpDctcp(), CeState0to1(), CeState1to0(), and UpdateAckReserved().
m_g
double ns3::TcpDctcp::m_g private
Estimation gain.
Definition at line 151 of file tcp-dctcp.h.
Referenced by GetTypeId(), and PktsAcked().
m_nextSeq
SequenceNumber32 ns3::TcpDctcp::m_nextSeq private
TCP sequence number threshold for beginning a new observation window.
Definition at line 147 of file tcp-dctcp.h.
Referenced by TcpDctcp(), PktsAcked(), and Reset().
m_nextSeqFlag
bool ns3::TcpDctcp::m_nextSeqFlag private
Variable used in setting the value of m_nextSeq for first time.
Definition at line 148 of file tcp-dctcp.h.
Referenced by TcpDctcp(), and PktsAcked().
m_priorRcvNxt
SequenceNumber32 ns3::TcpDctcp::m_priorRcvNxt private
Sequence number of the first missing byte in data.
Definition at line 144 of file tcp-dctcp.h.
Referenced by TcpDctcp(), CeState0to1(), and CeState1to0().
m_priorRcvNxtFlag
bool ns3::TcpDctcp::m_priorRcvNxtFlag private
Variable used in setting the value of m_priorRcvNxt for first time.
Definition at line 145 of file tcp-dctcp.h.
Referenced by TcpDctcp(), CeState0to1(), and CeState1to0().
m_useEct0
bool ns3::TcpDctcp::m_useEct0 private
Use ECT(0) for ECN codepoint.
Definition at line 152 of file tcp-dctcp.h.
Referenced by GetTypeId(), and Init().
The documentation for this class was generated from the following files:
src/internet/model/tcp-dctcp.h
src/internet/model/tcp-dctcp.cc