ns-3: ns3::dsr::DsrGraReply Class Reference
ns3::dsr::DsrGraReply Class Reference
DSR Routing
maintain the gratuitous reply
#include "dsr-gratuitous-reply-table.h"
Classes
struct IsExpired
Check if the entry is expired or not.
Public Member Functions
DsrGraReply ()
virtual ~DsrGraReply ()
bool AddEntry (GraReplyEntry &graTableEntry)
Add a new gratuitous reply entry.
void Clear ()
Remove all entries.
bool FindAndUpdate (Ipv4Address replyTo, Ipv4Address replyFrom, Time gratReplyHoldoff)
Update the route entry if found.
uint32_t GetGraTableSize () const
Get the gratuitous reply table size.
void Purge ()
Remove all expired entries.
void SetGraTableSize (uint32_t g)
Set the gratuitous reply table size.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint32_t GraReplyTableSize
The max # of gratuitous reply entries to hold.
std::vector< GraReplyEntry > m_graReply
Vector of entries.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
maintain the gratuitous reply
Definition at line 72 of file dsr-gratuitous-reply-table.h.
Constructor & Destructor Documentation
DsrGraReply()
ns3::dsr::DsrGraReply::DsrGraReply ()
Definition at line 54 of file dsr-gratuitous-reply-table.cc.
~DsrGraReply()
ns3::dsr::DsrGraReply::~DsrGraReply () virtual
Definition at line 58 of file dsr-gratuitous-reply-table.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
AddEntry()
bool ns3::dsr::DsrGraReply::AddEntry (GraReplyEntry & graTableEntry)
Add a new gratuitous reply entry.
Parameters
graTableEntry The gratuitous reply entry
Returns
true on success
Definition at line 81 of file dsr-gratuitous-reply-table.cc.
References m_graReply.
Referenced by ns3::dsr::DsrRouting::SendGratuitousReply().
Clear()
void ns3::dsr::DsrGraReply::Clear () inline
Remove all entries.
Definition at line 109 of file dsr-gratuitous-reply-table.h.
References m_graReply.
FindAndUpdate()
bool ns3::dsr::DsrGraReply::FindAndUpdate (Ipv4Address replyTo, Ipv4Address replyFrom, Time gratReplyHoldoff)
Update the route entry if found.
Parameters
replyTo Entry directed to
replyFrom Entry heard from
gratReplyHoldoff New gratuitous reply holdoff time
Returns
true on success
Definition at line 64 of file dsr-gratuitous-reply-table.cc.
References m_graReply, max, ns3::Simulator::Now(), NS_LOG_DEBUG, and Purge().
Referenced by ns3::dsr::DsrRouting::SendGratuitousReply().
GetGraTableSize()
uint32_t ns3::dsr::DsrGraReply::GetGraTableSize () const inline
Get the gratuitous reply table size.
Returns
The gratuitous reply table size
Definition at line 92 of file dsr-gratuitous-reply-table.h.
References GraReplyTableSize.
GetTypeId()
TypeId ns3::dsr::DsrGraReply::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 44 of file dsr-gratuitous-reply-table.cc.
References ns3::TypeId::SetParent().
Purge()
void ns3::dsr::DsrGraReply::Purge ()
Remove all expired entries.
Definition at line 88 of file dsr-gratuitous-reply-table.cc.
References m_graReply.
Referenced by FindAndUpdate().
SetGraTableSize()
void ns3::dsr::DsrGraReply::SetGraTableSize (uint32_t g) inline
Set the gratuitous reply table size.
Parameters
g The gratuitous reply table size
Definition at line 86 of file dsr-gratuitous-reply-table.h.
References GraReplyTableSize.
Referenced by ns3::dsr::DsrRouting::Start().
Member Data Documentation
GraReplyTableSize
uint32_t ns3::dsr::DsrGraReply::GraReplyTableSize private
The max # of gratuitous reply entries to hold.
Definition at line 118 of file dsr-gratuitous-reply-table.h.
Referenced by GetGraTableSize(), and SetGraTableSize().
m_graReply
std::vector<GraReplyEntry> ns3::dsr::DsrGraReply::m_graReply private
Vector of entries.
Definition at line 116 of file dsr-gratuitous-reply-table.h.
Referenced by AddEntry(), Clear(), FindAndUpdate(), and Purge().
The documentation for this class was generated from the following files:
src/dsr/model/dsr-gratuitous-reply-table.h
src/dsr/model/dsr-gratuitous-reply-table.cc