ns-3: ns3::Ipv4AddressTlvValue Class Reference
ns3::Ipv4AddressTlvValue Class Reference
WiMAX Models
Ipv4AddressTlvValue class.
#include "wimax-tlv.h"
Classes
struct ipv4Addr
ipv4Addr structure
Public Types
typedef std::vector< struct ipv4Addr >::const_iterator Iterator
IPv4 address vector iterator typedef.
Public Member Functions
Ipv4AddressTlvValue ()
~Ipv4AddressTlvValue ()
void Add (Ipv4Address address, Ipv4Mask Mask)
Add IPv4 address and mask.
Iterator Begin () const
Begin iterator.
virtual Ipv4AddressTlvValue * Copy () const
Copy function.
virtual uint32_t Deserialize (Buffer::Iterator start, uint64_t valueLength)
Deserialize from a buffer.
Iterator End () const
End iterator.
virtual uint32_t GetSerializedSize (void) const
Get serialized size in bytes.
virtual void Serialize (Buffer::Iterator start) const
Serialize to a buffer.
Public Member Functions inherited from ns3::TlvValue
virtual ~TlvValue ()
Private Attributes
std::vector< struct ipv4Addr > * m_ipv4Addr
ipv4 addr
Detailed Description
Ipv4AddressTlvValue class.
Definition at line 556 of file wimax-tlv.h.
Member Typedef Documentation
Iterator
typedef std::vector<struct ipv4Addr>::const_iterator ns3::Ipv4AddressTlvValue::Iterator
IPv4 address vector iterator typedef.
Definition at line 566 of file wimax-tlv.h.
Constructor & Destructor Documentation
Ipv4AddressTlvValue()
ns3::Ipv4AddressTlvValue::Ipv4AddressTlvValue ()
Definition at line 1022 of file wimax-tlv.cc.
References m_ipv4Addr.
Referenced by Copy().
~Ipv4AddressTlvValue()
ns3::Ipv4AddressTlvValue::~Ipv4AddressTlvValue ()
Definition at line 1027 of file wimax-tlv.cc.
References m_ipv4Addr.
Member Function Documentation
Add()
void ns3::Ipv4AddressTlvValue::Add (Ipv4Address address, Ipv4Mask Mask)
Add IPv4 address and mask.
Parameters
address the IPv4 address
Mask the IPv4 mask
Definition at line 1068 of file wimax-tlv.cc.
References first::address, ns3::Ipv4AddressTlvValue::ipv4Addr::Address, m_ipv4Addr, and ns3::Ipv4AddressTlvValue::ipv4Addr::Mask.
Referenced by Copy(), Deserialize(), and ns3::IpcsClassifierRecord::ToTlv().
Begin()
Ipv4AddressTlvValue::Iterator ns3::Ipv4AddressTlvValue::Begin () const
Begin iterator.
Returns
the beginning element
Definition at line 1077 of file wimax-tlv.cc.
References m_ipv4Addr.
Copy()
Ipv4AddressTlvValue * ns3::Ipv4AddressTlvValue::Copy () const virtual
Copy function.
Returns
the TLV value
Implements ns3::TlvValue.
Definition at line 1089 of file wimax-tlv.cc.
References Ipv4AddressTlvValue(), Add(), and m_ipv4Addr.
Deserialize()
uint32_t ns3::Ipv4AddressTlvValue::Deserialize (Buffer::Iterator start, uint64_t valueLen) virtual
Deserialize from a buffer.
Parameters
start the iterator
valueLen the maximum length of the value
Returns
the
Implements ns3::TlvValue.
Definition at line 1054 of file wimax-tlv.cc.
References Add(), and ns3::Buffer::Iterator::ReadNtohU32().
Referenced by ns3::ClassificationRuleVectorTlvValue::Deserialize().
End()
Ipv4AddressTlvValue::Iterator ns3::Ipv4AddressTlvValue::End () const
End iterator.
Returns
the ending element
Definition at line 1083 of file wimax-tlv.cc.
References m_ipv4Addr.
GetSerializedSize()
uint32_t ns3::Ipv4AddressTlvValue::GetSerializedSize (void) const virtual
Get serialized size in bytes.
Returns
the serialized size
Implements ns3::TlvValue.
Definition at line 1038 of file wimax-tlv.cc.
References m_ipv4Addr.
Referenced by ns3::ClassificationRuleVectorTlvValue::Deserialize(), and ns3::IpcsClassifierRecord::ToTlv().
Serialize()
void ns3::Ipv4AddressTlvValue::Serialize (Buffer::Iterator start) const virtual
Serialize to a buffer.
Parameters
start the iterator
Implements ns3::TlvValue.
Definition at line 1044 of file wimax-tlv.cc.
References m_ipv4Addr, and ns3::Buffer::Iterator::WriteHtonU32().
Member Data Documentation
m_ipv4Addr
std::vector<struct ipv4Addr>* ns3::Ipv4AddressTlvValue::m_ipv4Addr private
ipv4 addr
Definition at line 590 of file wimax-tlv.h.
Referenced by Ipv4AddressTlvValue(), ~Ipv4AddressTlvValue(), Add(), Begin(), Copy(), End(), GetSerializedSize(), and Serialize().
The documentation for this class was generated from the following files:
src/wimax/model/wimax-tlv.h
src/wimax/model/wimax-tlv.cc