ns-3: AredQueueDiscTestCase Class Reference
AredQueueDiscTestCase Class Reference
Traffic-control » traffic-control module tests | Test suites
Ared Queue Disc Test Case.
Public Member Functions
AredQueueDiscTestCase ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void Enqueue (Ptr< RedQueueDisc > queue, uint32_t size, uint32_t nPkt)
Enqueue function.
void EnqueueWithDelay (Ptr< RedQueueDisc > queue, uint32_t size, uint32_t nPkt)
Enqueue with delay function.
void RunAredDiscTest (QueueSizeUnit mode)
Run ARED queue disc test function.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Ared Queue Disc Test Case.
Definition at line 99 of file adaptive-red-queue-disc-test-suite.cc.
Constructor & Destructor Documentation
AredQueueDiscTestCase()
AredQueueDiscTestCase::AredQueueDiscTestCase ()
Definition at line 126 of file adaptive-red-queue-disc-test-suite.cc.
Member Function Documentation
DoRun()
void AredQueueDiscTestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 354 of file adaptive-red-queue-disc-test-suite.cc.
References ns3::BYTES, ns3::PACKETS, and RunAredDiscTest().
Enqueue()
void AredQueueDiscTestCase::Enqueue (Ptr< RedQueueDisc > queue, uint32_t size, uint32_t nPkt) private
Enqueue function.
Parameters
queue the queue disc
size the size
nPkt the number of packets
Definition at line 333 of file adaptive-red-queue-disc-test-suite.cc.
References ns3::QueueDisc::Enqueue().
Referenced by EnqueueWithDelay(), and RunAredDiscTest().
EnqueueWithDelay()
void AredQueueDiscTestCase::EnqueueWithDelay (Ptr< RedQueueDisc > queue, uint32_t size, uint32_t nPkt) private
Enqueue with delay function.
Parameters
queue the queue disc
size the size
nPkt the number of packets
Definition at line 343 of file adaptive-red-queue-disc-test-suite.cc.
References Enqueue(), and ns3::Seconds().
Referenced by RunAredDiscTest().
RunAredDiscTest()
void AredQueueDiscTestCase::RunAredDiscTest (QueueSizeUnit mode) private
Run ARED queue disc test function.
Parameters
mode the test mode
Definition at line 132 of file adaptive-red-queue-disc-test-suite.cc.
References ns3::BYTES, Enqueue(), EnqueueWithDelay(), ns3::QueueDisc::Stats::GetNDroppedPackets(), ns3::QueueDisc::GetStats(), ns3::Object::Initialize(), NS_TEST_EXPECT_MSG_EQ, NS_TEST_EXPECT_MSG_LT, NS_TEST_EXPECT_MSG_NE, ns3::Seconds(), and ns3::ObjectBase::SetAttributeFailSafe().
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/traffic-control/test/adaptive-red-queue-disc-test-suite.cc