ns-3: LteEnhancedFfrAreaTestCase Class Reference
LteEnhancedFfrAreaTestCase Class Reference
LTE Models » lte module tests | Test suites
Lte Enhanced Ffr Area Test Case.
#include "lte-test-frequency-reuse.h"
Public Member Functions
LteEnhancedFfrAreaTestCase (std::string name, std::string schedulerType)
Constructor.
virtual ~LteEnhancedFfrAreaTestCase ()
Public Member Functions inherited from LteFrAreaTestCase
LteFrAreaTestCase (std::string name, std::string schedulerType)
Constructor.
virtual ~LteFrAreaTestCase ()
void DlDataRxStart (Ptr< const SpectrumValue > spectrumValue)
DL data receive start function.
void SetDlExpectedValues (double expectedPower, std::vector< bool > expectedDlRb)
Set DL expected values function.
void SetUlExpectedValues (double expectedPower, std::vector< bool > expectedDlRb)
Set UL expected values function.
void SimpleTeleportUe (uint32_t x, uint32_t y)
Simple teleport UE function.
void TeleportUe (uint32_t x, uint32_t y, double expectedPower, std::vector< bool > expectedDlRb)
Teleport UE function.
void TeleportUe2 (Ptr< Node > ueNode, uint32_t x, uint32_t y, double expectedPower, std::vector< bool > expectedDlRb)
Teleport UE 2 function.
void UlDataRxStart (Ptr< const SpectrumValue > spectrumValue)
UL data receive start function.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Protected Attributes inherited from LteFrAreaTestCase
uint16_t m_dlBandwidth
the DL bandwidth
double m_expectedDlPower
the expected DL power
std::vector< bool > m_expectedDlRb
the expected DL per RB
double m_expectedUlPower
expected UL power
std::vector< bool > m_expectedUlRb
expected UL per RB
std::string m_schedulerType
the scheduler type
Time m_teleportTime
the telport time
Ptr< MobilityModel > m_ueMobility
the UE mobility model
uint16_t m_ulBandwidth
the UL bandwidth
bool m_usedWrongDlPower
used wrong DL power?
bool m_usedWrongDlRbg
used wrong DL RBG?
bool m_usedWrongUlPower
used wrong UL power?
bool m_usedWrongUlRbg
used wrong UL RBG?
Detailed Description
Lte Enhanced Ffr Area Test Case.
Definition at line 358 of file lte-test-frequency-reuse.h.
Constructor & Destructor Documentation
LteEnhancedFfrAreaTestCase()
LteEnhancedFfrAreaTestCase::LteEnhancedFfrAreaTestCase (std::string name, std::string schedulerType)
Constructor.
Parameters
name the reference name
schedulerType the scheduler type
Definition at line 1241 of file lte-test-frequency-reuse.cc.
References NS_LOG_INFO.
~LteEnhancedFfrAreaTestCase()
LteEnhancedFfrAreaTestCase::~LteEnhancedFfrAreaTestCase () virtual
Definition at line 1247 of file lte-test-frequency-reuse.cc.
Member Function Documentation
DoRun()
void LteEnhancedFfrAreaTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Reimplemented from LteFrAreaTestCase.
Definition at line 1252 of file lte-test-frequency-reuse.cc.
References ns3::LteHelper::ActivateDataRadioBearer(), ns3::NetDeviceContainer::Add(), ns3::ListPositionAllocator::Add(), ns3::LteHelper::Attach(), ns3::NodeContainer::Create(), DlDataRxStartNofiticationArea(), ns3::GbrQosInformation::gbrDl, ns3::GbrQosInformation::gbrUl, ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::LteSpectrumPhy::GetChannel(), ns3::LteEnbNetDevice::GetDlEarfcn(), ns3::Object::GetObject(), ns3::LteEnbNetDevice::GetUlEarfcn(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), LteFrAreaTestCase::m_dlBandwidth, LteFrAreaTestCase::m_schedulerType, LteFrAreaTestCase::m_ueMobility, LteFrAreaTestCase::m_ulBandwidth, LteFrAreaTestCase::m_usedWrongDlRbg, LteFrAreaTestCase::m_usedWrongUlRbg, ns3::MakeBoundCallback(), ns3::GbrQosInformation::mbrDl, ns3::GbrQosInformation::mbrUl, ns3::MilliSeconds(), third::mobility, NS_LOG_DEBUG, NS_TEST_ASSERT_MSG_EQ, ns3::Config::Reset(), ns3::Seconds(), ns3::LteSimpleSpectrumPhy::SetCellId(), ns3::Config::SetDefault(), ns3::LteHelper::SetEnbDeviceAttribute(), ns3::LteHelper::SetFfrAlgorithmAttribute(), ns3::LteHelper::SetFfrAlgorithmType(), ns3::LteSimpleSpectrumPhy::SetRxSpectrumModel(), ns3::LteHelper::SetSchedulerAttribute(), ns3::LteHelper::SetSchedulerType(), LteFrAreaTestCase::SetUlExpectedValues(), LteFrAreaTestCase::TeleportUe(), ns3::ObjectBase::TraceConnectWithoutContext(), and UlDataRxStartNofiticationArea().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-frequency-reuse.h
src/lte/test/lte-test-frequency-reuse.cc