ns-3: ns3::VhtOperation Class Reference
ns3::VhtOperation Class Reference
Wifi Models
The VHT Operation Information Element.
#include "vht-operation.h"
Public Member Functions
VhtOperation ()
uint8_t DeserializeInformationField (Buffer::Iterator start, uint8_t length)
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
WifiInformationElementId ElementId () const
uint16_t GetBasicVhtMcsAndNssSet (void) const
Return the Basic VHT-MCS And Nss field in the VHT Operation information element.
uint8_t GetChannelCenterFrequencySegment0 (void) const
Return the Channel Center Frequency Segment 0 field in the VHT Operation information element.
uint8_t GetChannelCenterFrequencySegment1 (void) const
Return the Channel Center Frequency Segment 1 field in the VHT Operation information element.
uint8_t GetChannelWidth (void) const
Return the Channel Width field in the VHT Operation information element.
uint8_t GetInformationFieldSize () const
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
uint16_t GetSerializedSize () const
Buffer::Iterator Serialize (Buffer::Iterator start) const
void SerializeInformationField (Buffer::Iterator start) const
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
void SetBasicVhtMcsAndNssSet (uint16_t basicVhtMcsAndNssSet)
Set the Basic VHT-MCS and NSS field in the VHT Operation information element.
void SetChannelCenterFrequencySegment0 (uint8_t channelCenterFrequencySegment0)
Set the Channel Center Frequency Segment 0 field in the VHT Operation information element.
void SetChannelCenterFrequencySegment1 (uint8_t channelCenterFrequencySegment1)
Set the Channel Center Frequency Segment 1 field in the VHT Operation information element.
void SetChannelWidth (uint8_t channelWidth)
Set the Channel Width field in the VHT Operation information element.
void SetMaxVhtMcsPerNss (uint8_t nss, uint8_t maxVhtMcs)
Set the Basic VHT-MCS and NSS field in the VHT Operation information element by specifying the tuple (nss, maxMcs).
void SetVhtSupported (uint8_t vhtSupported)
Set the VHT supported information element.
Public Member Functions inherited from ns3::WifiInformationElement
virtual ~WifiInformationElement ()
Buffer::Iterator Deserialize (Buffer::Iterator i)
Deserialize entire IE, which must be present.
Buffer::Iterator DeserializeIfPresent (Buffer::Iterator i)
Deserialize entire IE if it is present.
virtual WifiInformationElementId ElementIdExt () const
uint16_t GetSerializedSize () const
Get the size of the serialized IE including Element ID and length fields.
virtual bool operator== (WifiInformationElement const &a) const
Compare two IEs for equality by ID & Length, and then through memcmp of serialised version.
virtual void Print (std::ostream &os) const
Generate human-readable form of IE.
Buffer::Iterator Serialize (Buffer::Iterator i) const
Serialize entire IE including Element ID and length fields.
Public Member Functions inherited from ns3::SimpleRefCount< WifiInformationElement >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
uint16_t m_basicVhtMcsAndNssSet
basic VHT MCS NSS set
uint8_t m_channelCenterFrequencySegment0
channel center frequency segment 0
uint8_t m_channelCenterFrequencySegment1
channel center frequency segment 1
uint8_t m_channelWidth
channel width
uint8_t m_vhtSupported
This is used to decide whether this element should be added to the frame or not.
Detailed Description
The VHT Operation Information Element.
This class knows how to serialise and deserialise the VHT Operation Information Element
Definition at line 35 of file vht-operation.h.
Constructor & Destructor Documentation
VhtOperation()
ns3::VhtOperation::VhtOperation ()
Definition at line 25 of file vht-operation.cc.
Member Function Documentation
DeserializeInformationField()
uint8_t ns3::VhtOperation::DeserializeInformationField (Buffer::Iterator start, uint8_t length) virtual
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
length
Returns
the number of bytes read
Implements ns3::WifiInformationElement.
Definition at line 150 of file vht-operation.cc.
References ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU8(), SetBasicVhtMcsAndNssSet(), SetChannelCenterFrequencySegment0(), SetChannelCenterFrequencySegment1(), SetChannelWidth(), and visualizer.core::start().
ElementId()
WifiInformationElementId ns3::VhtOperation::ElementId () const virtual
Returns
Own unique Element ID
Implements ns3::WifiInformationElement.
Definition at line 35 of file vht-operation.cc.
References IE_VHT_OPERATION.
GetBasicVhtMcsAndNssSet()
uint16_t ns3::VhtOperation::GetBasicVhtMcsAndNssSet (void) const
Return the Basic VHT-MCS And Nss field in the VHT Operation information element.
Returns
the Basic VHT-MCS And Nss field in the VHT Operation information element
Definition at line 111 of file vht-operation.cc.
References m_basicVhtMcsAndNssSet.
Referenced by ns3::operator<<(), and SerializeInformationField().
GetChannelCenterFrequencySegment0()
uint8_t ns3::VhtOperation::GetChannelCenterFrequencySegment0 (void) const
Return the Channel Center Frequency Segment 0 field in the VHT Operation information element.
Returns
the Channel Center Frequency Segment 0 field in the VHT Operation information element
Definition at line 99 of file vht-operation.cc.
References m_channelCenterFrequencySegment0.
Referenced by ns3::operator<<(), and SerializeInformationField().
GetChannelCenterFrequencySegment1()
uint8_t ns3::VhtOperation::GetChannelCenterFrequencySegment1 (void) const
Return the Channel Center Frequency Segment 1 field in the VHT Operation information element.
Returns
the Channel Center Frequency Segment 1 field in the VHT Operation information element
Definition at line 105 of file vht-operation.cc.
References m_channelCenterFrequencySegment1.
Referenced by ns3::operator<<(), and SerializeInformationField().
GetChannelWidth()
uint8_t ns3::VhtOperation::GetChannelWidth (void) const
Return the Channel Width field in the VHT Operation information element.
Returns
the Channel Width field in the VHT Operation information element
Definition at line 93 of file vht-operation.cc.
References m_channelWidth.
Referenced by ns3::operator<<(), and SerializeInformationField().
GetInformationFieldSize()
uint8_t ns3::VhtOperation::GetInformationFieldSize () const virtual
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
This is the value that will appear in the second octet of the entire IE - the length field)
Returns
the length of serialized information
Implements ns3::WifiInformationElement.
Definition at line 47 of file vht-operation.cc.
References m_vhtSupported, and NS_ASSERT.
GetSerializedSize()
uint16_t ns3::VhtOperation::GetSerializedSize () const
Definition at line 127 of file vht-operation.cc.
References ns3::WifiInformationElement::GetSerializedSize(), and m_vhtSupported.
Referenced by ns3::MgtAssocResponseHeader::GetSerializedSize(), and ns3::MgtProbeResponseHeader::GetSerializedSize().
Serialize()
Buffer::Iterator ns3::VhtOperation::Serialize (Buffer::Iterator start) const
Definition at line 117 of file vht-operation.cc.
References m_vhtSupported, and ns3::WifiInformationElement::Serialize().
Referenced by ns3::MgtAssocResponseHeader::Serialize(), and ns3::MgtProbeResponseHeader::Serialize().
SerializeInformationField()
void ns3::VhtOperation::SerializeInformationField (Buffer::Iterator start) const virtual
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
Implements ns3::WifiInformationElement.
Definition at line 137 of file vht-operation.cc.
References GetBasicVhtMcsAndNssSet(), GetChannelCenterFrequencySegment0(), GetChannelCenterFrequencySegment1(), GetChannelWidth(), m_vhtSupported, and visualizer.core::start().
SetBasicVhtMcsAndNssSet()
void ns3::VhtOperation::SetBasicVhtMcsAndNssSet (uint16_t basicVhtMcsAndNssSet)
Set the Basic VHT-MCS and NSS field in the VHT Operation information element.
Parameters
basicVhtMcsAndNssSet the Basic VHT-MCS and NSS field in the VHT Operation information element
Definition at line 87 of file vht-operation.cc.
References m_basicVhtMcsAndNssSet.
Referenced by DeserializeInformationField().
SetChannelCenterFrequencySegment0()
void ns3::VhtOperation::SetChannelCenterFrequencySegment0 (uint8_t channelCenterFrequencySegment0)
Set the Channel Center Frequency Segment 0 field in the VHT Operation information element.
Parameters
channelCenterFrequencySegment0 the Channel Center Frequency Segment 0 field in the VHT Operation information element
Definition at line 61 of file vht-operation.cc.
References m_channelCenterFrequencySegment0.
Referenced by DeserializeInformationField().
SetChannelCenterFrequencySegment1()
void ns3::VhtOperation::SetChannelCenterFrequencySegment1 (uint8_t channelCenterFrequencySegment1)
Set the Channel Center Frequency Segment 1 field in the VHT Operation information element.
Parameters
channelCenterFrequencySegment1 the Channel Center Frequency Segment 1 field in the VHT Operation information element
Definition at line 67 of file vht-operation.cc.
References m_channelCenterFrequencySegment1.
Referenced by DeserializeInformationField().
SetChannelWidth()
void ns3::VhtOperation::SetChannelWidth (uint8_t channelWidth)
Set the Channel Width field in the VHT Operation information element.
Parameters
channelWidth the Channel Width field in the VHT Operation information element
Definition at line 55 of file vht-operation.cc.
References m_channelWidth.
Referenced by DeserializeInformationField(), and ns3::ApWifiMac::GetVhtOperation().
SetMaxVhtMcsPerNss()
void ns3::VhtOperation::SetMaxVhtMcsPerNss (uint8_t nss, uint8_t maxVhtMcs)
Set the Basic VHT-MCS and NSS field in the VHT Operation information element by specifying the tuple (nss, maxMcs).
Parameters
nss the NSS
maxVhtMcs the maximum supported VHT-MCS value corresponding to that NSS
Definition at line 73 of file vht-operation.cc.
References m_basicVhtMcsAndNssSet, and NS_ASSERT.
Referenced by ns3::ApWifiMac::GetVhtOperation().
SetVhtSupported()
void ns3::VhtOperation::SetVhtSupported (uint8_t vhtSupported)
Set the VHT supported information element.
Parameters
vhtSupported the VHT supported information element
Definition at line 41 of file vht-operation.cc.
References m_vhtSupported.
Referenced by ns3::ApWifiMac::GetVhtOperation().
Member Data Documentation
m_basicVhtMcsAndNssSet
uint16_t ns3::VhtOperation::m_basicVhtMcsAndNssSet private
basic VHT MCS NSS set
Definition at line 125 of file vht-operation.h.
Referenced by GetBasicVhtMcsAndNssSet(), SetBasicVhtMcsAndNssSet(), and SetMaxVhtMcsPerNss().
m_channelCenterFrequencySegment0
uint8_t ns3::VhtOperation::m_channelCenterFrequencySegment0 private
channel center frequency segment 0
Definition at line 121 of file vht-operation.h.
Referenced by GetChannelCenterFrequencySegment0(), and SetChannelCenterFrequencySegment0().
m_channelCenterFrequencySegment1
uint8_t ns3::VhtOperation::m_channelCenterFrequencySegment1 private
channel center frequency segment 1
Definition at line 122 of file vht-operation.h.
Referenced by GetChannelCenterFrequencySegment1(), and SetChannelCenterFrequencySegment1().
m_channelWidth
uint8_t ns3::VhtOperation::m_channelWidth private
channel width
Definition at line 120 of file vht-operation.h.
Referenced by GetChannelWidth(), and SetChannelWidth().
m_vhtSupported
uint8_t ns3::VhtOperation::m_vhtSupported private
This is used to decide whether this element should be added to the frame or not.
Definition at line 128 of file vht-operation.h.
Referenced by GetInformationFieldSize(), GetSerializedSize(), Serialize(), SerializeInformationField(), and SetVhtSupported().
The documentation for this class was generated from the following files:
src/wifi/model/vht-operation.h
src/wifi/model/vht-operation.cc