ns-3: ns3::MgtProbeResponseHeader Class Reference
ns3::MgtProbeResponseHeader Class Reference
Wifi Models
#include "mgt-headers.h"
Public Member Functions
MgtProbeResponseHeader ()
~MgtProbeResponseHeader ()
uint32_t Deserialize (Buffer::Iterator start)
uint64_t GetBeaconIntervalUs (void) const
Return the beacon interval in microseconds unit.
CapabilityInformation GetCapabilities (void) const
Return the Capability information.
CfParameterSet GetCfParameterSet (void) const
Return the CF parameter set.
DsssParameterSet GetDsssParameterSet (void) const
Return the DSSS Parameter Set.
EdcaParameterSet GetEdcaParameterSet (void) const
Return the EDCA Parameter Set.
ErpInformation GetErpInformation (void) const
Return the ERP information.
ExtendedCapabilities GetExtendedCapabilities (void) const
Return the extended capabilities.
HeCapabilities GetHeCapabilities (void) const
Return the HE capabilities.
HeOperation GetHeOperation (void) const
Return the HE operation.
HtCapabilities GetHtCapabilities (void) const
Return the HT capabilities.
HtOperation GetHtOperation (void) const
Return the HT operation.
TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint32_t GetSerializedSize (void) const
Ssid GetSsid (void) const
Return the Service Set Identifier (SSID).
SupportedRates GetSupportedRates (void) const
Return the supported rates.
uint64_t GetTimestamp ()
Return the time stamp.
VhtCapabilities GetVhtCapabilities (void) const
Return the VHT capabilities.
VhtOperation GetVhtOperation (void) const
Return the VHT operation.
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetBeaconIntervalUs (uint64_t us)
Set the beacon interval in microseconds unit.
void SetCapabilities (CapabilityInformation capabilities)
Set the Capability information.
void SetCfParameterSet (CfParameterSet cfParameterSet)
Set the CF parameter set.
void SetDsssParameterSet (DsssParameterSet dsssParameterSet)
Set the DSSS Parameter Set.
void SetEdcaParameterSet (EdcaParameterSet edcaParameterSet)
Set the EDCA Parameter Set.
void SetErpInformation (ErpInformation erpInformation)
Set the ERP information.
void SetExtendedCapabilities (ExtendedCapabilities extendedCapabilities)
Set the extended capabilities.
void SetHeCapabilities (HeCapabilities heCapabilities)
Set the HE capabilities.
void SetHeOperation (HeOperation heOperation)
Set the HE operation.
void SetHtCapabilities (HtCapabilities htCapabilities)
Set the HT capabilities.
void SetHtOperation (HtOperation htOperation)
Set the HT operation.
void SetSsid (Ssid ssid)
Set the Service Set Identifier (SSID).
void SetSupportedRates (SupportedRates rates)
Set the supported rates.
void SetVhtCapabilities (VhtCapabilities vhtCapabilities)
Set the VHT capabilities.
void SetVhtOperation (VhtOperation vhtOperation)
Set the VHT operation.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint64_t m_beaconInterval
Beacon interval.
CapabilityInformation m_capability
Capability information.
CfParameterSet m_cfParameterSet
CF parameter set.
DsssParameterSet m_dsssParameterSet
DSSS Parameter Set.
EdcaParameterSet m_edcaParameterSet
EDCA Parameter Set.
ErpInformation m_erpInformation
ERP information.
ExtendedCapabilities m_extendedCapability
extended capabilities
HeCapabilities m_heCapability
HE capabilities.
HeOperation m_heOperation
HE operation.
HtCapabilities m_htCapability
HT capabilities.
HtOperation m_htOperation
HT operation.
SupportedRates m_rates
List of supported rates.
Ssid m_ssid
Service set ID (SSID)
uint64_t m_timestamp
Timestamp.
VhtCapabilities m_vhtCapability
VHT capabilities.
VhtOperation m_vhtOperation
VHT operation.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implement the header for management frames of type probe response.
Definition at line 618 of file mgt-headers.h.
Constructor & Destructor Documentation
MgtProbeResponseHeader()
ns3::MgtProbeResponseHeader::MgtProbeResponseHeader ()
Definition at line 187 of file mgt-headers.cc.
~MgtProbeResponseHeader()
ns3::MgtProbeResponseHeader::~MgtProbeResponseHeader ()
Definition at line 191 of file mgt-headers.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::MgtProbeResponseHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 470 of file mgt-headers.cc.
References ns3::WifiInformationElement::Deserialize(), ns3::CapabilityInformation::Deserialize(), ns3::WifiInformationElement::DeserializeIfPresent(), ns3::SupportedRates::extended, ns3::Buffer::Iterator::GetDistanceFrom(), m_beaconInterval, m_capability, m_cfParameterSet, m_dsssParameterSet, m_edcaParameterSet, m_erpInformation, m_extendedCapability, m_heCapability, m_heOperation, m_htCapability, m_htOperation, m_rates, m_ssid, m_timestamp, m_vhtCapability, m_vhtOperation, ns3::Buffer::Iterator::ReadLsbtohU16(), ns3::Buffer::Iterator::ReadLsbtohU64(), and visualizer.core::start().
GetBeaconIntervalUs()
uint64_t ns3::MgtProbeResponseHeader::GetBeaconIntervalUs (void) const
Return the beacon interval in microseconds unit.
Returns
beacon interval in microseconds unit
Definition at line 208 of file mgt-headers.cc.
References m_beaconInterval.
Referenced by ns3::MeshWifiBeacon::GetBeaconInterval(), ns3::dot11s::PeerManagementProtocolMac::Receive(), ns3::StaWifiMac::Receive(), and ns3::StaWifiMac::ScanningTimeout().
GetCapabilities()
CapabilityInformation ns3::MgtProbeResponseHeader::GetCapabilities (void) const
Return the Capability information.
Returns
Capability information
Definition at line 226 of file mgt-headers.cc.
References m_capability.
Referenced by ns3::StaWifiMac::Receive(), ns3::StaWifiMac::UpdateApInfoFromBeacon(), and ns3::StaWifiMac::UpdateApInfoFromProbeResp().
GetCfParameterSet()
CfParameterSet ns3::MgtProbeResponseHeader::GetCfParameterSet (void) const
Return the CF parameter set.
Returns
CF parameter set
Definition at line 322 of file mgt-headers.cc.
References m_cfParameterSet.
Referenced by ns3::StaWifiMac::Receive().
GetDsssParameterSet()
DsssParameterSet ns3::MgtProbeResponseHeader::GetDsssParameterSet (void) const
Return the DSSS Parameter Set.
Returns
the DSSS Parameter Set
Definition at line 352 of file mgt-headers.cc.
References m_dsssParameterSet.
GetEdcaParameterSet()
EdcaParameterSet ns3::MgtProbeResponseHeader::GetEdcaParameterSet (void) const
Return the EDCA Parameter Set.
Returns
the EDCA Parameter Set
Definition at line 376 of file mgt-headers.cc.
References m_edcaParameterSet.
Referenced by ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetErpInformation()
ErpInformation ns3::MgtProbeResponseHeader::GetErpInformation (void) const
Return the ERP information.
Returns
the ERP information
Definition at line 364 of file mgt-headers.cc.
References m_erpInformation.
Referenced by ns3::StaWifiMac::UpdateApInfoFromBeacon(), and ns3::StaWifiMac::UpdateApInfoFromProbeResp().
GetExtendedCapabilities()
ExtendedCapabilities ns3::MgtProbeResponseHeader::GetExtendedCapabilities (void) const
Return the extended capabilities.
Returns
the extended capabilities
Definition at line 238 of file mgt-headers.cc.
References m_extendedCapability.
Referenced by ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetHeCapabilities()
HeCapabilities ns3::MgtProbeResponseHeader::GetHeCapabilities (void) const
Return the HE capabilities.
Returns
HE capabilities
Definition at line 298 of file mgt-headers.cc.
References m_heCapability.
Referenced by ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetHeOperation()
HeOperation ns3::MgtProbeResponseHeader::GetHeOperation (void) const
Return the HE operation.
Returns
HE operation
Definition at line 310 of file mgt-headers.cc.
References m_heOperation.
Referenced by ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetHtCapabilities()
HtCapabilities ns3::MgtProbeResponseHeader::GetHtCapabilities (void) const
Return the HT capabilities.
Returns
HT capabilities
Definition at line 250 of file mgt-headers.cc.
References m_htCapability.
Referenced by ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetHtOperation()
HtOperation ns3::MgtProbeResponseHeader::GetHtOperation (void) const
Return the HT operation.
Returns
HT operation
Definition at line 262 of file mgt-headers.cc.
References m_htOperation.
Referenced by Bug2831TestCase::RxCallback(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetInstanceTypeId()
TypeId ns3::MgtProbeResponseHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 393 of file mgt-headers.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::MgtProbeResponseHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 399 of file mgt-headers.cc.
References ns3::SupportedRates::extended, ns3::CfParameterSet::GetSerializedSize(), ns3::DsssParameterSet::GetSerializedSize(), ns3::EdcaParameterSet::GetSerializedSize(), ns3::ErpInformation::GetSerializedSize(), ns3::ExtendedCapabilities::GetSerializedSize(), ns3::HeCapabilities::GetSerializedSize(), ns3::HeOperation::GetSerializedSize(), ns3::HtCapabilities::GetSerializedSize(), ns3::HtOperation::GetSerializedSize(), ns3::ExtendedSupportedRatesIE::GetSerializedSize(), ns3::VhtCapabilities::GetSerializedSize(), ns3::VhtOperation::GetSerializedSize(), ns3::WifiInformationElement::GetSerializedSize(), ns3::CapabilityInformation::GetSerializedSize(), m_capability, m_cfParameterSet, m_dsssParameterSet, m_edcaParameterSet, m_erpInformation, m_extendedCapability, m_heCapability, m_heOperation, m_htCapability, m_htOperation, m_rates, m_ssid, m_vhtCapability, and m_vhtOperation.
GetSsid()
Ssid ns3::MgtProbeResponseHeader::GetSsid (void) const
Return the Service Set Identifier (SSID).
Returns
SSID
Definition at line 202 of file mgt-headers.cc.
References m_ssid.
Referenced by ns3::MeshWifiInterfaceMac::Receive(), and ns3::StaWifiMac::Receive().
GetSupportedRates()
SupportedRates ns3::MgtProbeResponseHeader::GetSupportedRates (void) const
Return the supported rates.
Returns
the supported rates
Definition at line 214 of file mgt-headers.cc.
References m_rates.
Referenced by ns3::MeshWifiInterfaceMac::Receive(), ns3::StaWifiMac::Receive(), ns3::StaWifiMac::UpdateApInfoFromBeacon(), and ns3::StaWifiMac::UpdateApInfoFromProbeResp().
GetTimestamp()
uint64_t ns3::MgtProbeResponseHeader::GetTimestamp ()
Return the time stamp.
Returns
time stamp
Definition at line 196 of file mgt-headers.cc.
References m_timestamp.
GetTypeId()
TypeId ns3::MgtProbeResponseHeader::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 382 of file mgt-headers.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
GetVhtCapabilities()
VhtCapabilities ns3::MgtProbeResponseHeader::GetVhtCapabilities (void) const
Return the VHT capabilities.
Returns
VHT capabilities
Definition at line 274 of file mgt-headers.cc.
References m_vhtCapability.
Referenced by ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetVhtOperation()
VhtOperation ns3::MgtProbeResponseHeader::GetVhtOperation (void) const
Return the VHT operation.
Returns
VHT operation
Definition at line 286 of file mgt-headers.cc.
References m_vhtOperation.
Referenced by ns3::StaWifiMac::UpdateApInfoFromBeacon().
Print()
void ns3::MgtProbeResponseHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 423 of file mgt-headers.cc.
References m_erpInformation, m_extendedCapability, m_heCapability, m_heOperation, m_htCapability, m_htOperation, m_rates, m_ssid, m_vhtCapability, and m_vhtOperation.
Serialize()
void ns3::MgtProbeResponseHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 438 of file mgt-headers.cc.
References ns3::SupportedRates::extended, m_beaconInterval, m_capability, m_cfParameterSet, m_dsssParameterSet, m_edcaParameterSet, m_erpInformation, m_extendedCapability, m_heCapability, m_heOperation, m_htCapability, m_htOperation, m_rates, m_ssid, m_vhtCapability, m_vhtOperation, ns3::Simulator::Now(), ns3::WifiInformationElement::Serialize(), ns3::CapabilityInformation::Serialize(), ns3::CfParameterSet::Serialize(), ns3::DsssParameterSet::Serialize(), ns3::EdcaParameterSet::Serialize(), ns3::ErpInformation::Serialize(), ns3::ExtendedCapabilities::Serialize(), ns3::HeCapabilities::Serialize(), ns3::HeOperation::Serialize(), ns3::HtCapabilities::Serialize(), ns3::HtOperation::Serialize(), ns3::ExtendedSupportedRatesIE::Serialize(), ns3::VhtCapabilities::Serialize(), ns3::VhtOperation::Serialize(), visualizer.core::start(), ns3::Buffer::Iterator::WriteHtolsbU16(), and ns3::Buffer::Iterator::WriteHtolsbU64().
SetBeaconIntervalUs()
void ns3::MgtProbeResponseHeader::SetBeaconIntervalUs (uint64_t us)
Set the beacon interval in microseconds unit.
Parameters
us beacon interval in microseconds unit
Definition at line 334 of file mgt-headers.cc.
References m_beaconInterval.
Referenced by ns3::MeshWifiBeacon::MeshWifiBeacon(), ns3::ApWifiMac::SendOneBeacon(), and ns3::ApWifiMac::SendProbeResp().
SetCapabilities()
void ns3::MgtProbeResponseHeader::SetCapabilities (CapabilityInformation capabilities)
Set the Capability information.
Parameters
capabilities Capability information
Definition at line 220 of file mgt-headers.cc.
References m_capability.
Referenced by ns3::ApWifiMac::SendOneBeacon(), and ns3::ApWifiMac::SendProbeResp().
SetCfParameterSet()
void ns3::MgtProbeResponseHeader::SetCfParameterSet (CfParameterSet cfParameterSet)
Set the CF parameter set.
Parameters
cfParameterSet CF parameter set
Definition at line 316 of file mgt-headers.cc.
References m_cfParameterSet.
Referenced by ns3::ApWifiMac::SendOneBeacon().
SetDsssParameterSet()
void ns3::MgtProbeResponseHeader::SetDsssParameterSet (DsssParameterSet dsssParameterSet)
Set the DSSS Parameter Set.
Parameters
dsssParameterSet the DSSS Parameter Set
Definition at line 346 of file mgt-headers.cc.
References m_dsssParameterSet.
Referenced by ns3::ApWifiMac::SendOneBeacon(), and ns3::ApWifiMac::SendProbeResp().
SetEdcaParameterSet()
void ns3::MgtProbeResponseHeader::SetEdcaParameterSet (EdcaParameterSet edcaParameterSet)
Set the EDCA Parameter Set.
Parameters
edcaParameterSet the EDCA Parameter Set
Definition at line 370 of file mgt-headers.cc.
References m_edcaParameterSet.
Referenced by ns3::ApWifiMac::SendOneBeacon(), and ns3::ApWifiMac::SendProbeResp().
SetErpInformation()
void ns3::MgtProbeResponseHeader::SetErpInformation (ErpInformation erpInformation)
Set the ERP information.
Parameters
erpInformation the ERP information
Definition at line 358 of file mgt-headers.cc.
References m_erpInformation.
Referenced by ns3::ApWifiMac::SendOneBeacon(), and ns3::ApWifiMac::SendProbeResp().
SetExtendedCapabilities()
void ns3::MgtProbeResponseHeader::SetExtendedCapabilities (ExtendedCapabilities extendedCapabilities)
Set the extended capabilities.
Parameters
extendedCapabilities the extended capabilities
Definition at line 232 of file mgt-headers.cc.
References m_extendedCapability.
Referenced by ns3::ApWifiMac::SendOneBeacon(), and ns3::ApWifiMac::SendProbeResp().
SetHeCapabilities()
void ns3::MgtProbeResponseHeader::SetHeCapabilities (HeCapabilities heCapabilities)
Set the HE capabilities.
Parameters
heCapabilities HE capabilities
Definition at line 292 of file mgt-headers.cc.
References m_heCapability.
Referenced by ns3::ApWifiMac::SendOneBeacon(), and ns3::ApWifiMac::SendProbeResp().
SetHeOperation()
void ns3::MgtProbeResponseHeader::SetHeOperation (HeOperation heOperation)
Set the HE operation.
Parameters
heOperation HE operation
Definition at line 304 of file mgt-headers.cc.
References m_heOperation.
Referenced by ns3::ApWifiMac::SendOneBeacon(), and ns3::ApWifiMac::SendProbeResp().
SetHtCapabilities()
void ns3::MgtProbeResponseHeader::SetHtCapabilities (HtCapabilities htCapabilities)
Set the HT capabilities.
Parameters
htCapabilities HT capabilities
Definition at line 244 of file mgt-headers.cc.
References m_htCapability.
Referenced by ns3::ApWifiMac::SendOneBeacon(), and ns3::ApWifiMac::SendProbeResp().
SetHtOperation()
void ns3::MgtProbeResponseHeader::SetHtOperation (HtOperation htOperation)
Set the HT operation.
Parameters
htOperation HT operation
Definition at line 256 of file mgt-headers.cc.
References m_htOperation.
Referenced by ns3::ApWifiMac::SendOneBeacon(), and ns3::ApWifiMac::SendProbeResp().
SetSsid()
void ns3::MgtProbeResponseHeader::SetSsid (Ssid ssid)
Set the Service Set Identifier (SSID).
Parameters
ssid SSID
Definition at line 328 of file mgt-headers.cc.
References m_ssid, and third::ssid.
Referenced by ns3::MeshWifiBeacon::MeshWifiBeacon(), ns3::ApWifiMac::SendOneBeacon(), and ns3::ApWifiMac::SendProbeResp().
SetSupportedRates()
void ns3::MgtProbeResponseHeader::SetSupportedRates (SupportedRates rates)
Set the supported rates.
Parameters
rates the supported rates
Definition at line 340 of file mgt-headers.cc.
References m_rates.
Referenced by ns3::MeshWifiBeacon::MeshWifiBeacon(), ns3::ApWifiMac::SendOneBeacon(), and ns3::ApWifiMac::SendProbeResp().
SetVhtCapabilities()
void ns3::MgtProbeResponseHeader::SetVhtCapabilities (VhtCapabilities vhtCapabilities)
Set the VHT capabilities.
Parameters
vhtCapabilities VHT capabilities
Definition at line 268 of file mgt-headers.cc.
References m_vhtCapability.
Referenced by ns3::ApWifiMac::SendOneBeacon(), and ns3::ApWifiMac::SendProbeResp().
SetVhtOperation()
void ns3::MgtProbeResponseHeader::SetVhtOperation (VhtOperation vhtOperation)
Set the VHT operation.
Parameters
vhtOperation VHT operation
Definition at line 280 of file mgt-headers.cc.
References m_vhtOperation.
Referenced by ns3::ApWifiMac::SendOneBeacon(), and ns3::ApWifiMac::SendProbeResp().
Member Data Documentation
m_beaconInterval
uint64_t ns3::MgtProbeResponseHeader::m_beaconInterval private
Beacon interval.
Definition at line 826 of file mgt-headers.h.
Referenced by Deserialize(), GetBeaconIntervalUs(), Serialize(), and SetBeaconIntervalUs().
m_capability
CapabilityInformation ns3::MgtProbeResponseHeader::m_capability private
Capability information.
Definition at line 828 of file mgt-headers.h.
Referenced by Deserialize(), GetCapabilities(), GetSerializedSize(), Serialize(), and SetCapabilities().
m_cfParameterSet
CfParameterSet ns3::MgtProbeResponseHeader::m_cfParameterSet private
CF parameter set.
Definition at line 839 of file mgt-headers.h.
Referenced by Deserialize(), GetCfParameterSet(), GetSerializedSize(), Serialize(), and SetCfParameterSet().
m_dsssParameterSet
DsssParameterSet ns3::MgtProbeResponseHeader::m_dsssParameterSet private
DSSS Parameter Set.
Definition at line 829 of file mgt-headers.h.
Referenced by Deserialize(), GetDsssParameterSet(), GetSerializedSize(), Serialize(), and SetDsssParameterSet().
m_edcaParameterSet
EdcaParameterSet ns3::MgtProbeResponseHeader::m_edcaParameterSet private
EDCA Parameter Set.
Definition at line 838 of file mgt-headers.h.
Referenced by Deserialize(), GetEdcaParameterSet(), GetSerializedSize(), Serialize(), and SetEdcaParameterSet().
m_erpInformation
ErpInformation ns3::MgtProbeResponseHeader::m_erpInformation private
ERP information.
Definition at line 837 of file mgt-headers.h.
Referenced by Deserialize(), GetErpInformation(), GetSerializedSize(), Print(), Serialize(), and SetErpInformation().
m_extendedCapability
ExtendedCapabilities ns3::MgtProbeResponseHeader::m_extendedCapability private
extended capabilities
Definition at line 830 of file mgt-headers.h.
Referenced by Deserialize(), GetExtendedCapabilities(), GetSerializedSize(), Print(), Serialize(), and SetExtendedCapabilities().
m_heCapability
HeCapabilities ns3::MgtProbeResponseHeader::m_heCapability private
HE capabilities.
Definition at line 835 of file mgt-headers.h.
Referenced by Deserialize(), GetHeCapabilities(), GetSerializedSize(), Print(), Serialize(), and SetHeCapabilities().
m_heOperation
HeOperation ns3::MgtProbeResponseHeader::m_heOperation private
HE operation.
Definition at line 836 of file mgt-headers.h.
Referenced by Deserialize(), GetHeOperation(), GetSerializedSize(), Print(), Serialize(), and SetHeOperation().
m_htCapability
HtCapabilities ns3::MgtProbeResponseHeader::m_htCapability private
HT capabilities.
Definition at line 831 of file mgt-headers.h.
Referenced by Deserialize(), GetHtCapabilities(), GetSerializedSize(), Print(), Serialize(), and SetHtCapabilities().
m_htOperation
HtOperation ns3::MgtProbeResponseHeader::m_htOperation private
HT operation.
Definition at line 832 of file mgt-headers.h.
Referenced by Deserialize(), GetHtOperation(), GetSerializedSize(), Print(), Serialize(), and SetHtOperation().
m_rates
SupportedRates ns3::MgtProbeResponseHeader::m_rates private
List of supported rates.
Definition at line 827 of file mgt-headers.h.
Referenced by Deserialize(), GetSerializedSize(), GetSupportedRates(), Print(), Serialize(), and SetSupportedRates().
m_ssid
Ssid ns3::MgtProbeResponseHeader::m_ssid private
Service set ID (SSID)
Definition at line 825 of file mgt-headers.h.
Referenced by Deserialize(), GetSerializedSize(), GetSsid(), Print(), Serialize(), and SetSsid().
m_timestamp
uint64_t ns3::MgtProbeResponseHeader::m_timestamp private
Timestamp.
Definition at line 824 of file mgt-headers.h.
Referenced by Deserialize(), and GetTimestamp().
m_vhtCapability
VhtCapabilities ns3::MgtProbeResponseHeader::m_vhtCapability private
VHT capabilities.
Definition at line 833 of file mgt-headers.h.
Referenced by Deserialize(), GetSerializedSize(), GetVhtCapabilities(), Print(), Serialize(), and SetVhtCapabilities().
m_vhtOperation
VhtOperation ns3::MgtProbeResponseHeader::m_vhtOperation private
VHT operation.
Definition at line 834 of file mgt-headers.h.
Referenced by Deserialize(), GetSerializedSize(), GetVhtOperation(), Print(), Serialize(), and SetVhtOperation().
The documentation for this class was generated from the following files:
src/wifi/model/mgt-headers.h
src/wifi/model/mgt-headers.cc