ns-3: ns3::lorawan::LoraRadioEnergyModel Class Reference
ns3::lorawan::LoraRadioEnergyModel Class Reference
Energy Models
A WiFi radio energy model.
#include "lora-radio-energy-model.h"
Public Types
typedef Callback< void > LoraRadioEnergyDepletionCallback
Callback type for energy depletion handling.
typedef Callback< void > LoraRadioEnergyRechargedCallback
Callback type for energy recharged handling.
Public Types inherited from ns3::DeviceEnergyModel
typedef Callback< void, int > ChangeStateCallback
Callback type for ChangeState function.
Public Member Functions
LoraRadioEnergyModel ()
virtual ~LoraRadioEnergyModel ()
void ChangeState (int newState)
Changes state of the LoraRadioEnergyMode.
EndDeviceLoraPhy::State GetCurrentState (void) const
LoraRadioEnergyModelPhyListener * GetPhyListener (void)
double GetRxCurrentA (void) const
Gets receive current.
double GetSleepCurrentA (void) const
Gets sleep current.
double GetStandbyCurrentA (void) const
Gets idle current.
double GetTotalEnergyConsumption (void) const
double GetTxCurrentA (void) const
Gets transmit current.
void HandleEnergyChanged (void)
Handles energy recharged.
void HandleEnergyDepletion (void)
Handles energy depletion.
void HandleEnergyRecharged (void)
Handles energy recharged.
void SetEnergyDepletionCallback (LoraRadioEnergyDepletionCallback callback)
void SetEnergyRechargedCallback (LoraRadioEnergyRechargedCallback callback)
void SetEnergySource (Ptr< EnergySource > source)
Sets pointer to EnergySouce installed on node.
void SetRxCurrentA (double rxCurrentA)
Sets receive current.
void SetSleepCurrentA (double sleepCurrentA)
Sets sleep current.
void SetStandbyCurrentA (double idleCurrentA)
Sets idle current.
void SetTxCurrentA (double txCurrentA)
Sets transmit current.
void SetTxCurrentFromModel (double txPowerDbm)
Calls the CalcTxCurrent method of the tx current model to compute the tx current based on such model.
void SetTxCurrentModel (Ptr< LoraTxCurrentModel > model)
Public Member Functions inherited from ns3::DeviceEnergyModel
DeviceEnergyModel ()
virtual ~DeviceEnergyModel ()
double GetCurrentA (void) const
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::DeviceEnergyModel
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void DoDispose (void)
Destructor implementation.
double DoGetCurrentA (void) const
void SetLoraRadioState (const EndDeviceLoraPhy::State state)
Private Attributes
EndDeviceLoraPhy::State m_currentState
current state the radio is in
LoraRadioEnergyDepletionCallback m_energyDepletionCallback
Energy depletion callback.
LoraRadioEnergyRechargedCallback m_energyRechargedCallback
Energy recharged callback.
double m_idleCurrentA
idle current
bool m_isSupersededChangeState
superseded change state
Time m_lastUpdateTime
time stamp of previous energy update
LoraRadioEnergyModelPhyListener * m_listener
EndDeviceLoraPhy listener.
uint8_t m_nPendingChangeState
pending state change
double m_rxCurrentA
receive current
double m_sleepCurrentA
sleep current
Ptr< EnergySource > m_source
energy source
TracedValue< double > m_totalEnergyConsumption
This variable keeps track of the total energy consumed by this model.
double m_txCurrentA
transmit current
Ptr< LoraTxCurrentModel > m_txCurrentModel
current model
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
A WiFi radio energy model.
4 states are defined for the radio: TX, RX, STANDBY, SLEEP. Default state is STANDBY. The different types of transactions that are defined are:
Tx: State goes from STANDBY to TX, radio is in TX state for TX_duration, then state goes from TX to STANDBY.
Rx: State goes from STANDBY to RX, radio is in RX state for RX_duration, then state goes from RX to STANDBY.
Go_to_Sleep: State goes from STANDBY to SLEEP.
End_of_Sleep: State goes from SLEEP to STANDBY. The class keeps track of what state the radio is currently in.
Energy calculation: For each transaction, this model notifies EnergySource object. The EnergySource object will query this model for the total current. Then the EnergySource object uses the total current to calculate energy.
Definition at line 127 of file lora-radio-energy-model.h.
Member Typedef Documentation
LoraRadioEnergyDepletionCallback
typedef Callback<void> ns3::lorawan::LoraRadioEnergyModel::LoraRadioEnergyDepletionCallback
Callback type for energy depletion handling.
Definition at line 133 of file lora-radio-energy-model.h.
LoraRadioEnergyRechargedCallback
typedef Callback<void> ns3::lorawan::LoraRadioEnergyModel::LoraRadioEnergyRechargedCallback
Callback type for energy recharged handling.
Definition at line 138 of file lora-radio-energy-model.h.
Constructor & Destructor Documentation
LoraRadioEnergyModel()
ns3::lorawan::LoraRadioEnergyModel::LoraRadioEnergyModel ()
Definition at line 74 of file lora-radio-energy-model.cc.
References ns3::DeviceEnergyModel::ChangeState(), m_currentState, m_energyDepletionCallback, m_isSupersededChangeState, m_lastUpdateTime, m_listener, m_nPendingChangeState, m_source, ns3::MakeCallback(), NS_LOG_FUNCTION, ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::Nullify(), ns3::Seconds(), ns3::lorawan::LoraRadioEnergyModelPhyListener::SetChangeStateCallback(), SetTxCurrentFromModel(), ns3::lorawan::LoraRadioEnergyModelPhyListener::SetUpdateTxCurrentCallback(), and ns3::lorawan::EndDeviceLoraPhy::SLEEP.
~LoraRadioEnergyModel()
ns3::lorawan::LoraRadioEnergyModel::~LoraRadioEnergyModel () virtual
Definition at line 90 of file lora-radio-energy-model.cc.
References m_listener, and NS_LOG_FUNCTION.
Member Function Documentation
ChangeState()
void ns3::lorawan::LoraRadioEnergyModel::ChangeState (int newState) virtual
Changes state of the LoraRadioEnergyMode.
Parameters
newState New state the lora radio is in.
Implements DeviceEnergyModel::ChangeState.
Implements ns3::DeviceEnergyModel.
Definition at line 214 of file lora-radio-energy-model.cc.
References aloha::duration, m_currentState, m_idleCurrentA, m_isSupersededChangeState, m_lastUpdateTime, m_nPendingChangeState, m_rxCurrentA, m_sleepCurrentA, m_source, m_totalEnergyConsumption, m_txCurrentA, ns3::Simulator::Now(), NS_ASSERT, NS_FATAL_ERROR, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::lorawan::EndDeviceLoraPhy::RX, SetLoraRadioState(), ns3::lorawan::EndDeviceLoraPhy::SLEEP, ns3::lorawan::EndDeviceLoraPhy::STANDBY, and ns3::lorawan::EndDeviceLoraPhy::TX.
DoDispose()
void ns3::lorawan::LoraRadioEnergyModel::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 318 of file lora-radio-energy-model.cc.
References m_energyDepletionCallback, m_source, NS_LOG_FUNCTION, and ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::Nullify().
DoGetCurrentA()
double ns3::lorawan::LoraRadioEnergyModel::DoGetCurrentA (void) const private virtual
Returns
Current draw of device, at current state.
Implements DeviceEnergyModel::GetCurrentA.
Reimplemented from ns3::DeviceEnergyModel.
Definition at line 326 of file lora-radio-energy-model.cc.
References m_currentState, m_idleCurrentA, m_rxCurrentA, m_sleepCurrentA, m_txCurrentA, NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::lorawan::EndDeviceLoraPhy::RX, ns3::lorawan::EndDeviceLoraPhy::SLEEP, ns3::lorawan::EndDeviceLoraPhy::STANDBY, and ns3::lorawan::EndDeviceLoraPhy::TX.
GetCurrentState()
EndDeviceLoraPhy::State ns3::lorawan::LoraRadioEnergyModel::GetCurrentState (void) const
Returns
Current state.
Definition at line 168 of file lora-radio-energy-model.cc.
References m_currentState, and NS_LOG_FUNCTION.
GetPhyListener()
LoraRadioEnergyModelPhyListener * ns3::lorawan::LoraRadioEnergyModel::GetPhyListener (void)
Returns
Pointer to the PHY listener.
Definition at line 307 of file lora-radio-energy-model.cc.
References m_listener, and NS_LOG_FUNCTION.
GetRxCurrentA()
double ns3::lorawan::LoraRadioEnergyModel::GetRxCurrentA (void) const
Gets receive current.
Returns
receive current of the lora device.
Definition at line 140 of file lora-radio-energy-model.cc.
References m_rxCurrentA, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetSleepCurrentA()
double ns3::lorawan::LoraRadioEnergyModel::GetSleepCurrentA (void) const
Gets sleep current.
Returns
sleep current of the lora device.
Definition at line 154 of file lora-radio-energy-model.cc.
References m_sleepCurrentA, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetStandbyCurrentA()
double ns3::lorawan::LoraRadioEnergyModel::GetStandbyCurrentA (void) const
Gets idle current.
Returns
idle current of the lora device.
Definition at line 112 of file lora-radio-energy-model.cc.
References m_idleCurrentA, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetTotalEnergyConsumption()
double ns3::lorawan::LoraRadioEnergyModel::GetTotalEnergyConsumption (void) const virtual
Returns
Total energy consumption of the wifi device.
Implements DeviceEnergyModel::GetTotalEnergyConsumption.
Implements ns3::DeviceEnergyModel.
Definition at line 105 of file lora-radio-energy-model.cc.
References m_totalEnergyConsumption, and NS_LOG_FUNCTION.
GetTxCurrentA()
double ns3::lorawan::LoraRadioEnergyModel::GetTxCurrentA (void) const
Gets transmit current.
Returns
transmit current of the lora device.
Definition at line 126 of file lora-radio-energy-model.cc.
References m_txCurrentA, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::lorawan::LoraRadioEnergyModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 32 of file lora-radio-energy-model.cc.
References GetRxCurrentA(), GetSleepCurrentA(), GetStandbyCurrentA(), GetTxCurrentA(), m_totalEnergyConsumption, m_txCurrentModel, ns3::MakeDoubleAccessor(), ns3::MakePointerAccessor(), ns3::MakeTraceSourceAccessor(), ns3::TypeId::SetParent(), SetRxCurrentA(), SetSleepCurrentA(), SetStandbyCurrentA(), and SetTxCurrentA().
HandleEnergyChanged()
void ns3::lorawan::LoraRadioEnergyModel::HandleEnergyChanged (void) virtual
Handles energy recharged.
Implements DeviceEnergyModel::HandleEnergyChanged
Implements ns3::DeviceEnergyModel.
Definition at line 288 of file lora-radio-energy-model.cc.
References NS_LOG_DEBUG, and NS_LOG_FUNCTION.
HandleEnergyDepletion()
void ns3::lorawan::LoraRadioEnergyModel::HandleEnergyDepletion (void) virtual
Handles energy depletion.
Implements DeviceEnergyModel::HandleEnergyDepletion
Implements ns3::DeviceEnergyModel.
Definition at line 276 of file lora-radio-energy-model.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_energyDepletionCallback, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
HandleEnergyRecharged()
void ns3::lorawan::LoraRadioEnergyModel::HandleEnergyRecharged (void) virtual
Handles energy recharged.
Implements DeviceEnergyModel::HandleEnergyRecharged
Implements ns3::DeviceEnergyModel.
Definition at line 295 of file lora-radio-energy-model.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_energyRechargedCallback, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
SetEnergyDepletionCallback()
void ns3::lorawan::LoraRadioEnergyModel::SetEnergyDepletionCallback (LoraRadioEnergyDepletionCallback callback)
Parameters
callback Callback function.
Sets callback for energy depletion handling.
Definition at line 175 of file lora-radio-energy-model.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_energyDepletionCallback, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
SetEnergyRechargedCallback()
void ns3::lorawan::LoraRadioEnergyModel::SetEnergyRechargedCallback (LoraRadioEnergyRechargedCallback callback)
Parameters
callback Callback function.
Sets callback for energy recharged handling.
Definition at line 187 of file lora-radio-energy-model.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_energyRechargedCallback, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
SetEnergySource()
void ns3::lorawan::LoraRadioEnergyModel::SetEnergySource (Ptr< EnergySource > source) virtual
Sets pointer to EnergySouce installed on node.
Parameters
source Pointer to EnergySource installed on node.
Implements DeviceEnergyModel::SetEnergySource.
Implements ns3::DeviceEnergyModel.
Definition at line 97 of file lora-radio-energy-model.cc.
References m_source, NS_ASSERT, and NS_LOG_FUNCTION.
SetLoraRadioState()
void ns3::lorawan::LoraRadioEnergyModel::SetLoraRadioState (const EndDeviceLoraPhy::State state) private
Parameters
state New state the radio device is currently in.
Sets current state. This function is private so that only the energy model can change its own state.
Definition at line 345 of file lora-radio-energy-model.cc.
References m_currentState, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::lorawan::EndDeviceLoraPhy::RX, ns3::lorawan::EndDeviceLoraPhy::SLEEP, ns3::lorawan::EndDeviceLoraPhy::STANDBY, and ns3::lorawan::EndDeviceLoraPhy::TX.
Referenced by ChangeState().
SetRxCurrentA()
void ns3::lorawan::LoraRadioEnergyModel::SetRxCurrentA (double rxCurrentA)
Sets receive current.
Parameters
rxCurrentA the receive current
Definition at line 147 of file lora-radio-energy-model.cc.
References m_rxCurrentA, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetSleepCurrentA()
void ns3::lorawan::LoraRadioEnergyModel::SetSleepCurrentA (double sleepCurrentA)
Sets sleep current.
Parameters
sleepCurrentA the sleep current
Definition at line 161 of file lora-radio-energy-model.cc.
References m_sleepCurrentA, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetStandbyCurrentA()
void ns3::lorawan::LoraRadioEnergyModel::SetStandbyCurrentA (double idleCurrentA)
Sets idle current.
Parameters
idleCurrentA the idle current
Definition at line 119 of file lora-radio-energy-model.cc.
References m_idleCurrentA, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetTxCurrentA()
void ns3::lorawan::LoraRadioEnergyModel::SetTxCurrentA (double txCurrentA)
Sets transmit current.
Parameters
txCurrentA the transmit current
Definition at line 133 of file lora-radio-energy-model.cc.
References m_txCurrentA, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
SetTxCurrentFromModel()
void ns3::lorawan::LoraRadioEnergyModel::SetTxCurrentFromModel (double txPowerDbm)
Calls the CalcTxCurrent method of the tx current model to compute the tx current based on such model.
Parameters
txPowerDbm the nominal tx power in dBm
Definition at line 205 of file lora-radio-energy-model.cc.
References m_txCurrentA, and m_txCurrentModel.
Referenced by LoraRadioEnergyModel().
SetTxCurrentModel()
void ns3::lorawan::LoraRadioEnergyModel::SetTxCurrentModel (Ptr< LoraTxCurrentModel > model)
Parameters
model the model used to compute the lora tx current.
Definition at line 199 of file lora-radio-energy-model.cc.
References m_txCurrentModel.
Member Data Documentation
m_currentState
EndDeviceLoraPhy::State ns3::lorawan::LoraRadioEnergyModel::m_currentState private
current state the radio is in
Definition at line 316 of file lora-radio-energy-model.h.
Referenced by LoraRadioEnergyModel(), ChangeState(), DoGetCurrentA(), GetCurrentState(), and SetLoraRadioState().
m_energyDepletionCallback
LoraRadioEnergyDepletionCallback ns3::lorawan::LoraRadioEnergyModel::m_energyDepletionCallback private
Energy depletion callback.
Definition at line 323 of file lora-radio-energy-model.h.
Referenced by LoraRadioEnergyModel(), DoDispose(), HandleEnergyDepletion(), and SetEnergyDepletionCallback().
m_energyRechargedCallback
LoraRadioEnergyRechargedCallback ns3::lorawan::LoraRadioEnergyModel::m_energyRechargedCallback private
Energy recharged callback.
Definition at line 326 of file lora-radio-energy-model.h.
Referenced by HandleEnergyRecharged(), and SetEnergyRechargedCallback().
m_idleCurrentA
double ns3::lorawan::LoraRadioEnergyModel::m_idleCurrentA private
idle current
Definition at line 307 of file lora-radio-energy-model.h.
Referenced by ChangeState(), DoGetCurrentA(), GetStandbyCurrentA(), and SetStandbyCurrentA().
m_isSupersededChangeState
bool ns3::lorawan::LoraRadioEnergyModel::m_isSupersededChangeState private
superseded change state
Definition at line 320 of file lora-radio-energy-model.h.
Referenced by LoraRadioEnergyModel(), and ChangeState().
m_lastUpdateTime
Time ns3::lorawan::LoraRadioEnergyModel::m_lastUpdateTime private
time stamp of previous energy update
Definition at line 317 of file lora-radio-energy-model.h.
Referenced by LoraRadioEnergyModel(), and ChangeState().
m_listener
LoraRadioEnergyModelPhyListener* ns3::lorawan::LoraRadioEnergyModel::m_listener private
EndDeviceLoraPhy listener.
Definition at line 329 of file lora-radio-energy-model.h.
Referenced by LoraRadioEnergyModel(), ~LoraRadioEnergyModel(), and GetPhyListener().
m_nPendingChangeState
uint8_t ns3::lorawan::LoraRadioEnergyModel::m_nPendingChangeState private
pending state change
Definition at line 319 of file lora-radio-energy-model.h.
Referenced by LoraRadioEnergyModel(), and ChangeState().
m_rxCurrentA
double ns3::lorawan::LoraRadioEnergyModel::m_rxCurrentA private
receive current
Definition at line 306 of file lora-radio-energy-model.h.
Referenced by ChangeState(), DoGetCurrentA(), GetRxCurrentA(), and SetRxCurrentA().
m_sleepCurrentA
double ns3::lorawan::LoraRadioEnergyModel::m_sleepCurrentA private
sleep current
Definition at line 308 of file lora-radio-energy-model.h.
Referenced by ChangeState(), DoGetCurrentA(), GetSleepCurrentA(), and SetSleepCurrentA().
m_source
Ptr<EnergySource> ns3::lorawan::LoraRadioEnergyModel::m_source private
energy source
Definition at line 302 of file lora-radio-energy-model.h.
Referenced by LoraRadioEnergyModel(), ChangeState(), DoDispose(), and SetEnergySource().
m_totalEnergyConsumption
TracedValue<double> ns3::lorawan::LoraRadioEnergyModel::m_totalEnergyConsumption private
This variable keeps track of the total energy consumed by this model.
Definition at line 313 of file lora-radio-energy-model.h.
Referenced by ChangeState(), GetTotalEnergyConsumption(), and GetTypeId().
m_txCurrentA
double ns3::lorawan::LoraRadioEnergyModel::m_txCurrentA private
transmit current
Definition at line 305 of file lora-radio-energy-model.h.
Referenced by ChangeState(), DoGetCurrentA(), GetTxCurrentA(), SetTxCurrentA(), and SetTxCurrentFromModel().
m_txCurrentModel
Ptr<LoraTxCurrentModel> ns3::lorawan::LoraRadioEnergyModel::m_txCurrentModel private
current model
Definition at line 310 of file lora-radio-energy-model.h.
Referenced by GetTypeId(), SetTxCurrentFromModel(), and SetTxCurrentModel().
The documentation for this class was generated from the following files:
src/lorawan/model/lora-radio-energy-model.h
src/lorawan/model/lora-radio-energy-model.cc