ns-3: EpsGtpuHeaderTestCase Class Reference
EpsGtpuHeaderTestCase Class Reference
Test 1.Check header coding and decoding.
#include "epc-test-gtpu.h"
Public Member Functions
EpsGtpuHeaderTestCase ()
TestCase.
virtual ~EpsGtpuHeaderTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test 1.Check header coding and decoding.
Definition at line 53 of file epc-test-gtpu.h.
Constructor & Destructor Documentation
EpsGtpuHeaderTestCase()
EpsGtpuHeaderTestCase::EpsGtpuHeaderTestCase ()
TestCase.
Definition at line 50 of file epc-test-gtpu.cc.
References NS_LOG_INFO.
~EpsGtpuHeaderTestCase()
EpsGtpuHeaderTestCase::~EpsGtpuHeaderTestCase () virtual
Definition at line 56 of file epc-test-gtpu.cc.
Member Function Documentation
DoRun()
void EpsGtpuHeaderTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 61 of file epc-test-gtpu.cc.
References ns3::Packet::AddHeader(), ns3::LOG_LEVEL_ALL, ns3::LOG_PREFIX_FUNC, ns3::LOG_PREFIX_TIME, ns3::LogComponentEnable(), NS_TEST_ASSERT_MSG_EQ, ns3::Packet::RemoveHeader(), ns3::GtpuHeader::SetExtensionHeaderFlag(), ns3::GtpuHeader::SetLength(), ns3::GtpuHeader::SetMessageType(), ns3::GtpuHeader::SetNextExtensionType(), ns3::GtpuHeader::SetNPduNumber(), ns3::GtpuHeader::SetNPduNumberFlag(), ns3::GtpuHeader::SetProtocolType(), ns3::GtpuHeader::SetSequenceNumber(), ns3::GtpuHeader::SetSequenceNumberFlag(), ns3::GtpuHeader::SetTeid(), and ns3::GtpuHeader::SetVersion().
The documentation for this class was generated from the following files:
src/lte/test/epc-test-gtpu.h
src/lte/test/epc-test-gtpu.cc