ns-3: ns3::UlMap Class Reference
ns3::UlMap Class Reference
This class implements the UL-MAP_IE message as described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems" 8.2.1.8.2 Compressed UL-MAP, page 404.
#include "ul-mac-messages.h"
Public Member Functions
UlMap (void)
virtual ~UlMap (void)
void AddUlMapElement (OfdmUlMapIe ulMapElement)
Add UL map element.
uint32_t Deserialize (Buffer::Iterator start)
uint32_t GetAllocationStartTime (void) const
Get allocation start time.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
std::string GetName (void) const
Get name.
uint32_t GetSerializedSize (void) const
uint8_t GetUcdCount (void) const
Get UCD count.
std::list< OfdmUlMapIe > GetUlMapElements (void) const
Get UL map elements.
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetAllocationStartTime (uint32_t allocationStartTime)
Set allocation start time.
void SetUcdCount (uint8_t ucdCount)
Set UCD count.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint32_t m_allocationStartTime
allocation start time
uint8_t m_reserved
changed as per the amendment 802.16e-2005
uint8_t m_ucdCount
UCD count.
std::list< OfdmUlMapIe > m_ulMapElements
UL map elements.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class implements the UL-MAP_IE message as described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems" 8.2.1.8.2 Compressed UL-MAP, page 404.
Definition at line 573 of file ul-mac-messages.h.
Constructor & Destructor Documentation
UlMap()
ns3::UlMap::UlMap (void)
Definition at line 583 of file ul-mac-messages.cc.
~UlMap()
ns3::UlMap::~UlMap (void) virtual
Definition at line 590 of file ul-mac-messages.cc.
Member Function Documentation
AddUlMapElement()
void ns3::UlMap::AddUlMapElement (OfdmUlMapIe ulMapElement)
Add UL map element.
Parameters
ulMapElement the UL map element
Definition at line 607 of file ul-mac-messages.cc.
References m_ulMapElements.
Referenced by ns3::BaseStationNetDevice::CreateUlMap(), and Deserialize().
Deserialize()
uint32_t ns3::UlMap::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 692 of file ul-mac-messages.cc.
References AddUlMapElement(), ns3::Buffer::Iterator::GetDistanceFrom(), ns3::OfdmUlMapIe::GetUiuc(), m_allocationStartTime, m_reserved, m_ucdCount, m_ulMapElements, ns3::OfdmUlMapIe::Read(), ns3::Buffer::Iterator::ReadU32(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetAllocationStartTime()
uint32_t ns3::UlMap::GetAllocationStartTime (void) const
Get allocation start time.
Returns
the allocation start time
Definition at line 619 of file ul-mac-messages.cc.
References m_allocationStartTime.
Referenced by ns3::SubscriberStationNetDevice::ProcessUlMap().
GetInstanceTypeId()
TypeId ns3::UlMap::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 648 of file ul-mac-messages.cc.
References GetTypeId().
GetName()
std::string ns3::UlMap::GetName (void) const
Get name.
Returns
the name
Definition at line 631 of file ul-mac-messages.cc.
GetSerializedSize()
uint32_t ns3::UlMap::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 662 of file ul-mac-messages.cc.
References ns3::OfdmUlMapIe::GetSize(), and m_ulMapElements.
GetTypeId()
TypeId ns3::UlMap::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 637 of file ul-mac-messages.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
GetUcdCount()
uint8_t ns3::UlMap::GetUcdCount (void) const
Get UCD count.
Returns
the UCD count
Definition at line 613 of file ul-mac-messages.cc.
References m_ucdCount.
Referenced by ns3::SubscriberStationNetDevice::ProcessUlMap().
GetUlMapElements()
std::list< OfdmUlMapIe > ns3::UlMap::GetUlMapElements (void) const
Get UL map elements.
Returns
the UL map elements
Definition at line 625 of file ul-mac-messages.cc.
References m_ulMapElements.
Referenced by ns3::SubscriberStationNetDevice::ProcessUlMap().
Print()
void ns3::UlMap::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 654 of file ul-mac-messages.cc.
References m_allocationStartTime, m_ucdCount, and m_ulMapElements.
Serialize()
void ns3::UlMap::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 676 of file ul-mac-messages.cc.
References m_allocationStartTime, m_reserved, m_ucdCount, m_ulMapElements, visualizer.core::start(), ns3::OfdmUlMapIe::Write(), ns3::Buffer::Iterator::WriteU32(), and ns3::Buffer::Iterator::WriteU8().
SetAllocationStartTime()
void ns3::UlMap::SetAllocationStartTime (uint32_t allocationStartTime)
Set allocation start time.
Parameters
allocationStartTime the allocation start time
Definition at line 601 of file ul-mac-messages.cc.
References m_allocationStartTime.
Referenced by ns3::BaseStationNetDevice::CreateUlMap().
SetUcdCount()
void ns3::UlMap::SetUcdCount (uint8_t ucdCount)
Set UCD count.
Parameters
ucdCount the UCD count
Definition at line 595 of file ul-mac-messages.cc.
References m_ucdCount.
Referenced by ns3::BaseStationNetDevice::CreateUlMap().
Member Data Documentation
m_allocationStartTime
uint32_t ns3::UlMap::m_allocationStartTime private
allocation start time
Definition at line 630 of file ul-mac-messages.h.
Referenced by Deserialize(), GetAllocationStartTime(), Print(), Serialize(), and SetAllocationStartTime().
m_reserved
uint8_t ns3::UlMap::m_reserved private
changed as per the amendment 802.16e-2005
Definition at line 627 of file ul-mac-messages.h.
Referenced by Deserialize(), and Serialize().
m_ucdCount
uint8_t ns3::UlMap::m_ucdCount private
UCD count.
Definition at line 629 of file ul-mac-messages.h.
Referenced by Deserialize(), GetUcdCount(), Print(), Serialize(), and SetUcdCount().
m_ulMapElements
std::list<OfdmUlMapIe> ns3::UlMap::m_ulMapElements private
UL map elements.
Definition at line 631 of file ul-mac-messages.h.
Referenced by AddUlMapElement(), Deserialize(), GetSerializedSize(), GetUlMapElements(), Print(), and Serialize().
The documentation for this class was generated from the following files:
src/wimax/model/ul-mac-messages.h
src/wimax/model/ul-mac-messages.cc