ns-3: PbbTestSuite Class Reference
PbbTestSuite Class Reference
Network » Network module unit tests | Test suites
PacketBb TestSuite.
Public Member Functions
PbbTestSuite ()
Public Member Functions inherited from ns3::TestSuite
TestSuite (std::string name, Type type=UNIT)
Construct a new test suite.
TestSuite::Type GetTestType (void)
get the kind of test this test suite implements
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Additional Inherited Members
Public Types inherited from ns3::TestSuite
enum Type {
ALL = 0, UNIT, SYSTEM, EXAMPLE,
PERFORMANCE
}
Type of test.
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
PacketBb TestSuite.
Definition at line 123 of file packetbb-test-suite.cc.
Constructor & Destructor Documentation
PbbTestSuite()
PbbTestSuite::PbbTestSuite ()
Definition at line 129 of file packetbb-test-suite.cc.
References ns3::PbbMessage::AddressBlockPushBack(), ns3::PbbAddressBlock::AddressPushBack(), ns3::TestCase::AddTestCase(), MRG32k3a::m1, MRG32k3a::m2, ns3::PbbPacket::MessagePushBack(), ns3::PbbAddressBlock::PrefixPushBack(), ns3::PbbMessage::SetHopCount(), ns3::PbbMessage::SetHopLimit(), ns3::PbbAddressTlv::SetIndexStart(), ns3::PbbAddressTlv::SetIndexStop(), ns3::PbbAddressTlv::SetMultivalue(), ns3::PbbMessage::SetOriginatorAddress(), ns3::PbbPacket::SetSequenceNumber(), ns3::PbbMessage::SetSequenceNumber(), ns3::PbbMessage::SetType(), ns3::PbbTlv::SetType(), ns3::PbbTlv::SetTypeExt(), ns3::PbbTlv::SetValue(), ns3::PbbAddressBlock::TlvPushBack(), ns3::PbbPacket::TlvPushBack(), and ns3::PbbMessage::TlvPushBack().
The documentation for this class was generated from the following file:
src/network/test/packetbb-test-suite.cc