ns-3: ns3::PortRangeTlvValue Class Reference
ns3::PortRangeTlvValue Class Reference
WiMAX Models
PortRangeTlvValue class.
#include "wimax-tlv.h"
Classes
struct PortRange
PortRange structure.
Public Types
typedef std::vector< struct PortRange >::const_iterator Iterator
PortRange vector iterator typedef.
Public Member Functions
PortRangeTlvValue ()
~PortRangeTlvValue ()
void Add (uint16_t portLow, uint16_t portHigh)
Add a range.
Iterator Begin () const
Begin iterator.
virtual PortRangeTlvValue * Copy (void) const
Copy.
virtual uint32_t Deserialize (Buffer::Iterator start, uint64_t valueLength)
Deserialize from a buffer.
Iterator End () const
End iterator.
virtual uint32_t GetSerializedSize (void) const
Get serialized size in bytes.
virtual void Serialize (Buffer::Iterator start) const
Serialize to a buffer.
Public Member Functions inherited from ns3::TlvValue
virtual ~TlvValue ()
Private Attributes
std::vector< struct PortRange > * m_portRange
port range
Detailed Description
PortRangeTlvValue class.
Definition at line 470 of file wimax-tlv.h.
Member Typedef Documentation
Iterator
typedef std::vector<struct PortRange>::const_iterator ns3::PortRangeTlvValue::Iterator
PortRange vector iterator typedef.
Definition at line 480 of file wimax-tlv.h.
Constructor & Destructor Documentation
PortRangeTlvValue()
ns3::PortRangeTlvValue::PortRangeTlvValue ()
Definition at line 880 of file wimax-tlv.cc.
References m_portRange.
Referenced by Copy().
~PortRangeTlvValue()
ns3::PortRangeTlvValue::~PortRangeTlvValue ()
Definition at line 884 of file wimax-tlv.cc.
References m_portRange.
Member Function Documentation
Add()
void ns3::PortRangeTlvValue::Add (uint16_t portLow, uint16_t portHigh)
Add a range.
Parameters
portLow the low port of the range
portHigh the high port of the range
Definition at line 918 of file wimax-tlv.cc.
References m_portRange, ns3::PortRangeTlvValue::PortRange::PortHigh, and ns3::PortRangeTlvValue::PortRange::PortLow.
Referenced by Copy(), Deserialize(), and ns3::IpcsClassifierRecord::ToTlv().
Begin()
PortRangeTlvValue::Iterator ns3::PortRangeTlvValue::Begin () const
Begin iterator.
Returns
the beginning element
Definition at line 926 of file wimax-tlv.cc.
References m_portRange.
Copy()
PortRangeTlvValue * ns3::PortRangeTlvValue::Copy (void) const virtual
Copy.
Returns
the port range tlv value
Implements ns3::TlvValue.
Definition at line 938 of file wimax-tlv.cc.
References PortRangeTlvValue(), Add(), and m_portRange.
Deserialize()
uint32_t ns3::PortRangeTlvValue::Deserialize (Buffer::Iterator start, uint64_t valueLen) virtual
Deserialize from a buffer.
Parameters
start the iterator
valueLen the maximum length of the value
Returns
the
Implements ns3::TlvValue.
Definition at line 905 of file wimax-tlv.cc.
References Add(), and ns3::Buffer::Iterator::ReadNtohU16().
Referenced by ns3::ClassificationRuleVectorTlvValue::Deserialize().
End()
PortRangeTlvValue::Iterator ns3::PortRangeTlvValue::End () const
End iterator.
Returns
the ending element
Definition at line 932 of file wimax-tlv.cc.
References m_portRange.
GetSerializedSize()
uint32_t ns3::PortRangeTlvValue::GetSerializedSize (void) const virtual
Get serialized size in bytes.
Returns
the serialized size
Implements ns3::TlvValue.
Definition at line 891 of file wimax-tlv.cc.
References m_portRange.
Referenced by ns3::ClassificationRuleVectorTlvValue::Deserialize(), and ns3::IpcsClassifierRecord::ToTlv().
Serialize()
void ns3::PortRangeTlvValue::Serialize (Buffer::Iterator start) const virtual
Serialize to a buffer.
Parameters
start the iterator
Implements ns3::TlvValue.
Definition at line 896 of file wimax-tlv.cc.
References m_portRange, and ns3::Buffer::Iterator::WriteHtonU16().
Member Data Documentation
m_portRange
std::vector<struct PortRange>* ns3::PortRangeTlvValue::m_portRange private
port range
Definition at line 508 of file wimax-tlv.h.
Referenced by PortRangeTlvValue(), ~PortRangeTlvValue(), Add(), Begin(), Copy(), End(), GetSerializedSize(), and Serialize().
The documentation for this class was generated from the following files:
src/wimax/model/wimax-tlv.h
src/wimax/model/wimax-tlv.cc