ns-3: TvSpectrumTransmitterTestCase Class Reference
TvSpectrumTransmitterTestCase Class Reference
Public Member Functions
TvSpectrumTransmitterTestCase (double startFrequency, double channelBandwidth, double basePsd, TvSpectrumTransmitter::TvType tvType)
virtual ~TvSpectrumTransmitterTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Static Private Member Functions
static std::string Name (TvSpectrumTransmitter::TvType tvType, double startFrequency, double channelBandwidth, double basePsd)
Private Attributes
double m_basePsd
double m_channelBandwidth
double m_startFrequency
TvSpectrumTransmitter::TvType m_tvType
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 44 of file tv-spectrum-transmitter-test.cc.
Constructor & Destructor Documentation
TvSpectrumTransmitterTestCase()
TvSpectrumTransmitterTestCase::TvSpectrumTransmitterTestCase (double startFrequency, double channelBandwidth, double basePsd, TvSpectrumTransmitter::TvType tvType)
Definition at line 81 of file tv-spectrum-transmitter-test.cc.
~TvSpectrumTransmitterTestCase()
TvSpectrumTransmitterTestCase::~TvSpectrumTransmitterTestCase () virtual
Definition at line 93 of file tv-spectrum-transmitter-test.cc.
Member Function Documentation
DoRun()
void TvSpectrumTransmitterTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 98 of file tv-spectrum-transmitter-test.cc.
References ns3::SpectrumValue::ConstBandsBegin(), ns3::SpectrumValue::ConstBandsEnd(), ns3::SpectrumValue::ConstValuesBegin(), ns3::SpectrumValue::ConstValuesEnd(), epsilon, m_basePsd, m_channelBandwidth, m_startFrequency, m_tvType, max, NS_LOG_FUNCTION, NS_TEST_ASSERT_MSG_EQ_TOL, third::phy, and TOLERANCE.
Name()
std::string TvSpectrumTransmitterTestCase::Name (TvSpectrumTransmitter::TvType tvType, double startFrequency, double channelBandwidth, double basePsd) static private
Definition at line 68 of file tv-spectrum-transmitter-test.cc.
Member Data Documentation
m_basePsd
double TvSpectrumTransmitterTestCase::m_basePsd private
Definition at line 62 of file tv-spectrum-transmitter-test.cc.
Referenced by DoRun().
m_channelBandwidth
double TvSpectrumTransmitterTestCase::m_channelBandwidth private
Definition at line 61 of file tv-spectrum-transmitter-test.cc.
Referenced by DoRun().
m_startFrequency
double TvSpectrumTransmitterTestCase::m_startFrequency private
Definition at line 60 of file tv-spectrum-transmitter-test.cc.
Referenced by DoRun().
m_tvType
TvSpectrumTransmitter::TvType TvSpectrumTransmitterTestCase::m_tvType private
Definition at line 63 of file tv-spectrum-transmitter-test.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/spectrum/test/tv-spectrum-transmitter-test.cc