ns-3: ns3::TcpOption Class Reference
ns3::TcpOption Class Reference abstract
Internet » TCP
#include "tcp-option.h"
Public Types
enum Kind {
END = 0, NOP = 1, MSS = 2, WINSCALE = 3,
SACKPERMITTED = 4, SACK = 5, TS = 8, UNKNOWN = 255
}
The option Kind, as defined in the respective RFCs.
Public Member Functions
TcpOption ()
virtual ~TcpOption ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the Option from a buffer iterator.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint8_t GetKind (void) const =0
Get the ‘kind’ (as in RFC 793) of this option.
virtual uint32_t GetSerializedSize (void) const =0
Returns number of bytes required for Option serialization.
virtual void Print (std::ostream &os) const =0
Print the Option contents.
virtual void Serialize (Buffer::Iterator start) const =0
Serialize the Option to a buffer iterator.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static Ptr< TcpOption > CreateOption (uint8_t kind)
Creates an option.
static TypeId GetTypeId (void)
Get the type ID.
static bool IsKindKnown (uint8_t kind)
Check if the option is implemented.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Base class for all kinds of TCP options
Definition at line 36 of file tcp-option.h.
Member Enumeration Documentation
Kind
enum ns3::TcpOption::Kind
The option Kind, as defined in the respective RFCs.
Enumerator
END
END.
NOP
NOP.
MSS
MSS.
WINSCALE
WINSCALE.
SACKPERMITTED
SACKPERMITTED.
SACK
SACK.
TS
TS.
UNKNOWN
not a standardized value; for unknown recv'd options
Definition at line 53 of file tcp-option.h.
Constructor & Destructor Documentation
TcpOption()
ns3::TcpOption::TcpOption ()
Definition at line 40 of file tcp-option.cc.
~TcpOption()
ns3::TcpOption::~TcpOption () virtual
Definition at line 44 of file tcp-option.cc.
Member Function Documentation
CreateOption()
Ptr< TcpOption > ns3::TcpOption::CreateOption (uint8_t kind) static
Creates an option.
Parameters
kind the option kind
Returns
the requested option or an ns3::UnknownOption if the option is not supported
Definition at line 65 of file tcp-option.cc.
References ns3::ObjectFactory::Create(), END, ns3::TcpOptionEnd::GetTypeId(), ns3::TcpOptionNOP::GetTypeId(), ns3::TcpOptionMSS::GetTypeId(), ns3::TcpOptionSackPermitted::GetTypeId(), ns3::TcpOptionSack::GetTypeId(), ns3::TcpOptionTS::GetTypeId(), ns3::TcpOptionWinScale::GetTypeId(), ns3::TcpOptionUnknown::GetTypeId(), MSS, NOP, SACK, SACKPERMITTED, ns3::ObjectFactory::SetTypeId(), TS, UNKNOWN, and WINSCALE.
Referenced by ns3::TcpHeader::Deserialize().
Deserialize()
virtual uint32_t ns3::TcpOption::Deserialize (Buffer::Iterator start) pure virtual
Deserialize the Option from a buffer iterator.
Parameters
start the buffer iterator
Returns
the number of deserialized bytes
Implemented in ns3::TcpOptionUnknown, ns3::TcpOptionWinScale, ns3::TcpOptionTS, ns3::TcpOptionSack, ns3::TcpOptionSackPermitted, ns3::TcpOptionMSS, ns3::TcpOptionNOP, and ns3::TcpOptionEnd.
GetInstanceTypeId()
TypeId ns3::TcpOption::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Reimplemented from ns3::Object.
Reimplemented in ns3::TcpOptionUnknown, ns3::TcpOptionWinScale, ns3::TcpOptionTS, ns3::TcpOptionSack, ns3::TcpOptionSackPermitted, ns3::TcpOptionMSS, ns3::TcpOptionNOP, and ns3::TcpOptionEnd.
Definition at line 59 of file tcp-option.cc.
References GetTypeId().
GetKind()
virtual uint8_t ns3::TcpOption::GetKind (void) const pure virtual
Get the ‘kind’ (as in RFC 793) of this option.
Returns
the Option Kind
Implemented in ns3::TcpOptionUnknown, ns3::TcpOptionWinScale, ns3::TcpOptionTS, ns3::TcpOptionSack, ns3::TcpOptionSackPermitted, ns3::TcpOptionMSS, ns3::TcpOptionNOP, and ns3::TcpOptionEnd.
Referenced by ns3::TcpHeader::AppendOption(), and ns3::TcpSocketBase::ReadOptions().
GetSerializedSize()
virtual uint32_t ns3::TcpOption::GetSerializedSize (void) const pure virtual
Returns number of bytes required for Option serialization.
Returns
number of bytes required for Option serialization
Implemented in ns3::TcpOptionUnknown, ns3::TcpOptionWinScale, ns3::TcpOptionTS, ns3::TcpOptionSack, ns3::TcpOptionSackPermitted, ns3::TcpOptionMSS, ns3::TcpOptionNOP, and ns3::TcpOptionEnd.
Referenced by ns3::TcpHeader::AppendOption().
GetTypeId()
TypeId ns3::TcpOption::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 49 of file tcp-option.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
IsKindKnown()
bool ns3::TcpOption::IsKindKnown (uint8_t kind) static
Check if the option is implemented.
Parameters
kind the Option kind
Returns
true if the option is known
Definition at line 99 of file tcp-option.cc.
References END, MSS, NOP, SACK, SACKPERMITTED, TS, and WINSCALE.
Referenced by ns3::TcpHeader::AppendOption(), and ns3::TcpHeader::Deserialize().
Print()
virtual void ns3::TcpOption::Print (std::ostream & os) const pure virtual
Print the Option contents.
Parameters
os the output stream
Implemented in ns3::TcpOptionUnknown, ns3::TcpOptionWinScale, ns3::TcpOptionTS, ns3::TcpOptionSack, ns3::TcpOptionSackPermitted, ns3::TcpOptionMSS, ns3::TcpOptionNOP, and ns3::TcpOptionEnd.
Serialize()
virtual void ns3::TcpOption::Serialize (Buffer::Iterator start) const pure virtual
Serialize the Option to a buffer iterator.
Parameters
start the buffer iterator
Implemented in ns3::TcpOptionUnknown, ns3::TcpOptionWinScale, ns3::TcpOptionTS, ns3::TcpOptionSack, ns3::TcpOptionSackPermitted, ns3::TcpOptionMSS, ns3::TcpOptionNOP, and ns3::TcpOptionEnd.
The documentation for this class was generated from the following files:
src/internet/model/tcp-option.h
src/internet/model/tcp-option.cc