ns-3: ns3::RlcTag Class Reference
ns3::RlcTag Class Reference
Tag to calculate the per-PDU delay from eNb RLC to UE RLC.
#include "lte-rlc-tag.h"
Public Member Functions
RlcTag ()
Create an empty RLC tag.
RlcTag (Time senderTimestamp)
Create an RLC tag with the given senderTimestamp.
virtual void Deserialize (TagBuffer i)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
Time GetSenderTimestamp (void) const
Get the instant when the RLC delivers the PDU to the MAC SAP provider.
virtual uint32_t GetSerializedSize () const
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer i) const
void SetSenderTimestamp (Time senderTimestamp)
Set the sender timestamp.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Time m_senderTimestamp
sender timestamp
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Tag to calculate the per-PDU delay from eNb RLC to UE RLC.
Definition at line 36 of file lte-rlc-tag.h.
Constructor & Destructor Documentation
RlcTag() [1/2]
ns3::RlcTag::RlcTag ()
Create an empty RLC tag.
Definition at line 29 of file lte-rlc-tag.cc.
RlcTag() [2/2]
ns3::RlcTag::RlcTag (Time senderTimestamp)
Create an RLC tag with the given senderTimestamp.
Parameters
senderTimestamp the time
Definition at line 36 of file lte-rlc-tag.cc.
Member Function Documentation
Deserialize()
void ns3::RlcTag::Deserialize (TagBuffer i) virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 73 of file lte-rlc-tag.cc.
References m_senderTimestamp, ns3::NanoSeconds(), and ns3::TagBuffer::Read().
GetInstanceTypeId()
TypeId ns3::RlcTag::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 54 of file lte-rlc-tag.cc.
References GetTypeId().
GetSenderTimestamp()
Time ns3::RlcTag::GetSenderTimestamp (void) const inline
Get the instant when the RLC delivers the PDU to the MAC SAP provider.
Returns
the sender timestamp
Definition at line 65 of file lte-rlc-tag.h.
References m_senderTimestamp.
Referenced by ns3::LteRlcAm::DoReceivePdu(), ns3::LteRlcUm::DoReceivePdu(), and ns3::LteRlcSm::DoReceivePdu().
GetSerializedSize()
uint32_t ns3::RlcTag::GetSerializedSize () const virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 60 of file lte-rlc-tag.cc.
GetTypeId()
TypeId ns3::RlcTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 44 of file lte-rlc-tag.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::RlcTag::Print (std::ostream & os) const virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 82 of file lte-rlc-tag.cc.
References m_senderTimestamp.
Serialize()
void ns3::RlcTag::Serialize (TagBuffer i) const virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 66 of file lte-rlc-tag.cc.
References ns3::Time::GetNanoSeconds(), m_senderTimestamp, and ns3::TagBuffer::Write().
SetSenderTimestamp()
void ns3::RlcTag::SetSenderTimestamp (Time senderTimestamp) inline
Set the sender timestamp.
Parameters
senderTimestamp time stamp of the instant when the RLC delivers the PDU to the MAC SAP provider
Definition at line 74 of file lte-rlc-tag.h.
References m_senderTimestamp.
Referenced by ns3::LteRlcAm::DoNotifyTxOpportunity().
Member Data Documentation
m_senderTimestamp
Time ns3::RlcTag::m_senderTimestamp private
sender timestamp
Definition at line 80 of file lte-rlc-tag.h.
Referenced by Deserialize(), GetSenderTimestamp(), Print(), Serialize(), and SetSenderTimestamp().
The documentation for this class was generated from the following files:
src/lte/model/lte-rlc-tag.h
src/lte/model/lte-rlc-tag.cc