ns-3: ns3::LoraInterferenceHelper Class Reference
ns3::LoraInterferenceHelper Class Reference
Helper for LoraPhy that manages interference calculations.
#include "lora-interference-helper.h"
Classes
class Event
A class representing a signal in time.
Public Member Functions
LoraInterferenceHelper ()
virtual ~LoraInterferenceHelper ()
Ptr< LoraInterferenceHelper::Event > Add (Time duration, double rxPower, uint8_t spreadingFactor, Ptr< Packet > packet, double frequencyMHz)
Add an event to the InterferenceHelper.
void CleanOldEvents (void)
Delete old events in this LoraInterferenceHelper.
void ClearAllEvents (void)
Delete all events in the LoraInterferenceHelper.
std::list< Ptr< LoraInterferenceHelper::Event > > GetInterferers ()
Get a list of the interferers currently registered at this InterferenceHelper.
Time GetOverlapTime (Ptr< LoraInterferenceHelper::Event > event1, Ptr< LoraInterferenceHelper::Event > event2)
Compute the time duration in which two given events are overlapping.
uint8_t IsDestroyedByInterference (Ptr< LoraInterferenceHelper::Event > event)
Determine whether the event was destroyed by interference or not.
void PrintEvents (std::ostream &stream)
Print the events that are saved in this helper in a human readable format.
Static Public Member Functions
static TypeId GetTypeId (void)
Private Attributes
std::list< Ptr< LoraInterferenceHelper::Event > > m_events
A list of the events this LoraInterferenceHelper is keeping track of.
Static Private Attributes
static const double collisionSnir [6][6]
The matrix containing information about how packets survive interference.
static Time oldEventThreshold = Seconds (2)
The threshold after which an event is considered old and removed from the list.
Detailed Description
Helper for LoraPhy that manages interference calculations.
This class keeps a list of signals that are impinging on the antenna of the device, in order to compute which ones can be correctly received and which ones are lost due to interference.
Definition at line 42 of file lora-interference-helper.h.
Constructor & Destructor Documentation
LoraInterferenceHelper()
ns3::LoraInterferenceHelper::LoraInterferenceHelper ()
Definition at line 127 of file lora-interference-helper.cc.
References NS_LOG_FUNCTION.
~LoraInterferenceHelper()
ns3::LoraInterferenceHelper::~LoraInterferenceHelper () virtual
Definition at line 132 of file lora-interference-helper.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Add()
Ptr< LoraInterferenceHelper::Event > ns3::LoraInterferenceHelper::Add (Time duration, double rxPower, uint8_t spreadingFactor, Ptr< Packet > packet, double frequencyMHz)
Add an event to the InterferenceHelper.
Parameters
duration the duration of the packet.
rxPower the received power in dBm.
spreadingFactor the spreading factor used by the transmission.
packet The packet carried by this transmission.
frequencyMHz The frequency this event was sent at.
Returns
the newly created event
Definition at line 169 of file lora-interference-helper.cc.
References CleanOldEvents(), ns3::Time::GetSeconds(), m_events, NS_LOG_FUNCTION, and packet.
Referenced by InterferenceTest::DoRun(), ns3::GatewayLoraPhy::Send(), ns3::EndDeviceLoraPhy::StartReceive(), and ns3::GatewayLoraPhy::StartReceive().
CleanOldEvents()
void ns3::LoraInterferenceHelper::CleanOldEvents (void)
Delete old events in this LoraInterferenceHelper.
Definition at line 195 of file lora-interference-helper.cc.
References m_events, ns3::Simulator::Now(), NS_LOG_FUNCTION, and oldEventThreshold.
Referenced by Add().
ClearAllEvents()
void ns3::LoraInterferenceHelper::ClearAllEvents (void)
Delete all events in the LoraInterferenceHelper.
Definition at line 346 of file lora-interference-helper.cc.
References m_events, and NS_LOG_FUNCTION_NOARGS.
Referenced by InterferenceTest::DoRun().
GetInterferers()
std::list< Ptr< LoraInterferenceHelper::Event > > ns3::LoraInterferenceHelper::GetInterferers ()
Get a list of the interferers currently registered at this InterferenceHelper.
Definition at line 211 of file lora-interference-helper.cc.
References m_events.
GetOverlapTime()
Time ns3::LoraInterferenceHelper::GetOverlapTime (Ptr< LoraInterferenceHelper::Event > event1, Ptr< LoraInterferenceHelper::Event > event2)
Compute the time duration in which two given events are overlapping.
Parameters
event1 The first event
event2 The second event
Returns
The overlap time
Definition at line 354 of file lora-interference-helper.cc.
References NS_LOG_FUNCTION_NOARGS, and ns3::Seconds().
Referenced by InterferenceTest::DoRun(), and IsDestroyedByInterference().
GetTypeId()
TypeId ns3::LoraInterferenceHelper::GetTypeId (void) static
Definition at line 118 of file lora-interference-helper.cc.
References ns3::TypeId::SetParent().
IsDestroyedByInterference()
uint8_t ns3::LoraInterferenceHelper::IsDestroyedByInterference (Ptr< LoraInterferenceHelper::Event > event)
Determine whether the event was destroyed by interference or not.
This is the method where the SNIR tables come into play and the computations regarding power are performed.
Parameters
event The event for which to check the outcome.
Returns
The sf of the packets that caused the loss, or 0 if there was no loss.
Definition at line 231 of file lora-interference-helper.cc.
References collisionSnir, GetOverlapTime(), ns3::Time::GetSeconds(), m_events, ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and NS_LOG_INFO.
Referenced by InterferenceTest::DoRun(), ns3::EndDeviceLoraPhy::EndReceive(), and ns3::GatewayLoraPhy::EndReceive().
PrintEvents()
void ns3::LoraInterferenceHelper::PrintEvents (std::ostream & stream)
Print the events that are saved in this helper in a human readable format.
Definition at line 217 of file lora-interference-helper.cc.
References m_events, and NS_LOG_FUNCTION_NOARGS.
Member Data Documentation
collisionSnir
const double ns3::LoraInterferenceHelper::collisionSnir static private
Initial value:
=
{
  {  6, -16, -18, -19, -19, -20},
  {-24,   6, -20, -22, -22, -22},
  {-27, -27,   6, -23, -25, -25},
  {-30, -30, -30,   6, -26, -28},
  {-33, -33, -33, -33,   6, -29},
  {-36, -36, -36, -36, -36,   6}
}
The matrix containing information about how packets survive interference.
Definition at line 209 of file lora-interference-helper.h.
Referenced by IsDestroyedByInterference().
m_events
std::list< Ptr< LoraInterferenceHelper::Event > > ns3::LoraInterferenceHelper::m_events private
A list of the events this LoraInterferenceHelper is keeping track of.
Definition at line 204 of file lora-interference-helper.h.
Referenced by Add(), CleanOldEvents(), ClearAllEvents(), GetInterferers(), IsDestroyedByInterference(), and PrintEvents().
oldEventThreshold
Time ns3::LoraInterferenceHelper::oldEventThreshold = Seconds (2) static private
The threshold after which an event is considered old and removed from the list.
Definition at line 215 of file lora-interference-helper.h.
Referenced by CleanOldEvents().
The documentation for this class was generated from the following files:
src/lorawan/model/lora-interference-helper.h
src/lorawan/model/lora-interference-helper.cc