ns-3: ns3::EmuEpcHelper Class Reference
ns3::EmuEpcHelper Class Reference
LTE Models
Create an EPC network using EmuFdNetDevice.
#include "emu-epc-helper.h"
Public Member Functions
EmuEpcHelper ()
Constructor.
virtual ~EmuEpcHelper ()
Destructor.
virtual void AddEnb (Ptr< Node > enbNode, Ptr< NetDevice > lteEnbNetDevice, uint16_t cellId)
Add an eNB to the EPC.
virtual void AddX2Interface (Ptr< Node > enbNode1, Ptr< Node > enbNode2)
Add an X2 interface between two eNB.
virtual void DoDispose ()
Destructor implementation.
TypeId GetInstanceTypeId () const
Get the most derived TypeId for this Object.
Public Member Functions inherited from ns3::NoBackhaulEpcHelper
NoBackhaulEpcHelper ()
Constructor.
virtual ~NoBackhaulEpcHelper ()
Destructor.
virtual uint8_t ActivateEpsBearer (Ptr< NetDevice > ueLteDevice, uint64_t imsi, Ptr< EpcTft > tft, EpsBearer bearer)
Activate an EPS bearer, setting up the corresponding S1-U tunnel.
virtual void AddS1Interface (Ptr< Node > enb, Ipv4Address enbAddress, Ipv4Address sgwAddress, uint16_t cellId=0)
Add an S1 interface between an eNB and a SGW.
virtual void AddUe (Ptr< NetDevice > ueLteDevice, uint64_t imsi)
Notify the EPC of the existence of a new UE which might attach at a later time.
virtual Ipv4InterfaceContainer AssignUeIpv4Address (NetDeviceContainer ueDevices)
Assign IPv4 addresses to UE devices.
virtual Ipv6InterfaceContainer AssignUeIpv6Address (NetDeviceContainer ueDevices)
Assign IPv6 addresses to UE devices.
TypeId GetInstanceTypeId () const
Get the most derived TypeId for this Object.
virtual Ptr< Node > GetPgwNode () const
Get the PGW node.
virtual Ptr< Node > GetSgwNode () const
Get the SGW node.
virtual Ipv4Address GetUeDefaultGatewayAddress ()
virtual Ipv6Address GetUeDefaultGatewayAddress6 ()
Public Member Functions inherited from ns3::EpcHelper
EpcHelper ()
Constructor.
virtual ~EpcHelper ()
Destructor.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::NoBackhaulEpcHelper
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::EpcHelper
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
std::string m_enbDeviceName
The name of the device used for the S1-U interface of the eNB.
std::string m_enbMacAddressBase
First 5 bytes of the Enb MAC address base.
Ipv4AddressHelper m_epcIpv4AddressHelper
helper to assign addresses to S1-U NetDevices
std::string m_sgwDeviceName
The name of the device used for the S1-U interface of the SGW.
Ipv4InterfaceContainer m_sgwIpIfaces
Container for Ipv4Interfaces of the SGW.
std::string m_sgwMacAddress
MAC address used for the SGW.
Additional Inherited Members
Protected Member Functions inherited from ns3::NoBackhaulEpcHelper
virtual void DoActivateEpsBearerForUe (const Ptr< NetDevice > &ueDevice, const Ptr< EpcTft > &tft, const EpsBearer &bearer) const
DoActivateEpsBearerForUe: Schedule ActivateEpsBearer on the UE.
virtual void DoAddX2Interface (const Ptr< EpcX2 > &enb1X2, const Ptr< NetDevice > &enb1LteDev, const Ipv4Address &enb1X2Address, const Ptr< EpcX2 > &enb2X2, const Ptr< NetDevice > &enb2LteDev, const Ipv4Address &enb2X2Address) const
DoAddX2Interface: Call AddX2Interface on top of the Enb device pointers.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Create an EPC network using EmuFdNetDevice.
This Helper will create an EPC network topology comprising of a single node that implements both the SGW and PGW functionality, and an MME node. The S1-U, X2-U and X2-C interfaces are realized using EmuFdNetDevice; in particular, one device is used to send all the traffic related to these interfaces.
Definition at line 41 of file emu-epc-helper.h.
Constructor & Destructor Documentation
EmuEpcHelper()
ns3::EmuEpcHelper::EmuEpcHelper ()
Constructor.
Definition at line 40 of file emu-epc-helper.cc.
References ns3::Ipv4AddressHelper::Assign(), ns3::ObjectBase::ConstructSelf(), ns3::NetDeviceContainer::Get(), ns3::NoBackhaulEpcHelper::GetSgwNode(), ns3::FdNetDeviceHelper::Install(), m_epcIpv4AddressHelper, m_sgwDeviceName, m_sgwIpIfaces, m_sgwMacAddress, NS_LOG_FUNCTION, NS_LOG_LOGIC(), ns3::Ipv4AddressHelper::SetBase(), and ns3::EmuFdNetDeviceHelper::SetDeviceName().
~EmuEpcHelper()
ns3::EmuEpcHelper::~EmuEpcHelper () virtual
Destructor.
Definition at line 66 of file emu-epc-helper.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddEnb()
void ns3::EmuEpcHelper::AddEnb (Ptr< Node > enbNode, Ptr< NetDevice > lteEnbNetDevice, uint16_t cellId) virtual
Add an eNB to the EPC.
Parameters
enbNode the previously created eNB node which is to be added to the EPC
lteEnbNetDevice the LteEnbNetDevice of the eNB node
cellId ID of the eNB
Reimplemented from ns3::NoBackhaulEpcHelper.
Definition at line 117 of file emu-epc-helper.cc.
References ns3::NoBackhaulEpcHelper::AddEnb(), ns3::NoBackhaulEpcHelper::AddS1Interface(), ns3::Ipv4AddressHelper::Assign(), ns3::NetDeviceContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::Ipv4::GetNInterfaces(), ns3::Object::GetObject(), ns3::FdNetDeviceHelper::Install(), m_enbDeviceName, m_enbMacAddressBase, m_epcIpv4AddressHelper, m_sgwIpIfaces, NS_ABORT_IF, NS_LOG_FUNCTION, NS_LOG_LOGIC(), and ns3::EmuFdNetDeviceHelper::SetDeviceName().
AddX2Interface()
void ns3::EmuEpcHelper::AddX2Interface (Ptr< Node > enbNode1, Ptr< Node > enbNode2) virtual
Add an X2 interface between two eNB.
Parameters
enbNode1 one eNB peer of the X2 interface
enbNode2 the other eNB peer of the X2 interface
Reimplemented from ns3::NoBackhaulEpcHelper.
Definition at line 151 of file emu-epc-helper.cc.
References ns3::LteEnbNetDevice::GetCellId(), ns3::Node::GetDevice(), ns3::Node::GetNDevices(), ns3::Object::GetObject(), NS_ASSERT, NS_LOG_FUNCTION, NS_LOG_LOGIC(), and NS_LOG_WARN.
DoDispose()
void ns3::EmuEpcHelper::DoDispose () virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::NoBackhaulEpcHelper.
Definition at line 109 of file emu-epc-helper.cc.
References ns3::NoBackhaulEpcHelper::DoDispose(), and NS_LOG_FUNCTION.
GetInstanceTypeId()
TypeId ns3::EmuEpcHelper::GetInstanceTypeId () const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Reimplemented from ns3::Object.
Definition at line 103 of file emu-epc-helper.cc.
References GetTypeId().
GetTypeId()
TypeId ns3::EmuEpcHelper::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 72 of file emu-epc-helper.cc.
References m_enbDeviceName, m_enbMacAddressBase, m_sgwDeviceName, m_sgwMacAddress, ns3::MakeStringAccessor(), ns3::MakeStringChecker(), and ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Member Data Documentation
m_enbDeviceName
std::string ns3::EmuEpcHelper::m_enbDeviceName private
The name of the device used for the S1-U interface of the eNB.
Definition at line 87 of file emu-epc-helper.h.
Referenced by AddEnb(), and GetTypeId().
m_enbMacAddressBase
std::string ns3::EmuEpcHelper::m_enbMacAddressBase private
First 5 bytes of the Enb MAC address base.
Definition at line 97 of file emu-epc-helper.h.
Referenced by AddEnb(), and GetTypeId().
m_epcIpv4AddressHelper
Ipv4AddressHelper ns3::EmuEpcHelper::m_epcIpv4AddressHelper private
helper to assign addresses to S1-U NetDevices
Definition at line 72 of file emu-epc-helper.h.
Referenced by EmuEpcHelper(), and AddEnb().
m_sgwDeviceName
std::string ns3::EmuEpcHelper::m_sgwDeviceName private
The name of the device used for the S1-U interface of the SGW.
Definition at line 82 of file emu-epc-helper.h.
Referenced by EmuEpcHelper(), and GetTypeId().
m_sgwIpIfaces
Ipv4InterfaceContainer ns3::EmuEpcHelper::m_sgwIpIfaces private
Container for Ipv4Interfaces of the SGW.
Definition at line 77 of file emu-epc-helper.h.
Referenced by EmuEpcHelper(), and AddEnb().
m_sgwMacAddress
std::string ns3::EmuEpcHelper::m_sgwMacAddress private
MAC address used for the SGW.
Definition at line 92 of file emu-epc-helper.h.
Referenced by EmuEpcHelper(), and GetTypeId().
The documentation for this class was generated from the following files:
src/lte/helper/emu-epc-helper.h
src/lte/helper/emu-epc-helper.cc