ns-3: ns3::FfMacCschedSapUser Class Reference
ns3::FfMacCschedSapUser Class Reference abstract
FfMacCschedSapUser class.
#include "ff-mac-csched-sap.h"
Classes
struct CschedCellConfigCnfParameters
Parameters of the API primitives.
struct CschedCellConfigUpdateIndParameters
Parameters of the CSCHED_CELL_CONFIG_UPDATE_IND primitive.
struct CschedLcConfigCnfParameters
Parameters of the CSCHED_LC_CONFIG_CNF primitive.
struct CschedLcReleaseCnfParameters
Parameters of the CSCHED_LC_RELEASE_CNF primitive.
struct CschedUeConfigCnfParameters
Parameters of the CSCHED_UE_CONFIG_CNF primitive.
struct CschedUeConfigUpdateIndParameters
Parameters of the CSCHED_UE_CONFIG_UPDATE_IND primitive.
struct CschedUeReleaseCnfParameters
Parameters of the CSCHED_UE_RELEASE_CNF primitive.
Public Member Functions
virtual ~FfMacCschedSapUser ()
virtual void CschedCellConfigCnf (const struct CschedCellConfigCnfParameters &params)=0
CSCHED_CELL_CONFIG_CNF.
virtual void CschedCellConfigUpdateInd (const struct CschedCellConfigUpdateIndParameters &params)=0
CSCHED_UE_CONFIG_IND.
virtual void CschedLcConfigCnf (const struct CschedLcConfigCnfParameters &params)=0
CSCHED_LC_CONFIG_CNF.
virtual void CschedLcReleaseCnf (const struct CschedLcReleaseCnfParameters &params)=0
CSCHED_LC_RELEASE_CNF.
virtual void CschedUeConfigCnf (const struct CschedUeConfigCnfParameters &params)=0
CSCHED_UE_CONFIG_CNF.
virtual void CschedUeConfigUpdateInd (const struct CschedUeConfigUpdateIndParameters &params)=0
CSCHED_UE_UPDATE_IND.
virtual void CschedUeReleaseCnf (const struct CschedUeReleaseCnfParameters &params)=0
CSCHED_UE_RELEASE_CNF.
Detailed Description
FfMacCschedSapUser class.
Definition at line 283 of file ff-mac-csched-sap.h.
Constructor & Destructor Documentation
~FfMacCschedSapUser()
ns3::FfMacCschedSapUser::~FfMacCschedSapUser () virtual
Definition at line 29 of file ff-mac-csched-sap.cc.
Member Function Documentation
CschedCellConfigCnf()
virtual void ns3::FfMacCschedSapUser::CschedCellConfigCnf (const struct CschedCellConfigCnfParameters & params) pure virtual
CSCHED_CELL_CONFIG_CNF.
Parameters
params CschedCellConfigCnfParameters
Implemented in ns3::EnbMacMemberFfMacCschedSapUser.
CschedCellConfigUpdateInd()
virtual void ns3::FfMacCschedSapUser::CschedCellConfigUpdateInd (const struct CschedCellConfigUpdateIndParameters & params) pure virtual
CSCHED_UE_CONFIG_IND.
Parameters
params CschedCellConfigUpdateIndParameters
Implemented in ns3::EnbMacMemberFfMacCschedSapUser.
CschedLcConfigCnf()
virtual void ns3::FfMacCschedSapUser::CschedLcConfigCnf (const struct CschedLcConfigCnfParameters & params) pure virtual
CSCHED_LC_CONFIG_CNF.
Parameters
params CschedLcConfigCnfParameters
Implemented in ns3::EnbMacMemberFfMacCschedSapUser.
CschedLcReleaseCnf()
virtual void ns3::FfMacCschedSapUser::CschedLcReleaseCnf (const struct CschedLcReleaseCnfParameters & params) pure virtual
CSCHED_LC_RELEASE_CNF.
Parameters
params CschedLcReleaseCnfParameters
Implemented in ns3::EnbMacMemberFfMacCschedSapUser.
CschedUeConfigCnf()
virtual void ns3::FfMacCschedSapUser::CschedUeConfigCnf (const struct CschedUeConfigCnfParameters & params) pure virtual
CSCHED_UE_CONFIG_CNF.
Parameters
params CschedUeConfigCnfParameters
Implemented in ns3::EnbMacMemberFfMacCschedSapUser.
Referenced by ns3::CqaFfMacScheduler::DoCschedCellConfigReq(), ns3::FdBetFfMacScheduler::DoCschedCellConfigReq(), ns3::FdMtFfMacScheduler::DoCschedCellConfigReq(), ns3::FdTbfqFfMacScheduler::DoCschedCellConfigReq(), ns3::PfFfMacScheduler::DoCschedCellConfigReq(), ns3::PssFfMacScheduler::DoCschedCellConfigReq(), ns3::RrFfMacScheduler::DoCschedCellConfigReq(), ns3::TdBetFfMacScheduler::DoCschedCellConfigReq(), ns3::TdMtFfMacScheduler::DoCschedCellConfigReq(), ns3::TdTbfqFfMacScheduler::DoCschedCellConfigReq(), and ns3::TtaFfMacScheduler::DoCschedCellConfigReq().
CschedUeConfigUpdateInd()
virtual void ns3::FfMacCschedSapUser::CschedUeConfigUpdateInd (const struct CschedUeConfigUpdateIndParameters & params) pure virtual
CSCHED_UE_UPDATE_IND.
Parameters
params CschedUeConfigUpdateIndParameters
Implemented in ns3::EnbMacMemberFfMacCschedSapUser.
Referenced by ns3::CqaFfMacScheduler::TransmissionModeConfigurationUpdate(), ns3::FdBetFfMacScheduler::TransmissionModeConfigurationUpdate(), ns3::FdMtFfMacScheduler::TransmissionModeConfigurationUpdate(), ns3::FdTbfqFfMacScheduler::TransmissionModeConfigurationUpdate(), ns3::PfFfMacScheduler::TransmissionModeConfigurationUpdate(), ns3::PssFfMacScheduler::TransmissionModeConfigurationUpdate(), ns3::RrFfMacScheduler::TransmissionModeConfigurationUpdate(), ns3::TdBetFfMacScheduler::TransmissionModeConfigurationUpdate(), ns3::TdMtFfMacScheduler::TransmissionModeConfigurationUpdate(), ns3::TdTbfqFfMacScheduler::TransmissionModeConfigurationUpdate(), and ns3::TtaFfMacScheduler::TransmissionModeConfigurationUpdate().
CschedUeReleaseCnf()
virtual void ns3::FfMacCschedSapUser::CschedUeReleaseCnf (const struct CschedUeReleaseCnfParameters & params) pure virtual
CSCHED_UE_RELEASE_CNF.
Parameters
params CschedUeReleaseCnfParameters
Implemented in ns3::EnbMacMemberFfMacCschedSapUser.
The documentation for this class was generated from the following files:
src/lte/model/ff-mac-csched-sap.h
src/lte/model/ff-mac-csched-sap.cc