ns-3: ns3::GrantManagementSubheader Class Reference
ns3::GrantManagementSubheader Class Reference
WiMAX Models
#include "wimax-mac-header.h"
Public Member Functions
GrantManagementSubheader (void)
~GrantManagementSubheader (void)
uint32_t Deserialize (Buffer::Iterator start)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
std::string GetName (void) const
Get name field.
uint16_t GetPbr (void) const
Get PBR field.
uint8_t GetPm (void) const
Get PM field.
uint32_t GetSerializedSize (void) const
uint8_t GetSi (void) const
Get SI field.
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetPbr (uint16_t pbr)
Set PRR field.
void SetPm (uint8_t pm)
Set PM field.
void SetSi (uint8_t si)
Set SI field.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint16_t m_pbr
PiggyBack Request.
uint8_t m_pm
Poll-Me bit (byte in this case)
uint8_t m_si
Slip Indicator.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class implements the grant management sub-header as described by IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems 6.3.2.2.2 Grant Management subheader, page 40
Definition at line 376 of file wimax-mac-header.h.
Constructor & Destructor Documentation
GrantManagementSubheader()
ns3::GrantManagementSubheader::GrantManagementSubheader (void)
Definition at line 494 of file wimax-mac-header.cc.
~GrantManagementSubheader()
ns3::GrantManagementSubheader::~GrantManagementSubheader (void)
Definition at line 501 of file wimax-mac-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::GrantManagementSubheader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 574 of file wimax-mac-header.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_pbr, m_pm, m_si, ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetInstanceTypeId()
TypeId ns3::GrantManagementSubheader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 550 of file wimax-mac-header.cc.
References GetTypeId().
GetName()
std::string ns3::GrantManagementSubheader::GetName (void) const
Get name field.
Returns
the name
Definition at line 535 of file wimax-mac-header.cc.
GetPbr()
uint16_t ns3::GrantManagementSubheader::GetPbr (void) const
Get PBR field.
Returns
the PBR
Definition at line 530 of file wimax-mac-header.cc.
References m_pbr.
GetPm()
uint8_t ns3::GrantManagementSubheader::GetPm (void) const
Get PM field.
Returns
the PM
Definition at line 525 of file wimax-mac-header.cc.
References m_pm.
GetSerializedSize()
uint32_t ns3::GrantManagementSubheader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 561 of file wimax-mac-header.cc.
GetSi()
uint8_t ns3::GrantManagementSubheader::GetSi (void) const
Get SI field.
Returns
the SI
Definition at line 520 of file wimax-mac-header.cc.
References m_si.
GetTypeId()
TypeId ns3::GrantManagementSubheader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 540 of file wimax-mac-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::GrantManagementSubheader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 555 of file wimax-mac-header.cc.
References m_pbr, m_pm, and m_si.
Serialize()
void ns3::GrantManagementSubheader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 566 of file wimax-mac-header.cc.
References m_pbr, m_pm, m_si, visualizer.core::start(), ns3::Buffer::Iterator::WriteU16(), and ns3::Buffer::Iterator::WriteU8().
SetPbr()
void ns3::GrantManagementSubheader::SetPbr (uint16_t pbr)
Set PRR field.
Parameters
pbr the PBR
Definition at line 515 of file wimax-mac-header.cc.
References m_pbr.
SetPm()
void ns3::GrantManagementSubheader::SetPm (uint8_t pm)
Set PM field.
Parameters
pm the PM
Definition at line 510 of file wimax-mac-header.cc.
References m_pm.
Referenced by ns3::SubscriberStationNetDevice::Enqueue().
SetSi()
void ns3::GrantManagementSubheader::SetSi (uint8_t si)
Set SI field.
Parameters
si the SI
Definition at line 505 of file wimax-mac-header.cc.
References m_si.
Member Data Documentation
m_pbr
uint16_t ns3::GrantManagementSubheader::m_pbr private
PiggyBack Request.
Definition at line 435 of file wimax-mac-header.h.
Referenced by Deserialize(), GetPbr(), Print(), Serialize(), and SetPbr().
m_pm
uint8_t ns3::GrantManagementSubheader::m_pm private
Poll-Me bit (byte in this case)
Definition at line 434 of file wimax-mac-header.h.
Referenced by Deserialize(), GetPm(), Print(), Serialize(), and SetPm().
m_si
uint8_t ns3::GrantManagementSubheader::m_si private
Slip Indicator.
Definition at line 433 of file wimax-mac-header.h.
Referenced by Deserialize(), GetSi(), Print(), Serialize(), and SetSi().
The documentation for this class was generated from the following files:
src/wimax/model/wimax-mac-header.h
src/wimax/model/wimax-mac-header.cc