ns-3: ns3::Ipv6RawSocketImpl Class Reference
ns3::Ipv6RawSocketImpl Class Reference
Network » Socket | Internet » IPv6 classes and sub-modules
IPv6 raw socket.
#include "ipv6-raw-socket-impl.h"
Classes
struct Data
IPv6 raw data and additional information.
struct Icmpv6Filter
Struct to hold the ICMPv6 filter.
Public Member Functions
Ipv6RawSocketImpl ()
virtual ~Ipv6RawSocketImpl ()
virtual int Bind ()
Allocate a local IPv4 endpoint for this socket.
virtual int Bind (const Address &address)
Allocate a local endpoint for this socket.
virtual int Bind6 ()
Allocate a local IPv6 endpoint for this socket.
virtual int Close ()
Close a socket.
virtual int Connect (const Address &address)
Initiate a connection to a remote host.
bool ForwardUp (Ptr< const Packet > p, Ipv6Header hdr, Ptr< NetDevice > device)
Forward up to receive method.
virtual bool GetAllowBroadcast () const
Query whether broadcast datagram transmissions are allowed.
virtual enum Socket::SocketErrno GetErrno () const
Get last error number.
virtual Ptr< Node > GetNode () const
Return the node this socket is associated with.
virtual int GetPeerName (Address &address) const
Get the peer address of a connected socket.
virtual uint32_t GetRxAvailable () const
Return number of bytes which can be returned from one or multiple calls to Recv.
virtual enum Socket::SocketType GetSocketType () const
Get socket type (NS3_SOCK_RAW)
virtual int GetSockName (Address &address) const
Get socket address.
virtual uint32_t GetTxAvailable () const
Returns the number of bytes which can be sent in a single call to Send.
void Icmpv6FilterSetBlock (uint8_t type)
Set the filter to block one ICMPv6 type.
void Icmpv6FilterSetBlockAll ()
Set the filter to block all the ICMPv6 types.
void Icmpv6FilterSetPass (uint8_t type)
Set the filter to pass one ICMPv6 type.
void Icmpv6FilterSetPassAll ()
Clean the ICMPv6 filter structure.
bool Icmpv6FilterWillBlock (uint8_t type)
Ask the filter about the status of one ICMPv6 type.
bool Icmpv6FilterWillPass (uint8_t type)
Ask the filter about the status of one ICMPv6 type.
virtual void Ipv6JoinGroup (Ipv6Address address, Socket::Ipv6MulticastFilterMode filterMode, std::vector< Ipv6Address > sourceAddresses)
Joins a IPv6 multicast group.
virtual int Listen ()
Listen for incoming connections.
virtual Ptr< Packet > Recv (uint32_t maxSize, uint32_t flags)
Read data from the socket.
virtual Ptr< Packet > RecvFrom (uint32_t maxSize, uint32_t flags, Address &fromAddress)
Read a single packet from the socket and retrieve the sender address.
virtual int Send (Ptr< Packet > p, uint32_t flags)
Send data (or dummy data) to the remote host.
virtual int SendTo (Ptr< Packet > p, uint32_t flags, const Address &toAddress)
Send data to a specified peer.
virtual bool SetAllowBroadcast (bool allowBroadcast)
Configure whether broadcast datagram transmissions are allowed.
void SetNode (Ptr< Node > node)
Set the node associated with this socket.
void SetProtocol (uint16_t protocol)
Set protocol field.
virtual int ShutdownRecv ()
virtual int ShutdownSend ()
Public Member Functions inherited from ns3::Socket
Socket (void)
virtual ~Socket (void)
virtual void BindToNetDevice (Ptr< NetDevice > netdevice)
Bind a socket to specific device.
Ptr< NetDevice > GetBoundNetDevice ()
Returns socket's bound NetDevice, if any.
uint8_t GetIpTos (void) const
Query the value of IP Type of Service of this socket.
virtual uint8_t GetIpTtl (void) const
Query the value of IP Time to Live field of this socket.
virtual uint8_t GetIpv6HopLimit (void) const
Query the value of IP Hop Limit field of this socket.
uint8_t GetIpv6Tclass (void) const
Query the value of IPv6 Traffic Class field of this socket.
uint8_t GetPriority (void) const
Query the priority value of this socket.
virtual void Ipv6JoinGroup (Ipv6Address address)
Joins a IPv6 multicast group without filters.
virtual void Ipv6LeaveGroup (void)
Leaves IPv6 multicast group this socket is joined to.
bool IsIpRecvTos (void) const
Ask if the socket is currently passing information about IP Type of Service up the stack.
bool IsIpRecvTtl (void) const
Ask if the socket is currently passing information about IP_TTL up the stack.
bool IsIpv6RecvHopLimit (void) const
Ask if the socket is currently passing information about IPv6 Hop Limit up the stack.
bool IsIpv6RecvTclass (void) const
Ask if the socket is currently passing information about IPv6 Traffic Class up the stack.
bool IsRecvPktInfo () const
Get status indicating whether enable/disable packet information to socket.
int Recv (uint8_t *buf, uint32_t size, uint32_t flags)
Recv data (or dummy data) from the remote host.
Ptr< Packet > Recv (void)
Read a single packet from the socket.
Ptr< Packet > RecvFrom (Address &fromAddress)
Read a single packet from the socket and retrieve the sender address.
int RecvFrom (uint8_t *buf, uint32_t size, uint32_t flags, Address &fromAddress)
Read a single packet from the socket and retrieve the sender address.
int Send (const uint8_t *buf, uint32_t size, uint32_t flags)
Send data (or dummy data) to the remote host.
int Send (Ptr< Packet > p)
Send data (or dummy data) to the remote host.
int SendTo (const uint8_t *buf, uint32_t size, uint32_t flags, const Address &address)
Send data to a specified peer.
void SetAcceptCallback (Callback< bool, Ptr< Socket >, const Address & > connectionRequest, Callback< void, Ptr< Socket >, const Address & > newConnectionCreated)
Accept connection requests from remote hosts.
void SetCloseCallbacks (Callback< void, Ptr< Socket > > normalClose, Callback< void, Ptr< Socket > > errorClose)
Detect socket recv() events such as graceful shutdown or error.
void SetConnectCallback (Callback< void, Ptr< Socket > > connectionSucceeded, Callback< void, Ptr< Socket > > connectionFailed)
Specify callbacks to allow the caller to determine if the connection succeeds of fails.
void SetDataSentCallback (Callback< void, Ptr< Socket >, uint32_t > dataSent)
Notify application when a packet has been sent from transport protocol (non-standard socket call)
void SetIpRecvTos (bool ipv4RecvTos)
Tells a socket to pass information about IP Type of Service up the stack.
void SetIpRecvTtl (bool ipv4RecvTtl)
Tells a socket to pass information about IP_TTL up the stack.
void SetIpTos (uint8_t ipTos)
Manually set IP Type of Service field.
virtual void SetIpTtl (uint8_t ipTtl)
Manually set IP Time to Live field.
virtual void SetIpv6HopLimit (uint8_t ipHopLimit)
Manually set IPv6 Hop Limit.
void SetIpv6RecvHopLimit (bool ipv6RecvHopLimit)
Tells a socket to pass information about IPv6 Hop Limit up the stack.
void SetIpv6RecvTclass (bool ipv6RecvTclass)
Tells a socket to pass information about IPv6 Traffic Class up the stack.
void SetIpv6Tclass (int ipTclass)
Manually set IPv6 Traffic Class field.
void SetPriority (uint8_t priority)
Manually set the socket priority.
void SetRecvCallback (Callback< void, Ptr< Socket > >)
Notify application when new data is available to be read.
void SetRecvPktInfo (bool flag)
Enable/Disable receive packet information to socket.
void SetSendCallback (Callback< void, Ptr< Socket >, uint32_t > sendCb)
Notify application when space in transmit buffer is added.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID of this class.
Static Public Member Functions inherited from ns3::Socket
static Ptr< Socket > CreateSocket (Ptr< Node > node, TypeId tid)
This method wraps the creation of sockets that is performed on a given node by a SocketFactory specified by TypeId.
static TypeId GetTypeId (void)
Get the type ID.
static uint8_t IpTos2Priority (uint8_t ipTos)
Return the priority corresponding to a given TOS value.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual void DoDispose ()
Dispose object.
Private Attributes
std::list< Data > m_data
Packet waiting to be processed.
Ipv6Address m_dst
Destination address.
enum Socket::SocketErrno m_err
Last error number.
Icmpv6Filter m_icmpFilter
ICMPv6 filter.
Ptr< Node > m_node
Node.
uint16_t m_protocol
Protocol.
bool m_shutdownRecv
Flag to shutdown receive capability.
bool m_shutdownSend
Flag to shutdown send capability.
Ipv6Address m_src
Source address.
Additional Inherited Members
Public Types inherited from ns3::Socket
enum Ipv6MulticastFilterMode { INCLUDE =1, EXCLUDE }
Enumeration of the possible filter of a socket.
enum SocketErrno {
ERROR_NOTERROR, ERROR_ISCONN, ERROR_NOTCONN, ERROR_MSGSIZE,
ERROR_AGAIN, ERROR_SHUTDOWN, ERROR_OPNOTSUPP, ERROR_AFNOSUPPORT,
ERROR_INVAL, ERROR_BADF, ERROR_NOROUTETOHOST, ERROR_NODEV,
ERROR_ADDRNOTAVAIL, ERROR_ADDRINUSE, SOCKET_ERRNO_LAST
}
Enumeration of the possible errors returned by a socket.
enum SocketPriority {
NS3_PRIO_BESTEFFORT = 0, NS3_PRIO_FILLER = 1, NS3_PRIO_BULK = 2, NS3_PRIO_INTERACTIVE_BULK = 4,
NS3_PRIO_INTERACTIVE = 6, NS3_PRIO_CONTROL = 7
}
Enumeration of the possible socket priorities.
enum SocketType { NS3_SOCK_STREAM, NS3_SOCK_SEQPACKET, NS3_SOCK_DGRAM, NS3_SOCK_RAW }
Enumeration of the possible socket types.
Protected Member Functions inherited from ns3::Socket
bool IsManualIpTtl (void) const
Checks if the socket has a specific IPv4 TTL set.
bool IsManualIpv6HopLimit (void) const
Checks if the socket has a specific IPv6 Hop Limit set.
bool IsManualIpv6Tclass (void) const
Checks if the socket has a specific IPv6 Tclass set.
void NotifyConnectionFailed (void)
Notify through the callback (if set) that the connection has not been established due to an error.
bool NotifyConnectionRequest (const Address &from)
Notify through the callback (if set) that an incoming connection is being requested by a remote host.
void NotifyConnectionSucceeded (void)
Notify through the callback (if set) that the connection has been established.
void NotifyDataRecv (void)
Notify through the callback (if set) that some data have been received.
void NotifyDataSent (uint32_t size)
Notify through the callback (if set) that some data have been sent.
void NotifyErrorClose (void)
Notify through the callback (if set) that the connection has been closed due to an error.
void NotifyNewConnectionCreated (Ptr< Socket > socket, const Address &from)
Notify through the callback (if set) that a new connection has been created.
void NotifyNormalClose (void)
Notify through the callback (if set) that the connection has been closed.
void NotifySend (uint32_t spaceAvailable)
Notify through the callback (if set) that some data have been sent.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Socket
Ptr< NetDevice > m_boundnetdevice
the device this socket is bound to (might be null).
Ipv6Address m_ipv6MulticastGroupAddress
IPv6 multicast group address.
bool m_recvPktInfo
if the socket should add packet info tags to the packet forwarded to L4.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
IPv6 raw socket.
A RAW Socket typically is used to access specific IP layers not usually available through L4 sockets, e.g., ICMP. The implementer should take particular care to define the Ipv6RawSocketImpl Attributes, and in particular the Protocol attribute. Not setting it will result in a zero protocol at IP level (corresponding to the HopByHop IPv6 Extension header, i.e., Ipv6ExtensionHopByHopHeader) when sending data through the socket, which is probably not the intended behavior.
A correct example is (from src/applications/model/radvd.cc):
if (!m_socket)
  {
    TypeId tid = TypeId::LookupByName ("ns3::Ipv6RawSocketFactory");
    m_socket = Socket::CreateSocket (GetNode (), tid);
    NS_ASSERT (m_socket);
    m_socket->SetAttribute ("Protocol", UintegerValue(Ipv6Header::IPV6_ICMPV6));
    m_socket->SetRecvCallback (MakeCallback (&Radvd::HandleRead, this));
  }
Definition at line 66 of file ipv6-raw-socket-impl.h.
Constructor & Destructor Documentation
Ipv6RawSocketImpl()
ns3::Ipv6RawSocketImpl::Ipv6RawSocketImpl ()
Definition at line 58 of file ipv6-raw-socket-impl.cc.
References ns3::Socket::ERROR_NOTERROR, ns3::Ipv6Address::GetAny(), Icmpv6FilterSetPassAll(), m_dst, m_err, m_node, m_protocol, m_shutdownRecv, m_shutdownSend, m_src, and NS_LOG_FUNCTION_NOARGS.
~Ipv6RawSocketImpl()
ns3::Ipv6RawSocketImpl::~Ipv6RawSocketImpl () virtual
Definition at line 71 of file ipv6-raw-socket-impl.cc.
Member Function Documentation
Bind() [1/2]
int ns3::Ipv6RawSocketImpl::Bind () virtual
Allocate a local IPv4 endpoint for this socket.
Returns
0 on success, -1 on failure.
Implements ns3::Socket.
Definition at line 118 of file ipv6-raw-socket-impl.cc.
References ns3::Ipv6Address::GetAny(), m_src, and NS_LOG_FUNCTION_NOARGS.
Referenced by Bind6().
Bind() [2/2]
int ns3::Ipv6RawSocketImpl::Bind (const Address & address) virtual
Allocate a local endpoint for this socket.
Parameters
address the address to try to allocate
Returns
0 on success, -1 on failure.
Implements ns3::Socket.
Definition at line 104 of file ipv6-raw-socket-impl.cc.
References first::address, ns3::Inet6SocketAddress::ConvertFrom(), ns3::Socket::ERROR_INVAL, ns3::Inet6SocketAddress::GetIpv6(), ns3::Inet6SocketAddress::IsMatchingType(), m_err, m_src, and NS_LOG_FUNCTION.
Bind6()
int ns3::Ipv6RawSocketImpl::Bind6 () virtual
Allocate a local IPv6 endpoint for this socket.
Returns
0 on success, -1 on failure.
Implements ns3::Socket.
Definition at line 125 of file ipv6-raw-socket-impl.cc.
References Bind().
Close()
int ns3::Ipv6RawSocketImpl::Close () virtual
Close a socket.
Returns
zero on success, -1 on failure.
After the Close call, the socket is no longer valid, and cannot safely be used for subsequent operations.
Implements ns3::Socket.
Definition at line 153 of file ipv6-raw-socket-impl.cc.
References ns3::Object::GetObject(), ns3::Socket::Ipv6LeaveGroup(), m_node, and NS_LOG_FUNCTION_NOARGS.
Connect()
int ns3::Ipv6RawSocketImpl::Connect (const Address & address) virtual
Initiate a connection to a remote host.
Parameters
address Address of remote.
Returns
0 on success, -1 on error (in which case errno is set).
Implements ns3::Socket.
Definition at line 180 of file ipv6-raw-socket-impl.cc.
References first::address, ns3::Inet6SocketAddress::ConvertFrom(), ns3::Socket::ERROR_INVAL, ns3::Inet6SocketAddress::GetIpv6(), ns3::Inet6SocketAddress::IsMatchingType(), m_dst, m_err, and NS_LOG_FUNCTION.
DoDispose()
void ns3::Ipv6RawSocketImpl::DoDispose () private virtual
Dispose object.
Reimplemented from ns3::Socket.
Definition at line 75 of file ipv6-raw-socket-impl.cc.
References ns3::Socket::DoDispose(), m_node, and NS_LOG_FUNCTION_NOARGS.
ForwardUp()
bool ns3::Ipv6RawSocketImpl::ForwardUp (Ptr< const Packet > p, Ipv6Header hdr, Ptr< NetDevice > device)
Forward up to receive method.
Parameters
p packet
hdr IPv6 header
device device
Returns
true if forwarded, false otherwise
Definition at line 397 of file ipv6-raw-socket-impl.cc.
References ns3::Packet::AddHeader(), ns3::Packet::AddPacketTag(), data, ns3::Ipv6Address::GetAny(), ns3::Socket::GetBoundNetDevice(), ns3::Ipv6Header::GetDestinationAddress(), ns3::Ipv6Header::GetHopLimit(), ns3::Ipv6Header::GetNextHeader(), ns3::Ipv6Header::GetSourceAddress(), ns3::Icmpv6L4Protocol::GetStaticProtocolNumber(), ns3::Ipv6Header::GetTrafficClass(), ns3::Icmpv6Header::GetType(), Icmpv6FilterWillBlock(), ns3::Socket::IsIpv6RecvHopLimit(), ns3::Socket::IsIpv6RecvTclass(), ns3::Socket::IsRecvPktInfo(), m_data, m_dst, m_protocol, m_shutdownRecv, m_src, ns3::Socket::NotifyDataRecv(), NS_LOG_FUNCTION, ns3::Packet::PeekHeader(), ns3::Packet::RemovePacketTag(), ns3::SocketIpv6HopLimitTag::SetHopLimit(), ns3::Ipv6PacketInfoTag::SetRecvIf(), and ns3::SocketIpv6TclassTag::SetTclass().
Referenced by ns3::Ipv6L3Protocol::Receive().
GetAllowBroadcast()
bool ns3::Ipv6RawSocketImpl::GetAllowBroadcast () const virtual
Query whether broadcast datagram transmissions are allowed.
This method corresponds to using getsockopt() SO_BROADCAST of real network or BSD sockets.
Returns
true if broadcast is allowed, false otherwise
Implements ns3::Socket.
Definition at line 482 of file ipv6-raw-socket-impl.cc.
GetErrno()
enum Socket::SocketErrno ns3::Ipv6RawSocketImpl::GetErrno () const virtual
Get last error number.
Returns
the errno associated to the last call which failed in this socket. Each socket's errno is initialized to zero when the socket is created.
Implements ns3::Socket.
Definition at line 88 of file ipv6-raw-socket-impl.cc.
GetNode()
Ptr< Node > ns3::Ipv6RawSocketImpl::GetNode () const virtual
Return the node this socket is associated with.
Returns
the node
Implements ns3::Socket.
Definition at line 88 of file ipv6-raw-socket-impl.cc.
GetPeerName()
int ns3::Ipv6RawSocketImpl::GetPeerName (Address & address) const virtual
Get the peer address of a connected socket.
Parameters
address the address this socket is connected to.
Returns
0 if success, -1 otherwise
Implements ns3::Socket.
Definition at line 138 of file ipv6-raw-socket-impl.cc.
References first::address, ns3::Socket::ERROR_NOTCONN, ns3::Ipv6Address::IsAny(), m_dst, m_err, and NS_LOG_FUNCTION.
GetRxAvailable()
uint32_t ns3::Ipv6RawSocketImpl::GetRxAvailable () const virtual
Return number of bytes which can be returned from one or multiple calls to Recv.
Must be possible to call this method from the Recv callback.
Returns
the number of bytes which can be returned from one or multiple Recv calls.
Implements ns3::Socket.
Definition at line 384 of file ipv6-raw-socket-impl.cc.
References ns3::GetSize(), m_data, and NS_LOG_FUNCTION_NOARGS.
GetSocketType()
enum Socket::SocketType ns3::Ipv6RawSocketImpl::GetSocketType () const virtual
Get socket type (NS3_SOCK_RAW)
Returns
socket type
Implements ns3::Socket.
Definition at line 88 of file ipv6-raw-socket-impl.cc.
References m_node.
GetSockName()
int ns3::Ipv6RawSocketImpl::GetSockName (Address & address) const virtual
Get socket address.
Parameters
address the address name this socket is associated with.
Returns
0 if success, -1 otherwise
Implements ns3::Socket.
Definition at line 130 of file ipv6-raw-socket-impl.cc.
References first::address, m_src, and NS_LOG_FUNCTION_NOARGS.
GetTxAvailable()
uint32_t ns3::Ipv6RawSocketImpl::GetTxAvailable () const virtual
Returns the number of bytes which can be sent in a single call to Send.
For datagram sockets, this returns the number of bytes that can be passed atomically through the underlying protocol.
For stream sockets, this returns the available space in bytes left in the transmit buffer.
Returns
The number of bytes which can be sent in a single Send call.
Implements ns3::Socket.
Definition at line 378 of file ipv6-raw-socket-impl.cc.
References NS_LOG_FUNCTION_NOARGS.
Referenced by SendTo().
GetTypeId()
TypeId ns3::Ipv6RawSocketImpl::GetTypeId () static
Get the type ID of this class.
Returns
type ID
Definition at line 45 of file ipv6-raw-socket-impl.cc.
References m_protocol, ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
Icmpv6FilterSetBlock()
void ns3::Ipv6RawSocketImpl::Icmpv6FilterSetBlock (uint8_t type)
Set the filter to block one ICMPv6 type.
Parameters
type the ICMPv6 type to block
Definition at line 506 of file ipv6-raw-socket-impl.cc.
References ns3::Ipv6RawSocketImpl::Icmpv6Filter::icmpv6Filt, and m_icmpFilter.
Icmpv6FilterSetBlockAll()
void ns3::Ipv6RawSocketImpl::Icmpv6FilterSetBlockAll ()
Set the filter to block all the ICMPv6 types.
Definition at line 494 of file ipv6-raw-socket-impl.cc.
References m_icmpFilter.
Icmpv6FilterSetPass()
void ns3::Ipv6RawSocketImpl::Icmpv6FilterSetPass (uint8_t type)
Set the filter to pass one ICMPv6 type.
Parameters
type the ICMPv6 type to pass
Definition at line 500 of file ipv6-raw-socket-impl.cc.
References ns3::Ipv6RawSocketImpl::Icmpv6Filter::icmpv6Filt, and m_icmpFilter.
Icmpv6FilterSetPassAll()
void ns3::Ipv6RawSocketImpl::Icmpv6FilterSetPassAll ()
Clean the ICMPv6 filter structure.
Definition at line 488 of file ipv6-raw-socket-impl.cc.
References m_icmpFilter.
Referenced by Ipv6RawSocketImpl().
Icmpv6FilterWillBlock()
bool ns3::Ipv6RawSocketImpl::Icmpv6FilterWillBlock (uint8_t type)
Ask the filter about the status of one ICMPv6 type.
Parameters
type the ICMPv6 type
Returns
true if the ICMP type is being blocked
Definition at line 518 of file ipv6-raw-socket-impl.cc.
References ns3::Ipv6RawSocketImpl::Icmpv6Filter::icmpv6Filt, and m_icmpFilter.
Referenced by ForwardUp().
Icmpv6FilterWillPass()
bool ns3::Ipv6RawSocketImpl::Icmpv6FilterWillPass (uint8_t type)
Ask the filter about the status of one ICMPv6 type.
Parameters
type the ICMPv6 type
Returns
true if the ICMP type is passing through
Definition at line 512 of file ipv6-raw-socket-impl.cc.
References ns3::Ipv6RawSocketImpl::Icmpv6Filter::icmpv6Filt, and m_icmpFilter.
Ipv6JoinGroup()
void ns3::Ipv6RawSocketImpl::Ipv6JoinGroup (Ipv6Address address, Socket::Ipv6MulticastFilterMode filterMode, std::vector< Ipv6Address > sourceAddresses) virtual
Joins a IPv6 multicast group.
Based on the filter mode and source addresses this can be interpreted as a join, leave, or modification to source filtering on a multicast group.
Mind that a socket can join only one multicast group. Any attempt to join another group will remove the old one.
Parameters
address Requested multicast address.
filterMode Socket filtering mode (INCLUDE | EXCLUDE).
sourceAddresses All the source addresses on which socket is interested or not interested.
Reimplemented from ns3::Socket.
Definition at line 335 of file ipv6-raw-socket-impl.cc.
References first::address, ns3::Object::GetObject(), ns3::Socket::INCLUDE, ns3::Ipv6Address::IsAny(), ns3::Socket::m_boundnetdevice, ns3::Socket::m_ipv6MulticastGroupAddress, m_node, NS_ASSERT_MSG(), and NS_LOG_FUNCTION.
Listen()
int ns3::Ipv6RawSocketImpl::Listen () virtual
Listen for incoming connections.
Returns
0 on success, -1 on error (in which case errno is set).
Implements ns3::Socket.
Definition at line 195 of file ipv6-raw-socket-impl.cc.
References ns3::Socket::ERROR_OPNOTSUPP, m_err, and NS_LOG_FUNCTION_NOARGS.
Recv()
Ptr< Packet > ns3::Ipv6RawSocketImpl::Recv (uint32_t maxSize, uint32_t flags) virtual
Read data from the socket.
This function matches closely in semantics to the recv() function call in the standard C library (libc): ssize_t recv (int s, void *buf, size_t len, int flags); except that the receive I/O is asynchronous. This is the primary Recv method at this low-level API and must be implemented by subclasses.
This method is normally used only on a connected socket. In a typical blocking sockets model, this call would block until at least one byte is returned or the connection closes. In ns-3 at this API, the call returns immediately in such a case and returns 0 if nothing is available to be read. However, an application can set a callback, ns3::SetRecvCallback, to be notified of data being available to be read (when it conceptually unblocks); this is an asynchronous I/O model for recv().
This variant of Recv() uses class ns3::Packet to encapsulate data, rather than providing a raw pointer and length field. This allows an ns-3 application to attach tags if desired (such as a flow ID) and may allow the simulator to avoid some data copies. Despite the appearance of receiving Packets on a stream socket, just think of it as a fancy byte buffer with streaming semantics.
The semantics depend on the type of socket. For a datagram socket, each Recv() returns the data from at most one Send(), and order is not necessarily preserved. For a stream socket, the bytes are delivered in order, and on-the-wire packet boundaries are not preserved.
The flags argument is formed by or'ing one or more of the values: MSG_OOB process out-of-band data MSG_PEEK peek at incoming message None of these flags are supported for now.
Some variants of Recv() are supported as additional API, including RecvFrom(), overloaded Recv() without arguments, and variants that use raw character buffers.
Parameters
maxSize reader will accept packet up to maxSize
flags Socket control flags
Returns
Ptr<Packet> of the next in-sequence packet. Returns 0 if the socket cannot return a next in-sequence packet conforming to the maxSize and flags.
See also
SetRecvCallback
Implements ns3::Socket.
Definition at line 300 of file ipv6-raw-socket-impl.cc.
References NS_LOG_FUNCTION, and RecvFrom().
RecvFrom()
Ptr< Packet > ns3::Ipv6RawSocketImpl::RecvFrom (uint32_t maxSize, uint32_t flags, Address & fromAddress) virtual
Read a single packet from the socket and retrieve the sender address.
Calls Recv(maxSize, flags) with maxSize implicitly set to maximum sized integer, and flags set to zero.
This method has similar semantics to Recv () but subclasses may want to provide checks on socket state, so the implementation is pushed to subclasses.
Parameters
maxSize reader will accept packet up to maxSize
flags Socket control flags
fromAddress output parameter that will return the address of the sender of the received packet, if any. Remains untouched if no packet is received.
Returns
Ptr<Packet> of the next in-sequence packet. Returns 0 if the socket cannot return a next in-sequence packet.
Implements ns3::Socket.
Definition at line 307 of file ipv6-raw-socket-impl.cc.
References data, m_data, and NS_LOG_FUNCTION.
Referenced by Recv().
Send()
int ns3::Ipv6RawSocketImpl::Send (Ptr< Packet > p, uint32_t flags) virtual
Send data (or dummy data) to the remote host.
This function matches closely in semantics to the send() function call in the standard C library (libc): ssize_t send (int s, const void *msg, size_t len, int flags); except that the send I/O is asynchronous. This is the primary Send method at this low-level API and must be implemented by subclasses.
In a typical blocking sockets model, this call would block upon lack of space to hold the message to be sent. In ns-3 at this API, the call returns immediately in such a case, but the callback registered with SetSendCallback() is invoked when the socket has space (when it conceptually unblocks); this is an asynchronous I/O model for send().
This variant of Send() uses class ns3::Packet to encapsulate data, rather than providing a raw pointer and length field. This allows an ns-3 application to attach tags if desired (such as a flow ID) and may allow the simulator to avoid some data copies. Despite the appearance of sending Packets on a stream socket, just think of it as a fancy byte buffer with streaming semantics.
If either the message buffer within the Packet is too long to pass atomically through the underlying protocol (for datagram sockets), or the message buffer cannot entirely fit in the transmit buffer (for stream sockets), -1 is returned and SocketErrno is set to ERROR_MSGSIZE. If the packet does not fit, the caller can split the Packet (based on information obtained from GetTxAvailable) and reattempt to send the data.
The flags argument is formed by or'ing one or more of the values: MSG_OOB process out-of-band data MSG_DONTROUTE bypass routing, use direct interface These flags are unsupported as of ns-3.1.
Parameters
p ns3::Packet to send
flags Socket control flags
Returns
the number of bytes accepted for transmission if no error occurs, and -1 otherwise.
See also
SetSendCallback
Implements ns3::Socket.
Definition at line 202 of file ipv6-raw-socket-impl.cc.
References m_dst, m_protocol, NS_LOG_FUNCTION, and SendTo().
SendTo()
int ns3::Ipv6RawSocketImpl::SendTo (Ptr< Packet > p, uint32_t flags, const Address & toAddress) virtual
Send data to a specified peer.
This method has similar semantics to Send () but subclasses may want to provide checks on socket state, so the implementation is pushed to subclasses.
Parameters
p packet to send
flags Socket control flags
toAddress IP Address of remote host
Returns
-1 in case of error or the number of bytes copied in the internal buffer and accepted for transmission.
Implements ns3::Socket.
Definition at line 209 of file ipv6-raw-socket-impl.cc.
References ns3::Packet::AddHeader(), ns3::Packet::AddPacketTag(), ns3::Icmpv6Header::CalculatePseudoHeaderChecksum(), ns3::Inet6SocketAddress::ConvertFrom(), ns3::Packet::CopyData(), ns3::Socket::ERROR_INVAL, ns3::Socket::ERROR_NOTERROR, ns3::Inet6SocketAddress::GetIpv6(), ns3::Socket::GetIpv6HopLimit(), ns3::Socket::GetIpv6Tclass(), ns3::Object::GetObject(), ns3::Icmpv6Echo::GetSerializedSize(), ns3::Packet::GetSize(), ns3::Icmpv6L4Protocol::GetStaticProtocolNumber(), GetTxAvailable(), ns3::Icmpv6Header::ICMPV6_ECHO_REQUEST, ns3::Ipv6Address::IsAny(), ns3::Socket::IsManualIpv6HopLimit(), ns3::Socket::IsManualIpv6Tclass(), ns3::Inet6SocketAddress::IsMatchingType(), ns3::Socket::m_boundnetdevice, m_err, m_node, m_protocol, m_shutdownSend, m_src, ns3::Socket::NotifyDataSent(), ns3::Socket::NotifySend(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_LOG_LOGIC(), ns3::Packet::RemoveHeader(), ns3::Ipv6Header::SetDestinationAddress(), ns3::SocketIpv6HopLimitTag::SetHopLimit(), and ns3::SocketIpv6TclassTag::SetTclass().
Referenced by Send().
SetAllowBroadcast()
bool ns3::Ipv6RawSocketImpl::SetAllowBroadcast (bool allowBroadcast) virtual
Configure whether broadcast datagram transmissions are allowed.
This method corresponds to using setsockopt() SO_BROADCAST of real network or BSD sockets. If set on a socket, this option will enable or disable packets to be transmitted to broadcast destination addresses.
Parameters
allowBroadcast Whether broadcast is allowed
Returns
true if operation succeeds
Implements ns3::Socket.
Definition at line 472 of file ipv6-raw-socket-impl.cc.
SetNode()
void ns3::Ipv6RawSocketImpl::SetNode (Ptr< Node > node)
Set the node associated with this socket.
Parameters
node node to set
Definition at line 82 of file ipv6-raw-socket-impl.cc.
References m_node, and NS_LOG_FUNCTION.
Referenced by ns3::Ipv6L3Protocol::CreateRawSocket().
SetProtocol()
void ns3::Ipv6RawSocketImpl::SetProtocol (uint16_t protocol)
Set protocol field.
Parameters
protocol protocol to set
ShutdownRecv()
int ns3::Ipv6RawSocketImpl::ShutdownRecv () virtual
Returns
zero on success, -1 on failure.
Do not allow any further Recv calls. This method is typically implemented for Tcp sockets by a half close.
Implements ns3::Socket.
Definition at line 173 of file ipv6-raw-socket-impl.cc.
References m_shutdownRecv, and NS_LOG_FUNCTION_NOARGS.
ShutdownSend()
int ns3::Ipv6RawSocketImpl::ShutdownSend () virtual
Returns
zero on success, -1 on failure.
Do not allow any further Send calls. This method is typically implemented for Tcp sockets by a half close.
Implements ns3::Socket.
Definition at line 166 of file ipv6-raw-socket-impl.cc.
References m_shutdownSend, and NS_LOG_FUNCTION_NOARGS.
Member Data Documentation
m_data
std::list<Data> ns3::Ipv6RawSocketImpl::m_data private
Packet waiting to be processed.
Definition at line 213 of file ipv6-raw-socket-impl.h.
Referenced by ForwardUp(), GetRxAvailable(), and RecvFrom().
m_dst
Ipv6Address ns3::Ipv6RawSocketImpl::m_dst private
Destination address.
Definition at line 203 of file ipv6-raw-socket-impl.h.
Referenced by Ipv6RawSocketImpl(), Connect(), ForwardUp(), GetPeerName(), and Send().
m_err
enum Socket::SocketErrno ns3::Ipv6RawSocketImpl::m_err mutable private
Last error number.
Definition at line 183 of file ipv6-raw-socket-impl.h.
Referenced by Ipv6RawSocketImpl(), Bind(), Connect(), GetPeerName(), Listen(), and SendTo().
m_icmpFilter
Icmpv6Filter ns3::Ipv6RawSocketImpl::m_icmpFilter private
ICMPv6 filter.
Definition at line 236 of file ipv6-raw-socket-impl.h.
Referenced by Icmpv6FilterSetBlock(), Icmpv6FilterSetBlockAll(), Icmpv6FilterSetPass(), Icmpv6FilterSetPassAll(), Icmpv6FilterWillBlock(), and Icmpv6FilterWillPass().
m_node
Ptr<Node> ns3::Ipv6RawSocketImpl::m_node private
Node.
Definition at line 193 of file ipv6-raw-socket-impl.h.
Referenced by Ipv6RawSocketImpl(), Close(), DoDispose(), GetSocketType(), Ipv6JoinGroup(), SendTo(), and SetNode().
m_protocol
uint16_t ns3::Ipv6RawSocketImpl::m_protocol private
Protocol.
Definition at line 208 of file ipv6-raw-socket-impl.h.
Referenced by Ipv6RawSocketImpl(), ForwardUp(), GetTypeId(), Send(), and SendTo().
m_shutdownRecv
bool ns3::Ipv6RawSocketImpl::m_shutdownRecv private
Flag to shutdown receive capability.
Definition at line 223 of file ipv6-raw-socket-impl.h.
Referenced by Ipv6RawSocketImpl(), ForwardUp(), and ShutdownRecv().
m_shutdownSend
bool ns3::Ipv6RawSocketImpl::m_shutdownSend private
Flag to shutdown send capability.
Definition at line 218 of file ipv6-raw-socket-impl.h.
Referenced by Ipv6RawSocketImpl(), SendTo(), and ShutdownSend().
m_src
Ipv6Address ns3::Ipv6RawSocketImpl::m_src private
Source address.
Definition at line 198 of file ipv6-raw-socket-impl.h.
Referenced by Ipv6RawSocketImpl(), Bind(), ForwardUp(), GetSockName(), and SendTo().
The documentation for this class was generated from the following files:
src/internet/model/ipv6-raw-socket-impl.h
src/internet/model/ipv6-raw-socket-impl.cc