ns-3: ns3::LoraHelper Class Reference
ns3::LoraHelper Class Reference
Helps to create LoraNetDevice objects.
#include "lora-helper.h"
Public Member Functions
LoraHelper ()
virtual ~LoraHelper ()
virtual NetDeviceContainer Install (const LoraPhyHelper &phyHelper, const LoraMacHelper &macHelper, NodeContainer c) const
Install LoraNetDevices on a list of nodes.
virtual NetDeviceContainer Install (const LoraPhyHelper &phyHelper, const LoraMacHelper &macHelper, Ptr< Node > node) const
Install LoraNetDevice on a single node.
Detailed Description
Helps to create LoraNetDevice objects.
This class can help create a large set of similar LoraNetDevice objects and configure a large set of their attributes during creation.
Definition at line 39 of file lora-helper.h.
Constructor & Destructor Documentation
~LoraHelper()
ns3::LoraHelper::~LoraHelper () virtual
Definition at line 32 of file lora-helper.cc.
LoraHelper()
ns3::LoraHelper::LoraHelper ()
Definition at line 28 of file lora-helper.cc.
Member Function Documentation
Install() [1/2]
NetDeviceContainer ns3::LoraHelper::Install (const LoraPhyHelper & phyHelper, const LoraMacHelper & macHelper, NodeContainer c) const virtual
Install LoraNetDevices on a list of nodes.
Parameters
phy the PHY helper to create PHY objects
mac the MAC helper to create MAC objects
c the set of nodes on which a lora device must be created
Returns
a device container which contains all the devices created by this method.
Definition at line 37 of file lora-helper.cc.
References ns3::Node::AddDevice(), ns3::NodeContainer::Begin(), ns3::LoraMacHelper::Create(), ns3::LoraPhyHelper::Create(), first::devices, ns3::NodeContainer::End(), ns3::Object::GetObject(), third::mac, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION_NOARGS, and third::phy.
Referenced by Install(), and Reset().
Install() [2/2]
NetDeviceContainer ns3::LoraHelper::Install (const LoraPhyHelper & phyHelper, const LoraMacHelper & macHelper, Ptr< Node > node) const virtual
Install LoraNetDevice on a single node.
Parameters
phy the PHY helper to create PHY objects
mac the MAC helper to create MAC objects
node the node on which a lora device must be created
Returns
a device container which contains all the devices created by this method.
Definition at line 74 of file lora-helper.cc.
References Install(), third::mac, and third::phy.
The documentation for this class was generated from the following files:
src/lorawan/helper/lora-helper.h
src/lorawan/helper/lora-helper.cc