ns-3: LtePathlossModelSystemTestCase Class Reference
LtePathlossModelSystemTestCase Class Reference
LTE Models » lte module tests | Test suites
Tests that the BuildingPathlossModel works according to the expected theoretical values. Theoretical reference values are obtained with the octave script src/lte/test/reference/lte_pathloss.m.
#include "lte-test-pathloss-model.h"
Public Member Functions
LtePathlossModelSystemTestCase ()
LtePathlossModelSystemTestCase (std::string name, double snrDb, double dist, uint16_t mcsIndex)
Constructor.
virtual ~LtePathlossModelSystemTestCase ()
void DlScheduling (DlSchedulingCallbackInfo dlInfo)
DL scheduling function.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
double m_distance
the distance
uint16_t m_mcsIndex
the MCS index
double m_snrDb
the SNR in dB
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Tests that the BuildingPathlossModel works according to the expected theoretical values. Theoretical reference values are obtained with the octave script src/lte/test/reference/lte_pathloss.m.
Definition at line 55 of file lte-test-pathloss-model.h.
Constructor & Destructor Documentation
LtePathlossModelSystemTestCase() [1/2]
LtePathlossModelSystemTestCase::LtePathlossModelSystemTestCase (std::string name, double snrDb, double dist, uint16_t mcsIndex)
Constructor.
Parameters
name the reference name
snrDb the SNR in dB
dist the distance
mcsIndex the MCS index
Definition at line 176 of file lte-test-pathloss-model.cc.
References NS_LOG_INFO.
LtePathlossModelSystemTestCase() [2/2]
LtePathlossModelSystemTestCase::LtePathlossModelSystemTestCase ()
~LtePathlossModelSystemTestCase()
LtePathlossModelSystemTestCase::~LtePathlossModelSystemTestCase () virtual
Definition at line 189 of file lte-test-pathloss-model.cc.
Member Function Documentation
DlScheduling()
void LtePathlossModelSystemTestCase::DlScheduling (DlSchedulingCallbackInfo dlInfo)
DL scheduling function.
Parameters
dlInfo the DL info
Definition at line 285 of file lte-test-pathloss-model.cc.
References m_mcsIndex, m_snrDb, ns3::DlSchedulingCallbackInfo::mcsTb1, ns3::MilliSeconds(), ns3::Now(), NS_LOG_INFO, and NS_TEST_ASSERT_MSG_EQ.
Referenced by LteTestPathlossDlSchedCallback().
DoRun()
void LtePathlossModelSystemTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Simulation Topology
Implements ns3::TestCase.
Definition at line 194 of file lte-test-pathloss-model.cc.
References ns3::LteHelper::ActivateDataRadioBearer(), ns3::LteChunkProcessor::AddCallback(), ns3::LteHelper::Attach(), ns3::NodeContainer::Create(), ns3::LteHelper::EnableMacTraces(), ns3::LteHelper::EnableRlcTraces(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::Object::GetObject(), ns3::LteEnbNetDevice::GetPhy(), ns3::LteUeNetDevice::GetPhy(), ns3::LteSpectrumValueCatcher::GetValue(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), m_distance, m_snrDb, ns3::MakeCallback(), third::mobility, NS_LOG_INFO, NS_TEST_ASSERT_MSG_EQ_TOL, ns3::Seconds(), ns3::ObjectBase::SetAttribute(), ns3::Config::SetDefault(), ns3::LteHelper::SetEnbDeviceAttribute(), ns3::LteHelper::SetPathlossModelAttribute(), ns3::MobilityModel::SetPosition(), ns3::LteHelper::SetSchedulerType(), and ns3::LteHelper::SetUeDeviceAttribute().
Member Data Documentation
m_distance
double LtePathlossModelSystemTestCase::m_distance private
the distance
Definition at line 80 of file lte-test-pathloss-model.h.
Referenced by DoRun().
m_mcsIndex
uint16_t LtePathlossModelSystemTestCase::m_mcsIndex private
the MCS index
Definition at line 81 of file lte-test-pathloss-model.h.
Referenced by DlScheduling().
m_snrDb
double LtePathlossModelSystemTestCase::m_snrDb private
the SNR in dB
Definition at line 79 of file lte-test-pathloss-model.h.
Referenced by DlScheduling(), and DoRun().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-pathloss-model.h
src/lte/test/lte-test-pathloss-model.cc