ns-3: ns3::Ipv6ExtensionLooseRoutingHeader Class Reference
ns3::Ipv6ExtensionLooseRoutingHeader Class Reference
Internet » IPv6 classes and sub-modules » IPV6 Header extension system.
Header of IPv6 Extension Routing : Type 0 (Loose Routing)
#include "ipv6-extension-header.h"
Public Member Functions
Ipv6ExtensionLooseRoutingHeader ()
Constructor.
virtual ~Ipv6ExtensionLooseRoutingHeader ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
Ipv6Address GetRouterAddress (uint8_t index) const
Get a Router IPv6 Address.
std::vector< Ipv6Address > GetRoutersAddress () const
Get the vector of routers' address.
virtual uint32_t GetSerializedSize () const
Get the serialized size of the packet.
virtual void Print (std::ostream &os) const
Print some information about the packet.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetNumberAddress (uint8_t n)
Set the number of routers' address.
void SetRouterAddress (uint8_t index, Ipv6Address addr)
Set a Router IPv6 Address.
void SetRoutersAddress (std::vector< Ipv6Address > routersAddress)
Set the vector of routers' address.
Public Member Functions inherited from ns3::Ipv6ExtensionRoutingHeader
Ipv6ExtensionRoutingHeader ()
Constructor.
virtual ~Ipv6ExtensionRoutingHeader ()
Destructor.
uint8_t GetSegmentsLeft () const
Get the field "Segments left".
uint8_t GetTypeRouting () const
Get the field "Type of Routing".
void SetSegmentsLeft (uint8_t segmentsLeft)
Set the "Segments left" field.
void SetTypeRouting (uint8_t typeRouting)
Set the "Type of Routing" field.
Public Member Functions inherited from ns3::Ipv6ExtensionHeader
Ipv6ExtensionHeader ()
Constructor.
virtual ~Ipv6ExtensionHeader ()
Destructor.
uint16_t GetLength () const
Get the length of the extension.
uint8_t GetNextHeader () const
Get the next header.
void SetLength (uint16_t length)
brief Set the length of the extension.
void SetNextHeader (uint8_t nextHeader)
Set the "Next header" field.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Ipv6ExtensionRoutingHeader
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Ipv6ExtensionHeader
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef std::vector< Ipv6Address > VectorIpv6Address_t
A vector of IPv6 Address.
Private Attributes
VectorIpv6Address_t m_routersAddress
The vector of Routers' IPv6 Address.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Ipv6ExtensionHeader
uint8_t m_length
The "length" field.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Header of IPv6 Extension Routing : Type 0 (Loose Routing)
Definition at line 533 of file ipv6-extension-header.h.
Member Typedef Documentation
VectorIpv6Address_t
typedef std::vector<Ipv6Address> ns3::Ipv6ExtensionLooseRoutingHeader::VectorIpv6Address_t private
A vector of IPv6 Address.
Definition at line 620 of file ipv6-extension-header.h.
Constructor & Destructor Documentation
Ipv6ExtensionLooseRoutingHeader()
ns3::Ipv6ExtensionLooseRoutingHeader::Ipv6ExtensionLooseRoutingHeader ()
Constructor.
Definition at line 511 of file ipv6-extension-header.cc.
~Ipv6ExtensionLooseRoutingHeader()
ns3::Ipv6ExtensionLooseRoutingHeader::~Ipv6ExtensionLooseRoutingHeader () virtual
Destructor.
Definition at line 516 of file ipv6-extension-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::Ipv6ExtensionLooseRoutingHeader::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start Buffer iterator
Returns
size of the packet
Reimplemented from ns3::Ipv6ExtensionRoutingHeader.
Definition at line 584 of file ipv6-extension-header.cc.
References GetSerializedSize(), ns3::Ipv6ExtensionHeader::m_length, ns3::Buffer::Iterator::Read(), ns3::Buffer::Iterator::ReadU32(), ns3::Buffer::Iterator::ReadU8(), ns3::Ipv6ExtensionHeader::SetNextHeader(), SetNumberAddress(), SetRouterAddress(), ns3::Ipv6ExtensionRoutingHeader::SetSegmentsLeft(), ns3::Ipv6ExtensionRoutingHeader::SetTypeRouting(), and visualizer.core::start().
GetInstanceTypeId()
TypeId ns3::Ipv6ExtensionLooseRoutingHeader::GetInstanceTypeId () const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::Ipv6ExtensionRoutingHeader.
Definition at line 506 of file ipv6-extension-header.cc.
References GetTypeId().
GetRouterAddress()
Ipv6Address ns3::Ipv6ExtensionLooseRoutingHeader::GetRouterAddress (uint8_t index) const
Get a Router IPv6 Address.
Parameters
index the index of the IPv6 Address
Returns
the router IPv6 Address
Definition at line 541 of file ipv6-extension-header.cc.
References m_routersAddress.
Referenced by ns3::Ipv6ExtensionLooseRouting::Process().
GetRoutersAddress()
std::vector< Ipv6Address > ns3::Ipv6ExtensionLooseRoutingHeader::GetRoutersAddress () const
Get the vector of routers' address.
Returns
the vector of routers' address
Definition at line 531 of file ipv6-extension-header.cc.
References m_routersAddress.
GetSerializedSize()
uint32_t ns3::Ipv6ExtensionLooseRoutingHeader::GetSerializedSize () const virtual
Get the serialized size of the packet.
Returns
size
Reimplemented from ns3::Ipv6ExtensionRoutingHeader.
Definition at line 559 of file ipv6-extension-header.cc.
References m_routersAddress.
Referenced by Deserialize(), and ns3::Ipv6ExtensionLooseRouting::Process().
GetTypeId()
TypeId ns3::Ipv6ExtensionLooseRoutingHeader::GetTypeId () static
Get the type identificator.
Returns
type identificator
Definition at line 496 of file ipv6-extension-header.cc.
References ns3::TypeId::AddConstructor().
Referenced by GetInstanceTypeId().
Print()
void ns3::Ipv6ExtensionLooseRoutingHeader::Print (std::ostream & os) const virtual
Print some information about the packet.
Parameters
os output stream
Returns
info about this packet
Reimplemented from ns3::Ipv6ExtensionRoutingHeader.
Definition at line 546 of file ipv6-extension-header.cc.
References ns3::Ipv6ExtensionHeader::GetLength(), ns3::Ipv6ExtensionHeader::GetNextHeader(), ns3::Ipv6ExtensionRoutingHeader::GetSegmentsLeft(), ns3::Ipv6ExtensionRoutingHeader::GetTypeRouting(), and m_routersAddress.
Serialize()
void ns3::Ipv6ExtensionLooseRoutingHeader::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start Buffer iterator
Reimplemented from ns3::Ipv6ExtensionRoutingHeader.
Definition at line 564 of file ipv6-extension-header.cc.
References ns3::Ipv6ExtensionHeader::GetNextHeader(), ns3::Ipv6ExtensionRoutingHeader::GetSegmentsLeft(), ns3::Ipv6ExtensionRoutingHeader::GetTypeRouting(), m_routersAddress, visualizer.core::start(), ns3::Buffer::Iterator::Write(), ns3::Buffer::Iterator::WriteU32(), and ns3::Buffer::Iterator::WriteU8().
SetNumberAddress()
void ns3::Ipv6ExtensionLooseRoutingHeader::SetNumberAddress (uint8_t n)
Set the number of routers' address.
Parameters
n the number of routers' address
Definition at line 520 of file ipv6-extension-header.cc.
References m_routersAddress, and sample-rng-plot::n.
Referenced by Deserialize(), ns3::Ipv6ExtensionFragment::GetFragments(), and ns3::Ipv6ExtensionLooseRouting::Process().
SetRouterAddress()
void ns3::Ipv6ExtensionLooseRoutingHeader::SetRouterAddress (uint8_t index, Ipv6Address addr)
Set a Router IPv6 Address.
Parameters
index the index of the IPv6 Address
addr the new IPv6 Address
Definition at line 536 of file ipv6-extension-header.cc.
References m_routersAddress.
Referenced by Deserialize(), and ns3::Ipv6ExtensionLooseRouting::Process().
SetRoutersAddress()
void ns3::Ipv6ExtensionLooseRoutingHeader::SetRoutersAddress (std::vector< Ipv6Address > routersAddress)
Set the vector of routers' address.
Parameters
routersAddress the vector of routers's address
Definition at line 526 of file ipv6-extension-header.cc.
References m_routersAddress.
Referenced by ns3::Ping6::Send().
Member Data Documentation
m_routersAddress
VectorIpv6Address_t ns3::Ipv6ExtensionLooseRoutingHeader::m_routersAddress private
The vector of Routers' IPv6 Address.
Definition at line 625 of file ipv6-extension-header.h.
Referenced by GetRouterAddress(), GetRoutersAddress(), GetSerializedSize(), Print(), Serialize(), SetNumberAddress(), SetRouterAddress(), and SetRoutersAddress().
The documentation for this class was generated from the following files:
src/internet/model/ipv6-extension-header.h
src/internet/model/ipv6-extension-header.cc