ns-3: PfifoFastQueueDiscOverflow Class Reference
PfifoFastQueueDiscOverflow Class Reference
This class tests that each band is txqueuelen deep.
Public Member Functions
PfifoFastQueueDiscOverflow ()
virtual ~PfifoFastQueueDiscOverflow ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void AddPacket (Ptr< PfifoFastQueueDisc > queue, Ipv4Header::DscpType dscp)
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
This class tests that each band is txqueuelen deep.
Definition at line 196 of file pfifo-fast-queue-disc-test-suite.cc.
Constructor & Destructor Documentation
PfifoFastQueueDiscOverflow()
PfifoFastQueueDiscOverflow::PfifoFastQueueDiscOverflow ()
Definition at line 207 of file pfifo-fast-queue-disc-test-suite.cc.
~PfifoFastQueueDiscOverflow()
PfifoFastQueueDiscOverflow::~PfifoFastQueueDiscOverflow () virtual
Definition at line 212 of file pfifo-fast-queue-disc-test-suite.cc.
Member Function Documentation
AddPacket()
void PfifoFastQueueDiscOverflow::AddPacket (Ptr< PfifoFastQueueDisc > queue, Ipv4Header::DscpType dscp) private
Definition at line 217 of file pfifo-fast-queue-disc-test-suite.cc.
References ns3::Packet::AddPacketTag(), ns3::QueueDisc::Enqueue(), ns3::Ipv4Header::GetTos(), ns3::Ipv4Header::SetDscp(), ns3::Ipv4Header::SetPayloadSize(), ns3::SocketPriorityTag::SetPriority(), and ns3::Ipv4Header::SetProtocol().
Referenced by DoRun().
DoRun()
void PfifoFastQueueDiscOverflow::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 233 of file pfifo-fast-queue-disc-test-suite.cc.
References ns3::QueueDisc::AddInternalQueue(), AddPacket(), ns3::QueueDisc::GetInternalQueue(), and NS_TEST_ASSERT_MSG_EQ.
The documentation for this class was generated from the following file:
src/test/ns3tc/pfifo-fast-queue-disc-test-suite.cc