ns-3: LrWpanPacketTestCase Class Reference
LrWpanPacketTestCase Class Reference
LR-WPAN models » LrWpan module tests | Test suites
LrWpan header and trailer Test.
Public Member Functions
LrWpanPacketTestCase ()
virtual ~LrWpanPacketTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
LrWpan header and trailer Test.
Definition at line 39 of file lr-wpan-packet-test.cc.
Constructor & Destructor Documentation
LrWpanPacketTestCase()
LrWpanPacketTestCase::LrWpanPacketTestCase ()
Definition at line 49 of file lr-wpan-packet-test.cc.
~LrWpanPacketTestCase()
LrWpanPacketTestCase::~LrWpanPacketTestCase () virtual
Definition at line 54 of file lr-wpan-packet-test.cc.
Member Function Documentation
DoRun()
void LrWpanPacketTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 59 of file lr-wpan-packet-test.cc.
References ns3::Packet::AddHeader(), ns3::Packet::AddTrailer(), ns3::Packet::GetSerializedSize(), ns3::Packet::GetSize(), NS_TEST_ASSERT_MSG_EQ, ns3::LrWpanMacHeader::Print(), ns3::Packet::Print(), ns3::Packet::RemoveHeader(), ns3::Packet::RemoveTrailer(), ns3::Packet::Serialize(), ns3::LrWpanMacHeader::SetDstAddrMode(), ns3::LrWpanMacHeader::SetNoPanIdComp(), ns3::LrWpanMacHeader::SetSecDisable(), ns3::LrWpanMacHeader::SetSrcAddrFields(), and ns3::LrWpanMacHeader::SetSrcAddrMode().
The documentation for this class was generated from the following file:
src/lr-wpan/test/lr-wpan-packet-test.cc