ns-3: WifiMsduAggregatorThroughputTest Class Reference
WifiMsduAggregatorThroughputTest Class Reference
Public Member Functions
WifiMsduAggregatorThroughputTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Attributes
bool m_writeResults
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 37 of file wifi-msdu-aggregator-test-suite.cc.
Constructor & Destructor Documentation
WifiMsduAggregatorThroughputTest()
WifiMsduAggregatorThroughputTest::WifiMsduAggregatorThroughputTest ()
Definition at line 47 of file wifi-msdu-aggregator-test-suite.cc.
Member Function Documentation
DoRun()
void WifiMsduAggregatorThroughputTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 54 of file wifi-msdu-aggregator-test-suite.cc.
References first::address, ns3::NodeContainer::Create(), ns3::YansWifiChannelHelper::Create(), ns3::PcapHelperForDevice::EnablePcap(), ns3::ApplicationContainer::Get(), ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::Node::GetId(), ns3::OnOffHelper::Install(), ns3::PacketSinkHelper::Install(), m_writeResults, ns3::MicroSeconds(), third::mobility, NS_TEST_ASSERT_MSG_GT, ns3::Seconds(), ns3::OnOffHelper::SetAttribute(), ns3::YansWifiPhyHelper::SetChannel(), ns3::OnOffHelper::SetConstantRate(), ns3::WifiMacHelper::SetType(), third::ssid, first::stack, ns3::ApplicationContainer::Start(), ns3::ApplicationContainer::Stop(), third::wifi, and ns3::WIFI_PHY_STANDARD_80211b.
Member Data Documentation
m_writeResults
bool WifiMsduAggregatorThroughputTest::m_writeResults private
Definition at line 44 of file wifi-msdu-aggregator-test-suite.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/test/ns3wifi/wifi-msdu-aggregator-test-suite.cc