ns-3: LenaTdTbfqFfMacSchedulerTestCase1 Class Reference
LenaTdTbfqFfMacSchedulerTestCase1 Class Reference
LTE Models » lte module tests | Test suites
This system test program creates different test cases with a single eNB and several UEs, all having the same Radio Bearer specification. In each test case, the UEs see the same SINR from the eNB; different test cases are implemented obtained by using different SINR values and different numbers of UEs. The test consists on checking that the obtained throughput performance is equal among users is consistent with the definition of token bank fair
queue scheduling.
#include "lte-test-tdtbfq-ff-mac-scheduler.h"
Public Member Functions
LenaTdTbfqFfMacSchedulerTestCase1 (uint16_t nUser, double dist, double thrRefDl, double thrRefUl, uint16_t packetSize, uint16_t interval, bool errorModelEnabled)
Constructor.
virtual ~LenaTdTbfqFfMacSchedulerTestCase1 ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Static Private Member Functions
static std::string BuildNameString (uint16_t nUser, double dist)
Builds the test name string based on provided parameter values.
Private Attributes
double m_dist
the distance between nodes
bool m_errorModelEnabled
whether the error model is enabled
uint16_t m_interval
the interval time in ms
uint16_t m_nUser
number of UE nodes
uint16_t m_packetSize
the packet size in bytes
double m_thrRefDl
the DL throughput reference
double m_thrRefUl
the UL throughput reference
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
This system test program creates different test cases with a single eNB and several UEs, all having the same Radio Bearer specification. In each test case, the UEs see the same SINR from the eNB; different test cases are implemented obtained by using different SINR values and different numbers of UEs. The test consists on checking that the obtained throughput performance is equal among users is consistent with the definition of token bank fair
queue scheduling.
Definition at line 45 of file lte-test-tdtbfq-ff-mac-scheduler.h.
Constructor & Destructor Documentation
LenaTdTbfqFfMacSchedulerTestCase1()
LenaTdTbfqFfMacSchedulerTestCase1::LenaTdTbfqFfMacSchedulerTestCase1 (uint16_t nUser, double dist, double thrRefDl, double thrRefUl, uint16_t packetSize, uint16_t interval, bool errorModelEnabled)
Constructor.
Parameters
nUser the number of UE nodes
dist the distance between nodes
thrRefDl the DL throughput reference
thrRefUl the UL throughput reference
packetSize the packet size
interval the interval time
errorModelEnabled if true the error model is enabled
Definition at line 245 of file lte-test-tdtbfq-ff-mac-scheduler.cc.
~LenaTdTbfqFfMacSchedulerTestCase1()
LenaTdTbfqFfMacSchedulerTestCase1::~LenaTdTbfqFfMacSchedulerTestCase1 () virtual
Definition at line 257 of file lte-test-tdtbfq-ff-mac-scheduler.cc.
Member Function Documentation
BuildNameString()
std::string LenaTdTbfqFfMacSchedulerTestCase1::BuildNameString (uint16_t nUser, double dist) static private
Builds the test name string based on provided parameter values.
Parameters
nUser the number of UE nodes
dist the distnace between UE nodes and eNodeB
Returns
the name string
Definition at line 237 of file lte-test-tdtbfq-ff-mac-scheduler.cc.
DoRun()
void LenaTdTbfqFfMacSchedulerTestCase1::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Check that the downlink assignment is done in a "token bank fair queue" manner
Check that the uplink assignment is done in a "round robin" manner
Implements ns3::TestCase.
Definition at line 262 of file lte-test-tdtbfq-ff-mac-scheduler.cc.
References ns3::LteHelper::ActivateDedicatedEpsBearer(), ns3::Ipv4StaticRouting::AddNetworkRouteTo(), ns3::Ipv4AddressHelper::Assign(), ns3::NoBackhaulEpcHelper::AssignUeIpv4Address(), ns3::LteHelper::Attach(), first::clientApps, ns3::NodeContainer::Create(), ns3::TestCase::CreateTempDirFilename(), data, ns3::LteHelper::EnableMacTraces(), ns3::LteHelper::EnableRlcTraces(), ns3::GbrQosInformation::gbrDl, ns3::GbrQosInformation::gbrUl, ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::RadioBearerStatsCalculator::GetDlRxData(), ns3::NodeContainer::GetN(), ns3::TestCase::GetName(), ns3::Object::GetObject(), ns3::NoBackhaulEpcHelper::GetPgwNode(), ns3::LteEnbNetDevice::GetPhy(), ns3::LteUeNetDevice::GetPhy(), ns3::LteHelper::GetRlcStats(), ns3::Ipv4StaticRoutingHelper::GetStaticRouting(), ns3::NoBackhaulEpcHelper::GetUeDefaultGatewayAddress(), ns3::RadioBearerStatsCalculator::GetUlRxData(), ns3::UdpClientHelper::Install(), ns3::PointToPointHelper::Install(), ns3::PacketSinkHelper::Install(), ns3::InternetStackHelper::Install(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), m_dist, m_errorModelEnabled, m_interval, m_nUser, m_packetSize, m_thrRefDl, m_thrRefUl, ns3::GbrQosInformation::mbrDl, ns3::GbrQosInformation::mbrUl, ns3::MilliSeconds(), third::mobility, NS_LOG_FUNCTION, NS_LOG_INFO, NS_TEST_ASSERT_MSG_EQ_TOL, ns3::Seconds(), first::serverApps, ns3::UdpClientHelper::SetAttribute(), ns3::ObjectBase::SetAttribute(), ns3::Ipv4AddressHelper::SetBase(), ns3::PointToPointHelper::SetChannelAttribute(), ns3::Config::SetDefault(), ns3::Ipv4StaticRouting::SetDefaultRoute(), ns3::PointToPointHelper::SetDeviceAttribute(), ns3::LteHelper::SetEpcHelper(), ns3::MobilityModel::SetPosition(), ns3::LteHelper::SetSchedulerAttribute(), and ns3::LteHelper::SetSchedulerType().
Member Data Documentation
m_dist
double LenaTdTbfqFfMacSchedulerTestCase1::m_dist private
the distance between nodes
Definition at line 72 of file lte-test-tdtbfq-ff-mac-scheduler.h.
Referenced by DoRun().
m_errorModelEnabled
bool LenaTdTbfqFfMacSchedulerTestCase1::m_errorModelEnabled private
whether the error model is enabled
Definition at line 77 of file lte-test-tdtbfq-ff-mac-scheduler.h.
Referenced by DoRun().
m_interval
uint16_t LenaTdTbfqFfMacSchedulerTestCase1::m_interval private
the interval time in ms
Definition at line 74 of file lte-test-tdtbfq-ff-mac-scheduler.h.
Referenced by DoRun().
m_nUser
uint16_t LenaTdTbfqFfMacSchedulerTestCase1::m_nUser private
number of UE nodes
Definition at line 71 of file lte-test-tdtbfq-ff-mac-scheduler.h.
Referenced by DoRun().
m_packetSize
uint16_t LenaTdTbfqFfMacSchedulerTestCase1::m_packetSize private
the packet size in bytes
Definition at line 73 of file lte-test-tdtbfq-ff-mac-scheduler.h.
Referenced by DoRun().
m_thrRefDl
double LenaTdTbfqFfMacSchedulerTestCase1::m_thrRefDl private
the DL throughput reference
Definition at line 75 of file lte-test-tdtbfq-ff-mac-scheduler.h.
Referenced by DoRun().
m_thrRefUl
double LenaTdTbfqFfMacSchedulerTestCase1::m_thrRefUl private
the UL throughput reference
Definition at line 76 of file lte-test-tdtbfq-ff-mac-scheduler.h.
Referenced by DoRun().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-tdtbfq-ff-mac-scheduler.h
src/lte/test/lte-test-tdtbfq-ff-mac-scheduler.cc