ns-3: ns3::flame::FlameRtable Class Reference
ns3::flame::FlameRtable Class Reference
Mesh Device » FLAME
Routing table for FLAME.
#include "flame-rtable.h"
Classes
struct LookupResult
Route lookup result, return type of LookupXXX methods.
struct Route
Routing table entry.
Public Member Functions
FlameRtable ()
~FlameRtable ()
void AddPath (const Mac48Address destination, const Mac48Address retransmitter, const uint32_t interface, const uint8_t cost, const uint16_t seqnum)
Add path.
void DoDispose ()
Destructor implementation.
LookupResult Lookup (Mac48Address destination)
Lookup path to destination.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static const uint32_t INTERFACE_ANY = 0xffffffff
Means all interfaces.
static const uint32_t MAX_COST = 0xff
Maximum (the best?) path cost.
Private Member Functions
FlameRtable (const FlameRtable &)
type conversion operator
FlameRtable & operator= (const FlameRtable &table)
assignment operator
Private Attributes
Time m_lifetime
Lifetime parameter.
std::map< Mac48Address, Route > m_routes
List of routes.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Routing table for FLAME.
Definition at line 36 of file flame-rtable.h.
Constructor & Destructor Documentation
FlameRtable() [1/2]
ns3::flame::FlameRtable::FlameRtable ()
Definition at line 52 of file flame-rtable.cc.
~FlameRtable()
ns3::flame::FlameRtable::~FlameRtable ()
Definition at line 56 of file flame-rtable.cc.
FlameRtable() [2/2]
ns3::flame::FlameRtable::FlameRtable (const FlameRtable &) private
type conversion operator
Member Function Documentation
AddPath()
void ns3::flame::FlameRtable::AddPath (const Mac48Address destination, const Mac48Address retransmitter, const uint32_t interface, const uint8_t cost, const uint16_t seqnum)
Add path.
Parameters
destination the destination address
retransmitter the retransmitter address
interface the interface
cost the cost
seqnum the sequence number
Definition at line 65 of file flame-rtable.cc.
References ns3::flame::FlameRtable::Route::cost, ns3::flame::FlameRtable::Route::interface, m_lifetime, m_routes, ns3::Simulator::Now(), NS_ASSERT, ns3::flame::FlameRtable::Route::retransmitter, ns3::flame::FlameRtable::Route::seqnum, and ns3::flame::FlameRtable::Route::whenExpire.
Referenced by ns3::flame::FlameProtocol::HandleDataFrame(), FlameRtableTest::TestAddPath(), and FlameRtableTest::TestLookup().
DoDispose()
void ns3::flame::FlameRtable::DoDispose () virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 60 of file flame-rtable.cc.
References m_routes.
GetTypeId()
TypeId ns3::flame::FlameRtable::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 36 of file flame-rtable.cc.
References m_lifetime, ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::Seconds(), and ns3::TypeId::SetParent().
Lookup()
FlameRtable::LookupResult ns3::flame::FlameRtable::Lookup (Mac48Address destination)
Lookup path to destination.
Parameters
destination
Returns
Broadcast if not found
Definition at line 88 of file flame-rtable.cc.
References m_routes, ns3::Simulator::Now(), and NS_LOG_DEBUG.
Referenced by ns3::flame::FlameProtocol::HandleDataFrame(), ns3::flame::FlameProtocol::RequestRoute(), FlameRtableTest::TestExpire(), and FlameRtableTest::TestLookup().
operator=()
FlameRtable& ns3::flame::FlameRtable::operator= (const FlameRtable & table) private
assignment operator
Parameters
table the flame table to assign
Returns
the assigned value
Member Data Documentation
INTERFACE_ANY
const uint32_t ns3::flame::FlameRtable::INTERFACE_ANY = 0xffffffff static
Means all interfaces.
Definition at line 40 of file flame-rtable.h.
Referenced by ns3::flame::FlameRtable::LookupResult::IsValid(), and ns3::flame::FlameProtocol::RequestRoute().
m_lifetime
Time ns3::flame::FlameRtable::m_lifetime private
Lifetime parameter.
Definition at line 134 of file flame-rtable.h.
Referenced by AddPath(), and GetTypeId().
m_routes
std::map<Mac48Address, Route> ns3::flame::FlameRtable::m_routes private
List of routes.
Definition at line 136 of file flame-rtable.h.
Referenced by AddPath(), DoDispose(), and Lookup().
MAX_COST
const uint32_t ns3::flame::FlameRtable::MAX_COST = 0xff static
Maximum (the best?) path cost.
Definition at line 42 of file flame-rtable.h.
Referenced by ns3::flame::FlameRtable::LookupResult::IsValid().
The documentation for this class was generated from the following files:
src/mesh/model/flame/flame-rtable.h
src/mesh/model/flame/flame-rtable.cc