ns-3: ns3::int64x64::test::Int64x64InvertTestCase Class Reference
ns3::int64x64::test::Int64x64InvertTestCase Class Reference
Public Member Functions
Int64x64InvertTestCase ()
void Check (const int64_t factor)
void CheckCase (const uint64_t factor, const int64x64_t result, const int64x64_t expect, const std::string &msg, const double tolerance=0)
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 850 of file int64x64-test-suite.cc.
Constructor & Destructor Documentation
Int64x64InvertTestCase()
ns3::int64x64::test::Int64x64InvertTestCase::Int64x64InvertTestCase ()
Definition at line 862 of file int64x64-test-suite.cc.
Member Function Documentation
Check()
void ns3::int64x64::test::Int64x64InvertTestCase::Check (const int64_t factor)
Definition at line 895 of file int64x64-test-suite.cc.
References CheckCase(), ns3::int64x64_t::implementation, ns3::int64x64_t::Invert(), ns3::int64x64_t::ld_impl, and ns3::int64x64_t::MulByInvert().
Referenced by DoRun().
CheckCase()
void ns3::int64x64::test::Int64x64InvertTestCase::CheckCase (const uint64_t factor, const int64x64_t result, const int64x64_t expect, const std::string & msg, const double tolerance = 0)
Definition at line 866 of file int64x64-test-suite.cc.
References ns3::Abs(), ns3::TestCase::GetName(), ns3::TestCase::GetParent(), and NS_TEST_ASSERT_MSG_EQ_TOL.
Referenced by Check().
DoRun()
void ns3::int64x64::test::Int64x64InvertTestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 927 of file int64x64-test-suite.cc.
References Check(), ns3::TestCase::GetName(), and ns3::TestCase::GetParent().
The documentation for this class was generated from the following file:
src/core/test/int64x64-test-suite.cc