ns-3: Ns3TcpCwndTestCase2 Class Reference
Ns3TcpCwndTestCase2 Class Reference
Classes
class CwndEvent
Public Member Functions
Ns3TcpCwndTestCase2 ()
virtual ~Ns3TcpCwndTestCase2 ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CwndChange (uint32_t oldCwnd, uint32_t newCwnd)
void CwndChangeNotInflated (uint32_t oldCwnd, uint32_t newCwnd)
virtual void DoRun (void)
Implementation to actually run this TestCase.
void VerifyCwndRun (uint32_t beginIdx, uint32_t endIdx, uint32_t initialCwnd, uint32_t mss)
Private Attributes
TestVectors< CwndEvent > m_responses
bool m_writeResults
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 391 of file ns3tcp-cwnd-test-suite.cc.
Constructor & Destructor Documentation
Ns3TcpCwndTestCase2()
Ns3TcpCwndTestCase2::Ns3TcpCwndTestCase2 ()
Definition at line 414 of file ns3tcp-cwnd-test-suite.cc.
~Ns3TcpCwndTestCase2()
Ns3TcpCwndTestCase2::~Ns3TcpCwndTestCase2 () virtual
Definition at line 420 of file ns3tcp-cwnd-test-suite.cc.
Member Function Documentation
CwndChange()
void Ns3TcpCwndTestCase2::CwndChange (uint32_t oldCwnd, uint32_t newCwnd) private
Definition at line 425 of file ns3tcp-cwnd-test-suite.cc.
References Ns3TcpCwndTestCase2::CwndEvent::m_oldCwnd, m_responses, ns3::Now(), NS_LOG_DEBUG, and aloha::S.
Referenced by DoRun().
CwndChangeNotInflated()
void Ns3TcpCwndTestCase2::CwndChangeNotInflated (uint32_t oldCwnd, uint32_t newCwnd) private
Definition at line 437 of file ns3tcp-cwnd-test-suite.cc.
References m_responses, ns3::Now(), NS_LOG_DEBUG, and aloha::S.
Referenced by DoRun().
DoRun()
void Ns3TcpCwndTestCase2::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 443 of file ns3tcp-cwnd-test-suite.cc.
References ns3::NodeContainer::Add(), ns3::Node::AddApplication(), ns3::Ipv4AddressHelper::Assign(), ns3::NodeContainer::Create(), CwndChange(), CwndChangeNotInflated(), ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::PointToPointHelper::Install(), ns3::InternetStackHelper::InstallAll(), Ns3TcpCwndTestCase2::CwndEvent::m_newCwnd, m_responses, m_writeResults, ns3::MakeCallback(), max, ns3::MilliSeconds(), n1n2, n2n3, NS_LOG_DEBUG, NS_TEST_ASSERT_MSG_EQ, ns3::PACKETS, first::pointToPoint, ns3::Seconds(), ns3::ObjectBase::SetAttribute(), ns3::Ipv4AddressHelper::SetBase(), ns3::PointToPointHelper::SetChannelAttribute(), ns3::Config::SetDefault(), ns3::PointToPointHelper::SetDeviceAttribute(), ns3::Application::SetStartTime(), ns3::Application::SetStopTime(), SimpleSource::Setup(), sink, ns3::ApplicationContainer::Start(), ns3::ApplicationContainer::Stop(), ns3::ObjectBase::TraceConnectWithoutContext(), ns3::TrafficControlHelper::Uninstall(), and VerifyCwndRun().
VerifyCwndRun()
void Ns3TcpCwndTestCase2::VerifyCwndRun (uint32_t beginIdx, uint32_t endIdx, uint32_t initialCwnd, uint32_t mss) private
Definition at line 601 of file ns3tcp-cwnd-test-suite.cc.
References Ns3TcpCwndTestCase2::CwndEvent::m_newCwnd, m_responses, and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
Member Data Documentation
m_responses
TestVectors<CwndEvent> Ns3TcpCwndTestCase2::m_responses private
Definition at line 408 of file ns3tcp-cwnd-test-suite.cc.
Referenced by CwndChange(), CwndChangeNotInflated(), DoRun(), and VerifyCwndRun().
m_writeResults
bool Ns3TcpCwndTestCase2::m_writeResults private
Definition at line 400 of file ns3tcp-cwnd-test-suite.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/test/ns3tcp/ns3tcp-cwnd-test-suite.cc