ns-3: ns3::NixVector Class Reference
ns3::NixVector Class Reference
Network » Packet
Neighbor-index data structure for nix-vector routing.
#include "nix-vector.h"
Public Member Functions
NixVector ()
NixVector (const NixVector &o)
~NixVector ()
void AddNeighborIndex (uint32_t newBits, uint32_t numberOfBits)
uint32_t BitCount (uint32_t numberOfNeighbors) const
Ptr< NixVector > Copy (void) const
uint32_t Deserialize (const uint32_t *buffer, uint32_t size)
uint32_t ExtractNeighborIndex (uint32_t numberOfBits)
uint32_t GetRemainingBits (void)
uint32_t GetSerializedSize (void) const
NixVector & operator= (const NixVector &o)
uint32_t Serialize (uint32_t *buffer, uint32_t maxSize) const
Public Member Functions inherited from ns3::SimpleRefCount< NixVector >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Types
typedef std::vector< uint32_t > NixBits_t
Typedef: the NixVector bits storage.
Private Member Functions
void DumpNixVector (std::ostream &os) const
Print the NixVector.
void PrintDec2BinNix (uint32_t decimalNum, uint32_t bitCount, std::ostream &os) const
Internal for pretty printing of nix-vector (no fill)
void PrintDec2BinNixFill (uint32_t decimalNum, uint32_t bitCount, std::ostream &os) const
Internal for pretty printing of nix-vector (fill)
Private Attributes
uint32_t m_currentVectorBitSize
For tracking how many bits we have used in the current vector entry.
NixBits_t m_nixVector
the actual nix-vector
uint32_t m_totalBitSize
A counter of how total bits are in the nix-vector.
uint32_t m_used
For tracking where we are in the nix-vector.
Friends
std::ostream & operator<< (std::ostream &os, const NixVector &nix)
Stream insertion operator.
Detailed Description
Neighbor-index data structure for nix-vector routing.
This data structure holds a vector of "neighbor-indexes" for a simulation specific routing protocol, nix-vector routing. Theses neighbor-indexes correspond to the net-device which a node should use to route a packet. A nix-vector is built (or fetched from a cache) on-demand. The nix-vector is transmitted with the packet, and along each hop of the route, the current node extracts the appropriate neighbor-index and routes the packet.
Internal:
The implementation of NixVector uses a vector to store the neighbor-indexes. Each entry in the vector is 32 bits long and can store multiple neighbor-indexes. A fair amount of bit manipulation is used to store these neighbor-indexes efficiently. A vector is used so that the nix-vector can grow arbitrarily if the topology and route requires a large number of neighbor-indexes.
As the nix-vector travels along the route, an internal private member variable keeps track of how many bits have been used. At a particular node, the nix-vector is used to return the next neighbor-index. This neighbor-index is used to determine which net-device to use. The number of bits used would then be incremented accordingly, and the packet would be routed.
Definition at line 63 of file nix-vector.h.
Member Typedef Documentation
NixBits_t
typedef std::vector<uint32_t> ns3::NixVector::NixBits_t private
Typedef: the NixVector bits storage.
Definition at line 156 of file nix-vector.h.
Constructor & Destructor Documentation
NixVector() [1/2]
ns3::NixVector::NixVector ()
Definition at line 32 of file nix-vector.cc.
References m_nixVector, and NS_LOG_FUNCTION.
~NixVector()
ns3::NixVector::~NixVector ()
Definition at line 43 of file nix-vector.cc.
References NS_LOG_FUNCTION.
NixVector() [2/2]
ns3::NixVector::NixVector (const NixVector & o)
Parameters
o the NixVector to copy to a new NixVector using a constructor
Definition at line 48 of file nix-vector.cc.
Member Function Documentation
AddNeighborIndex()
void ns3::NixVector::AddNeighborIndex (uint32_t newBits, uint32_t numberOfBits)
Parameters
newBits the neighbor-index to be added to the vector
numberOfBits the number of bits that newBits contains
Adds the neighbor index to the vector using a fair amount of bit manipulation to pack everything in efficiently.
Note: This function assumes that the number of bits to be added is always less than or equal to 32, ie., you can only span one entry of a nix-vector at a time. This is reasonable, since 32 bits gives you 2^32 possible neighbors.
Definition at line 88 of file nix-vector.cc.
References m_currentVectorBitSize, m_nixVector, m_totalBitSize, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
BitCount()
uint32_t ns3::NixVector::BitCount (uint32_t numberOfNeighbors) const
Returns
number of bits of numberOfNeighbors
Parameters
numberOfNeighbors the total number of neighbors
This function is used to determine the number of bits of numberOfNeighbors so that this value can be passed in to AddNeighborIndex or ExtractNeighborIndex.
Definition at line 365 of file nix-vector.cc.
References NS_LOG_FUNCTION.
Referenced by DumpNixVector().
Copy()
Ptr< NixVector > ns3::NixVector::Copy (void) const
Returns
a copy of this nix-vector
Definition at line 71 of file nix-vector.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::Packet::Packet(), and ns3::Packet::operator=().
Deserialize()
uint32_t ns3::NixVector::Deserialize (const uint32_t * buffer, uint32_t size)
Returns
zero if a complete nix-vector is not deserialized
Parameters
buffer points to buffer for deserialization
size number of bytes to deserialize
The raw character buffer containing all the nix-vector information is deserialized into this nix-vector.
Definition at line 282 of file nix-vector.cc.
References m_currentVectorBitSize, m_nixVector, m_totalBitSize, m_used, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::Packet::Deserialize().
DumpNixVector()
void ns3::NixVector::DumpNixVector (std::ostream & os) const private
Print the NixVector.
Parameters
os the output stream
Definition at line 319 of file nix-vector.cc.
References BitCount(), m_nixVector, m_totalBitSize, NS_LOG_FUNCTION, PrintDec2BinNix(), and PrintDec2BinNixFill().
Referenced by ns3::operator<<().
ExtractNeighborIndex()
uint32_t ns3::NixVector::ExtractNeighborIndex (uint32_t numberOfBits)
Returns
the neighbor index
Parameters
numberOfBits the number of bits to extract from the vector
Extracts the number of bits specified from the vector and returns the value extracted
Note: This function assumes that the number of bits to be extracted is always less than or equal to 32, ie., you can only span one entry of a nix-vector at a time. This is reasonable, since 32 bits gives you 2^32 possible neighbors.
Definition at line 160 of file nix-vector.cc.
References GetRemainingBits(), m_nixVector, m_used, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
GetRemainingBits()
uint32_t ns3::NixVector::GetRemainingBits (void)
Returns
number of bits remaining in the nix-vector (ie m_total - m_used)
Definition at line 357 of file nix-vector.cc.
References m_totalBitSize, m_used, and NS_LOG_FUNCTION.
Referenced by ExtractNeighborIndex().
GetSerializedSize()
uint32_t ns3::NixVector::GetSerializedSize (void) const
Returns
the number of bytes required for serialization
Definition at line 214 of file nix-vector.cc.
References m_currentVectorBitSize, m_nixVector, m_totalBitSize, m_used, and NS_LOG_FUNCTION.
Referenced by ns3::Packet::GetSerializedSize(), and ns3::Packet::Serialize().
operator=()
NixVector & ns3::NixVector::operator= (const NixVector & o)
Returns
a reference to the assignee
Parameters
o the NixVector to copy to a new NixVector using the equals operator
Definition at line 57 of file nix-vector.cc.
References m_currentVectorBitSize, m_nixVector, m_totalBitSize, and m_used.
PrintDec2BinNix()
void ns3::NixVector::PrintDec2BinNix (uint32_t decimalNum, uint32_t bitCount, std::ostream & os) const private
Internal for pretty printing of nix-vector (no fill)
Parameters
decimalNum decimal divider
bitCount bit counter
os output stream
Definition at line 388 of file nix-vector.cc.
References NS_LOG_FUNCTION.
Referenced by DumpNixVector().
PrintDec2BinNixFill()
void ns3::NixVector::PrintDec2BinNixFill (uint32_t decimalNum, uint32_t bitCount, std::ostream & os) const private
Internal for pretty printing of nix-vector (fill)
Parameters
decimalNum decimal divider
bitCount bit counter
os output stream
Definition at line 415 of file nix-vector.cc.
References NS_LOG_FUNCTION.
Referenced by DumpNixVector().
Serialize()
uint32_t ns3::NixVector::Serialize (uint32_t * buffer, uint32_t maxSize) const
Returns
zero if buffer not large enough
Parameters
buffer points to serialization buffer
maxSize max number of bytes to write
This nix-vector is serialized into the raw character buffer parameter.
Definition at line 225 of file nix-vector.cc.
References m_currentVectorBitSize, m_nixVector, m_totalBitSize, m_used, and NS_LOG_FUNCTION.
Referenced by ns3::Packet::Serialize().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const NixVector & nix) friend
Stream insertion operator.
Parameters
os the stream
nix the Nixvector
Returns
a reference to the stream
Definition at line 81 of file nix-vector.cc.
Member Data Documentation
m_currentVectorBitSize
uint32_t ns3::NixVector::m_currentVectorBitSize private
For tracking how many bits we have used in the current vector entry.
need this in order to expand the vector passed 32bits
Definition at line 184 of file nix-vector.h.
Referenced by AddNeighborIndex(), Deserialize(), GetSerializedSize(), operator=(), and Serialize().
m_nixVector
NixBits_t ns3::NixVector::m_nixVector private
the actual nix-vector
Definition at line 175 of file nix-vector.h.
Referenced by NixVector(), AddNeighborIndex(), Deserialize(), DumpNixVector(), ExtractNeighborIndex(), GetSerializedSize(), operator=(), and Serialize().
m_totalBitSize
uint32_t ns3::NixVector::m_totalBitSize private
A counter of how total bits are in the nix-vector.
Definition at line 190 of file nix-vector.h.
Referenced by AddNeighborIndex(), Deserialize(), DumpNixVector(), GetRemainingBits(), GetSerializedSize(), operator=(), and Serialize().
m_used
uint32_t ns3::NixVector::m_used private
For tracking where we are in the nix-vector.
Definition at line 176 of file nix-vector.h.
Referenced by Deserialize(), ExtractNeighborIndex(), GetRemainingBits(), GetSerializedSize(), operator=(), and Serialize().
The documentation for this class was generated from the following files:
src/network/model/nix-vector.h
src/network/model/nix-vector.cc