ns-3: ns3::MpiReceiver Class Reference
ns3::MpiReceiver Class Reference
MPI Distributed Simulation
Class to aggregate to a NetDevice if it supports MPI capability.
#include "mpi-receiver.h"
Public Member Functions
virtual ~MpiReceiver ()
void Receive (Ptr< Packet > p)
Direct an incoming packet to the device Receive() method.
void SetReceiveCallback (Callback< void, Ptr< Packet > > callback)
Set the receive callback to get packets to net devices.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual void DoDispose (void)
Destructor implementation.
Private Attributes
Callback< void, Ptr< Packet > > m_rxCallback
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Class to aggregate to a NetDevice if it supports MPI capability.
MpiInterface::ReceiveMessages () needs to send packets to a NetDevice Receive() method. Since each NetDevice's Receive() method is specific to the derived class, and since we do not know whether such a NetDevice is MPI-capable, we aggregate one of these objects to each MPI-capable device. In addition, we must hook up a NetDevice::Receive() method to the callback. So the two steps to enable MPI capability are to aggregate this object to a NetDevice, and to set the callback.
Definition at line 42 of file mpi-receiver.h.
Constructor & Destructor Documentation
~MpiReceiver()
ns3::MpiReceiver::~MpiReceiver () virtual
Definition at line 33 of file mpi-receiver.cc.
Member Function Documentation
DoDispose()
void ns3::MpiReceiver::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 51 of file mpi-receiver.cc.
References m_rxCallback.
GetTypeId()
TypeId ns3::MpiReceiver::GetTypeId (void) static
Definition at line 24 of file mpi-receiver.cc.
References ns3::TypeId::SetParent().
Receive()
void ns3::MpiReceiver::Receive (Ptr< Packet > p)
Direct an incoming packet to the device Receive() method.
Parameters
p Packet to receive
Definition at line 44 of file mpi-receiver.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_rxCallback, and NS_ASSERT.
Referenced by ns3::GrantedTimeWindowMpiInterface::ReceiveMessages(), and ns3::NullMessageMpiInterface::ReceiveMessages().
SetReceiveCallback()
void ns3::MpiReceiver::SetReceiveCallback (Callback< void, Ptr< Packet > > callback)
Set the receive callback to get packets to net devices.
Parameters
callback the callback itself
Definition at line 38 of file mpi-receiver.cc.
References m_rxCallback.
Member Data Documentation
m_rxCallback
Callback<void, Ptr<Packet> > ns3::MpiReceiver::m_rxCallback private
Definition at line 61 of file mpi-receiver.h.
Referenced by DoDispose(), Receive(), and SetReceiveCallback().
The documentation for this class was generated from the following files:
src/mpi/model/mpi-receiver.h
src/mpi/model/mpi-receiver.cc