ns-3: ns3::lorawan::NetworkServerHelper Class Reference
ns3::lorawan::NetworkServerHelper Class Reference
This class can install Network Server applications on multiple nodes at once.
#include "network-server-helper.h"
Public Member Functions
NetworkServerHelper ()
~NetworkServerHelper ()
void EnableAdr (bool enableAdr)
Enable (true) or disable (false) the ADR component in the Network Server created by this helper.
ApplicationContainer Install (NodeContainer c)
ApplicationContainer Install (Ptr< Node > node)
void SetAdr (std::string type)
Set the ADR implementation to use in the Network Server created by this helper.
void SetAttribute (std::string name, const AttributeValue &value)
void SetEndDevices (NodeContainer endDevices)
Set which end devices will be managed by this NS.
void SetGateways (NodeContainer gateways)
Set which gateways will need to be connected to this NS.
Private Member Functions
void InstallComponents (Ptr< NetworkServer > netServer)
Ptr< Application > InstallPriv (Ptr< Node > node)
Private Attributes
bool m_adrEnabled
ObjectFactory m_adrSupportFactory
NodeContainer m_endDevices
Set of endDevices to connect to this NS.
ObjectFactory m_factory
NodeContainer m_gateways
Set of gateways to connect to this NS.
PointToPointHelper p2pHelper
Helper to create PointToPoint links.
Detailed Description
This class can install Network Server applications on multiple nodes at once.
Definition at line 41 of file network-server-helper.h.
Constructor & Destructor Documentation
NetworkServerHelper()
ns3::lorawan::NetworkServerHelper::NetworkServerHelper ()
Definition at line 35 of file network-server-helper.cc.
References m_factory, p2pHelper, SetAdr(), ns3::PointToPointHelper::SetChannelAttribute(), ns3::PointToPointHelper::SetDeviceAttribute(), and ns3::ObjectFactory::SetTypeId().
~NetworkServerHelper()
ns3::lorawan::NetworkServerHelper::~NetworkServerHelper ()
Definition at line 43 of file network-server-helper.cc.
Member Function Documentation
EnableAdr()
void ns3::lorawan::NetworkServerHelper::EnableAdr (bool enableAdr)
Enable (true) or disable (false) the ADR component in the Network Server created by this helper.
Definition at line 125 of file network-server-helper.cc.
References m_adrEnabled, and NS_LOG_FUNCTION.
Install() [1/2]
ApplicationContainer ns3::lorawan::NetworkServerHelper::Install (NodeContainer c)
Definition at line 72 of file network-server-helper.cc.
References ns3::ApplicationContainer::Add(), ns3::NodeContainer::Begin(), ns3::NodeContainer::End(), and InstallPriv().
Referenced by ns3::lorawan::CreateNetworkServer().
Install() [2/2]
ApplicationContainer ns3::lorawan::NetworkServerHelper::Install (Ptr< Node > node)
Definition at line 66 of file network-server-helper.cc.
References InstallPriv().
InstallComponents()
void ns3::lorawan::NetworkServerHelper::InstallComponents (Ptr< NetworkServer > netServer) private
Definition at line 142 of file network-server-helper.cc.
References ns3::ObjectFactory::Create(), m_adrEnabled, m_adrSupportFactory, and NS_LOG_FUNCTION.
Referenced by InstallPriv().
InstallPriv()
Ptr< Application > ns3::lorawan::NetworkServerHelper::InstallPriv (Ptr< Node > node) private
Definition at line 84 of file network-server-helper.cc.
References ns3::Node::AddApplication(), ns3::NodeContainer::Begin(), ns3::ObjectFactory::Create(), ns3::NodeContainer::End(), ns3::NetDeviceContainer::Get(), ns3::Node::GetDevice(), ns3::Node::GetNDevices(), ns3::PointToPointHelper::Install(), InstallComponents(), m_endDevices, m_factory, m_gateways, ns3::MakeCallback(), NS_LOG_FUNCTION, p2pHelper, and ns3::lorawan::NetworkServer::Receive().
Referenced by Install().
SetAdr()
void ns3::lorawan::NetworkServerHelper::SetAdr (std::string type)
Set the ADR implementation to use in the Network Server created by this helper.
Definition at line 133 of file network-server-helper.cc.
References m_adrSupportFactory, NS_LOG_FUNCTION, and ns3::ObjectFactory::SetTypeId().
Referenced by NetworkServerHelper().
SetAttribute()
void ns3::lorawan::NetworkServerHelper::SetAttribute (std::string name, const AttributeValue & value)
Definition at line 48 of file network-server-helper.cc.
References m_factory, and ns3::ObjectFactory::Set().
SetEndDevices()
void ns3::lorawan::NetworkServerHelper::SetEndDevices (NodeContainer endDevices)
Set which end devices will be managed by this NS.
Definition at line 60 of file network-server-helper.cc.
References m_endDevices.
Referenced by ns3::lorawan::CreateNetworkServer().
SetGateways()
void ns3::lorawan::NetworkServerHelper::SetGateways (NodeContainer gateways)
Set which gateways will need to be connected to this NS.
Definition at line 54 of file network-server-helper.cc.
References m_gateways.
Referenced by ns3::lorawan::CreateNetworkServer().
Member Data Documentation
m_adrEnabled
bool ns3::lorawan::NetworkServerHelper::m_adrEnabled private
Definition at line 88 of file network-server-helper.h.
Referenced by EnableAdr(), and InstallComponents().
m_adrSupportFactory
ObjectFactory ns3::lorawan::NetworkServerHelper::m_adrSupportFactory private
Definition at line 90 of file network-server-helper.h.
Referenced by InstallComponents(), and SetAdr().
m_endDevices
NodeContainer ns3::lorawan::NetworkServerHelper::m_endDevices private
Set of endDevices to connect to this NS.
Definition at line 84 of file network-server-helper.h.
Referenced by InstallPriv(), and SetEndDevices().
m_factory
ObjectFactory ns3::lorawan::NetworkServerHelper::m_factory private
Definition at line 80 of file network-server-helper.h.
Referenced by NetworkServerHelper(), InstallPriv(), and SetAttribute().
m_gateways
NodeContainer ns3::lorawan::NetworkServerHelper::m_gateways private
Set of gateways to connect to this NS.
Definition at line 82 of file network-server-helper.h.
Referenced by InstallPriv(), and SetGateways().
p2pHelper
PointToPointHelper ns3::lorawan::NetworkServerHelper::p2pHelper private
Helper to create PointToPoint links.
Definition at line 86 of file network-server-helper.h.
Referenced by NetworkServerHelper(), and InstallPriv().
The documentation for this class was generated from the following files:
src/lorawan/helper/network-server-helper.h
src/lorawan/helper/network-server-helper.cc