ns-3: ns3::SQLiteOutput Class Reference
ns3::SQLiteOutput Class Reference
Internet » internet module tests | Test suites
A C++ interface towards an SQLITE database.
#include "sqlite-output.h"
Public Member Functions
SQLiteOutput (const std::string &name, const std::string &semName)
SQLiteOutput constructor.
~SQLiteOutput ()
Destructor.
template<>
bool Bind (sqlite3_stmt *stmt, int pos, const double &value) const
template<>
bool Bind (sqlite3_stmt *stmt, int pos, const int &value) const
template<>
bool Bind (sqlite3_stmt *stmt, int pos, const long &value) const
template<>
bool Bind (sqlite3_stmt *stmt, int pos, const long long &value) const
template<>
bool Bind (sqlite3_stmt *stmt, int pos, const std::string &value) const
template<typename T >
bool Bind (sqlite3_stmt *stmt, int pos, const T &value) const
Bind a value to a sqlite statement.
template<>
bool Bind (sqlite3_stmt *stmt, int pos, const Time &value) const
template<>
bool Bind (sqlite3_stmt *stmt, int pos, const uint16_t &value) const
template<>
bool Bind (sqlite3_stmt *stmt, int pos, const uint32_t &value) const
template<>
bool Bind (sqlite3_stmt *stmt, int pos, const uint8_t &value) const
template<>
int RetrieveColumn (sqlite3_stmt *stmt, int pos) const
template<typename T >
T RetrieveColumn (sqlite3_stmt *stmt, int pos) const
Retrieve a value from an executed statement.
void SetJournalInMemory ()
Instruct SQLite to store the journal in memory.
bool SpinExec (const std::string &cmd) const
Execute a command until the return value is OK or an ERROR.
bool SpinExec (sqlite3_stmt *stmt) const
Execute a command until the return value is OK or an ERROR.
bool SpinPrepare (sqlite3_stmt **stmt, const std::string &cmd) const
Prepare a statement.
bool WaitExec (const std::string &cmd) const
Execute a command, waiting on a system semaphore.
bool WaitExec (sqlite3_stmt *stmt) const
Execute a command, waiting on a system semaphore.
bool WaitPrepare (sqlite3_stmt **stmt, const std::string &cmd) const
Prepare a statement, waiting on a system semaphore.
Public Member Functions inherited from ns3::SimpleRefCount< SQLiteOutput >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Static Public Member Functions
static int SpinFinalize (sqlite3_stmt *stmt)
Finalize a statement until the result is ok or an error.
static int SpinReset (sqlite3_stmt *stmt)
Reset a statement until the result is ok or an error.
static int SpinStep (sqlite3_stmt *stmt)
Execute a step operation on a statement until the result is ok or an error.
Protected Member Functions
int WaitExec (sqlite3 *db, const std::string &cmd) const
Execute a command, waiting on a system semaphore.
int WaitExec (sqlite3 *db, sqlite3_stmt *stmt) const
Execute a statement, waiting on a system semaphore.
int WaitPrepare (sqlite3 *db, sqlite3_stmt **stmt, const std::string &cmd) const
Prepare a statement, waiting on a system semaphore.
Static Protected Member Functions
static bool CheckError (sqlite3 *db, int rc, const std::string &cmd, sem_t *sem, bool hardExit)
Check any error in the db.
static void Error (sqlite3 *db, const std::string &cmd)
Fail, printing an error message from sqlite.
static int SpinExec (sqlite3 *db, const std::string &cmd)
Execute a command ignoring concurrency problems, retrying instead.
static int SpinExec (sqlite3 *db, sqlite3_stmt *stmt)
static int SpinPrepare (sqlite3 *db, sqlite3_stmt **stmt, const std::string &cmd)
Preparing a command ignoring concurrency problems, retrying instead.
Private Attributes
sqlite3 * m_db
Database pointer.
std::string m_dBname
Database name.
std::string m_semName
System semaphore name.
Detailed Description
A C++ interface towards an SQLITE database.
The class is able to execute commands, and retrieve results, from an SQLITE database. The methods with the "Spin" prefix, in case of concurrent access to the database, will spin until the operation is applied. The methods with the "Wait" prefix will wait on a system semaphore.
If you run multiple simulations that write on the same database, it is recommended to use the "Wait" prefixed methods. Otherwise, if the access to the database is unique, using "Spin" methods will speed up database access.
The database is opened in the constructor, and closed in the deconstructor.
Definition at line 50 of file sqlite-output.h.
Constructor & Destructor Documentation
SQLiteOutput()
ns3::SQLiteOutput::SQLiteOutput (const std::string & name, const std::string & semName)
SQLiteOutput constructor.
Parameters
name database name
semName system semaphore name
Definition at line 31 of file sqlite-output.cc.
References m_db, and NS_ABORT_MSG_UNLESS.
~SQLiteOutput()
ns3::SQLiteOutput::~SQLiteOutput ()
Destructor.
Definition at line 38 of file sqlite-output.cc.
References m_db, and NS_ABORT_MSG_UNLESS.
Member Function Documentation
Bind() [1/10]
template<> bool ns3::SQLiteOutput::Bind (sqlite3_stmt * stmt, int pos, const double & value) const
Definition at line 145 of file sqlite-output.cc.
Bind() [2/10]
template<> bool ns3::SQLiteOutput::Bind (sqlite3_stmt * stmt, int pos, const int & value) const
Definition at line 211 of file sqlite-output.cc.
Bind() [3/10]
template<> bool ns3::SQLiteOutput::Bind (sqlite3_stmt * stmt, int pos, const long & value) const
Definition at line 167 of file sqlite-output.cc.
Bind() [4/10]
template<> bool ns3::SQLiteOutput::Bind (sqlite3_stmt * stmt, int pos, const long long & value) const
Definition at line 178 of file sqlite-output.cc.
Bind() [5/10]
template<> bool ns3::SQLiteOutput::Bind (sqlite3_stmt * stmt, int pos, const std::string & value) const
Definition at line 222 of file sqlite-output.cc.
Bind() [6/10]
template<typename T > bool ns3::SQLiteOutput::Bind (sqlite3_stmt * stmt, int pos, const T & value) const
Bind a value to a sqlite statement.
Parameters
stmt Sqlite statement
pos Position of the bind argument inside the statement
value Value to bind
Definition at line 123 of file sqlite-output.cc.
References NS_FATAL_ERROR, and NS_UNUSED.
Bind() [7/10]
template<> bool ns3::SQLiteOutput::Bind (sqlite3_stmt * stmt, int pos, const Time & value) const
Definition at line 134 of file sqlite-output.cc.
References ns3::Time::GetSeconds().
Bind() [8/10]
template<> bool ns3::SQLiteOutput::Bind (sqlite3_stmt * stmt, int pos, const uint16_t & value) const
Definition at line 189 of file sqlite-output.cc.
Bind() [9/10]
template<> bool ns3::SQLiteOutput::Bind (sqlite3_stmt * stmt, int pos, const uint32_t & value) const
Definition at line 156 of file sqlite-output.cc.
Bind() [10/10]
template<> bool ns3::SQLiteOutput::Bind (sqlite3_stmt * stmt, int pos, const uint8_t & value) const
Definition at line 200 of file sqlite-output.cc.
CheckError()
bool ns3::SQLiteOutput::CheckError (sqlite3 * db, int rc, const std::string & cmd, sem_t * sem, bool hardExit) static protected
Check any error in the db.
Parameters
db Database
rc Sqlite return code
cmd Command
sem System semaphore
hardExit if true, will exit the program
Returns
true in case of error, false otherwise
Definition at line 327 of file sqlite-output.cc.
References second::cmd, and Error().
Referenced by SpinExec(), WaitExec(), and WaitPrepare().
Error()
void ns3::SQLiteOutput::Error (sqlite3 * db, const std::string & cmd) static protected
Fail, printing an error message from sqlite.
Parameters
db Database
cmd Command
Definition at line 321 of file sqlite-output.cc.
References second::cmd, and NS_ABORT_MSG.
Referenced by CheckError().
RetrieveColumn() [1/2]
template<> double ns3::SQLiteOutput::RetrieveColumn (sqlite3_stmt * stmt, int pos) const
Definition at line 102 of file sqlite-output.cc.
RetrieveColumn() [2/2]
template<typename T > T ns3::SQLiteOutput::RetrieveColumn (sqlite3_stmt * stmt, int pos) const
Retrieve a value from an executed statement.
Parameters
stmt sqlite statement
pos Column position
Definition at line 93 of file sqlite-output.cc.
References NS_FATAL_ERROR, and NS_UNUSED.
SetJournalInMemory()
void ns3::SQLiteOutput::SetJournalInMemory ()
Instruct SQLite to store the journal in memory.
May lead to data losses in case of unexpected program exits.
Definition at line 47 of file sqlite-output.cc.
References NS_LOG_FUNCTION, and SpinExec().
SpinExec() [1/4]
bool ns3::SQLiteOutput::SpinExec (const std::string & cmd) const
Execute a command until the return value is OK or an ERROR.
Ignore errors due to concurrency, the method will repeat the command instead
Parameters
cmd Command
Returns
true in case of success
Definition at line 54 of file sqlite-output.cc.
References second::cmd, and m_db.
Referenced by SetJournalInMemory(), and SpinExec().
SpinExec() [2/4]
int ns3::SQLiteOutput::SpinExec (sqlite3 * db, const std::string & cmd) static protected
Execute a command ignoring concurrency problems, retrying instead.
Parameters
db Database
cmd Command
Returns
Sqlite error code
Definition at line 351 of file sqlite-output.cc.
References CheckError(), second::cmd, SpinFinalize(), SpinPrepare(), and SpinStep().
SpinExec() [3/4]
int ns3::SQLiteOutput::SpinExec (sqlite3 * db, sqlite3_stmt * stmt) static protected
Definition at line 377 of file sqlite-output.cc.
References CheckError(), SpinFinalize(), and SpinStep().
SpinExec() [4/4]
bool ns3::SQLiteOutput::SpinExec (sqlite3_stmt * stmt) const
Execute a command until the return value is OK or an ERROR.
Parameters
stmt SQLite statement
Returns
true in case of success
Definition at line 60 of file sqlite-output.cc.
References CheckError(), m_db, and SpinExec().
SpinFinalize()
int ns3::SQLiteOutput::SpinFinalize (sqlite3_stmt * stmt) static
Finalize a statement until the result is ok or an error.
Ignores concurrency errors; it will retry instead of failing.
Parameters
stmt Statement
Returns
Sqlite error code
Definition at line 295 of file sqlite-output.cc.
Referenced by SpinExec(), and WaitExec().
SpinPrepare() [1/2]
int ns3::SQLiteOutput::SpinPrepare (sqlite3 * db, sqlite3_stmt ** stmt, const std::string & cmd) static protected
Preparing a command ignoring concurrency problems, retrying instead.
Parameters
db Database
stmt Statement
cmd Command to prepare
Returns
Sqlite error code
Definition at line 267 of file sqlite-output.cc.
References second::cmd.
SpinPrepare() [2/2]
bool ns3::SQLiteOutput::SpinPrepare (sqlite3_stmt ** stmt, const std::string & cmd) const
Prepare a statement.
Parameters
stmt Sqlite statement
cmd Command to prepare inside the statement
Returns
true in case of success
Definition at line 86 of file sqlite-output.cc.
References second::cmd, and m_db.
Referenced by SpinExec(), and WaitExec().
SpinReset()
int ns3::SQLiteOutput::SpinReset (sqlite3_stmt * stmt) static
Reset a statement until the result is ok or an error.
Ignores concurrency errors: it will retry instead of failing.
Parameters
stmt Statement
Returns
the return code of reset
Definition at line 307 of file sqlite-output.cc.
SpinStep()
int ns3::SQLiteOutput::SpinStep (sqlite3_stmt * stmt) static
Execute a step operation on a statement until the result is ok or an error.
Ignores concurrency errors; it will retry instead of failing.
Parameters
stmt Statement
Returns
Sqlite error core
Definition at line 282 of file sqlite-output.cc.
Referenced by SpinExec(), and WaitExec().
WaitExec() [1/4]
bool ns3::SQLiteOutput::WaitExec (const std::string & cmd) const
Execute a command, waiting on a system semaphore.
Parameters
cmd Command to be executed
Returns
true in case of success
Definition at line 67 of file sqlite-output.cc.
References CheckError(), second::cmd, and m_db.
Referenced by WaitExec().
WaitExec() [2/4]
int ns3::SQLiteOutput::WaitExec (sqlite3 * db, const std::string & cmd) const protected
Execute a command, waiting on a system semaphore.
Parameters
db Database
cmd Command
Returns
Sqlite error code
Definition at line 427 of file sqlite-output.cc.
References CheckError(), second::cmd, m_semName, NS_ABORT_MSG_IF, SpinFinalize(), SpinPrepare(), and SpinStep().
WaitExec() [3/4]
int ns3::SQLiteOutput::WaitExec (sqlite3 * db, sqlite3_stmt * stmt) const protected
Execute a statement, waiting on a system semaphore.
Parameters
db Database
stmt Statement
Returns
Sqlite error code
Definition at line 392 of file sqlite-output.cc.
References CheckError(), m_semName, NS_ABORT_MSG_IF, NS_FATAL_ERROR, SpinFinalize(), and SpinStep().
WaitExec() [4/4]
bool ns3::SQLiteOutput::WaitExec (sqlite3_stmt * stmt) const
Execute a command, waiting on a system semaphore.
Parameters
stmt Sqlite3 statement to be executed
Returns
true in case of success
Definition at line 74 of file sqlite-output.cc.
References m_db, and WaitExec().
WaitPrepare() [1/2]
int ns3::SQLiteOutput::WaitPrepare (sqlite3 * db, sqlite3_stmt ** stmt, const std::string & cmd) const protected
Prepare a statement, waiting on a system semaphore.
Parameters
db Database
stmt Statement
cmd Command to prepare
Returns
Sqlite error code
Definition at line 232 of file sqlite-output.cc.
References CheckError(), second::cmd, m_semName, NS_ABORT_MSG_IF, and NS_FATAL_ERROR.
WaitPrepare() [2/2]
bool ns3::SQLiteOutput::WaitPrepare (sqlite3_stmt ** stmt, const std::string & cmd) const
Prepare a statement, waiting on a system semaphore.
Parameters
stmt Sqlite statement
cmd Command to prepare inside the statement
Returns
true in case of success
Definition at line 80 of file sqlite-output.cc.
References second::cmd, and m_db.
Member Data Documentation
m_db
sqlite3* ns3::SQLiteOutput::m_db private
Initial value:
{
    nullptr
  }
Database pointer.
Definition at line 224 of file sqlite-output.h.
Referenced by SQLiteOutput(), ~SQLiteOutput(), SpinExec(), SpinPrepare(), WaitExec(), and WaitPrepare().
m_dBname
std::string ns3::SQLiteOutput::m_dBname private
Database name.
Definition at line 222 of file sqlite-output.h.
m_semName
std::string ns3::SQLiteOutput::m_semName private
System semaphore name.
Definition at line 223 of file sqlite-output.h.
Referenced by WaitExec(), and WaitPrepare().
The documentation for this class was generated from the following files:
src/stats/model/sqlite-output.h
src/stats/model/sqlite-output.cc