ns-3: ns3::LtePhyTag Class Reference
ns3::LtePhyTag Class Reference
Tag used to define PHY parameters.
#include "lte-phy-tag.h"
Public Member Functions
LtePhyTag ()
Create an empty LtePhyTag.
LtePhyTag (uint16_t cellId)
Create a LtePhyTag with the given RNTI and LC id.
virtual ~LtePhyTag ()
virtual void Deserialize (TagBuffer i)
uint16_t GetCellId () const
Get cell ID.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize () const
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer i) const
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint16_t m_cellId
the cell ID
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Tag used to define PHY parameters.
Definition at line 31 of file lte-phy-tag.h.
Constructor & Destructor Documentation
LtePhyTag() [1/2]
ns3::LtePhyTag::LtePhyTag ()
Create an empty LtePhyTag.
Definition at line 48 of file lte-phy-tag.cc.
LtePhyTag() [2/2]
ns3::LtePhyTag::LtePhyTag (uint16_t cellId)
Create a LtePhyTag with the given RNTI and LC id.
Parameters
cellId the cell ID
Definition at line 52 of file lte-phy-tag.cc.
~LtePhyTag()
ns3::LtePhyTag::~LtePhyTag () virtual
Definition at line 57 of file lte-phy-tag.cc.
Member Function Documentation
Deserialize()
void ns3::LtePhyTag::Deserialize (TagBuffer i) virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 74 of file lte-phy-tag.cc.
References m_cellId, and ns3::TagBuffer::ReadU16().
GetCellId()
uint16_t ns3::LtePhyTag::GetCellId () const
Get cell ID.
Returns
cell ID
Definition at line 86 of file lte-phy-tag.cc.
References m_cellId.
GetInstanceTypeId()
TypeId ns3::LtePhyTag::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 43 of file lte-phy-tag.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::LtePhyTag::GetSerializedSize () const virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 62 of file lte-phy-tag.cc.
GetTypeId()
TypeId ns3::LtePhyTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 32 of file lte-phy-tag.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::LtePhyTag::Print (std::ostream & os) const virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 80 of file lte-phy-tag.cc.
References m_cellId.
Serialize()
void ns3::LtePhyTag::Serialize (TagBuffer i) const virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 68 of file lte-phy-tag.cc.
References m_cellId, and ns3::TagBuffer::WriteU16().
Member Data Documentation
m_cellId
uint16_t ns3::LtePhyTag::m_cellId private
the cell ID
Definition at line 68 of file lte-phy-tag.h.
Referenced by Deserialize(), GetCellId(), Print(), and Serialize().
The documentation for this class was generated from the following files:
src/lte/model/lte-phy-tag.h
src/lte/model/lte-phy-tag.cc