ns-3: ns3::Ipv6ExtensionFragmentHeader Class Reference
ns3::Ipv6ExtensionFragmentHeader Class Reference
Internet » IPv6 classes and sub-modules » IPV6 Header extension system.
Header of IPv6 Extension Fragment.
#include "ipv6-extension-header.h"
Public Member Functions
Ipv6ExtensionFragmentHeader ()
Constructor.
virtual ~Ipv6ExtensionFragmentHeader ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
uint32_t GetIdentification () const
Get the field "Identification".
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
bool GetMoreFragment () const
Get the status of "More Fragment" bit.
uint16_t GetOffset () const
Get the field "Offset".
virtual uint32_t GetSerializedSize () const
Get the serialized size of the packet.
virtual void Print (std::ostream &os) const
Print some information about the packet.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetIdentification (uint32_t identification)
Set the "Identification" field.
void SetMoreFragment (bool moreFragment)
Set the status of "More Fragment" bit.
void SetOffset (uint16_t offset)
Set the "Offset" field.
Public Member Functions inherited from ns3::Ipv6ExtensionHeader
Ipv6ExtensionHeader ()
Constructor.
virtual ~Ipv6ExtensionHeader ()
Destructor.
uint16_t GetLength () const
Get the length of the extension.
uint8_t GetNextHeader () const
Get the next header.
void SetLength (uint16_t length)
brief Set the length of the extension.
void SetNextHeader (uint8_t nextHeader)
Set the "Next header" field.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Ipv6ExtensionHeader
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint32_t m_identification
Identifier of the packet.
uint16_t m_offset
Offset of the fragment and More Fragment bit.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Ipv6ExtensionHeader
uint8_t m_length
The "length" field.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Header of IPv6 Extension Fragment.
Definition at line 337 of file ipv6-extension-header.h.
Constructor & Destructor Documentation
Ipv6ExtensionFragmentHeader()
ns3::Ipv6ExtensionFragmentHeader::Ipv6ExtensionFragmentHeader ()
Constructor.
Definition at line 336 of file ipv6-extension-header.cc.
References ns3::Ipv6ExtensionHeader::m_length.
~Ipv6ExtensionFragmentHeader()
ns3::Ipv6ExtensionFragmentHeader::~Ipv6ExtensionFragmentHeader () virtual
Destructor.
Definition at line 343 of file ipv6-extension-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::Ipv6ExtensionFragmentHeader::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start Buffer iterator
Returns
size of the packet
Reimplemented from ns3::Ipv6ExtensionHeader.
Definition at line 401 of file ipv6-extension-header.cc.
References GetSerializedSize(), m_identification, m_offset, ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadNtohU32(), ns3::Buffer::Iterator::ReadU8(), ns3::Ipv6ExtensionHeader::SetNextHeader(), and visualizer.core::start().
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanNhc().
GetIdentification()
uint32_t ns3::Ipv6ExtensionFragmentHeader::GetIdentification () const
Get the field "Identification".
Returns
the identifier of the fragment
Definition at line 374 of file ipv6-extension-header.cc.
References m_identification.
Referenced by ns3::Ipv6ExtensionFragment::Process().
GetInstanceTypeId()
TypeId ns3::Ipv6ExtensionFragmentHeader::GetInstanceTypeId () const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::Ipv6ExtensionHeader.
Definition at line 331 of file ipv6-extension-header.cc.
References GetTypeId().
GetMoreFragment()
bool ns3::Ipv6ExtensionFragmentHeader::GetMoreFragment () const
Get the status of "More Fragment" bit.
Returns
the status of "More Fragment" bit.
Definition at line 364 of file ipv6-extension-header.cc.
References m_offset.
Referenced by Print(), and ns3::Ipv6ExtensionFragment::Process().
GetOffset()
uint16_t ns3::Ipv6ExtensionFragmentHeader::GetOffset () const
Get the field "Offset".
Returns
the offset of the fragment
Definition at line 354 of file ipv6-extension-header.cc.
References m_offset.
Referenced by Print(), and ns3::Ipv6ExtensionFragment::Process().
GetSerializedSize()
uint32_t ns3::Ipv6ExtensionFragmentHeader::GetSerializedSize () const virtual
Get the serialized size of the packet.
Returns
size
Reimplemented from ns3::Ipv6ExtensionHeader.
Definition at line 385 of file ipv6-extension-header.cc.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanNhc(), Deserialize(), and ns3::Ipv6ExtensionFragment::GetFragments().
GetTypeId()
TypeId ns3::Ipv6ExtensionFragmentHeader::GetTypeId () static
Get the type identificator.
Returns
type identificator
Definition at line 321 of file ipv6-extension-header.cc.
References ns3::TypeId::AddConstructor().
Referenced by GetInstanceTypeId().
Print()
void ns3::Ipv6ExtensionFragmentHeader::Print (std::ostream & os) const virtual
Print some information about the packet.
Parameters
os output stream
Returns
info about this packet
Reimplemented from ns3::Ipv6ExtensionHeader.
Definition at line 379 of file ipv6-extension-header.cc.
References ns3::Ipv6ExtensionHeader::GetLength(), GetMoreFragment(), ns3::Ipv6ExtensionHeader::GetNextHeader(), GetOffset(), and m_identification.
Serialize()
void ns3::Ipv6ExtensionFragmentHeader::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start Buffer iterator
Reimplemented from ns3::Ipv6ExtensionHeader.
Definition at line 390 of file ipv6-extension-header.cc.
References ns3::Ipv6ExtensionHeader::GetNextHeader(), m_identification, m_offset, visualizer.core::start(), ns3::Buffer::Iterator::WriteHtonU16(), ns3::Buffer::Iterator::WriteHtonU32(), and ns3::Buffer::Iterator::WriteU8().
Referenced by ns3::SixLowPanNetDevice::CompressLowPanNhc().
SetIdentification()
void ns3::Ipv6ExtensionFragmentHeader::SetIdentification (uint32_t identification)
Set the "Identification" field.
Parameters
identification the identifier of the fragment
Definition at line 369 of file ipv6-extension-header.cc.
References m_identification.
Referenced by ns3::Ipv6ExtensionFragment::GetFragments().
SetMoreFragment()
void ns3::Ipv6ExtensionFragmentHeader::SetMoreFragment (bool moreFragment)
Set the status of "More Fragment" bit.
Parameters
moreFragment the bit "More Fragment"
Definition at line 359 of file ipv6-extension-header.cc.
References m_offset.
Referenced by ns3::Ipv6ExtensionFragment::GetFragments().
SetOffset()
void ns3::Ipv6ExtensionFragmentHeader::SetOffset (uint16_t offset)
Set the "Offset" field.
Parameters
offset the offset of the fragment
Definition at line 347 of file ipv6-extension-header.cc.
References m_offset.
Referenced by ns3::Ipv6ExtensionFragment::GetFragments().
Member Data Documentation
m_identification
uint32_t ns3::Ipv6ExtensionFragmentHeader::m_identification private
Identifier of the packet.
Definition at line 433 of file ipv6-extension-header.h.
Referenced by Deserialize(), GetIdentification(), Print(), Serialize(), and SetIdentification().
m_offset
uint16_t ns3::Ipv6ExtensionFragmentHeader::m_offset private
Offset of the fragment and More Fragment bit.
Definition at line 428 of file ipv6-extension-header.h.
Referenced by Deserialize(), GetMoreFragment(), GetOffset(), Serialize(), SetMoreFragment(), and SetOffset().
The documentation for this class was generated from the following files:
src/internet/model/ipv6-extension-header.h
src/internet/model/ipv6-extension-header.cc