ns-3: LrWpanErrorDistanceTestCase Class Reference
LrWpanErrorDistanceTestCase Class Reference
LR-WPAN models » LrWpan module tests | Test suites
LrWpan Error Vs Distance Test.
Public Member Functions
LrWpanErrorDistanceTestCase ()
virtual ~LrWpanErrorDistanceTestCase ()
uint32_t GetReceived (void) const
Get the number of received packets.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void Callback (McpsDataIndicationParams params, Ptr< Packet > p)
Function to be called when a packet is received.
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
uint32_t m_received
The number of received packets.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
LrWpan Error Vs Distance Test.
Definition at line 46 of file lr-wpan-error-model-test.cc.
Constructor & Destructor Documentation
LrWpanErrorDistanceTestCase()
LrWpanErrorDistanceTestCase::LrWpanErrorDistanceTestCase ()
Definition at line 89 of file lr-wpan-error-model-test.cc.
~LrWpanErrorDistanceTestCase()
LrWpanErrorDistanceTestCase::~LrWpanErrorDistanceTestCase () virtual
Definition at line 95 of file lr-wpan-error-model-test.cc.
Member Function Documentation
Callback()
void LrWpanErrorDistanceTestCase::Callback (McpsDataIndicationParams params, Ptr< Packet > p) private
Function to be called when a packet is received.
Parameters
params MCPS params.
p The packet.
Definition at line 100 of file lr-wpan-error-model-test.cc.
References m_received.
Referenced by DoRun().
DoRun()
void LrWpanErrorDistanceTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 106 of file lr-wpan-error-model-test.cc.
References ns3::Node::AddDevice(), ns3::LrWpanNetDevice::AssignStreams(), Callback(), third::channel, ns3::LrWpanNetDevice::GetMac(), ns3::LrWpanNetDevice::GetPhy(), GetReceived(), ns3::MakeCallback(), NS_TEST_ASSERT_MSG_EQ, aloha::params, ns3::Seconds(), ns3::LrWpanNetDevice::SetAddress(), ns3::LrWpanNetDevice::SetChannel(), ns3::MobilityModel::SetPosition(), and ns3::SHORT_ADDR.
GetReceived()
uint32_t LrWpanErrorDistanceTestCase::GetReceived (void) const inline
Get the number of received packets.
Returns
The number of received packets.
Definition at line 56 of file lr-wpan-error-model-test.cc.
Referenced by DoRun().
Member Data Documentation
m_received
uint32_t LrWpanErrorDistanceTestCase::m_received private
The number of received packets.
Definition at line 70 of file lr-wpan-error-model-test.cc.
Referenced by Callback().
The documentation for this class was generated from the following file:
src/lr-wpan/test/lr-wpan-error-model-test.cc