ns-3: ns3::VendorSpecificActionHeader Class Reference
ns3::VendorSpecificActionHeader Class Reference
WAVE module
#include "vendor-specific-action.h"
Public Member Functions
VendorSpecificActionHeader (void)
virtual ~VendorSpecificActionHeader (void)
virtual uint32_t Deserialize (Buffer::Iterator start)
uint8_t GetCategory (void) const
the category field shall be CATEGORY_OF_VSA
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
OrganizationIdentifier GetOrganizationIdentifier (void) const
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetOrganizationIdentifier (OrganizationIdentifier oi)
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_category
category
OrganizationIdentifier m_oi
OI.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
See IEEE 802.11-2007 chapter 7.3.1.11 and 7.4.5 also IEEE 802.11p-2010 chapter 7.4.5 Although WifiActionHeader has been defined in wifi mgt-header.h/.cc, it is not a good way to inherit from it or add vendor specific action support. The reason is Action field. Other Action frames contains Action field, and the VSA frame contains OUI or variable OrganizationIdentifier instead of one byte Action field. Header format: | Category | Organization IdentifierType | Vendor Specific content | Octets: 1 j Variable
In ns-3, VSA frame will be divided into VendorSpecificActionHeader vsaHeader and Packet vsc that indicates vendor specific content.
This frame is used by IEEE 1609.4 to send WSA packet of IEEE 1609.3, and if users want to send management information without customized management frames, he can use VSA frames.
Definition at line 155 of file vendor-specific-action.h.
Constructor & Destructor Documentation
VendorSpecificActionHeader()
ns3::VendorSpecificActionHeader::VendorSpecificActionHeader (void)
Definition at line 249 of file vendor-specific-action.cc.
References NS_LOG_FUNCTION.
~VendorSpecificActionHeader()
ns3::VendorSpecificActionHeader::~VendorSpecificActionHeader (void) virtual
Definition at line 256 of file vendor-specific-action.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Deserialize()
uint32_t ns3::VendorSpecificActionHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 327 of file vendor-specific-action.cc.
References ns3::CATEGORY_OF_VSA, ns3::OrganizationIdentifier::Deserialize(), GetSerializedSize(), m_category, m_oi, NS_LOG_FUNCTION, and visualizer.core::start().
GetCategory()
uint8_t ns3::VendorSpecificActionHeader::GetCategory (void) const
the category field shall be CATEGORY_OF_VSA
Definition at line 288 of file vendor-specific-action.cc.
References m_category, and NS_LOG_FUNCTION.
Referenced by ns3::OcbWifiMac::Receive().
GetInstanceTypeId()
TypeId ns3::VendorSpecificActionHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 295 of file vendor-specific-action.cc.
References GetTypeId(), and NS_LOG_FUNCTION.
GetOrganizationIdentifier()
OrganizationIdentifier ns3::VendorSpecificActionHeader::GetOrganizationIdentifier (void) const
Returns
current OrganizationIdentifier of the VSA header
Definition at line 269 of file vendor-specific-action.cc.
References m_oi, and NS_LOG_FUNCTION.
Referenced by ns3::OcbWifiMac::Receive().
GetSerializedSize()
uint32_t ns3::VendorSpecificActionHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 312 of file vendor-specific-action.cc.
References ns3::OrganizationIdentifier::GetSerializedSize(), m_category, m_oi, and NS_LOG_FUNCTION.
Referenced by Deserialize().
GetTypeId()
TypeId ns3::VendorSpecificActionHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 276 of file vendor-specific-action.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::VendorSpecificActionHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 302 of file vendor-specific-action.cc.
References m_category, m_oi, and NS_LOG_FUNCTION.
Serialize()
void ns3::VendorSpecificActionHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 319 of file vendor-specific-action.cc.
References m_category, m_oi, NS_LOG_FUNCTION, ns3::OrganizationIdentifier::Serialize(), and visualizer.core::start().
SetOrganizationIdentifier()
void ns3::VendorSpecificActionHeader::SetOrganizationIdentifier (OrganizationIdentifier oi)
Parameters
oi the OrganizationIdentifier of current VSA header
Definition at line 262 of file vendor-specific-action.cc.
References m_oi, and NS_LOG_FUNCTION.
Referenced by ns3::OcbWifiMac::SendVsc().
Member Data Documentation
m_category
uint8_t ns3::VendorSpecificActionHeader::m_category private
category
Definition at line 187 of file vendor-specific-action.h.
Referenced by Deserialize(), GetCategory(), GetSerializedSize(), Print(), and Serialize().
m_oi
OrganizationIdentifier ns3::VendorSpecificActionHeader::m_oi private
OI.
Definition at line 186 of file vendor-specific-action.h.
Referenced by Deserialize(), GetOrganizationIdentifier(), GetSerializedSize(), Print(), Serialize(), and SetOrganizationIdentifier().
The documentation for this class was generated from the following files:
src/wave/model/vendor-specific-action.h
src/wave/model/vendor-specific-action.cc