ns-3: ns3::BlockAckCache Class Reference
ns3::BlockAckCache Class Reference
Wifi Models
BlockAckCache cache.
#include "block-ack-cache.h"
Public Member Functions
void FillBlockAckBitmap (CtrlBAckResponseHeader *blockAckHeader)
Fill block ack bitmap function.
uint16_t GetWinStart (void) const
When an A-MPDU is received, the window start may change to a new value depending on the sequence number of the received MPDU (standard11n page 134).
void Init (uint16_t winStart, uint16_t winSize)
Initialization function.
void UpdateWithBlockAckReq (uint16_t startingSeq)
Update with block ack request function.
void UpdateWithMpdu (const WifiMacHeader *hdr)
Update with MPDU function.
Private Member Functions
void ResetPortionOfBitmap (uint16_t start, uint16_t end)
Reset portion of bitmap function.
Private Attributes
uint16_t m_bitmap [4096]
bitmap
uint16_t m_winEnd
window end
uint16_t m_winSize
window size
uint16_t m_winStart
window start
Detailed Description
BlockAckCache cache.
Definition at line 36 of file block-ack-cache.h.
Member Function Documentation
FillBlockAckBitmap()
void ns3::BlockAckCache::FillBlockAckBitmap (CtrlBAckResponseHeader * blockAckHeader)
Fill block ack bitmap function.
Parameters
blockAckHeader the block ack bitmap
Definition at line 115 of file block-ack-cache.cc.
References ns3::CtrlBAckResponseHeader::GetStartingSequence(), ns3::CtrlBAckResponseHeader::IsBasic(), ns3::CtrlBAckResponseHeader::IsCompressed(), ns3::CtrlBAckResponseHeader::IsExtendedCompressed(), ns3::CtrlBAckResponseHeader::IsMultiTid(), m_bitmap, m_winSize, NS_FATAL_ERROR, NS_LOG_FUNCTION, and ns3::CtrlBAckResponseHeader::SetReceivedPacket().
GetWinStart()
uint16_t ns3::BlockAckCache::GetWinStart (void) const
When an A-MPDU is received, the window start may change to a new value depending on the sequence number of the received MPDU (standard11n page 134).
This function is used to retrieve this value in order to add it to the BlockAck.
Returns
window start
Definition at line 45 of file block-ack-cache.cc.
References m_winStart.
Init()
void ns3::BlockAckCache::Init (uint16_t winStart, uint16_t winSize)
Initialization function.
Parameters
winStart the window start
winSize the window size
Definition at line 35 of file block-ack-cache.cc.
References m_bitmap, m_winEnd, m_winSize, m_winStart, and NS_LOG_FUNCTION.
Referenced by ns3::MacLow::CreateBlockAckAgreement().
ResetPortionOfBitmap()
void ns3::BlockAckCache::ResetPortionOfBitmap (uint16_t start, uint16_t end) private
Reset portion of bitmap function.
Parameters
start the starting position
end the ending position
Definition at line 103 of file block-ack-cache.cc.
References m_bitmap, NS_LOG_FUNCTION, and visualizer.core::start().
Referenced by UpdateWithBlockAckReq(), and UpdateWithMpdu().
UpdateWithBlockAckReq()
void ns3::BlockAckCache::UpdateWithBlockAckReq (uint16_t startingSeq)
Update with block ack request function.
Parameters
startingSeq the starting sequence
Definition at line 74 of file block-ack-cache.cc.
References ns3::IsInWindow(), m_winEnd, m_winSize, m_winStart, NS_LOG_FUNCTION, ns3::QosUtilsIsOldPacket(), ResetPortionOfBitmap(), and WINSIZE_ASSERT.
UpdateWithMpdu()
void ns3::BlockAckCache::UpdateWithMpdu (const WifiMacHeader * hdr)
Update with MPDU function.
Parameters
hdr the wifi MAC header
Definition at line 51 of file block-ack-cache.cc.
References ns3::WifiMacHeader::GetFragmentNumber(), ns3::WifiMacHeader::GetSequenceNumber(), ns3::IsInWindow(), m_bitmap, m_winEnd, m_winSize, m_winStart, NS_LOG_FUNCTION, ns3::QosUtilsIsOldPacket(), ResetPortionOfBitmap(), and WINSIZE_ASSERT.
Member Data Documentation
m_bitmap
uint16_t ns3::BlockAckCache::m_bitmap[4096] private
bitmap
Definition at line 83 of file block-ack-cache.h.
Referenced by FillBlockAckBitmap(), Init(), ResetPortionOfBitmap(), and UpdateWithMpdu().
m_winEnd
uint16_t ns3::BlockAckCache::m_winEnd private
window end
Definition at line 81 of file block-ack-cache.h.
Referenced by Init(), UpdateWithBlockAckReq(), and UpdateWithMpdu().
m_winSize
uint16_t ns3::BlockAckCache::m_winSize private
window size
Definition at line 80 of file block-ack-cache.h.
Referenced by FillBlockAckBitmap(), Init(), UpdateWithBlockAckReq(), and UpdateWithMpdu().
m_winStart
uint16_t ns3::BlockAckCache::m_winStart private
window start
Definition at line 79 of file block-ack-cache.h.
Referenced by GetWinStart(), Init(), UpdateWithBlockAckReq(), and UpdateWithMpdu().
The documentation for this class was generated from the following files:
src/wifi/model/block-ack-cache.h
src/wifi/model/block-ack-cache.cc