ns-3: SpectrumInterferenceTestCase Class Reference
SpectrumInterferenceTestCase Class Reference
Public Member Functions
SpectrumInterferenceTestCase (Ptr< SpectrumValue > s, uint32_t txBytes, bool rxCorrect, std::string name)
virtual ~SpectrumInterferenceTestCase ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
void RetrieveTestResult (SpectrumInterference *si)
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Attributes
Ptr< const SpectrumModel > m_mySpectrumModel
uint32_t m_rxCorrectKnownOutcome
Ptr< SpectrumValue > m_s
uint32_t m_txBytes
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 37 of file spectrum-interference-test.cc.
Constructor & Destructor Documentation
SpectrumInterferenceTestCase()
SpectrumInterferenceTestCase::SpectrumInterferenceTestCase (Ptr< SpectrumValue > s, uint32_t txBytes, bool rxCorrect, std::string name)
Definition at line 54 of file spectrum-interference-test.cc.
~SpectrumInterferenceTestCase()
SpectrumInterferenceTestCase::~SpectrumInterferenceTestCase () virtual
Definition at line 63 of file spectrum-interference-test.cc.
Member Function Documentation
DoRun()
void SpectrumInterferenceTestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 70 of file spectrum-interference-test.cc.
References m_mySpectrumModel, m_s, m_txBytes, sample-rng-plot::n, RetrieveTestResult(), ns3::Seconds(), ns3::SpectrumInterference::SetErrorModel(), and ns3::SpectrumInterference::SetNoisePowerSpectralDensity().
RetrieveTestResult()
void SpectrumInterferenceTestCase::RetrieveTestResult (SpectrumInterference * si)
Definition at line 126 of file spectrum-interference-test.cc.
References ns3::SpectrumInterference::EndRx(), m_rxCorrectKnownOutcome, and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
Member Data Documentation
m_mySpectrumModel
Ptr<const SpectrumModel> SpectrumInterferenceTestCase::m_mySpectrumModel private
Definition at line 49 of file spectrum-interference-test.cc.
Referenced by DoRun().
m_rxCorrectKnownOutcome
uint32_t SpectrumInterferenceTestCase::m_rxCorrectKnownOutcome private
Definition at line 48 of file spectrum-interference-test.cc.
Referenced by RetrieveTestResult().
m_s
Ptr<SpectrumValue> SpectrumInterferenceTestCase::m_s private
Definition at line 46 of file spectrum-interference-test.cc.
Referenced by DoRun().
m_txBytes
uint32_t SpectrumInterferenceTestCase::m_txBytes private
Definition at line 47 of file spectrum-interference-test.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/spectrum/test/spectrum-interference-test.cc