ns-3: ns3::SnrTag Class Reference
ns3::SnrTag Class Reference
#include "snr-tag.h"
Public Member Functions
SnrTag ()
Create a SnrTag with the default SNR 0.
void Deserialize (TagBuffer i)
double Get (void) const
Return the SNR value.
TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint32_t GetSerializedSize (void) const
void Print (std::ostream &os) const
void Serialize (TagBuffer i) const
void Set (double snr)
Set the SNR to the given value.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
double m_snr
SNR value in linear scale.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 34 of file snr-tag.h.
Constructor & Destructor Documentation
SnrTag()
ns3::SnrTag::SnrTag ()
Create a SnrTag with the default SNR 0.
Definition at line 53 of file snr-tag.cc.
Member Function Documentation
Deserialize()
void ns3::SnrTag::Deserialize (TagBuffer i) virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 71 of file snr-tag.cc.
References m_snr, and ns3::TagBuffer::ReadDouble().
Get()
double ns3::SnrTag::Get (void) const
Return the SNR value.
Returns
the SNR value in linear scale
Definition at line 89 of file snr-tag.cc.
References m_snr.
Referenced by GetTypeId(), ns3::StaWifiMac::Receive(), and ns3::MacLow::ReceiveOk().
GetInstanceTypeId()
TypeId ns3::SnrTag::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 48 of file snr-tag.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::SnrTag::GetSerializedSize (void) const virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 59 of file snr-tag.cc.
GetTypeId()
TypeId ns3::SnrTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 33 of file snr-tag.cc.
References Get(), ns3::MakeDoubleAccessor(), and ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::SnrTag::Print (std::ostream & os) const virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 77 of file snr-tag.cc.
References m_snr.
Serialize()
void ns3::SnrTag::Serialize (TagBuffer i) const virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 65 of file snr-tag.cc.
References m_snr, and ns3::TagBuffer::WriteDouble().
Set()
void ns3::SnrTag::Set (double snr)
Set the SNR to the given value.
Parameters
snr the value of the SNR to set in linear scale
Definition at line 83 of file snr-tag.cc.
References m_snr.
Referenced by ns3::MacLow::ReceiveOk(), ns3::MacLow::SendAckAfterData(), ns3::MacLow::SendBlockAckResponse(), and ns3::MacLow::SendCtsAfterRts().
Member Data Documentation
m_snr
double ns3::SnrTag::m_snr private
SNR value in linear scale.
Definition at line 69 of file snr-tag.h.
Referenced by Deserialize(), Get(), Print(), Serialize(), and Set().
The documentation for this class was generated from the following files:
src/wifi/model/snr-tag.h
src/wifi/model/snr-tag.cc