ns-3: ns3::WifiMacQueueItem Class Reference
ns3::WifiMacQueueItem Class Reference
Wifi Models
#include "wifi-mac-queue-item.h"
Public Member Functions
WifiMacQueueItem (Ptr< const Packet > p, const WifiMacHeader &header)
Create a Wifi MAC queue item containing a packet and a Wifi MAC header.
WifiMacQueueItem (Ptr< const Packet > p, const WifiMacHeader &header, Time tstamp)
Create a Wifi MAC queue item containing a packet and a Wifi MAC header.
virtual ~WifiMacQueueItem ()
void Aggregate (Ptr< const WifiMacQueueItem > msdu)
Aggregate the MSDU contained in the given MPDU to this MPDU (thus constituting an A-MSDU).
MsduAggregator::DeaggregatedMsdusCI begin (void)
Get a constant iterator pointing to the first MSDU in the list of aggregated MSDUs.
MsduAggregator::DeaggregatedMsdusCI end (void)
Get a constant iterator indicating past-the-last MSDU in the list of aggregated MSDUs.
Mac48Address GetDestinationAddress (void) const
Return the destination address present in the header.
WifiMacHeader & GetHeader (void)
Get the header stored in this item.
const WifiMacHeader & GetHeader (void) const
Get the header stored in this item.
Ptr< const Packet > GetPacket (void) const
Get the packet stored in this item.
Ptr< Packet > GetProtocolDataUnit (void) const
Get the MAC protocol data unit (MPDU) corresponding to this item (i.e.
uint32_t GetSize (void) const
Return the size of the packet stored by this item, including header size and trailer size.
Time GetTimeStamp (void) const
Get the timestamp included in this item.
virtual void Print (std::ostream &os) const
Print the item contents.
Public Member Functions inherited from ns3::SimpleRefCount< WifiMacQueueItem >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Member Functions
void DoAggregate (Ptr< const WifiMacQueueItem > msdu)
Aggregate the MSDU contained in the given MPDU to this MPDU (thus constituting an A-MSDU).
Private Attributes
WifiMacHeader m_header
Wifi MAC header associated with the packet.
MsduAggregator::DeaggregatedMsdus m_msduList
The list of aggregated MSDUs included in this MPDU.
Ptr< const Packet > m_packet
The packet (MSDU or A-MSDU) contained in this queue item.
Time m_tstamp
timestamp when the packet arrived at the queue
Detailed Description
WifiMacQueueItem stores (const) packets along with their Wifi MAC headers and the time when they were enqueued.
Definition at line 43 of file wifi-mac-queue-item.h.
Constructor & Destructor Documentation
WifiMacQueueItem() [1/2]
ns3::WifiMacQueueItem::WifiMacQueueItem (Ptr< const Packet > p, const WifiMacHeader & header)
Create a Wifi MAC queue item containing a packet and a Wifi MAC header.
Parameters
p the const packet included in the created item.
header the Wifi MAC header included in the created item.
Definition at line 35 of file wifi-mac-queue-item.cc.
WifiMacQueueItem() [2/2]
ns3::WifiMacQueueItem::WifiMacQueueItem (Ptr< const Packet > p, const WifiMacHeader & header, Time tstamp)
Create a Wifi MAC queue item containing a packet and a Wifi MAC header.
Parameters
p the const packet included in the created item.
header the Wifi MAC header included in the created item.
tstamp the timestamp associated with the created item.
Definition at line 40 of file wifi-mac-queue-item.cc.
References ns3::MsduAggregator::Deaggregate(), ns3::WifiMacHeader::IsQosAmsdu(), ns3::WifiMacHeader::IsQosData(), and m_msduList.
~WifiMacQueueItem()
ns3::WifiMacQueueItem::~WifiMacQueueItem () virtual
Definition at line 51 of file wifi-mac-queue-item.cc.
Member Function Documentation
Aggregate()
void ns3::WifiMacQueueItem::Aggregate (Ptr< const WifiMacQueueItem > msdu)
Aggregate the MSDU contained in the given MPDU to this MPDU (thus constituting an A-MSDU).
Note that the given MPDU cannot contain an A-MSDU.
Parameters
msdu the MPDU containing the MSDU to aggregate
Definition at line 101 of file wifi-mac-queue-item.cc.
References DoAggregate(), ns3::WifiMacHeader::GetAddr1(), ns3::WifiMacHeader::GetAddr2(), ns3::WifiMacHeader::IsFromDs(), ns3::WifiMacHeader::IsToDs(), m_header, m_msduList, m_packet, NS_ABORT_MSG_IF, NS_ASSERT, NS_LOG_FUNCTION, ns3::WifiMacHeader::SetAddr3(), and ns3::WifiMacHeader::SetQosAmsdu().
Referenced by ns3::MsduAggregator::GetNextAmsdu().
begin()
MsduAggregator::DeaggregatedMsdusCI ns3::WifiMacQueueItem::begin (void)
Get a constant iterator pointing to the first MSDU in the list of aggregated MSDUs.
Returns
a constant iterator pointing to the first MSDU in the list of aggregated MSDUs
Definition at line 191 of file wifi-mac-queue-item.cc.
References m_msduList.
DoAggregate()
void ns3::WifiMacQueueItem::DoAggregate (Ptr< const WifiMacQueueItem > msdu) private
Aggregate the MSDU contained in the given MPDU to this MPDU (thus constituting an A-MSDU).
Note that the given MPDU cannot contain an A-MSDU.
Parameters
msdu the MPDU containing the MSDU to aggregate
Definition at line 135 of file wifi-mac-queue-item.cc.
References ns3::Packet::AddAtEnd(), ns3::Packet::AddHeader(), ns3::MsduAggregator::CalculatePadding(), m_msduList, m_packet, m_tstamp, ns3::Max(), NS_ASSERT, NS_LOG_FUNCTION, ns3::AmsduSubframeHeader::SetDestinationAddr(), ns3::AmsduSubframeHeader::SetLength(), and ns3::AmsduSubframeHeader::SetSourceAddr().
Referenced by Aggregate().
end()
MsduAggregator::DeaggregatedMsdusCI ns3::WifiMacQueueItem::end (void)
Get a constant iterator indicating past-the-last MSDU in the list of aggregated MSDUs.
Returns
a constant iterator indicating past-the-last MSDU in the list of aggregated MSDUs
Definition at line 197 of file wifi-mac-queue-item.cc.
References m_msduList.
GetDestinationAddress()
Mac48Address ns3::WifiMacQueueItem::GetDestinationAddress (void) const
Return the destination address present in the header.
Returns
the destination address
Definition at line 74 of file wifi-mac-queue-item.cc.
References ns3::WifiMacHeader::GetAddr1(), and m_header.
GetHeader() [1/2]
WifiMacHeader & ns3::WifiMacQueueItem::GetHeader (void)
Get the header stored in this item.
Returns
the header stored in this item.
Definition at line 68 of file wifi-mac-queue-item.cc.
References m_header.
GetHeader() [2/2]
const WifiMacHeader & ns3::WifiMacQueueItem::GetHeader (void) const
Get the header stored in this item.
Returns
the header stored in this item.
Definition at line 62 of file wifi-mac-queue-item.cc.
References m_header.
Referenced by ns3::QosTxop::CompleteMpduTx(), ns3::ApWifiMac::DeaggregateAmsduAndForward(), ns3::QosTxop::DequeuePeekedFrame(), ns3::BlockAckManager::DiscardOutstandingMpdus(), OriginatorBlockAckWindowTest::DoRun(), ns3::MpduAggregator::GetNextAmpdu(), ns3::MsduAggregator::GetNextAmsdu(), ns3::BlockAckManager::InsertInRetryQueue(), ns3::QosTxop::NotifyAccessGranted(), ns3::Txop::NotifyAccessGranted(), ns3::BlockAckManager::NotifyMissedAck(), ns3::MeshWifiInterfaceMac::Receive(), ns3::OcbWifiMac::Receive(), ns3::AdhocWifiMac::Receive(), ns3::ApWifiMac::Receive(), ns3::MacRxMiddle::Receive(), ns3::RegularWifiMac::Receive(), ns3::StaWifiMac::Receive(), ns3::MacLow::ReceiveMpdu(), ns3::MacLow::ReceiveOk(), ns3::Txop::SendCfFrame(), ns3::QosTxop::StartNextPacket(), ns3::WaveMacLow::StartTransmission(), ns3::MacLow::StartTransmission(), ns3::MacLow::StoreMpduIfNeeded(), ns3::BlockAckManager::StorePacket(), and ns3::QosTxop::UpdateCurrentPacket().
GetPacket()
Ptr< const Packet > ns3::WifiMacQueueItem::GetPacket (void) const
Get the packet stored in this item.
Returns
the packet stored in this item.
Definition at line 56 of file wifi-mac-queue-item.cc.
References m_packet.
Referenced by ns3::QosTxop::DequeuePeekedFrame(), TwoLevelAggregationTest::DoRun(), ns3::MsduAggregator::GetNextAmsdu(), ns3::QosTxop::NotifyAccessGranted(), ns3::Txop::NotifyAccessGranted(), WifiAcMappingTest::PacketEnqueuedInWifiMacQueue(), ns3::MeshWifiInterfaceMac::Receive(), ns3::OcbWifiMac::Receive(), ns3::AdhocWifiMac::Receive(), ns3::ApWifiMac::Receive(), ns3::MacRxMiddle::Receive(), ns3::RegularWifiMac::Receive(), ns3::StaWifiMac::Receive(), ns3::MacLow::ReceiveOk(), ns3::Txop::SendCfFrame(), ns3::QosTxop::StartNextPacket(), ns3::WaveMacLow::StartTransmission(), ns3::MacLow::StartTransmission(), and ns3::QosTxop::UpdateCurrentPacket().
GetProtocolDataUnit()
Ptr< Packet > ns3::WifiMacQueueItem::GetProtocolDataUnit (void) const
Get the MAC protocol data unit (MPDU) corresponding to this item (i.e.
a copy of the packet stored in this item wrapped with MAC header and trailer)
Returns
the MAC protocol data unit corresponding to this item.
Definition at line 92 of file wifi-mac-queue-item.cc.
References ns3::Packet::AddHeader(), ns3::AddWifiMacTrailer(), m_header, and m_packet.
GetSize()
uint32_t ns3::WifiMacQueueItem::GetSize (void) const
Return the size of the packet stored by this item, including header size and trailer size.
Returns
the size of the packet stored by this item in bytes.
Definition at line 86 of file wifi-mac-queue-item.cc.
References ns3::WifiMacHeader::GetSerializedSize(), m_header, m_packet, and ns3::WIFI_MAC_FCS_LENGTH.
Referenced by ns3::WifiPsdu::WifiPsdu(), and ns3::MpduAggregator::GetNextAmpdu().
GetTimeStamp()
Time ns3::WifiMacQueueItem::GetTimeStamp (void) const
Get the timestamp included in this item.
Returns
the timestamp included in this item.
Definition at line 80 of file wifi-mac-queue-item.cc.
References m_tstamp.
Referenced by ns3::QosTxop::NotifyAccessGranted(), ns3::QosTxop::StartNextPacket(), and ns3::QosTxop::UpdateCurrentPacket().
Print()
void ns3::WifiMacQueueItem::Print (std::ostream & os) const virtual
Print the item contents.
Parameters
os output stream in which the data should be printed.
Definition at line 203 of file wifi-mac-queue-item.cc.
References ns3::WifiMacHeader::GetAddr1(), ns3::WifiMacHeader::GetQosTid(), ns3::WifiMacHeader::GetSequenceNumber(), ns3::WifiMacHeader::IsQosAck(), ns3::WifiMacHeader::IsQosBlockAck(), ns3::WifiMacHeader::IsQosData(), ns3::WifiMacHeader::IsQosNoAck(), m_header, m_packet, m_tstamp, and ns3::Simulator::Now().
Referenced by ns3::operator<<().
Member Data Documentation
m_header
WifiMacHeader ns3::WifiMacQueueItem::m_header private
Wifi MAC header associated with the packet.
Definition at line 146 of file wifi-mac-queue-item.h.
Referenced by Aggregate(), GetDestinationAddress(), GetHeader(), GetProtocolDataUnit(), GetSize(), and Print().
m_msduList
MsduAggregator::DeaggregatedMsdus ns3::WifiMacQueueItem::m_msduList private
The list of aggregated MSDUs included in this MPDU.
Definition at line 148 of file wifi-mac-queue-item.h.
Referenced by WifiMacQueueItem(), Aggregate(), begin(), DoAggregate(), and end().
m_packet
Ptr<const Packet> ns3::WifiMacQueueItem::m_packet private
The packet (MSDU or A-MSDU) contained in this queue item.
Definition at line 145 of file wifi-mac-queue-item.h.
Referenced by Aggregate(), DoAggregate(), GetPacket(), GetProtocolDataUnit(), GetSize(), and Print().
m_tstamp
Time ns3::WifiMacQueueItem::m_tstamp private
timestamp when the packet arrived at the queue
Definition at line 147 of file wifi-mac-queue-item.h.
Referenced by DoAggregate(), GetTimeStamp(), and Print().
The documentation for this class was generated from the following files:
src/wifi/model/wifi-mac-queue-item.h
src/wifi/model/wifi-mac-queue-item.cc