ns-3: WifiTest Class Reference
WifiTest Class Reference
Wifi Models » wifi module tests | Test suites
Wifi Test.
Public Member Functions
WifiTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CreateOne (Vector pos, Ptr< YansWifiChannel > channel)
Create one function.
void RunOne (void)
Run one function.
void SendOnePacket (Ptr< WifiNetDevice > dev)
Send one packet function.
Private Attributes
ObjectFactory m_mac
MAC.
ObjectFactory m_manager
manager
ObjectFactory m_propDelay
propagation delay
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Wifi Test.
Definition at line 92 of file wifi-test.cc.
Constructor & Destructor Documentation
WifiTest()
WifiTest::WifiTest ()
Definition at line 120 of file wifi-test.cc.
Member Function Documentation
CreateOne()
void WifiTest::CreateOne (Vector pos, Ptr< YansWifiChannel > channel) private
Create one function.
Parameters
pos the position
channel the wifi channel
Definition at line 133 of file wifi-test.cc.
References ns3::Node::AddDevice(), ns3::Object::AggregateObject(), third::channel, ns3::ObjectFactory::Create(), m_mac, m_manager, third::mac, third::mobility, third::phy, ns3::Seconds(), SendOnePacket(), ns3::WifiNetDevice::SetMac(), ns3::WifiNetDevice::SetPhy(), ns3::WifiNetDevice::SetRemoteStationManager(), and ns3::WIFI_PHY_STANDARD_80211a.
Referenced by RunOne().
DoRun()
void WifiTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 181 of file wifi-test.cc.
References m_mac, m_manager, m_propDelay, RunOne(), and ns3::ObjectFactory::SetTypeId().
RunOne()
void WifiTest::RunOne (void) private
Run one function.
Definition at line 162 of file wifi-test.cc.
References third::channel, ns3::ObjectFactory::Create(), CreateOne(), m_propDelay, and ns3::Seconds().
Referenced by DoRun().
SendOnePacket()
void WifiTest::SendOnePacket (Ptr< WifiNetDevice > dev) private
Send one packet function.
Parameters
dev the device
Definition at line 126 of file wifi-test.cc.
References ns3::WifiNetDevice::GetBroadcast(), and ns3::WifiNetDevice::Send().
Referenced by CreateOne().
Member Data Documentation
m_mac
ObjectFactory WifiTest::m_mac private
MAC.
Definition at line 116 of file wifi-test.cc.
Referenced by CreateOne(), and DoRun().
m_manager
ObjectFactory WifiTest::m_manager private
manager
Definition at line 115 of file wifi-test.cc.
Referenced by CreateOne(), and DoRun().
m_propDelay
ObjectFactory WifiTest::m_propDelay private
propagation delay
Definition at line 117 of file wifi-test.cc.
Referenced by DoRun(), and RunOne().
The documentation for this class was generated from the following file:
src/wifi/test/wifi-test.cc