ns-3: IPv4TestTag Class Reference
IPv4TestTag Class Reference
Internet » internet module tests | Test suites
Tag used in IPv4 Fragmentation Test.
Public Member Functions
virtual void Deserialize (TagBuffer buffer)
virtual TypeId GetInstanceTypeId () const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize () const
uint64_t GetToken ()
Get the token.
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer buffer) const
void SetToken (uint64_t token)
Set the token.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint64_t token
Token carried by the tag.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Tag used in IPv4 Fragmentation Test.
Definition at line 64 of file ipv4-fragmentation-test.cc.
Member Function Documentation
Deserialize()
virtual void IPv4TestTag::Deserialize (TagBuffer i) inline virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 79 of file ipv4-fragmentation-test.cc.
References ns3::TagBuffer::ReadU64().
GetInstanceTypeId()
virtual TypeId IPv4TestTag::GetInstanceTypeId () const inline virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 76 of file ipv4-fragmentation-test.cc.
GetSerializedSize()
virtual uint32_t IPv4TestTag::GetSerializedSize () const inline virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 77 of file ipv4-fragmentation-test.cc.
GetToken()
uint64_t IPv4TestTag::GetToken () inline
Get the token.
Returns
The token.
Definition at line 90 of file ipv4-fragmentation-test.cc.
Referenced by Ipv4FragmentationTest::DoRun().
GetTypeId()
static TypeId IPv4TestTag::GetTypeId () inline static
Get the type ID.
Returns
the object TypeId
Definition at line 72 of file ipv4-fragmentation-test.cc.
References ns3::TypeId::SetParent().
Print()
virtual void IPv4TestTag::Print (std::ostream & os) const inline virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 80 of file ipv4-fragmentation-test.cc.
Serialize()
virtual void IPv4TestTag::Serialize (TagBuffer i) const inline virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 78 of file ipv4-fragmentation-test.cc.
References ns3::TagBuffer::WriteU64().
SetToken()
void IPv4TestTag::SetToken (uint64_t token) inline
Set the token.
Parameters
token The token.
Definition at line 85 of file ipv4-fragmentation-test.cc.
Referenced by Ipv4FragmentationTest::SendClient().
Member Data Documentation
token
uint64_t IPv4TestTag::token private
Token carried by the tag.
Definition at line 66 of file ipv4-fragmentation-test.cc.
The documentation for this class was generated from the following file:
src/internet/test/ipv4-fragmentation-test.cc