ns-3: ns3::BurstErrorModel Class Reference
ns3::BurstErrorModel Class Reference
Determine which bursts of packets are errored corresponding to an underlying distribution, burst rate, and burst size.
#include "error-model.h"
Public Member Functions
BurstErrorModel ()
virtual ~BurstErrorModel ()
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
double GetBurstRate (void) const
void SetBurstRate (double rate)
void SetRandomBurstSize (Ptr< RandomVariableStream > burstSz)
void SetRandomVariable (Ptr< RandomVariableStream > ranVar)
Public Member Functions inherited from ns3::ErrorModel
ErrorModel ()
virtual ~ErrorModel ()
void Disable (void)
Disable the error model.
void Enable (void)
Enable the error model.
bool IsCorrupt (Ptr< Packet > pkt)
Note: Depending on the error model, this function may or may not alter the contents of the packet upon returning true.
bool IsEnabled (void) const
void Reset (void)
Reset any state associated with the error model.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ErrorModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual bool DoCorrupt (Ptr< Packet > p)
Corrupt a packet according to the specified model.
virtual void DoReset (void)
Re-initialize any state.
Private Attributes
double m_burstRate
the burst error event
Ptr< RandomVariableStream > m_burstSize
the number of packets being flagged as errored
Ptr< RandomVariableStream > m_burstStart
the error decision variable
uint32_t m_counter
keep track of the number of packets being errored until it reaches m_burstSize
uint32_t m_currentBurstSz
the current burst size
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Determine which bursts of packets are errored corresponding to an underlying distribution, burst rate, and burst size.
This object is used to flag packets as being lost/errored or not. The two parameters that govern the behavior are the burst rate (or equivalently, the mean duration/spacing between between error events), and the burst size (or equivalently, the number of packets being flagged as errored at each error event).
Users can optionally provide RandomVariableStream objects; the default for the decision variable is to use a Uniform(0,1) distribution; the default for the burst size (number of packets) is to use a discrete Uniform[1,4] distribution.
For every packet, the model generates a random number based on the decision variable, and compares it with the burst error rate to determine if a burst error event should occur. If a new error event occurs, the model to will generate a new burst size to determine how many packets should be dropped in this particular burst error event in addition to the current packet.
When a second packet arrives, the model again determines if a new error event should occur based on a newly generated decision variable and the burst error rate. If a new error event is determined to occur, the model will restart with a new burst size. Otherwise, the model will resume the last error event and drop the packet provided that the total number of packets that has been dropped does not exceed the burst size.
IsCorrupt() will not modify the packet data buffer
Definition at line 298 of file error-model.h.
Constructor & Destructor Documentation
BurstErrorModel()
ns3::BurstErrorModel::BurstErrorModel ()
Definition at line 314 of file error-model.cc.
~BurstErrorModel()
ns3::BurstErrorModel::~BurstErrorModel () virtual
Definition at line 319 of file error-model.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AssignStreams()
int64_t ns3::BurstErrorModel::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 353 of file error-model.cc.
References m_burstSize, m_burstStart, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
Referenced by BurstErrorModelSimple::DoRun().
DoCorrupt()
bool ns3::BurstErrorModel::DoCorrupt (Ptr< Packet > p) private virtual
Corrupt a packet according to the specified model.
Parameters
p the packet to corrupt
Returns
true if the packet is corrupted
Implements ns3::ErrorModel.
Definition at line 362 of file error-model.cc.
References ns3::RandomVariableStream::GetInteger(), ns3::RandomVariableStream::GetValue(), ns3::ErrorModel::IsEnabled(), m_burstRate, m_burstSize, m_burstStart, m_counter, m_currentBurstSz, NS_LOG_DEBUG, NS_LOG_FUNCTION, and NS_LOG_WARN.
DoReset()
void ns3::BurstErrorModel::DoReset (void) private virtual
Re-initialize any state.
Implements ns3::ErrorModel.
Definition at line 405 of file error-model.cc.
References m_counter, m_currentBurstSz, and NS_LOG_FUNCTION.
GetBurstRate()
double ns3::BurstErrorModel::GetBurstRate (void) const
Returns
the error rate being applied by the model
Definition at line 325 of file error-model.cc.
References m_burstRate, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::BurstErrorModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 291 of file error-model.cc.
References m_burstRate, m_burstSize, m_burstStart, ns3::MakeDoubleAccessor(), ns3::MakePointerAccessor(), and ns3::TypeId::SetParent().
SetBurstRate()
void ns3::BurstErrorModel::SetBurstRate (double rate)
Parameters
rate the error rate to be used by the model
Definition at line 332 of file error-model.cc.
References m_burstRate, and NS_LOG_FUNCTION.
SetRandomBurstSize()
void ns3::BurstErrorModel::SetRandomBurstSize (Ptr< RandomVariableStream > burstSz)
Parameters
burstSz A random variable distribution to generate random burst size
Definition at line 346 of file error-model.cc.
References m_burstSize, and NS_LOG_FUNCTION.
SetRandomVariable()
void ns3::BurstErrorModel::SetRandomVariable (Ptr< RandomVariableStream > ranVar)
Parameters
ranVar A random variable distribution to generate random variates
Definition at line 339 of file error-model.cc.
References m_burstStart, and NS_LOG_FUNCTION.
Referenced by BurstErrorModelSimple::DoRun().
Member Data Documentation
m_burstRate
double ns3::BurstErrorModel::m_burstRate private
the burst error event
Definition at line 343 of file error-model.h.
Referenced by DoCorrupt(), GetBurstRate(), GetTypeId(), and SetBurstRate().
m_burstSize
Ptr<RandomVariableStream> ns3::BurstErrorModel::m_burstSize private
the number of packets being flagged as errored
Definition at line 345 of file error-model.h.
Referenced by AssignStreams(), DoCorrupt(), GetTypeId(), and SetRandomBurstSize().
m_burstStart
Ptr<RandomVariableStream> ns3::BurstErrorModel::m_burstStart private
the error decision variable
Definition at line 344 of file error-model.h.
Referenced by AssignStreams(), DoCorrupt(), GetTypeId(), and SetRandomVariable().
m_counter
uint32_t ns3::BurstErrorModel::m_counter private
keep track of the number of packets being errored until it reaches m_burstSize
Definition at line 351 of file error-model.h.
Referenced by DoCorrupt(), and DoReset().
m_currentBurstSz
uint32_t ns3::BurstErrorModel::m_currentBurstSz private
the current burst size
Definition at line 352 of file error-model.h.
Referenced by DoCorrupt(), and DoReset().
The documentation for this class was generated from the following files:
src/network/utils/error-model.h
src/network/utils/error-model.cc