ns-3: ns3::DsaRsp Class Reference
ns3::DsaRsp Class Reference
WiMAX Models
#include "mac-messages.h"
Public Member Functions
DsaRsp (void)
~DsaRsp (void)
uint32_t Deserialize (Buffer::Iterator start)
Cid GetCid (void) const
uint16_t GetConfirmationCode (void) const
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
std::string GetName (void) const
uint32_t GetSerializedSize (void) const
ServiceFlow GetServiceFlow (void) const
uint32_t GetSfid (void) const
uint16_t GetTransactionId (void) const
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetCid (Cid cid)
set the connection identifier
void SetConfirmationCode (uint16_t confirmationCode)
set the confirmation code
void SetServiceFlow (ServiceFlow sf)
specify a service flow to be requested by this message
void SetSfid (uint32_t sfid)
set the service flow identifier
void SetTransactionId (uint16_t transactionId)
set the transaction ID
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Cid m_cid
CID.
uint8_t m_confirmationCode
confirmation code
ServiceFlow m_serviceFlow
service flow
uint32_t m_sfid
SFID.
uint16_t m_transactionId
transaction ID
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class implements the DSA-RSP message described by "IEEE Standard for Local and metropolitan area networks Part 16: Air Interface for Fixed Broadband Wireless Access Systems" 6.3.2.3.11 DSA-RSP message, page 63
*   0             7             15            23
*  +-------------+-------------+-------------+
*  |Mngt msg type|       Transaction ID      |
*  +-------------+-------------+-------------+
*  | Conf Code   | Service Flow TLV          |
*  +~~~~~~~~~~~~~+~~~~~~~~~~~~~+~~~~~~~~~~~~~+
*
Definition at line 474 of file mac-messages.h.
Constructor & Destructor Documentation
DsaRsp()
ns3::DsaRsp::DsaRsp (void)
Definition at line 643 of file mac-messages.cc.
~DsaRsp()
ns3::DsaRsp::~DsaRsp (void)
Definition at line 651 of file mac-messages.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::DsaRsp::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 763 of file mac-messages.cc.
References ns3::Tlv::Deserialize(), m_confirmationCode, m_serviceFlow, m_transactionId, ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetCid()
Cid ns3::DsaRsp::GetCid (void) const
Returns
the connection identifier
Definition at line 710 of file mac-messages.cc.
References m_cid.
GetConfirmationCode()
uint16_t ns3::DsaRsp::GetConfirmationCode (void) const
Returns
the confirmation code
Definition at line 686 of file mac-messages.cc.
References m_confirmationCode.
GetInstanceTypeId()
TypeId ns3::DsaRsp::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 733 of file mac-messages.cc.
References GetTypeId().
GetName()
std::string ns3::DsaRsp::GetName (void) const
Returns
the service name
Definition at line 716 of file mac-messages.cc.
GetSerializedSize()
uint32_t ns3::DsaRsp::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 746 of file mac-messages.cc.
References ns3::Tlv::GetSerializedSize(), m_serviceFlow, and ns3::ServiceFlow::ToTlv().
GetServiceFlow()
ServiceFlow ns3::DsaRsp::GetServiceFlow (void) const
Returns
the service flow requested by this message
Definition at line 668 of file mac-messages.cc.
References m_serviceFlow.
Referenced by ns3::SsServiceFlowManager::ProcessDsaRsp().
GetSfid()
uint32_t ns3::DsaRsp::GetSfid (void) const
Returns
the service flow identifier
Definition at line 698 of file mac-messages.cc.
References m_sfid.
GetTransactionId()
uint16_t ns3::DsaRsp::GetTransactionId (void) const
Returns
the transaction ID
Definition at line 662 of file mac-messages.cc.
References m_transactionId.
Referenced by ns3::SsServiceFlowManager::ProcessDsaRsp().
GetTypeId()
TypeId ns3::DsaRsp::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 722 of file mac-messages.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::DsaRsp::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 739 of file mac-messages.cc.
References m_cid, m_confirmationCode, m_sfid, and m_transactionId.
Serialize()
void ns3::DsaRsp::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 753 of file mac-messages.cc.
References m_confirmationCode, m_serviceFlow, m_transactionId, ns3::Tlv::Serialize(), visualizer.core::start(), ns3::ServiceFlow::ToTlv(), ns3::Buffer::Iterator::WriteU16(), and ns3::Buffer::Iterator::WriteU8().
SetCid()
void ns3::DsaRsp::SetCid (Cid cid)
set the connection identifier
Parameters
cid the connection identifier
Definition at line 704 of file mac-messages.cc.
References m_cid.
SetConfirmationCode()
void ns3::DsaRsp::SetConfirmationCode (uint16_t confirmationCode)
set the confirmation code
Parameters
confirmationCode
Definition at line 680 of file mac-messages.cc.
References m_confirmationCode.
Referenced by ns3::BsServiceFlowManager::CreateDsaRsp().
SetServiceFlow()
void ns3::DsaRsp::SetServiceFlow (ServiceFlow sf)
specify a service flow to be requested by this message
Parameters
sf the service flow
Definition at line 674 of file mac-messages.cc.
References m_serviceFlow.
Referenced by ns3::BsServiceFlowManager::CreateDsaRsp().
SetSfid()
void ns3::DsaRsp::SetSfid (uint32_t sfid)
set the service flow identifier
Parameters
sfid the service flow identifier
Definition at line 692 of file mac-messages.cc.
References m_sfid.
SetTransactionId()
void ns3::DsaRsp::SetTransactionId (uint16_t transactionId)
set the transaction ID
Parameters
transactionId
Definition at line 656 of file mac-messages.cc.
References m_transactionId.
Referenced by ns3::BsServiceFlowManager::CreateDsaRsp().
Member Data Documentation
m_cid
Cid ns3::DsaRsp::m_cid private
CID.
Definition at line 547 of file mac-messages.h.
Referenced by GetCid(), Print(), and SetCid().
m_confirmationCode
uint8_t ns3::DsaRsp::m_confirmationCode private
confirmation code
Definition at line 543 of file mac-messages.h.
Referenced by Deserialize(), GetConfirmationCode(), Print(), Serialize(), and SetConfirmationCode().
m_serviceFlow
ServiceFlow ns3::DsaRsp::m_serviceFlow private
service flow
Definition at line 545 of file mac-messages.h.
Referenced by Deserialize(), GetSerializedSize(), GetServiceFlow(), Serialize(), and SetServiceFlow().
m_sfid
uint32_t ns3::DsaRsp::m_sfid private
SFID.
Definition at line 546 of file mac-messages.h.
Referenced by GetSfid(), Print(), and SetSfid().
m_transactionId
uint16_t ns3::DsaRsp::m_transactionId private
transaction ID
Definition at line 542 of file mac-messages.h.
Referenced by Deserialize(), GetTransactionId(), Print(), Serialize(), and SetTransactionId().
The documentation for this class was generated from the following files:
src/wimax/model/mac-messages.h
src/wimax/model/mac-messages.cc