ns-3: ns3::ListErrorModel Class Reference
ns3::ListErrorModel Class Reference
Provide a list of Packet uids to corrupt.
#include "error-model.h"
Public Member Functions
ListErrorModel ()
virtual ~ListErrorModel ()
std::list< uint32_t > GetList (void) const
void SetList (const std::list< uint32_t > &packetlist)
Public Member Functions inherited from ns3::ErrorModel
ErrorModel ()
virtual ~ErrorModel ()
void Disable (void)
Disable the error model.
void Enable (void)
Enable the error model.
bool IsCorrupt (Ptr< Packet > pkt)
Note: Depending on the error model, this function may or may not alter the contents of the packet upon returning true.
bool IsEnabled (void) const
void Reset (void)
Reset any state associated with the error model.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ErrorModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef std::list< uint32_t > PacketList
Typedef: packet Uid list.
typedef std::list< uint32_t >::const_iterator PacketListCI
Typedef: packet Uid list const iterator.
Private Member Functions
virtual bool DoCorrupt (Ptr< Packet > p)
Corrupt a packet according to the specified model.
virtual void DoReset (void)
Re-initialize any state.
Private Attributes
PacketList m_packetList
container of Uid of packets to corrupt
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Provide a list of Packet uids to corrupt.
This object is used to flag packets as being lost/errored or not. A note on performance: the list is assumed to be unordered, and in general, Packet uids received may be unordered. Therefore, each call to IsCorrupt() will result in a walk of the list with the present underlying implementation.
Note also that if one wants to target multiple packets from looking at an (unerrored) trace file, the act of erroring a given packet may cause subsequent packet uids to change. For instance, suppose one wants to error packets 11 and 17 on a given device. It may be that erroring packet 11 will cause the subsequent uid stream to change and 17 may no longer correspond to the second packet that one wants to lose. Therefore, be advised that it might take some trial and error to select the right uids when multiple are provided.
Reset() on this model will clear the list
IsCorrupt() will not modify the packet data buffer
Definition at line 379 of file error-model.h.
Member Typedef Documentation
PacketList
typedef std::list<uint32_t> ns3::ListErrorModel::PacketList private
Typedef: packet Uid list.
Definition at line 406 of file error-model.h.
PacketListCI
typedef std::list<uint32_t>::const_iterator ns3::ListErrorModel::PacketListCI private
Typedef: packet Uid list const iterator.
Definition at line 408 of file error-model.h.
Constructor & Destructor Documentation
ListErrorModel()
ns3::ListErrorModel::ListErrorModel ()
Definition at line 430 of file error-model.cc.
References NS_LOG_FUNCTION.
~ListErrorModel()
ns3::ListErrorModel::~ListErrorModel () virtual
Definition at line 435 of file error-model.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
DoCorrupt()
bool ns3::ListErrorModel::DoCorrupt (Ptr< Packet > p) private virtual
Corrupt a packet according to the specified model.
Parameters
p the packet to corrupt
Returns
true if the packet is corrupted
Implements ns3::ErrorModel.
Definition at line 458 of file error-model.cc.
References ns3::Packet::GetUid(), ns3::ErrorModel::IsEnabled(), m_packetList, and NS_LOG_FUNCTION.
DoReset()
void ns3::ListErrorModel::DoReset (void) private virtual
Re-initialize any state.
Implements ns3::ErrorModel.
Definition at line 478 of file error-model.cc.
References m_packetList, and NS_LOG_FUNCTION.
GetList()
std::list< uint32_t > ns3::ListErrorModel::GetList (void) const
Returns
a copy of the underlying list
Definition at line 441 of file error-model.cc.
References m_packetList, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::ListErrorModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 420 of file error-model.cc.
References ns3::TypeId::SetParent().
SetList()
void ns3::ListErrorModel::SetList (const std::list< uint32_t > & packetlist)
Parameters
packetlist The list of packet uids to error.
This method overwrites any previously provided list.
Definition at line 448 of file error-model.cc.
References m_packetList, and NS_LOG_FUNCTION.
Member Data Documentation
m_packetList
PacketList ns3::ListErrorModel::m_packetList private
container of Uid of packets to corrupt
Definition at line 410 of file error-model.h.
Referenced by DoCorrupt(), DoReset(), GetList(), and SetList().
The documentation for this class was generated from the following files:
src/network/utils/error-model.h
src/network/utils/error-model.cc