ns-3: SteadyStateRandomWaypointTest Class Reference
SteadyStateRandomWaypointTest Class Reference
Mobility » mobility module tests | Test suites
Steady State Random Waypoint Test.
Public Member Functions
SteadyStateRandomWaypointTest ()
virtual ~SteadyStateRandomWaypointTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void DistribCompare ()
Distribution compare function.
virtual void DoRun (void)
Implementation to actually run this TestCase.
virtual void DoTeardown (void)
Implementation to do any local setup required for this TestCase.
Private Attributes
double count
count
std::vector< Ptr< MobilityModel > > mobilityStack
modility model
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Steady State Random Waypoint Test.
Definition at line 37 of file steady-state-random-waypoint-mobility-model-test.cc.
Constructor & Destructor Documentation
SteadyStateRandomWaypointTest()
SteadyStateRandomWaypointTest::SteadyStateRandomWaypointTest () inline
Definition at line 40 of file steady-state-random-waypoint-mobility-model-test.cc.
~SteadyStateRandomWaypointTest()
virtual SteadyStateRandomWaypointTest::~SteadyStateRandomWaypointTest () inline virtual
Definition at line 42 of file steady-state-random-waypoint-mobility-model-test.cc.
Member Function Documentation
DistribCompare()
void SteadyStateRandomWaypointTest::DistribCompare () private
Distribution compare function.
Definition at line 99 of file steady-state-random-waypoint-mobility-model-test.cc.
References ns3::MobilityModel::GetPosition(), ns3::MobilityModel::GetVelocity(), and NS_TEST_EXPECT_MSG_EQ_TOL.
Referenced by DoRun().
DoRun()
void SteadyStateRandomWaypointTest::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 61 of file steady-state-random-waypoint-mobility-model-test.cc.
References ns3::MobilityModel::AssignStreams(), ns3::ObjectFactory::Create(), ns3::Simulator::Destroy(), DistribCompare(), ns3::Object::GetObject(), ns3::Object::Initialize(), ns3::Simulator::Run(), ns3::Simulator::Schedule(), ns3::Seconds(), ns3::ObjectFactory::Set(), ns3::RngSeedManager::SetSeed(), ns3::ObjectFactory::SetTypeId(), and ns3::Simulator::Stop().
DoTeardown()
void SteadyStateRandomWaypointTest::DoTeardown (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test teardown
Reimplemented from ns3::TestCase.
Definition at line 55 of file steady-state-random-waypoint-mobility-model-test.cc.
Member Data Documentation
count
double SteadyStateRandomWaypointTest::count private
count
Definition at line 46 of file steady-state-random-waypoint-mobility-model-test.cc.
mobilityStack
std::vector<Ptr<MobilityModel> > SteadyStateRandomWaypointTest::mobilityStack private
modility model
Definition at line 45 of file steady-state-random-waypoint-mobility-model-test.cc.
The documentation for this class was generated from the following file:
src/mobility/test/steady-state-random-waypoint-mobility-model-test.cc