ns-3: ns3::Ipv6InterfaceAddress Class Reference
ns3::Ipv6InterfaceAddress Class Reference
Network » Address | Internet » IPv6 classes and sub-modules
IPv6 address associated with an interface.
#include "ipv6-interface-address.h"
Public Types
enum Scope_e { HOST, LINKLOCAL, GLOBAL }
Address scope.
enum State_e {
TENTATIVE, DEPRECATED, PREFERRED, PERMANENT,
HOMEADDRESS, TENTATIVE_OPTIMISTIC, INVALID
}
State of an address associated with an interface.
Public Member Functions
Ipv6InterfaceAddress ()
Default constructor.
Ipv6InterfaceAddress (const Ipv6InterfaceAddress &o)
Copy constructor.
Ipv6InterfaceAddress (Ipv6Address address)
Constructor.
Ipv6InterfaceAddress (Ipv6Address address, Ipv6Prefix prefix)
Constructor.
~Ipv6InterfaceAddress ()
Destructor.
Ipv6Address GetAddress () const
Get the IPv6 address.
uint32_t GetNsDadUid () const
Get the latest DAD probe packet UID.
Ipv6Prefix GetPrefix () const
Get the IPv6 prefix.
Ipv6InterfaceAddress::Scope_e GetScope () const
Get address scope.
Ipv6InterfaceAddress::State_e GetState () const
Get the address state.
bool IsInSameSubnet (Ipv6Address b) const
Checks if the address is in the same subnet.
void SetAddress (Ipv6Address address)
Set IPv6 address (and scope).
void SetNsDadUid (uint32_t uid)
Set the latest DAD probe packet UID.
void SetScope (Ipv6InterfaceAddress::Scope_e scope)
Set the scope.
void SetState (Ipv6InterfaceAddress::State_e state)
Set the state.
Private Attributes
Ipv6Address m_address
The IPv6 address.
uint32_t m_nsDadUid
Last DAD probe packet UID.
Ipv6Prefix m_prefix
The IPv6 prefix.
Scope_e m_scope
Scope of the address.
State_e m_state
State of the address.
Friends
bool operator!= (Ipv6InterfaceAddress const &a, Ipv6InterfaceAddress const &b)
Not equal to operator.
bool operator== (Ipv6InterfaceAddress const &a, Ipv6InterfaceAddress const &b)
Equal to operator.
Detailed Description
IPv6 address associated with an interface.
Definition at line 37 of file ipv6-interface-address.h.
Member Enumeration Documentation
Scope_e
enum ns3::Ipv6InterfaceAddress::Scope_e
Address scope.
Enumerator
HOST
Localhost (::1/128)
LINKLOCAL
Link-local address (fe80::/64)
GLOBAL
Global address (2000::/3)
Definition at line 59 of file ipv6-interface-address.h.
State_e
enum ns3::Ipv6InterfaceAddress::State_e
State of an address associated with an interface.
Enumerator
TENTATIVE
Address is tentative, no packet can be sent unless DAD finished.
DEPRECATED
Address is deprecated and should not be used.
PREFERRED
Preferred address.
PERMANENT
Permanent address.
HOMEADDRESS
Address is a HomeAddress.
TENTATIVE_OPTIMISTIC
Address is tentative but we are optimistic so we can send packet even if DAD is not yet finished.
INVALID
Invalid state (after a DAD failed)
Definition at line 44 of file ipv6-interface-address.h.
Constructor & Destructor Documentation
Ipv6InterfaceAddress() [1/4]
ns3::Ipv6InterfaceAddress::Ipv6InterfaceAddress ()
Default constructor.
Definition at line 33 of file ipv6-interface-address.cc.
References NS_LOG_FUNCTION.
Ipv6InterfaceAddress() [2/4]
ns3::Ipv6InterfaceAddress::Ipv6InterfaceAddress (Ipv6Address address)
Constructor.
Prefix is 64 by default.
Parameters
address the IPv6 address to set
Definition at line 43 of file ipv6-interface-address.cc.
References first::address, m_nsDadUid, m_prefix, NS_LOG_FUNCTION, SetAddress(), SetState(), and TENTATIVE_OPTIMISTIC.
Ipv6InterfaceAddress() [3/4]
ns3::Ipv6InterfaceAddress::Ipv6InterfaceAddress (Ipv6Address address, Ipv6Prefix prefix)
Constructor.
Parameters
address IPv6 address to set
prefix IPv6 prefix
Definition at line 52 of file ipv6-interface-address.cc.
References first::address, m_nsDadUid, m_prefix, NS_LOG_FUNCTION, SetAddress(), SetState(), and TENTATIVE_OPTIMISTIC.
Ipv6InterfaceAddress() [4/4]
ns3::Ipv6InterfaceAddress::Ipv6InterfaceAddress (const Ipv6InterfaceAddress & o)
Copy constructor.
Parameters
o object to copy
Definition at line 61 of file ipv6-interface-address.cc.
~Ipv6InterfaceAddress()
ns3::Ipv6InterfaceAddress::~Ipv6InterfaceAddress ()
Destructor.
Definition at line 70 of file ipv6-interface-address.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
GetAddress()
Ipv6Address ns3::Ipv6InterfaceAddress::GetAddress () const
Get the IPv6 address.
Returns
IPv6 address
Definition at line 75 of file ipv6-interface-address.cc.
References m_address, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Ipv6Interface::AddAddress(), Ipv6L3ProtocolTestCase::DoRun(), IpAddressHelperTestCasev6::DoRun(), Ipv6PacketInfoTagTest::DoRun(), ns3::Icmpv6L4Protocol::FunctionDadTimeout(), ns3::Ipv6Interface::GetAddressMatchingDestination(), ns3::AnimationInterface::GetIpv6Address(), ns3::AnimationInterface::GetIpv6Addresses(), ns3::Ipv6InterfaceContainer::GetLinkLocalAddress(), ns3::Icmpv6L4Protocol::HandleEchoRequest(), ns3::Icmpv6L4Protocol::HandleNA(), ns3::Icmpv6L4Protocol::HandleNS(), ns3::Ipv6L3Protocol::IpForward(), ns3::Icmpv6L4Protocol::Lookup(), ns3::operator<<(), ns3::Ipv6L3Protocol::Receive(), ns3::Ipv6L3Protocol::RemoveAutoconfiguredAddress(), ns3::Ping6::Send(), UanExperiment::SendPackets(), and ns3::Ipv6L3Protocol::SendRealOut().
GetNsDadUid()
uint32_t ns3::Ipv6InterfaceAddress::GetNsDadUid () const
Get the latest DAD probe packet UID.
Returns
uid
Definition at line 184 of file ipv6-interface-address.cc.
References m_nsDadUid, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Icmpv6L4Protocol::HandleNS().
GetPrefix()
Ipv6Prefix ns3::Ipv6InterfaceAddress::GetPrefix () const
Get the IPv6 prefix.
Returns
IPv6 prefix
Definition at line 110 of file ipv6-interface-address.cc.
References m_prefix, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Ipv6Interface::GetAddressMatchingDestination(), and ns3::operator<<().
GetScope()
Ipv6InterfaceAddress::Scope_e ns3::Ipv6InterfaceAddress::GetScope () const
Get address scope.
Returns
scope
Definition at line 134 of file ipv6-interface-address.cc.
References m_scope, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::RipNg::DoSendRouteUpdate(), ns3::Ipv6InterfaceContainer::GetLinkLocalAddress(), ns3::RipNg::HandleRequests(), and ns3::operator<<().
GetState()
Ipv6InterfaceAddress::State_e ns3::Ipv6InterfaceAddress::GetState () const
Get the address state.
Returns
address state
Definition at line 122 of file ipv6-interface-address.cc.
References m_state, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Icmpv6L4Protocol::FunctionDadTimeout(), and ns3::Icmpv6L4Protocol::HandleNA().
IsInSameSubnet()
bool ns3::Ipv6InterfaceAddress::IsInSameSubnet (Ipv6Address b) const
Checks if the address is in the same subnet.
Parameters
b the address to check
Returns
true if the address is in the same subnet.
Definition at line 140 of file ipv6-interface-address.cc.
References ns3::Ipv6Address::CombinePrefix(), ns3::Ipv6Address::IsLinkLocal(), ns3::Ipv6Address::IsLinkLocalMulticast(), m_address, m_prefix, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::Ping6::Send().
SetAddress()
void ns3::Ipv6InterfaceAddress::SetAddress (Ipv6Address address)
Set IPv6 address (and scope).
Parameters
address IPv6 address to set
Definition at line 81 of file ipv6-interface-address.cc.
References first::address, GLOBAL, HOST, LINKLOCAL, m_address, m_prefix, m_scope, and NS_LOG_FUNCTION.
Referenced by Ipv6InterfaceAddress().
SetNsDadUid()
void ns3::Ipv6InterfaceAddress::SetNsDadUid (uint32_t uid)
Set the latest DAD probe packet UID.
Parameters
uid packet uid
Definition at line 190 of file ipv6-interface-address.cc.
References m_nsDadUid, and NS_LOG_FUNCTION.
SetScope()
void ns3::Ipv6InterfaceAddress::SetScope (Ipv6InterfaceAddress::Scope_e scope)
Set the scope.
Parameters
scope the scope of address
Definition at line 128 of file ipv6-interface-address.cc.
References m_scope, and NS_LOG_FUNCTION.
SetState()
void ns3::Ipv6InterfaceAddress::SetState (Ipv6InterfaceAddress::State_e state)
Set the state.
Parameters
state the state
Definition at line 116 of file ipv6-interface-address.cc.
References m_state, and NS_LOG_FUNCTION.
Referenced by Ipv6InterfaceAddress().
Friends And Related Function Documentation
operator!=
bool operator!= (Ipv6InterfaceAddress const & a, Ipv6InterfaceAddress const & b) friend
Not equal to operator.
Parameters
a the first operand
b the first operand
Returns
true if the operands are not equal
Definition at line 230 of file ipv6-interface-address.h.
operator==
bool operator== (Ipv6InterfaceAddress const & a, Ipv6InterfaceAddress const & b) friend
Equal to operator.
Parameters
a the first operand
b the first operand
Returns
true if the operands are equal
Definition at line 224 of file ipv6-interface-address.h.
Member Data Documentation
m_address
Ipv6Address ns3::Ipv6InterfaceAddress::m_address private
The IPv6 address.
Definition at line 173 of file ipv6-interface-address.h.
Referenced by GetAddress(), IsInSameSubnet(), ns3::operator!=(), ns3::operator==(), and SetAddress().
m_nsDadUid
uint32_t ns3::Ipv6InterfaceAddress::m_nsDadUid private
Last DAD probe packet UID.
Definition at line 211 of file ipv6-interface-address.h.
Referenced by Ipv6InterfaceAddress(), GetNsDadUid(), and SetNsDadUid().
m_prefix
Ipv6Prefix ns3::Ipv6InterfaceAddress::m_prefix private
The IPv6 prefix.
Definition at line 178 of file ipv6-interface-address.h.
Referenced by Ipv6InterfaceAddress(), GetPrefix(), IsInSameSubnet(), ns3::operator!=(), ns3::operator==(), and SetAddress().
m_scope
Scope_e ns3::Ipv6InterfaceAddress::m_scope private
Scope of the address.
Definition at line 188 of file ipv6-interface-address.h.
Referenced by GetScope(), ns3::operator!=(), ns3::operator==(), SetAddress(), and SetScope().
m_state
State_e ns3::Ipv6InterfaceAddress::m_state private
State of the address.
Definition at line 183 of file ipv6-interface-address.h.
Referenced by GetState(), ns3::operator!=(), ns3::operator==(), and SetState().
The documentation for this class was generated from the following files:
src/internet/model/ipv6-interface-address.h
src/internet/model/ipv6-interface-address.cc