ns-3: ns3::TcpOptionWinScale Class Reference
ns3::TcpOptionWinScale Class Reference
Internet » TCP
Defines the TCP option of kind 3 (window scale option) as in RFC 1323
#include "tcp-option-winscale.h"
Public Member Functions
TcpOptionWinScale ()
virtual ~TcpOptionWinScale ()
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the Option from a buffer iterator.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint8_t GetKind (void) const
Get the ‘kind’ (as in RFC 793) of this option.
uint8_t GetScale (void) const
Get the scale value (uint8_t)
virtual uint32_t GetSerializedSize (void) const
Returns number of bytes required for Option serialization.
virtual void Print (std::ostream &os) const
Print the Option contents.
virtual void Serialize (Buffer::Iterator start) const
Serialize the Option to a buffer iterator.
void SetScale (uint8_t scale)
Set the scale option.
Public Member Functions inherited from ns3::TcpOption
TcpOption ()
virtual ~TcpOption ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpOption
static Ptr< TcpOption > CreateOption (uint8_t kind)
Creates an option.
static TypeId GetTypeId (void)
Get the type ID.
static bool IsKindKnown (uint8_t kind)
Check if the option is implemented.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Attributes
uint8_t m_scale
Window scaling in number of bit shift.
Additional Inherited Members
Public Types inherited from ns3::TcpOption
enum Kind {
END = 0, NOP = 1, MSS = 2, WINSCALE = 3,
SACKPERMITTED = 4, SACK = 5, TS = 8, UNKNOWN = 255
}
The option Kind, as defined in the respective RFCs.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Defines the TCP option of kind 3 (window scale option) as in RFC 1323
For more efficient use of high bandwidth networks, a larger TCP window size may be used. The TCP window size field controls the flow of data and its value is limited to between 2 and 65,535 bytes.
Since the size field cannot be expanded, a scaling factor is used. The TCP window scale option, as defined in RFC 1323, is an option used to increase the maximum window size from 65,535 bytes to 1 gigabyte. Scaling up to larger window sizes is a part of what is necessary for TCP Tuning.
The window scale option is used only during the TCP 3-way handshake. The window scale value represents the number of bits to left-shift the 16-bit window size field. The window scale value can be set from 0 (no shift) to 14 for each direction independently. Both sides must send the option in their SYN segments to enable window scaling in either direction.
Definition at line 50 of file tcp-option-winscale.h.
Constructor & Destructor Documentation
TcpOptionWinScale()
ns3::TcpOptionWinScale::TcpOptionWinScale ()
Definition at line 31 of file tcp-option-winscale.cc.
~TcpOptionWinScale()
ns3::TcpOptionWinScale::~TcpOptionWinScale () virtual
Definition at line 37 of file tcp-option-winscale.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::TcpOptionWinScale::Deserialize (Buffer::Iterator start) virtual
Deserialize the Option from a buffer iterator.
Parameters
start the buffer iterator
Returns
the number of deserialized bytes
Implements ns3::TcpOption.
Definition at line 80 of file tcp-option-winscale.cc.
References GetKind(), GetSerializedSize(), m_scale, NS_LOG_WARN, ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
Referenced by TcpOptionWSTestCase::TestDeserialize().
GetInstanceTypeId()
TypeId ns3::TcpOptionWinScale::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Reimplemented from ns3::TcpOption.
Definition at line 53 of file tcp-option-winscale.cc.
References GetTypeId().
GetKind()
uint8_t ns3::TcpOptionWinScale::GetKind (void) const virtual
Get the ‘kind’ (as in RFC 793) of this option.
Returns
the Option Kind
Implements ns3::TcpOption.
Definition at line 101 of file tcp-option-winscale.cc.
References ns3::TcpOption::WINSCALE.
Referenced by Deserialize(), and Serialize().
GetScale()
uint8_t ns3::TcpOptionWinScale::GetScale (void) const
Get the scale value (uint8_t)
Returns
The scale value
Definition at line 107 of file tcp-option-winscale.cc.
References m_scale, and NS_ASSERT.
Referenced by TcpOptionWSTestCase::TestDeserialize(), and TcpOptionWSTestCase::TestSerialize().
GetSerializedSize()
uint32_t ns3::TcpOptionWinScale::GetSerializedSize (void) const virtual
Returns number of bytes required for Option serialization.
Returns
number of bytes required for Option serialization
Implements ns3::TcpOption.
Definition at line 65 of file tcp-option-winscale.cc.
Referenced by Deserialize(), and TcpOptionWSTestCase::TestSerialize().
GetTypeId()
TypeId ns3::TcpOptionWinScale::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 42 of file tcp-option-winscale.cc.
References ns3::TypeId::SetParent().
Referenced by ns3::TcpOption::CreateOption(), and GetInstanceTypeId().
Print()
void ns3::TcpOptionWinScale::Print (std::ostream & os) const virtual
Print the Option contents.
Parameters
os the output stream
Implements ns3::TcpOption.
Definition at line 59 of file tcp-option-winscale.cc.
References m_scale.
Serialize()
void ns3::TcpOptionWinScale::Serialize (Buffer::Iterator start) const virtual
Serialize the Option to a buffer iterator.
Parameters
start the buffer iterator
Implements ns3::TcpOption.
Definition at line 71 of file tcp-option-winscale.cc.
References GetKind(), m_scale, visualizer.core::start(), and ns3::Buffer::Iterator::WriteU8().
Referenced by TcpOptionWSTestCase::TestSerialize().
SetScale()
void ns3::TcpOptionWinScale::SetScale (uint8_t scale)
Set the scale option.
The scale option SHOULD be <= 14 (as RFC 1323).
Parameters
scale Scale factor
Definition at line 115 of file tcp-option-winscale.cc.
References m_scale, and NS_ASSERT.
Referenced by TcpOptionWSTestCase::TestSerialize().
Member Data Documentation
m_scale
uint8_t ns3::TcpOptionWinScale::m_scale protected
Window scaling in number of bit shift.
Definition at line 86 of file tcp-option-winscale.h.
Referenced by Deserialize(), GetScale(), Print(), Serialize(), and SetScale().
The documentation for this class was generated from the following files:
src/internet/model/tcp-option-winscale.h
src/internet/model/tcp-option-winscale.cc