ns-3: MobilityTraceTestCase Class Reference
MobilityTraceTestCase Class Reference
Mobility » mobility module tests | Test suites
Mobility Trace Test Case.
Public Member Functions
MobilityTraceTestCase ()
virtual ~MobilityTraceTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Mobility Trace Test Case.
Definition at line 45 of file mobility-trace-test-suite.cc.
Constructor & Destructor Documentation
MobilityTraceTestCase()
MobilityTraceTestCase::MobilityTraceTestCase ()
Definition at line 55 of file mobility-trace-test-suite.cc.
~MobilityTraceTestCase()
MobilityTraceTestCase::~MobilityTraceTestCase () virtual
Definition at line 61 of file mobility-trace-test-suite.cc.
Member Function Documentation
DoRun()
void MobilityTraceTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 66 of file mobility-trace-test-suite.cc.
References ns3::NodeContainer::Create(), ns3::TestCase::CreateDataDirFilename(), ns3::AsciiTraceHelper::CreateFileStream(), ns3::TestCase::CreateTempDirFilename(), third::mobility, NS_ASCII_TEST_EXPECT_EQ, ns3::Seconds(), and ns3::TestCase::SetDataDir().
The documentation for this class was generated from the following file:
src/mobility/test/mobility-trace-test-suite.cc