ns-3: ns3::Ipv6Option Class Reference
ns3::Ipv6Option Class Reference abstract
Internet » IPv6 classes and sub-modules » IPV6 Header extension system.
IPv6 Option base.
#include "ipv6-option.h"
Public Member Functions
virtual ~Ipv6Option ()
Destructor.
virtual uint8_t GetOptionNumber () const =0
Get the option number.
virtual uint8_t Process (Ptr< Packet > packet, uint8_t offset, Ipv6Header const &ipv6Header, bool &isDropped)=0
Process method.
void SetNode (Ptr< Node > node)
Set the node.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Ptr< Node > m_node
The node.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
IPv6 Option base.
If you want to implement a new IPv6 option, all you have to do is implement a subclass of this class and add it to an Ipv6OptionDemux.
Definition at line 46 of file ipv6-option.h.
Constructor & Destructor Documentation
~Ipv6Option()
ns3::Ipv6Option::~Ipv6Option () virtual
Destructor.
Definition at line 47 of file ipv6-option.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
GetOptionNumber()
virtual uint8_t ns3::Ipv6Option::GetOptionNumber () const pure virtual
Get the option number.
Returns
option number
Implemented in ns3::Ipv6OptionRouterAlert, ns3::Ipv6OptionJumbogram, ns3::Ipv6OptionPadn, and ns3::Ipv6OptionPad1.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::Ipv6Option::GetTypeId () static
Get the type identificator.
Returns
type identificator
Definition at line 34 of file ipv6-option.cc.
References GetOptionNumber(), ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
Process()
virtual uint8_t ns3::Ipv6Option::Process (Ptr< Packet > packet, uint8_t offset, Ipv6Header const & ipv6Header, bool & isDropped) pure virtual
Process method.
Called from Ipv6L3Protocol::Receive.
Parameters
packet the packet
offset the offset of the extension to process
ipv6Header the IPv6 header of packet received
isDropped if the packet must be dropped
Returns
the processed size
Implemented in ns3::Ipv6OptionRouterAlert, ns3::Ipv6OptionJumbogram, ns3::Ipv6OptionPadn, and ns3::Ipv6OptionPad1.
SetNode()
void ns3::Ipv6Option::SetNode (Ptr< Node > node)
Set the node.
Parameters
node the node to set
Definition at line 52 of file ipv6-option.cc.
References m_node, and NS_LOG_FUNCTION.
Member Data Documentation
m_node
Ptr<Node> ns3::Ipv6Option::m_node private
The node.
Definition at line 88 of file ipv6-option.h.
Referenced by SetNode().
The documentation for this class was generated from the following files:
src/internet/model/ipv6-option.h
src/internet/model/ipv6-option.cc