ns-3: ns3::MacLow Class Reference
ns3::MacLow Class Reference
Wifi Models
handle RTS/CTS/Data/Ack transactions.
#include "mac-low.h"
Classes
struct CfAckInfo
A struct that holds information about Ack piggybacking (CF-Ack).
Public Types
typedef Callback< void, Ptr< WifiMacQueueItem > > MacLowRxCallback
typedef for a callback for MacLowRx
Public Member Functions
MacLow ()
virtual ~MacLow ()
Time CalculateOverallTxTime (Ptr< const Packet > packet, const WifiMacHeader *hdr, const MacLowTransmissionParameters &params, uint32_t fragmentSize=0) const
Time CalculateOverheadTxTime (Ptr< const WifiMacQueueItem > item, const MacLowTransmissionParameters &params) const
Time CalculateTransmissionTime (Ptr< const Packet > packet, const WifiMacHeader *hdr, const MacLowTransmissionParameters &parameters) const
bool CanTransmitNextCfFrame (void) const
This function decides if a CF frame can be transmitted in the current CFP.
void CreateBlockAckAgreement (const MgtAddBaResponseHeader *respHdr, Mac48Address originator, uint16_t startingSeq)
void DeaggregateAmpduAndReceive (Ptr< WifiPsdu > aggregatedPacket, double rxSnr, WifiTxVector txVector, std::vector< bool > statusPerMpdu)
void DestroyBlockAckAgreement (Mac48Address originator, uint8_t tid)
bool DoNavStartNow (Time duration)
Start NAV with the given duration.
Time GetAckTimeout (void) const
Return Ack timeout of this MacLow.
Mac48Address GetAddress (void) const
Return the MAC address of this MacLow.
Time GetBasicBlockAckTimeout (void) const
Return Basic BlockAck timeout of this MacLow.
Time GetBeaconInterval (void) const
Mac48Address GetBssid (void) const
Return the Basic Service Set Identification.
Time GetCfpMaxDuration (void) const
Time GetCompressedBlockAckTimeout (void) const
Return Compressed BlockAck timeout of this MacLow.
bool GetCtsToSelfSupported (void) const
Return whether CTS-to-self capability is supported.
virtual WifiTxVector GetDataTxVector (Ptr< const WifiMacQueueItem > item) const
Return a TXVECTOR for the Data frame given the destination.
Ptr< QosTxop > GetEdca (uint8_t tid) const
Ptr< MpduAggregator > GetMpduAggregator (void) const
Returns the aggregator used to construct A-MPDU subframes.
Ptr< MsduAggregator > GetMsduAggregator (void) const
Returns the aggregator used to construct A-MSDU subframes.
Ptr< WifiPhy > GetPhy (void) const
Time GetPifs (void) const
Return PCF Interframe Space (PIFS) of this MacLow.
Time GetRemainingCfpDuration (void) const
Time GetRifs (void) const
Return Reduced Interframe Space (RIFS) of this MacLow.
Time GetSifs (void) const
Return Short Interframe Space (SIFS) of this MacLow.
Time GetSlotTime (void) const
Return slot duration of this MacLow.
virtual bool IsCfPeriod (void) const
This function indicates whether Simulator::Now is in the CF period.
bool IsPromisc (void) const
Check if MacLow is operating in promiscuous mode.
bool IsWithinSizeAndTimeLimits (Ptr< const WifiMacQueueItem > mpdu, WifiTxVector txVector, uint32_t ampduSize, Time ppduDurationLimit)
Check whether the given MPDU, if transmitted according to the given TX vector, meets the constraint on the maximum A-MPDU size (by assuming that the frame has to be aggregated to an existing A-MPDU of the given size) and its transmission time exceeds neither the max PPDU duration (depending on the PPDU format) nor the given PPDU duration limit (if strictly positive).
bool IsWithinSizeAndTimeLimits (uint32_t mpduSize, Mac48Address receiver, uint8_t tid, WifiTxVector txVector, uint32_t ampduSize, Time ppduDurationLimit)
Check whether an MPDU of the given size, destined to the given receiver and belonging to the given TID, if transmitted according to the given TX vector, meets the constraint on the maximum A-MPDU size (by assuming that the frame has to be aggregated to an existing A-MPDU of the given size) and its transmission time exceeds neither the max PPDU duration (depending on the PPDU format) nor the given PPDU duration limit (if strictly positive).
void NotifyOffNow (void)
This method is typically invoked by the PhyMacLowListener to notify the MAC layer that the device has been put into off mode.
void NotifySleepNow (void)
This method is typically invoked by the PhyMacLowListener to notify the MAC layer that the device has been put into sleep mode.
void NotifySwitchingStartNow (Time duration)
void ReceiveError (Ptr< WifiPsdu > psdu)
void ReceiveOk (Ptr< WifiMacQueueItem > mpdu, double rxSnr, WifiTxVector txVector, bool ampduSubframe)
void RegisterChannelAccessManager (Ptr< ChannelAccessManager > channelAccessManager)
void RegisterEdcaForAc (AcIndex ac, Ptr< QosTxop > edca)
void ResetPhy (void)
Remove WifiPhy associated with this MacLow.
void RxStartIndication (WifiTxVector txVector, Time psduDuration)
void SetAckTimeout (Time ackTimeout)
Set Ack timeout of this MacLow.
void SetAddress (Mac48Address ad)
Set MAC address of this MacLow.
void SetBasicBlockAckTimeout (Time blockAckTimeout)
Set Basic BlockAck timeout of this MacLow.
void SetBeaconInterval (Time interval)
void SetBssid (Mac48Address ad)
Set the Basic Service Set Identification.
void SetCfpMaxDuration (Time duration)
void SetCompressedBlockAckTimeout (Time blockAckTimeout)
Set Compressed BlockAck timeout of this MacLow.
void SetCtsToSelfSupported (bool enable)
Enable or disable CTS-to-self capability.
void SetMac (const Ptr< WifiMac > mac)
Set up WifiMac associated with this MacLow.
void SetMpduAggregator (const Ptr< MpduAggregator > aggr)
Set the aggregator used to construct A-MPDU subframes.
void SetMsduAggregator (const Ptr< MsduAggregator > aggr)
Set the aggregator used to construct A-MSDU subframes.
void SetPhy (const Ptr< WifiPhy > phy)
Set up WifiPhy associated with this MacLow.
void SetPifs (Time pifs)
Set PCF Interframe Space (PIFS) of this MacLow.
void SetPromisc (void)
Enable promiscuous mode.
void SetRifs (Time rifs)
Set Reduced Interframe Space (RIFS) of this MacLow.
void SetRxCallback (Callback< void, Ptr< WifiMacQueueItem >> callback)
void SetSifs (Time sifs)
Set Short Interframe Space (SIFS) of this MacLow.
void SetSlotTime (Time slotTime)
Set slot duration of this MacLow.
void SetWifiRemoteStationManager (const Ptr< WifiRemoteStationManager > manager)
Set up WifiRemoteStationManager associated with this MacLow.
virtual void StartTransmission (Ptr< WifiMacQueueItem > mpdu, MacLowTransmissionParameters parameters, Ptr< Txop > txop)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef std::pair< Mac48Address, uint8_t > AgreementKey
agreement key typedef
typedef std::map< AgreementKey, AgreementValue > Agreements
agreements
typedef std::map< AgreementKey, AgreementValue >::iterator AgreementsI
agreements iterator
typedef std::pair< BlockAckAgreement, std::list< Ptr< WifiMacQueueItem > > > AgreementValue
agreement value typedef
typedef std::map< AgreementKey, BlockAckCache > BlockAckCaches
block ack caches typedef
typedef std::map< AgreementKey, BlockAckCache >::iterator BlockAckCachesI
block ack caches iterator typedef
typedef std::list< Ptr< WifiMacQueueItem > >::iterator BufferedPacketI
buffered packet iterator typedef
typedef std::vector< Ptr< ChannelAccessManager > > ChannelAccessManagers
typedef for a list of ChannelAccessManager.
typedef std::vector< Ptr< ChannelAccessManager > >::const_iterator ChannelAccessManagersCI
typedef for an iterator for a list of ChannelAccessManager.
typedef std::map< AcIndex, Ptr< QosTxop > > QueueEdcas
EDCA queues typedef.
Private Member Functions
void BlockAckTimeout (void)
Event handler when BlockAck timeout occurs.
void CancelAllEvents (void)
Cancel all scheduled events.
void CfPollTimeout (void)
Event handler when CF-Poll timeout occurs.
void CtsTimeout (void)
Event handler when CTS timeout occurs.
void DoDispose (void)
Destructor implementation.
void DoNavResetNow (Time duration)
Reset NAV with the given duration.
void EndTxNoAck (void)
A transmission that does not require an Ack has completed.
void ForwardDown (Ptr< const WifiPsdu > psdu, WifiTxVector txVector)
Forward a PSDU down to WifiPhy for transmission.
Time GetAckDuration (Mac48Address to, WifiTxVector dataTxVector) const
Return the time required to transmit the Ack to the specified address given the TXVECTOR of the Data (including preamble and FCS).
Time GetAckDuration (WifiTxVector ackTxVector) const
Return the time required to transmit the Ack (including preamble and FCS).
WifiTxVector GetAckTxVector (Mac48Address to, WifiMode dataTxMode) const
Return a TXVECTOR for the Ack frame given the destination and the mode of the Data used by the sender.
WifiTxVector GetAckTxVectorForData (Mac48Address to, WifiMode dataTxMode) const
Return a TXVECTOR for the BlockAck frame given the destination and the mode of the Data used by the sender.
Time GetBlockAckDuration (WifiTxVector blockAckReqTxVector, BlockAckType type) const
Return the time required to transmit the BlockAck to the specified address given the TXVECTOR of the BAR (including preamble and FCS).
Time GetBlockAckRequestDuration (WifiTxVector blockAckReqTxVector, BlockAckType type) const
Return the time required to transmit the BlockAckRequest to the specified address given the TXVECTOR (including preamble and FCS).
WifiTxVector GetBlockAckTxVector (Mac48Address to, WifiMode dataTxMode) const
Return a TXVECTOR for the BlockAck frame given the destination and the mode of the Data used by the sender.
uint32_t GetCfEndSize (void) const
Return the total CF-END size (including FCS trailer).
WifiMode GetControlAnswerMode (WifiMode reqMode) const
Get control answer mode function.
Time GetCtsDuration (Mac48Address to, WifiTxVector rtsTxVector) const
Return the time required to transmit the CTS to the specified address given the TXVECTOR of the RTS (including preamble and FCS).
Time GetCtsDuration (WifiTxVector ctsTxVector) const
Return the time required to transmit the CTS (including preamble and FCS).
WifiTxVector GetCtsTxVector (Mac48Address to, WifiMode rtsTxMode) const
Return a TXVECTOR for the CTS frame given the destination and the mode of the RTS used by the sender.
WifiTxVector GetCtsTxVectorForRts (Mac48Address to, WifiMode rtsTxMode) const
Return a TXVECTOR for the CTS frame given the destination and the mode of the RTS used by the sender.
Time GetResponseDuration (const MacLowTransmissionParameters &params, WifiTxVector dataTxVector, Mac48Address receiver) const
Return the time required to transmit the response frames (Ack or BAR+BA following the policy configured in the transmit parameters).
WifiTxVector GetRtsTxVector (Ptr< const WifiMacQueueItem > item) const
Return a TXVECTOR for the RTS frame given the destination.
bool IsNavZero (void) const
Check if NAV is zero.
bool NeedCtsToSelf (void) const
Check if CTS-to-self mechanism should be used for the current packet.
void NormalAckTimeout (void)
Event handler when normal Ack timeout occurs.
void NotifyAckTimeoutResetNow (void)
Notify ChannelAccessManager that Ack timer should be reset.
void NotifyAckTimeoutStartNow (Time duration)
Notify ChannelAccessManager that Ack timer should be started for the given duration.
void NotifyCtsTimeoutResetNow (void)
Notify ChannelAccessManager that CTS timer should be reset.
void NotifyCtsTimeoutStartNow (Time duration)
Notify ChannelAccessManager that CTS timer should be started for the given duration.
void NotifyNav (Ptr< const Packet > packet, const WifiMacHeader &hdr)
Notify NAV function.
bool ReceiveMpdu (Ptr< WifiMacQueueItem > mpdu)
void RemovePhyMacLowListener (Ptr< WifiPhy > phy)
Remove current WifiPhy listener for this MacLow.
void ResetBlockAckInactivityTimerIfNeeded (BlockAckAgreement &agreement)
Every time that a BlockAckRequest or a packet with Ack Policy equals to Block Ack are received, if a relative block ack agreement exists and the value of inactivity timeout is not 0, the timer is reset.
void RxCompleteBufferedPacketsUntilFirstLost (Mac48Address originator, uint8_t tid)
void RxCompleteBufferedPacketsWithSmallerSequence (uint16_t seq, Mac48Address originator, uint8_t tid)
void SendAckAfterData (Mac48Address source, Time duration, WifiMode dataTxMode, double dataSnr)
Send Ack after receiving Data.
void SendBlockAckAfterAmpdu (uint8_t tid, Mac48Address originator, Time duration, WifiTxVector blockAckReqTxVector, double rxSnr)
Invoked after an A-MPDU has been received.
void SendBlockAckAfterBlockAckRequest (const CtrlBAckRequestHeader reqHdr, Mac48Address originator, Time duration, WifiMode blockAckReqTxMode, double rxSnr)
Invoked after that a BlockAckRequest has been received.
void SendBlockAckResponse (const CtrlBAckResponseHeader *blockAck, Mac48Address originator, bool immediate, Time duration, WifiMode blockAckReqTxMode, double rxSnr)
This method creates BlockAck frame with header equals to blockAck and start its transmission.
void SendCtsAfterRts (Mac48Address source, Time duration, WifiTxVector rtsTxVector, double rtsSnr)
Send CTS after receiving RTS.
void SendCtsToSelf (void)
Send CTS for a CTS-to-self mechanism.
void SendDataAfterCts (Time duration)
Send Data after receiving CTS.
void SendDataPacket (void)
Send Data packet, which can be Data-Ack or RTS-CTS-Data-Ack transaction.
void SendRtsForPacket (void)
Send RTS to begin RTS-CTS-Data-Ack transaction.
void SetupPhyMacLowListener (const Ptr< WifiPhy > phy)
Set up WifiPhy listener for this MacLow.
void StartDataTxTimers (WifiTxVector dataTxVector)
Start a Data timer by scheduling appropriate Ack timeout.
bool StoreMpduIfNeeded (Ptr< WifiMacQueueItem > mpdu)
void WaitIfsAfterEndTxFragment (void)
Event handler that is usually scheduled to fired at the appropriate time after completing transmissions.
void WaitIfsAfterEndTxPacket (void)
Event handler that is usually scheduled to fired at the appropriate time after sending a packet.
Private Attributes
Time m_ackTimeout
Ack timeout duration.
Agreements m_bAckAgreements
block ack agreements
BlockAckCaches m_bAckCaches
block ack caches
Time m_basicBlockAckTimeout
Basic BlockAck timeout duration.
Time m_beaconInterval
Expected interval between two beacon transmissions.
EventId m_blockAckTimeoutEvent
BlockAck timeout event.
Mac48Address m_bssid
BSSID address (Mac48Address)
CfAckInfo m_cfAckInfo
Info about piggyback Acks used in PCF.
Time m_cfpForeshortening
The delay the current CF period should be foreshortened.
Time m_cfpMaxDuration
CFP max duration.
Time m_cfpStart
The time when the latest CF period started.
ChannelAccessManagers m_channelAccessManagers
List of ChannelAccessManager.
Time m_compressedBlockAckTimeout
Compressed BlockAck timeout duration.
EventId m_ctsTimeoutEvent
CTS timeout event.
bool m_ctsToSelfSupported
Flag whether CTS-to-self is supported.
Ptr< WifiPsdu > m_currentPacket
Current packet transmitted/to be transmitted.
Ptr< Txop > m_currentTxop
Current TXOP.
WifiTxVector m_currentTxVector
TXVECTOR used for the current packet transmission.
QueueEdcas m_edca
EDCA queues.
EventId m_endTxNoAckEvent
Event for finishing transmission that does not require Ack.
Time m_lastBeacon
The time when the last beacon frame transmission started.
Time m_lastNavDuration
The duration of the latest NAV.
Time m_lastNavStart
The time when the latest NAV started.
Ptr< WifiMac > m_mac
Pointer to WifiMac (to fetch configuration)
Ptr< MpduAggregator > m_mpduAggregator
A-MPDU aggregator.
Ptr< MsduAggregator > m_msduAggregator
A-MSDU aggregator.
EventId m_navCounterResetCtsMissed
Event to reset NAV when CTS is not received.
EventId m_normalAckTimeoutEvent
Normal Ack timeout event.
Ptr< WifiPhy > m_phy
Pointer to WifiPhy (actually send/receives frames)
class PhyMacLowListener * m_phyMacLowListener
Listener needed to monitor when a channel switching occurs.
Time m_pifs
PCF Interframe Space (PIFS) duration.
bool m_promisc
Flag if the device is operating in promiscuous mode.
Time m_rifs
Reduced Interframe Space (RIFS) duration.
MacLowRxCallback m_rxCallback
Callback to pass packet up.
Mac48Address m_self
Address of this MacLow (Mac48Address)
EventId m_sendAckEvent
Event to send Ack.
EventId m_sendCtsEvent
Event to send CTS.
EventId m_sendDataEvent
Event to send Data.
Time m_sifs
Short Interframe Space (SIFS) duration.
Time m_slotTime
Slot duration.
Ptr< WifiRemoteStationManager > m_stationManager
Pointer to WifiRemoteStationManager (rate control)
MacLowTransmissionParameters m_txParams
Transmission parameters of the current packet.
EventId m_waitIfsEvent
Wait for IFS event.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
handle RTS/CTS/Data/Ack transactions.
Definition at line 59 of file mac-low.h.
Member Typedef Documentation
AgreementKey
typedef std::pair<Mac48Address, uint8_t> ns3::MacLow::AgreementKey private
agreement key typedef
Definition at line 963 of file mac-low.h.
Agreements
typedef std::map<AgreementKey, AgreementValue> ns3::MacLow::Agreements private
agreements
Definition at line 966 of file mac-low.h.
AgreementsI
typedef std::map<AgreementKey, AgreementValue>::iterator ns3::MacLow::AgreementsI private
agreements iterator
Definition at line 967 of file mac-low.h.
AgreementValue
typedef std::pair<BlockAckAgreement, std::list<Ptr<WifiMacQueueItem> > > ns3::MacLow::AgreementValue private
agreement value typedef
Definition at line 964 of file mac-low.h.
BlockAckCaches
typedef std::map<AgreementKey, BlockAckCache> ns3::MacLow::BlockAckCaches private
block ack caches typedef
Definition at line 969 of file mac-low.h.
BlockAckCachesI
typedef std::map<AgreementKey, BlockAckCache>::iterator ns3::MacLow::BlockAckCachesI private
block ack caches iterator typedef
Definition at line 970 of file mac-low.h.
BufferedPacketI
typedef std::list<Ptr<WifiMacQueueItem> >::iterator ns3::MacLow::BufferedPacketI private
buffered packet iterator typedef
Definition at line 961 of file mac-low.h.
ChannelAccessManagers
typedef std::vector<Ptr<ChannelAccessManager> > ns3::MacLow::ChannelAccessManagers private
typedef for a list of ChannelAccessManager.
Definition at line 915 of file mac-low.h.
ChannelAccessManagersCI
typedef std::vector<Ptr<ChannelAccessManager> >::const_iterator ns3::MacLow::ChannelAccessManagersCI private
typedef for an iterator for a list of ChannelAccessManager.
Definition at line 911 of file mac-low.h.
MacLowRxCallback
typedef Callback<void, Ptr<WifiMacQueueItem> > ns3::MacLow::MacLowRxCallback
typedef for a callback for MacLowRx
Definition at line 66 of file mac-low.h.
QueueEdcas
typedef std::map<AcIndex, Ptr<QosTxop> > ns3::MacLow::QueueEdcas private
EDCA queues typedef.
Definition at line 975 of file mac-low.h.
Constructor & Destructor Documentation
MacLow()
ns3::MacLow::MacLow ()
Definition at line 116 of file mac-low.cc.
References NS_LOG_FUNCTION.
~MacLow()
ns3::MacLow::~MacLow () virtual
Definition at line 142 of file mac-low.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
BlockAckTimeout()
void ns3::MacLow::BlockAckTimeout (void) private
Event handler when BlockAck timeout occurs.
Definition at line 1803 of file mac-low.cc.
References m_currentPacket, m_currentTxop, ns3::Txop::MissedBlockAck(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by RxStartIndication(), and StartDataTxTimers().
CalculateOverallTxTime()
Time ns3::MacLow::CalculateOverallTxTime (Ptr< const Packet > packet, const WifiMacHeader * hdr, const MacLowTransmissionParameters & params, uint32_t fragmentSize = 0) const
Parameters
packet to send (does not include the 802.11 MAC header and checksum)
hdr header associated to the packet to send.
params transmission parameters of packet.
fragmentSize the packet fragment size (if fragmentation is used) in bytes
Returns
the transmission time that includes the time for the next packet transmission
This transmission time does not include the time required for the next packet transmission if one was selected.
Definition at line 1519 of file mac-low.cc.
References CalculateOverheadTxTime(), ns3::WifiPhy::CalculateTxDuration(), GetDataTxVector(), ns3::WifiPhy::GetFrequency(), ns3::GetSize(), m_currentPacket, m_phy, and aloha::params.
Referenced by CalculateTransmissionTime().
CalculateOverheadTxTime()
Time ns3::MacLow::CalculateOverheadTxTime (Ptr< const WifiMacQueueItem > item, const MacLowTransmissionParameters & params) const
Parameters
item packet to send (does not include the 802.11 MAC header and checksum)
params transmission parameters of packet.
Returns
the transmission time that does not include the time required to transmit the frame
This transmission time only includes the time for the RTS/CTS exchange (if any) and for the Ack frame (if any).
Definition at line 1541 of file mac-low.cc.
References ns3::WifiPhy::CalculateTxDuration(), GetCtsDuration(), GetDataTxVector(), ns3::WifiPhy::GetFrequency(), GetResponseDuration(), ns3::GetRtsSize(), GetRtsTxVector(), GetSifs(), m_phy, aloha::params, and ns3::Seconds().
Referenced by CalculateOverallTxTime(), and StartTransmission().
CalculateTransmissionTime()
Time ns3::MacLow::CalculateTransmissionTime (Ptr< const Packet > packet, const WifiMacHeader * hdr, const MacLowTransmissionParameters & parameters) const
Parameters
packet to send (does not include the 802.11 MAC header and checksum)
hdr header associated to the packet to send.
parameters transmission parameters of packet.
Returns
the transmission time that includes the time for the next packet transmission
This transmission time includes the time required for the next packet transmission if one was selected.
Definition at line 1558 of file mac-low.cc.
References CalculateOverallTxTime(), ns3::WifiPhy::CalculateTxDuration(), GetDataTxVector(), ns3::WifiPhy::GetFrequency(), GetSifs(), m_phy, and aloha::params.
Referenced by ns3::WaveMacLow::StartTransmission().
CancelAllEvents()
void ns3::MacLow::CancelAllEvents (void) private
Cancel all scheduled events.
Called before beginning a transmission or switching channel.
Definition at line 201 of file mac-low.cc.
References ns3::EventId::Cancel(), ns3::Txop::Cancel(), ns3::EventId::IsRunning(), m_blockAckTimeoutEvent, m_ctsTimeoutEvent, m_currentTxop, m_endTxNoAckEvent, m_normalAckTimeoutEvent, m_sendAckEvent, m_sendCtsEvent, m_sendDataEvent, m_waitIfsEvent, and NS_LOG_FUNCTION.
Referenced by NotifyOffNow(), NotifySleepNow(), NotifySwitchingStartNow(), and StartTransmission().
CanTransmitNextCfFrame()
bool ns3::MacLow::CanTransmitNextCfFrame (void) const
This function decides if a CF frame can be transmitted in the current CFP.
Returns
true if a CF frame can be transmitted in the current CFP, false otherwise
Definition at line 2698 of file mac-low.cc.
References ns3::WifiPhy::CalculateTxDuration(), GetCfEndSize(), ns3::WifiPhy::GetFrequency(), GetRemainingCfpDuration(), ns3::WifiMacHeader::GetSerializedSize(), ns3::WifiMacTrailer::GetSerializedSize(), GetSifs(), IsCfPeriod(), m_currentTxVector, m_phy, ns3::MAX_MSDU_SIZE, NS_ASSERT, NS_LOG_FUNCTION, ns3::WifiMacHeader::SetType(), and ns3::WIFI_MAC_DATA.
CfPollTimeout()
void ns3::MacLow::CfPollTimeout (void) private
Event handler when CF-Poll timeout occurs.
Definition at line 1750 of file mac-low.cc.
References ns3::MacLow::CfAckInfo::expectCfAck, m_cfAckInfo, m_channelAccessManagers, m_currentTxop, ns3::Txop::MissedCfPollResponse(), NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ForwardDown().
CreateBlockAckAgreement()
void ns3::MacLow::CreateBlockAckAgreement (const MgtAddBaResponseHeader * respHdr, Mac48Address originator, uint16_t startingSeq)
Parameters
respHdr Add block ack response from originator (action frame).
originator Address of peer station involved in block ack mechanism.
startingSeq Sequence number of the first MPDU of all packets for which block ack was negotiated.
This function is typically invoked only by ns3::RegularWifiMac when the STA (which may be non-AP in ESS, or in an IBSS) has received an ADDBA Request frame and is transmitting an ADDBA Response frame. At this point MacLow must allocate buffers to collect all correctly received packets belonging to the category for which block ack was negotiated.
Definition at line 2259 of file mac-low.cc.
References ns3::MgtAddBaResponseHeader::GetBufferSize(), ns3::BlockAckAgreement::GetTid(), ns3::MgtAddBaResponseHeader::GetTid(), ns3::BlockAckAgreement::GetTimeout(), ns3::MgtAddBaResponseHeader::GetTimeout(), ns3::BlockAckCache::Init(), ns3::MgtAddBaResponseHeader::IsAmsduSupported(), ns3::MgtAddBaResponseHeader::IsImmediateBlockAck(), m_bAckAgreements, m_bAckCaches, m_edca, ns3::MicroSeconds(), NS_LOG_FUNCTION, ns3::QosUtilsMapTidToAc(), ns3::Simulator::Schedule(), ns3::QosTxop::SendDelbaFrame(), ns3::BlockAckAgreement::SetAmsduSupport(), ns3::BlockAckAgreement::SetBufferSize(), ns3::BlockAckAgreement::SetDelayedBlockAck(), ns3::BlockAckAgreement::SetImmediateBlockAck(), ns3::BlockAckAgreement::SetStartingSequence(), ns3::BlockAckAgreement::SetTimeout(), and timeout.
CtsTimeout()
void ns3::MacLow::CtsTimeout (void) private
Event handler when CTS timeout occurs.
Todo:
should check that there was no RX start before now. we should restart a new CTS timeout now until the expected end of RX if there was a RX start before now.
Definition at line 1768 of file mac-low.cc.
References list, m_currentPacket, m_currentTxop, m_stationManager, ns3::Txop::MissedCts(), ns3::QosTxop::NotifyMissedCts(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::WifiRemoteStationManager::ReportRtsFailed().
Referenced by RxStartIndication(), and SendRtsForPacket().
DeaggregateAmpduAndReceive()
void ns3::MacLow::DeaggregateAmpduAndReceive (Ptr< WifiPsdu > aggregatedPacket, double rxSnr, WifiTxVector txVector, std::vector< bool > statusPerMpdu)
Parameters
aggregatedPacket which is the current A-MPDU
rxSnr SNR of packet received in linear scale
txVector TXVECTOR of packet received
statusPerMpdu reception status per MPDU
This function de-aggregates an A-MPDU and decide if each MPDU is received correctly or not
Definition at line 2585 of file mac-low.cc.
References ns3::WifiMacHeader::GetAddr1(), ns3::WifiMacHeader::GetAddr2(), ns3::WifiMacHeader::GetDuration(), ns3::WifiMacHeader::GetQosTid(), ns3::WifiMacHeader::GetSequenceNumber(), GetSifs(), ns3::WifiMacHeader::IsAck(), ns3::WifiTxVector::IsAggregation(), ns3::WifiMacHeader::IsBlockAck(), ns3::WifiMacHeader::IsBlockAckReq(), ns3::WifiMacHeader::IsData(), ns3::WifiMacHeader::IsQosAck(), ns3::WifiMacHeader::IsQosData(), ns3::EventId::IsRunning(), m_bAckAgreements, m_self, m_sendAckEvent, sample-rng-plot::n, NotifyNav(), NS_ABORT_MSG_IF, NS_ASSERT, NS_FATAL_ERROR, NS_LOG_DEBUG, NS_LOG_FUNCTION, ReceiveOk(), ResetBlockAckInactivityTimerIfNeeded(), ns3::Simulator::Schedule(), and SendBlockAckAfterAmpdu().
Referenced by SetPhy().
DestroyBlockAckAgreement()
void ns3::MacLow::DestroyBlockAckAgreement (Mac48Address originator, uint8_t tid)
Parameters
originator Address of peer participating in block ack mechanism.
tid TID for which block ack was created.
Checks if exists an established block ack agreement with originator for TID tid. If the agreement exists, tears down it. This function is typically invoked when a DELBA frame is received from originator.
Definition at line 2301 of file mac-low.cc.
References m_bAckAgreements, m_bAckCaches, NS_ASSERT, NS_LOG_FUNCTION, RxCompleteBufferedPacketsUntilFirstLost(), and RxCompleteBufferedPacketsWithSmallerSequence().
DoDispose()
void ns3::MacLow::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 178 of file mac-low.cc.
References ns3::EventId::Cancel(), m_blockAckTimeoutEvent, m_ctsTimeoutEvent, m_endTxNoAckEvent, m_mpduAggregator, m_msduAggregator, m_normalAckTimeoutEvent, m_phy, m_phyMacLowListener, m_sendAckEvent, m_sendCtsEvent, m_sendDataEvent, m_stationManager, m_waitIfsEvent, and NS_LOG_FUNCTION.
DoNavResetNow()
void ns3::MacLow::DoNavResetNow (Time duration) private
Reset NAV with the given duration.
Parameters
duration the duration to set
Definition at line 1618 of file mac-low.cc.
References aloha::duration, m_channelAccessManagers, m_lastNavDuration, m_lastNavStart, ns3::Simulator::Now(), and NS_LOG_FUNCTION.
Referenced by NotifyNav().
DoNavStartNow()
bool ns3::MacLow::DoNavStartNow (Time duration)
Start NAV with the given duration.
Parameters
duration the duration
Returns
true if NAV is reset
Definition at line 1630 of file mac-low.cc.
References aloha::duration, m_channelAccessManagers, m_lastNavDuration, m_lastNavStart, and ns3::Simulator::Now().
Referenced by NotifyNav().
EndTxNoAck()
void ns3::MacLow::EndTxNoAck (void) private
A transmission that does not require an Ack has completed.
Definition at line 2142 of file mac-low.cc.
References ns3::Txop::EndTxNoAck(), ns3::MacLow::CfAckInfo::expectCfAck, ns3::WifiRemoteStationManager::GetPcfSupported(), IsCfPeriod(), m_cfAckInfo, m_cfpStart, m_currentPacket, m_currentTxop, m_stationManager, ns3::Simulator::Now(), and NS_LOG_FUNCTION.
Referenced by StartDataTxTimers().
ForwardDown()
void ns3::MacLow::ForwardDown (Ptr< const WifiPsdu > psdu, WifiTxVector txVector) private
Forward a PSDU down to WifiPhy for transmission.
Parameters
psdu the PSDU
txVector the transmit vector
Definition at line 1684 of file mac-low.cc.
References ns3::MacLow::CfAckInfo::appendCfAck, ns3::WifiPhy::CalculateTxDuration(), CfPollTimeout(), ns3::MacLow::CfAckInfo::expectCfAck, ns3::WifiMacHeader::GetAddr1(), ns3::WifiMacHeader::GetDuration(), ns3::WifiPhy::GetFrequency(), ns3::WifiTxVector::GetMode(), ns3::WifiRemoteStationManager::GetPcfSupported(), GetPifs(), ns3::WifiTxVector::GetPreambleType(), ns3::WifiMacHeader::GetSequenceControl(), ns3::WifiMacHeader::GetTypeString(), ns3::WifiMacHeader::HasData(), ns3::WifiMacHeader::IsBeacon(), ns3::WifiMacHeader::IsCfEnd(), IsCfPeriod(), ns3::WifiMacHeader::IsCfPoll(), m_beaconInterval, m_cfAckInfo, m_cfpForeshortening, m_cfpStart, m_edca, m_lastBeacon, m_phy, m_stationManager, ns3::NanoSeconds(), ns3::Simulator::Now(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::PeekPointer(), ns3::QosUtilsMapTidToAc(), ns3::Simulator::Schedule(), ns3::WifiPhy::Send(), and ns3::WifiTxVector::SetAggregation().
Referenced by SendAckAfterData(), SendBlockAckResponse(), SendCtsAfterRts(), SendCtsToSelf(), SendDataAfterCts(), SendDataPacket(), and SendRtsForPacket().
GetAckDuration() [1/2]
Time ns3::MacLow::GetAckDuration (Mac48Address to, WifiTxVector dataTxVector) const private
Return the time required to transmit the Ack to the specified address given the TXVECTOR of the Data (including preamble and FCS).
Parameters
to the receiver MAC address
dataTxVector the TXVECTOR used to transmit the Data
Returns
the time required to transmit the Ack (including preamble and FCS)
Definition at line 1231 of file mac-low.cc.
References GetAckDuration(), GetAckTxVectorForData(), and ns3::WifiTxVector::GetMode().
GetAckDuration() [2/2]
Time ns3::MacLow::GetAckDuration (WifiTxVector ackTxVector) const private
Return the time required to transmit the Ack (including preamble and FCS).
Parameters
ackTxVector the TXVECTOR used to transmit the Ack
Returns
the time required to transmit the Ack (including preamble and FCS)
Definition at line 1238 of file mac-low.cc.
References ns3::WifiPhy::CalculateTxDuration(), ns3::GetAckSize(), ns3::WifiPhy::GetFrequency(), ns3::WifiTxVector::GetMode(), ns3::WifiMode::GetModulationClass(), m_phy, NS_ASSERT, and ns3::WIFI_MOD_CLASS_HT.
Referenced by GetAckDuration(), GetResponseDuration(), SendAckAfterData(), and SendBlockAckResponse().
GetAckTimeout()
Time ns3::MacLow::GetAckTimeout (void) const
Return Ack timeout of this MacLow.
Returns
Ack timeout
Definition at line 415 of file mac-low.cc.
References m_ackTimeout.
GetAckTxVector()
WifiTxVector ns3::MacLow::GetAckTxVector (Mac48Address to, WifiMode dataTxMode) const private
Return a TXVECTOR for the Ack frame given the destination and the mode of the Data used by the sender.
The function consults WifiRemoteStationManager, which controls the rate to different destinations.
Parameters
to the MAC address of the Ack receiver
dataTxMode the mode of the Data used by the sender
Returns
TXVECTOR for the Ack
Definition at line 1475 of file mac-low.cc.
References ns3::ConvertGuardIntervalToNanoSeconds(), ns3::WifiPhy::GetChannelWidth(), ns3::GetChannelWidthForTransmission(), GetControlAnswerMode(), ns3::WifiRemoteStationManager::GetDefaultTxPowerLevel(), ns3::WifiPhy::GetGuardInterval(), ns3::WifiMode::GetModulationClass(), ns3::GetPreambleForTransmission(), ns3::WifiPhy::GetShortGuardInterval(), ns3::WifiRemoteStationManager::GetShortPreambleEnabled(), ns3::Mac48Address::IsGroup(), m_phy, m_stationManager, NS_ASSERT, ns3::WifiTxVector::SetChannelWidth(), ns3::WifiTxVector::SetGuardInterval(), ns3::WifiTxVector::SetMode(), ns3::WifiTxVector::SetNss(), ns3::WifiTxVector::SetPreambleType(), ns3::WifiTxVector::SetTxPowerLevel(), and ns3::WifiRemoteStationManager::UseGreenfieldForDestination().
Referenced by GetAckTxVectorForData(), SendAckAfterData(), and StartDataTxTimers().
GetAckTxVectorForData()
WifiTxVector ns3::MacLow::GetAckTxVectorForData (Mac48Address to, WifiMode dataTxMode) const private
Return a TXVECTOR for the BlockAck frame given the destination and the mode of the Data used by the sender.
The function consults WifiRemoteStationManager, which controls the rate to different destinations.
Parameters
to the MAC address of the BlockAck receiver
dataTxMode the mode of the Data used by the sender
Returns
TXVECTOR for the BlockAck
Definition at line 1513 of file mac-low.cc.
References GetAckTxVector().
Referenced by GetAckDuration().
GetAddress()
Mac48Address ns3::MacLow::GetAddress (void) const
Return the MAC address of this MacLow.
Returns
Mac48Address of this MacLow
Definition at line 409 of file mac-low.cc.
References m_self.
Referenced by SendBlockAckResponse().
GetBasicBlockAckTimeout()
Time ns3::MacLow::GetBasicBlockAckTimeout (void) const
Return Basic BlockAck timeout of this MacLow.
Returns
Basic BlockAck timeout
Definition at line 421 of file mac-low.cc.
References m_basicBlockAckTimeout.
GetBeaconInterval()
Time ns3::MacLow::GetBeaconInterval (void) const
Returns
the expected interval between two beacon transmissions.
Definition at line 463 of file mac-low.cc.
References m_beaconInterval.
GetBlockAckDuration()
Time ns3::MacLow::GetBlockAckDuration (WifiTxVector blockAckReqTxVector, BlockAckType type) const private
Return the time required to transmit the BlockAck to the specified address given the TXVECTOR of the BAR (including preamble and FCS).
Parameters
blockAckReqTxVector the TXVECTOR used to transmit the BAR
type the BlockAck type
Returns
the time required to transmit the BlockAck (including preamble and FCS)
Definition at line 1245 of file mac-low.cc.
References ns3::WifiPhy::CalculateTxDuration(), ns3::GetBlockAckSize(), ns3::WifiPhy::GetFrequency(), and m_phy.
Referenced by GetResponseDuration(), and SendBlockAckResponse().
GetBlockAckRequestDuration()
Time ns3::MacLow::GetBlockAckRequestDuration (WifiTxVector blockAckReqTxVector, BlockAckType type) const private
Return the time required to transmit the BlockAckRequest to the specified address given the TXVECTOR (including preamble and FCS).
Parameters
blockAckReqTxVector the TX vector used to transmit the BAR
type the BlockAckRequest type
Returns
the time required to transmit the BlockAckRequest (including preamble and FCS)
Definition at line 1255 of file mac-low.cc.
References ns3::WifiPhy::CalculateTxDuration(), ns3::GetBlockAckRequestSize(), ns3::WifiPhy::GetFrequency(), and m_phy.
Referenced by GetResponseDuration().
GetBlockAckTxVector()
WifiTxVector ns3::MacLow::GetBlockAckTxVector (Mac48Address to, WifiMode dataTxMode) const private
Return a TXVECTOR for the BlockAck frame given the destination and the mode of the Data used by the sender.
The function consults WifiRemoteStationManager, which controls the rate to different destinations.
Parameters
to the MAC address of the BlockAck receiver
dataTxMode the mode of the Data used by the sender
Returns
TXVECTOR for the BlockAck
Definition at line 1491 of file mac-low.cc.
References ns3::ConvertGuardIntervalToNanoSeconds(), ns3::WifiPhy::GetChannelWidth(), ns3::GetChannelWidthForTransmission(), GetControlAnswerMode(), ns3::WifiRemoteStationManager::GetDefaultTxPowerLevel(), ns3::WifiPhy::GetGuardInterval(), ns3::WifiMode::GetModulationClass(), ns3::GetPreambleForTransmission(), ns3::WifiPhy::GetShortGuardInterval(), ns3::WifiRemoteStationManager::GetShortPreambleEnabled(), ns3::Mac48Address::IsGroup(), m_phy, m_stationManager, NS_ASSERT, ns3::WifiTxVector::SetChannelWidth(), ns3::WifiTxVector::SetGuardInterval(), ns3::WifiTxVector::SetMode(), ns3::WifiTxVector::SetNss(), ns3::WifiTxVector::SetPreambleType(), ns3::WifiTxVector::SetTxPowerLevel(), and ns3::WifiRemoteStationManager::UseGreenfieldForDestination().
Referenced by GetResponseDuration(), SendBlockAckAfterAmpdu(), SendBlockAckResponse(), and StartDataTxTimers().
GetBssid()
Mac48Address ns3::MacLow::GetBssid (void) const
Return the Basic Service Set Identification.
Returns
BSSID
Definition at line 457 of file mac-low.cc.
References m_bssid.
GetCfEndSize()
uint32_t ns3::MacLow::GetCfEndSize (void) const private
Return the total CF-END size (including FCS trailer).
Returns
the total CF-END size in bytes
Definition at line 1216 of file mac-low.cc.
References ns3::MacLow::CfAckInfo::appendCfAck, ns3::MacLow::CfAckInfo::expectCfAck, ns3::WifiMacHeader::GetSize(), m_cfAckInfo, ns3::WifiMacHeader::SetType(), ns3::WIFI_MAC_CTL_END, and ns3::WIFI_MAC_CTL_END_ACK.
Referenced by CanTransmitNextCfFrame().
GetCfpMaxDuration()
Time ns3::MacLow::GetCfpMaxDuration (void) const
Returns
the maximum duration for the CF period.
Definition at line 469 of file mac-low.cc.
References m_cfpMaxDuration.
GetCompressedBlockAckTimeout()
Time ns3::MacLow::GetCompressedBlockAckTimeout (void) const
Return Compressed BlockAck timeout of this MacLow.
Returns
Compressed BlockAck timeout
Definition at line 427 of file mac-low.cc.
References m_compressedBlockAckTimeout.
GetControlAnswerMode()
WifiMode ns3::MacLow::GetControlAnswerMode (WifiMode reqMode) const private
Get control answer mode function.
Parameters
reqMode request mode
Returns
control answer mode
The standard has relatively unambiguous rules for selecting a control response rate (the below is quoted from IEEE 802.11-2012, Section 9.7):
To allow the transmitting STA to calculate the contents of the Duration/ID field, a STA responding to a received frame shall transmit its Control Response frame (either CTS or Ack), other than the BlockAck control frame, at the highest rate in the BSSBasicRateSet parameter that is less than or equal to the rate of the immediately previous frame in the frame exchange sequence (as defined in Annex G) and that is of the same modulation class (see Section 9.7.8) as the received frame...
If no suitable basic rate was found, we search the mandatory rates. The standard (IEEE 802.11-2007, Section 9.6) says:
...If no rate contained in the BSSBasicRateSet parameter meets these conditions, then the control frame sent in response to a received frame shall be transmitted at the highest mandatory rate of the PHY that is less than or equal to the rate of the received frame, and that is of the same modulation class as the received frame. In addition, the Control Response frame shall be sent using the same PHY options as the received frame, unless they conflict with the requirement to use the BSSBasicRateSet parameter.
Todo:
Note that we're ignoring the last sentence for now, because there is not yet any manipulation here of PHY options.
If we still haven't found a suitable rate for the response then someone has messed up the simulation configuration. This probably means that the WifiPhyStandard is not set correctly, or that a rate that is not supported by the PHY has been explicitly requested.
Either way, it is serious - we can either disobey the standard or fail, and I have chosen to do the latter...
Definition at line 1317 of file mac-low.cc.
References ns3::WifiRemoteStationManager::GetBasicMcs(), ns3::WifiRemoteStationManager::GetBasicMode(), ns3::WifiRemoteStationManager::GetDefaultMcs(), ns3::WifiRemoteStationManager::GetDefaultMode(), ns3::WifiRemoteStationManager::GetHtSupported(), ns3::WifiPhy::GetMcs(), ns3::WifiPhy::GetMode(), ns3::WifiMode::GetModulationClass(), ns3::WifiRemoteStationManager::GetNBasicMcs(), ns3::WifiRemoteStationManager::GetNBasicModes(), ns3::WifiPhy::GetNMcs(), ns3::WifiPhy::GetNModes(), ns3::IsAllowedControlAnswerModulationClass(), ns3::WifiMode::IsHigherCodeRate(), ns3::WifiMode::IsHigherDataRate(), ns3::WifiMode::IsMandatory(), m_phy, m_stationManager, NS_FATAL_ERROR, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by GetAckTxVector(), GetBlockAckTxVector(), and GetCtsTxVector().
GetCtsDuration() [1/2]
Time ns3::MacLow::GetCtsDuration (Mac48Address to, WifiTxVector rtsTxVector) const private
Return the time required to transmit the CTS to the specified address given the TXVECTOR of the RTS (including preamble and FCS).
Parameters
to the receiver MAC address
rtsTxVector the TXVECTOR used to transmit the RTS
Returns
the time required to transmit the CTS (including preamble and FCS)
Definition at line 1261 of file mac-low.cc.
References GetCtsDuration(), GetCtsTxVectorForRts(), and ns3::WifiTxVector::GetMode().
GetCtsDuration() [2/2]
Time ns3::MacLow::GetCtsDuration (WifiTxVector ctsTxVector) const private
Return the time required to transmit the CTS (including preamble and FCS).
Parameters
ctsTxVector the TXVECTOR used to transmit the CTS
Returns
the time required to transmit the CTS (including preamble and FCS)
Definition at line 1268 of file mac-low.cc.
References ns3::WifiPhy::CalculateTxDuration(), ns3::GetCtsSize(), ns3::WifiPhy::GetFrequency(), ns3::WifiTxVector::GetMode(), ns3::WifiMode::GetModulationClass(), m_phy, NS_ASSERT, and ns3::WIFI_MOD_CLASS_HT.
Referenced by CalculateOverheadTxTime(), GetCtsDuration(), SendCtsAfterRts(), and SendRtsForPacket().
GetCtsToSelfSupported()
bool ns3::MacLow::GetCtsToSelfSupported (void) const
Return whether CTS-to-self capability is supported.
Returns
true if CTS-to-self is supported, false otherwise
Definition at line 355 of file mac-low.cc.
References m_ctsToSelfSupported.
GetCtsTxVector()
WifiTxVector ns3::MacLow::GetCtsTxVector (Mac48Address to, WifiMode rtsTxMode) const private
Return a TXVECTOR for the CTS frame given the destination and the mode of the RTS used by the sender.
The function consults WifiRemoteStationManager, which controls the rate to different destinations.
Parameters
to the MAC address of the CTS receiver
rtsTxMode the mode of the RTS used by the sender
Returns
TXVECTOR for the CTS
Definition at line 1459 of file mac-low.cc.
References ns3::ConvertGuardIntervalToNanoSeconds(), ns3::WifiPhy::GetChannelWidth(), ns3::GetChannelWidthForTransmission(), GetControlAnswerMode(), ns3::WifiRemoteStationManager::GetDefaultTxPowerLevel(), ns3::WifiPhy::GetGuardInterval(), ns3::WifiMode::GetModulationClass(), ns3::GetPreambleForTransmission(), ns3::WifiPhy::GetShortGuardInterval(), ns3::WifiRemoteStationManager::GetShortPreambleEnabled(), ns3::Mac48Address::IsGroup(), m_phy, m_stationManager, NS_ASSERT, ns3::WifiTxVector::SetChannelWidth(), ns3::WifiTxVector::SetGuardInterval(), ns3::WifiTxVector::SetMode(), ns3::WifiTxVector::SetNss(), ns3::WifiTxVector::SetPreambleType(), ns3::WifiTxVector::SetTxPowerLevel(), and ns3::WifiRemoteStationManager::UseGreenfieldForDestination().
Referenced by GetCtsTxVectorForRts(), and SendCtsAfterRts().
GetCtsTxVectorForRts()
WifiTxVector ns3::MacLow::GetCtsTxVectorForRts (Mac48Address to, WifiMode rtsTxMode) const private
Return a TXVECTOR for the CTS frame given the destination and the mode of the RTS used by the sender.
The function consults WifiRemoteStationManager, which controls the rate to different destinations.
Parameters
to the MAC address of the CTS receiver
rtsTxMode the mode of the RTS used by the sender
Returns
TXVECTOR for the CTS
Definition at line 1507 of file mac-low.cc.
References GetCtsTxVector().
Referenced by GetCtsDuration().
GetDataTxVector()
WifiTxVector ns3::MacLow::GetDataTxVector (Ptr< const WifiMacQueueItem > item) const virtual
Return a TXVECTOR for the Data frame given the destination.
The function consults WifiRemoteStationManager, which controls the rate to different destinations.
Parameters
item the item being asked for TXVECTOR
Returns
TXVECTOR for the given item
Reimplemented in ns3::WaveMacLow.
Definition at line 1282 of file mac-low.cc.
References ns3::WifiRemoteStationManager::GetDataTxVector(), and m_stationManager.
Referenced by CalculateOverallTxTime(), CalculateOverheadTxTime(), CalculateTransmissionTime(), ns3::WaveMacLow::GetDataTxVector(), NeedCtsToSelf(), SendDataPacket(), and StartTransmission().
GetEdca()
Ptr< QosTxop > ns3::MacLow::GetEdca (uint8_t tid) const
Parameters
tid the Traffic ID
Returns
the QosTxop corresponding to the given TID
Definition at line 279 of file mac-low.cc.
References m_edca, NS_ASSERT, and ns3::QosUtilsMapTidToAc().
GetMpduAggregator()
Ptr< MpduAggregator > ns3::MacLow::GetMpduAggregator (void) const
Returns the aggregator used to construct A-MPDU subframes.
Returns
the aggregator used to construct A-MPDU subframes.
Definition at line 305 of file mac-low.cc.
References m_mpduAggregator.
Referenced by IsWithinSizeAndTimeLimits().
GetMsduAggregator()
Ptr< MsduAggregator > ns3::MacLow::GetMsduAggregator (void) const
Returns the aggregator used to construct A-MSDU subframes.
Returns
the aggregator used to construct A-MSDU subframes.
Definition at line 299 of file mac-low.cc.
References m_msduAggregator.
GetPhy()
Ptr< WifiPhy > ns3::MacLow::GetPhy (void) const
Returns
current attached PHY device
Definition at line 263 of file mac-low.cc.
References m_phy.
Referenced by ns3::WaveMacLow::StartTransmission().
GetPifs()
Time ns3::MacLow::GetPifs (void) const
Return PCF Interframe Space (PIFS) of this MacLow.
Returns
PIFS
Definition at line 451 of file mac-low.cc.
References m_pifs.
Referenced by ForwardDown().
GetRemainingCfpDuration()
Time ns3::MacLow::GetRemainingCfpDuration (void) const
Returns
the remaining duration for the CF period.
Definition at line 2683 of file mac-low.cc.
References ns3::Time::IsPositive(), m_cfpForeshortening, m_cfpMaxDuration, m_cfpStart, min, ns3::Simulator::Now(), NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by CanTransmitNextCfFrame().
GetResponseDuration()
Time ns3::MacLow::GetResponseDuration (const MacLowTransmissionParameters & params, WifiTxVector dataTxVector, Mac48Address receiver) const private
Return the time required to transmit the response frames (Ack or BAR+BA following the policy configured in the transmit parameters).
Parameters
params the transmission parameters
dataTxVector the TX vector used to transmit the data frame
receiver the station from which a response is expected
Returns
the time required to transmit the response (Ack or BAR+BA)
Definition at line 1289 of file mac-low.cc.
References aloha::duration, GetAckDuration(), GetBlockAckDuration(), GetBlockAckRequestDuration(), GetBlockAckTxVector(), ns3::WifiTxVector::GetMode(), GetSifs(), m_self, NS_LOG_FUNCTION, aloha::params, and ns3::Seconds().
Referenced by CalculateOverheadTxTime(), SendCtsToSelf(), SendDataAfterCts(), SendDataPacket(), and SendRtsForPacket().
GetRifs()
Time ns3::MacLow::GetRifs (void) const
Return Reduced Interframe Space (RIFS) of this MacLow.
Returns
RIFS
Definition at line 439 of file mac-low.cc.
References m_rifs.
Referenced by ReceiveOk(), SendDataAfterCts(), SendDataPacket(), and StartDataTxTimers().
GetRtsTxVector()
WifiTxVector ns3::MacLow::GetRtsTxVector (Ptr< const WifiMacQueueItem > item) const private
Return a TXVECTOR for the RTS frame given the destination.
The function consults WifiRemoteStationManager, which controls the rate to different destinations.
Parameters
item the item being asked for RTS TXVECTOR
Returns
TXVECTOR for the RTS of the given item
Definition at line 1275 of file mac-low.cc.
References ns3::WifiRemoteStationManager::GetRtsTxVector(), and m_stationManager.
Referenced by CalculateOverheadTxTime(), NotifyNav(), SendCtsToSelf(), SendRtsForPacket(), and StartTransmission().
GetSifs()
Time ns3::MacLow::GetSifs (void) const
Return Short Interframe Space (SIFS) of this MacLow.
Returns
SIFS
Definition at line 433 of file mac-low.cc.
References m_sifs.
Referenced by CalculateOverheadTxTime(), CalculateTransmissionTime(), CanTransmitNextCfFrame(), DeaggregateAmpduAndReceive(), GetResponseDuration(), NotifyNav(), ReceiveOk(), SendAckAfterData(), SendBlockAckResponse(), SendCtsAfterRts(), SendCtsToSelf(), SendDataAfterCts(), SendDataPacket(), SendRtsForPacket(), and StartDataTxTimers().
GetSlotTime()
Time ns3::MacLow::GetSlotTime (void) const
Return slot duration of this MacLow.
Returns
slot duration
Definition at line 445 of file mac-low.cc.
References m_slotTime.
Referenced by NotifyNav(), SendRtsForPacket(), and StartDataTxTimers().
GetTypeId()
TypeId ns3::MacLow::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 149 of file mac-low.cc.
References ns3::TypeId::SetParent().
IsCfPeriod()
bool ns3::MacLow::IsCfPeriod (void) const virtual
This function indicates whether Simulator::Now is in the CF period.
Returns
true if Simulator::Now is in CF period, false otherwise
Reimplemented in MacLowStub.
Definition at line 2692 of file mac-low.cc.
References ns3::WifiRemoteStationManager::GetPcfSupported(), ns3::Time::IsStrictlyPositive(), m_cfpStart, and m_stationManager.
Referenced by CanTransmitNextCfFrame(), EndTxNoAck(), ForwardDown(), ReceiveError(), ReceiveOk(), SendDataPacket(), and StartDataTxTimers().
IsNavZero()
bool ns3::MacLow::IsNavZero (void) const private
Check if NAV is zero.
Returns
true if NAV is zero, false otherwise
Definition at line 2011 of file mac-low.cc.
References m_lastNavDuration, m_lastNavStart, and ns3::Simulator::Now().
Referenced by ReceiveOk().
IsPromisc()
bool ns3::MacLow::IsPromisc (void) const
Check if MacLow is operating in promiscuous mode.
Returns
true if MacLow is operating in promiscuous mode, false otherwise
Definition at line 475 of file mac-low.cc.
References m_promisc.
IsWithinSizeAndTimeLimits() [1/2]
bool ns3::MacLow::IsWithinSizeAndTimeLimits (Ptr< const WifiMacQueueItem > mpdu, WifiTxVector txVector, uint32_t ampduSize, Time ppduDurationLimit)
Check whether the given MPDU, if transmitted according to the given TX vector, meets the constraint on the maximum A-MPDU size (by assuming that the frame has to be aggregated to an existing A-MPDU of the given size) and its transmission time exceeds neither the max PPDU duration (depending on the PPDU format) nor the given PPDU duration limit (if strictly positive).
The given MPDU needs to be a QoS Data frame.
Parameters
mpdu the MPDU.
txVector the TX vector used to transmit the MPDU
ampduSize the size of the existing A-MPDU in bytes, if any
ppduDurationLimit the limit on the PPDU duration
Returns
true if constraints on size and duration limit are met.
Definition at line 652 of file mac-low.cc.
References NS_ASSERT.
Referenced by StartTransmission().
IsWithinSizeAndTimeLimits() [2/2]
bool ns3::MacLow::IsWithinSizeAndTimeLimits (uint32_t mpduSize, Mac48Address receiver, uint8_t tid, WifiTxVector txVector, uint32_t ampduSize, Time ppduDurationLimit)
Check whether an MPDU of the given size, destined to the given receiver and belonging to the given TID, if transmitted according to the given TX vector, meets the constraint on the maximum A-MPDU size (by assuming that the frame has to be aggregated to an existing A-MPDU of the given size) and its transmission time exceeds neither the max PPDU duration (depending on the PPDU format) nor the given PPDU duration limit (if strictly positive).
Parameters
mpduSize the MPDU size.
receiver the receiver
tid the TID
txVector the TX vector used to transmit the MPDU
ampduSize the size of the existing A-MPDU in bytes, if any
ppduDurationLimit the limit on the PPDU duration
Returns
true if constraints on size and duration limit are met.
Definition at line 663 of file mac-low.cc.
References ns3::WifiPhy::CalculateTxDuration(), ns3::WifiPhy::GetFrequency(), ns3::WifiTxVector::GetMode(), ns3::WifiMode::GetModulationClass(), GetMpduAggregator(), ns3::GetPpduMaxTime(), ns3::WifiTxVector::GetPreambleType(), ns3::Time::IsNegative(), ns3::Time::IsStrictlyPositive(), m_phy, ns3::Time::Min(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, and ns3::WIFI_MOD_CLASS_VHT.
NeedCtsToSelf()
bool ns3::MacLow::NeedCtsToSelf (void) const private
Check if CTS-to-self mechanism should be used for the current packet.
Returns
true if CTS-to-self mechanism should be used for the current packet, false otherwise
Definition at line 645 of file mac-low.cc.
References GetDataTxVector(), m_currentPacket, m_stationManager, and ns3::WifiRemoteStationManager::NeedCtsToSelf().
Referenced by StartTransmission().
NormalAckTimeout()
void ns3::MacLow::NormalAckTimeout (void) private
Event handler when normal Ack timeout occurs.
Todo:
should check that there was no RX start before now. we should restart a new ack timeout now until the expected end of RX if there was a RX start before now.
Definition at line 1790 of file mac-low.cc.
References m_currentTxop, ns3::Txop::MissedAck(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by RxStartIndication(), and StartDataTxTimers().
NotifyAckTimeoutResetNow()
void ns3::MacLow::NotifyAckTimeoutResetNow (void) private
Notify ChannelAccessManager that Ack timer should be reset.
Definition at line 1657 of file mac-low.cc.
References m_channelAccessManagers.
Referenced by ReceiveOk(), and RxStartIndication().
NotifyAckTimeoutStartNow()
void ns3::MacLow::NotifyAckTimeoutStartNow (Time duration) private
Notify ChannelAccessManager that Ack timer should be started for the given duration.
Parameters
duration the duration of the timer
Definition at line 1648 of file mac-low.cc.
References aloha::duration, and m_channelAccessManagers.
Referenced by StartDataTxTimers().
NotifyCtsTimeoutResetNow()
void ns3::MacLow::NotifyCtsTimeoutResetNow (void) private
Notify ChannelAccessManager that CTS timer should be reset.
Definition at line 1675 of file mac-low.cc.
References m_channelAccessManagers.
Referenced by ReceiveOk(), and RxStartIndication().
NotifyCtsTimeoutStartNow()
void ns3::MacLow::NotifyCtsTimeoutStartNow (Time duration) private
Notify ChannelAccessManager that CTS timer should be started for the given duration.
Parameters
duration the duration of the timer
Definition at line 1666 of file mac-low.cc.
References aloha::duration, and m_channelAccessManagers.
Referenced by SendRtsForPacket().
NotifyNav()
void ns3::MacLow::NotifyNav (Ptr< const Packet > packet, const WifiMacHeader & hdr) private
Notify NAV function.
Parameters
packet the packet
hdr the header
A STA that used information from an RTS frame as the most recent basis to update its NAV setting is permitted to reset its NAV if no PHY-RXSTART.indication is detected from the PHY during a period with a duration of (2 * aSIFSTime) + (CTS_Time) + aRxPHYStartDelay + (2 * aSlotTime) starting at the PHY-RXEND.indication corresponding to the detection of the RTS frame. The CTS_Time shall be calculated using the length of the CTS frame and the data rate at which the RTS frame used for the most recent NAV update was received.
Definition at line 1573 of file mac-low.cc.
References ns3::WifiPhy::CalculatePhyPreambleAndHeaderDuration(), ns3::WifiPhy::CalculateTxDuration(), DoNavResetNow(), DoNavStartNow(), aloha::duration, ns3::WifiMacHeader::GetAddr1(), ns3::WifiMacHeader::GetAddr2(), ns3::WifiMacHeader::GetDuration(), ns3::WifiPhy::GetFrequency(), ns3::WifiMacHeader::GetRawDuration(), GetRtsTxVector(), ns3::WifiMacHeader::GetSerializedSize(), GetSifs(), GetSlotTime(), ns3::WifiMacHeader::IsCfEnd(), ns3::WifiMacHeader::IsRts(), m_bssid, m_lastNavStart, m_navCounterResetCtsMissed, m_phy, m_self, ns3::Simulator::Now(), NS_ASSERT, ns3::Simulator::Schedule(), ns3::Seconds(), ns3::WifiMacHeader::SetType(), and ns3::WIFI_MAC_CTL_CTS.
Referenced by DeaggregateAmpduAndReceive(), and ReceiveOk().
NotifyOffNow()
void ns3::MacLow::NotifyOffNow (void)
This method is typically invoked by the PhyMacLowListener to notify the MAC layer that the device has been put into off mode.
When the device is put into off mode, pending MAC transmissions (RTS, CTS, Data and Ack) are cancelled.
Definition at line 808 of file mac-low.cc.
References ns3::EventId::Cancel(), CancelAllEvents(), ns3::EventId::IsRunning(), m_currentPacket, m_currentTxop, m_lastNavDuration, m_lastNavStart, m_navCounterResetCtsMissed, ns3::Simulator::Now(), NS_LOG_DEBUG, and ns3::Seconds().
Referenced by ns3::PhyMacLowListener::NotifyOff().
NotifySleepNow()
void ns3::MacLow::NotifySleepNow (void)
This method is typically invoked by the PhyMacLowListener to notify the MAC layer that the device has been put into sleep mode.
When the device is put into sleep mode, pending MAC transmissions (RTS, CTS, Data and Ack) are cancelled.
Definition at line 793 of file mac-low.cc.
References ns3::EventId::Cancel(), CancelAllEvents(), ns3::EventId::IsRunning(), m_currentPacket, m_currentTxop, m_lastNavDuration, m_lastNavStart, m_navCounterResetCtsMissed, ns3::Simulator::Now(), NS_LOG_DEBUG, and ns3::Seconds().
Referenced by ns3::PhyMacLowListener::NotifySleep().
NotifySwitchingStartNow()
void ns3::MacLow::NotifySwitchingStartNow (Time duration)
Parameters
duration switching delay duration.
This method is typically invoked by the PhyMacLowListener to notify the MAC layer that a channel switching occurred. When a channel switching occurs, pending MAC transmissions (RTS, CTS, Data and Ack) are cancelled.
Definition at line 777 of file mac-low.cc.
References ns3::EventId::Cancel(), CancelAllEvents(), ns3::EventId::IsRunning(), m_currentPacket, m_currentTxop, m_lastNavDuration, m_lastNavStart, m_navCounterResetCtsMissed, m_stationManager, ns3::Simulator::Now(), NS_LOG_DEBUG, ns3::WifiRemoteStationManager::Reset(), and ns3::Seconds().
Referenced by ns3::PhyMacLowListener::NotifySwitchingStart().
ReceiveError()
void ns3::MacLow::ReceiveError (Ptr< WifiPsdu > psdu)
Parameters
psdu PSDU received.
This method is typically invoked by the lower PHY layer to notify the MAC layer that a PSDU was unsuccessfully received.
Definition at line 756 of file mac-low.cc.
References ns3::MacLow::CfAckInfo::expectCfAck, IsCfPeriod(), m_cfAckInfo, m_currentPacket, m_currentTxop, ns3::Txop::MissedAck(), ns3::Txop::MissedCfPollResponse(), NS_ASSERT, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by SetPhy().
ReceiveMpdu()
bool ns3::MacLow::ReceiveMpdu (Ptr< WifiMacQueueItem > mpdu) private
Parameters
mpdu the MPDU
Returns
true if MPDU received
This method updates the reorder buffer and the scoreboard when an MPDU is received in an HT station and stores the MPDU if needed when an MPDU is received in an non-HT Station (implements HT immediate BlockAck)
Definition at line 2191 of file mac-low.cc.
References ns3::WifiMacHeader::GetAddr2(), ns3::WifiMacQueueItem::GetHeader(), ns3::WifiRemoteStationManager::GetHeSupported(), ns3::WifiRemoteStationManager::GetHtSupported(), ns3::WifiMacHeader::GetQosTid(), ns3::WifiMacHeader::GetSequenceNumber(), ns3::WifiRemoteStationManager::GetVhtSupported(), ns3::IsInWindow(), ns3::WifiMacHeader::IsQosData(), m_bAckAgreements, m_stationManager, NS_ASSERT, ns3::QosUtilsIsOldPacket(), RxCompleteBufferedPacketsUntilFirstLost(), RxCompleteBufferedPacketsWithSmallerSequence(), and StoreMpduIfNeeded().
Referenced by ReceiveOk().
ReceiveOk()
void ns3::MacLow::ReceiveOk (Ptr< WifiMacQueueItem > mpdu, double rxSnr, WifiTxVector txVector, bool ampduSubframe)
Parameters
mpdu MPDU received
rxSnr snr of MPDU received in linear scale
txVector TXVECTOR of MPDU received
ampduSubframe true if this MPDU is part of an A-MPDU
This method is typically invoked by the lower PHY layer to notify the MAC layer that an MPDU was successfully received.
Definition at line 823 of file mac-low.cc.
References ns3::Packet::AddPacketTag(), ns3::MacLow::CfAckInfo::address, ns3::MacLow::CfAckInfo::appendCfAck, ns3::EventId::Cancel(), ns3::MacLow::CfAckInfo::expectCfAck, ns3::SnrTag::Get(), ns3::WifiMacHeader::GetAddr1(), ns3::WifiMacHeader::GetAddr2(), ns3::WifiMacHeader::GetDuration(), ns3::WifiMacQueueItem::GetHeader(), ns3::WifiTxVector::GetMode(), ns3::WifiMacQueueItem::GetPacket(), ns3::WifiMacHeader::GetQosTid(), GetRifs(), ns3::WifiRemoteStationManager::GetRifsPermitted(), GetSifs(), ns3::CtrlBAckRequestHeader::GetStartingSequence(), ns3::CtrlBAckRequestHeader::GetTidInfo(), ns3::Txop::GetTxopLimit(), ns3::Txop::GetTxopRemaining(), ns3::WifiMacHeader::GetTypeString(), ns3::Txop::GotAck(), ns3::Txop::GotBlockAck(), ns3::Txop::GotCfEnd(), ns3::WifiMacHeader::HasData(), ns3::MacLowTransmissionParameters::HasNextPacket(), ns3::WifiMacHeader::IsAck(), ns3::WifiMacHeader::IsBeacon(), ns3::WifiMacHeader::IsBlockAck(), ns3::WifiMacHeader::IsBlockAckReq(), ns3::WifiMacHeader::IsCfAck(), ns3::WifiMacHeader::IsCfEnd(), IsCfPeriod(), ns3::WifiMacHeader::IsCfPoll(), ns3::WifiMacHeader::IsCtl(), ns3::WifiMacHeader::IsCts(), ns3::WifiMacHeader::IsData(), ns3::EventId::IsExpired(), ns3::Mac48Address::IsGroup(), ns3::WifiMacHeader::IsMgt(), ns3::CtrlBAckRequestHeader::IsMultiTid(), IsNavZero(), ns3::WifiMacHeader::IsProbeResp(), ns3::WifiMacHeader::IsQosAck(), ns3::WifiMacHeader::IsQosBlockAck(), ns3::WifiMacHeader::IsQosData(), ns3::WifiMacHeader::IsQosNoAck(), ns3::Txop::IsQosTxop(), ns3::WifiMacHeader::IsRts(), ns3::EventId::IsRunning(), ns3::Time::IsStrictlyPositive(), m_bAckAgreements, m_bAckCaches, m_blockAckTimeoutEvent, m_cfAckInfo, m_cfpStart, m_ctsTimeoutEvent, m_currentPacket, m_currentTxop, m_edca, m_normalAckTimeoutEvent, m_promisc, m_rxCallback, m_self, m_sendAckEvent, m_sendCtsEvent, m_sendDataEvent, m_stationManager, m_txParams, m_waitIfsEvent, ns3::Txop::MissedAck(), ns3::MacLowTransmissionParameters::MustWaitBlockAck(), ns3::MacLowTransmissionParameters::MustWaitNormalAck(), ns3::NanoSeconds(), NotifyAckTimeoutResetNow(), NotifyCtsTimeoutResetNow(), NotifyNav(), ns3::Simulator::Now(), NS_ASSERT, NS_FATAL_ERROR, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::QosUtilsMapTidToAc(), ReceiveMpdu(), ns3::Packet::RemoveHeader(), ns3::Packet::RemovePacketTag(), ns3::WifiRemoteStationManager::ReportDataOk(), ns3::WifiRemoteStationManager::ReportRtsOk(), ns3::WifiRemoteStationManager::ReportRxOk(), ResetBlockAckInactivityTimerIfNeeded(), RxCompleteBufferedPacketsUntilFirstLost(), RxCompleteBufferedPacketsWithSmallerSequence(), ns3::Simulator::Schedule(), SendAckAfterData(), SendBlockAckAfterBlockAckRequest(), SendCtsAfterRts(), SendDataAfterCts(), ns3::SnrTag::Set(), ns3::Txop::TerminateTxop(), WaitIfsAfterEndTxFragment(), and WaitIfsAfterEndTxPacket().
Referenced by DeaggregateAmpduAndReceive().
RegisterChannelAccessManager()
void ns3::MacLow::RegisterChannelAccessManager (Ptr< ChannelAccessManager > channelAccessManager)
Parameters
channelAccessManager pointer to ChannelAccessManager in order to listen to NAV events for every incoming and outgoing packet.
Definition at line 487 of file mac-low.cc.
References m_channelAccessManagers.
RegisterEdcaForAc()
void ns3::MacLow::RegisterEdcaForAc (AcIndex ac, Ptr< QosTxop > edca)
Parameters
ac Access class managed by the queue.
edca the QosTxop for the queue.
The lifetime of the registered QosTxop is typically equal to the lifetime of the queue associated to this AC.
Definition at line 2579 of file mac-low.cc.
References m_edca.
RemovePhyMacLowListener()
void ns3::MacLow::RemovePhyMacLowListener (Ptr< WifiPhy > phy) private
Remove current WifiPhy listener for this MacLow.
Parameters
phy the WifiPhy this MacLow is connected to
Definition at line 167 of file mac-low.cc.
References m_phyMacLowListener, and third::phy.
Referenced by ResetPhy().
ResetBlockAckInactivityTimerIfNeeded()
void ns3::MacLow::ResetBlockAckInactivityTimerIfNeeded (BlockAckAgreement & agreement) private
Every time that a BlockAckRequest or a packet with Ack Policy equals to Block Ack are received, if a relative block ack agreement exists and the value of inactivity timeout is not 0, the timer is reset.
see section 11.5.3 in IEEE 802.11e for more details.
Parameters
agreement the BA agreement
Definition at line 2563 of file mac-low.cc.
References ns3::EventId::Cancel(), ns3::BlockAckAgreement::GetPeer(), ns3::BlockAckAgreement::GetTid(), ns3::BlockAckAgreement::GetTimeout(), ns3::EventId::IsRunning(), m_edca, ns3::BlockAckAgreement::m_inactivityEvent, ns3::MicroSeconds(), NS_ASSERT, ns3::QosUtilsMapTidToAc(), ns3::Simulator::Schedule(), ns3::QosTxop::SendDelbaFrame(), and timeout.
Referenced by DeaggregateAmpduAndReceive(), and ReceiveOk().
ResetPhy()
void ns3::MacLow::ResetPhy (void)
Remove WifiPhy associated with this MacLow.
Definition at line 269 of file mac-low.cc.
References m_phy, ns3::MakeCallback(), ns3::MakeNullCallback(), RemovePhyMacLowListener(), RxStartIndication(), ns3::WifiPhy::SetReceiveErrorCallback(), ns3::WifiPhy::SetReceiveOkCallback(), and ns3::ObjectBase::TraceDisconnectWithoutContext().
RxCompleteBufferedPacketsUntilFirstLost()
void ns3::MacLow::RxCompleteBufferedPacketsUntilFirstLost (Mac48Address originator, uint8_t tid) private
Parameters
originator Address of peer participating in block ack mechanism.
tid TID for which block ack was created.
This method is typically invoked when a MPDU with ack policy subfield set to Normal Ack is received and a block ack agreement for that packet exists. This happens when the originator of block ack has only few MPDUs to send. All completed MSDUs starting with starting sequence number of block ack agreement are forward up to WifiMac until there is an incomplete or missing MSDU. See section 9.10.4 in IEEE 802.11 standard for more details.
Definition at line 2380 of file mac-low.cc.
References m_bAckAgreements, and m_rxCallback.
Referenced by DestroyBlockAckAgreement(), ReceiveMpdu(), ReceiveOk(), and SendBlockAckAfterBlockAckRequest().
RxCompleteBufferedPacketsWithSmallerSequence()
void ns3::MacLow::RxCompleteBufferedPacketsWithSmallerSequence (uint16_t seq, Mac48Address originator, uint8_t tid) private
Parameters
originator Address of peer participating in block ack mechanism.
tid TID for which block ack was created.
seq Starting sequence control
This function forward up all completed "old" packets with sequence number smaller than seq. All comparison are performed circularly modulo 4096.
Definition at line 2317 of file mac-low.cc.
References m_bAckAgreements, m_rxCallback, and ns3::QosUtilsMapSeqControlToUniqueInteger().
Referenced by DestroyBlockAckAgreement(), ReceiveMpdu(), ReceiveOk(), and SendBlockAckAfterBlockAckRequest().
RxStartIndication()
void ns3::MacLow::RxStartIndication (WifiTxVector txVector, Time psduDuration)
Parameters
txVector the TXVECTOR decoded from PHY header.
psduDuration the duration of the PSDU that is about to be received.
This method is typically invoked by the lower PHY layer to notify the MAC layer that the reception of a PSDU is starting. This is equivalent to the PHY-RXSTART primitive. If the reception is correct for at least one MPDU of the PSDU the DeaggregateAmpduAndReceive will be called after psduDuration. Otherwise, ReceiveError will be called after the same duration.
Definition at line 714 of file mac-low.cc.
References BlockAckTimeout(), ns3::EventId::Cancel(), CtsTimeout(), ns3::EventId::IsRunning(), ns3::Time::IsStrictlyPositive(), m_blockAckTimeoutEvent, m_ctsTimeoutEvent, m_navCounterResetCtsMissed, m_normalAckTimeoutEvent, ns3::NanoSeconds(), NormalAckTimeout(), NotifyAckTimeoutResetNow(), NotifyCtsTimeoutResetNow(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, PSDU_DURATION_SAFEGUARD, ns3::Simulator::Schedule(), ns3::Time::ToDouble(), and ns3::Time::US.
Referenced by ResetPhy(), and SetPhy().
SendAckAfterData()
void ns3::MacLow::SendAckAfterData (Mac48Address source, Time duration, WifiMode dataTxMode, double dataSnr) private
Send Ack after receiving Data.
Parameters
source the transmitter of the Data
duration the NAV of the Data
dataTxMode the TXVECTOR used to transmit the Data
dataSnr the SNR of the Data in linear scale
Definition at line 2161 of file mac-low.cc.
References ns3::Packet::AddPacketTag(), aloha::duration, ForwardDown(), GetAckDuration(), GetAckTxVector(), GetSifs(), NS_ASSERT_MSG(), NS_LOG_FUNCTION, ns3::SnrTag::Set(), ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetDsNotFrom(), ns3::WifiMacHeader::SetDsNotTo(), ns3::WifiMacHeader::SetDuration(), ns3::WifiMacHeader::SetNoMoreFragments(), ns3::WifiMacHeader::SetNoRetry(), ns3::WifiMacHeader::SetType(), and ns3::WIFI_MAC_CTL_ACK.
Referenced by ReceiveOk().
SendBlockAckAfterAmpdu()
void ns3::MacLow::SendBlockAckAfterAmpdu (uint8_t tid, Mac48Address originator, Time duration, WifiTxVector blockAckReqTxVector, double rxSnr) private
Invoked after an A-MPDU has been received.
Looks for corresponding block ack agreement and creates a block ack bitmap on a received packets basis.
Parameters
tid the Traffic ID
originator the originator MAC address
duration the remaining NAV duration
blockAckReqTxVector the transmit vector
rxSnr the receive SNR in linear scale
Definition at line 2458 of file mac-low.cc.
References ns3::COMPRESSED_BLOCK_ACK, aloha::duration, ns3::EXTENDED_COMPRESSED_BLOCK_ACK, GetBlockAckTxVector(), ns3::WifiTxVector::GetMode(), ns3::WifiPhy::IsStateRx(), ns3::WifiPhy::IsStateTx(), m_bAckAgreements, m_bAckCaches, m_phy, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Time::S, SendBlockAckResponse(), ns3::CtrlBAckResponseHeader::SetStartingSequence(), ns3::CtrlBAckResponseHeader::SetTidInfo(), and ns3::CtrlBAckResponseHeader::SetType().
Referenced by DeaggregateAmpduAndReceive().
SendBlockAckAfterBlockAckRequest()
void ns3::MacLow::SendBlockAckAfterBlockAckRequest (const CtrlBAckRequestHeader reqHdr, Mac48Address originator, Time duration, WifiMode blockAckReqTxMode, double rxSnr) private
Invoked after that a BlockAckRequest has been received.
Looks for corresponding block ack agreement and creates a block ack bitmap on a received packets basis.
Parameters
reqHdr the BAR header
originator the transmitter of the BAR
duration the NAV of the BAR
blockAckReqTxMode the TXVECTOR used to transmit the BAR
rxSnr the SNR of the BAR in linear scale
Definition at line 2497 of file mac-low.cc.
References ns3::BASIC_BLOCK_ACK, ns3::COMPRESSED_BLOCK_ACK, aloha::duration, ns3::EXTENDED_COMPRESSED_BLOCK_ACK, ns3::WifiRemoteStationManager::GetHeSupported(), ns3::WifiRemoteStationManager::GetHtSupported(), ns3::CtrlBAckRequestHeader::GetStartingSequence(), ns3::CtrlBAckRequestHeader::GetStartingSequenceControl(), ns3::CtrlBAckRequestHeader::GetTidInfo(), ns3::WifiRemoteStationManager::GetVhtSupported(), ns3::CtrlBAckRequestHeader::IsBasic(), ns3::CtrlBAckRequestHeader::IsCompressed(), ns3::CtrlBAckRequestHeader::IsExtendedCompressed(), ns3::CtrlBAckRequestHeader::IsMultiTid(), m_bAckAgreements, m_bAckCaches, m_stationManager, NS_ASSERT, NS_FATAL_ERROR, NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::QosUtilsIsOldPacket(), RxCompleteBufferedPacketsUntilFirstLost(), RxCompleteBufferedPacketsWithSmallerSequence(), SendBlockAckResponse(), ns3::CtrlBAckResponseHeader::SetStartingSequence(), ns3::CtrlBAckResponseHeader::SetTidInfo(), and ns3::CtrlBAckResponseHeader::SetType().
Referenced by ReceiveOk().
SendBlockAckResponse()
void ns3::MacLow::SendBlockAckResponse (const CtrlBAckResponseHeader * blockAck, Mac48Address originator, bool immediate, Time duration, WifiMode blockAckReqTxMode, double rxSnr) private
This method creates BlockAck frame with header equals to blockAck and start its transmission.
Parameters
blockAck the BA response header to send
originator the station to send a BA to
immediate use immediate BA policy if true
duration the NAV duration
blockAckReqTxMode the TXVECTOR used to transmit the BAR
rxSnr the received SNR in linear scale
Definition at line 2410 of file mac-low.cc.
References ns3::Packet::AddHeader(), ns3::Packet::AddPacketTag(), ns3::MacLowTransmissionParameters::DisableAck(), ns3::MacLowTransmissionParameters::DisableNextData(), aloha::duration, ns3::MacLowTransmissionParameters::EnableAck(), ForwardDown(), GetAckDuration(), GetAddress(), GetBlockAckDuration(), GetBlockAckTxVector(), GetSifs(), ns3::CtrlBAckResponseHeader::GetType(), m_txParams, NS_ASSERT, NS_LOG_FUNCTION, ns3::SnrTag::Set(), ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetAddr2(), ns3::WifiMacHeader::SetDsNotFrom(), ns3::WifiMacHeader::SetDsNotTo(), ns3::WifiMacHeader::SetDuration(), ns3::WifiMacHeader::SetNoMoreFragments(), ns3::WifiMacHeader::SetNoRetry(), ns3::WifiMacHeader::SetType(), StartDataTxTimers(), and ns3::WIFI_MAC_CTL_BACKRESP.
Referenced by SendBlockAckAfterAmpdu(), and SendBlockAckAfterBlockAckRequest().
SendCtsAfterRts()
void ns3::MacLow::SendCtsAfterRts (Mac48Address source, Time duration, WifiTxVector rtsTxVector, double rtsSnr) private
Send CTS after receiving RTS.
Parameters
source the transmitter of the RTS
duration the NAV of the RTS
rtsTxVector the TXVECTOR used to transmit the RTS
rtsSnr the SNR of the RTS in linear scale
Definition at line 2056 of file mac-low.cc.
References ns3::Packet::AddPacketTag(), aloha::duration, ForwardDown(), GetCtsDuration(), GetCtsTxVector(), ns3::WifiTxVector::GetMode(), GetSifs(), NS_ASSERT, NS_LOG_FUNCTION, ns3::SnrTag::Set(), ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetDsNotFrom(), ns3::WifiMacHeader::SetDsNotTo(), ns3::WifiMacHeader::SetDuration(), ns3::WifiMacHeader::SetNoMoreFragments(), ns3::WifiMacHeader::SetNoRetry(), ns3::WifiMacHeader::SetType(), and ns3::WIFI_MAC_CTL_CTS.
Referenced by ReceiveOk().
SendCtsToSelf()
void ns3::MacLow::SendCtsToSelf (void) private
Send CTS for a CTS-to-self mechanism.
Definition at line 2017 of file mac-low.cc.
References ns3::WifiPhy::CalculateTxDuration(), aloha::duration, ForwardDown(), ns3::GetCtsSize(), ns3::WifiPhy::GetFrequency(), ns3::MacLowTransmissionParameters::GetNextPacketSize(), GetResponseDuration(), GetRtsTxVector(), GetSifs(), ns3::MacLowTransmissionParameters::HasNextPacket(), ns3::EventId::IsExpired(), m_currentPacket, m_currentTxVector, m_phy, m_self, m_sendDataEvent, m_txParams, NS_ASSERT, ns3::Simulator::Schedule(), ns3::Seconds(), SendDataAfterCts(), ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetDsNotFrom(), ns3::WifiMacHeader::SetDsNotTo(), ns3::WifiMacHeader::SetDuration(), ns3::WifiMacHeader::SetNoMoreFragments(), ns3::WifiMacHeader::SetNoRetry(), ns3::WifiMacHeader::SetType(), and ns3::WIFI_MAC_CTL_CTS.
Referenced by StartTransmission().
SendDataAfterCts()
void ns3::MacLow::SendDataAfterCts (Time duration) private
Send Data after receiving CTS.
Parameters
duration the NAV of the CTS
Definition at line 2086 of file mac-low.cc.
References ns3::WifiPhy::CalculateTxDuration(), aloha::duration, ForwardDown(), ns3::WifiPhy::GetFrequency(), ns3::MacLowTransmissionParameters::GetNextPacketSize(), GetResponseDuration(), GetRifs(), ns3::WifiRemoteStationManager::GetRifsPermitted(), GetSifs(), ns3::MacLowTransmissionParameters::HasNextPacket(), m_currentPacket, m_currentTxop, m_currentTxVector, m_phy, m_stationManager, m_txParams, max, ns3::MacLowTransmissionParameters::MustSendBlockAckRequest(), NS_ASSERT, NS_LOG_FUNCTION, ns3::QosTxop::PrepareBlockAckRequest(), ns3::QosTxop::ScheduleBar(), and StartDataTxTimers().
Referenced by ReceiveOk(), and SendCtsToSelf().
SendDataPacket()
void ns3::MacLow::SendDataPacket (void) private
Send Data packet, which can be Data-Ack or RTS-CTS-Data-Ack transaction.
Definition at line 1921 of file mac-low.cc.
References ns3::MacLow::CfAckInfo::address, ns3::MacLow::CfAckInfo::appendCfAck, ns3::WifiPhy::CalculateTxDuration(), aloha::duration, ForwardDown(), ns3::WifiMode::GetDataRate(), GetDataTxVector(), ns3::WifiPhy::GetFrequency(), ns3::WifiTxVector::GetMode(), ns3::MacLowTransmissionParameters::GetNextPacketSize(), GetResponseDuration(), GetRifs(), ns3::WifiRemoteStationManager::GetRifsPermitted(), GetSifs(), ns3::MacLowTransmissionParameters::HasNextPacket(), IsCfPeriod(), m_cfAckInfo, m_currentPacket, m_currentTxop, m_currentTxVector, m_phy, m_stationManager, m_txParams, ns3::MacLowTransmissionParameters::MustSendBlockAckRequest(), NS_ASSERT, NS_LOG_FUNCTION, ns3::QosTxop::PrepareBlockAckRequest(), ns3::QosTxop::ScheduleBar(), ns3::WifiMacHeader::SetAddr1(), StartDataTxTimers(), ns3::WIFI_MAC_CTL_END, ns3::WIFI_MAC_CTL_END_ACK, ns3::WIFI_MAC_DATA, ns3::WIFI_MAC_DATA_CFACK, ns3::WIFI_MAC_DATA_CFACK_CFPOLL, ns3::WIFI_MAC_DATA_CFPOLL, ns3::WIFI_MAC_DATA_NULL, ns3::WIFI_MAC_DATA_NULL_CFACK, ns3::WIFI_MAC_DATA_NULL_CFACK_CFPOLL, and ns3::WIFI_MAC_DATA_NULL_CFPOLL.
Referenced by StartTransmission().
SendRtsForPacket()
void ns3::MacLow::SendRtsForPacket (void) private
Send RTS to begin RTS-CTS-Data-Ack transaction.
Definition at line 1813 of file mac-low.cc.
References ns3::WifiPhy::CalculatePhyPreambleAndHeaderDuration(), ns3::WifiPhy::CalculateTxDuration(), CtsTimeout(), aloha::duration, ForwardDown(), GetCtsDuration(), ns3::WifiPhy::GetFrequency(), ns3::MacLowTransmissionParameters::GetNextPacketSize(), GetResponseDuration(), ns3::GetRtsSize(), GetRtsTxVector(), GetSifs(), GetSlotTime(), ns3::MacLowTransmissionParameters::HasNextPacket(), ns3::EventId::IsExpired(), m_ctsTimeoutEvent, m_currentPacket, m_currentTxVector, m_phy, m_self, m_txParams, NotifyCtsTimeoutStartNow(), NS_ASSERT, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), ns3::Seconds(), ns3::WifiMacHeader::SetAddr1(), ns3::WifiMacHeader::SetAddr2(), ns3::WifiMacHeader::SetDsNotFrom(), ns3::WifiMacHeader::SetDsNotTo(), ns3::WifiMacHeader::SetDuration(), ns3::WifiMacHeader::SetNoMoreFragments(), ns3::WifiMacHeader::SetNoRetry(), ns3::WifiMacHeader::SetType(), and ns3::WIFI_MAC_CTL_RTS.
Referenced by StartTransmission().
SetAckTimeout()
void ns3::MacLow::SetAckTimeout (Time ackTimeout)
Set Ack timeout of this MacLow.
Parameters
ackTimeout Ack timeout of this MacLow
Definition at line 331 of file mac-low.cc.
References m_ackTimeout.
SetAddress()
void ns3::MacLow::SetAddress (Mac48Address ad)
Set MAC address of this MacLow.
Parameters
ad Mac48Address of this MacLow
Definition at line 325 of file mac-low.cc.
References m_self.
SetBasicBlockAckTimeout()
void ns3::MacLow::SetBasicBlockAckTimeout (Time blockAckTimeout)
Set Basic BlockAck timeout of this MacLow.
Parameters
blockAckTimeout Basic BlockAck timeout of this MacLow
Definition at line 337 of file mac-low.cc.
References m_basicBlockAckTimeout.
SetBeaconInterval()
void ns3::MacLow::SetBeaconInterval (Time interval)
Parameters
interval the expected interval between two beacon transmissions.
Definition at line 385 of file mac-low.cc.
References m_beaconInterval.
SetBssid()
void ns3::MacLow::SetBssid (Mac48Address ad)
Set the Basic Service Set Identification.
Parameters
ad the BSSID
Definition at line 397 of file mac-low.cc.
References m_bssid.
SetCfpMaxDuration()
void ns3::MacLow::SetCfpMaxDuration (Time duration)
Parameters
duration the maximum duration for the CF period.
Definition at line 391 of file mac-low.cc.
References m_cfpMaxDuration.
SetCompressedBlockAckTimeout()
void ns3::MacLow::SetCompressedBlockAckTimeout (Time blockAckTimeout)
Set Compressed BlockAck timeout of this MacLow.
Parameters
blockAckTimeout Compressed BlockAck timeout of this MacLow
Definition at line 343 of file mac-low.cc.
References m_compressedBlockAckTimeout.
SetCtsToSelfSupported()
void ns3::MacLow::SetCtsToSelfSupported (bool enable)
Enable or disable CTS-to-self capability.
Parameters
enable Enable or disable CTS-to-self capability
Definition at line 349 of file mac-low.cc.
References m_ctsToSelfSupported.
SetMac()
void ns3::MacLow::SetMac (const Ptr< WifiMac > mac)
Set up WifiMac associated with this MacLow.
Parameters
mac WifiMac associated with this MacLow
Definition at line 287 of file mac-low.cc.
References m_mac, and third::mac.
SetMpduAggregator()
void ns3::MacLow::SetMpduAggregator (const Ptr< MpduAggregator > aggr)
Set the aggregator used to construct A-MPDU subframes.
Parameters
aggr pointer to the MPDU aggregator.
Definition at line 318 of file mac-low.cc.
References m_mpduAggregator, and NS_LOG_FUNCTION.
SetMsduAggregator()
void ns3::MacLow::SetMsduAggregator (const Ptr< MsduAggregator > aggr)
Set the aggregator used to construct A-MSDU subframes.
Parameters
aggr pointer to the MSDU aggregator.
Definition at line 311 of file mac-low.cc.
References m_msduAggregator, and NS_LOG_FUNCTION.
SetPhy()
void ns3::MacLow::SetPhy (const Ptr< WifiPhy > phy)
Set up WifiPhy associated with this MacLow.
Parameters
phy WifiPhy associated with this MacLow
Definition at line 253 of file mac-low.cc.
References DeaggregateAmpduAndReceive(), m_phy, ns3::MakeCallback(), third::phy, ReceiveError(), RxStartIndication(), ns3::WifiPhy::SetReceiveErrorCallback(), ns3::WifiPhy::SetReceiveOkCallback(), SetupPhyMacLowListener(), and ns3::ObjectBase::TraceConnectWithoutContext().
SetPifs()
void ns3::MacLow::SetPifs (Time pifs)
Set PCF Interframe Space (PIFS) of this MacLow.
Parameters
pifs PIFS of this MacLow
Definition at line 373 of file mac-low.cc.
References m_pifs.
SetPromisc()
void ns3::MacLow::SetPromisc (void)
Enable promiscuous mode.
Definition at line 403 of file mac-low.cc.
References m_promisc.
SetRifs()
void ns3::MacLow::SetRifs (Time rifs)
Set Reduced Interframe Space (RIFS) of this MacLow.
Parameters
rifs RIFS of this MacLow
Definition at line 379 of file mac-low.cc.
References m_rifs.
SetRxCallback()
void ns3::MacLow::SetRxCallback (Callback< void, Ptr< WifiMacQueueItem >> callback)
Parameters
callback the callback which receives every incoming packet.
This callback typically forwards incoming packets to an instance of ns3::MacRxMiddle.
Definition at line 481 of file mac-low.cc.
References m_rxCallback.
SetSifs()
void ns3::MacLow::SetSifs (Time sifs)
Set Short Interframe Space (SIFS) of this MacLow.
Parameters
sifs SIFS of this MacLow
Definition at line 361 of file mac-low.cc.
References m_sifs.
SetSlotTime()
void ns3::MacLow::SetSlotTime (Time slotTime)
Set slot duration of this MacLow.
Parameters
slotTime slot duration of this MacLow
Definition at line 367 of file mac-low.cc.
References m_slotTime.
SetupPhyMacLowListener()
void ns3::MacLow::SetupPhyMacLowListener (const Ptr< WifiPhy > phy) private
Set up WifiPhy listener for this MacLow.
Parameters
phy the WifiPhy this MacLow is connected to
Definition at line 160 of file mac-low.cc.
References m_phyMacLowListener, and third::phy.
Referenced by SetPhy().
SetWifiRemoteStationManager()
void ns3::MacLow::SetWifiRemoteStationManager (const Ptr< WifiRemoteStationManager > manager)
Set up WifiRemoteStationManager associated with this MacLow.
Parameters
manager WifiRemoteStationManager associated with this MacLow
Definition at line 293 of file mac-low.cc.
References m_stationManager.
StartDataTxTimers()
void ns3::MacLow::StartDataTxTimers (WifiTxVector dataTxVector) private
Start a Data timer by scheduling appropriate Ack timeout.
Parameters
dataTxVector the TXVECTOR used to transmit the Data
Definition at line 1856 of file mac-low.cc.
References BlockAckTimeout(), ns3::WifiPhy::CalculatePhyPreambleAndHeaderDuration(), ns3::WifiPhy::CalculateTxDuration(), EndTxNoAck(), GetAckTxVector(), GetBlockAckTxVector(), ns3::WifiPhy::GetFrequency(), ns3::WifiTxVector::GetMode(), GetRifs(), ns3::WifiRemoteStationManager::GetRifsPermitted(), GetSifs(), GetSlotTime(), ns3::Txop::GetTxopLimit(), ns3::Txop::GetTxopRemaining(), ns3::MacLowTransmissionParameters::HasNextPacket(), IsCfPeriod(), ns3::EventId::IsExpired(), ns3::Txop::IsQosTxop(), ns3::Time::IsStrictlyPositive(), m_blockAckTimeoutEvent, m_currentPacket, m_currentTxop, m_endTxNoAckEvent, m_normalAckTimeoutEvent, m_phy, m_stationManager, m_txParams, m_waitIfsEvent, ns3::MacLowTransmissionParameters::MustWaitBlockAck(), ns3::MacLowTransmissionParameters::MustWaitNormalAck(), NormalAckTimeout(), NotifyAckTimeoutStartNow(), NS_ASSERT, ns3::Simulator::Schedule(), WaitIfsAfterEndTxFragment(), and WaitIfsAfterEndTxPacket().
Referenced by SendBlockAckResponse(), SendDataAfterCts(), and SendDataPacket().
StartTransmission()
void ns3::MacLow::StartTransmission (Ptr< WifiMacQueueItem > mpdu, MacLowTransmissionParameters parameters, Ptr< Txop > txop) virtual
Parameters
mpdu packet to send
parameters the transmission parameters to use for this packet.
txop pointer to the calling Txop.
Start the transmission of the input packet and notify the listener of transmission events.
Reimplemented in ns3::WaveMacLow.
Definition at line 493 of file mac-low.cc.
References CalculateOverheadTxTime(), CancelAllEvents(), ns3::QosTxop::DequeuePeekedFrame(), ns3::MacLow::CfAckInfo::expectCfAck, ns3::QosTxop::GetAckPolicySelector(), ns3::WifiMacHeader::GetAddr1(), GetDataTxVector(), ns3::WifiMacHeader::GetFragmentNumber(), ns3::WifiMacQueueItem::GetHeader(), ns3::WifiTxVector::GetMode(), ns3::WifiMode::GetModulationClass(), ns3::WifiMacQueueItem::GetPacket(), ns3::WifiMacHeader::GetQosTid(), GetRtsTxVector(), ns3::WifiMacHeader::GetSequenceNumber(), ns3::Txop::GetTxopLimit(), ns3::Txop::GetTxopRemaining(), ns3::WifiRemoteStationManager::GetUseNonErpProtection(), ns3::Mac48Address::IsBroadcast(), ns3::WifiMacHeader::IsCtl(), ns3::WifiMacHeader::IsMoreFragments(), ns3::Time::IsPositive(), ns3::WifiMacHeader::IsQosData(), ns3::WifiPhy::IsStateOff(), ns3::WifiPhy::IsStateTx(), ns3::Time::IsStrictlyPositive(), IsWithinSizeAndTimeLimits(), m_cfAckInfo, m_ctsToSelfSupported, m_currentPacket, m_currentTxop, m_currentTxVector, m_edca, m_mpduAggregator, m_phy, m_stationManager, m_txParams, ns3::Time::Min(), ns3::MacLowTransmissionParameters::MustSendRts(), NeedCtsToSelf(), NS_ASSERT, NS_LOG_DEBUG, NS_LOG_FUNCTION, aloha::params, ns3::QosTxop::PeekNextFrame(), ns3::QosUtilsMapTidToAc(), SendCtsToSelf(), SendDataPacket(), SendRtsForPacket(), ns3::QosTxop::SetAmpduExist(), ns3::QosTxop::UpdateCurrentPacket(), ns3::WIFI_MOD_CLASS_HE, and ns3::WIFI_MOD_CLASS_VHT.
Referenced by ns3::WaveMacLow::StartTransmission().
StoreMpduIfNeeded()
bool ns3::MacLow::StoreMpduIfNeeded (Ptr< WifiMacQueueItem > mpdu) private
Parameters
mpdu the MPDU
Returns
true if the MPDU stored
This method checks if exists a valid established block ack agreement. If there is, store the packet without pass it up to WifiMac. The packet is buffered in order of increasing sequence control field. All comparison are performed circularly modulo 2^12.
Definition at line 2232 of file mac-low.cc.
References ns3::WifiMacHeader::GetAddr2(), ns3::WifiMacQueueItem::GetHeader(), ns3::WifiMacHeader::GetQosTid(), ns3::WifiMacHeader::GetSequenceControl(), m_bAckAgreements, m_bAckCaches, NS_ASSERT, and ns3::QosUtilsMapSeqControlToUniqueInteger().
Referenced by ReceiveMpdu().
WaitIfsAfterEndTxFragment()
void ns3::MacLow::WaitIfsAfterEndTxFragment (void) private
Event handler that is usually scheduled to fired at the appropriate time after completing transmissions.
Definition at line 2128 of file mac-low.cc.
References m_currentTxop, NS_LOG_FUNCTION, and ns3::Txop::StartNextFragment().
Referenced by ReceiveOk(), and StartDataTxTimers().
WaitIfsAfterEndTxPacket()
void ns3::MacLow::WaitIfsAfterEndTxPacket (void) private
Event handler that is usually scheduled to fired at the appropriate time after sending a packet.
Definition at line 2135 of file mac-low.cc.
References m_currentTxop, NS_LOG_FUNCTION, and ns3::Txop::StartNextPacket().
Referenced by ReceiveOk(), and StartDataTxTimers().
Member Data Documentation
m_ackTimeout
Time ns3::MacLow::m_ackTimeout private
Ack timeout duration.
Definition at line 936 of file mac-low.h.
Referenced by GetAckTimeout(), and SetAckTimeout().
m_bAckAgreements
Agreements ns3::MacLow::m_bAckAgreements private
block ack agreements
Definition at line 972 of file mac-low.h.
Referenced by CreateBlockAckAgreement(), DeaggregateAmpduAndReceive(), DestroyBlockAckAgreement(), ReceiveMpdu(), ReceiveOk(), RxCompleteBufferedPacketsUntilFirstLost(), RxCompleteBufferedPacketsWithSmallerSequence(), SendBlockAckAfterAmpdu(), SendBlockAckAfterBlockAckRequest(), and StoreMpduIfNeeded().
m_bAckCaches
BlockAckCaches ns3::MacLow::m_bAckCaches private
block ack caches
Definition at line 973 of file mac-low.h.
Referenced by CreateBlockAckAgreement(), DestroyBlockAckAgreement(), ReceiveOk(), SendBlockAckAfterAmpdu(), SendBlockAckAfterBlockAckRequest(), and StoreMpduIfNeeded().
m_basicBlockAckTimeout
Time ns3::MacLow::m_basicBlockAckTimeout private
Basic BlockAck timeout duration.
Definition at line 937 of file mac-low.h.
Referenced by GetBasicBlockAckTimeout(), and SetBasicBlockAckTimeout().
m_beaconInterval
Time ns3::MacLow::m_beaconInterval private
Expected interval between two beacon transmissions.
Definition at line 944 of file mac-low.h.
Referenced by ForwardDown(), GetBeaconInterval(), and SetBeaconInterval().
m_blockAckTimeoutEvent
EventId ns3::MacLow::m_blockAckTimeoutEvent private
BlockAck timeout event.
Definition at line 922 of file mac-low.h.
Referenced by CancelAllEvents(), DoDispose(), ReceiveOk(), RxStartIndication(), and StartDataTxTimers().
m_bssid
Mac48Address ns3::MacLow::m_bssid private
BSSID address (Mac48Address)
Definition at line 935 of file mac-low.h.
Referenced by GetBssid(), NotifyNav(), and SetBssid().
m_cfAckInfo
CfAckInfo ns3::MacLow::m_cfAckInfo private
Info about piggyback Acks used in PCF.
Definition at line 981 of file mac-low.h.
Referenced by CfPollTimeout(), EndTxNoAck(), ForwardDown(), GetCfEndSize(), ReceiveError(), ReceiveOk(), SendDataPacket(), and StartTransmission().
m_cfpForeshortening
Time ns3::MacLow::m_cfpForeshortening private
The delay the current CF period should be foreshortened.
Definition at line 952 of file mac-low.h.
Referenced by ForwardDown(), and GetRemainingCfpDuration().
m_cfpMaxDuration
Time ns3::MacLow::m_cfpMaxDuration private
CFP max duration.
Definition at line 945 of file mac-low.h.
Referenced by GetCfpMaxDuration(), GetRemainingCfpDuration(), and SetCfpMaxDuration().
m_cfpStart
Time ns3::MacLow::m_cfpStart private
The time when the latest CF period started.
Definition at line 950 of file mac-low.h.
Referenced by EndTxNoAck(), ForwardDown(), GetRemainingCfpDuration(), IsCfPeriod(), and ReceiveOk().
m_channelAccessManagers
ChannelAccessManagers ns3::MacLow::m_channelAccessManagers private
List of ChannelAccessManager.
Definition at line 916 of file mac-low.h.
Referenced by CfPollTimeout(), DoNavResetNow(), DoNavStartNow(), NotifyAckTimeoutResetNow(), NotifyAckTimeoutStartNow(), NotifyCtsTimeoutResetNow(), NotifyCtsTimeoutStartNow(), and RegisterChannelAccessManager().
m_compressedBlockAckTimeout
Time ns3::MacLow::m_compressedBlockAckTimeout private
Compressed BlockAck timeout duration.
Definition at line 938 of file mac-low.h.
Referenced by GetCompressedBlockAckTimeout(), and SetCompressedBlockAckTimeout().
m_ctsTimeoutEvent
EventId ns3::MacLow::m_ctsTimeoutEvent private
CTS timeout event.
Definition at line 923 of file mac-low.h.
Referenced by CancelAllEvents(), DoDispose(), ReceiveOk(), RxStartIndication(), and SendRtsForPacket().
m_ctsToSelfSupported
bool ns3::MacLow::m_ctsToSelfSupported private
Flag whether CTS-to-self is supported.
Definition at line 978 of file mac-low.h.
Referenced by GetCtsToSelfSupported(), SetCtsToSelfSupported(), and StartTransmission().
m_currentPacket
Ptr<WifiPsdu> ns3::MacLow::m_currentPacket private
Current packet transmitted/to be transmitted.
Definition at line 931 of file mac-low.h.
Referenced by BlockAckTimeout(), CalculateOverallTxTime(), CtsTimeout(), EndTxNoAck(), NeedCtsToSelf(), NotifyOffNow(), NotifySleepNow(), NotifySwitchingStartNow(), ReceiveError(), ReceiveOk(), SendCtsToSelf(), SendDataAfterCts(), SendDataPacket(), SendRtsForPacket(), StartDataTxTimers(), and StartTransmission().
m_currentTxop
Ptr<Txop> ns3::MacLow::m_currentTxop private
Current TXOP.
Definition at line 932 of file mac-low.h.
Referenced by BlockAckTimeout(), CancelAllEvents(), CfPollTimeout(), CtsTimeout(), EndTxNoAck(), NormalAckTimeout(), NotifyOffNow(), NotifySleepNow(), NotifySwitchingStartNow(), ReceiveError(), ReceiveOk(), SendDataAfterCts(), SendDataPacket(), StartDataTxTimers(), StartTransmission(), WaitIfsAfterEndTxFragment(), and WaitIfsAfterEndTxPacket().
m_currentTxVector
WifiTxVector ns3::MacLow::m_currentTxVector private
TXVECTOR used for the current packet transmission.
Definition at line 979 of file mac-low.h.
Referenced by CanTransmitNextCfFrame(), SendCtsToSelf(), SendDataAfterCts(), SendDataPacket(), SendRtsForPacket(), and StartTransmission().
m_edca
QueueEdcas ns3::MacLow::m_edca private
EDCA queues.
Definition at line 976 of file mac-low.h.
Referenced by CreateBlockAckAgreement(), ForwardDown(), GetEdca(), ReceiveOk(), RegisterEdcaForAc(), ResetBlockAckInactivityTimerIfNeeded(), and StartTransmission().
m_endTxNoAckEvent
EventId ns3::MacLow::m_endTxNoAckEvent private
Event for finishing transmission that does not require Ack.
Definition at line 928 of file mac-low.h.
Referenced by CancelAllEvents(), DoDispose(), and StartDataTxTimers().
m_lastBeacon
Time ns3::MacLow::m_lastBeacon private
The time when the last beacon frame transmission started.
Definition at line 951 of file mac-low.h.
Referenced by ForwardDown().
m_lastNavDuration
Time ns3::MacLow::m_lastNavDuration private
The duration of the latest NAV.
Definition at line 948 of file mac-low.h.
Referenced by DoNavResetNow(), DoNavStartNow(), IsNavZero(), NotifyOffNow(), NotifySleepNow(), and NotifySwitchingStartNow().
m_lastNavStart
Time ns3::MacLow::m_lastNavStart private
The time when the latest NAV started.
Definition at line 947 of file mac-low.h.
Referenced by DoNavResetNow(), DoNavStartNow(), IsNavZero(), NotifyNav(), NotifyOffNow(), NotifySleepNow(), and NotifySwitchingStartNow().
m_mac
Ptr<WifiMac> ns3::MacLow::m_mac private
Pointer to WifiMac (to fetch configuration)
Definition at line 894 of file mac-low.h.
Referenced by SetMac().
m_mpduAggregator
Ptr<MpduAggregator> ns3::MacLow::m_mpduAggregator private
A-MPDU aggregator.
Definition at line 919 of file mac-low.h.
Referenced by DoDispose(), GetMpduAggregator(), SetMpduAggregator(), and StartTransmission().
m_msduAggregator
Ptr<MsduAggregator> ns3::MacLow::m_msduAggregator private
A-MSDU aggregator.
Definition at line 918 of file mac-low.h.
Referenced by DoDispose(), GetMsduAggregator(), and SetMsduAggregator().
m_navCounterResetCtsMissed
EventId ns3::MacLow::m_navCounterResetCtsMissed private
Event to reset NAV when CTS is not received.
Definition at line 929 of file mac-low.h.
Referenced by NotifyNav(), NotifyOffNow(), NotifySleepNow(), NotifySwitchingStartNow(), and RxStartIndication().
m_normalAckTimeoutEvent
EventId ns3::MacLow::m_normalAckTimeoutEvent private
Normal Ack timeout event.
Definition at line 921 of file mac-low.h.
Referenced by CancelAllEvents(), DoDispose(), ReceiveOk(), RxStartIndication(), and StartDataTxTimers().
m_phy
Ptr<WifiPhy> ns3::MacLow::m_phy private
Pointer to WifiPhy (actually send/receives frames)
Definition at line 893 of file mac-low.h.
Referenced by CalculateOverallTxTime(), CalculateOverheadTxTime(), CalculateTransmissionTime(), CanTransmitNextCfFrame(), DoDispose(), ForwardDown(), GetAckDuration(), GetAckTxVector(), GetBlockAckDuration(), GetBlockAckRequestDuration(), GetBlockAckTxVector(), GetControlAnswerMode(), GetCtsDuration(), GetCtsTxVector(), GetPhy(), IsWithinSizeAndTimeLimits(), NotifyNav(), ResetPhy(), SendBlockAckAfterAmpdu(), SendCtsToSelf(), SendDataAfterCts(), SendDataPacket(), SendRtsForPacket(), SetPhy(), StartDataTxTimers(), and StartTransmission().
m_phyMacLowListener
class PhyMacLowListener* ns3::MacLow::m_phyMacLowListener private
Listener needed to monitor when a channel switching occurs.
Definition at line 956 of file mac-low.h.
Referenced by DoDispose(), RemovePhyMacLowListener(), and SetupPhyMacLowListener().
m_pifs
Time ns3::MacLow::m_pifs private
PCF Interframe Space (PIFS) duration.
Definition at line 941 of file mac-low.h.
Referenced by GetPifs(), and SetPifs().
m_promisc
bool ns3::MacLow::m_promisc private
Flag if the device is operating in promiscuous mode.
Definition at line 954 of file mac-low.h.
Referenced by IsPromisc(), ReceiveOk(), and SetPromisc().
m_rifs
Time ns3::MacLow::m_rifs private
Reduced Interframe Space (RIFS) duration.
Definition at line 942 of file mac-low.h.
Referenced by GetRifs(), and SetRifs().
m_rxCallback
MacLowRxCallback ns3::MacLow::m_rxCallback private
Callback to pass packet up.
Definition at line 896 of file mac-low.h.
Referenced by ReceiveOk(), RxCompleteBufferedPacketsUntilFirstLost(), RxCompleteBufferedPacketsWithSmallerSequence(), and SetRxCallback().
m_self
Mac48Address ns3::MacLow::m_self private
Address of this MacLow (Mac48Address)
Definition at line 934 of file mac-low.h.
Referenced by DeaggregateAmpduAndReceive(), GetAddress(), GetResponseDuration(), NotifyNav(), ReceiveOk(), SendCtsToSelf(), SendRtsForPacket(), and SetAddress().
m_sendAckEvent
EventId ns3::MacLow::m_sendAckEvent private
Event to send Ack.
Definition at line 925 of file mac-low.h.
Referenced by CancelAllEvents(), DeaggregateAmpduAndReceive(), DoDispose(), and ReceiveOk().
m_sendCtsEvent
EventId ns3::MacLow::m_sendCtsEvent private
Event to send CTS.
Definition at line 924 of file mac-low.h.
Referenced by CancelAllEvents(), DoDispose(), and ReceiveOk().
m_sendDataEvent
EventId ns3::MacLow::m_sendDataEvent private
Event to send Data.
Definition at line 926 of file mac-low.h.
Referenced by CancelAllEvents(), DoDispose(), ReceiveOk(), and SendCtsToSelf().
m_sifs
Time ns3::MacLow::m_sifs private
Short Interframe Space (SIFS) duration.
Definition at line 939 of file mac-low.h.
Referenced by GetSifs(), and SetSifs().
m_slotTime
Time ns3::MacLow::m_slotTime private
Slot duration.
Definition at line 940 of file mac-low.h.
Referenced by GetSlotTime(), and SetSlotTime().
m_stationManager
Ptr<WifiRemoteStationManager> ns3::MacLow::m_stationManager private
Pointer to WifiRemoteStationManager (rate control)
Definition at line 895 of file mac-low.h.
Referenced by CtsTimeout(), DoDispose(), EndTxNoAck(), ForwardDown(), GetAckTxVector(), GetBlockAckTxVector(), GetControlAnswerMode(), GetCtsTxVector(), GetDataTxVector(), GetRtsTxVector(), IsCfPeriod(), NeedCtsToSelf(), NotifySwitchingStartNow(), ReceiveMpdu(), ReceiveOk(), SendBlockAckAfterBlockAckRequest(), SendDataAfterCts(), SendDataPacket(), SetWifiRemoteStationManager(), StartDataTxTimers(), and StartTransmission().
m_txParams
MacLowTransmissionParameters ns3::MacLow::m_txParams private
Transmission parameters of the current packet.
Definition at line 933 of file mac-low.h.
Referenced by ReceiveOk(), SendBlockAckResponse(), SendCtsToSelf(), SendDataAfterCts(), SendDataPacket(), SendRtsForPacket(), StartDataTxTimers(), and StartTransmission().
m_waitIfsEvent
EventId ns3::MacLow::m_waitIfsEvent private
Wait for IFS event.
Definition at line 927 of file mac-low.h.
Referenced by CancelAllEvents(), DoDispose(), ReceiveOk(), and StartDataTxTimers().
The documentation for this class was generated from the following files:
src/wifi/model/mac-low.h
src/wifi/model/mac-low.cc