ns-3: ns3::RipRoutingTableEntry Class Reference
ns3::RipRoutingTableEntry Class Reference
Internet » IPv4 Routing Protocols. » RIP
Rip Routing Table Entry.
#include "rip.h"
Public Types
enum Status_e { RIP_VALID, RIP_INVALID }
Route status.
Public Member Functions
RipRoutingTableEntry (Ipv4Address network, Ipv4Mask networkPrefix, Ipv4Address nextHop, uint32_t interface)
Constructor.
RipRoutingTableEntry (Ipv4Address network, Ipv4Mask networkPrefix, uint32_t interface)
Constructor.
RipRoutingTableEntry (void)
virtual ~RipRoutingTableEntry ()
uint8_t GetRouteMetric (void) const
Get the route metric.
Status_e GetRouteStatus (void) const
Get the route status.
uint16_t GetRouteTag (void) const
Get the route tag.
bool IsRouteChanged (void) const
Get the route changed status.
void SetRouteChanged (bool changed)
Set the route as changed.
void SetRouteMetric (uint8_t routeMetric)
Set the route metric.
void SetRouteStatus (Status_e status)
Set the route status.
void SetRouteTag (uint16_t routeTag)
Set the route tag.
Public Member Functions inherited from ns3::Ipv4RoutingTableEntry
Ipv4RoutingTableEntry ()
This constructor does nothing.
Ipv4RoutingTableEntry (Ipv4RoutingTableEntry const &route)
Copy Constructor.
Ipv4RoutingTableEntry (Ipv4RoutingTableEntry const *route)
Copy Constructor.
Ipv4Address GetDest (void) const
Ipv4Address GetDestNetwork (void) const
Ipv4Mask GetDestNetworkMask (void) const
Ipv4Address GetGateway (void) const
uint32_t GetInterface (void) const
bool IsDefault (void) const
bool IsGateway (void) const
bool IsHost (void) const
bool IsNetwork (void) const
Private Attributes
bool m_changed
route has been updated
uint8_t m_metric
route metric
Status_e m_status
route status
uint16_t m_tag
route tag
Additional Inherited Members
Static Public Member Functions inherited from ns3::Ipv4RoutingTableEntry
static Ipv4RoutingTableEntry CreateDefaultRoute (Ipv4Address nextHop, uint32_t interface)
static Ipv4RoutingTableEntry CreateHostRouteTo (Ipv4Address dest, Ipv4Address nextHop, uint32_t interface)
static Ipv4RoutingTableEntry CreateHostRouteTo (Ipv4Address dest, uint32_t interface)
static Ipv4RoutingTableEntry CreateNetworkRouteTo (Ipv4Address network, Ipv4Mask networkMask, Ipv4Address nextHop, uint32_t interface)
static Ipv4RoutingTableEntry CreateNetworkRouteTo (Ipv4Address network, Ipv4Mask networkMask, uint32_t interface)
Detailed Description
Rip Routing Table Entry.
Definition at line 63 of file rip.h.
Member Enumeration Documentation
Status_e
enum ns3::RipRoutingTableEntry::Status_e
Route status.
Enumerator
RIP_VALID
RIP_INVALID
Definition at line 70 of file rip.h.
Constructor & Destructor Documentation
RipRoutingTableEntry() [1/3]
ns3::RipRoutingTableEntry::RipRoutingTableEntry (void)
Definition at line 1298 of file rip.cc.
RipRoutingTableEntry() [2/3]
ns3::RipRoutingTableEntry::RipRoutingTableEntry (Ipv4Address network, Ipv4Mask networkPrefix, Ipv4Address nextHop, uint32_t interface)
Constructor.
Parameters
network network address
networkPrefix network prefix
nextHop next hop address to route the packet
interface interface index
Definition at line 1303 of file rip.cc.
RipRoutingTableEntry() [3/3]
ns3::RipRoutingTableEntry::RipRoutingTableEntry (Ipv4Address network, Ipv4Mask networkPrefix, uint32_t interface)
Constructor.
Parameters
network network address
networkPrefix network prefix
interface interface index
Definition at line 1309 of file rip.cc.
~RipRoutingTableEntry()
ns3::RipRoutingTableEntry::~RipRoutingTableEntry () virtual
Definition at line 1315 of file rip.cc.
Member Function Documentation
GetRouteMetric()
uint8_t ns3::RipRoutingTableEntry::GetRouteMetric (void) const
Get the route metric.
Returns
the route metric
Definition at line 1343 of file rip.cc.
References m_metric.
Referenced by ns3::operator<<(), and ns3::Rip::PrintRoutingTable().
GetRouteStatus()
RipRoutingTableEntry::Status_e ns3::RipRoutingTableEntry::GetRouteStatus (void) const
Get the route status.
Returns
the route status
Definition at line 1357 of file rip.cc.
References m_status.
Referenced by ns3::Rip::Lookup(), and ns3::Rip::PrintRoutingTable().
GetRouteTag()
uint16_t ns3::RipRoutingTableEntry::GetRouteTag (void) const
Get the route tag.
Returns
the route tag
Definition at line 1329 of file rip.cc.
References m_tag.
Referenced by ns3::operator<<().
IsRouteChanged()
bool ns3::RipRoutingTableEntry::IsRouteChanged (void) const
Get the route changed status.
Returns
true if route is changed
Definition at line 1367 of file rip.cc.
References m_changed.
SetRouteChanged()
void ns3::RipRoutingTableEntry::SetRouteChanged (bool changed)
Set the route as changed.
The changed routes are scheduled for a Triggered Update. After a Triggered Update, all the changed flags are cleared from the routing table.
Parameters
changed true if route is changed
Definition at line 1362 of file rip.cc.
References m_changed.
Referenced by ns3::Rip::AddNetworkRouteTo(), ns3::Rip::HandleResponses(), and ns3::Rip::InvalidateRoute().
SetRouteMetric()
void ns3::RipRoutingTableEntry::SetRouteMetric (uint8_t routeMetric)
Set the route metric.
Parameters
routeMetric the route metric
Definition at line 1334 of file rip.cc.
References m_changed, and m_metric.
Referenced by ns3::Rip::AddNetworkRouteTo(), ns3::Rip::HandleResponses(), and ns3::Rip::InvalidateRoute().
SetRouteStatus()
void ns3::RipRoutingTableEntry::SetRouteStatus (Status_e status)
Set the route status.
Parameters
status the route status
Definition at line 1348 of file rip.cc.
References m_changed, and m_status.
Referenced by ns3::Rip::AddNetworkRouteTo(), ns3::Rip::HandleResponses(), and ns3::Rip::InvalidateRoute().
SetRouteTag()
void ns3::RipRoutingTableEntry::SetRouteTag (uint16_t routeTag)
Set the route tag.
Parameters
routeTag the route tag
Definition at line 1320 of file rip.cc.
References m_changed, and m_tag.
Referenced by ns3::Rip::HandleResponses().
Member Data Documentation
m_changed
bool ns3::RipRoutingTableEntry::m_changed private
route has been updated
Definition at line 154 of file rip.h.
Referenced by IsRouteChanged(), SetRouteChanged(), SetRouteMetric(), SetRouteStatus(), and SetRouteTag().
m_metric
uint8_t ns3::RipRoutingTableEntry::m_metric private
route metric
Definition at line 152 of file rip.h.
Referenced by GetRouteMetric(), and SetRouteMetric().
m_status
Status_e ns3::RipRoutingTableEntry::m_status private
route status
Definition at line 153 of file rip.h.
Referenced by GetRouteStatus(), and SetRouteStatus().
m_tag
uint16_t ns3::RipRoutingTableEntry::m_tag private
route tag
Definition at line 151 of file rip.h.
Referenced by GetRouteTag(), and SetRouteTag().
The documentation for this class was generated from the following files:
src/internet/model/rip.h
src/internet/model/rip.cc