ns-3: DhcpTestCase Class Reference
DhcpTestCase Class Reference
Internet Applications » DHCPv4 Client and Server » DHCP module tests | Test suites
DHCP basic tests.
Public Member Functions
DhcpTestCase ()
virtual ~DhcpTestCase ()
void LeaseObtained (std::string context, const Ipv4Address &newAddress)
Triggered by an address lease on a client.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
Ipv4Address m_leasedAddress [3]
Address given to the nodes.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
DHCP basic tests.
Definition at line 47 of file dhcp-test.cc.
Constructor & Destructor Documentation
DhcpTestCase()
DhcpTestCase::DhcpTestCase ()
Definition at line 63 of file dhcp-test.cc.
~DhcpTestCase()
DhcpTestCase::~DhcpTestCase () virtual
Definition at line 68 of file dhcp-test.cc.
Member Function Documentation
DoRun()
void DhcpTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 84 of file dhcp-test.cc.
References ns3::NetDeviceContainer::Add(), ns3::NodeContainer::Create(), ns3::ApplicationContainer::Get(), ns3::NetDeviceContainer::Get(), ns3::SimpleNetDeviceHelper::Install(), ns3::InternetStackHelper::Install(), ns3::DhcpHelper::InstallDhcpClient(), ns3::DhcpHelper::InstallDhcpServer(), LeaseObtained(), m_leasedAddress, ns3::MakeCallback(), ns3::MilliSeconds(), first::nodes, NS_TEST_ASSERT_MSG_EQ, ns3::Seconds(), ns3::SimpleNetDeviceHelper::SetChannelAttribute(), ns3::SimpleNetDeviceHelper::SetDeviceAttribute(), ns3::ApplicationContainer::Start(), ns3::ApplicationContainer::Stop(), and ns3::ObjectBase::TraceConnect().
LeaseObtained()
void DhcpTestCase::LeaseObtained (std::string context, const Ipv4Address & newAddress)
Triggered by an address lease on a client.
Parameters
context The test name.
newAddress The leased address.
Definition at line 73 of file dhcp-test.cc.
References m_leasedAddress.
Referenced by DoRun().
Member Data Documentation
m_leasedAddress
Ipv4Address DhcpTestCase::m_leasedAddress[3] private
Address given to the nodes.
Definition at line 60 of file dhcp-test.cc.
Referenced by DoRun(), and LeaseObtained().
The documentation for this class was generated from the following file:
src/internet-apps/test/dhcp-test.cc