ns-3: grid.Colors Class Reference
grid.Colors Class Reference
Colors class.
Public Member Functions
def __init__ (self)
Initializer.
def add (self, name, color)
Add.
def lookup (self, name)
Lookup name.
Static Public Attributes
list default_colors = [Color(1, 0, 0), Color(0, 1, 0), Color(0, 0, 1), Color(1, 1, 0), Color(1, 0, 1), Color(0, 1, 1)]
Private Attributes
__colors
Detailed Description
Colors class.
Definition at line 468 of file grid.py.
Constructor & Destructor Documentation
__init__()
def grid.Colors.__init__ (self)
Initializer.
Parameters
self this object
Returns
none
Definition at line 475 of file grid.py.
Member Function Documentation
add()
def grid.Colors.add (self, name, color)
Add.
Parameters
self this object
name name of the color
color color value
Returns
none
Definition at line 481 of file grid.py.
References grid.Colors.__colors.
Referenced by grid.Colors.lookup().
lookup()
def grid.Colors.lookup (self, name)
Lookup name.
Parameters
self this object
name name
Returns
named color
Definition at line 489 of file grid.py.
References grid.Colors.__colors, grid.Colors.add(), and grid.Colors.default_colors.
Member Data Documentation
__colors
grid.Colors.__colors private
colors
Definition at line 480 of file grid.py.
Referenced by grid.Colors.add(), grid.TopLegendRenderer.draw(), and grid.Colors.lookup().
default_colors
grid.Colors.default_colors = [Color(1, 0, 0), Color(0, 1, 0), Color(0, 0, 1), Color(1, 1, 0), Color(1, 0, 1), Color(0, 1, 1)] static
default colors XXX add more
Definition at line 474 of file grid.py.
Referenced by grid.Colors.lookup().
The documentation for this class was generated from the following file:
utils/grid.py