ns-3: ns3::FrameCaptureModel Class Reference
ns3::FrameCaptureModel Class Reference abstract
Wifi Models
the interface for Wifi's frame capture models
#include "frame-capture-model.h"
Public Member Functions
virtual bool CaptureNewFrame (Ptr< Event > currentEvent, Ptr< Event > newEvent) const =0
A pure virtual method that must be implemented in the subclass.
virtual bool IsInCaptureWindow (Time timePreambleDetected) const
This method returns true if the capture window duration has not elapsed yet, false otherwise.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Time m_captureWindow
Capture window duration.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
the interface for Wifi's frame capture models
Definition at line 36 of file frame-capture-model.h.
Member Function Documentation
CaptureNewFrame()
virtual bool ns3::FrameCaptureModel::CaptureNewFrame (Ptr< Event > currentEvent, Ptr< Event > newEvent) const pure virtual
A pure virtual method that must be implemented in the subclass.
This method returns whether the reception should be switched to a new incoming frame.
Parameters
currentEvent the event of the current frame
newEvent the event of the new incoming frame
Returns
true if the reception should be switched to a new incoming frame, false otherwise
Implemented in ns3::SimpleFrameCaptureModel.
GetTypeId()
TypeId ns3::FrameCaptureModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 29 of file frame-capture-model.cc.
References m_captureWindow, ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MicroSeconds(), and ns3::TypeId::SetParent().
IsInCaptureWindow()
bool ns3::FrameCaptureModel::IsInCaptureWindow (Time timePreambleDetected) const virtual
This method returns true if the capture window duration has not elapsed yet, false otherwise.
Parameters
timePreambleDetected the time the preamble was detected
Returns
true if the capture window duration has not elapsed yet, false otherwise
Definition at line 44 of file frame-capture-model.cc.
References m_captureWindow, and ns3::Simulator::Now().
Referenced by ns3::SimpleFrameCaptureModel::CaptureNewFrame().
Member Data Documentation
m_captureWindow
Time ns3::FrameCaptureModel::m_captureWindow private
Capture window duration.
Definition at line 71 of file frame-capture-model.h.
Referenced by GetTypeId(), and IsInCaptureWindow().
The documentation for this class was generated from the following files:
src/wifi/model/frame-capture-model.h
src/wifi/model/frame-capture-model.cc