ns-3: CoDelQueueDiscBasicDrop Class Reference
CoDelQueueDiscBasicDrop Class Reference
Traffic-control » traffic-control module tests | Test suites
Test 5: enqueue/dequeue with drops according to CoDel algorithm.
Public Member Functions
CoDelQueueDiscBasicDrop (QueueSizeUnit mode)
Constructor.
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void Dequeue (Ptr< CoDelQueueDisc > queue, uint32_t modeSize)
Dequeue function.
void DropNextTracer (uint32_t oldVal, uint32_t newVal)
Drop next tracer function.
void Enqueue (Ptr< CoDelQueueDisc > queue, uint32_t size, uint32_t nPkt)
Enqueue function.
Private Attributes
uint32_t m_dropNextCount
count the number of times m_dropNext is recalculated
QueueSizeUnit m_mode
mode
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test 5: enqueue/dequeue with drops according to CoDel algorithm.
Definition at line 414 of file codel-queue-disc-test-suite.cc.
Constructor & Destructor Documentation
CoDelQueueDiscBasicDrop()
CoDelQueueDiscBasicDrop::CoDelQueueDiscBasicDrop (QueueSizeUnit mode)
Constructor.
Parameters
mode the mode
Definition at line 448 of file codel-queue-disc-test-suite.cc.
References m_dropNextCount, and m_mode.
Member Function Documentation
Dequeue()
void CoDelQueueDiscBasicDrop::Dequeue (Ptr< CoDelQueueDisc > queue, uint32_t modeSize) private
Dequeue function.
Parameters
queue the queue disc
modeSize the mode size
Definition at line 519 of file codel-queue-disc-test-suite.cc.
References ns3::QueueDisc::Dequeue(), DropNextTracer(), ns3::QueueDisc::GetCurrentSize(), ns3::CoDelQueueDisc::GetDropNext(), ns3::CoDelQueueDisc::GetInterval(), ns3::Time::GetMicroSeconds(), ns3::QueueDisc::Stats::GetNDroppedPackets(), ns3::QueueDisc::GetStats(), ns3::CoDelQueueDisc::GetTarget(), ns3::QueueSize::GetValue(), m_dropNextCount, ns3::MakeCallback(), ns3::Now(), NS_TEST_EXPECT_MSG_EQ, and ns3::ObjectBase::TraceConnectWithoutContext().
Referenced by DoRun().
DoRun()
void CoDelQueueDiscBasicDrop::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 464 of file codel-queue-disc-test-suite.cc.
References ns3::BYTES, Dequeue(), Enqueue(), ns3::QueueDisc::GetCurrentSize(), ns3::CoDelQueueDisc::GetInterval(), ns3::CoDelQueueDisc::GetTarget(), ns3::QueueSize::GetValue(), ns3::Object::Initialize(), m_mode, NS_TEST_EXPECT_MSG_EQ, ns3::PACKETS, and ns3::ObjectBase::SetAttributeFailSafe().
DropNextTracer()
void CoDelQueueDiscBasicDrop::DropNextTracer (uint32_t oldVal, uint32_t newVal) private
Drop next tracer function.
Parameters
oldVal the old value
newVal the new value
Definition at line 456 of file codel-queue-disc-test-suite.cc.
References m_dropNextCount, and NS_UNUSED.
Referenced by Dequeue().
Enqueue()
void CoDelQueueDiscBasicDrop::Enqueue (Ptr< CoDelQueueDisc > queue, uint32_t size, uint32_t nPkt) private
Enqueue function.
Parameters
queue the queue disc
size the size
nPkt the number of packets
Definition at line 509 of file codel-queue-disc-test-suite.cc.
References ns3::QueueDisc::Enqueue().
Referenced by DoRun().
Member Data Documentation
m_dropNextCount
uint32_t CoDelQueueDiscBasicDrop::m_dropNextCount private
count the number of times m_dropNext is recalculated
Definition at line 445 of file codel-queue-disc-test-suite.cc.
Referenced by CoDelQueueDiscBasicDrop(), Dequeue(), and DropNextTracer().
m_mode
QueueSizeUnit CoDelQueueDiscBasicDrop::m_mode private
mode
Definition at line 444 of file codel-queue-disc-test-suite.cc.
Referenced by CoDelQueueDiscBasicDrop(), and DoRun().
The documentation for this class was generated from the following file:
src/traffic-control/test/codel-queue-disc-test-suite.cc