ns-3: ns3::SixLowPanUdpNhcExtension Class Reference
ns3::SixLowPanUdpNhcExtension Class Reference
6LoWPAN
UDP LOWPAN_NHC Extension Header Encoding - see RFC 6282.
#include "sixlowpan-header.h"
Public Types
enum Ports_e { PORTS_INLINE = 0, PORTS_ALL_SRC_LAST_DST, PORTS_LAST_SRC_ALL_DST, PORTS_LAST_SRC_LAST_DST }
Ports:
Public Member Functions
SixLowPanUdpNhcExtension (void)
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
bool GetC (void) const
Get the C (Checksum).
uint16_t GetChecksum (void) const
Get the Checksum field value.
uint16_t GetDstPort () const
Get the Destination Port.
virtual TypeId GetInstanceTypeId (void) const
Return the instance type identifier.
virtual SixLowPanDispatch::NhcDispatch_e GetNhcDispatchType (void) const
Get the NhcDispatch type.
Ports_e GetPorts (void) const
Get the compressed Src and Dst Ports.
virtual uint32_t GetSerializedSize (void) const
Get the serialized size of the packet.
uint16_t GetSrcPort () const
Get the Source Port.
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetC (bool cField)
Set the C (Checksum).
void SetChecksum (uint16_t checksum)
Set the Checksum field values.
void SetDstPort (uint16_t port)
Set the Destination Port.
void SetPorts (Ports_e port)
Set the compressed Src and Dst Ports.
void SetSrcPort (uint16_t port)
Set the Source Port.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_baseFormat
Dispatch + encoding fields.
uint16_t m_checksum
Checksum.
uint16_t m_dstPort
Destination port.
uint16_t m_srcPort
Source port.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
UDP LOWPAN_NHC Extension Header Encoding - see RFC 6282.
   0   1   2   3   4   5   6   7
 +---+---+---+---+---+---+---+---+
 | 1 | 1 | 1 | 1 | 0 | C |   P   |
 +---+---+---+---+---+---+---+---+
Definition at line 1103 of file sixlowpan-header.h.
Member Enumeration Documentation
Ports_e
enum ns3::SixLowPanUdpNhcExtension::Ports_e
Ports:
00: 16 bits for both Source Port and Destination Port 01: 16 bits for Source Port. Last 8 bits for Destination Port 10: Last 8 bits for Source Port. All 16 bits for Destination Port 11: Last 4 bits of both Source Port and Destination Port
Enumerator
PORTS_INLINE
PORTS_ALL_SRC_LAST_DST
PORTS_LAST_SRC_ALL_DST
PORTS_LAST_SRC_LAST_DST
Definition at line 1114 of file sixlowpan-header.h.
Constructor & Destructor Documentation
SixLowPanUdpNhcExtension()
ns3::SixLowPanUdpNhcExtension::SixLowPanUdpNhcExtension (void)
Definition at line 1618 of file sixlowpan-header.cc.
References m_baseFormat, m_checksum, m_dstPort, and m_srcPort.
Member Function Documentation
Deserialize()
uint32_t ns3::SixLowPanUdpNhcExtension::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
[in] start Buffer iterator.
Returns
Size of the packet.
Implements ns3::Header.
Definition at line 1708 of file sixlowpan-header.cc.
References GetC(), GetPorts(), GetSerializedSize(), m_baseFormat, m_checksum, m_dstPort, m_srcPort, PORTS_ALL_SRC_LAST_DST, PORTS_INLINE, PORTS_LAST_SRC_ALL_DST, PORTS_LAST_SRC_LAST_DST, ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetC()
bool ns3::SixLowPanUdpNhcExtension::GetC (void) const
Get the C (Checksum).
Returns
False (All checksum carried in-line), true (Checksum elided).
Definition at line 1790 of file sixlowpan-header.cc.
References m_baseFormat.
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanUdpNhc(), Deserialize(), GetSerializedSize(), and Serialize().
GetChecksum()
uint16_t ns3::SixLowPanUdpNhcExtension::GetChecksum (void) const
Get the Checksum field value.
Returns
The Checksum field value.
Definition at line 1800 of file sixlowpan-header.cc.
References m_checksum.
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanUdpNhc().
GetDstPort()
uint16_t ns3::SixLowPanUdpNhcExtension::GetDstPort () const
Get the Destination Port.
Returns
The Destination Port.
Definition at line 1779 of file sixlowpan-header.cc.
References m_dstPort.
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanUdpNhc().
GetInstanceTypeId()
TypeId ns3::SixLowPanUdpNhcExtension::GetInstanceTypeId (void) const virtual
Return the instance type identifier.
Returns
Instance type ID.
Implements ns3::ObjectBase.
Definition at line 1636 of file sixlowpan-header.cc.
References GetTypeId().
GetNhcDispatchType()
SixLowPanDispatch::NhcDispatch_e ns3::SixLowPanUdpNhcExtension::GetNhcDispatchType (void) const virtual
Get the NhcDispatch type.
Returns
The NhcDispatch type.
Definition at line 1748 of file sixlowpan-header.cc.
References ns3::SixLowPanDispatch::LOWPAN_UDPNHC.
GetPorts()
SixLowPanUdpNhcExtension::Ports_e ns3::SixLowPanUdpNhcExtension::GetPorts (void) const
Get the compressed Src and Dst Ports.
Returns
The Src and Dst Ports.
Definition at line 1759 of file sixlowpan-header.cc.
References m_baseFormat.
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanUdpNhc(), Deserialize(), GetSerializedSize(), and Serialize().
GetSerializedSize()
uint32_t ns3::SixLowPanUdpNhcExtension::GetSerializedSize (void) const virtual
Get the serialized size of the packet.
Returns
Size.
Implements ns3::Header.
Definition at line 1646 of file sixlowpan-header.cc.
References GetC(), GetPorts(), PORTS_ALL_SRC_LAST_DST, PORTS_INLINE, PORTS_LAST_SRC_ALL_DST, and PORTS_LAST_SRC_LAST_DST.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanUdpNhc(), and Deserialize().
GetSrcPort()
uint16_t ns3::SixLowPanUdpNhcExtension::GetSrcPort () const
Get the Source Port.
Returns
The Source Port.
Definition at line 1769 of file sixlowpan-header.cc.
References m_srcPort.
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanUdpNhc().
GetTypeId()
TypeId ns3::SixLowPanUdpNhcExtension::GetTypeId (void) static
Get the type ID.
Returns
The object TypeId.
Definition at line 1627 of file sixlowpan-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::SixLowPanUdpNhcExtension::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 1641 of file sixlowpan-header.cc.
References m_baseFormat.
Referenced by ns3::operator<<().
Serialize()
void ns3::SixLowPanUdpNhcExtension::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
[in] start Buffer iterator.
Implements ns3::Header.
Definition at line 1671 of file sixlowpan-header.cc.
References GetC(), GetPorts(), m_baseFormat, m_checksum, m_dstPort, m_srcPort, PORTS_ALL_SRC_LAST_DST, PORTS_INLINE, PORTS_LAST_SRC_ALL_DST, PORTS_LAST_SRC_LAST_DST, visualizer.core::start(), ns3::Buffer::Iterator::WriteHtonU16(), ns3::Buffer::Iterator::WriteU16(), and ns3::Buffer::Iterator::WriteU8().
SetC()
void ns3::SixLowPanUdpNhcExtension::SetC (bool cField)
Set the C (Checksum).
Parameters
[in] cField False (All checksum carried in-line), true (Checksum elided).
Definition at line 1784 of file sixlowpan-header.cc.
References m_baseFormat.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanUdpNhc().
SetChecksum()
void ns3::SixLowPanUdpNhcExtension::SetChecksum (uint16_t checksum)
Set the Checksum field values.
Parameters
[in] checksum The Checksum field value.
Definition at line 1795 of file sixlowpan-header.cc.
References m_checksum.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanUdpNhc().
SetDstPort()
void ns3::SixLowPanUdpNhcExtension::SetDstPort (uint16_t port)
Set the Destination Port.
Parameters
[in] port The Destination Port.
Definition at line 1774 of file sixlowpan-header.cc.
References m_dstPort.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanUdpNhc().
SetPorts()
void ns3::SixLowPanUdpNhcExtension::SetPorts (Ports_e port)
Set the compressed Src and Dst Ports.
Parameters
[in] port Src and Dst Ports.
Definition at line 1753 of file sixlowpan-header.cc.
References m_baseFormat.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanUdpNhc().
SetSrcPort()
void ns3::SixLowPanUdpNhcExtension::SetSrcPort (uint16_t port)
Set the Source Port.
Parameters
[in] port The Source Port.
Definition at line 1764 of file sixlowpan-header.cc.
References m_srcPort.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanUdpNhc().
Member Data Documentation
m_baseFormat
uint8_t ns3::SixLowPanUdpNhcExtension::m_baseFormat private
Dispatch + encoding fields.
Definition at line 1224 of file sixlowpan-header.h.
Referenced by SixLowPanUdpNhcExtension(), Deserialize(), GetC(), GetPorts(), Print(), Serialize(), SetC(), and SetPorts().
m_checksum
uint16_t ns3::SixLowPanUdpNhcExtension::m_checksum private
Checksum.
Definition at line 1225 of file sixlowpan-header.h.
Referenced by SixLowPanUdpNhcExtension(), Deserialize(), GetChecksum(), Serialize(), and SetChecksum().
m_dstPort
uint16_t ns3::SixLowPanUdpNhcExtension::m_dstPort private
Destination port.
Definition at line 1227 of file sixlowpan-header.h.
Referenced by SixLowPanUdpNhcExtension(), Deserialize(), GetDstPort(), Serialize(), and SetDstPort().
m_srcPort
uint16_t ns3::SixLowPanUdpNhcExtension::m_srcPort private
Source port.
Definition at line 1226 of file sixlowpan-header.h.
Referenced by SixLowPanUdpNhcExtension(), Deserialize(), GetSrcPort(), Serialize(), and SetSrcPort().
The documentation for this class was generated from the following files:
src/sixlowpan/model/sixlowpan-header.h
src/sixlowpan/model/sixlowpan-header.cc