ns-3: MeshTest Class Reference
MeshTest Class Reference
Mesh Device
MeshTest class.
Public Member Functions
MeshTest ()
Init test.
void Configure (int argc, char **argv)
Configure test from command line arguments.
int Run ()
Run test.
Private Member Functions
void CreateNodes ()
Create nodes and setup their mobility.
void InstallApplication ()
Install applications.
void InstallInternetStack ()
Install internet m_stack on nodes.
void Report ()
Print mesh devices diagnostics.
Private Attributes
Ipv4InterfaceContainer interfaces
Addresses of interfaces:
bool m_ascii
ASCII.
bool m_chan
channel
uint32_t m_nIfaces
number interfaces
double m_packetInterval
packet interval
uint16_t m_packetSize
packet size
bool m_pcap
PCAP.
double m_randomStart
random start
std::string m_root
root
std::string m_stack
stack
double m_step
step
double m_totalTime
total time
int m_xSize
X size.
int m_ySize
Y size.
MeshHelper mesh
MeshHelper. Report is not static methods.
NetDeviceContainer meshDevices
List of all mesh point devices.
NodeContainer nodes
List of network nodes.
Detailed Description
MeshTest class.
Definition at line 66 of file mesh.cc.
Constructor & Destructor Documentation
MeshTest()
MeshTest::MeshTest ()
Init test.
Definition at line 115 of file mesh.cc.
Member Function Documentation
Configure()
void MeshTest::Configure (int argc, char ** argv)
Configure test from command line arguments.
Parameters
argc command line argument count
argv command line arguments
Definition at line 132 of file mesh.cc.
References second::cmd, COMMANDLINE, m_ascii, m_chan, m_nIfaces, m_packetInterval, m_packetSize, m_pcap, m_randomStart, m_root, m_stack, m_step, m_totalTime, m_xSize, m_ySize, and NS_LOG_DEBUG.
CreateNodes()
void MeshTest::CreateNodes () private
Create nodes and setup their mobility.
Definition at line 159 of file mesh.cc.
References ns3::NodeContainer::Create(), ns3::YansWifiChannelHelper::Create(), ns3::AsciiTraceHelper::CreateFileStream(), ns3::AsciiTraceHelperForDevice::EnableAsciiAll(), ns3::PcapHelperForDevice::EnablePcapAll(), ns3::MeshHelper::Install(), ns3::Mac48Address::IsBroadcast(), m_ascii, m_chan, m_nIfaces, m_pcap, m_randomStart, m_root, m_stack, m_step, m_xSize, m_ySize, mesh, meshDevices, third::mobility, nodes, ns3::Seconds(), ns3::YansWifiPhyHelper::SetChannel(), ns3::MeshHelper::SetMacType(), ns3::MeshHelper::SetNumberOfInterfaces(), ns3::MeshHelper::SetSpreadInterfaceChannels(), and ns3::MeshHelper::SetStackInstaller().
Referenced by Run().
InstallApplication()
void MeshTest::InstallApplication () private
Install applications.
Definition at line 227 of file mesh.cc.
References first::clientApps, first::echoClient, first::echoServer, ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), interfaces, m_packetInterval, m_packetSize, m_totalTime, m_xSize, m_ySize, nodes, ns3::Seconds(), and first::serverApps.
Referenced by Run().
InstallInternetStack()
void MeshTest::InstallInternetStack () private
Install internet m_stack on nodes.
Definition at line 218 of file mesh.cc.
References first::address, ns3::InternetStackHelper::Install(), interfaces, meshDevices, and nodes.
Referenced by Run().
Report()
void MeshTest::Report () private
Print mesh devices diagnostics.
Definition at line 254 of file mesh.cc.
References ns3::NetDeviceContainer::Begin(), ns3::NetDeviceContainer::End(), mesh, meshDevices, sample-rng-plot::n, and ns3::MeshHelper::Report().
Referenced by Run().
Run()
int MeshTest::Run ()
Run test.
Returns
the test status
Definition at line 242 of file mesh.cc.
References CreateNodes(), InstallApplication(), InstallInternetStack(), m_totalTime, Report(), and ns3::Seconds().
Member Data Documentation
interfaces
Ipv4InterfaceContainer MeshTest::interfaces private
Addresses of interfaces:
Definition at line 102 of file mesh.cc.
Referenced by InstallApplication(), and InstallInternetStack().
m_ascii
bool MeshTest::m_ascii private
ASCII.
Definition at line 94 of file mesh.cc.
Referenced by Configure(), and CreateNodes().
m_chan
bool MeshTest::m_chan private
channel
Definition at line 92 of file mesh.cc.
Referenced by Configure(), and CreateNodes().
m_nIfaces
uint32_t MeshTest::m_nIfaces private
number interfaces
Definition at line 91 of file mesh.cc.
Referenced by Configure(), and CreateNodes().
m_packetInterval
double MeshTest::m_packetInterval private
packet interval
Definition at line 89 of file mesh.cc.
Referenced by Configure(), and InstallApplication().
m_packetSize
uint16_t MeshTest::m_packetSize private
packet size
Definition at line 90 of file mesh.cc.
Referenced by Configure(), and InstallApplication().
m_pcap
bool MeshTest::m_pcap private
PCAP.
Definition at line 93 of file mesh.cc.
Referenced by Configure(), and CreateNodes().
m_randomStart
double MeshTest::m_randomStart private
random start
Definition at line 87 of file mesh.cc.
Referenced by Configure(), and CreateNodes().
m_root
std::string MeshTest::m_root private
root
Definition at line 96 of file mesh.cc.
Referenced by Configure(), and CreateNodes().
m_stack
std::string MeshTest::m_stack private
stack
Definition at line 95 of file mesh.cc.
Referenced by Configure(), and CreateNodes().
m_step
double MeshTest::m_step private
step
Definition at line 86 of file mesh.cc.
Referenced by Configure(), and CreateNodes().
m_totalTime
double MeshTest::m_totalTime private
total time
Definition at line 88 of file mesh.cc.
Referenced by Configure(), InstallApplication(), and Run().
m_xSize
int MeshTest::m_xSize private
X size.
Definition at line 84 of file mesh.cc.
Referenced by Configure(), CreateNodes(), and InstallApplication().
m_ySize
int MeshTest::m_ySize private
Y size.
Definition at line 85 of file mesh.cc.
Referenced by Configure(), CreateNodes(), and InstallApplication().
mesh
MeshHelper MeshTest::mesh private
MeshHelper. Report is not static methods.
Definition at line 104 of file mesh.cc.
Referenced by CreateNodes(), and Report().
meshDevices
NetDeviceContainer MeshTest::meshDevices private
List of all mesh point devices.
Definition at line 100 of file mesh.cc.
Referenced by CreateNodes(), InstallInternetStack(), and Report().
nodes
NodeContainer MeshTest::nodes private
List of network nodes.
Definition at line 98 of file mesh.cc.
Referenced by CreateNodes(), InstallApplication(), and InstallInternetStack().
The documentation for this class was generated from the following file:
src/mesh/examples/mesh.cc