ns-3: ns3::PacketBurst Class Reference
ns3::PacketBurst Class Reference
this class implement a burst as a list of packets
#include "packet-burst.h"
Public Types
typedef void(* TracedCallback) (Ptr< const PacketBurst > burst)
TracedCallback signature for Ptr<PacketBurst>
Public Member Functions
PacketBurst (void)
virtual ~PacketBurst (void)
void AddPacket (Ptr< Packet > packet)
add a packet to the list of packet
std::list< Ptr< Packet > >::const_iterator Begin (void) const
Returns an iterator to the begin of the burst.
Ptr< PacketBurst > Copy (void) const
std::list< Ptr< Packet > >::const_iterator End (void) const
Returns an iterator to the end of the burst.
uint32_t GetNPackets (void) const
std::list< Ptr< Packet > > GetPackets (void) const
uint32_t GetSize (void) const
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void DoDispose (void)
Destructor implementation.
Private Attributes
std::list< Ptr< Packet > > m_packets
the list of packets in the burst
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
this class implement a burst as a list of packets
Definition at line 35 of file packet-burst.h.
Member Typedef Documentation
TracedCallback
typedef void(* ns3::PacketBurst::TracedCallback) (Ptr< const PacketBurst > burst)
TracedCallback signature for Ptr<PacketBurst>
Parameters
[in] burst The PacketBurst
Definition at line 83 of file packet-burst.h.
Constructor & Destructor Documentation
PacketBurst()
ns3::PacketBurst::PacketBurst (void)
Definition at line 44 of file packet-burst.cc.
References NS_LOG_FUNCTION.
~PacketBurst()
ns3::PacketBurst::~PacketBurst (void) virtual
Definition at line 49 of file packet-burst.cc.
References list, m_packets, and NS_LOG_FUNCTION.
Member Function Documentation
AddPacket()
void ns3::PacketBurst::AddPacket (Ptr< Packet > packet)
add a packet to the list of packet
Parameters
packet the packet to add
Definition at line 82 of file packet-burst.cc.
References m_packets, and NS_LOG_FUNCTION.
Referenced by LteDownlinkDataSinrTestCase::DoRun(), and LteUplinkDataSinrTestCase::DoRun().
Begin()
std::list< Ptr< Packet > >::const_iterator ns3::PacketBurst::Begin (void) const
Returns an iterator to the begin of the burst.
Returns
iterator to the burst list start
Definition at line 120 of file packet-burst.cc.
References m_packets, and NS_LOG_FUNCTION.
Copy()
Ptr< PacketBurst > ns3::PacketBurst::Copy (void) const
Returns
a copy the packetBurst
Definition at line 67 of file packet-burst.cc.
References ns3::Packet::Copy(), list, m_packets, and NS_LOG_FUNCTION.
DoDispose()
void ns3::PacketBurst::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 61 of file packet-burst.cc.
References m_packets, and NS_LOG_FUNCTION.
End()
std::list< Ptr< Packet > >::const_iterator ns3::PacketBurst::End (void) const
Returns an iterator to the end of the burst.
Returns
iterator to the burst list end
Definition at line 127 of file packet-burst.cc.
References m_packets, and NS_LOG_FUNCTION.
GetNPackets()
uint32_t ns3::PacketBurst::GetNPackets (void) const
Returns
the number of packet in the burst
Definition at line 99 of file packet-burst.cc.
References m_packets, and NS_LOG_FUNCTION.
GetPackets()
std::list< Ptr< Packet > > ns3::PacketBurst::GetPackets (void) const
Returns
the list of packet of this burst
Definition at line 92 of file packet-burst.cc.
References m_packets, and NS_LOG_FUNCTION.
Referenced by ns3::PcapSniffTxRxEvent().
GetSize()
uint32_t ns3::PacketBurst::GetSize (void) const
Returns
the size of the burst in byte (the size of all packets)
Definition at line 106 of file packet-burst.cc.
References ns3::Packet::GetSize(), list, m_packets, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::PacketBurst::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 34 of file packet-burst.cc.
References ns3::TypeId::SetParent().
Member Data Documentation
m_packets
std::list<Ptr<Packet> > ns3::PacketBurst::m_packets private
the list of packets in the burst
Definition at line 88 of file packet-burst.h.
Referenced by ~PacketBurst(), AddPacket(), Begin(), Copy(), DoDispose(), End(), GetNPackets(), GetPackets(), and GetSize().
The documentation for this class was generated from the following files:
src/network/utils/packet-burst.h
src/network/utils/packet-burst.cc