ns-3: Ns3TcpCwndTestCase1 Class Reference
Ns3TcpCwndTestCase1 Class Reference
Classes
class CwndEvent
Public Member Functions
Ns3TcpCwndTestCase1 ()
virtual ~Ns3TcpCwndTestCase1 ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CwndChange (uint32_t oldCwnd, uint32_t newCwnd)
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
TestVectors< CwndEvent > m_responses
bool m_writeResults
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 198 of file ns3tcp-cwnd-test-suite.cc.
Constructor & Destructor Documentation
Ns3TcpCwndTestCase1()
Ns3TcpCwndTestCase1::Ns3TcpCwndTestCase1 ()
Definition at line 219 of file ns3tcp-cwnd-test-suite.cc.
~Ns3TcpCwndTestCase1()
Ns3TcpCwndTestCase1::~Ns3TcpCwndTestCase1 () virtual
Definition at line 225 of file ns3tcp-cwnd-test-suite.cc.
Member Function Documentation
CwndChange()
void Ns3TcpCwndTestCase1::CwndChange (uint32_t oldCwnd, uint32_t newCwnd) private
Definition at line 230 of file ns3tcp-cwnd-test-suite.cc.
References Ns3TcpCwndTestCase1::CwndEvent::m_oldCwnd, m_responses, ns3::Now(), NS_LOG_DEBUG, and aloha::S.
Referenced by DoRun().
DoRun()
void Ns3TcpCwndTestCase1::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 243 of file ns3tcp-cwnd-test-suite.cc.
References first::address, CwndChange(), first::devices, ns3::PacketSinkHelper::Install(), first::interfaces, Ns3TcpCwndTestCase1::CwndEvent::m_newCwnd, Ns3TcpCwndTestCase1::CwndEvent::m_oldCwnd, m_responses, m_writeResults, ns3::MakeCallback(), first::nodes, NS_LOG_DEBUG, NS_TEST_ASSERT_MSG_EQ, first::pointToPoint, ns3::Seconds(), ns3::Application::SetStartTime(), ns3::Application::SetStopTime(), SimpleSource::Setup(), first::stack, ns3::ApplicationContainer::Start(), ns3::ApplicationContainer::Stop(), and ns3::ObjectBase::TraceConnectWithoutContext().
Member Data Documentation
m_responses
TestVectors<CwndEvent> Ns3TcpCwndTestCase1::m_responses private
Definition at line 214 of file ns3tcp-cwnd-test-suite.cc.
Referenced by CwndChange(), and DoRun().
m_writeResults
bool Ns3TcpCwndTestCase1::m_writeResults private
Definition at line 206 of file ns3tcp-cwnd-test-suite.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/test/ns3tcp/ns3tcp-cwnd-test-suite.cc