ns-3: LenaRrFfMacSchedulerTestCase Class Reference
LenaRrFfMacSchedulerTestCase Class Reference
LTE Models » lte module tests | Test suites
This system test program creates different test cases with a single eNB and This system test program creates different test cases with a single eNB and several UEs, all having the same Radio Bearer specification. In each test case, the UEs see the same SINR from the eNB; different test cases are implemented obtained by using different SINR values and different numbers of UEs. The test consists on checking that the obtained throughput performance is equal among users and matches a reference throughput value within a given tolerance.
#include "lte-test-rr-ff-mac-scheduler.h"
Public Member Functions
LenaRrFfMacSchedulerTestCase (uint16_t nUser, double dist, double thrRefDl, double thrRefUl, bool errorModelEnabled)
Constructor.
virtual ~LenaRrFfMacSchedulerTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Static Private Member Functions
static std::string BuildNameString (uint16_t nUser, double dist)
Builds the test name string based on provided parameter values.
Private Attributes
double m_dist
the distance between nodes
bool m_errorModelEnabled
indicates whether the error model is enabled
uint16_t m_nUser
number of UE nodes
double m_thrRefDl
the DL throughput reference
double m_thrRefUl
the UL throughput reference
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
This system test program creates different test cases with a single eNB and This system test program creates different test cases with a single eNB and several UEs, all having the same Radio Bearer specification. In each test case, the UEs see the same SINR from the eNB; different test cases are implemented obtained by using different SINR values and different numbers of UEs. The test consists on checking that the obtained throughput performance is equal among users and matches a reference throughput value within a given tolerance.
Definition at line 44 of file lte-test-rr-ff-mac-scheduler.h.
Constructor & Destructor Documentation
LenaRrFfMacSchedulerTestCase()
LenaRrFfMacSchedulerTestCase::LenaRrFfMacSchedulerTestCase (uint16_t nUser, double dist, double thrRefDl, double thrRefUl, bool errorModelEnabled)
Constructor.
Parameters
nUser the number of UE nodes
dist the distance between nodes
thrRefDl the DL throughput reference
thrRefUl the UL throughput reference
errorModelEnabled if true the error model is enabled
Definition at line 166 of file lte-test-rr-ff-mac-scheduler.cc.
~LenaRrFfMacSchedulerTestCase()
LenaRrFfMacSchedulerTestCase::~LenaRrFfMacSchedulerTestCase () virtual
Definition at line 176 of file lte-test-rr-ff-mac-scheduler.cc.
Member Function Documentation
BuildNameString()
std::string LenaRrFfMacSchedulerTestCase::BuildNameString (uint16_t nUser, double dist) static private
Builds the test name string based on provided parameter values.
Parameters
nUser the number of UE nodes
dist the distance between UE nodes and eNodeB
Returns
the name string
Definition at line 159 of file lte-test-rr-ff-mac-scheduler.cc.
DoRun()
void LenaRrFfMacSchedulerTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Initialize Simulation Scenario: 1 eNB and m_nUser UEs
Check that the assignment is done in a RR fashion
Implements ns3::TestCase.
Definition at line 181 of file lte-test-rr-ff-mac-scheduler.cc.
References ns3::LteHelper::ActivateDataRadioBearer(), ns3::LteHelper::Attach(), ns3::NodeContainer::Create(), ns3::TestCase::CreateTempDirFilename(), ns3::LteHelper::EnableRlcTraces(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::RadioBearerStatsCalculator::GetDlRxData(), ns3::Object::GetObject(), ns3::LteEnbNetDevice::GetPhy(), ns3::LteUeNetDevice::GetPhy(), ns3::LteHelper::GetRlcStats(), ns3::RadioBearerStatsCalculator::GetUlRxData(), ns3::RadioBearerStatsCalculator::GetUlTxData(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), m_dist, m_errorModelEnabled, m_nUser, m_thrRefDl, m_thrRefUl, third::mobility, NS_LOG_FUNCTION, NS_LOG_INFO, NS_TEST_ASSERT_MSG_EQ_TOL, ns3::Seconds(), ns3::ObjectBase::SetAttribute(), ns3::Config::SetDefault(), ns3::MobilityModel::SetPosition(), ns3::LteHelper::SetSchedulerAttribute(), and ns3::LteHelper::SetSchedulerType().
Member Data Documentation
m_dist
double LenaRrFfMacSchedulerTestCase::m_dist private
the distance between nodes
Definition at line 69 of file lte-test-rr-ff-mac-scheduler.h.
Referenced by DoRun().
m_errorModelEnabled
bool LenaRrFfMacSchedulerTestCase::m_errorModelEnabled private
indicates whether the error model is enabled
Definition at line 72 of file lte-test-rr-ff-mac-scheduler.h.
Referenced by DoRun().
m_nUser
uint16_t LenaRrFfMacSchedulerTestCase::m_nUser private
number of UE nodes
Definition at line 68 of file lte-test-rr-ff-mac-scheduler.h.
Referenced by DoRun().
m_thrRefDl
double LenaRrFfMacSchedulerTestCase::m_thrRefDl private
the DL throughput reference
Definition at line 70 of file lte-test-rr-ff-mac-scheduler.h.
Referenced by DoRun().
m_thrRefUl
double LenaRrFfMacSchedulerTestCase::m_thrRefUl private
the UL throughput reference
Definition at line 71 of file lte-test-rr-ff-mac-scheduler.h.
Referenced by DoRun().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-rr-ff-mac-scheduler.h
src/lte/test/lte-test-rr-ff-mac-scheduler.cc