ns-3: ns3::SixLowPanNhcExtension Class Reference
ns3::SixLowPanNhcExtension Class Reference
6LoWPAN
LOWPAN_NHC Extension Header Encoding - see RFC 6282.
#include "sixlowpan-header.h"
Public Types
enum Eid_e {
EID_HOPBYHOP_OPTIONS_H = 0, EID_ROUTING_H, EID_FRAGMENTATION_H, EID_DESTINATION_OPTIONS_H,
EID_MOBILITY_H, EID_IPv6_H = 7
}
EID: IPv6 Extension Header ID.
Public Member Functions
SixLowPanNhcExtension (void)
uint32_t CopyBlob (uint8_t *blob, uint32_t size) const
Get the option header data blob.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
Eid_e GetEid (void) const
Get the Extension Header Type.
virtual TypeId GetInstanceTypeId (void) const
Return the instance type identifier.
uint8_t GetNextHeader (void) const
Get the Next Header field value.
bool GetNh (void) const
Get the Next Header field value.
virtual SixLowPanDispatch::NhcDispatch_e GetNhcDispatchType (void) const
Get the NhcDispatch type.
virtual uint32_t GetSerializedSize (void) const
Get the serialized size of the packet.
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetBlob (const uint8_t *blob, uint32_t size)
Set the option header data blob.
void SetEid (Eid_e extensionHeaderType)
Set the Extension Header Type.
void SetNextHeader (uint8_t nextHeader)
Set the Next Header field values.
void SetNh (bool nhField)
Set the NH field values.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_nhcBlob [256]
NHC compressed header.
uint8_t m_nhcBlobLength
Length of the NHC compressed header.
uint8_t m_nhcExtensionHeader
NHC extension header type.
uint8_t m_nhcNextHeader
Next header.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
LOWPAN_NHC Extension Header Encoding - see RFC 6282.
   0   1   2   3   4   5   6   7
 +---+---+---+---+---+---+---+---+
 | 1 | 1 | 1 | 0 |    EID    |NH |
 +---+---+---+---+---+---+---+---+
Definition at line 958 of file sixlowpan-header.h.
Member Enumeration Documentation
Eid_e
enum ns3::SixLowPanNhcExtension::Eid_e
EID: IPv6 Extension Header ID.
EID: IPv6 Extension Header ID: 0: IPv6 Hop-by-Hop Options Header [RFC 2460] 1: IPv6 Routing Header [RFC 2460] 2: IPv6 Fragment Header [RFC 2460] 3: IPv6 Destination Options Header [RFC 2460] 4: IPv6 Mobility Header [RFC 6275] 5: Reserved 6: Reserved 7: IPv6 Header
Enumerator
EID_HOPBYHOP_OPTIONS_H
EID_ROUTING_H
EID_FRAGMENTATION_H
EID_DESTINATION_OPTIONS_H
EID_MOBILITY_H
EID_IPv6_H
Definition at line 974 of file sixlowpan-header.h.
Constructor & Destructor Documentation
SixLowPanNhcExtension()
ns3::SixLowPanNhcExtension::SixLowPanNhcExtension (void)
Definition at line 1490 of file sixlowpan-header.cc.
References m_nhcBlobLength, m_nhcExtensionHeader, and m_nhcNextHeader.
Member Function Documentation
CopyBlob()
uint32_t ns3::SixLowPanNhcExtension::CopyBlob (uint8_t * blob, uint32_t size) const
Get the option header data blob.
Parameters
[in] blob A buffer to copy the blob data into.
[in] size The size of the buffer.
Returns
The length of the copied data.
Definition at line 1599 of file sixlowpan-header.cc.
References m_nhcBlob, m_nhcBlobLength, and NS_ASSERT_MSG().
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanNhc().
Deserialize()
uint32_t ns3::SixLowPanNhcExtension::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
[in] start Buffer iterator.
Returns
Size of the packet.
Implements ns3::Header.
Definition at line 1539 of file sixlowpan-header.cc.
References GetNh(), GetSerializedSize(), m_nhcBlob, m_nhcBlobLength, m_nhcExtensionHeader, m_nhcNextHeader, ns3::Buffer::Iterator::Read(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetEid()
SixLowPanNhcExtension::Eid_e ns3::SixLowPanNhcExtension::GetEid (void) const
Get the Extension Header Type.
Returns
The Extension Header Type.
Definition at line 1565 of file sixlowpan-header.cc.
References m_nhcExtensionHeader.
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanNhc().
GetInstanceTypeId()
TypeId ns3::SixLowPanNhcExtension::GetInstanceTypeId (void) const virtual
Return the instance type identifier.
Returns
Instance type ID.
Implements ns3::ObjectBase.
Definition at line 1507 of file sixlowpan-header.cc.
References GetTypeId().
GetNextHeader()
uint8_t ns3::SixLowPanNhcExtension::GetNextHeader (void) const
Get the Next Header field value.
Returns
The Next Header field value.
Definition at line 1575 of file sixlowpan-header.cc.
References m_nhcNextHeader.
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanNhc().
GetNh()
bool ns3::SixLowPanNhcExtension::GetNh (void) const
Get the Next Header field value.
Returns
The NH field value.
Definition at line 1586 of file sixlowpan-header.cc.
References m_nhcExtensionHeader.
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanNhc(), Deserialize(), GetSerializedSize(), and Serialize().
GetNhcDispatchType()
SixLowPanDispatch::NhcDispatch_e ns3::SixLowPanNhcExtension::GetNhcDispatchType (void) const virtual
Get the NhcDispatch type.
Returns
The NhcDispatch type.
Definition at line 1554 of file sixlowpan-header.cc.
References ns3::SixLowPanDispatch::LOWPAN_NHC.
GetSerializedSize()
uint32_t ns3::SixLowPanNhcExtension::GetSerializedSize (void) const virtual
Get the serialized size of the packet.
Returns
Size.
Implements ns3::Header.
Definition at line 1517 of file sixlowpan-header.cc.
References GetNh(), and m_nhcBlobLength.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanNhc(), Deserialize(), and Print().
GetTypeId()
TypeId ns3::SixLowPanNhcExtension::GetTypeId (void) static
Get the type ID.
Returns
The object TypeId.
Definition at line 1498 of file sixlowpan-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::SixLowPanNhcExtension::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 1512 of file sixlowpan-header.cc.
References GetSerializedSize(), and m_nhcExtensionHeader.
Referenced by ns3::operator<<().
Serialize()
void ns3::SixLowPanNhcExtension::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
[in] start Buffer iterator.
Implements ns3::Header.
Definition at line 1527 of file sixlowpan-header.cc.
References GetNh(), m_nhcBlob, m_nhcBlobLength, m_nhcExtensionHeader, m_nhcNextHeader, visualizer.core::start(), ns3::Buffer::Iterator::Write(), and ns3::Buffer::Iterator::WriteU8().
SetBlob()
void ns3::SixLowPanNhcExtension::SetBlob (const uint8_t * blob, uint32_t size)
Set the option header data blob.
Parameters
[in] blob A buffer holding the blob data.
[in] size The data blob size.
Definition at line 1591 of file sixlowpan-header.cc.
References m_nhcBlob, m_nhcBlobLength, and NS_ASSERT_MSG().
Referenced by ns3::SixLowPanNetDevice::CompressLowPanNhc().
SetEid()
void ns3::SixLowPanNhcExtension::SetEid (Eid_e extensionHeaderType)
Set the Extension Header Type.
Parameters
[in] extensionHeaderType The Extension Header Type.
Definition at line 1559 of file sixlowpan-header.cc.
References m_nhcExtensionHeader.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanNhc().
SetNextHeader()
void ns3::SixLowPanNhcExtension::SetNextHeader (uint8_t nextHeader)
Set the Next Header field values.
Parameters
[in] nextHeader The Next Header field value.
Definition at line 1570 of file sixlowpan-header.cc.
References m_nhcNextHeader.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanNhc().
SetNh()
void ns3::SixLowPanNhcExtension::SetNh (bool nhField)
Set the NH field values.
Parameters
[in] nhField The NH field value.
Definition at line 1580 of file sixlowpan-header.cc.
References m_nhcExtensionHeader.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanNhc().
Member Data Documentation
m_nhcBlob
uint8_t ns3::SixLowPanNhcExtension::m_nhcBlob[256] private
NHC compressed header.
Definition at line 1080 of file sixlowpan-header.h.
Referenced by CopyBlob(), Deserialize(), Serialize(), and SetBlob().
m_nhcBlobLength
uint8_t ns3::SixLowPanNhcExtension::m_nhcBlobLength private
Length of the NHC compressed header.
Definition at line 1079 of file sixlowpan-header.h.
Referenced by SixLowPanNhcExtension(), CopyBlob(), Deserialize(), GetSerializedSize(), Serialize(), and SetBlob().
m_nhcExtensionHeader
uint8_t ns3::SixLowPanNhcExtension::m_nhcExtensionHeader private
NHC extension header type.
Definition at line 1077 of file sixlowpan-header.h.
Referenced by SixLowPanNhcExtension(), Deserialize(), GetEid(), GetNh(), Print(), Serialize(), SetEid(), and SetNh().
m_nhcNextHeader
uint8_t ns3::SixLowPanNhcExtension::m_nhcNextHeader private
Next header.
Definition at line 1078 of file sixlowpan-header.h.
Referenced by SixLowPanNhcExtension(), Deserialize(), GetNextHeader(), Serialize(), and SetNextHeader().
The documentation for this class was generated from the following files:
src/sixlowpan/model/sixlowpan-header.h
src/sixlowpan/model/sixlowpan-header.cc