ns-3: ns3::QueueBase Class Reference
ns3::QueueBase Class Reference
Network » Queue
Abstract base class for packet Queues.
#include "queue.h"
Public Member Functions
QueueBase ()
virtual ~QueueBase ()
QueueSize GetCurrentSize (void) const
QueueSize GetMaxSize (void) const
uint32_t GetNBytes (void) const
uint32_t GetNPackets (void) const
uint32_t GetTotalDroppedBytes (void) const
uint32_t GetTotalDroppedBytesAfterDequeue (void) const
uint32_t GetTotalDroppedBytesBeforeEnqueue (void) const
uint32_t GetTotalDroppedPackets (void) const
uint32_t GetTotalDroppedPacketsAfterDequeue (void) const
uint32_t GetTotalDroppedPacketsBeforeEnqueue (void) const
uint32_t GetTotalReceivedBytes (void) const
uint32_t GetTotalReceivedPackets (void) const
bool IsEmpty (void) const
void ResetStatistics (void)
Resets the counts for dropped packets, dropped bytes, received packets, and received bytes.
void SetMaxSize (QueueSize size)
Set the maximum size of this queue.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static void AppendItemTypeIfNotPresent (std::string &typeId, const std::string &itemType)
Append the item type to the provided type ID if the latter does not end with '>'.
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
QueueSize m_maxSize
max queue size
TracedValue< uint32_t > m_nBytes
Number of bytes in the queue.
TracedValue< uint32_t > m_nPackets
Number of packets in the queue.
uint32_t m_nTotalDroppedBytes
Total dropped bytes.
uint32_t m_nTotalDroppedBytesAfterDequeue
Total dropped bytes after dequeue.
uint32_t m_nTotalDroppedBytesBeforeEnqueue
Total dropped bytes before enqueue.
uint32_t m_nTotalDroppedPackets
Total dropped packets.
uint32_t m_nTotalDroppedPacketsAfterDequeue
Total dropped packets after dequeue.
uint32_t m_nTotalDroppedPacketsBeforeEnqueue
Total dropped packets before enqueue.
uint32_t m_nTotalReceivedBytes
Total received bytes.
uint32_t m_nTotalReceivedPackets
Total received packets.
Friends
template<typename Item >
class Queue
Friend class.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Abstract base class for packet Queues.
This class defines the subset of the base APIs for packet queues in the ns-3 system that is independent of the type of enqueued objects
Definition at line 52 of file queue.h.
Constructor & Destructor Documentation
QueueBase()
ns3::QueueBase::QueueBase ()
Definition at line 51 of file queue.cc.
References m_maxSize, max, NS_LOG_FUNCTION, and ns3::PACKETS.
~QueueBase()
ns3::QueueBase::~QueueBase () virtual
Definition at line 67 of file queue.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AppendItemTypeIfNotPresent()
void ns3::QueueBase::AppendItemTypeIfNotPresent (std::string & typeId, const std::string & itemType) static
Append the item type to the provided type ID if the latter does not end with '>'.
Parameters
typeId the type ID
itemType the item type
This method is meant to be invoked by helpers to save users from specifying the type of items stored in a queue. For instance, PointToPointHelper::SetQueue calls
QueueBase::AppendItemTypeIfNotPresent (type, "Packet");
where type specifies the queue type (e.g., "ns3::DropTailQueue"). This allows users to call SetQueue ("ns3::DropTailQueue") instead of SetQueue ("ns3::DropTailQueue<Packet>")
Definition at line 73 of file queue.cc.
Referenced by ns3::TrafficControlHelper::AddInternalQueues(), ns3::CsmaHelper::SetQueue(), ns3::SimpleNetDeviceHelper::SetQueue(), and ns3::PointToPointHelper::SetQueue().
GetCurrentSize()
QueueSize ns3::QueueBase::GetCurrentSize (void) const
Returns
The current size of the Queue in terms of packets, if the maximum size is specified in packets, or bytes, otherwise
Definition at line 106 of file queue.cc.
References ns3::BYTES, ns3::QueueSize::GetUnit(), m_maxSize, m_nBytes, m_nPackets, NS_ABORT_MSG, NS_LOG_FUNCTION, and ns3::PACKETS.
Referenced by SetMaxSize().
GetMaxSize()
QueueSize ns3::QueueBase::GetMaxSize (void) const
Returns
the maximum size of this queue
Definition at line 217 of file queue.cc.
References m_maxSize, and NS_LOG_FUNCTION.
Referenced by ns3::DropTailQueue< Item >::GetTypeId(), and ns3::WifiMacQueue::GetTypeId().
GetNBytes()
uint32_t ns3::QueueBase::GetNBytes (void) const
Returns
The number of bytes currently occupied by the packets in the Queue
Definition at line 98 of file queue.cc.
References m_nBytes, NS_LOG_FUNCTION, and NS_LOG_LOGIC().
Referenced by ns3::WifiMacQueue::GetNBytes().
GetNPackets()
uint32_t ns3::QueueBase::GetNPackets (void) const
Returns
The number of packets currently stored in the Queue
Definition at line 90 of file queue.cc.
References m_nPackets, NS_LOG_FUNCTION, and NS_LOG_LOGIC().
Referenced by ns3::WifiMacQueue::GetNPackets(), and ns3::WifiMacQueue::Insert().
GetTotalDroppedBytes()
uint32_t ns3::QueueBase::GetTotalDroppedBytes (void) const
Returns
The total number of bytes dropped by this Queue since the simulation began, or since ResetStatistics was called, according to whichever happened more recently
Definition at line 138 of file queue.cc.
References m_nTotalDroppedBytes, NS_LOG_FUNCTION, and NS_LOG_LOGIC().
GetTotalDroppedBytesAfterDequeue()
uint32_t ns3::QueueBase::GetTotalDroppedBytesAfterDequeue (void) const
Returns
The total number of bytes dropped after dequeue by this Queue since the simulation began, or since ResetStatistics was called, according to whichever happened more recently
Definition at line 154 of file queue.cc.
References m_nTotalDroppedBytesAfterDequeue, NS_LOG_FUNCTION, and NS_LOG_LOGIC().
GetTotalDroppedBytesBeforeEnqueue()
uint32_t ns3::QueueBase::GetTotalDroppedBytesBeforeEnqueue (void) const
Returns
The total number of bytes dropped before enqueue by this Queue since the simulation began, or since ResetStatistics was called, according to whichever happened more recently
Definition at line 146 of file queue.cc.
References m_nTotalDroppedBytesBeforeEnqueue, NS_LOG_FUNCTION, and NS_LOG_LOGIC().
GetTotalDroppedPackets()
uint32_t ns3::QueueBase::GetTotalDroppedPackets (void) const
Returns
The total number of packets dropped by this Queue since the simulation began, or since ResetStatistics was called, according to whichever happened more recently
Definition at line 162 of file queue.cc.
References m_nTotalDroppedPackets, NS_LOG_FUNCTION, and NS_LOG_LOGIC().
GetTotalDroppedPacketsAfterDequeue()
uint32_t ns3::QueueBase::GetTotalDroppedPacketsAfterDequeue (void) const
Returns
The total number of packets dropped after dequeue by this Queue since the simulation began, or since ResetStatistics was called, according to whichever happened more recently
Definition at line 178 of file queue.cc.
References m_nTotalDroppedPacketsAfterDequeue, NS_LOG_FUNCTION, and NS_LOG_LOGIC().
GetTotalDroppedPacketsBeforeEnqueue()
uint32_t ns3::QueueBase::GetTotalDroppedPacketsBeforeEnqueue (void) const
Returns
The total number of packets dropped before enqueue by this Queue since the simulation began, or since ResetStatistics was called, according to whichever happened more recently
Definition at line 170 of file queue.cc.
References m_nTotalDroppedPacketsBeforeEnqueue, NS_LOG_FUNCTION, and NS_LOG_LOGIC().
GetTotalReceivedBytes()
uint32_t ns3::QueueBase::GetTotalReceivedBytes (void) const
Returns
The total number of bytes received by this Queue since the simulation began, or since ResetStatistics was called, according to whichever happened more recently
Definition at line 122 of file queue.cc.
References m_nTotalReceivedBytes, NS_LOG_FUNCTION, and NS_LOG_LOGIC().
GetTotalReceivedPackets()
uint32_t ns3::QueueBase::GetTotalReceivedPackets (void) const
Returns
The total number of packets received by this Queue since the simulation began, or since ResetStatistics was called, according to whichever happened more recently
Definition at line 130 of file queue.cc.
References m_nTotalReceivedPackets, NS_LOG_FUNCTION, and NS_LOG_LOGIC().
GetTypeId()
TypeId ns3::QueueBase::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 34 of file queue.cc.
References m_nBytes, m_nPackets, ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
IsEmpty()
bool ns3::QueueBase::IsEmpty (void) const
Returns
true if the queue is empty; false otherwise
Definition at line 82 of file queue.cc.
References ns3::TracedValue< T >::Get(), m_nPackets, NS_LOG_FUNCTION, and NS_LOG_LOGIC().
ResetStatistics()
void ns3::QueueBase::ResetStatistics (void)
Resets the counts for dropped packets, dropped bytes, received packets, and received bytes.
Definition at line 186 of file queue.cc.
References m_nTotalDroppedBytes, m_nTotalDroppedBytesAfterDequeue, m_nTotalDroppedBytesBeforeEnqueue, m_nTotalDroppedPackets, m_nTotalDroppedPacketsAfterDequeue, m_nTotalDroppedPacketsBeforeEnqueue, m_nTotalReceivedBytes, m_nTotalReceivedPackets, and NS_LOG_FUNCTION.
SetMaxSize()
void ns3::QueueBase::SetMaxSize (QueueSize size)
Set the maximum size of this queue.
Trying to set a null size has no effect.
Parameters
size the maximum size
Definition at line 200 of file queue.cc.
References GetCurrentSize(), ns3::QueueSize::GetValue(), m_maxSize, NS_ABORT_MSG_IF, and NS_LOG_FUNCTION.
Referenced by ns3::DropTailQueue< Item >::GetTypeId(), and ns3::WifiMacQueue::GetTypeId().
Friends And Related Function Documentation
Queue
template<typename Item > friend class Queue friend
Friend class.
Definition at line 222 of file queue.h.
Member Data Documentation
m_maxSize
QueueSize ns3::QueueBase::m_maxSize private
max queue size
Definition at line 218 of file queue.h.
Referenced by QueueBase(), GetCurrentSize(), GetMaxSize(), and SetMaxSize().
m_nBytes
TracedValue<uint32_t> ns3::QueueBase::m_nBytes private
Number of bytes in the queue.
Definition at line 207 of file queue.h.
Referenced by GetCurrentSize(), GetNBytes(), and GetTypeId().
m_nPackets
TracedValue<uint32_t> ns3::QueueBase::m_nPackets private
Number of packets in the queue.
Definition at line 209 of file queue.h.
Referenced by GetCurrentSize(), GetNPackets(), GetTypeId(), and IsEmpty().
m_nTotalDroppedBytes
uint32_t ns3::QueueBase::m_nTotalDroppedBytes private
Total dropped bytes.
Definition at line 211 of file queue.h.
Referenced by GetTotalDroppedBytes(), and ResetStatistics().
m_nTotalDroppedBytesAfterDequeue
uint32_t ns3::QueueBase::m_nTotalDroppedBytesAfterDequeue private
Total dropped bytes after dequeue.
Definition at line 213 of file queue.h.
Referenced by GetTotalDroppedBytesAfterDequeue(), and ResetStatistics().
m_nTotalDroppedBytesBeforeEnqueue
uint32_t ns3::QueueBase::m_nTotalDroppedBytesBeforeEnqueue private
Total dropped bytes before enqueue.
Definition at line 212 of file queue.h.
Referenced by GetTotalDroppedBytesBeforeEnqueue(), and ResetStatistics().
m_nTotalDroppedPackets
uint32_t ns3::QueueBase::m_nTotalDroppedPackets private
Total dropped packets.
Definition at line 214 of file queue.h.
Referenced by GetTotalDroppedPackets(), and ResetStatistics().
m_nTotalDroppedPacketsAfterDequeue
uint32_t ns3::QueueBase::m_nTotalDroppedPacketsAfterDequeue private
Total dropped packets after dequeue.
Definition at line 216 of file queue.h.
Referenced by GetTotalDroppedPacketsAfterDequeue(), and ResetStatistics().
m_nTotalDroppedPacketsBeforeEnqueue
uint32_t ns3::QueueBase::m_nTotalDroppedPacketsBeforeEnqueue private
Total dropped packets before enqueue.
Definition at line 215 of file queue.h.
Referenced by GetTotalDroppedPacketsBeforeEnqueue(), and ResetStatistics().
m_nTotalReceivedBytes
uint32_t ns3::QueueBase::m_nTotalReceivedBytes private
Total received bytes.
Definition at line 208 of file queue.h.
Referenced by GetTotalReceivedBytes(), and ResetStatistics().
m_nTotalReceivedPackets
uint32_t ns3::QueueBase::m_nTotalReceivedPackets private
Total received packets.
Definition at line 210 of file queue.h.
Referenced by GetTotalReceivedPackets(), and ResetStatistics().
The documentation for this class was generated from the following files:
src/network/utils/queue.h
src/network/utils/queue.cc