ns-3: Udp6SocketLoopbackTest Class Reference
Udp6SocketLoopbackTest Class Reference
Internet » internet module tests | Test suites
UDP Socket Loopback over IPv6 Test.
Public Member Functions
Udp6SocketLoopbackTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
void ReceivePkt (Ptr< Socket > socket)
Receive a packet.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Public Attributes
Ptr< Packet > m_receivedPacket
Received packet.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
UDP Socket Loopback over IPv6 Test.
Definition at line 120 of file udp-test.cc.
Constructor & Destructor Documentation
Udp6SocketLoopbackTest()
Udp6SocketLoopbackTest::Udp6SocketLoopbackTest ()
Definition at line 134 of file udp-test.cc.
Member Function Documentation
DoRun()
void Udp6SocketLoopbackTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 151 of file udp-test.cc.
References ns3::Socket::Bind(), ns3::SocketFactory::CreateSocket(), ns3::Object::GetObject(), ns3::Packet::GetSize(), ns3::InternetStackHelper::Install(), m_receivedPacket, ns3::MakeCallback(), NS_TEST_EXPECT_MSG_EQ, ReceivePkt(), and ns3::Socket::SendTo().
ReceivePkt()
void Udp6SocketLoopbackTest::ReceivePkt (Ptr< Socket > socket)
Receive a packet.
Parameters
socket The receiving socket.
Definition at line 139 of file udp-test.cc.
References ns3::Socket::GetRxAvailable(), ns3::Packet::GetSize(), m_receivedPacket, max, NS_ASSERT, and ns3::Socket::Recv().
Referenced by DoRun().
Member Data Documentation
m_receivedPacket
Ptr<Packet> Udp6SocketLoopbackTest::m_receivedPacket
Received packet.
Definition at line 131 of file udp-test.cc.
Referenced by DoRun(), and ReceivePkt().
The documentation for this class was generated from the following file:
src/internet/test/udp-test.cc