ns-3: ns3::SequenceNumber10 Class Reference
ns3::SequenceNumber10 Class Reference
SequenceNumber10 class.
#include "lte-rlc-sequence-number.h"
Public Member Functions
SequenceNumber10 ()
SequenceNumber10 (SequenceNumber10 const &value)
Constructor.
SequenceNumber10 (uint16_t value)
Constructor.
uint16_t GetValue () const
Extracts the numeric value of the sequence number.
bool operator!= (const SequenceNumber10 &other) const
inequality operator
SequenceNumber10 operator+ (uint16_t delta) const
addition operator
SequenceNumber10 operator++ (int)
postfix ++ operator
uint16_t operator- (const SequenceNumber10 &other) const
subtraction operator
SequenceNumber10 operator- (uint16_t delta) const
subtraction operator
bool operator< (const SequenceNumber10 &other) const
less than operator
bool operator<= (const SequenceNumber10 &other) const
less than or equal operator
SequenceNumber10 & operator= (uint16_t value)
Assignment operator.
bool operator== (const SequenceNumber10 &other) const
equality operator
bool operator> (const SequenceNumber10 &other) const
greater than operator
bool operator>= (const SequenceNumber10 &other) const
greater than or equal operator
void SetModulusBase (SequenceNumber10 modulusBase)
Set modulus base.
void SetModulusBase (uint16_t modulusBase)
Set modulus base.
Private Attributes
uint16_t m_modulusBase
the modulus base
uint16_t m_value
the value
Friends
std::ostream & operator<< (std::ostream &os, const SequenceNumber10 &val)
Ostream output function.
Detailed Description
SequenceNumber10 class.
Definition at line 36 of file lte-rlc-sequence-number.h.
Constructor & Destructor Documentation
SequenceNumber10() [1/3]
ns3::SequenceNumber10::SequenceNumber10 () inline
Definition at line 39 of file lte-rlc-sequence-number.h.
SequenceNumber10() [2/3]
ns3::SequenceNumber10::SequenceNumber10 (uint16_t value) inline explicit
Constructor.
Parameters
value the value
Definition at line 49 of file lte-rlc-sequence-number.h.
SequenceNumber10() [3/3]
ns3::SequenceNumber10::SequenceNumber10 (SequenceNumber10 const & value) inline
Constructor.
Parameters
value the value
Definition at line 59 of file lte-rlc-sequence-number.h.
Member Function Documentation
GetValue()
uint16_t ns3::SequenceNumber10::GetValue () const inline
Extracts the numeric value of the sequence number.
Returns
the sequence number value
Definition at line 81 of file lte-rlc-sequence-number.h.
References m_value.
Referenced by ns3::LteRlcAm::DoNotifyTxOpportunity(), ns3::LteRlcAm::DoReceivePdu(), ns3::LteRlcUm::DoReceivePdu(), ns3::LteRlcAm::DoReportBufferStatus(), ns3::LteRlcAm::ExpirePollRetransmitTimer(), ns3::LteRlcAm::ExpireReorderingTimer(), ns3::LteRlcUm::ExpireReorderingTimer(), ns3::LteRlcAmHeader::IsNackPresent(), ns3::LteRlcUm::ReassembleSnInterval(), ns3::LteRlcAmHeader::Serialize(), and ns3::LteRlcHeader::Serialize().
operator!=()
bool ns3::SequenceNumber10::operator!= (const SequenceNumber10 & other) const inline
inequality operator
Parameters
other the object to compare
Returns
true if not equal
Definition at line 179 of file lte-rlc-sequence-number.h.
References m_value.
operator+()
SequenceNumber10 ns3::SequenceNumber10::operator+ (uint16_t delta) const inline
addition operator
Parameters
delta the amount to add
Returns
SequenceNumber10
Definition at line 121 of file lte-rlc-sequence-number.h.
References m_modulusBase, m_value, and SetModulusBase().
operator++()
SequenceNumber10 ns3::SequenceNumber10::operator++ (int) inline
postfix ++ operator
Returns
SequenceNumber10
Definition at line 108 of file lte-rlc-sequence-number.h.
References m_modulusBase, m_value, and SetModulusBase().
operator-() [1/2]
uint16_t ns3::SequenceNumber10::operator- (const SequenceNumber10 & other) const inline
subtraction operator
Parameters
other the amount to subtract
Returns
SequenceNumber10
Definition at line 145 of file lte-rlc-sequence-number.h.
References m_value.
operator-() [2/2]
SequenceNumber10 ns3::SequenceNumber10::operator- (uint16_t delta) const inline
subtraction operator
Parameters
delta the amount to subtract
Returns
SequenceNumber10
Definition at line 133 of file lte-rlc-sequence-number.h.
References m_modulusBase, m_value, and SetModulusBase().
operator<()
bool ns3::SequenceNumber10::operator< (const SequenceNumber10 & other) const inline
less than operator
Parameters
other the object to compare
Returns
true if less than
Definition at line 209 of file lte-rlc-sequence-number.h.
References m_value, and operator>().
operator<=()
bool ns3::SequenceNumber10::operator<= (const SequenceNumber10 & other) const inline
less than or equal operator
Parameters
other the object to compare
Returns
true if less than or equal
Definition at line 189 of file lte-rlc-sequence-number.h.
operator=()
SequenceNumber10& ns3::SequenceNumber10::operator= (uint16_t value) inline
Assignment operator.
Parameters
value the value
Returns
SequenceNumber10
Definition at line 70 of file lte-rlc-sequence-number.h.
References m_value.
operator==()
bool ns3::SequenceNumber10::operator== (const SequenceNumber10 & other) const inline
equality operator
Parameters
other the object to compare
Returns
true if equal
Definition at line 169 of file lte-rlc-sequence-number.h.
References m_value.
operator>()
bool ns3::SequenceNumber10::operator> (const SequenceNumber10 & other) const inline
greater than operator
Parameters
other the object to compare
Returns
true if greater than
Definition at line 156 of file lte-rlc-sequence-number.h.
References m_modulusBase, m_value, and NS_ASSERT.
Referenced by operator<().
operator>=()
bool ns3::SequenceNumber10::operator>= (const SequenceNumber10 & other) const inline
greater than or equal operator
Parameters
other the object to compare
Returns
true if greater than or equal
Definition at line 199 of file lte-rlc-sequence-number.h.
SetModulusBase() [1/2]
void ns3::SequenceNumber10::SetModulusBase (SequenceNumber10 modulusBase) inline
Set modulus base.
Parameters
modulusBase the modulus
Definition at line 90 of file lte-rlc-sequence-number.h.
References m_modulusBase, and m_value.
Referenced by ns3::LteRlcAm::DoNotifyTxOpportunity(), ns3::LteRlcAm::DoReceivePdu(), ns3::LteRlcUm::DoReceivePdu(), ns3::LteRlcAm::IsInsideReceivingWindow(), ns3::LteRlcUm::IsInsideReorderingWindow(), operator+(), operator++(), and operator-().
SetModulusBase() [2/2]
void ns3::SequenceNumber10::SetModulusBase (uint16_t modulusBase) inline
Set modulus base.
Parameters
modulusBase the modulus
Definition at line 99 of file lte-rlc-sequence-number.h.
References m_modulusBase.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const SequenceNumber10 & val) friend
Ostream output function.
Parameters
os the output stream
val the sequence number
Returns
the os
Definition at line 31 of file lte-rlc-sequence-number.cc.
Member Data Documentation
m_modulusBase
uint16_t ns3::SequenceNumber10::m_modulusBase private
the modulus base
Definition at line 219 of file lte-rlc-sequence-number.h.
Referenced by operator+(), operator++(), operator-(), operator>(), and SetModulusBase().
m_value
uint16_t ns3::SequenceNumber10::m_value private
the value
Definition at line 218 of file lte-rlc-sequence-number.h.
Referenced by GetValue(), operator!=(), operator+(), operator++(), operator-(), operator<(), ns3::operator<<(), operator=(), operator==(), operator>(), and SetModulusBase().
The documentation for this class was generated from the following file:
src/lte/model/lte-rlc-sequence-number.h