ns-3: TcpRxBufferTestCase Class Reference
TcpRxBufferTestCase Class Reference
Test suites
The TcpRxBuffer Test.
Public Member Functions
TcpRxBufferTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
virtual void DoTeardown (void)
Implementation to do any local setup required for this TestCase.
void TestUpdateSACKList ()
Test the SACK list update.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
The TcpRxBuffer Test.
Definition at line 34 of file tcp-rx-buffer-test.cc.
Constructor & Destructor Documentation
TcpRxBufferTestCase()
TcpRxBufferTestCase::TcpRxBufferTestCase ()
Definition at line 49 of file tcp-rx-buffer-test.cc.
Member Function Documentation
DoRun()
void TcpRxBufferTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 55 of file tcp-rx-buffer-test.cc.
References TestUpdateSACKList().
DoTeardown()
void TcpRxBufferTestCase::DoTeardown (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test teardown
Reimplemented from ns3::TestCase.
Definition at line 342 of file tcp-rx-buffer-test.cc.
TestUpdateSACKList()
void TcpRxBufferTestCase::TestUpdateSACKList () private
Test the SACK list update.
Definition at line 61 of file tcp-rx-buffer-test.cc.
References ns3::TcpRxBuffer::Add(), ns3::TcpRxBuffer::GetSackList(), ns3::TcpRxBuffer::NextRxSequence(), NS_TEST_ASSERT_MSG_EQ, ns3::TcpRxBuffer::SetNextRxSequence(), and ns3::TcpHeader::SetSequenceNumber().
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/internet/test/tcp-rx-buffer-test.cc