ns-3: ns3::SocketWriter Class Reference
ns3::SocketWriter Class Reference
#include "ns3tcp-socket-writer.h"
Public Member Functions
SocketWriter ()
virtual ~SocketWriter ()
void Close ()
void Connect ()
void Setup (Ptr< Node > node, Address peer)
void Write (uint32_t numBytes)
Public Member Functions inherited from ns3::Application
Application ()
virtual ~Application ()
Ptr< Node > GetNode () const
void SetNode (Ptr< Node > node)
void SetStartTime (Time start)
Specify application start time.
void SetStopTime (Time stop)
Specify application stop time.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Application
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual void StartApplication (void)
Application specific startup code.
virtual void StopApplication (void)
Application specific shutdown code.
Private Attributes
bool m_isConnected
bool m_isSetup
Ptr< Node > m_node
Address m_peer
Ptr< Socket > m_socket
Additional Inherited Members
Public Types inherited from ns3::Application
typedef void(* DelayAddressCallback) (const Time &delay, const Address &from)
Common callback signature for packet delay and address.
typedef void(* StateTransitionCallback) (const std::string &oldState, const std::string &newState)
Common signature used by callbacks to application's state transition trace source.
Protected Member Functions inherited from ns3::Application
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Application
Ptr< Node > m_node
The node that this application is installed on.
EventId m_startEvent
The event that will fire at m_startTime to start the application.
Time m_startTime
The simulation time that the application will start.
EventId m_stopEvent
The event that will fire at m_stopTime to end the application.
Time m_stopTime
The simulation time that the application will end.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 28 of file ns3tcp-socket-writer.h.
Constructor & Destructor Documentation
SocketWriter()
ns3::SocketWriter::SocketWriter ()
Definition at line 26 of file ns3tcp-socket-writer.cc.
~SocketWriter()
ns3::SocketWriter::~SocketWriter () virtual
Definition at line 30 of file ns3tcp-socket-writer.cc.
References m_node, and m_socket.
Member Function Documentation
Close()
void ns3::SocketWriter::Close ()
Definition at line 91 of file ns3tcp-socket-writer.cc.
References ns3::Socket::Close(), and m_socket.
Connect()
void ns3::SocketWriter::Connect ()
Definition at line 69 of file ns3tcp-socket-writer.cc.
References ns3::Socket::Connect(), m_isConnected, m_isSetup, m_peer, m_socket, and NS_FATAL_ERROR.
Referenced by Write().
GetTypeId()
TypeId ns3::SocketWriter::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 38 of file ns3tcp-socket-writer.cc.
References ns3::TypeId::SetParent().
Setup()
void ns3::SocketWriter::Setup (Ptr< Node > node, Address peer)
Definition at line 61 of file ns3tcp-socket-writer.cc.
References m_isSetup, m_node, and m_peer.
Referenced by Ns3TcpNoDelayTestCase::DoRun(), Ns3TcpSocketTestCase1::DoRun(), Ns3TcpSocketTestCase2::DoRun(), NscTcpLossTestCase1::DoRun(), and NscTcpLossTestCase2::DoRun().
StartApplication()
void ns3::SocketWriter::StartApplication (void) private virtual
Application specific startup code.
The StartApplication method is called at the start time specified by Start This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 49 of file ns3tcp-socket-writer.cc.
References ns3::Socket::Bind(), ns3::Socket::CreateSocket(), ns3::TcpSocketFactory::GetTypeId(), m_node, and m_socket.
StopApplication()
void ns3::SocketWriter::StopApplication (void) private virtual
Application specific shutdown code.
The StopApplication method is called at the stop time specified by Stop This method should be overridden by all or most application subclasses.
Reimplemented from ns3::Application.
Definition at line 56 of file ns3tcp-socket-writer.cc.
Write()
void ns3::SocketWriter::Write (uint32_t numBytes)
Definition at line 80 of file ns3tcp-socket-writer.cc.
References Connect(), m_isConnected, m_socket, and ns3::Socket::Send().
Member Data Documentation
m_isConnected
bool ns3::SocketWriter::m_isConnected private
Definition at line 51 of file ns3tcp-socket-writer.h.
Referenced by Connect(), and Write().
m_isSetup
bool ns3::SocketWriter::m_isSetup private
Definition at line 50 of file ns3tcp-socket-writer.h.
Referenced by Connect(), and Setup().
m_node
Ptr<Node> ns3::SocketWriter::m_node private
Definition at line 48 of file ns3tcp-socket-writer.h.
Referenced by ~SocketWriter(), Setup(), and StartApplication().
m_peer
Address ns3::SocketWriter::m_peer private
Definition at line 47 of file ns3tcp-socket-writer.h.
Referenced by Connect(), and Setup().
m_socket
Ptr<Socket> ns3::SocketWriter::m_socket private
Definition at line 49 of file ns3tcp-socket-writer.h.
Referenced by ~SocketWriter(), Close(), Connect(), StartApplication(), and Write().
The documentation for this class was generated from the following files:
src/test/ns3tcp/ns3tcp-socket-writer.h
src/test/ns3tcp/ns3tcp-socket-writer.cc