ns-3: AcousticModemEnergyDepletionTestCase Class Reference
AcousticModemEnergyDepletionTestCase Class Reference
UAN Models » uan module tests | Test suites
Acoustic Modem Energy Depletion Test Case.
Public Member Functions
AcousticModemEnergyDepletionTestCase ()
~AcousticModemEnergyDepletionTestCase ()
void DepletionHandler (void)
Depletion handler function.
void DoRun (void)
Implementation to actually run this TestCase.
void SendOnePacket (Ptr< Node > node)
Send one packet function.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Public Attributes
uint32_t m_callbackCount
callback count
Ptr< Node > m_node
the node
uint32_t m_packetSize
packet size
double m_simTime
Simulation time.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Acoustic Modem Energy Depletion Test Case.
Definition at line 224 of file uan-energy-model-test.cc.
Constructor & Destructor Documentation
AcousticModemEnergyDepletionTestCase()
AcousticModemEnergyDepletionTestCase::AcousticModemEnergyDepletionTestCase ()
Definition at line 246 of file uan-energy-model-test.cc.
~AcousticModemEnergyDepletionTestCase()
AcousticModemEnergyDepletionTestCase::~AcousticModemEnergyDepletionTestCase ()
Definition at line 254 of file uan-energy-model-test.cc.
References m_node.
Member Function Documentation
DepletionHandler()
void AcousticModemEnergyDepletionTestCase::DepletionHandler (void)
Depletion handler function.
Definition at line 260 of file uan-energy-model-test.cc.
References m_callbackCount.
Referenced by DoRun().
DoRun()
void AcousticModemEnergyDepletionTestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 282 of file uan-energy-model-test.cc.
References ns3::Object::AggregateObject(), third::channel, DepletionHandler(), ns3::Object::GetObject(), ns3::UanHelper::Install(), ns3::DeviceEnergyModelHelper::Install(), ns3::EnergySourceHelper::Install(), m_callbackCount, m_node, m_simTime, ns3::MakeCallback(), third::mobility, NS_TEST_ASSERT_MSG_EQ, ns3::Seconds(), SendOnePacket(), ns3::BasicEnergySourceHelper::Set(), and ns3::AcousticModemEnergyModelHelper::SetDepletionCallback().
SendOnePacket()
void AcousticModemEnergyDepletionTestCase::SendOnePacket (Ptr< Node > node)
Send one packet function.
Parameters
node the node to send to
Definition at line 267 of file uan-energy-model-test.cc.
References ns3::UanNetDevice::GetBroadcast(), ns3::Node::GetDevice(), m_packetSize, ns3::Seconds(), and ns3::UanNetDevice::Send().
Referenced by DoRun().
Member Data Documentation
m_callbackCount
uint32_t AcousticModemEnergyDepletionTestCase::m_callbackCount
callback count
Definition at line 241 of file uan-energy-model-test.cc.
Referenced by DepletionHandler(), and DoRun().
m_node
Ptr<Node> AcousticModemEnergyDepletionTestCase::m_node
the node
Definition at line 243 of file uan-energy-model-test.cc.
Referenced by ~AcousticModemEnergyDepletionTestCase(), and DoRun().
m_packetSize
uint32_t AcousticModemEnergyDepletionTestCase::m_packetSize
packet size
Definition at line 242 of file uan-energy-model-test.cc.
Referenced by SendOnePacket().
m_simTime
double AcousticModemEnergyDepletionTestCase::m_simTime
Simulation time.
Definition at line 240 of file uan-energy-model-test.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/uan/test/uan-energy-model-test.cc