ns-3: LteDownlinkPowerControlTestCase Class Reference
LteDownlinkPowerControlTestCase Class Reference
LTE Models » lte module tests | Test suites
Test SINR calculation in the downlink when the power control is used. Test the power control by comparing the downlink data and ctrl power difference with the estimated value based on the specified change in power.
#include "lte-test-downlink-power-control.h"
Public Member Functions
LteDownlinkPowerControlTestCase (bool changePower, uint8_t pa, std::string name)
Constructor.
virtual ~LteDownlinkPowerControlTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
bool m_changePdschConfigDedicated
PDSCH config dedicated change.
double m_expectedPowerDiff
expected power difference
LteRrcSap::PdschConfigDedicated m_pdschConfigDedicated
PDSCH config dedicated.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test SINR calculation in the downlink when the power control is used. Test the power control by comparing the downlink data and ctrl power difference with the estimated value based on the specified change in power.
Definition at line 98 of file lte-test-downlink-power-control.h.
Constructor & Destructor Documentation
LteDownlinkPowerControlTestCase()
LteDownlinkPowerControlTestCase::LteDownlinkPowerControlTestCase (bool changePower, uint8_t pa, std::string name)
Constructor.
Parameters
changePower
pa
name the reference name
Definition at line 382 of file lte-test-downlink-power-control.cc.
References m_changePdschConfigDedicated, m_expectedPowerDiff, m_pdschConfigDedicated, NS_LOG_INFO, and ns3::LteRrcSap::PdschConfigDedicated::pa.
~LteDownlinkPowerControlTestCase()
LteDownlinkPowerControlTestCase::~LteDownlinkPowerControlTestCase () virtual
Definition at line 391 of file lte-test-downlink-power-control.cc.
Member Function Documentation
DoRun()
void LteDownlinkPowerControlTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Simulation Topology
Implements ns3::TestCase.
Definition at line 396 of file lte-test-downlink-power-control.cc.
References ns3::LteHelper::ActivateDataRadioBearer(), ns3::LteChunkProcessor::AddCallback(), ns3::LteHelper::Attach(), ns3::LteFfrSimple::ChangePdschConfigDedicated(), ns3::NodeContainer::Create(), ns3::NetDeviceContainer::Get(), ns3::LtePhy::GetDownlinkSpectrumPhy(), ns3::Object::GetObject(), ns3::PointerValue::GetObject(), ns3::LteSpectrumValueCatcher::GetValue(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), m_changePdschConfigDedicated, m_expectedPowerDiff, m_pdschConfigDedicated, ns3::MakeCallback(), third::mobility, NS_LOG_DEBUG, NS_TEST_ASSERT_MSG_EQ_TOL, ns3::Config::Reset(), ns3::Seconds(), ns3::Config::SetDefault(), ns3::LteHelper::SetFfrAlgorithmType(), ns3::LteFfrSimple::SetPdschConfigDedicated(), and ns3::LteHelper::SetSchedulerType().
Member Data Documentation
m_changePdschConfigDedicated
bool LteDownlinkPowerControlTestCase::m_changePdschConfigDedicated private
PDSCH config dedicated change.
Definition at line 114 of file lte-test-downlink-power-control.h.
Referenced by LteDownlinkPowerControlTestCase(), and DoRun().
m_expectedPowerDiff
double LteDownlinkPowerControlTestCase::m_expectedPowerDiff private
expected power difference
Definition at line 116 of file lte-test-downlink-power-control.h.
Referenced by LteDownlinkPowerControlTestCase(), and DoRun().
m_pdschConfigDedicated
LteRrcSap::PdschConfigDedicated LteDownlinkPowerControlTestCase::m_pdschConfigDedicated private
PDSCH config dedicated.
Definition at line 115 of file lte-test-downlink-power-control.h.
Referenced by LteDownlinkPowerControlTestCase(), and DoRun().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-downlink-power-control.h
src/lte/test/lte-test-downlink-power-control.cc