ns-3: ns3::LteEnbRrcSapProvider Class Reference
ns3::LteEnbRrcSapProvider Class Reference abstract
Part of the RRC protocol.
#include "lte-rrc-sap.h"
Classes
struct CompleteSetupUeParameters
CompleteSetupUeParameters structure.
Public Member Functions
virtual void CompleteSetupUe (uint16_t rnti, CompleteSetupUeParameters params)=0
Complete setup UE function.
virtual void RecvIdealUeContextRemoveRequest (uint16_t rnti)=0
Receive ideal UE context remove request from the UE RRC.
virtual void RecvMeasurementReport (uint16_t rnti, MeasurementReport msg)=0
Receive a MeasurementReport message from a UE during a measurement reporting procedure (Section 5.5.5 of TS 36.331).
virtual void RecvRrcConnectionReconfigurationCompleted (uint16_t rnti, RrcConnectionReconfigurationCompleted msg)=0
Receive an RRCConnectionReconfigurationComplete message from a UE during an RRC connection reconfiguration procedure (Section 5.3.5 of TS 36.331).
virtual void RecvRrcConnectionReestablishmentComplete (uint16_t rnti, RrcConnectionReestablishmentComplete msg)=0
Receive an RRCConnectionReestablishmentComplete message from a UE during an RRC connection re-establishment procedure (Section 5.3.7 of TS 36.331).
virtual void RecvRrcConnectionReestablishmentRequest (uint16_t rnti, RrcConnectionReestablishmentRequest msg)=0
Receive an RRCConnectionReestablishmentRequest message from a UE during an RRC connection re-establishment procedure (Section 5.3.7 of TS 36.331).
virtual void RecvRrcConnectionRequest (uint16_t rnti, RrcConnectionRequest msg)=0
Receive an RRCConnectionRequest message from a UE during an RRC connection establishment procedure (Section 5.3.3 of TS 36.331).
virtual void RecvRrcConnectionSetupCompleted (uint16_t rnti, RrcConnectionSetupCompleted msg)=0
Receive an RRCConnectionSetupComplete message from a UE during an RRC connection establishment procedure (Section 5.3.3 of TS 36.331).
Public Member Functions inherited from ns3::LteRrcSap
virtual ~LteRrcSap ()
Additional Inherited Members
Public Types inherited from ns3::LteRrcSap
enum ReestablishmentCause { RECONFIGURATION_FAILURE, HANDOVER_FAILURE, OTHER_FAILURE }
ReestablishmentCause enumeration.
Static Public Member Functions inherited from ns3::LteRrcSap
static double ConvertPdschConfigDedicated2Double (PdschConfigDedicated pdschConfigDedicated)
Convert PDSCH config dedicated function.
Static Public Attributes inherited from ns3::LteRrcSap
static const uint8_t MaxReportCells = 8
Constraint values.
Detailed Description
Part of the RRC protocol.
This Service Access Point (SAP) is used to let the eNB RRC receive a message from a UE RRC. Each method defined in this class corresponds to the reception of a message that is defined in Section 6.2.2 of TS 36.331.
Definition at line 1200 of file lte-rrc-sap.h.
Member Function Documentation
CompleteSetupUe()
virtual void ns3::LteEnbRrcSapProvider::CompleteSetupUe (uint16_t rnti, CompleteSetupUeParameters params) pure virtual
Complete setup UE function.
Parameters
rnti the RNTI of UE which sent the message
params CompleteSetupUeParameters
Implemented in ns3::MemberLteEnbRrcSapProvider< C >.
Referenced by ns3::LteEnbRrcProtocolReal::DoSetupUe().
RecvIdealUeContextRemoveRequest()
virtual void ns3::LteEnbRrcSapProvider::RecvIdealUeContextRemoveRequest (uint16_t rnti) pure virtual
Receive ideal UE context remove request from the UE RRC.
Receive the notification from UE to remove the UE context once radio link failure or random access failure is detected. It is needed since no RLF detection mechanism at eNodeB is implemented.
Parameters
rnti the C-RNTI of the UE
Implemented in ns3::MemberLteEnbRrcSapProvider< C >.
Referenced by ns3::LteUeRrcProtocolIdeal::DoSendIdealUeContextRemoveRequest(), and ns3::LteUeRrcProtocolReal::DoSendIdealUeContextRemoveRequest().
RecvMeasurementReport()
virtual void ns3::LteEnbRrcSapProvider::RecvMeasurementReport (uint16_t rnti, MeasurementReport msg) pure virtual
Receive a MeasurementReport message from a UE during a measurement reporting procedure (Section 5.5.5 of TS 36.331).
Parameters
rnti the RNTI of UE which sent the message
msg the message
Implemented in ns3::MemberLteEnbRrcSapProvider< C >.
Referenced by ns3::LteEnbRrcProtocolReal::DoReceivePdcpSdu(), and ns3::LteUeRrcProtocolIdeal::DoSendMeasurementReport().
RecvRrcConnectionReconfigurationCompleted()
virtual void ns3::LteEnbRrcSapProvider::RecvRrcConnectionReconfigurationCompleted (uint16_t rnti, RrcConnectionReconfigurationCompleted msg) pure virtual
Receive an RRCConnectionReconfigurationComplete message from a UE during an RRC connection reconfiguration procedure (Section 5.3.5 of TS 36.331).
Parameters
rnti the RNTI of UE which sent the message
msg the message
Implemented in ns3::MemberLteEnbRrcSapProvider< C >.
Referenced by ns3::LteEnbRrcProtocolReal::DoReceivePdcpSdu(), and ns3::LteUeRrcProtocolIdeal::DoSendRrcConnectionReconfigurationCompleted().
RecvRrcConnectionReestablishmentComplete()
virtual void ns3::LteEnbRrcSapProvider::RecvRrcConnectionReestablishmentComplete (uint16_t rnti, RrcConnectionReestablishmentComplete msg) pure virtual
Receive an RRCConnectionReestablishmentComplete message from a UE during an RRC connection re-establishment procedure (Section 5.3.7 of TS 36.331).
Parameters
rnti the RNTI of UE which sent the message
msg the message
Implemented in ns3::MemberLteEnbRrcSapProvider< C >.
Referenced by ns3::LteEnbRrcProtocolReal::DoReceivePdcpSdu(), and ns3::LteUeRrcProtocolIdeal::DoSendRrcConnectionReestablishmentComplete().
RecvRrcConnectionReestablishmentRequest()
virtual void ns3::LteEnbRrcSapProvider::RecvRrcConnectionReestablishmentRequest (uint16_t rnti, RrcConnectionReestablishmentRequest msg) pure virtual
Receive an RRCConnectionReestablishmentRequest message from a UE during an RRC connection re-establishment procedure (Section 5.3.7 of TS 36.331).
Parameters
rnti the RNTI of UE which sent the message
msg the message
Implemented in ns3::MemberLteEnbRrcSapProvider< C >.
Referenced by ns3::LteEnbRrcProtocolReal::DoReceivePdcpPdu(), and ns3::LteUeRrcProtocolIdeal::DoSendRrcConnectionReestablishmentRequest().
RecvRrcConnectionRequest()
virtual void ns3::LteEnbRrcSapProvider::RecvRrcConnectionRequest (uint16_t rnti, RrcConnectionRequest msg) pure virtual
Receive an RRCConnectionRequest message from a UE during an RRC connection establishment procedure (Section 5.3.3 of TS 36.331).
Parameters
rnti the RNTI of UE which sent the message
msg the message
Implemented in ns3::MemberLteEnbRrcSapProvider< C >.
Referenced by ns3::LteEnbRrcProtocolReal::DoReceivePdcpPdu(), and ns3::LteUeRrcProtocolIdeal::DoSendRrcConnectionRequest().
RecvRrcConnectionSetupCompleted()
virtual void ns3::LteEnbRrcSapProvider::RecvRrcConnectionSetupCompleted (uint16_t rnti, RrcConnectionSetupCompleted msg) pure virtual
Receive an RRCConnectionSetupComplete message from a UE during an RRC connection establishment procedure (Section 5.3.3 of TS 36.331).
Parameters
rnti the RNTI of UE which sent the message
msg the message
Implemented in ns3::MemberLteEnbRrcSapProvider< C >.
Referenced by ns3::LteEnbRrcProtocolReal::DoReceivePdcpSdu(), and ns3::LteUeRrcProtocolIdeal::DoSendRrcConnectionSetupCompleted().
The documentation for this class was generated from the following file:
src/lte/model/lte-rrc-sap.h