ns-3: ns3::SixLowPanIphc Class Reference
ns3::SixLowPanIphc Class Reference
6LoWPAN
LOWPAN_IPHC base Encoding - see RFC 6282.
#include "sixlowpan-header.h"
Public Types
enum HeaderCompression_e { HC_INLINE = 0, HC_COMPR_64, HC_COMPR_16, HC_COMPR_0 }
Source or Destination Address Mode.
enum Hlim_e { HLIM_INLINE = 0, HLIM_COMPR_1, HLIM_COMPR_64, HLIM_COMPR_255 }
HLIM: Hop Limit.
enum TrafficClassFlowLabel_e { TF_FULL = 0, TF_DSCP_ELIDED, TF_FL_ELIDED, TF_ELIDED }
TF: Traffic Class, Flow Label.
Public Member Functions
SixLowPanIphc (uint8_t dispatch)
Constructor.
SixLowPanIphc (void)
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
bool GetCid (void) const
Get the CID (Context Identifier Extension) compression.
bool GetDac (void) const
Get the DAC (Destination Address Compression) compression.
HeaderCompression_e GetDam (void) const
Get the DAM (Destination Address Mode) compression.
uint8_t GetDscp (void) const
Get the DSCP.
Ipv6Address GetDstAddress () const
Get the Destination Address.
uint8_t GetDstContextId (void) const
Get the DstContextId.
uint8_t GetEcn (void) const
Get the ECN.
uint32_t GetFlowLabel (void) const
Get the Flow Label.
Hlim_e GetHlim (void) const
Get the HLIM (Hop Limit) compression.
uint8_t GetHopLimit (void) const
Get the Hop Limit field.
virtual TypeId GetInstanceTypeId (void) const
Return the instance type identifier.
bool GetM (void) const
Get the M (Multicast) compression.
uint8_t GetNextHeader (void) const
Get the Next Header field.
bool GetNh (void) const
Get the NH (Next Header) compression.
bool GetSac (void) const
Get the SAC (Source Address Compression) compression.
HeaderCompression_e GetSam (void) const
Get the SAM (Source Address Mode) compression.
virtual uint32_t GetSerializedSize (void) const
Get the serialized size of the packet.
Ipv6Address GetSrcAddress () const
Get the Source Address.
uint8_t GetSrcContextId (void) const
Get the SrcContextId.
TrafficClassFlowLabel_e GetTf (void) const
Get the TF (Traffic Class, Flow Label) compression.
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetCid (bool cidField)
Set the CID (Context Identifier Extension) compression.
void SetDac (bool dacField)
Set the DAC (Destination Address Compression) compression.
void SetDam (HeaderCompression_e damField)
Set the DAM (Destination Address Mode) compression.
void SetDscp (uint8_t dscp)
Set the DSCP (6bits).
void SetDstAddress (Ipv6Address dstAddress)
Set the Destination Address.
void SetDstContextId (uint8_t dstContextId)
Set the DstContextId.
void SetEcn (uint8_t ecn)
Set the ECN (2bits).
void SetFlowLabel (uint32_t flowLabel)
Set the Flow Label (20bits).
void SetHlim (Hlim_e hlimField)
Set the HLIM (Hop Limit) compression.
void SetHopLimit (uint8_t hopLimit)
Set the Hop Limit field.
void SetM (bool mField)
Set the M (Multicast) compression.
void SetNextHeader (uint8_t nextHeader)
Set the Next Header field.
void SetNh (bool nhField)
Set the NH (Next Header) compression.
void SetSac (bool sacField)
Set the SAC (Source Address Compression) compression.
void SetSam (HeaderCompression_e samField)
Set the SAM (Source Address Mode) compression.
void SetSrcAddress (Ipv6Address srcAddress)
Set the Source Address.
void SetSrcContextId (uint8_t srcContextId)
Set the SrcContextId.
void SetTf (TrafficClassFlowLabel_e tfField)
Set the TF (Traffic Class, Flow Label) compression.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void PostProcessDac ()
Post-process the Destination address stateful compression.
void PostProcessSac ()
Post-process the Source address stateful compression.
Private Attributes
uint16_t m_baseFormat
Dispatch + encoding fields.
uint8_t m_dscp: 6
DSCP bits.
Ipv6Address m_dstAddress
Dst address.
uint8_t m_ecn: 2
ECN bits.
uint32_t m_flowLabel: 20
Flow Label bits.
uint8_t m_hopLimit
Hop Limit.
uint8_t m_nextHeader
Next header.
Ipv6Address m_srcAddress
Src address.
uint8_t m_srcdstContextId
Src and Dst Context ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
LOWPAN_IPHC base Encoding - see RFC 6282.
     0                                       1
     0   1   2   3   4   5   6   7   8   9   0   1   2   3   4   5
   +---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+
   | 0 | 1 | 1 |  TF   |NH | HLIM  |CID|SAC|  SAM  | M |DAC|  DAM  |
   +---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+
Definition at line 607 of file sixlowpan-header.h.
Member Enumeration Documentation
HeaderCompression_e
enum ns3::SixLowPanIphc::HeaderCompression_e
Source or Destination Address Mode.
00: 128 bits. 01: 64 bits (or 48 bits if multicast). 10: 16 bits (or 32 bits if multicast). 11: Fully elided (or 8 bits if multicast).
Enumerator
HC_INLINE
HC_COMPR_64
HC_COMPR_16
HC_COMPR_0
Definition at line 651 of file sixlowpan-header.h.
Hlim_e
enum ns3::SixLowPanIphc::Hlim_e
HLIM: Hop Limit.
00: The Hop Limit field is carried in-line. 01: The Hop Limit field is compressed and the hop limit is 1. 10: The Hop Limit field is compressed and the hop limit is 64. 11: The Hop Limit field is compressed and the hop limit is 255.
Enumerator
HLIM_INLINE
HLIM_COMPR_1
HLIM_COMPR_64
HLIM_COMPR_255
Definition at line 635 of file sixlowpan-header.h.
TrafficClassFlowLabel_e
enum ns3::SixLowPanIphc::TrafficClassFlowLabel_e
TF: Traffic Class, Flow Label.
00: ECN + DSCP + 4-bit Pad + Flow Label (4 bytes) 01: ECN + 2-bit Pad + Flow Label (3 bytes), DSCP is elided. 10: ECN + DSCP (1 byte), Flow Label is elided. 11: Traffic Class and Flow Label are elided.
Enumerator
TF_FULL
TF_DSCP_ELIDED
TF_FL_ELIDED
TF_ELIDED
Definition at line 619 of file sixlowpan-header.h.
Constructor & Destructor Documentation
SixLowPanIphc() [1/2]
ns3::SixLowPanIphc::SixLowPanIphc (void)
Definition at line 792 of file sixlowpan-header.cc.
References m_baseFormat.
SixLowPanIphc() [2/2]
ns3::SixLowPanIphc::SixLowPanIphc (uint8_t dispatch)
Constructor.
Parameters
[in] dispatch Dispatch value.
Definition at line 798 of file sixlowpan-header.cc.
References m_baseFormat.
Member Function Documentation
Deserialize()
uint32_t ns3::SixLowPanIphc::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
[in] start Buffer iterator.
Returns
Size of the packet.
Implements ns3::Header.
Definition at line 1079 of file sixlowpan-header.cc.
References ns3::Ipv6Address::Deserialize(), GetCid(), GetDac(), GetDam(), GetHlim(), GetM(), GetNh(), GetSac(), GetSam(), GetSerializedSize(), GetTf(), HC_COMPR_0, HC_COMPR_16, HC_COMPR_64, HC_INLINE, HLIM_COMPR_1, HLIM_COMPR_255, HLIM_COMPR_64, HLIM_INLINE, m_baseFormat, m_dscp, m_dstAddress, m_ecn, m_flowLabel, m_hopLimit, m_nextHeader, m_srcAddress, m_srcdstContextId, PostProcessDac(), PostProcessSac(), ns3::Buffer::Iterator::Read(), ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadU8(), visualizer.core::start(), TF_DSCP_ELIDED, TF_FL_ELIDED, and TF_FULL.
GetCid()
bool ns3::SixLowPanIphc::GetCid (void) const
Get the CID (Context Identifier Extension) compression.
Returns
False (no CID present), true (CID follows).
Definition at line 1312 of file sixlowpan-header.cc.
References m_baseFormat.
Referenced by Deserialize(), GetSerializedSize(), and Serialize().
GetDac()
bool ns3::SixLowPanIphc::GetDac (void) const
Get the DAC (Destination Address Compression) compression.
Returns
False (stateless), true (stateful).
Definition at line 1356 of file sixlowpan-header.cc.
References m_baseFormat.
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanIphc(), Deserialize(), GetSerializedSize(), and Serialize().
GetDam()
SixLowPanIphc::HeaderCompression_e ns3::SixLowPanIphc::GetDam (void) const
Get the DAM (Destination Address Mode) compression.
Returns
Depends on the DAC and M fields.
Definition at line 1367 of file sixlowpan-header.cc.
References m_baseFormat.
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanIphc(), Deserialize(), GetSerializedSize(), and Serialize().
GetDscp()
uint8_t ns3::SixLowPanIphc::GetDscp (void) const
Get the DSCP.
Returns
The DSCP.
Definition at line 1411 of file sixlowpan-header.cc.
References m_dscp.
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanIphc().
GetDstAddress()
Ipv6Address ns3::SixLowPanIphc::GetDstAddress () const
Get the Destination Address.
Returns
The Destination Address.
Definition at line 1462 of file sixlowpan-header.cc.
References m_dstAddress.
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanIphc().
GetDstContextId()
uint8_t ns3::SixLowPanIphc::GetDstContextId (void) const
Get the DstContextId.
Returns
The DstContextId.
Definition at line 1389 of file sixlowpan-header.cc.
References m_srcdstContextId.
GetEcn()
uint8_t ns3::SixLowPanIphc::GetEcn (void) const
Get the ECN.
Returns
The ECN.
Definition at line 1400 of file sixlowpan-header.cc.
References m_ecn.
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanIphc().
GetFlowLabel()
uint32_t ns3::SixLowPanIphc::GetFlowLabel (void) const
Get the Flow Label.
Returns
The Flow Label.
Definition at line 1422 of file sixlowpan-header.cc.
References m_flowLabel.
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanIphc().
GetHlim()
SixLowPanIphc::Hlim_e ns3::SixLowPanIphc::GetHlim (void) const
Get the HLIM (Hop Limit) compression.
Returns
Hop Limit compression type.
Definition at line 1301 of file sixlowpan-header.cc.
References m_baseFormat.
Referenced by Deserialize(), GetSerializedSize(), and Serialize().
GetHopLimit()
uint8_t ns3::SixLowPanIphc::GetHopLimit (void) const
Get the Hop Limit field.
Returns
The Hop Limit field.
Definition at line 1442 of file sixlowpan-header.cc.
References m_hopLimit.
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanIphc().
GetInstanceTypeId()
TypeId ns3::SixLowPanIphc::GetInstanceTypeId (void) const virtual
Return the instance type identifier.
Returns
Instance type ID.
Implements ns3::ObjectBase.
Definition at line 814 of file sixlowpan-header.cc.
References GetTypeId().
GetM()
bool ns3::SixLowPanIphc::GetM (void) const
Get the M (Multicast) compression.
Returns
True if destination is multicast.
Definition at line 1345 of file sixlowpan-header.cc.
References m_baseFormat.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanIphc(), ns3::SixLowPanNetDevice::DecompressLowPanIphc(), Deserialize(), GetSerializedSize(), and Serialize().
GetNextHeader()
uint8_t ns3::SixLowPanIphc::GetNextHeader (void) const
Get the Next Header field.
Returns
The Next Header field.
Definition at line 1432 of file sixlowpan-header.cc.
References m_nextHeader.
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanIphc().
GetNh()
bool ns3::SixLowPanIphc::GetNh (void) const
Get the NH (Next Header) compression.
Returns
False (Next Header carried in-line), true (compressed NH).
Definition at line 1290 of file sixlowpan-header.cc.
References m_baseFormat.
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanIphc(), Deserialize(), GetSerializedSize(), and Serialize().
GetSac()
bool ns3::SixLowPanIphc::GetSac (void) const
Get the SAC (Source Address Compression) compression.
Returns
False (stateless), true (stateful).
Definition at line 1323 of file sixlowpan-header.cc.
References m_baseFormat.
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanIphc(), Deserialize(), GetSerializedSize(), and Serialize().
GetSam()
SixLowPanIphc::HeaderCompression_e ns3::SixLowPanIphc::GetSam (void) const
Get the SAM (Source Address Mode) compression.
Returns
Depends on the SAC field.
Definition at line 1334 of file sixlowpan-header.cc.
References m_baseFormat.
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanIphc(), Deserialize(), GetSerializedSize(), and Serialize().
GetSerializedSize()
uint32_t ns3::SixLowPanIphc::GetSerializedSize (void) const virtual
Get the serialized size of the packet.
Returns
Size.
Implements ns3::Header.
Definition at line 824 of file sixlowpan-header.cc.
References GetCid(), GetDac(), GetDam(), GetHlim(), GetM(), GetNh(), GetSac(), GetSam(), GetTf(), HC_COMPR_0, HC_COMPR_16, HC_COMPR_64, HC_INLINE, HLIM_INLINE, TF_DSCP_ELIDED, TF_FL_ELIDED, and TF_FULL.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanIphc(), and Deserialize().
GetSrcAddress()
Ipv6Address ns3::SixLowPanIphc::GetSrcAddress () const
Get the Source Address.
Returns
The Source Address.
Definition at line 1452 of file sixlowpan-header.cc.
References m_srcAddress.
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanIphc().
GetSrcContextId()
uint8_t ns3::SixLowPanIphc::GetSrcContextId (void) const
Get the SrcContextId.
Returns
The SrcContextId.
Definition at line 1378 of file sixlowpan-header.cc.
References m_srcdstContextId.
GetTf()
SixLowPanIphc::TrafficClassFlowLabel_e ns3::SixLowPanIphc::GetTf (void) const
Get the TF (Traffic Class, Flow Label) compression.
Returns
The ECN, DSCP, Flow Label compression type.
Definition at line 1279 of file sixlowpan-header.cc.
References m_baseFormat.
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanIphc(), Deserialize(), GetSerializedSize(), and Serialize().
GetTypeId()
TypeId ns3::SixLowPanIphc::GetTypeId (void) static
Get the type ID.
Returns
The object TypeId.
Definition at line 805 of file sixlowpan-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
PostProcessDac()
void ns3::SixLowPanIphc::PostProcessDac () private
Post-process the Destination address stateful compression.
Note
Currently unsupported.
Definition at line 1473 of file sixlowpan-header.cc.
References NS_ABORT_MSG.
Referenced by Deserialize().
PostProcessSac()
void ns3::SixLowPanIphc::PostProcessSac () private
Post-process the Source address stateful compression.
Note
Currently unsupported.
Definition at line 1467 of file sixlowpan-header.cc.
References NS_ABORT_MSG.
Referenced by Deserialize().
Print()
void ns3::SixLowPanIphc::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 819 of file sixlowpan-header.cc.
References m_baseFormat.
Referenced by ns3::operator<<().
Serialize()
void ns3::SixLowPanIphc::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
[in] start Buffer iterator.
Implements ns3::Header.
Definition at line 934 of file sixlowpan-header.cc.
References GetCid(), GetDac(), GetDam(), GetHlim(), GetM(), GetNh(), GetSac(), GetSam(), GetTf(), HC_COMPR_0, HC_COMPR_16, HC_COMPR_64, HC_INLINE, HLIM_INLINE, m_baseFormat, m_dscp, m_dstAddress, m_ecn, m_flowLabel, m_hopLimit, m_nextHeader, m_srcAddress, m_srcdstContextId, ns3::Ipv6Address::Serialize(), visualizer.core::start(), TF_DSCP_ELIDED, TF_FL_ELIDED, TF_FULL, ns3::Buffer::Iterator::Write(), ns3::Buffer::Iterator::WriteHtonU16(), and ns3::Buffer::Iterator::WriteU8().
SetCid()
void ns3::SixLowPanIphc::SetCid (bool cidField)
Set the CID (Context Identifier Extension) compression.
Parameters
[in] cidField False (no CID present), true (CID follows).
Definition at line 1306 of file sixlowpan-header.cc.
References m_baseFormat.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanIphc().
SetDac()
void ns3::SixLowPanIphc::SetDac (bool dacField)
Set the DAC (Destination Address Compression) compression.
Parameters
[in] dacField False (stateless), true (stateful).
Definition at line 1350 of file sixlowpan-header.cc.
References m_baseFormat.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanIphc().
SetDam()
void ns3::SixLowPanIphc::SetDam (HeaderCompression_e damField)
Set the DAM (Destination Address Mode) compression.
Parameters
[in] damField Depends on the DAC and M fields.
Definition at line 1361 of file sixlowpan-header.cc.
References m_baseFormat.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanIphc().
SetDscp()
void ns3::SixLowPanIphc::SetDscp (uint8_t dscp)
Set the DSCP (6bits).
Parameters
[in] dscp Valid values are [0:63].
Definition at line 1405 of file sixlowpan-header.cc.
References m_dscp, and NS_ASSERT_MSG().
Referenced by ns3::SixLowPanNetDevice::CompressLowPanIphc().
SetDstAddress()
void ns3::SixLowPanIphc::SetDstAddress (Ipv6Address dstAddress)
Set the Destination Address.
Parameters
[in] dstAddress The Destination Address.
Definition at line 1457 of file sixlowpan-header.cc.
References m_dstAddress.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanIphc().
SetDstContextId()
void ns3::SixLowPanIphc::SetDstContextId (uint8_t dstContextId)
Set the DstContextId.
Parameters
[in] dstContextId Valid values are [0:15].
Definition at line 1383 of file sixlowpan-header.cc.
References m_srcdstContextId, and NS_ASSERT_MSG().
SetEcn()
void ns3::SixLowPanIphc::SetEcn (uint8_t ecn)
Set the ECN (2bits).
Parameters
[in] ecn Valid values are [0:3].
Definition at line 1394 of file sixlowpan-header.cc.
References m_ecn, and NS_ASSERT_MSG().
Referenced by ns3::SixLowPanNetDevice::CompressLowPanIphc().
SetFlowLabel()
void ns3::SixLowPanIphc::SetFlowLabel (uint32_t flowLabel)
Set the Flow Label (20bits).
Parameters
[in] flowLabel Valid values are 20 bits long.
Definition at line 1416 of file sixlowpan-header.cc.
References m_flowLabel, and NS_ASSERT_MSG().
Referenced by ns3::SixLowPanNetDevice::CompressLowPanIphc().
SetHlim()
void ns3::SixLowPanIphc::SetHlim (Hlim_e hlimField)
Set the HLIM (Hop Limit) compression.
Parameters
[in] hlimField Hop Limit compression type
Definition at line 1295 of file sixlowpan-header.cc.
References m_baseFormat.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanIphc().
SetHopLimit()
void ns3::SixLowPanIphc::SetHopLimit (uint8_t hopLimit)
Set the Hop Limit field.
Parameters
[in] hopLimit Hop Limit field.
Definition at line 1437 of file sixlowpan-header.cc.
References m_hopLimit.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanIphc().
SetM()
void ns3::SixLowPanIphc::SetM (bool mField)
Set the M (Multicast) compression.
Parameters
[in] mField True if destination is multicast.
Definition at line 1339 of file sixlowpan-header.cc.
References m_baseFormat.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanIphc().
SetNextHeader()
void ns3::SixLowPanIphc::SetNextHeader (uint8_t nextHeader)
Set the Next Header field.
Parameters
[in] nextHeader Next Header field.
Definition at line 1427 of file sixlowpan-header.cc.
References m_nextHeader.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanIphc().
SetNh()
void ns3::SixLowPanIphc::SetNh (bool nhField)
Set the NH (Next Header) compression.
Parameters
[in] nhField False (Next Header carried in-line), true (compressed NH).
Definition at line 1284 of file sixlowpan-header.cc.
References m_baseFormat.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanIphc().
SetSac()
void ns3::SixLowPanIphc::SetSac (bool sacField)
Set the SAC (Source Address Compression) compression.
Parameters
[in] sacField False (stateless), true (stateful).
Definition at line 1317 of file sixlowpan-header.cc.
References m_baseFormat.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanIphc().
SetSam()
void ns3::SixLowPanIphc::SetSam (HeaderCompression_e samField)
Set the SAM (Source Address Mode) compression.
Parameters
[in] samField Depends on the SAC.
Definition at line 1328 of file sixlowpan-header.cc.
References m_baseFormat.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanIphc().
SetSrcAddress()
void ns3::SixLowPanIphc::SetSrcAddress (Ipv6Address srcAddress)
Set the Source Address.
Parameters
[in] srcAddress The Source Address.
Definition at line 1447 of file sixlowpan-header.cc.
References m_srcAddress.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanIphc().
SetSrcContextId()
void ns3::SixLowPanIphc::SetSrcContextId (uint8_t srcContextId)
Set the SrcContextId.
Parameters
[in] srcContextId Valid values are [0:15].
Definition at line 1372 of file sixlowpan-header.cc.
References m_srcdstContextId, and NS_ASSERT_MSG().
SetTf()
void ns3::SixLowPanIphc::SetTf (TrafficClassFlowLabel_e tfField)
Set the TF (Traffic Class, Flow Label) compression.
Parameters
[in] tfField ECN, DSCP, Flow Label compression type.
Definition at line 1273 of file sixlowpan-header.cc.
References m_baseFormat.
Referenced by ns3::SixLowPanNetDevice::CompressLowPanIphc().
Member Data Documentation
m_baseFormat
uint16_t ns3::SixLowPanIphc::m_baseFormat private
Dispatch + encoding fields.
Definition at line 916 of file sixlowpan-header.h.
Referenced by SixLowPanIphc(), Deserialize(), GetCid(), GetDac(), GetDam(), GetHlim(), GetM(), GetNh(), GetSac(), GetSam(), GetTf(), Print(), Serialize(), SetCid(), SetDac(), SetDam(), SetHlim(), SetM(), SetNh(), SetSac(), SetSam(), and SetTf().
m_dscp
uint8_t ns3::SixLowPanIphc::m_dscp private
DSCP bits.
Definition at line 919 of file sixlowpan-header.h.
Referenced by Deserialize(), GetDscp(), Serialize(), and SetDscp().
m_dstAddress
Ipv6Address ns3::SixLowPanIphc::m_dstAddress private
Dst address.
Definition at line 924 of file sixlowpan-header.h.
Referenced by Deserialize(), GetDstAddress(), Serialize(), and SetDstAddress().
m_ecn
uint8_t ns3::SixLowPanIphc::m_ecn private
ECN bits.
Definition at line 918 of file sixlowpan-header.h.
Referenced by Deserialize(), GetEcn(), Serialize(), and SetEcn().
m_flowLabel
uint32_t ns3::SixLowPanIphc::m_flowLabel private
Flow Label bits.
Definition at line 920 of file sixlowpan-header.h.
Referenced by Deserialize(), GetFlowLabel(), Serialize(), and SetFlowLabel().
m_hopLimit
uint8_t ns3::SixLowPanIphc::m_hopLimit private
Hop Limit.
Definition at line 922 of file sixlowpan-header.h.
Referenced by Deserialize(), GetHopLimit(), Serialize(), and SetHopLimit().
m_nextHeader
uint8_t ns3::SixLowPanIphc::m_nextHeader private
Next header.
Definition at line 921 of file sixlowpan-header.h.
Referenced by Deserialize(), GetNextHeader(), Serialize(), and SetNextHeader().
m_srcAddress
Ipv6Address ns3::SixLowPanIphc::m_srcAddress private
Src address.
Definition at line 923 of file sixlowpan-header.h.
Referenced by Deserialize(), GetSrcAddress(), Serialize(), and SetSrcAddress().
m_srcdstContextId
uint8_t ns3::SixLowPanIphc::m_srcdstContextId private
Src and Dst Context ID.
Definition at line 917 of file sixlowpan-header.h.
Referenced by Deserialize(), GetDstContextId(), GetSrcContextId(), Serialize(), SetDstContextId(), and SetSrcContextId().
The documentation for this class was generated from the following files:
src/sixlowpan/model/sixlowpan-header.h
src/sixlowpan/model/sixlowpan-header.cc