ns-3: RngExponentialTestCase Class Reference
RngExponentialTestCase Class Reference
Public Member Functions
RngExponentialTestCase ()
virtual ~RngExponentialTestCase ()
double ChiSquaredTest (Ptr< ExponentialRandomVariable > n)
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Static Public Attributes
static const uint32_t N_BINS = 50
static const uint32_t N_MEASUREMENTS = 1000000
static const uint32_t N_RUNS = 5
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 223 of file rng-test-suite.cc.
Constructor & Destructor Documentation
RngExponentialTestCase()
RngExponentialTestCase::RngExponentialTestCase ()
Definition at line 239 of file rng-test-suite.cc.
~RngExponentialTestCase()
RngExponentialTestCase::~RngExponentialTestCase () virtual
Definition at line 243 of file rng-test-suite.cc.
Member Function Documentation
ChiSquaredTest()
double RngExponentialTestCase::ChiSquaredTest (Ptr< ExponentialRandomVariable > n)
Definition at line 247 of file rng-test-suite.cc.
References FillHistoRangeUniformly(), ns3::ExponentialRandomVariable::GetValue(), max, N_BINS, and N_MEASUREMENTS.
Referenced by DoRun().
DoRun()
void RngExponentialTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 295 of file rng-test-suite.cc.
References ChiSquaredTest(), N_BINS, N_RUNS, and NS_TEST_ASSERT_MSG_LT.
Member Data Documentation
N_BINS
const uint32_t RngExponentialTestCase::N_BINS = 50 static
Definition at line 227 of file rng-test-suite.cc.
Referenced by ChiSquaredTest(), and DoRun().
N_MEASUREMENTS
const uint32_t RngExponentialTestCase::N_MEASUREMENTS = 1000000 static
Definition at line 228 of file rng-test-suite.cc.
Referenced by ChiSquaredTest().
N_RUNS
const uint32_t RngExponentialTestCase::N_RUNS = 5 static
Definition at line 226 of file rng-test-suite.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/core/test/rng-test-suite.cc