ns-3: DsaRequestTestCase Class Reference
DsaRequestTestCase Class Reference
WiMAX Models » wimax module tests | Test suites
Test the DSA request message.
Public Member Functions
DsaRequestTestCase ()
virtual ~DsaRequestTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test the DSA request message.
Definition at line 39 of file mac-messages-test.cc.
Constructor & Destructor Documentation
DsaRequestTestCase()
DsaRequestTestCase::DsaRequestTestCase ()
Definition at line 50 of file mac-messages-test.cc.
~DsaRequestTestCase()
DsaRequestTestCase::~DsaRequestTestCase () virtual
Definition at line 55 of file mac-messages-test.cc.
Member Function Documentation
DoRun()
void DsaRequestTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 60 of file mac-messages-test.cc.
References ns3::Packet::AddHeader(), ns3::ServiceFlow::GetCsSpecification(), ns3::ServiceFlow::GetDirection(), ns3::ServiceFlow::GetMaximumLatency(), ns3::ServiceFlow::GetMaxSustainedTrafficRate(), ns3::ServiceFlow::GetMaxTrafficBurst(), ns3::ServiceFlow::GetMinReservedTrafficRate(), ns3::ServiceFlow::GetMinTolerableTrafficRate(), ns3::DsaReq::GetServiceFlow(), ns3::ServiceFlow::GetServiceSchedulingType(), ns3::ServiceFlow::GetSfid(), ns3::ServiceFlow::GetTrafficPriority(), ns3::IPV4, NS_TEST_ASSERT_MSG_EQ, ns3::Packet::RemoveHeader(), ns3::ServiceFlow::SetConvergenceSublayerParam(), ns3::ServiceFlow::SetCsSpecification(), ns3::ServiceFlow::SetMaximumLatency(), ns3::ServiceFlow::SetMaxSustainedTrafficRate(), ns3::ServiceFlow::SetMaxTrafficBurst(), ns3::ServiceFlow::SetMinReservedTrafficRate(), ns3::ServiceFlow::SetMinTolerableTrafficRate(), ns3::ServiceFlow::SetServiceSchedulingType(), ns3::ServiceFlow::SetSfid(), and ns3::ServiceFlow::SetTrafficPriority().
The documentation for this class was generated from the following file:
src/wimax/test/mac-messages-test.cc