ns-3: ParabolicAntennaModelTestCase Class Reference
ParabolicAntennaModelTestCase Class Reference
Public Member Functions
ParabolicAntennaModelTestCase (Angles a, double b, double o, double g, double expectedGainDb, ParabolicAntennaModelGainTestCondition cond)
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Static Public Member Functions
static std::string BuildNameString (Angles a, double b, double o, double g)
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
Angles m_a
double m_b
ParabolicAntennaModelGainTestCondition m_cond
double m_expectedGain
double m_g
double m_o
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 41 of file test-parabolic-antenna.cc.
Constructor & Destructor Documentation
ParabolicAntennaModelTestCase()
ParabolicAntennaModelTestCase::ParabolicAntennaModelTestCase (Angles a, double b, double o, double g, double expectedGainDb, ParabolicAntennaModelGainTestCondition cond)
Definition at line 70 of file test-parabolic-antenna.cc.
Member Function Documentation
BuildNameString()
std::string ParabolicAntennaModelTestCase::BuildNameString (Angles a, double b, double o, double g) static
Definition at line 59 of file test-parabolic-antenna.cc.
References ns3::Angles::phi, and ns3::Angles::theta.
Referenced by DoRun().
DoRun()
void ParabolicAntennaModelTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 82 of file test-parabolic-antenna.cc.
References BuildNameString(), EQUAL, ns3::ParabolicAntennaModel::GetGainDb(), LESSTHAN, m_a, m_b, m_cond, m_expectedGain, m_g, m_o, NS_LOG_FUNCTION, NS_TEST_EXPECT_MSG_EQ_TOL, NS_TEST_EXPECT_MSG_LT, and ns3::ObjectBase::SetAttribute().
Member Data Documentation
m_a
Angles ParabolicAntennaModelTestCase::m_a private
Definition at line 51 of file test-parabolic-antenna.cc.
Referenced by DoRun().
m_b
double ParabolicAntennaModelTestCase::m_b private
Definition at line 52 of file test-parabolic-antenna.cc.
Referenced by DoRun().
m_cond
ParabolicAntennaModelGainTestCondition ParabolicAntennaModelTestCase::m_cond private
Definition at line 56 of file test-parabolic-antenna.cc.
Referenced by DoRun().
m_expectedGain
double ParabolicAntennaModelTestCase::m_expectedGain private
Definition at line 55 of file test-parabolic-antenna.cc.
Referenced by DoRun().
m_g
double ParabolicAntennaModelTestCase::m_g private
Definition at line 54 of file test-parabolic-antenna.cc.
Referenced by DoRun().
m_o
double ParabolicAntennaModelTestCase::m_o private
Definition at line 53 of file test-parabolic-antenna.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/antenna/test/test-parabolic-antenna.cc