ns-3: ns3::EpsBearerTag Class Reference
ns3::EpsBearerTag Class Reference
Tag used to define the RNTI and EPS bearer ID for packets interchanged between the EpcEnbApplication and the LteEnbNetDevice.
#include "eps-bearer-tag.h"
Public Member Functions
EpsBearerTag ()
Create an empty EpsBearerTag.
EpsBearerTag (uint16_t rnti, uint8_t bid)
Create a EpsBearerTag with the given RNTI and bearer id.
virtual void Deserialize (TagBuffer i)
uint8_t GetBid (void) const
Get Bearer Id function.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint16_t GetRnti (void) const
Get RNTI function.
virtual uint32_t GetSerializedSize () const
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer i) const
void SetBid (uint8_t bid)
Set the bearer id to the given value.
void SetRnti (uint16_t rnti)
Set the RNTI to the given value.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_bid
Bearer Id value.
uint16_t m_rnti
RNTI value.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Tag used to define the RNTI and EPS bearer ID for packets interchanged between the EpcEnbApplication and the LteEnbNetDevice.
Definition at line 36 of file eps-bearer-tag.h.
Constructor & Destructor Documentation
EpsBearerTag() [1/2]
ns3::EpsBearerTag::EpsBearerTag ()
Create an empty EpsBearerTag.
Definition at line 56 of file eps-bearer-tag.cc.
EpsBearerTag() [2/2]
ns3::EpsBearerTag::EpsBearerTag (uint16_t rnti, uint8_t bid)
Create a EpsBearerTag with the given RNTI and bearer id.
Parameters
rnti the value of the RNTI to set
bid the value of the Bearer Id to set
Definition at line 61 of file eps-bearer-tag.cc.
Member Function Documentation
Deserialize()
void ns3::EpsBearerTag::Deserialize (TagBuffer i) virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 93 of file eps-bearer-tag.cc.
References m_bid, m_rnti, ns3::TagBuffer::ReadU16(), and ns3::TagBuffer::ReadU8().
GetBid()
uint8_t ns3::EpsBearerTag::GetBid (void) const
Get Bearer Id function.
Returns
the Bearer Id
Definition at line 106 of file eps-bearer-tag.cc.
References m_bid.
Referenced by GetTypeId(), ns3::EpcEnbApplication::RecvFromLteSocket(), and ns3::LteEnbRrc::SendData().
GetInstanceTypeId()
TypeId ns3::EpsBearerTag::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 51 of file eps-bearer-tag.cc.
References GetTypeId().
GetRnti()
uint16_t ns3::EpsBearerTag::GetRnti (void) const
Get RNTI function.
Returns
the RNTI
Definition at line 100 of file eps-bearer-tag.cc.
References m_rnti.
Referenced by GetTypeId(), ns3::EpcEnbApplication::RecvFromLteSocket(), and ns3::LteEnbRrc::SendData().
GetSerializedSize()
uint32_t ns3::EpsBearerTag::GetSerializedSize () const virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 80 of file eps-bearer-tag.cc.
GetTypeId()
TypeId ns3::EpsBearerTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 32 of file eps-bearer-tag.cc.
References GetBid(), GetRnti(), ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::EpsBearerTag::Print (std::ostream & os) const virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 112 of file eps-bearer-tag.cc.
References m_bid, and m_rnti.
Serialize()
void ns3::EpsBearerTag::Serialize (TagBuffer i) const virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 86 of file eps-bearer-tag.cc.
References m_bid, m_rnti, ns3::TagBuffer::WriteU16(), and ns3::TagBuffer::WriteU8().
SetBid()
void ns3::EpsBearerTag::SetBid (uint8_t bid)
Set the bearer id to the given value.
Parameters
bid the value of the Bearer Id to set
Definition at line 74 of file eps-bearer-tag.cc.
References m_bid.
Referenced by ns3::UeManager::DoReceivePdcpSdu().
SetRnti()
void ns3::EpsBearerTag::SetRnti (uint16_t rnti)
Set the RNTI to the given value.
Parameters
rnti the value of the RNTI to set
Definition at line 68 of file eps-bearer-tag.cc.
References m_rnti.
Referenced by ns3::UeManager::DoReceivePdcpSdu().
Member Data Documentation
m_bid
uint8_t ns3::EpsBearerTag::m_bid private
Bearer Id value.
Definition at line 91 of file eps-bearer-tag.h.
Referenced by Deserialize(), GetBid(), Print(), Serialize(), and SetBid().
m_rnti
uint16_t ns3::EpsBearerTag::m_rnti private
RNTI value.
Definition at line 90 of file eps-bearer-tag.h.
Referenced by Deserialize(), GetRnti(), Print(), Serialize(), and SetRnti().
The documentation for this class was generated from the following files:
src/lte/model/eps-bearer-tag.h
src/lte/model/eps-bearer-tag.cc