ns-3: ns3::GnuplotDataset Class Reference
ns3::GnuplotDataset Class Reference
Statistics » Gnuplot
Abstract class to store a plot line to be used by ns3::Gnuplot.
#include "gnuplot.h"
Classes
struct Data
Public Member Functions
GnuplotDataset (const GnuplotDataset &original)
Reference-counting copy constructor.
~GnuplotDataset ()
Reference-counting destructor.
GnuplotDataset & operator= (const GnuplotDataset &original)
Reference-counting assignment operator.
void SetExtra (const std::string &extra)
Add extra formatting parameters to this dataset.
void SetTitle (const std::string &title)
Change line title.
Static Public Member Functions
static void SetDefaultExtra (const std::string &extra)
Change extra formatting style parameters for newly created objects.
Protected Member Functions
GnuplotDataset (struct Data *data)
Called by constructors of derived classes.
Protected Attributes
struct Data * m_data
Reference counted data object.
Static Protected Attributes
static std::string m_defaultExtra = ""
Extra gnuplot parameters set on every newly created dataset.
Friends
class Gnuplot
Friend because it accesses m_data and it's virtual functions directly in GenerateOutput().
Detailed Description
Abstract class to store a plot line to be used by ns3::Gnuplot.
This class contains a reference counted data object in m_data. The data object contains different structs derived from struct Data by subclasses.
Definition at line 38 of file gnuplot.h.
Constructor & Destructor Documentation
GnuplotDataset() [1/2]
ns3::GnuplotDataset::GnuplotDataset (const GnuplotDataset & original)
Reference-counting copy constructor.
Parameters
original Original GnuPlotDataset
Definition at line 115 of file gnuplot.cc.
References m_data, and ns3::GnuplotDataset::Data::m_references.
~GnuplotDataset()
ns3::GnuplotDataset::~GnuplotDataset ()
Reference-counting destructor.
Definition at line 121 of file gnuplot.cc.
References m_data, and ns3::GnuplotDataset::Data::m_references.
GnuplotDataset() [2/2]
ns3::GnuplotDataset::GnuplotDataset (struct Data * data) protected
Called by constructors of derived classes.
Parameters
data the reference counted data object representing this dataset.
Definition at line 110 of file gnuplot.cc.
Member Function Documentation
operator=()
GnuplotDataset & ns3::GnuplotDataset::operator= (const GnuplotDataset & original)
Reference-counting assignment operator.
Parameters
original Right-hand side of assignment operator
Returns
Copy of original GnuplotDataset
Definition at line 127 of file gnuplot.cc.
References m_data, and ns3::GnuplotDataset::Data::m_references.
SetDefaultExtra()
void ns3::GnuplotDataset::SetDefaultExtra (const std::string & extra) static
Change extra formatting style parameters for newly created objects.
Parameters
extra extra formatting
Definition at line 147 of file gnuplot.cc.
References m_defaultExtra.
Referenced by ns3::GnuplotAggregator::Set2dDatasetDefaultExtra().
SetExtra()
void ns3::GnuplotDataset::SetExtra (const std::string & extra)
Add extra formatting parameters to this dataset.
Parameters
extra extra formatting
Definition at line 152 of file gnuplot.cc.
References m_data, and ns3::GnuplotDataset::Data::m_extra.
Referenced by TestProbabilistic().
SetTitle()
void ns3::GnuplotDataset::SetTitle (const std::string & title)
Change line title.
Parameters
title the new title string to use for this dataset.
Note
If you want your title to contain a newline character, escape it like this: "First line\\nSecond line" so that it is converted to "First line\nSecond line" in the plot file.
Definition at line 141 of file gnuplot.cc.
References m_data, and ns3::GnuplotDataset::Data::m_title.
Referenced by anonymous_namespace{gnuplot-example.cc}::Create2DPlotFile(), anonymous_namespace{gnuplot-example.cc}::Create2DPlotWithErrorBarsFile(), anonymous_namespace{gnuplot-example.cc}::Create3DPlotFile(), TestDeterministic(), TestDeterministicByTime(), and TestProbabilistic().
Friends And Related Function Documentation
Gnuplot
friend class Gnuplot friend
Friend because it accesses m_data and it's virtual functions directly in GenerateOutput().
Definition at line 86 of file gnuplot.h.
Member Data Documentation
m_data
struct Data* ns3::GnuplotDataset::m_data protected
Reference counted data object.
Definition at line 107 of file gnuplot.h.
Referenced by GnuplotDataset(), ~GnuplotDataset(), ns3::Gnuplot2dDataset::Add(), ns3::Gnuplot3dDataset::Add(), ns3::Gnuplot2dDataset::AddEmptyLine(), ns3::Gnuplot3dDataset::AddEmptyLine(), operator=(), ns3::Gnuplot2dDataset::SetErrorBars(), SetExtra(), ns3::Gnuplot2dFunction::SetFunction(), ns3::Gnuplot3dFunction::SetFunction(), ns3::Gnuplot3dDataset::SetStyle(), ns3::Gnuplot2dDataset::SetStyle(), and SetTitle().
m_defaultExtra
std::string ns3::GnuplotDataset::m_defaultExtra = "" static protected
Extra gnuplot parameters set on every newly created dataset.
Definition at line 91 of file gnuplot.h.
Referenced by SetDefaultExtra().
The documentation for this class was generated from the following files:
src/stats/model/gnuplot.h
src/stats/model/gnuplot.cc