ns-3: ns3::Ipv4FlowProbeTag Class Reference
ns3::Ipv4FlowProbeTag Class Reference
Flow Monitor
Tag used to allow a fast identification of the packet.
Public Member Functions
Ipv4FlowProbeTag ()
Ipv4FlowProbeTag (uint32_t flowId, uint32_t packetId, uint32_t packetSize, Ipv4Address src, Ipv4Address dst)
Consructor.
virtual void Deserialize (TagBuffer buf)
uint32_t GetFlowId (void) const
Set the flow identifier.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint32_t GetPacketId (void) const
Set the packet identifier.
uint32_t GetPacketSize (void) const
Get the packet size.
virtual uint32_t GetSerializedSize (void) const
bool IsSrcDstValid (Ipv4Address src, Ipv4Address dst) const
Checks if the addresses stored in tag are matching the arguments.
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer buf) const
void SetFlowId (uint32_t flowId)
Set the flow identifier.
void SetPacketId (uint32_t packetId)
Set the packet identifier.
void SetPacketSize (uint32_t packetSize)
Set the packet size.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Ipv4Address m_dst
IP destination.
uint32_t m_flowId
flow identifier
uint32_t m_packetId
packet identifier
uint32_t m_packetSize
packet size
Ipv4Address m_src
IP source.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Tag used to allow a fast identification of the packet.
This tag is added by FlowMonitor when a packet is seen for the first time, and it is then used to classify the packet in the following hops.
Definition at line 48 of file ipv4-flow-probe.cc.
Constructor & Destructor Documentation
Ipv4FlowProbeTag() [1/2]
ns3::Ipv4FlowProbeTag::Ipv4FlowProbeTag ()
Definition at line 173 of file ipv4-flow-probe.cc.
Ipv4FlowProbeTag() [2/2]
ns3::Ipv4FlowProbeTag::Ipv4FlowProbeTag (uint32_t flowId, uint32_t packetId, uint32_t packetSize, Ipv4Address src, Ipv4Address dst)
Consructor.
Parameters
flowId the flow identifier
packetId the packet identifier
packetSize the packet size
src packet source address
dst packet destination address
Definition at line 178 of file ipv4-flow-probe.cc.
Member Function Documentation
Deserialize()
void ns3::Ipv4FlowProbeTag::Deserialize (TagBuffer i) virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 154 of file ipv4-flow-probe.cc.
References ns3::Ipv4Address::Deserialize(), m_dst, m_flowId, m_packetId, m_packetSize, m_src, ns3::TagBuffer::Read(), and ns3::TagBuffer::ReadU32().
GetFlowId()
uint32_t ns3::Ipv4FlowProbeTag::GetFlowId (void) const
Set the flow identifier.
Returns
the flow identifier
Definition at line 199 of file ipv4-flow-probe.cc.
References m_flowId.
Referenced by ns3::Ipv4FlowProbe::DropLogger(), ns3::Ipv4FlowProbe::ForwardLogger(), ns3::Ipv4FlowProbe::ForwardUpLogger(), ns3::Ipv4FlowProbe::QueueDiscDropLogger(), and ns3::Ipv4FlowProbe::QueueDropLogger().
GetInstanceTypeId()
TypeId ns3::Ipv4FlowProbeTag::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 131 of file ipv4-flow-probe.cc.
References GetTypeId().
GetPacketId()
uint32_t ns3::Ipv4FlowProbeTag::GetPacketId (void) const
Set the packet identifier.
Returns
the packet identifier
Definition at line 204 of file ipv4-flow-probe.cc.
References m_packetId.
Referenced by ns3::Ipv4FlowProbe::DropLogger(), ns3::Ipv4FlowProbe::ForwardLogger(), ns3::Ipv4FlowProbe::ForwardUpLogger(), ns3::Ipv4FlowProbe::QueueDiscDropLogger(), and ns3::Ipv4FlowProbe::QueueDropLogger().
GetPacketSize()
uint32_t ns3::Ipv4FlowProbeTag::GetPacketSize (void) const
Get the packet size.
Returns
the packet size
Definition at line 209 of file ipv4-flow-probe.cc.
References m_packetSize.
Referenced by ns3::Ipv4FlowProbe::QueueDiscDropLogger(), and ns3::Ipv4FlowProbe::QueueDropLogger().
GetSerializedSize()
uint32_t ns3::Ipv4FlowProbeTag::GetSerializedSize (void) const virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 136 of file ipv4-flow-probe.cc.
GetTypeId()
TypeId ns3::Ipv4FlowProbeTag::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 121 of file ipv4-flow-probe.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
IsSrcDstValid()
bool ns3::Ipv4FlowProbeTag::IsSrcDstValid (Ipv4Address src, Ipv4Address dst) const
Checks if the addresses stored in tag are matching the arguments.
This check is important for IP over IP encapsulation.
Parameters
src Source address.
dst Destination address.
Returns
True if the addresses are matching.
Definition at line 214 of file ipv4-flow-probe.cc.
References m_dst, and m_src.
Referenced by ns3::Ipv4FlowProbe::ForwardLogger(), and ns3::Ipv4FlowProbe::ForwardUpLogger().
Print()
void ns3::Ipv4FlowProbeTag::Print (std::ostream & os) const virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 167 of file ipv4-flow-probe.cc.
References m_flowId, m_packetId, and m_packetSize.
Serialize()
void ns3::Ipv4FlowProbeTag::Serialize (TagBuffer i) const virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 141 of file ipv4-flow-probe.cc.
References m_dst, m_flowId, m_packetId, m_packetSize, m_src, ns3::Ipv4Address::Serialize(), ns3::TagBuffer::Write(), and ns3::TagBuffer::WriteU32().
SetFlowId()
void ns3::Ipv4FlowProbeTag::SetFlowId (uint32_t flowId)
Set the flow identifier.
Parameters
flowId the flow identifier
Definition at line 184 of file ipv4-flow-probe.cc.
References m_flowId.
SetPacketId()
void ns3::Ipv4FlowProbeTag::SetPacketId (uint32_t packetId)
Set the packet identifier.
Parameters
packetId the packet identifier
Definition at line 189 of file ipv4-flow-probe.cc.
References m_packetId.
SetPacketSize()
void ns3::Ipv4FlowProbeTag::SetPacketSize (uint32_t packetSize)
Set the packet size.
Parameters
packetSize the packet size
Definition at line 194 of file ipv4-flow-probe.cc.
References m_packetSize.
Member Data Documentation
m_dst
Ipv4Address ns3::Ipv4FlowProbeTag::m_dst private
IP destination.
Definition at line 117 of file ipv4-flow-probe.cc.
Referenced by Deserialize(), IsSrcDstValid(), and Serialize().
m_flowId
uint32_t ns3::Ipv4FlowProbeTag::m_flowId private
flow identifier
Definition at line 113 of file ipv4-flow-probe.cc.
Referenced by Deserialize(), GetFlowId(), Print(), Serialize(), and SetFlowId().
m_packetId
uint32_t ns3::Ipv4FlowProbeTag::m_packetId private
packet identifier
Definition at line 114 of file ipv4-flow-probe.cc.
Referenced by Deserialize(), GetPacketId(), Print(), Serialize(), and SetPacketId().
m_packetSize
uint32_t ns3::Ipv4FlowProbeTag::m_packetSize private
packet size
Definition at line 115 of file ipv4-flow-probe.cc.
Referenced by Deserialize(), GetPacketSize(), Print(), Serialize(), and SetPacketSize().
m_src
Ipv4Address ns3::Ipv4FlowProbeTag::m_src private
IP source.
Definition at line 116 of file ipv4-flow-probe.cc.
Referenced by Deserialize(), IsSrcDstValid(), and Serialize().
The documentation for this class was generated from the following file:
src/flow-monitor/model/ipv4-flow-probe.cc