ns-3: ns3::lorawan::NwkAddr Class Reference
ns3::lorawan::NwkAddr Class Reference
Class representing the Network Address component of a LoraDeviceAddress (25 bits)
#include "lora-device-address.h"
Public Member Functions
NwkAddr (uint32_t nwkId=0)
uint32_t Get (void) const
Get an uint32_t representation of the 25-bit network address.
void Set (uint32_t nwkAddr)
Set the NwkAddr, starting from a 32-bit representation of a 25-bit integer.
Private Attributes
uint32_t m_nwkAddr
8-bit integer representation of the network id
Detailed Description
Class representing the Network Address component of a LoraDeviceAddress (25 bits)
Definition at line 64 of file lora-device-address.h.
Constructor & Destructor Documentation
NwkAddr()
ns3::lorawan::NwkAddr::NwkAddr (uint32_t nwkId = 0)
Definition at line 57 of file lora-device-address.cc.
Member Function Documentation
Get()
uint32_t ns3::lorawan::NwkAddr::Get (void) const
Get an uint32_t representation of the 25-bit network address.
Returns
The Network Address.
Definition at line 73 of file lora-device-address.cc.
References m_nwkAddr.
Referenced by ns3::lorawan::LoraDeviceAddress::LoraDeviceAddress(), ns3::lorawan::LoraDeviceAddress::Get(), ns3::lorawan::LoraDeviceAddressGenerator::GetNextAddress(), ns3::lorawan::LoraDeviceAddress::GetNwkAddr(), ns3::lorawan::LoraDeviceAddressGenerator::NextAddress(), and ns3::lorawan::LoraDeviceAddress::Print().
Set()
void ns3::lorawan::NwkAddr::Set (uint32_t nwkAddr)
Set the NwkAddr, starting from a 32-bit representation of a 25-bit integer.
This method will ignore the most significant bits of the argument. This means that all arguments such that nwkAddr > 2^25 will actually be considered as nwkAddr mod 2^25.
Parameters
nwkAddr The Network Address to set.
Definition at line 62 of file lora-device-address.cc.
References m_nwkAddr, and NS_LOG_WARN.
Referenced by ns3::lorawan::LoraDeviceAddress::LoraDeviceAddress(), ns3::lorawan::LoraDeviceAddressGenerator::LoraDeviceAddressGenerator(), ns3::lorawan::LoraDeviceAddressGenerator::NextAddress(), ns3::lorawan::LoraDeviceAddressGenerator::NextNetwork(), ns3::lorawan::LoraDeviceAddress::Set(), and ns3::lorawan::LoraDeviceAddress::SetNwkAddr().
Member Data Documentation
m_nwkAddr
uint32_t ns3::lorawan::NwkAddr::m_nwkAddr private
8-bit integer representation of the network id
Definition at line 88 of file lora-device-address.h.
Referenced by Get(), and Set().
The documentation for this class was generated from the following files:
src/lorawan/model/lora-device-address.h
src/lorawan/model/lora-device-address.cc