ns-3: LteEpcE2eDataTestCase Class Reference
LteEpcE2eDataTestCase Class Reference
LTE Models » lte module tests | Test suites
Test that e2e packet flow is correct. Compares the data send and the data received. Test uses mostly the PDCP stats to check the performance.
Public Member Functions
LteEpcE2eDataTestCase (std::string name, std::vector< EnbTestData > v)
Constructor.
virtual ~LteEpcE2eDataTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
std::vector< EnbTestData > m_enbTestData
the ENB test data
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test that e2e packet flow is correct. Compares the data send and the data received. Test uses mostly the PDCP stats to check the performance.
Definition at line 108 of file test-lte-epc-e2e-data.cc.
Constructor & Destructor Documentation
LteEpcE2eDataTestCase()
LteEpcE2eDataTestCase::LteEpcE2eDataTestCase (std::string name, std::vector< EnbTestData > v)
Constructor.
Parameters
name the reference name
v the ENB test data
Definition at line 126 of file test-lte-epc-e2e-data.cc.
References NS_LOG_FUNCTION.
~LteEpcE2eDataTestCase()
LteEpcE2eDataTestCase::~LteEpcE2eDataTestCase () virtual
Definition at line 133 of file test-lte-epc-e2e-data.cc.
Member Function Documentation
DoRun()
void LteEpcE2eDataTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 138 of file test-lte-epc-e2e-data.cc.
References ns3::LteHelper::ActivateDedicatedEpsBearer(), ns3::EpcTft::Add(), ns3::Ipv4StaticRouting::AddNetworkRouteTo(), ns3::Ipv4AddressHelper::Assign(), ns3::NoBackhaulEpcHelper::AssignUeIpv4Address(), ns3::LteHelper::Attach(), ns3::NetDeviceContainer::Begin(), ns3::NodeContainer::Create(), ns3::TestCase::CreateTempDirFilename(), BearerTestData::dlClientApp, BearerTestData::dlServerApp, ns3::LteHelper::EnablePdcpTraces(), ns3::NetDeviceContainer::End(), ns3::ApplicationContainer::Get(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::NodeContainer::GetN(), ns3::TestCase::GetName(), ns3::Object::GetObject(), ns3::LteHelper::GetPdcpStats(), ns3::NoBackhaulEpcHelper::GetPgwNode(), GetPosition(), ns3::Ipv4StaticRoutingHelper::GetStaticRouting(), ns3::NoBackhaulEpcHelper::GetUeDefaultGatewayAddress(), ns3::PointToPointHelper::Install(), ns3::PacketSinkHelper::Install(), ns3::MobilityHelper::Install(), ns3::InternetStackHelper::Install(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), BearerTestData::interPacketInterval, ns3::EpcTft::PacketFilter::localPortEnd, ns3::EpcTft::PacketFilter::localPortStart, m_enbTestData, NS_ABORT_IF, NS_LOG_FUNCTION, NS_TEST_ASSERT_MSG_EQ, BearerTestData::numPkts, BearerTestData::pktSize, ns3::EpcTft::PacketFilter::remotePortEnd, ns3::EpcTft::PacketFilter::remotePortStart, ns3::Config::Reset(), ns3::Seconds(), ns3::Config::Set(), ns3::ObjectBase::SetAttribute(), ns3::Ipv4AddressHelper::SetBase(), ns3::PointToPointHelper::SetChannelAttribute(), ns3::Config::SetDefault(), ns3::Ipv4StaticRouting::SetDefaultRoute(), ns3::PointToPointHelper::SetDeviceAttribute(), ns3::LteHelper::SetEpcHelper(), ns3::MobilityHelper::SetMobilityModel(), ns3::MobilityHelper::SetPositionAllocator(), ns3::ApplicationContainer::Start(), BearerTestData::ulClientApp, and BearerTestData::ulServerApp.
Member Data Documentation
m_enbTestData
std::vector<EnbTestData> LteEpcE2eDataTestCase::m_enbTestData private
the ENB test data
Definition at line 122 of file test-lte-epc-e2e-data.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/lte/test/test-lte-epc-e2e-data.cc