ns-3: ns3::lorawan::LorawanMac Class Reference
ns3::lorawan::LorawanMac Class Reference abstract
Class representing the LoRaWAN MAC layer.
#include "lorawan-mac.h"
Public Types
typedef std::array< std::array< uint8_t, 6 >, 8 > ReplyDataRateMatrix
Public Member Functions
LorawanMac ()
virtual ~LorawanMac ()
virtual void FailedReception (Ptr< Packet const > packet)=0
Function called by lower layers to inform this layer that reception of a packet we were locked on failed.
double GetBandwidthFromDataRate (uint8_t dataRate)
Get the BW corresponding to a data rate, based on this MAC's region.
double GetDbmForTxPower (uint8_t txPower)
Get the transmission power in dBm that corresponds, in this region, to the encoded 8-bit txPower.
Ptr< NetDevice > GetDevice (void)
Get the device this MAC layer is installed on.
LogicalLoraChannelHelper GetLogicalLoraChannelHelper (void)
Get the logical lora channel helper associated with this MAC.
int GetNPreambleSymbols (void)
Get the number of PHY preamble symbols this MAC is set to use.
Ptr< LoraPhy > GetPhy (void)
Get the underlying PHY layer.
uint8_t GetSfFromDataRate (uint8_t dataRate)
Get the SF corresponding to a data rate, based on this MAC's region.
virtual void Receive (Ptr< Packet const > packet)=0
Receive a packet from the lower layer.
virtual void Send (Ptr< Packet > packet)=0
Send a packet.
void SetBandwidthForDataRate (std::vector< double > bandwidthForDataRate)
Set the vector to use to check up correspondence between bandwidth and DataRate.
void SetDevice (Ptr< NetDevice > device)
Set the device this MAC layer is installed on.
void SetLogicalLoraChannelHelper (LogicalLoraChannelHelper helper)
Set the LogicalLoraChannelHelper this MAC instance will use.
void SetMaxAppPayloadForDataRate (std::vector< uint32_t > maxAppPayloadForDataRate)
Set the maximum App layer payload for a set DataRate.
void SetNPreambleSymbols (int nPreambleSymbols)
Set the number of PHY preamble symbols this MAC is set to use.
void SetPhy (Ptr< LoraPhy > phy)
Set the underlying PHY layer.
void SetReplyDataRateMatrix (ReplyDataRateMatrix replyDataRateMatrix)
Set the matrix to use when deciding with which DataRate to respond.
void SetSfForDataRate (std::vector< uint8_t > sfForDataRate)
Set the vector to use to check up correspondence between SF and DataRate.
void SetTxDbmForTxPower (std::vector< double > txDbmForTxPower)
Set the vector to use to check up which transmission power in Dbm corresponds to a certain TxPower value in this MAC's region.
virtual void TxFinished (Ptr< const Packet > packet)=0
Perform actions after sending a packet.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Attributes
std::vector< double > m_bandwidthForDataRate
A vector holding the bandwidth each Data Rate corresponds to.
TracedCallback< Ptr< const Packet > > m_cannotSendBecauseDutyCycle
The trace source that is fired when a packet cannot be sent because of duty cycle limitations.
LogicalLoraChannelHelper m_channelHelper
The LogicalLoraChannelHelper instance that is assigned to this MAC.
Ptr< NetDevice > m_device
The device this MAC layer is installed on.
std::vector< uint32_t > m_maxAppPayloadForDataRate
A vector holding the maximum app payload size that corresponds to a certain DataRate.
int m_nPreambleSymbols
The number of symbols to use in the PHY preamble.
Ptr< LoraPhy > m_phy
The PHY instance that sits under this MAC layer.
TracedCallback< Ptr< const Packet > > m_receivedPacket
Trace source that is fired when a packet reaches the MAC layer.
ReplyDataRateMatrix m_replyDataRateMatrix
The matrix that decides the DR the GW will use in a reply based on the ED's sending DR and on the value of the RX1DROffset parameter.
TracedCallback< Ptr< Packet const > > m_sentNewPacket
Trace source that is fired when a new APP layer packet arrives at the MAC layer.
std::vector< uint8_t > m_sfForDataRate
A vector holding the SF each Data Rate corresponds to.
std::vector< double > m_txDbmForTxPower
A vector holding the power that corresponds to a certain TxPower value.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Class representing the LoRaWAN MAC layer.
This class is meant to be extended differently based on whether the layer belongs to an End Device or a Gateway, while holding some functionality that is common to both.
Definition at line 42 of file lorawan-mac.h.
Member Typedef Documentation
ReplyDataRateMatrix
typedef std::array<std::array<uint8_t, 6>, 8> ns3::lorawan::LorawanMac::ReplyDataRateMatrix
Definition at line 50 of file lorawan-mac.h.
Constructor & Destructor Documentation
LorawanMac()
ns3::lorawan::LorawanMac::LorawanMac ()
Definition at line 55 of file lorawan-mac.cc.
References NS_LOG_FUNCTION.
~LorawanMac()
ns3::lorawan::LorawanMac::~LorawanMac () virtual
Definition at line 60 of file lorawan-mac.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
FailedReception()
virtual void ns3::lorawan::LorawanMac::FailedReception (Ptr< Packet const > packet) pure virtual
Function called by lower layers to inform this layer that reception of a packet we were locked on failed.
Parameters
packet the packet we failed to receive
Implemented in ns3::lorawan::GatewayLorawanMac, ns3::lorawan::EndDeviceLorawanMac, and ns3::lorawan::ClassAEndDeviceLorawanMac.
Referenced by SetPhy().
GetBandwidthFromDataRate()
double ns3::lorawan::LorawanMac::GetBandwidthFromDataRate (uint8_t dataRate)
Get the BW corresponding to a data rate, based on this MAC's region.
Parameters
dataRate The Data Rate we need to convert to a bandwidth value.
Returns
The bandwidth that corresponds to the parameter Data Rate in this MAC's region, or 0 if the dataRate is not valid.
Definition at line 122 of file lorawan-mac.cc.
References m_bandwidthForDataRate, and NS_LOG_FUNCTION.
Referenced by ns3::lorawan::ClassAEndDeviceLorawanMac::GetNextClassTransmissionDelay(), ns3::lorawan::EndDeviceLorawanMac::OnLinkAdrReq(), ns3::lorawan::ClassAEndDeviceLorawanMac::OnRxClassParamSetupReq(), ns3::lorawan::ClassAEndDeviceLorawanMac::OpenFirstReceiveWindow(), ns3::lorawan::ClassAEndDeviceLorawanMac::OpenSecondReceiveWindow(), ns3::lorawan::GatewayLorawanMac::Send(), and ns3::lorawan::ClassAEndDeviceLorawanMac::SendToPhy().
GetDbmForTxPower()
double ns3::lorawan::LorawanMac::GetDbmForTxPower (uint8_t txPower)
Get the transmission power in dBm that corresponds, in this region, to the encoded 8-bit txPower.
Parameters
txPower The 8-bit encoded txPower to convert.
Returns
The corresponding transmission power in dBm, or 0 if the encoded power was not recognized as valid.
Definition at line 136 of file lorawan-mac.cc.
References m_txDbmForTxPower, and NS_LOG_FUNCTION.
Referenced by ns3::lorawan::EndDeviceLorawanMac::OnLinkAdrReq().
GetDevice()
Ptr< NetDevice > ns3::lorawan::LorawanMac::GetDevice (void)
Get the device this MAC layer is installed on.
Returns
The NetDevice this MAC layer will refer to.
Definition at line 72 of file lorawan-mac.cc.
References m_device.
GetLogicalLoraChannelHelper()
LogicalLoraChannelHelper ns3::lorawan::LorawanMac::GetLogicalLoraChannelHelper (void)
Get the logical lora channel helper associated with this MAC.
Returns
The instance of LogicalLoraChannelHelper that this MAC is using.
Definition at line 96 of file lorawan-mac.cc.
References m_channelHelper.
GetNPreambleSymbols()
int ns3::lorawan::LorawanMac::GetNPreambleSymbols (void)
Get the number of PHY preamble symbols this MAC is set to use.
Returns
The number of preamble symbols to use (typically 8).
Definition at line 179 of file lorawan-mac.cc.
References m_nPreambleSymbols.
GetPhy()
Ptr< LoraPhy > ns3::lorawan::LorawanMac::GetPhy (void)
Get the underlying PHY layer.
Returns
The PHY layer that this MAC is connected to.
Definition at line 78 of file lorawan-mac.cc.
References m_phy.
GetSfFromDataRate()
uint8_t ns3::lorawan::LorawanMac::GetSfFromDataRate (uint8_t dataRate)
Get the SF corresponding to a data rate, based on this MAC's region.
Parameters
dataRate The Data Rate we need to convert to a Spreading Factor value.
Returns
The SF that corresponds to a Data Rate in this MAC's region, or 0 if the dataRate is not valid.
Definition at line 108 of file lorawan-mac.cc.
References m_sfForDataRate, and NS_LOG_FUNCTION.
Referenced by ns3::lorawan::ClassAEndDeviceLorawanMac::GetNextClassTransmissionDelay(), ns3::lorawan::EndDeviceLorawanMac::OnLinkAdrReq(), ns3::lorawan::ClassAEndDeviceLorawanMac::OnRxClassParamSetupReq(), ns3::lorawan::ClassAEndDeviceLorawanMac::OpenFirstReceiveWindow(), ns3::lorawan::ClassAEndDeviceLorawanMac::OpenSecondReceiveWindow(), ns3::lorawan::GatewayLorawanMac::Send(), and ns3::lorawan::ClassAEndDeviceLorawanMac::SendToPhy().
GetTypeId()
TypeId ns3::lorawan::LorawanMac::GetTypeId (void) static
Definition at line 32 of file lorawan-mac.cc.
References m_cannotSendBecauseDutyCycle, m_receivedPacket, m_sentNewPacket, ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
Receive()
virtual void ns3::lorawan::LorawanMac::Receive (Ptr< Packet const > packet) pure virtual
Receive a packet from the lower layer.
Parameters
packet the received packet
Implemented in ns3::lorawan::GatewayLorawanMac, ns3::lorawan::EndDeviceLorawanMac, and ns3::lorawan::ClassAEndDeviceLorawanMac.
Referenced by SetPhy().
Send()
virtual void ns3::lorawan::LorawanMac::Send (Ptr< Packet > packet) pure virtual
Send a packet.
Parameters
packet The packet to send.
Implemented in ns3::lorawan::GatewayLorawanMac, and ns3::lorawan::EndDeviceLorawanMac.
SetBandwidthForDataRate()
void ns3::lorawan::LorawanMac::SetBandwidthForDataRate (std::vector< double > bandwidthForDataRate)
Set the vector to use to check up correspondence between bandwidth and DataRate.
Parameters
bandwidthForDataRate A vector that contains at position i the bandwidth that should correspond to DR i in this MAC's region.
Definition at line 155 of file lorawan-mac.cc.
References m_bandwidthForDataRate.
SetDevice()
void ns3::lorawan::LorawanMac::SetDevice (Ptr< NetDevice > device)
Set the device this MAC layer is installed on.
Parameters
device The NetDevice this MAC layer will refer to.
Definition at line 66 of file lorawan-mac.cc.
References m_device.
SetLogicalLoraChannelHelper()
void ns3::lorawan::LorawanMac::SetLogicalLoraChannelHelper (LogicalLoraChannelHelper helper)
Set the LogicalLoraChannelHelper this MAC instance will use.
Parameters
helper The instance of the helper to use.
Definition at line 102 of file lorawan-mac.cc.
References m_channelHelper.
SetMaxAppPayloadForDataRate()
void ns3::lorawan::LorawanMac::SetMaxAppPayloadForDataRate (std::vector< uint32_t > maxAppPayloadForDataRate)
Set the maximum App layer payload for a set DataRate.
Parameters
maxAppPayloadForDataRate A vector that contains at position i the maximum Application layer payload that should correspond to DR i in this MAC's region.
Definition at line 161 of file lorawan-mac.cc.
References m_maxAppPayloadForDataRate.
SetNPreambleSymbols()
void ns3::lorawan::LorawanMac::SetNPreambleSymbols (int nPreambleSymbols)
Set the number of PHY preamble symbols this MAC is set to use.
Parameters
nPreambleSymbols The number of preamble symbols to use (typically 8).
Definition at line 173 of file lorawan-mac.cc.
References m_nPreambleSymbols.
SetPhy()
void ns3::lorawan::LorawanMac::SetPhy (Ptr< LoraPhy > phy)
Set the underlying PHY layer.
Parameters
phy the phy layer
Definition at line 84 of file lorawan-mac.cc.
References FailedReception(), m_phy, ns3::MakeCallback(), third::phy, Receive(), and TxFinished().
SetReplyDataRateMatrix()
void ns3::lorawan::LorawanMac::SetReplyDataRateMatrix (ReplyDataRateMatrix replyDataRateMatrix)
Set the matrix to use when deciding with which DataRate to respond.
Region based.
Parameters
replyDataRateMatrix A matrix containing the reply DataRates, based on the sending DataRate and on the value of the RX1DROffset parameter.
Definition at line 185 of file lorawan-mac.cc.
References m_replyDataRateMatrix.
SetSfForDataRate()
void ns3::lorawan::LorawanMac::SetSfForDataRate (std::vector< uint8_t > sfForDataRate)
Set the vector to use to check up correspondence between SF and DataRate.
Parameters
sfForDataRate A vector that contains at position i the SF that should correspond to DR i.
Definition at line 149 of file lorawan-mac.cc.
References m_sfForDataRate.
SetTxDbmForTxPower()
void ns3::lorawan::LorawanMac::SetTxDbmForTxPower (std::vector< double > txDbmForTxPower)
Set the vector to use to check up which transmission power in Dbm corresponds to a certain TxPower value in this MAC's region.
Parameters
txDbmForTxPower A vector that contains at position i the transmission power in dBm that should correspond to a TXPOWER value of i in this MAC's region.
Definition at line 167 of file lorawan-mac.cc.
References m_txDbmForTxPower.
TxFinished()
virtual void ns3::lorawan::LorawanMac::TxFinished (Ptr< const Packet > packet) pure virtual
Perform actions after sending a packet.
Parameters
packet The packet that just finished transmission.
Implemented in ns3::lorawan::GatewayLorawanMac, ns3::lorawan::EndDeviceLorawanMac, and ns3::lorawan::ClassAEndDeviceLorawanMac.
Referenced by SetPhy().
Member Data Documentation
m_bandwidthForDataRate
std::vector<double> ns3::lorawan::LorawanMac::m_bandwidthForDataRate protected
A vector holding the bandwidth each Data Rate corresponds to.
Definition at line 256 of file lorawan-mac.h.
Referenced by GetBandwidthFromDataRate(), and SetBandwidthForDataRate().
m_cannotSendBecauseDutyCycle
TracedCallback<Ptr<const Packet> > ns3::lorawan::LorawanMac::m_cannotSendBecauseDutyCycle protected
The trace source that is fired when a packet cannot be sent because of duty cycle limitations.
See also
class CallBackTraceSource
Definition at line 220 of file lorawan-mac.h.
Referenced by GetTypeId(), and ns3::lorawan::EndDeviceLorawanMac::Send().
m_channelHelper
LogicalLoraChannelHelper ns3::lorawan::LorawanMac::m_channelHelper protected
The LogicalLoraChannelHelper instance that is assigned to this MAC.
Definition at line 246 of file lorawan-mac.h.
Referenced by ns3::lorawan::EndDeviceLorawanMac::AddLogicalChannel(), ns3::lorawan::EndDeviceLorawanMac::AddSubBand(), ns3::lorawan::EndDeviceLorawanMac::GetChannelForTx(), GetLogicalLoraChannelHelper(), ns3::lorawan::EndDeviceLorawanMac::GetNextTransmissionDelay(), ns3::lorawan::GatewayLorawanMac::GetWaitingTime(), ns3::lorawan::EndDeviceLorawanMac::OnLinkAdrReq(), ns3::lorawan::EndDeviceLorawanMac::Send(), ns3::lorawan::GatewayLorawanMac::Send(), ns3::lorawan::ClassAEndDeviceLorawanMac::SendToPhy(), ns3::lorawan::EndDeviceLorawanMac::SetLogicalChannel(), and SetLogicalLoraChannelHelper().
m_device
Ptr<NetDevice> ns3::lorawan::LorawanMac::m_device protected
The device this MAC layer is installed on.
Definition at line 241 of file lorawan-mac.h.
Referenced by GetDevice(), ns3::lorawan::GatewayLorawanMac::Receive(), and SetDevice().
m_maxAppPayloadForDataRate
std::vector<uint32_t> ns3::lorawan::LorawanMac::m_maxAppPayloadForDataRate protected
A vector holding the maximum app payload size that corresponds to a certain DataRate.
Definition at line 262 of file lorawan-mac.h.
Referenced by ns3::lorawan::EndDeviceLorawanMac::Send(), and SetMaxAppPayloadForDataRate().
m_nPreambleSymbols
int ns3::lorawan::LorawanMac::m_nPreambleSymbols protected
The number of symbols to use in the PHY preamble.
Definition at line 267 of file lorawan-mac.h.
Referenced by GetNPreambleSymbols(), ns3::lorawan::ClassAEndDeviceLorawanMac::SendToPhy(), and SetNPreambleSymbols().
m_phy
Ptr<LoraPhy> ns3::lorawan::LorawanMac::m_phy protected
The PHY instance that sits under this MAC layer.
Definition at line 236 of file lorawan-mac.h.
Referenced by ns3::lorawan::ClassAEndDeviceLorawanMac::CloseFirstReceiveWindow(), ns3::lorawan::ClassAEndDeviceLorawanMac::CloseSecondReceiveWindow(), ns3::lorawan::ClassAEndDeviceLorawanMac::FailedReception(), GetPhy(), ns3::lorawan::GatewayLorawanMac::IsTransmitting(), ns3::lorawan::ClassAEndDeviceLorawanMac::OpenFirstReceiveWindow(), ns3::lorawan::ClassAEndDeviceLorawanMac::OpenSecondReceiveWindow(), ns3::lorawan::ClassAEndDeviceLorawanMac::Receive(), ns3::lorawan::GatewayLorawanMac::Send(), ns3::lorawan::ClassAEndDeviceLorawanMac::SendToPhy(), SetPhy(), and ns3::lorawan::ClassAEndDeviceLorawanMac::TxFinished().
m_receivedPacket
TracedCallback<Ptr<const Packet> > ns3::lorawan::LorawanMac::m_receivedPacket protected
Trace source that is fired when a packet reaches the MAC layer.
Definition at line 225 of file lorawan-mac.h.
Referenced by GetTypeId(), ns3::lorawan::ClassAEndDeviceLorawanMac::Receive(), and ns3::lorawan::GatewayLorawanMac::Receive().
m_replyDataRateMatrix
ReplyDataRateMatrix ns3::lorawan::LorawanMac::m_replyDataRateMatrix protected
The matrix that decides the DR the GW will use in a reply based on the ED's sending DR and on the value of the RX1DROffset parameter.
Definition at line 278 of file lorawan-mac.h.
Referenced by ns3::lorawan::ClassAEndDeviceLorawanMac::GetFirstReceiveWindowDataRate(), and SetReplyDataRateMatrix().
m_sentNewPacket
TracedCallback<Ptr<Packet const> > ns3::lorawan::LorawanMac::m_sentNewPacket protected
Trace source that is fired when a new APP layer packet arrives at the MAC layer.
Definition at line 231 of file lorawan-mac.h.
Referenced by ns3::lorawan::EndDeviceLorawanMac::DoSend(), GetTypeId(), and ns3::lorawan::GatewayLorawanMac::Send().
m_sfForDataRate
std::vector<uint8_t> ns3::lorawan::LorawanMac::m_sfForDataRate protected
A vector holding the SF each Data Rate corresponds to.
Definition at line 251 of file lorawan-mac.h.
Referenced by GetSfFromDataRate(), and SetSfForDataRate().
m_txDbmForTxPower
std::vector<double> ns3::lorawan::LorawanMac::m_txDbmForTxPower protected
A vector holding the power that corresponds to a certain TxPower value.
Definition at line 272 of file lorawan-mac.h.
Referenced by GetDbmForTxPower(), and SetTxDbmForTxPower().
The documentation for this class was generated from the following files:
src/lorawan/model/lorawan-mac.h
src/lorawan/model/lorawan-mac.cc