ns-3: ns3::dsr::DsrOptionRrepHeader Class Reference
ns3::dsr::DsrOptionRrepHeader Class Reference
DSR Routing
Route Reply (RREP) Message Format.
#include "dsr-option-header.h"
Public Member Functions
DsrOptionRrepHeader ()
Constructor.
virtual ~DsrOptionRrepHeader ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
virtual Alignment GetAlignment () const
Get the Alignment requirement of this option header.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
Ipv4Address GetNodeAddress (uint8_t index) const
Get a Node IPv4 Address.
std::vector< Ipv4Address > GetNodesAddress () const
Get the vector of ipv4 address.
virtual uint32_t GetSerializedSize () const
Get the serialized size of the packet.
Ipv4Address GetTargetAddress (std::vector< Ipv4Address > ipv4Address) const
Get the target node Ip address.
virtual void Print (std::ostream &os) const
Print some information about the packet.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetNodeAddress (uint8_t index, Ipv4Address addr)
Set a Node IPv4 Address.
void SetNodesAddress (std::vector< Ipv4Address > ipv4Address)
Set the vector of ipv4 address.
void SetNumberAddress (uint8_t n)
Set the number of ipv4 address.
Public Member Functions inherited from ns3::dsr::DsrOptionHeader
DsrOptionHeader ()
Constructor.
virtual ~DsrOptionHeader ()
Destructor.
uint8_t GetLength () const
Get the option length.
uint8_t GetType () const
Get the type of the option.
void SetLength (uint8_t length)
Set the option length.
void SetType (uint8_t type)
Set the type of the option.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::dsr::DsrOptionHeader
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef std::vector< Ipv4Address > VectorIpv4Address_t
type def A vector of IPv4 Address.
Private Attributes
Ipv4Address m_address
The Ip address to write to when deserialize the packet.
VectorIpv4Address_t m_ipv4Address
The vector of Nodes' IPv4 Address.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Route Reply (RREP) Message Format.
Header of Dsr Option Route Reply.
 |      0        |      1        |      2        |      3        |
 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7
                -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
                |  Option Type  |  Opt Data Len |L|   Reserved   |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                            Address[1]                         |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                            Address[2]                         |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                               ...                             |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                            Address[n]                         |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Route Reply (RREP) Message Format
 |      0        |      1        |      2        |      3        |
 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |  Option Type  |  Opt Data Len |L|   Reserved   |   Reserved   |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                            Address[1]                         |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                            Address[2]                         |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                               ...                             |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                            Address[n]                         |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 448 of file dsr-option-header.h.
Member Typedef Documentation
VectorIpv4Address_t
typedef std::vector<Ipv4Address> ns3::dsr::DsrOptionRrepHeader::VectorIpv4Address_t private
type def A vector of IPv4 Address.
Definition at line 538 of file dsr-option-header.h.
Constructor & Destructor Documentation
DsrOptionRrepHeader()
ns3::dsr::DsrOptionRrepHeader::DsrOptionRrepHeader ()
Constructor.
Definition at line 414 of file dsr-option-header.cc.
References m_ipv4Address, ns3::dsr::DsrOptionHeader::SetLength(), and ns3::dsr::DsrOptionHeader::SetType().
~DsrOptionRrepHeader()
ns3::dsr::DsrOptionRrepHeader::~DsrOptionRrepHeader () virtual
Destructor.
Definition at line 421 of file dsr-option-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::dsr::DsrOptionRrepHeader::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start Buffer iterator
Returns
size of the packet
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 491 of file dsr-option-header.cc.
References ns3::Ipv4Address::Deserialize(), GetSerializedSize(), m_address, m_ipv4Address, ns3::Buffer::Iterator::Read(), ns3::Buffer::Iterator::ReadU8(), ns3::dsr::DsrOptionHeader::SetLength(), SetNodeAddress(), ns3::dsr::DsrOptionHeader::SetType(), and visualizer.core::start().
GetAlignment()
DsrOptionHeader::Alignment ns3::dsr::DsrOptionRrepHeader::GetAlignment () const virtual
Get the Alignment requirement of this option header.
Returns
The required alignment
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 513 of file dsr-option-header.cc.
GetInstanceTypeId()
TypeId ns3::dsr::DsrOptionRrepHeader::GetInstanceTypeId () const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 409 of file dsr-option-header.cc.
References GetTypeId().
GetNodeAddress()
Ipv4Address ns3::dsr::DsrOptionRrepHeader::GetNodeAddress (uint8_t index) const
Get a Node IPv4 Address.
Parameters
index the index of the IPv4 Address
Returns
the router IPv4 Address
Definition at line 447 of file dsr-option-header.cc.
References m_ipv4Address.
Referenced by DsrRrepHeaderTest::DoRun().
GetNodesAddress()
std::vector< Ipv4Address > ns3::dsr::DsrOptionRrepHeader::GetNodesAddress () const
Get the vector of ipv4 address.
Returns
the vector of ipv4 address
Definition at line 437 of file dsr-option-header.cc.
References m_ipv4Address.
Referenced by ns3::dsr::DsrOptionRrep::Process().
GetSerializedSize()
uint32_t ns3::dsr::DsrOptionRrepHeader::GetSerializedSize () const virtual
Get the serialized size of the packet.
Returns
size
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 469 of file dsr-option-header.cc.
References m_ipv4Address.
Referenced by Deserialize(), and ns3::dsr::DsrOptionRrep::Process().
GetTargetAddress()
Ipv4Address ns3::dsr::DsrOptionRrepHeader::GetTargetAddress (std::vector< Ipv4Address > ipv4Address) const
Get the target node Ip address.
Parameters
ipv4Address target address
Returns
the target address
Definition at line 452 of file dsr-option-header.cc.
References m_ipv4Address.
GetTypeId()
TypeId ns3::dsr::DsrOptionRrepHeader::GetTypeId () static
Get the type identificator.
Returns
type identificator
Definition at line 399 of file dsr-option-header.cc.
References ns3::TypeId::AddConstructor().
Referenced by GetInstanceTypeId().
Print()
void ns3::dsr::DsrOptionRrepHeader::Print (std::ostream & os) const virtual
Print some information about the packet.
Parameters
os output stream
Returns
info about this packet
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 457 of file dsr-option-header.cc.
References ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrOptionHeader::GetType(), and m_ipv4Address.
Serialize()
void ns3::dsr::DsrOptionRrepHeader::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start Buffer iterator
Reimplemented from ns3::dsr::DsrOptionHeader.
Definition at line 474 of file dsr-option-header.cc.
References ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrOptionHeader::GetType(), m_ipv4Address, visualizer.core::start(), ns3::Buffer::Iterator::Write(), and ns3::Buffer::Iterator::WriteU8().
SetNodeAddress()
void ns3::dsr::DsrOptionRrepHeader::SetNodeAddress (uint8_t index, Ipv4Address addr)
Set a Node IPv4 Address.
Parameters
index the index of the IPv4 Address
addr the new IPv4 Address
Definition at line 442 of file dsr-option-header.cc.
References m_ipv4Address.
Referenced by Deserialize().
SetNodesAddress()
void ns3::dsr::DsrOptionRrepHeader::SetNodesAddress (std::vector< Ipv4Address > ipv4Address)
Set the vector of ipv4 address.
Parameters
ipv4Address the vector of ipv4 address
Definition at line 431 of file dsr-option-header.cc.
References m_ipv4Address, and ns3::dsr::DsrOptionHeader::SetLength().
Referenced by DsrRrepHeaderTest::DoRun(), ns3::dsr::DsrOptionRreq::Process(), and ns3::dsr::DsrRouting::SendGratuitousReply().
SetNumberAddress()
void ns3::dsr::DsrOptionRrepHeader::SetNumberAddress (uint8_t n)
Set the number of ipv4 address.
Parameters
n the number of ipv4 address
Definition at line 425 of file dsr-option-header.cc.
References m_ipv4Address, and sample-rng-plot::n.
Referenced by DsrRrepHeaderTest::DoRun(), and ns3::dsr::DsrOptionRrep::Process().
Member Data Documentation
m_address
Ipv4Address ns3::dsr::DsrOptionRrepHeader::m_address private
The Ip address to write to when deserialize the packet.
Definition at line 534 of file dsr-option-header.h.
Referenced by Deserialize().
m_ipv4Address
VectorIpv4Address_t ns3::dsr::DsrOptionRrepHeader::m_ipv4Address private
The vector of Nodes' IPv4 Address.
Definition at line 542 of file dsr-option-header.h.
Referenced by DsrOptionRrepHeader(), Deserialize(), GetNodeAddress(), GetNodesAddress(), GetSerializedSize(), GetTargetAddress(), Print(), Serialize(), SetNodeAddress(), SetNodesAddress(), and SetNumberAddress().
The documentation for this class was generated from the following files:
src/dsr/model/dsr-option-header.h
src/dsr/model/dsr-option-header.cc