ns-3: ns3::Ipv4ListRoutingHelper Class Reference
ns3::Ipv4ListRoutingHelper Class Reference
Internet » IPv4 Helper classes
Helper class that adds ns3::Ipv4ListRouting objects.
#include "ipv4-list-routing-helper.h"
Public Member Functions
Ipv4ListRoutingHelper ()
Ipv4ListRoutingHelper (const Ipv4ListRoutingHelper &)
Construct an Ipv4ListRoutingHelper from another previously initialized instance (Copy Constructor).
virtual ~Ipv4ListRoutingHelper ()
void Add (const Ipv4RoutingHelper &routing, int16_t priority)
Ipv4ListRoutingHelper * Copy (void) const
virtual Ptr< Ipv4RoutingProtocol > Create (Ptr< Node > node) const
Public Member Functions inherited from ns3::Ipv4RoutingHelper
virtual ~Ipv4RoutingHelper ()
Private Member Functions
Ipv4ListRoutingHelper & operator= (const Ipv4ListRoutingHelper &)
Assignment operator declared private and not implemented to disallow assignment and prevent the compiler from happily inserting its own.
Private Attributes
std::list< std::pair< const Ipv4RoutingHelper *, int16_t > > m_list
Container for pairs of Ipv4RoutingHelper pointer / priority.
Additional Inherited Members
Static Public Member Functions inherited from ns3::Ipv4RoutingHelper
template<class T >
static Ptr< T > GetRouting (Ptr< Ipv4RoutingProtocol > protocol)
Request a specified routing protocol <T> from Ipv4RoutingProtocol protocol.
static void PrintNeighborCacheAllAt (Time printTime, Ptr< OutputStreamWrapper > stream)
prints the neighbor cache of all nodes at a particular time.
static void PrintNeighborCacheAllEvery (Time printInterval, Ptr< OutputStreamWrapper > stream)
prints the neighbor cache of all nodes at regular intervals specified by user.
static void PrintNeighborCacheAt (Time printTime, Ptr< Node > node, Ptr< OutputStreamWrapper > stream)
prints the neighbor cache of a node at a particular time.
static void PrintNeighborCacheEvery (Time printInterval, Ptr< Node > node, Ptr< OutputStreamWrapper > stream)
prints the neighbor cache of a node at regular intervals specified by user.
static void PrintRoutingTableAllAt (Time printTime, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of all nodes at a particular time.
static void PrintRoutingTableAllEvery (Time printInterval, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of all nodes at regular intervals specified by user.
static void PrintRoutingTableAt (Time printTime, Ptr< Node > node, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of a node at a particular time.
static void PrintRoutingTableEvery (Time printInterval, Ptr< Node > node, Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S)
prints the routing tables of a node at regular intervals specified by user.
Detailed Description
Helper class that adds ns3::Ipv4ListRouting objects.
This class is expected to be used in conjunction with ns3::InternetStackHelper::SetRoutingHelper
Definition at line 37 of file ipv4-list-routing-helper.h.
Constructor & Destructor Documentation
Ipv4ListRoutingHelper() [1/2]
ns3::Ipv4ListRoutingHelper::Ipv4ListRoutingHelper ()
Definition at line 26 of file ipv4-list-routing-helper.cc.
Referenced by Copy().
~Ipv4ListRoutingHelper()
ns3::Ipv4ListRoutingHelper::~Ipv4ListRoutingHelper () virtual
Definition at line 30 of file ipv4-list-routing-helper.cc.
References list, and m_list.
Ipv4ListRoutingHelper() [2/2]
ns3::Ipv4ListRoutingHelper::Ipv4ListRoutingHelper (const Ipv4ListRoutingHelper & o)
Construct an Ipv4ListRoutingHelper from another previously initialized instance (Copy Constructor).
Definition at line 39 of file ipv4-list-routing-helper.cc.
References m_list.
Member Function Documentation
Add()
void ns3::Ipv4ListRoutingHelper::Add (const Ipv4RoutingHelper & routing, int16_t priority)
Parameters
routing a routing helper
priority the priority of the associated helper
Store in the internal list a reference to the input routing helper and associated priority. These helpers will be used later by the ns3::Ipv4ListRoutingHelper::Create method to create an ns3::Ipv4ListRouting object and add in it routing protocols created with the helpers.
Definition at line 55 of file ipv4-list-routing-helper.cc.
References ns3::Ipv4RoutingHelper::Copy(), and m_list.
Referenced by Ipv4DeduplicationTest::DoRun(), Ipv4DeduplicationPerformanceTest::DoRun(), and ns3::InternetStackHelper::Initialize().
Copy()
Ipv4ListRoutingHelper * ns3::Ipv4ListRoutingHelper::Copy (void) const virtual
Returns
pointer to clone of this Ipv4ListRoutingHelper
This method is mainly for internal use by the other helpers; clients are expected to free the dynamic memory allocated by this method
Implements ns3::Ipv4RoutingHelper.
Definition at line 49 of file ipv4-list-routing-helper.cc.
References Ipv4ListRoutingHelper().
Create()
Ptr< Ipv4RoutingProtocol > ns3::Ipv4ListRoutingHelper::Create (Ptr< Node > node) const virtual
Parameters
node the node on which the routing protocol will run
Returns
a newly-created routing protocol
This method will be called by ns3::InternetStackHelper::Install
Implements ns3::Ipv4RoutingHelper.
Definition at line 61 of file ipv4-list-routing-helper.cc.
References list, and m_list.
operator=()
Ipv4ListRoutingHelper& ns3::Ipv4ListRoutingHelper::operator= (const Ipv4ListRoutingHelper &) private
Assignment operator declared private and not implemented to disallow assignment and prevent the compiler from happily inserting its own.
Returns
Member Data Documentation
m_list
std::list<std::pair<const Ipv4RoutingHelper *,int16_t> > ns3::Ipv4ListRoutingHelper::m_list private
Container for pairs of Ipv4RoutingHelper pointer / priority.
Definition at line 94 of file ipv4-list-routing-helper.h.
Referenced by Ipv4ListRoutingHelper(), ~Ipv4ListRoutingHelper(), Add(), and Create().
The documentation for this class was generated from the following files:
src/internet/helper/ipv4-list-routing-helper.h
src/internet/helper/ipv4-list-routing-helper.cc