ns-3: Tunnel Class Reference
Tunnel Class Reference
Public Member Functions
Tunnel (Ptr< Node > n3, Ptr< Node > n0, Ptr< Node > n1, Ipv4Address n3Addr, Ipv4Address n0Addr, Ipv4Address n1Addr)
Private Member Functions
void N0SocketRecv (Ptr< Socket > socket)
bool N0VirtualSend (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
void N1SocketRecv (Ptr< Socket > socket)
bool N1VirtualSend (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
void N3SocketRecv (Ptr< Socket > socket)
bool N3VirtualSend (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
Private Attributes
Ipv4Address m_n0Address
Ptr< Socket > m_n0Socket
Ptr< VirtualNetDevice > m_n0Tap
Ipv4Address m_n1Address
Ptr< Socket > m_n1Socket
Ptr< VirtualNetDevice > m_n1Tap
Ipv4Address m_n3Address
Ptr< Socket > m_n3Socket
Ptr< VirtualNetDevice > m_n3Tap
Ptr< UniformRandomVariable > m_rng
Detailed Description
Definition at line 61 of file virtual-net-device.cc.
Constructor & Destructor Documentation
Tunnel()
Tunnel::Tunnel (Ptr< Node > n3, Ptr< Node > n0, Ptr< Node > n1, Ipv4Address n3Addr, Ipv4Address n0Addr, Ipv4Address n1Addr) inline
Definition at line 130 of file virtual-net-device.cc.
References ns3::Ipv4::AddAddress(), ns3::Node::AddDevice(), ns3::Ipv4::AddInterface(), ns3::Socket::Bind(), ns3::Socket::CreateSocket(), ns3::Ipv4Address::GetAny(), ns3::Object::GetObject(), ns3::TypeId::LookupByName(), ns3::MakeCallback(), N0SocketRecv(), N0VirtualSend(), N1SocketRecv(), N1VirtualSend(), N3SocketRecv(), N3VirtualSend(), ns3::VirtualNetDevice::SetAddress(), ns3::Socket::SetRecvCallback(), ns3::VirtualNetDevice::SetSendCallback(), and ns3::Ipv4::SetUp().
Member Function Documentation
N0SocketRecv()
void Tunnel::N0SocketRecv (Ptr< Socket > socket) inline private
Definition at line 114 of file virtual-net-device.cc.
References ns3::VirtualNetDevice::GetAddress(), NS_LOG_DEBUG, ns3::NetDevice::PACKET_HOST, ns3::VirtualNetDevice::Receive(), and ns3::Socket::Recv().
Referenced by Tunnel().
N0VirtualSend()
bool Tunnel::N0VirtualSend (Ptr< Packet > packet, const Address & source, const Address & dest, uint16_t protocolNumber) inline private
Definition at line 76 of file virtual-net-device.cc.
References NS_LOG_DEBUG, and ns3::Socket::SendTo().
Referenced by Tunnel().
N1SocketRecv()
void Tunnel::N1SocketRecv (Ptr< Socket > socket) inline private
Definition at line 121 of file virtual-net-device.cc.
References ns3::VirtualNetDevice::GetAddress(), NS_LOG_DEBUG, ns3::NetDevice::PACKET_HOST, ns3::VirtualNetDevice::Receive(), and ns3::Socket::Recv().
Referenced by Tunnel().
N1VirtualSend()
bool Tunnel::N1VirtualSend (Ptr< Packet > packet, const Address & source, const Address & dest, uint16_t protocolNumber) inline private
Definition at line 84 of file virtual-net-device.cc.
References NS_LOG_DEBUG, and ns3::Socket::SendTo().
Referenced by Tunnel().
N3SocketRecv()
void Tunnel::N3SocketRecv (Ptr< Socket > socket) inline private
Definition at line 107 of file virtual-net-device.cc.
References ns3::VirtualNetDevice::GetAddress(), NS_LOG_DEBUG, ns3::NetDevice::PACKET_HOST, ns3::VirtualNetDevice::Receive(), and ns3::Socket::Recv().
Referenced by Tunnel().
N3VirtualSend()
bool Tunnel::N3VirtualSend (Ptr< Packet > packet, const Address & source, const Address & dest, uint16_t protocolNumber) inline private
Definition at line 92 of file virtual-net-device.cc.
References ns3::UniformRandomVariable::GetValue(), NS_LOG_DEBUG, and ns3::Socket::SendTo().
Referenced by Tunnel().
Member Data Documentation
m_n0Address
Ipv4Address Tunnel::m_n0Address private
Definition at line 67 of file virtual-net-device.cc.
m_n0Socket
Ptr<Socket> Tunnel::m_n0Socket private
Definition at line 64 of file virtual-net-device.cc.
m_n0Tap
Ptr<VirtualNetDevice> Tunnel::m_n0Tap private
Definition at line 70 of file virtual-net-device.cc.
m_n1Address
Ipv4Address Tunnel::m_n1Address private
Definition at line 68 of file virtual-net-device.cc.
m_n1Socket
Ptr<Socket> Tunnel::m_n1Socket private
Definition at line 65 of file virtual-net-device.cc.
m_n1Tap
Ptr<VirtualNetDevice> Tunnel::m_n1Tap private
Definition at line 71 of file virtual-net-device.cc.
m_n3Address
Ipv4Address Tunnel::m_n3Address private
Definition at line 66 of file virtual-net-device.cc.
m_n3Socket
Ptr<Socket> Tunnel::m_n3Socket private
Definition at line 63 of file virtual-net-device.cc.
m_n3Tap
Ptr<VirtualNetDevice> Tunnel::m_n3Tap private
Definition at line 72 of file virtual-net-device.cc.
m_rng
Ptr<UniformRandomVariable> Tunnel::m_rng private
Definition at line 69 of file virtual-net-device.cc.
The documentation for this class was generated from the following file:
src/virtual-net-device/examples/virtual-net-device.cc