ns-3: ns3::Hash::Function::Fnv1a Class Reference
ns3::Hash::Function::Fnv1a Class Reference
Core » Hash Functions
Fnv1a hash function implementation.
#include "hash-fnv.h"
Public Member Functions
Fnv1a ()
Constructor.
virtual void clear (void)
Restore initial state.
uint32_t GetHash32 (const char *buffer, const size_t size)
Compute 32-bit hash of a byte buffer.
uint64_t GetHash64 (const char *buffer, const size_t size)
Compute 64-bit hash of a byte buffer.
Public Member Functions inherited from ns3::Hash::Implementation
Implementation ()
Constructor.
virtual ~Implementation ()
Destructor.
virtual uint32_t GetHash32 (const char *buffer, const std::size_t size)=0
Compute 32-bit hash of a byte buffer.
virtual uint64_t GetHash64 (const char *buffer, const std::size_t size)
Compute 64-bit hash of a byte buffer.
Public Member Functions inherited from ns3::SimpleRefCount< Implementation >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Types
enum seed { SEED = 0x8BADF00D }
Seed value.
Private Attributes
uint32_t m_hash32
Cache last hash value, for incremental hashing.
uint64_t m_hash64
Cache last hash value, for incremental hashing.
Detailed Description
Fnv1a hash function implementation.
This is the venerable Fowler-Noll-Vo hash, version 1A. (See the FNV page.)
The implementation here is taken directly from the published FNV reference code, with minor modifications to wrap into this class. See the hash-fnv.cc file for details.
Definition at line 53 of file hash-fnv.h.
Member Enumeration Documentation
seed
enum ns3::Hash::Function::Fnv1a::seed private
Seed value.
Enumerator
SEED
Ate bad food.
Definition at line 99 of file hash-fnv.h.
Constructor & Destructor Documentation
Fnv1a()
ns3::Hash::Function::Fnv1a::Fnv1a ()
Constructor.
Definition at line 749 of file hash-fnv.cc.
References clear().
Member Function Documentation
clear()
void ns3::Hash::Function::Fnv1a::clear (void) virtual
Restore initial state.
Implements ns3::Hash::Implementation.
Definition at line 771 of file hash-fnv.cc.
References FNV1_32A_INIT, FNV1A_64_INIT, m_hash32, and m_hash64.
Referenced by Fnv1a().
GetHash32()
uint32_t ns3::Hash::Function::Fnv1a::GetHash32 (const char * buffer, const size_t size)
Compute 32-bit hash of a byte buffer.
Call clear () between calls to GetHash32() to reset the internal state and hash each buffer separately.
If you don't call clear() between calls to GetHash32, you can hash successive buffers. The final return value will be the cumulative hash across all calls.
Parameters
[in] buffer pointer to the beginning of the buffer
[in] size length of the buffer, in bytes
Returns
32-bit hash of the buffer
Definition at line 755 of file hash-fnv.cc.
References ns3::Hash::Function::Fnv1aImplementation::fnv_32a_buf(), and m_hash32.
GetHash64()
uint64_t ns3::Hash::Function::Fnv1a::GetHash64 (const char * buffer, const size_t size)
Compute 64-bit hash of a byte buffer.
Call clear () between calls to GetHash64() to reset the internal state and hash each buffer separately.
If you don't call clear() between calls to GetHash64, you can hash successive buffers. The final return value will be the cumulative hash across all calls.
Parameters
[in] buffer pointer to the beginning of the buffer
[in] size length of the buffer, in bytes
Returns
64-bit hash of the buffer
Definition at line 763 of file hash-fnv.cc.
References ns3::Hash::Function::Fnv1aImplementation::fnv_64a_buf(), and m_hash64.
Member Data Documentation
m_hash32
uint32_t ns3::Hash::Function::Fnv1a::m_hash32 private
Cache last hash value, for incremental hashing.
Definition at line 105 of file hash-fnv.h.
Referenced by clear(), and GetHash32().
m_hash64
uint64_t ns3::Hash::Function::Fnv1a::m_hash64 private
Cache last hash value, for incremental hashing.
Definition at line 106 of file hash-fnv.h.
Referenced by clear(), and GetHash64().
The documentation for this class was generated from the following files:
src/core/model/hash-fnv.h
src/core/model/hash-fnv.cc