ns-3: UplinkPacketTest Class Reference
UplinkPacketTest Class Reference
Public Member Functions
UplinkPacketTest ()
virtual ~UplinkPacketTest ()
void ReceivedPacket (Ptr< Packet const > packet)
void SendPacket (Ptr< Node > endDevice)
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
bool m_receivedPacket = false
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 31 of file network-server-test-suite.cc.
Constructor & Destructor Documentation
UplinkPacketTest()
UplinkPacketTest::UplinkPacketTest ()
Definition at line 46 of file network-server-test-suite.cc.
~UplinkPacketTest()
UplinkPacketTest::~UplinkPacketTest () virtual
Definition at line 53 of file network-server-test-suite.cc.
Member Function Documentation
DoRun()
void UplinkPacketTest::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 73 of file network-server-test-suite.cc.
References third::channel, ns3::lorawan::NetworkComponents::channel, ns3::lorawan::NetworkComponents::endDevices, ns3::lorawan::NetworkComponents::gateways, ns3::NodeContainer::Get(), ns3::Node::GetApplication(), ns3::lorawan::InitializeNetwork(), m_receivedPacket, ns3::MakeCallback(), NS_ASSERT, NS_LOG_DEBUG, ns3::lorawan::NetworkComponents::nsNode, ReceivedPacket(), ns3::Seconds(), SendPacket(), and ns3::ObjectBase::TraceConnectWithoutContext().
ReceivedPacket()
void UplinkPacketTest::ReceivedPacket (Ptr< Packet const > packet)
Definition at line 58 of file network-server-test-suite.cc.
References m_receivedPacket, and NS_LOG_DEBUG.
Referenced by DoRun().
SendPacket()
void UplinkPacketTest::SendPacket (Ptr< Node > endDevice)
Definition at line 65 of file network-server-test-suite.cc.
References ns3::Node::GetDevice().
Referenced by DoRun().
Member Data Documentation
m_receivedPacket
bool UplinkPacketTest::m_receivedPacket = false private
Definition at line 42 of file network-server-test-suite.cc.
Referenced by DoRun(), and ReceivedPacket().
The documentation for this class was generated from the following file:
src/lorawan/test/network-server-test-suite.cc