ns-3: ns3::UdpSocket Class Reference
ns3::UdpSocket Class Reference abstract
Network » Socket | Internet » UDP
(abstract) base class of all UdpSockets
#include "udp-socket.h"
Public Member Functions
UdpSocket (void)
virtual ~UdpSocket (void)
virtual int MulticastJoinGroup (uint32_t interface, const Address &groupAddress)=0
Corresponds to socket option MCAST_JOIN_GROUP.
virtual int MulticastLeaveGroup (uint32_t interface, const Address &groupAddress)=0
Corresponds to socket option MCAST_LEAVE_GROUP.
Public Member Functions inherited from ns3::Socket
Socket (void)
virtual ~Socket (void)
virtual int Bind ()=0
Allocate a local IPv4 endpoint for this socket.
virtual int Bind (const Address &address)=0
Allocate a local endpoint for this socket.
virtual int Bind6 ()=0
Allocate a local IPv6 endpoint for this socket.
virtual void BindToNetDevice (Ptr< NetDevice > netdevice)
Bind a socket to specific device.
virtual int Close (void)=0
Close a socket.
virtual int Connect (const Address &address)=0
Initiate a connection to a remote host.
virtual bool GetAllowBroadcast () const =0
Query whether broadcast datagram transmissions are allowed.
Ptr< NetDevice > GetBoundNetDevice ()
Returns socket's bound NetDevice, if any.
virtual enum Socket::SocketErrno GetErrno (void) const =0
Get last error number.
uint8_t GetIpTos (void) const
Query the value of IP Type of Service of this socket.
virtual uint8_t GetIpTtl (void) const
Query the value of IP Time to Live field of this socket.
virtual uint8_t GetIpv6HopLimit (void) const
Query the value of IP Hop Limit field of this socket.
uint8_t GetIpv6Tclass (void) const
Query the value of IPv6 Traffic Class field of this socket.
virtual Ptr< Node > GetNode (void) const =0
Return the node this socket is associated with.
virtual int GetPeerName (Address &address) const =0
Get the peer address of a connected socket.
uint8_t GetPriority (void) const
Query the priority value of this socket.
virtual uint32_t GetRxAvailable (void) const =0
Return number of bytes which can be returned from one or multiple calls to Recv.
virtual enum Socket::SocketType GetSocketType (void) const =0
virtual int GetSockName (Address &address) const =0
Get socket address.
virtual uint32_t GetTxAvailable (void) const =0
Returns the number of bytes which can be sent in a single call to Send.
virtual void Ipv6JoinGroup (Ipv6Address address)
Joins a IPv6 multicast group without filters.
virtual void Ipv6JoinGroup (Ipv6Address address, Ipv6MulticastFilterMode filterMode, std::vector< Ipv6Address > sourceAddresses)
Joins a IPv6 multicast group.
virtual void Ipv6LeaveGroup (void)
Leaves IPv6 multicast group this socket is joined to.
bool IsIpRecvTos (void) const
Ask if the socket is currently passing information about IP Type of Service up the stack.
bool IsIpRecvTtl (void) const
Ask if the socket is currently passing information about IP_TTL up the stack.
bool IsIpv6RecvHopLimit (void) const
Ask if the socket is currently passing information about IPv6 Hop Limit up the stack.
bool IsIpv6RecvTclass (void) const
Ask if the socket is currently passing information about IPv6 Traffic Class up the stack.
bool IsRecvPktInfo () const
Get status indicating whether enable/disable packet information to socket.
virtual int Listen (void)=0
Listen for incoming connections.
virtual Ptr< Packet > Recv (uint32_t maxSize, uint32_t flags)=0
Read data from the socket.
int Recv (uint8_t *buf, uint32_t size, uint32_t flags)
Recv data (or dummy data) from the remote host.
Ptr< Packet > Recv (void)
Read a single packet from the socket.
Ptr< Packet > RecvFrom (Address &fromAddress)
Read a single packet from the socket and retrieve the sender address.
virtual Ptr< Packet > RecvFrom (uint32_t maxSize, uint32_t flags, Address &fromAddress)=0
Read a single packet from the socket and retrieve the sender address.
int RecvFrom (uint8_t *buf, uint32_t size, uint32_t flags, Address &fromAddress)
Read a single packet from the socket and retrieve the sender address.
int Send (const uint8_t *buf, uint32_t size, uint32_t flags)
Send data (or dummy data) to the remote host.
int Send (Ptr< Packet > p)
Send data (or dummy data) to the remote host.
virtual int Send (Ptr< Packet > p, uint32_t flags)=0
Send data (or dummy data) to the remote host.
int SendTo (const uint8_t *buf, uint32_t size, uint32_t flags, const Address &address)
Send data to a specified peer.
virtual int SendTo (Ptr< Packet > p, uint32_t flags, const Address &toAddress)=0
Send data to a specified peer.
void SetAcceptCallback (Callback< bool, Ptr< Socket >, const Address & > connectionRequest, Callback< void, Ptr< Socket >, const Address & > newConnectionCreated)
Accept connection requests from remote hosts.
virtual bool SetAllowBroadcast (bool allowBroadcast)=0
Configure whether broadcast datagram transmissions are allowed.
void SetCloseCallbacks (Callback< void, Ptr< Socket > > normalClose, Callback< void, Ptr< Socket > > errorClose)
Detect socket recv() events such as graceful shutdown or error.
void SetConnectCallback (Callback< void, Ptr< Socket > > connectionSucceeded, Callback< void, Ptr< Socket > > connectionFailed)
Specify callbacks to allow the caller to determine if the connection succeeds of fails.
void SetDataSentCallback (Callback< void, Ptr< Socket >, uint32_t > dataSent)
Notify application when a packet has been sent from transport protocol (non-standard socket call)
void SetIpRecvTos (bool ipv4RecvTos)
Tells a socket to pass information about IP Type of Service up the stack.
void SetIpRecvTtl (bool ipv4RecvTtl)
Tells a socket to pass information about IP_TTL up the stack.
void SetIpTos (uint8_t ipTos)
Manually set IP Type of Service field.
virtual void SetIpTtl (uint8_t ipTtl)
Manually set IP Time to Live field.
virtual void SetIpv6HopLimit (uint8_t ipHopLimit)
Manually set IPv6 Hop Limit.
void SetIpv6RecvHopLimit (bool ipv6RecvHopLimit)
Tells a socket to pass information about IPv6 Hop Limit up the stack.
void SetIpv6RecvTclass (bool ipv6RecvTclass)
Tells a socket to pass information about IPv6 Traffic Class up the stack.
void SetIpv6Tclass (int ipTclass)
Manually set IPv6 Traffic Class field.
void SetPriority (uint8_t priority)
Manually set the socket priority.
void SetRecvCallback (Callback< void, Ptr< Socket > >)
Notify application when new data is available to be read.
void SetRecvPktInfo (bool flag)
Enable/Disable receive packet information to socket.
void SetSendCallback (Callback< void, Ptr< Socket >, uint32_t > sendCb)
Notify application when space in transmit buffer is added.
virtual int ShutdownRecv (void)=0
virtual int ShutdownSend (void)=0
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Socket
static Ptr< Socket > CreateSocket (Ptr< Node > node, TypeId tid)
This method wraps the creation of sockets that is performed on a given node by a SocketFactory specified by TypeId.
static TypeId GetTypeId (void)
Get the type ID.
static uint8_t IpTos2Priority (uint8_t ipTos)
Return the priority corresponding to a given TOS value.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual int32_t GetIpMulticastIf (void) const =0
Get the IP multicast interface.
virtual bool GetIpMulticastLoop (void) const =0
Get the IP multicast loop capability.
virtual uint8_t GetIpMulticastTtl (void) const =0
Get the IP multicast TTL.
virtual bool GetMtuDiscover (void) const =0
Get the MTU discover capability.
virtual uint32_t GetRcvBufSize (void) const =0
Get the receiving buffer size.
virtual void SetIpMulticastIf (int32_t ipIf)=0
Set the IP multicast interface.
virtual void SetIpMulticastLoop (bool loop)=0
Set the IP multicast loop capability.
virtual void SetIpMulticastTtl (uint8_t ipTtl)=0
Set the IP multicast TTL.
virtual void SetMtuDiscover (bool discover)=0
Set the MTU discover capability.
virtual void SetRcvBufSize (uint32_t size)=0
Set the receiving buffer size.
Additional Inherited Members
Public Types inherited from ns3::Socket
enum Ipv6MulticastFilterMode { INCLUDE =1, EXCLUDE }
Enumeration of the possible filter of a socket.
enum SocketErrno {
ERROR_NOTERROR, ERROR_ISCONN, ERROR_NOTCONN, ERROR_MSGSIZE,
ERROR_AGAIN, ERROR_SHUTDOWN, ERROR_OPNOTSUPP, ERROR_AFNOSUPPORT,
ERROR_INVAL, ERROR_BADF, ERROR_NOROUTETOHOST, ERROR_NODEV,
ERROR_ADDRNOTAVAIL, ERROR_ADDRINUSE, SOCKET_ERRNO_LAST
}
Enumeration of the possible errors returned by a socket.
enum SocketPriority {
NS3_PRIO_BESTEFFORT = 0, NS3_PRIO_FILLER = 1, NS3_PRIO_BULK = 2, NS3_PRIO_INTERACTIVE_BULK = 4,
NS3_PRIO_INTERACTIVE = 6, NS3_PRIO_CONTROL = 7
}
Enumeration of the possible socket priorities.
enum SocketType { NS3_SOCK_STREAM, NS3_SOCK_SEQPACKET, NS3_SOCK_DGRAM, NS3_SOCK_RAW }
Enumeration of the possible socket types.
Protected Member Functions inherited from ns3::Socket
virtual void DoDispose (void)
Destructor implementation.
bool IsManualIpTtl (void) const
Checks if the socket has a specific IPv4 TTL set.
bool IsManualIpv6HopLimit (void) const
Checks if the socket has a specific IPv6 Hop Limit set.
bool IsManualIpv6Tclass (void) const
Checks if the socket has a specific IPv6 Tclass set.
void NotifyConnectionFailed (void)
Notify through the callback (if set) that the connection has not been established due to an error.
bool NotifyConnectionRequest (const Address &from)
Notify through the callback (if set) that an incoming connection is being requested by a remote host.
void NotifyConnectionSucceeded (void)
Notify through the callback (if set) that the connection has been established.
void NotifyDataRecv (void)
Notify through the callback (if set) that some data have been received.
void NotifyDataSent (uint32_t size)
Notify through the callback (if set) that some data have been sent.
void NotifyErrorClose (void)
Notify through the callback (if set) that the connection has been closed due to an error.
void NotifyNewConnectionCreated (Ptr< Socket > socket, const Address &from)
Notify through the callback (if set) that a new connection has been created.
void NotifyNormalClose (void)
Notify through the callback (if set) that the connection has been closed.
void NotifySend (uint32_t spaceAvailable)
Notify through the callback (if set) that some data have been sent.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Socket
Ptr< NetDevice > m_boundnetdevice
the device this socket is bound to (might be null).
Ipv6Address m_ipv6MulticastGroupAddress
IPv6 multicast group address.
bool m_recvPktInfo
if the socket should add packet info tags to the packet forwarded to L4.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
(abstract) base class of all UdpSockets
This class exists solely for hosting UdpSocket attributes that can be reused across different implementations, and for declaring UDP-specific multicast API.
Definition at line 47 of file udp-socket.h.
Constructor & Destructor Documentation
UdpSocket()
ns3::UdpSocket::UdpSocket (void)
Definition at line 80 of file udp-socket.cc.
References NS_LOG_FUNCTION_NOARGS.
~UdpSocket()
ns3::UdpSocket::~UdpSocket (void) virtual
Definition at line 85 of file udp-socket.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
GetIpMulticastIf()
virtual int32_t ns3::UdpSocket::GetIpMulticastIf (void) const private pure virtual
Get the IP multicast interface.
Returns
the IP multicast interface
Implemented in ns3::UdpSocketImpl.
Referenced by GetTypeId().
GetIpMulticastLoop()
virtual bool ns3::UdpSocket::GetIpMulticastLoop (void) const private pure virtual
Get the IP multicast loop capability.
This means that the socket will receive the packets sent by itself on a multicast address. Equivalent to setsockopt IP_MULTICAST_LOOP
Returns
the IP multicast loop capability
Implemented in ns3::UdpSocketImpl.
Referenced by GetTypeId().
GetIpMulticastTtl()
virtual uint8_t ns3::UdpSocket::GetIpMulticastTtl (void) const private pure virtual
Get the IP multicast TTL.
Returns
the IP multicast TTL
Implemented in ns3::UdpSocketImpl.
Referenced by GetTypeId().
GetMtuDiscover()
virtual bool ns3::UdpSocket::GetMtuDiscover (void) const private pure virtual
Get the MTU discover capability.
Returns
the MTU discover capability
Implemented in ns3::UdpSocketImpl.
Referenced by ns3::Ipv4::GetTypeId(), and GetTypeId().
GetRcvBufSize()
virtual uint32_t ns3::UdpSocket::GetRcvBufSize (void) const private pure virtual
Get the receiving buffer size.
Returns
the buffer size
Implemented in ns3::UdpSocketImpl.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::UdpSocket::GetTypeId (void) static
Get the type ID.
Get the type ID.
Returns
the object TypeId
Definition at line 36 of file udp-socket.cc.
References GetIpMulticastIf(), GetIpMulticastLoop(), GetIpMulticastTtl(), ns3::Socket::GetIpTtl(), GetMtuDiscover(), GetRcvBufSize(), ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeIntegerAccessor(), ns3::MakeUintegerAccessor(), SetIpMulticastIf(), SetIpMulticastLoop(), SetIpMulticastTtl(), ns3::Socket::SetIpTtl(), SetMtuDiscover(), ns3::TypeId::SetParent(), and SetRcvBufSize().
MulticastJoinGroup()
virtual int ns3::UdpSocket::MulticastJoinGroup (uint32_t interface, const Address & groupAddress) pure virtual
Corresponds to socket option MCAST_JOIN_GROUP.
Parameters
interface interface number, or 0
groupAddress multicast group address
Returns
on success, zero is returned. On error, -1 is returned, and errno is set appropriately
Enable reception of multicast datagrams for this socket on the interface number specified. If zero is specified as the interface, then a single local interface is chosen by system. In the future, this function will generate trigger IGMP joins as necessary when IGMP is implemented, but for now, this just enables multicast datagram reception in the system if not already enabled for this interface/groupAddress combination.
Attention
IGMP is not yet implemented in ns-3
This function may be called repeatedly on a given socket but each join must be for a different multicast address, or for the same multicast address but on a different interface from previous joins. This enables host multihoming, and the ability to join the same group on different interfaces.
Implemented in ns3::UdpSocketImpl.
Referenced by Ipv4DeduplicationTest::DoRun(), and Ipv4FragmentationTest::StartServer().
MulticastLeaveGroup()
virtual int ns3::UdpSocket::MulticastLeaveGroup (uint32_t interface, const Address & groupAddress) pure virtual
Corresponds to socket option MCAST_LEAVE_GROUP.
Parameters
interface interface number, or 0
groupAddress multicast group address
Returns
on success, zero is returned. On error, -1 is returned, and errno is set appropriately
Disable reception of multicast datagrams for this socket on the interface number specified. If zero is specified as the interfaceIndex, then a single local interface is chosen by system. In the future, this function will generate trigger IGMP leaves as necessary when IGMP is implemented, but for now, this just disables multicast datagram reception in the system if this socket is the last for this interface/groupAddress combination.
Attention
IGMP is not yet implemented in ns-3
Implemented in ns3::UdpSocketImpl.
SetIpMulticastIf()
virtual void ns3::UdpSocket::SetIpMulticastIf (int32_t ipIf) private pure virtual
Set the IP multicast interface.
Parameters
ipIf the IP multicast interface
Implemented in ns3::UdpSocketImpl.
Referenced by GetTypeId().
SetIpMulticastLoop()
virtual void ns3::UdpSocket::SetIpMulticastLoop (bool loop) private pure virtual
Set the IP multicast loop capability.
This means that the socket will receive the packets sent by itself on a multicast address. Equivalent to setsockopt IP_MULTICAST_LOOP
Parameters
loop the IP multicast loop capability
Implemented in ns3::UdpSocketImpl.
Referenced by GetTypeId().
SetIpMulticastTtl()
virtual void ns3::UdpSocket::SetIpMulticastTtl (uint8_t ipTtl) private pure virtual
Set the IP multicast TTL.
Parameters
ipTtl the IP multicast TTL
Implemented in ns3::UdpSocketImpl.
Referenced by GetTypeId().
SetMtuDiscover()
virtual void ns3::UdpSocket::SetMtuDiscover (bool discover) private pure virtual
Set the MTU discover capability.
Parameters
discover the MTU discover capability
Implemented in ns3::UdpSocketImpl.
Referenced by ns3::Ipv4::GetTypeId(), and GetTypeId().
SetRcvBufSize()
virtual void ns3::UdpSocket::SetRcvBufSize (uint32_t size) private pure virtual
Set the receiving buffer size.
Parameters
size the buffer size
Implemented in ns3::UdpSocketImpl.
Referenced by GetTypeId().
The documentation for this class was generated from the following files:
src/internet/model/udp-socket.h
src/internet/model/udp-socket.cc