ns-3: ns3::MemberLteEnbRrcSapProvider< C > Class Template Reference
ns3::MemberLteEnbRrcSapProvider< C > Class Template Reference
Template for the implementation of the LteEnbRrcSapProvider as a member of an owner class of type C to which all methods are forwarded.
#include "lte-rrc-sap.h"
Public Member Functions
MemberLteEnbRrcSapProvider (C *owner)
Constructor.
virtual void CompleteSetupUe (uint16_t rnti, CompleteSetupUeParameters params)
Complete setup UE function.
virtual void RecvIdealUeContextRemoveRequest (uint16_t rnti)
Receive ideal UE context remove request from the UE RRC.
virtual void RecvMeasurementReport (uint16_t rnti, MeasurementReport msg)
Receive a MeasurementReport message from a UE during a measurement reporting procedure (Section 5.5.5 of TS 36.331).
virtual void RecvRrcConnectionReconfigurationCompleted (uint16_t rnti, RrcConnectionReconfigurationCompleted msg)
Receive an RRCConnectionReconfigurationComplete message from a UE during an RRC connection reconfiguration procedure (Section 5.3.5 of TS 36.331).
virtual void RecvRrcConnectionReestablishmentComplete (uint16_t rnti, RrcConnectionReestablishmentComplete msg)
Receive an RRCConnectionReestablishmentComplete message from a UE during an RRC connection re-establishment procedure (Section 5.3.7 of TS 36.331).
virtual void RecvRrcConnectionReestablishmentRequest (uint16_t rnti, RrcConnectionReestablishmentRequest msg)
Receive an RRCConnectionReestablishmentRequest message from a UE during an RRC connection re-establishment procedure (Section 5.3.7 of TS 36.331).
virtual void RecvRrcConnectionRequest (uint16_t rnti, RrcConnectionRequest msg)
Receive an RRCConnectionRequest message from a UE during an RRC connection establishment procedure (Section 5.3.3 of TS 36.331).
virtual void RecvRrcConnectionSetupCompleted (uint16_t rnti, RrcConnectionSetupCompleted msg)
Receive an RRCConnectionSetupComplete message from a UE during an RRC connection establishment procedure (Section 5.3.3 of TS 36.331).
Public Member Functions inherited from ns3::LteRrcSap
virtual ~LteRrcSap ()
Private Member Functions
MemberLteEnbRrcSapProvider ()
Private Attributes
C * m_owner
the owner class
Additional Inherited Members
Public Types inherited from ns3::LteRrcSap
enum ReestablishmentCause { RECONFIGURATION_FAILURE, HANDOVER_FAILURE, OTHER_FAILURE }
ReestablishmentCause enumeration.
Static Public Member Functions inherited from ns3::LteRrcSap
static double ConvertPdschConfigDedicated2Double (PdschConfigDedicated pdschConfigDedicated)
Convert PDSCH config dedicated function.
Static Public Attributes inherited from ns3::LteRrcSap
static const uint8_t MaxReportCells = 8
Constraint values.
Detailed Description
template<class C>
class ns3::MemberLteEnbRrcSapProvider< C >
Template for the implementation of the LteEnbRrcSapProvider as a member of an owner class of type C to which all methods are forwarded.
Definition at line 1642 of file lte-rrc-sap.h.
Constructor & Destructor Documentation
MemberLteEnbRrcSapProvider() [1/2]
template<class C > ns3::MemberLteEnbRrcSapProvider< C >::MemberLteEnbRrcSapProvider (C * owner)
Constructor.
Parameters
owner
Definition at line 1669 of file lte-rrc-sap.h.
MemberLteEnbRrcSapProvider() [2/2]
template<class C > ns3::MemberLteEnbRrcSapProvider< C >::MemberLteEnbRrcSapProvider private
Definition at line 1675 of file lte-rrc-sap.h.
Member Function Documentation
CompleteSetupUe()
template<class C > void ns3::MemberLteEnbRrcSapProvider< C >::CompleteSetupUe (uint16_t rnti, CompleteSetupUeParameters params) virtual
Complete setup UE function.
Parameters
rnti the RNTI of UE which sent the message
params CompleteSetupUeParameters
Implements ns3::LteEnbRrcSapProvider.
Definition at line 1681 of file lte-rrc-sap.h.
References aloha::params.
RecvIdealUeContextRemoveRequest()
template<class C > void ns3::MemberLteEnbRrcSapProvider< C >::RecvIdealUeContextRemoveRequest (uint16_t rnti) virtual
Receive ideal UE context remove request from the UE RRC.
Receive the notification from UE to remove the UE context once radio link failure or random access failure is detected. It is needed since no RLF detection mechanism at eNodeB is implemented.
Parameters
rnti the C-RNTI of the UE
Implements ns3::LteEnbRrcSapProvider.
Definition at line 1729 of file lte-rrc-sap.h.
References ns3::Simulator::ScheduleNow().
RecvMeasurementReport()
template<class C > void ns3::MemberLteEnbRrcSapProvider< C >::RecvMeasurementReport (uint16_t rnti, MeasurementReport msg) virtual
Receive a MeasurementReport message from a UE during a measurement reporting procedure (Section 5.5.5 of TS 36.331).
Parameters
rnti the RNTI of UE which sent the message
msg the message
Implements ns3::LteEnbRrcSapProvider.
Definition at line 1723 of file lte-rrc-sap.h.
References ns3::Simulator::ScheduleNow().
RecvRrcConnectionReconfigurationCompleted()
template<class C > void ns3::MemberLteEnbRrcSapProvider< C >::RecvRrcConnectionReconfigurationCompleted (uint16_t rnti, RrcConnectionReconfigurationCompleted msg) virtual
Receive an RRCConnectionReconfigurationComplete message from a UE during an RRC connection reconfiguration procedure (Section 5.3.5 of TS 36.331).
Parameters
rnti the RNTI of UE which sent the message
msg the message
Implements ns3::LteEnbRrcSapProvider.
Definition at line 1702 of file lte-rrc-sap.h.
References ns3::Simulator::ScheduleNow().
RecvRrcConnectionReestablishmentComplete()
template<class C > void ns3::MemberLteEnbRrcSapProvider< C >::RecvRrcConnectionReestablishmentComplete (uint16_t rnti, RrcConnectionReestablishmentComplete msg) virtual
Receive an RRCConnectionReestablishmentComplete message from a UE during an RRC connection re-establishment procedure (Section 5.3.7 of TS 36.331).
Parameters
rnti the RNTI of UE which sent the message
msg the message
Implements ns3::LteEnbRrcSapProvider.
Definition at line 1716 of file lte-rrc-sap.h.
References ns3::Simulator::ScheduleNow().
RecvRrcConnectionReestablishmentRequest()
template<class C > void ns3::MemberLteEnbRrcSapProvider< C >::RecvRrcConnectionReestablishmentRequest (uint16_t rnti, RrcConnectionReestablishmentRequest msg) virtual
Receive an RRCConnectionReestablishmentRequest message from a UE during an RRC connection re-establishment procedure (Section 5.3.7 of TS 36.331).
Parameters
rnti the RNTI of UE which sent the message
msg the message
Implements ns3::LteEnbRrcSapProvider.
Definition at line 1709 of file lte-rrc-sap.h.
References ns3::Simulator::ScheduleNow().
RecvRrcConnectionRequest()
template<class C > void ns3::MemberLteEnbRrcSapProvider< C >::RecvRrcConnectionRequest (uint16_t rnti, RrcConnectionRequest msg) virtual
Receive an RRCConnectionRequest message from a UE during an RRC connection establishment procedure (Section 5.3.3 of TS 36.331).
Parameters
rnti the RNTI of UE which sent the message
msg the message
Implements ns3::LteEnbRrcSapProvider.
Definition at line 1688 of file lte-rrc-sap.h.
References ns3::Simulator::ScheduleNow().
RecvRrcConnectionSetupCompleted()
template<class C > void ns3::MemberLteEnbRrcSapProvider< C >::RecvRrcConnectionSetupCompleted (uint16_t rnti, RrcConnectionSetupCompleted msg) virtual
Receive an RRCConnectionSetupComplete message from a UE during an RRC connection establishment procedure (Section 5.3.3 of TS 36.331).
Parameters
rnti the RNTI of UE which sent the message
msg the message
Implements ns3::LteEnbRrcSapProvider.
Definition at line 1695 of file lte-rrc-sap.h.
References ns3::Simulator::ScheduleNow().
Member Data Documentation
m_owner
template<class C > C* ns3::MemberLteEnbRrcSapProvider< C >::m_owner private
the owner class
Definition at line 1665 of file lte-rrc-sap.h.
The documentation for this class was generated from the following file:
src/lte/model/lte-rrc-sap.h