ns-3: ns3::HybridBuildingsPropagationLossModel Class Reference
ns3::HybridBuildingsPropagationLossModel Class Reference
Propagation Models
The HybridBuildingsPropagationModel is a compound of different models able to evaluate the pathloss from 200 to 2600 MHz, in different environments and with buildings (i.e., indoor and outdoor communications).
#include "hybrid-buildings-propagation-loss-model.h"
Public Member Functions
HybridBuildingsPropagationLossModel ()
~HybridBuildingsPropagationLossModel ()
virtual double GetLoss (Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
void SetCitySize (CitySize size)
set the size of the city
void SetEnvironment (EnvironmentType env)
set the environment type
void SetFrequency (double freq)
set the propagation frequency
void SetRooftopHeight (double rooftopHeight)
set the rooftop height
Public Member Functions inherited from ns3::BuildingsPropagationLossModel
BuildingsPropagationLossModel ()
virtual double DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account only the particular PropagationLossModel.
Public Member Functions inherited from ns3::PropagationLossModel
PropagationLossModel ()
virtual ~PropagationLossModel ()
int64_t AssignStreams (int64_t stream)
If this loss model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
double CalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account all the PropagationLossModel(s) chained to the current one.
Ptr< PropagationLossModel > GetNext ()
Gets the next PropagationLossModel in the chain of loss models that act on the signal.
void SetNext (Ptr< PropagationLossModel > next)
Enables a chain of loss models to act on the signal.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::BuildingsPropagationLossModel
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::PropagationLossModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
double ItuR1238 (Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
double ItuR1411 (Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
double OkumuraHata (Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Private Attributes
double m_frequency
double m_itu1411NlosThreshold
in meters (switch Los -> NLoS)
Ptr< ItuR1238PropagationLossModel > m_ituR1238
Ptr< ItuR1411LosPropagationLossModel > m_ituR1411Los
Ptr< ItuR1411NlosOverRooftopPropagationLossModel > m_ituR1411NlosOverRooftop
Ptr< Kun2600MhzPropagationLossModel > m_kun2600Mhz
Ptr< OkumuraHataPropagationLossModel > m_okumuraHata
double m_rooftopHeight
Additional Inherited Members
Protected Member Functions inherited from ns3::BuildingsPropagationLossModel
virtual int64_t DoAssignStreams (int64_t stream)
Subclasses must implement this; those not using random variables can return zero.
double EvaluateSigma (Ptr< MobilityBuildingInfo > a, Ptr< MobilityBuildingInfo > b) const
double ExternalWallLoss (Ptr< MobilityBuildingInfo > a) const
double GetShadowing (Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
double HeightLoss (Ptr< MobilityBuildingInfo > n) const
double InternalWallsLoss (Ptr< MobilityBuildingInfo > a, Ptr< MobilityBuildingInfo > b) const
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::BuildingsPropagationLossModel
double m_lossInternalWall
Ptr< NormalRandomVariable > m_randVariable
std::map< Ptr< MobilityModel >, std::map< Ptr< MobilityModel >, ShadowingLoss > > m_shadowingLossMap
double m_shadowingSigmaExtWalls
double m_shadowingSigmaIndoor
double m_shadowingSigmaOutdoor
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The HybridBuildingsPropagationModel is a compound of different models able to evaluate the pathloss from 200 to 2600 MHz, in different environments and with buildings (i.e., indoor and outdoor communications).
This model includes Hata model, COST231, ITU-R P.1411 (short range communications), ITU-R P.1238 (indoor communications), which are combined in order to be able to evaluate the pathloss under different scenarios, in detail:
Environments: urban, suburban, open-areas;
frequency: from 200 uo to 2600 MHz
short range communications vs long range communications
Node position respect to buildings: indoor, outdoor and hybrid (indoor <-> outdoor)
Building penetretation loss
floors, etc...
Warning
This model works only with MobilityBuildingInfo
Definition at line 56 of file hybrid-buildings-propagation-loss-model.h.
Constructor & Destructor Documentation
HybridBuildingsPropagationLossModel()
ns3::HybridBuildingsPropagationLossModel::HybridBuildingsPropagationLossModel ()
Definition at line 48 of file hybrid-buildings-propagation-loss-model.cc.
References m_ituR1238, m_ituR1411Los, m_ituR1411NlosOverRooftop, m_kun2600Mhz, and m_okumuraHata.
~HybridBuildingsPropagationLossModel()
ns3::HybridBuildingsPropagationLossModel::~HybridBuildingsPropagationLossModel ()
Definition at line 57 of file hybrid-buildings-propagation-loss-model.cc.
Member Function Documentation
GetLoss()
double ns3::HybridBuildingsPropagationLossModel::GetLoss (Ptr< MobilityModel > a, Ptr< MobilityModel > b) const virtual
Parameters
a the mobility model of the source
b the mobility model of the destination
Returns
the propagation loss (in dBm)
Implements ns3::BuildingsPropagationLossModel.
Definition at line 143 of file hybrid-buildings-propagation-loss-model.cc.
References ns3::BuildingsPropagationLossModel::ExternalWallLoss(), ns3::MobilityModel::GetDistanceFrom(), ns3::Object::GetObject(), ns3::MobilityModel::GetPosition(), ns3::BuildingsPropagationLossModel::HeightLoss(), ns3::BuildingsPropagationLossModel::InternalWallsLoss(), ItuR1238(), ItuR1411(), m_rooftopHeight, max, NS_ASSERT_MSG(), NS_LOG_INFO, and OkumuraHata().
Referenced by BuildingsPathlossTestCase::DoRun().
GetTypeId()
TypeId ns3::HybridBuildingsPropagationLossModel::GetTypeId (void) static
Definition at line 62 of file hybrid-buildings-propagation-loss-model.cc.
References ns3::LargeCity, m_itu1411NlosThreshold, ns3::MakeDoubleAccessor(), ns3::MakeEnumAccessor(), ns3::MakeEnumChecker(), ns3::MediumCity, ns3::OpenAreasEnvironment, SetCitySize(), SetEnvironment(), SetFrequency(), ns3::TypeId::SetParent(), SetRooftopHeight(), ns3::SmallCity, ns3::SubUrbanEnvironment, and ns3::UrbanEnvironment.
ItuR1238()
double ns3::HybridBuildingsPropagationLossModel::ItuR1238 (Ptr< MobilityModel > a, Ptr< MobilityModel > b) const private
Definition at line 289 of file hybrid-buildings-propagation-loss-model.cc.
References m_ituR1238.
Referenced by GetLoss().
ItuR1411()
double ns3::HybridBuildingsPropagationLossModel::ItuR1411 (Ptr< MobilityModel > a, Ptr< MobilityModel > b) const private
Definition at line 276 of file hybrid-buildings-propagation-loss-model.cc.
References ns3::MobilityModel::GetDistanceFrom(), m_itu1411NlosThreshold, m_ituR1411Los, and m_ituR1411NlosOverRooftop.
Referenced by GetLoss().
OkumuraHata()
double ns3::HybridBuildingsPropagationLossModel::OkumuraHata (Ptr< MobilityModel > a, Ptr< MobilityModel > b) const private
Definition at line 263 of file hybrid-buildings-propagation-loss-model.cc.
References m_frequency, m_kun2600Mhz, and m_okumuraHata.
Referenced by GetLoss().
SetCitySize()
void ns3::HybridBuildingsPropagationLossModel::SetCitySize (CitySize size)
set the size of the city
Parameters
size
Definition at line 118 of file hybrid-buildings-propagation-loss-model.cc.
References m_ituR1411NlosOverRooftop, and m_okumuraHata.
Referenced by GetTypeId().
SetEnvironment()
void ns3::HybridBuildingsPropagationLossModel::SetEnvironment (EnvironmentType env)
set the environment type
Parameters
env
Definition at line 111 of file hybrid-buildings-propagation-loss-model.cc.
References m_ituR1411NlosOverRooftop, and m_okumuraHata.
Referenced by GetTypeId().
SetFrequency()
void ns3::HybridBuildingsPropagationLossModel::SetFrequency (double freq)
set the propagation frequency
Parameters
freq
Definition at line 125 of file hybrid-buildings-propagation-loss-model.cc.
References m_frequency, m_ituR1238, m_ituR1411Los, m_ituR1411NlosOverRooftop, and m_okumuraHata.
Referenced by GetTypeId().
SetRooftopHeight()
void ns3::HybridBuildingsPropagationLossModel::SetRooftopHeight (double rooftopHeight)
set the rooftop height
Parameters
rooftopHeight
Definition at line 135 of file hybrid-buildings-propagation-loss-model.cc.
References m_ituR1411NlosOverRooftop, and m_rooftopHeight.
Referenced by GetTypeId().
Member Data Documentation
m_frequency
double ns3::HybridBuildingsPropagationLossModel::m_frequency private
Definition at line 115 of file hybrid-buildings-propagation-loss-model.h.
Referenced by OkumuraHata(), and SetFrequency().
m_itu1411NlosThreshold
double ns3::HybridBuildingsPropagationLossModel::m_itu1411NlosThreshold private
in meters (switch Los -> NLoS)
Definition at line 113 of file hybrid-buildings-propagation-loss-model.h.
Referenced by GetTypeId(), and ItuR1411().
m_ituR1238
Ptr<ItuR1238PropagationLossModel> ns3::HybridBuildingsPropagationLossModel::m_ituR1238 private
Definition at line 110 of file hybrid-buildings-propagation-loss-model.h.
Referenced by HybridBuildingsPropagationLossModel(), ItuR1238(), and SetFrequency().
m_ituR1411Los
Ptr<ItuR1411LosPropagationLossModel> ns3::HybridBuildingsPropagationLossModel::m_ituR1411Los private
Definition at line 108 of file hybrid-buildings-propagation-loss-model.h.
Referenced by HybridBuildingsPropagationLossModel(), ItuR1411(), and SetFrequency().
m_ituR1411NlosOverRooftop
Ptr<ItuR1411NlosOverRooftopPropagationLossModel> ns3::HybridBuildingsPropagationLossModel::m_ituR1411NlosOverRooftop private
Definition at line 109 of file hybrid-buildings-propagation-loss-model.h.
Referenced by HybridBuildingsPropagationLossModel(), ItuR1411(), SetCitySize(), SetEnvironment(), SetFrequency(), and SetRooftopHeight().
m_kun2600Mhz
Ptr<Kun2600MhzPropagationLossModel> ns3::HybridBuildingsPropagationLossModel::m_kun2600Mhz private
Definition at line 111 of file hybrid-buildings-propagation-loss-model.h.
Referenced by HybridBuildingsPropagationLossModel(), and OkumuraHata().
m_okumuraHata
Ptr<OkumuraHataPropagationLossModel> ns3::HybridBuildingsPropagationLossModel::m_okumuraHata private
Definition at line 107 of file hybrid-buildings-propagation-loss-model.h.
Referenced by HybridBuildingsPropagationLossModel(), OkumuraHata(), SetCitySize(), SetEnvironment(), and SetFrequency().
m_rooftopHeight
double ns3::HybridBuildingsPropagationLossModel::m_rooftopHeight private
Definition at line 114 of file hybrid-buildings-propagation-loss-model.h.
Referenced by GetLoss(), and SetRooftopHeight().
The documentation for this class was generated from the following files:
src/buildings/model/hybrid-buildings-propagation-loss-model.h
src/buildings/model/hybrid-buildings-propagation-loss-model.cc