ns-3: ns3::EpcX2SapProvider Class Reference
ns3::EpcX2SapProvider Class Reference abstract
These service primitives of this part of the X2 SAP are provided by the X2 entity and issued by RRC entity.
#include "epc-x2-sap.h"
Public Member Functions
virtual ~EpcX2SapProvider ()
virtual void SendHandoverPreparationFailure (HandoverPreparationFailureParams params)=0
Send handover preparation failure function.
virtual void SendHandoverRequest (HandoverRequestParams params)=0
Send handover request function.
virtual void SendHandoverRequestAck (HandoverRequestAckParams params)=0
Send handover request ack function.
virtual void SendLoadInformation (LoadInformationParams params)=0
Send load information function.
virtual void SendResourceStatusUpdate (ResourceStatusUpdateParams params)=0
Send resource status update function.
virtual void SendSnStatusTransfer (SnStatusTransferParams params)=0
Send SN status transfer function.
virtual void SendUeContextRelease (UeContextReleaseParams params)=0
Send UE context release function.
virtual void SendUeData (UeDataParams params)=0
Send UE data function.
Public Member Functions inherited from ns3::EpcX2Sap
virtual ~EpcX2Sap ()
Additional Inherited Members
Public Types inherited from ns3::EpcX2Sap
enum IdCause { HandoverDesirableForRadioReason, TimeCriticalHandover }
Cause ID enumeration.
enum LoadIndicator { LowLoad, MediumLoad, HighLoad, Overload }
Load Indicator as it is used in the RESOURCE STATUS UPDATE message.
enum UlInterferenceOverloadIndicationItem { HighInterference, MediumInterference, LowInterference }
UL Interference OverloadIndication as it is used in the LOAD INFORMATION message.
Static Public Attributes inherited from ns3::EpcX2Sap
static const uint16_t m_maxPdcpSn = 4096
E-RABs subject to status transfer item as it is used in the SN STATUS TRANSFER message.
Detailed Description
These service primitives of this part of the X2 SAP are provided by the X2 entity and issued by RRC entity.
Definition at line 343 of file epc-x2-sap.h.
Constructor & Destructor Documentation
~EpcX2SapProvider()
ns3::EpcX2SapProvider::~EpcX2SapProvider () virtual
Definition at line 35 of file epc-x2-sap.cc.
Member Function Documentation
SendHandoverPreparationFailure()
virtual void ns3::EpcX2SapProvider::SendHandoverPreparationFailure (HandoverPreparationFailureParams params) pure virtual
Send handover preparation failure function.
Parameters
params the handover preparation failure
Implemented in ns3::EpcX2SpecificEpcX2SapProvider< C >.
Referenced by ns3::LteEnbRrc::DoRecvHandoverRequest().
SendHandoverRequest()
virtual void ns3::EpcX2SapProvider::SendHandoverRequest (HandoverRequestParams params) pure virtual
Send handover request function.
Parameters
params handover request parameters
Implemented in ns3::EpcX2SpecificEpcX2SapProvider< C >.
SendHandoverRequestAck()
virtual void ns3::EpcX2SapProvider::SendHandoverRequestAck (HandoverRequestAckParams params) pure virtual
Send handover request ack function.
Parameters
params the handover request ack parameters
Implemented in ns3::EpcX2SpecificEpcX2SapProvider< C >.
Referenced by ns3::LteEnbRrc::DoRecvHandoverRequest().
SendLoadInformation()
virtual void ns3::EpcX2SapProvider::SendLoadInformation (LoadInformationParams params) pure virtual
Send load information function.
Parameters
params the load information parameters
Implemented in ns3::EpcX2SpecificEpcX2SapProvider< C >.
Referenced by ns3::LteEnbRrc::DoSendLoadInformation().
SendResourceStatusUpdate()
virtual void ns3::EpcX2SapProvider::SendResourceStatusUpdate (ResourceStatusUpdateParams params) pure virtual
Send resource status update function.
Parameters
params the resource statue update paramweters
Implemented in ns3::EpcX2SpecificEpcX2SapProvider< C >.
SendSnStatusTransfer()
virtual void ns3::EpcX2SapProvider::SendSnStatusTransfer (SnStatusTransferParams params) pure virtual
Send SN status transfer function.
Parameters
params the SN status transfer parameters
Implemented in ns3::EpcX2SpecificEpcX2SapProvider< C >.
SendUeContextRelease()
virtual void ns3::EpcX2SapProvider::SendUeContextRelease (UeContextReleaseParams params) pure virtual
Send UE context release function.
Parameters
params the UE context release parameters
Implemented in ns3::EpcX2SpecificEpcX2SapProvider< C >.
SendUeData()
virtual void ns3::EpcX2SapProvider::SendUeData (UeDataParams params) pure virtual
Send UE data function.
Parameters
params the UE data parameters
Implemented in ns3::EpcX2SpecificEpcX2SapProvider< C >.
The documentation for this class was generated from the following files:
src/lte/model/epc-x2-sap.h
src/lte/model/epc-x2-sap.cc