ns-3: ns3::dsr::DsrOptionRerrUnsupportHeader Class Reference
ns3::dsr::DsrOptionRerrUnsupportHeader Class Reference
DSR Routing
Route Error (RERR) Unsupported option Message Format.
#include "dsr-option-header.h"
Public Member Functions
DsrOptionRerrUnsupportHeader ()
Constructor.
virtual ~DsrOptionRerrUnsupportHeader ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
virtual Alignment GetAlignment () const
Get the Alignment requirement of this option header.
virtual Ipv4Address GetErrorDst () const
Get the error destination ip address.
virtual Ipv4Address GetErrorSrc () const
Get the route error source address.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
virtual uint8_t GetSalvage () const
Get the salvage value of the packet.
virtual uint32_t GetSerializedSize () const
Get the serialized size of the packet.
uint16_t GetUnsupported () const
Get the unsupported option type value.
virtual void Print (std::ostream &os) const
Print some information about the packet.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
virtual void SetErrorDst (Ipv4Address errorDstAddress)
Set the error destination ip address.
virtual void SetErrorSrc (Ipv4Address errorSrcAddress)
Set the route error source address.
virtual void SetSalvage (uint8_t salvage)
Set the salvage value of the packet.
void SetUnsupported (uint16_t optionType)
Set the unsupported option type value.
Public Member Functions inherited from ns3::dsr::DsrOptionRerrHeader
DsrOptionRerrHeader ()
Constructor.
virtual ~DsrOptionRerrHeader ()
Destructor.
uint8_t GetErrorType () const
Get the route error type.
void SetErrorType (uint8_t errorType)
Set the route error type.
Public Member Functions inherited from ns3::dsr::DsrOptionHeader
DsrOptionHeader ()
Constructor.
virtual ~DsrOptionHeader ()
Destructor.
uint8_t GetLength () const
Get the option length.
uint8_t GetType () const
Get the type of the option.
void SetLength (uint8_t length)
Set the option length.
void SetType (uint8_t type)
Set the type of the option.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::dsr::DsrOptionRerrHeader
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::dsr::DsrOptionHeader
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Ipv4Address m_errorDstAddress
The error destination address.
Ipv4Address m_errorSrcAddress
The error source address.
uint8_t m_errorType
The error type or route error option.
uint8_t m_salvage
The salavage field.
uint16_t m_unsupport
The unsupported option.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Route Error (RERR) Unsupported option Message Format.
 |      0        |      1        |      2        |      3        |
 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |  Option Type |  Opt Data Len |   Error Type  |Reservd| Salvage|
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                      Error Source Address                     |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                    Error Destination Address                  |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 .                                                               .
 .                    Type-Specific Information                  .
 .                                                               .
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 1037 of file dsr-option-header.h.
Constructor & Destructor Documentation
DsrOptionRerrUnsupportHeader()
ns3::dsr::DsrOptionRerrUnsupportHeader::DsrOptionRerrUnsupportHeader ()
Constructor.
Definition at line 930 of file dsr-option-header.cc.
References ns3::dsr::DsrOptionRerrHeader::SetErrorType(), ns3::dsr::DsrOptionHeader::SetLength(), and ns3::dsr::DsrOptionHeader::SetType().
~DsrOptionRerrUnsupportHeader()
ns3::dsr::DsrOptionRerrUnsupportHeader::~DsrOptionRerrUnsupportHeader () virtual
Destructor.
Definition at line 938 of file dsr-option-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::dsr::DsrOptionRerrUnsupportHeader::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start Buffer iterator
Returns
size of the packet
Reimplemented from ns3::dsr::DsrOptionRerrHeader.
Definition at line 1010 of file dsr-option-header.cc.
References GetSerializedSize(), m_errorDstAddress, m_errorSrcAddress, m_salvage, m_unsupport, ns3::ReadFrom(), ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU8(), ns3::dsr::DsrOptionRerrHeader::SetErrorType(), ns3::dsr::DsrOptionHeader::SetLength(), ns3::dsr::DsrOptionHeader::SetType(), and visualizer.core::start().
GetAlignment()
DsrOptionHeader::Alignment ns3::dsr::DsrOptionRerrUnsupportHeader::GetAlignment () const virtual
Get the Alignment requirement of this option header.
Returns
The required alignment
Reimplemented from ns3::dsr::DsrOptionRerrHeader.
Definition at line 1025 of file dsr-option-header.cc.
GetErrorDst()
Ipv4Address ns3::dsr::DsrOptionRerrUnsupportHeader::GetErrorDst () const virtual
Get the error destination ip address.
Returns
The error destination address
Reimplemented from ns3::dsr::DsrOptionRerrHeader.
Definition at line 967 of file dsr-option-header.cc.
References m_errorDstAddress.
GetErrorSrc()
Ipv4Address ns3::dsr::DsrOptionRerrUnsupportHeader::GetErrorSrc () const virtual
Get the route error source address.
Returns
The error source address
Reimplemented from ns3::dsr::DsrOptionRerrHeader.
Definition at line 957 of file dsr-option-header.cc.
References m_errorSrcAddress.
GetInstanceTypeId()
TypeId ns3::dsr::DsrOptionRerrUnsupportHeader::GetInstanceTypeId () const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::dsr::DsrOptionRerrHeader.
Definition at line 925 of file dsr-option-header.cc.
References GetTypeId().
GetSalvage()
uint8_t ns3::dsr::DsrOptionRerrUnsupportHeader::GetSalvage () const virtual
Get the salvage value of the packet.
Returns
The salvage value of the packet
Reimplemented from ns3::dsr::DsrOptionRerrHeader.
Definition at line 947 of file dsr-option-header.cc.
References m_salvage.
GetSerializedSize()
uint32_t ns3::dsr::DsrOptionRerrUnsupportHeader::GetSerializedSize () const virtual
Get the serialized size of the packet.
Returns
size
Reimplemented from ns3::dsr::DsrOptionRerrHeader.
Definition at line 991 of file dsr-option-header.cc.
Referenced by Deserialize(), and ns3::dsr::DsrOptionRerr::Process().
GetTypeId()
TypeId ns3::dsr::DsrOptionRerrUnsupportHeader::GetTypeId () static
Get the type identificator.
Returns
type identificator
Definition at line 915 of file dsr-option-header.cc.
References ns3::TypeId::AddConstructor().
Referenced by GetInstanceTypeId().
GetUnsupported()
uint16_t ns3::dsr::DsrOptionRerrUnsupportHeader::GetUnsupported () const
Get the unsupported option type value.
Returns
The unsupported option type value
Definition at line 977 of file dsr-option-header.cc.
References m_unsupport.
Print()
void ns3::dsr::DsrOptionRerrUnsupportHeader::Print (std::ostream & os) const virtual
Print some information about the packet.
Parameters
os output stream
Returns
info about this packet
Reimplemented from ns3::dsr::DsrOptionRerrHeader.
Definition at line 982 of file dsr-option-header.cc.
References ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrOptionHeader::GetType(), m_errorDstAddress, m_errorSrcAddress, m_errorType, m_salvage, and m_unsupport.
Serialize()
void ns3::dsr::DsrOptionRerrUnsupportHeader::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start Buffer iterator
Reimplemented from ns3::dsr::DsrOptionRerrHeader.
Definition at line 996 of file dsr-option-header.cc.
References ns3::dsr::DsrOptionRerrHeader::GetErrorType(), ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrOptionHeader::GetType(), m_errorDstAddress, m_errorSrcAddress, m_salvage, m_unsupport, visualizer.core::start(), ns3::WriteTo(), ns3::Buffer::Iterator::WriteU16(), and ns3::Buffer::Iterator::WriteU8().
SetErrorDst()
void ns3::dsr::DsrOptionRerrUnsupportHeader::SetErrorDst (Ipv4Address errorDstAddress) virtual
Set the error destination ip address.
Parameters
errorDstAddress The error destination address
Reimplemented from ns3::dsr::DsrOptionRerrHeader.
Definition at line 962 of file dsr-option-header.cc.
References m_errorDstAddress.
SetErrorSrc()
void ns3::dsr::DsrOptionRerrUnsupportHeader::SetErrorSrc (Ipv4Address errorSrcAddress) virtual
Set the route error source address.
Parameters
errorSrcAddress The error source address
Reimplemented from ns3::dsr::DsrOptionRerrHeader.
Definition at line 952 of file dsr-option-header.cc.
References m_errorSrcAddress.
SetSalvage()
void ns3::dsr::DsrOptionRerrUnsupportHeader::SetSalvage (uint8_t salvage) virtual
Set the salvage value of the packet.
Parameters
salvage the salvage value
Reimplemented from ns3::dsr::DsrOptionRerrHeader.
Definition at line 942 of file dsr-option-header.cc.
References m_salvage.
SetUnsupported()
void ns3::dsr::DsrOptionRerrUnsupportHeader::SetUnsupported (uint16_t optionType)
Set the unsupported option type value.
Parameters
optionType The unsupported option type value
Definition at line 972 of file dsr-option-header.cc.
References m_unsupport.
Member Data Documentation
m_errorDstAddress
Ipv4Address ns3::dsr::DsrOptionRerrUnsupportHeader::m_errorDstAddress private
The error destination address.
Definition at line 1142 of file dsr-option-header.h.
Referenced by Deserialize(), GetErrorDst(), Print(), Serialize(), and SetErrorDst().
m_errorSrcAddress
Ipv4Address ns3::dsr::DsrOptionRerrUnsupportHeader::m_errorSrcAddress private
The error source address.
Definition at line 1138 of file dsr-option-header.h.
Referenced by Deserialize(), GetErrorSrc(), Print(), Serialize(), and SetErrorSrc().
m_errorType
uint8_t ns3::dsr::DsrOptionRerrUnsupportHeader::m_errorType private
The error type or route error option.
Definition at line 1130 of file dsr-option-header.h.
Referenced by Print().
m_salvage
uint8_t ns3::dsr::DsrOptionRerrUnsupportHeader::m_salvage private
The salavage field.
Definition at line 1134 of file dsr-option-header.h.
Referenced by Deserialize(), GetSalvage(), Print(), Serialize(), and SetSalvage().
m_unsupport
uint16_t ns3::dsr::DsrOptionRerrUnsupportHeader::m_unsupport private
The unsupported option.
Definition at line 1146 of file dsr-option-header.h.
Referenced by Deserialize(), GetUnsupported(), Print(), Serialize(), and SetUnsupported().
The documentation for this class was generated from the following files:
src/dsr/model/dsr-option-header.h
src/dsr/model/dsr-option-header.cc