ns-3: ns3::Icmpv4TimeExceeded Class Reference
ns3::Icmpv4TimeExceeded Class Reference
Internet » IPv4 classes and sub-modules » ICMP protocol and associated headers.
ICMP Time Exceeded header.
#include "icmpv4.h"
Public Types
enum ErrorTimeExceeded_e { ICMPV4_TIME_TO_LIVE = 0, ICMPV4_FRAGMENT_REASSEMBLY = 1 }
ICMP error code : Time Exceeded.
Public Member Functions
Icmpv4TimeExceeded ()
virtual ~Icmpv4TimeExceeded ()
virtual uint32_t Deserialize (Buffer::Iterator start)
void GetData (uint8_t payload[8]) const
Get the ICMP carried data.
Ipv4Header GetHeader (void) const
Get the ICMP carried IPv4 header.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetData (Ptr< const Packet > data)
Get the ICMP carried data.
void SetHeader (Ipv4Header header)
Set the ICMP carried IPv4 header.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get ICMP type.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_data [8]
carried data
Ipv4Header m_header
carried IPv4 header
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
ICMP Time Exceeded header.
Definition at line 246 of file icmpv4.h.
Member Enumeration Documentation
ErrorTimeExceeded_e
enum ns3::Icmpv4TimeExceeded::ErrorTimeExceeded_e
ICMP error code : Time Exceeded.
Enumerator
ICMPV4_TIME_TO_LIVE
ICMPV4_FRAGMENT_REASSEMBLY
Definition at line 252 of file icmpv4.h.
Constructor & Destructor Documentation
Icmpv4TimeExceeded()
ns3::Icmpv4TimeExceeded::Icmpv4TimeExceeded ()
Definition at line 413 of file icmpv4.cc.
References m_data, and NS_LOG_FUNCTION.
~Icmpv4TimeExceeded()
ns3::Icmpv4TimeExceeded::~Icmpv4TimeExceeded () virtual
Definition at line 451 of file icmpv4.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Deserialize()
uint32_t ns3::Icmpv4TimeExceeded::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 479 of file icmpv4.cc.
References ns3::Ipv4Header::Deserialize(), ns3::Buffer::Iterator::GetDistanceFrom(), m_data, m_header, ns3::Buffer::Iterator::Next(), NS_LOG_FUNCTION, ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetData()
void ns3::Icmpv4TimeExceeded::GetData (uint8_t payload[8]) const
Get the ICMP carried data.
Parameters
payload the data (filled)
Definition at line 438 of file icmpv4.cc.
References m_data, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv4L4Protocol::Receive(), and ns3::V4TraceRoute::Receive().
GetHeader()
Ipv4Header ns3::Icmpv4TimeExceeded::GetHeader (void) const
Get the ICMP carried IPv4 header.
Returns
the header
Definition at line 444 of file icmpv4.cc.
References m_header, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv4L4Protocol::Receive().
GetInstanceTypeId()
TypeId ns3::Icmpv4TimeExceeded::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 456 of file icmpv4.cc.
References GetTypeId(), and NS_LOG_FUNCTION.
GetSerializedSize()
uint32_t ns3::Icmpv4TimeExceeded::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 462 of file icmpv4.cc.
References ns3::Ipv4Header::GetSerializedSize(), m_header, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::Icmpv4TimeExceeded::GetTypeId (void) static
Get ICMP type.
Returns
the ICMP type
Definition at line 404 of file icmpv4.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::Icmpv4TimeExceeded::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 493 of file icmpv4.cc.
References m_data, m_header, NS_LOG_FUNCTION, and ns3::Ipv4Header::Print().
Serialize()
void ns3::Icmpv4TimeExceeded::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 468 of file icmpv4.cc.
References ns3::Ipv4Header::GetSerializedSize(), m_data, m_header, NS_LOG_FUNCTION, ns3::Ipv4Header::Serialize(), and visualizer.core::start().
SetData()
void ns3::Icmpv4TimeExceeded::SetData (Ptr< const Packet > data)
Get the ICMP carried data.
Parameters
data the data
Definition at line 426 of file icmpv4.cc.
References data, m_data, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv4L4Protocol::SendTimeExceededTtl().
SetHeader()
void ns3::Icmpv4TimeExceeded::SetHeader (Ipv4Header header)
Set the ICMP carried IPv4 header.
Parameters
header the header
Definition at line 432 of file icmpv4.cc.
References m_header, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv4L4Protocol::SendTimeExceededTtl().
Member Data Documentation
m_data
uint8_t ns3::Icmpv4TimeExceeded::m_data[8] private
carried data
Definition at line 295 of file icmpv4.h.
Referenced by Icmpv4TimeExceeded(), Deserialize(), GetData(), Print(), Serialize(), and SetData().
m_header
Ipv4Header ns3::Icmpv4TimeExceeded::m_header private
carried IPv4 header
Definition at line 294 of file icmpv4.h.
Referenced by Deserialize(), GetHeader(), GetSerializedSize(), Print(), Serialize(), and SetHeader().
The documentation for this class was generated from the following files:
src/internet/model/icmpv4.h
src/internet/model/icmpv4.cc