ns-3: ns3::UanPhy Class Reference
ns3::UanPhy Class Reference abstract
UAN Models
#include "uan-phy.h"
Public Types
typedef Callback< void, Ptr< Packet >, double > RxErrCallback
Packet receive error callback function type.
typedef Callback< void, Ptr< Packet >, double, UanTxMode > RxOkCallback
Packet received successfully callback function type.
enum State {
IDLE, CCABUSY, RX, TX,
SLEEP, DISABLED
}
Enum defining possible Phy states.
typedef void(* TracedCallback) (Ptr< const Packet > pkt, double sinr, UanTxMode mode)
TracedCallback signature for UanPhy packet send/receive events.
Public Member Functions
virtual int64_t AssignStreams (int64_t stream)=0
Assign a fixed random variable stream number to the random variables used by this model.
virtual void Clear (void)=0
Clear all pointer references.
virtual void EnergyDepletionHandler (void)=0
Handle the energy depletion event.
virtual void EnergyRechargeHandler (void)=0
Handle the energy recharge event.
virtual double GetCcaThresholdDb (void)=0
Get the CCA threshold signal strength required to detect channel busy.
virtual Ptr< UanChannel > GetChannel (void) const =0
Get the attached channel.
virtual Ptr< UanNetDevice > GetDevice (void) const =0
Get the device hosting this Phy.
virtual UanTxMode GetMode (uint32_t n)=0
Get a specific transmission mode.
virtual uint32_t GetNModes (void)=0
Get the number of transmission modes supported by this Phy.
virtual Ptr< Packet > GetPacketRx (void) const =0
Get the packet currently being received.
virtual double GetRxThresholdDb (void)=0
Get the minimum received signal strength required to receive a packet without errors.
virtual Ptr< UanTransducer > GetTransducer (void)=0
Get the attached transducer.
virtual double GetTxPowerDb (void)=0
Get the current transmit power, in dB.
virtual bool IsStateBusy (void)=0
virtual bool IsStateCcaBusy (void)=0
virtual bool IsStateIdle (void)=0
virtual bool IsStateRx (void)=0
virtual bool IsStateSleep (void)=0
virtual bool IsStateTx (void)=0
virtual void NotifyIntChange (void)=0
Called when there has been a change in the amount of interference this node is experiencing from other transmissions.
void NotifyRxBegin (Ptr< const Packet > packet)
Called when the Phy begins to receive a packet.
void NotifyRxDrop (Ptr< const Packet > packet)
Called when the Phy drops a packet.
void NotifyRxEnd (Ptr< const Packet > packet)
Called when a packet is received without error.
virtual void NotifyTransStartTx (Ptr< Packet > packet, double txPowerDb, UanTxMode txMode)=0
Called when a transmission is beginning on the attached transducer.
void NotifyTxBegin (Ptr< const Packet > packet)
Called when the transducer begins transmitting a packet.
void NotifyTxDrop (Ptr< const Packet > packet)
Called when the transducer attempts to transmit a new packet while already transmitting a prior packet.
void NotifyTxEnd (Ptr< const Packet > packet)
Called when the transducer finishes transmitting a packet.
virtual void RegisterListener (UanPhyListener *listener)=0
Register a UanPhyListener to be notified of common UanPhy events.
virtual void SendPacket (Ptr< Packet > pkt, uint32_t modeNum)=0
Send a packet using a specific transmission mode.
virtual void SetCcaThresholdDb (double thresh)=0
Set the threshold for detecting channel busy.
virtual void SetChannel (Ptr< UanChannel > channel)=0
Attach to a channel.
virtual void SetDevice (Ptr< UanNetDevice > device)=0
Set the device hosting this Phy.
virtual void SetEnergyModelCallback (DeviceEnergyModel::ChangeStateCallback callback)=0
Set the DeviceEnergyModel callback for UanPhy device.
virtual void SetMac (Ptr< UanMac > mac)=0
Set the MAC forwarding messages to this Phy.
virtual void SetReceiveErrorCallback (RxErrCallback cb)=0
Set the callback to be used when a packet is received with errors.
virtual void SetReceiveOkCallback (RxOkCallback cb)=0
Set the callback to be used when a packet is received without error.
virtual void SetRxThresholdDb (double thresh)=0
Set the minimum SINR threshold to receive a packet without errors.
virtual void SetSleepMode (bool sleep)=0
Set the Phy SLEEP mode.
virtual void SetTransducer (Ptr< UanTransducer > trans)=0
Attach a transducer to this Phy.
virtual void SetTxPowerDb (double txpwr)=0
Set the transmit power.
virtual void StartRxPacket (Ptr< Packet > pkt, double rxPowerDb, UanTxMode txMode, UanPdp pdp)=0
Packet arriving from channel: i.e.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
ns3::TracedCallback< Ptr< const Packet > > m_phyRxBeginTrace
Trace source indicating a packet has begun being received from the channel medium by the device.
ns3::TracedCallback< Ptr< const Packet > > m_phyRxDropTrace
Trace source indicating a packet has been dropped by the device during reception.
ns3::TracedCallback< Ptr< const Packet > > m_phyRxEndTrace
Trace source indicating a packet has been completely received from the channel medium by the device.
ns3::TracedCallback< Ptr< const Packet > > m_phyTxBeginTrace
Trace source indicating a packet has begun transmitting over the channel medium.
ns3::TracedCallback< Ptr< const Packet > > m_phyTxDropTrace
Trace source indicating a packet has been dropped by the device during transmission.
ns3::TracedCallback< Ptr< const Packet > > m_phyTxEndTrace
Trace source indicating a packet has been completely transmitted over the channel.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Base class for UAN Phy models.
Definition at line 175 of file uan-phy.h.
Member Typedef Documentation
RxErrCallback
typedef Callback<void, Ptr<Packet>, double > ns3::UanPhy::RxErrCallback
Packet receive error callback function type.
arg1 Packet received successfully. arg2 SNIR of packet.
Definition at line 204 of file uan-phy.h.
RxOkCallback
typedef Callback<void, Ptr<Packet>, double, UanTxMode> ns3::UanPhy::RxOkCallback
Packet received successfully callback function type.
arg1 Packet received successfully. arg2 SNIR of packet. arg3 Mode of packet.
Definition at line 196 of file uan-phy.h.
TracedCallback
typedef void(* ns3::UanPhy::TracedCallback) (Ptr< const Packet > pkt, double sinr, UanTxMode mode)
TracedCallback signature for UanPhy packet send/receive events.
Parameters
[in] pkt The packet.
[in] sinr The SINR.
[in] mode The channel mode.
Definition at line 213 of file uan-phy.h.
Member Enumeration Documentation
State
enum ns3::UanPhy::State
Enum defining possible Phy states.
Enumerator
IDLE
Idle state.
CCABUSY
Channel busy.
RX
Receiving.
TX
Transmitting.
SLEEP
Sleeping.
DISABLED
Disabled.
Definition at line 179 of file uan-phy.h.
Member Function Documentation
AssignStreams()
virtual int64_t ns3::UanPhy::AssignStreams (int64_t stream) pure virtual
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream First stream index to use.
Returns
The number of stream indices assigned by this model.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
Clear()
virtual void ns3::UanPhy::Clear (void) pure virtual
Clear all pointer references.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
EnergyDepletionHandler()
virtual void ns3::UanPhy::EnergyDepletionHandler (void) pure virtual
Handle the energy depletion event.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
EnergyRechargeHandler()
virtual void ns3::UanPhy::EnergyRechargeHandler (void) pure virtual
Handle the energy recharge event.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
GetCcaThresholdDb()
virtual double ns3::UanPhy::GetCcaThresholdDb (void) pure virtual
Get the CCA threshold signal strength required to detect channel busy.
Returns
The CCA threshold signal strength in dB.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
GetChannel()
virtual Ptr<UanChannel> ns3::UanPhy::GetChannel (void) const pure virtual
Get the attached channel.
Returns
The channel.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
GetDevice()
virtual Ptr<UanNetDevice> ns3::UanPhy::GetDevice (void) const pure virtual
Get the device hosting this Phy.
Returns
The net device.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
GetMode()
virtual UanTxMode ns3::UanPhy::GetMode (uint32_t n) pure virtual
Get a specific transmission mode.
Parameters
n The mode number.
Returns
The mode.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
GetNModes()
virtual uint32_t ns3::UanPhy::GetNModes (void) pure virtual
Get the number of transmission modes supported by this Phy.
Returns
The number modes.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
GetPacketRx()
virtual Ptr<Packet> ns3::UanPhy::GetPacketRx (void) const pure virtual
Get the packet currently being received.
Warning
Returns non-valid pointer if IsStateRx == false.
Returns
The packet.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
GetRxThresholdDb()
virtual double ns3::UanPhy::GetRxThresholdDb (void) pure virtual
Get the minimum received signal strength required to receive a packet without errors.
Returns
The minimum required signal strength, in dB.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
GetTransducer()
virtual Ptr<UanTransducer> ns3::UanPhy::GetTransducer (void) pure virtual
Get the attached transducer.
Returns
The transducer.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
GetTxPowerDb()
virtual double ns3::UanPhy::GetTxPowerDb (void) pure virtual
Get the current transmit power, in dB.
Returns
The transmit power.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
GetTypeId()
TypeId ns3::UanPhy::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 73 of file uan-phy.cc.
References m_phyRxBeginTrace, m_phyRxDropTrace, m_phyRxEndTrace, m_phyTxBeginTrace, m_phyTxDropTrace, m_phyTxEndTrace, ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
IsStateBusy()
virtual bool ns3::UanPhy::IsStateBusy (void) pure virtual
Returns
True if Phy is neither IDLE nor SLEEP.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
IsStateCcaBusy()
virtual bool ns3::UanPhy::IsStateCcaBusy (void) pure virtual
Returns
True if Phy is in CCABUSY state.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
IsStateIdle()
virtual bool ns3::UanPhy::IsStateIdle (void) pure virtual
Returns
True if Phy is in IDLE state.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
IsStateRx()
virtual bool ns3::UanPhy::IsStateRx (void) pure virtual
Returns
True if Phy is currently in receive mode.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
IsStateSleep()
virtual bool ns3::UanPhy::IsStateSleep (void) pure virtual
Returns
True if Phy is in SLEEP state.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
IsStateTx()
virtual bool ns3::UanPhy::IsStateTx (void) pure virtual
Returns
True if Phy is busy transmitting.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
NotifyIntChange()
virtual void ns3::UanPhy::NotifyIntChange (void) pure virtual
Called when there has been a change in the amount of interference this node is experiencing from other transmissions.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
NotifyRxBegin()
void ns3::UanPhy::NotifyRxBegin (Ptr< const Packet > packet)
Called when the Phy begins to receive a packet.
This fires a PhyRxBegin trace. Implemented for encapsulation purposes.
Parameters
packet The packet.
Definition at line 132 of file uan-phy.cc.
References m_phyRxBeginTrace.
Referenced by ns3::UanPhyGen::StartRxPacket().
NotifyRxDrop()
void ns3::UanPhy::NotifyRxDrop (Ptr< const Packet > packet)
Called when the Phy drops a packet.
This fires a PhyRxDrop trace. Implemented for encapsulation purposes.
Parameters
packet The packet.
Definition at line 144 of file uan-phy.cc.
References m_phyRxDropTrace.
Referenced by ns3::UanPhyGen::EnergyDepletionHandler(), ns3::UanPhyGen::RxEndEvent(), and ns3::UanPhyGen::StartRxPacket().
NotifyRxEnd()
void ns3::UanPhy::NotifyRxEnd (Ptr< const Packet > packet)
Called when a packet is received without error.
This fires a PhyRxEnd trace. Implemented for encapsulation purposes.
Parameters
packet The packet.
Definition at line 138 of file uan-phy.cc.
References m_phyRxEndTrace.
Referenced by ns3::UanPhyGen::RxEndEvent().
NotifyTransStartTx()
virtual void ns3::UanPhy::NotifyTransStartTx (Ptr< Packet > packet, double txPowerDb, UanTxMode txMode) pure virtual
Called when a transmission is beginning on the attached transducer.
Parameters
packet Packet that is beginning transmission.
txPowerDb Transmit power of packet.
txMode Transmission mode of packet.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
NotifyTxBegin()
void ns3::UanPhy::NotifyTxBegin (Ptr< const Packet > packet)
Called when the transducer begins transmitting a packet.
This fires a PhyTxBegin trace. Implemented for encapsulation purposes.
Parameters
packet The packet.
Definition at line 114 of file uan-phy.cc.
References m_phyTxBeginTrace.
NotifyTxDrop()
void ns3::UanPhy::NotifyTxDrop (Ptr< const Packet > packet)
Called when the transducer attempts to transmit a new packet while already transmitting a prior packet.
This fires a PhyTxDrop trace. Implemented for encapsulation purposes.
Parameters
packet The packet.
Definition at line 126 of file uan-phy.cc.
References m_phyTxDropTrace.
Referenced by ns3::UanPhyGen::EnergyDepletionHandler().
NotifyTxEnd()
void ns3::UanPhy::NotifyTxEnd (Ptr< const Packet > packet)
Called when the transducer finishes transmitting a packet.
This fires a PhyTxEnd trace. Implemented for encapsulation purposes.
Parameters
packet The packet.
Definition at line 120 of file uan-phy.cc.
References m_phyTxEndTrace.
Referenced by ns3::UanTransducerHd::Transmit().
RegisterListener()
virtual void ns3::UanPhy::RegisterListener (UanPhyListener * listener) pure virtual
Register a UanPhyListener to be notified of common UanPhy events.
Parameters
listener New listener to register.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
SendPacket()
virtual void ns3::UanPhy::SendPacket (Ptr< Packet > pkt, uint32_t modeNum) pure virtual
Send a packet using a specific transmission mode.
Parameters
pkt Packet to transmit.
modeNum Index of mode in SupportedModes list to use for transmission.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
SetCcaThresholdDb()
virtual void ns3::UanPhy::SetCcaThresholdDb (double thresh) pure virtual
Set the threshold for detecting channel busy.
Parameters
thresh Signal power threshold at receiver.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
SetChannel()
virtual void ns3::UanPhy::SetChannel (Ptr< UanChannel > channel) pure virtual
Attach to a channel.
Parameters
channel The channel to attach to.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
SetDevice()
virtual void ns3::UanPhy::SetDevice (Ptr< UanNetDevice > device) pure virtual
Set the device hosting this Phy.
Parameters
device The device.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
SetEnergyModelCallback()
virtual void ns3::UanPhy::SetEnergyModelCallback (DeviceEnergyModel::ChangeStateCallback callback) pure virtual
Set the DeviceEnergyModel callback for UanPhy device.
Parameters
callback The DeviceEnergyModel change state callback.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
SetMac()
virtual void ns3::UanPhy::SetMac (Ptr< UanMac > mac) pure virtual
Set the MAC forwarding messages to this Phy.
Parameters
mac The MAC.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
SetReceiveErrorCallback()
virtual void ns3::UanPhy::SetReceiveErrorCallback (RxErrCallback cb) pure virtual
Set the callback to be used when a packet is received with errors.
Parameters
cb The callback.
Implemented in ns3::UanPhyDual.
SetReceiveOkCallback()
virtual void ns3::UanPhy::SetReceiveOkCallback (RxOkCallback cb) pure virtual
Set the callback to be used when a packet is received without error.
Parameters
cb The callback.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
SetRxThresholdDb()
virtual void ns3::UanPhy::SetRxThresholdDb (double thresh) pure virtual
Set the minimum SINR threshold to receive a packet without errors.
Deprecated:
See UanPhyPer.
Parameters
thresh Threshold SINR for proper reception in dB re 1 uPa.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
SetSleepMode()
virtual void ns3::UanPhy::SetSleepMode (bool sleep) pure virtual
Set the Phy SLEEP mode.
Parameters
sleep SLEEP on or off.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
SetTransducer()
virtual void ns3::UanPhy::SetTransducer (Ptr< UanTransducer > trans) pure virtual
Attach a transducer to this Phy.
Parameters
trans The transducer.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
SetTxPowerDb()
virtual void ns3::UanPhy::SetTxPowerDb (double txpwr) pure virtual
Set the transmit power.
Parameters
txpwr Final output transmission power, in dB.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
StartRxPacket()
virtual void ns3::UanPhy::StartRxPacket (Ptr< Packet > pkt, double rxPowerDb, UanTxMode txMode, UanPdp pdp) pure virtual
Packet arriving from channel: i.e.
leading bit of packet has arrived.
Parameters
pkt Packet which is arriving.
rxPowerDb Signal power of incoming packet in dB re 1 uPa.
txMode Transmission mode defining modulation of incoming packet.
pdp Power delay profile of incoming packet.
Implemented in ns3::UanPhyGen, and ns3::UanPhyDual.
Member Data Documentation
m_phyRxBeginTrace
ns3::TracedCallback<Ptr<const Packet> > ns3::UanPhy::m_phyRxBeginTrace private
Trace source indicating a packet has begun being received from the channel medium by the device.
See also
class CallBackTraceSource
Definition at line 537 of file uan-phy.h.
Referenced by GetTypeId(), and NotifyRxBegin().
m_phyRxDropTrace
ns3::TracedCallback<Ptr<const Packet> > ns3::UanPhy::m_phyRxDropTrace private
Trace source indicating a packet has been dropped by the device during reception.
See also
class CallBackTraceSource
Definition at line 553 of file uan-phy.h.
Referenced by GetTypeId(), and NotifyRxDrop().
m_phyRxEndTrace
ns3::TracedCallback<Ptr<const Packet> > ns3::UanPhy::m_phyRxEndTrace private
Trace source indicating a packet has been completely received from the channel medium by the device.
See also
class CallBackTraceSource
Definition at line 545 of file uan-phy.h.
Referenced by GetTypeId(), and NotifyRxEnd().
m_phyTxBeginTrace
ns3::TracedCallback<Ptr<const Packet> > ns3::UanPhy::m_phyTxBeginTrace private
Trace source indicating a packet has begun transmitting over the channel medium.
See also
class CallBackTraceSource
Definition at line 513 of file uan-phy.h.
Referenced by GetTypeId(), and NotifyTxBegin().
m_phyTxDropTrace
ns3::TracedCallback<Ptr<const Packet> > ns3::UanPhy::m_phyTxDropTrace private
Trace source indicating a packet has been dropped by the device during transmission.
See also
class CallBackTraceSource
Definition at line 529 of file uan-phy.h.
Referenced by GetTypeId(), and NotifyTxDrop().
m_phyTxEndTrace
ns3::TracedCallback<Ptr<const Packet> > ns3::UanPhy::m_phyTxEndTrace private
Trace source indicating a packet has been completely transmitted over the channel.
See also
class CallBackTraceSource
Definition at line 521 of file uan-phy.h.
Referenced by GetTypeId(), and NotifyTxEnd().
The documentation for this class was generated from the following files:
src/uan/model/uan-phy.h
src/uan/model/uan-phy.cc