ns-3: ns3::HtOperation Class Reference
ns3::HtOperation Class Reference
Wifi Models
The HT Operation Information Element.
#include "ht-operation.h"
Public Member Functions
HtOperation ()
uint8_t DeserializeInformationField (Buffer::Iterator start, uint8_t length)
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
WifiInformationElementId ElementId () const
uint64_t GetBasicMcsSet1 (void) const
Return the first 64 bytes of the Basic MCS Set field in the HT Operation information element.
uint64_t GetBasicMcsSet2 (void) const
Return the last 64 bytes of the Basic MCS Set field in the HT Operation information element.
uint8_t GetDualBeacon (void) const
Return dual beacon.
uint8_t GetDualCtsProtection (void) const
Return dual CTS protection.
uint8_t GetHtProtection (void) const
Return the HT protection.
uint8_t GetInformationFieldSize () const
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
uint8_t GetInformationSubset1 (void) const
Return the Information Subset 1 field in the HT Operation information element.
uint16_t GetInformationSubset2 (void) const
Return the Information Subset 2 field in the HT Operation information element.
uint16_t GetInformationSubset3 (void) const
Return the Information Subset 3 field in the HT Operation information element.
uint8_t GetLSigTxopProtectionFullSupport (void) const
Return LSIG TXOP protection full support.
uint8_t GetNonGfHtStasPresent (void) const
Return the non GF HT STAs present.
uint8_t GetObssNonHtStasPresent (void) const
Return the OBSS non HT STAs present.
uint8_t GetPcoActive (void) const
Return PCO active.
uint8_t GetPhase (void) const
Return phase.
uint8_t GetPrimaryChannel (void) const
Return the Primary Channel field in the HT Operation information element.
uint8_t GetRifsMode (void) const
Return the RIFS mode.
uint16_t GetRxHighestSupportedDataRate (void) const
Return receive highest supported data rate.
uint8_t GetSecondaryChannelOffset (void) const
Return the secondary channel offset.
uint16_t GetSerializedSize () const
uint8_t GetStaChannelWidth (void) const
Return the STA channel width.
uint8_t GetStbcBeacon (void) const
Return STBC beacon.
uint8_t GetTxMaxNSpatialStreams (void) const
Return transmit maximum number spatial streams.
uint8_t GetTxMcsSetDefined (void) const
Return transmit MCS set defined.
uint8_t GetTxRxMcsSetUnequal (void) const
Return transmit / receive MCS set unequal.
uint8_t GetTxUnequalModulation (void) const
Return transmit unequal modulation.
bool IsSupportedMcs (uint8_t mcs) const
Return MCS is supported.
Buffer::Iterator Serialize (Buffer::Iterator start) const
void SerializeInformationField (Buffer::Iterator start) const
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
void SetBasicMcsSet (uint64_t ctrl1, uint64_t ctrl2)
Set the Basic MCS Set field in the HT Operation information element.
void SetDualBeacon (uint8_t dualBeacon)
Set the dual beacon.
void SetDualCtsProtection (uint8_t dualCtsProtection)
Set the dual CTS protection.
void SetHtProtection (uint8_t htProtection)
Set the HT protection.
void SetHtSupported (uint8_t htSupported)
Set the HT Supported.
void SetInformationSubset1 (uint8_t ctrl)
Set the Information Subset 1 field in the HT Operation information element.
void SetInformationSubset2 (uint16_t ctrl)
Set the Information Subset 2 field in the HT Operation information element.
void SetInformationSubset3 (uint16_t ctrl)
Set the Information Subset 3 field in the HT Operation information element.
void SetLSigTxopProtectionFullSupport (uint8_t lSigTxopProtectionFullSupport)
Set the LSIG TXOP protection full support.
void SetNonGfHtStasPresent (uint8_t nonGfHtStasPresent)
Set the non GF HT STAs present.
void SetObssNonHtStasPresent (uint8_t obssNonHtStasPresent)
Set the OBSS non HT STAs present.
void SetPcoActive (uint8_t pcoActive)
Set the PCO active.
void SetPhase (uint8_t pcoPhase)
Set the PCO phase.
void SetPrimaryChannel (uint8_t ctrl)
Set the Primary Channel field in the HT Operation information element.
void SetRifsMode (uint8_t rifsMode)
Set the RIFS mode.
void SetRxHighestSupportedDataRate (uint16_t maxSupportedRate)
Set the receive highest supported data rate.
void SetRxMcsBitmask (uint8_t index)
Set the receive MCS bitmask.
void SetSecondaryChannelOffset (uint8_t secondaryChannelOffset)
Set the secondary channel offset.
void SetStaChannelWidth (uint8_t staChannelWidth)
Set the STA channel width.
void SetStbcBeacon (uint8_t stbcBeacon)
Set the STBC beacon.
void SetTxMaxNSpatialStreams (uint8_t maxTxSpatialStreams)
Set the transmit maximum number spatial streams.
void SetTxMcsSetDefined (uint8_t txMcsSetDefined)
Set the transmit MCS set defined.
void SetTxRxMcsSetUnequal (uint8_t txRxMcsSetUnequal)
Set the transmit / receive MCS set unequal.
void SetTxUnequalModulation (uint8_t txUnequalModulation)
Set the transmit unequal modulation.
Public Member Functions inherited from ns3::WifiInformationElement
virtual ~WifiInformationElement ()
Buffer::Iterator Deserialize (Buffer::Iterator i)
Deserialize entire IE, which must be present.
Buffer::Iterator DeserializeIfPresent (Buffer::Iterator i)
Deserialize entire IE if it is present.
virtual WifiInformationElementId ElementIdExt () const
uint16_t GetSerializedSize () const
Get the size of the serialized IE including Element ID and length fields.
virtual bool operator== (WifiInformationElement const &a) const
Compare two IEs for equality by ID & Length, and then through memcmp of serialised version.
virtual void Print (std::ostream &os) const
Generate human-readable form of IE.
Buffer::Iterator Serialize (Buffer::Iterator i) const
Serialize entire IE including Element ID and length fields.
Public Member Functions inherited from ns3::SimpleRefCount< WifiInformationElement >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
uint8_t m_dualBeacon
dual beacon
uint8_t m_dualCtsProtection
dual CTS protection
uint8_t m_htProtection
HT protection.
uint8_t m_htSupported
This is used to decide whether this element should be added to the frame or not.
uint8_t m_lSigTxopProtectionFullSupport
L-SIG TXOP protection full support.
uint8_t m_nonGfHtStasPresent
non GF HT STAs present
uint8_t m_obssNonHtStasPresent
OBSS NON HT STAs present.
uint8_t m_pcoActive
PCO active.
uint8_t m_pcoPhase
PCO phase.
uint8_t m_primaryChannel
primary channel
uint8_t m_reservedInformationSubset1
reserved information subset 1
uint8_t m_reservedInformationSubset2_1
reserved information subset 2-1
uint8_t m_reservedInformationSubset2_2
reserved information subset 2-2
uint8_t m_reservedInformationSubset3_1
reserved information subset 3-1
uint8_t m_reservedInformationSubset3_2
reserved information subset 3-2
uint8_t m_reservedMcsSet1
reserved MCS set 1
uint8_t m_reservedMcsSet2
reserved MCS set2
uint32_t m_reservedMcsSet3
reserved MCS set 3
uint8_t m_rifsMode
RIFS mode.
uint16_t m_rxHighestSupportedDataRate
receive highest supported data rate
uint8_t m_rxMcsBitmask [MAX_SUPPORTED_MCS]
receive MCS bitmask
uint8_t m_secondaryChannelOffset
secondary channel offset
uint8_t m_staChannelWidth
STA channel width.
uint8_t m_stbcBeacon
STBC beacon.
uint8_t m_txMaxNSpatialStreams
transmit maximum number spatial streams
uint8_t m_txMcsSetDefined
transmit MCS set defined
uint8_t m_txRxMcsSetUnequal
transmit / receive MCS set unequal
uint8_t m_txUnequalModulation
transmit unequal modulation
Detailed Description
The HT Operation Information Element.
This class knows how to serialise and deserialise the HT Operation Information Element
Definition at line 50 of file ht-operation.h.
Constructor & Destructor Documentation
HtOperation()
ns3::HtOperation::HtOperation ()
Definition at line 25 of file ht-operation.cc.
References m_rxMcsBitmask, and MAX_SUPPORTED_MCS.
Member Function Documentation
DeserializeInformationField()
uint8_t ns3::HtOperation::DeserializeInformationField (Buffer::Iterator start, uint8_t length) virtual
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
length
Returns
the number of bytes read
Implements ns3::WifiInformationElement.
Definition at line 474 of file ht-operation.cc.
References ns3::Buffer::Iterator::ReadLsbtohU64(), ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU8(), SetBasicMcsSet(), SetInformationSubset1(), SetInformationSubset2(), SetInformationSubset3(), SetPrimaryChannel(), and visualizer.core::start().
ElementId()
WifiInformationElementId ns3::HtOperation::ElementId () const virtual
Returns
Own unique Element ID
Implements ns3::WifiInformationElement.
Definition at line 61 of file ht-operation.cc.
References IE_HT_OPERATION.
GetBasicMcsSet1()
uint64_t ns3::HtOperation::GetBasicMcsSet1 (void) const
Return the first 64 bytes of the Basic MCS Set field in the HT Operation information element.
Returns
the first 64 bytes of the Basic MCS Set field in the HT Operation information element
Definition at line 427 of file ht-operation.cc.
References m_rxMcsBitmask.
Referenced by SerializeInformationField().
GetBasicMcsSet2()
uint64_t ns3::HtOperation::GetBasicMcsSet2 (void) const
Return the last 64 bytes of the Basic MCS Set field in the HT Operation information element.
Returns
the last 64 bytes of the Basic MCS Set field in the HT Operation information element
Definition at line 439 of file ht-operation.cc.
References m_reservedMcsSet1, m_reservedMcsSet2, m_reservedMcsSet3, m_rxHighestSupportedDataRate, m_rxMcsBitmask, m_txMaxNSpatialStreams, m_txMcsSetDefined, m_txRxMcsSetUnequal, and m_txUnequalModulation.
Referenced by SerializeInformationField().
GetDualBeacon()
uint8_t ns3::HtOperation::GetDualBeacon (void) const
Return dual beacon.
Returns
the dual beacon
Definition at line 237 of file ht-operation.cc.
References m_dualBeacon.
Referenced by ns3::operator<<().
GetDualCtsProtection()
uint8_t ns3::HtOperation::GetDualCtsProtection (void) const
Return dual CTS protection.
Returns
the dual CTS protection
Definition at line 243 of file ht-operation.cc.
References m_dualCtsProtection.
Referenced by ns3::operator<<().
GetHtProtection()
uint8_t ns3::HtOperation::GetHtProtection (void) const
Return the HT protection.
Returns
the HT protection
Definition at line 219 of file ht-operation.cc.
References m_htProtection.
Referenced by ns3::operator<<().
GetInformationFieldSize()
uint8_t ns3::HtOperation::GetInformationFieldSize () const virtual
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
This is the value that will appear in the second octet of the entire IE - the length field)
Returns
the length of serialized information
Implements ns3::WifiInformationElement.
Definition at line 73 of file ht-operation.cc.
References m_htSupported, and NS_ASSERT.
GetInformationSubset1()
uint8_t ns3::HtOperation::GetInformationSubset1 (void) const
Return the Information Subset 1 field in the HT Operation information element.
Returns
the Information Subset 1 field in the HT Operation information element
Definition at line 333 of file ht-operation.cc.
References m_reservedInformationSubset1, m_rifsMode, m_secondaryChannelOffset, and m_staChannelWidth.
Referenced by SerializeInformationField().
GetInformationSubset2()
uint16_t ns3::HtOperation::GetInformationSubset2 (void) const
Return the Information Subset 2 field in the HT Operation information element.
Returns
the Information Subset 2 field in the HT Operation information element
Definition at line 353 of file ht-operation.cc.
References m_htProtection, m_nonGfHtStasPresent, m_obssNonHtStasPresent, m_reservedInformationSubset2_1, and m_reservedInformationSubset2_2.
Referenced by SerializeInformationField().
GetInformationSubset3()
uint16_t ns3::HtOperation::GetInformationSubset3 (void) const
Return the Information Subset 3 field in the HT Operation information element.
Returns
the Information Subset 3 field in the HT Operation information element
Definition at line 375 of file ht-operation.cc.
References m_dualBeacon, m_dualCtsProtection, m_lSigTxopProtectionFullSupport, m_pcoActive, m_pcoPhase, m_reservedInformationSubset3_1, m_reservedInformationSubset3_2, and m_stbcBeacon.
Referenced by SerializeInformationField().
GetLSigTxopProtectionFullSupport()
uint8_t ns3::HtOperation::GetLSigTxopProtectionFullSupport (void) const
Return LSIG TXOP protection full support.
Returns
the LSIG TXOP protection full support
Definition at line 255 of file ht-operation.cc.
References m_lSigTxopProtectionFullSupport.
Referenced by ns3::operator<<().
GetNonGfHtStasPresent()
uint8_t ns3::HtOperation::GetNonGfHtStasPresent (void) const
Return the non GF HT STAs present.
Returns
the non GF HT STAs present
Definition at line 225 of file ht-operation.cc.
References m_nonGfHtStasPresent.
Referenced by ns3::operator<<(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetObssNonHtStasPresent()
uint8_t ns3::HtOperation::GetObssNonHtStasPresent (void) const
Return the OBSS non HT STAs present.
Returns
the OBSS non HT STAs present
Definition at line 231 of file ht-operation.cc.
References m_obssNonHtStasPresent.
Referenced by ns3::operator<<().
GetPcoActive()
uint8_t ns3::HtOperation::GetPcoActive (void) const
Return PCO active.
Returns
the PCO active
Definition at line 261 of file ht-operation.cc.
References m_pcoActive.
Referenced by ns3::operator<<().
GetPhase()
uint8_t ns3::HtOperation::GetPhase (void) const
Return phase.
Returns
the phase
Definition at line 267 of file ht-operation.cc.
References m_pcoPhase.
Referenced by ns3::operator<<().
GetPrimaryChannel()
uint8_t ns3::HtOperation::GetPrimaryChannel (void) const
Return the Primary Channel field in the HT Operation information element.
Returns
the Primary Channel field in the HT Operation information element
Definition at line 195 of file ht-operation.cc.
References m_primaryChannel.
Referenced by ns3::operator<<(), and SerializeInformationField().
GetRifsMode()
uint8_t ns3::HtOperation::GetRifsMode (void) const
Return the RIFS mode.
Returns
the RIFS mode
Definition at line 213 of file ht-operation.cc.
References m_rifsMode.
Referenced by ns3::operator<<(), ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetRxHighestSupportedDataRate()
uint16_t ns3::HtOperation::GetRxHighestSupportedDataRate (void) const
Return receive highest supported data rate.
Returns
receive highest supported data rate
Definition at line 283 of file ht-operation.cc.
References m_rxHighestSupportedDataRate.
Referenced by ns3::operator<<().
GetSecondaryChannelOffset()
uint8_t ns3::HtOperation::GetSecondaryChannelOffset (void) const
Return the secondary channel offset.
Returns
the secondary channel offset
Definition at line 201 of file ht-operation.cc.
References m_secondaryChannelOffset.
Referenced by ns3::operator<<().
GetSerializedSize()
uint16_t ns3::HtOperation::GetSerializedSize () const
Definition at line 323 of file ht-operation.cc.
References ns3::WifiInformationElement::GetSerializedSize(), and m_htSupported.
Referenced by ns3::MgtAssocResponseHeader::GetSerializedSize(), and ns3::MgtProbeResponseHeader::GetSerializedSize().
GetStaChannelWidth()
uint8_t ns3::HtOperation::GetStaChannelWidth (void) const
Return the STA channel width.
Returns
the STA channel width
Definition at line 207 of file ht-operation.cc.
References m_staChannelWidth.
Referenced by ns3::operator<<(), and Bug2831TestCase::RxCallback().
GetStbcBeacon()
uint8_t ns3::HtOperation::GetStbcBeacon (void) const
Return STBC beacon.
Returns
the STBC beacon
Definition at line 249 of file ht-operation.cc.
References m_stbcBeacon.
Referenced by ns3::operator<<().
GetTxMaxNSpatialStreams()
uint8_t ns3::HtOperation::GetTxMaxNSpatialStreams (void) const
Return transmit maximum number spatial streams.
Returns
transmit maximum number spatial streams
Definition at line 301 of file ht-operation.cc.
References m_txMaxNSpatialStreams.
Referenced by ns3::operator<<().
GetTxMcsSetDefined()
uint8_t ns3::HtOperation::GetTxMcsSetDefined (void) const
Return transmit MCS set defined.
Returns
the transmit MCS set defined
Definition at line 289 of file ht-operation.cc.
References m_txMcsSetDefined.
Referenced by ns3::operator<<().
GetTxRxMcsSetUnequal()
uint8_t ns3::HtOperation::GetTxRxMcsSetUnequal (void) const
Return transmit / receive MCS set unequal.
Returns
transmit / receive MCS set unequal
Definition at line 295 of file ht-operation.cc.
References m_txRxMcsSetUnequal.
Referenced by ns3::operator<<().
GetTxUnequalModulation()
uint8_t ns3::HtOperation::GetTxUnequalModulation (void) const
Return transmit unequal modulation.
Returns
transmit unequal modulation
Definition at line 307 of file ht-operation.cc.
References m_txUnequalModulation.
Referenced by ns3::operator<<().
IsSupportedMcs()
bool ns3::HtOperation::IsSupportedMcs (uint8_t mcs) const
Return MCS is supported.
Parameters
mcs MCS \
Returns
the MCS is supported
Definition at line 273 of file ht-operation.cc.
References m_rxMcsBitmask.
Referenced by ns3::operator<<().
Serialize()
Buffer::Iterator ns3::HtOperation::Serialize (Buffer::Iterator start) const
Definition at line 313 of file ht-operation.cc.
References m_htSupported, and ns3::WifiInformationElement::Serialize().
Referenced by ns3::MgtAssocResponseHeader::Serialize(), and ns3::MgtProbeResponseHeader::Serialize().
SerializeInformationField()
void ns3::HtOperation::SerializeInformationField (Buffer::Iterator start) const virtual
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
Implements ns3::WifiInformationElement.
Definition at line 459 of file ht-operation.cc.
References GetBasicMcsSet1(), GetBasicMcsSet2(), GetInformationSubset1(), GetInformationSubset2(), GetInformationSubset3(), GetPrimaryChannel(), m_htSupported, and visualizer.core::start().
SetBasicMcsSet()
void ns3::HtOperation::SetBasicMcsSet (uint64_t ctrl1, uint64_t ctrl2)
Set the Basic MCS Set field in the HT Operation information element.
Parameters
ctrl1 the first 64 bytes of the Basic MCS Set field in the HT Operation information element
ctrl2 the last 64 bytes of the Basic MCS Set field in the HT Operation information element
Definition at line 403 of file ht-operation.cc.
References m_reservedMcsSet1, m_reservedMcsSet2, m_reservedMcsSet3, m_rxHighestSupportedDataRate, m_rxMcsBitmask, m_txMaxNSpatialStreams, m_txMcsSetDefined, m_txRxMcsSetUnequal, and m_txUnequalModulation.
Referenced by DeserializeInformationField().
SetDualBeacon()
void ns3::HtOperation::SetDualBeacon (uint8_t dualBeacon)
Set the dual beacon.
Parameters
dualBeacon the dual beacon
Definition at line 123 of file ht-operation.cc.
References m_dualBeacon.
Referenced by ns3::ApWifiMac::GetHtOperation().
SetDualCtsProtection()
void ns3::HtOperation::SetDualCtsProtection (uint8_t dualCtsProtection)
Set the dual CTS protection.
Parameters
dualCtsProtection the dual CTS protection
Definition at line 129 of file ht-operation.cc.
References m_dualCtsProtection.
Referenced by ns3::ApWifiMac::GetHtOperation().
SetHtProtection()
void ns3::HtOperation::SetHtProtection (uint8_t htProtection)
Set the HT protection.
Parameters
htProtection the HT protection
Definition at line 105 of file ht-operation.cc.
References m_htProtection.
Referenced by ns3::ApWifiMac::GetHtOperation().
SetHtSupported()
void ns3::HtOperation::SetHtSupported (uint8_t htSupported)
Set the HT Supported.
Parameters
htSupported the HT Supported flag
Definition at line 67 of file ht-operation.cc.
References m_htSupported.
Referenced by ns3::ApWifiMac::GetHtOperation().
SetInformationSubset1()
void ns3::HtOperation::SetInformationSubset1 (uint8_t ctrl)
Set the Information Subset 1 field in the HT Operation information element.
Parameters
ctrl the Information Subset 1 field in the HT Operation information element
Definition at line 344 of file ht-operation.cc.
References m_reservedInformationSubset1, m_rifsMode, m_secondaryChannelOffset, and m_staChannelWidth.
Referenced by DeserializeInformationField().
SetInformationSubset2()
void ns3::HtOperation::SetInformationSubset2 (uint16_t ctrl)
Set the Information Subset 2 field in the HT Operation information element.
Parameters
ctrl the Information Subset 2 field in the HT Operation information element
Definition at line 365 of file ht-operation.cc.
References m_htProtection, m_nonGfHtStasPresent, m_obssNonHtStasPresent, m_reservedInformationSubset2_1, and m_reservedInformationSubset2_2.
Referenced by DeserializeInformationField().
SetInformationSubset3()
void ns3::HtOperation::SetInformationSubset3 (uint16_t ctrl)
Set the Information Subset 3 field in the HT Operation information element.
Parameters
ctrl the Information Subset 3 field in the HT Operation information element
Definition at line 390 of file ht-operation.cc.
References m_dualBeacon, m_dualCtsProtection, m_lSigTxopProtectionFullSupport, m_pcoActive, m_pcoPhase, m_reservedInformationSubset3_1, m_reservedInformationSubset3_2, and m_stbcBeacon.
Referenced by DeserializeInformationField().
SetLSigTxopProtectionFullSupport()
void ns3::HtOperation::SetLSigTxopProtectionFullSupport (uint8_t lSigTxopProtectionFullSupport)
Set the LSIG TXOP protection full support.
Parameters
lSigTxopProtectionFullSupport the LSIG TXOP protection full support
Definition at line 141 of file ht-operation.cc.
References m_lSigTxopProtectionFullSupport.
Referenced by ns3::ApWifiMac::GetHtOperation().
SetNonGfHtStasPresent()
void ns3::HtOperation::SetNonGfHtStasPresent (uint8_t nonGfHtStasPresent)
Set the non GF HT STAs present.
Parameters
nonGfHtStasPresent the non GF HT STAs present
Definition at line 111 of file ht-operation.cc.
References m_nonGfHtStasPresent.
Referenced by ns3::ApWifiMac::GetHtOperation().
SetObssNonHtStasPresent()
void ns3::HtOperation::SetObssNonHtStasPresent (uint8_t obssNonHtStasPresent)
Set the OBSS non HT STAs present.
Parameters
obssNonHtStasPresent the OBSS non HTA STAs present
Definition at line 117 of file ht-operation.cc.
References m_obssNonHtStasPresent.
Referenced by ns3::ApWifiMac::GetHtOperation().
SetPcoActive()
void ns3::HtOperation::SetPcoActive (uint8_t pcoActive)
Set the PCO active.
Parameters
pcoActive the PCO active
Definition at line 147 of file ht-operation.cc.
References m_pcoActive.
Referenced by ns3::ApWifiMac::GetHtOperation().
SetPhase()
void ns3::HtOperation::SetPhase (uint8_t pcoPhase)
Set the PCO phase.
Parameters
pcoPhase the PCO phase
Definition at line 153 of file ht-operation.cc.
References m_pcoPhase.
Referenced by ns3::ApWifiMac::GetHtOperation().
SetPrimaryChannel()
void ns3::HtOperation::SetPrimaryChannel (uint8_t ctrl)
Set the Primary Channel field in the HT Operation information element.
Parameters
ctrl the Primary Channel field in the HT Operation information element
Definition at line 81 of file ht-operation.cc.
References m_primaryChannel.
Referenced by DeserializeInformationField(), and ns3::ApWifiMac::GetHtOperation().
SetRifsMode()
void ns3::HtOperation::SetRifsMode (uint8_t rifsMode)
Set the RIFS mode.
Parameters
rifsMode the RIFS mode
Definition at line 99 of file ht-operation.cc.
References m_rifsMode.
Referenced by ns3::ApWifiMac::GetHtOperation().
SetRxHighestSupportedDataRate()
void ns3::HtOperation::SetRxHighestSupportedDataRate (uint16_t maxSupportedRate)
Set the receive highest supported data rate.
Parameters
maxSupportedRate the maximum supported data rate
Definition at line 165 of file ht-operation.cc.
References m_rxHighestSupportedDataRate.
Referenced by ns3::ApWifiMac::GetHtOperation().
SetRxMcsBitmask()
void ns3::HtOperation::SetRxMcsBitmask (uint8_t index)
Set the receive MCS bitmask.
Parameters
index the MCS bitmask
Definition at line 159 of file ht-operation.cc.
References m_rxMcsBitmask.
Referenced by ns3::ApWifiMac::GetHtOperation().
SetSecondaryChannelOffset()
void ns3::HtOperation::SetSecondaryChannelOffset (uint8_t secondaryChannelOffset)
Set the secondary channel offset.
Parameters
secondaryChannelOffset the secondary channel offset
Definition at line 87 of file ht-operation.cc.
References m_secondaryChannelOffset.
Referenced by ns3::ApWifiMac::GetHtOperation().
SetStaChannelWidth()
void ns3::HtOperation::SetStaChannelWidth (uint8_t staChannelWidth)
Set the STA channel width.
Parameters
staChannelWidth the STA channel width
Definition at line 93 of file ht-operation.cc.
References m_staChannelWidth.
Referenced by ns3::ApWifiMac::GetHtOperation().
SetStbcBeacon()
void ns3::HtOperation::SetStbcBeacon (uint8_t stbcBeacon)
Set the STBC beacon.
Parameters
stbcBeacon the STBC beacon
Definition at line 135 of file ht-operation.cc.
References m_stbcBeacon.
Referenced by ns3::ApWifiMac::GetHtOperation().
SetTxMaxNSpatialStreams()
void ns3::HtOperation::SetTxMaxNSpatialStreams (uint8_t maxTxSpatialStreams)
Set the transmit maximum number spatial streams.
Parameters
maxTxSpatialStreams the maximum transmit spatial streams
Definition at line 183 of file ht-operation.cc.
References m_txMaxNSpatialStreams.
Referenced by ns3::ApWifiMac::GetHtOperation().
SetTxMcsSetDefined()
void ns3::HtOperation::SetTxMcsSetDefined (uint8_t txMcsSetDefined)
Set the transmit MCS set defined.
Parameters
txMcsSetDefined the transmit MCS set defined
Definition at line 171 of file ht-operation.cc.
References m_txMcsSetDefined.
Referenced by ns3::ApWifiMac::GetHtOperation().
SetTxRxMcsSetUnequal()
void ns3::HtOperation::SetTxRxMcsSetUnequal (uint8_t txRxMcsSetUnequal)
Set the transmit / receive MCS set unequal.
Parameters
txRxMcsSetUnequal the transmit / receive MCS set unequal
Definition at line 177 of file ht-operation.cc.
References m_txRxMcsSetUnequal.
Referenced by ns3::ApWifiMac::GetHtOperation().
SetTxUnequalModulation()
void ns3::HtOperation::SetTxUnequalModulation (uint8_t txUnequalModulation)
Set the transmit unequal modulation.
Parameters
txUnequalModulation the transmit unequal modulation
Definition at line 189 of file ht-operation.cc.
References m_txUnequalModulation.
Referenced by ns3::ApWifiMac::GetHtOperation().
Member Data Documentation
m_dualBeacon
uint8_t ns3::HtOperation::m_dualBeacon private
dual beacon
Definition at line 389 of file ht-operation.h.
Referenced by GetDualBeacon(), GetInformationSubset3(), SetDualBeacon(), and SetInformationSubset3().
m_dualCtsProtection
uint8_t ns3::HtOperation::m_dualCtsProtection private
dual CTS protection
Definition at line 390 of file ht-operation.h.
Referenced by GetDualCtsProtection(), GetInformationSubset3(), SetDualCtsProtection(), and SetInformationSubset3().
m_htProtection
uint8_t ns3::HtOperation::m_htProtection private
HT protection.
Definition at line 381 of file ht-operation.h.
Referenced by GetHtProtection(), GetInformationSubset2(), SetHtProtection(), and SetInformationSubset2().
m_htSupported
uint8_t ns3::HtOperation::m_htSupported private
This is used to decide whether this element should be added to the frame or not.
Definition at line 409 of file ht-operation.h.
Referenced by GetInformationFieldSize(), GetSerializedSize(), Serialize(), SerializeInformationField(), and SetHtSupported().
m_lSigTxopProtectionFullSupport
uint8_t ns3::HtOperation::m_lSigTxopProtectionFullSupport private
L-SIG TXOP protection full support.
Definition at line 392 of file ht-operation.h.
Referenced by GetInformationSubset3(), GetLSigTxopProtectionFullSupport(), SetInformationSubset3(), and SetLSigTxopProtectionFullSupport().
m_nonGfHtStasPresent
uint8_t ns3::HtOperation::m_nonGfHtStasPresent private
non GF HT STAs present
Definition at line 382 of file ht-operation.h.
Referenced by GetInformationSubset2(), GetNonGfHtStasPresent(), SetInformationSubset2(), and SetNonGfHtStasPresent().
m_obssNonHtStasPresent
uint8_t ns3::HtOperation::m_obssNonHtStasPresent private
OBSS NON HT STAs present.
Definition at line 384 of file ht-operation.h.
Referenced by GetInformationSubset2(), GetObssNonHtStasPresent(), SetInformationSubset2(), and SetObssNonHtStasPresent().
m_pcoActive
uint8_t ns3::HtOperation::m_pcoActive private
PCO active.
Definition at line 393 of file ht-operation.h.
Referenced by GetInformationSubset3(), GetPcoActive(), SetInformationSubset3(), and SetPcoActive().
m_pcoPhase
uint8_t ns3::HtOperation::m_pcoPhase private
PCO phase.
Definition at line 394 of file ht-operation.h.
Referenced by GetInformationSubset3(), GetPhase(), SetInformationSubset3(), and SetPhase().
m_primaryChannel
uint8_t ns3::HtOperation::m_primaryChannel private
primary channel
Definition at line 372 of file ht-operation.h.
Referenced by GetPrimaryChannel(), and SetPrimaryChannel().
m_reservedInformationSubset1
uint8_t ns3::HtOperation::m_reservedInformationSubset1 private
reserved information subset 1
Definition at line 378 of file ht-operation.h.
Referenced by GetInformationSubset1(), and SetInformationSubset1().
m_reservedInformationSubset2_1
uint8_t ns3::HtOperation::m_reservedInformationSubset2_1 private
reserved information subset 2-1
Definition at line 383 of file ht-operation.h.
Referenced by GetInformationSubset2(), and SetInformationSubset2().
m_reservedInformationSubset2_2
uint8_t ns3::HtOperation::m_reservedInformationSubset2_2 private
reserved information subset 2-2
Definition at line 385 of file ht-operation.h.
Referenced by GetInformationSubset2(), and SetInformationSubset2().
m_reservedInformationSubset3_1
uint8_t ns3::HtOperation::m_reservedInformationSubset3_1 private
reserved information subset 3-1
Definition at line 388 of file ht-operation.h.
Referenced by GetInformationSubset3(), and SetInformationSubset3().
m_reservedInformationSubset3_2
uint8_t ns3::HtOperation::m_reservedInformationSubset3_2 private
reserved information subset 3-2
Definition at line 395 of file ht-operation.h.
Referenced by GetInformationSubset3(), and SetInformationSubset3().
m_reservedMcsSet1
uint8_t ns3::HtOperation::m_reservedMcsSet1 private
reserved MCS set 1
Definition at line 398 of file ht-operation.h.
Referenced by GetBasicMcsSet2(), and SetBasicMcsSet().
m_reservedMcsSet2
uint8_t ns3::HtOperation::m_reservedMcsSet2 private
reserved MCS set2
Definition at line 400 of file ht-operation.h.
Referenced by GetBasicMcsSet2(), and SetBasicMcsSet().
m_reservedMcsSet3
uint32_t ns3::HtOperation::m_reservedMcsSet3 private
reserved MCS set 3
Definition at line 405 of file ht-operation.h.
Referenced by GetBasicMcsSet2(), and SetBasicMcsSet().
m_rifsMode
uint8_t ns3::HtOperation::m_rifsMode private
RIFS mode.
Definition at line 377 of file ht-operation.h.
Referenced by GetInformationSubset1(), GetRifsMode(), SetInformationSubset1(), and SetRifsMode().
m_rxHighestSupportedDataRate
uint16_t ns3::HtOperation::m_rxHighestSupportedDataRate private
receive highest supported data rate
Definition at line 399 of file ht-operation.h.
Referenced by GetBasicMcsSet2(), GetRxHighestSupportedDataRate(), SetBasicMcsSet(), and SetRxHighestSupportedDataRate().
m_rxMcsBitmask
uint8_t ns3::HtOperation::m_rxMcsBitmask[MAX_SUPPORTED_MCS] private
receive MCS bitmask
Definition at line 406 of file ht-operation.h.
Referenced by HtOperation(), GetBasicMcsSet1(), GetBasicMcsSet2(), IsSupportedMcs(), SetBasicMcsSet(), and SetRxMcsBitmask().
m_secondaryChannelOffset
uint8_t ns3::HtOperation::m_secondaryChannelOffset private
secondary channel offset
Definition at line 375 of file ht-operation.h.
Referenced by GetInformationSubset1(), GetSecondaryChannelOffset(), SetInformationSubset1(), and SetSecondaryChannelOffset().
m_staChannelWidth
uint8_t ns3::HtOperation::m_staChannelWidth private
STA channel width.
Definition at line 376 of file ht-operation.h.
Referenced by GetInformationSubset1(), GetStaChannelWidth(), SetInformationSubset1(), and SetStaChannelWidth().
m_stbcBeacon
uint8_t ns3::HtOperation::m_stbcBeacon private
STBC beacon.
Definition at line 391 of file ht-operation.h.
Referenced by GetInformationSubset3(), GetStbcBeacon(), SetInformationSubset3(), and SetStbcBeacon().
m_txMaxNSpatialStreams
uint8_t ns3::HtOperation::m_txMaxNSpatialStreams private
transmit maximum number spatial streams
Definition at line 403 of file ht-operation.h.
Referenced by GetBasicMcsSet2(), GetTxMaxNSpatialStreams(), SetBasicMcsSet(), and SetTxMaxNSpatialStreams().
m_txMcsSetDefined
uint8_t ns3::HtOperation::m_txMcsSetDefined private
transmit MCS set defined
Definition at line 401 of file ht-operation.h.
Referenced by GetBasicMcsSet2(), GetTxMcsSetDefined(), SetBasicMcsSet(), and SetTxMcsSetDefined().
m_txRxMcsSetUnequal
uint8_t ns3::HtOperation::m_txRxMcsSetUnequal private
transmit / receive MCS set unequal
Definition at line 402 of file ht-operation.h.
Referenced by GetBasicMcsSet2(), GetTxRxMcsSetUnequal(), SetBasicMcsSet(), and SetTxRxMcsSetUnequal().
m_txUnequalModulation
uint8_t ns3::HtOperation::m_txUnequalModulation private
transmit unequal modulation
Definition at line 404 of file ht-operation.h.
Referenced by GetBasicMcsSet2(), GetTxUnequalModulation(), SetBasicMcsSet(), and SetTxUnequalModulation().
The documentation for this class was generated from the following files:
src/wifi/model/ht-operation.h
src/wifi/model/ht-operation.cc