ns-3: Ns3WimaxFragmentationTestCase Class Reference
Ns3WimaxFragmentationTestCase Class Reference
WiMAX Models » wimax module tests | Test suites
Test the wimax packet fragmentation.
Public Member Functions
Ns3WimaxFragmentationTestCase ()
virtual ~Ns3WimaxFragmentationTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test the wimax packet fragmentation.
Definition at line 39 of file wimax-fragmentation-test.cc.
Constructor & Destructor Documentation
Ns3WimaxFragmentationTestCase()
Ns3WimaxFragmentationTestCase::Ns3WimaxFragmentationTestCase ()
Definition at line 50 of file wimax-fragmentation-test.cc.
~Ns3WimaxFragmentationTestCase()
Ns3WimaxFragmentationTestCase::~Ns3WimaxFragmentationTestCase () virtual
Definition at line 55 of file wimax-fragmentation-test.cc.
Member Function Documentation
DoRun()
void Ns3WimaxFragmentationTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 60 of file wimax-fragmentation-test.cc.
References ns3::Packet::AddAtEnd(), ns3::WimaxConnection::ClearFragmentsQueue(), ns3::WimaxConnection::Dequeue(), ns3::WimaxConnection::Enqueue(), ns3::WimaxConnection::FragmentEnqueue(), ns3::WimaxConnection::GetCid(), ns3::FragmentationSubheader::GetFc(), ns3::WimaxConnection::GetFragmentsQueue(), ns3::WimaxConnection::GetQueue(), ns3::GenericMacHeader::GetSerializedSize(), ns3::Packet::GetSize(), ns3::GenericMacHeader::GetType(), list, NS_TEST_EXPECT_MSG_EQ, ns3::Packet::RemoveHeader(), ns3::GenericMacHeader::SetCid(), and ns3::GenericMacHeader::SetLen().
The documentation for this class was generated from the following file:
src/wimax/test/wimax-fragmentation-test.cc