ns-3: ns3::MgtAssocResponseHeader Class Reference
ns3::MgtAssocResponseHeader Class Reference
Wifi Models
#include "mgt-headers.h"
Public Member Functions
MgtAssocResponseHeader ()
~MgtAssocResponseHeader ()
uint32_t Deserialize (Buffer::Iterator start)
uint16_t GetAssociationId (void) const
Return the association ID.
CapabilityInformation GetCapabilities (void) const
Return the Capability information.
EdcaParameterSet GetEdcaParameterSet (void) const
Return the EDCA Parameter Set.
ErpInformation GetErpInformation (void) const
Return the ERP information.
ExtendedCapabilities GetExtendedCapabilities (void) const
Return the extended capabilities.
HeCapabilities GetHeCapabilities (void) const
Return the HE capabilities.
HeOperation GetHeOperation (void) const
Return the HE operation.
HtCapabilities GetHtCapabilities (void) const
Return the HT capabilities.
HtOperation GetHtOperation (void) const
Return the HT operation.
TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint32_t GetSerializedSize (void) const
StatusCode GetStatusCode (void)
Return the status code.
SupportedRates GetSupportedRates (void)
Return the supported rates.
VhtCapabilities GetVhtCapabilities (void) const
Return the VHT capabilities.
VhtOperation GetVhtOperation (void) const
Return the VHT operation.
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetAssociationId (uint16_t aid)
Set the association ID.
void SetCapabilities (CapabilityInformation capabilities)
Set the Capability information.
void SetEdcaParameterSet (EdcaParameterSet edcaParameterSet)
Set the EDCA Parameter Set.
void SetErpInformation (ErpInformation erpInformation)
Set the ERP information.
void SetExtendedCapabilities (ExtendedCapabilities extendedCapabilities)
Set the extended capabilities.
void SetHeCapabilities (HeCapabilities heCapabilities)
Set the HE capabilities.
void SetHeOperation (HeOperation heOperation)
Set the HE operation.
void SetHtCapabilities (HtCapabilities htCapabilities)
Set the HT capabilities.
void SetHtOperation (HtOperation htOperation)
Set the HT operation.
void SetStatusCode (StatusCode code)
Set the status code.
void SetSupportedRates (SupportedRates rates)
Set the supported rates.
void SetVhtCapabilities (VhtCapabilities vhtCapabilities)
Set the VHT capabilities.
void SetVhtOperation (VhtOperation vhtOperation)
Set the VHT operation.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint16_t m_aid
AID.
CapabilityInformation m_capability
Capability information.
StatusCode m_code
Status code.
EdcaParameterSet m_edcaParameterSet
EDCA Parameter Set.
ErpInformation m_erpInformation
ERP information.
ExtendedCapabilities m_extendedCapability
extended capabilities
HeCapabilities m_heCapability
HE capabilities.
HeOperation m_heOperation
HE operation.
HtCapabilities m_htCapability
HT capabilities.
HtOperation m_htOperation
HT operation.
SupportedRates m_rates
List of supported rates.
VhtCapabilities m_vhtCapability
VHT capabilities.
VhtOperation m_vhtOperation
VHT operation.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implement the header for management frames of type association and reassociation response.
Definition at line 318 of file mgt-headers.h.
Constructor & Destructor Documentation
MgtAssocResponseHeader()
ns3::MgtAssocResponseHeader::MgtAssocResponseHeader ()
Definition at line 904 of file mgt-headers.cc.
~MgtAssocResponseHeader()
ns3::MgtAssocResponseHeader::~MgtAssocResponseHeader ()
Definition at line 909 of file mgt-headers.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::MgtAssocResponseHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 1144 of file mgt-headers.cc.
References ns3::WifiInformationElement::Deserialize(), ns3::CapabilityInformation::Deserialize(), ns3::StatusCode::Deserialize(), ns3::WifiInformationElement::DeserializeIfPresent(), ns3::SupportedRates::extended, ns3::Buffer::Iterator::GetDistanceFrom(), m_aid, m_capability, m_code, m_edcaParameterSet, m_erpInformation, m_extendedCapability, m_heCapability, m_heOperation, m_htCapability, m_htOperation, m_rates, m_vhtCapability, m_vhtOperation, ns3::Buffer::Iterator::ReadLsbtohU16(), and visualizer.core::start().
GetAssociationId()
uint16_t ns3::MgtAssocResponseHeader::GetAssociationId (void) const
Return the association ID.
Returns
the association ID
Definition at line 1040 of file mgt-headers.cc.
References m_aid.
Referenced by ns3::StaWifiMac::Receive().
GetCapabilities()
CapabilityInformation ns3::MgtAssocResponseHeader::GetCapabilities (void) const
Return the Capability information.
Returns
Capability information
Definition at line 944 of file mgt-headers.cc.
References m_capability.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp().
GetEdcaParameterSet()
EdcaParameterSet ns3::MgtAssocResponseHeader::GetEdcaParameterSet (void) const
Return the EDCA Parameter Set.
Returns
the EDCA Parameter Set
Definition at line 1064 of file mgt-headers.cc.
References m_edcaParameterSet.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp().
GetErpInformation()
ErpInformation ns3::MgtAssocResponseHeader::GetErpInformation (void) const
Return the ERP information.
Returns
the ERP information
Definition at line 1052 of file mgt-headers.cc.
References m_erpInformation.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp().
GetExtendedCapabilities()
ExtendedCapabilities ns3::MgtAssocResponseHeader::GetExtendedCapabilities (void) const
Return the extended capabilities.
Returns
the extended capabilities
Definition at line 956 of file mgt-headers.cc.
References m_extendedCapability.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp().
GetHeCapabilities()
HeCapabilities ns3::MgtAssocResponseHeader::GetHeCapabilities (void) const
Return the HE capabilities.
Returns
HE capabilities
Definition at line 1016 of file mgt-headers.cc.
References m_heCapability.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp().
GetHeOperation()
HeOperation ns3::MgtAssocResponseHeader::GetHeOperation (void) const
Return the HE operation.
Returns
HE operation
Definition at line 1028 of file mgt-headers.cc.
References m_heOperation.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp().
GetHtCapabilities()
HtCapabilities ns3::MgtAssocResponseHeader::GetHtCapabilities (void) const
Return the HT capabilities.
Returns
HT capabilities
Definition at line 968 of file mgt-headers.cc.
References m_htCapability.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp().
GetHtOperation()
HtOperation ns3::MgtAssocResponseHeader::GetHtOperation (void) const
Return the HT operation.
Returns
HT operation
Definition at line 980 of file mgt-headers.cc.
References m_htOperation.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp().
GetInstanceTypeId()
TypeId ns3::MgtAssocResponseHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 1081 of file mgt-headers.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::MgtAssocResponseHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 1087 of file mgt-headers.cc.
References ns3::SupportedRates::extended, ns3::EdcaParameterSet::GetSerializedSize(), ns3::ErpInformation::GetSerializedSize(), ns3::ExtendedCapabilities::GetSerializedSize(), ns3::HeCapabilities::GetSerializedSize(), ns3::HeOperation::GetSerializedSize(), ns3::HtCapabilities::GetSerializedSize(), ns3::HtOperation::GetSerializedSize(), ns3::ExtendedSupportedRatesIE::GetSerializedSize(), ns3::VhtCapabilities::GetSerializedSize(), ns3::VhtOperation::GetSerializedSize(), ns3::WifiInformationElement::GetSerializedSize(), ns3::CapabilityInformation::GetSerializedSize(), ns3::StatusCode::GetSerializedSize(), m_capability, m_code, m_edcaParameterSet, m_erpInformation, m_extendedCapability, m_heCapability, m_heOperation, m_htCapability, m_htOperation, m_rates, m_vhtCapability, and m_vhtOperation.
GetStatusCode()
StatusCode ns3::MgtAssocResponseHeader::GetStatusCode (void)
Return the status code.
Returns
the status code
Definition at line 914 of file mgt-headers.cc.
References m_code.
Referenced by ns3::StaWifiMac::Receive().
GetSupportedRates()
SupportedRates ns3::MgtAssocResponseHeader::GetSupportedRates (void)
Return the supported rates.
Returns
the supported rates
Definition at line 920 of file mgt-headers.cc.
References m_rates.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp().
GetTypeId()
TypeId ns3::MgtAssocResponseHeader::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 1070 of file mgt-headers.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
GetVhtCapabilities()
VhtCapabilities ns3::MgtAssocResponseHeader::GetVhtCapabilities (void) const
Return the VHT capabilities.
Returns
VHT capabilities
Definition at line 992 of file mgt-headers.cc.
References m_vhtCapability.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp().
GetVhtOperation()
VhtOperation ns3::MgtAssocResponseHeader::GetVhtOperation (void) const
Return the VHT operation.
Returns
VHT operation
Definition at line 1004 of file mgt-headers.cc.
References m_vhtOperation.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp().
Print()
void ns3::MgtAssocResponseHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 1108 of file mgt-headers.cc.
References m_aid, m_code, m_erpInformation, m_extendedCapability, m_heCapability, m_heOperation, m_htCapability, m_htOperation, m_rates, m_vhtCapability, and m_vhtOperation.
Serialize()
void ns3::MgtAssocResponseHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 1124 of file mgt-headers.cc.
References ns3::SupportedRates::extended, m_aid, m_capability, m_code, m_edcaParameterSet, m_erpInformation, m_extendedCapability, m_heCapability, m_heOperation, m_htCapability, m_htOperation, m_rates, m_vhtCapability, m_vhtOperation, ns3::WifiInformationElement::Serialize(), ns3::CapabilityInformation::Serialize(), ns3::EdcaParameterSet::Serialize(), ns3::ErpInformation::Serialize(), ns3::ExtendedCapabilities::Serialize(), ns3::HeCapabilities::Serialize(), ns3::HeOperation::Serialize(), ns3::HtCapabilities::Serialize(), ns3::HtOperation::Serialize(), ns3::StatusCode::Serialize(), ns3::ExtendedSupportedRatesIE::Serialize(), ns3::VhtCapabilities::Serialize(), ns3::VhtOperation::Serialize(), visualizer.core::start(), and ns3::Buffer::Iterator::WriteHtolsbU16().
SetAssociationId()
void ns3::MgtAssocResponseHeader::SetAssociationId (uint16_t aid)
Set the association ID.
Parameters
aid the association ID
Definition at line 1034 of file mgt-headers.cc.
References m_aid.
Referenced by ns3::ApWifiMac::SendAssocResp().
SetCapabilities()
void ns3::MgtAssocResponseHeader::SetCapabilities (CapabilityInformation capabilities)
Set the Capability information.
Parameters
capabilities Capability information
Definition at line 938 of file mgt-headers.cc.
References m_capability.
Referenced by ns3::ApWifiMac::SendAssocResp().
SetEdcaParameterSet()
void ns3::MgtAssocResponseHeader::SetEdcaParameterSet (EdcaParameterSet edcaParameterSet)
Set the EDCA Parameter Set.
Parameters
edcaParameterSet the EDCA Parameter Set
Definition at line 1058 of file mgt-headers.cc.
References m_edcaParameterSet.
Referenced by ns3::ApWifiMac::SendAssocResp().
SetErpInformation()
void ns3::MgtAssocResponseHeader::SetErpInformation (ErpInformation erpInformation)
Set the ERP information.
Parameters
erpInformation the ERP information
Definition at line 1046 of file mgt-headers.cc.
References m_erpInformation.
Referenced by ns3::ApWifiMac::SendAssocResp().
SetExtendedCapabilities()
void ns3::MgtAssocResponseHeader::SetExtendedCapabilities (ExtendedCapabilities extendedCapabilities)
Set the extended capabilities.
Parameters
extendedCapabilities the extended capabilities
Definition at line 950 of file mgt-headers.cc.
References m_extendedCapability.
Referenced by ns3::ApWifiMac::SendAssocResp().
SetHeCapabilities()
void ns3::MgtAssocResponseHeader::SetHeCapabilities (HeCapabilities heCapabilities)
Set the HE capabilities.
Parameters
heCapabilities HE capabilities
Definition at line 1010 of file mgt-headers.cc.
References m_heCapability.
Referenced by ns3::ApWifiMac::SendAssocResp().
SetHeOperation()
void ns3::MgtAssocResponseHeader::SetHeOperation (HeOperation heOperation)
Set the HE operation.
Parameters
heOperation HE operation
Definition at line 1022 of file mgt-headers.cc.
References m_heOperation.
Referenced by ns3::ApWifiMac::SendAssocResp().
SetHtCapabilities()
void ns3::MgtAssocResponseHeader::SetHtCapabilities (HtCapabilities htCapabilities)
Set the HT capabilities.
Parameters
htCapabilities HT capabilities
Definition at line 962 of file mgt-headers.cc.
References m_htCapability.
Referenced by ns3::ApWifiMac::SendAssocResp().
SetHtOperation()
void ns3::MgtAssocResponseHeader::SetHtOperation (HtOperation htOperation)
Set the HT operation.
Parameters
htOperation HT operation
Definition at line 974 of file mgt-headers.cc.
References m_htOperation.
Referenced by ns3::ApWifiMac::SendAssocResp().
SetStatusCode()
void ns3::MgtAssocResponseHeader::SetStatusCode (StatusCode code)
Set the status code.
Parameters
code the status code
Definition at line 926 of file mgt-headers.cc.
References m_code.
Referenced by ns3::ApWifiMac::SendAssocResp().
SetSupportedRates()
void ns3::MgtAssocResponseHeader::SetSupportedRates (SupportedRates rates)
Set the supported rates.
Parameters
rates the supported rates
Definition at line 932 of file mgt-headers.cc.
References m_rates.
Referenced by ns3::ApWifiMac::SendAssocResp().
SetVhtCapabilities()
void ns3::MgtAssocResponseHeader::SetVhtCapabilities (VhtCapabilities vhtCapabilities)
Set the VHT capabilities.
Parameters
vhtCapabilities VHT capabilities
Definition at line 986 of file mgt-headers.cc.
References m_vhtCapability.
Referenced by ns3::ApWifiMac::SendAssocResp().
SetVhtOperation()
void ns3::MgtAssocResponseHeader::SetVhtOperation (VhtOperation vhtOperation)
Set the VHT operation.
Parameters
vhtOperation VHT operation
Definition at line 998 of file mgt-headers.cc.
References m_vhtOperation.
Referenced by ns3::ApWifiMac::SendAssocResp().
Member Data Documentation
m_aid
uint16_t ns3::MgtAssocResponseHeader::m_aid private
AID.
Definition at line 497 of file mgt-headers.h.
Referenced by Deserialize(), GetAssociationId(), Print(), Serialize(), and SetAssociationId().
m_capability
CapabilityInformation ns3::MgtAssocResponseHeader::m_capability private
Capability information.
Definition at line 495 of file mgt-headers.h.
Referenced by Deserialize(), GetCapabilities(), GetSerializedSize(), Serialize(), and SetCapabilities().
m_code
StatusCode ns3::MgtAssocResponseHeader::m_code private
Status code.
Definition at line 496 of file mgt-headers.h.
Referenced by Deserialize(), GetSerializedSize(), GetStatusCode(), Print(), Serialize(), and SetStatusCode().
m_edcaParameterSet
EdcaParameterSet ns3::MgtAssocResponseHeader::m_edcaParameterSet private
EDCA Parameter Set.
Definition at line 504 of file mgt-headers.h.
Referenced by Deserialize(), GetEdcaParameterSet(), GetSerializedSize(), Serialize(), and SetEdcaParameterSet().
m_erpInformation
ErpInformation ns3::MgtAssocResponseHeader::m_erpInformation private
ERP information.
Definition at line 503 of file mgt-headers.h.
Referenced by Deserialize(), GetErpInformation(), GetSerializedSize(), Print(), Serialize(), and SetErpInformation().
m_extendedCapability
ExtendedCapabilities ns3::MgtAssocResponseHeader::m_extendedCapability private
extended capabilities
Definition at line 498 of file mgt-headers.h.
Referenced by Deserialize(), GetExtendedCapabilities(), GetSerializedSize(), Print(), Serialize(), and SetExtendedCapabilities().
m_heCapability
HeCapabilities ns3::MgtAssocResponseHeader::m_heCapability private
HE capabilities.
Definition at line 505 of file mgt-headers.h.
Referenced by Deserialize(), GetHeCapabilities(), GetSerializedSize(), Print(), Serialize(), and SetHeCapabilities().
m_heOperation
HeOperation ns3::MgtAssocResponseHeader::m_heOperation private
HE operation.
Definition at line 506 of file mgt-headers.h.
Referenced by Deserialize(), GetHeOperation(), GetSerializedSize(), Print(), Serialize(), and SetHeOperation().
m_htCapability
HtCapabilities ns3::MgtAssocResponseHeader::m_htCapability private
HT capabilities.
Definition at line 499 of file mgt-headers.h.
Referenced by Deserialize(), GetHtCapabilities(), GetSerializedSize(), Print(), Serialize(), and SetHtCapabilities().
m_htOperation
HtOperation ns3::MgtAssocResponseHeader::m_htOperation private
HT operation.
Definition at line 500 of file mgt-headers.h.
Referenced by Deserialize(), GetHtOperation(), GetSerializedSize(), Print(), Serialize(), and SetHtOperation().
m_rates
SupportedRates ns3::MgtAssocResponseHeader::m_rates private
List of supported rates.
Definition at line 494 of file mgt-headers.h.
Referenced by Deserialize(), GetSerializedSize(), GetSupportedRates(), Print(), Serialize(), and SetSupportedRates().
m_vhtCapability
VhtCapabilities ns3::MgtAssocResponseHeader::m_vhtCapability private
VHT capabilities.
Definition at line 501 of file mgt-headers.h.
Referenced by Deserialize(), GetSerializedSize(), GetVhtCapabilities(), Print(), Serialize(), and SetVhtCapabilities().
m_vhtOperation
VhtOperation ns3::MgtAssocResponseHeader::m_vhtOperation private
VHT operation.
Definition at line 502 of file mgt-headers.h.
Referenced by Deserialize(), GetSerializedSize(), GetVhtOperation(), Print(), Serialize(), and SetVhtOperation().
The documentation for this class was generated from the following files:
src/wifi/model/mgt-headers.h
src/wifi/model/mgt-headers.cc