ns-3: AcousticModemEnergyTestCase Class Reference
AcousticModemEnergyTestCase Class Reference
UAN Models » uan module tests | Test suites
Acoustic Modem Energy Test Case.
Public Member Functions
AcousticModemEnergyTestCase ()
~AcousticModemEnergyTestCase ()
void DoRun (void)
Implementation to actually run this TestCase.
bool RxPacket (Ptr< NetDevice > dev, Ptr< const Packet > pkt, uint16_t mode, const Address &sender)
Receive packet function.
void SendOnePacket (Ptr< Node > node)
Send one packet function.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Public Attributes
uint32_t m_bytesRx
bytes received
Ptr< Node > m_gateway
the gateway
Ptr< Node > m_node
node
uint32_t m_packetSize
packet size
uint32_t m_sentPackets
number of sent packets
double m_simTime
simulation time
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Acoustic Modem Energy Test Case.
Definition at line 55 of file uan-energy-model-test.cc.
Constructor & Destructor Documentation
AcousticModemEnergyTestCase()
AcousticModemEnergyTestCase::AcousticModemEnergyTestCase ()
Definition at line 86 of file uan-energy-model-test.cc.
~AcousticModemEnergyTestCase()
AcousticModemEnergyTestCase::~AcousticModemEnergyTestCase ()
Definition at line 95 of file uan-energy-model-test.cc.
References m_gateway, and m_node.
Member Function Documentation
DoRun()
void AcousticModemEnergyTestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 130 of file uan-energy-model-test.cc.
References ns3::Object::AggregateObject(), third::channel, ns3::DeviceEnergyModelContainer::Get(), ns3::Node::GetDevice(), ns3::EnergySource::GetInitialEnergy(), ns3::Object::GetObject(), ns3::UanNetDevice::GetPhy(), ns3::EnergySource::GetRemainingEnergy(), ns3::UanHeaderCommon::GetSerializedSize(), ns3::UanHelper::Install(), ns3::DeviceEnergyModelHelper::Install(), ns3::EnergySourceHelper::Install(), m_bytesRx, m_gateway, m_node, m_packetSize, m_sentPackets, m_simTime, ns3::MakeCallback(), third::mobility, NS_TEST_ASSERT_MSG_EQ_TOL, RxPacket(), ns3::Seconds(), SendOnePacket(), ns3::BasicEnergySourceHelper::Set(), ns3::MobilityModel::SetPosition(), and ns3::NetDevice::SetReceiveCallback().
RxPacket()
bool AcousticModemEnergyTestCase::RxPacket (Ptr< NetDevice > dev, Ptr< const Packet > pkt, uint16_t mode, const Address & sender)
Receive packet function.
Parameters
dev the device
pkt the packet
mode the mode
sender the address of the sender
Returns
true if successful
Definition at line 119 of file uan-energy-model-test.cc.
References ns3::Packet::GetSize(), m_bytesRx, and NS_UNUSED.
Referenced by DoRun().
SendOnePacket()
void AcousticModemEnergyTestCase::SendOnePacket (Ptr< Node > node)
Send one packet function.
Parameters
node the node to send to
Definition at line 102 of file uan-energy-model-test.cc.
References ns3::UanNetDevice::GetBroadcast(), ns3::Node::GetDevice(), m_packetSize, m_sentPackets, ns3::Seconds(), and ns3::UanNetDevice::Send().
Referenced by DoRun().
Member Data Documentation
m_bytesRx
uint32_t AcousticModemEnergyTestCase::m_bytesRx
bytes received
Definition at line 79 of file uan-energy-model-test.cc.
Referenced by DoRun(), and RxPacket().
m_gateway
Ptr<Node> AcousticModemEnergyTestCase::m_gateway
the gateway
Definition at line 83 of file uan-energy-model-test.cc.
Referenced by ~AcousticModemEnergyTestCase(), and DoRun().
m_node
Ptr<Node> AcousticModemEnergyTestCase::m_node
node
Definition at line 82 of file uan-energy-model-test.cc.
Referenced by ~AcousticModemEnergyTestCase(), and DoRun().
m_packetSize
uint32_t AcousticModemEnergyTestCase::m_packetSize
packet size
Definition at line 81 of file uan-energy-model-test.cc.
Referenced by DoRun(), and SendOnePacket().
m_sentPackets
uint32_t AcousticModemEnergyTestCase::m_sentPackets
number of sent packets
Definition at line 80 of file uan-energy-model-test.cc.
Referenced by DoRun(), and SendOnePacket().
m_simTime
double AcousticModemEnergyTestCase::m_simTime
simulation time
Definition at line 78 of file uan-energy-model-test.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/uan/test/uan-energy-model-test.cc