ns-3: ns3::LteAsSapProvider Class Reference
ns3::LteAsSapProvider Class Reference abstract
This class implements the Access Stratum (AS) Service Access Point (SAP), i.e., the interface between the EpcUeNas and the LteUeRrc.
#include "lte-as-sap.h"
Public Member Functions
virtual ~LteAsSapProvider ()
virtual void Connect (void)=0
Tell the RRC entity to enter Connected mode.
virtual void Disconnect ()=0
Tell the RRC entity to release the connection.
virtual void ForceCampedOnEnb (uint16_t cellId, uint32_t dlEarfcn)=0
Force the RRC entity to stay camped on a certain eNodeB.
virtual void SendData (Ptr< Packet > packet, uint8_t bid)=0
Send a data packet.
virtual void SetCsgWhiteList (uint32_t csgId)=0
Set the selected Closed Subscriber Group subscription list to be used for cell selection.
virtual void StartCellSelection (uint32_t dlEarfcn)=0
Initiate Idle mode cell selection procedure.
Detailed Description
This class implements the Access Stratum (AS) Service Access Point (SAP), i.e., the interface between the EpcUeNas and the LteUeRrc.
In particular, this class implements the Provider part of the SAP, i.e., the methods exported by the LteUeRrc and called by the EpcUeNas.
Definition at line 41 of file lte-as-sap.h.
Constructor & Destructor Documentation
~LteAsSapProvider()
ns3::LteAsSapProvider::~LteAsSapProvider () virtual
Definition at line 25 of file lte-as-sap.cc.
Member Function Documentation
Connect()
virtual void ns3::LteAsSapProvider::Connect (void) pure virtual
Tell the RRC entity to enter Connected mode.
If this function is called when the UE is in a situation where connecting is not possible (e.g. before the simulation begin), then the UE will attempt to connect at the earliest possible time (e.g. after it camps to a suitable cell).
Implemented in ns3::MemberLteAsSapProvider< C >.
Referenced by ns3::EpcUeNas::Connect(), and ns3::EpcUeNas::DoNotifyConnectionFailed().
Disconnect()
virtual void ns3::LteAsSapProvider::Disconnect () pure virtual
Tell the RRC entity to release the connection.
Implemented in ns3::MemberLteAsSapProvider< C >.
Referenced by ns3::EpcUeNas::Disconnect().
ForceCampedOnEnb()
virtual void ns3::LteAsSapProvider::ForceCampedOnEnb (uint16_t cellId, uint32_t dlEarfcn) pure virtual
Force the RRC entity to stay camped on a certain eNodeB.
Parameters
cellId the cell ID identifying the eNodeB
dlEarfcn the downlink carrier frequency (EARFCN)
Implemented in ns3::MemberLteAsSapProvider< C >.
Referenced by ns3::EpcUeNas::Connect().
SendData()
virtual void ns3::LteAsSapProvider::SendData (Ptr< Packet > packet, uint8_t bid) pure virtual
Send a data packet.
Parameters
packet the packet
bid the EPS bearer ID
Implemented in ns3::MemberLteAsSapProvider< C >.
Referenced by ns3::EpcUeNas::Send().
SetCsgWhiteList()
virtual void ns3::LteAsSapProvider::SetCsgWhiteList (uint32_t csgId) pure virtual
Set the selected Closed Subscriber Group subscription list to be used for cell selection.
Parameters
csgId identity of the subscribed CSG
Implemented in ns3::MemberLteAsSapProvider< C >.
Referenced by ns3::EpcUeNas::SetCsgId().
StartCellSelection()
virtual void ns3::LteAsSapProvider::StartCellSelection (uint32_t dlEarfcn) pure virtual
Initiate Idle mode cell selection procedure.
Parameters
dlEarfcn the downlink carrier frequency (EARFCN)
Implemented in ns3::MemberLteAsSapProvider< C >.
Referenced by ns3::EpcUeNas::StartCellSelection().
The documentation for this class was generated from the following files:
src/lte/model/lte-as-sap.h
src/lte/model/lte-as-sap.cc