ns-3: ns3::WaveMacLow Class Reference
ns3::WaveMacLow Class Reference
WAVE module
#include "wave-mac-low.h"
Public Member Functions
WaveMacLow ()
virtual ~WaveMacLow ()
void SetWaveNetDevice (Ptr< WaveNetDevice > device)
virtual void StartTransmission (Ptr< WifiMacQueueItem > mpdu, MacLowTransmissionParameters parameters, Ptr< Txop > txop)
Public Member Functions inherited from ns3::MacLow
MacLow ()
virtual ~MacLow ()
Time CalculateOverallTxTime (Ptr< const Packet > packet, const WifiMacHeader *hdr, const MacLowTransmissionParameters &params, uint32_t fragmentSize=0) const
Time CalculateOverheadTxTime (Ptr< const WifiMacQueueItem > item, const MacLowTransmissionParameters &params) const
Time CalculateTransmissionTime (Ptr< const Packet > packet, const WifiMacHeader *hdr, const MacLowTransmissionParameters &parameters) const
bool CanTransmitNextCfFrame (void) const
This function decides if a CF frame can be transmitted in the current CFP.
void CreateBlockAckAgreement (const MgtAddBaResponseHeader *respHdr, Mac48Address originator, uint16_t startingSeq)
void DeaggregateAmpduAndReceive (Ptr< WifiPsdu > aggregatedPacket, double rxSnr, WifiTxVector txVector, std::vector< bool > statusPerMpdu)
void DestroyBlockAckAgreement (Mac48Address originator, uint8_t tid)
bool DoNavStartNow (Time duration)
Start NAV with the given duration.
Time GetAckTimeout (void) const
Return Ack timeout of this MacLow.
Mac48Address GetAddress (void) const
Return the MAC address of this MacLow.
Time GetBasicBlockAckTimeout (void) const
Return Basic BlockAck timeout of this MacLow.
Time GetBeaconInterval (void) const
Mac48Address GetBssid (void) const
Return the Basic Service Set Identification.
Time GetCfpMaxDuration (void) const
Time GetCompressedBlockAckTimeout (void) const
Return Compressed BlockAck timeout of this MacLow.
bool GetCtsToSelfSupported (void) const
Return whether CTS-to-self capability is supported.
Ptr< QosTxop > GetEdca (uint8_t tid) const
Ptr< MpduAggregator > GetMpduAggregator (void) const
Returns the aggregator used to construct A-MPDU subframes.
Ptr< MsduAggregator > GetMsduAggregator (void) const
Returns the aggregator used to construct A-MSDU subframes.
Ptr< WifiPhy > GetPhy (void) const
Time GetPifs (void) const
Return PCF Interframe Space (PIFS) of this MacLow.
Time GetRemainingCfpDuration (void) const
Time GetRifs (void) const
Return Reduced Interframe Space (RIFS) of this MacLow.
Time GetSifs (void) const
Return Short Interframe Space (SIFS) of this MacLow.
Time GetSlotTime (void) const
Return slot duration of this MacLow.
virtual bool IsCfPeriod (void) const
This function indicates whether Simulator::Now is in the CF period.
bool IsPromisc (void) const
Check if MacLow is operating in promiscuous mode.
bool IsWithinSizeAndTimeLimits (Ptr< const WifiMacQueueItem > mpdu, WifiTxVector txVector, uint32_t ampduSize, Time ppduDurationLimit)
Check whether the given MPDU, if transmitted according to the given TX vector, meets the constraint on the maximum A-MPDU size (by assuming that the frame has to be aggregated to an existing A-MPDU of the given size) and its transmission time exceeds neither the max PPDU duration (depending on the PPDU format) nor the given PPDU duration limit (if strictly positive).
bool IsWithinSizeAndTimeLimits (uint32_t mpduSize, Mac48Address receiver, uint8_t tid, WifiTxVector txVector, uint32_t ampduSize, Time ppduDurationLimit)
Check whether an MPDU of the given size, destined to the given receiver and belonging to the given TID, if transmitted according to the given TX vector, meets the constraint on the maximum A-MPDU size (by assuming that the frame has to be aggregated to an existing A-MPDU of the given size) and its transmission time exceeds neither the max PPDU duration (depending on the PPDU format) nor the given PPDU duration limit (if strictly positive).
void NotifyOffNow (void)
This method is typically invoked by the PhyMacLowListener to notify the MAC layer that the device has been put into off mode.
void NotifySleepNow (void)
This method is typically invoked by the PhyMacLowListener to notify the MAC layer that the device has been put into sleep mode.
void NotifySwitchingStartNow (Time duration)
void ReceiveError (Ptr< WifiPsdu > psdu)
void ReceiveOk (Ptr< WifiMacQueueItem > mpdu, double rxSnr, WifiTxVector txVector, bool ampduSubframe)
void RegisterChannelAccessManager (Ptr< ChannelAccessManager > channelAccessManager)
void RegisterEdcaForAc (AcIndex ac, Ptr< QosTxop > edca)
void ResetPhy (void)
Remove WifiPhy associated with this MacLow.
void RxStartIndication (WifiTxVector txVector, Time psduDuration)
void SetAckTimeout (Time ackTimeout)
Set Ack timeout of this MacLow.
void SetAddress (Mac48Address ad)
Set MAC address of this MacLow.
void SetBasicBlockAckTimeout (Time blockAckTimeout)
Set Basic BlockAck timeout of this MacLow.
void SetBeaconInterval (Time interval)
void SetBssid (Mac48Address ad)
Set the Basic Service Set Identification.
void SetCfpMaxDuration (Time duration)
void SetCompressedBlockAckTimeout (Time blockAckTimeout)
Set Compressed BlockAck timeout of this MacLow.
void SetCtsToSelfSupported (bool enable)
Enable or disable CTS-to-self capability.
void SetMac (const Ptr< WifiMac > mac)
Set up WifiMac associated with this MacLow.
void SetMpduAggregator (const Ptr< MpduAggregator > aggr)
Set the aggregator used to construct A-MPDU subframes.
void SetMsduAggregator (const Ptr< MsduAggregator > aggr)
Set the aggregator used to construct A-MSDU subframes.
void SetPhy (const Ptr< WifiPhy > phy)
Set up WifiPhy associated with this MacLow.
void SetPifs (Time pifs)
Set PCF Interframe Space (PIFS) of this MacLow.
void SetPromisc (void)
Enable promiscuous mode.
void SetRifs (Time rifs)
Set Reduced Interframe Space (RIFS) of this MacLow.
void SetRxCallback (Callback< void, Ptr< WifiMacQueueItem >> callback)
void SetSifs (Time sifs)
Set Short Interframe Space (SIFS) of this MacLow.
void SetSlotTime (Time slotTime)
Set slot duration of this MacLow.
void SetWifiRemoteStationManager (const Ptr< WifiRemoteStationManager > manager)
Set up WifiRemoteStationManager associated with this MacLow.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::MacLow
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual WifiTxVector GetDataTxVector (Ptr< const WifiMacQueueItem > item) const
Return a TXVECTOR for the DATA frame given the destination.
Private Attributes
Ptr< ChannelCoordinator > m_coordinator
the channel coordinator
Ptr< ChannelScheduler > m_scheduler
the channel scheduler
Additional Inherited Members
Public Types inherited from ns3::MacLow
typedef Callback< void, Ptr< WifiMacQueueItem > > MacLowRxCallback
typedef for a callback for MacLowRx
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class is the subclass of MacLow to provide support for MAC extension (1) allows higher layer control data rate and tx power level. If higher layer does not set, they will be determined by WifiRemoteStationManager of MAC layer; If higher layer sets tx parameters in non-adaptable mode, the data rate and tx power level will be used for transmission;. If higher layer sets tx parameters in adaptable mode, the data rate will be lower bound for the actual data rate, and the power level will be upper bound for the actual transmit power. (2) implements the feature described in Annex C : avoid transmission at scheduled guard intervals However, the feature is extended further here that the required transmit time is determined by MAC layer itself rather than PHY layer, which contains RTS/CTS, DATA and ACK time.
Definition at line 49 of file wave-mac-low.h.
Constructor & Destructor Documentation
WaveMacLow()
ns3::WaveMacLow::WaveMacLow ()
Definition at line 45 of file wave-mac-low.cc.
References NS_LOG_FUNCTION.
~WaveMacLow()
ns3::WaveMacLow::~WaveMacLow () virtual
Definition at line 49 of file wave-mac-low.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
GetDataTxVector()
WifiTxVector ns3::WaveMacLow::GetDataTxVector (Ptr< const WifiMacQueueItem > item) const private virtual
Return a TXVECTOR for the DATA frame given the destination.
The function consults WifiRemoteStationManager, which controls the rate to different destinations.
Parameters
item the item being asked for TXVECTOR
Returns
TXVECTOR for the given item
Reimplemented from ns3::MacLow.
Definition at line 63 of file wave-mac-low.cc.
References ns3::WifiTxVector::GetChannelWidth(), ns3::WifiMode::GetDataRate(), ns3::MacLow::GetDataTxVector(), ns3::WifiTxVector::GetMode(), ns3::WifiTxVector::GetPreambleType(), ns3::WifiTxVector::GetTxPowerLevel(), ns3::HigherLayerTxVectorTag::GetTxVector(), ns3::HigherLayerTxVectorTag::IsAdaptable(), min, NS_LOG_FUNCTION, ns3::WifiTxVector::SetChannelWidth(), ns3::WifiTxVector::SetMode(), ns3::WifiTxVector::SetPreambleType(), and ns3::WifiTxVector::SetTxPowerLevel().
GetTypeId()
TypeId ns3::WaveMacLow::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 36 of file wave-mac-low.cc.
References ns3::TypeId::SetParent().
SetWaveNetDevice()
void ns3::WaveMacLow::SetWaveNetDevice (Ptr< WaveNetDevice > device)
Parameters
device WaveNetDevice associated with WaveMacLow
Definition at line 55 of file wave-mac-low.cc.
References ns3::WaveNetDevice::GetChannelCoordinator(), ns3::WaveNetDevice::GetChannelScheduler(), m_coordinator, m_scheduler, and NS_ASSERT.
StartTransmission()
void ns3::WaveMacLow::StartTransmission (Ptr< WifiMacQueueItem > mpdu, MacLowTransmissionParameters parameters, Ptr< Txop > txop) virtual
Parameters
mpdu packet to send
parameters the transmission parameters to use for this packet.
txop pointer to the calling Txop.
Start the transmission of the input packet and notify the listener of transmission events.
Reimplemented from ns3::MacLow.
Definition at line 109 of file wave-mac-low.cc.
References ns3::MacLow::CalculateTransmissionTime(), ns3::WifiMacQueueItem::GetHeader(), ns3::Time::GetMilliSeconds(), ns3::WifiMacQueueItem::GetPacket(), ns3::MacLow::GetPhy(), m_coordinator, m_scheduler, ns3::ChannelCoordinator::NeedTimeToGuardInterval(), NS_LOG_DEBUG, NS_LOG_FUNCTION, aloha::params, third::phy, and ns3::MacLow::StartTransmission().
Member Data Documentation
m_coordinator
Ptr<ChannelCoordinator> ns3::WaveMacLow::m_coordinator private
the channel coordinator
Definition at line 88 of file wave-mac-low.h.
Referenced by SetWaveNetDevice(), and StartTransmission().
m_scheduler
Ptr<ChannelScheduler> ns3::WaveMacLow::m_scheduler private
the channel scheduler
Definition at line 87 of file wave-mac-low.h.
Referenced by SetWaveNetDevice(), and StartTransmission().
The documentation for this class was generated from the following files:
src/wave/model/wave-mac-low.h
src/wave/model/wave-mac-low.cc