ns-3: ns3::ZipfRandomVariable Class Reference
ns3::ZipfRandomVariable Class Reference
Core » Random Variables
The Zipf distribution Random Number Generator (RNG) that allows stream numbers to be set deterministically.
#include "random-variable-stream.h"
Public Member Functions
ZipfRandomVariable ()
Creates a Zipf distribution RNG with the default values for n and alpha.
double GetAlpha (void) const
Returns the alpha value for the Zipf distribution returned by this RNG stream.
uint32_t GetInteger (uint32_t n, uint32_t alpha)
Returns a random unsigned integer from a Zipf distribution with the specified n and alpha.
virtual uint32_t GetInteger (void)
Returns a random unsigned integer from a Zipf distribution with the current n and alpha.
uint32_t GetN (void) const
Returns the n value for the Zipf distribution returned by this RNG stream.
double GetValue (uint32_t n, double alpha)
Returns a random double from a Zipf distribution with the specified n and alpha.
virtual double GetValue (void)
Returns a random double from a Zipf distribution with the current n and alpha.
Public Member Functions inherited from ns3::RandomVariableStream
RandomVariableStream ()
Default constructor.
virtual ~RandomVariableStream ()
Destructor.
int64_t GetStream (void) const
Returns the stream number for the RngStream.
bool IsAntithetic (void) const
Check if antithetic values will be generated.
void SetAntithetic (bool isAntithetic)
Specify whether antithetic values should be generated.
void SetStream (int64_t stream)
Specifies the stream number for the RngStream.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::RandomVariableStream
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
double m_alpha
The alpha value for the Zipf distribution returned by this RNG stream.
double m_c
The normalization constant.
uint32_t m_n
The n value for the Zipf distribution returned by this RNG stream.
Additional Inherited Members
Protected Member Functions inherited from ns3::RandomVariableStream
RngStream * Peek (void) const
Get the pointer to the underlying RngStream.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The Zipf distribution Random Number Generator (RNG) that allows stream numbers to be set deterministically.
This class supports the creation of objects that return random numbers from a fixed Zipf distribution. It also supports the generation of single random numbers from various Zipf distributions.
The Zipf's law states that given some corpus of natural language utterances, the frequency of any word is inversely proportional to its rank in the frequency table.
Zipf's distribution has two parameters, alpha and N, where: (real) and (integer). Probability Mass Function is where
Here is an example of how to use this class:
uint32_t n = 1;
double alpha = 2.0;
Ptr<ZipfRandomVariable> x = CreateObject<ZipfRandomVariable> ();
x->SetAttribute ("N", IntegerValue (n));
x->SetAttribute ("Alpha", DoubleValue (alpha));
// The expected value for the mean of the values returned by a
// Zipfly distributed random variable is equal to
//
//                   H
//                    N, alpha - 1
//     E[value]  =  ---------------
//                     H
//                      N, alpha
//
// where
//
//                    N
//                   ---
//                   \     -alpha
//     H          =  /    m        .
//      N, alpha     ---
//                   m=1
//
// For this test,
//
//                      -(alpha - 1)
//                     1
//     E[value]  =  ---------------
//                      -alpha
//                     1
//
//               =  1  .
//
double value = x->GetValue ();
Definition at line 2100 of file random-variable-stream.h.
Constructor & Destructor Documentation
ZipfRandomVariable()
ns3::ZipfRandomVariable::ZipfRandomVariable ()
Creates a Zipf distribution RNG with the default values for n and alpha.
Definition at line 1304 of file random-variable-stream.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
GetAlpha()
double ns3::ZipfRandomVariable::GetAlpha (void) const
Returns the alpha value for the Zipf distribution returned by this RNG stream.
Returns
The alpha value for the Zipf distribution returned by this RNG stream.
Definition at line 1317 of file random-variable-stream.cc.
References m_alpha, and NS_LOG_FUNCTION.
GetInteger() [1/2]
uint32_t ns3::ZipfRandomVariable::GetInteger (uint32_t n, uint32_t alpha)
Returns a random unsigned integer from a Zipf distribution with the specified n and alpha.
Parameters
[in] n N value for the Zipf distribution.
[in] alpha Alpha value for the Zipf distribution.
Returns
A random unsigned integer value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If is a uniform variable over [0,1] and is a value that would be returned normally, then) is the distance that would be from . The value returned in the antithetic case, , uses (1-u), which is the distance is from the 1.
Definition at line 1356 of file random-variable-stream.cc.
References sample-rng-plot::alpha, GetValue(), sample-rng-plot::n, and NS_LOG_FUNCTION.
GetInteger() [2/2]
uint32_t ns3::ZipfRandomVariable::GetInteger (void) virtual
Returns a random unsigned integer from a Zipf distribution with the current n and alpha.
Returns
A random unsigned integer value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If is a uniform variable over [0,1] and is a value that would be returned normally, then) is the distance that would be from . The value returned in the antithetic case, , uses (1-u), which is the distance is from the 1.
Implements ns3::RandomVariableStream.
Definition at line 1369 of file random-variable-stream.cc.
References GetValue(), m_alpha, m_n, and NS_LOG_FUNCTION.
GetN()
uint32_t ns3::ZipfRandomVariable::GetN (void) const
Returns the n value for the Zipf distribution returned by this RNG stream.
Returns
The n value for the Zipf distribution returned by this RNG stream.
Definition at line 1311 of file random-variable-stream.cc.
References m_n, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::ZipfRandomVariable::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 1287 of file random-variable-stream.cc.
References m_alpha, m_n, ns3::MakeDoubleAccessor(), ns3::MakeIntegerAccessor(), and ns3::TypeId::SetParent().
GetValue() [1/2]
double ns3::ZipfRandomVariable::GetValue (uint32_t n, double alpha)
Returns a random double from a Zipf distribution with the specified n and alpha.
Parameters
[in] n N value for the Zipf distribution.
[in] alpha Alpha value for the Zipf distribution.
Returns
A floating point random value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If is a uniform variable over [0,1] and is a value that would be returned normally, then) is the distance that would be from . The value returned in the antithetic case, , uses (1-u), which is the distance is from the 1.
Definition at line 1324 of file random-variable-stream.cc.
References sample-rng-plot::alpha, ns3::RandomVariableStream::IsAntithetic(), m_alpha, m_c, m_n, sample-rng-plot::n, NS_LOG_FUNCTION, ns3::RandomVariableStream::Peek(), and ns3::RngStream::RandU01().
GetValue() [2/2]
double ns3::ZipfRandomVariable::GetValue (void) virtual
Returns a random double from a Zipf distribution with the current n and alpha.
Returns
A floating point random value.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If is a uniform variable over [0,1] and is a value that would be returned normally, then) is the distance that would be from . The value returned in the antithetic case, , uses (1-u), which is the distance is from the 1.
Note that we have to re-implement this method here because the method is overloaded above for the two-argument variant and the c++ name resolution rules don't work well with overloads split between parent and child classes.
Implements ns3::RandomVariableStream.
Definition at line 1363 of file random-variable-stream.cc.
References m_alpha, m_n, and NS_LOG_FUNCTION.
Referenced by GetInteger().
Member Data Documentation
m_alpha
double ns3::ZipfRandomVariable::m_alpha private
The alpha value for the Zipf distribution returned by this RNG stream.
Definition at line 2193 of file random-variable-stream.h.
Referenced by GetAlpha(), GetInteger(), GetTypeId(), and GetValue().
m_c
double ns3::ZipfRandomVariable::m_c private
The normalization constant.
Definition at line 2196 of file random-variable-stream.h.
Referenced by GetValue().
m_n
uint32_t ns3::ZipfRandomVariable::m_n private
The n value for the Zipf distribution returned by this RNG stream.
Definition at line 2190 of file random-variable-stream.h.
Referenced by GetInteger(), GetN(), GetTypeId(), and GetValue().
The documentation for this class was generated from the following files:
src/core/model/random-variable-stream.h
src/core/model/random-variable-stream.cc