ns-3: ns3::EthernetTrailer Class Reference
ns3::EthernetTrailer Class Reference
Network
Packet trailer for Ethernet.
#include "ethernet-trailer.h"
Public Member Functions
EthernetTrailer ()
Construct a null ethernet trailer.
void CalcFcs (Ptr< const Packet > p)
Updates the Fcs Field to the correct FCS.
bool CheckFcs (Ptr< const Packet > p) const
Calculate an FCS on the provided packet and check this value against the FCS found when the trailer was deserialized (the one in the transmitted packet).
virtual uint32_t Deserialize (Buffer::Iterator end)
void EnableFcs (bool enable)
Enable or disable FCS checking and calculations.
uint32_t GetFcs () const
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize (void) const
uint32_t GetTrailerSize () const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator end) const
void SetFcs (uint32_t fcs)
Sets the FCS to a new value.
Public Member Functions inherited from ns3::Trailer
virtual ~Trailer ()
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Trailer
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
bool m_calcFcs
Enabled FCS calculations.
uint32_t m_fcs
Value of the fcs contained in the trailer.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Packet trailer for Ethernet.
This class can be used to add and verify the FCS at the end of an Ethernet packet.
Definition at line 39 of file ethernet-trailer.h.
Constructor & Destructor Documentation
EthernetTrailer()
ns3::EthernetTrailer::EthernetTrailer ()
Construct a null ethernet trailer.
Definition at line 33 of file ethernet-trailer.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CalcFcs()
void ns3::EthernetTrailer::CalcFcs (Ptr< const Packet > p)
Updates the Fcs Field to the correct FCS.
Parameters
p Reference to a packet on which the FCS should be calculated. The packet should not currently contain an EthernetTrailer.
Definition at line 68 of file ethernet-trailer.cc.
References ns3::CRC32Calculate(), m_calcFcs, m_fcs, and NS_LOG_FUNCTION.
Referenced by ns3::CsmaNetDevice::AddHeader().
CheckFcs()
bool ns3::EthernetTrailer::CheckFcs (Ptr< const Packet > p) const
Calculate an FCS on the provided packet and check this value against the FCS found when the trailer was deserialized (the one in the transmitted packet).
If FCS checking is disabled, this method will always return true.
Parameters
p Reference to the packet on which the FCS should be calculated. The packet should not contain an EthernetTrailer.
Returns
Returns true if the Packet FCS matches the FCS in the trailer, false otherwise.
Definition at line 48 of file ethernet-trailer.cc.
References ns3::CRC32Calculate(), m_calcFcs, m_fcs, and NS_LOG_FUNCTION.
Referenced by ns3::CsmaNetDevice::Receive().
Deserialize()
uint32_t ns3::EthernetTrailer::Deserialize (Buffer::Iterator end) virtual
Parameters
end an iterator which points to the end of the buffer where the trailer should be read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveTrailer to re-create a trailer from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this trailer in real networks. The input iterator points to the end of the area where the data shall be written. This method is thus expected to call Buffer::Iterator::Prev prior to actually reading any data.
Implements ns3::Trailer.
Definition at line 144 of file ethernet-trailer.cc.
References GetSerializedSize(), m_fcs, NS_LOG_FUNCTION, ns3::Buffer::Iterator::Prev(), and ns3::Buffer::Iterator::ReadU32().
EnableFcs()
void ns3::EthernetTrailer::EnableFcs (bool enable)
Enable or disable FCS checking and calculations.
Parameters
enable If true, enables FCS calculations.
Definition at line 41 of file ethernet-trailer.cc.
References m_calcFcs, and NS_LOG_FUNCTION.
Referenced by ns3::CsmaNetDevice::AddHeader(), and ns3::CsmaNetDevice::Receive().
GetFcs()
uint32_t ns3::EthernetTrailer::GetFcs () const
Returns
the FCS contained in this trailer
Definition at line 93 of file ethernet-trailer.cc.
References m_fcs, and NS_LOG_FUNCTION.
GetInstanceTypeId()
TypeId ns3::EthernetTrailer::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 117 of file ethernet-trailer.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::EthernetTrailer::GetSerializedSize (void) const virtual
Returns
the expected size of the trailer.
This method is used by Packet::AddTrailer to store a trailer into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full trailer data by Serialize.
Implements ns3::Trailer.
Definition at line 128 of file ethernet-trailer.cc.
References NS_LOG_FUNCTION.
Referenced by Deserialize(), GetTrailerSize(), and Serialize().
GetTrailerSize()
uint32_t ns3::EthernetTrailer::GetTrailerSize () const
Returns
Returns the size of the trailer
Definition at line 100 of file ethernet-trailer.cc.
References GetSerializedSize(), and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::EthernetTrailer::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 107 of file ethernet-trailer.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::EthernetTrailer::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a trailer as ascii data to a c++ output stream. Although the trailer is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Trailer.
Definition at line 122 of file ethernet-trailer.cc.
References m_fcs, and NS_LOG_FUNCTION.
Serialize()
void ns3::EthernetTrailer::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the trailer should be written.
This method is used by Packet::AddTrailer to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this trailer in real networks. The input iterator points to the end of the area where the data shall be written. This method is thus expected to call Buffer::Iterator::Prev prior to actually writing any data.
Implements ns3::Trailer.
Definition at line 135 of file ethernet-trailer.cc.
References GetSerializedSize(), m_fcs, NS_LOG_FUNCTION, ns3::Buffer::Iterator::Prev(), and ns3::Buffer::Iterator::WriteU32().
SetFcs()
void ns3::EthernetTrailer::SetFcs (uint32_t fcs)
Sets the FCS to a new value.
Parameters
fcs New FCS value
Definition at line 86 of file ethernet-trailer.cc.
References m_fcs, and NS_LOG_FUNCTION.
Member Data Documentation
m_calcFcs
bool ns3::EthernetTrailer::m_calcFcs private
Enabled FCS calculations.
If false, m_fcs is set to 0 and CheckFcs returns true.
Definition at line 108 of file ethernet-trailer.h.
Referenced by CalcFcs(), CheckFcs(), and EnableFcs().
m_fcs
uint32_t ns3::EthernetTrailer::m_fcs private
Value of the fcs contained in the trailer.
Definition at line 109 of file ethernet-trailer.h.
Referenced by CalcFcs(), CheckFcs(), Deserialize(), GetFcs(), Print(), Serialize(), and SetFcs().
The documentation for this class was generated from the following files:
src/network/utils/ethernet-trailer.h
src/network/utils/ethernet-trailer.cc