ns-3: LteLinkAdaptationTestCase Class Reference
LteLinkAdaptationTestCase Class Reference
LTE Models » lte module tests | Test suites
Test that LTE link adaptation works according to the theoretical model.
#include "lte-test-link-adaptation.h"
Public Member Functions
LteLinkAdaptationTestCase ()
LteLinkAdaptationTestCase (std::string name, double snrDb, double loss, uint16_t mcsIndex)
Constructor.
virtual ~LteLinkAdaptationTestCase ()
void DlScheduling (DlSchedulingCallbackInfo dlInfo)
DL scheduling function.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
double m_loss
the loss
uint16_t m_mcsIndex
the MCS index
double m_snrDb
the SNR in dB
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test that LTE link adaptation works according to the theoretical model.
Definition at line 49 of file lte-test-link-adaptation.h.
Constructor & Destructor Documentation
LteLinkAdaptationTestCase() [1/2]
LteLinkAdaptationTestCase::LteLinkAdaptationTestCase (std::string name, double snrDb, double loss, uint16_t mcsIndex)
Constructor.
TestCase.
Parameters
name the reference name
snrDb the SNR in dB
loss the loss
mcsIndex the DL se
Definition at line 138 of file lte-test-link-adaptation.cc.
References NS_LOG_INFO.
LteLinkAdaptationTestCase() [2/2]
LteLinkAdaptationTestCase::LteLinkAdaptationTestCase ()
~LteLinkAdaptationTestCase()
LteLinkAdaptationTestCase::~LteLinkAdaptationTestCase () virtual
Definition at line 151 of file lte-test-link-adaptation.cc.
Member Function Documentation
DlScheduling()
void LteLinkAdaptationTestCase::DlScheduling (DlSchedulingCallbackInfo dlInfo)
DL scheduling function.
Parameters
dlInfo the DL info
Note: the MCS can only be properly evaluated after: RRC connection has been completed and CQI feedback is available at the eNB.
Definition at line 227 of file lte-test-link-adaptation.cc.
References m_mcsIndex, m_snrDb, ns3::DlSchedulingCallbackInfo::mcsTb1, ns3::Now(), NS_LOG_INFO, and NS_TEST_ASSERT_MSG_EQ.
Referenced by LteTestDlSchedulingCallback().
DoRun()
void LteLinkAdaptationTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Simulation Topology
Implements ns3::TestCase.
Definition at line 156 of file lte-test-link-adaptation.cc.
References ns3::LteHelper::ActivateDataRadioBearer(), ns3::LteHelper::Attach(), ns3::Config::Connect(), ns3::NodeContainer::Create(), ns3::LteHelper::EnableMacTraces(), ns3::LteHelper::EnableRlcTraces(), ns3::NetDeviceContainer::Get(), ns3::LtePhy::GetDownlinkSpectrumPhy(), ns3::Object::GetObject(), ns3::LteSpectrumValueCatcher::GetValue(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), LteTestDlSchedulingCallback(), m_loss, m_snrDb, ns3::MakeBoundCallback(), ns3::MakeCallback(), third::mobility, NS_LOG_INFO, NS_TEST_ASSERT_MSG_EQ_TOL, ns3::Config::Reset(), ns3::Seconds(), ns3::ObjectBase::SetAttribute(), ns3::Config::SetDefault(), ns3::LteHelper::SetPathlossModelAttribute(), and ns3::LteHelper::SetSchedulerType().
Member Data Documentation
m_loss
double LteLinkAdaptationTestCase::m_loss private
the loss
Definition at line 74 of file lte-test-link-adaptation.h.
Referenced by DoRun().
m_mcsIndex
uint16_t LteLinkAdaptationTestCase::m_mcsIndex private
the MCS index
Definition at line 75 of file lte-test-link-adaptation.h.
Referenced by DlScheduling().
m_snrDb
double LteLinkAdaptationTestCase::m_snrDb private
the SNR in dB
Definition at line 73 of file lte-test-link-adaptation.h.
Referenced by DlScheduling(), and DoRun().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-link-adaptation.h
src/lte/test/lte-test-link-adaptation.cc