ns-3: ns3::lorawan::LoraFrameHeader Class Reference
ns3::lorawan::LoraFrameHeader Class Reference
This class represents the Frame header (FHDR) used in a LoraWAN network.
#include "lora-frame-header.h"
Public Member Functions
LoraFrameHeader ()
~LoraFrameHeader ()
void AddCommand (Ptr< MacCommand > macCommand)
Add a predefined command to the list.
void AddDevStatusReq ()
Add a DevStatusReq command.
void AddDutyCycleAns (void)
Add a DutyCycleAns command.
void AddDutyCycleReq (uint8_t dutyCycle)
Add a DutyCycleReq command.
void AddLinkAdrAns (bool powerAck, bool dataRateAck, bool channelMaskAck)
Add a LinkAdrAns command.
void AddLinkAdrReq (uint8_t dataRate, uint8_t txPower, std::list< int > enabledChannels, int repetitions)
Add a LinkAdrReq command.
void AddLinkCheckAns (uint8_t margin, uint8_t gwCnt)
Add a LinkCheckAns command.
void AddLinkCheckReq (void)
Add a LinkCheckReq command.
void AddNewChannelReq (uint8_t chIndex, double frequency, uint8_t minDataRate, uint8_t maxDataRate)
Add a NewChannelReq command.
void AddRxParamSetupAns ()
Add a RxParamSetupAns command.
void AddRxParamSetupReq (uint8_t rx1DrOffset, uint8_t rx2DataRate, double frequency)
Add a RxParamSetupReq command.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the contents of the buffer into a LoraFrameHeader object.
bool GetAck (void) const
Get the Ack bit value.
LoraDeviceAddress GetAddress (void) const
Get this header's device address value.
bool GetAdr (void) const
Get the Adr value.
bool GetAdrAckReq (void) const
Get the AdrAckReq value.
std::list< Ptr< MacCommand > > GetCommands (void)
Return a list of pointers to all the MAC commands saved in this header.
uint16_t GetFCnt (void) const
Get the FCnt value.
uint8_t GetFOptsLen (void) const
Get the FOptsLen value.
bool GetFPending (void) const
Get the FPending value.
uint8_t GetFPort (void) const
Get the FPort value.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetMacCommand (void)
Return a pointer to a MacCommand, or 0 if the MacCommand does not exist in this header.
virtual uint32_t GetSerializedSize (void) const
Return the size required for serialization of this header.
virtual void Print (std::ostream &os) const
Print the header in a human-readable format.
virtual void Serialize (Buffer::Iterator start) const
Serialize the header.
void SetAck (bool ack)
Set the Ack bit.
void SetAddress (LoraDeviceAddress address)
Set the address.
void SetAdr (bool adr)
Set the Adr value.
void SetAdrAckReq (bool adrAckReq)
Set the AdrAckReq value.
void SetAsDownlink (void)
State that this is a downlink message.
void SetAsUplink (void)
State that this is an uplink message.
void SetFCnt (uint16_t fCnt)
Set the FCnt value.
void SetFPending (bool fPending)
Set the FPending value.
void SetFPort (uint8_t fPort)
Set the FPort value.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
bool m_ack
LoraDeviceAddress m_address
bool m_adr
bool m_adrAckReq
uint16_t m_fCnt
Buffer m_fOpts
uint8_t m_fOptsLen
bool m_fPending
uint8_t m_fPort
bool m_isUplink
std::list< Ptr< MacCommand > > m_macCommands
List containing all the MacCommand instances that are contained in this LoraFrameHeader.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class represents the Frame header (FHDR) used in a LoraWAN network.
Although the specification divides the FHDR from the FPort field, this implementation considers them as a unique entity (i.e., FPort is treated as if it were a part of FHDR).
Remarks
Prior to using it, this class needs to be informed of whether the header is for an uplink or downlink message. This is necessary due to the fact that UL and DL messages have subtly different structure and, hence, serialization and deserialization schemes.
Definition at line 43 of file lora-frame-header.h.
Constructor & Destructor Documentation
LoraFrameHeader()
ns3::lorawan::LoraFrameHeader::LoraFrameHeader ()
Definition at line 31 of file lora-frame-header.cc.
~LoraFrameHeader()
ns3::lorawan::LoraFrameHeader::~LoraFrameHeader ()
Definition at line 43 of file lora-frame-header.cc.
Member Function Documentation
AddCommand()
void ns3::lorawan::LoraFrameHeader::AddCommand (Ptr< MacCommand > macCommand)
Add a predefined command to the list.
Definition at line 591 of file lora-frame-header.cc.
References m_fOptsLen, m_macCommands, and NS_LOG_FUNCTION.
Referenced by ns3::lorawan::EndDeviceStatus::AddMACCommand(), and ns3::lorawan::EndDeviceLorawanMac::ApplyNecessaryOptions().
AddDevStatusReq()
void ns3::lorawan::LoraFrameHeader::AddDevStatusReq ()
Add a DevStatusReq command.
Definition at line 557 of file lora-frame-header.cc.
References m_fOptsLen, m_macCommands, and NS_LOG_FUNCTION.
AddDutyCycleAns()
void ns3::lorawan::LoraFrameHeader::AddDutyCycleAns (void)
Add a DutyCycleAns command.
Definition at line 515 of file lora-frame-header.cc.
References m_fOptsLen, m_macCommands, and NS_LOG_FUNCTION.
AddDutyCycleReq()
void ns3::lorawan::LoraFrameHeader::AddDutyCycleReq (uint8_t dutyCycle)
Add a DutyCycleReq command.
This command accepts an 8-bit integer as dutyCycle. The actual dutyCycle that will be implemented in the end-device will then be, in fraction form, 1/2^(dutyCycle).
Parameters
dutyCycle The dutyCycle in 8-bit form.
Definition at line 503 of file lora-frame-header.cc.
References m_fOptsLen, m_macCommands, and NS_LOG_FUNCTION.
AddLinkAdrAns()
void ns3::lorawan::LoraFrameHeader::AddLinkAdrAns (bool powerAck, bool dataRateAck, bool channelMaskAck)
Add a LinkAdrAns command.
Parameters
powerAck Whether the power can be set or not.
dataRateAck Whether the data rate can be set or not.
channelMaskAck Whether the channel mask is coherent with the device's current state or not.
Definition at line 492 of file lora-frame-header.cc.
References m_fOptsLen, m_macCommands, and NS_LOG_FUNCTION.
AddLinkAdrReq()
void ns3::lorawan::LoraFrameHeader::AddLinkAdrReq (uint8_t dataRate, uint8_t txPower, std::list< int > enabledChannels, int repetitions)
Add a LinkAdrReq command.
Parameters
dataRate The data rate at which the receiver should transmit.
txPower The power at which the receiver should transmit, encoded according to the LoRaWAN specification of the region.
enabledChannels A list containing the indices of channels enabled by this command.
repetitions The number of repetitions the receiver should send when transmitting.
Definition at line 469 of file lora-frame-header.cc.
References m_fOptsLen, m_macCommands, NS_ASSERT, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
AddLinkCheckAns()
void ns3::lorawan::LoraFrameHeader::AddLinkCheckAns (uint8_t margin, uint8_t gwCnt)
Add a LinkCheckAns command.
Parameters
margin The demodulation margin the LinkCheckReq packet was received with.
gwCnt The number of gateways the LinkCheckReq packet was received by.
Definition at line 458 of file lora-frame-header.cc.
References m_fOptsLen, m_macCommands, and NS_LOG_FUNCTION.
Referenced by HeaderTest::DoRun().
AddLinkCheckReq()
void ns3::lorawan::LoraFrameHeader::AddLinkCheckReq (void)
Add a LinkCheckReq command.
Definition at line 446 of file lora-frame-header.cc.
References m_fOptsLen, m_macCommands, NS_LOG_DEBUG, and NS_LOG_FUNCTION_NOARGS.
AddNewChannelReq()
void ns3::lorawan::LoraFrameHeader::AddNewChannelReq (uint8_t chIndex, double frequency, uint8_t minDataRate, uint8_t maxDataRate)
Add a NewChannelReq command.
Definition at line 569 of file lora-frame-header.cc.
References m_fOptsLen, m_macCommands, and NS_LOG_FUNCTION.
AddRxParamSetupAns()
void ns3::lorawan::LoraFrameHeader::AddRxParamSetupAns ()
Add a RxParamSetupAns command.
Definition at line 545 of file lora-frame-header.cc.
References m_fOptsLen, m_macCommands, and NS_LOG_FUNCTION.
AddRxParamSetupReq()
void ns3::lorawan::LoraFrameHeader::AddRxParamSetupReq (uint8_t rx1DrOffset, uint8_t rx2DataRate, double frequency)
Add a RxParamSetupReq command.
Parameters
rx1DrOffset The requested data rate offset for the first receive window.
rx2DataRate The requested data rate for the second receive window.
frequency The frequency at which to listen for the second receive window.
Definition at line 527 of file lora-frame-header.cc.
References m_fOptsLen, m_macCommands, NS_ASSERT, and NS_LOG_FUNCTION.
Deserialize()
uint32_t ns3::lorawan::LoraFrameHeader::Deserialize (Buffer::Iterator start) virtual
Deserialize the contents of the buffer into a LoraFrameHeader object.
Parameters
start A pointer to the buffer we need to deserialize.
Returns
The number of consumed bytes.
Implements ns3::Header.
Definition at line 109 of file lora-frame-header.cc.
References m_ack, m_address, m_adr, m_adrAckReq, m_fCnt, m_fOptsLen, m_fPending, m_fPort, m_isUplink, m_macCommands, NS_LOG_DEBUG, NS_LOG_ERROR, NS_LOG_FUNCTION_NOARGS, ns3::lorawan::LoraDeviceAddress::Print(), ns3::lorawan::LoraDeviceAddress::Set(), and visualizer.core::start().
Referenced by HeaderTest::DoRun().
GetAck()
bool ns3::lorawan::LoraFrameHeader::GetAck (void) const
Get the Ack bit value.
Returns
True if the ACK bit is set, false otherwise.
Definition at line 404 of file lora-frame-header.cc.
References m_ack.
Referenced by HeaderTest::DoRun(), and ns3::lorawan::EndDeviceLorawanMac::ParseCommands().
GetAddress()
LoraDeviceAddress ns3::lorawan::LoraFrameHeader::GetAddress (void) const
Get this header's device address value.
Returns
The address value stored in this header.
Definition at line 369 of file lora-frame-header.cc.
References m_address.
Referenced by HeaderTest::DoRun(), ns3::lorawan::NetworkStatus::GetEndDeviceStatus(), ns3::lorawan::NetworkScheduler::OnReceivedPacket(), ns3::lorawan::NetworkStatus::OnReceivedPacket(), ns3::lorawan::ConfirmedMessagesComponent::OnReceivedPacket(), and ns3::lorawan::ClassAEndDeviceLorawanMac::Receive().
GetAdr()
bool ns3::lorawan::LoraFrameHeader::GetAdr (void) const
Get the Adr value.
Returns
The Adr value.
Definition at line 381 of file lora-frame-header.cc.
References m_adr.
Referenced by ns3::lorawan::AdrComponent::BeforeSendingReply(), and HeaderTest::DoRun().
GetAdrAckReq()
bool ns3::lorawan::LoraFrameHeader::GetAdrAckReq (void) const
Get the AdrAckReq value.
Returns
The AdrAckReq value.
Definition at line 392 of file lora-frame-header.cc.
References m_adrAckReq.
GetCommands()
std::list< Ptr< MacCommand > > ns3::lorawan::LoraFrameHeader::GetCommands (void)
Return a list of pointers to all the MAC commands saved in this header.
Definition at line 583 of file lora-frame-header.cc.
References m_macCommands, and NS_LOG_FUNCTION_NOARGS.
Referenced by HeaderTest::DoRun(), and ns3::lorawan::EndDeviceLorawanMac::ParseCommands().
GetFCnt()
uint16_t ns3::lorawan::LoraFrameHeader::GetFCnt (void) const
Get the FCnt value.
Returns
The FCnt value.
Definition at line 440 of file lora-frame-header.cc.
References m_fCnt.
Referenced by HeaderTest::DoRun(), ns3::lorawan::EndDeviceStatus::GetCompleteReplyPacket(), ns3::lorawan::EndDeviceStatus::InsertReceivedPacket(), and ns3::lorawan::NetworkScheduler::OnReceivedPacket().
GetFOptsLen()
uint8_t ns3::lorawan::LoraFrameHeader::GetFOptsLen (void) const
Get the FOptsLen value.
Remarks
This value cannot be set since it's directly extracted from the number and kind of MAC commands.
Returns
The FOptsLen value.
Definition at line 421 of file lora-frame-header.cc.
References m_macCommands.
GetFPending()
bool ns3::lorawan::LoraFrameHeader::GetFPending (void) const
Get the FPending value.
Returns
The FPending value.
Definition at line 415 of file lora-frame-header.cc.
References m_fPending.
GetFPort()
uint8_t ns3::lorawan::LoraFrameHeader::GetFPort (void) const
Get the FPort value.
Returns
The FPort value.
Definition at line 357 of file lora-frame-header.cc.
References m_fPort.
GetInstanceTypeId()
TypeId ns3::lorawan::LoraFrameHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 58 of file lora-frame-header.cc.
References GetTypeId().
GetMacCommand()
template<typename T > Ptr< T > ns3::lorawan::LoraFrameHeader::GetMacCommand (void) inline
Return a pointer to a MacCommand, or 0 if the MacCommand does not exist in this header.
Definition at line 325 of file lora-frame-header.h.
References m_macCommands.
Referenced by ns3::lorawan::LinkCheckComponent::BeforeSendingReply().
GetSerializedSize()
uint32_t ns3::lorawan::LoraFrameHeader::GetSerializedSize (void) const virtual
Return the size required for serialization of this header.
Returns
The serialized size in bytes
Implements ns3::Header.
Definition at line 64 of file lora-frame-header.cc.
References m_fOptsLen, NS_LOG_FUNCTION_NOARGS, and NS_LOG_INFO.
Referenced by ns3::lorawan::EndDeviceLorawanMac::DoSend().
GetTypeId()
TypeId ns3::lorawan::LoraFrameHeader::GetTypeId (void) static
Definition at line 48 of file lora-frame-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::lorawan::LoraFrameHeader::Print (std::ostream & os) const virtual
Print the header in a human-readable format.
Parameters
os The std::ostream on which to print the header.
Implements ns3::Header.
Definition at line 314 of file lora-frame-header.cc.
References m_ack, m_address, m_adr, m_adrAckReq, m_fCnt, m_fOptsLen, m_fPending, m_fPort, m_macCommands, NS_LOG_FUNCTION_NOARGS, and ns3::lorawan::LoraDeviceAddress::Print().
Serialize()
void ns3::lorawan::LoraFrameHeader::Serialize (Buffer::Iterator start) const virtual
Serialize the header.
See Page 15 of LoraWAN specification for a representation of fields.
Parameters
start A pointer to the buffer that will be filled with the serialization.
Implements ns3::Header.
Definition at line 78 of file lora-frame-header.cc.
References ns3::lorawan::LoraDeviceAddress::Get(), m_ack, m_address, m_adr, m_adrAckReq, m_fCnt, m_fOptsLen, m_fPending, m_fPort, m_macCommands, NS_LOG_DEBUG, NS_LOG_FUNCTION_NOARGS, and visualizer.core::start().
Referenced by HeaderTest::DoRun().
SetAck()
void ns3::lorawan::LoraFrameHeader::SetAck (bool ack)
Set the Ack bit.
Parameters
ack Whether or not to set the ACK bit.
Definition at line 398 of file lora-frame-header.cc.
References m_ack, and NS_LOG_FUNCTION.
Referenced by HeaderTest::DoRun().
SetAddress()
void ns3::lorawan::LoraFrameHeader::SetAddress (LoraDeviceAddress address)
Set the address.
Parameters
address The LoraDeviceAddress to set.
Definition at line 363 of file lora-frame-header.cc.
References first::address, and m_address.
Referenced by ns3::lorawan::EndDeviceLorawanMac::ApplyNecessaryOptions(), HeaderTest::DoRun(), and ns3::lorawan::EndDeviceStatus::GetCompleteReplyPacket().
SetAdr()
void ns3::lorawan::LoraFrameHeader::SetAdr (bool adr)
Set the Adr value.
Parameters
Adr The Adr to set.
Definition at line 375 of file lora-frame-header.cc.
References m_adr, and NS_LOG_FUNCTION.
Referenced by ns3::lorawan::EndDeviceLorawanMac::ApplyNecessaryOptions(), and HeaderTest::DoRun().
SetAdrAckReq()
void ns3::lorawan::LoraFrameHeader::SetAdrAckReq (bool adrAckReq)
Set the AdrAckReq value.
Parameters
adrAckReq The AdrAckReq to set.
Definition at line 387 of file lora-frame-header.cc.
References m_adrAckReq.
Referenced by ns3::lorawan::EndDeviceLorawanMac::ApplyNecessaryOptions().
SetAsDownlink()
void ns3::lorawan::LoraFrameHeader::SetAsDownlink (void)
State that this is a downlink message.
This method needs to be called at least once before any serialization or deserialization.
Definition at line 343 of file lora-frame-header.cc.
References m_isUplink, and NS_LOG_FUNCTION_NOARGS.
Referenced by HeaderTest::DoRun(), and ns3::lorawan::ClassAEndDeviceLorawanMac::Receive().
SetAsUplink()
void ns3::lorawan::LoraFrameHeader::SetAsUplink (void)
State that this is an uplink message.
This method needs to be called at least once before any serialization or deserialization.
Definition at line 335 of file lora-frame-header.cc.
References m_isUplink, and NS_LOG_FUNCTION_NOARGS.
Referenced by ns3::lorawan::EndDeviceLorawanMac::ApplyNecessaryOptions(), ns3::lorawan::AdrComponent::BeforeSendingReply(), ns3::lorawan::LinkCheckComponent::BeforeSendingReply(), ns3::lorawan::EndDeviceStatus::GetCompleteReplyPacket(), ns3::lorawan::EndDeviceStatus::InsertReceivedPacket(), ns3::lorawan::NetworkScheduler::OnReceivedPacket(), ns3::lorawan::NetworkStatus::OnReceivedPacket(), and ns3::lorawan::ConfirmedMessagesComponent::OnReceivedPacket().
SetFCnt()
void ns3::lorawan::LoraFrameHeader::SetFCnt (uint16_t fCnt)
Set the FCnt value.
Parameters
FCnt The FCnt to set.
Definition at line 434 of file lora-frame-header.cc.
References m_fCnt.
Referenced by ns3::lorawan::EndDeviceLorawanMac::ApplyNecessaryOptions(), HeaderTest::DoRun(), and ns3::lorawan::EndDeviceStatus::GetCompleteReplyPacket().
SetFPending()
void ns3::lorawan::LoraFrameHeader::SetFPending (bool fPending)
Set the FPending value.
Parameters
fPending The FPending to set.
Definition at line 410 of file lora-frame-header.cc.
References m_fPending.
SetFPort()
void ns3::lorawan::LoraFrameHeader::SetFPort (uint8_t fPort)
Set the FPort value.
Parameters
fPort The FPort to set.
Definition at line 351 of file lora-frame-header.cc.
References m_fPort.
Referenced by ns3::lorawan::EndDeviceLorawanMac::ApplyNecessaryOptions().
Member Data Documentation
m_ack
bool ns3::lorawan::LoraFrameHeader::m_ack private
Definition at line 305 of file lora-frame-header.h.
Referenced by Deserialize(), GetAck(), Print(), Serialize(), and SetAck().
m_address
LoraDeviceAddress ns3::lorawan::LoraFrameHeader::m_address private
Definition at line 301 of file lora-frame-header.h.
Referenced by Deserialize(), GetAddress(), Print(), Serialize(), and SetAddress().
m_adr
bool ns3::lorawan::LoraFrameHeader::m_adr private
Definition at line 303 of file lora-frame-header.h.
Referenced by Deserialize(), GetAdr(), Print(), Serialize(), and SetAdr().
m_adrAckReq
bool ns3::lorawan::LoraFrameHeader::m_adrAckReq private
Definition at line 304 of file lora-frame-header.h.
Referenced by Deserialize(), GetAdrAckReq(), Print(), Serialize(), and SetAdrAckReq().
m_fCnt
uint16_t ns3::lorawan::LoraFrameHeader::m_fCnt private
Definition at line 309 of file lora-frame-header.h.
Referenced by Deserialize(), GetFCnt(), Print(), Serialize(), and SetFCnt().
m_fOpts
Buffer ns3::lorawan::LoraFrameHeader::m_fOpts private
Definition at line 311 of file lora-frame-header.h.
m_fOptsLen
uint8_t ns3::lorawan::LoraFrameHeader::m_fOptsLen private
Definition at line 307 of file lora-frame-header.h.
Referenced by AddCommand(), AddDevStatusReq(), AddDutyCycleAns(), AddDutyCycleReq(), AddLinkAdrAns(), AddLinkAdrReq(), AddLinkCheckAns(), AddLinkCheckReq(), AddNewChannelReq(), AddRxParamSetupAns(), AddRxParamSetupReq(), Deserialize(), GetSerializedSize(), Print(), and Serialize().
m_fPending
bool ns3::lorawan::LoraFrameHeader::m_fPending private
Definition at line 306 of file lora-frame-header.h.
Referenced by Deserialize(), GetFPending(), Print(), Serialize(), and SetFPending().
m_fPort
uint8_t ns3::lorawan::LoraFrameHeader::m_fPort private
Definition at line 299 of file lora-frame-header.h.
Referenced by Deserialize(), GetFPort(), Print(), Serialize(), and SetFPort().
m_isUplink
bool ns3::lorawan::LoraFrameHeader::m_isUplink private
Definition at line 319 of file lora-frame-header.h.
Referenced by Deserialize(), SetAsDownlink(), and SetAsUplink().
m_macCommands
std::list< Ptr< MacCommand> > ns3::lorawan::LoraFrameHeader::m_macCommands private
List containing all the MacCommand instances that are contained in this LoraFrameHeader.
Definition at line 317 of file lora-frame-header.h.
Referenced by AddCommand(), AddDevStatusReq(), AddDutyCycleAns(), AddDutyCycleReq(), AddLinkAdrAns(), AddLinkAdrReq(), AddLinkCheckAns(), AddLinkCheckReq(), AddNewChannelReq(), AddRxParamSetupAns(), AddRxParamSetupReq(), Deserialize(), GetCommands(), GetFOptsLen(), GetMacCommand(), Print(), and Serialize().
The documentation for this class was generated from the following files:
src/lorawan/model/lora-frame-header.h
src/lorawan/model/lora-frame-header.cc