ns-3: ns3::dot11s::IePeerManagement Class Reference
ns3::dot11s::IePeerManagement Class Reference
according to IEEE 802.11 - 2012
#include "ie-dot11s-peer-management.h"
Public Types
enum Subtype { PEER_OPEN = 1, PEER_CONFIRM = 2, PEER_CLOSE = 3 }
Subtype enumeration.
Public Member Functions
IePeerManagement ()
virtual uint8_t DeserializeInformationField (Buffer::Iterator i, uint8_t length)
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
virtual WifiInformationElementId ElementId () const
virtual uint8_t GetInformationFieldSize (void) const
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
uint16_t GetLocalLinkId () const
Get local link ID function.
uint16_t GetPeerLinkId () const
Get peer link ID function.
PmpReasonCode GetReasonCode () const
Get reason code function.
uint8_t GetSubtype () const
Get subtype function.
virtual void Print (std::ostream &os) const
Generate human-readable form of IE.
virtual void SerializeInformationField (Buffer::Iterator i) const
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
void SetPeerClose (uint16_t localLinkID, uint16_t peerLinkId, PmpReasonCode reasonCode)
Set peer close function.
void SetPeerConfirm (uint16_t localLinkID, uint16_t peerLinkId)
Set peer confirm function.
void SetPeerOpen (uint16_t localLinkId)
Set peer open function.
bool SubtypeIsClose () const
Subtype is close function.
bool SubtypeIsConfirm () const
Subtype is confirm function.
bool SubtypeIsOpen () const
Subtype is open function.
Public Member Functions inherited from ns3::WifiInformationElement
virtual ~WifiInformationElement ()
Buffer::Iterator Deserialize (Buffer::Iterator i)
Deserialize entire IE, which must be present.
Buffer::Iterator DeserializeIfPresent (Buffer::Iterator i)
Deserialize entire IE if it is present.
virtual WifiInformationElementId ElementIdExt () const
uint16_t GetSerializedSize () const
Get the size of the serialized IE including Element ID and length fields.
virtual bool operator== (WifiInformationElement const &a) const
Compare two IEs for equality by ID & Length, and then through memcmp of serialised version.
Buffer::Iterator Serialize (Buffer::Iterator i) const
Serialize entire IE including Element ID and length fields.
Public Member Functions inherited from ns3::SimpleRefCount< WifiInformationElement >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
uint8_t m_length
length
uint16_t m_localLinkId
local link ID
uint16_t m_peerLinkId
Present within confirm and may be present in close.
PmpReasonCode m_reasonCode
Present only within close frame.
uint8_t m_subtype
subtype
Friends
bool operator== (const IePeerManagement &a, const IePeerManagement &b)
equality operator
Detailed Description
according to IEEE 802.11 - 2012
Definition at line 50 of file ie-dot11s-peer-management.h.
Member Enumeration Documentation
Subtype
enum ns3::dot11s::IePeerManagement::Subtype
Subtype enumeration.
Enumerator
PEER_OPEN
PEER_CONFIRM
PEER_CLOSE
Definition at line 55 of file ie-dot11s-peer-management.h.
Constructor & Destructor Documentation
IePeerManagement()
ns3::dot11s::IePeerManagement::IePeerManagement ()
Definition at line 29 of file ie-dot11s-peer-management.cc.
Member Function Documentation
DeserializeInformationField()
uint8_t ns3::dot11s::IePeerManagement::DeserializeInformationField (Buffer::Iterator start, uint8_t length) virtual
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
length
Returns
the number of bytes read
Implements ns3::WifiInformationElement.
Definition at line 123 of file ie-dot11s-peer-management.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_length, m_localLinkId, m_peerLinkId, m_reasonCode, m_subtype, NS_ASSERT, PEER_CLOSE, PEER_CONFIRM, PEER_OPEN, ns3::Buffer::Iterator::ReadLsbtohU16(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
ElementId()
WifiInformationElementId ns3::dot11s::IePeerManagement::ElementId () const virtual
Returns
Own unique Element ID
Implements ns3::WifiInformationElement.
Definition at line 34 of file ie-dot11s-peer-management.cc.
References IE_MESH_PEERING_MANAGEMENT.
GetInformationFieldSize()
uint8_t ns3::dot11s::IePeerManagement::GetInformationFieldSize (void) const virtual
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
This is the value that will appear in the second octet of the entire IE - the length field)
Returns
the length of serialized information
Implements ns3::WifiInformationElement.
Definition at line 83 of file ie-dot11s-peer-management.cc.
References m_length.
GetLocalLinkId()
uint16_t ns3::dot11s::IePeerManagement::GetLocalLinkId () const
Get local link ID function.
Returns
the local link id
Definition at line 71 of file ie-dot11s-peer-management.cc.
References m_localLinkId.
Referenced by ns3::dot11s::PeerManagementProtocol::ReceivePeerLinkFrame().
GetPeerLinkId()
uint16_t ns3::dot11s::IePeerManagement::GetPeerLinkId () const
Get peer link ID function.
Returns
the peer link ID
Definition at line 77 of file ie-dot11s-peer-management.cc.
References m_peerLinkId.
Referenced by ns3::dot11s::PeerManagementProtocol::ReceivePeerLinkFrame().
GetReasonCode()
PmpReasonCode ns3::dot11s::IePeerManagement::GetReasonCode () const
Get reason code function.
Returns
the reason code
Definition at line 65 of file ie-dot11s-peer-management.cc.
References m_reasonCode.
Referenced by ns3::dot11s::PeerManagementProtocol::ReceivePeerLinkFrame().
GetSubtype()
uint8_t ns3::dot11s::IePeerManagement::GetSubtype () const
Get subtype function.
Returns
the subtype
Definition at line 88 of file ie-dot11s-peer-management.cc.
References m_subtype.
Print()
void ns3::dot11s::IePeerManagement::Print (std::ostream & os) const virtual
Generate human-readable form of IE.
Parameters
os output stream
Reimplemented from ns3::WifiInformationElement.
Definition at line 152 of file ie-dot11s-peer-management.cc.
References m_length, m_localLinkId, m_peerLinkId, m_reasonCode, and m_subtype.
Referenced by ns3::dot11s::operator<<().
SerializeInformationField()
void ns3::dot11s::IePeerManagement::SerializeInformationField (Buffer::Iterator start) const virtual
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
Implements ns3::WifiInformationElement.
Definition at line 109 of file ie-dot11s-peer-management.cc.
References m_length, m_localLinkId, m_peerLinkId, m_reasonCode, m_subtype, ns3::Buffer::Iterator::WriteHtolsbU16(), and ns3::Buffer::Iterator::WriteU8().
SetPeerClose()
void ns3::dot11s::IePeerManagement::SetPeerClose (uint16_t localLinkID, uint16_t peerLinkId, PmpReasonCode reasonCode)
Set peer close function.
Parameters
localLinkID the local link id
peerLinkId the peer link id
reasonCode the reason code
Definition at line 46 of file ie-dot11s-peer-management.cc.
References m_length, m_localLinkId, m_peerLinkId, m_reasonCode, m_subtype, and PEER_CLOSE.
Referenced by MeshInformationElementVectorBist::DoRun(), and ns3::dot11s::PeerLink::SendPeerLinkClose().
SetPeerConfirm()
void ns3::dot11s::IePeerManagement::SetPeerConfirm (uint16_t localLinkID, uint16_t peerLinkId)
Set peer confirm function.
Parameters
localLinkID the local link id
peerLinkId the peer link id
Definition at line 56 of file ie-dot11s-peer-management.cc.
References m_length, m_localLinkId, m_peerLinkId, m_subtype, and PEER_CONFIRM.
Referenced by MeshInformationElementVectorBist::DoRun(), and ns3::dot11s::PeerLink::SendPeerLinkConfirm().
SetPeerOpen()
void ns3::dot11s::IePeerManagement::SetPeerOpen (uint16_t localLinkId)
Set peer open function.
Parameters
localLinkId
Definition at line 39 of file ie-dot11s-peer-management.cc.
References m_length, m_localLinkId, m_subtype, and PEER_OPEN.
Referenced by MeshInformationElementVectorBist::DoRun(), and ns3::dot11s::PeerLink::SendPeerLinkOpen().
SubtypeIsClose()
bool ns3::dot11s::IePeerManagement::SubtypeIsClose () const
Subtype is close function.
Returns
true if closed
Definition at line 98 of file ie-dot11s-peer-management.cc.
References m_subtype, and PEER_CLOSE.
Referenced by ns3::dot11s::PeerManagementProtocol::ReceivePeerLinkFrame(), and ns3::dot11s::PeerManagementProtocolMac::SendPeerLinkManagementFrame().
SubtypeIsConfirm()
bool ns3::dot11s::IePeerManagement::SubtypeIsConfirm () const
Subtype is confirm function.
Returns
true if the subtype is confirm
Definition at line 103 of file ie-dot11s-peer-management.cc.
References m_subtype, and PEER_CONFIRM.
Referenced by ns3::dot11s::PeerManagementProtocol::ReceivePeerLinkFrame(), and ns3::dot11s::PeerManagementProtocolMac::SendPeerLinkManagementFrame().
SubtypeIsOpen()
bool ns3::dot11s::IePeerManagement::SubtypeIsOpen () const
Subtype is open function.
Returns
true if open
Definition at line 93 of file ie-dot11s-peer-management.cc.
References m_subtype, and PEER_OPEN.
Referenced by ns3::dot11s::PeerManagementProtocol::ReceivePeerLinkFrame(), and ns3::dot11s::PeerManagementProtocolMac::SendPeerLinkManagementFrame().
Friends And Related Function Documentation
operator==
bool operator== (const IePeerManagement & a, const IePeerManagement & b) friend
equality operator
Parameters
a lhs
b rhs
Returns
true if equal
Definition at line 162 of file ie-dot11s-peer-management.cc.
Member Data Documentation
m_length
uint8_t ns3::dot11s::IePeerManagement::m_length private
length
Definition at line 124 of file ie-dot11s-peer-management.h.
Referenced by DeserializeInformationField(), GetInformationFieldSize(), ns3::dot11s::operator==(), Print(), SerializeInformationField(), SetPeerClose(), SetPeerConfirm(), and SetPeerOpen().
m_localLinkId
uint16_t ns3::dot11s::IePeerManagement::m_localLinkId private
local link ID
Definition at line 126 of file ie-dot11s-peer-management.h.
Referenced by DeserializeInformationField(), GetLocalLinkId(), ns3::dot11s::operator==(), Print(), SerializeInformationField(), SetPeerClose(), SetPeerConfirm(), and SetPeerOpen().
m_peerLinkId
uint16_t ns3::dot11s::IePeerManagement::m_peerLinkId private
Present within confirm and may be present in close.
Definition at line 130 of file ie-dot11s-peer-management.h.
Referenced by DeserializeInformationField(), GetPeerLinkId(), ns3::dot11s::operator==(), Print(), SerializeInformationField(), SetPeerClose(), and SetPeerConfirm().
m_reasonCode
PmpReasonCode ns3::dot11s::IePeerManagement::m_reasonCode private
Present only within close frame.
Definition at line 134 of file ie-dot11s-peer-management.h.
Referenced by DeserializeInformationField(), GetReasonCode(), ns3::dot11s::operator==(), Print(), SerializeInformationField(), and SetPeerClose().
m_subtype
uint8_t ns3::dot11s::IePeerManagement::m_subtype private
subtype
Definition at line 125 of file ie-dot11s-peer-management.h.
Referenced by DeserializeInformationField(), GetSubtype(), ns3::dot11s::operator==(), Print(), SerializeInformationField(), SetPeerClose(), SetPeerConfirm(), SetPeerOpen(), SubtypeIsClose(), SubtypeIsConfirm(), and SubtypeIsOpen().
The documentation for this class was generated from the following files:
src/mesh/model/dot11s/ie-dot11s-peer-management.h
src/mesh/model/dot11s/ie-dot11s-peer-management.cc