ns-3: ns3::Gnuplot3dDataset Class Reference
ns3::Gnuplot3dDataset Class Reference
Statistics » Gnuplot
Class to represent a 3D points plot. Set the line or points style using SetStyle() and set points using Add().
#include "gnuplot.h"
Classes
struct Data3d
struct Point
A point in a 3D plot.
Public Member Functions
Gnuplot3dDataset (const std::string &title="Untitled")
void Add (double x, double y, double z)
void AddEmptyLine ()
Add an empty line in the data output sequence.
void SetStyle (const std::string &style)
Public Member Functions inherited from ns3::GnuplotDataset
GnuplotDataset (const GnuplotDataset &original)
Reference-counting copy constructor.
~GnuplotDataset ()
Reference-counting destructor.
GnuplotDataset & operator= (const GnuplotDataset &original)
Reference-counting assignment operator.
void SetExtra (const std::string &extra)
Add extra formatting parameters to this dataset.
void SetTitle (const std::string &title)
Change line title.
Static Public Member Functions
static void SetDefaultStyle (const std::string &style)
Change default style for all newly created objects.
Static Public Member Functions inherited from ns3::GnuplotDataset
static void SetDefaultExtra (const std::string &extra)
Change extra formatting style parameters for newly created objects.
Private Types
typedef std::vector< struct Point > PointSet
The set of points in the dataset.
Static Private Attributes
static std::string m_defaultStyle = ""
default plot style
Additional Inherited Members
Protected Member Functions inherited from ns3::GnuplotDataset
GnuplotDataset (struct Data *data)
Called by constructors of derived classes.
Protected Attributes inherited from ns3::GnuplotDataset
struct Data * m_data
Reference counted data object.
Static Protected Attributes inherited from ns3::GnuplotDataset
static std::string m_defaultExtra = ""
Extra gnuplot parameters set on every newly created dataset.
Detailed Description
Class to represent a 3D points plot. Set the line or points style using SetStyle() and set points using Add().
Definition at line 272 of file gnuplot.h.
Member Typedef Documentation
PointSet
typedef std::vector<struct Point> ns3::Gnuplot3dDataset::PointSet private
The set of points in the dataset.
Definition at line 322 of file gnuplot.h.
Constructor & Destructor Documentation
Gnuplot3dDataset()
ns3::Gnuplot3dDataset::Gnuplot3dDataset (const std::string & title = "Untitled")
Parameters
title the title to be associated to this dataset.
Create an empty dataset. Usually, the dataset's title is displayed in the legend box.
Definition at line 576 of file gnuplot.cc.
Member Function Documentation
Add()
void ns3::Gnuplot3dDataset::Add (double x, double y, double z)
Parameters
x x coord to new data point
y y coord to new data point
z z coord to new data point
Use this method to add a new 3D point
Definition at line 593 of file gnuplot.cc.
References data, ns3::GnuplotDataset::m_data, and sample-rng-plot::x.
Referenced by anonymous_namespace{gnuplot-example.cc}::Create3DPlotFile(), and TestProbabilistic().
AddEmptyLine()
void ns3::Gnuplot3dDataset::AddEmptyLine ()
Add an empty line in the data output sequence.
Empty lines in the plot data break continuous lines and do other things in the output.
Definition at line 604 of file gnuplot.cc.
References data, and ns3::GnuplotDataset::m_data.
Referenced by anonymous_namespace{gnuplot-example.cc}::Create3DPlotFile(), and TestProbabilistic().
SetDefaultStyle()
void ns3::Gnuplot3dDataset::SetDefaultStyle (const std::string & style) static
Change default style for all newly created objects.
Parameters
style the style of plotting to use for newly created datasets.
Definition at line 582 of file gnuplot.cc.
References m_defaultStyle.
SetStyle()
void ns3::Gnuplot3dDataset::SetStyle (const std::string & style)
Parameters
style the style of plotting to use for this dataset.
Definition at line 587 of file gnuplot.cc.
References ns3::GnuplotDataset::m_data.
Referenced by anonymous_namespace{gnuplot-example.cc}::Create3DPlotFile(), and TestProbabilistic().
Member Data Documentation
m_defaultStyle
std::string ns3::Gnuplot3dDataset::m_defaultStyle = "" static private
default plot style
Definition at line 324 of file gnuplot.h.
Referenced by SetDefaultStyle().
The documentation for this class was generated from the following files:
src/stats/model/gnuplot.h
src/stats/model/gnuplot.cc