ns-3: ns3::Icmpv6NA Class Reference
ns3::Icmpv6NA Class Reference
Internet » IPv6 classes and sub-modules » ICMPv6 protocol and associated headers.
ICMPv6 Neighbor Advertisement header.
#include "icmpv6-header.h"
Public Member Functions
Icmpv6NA ()
Constructor.
virtual ~Icmpv6NA ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
bool GetFlagO () const
Get the O flag.
bool GetFlagR () const
Get the R flag.
bool GetFlagS () const
Get the S flag.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
Ipv6Address GetIpv6Target () const
Get the IPv6 target field.
uint32_t GetReserved () const
Get the reserved field.
virtual uint32_t GetSerializedSize () const
Get the serialized size.
virtual void Print (std::ostream &os) const
Print information.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetFlagO (bool o)
Set the O flag.
void SetFlagR (bool r)
Set the R flag.
void SetFlagS (bool s)
Set the S flag.
void SetIpv6Target (Ipv6Address target)
Set the IPv6 target field.
void SetReserved (uint32_t reserved)
Set the reserved field.
Public Member Functions inherited from ns3::Icmpv6Header
Icmpv6Header ()
Constructor.
virtual ~Icmpv6Header ()
Destructor.
void CalculatePseudoHeaderChecksum (Ipv6Address src, Ipv6Address dst, uint16_t length, uint8_t protocol)
Calculate pseudo header checksum for IPv6.
uint16_t GetChecksum () const
Get the checksum.
uint8_t GetCode () const
Get the code field.
uint8_t GetType () const
Get the type field.
void SetChecksum (uint16_t checksum)
Set the checksum.
void SetCode (uint8_t code)
Set the code field.
void SetType (uint8_t type)
Set the type.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the UID of this class.
Static Public Member Functions inherited from ns3::Icmpv6Header
static TypeId GetTypeId ()
Get the UID of this class.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
bool m_flagO
The M flag.
bool m_flagR
The R flag.
bool m_flagS
The O flag.
uint32_t m_reserved
The reserved value.
Ipv6Address m_target
The IPv6 target address.
Additional Inherited Members
Public Types inherited from ns3::Icmpv6Header
enum ErrorDestinationUnreachable_e {
ICMPV6_NO_ROUTE = 0, ICMPV6_ADM_PROHIBITED, ICMPV6_NOT_NEIGHBOUR, ICMPV6_ADDR_UNREACHABLE,
ICMPV6_PORT_UNREACHABLE
}
ICMPv6 error code : Destination Unreachable.
enum ErrorParameterError_e { ICMPV6_MALFORMED_HEADER = 0, ICMPV6_UNKNOWN_NEXT_HEADER, ICMPV6_UNKNOWN_OPTION }
ICMPv6 error code : Parameter Error.
enum ErrorTimeExceeded_e { ICMPV6_HOPLIMIT = 0, ICMPV6_FRAGTIME }
ICMPv6 error code : Time Exceeded.
enum OptionType_e {
ICMPV6_OPT_LINK_LAYER_SOURCE = 1, ICMPV6_OPT_LINK_LAYER_TARGET, ICMPV6_OPT_PREFIX, ICMPV6_OPT_REDIRECTED,
ICMPV6_OPT_MTU
}
ICMPv6 Option type code.
enum Type_e {
ICMPV6_ERROR_DESTINATION_UNREACHABLE = 1, ICMPV6_ERROR_PACKET_TOO_BIG, ICMPV6_ERROR_TIME_EXCEEDED, ICMPV6_ERROR_PARAMETER_ERROR,
ICMPV6_ECHO_REQUEST = 128, ICMPV6_ECHO_REPLY, ICMPV6_SUBSCRIBE_REQUEST, ICMPV6_SUBSCRIBE_REPORT,
ICMPV6_SUBSCRIVE_END, ICMPV6_ND_ROUTER_SOLICITATION, ICMPV6_ND_ROUTER_ADVERTISEMENT, ICMPV6_ND_NEIGHBOR_SOLICITATION,
ICMPV6_ND_NEIGHBOR_ADVERTISEMENT, ICMPV6_ND_REDIRECTION, ICMPV6_ROUTER_RENUMBER, ICMPV6_INFORMATION_REQUEST,
ICMPV6_INFORMATION_RESPONSE, ICMPV6_INVERSE_ND_SOLICITATION, ICMPV6_INVERSE_ND_ADVERSTISEMENT, ICMPV6_MLDV2_SUBSCRIBE_REPORT,
ICMPV6_MOBILITY_HA_DISCOVER_REQUEST, ICMPV6_MOBILITY_HA_DISCOVER_RESPONSE, ICMPV6_MOBILITY_MOBILE_PREFIX_SOLICITATION, ICMPV6_SECURE_ND_CERTIFICATE_PATH_SOLICITATION,
ICMPV6_SECURE_ND_CERTIFICATE_PATH_ADVERTISEMENT, ICMPV6_EXPERIMENTAL_MOBILITY
}
ICMPv6 type code.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Icmpv6Header
bool m_calcChecksum
Checksum enable or not.
uint16_t m_checksum
The checksum.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
ICMPv6 Neighbor Advertisement header.
Definition at line 427 of file icmpv6-header.h.
Constructor & Destructor Documentation
Icmpv6NA()
ns3::Icmpv6NA::Icmpv6NA ()
Constructor.
Definition at line 317 of file icmpv6-header.cc.
References ns3::Icmpv6Header::ICMPV6_ND_NEIGHBOR_ADVERTISEMENT, ns3::Icmpv6Header::m_checksum, NS_LOG_FUNCTION, ns3::Icmpv6Header::SetCode(), SetFlagO(), SetFlagR(), SetFlagS(), SetReserved(), and ns3::Icmpv6Header::SetType().
~Icmpv6NA()
ns3::Icmpv6NA::~Icmpv6NA () virtual
Destructor.
Definition at line 329 of file icmpv6-header.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Deserialize()
uint32_t ns3::Icmpv6NA::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start start offset
Returns
length of packet
Reimplemented from ns3::Icmpv6Header.
Definition at line 447 of file icmpv6-header.cc.
References GetSerializedSize(), ns3::Icmpv6Header::m_checksum, m_flagO, m_flagR, m_flagS, m_reserved, m_target, NS_LOG_FUNCTION, ns3::Buffer::Iterator::Read(), ns3::Buffer::Iterator::ReadNtohU32(), ns3::Buffer::Iterator::ReadU16(), ns3::Buffer::Iterator::ReadU8(), ns3::Ipv6Address::Set(), ns3::Icmpv6Header::SetCode(), ns3::Icmpv6Header::SetType(), and visualizer.core::start().
GetFlagO()
bool ns3::Icmpv6NA::GetFlagO () const
Get the O flag.
Returns
O flag
Definition at line 376 of file icmpv6-header.cc.
References m_flagO, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::HandleNA().
GetFlagR()
bool ns3::Icmpv6NA::GetFlagR () const
Get the R flag.
Returns
R flag
Definition at line 352 of file icmpv6-header.cc.
References m_flagR, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::HandleNA().
GetFlagS()
bool ns3::Icmpv6NA::GetFlagS () const
Get the S flag.
Returns
S flag
Definition at line 364 of file icmpv6-header.cc.
References m_flagS, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::HandleNA().
GetInstanceTypeId()
TypeId ns3::Icmpv6NA::GetInstanceTypeId () const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::Icmpv6Header.
Definition at line 311 of file icmpv6-header.cc.
References GetTypeId(), and NS_LOG_FUNCTION.
GetIpv6Target()
Ipv6Address ns3::Icmpv6NA::GetIpv6Target () const
Get the IPv6 target field.
Returns
IPv6 address
Definition at line 346 of file icmpv6-header.cc.
References m_target, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::HandleNA().
GetReserved()
uint32_t ns3::Icmpv6NA::GetReserved () const
Get the reserved field.
Returns
reserved value
Definition at line 334 of file icmpv6-header.cc.
References m_reserved, and NS_LOG_FUNCTION.
GetSerializedSize()
uint32_t ns3::Icmpv6NA::GetSerializedSize () const virtual
Get the serialized size.
Returns
serialized size
Reimplemented from ns3::Icmpv6Header.
Definition at line 400 of file icmpv6-header.cc.
References NS_LOG_FUNCTION.
Referenced by Deserialize(), ns3::Icmpv6L4Protocol::ForgeNA(), and ns3::Icmpv6L4Protocol::SendNA().
GetTypeId()
TypeId ns3::Icmpv6NA::GetTypeId () static
Get the UID of this class.
Returns
UID
Definition at line 301 of file icmpv6-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::Icmpv6NA::Print (std::ostream & os) const virtual
Print information.
Parameters
os output stream
Reimplemented from ns3::Icmpv6Header.
Definition at line 394 of file icmpv6-header.cc.
References ns3::Icmpv6Header::GetChecksum(), ns3::Icmpv6Header::GetCode(), ns3::Icmpv6Header::GetType(), and NS_LOG_FUNCTION.
Serialize()
void ns3::Icmpv6NA::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start start offset
Reimplemented from ns3::Icmpv6Header.
Definition at line 406 of file icmpv6-header.cc.
References ns3::Buffer::Iterator::CalculateIpChecksum(), ns3::Icmpv6Header::GetChecksum(), ns3::Icmpv6Header::GetCode(), ns3::Buffer::Iterator::GetSize(), ns3::Icmpv6Header::GetType(), ns3::Icmpv6Header::m_calcChecksum, m_flagO, m_flagR, m_flagS, m_reserved, m_target, ns3::Buffer::Iterator::Next(), NS_LOG_FUNCTION, ns3::Ipv6Address::Serialize(), visualizer.core::start(), ns3::Buffer::Iterator::Write(), ns3::Buffer::Iterator::WriteHtonU32(), ns3::Buffer::Iterator::WriteU16(), and ns3::Buffer::Iterator::WriteU8().
SetFlagO()
void ns3::Icmpv6NA::SetFlagO (bool o)
Set the O flag.
Parameters
o value
Definition at line 382 of file icmpv6-header.cc.
References m_flagO, and NS_LOG_FUNCTION.
Referenced by Icmpv6NA(), ns3::Icmpv6L4Protocol::ForgeNA(), and ns3::Icmpv6L4Protocol::SendNA().
SetFlagR()
void ns3::Icmpv6NA::SetFlagR (bool r)
Set the R flag.
Parameters
r value
Definition at line 358 of file icmpv6-header.cc.
References m_flagR, and NS_LOG_FUNCTION.
Referenced by Icmpv6NA(), ns3::Icmpv6L4Protocol::ForgeNA(), and ns3::Icmpv6L4Protocol::SendNA().
SetFlagS()
void ns3::Icmpv6NA::SetFlagS (bool s)
Set the S flag.
Parameters
s value
Definition at line 370 of file icmpv6-header.cc.
References m_flagS, and NS_LOG_FUNCTION.
Referenced by Icmpv6NA(), ns3::Icmpv6L4Protocol::ForgeNA(), and ns3::Icmpv6L4Protocol::SendNA().
SetIpv6Target()
void ns3::Icmpv6NA::SetIpv6Target (Ipv6Address target)
Set the IPv6 target field.
Parameters
target IPv6 address
Definition at line 388 of file icmpv6-header.cc.
References m_target, and NS_LOG_FUNCTION.
Referenced by ns3::Icmpv6L4Protocol::ForgeNA(), and ns3::Icmpv6L4Protocol::SendNA().
SetReserved()
void ns3::Icmpv6NA::SetReserved (uint32_t reserved)
Set the reserved field.
Parameters
reserved the reserved value
Definition at line 340 of file icmpv6-header.cc.
References m_reserved, and NS_LOG_FUNCTION.
Referenced by Icmpv6NA().
Member Data Documentation
m_flagO
bool ns3::Icmpv6NA::m_flagO private
The M flag.
Definition at line 551 of file icmpv6-header.h.
Referenced by Deserialize(), GetFlagO(), Serialize(), and SetFlagO().
m_flagR
bool ns3::Icmpv6NA::m_flagR private
The R flag.
Definition at line 541 of file icmpv6-header.h.
Referenced by Deserialize(), GetFlagR(), Serialize(), and SetFlagR().
m_flagS
bool ns3::Icmpv6NA::m_flagS private
The O flag.
Definition at line 546 of file icmpv6-header.h.
Referenced by Deserialize(), GetFlagS(), Serialize(), and SetFlagS().
m_reserved
uint32_t ns3::Icmpv6NA::m_reserved private
The reserved value.
Definition at line 556 of file icmpv6-header.h.
Referenced by Deserialize(), GetReserved(), Serialize(), and SetReserved().
m_target
Ipv6Address ns3::Icmpv6NA::m_target private
The IPv6 target address.
Definition at line 561 of file icmpv6-header.h.
Referenced by Deserialize(), GetIpv6Target(), Serialize(), and SetIpv6Target().
The documentation for this class was generated from the following files:
src/internet/model/icmpv6-header.h
src/internet/model/icmpv6-header.cc