ns-3: ns3::Ipv6ExtensionESPHeader Class Reference
ns3::Ipv6ExtensionESPHeader Class Reference
Internet » IPv6 classes and sub-modules » IPV6 Header extension system.
Header of IPv6 Extension ESP.
#include "ipv6-extension-header.h"
Public Member Functions
Ipv6ExtensionESPHeader ()
Constructor.
virtual ~Ipv6ExtensionESPHeader ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
virtual uint32_t GetSerializedSize () const
Get the serialized size of the packet.
virtual void Print (std::ostream &os) const
Print some information about the packet.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
Public Member Functions inherited from ns3::Ipv6ExtensionHeader
Ipv6ExtensionHeader ()
Constructor.
virtual ~Ipv6ExtensionHeader ()
Destructor.
uint16_t GetLength () const
Get the length of the extension.
uint8_t GetNextHeader () const
Get the next header.
void SetLength (uint16_t length)
brief Set the length of the extension.
void SetNextHeader (uint8_t nextHeader)
Set the "Next header" field.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Ipv6ExtensionHeader
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Ipv6ExtensionHeader
uint8_t m_length
The "length" field.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Header of IPv6 Extension ESP.
Definition at line 633 of file ipv6-extension-header.h.
Constructor & Destructor Documentation
Ipv6ExtensionESPHeader()
ns3::Ipv6ExtensionESPHeader::Ipv6ExtensionESPHeader ()
Constructor.
Definition at line 623 of file ipv6-extension-header.cc.
~Ipv6ExtensionESPHeader()
ns3::Ipv6ExtensionESPHeader::~Ipv6ExtensionESPHeader () virtual
Destructor.
Definition at line 627 of file ipv6-extension-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::Ipv6ExtensionESPHeader::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start Buffer iterator
Returns
size of the packet
Todo:
Reimplemented from ns3::Ipv6ExtensionHeader.
Definition at line 647 of file ipv6-extension-header.cc.
GetInstanceTypeId()
TypeId ns3::Ipv6ExtensionESPHeader::GetInstanceTypeId () const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::Ipv6ExtensionHeader.
Definition at line 618 of file ipv6-extension-header.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::Ipv6ExtensionESPHeader::GetSerializedSize () const virtual
Get the serialized size of the packet.
Returns
size
Todo:
Reimplemented from ns3::Ipv6ExtensionHeader.
Definition at line 636 of file ipv6-extension-header.cc.
GetTypeId()
TypeId ns3::Ipv6ExtensionESPHeader::GetTypeId () static
Get the type identificator.
Returns
type identificator
Definition at line 608 of file ipv6-extension-header.cc.
References ns3::TypeId::AddConstructor().
Referenced by GetInstanceTypeId().
Print()
void ns3::Ipv6ExtensionESPHeader::Print (std::ostream & os) const virtual
Print some information about the packet.
Parameters
os output stream
Returns
info about this packet
Todo:
Reimplemented from ns3::Ipv6ExtensionHeader.
Definition at line 631 of file ipv6-extension-header.cc.
Serialize()
void ns3::Ipv6ExtensionESPHeader::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start Buffer iterator
Todo:
Reimplemented from ns3::Ipv6ExtensionHeader.
Definition at line 642 of file ipv6-extension-header.cc.
The documentation for this class was generated from the following files:
src/internet/model/ipv6-extension-header.h
src/internet/model/ipv6-extension-header.cc