ns-3: ns3::Ipv6PmtuCache Class Reference
ns3::Ipv6PmtuCache Class Reference
Internet » IPv6 classes and sub-modules
This class implements the Path MTU cache, as defined by RFC 1981.
#include "ipv6-pmtu-cache.h"
Public Member Functions
Ipv6PmtuCache ()
Constructor.
~Ipv6PmtuCache ()
Destructor.
virtual void DoDispose ()
Dispose object.
uint32_t GetPmtu (Ipv6Address dst)
Gets the known Path MTU for the specific destination.
Time GetPmtuValidityTime () const
Gets the Path MTU validity time.
void SetPmtu (Ipv6Address dst, uint32_t pmtu)
Sets the Path MTU for the specific destination.
bool SetPmtuValidityTime (Time validity)
Sets the Path MTU validity time (minimum is 5 minutes)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef std::map< Ipv6Address, EventId >::iterator pathMtuTimerIter
Container of the IPv6 PMTU data (Ipv6 destination address and expiration event).
Private Member Functions
void ClearPmtu (Ipv6Address dst)
Clears the Path MTU for the specific destination.
Private Attributes
std::map< Ipv6Address, uint32_t > m_pathMtu
Path MTU table.
std::map< Ipv6Address, EventId > m_pathMtuTimer
Path MTU Expiration table.
Time m_validityTime
Path MTU entry validity time.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This class implements the Path MTU cache, as defined by RFC 1981.
The Path MTU is stored according to the destination address, and it is cleared upon expiration (default validity time is 10 minutes).
The "infinite lifetime" PMTU entry type is not implemented, since it is useful only in an very limited number of cases. See the RFC for further details.
Definition at line 47 of file ipv6-pmtu-cache.h.
Member Typedef Documentation
pathMtuTimerIter
typedef std::map<Ipv6Address, EventId>::iterator ns3::Ipv6PmtuCache::pathMtuTimerIter private
Container of the IPv6 PMTU data (Ipv6 destination address and expiration event).
Definition at line 115 of file ipv6-pmtu-cache.h.
Constructor & Destructor Documentation
Ipv6PmtuCache()
ns3::Ipv6PmtuCache::Ipv6PmtuCache ()
Constructor.
Definition at line 45 of file ipv6-pmtu-cache.cc.
~Ipv6PmtuCache()
ns3::Ipv6PmtuCache::~Ipv6PmtuCache ()
Destructor.
Definition at line 49 of file ipv6-pmtu-cache.cc.
Member Function Documentation
ClearPmtu()
void ns3::Ipv6PmtuCache::ClearPmtu (Ipv6Address dst) private
Clears the Path MTU for the specific destination.
Parameters
dst the destination
Definition at line 108 of file ipv6-pmtu-cache.cc.
References m_pathMtu, m_pathMtuTimer, and NS_LOG_FUNCTION.
Referenced by SetPmtu().
DoDispose()
void ns3::Ipv6PmtuCache::DoDispose () virtual
Dispose object.
Reimplemented from ns3::Object.
Definition at line 53 of file ipv6-pmtu-cache.cc.
References m_pathMtu, and m_pathMtuTimer.
GetPmtu()
uint32_t ns3::Ipv6PmtuCache::GetPmtu (Ipv6Address dst)
Gets the known Path MTU for the specific destination.
Parameters
dst the destination
Returns
the Path MTU (zero if unknown)
Definition at line 63 of file ipv6-pmtu-cache.cc.
References m_pathMtu, and NS_LOG_FUNCTION.
GetPmtuValidityTime()
Time ns3::Ipv6PmtuCache::GetPmtuValidityTime () const
Gets the Path MTU validity time.
Returns
the Path MTU validity time
Definition at line 88 of file ipv6-pmtu-cache.cc.
References m_validityTime, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::Ipv6PmtuCache::GetTypeId () static
Get the type ID.
Returns
type ID
Definition at line 31 of file ipv6-pmtu-cache.cc.
References m_validityTime, ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::Seconds(), and ns3::TypeId::SetParent().
SetPmtu()
void ns3::Ipv6PmtuCache::SetPmtu (Ipv6Address dst, uint32_t pmtu)
Sets the Path MTU for the specific destination.
Parameters
dst the destination
pmtu the Path MTU
Definition at line 74 of file ipv6-pmtu-cache.cc.
References ClearPmtu(), m_pathMtu, m_pathMtuTimer, m_validityTime, NS_LOG_FUNCTION, and ns3::Simulator::Schedule().
SetPmtuValidityTime()
bool ns3::Ipv6PmtuCache::SetPmtuValidityTime (Time validity)
Sets the Path MTU validity time (minimum is 5 minutes)
Parameters
validity the Path MTU validity time
Returns
true if the change was successful
Definition at line 94 of file ipv6-pmtu-cache.cc.
References m_validityTime, NS_LOG_FUNCTION, NS_LOG_LOGIC(), and ns3::Seconds().
Member Data Documentation
m_pathMtu
std::map<Ipv6Address, uint32_t> ns3::Ipv6PmtuCache::m_pathMtu private
Path MTU table.
Definition at line 110 of file ipv6-pmtu-cache.h.
Referenced by ClearPmtu(), DoDispose(), GetPmtu(), and SetPmtu().
m_pathMtuTimer
std::map<Ipv6Address, EventId> ns3::Ipv6PmtuCache::m_pathMtuTimer private
Path MTU Expiration table.
Definition at line 120 of file ipv6-pmtu-cache.h.
Referenced by ClearPmtu(), DoDispose(), and SetPmtu().
m_validityTime
Time ns3::Ipv6PmtuCache::m_validityTime private
Path MTU entry validity time.
Definition at line 125 of file ipv6-pmtu-cache.h.
Referenced by GetPmtuValidityTime(), GetTypeId(), SetPmtu(), and SetPmtuValidityTime().
The documentation for this class was generated from the following files:
src/internet/model/ipv6-pmtu-cache.h
src/internet/model/ipv6-pmtu-cache.cc