ns-3: ns3::LteControlMessage Class Reference
ns3::LteControlMessage Class Reference
LTE Models
#include "lte-control-messages.h"
Public Types
enum MessageType {
DL_DCI, UL_DCI, DL_CQI, UL_CQI,
BSR, DL_HARQ, RACH_PREAMBLE, RAR,
MIB, SIB1
}
The type of the message NOTE: The messages sent by UE are filtered by the LteEnbPhy::ReceiveLteControlMessageList in order to remove the ones that has been already handoff by the eNB for avoiding propagation of spurious messages.
Public Member Functions
LteControlMessage (void)
virtual ~LteControlMessage (void)
MessageType GetMessageType (void)
Get the type of the message.
void SetMessageType (MessageType type)
Set the type of the message.
Public Member Functions inherited from ns3::SimpleRefCount< LteControlMessage >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
MessageType m_type
message type
Detailed Description
The LteControlMessage provides a basic implementations for control messages (such as PDCCH allocation map, CQI feedbacks) that are exchanged among eNodeB and UEs.
Definition at line 43 of file lte-control-messages.h.
Member Enumeration Documentation
MessageType
enum ns3::LteControlMessage::MessageType
The type of the message NOTE: The messages sent by UE are filtered by the LteEnbPhy::ReceiveLteControlMessageList in order to remove the ones that has been already handoff by the eNB for avoiding propagation of spurious messages.
When new messaged have to been added, consider to update the switch statement implementing the filtering.
Enumerator
DL_DCI
UL_DCI
DL_CQI
UL_CQI
BSR
DL_HARQ
RACH_PREAMBLE
RAR
MIB
SIB1
Definition at line 54 of file lte-control-messages.h.
Constructor & Destructor Documentation
LteControlMessage()
ns3::LteControlMessage::LteControlMessage (void)
Definition at line 33 of file lte-control-messages.cc.
~LteControlMessage()
ns3::LteControlMessage::~LteControlMessage (void) virtual
Definition at line 38 of file lte-control-messages.cc.
Member Function Documentation
GetMessageType()
LteControlMessage::MessageType ns3::LteControlMessage::GetMessageType (void)
Get the type of the message.
Returns
the type of the message
Definition at line 51 of file lte-control-messages.cc.
References m_type.
SetMessageType()
void ns3::LteControlMessage::SetMessageType (LteControlMessage::MessageType type)
Set the type of the message.
Parameters
type the type of the message
Definition at line 44 of file lte-control-messages.cc.
References m_type.
Referenced by ns3::BsrLteControlMessage::BsrLteControlMessage(), ns3::DlCqiLteControlMessage::DlCqiLteControlMessage(), ns3::DlDciLteControlMessage::DlDciLteControlMessage(), ns3::DlHarqFeedbackLteControlMessage::DlHarqFeedbackLteControlMessage(), ns3::MibLteControlMessage::MibLteControlMessage(), ns3::RachPreambleLteControlMessage::RachPreambleLteControlMessage(), ns3::RarLteControlMessage::RarLteControlMessage(), ns3::Sib1LteControlMessage::Sib1LteControlMessage(), and ns3::UlDciLteControlMessage::UlDciLteControlMessage().
Member Data Documentation
m_type
MessageType ns3::LteControlMessage::m_type private
message type
Definition at line 81 of file lte-control-messages.h.
Referenced by GetMessageType(), and SetMessageType().
The documentation for this class was generated from the following files:
src/lte/model/lte-control-messages.h
src/lte/model/lte-control-messages.cc