ns-3: ns3::EpcS1apSapMme Class Reference
ns3::EpcS1apSapMme Class Reference abstract
LTE Models
#include "epc-s1ap-sap.h"
Classes
struct ErabSetupItem
E-RAB Setup Item IEs, see 3GPP TS 36.413 9.1.4.2.
struct ErabSwitchedInDownlinkItem
E-RABs Switched in Downlink Item IE, see 3GPP TS 36.413 9.1.5.8.
struct ErabToBeReleasedIndication
E-RAB Release Indication Item IEs, 3GPP TS 36.413 version 9.8.0 section 9.1.3.7.
Public Member Functions
virtual void ErabReleaseIndication (uint64_t mmeUeS1Id, uint16_t enbUeS1Id, std::list< ErabToBeReleasedIndication > erabToBeReleaseIndication)=0
As per 3GPP TS 23.401 Release 9 V9.5.0 Figure 5.4.4.2-1 eNB sends indication of Bearer Release to MME.
virtual void InitialContextSetupResponse (uint64_t mmeUeS1Id, uint16_t enbUeS1Id, std::list< ErabSetupItem > erabSetupList)=0
INITIAL CONTEXT SETUP RESPONSE message, see 3GPP TS 36.413 9.1.4.2.
virtual void InitialUeMessage (uint64_t mmeUeS1Id, uint16_t enbUeS1Id, uint64_t stmsi, uint16_t ecgi)=0
virtual void PathSwitchRequest (uint64_t enbUeS1Id, uint64_t mmeUeS1Id, uint16_t gci, std::list< ErabSwitchedInDownlinkItem > erabToBeSwitchedInDownlinkList)=0
PATH SWITCH REQUEST message, see 3GPP TS 36.413 9.1.5.8.
Public Member Functions inherited from ns3::EpcS1apSap
virtual ~EpcS1apSap ()
Detailed Description
MME side of the S1-AP Service Access Point (SAP), provides the MME methods to be called when an S1-AP message is received by the MME.
Definition at line 53 of file epc-s1ap-sap.h.
Member Function Documentation
ErabReleaseIndication()
virtual void ns3::EpcS1apSapMme::ErabReleaseIndication (uint64_t mmeUeS1Id, uint16_t enbUeS1Id, std::list< ErabToBeReleasedIndication > erabToBeReleaseIndication) pure virtual
As per 3GPP TS 23.401 Release 9 V9.5.0 Figure 5.4.4.2-1 eNB sends indication of Bearer Release to MME.
As per 3GPP TS version 9.8.0 section 8.2.3.2.2, the eNB initiates the procedure by sending an E-RAB RELEASE INDICATION message towards MME
Parameters
mmeUeS1Id in practice, we use the IMSI
enbUeS1Id in practice, we use the RNTI
erabToBeReleaseIndication,List of bearers to be deactivated
Implemented in ns3::MemberEpcS1apSapMme< C >.
Referenced by ns3::EpcEnbApplication::DoReleaseIndication().
InitialContextSetupResponse()
virtual void ns3::EpcS1apSapMme::InitialContextSetupResponse (uint64_t mmeUeS1Id, uint16_t enbUeS1Id, std::list< ErabSetupItem > erabSetupList) pure virtual
INITIAL CONTEXT SETUP RESPONSE message, see 3GPP TS 36.413 9.1.4.2.
Parameters
mmeUeS1Id in practice, we use the IMSI
enbUeS1Id in practice, we use the RNTI
erabSetupList
Implemented in ns3::MemberEpcS1apSapMme< C >.
InitialUeMessage()
virtual void ns3::EpcS1apSapMme::InitialUeMessage (uint64_t mmeUeS1Id, uint16_t enbUeS1Id, uint64_t stmsi, uint16_t ecgi) pure virtual
Parameters
mmeUeS1Id in practice, we use the IMSI
enbUeS1Id in practice, we use the RNTI
stmsi in practice, the imsi
ecgi in practice, the cell Id
Implemented in ns3::MemberEpcS1apSapMme< C >.
Referenced by ns3::EpcEnbApplication::DoInitialUeMessage().
PathSwitchRequest()
virtual void ns3::EpcS1apSapMme::PathSwitchRequest (uint64_t enbUeS1Id, uint64_t mmeUeS1Id, uint16_t gci, std::list< ErabSwitchedInDownlinkItem > erabToBeSwitchedInDownlinkList) pure virtual
PATH SWITCH REQUEST message, see 3GPP TS 36.413 9.1.5.8.
Parameters
enbUeS1Id in practice, we use the RNTI
mmeUeS1Id in practice, we use the IMSI
gci
erabToBeSwitchedInDownlinkList
Implemented in ns3::MemberEpcS1apSapMme< C >.
Referenced by ns3::EpcEnbApplication::DoPathSwitchRequest().
The documentation for this class was generated from the following file:
src/lte/model/epc-s1ap-sap.h