ns-3: ns3::AmpduSubframeHeader Class Reference
ns3::AmpduSubframeHeader Class Reference
Wifi Models
Headers for A-MPDU subframes.
#include "ampdu-subframe-header.h"
Public Member Functions
AmpduSubframeHeader ()
virtual ~AmpduSubframeHeader ()
uint32_t Deserialize (Buffer::Iterator start)
bool GetEof (void) const
Return the EOF field.
TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint16_t GetLength (void) const
Return the length field.
uint32_t GetSerializedSize (void) const
bool IsSignatureValid (void) const
Return whether the pattern stored in the delimiter signature field is correct, i.e.
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetEof (bool eof)
Set the EOF field.
void SetLength (uint16_t length)
Set the length field.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
bool m_eof
EOF field.
uint16_t m_length
length field in bytes
uint8_t m_signature
delimiter signature (should correspond to pattern 0x4E in order to be assumed valid)
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Headers for A-MPDU subframes.
Definition at line 32 of file ampdu-subframe-header.h.
Constructor & Destructor Documentation
AmpduSubframeHeader()
ns3::AmpduSubframeHeader::AmpduSubframeHeader ()
Definition at line 45 of file ampdu-subframe-header.cc.
~AmpduSubframeHeader()
ns3::AmpduSubframeHeader::~AmpduSubframeHeader () virtual
Definition at line 52 of file ampdu-subframe-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::AmpduSubframeHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 71 of file ampdu-subframe-header.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_eof, m_length, m_signature, ns3::Buffer::Iterator::ReadLsbtohU16(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetEof()
bool ns3::AmpduSubframeHeader::GetEof (void) const
Return the EOF field.
Returns
the EOF field
Definition at line 108 of file ampdu-subframe-header.cc.
References m_eof.
Referenced by ns3::WifiPhyHelper::GetRadiotapHeader().
GetInstanceTypeId()
TypeId ns3::AmpduSubframeHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 40 of file ampdu-subframe-header.cc.
References GetTypeId().
GetLength()
uint16_t ns3::AmpduSubframeHeader::GetLength (void) const
Return the length field.
Returns
the length field in bytes
Definition at line 102 of file ampdu-subframe-header.cc.
References m_length.
Referenced by ns3::WifiPhyHelper::GetRadiotapHeader().
GetSerializedSize()
uint32_t ns3::AmpduSubframeHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 57 of file ampdu-subframe-header.cc.
GetTypeId()
TypeId ns3::AmpduSubframeHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 29 of file ampdu-subframe-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
IsSignatureValid()
bool ns3::AmpduSubframeHeader::IsSignatureValid (void) const
Return whether the pattern stored in the delimiter signature field is correct, i.e.
corresponds to the unique pattern 0x4E.
Returns
true if the signature is valid, false otherwise
Definition at line 114 of file ampdu-subframe-header.cc.
References m_signature.
Print()
void ns3::AmpduSubframeHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 83 of file ampdu-subframe-header.cc.
References m_eof, m_length, and m_signature.
Serialize()
void ns3::AmpduSubframeHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 63 of file ampdu-subframe-header.cc.
References m_eof, m_length, m_signature, ns3::Buffer::Iterator::WriteHtolsbU16(), and ns3::Buffer::Iterator::WriteU8().
SetEof()
void ns3::AmpduSubframeHeader::SetEof (bool eof)
Set the EOF field.
Parameters
eof set EOF field if true
Definition at line 96 of file ampdu-subframe-header.cc.
References m_eof.
Referenced by ns3::MpduAggregator::GetAmpduSubframeHeader().
SetLength()
void ns3::AmpduSubframeHeader::SetLength (uint16_t length)
Set the length field.
Parameters
length in bytes
Definition at line 90 of file ampdu-subframe-header.cc.
References m_length.
Referenced by ns3::MpduAggregator::GetAmpduSubframeHeader().
Member Data Documentation
m_eof
bool ns3::AmpduSubframeHeader::m_eof private
EOF field.
Definition at line 85 of file ampdu-subframe-header.h.
Referenced by Deserialize(), GetEof(), Print(), Serialize(), and SetEof().
m_length
uint16_t ns3::AmpduSubframeHeader::m_length private
length field in bytes
Definition at line 84 of file ampdu-subframe-header.h.
Referenced by Deserialize(), GetLength(), Print(), Serialize(), and SetLength().
m_signature
uint8_t ns3::AmpduSubframeHeader::m_signature private
delimiter signature (should correspond to pattern 0x4E in order to be assumed valid)
Definition at line 86 of file ampdu-subframe-header.h.
Referenced by Deserialize(), IsSignatureValid(), Print(), and Serialize().
The documentation for this class was generated from the following files:
src/wifi/model/ampdu-subframe-header.h
src/wifi/model/ampdu-subframe-header.cc