ns-3: TimestampTag Class Reference
TimestampTag Class Reference
#include "wifi-example-apps.h"
Public Member Functions
virtual void Deserialize (TagBuffer i)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize (void) const
Time GetTimestamp (void) const
void Print (std::ostream &os) const
virtual void Serialize (TagBuffer i) const
void SetTimestamp (Time time)
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Time m_timestamp
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 105 of file wifi-example-apps.h.
Member Function Documentation
Deserialize()
void TimestampTag::Deserialize (TagBuffer i) virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 310 of file wifi-example-apps.cc.
References m_timestamp, ns3::NanoSeconds(), and ns3::TagBuffer::Read().
GetInstanceTypeId()
TypeId TimestampTag::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 293 of file wifi-example-apps.cc.
References GetTypeId().
GetSerializedSize()
uint32_t TimestampTag::GetSerializedSize (void) const virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 299 of file wifi-example-apps.cc.
GetTimestamp()
Time TimestampTag::GetTimestamp (void) const
Definition at line 323 of file wifi-example-apps.cc.
References m_timestamp.
Referenced by GetTypeId(), and Receiver::Receive().
GetTypeId()
TypeId TimestampTag::GetTypeId (void) static
Definition at line 279 of file wifi-example-apps.cc.
References GetTimestamp(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), and ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void TimestampTag::Print (std::ostream & os) const virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 329 of file wifi-example-apps.cc.
References m_timestamp.
Serialize()
void TimestampTag::Serialize (TagBuffer i) const virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 304 of file wifi-example-apps.cc.
References ns3::Time::GetNanoSeconds(), m_timestamp, and ns3::TagBuffer::Write().
SetTimestamp()
void TimestampTag::SetTimestamp (Time time)
Definition at line 318 of file wifi-example-apps.cc.
References m_timestamp.
Referenced by Sender::SendPacket().
Member Data Documentation
m_timestamp
Time TimestampTag::m_timestamp private
Definition at line 121 of file wifi-example-apps.h.
Referenced by Deserialize(), GetTimestamp(), Print(), Serialize(), and SetTimestamp().
The documentation for this class was generated from the following files:
examples/stats/wifi-example-apps.h
examples/stats/wifi-example-apps.cc