ns-3: WifiApp Class Reference
WifiApp Class Reference
WAVE module
The WifiApp class enforces program flow for ns-3 wifi applications.
Public Member Functions
WifiApp ()
Constructor.
virtual ~WifiApp ()
Destructor.
void Simulate (int argc, char **argv)
Enacts simulation of an ns-3 wifi application.
Protected Member Functions
virtual void ConfigureApplications ()
Configure applications.
virtual void ConfigureChannels ()
Configure channels.
virtual void ConfigureDevices ()
Configure devices.
virtual void ConfigureMobility ()
Configure mobility.
virtual void ConfigureNodes ()
Configure nodes.
virtual void ConfigureTracing ()
Configure tracing.
virtual void ParseCommandLineArguments (int argc, char **argv)
Process command line arguments.
virtual void ProcessOutputs ()
Process outputs.
virtual void RunSimulation ()
Run the simulation.
virtual void SetDefaultAttributeValues ()
Sets default attribute values.
Detailed Description
The WifiApp class enforces program flow for ns-3 wifi applications.
Definition at line 836 of file vanet-routing-compare.cc.
Constructor & Destructor Documentation
WifiApp()
WifiApp::WifiApp ()
Constructor.
Returns
none
Definition at line 923 of file vanet-routing-compare.cc.
~WifiApp()
WifiApp::~WifiApp () virtual
Destructor.
Returns
none
Definition at line 927 of file vanet-routing-compare.cc.
Member Function Documentation
ConfigureApplications()
void WifiApp::ConfigureApplications () protected virtual
Configure applications.
Returns
none
Reimplemented in VanetRoutingExperiment.
Definition at line 995 of file vanet-routing-compare.cc.
Referenced by Simulate().
ConfigureChannels()
void WifiApp::ConfigureChannels () protected virtual
Configure channels.
Returns
none
Reimplemented in VanetRoutingExperiment.
Definition at line 980 of file vanet-routing-compare.cc.
Referenced by Simulate().
ConfigureDevices()
void WifiApp::ConfigureDevices () protected virtual
Configure devices.
Returns
none
Reimplemented in VanetRoutingExperiment.
Definition at line 985 of file vanet-routing-compare.cc.
Referenced by Simulate().
ConfigureMobility()
void WifiApp::ConfigureMobility () protected virtual
Configure mobility.
Returns
none
Reimplemented in VanetRoutingExperiment.
Definition at line 990 of file vanet-routing-compare.cc.
Referenced by Simulate().
ConfigureNodes()
void WifiApp::ConfigureNodes () protected virtual
Configure nodes.
Returns
none
Reimplemented in VanetRoutingExperiment.
Definition at line 975 of file vanet-routing-compare.cc.
Referenced by Simulate().
ConfigureTracing()
void WifiApp::ConfigureTracing () protected virtual
Configure tracing.
Returns
none
Reimplemented in VanetRoutingExperiment.
Definition at line 1000 of file vanet-routing-compare.cc.
Referenced by Simulate().
ParseCommandLineArguments()
void WifiApp::ParseCommandLineArguments (int argc, char ** argv) protected virtual
Process command line arguments.
Parameters
argc program arguments count
argv program arguments
Returns
none
Reimplemented in VanetRoutingExperiment.
Definition at line 970 of file vanet-routing-compare.cc.
Referenced by Simulate().
ProcessOutputs()
void WifiApp::ProcessOutputs () protected virtual
Process outputs.
Returns
none
Reimplemented in VanetRoutingExperiment.
Definition at line 1010 of file vanet-routing-compare.cc.
Referenced by Simulate().
RunSimulation()
void WifiApp::RunSimulation () protected virtual
Run the simulation.
Returns
none
Reimplemented in VanetRoutingExperiment.
Definition at line 1005 of file vanet-routing-compare.cc.
Referenced by Simulate().
SetDefaultAttributeValues()
void WifiApp::SetDefaultAttributeValues () protected virtual
Sets default attribute values.
Returns
none
Reimplemented in VanetRoutingExperiment.
Definition at line 965 of file vanet-routing-compare.cc.
Referenced by Simulate().
Simulate()
void WifiApp::Simulate (int argc, char ** argv)
Enacts simulation of an ns-3 wifi application.
Parameters
argc program arguments count
argv program arguments
Returns
none
Definition at line 932 of file vanet-routing-compare.cc.
References ConfigureApplications(), ConfigureChannels(), ConfigureDevices(), ConfigureMobility(), ConfigureNodes(), ConfigureTracing(), ParseCommandLineArguments(), ProcessOutputs(), RunSimulation(), and SetDefaultAttributeValues().
The documentation for this class was generated from the following file:
src/wave/examples/vanet-routing-compare.cc