ns-3: ns3::BriteTopologyHelper Class Reference
ns3::BriteTopologyHelper Class Reference
BRITE Topology Generator
Interface with BRITE, the Boston university Representative Internet Topology gEnerator.
#include "brite-topology-helper.h"
Classes
struct BriteEdgeInfo
Edge information from BRITE.
struct BriteNodeInfo
Node information from BRITE.
Public Member Functions
BriteTopologyHelper (std::string confFile)
Construct a BriteTopologyHelper using NS3 to generate seed values need by BRITE.
BriteTopologyHelper (std::string confFile, std::string seedFile, std::string newseedFile)
Construct a BriteTopologyHelper.
~BriteTopologyHelper ()
void AssignIpv4Addresses (Ipv4AddressHelper &address)
void AssignIpv6Addresses (Ipv6AddressHelper &address)
void AssignStreams (int64_t streamNumber)
Assigns stream number to UniformRandomVariable used to generate brite seed file.
void BuildBriteTopology (InternetStackHelper &stack)
Create NS3 topology using information generated from BRITE.
void BuildBriteTopology (InternetStackHelper &stack, const uint32_t systemCount)
Create NS3 topology using information generated from BRITE and configure topology for MPI use.
Ptr< Node > GetLeafNodeForAs (uint32_t asNum, uint32_t leafNum)
Returns a given router leaf node from a given AS.
uint32_t GetNAs (void) const
Returns the number of AS created in the topology.
uint32_t GetNEdgesTopology () const
Returns the number of edges created within the topology.
uint32_t GetNLeafNodesForAs (uint32_t asNum)
Returns the number of router leaf nodes for a given AS.
uint32_t GetNNodesForAs (uint32_t asNum)
Returns the total number of nodes for a given AS.
uint32_t GetNNodesTopology () const
Returns the number of nodes created within the topology.
Ptr< Node > GetNodeForAs (uint32_t asNum, uint32_t nodeNum)
Returns a given router node for a given AS.
uint32_t GetSystemNumberForAs (uint32_t asNum) const
Returns the system number for the MPI instance that this AS is assigned to.
Private Member Functions
void BuildBriteEdgeInfoList (void)
void BuildBriteNodeInfoList (void)
void ConstructTopology (void)
void GenerateBriteTopology (void)
Private Attributes
std::vector< NodeContainer * > m_asLeafNodes
stores the leaf router nodes for each AS
PointToPointHelper m_britePointToPointHelper
used to create the links within the topology
std::string m_confFile
brite configuration file to use
std::vector< NetDeviceContainer * > m_netDevices
stores the netdevices created for each AS
std::string m_newSeedFile
brite seed file to generate for next run
NodeContainer m_nodes
std::vector< NodeContainer * > m_nodesByAs
stores all of the nodes in the brite topology by AS number
uint32_t m_numAs
stores the number of AS in the BRITE generated topology
uint32_t m_numEdges
stores the number of edges created in the BRITE topology
uint32_t m_numNodes
stores the number of nodes created in the BRITE topology
std::string m_seedFile
brite seed file to use
std::vector< int > m_systemForAs
stores the MPI system number each AS assigned to. All assigned to 0 if MPI not used.
brite::Topology * m_topology
the Brite topology
Ptr< UniformRandomVariable > m_uv
random variable stream for brite seed file
Static Private Attributes
static const int mbpsToBps = 1000000
typedef std::vector< BriteNodeInfo > BriteNodeInfoList
The BRITE code generates multiple nodes and edges.
typedef std::vector< BriteEdgeInfo > BriteEdgeInfoList
The BRITE code generates multiple nodes and edges.
BriteNodeInfoList m_briteNodeInfoList
The BRITE code generates multiple nodes and edges.
BriteEdgeInfoList m_briteEdgeInfoList
The BRITE code generates multiple nodes and edges.
Detailed Description
Interface with BRITE, the Boston university Representative Internet Topology gEnerator.
This helper class creates an interface with BRITE and allows the user to easily create ns-3 topologies from BRITE generated graphs. This class accepts a BRITE configuration and seed file, much like the stand-alone BRITE software. Using these files, BRITE generates a graph which is stored herein. ns-3 examples can then grab the BRITE generated nodes and edges from this helper and create ns-3 specific topologies.
Definition at line 59 of file brite-topology-helper.h.
Member Typedef Documentation
BriteEdgeInfoList
typedef std::vector<BriteEdgeInfo> ns3::BriteTopologyHelper::BriteEdgeInfoList private
The BRITE code generates multiple nodes and edges.
Each node and edge is stored in a BriteNodeInfo or BriteEdgeInfo struct, and each instance is stored in a vector.
Definition at line 279 of file brite-topology-helper.h.
BriteNodeInfoList
typedef std::vector<BriteNodeInfo> ns3::BriteTopologyHelper::BriteNodeInfoList private
The BRITE code generates multiple nodes and edges.
Each node and edge is stored in a BriteNodeInfo or BriteEdgeInfo struct, and each instance is stored in a vector.
Definition at line 278 of file brite-topology-helper.h.
Constructor & Destructor Documentation
BriteTopologyHelper() [1/2]
ns3::BriteTopologyHelper::BriteTopologyHelper (std::string confFile, std::string seedFile, std::string newseedFile)
Construct a BriteTopologyHelper.
Parameters
confFile a BRITE configuration file
seedFile a BRITE seed file
newseedFile a BRITE seed file with newly generated values
Definition at line 37 of file brite-topology-helper.cc.
References m_uv, and NS_LOG_FUNCTION.
BriteTopologyHelper() [2/2]
ns3::BriteTopologyHelper::BriteTopologyHelper (std::string confFile)
Construct a BriteTopologyHelper using NS3 to generate seed values need by BRITE.
Definition at line 54 of file brite-topology-helper.cc.
References m_uv, and NS_LOG_FUNCTION.
~BriteTopologyHelper()
ns3::BriteTopologyHelper::~BriteTopologyHelper ()
Definition at line 67 of file brite-topology-helper.cc.
References m_asLeafNodes, m_netDevices, m_nodesByAs, m_topology, and NS_LOG_FUNCTION.
Member Function Documentation
AssignIpv4Addresses()
void ns3::BriteTopologyHelper::AssignIpv4Addresses (Ipv4AddressHelper & address)
Parameters
address an Ipv4AddressHelper which is used to install Ipv4 addresses on all the node interfaces in the topology
Definition at line 421 of file brite-topology-helper.cc.
References first::address, m_netDevices, and NS_LOG_FUNCTION.
Referenced by BriteTopologyFunctionTestCase::DoRun().
AssignIpv6Addresses()
void ns3::BriteTopologyHelper::AssignIpv6Addresses (Ipv6AddressHelper & address)
Parameters
network an IPv6 address representing the network portion of the IPv6 Address
prefix the prefix length
Definition at line 433 of file brite-topology-helper.cc.
References first::address, m_netDevices, and NS_LOG_FUNCTION.
AssignStreams()
void ns3::BriteTopologyHelper::AssignStreams (int64_t streamNumber)
Assigns stream number to UniformRandomVariable used to generate brite seed file.
Parameters
streamNumber the stream number to assign
Definition at line 92 of file brite-topology-helper.cc.
References m_uv, and ns3::RandomVariableStream::SetStream().
Referenced by BriteTopologyStructureTestCase::DoRun().
BuildBriteEdgeInfoList()
void ns3::BriteTopologyHelper::BuildBriteEdgeInfoList (void) private
Definition at line 183 of file brite-topology-helper.cc.
References ns3::BriteTopologyHelper::BriteEdgeInfo::asFrom, ns3::BriteTopologyHelper::BriteEdgeInfo::asTo, ns3::BriteTopologyHelper::BriteEdgeInfo::bandwidth, ns3::BriteTopologyHelper::BriteEdgeInfo::delay, ns3::BriteTopologyHelper::BriteEdgeInfo::destId, ns3::BriteTopologyHelper::BriteEdgeInfo::edgeId, ns3::BriteTopologyHelper::BriteEdgeInfo::length, m_briteEdgeInfoList, m_topology, NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::BriteTopologyHelper::BriteEdgeInfo::srcId, and ns3::BriteTopologyHelper::BriteEdgeInfo::type.
Referenced by GenerateBriteTopology().
BuildBriteNodeInfoList()
void ns3::BriteTopologyHelper::BuildBriteNodeInfoList (void) private
Definition at line 98 of file brite-topology-helper.cc.
References ns3::BriteTopologyHelper::BriteNodeInfo::asId, ns3::BriteTopologyHelper::BriteNodeInfo::inDegree, m_briteNodeInfoList, m_numAs, m_topology, ns3::BriteTopologyHelper::BriteNodeInfo::nodeId, NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::BriteTopologyHelper::BriteNodeInfo::outDegree, ns3::BriteTopologyHelper::BriteNodeInfo::type, ns3::BriteTopologyHelper::BriteNodeInfo::xCoordinate, and ns3::BriteTopologyHelper::BriteNodeInfo::yCoordinate.
Referenced by GenerateBriteTopology().
BuildBriteTopology() [1/2]
void ns3::BriteTopologyHelper::BuildBriteTopology (InternetStackHelper & stack)
Create NS3 topology using information generated from BRITE.
Parameters
stack Internet stack to assign to nodes in topology
Definition at line 366 of file brite-topology-helper.cc.
References ConstructTopology(), ns3::NodeContainer::Create(), GenerateBriteTopology(), m_briteNodeInfoList, m_nodes, m_numAs, m_numNodes, m_systemForAs, NS_LOG_DEBUG, NS_LOG_FUNCTION, and first::stack.
Referenced by BriteTopologyStructureTestCase::DoRun(), and BriteTopologyFunctionTestCase::DoRun().
BuildBriteTopology() [2/2]
void ns3::BriteTopologyHelper::BuildBriteTopology (InternetStackHelper & stack, const uint32_t systemCount)
Create NS3 topology using information generated from BRITE and configure topology for MPI use.
Parameters
stack Internet stack to assign to nodes in topology.
systemCount The number of MPI instances to be used in the simulation.
Definition at line 391 of file brite-topology-helper.cc.
References ns3::NodeContainer::Add(), ConstructTopology(), GenerateBriteTopology(), GetSystemNumberForAs(), m_briteNodeInfoList, m_nodes, m_numAs, m_numNodes, m_systemForAs, NS_LOG_FUNCTION, NS_LOG_INFO, NS_LOG_LOGIC(), and first::stack.
ConstructTopology()
void ns3::BriteTopologyHelper::ConstructTopology (void) private
Definition at line 445 of file brite-topology-helper.cc.
References ns3::NodeContainer::Get(), ns3::PointToPointHelper::Install(), m_asLeafNodes, m_briteEdgeInfoList, m_briteNodeInfoList, m_britePointToPointHelper, m_netDevices, m_nodes, m_nodesByAs, m_numAs, m_numEdges, mbpsToBps, NS_LOG_FUNCTION, NS_LOG_INFO, ns3::Seconds(), ns3::PointToPointHelper::SetChannelAttribute(), and ns3::PointToPointHelper::SetDeviceAttribute().
Referenced by BuildBriteTopology().
GenerateBriteTopology()
void ns3::BriteTopologyHelper::GenerateBriteTopology (void) private
Definition at line 318 of file brite-topology-helper.cc.
References BuildBriteEdgeInfoList(), BuildBriteNodeInfoList(), ns3::UniformRandomVariable::GetInteger(), m_confFile, m_newSeedFile, m_seedFile, m_topology, m_uv, NS_ASSERT, NS_ASSERT_MSG(), and NS_LOG_LOGIC().
Referenced by BuildBriteTopology().
GetLeafNodeForAs()
Ptr< Node > ns3::BriteTopologyHelper::GetLeafNodeForAs (uint32_t asNum, uint32_t leafNum)
Returns a given router leaf node from a given AS.
Parameters
asNum the AS number
leafNum the leaf number
Returns
the specified node
Definition at line 271 of file brite-topology-helper.cc.
References m_asLeafNodes.
GetNAs()
uint32_t ns3::BriteTopologyHelper::GetNAs (void) const
Returns the number of AS created in the topology.
Returns
the number of AS created in the topology
Definition at line 307 of file brite-topology-helper.cc.
References m_numAs.
Referenced by BriteTopologyStructureTestCase::DoRun().
GetNEdgesTopology()
uint32_t ns3::BriteTopologyHelper::GetNEdgesTopology () const
Returns the number of edges created within the topology.
Returns
the total number of edges within the brite topology
Definition at line 301 of file brite-topology-helper.cc.
References m_numEdges.
Referenced by BriteTopologyStructureTestCase::DoRun().
GetNLeafNodesForAs()
uint32_t ns3::BriteTopologyHelper::GetNLeafNodesForAs (uint32_t asNum)
Returns the number of router leaf nodes for a given AS.
Parameters
asNum the AS number
Returns
the number of leaf nodes in the specified AS
Definition at line 289 of file brite-topology-helper.cc.
References m_asLeafNodes.
Referenced by BriteTopologyStructureTestCase::DoRun().
GetNNodesForAs()
uint32_t ns3::BriteTopologyHelper::GetNNodesForAs (uint32_t asNum)
Returns the total number of nodes for a given AS.
Parameters
asNum the AS number
Returns
the total number of nodes in the given AS
Definition at line 283 of file brite-topology-helper.cc.
References m_nodesByAs.
Referenced by BriteTopologyFunctionTestCase::DoRun().
GetNNodesTopology()
uint32_t ns3::BriteTopologyHelper::GetNNodesTopology () const
Returns the number of nodes created within the topology.
Returns
the total number of nodes within the brite topology
Definition at line 295 of file brite-topology-helper.cc.
References m_numNodes.
Referenced by BriteTopologyStructureTestCase::DoRun().
GetNodeForAs()
Ptr< Node > ns3::BriteTopologyHelper::GetNodeForAs (uint32_t asNum, uint32_t nodeNum)
Returns a given router node for a given AS.
Parameters
asNum the AS number
Returns
the specified node
Definition at line 277 of file brite-topology-helper.cc.
References m_nodesByAs.
Referenced by BriteTopologyFunctionTestCase::DoRun().
GetSystemNumberForAs()
uint32_t ns3::BriteTopologyHelper::GetSystemNumberForAs (uint32_t asNum) const
Returns the system number for the MPI instance that this AS is assigned to.
Will always return 0 if MPI not used
Returns
The system number that the specified AS number belongs to
param asNum The AS Number
Definition at line 313 of file brite-topology-helper.cc.
References m_systemForAs.
Referenced by BuildBriteTopology().
Member Data Documentation
m_asLeafNodes
std::vector<NodeContainer*> ns3::BriteTopologyHelper::m_asLeafNodes private
stores the leaf router nodes for each AS
Definition at line 255 of file brite-topology-helper.h.
Referenced by ~BriteTopologyHelper(), ConstructTopology(), GetLeafNodeForAs(), and GetNLeafNodesForAs().
m_briteEdgeInfoList
BriteEdgeInfoList ns3::BriteTopologyHelper::m_briteEdgeInfoList private
The BRITE code generates multiple nodes and edges.
Each node and edge is stored in a BriteNodeInfo or BriteEdgeInfo struct, and each instance is stored in a vector.
Definition at line 282 of file brite-topology-helper.h.
Referenced by BuildBriteEdgeInfoList(), and ConstructTopology().
m_briteNodeInfoList
BriteNodeInfoList ns3::BriteTopologyHelper::m_briteNodeInfoList private
The BRITE code generates multiple nodes and edges.
Each node and edge is stored in a BriteNodeInfo or BriteEdgeInfo struct, and each instance is stored in a vector.
Definition at line 281 of file brite-topology-helper.h.
Referenced by BuildBriteNodeInfoList(), BuildBriteTopology(), and ConstructTopology().
m_britePointToPointHelper
PointToPointHelper ns3::BriteTopologyHelper::m_britePointToPointHelper private
used to create the links within the topology
Definition at line 286 of file brite-topology-helper.h.
Referenced by ConstructTopology().
m_confFile
std::string ns3::BriteTopologyHelper::m_confFile private
brite configuration file to use
Definition at line 240 of file brite-topology-helper.h.
Referenced by GenerateBriteTopology().
m_netDevices
std::vector<NetDeviceContainer*> ns3::BriteTopologyHelper::m_netDevices private
stores the netdevices created for each AS
Definition at line 252 of file brite-topology-helper.h.
Referenced by ~BriteTopologyHelper(), AssignIpv4Addresses(), AssignIpv6Addresses(), and ConstructTopology().
m_newSeedFile
std::string ns3::BriteTopologyHelper::m_newSeedFile private
brite seed file to generate for next run
Definition at line 246 of file brite-topology-helper.h.
Referenced by GenerateBriteTopology().
m_nodes
NodeContainer ns3::BriteTopologyHelper::m_nodes private
Definition at line 232 of file brite-topology-helper.h.
Referenced by BuildBriteTopology(), and ConstructTopology().
m_nodesByAs
std::vector<NodeContainer*> ns3::BriteTopologyHelper::m_nodesByAs private
stores all of the nodes in the brite topology by AS number
Definition at line 258 of file brite-topology-helper.h.
Referenced by ~BriteTopologyHelper(), ConstructTopology(), GetNNodesForAs(), and GetNodeForAs().
m_numAs
uint32_t ns3::BriteTopologyHelper::m_numAs private
stores the number of AS in the BRITE generated topology
Definition at line 249 of file brite-topology-helper.h.
Referenced by BuildBriteNodeInfoList(), BuildBriteTopology(), ConstructTopology(), and GetNAs().
m_numEdges
uint32_t ns3::BriteTopologyHelper::m_numEdges private
stores the number of edges created in the BRITE topology
Definition at line 270 of file brite-topology-helper.h.
Referenced by ConstructTopology(), and GetNEdgesTopology().
m_numNodes
uint32_t ns3::BriteTopologyHelper::m_numNodes private
stores the number of nodes created in the BRITE topology
Definition at line 267 of file brite-topology-helper.h.
Referenced by BuildBriteTopology(), and GetNNodesTopology().
m_seedFile
std::string ns3::BriteTopologyHelper::m_seedFile private
brite seed file to use
Definition at line 243 of file brite-topology-helper.h.
Referenced by GenerateBriteTopology().
m_systemForAs
std::vector<int> ns3::BriteTopologyHelper::m_systemForAs private
stores the MPI system number each AS assigned to. All assigned to 0 if MPI not used.
Definition at line 261 of file brite-topology-helper.h.
Referenced by BuildBriteTopology(), and GetSystemNumberForAs().
m_topology
brite::Topology* ns3::BriteTopologyHelper::m_topology private
the Brite topology
Definition at line 264 of file brite-topology-helper.h.
Referenced by ~BriteTopologyHelper(), BuildBriteEdgeInfoList(), BuildBriteNodeInfoList(), and GenerateBriteTopology().
m_uv
Ptr<UniformRandomVariable> ns3::BriteTopologyHelper::m_uv private
random variable stream for brite seed file
Definition at line 289 of file brite-topology-helper.h.
Referenced by BriteTopologyHelper(), AssignStreams(), and GenerateBriteTopology().
mbpsToBps
const int ns3::BriteTopologyHelper::mbpsToBps = 1000000 static private
Definition at line 191 of file brite-topology-helper.h.
Referenced by ConstructTopology().
The documentation for this class was generated from the following files:
src/brite/helper/brite-topology-helper.h
src/brite/helper/brite-topology-helper.cc