ns-3: PacketSocketAppsTest Class Reference
PacketSocketAppsTest Class Reference
Network » Network module unit tests | Test suites
PacketSocket apps Unit Test.
Public Member Functions
PacketSocketAppsTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
void ReceivePkt (Ptr< const Packet > packet, const Address &from)
Receive a packet.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Attributes
uint32_t m_receivedPacketNumber
Number of received packets.
uint32_t m_receivedPacketSize
Received packet size.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
PacketSocket apps Unit Test.
Definition at line 41 of file packet-socket-apps-test-suite.cc.
Constructor & Destructor Documentation
PacketSocketAppsTest()
PacketSocketAppsTest::PacketSocketAppsTest ()
Definition at line 58 of file packet-socket-apps-test-suite.cc.
References m_receivedPacketNumber, and m_receivedPacketSize.
Member Function Documentation
DoRun()
void PacketSocketAppsTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 76 of file packet-socket-apps-test-suite.cc.
References third::channel, ns3::SimpleNetDevice::GetAddress(), ns3::SimpleNetDevice::GetIfIndex(), ns3::PacketSocketHelper::Install(), m_receivedPacketNumber, m_receivedPacketSize, ns3::MakeCallback(), first::nodes, NS_TEST_EXPECT_MSG_EQ, ReceivePkt(), ns3::ObjectBase::SetAttribute(), ns3::SimpleNetDevice::SetChannel(), ns3::PacketSocketServer::SetLocal(), ns3::SimpleNetDevice::SetNode(), ns3::PacketSocketAddress::SetPhysicalAddress(), ns3::PacketSocketAddress::SetProtocol(), ns3::PacketSocketClient::SetRemote(), ns3::PacketSocketAddress::SetSingleDevice(), and ns3::ObjectBase::TraceConnectWithoutContext().
ReceivePkt()
void PacketSocketAppsTest::ReceivePkt (Ptr< const Packet > packet, const Address & from)
Receive a packet.
Parameters
packet The packet
from Address of the sender
Definition at line 65 of file packet-socket-apps-test-suite.cc.
References ns3::Packet::GetSize(), m_receivedPacketNumber, and m_receivedPacketSize.
Referenced by DoRun().
Member Data Documentation
m_receivedPacketNumber
uint32_t PacketSocketAppsTest::m_receivedPacketNumber private
Number of received packets.
Definition at line 44 of file packet-socket-apps-test-suite.cc.
Referenced by PacketSocketAppsTest(), DoRun(), and ReceivePkt().
m_receivedPacketSize
uint32_t PacketSocketAppsTest::m_receivedPacketSize private
Received packet size.
Definition at line 43 of file packet-socket-apps-test-suite.cc.
Referenced by PacketSocketAppsTest(), DoRun(), and ReceivePkt().
The documentation for this class was generated from the following file:
src/network/test/packet-socket-apps-test-suite.cc