ns-3: ns3::TcpOptionSack Class Reference
ns3::TcpOptionSack Class Reference
Defines the TCP option of kind 5 (selective acknowledgment option) as in RFC 2018
#include "tcp-option-sack.h"
Public Types
typedef std::pair< SequenceNumber32, SequenceNumber32 > SackBlock
SACK block definition.
typedef std::list< SackBlock > SackList
SACK list definition.
Public Types inherited from ns3::TcpOption
enum Kind {
END = 0, NOP = 1, MSS = 2, WINSCALE = 3,
SACKPERMITTED = 4, SACK = 5, TS = 8, UNKNOWN = 255
}
The option Kind, as defined in the respective RFCs.
Public Member Functions
TcpOptionSack ()
virtual ~TcpOptionSack ()
void AddSackBlock (SackBlock s)
Add a SACK block.
void ClearSackList (void)
Clear the SACK list.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the Option from a buffer iterator.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint8_t GetKind (void) const
Get the ‘kind’ (as in RFC 793) of this option.
uint32_t GetNumSackBlocks (void) const
Count the total number of SACK blocks.
SackList GetSackList (void) const
Get the SACK list.
virtual uint32_t GetSerializedSize (void) const
Returns number of bytes required for Option serialization.
virtual void Print (std::ostream &os) const
Print the Option contents.
virtual void Serialize (Buffer::Iterator start) const
Serialize the Option to a buffer iterator.
Public Member Functions inherited from ns3::TcpOption
TcpOption ()
virtual ~TcpOption ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::TcpOption
static Ptr< TcpOption > CreateOption (uint8_t kind)
Creates an option.
static TypeId GetTypeId (void)
Get the type ID.
static bool IsKindKnown (uint8_t kind)
Check if the option is implemented.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Attributes
SackList m_sackList
the list of SACK blocks
Friends
std::ostream & operator<< (std::ostream &os, TcpOptionSack const &sackOption)
Output operator.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Defines the TCP option of kind 5 (selective acknowledgment option) as in RFC 2018
TCP SACK Option is used by a receiver to report non-contiguous blocks of data that have been received and queued in the receiving buffer. Using the information conveyed in SACK option sender retransmits only the segments that have actually been lost, allowing the recovery of multiple packet losses per sending window.
Each SACK block is defined by two 32-bit unsigned integers specifying the left and the right edge of the block. It means that with the 40-byte TCP option limitation in addition to the presence of TCP Timestamp Option, the maximum number of SACK blocks that can be appended to each segment is 3.
Definition at line 49 of file tcp-option-sack.h.
Member Typedef Documentation
SackBlock
typedef std::pair<SequenceNumber32, SequenceNumber32> ns3::TcpOptionSack::SackBlock
SACK block definition.
Definition at line 59 of file tcp-option-sack.h.
SackList
typedef std::list<SackBlock> ns3::TcpOptionSack::SackList
SACK list definition.
Definition at line 60 of file tcp-option-sack.h.
Constructor & Destructor Documentation
TcpOptionSack()
ns3::TcpOptionSack::TcpOptionSack ()
Definition at line 35 of file tcp-option-sack.cc.
~TcpOptionSack()
ns3::TcpOptionSack::~TcpOptionSack () virtual
Definition at line 40 of file tcp-option-sack.cc.
Member Function Documentation
AddSackBlock()
void ns3::TcpOptionSack::AddSackBlock (SackBlock s)
Add a SACK block.
Parameters
s the SACK block to be added
Definition at line 132 of file tcp-option-sack.cc.
References m_sackList, and NS_LOG_FUNCTION.
Referenced by Deserialize(), TcpTxBufferTestCase::TestIsLost(), TcpTxBufferTestCase::TestNextSeg(), and TcpRateLinuxWithBufferTest::TestWithSackBlocks().
ClearSackList()
void ns3::TcpOptionSack::ClearSackList (void)
Clear the SACK list.
Definition at line 147 of file tcp-option-sack.cc.
References m_sackList.
Referenced by TcpTxBufferTestCase::TestNextSeg().
Deserialize()
uint32_t ns3::TcpOptionSack::Deserialize (Buffer::Iterator start) virtual
Deserialize the Option from a buffer iterator.
Parameters
start the buffer iterator
Returns
the number of deserialized bytes
Implements ns3::TcpOption.
Definition at line 98 of file tcp-option-sack.cc.
References AddSackBlock(), GetKind(), GetSerializedSize(), m_sackList, NS_LOG_FUNCTION, NS_LOG_LOGIC(), NS_LOG_WARN, ns3::Buffer::Iterator::ReadNtohU32(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetInstanceTypeId()
TypeId ns3::TcpOptionSack::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Reimplemented from ns3::TcpOption.
Definition at line 56 of file tcp-option-sack.cc.
References GetTypeId().
GetKind()
uint8_t ns3::TcpOptionSack::GetKind (void) const virtual
Get the ‘kind’ (as in RFC 793) of this option.
Returns
the Option Kind
Implements ns3::TcpOption.
Definition at line 126 of file tcp-option-sack.cc.
References ns3::TcpOption::SACK.
Referenced by Deserialize(), and Serialize().
GetNumSackBlocks()
uint32_t ns3::TcpOptionSack::GetNumSackBlocks (void) const
Count the total number of SACK blocks.
Returns
the total number of SACK blocks
Definition at line 139 of file tcp-option-sack.cc.
References m_sackList, NS_LOG_FUNCTION, and NS_LOG_LOGIC().
Referenced by GetSerializedSize(), Print(), and Serialize().
GetSackList()
TcpOptionSack::SackList ns3::TcpOptionSack::GetSackList (void) const
Get the SACK list.
Returns
the SACK list
Definition at line 153 of file tcp-option-sack.cc.
References m_sackList, and NS_LOG_FUNCTION.
Referenced by TcpTxBufferTestCase::TestIsLost(), TcpTxBufferTestCase::TestNextSeg(), and TcpRateLinuxWithBufferTest::TestWithSackBlocks().
GetSerializedSize()
uint32_t ns3::TcpOptionSack::GetSerializedSize (void) const virtual
Returns number of bytes required for Option serialization.
Returns
number of bytes required for Option serialization
Implements ns3::TcpOption.
Definition at line 72 of file tcp-option-sack.cc.
References GetNumSackBlocks(), NS_LOG_FUNCTION, and NS_LOG_LOGIC().
Referenced by Deserialize().
GetTypeId()
TypeId ns3::TcpOptionSack::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 45 of file tcp-option-sack.cc.
References ns3::TypeId::SetParent().
Referenced by ns3::TcpOption::CreateOption(), and GetInstanceTypeId().
Print()
void ns3::TcpOptionSack::Print (std::ostream & os) const virtual
Print the Option contents.
Parameters
os the output stream
Implements ns3::TcpOption.
Definition at line 62 of file tcp-option-sack.cc.
References GetNumSackBlocks(), and m_sackList.
Serialize()
void ns3::TcpOptionSack::Serialize (Buffer::Iterator start) const virtual
Serialize the Option to a buffer iterator.
Parameters
start the buffer iterator
Implements ns3::TcpOption.
Definition at line 80 of file tcp-option-sack.cc.
References GetKind(), GetNumSackBlocks(), ns3::SequenceNumber< NUMERIC_TYPE, SIGNED_TYPE >::GetValue(), m_sackList, NS_LOG_FUNCTION, visualizer.core::start(), ns3::Buffer::Iterator::WriteHtonU32(), and ns3::Buffer::Iterator::WriteU8().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, TcpOptionSack const & sackOption) friend
Output operator.
Parameters
os The output stream.
sackOption the option to print.
Returns
The output stream.
Definition at line 159 of file tcp-option-sack.cc.
Member Data Documentation
m_sackList
SackList ns3::TcpOptionSack::m_sackList protected
the list of SACK blocks
Definition at line 98 of file tcp-option-sack.h.
Referenced by AddSackBlock(), ClearSackList(), Deserialize(), GetNumSackBlocks(), GetSackList(), ns3::operator<<(), Print(), and Serialize().
The documentation for this class was generated from the following files:
src/internet/model/tcp-option-sack.h
src/internet/model/tcp-option-sack.cc