ns-3: ns3::DeterministicRandomVariable Class Reference
ns3::DeterministicRandomVariable Class Reference
Core » Random Variables
The Random Number Generator (RNG) that returns a predetermined sequence.
#include "random-variable-stream.h"
Public Member Functions
DeterministicRandomVariable ()
Creates a deterministic RNG that will have a predetermined sequence of values.
virtual ~DeterministicRandomVariable ()
virtual uint32_t GetInteger (void)
Returns the next value in the sequence.
virtual double GetValue (void)
Returns the next value in the sequence.
void SetValueArray (double *values, std::size_t length)
Sets the array of values that holds the predetermined sequence.
Public Member Functions inherited from ns3::RandomVariableStream
RandomVariableStream ()
Default constructor.
virtual ~RandomVariableStream ()
Destructor.
int64_t GetStream (void) const
Returns the stream number for the RngStream.
bool IsAntithetic (void) const
Check if antithetic values will be generated.
void SetAntithetic (bool isAntithetic)
Specify whether antithetic values should be generated.
void SetStream (int64_t stream)
Specifies the stream number for the RngStream.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::RandomVariableStream
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
std::size_t m_count
Size of the array of values.
double * m_data
Array of values to return in sequence.
std::size_t m_next
Position of the next value in the array of values.
Additional Inherited Members
Protected Member Functions inherited from ns3::RandomVariableStream
RngStream * Peek (void) const
Get the pointer to the underlying RngStream.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The Random Number Generator (RNG) that returns a predetermined sequence.
Defines a random variable that has a specified, predetermined sequence. This would be useful when trying to force the RNG to return a known sequence, perhaps to compare ns-3 to some other simulator
Creates a generator that returns successive elements of the values array on successive calls to RandomVariableStream::GetValue. Note that the values in the array are copied and stored by the generator (deep-copy). Also note that the sequence repeats if more values are requested than are present in the array.
Here is an example of how to use this class:
Ptr<DeterministicRandomVariable> s = CreateObject<DeterministicRandomVariable> ();
// The following array should give the sequence
//
//    4, 4, 7, 7, 10, 10 .
//
double array [] = { 4, 4, 7, 7, 10, 10};
uint64_t count = 6;
s->SetValueArray (array, count);
double value = x->GetValue ();
Definition at line 2360 of file random-variable-stream.h.
Constructor & Destructor Documentation
DeterministicRandomVariable()
ns3::DeterministicRandomVariable::DeterministicRandomVariable ()
Creates a deterministic RNG that will have a predetermined sequence of values.
Definition at line 1471 of file random-variable-stream.cc.
References NS_LOG_FUNCTION.
~DeterministicRandomVariable()
ns3::DeterministicRandomVariable::~DeterministicRandomVariable () virtual
Definition at line 1479 of file random-variable-stream.cc.
References m_data, and NS_LOG_FUNCTION.
Member Function Documentation
GetInteger()
uint32_t ns3::DeterministicRandomVariable::GetInteger (void) virtual
Returns the next value in the sequence.
Returns
The integer next value in the sequence.
Implements ns3::RandomVariableStream.
Definition at line 1526 of file random-variable-stream.cc.
References GetValue(), and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::DeterministicRandomVariable::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 1462 of file random-variable-stream.cc.
References ns3::TypeId::SetParent().
GetValue()
double ns3::DeterministicRandomVariable::GetValue (void) virtual
Returns the next value in the sequence.
Returns
The floating point next value in the sequence.
Implements ns3::RandomVariableStream.
Definition at line 1512 of file random-variable-stream.cc.
References m_count, m_data, m_next, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by RandomVariableStreamDeterministicTestCase::DoRun(), and GetInteger().
SetValueArray()
void ns3::DeterministicRandomVariable::SetValueArray (double * values, std::size_t length)
Sets the array of values that holds the predetermined sequence.
Parameters
[in] values Array of random values to return in sequence.
[in] length Number of values in the array.
Note that the values in the array are copied and stored (deep-copy).
Definition at line 1490 of file random-variable-stream.cc.
References m_count, m_data, m_next, and NS_LOG_FUNCTION.
Referenced by RandomVariableStreamDeterministicTestCase::DoRun(), and GetRandomStream().
Member Data Documentation
m_count
std::size_t ns3::DeterministicRandomVariable::m_count private
Size of the array of values.
Definition at line 2400 of file random-variable-stream.h.
Referenced by GetValue(), and SetValueArray().
m_data
double* ns3::DeterministicRandomVariable::m_data private
Array of values to return in sequence.
Definition at line 2406 of file random-variable-stream.h.
Referenced by ~DeterministicRandomVariable(), GetValue(), and SetValueArray().
m_next
std::size_t ns3::DeterministicRandomVariable::m_next private
Position of the next value in the array of values.
Definition at line 2403 of file random-variable-stream.h.
Referenced by GetValue(), and SetValueArray().
The documentation for this class was generated from the following files:
src/core/model/random-variable-stream.h
src/core/model/random-variable-stream.cc