ns-3: ns3::TlvValue Class Reference
ns3::TlvValue Class Reference abstract
WiMAX Models
#include "wimax-tlv.h"
Public Member Functions
virtual ~TlvValue ()
virtual TlvValue * Copy (void) const =0
Copy function.
virtual uint32_t Deserialize (Buffer::Iterator start, uint64_t valueLen)=0
Deserialize from a buffer.
virtual uint32_t GetSerializedSize (void) const =0
Get serialized size in bytes.
virtual void Serialize (Buffer::Iterator start) const =0
Serialize to a buffer.
Detailed Description
The value field of a tlv can take different values (uint8_t, uint16, vector, ...). This class is a virtual interface from which all the types of tlv values should derive
Definition at line 43 of file wimax-tlv.h.
Constructor & Destructor Documentation
~TlvValue()
virtual ns3::TlvValue::~TlvValue () inline virtual
Definition at line 46 of file wimax-tlv.h.
Member Function Documentation
Copy()
virtual TlvValue* ns3::TlvValue::Copy (void) const pure virtual
Copy function.
Returns
the TLV value
Implemented in ns3::VectorTlvValue, ns3::ProtocolTlvValue, ns3::PortRangeTlvValue, ns3::ClassificationRuleVectorTlvValue, ns3::CsParamVectorTlvValue, ns3::SfVectorTlvValue, ns3::U32TlvValue, ns3::U16TlvValue, ns3::U8TlvValue, ns3::Ipv4AddressTlvValue, and ns3::TosTlvValue.
Referenced by ns3::Tlv::Tlv(), and ns3::Tlv::CopyValue().
Deserialize()
virtual uint32_t ns3::TlvValue::Deserialize (Buffer::Iterator start, uint64_t valueLen) pure virtual
Deserialize from a buffer.
Parameters
start the iterator
valueLen the maximum length of the value
Returns
the
Implemented in ns3::VectorTlvValue, ns3::Ipv4AddressTlvValue, ns3::ProtocolTlvValue, ns3::PortRangeTlvValue, ns3::TosTlvValue, ns3::ClassificationRuleVectorTlvValue, ns3::CsParamVectorTlvValue, ns3::SfVectorTlvValue, ns3::U32TlvValue, ns3::U16TlvValue, and ns3::U8TlvValue.
GetSerializedSize()
virtual uint32_t ns3::TlvValue::GetSerializedSize (void) const pure virtual
Get serialized size in bytes.
Returns
the serialized size
Implemented in ns3::Ipv4AddressTlvValue, ns3::ProtocolTlvValue, ns3::PortRangeTlvValue, ns3::TosTlvValue, ns3::VectorTlvValue, ns3::U32TlvValue, ns3::U16TlvValue, and ns3::U8TlvValue.
Referenced by ns3::Tlv::GetSerializedSize().
Serialize()
virtual void ns3::TlvValue::Serialize (Buffer::Iterator start) const pure virtual
Serialize to a buffer.
Parameters
start the iterator
Implemented in ns3::Ipv4AddressTlvValue, ns3::ProtocolTlvValue, ns3::PortRangeTlvValue, ns3::TosTlvValue, ns3::VectorTlvValue, ns3::U32TlvValue, ns3::U16TlvValue, and ns3::U8TlvValue.
Referenced by ns3::Tlv::Serialize().
The documentation for this class was generated from the following file:
src/wimax/model/wimax-tlv.h