ns-3: Ns3TcpInteroperabilityTestCase Class Reference
Ns3TcpInteroperabilityTestCase Class Reference
Public Member Functions
Ns3TcpInteroperabilityTestCase ()
virtual ~Ns3TcpInteroperabilityTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
virtual void DoSetup (void)
Implementation to do any local setup required for this TestCase.
virtual void DoTeardown (void)
Implementation to do any local setup required for this TestCase.
void Ipv4L3Tx (std::string context, Ptr< const Packet > packet, Ptr< Ipv4 > ipv4, uint32_t interface)
Private Attributes
PcapFile m_pcapFile
std::string m_pcapFilename
bool m_writeResults
bool m_writeVectors
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 91 of file ns3tcp-interop-test-suite.cc.
Constructor & Destructor Documentation
Ns3TcpInteroperabilityTestCase()
Ns3TcpInteroperabilityTestCase::Ns3TcpInteroperabilityTestCase ()
Definition at line 110 of file ns3tcp-interop-test-suite.cc.
~Ns3TcpInteroperabilityTestCase()
Ns3TcpInteroperabilityTestCase::~Ns3TcpInteroperabilityTestCase () virtual
Definition at line 115 of file ns3tcp-interop-test-suite.cc.
Member Function Documentation
DoRun()
void Ns3TcpInteroperabilityTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 203 of file ns3tcp-interop-test-suite.cc.
References first::address, ns3::Config::Connect(), first::devices, ns3::OnOffHelper::Install(), ns3::PacketSinkHelper::Install(), first::interfaces, Ipv4L3Tx(), m_writeResults, ns3::MakeCallback(), first::nodes, first::pointToPoint, ns3::Seconds(), ns3::OnOffHelper::SetAttribute(), first::stack, ns3::ApplicationContainer::Start(), and ns3::ApplicationContainer::Stop().
DoSetup()
void Ns3TcpInteroperabilityTestCase::DoSetup (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test setup before DoRun is invoked.
Reimplemented from ns3::TestCase.
Definition at line 120 of file ns3tcp-interop-test-suite.cc.
References ns3::TestCase::CreateDataDirFilename(), ns3::PcapFile::GetDataLinkType(), ns3::PcapFile::Init(), m_pcapFile, m_pcapFilename, m_writeVectors, NS_ABORT_MSG_UNLESS, ns3::PcapFile::Open(), PCAP_LINK_TYPE, and PCAP_SNAPLEN.
DoTeardown()
void Ns3TcpInteroperabilityTestCase::DoTeardown (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test teardown
Reimplemented from ns3::TestCase.
Definition at line 141 of file ns3tcp-interop-test-suite.cc.
References ns3::PcapFile::Close(), and m_pcapFile.
Ipv4L3Tx()
void Ns3TcpInteroperabilityTestCase::Ipv4L3Tx (std::string context, Ptr< const Packet > packet, Ptr< Ipv4 > ipv4, uint32_t interface) private
Definition at line 147 of file ns3tcp-interop-test-suite.cc.
References ns3::Packet::Copy(), ns3::Packet::CopyData(), ns3::Time::GetMicroSeconds(), ns3::TestCase::IsStatusSuccess(), m_pcapFile, m_writeVectors, ns3::Now(), NS_TEST_EXPECT_MSG_EQ, PCAP_SNAPLEN, ns3::PcapFile::Read(), ns3::Packet::RemoveHeader(), and ns3::PcapFile::Write().
Referenced by DoRun().
Member Data Documentation
m_pcapFile
PcapFile Ns3TcpInteroperabilityTestCase::m_pcapFile private
Definition at line 105 of file ns3tcp-interop-test-suite.cc.
Referenced by DoSetup(), DoTeardown(), and Ipv4L3Tx().
m_pcapFilename
std::string Ns3TcpInteroperabilityTestCase::m_pcapFilename private
Definition at line 104 of file ns3tcp-interop-test-suite.cc.
Referenced by DoSetup().
m_writeResults
bool Ns3TcpInteroperabilityTestCase::m_writeResults private
Definition at line 107 of file ns3tcp-interop-test-suite.cc.
Referenced by DoRun().
m_writeVectors
bool Ns3TcpInteroperabilityTestCase::m_writeVectors private
Definition at line 106 of file ns3tcp-interop-test-suite.cc.
Referenced by DoSetup(), and Ipv4L3Tx().
The documentation for this class was generated from the following file:
src/test/ns3tcp/ns3tcp-interop-test-suite.cc