ns-3: ns3::UanPhyCalcSinrDual Class Reference
ns3::UanPhyCalcSinrDual Class Reference
Default SINR model for UanPhyDual.
#include "uan-phy-dual.h"
Public Member Functions
UanPhyCalcSinrDual ()
Constructor.
virtual ~UanPhyCalcSinrDual ()
Destructor.
virtual double CalcSinrDb (Ptr< Packet > pkt, Time arrTime, double rxPowerDb, double ambNoiseDb, UanTxMode mode, UanPdp pdp, const UanTransducer::ArrivalList &arrivalList) const
Calculate the SINR value for a packet.
Public Member Functions inherited from ns3::UanPhyCalcSinr
virtual void Clear (void)
Clear all pointer references.
double DbToKp (double db) const
Convert dB re 1 uPa to kilopascals.
double KpToDb (double kp) const
Convert kilopascals to dB re 1 uPa.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::UanPhyCalcSinr
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::UanPhyCalcSinr
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Default SINR model for UanPhyDual.
Considers interfering packet power as additional ambient noise only if there is overlap in frequency band as found from supplied UanTxMode. If there is no overlap, then the packets are considered not to interfere.
Definition at line 41 of file uan-phy-dual.h.
Constructor & Destructor Documentation
UanPhyCalcSinrDual()
ns3::UanPhyCalcSinrDual::UanPhyCalcSinrDual ()
Constructor.
Definition at line 48 of file uan-phy-dual.cc.
~UanPhyCalcSinrDual()
ns3::UanPhyCalcSinrDual::~UanPhyCalcSinrDual () virtual
Destructor.
Definition at line 52 of file uan-phy-dual.cc.
Member Function Documentation
CalcSinrDb()
double ns3::UanPhyCalcSinrDual::CalcSinrDb (Ptr< Packet > pkt, Time arrTime, double rxPowerDb, double ambNoiseDb, UanTxMode mode, UanPdp pdp, const UanTransducer::ArrivalList & arrivalList) const virtual
Calculate the SINR value for a packet.
Parameters
pkt Packet to calculate SINR for.
arrTime Arrival time of pkt.
rxPowerDb The received signal strength of the packet in dB re 1 uPa.
ambNoiseDb Ambient channel noise in dB re 1 uPa.
mode TX Mode of pkt.
pdp Power delay profile of pkt.
arrivalList List of interfering arrivals given from Transducer.
Returns
The SINR in dB re 1 uPa.
Implements ns3::UanPhyCalcSinr.
Definition at line 69 of file uan-phy-dual.cc.
References ns3::UanPhyCalcSinr::DbToKp(), ns3::UanTxMode::GetBandwidthHz(), ns3::UanTxMode::GetCenterFreqHz(), ns3::UanTxMode::GetModType(), ns3::UanTxMode::GetName(), ns3::UanHeaderCommon::GetSrc(), ns3::UanHeaderCommon::GetType(), ns3::UanPhyCalcSinr::KpToDb(), ns3::Now(), NS_LOG_DEBUG, NS_LOG_WARN, ns3::UanTxMode::OTHER, ns3::Packet::PeekHeader(), ns3::Time::S, and ns3::UanMacRc::TYPE_DATA.
GetTypeId()
TypeId ns3::UanPhyCalcSinrDual::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 58 of file uan-phy-dual.cc.
References ns3::TypeId::SetParent().
The documentation for this class was generated from the following files:
src/uan/model/uan-phy-dual.h
src/uan/model/uan-phy-dual.cc