ns-3: ns3::TimerImpl Class Reference
ns3::TimerImpl Class Reference abstract
Core » Virtual Time Timer and Watchdog
#include "timer-impl.h"
Public Member Functions
virtual ~TimerImpl ()
Destructor.
virtual void Invoke (void)=0
Invoke the expire function.
virtual EventId Schedule (const Time &delay)=0
Schedule the callback for a future time.
template<typename T1 >
void SetArgs (T1 a1)
Set the arguments to be used when invoking the expire function.
template<typename T1 , typename T2 >
void SetArgs (T1 a1, T2 a2)
template<typename T1 , typename T2 , typename T3 >
void SetArgs (T1 a1, T2 a2, T3 a3)
template<typename T1 , typename T2 , typename T3 , typename T4 >
void SetArgs (T1 a1, T2 a2, T3 a3, T4 a4)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
void SetArgs (T1 a1, T2 a2, T3 a3, T4 a4, T5 a5)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 >
void SetArgs (T1 a1, T2 a2, T3 a3, T4 a4, T5 a5, T6 a6)
Detailed Description
The timer implementation underlying Timer and Watchdog.
Definition at line 42 of file timer-impl.h.
Constructor & Destructor Documentation
~TimerImpl()
virtual ns3::TimerImpl::~TimerImpl () inline virtual
Destructor.
Definition at line 46 of file timer-impl.h.
Member Function Documentation
Invoke()
virtual void ns3::TimerImpl::Invoke (void) pure virtual
Invoke the expire function.
Referenced by ns3::Watchdog::Expire().
Schedule()
virtual EventId ns3::TimerImpl::Schedule (const Time & delay) pure virtual
Schedule the callback for a future time.
Parameters
[in] delay The amount of time until the timer expires.
Returns
The scheduled EventId.
Referenced by ns3::Timer::Resume(), and ns3::Timer::Schedule().
SetArgs() [1/6]
template<typename T1 > void ns3::TimerImpl::SetArgs (T1 a1)
Set the arguments to be used when invoking the expire function.
Template Parameters
T1 [deduced] Type of the first argument.
Parameters
[in] a1 The first argument
Definition at line 961 of file timer-impl.h.
References NS_FATAL_ERROR.
SetArgs() [2/6]
template<typename T1 , typename T2 > void ns3::TimerImpl::SetArgs (T1 a1, T2 a2)
Template Parameters
T1 [deduced] Type of the first argument.
T2 [deduced] Type of the second argument.
Parameters
[in] a1 the first argument
[in] a2 the second argument
Definition at line 977 of file timer-impl.h.
References NS_FATAL_ERROR.
SetArgs() [3/6]
template<typename T1 , typename T2 , typename T3 > void ns3::TimerImpl::SetArgs (T1 a1, T2 a2, T3 a3)
Template Parameters
T1 [deduced] Type of the first argument.
T2 [deduced] Type of the second argument.
T3 [deduced] Type of the third argument.
Parameters
[in] a1 the first argument
[in] a2 the second argument
[in] a3 the third argument
Definition at line 994 of file timer-impl.h.
References NS_FATAL_ERROR.
SetArgs() [4/6]
template<typename T1 , typename T2 , typename T3 , typename T4 > void ns3::TimerImpl::SetArgs (T1 a1, T2 a2, T3 a3, T4 a4)
Template Parameters
T1 [deduced] Type of the first argument.
T2 [deduced] Type of the second argument.
T3 [deduced] Type of the third argument.
T4 [deduced] Type of the fourth argument.
Parameters
[in] a1 the first argument
[in] a2 the second argument
[in] a3 the third argument
[in] a4 the fourth argument
Definition at line 1012 of file timer-impl.h.
References NS_FATAL_ERROR.
SetArgs() [5/6]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > void ns3::TimerImpl::SetArgs (T1 a1, T2 a2, T3 a3, T4 a4, T5 a5)
Template Parameters
T1 [deduced] Type of the first argument.
T2 [deduced] Type of the second argument.
T3 [deduced] Type of the third argument.
T4 [deduced] Type of the fourth argument.
T5 [deduced] Type of the fifth argument.
Parameters
[in] a1 the first argument
[in] a2 the second argument
[in] a3 the third argument
[in] a4 the fourth argument
[in] a5 the fifth argument
Definition at line 1031 of file timer-impl.h.
References NS_FATAL_ERROR.
SetArgs() [6/6]
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 > void ns3::TimerImpl::SetArgs (T1 a1, T2 a2, T3 a3, T4 a4, T5 a5, T6 a6)
Template Parameters
T1 [deduced] Type of the first argument.
T2 [deduced] Type of the second argument.
T3 [deduced] Type of the third argument.
T4 [deduced] Type of the fourth argument.
T5 [deduced] Type of the fifth argument.
T6 [deduced] Type of the sixth argument.
Parameters
[in] a1 the first argument
[in] a2 the second argument
[in] a3 the third argument
[in] a4 the fourth argument
[in] a5 the fifth argument
[in] a6 the sixth argument
Definition at line 1051 of file timer-impl.h.
References NS_FATAL_ERROR.
The documentation for this class was generated from the following file:
src/core/model/timer-impl.h