ns-3: ns3::XmlConfigSave Class Reference
ns3::XmlConfigSave Class Reference
Configuration Store/Load
A class to enable saving of configuration store in an XML file.
#include "xml-config.h"
Public Member Functions
XmlConfigSave ()
virtual ~XmlConfigSave ()
virtual void Attributes (void)
Load or save the attributes values.
virtual void Default (void)
Load or save the default values.
virtual void Global (void)
Load or save the global values.
virtual void SetFilename (std::string filename)
Set the file name.
Public Member Functions inherited from ns3::FileConfig
virtual ~FileConfig ()
Private Attributes
xmlTextWriterPtr m_writer
XML writer.
Detailed Description
A class to enable saving of configuration store in an XML file.
Definition at line 36 of file xml-config.h.
Constructor & Destructor Documentation
XmlConfigSave()
ns3::XmlConfigSave::XmlConfigSave ()
Definition at line 36 of file xml-config.cc.
References NS_LOG_FUNCTION.
~XmlConfigSave()
ns3::XmlConfigSave::~XmlConfigSave () virtual
Definition at line 79 of file xml-config.cc.
References m_writer, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
Member Function Documentation
Attributes()
void ns3::XmlConfigSave::Attributes (void) virtual
Load or save the attributes values.
Implements ns3::FileConfig.
Definition at line 147 of file xml-config.cc.
References ns3::StringValue::Get(), m_writer, and NS_FATAL_ERROR.
Default()
void ns3::XmlConfigSave::Default (void) virtual
Load or save the default values.
Implements ns3::FileConfig.
Definition at line 101 of file xml-config.cc.
References m_writer, and NS_FATAL_ERROR.
Global()
void ns3::XmlConfigSave::Global (void) virtual
Load or save the global values.
Implements ns3::FileConfig.
Definition at line 190 of file xml-config.cc.
References ns3::GlobalValue::Begin(), ns3::GlobalValue::End(), ns3::StringValue::Get(), m_writer, and NS_FATAL_ERROR.
SetFilename()
void ns3::XmlConfigSave::SetFilename (std::string filename) virtual
Set the file name.
Parameters
filename the filename
Implements ns3::FileConfig.
Definition at line 42 of file xml-config.cc.
References m_writer, NS_FATAL_ERROR, and NS_LOG_FUNCTION.
Member Data Documentation
m_writer
xmlTextWriterPtr ns3::XmlConfigSave::m_writer private
XML writer.
Definition at line 47 of file xml-config.h.
Referenced by ~XmlConfigSave(), Attributes(), Default(), Global(), and SetFilename().
The documentation for this class was generated from the following files:
src/config-store/model/xml-config.h
src/config-store/model/xml-config.cc