ns-3: anonymous_namespace{sample-show-progress.cc}::Hold Class Reference
anonymous_namespace{sample-show-progress.cc}::Hold Class Reference
Execute a function periodically, which takes more or less time to run.
Public Member Functions
Hold (Ptr< RandomVariableStream > rng)
Create a hold with a specified random number generator for the wait time.
Hold (Time wait, Time interval)
Create a Hold with mean inter-event time wait, changing workload every interval.
void Event (void)
The Hold event.
Public Member Functions inherited from ns3::SimpleRefCount< Hold >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
SystemCondition m_condition
Timer to represent workload.
Time m_interval
Time between switching workloads.
Ptr< RandomVariableStream > m_rng
The random number generator for the interval between events.
Time m_wait
Mean inter-event time.
Detailed Description
Execute a function periodically, which takes more or less time to run.
Inspired by PHOLD.
Definition at line 92 of file sample-show-progress.cc.
Constructor & Destructor Documentation
Hold() [1/2]
anonymous_namespace{sample-show-progress.cc}::Hold::Hold (Time wait, Time interval) inline
Create a Hold with mean inter-event time wait, changing workload every interval.
Parameters
wait The mean inter-event time.
interval How often to change work load. This should be an order of magnitude larger than wait.
Definition at line 103 of file sample-show-progress.cc.
Hold() [2/2]
anonymous_namespace{sample-show-progress.cc}::Hold::Hold (Ptr< RandomVariableStream > rng) inline
Create a hold with a specified random number generator for the wait time.
The RNG value will be interpreted as seconds.
Parameters
rng The random variable generator to use for the inter-event time.
Definition at line 117 of file sample-show-progress.cc.
Member Function Documentation
Event()
void anonymous_namespace{sample-show-progress.cc}::Hold::Event (void) inline
The Hold event.
Definition at line 122 of file sample-show-progress.cc.
References ns3::int64x64_t::GetHigh(), ns3::Time::GetNanoSeconds(), ns3::Simulator::Now(), NS_LOG_LOGIC(), ns3::Simulator::Schedule(), and ns3::Seconds().
Member Data Documentation
m_condition
SystemCondition anonymous_namespace{sample-show-progress.cc}::Hold::m_condition private
Timer to represent workload.
Definition at line 142 of file sample-show-progress.cc.
m_interval
Time anonymous_namespace{sample-show-progress.cc}::Hold::m_interval private
Time between switching workloads.
Definition at line 146 of file sample-show-progress.cc.
m_rng
Ptr<RandomVariableStream> anonymous_namespace{sample-show-progress.cc}::Hold::m_rng private
The random number generator for the interval between events.
Definition at line 140 of file sample-show-progress.cc.
m_wait
Time anonymous_namespace{sample-show-progress.cc}::Hold::m_wait private
Mean inter-event time.
Definition at line 144 of file sample-show-progress.cc.
The documentation for this class was generated from the following file:
src/core/examples/sample-show-progress.cc