ns-3: ns3::DefaultSimulatorImpl Class Reference
ns3::DefaultSimulatorImpl Class Reference
Core » Simulator
#include "default-simulator-impl.h"
Classes
struct EventWithContext
Wrap an event with its execution context.
Public Member Functions
DefaultSimulatorImpl ()
Constructor.
~DefaultSimulatorImpl ()
Destructor.
virtual void Cancel (const EventId &id)
Set the cancel bit on this event: the event's associated function will not be invoked when it expires.
virtual void Destroy ()
Execute the events scheduled with ScheduleDestroy().
virtual uint32_t GetContext (void) const
Get the current simulation context.
virtual Time GetDelayLeft (const EventId &id) const
Get the remaining time until this event will execute.
virtual uint64_t GetEventCount (void) const
Get the number of events executed.
virtual Time GetMaximumSimulationTime (void) const
Get the maximum representable simulation time.
virtual uint32_t GetSystemId (void) const
Get the system id of this simulator.
virtual bool IsExpired (const EventId &id) const
Check if an event has already run or been cancelled.
virtual bool IsFinished (void) const
Check if the simulation should finish.
virtual Time Now (void) const
Return the current simulation virtual time.
virtual void Remove (const EventId &id)
Remove an event from the event list.
virtual void Run (void)
Run the simulation.
virtual EventId Schedule (const Time &delay, EventImpl *event)
Schedule a future event execution (in the same context).
virtual EventId ScheduleDestroy (EventImpl *event)
Schedule an event to run at the end of the simulation, after the Stop() time or condition has been reached.
virtual EventId ScheduleNow (EventImpl *event)
Schedule an event to run at the current virtual time.
virtual void ScheduleWithContext (uint32_t context, const Time &delay, EventImpl *event)
Schedule a future event execution (in a different context).
virtual void SetScheduler (ObjectFactory schedulerFactory)
Set the Scheduler to be used to manage the event list.
virtual void Stop (const Time &delay)
Schedule the time delay until the Simulator should stop.
virtual void Stop (void)
Tell the Simulator the calling event should be the last one executed.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::SimulatorImpl
static TypeId GetTypeId (void)
Get the registered TypeId for this class.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef std::list< EventId > DestroyEvents
Container type for the events to run at Simulator::Destroy()
typedef std::list< struct EventWithContext > EventsWithContext
Container type for the events from a different context.
Private Member Functions
virtual void DoDispose (void)
Destructor implementation.
void ProcessEventsWithContext (void)
Move events from a different context into the main event queue.
void ProcessOneEvent (void)
Process the next event.
Private Attributes
uint32_t m_currentContext
Execution context of the current event.
uint64_t m_currentTs
Timestamp of the current event.
uint32_t m_currentUid
Unique id of the current event.
DestroyEvents m_destroyEvents
The container of events to run at Destroy.
uint64_t m_eventCount
The event count.
Ptr< Scheduler > m_events
The event priority queue.
EventsWithContext m_eventsWithContext
The container of events from a different context.
bool m_eventsWithContextEmpty
Flag true if all events with context have been moved to the primary event queue.
SystemMutex m_eventsWithContextMutex
Mutex to control access to the list of events with context.
SystemThread::ThreadId m_main
Main execution thread.
bool m_stop
Flag calling for the end of the simulation.
uint32_t m_uid
Next event unique id.
int m_unscheduledEvents
Number of events that have been inserted but not yet scheduled, not counting the Destroy events; this is used for validation.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The default single process simulator implementation.
Definition at line 47 of file default-simulator-impl.h.
Member Typedef Documentation
DestroyEvents
typedef std::list<EventId> ns3::DefaultSimulatorImpl::DestroyEvents private
Container type for the events to run at Simulator::Destroy()
Definition at line 113 of file default-simulator-impl.h.
EventsWithContext
typedef std::list<struct EventWithContext> ns3::DefaultSimulatorImpl::EventsWithContext private
Container type for the events from a different context.
Definition at line 101 of file default-simulator-impl.h.
Constructor & Destructor Documentation
DefaultSimulatorImpl()
ns3::DefaultSimulatorImpl::DefaultSimulatorImpl ()
Constructor.
Definition at line 60 of file default-simulator-impl.cc.
References m_currentContext, m_currentTs, m_currentUid, m_eventCount, m_eventsWithContextEmpty, m_main, m_stop, m_uid, m_unscheduledEvents, ns3::Simulator::NO_CONTEXT, NS_LOG_FUNCTION, and ns3::SystemThread::Self().
~DefaultSimulatorImpl()
ns3::DefaultSimulatorImpl::~DefaultSimulatorImpl ()
Destructor.
Definition at line 79 of file default-simulator-impl.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Cancel()
void ns3::DefaultSimulatorImpl::Cancel (const EventId & id) virtual
Set the cancel bit on this event: the event's associated function will not be invoked when it expires.
This method has the same visible effect as the ns3::Simulator::Remove method but its algorithmic complexity is much lower: it has O(1) complexity. This method has the exact same semantics as ns3::EventId::Cancel. Note that it is not possible to cancel events which were scheduled for the "destroy" time. Doing so will result in a program error (crash).
Parameters
[in] id the event to cancel
Implements ns3::SimulatorImpl.
Definition at line 362 of file default-simulator-impl.cc.
References IsExpired().
Destroy()
void ns3::DefaultSimulatorImpl::Destroy () virtual
Execute the events scheduled with ScheduleDestroy().
This method is typically invoked at the end of a simulation to avoid false-positive reports by a leak checker. After this method has been invoked, it is actually possible to restart a new simulation with a set of calls to Simulator::Run, Simulator::Schedule and Simulator::ScheduleWithContext.
Implements ns3::SimulatorImpl.
Definition at line 99 of file default-simulator-impl.cc.
References m_destroyEvents, NS_LOG_FUNCTION, and NS_LOG_LOGIC().
DoDispose()
void ns3::DefaultSimulatorImpl::DoDispose (void) private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 85 of file default-simulator-impl.cc.
References ns3::Object::DoDispose(), ns3::Scheduler::Event::impl, m_events, NS_LOG_FUNCTION, ProcessEventsWithContext(), and ns3::SimpleRefCount< T, PARENT, DELETER >::Unref().
GetContext()
uint32_t ns3::DefaultSimulatorImpl::GetContext (void) const virtual
Get the current simulation context.
The simulation context is the ns-3 notion of a Logical Process. Events in a single context should only modify state associated with that context. Events for objects in other contexts should be scheduled with ScheduleWithContext() to track the context switches. In other words, events in different contexts should be mutually thread safe, by not modify overlapping model state.
In circumstances where the context can't be determined, such as during object initialization, the enum value NO_CONTEXT should be used.
Returns
The current simulation context
Implements ns3::SimulatorImpl.
Definition at line 410 of file default-simulator-impl.cc.
References m_currentContext.
Referenced by Schedule(), and ScheduleNow().
GetDelayLeft()
Time ns3::DefaultSimulatorImpl::GetDelayLeft (const EventId & id) const virtual
Get the remaining time until this event will execute.
Parameters
[in] id The event id to analyse.
Returns
The delay left until the input event id expires. if the event is not running, this method returns zero.
Implements ns3::SimulatorImpl.
Definition at line 316 of file default-simulator-impl.cc.
References IsExpired(), m_currentTs, and ns3::TimeStep().
GetEventCount()
uint64_t ns3::DefaultSimulatorImpl::GetEventCount (void) const virtual
Get the number of events executed.
Returns
The total number of events executed.
Implements ns3::SimulatorImpl.
Definition at line 416 of file default-simulator-impl.cc.
References m_eventCount.
GetMaximumSimulationTime()
Time ns3::DefaultSimulatorImpl::GetMaximumSimulationTime (void) const virtual
Get the maximum representable simulation time.
Returns
The maximum simulation time at which an event can be scheduled.
The returned value will always be bigger than or equal to Simulator::Now.
Implements ns3::SimulatorImpl.
Definition at line 404 of file default-simulator-impl.cc.
References ns3::TimeStep().
GetSystemId()
uint32_t ns3::DefaultSimulatorImpl::GetSystemId (void) const virtual
Get the system id of this simulator.
The system id is the identifier for this simulator instance in a distributed simulation. For MPI this is the MPI rank.
Returns
The system id for this simulator.
Implements ns3::SimulatorImpl.
Definition at line 133 of file default-simulator-impl.cc.
GetTypeId()
TypeId ns3::DefaultSimulatorImpl::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 50 of file default-simulator-impl.cc.
References ns3::TypeId::SetParent().
Referenced by ns3::anonymous_namespace{visual-simulator-impl.cc}::GetDefaultSimulatorImplFactory().
IsExpired()
bool ns3::DefaultSimulatorImpl::IsExpired (const EventId & id) const virtual
Check if an event has already run or been cancelled.
This method has O(1) complexity. Note that it is not possible to test for the expiration of events which were scheduled for the "destroy" time. Doing so will result in a program error (crash). An event is said to "expire" when it starts being scheduled which means that if the code executed by the event calls this function, it will get true.
Parameters
[in] id The event to test for expiration.
Returns
true if the event has expired, false otherwise.
Implements ns3::SimulatorImpl.
Definition at line 371 of file default-simulator-impl.cc.
References m_currentTs, m_currentUid, and m_destroyEvents.
Referenced by Cancel(), GetDelayLeft(), and Remove().
IsFinished()
bool ns3::DefaultSimulatorImpl::IsFinished (void) const virtual
Check if the simulation should finish.
Reasons to finish are because there are no more events lefts to be scheduled, or if simulation time has already reached the "stop time" (see Simulator::Stop()).
Returns
true if no more events or stop time reached.
Implements ns3::SimulatorImpl.
Definition at line 158 of file default-simulator-impl.cc.
References m_events, and m_stop.
Now()
Time ns3::DefaultSimulatorImpl::Now (void) const virtual
Return the current simulation virtual time.
Returns
The current virtual time.
Implements ns3::SimulatorImpl.
Definition at line 309 of file default-simulator-impl.cc.
References m_currentTs, and ns3::TimeStep().
ProcessEventsWithContext()
void ns3::DefaultSimulatorImpl::ProcessEventsWithContext (void) private
Move events from a different context into the main event queue.
Definition at line 164 of file default-simulator-impl.cc.
References ns3::Scheduler::Event::impl, ns3::Scheduler::Event::key, ns3::Scheduler::EventKey::m_context, m_currentTs, m_events, m_eventsWithContext, m_eventsWithContextEmpty, m_eventsWithContextMutex, ns3::Scheduler::EventKey::m_ts, m_uid, ns3::Scheduler::EventKey::m_uid, and m_unscheduledEvents.
Referenced by DoDispose(), ProcessOneEvent(), and Run().
ProcessOneEvent()
void ns3::DefaultSimulatorImpl::ProcessOneEvent (void) private
Process the next event.
Definition at line 139 of file default-simulator-impl.cc.
References ns3::Scheduler::Event::impl, ns3::EventImpl::Invoke(), ns3::Scheduler::Event::key, ns3::Scheduler::EventKey::m_context, m_currentContext, m_currentTs, m_currentUid, m_eventCount, m_events, ns3::Scheduler::EventKey::m_ts, ns3::Scheduler::EventKey::m_uid, m_unscheduledEvents, NS_ASSERT, NS_LOG_LOGIC(), ProcessEventsWithContext(), and ns3::SimpleRefCount< T, PARENT, DELETER >::Unref().
Referenced by Run().
Remove()
void ns3::DefaultSimulatorImpl::Remove (const EventId & id) virtual
Remove an event from the event list.
This method has the same visible effect as the ns3::EventId::Cancel method but its algorithmic complexity is much higher: it has often O(log(n)) complexity, sometimes O(n), sometimes worse. Note that it is not possible to remove events which were scheduled for the "destroy" time. Doing so will result in a program error (crash).
Parameters
[in] id The event to remove from the list of scheduled events.
Implements ns3::SimulatorImpl.
Definition at line 329 of file default-simulator-impl.cc.
References ns3::Scheduler::Event::impl, IsExpired(), m_destroyEvents, m_events, and m_unscheduledEvents.
Run()
void ns3::DefaultSimulatorImpl::Run (void) virtual
Run the simulation.
The simulation will run until one of:
No events are present anymore
The user called Simulator::Stop
The user called Simulator::Stop with a stop time and the expiration time of the next event to be processed is greater than or equal to the stop time.
Implements ns3::SimulatorImpl.
Definition at line 194 of file default-simulator-impl.cc.
References m_events, m_main, m_stop, m_unscheduledEvents, NS_ASSERT, NS_LOG_FUNCTION, ProcessEventsWithContext(), ProcessOneEvent(), and ns3::SystemThread::Self().
Schedule()
EventId ns3::DefaultSimulatorImpl::Schedule (const Time & delay, EventImpl * event) virtual
Schedule a future event execution (in the same context).
Parameters
[in] delay Delay until the event expires.
[in] event The event to schedule.
Returns
A unique identifier for the newly-scheduled event.
Implements ns3::SimulatorImpl.
Definition at line 230 of file default-simulator-impl.cc.
References ns3::SystemThread::Equals(), GetContext(), ns3::Time::GetTimeStep(), ns3::Scheduler::Event::impl, ns3::Time::IsPositive(), ns3::Scheduler::Event::key, ns3::Scheduler::EventKey::m_context, m_currentTs, m_events, m_main, ns3::Scheduler::EventKey::m_ts, m_uid, ns3::Scheduler::EventKey::m_uid, m_unscheduledEvents, NS_ASSERT_MSG(), NS_LOG_FUNCTION, and ns3::TimeStep().
ScheduleDestroy()
EventId ns3::DefaultSimulatorImpl::ScheduleDestroy (EventImpl * event) virtual
Schedule an event to run at the end of the simulation, after the Stop() time or condition has been reached.
Parameters
[in] event The event to schedule.
Returns
A unique identifier for the newly-scheduled event.
Implements ns3::SimulatorImpl.
Definition at line 298 of file default-simulator-impl.cc.
References ns3::SystemThread::Equals(), m_currentTs, m_destroyEvents, m_main, m_uid, and NS_ASSERT_MSG().
ScheduleNow()
EventId ns3::DefaultSimulatorImpl::ScheduleNow (EventImpl * event) virtual
Schedule an event to run at the current virtual time.
Parameters
[in] event The event to schedule.
Returns
A unique identifier for the newly-scheduled event.
Implements ns3::SimulatorImpl.
Definition at line 282 of file default-simulator-impl.cc.
References ns3::SystemThread::Equals(), GetContext(), ns3::Scheduler::Event::impl, ns3::Scheduler::Event::key, ns3::Scheduler::EventKey::m_context, m_currentTs, m_events, m_main, ns3::Scheduler::EventKey::m_ts, m_uid, ns3::Scheduler::EventKey::m_uid, m_unscheduledEvents, and NS_ASSERT_MSG().
ScheduleWithContext()
void ns3::DefaultSimulatorImpl::ScheduleWithContext (uint32_t context, const Time & delay, EventImpl * event) virtual
Schedule a future event execution (in a different context).
This method is thread-safe: it can be called from any thread.
Parameters
[in] delay Delay until the event expires.
[in] context Event context.
[in] event The event to schedule.
Returns
A unique identifier for the newly-scheduled event.
Implements ns3::SimulatorImpl.
Definition at line 250 of file default-simulator-impl.cc.
References ns3::DefaultSimulatorImpl::EventWithContext::context, ns3::SystemThread::Equals(), ns3::DefaultSimulatorImpl::EventWithContext::event, ns3::Time::GetTimeStep(), ns3::Scheduler::Event::impl, ns3::Scheduler::Event::key, ns3::Scheduler::EventKey::m_context, m_currentTs, m_events, m_eventsWithContext, m_eventsWithContextEmpty, m_eventsWithContextMutex, m_main, ns3::Scheduler::EventKey::m_ts, m_uid, ns3::Scheduler::EventKey::m_uid, m_unscheduledEvents, NS_LOG_FUNCTION, ns3::DefaultSimulatorImpl::EventWithContext::timestamp, and ns3::TimeStep().
SetScheduler()
void ns3::DefaultSimulatorImpl::SetScheduler (ObjectFactory schedulerFactory) virtual
Set the Scheduler to be used to manage the event list.
Parameters
[in] schedulerFactory A new event scheduler factory.
The event scheduler can be set at any time: the events scheduled in the previous scheduler will be transferred to the new scheduler before we start to use it.
Implements ns3::SimulatorImpl.
Definition at line 115 of file default-simulator-impl.cc.
References ns3::ObjectFactory::Create(), m_events, and NS_LOG_FUNCTION.
Stop() [1/2]
void ns3::DefaultSimulatorImpl::Stop (const Time & delay) virtual
Schedule the time delay until the Simulator should stop.
Force the Simulator::Run method to return to the caller when the expiration time of the next event to be processed is greater than or equal to the stop time. The stop time is relative to the current simulation time.
Parameters
[in] delay The stop time, relative to the current time.
Implements ns3::SimulatorImpl.
Definition at line 220 of file default-simulator-impl.cc.
References ns3::Time::GetTimeStep(), NS_LOG_FUNCTION, ns3::Simulator::Schedule(), and ns3::Simulator::Stop().
Stop() [2/2]
void ns3::DefaultSimulatorImpl::Stop (void) virtual
Tell the Simulator the calling event should be the last one executed.
If a running event invokes this method, it will be the last event executed by the Simulator::Run method before returning to the caller.
Implements ns3::SimulatorImpl.
Definition at line 213 of file default-simulator-impl.cc.
References m_stop, and NS_LOG_FUNCTION.
Member Data Documentation
m_currentContext
uint32_t ns3::DefaultSimulatorImpl::m_currentContext private
Execution context of the current event.
Definition at line 128 of file default-simulator-impl.h.
Referenced by DefaultSimulatorImpl(), GetContext(), and ProcessOneEvent().
m_currentTs
uint64_t ns3::DefaultSimulatorImpl::m_currentTs private
Timestamp of the current event.
Definition at line 126 of file default-simulator-impl.h.
Referenced by DefaultSimulatorImpl(), GetDelayLeft(), IsExpired(), Now(), ProcessEventsWithContext(), ProcessOneEvent(), Schedule(), ScheduleDestroy(), ScheduleNow(), and ScheduleWithContext().
m_currentUid
uint32_t ns3::DefaultSimulatorImpl::m_currentUid private
Unique id of the current event.
Definition at line 124 of file default-simulator-impl.h.
Referenced by DefaultSimulatorImpl(), IsExpired(), and ProcessOneEvent().
m_destroyEvents
DestroyEvents ns3::DefaultSimulatorImpl::m_destroyEvents private
The container of events to run at Destroy.
Definition at line 115 of file default-simulator-impl.h.
Referenced by Destroy(), IsExpired(), Remove(), and ScheduleDestroy().
m_eventCount
uint64_t ns3::DefaultSimulatorImpl::m_eventCount private
The event count.
Definition at line 130 of file default-simulator-impl.h.
Referenced by DefaultSimulatorImpl(), GetEventCount(), and ProcessOneEvent().
m_events
Ptr<Scheduler> ns3::DefaultSimulatorImpl::m_events private
The event priority queue.
Definition at line 119 of file default-simulator-impl.h.
Referenced by DoDispose(), IsFinished(), ProcessEventsWithContext(), ProcessOneEvent(), Remove(), Run(), Schedule(), ScheduleNow(), ScheduleWithContext(), and SetScheduler().
m_eventsWithContext
EventsWithContext ns3::DefaultSimulatorImpl::m_eventsWithContext private
The container of events from a different context.
Definition at line 103 of file default-simulator-impl.h.
Referenced by ProcessEventsWithContext(), and ScheduleWithContext().
m_eventsWithContextEmpty
bool ns3::DefaultSimulatorImpl::m_eventsWithContextEmpty private
Flag true if all events with context have been moved to the primary event queue.
Definition at line 108 of file default-simulator-impl.h.
Referenced by DefaultSimulatorImpl(), ProcessEventsWithContext(), and ScheduleWithContext().
m_eventsWithContextMutex
SystemMutex ns3::DefaultSimulatorImpl::m_eventsWithContextMutex private
Mutex to control access to the list of events with context.
Definition at line 110 of file default-simulator-impl.h.
Referenced by ProcessEventsWithContext(), and ScheduleWithContext().
m_main
SystemThread::ThreadId ns3::DefaultSimulatorImpl::m_main private
Main execution thread.
Definition at line 138 of file default-simulator-impl.h.
Referenced by DefaultSimulatorImpl(), Run(), Schedule(), ScheduleDestroy(), ScheduleNow(), and ScheduleWithContext().
m_stop
bool ns3::DefaultSimulatorImpl::m_stop private
Flag calling for the end of the simulation.
Definition at line 117 of file default-simulator-impl.h.
Referenced by DefaultSimulatorImpl(), IsFinished(), Run(), and Stop().
m_uid
uint32_t ns3::DefaultSimulatorImpl::m_uid private
Next event unique id.
Definition at line 122 of file default-simulator-impl.h.
Referenced by DefaultSimulatorImpl(), ProcessEventsWithContext(), Schedule(), ScheduleDestroy(), ScheduleNow(), and ScheduleWithContext().
m_unscheduledEvents
int ns3::DefaultSimulatorImpl::m_unscheduledEvents private
Number of events that have been inserted but not yet scheduled, not counting the Destroy events; this is used for validation.
Definition at line 135 of file default-simulator-impl.h.
Referenced by DefaultSimulatorImpl(), ProcessEventsWithContext(), ProcessOneEvent(), Remove(), Run(), Schedule(), ScheduleNow(), and ScheduleWithContext().
The documentation for this class was generated from the following files:
src/core/model/default-simulator-impl.h
src/core/model/default-simulator-impl.cc