ns-3: ns3::LteRlcSpecificLteMacSapUser Class Reference
ns3::LteRlcSpecificLteMacSapUser Class Reference
LteRlcSpecificLteMacSapUser class.
Public Member Functions
LteRlcSpecificLteMacSapUser (LteRlc *rlc)
Constructor.
virtual void NotifyHarqDeliveryFailure ()
Called by the MAC to notify the RLC that an HARQ process related to this RLC instance has failed.
virtual void NotifyTxOpportunity (LteMacSapUser::TxOpportunityParameters params)
Called by the MAC to notify the RLC that the scheduler granted a transmission opportunity to this RLC instance.
virtual void ReceivePdu (LteMacSapUser::ReceivePduParameters params)
Called by the MAC to notify the RLC of the reception of a new PDU.
Public Member Functions inherited from ns3::LteMacSapUser
virtual ~LteMacSapUser ()
Private Member Functions
LteRlcSpecificLteMacSapUser ()
Private Attributes
LteRlc * m_rlc
the RLC
Detailed Description
LteRlcSpecificLteMacSapUser class.
Definition at line 36 of file lte-rlc.cc.
Constructor & Destructor Documentation
LteRlcSpecificLteMacSapUser() [1/2]
ns3::LteRlcSpecificLteMacSapUser::LteRlcSpecificLteMacSapUser (LteRlc * rlc)
Constructor.
Parameters
rlc the RLC
Definition at line 56 of file lte-rlc.cc.
LteRlcSpecificLteMacSapUser() [2/2]
ns3::LteRlcSpecificLteMacSapUser::LteRlcSpecificLteMacSapUser () private
Definition at line 61 of file lte-rlc.cc.
Member Function Documentation
NotifyHarqDeliveryFailure()
void ns3::LteRlcSpecificLteMacSapUser::NotifyHarqDeliveryFailure () virtual
Called by the MAC to notify the RLC that an HARQ process related to this RLC instance has failed.
Todo:
eventual parameters to be defined
Implements ns3::LteMacSapUser.
Definition at line 72 of file lte-rlc.cc.
References ns3::LteRlc::DoNotifyHarqDeliveryFailure(), and m_rlc.
NotifyTxOpportunity()
void ns3::LteRlcSpecificLteMacSapUser::NotifyTxOpportunity (LteMacSapUser::TxOpportunityParameters params) virtual
Called by the MAC to notify the RLC that the scheduler granted a transmission opportunity to this RLC instance.
Parameters
params the TxOpportunityParameters
Implements ns3::LteMacSapUser.
Definition at line 66 of file lte-rlc.cc.
References ns3::LteRlc::DoNotifyTxOpportunity(), m_rlc, and aloha::params.
ReceivePdu()
void ns3::LteRlcSpecificLteMacSapUser::ReceivePdu (LteMacSapUser::ReceivePduParameters params) virtual
Called by the MAC to notify the RLC of the reception of a new PDU.
Parameters
params the ReceivePduParameters
Implements ns3::LteMacSapUser.
Definition at line 78 of file lte-rlc.cc.
References ns3::LteRlc::DoReceivePdu(), m_rlc, and aloha::params.
Member Data Documentation
m_rlc
LteRlc* ns3::LteRlcSpecificLteMacSapUser::m_rlc private
the RLC
Definition at line 53 of file lte-rlc.cc.
Referenced by NotifyHarqDeliveryFailure(), NotifyTxOpportunity(), and ReceivePdu().
The documentation for this class was generated from the following file:
src/lte/model/lte-rlc.cc