ns-3: SixlowpanIphcImplTest Class Reference
SixlowpanIphcImplTest Class Reference
6LoWPAN » 6LoWPAN module tests | Test suites
6LoWPAN IPHC Test
Public Member Functions
SixlowpanIphcImplTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
void ReceivePacket (Ptr< Socket > socket, Ptr< Packet > packet, const Address &from)
Packet receive function.
void ReceivePkt (Ptr< Socket > socket)
Packet receive function.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void DoSendData (Ptr< Socket > socket, std::string to)
Send data function.
void SendData (Ptr< Socket > socket, std::string to)
Send data function.
Private Attributes
Ptr< Packet > m_receivedPacket
received packet
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
6LoWPAN IPHC Test
Definition at line 54 of file sixlowpan-iphc-test.cc.
Constructor & Destructor Documentation
SixlowpanIphcImplTest()
SixlowpanIphcImplTest::SixlowpanIphcImplTest ()
Definition at line 94 of file sixlowpan-iphc-test.cc.
Member Function Documentation
DoRun()
void SixlowpanIphcImplTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 136 of file sixlowpan-iphc-test.cc.
References ns3::Ipv6::AddAddress(), ns3::Node::AddDevice(), ns3::Ipv6::AddInterface(), ns3::Packet::CopyData(), ns3::SocketFactory::CreateSocket(), ns3::Object::GetObject(), ns3::Packet::GetSize(), ns3::InternetStackHelper::Install(), m_receivedPacket, ns3::MakeCallback(), NS_TEST_EXPECT_MSG_EQ, ReceivePkt(), ns3::Packet::RemoveAllByteTags(), SendData(), ns3::SimpleNetDevice::SetAddress(), ns3::Socket::SetAllowBroadcast(), ns3::ObjectBase::SetAttribute(), ns3::SimpleNetDevice::SetChannel(), ns3::InternetStackHelper::SetIpv4StackInstall(), ns3::SixLowPanNetDevice::SetNetDevice(), and ns3::Ipv6::SetUp().
DoSendData()
void SixlowpanIphcImplTest::DoSendData (Ptr< Socket > socket, std::string to) private
Send data function.
Parameters
socket The sending socket.
to The destination.
Definition at line 116 of file sixlowpan-iphc-test.cc.
References NS_TEST_EXPECT_MSG_EQ, and ns3::Socket::SendTo().
Referenced by SendData().
ReceivePacket()
void SixlowpanIphcImplTest::ReceivePacket (Ptr< Socket > socket, Ptr< Packet > packet, const Address & from)
Packet receive function.
Parameters
socket The receiving socket.
packet The received packet.
from The sender.
Definition at line 99 of file sixlowpan-iphc-test.cc.
References m_receivedPacket.
ReceivePkt()
void SixlowpanIphcImplTest::ReceivePkt (Ptr< Socket > socket)
Packet receive function.
Parameters
socket The receiving socket.
Definition at line 104 of file sixlowpan-iphc-test.cc.
References ns3::Socket::GetRxAvailable(), ns3::Packet::GetSize(), m_receivedPacket, max, NS_ASSERT, and ns3::Socket::Recv().
Referenced by DoRun().
SendData()
void SixlowpanIphcImplTest::SendData (Ptr< Socket > socket, std::string to) private
Send data function.
Parameters
socket The sending socket.
to The destination.
Definition at line 127 of file sixlowpan-iphc-test.cc.
References DoSendData(), ns3::Node::GetId(), ns3::Socket::GetNode(), m_receivedPacket, and ns3::Seconds().
Referenced by DoRun().
Member Data Documentation
m_receivedPacket
Ptr<Packet> SixlowpanIphcImplTest::m_receivedPacket private
received packet
Definition at line 56 of file sixlowpan-iphc-test.cc.
Referenced by DoRun(), ReceivePacket(), ReceivePkt(), and SendData().
The documentation for this class was generated from the following file:
src/sixlowpan/test/sixlowpan-iphc-test.cc