ns-3: ns3::Ns2MobilityHelper Class Reference
ns3::Ns2MobilityHelper Class Reference
Mobility
Helper class which can read ns-2 movement files and configure nodes mobility.
#include "ns2-mobility-helper.h"
Classes
class ObjectStore
a class to hold input objects internally
Public Member Functions
Ns2MobilityHelper (std::string filename)
template<typename T >
void Install (T begin, T end) const
void Install (void) const
Read the ns2 trace file and configure the movement patterns of all nodes contained in the global ns3::NodeList whose nodeId is matches the nodeId of the nodes in the trace file.
Private Member Functions
void ConfigNodesMovements (const ObjectStore &store) const
Parses ns-2 mobility file to create ns-3 mobility events.
Ptr< ConstantVelocityMobilityModel > GetMobilityModel (std::string idString, const ObjectStore &store) const
Get or create a ConstantVelocityMobilityModel corresponding to idString.
Private Attributes
std::string m_filename
filename of file containing ns-2 mobility trace
Detailed Description
Helper class which can read ns-2 movement files and configure nodes mobility.
This implementation is based on the ns2 movement documentation of ns2 as described in http://www.isi.edu/nsnam/ns/doc/node172.html
Valid trace files use the following ns2 statements:
  $node set X_ x1
  $node set Y_ y1
  $node set Z_ z1
  $ns at $time $node setdest x2 y2 speed
  $ns at $time $node set X_ x1
  $ns at $time $node set Y_ Y1
  $ns at $time $node set Z_ Z1
Note that initial position statements may also appear at the end of the mobility file like this:
  $ns at $time $node setdest x2 y2 speed
  $ns at $time $node set X_ x1
  $ns at $time $node set Y_ Y1
  $ns at $time $node set Z_ Z1
  $node set X_ x1
  $node set Y_ y1
  $node set Z_ z1
The following tools are known to support this format:
BonnMotion http://net.cs.uni-bonn.de/wg/cs/applications/bonnmotion/
SUMO http://sourceforge.net/apps/mediawiki/sumo/index.php?title=Main_Page
TraNS http://trans.epfl.ch/
See usage example in examples/mobility/ns2-mobility-trace.cc
Bug:
Rounding errors may cause movement to diverge from the mobility pattern in ns-2 (using the same trace). See https://www.nsnam.org/bugzilla/show_bug.cgi?id=1316
Definition at line 76 of file ns2-mobility-helper.h.
Constructor & Destructor Documentation
Ns2MobilityHelper()
ns3::Ns2MobilityHelper::Ns2MobilityHelper (std::string filename)
Parameters
filename filename of file which contains the ns2 movement trace.
Definition at line 185 of file ns2-mobility-helper.cc.
References anonymous_namespace{print-introspected-doxygen.cc}::file, m_filename, and NS_FATAL_ERROR.
Member Function Documentation
ConfigNodesMovements()
void ns3::Ns2MobilityHelper::ConfigNodesMovements (const ObjectStore & store) const private
Parses ns-2 mobility file to create ns-3 mobility events.
Parameters
store Object store containing ns-3 mobility models
Definition at line 215 of file ns2-mobility-helper.cc.
References ns3::ParseResult::dvals, anonymous_namespace{print-introspected-doxygen.cc}::file, GetMobilityModel(), ns3::GetNodeIdInt(), ns3::GetNodeIdString(), ns3::IsNumber(), ns3::IsSchedMobilityPos(), ns3::IsSchedSetPos(), ns3::IsSetInitialPos(), m_filename, ns3::DestinationPoint::m_finalPosition, NS_LOG_DEBUG, NS_LOG_ERROR, NS_LOG_LOGIC(), NS_LOG_WARN, ns3::ParseNs2Line(), ns3::SetInitialPosition(), ns3::SetMovement(), ns3::SetSchedPosition(), and ns3::ParseResult::tokens.
Referenced by Install().
GetMobilityModel()
Ptr< ConstantVelocityMobilityModel > ns3::Ns2MobilityHelper::GetMobilityModel (std::string idString, const ObjectStore & store) const private
Get or create a ConstantVelocityMobilityModel corresponding to idString.
Parameters
idString string name for a node
store Object store containing ns-3 mobility models
Returns
pointer to a ConstantVelocityMobilityModel
Definition at line 193 of file ns2-mobility-helper.cc.
References ns3::Ns2MobilityHelper::ObjectStore::Get().
Referenced by ConfigNodesMovements().
Install() [1/2]
template<typename T > void ns3::Ns2MobilityHelper::Install (T begin, T end) const
Parameters
begin an iterator which points to the start of the input object array.
end an iterator which points to the end of the input object array.
Read the ns2 trace file and configure the movement patterns of all input objects. Each input object is identified by a unique node id which reflects the index of the object in the input array.
Definition at line 142 of file ns2-mobility-helper.h.
References ConfigNodesMovements().
Install() [2/2]
void ns3::Ns2MobilityHelper::Install (void) const
Read the ns2 trace file and configure the movement patterns of all nodes contained in the global ns3::NodeList whose nodeId is matches the nodeId of the nodes in the trace file.
Definition at line 811 of file ns2-mobility-helper.cc.
References ns3::NodeList::Begin(), and ns3::NodeList::End().
Referenced by VanetRoutingExperiment::SetupAdhocMobilityNodes().
Member Data Documentation
m_filename
std::string ns3::Ns2MobilityHelper::m_filename private
filename of file containing ns-2 mobility trace
Definition at line 133 of file ns2-mobility-helper.h.
Referenced by Ns2MobilityHelper(), and ConfigNodesMovements().
The documentation for this class was generated from the following files:
src/mobility/helper/ns2-mobility-helper.h
src/mobility/helper/ns2-mobility-helper.cc