ns-3: ns3::QosWaveMacHelper Class Reference
ns3::QosWaveMacHelper Class Reference
WAVE module
Qos Wave Mac Helper class.
#include "wave-mac-helper.h"
Public Member Functions
QosWaveMacHelper (void)
Create a QosWaveMacHelper that is used to make life easier when working with Wifi 802.11p devices using a QOS MAC layer.
virtual ~QosWaveMacHelper (void)
Destroy a QosWaveMacHelper.
virtual void SetType (std::string type, std::string n0="", const AttributeValue &v0=EmptyAttributeValue(), std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue(), std::string n6="", const AttributeValue &v6=EmptyAttributeValue(), std::string n7="", const AttributeValue &v7=EmptyAttributeValue(), std::string n8="", const AttributeValue &v8=EmptyAttributeValue(), std::string n9="", const AttributeValue &v9=EmptyAttributeValue(), std::string n10="", const AttributeValue &v10=EmptyAttributeValue())
Public Member Functions inherited from ns3::WifiMacHelper
WifiMacHelper ()
Create a WifiMacHelper to make life easier for people who want to work with Wifi MAC layers.
virtual ~WifiMacHelper ()
Destroy a WifiMacHelper.
virtual Ptr< WifiMac > Create (Ptr< NetDevice > device) const
Static Public Member Functions
static QosWaveMacHelper Default (void)
Create a mac helper in a default working state.
Additional Inherited Members
Protected Attributes inherited from ns3::WifiMacHelper
ObjectFactory m_mac
MAC object factory.
Detailed Description
Qos Wave Mac Helper class.
Definition at line 102 of file wave-mac-helper.h.
Constructor & Destructor Documentation
QosWaveMacHelper()
ns3::QosWaveMacHelper::QosWaveMacHelper (void)
Create a QosWaveMacHelper that is used to make life easier when working with Wifi 802.11p devices using a QOS MAC layer.
Definition at line 81 of file wave-mac-helper.cc.
~QosWaveMacHelper()
ns3::QosWaveMacHelper::~QosWaveMacHelper (void) virtual
Destroy a QosWaveMacHelper.
Definition at line 84 of file wave-mac-helper.cc.
Member Function Documentation
Default()
QosWaveMacHelper ns3::QosWaveMacHelper::Default (void) static
Create a mac helper in a default working state.
Definition at line 88 of file wave-mac-helper.cc.
References SetType().
Referenced by WaveNetDeviceExample::CreateWaveNodes().
SetType()
void ns3::QosWaveMacHelper::SetType (std::string type, std::string n0 = "", const AttributeValue & v0 = EmptyAttributeValue (), std::string n1 = "", const AttributeValue & v1 = EmptyAttributeValue (), std::string n2 = "", const AttributeValue & v2 = EmptyAttributeValue (), std::string n3 = "", const AttributeValue & v3 = EmptyAttributeValue (), std::string n4 = "", const AttributeValue & v4 = EmptyAttributeValue (), std::string n5 = "", const AttributeValue & v5 = EmptyAttributeValue (), std::string n6 = "", const AttributeValue & v6 = EmptyAttributeValue (), std::string n7 = "", const AttributeValue & v7 = EmptyAttributeValue (), std::string n8 = "", const AttributeValue & v8 = EmptyAttributeValue (), std::string n9 = "", const AttributeValue & v9 = EmptyAttributeValue (), std::string n10 = "", const AttributeValue & v10 = EmptyAttributeValue ()) virtual
Parameters
type the type of ns3::WifiMac to create.
n0 the name of the attribute to set
v0 the value of the attribute to set
n1 the name of the attribute to set
v1 the value of the attribute to set
n2 the name of the attribute to set
v2 the value of the attribute to set
n3 the name of the attribute to set
v3 the value of the attribute to set
n4 the name of the attribute to set
v4 the value of the attribute to set
n5 the name of the attribute to set
v5 the value of the attribute to set
n6 the name of the attribute to set
v6 the value of the attribute to set
n7 the name of the attribute to set
v7 the value of the attribute to set
n8 the value of the attribute to set
v8 the value of the attribute to set
n9 the value of the attribute to set
v9 the value of the attribute to set
n10 the value of the attribute to set
v10 the value of the attribute to set
All the attributes specified in this method should exist in the requested mac.
note: Here we require users set type with OcbWifiMac or its subclass, otherwise it will become error
Reimplemented from ns3::WifiMacHelper.
Definition at line 101 of file wave-mac-helper.cc.
References NS_FATAL_ERROR, and ns3::WifiMacHelper::SetType().
Referenced by Default().
The documentation for this class was generated from the following files:
src/wave/helper/wave-mac-helper.h
src/wave/helper/wave-mac-helper.cc