ns-3: ns3::TcpOptionTS Class Reference
ns3::TcpOptionTS Class Reference
Internet » TCP
#include "tcp-option-ts.h"
Public Member Functions
TcpOptionTS ()
virtual ~TcpOptionTS ()
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the Option from a buffer iterator.
uint32_t GetEcho (void) const
Get the timestamp echo stored in the Option.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint8_t GetKind (void) const
Get the ‘kind’ (as in RFC 793) of this option.
virtual uint32_t GetSerializedSize (void) const
Returns number of bytes required for Option serialization.
uint32_t GetTimestamp (void) const
Get the timestamp stored in the Option.
virtual void Print (std::ostream &os) const
Print the Option contents.
virtual void Serialize (Buffer::Iterator start) const
Serialize the Option to a buffer iterator.
void SetEcho (uint32_t ts)
Set the timestamp echo stored in the Option.
void SetTimestamp (uint32_t ts)
Set the timestamp stored in the Option.
Public Member Functions inherited from ns3::TcpOption
TcpOption ()
virtual ~TcpOption ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static Time ElapsedTimeFromTsValue (uint32_t echoTime)
Estimate the Time elapsed from a TS echo value.
static TypeId GetTypeId (void)
Get the type ID.
static uint32_t NowToTsValue ()
Return an uint32_t value which represent "now".
Static Public Member Functions inherited from ns3::TcpOption
static Ptr< TcpOption > CreateOption (uint8_t kind)
Creates an option.
static TypeId GetTypeId (void)
Get the type ID.
static bool IsKindKnown (uint8_t kind)
Check if the option is implemented.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Attributes
uint32_t m_echo
echo timestamp
uint32_t m_timestamp
local timestamp
Additional Inherited Members
Public Types inherited from ns3::TcpOption
enum Kind {
END = 0, NOP = 1, MSS = 2, WINSCALE = 3,
SACKPERMITTED = 4, SACK = 5, TS = 8, UNKNOWN = 255
}
The option Kind, as defined in the respective RFCs.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Defines the TCP option of kind 8 (timestamp option) as in RFC 1323
Definition at line 35 of file tcp-option-ts.h.
Constructor & Destructor Documentation
TcpOptionTS()
ns3::TcpOptionTS::TcpOptionTS ()
Definition at line 30 of file tcp-option-ts.cc.
~TcpOptionTS()
ns3::TcpOptionTS::~TcpOptionTS () virtual
Definition at line 37 of file tcp-option-ts.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::TcpOptionTS::Deserialize (Buffer::Iterator start) virtual
Deserialize the Option from a buffer iterator.
Parameters
start the buffer iterator
Returns
the number of deserialized bytes
Implements ns3::TcpOption.
Definition at line 81 of file tcp-option-ts.cc.
References GetKind(), GetSerializedSize(), m_echo, m_timestamp, NS_LOG_WARN, ns3::Buffer::Iterator::ReadNtohU32(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
Referenced by TcpOptionTSTestCase::TestDeserialize().
ElapsedTimeFromTsValue()
Time ns3::TcpOptionTS::ElapsedTimeFromTsValue (uint32_t echoTime) static
Estimate the Time elapsed from a TS echo value.
The echoTime should be a value returned from NowToTsValue.
Parameters
echoTime Echoed value from other side
See also
NowToTsValue
Returns
The measured RTT
Definition at line 144 of file tcp-option-ts.cc.
References ns3::Time::GetMilliSeconds(), ns3::MilliSeconds(), ns3::Simulator::Now(), and ns3::Seconds().
Referenced by ns3::TcpSocketBase::EstimateRtt().
GetEcho()
uint32_t ns3::TcpOptionTS::GetEcho (void) const
Get the timestamp echo stored in the Option.
Returns
the timestamp echo
Definition at line 116 of file tcp-option-ts.cc.
References m_echo.
Referenced by TcpOptionTSTestCase::TestDeserialize(), and TcpOptionTSTestCase::TestSerialize().
GetInstanceTypeId()
TypeId ns3::TcpOptionTS::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Reimplemented from ns3::TcpOption.
Definition at line 53 of file tcp-option-ts.cc.
References GetTypeId().
GetKind()
uint8_t ns3::TcpOptionTS::GetKind (void) const virtual
Get the ‘kind’ (as in RFC 793) of this option.
Returns
the Option Kind
Implements ns3::TcpOption.
Definition at line 104 of file tcp-option-ts.cc.
References ns3::TcpOption::TS.
Referenced by Deserialize(), and Serialize().
GetSerializedSize()
uint32_t ns3::TcpOptionTS::GetSerializedSize (void) const virtual
Returns number of bytes required for Option serialization.
Returns
number of bytes required for Option serialization
Implements ns3::TcpOption.
Definition at line 65 of file tcp-option-ts.cc.
Referenced by Deserialize(), and TcpOptionTSTestCase::TestSerialize().
GetTimestamp()
uint32_t ns3::TcpOptionTS::GetTimestamp (void) const
Get the timestamp stored in the Option.
Returns
the timestamp
Definition at line 110 of file tcp-option-ts.cc.
References m_timestamp.
Referenced by TcpOptionTSTestCase::TestDeserialize(), and TcpOptionTSTestCase::TestSerialize().
GetTypeId()
TypeId ns3::TcpOptionTS::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 42 of file tcp-option-ts.cc.
References ns3::TypeId::SetParent().
Referenced by ns3::TcpOption::CreateOption(), and GetInstanceTypeId().
NowToTsValue()
uint32_t ns3::TcpOptionTS::NowToTsValue () static
Return an uint32_t value which represent "now".
The value returned is usually used as Timestamp option for the TCP header; when the value will be echoed back, calculating the RTT will be an easy matter.
The RFC does not mention any units for this value; following what is implemented in OS, we use milliseconds. Any change to this must be reflected to EstimateRttFromTs.
See also
EstimateRttFromTs
Returns
The Timestamp value to use
Definition at line 134 of file tcp-option-ts.cc.
References ns3::Time::GetMilliSeconds(), and ns3::Simulator::Now().
Referenced by ns3::TcpSocketBase::AddOptionTimestamp().
Print()
void ns3::TcpOptionTS::Print (std::ostream & os) const virtual
Print the Option contents.
Parameters
os the output stream
Implements ns3::TcpOption.
Definition at line 59 of file tcp-option-ts.cc.
References m_echo, and m_timestamp.
Serialize()
void ns3::TcpOptionTS::Serialize (Buffer::Iterator start) const virtual
Serialize the Option to a buffer iterator.
Parameters
start the buffer iterator
Implements ns3::TcpOption.
Definition at line 71 of file tcp-option-ts.cc.
References GetKind(), m_echo, m_timestamp, visualizer.core::start(), ns3::Buffer::Iterator::WriteHtonU32(), and ns3::Buffer::Iterator::WriteU8().
Referenced by TcpOptionTSTestCase::TestSerialize().
SetEcho()
void ns3::TcpOptionTS::SetEcho (uint32_t ts)
Set the timestamp echo stored in the Option.
Parameters
ts the timestamp echo
Definition at line 128 of file tcp-option-ts.cc.
References m_echo.
Referenced by TcpOptionTSTestCase::TestSerialize().
SetTimestamp()
void ns3::TcpOptionTS::SetTimestamp (uint32_t ts)
Set the timestamp stored in the Option.
Parameters
ts the timestamp
Definition at line 122 of file tcp-option-ts.cc.
References m_timestamp.
Referenced by TcpOptionTSTestCase::TestSerialize().
Member Data Documentation
m_echo
uint32_t ns3::TcpOptionTS::m_echo protected
echo timestamp
Definition at line 105 of file tcp-option-ts.h.
Referenced by Deserialize(), GetEcho(), Print(), Serialize(), and SetEcho().
m_timestamp
uint32_t ns3::TcpOptionTS::m_timestamp protected
local timestamp
Definition at line 104 of file tcp-option-ts.h.
Referenced by Deserialize(), GetTimestamp(), Print(), Serialize(), and SetTimestamp().
The documentation for this class was generated from the following files:
src/internet/model/tcp-option-ts.h
src/internet/model/tcp-option-ts.cc