ns-3: ns3::RrpaaWifiManager Class Reference
ns3::RrpaaWifiManager Class Reference
#include "rrpaa-wifi-manager.h"
Public Member Functions
RrpaaWifiManager ()
virtual ~RrpaaWifiManager ()
int64_t AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
virtual void SetupMac (const Ptr< WifiMac > mac)
Set up MAC associated with this device since it is the object that knows the full set of timing parameters (e.g.
virtual void SetupPhy (const Ptr< WifiPhy > phy)
Set up PHY associated with this device since it is the object that knows the full set of transmit rates that are supported.
Public Member Functions inherited from ns3::WifiRemoteStationManager
WifiRemoteStationManager ()
virtual ~WifiRemoteStationManager ()
void AddAllSupportedMcs (Mac48Address address)
Invoked in a STA or AP to store all of the MCS supported by a destination which is also supported locally.
void AddAllSupportedModes (Mac48Address address)
Invoked in a STA or AP to store all of the modes supported by a destination which is also supported locally.
void AddBasicMcs (WifiMode mcs)
Add a given Modulation and Coding Scheme (MCS) index to the set of basic MCS.
void AddBasicMode (WifiMode mode)
Invoked in a STA upon association to store the set of rates which belong to the BSSBasicRateSet of the associated AP and which are supported locally.
void AddStationHeCapabilities (Mac48Address from, HeCapabilities heCapabilities)
Records HE capabilities of the remote station.
void AddStationHtCapabilities (Mac48Address from, HtCapabilities htCapabilities)
Records HT capabilities of the remote station.
void AddStationVhtCapabilities (Mac48Address from, VhtCapabilities vhtCapabilities)
Records VHT capabilities of the remote station.
void AddSupportedErpSlotTime (Mac48Address address, bool isShortSlotTimeSupported)
Record whether the short ERP slot time is supported by the station.
void AddSupportedMcs (Mac48Address address, WifiMode mcs)
Record the MCS index supported by the station.
void AddSupportedMode (Mac48Address address, WifiMode mode)
Invoked in a STA or AP to store the set of modes supported by a destination which is also supported locally.
void AddSupportedPhyPreamble (Mac48Address address, bool isShortPreambleSupported)
Record whether the short PHY preamble is supported by the station.
WifiTxVector DoGetCtsToSelfTxVector (void)
Since CTS-to-self parameters are not dependent on the station, it is implemented in wifi remote station manager.
WifiMode GetBasicMcs (uint8_t i) const
Return the MCS at the given list index.
WifiMode GetBasicMode (uint8_t i) const
Return a basic mode from the set of basic modes.
uint16_t GetChannelWidthSupported (Mac48Address address) const
Return the channel width supported by the station.
WifiTxVector GetCtsToSelfTxVector (const WifiMacHeader *header, Ptr< const Packet > packet)
WifiTxVector GetDataTxVector (Mac48Address address, const WifiMacHeader *header, Ptr< const Packet > packet)
WifiMode GetDefaultMcs (void) const
Return the default Modulation and Coding Scheme (MCS) index.
WifiMode GetDefaultMode (void) const
Return the default transmission mode.
uint8_t GetDefaultTxPowerLevel (void) const
uint32_t GetFragmentationThreshold (void) const
Return the fragmentation threshold.
uint32_t GetFragmentOffset (Mac48Address address, const WifiMacHeader *header, Ptr< const Packet > packet, uint32_t fragmentNumber)
uint32_t GetFragmentSize (Mac48Address address, const WifiMacHeader *header, Ptr< const Packet > packet, uint32_t fragmentNumber)
bool GetGreenfieldSupported (Mac48Address address) const
Return whether the station supports Greenfield or not.
bool GetGreenfieldSupported (void) const
Return whether the device has HT Greenfield support enabled.
uint16_t GetGuardInterval (void) const
Return the supported HE guard interval duration (in nanoseconds).
bool GetHeSupported (Mac48Address address) const
Return whether the station supports HE or not.
bool GetHeSupported (void) const
Return whether the device has HE capability support enabled.
bool GetHtSupported (Mac48Address address) const
Return whether the station supports HT or not.
bool GetHtSupported (void) const
Return whether the device has HT capability support enabled.
WifiRemoteStationInfo GetInfo (Mac48Address address)
uint8_t GetMaxNumberOfTransmitStreams (void) const
uint8_t GetNBasicMcs (void) const
Return the number of basic MCS index.
uint8_t GetNBasicModes (void) const
Return the number of basic modes we support.
uint8_t GetNMcsSupported (Mac48Address address) const
Return the number of MCS supported by the station.
uint32_t GetNNonErpBasicModes (void) const
Return the number of non-ERP basic modes we support.
WifiMode GetNonErpBasicMode (uint8_t i) const
Return a basic mode from the set of basic modes that is not an ERP mode.
WifiMode GetNonUnicastMode (void) const
Return a mode for non-unicast packets.
uint8_t GetNumberOfAntennas (void) const
uint8_t GetNumberOfSupportedStreams (Mac48Address address) const
Return the number of spatial streams supported by the station.
bool GetPcfSupported (void) const
Return whether the device has PCF capability support enabled.
bool GetQosSupported (Mac48Address address) const
Return whether the given station is QoS capable.
bool GetRifsPermitted (void) const
Return whether the device can use RIFS.
WifiTxVector GetRtsTxVector (Mac48Address address, Ptr< const Packet > packet)
bool GetShortGuardIntervalSupported (Mac48Address address) const
Return whether the station supports HT/VHT short guard interval.
bool GetShortGuardIntervalSupported (void) const
Return whether the device has SGI support enabled.
bool GetShortPreambleEnabled (void) const
Return whether the device uses short PHY preambles.
bool GetShortPreambleSupported (Mac48Address address) const
Return whether the station supports short PHY preamble or not.
bool GetShortSlotTimeEnabled (void) const
Return whether the device uses short slot time.
bool GetShortSlotTimeSupported (Mac48Address address) const
Return whether the station supports short ERP slot time or not.
Ptr< const HeCapabilities > GetStationHeCapabilities (Mac48Address from)
Return the HE capabilities sent by the remote station.
Ptr< const HtCapabilities > GetStationHtCapabilities (Mac48Address from)
Return the HT capabilities sent by the remote station.
Ptr< const VhtCapabilities > GetStationVhtCapabilities (Mac48Address from)
Return the VHT capabilities sent by the remote station.
bool GetUseGreenfieldProtection (void) const
Return whether protection for stations that do not support HT Greenfield format is enabled.
bool GetUseNonErpProtection (void) const
Return whether the device supports protection of non-ERP stations.
bool GetUseNonHtProtection (void) const
Return whether the device supports protection of non-HT stations.
bool GetVhtSupported (Mac48Address address) const
Return whether the station supports VHT or not.
bool GetVhtSupported (void) const
Return whether the device has VHT capability support enabled.
bool IsAssociated (Mac48Address address) const
Return whether the station associated.
bool IsBrandNew (Mac48Address address) const
Return whether the station state is brand new.
bool IsLastFragment (Mac48Address address, const WifiMacHeader *header, Ptr< const Packet > packet, uint32_t fragmentNumber)
bool IsWaitAssocTxOk (Mac48Address address) const
Return whether we are waiting for an ACK for the association response we sent.
bool NeedCtsToSelf (WifiTxVector txVector)
Return if we need to do CTS-to-self before sending a DATA.
bool NeedFragmentation (Mac48Address address, const WifiMacHeader *header, Ptr< const Packet > packet)
bool NeedRetransmission (Mac48Address address, const WifiMacHeader *header, Ptr< const Packet > packet)
bool NeedRts (const WifiMacHeader *header, Ptr< const Packet > packet)
void PrepareForQueue (Mac48Address address, Ptr< const Packet > packet)
void RecordDisassociated (Mac48Address address)
Records that the STA was disassociated.
void RecordGotAssocTxFailed (Mac48Address address)
Records that we missed an ACK for the association response we sent.
void RecordGotAssocTxOk (Mac48Address address)
Records that we got an ACK for the association response we sent.
void RecordWaitAssocTxOk (Mac48Address address)
Records that we are waiting for an ACK for the association response we sent.
void RemoveAllSupportedMcs (Mac48Address address)
Invoked in a STA or AP to delete all of the supported MCS by a destination.
void ReportAmpduTxStatus (Mac48Address address, uint8_t nSuccessfulMpdus, uint8_t nFailedMpdus, double rxSnr, double dataSnr)
Typically called per A-MPDU, either when a Block ACK was successfully received or when a BlockAckTimeout has elapsed.
void ReportDataFailed (Mac48Address address, const WifiMacHeader *header, uint32_t packetSize)
Should be invoked whenever the AckTimeout associated to a transmission attempt expires.
void ReportDataOk (Mac48Address address, const WifiMacHeader *header, double ackSnr, WifiMode ackMode, double dataSnr, uint32_t packetSize)
Should be invoked whenever we receive the ACK associated to a data packet we just sent.
void ReportFinalDataFailed (Mac48Address address, const WifiMacHeader *header, uint32_t packetSize)
Should be invoked after calling ReportDataFailed if NeedRetransmission returns false.
void ReportFinalRtsFailed (Mac48Address address, const WifiMacHeader *header)
Should be invoked after calling ReportRtsFailed if NeedRetransmission returns false.
void ReportRtsFailed (Mac48Address address, const WifiMacHeader *header)
Should be invoked whenever the RtsTimeout associated to a transmission attempt expires.
void ReportRtsOk (Mac48Address address, const WifiMacHeader *header, double ctsSnr, WifiMode ctsMode, double rtsSnr)
Should be invoked whenever we receive the CTS associated to an RTS we just sent.
void ReportRxOk (Mac48Address address, double rxSnr, WifiMode txMode)
void Reset (void)
Reset the station, invoked in a STA upon dis-association or in an AP upon reboot.
void SetDefaultTxPowerLevel (uint8_t txPower)
Set the default transmission power level.
void SetFragmentationThreshold (uint32_t threshold)
Sets a fragmentation threshold.
void SetMaxSlrc (uint32_t maxSlrc)
Sets the maximum STA long retry count (SLRC).
void SetMaxSsrc (uint32_t maxSsrc)
Sets the maximum STA short retry count (SSRC).
void SetPcfSupported (bool enable)
Enable or disable PCF capability support.
void SetQosSupport (Mac48Address from, bool qosSupported)
Records QoS support of the remote station.
void SetRifsPermitted (bool allow)
Permit or prohibit RIFS.
void SetRtsCtsThreshold (uint32_t threshold)
Sets the RTS threshold.
void SetShortPreambleEnabled (bool enable)
Enable or disable short PHY preambles.
void SetShortSlotTimeEnabled (bool enable)
Enable or disable short slot time.
void SetUseGreenfieldProtection (bool enable)
Enable or disable protection for stations that do not support HT Greenfield format.
void SetUseNonErpProtection (bool enable)
Enable or disable protection for non-ERP stations.
void SetUseNonHtProtection (bool enable)
Enable or disable protection for non-HT stations.
void UpdateFragmentationThreshold (void)
Typically called to update the fragmentation threshold at the start of a new transmission.
bool UseGreenfieldForDestination (Mac48Address dest) const
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::WifiRemoteStationManager
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Types
typedef std::vector< std::pair< Time, WifiMode > > TxTime
typedef for a vector of a pair of Time, WifiMode.
Private Member Functions
void AddCalcTxTime (WifiMode mode, Time t)
Add transmission time for the given mode to an internal list.
void CheckInit (RrpaaWifiRemoteStation *station)
Check for initializations.
void CheckTimeout (RrpaaWifiRemoteStation *station)
Check if the counter should be reset.
virtual WifiRemoteStation * DoCreateStation (void) const
virtual WifiTxVector DoGetDataTxVector (WifiRemoteStation *station)
virtual WifiTxVector DoGetRtsTxVector (WifiRemoteStation *station)
void DoInitialize (void)
Initialize() implementation.
virtual bool DoNeedRts (WifiRemoteStation *st, Ptr< const Packet > packet, bool normally)
virtual void DoReportDataFailed (WifiRemoteStation *station)
This method is a pure virtual method that must be implemented by the sub-class.
virtual void DoReportDataOk (WifiRemoteStation *station, double ackSnr, WifiMode ackMode, double dataSnr)
This method is a pure virtual method that must be implemented by the sub-class.
virtual void DoReportFinalDataFailed (WifiRemoteStation *station)
This method is a pure virtual method that must be implemented by the sub-class.
virtual void DoReportFinalRtsFailed (WifiRemoteStation *station)
This method is a pure virtual method that must be implemented by the sub-class.
virtual void DoReportRtsFailed (WifiRemoteStation *station)
This method is a pure virtual method that must be implemented by the sub-class.
virtual void DoReportRtsOk (WifiRemoteStation *station, double ctsSnr, WifiMode ctsMode, double rtsSnr)
This method is a pure virtual method that must be implemented by the sub-class.
virtual void DoReportRxOk (WifiRemoteStation *station, double rxSnr, WifiMode txMode)
This method is a pure virtual method that must be implemented by the sub-class.
Time GetCalcTxTime (WifiMode mode) const
Get the estimated TxTime of a packet with a given mode.
WifiRrpaaThresholds GetThresholds (RrpaaWifiRemoteStation *station, uint8_t index) const
Get the thresholds for the given station and mode index.
WifiRrpaaThresholds GetThresholds (RrpaaWifiRemoteStation *station, WifiMode mode) const
Get the thresholds for the given station and mode.
void InitThresholds (RrpaaWifiRemoteStation *station)
Initialize the thresholds internal list for the given station.
virtual bool IsLowLatency (void) const
void ResetCountersBasic (RrpaaWifiRemoteStation *station)
Reset the counters of the given station.
void RunAdaptiveRtsAlgorithm (RrpaaWifiRemoteStation *station)
Run an enhanced algorithm which activates the use of RTS for the given station if the conditions are met.
void RunBasicAlgorithm (RrpaaWifiRemoteStation *station)
Find an appropriate rate and power for the given station, using a basic algorithm.
Private Attributes
uint32_t m_ackLength
Ack frame length used for calculate mode TxTime (in bytes).
double m_alpha
Alpha value for RRPAA (value for calculating MTL threshold)
bool m_basic
If using the basic algorithm (without RTS/CTS).
double m_beta
Beta value for RRPAA (value for calculating ORI threshold).
TxTime m_calcTxTime
To hold all the calculated TxTime for all modes.
double m_delta
Delta value for RRPAA (value for pdTable increments).
Time m_difs
Value of DIFS configured in the device.
uint32_t m_frameLength
Data frame length used for calculate mode TxTime (in bytes).
double m_gamma
Gamma value for RRPAA (value for pdTable decrements).
uint8_t m_maxPowerLevel
Maximal power level.
uint8_t m_minPowerLevel
Differently form rate, power levels do not depend on the remote station.
uint8_t m_nPowerLevels
Number of power levels.
TracedCallback< double, double, Mac48Address > m_powerChange
The trace source fired when the transmission power change.
TracedCallback< DataRate, DataRate, Mac48Address > m_rateChange
The trace source fired when the transmission rate change.
Time m_sifs
Value of SIFS configured in the device.
double m_tau
Tau value for RRPAA (value for calculating EWND size).
Time m_timeout
Timeout for the RRAA BASIC loss estimation block.
Ptr< UniformRandomVariable > m_uniformRandomVariable
Provides uniform random variables for probabilistic changes.
Additional Inherited Members
Public Types inherited from ns3::WifiRemoteStationManager
typedef void(* PowerChangeTracedCallback) (double oldPower, double newPower, Mac48Address remoteAddress)
TracedCallback signature for power change events.
enum ProtectionMode { RTS_CTS, CTS_TO_SELF }
ProtectionMode enumeration.
typedef void(* RateChangeTracedCallback) (DataRate oldRate, DataRate newRate, Mac48Address remoteAddress)
TracedCallback signature for rate change events.
typedef std::vector< WifiRemoteStation * > Stations
A vector of WifiRemoteStations.
typedef std::vector< WifiRemoteStationState * > StationStates
A vector of WifiRemoteStationStates.
Protected Member Functions inherited from ns3::WifiRemoteStationManager
virtual void DoDispose (void)
Destructor implementation.
Mac48Address GetAddress (const WifiRemoteStation *station) const
Return the address of the station.
bool GetAggregation (const WifiRemoteStation *station) const
Return whether the given station supports A-MPDU.
uint16_t GetChannelWidth (const WifiRemoteStation *station) const
Return the channel width supported by the station.
bool GetGreenfield (const WifiRemoteStation *station) const
Return whether the station supports Greenfield or not.
uint16_t GetGuardInterval (const WifiRemoteStation *station) const
Return the HE guard interval duration supported by the station.
bool GetHeSupported (const WifiRemoteStation *station) const
Return whether the given station is HE capable.
bool GetHtSupported (const WifiRemoteStation *station) const
Return whether the given station is HT capable.
Ptr< WifiMac > GetMac (void) const
Return the WifiMac.
WifiMode GetMcsSupported (const WifiRemoteStation *station, uint8_t i) const
Return the WifiMode supported by the specified station at the specified index.
uint8_t GetNess (const WifiRemoteStation *station) const
uint8_t GetNMcsSupported (const WifiRemoteStation *station) const
Return the number of MCS supported by the given station.
uint32_t GetNNonErpSupported (const WifiRemoteStation *station) const
Return the number of non-ERP modes supported by the given station.
WifiMode GetNonErpSupported (const WifiRemoteStation *station, uint8_t i) const
Return whether non-ERP mode associated with the specified station at the specified index.
uint8_t GetNSupported (const WifiRemoteStation *station) const
Return the number of modes supported by the given station.
uint8_t GetNumberOfSupportedStreams (const WifiRemoteStation *station) const
Return the number of supported streams the station has.
Ptr< WifiPhy > GetPhy (void) const
Return the WifiPhy.
bool GetQosSupported (const WifiRemoteStation *station) const
Return whether the given station is QoS capable.
bool GetShortGuardIntervalSupported (const WifiRemoteStation *station) const
Return whether the given station supports HT/VHT short guard interval.
WifiMode GetSupported (const WifiRemoteStation *station, uint8_t i) const
Return whether mode associated with the specified station at the specified index.
bool GetVhtSupported (const WifiRemoteStation *station) const
Return whether the given station is VHT capable.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 74 of file rrpaa-wifi-manager.h.
Member Typedef Documentation
TxTime
typedef std::vector<std::pair<Time,WifiMode> > ns3::RrpaaWifiManager::TxTime private
typedef for a vector of a pair of Time, WifiMode.
Essentially a list for WifiMode and its corresponding transmission time to transmit a reference packet.
Definition at line 201 of file rrpaa-wifi-manager.h.
Constructor & Destructor Documentation
RrpaaWifiManager()
ns3::RrpaaWifiManager::RrpaaWifiManager ()
Definition at line 128 of file rrpaa-wifi-manager.cc.
References m_uniformRandomVariable, and NS_LOG_FUNCTION.
~RrpaaWifiManager()
ns3::RrpaaWifiManager::~RrpaaWifiManager () virtual
Definition at line 134 of file rrpaa-wifi-manager.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddCalcTxTime()
void ns3::RrpaaWifiManager::AddCalcTxTime (WifiMode mode, Time t) private
Add transmission time for the given mode to an internal list.
Parameters
mode the WifiMode
t transmission time
Definition at line 213 of file rrpaa-wifi-manager.cc.
References m_calcTxTime, and NS_LOG_FUNCTION.
Referenced by SetupPhy().
AssignStreams()
int64_t ns3::RrpaaWifiManager::AssignStreams (int64_t stream)
Assign a fixed random variable stream number to the random variables used by this model.
Return the number of streams (possibly zero) that have been assigned.
Parameters
stream first stream index to use
Returns
the number of stream indices assigned by this model
Definition at line 140 of file rrpaa-wifi-manager.cc.
References m_uniformRandomVariable, NS_LOG_FUNCTION, and ns3::RandomVariableStream::SetStream().
CheckInit()
void ns3::RrpaaWifiManager::CheckInit (RrpaaWifiRemoteStation * station) private
Check for initializations.
Parameters
station the remote station.
Definition at line 249 of file rrpaa-wifi-manager.cc.
References ns3::WifiRemoteStationManager::GetChannelWidth(), ns3::WifiMode::GetDataRate(), ns3::WifiRemoteStationManager::GetNSupported(), ns3::WifiRemoteStationManager::GetPhy(), ns3::WifiPhy::GetPowerDbm(), ns3::WifiRemoteStationManager::GetSupported(), InitThresholds(), ns3::WifiRemoteStationState::m_address, ns3::RrpaaWifiRemoteStation::m_initialized, m_maxPowerLevel, m_nPowerLevels, ns3::RrpaaWifiRemoteStation::m_nRate, ns3::RrpaaWifiRemoteStation::m_pdTable, m_powerChange, ns3::RrpaaWifiRemoteStation::m_powerLevel, ns3::RrpaaWifiRemoteStation::m_prevPowerLevel, ns3::RrpaaWifiRemoteStation::m_prevRateIndex, m_rateChange, ns3::RrpaaWifiRemoteStation::m_rateIndex, ns3::WifiRemoteStation::m_state, ns3::RrpaaWifiRemoteStation::m_thresholds, NS_LOG_DEBUG, NS_LOG_FUNCTION, and ResetCountersBasic().
Referenced by DoGetDataTxVector(), DoNeedRts(), DoReportDataFailed(), and DoReportDataOk().
CheckTimeout()
void ns3::RrpaaWifiManager::CheckTimeout (RrpaaWifiRemoteStation * station) private
Check if the counter should be reset.
Parameters
station the remote station
Definition at line 459 of file rrpaa-wifi-manager.cc.
References ns3::RrpaaWifiRemoteStation::m_counter, ns3::RrpaaWifiRemoteStation::m_lastReset, m_timeout, ns3::Simulator::Now(), NS_LOG_FUNCTION, and ResetCountersBasic().
Referenced by DoReportDataFailed(), and DoReportDataOk().
DoCreateStation()
WifiRemoteStation * ns3::RrpaaWifiManager::DoCreateStation (void) const private virtual
Returns
a new station data structure
Implements ns3::WifiRemoteStationManager.
Definition at line 236 of file rrpaa-wifi-manager.cc.
References ns3::RrpaaWifiRemoteStation::m_adaptiveRtsOn, ns3::RrpaaWifiRemoteStation::m_adaptiveRtsWnd, ns3::RrpaaWifiRemoteStation::m_initialized, ns3::RrpaaWifiRemoteStation::m_lastFrameFail, ns3::RrpaaWifiRemoteStation::m_rtsCounter, and NS_LOG_FUNCTION.
DoGetDataTxVector()
WifiTxVector ns3::RrpaaWifiManager::DoGetDataTxVector (WifiRemoteStation * station) private virtual
Parameters
station the station that we need to communicate
Returns
the TXVECTOR to use to send a packet to the station
Note: This method is called before sending a unicast packet or a fragment of a unicast packet to decide which transmission mode to use.
Implements ns3::WifiRemoteStationManager.
Definition at line 392 of file rrpaa-wifi-manager.cc.
References CheckInit(), ns3::WifiRemoteStationManager::GetAddress(), ns3::WifiRemoteStationManager::GetAggregation(), ns3::WifiRemoteStationManager::GetChannelWidth(), ns3::WifiMode::GetDataRate(), ns3::WifiMode::GetModulationClass(), ns3::WifiRemoteStationManager::GetPhy(), ns3::WifiPhy::GetPowerDbm(), ns3::GetPreambleForTransmission(), ns3::WifiRemoteStationManager::GetShortPreambleEnabled(), ns3::WifiRemoteStationManager::GetSupported(), ns3::WifiRemoteStationState::m_address, m_powerChange, ns3::RrpaaWifiRemoteStation::m_powerLevel, ns3::RrpaaWifiRemoteStation::m_prevPowerLevel, ns3::RrpaaWifiRemoteStation::m_prevRateIndex, m_rateChange, ns3::RrpaaWifiRemoteStation::m_rateIndex, ns3::WifiRemoteStation::m_state, NS_LOG_FUNCTION, and ns3::WifiRemoteStationManager::UseGreenfieldForDestination().
DoGetRtsTxVector()
WifiTxVector ns3::RrpaaWifiManager::DoGetRtsTxVector (WifiRemoteStation * station) private virtual
Parameters
station the station that we need to communicate
Returns
the transmission mode to use to send an RTS to the station
Note: This method is called before sending an RTS to a station to decide which transmission mode to use for the RTS.
Implements ns3::WifiRemoteStationManager.
Definition at line 420 of file rrpaa-wifi-manager.cc.
References ns3::WifiRemoteStationManager::GetAddress(), ns3::WifiRemoteStationManager::GetAggregation(), ns3::WifiRemoteStationManager::GetChannelWidth(), ns3::WifiRemoteStationManager::GetDefaultTxPowerLevel(), ns3::WifiMode::GetModulationClass(), ns3::WifiRemoteStationManager::GetNonErpSupported(), ns3::GetPreambleForTransmission(), ns3::WifiRemoteStationManager::GetShortPreambleEnabled(), ns3::WifiRemoteStationManager::GetSupported(), ns3::WifiRemoteStationManager::GetUseNonErpProtection(), NS_LOG_FUNCTION, and ns3::WifiRemoteStationManager::UseGreenfieldForDestination().
DoInitialize()
void ns3::RrpaaWifiManager::DoInitialize (void) private virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 180 of file rrpaa-wifi-manager.cc.
References ns3::WifiRemoteStationManager::GetHeSupported(), ns3::WifiRemoteStationManager::GetHtSupported(), ns3::WifiRemoteStationManager::GetVhtSupported(), NS_FATAL_ERROR, and NS_LOG_FUNCTION.
DoNeedRts()
bool ns3::RrpaaWifiManager::DoNeedRts (WifiRemoteStation * station, Ptr< const Packet > packet, bool normally) private virtual
Parameters
station the station that we need to communicate
packet the packet to send
normally indicates whether the normal 802.11 RTS enable mechanism would request that the RTS is sent or not.
Returns
true if we want to use an RTS/CTS handshake for this packet before sending it, false otherwise.
Note: This method is called before a unicast packet is sent on the medium.
Reimplemented from ns3::WifiRemoteStationManager.
Definition at line 444 of file rrpaa-wifi-manager.cc.
References CheckInit(), ns3::RrpaaWifiRemoteStation::m_adaptiveRtsOn, m_basic, NS_LOG_FUNCTION, and RunAdaptiveRtsAlgorithm().
DoReportDataFailed()
void ns3::RrpaaWifiManager::DoReportDataFailed (WifiRemoteStation * station) private virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that we failed to send DATA
Implements ns3::WifiRemoteStationManager.
Definition at line 342 of file rrpaa-wifi-manager.cc.
References CheckInit(), CheckTimeout(), ns3::RrpaaWifiRemoteStation::m_counter, ns3::RrpaaWifiRemoteStation::m_lastFrameFail, ns3::RrpaaWifiRemoteStation::m_nFailed, NS_LOG_FUNCTION, and RunBasicAlgorithm().
DoReportDataOk()
void ns3::RrpaaWifiManager::DoReportDataOk (WifiRemoteStation * station, double ackSnr, WifiMode ackMode, double dataSnr) private virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that we successfully sent RTS
ackSnr the SNR of the ACK we received
ackMode the WifiMode the receiver used to send the ACK
dataSnr the SNR of the DATA we sent
Implements ns3::WifiRemoteStationManager.
Definition at line 369 of file rrpaa-wifi-manager.cc.
References CheckInit(), CheckTimeout(), ns3::RrpaaWifiRemoteStation::m_counter, ns3::RrpaaWifiRemoteStation::m_lastFrameFail, NS_LOG_FUNCTION, and RunBasicAlgorithm().
DoReportFinalDataFailed()
void ns3::RrpaaWifiManager::DoReportFinalDataFailed (WifiRemoteStation * station) private virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that we failed to send DATA
Implements ns3::WifiRemoteStationManager.
Definition at line 386 of file rrpaa-wifi-manager.cc.
References NS_LOG_FUNCTION.
DoReportFinalRtsFailed()
void ns3::RrpaaWifiManager::DoReportFinalRtsFailed (WifiRemoteStation * station) private virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that we failed to send RTS
Implements ns3::WifiRemoteStationManager.
Definition at line 381 of file rrpaa-wifi-manager.cc.
References NS_LOG_FUNCTION.
DoReportRtsFailed()
void ns3::RrpaaWifiManager::DoReportRtsFailed (WifiRemoteStation * station) private virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that we failed to send RTS
Implements ns3::WifiRemoteStationManager.
Definition at line 336 of file rrpaa-wifi-manager.cc.
References NS_LOG_FUNCTION.
DoReportRtsOk()
void ns3::RrpaaWifiManager::DoReportRtsOk (WifiRemoteStation * station, double ctsSnr, WifiMode ctsMode, double rtsSnr) private virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that we successfully sent RTS
ctsSnr the SNR of the CTS we received
ctsMode the WifiMode the receiver used to send the CTS
rtsSnr the SNR of the RTS we sent
Implements ns3::WifiRemoteStationManager.
Definition at line 362 of file rrpaa-wifi-manager.cc.
References NS_LOG_FUNCTION.
DoReportRxOk()
void ns3::RrpaaWifiManager::DoReportRxOk (WifiRemoteStation * station, double rxSnr, WifiMode txMode) private virtual
This method is a pure virtual method that must be implemented by the sub-class.
This allows different types of WifiRemoteStationManager to respond differently,
Parameters
station the station that sent the DATA to us
rxSnr the SNR of the DATA we received
txMode the WifiMode the sender used to send the DATA
Implements ns3::WifiRemoteStationManager.
Definition at line 355 of file rrpaa-wifi-manager.cc.
References NS_LOG_FUNCTION.
GetCalcTxTime()
Time ns3::RrpaaWifiManager::GetCalcTxTime (WifiMode mode) const private
Get the estimated TxTime of a packet with a given mode.
Parameters
mode the WifiMode
Returns
the estimated TX time
Definition at line 198 of file rrpaa-wifi-manager.cc.
References m_calcTxTime, NS_ASSERT, NS_LOG_FUNCTION, and ns3::Seconds().
Referenced by InitThresholds().
GetThresholds() [1/2]
WifiRrpaaThresholds ns3::RrpaaWifiManager::GetThresholds (RrpaaWifiRemoteStation * station, uint8_t index) const private
Get the thresholds for the given station and mode index.
Parameters
station the remote station
index the mode index in the supported rates
Returns
the RRPAA thresholds
Definition at line 606 of file rrpaa-wifi-manager.cc.
References ns3::WifiRemoteStationManager::GetSupported(), GetThresholds(), and NS_LOG_FUNCTION.
GetThresholds() [2/2]
WifiRrpaaThresholds ns3::RrpaaWifiManager::GetThresholds (RrpaaWifiRemoteStation * station, WifiMode mode) const private
Get the thresholds for the given station and mode.
Parameters
station the remote station
mode the WifiMode
Returns
the RRPAA thresholds
Definition at line 220 of file rrpaa-wifi-manager.cc.
References ns3::RrpaaWifiRemoteStation::m_thresholds, NS_ABORT_MSG, and NS_LOG_FUNCTION.
Referenced by GetThresholds(), ResetCountersBasic(), and RunBasicAlgorithm().
GetTypeId()
TypeId ns3::RrpaaWifiManager::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 64 of file rrpaa-wifi-manager.cc.
References m_ackLength, m_alpha, m_basic, m_beta, m_delta, m_frameLength, m_gamma, m_powerChange, m_rateChange, m_tau, m_timeout, ns3::MakeBooleanAccessor(), ns3::MakeBooleanChecker(), ns3::MakeDoubleAccessor(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::MakeUintegerAccessor(), ns3::MilliSeconds(), and ns3::TypeId::SetParent().
InitThresholds()
void ns3::RrpaaWifiManager::InitThresholds (RrpaaWifiRemoteStation * station) private
Initialize the thresholds internal list for the given station.
Parameters
station the remote station
Definition at line 289 of file rrpaa-wifi-manager.cc.
References GetCalcTxTime(), ns3::Time::GetSeconds(), ns3::WifiRemoteStationManager::GetSupported(), m_alpha, m_beta, m_difs, ns3::WifiRrpaaThresholds::m_ewnd, ns3::WifiRrpaaThresholds::m_mtl, ns3::RrpaaWifiRemoteStation::m_nRate, ns3::WifiRrpaaThresholds::m_ori, m_sifs, m_tau, ns3::RrpaaWifiRemoteStation::m_thresholds, NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by CheckInit().
IsLowLatency()
bool ns3::RrpaaWifiManager::IsLowLatency (void) const private virtual
Returns
whether this manager is a manager designed to work in low-latency environments.
Note: In this context, low vs high latency is defined in IEEE 802.11 Rate Adaptation: A Practical Approach, by M. Lacage, M.H. Manshaei, and T. Turletti.
Implements ns3::WifiRemoteStationManager.
Definition at line 614 of file rrpaa-wifi-manager.cc.
ResetCountersBasic()
void ns3::RrpaaWifiManager::ResetCountersBasic (RrpaaWifiRemoteStation * station) private
Reset the counters of the given station.
Parameters
station the remote station
Definition at line 327 of file rrpaa-wifi-manager.cc.
References GetThresholds(), ns3::RrpaaWifiRemoteStation::m_counter, ns3::WifiRrpaaThresholds::m_ewnd, ns3::RrpaaWifiRemoteStation::m_lastReset, ns3::RrpaaWifiRemoteStation::m_nFailed, ns3::RrpaaWifiRemoteStation::m_rateIndex, ns3::Simulator::Now(), and NS_LOG_FUNCTION.
Referenced by CheckInit(), CheckTimeout(), and RunBasicAlgorithm().
RunAdaptiveRtsAlgorithm()
void ns3::RrpaaWifiManager::RunAdaptiveRtsAlgorithm (RrpaaWifiRemoteStation * station) private
Run an enhanced algorithm which activates the use of RTS for the given station if the conditions are met.
Parameters
station the remote station
Definition at line 579 of file rrpaa-wifi-manager.cc.
References ns3::RrpaaWifiRemoteStation::m_adaptiveRtsOn, ns3::RrpaaWifiRemoteStation::m_adaptiveRtsWnd, ns3::RrpaaWifiRemoteStation::m_lastFrameFail, ns3::RrpaaWifiRemoteStation::m_rtsCounter, and NS_LOG_FUNCTION.
Referenced by DoNeedRts().
RunBasicAlgorithm()
void ns3::RrpaaWifiManager::RunBasicAlgorithm (RrpaaWifiRemoteStation * station) private
Find an appropriate rate and power for the given station, using a basic algorithm.
Parameters
station the remote station
Definition at line 470 of file rrpaa-wifi-manager.cc.
References GetThresholds(), ns3::UniformRandomVariable::GetValue(), ns3::RrpaaWifiRemoteStation::m_counter, m_delta, ns3::WifiRrpaaThresholds::m_ewnd, m_gamma, m_maxPowerLevel, m_minPowerLevel, ns3::WifiRrpaaThresholds::m_mtl, ns3::RrpaaWifiRemoteStation::m_nFailed, ns3::RrpaaWifiRemoteStation::m_nRate, ns3::WifiRrpaaThresholds::m_ori, ns3::RrpaaWifiRemoteStation::m_pdTable, ns3::RrpaaWifiRemoteStation::m_powerLevel, ns3::RrpaaWifiRemoteStation::m_rateIndex, m_uniformRandomVariable, NS_LOG_DEBUG, NS_LOG_FUNCTION, and ResetCountersBasic().
Referenced by DoReportDataFailed(), and DoReportDataOk().
SetupMac()
void ns3::RrpaaWifiManager::SetupMac (const Ptr< WifiMac > mac) virtual
Set up MAC associated with this device since it is the object that knows the full set of timing parameters (e.g.
IFS).
Parameters
mac the MAC of this device
Reimplemented from ns3::WifiRemoteStationManager.
Definition at line 171 of file rrpaa-wifi-manager.cc.
References m_difs, m_sifs, third::mac, NS_LOG_FUNCTION, and ns3::WifiRemoteStationManager::SetupMac().
SetupPhy()
void ns3::RrpaaWifiManager::SetupPhy (const Ptr< WifiPhy > phy) virtual
Set up PHY associated with this device since it is the object that knows the full set of transmit rates that are supported.
Parameters
phy the PHY of this device
Reimplemented from ns3::WifiRemoteStationManager.
Definition at line 148 of file rrpaa-wifi-manager.cc.
References AddCalcTxTime(), m_ackLength, m_frameLength, m_maxPowerLevel, m_minPowerLevel, m_nPowerLevels, NS_LOG_DEBUG, NS_LOG_FUNCTION, third::phy, ns3::WifiTxVector::SetMode(), ns3::WifiTxVector::SetPreambleType(), ns3::WifiRemoteStationManager::SetupPhy(), and ns3::WIFI_PREAMBLE_LONG.
Member Data Documentation
m_ackLength
uint32_t ns3::RrpaaWifiManager::m_ackLength private
Ack frame length used for calculate mode TxTime (in bytes).
Definition at line 208 of file rrpaa-wifi-manager.h.
Referenced by GetTypeId(), and SetupPhy().
m_alpha
double ns3::RrpaaWifiManager::m_alpha private
Alpha value for RRPAA (value for calculating MTL threshold)
Definition at line 212 of file rrpaa-wifi-manager.h.
Referenced by GetTypeId(), and InitThresholds().
m_basic
bool ns3::RrpaaWifiManager::m_basic private
If using the basic algorithm (without RTS/CTS).
Definition at line 210 of file rrpaa-wifi-manager.h.
Referenced by DoNeedRts(), and GetTypeId().
m_beta
double ns3::RrpaaWifiManager::m_beta private
Beta value for RRPAA (value for calculating ORI threshold).
Definition at line 213 of file rrpaa-wifi-manager.h.
Referenced by GetTypeId(), and InitThresholds().
m_calcTxTime
TxTime ns3::RrpaaWifiManager::m_calcTxTime private
To hold all the calculated TxTime for all modes.
Definition at line 203 of file rrpaa-wifi-manager.h.
Referenced by AddCalcTxTime(), and GetCalcTxTime().
m_delta
double ns3::RrpaaWifiManager::m_delta private
Delta value for RRPAA (value for pdTable increments).
Definition at line 216 of file rrpaa-wifi-manager.h.
Referenced by GetTypeId(), and RunBasicAlgorithm().
m_difs
Time ns3::RrpaaWifiManager::m_difs private
Value of DIFS configured in the device.
Definition at line 205 of file rrpaa-wifi-manager.h.
Referenced by InitThresholds(), and SetupMac().
m_frameLength
uint32_t ns3::RrpaaWifiManager::m_frameLength private
Data frame length used for calculate mode TxTime (in bytes).
Definition at line 207 of file rrpaa-wifi-manager.h.
Referenced by GetTypeId(), and SetupPhy().
m_gamma
double ns3::RrpaaWifiManager::m_gamma private
Gamma value for RRPAA (value for pdTable decrements).
Definition at line 215 of file rrpaa-wifi-manager.h.
Referenced by GetTypeId(), and RunBasicAlgorithm().
m_maxPowerLevel
uint8_t ns3::RrpaaWifiManager::m_maxPowerLevel private
Maximal power level.
Definition at line 223 of file rrpaa-wifi-manager.h.
Referenced by CheckInit(), RunBasicAlgorithm(), and SetupPhy().
m_minPowerLevel
uint8_t ns3::RrpaaWifiManager::m_minPowerLevel private
Differently form rate, power levels do not depend on the remote station.
The levels depend only on the physical layer of the device. Minimal power level.
Definition at line 222 of file rrpaa-wifi-manager.h.
Referenced by RunBasicAlgorithm(), and SetupPhy().
m_nPowerLevels
uint8_t ns3::RrpaaWifiManager::m_nPowerLevels private
Number of power levels.
Definition at line 224 of file rrpaa-wifi-manager.h.
Referenced by CheckInit(), and SetupPhy().
m_powerChange
TracedCallback<double, double, Mac48Address> ns3::RrpaaWifiManager::m_powerChange private
The trace source fired when the transmission power change.
Definition at line 229 of file rrpaa-wifi-manager.h.
Referenced by CheckInit(), DoGetDataTxVector(), and GetTypeId().
m_rateChange
TracedCallback<DataRate, DataRate, Mac48Address> ns3::RrpaaWifiManager::m_rateChange private
The trace source fired when the transmission rate change.
Definition at line 233 of file rrpaa-wifi-manager.h.
Referenced by CheckInit(), DoGetDataTxVector(), and GetTypeId().
m_sifs
Time ns3::RrpaaWifiManager::m_sifs private
Value of SIFS configured in the device.
Definition at line 204 of file rrpaa-wifi-manager.h.
Referenced by InitThresholds(), and SetupMac().
m_tau
double ns3::RrpaaWifiManager::m_tau private
Tau value for RRPAA (value for calculating EWND size).
Definition at line 214 of file rrpaa-wifi-manager.h.
Referenced by GetTypeId(), and InitThresholds().
m_timeout
Time ns3::RrpaaWifiManager::m_timeout private
Timeout for the RRAA BASIC loss estimation block.
Definition at line 211 of file rrpaa-wifi-manager.h.
Referenced by CheckTimeout(), and GetTypeId().
m_uniformRandomVariable
Ptr<UniformRandomVariable> ns3::RrpaaWifiManager::m_uniformRandomVariable private
Provides uniform random variables for probabilistic changes.
Definition at line 235 of file rrpaa-wifi-manager.h.
Referenced by RrpaaWifiManager(), AssignStreams(), and RunBasicAlgorithm().
The documentation for this class was generated from the following files:
src/wifi/model/rrpaa-wifi-manager.h
src/wifi/model/rrpaa-wifi-manager.cc