ns-3: anonymous_namespace{packet-test-suite.cc}::ALargeTestTag Class Reference
anonymous_namespace{packet-test-suite.cc}::ALargeTestTag Class Reference
Network » Network module unit tests | Test suites
Template class for Large Test tags.
Public Member Functions
ALargeTestTag ()
virtual void Deserialize (TagBuffer buf)
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer buf) const
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
std::vector< uint8_t > m_data
Tag data.
uint8_t m_size
Packet size.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Template class for Large Test tags.
See also
Bug 2221: Expanding Packet tag maximum size
Note
Class internal to packet-test-suite.cc
Definition at line 153 of file packet-test-suite.cc.
Constructor & Destructor Documentation
ALargeTestTag()
anonymous_namespace{packet-test-suite.cc}::ALargeTestTag::ALargeTestTag () inline
Definition at line 156 of file packet-test-suite.cc.
References LARGE_TAG_BUFFER_SIZE.
Member Function Documentation
Deserialize()
virtual void anonymous_namespace{packet-test-suite.cc}::ALargeTestTag::Deserialize (TagBuffer i) inline virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 190 of file packet-test-suite.cc.
References ns3::TagBuffer::ReadU8().
GetInstanceTypeId()
virtual TypeId anonymous_namespace{packet-test-suite.cc}::ALargeTestTag::GetInstanceTypeId (void) const inline virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 177 of file packet-test-suite.cc.
GetSerializedSize()
virtual uint32_t anonymous_namespace{packet-test-suite.cc}::ALargeTestTag::GetSerializedSize (void) const inline virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 180 of file packet-test-suite.cc.
GetTypeId()
static TypeId anonymous_namespace{packet-test-suite.cc}::ALargeTestTag::GetTypeId (void) inline static
Register this type.
Returns
The TypeId.
Definition at line 167 of file packet-test-suite.cc.
References ns3::TypeId::SetParent().
Print()
virtual void anonymous_namespace{packet-test-suite.cc}::ALargeTestTag::Print (std::ostream & os) const inline virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 198 of file packet-test-suite.cc.
Serialize()
virtual void anonymous_namespace{packet-test-suite.cc}::ALargeTestTag::Serialize (TagBuffer i) const inline virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 183 of file packet-test-suite.cc.
References ns3::TagBuffer::WriteU8().
Member Data Documentation
m_data
std::vector<uint8_t> anonymous_namespace{packet-test-suite.cc}::ALargeTestTag::m_data private
Tag data.
Definition at line 203 of file packet-test-suite.cc.
m_size
uint8_t anonymous_namespace{packet-test-suite.cc}::ALargeTestTag::m_size private
Packet size.
Definition at line 202 of file packet-test-suite.cc.
The documentation for this class was generated from the following file:
src/network/test/packet-test-suite.cc