ns-3: ns3::SingleModelSpectrumChannel Class Reference
ns3::SingleModelSpectrumChannel Class Reference
Spectrum Models
SpectrumChannel implementation which handles a single spectrum model.
#include "single-model-spectrum-channel.h"
Public Types
typedef std::vector< Ptr< SpectrumPhy > > PhyList
Container: SpectrumPhy objects.
Public Types inherited from ns3::SpectrumChannel
typedef void(* GainTracedCallback) (Ptr< const MobilityModel > txMobility, Ptr< const MobilityModel > rxMobility, double txAntennaGain, double rxAntennaGain, double propagationGain, double pathloss)
TracedCallback signature for path loss calculation events.
typedef void(* LossTracedCallback) (Ptr< const SpectrumPhy > txPhy, Ptr< const SpectrumPhy > rxPhy, double lossDb)
TracedCallback signature for path loss calculation events.
typedef void(* SignalParametersTracedCallback) (Ptr< SpectrumSignalParameters > params)
TracedCallback signature for Ptr<const SpectrumSignalParameters>.
Public Member Functions
SingleModelSpectrumChannel ()
virtual void AddRx (Ptr< SpectrumPhy > phy)
Add a SpectrumPhy to a channel, so it can receive packets.
virtual Ptr< NetDevice > GetDevice (std::size_t i) const
virtual std::size_t GetNDevices (void) const
virtual void StartTx (Ptr< SpectrumSignalParameters > params)
Used by attached PHY instances to transmit signals on the channel.
Public Member Functions inherited from ns3::SpectrumChannel
SpectrumChannel ()
constructor
virtual ~SpectrumChannel ()
destructor
void AddPropagationLossModel (Ptr< PropagationLossModel > loss)
Add the single-frequency propagation loss model to be used.
void AddSpectrumPropagationLossModel (Ptr< SpectrumPropagationLossModel > loss)
Add the frequency-dependent propagation loss model to be used.
Ptr< SpectrumPropagationLossModel > GetSpectrumPropagationLossModel (void)
Get the frequency-dependent propagation loss model.
void SetPropagationDelayModel (Ptr< PropagationDelayModel > delay)
Set the propagation delay model to be used.
Public Member Functions inherited from ns3::Channel
Channel ()
virtual ~Channel ()
uint32_t GetId (void) const
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::SpectrumChannel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Channel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual void DoDispose ()
Destructor implementation.
void StartRx (Ptr< SpectrumSignalParameters > params, Ptr< SpectrumPhy > receiver)
Used internally to reschedule transmission after the propagation delay.
Private Attributes
PhyList m_phyList
List of SpectrumPhy instances attached to the channel.
Ptr< const SpectrumModel > m_spectrumModel
SpectrumModel that this channel instance is supporting.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::SpectrumChannel
TracedCallback< Ptr< const MobilityModel >, Ptr< const MobilityModel >, double, double, double, double > m_gainTrace
The Gain trace source.
double m_maxLossDb
Maximum loss [dB].
TracedCallback< Ptr< const SpectrumPhy >, Ptr< const SpectrumPhy >, double > m_pathLossTrace
The PathLoss trace source.
Ptr< PropagationDelayModel > m_propagationDelay
Propagation delay model to be used with this channel.
Ptr< PropagationLossModel > m_propagationLoss
Single-frequency propagation loss model to be used with this channel.
Ptr< SpectrumPropagationLossModel > m_spectrumPropagationLoss
Frequency-dependent propagation loss model to be used with this channel.
TracedCallback< Ptr< SpectrumSignalParameters > > m_txSigParamsTrace
Traced callback for SpectrumSignalParameters in StartTx requests.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
SpectrumChannel implementation which handles a single spectrum model.
All SpectrumPhy layers attached to this SpectrumChannel
Definition at line 40 of file single-model-spectrum-channel.h.
Member Typedef Documentation
PhyList
typedef std::vector<Ptr<SpectrumPhy> > ns3::SingleModelSpectrumChannel::PhyList
Container: SpectrumPhy objects.
Definition at line 62 of file single-model-spectrum-channel.h.
Constructor & Destructor Documentation
SingleModelSpectrumChannel()
ns3::SingleModelSpectrumChannel::SingleModelSpectrumChannel ()
Definition at line 47 of file single-model-spectrum-channel.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddRx()
void ns3::SingleModelSpectrumChannel::AddRx (Ptr< SpectrumPhy > phy) virtual
Add a SpectrumPhy to a channel, so it can receive packets.
This method is used to attach a SpectrumPhy instance to a SpectrumChannel instance, so that the SpectrumPhy can receive packets sent on that channel. Note that a SpectrumPhy that only transmits (without receiving ever) does not need to be added to the channel.
This method is to be implemented by all classes inheriting from SpectrumChannel.
Parameters
phy the SpectrumPhy instance to be added to the channel as a receiver.
Implements ns3::SpectrumChannel.
Definition at line 75 of file single-model-spectrum-channel.cc.
References m_phyList, NS_LOG_FUNCTION, and third::phy.
DoDispose()
void ns3::SingleModelSpectrumChannel::DoDispose () private virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::SpectrumChannel.
Definition at line 53 of file single-model-spectrum-channel.cc.
References ns3::SpectrumChannel::DoDispose(), m_phyList, m_spectrumModel, and NS_LOG_FUNCTION.
GetDevice()
Ptr< NetDevice > ns3::SingleModelSpectrumChannel::GetDevice (std::size_t i) const virtual
Parameters
i index of NetDevice to retrieve
Returns
one of the NetDevices connected to this channel.
This method must be implemented by subclasses.
Implements ns3::Channel.
Definition at line 205 of file single-model-spectrum-channel.cc.
References m_phyList, and NS_LOG_FUNCTION.
GetNDevices()
std::size_t ns3::SingleModelSpectrumChannel::GetNDevices (void) const virtual
Returns
the number of NetDevices connected to this Channel.
This method must be implemented by subclasses.
Implements ns3::Channel.
Definition at line 198 of file single-model-spectrum-channel.cc.
References m_phyList, and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::SingleModelSpectrumChannel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 62 of file single-model-spectrum-channel.cc.
References NS_LOG_FUNCTION_NOARGS, and ns3::TypeId::SetParent().
StartRx()
void ns3::SingleModelSpectrumChannel::StartRx (Ptr< SpectrumSignalParameters > params, Ptr< SpectrumPhy > receiver) private
Used internally to reschedule transmission after the propagation delay.
Parameters
params
receiver
Definition at line 191 of file single-model-spectrum-channel.cc.
References NS_LOG_FUNCTION, aloha::params, and ns3::SpectrumPhy::StartRx().
Referenced by StartTx().
StartTx()
void ns3::SingleModelSpectrumChannel::StartTx (Ptr< SpectrumSignalParameters > params) virtual
Used by attached PHY instances to transmit signals on the channel.
Parameters
params the parameters of the signals being transmitted
Implements ns3::SpectrumChannel.
Definition at line 83 of file single-model-spectrum-channel.cc.
References ns3::PropagationLossModel::CalcRxPower(), ns3::MobilityModel::GetPosition(), ns3::SpectrumChannel::m_gainTrace, ns3::SpectrumChannel::m_maxLossDb, ns3::SpectrumChannel::m_pathLossTrace, m_phyList, ns3::SpectrumChannel::m_propagationDelay, ns3::SpectrumChannel::m_propagationLoss, m_spectrumModel, ns3::SpectrumChannel::m_spectrumPropagationLoss, ns3::SpectrumChannel::m_txSigParamsTrace, ns3::MicroSeconds(), NS_ASSERT, NS_ASSERT_MSG(), NS_LOG_FUNCTION, NS_LOG_LOGIC(), ns3::Simulator::Schedule(), ns3::Simulator::ScheduleWithContext(), and StartRx().
Member Data Documentation
m_phyList
PhyList ns3::SingleModelSpectrumChannel::m_phyList private
List of SpectrumPhy instances attached to the channel.
Definition at line 78 of file single-model-spectrum-channel.h.
Referenced by AddRx(), DoDispose(), GetDevice(), GetNDevices(), and StartTx().
m_spectrumModel
Ptr<const SpectrumModel> ns3::SingleModelSpectrumChannel::m_spectrumModel private
SpectrumModel that this channel instance is supporting.
Definition at line 83 of file single-model-spectrum-channel.h.
Referenced by DoDispose(), and StartTx().
The documentation for this class was generated from the following files:
src/spectrum/model/single-model-spectrum-channel.h
src/spectrum/model/single-model-spectrum-channel.cc