ns-3: TestCaseHelper Class Reference
TestCaseHelper Class Reference
WAVE module » wave module tests | Test suites
Test Case Helper.
Static Public Member Functions
static NetDeviceContainer CreatWaveDevice (uint32_t nodesNumber=2)
Create WAVE device function.
Detailed Description
Test Case Helper.
Definition at line 265 of file mac-extension-test-suite.cc.
Member Function Documentation
CreatWaveDevice()
NetDeviceContainer TestCaseHelper::CreatWaveDevice (uint32_t nodesNumber = 2) static
Create WAVE device function.
Parameters
nodesNumber the number of nodes
Returns
the collection of nodes
Definition at line 279 of file mac-extension-test-suite.cc.
References ns3::YansWifiChannelHelper::Create(), first::devices, ns3::Object::GetObject(), ns3::WaveHelper::Install(), third::mobility, sample-rng-plot::n, first::nodes, PI, ns3::YansWifiPhyHelper::SetChannel(), ns3::MobilityModel::SetPosition(), and sample-rng-plot::x.
Referenced by ChannelRoutingTestCase::DoRun(), ChannelAccessTestCase::DoRun(), and AnnexC_TestCase::DoRun().
The documentation for this class was generated from the following file:
src/wave/test/mac-extension-test-suite.cc