ns-3: LteX2HandoverMeasuresTestCase Class Reference
LteX2HandoverMeasuresTestCase Class Reference
LTE Models » lte module tests | Test suites
Test different X2 handover measures and algorithms, e.g. A2A4RsrqHandoverAlgorithm and A3RsrpHandoverAlgorithm. Test defines different handover parameters and scenario configurations.
Classes
struct BearerData
BearerData structure.
struct UeData
UeData structure.
Public Member Functions
LteX2HandoverMeasuresTestCase (uint32_t nEnbs, uint32_t nUes, uint32_t nDedicatedBearers, std::list< CheckPointEvent > checkPointEventList, std::string checkPointEventListName, bool useUdp, std::string schedulerType, std::string handoverAlgorithmType, bool admitHo, bool useIdealRrc)
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CheckConnected (Ptr< NetDevice > ueDevice, Ptr< NetDevice > enbDevice)
Check connected function.
void CheckStats (uint32_t ueIndex)
Check stats function.
virtual void DoRun (void)
Implementation to actually run this TestCase.
void SaveStats (uint32_t ueIndex)
Save stats function.
Static Private Member Functions
static std::string BuildNameString (uint32_t nEnbs, uint32_t nUes, uint32_t nDedicatedBearers, std::string checkPointEventListName, bool useUdp, std::string schedulerType, std::string handoverAlgorithmType, bool admitHo, bool useIdealRrc)
Build name string.
Private Attributes
bool m_admitHo
whether to configure to admit handover
std::list< CheckPointEvent > m_checkPointEventList
check point event list
std::string m_checkPointEventListName
check point event list name
bool m_epc
whether to use EPC
Ptr< PointToPointEpcHelper > m_epcHelper
EPC helper.
std::string m_handoverAlgorithmType
handover algorithm type
Ptr< LteHelper > m_lteHelper
LTE helper.
const Time m_maxHoDuration
maximum HO duration
uint32_t m_nDedicatedBearers
number of UEs in the test
uint32_t m_nEnbs
number of eNBs in the test
uint32_t m_nUes
number of UEs in the test
std::string m_schedulerType
scheduler type
const Time m_statsDuration
stats duration
const Time m_udpClientInterval
UDP client interval.
const uint32_t m_udpClientPktSize
UDP client packet size.
std::vector< UeData > m_ueDataVector
UE data vector.
bool m_useIdealRrc
whether to use ideal RRC
bool m_useUdp
whether to use UDP traffic
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test different X2 handover measures and algorithms, e.g. A2A4RsrqHandoverAlgorithm and A3RsrpHandoverAlgorithm. Test defines different handover parameters and scenario configurations.
Definition at line 75 of file test-lte-x2-handover-measures.cc.
Constructor & Destructor Documentation
LteX2HandoverMeasuresTestCase()
LteX2HandoverMeasuresTestCase::LteX2HandoverMeasuresTestCase (uint32_t nEnbs, uint32_t nUes, uint32_t nDedicatedBearers, std::list< CheckPointEvent > checkPointEventList, std::string checkPointEventListName, bool useUdp, std::string schedulerType, std::string handoverAlgorithmType, bool admitHo, bool useIdealRrc)
Parameters
nEnbs number of eNBs in the test
nUes number of UEs in the test
nDedicatedBearers number of bearers to be activated per UE
checkPointEventList
checkPointEventListName
useUdp true if UDP is to be used, false if TCP is to be used
schedulerType type of scheduler to be used (e.g. "ns3::PfFfMacScheduler")
handoverAlgorithmType type of handover algorithm to be used (e.g. "ns3::A3RsrpHandoverAlgorithm")
admitHo
useIdealRrc true if ideal RRC is to be used, false if real RRC is to be used
Returns
Definition at line 216 of file test-lte-x2-handover-measures.cc.
Member Function Documentation
BuildNameString()
std::string LteX2HandoverMeasuresTestCase::BuildNameString (uint32_t nEnbs, uint32_t nUes, uint32_t nDedicatedBearers, std::string checkPointEventListName, bool useUdp, std::string schedulerType, std::string handoverAlgorithmType, bool admitHo, bool useIdealRrc) static private
Build name string.
Parameters
nEnbs number of eNBs in the test
nUes number of UEs in the test
nDedicatedBearers number of bearers to be activated per UE
checkPointEventListName
useUdp true if UDP is to be used, false if TCP is to be used
schedulerType the scheduler type
handoverAlgorithmType type of handover algorithm to be used (e.g. "ns3::A3RsrpHandoverAlgorithm")
admitHo
useIdealRrc true if the ideal RRC should be used
Returns
the name string
Definition at line 190 of file test-lte-x2-handover-measures.cc.
Referenced by DoRun().
CheckConnected()
void LteX2HandoverMeasuresTestCase::CheckConnected (Ptr< NetDevice > ueDevice, Ptr< NetDevice > enbDevice) private
Check connected function.
Parameters
ueDevice the UE device
enbDevice the ENB device
Definition at line 568 of file test-lte-x2-handover-measures.cc.
References ns3::ObjectPtrContainerValue::Begin(), ns3::ObjectPtrContainerValue::End(), ns3::ObjectBase::GetAttribute(), ns3::LteEnbNetDevice::GetCellId(), ns3::LteEnbNetDevice::GetDlBandwidth(), ns3::LteEnbNetDevice::GetDlEarfcn(), ns3::LteUeNetDevice::GetImsi(), ns3::UeManager::GetImsi(), ns3::ObjectPtrContainerValue::GetN(), ns3::Object::GetObject(), ns3::LteEnbNetDevice::GetRrc(), ns3::LteUeNetDevice::GetRrc(), ns3::UeManager::GetState(), ns3::LteEnbNetDevice::GetUlBandwidth(), ns3::LteEnbNetDevice::GetUlEarfcn(), ns3::LteDataRadioBearerInfo::m_drbIdentity, ns3::LteDataRadioBearerInfo::m_epsBearerIdentity, ns3::LteDataRadioBearerInfo::m_logicalChannelIdentity, m_nDedicatedBearers, NS_ASSERT_MSG(), NS_LOG_FUNCTION, NS_TEST_ASSERT_MSG_EQ, and NS_TEST_ASSERT_MSG_NE.
Referenced by DoRun().
CheckStats()
void LteX2HandoverMeasuresTestCase::CheckStats (uint32_t ueIndex) private
Check stats function.
Parameters
ueIndex the index of the UE
Definition at line 656 of file test-lte-x2-handover-measures.cc.
References ns3::Time::GetSeconds(), m_statsDuration, m_udpClientInterval, m_udpClientPktSize, m_ueDataVector, NS_LOG_FUNCTION, NS_LOG_LOGIC(), and NS_TEST_ASSERT_MSG_GT.
Referenced by DoRun().
DoRun()
void LteX2HandoverMeasuresTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 244 of file test-lte-x2-handover-measures.cc.
References ns3::LteHelper::ActivateDataRadioBearer(), ns3::LteHelper::ActivateDedicatedEpsBearer(), ns3::EpcTft::Add(), ns3::ListPositionAllocator::Add(), ns3::Ipv4StaticRouting::AddNetworkRouteTo(), ns3::LteHelper::AddX2Interface(), ns3::Ipv4AddressHelper::Assign(), ns3::LteHelper::AssignStreams(), ns3::NoBackhaulEpcHelper::AssignUeIpv4Address(), ns3::LteHelper::Attach(), LteX2HandoverMeasuresTestCase::UeData::bearerDataList, ns3::NetDeviceContainer::Begin(), BuildNameString(), CheckConnected(), CheckStats(), first::clientApps, ns3::NodeContainer::Create(), LteX2HandoverMeasuresTestCase::BearerData::dlSink, ns3::NetDeviceContainer::End(), ns3::ApplicationContainer::Get(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::NetDeviceContainer::GetN(), ns3::NodeContainer::GetN(), ns3::Object::GetObject(), ns3::NoBackhaulEpcHelper::GetPgwNode(), ns3::Ipv4StaticRoutingHelper::GetStaticRouting(), ns3::NoBackhaulEpcHelper::GetUeDefaultGatewayAddress(), ns3::UniformRandomVariable::GetValue(), ns3::UdpClientHelper::Install(), ns3::PointToPointHelper::Install(), ns3::BulkSendHelper::Install(), ns3::PacketSinkHelper::Install(), ns3::MobilityHelper::Install(), ns3::InternetStackHelper::Install(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), ns3::EpcTft::PacketFilter::localPortEnd, ns3::EpcTft::PacketFilter::localPortStart, m_admitHo, m_checkPointEventList, m_checkPointEventListName, m_epc, m_epcHelper, m_handoverAlgorithmType, m_lteHelper, m_nDedicatedBearers, m_nEnbs, m_nUes, m_schedulerType, m_statsDuration, m_udpClientInterval, m_udpClientPktSize, m_ueDataVector, m_useIdealRrc, m_useUdp, ns3::MilliSeconds(), NS_FATAL_ERROR, NS_LOG_FUNCTION, ns3::EpcTft::PacketFilter::remotePortEnd, ns3::EpcTft::PacketFilter::remotePortStart, ns3::Config::Reset(), SaveStats(), ns3::Seconds(), first::serverApps, ns3::BulkSendHelper::SetAttribute(), ns3::ObjectBase::SetAttribute(), ns3::Ipv4AddressHelper::SetBase(), ns3::PointToPointHelper::SetChannelAttribute(), ns3::Config::SetDefault(), ns3::Ipv4StaticRouting::SetDefaultRoute(), ns3::PointToPointHelper::SetDeviceAttribute(), ns3::LteHelper::SetEpcHelper(), ns3::LteHelper::SetHandoverAlgorithmAttribute(), ns3::LteHelper::SetHandoverAlgorithmType(), ns3::MobilityHelper::SetMobilityModel(), SetPosition(), ns3::MobilityHelper::SetPositionAllocator(), ns3::LteHelper::SetSchedulerType(), ns3::RandomVariableStream::SetStream(), startTime, stopTime, and LteX2HandoverMeasuresTestCase::BearerData::ulSink.
SaveStats()
void LteX2HandoverMeasuresTestCase::SaveStats (uint32_t ueIndex) private
Save stats function.
Parameters
ueIndex the index of the UE
Definition at line 637 of file test-lte-x2-handover-measures.cc.
References m_ueDataVector, and NS_LOG_FUNCTION.
Referenced by DoRun().
Member Data Documentation
m_admitHo
bool LteX2HandoverMeasuresTestCase::m_admitHo private
whether to configure to admit handover
Definition at line 137 of file test-lte-x2-handover-measures.cc.
Referenced by DoRun().
m_checkPointEventList
std::list<CheckPointEvent> LteX2HandoverMeasuresTestCase::m_checkPointEventList private
check point event list
Definition at line 131 of file test-lte-x2-handover-measures.cc.
Referenced by DoRun().
m_checkPointEventListName
std::string LteX2HandoverMeasuresTestCase::m_checkPointEventListName private
check point event list name
Definition at line 132 of file test-lte-x2-handover-measures.cc.
Referenced by DoRun().
m_epc
bool LteX2HandoverMeasuresTestCase::m_epc private
whether to use EPC
Definition at line 133 of file test-lte-x2-handover-measures.cc.
Referenced by DoRun().
m_epcHelper
Ptr<PointToPointEpcHelper> LteX2HandoverMeasuresTestCase::m_epcHelper private
EPC helper.
Definition at line 140 of file test-lte-x2-handover-measures.cc.
Referenced by DoRun().
m_handoverAlgorithmType
std::string LteX2HandoverMeasuresTestCase::m_handoverAlgorithmType private
handover algorithm type
Definition at line 136 of file test-lte-x2-handover-measures.cc.
Referenced by DoRun().
m_lteHelper
Ptr<LteHelper> LteX2HandoverMeasuresTestCase::m_lteHelper private
LTE helper.
Definition at line 139 of file test-lte-x2-handover-measures.cc.
Referenced by DoRun().
m_maxHoDuration
const Time LteX2HandoverMeasuresTestCase::m_maxHoDuration private
maximum HO duration
Definition at line 182 of file test-lte-x2-handover-measures.cc.
m_nDedicatedBearers
uint32_t LteX2HandoverMeasuresTestCase::m_nDedicatedBearers private
number of UEs in the test
Definition at line 130 of file test-lte-x2-handover-measures.cc.
Referenced by CheckConnected(), and DoRun().
m_nEnbs
uint32_t LteX2HandoverMeasuresTestCase::m_nEnbs private
number of eNBs in the test
Definition at line 128 of file test-lte-x2-handover-measures.cc.
Referenced by DoRun().
m_nUes
uint32_t LteX2HandoverMeasuresTestCase::m_nUes private
number of UEs in the test
Definition at line 129 of file test-lte-x2-handover-measures.cc.
Referenced by DoRun().
m_schedulerType
std::string LteX2HandoverMeasuresTestCase::m_schedulerType private
scheduler type
Definition at line 135 of file test-lte-x2-handover-measures.cc.
Referenced by DoRun().
m_statsDuration
const Time LteX2HandoverMeasuresTestCase::m_statsDuration private
stats duration
Definition at line 183 of file test-lte-x2-handover-measures.cc.
Referenced by CheckStats(), and DoRun().
m_udpClientInterval
const Time LteX2HandoverMeasuresTestCase::m_udpClientInterval private
UDP client interval.
Definition at line 184 of file test-lte-x2-handover-measures.cc.
Referenced by CheckStats(), and DoRun().
m_udpClientPktSize
const uint32_t LteX2HandoverMeasuresTestCase::m_udpClientPktSize private
UDP client packet size.
Definition at line 185 of file test-lte-x2-handover-measures.cc.
Referenced by CheckStats(), and DoRun().
m_ueDataVector
std::vector<UeData> LteX2HandoverMeasuresTestCase::m_ueDataVector private
UE data vector.
Definition at line 180 of file test-lte-x2-handover-measures.cc.
Referenced by CheckStats(), DoRun(), and SaveStats().
m_useIdealRrc
bool LteX2HandoverMeasuresTestCase::m_useIdealRrc private
whether to use ideal RRC
Definition at line 138 of file test-lte-x2-handover-measures.cc.
Referenced by DoRun().
m_useUdp
bool LteX2HandoverMeasuresTestCase::m_useUdp private
whether to use UDP traffic
Definition at line 134 of file test-lte-x2-handover-measures.cc.
Referenced by DoRun().
The documentation for this class was generated from the following file:
src/lte/test/test-lte-x2-handover-measures.cc