ns-3: MakeCallbackTemplatesTestCase Class Reference
MakeCallbackTemplatesTestCase Class Reference
Public Member Functions
MakeCallbackTemplatesTestCase ()
virtual ~MakeCallbackTemplatesTestCase ()
void Target1 (void)
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
bool m_test1
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 602 of file callback-test-suite.cc.
Constructor & Destructor Documentation
MakeCallbackTemplatesTestCase()
MakeCallbackTemplatesTestCase::MakeCallbackTemplatesTestCase ()
Definition at line 687 of file callback-test-suite.cc.
~MakeCallbackTemplatesTestCase()
virtual MakeCallbackTemplatesTestCase::~MakeCallbackTemplatesTestCase () inline virtual
Definition at line 606 of file callback-test-suite.cc.
Member Function Documentation
DoRun()
void MakeCallbackTemplatesTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 692 of file callback-test-suite.cc.
References CallbackTestClass::CheckParentalRights(), ns3::MakeBoundCallback(), ns3::MakeCallback(), CallbackTestClass::TestCFive(), CallbackTestClass::TestCFour(), CallbackTestClass::TestCOne(), CallbackTestClass::TestCSix(), CallbackTestClass::TestCThree(), CallbackTestClass::TestCTwo(), CallbackTestClass::TestCZero(), TestFFive(), TestFFour(), CallbackTestClass::TestFive(), TestFOne(), CallbackTestClass::TestFour(), TestFRFive(), TestFRFour(), TestFROne(), TestFRSix(), TestFRThree(), TestFRTwo(), TestFSix(), TestFThree(), TestFTwo(), TestFZero(), CallbackTestClass::TestOne(), CallbackTestClass::TestSix(), CallbackTestClass::TestThree(), CallbackTestClass::TestTwo(), and CallbackTestClass::TestZero().
Target1()
void MakeCallbackTemplatesTestCase::Target1 (void) inline
Definition at line 609 of file callback-test-suite.cc.
References m_test1.
Member Data Documentation
m_test1
bool MakeCallbackTemplatesTestCase::m_test1 private
Definition at line 617 of file callback-test-suite.cc.
Referenced by Target1().
The documentation for this class was generated from the following file:
src/core/test/callback-test-suite.cc