ns-3: RoutingStats Class Reference
RoutingStats Class Reference
WAVE module
The RoutingStats class manages collects statistics on routing data (application-data packet and byte counts) for the vehicular network.
Public Member Functions
RoutingStats ()
Constructor.
uint32_t GetCumulativeRxBytes ()
Returns the cumulative number of bytes received.
uint32_t GetCumulativeRxPkts ()
Returns the cumulative count of packets received.
uint32_t GetCumulativeTxBytes ()
Returns the cumulative number of bytes transmitted.
uint32_t GetCumulativeTxPkts ()
Returns the cumulative number of packets transmitted.
uint32_t GetRxBytes ()
Returns the number of bytes received.
uint32_t GetRxPkts ()
Returns the count of packets received.
uint32_t GetTxBytes ()
Returns the number of bytes transmitted.
uint32_t GetTxPkts ()
Returns the number of packets transmitted.
void IncRxBytes (uint32_t rxBytes)
Increments the number of (application-data) bytes received, not including MAC/PHY overhead.
void IncRxPkts ()
Increments the count of packets received.
void IncTxBytes (uint32_t txBytes)
Increment the number of bytes transmitted.
void IncTxPkts ()
Increment the count of packets transmitted.
void SetRxBytes (uint32_t rxBytes)
Sets the number of bytes received.
void SetRxPkts (uint32_t rxPkts)
Sets the number of packets received.
void SetTxBytes (uint32_t txBytes)
Sets the number of bytes transmitted.
void SetTxPkts (uint32_t txPkts)
Sets the number of packets transmitted.
Private Attributes
uint32_t m_cumulativeRxBytes
cumulative receive bytes
uint32_t m_cumulativeRxPkts
cumulative receive packets
uint32_t m_cumulativeTxBytes
cumulative transmit bytes
uint32_t m_cumulativeTxPkts
cumulative transmit packets
uint32_t m_RxBytes
reeive bytes
uint32_t m_RxPkts
receive packets
uint32_t m_TxBytes
transmit bytes
uint32_t m_TxPkts
transmit packets
Detailed Description
The RoutingStats class manages collects statistics on routing data (application-data packet and byte counts) for the vehicular network.
Definition at line 135 of file vanet-routing-compare.cc.
Constructor & Destructor Documentation
RoutingStats()
RoutingStats::RoutingStats ()
Constructor.
Returns
none
Definition at line 258 of file vanet-routing-compare.cc.
Member Function Documentation
GetCumulativeRxBytes()
uint32_t RoutingStats::GetCumulativeRxBytes ()
Returns the cumulative number of bytes received.
Returns
the cumulative number of bytes received
Definition at line 277 of file vanet-routing-compare.cc.
References m_cumulativeRxBytes.
Referenced by VanetRoutingExperiment::ProcessOutputs().
GetCumulativeRxPkts()
uint32_t RoutingStats::GetCumulativeRxPkts ()
Returns the cumulative count of packets received.
Returns
the cumulative count of packets received
Definition at line 289 of file vanet-routing-compare.cc.
References m_cumulativeRxPkts.
GetCumulativeTxBytes()
uint32_t RoutingStats::GetCumulativeTxBytes ()
Returns the cumulative number of bytes transmitted.
Returns
none
Definition at line 327 of file vanet-routing-compare.cc.
References m_cumulativeTxBytes.
Referenced by VanetRoutingExperiment::CheckThroughput(), and VanetRoutingExperiment::ProcessOutputs().
GetCumulativeTxPkts()
uint32_t RoutingStats::GetCumulativeTxPkts ()
Returns the cumulative number of packets transmitted.
Returns
the cumulative number of packets transmitted
Definition at line 339 of file vanet-routing-compare.cc.
References m_cumulativeTxPkts.
GetRxBytes()
uint32_t RoutingStats::GetRxBytes ()
Returns the number of bytes received.
Returns
the number of bytes received
Definition at line 271 of file vanet-routing-compare.cc.
References m_RxBytes.
Referenced by VanetRoutingExperiment::CheckThroughput().
GetRxPkts()
uint32_t RoutingStats::GetRxPkts ()
Returns the count of packets received.
Returns
the count of packets received
Definition at line 283 of file vanet-routing-compare.cc.
References m_RxPkts.
Referenced by VanetRoutingExperiment::CheckThroughput().
GetTxBytes()
uint32_t RoutingStats::GetTxBytes ()
Returns the number of bytes transmitted.
Returns
the number of bytes transmitted
Definition at line 321 of file vanet-routing-compare.cc.
References m_TxBytes.
GetTxPkts()
uint32_t RoutingStats::GetTxPkts ()
Returns the number of packets transmitted.
Returns
the number of packets transmitted
Definition at line 333 of file vanet-routing-compare.cc.
References m_TxPkts.
IncRxBytes()
void RoutingStats::IncRxBytes (uint32_t rxBytes)
Increments the number of (application-data) bytes received, not including MAC/PHY overhead.
Parameters
rxBytes the number of bytes received
Returns
none
Definition at line 295 of file vanet-routing-compare.cc.
References m_cumulativeRxBytes, and m_RxBytes.
Referenced by RoutingHelper::ReceiveRoutingPacket().
IncRxPkts()
void RoutingStats::IncRxPkts ()
Increments the count of packets received.
Returns
none
Definition at line 302 of file vanet-routing-compare.cc.
References m_cumulativeRxPkts, and m_RxPkts.
Referenced by RoutingHelper::ReceiveRoutingPacket().
IncTxBytes()
void RoutingStats::IncTxBytes (uint32_t txBytes)
Increment the number of bytes transmitted.
Parameters
txBytes the number of additional bytes transmitted
Returns
none
Definition at line 345 of file vanet-routing-compare.cc.
References m_cumulativeTxBytes, and m_TxBytes.
Referenced by RoutingHelper::OnOffTrace().
IncTxPkts()
void RoutingStats::IncTxPkts ()
Increment the count of packets transmitted.
Returns
none
Definition at line 352 of file vanet-routing-compare.cc.
References m_cumulativeTxPkts, and m_TxPkts.
SetRxBytes()
void RoutingStats::SetRxBytes (uint32_t rxBytes)
Sets the number of bytes received.
Parameters
rxBytes the number of bytes received
Returns
none
Definition at line 309 of file vanet-routing-compare.cc.
References m_RxBytes.
Referenced by VanetRoutingExperiment::CheckThroughput().
SetRxPkts()
void RoutingStats::SetRxPkts (uint32_t rxPkts)
Sets the number of packets received.
Parameters
rxPkts the number of packets received
Returns
none
Definition at line 315 of file vanet-routing-compare.cc.
References m_RxPkts.
Referenced by VanetRoutingExperiment::CheckThroughput().
SetTxBytes()
void RoutingStats::SetTxBytes (uint32_t txBytes)
Sets the number of bytes transmitted.
Parameters
txBytes the number of bytes transmitted
Returns
none
Definition at line 359 of file vanet-routing-compare.cc.
References m_TxBytes.
SetTxPkts()
void RoutingStats::SetTxPkts (uint32_t txPkts)
Sets the number of packets transmitted.
Parameters
txPkts the number of packets transmitted
Returns
none
Definition at line 365 of file vanet-routing-compare.cc.
References m_TxPkts.
Member Data Documentation
m_cumulativeRxBytes
uint32_t RoutingStats::m_cumulativeRxBytes private
cumulative receive bytes
Definition at line 249 of file vanet-routing-compare.cc.
Referenced by GetCumulativeRxBytes(), and IncRxBytes().
m_cumulativeRxPkts
uint32_t RoutingStats::m_cumulativeRxPkts private
cumulative receive packets
Definition at line 251 of file vanet-routing-compare.cc.
Referenced by GetCumulativeRxPkts(), and IncRxPkts().
m_cumulativeTxBytes
uint32_t RoutingStats::m_cumulativeTxBytes private
cumulative transmit bytes
Definition at line 253 of file vanet-routing-compare.cc.
Referenced by GetCumulativeTxBytes(), and IncTxBytes().
m_cumulativeTxPkts
uint32_t RoutingStats::m_cumulativeTxPkts private
cumulative transmit packets
Definition at line 255 of file vanet-routing-compare.cc.
Referenced by GetCumulativeTxPkts(), and IncTxPkts().
m_RxBytes
uint32_t RoutingStats::m_RxBytes private
reeive bytes
Definition at line 248 of file vanet-routing-compare.cc.
Referenced by GetRxBytes(), IncRxBytes(), and SetRxBytes().
m_RxPkts
uint32_t RoutingStats::m_RxPkts private
receive packets
Definition at line 250 of file vanet-routing-compare.cc.
Referenced by GetRxPkts(), IncRxPkts(), and SetRxPkts().
m_TxBytes
uint32_t RoutingStats::m_TxBytes private
transmit bytes
Definition at line 252 of file vanet-routing-compare.cc.
Referenced by GetTxBytes(), IncTxBytes(), and SetTxBytes().
m_TxPkts
uint32_t RoutingStats::m_TxPkts private
transmit packets
Definition at line 254 of file vanet-routing-compare.cc.
Referenced by GetTxPkts(), IncTxPkts(), and SetTxPkts().
The documentation for this class was generated from the following file:
src/wave/examples/vanet-routing-compare.cc