ns-3: CoDelQueueDiscControlLawTest Class Reference
CoDelQueueDiscControlLawTest Class Reference
Traffic-control » traffic-control module tests | Test suites
Test 4: ControlLaw unit test - test against explicit port of Linux implementation.
Public Member Functions
CoDelQueueDiscControlLawTest ()
uint32_t _codel_control_law (uint32_t t, uint32_t interval, uint32_t recInvSqrt)
Codel control law function.
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Test 4: ControlLaw unit test - test against explicit port of Linux implementation.
Definition at line 359 of file codel-queue-disc-test-suite.cc.
Constructor & Destructor Documentation
CoDelQueueDiscControlLawTest()
CoDelQueueDiscControlLawTest::CoDelQueueDiscControlLawTest ()
Definition at line 373 of file codel-queue-disc-test-suite.cc.
Member Function Documentation
_codel_control_law()
uint32_t CoDelQueueDiscControlLawTest::_codel_control_law (uint32_t t, uint32_t interval, uint32_t recInvSqrt)
Codel control law function.
Parameters
queue the queue disc
t
Returns
the codel control law
Definition at line 381 of file codel-queue-disc-test-suite.cc.
References _reciprocal_scale(), and REC_INV_SQRT_SHIFT_ns3.
Referenced by DoRun().
DoRun()
void CoDelQueueDiscControlLawTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 388 of file codel-queue-disc-test-suite.cc.
References _codel_control_law(), ns3::CoDelQueueDisc::ControlLaw(), ns3::MilliSeconds(), NS_TEST_EXPECT_MSG_EQ, ns3::Seconds(), and ns3::CoDelQueueDisc::Time2CoDel().
The documentation for this class was generated from the following file:
src/traffic-control/test/codel-queue-disc-test-suite.cc