ns-3: ns3::Gnuplot2dDataset Class Reference
ns3::Gnuplot2dDataset Class Reference
Statistics » Gnuplot
Class to represent a 2D points plot. Set the line or points style using SetStyle() and set points using Add().
#include "gnuplot.h"
Classes
struct Data2d
struct Point
A point in a 2D plot.
Public Types
enum ErrorBars { NONE, X, Y, XY }
Whether errorbars should be used for this dataset.
enum Style {
LINES, POINTS, LINES_POINTS, DOTS,
IMPULSES, STEPS, FSTEPS, HISTEPS
}
The plotting style to use for this dataset.
Public Member Functions
Gnuplot2dDataset (const std::string &title="Untitled")
void Add (double x, double y)
void Add (double x, double y, double errorDelta)
void Add (double x, double y, double xErrorDelta, double yErrorDelta)
void AddEmptyLine ()
Add an empty line in the data output sequence.
void SetErrorBars (enum ErrorBars errorBars)
void SetStyle (enum Style style)
Public Member Functions inherited from ns3::GnuplotDataset
GnuplotDataset (const GnuplotDataset &original)
Reference-counting copy constructor.
~GnuplotDataset ()
Reference-counting destructor.
GnuplotDataset & operator= (const GnuplotDataset &original)
Reference-counting assignment operator.
void SetExtra (const std::string &extra)
Add extra formatting parameters to this dataset.
void SetTitle (const std::string &title)
Change line title.
Static Public Member Functions
static void SetDefaultErrorBars (enum ErrorBars errorBars)
Change default errorbars style for all newly created objects.
static void SetDefaultStyle (enum Style style)
Change default style for all newly created objects.
Static Public Member Functions inherited from ns3::GnuplotDataset
static void SetDefaultExtra (const std::string &extra)
Change extra formatting style parameters for newly created objects.
Private Types
typedef std::vector< struct Point > PointSet
The set of points in the dataset.
Static Private Attributes
static enum ErrorBars m_defaultErrorBars
default error bars type
static enum Style m_defaultStyle
default plot style
Additional Inherited Members
Protected Member Functions inherited from ns3::GnuplotDataset
GnuplotDataset (struct Data *data)
Called by constructors of derived classes.
Protected Attributes inherited from ns3::GnuplotDataset
struct Data * m_data
Reference counted data object.
Static Protected Attributes inherited from ns3::GnuplotDataset
static std::string m_defaultExtra = ""
Extra gnuplot parameters set on every newly created dataset.
Detailed Description
Class to represent a 2D points plot. Set the line or points style using SetStyle() and set points using Add().
Definition at line 117 of file gnuplot.h.
Member Typedef Documentation
PointSet
typedef std::vector<struct Point> ns3::Gnuplot2dDataset::PointSet private
The set of points in the dataset.
Definition at line 226 of file gnuplot.h.
Member Enumeration Documentation
ErrorBars
enum ns3::Gnuplot2dDataset::ErrorBars
Whether errorbars should be used for this dataset.
Enumerator
NONE
X
Y
XY
Definition at line 137 of file gnuplot.h.
Style
enum ns3::Gnuplot2dDataset::Style
The plotting style to use for this dataset.
Enumerator
LINES
POINTS
LINES_POINTS
DOTS
IMPULSES
STEPS
FSTEPS
HISTEPS
Definition at line 123 of file gnuplot.h.
Constructor & Destructor Documentation
Gnuplot2dDataset()
ns3::Gnuplot2dDataset::Gnuplot2dDataset (const std::string & title = "Untitled")
Parameters
title the title to be associated to this dataset.
Create an empty dataset. Usually, the dataset's title is displayed in the legend box.
Definition at line 331 of file gnuplot.cc.
Member Function Documentation
Add() [1/3]
void ns3::Gnuplot2dDataset::Add (double x, double y)
Parameters
x x coord to new data point
y y coord to new data point
Use this method with error bar style NONE.
Definition at line 359 of file gnuplot.cc.
References data, ns3::GnuplotDataset::m_data, NONE, NS_ASSERT, and sample-rng-plot::x.
Referenced by Experiment::AdvancePosition(), ChangeSignalAndReportRate(), Experiment::CheckThroughput(), anonymous_namespace{gnuplot-example.cc}::Create2DPlotFile(), anonymous_namespace{gnuplot-example.cc}::Create2DPlotWithErrorBarsFile(), Experiment::IncrementCw(), TestDeterministic(), and TestDeterministicByTime().
Add() [2/3]
void ns3::Gnuplot2dDataset::Add (double x, double y, double errorDelta)
Parameters
x x coord to new data point
y y coord to new data point
errorDelta x and y data point uncertainty
Use this method with error bar style X or Y.
Definition at line 373 of file gnuplot.cc.
References data, ns3::GnuplotDataset::m_data, NS_ASSERT, sample-rng-plot::x, X, and Y.
Add() [3/3]
void ns3::Gnuplot2dDataset::Add (double x, double y, double xErrorDelta, double yErrorDelta)
Parameters
x x coord to new data point
y y coord to new data point
xErrorDelta x data point uncertainty
yErrorDelta y data point uncertainty
Use this method with error bar style XY.
Definition at line 388 of file gnuplot.cc.
References data, ns3::GnuplotDataset::m_data, NS_ASSERT, sample-rng-plot::x, and XY.
AddEmptyLine()
void ns3::Gnuplot2dDataset::AddEmptyLine ()
Add an empty line in the data output sequence.
Empty lines in the plot data break continuous lines and do other things in the output.
Definition at line 402 of file gnuplot.cc.
References data, and ns3::GnuplotDataset::m_data.
SetDefaultErrorBars()
void ns3::Gnuplot2dDataset::SetDefaultErrorBars (enum ErrorBars errorBars) static
Change default errorbars style for all newly created objects.
Parameters
errorBars the style of errorbars to use for newly created datasets.
Definition at line 348 of file gnuplot.cc.
References m_defaultErrorBars.
Referenced by ns3::GnuplotAggregator::Set2dDatasetDefaultErrorBars().
SetDefaultStyle()
void ns3::Gnuplot2dDataset::SetDefaultStyle (enum Style style) static
Change default style for all newly created objects.
Parameters
style the style of plotting to use for newly created datasets.
Definition at line 337 of file gnuplot.cc.
References m_defaultStyle.
Referenced by ns3::GnuplotAggregator::Set2dDatasetDefaultStyle().
SetErrorBars()
void ns3::Gnuplot2dDataset::SetErrorBars (enum ErrorBars errorBars)
Parameters
errorBars the style of errorbars to display.
If you use any style other than none, you need to make sure you store the delta information in this dataset with the right GnuplotDataset::Add method.
Definition at line 353 of file gnuplot.cc.
References ns3::GnuplotDataset::m_data.
Referenced by anonymous_namespace{gnuplot-example.cc}::Create2DPlotWithErrorBarsFile().
SetStyle()
void ns3::Gnuplot2dDataset::SetStyle (enum Style style)
Parameters
style the style of plotting to use for this dataset.
Definition at line 342 of file gnuplot.cc.
References ns3::GnuplotDataset::m_data.
Referenced by Experiment::Experiment(), anonymous_namespace{gnuplot-example.cc}::Create2DPlotFile(), anonymous_namespace{gnuplot-example.cc}::Create2DPlotWithErrorBarsFile(), TestDeterministic(), and TestDeterministicByTime().
Member Data Documentation
m_defaultErrorBars
enum ErrorBars ns3::Gnuplot2dDataset::m_defaultErrorBars static private
default error bars type
Definition at line 226 of file gnuplot.h.
Referenced by SetDefaultErrorBars().
m_defaultStyle
enum Style ns3::Gnuplot2dDataset::m_defaultStyle static private
default plot style
Definition at line 226 of file gnuplot.h.
Referenced by SetDefaultStyle().
The documentation for this class was generated from the following files:
src/stats/model/gnuplot.h
src/stats/model/gnuplot.cc