ns-3: DsrSRHeaderTest Class Reference
DsrSRHeaderTest Class Reference
DSR Routing » DSR routing module tests | Test suites
Unit test for Source Route.
Public Member Functions
DsrSRHeaderTest ()
~DsrSRHeaderTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Unit test for Source Route.
Definition at line 205 of file dsr-test-suite.cc.
Constructor & Destructor Documentation
DsrSRHeaderTest()
DsrSRHeaderTest::DsrSRHeaderTest ()
Definition at line 213 of file dsr-test-suite.cc.
~DsrSRHeaderTest()
DsrSRHeaderTest::~DsrSRHeaderTest ()
Definition at line 217 of file dsr-test-suite.cc.
Member Function Documentation
DoRun()
void DsrSRHeaderTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 221 of file dsr-test-suite.cc.
References ns3::dsr::DsrOptionField::AddDsrOption(), ns3::Packet::AddHeader(), ns3::dsr::DsrOptionSRHeader::GetNodeAddress(), ns3::dsr::DsrOptionSRHeader::GetSalvage(), ns3::dsr::DsrOptionSRHeader::GetSegmentsLeft(), NS_TEST_EXPECT_MSG_EQ, ns3::Packet::RemoveAtStart(), ns3::Packet::RemoveHeader(), ns3::dsr::DsrOptionSRHeader::SetNodesAddress(), ns3::dsr::DsrOptionSRHeader::SetNumberAddress(), ns3::dsr::DsrOptionSRHeader::SetSalvage(), and ns3::dsr::DsrOptionSRHeader::SetSegmentsLeft().
The documentation for this class was generated from the following file:
src/dsr/test/dsr-test-suite.cc