ns-3: LteCqiGenerationDlPowerControlTestCase Class Reference
LteCqiGenerationDlPowerControlTestCase Class Reference
LTE Models » lte module tests | Test suites
This test is very similar to LteCqiGenerationTestCase. The difference is that in this test is enabled the downlink power control.
#include "lte-test-cqi-generation.h"
Public Member Functions
LteCqiGenerationDlPowerControlTestCase (std::string name, uint8_t cell0Pa, uint8_t cell1Pa, uint16_t dlMcs, uint16_t ulMcs)
Constructor.
virtual ~LteCqiGenerationDlPowerControlTestCase ()
void DlScheduling (DlSchedulingCallbackInfo dlInfo)
DL Scheduling function.
void UlScheduling (uint32_t frameNo, uint32_t subframeNo, uint16_t rnti, uint8_t mcs, uint16_t sizeTb)
UL Scheduling function.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
uint8_t m_cell0Pa
cell #0 PA
uint8_t m_cell1Pa
cell #1 PA
uint16_t m_dlMcs
the DL MCS
uint16_t m_ulMcs
the UL MCS
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
This test is very similar to LteCqiGenerationTestCase. The difference is that in this test is enabled the downlink power control.
Definition at line 102 of file lte-test-cqi-generation.h.
Constructor & Destructor Documentation
LteCqiGenerationDlPowerControlTestCase()
LteCqiGenerationDlPowerControlTestCase::LteCqiGenerationDlPowerControlTestCase (std::string name, uint8_t cell0Pa, uint8_t cell1Pa, uint16_t dlMcs, uint16_t ulMcs)
Constructor.
Parameters
name reference name
cell0Pa cell # 0 PA
cell1Pa cell # 1 PA
dlMcs DL MCS
ulMcs UL MCS
Definition at line 241 of file lte-test-cqi-generation.cc.
References NS_LOG_INFO.
~LteCqiGenerationDlPowerControlTestCase()
LteCqiGenerationDlPowerControlTestCase::~LteCqiGenerationDlPowerControlTestCase () virtual
Definition at line 252 of file lte-test-cqi-generation.cc.
Member Function Documentation
DlScheduling()
void LteCqiGenerationDlPowerControlTestCase::DlScheduling (DlSchedulingCallbackInfo dlInfo)
DL Scheduling function.
Parameters
dlInfo DL info
Definition at line 257 of file lte-test-cqi-generation.cc.
References m_dlMcs, ns3::DlSchedulingCallbackInfo::mcsTb1, ns3::MilliSeconds(), ns3::Now(), and NS_TEST_ASSERT_MSG_EQ.
Referenced by LteTestDlSchedulingCallback2().
DoRun()
void LteCqiGenerationDlPowerControlTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 280 of file lte-test-cqi-generation.cc.
References ns3::LteHelper::ActivateDataRadioBearer(), ns3::ListPositionAllocator::Add(), ns3::LteUeMac::AssignStreams(), ns3::LteHelper::Attach(), ns3::LteFfrSimple::ChangePdschConfigDedicated(), ns3::Config::Connect(), ns3::NodeContainer::Create(), ns3::NetDeviceContainer::Get(), ns3::LteUeNetDevice::GetMac(), ns3::PointerValue::GetObject(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), LteTestDlSchedulingCallback2(), LteTestUlSchedulingCallback2(), m_cell0Pa, m_cell1Pa, ns3::MakeBoundCallback(), third::mobility, NS_LOG_DEBUG, ns3::LteRrcSap::PdschConfigDedicated::pa, ns3::Config::Reset(), ns3::Seconds(), ns3::Config::SetDefault(), ns3::LteHelper::SetFfrAlgorithmType(), ns3::LteFfrSimple::SetPdschConfigDedicated(), ns3::LteHelper::SetSchedulerAttribute(), and ns3::LteHelper::SetSchedulerType().
UlScheduling()
void LteCqiGenerationDlPowerControlTestCase::UlScheduling (uint32_t frameNo, uint32_t subframeNo, uint16_t rnti, uint8_t mcs, uint16_t sizeTb)
UL Scheduling function.
Parameters
frameNo frame number
subframeNo subframe number
rnti the RNTI
mcs the MCS
sizeTb size
Definition at line 268 of file lte-test-cqi-generation.cc.
References m_ulMcs, ns3::MilliSeconds(), ns3::Now(), and NS_TEST_ASSERT_MSG_EQ.
Referenced by LteTestUlSchedulingCallback2().
Member Data Documentation
m_cell0Pa
uint8_t LteCqiGenerationDlPowerControlTestCase::m_cell0Pa private
cell #0 PA
Definition at line 138 of file lte-test-cqi-generation.h.
Referenced by DoRun().
m_cell1Pa
uint8_t LteCqiGenerationDlPowerControlTestCase::m_cell1Pa private
cell #1 PA
Definition at line 139 of file lte-test-cqi-generation.h.
Referenced by DoRun().
m_dlMcs
uint16_t LteCqiGenerationDlPowerControlTestCase::m_dlMcs private
the DL MCS
Definition at line 141 of file lte-test-cqi-generation.h.
Referenced by DlScheduling().
m_ulMcs
uint16_t LteCqiGenerationDlPowerControlTestCase::m_ulMcs private
the UL MCS
Definition at line 142 of file lte-test-cqi-generation.h.
Referenced by UlScheduling().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-cqi-generation.h
src/lte/test/lte-test-cqi-generation.cc