ns-3: ns3::dot11s::IePrep Class Reference
ns3::dot11s::IePrep Class Reference
Mesh Device » IEEE 802.11s draft
See 7.3.2.97 of 802.11s draft 2.07.
#include "ie-dot11s-prep.h"
Public Member Functions
IePrep ()
~IePrep ()
void DecrementTtl ()
Decrement TTL function.
virtual uint8_t DeserializeInformationField (Buffer::Iterator start, uint8_t length)
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
virtual WifiInformationElementId ElementId () const
Mac48Address GetDestinationAddress () const
Get destination address function.
uint32_t GetDestinationSeqNumber () const
Get destination sequence number function.
uint8_t GetFlags () const
Get flags function.
uint8_t GetHopcount () const
Get hop count function.
virtual uint8_t GetInformationFieldSize () const
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
uint32_t GetLifetime () const
Get lifetime function.
uint32_t GetMetric () const
Get metric function.
Mac48Address GetOriginatorAddress () const
Get originator address function.
uint32_t GetOriginatorSeqNumber () const
Get originator sequence number.
uint32_t GetTtl () const
Get TTL function.
void IncrementMetric (uint32_t metric)
Increment metric function.
virtual void Print (std::ostream &os) const
Generate human-readable form of IE.
virtual void SerializeInformationField (Buffer::Iterator i) const
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
void SetDestinationAddress (Mac48Address dest_address)
Set destination address function.
void SetDestinationSeqNumber (uint32_t dest_seq_number)
Set destination sequence number function.
void SetFlags (uint8_t flags)
Set flags function.
void SetHopcount (uint8_t hopcount)
Set hop count function.
void SetLifetime (uint32_t lifetime)
Set lifetime function.
void SetMetric (uint32_t metric)
Set metric function.
void SetOriginatorAddress (Mac48Address originator_address)
Set originator address function.
void SetOriginatorSeqNumber (uint32_t originator_seq_number)
Set originator sequence number function.
void SetTtl (uint8_t ttl)
Set TTL function.
Public Member Functions inherited from ns3::WifiInformationElement
virtual ~WifiInformationElement ()
Buffer::Iterator Deserialize (Buffer::Iterator i)
Deserialize entire IE, which must be present.
Buffer::Iterator DeserializeIfPresent (Buffer::Iterator i)
Deserialize entire IE if it is present.
virtual WifiInformationElementId ElementIdExt () const
uint16_t GetSerializedSize () const
Get the size of the serialized IE including Element ID and length fields.
virtual bool operator== (WifiInformationElement const &a) const
Compare two IEs for equality by ID & Length, and then through memcmp of serialised version.
Buffer::Iterator Serialize (Buffer::Iterator i) const
Serialize entire IE including Element ID and length fields.
Public Member Functions inherited from ns3::SimpleRefCount< WifiInformationElement >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
Mac48Address m_destinationAddress
destination address
uint32_t m_destSeqNumber
destination sequence number
uint8_t m_flags
flags
uint8_t m_hopcount
hop count
uint32_t m_lifetime
lifetime
uint32_t m_metric
metric
Mac48Address m_originatorAddress
originator address
uint32_t m_originatorSeqNumber
originator sequence number
uint8_t m_ttl
TTL.
Friends
bool operator== (const IePrep &a, const IePrep &b)
equality operator
Detailed Description
See 7.3.2.97 of 802.11s draft 2.07.
Definition at line 33 of file ie-dot11s-prep.h.
Constructor & Destructor Documentation
IePrep()
ns3::dot11s::IePrep::IePrep ()
Definition at line 33 of file ie-dot11s-prep.cc.
~IePrep()
ns3::dot11s::IePrep::~IePrep ()
Definition at line 30 of file ie-dot11s-prep.cc.
Member Function Documentation
DecrementTtl()
void ns3::dot11s::IePrep::DecrementTtl ()
Decrement TTL function.
Definition at line 135 of file ie-dot11s-prep.cc.
References m_hopcount, and m_ttl.
DeserializeInformationField()
uint8_t ns3::dot11s::IePrep::DeserializeInformationField (Buffer::Iterator start, uint8_t length) virtual
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
length
Returns
the number of bytes read
Implements ns3::WifiInformationElement.
Definition at line 161 of file ie-dot11s-prep.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_destinationAddress, m_destSeqNumber, m_flags, m_hopcount, m_lifetime, m_metric, m_originatorAddress, m_originatorSeqNumber, m_ttl, ns3::ReadFrom(), ns3::Buffer::Iterator::ReadLsbtohU32(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
ElementId()
WifiInformationElementId ns3::dot11s::IePrep::ElementId () const virtual
Returns
Own unique Element ID
Implements ns3::WifiInformationElement.
Definition at line 40 of file ie-dot11s-prep.cc.
References IE_PREP.
GetDestinationAddress()
Mac48Address ns3::dot11s::IePrep::GetDestinationAddress () const
Get destination address function.
Returns
the destination MAC address
Definition at line 110 of file ie-dot11s-prep.cc.
References m_destinationAddress.
Referenced by ns3::dot11s::HwmpProtocol::ReceivePrep().
GetDestinationSeqNumber()
uint32_t ns3::dot11s::IePrep::GetDestinationSeqNumber () const
Get destination sequence number function.
Returns
the destination sequence number
Definition at line 105 of file ie-dot11s-prep.cc.
References m_destSeqNumber.
Referenced by ns3::dot11s::HwmpProtocol::ReceivePrep().
GetFlags()
uint8_t ns3::dot11s::IePrep::GetFlags () const
Get flags function.
Returns
the flags
Definition at line 90 of file ie-dot11s-prep.cc.
References m_flags.
GetHopcount()
uint8_t ns3::dot11s::IePrep::GetHopcount () const
Get hop count function.
Returns
the hop count
Definition at line 95 of file ie-dot11s-prep.cc.
References m_hopcount.
GetInformationFieldSize()
uint8_t ns3::dot11s::IePrep::GetInformationFieldSize () const virtual
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
This is the value that will appear in the second octet of the entire IE - the length field)
Returns
the length of serialized information
Implements ns3::WifiInformationElement.
Definition at line 176 of file ie-dot11s-prep.cc.
GetLifetime()
uint32_t ns3::dot11s::IePrep::GetLifetime () const
Get lifetime function.
Returns
the lifetime
Definition at line 130 of file ie-dot11s-prep.cc.
References m_lifetime.
Referenced by ns3::dot11s::HwmpProtocol::ReceivePrep().
GetMetric()
uint32_t ns3::dot11s::IePrep::GetMetric () const
Get metric function.
Returns
the metric
Definition at line 115 of file ie-dot11s-prep.cc.
References m_metric.
Referenced by ns3::dot11s::HwmpProtocol::ReceivePrep().
GetOriginatorAddress()
Mac48Address ns3::dot11s::IePrep::GetOriginatorAddress () const
Get originator address function.
Returns
the MAC address of the originator
Definition at line 120 of file ie-dot11s-prep.cc.
References m_originatorAddress.
Referenced by ns3::dot11s::HwmpProtocol::ReceivePrep().
GetOriginatorSeqNumber()
uint32_t ns3::dot11s::IePrep::GetOriginatorSeqNumber () const
Get originator sequence number.
Returns
the originator sequence number
Definition at line 125 of file ie-dot11s-prep.cc.
References m_originatorSeqNumber.
GetTtl()
uint32_t ns3::dot11s::IePrep::GetTtl () const
Get TTL function.
Returns
the TTL
Definition at line 100 of file ie-dot11s-prep.cc.
References m_ttl.
IncrementMetric()
void ns3::dot11s::IePrep::IncrementMetric (uint32_t metric)
Increment metric function.
Parameters
metric the metric to increment
Definition at line 142 of file ie-dot11s-prep.cc.
References m_metric.
Referenced by ns3::dot11s::HwmpProtocol::ReceivePrep().
Print()
void ns3::dot11s::IePrep::Print (std::ostream & os) const virtual
Generate human-readable form of IE.
Parameters
os output stream
Reimplemented from ns3::WifiInformationElement.
Definition at line 190 of file ie-dot11s-prep.cc.
References m_destinationAddress, m_destSeqNumber, m_flags, m_hopcount, m_lifetime, m_metric, m_originatorAddress, m_originatorSeqNumber, and m_ttl.
Referenced by ns3::dot11s::operator<<().
SerializeInformationField()
void ns3::dot11s::IePrep::SerializeInformationField (Buffer::Iterator start) const virtual
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
Implements ns3::WifiInformationElement.
Definition at line 148 of file ie-dot11s-prep.cc.
References m_destinationAddress, m_destSeqNumber, m_flags, m_hopcount, m_lifetime, m_metric, m_originatorAddress, m_originatorSeqNumber, m_ttl, ns3::Buffer::Iterator::WriteHtolsbU32(), ns3::WriteTo(), and ns3::Buffer::Iterator::WriteU8().
SetDestinationAddress()
void ns3::dot11s::IePrep::SetDestinationAddress (Mac48Address dest_address)
Set destination address function.
Parameters
dest_address
Definition at line 65 of file ie-dot11s-prep.cc.
References m_destinationAddress.
Referenced by MeshInformationElementVectorBist::DoRun(), and ns3::dot11s::HwmpProtocol::SendPrep().
SetDestinationSeqNumber()
void ns3::dot11s::IePrep::SetDestinationSeqNumber (uint32_t dest_seq_number)
Set destination sequence number function.
Parameters
dest_seq_number the destination sequence number
Definition at line 60 of file ie-dot11s-prep.cc.
References m_destSeqNumber.
Referenced by MeshInformationElementVectorBist::DoRun(), and ns3::dot11s::HwmpProtocol::SendPrep().
SetFlags()
void ns3::dot11s::IePrep::SetFlags (uint8_t flags)
Set flags function.
Parameters
flags the flags to set
Definition at line 45 of file ie-dot11s-prep.cc.
References m_flags.
Referenced by MeshInformationElementVectorBist::DoRun().
SetHopcount()
void ns3::dot11s::IePrep::SetHopcount (uint8_t hopcount)
Set hop count function.
Parameters
hopcount the hop count
Definition at line 50 of file ie-dot11s-prep.cc.
References m_hopcount.
Referenced by MeshInformationElementVectorBist::DoRun(), and ns3::dot11s::HwmpProtocol::SendPrep().
SetLifetime()
void ns3::dot11s::IePrep::SetLifetime (uint32_t lifetime)
Set lifetime function.
Parameters
lifetime the lifetime
Definition at line 85 of file ie-dot11s-prep.cc.
References m_lifetime.
Referenced by MeshInformationElementVectorBist::DoRun(), and ns3::dot11s::HwmpProtocol::SendPrep().
SetMetric()
void ns3::dot11s::IePrep::SetMetric (uint32_t metric)
Set metric function.
Parameters
metric the metric to set
Definition at line 70 of file ie-dot11s-prep.cc.
References m_metric.
Referenced by MeshInformationElementVectorBist::DoRun(), and ns3::dot11s::HwmpProtocol::SendPrep().
SetOriginatorAddress()
void ns3::dot11s::IePrep::SetOriginatorAddress (Mac48Address originator_address)
Set originator address function.
Parameters
originator_address the originator address
Definition at line 75 of file ie-dot11s-prep.cc.
References m_originatorAddress.
Referenced by MeshInformationElementVectorBist::DoRun(), and ns3::dot11s::HwmpProtocol::SendPrep().
SetOriginatorSeqNumber()
void ns3::dot11s::IePrep::SetOriginatorSeqNumber (uint32_t originator_seq_number)
Set originator sequence number function.
Parameters
originator_seq_number the originator sequence number
Definition at line 80 of file ie-dot11s-prep.cc.
References m_originatorSeqNumber.
Referenced by MeshInformationElementVectorBist::DoRun(), and ns3::dot11s::HwmpProtocol::SendPrep().
SetTtl()
void ns3::dot11s::IePrep::SetTtl (uint8_t ttl)
Set TTL function.
Parameters
ttl the TTL
Definition at line 55 of file ie-dot11s-prep.cc.
References m_ttl.
Referenced by MeshInformationElementVectorBist::DoRun(), and ns3::dot11s::HwmpProtocol::SendPrep().
Friends And Related Function Documentation
operator==
bool operator== (const IePrep & a, const IePrep & b) friend
equality operator
Parameters
a lhs
b rhs
Returns
true if equal
Definition at line 198 of file ie-dot11s-prep.cc.
Member Data Documentation
m_destinationAddress
Mac48Address ns3::dot11s::IePrep::m_destinationAddress private
destination address
Definition at line 149 of file ie-dot11s-prep.h.
Referenced by DeserializeInformationField(), GetDestinationAddress(), ns3::dot11s::operator==(), Print(), SerializeInformationField(), and SetDestinationAddress().
m_destSeqNumber
uint32_t ns3::dot11s::IePrep::m_destSeqNumber private
destination sequence number
Definition at line 150 of file ie-dot11s-prep.h.
Referenced by DeserializeInformationField(), GetDestinationSeqNumber(), ns3::dot11s::operator==(), Print(), SerializeInformationField(), and SetDestinationSeqNumber().
m_flags
uint8_t ns3::dot11s::IePrep::m_flags private
flags
Definition at line 146 of file ie-dot11s-prep.h.
Referenced by DeserializeInformationField(), GetFlags(), ns3::dot11s::operator==(), Print(), SerializeInformationField(), and SetFlags().
m_hopcount
uint8_t ns3::dot11s::IePrep::m_hopcount private
hop count
Definition at line 147 of file ie-dot11s-prep.h.
Referenced by DecrementTtl(), DeserializeInformationField(), GetHopcount(), ns3::dot11s::operator==(), Print(), SerializeInformationField(), and SetHopcount().
m_lifetime
uint32_t ns3::dot11s::IePrep::m_lifetime private
lifetime
Definition at line 151 of file ie-dot11s-prep.h.
Referenced by DeserializeInformationField(), GetLifetime(), ns3::dot11s::operator==(), Print(), SerializeInformationField(), and SetLifetime().
m_metric
uint32_t ns3::dot11s::IePrep::m_metric private
metric
Definition at line 152 of file ie-dot11s-prep.h.
Referenced by DeserializeInformationField(), GetMetric(), IncrementMetric(), ns3::dot11s::operator==(), Print(), SerializeInformationField(), and SetMetric().
m_originatorAddress
Mac48Address ns3::dot11s::IePrep::m_originatorAddress private
originator address
Definition at line 153 of file ie-dot11s-prep.h.
Referenced by DeserializeInformationField(), GetOriginatorAddress(), ns3::dot11s::operator==(), Print(), SerializeInformationField(), and SetOriginatorAddress().
m_originatorSeqNumber
uint32_t ns3::dot11s::IePrep::m_originatorSeqNumber private
originator sequence number
Definition at line 154 of file ie-dot11s-prep.h.
Referenced by DeserializeInformationField(), GetOriginatorSeqNumber(), ns3::dot11s::operator==(), Print(), SerializeInformationField(), and SetOriginatorSeqNumber().
m_ttl
uint8_t ns3::dot11s::IePrep::m_ttl private
TTL.
Definition at line 148 of file ie-dot11s-prep.h.
Referenced by DecrementTtl(), DeserializeInformationField(), GetTtl(), ns3::dot11s::operator==(), Print(), SerializeInformationField(), and SetTtl().
The documentation for this class was generated from the following files:
src/mesh/model/dot11s/ie-dot11s-prep.h
src/mesh/model/dot11s/ie-dot11s-prep.cc