ns-3: ns3::Ipv6ExtensionHopByHopHeader Class Reference
ns3::Ipv6ExtensionHopByHopHeader Class Reference
Internet » IPv6 classes and sub-modules » IPV6 Header extension system.
Header of IPv6 Extension "Hop by Hop".
#include "ipv6-extension-header.h"
Public Member Functions
Ipv6ExtensionHopByHopHeader ()
Constructor.
virtual ~Ipv6ExtensionHopByHopHeader ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
virtual uint32_t GetSerializedSize () const
Get the serialized size of the packet.
virtual void Print (std::ostream &os) const
Print some information about the packet.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
Public Member Functions inherited from ns3::Ipv6ExtensionHeader
Ipv6ExtensionHeader ()
Constructor.
virtual ~Ipv6ExtensionHeader ()
Destructor.
uint16_t GetLength () const
Get the length of the extension.
uint8_t GetNextHeader () const
Get the next header.
void SetLength (uint16_t length)
brief Set the length of the extension.
void SetNextHeader (uint8_t nextHeader)
Set the "Next header" field.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Public Member Functions inherited from ns3::OptionField
OptionField (uint32_t optionsOffset)
Constructor.
~OptionField ()
Destructor.
void AddOption (Ipv6OptionHeader const &option)
Serialize the option, prepending pad1 or padn option as necessary.
uint32_t Deserialize (Buffer::Iterator start, uint32_t length)
Deserialize the packet.
Buffer GetOptionBuffer ()
Get the buffer.
uint32_t GetOptionsOffset ()
Get the offset where the options begin, measured from the start of the extension header.
uint32_t GetSerializedSize () const
Get the serialized size of the packet.
void Serialize (Buffer::Iterator start) const
Serialize all added options.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Ipv6ExtensionHeader
static TypeId GetTypeId ()
Get the type identificator.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::Ipv6ExtensionHeader
uint8_t m_length
The "length" field.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Header of IPv6 Extension "Hop by Hop".
Definition at line 223 of file ipv6-extension-header.h.
Constructor & Destructor Documentation
Ipv6ExtensionHopByHopHeader()
ns3::Ipv6ExtensionHopByHopHeader::Ipv6ExtensionHopByHopHeader ()
Constructor.
Definition at line 224 of file ipv6-extension-header.cc.
~Ipv6ExtensionHopByHopHeader()
ns3::Ipv6ExtensionHopByHopHeader::~Ipv6ExtensionHopByHopHeader () virtual
Destructor.
Definition at line 229 of file ipv6-extension-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::Ipv6ExtensionHopByHopHeader::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start Buffer iterator
Returns
size of the packet
Reimplemented from ns3::Ipv6ExtensionHeader.
Definition at line 252 of file ipv6-extension-header.cc.
References ns3::OptionField::Deserialize(), ns3::Ipv6ExtensionHeader::GetLength(), GetSerializedSize(), ns3::Ipv6ExtensionHeader::m_length, ns3::Buffer::Iterator::ReadU8(), ns3::Ipv6ExtensionHeader::SetNextHeader(), and visualizer.core::start().
Referenced by ns3::SixLowPanNetDevice::DecompressLowPanNhc().
GetInstanceTypeId()
TypeId ns3::Ipv6ExtensionHopByHopHeader::GetInstanceTypeId () const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::Ipv6ExtensionHeader.
Definition at line 219 of file ipv6-extension-header.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::Ipv6ExtensionHopByHopHeader::GetSerializedSize () const virtual
Get the serialized size of the packet.
Returns
size
Reimplemented from ns3::Ipv6ExtensionHeader.
Definition at line 238 of file ipv6-extension-header.cc.
References ns3::OptionField::GetSerializedSize().
Referenced by ns3::SixLowPanNetDevice::CompressLowPanNhc(), Deserialize(), and Serialize().
GetTypeId()
TypeId ns3::Ipv6ExtensionHopByHopHeader::GetTypeId () static
Get the type identificator.
Returns
type identificator
Definition at line 209 of file ipv6-extension-header.cc.
References ns3::TypeId::AddConstructor().
Referenced by GetInstanceTypeId().
Print()
void ns3::Ipv6ExtensionHopByHopHeader::Print (std::ostream & os) const virtual
Print some information about the packet.
Parameters
os output stream
Returns
info about this packet
Reimplemented from ns3::Ipv6ExtensionHeader.
Definition at line 233 of file ipv6-extension-header.cc.
References ns3::Ipv6ExtensionHeader::GetLength(), and ns3::Ipv6ExtensionHeader::GetNextHeader().
Serialize()
void ns3::Ipv6ExtensionHopByHopHeader::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start Buffer iterator
Reimplemented from ns3::Ipv6ExtensionHeader.
Definition at line 243 of file ipv6-extension-header.cc.
References ns3::Ipv6ExtensionHeader::GetNextHeader(), GetSerializedSize(), ns3::OptionField::Serialize(), visualizer.core::start(), and ns3::Buffer::Iterator::WriteU8().
Referenced by ns3::SixLowPanNetDevice::CompressLowPanNhc().
The documentation for this class was generated from the following files:
src/internet/model/ipv6-extension-header.h
src/internet/model/ipv6-extension-header.cc