ns-3: ns3::WifiMacQueue Class Reference
ns3::WifiMacQueue Class Reference
Wifi Models
#include "wifi-mac-queue.h"
Public Types
enum DropPolicy { DROP_NEWEST, DROP_OLDEST }
drop policy
Public Types inherited from ns3::Queue< WifiMacQueueItem >
typedef WifiMacQueueItem ItemType
Define ItemType as the type of the stored elements.
Public Member Functions
WifiMacQueue ()
~WifiMacQueue ()
Ptr< WifiMacQueueItem > Dequeue (void)
Dequeue the packet in the front of the queue.
Ptr< WifiMacQueueItem > Dequeue (WifiMacQueue::ConstIterator pos)
Dequeue the item at position pos in the queue.
Ptr< WifiMacQueueItem > DequeueByAddress (Mac48Address dest)
Search and return, if present in the queue, the first packet (either Data frame or QoS Data frame) having the receiver address equal to addr.
Ptr< WifiMacQueueItem > DequeueByTid (uint8_t tid)
Search and return, if present in the queue, the first packet having the TID equal to tid.
Ptr< WifiMacQueueItem > DequeueByTidAndAddress (uint8_t tid, Mac48Address dest)
Search and return, if present in the queue, the first packet having the address indicated by type equal to addr, and TID equal to tid.
Ptr< WifiMacQueueItem > DequeueFirstAvailable (const Ptr< QosBlockedDestinations > blockedPackets=nullptr)
Return first available packet for transmission.
bool Enqueue (Ptr< WifiMacQueueItem > item)
Enqueue the given Wifi MAC queue item at the end of the queue.
Time GetMaxDelay (void) const
Return the maximum delay before the packet is discarded.
uint32_t GetNBytes (void)
uint32_t GetNPackets (void)
uint32_t GetNPacketsByAddress (Mac48Address dest)
Return the number of packets having destination address specified by dest.
uint32_t GetNPacketsByTidAndAddress (uint8_t tid, Mac48Address dest)
Return the number of QoS packets having TID equal to tid and destination address equal to dest.
bool Insert (ConstIterator pos, Ptr< WifiMacQueueItem > item)
Enqueue the given Wifi MAC queue item before the given position.
bool IsEmpty (void)
Ptr< const WifiMacQueueItem > Peek (void) const
Peek the packet in the front of the queue.
ConstIterator PeekByAddress (Mac48Address dest, ConstIterator pos=EMPTY) const
Search and return, if present in the queue, the first packet (either Data frame or QoS Data frame) having the receiver address equal to addr.
ConstIterator PeekByTid (uint8_t tid, ConstIterator pos=EMPTY) const
Search and return, if present in the queue, the first packet having the TID equal to tid.
ConstIterator PeekByTidAndAddress (uint8_t tid, Mac48Address dest, ConstIterator pos=EMPTY) const
Search and return, if present in the queue, the first packet having the receiver address equal to dest, and TID equal to tid.
ConstIterator PeekFirstAvailable (const Ptr< QosBlockedDestinations > blockedPackets=nullptr, ConstIterator pos=EMPTY) const
Return first available packet for transmission.
bool PushFront (Ptr< WifiMacQueueItem > item)
Enqueue the given Wifi MAC queue item at the front of the queue.
ConstIterator Remove (ConstIterator pos, bool removeExpired=false)
Remove the item at position pos in the queue and return an iterator pointing to the item following the removed one.
bool Remove (Ptr< const Packet > packet)
If exists, removes packet from queue and returns true.
Ptr< WifiMacQueueItem > Remove (void)
Remove the packet in the front of the queue.
void SetMaxDelay (Time delay)
Set the maximum delay before the packet is discarded.
Public Member Functions inherited from ns3::Queue< WifiMacQueueItem >
Queue ()
virtual ~Queue ()
void Flush (void)
Flush the queue.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Queue< WifiMacQueueItem >
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static const ConstIterator EMPTY = std::list<Ptr<WifiMacQueueItem>> ().end ()
Invalid iterator to signal an empty queue.
Private Member Functions
bool TtlExceeded (ConstIterator &it)
Remove the item pointed to by the iterator it if it has been in the queue for too long.
Private Attributes
DropPolicy m_dropPolicy
Drop behavior of queue.
bool m_expiredPacketsPresent
True if expired packets are in the queue.
Time m_maxDelay
Time to live for packets in the queue.
TracedCallback< Ptr< const WifiMacQueueItem > > m_traceExpired
Traced callback: fired when a packet is dropped due to lifetime expiration.
NS_LOG_TEMPLATE_DECLARE
redefinition of the log component
Additional Inherited Members
Protected Types inherited from ns3::Queue< WifiMacQueueItem >
typedef std::list< Ptr< WifiMacQueueItem > >::const_iterator ConstIterator
Const iterator.
typedef std::list< Ptr< WifiMacQueueItem > >::iterator Iterator
Iterator.
Protected Member Functions inherited from ns3::Queue< WifiMacQueueItem >
Iterator begin (void)
Get an iterator which refers to the first item in the queue.
ConstIterator begin (void) const
Get a const iterator which refers to the first item in the queue.
Ptr< WifiMacQueueItem > DoDequeue (ConstIterator pos)
Pull the item to dequeue from the queue.
bool DoEnqueue (ConstIterator pos, Ptr< WifiMacQueueItem > item)
Push an item in the queue.
Ptr< const WifiMacQueueItem > DoPeek (ConstIterator pos) const
Peek the front item in the queue.
Ptr< WifiMacQueueItem > DoRemove (ConstIterator pos)
Pull the item to drop from the queue.
void DropAfterDequeue (Ptr< WifiMacQueueItem > item)
Drop a packet after dequeue.
void DropBeforeEnqueue (Ptr< WifiMacQueueItem > item)
Drop a packet before enqueue.
Iterator end (void)
Get an iterator which indicates past-the-last item in the queue.
ConstIterator end (void) const
Get a const iterator which indicates past-the-last item in the queue.
Detailed Description
This queue implements the timeout procedure described in (Section 9.19.2.6 "Retransmit procedures" paragraph 6; IEEE 802.11-2012).
When a packet is received by the MAC, to be sent to the PHY, it is queued in the internal queue after being tagged by the current time.
When a packet is dequeued, the queue checks its timestamp to verify whether or not it should be dropped. If dot11EDCATableMSDULifetime has elapsed, it is dropped. Otherwise, it is returned to the caller.
Definition at line 57 of file wifi-mac-queue.h.
Member Enumeration Documentation
DropPolicy
enum ns3::WifiMacQueue::DropPolicy
drop policy
Enumerator
DROP_NEWEST
DROP_OLDEST
Definition at line 69 of file wifi-mac-queue.h.
Constructor & Destructor Documentation
WifiMacQueue()
ns3::WifiMacQueue::WifiMacQueue ()
Definition at line 64 of file wifi-mac-queue.cc.
~WifiMacQueue()
ns3::WifiMacQueue::~WifiMacQueue ()
Definition at line 70 of file wifi-mac-queue.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
Dequeue() [1/2]
Ptr< WifiMacQueueItem > ns3::WifiMacQueue::Dequeue (void) virtual
Dequeue the packet in the front of the queue.
Returns
the packet
Implements ns3::Queue< WifiMacQueueItem >.
Definition at line 162 of file wifi-mac-queue.cc.
References ns3::Queue< WifiMacQueueItem >::begin(), ns3::Queue< WifiMacQueueItem >::DoDequeue(), ns3::Queue< WifiMacQueueItem >::end(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and TtlExceeded().
Referenced by DequeueByAddress(), DequeueByTid(), DequeueByTidAndAddress(), and DequeueFirstAvailable().
Dequeue() [2/2]
Ptr<WifiMacQueueItem> ns3::WifiMacQueue::Dequeue (WifiMacQueue::ConstIterator pos)
Dequeue the item at position pos in the queue.
Return a null pointer if the given iterator is invalid, the queue is empty or the lifetime of the item pointed to by the given iterator is expired.
Parameters
pos the position of the item to be dequeued
Returns
the dequeued item, if any
DequeueByAddress()
Ptr< WifiMacQueueItem > ns3::WifiMacQueue::DequeueByAddress (Mac48Address dest)
Search and return, if present in the queue, the first packet (either Data frame or QoS Data frame) having the receiver address equal to addr.
This method removes the packet from the queue. It is typically used by ns3::Txop during the CF period.
Parameters
dest the given destination
Returns
the packet
Definition at line 177 of file wifi-mac-queue.cc.
References Dequeue(), ns3::Queue< WifiMacQueueItem >::end(), NS_LOG_FUNCTION, and PeekByAddress().
DequeueByTid()
Ptr< WifiMacQueueItem > ns3::WifiMacQueue::DequeueByTid (uint8_t tid)
Search and return, if present in the queue, the first packet having the TID equal to tid.
This method removes the packet from the queue.
Parameters
tid the given TID
Returns
the packet
Definition at line 190 of file wifi-mac-queue.cc.
References Dequeue(), ns3::Queue< WifiMacQueueItem >::end(), NS_LOG_FUNCTION, and PeekByTid().
DequeueByTidAndAddress()
Ptr< WifiMacQueueItem > ns3::WifiMacQueue::DequeueByTidAndAddress (uint8_t tid, Mac48Address dest)
Search and return, if present in the queue, the first packet having the address indicated by type equal to addr, and TID equal to tid.
This method removes the packet from the queue. It is typically used by ns3::QosTxop in order to perform correct MSDU aggregation (A-MSDU).
Parameters
tid the given TID
dest the given destination
Returns
the packet
Definition at line 203 of file wifi-mac-queue.cc.
References Dequeue(), ns3::Queue< WifiMacQueueItem >::end(), NS_LOG_FUNCTION, and PeekByTidAndAddress().
DequeueFirstAvailable()
Ptr< WifiMacQueueItem > ns3::WifiMacQueue::DequeueFirstAvailable (const Ptr< QosBlockedDestinations > blockedPackets = nullptr)
Return first available packet for transmission.
A packet could be no available if it is a QoS packet with a TID and an address1 fields equal to tid and addr respectively that index a pending agreement in the BlockAckManager object. So that packet must not be transmitted until reception of an ADDBA response frame from station addressed by addr. This method removes the packet from queue.
Parameters
blockedPackets the destination address & TID pairs that are waiting for a BlockAck response
Returns
the packet
Definition at line 216 of file wifi-mac-queue.cc.
References Dequeue(), ns3::Queue< WifiMacQueueItem >::end(), NS_LOG_FUNCTION, and PeekFirstAvailable().
Enqueue()
bool ns3::WifiMacQueue::Enqueue (Ptr< WifiMacQueueItem > item) virtual
Enqueue the given Wifi MAC queue item at the end of the queue.
Parameters
item the Wifi MAC queue item to be enqueued at the end
Returns
true if success, false if the packet has been dropped
Implements ns3::Queue< WifiMacQueueItem >.
Definition at line 108 of file wifi-mac-queue.cc.
References ns3::Queue< WifiMacQueueItem >::end(), Insert(), and NS_LOG_FUNCTION.
GetMaxDelay()
Time ns3::WifiMacQueue::GetMaxDelay (void) const
Return the maximum delay before the packet is discarded.
Returns
the maximum delay
Definition at line 85 of file wifi-mac-queue.cc.
References m_maxDelay.
GetNBytes()
uint32_t ns3::WifiMacQueue::GetNBytes (void)
Returns
The number of bytes currently occupied by the packets in the Queue
Overrides the GetNBytes method provided by QueueBase
Definition at line 545 of file wifi-mac-queue.cc.
References ns3::Queue< WifiMacQueueItem >::begin(), ns3::Queue< WifiMacQueueItem >::end(), ns3::QueueBase::GetNBytes(), NS_LOG_FUNCTION, and TtlExceeded().
GetNPackets()
uint32_t ns3::WifiMacQueue::GetNPackets (void)
Returns
The number of packets currently stored in the Queue
Overrides the GetNPackets method provided by QueueBase
Definition at line 530 of file wifi-mac-queue.cc.
References ns3::Queue< WifiMacQueueItem >::begin(), ns3::Queue< WifiMacQueueItem >::end(), ns3::QueueBase::GetNPackets(), NS_LOG_FUNCTION, and TtlExceeded().
GetNPacketsByAddress()
uint32_t ns3::WifiMacQueue::GetNPacketsByAddress (Mac48Address dest)
Return the number of packets having destination address specified by dest.
Parameters
dest the given destination
Returns
the number of packets
Definition at line 469 of file wifi-mac-queue.cc.
References ns3::Queue< WifiMacQueueItem >::begin(), ns3::Queue< WifiMacQueueItem >::end(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and TtlExceeded().
GetNPacketsByTidAndAddress()
uint32_t ns3::WifiMacQueue::GetNPacketsByTidAndAddress (uint8_t tid, Mac48Address dest)
Return the number of QoS packets having TID equal to tid and destination address equal to dest.
Parameters
tid the given TID
dest the given destination
Returns
the number of QoS packets
Definition at line 492 of file wifi-mac-queue.cc.
References ns3::Queue< WifiMacQueueItem >::begin(), ns3::Queue< WifiMacQueueItem >::end(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and TtlExceeded().
GetTypeId()
TypeId ns3::WifiMacQueue::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 36 of file wifi-mac-queue.cc.
References DROP_NEWEST, DROP_OLDEST, ns3::QueueBase::GetMaxSize(), m_dropPolicy, m_traceExpired, ns3::MakeEnumAccessor(), ns3::MakeEnumChecker(), ns3::MakeQueueSizeAccessor(), ns3::MakeQueueSizeChecker(), ns3::MakeTimeAccessor(), ns3::MakeTimeChecker(), ns3::MakeTraceSourceAccessor(), ns3::MilliSeconds(), SetMaxDelay(), ns3::QueueBase::SetMaxSize(), and ns3::TypeId::SetParent().
Insert()
bool ns3::WifiMacQueue::Insert (ConstIterator pos, Ptr< WifiMacQueueItem > item)
Enqueue the given Wifi MAC queue item before the given position.
Parameters
pos the position before which the item is to be inserted
item the Wifi MAC queue item to be enqueued
Returns
true if success, false if the packet has been dropped
Definition at line 124 of file wifi-mac-queue.cc.
References ns3::Queue< WifiMacQueueItem >::begin(), ns3::Queue< WifiMacQueueItem >::DoEnqueue(), ns3::Queue< WifiMacQueueItem >::DoRemove(), DROP_OLDEST, ns3::Queue< WifiMacQueueItem >::end(), ns3::QueueBase::GetNPackets(), m_dropPolicy, NS_ASSERT_MSG(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::PACKETS, and TtlExceeded().
Referenced by Enqueue(), and PushFront().
IsEmpty()
bool ns3::WifiMacQueue::IsEmpty (void)
Returns
true if the queue is empty; false otherwise
Overrides the IsEmpty method provided by QueueBase
Definition at line 514 of file wifi-mac-queue.cc.
References ns3::Queue< WifiMacQueueItem >::begin(), ns3::Queue< WifiMacQueueItem >::end(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and TtlExceeded().
Peek()
Ptr< const WifiMacQueueItem > ns3::WifiMacQueue::Peek (void) const virtual
Peek the packet in the front of the queue.
The packet is not removed.
Returns
the packet
Implements ns3::Queue< WifiMacQueueItem >.
Definition at line 268 of file wifi-mac-queue.cc.
References ns3::Queue< WifiMacQueueItem >::begin(), ns3::Queue< WifiMacQueueItem >::DoPeek(), ns3::Queue< WifiMacQueueItem >::end(), m_expiredPacketsPresent, m_maxDelay, ns3::Simulator::Now(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
PeekByAddress()
WifiMacQueue::ConstIterator ns3::WifiMacQueue::PeekByAddress (Mac48Address dest, ConstIterator pos = EMPTY) const
Search and return, if present in the queue, the first packet (either Data frame or QoS Data frame) having the receiver address equal to addr.
If pos is a valid iterator, the search starts from the packet pointed to by the given iterator. This method does not remove the packet from the queue.
Parameters
dest the given destination
pos the iterator pointing to the packet the search starts from
Returns
an iterator pointing to the peeked packet
Definition at line 287 of file wifi-mac-queue.cc.
References ns3::Queue< WifiMacQueueItem >::begin(), EMPTY, ns3::Queue< WifiMacQueueItem >::end(), m_expiredPacketsPresent, m_maxDelay, ns3::Simulator::Now(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by DequeueByAddress().
PeekByTid()
WifiMacQueue::ConstIterator ns3::WifiMacQueue::PeekByTid (uint8_t tid, ConstIterator pos = EMPTY) const
Search and return, if present in the queue, the first packet having the TID equal to tid.
If pos is a valid iterator, the search starts from the packet pointed to by the given iterator. This method does not remove the packet from the queue.
Parameters
tid the given TID
pos the iterator pointing to the packet the search starts from
Returns
an iterator pointing to the peeked packet
Definition at line 315 of file wifi-mac-queue.cc.
References ns3::Queue< WifiMacQueueItem >::begin(), EMPTY, ns3::Queue< WifiMacQueueItem >::end(), m_expiredPacketsPresent, m_maxDelay, ns3::Simulator::Now(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by DequeueByTid().
PeekByTidAndAddress()
WifiMacQueue::ConstIterator ns3::WifiMacQueue::PeekByTidAndAddress (uint8_t tid, Mac48Address dest, ConstIterator pos = EMPTY) const
Search and return, if present in the queue, the first packet having the receiver address equal to dest, and TID equal to tid.
If pos is a valid iterator, the search starts from the packet pointed to by the given iterator. This method does not remove the packet from the queue. It is typically used by ns3::QosTxop in order to perform correct MSDU aggregation (A-MSDU).
Parameters
tid the given TID
dest the given destination
pos the iterator pointing to the packet the search starts from
Returns
an iterator pointing to the peeked packet
Definition at line 342 of file wifi-mac-queue.cc.
References ns3::Queue< WifiMacQueueItem >::begin(), EMPTY, ns3::Queue< WifiMacQueueItem >::end(), m_expiredPacketsPresent, m_maxDelay, ns3::Simulator::Now(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by DequeueByTidAndAddress().
PeekFirstAvailable()
WifiMacQueue::ConstIterator ns3::WifiMacQueue::PeekFirstAvailable (const Ptr< QosBlockedDestinations > blockedPackets = nullptr, ConstIterator pos = EMPTY) const
Return first available packet for transmission.
The packet is not removed from queue.
Parameters
blockedPackets the destination address & TID pairs that are waiting for a BlockAck response
pos the iterator pointing to the packet the search starts from
Returns
an iterator pointing to the peeked packet
Definition at line 370 of file wifi-mac-queue.cc.
References ns3::Queue< WifiMacQueueItem >::begin(), EMPTY, ns3::Queue< WifiMacQueueItem >::end(), m_expiredPacketsPresent, m_maxDelay, ns3::Simulator::Now(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by DequeueFirstAvailable().
PushFront()
bool ns3::WifiMacQueue::PushFront (Ptr< WifiMacQueueItem > item)
Enqueue the given Wifi MAC queue item at the front of the queue.
Parameters
item the Wifi MAC queue item to be enqueued at the front
Returns
true if success, false if the packet has been dropped
Definition at line 116 of file wifi-mac-queue.cc.
References ns3::Queue< WifiMacQueueItem >::begin(), Insert(), and NS_LOG_FUNCTION.
Remove() [1/3]
WifiMacQueue::ConstIterator ns3::WifiMacQueue::Remove (ConstIterator pos, bool removeExpired = false)
Remove the item at position pos in the queue and return an iterator pointing to the item following the removed one.
If removeExpired is true, all the items in the queue from the head to the given position are removed if their lifetime expired.
Parameters
pos the position of the item to be removed
removeExpired true to remove expired items
Returns
an iterator pointing to the item following the removed one
Definition at line 435 of file wifi-mac-queue.cc.
References ns3::Queue< WifiMacQueueItem >::begin(), ns3::Queue< WifiMacQueueItem >::DoRemove(), ns3::Queue< WifiMacQueueItem >::end(), m_expiredPacketsPresent, NS_LOG_DEBUG, NS_LOG_FUNCTION, and TtlExceeded().
Remove() [2/3]
bool ns3::WifiMacQueue::Remove (Ptr< const Packet > packet)
If exists, removes packet from queue and returns true.
Otherwise it takes no effects and return false. Deletion of the packet is performed in linear time (O(n)).
Parameters
packet the packet to be removed
Returns
true if the packet was removed, false otherwise
Definition at line 414 of file wifi-mac-queue.cc.
References ns3::Queue< WifiMacQueueItem >::begin(), ns3::Queue< WifiMacQueueItem >::DoRemove(), ns3::Queue< WifiMacQueueItem >::end(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and TtlExceeded().
Remove() [3/3]
Ptr< WifiMacQueueItem > ns3::WifiMacQueue::Remove (void) virtual
Remove the packet in the front of the queue.
Returns
the packet
Implements ns3::Queue< WifiMacQueueItem >.
Definition at line 398 of file wifi-mac-queue.cc.
References ns3::Queue< WifiMacQueueItem >::begin(), ns3::Queue< WifiMacQueueItem >::DoRemove(), ns3::Queue< WifiMacQueueItem >::end(), NS_LOG_DEBUG, NS_LOG_FUNCTION, and TtlExceeded().
SetMaxDelay()
void ns3::WifiMacQueue::SetMaxDelay (Time delay)
Set the maximum delay before the packet is discarded.
Parameters
delay the maximum delay
Definition at line 78 of file wifi-mac-queue.cc.
References m_maxDelay, and NS_LOG_FUNCTION.
Referenced by GetTypeId().
TtlExceeded()
bool ns3::WifiMacQueue::TtlExceeded (ConstIterator & it) private
Remove the item pointed to by the iterator it if it has been in the queue for too long.
If the item is removed, the iterator is updated to point to the item that followed the erased one.
Parameters
it an iterator pointing to the item
Returns
true if the item is removed, false otherwise
Definition at line 91 of file wifi-mac-queue.cc.
References ns3::Queue< WifiMacQueueItem >::DoRemove(), m_maxDelay, m_traceExpired, ns3::Simulator::Now(), NS_LOG_DEBUG, and NS_LOG_FUNCTION.
Referenced by Dequeue(), GetNBytes(), GetNPackets(), GetNPacketsByAddress(), GetNPacketsByTidAndAddress(), Insert(), IsEmpty(), and Remove().
Member Data Documentation
EMPTY
const WifiMacQueue::ConstIterator ns3::WifiMacQueue::EMPTY = std::list<Ptr<WifiMacQueueItem>> ().end () static
Invalid iterator to signal an empty queue.
Definition at line 302 of file wifi-mac-queue.h.
Referenced by ns3::BlockAckManager::GetBar(), PeekByAddress(), PeekByTid(), PeekByTidAndAddress(), PeekFirstAvailable(), and ns3::QosTxop::PeekNextFrame().
m_dropPolicy
DropPolicy ns3::WifiMacQueue::m_dropPolicy private
Drop behavior of queue.
Definition at line 317 of file wifi-mac-queue.h.
Referenced by GetTypeId(), and Insert().
m_expiredPacketsPresent
bool ns3::WifiMacQueue::m_expiredPacketsPresent mutable private
True if expired packets are in the queue.
Definition at line 318 of file wifi-mac-queue.h.
Referenced by Peek(), PeekByAddress(), PeekByTid(), PeekByTidAndAddress(), PeekFirstAvailable(), and Remove().
m_maxDelay
Time ns3::WifiMacQueue::m_maxDelay private
Time to live for packets in the queue.
Definition at line 316 of file wifi-mac-queue.h.
Referenced by GetMaxDelay(), Peek(), PeekByAddress(), PeekByTid(), PeekByTidAndAddress(), PeekFirstAvailable(), SetMaxDelay(), and TtlExceeded().
m_traceExpired
TracedCallback<Ptr<const WifiMacQueueItem> > ns3::WifiMacQueue::m_traceExpired private
Traced callback: fired when a packet is dropped due to lifetime expiration.
Definition at line 321 of file wifi-mac-queue.h.
Referenced by GetTypeId(), and TtlExceeded().
NS_LOG_TEMPLATE_DECLARE
ns3::WifiMacQueue::NS_LOG_TEMPLATE_DECLARE private
redefinition of the log component
Definition at line 323 of file wifi-mac-queue.h.
The documentation for this class was generated from the following files:
src/wifi/model/wifi-mac-queue.h
src/wifi/model/wifi-mac-queue.cc