ns-3: ns3::dot11s::HwmpTag Class Reference
ns3::dot11s::HwmpTag Class Reference
Mesh Device » IEEE 802.11s draft
Hwmp tag implements interaction between HWMP protocol and MeshWifiMac.
#include "hwmp-tag.h"
Public Member Functions
HwmpTag ()
~HwmpTag ()
void DecrementTtl ()
Decrement TTL.
virtual void Deserialize (TagBuffer i)
Mac48Address GetAddress ()
Get address from tag.
virtual TypeId GetInstanceTypeId () const
Get the most derived TypeId for this Object.
uint32_t GetMetric ()
Get the metric value.
uint32_t GetSeqno ()
Get the sequence number.
virtual uint32_t GetSerializedSize () const
uint8_t GetTtl ()
Get the TTL value.
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer i) const
void SetAddress (Mac48Address retransmitter)
Set address.
void SetMetric (uint32_t metric)
Set the metric value.
void SetSeqno (uint32_t seqno)
Set sequence number.
void SetTtl (uint8_t ttl)
Set the TTL value.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::Tag
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Mac48Address m_address
address
uint32_t m_metric
metric
uint32_t m_seqno
sequence no
uint8_t m_ttl
TTL.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Hwmp tag implements interaction between HWMP protocol and MeshWifiMac.
Hwmp tag keeps the following:
When packet is passed from Hwmp to 11sMAC:
retransmitter address,
TTL value,
When packet is passed to Hwmp from 11sMAC:
lasthop address,
TTL value,
metric value (metric of link is recalculated at each packet, but routing table stores metric obtained during path discovery procedure)
Definition at line 48 of file hwmp-tag.h.
Constructor & Destructor Documentation
HwmpTag()
ns3::dot11s::HwmpTag::HwmpTag ()
Definition at line 29 of file hwmp-tag.cc.
~HwmpTag()
ns3::dot11s::HwmpTag::~HwmpTag ()
Definition at line 34 of file hwmp-tag.cc.
Member Function Documentation
DecrementTtl()
void ns3::dot11s::HwmpTag::DecrementTtl ()
Decrement TTL.
Definition at line 155 of file hwmp-tag.cc.
References m_ttl.
Referenced by ns3::dot11s::HwmpProtocol::RequestRoute().
Deserialize()
void ns3::dot11s::HwmpTag::Deserialize (TagBuffer i) virtual
Parameters
i the buffer to read data from.
Read the content of the tag from the provided tag buffer. DO NOT attempt to read more bytes than you wrote with Tag::Serialize.
Implements ns3::Tag.
Definition at line 132 of file hwmp-tag.cc.
References first::address, ns3::Mac48Address::CopyFrom(), m_address, m_metric, m_seqno, m_ttl, ns3::TagBuffer::ReadU32(), and ns3::TagBuffer::ReadU8().
GetAddress()
Mac48Address ns3::dot11s::HwmpTag::GetAddress ()
Get address from tag.
Returns
the MAC address
Definition at line 45 of file hwmp-tag.cc.
References m_address.
Referenced by ns3::dot11s::HwmpProtocolMac::UpdateOutcomingFrame().
GetInstanceTypeId()
TypeId ns3::dot11s::HwmpTag::GetInstanceTypeId () const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 102 of file hwmp-tag.cc.
References GetTypeId().
GetMetric()
uint32_t ns3::dot11s::HwmpTag::GetMetric ()
Get the metric value.
Returns
the metric
Definition at line 69 of file hwmp-tag.cc.
References m_metric.
GetSeqno()
uint32_t ns3::dot11s::HwmpTag::GetSeqno ()
Get the sequence number.
Returns
the sequence number
Definition at line 81 of file hwmp-tag.cc.
References m_seqno.
Referenced by ns3::dot11s::HwmpProtocolMac::UpdateOutcomingFrame().
GetSerializedSize()
uint32_t ns3::dot11s::HwmpTag::GetSerializedSize () const virtual
Returns
the number of bytes required to serialize the data of the tag.
This method is typically invoked by Packet::AddPacketTag or Packet::AddByteTag just prior to calling Tag::Serialize.
Implements ns3::Tag.
Definition at line 108 of file hwmp-tag.cc.
GetTtl()
uint8_t ns3::dot11s::HwmpTag::GetTtl ()
Get the TTL value.
Returns
the TTL
Definition at line 57 of file hwmp-tag.cc.
References m_ttl.
Referenced by ns3::dot11s::HwmpProtocol::RequestRoute(), and ns3::dot11s::HwmpProtocolMac::UpdateOutcomingFrame().
GetTypeId()
TypeId ns3::dot11s::HwmpTag::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 91 of file hwmp-tag.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::dot11s::HwmpTag::Print (std::ostream & os) const virtual
Parameters
os the stream to print to
This method is typically invoked from the Packet::PrintByteTags or Packet::PrintPacketTags methods.
Implements ns3::Tag.
Definition at line 147 of file hwmp-tag.cc.
References m_address, m_metric, m_seqno, and m_ttl.
Serialize()
void ns3::dot11s::HwmpTag::Serialize (TagBuffer i) const virtual
Parameters
i the buffer to write data into.
Write the content of the tag in the provided tag buffer. DO NOT attempt to write more bytes than you requested with Tag::GetSerializedSize.
Implements ns3::Tag.
Definition at line 117 of file hwmp-tag.cc.
References first::address, ns3::Mac48Address::CopyTo(), m_address, m_metric, m_seqno, m_ttl, ns3::TagBuffer::WriteU32(), and ns3::TagBuffer::WriteU8().
SetAddress()
void ns3::dot11s::HwmpTag::SetAddress (Mac48Address retransmitter)
Set address.
Parameters
retransmitter the MAC address of the retransmitter
Definition at line 39 of file hwmp-tag.cc.
References m_address.
Referenced by ns3::dot11s::HwmpProtocol::ForwardUnicast(), ns3::dot11s::HwmpProtocol::ProactivePathResolved(), ns3::dot11s::HwmpProtocol::ReactivePathResolved(), and ns3::dot11s::HwmpProtocol::RequestRoute().
SetMetric()
void ns3::dot11s::HwmpTag::SetMetric (uint32_t metric)
Set the metric value.
Parameters
metric the metric
Definition at line 63 of file hwmp-tag.cc.
References m_metric.
SetSeqno()
void ns3::dot11s::HwmpTag::SetSeqno (uint32_t seqno)
Set sequence number.
Parameters
seqno the sequence number
Definition at line 75 of file hwmp-tag.cc.
References m_seqno.
Referenced by ns3::dot11s::HwmpProtocolMac::ReceiveData(), and ns3::dot11s::HwmpProtocol::RequestRoute().
SetTtl()
void ns3::dot11s::HwmpTag::SetTtl (uint8_t ttl)
Set the TTL value.
Parameters
ttl
Definition at line 51 of file hwmp-tag.cc.
References m_ttl.
Referenced by ns3::dot11s::HwmpProtocol::ForwardUnicast(), ns3::dot11s::HwmpProtocolMac::ReceiveData(), and ns3::dot11s::HwmpProtocol::RequestRoute().
Member Data Documentation
m_address
Mac48Address ns3::dot11s::HwmpTag::m_address private
address
Definition at line 107 of file hwmp-tag.h.
Referenced by Deserialize(), GetAddress(), Print(), Serialize(), and SetAddress().
m_metric
uint32_t ns3::dot11s::HwmpTag::m_metric private
metric
Definition at line 109 of file hwmp-tag.h.
Referenced by Deserialize(), GetMetric(), Print(), Serialize(), and SetMetric().
m_seqno
uint32_t ns3::dot11s::HwmpTag::m_seqno private
sequence no
Definition at line 110 of file hwmp-tag.h.
Referenced by Deserialize(), GetSeqno(), Print(), Serialize(), and SetSeqno().
m_ttl
uint8_t ns3::dot11s::HwmpTag::m_ttl private
TTL.
Definition at line 108 of file hwmp-tag.h.
Referenced by DecrementTtl(), Deserialize(), GetTtl(), Print(), Serialize(), and SetTtl().
The documentation for this class was generated from the following files:
src/mesh/model/dot11s/hwmp-tag.h
src/mesh/model/dot11s/hwmp-tag.cc