ns-3: StackHelper Class Reference
StackHelper Class Reference
Helper to set or get some IPv6 information about nodes.
Public Member Functions
void AddAddress (Ptr< Node > &n, uint32_t interface, Ipv6Address address)
Add an address to a IPv6 node.
void PrintRoutingTable (Ptr< Node > &n)
Print the routing table.
Detailed Description
Helper to set or get some IPv6 information about nodes.
Definition at line 48 of file simple-routing-ping6.cc.
Member Function Documentation
AddAddress()
void StackHelper::AddAddress (Ptr< Node > & n, uint32_t interface, Ipv6Address address) inline
Add an address to a IPv6 node.
Parameters
n node
interface interface index
address IPv6 address to add
Definition at line 58 of file simple-routing-ping6.cc.
References ns3::Ipv6::AddAddress(), first::address, and sample-rng-plot::n.
PrintRoutingTable()
void StackHelper::PrintRoutingTable (Ptr< Node > & n) inline
Print the routing table.
Parameters
n the node
Definition at line 68 of file simple-routing-ping6.cc.
References ns3::Ipv6RoutingTableEntry::GetDest(), ns3::Ipv6RoutingTableEntry::GetGateway(), ns3::Ipv6RoutingTableEntry::GetInterface(), ns3::Ipv6StaticRouting::GetNRoutes(), ns3::Ipv6RoutingTableEntry::GetPrefixToUse(), ns3::Ipv6StaticRouting::GetRoute(), ns3::Ipv6StaticRoutingHelper::GetStaticRouting(), and sample-rng-plot::n.
The documentation for this class was generated from the following file:
examples/routing/simple-routing-ping6.cc