ns-3: ns3::Ipv4StaticRouting Class Reference
ns3::Ipv4StaticRouting Class Reference
Internet » IPv4 Routing Protocols.
Static routing protocol for IP version 4 stacks.
#include "ipv4-static-routing.h"
Public Member Functions
Ipv4StaticRouting ()
virtual ~Ipv4StaticRouting ()
void AddHostRouteTo (Ipv4Address dest, Ipv4Address nextHop, uint32_t interface, uint32_t metric=0)
Add a host route to the static routing table.
void AddHostRouteTo (Ipv4Address dest, uint32_t interface, uint32_t metric=0)
Add a host route to the static routing table.
void AddMulticastRoute (Ipv4Address origin, Ipv4Address group, uint32_t inputInterface, std::vector< uint32_t > outputInterfaces)
Add a multicast route to the static routing table.
void AddNetworkRouteTo (Ipv4Address network, Ipv4Mask networkMask, Ipv4Address nextHop, uint32_t interface, uint32_t metric=0)
Add a network route to the static routing table.
void AddNetworkRouteTo (Ipv4Address network, Ipv4Mask networkMask, uint32_t interface, uint32_t metric=0)
Add a network route to the static routing table.
Ipv4RoutingTableEntry GetDefaultRoute (void)
Get the default route with lowest metric from the static routing table.
uint32_t GetMetric (uint32_t index) const
Get a metric for route from the static unicast routing table.
Ipv4MulticastRoutingTableEntry GetMulticastRoute (uint32_t i) const
Get a route from the static multicast routing table.
uint32_t GetNMulticastRoutes (void) const
Get the number of individual multicast routes that have been added to the routing table.
uint32_t GetNRoutes (void) const
Get the number of individual unicast routes that have been added to the routing table.
Ipv4RoutingTableEntry GetRoute (uint32_t i) const
Get a route from the static unicast routing table.
virtual void NotifyAddAddress (uint32_t interface, Ipv4InterfaceAddress address)
virtual void NotifyInterfaceDown (uint32_t interface)
virtual void NotifyInterfaceUp (uint32_t interface)
virtual void NotifyRemoveAddress (uint32_t interface, Ipv4InterfaceAddress address)
virtual void PrintRoutingTable (Ptr< OutputStreamWrapper > stream, Time::Unit unit=Time::S) const
Print the Routing Table entries.
bool RemoveMulticastRoute (Ipv4Address origin, Ipv4Address group, uint32_t inputInterface)
Remove a route from the static multicast routing table.
void RemoveMulticastRoute (uint32_t index)
Remove a route from the static multicast routing table.
void RemoveRoute (uint32_t i)
Remove a route from the static unicast routing table.
virtual bool RouteInput (Ptr< const Packet > p, const Ipv4Header &header, Ptr< const NetDevice > idev, UnicastForwardCallback ucb, MulticastForwardCallback mcb, LocalDeliverCallback lcb, ErrorCallback ecb)
Route an input packet (to be forwarded or locally delivered)
virtual Ptr< Ipv4Route > RouteOutput (Ptr< Packet > p, const Ipv4Header &header, Ptr< NetDevice > oif, Socket::SocketErrno &sockerr)
Query routing cache for an existing route, for an outbound packet.
void SetDefaultMulticastRoute (uint32_t outputInterface)
Add a default multicast route to the static routing table.
void SetDefaultRoute (Ipv4Address nextHop, uint32_t interface, uint32_t metric=0)
Add a default route to the static routing table.
virtual void SetIpv4 (Ptr< Ipv4 > ipv4)
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
The interface Id associated with this class.
Static Public Member Functions inherited from ns3::Ipv4RoutingProtocol
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoDispose (void)
Destructor implementation.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Private Types
typedef std::list< Ipv4MulticastRoutingTableEntry * > MulticastRoutes
Container for the multicast routes.
typedef std::list< Ipv4MulticastRoutingTableEntry * >::const_iterator MulticastRoutesCI
Const Iterator for container for the multicast routes.
typedef std::list< Ipv4MulticastRoutingTableEntry * >::iterator MulticastRoutesI
Iterator for container for the multicast routes.
typedef std::list< std::pair< Ipv4RoutingTableEntry *, uint32_t > > NetworkRoutes
Container for the network routes.
typedef std::list< std::pair< Ipv4RoutingTableEntry *, uint32_t > >::const_iterator NetworkRoutesCI
Const Iterator for container for the network routes.
typedef std::list< std::pair< Ipv4RoutingTableEntry *, uint32_t > >::iterator NetworkRoutesI
Iterator for container for the network routes.
Private Member Functions
Ptr< Ipv4Route > LookupStatic (Ipv4Address dest, Ptr< NetDevice > oif=0)
Lookup in the forwarding table for destination.
Ptr< Ipv4MulticastRoute > LookupStatic (Ipv4Address origin, Ipv4Address group, uint32_t interface)
Lookup in the multicast forwarding table for destination.
Private Attributes
Ptr< Ipv4 > m_ipv4
Ipv4 reference.
MulticastRoutes m_multicastRoutes
the forwarding table for multicast.
NetworkRoutes m_networkRoutes
the forwarding table for network.
Additional Inherited Members
Public Types inherited from ns3::Ipv4RoutingProtocol
typedef Callback< void, Ptr< const Packet >, const Ipv4Header &, Socket::SocketErrno > ErrorCallback
Callback for routing errors (e.g., no route found)
typedef Callback< void, Ptr< const Packet >, const Ipv4Header &, uint32_t > LocalDeliverCallback
Callback for packets to be locally delivered.
typedef Callback< void, Ptr< Ipv4MulticastRoute >, Ptr< const Packet >, const Ipv4Header & > MulticastForwardCallback
Callback for multicast packets to be forwarded.
typedef Callback< void, Ptr< Ipv4Route >, Ptr< const Packet >, const Ipv4Header & > UnicastForwardCallback
Callback for unicast packets to be forwarded.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Static routing protocol for IP version 4 stacks.
This class provides a basic set of methods for inserting static unicast and multicast routes into the Ipv4 routing system. This particular protocol is designed to be inserted into an Ipv4ListRouting protocol but can be used also as a standalone protocol.
The Ipv4StaticRouting class inherits from the abstract base class Ipv4RoutingProtocol that defines the interface methods that a routing protocol must support.
See also
Ipv4RoutingProtocol
Ipv4ListRouting
Ipv4ListRouting::AddRoutingProtocol
Definition at line 65 of file ipv4-static-routing.h.
Member Typedef Documentation
MulticastRoutes
typedef std::list<Ipv4MulticastRoutingTableEntry *> ns3::Ipv4StaticRouting::MulticastRoutes private
Container for the multicast routes.
Definition at line 390 of file ipv4-static-routing.h.
MulticastRoutesCI
typedef std::list<Ipv4MulticastRoutingTableEntry *>::const_iterator ns3::Ipv4StaticRouting::MulticastRoutesCI private
Const Iterator for container for the multicast routes.
Definition at line 393 of file ipv4-static-routing.h.
MulticastRoutesI
typedef std::list<Ipv4MulticastRoutingTableEntry *>::iterator ns3::Ipv4StaticRouting::MulticastRoutesI private
Iterator for container for the multicast routes.
Definition at line 396 of file ipv4-static-routing.h.
NetworkRoutes
typedef std::list<std::pair <Ipv4RoutingTableEntry *, uint32_t> > ns3::Ipv4StaticRouting::NetworkRoutes private
Container for the network routes.
Definition at line 381 of file ipv4-static-routing.h.
NetworkRoutesCI
typedef std::list<std::pair <Ipv4RoutingTableEntry *, uint32_t> >::const_iterator ns3::Ipv4StaticRouting::NetworkRoutesCI private
Const Iterator for container for the network routes.
Definition at line 384 of file ipv4-static-routing.h.
NetworkRoutesI
typedef std::list<std::pair <Ipv4RoutingTableEntry *, uint32_t> >::iterator ns3::Ipv4StaticRouting::NetworkRoutesI private
Iterator for container for the network routes.
Definition at line 387 of file ipv4-static-routing.h.
Constructor & Destructor Documentation
Ipv4StaticRouting()
ns3::Ipv4StaticRouting::Ipv4StaticRouting ()
Definition at line 56 of file ipv4-static-routing.cc.
References NS_LOG_FUNCTION.
~Ipv4StaticRouting()
ns3::Ipv4StaticRouting::~Ipv4StaticRouting () virtual
Definition at line 563 of file ipv4-static-routing.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
AddHostRouteTo() [1/2]
void ns3::Ipv4StaticRouting::AddHostRouteTo (Ipv4Address dest, Ipv4Address nextHop, uint32_t interface, uint32_t metric = 0)
Add a host route to the static routing table.
Parameters
dest The Ipv4Address destination for this route.
nextHop The Ipv4Address of the next hop in the route.
interface The network interface index used to send packets to the destination.
metric Metric of route in case of multiple routes to same destination
See also
Ipv4Address
Definition at line 93 of file ipv4-static-routing.cc.
References AddNetworkRouteTo(), ns3::Ipv4Mask::GetOnes(), and NS_LOG_FUNCTION.
Referenced by Ipv4StaticRoutingSlash32TestCase::DoRun().
AddHostRouteTo() [2/2]
void ns3::Ipv4StaticRouting::AddHostRouteTo (Ipv4Address dest, uint32_t interface, uint32_t metric = 0)
Add a host route to the static routing table.
Parameters
dest The Ipv4Address destination for this route.
interface The network interface index used to send packets to the destination.
metric Metric of route in case of multiple routes to same destination
See also
Ipv4Address
Definition at line 103 of file ipv4-static-routing.cc.
References AddNetworkRouteTo(), ns3::Ipv4Mask::GetOnes(), and NS_LOG_FUNCTION.
AddMulticastRoute()
void ns3::Ipv4StaticRouting::AddMulticastRoute (Ipv4Address origin, Ipv4Address group, uint32_t inputInterface, std::vector< uint32_t > outputInterfaces)
Add a multicast route to the static routing table.
A multicast route must specify an origin IP address, a multicast group and an input network interface index as conditions and provide a vector of output network interface indices over which packets matching the conditions are sent.
Typically there are two main types of multicast routes: routes of the first kind are used during forwarding. All of the conditions must be explicitly provided. The second kind of routes are used to get packets off of a local node. The difference is in the input interface. Routes for forwarding will always have an explicit input interface specified. Routes off of a node will always set the input interface to a wildcard specified by the index Ipv4RoutingProtocol::INTERFACE_ANY.
For routes off of a local node wildcards may be used in the origin and multicast group addresses. The wildcard used for Ipv4Adresses is that address returned by Ipv4Address::GetAny () – typically "0.0.0.0". Usage of a wildcard allows one to specify default behavior to varying degrees.
For example, making the origin address a wildcard, but leaving the multicast group specific allows one (in the case of a node with multiple interfaces) to create different routes using different output interfaces for each multicast group.
If the origin and multicast addresses are made wildcards, you have created essentially a default multicast address that can forward to multiple interfaces. Compare this to the actual default multicast address that is limited to specifying a single output interface for compatibility with existing functionality in other systems.
Parameters
origin The Ipv4Address of the origin of packets for this route. May be Ipv4Address:GetAny for open groups.
group The Ipv4Address of the multicast group or this route.
inputInterface The input network interface index over which to expect packets destined for this route. May be Ipv4RoutingProtocol::INTERFACE_ANY for packets of local origin.
outputInterfaces A vector of network interface indices used to specify how to send packets to the destination(s).
See also
Ipv4Address
Definition at line 121 of file ipv4-static-routing.cc.
References ns3::Ipv4MulticastRoutingTableEntry::CreateMulticastRoute(), m_multicastRoutes, and NS_LOG_FUNCTION.
AddNetworkRouteTo() [1/2]
void ns3::Ipv4StaticRouting::AddNetworkRouteTo (Ipv4Address network, Ipv4Mask networkMask, Ipv4Address nextHop, uint32_t interface, uint32_t metric = 0)
Add a network route to the static routing table.
Parameters
network The Ipv4Address network for this route.
networkMask The Ipv4Mask to extract the network.
nextHop The next hop in the route to the destination network.
interface The network interface index used to send packets to the destination.
metric Metric of route in case of multiple routes to same destination
See also
Ipv4Address
Definition at line 63 of file ipv4-static-routing.cc.
References ns3::Ipv4RoutingTableEntry::CreateNetworkRouteTo(), m_networkRoutes, and NS_LOG_FUNCTION.
Referenced by AddHostRouteTo(), LteCellSelectionTestCase::DoRun(), LteRadioLinkFailureTestCase::DoRun(), LteUeMeasurementsHandoverTestCase::DoRun(), LteHandoverTargetTestCase::DoRun(), EpcS1uDlTestCase::DoRun(), EpcS1uUlTestCase::DoRun(), LenaCqaFfMacSchedulerTestCase1::DoRun(), LenaCqaFfMacSchedulerTestCase2::DoRun(), LenaFdTbfqFfMacSchedulerTestCase1::DoRun(), LenaFdTbfqFfMacSchedulerTestCase2::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LenaPssFfMacSchedulerTestCase1::DoRun(), LenaPssFfMacSchedulerTestCase2::DoRun(), LenaTdTbfqFfMacSchedulerTestCase1::DoRun(), LenaTdTbfqFfMacSchedulerTestCase2::DoRun(), LteEpcE2eDataTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), LteX2HandoverTestCase::DoRun(), NotifyAddAddress(), NotifyInterfaceUp(), and SetDefaultRoute().
AddNetworkRouteTo() [2/2]
void ns3::Ipv4StaticRouting::AddNetworkRouteTo (Ipv4Address network, Ipv4Mask networkMask, uint32_t interface, uint32_t metric = 0)
Add a network route to the static routing table.
Parameters
network The Ipv4Address network for this route.
networkMask The Ipv4Mask to extract the network.
interface The network interface index used to send packets to the destination.
metric Metric of route in case of multiple routes to same destination
See also
Ipv4Address
Definition at line 79 of file ipv4-static-routing.cc.
References ns3::Ipv4RoutingTableEntry::CreateNetworkRouteTo(), m_networkRoutes, and NS_LOG_FUNCTION.
DoDispose()
void ns3::Ipv4StaticRouting::DoDispose (void) protected virtual
Destructor implementation.
This method is called by Dispose() or by the Object's destructor, whichever comes first.
Subclasses are expected to implement their real destruction code in an overridden version of this method and chain up to their parent's implementation once they are done. i.e, for simplicity, the destructor of every subclass should be empty and its content should be moved to the associated DoDispose() method.
It is safe to call GetObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 569 of file ipv4-static-routing.cc.
References ns3::Object::DoDispose(), m_ipv4, m_multicastRoutes, m_networkRoutes, and NS_LOG_FUNCTION.
GetDefaultRoute()
Ipv4RoutingTableEntry ns3::Ipv4StaticRouting::GetDefaultRoute (void)
Get the default route with lowest metric from the static routing table.
Returns
If the default route is set, a pointer to that Ipv4RoutingTableEntry is returned, otherwise an empty routing table entry is returned. If multiple default routes exist, the one with lowest metric is returned.
See also
Ipv4RoutingTableEntry
Definition at line 364 of file ipv4-static-routing.cc.
References ns3::Ipv4Mask::GetPrefixLength(), m_networkRoutes, and NS_LOG_FUNCTION.
GetMetric()
uint32_t ns3::Ipv4StaticRouting::GetMetric (uint32_t index) const
Get a metric for route from the static unicast routing table.
Parameters
index The index (into the routing table) of the route to retrieve.
Returns
If route is set, the metric is returned. If not, an infinity metric (0xffffffff) is returned
Definition at line 421 of file ipv4-static-routing.cc.
References m_networkRoutes, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by PrintRoutingTable().
GetMulticastRoute()
Ipv4MulticastRoutingTableEntry ns3::Ipv4StaticRouting::GetMulticastRoute (uint32_t i) const
Get a route from the static multicast routing table.
Externally, the multicast static routing table appears simply as a table with n entries.
Parameters
i The index (into the routing table) of the multicast route to retrieve.
Returns
If route i is set, a pointer to that Ipv4MulticastRoutingTableEntry is returned, otherwise a zero pointer is returned.
See also
Ipv4MulticastRoutingTableEntry
Ipv4StaticRouting::RemoveRoute
Definition at line 157 of file ipv4-static-routing.cc.
References m_multicastRoutes, NS_ASSERT_MSG(), and NS_LOG_FUNCTION.
GetNMulticastRoutes()
uint32_t ns3::Ipv4StaticRouting::GetNMulticastRoutes (void) const
Get the number of individual multicast routes that have been added to the routing table.
Warning
The default multicast route counts as one of the routes.
Returns
number of entries
Definition at line 150 of file ipv4-static-routing.cc.
References m_multicastRoutes, and NS_LOG_FUNCTION.
GetNRoutes()
uint32_t ns3::Ipv4StaticRouting::GetNRoutes (void) const
Get the number of individual unicast routes that have been added to the routing table.
Warning
The default route counts as one of the routes.
Returns
number of entries
Definition at line 357 of file ipv4-static-routing.cc.
References m_networkRoutes, and NS_LOG_FUNCTION.
Referenced by PrintRoutingTable().
GetRoute()
Ipv4RoutingTableEntry ns3::Ipv4StaticRouting::GetRoute (uint32_t i) const
Get a route from the static unicast routing table.
Externally, the unicast static routing table appears simply as a table with n entries.
Parameters
i The index (into the routing table) of the route to retrieve.
Returns
If route is set, a pointer to that Ipv4RoutingTableEntry is returned, otherwise a zero pointer is returned.
See also
Ipv4RoutingTableEntry
Ipv4StaticRouting::RemoveRoute
Definition at line 401 of file ipv4-static-routing.cc.
References m_networkRoutes, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by PrintRoutingTable().
GetTypeId()
TypeId ns3::Ipv4StaticRouting::GetTypeId (void) static
The interface Id associated with this class.
Returns
type identifier
Definition at line 46 of file ipv4-static-routing.cc.
References ns3::TypeId::SetParent().
LookupStatic() [1/2]
Ptr< Ipv4Route > ns3::Ipv4StaticRouting::LookupStatic (Ipv4Address dest, Ptr< NetDevice > oif = 0) private
Lookup in the forwarding table for destination.
Parameters
dest destination address
oif output interface if any (put 0 otherwise)
Returns
Ipv4Route to route the packet to reach dest address
Definition at line 223 of file ipv4-static-routing.cc.
References ns3::Ipv4RoutingTableEntry::GetDest(), ns3::Ipv4Route::GetGateway(), ns3::Ipv4RoutingTableEntry::GetGateway(), ns3::Ipv4RoutingTableEntry::GetInterface(), ns3::Ipv4Mask::GetPrefixLength(), ns3::Ipv4Address::GetZero(), ns3::Ipv4Address::IsLocalMulticast(), ns3::Ipv4Mask::IsMatch(), m_ipv4, m_networkRoutes, NS_ASSERT_MSG(), NS_LOG_FUNCTION, NS_LOG_LOGIC(), ns3::Ipv4Route::SetDestination(), ns3::Ipv4Route::SetGateway(), ns3::Ipv4Route::SetOutputDevice(), and ns3::Ipv4Route::SetSource().
Referenced by RouteInput(), and RouteOutput().
LookupStatic() [2/2]
Ptr< Ipv4MulticastRoute > ns3::Ipv4StaticRouting::LookupStatic (Ipv4Address origin, Ipv4Address group, uint32_t interface) private
Lookup in the multicast forwarding table for destination.
Parameters
origin source address
group group multicast address
interface interface index
Returns
Ipv4MulticastRoute to route the packet to reach dest address
Definition at line 305 of file ipv4-static-routing.cc.
References ns3::Ipv4MulticastRoutingTableEntry::GetGroup(), ns3::Ipv4MulticastRoutingTableEntry::GetInputInterface(), ns3::Ipv4MulticastRoutingTableEntry::GetNOutputInterfaces(), ns3::Ipv4MulticastRoutingTableEntry::GetOrigin(), ns3::Ipv4MulticastRoutingTableEntry::GetOutputInterface(), ns3::Ipv4::IF_ANY, m_multicastRoutes, ns3::Ipv4MulticastRoute::MAX_TTL, NS_LOG_FUNCTION, and NS_LOG_LOGIC().
NotifyAddAddress()
void ns3::Ipv4StaticRouting::NotifyAddAddress (uint32_t interface, Ipv4InterfaceAddress address) virtual
Parameters
interface the index of the interface we are being notified about
address a new address being added to an interface
Protocols are expected to implement this method to be notified whenever a new address is added to an interface. Typically used to add a 'network route' on an interface. Can be invoked on an up or down interface.
Implements ns3::Ipv4RoutingProtocol.
Definition at line 627 of file ipv4-static-routing.cc.
References AddNetworkRouteTo(), first::address, m_ipv4, and NS_LOG_FUNCTION.
NotifyInterfaceDown()
void ns3::Ipv4StaticRouting::NotifyInterfaceDown (uint32_t interface) virtual
Parameters
interface the index of the interface we are being notified about
Protocols are expected to implement this method to be notified of the state change of an interface in a node.
Implements ns3::Ipv4RoutingProtocol.
Definition at line 608 of file ipv4-static-routing.cc.
References m_networkRoutes, and NS_LOG_FUNCTION.
Referenced by SetIpv4().
NotifyInterfaceUp()
void ns3::Ipv4StaticRouting::NotifyInterfaceUp (uint32_t interface) virtual
Parameters
interface the index of the interface we are being notified about
Protocols are expected to implement this method to be notified of the state change of an interface in a node.
Implements ns3::Ipv4RoutingProtocol.
Definition at line 589 of file ipv4-static-routing.cc.
References AddNetworkRouteTo(), ns3::Ipv4Mask::GetOnes(), m_ipv4, and NS_LOG_FUNCTION.
Referenced by SetIpv4().
NotifyRemoveAddress()
void ns3::Ipv4StaticRouting::NotifyRemoveAddress (uint32_t interface, Ipv4InterfaceAddress address) virtual
Parameters
interface the index of the interface we are being notified about
address a new address being added to an interface
Protocols are expected to implement this method to be notified whenever a new address is removed from an interface. Typically used to remove the 'network route' of an interface. Can be invoked on an up or down interface.
Implements ns3::Ipv4RoutingProtocol.
Definition at line 645 of file ipv4-static-routing.cc.
References first::address, m_ipv4, m_networkRoutes, and NS_LOG_FUNCTION.
PrintRoutingTable()
void ns3::Ipv4StaticRouting::PrintRoutingTable (Ptr< OutputStreamWrapper > stream, Time::Unit unit = Time::S) const virtual
Print the Routing Table entries.
Parameters
stream The ostream the Routing table is printed to
unit The time unit to be used in the report
Implements ns3::Ipv4RoutingProtocol.
Definition at line 693 of file ipv4-static-routing.cc.
References ns3::Time::As(), ns3::Names::FindName(), ns3::Ipv4RoutingTableEntry::GetDest(), ns3::Ipv4RoutingTableEntry::GetDestNetworkMask(), ns3::Ipv4RoutingTableEntry::GetGateway(), ns3::Ipv4RoutingTableEntry::GetInterface(), GetMetric(), GetNRoutes(), GetRoute(), ns3::OutputStreamWrapper::GetStream(), ns3::Ipv4RoutingTableEntry::IsGateway(), ns3::Ipv4RoutingTableEntry::IsHost(), m_ipv4, ns3::Now(), and NS_LOG_FUNCTION.
RemoveMulticastRoute() [1/2]
bool ns3::Ipv4StaticRouting::RemoveMulticastRoute (Ipv4Address origin, Ipv4Address group, uint32_t inputInterface)
Remove a route from the static multicast routing table.
Externally, the multicast static routing table appears simply as a table with n entries. This method causes the multicast routing table to be searched for the first route that matches the parameters and removes it.
Wildcards may be provided to this function, but the wildcards are used to exactly match wildcards in the routes (see AddMulticastRoute). That is, calling RemoveMulticastRoute with the origin set to "0.0.0.0" will not remove routes with any address in the origin, but will only remove routes with "0.0.0.0" set as the the origin.
Parameters
origin The IP address specified as the origin of packets for the route.
group The IP address specified as the multicast group address of the route.
inputInterface The network interface index specified as the expected input interface for the route.
Returns
true if a route was found and removed, false otherwise.
See also
Ipv4MulticastRoutingTableEntry
Ipv4StaticRouting::AddMulticastRoute
Definition at line 181 of file ipv4-static-routing.cc.
References ns3::Ipv4MulticastRoutingTableEntry::GetGroup(), ns3::Ipv4MulticastRoutingTableEntry::GetInputInterface(), ns3::Ipv4MulticastRoutingTableEntry::GetOrigin(), m_multicastRoutes, and NS_LOG_FUNCTION.
RemoveMulticastRoute() [2/2]
void ns3::Ipv4StaticRouting::RemoveMulticastRoute (uint32_t index)
Remove a route from the static multicast routing table.
Externally, the multicast static routing table appears simply as a table with n entries.
Parameters
index The index (into the multicast routing table) of the route to remove.
See also
Ipv4RoutingTableEntry
Ipv4StaticRouting::GetRoute
Ipv4StaticRouting::AddRoute
Definition at line 204 of file ipv4-static-routing.cc.
References m_multicastRoutes, and NS_LOG_FUNCTION.
RemoveRoute()
void ns3::Ipv4StaticRouting::RemoveRoute (uint32_t i)
Remove a route from the static unicast routing table.
Externally, the unicast static routing table appears simply as a table with n entries.
Parameters
i The index (into the routing table) of the route to remove.
See also
Ipv4RoutingTableEntry
Ipv4StaticRouting::GetRoute
Ipv4StaticRouting::AddRoute
Definition at line 440 of file ipv4-static-routing.cc.
References m_networkRoutes, NS_ASSERT, and NS_LOG_FUNCTION.
RouteInput()
bool ns3::Ipv4StaticRouting::RouteInput (Ptr< const Packet > p, const Ipv4Header & header, Ptr< const NetDevice > idev, UnicastForwardCallback ucb, MulticastForwardCallback mcb, LocalDeliverCallback lcb, ErrorCallback ecb) virtual
Route an input packet (to be forwarded or locally delivered)
This lookup is used in the forwarding process. The packet is handed over to the Ipv4RoutingProtocol, and will get forwarded onward by one of the callbacks. The Linux equivalent is ip_route_input(). There are four valid outcomes, and a matching callbacks to handle each.
Parameters
p received packet
header input parameter used to form a search key for a route
idev Pointer to ingress network device
ucb Callback for the case in which the packet is to be forwarded as unicast
mcb Callback for the case in which the packet is to be forwarded as multicast
lcb Callback for the case in which the packet is to be locally delivered
ecb Callback to call if there is an error in forwarding
Returns
true if the Ipv4RoutingProtocol takes responsibility for forwarding or delivering the packet, false otherwise
Implements ns3::Ipv4RoutingProtocol.
Definition at line 490 of file ipv4-static-routing.cc.
References ns3::Socket::ERROR_NOROUTETOHOST, ns3::Ipv4Header::GetDestination(), ns3::Ipv4Header::GetSource(), ns3::Ipv4Address::IsMulticast(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), LookupStatic(), m_ipv4, NS_ASSERT, NS_LOG_FUNCTION, and NS_LOG_LOGIC().
RouteOutput()
Ptr< Ipv4Route > ns3::Ipv4StaticRouting::RouteOutput (Ptr< Packet > p, const Ipv4Header & header, Ptr< NetDevice > oif, Socket::SocketErrno & sockerr) virtual
Query routing cache for an existing route, for an outbound packet.
This lookup is used by transport protocols. It does not cause any packet to be forwarded, and is synchronous. Can be used for multicast or unicast. The Linux equivalent is ip_route_output()
The header input parameter may have an uninitialized value for the source address, but the destination address should always be properly set by the caller.
Parameters
p packet to be routed. Note that this method may modify the packet. Callers may also pass in a null pointer.
header input parameter (used to form key to search for the route)
oif Output interface Netdevice. May be zero, or may be bound via socket options to a particular output interface.
sockerr Output parameter; socket errno
Returns
a code that indicates what happened in the lookup
Implements ns3::Ipv4RoutingProtocol.
Definition at line 460 of file ipv4-static-routing.cc.
References ns3::Socket::ERROR_NOROUTETOHOST, ns3::Socket::ERROR_NOTERROR, ns3::Ipv4Header::GetDestination(), ns3::Ipv4Address::IsMulticast(), LookupStatic(), NS_LOG_FUNCTION, and NS_LOG_LOGIC().
SetDefaultMulticastRoute()
void ns3::Ipv4StaticRouting::SetDefaultMulticastRoute (uint32_t outputInterface)
Add a default multicast route to the static routing table.
This is the multicast equivalent of the unicast version SetDefaultRoute. We tell the routing system what to do in the case where a specific route to a destination multicast group is not found. The system forwards packets out the specified interface in the hope that "something out there" knows better how to route the packet. This method is only used in initially sending packets off of a host. The default multicast route is not consulted during forwarding – exact routes must be specified using AddMulticastRoute for that case.
Since we're basically sending packets to some entity we think may know better what to do, we don't pay attention to "subtleties" like origin address, nor do we worry about forwarding out multiple interfaces. If the default multicast route is set, it is returned as the selected route from LookupStatic irrespective of origin or multicast group if another specific route is not found.
Parameters
outputInterface The network interface index used to specify where to send packets in the case of unknown routes.
See also
Ipv4Address
Definition at line 137 of file ipv4-static-routing.cc.
References ns3::Ipv4RoutingTableEntry::CreateNetworkRouteTo(), m_networkRoutes, and NS_LOG_FUNCTION.
SetDefaultRoute()
void ns3::Ipv4StaticRouting::SetDefaultRoute (Ipv4Address nextHop, uint32_t interface, uint32_t metric = 0)
Add a default route to the static routing table.
This method tells the routing system what to do in the case where a specific route to a destination is not found. The system forwards packets to the specified node in the hope that it knows better how to route the packet.
If the default route is set, it is returned as the selected route from LookupStatic irrespective of destination address if no specific route is found.
Parameters
nextHop The Ipv4Address to send packets to in the hope that they will be forwarded correctly.
interface The network interface index used to send packets.
metric Metric of route in case of multiple routes to same destination
See also
Ipv4Address
Ipv4StaticRouting::Lookup
Definition at line 112 of file ipv4-static-routing.cc.
References AddNetworkRouteTo(), ns3::Ipv4Mask::GetZero(), and NS_LOG_FUNCTION.
Referenced by LteCellSelectionTestCase::DoRun(), LteRadioLinkFailureTestCase::DoRun(), LteUeMeasurementsHandoverTestCase::DoRun(), LteHandoverTargetTestCase::DoRun(), Ipv4ForwardingTest::DoRun(), Ipv4RipTest::DoRun(), Ipv4RipCountToInfinityTest::DoRun(), EpcS1uUlTestCase::DoRun(), LenaCqaFfMacSchedulerTestCase1::DoRun(), LenaCqaFfMacSchedulerTestCase2::DoRun(), LenaFdTbfqFfMacSchedulerTestCase1::DoRun(), LenaFdTbfqFfMacSchedulerTestCase2::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LenaPssFfMacSchedulerTestCase1::DoRun(), LenaPssFfMacSchedulerTestCase2::DoRun(), LenaTdTbfqFfMacSchedulerTestCase1::DoRun(), LenaTdTbfqFfMacSchedulerTestCase2::DoRun(), LteEpcE2eDataTestCase::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), and LteX2HandoverTestCase::DoRun().
SetIpv4()
void ns3::Ipv4StaticRouting::SetIpv4 (Ptr< Ipv4 > ipv4) virtual
Parameters
ipv4 the ipv4 object this routing protocol is being associated with
Typically, invoked directly or indirectly from ns3::Ipv4::SetRoutingProtocol
Implements ns3::Ipv4RoutingProtocol.
Definition at line 674 of file ipv4-static-routing.cc.
References m_ipv4, NotifyInterfaceDown(), NotifyInterfaceUp(), NS_ASSERT, and NS_LOG_FUNCTION.
Member Data Documentation
m_ipv4
Ptr<Ipv4> ns3::Ipv4StaticRouting::m_ipv4 private
Ipv4 reference.
Definition at line 429 of file ipv4-static-routing.h.
Referenced by DoDispose(), LookupStatic(), NotifyAddAddress(), NotifyInterfaceUp(), NotifyRemoveAddress(), PrintRoutingTable(), RouteInput(), and SetIpv4().
m_multicastRoutes
MulticastRoutes ns3::Ipv4StaticRouting::m_multicastRoutes private
the forwarding table for multicast.
Definition at line 424 of file ipv4-static-routing.h.
Referenced by AddMulticastRoute(), DoDispose(), GetMulticastRoute(), GetNMulticastRoutes(), LookupStatic(), and RemoveMulticastRoute().
m_networkRoutes
NetworkRoutes ns3::Ipv4StaticRouting::m_networkRoutes private
the forwarding table for network.
Definition at line 419 of file ipv4-static-routing.h.
Referenced by AddNetworkRouteTo(), DoDispose(), GetDefaultRoute(), GetMetric(), GetNRoutes(), GetRoute(), LookupStatic(), NotifyInterfaceDown(), NotifyRemoveAddress(), RemoveRoute(), and SetDefaultMulticastRoute().
The documentation for this class was generated from the following files:
src/internet/model/ipv4-static-routing.h
src/internet/model/ipv4-static-routing.cc