ns-3: ns3::dsr::DsrOptionRerr Class Reference
ns3::dsr::DsrOptionRerr Class Reference
Dsr Option Route Error.
#include "dsr-options.h"
Public Member Functions
DsrOptionRerr ()
virtual ~DsrOptionRerr ()
uint8_t DoSendError (Ptr< Packet > p, DsrOptionRerrUnreachHeader &rerr, uint32_t rerrSize, Ipv4Address ipv4Address, uint8_t protocol)
Do Send error message.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
virtual uint8_t GetOptionNumber () const
Get the option number.
virtual uint8_t Process (Ptr< Packet > packet, Ptr< Packet > dsrP, Ipv4Address ipv4Address, Ipv4Address source, Ipv4Header const &ipv4Header, uint8_t protocol, bool &isPromisc, Ipv4Address promiscSource)
Process method.
Public Member Functions inherited from ns3::dsr::DsrOptions
DsrOptions ()
Constructor.
virtual ~DsrOptions ()
Destructor.
bool CheckDuplicates (Ipv4Address ipv4Address, std::vector< Ipv4Address > &vec)
Check if the route already contains the node ip address.
bool ContainAddressAfter (Ipv4Address ipv4Address, Ipv4Address destAddress, std::vector< Ipv4Address > &nodeList)
Search for the ipv4 address in the node list.
std::vector< Ipv4Address > CutRoute (Ipv4Address ipv4Address, std::vector< Ipv4Address > &nodeList)
Cut the route from ipv4Address to the end of the route vector.
uint32_t GetIDfromIP (Ipv4Address address)
Get the node id with Ipv4Address.
Ptr< Node > GetNode () const
Get the node.
Ptr< Node > GetNodeWithAddress (Ipv4Address ipv4Address)
Get the node object with Ipv4Address.
bool IfDuplicates (std::vector< Ipv4Address > &vec, std::vector< Ipv4Address > &vec2)
Check if the two vectors contain duplicate or not.
void PrintVector (std::vector< Ipv4Address > &vec)
Print out the elements in the route vector.
void RemoveDuplicates (std::vector< Ipv4Address > &vec)
Remove the duplicates from the route.
bool ReverseRoutes (std::vector< Ipv4Address > &vec)
Reverse the routes.
Ipv4Address ReverseSearchNextHop (Ipv4Address ipv4Address, std::vector< Ipv4Address > &vec)
Reverse search for the next hop in the route.
Ipv4Address ReverseSearchNextTwoHop (Ipv4Address ipv4Address, std::vector< Ipv4Address > &vec)
Reverse search for the next two hop in the route.
void ScheduleReply (Ptr< Packet > &packet, std::vector< Ipv4Address > &nodeList, Ipv4Address &source, Ipv4Address &destination)
Schedule the intermediate node route request broadcast.
Ipv4Address SearchNextHop (Ipv4Address ipv4Address, std::vector< Ipv4Address > &vec)
Search for the next hop in the route.
void SetNode (Ptr< Node > node)
Set the node.
virtual Ptr< Ipv4Route > SetRoute (Ipv4Address nextHop, Ipv4Address srcAddress)
Set the route to use for data packets, used by the option headers when sending data/control packets.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the type ID.
Static Public Member Functions inherited from ns3::dsr::DsrOptions
static TypeId GetTypeId (void)
Get the type identificator.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Static Public Attributes
static const uint8_t OPT_NUMBER = 3
Dsr Route Error option number.
Private Attributes
Ptr< Ipv4 > m_ipv4
The ipv4 layer 3.
Ptr< dsr::DsrRouteCache > m_routeCache
The route cache.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes inherited from ns3::dsr::DsrOptions
Time ActiveRouteTimeout
The active route timeout value.
Ipv4Address Broadcast
The broadcast IP address.
TracedCallback< Ptr< const Packet > > m_dropTrace
Drop trace callback.
std::vector< Ipv4Address > m_finalRoute
The vector of final Ipv4 address.
Ptr< Ipv4 > m_ipv4
The ipv4.
std::vector< Ipv4Address > m_ipv4Address
The vector of Ipv4 address.
Ptr< Ipv4Route > m_ipv4Route
The ipv4 route.
Ptr< dsr::DsrRouteCache > m_routeCache
The route cache table.
Ptr< dsr::DsrRreqTable > m_rreqTable
The route request table.
TracedCallback< const DsrOptionSRHeader & > m_rxPacketTrace
The receive trace back, only triggered when final destination receive data packet.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Dsr Option Route Error.
Definition at line 449 of file dsr-options.h.
Constructor & Destructor Documentation
DsrOptionRerr()
ns3::dsr::DsrOptionRerr::DsrOptionRerr ()
Definition at line 1416 of file dsr-options.cc.
References NS_LOG_FUNCTION_NOARGS.
~DsrOptionRerr()
ns3::dsr::DsrOptionRerr::~DsrOptionRerr () virtual
Definition at line 1421 of file dsr-options.cc.
References NS_LOG_FUNCTION_NOARGS.
Member Function Documentation
DoSendError()
uint8_t ns3::dsr::DsrOptionRerr::DoSendError (Ptr< Packet > p, DsrOptionRerrUnreachHeader & rerr, uint32_t rerrSize, Ipv4Address ipv4Address, uint8_t protocol)
Do Send error message.
Parameters
p the packet
rerr the DsrOptionRerrUnreachHeader header
rerrSize the route error header size
ipv4Address ipv4 address of our own
protocol the protocol number of the up layer
Returns
the processed size
to test if the next address is multicast or not
Definition at line 1505 of file dsr-options.cc.
References ns3::Packet::CopyData(), ns3::dsr::DsrOptionHeader::GetLength(), ns3::dsr::DsrOptionSRHeader::GetNodeAddress(), ns3::dsr::DsrOptionSRHeader::GetNodesAddress(), ns3::dsr::DsrOptions::GetNodeWithAddress(), ns3::Object::GetObject(), ns3::dsr::DsrOptionSRHeader::GetSalvage(), ns3::dsr::DsrOptionSRHeader::GetSegmentsLeft(), ns3::dsr::DsrOptionSRHeader::GetSerializedSize(), ns3::Packet::GetSize(), ns3::Ipv4Address::IsMulticast(), ns3::dsr::DsrOptions::m_dropTrace, ns3::dsr::DsrOptions::m_ipv4Route, NS_ASSERT, NS_LOG_DEBUG, NS_LOG_INFO, NS_LOG_LOGIC(), ns3::Packet::RemoveHeader(), ns3::dsr::DsrOptionSRHeader::SetNodesAddress(), ns3::dsr::DsrOptionSRHeader::SetNumberAddress(), ns3::dsr::DsrOptions::SetRoute(), ns3::dsr::DsrOptionSRHeader::SetSalvage(), and ns3::dsr::DsrOptionSRHeader::SetSegmentsLeft().
Referenced by Process().
GetInstanceTypeId()
TypeId ns3::dsr::DsrOptionRerr::GetInstanceTypeId () const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::Object.
Definition at line 1426 of file dsr-options.cc.
References GetTypeId().
GetOptionNumber()
uint8_t ns3::dsr::DsrOptionRerr::GetOptionNumber () const virtual
Get the option number.
Returns
option number
Implements ns3::dsr::DsrOptions.
Definition at line 1431 of file dsr-options.cc.
References NS_LOG_FUNCTION_NOARGS, and OPT_NUMBER.
GetTypeId()
TypeId ns3::dsr::DsrOptionRerr::GetTypeId () static
Get the type ID.
Returns
the object TypeId
Definition at line 1406 of file dsr-options.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Process()
uint8_t ns3::dsr::DsrOptionRerr::Process (Ptr< Packet > packet, Ptr< Packet > dsrP, Ipv4Address ipv4Address, Ipv4Address source, Ipv4Header const & ipv4Header, uint8_t protocol, bool & isPromisc, Ipv4Address promiscSource) virtual
Process method.
Called from DsrRouting::Receive.
Parameters
packet the packet
dsrP the clean packet with payload
ipv4Address the IPv4 address
source IPv4 address of the source
ipv4Header the IPv4 header of packet received
protocol the protocol number of the up layer
isPromisc if the packet must be dropped
promiscSource IPv4 address
Returns
the processed size
Todo:
This is for the other two error options, not supporting for now
Implements ns3::dsr::DsrOptions.
Definition at line 1437 of file dsr-options.cc.
References ns3::Packet::Copy(), ns3::Packet::CopyData(), data, DoSendError(), ns3::dsr::DsrOptionRerrUnreachHeader::GetErrorDst(), ns3::dsr::DsrOptionRerrUnreachHeader::GetErrorSrc(), ns3::dsr::DsrOptions::GetNodeWithAddress(), ns3::Object::GetObject(), ns3::dsr::DsrOptionRerrUnreachHeader::GetSerializedSize(), ns3::dsr::DsrOptionRerrUnsupportHeader::GetSerializedSize(), ns3::Packet::GetSize(), ns3::dsr::DsrOptionRerrUnreachHeader::GetUnreachNode(), NS_LOG_DEBUG, NS_LOG_FUNCTION, NS_UNUSED, and ns3::Packet::RemoveHeader().
Member Data Documentation
m_ipv4
Ptr<Ipv4> ns3::dsr::DsrOptionRerr::m_ipv4 private
The ipv4 layer 3.
Definition at line 493 of file dsr-options.h.
m_routeCache
Ptr<dsr::DsrRouteCache> ns3::dsr::DsrOptionRerr::m_routeCache private
The route cache.
Definition at line 489 of file dsr-options.h.
OPT_NUMBER
const uint8_t ns3::dsr::DsrOptionRerr::OPT_NUMBER = 3 static
Dsr Route Error option number.
Definition at line 455 of file dsr-options.h.
Referenced by GetOptionNumber().
The documentation for this class was generated from the following files:
src/dsr/model/dsr-options.h
src/dsr/model/dsr-options.cc