ns-3: CsmaBridgeTestCase Class Reference
CsmaBridgeTestCase Class Reference
Public Member Functions
CsmaBridgeTestCase ()
virtual ~CsmaBridgeTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
void SinkRx (Ptr< const Packet > p, const Address &ad)
Private Attributes
uint32_t m_count
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 54 of file csma-system-test-suite.cc.
Constructor & Destructor Documentation
CsmaBridgeTestCase()
CsmaBridgeTestCase::CsmaBridgeTestCase ()
Definition at line 67 of file csma-system-test-suite.cc.
~CsmaBridgeTestCase()
CsmaBridgeTestCase::~CsmaBridgeTestCase () virtual
Definition at line 72 of file csma-system-test-suite.cc.
Member Function Documentation
DoRun()
void CsmaBridgeTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 95 of file csma-system-test-suite.cc.
References ns3::NetDeviceContainer::Add(), ns3::Ipv4AddressHelper::Assign(), ns3::Config::ConnectWithoutContext(), ns3::NodeContainer::Create(), second::csma, ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::OnOffHelper::Install(), ns3::BridgeHelper::Install(), ns3::InternetStackHelper::Install(), m_count, ns3::MakeCallback(), ns3::MilliSeconds(), NS_TEST_ASSERT_MSG_EQ, port, ns3::Seconds(), ns3::Ipv4AddressHelper::SetBase(), ns3::OnOffHelper::SetConstantRate(), sink, SinkRx(), ns3::ApplicationContainer::Start(), and ns3::ApplicationContainer::Stop().
SinkRx()
void CsmaBridgeTestCase::SinkRx (Ptr< const Packet > p, const Address & ad) private
Definition at line 77 of file csma-system-test-suite.cc.
References m_count.
Referenced by DoRun().
Member Data Documentation
m_count
uint32_t CsmaBridgeTestCase::m_count private
Definition at line 63 of file csma-system-test-suite.cc.
Referenced by DoRun(), and SinkRx().
The documentation for this class was generated from the following file:
src/test/csma-system-test-suite.cc