ns-3: FqCoDelQueueDiscTCPFlowsSeparation Class Reference
FqCoDelQueueDiscTCPFlowsSeparation Class Reference
This class tests the TCP flows separation.
Public Member Functions
FqCoDelQueueDiscTCPFlowsSeparation ()
virtual ~FqCoDelQueueDiscTCPFlowsSeparation ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void AddPacket (Ptr< FqCoDelQueueDisc > queue, Ipv4Header ipHdr, TcpHeader tcpHdr)
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
This class tests the TCP flows separation.
Definition at line 347 of file fq-codel-queue-disc-test-suite.cc.
Constructor & Destructor Documentation
FqCoDelQueueDiscTCPFlowsSeparation()
FqCoDelQueueDiscTCPFlowsSeparation::FqCoDelQueueDiscTCPFlowsSeparation ()
Definition at line 358 of file fq-codel-queue-disc-test-suite.cc.
~FqCoDelQueueDiscTCPFlowsSeparation()
FqCoDelQueueDiscTCPFlowsSeparation::~FqCoDelQueueDiscTCPFlowsSeparation () virtual
Definition at line 363 of file fq-codel-queue-disc-test-suite.cc.
Member Function Documentation
AddPacket()
void FqCoDelQueueDiscTCPFlowsSeparation::AddPacket (Ptr< FqCoDelQueueDisc > queue, Ipv4Header ipHdr, TcpHeader tcpHdr) private
Definition at line 368 of file fq-codel-queue-disc-test-suite.cc.
References ns3::Packet::AddHeader(), and ns3::QueueDisc::Enqueue().
Referenced by DoRun().
DoRun()
void FqCoDelQueueDiscTCPFlowsSeparation::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 378 of file fq-codel-queue-disc-test-suite.cc.
References AddPacket(), ns3::QueueDisc::GetQueueDiscClass(), ns3::Object::Initialize(), NS_TEST_ASSERT_MSG_EQ, ns3::Ipv4Header::SetDestination(), ns3::TcpHeader::SetDestinationPort(), ns3::Ipv4Header::SetPayloadSize(), ns3::Ipv4Header::SetProtocol(), ns3::FqCoDelQueueDisc::SetQuantum(), ns3::Ipv4Header::SetSource(), and ns3::TcpHeader::SetSourcePort().
The documentation for this class was generated from the following file:
src/test/ns3tc/fq-codel-queue-disc-test-suite.cc