ns-3: ns3::MgtAddBaResponseHeader Class Reference
ns3::MgtAddBaResponseHeader Class Reference
Wifi Models
#include "mgt-headers.h"
Public Member Functions
MgtAddBaResponseHeader ()
uint32_t Deserialize (Buffer::Iterator start)
uint16_t GetBufferSize (void) const
Return the buffer size.
TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint32_t GetSerializedSize (void) const
StatusCode GetStatusCode (void) const
Return the status code.
uint8_t GetTid (void) const
Return the Traffic ID (TID).
uint16_t GetTimeout (void) const
Return the timeout.
bool IsAmsduSupported (void) const
Return whether A-MSDU capability is supported.
bool IsImmediateBlockAck (void) const
Return whether the Block Ack policy is immediate Block Ack.
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetAmsduSupport (bool supported)
Enable or disable A-MSDU support.
void SetBufferSize (uint16_t size)
Set buffer size.
void SetDelayedBlockAck ()
Enable delayed BlockAck.
void SetImmediateBlockAck ()
Enable immediate BlockAck.
void SetStatusCode (StatusCode code)
Set the status code.
void SetTid (uint8_t tid)
Set Traffic ID (TID).
void SetTimeout (uint16_t timeout)
Set timeout.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
uint16_t GetParameterSet (void) const
Return the raw parameter set.
void SetParameterSet (uint16_t params)
Set the parameter set from the given raw value.
Private Attributes
uint8_t m_amsduSupport
Flag if A-MSDU is supported.
uint16_t m_bufferSize
Buffer size.
StatusCode m_code
Status code.
uint8_t m_dialogToken
Not used for now.
uint8_t m_policy
Block ACK policy.
uint8_t m_tid
Traffic ID.
uint16_t m_timeoutValue
Timeout.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Implement the header for management frames of type Add Block Ack response.
Definition at line 1135 of file mgt-headers.h.
Constructor & Destructor Documentation
MgtAddBaResponseHeader()
ns3::MgtAddBaResponseHeader::MgtAddBaResponseHeader ()
Definition at line 1629 of file mgt-headers.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::MgtAddBaResponseHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 1681 of file mgt-headers.cc.
References ns3::StatusCode::Deserialize(), ns3::Buffer::Iterator::GetDistanceFrom(), m_code, m_dialogToken, m_timeoutValue, ns3::Buffer::Iterator::ReadLsbtohU16(), ns3::Buffer::Iterator::ReadU8(), SetParameterSet(), and visualizer.core::start().
GetBufferSize()
uint16_t ns3::MgtAddBaResponseHeader::GetBufferSize (void) const
Return the buffer size.
Returns
the buffer size.
Definition at line 1759 of file mgt-headers.cc.
References m_bufferSize.
Referenced by ns3::MacLow::CreateBlockAckAgreement(), and ns3::BlockAckManager::UpdateAgreement().
GetInstanceTypeId()
TypeId ns3::MgtAddBaResponseHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 1648 of file mgt-headers.cc.
References GetTypeId().
GetParameterSet()
uint16_t ns3::MgtAddBaResponseHeader::GetParameterSet (void) const private
Return the raw parameter set.
Returns
the raw parameter set
Definition at line 1771 of file mgt-headers.cc.
References m_amsduSupport, m_bufferSize, m_policy, and m_tid.
Referenced by Serialize().
GetSerializedSize()
uint32_t ns3::MgtAddBaResponseHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 1660 of file mgt-headers.cc.
References ns3::StatusCode::GetSerializedSize(), and m_code.
GetStatusCode()
StatusCode ns3::MgtAddBaResponseHeader::GetStatusCode (void) const
Return the status code.
Returns
the status code
Definition at line 1735 of file mgt-headers.cc.
References m_code.
Referenced by ns3::QosTxop::GotAddBaResponse().
GetTid()
uint8_t ns3::MgtAddBaResponseHeader::GetTid (void) const
Return the Traffic ID (TID).
Returns
TID
Definition at line 1741 of file mgt-headers.cc.
References m_tid.
Referenced by ns3::MacLow::CreateBlockAckAgreement(), ns3::GetTid(), ns3::QosTxop::GotAddBaResponse(), ns3::RegularWifiMac::Receive(), and ns3::BlockAckManager::UpdateAgreement().
GetTimeout()
uint16_t ns3::MgtAddBaResponseHeader::GetTimeout (void) const
Return the timeout.
Returns
timeout
Definition at line 1753 of file mgt-headers.cc.
References m_timeoutValue.
Referenced by ns3::MacLow::CreateBlockAckAgreement(), and ns3::BlockAckManager::UpdateAgreement().
GetTypeId()
TypeId ns3::MgtAddBaResponseHeader::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 1637 of file mgt-headers.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
IsAmsduSupported()
bool ns3::MgtAddBaResponseHeader::IsAmsduSupported (void) const
Return whether A-MSDU capability is supported.
Returns
true is A-MSDU is supported, false otherwise
Definition at line 1765 of file mgt-headers.cc.
References m_amsduSupport.
Referenced by ns3::MacLow::CreateBlockAckAgreement(), and ns3::BlockAckManager::UpdateAgreement().
IsImmediateBlockAck()
bool ns3::MgtAddBaResponseHeader::IsImmediateBlockAck (void) const
Return whether the Block Ack policy is immediate Block Ack.
Returns
true if immediate Block Ack is being used, false otherwise
Definition at line 1747 of file mgt-headers.cc.
References m_policy.
Referenced by ns3::MacLow::CreateBlockAckAgreement(), and ns3::BlockAckManager::UpdateAgreement().
Print()
void ns3::MgtAddBaResponseHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 1654 of file mgt-headers.cc.
References m_code.
Serialize()
void ns3::MgtAddBaResponseHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 1671 of file mgt-headers.cc.
References GetParameterSet(), m_code, m_dialogToken, m_timeoutValue, ns3::StatusCode::Serialize(), visualizer.core::start(), ns3::Buffer::Iterator::WriteHtolsbU16(), and ns3::Buffer::Iterator::WriteU8().
SetAmsduSupport()
void ns3::MgtAddBaResponseHeader::SetAmsduSupport (bool supported)
Enable or disable A-MSDU support.
Parameters
supported enable or disable A-MSDU support
Definition at line 1729 of file mgt-headers.cc.
References m_amsduSupport.
Referenced by ns3::RegularWifiMac::SendAddBaResponse().
SetBufferSize()
void ns3::MgtAddBaResponseHeader::SetBufferSize (uint16_t size)
Set buffer size.
Parameters
size buffer size
Definition at line 1717 of file mgt-headers.cc.
References m_bufferSize.
Referenced by ns3::RegularWifiMac::SendAddBaResponse().
SetDelayedBlockAck()
void ns3::MgtAddBaResponseHeader::SetDelayedBlockAck ()
Enable delayed BlockAck.
Definition at line 1692 of file mgt-headers.cc.
References m_policy.
Referenced by ns3::RegularWifiMac::SendAddBaResponse().
SetImmediateBlockAck()
void ns3::MgtAddBaResponseHeader::SetImmediateBlockAck ()
Enable immediate BlockAck.
Definition at line 1698 of file mgt-headers.cc.
References m_policy.
Referenced by ns3::RegularWifiMac::SendAddBaResponse().
SetParameterSet()
void ns3::MgtAddBaResponseHeader::SetParameterSet (uint16_t params) private
Set the parameter set from the given raw value.
Parameters
params raw parameter set value
Definition at line 1782 of file mgt-headers.cc.
References m_amsduSupport, m_bufferSize, m_policy, m_tid, and aloha::params.
Referenced by Deserialize().
SetStatusCode()
void ns3::MgtAddBaResponseHeader::SetStatusCode (StatusCode code)
Set the status code.
Parameters
code the status code
Definition at line 1723 of file mgt-headers.cc.
References m_code.
Referenced by ns3::RegularWifiMac::SendAddBaResponse().
SetTid()
void ns3::MgtAddBaResponseHeader::SetTid (uint8_t tid)
Set Traffic ID (TID).
Parameters
tid traffic ID
Definition at line 1704 of file mgt-headers.cc.
References m_tid, and NS_ASSERT.
Referenced by ns3::RegularWifiMac::SendAddBaResponse().
SetTimeout()
void ns3::MgtAddBaResponseHeader::SetTimeout (uint16_t timeout)
Set timeout.
Parameters
timeout timeout
Definition at line 1711 of file mgt-headers.cc.
References m_timeoutValue, and timeout.
Referenced by ns3::RegularWifiMac::SendAddBaResponse().
Member Data Documentation
m_amsduSupport
uint8_t ns3::MgtAddBaResponseHeader::m_amsduSupport private
Flag if A-MSDU is supported.
Definition at line 1244 of file mgt-headers.h.
Referenced by GetParameterSet(), IsAmsduSupported(), SetAmsduSupport(), and SetParameterSet().
m_bufferSize
uint16_t ns3::MgtAddBaResponseHeader::m_bufferSize private
Buffer size.
Definition at line 1247 of file mgt-headers.h.
Referenced by GetBufferSize(), GetParameterSet(), SetBufferSize(), and SetParameterSet().
m_code
StatusCode ns3::MgtAddBaResponseHeader::m_code private
Status code.
Definition at line 1243 of file mgt-headers.h.
Referenced by Deserialize(), GetSerializedSize(), GetStatusCode(), Print(), Serialize(), and SetStatusCode().
m_dialogToken
uint8_t ns3::MgtAddBaResponseHeader::m_dialogToken private
Not used for now.
Definition at line 1242 of file mgt-headers.h.
Referenced by Deserialize(), and Serialize().
m_policy
uint8_t ns3::MgtAddBaResponseHeader::m_policy private
Block ACK policy.
Definition at line 1245 of file mgt-headers.h.
Referenced by GetParameterSet(), IsImmediateBlockAck(), SetDelayedBlockAck(), SetImmediateBlockAck(), and SetParameterSet().
m_tid
uint8_t ns3::MgtAddBaResponseHeader::m_tid private
Traffic ID.
Definition at line 1246 of file mgt-headers.h.
Referenced by GetParameterSet(), GetTid(), SetParameterSet(), and SetTid().
m_timeoutValue
uint16_t ns3::MgtAddBaResponseHeader::m_timeoutValue private
Timeout.
Definition at line 1248 of file mgt-headers.h.
Referenced by Deserialize(), GetTimeout(), Serialize(), and SetTimeout().
The documentation for this class was generated from the following files:
src/wifi/model/mgt-headers.h
src/wifi/model/mgt-headers.cc