ns-3: ns3::LteRlcSapProvider Class Reference
ns3::LteRlcSapProvider Class Reference abstract
Service Access Point (SAP) offered by the UM-RLC and AM-RLC entities to the PDCP entity See 3GPP 36.322 Radio Link Control (RLC) protocol specification.
#include "lte-rlc-sap.h"
Classes
struct TransmitPdcpPduParameters
Parameters for LteRlcSapProvider::TransmitPdcpPdu.
Public Member Functions
virtual ~LteRlcSapProvider ()
virtual void TransmitPdcpPdu (TransmitPdcpPduParameters params)=0
Send a PDCP PDU to the RLC for transmission This method is to be called when upper PDCP entity has a PDCP PDU ready to send.
Detailed Description
Service Access Point (SAP) offered by the UM-RLC and AM-RLC entities to the PDCP entity See 3GPP 36.322 Radio Link Control (RLC) protocol specification.
This is the RLC SAP Provider (i.e. the part of the SAP that contains the RLC methods called by the PDCP)
Definition at line 35 of file lte-rlc-sap.h.
Constructor & Destructor Documentation
~LteRlcSapProvider()
ns3::LteRlcSapProvider::~LteRlcSapProvider () virtual
Definition at line 25 of file lte-rlc-sap.cc.
Member Function Documentation
TransmitPdcpPdu()
virtual void ns3::LteRlcSapProvider::TransmitPdcpPdu (TransmitPdcpPduParameters params) pure virtual
Send a PDCP PDU to the RLC for transmission This method is to be called when upper PDCP entity has a PDCP PDU ready to send.
Parameters
params the TransmitPdcpPduParameters
Implemented in ns3::LteRlcSpecificLteRlcSapProvider< C >.
Referenced by ns3::LteUeRrcProtocolReal::DoSendRrcConnectionReestablishmentRequest(), ns3::LteUeRrcProtocolReal::DoSendRrcConnectionRequest(), ns3::LtePdcp::DoTransmitPdcpSdu(), and ns3::LteTestPdcp::SendData().
The documentation for this class was generated from the following files:
src/lte/model/lte-rlc-sap.h
src/lte/model/lte-rlc-sap.cc