ns-3: ns3::tests::Hash32FunctionPtrTestCase Class Reference
ns3::tests::Hash32FunctionPtrTestCase Class Reference
Test suites | Core » Core module tests | Core » Hash Functions » Hash test suite
Public Member Functions
Hash32FunctionPtrTestCase ()
Constructor.
virtual ~Hash32FunctionPtrTestCase ()
Destructor.
Public Member Functions inherited from ns3::tests::HashTestCase
HashTestCase (const std::string name)
Constructor.
virtual ~HashTestCase ()
Destructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::tests::HashTestCase
void Check (const std::string hashName, const uint32_t hash)
Check function.
void Check (const std::string hashName, const uint64_t hash)
Check function.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Protected Attributes inherited from ns3::tests::HashTestCase
uint32_t hash32Reference
The 32-bit hash of the reference.
uint64_t hash64Reference
The 64-bit hash of the reference.
std::string key
The reference value to hash.
Detailed Description
Test 32-bit function pointer
Definition at line 313 of file hash-test-suite.cc.
Constructor & Destructor Documentation
Hash32FunctionPtrTestCase()
ns3::tests::Hash32FunctionPtrTestCase::Hash32FunctionPtrTestCase ()
Constructor.
Definition at line 325 of file hash-test-suite.cc.
~Hash32FunctionPtrTestCase()
ns3::tests::Hash32FunctionPtrTestCase::~Hash32FunctionPtrTestCase () virtual
Destructor.
Definition at line 329 of file hash-test-suite.cc.
Member Function Documentation
DoRun()
void ns3::tests::Hash32FunctionPtrTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Reimplemented from ns3::tests::HashTestCase.
Definition at line 333 of file hash-test-suite.cc.
References ns3::tests::HashTestCase::Check(), ns3::Hasher::clear(), ns3::Hasher::GetHash32(), ns3::tests::gnu_sum32(), ns3::tests::HashTestCase::hash32Reference, and ns3::tests::HashTestCase::key.
The documentation for this class was generated from the following file:
src/core/test/hash-test-suite.cc