ns-3: ns3::Channel Class Reference
ns3::Channel Class Reference abstract
Network » Channel
Abstract Channel Base Class.
#include "channel.h"
Public Member Functions
Channel ()
virtual ~Channel ()
virtual Ptr< NetDevice > GetDevice (std::size_t i) const =0
uint32_t GetId (void) const
virtual std::size_t GetNDevices (void) const =0
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint32_t m_id
Channel id for this channel.
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Abstract Channel Base Class.
A channel is a logical path over which information flows. The path can be as simple as a short piece of wire, or as complicated as space-time.
Subclasses must use Simulator::ScheduleWithContext to correctly update event contexts when scheduling an event from one node to another one.
Definition at line 43 of file channel.h.
Constructor & Destructor Documentation
Channel()
ns3::Channel::Channel ()
Definition at line 46 of file channel.cc.
References ns3::ChannelList::Add(), m_id, and NS_LOG_FUNCTION.
~Channel()
ns3::Channel::~Channel () virtual
Definition at line 53 of file channel.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
GetDevice()
virtual Ptr<NetDevice> ns3::Channel::GetDevice (std::size_t i) const pure virtual
Parameters
i index of NetDevice to retrieve
Returns
one of the NetDevices connected to this channel.
This method must be implemented by subclasses.
Implemented in ns3::WimaxChannel, ns3::YansWifiChannel, ns3::UanChannel, ns3::SingleModelSpectrumChannel, ns3::MultiModelSpectrumChannel, ns3::PointToPointChannel, ns3::SimpleChannel, ns3::ErrorChannel, ns3::lorawan::LoraChannel, ns3::CsmaChannel, and ns3::BridgeChannel.
GetId()
uint32_t ns3::Channel::GetId (void) const
Returns
the unique id of this channel
This unique id happens to be also the index of the Channel into the ChannelList.
Definition at line 59 of file channel.cc.
References m_id, and NS_LOG_FUNCTION.
GetNDevices()
virtual std::size_t ns3::Channel::GetNDevices (void) const pure virtual
Returns
the number of NetDevices connected to this Channel.
This method must be implemented by subclasses.
Implemented in ns3::WimaxChannel, ns3::YansWifiChannel, ns3::UanChannel, ns3::SingleModelSpectrumChannel, ns3::MultiModelSpectrumChannel, ns3::PointToPointChannel, ns3::SimpleChannel, ns3::ErrorChannel, ns3::lorawan::LoraChannel, ns3::CsmaChannel, and ns3::BridgeChannel.
GetTypeId()
TypeId ns3::Channel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 33 of file channel.cc.
References ns3::TypeId::ATTR_GET, m_id, ns3::MakeUintegerAccessor(), and ns3::TypeId::SetParent().
Member Data Documentation
m_id
uint32_t ns3::Channel::m_id private
Channel id for this channel.
Definition at line 78 of file channel.h.
Referenced by Channel(), GetId(), and GetTypeId().
The documentation for this class was generated from the following files:
src/network/model/channel.h
src/network/model/channel.cc