ns-3: ns3::DrbActivator Class Reference
ns3::DrbActivator Class Reference
LTE Models
Public Member Functions
DrbActivator (Ptr< NetDevice > ueDevice, EpsBearer bearer)
DrbActivator Constructor.
void ActivateDrb (uint64_t imsi, uint16_t cellId, uint16_t rnti)
Procedure firstly checks if bearer was not activated, if IMSI from trace source equals configured one and if UE is really in RRC connected state.
Public Member Functions inherited from ns3::SimpleRefCount< DrbActivator >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Static Public Member Functions
static void ActivateCallback (Ptr< DrbActivator > a, std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti)
Function hooked to the Enb RRC Connection Established trace source Fired upon successful RRC connection establishment.
Private Attributes
bool m_active
Bearer can be activated only once.
EpsBearer m_bearer
Configuration of bearer which will be activated.
uint64_t m_imsi
imsi the unique UE identifier
Ptr< NetDevice > m_ueDevice
UeNetDevice for which bearer will be activated.
Detailed Description
DrbActivatior allows user to activate bearers for UEs when EPC is not used. Activation function is hooked to the Enb RRC Connection Established trace source. When UE change its RRC state to CONNECTED_NORMALLY, activation function is called and bearer is activated.
Definition at line 1102 of file lte-helper.cc.
Constructor & Destructor Documentation
DrbActivator()
ns3::DrbActivator::DrbActivator (Ptr< NetDevice > ueDevice, EpsBearer bearer)
DrbActivator Constructor.
Parameters
ueDevice the UeNetDevice for which bearer will be activated
bearer the bearer configuration
Definition at line 1157 of file lte-helper.cc.
Member Function Documentation
ActivateCallback()
void ns3::DrbActivator::ActivateCallback (Ptr< DrbActivator > a, std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti) static
Function hooked to the Enb RRC Connection Established trace source Fired upon successful RRC connection establishment.
Parameters
a DrbActivator object
context
imsi
cellId
rnti
Definition at line 1166 of file lte-helper.cc.
References NS_LOG_FUNCTION.
Referenced by ns3::LteHelper::ActivateDataRadioBearer().
ActivateDrb()
void ns3::DrbActivator::ActivateDrb (uint64_t imsi, uint16_t cellId, uint16_t rnti)
Procedure firstly checks if bearer was not activated, if IMSI from trace source equals configured one and if UE is really in RRC connected state.
If all requirements are met, it performs bearer activation.
Parameters
imsi
cellId
rnti
Definition at line 1173 of file lte-helper.cc.
References ns3::UeManager::CONNECTED_NORMALLY, ns3::LteUeRrc::CONNECTED_NORMALLY, ns3::UeManager::CONNECTION_RECONFIGURATION, ns3::LteEnbNetDevice::GetCellId(), ns3::Object::GetObject(), m_active, m_bearer, m_imsi, m_ueDevice, NS_ASSERT, NS_LOG_FUNCTION, and aloha::params.
Member Data Documentation
m_active
bool ns3::DrbActivator::m_active private
Bearer can be activated only once.
This value stores state of bearer. Initially is set to false and changed to true during bearer activation.
Definition at line 1142 of file lte-helper.cc.
Referenced by ActivateDrb().
m_bearer
EpsBearer ns3::DrbActivator::m_bearer private
Configuration of bearer which will be activated.
Definition at line 1150 of file lte-helper.cc.
Referenced by ActivateDrb().
m_imsi
uint64_t ns3::DrbActivator::m_imsi private
imsi the unique UE identifier
Definition at line 1154 of file lte-helper.cc.
Referenced by ActivateDrb().
m_ueDevice
Ptr<NetDevice> ns3::DrbActivator::m_ueDevice private
UeNetDevice for which bearer will be activated.
Definition at line 1146 of file lte-helper.cc.
Referenced by ActivateDrb().
The documentation for this class was generated from the following file:
src/lte/helper/lte-helper.cc