ns-3: ns3::LteEnbCmacSapUser Class Reference
ns3::LteEnbCmacSapUser Class Reference abstract
Service Access Point (SAP) offered by the MAC to the RRC See Femto Forum MAC Scheduler Interface Specification v 1.11, Figure 1.
#include "lte-enb-cmac-sap.h"
Classes
struct UeConfig
Parameters for [re]configuring the UE.
Public Member Functions
virtual ~LteEnbCmacSapUser ()
virtual uint16_t AllocateTemporaryCellRnti ()=0
request the allocation of a Temporary C-RNTI
virtual bool IsRandomAccessCompleted (uint16_t rnti)=0
Is random access completed function.
virtual void NotifyLcConfigResult (uint16_t rnti, uint8_t lcid, bool success)=0
notify the result of the last LC config operation
virtual void RrcConfigurationUpdateInd (UeConfig params)=0
Notify the RRC of a UE config updated requested by the MAC (normally, by the scheduler)
Detailed Description
Service Access Point (SAP) offered by the MAC to the RRC See Femto Forum MAC Scheduler Interface Specification v 1.11, Figure 1.
This is the MAC SAP User, i.e., the part of the SAP that contains the RRC methods called by the MAC
Definition at line 181 of file lte-enb-cmac-sap.h.
Constructor & Destructor Documentation
~LteEnbCmacSapUser()
ns3::LteEnbCmacSapUser::~LteEnbCmacSapUser () virtual
Definition at line 32 of file lte-enb-cmac-sap.cc.
Member Function Documentation
AllocateTemporaryCellRnti()
virtual uint16_t ns3::LteEnbCmacSapUser::AllocateTemporaryCellRnti () pure virtual
request the allocation of a Temporary C-RNTI
Returns
the T-C-RNTI
Implemented in ns3::EnbRrcMemberLteEnbCmacSapUser.
Referenced by ns3::LteEnbMac::DoSubframeIndication().
IsRandomAccessCompleted()
virtual bool ns3::LteEnbCmacSapUser::IsRandomAccessCompleted (uint16_t rnti) pure virtual
Is random access completed function.
This method is executed to decide if the non contention based preamble has to be reused or not upon preamble expiry. If the random access in connected mode is completed, then the preamble can be reused by other UEs. If not, the same UE retains the preamble and other available preambles are assigned to the required UEs.
Parameters
rnti the C-RNTI identifying the user
Returns
true if the random access in connected mode is completed
Implemented in ns3::EnbRrcMemberLteEnbCmacSapUser.
Referenced by ns3::LteEnbMac::DoAllocateNcRaPreamble().
NotifyLcConfigResult()
virtual void ns3::LteEnbCmacSapUser::NotifyLcConfigResult (uint16_t rnti, uint8_t lcid, bool success) pure virtual
notify the result of the last LC config operation
Parameters
rnti the rnti of the user
lcid the logical channel id
success true if the operation was successful, false otherwise
Implemented in ns3::EnbRrcMemberLteEnbCmacSapUser.
RrcConfigurationUpdateInd()
virtual void ns3::LteEnbCmacSapUser::RrcConfigurationUpdateInd (UeConfig params) pure virtual
Notify the RRC of a UE config updated requested by the MAC (normally, by the scheduler)
Parameters
params
Implemented in ns3::EnbRrcMemberLteEnbCmacSapUser.
Referenced by ns3::LteEnbMac::DoCschedUeConfigUpdateInd().
The documentation for this class was generated from the following files:
src/lte/model/lte-enb-cmac-sap.h
src/lte/model/lte-enb-cmac-sap.cc