ns-3: ns3::FriisPropagationLossModel Class Reference
ns3::FriisPropagationLossModel Class Reference
Propagation Models
a Friis propagation loss model
#include "propagation-loss-model.h"
Public Member Functions
FriisPropagationLossModel ()
double GetFrequency (void) const
double GetMinLoss (void) const
double GetSystemLoss (void) const
void SetFrequency (double frequency)
void SetMinLoss (double minLoss)
void SetSystemLoss (double systemLoss)
Public Member Functions inherited from ns3::PropagationLossModel
PropagationLossModel ()
virtual ~PropagationLossModel ()
int64_t AssignStreams (int64_t stream)
If this loss model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
double CalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account all the PropagationLossModel(s) chained to the current one.
Ptr< PropagationLossModel > GetNext ()
Gets the next PropagationLossModel in the chain of loss models that act on the signal.
void SetNext (Ptr< PropagationLossModel > next)
Enables a chain of loss models to act on the signal.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::PropagationLossModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
FriisPropagationLossModel (const FriisPropagationLossModel &)
Copy constructor.
double DbmFromW (double w) const
Transforms a Watt value to Dbm.
double DbmToW (double dbm) const
Transforms a Dbm value to Watt.
virtual int64_t DoAssignStreams (int64_t stream)
Subclasses must implement this; those not using random variables can return zero.
virtual double DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account only the particular PropagationLossModel.
FriisPropagationLossModel & operator= (const FriisPropagationLossModel &)
Copy constructor.
Private Attributes
double m_frequency
the carrier frequency
double m_lambda
the carrier wavelength
double m_minLoss
the minimum loss
double m_systemLoss
the system loss
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
a Friis propagation loss model
The Friis propagation loss model was first described in "A Note on a Simple Transmission Formula", by "Harald T. Friis".
The original equation was described as: with the following equation for the case of an isotropic antenna with no heat loss:
The final equation becomes:
Modern extensions to this original equation are:
With:
: reception power (W)
: transmission power (W)
: transmission gain (unit-less)
: reception gain (unit-less)
: wavelength (m)
: distance (m)
: system loss (unit-less)
In the implementation, is calculated as , where m/s is the speed of light in vacuum, and is the frequency in Hz which can be configured by the user via the Frequency attribute.
The Friis model is valid only for propagation in free space within the so-called far field region, which can be considered approximately as the region for . The model will still return a value for , as doing so (rather than triggering a fatal error) is practical for many simulation scenarios. However, we stress that the values obtained in such conditions shall not be considered realistic.
Related with this issue, we note that the Friis formula is undefined for , and results in for . Both these conditions occur outside of the far field region, so in principle the Friis model shall not be used in these conditions. In practice, however, Friis is often used in scenarios where accurate propagation modeling is not deemed important, and values of can occur. To allow practical use of the model in such scenarios, we have to 1) return some value for , and 2) avoid large discontinuities in propagation loss values (which could lead to artifacts such as bogus capture effects which are much worse than inaccurate propagation loss values). The two issues are conflicting, as, according to the Friis formula, ; so if, for , we use a fixed loss value, we end up with an infinitely large discontinuity, which as we discussed can cause undesirable simulation artifacts.
To avoid these artifact, this implementation of the Friis model provides an attribute called MinLoss which allows to specify the minimum total loss (in dB) returned by the model. This is used in such a way that continuously increases for , until MinLoss is reached, and then stay constant; this allow to return a value for and at the same time avoid discontinuities. The model won't be much realistic, but at least the simulation artifacts discussed before are avoided. The default value of MinLoss is 0 dB, which means that by default the model will return for . We note that this value of is outside of the far field region, hence the validity of the model in the far field region is not affected.
Definition at line 261 of file propagation-loss-model.h.
Constructor & Destructor Documentation
FriisPropagationLossModel() [1/2]
ns3::FriisPropagationLossModel::FriisPropagationLossModel ()
Definition at line 172 of file propagation-loss-model.cc.
FriisPropagationLossModel() [2/2]
ns3::FriisPropagationLossModel::FriisPropagationLossModel (const FriisPropagationLossModel &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Member Function Documentation
DbmFromW()
double ns3::FriisPropagationLossModel::DbmFromW (double w) const private
Transforms a Watt value to Dbm.
Parameters
w the Watt value
Returns
the Dbm
Definition at line 218 of file propagation-loss-model.cc.
DbmToW()
double ns3::FriisPropagationLossModel::DbmToW (double dbm) const private
Transforms a Dbm value to Watt.
Parameters
dbm the Dbm value
Returns
the Watts
Definition at line 211 of file propagation-loss-model.cc.
DoAssignStreams()
int64_t ns3::FriisPropagationLossModel::DoAssignStreams (int64_t stream) private virtual
Subclasses must implement this; those not using random variables can return zero.
Implements ns3::PropagationLossModel.
Definition at line 275 of file propagation-loss-model.cc.
DoCalcRxPower()
double ns3::FriisPropagationLossModel::DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const private virtual
Returns the Rx Power taking into account only the particular PropagationLossModel.
Parameters
txPowerDbm current transmission power (in dBm)
a the mobility model of the source
b the mobility model of the destination
Returns
the reception power after adding/multiplying propagation loss (in dBm)
Implements ns3::PropagationLossModel.
Definition at line 225 of file propagation-loss-model.cc.
References ns3::MobilityModel::GetDistanceFrom(), m_lambda, m_minLoss, m_systemLoss, max, NS_LOG_DEBUG, and NS_LOG_WARN.
GetFrequency()
double ns3::FriisPropagationLossModel::GetFrequency (void) const
Returns
the current frequency (Hz)
Definition at line 205 of file propagation-loss-model.cc.
References m_frequency.
Referenced by GetTypeId().
GetMinLoss()
double ns3::FriisPropagationLossModel::GetMinLoss (void) const
Returns
the minimum loss.
Definition at line 191 of file propagation-loss-model.cc.
References m_minLoss.
Referenced by GetTypeId().
GetSystemLoss()
double ns3::FriisPropagationLossModel::GetSystemLoss (void) const
Returns
the current system loss (dimension-less)
Definition at line 181 of file propagation-loss-model.cc.
References m_systemLoss.
GetTypeId()
TypeId ns3::FriisPropagationLossModel::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 146 of file propagation-loss-model.cc.
References GetFrequency(), GetMinLoss(), m_systemLoss, ns3::MakeDoubleAccessor(), SetFrequency(), SetMinLoss(), and ns3::TypeId::SetParent().
Referenced by ns3::LteHelper::GetTypeId().
operator=()
FriisPropagationLossModel& ns3::FriisPropagationLossModel::operator= (const FriisPropagationLossModel &) private
Copy constructor.
Defined and unimplemented to avoid misuse
Returns
SetFrequency()
void ns3::FriisPropagationLossModel::SetFrequency (double frequency)
Parameters
frequency (Hz)
Set the carrier frequency used in the Friis model calculation.
Definition at line 197 of file propagation-loss-model.cc.
References m_frequency, and m_lambda.
Referenced by Bug2843TestCase::DoRun(), and GetTypeId().
SetMinLoss()
void ns3::FriisPropagationLossModel::SetMinLoss (double minLoss)
Parameters
minLoss the minimum loss (dB)
no matter how short the distance, the total propagation loss (in dB) will always be greater or equal than this value
Definition at line 186 of file propagation-loss-model.cc.
References m_minLoss.
Referenced by GetTypeId().
SetSystemLoss()
void ns3::FriisPropagationLossModel::SetSystemLoss (double systemLoss)
Parameters
systemLoss (dimension-less)
Set the system loss used by the Friis propagation model.
Definition at line 176 of file propagation-loss-model.cc.
References m_systemLoss.
Member Data Documentation
m_frequency
double ns3::FriisPropagationLossModel::m_frequency private
the carrier frequency
Definition at line 341 of file propagation-loss-model.h.
Referenced by GetFrequency(), and SetFrequency().
m_lambda
double ns3::FriisPropagationLossModel::m_lambda private
the carrier wavelength
Definition at line 340 of file propagation-loss-model.h.
Referenced by DoCalcRxPower(), and SetFrequency().
m_minLoss
double ns3::FriisPropagationLossModel::m_minLoss private
the minimum loss
Definition at line 343 of file propagation-loss-model.h.
Referenced by DoCalcRxPower(), GetMinLoss(), and SetMinLoss().
m_systemLoss
double ns3::FriisPropagationLossModel::m_systemLoss private
the system loss
Definition at line 342 of file propagation-loss-model.h.
Referenced by DoCalcRxPower(), GetSystemLoss(), GetTypeId(), and SetSystemLoss().
The documentation for this class was generated from the following files:
src/propagation/model/propagation-loss-model.h
src/propagation/model/propagation-loss-model.cc