ns-3: LteRrcConnectionEstablishmentErrorTestCase Class Reference
LteRrcConnectionEstablishmentErrorTestCase Class Reference
LTE Models » lte module tests | Test suites
Lte Rrc Connection Establishment Error Test Case.
Public Member Functions
LteRrcConnectionEstablishmentErrorTestCase (Time jumpAwayTime, std::string description="")
Public Member Functions inherited from LteRrcConnectionEstablishmentTestCase
LteRrcConnectionEstablishmentTestCase (uint32_t nUes, uint32_t nBearers, uint32_t tConnBase, uint32_t tConnIncrPerUe, uint32_t delayDiscStart, bool errorExpected, bool useIdealRrc, bool admitRrcConnectionRequest, std::string description="")
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Protected Member Functions inherited from LteRrcConnectionEstablishmentTestCase
void CheckConnected (Ptr< NetDevice > ueDevice, Ptr< NetDevice > enbDevice)
Check connected function.
void CheckNotConnected (Ptr< NetDevice > ueDevice, Ptr< NetDevice > enbDevice)
Check not connected function.
void Connect (Ptr< NetDevice > ueDevice, Ptr< NetDevice > enbDevice)
Connect function.
void ConnectionEstablishedCallback (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti)
Connection established callback function.
void ConnectionTimeoutCallback (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti, uint8_t connEstFailCount)
Connection timeout callback function.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Private Member Functions
void JumpAway ()
Jump away function.
void JumpBack ()
Jump back function.
Private Attributes
Time m_jumpAwayTime
jump away time
Ptr< MobilityModel > m_ueMobility
UE mobility model.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Static Protected Member Functions inherited from LteRrcConnectionEstablishmentTestCase
static std::string BuildNameString (uint32_t nUes, uint32_t nBearers, uint32_t tConnBase, uint32_t tConnIncrPerUe, uint32_t delayDiscStart, bool useIdealRrc, bool admitRrcConnectionRequest, std::string description="")
Build name string function.
Protected Attributes inherited from LteRrcConnectionEstablishmentTestCase
bool m_admitRrcConnectionRequest
If set to false, eNb will not allow UE connections.
uint32_t m_delayConnEnd
expected duration to perform connection establishment in ms
uint32_t m_delayDiscEnd
expected duration to complete disconnection in ms
uint32_t m_delayDiscStart
delay between connection completed and disconnection request in ms
std::map< uint64_t, bool > m_isConnectionEstablished
key: IMSI
Ptr< LteHelper > m_lteHelper
LTE helper.
uint32_t m_nBearers
number of bearers to be setup in each connection
uint32_t m_nUes
number of UEs in the test
uint32_t m_tConnBase
connection time base value for all UEs in ms
uint32_t m_tConnIncrPerUe
additional connection time increment for each UE index (0...nUes-1) in ms
bool m_useIdealRrc
If set to false, real RRC protocol model will be used.
Detailed Description
Lte Rrc Connection Establishment Error Test Case.
Definition at line 553 of file test-lte-rrc.cc.
Constructor & Destructor Documentation
LteRrcConnectionEstablishmentErrorTestCase()
LteRrcConnectionEstablishmentErrorTestCase::LteRrcConnectionEstablishmentErrorTestCase (Time jumpAwayTime, std::string description = "")
Parameters
jumpAwayTime the time when all the UEs 'teleport' to a pre-defined high-interference position and stay there for 100 ms
description additional description of the test case
Definition at line 580 of file test-lte-rrc.cc.
References ns3::TestCase::GetName(), and NS_LOG_FUNCTION.
Member Function Documentation
DoRun()
void LteRrcConnectionEstablishmentErrorTestCase::DoRun (void) protected virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Reimplemented from LteRrcConnectionEstablishmentTestCase.
Definition at line 591 of file test-lte-rrc.cc.
References ns3::LteHelper::AssignStreams(), ns3::NetDeviceContainer::Begin(), LteRrcConnectionEstablishmentTestCase::CheckNotConnected(), LteRrcConnectionEstablishmentTestCase::Connect(), ns3::Config::Connect(), LteRrcConnectionEstablishmentTestCase::ConnectionEstablishedCallback(), LteRrcConnectionEstablishmentTestCase::ConnectionTimeoutCallback(), ns3::NodeContainer::Create(), ns3::NetDeviceContainer::End(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::LteUeNetDevice::GetImsi(), ns3::TestCase::GetName(), ns3::Object::GetObject(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), JumpAway(), JumpBack(), LteRrcConnectionEstablishmentTestCase::m_admitRrcConnectionRequest, LteRrcConnectionEstablishmentTestCase::m_delayConnEnd, LteRrcConnectionEstablishmentTestCase::m_delayDiscEnd, LteRrcConnectionEstablishmentTestCase::m_delayDiscStart, LteRrcConnectionEstablishmentTestCase::m_isConnectionEstablished, m_jumpAwayTime, LteRrcConnectionEstablishmentTestCase::m_lteHelper, LteRrcConnectionEstablishmentTestCase::m_nUes, LteRrcConnectionEstablishmentTestCase::m_tConnBase, LteRrcConnectionEstablishmentTestCase::m_tConnIncrPerUe, m_ueMobility, LteRrcConnectionEstablishmentTestCase::m_useIdealRrc, ns3::MakeCallback(), max, ns3::MilliSeconds(), third::mobility, NS_LOG_FUNCTION, ns3::Config::Reset(), ns3::ObjectBase::SetAttribute(), and ns3::Config::SetDefault().
JumpAway()
void LteRrcConnectionEstablishmentErrorTestCase::JumpAway () private
Jump away function.
Definition at line 716 of file test-lte-rrc.cc.
References m_ueMobility, NS_LOG_FUNCTION, and ns3::MobilityModel::SetPosition().
Referenced by DoRun().
JumpBack()
void LteRrcConnectionEstablishmentErrorTestCase::JumpBack () private
Jump back function.
Definition at line 725 of file test-lte-rrc.cc.
References m_ueMobility, NS_LOG_FUNCTION, and ns3::MobilityModel::SetPosition().
Referenced by DoRun().
Member Data Documentation
m_jumpAwayTime
Time LteRrcConnectionEstablishmentErrorTestCase::m_jumpAwayTime private
jump away time
Definition at line 575 of file test-lte-rrc.cc.
Referenced by DoRun().
m_ueMobility
Ptr<MobilityModel> LteRrcConnectionEstablishmentErrorTestCase::m_ueMobility private
UE mobility model.
Definition at line 576 of file test-lte-rrc.cc.
Referenced by DoRun(), JumpAway(), and JumpBack().
The documentation for this class was generated from the following file:
src/lte/test/test-lte-rrc.cc