ns-3: RttEstimatorTestCase Class Reference
RttEstimatorTestCase Class Reference
Internet » internet module tests | Test suites
RTT estimator Test.
Public Member Functions
RttEstimatorTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void CheckValues (Ptr< RttEstimator > rtt, Time m, Time e, Time v)
Check RTT values.
void CheckValuesWithTolerance (Ptr< RttEstimator > rtt, Time m, Time e, Time v)
Check RTT values with a 1 nanosecond of tolerance.
virtual void DoRun (void)
Implementation to actually run this TestCase.
virtual void DoTeardown (void)
Implementation to do any local setup required for this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
RTT estimator Test.
Definition at line 36 of file rtt-test.cc.
Constructor & Destructor Documentation
RttEstimatorTestCase()
RttEstimatorTestCase::RttEstimatorTestCase ()
Definition at line 63 of file rtt-test.cc.
Member Function Documentation
CheckValues()
void RttEstimatorTestCase::CheckValues (Ptr< RttEstimator > rtt, Time m, Time e, Time v) private
Check RTT values.
Parameters
rtt The RTT estimator.
m The measurement.
e The expected value.
v The expected variance.
Definition at line 69 of file rtt-test.cc.
References ns3::RttEstimator::GetEstimate(), ns3::RttEstimator::GetVariation(), ns3::RttEstimator::Measurement(), and NS_TEST_EXPECT_MSG_EQ.
Referenced by DoRun().
CheckValuesWithTolerance()
void RttEstimatorTestCase::CheckValuesWithTolerance (Ptr< RttEstimator > rtt, Time m, Time e, Time v) private
Check RTT values with a 1 nanosecond of tolerance.
Parameters
rtt The RTT estimator.
m The measurement.
e The expected value.
v The expected variance.
Definition at line 77 of file rtt-test.cc.
References ns3::RttEstimator::GetEstimate(), ns3::RttEstimator::GetVariation(), ns3::RttEstimator::Measurement(), ns3::NanoSeconds(), and NS_TEST_EXPECT_MSG_EQ_TOL.
Referenced by DoRun().
DoRun()
void RttEstimatorTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 86 of file rtt-test.cc.
References CheckValues(), CheckValuesWithTolerance(), ns3::RttMeanDeviation::Copy(), ns3::DoubleValue::Get(), ns3::TimeValue::Get(), ns3::ObjectBase::GetAttributeFailSafe(), ns3::RttEstimator::GetEstimate(), ns3::Time::GetInteger(), ns3::RttEstimator::GetNSamples(), ns3::RttEstimator::GetVariation(), ns3::MicroSeconds(), ns3::MilliSeconds(), NS_TEST_ASSERT_MSG_EQ_TOL, NS_TEST_EXPECT_MSG_EQ, ns3::RttMeanDeviation::Reset(), ns3::Seconds(), ns3::ObjectBase::SetAttributeFailSafe(), and ns3::Config::SetDefault().
DoTeardown()
void RttEstimatorTestCase::DoTeardown (void) private virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test teardown
Reimplemented from ns3::TestCase.
Definition at line 171 of file rtt-test.cc.
The documentation for this class was generated from the following file:
src/internet/test/rtt-test.cc