ns-3: ns3::WifiSpectrumValue5MhzFactory Class Reference
ns3::WifiSpectrumValue5MhzFactory Class Reference
Spectrum Models
#include "wifi-spectrum-value-helper.h"
Public Member Functions
virtual ~WifiSpectrumValue5MhzFactory ()
Destructor.
virtual Ptr< SpectrumValue > CreateConstant (double psd)
Creates a SpectrumValue instance with a constant value for all frequencies.
virtual Ptr< SpectrumValue > CreateRfFilter (uint8_t channel)
Creates a SpectrumValue instance which represents the frequency response of the RF filter which is used by a wifi device to receive signals when tuned to a particular channel.
virtual Ptr< SpectrumValue > CreateTxPowerSpectralDensity (double txPower, uint8_t channel)
Creates a SpectrumValue instance that represents the TX Power Spectral Density of a wifi device corresponding to the provided parameters.
Detailed Description
Implements Wifi SpectrumValue for the 2.4 GHz ISM band only, with a 5 MHz spectrum resolution.
Definition at line 222 of file wifi-spectrum-value-helper.h.
Constructor & Destructor Documentation
~WifiSpectrumValue5MhzFactory()
ns3::WifiSpectrumValue5MhzFactory::~WifiSpectrumValue5MhzFactory () virtual
Destructor.
Definition at line 631 of file wifi-spectrum-value-helper.cc.
Member Function Documentation
CreateConstant()
Ptr< SpectrumValue > ns3::WifiSpectrumValue5MhzFactory::CreateConstant (double psd) virtual
Creates a SpectrumValue instance with a constant value for all frequencies.
Parameters
psd the constant value
Returns
a Ptr to a newly created SpectrumValue
Definition at line 659 of file wifi-spectrum-value-helper.cc.
References ns3::g_WifiSpectrumModel5Mhz.
Referenced by SpectrumIdealPhyTestCase::DoRun().
CreateRfFilter()
Ptr< SpectrumValue > ns3::WifiSpectrumValue5MhzFactory::CreateRfFilter (uint8_t channel) virtual
Creates a SpectrumValue instance which represents the frequency response of the RF filter which is used by a wifi device to receive signals when tuned to a particular channel.
Parameters
channel the number of the channel (1 <= channel <= 13)
Returns
a Ptr to a newly created SpectrumValue
Definition at line 702 of file wifi-spectrum-value-helper.cc.
References third::channel, ns3::g_WifiSpectrumModel5Mhz, and NS_ASSERT.
CreateTxPowerSpectralDensity()
Ptr< SpectrumValue > ns3::WifiSpectrumValue5MhzFactory::CreateTxPowerSpectralDensity (double txPower, uint8_t channel) virtual
Creates a SpectrumValue instance that represents the TX Power Spectral Density of a wifi device corresponding to the provided parameters.
Since the spectrum model has a resolution of 5 MHz, we model the transmitted signal with a constant density over a 20MHz bandwidth centered on the center frequency of the channel. The transmission power outside the transmission power density is calculated considering the transmit spectrum mask, see IEEE Std. 802.11-2007, Annex I. The two bands just outside of the main 20 MHz are allocated power at -28 dB down from the center 20 MHz, and the two bands outside of this are allocated power at -40 dB down (with a total bandwidth of 60 MHz containing non-zero power allocation).
Parameters
txPower the total TX power in W
channel the number of the channel (1 <= channel <= 13)
Returns
a Ptr to a newly created SpectrumValue
Definition at line 668 of file wifi-spectrum-value-helper.cc.
References third::channel, ns3::g_WifiSpectrumModel5Mhz, and NS_ASSERT.
Referenced by SpectrumIdealPhyTestCase::DoRun(), and ThreeGppSpectrumPropagationLossModelTest::DoRun().
The documentation for this class was generated from the following files:
src/spectrum/model/wifi-spectrum-value-helper.h
src/spectrum/model/wifi-spectrum-value-helper.cc