ns-3: ns3::EdcaParameterSet Class Reference
ns3::EdcaParameterSet Class Reference
Wifi Models
The EDCA Parameter Set.
#include "edca-parameter-set.h"
Public Member Functions
EdcaParameterSet ()
uint8_t DeserializeInformationField (Buffer::Iterator start, uint8_t length)
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
WifiInformationElementId ElementId () const
uint8_t GetBeAifsn (void) const
Return the AC_BE AIFSN field in the EdcaParameterSet information element.
uint32_t GetBeCWmax (void) const
Return the AC_BE CWmax field in the EdcaParameterSet information element.
uint32_t GetBeCWmin (void) const
Return the AC_BE CWmin field in the EdcaParameterSet information element.
uint16_t GetBeTxopLimit (void) const
Return the AC_BE TXOP Limit field in the EdcaParameterSet information element.
uint8_t GetBkAifsn (void) const
Return the AC_BK AIFSN field in the EdcaParameterSet information element.
uint32_t GetBkCWmax (void) const
Return the AC_BK CWmax field in the EdcaParameterSet information element.
uint32_t GetBkCWmin (void) const
Return the AC_BK CWmin field in the EdcaParameterSet information element.
uint16_t GetBkTxopLimit (void) const
Return the AC_BK TXOP Limit field in the EdcaParameterSet information element.
uint8_t GetInformationFieldSize () const
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
uint8_t GetQosInfo (void) const
Return the QoS Info field in the EdcaParameterSet information element.
uint16_t GetSerializedSize () const
uint8_t GetViAifsn (void) const
Return the AC_VI AIFSN field in the EdcaParameterSet information element.
uint32_t GetViCWmax (void) const
Return the AC_VI CWmax field in the EdcaParameterSet information element.
uint32_t GetViCWmin (void) const
Return the AC_VI CWmin field in the EdcaParameterSet information element.
uint16_t GetViTxopLimit (void) const
Return the AC_VI TXOP Limit field in the EdcaParameterSet information element.
uint8_t GetVoAifsn (void) const
Return the AC_VO AIFSN field in the EdcaParameterSet information element.
uint32_t GetVoCWmax (void) const
Return the AC_VO CWmax field in the EdcaParameterSet information element.
uint32_t GetVoCWmin (void) const
Return the AC_VO CWmin field in the EdcaParameterSet information element.
uint16_t GetVoTxopLimit (void) const
Return the AC_VO TXOP Limit field in the EdcaParameterSet information element.
uint8_t IsQosSupported (void) const
Is QOS supported function.
Buffer::Iterator Serialize (Buffer::Iterator start) const
void SerializeInformationField (Buffer::Iterator start) const
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
void SetBeAci (uint8_t aci)
Set the AC_BE ACI field in the EdcaParameterSet information element.
void SetBeAifsn (uint8_t aifsn)
Set the AC_BE AIFSN field in the EdcaParameterSet information element.
void SetBeCWmax (uint32_t cwMax)
Set the AC_BE CWmax field in the EdcaParameterSet information element.
void SetBeCWmin (uint32_t cwMin)
Set the AC_BE CWmin field in the EdcaParameterSet information element.
void SetBeTxopLimit (uint16_t txop)
Set the AC_BE TXOP Limit field in the EdcaParameterSet information element.
void SetBkAci (uint8_t aci)
Set the AC_BK ACI field in the EdcaParameterSet information element.
void SetBkAifsn (uint8_t aifsn)
Set the AC_BK AIFSN field in the EdcaParameterSet information element.
void SetBkCWmax (uint32_t cwMax)
Set the AC_BK CWmax field in the EdcaParameterSet information element.
void SetBkCWmin (uint32_t cwMin)
Set the AC_BK CWmin field in the EdcaParameterSet information element.
void SetBkTxopLimit (uint16_t txop)
Set the AC_BK TXOP Limit field in the EdcaParameterSet information element.
void SetQosInfo (uint8_t qosInfo)
Set the QoS Info field in the EdcaParameterSet information element.
void SetQosSupported (uint8_t qosSupported)
Set QOS supported function.
void SetViAci (uint8_t aci)
Set the AC_VI ACI field in the EdcaParameterSet information element.
void SetViAifsn (uint8_t aifsn)
Set the AC_VI AIFSN field in the EdcaParameterSet information element.
void SetViCWmax (uint32_t cwMax)
Set the AC_VI CWmax field in the EdcaParameterSet information element.
void SetViCWmin (uint32_t cwMin)
Set the AC_VI CWmin field in the EdcaParameterSet information element.
void SetViTxopLimit (uint16_t txop)
Set the AC_VI TXOP Limit field in the EdcaParameterSet information element.
void SetVoAci (uint8_t aci)
Set the AC_VO ACI field in the EdcaParameterSet information element.
void SetVoAifsn (uint8_t aifsn)
Set the AC_VO AIFSN field in the EdcaParameterSet information element.
void SetVoCWmax (uint32_t cwMax)
Set the AC_VO CWmax field in the EdcaParameterSet information element.
void SetVoCWmin (uint32_t cwMin)
Set the AC_VO CWmin field in the EdcaParameterSet information element.
void SetVoTxopLimit (uint16_t txop)
Set the AC_VO TXOP Limit field in the EdcaParameterSet information element.
Public Member Functions inherited from ns3::WifiInformationElement
virtual ~WifiInformationElement ()
Buffer::Iterator Deserialize (Buffer::Iterator i)
Deserialize entire IE, which must be present.
Buffer::Iterator DeserializeIfPresent (Buffer::Iterator i)
Deserialize entire IE if it is present.
virtual WifiInformationElementId ElementIdExt () const
uint16_t GetSerializedSize () const
Get the size of the serialized IE including Element ID and length fields.
virtual bool operator== (WifiInformationElement const &a) const
Compare two IEs for equality by ID & Length, and then through memcmp of serialised version.
virtual void Print (std::ostream &os) const
Generate human-readable form of IE.
Buffer::Iterator Serialize (Buffer::Iterator i) const
Serialize entire IE including Element ID and length fields.
Public Member Functions inherited from ns3::SimpleRefCount< WifiInformationElement >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Private Attributes
uint32_t m_acBE
AC_BE.
uint32_t m_acBK
AC_BK.
uint32_t m_acVI
AC_VI.
uint32_t m_acVO
AC_VO.
uint8_t m_qosInfo
QOS info.
bool m_qosSupported
This is used to decide whether this element should be added to the frame or not.
uint8_t m_reserved
reserved
Detailed Description
The EDCA Parameter Set.
This class knows how to serialise and deserialise the EDCA Parameter Set.
Definition at line 34 of file edca-parameter-set.h.
Constructor & Destructor Documentation
EdcaParameterSet()
ns3::EdcaParameterSet::EdcaParameterSet ()
Definition at line 26 of file edca-parameter-set.cc.
Member Function Documentation
DeserializeInformationField()
uint8_t ns3::EdcaParameterSet::DeserializeInformationField (Buffer::Iterator start, uint8_t length) virtual
Deserialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
length
Returns
the number of bytes read
Implements ns3::WifiInformationElement.
Definition at line 341 of file edca-parameter-set.cc.
References m_acBE, m_acBK, m_acVI, m_acVO, m_qosInfo, m_reserved, ns3::Buffer::Iterator::ReadU32(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
ElementId()
WifiInformationElementId ns3::EdcaParameterSet::ElementId () const virtual
Returns
Own unique Element ID
Implements ns3::WifiInformationElement.
Definition at line 38 of file edca-parameter-set.cc.
References IE_EDCA_PARAMETER_SET.
GetBeAifsn()
uint8_t ns3::EdcaParameterSet::GetBeAifsn (void) const
Return the AC_BE AIFSN field in the EdcaParameterSet information element.
Returns
the AC_BE AIFSN field in the EdcaParameterSet information element
Definition at line 196 of file edca-parameter-set.cc.
References m_acBE.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetBeCWmax()
uint32_t ns3::EdcaParameterSet::GetBeCWmax (void) const
Return the AC_BE CWmax field in the EdcaParameterSet information element.
Returns
the AC_BE CWmax field in the EdcaParameterSet information element
Definition at line 209 of file edca-parameter-set.cc.
References m_acBE.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetBeCWmin()
uint32_t ns3::EdcaParameterSet::GetBeCWmin (void) const
Return the AC_BE CWmin field in the EdcaParameterSet information element.
Returns
the AC_BE CWmin field in the EdcaParameterSet information element
Definition at line 202 of file edca-parameter-set.cc.
References m_acBE.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetBeTxopLimit()
uint16_t ns3::EdcaParameterSet::GetBeTxopLimit (void) const
Return the AC_BE TXOP Limit field in the EdcaParameterSet information element.
Returns
the AC_BE TXOP Limit field in the EdcaParameterSet information element
Definition at line 216 of file edca-parameter-set.cc.
References m_acBE.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetBkAifsn()
uint8_t ns3::EdcaParameterSet::GetBkAifsn (void) const
Return the AC_BK AIFSN field in the EdcaParameterSet information element.
Returns
the AC_BK AIFSN field in the EdcaParameterSet information element
Definition at line 222 of file edca-parameter-set.cc.
References m_acBK.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetBkCWmax()
uint32_t ns3::EdcaParameterSet::GetBkCWmax (void) const
Return the AC_BK CWmax field in the EdcaParameterSet information element.
Returns
the AC_BK CWmax field in the EdcaParameterSet information element
Definition at line 235 of file edca-parameter-set.cc.
References m_acBK.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetBkCWmin()
uint32_t ns3::EdcaParameterSet::GetBkCWmin (void) const
Return the AC_BK CWmin field in the EdcaParameterSet information element.
Returns
the AC_BK CWmin field in the EdcaParameterSet information element
Definition at line 228 of file edca-parameter-set.cc.
References m_acBK.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetBkTxopLimit()
uint16_t ns3::EdcaParameterSet::GetBkTxopLimit (void) const
Return the AC_BK TXOP Limit field in the EdcaParameterSet information element.
Returns
the AC_BK TXOP Limit field in the EdcaParameterSet information element
Definition at line 242 of file edca-parameter-set.cc.
References m_acBK.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetInformationFieldSize()
uint8_t ns3::EdcaParameterSet::GetInformationFieldSize () const virtual
Length of serialized information (i.e., the length of the body of the IE, not including the Element ID and length octets.
This is the value that will appear in the second octet of the entire IE - the length field)
Returns
the length of serialized information
Implements ns3::WifiInformationElement.
Definition at line 300 of file edca-parameter-set.cc.
References m_qosSupported, and NS_ASSERT.
GetQosInfo()
uint8_t ns3::EdcaParameterSet::GetQosInfo (void) const
Return the QoS Info field in the EdcaParameterSet information element.
Returns
the QoS Info field in the EdcaParameterSet information element
Definition at line 190 of file edca-parameter-set.cc.
References m_qosInfo.
Referenced by SerializeInformationField().
GetSerializedSize()
uint16_t ns3::EdcaParameterSet::GetSerializedSize () const
Definition at line 317 of file edca-parameter-set.cc.
References ns3::WifiInformationElement::GetSerializedSize(), and m_qosSupported.
Referenced by ns3::MgtAssocResponseHeader::GetSerializedSize(), and ns3::MgtProbeResponseHeader::GetSerializedSize().
GetViAifsn()
uint8_t ns3::EdcaParameterSet::GetViAifsn (void) const
Return the AC_VI AIFSN field in the EdcaParameterSet information element.
Returns
the AC_VI AIFSN field in the EdcaParameterSet information element
Definition at line 248 of file edca-parameter-set.cc.
References m_acVI.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetViCWmax()
uint32_t ns3::EdcaParameterSet::GetViCWmax (void) const
Return the AC_VI CWmax field in the EdcaParameterSet information element.
Returns
the AC_VI CWmax field in the EdcaParameterSet information element
Definition at line 261 of file edca-parameter-set.cc.
References m_acVI.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetViCWmin()
uint32_t ns3::EdcaParameterSet::GetViCWmin (void) const
Return the AC_VI CWmin field in the EdcaParameterSet information element.
Returns
the AC_VI CWmin field in the EdcaParameterSet information element
Definition at line 254 of file edca-parameter-set.cc.
References m_acVI.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetViTxopLimit()
uint16_t ns3::EdcaParameterSet::GetViTxopLimit (void) const
Return the AC_VI TXOP Limit field in the EdcaParameterSet information element.
Returns
the AC_VI TXOP Limit field in the EdcaParameterSet information element
Definition at line 268 of file edca-parameter-set.cc.
References m_acVI.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetVoAifsn()
uint8_t ns3::EdcaParameterSet::GetVoAifsn (void) const
Return the AC_VO AIFSN field in the EdcaParameterSet information element.
Returns
the AC_VO AIFSN field in the EdcaParameterSet information element
Definition at line 274 of file edca-parameter-set.cc.
References m_acVO.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetVoCWmax()
uint32_t ns3::EdcaParameterSet::GetVoCWmax (void) const
Return the AC_VO CWmax field in the EdcaParameterSet information element.
Returns
the AC_VO CWmax field in the EdcaParameterSet information element
Definition at line 287 of file edca-parameter-set.cc.
References m_acVO.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetVoCWmin()
uint32_t ns3::EdcaParameterSet::GetVoCWmin (void) const
Return the AC_VO CWmin field in the EdcaParameterSet information element.
Returns
the AC_VO CWmin field in the EdcaParameterSet information element
Definition at line 280 of file edca-parameter-set.cc.
References m_acVO.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
GetVoTxopLimit()
uint16_t ns3::EdcaParameterSet::GetVoTxopLimit (void) const
Return the AC_VO TXOP Limit field in the EdcaParameterSet information element.
Returns
the AC_VO TXOP Limit field in the EdcaParameterSet information element
Definition at line 294 of file edca-parameter-set.cc.
References m_acVO.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
IsQosSupported()
uint8_t ns3::EdcaParameterSet::IsQosSupported (void) const
Is QOS supported function.
Returns
the is QOS supported indicator
Definition at line 50 of file edca-parameter-set.cc.
References m_acBE, m_acBK, m_acVI, and m_acVO.
Referenced by ns3::StaWifiMac::UpdateApInfoFromAssocResp(), and ns3::StaWifiMac::UpdateApInfoFromBeacon().
Serialize()
Buffer::Iterator ns3::EdcaParameterSet::Serialize (Buffer::Iterator start) const
Definition at line 307 of file edca-parameter-set.cc.
References m_qosSupported, and ns3::WifiInformationElement::Serialize().
Referenced by ns3::MgtAssocResponseHeader::Serialize(), and ns3::MgtProbeResponseHeader::Serialize().
SerializeInformationField()
void ns3::EdcaParameterSet::SerializeInformationField (Buffer::Iterator start) const virtual
Serialize information (i.e., the body of the IE, not including the Element ID and length octets)
Parameters
start an iterator which points to where the information should be written.
Implements ns3::WifiInformationElement.
Definition at line 327 of file edca-parameter-set.cc.
References GetQosInfo(), m_acBE, m_acBK, m_acVI, m_acVO, m_qosSupported, m_reserved, and visualizer.core::start().
SetBeAci()
void ns3::EdcaParameterSet::SetBeAci (uint8_t aci)
Set the AC_BE ACI field in the EdcaParameterSet information element.
Parameters
aci the AC_BE ACI field in the EdcaParameterSet information element
Definition at line 68 of file edca-parameter-set.cc.
References m_acBE.
Referenced by ns3::ApWifiMac::GetEdcaParameterSet().
SetBeAifsn()
void ns3::EdcaParameterSet::SetBeAifsn (uint8_t aifsn)
Set the AC_BE AIFSN field in the EdcaParameterSet information element.
Parameters
aifsn the AC_BE AIFSN field in the EdcaParameterSet information element
Definition at line 62 of file edca-parameter-set.cc.
References m_acBE.
Referenced by ns3::ApWifiMac::GetEdcaParameterSet().
SetBeCWmax()
void ns3::EdcaParameterSet::SetBeCWmax (uint32_t cwMax)
Set the AC_BE CWmax field in the EdcaParameterSet information element.
Parameters
cwMax the AC_BE CWmax field in the EdcaParameterSet information element
Definition at line 81 of file edca-parameter-set.cc.
References m_acBE.
Referenced by ns3::ApWifiMac::GetEdcaParameterSet().
SetBeCWmin()
void ns3::EdcaParameterSet::SetBeCWmin (uint32_t cwMin)
Set the AC_BE CWmin field in the EdcaParameterSet information element.
Parameters
cwMin the AC_BE CWmin field in the EdcaParameterSet information element
Definition at line 74 of file edca-parameter-set.cc.
References m_acBE.
Referenced by ns3::ApWifiMac::GetEdcaParameterSet().
SetBeTxopLimit()
void ns3::EdcaParameterSet::SetBeTxopLimit (uint16_t txop)
Set the AC_BE TXOP Limit field in the EdcaParameterSet information element.
Parameters
txop the AC_BE TXOP Limit field in the EdcaParameterSet information element
Definition at line 88 of file edca-parameter-set.cc.
References m_acBE.
Referenced by ns3::ApWifiMac::GetEdcaParameterSet().
SetBkAci()
void ns3::EdcaParameterSet::SetBkAci (uint8_t aci)
Set the AC_BK ACI field in the EdcaParameterSet information element.
Parameters
aci the AC_BK ACI field in the EdcaParameterSet information element
Definition at line 100 of file edca-parameter-set.cc.
References m_acBK.
Referenced by ns3::ApWifiMac::GetEdcaParameterSet().
SetBkAifsn()
void ns3::EdcaParameterSet::SetBkAifsn (uint8_t aifsn)
Set the AC_BK AIFSN field in the EdcaParameterSet information element.
Parameters
aifsn the AC_BB AIFSN field in the EdcaParameterSet information element
Definition at line 94 of file edca-parameter-set.cc.
References m_acBK.
Referenced by ns3::ApWifiMac::GetEdcaParameterSet().
SetBkCWmax()
void ns3::EdcaParameterSet::SetBkCWmax (uint32_t cwMax)
Set the AC_BK CWmax field in the EdcaParameterSet information element.
Parameters
cwMax the AC_BK CWmax field in the EdcaParameterSet information element
Definition at line 113 of file edca-parameter-set.cc.
References m_acBK.
Referenced by ns3::ApWifiMac::GetEdcaParameterSet().
SetBkCWmin()
void ns3::EdcaParameterSet::SetBkCWmin (uint32_t cwMin)
Set the AC_BK CWmin field in the EdcaParameterSet information element.
Parameters
cwMin the AC_BK CWmin field in the EdcaParameterSet information element
Definition at line 106 of file edca-parameter-set.cc.
References m_acBK.
Referenced by ns3::ApWifiMac::GetEdcaParameterSet().
SetBkTxopLimit()
void ns3::EdcaParameterSet::SetBkTxopLimit (uint16_t txop)
Set the AC_BK TXOP Limit field in the EdcaParameterSet information element.
Parameters
txop the AC_BK TXOP Limit field in the EdcaParameterSet information element
Definition at line 120 of file edca-parameter-set.cc.
References m_acBK.
Referenced by ns3::ApWifiMac::GetEdcaParameterSet().
SetQosInfo()
void ns3::EdcaParameterSet::SetQosInfo (uint8_t qosInfo)
Set the QoS Info field in the EdcaParameterSet information element.
Parameters
qosInfo the QoS Info field in the EdcaParameterSet information element
Definition at line 56 of file edca-parameter-set.cc.
References m_qosInfo.
Referenced by ns3::ApWifiMac::GetEdcaParameterSet().
SetQosSupported()
void ns3::EdcaParameterSet::SetQosSupported (uint8_t qosSupported)
Set QOS supported function.
Parameters
qosSupported the QOS supported indicator
Definition at line 44 of file edca-parameter-set.cc.
References m_qosSupported.
Referenced by ns3::ApWifiMac::GetEdcaParameterSet().
SetViAci()
void ns3::EdcaParameterSet::SetViAci (uint8_t aci)
Set the AC_VI ACI field in the EdcaParameterSet information element.
Parameters
aci the AC_VI ACI field in the EdcaParameterSet information element
Definition at line 132 of file edca-parameter-set.cc.
References m_acVI.
Referenced by ns3::ApWifiMac::GetEdcaParameterSet().
SetViAifsn()
void ns3::EdcaParameterSet::SetViAifsn (uint8_t aifsn)
Set the AC_VI AIFSN field in the EdcaParameterSet information element.
Parameters
aifsn the AC_VI AIFSN field in the EdcaParameterSet information element
Definition at line 126 of file edca-parameter-set.cc.
References m_acVI.
Referenced by ns3::ApWifiMac::GetEdcaParameterSet().
SetViCWmax()
void ns3::EdcaParameterSet::SetViCWmax (uint32_t cwMax)
Set the AC_VI CWmax field in the EdcaParameterSet information element.
Parameters
cwMax the AC_VI CWmax field in the EdcaParameterSet information element
Definition at line 145 of file edca-parameter-set.cc.
References m_acVI.
Referenced by ns3::ApWifiMac::GetEdcaParameterSet().
SetViCWmin()
void ns3::EdcaParameterSet::SetViCWmin (uint32_t cwMin)
Set the AC_VI CWmin field in the EdcaParameterSet information element.
Parameters
cwMin the AC_VI CWmin field in the EdcaParameterSet information element
Definition at line 138 of file edca-parameter-set.cc.
References m_acVI.
Referenced by ns3::ApWifiMac::GetEdcaParameterSet().
SetViTxopLimit()
void ns3::EdcaParameterSet::SetViTxopLimit (uint16_t txop)
Set the AC_VI TXOP Limit field in the EdcaParameterSet information element.
Parameters
txop the AC_VI TXOP Limit field in the EdcaParameterSet information element
Definition at line 152 of file edca-parameter-set.cc.
References m_acVI.
Referenced by ns3::ApWifiMac::GetEdcaParameterSet().
SetVoAci()
void ns3::EdcaParameterSet::SetVoAci (uint8_t aci)
Set the AC_VO ACI field in the EdcaParameterSet information element.
Parameters
aci the AC_VO ACI field in the EdcaParameterSet information element
Definition at line 164 of file edca-parameter-set.cc.
References m_acVO.
Referenced by ns3::ApWifiMac::GetEdcaParameterSet().
SetVoAifsn()
void ns3::EdcaParameterSet::SetVoAifsn (uint8_t aifsn)
Set the AC_VO AIFSN field in the EdcaParameterSet information element.
Parameters
aifsn the AC_VO AIFSN field in the EdcaParameterSet information element
Definition at line 158 of file edca-parameter-set.cc.
References m_acVO.
Referenced by ns3::ApWifiMac::GetEdcaParameterSet().
SetVoCWmax()
void ns3::EdcaParameterSet::SetVoCWmax (uint32_t cwMax)
Set the AC_VO CWmax field in the EdcaParameterSet information element.
Parameters
cwMax the AC_VO CWmax field in the EdcaParameterSet information element
Definition at line 177 of file edca-parameter-set.cc.
References m_acVO.
Referenced by ns3::ApWifiMac::GetEdcaParameterSet().
SetVoCWmin()
void ns3::EdcaParameterSet::SetVoCWmin (uint32_t cwMin)
Set the AC_VO CWmin field in the EdcaParameterSet information element.
Parameters
cwMin the AC_VO CWmin field in the EdcaParameterSet information element
Definition at line 170 of file edca-parameter-set.cc.
References m_acVO.
Referenced by ns3::ApWifiMac::GetEdcaParameterSet().
SetVoTxopLimit()
void ns3::EdcaParameterSet::SetVoTxopLimit (uint16_t txop)
Set the AC_VO TXOP Limit field in the EdcaParameterSet information element.
Parameters
txop the AC_VO TXOP Limit field in the EdcaParameterSet information element
Definition at line 184 of file edca-parameter-set.cc.
References m_acVO.
Referenced by ns3::ApWifiMac::GetEdcaParameterSet().
Member Data Documentation
m_acBE
uint32_t ns3::EdcaParameterSet::m_acBE private
AC_BE.
Definition at line 296 of file edca-parameter-set.h.
Referenced by DeserializeInformationField(), GetBeAifsn(), GetBeCWmax(), GetBeCWmin(), GetBeTxopLimit(), IsQosSupported(), SerializeInformationField(), SetBeAci(), SetBeAifsn(), SetBeCWmax(), SetBeCWmin(), and SetBeTxopLimit().
m_acBK
uint32_t ns3::EdcaParameterSet::m_acBK private
AC_BK.
Definition at line 297 of file edca-parameter-set.h.
Referenced by DeserializeInformationField(), GetBkAifsn(), GetBkCWmax(), GetBkCWmin(), GetBkTxopLimit(), IsQosSupported(), SerializeInformationField(), SetBkAci(), SetBkAifsn(), SetBkCWmax(), SetBkCWmin(), and SetBkTxopLimit().
m_acVI
uint32_t ns3::EdcaParameterSet::m_acVI private
AC_VI.
Definition at line 298 of file edca-parameter-set.h.
Referenced by DeserializeInformationField(), GetViAifsn(), GetViCWmax(), GetViCWmin(), GetViTxopLimit(), IsQosSupported(), SerializeInformationField(), SetViAci(), SetViAifsn(), SetViCWmax(), SetViCWmin(), and SetViTxopLimit().
m_acVO
uint32_t ns3::EdcaParameterSet::m_acVO private
AC_VO.
Definition at line 299 of file edca-parameter-set.h.
Referenced by DeserializeInformationField(), GetVoAifsn(), GetVoCWmax(), GetVoCWmin(), GetVoTxopLimit(), IsQosSupported(), SerializeInformationField(), SetVoAci(), SetVoAifsn(), SetVoCWmax(), SetVoCWmin(), and SetVoTxopLimit().
m_qosInfo
uint8_t ns3::EdcaParameterSet::m_qosInfo private
QOS info.
Definition at line 294 of file edca-parameter-set.h.
Referenced by DeserializeInformationField(), GetQosInfo(), and SetQosInfo().
m_qosSupported
bool ns3::EdcaParameterSet::m_qosSupported private
This is used to decide whether this element should be added to the frame or not.
Definition at line 302 of file edca-parameter-set.h.
Referenced by GetInformationFieldSize(), GetSerializedSize(), Serialize(), SerializeInformationField(), and SetQosSupported().
m_reserved
uint8_t ns3::EdcaParameterSet::m_reserved private
reserved
Definition at line 295 of file edca-parameter-set.h.
Referenced by DeserializeInformationField(), and SerializeInformationField().
The documentation for this class was generated from the following files:
src/wifi/model/edca-parameter-set.h
src/wifi/model/edca-parameter-set.cc