ns-3: PacketMetadataTest Class Reference
PacketMetadataTest Class Reference
Network » Network module unit tests | Test suites
Public Member Functions
PacketMetadataTest ()
virtual ~PacketMetadataTest ()
void CheckHistory (Ptr< Packet > p, const char *file, int line, uint32_t n,...)
Checks the packet header and trailer history.
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
Ptr< Packet > DoAddHeader (Ptr< Packet > p)
Adds an header to the packet.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Packet Metadata unit tests.
Definition at line 319 of file packet-metadata-test.cc.
Constructor & Destructor Documentation
PacketMetadataTest()
PacketMetadataTest::PacketMetadataTest ()
Definition at line 342 of file packet-metadata-test.cc.
~PacketMetadataTest()
PacketMetadataTest::~PacketMetadataTest () virtual
Definition at line 347 of file packet-metadata-test.cc.
Member Function Documentation
CheckHistory()
void PacketMetadataTest::CheckHistory (Ptr< Packet > p, const char * file, int line, uint32_t n, ...)
Checks the packet header and trailer history.
Parameters
p The packet
file The file name
line The line number
n The number of variable arguments
... The variable arguments
Definition at line 352 of file packet-metadata-test.cc.
References ns3::Packet::BeginItem(), ns3::PacketMetadata::Item::current, ns3::PacketMetadata::Item::currentSize, anonymous_namespace{print-introspected-doxygen.cc}::file, ns3::TypeId::GetConstructor(), ns3::PacketMetadata::ItemIterator::HasNext(), ns3::PacketMetadata::Item::isFragment, sample-rng-plot::n, ns3::PacketMetadata::ItemIterator::Next(), NS_ASSERT, NS_TEST_ASSERT_MSG_EQ_INTERNAL, ns3::PacketMetadata::Item::tid, and ns3::PacketMetadata::Item::type.
DoAddHeader()
Ptr< Packet > PacketMetadataTest::DoAddHeader (Ptr< Packet > p) private
Adds an header to the packet.
Parameters
p The packet
Returns
The packet with the header added.
Definition at line 471 of file packet-metadata-test.cc.
References ADD_HEADER.
Referenced by DoRun().
DoRun()
void PacketMetadataTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Internal:
See Bug 179
Internal:
See Bug 1072
Internal:
See Bug 1072
Implements ns3::TestCase.
Definition at line 478 of file packet-metadata-test.cc.
References ADD_HEADER, ADD_TRAILER, ns3::Packet::AddAtEnd(), CHECK_HISTORY, ns3::Packet::Copy(), ns3::Packet::CopyData(), ns3::Packet::CreateFragment(), DoAddHeader(), ns3::Packet::GetSize(), NS_TEST_EXPECT_MSG_EQ, REM_HEADER, REM_TRAILER, ns3::Packet::RemoveAtEnd(), and ns3::Packet::RemoveAtStart().
The documentation for this class was generated from the following file:
src/network/test/packet-metadata-test.cc