ns-3: StaWifiMacScanningTestCase Class Reference
StaWifiMacScanningTestCase Class Reference
Make sure that Wifi STA is correctly associating to the best AP (i.e., nearest from STA).
Public Member Functions
StaWifiMacScanningTestCase ()
virtual ~StaWifiMacScanningTestCase ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void AssocCallback (std::string context, Mac48Address bssid)
Callback function on STA assoc event.
NodeContainer Setup (bool nearestApBeaconGeneration, bool staActiveProbe)
Setup test.
void TurnApOff (Ptr< Node > apNode)
Turn the AP node off.
void TurnBeaconGenerationOn (Ptr< Node > apNode)
Turn beacon generation on the AP node.
Private Attributes
Mac48Address m_associatedApBssid
Associated AP's bssid.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Make sure that Wifi STA is correctly associating to the best AP (i.e., nearest from STA).
We consider 3 AP and 1 STA. This test case consisted of three sub tests:
The best AP sends its beacon later than the other APs. STA is expected to associate to the best AP.
The STA is using active scanning instead of passive, the rest of the APs works normally. STA is expected to associate to the best AP
The nearest AP is turned off after sending beacon and while STA is still scanning. STA is expected to associate to the second best AP.
See Bug 2399
Todo:
Add explicit association refusal test if ns-3 implemented it.
Definition at line 1705 of file wifi-test.cc.
Constructor & Destructor Documentation
StaWifiMacScanningTestCase()
StaWifiMacScanningTestCase::StaWifiMacScanningTestCase ()
Definition at line 1740 of file wifi-test.cc.
~StaWifiMacScanningTestCase()
StaWifiMacScanningTestCase::~StaWifiMacScanningTestCase () virtual
Definition at line 1745 of file wifi-test.cc.
Member Function Documentation
AssocCallback()
void StaWifiMacScanningTestCase::AssocCallback (std::string context, Mac48Address bssid) private
Callback function on STA assoc event.
Parameters
context context string
bssid the associated AP's bssid
Definition at line 1750 of file wifi-test.cc.
References m_associatedApBssid.
Referenced by Setup().
DoRun()
void StaWifiMacScanningTestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 1822 of file wifi-test.cc.
References ns3::Node::GetDevice(), m_associatedApBssid, first::nodes, NS_TEST_ASSERT_MSG_EQ, ns3::Seconds(), Setup(), TurnApOff(), and TurnBeaconGenerationOn().
Setup()
NodeContainer StaWifiMacScanningTestCase::Setup (bool nearestApBeaconGeneration, bool staActiveProbe) private
Setup test.
Parameters
nearestApBeaconGeneration set BeaconGeneration attribute of the nearest AP
staActiveProbe set ActiveProbing attribute of the STA
Returns
node container containing all nodes
Definition at line 1772 of file wifi-test.cc.
References ns3::ListPositionAllocator::Add(), AssocCallback(), third::channel, ns3::Config::Connect(), ns3::NodeContainer::Create(), third::mac, ns3::MakeCallback(), third::mobility, third::phy, third::wifi, and ns3::WIFI_PHY_STANDARD_80211n_2_4GHZ.
Referenced by DoRun().
TurnApOff()
void StaWifiMacScanningTestCase::TurnApOff (Ptr< Node > apNode) private
Turn the AP node off.
Parameters
apNode the AP node
Definition at line 1764 of file wifi-test.cc.
References ns3::Node::GetDevice(), ns3::WifiNetDevice::GetPhy(), and third::phy.
Referenced by DoRun().
TurnBeaconGenerationOn()
void StaWifiMacScanningTestCase::TurnBeaconGenerationOn (Ptr< Node > apNode) private
Turn beacon generation on the AP node.
Parameters
apNode the AP node
Definition at line 1756 of file wifi-test.cc.
References ns3::Node::GetDevice(), ns3::WifiNetDevice::GetMac(), and third::mac.
Referenced by DoRun().
Member Data Documentation
m_associatedApBssid
Mac48Address StaWifiMacScanningTestCase::m_associatedApBssid private
Associated AP's bssid.
Definition at line 1737 of file wifi-test.cc.
Referenced by AssocCallback(), and DoRun().
The documentation for this class was generated from the following file:
src/wifi/test/wifi-test.cc