ns-3: Ipv4StaticRoutingSlash32TestCase Class Reference
Ipv4StaticRoutingSlash32TestCase Class Reference
Internet » internet module tests | Test suites
IPv4 StaticRouting /32 Test.
Public Member Functions
Ipv4StaticRoutingSlash32TestCase ()
virtual ~Ipv4StaticRoutingSlash32TestCase ()
void DoSendData (Ptr< Socket > socket, std::string to)
Send data.
void ReceivePkt (Ptr< Socket > socket)
Receive data.
void SendData (Ptr< Socket > socket, std::string to)
Send data.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Public Attributes
Ptr< Packet > m_receivedPacket
Received packet.
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
IPv4 StaticRouting /32 Test.
Definition at line 47 of file ipv4-static-routing-test-suite.cc.
Constructor & Destructor Documentation
Ipv4StaticRoutingSlash32TestCase()
Ipv4StaticRoutingSlash32TestCase::Ipv4StaticRoutingSlash32TestCase ()
Definition at line 79 of file ipv4-static-routing-test-suite.cc.
~Ipv4StaticRoutingSlash32TestCase()
Ipv4StaticRoutingSlash32TestCase::~Ipv4StaticRoutingSlash32TestCase () virtual
Definition at line 84 of file ipv4-static-routing-test-suite.cc.
Member Function Documentation
DoRun()
void Ipv4StaticRoutingSlash32TestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 123 of file ipv4-static-routing-test-suite.cc.
References ns3::Ipv4::AddAddress(), ns3::Node::AddDevice(), ns3::Ipv4StaticRouting::AddHostRouteTo(), ns3::Ipv4::AddInterface(), ns3::Ipv4AddressHelper::Assign(), ns3::SocketFactory::CreateSocket(), ns3::Object::GetObject(), ns3::Packet::GetSize(), ns3::Ipv4StaticRoutingHelper::GetStaticRouting(), ns3::SimpleNetDeviceHelper::Install(), ns3::InternetStackHelper::Install(), m_receivedPacket, ns3::MakeCallback(), NS_TEST_EXPECT_MSG_EQ, ReceivePkt(), SendData(), ns3::SimpleNetDevice::SetAddress(), ns3::Socket::SetAllowBroadcast(), ns3::Ipv4AddressHelper::SetBase(), ns3::Ipv4::SetMetric(), and ns3::Ipv4::SetUp().
DoSendData()
void Ipv4StaticRoutingSlash32TestCase::DoSendData (Ptr< Socket > socket, std::string to)
Send data.
Parameters
socket The sending socket.
to Destination address.
Definition at line 101 of file ipv4-static-routing-test-suite.cc.
References NS_TEST_EXPECT_MSG_EQ, and ns3::Socket::SendTo().
Referenced by SendData().
ReceivePkt()
void Ipv4StaticRoutingSlash32TestCase::ReceivePkt (Ptr< Socket > socket)
Receive data.
Parameters
socket The receiving socket.
Definition at line 89 of file ipv4-static-routing-test-suite.cc.
References ns3::Socket::GetRxAvailable(), ns3::Packet::GetSize(), m_receivedPacket, max, NS_ASSERT, and ns3::Socket::Recv().
Referenced by DoRun().
SendData()
void Ipv4StaticRoutingSlash32TestCase::SendData (Ptr< Socket > socket, std::string to)
Send data.
Parameters
socket The sending socket.
to Destination address.
Definition at line 109 of file ipv4-static-routing-test-suite.cc.
References DoSendData(), ns3::Node::GetId(), ns3::Socket::GetNode(), m_receivedPacket, and ns3::Seconds().
Referenced by DoRun().
Member Data Documentation
m_receivedPacket
Ptr<Packet> Ipv4StaticRoutingSlash32TestCase::m_receivedPacket
Received packet.
Definition at line 53 of file ipv4-static-routing-test-suite.cc.
Referenced by DoRun(), ReceivePkt(), and SendData().
The documentation for this class was generated from the following file:
src/internet/test/ipv4-static-routing-test-suite.cc