ns-3: ns3::tests::HashTestCase Class Reference
ns3::tests::HashTestCase Class Reference
Test suites | Core » Core module tests | Core » Hash Functions » Hash test suite
Public Member Functions
HashTestCase (const std::string name)
Constructor.
virtual ~HashTestCase ()
Destructor.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Member Functions
void Check (const std::string hashName, const uint32_t hash)
Check function.
void Check (const std::string hashName, const uint64_t hash)
Check function.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Protected Attributes
uint32_t hash32Reference
The 32-bit hash of the reference.
uint64_t hash64Reference
The 64-bit hash of the reference.
std::string key
The reference value to hash.
Private Member Functions
void Check (const std::string hashName, const int bits, const uint64_t hash)
Check function.
virtual void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Detailed Description
Base class for hash tests
Definition at line 50 of file hash-test-suite.cc.
Constructor & Destructor Documentation
HashTestCase()
ns3::tests::HashTestCase::HashTestCase (const std::string name)
Constructor.
Parameters
[in] name reference name
Definition at line 92 of file hash-test-suite.cc.
~HashTestCase()
ns3::tests::HashTestCase::~HashTestCase () virtual
Destructor.
Definition at line 97 of file hash-test-suite.cc.
Member Function Documentation
Check() [1/3]
void ns3::tests::HashTestCase::Check (const std::string hashName, const int bits, const uint64_t hash) private
Check function.
Parameters
[in] hashName the name of the hash
[in] bits the number of bits
[in] hash the hash value
Definition at line 113 of file hash-test-suite.cc.
References ns3::TestCase::GetName(), hash32Reference, hash64Reference, and NS_TEST_EXPECT_MSG_EQ.
Check() [2/3]
void ns3::tests::HashTestCase::Check (const std::string hashName, const uint32_t hash) protected
Check function.
Parameters
[in] hashName the name of the hash
[in] hash the hash value
Definition at line 101 of file hash-test-suite.cc.
Referenced by Check(), ns3::tests::IncrementalTestCase::DoHash(), ns3::tests::DefaultHashTestCase::DoRun(), ns3::tests::Fnv1aTestCase::DoRun(), ns3::tests::Murmur3TestCase::DoRun(), ns3::tests::Hash32FunctionPtrTestCase::DoRun(), and ns3::tests::Hash64FunctionPtrTestCase::DoRun().
Check() [3/3]
void ns3::tests::HashTestCase::Check (const std::string hashName, const uint64_t hash) protected
Check function.
Parameters
[in] hashName the name of the hash
[in] hash the hash value
Definition at line 107 of file hash-test-suite.cc.
References Check().
DoRun()
void ns3::tests::HashTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Reimplemented in ns3::tests::IncrementalTestCase, ns3::tests::Hash64FunctionPtrTestCase, ns3::tests::Hash32FunctionPtrTestCase, ns3::tests::Murmur3TestCase, ns3::tests::Fnv1aTestCase, and ns3::tests::DefaultHashTestCase.
Definition at line 146 of file hash-test-suite.cc.
Member Data Documentation
hash32Reference
uint32_t ns3::tests::HashTestCase::hash32Reference protected
The 32-bit hash of the reference.
Definition at line 77 of file hash-test-suite.cc.
Referenced by Check(), ns3::tests::IncrementalTestCase::DoHash(), ns3::tests::DefaultHashTestCase::DoRun(), ns3::tests::Fnv1aTestCase::DoRun(), ns3::tests::Murmur3TestCase::DoRun(), and ns3::tests::Hash32FunctionPtrTestCase::DoRun().
hash64Reference
uint64_t ns3::tests::HashTestCase::hash64Reference protected
The 64-bit hash of the reference.
Definition at line 78 of file hash-test-suite.cc.
Referenced by Check(), ns3::tests::IncrementalTestCase::DoHash(), ns3::tests::DefaultHashTestCase::DoRun(), ns3::tests::Fnv1aTestCase::DoRun(), ns3::tests::Murmur3TestCase::DoRun(), and ns3::tests::Hash64FunctionPtrTestCase::DoRun().
key
std::string ns3::tests::HashTestCase::key protected
The reference value to hash.
Definition at line 76 of file hash-test-suite.cc.
Referenced by ns3::tests::DefaultHashTestCase::DoRun(), ns3::tests::Fnv1aTestCase::DoRun(), ns3::tests::Murmur3TestCase::DoRun(), ns3::tests::Hash32FunctionPtrTestCase::DoRun(), and ns3::tests::Hash64FunctionPtrTestCase::DoRun().
The documentation for this class was generated from the following file:
src/core/test/hash-test-suite.cc