ns-3: ns3::lorawan::LoraRadioEnergyModelPhyListener Class Reference
ns3::lorawan::LoraRadioEnergyModelPhyListener Class Reference
Energy Models
#include "lora-radio-energy-model.h"
Public Types
typedef Callback< void, double > UpdateTxCurrentCallback
Callback type for updating the transmit current based on the nominal tx power.
Public Member Functions
LoraRadioEnergyModelPhyListener ()
virtual ~LoraRadioEnergyModelPhyListener ()
void NotifyRxStart (void)
Switches the LoraRadioEnergyModel to RX state.
void NotifySleep (void)
Defined in ns3::LoraEndDevicePhyListener.
void NotifyStandby (void)
Defined in ns3::LoraEndDevicePhyListener.
void NotifyTxStart (double txPowerDbm)
Switches the LoraRadioEnergyModel to TX state and switches back to STANDBY after TX duration.
void SetChangeStateCallback (DeviceEnergyModel::ChangeStateCallback callback)
Sets the change state callback.
void SetUpdateTxCurrentCallback (UpdateTxCurrentCallback callback)
Sets the update tx current callback.
Public Member Functions inherited from ns3::lorawan::EndDeviceLoraPhyListener
virtual ~EndDeviceLoraPhyListener ()
Private Member Functions
void SwitchToStandby (void)
A helper function that makes scheduling m_changeStateCallback possible.
Private Attributes
DeviceEnergyModel::ChangeStateCallback m_changeStateCallback
Change state callback used to notify the LoraRadioEnergyModel of a state change.
UpdateTxCurrentCallback m_updateTxCurrentCallback
Callback used to update the tx current stored in LoraRadioEnergyModel based on the nominal tx power used to transmit the current frame.
Detailed Description
Definition at line 31 of file lora-radio-energy-model.h.
Member Typedef Documentation
UpdateTxCurrentCallback
typedef Callback<void, double> ns3::lorawan::LoraRadioEnergyModelPhyListener::UpdateTxCurrentCallback
Callback type for updating the transmit current based on the nominal tx power.
Definition at line 37 of file lora-radio-energy-model.h.
Constructor & Destructor Documentation
LoraRadioEnergyModelPhyListener()
ns3::lorawan::LoraRadioEnergyModelPhyListener::LoraRadioEnergyModelPhyListener ()
Definition at line 371 of file lora-radio-energy-model.cc.
References m_changeStateCallback, m_updateTxCurrentCallback, NS_LOG_FUNCTION, and ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::Nullify().
~LoraRadioEnergyModelPhyListener()
ns3::lorawan::LoraRadioEnergyModelPhyListener::~LoraRadioEnergyModelPhyListener () virtual
Definition at line 378 of file lora-radio-energy-model.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
NotifyRxStart()
void ns3::lorawan::LoraRadioEnergyModelPhyListener::NotifyRxStart (void) virtual
Switches the LoraRadioEnergyModel to RX state.
Parameters
duration the expected duration of the packet reception.
Defined in ns3::LoraEndDevicePhyListener
Implements ns3::lorawan::EndDeviceLoraPhyListener.
Definition at line 400 of file lora-radio-energy-model.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_changeStateCallback, NS_FATAL_ERROR, NS_LOG_FUNCTION, and ns3::lorawan::EndDeviceLoraPhy::RX.
NotifySleep()
void ns3::lorawan::LoraRadioEnergyModelPhyListener::NotifySleep (void) virtual
Defined in ns3::LoraEndDevicePhyListener.
Implements ns3::lorawan::EndDeviceLoraPhyListener.
Definition at line 427 of file lora-radio-energy-model.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_changeStateCallback, NS_FATAL_ERROR, NS_LOG_FUNCTION, and ns3::lorawan::EndDeviceLoraPhy::SLEEP.
NotifyStandby()
void ns3::lorawan::LoraRadioEnergyModelPhyListener::NotifyStandby (void) virtual
Defined in ns3::LoraEndDevicePhyListener.
Implements ns3::lorawan::EndDeviceLoraPhyListener.
Definition at line 438 of file lora-radio-energy-model.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_changeStateCallback, NS_FATAL_ERROR, NS_LOG_FUNCTION, and ns3::lorawan::EndDeviceLoraPhy::STANDBY.
NotifyTxStart()
void ns3::lorawan::LoraRadioEnergyModelPhyListener::NotifyTxStart (double txPowerDbm) virtual
Switches the LoraRadioEnergyModel to TX state and switches back to STANDBY after TX duration.
Parameters
duration the expected transmission duration.
txPowerDbm the nominal tx power in dBm
Defined in ns3::LoraEndDevicePhyListener
Implements ns3::lorawan::EndDeviceLoraPhyListener.
Definition at line 411 of file lora-radio-energy-model.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_changeStateCallback, m_updateTxCurrentCallback, NS_FATAL_ERROR, NS_LOG_FUNCTION, and ns3::lorawan::EndDeviceLoraPhy::TX.
SetChangeStateCallback()
void ns3::lorawan::LoraRadioEnergyModelPhyListener::SetChangeStateCallback (DeviceEnergyModel::ChangeStateCallback callback)
Sets the change state callback.
Used by helper class.
Parameters
callback Change state callback.
Definition at line 384 of file lora-radio-energy-model.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_changeStateCallback, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::lorawan::LoraRadioEnergyModel::LoraRadioEnergyModel().
SetUpdateTxCurrentCallback()
void ns3::lorawan::LoraRadioEnergyModelPhyListener::SetUpdateTxCurrentCallback (UpdateTxCurrentCallback callback)
Sets the update tx current callback.
Parameters
callback Update tx current callback.
Definition at line 392 of file lora-radio-energy-model.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_updateTxCurrentCallback, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by ns3::lorawan::LoraRadioEnergyModel::LoraRadioEnergyModel().
SwitchToStandby()
void ns3::lorawan::LoraRadioEnergyModelPhyListener::SwitchToStandby (void) private
A helper function that makes scheduling m_changeStateCallback possible.
Definition at line 453 of file lora-radio-energy-model.cc.
References ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsNull(), m_changeStateCallback, NS_FATAL_ERROR, NS_LOG_FUNCTION, and ns3::lorawan::EndDeviceLoraPhy::STANDBY.
Member Data Documentation
m_changeStateCallback
DeviceEnergyModel::ChangeStateCallback ns3::lorawan::LoraRadioEnergyModelPhyListener::m_changeStateCallback private
Change state callback used to notify the LoraRadioEnergyModel of a state change.
Definition at line 97 of file lora-radio-energy-model.h.
Referenced by LoraRadioEnergyModelPhyListener(), NotifyRxStart(), NotifySleep(), NotifyStandby(), NotifyTxStart(), SetChangeStateCallback(), and SwitchToStandby().
m_updateTxCurrentCallback
UpdateTxCurrentCallback ns3::lorawan::LoraRadioEnergyModelPhyListener::m_updateTxCurrentCallback private
Callback used to update the tx current stored in LoraRadioEnergyModel based on the nominal tx power used to transmit the current frame.
Definition at line 103 of file lora-radio-energy-model.h.
Referenced by LoraRadioEnergyModelPhyListener(), NotifyTxStart(), and SetUpdateTxCurrentCallback().
The documentation for this class was generated from the following files:
src/lorawan/model/lora-radio-energy-model.h
src/lorawan/model/lora-radio-energy-model.cc