ns-3: JakesPropagationExample Class Reference
JakesPropagationExample Class Reference
Propagation Models
Constructs a JakesPropagationlossModel and print the loss value as a function of time into std::cout. Distribution and correlation statistics is compared woth a theoretical ones using R package (http://www.r-project.org/). Scripts are presented within comments.
Public Member Functions
JakesPropagationExample ()
~JakesPropagationExample ()
Private Member Functions
void Next ()
Private Attributes
Ptr< MobilityModel > m_firstMobility
Ptr< PropagationLossModel > m_loss
EventId m_nextEvent
Ptr< MobilityModel > m_secondMobility
Time m_step
Detailed Description
Constructs a JakesPropagationlossModel and print the loss value as a function of time into std::cout. Distribution and correlation statistics is compared woth a theoretical ones using R package (http://www.r-project.org/). Scripts are presented within comments.
Definition at line 33 of file jakes-propagation-model-example.cc.
Constructor & Destructor Documentation
JakesPropagationExample()
JakesPropagationExample::JakesPropagationExample ()
Definition at line 48 of file jakes-propagation-model-example.cc.
References m_firstMobility, m_loss, m_nextEvent, m_secondMobility, m_step, Next(), and ns3::MobilityModel::SetPosition().
~JakesPropagationExample()
JakesPropagationExample::~JakesPropagationExample ()
Definition at line 59 of file jakes-propagation-model-example.cc.
Member Function Documentation
Next()
void JakesPropagationExample::Next () private
Definition at line 63 of file jakes-propagation-model-example.cc.
References ns3::PropagationLossModel::CalcRxPower(), ns3::Time::GetMilliSeconds(), m_firstMobility, m_loss, m_nextEvent, m_secondMobility, m_step, and ns3::Now().
Referenced by JakesPropagationExample().
Member Data Documentation
m_firstMobility
Ptr<MobilityModel> JakesPropagationExample::m_firstMobility private
Definition at line 40 of file jakes-propagation-model-example.cc.
Referenced by JakesPropagationExample(), and Next().
m_loss
Ptr<PropagationLossModel> JakesPropagationExample::m_loss private
Definition at line 39 of file jakes-propagation-model-example.cc.
Referenced by JakesPropagationExample(), and Next().
m_nextEvent
EventId JakesPropagationExample::m_nextEvent private
Definition at line 43 of file jakes-propagation-model-example.cc.
Referenced by JakesPropagationExample(), and Next().
m_secondMobility
Ptr<MobilityModel> JakesPropagationExample::m_secondMobility private
Definition at line 41 of file jakes-propagation-model-example.cc.
Referenced by JakesPropagationExample(), and Next().
m_step
Time JakesPropagationExample::m_step private
Definition at line 42 of file jakes-propagation-model-example.cc.
Referenced by JakesPropagationExample(), and Next().
The documentation for this class was generated from the following file:
src/propagation/examples/jakes-propagation-model-example.cc