ns-3: ns3::TransmissionModesLayers Class Reference
ns3::TransmissionModesLayers Class Reference
TransmissionModesLayers class.
#include "lte-common.h"
Static Public Member Functions
static uint8_t TxMode2LayerNum (uint8_t txMode)
Transmit mode 2 layer number.
Detailed Description
TransmissionModesLayers class.
Definition at line 173 of file lte-common.h.
Member Function Documentation
TxMode2LayerNum()
uint8_t ns3::TransmissionModesLayers::TxMode2LayerNum (uint8_t txMode) static
Transmit mode 2 layer number.
Parameters
txMode the transmit mode
Returns
the layer 2 number
Definition at line 212 of file lte-common.cc.
Referenced by ns3::LteUePhy::CreateDlCqiFeedbackMessage(), ns3::CqaFfMacScheduler::DoSchedDlTriggerReq(), ns3::FdBetFfMacScheduler::DoSchedDlTriggerReq(), ns3::FdMtFfMacScheduler::DoSchedDlTriggerReq(), ns3::FdTbfqFfMacScheduler::DoSchedDlTriggerReq(), ns3::PfFfMacScheduler::DoSchedDlTriggerReq(), ns3::PssFfMacScheduler::DoSchedDlTriggerReq(), ns3::RrFfMacScheduler::DoSchedDlTriggerReq(), ns3::TdBetFfMacScheduler::DoSchedDlTriggerReq(), ns3::TdMtFfMacScheduler::DoSchedDlTriggerReq(), ns3::TdTbfqFfMacScheduler::DoSchedDlTriggerReq(), ns3::TtaFfMacScheduler::DoSchedDlTriggerReq(), and ns3::LteSpectrumPhy::SetTransmissionMode().
The documentation for this class was generated from the following files:
src/lte/model/lte-common.h
src/lte/model/lte-common.cc