ns-3: LinkCheckTest Class Reference
LinkCheckTest Class Reference
Public Member Functions
LinkCheckTest ()
virtual ~LinkCheckTest ()
void LastKnownGatewayCount (int newValue, int oldValue)
void SendPacket (Ptr< Node > endDevice, bool requestAck)
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
int m_numberOfGatewaysThatReceivedPacket = 0
bool m_receivedPacketAtEd = false
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Definition at line 187 of file network-server-test-suite.cc.
Constructor & Destructor Documentation
LinkCheckTest()
LinkCheckTest::LinkCheckTest ()
Definition at line 204 of file network-server-test-suite.cc.
~LinkCheckTest()
LinkCheckTest::~LinkCheckTest () virtual
Definition at line 211 of file network-server-test-suite.cc.
Member Function Documentation
DoRun()
void LinkCheckTest::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 244 of file network-server-test-suite.cc.
References third::channel, ns3::lorawan::NetworkComponents::channel, ns3::lorawan::NetworkComponents::endDevices, ns3::lorawan::NetworkComponents::gateways, ns3::NodeContainer::Get(), ns3::Node::GetDevice(), ns3::Object::GetObject(), ns3::lorawan::InitializeNetwork(), LastKnownGatewayCount(), m_receivedPacketAtEd, ns3::MakeCallback(), NS_ASSERT, NS_LOG_DEBUG, ns3::lorawan::NetworkComponents::nsNode, ns3::Seconds(), and SendPacket().
LastKnownGatewayCount()
void LinkCheckTest::LastKnownGatewayCount (int newValue, int oldValue)
Definition at line 216 of file network-server-test-suite.cc.
References m_numberOfGatewaysThatReceivedPacket, m_receivedPacketAtEd, and NS_LOG_DEBUG.
Referenced by DoRun().
SendPacket()
void LinkCheckTest::SendPacket (Ptr< Node > endDevice, bool requestAck)
Definition at line 226 of file network-server-test-suite.cc.
References ns3::lorawan::EndDeviceLorawanMac::AddMacCommand(), ns3::Node::GetDevice(), ns3::Object::GetObject(), and ns3::lorawan::EndDeviceLorawanMac::SetMType().
Referenced by DoRun().
Member Data Documentation
m_numberOfGatewaysThatReceivedPacket
int LinkCheckTest::m_numberOfGatewaysThatReceivedPacket = 0 private
Definition at line 200 of file network-server-test-suite.cc.
Referenced by LastKnownGatewayCount().
m_receivedPacketAtEd
bool LinkCheckTest::m_receivedPacketAtEd = false private
Definition at line 199 of file network-server-test-suite.cc.
Referenced by DoRun(), and LastKnownGatewayCount().
The documentation for this class was generated from the following file:
src/lorawan/test/network-server-test-suite.cc