ns-3: TcpNewRenoCongAvoidNormalTest Class Reference
TcpNewRenoCongAvoidNormalTest Class Reference
Internet » internet module tests | Test suites
Test the behavior of RFC congestion avoidance.
Public Member Functions
TcpNewRenoCongAvoidNormalTest (uint32_t segmentSize, uint32_t packetSize, uint32_t packets, TypeId &congControl, const std::string &desc)
Constructor.
Public Member Functions inherited from ns3::TcpGeneralTest
TcpGeneralTest (const std::string &desc)
TcpGeneralTest constructor.
~TcpGeneralTest ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Member Functions
void Check ()
Called each RTT (1.0 sec in the testing environment) and check that the overall increment in this RTT is less or equal than 1 MSS.
virtual void ConfigureEnvironment ()
Change the configuration of the environment.
virtual void ConfigureProperties ()
Change the configuration of the socket properties.
virtual void CWndTrace (uint32_t oldValue, uint32_t newValue)
Tracks the congestion window changes.
virtual void NormalClose (SocketWho who)
Socket closed normally.
virtual void PhyDrop (SocketWho who)
Link drop.
virtual void QueueDrop (SocketWho who)
Drop on the queue.
Protected Member Functions inherited from ns3::TcpGeneralTest
virtual void AfterRTOExpired (const Ptr< const TcpSocketState > tcb, SocketWho who)
Rto has expired.
virtual void BeforeRTOExpired (const Ptr< const TcpSocketState > tcb, SocketWho who)
Rto has expired.
virtual void BytesInFlightTrace (uint32_t oldValue, uint32_t newValue)
Bytes in flight changes.
virtual void CongStateTrace (const TcpSocketState::TcpCongState_t oldValue, const TcpSocketState::TcpCongState_t newValue)
State on Ack state machine changes.
virtual Ptr< SimpleChannel > CreateChannel ()
Create and return the channel installed between the two socket.
virtual Ptr< ErrorModel > CreateReceiverErrorModel ()
Create and return the error model to install in the receiver node.
virtual Ptr< TcpSocketMsgBase > CreateReceiverSocket (Ptr< Node > node)
Create and install the socket to install on the receiver.
virtual Ptr< ErrorModel > CreateSenderErrorModel ()
Create and return the error model to install in the sender node.
virtual Ptr< TcpSocketMsgBase > CreateSenderSocket (Ptr< Node > node)
Create and install the socket to install on the sender.
virtual Ptr< TcpSocketMsgBase > CreateSocket (Ptr< Node > node, TypeId socketType, TypeId congControl)
Create a socket.
virtual Ptr< TcpSocketMsgBase > CreateSocket (Ptr< Node > node, TypeId socketType, TypeId congControl, TypeId recoveryAlgorithm)
Create a socket.
virtual void CWndInflTrace (uint32_t oldValue, uint32_t newValue)
Tracks the inflated congestion window changes.
virtual void DataSent (uint32_t size, SocketWho who)
Notifying application for sent data.
void DoConnect ()
Scheduled at 0.0, SENDER starts the connection to RECEIVER.
virtual void DoRun (void)
Execute the tcp test.
virtual void DoTeardown (void)
Teardown the TCP test.
virtual void ErrorClose (SocketWho who)
Socket closed with an error.
virtual void FinalChecks ()
Performs the (eventual) final checks through test asserts.
Time GetClockGranularity (SocketWho who)
Get the clock granularity attribute.
Time GetConnTimeout (SocketWho who)
Get the retransmission time for the SYN segments.
uint32_t GetDelAckCount (SocketWho who)
Get the number of delayed ack (if present)
Time GetDelAckTimeout (SocketWho who)
Get the timeout of delayed ack (if present)
uint32_t GetDupAckCount (SocketWho who)
Get the number of dupack received.
SequenceNumber32 GetHighestTxMark (SocketWho who)
Get the highest tx mark of the node specified.
uint32_t GetInitialCwnd (SocketWho who)
Get the initial congestion window.
uint32_t GetInitialSsThresh (SocketWho who)
Get the initial slow start threshold.
Time GetMinRto (SocketWho who)
Get the minimum RTO attribute.
uint32_t GetMtu () const
Get the MTU of the environment.
EventId GetPersistentEvent (SocketWho who)
Get the persistent event of the selected socket.
Time GetPersistentTimeout (SocketWho who)
Get the persistent timeout of the selected socket.
uint32_t GetPktCount () const
Get the number of application packets.
Time GetPktInterval () const
Get the interval to wait for each packet sent down from application to TCP.
uint32_t GetPktSize () const
Get the application packet size.
Time GetPropagationDelay () const
Get the channel Propagation Delay.
Ptr< TcpSocketMsgBase > GetReceiverSocket ()
Get the pointer to a previously created receiver socket.
uint32_t GetReTxThreshold (SocketWho who)
Get the retransmission threshold.
Time GetRto (SocketWho who)
Get the retransmission time.
Ptr< RttEstimator > GetRttEstimator (SocketWho who)
Get the Rtt estimator of the socket.
uint32_t GetRWnd (SocketWho who)
Get the rWnd of the selected socket.
Ptr< TcpRxBuffer > GetRxBuffer (SocketWho who)
Get the Rx buffer from selected socket.
uint32_t GetSegSize (SocketWho who)
Get the segment size of the node specified.
Ptr< TcpSocketMsgBase > GetSenderSocket ()
Get the pointer to a previously created sender socket.
Time GetStartTime () const
Get the data start time.
Ptr< TcpSocketState > GetTcb (SocketWho who)
Get the TCB from selected socket.
TcpSocket::TcpStates_t GetTcpState (SocketWho who)
Get the state of the TCP state machine.
Ptr< TcpTxBuffer > GetTxBuffer (SocketWho who)
Get the Tx buffer from selected socket.
virtual void HighestTxSeqTrace (SequenceNumber32 oldValue, SequenceNumber32 newValue)
Highest tx seq changes.
virtual void NextTxSeqTrace (SequenceNumber32 oldValue, SequenceNumber32 newValue)
Next tx seq changes.
virtual void ProcessedAck (const Ptr< const TcpSocketState > tcb, const TcpHeader &h, SocketWho who)
Processed ack.
virtual void RateSampleUpdatedTrace (const TcpRateLinux::TcpRateSample &sample)
Track the rate sample value of TcpRateLinux.
virtual void RateUpdatedTrace (const TcpRateLinux::TcpRateConnection &rate)
Track the rate value of TcpRateLinux.
virtual void RcvAck (const Ptr< const TcpSocketState > tcb, const TcpHeader &h, SocketWho who)
Received ack.
virtual void ReceivePacket (Ptr< Socket > socket)
Packet received.
virtual void RtoTrace (Time oldValue, Time newValue)
RTO changes.
virtual void RttTrace (Time oldTime, Time newTime)
Rtt changes.
virtual void Rx (const Ptr< const Packet > p, const TcpHeader &h, SocketWho who)
Packet received from IP layer.
void SendPacket (Ptr< Socket > socket, uint32_t pktSize, uint32_t pktCount, Time pktInterval)
Send packets to other endpoint.
void SetAppPktCount (uint32_t pktCount)
Set app packet count.
void SetAppPktInterval (Time pktInterval)
Interval between app-generated packet.
void SetAppPktSize (uint32_t pktSize)
Set app packet size.
void SetCongestionControl (TypeId congControl)
Congestion control of the sender socket.
void SetInitialCwnd (SocketWho who, uint32_t initialCwnd)
Forcefully set the initial cwnd.
void SetInitialSsThresh (SocketWho who, uint32_t initialSsThresh)
Forcefully set the initial ssth.
void SetMTU (uint32_t mtu)
MTU of the bottleneck link.
void SetPropagationDelay (Time propDelay)
Propagation delay of the bottleneck link.
void SetRcvBufSize (SocketWho who, uint32_t size)
Forcefully set a defined size for rx buffer.
void SetRecoveryAlgorithm (TypeId reccovery)
recovery algorithm of the sender socket
void SetSegmentSize (SocketWho who, uint32_t segmentSize)
Forcefully set the segment size.
void SetTransmitStart (Time startTime)
Set the initial time at which the application sends the first data packet.
void SetUseEcn (SocketWho who, TcpSocketState::UseEcn_t useEcn)
Forcefully set the ecn use on.
virtual void SsThreshTrace (uint32_t oldValue, uint32_t newValue)
Slow start threshold changes.
virtual void Tx (const Ptr< const Packet > p, const TcpHeader &h, SocketWho who)
Packet transmitted down to IP layer.
virtual void UpdatedRttHistory (const SequenceNumber32 &seq, uint32_t sz, bool isRetransmission, SocketWho who)
Updated the Rtt history.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Private Attributes
EventId m_event
Check event.
uint32_t m_increment
Congestion window increment.
bool m_initial
True on first run.
uint32_t m_packets
Number of packets.
uint32_t m_packetSize
Size of the packets.
uint32_t m_segmentSize
Segment size.
Additional Inherited Members
Public Types inherited from ns3::TcpGeneralTest
enum SocketWho { SENDER, RECEIVER }
Used as parameter of methods, specifies on what node the caller is interested (e.g.
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Attributes inherited from ns3::TcpGeneralTest
TypeId m_congControlTypeId
Congestion control.
TypeId m_recoveryTypeId
Recovery.
Detailed Description
Test the behavior of RFC congestion avoidance.
From RFC 5681:
cwnd += min (N, SMSS)                      (2)
During congestion avoidance, cwnd is incremented by roughly 1 full- sized segment per round-trip time (RTT). Congestion avoidance continues until congestion is detected. The basic guidelines for incrementing cwnd during congestion avoidance are:
MAY increment cwnd by SMSS bytes
SHOULD increment cwnd per equation (2) once per RTT
MUST NOT increment cwnd by more than SMSS bytes
To test this behavior and these points, a tracing callback is attached to the cWnd. Each time it increases, the increment is saved. Meanwhile, a timer checks if an amount of time equals to the RTT has passed, and if yes, it checks that the increment has not passed the 1 MSS limit.
Definition at line 56 of file tcp-cong-avoid-test.cc.
Constructor & Destructor Documentation
TcpNewRenoCongAvoidNormalTest()
TcpNewRenoCongAvoidNormalTest::TcpNewRenoCongAvoidNormalTest (uint32_t segmentSize, uint32_t packetSize, uint32_t packets, TypeId & congControl, const std::string & desc)
Constructor.
Parameters
segmentSize Segment size.
packetSize Size of the packets.
packets Number of packets.
congControl Type of congestion control.
desc The test description.
Definition at line 95 of file tcp-cong-avoid-test.cc.
References ns3::TcpGeneralTest::m_congControlTypeId.
Member Function Documentation
Check()
void TcpNewRenoCongAvoidNormalTest::Check () protected
Called each RTT (1.0 sec in the testing environment) and check that the overall increment in this RTT is less or equal than 1 MSS.
Definition at line 157 of file tcp-cong-avoid-test.cc.
References ns3::TcpGeneralTest::GetSegSize(), m_event, m_increment, NS_TEST_ASSERT_MSG_LT_OR_EQ, and ns3::Seconds().
Referenced by CWndTrace().
ConfigureEnvironment()
void TcpNewRenoCongAvoidNormalTest::ConfigureEnvironment () protected virtual
Change the configuration of the environment.
Reimplemented from ns3::TcpGeneralTest.
Definition at line 111 of file tcp-cong-avoid-test.cc.
References m_packets, m_packetSize, ns3::TcpGeneralTest::SetAppPktCount(), ns3::TcpGeneralTest::SetAppPktSize(), and ns3::TcpGeneralTest::SetMTU().
ConfigureProperties()
void TcpNewRenoCongAvoidNormalTest::ConfigureProperties () protected virtual
Change the configuration of the socket properties.
Reimplemented from ns3::TcpGeneralTest.
Definition at line 119 of file tcp-cong-avoid-test.cc.
References m_segmentSize, ns3::TcpGeneralTest::SENDER, ns3::TcpGeneralTest::SetInitialSsThresh(), and ns3::TcpGeneralTest::SetSegmentSize().
CWndTrace()
void TcpNewRenoCongAvoidNormalTest::CWndTrace (uint32_t oldValue, uint32_t newValue) protected virtual
Tracks the congestion window changes.
Parameters
oldValue old value
newValue new value
Reimplemented from ns3::TcpGeneralTest.
Definition at line 127 of file tcp-cong-avoid-test.cc.
References Check(), ns3::EventId::IsRunning(), m_event, m_increment, m_initial, and ns3::Seconds().
NormalClose()
void TcpNewRenoCongAvoidNormalTest::NormalClose (SocketWho who) protected virtual
Socket closed normally.
Parameters
who the socket closed (SENDER or RECEIVER)
Reimplemented from ns3::TcpGeneralTest.
Definition at line 175 of file tcp-cong-avoid-test.cc.
References ns3::EventId::Cancel(), m_event, and ns3::TcpGeneralTest::SENDER.
PhyDrop()
void TcpNewRenoCongAvoidNormalTest::PhyDrop (SocketWho who) protected virtual
Link drop.
Parameters
who where the drop occurred (SENDER or RECEIVER)
Reimplemented from ns3::TcpGeneralTest.
Definition at line 151 of file tcp-cong-avoid-test.cc.
References NS_FATAL_ERROR.
QueueDrop()
void TcpNewRenoCongAvoidNormalTest::QueueDrop (SocketWho who) protected virtual
Drop on the queue.
Parameters
who where the drop occurred (SENDER or RECEIVER)
Reimplemented from ns3::TcpGeneralTest.
Definition at line 145 of file tcp-cong-avoid-test.cc.
References NS_FATAL_ERROR.
Member Data Documentation
m_event
EventId TcpNewRenoCongAvoidNormalTest::m_event private
Check event.
Definition at line 90 of file tcp-cong-avoid-test.cc.
Referenced by Check(), CWndTrace(), and NormalClose().
m_increment
uint32_t TcpNewRenoCongAvoidNormalTest::m_increment private
Congestion window increment.
Definition at line 89 of file tcp-cong-avoid-test.cc.
Referenced by Check(), and CWndTrace().
m_initial
bool TcpNewRenoCongAvoidNormalTest::m_initial private
True on first run.
Definition at line 91 of file tcp-cong-avoid-test.cc.
Referenced by CWndTrace().
m_packets
uint32_t TcpNewRenoCongAvoidNormalTest::m_packets private
Number of packets.
Definition at line 88 of file tcp-cong-avoid-test.cc.
Referenced by ConfigureEnvironment().
m_packetSize
uint32_t TcpNewRenoCongAvoidNormalTest::m_packetSize private
Size of the packets.
Definition at line 87 of file tcp-cong-avoid-test.cc.
Referenced by ConfigureEnvironment().
m_segmentSize
uint32_t TcpNewRenoCongAvoidNormalTest::m_segmentSize private
Segment size.
Definition at line 86 of file tcp-cong-avoid-test.cc.
Referenced by ConfigureProperties().
The documentation for this class was generated from the following file:
src/internet/test/tcp-cong-avoid-test.cc