ns-3: Bug2222TestCase Class Reference
Bug2222TestCase Class Reference
Make sure that when virtual collision occurs the wifi remote station manager is triggered and the retry counter is increased.
Public Member Functions
Bug2222TestCase ()
virtual ~Bug2222TestCase ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void PopulateArpCache ()
Populate ARP cache function.
void TxDataFailedTrace (std::string context, Mac48Address adress)
Transmit data failed function.
Private Attributes
uint32_t m_countInternalCollisions
count internal collisions
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Make sure that when virtual collision occurs the wifi remote station manager is triggered and the retry counter is increased.
See Bug 2222
Definition at line 1208 of file wifi-test.cc.
Constructor & Destructor Documentation
Bug2222TestCase()
Bug2222TestCase::Bug2222TestCase ()
Definition at line 1230 of file wifi-test.cc.
~Bug2222TestCase()
Bug2222TestCase::~Bug2222TestCase () virtual
Definition at line 1236 of file wifi-test.cc.
Member Function Documentation
DoRun()
void Bug2222TestCase::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 1248 of file wifi-test.cc.
References ns3::ListPositionAllocator::Add(), ns3::Node::AddApplication(), third::channel, ns3::Config::Connect(), ns3::NodeContainer::Create(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::WifiNetDevice::GetAddress(), ns3::WifiNetDevice::GetIfIndex(), ns3::PacketSocketHelper::Install(), m_countInternalCollisions, third::mac, ns3::MakeCallback(), third::mobility, NS_TEST_ASSERT_MSG_EQ, third::phy, ns3::Seconds(), ns3::ObjectBase::SetAttribute(), ns3::PacketSocketServer::SetLocal(), ns3::PacketSocketAddress::SetPhysicalAddress(), ns3::PacketSocketAddress::SetProtocol(), ns3::PacketSocketClient::SetRemote(), ns3::PacketSocketAddress::SetSingleDevice(), ns3::Application::SetStartTime(), ns3::Application::SetStopTime(), third::ssid, TxDataFailedTrace(), and third::wifi.
PopulateArpCache()
void Bug2222TestCase::PopulateArpCache () private
Populate ARP cache function.
TxDataFailedTrace()
void Bug2222TestCase::TxDataFailedTrace (std::string context, Mac48Address adress) private
Transmit data failed function.
Parameters
context the context
adr the MAC address
Definition at line 1241 of file wifi-test.cc.
References m_countInternalCollisions.
Referenced by DoRun().
Member Data Documentation
m_countInternalCollisions
uint32_t Bug2222TestCase::m_countInternalCollisions private
count internal collisions
Definition at line 1218 of file wifi-test.cc.
Referenced by DoRun(), and TxDataFailedTrace().
The documentation for this class was generated from the following file:
src/wifi/test/wifi-test.cc