ns-3: ns3::BuildingsPropagationLossModel Class Reference
ns3::BuildingsPropagationLossModel Class Reference abstract
Propagation Models
#include "buildings-propagation-loss-model.h"
Classes
class ShadowingLoss
Public Member Functions
BuildingsPropagationLossModel ()
virtual double DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account only the particular PropagationLossModel.
virtual double GetLoss (Ptr< MobilityModel > a, Ptr< MobilityModel > b) const =0
Public Member Functions inherited from ns3::PropagationLossModel
PropagationLossModel ()
virtual ~PropagationLossModel ()
int64_t AssignStreams (int64_t stream)
If this loss model uses objects of type RandomVariableStream, set the stream numbers to the integers starting with the offset 'stream'.
double CalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
Returns the Rx Power taking into account all the PropagationLossModel(s) chained to the current one.
Ptr< PropagationLossModel > GetNext ()
Gets the next PropagationLossModel in the chain of loss models that act on the signal.
void SetNext (Ptr< PropagationLossModel > next)
Enables a chain of loss models to act on the signal.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::PropagationLossModel
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual int64_t DoAssignStreams (int64_t stream)
Subclasses must implement this; those not using random variables can return zero.
double EvaluateSigma (Ptr< MobilityBuildingInfo > a, Ptr< MobilityBuildingInfo > b) const
double ExternalWallLoss (Ptr< MobilityBuildingInfo > a) const
double GetShadowing (Ptr< MobilityModel > a, Ptr< MobilityModel > b) const
double HeightLoss (Ptr< MobilityBuildingInfo > n) const
double InternalWallsLoss (Ptr< MobilityBuildingInfo > a, Ptr< MobilityBuildingInfo > b) const
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Protected Attributes
double m_lossInternalWall
Ptr< NormalRandomVariable > m_randVariable
std::map< Ptr< MobilityModel >, std::map< Ptr< MobilityModel >, ShadowingLoss > > m_shadowingLossMap
double m_shadowingSigmaExtWalls
double m_shadowingSigmaIndoor
double m_shadowingSigmaOutdoor
Additional Inherited Members
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
This model provides means for simulating the following propagation phenomena in the presence of buildings:
shadowing (indoor, outdoor)
external wall penetration loss
internal wall penetration loss
The distance-dependent component of propagation loss is deferred to derived classes which are expected to implement the GetLoss method.
Warning
This model works only when MobilityBuildingInfo is aggreegated to the mobility model
Definition at line 57 of file buildings-propagation-loss-model.h.
Constructor & Destructor Documentation
BuildingsPropagationLossModel()
ns3::BuildingsPropagationLossModel::BuildingsPropagationLossModel ()
Definition at line 98 of file buildings-propagation-loss-model.cc.
References m_randVariable.
Member Function Documentation
DoAssignStreams()
int64_t ns3::BuildingsPropagationLossModel::DoAssignStreams (int64_t stream) protected virtual
Subclasses must implement this; those not using random variables can return zero.
Implements ns3::PropagationLossModel.
Definition at line 226 of file buildings-propagation-loss-model.cc.
References m_randVariable.
DoCalcRxPower()
double ns3::BuildingsPropagationLossModel::DoCalcRxPower (double txPowerDbm, Ptr< MobilityModel > a, Ptr< MobilityModel > b) const virtual
Returns the Rx Power taking into account only the particular PropagationLossModel.
Parameters
txPowerDbm current transmission power (in dBm)
a the mobility model of the source
b the mobility model of the destination
Returns
the reception power after adding/multiplying propagation loss (in dBm)
Implements ns3::PropagationLossModel.
Definition at line 220 of file buildings-propagation-loss-model.cc.
References GetLoss(), and GetShadowing().
Referenced by BuildingsShadowingTestCase::DoRun().
EvaluateSigma()
double ns3::BuildingsPropagationLossModel::EvaluateSigma (Ptr< MobilityBuildingInfo > a, Ptr< MobilityBuildingInfo > b) const protected
Definition at line 188 of file buildings-propagation-loss-model.cc.
References m_shadowingSigmaExtWalls, m_shadowingSigmaIndoor, and m_shadowingSigmaOutdoor.
Referenced by GetShadowing().
ExternalWallLoss()
double ns3::BuildingsPropagationLossModel::ExternalWallLoss (Ptr< MobilityBuildingInfo > a) const protected
Definition at line 104 of file buildings-propagation-loss-model.cc.
References ns3::Building::ConcreteWithoutWindows, ns3::Building::ConcreteWithWindows, ns3::Building::StoneBlocks, and ns3::Building::Wood.
Referenced by ns3::HybridBuildingsPropagationLossModel::GetLoss(), and ns3::OhBuildingsPropagationLossModel::GetLoss().
GetLoss()
virtual double ns3::BuildingsPropagationLossModel::GetLoss (Ptr< MobilityModel > a, Ptr< MobilityModel > b) const pure virtual
Parameters
a the mobility model of the source
b the mobility model of the destination
Returns
the propagation loss (in dBm)
Implemented in ns3::OhBuildingsPropagationLossModel, and ns3::HybridBuildingsPropagationLossModel.
Referenced by DoCalcRxPower(), and GetShadowing().
GetShadowing()
double ns3::BuildingsPropagationLossModel::GetShadowing (Ptr< MobilityModel > a, Ptr< MobilityModel > b) const protected
Definition at line 149 of file buildings-propagation-loss-model.cc.
References EvaluateSigma(), GetLoss(), ns3::Object::GetObject(), m_randVariable, m_shadowingLossMap, and NS_ASSERT_MSG().
Referenced by DoCalcRxPower().
GetTypeId()
TypeId ns3::BuildingsPropagationLossModel::GetTypeId (void) static
Definition at line 63 of file buildings-propagation-loss-model.cc.
References m_lossInternalWall, m_shadowingSigmaExtWalls, m_shadowingSigmaIndoor, m_shadowingSigmaOutdoor, ns3::MakeDoubleAccessor(), and ns3::TypeId::SetParent().
HeightLoss()
double ns3::BuildingsPropagationLossModel::HeightLoss (Ptr< MobilityBuildingInfo > n) const protected
Definition at line 128 of file buildings-propagation-loss-model.cc.
Referenced by ns3::HybridBuildingsPropagationLossModel::GetLoss().
InternalWallsLoss()
double ns3::BuildingsPropagationLossModel::InternalWallsLoss (Ptr< MobilityBuildingInfo > a, Ptr< MobilityBuildingInfo > b) const protected
Definition at line 138 of file buildings-propagation-loss-model.cc.
References m_lossInternalWall.
Referenced by ns3::HybridBuildingsPropagationLossModel::GetLoss(), and ns3::OhBuildingsPropagationLossModel::GetLoss().
Member Data Documentation
m_lossInternalWall
double ns3::BuildingsPropagationLossModel::m_lossInternalWall protected
Definition at line 81 of file buildings-propagation-loss-model.h.
Referenced by GetTypeId(), and InternalWallsLoss().
m_randVariable
Ptr<NormalRandomVariable> ns3::BuildingsPropagationLossModel::m_randVariable protected
Definition at line 103 of file buildings-propagation-loss-model.h.
Referenced by BuildingsPropagationLossModel(), DoAssignStreams(), and GetShadowing().
m_shadowingLossMap
std::map<Ptr<MobilityModel>, std::map<Ptr<MobilityModel>, ShadowingLoss> > ns3::BuildingsPropagationLossModel::m_shadowingLossMap mutable protected
Definition at line 96 of file buildings-propagation-loss-model.h.
Referenced by GetShadowing().
m_shadowingSigmaExtWalls
double ns3::BuildingsPropagationLossModel::m_shadowingSigmaExtWalls protected
Definition at line 100 of file buildings-propagation-loss-model.h.
Referenced by EvaluateSigma(), and GetTypeId().
m_shadowingSigmaIndoor
double ns3::BuildingsPropagationLossModel::m_shadowingSigmaIndoor protected
Definition at line 102 of file buildings-propagation-loss-model.h.
Referenced by EvaluateSigma(), and GetTypeId().
m_shadowingSigmaOutdoor
double ns3::BuildingsPropagationLossModel::m_shadowingSigmaOutdoor protected
Definition at line 101 of file buildings-propagation-loss-model.h.
Referenced by EvaluateSigma(), and GetTypeId().
The documentation for this class was generated from the following files:
src/buildings/model/buildings-propagation-loss-model.h
src/buildings/model/buildings-propagation-loss-model.cc