ns-3: ns3::flame::FlameHeader Class Reference
ns3::flame::FlameHeader Class Reference
Mesh Device » FLAME
Flame header.
#include "flame-header.h"
Public Member Functions
FlameHeader ()
~FlameHeader ()
void AddCost (uint8_t cost)
Add cost value.
virtual uint32_t Deserialize (Buffer::Iterator start)
uint8_t GetCost () const
Get cost value.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
Mac48Address GetOrigDst () const
Get origin destination address.
Mac48Address GetOrigSrc () const
Get origin source address.
uint16_t GetProtocol () const
Get protocol value.
uint16_t GetSeqno () const
Get sequence number value.
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetOrigDst (Mac48Address dst)
Set origin destination address.
void SetOrigSrc (Mac48Address OrigSrc)
Set origin source function.
void SetProtocol (uint16_t protocol)
Set protocol value.
void SetSeqno (uint16_t seqno)
Set sequence number value.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_cost
cost
Mac48Address m_origDst
origin destination
Mac48Address m_origSrc
origin source
uint16_t m_protocol
protocol
uint16_t m_seqno
sequence number
Friends
bool operator== (const FlameHeader &a, const FlameHeader &b)
equality operator
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Flame header.
Header format: | Reserved: 1 | cost: 1 | Sequence number: 2 | OrigDst: 6 | OrigSrc: 6 | Flame port : 2 |
Definition at line 37 of file flame-header.h.
Constructor & Destructor Documentation
FlameHeader()
ns3::flame::FlameHeader::FlameHeader ()
Definition at line 31 of file flame-header.cc.
~FlameHeader()
ns3::flame::FlameHeader::~FlameHeader ()
Definition at line 35 of file flame-header.cc.
Member Function Documentation
AddCost()
void ns3::flame::FlameHeader::AddCost (uint8_t cost)
Add cost value.
Parameters
cost the cost
Definition at line 93 of file flame-header.cc.
References m_cost.
Referenced by FlameHeaderTest::DoRun(), and ns3::flame::FlameProtocol::RequestRoute().
Deserialize()
uint32_t ns3::flame::FlameHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 81 of file flame-header.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_cost, m_origDst, m_origSrc, m_protocol, m_seqno, ns3::Buffer::Iterator::Next(), ns3::ReadFrom(), ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadU8(), and visualizer.core::start().
GetCost()
uint8_t ns3::flame::FlameHeader::GetCost () const
Get cost value.
Returns
the cost
Definition at line 98 of file flame-header.cc.
References m_cost.
Referenced by ns3::flame::FlameProtocol::HandleDataFrame().
GetInstanceTypeId()
TypeId ns3::flame::FlameHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 48 of file flame-header.cc.
References GetTypeId().
GetOrigDst()
Mac48Address ns3::flame::FlameHeader::GetOrigDst () const
Get origin destination address.
Returns
the MAC address of the destination
Definition at line 118 of file flame-header.cc.
References m_origDst.
GetOrigSrc()
Mac48Address ns3::flame::FlameHeader::GetOrigSrc () const
Get origin source address.
Returns
the MAC address of the origin source
Definition at line 128 of file flame-header.cc.
References m_origSrc.
GetProtocol()
uint16_t ns3::flame::FlameHeader::GetProtocol () const
Get protocol value.
Returns
the protocol
Definition at line 138 of file flame-header.cc.
References m_protocol.
Referenced by ns3::flame::FlameProtocol::RemoveRoutingStuff().
GetSeqno()
uint16_t ns3::flame::FlameHeader::GetSeqno () const
Get sequence number value.
Returns
the sequence number
Definition at line 108 of file flame-header.cc.
References m_seqno.
Referenced by ns3::flame::FlameProtocol::HandleDataFrame(), ns3::flame::FlameProtocol::RemoveRoutingStuff(), and ns3::flame::FlameProtocol::RequestRoute().
GetSerializedSize()
uint32_t ns3::flame::FlameHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 59 of file flame-header.cc.
GetTypeId()
TypeId ns3::flame::FlameHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 39 of file flame-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::flame::FlameHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 53 of file flame-header.cc.
References m_cost, m_origDst, m_origSrc, and m_seqno.
Serialize()
void ns3::flame::FlameHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 70 of file flame-header.cc.
References m_cost, m_origDst, m_origSrc, m_protocol, m_seqno, visualizer.core::start(), ns3::Buffer::Iterator::WriteHtonU16(), ns3::WriteTo(), and ns3::Buffer::Iterator::WriteU8().
SetOrigDst()
void ns3::flame::FlameHeader::SetOrigDst (Mac48Address dst)
Set origin destination address.
Parameters
dst the MAC address of the destination
Definition at line 113 of file flame-header.cc.
References m_origDst.
Referenced by FlameHeaderTest::DoRun(), and ns3::flame::FlameProtocol::RequestRoute().
SetOrigSrc()
void ns3::flame::FlameHeader::SetOrigSrc (Mac48Address OrigSrc)
Set origin source function.
Parameters
OrigSrc the MAC address of the origina source
Definition at line 123 of file flame-header.cc.
References m_origSrc.
Referenced by FlameHeaderTest::DoRun(), and ns3::flame::FlameProtocol::RequestRoute().
SetProtocol()
void ns3::flame::FlameHeader::SetProtocol (uint16_t protocol)
Set protocol value.
Parameters
protocol the protocol
Definition at line 133 of file flame-header.cc.
References m_protocol.
Referenced by FlameHeaderTest::DoRun(), and ns3::flame::FlameProtocol::RequestRoute().
SetSeqno()
void ns3::flame::FlameHeader::SetSeqno (uint16_t seqno)
Set sequence number value.
Parameters
seqno the sequence number
Definition at line 103 of file flame-header.cc.
References m_seqno.
Referenced by FlameHeaderTest::DoRun(), and ns3::flame::FlameProtocol::RequestRoute().
Friends And Related Function Documentation
operator==
bool operator== (const FlameHeader & a, const FlameHeader & b) friend
equality operator
Parameters
a lhs
b rhs
Returns
true if equal
Definition at line 143 of file flame-header.cc.
Member Data Documentation
m_cost
uint8_t ns3::flame::FlameHeader::m_cost private
cost
Definition at line 109 of file flame-header.h.
Referenced by AddCost(), Deserialize(), GetCost(), ns3::flame::operator==(), Print(), and Serialize().
m_origDst
Mac48Address ns3::flame::FlameHeader::m_origDst private
origin destination
Definition at line 111 of file flame-header.h.
Referenced by Deserialize(), GetOrigDst(), ns3::flame::operator==(), Print(), Serialize(), and SetOrigDst().
m_origSrc
Mac48Address ns3::flame::FlameHeader::m_origSrc private
origin source
Definition at line 112 of file flame-header.h.
Referenced by Deserialize(), GetOrigSrc(), ns3::flame::operator==(), Print(), Serialize(), and SetOrigSrc().
m_protocol
uint16_t ns3::flame::FlameHeader::m_protocol private
protocol
Definition at line 113 of file flame-header.h.
Referenced by Deserialize(), GetProtocol(), ns3::flame::operator==(), Serialize(), and SetProtocol().
m_seqno
uint16_t ns3::flame::FlameHeader::m_seqno private
sequence number
Definition at line 110 of file flame-header.h.
Referenced by Deserialize(), GetSeqno(), ns3::flame::operator==(), Print(), Serialize(), and SetSeqno().
The documentation for this class was generated from the following files:
src/mesh/model/flame/flame-header.h
src/mesh/model/flame/flame-header.cc