ns-3: ns3::Icmpv6OptionPrefixInformation Class Reference
ns3::Icmpv6OptionPrefixInformation Class Reference
Internet » IPv6 classes and sub-modules » ICMPv6 protocol and associated headers.
ICMPv6 Option Prefix Information.
#include "icmpv6-header.h"
Public Member Functions
Icmpv6OptionPrefixInformation ()
Constructor.
Icmpv6OptionPrefixInformation (Ipv6Address network, uint8_t prefixlen)
Constructor.
virtual ~Icmpv6OptionPrefixInformation ()
Destructor.
virtual uint32_t Deserialize (Buffer::Iterator start)
Deserialize the packet.
uint8_t GetFlags () const
Get the flags.
virtual TypeId GetInstanceTypeId () const
Get the instance type ID.
uint32_t GetPreferredTime () const
Get the preferred time of the information.
Ipv6Address GetPrefix () const
Get the IPv6 prefix.
uint8_t GetPrefixLength () const
Get the prefix length.
uint32_t GetReserved () const
Get the reserved field.
virtual uint32_t GetSerializedSize () const
Get the serialized size.
uint32_t GetValidTime () const
Get the valid time of the information.
virtual void Print (std::ostream &os) const
Print information.
virtual void Serialize (Buffer::Iterator start) const
Serialize the packet.
void SetFlags (uint8_t flags)
Set the flags.
void SetPreferredTime (uint32_t preferredTime)
Set the preferred time of the information.
void SetPrefix (Ipv6Address prefix)
Set the IPv6 prefix.
void SetPrefixLength (uint8_t prefixLength)
Set the prefix length.
void SetReserved (uint32_t reserved)
Set the reserved field (normally it will be 0x00000000).
void SetValidTime (uint32_t validTime)
Set the valid time of the information.
Public Member Functions inherited from ns3::Icmpv6OptionHeader
Icmpv6OptionHeader ()
Constructor.
virtual ~Icmpv6OptionHeader ()
Destructor.
uint8_t GetLength () const
Get the length of the option in 8 bytes unit.
uint8_t GetType () const
Get the type of the option.
void SetLength (uint8_t len)
Set the length of the option.
void SetType (uint8_t type)
Set the type of the option.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId ()
Get the UID of this class.
Static Public Member Functions inherited from ns3::Icmpv6OptionHeader
static TypeId GetTypeId ()
Get the UID of this class.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
uint8_t m_flags
The flags.
uint32_t m_preferredTime
The preferred time.
Ipv6Address m_prefix
The prefix value.
uint8_t m_prefixLength
The length of the prefix.
uint32_t m_reserved
The reserved field.
uint32_t m_validTime
The valid time.
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
ICMPv6 Option Prefix Information.
Definition at line 1471 of file icmpv6-header.h.
Constructor & Destructor Documentation
Icmpv6OptionPrefixInformation() [1/2]
ns3::Icmpv6OptionPrefixInformation::Icmpv6OptionPrefixInformation ()
Constructor.
Definition at line 1657 of file icmpv6-header.cc.
References ns3::Icmpv6Header::ICMPV6_OPT_PREFIX, NS_LOG_FUNCTION, SetFlags(), ns3::Icmpv6OptionHeader::SetLength(), SetPreferredTime(), SetPrefix(), SetPrefixLength(), SetReserved(), ns3::Icmpv6OptionHeader::SetType(), and SetValidTime().
Icmpv6OptionPrefixInformation() [2/2]
ns3::Icmpv6OptionPrefixInformation::Icmpv6OptionPrefixInformation (Ipv6Address network, uint8_t prefixlen)
Constructor.
Parameters
network prefix
prefixlen prefix length
Definition at line 1670 of file icmpv6-header.cc.
References ns3::Icmpv6Header::ICMPV6_OPT_PREFIX, NS_LOG_FUNCTION, SetFlags(), ns3::Icmpv6OptionHeader::SetLength(), SetPreferredTime(), SetPrefix(), SetPrefixLength(), SetReserved(), ns3::Icmpv6OptionHeader::SetType(), and SetValidTime().
~Icmpv6OptionPrefixInformation()
ns3::Icmpv6OptionPrefixInformation::~Icmpv6OptionPrefixInformation () virtual
Destructor.
Definition at line 1683 of file icmpv6-header.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
Deserialize()
uint32_t ns3::Icmpv6OptionPrefixInformation::Deserialize (Buffer::Iterator start) virtual
Deserialize the packet.
Parameters
start start offset
Returns
length of packet
Reimplemented from ns3::Icmpv6OptionHeader.
Definition at line 1792 of file icmpv6-header.cc.
References GetSerializedSize(), NS_LOG_FUNCTION, ns3::Buffer::Iterator::Read(), ns3::Buffer::Iterator::ReadNtohU32(), ns3::Buffer::Iterator::ReadU8(), SetFlags(), ns3::Icmpv6OptionHeader::SetLength(), SetPreferredTime(), SetPrefix(), SetPrefixLength(), SetReserved(), ns3::Icmpv6OptionHeader::SetType(), SetValidTime(), and visualizer.core::start().
GetFlags()
uint8_t ns3::Icmpv6OptionPrefixInformation::GetFlags () const
Get the flags.
Returns
the flags.
Definition at line 1701 of file icmpv6-header.cc.
References m_flags, and NS_LOG_FUNCTION.
GetInstanceTypeId()
TypeId ns3::Icmpv6OptionPrefixInformation::GetInstanceTypeId () const virtual
Get the instance type ID.
Returns
instance type ID
Reimplemented from ns3::Icmpv6OptionHeader.
Definition at line 1651 of file icmpv6-header.cc.
References GetTypeId(), and NS_LOG_FUNCTION.
GetPreferredTime()
uint32_t ns3::Icmpv6OptionPrefixInformation::GetPreferredTime () const
Get the preferred time of the information.
Returns
preferred time
Definition at line 1725 of file icmpv6-header.cc.
References m_preferredTime, and NS_LOG_FUNCTION.
GetPrefix()
Ipv6Address ns3::Icmpv6OptionPrefixInformation::GetPrefix () const
Get the IPv6 prefix.
Returns
IPv6 prefix
Definition at line 1749 of file icmpv6-header.cc.
References m_prefix, and NS_LOG_FUNCTION.
GetPrefixLength()
uint8_t ns3::Icmpv6OptionPrefixInformation::GetPrefixLength () const
Get the prefix length.
Returns
prefix length
Definition at line 1688 of file icmpv6-header.cc.
References m_prefixLength, and NS_LOG_FUNCTION.
GetReserved()
uint32_t ns3::Icmpv6OptionPrefixInformation::GetReserved () const
Get the reserved field.
Returns
the reserved field (should be 0x00000000)
Definition at line 1737 of file icmpv6-header.cc.
References m_preferredTime, and NS_LOG_FUNCTION.
GetSerializedSize()
uint32_t ns3::Icmpv6OptionPrefixInformation::GetSerializedSize () const virtual
Get the serialized size.
Returns
serialized size
Reimplemented from ns3::Icmpv6OptionHeader.
Definition at line 1767 of file icmpv6-header.cc.
References NS_LOG_FUNCTION.
Referenced by Deserialize().
GetTypeId()
TypeId ns3::Icmpv6OptionPrefixInformation::GetTypeId () static
Get the UID of this class.
Returns
UID
Definition at line 1641 of file icmpv6-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
GetValidTime()
uint32_t ns3::Icmpv6OptionPrefixInformation::GetValidTime () const
Get the valid time of the information.
Returns
valid time
Definition at line 1713 of file icmpv6-header.cc.
References m_validTime, and NS_LOG_FUNCTION.
Print()
void ns3::Icmpv6OptionPrefixInformation::Print (std::ostream & os) const virtual
Print information.
Parameters
os output stream
Reimplemented from ns3::Icmpv6OptionHeader.
Definition at line 1761 of file icmpv6-header.cc.
References ns3::Icmpv6OptionHeader::GetLength(), ns3::Icmpv6OptionHeader::GetType(), m_prefix, and NS_LOG_FUNCTION.
Serialize()
void ns3::Icmpv6OptionPrefixInformation::Serialize (Buffer::Iterator start) const virtual
Serialize the packet.
Parameters
start start offset
Reimplemented from ns3::Icmpv6OptionHeader.
Definition at line 1773 of file icmpv6-header.cc.
References ns3::Ipv6Address::GetBytes(), ns3::Icmpv6OptionHeader::GetLength(), ns3::Icmpv6OptionHeader::GetType(), m_flags, m_preferredTime, m_prefix, m_prefixLength, m_reserved, m_validTime, NS_LOG_FUNCTION, visualizer.core::start(), ns3::Buffer::Iterator::Write(), ns3::Buffer::Iterator::WriteHtonU32(), and ns3::Buffer::Iterator::WriteU8().
SetFlags()
void ns3::Icmpv6OptionPrefixInformation::SetFlags (uint8_t flags)
Set the flags.
Parameters
flags the flags to set
Definition at line 1707 of file icmpv6-header.cc.
References m_flags, and NS_LOG_FUNCTION.
Referenced by Icmpv6OptionPrefixInformation(), Deserialize(), and ns3::Radvd::Send().
SetPreferredTime()
void ns3::Icmpv6OptionPrefixInformation::SetPreferredTime (uint32_t preferredTime)
Set the preferred time of the information.
Parameters
preferredTime preferred time
Definition at line 1731 of file icmpv6-header.cc.
References m_preferredTime, and NS_LOG_FUNCTION.
Referenced by Icmpv6OptionPrefixInformation(), Deserialize(), and ns3::Radvd::Send().
SetPrefix()
void ns3::Icmpv6OptionPrefixInformation::SetPrefix (Ipv6Address prefix)
Set the IPv6 prefix.
Parameters
prefix the IPv6 prefix
Definition at line 1755 of file icmpv6-header.cc.
References m_prefix, and NS_LOG_FUNCTION.
Referenced by Icmpv6OptionPrefixInformation(), Deserialize(), and ns3::Radvd::Send().
SetPrefixLength()
void ns3::Icmpv6OptionPrefixInformation::SetPrefixLength (uint8_t prefixLength)
Set the prefix length.
Parameters
prefixLength the prefix length
Definition at line 1694 of file icmpv6-header.cc.
References m_prefixLength, NS_ASSERT, and NS_LOG_FUNCTION.
Referenced by Icmpv6OptionPrefixInformation(), Deserialize(), and ns3::Radvd::Send().
SetReserved()
void ns3::Icmpv6OptionPrefixInformation::SetReserved (uint32_t reserved)
Set the reserved field (normally it will be 0x00000000).
Parameters
reserved reserved value
Definition at line 1743 of file icmpv6-header.cc.
References m_reserved, and NS_LOG_FUNCTION.
Referenced by Icmpv6OptionPrefixInformation(), and Deserialize().
SetValidTime()
void ns3::Icmpv6OptionPrefixInformation::SetValidTime (uint32_t validTime)
Set the valid time of the information.
Parameters
validTime valid time
Definition at line 1719 of file icmpv6-header.cc.
References m_validTime, and NS_LOG_FUNCTION.
Referenced by Icmpv6OptionPrefixInformation(), Deserialize(), and ns3::Radvd::Send().
Member Data Documentation
m_flags
uint8_t ns3::Icmpv6OptionPrefixInformation::m_flags private
The flags.
Definition at line 1614 of file icmpv6-header.h.
Referenced by GetFlags(), Serialize(), and SetFlags().
m_preferredTime
uint32_t ns3::Icmpv6OptionPrefixInformation::m_preferredTime private
The preferred time.
Definition at line 1624 of file icmpv6-header.h.
Referenced by GetPreferredTime(), GetReserved(), Serialize(), and SetPreferredTime().
m_prefix
Ipv6Address ns3::Icmpv6OptionPrefixInformation::m_prefix private
The prefix value.
Definition at line 1604 of file icmpv6-header.h.
Referenced by GetPrefix(), Print(), Serialize(), and SetPrefix().
m_prefixLength
uint8_t ns3::Icmpv6OptionPrefixInformation::m_prefixLength private
The length of the prefix.
Definition at line 1609 of file icmpv6-header.h.
Referenced by GetPrefixLength(), Serialize(), and SetPrefixLength().
m_reserved
uint32_t ns3::Icmpv6OptionPrefixInformation::m_reserved private
The reserved field.
Definition at line 1629 of file icmpv6-header.h.
Referenced by Serialize(), and SetReserved().
m_validTime
uint32_t ns3::Icmpv6OptionPrefixInformation::m_validTime private
The valid time.
Definition at line 1619 of file icmpv6-header.h.
Referenced by GetValidTime(), Serialize(), and SetValidTime().
The documentation for this class was generated from the following files:
src/internet/model/icmpv6-header.h
src/internet/model/icmpv6-header.cc