ns-3: AttributeTestCase< T > Class Template Reference
AttributeTestCase< T > Class Template Reference
Public Member Functions
AttributeTestCase (std::string description)
virtual ~AttributeTestCase ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
bool CheckGetCodePaths (Ptr< Object > p, std::string attributeName, std::string expectedString, T expectedValue)
virtual void DoRun (void)
Implementation to actually run this TestCase.
void DoRun (void)
Implementation to actually run this TestCase.
void DoRun (void)
Implementation to actually run this TestCase.
void DoRun (void)
Implementation to actually run this TestCase.
void DoRun (void)
Implementation to actually run this TestCase.
void DoRun (void)
Implementation to actually run this TestCase.
void DoRun (void)
Implementation to actually run this TestCase.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
template<typename T>
class AttributeTestCase< T >
Definition at line 358 of file attribute-test-suite.cc.
Constructor & Destructor Documentation
AttributeTestCase()
template<typename T > AttributeTestCase< T >::AttributeTestCase (std::string description)
Definition at line 371 of file attribute-test-suite.cc.
~AttributeTestCase()
template<typename T > AttributeTestCase< T >::~AttributeTestCase virtual
Definition at line 376 of file attribute-test-suite.cc.
Member Function Documentation
CheckGetCodePaths()
template<typename T > bool AttributeTestCase< T >::CheckGetCodePaths (Ptr< Object > p, std::string attributeName, std::string expectedString, T expectedValue) private
Definition at line 380 of file attribute-test-suite.cc.
References ns3::StringValue::Get(), and ns3::ObjectBase::GetAttributeFailSafe().
DoRun() [1/7]
template<typename T > virtual void AttributeTestCase< T >::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
DoRun() [2/7]
void AttributeTestCase< BooleanValue >::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 408 of file attribute-test-suite.cc.
References NS_TEST_ASSERT_MSG_EQ, NS_TEST_ASSERT_MSG_NE, ns3::ObjectBase::SetAttributeFailSafe(), ns3::Config::SetDefault(), and ns3::Config::SetDefaultFailSafe().
DoRun() [3/7]
void AttributeTestCase< IntegerValue >::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 486 of file attribute-test-suite.cc.
References NS_TEST_ASSERT_MSG_EQ, NS_TEST_ASSERT_MSG_NE, and ns3::ObjectBase::SetAttributeFailSafe().
DoRun() [4/7]
void AttributeTestCase< UintegerValue >::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 596 of file attribute-test-suite.cc.
References NS_TEST_ASSERT_MSG_EQ, NS_TEST_ASSERT_MSG_NE, and ns3::ObjectBase::SetAttributeFailSafe().
DoRun() [5/7]
void AttributeTestCase< DoubleValue >::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 667 of file attribute-test-suite.cc.
References NS_TEST_ASSERT_MSG_EQ, NS_TEST_ASSERT_MSG_NE, and ns3::ObjectBase::SetAttributeFailSafe().
DoRun() [6/7]
void AttributeTestCase< EnumValue >::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 693 of file attribute-test-suite.cc.
References NS_TEST_ASSERT_MSG_EQ, NS_TEST_ASSERT_MSG_NE, ns3::ObjectBase::SetAttributeFailSafe(), AttributeObjectTest::TEST_A, AttributeObjectTest::TEST_B, and AttributeObjectTest::TEST_C.
DoRun() [7/7]
void AttributeTestCase< TimeValue >::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 764 of file attribute-test-suite.cc.
References NS_TEST_ASSERT_MSG_EQ, NS_TEST_ASSERT_MSG_NE, ns3::Seconds(), and ns3::ObjectBase::SetAttributeFailSafe().
The documentation for this class was generated from the following file:
src/core/test/attribute-test-suite.cc