ns-3: TestBase.TestBaseClass Class Reference
TestBase.TestBaseClass Class Reference
TestBaseClass class.
Public Member Functions
def __init__ (self, argv, desc, mode)
Provide input argument list, description and mode of the suite being executed.
def override_cmds (self)
Can be used by importing suite to handle custom commands.
def parseargs (self, argv, desc)
Parses the commandline arguments.
def runtests (self, cmds)
Execute the tests.
Public Attributes
mode
my_env
options
outfile
Detailed Description
TestBaseClass class.
    Generic class for testing tools based on provided commands and test cases.
Definition at line 53 of file TestBase.py.
Constructor & Destructor Documentation
__init__()
def TestBase.TestBaseClass.__init__ (self, argv, desc, mode)
Provide input argument list, description and mode of the suite being executed.
Parameters
self this object
argv argument list
desc description
mode test mode
Returns
none
Definition at line 66 of file TestBase.py.
Member Function Documentation
override_cmds()
def TestBase.TestBaseClass.override_cmds (self)
Can be used by importing suite to handle custom commands.
Parameters
self this object
Returns
custom commands
Definition at line 102 of file TestBase.py.
References TestBase.TestBaseClass.options.
parseargs()
def TestBase.TestBaseClass.parseargs (self, argv, desc)
Parses the commandline arguments.
Parameters
self this object
argv argument list
desc description
Returns
command line arguments
Definition at line 82 of file TestBase.py.
References TestBase.TestBaseClass.outfile.
runtests()
def TestBase.TestBaseClass.runtests (self, cmds)
Execute the tests.
Parameters
self this object
cmds test commands
Returns
error code
Definition at line 110 of file TestBase.py.
References TestBase.TestBaseClass.my_env, TestBase.TestBaseClass.options, print, TestBase.print_case_in_file(), TestBase.print_cmds(), and TestBase.print_failed_cases().
Member Data Documentation
mode
TestBase.TestBaseClass.mode
mode
Definition at line 78 of file TestBase.py.
my_env
TestBase.TestBaseClass.my_env
os environment
Definition at line 75 of file TestBase.py.
Referenced by TestBase.TestBaseClass.runtests().
options
TestBase.TestBaseClass.options
options
Definition at line 80 of file TestBase.py.
Referenced by TestBase.TestBaseClass.override_cmds(), and TestBase.TestBaseClass.runtests().
outfile
TestBase.TestBaseClass.outfile
output file
Definition at line 79 of file TestBase.py.
Referenced by TestBase.TestBaseClass.parseargs().
The documentation for this class was generated from the following file:
utils/tests/TestBase.py