ns-3: ns3::AmsduSubframeHeader Class Reference
ns3::AmsduSubframeHeader Class Reference
Wifi Models
Headers for A-MSDU subframes.
#include "amsdu-subframe-header.h"
Public Member Functions
AmsduSubframeHeader ()
virtual ~AmsduSubframeHeader ()
uint32_t Deserialize (Buffer::Iterator start)
Mac48Address GetDestinationAddr (void) const
Get destination address function.
TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
uint16_t GetLength (void) const
Get length function.
uint32_t GetSerializedSize (void) const
Mac48Address GetSourceAddr (void) const
Get source address function.
void Print (std::ostream &os) const
void Serialize (Buffer::Iterator start) const
void SetDestinationAddr (Mac48Address to)
Set destination address function.
void SetLength (uint16_t length)
Set length function.
void SetSourceAddr (Mac48Address to)
Set source address function.
Public Member Functions inherited from ns3::Header
virtual ~Header ()
virtual uint32_t Deserialize (Buffer::Iterator start)=0
Deserialize the object from a buffer iterator.
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::Chunk
virtual uint32_t Deserialize (Buffer::Iterator start, Buffer::Iterator end)
Deserialize the object from a buffer iterator.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Header
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Chunk
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Attributes
Mac48Address m_da
destination address
uint16_t m_length
length in bytes
Mac48Address m_sa
source address
Additional Inherited Members
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Headers for A-MSDU subframes.
Definition at line 33 of file amsdu-subframe-header.h.
Constructor & Destructor Documentation
AmsduSubframeHeader()
ns3::AmsduSubframeHeader::AmsduSubframeHeader ()
Definition at line 45 of file amsdu-subframe-header.cc.
~AmsduSubframeHeader()
ns3::AmsduSubframeHeader::~AmsduSubframeHeader () virtual
Definition at line 50 of file amsdu-subframe-header.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::AmsduSubframeHeader::Deserialize (Buffer::Iterator start) virtual
Parameters
start an iterator which points to where the header should read from.
Returns
the number of bytes read.
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet. The data read is expected to match bit-for-bit the representation of this header in real networks.
Note that data is not actually removed from the buffer to which the iterator points. Both Packet::RemoveHeader() and Packet::PeekHeader() call Deserialize(), but only the RemoveHeader() has additional statements to remove the header bytes from the underlying buffer and associated metadata.
Implements ns3::Header.
Definition at line 69 of file amsdu-subframe-header.cc.
References ns3::Buffer::Iterator::GetDistanceFrom(), m_da, m_length, m_sa, ns3::ReadFrom(), ns3::Buffer::Iterator::ReadNtohU16(), and visualizer.core::start().
GetDestinationAddr()
Mac48Address ns3::AmsduSubframeHeader::GetDestinationAddr (void) const
Get destination address function.
Returns
the destination MAC address
Definition at line 103 of file amsdu-subframe-header.cc.
References m_da.
GetInstanceTypeId()
TypeId ns3::AmsduSubframeHeader::GetInstanceTypeId (void) const virtual
Get the most derived TypeId for this Object.
This method is typically implemented by ns3::Object::GetInstanceTypeId but some classes which derive from ns3::ObjectBase directly have to implement it themselves.
Returns
The TypeId associated to the most-derived type of this instance.
Implements ns3::ObjectBase.
Definition at line 40 of file amsdu-subframe-header.cc.
References GetTypeId().
GetLength()
uint16_t ns3::AmsduSubframeHeader::GetLength (void) const
Get length function.
Returns
the length in bytes
Definition at line 115 of file amsdu-subframe-header.cc.
References m_length.
Referenced by ns3::MsduAggregator::Deaggregate().
GetSerializedSize()
uint32_t ns3::AmsduSubframeHeader::GetSerializedSize (void) const virtual
Returns
the expected size of the header.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. This method should return the number of bytes which are needed to store the full header data by Serialize.
Implements ns3::Header.
Definition at line 55 of file amsdu-subframe-header.cc.
GetSourceAddr()
Mac48Address ns3::AmsduSubframeHeader::GetSourceAddr (void) const
Get source address function.
Returns
the source MAC address
Definition at line 109 of file amsdu-subframe-header.cc.
References m_sa.
GetTypeId()
TypeId ns3::AmsduSubframeHeader::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 29 of file amsdu-subframe-header.cc.
References ns3::TypeId::SetParent().
Referenced by GetInstanceTypeId().
Print()
void ns3::AmsduSubframeHeader::Print (std::ostream & os) const virtual
Parameters
os output stream This method is used by Packet::Print to print the content of a header as ascii data to a c++ output stream. Although the header is free to format its output as it wishes, it is recommended to follow a few rules to integrate with the packet pretty printer: start with flags, small field values located between a pair of parens. Values should be separated by whitespace. Follow the parens with the important fields, separated by whitespace. i.e.: (field1 val1 field2 val2 field3 val3) field4 val4 field5 val5
Implements ns3::Header.
Definition at line 79 of file amsdu-subframe-header.cc.
References m_da, m_length, and m_sa.
Serialize()
void ns3::AmsduSubframeHeader::Serialize (Buffer::Iterator start) const virtual
Parameters
start an iterator which points to where the header should be written.
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet. The data written is expected to match bit-for-bit the representation of this header in a real network.
Implements ns3::Header.
Definition at line 61 of file amsdu-subframe-header.cc.
References m_da, m_length, m_sa, ns3::Buffer::Iterator::WriteHtonU16(), and ns3::WriteTo().
SetDestinationAddr()
void ns3::AmsduSubframeHeader::SetDestinationAddr (Mac48Address to)
Set destination address function.
Parameters
to the destination MAC address
Definition at line 85 of file amsdu-subframe-header.cc.
References m_da.
Referenced by ns3::WifiMacQueueItem::DoAggregate().
SetLength()
void ns3::AmsduSubframeHeader::SetLength (uint16_t length)
Set length function.
Parameters
length the length in bytes
Definition at line 97 of file amsdu-subframe-header.cc.
References m_length.
Referenced by ns3::WifiMacQueueItem::DoAggregate().
SetSourceAddr()
void ns3::AmsduSubframeHeader::SetSourceAddr (Mac48Address to)
Set source address function.
Parameters
to the source MAC address
Definition at line 91 of file amsdu-subframe-header.cc.
References m_sa.
Referenced by ns3::WifiMacQueueItem::DoAggregate().
Member Data Documentation
m_da
Mac48Address ns3::AmsduSubframeHeader::m_da private
destination address
Definition at line 82 of file amsdu-subframe-header.h.
Referenced by Deserialize(), GetDestinationAddr(), Print(), Serialize(), and SetDestinationAddr().
m_length
uint16_t ns3::AmsduSubframeHeader::m_length private
length in bytes
Definition at line 84 of file amsdu-subframe-header.h.
Referenced by Deserialize(), GetLength(), Print(), Serialize(), and SetLength().
m_sa
Mac48Address ns3::AmsduSubframeHeader::m_sa private
source address
Definition at line 83 of file amsdu-subframe-header.h.
Referenced by Deserialize(), GetSourceAddr(), Print(), Serialize(), and SetSourceAddr().
The documentation for this class was generated from the following files:
src/wifi/model/amsdu-subframe-header.h
src/wifi/model/amsdu-subframe-header.cc