ns-3: ns3::lorawan::OneShotSenderHelper Class Reference
ns3::lorawan::OneShotSenderHelper Class Reference
This class can be used to install OneShotSender applications on multiple nodes at once.
#include "one-shot-sender-helper.h"
Public Member Functions
OneShotSenderHelper ()
~OneShotSenderHelper ()
ApplicationContainer Install (NodeContainer c) const
ApplicationContainer Install (Ptr< Node > node) const
void SetAttribute (std::string name, const AttributeValue &value)
void SetSendTime (Time sendTime)
Private Member Functions
Ptr< Application > InstallPriv (Ptr< Node > node) const
Private Attributes
ObjectFactory m_factory
Time m_sendTime
Time at which the OneShotSender will be configured to.
Detailed Description
This class can be used to install OneShotSender applications on multiple nodes at once.
Definition at line 41 of file one-shot-sender-helper.h.
Constructor & Destructor Documentation
OneShotSenderHelper()
ns3::lorawan::OneShotSenderHelper::OneShotSenderHelper ()
Definition at line 34 of file one-shot-sender-helper.cc.
References m_factory, and ns3::ObjectFactory::SetTypeId().
~OneShotSenderHelper()
ns3::lorawan::OneShotSenderHelper::~OneShotSenderHelper ()
Definition at line 39 of file one-shot-sender-helper.cc.
Member Function Documentation
Install() [1/2]
ApplicationContainer ns3::lorawan::OneShotSenderHelper::Install (NodeContainer c) const
Definition at line 63 of file one-shot-sender-helper.cc.
References ns3::ApplicationContainer::Add(), ns3::NodeContainer::Begin(), ns3::NodeContainer::End(), and InstallPriv().
Install() [2/2]
ApplicationContainer ns3::lorawan::OneShotSenderHelper::Install (Ptr< Node > node) const
Definition at line 57 of file one-shot-sender-helper.cc.
References InstallPriv().
InstallPriv()
Ptr< Application > ns3::lorawan::OneShotSenderHelper::InstallPriv (Ptr< Node > node) const private
Definition at line 75 of file one-shot-sender-helper.cc.
References ns3::Node::AddApplication(), ns3::ObjectFactory::Create(), ns3::Node::GetId(), m_factory, m_sendTime, and NS_LOG_FUNCTION.
Referenced by Install().
SetAttribute()
void ns3::lorawan::OneShotSenderHelper::SetAttribute (std::string name, const AttributeValue & value)
Definition at line 50 of file one-shot-sender-helper.cc.
References m_factory, and ns3::ObjectFactory::Set().
SetSendTime()
void ns3::lorawan::OneShotSenderHelper::SetSendTime (Time sendTime)
Definition at line 44 of file one-shot-sender-helper.cc.
References m_sendTime.
Member Data Documentation
m_factory
ObjectFactory ns3::lorawan::OneShotSenderHelper::m_factory private
Definition at line 59 of file one-shot-sender-helper.h.
Referenced by OneShotSenderHelper(), InstallPriv(), and SetAttribute().
m_sendTime
Time ns3::lorawan::OneShotSenderHelper::m_sendTime private
Time at which the OneShotSender will be configured to.
Definition at line 61 of file one-shot-sender-helper.h.
Referenced by InstallPriv(), and SetSendTime().
The documentation for this class was generated from the following files:
src/lorawan/helper/one-shot-sender-helper.h
src/lorawan/helper/one-shot-sender-helper.cc