ns-3: LteCqiGenerationTestCase Class Reference
LteCqiGenerationTestCase Class Reference
LTE Models » lte module tests | Test suites
This is the test case for testing different configuration of CQI generation. The topology consists of the two UEs and two eNbs. UEs have the same position, while eNodeBs are at the same distance from both UEs. The checking whether CQI is generated properly for two different cases: when PDCCH is used for the CQI estimation and when PDSCH is used for CQI estimation.
#include "lte-test-cqi-generation.h"
Public Member Functions
LteCqiGenerationTestCase (std::string name, bool usePdcchForCqiGeneration, uint16_t dlMcs, uint16_t ulMcs)
Constructor.
virtual ~LteCqiGenerationTestCase ()
void DlScheduling (DlSchedulingCallbackInfo dlInfo)
DL Scheduling function.
void UlScheduling (uint32_t frameNo, uint32_t subframeNo, uint16_t rnti, uint8_t mcs, uint16_t sizeTb)
UL Scheduling function.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
virtual void DoRun (void)
Implementation to actually run this TestCase.
Private Attributes
uint16_t m_dlMcs
the DL MCS
uint16_t m_ulMcs
the UL MCS
bool m_usePdschForCqiGeneration
use PDCCH for CQI generation
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
This is the test case for testing different configuration of CQI generation. The topology consists of the two UEs and two eNbs. UEs have the same position, while eNodeBs are at the same distance from both UEs. The checking whether CQI is generated properly for two different cases: when PDCCH is used for the CQI estimation and when PDSCH is used for CQI estimation.
Definition at line 53 of file lte-test-cqi-generation.h.
Constructor & Destructor Documentation
LteCqiGenerationTestCase()
LteCqiGenerationTestCase::LteCqiGenerationTestCase (std::string name, bool usePdcchForCqiGeneration, uint16_t dlMcs, uint16_t ulMcs)
Constructor.
Parameters
name reference name
usePdcchForCqiGeneration use PDCCH for CQI generation
dlMcs DL MCS
ulMcs UL MCS
Definition at line 109 of file lte-test-cqi-generation.cc.
References m_usePdschForCqiGeneration, and NS_LOG_INFO.
~LteCqiGenerationTestCase()
LteCqiGenerationTestCase::~LteCqiGenerationTestCase () virtual
Definition at line 119 of file lte-test-cqi-generation.cc.
Member Function Documentation
DlScheduling()
void LteCqiGenerationTestCase::DlScheduling (DlSchedulingCallbackInfo dlInfo)
DL Scheduling function.
Parameters
dlInfo DL info
Definition at line 124 of file lte-test-cqi-generation.cc.
References m_dlMcs, ns3::DlSchedulingCallbackInfo::mcsTb1, ns3::MilliSeconds(), ns3::Now(), and NS_TEST_ASSERT_MSG_EQ.
Referenced by LteTestDlSchedulingCallback().
DoRun()
void LteCqiGenerationTestCase::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 147 of file lte-test-cqi-generation.cc.
References ns3::LteHelper::ActivateDataRadioBearer(), ns3::NetDeviceContainer::Add(), ns3::ListPositionAllocator::Add(), ns3::LteHelper::Attach(), ns3::Config::Connect(), ns3::NodeContainer::Create(), ns3::NetDeviceContainer::Get(), ns3::NodeContainer::Get(), ns3::LteHelper::InstallEnbDevice(), ns3::LteHelper::InstallUeDevice(), LteTestDlSchedulingCallback(), LteTestUlSchedulingCallback(), m_usePdschForCqiGeneration, ns3::MakeBoundCallback(), third::mobility, NS_LOG_DEBUG, ns3::Config::Reset(), ns3::Seconds(), ns3::Config::SetDefault(), ns3::LteHelper::SetFfrAlgorithmAttribute(), ns3::LteHelper::SetFfrAlgorithmType(), ns3::LteHelper::SetSchedulerAttribute(), and ns3::LteHelper::SetSchedulerType().
UlScheduling()
void LteCqiGenerationTestCase::UlScheduling (uint32_t frameNo, uint32_t subframeNo, uint16_t rnti, uint8_t mcs, uint16_t sizeTb)
UL Scheduling function.
Parameters
frameNo frame number
subframeNo subframe number
rnti the RNTI
mcs the MCS
sizeTb size
Definition at line 135 of file lte-test-cqi-generation.cc.
References m_ulMcs, ns3::MilliSeconds(), ns3::Now(), and NS_TEST_ASSERT_MSG_EQ.
Referenced by LteTestUlSchedulingCallback().
Member Data Documentation
m_dlMcs
uint16_t LteCqiGenerationTestCase::m_dlMcs private
the DL MCS
Definition at line 89 of file lte-test-cqi-generation.h.
Referenced by DlScheduling().
m_ulMcs
uint16_t LteCqiGenerationTestCase::m_ulMcs private
the UL MCS
Definition at line 90 of file lte-test-cqi-generation.h.
Referenced by UlScheduling().
m_usePdschForCqiGeneration
bool LteCqiGenerationTestCase::m_usePdschForCqiGeneration private
use PDCCH for CQI generation
Definition at line 88 of file lte-test-cqi-generation.h.
Referenced by LteCqiGenerationTestCase(), and DoRun().
The documentation for this class was generated from the following files:
src/lte/test/lte-test-cqi-generation.h
src/lte/test/lte-test-cqi-generation.cc