ns-3: ns3::GridBuildingAllocator Class Reference
ns3::GridBuildingAllocator Class Reference
Allocate buildings on a rectangular 2d grid.
#include "building-allocator.h"
Public Member Functions
GridBuildingAllocator ()
virtual ~GridBuildingAllocator ()
BuildingContainer Create (uint32_t n) const
Create a set of buildings allocated on a grid.
void SetBuildingAttribute (std::string n, const AttributeValue &v)
Set an attribute to be used for each new building to be created.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void PushAttributes () const
Private Attributes
ObjectFactory m_buildingFactory
uint32_t m_current
double m_deltaX
double m_deltaY
double m_height
enum GridPositionAllocator::LayoutType m_layoutType
double m_lengthX
double m_lengthY
Ptr< GridPositionAllocator > m_lowerLeftPositionAllocator
uint32_t m_n
Ptr< GridPositionAllocator > m_upperRightPositionAllocator
double m_xMin
double m_yMin
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Allocate buildings on a rectangular 2d grid.
This class allows to create a set of buildings positioned on a rectangular 2D grid. Under the hood, this class uses two instances of GridPositionAllocator.
Definition at line 44 of file building-allocator.h.
Constructor & Destructor Documentation
GridBuildingAllocator()
ns3::GridBuildingAllocator::GridBuildingAllocator ()
Definition at line 36 of file building-allocator.cc.
References m_buildingFactory, m_lowerLeftPositionAllocator, m_upperRightPositionAllocator, and ns3::ObjectFactory::SetTypeId().
~GridBuildingAllocator()
ns3::GridBuildingAllocator::~GridBuildingAllocator () virtual
Definition at line 44 of file building-allocator.cc.
Member Function Documentation
Create()
BuildingContainer ns3::GridBuildingAllocator::Create (uint32_t n) const
Create a set of buildings allocated on a grid.
Parameters
n the number of buildings to create
Returns
the BuildingContainer that contains the newly created buildings
Definition at line 104 of file building-allocator.cc.
References ns3::BuildingContainer::Add(), ns3::ObjectFactory::Create(), m_buildingFactory, m_current, m_height, m_lowerLeftPositionAllocator, m_upperRightPositionAllocator, sample-rng-plot::n, NS_LOG_FUNCTION, NS_LOG_LOGIC(), PushAttributes(), and ns3::ObjectFactory::Set().
Referenced by FemtocellBlockAllocator::Create().
GetTypeId()
TypeId ns3::GridBuildingAllocator::GetTypeId (void) static
Definition at line 49 of file building-allocator.cc.
References ns3::GridPositionAllocator::COLUMN_FIRST, m_deltaX, m_deltaY, m_height, m_layoutType, m_lengthX, m_lengthY, m_n, m_xMin, m_yMin, ns3::MakeDoubleAccessor(), ns3::MakeEnumAccessor(), ns3::MakeEnumChecker(), ns3::MakeUintegerAccessor(), ns3::GridPositionAllocator::ROW_FIRST, and ns3::TypeId::SetParent().
PushAttributes()
void ns3::GridBuildingAllocator::PushAttributes () const private
Definition at line 125 of file building-allocator.cc.
References m_deltaX, m_deltaY, m_layoutType, m_lengthX, m_lengthY, m_lowerLeftPositionAllocator, m_n, m_upperRightPositionAllocator, m_xMin, m_yMin, and NS_LOG_FUNCTION.
Referenced by Create().
SetBuildingAttribute()
void ns3::GridBuildingAllocator::SetBuildingAttribute (std::string n, const AttributeValue & v)
Set an attribute to be used for each new building to be created.
Parameters
n attribute name
v attribute value
Definition at line 97 of file building-allocator.cc.
References m_buildingFactory, sample-rng-plot::n, NS_LOG_FUNCTION, and ns3::ObjectFactory::Set().
Referenced by FemtocellBlockAllocator::Create().
Member Data Documentation
m_buildingFactory
ObjectFactory ns3::GridBuildingAllocator::m_buildingFactory mutable private
Definition at line 84 of file building-allocator.h.
Referenced by GridBuildingAllocator(), Create(), and SetBuildingAttribute().
m_current
uint32_t ns3::GridBuildingAllocator::m_current mutable private
Definition at line 73 of file building-allocator.h.
Referenced by Create().
m_deltaX
double ns3::GridBuildingAllocator::m_deltaX private
Definition at line 80 of file building-allocator.h.
Referenced by GetTypeId(), and PushAttributes().
m_deltaY
double ns3::GridBuildingAllocator::m_deltaY private
Definition at line 81 of file building-allocator.h.
Referenced by GetTypeId(), and PushAttributes().
m_height
double ns3::GridBuildingAllocator::m_height private
Definition at line 82 of file building-allocator.h.
Referenced by Create(), and GetTypeId().
m_layoutType
enum GridPositionAllocator::LayoutType ns3::GridBuildingAllocator::m_layoutType private
Definition at line 73 of file building-allocator.h.
Referenced by GetTypeId(), and PushAttributes().
m_lengthX
double ns3::GridBuildingAllocator::m_lengthX private
Definition at line 78 of file building-allocator.h.
Referenced by GetTypeId(), and PushAttributes().
m_lengthY
double ns3::GridBuildingAllocator::m_lengthY private
Definition at line 79 of file building-allocator.h.
Referenced by GetTypeId(), and PushAttributes().
m_lowerLeftPositionAllocator
Ptr<GridPositionAllocator> ns3::GridBuildingAllocator::m_lowerLeftPositionAllocator private
Definition at line 85 of file building-allocator.h.
Referenced by GridBuildingAllocator(), Create(), and PushAttributes().
m_n
uint32_t ns3::GridBuildingAllocator::m_n private
Definition at line 77 of file building-allocator.h.
Referenced by GetTypeId(), and PushAttributes().
m_upperRightPositionAllocator
Ptr<GridPositionAllocator> ns3::GridBuildingAllocator::m_upperRightPositionAllocator private
Definition at line 86 of file building-allocator.h.
Referenced by GridBuildingAllocator(), Create(), and PushAttributes().
m_xMin
double ns3::GridBuildingAllocator::m_xMin private
Definition at line 75 of file building-allocator.h.
Referenced by GetTypeId(), and PushAttributes().
m_yMin
double ns3::GridBuildingAllocator::m_yMin private
Definition at line 76 of file building-allocator.h.
Referenced by GetTypeId(), and PushAttributes().
The documentation for this class was generated from the following files:
src/buildings/helper/building-allocator.h
src/buildings/helper/building-allocator.cc