ns-3: ns3::EnbRrcMemberLteEnbCmacSapUser Class Reference
ns3::EnbRrcMemberLteEnbCmacSapUser Class Reference
Class for forwarding CMAC SAP User functions.
Public Member Functions
EnbRrcMemberLteEnbCmacSapUser (LteEnbRrc *rrc, uint8_t componentCarrierId)
Constructor.
virtual uint16_t AllocateTemporaryCellRnti ()
request the allocation of a Temporary C-RNTI
virtual bool IsRandomAccessCompleted (uint16_t rnti)
Is random access completed function.
virtual void NotifyLcConfigResult (uint16_t rnti, uint8_t lcid, bool success)
notify the result of the last LC config operation
virtual void RrcConfigurationUpdateInd (UeConfig params)
Notify the RRC of a UE config updated requested by the MAC (normally, by the scheduler)
Public Member Functions inherited from ns3::LteEnbCmacSapUser
virtual ~LteEnbCmacSapUser ()
Private Attributes
uint8_t m_componentCarrierId
Component carrier ID.
LteEnbRrc * m_rrc
the RRC
Detailed Description
Class for forwarding CMAC SAP User functions.
Definition at line 62 of file lte-enb-rrc.cc.
Constructor & Destructor Documentation
EnbRrcMemberLteEnbCmacSapUser()
ns3::EnbRrcMemberLteEnbCmacSapUser::EnbRrcMemberLteEnbCmacSapUser (LteEnbRrc * rrc, uint8_t componentCarrierId)
Constructor.
Parameters
rrc ENB RRC
componentCarrierId
Definition at line 83 of file lte-enb-rrc.cc.
Member Function Documentation
AllocateTemporaryCellRnti()
uint16_t ns3::EnbRrcMemberLteEnbCmacSapUser::AllocateTemporaryCellRnti () virtual
request the allocation of a Temporary C-RNTI
Returns
the T-C-RNTI
Implements ns3::LteEnbCmacSapUser.
Definition at line 90 of file lte-enb-rrc.cc.
References ns3::LteEnbRrc::DoAllocateTemporaryCellRnti(), m_componentCarrierId, and m_rrc.
IsRandomAccessCompleted()
bool ns3::EnbRrcMemberLteEnbCmacSapUser::IsRandomAccessCompleted (uint16_t rnti) virtual
Is random access completed function.
This method is executed to decide if the non contention based preamble has to be reused or not upon preamble expiry. If the random access in connected mode is completed, then the preamble can be reused by other UEs. If not, the same UE retains the preamble and other available preambles are assigned to the required UEs.
Parameters
rnti the C-RNTI identifying the user
Returns
true if the random access in connected mode is completed
Implements ns3::LteEnbCmacSapUser.
Definition at line 108 of file lte-enb-rrc.cc.
References ns3::LteEnbRrc::IsRandomAccessCompleted(), and m_rrc.
NotifyLcConfigResult()
void ns3::EnbRrcMemberLteEnbCmacSapUser::NotifyLcConfigResult (uint16_t rnti, uint8_t lcid, bool success) virtual
notify the result of the last LC config operation
Parameters
rnti the rnti of the user
lcid the logical channel id
success true if the operation was successful, false otherwise
Implements ns3::LteEnbCmacSapUser.
Definition at line 96 of file lte-enb-rrc.cc.
References ns3::LteEnbRrc::DoNotifyLcConfigResult(), and m_rrc.
RrcConfigurationUpdateInd()
void ns3::EnbRrcMemberLteEnbCmacSapUser::RrcConfigurationUpdateInd (UeConfig params) virtual
Notify the RRC of a UE config updated requested by the MAC (normally, by the scheduler)
Parameters
params
Implements ns3::LteEnbCmacSapUser.
Definition at line 102 of file lte-enb-rrc.cc.
References ns3::LteEnbRrc::DoRrcConfigurationUpdateInd(), m_rrc, and aloha::params.
Member Data Documentation
m_componentCarrierId
uint8_t ns3::EnbRrcMemberLteEnbCmacSapUser::m_componentCarrierId private
Component carrier ID.
Definition at line 80 of file lte-enb-rrc.cc.
Referenced by AllocateTemporaryCellRnti().
m_rrc
LteEnbRrc* ns3::EnbRrcMemberLteEnbCmacSapUser::m_rrc private
the RRC
Definition at line 79 of file lte-enb-rrc.cc.
Referenced by AllocateTemporaryCellRnti(), IsRandomAccessCompleted(), NotifyLcConfigResult(), and RrcConfigurationUpdateInd().
The documentation for this class was generated from the following file:
src/lte/model/lte-enb-rrc.cc