ns-3: Ipv6ForwardingTest Class Reference
Ipv6ForwardingTest Class Reference
Internet » internet module tests | Test suites
IPv6 Forwarding Test.
Public Member Functions
Ipv6ForwardingTest ()
virtual void DoRun (void)
Implementation to actually run this TestCase.
void ReceivePkt (Ptr< Socket > socket)
Receive data.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Private Member Functions
void DoSendData (Ptr< Socket > socket, std::string to)
Send data.
void SendData (Ptr< Socket > socket, std::string to)
Send data.
Private Attributes
Ptr< Packet > m_receivedPacket
Received packet.
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
IPv6 Forwarding Test.
Definition at line 54 of file ipv6-forwarding-test.cc.
Constructor & Destructor Documentation
Ipv6ForwardingTest()
Ipv6ForwardingTest::Ipv6ForwardingTest ()
Definition at line 82 of file ipv6-forwarding-test.cc.
Member Function Documentation
DoRun()
void Ipv6ForwardingTest::DoRun (void) virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 116 of file ipv6-forwarding-test.cc.
References ns3::Ipv6::AddAddress(), ns3::SocketFactory::CreateSocket(), ns3::NetDeviceContainer::Get(), ns3::Ipv6::GetInterfaceForDevice(), ns3::Object::GetObject(), ns3::Ipv6::GetRoutingProtocol(), ns3::Packet::GetSize(), ns3::SimpleNetDeviceHelper::Install(), ns3::InternetStackHelper::Install(), m_receivedPacket, ns3::MakeCallback(), first::nodes, NS_TEST_EXPECT_MSG_EQ, ReceivePkt(), ns3::Packet::RemoveAllByteTags(), SendData(), ns3::Socket::SetAllowBroadcast(), ns3::ObjectBase::SetAttribute(), ns3::Ipv6StaticRouting::SetDefaultRoute(), and ns3::SimpleNetDeviceHelper::SetNetDevicePointToPointMode().
DoSendData()
void Ipv6ForwardingTest::DoSendData (Ptr< Socket > socket, std::string to) private
Send data.
Parameters
socket The sending socket.
to Destination address.
Definition at line 99 of file ipv6-forwarding-test.cc.
References NS_TEST_EXPECT_MSG_EQ, and ns3::Socket::SendTo().
Referenced by SendData().
ReceivePkt()
void Ipv6ForwardingTest::ReceivePkt (Ptr< Socket > socket)
Receive data.
Parameters
socket The receiving socket.
Definition at line 87 of file ipv6-forwarding-test.cc.
References ns3::Socket::GetRxAvailable(), ns3::Packet::GetSize(), m_receivedPacket, max, NS_ASSERT, and ns3::Socket::Recv().
Referenced by DoRun().
SendData()
void Ipv6ForwardingTest::SendData (Ptr< Socket > socket, std::string to) private
Send data.
Parameters
socket The sending socket.
to Destination address.
Definition at line 107 of file ipv6-forwarding-test.cc.
References DoSendData(), ns3::Node::GetId(), ns3::Socket::GetNode(), m_receivedPacket, and ns3::Seconds().
Referenced by DoRun().
Member Data Documentation
m_receivedPacket
Ptr<Packet> Ipv6ForwardingTest::m_receivedPacket private
Received packet.
Definition at line 56 of file ipv6-forwarding-test.cc.
Referenced by DoRun(), ReceivePkt(), and SendData().
The documentation for this class was generated from the following file:
src/internet/test/ipv6-forwarding-test.cc