ns-3: Emitter Class Reference
Emitter Class Reference
Public Member Functions
Emitter ()
Emitter ()
Emitter ()
Emitter ()
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
static TypeId GetTypeId (void)
Register this type.
static TypeId GetTypeId (void)
Register this type.
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
void Count (void)
void Count (void)
void Count (void)
void DoInitialize (void)
Initialize() implementation.
void DoInitialize (void)
Initialize() implementation.
void DoInitialize (void)
Initialize() implementation.
void DoInitialize (void)
Initialize() implementation.
void Emit (void)
void Emit (void)
Private Attributes
TracedValue< double > m_counter
TracedValue< uint32_t > m_counter
TracedValue< Time > m_interval
Time m_last
Ptr< ExponentialRandomVariable > m_var
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 38 of file double-probe-example.cc.
Constructor & Destructor Documentation
Emitter() [1/4]
Emitter::Emitter ()
Definition at line 74 of file double-probe-example.cc.
References NS_LOG_FUNCTION.
Emitter() [2/4]
Emitter::Emitter ()
Emitter() [3/4]
Emitter::Emitter ()
Emitter() [4/4]
Emitter::Emitter ()
Member Function Documentation
Count() [1/3]
void Emitter::Count (void) private
Definition at line 98 of file double-probe-example.cc.
References ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), ns3::Seconds(), and ns3::DoubleProbe::SetValueByPath().
Referenced by DoInitialize().
Count() [2/3]
void Emitter::Count (void) private
Count() [3/3]
void Emitter::Count (void) private
DoInitialize() [1/4]
void Emitter::DoInitialize (void) private virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Definition at line 82 of file double-probe-example.cc.
References Count(), Emit(), NS_LOG_FUNCTION, ns3::Simulator::Schedule(), and ns3::Seconds().
DoInitialize() [2/4]
void Emitter::DoInitialize (void) private virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
DoInitialize() [3/4]
void Emitter::DoInitialize (void) private virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
DoInitialize() [4/4]
void Emitter::DoInitialize (void) private virtual
Initialize() implementation.
This method is called only once by Initialize(). If the user calls Initialize() multiple times, DoInitialize() is called only the first time.
Subclasses are expected to override this method and chain up to their parent's implementation once they are done. It is safe to call GetObject() and AggregateObject() from within this method.
Reimplemented from ns3::Object.
Emit() [1/2]
void Emitter::Emit (void) private
Definition at line 90 of file double-probe-example.cc.
References ns3::Simulator::Now(), NS_LOG_DEBUG, NS_LOG_FUNCTION, ns3::Simulator::Schedule(), and ns3::Seconds().
Referenced by DoInitialize().
Emit() [2/2]
void Emitter::Emit (void) private
GetTypeId() [1/4]
TypeId Emitter::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Definition at line 60 of file double-probe-example.cc.
References m_counter, ns3::MakeTraceSourceAccessor(), and ns3::TypeId::SetParent().
GetTypeId() [2/4]
static TypeId Emitter::GetTypeId (void) static
Register this type.
Returns
The TypeId.
GetTypeId() [3/4]
static TypeId Emitter::GetTypeId (void) static
Register this type.
Returns
The TypeId.
GetTypeId() [4/4]
static TypeId Emitter::GetTypeId (void) static
Register this type.
Returns
The TypeId.
Member Data Documentation
m_counter [1/2]
TracedValue< uint32_t > Emitter::m_counter private
Definition at line 52 of file double-probe-example.cc.
Referenced by GetTypeId().
m_counter [2/2]
TracedValue<uint32_t> Emitter::m_counter private
Definition at line 55 of file file-helper-example.cc.
m_interval
TracedValue<Time> Emitter::m_interval private
Definition at line 67 of file time-probe-example.cc.
m_last
Time Emitter::m_last private
Definition at line 68 of file time-probe-example.cc.
m_var
Ptr< ExponentialRandomVariable > Emitter::m_var private
Definition at line 53 of file double-probe-example.cc.
The documentation for this class was generated from the following files:
src/stats/examples/double-probe-example.cc
src/stats/examples/file-helper-example.cc
src/stats/examples/gnuplot-helper-example.cc
src/stats/examples/time-probe-example.cc