ns-3: ns3::BSLinkManager Class Reference
ns3::BSLinkManager Class Reference
WiMAX Models
#include "bs-link-manager.h"
Public Member Functions
BSLinkManager (Ptr< BaseStationNetDevice > bs)
Constructor.
~BSLinkManager (void)
uint8_t CalculateRangingOppsToAllocate (void)
void ProcessRangingRequest (Cid cid, RngReq rngreq)
process a ranging request message
uint64_t SelectDlChannel (void)
void VerifyInvitedRanging (Cid cid, uint8_t uiuc)
Verifies at the end of an invited ranging interval if SS sent ranging message in it or not.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
BSLinkManager (const BSLinkManager &)
copy constructor (disabled)
void AbortRanging (Cid cid, RngRsp *rngrsp, SSRecord *ssRecord, bool isNewSS)
Abort ranging function.
void AcceptRanging (Cid cid, RngRsp *rngrsp, SSRecord *ssRecord)
Accept ranging function.
bool ChangeDlChannel (void)
Change DL channel function.
void ContinueRanging (Cid cid, RngRsp *rngrsp, SSRecord *ssRecord)
Continue ranging function.
void DeallocateCids (Cid cid)
Deallocate CIDs function.
uint32_t GetNewDlChannel (void)
Get new DL channel function.
uint8_t GetSignalQuality (void)
Get signal quality function.
bool IsRangingAcceptable (void)
Is ranging acceptable function.
BSLinkManager & operator= (const BSLinkManager &)
assignment operator (disabled)
void PerformInitialRanging (Cid cid, RngReq *rngreq, RngRsp *rngrsp)
Perform initial ranging function.
void PerformInvitedRanging (Cid cid, RngRsp *rngrsp)
Perform inivted ranging function.
void PerformRanging (Cid cid, RngReq rngreq)
Perform ranging function.
void ScheduleRngRspMessage (Cid cid, RngRsp *rngrsp)
Schedule range response message function.
void SetParametersToAdjust (RngRsp *rngrsp)
Set parameters to adjust function.
Private Attributes
Ptr< BaseStationNetDevice > m_bs
base station
uint32_t m_signalQuality
signal quality
uint8_t m_signalQualityThreshold
signal quality threshold
int tries
variable to test multiple RNG-REQ by the SS for example undecodable at BS or lost RNG-RSP
Additional Inherited Members
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
Definition at line 38 of file bs-link-manager.h.
Constructor & Destructor Documentation
BSLinkManager() [1/2]
ns3::BSLinkManager::BSLinkManager (Ptr< BaseStationNetDevice > bs)
Constructor.
Parameters
bs base station device
Definition at line 49 of file bs-link-manager.cc.
References tries.
~BSLinkManager()
ns3::BSLinkManager::~BSLinkManager (void)
Definition at line 57 of file bs-link-manager.cc.
References m_bs.
BSLinkManager() [2/2]
ns3::BSLinkManager::BSLinkManager (const BSLinkManager &) private
copy constructor (disabled)
Member Function Documentation
AbortRanging()
void ns3::BSLinkManager::AbortRanging (Cid cid, RngRsp * rngrsp, SSRecord * ssRecord, bool isNewSS) private
Abort ranging function.
Parameters
cid the CID
rngrsp the ranging response
ssRecord the SS record
isNewSS true if a new SS
Definition at line 271 of file bs-link-manager.cc.
References DeallocateCids(), ns3::SSRecord::DisablePollForRanging(), ns3::WimaxNetDevice::RANGING_STATUS_ABORT, ScheduleRngRspMessage(), ns3::SSRecord::SetRangingStatus(), and ns3::RngRsp::SetRangStatus().
Referenced by PerformInitialRanging(), PerformInvitedRanging(), and VerifyInvitedRanging().
AcceptRanging()
void ns3::BSLinkManager::AcceptRanging (Cid cid, RngRsp * rngrsp, SSRecord * ssRecord) private
Accept ranging function.
Parameters
cid the CID
rngrsp the ranging response
ssRecord the SS record
Definition at line 286 of file bs-link-manager.cc.
References ns3::SSRecord::DisablePollForRanging(), ns3::WimaxNetDevice::RANGING_STATUS_SUCCESS, ScheduleRngRspMessage(), ns3::SSRecord::SetRangingStatus(), and ns3::RngRsp::SetRangStatus().
Referenced by PerformInitialRanging(), and PerformInvitedRanging().
CalculateRangingOppsToAllocate()
uint8_t ns3::BSLinkManager::CalculateRangingOppsToAllocate (void)
Returns
the ranging opportunities to allocate
Definition at line 63 of file bs-link-manager.cc.
ChangeDlChannel()
bool ns3::BSLinkManager::ChangeDlChannel (void) private
Change DL channel function.
Returns
true if the DL channel changed
Definition at line 341 of file bs-link-manager.cc.
Referenced by PerformInitialRanging().
ContinueRanging()
void ns3::BSLinkManager::ContinueRanging (Cid cid, RngRsp * rngrsp, SSRecord * ssRecord) private
Continue ranging function.
Parameters
cid the CID
rngrsp the ranging response
ssRecord the SS record
Definition at line 300 of file bs-link-manager.cc.
References ns3::WimaxNetDevice::RANGING_STATUS_CONTINUE, ScheduleRngRspMessage(), ns3::SSRecord::SetRangingStatus(), and ns3::RngRsp::SetRangStatus().
Referenced by PerformInitialRanging(), and PerformInvitedRanging().
DeallocateCids()
void ns3::BSLinkManager::DeallocateCids (Cid cid) private
Deallocate CIDs function.
Parameters
cid the CID
Definition at line 324 of file bs-link-manager.cc.
Referenced by AbortRanging().
GetNewDlChannel()
uint32_t ns3::BSLinkManager::GetNewDlChannel (void) private
Get new DL channel function.
Returns
the new DL channel
Definition at line 348 of file bs-link-manager.cc.
Referenced by PerformInitialRanging().
GetSignalQuality()
uint8_t ns3::BSLinkManager::GetSignalQuality (void) private
Get signal quality function.
Returns
the signal quality
Definition at line 355 of file bs-link-manager.cc.
References m_signalQuality.
Referenced by IsRangingAcceptable().
GetTypeId()
TypeId ns3::BSLinkManager::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 41 of file bs-link-manager.cc.
References ns3::TypeId::SetParent().
IsRangingAcceptable()
bool ns3::BSLinkManager::IsRangingAcceptable (void) private
Is ranging acceptable function.
Returns
true if ranging is acceptable
Definition at line 364 of file bs-link-manager.cc.
References GetSignalQuality(), and m_signalQualityThreshold.
Referenced by PerformInitialRanging(), and PerformInvitedRanging().
operator=()
BSLinkManager& ns3::BSLinkManager::operator= (const BSLinkManager &) private
assignment operator (disabled)
Returns
the BS link manager
PerformInitialRanging()
void ns3::BSLinkManager::PerformInitialRanging (Cid cid, RngReq * rngreq, RngRsp * rngrsp) private
Perform initial ranging function.
Parameters
cid the CID
rngreq the ranging request
rngrsp the ranging response
Definition at line 155 of file bs-link-manager.cc.
References AbortRanging(), AcceptRanging(), ChangeDlChannel(), ContinueRanging(), ns3::SSRecord::EnablePollForRanging(), ns3::SSRecord::GetBasicCid(), ns3::RngReq::GetMacAddress(), GetNewDlChannel(), ns3::RngReq::GetReqDlBurstProfile(), IsRangingAcceptable(), m_bs, ns3::SSRecord::ResetInvitedRangingRetries(), ns3::SSRecord::ResetRangingCorrectionRetries(), ns3::RngRsp::SetDlFreqOverride(), ns3::RngRsp::SetDlOperBurstProfile(), ns3::RngRsp::SetMacAddress(), and ns3::SSRecord::SetModulationType().
Referenced by PerformRanging().
PerformInvitedRanging()
void ns3::BSLinkManager::PerformInvitedRanging (Cid cid, RngRsp * rngrsp) private
Perform inivted ranging function.
Parameters
cid the CID
rngrsp the ranging response
Definition at line 219 of file bs-link-manager.cc.
References AbortRanging(), AcceptRanging(), ContinueRanging(), ns3::SSRecord::GetRangingCorrectionRetries(), ns3::SSRecord::IncrementRangingCorrectionRetries(), IsRangingAcceptable(), m_bs, and ns3::SSRecord::ResetInvitedRangingRetries().
Referenced by PerformRanging().
PerformRanging()
void ns3::BSLinkManager::PerformRanging (Cid cid, RngReq rngreq) private
Perform ranging function.
Parameters
cid the CID
rngreq the ranging request
Definition at line 113 of file bs-link-manager.cc.
References ns3::Cid::IsInitialRanging(), m_bs, NS_LOG_DEBUG, PerformInitialRanging(), PerformInvitedRanging(), ns3::RngReq::PrintDebug(), ns3::WimaxNetDevice::RANGING_STATUS_CONTINUE, ScheduleRngRspMessage(), ns3::RngRsp::SetFrameNumber(), ns3::RngRsp::SetInitRangOppNumber(), SetParametersToAdjust(), ns3::RngRsp::SetRangStatus(), and tries.
Referenced by ProcessRangingRequest().
ProcessRangingRequest()
void ns3::BSLinkManager::ProcessRangingRequest (Cid cid, RngReq rngreq)
process a ranging request message
Parameters
cid the connection identifier in which the ranging message was received
rngreq the ranging request message
Definition at line 73 of file bs-link-manager.cc.
References ns3::BaseStationNetDevice::BS_STATE_UL_SUB_FRAME, m_bs, ns3::Simulator::Now(), NS_ASSERT_MSG(), PerformRanging(), ns3::Seconds(), and tries.
ScheduleRngRspMessage()
void ns3::BSLinkManager::ScheduleRngRspMessage (Cid cid, RngRsp * rngrsp) private
Schedule range response message function.
Parameters
cid the CID
rngrsp the ranging response
Definition at line 308 of file bs-link-manager.cc.
References ns3::Packet::AddHeader(), ns3::RngRsp::GetRangStatus(), m_bs, ns3::ManagementMessageType::MESSAGE_TYPE_RNG_RSP, ns3::WimaxNetDevice::RANGING_STATUS_CONTINUE, ns3::WimaxNetDevice::RANGING_STATUS_SUCCESS, and SetParametersToAdjust().
Referenced by AbortRanging(), AcceptRanging(), ContinueRanging(), and PerformRanging().
SelectDlChannel()
uint64_t ns3::BSLinkManager::SelectDlChannel (void)
Returns
an available downlink channel
Definition at line 330 of file bs-link-manager.cc.
References m_bs.
SetParametersToAdjust()
void ns3::BSLinkManager::SetParametersToAdjust (RngRsp * rngrsp) private
Set parameters to adjust function.
Parameters
rngrsp the ranging response
Definition at line 262 of file bs-link-manager.cc.
References ns3::RngRsp::SetOffsetFreqAdjust(), ns3::RngRsp::SetPowerLevelAdjust(), and ns3::RngRsp::SetTimingAdjust().
Referenced by PerformRanging(), and ScheduleRngRspMessage().
VerifyInvitedRanging()
void ns3::BSLinkManager::VerifyInvitedRanging (Cid cid, uint8_t uiuc)
Verifies at the end of an invited ranging interval if SS sent ranging message in it or not.
Parameters
cid the connection identifier in which the ranging message was received
uiuc the ranging
Definition at line 243 of file bs-link-manager.cc.
References AbortRanging(), ns3::SSRecord::GetBasicCid(), ns3::SSRecord::GetInvitedRangRetries(), ns3::SSRecord::IncrementInvitedRangingRetries(), m_bs, and ns3::OfdmUlBurstProfile::UIUC_INITIAL_RANGING.
Member Data Documentation
m_bs
Ptr<BaseStationNetDevice> ns3::BSLinkManager::m_bs private
base station
Definition at line 163 of file bs-link-manager.h.
Referenced by ~BSLinkManager(), PerformInitialRanging(), PerformInvitedRanging(), PerformRanging(), ProcessRangingRequest(), ScheduleRngRspMessage(), SelectDlChannel(), and VerifyInvitedRanging().
m_signalQuality
uint32_t ns3::BSLinkManager::m_signalQuality private
signal quality
Definition at line 166 of file bs-link-manager.h.
Referenced by GetSignalQuality().
m_signalQualityThreshold
uint8_t ns3::BSLinkManager::m_signalQualityThreshold private
signal quality threshold
Definition at line 167 of file bs-link-manager.h.
Referenced by IsRangingAcceptable().
tries
int ns3::BSLinkManager::tries private
variable to test multiple RNG-REQ by the SS for example undecodable at BS or lost RNG-RSP
Definition at line 168 of file bs-link-manager.h.
Referenced by BSLinkManager(), PerformRanging(), and ProcessRangingRequest().
The documentation for this class was generated from the following files:
src/wimax/model/bs-link-manager.h
src/wimax/model/bs-link-manager.cc