ns-3: TestAmpduReception Class Reference
TestAmpduReception Class Reference
Wifi Models » wifi module tests | Test suites
A-MPDU reception test.
Public Member Functions
TestAmpduReception ()
virtual ~TestAmpduReception ()
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Protected Member Functions
virtual void DoSetup (void)
Implementation to do any local setup required for this TestCase.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Private Member Functions
void CheckPhyState (WifiPhyState expectedState)
Check the PHY state.
void CheckRxDroppedBitmapAmpdu1 (uint8_t expected)
Check the RX dropped bitmap for A-MPDU 1.
void CheckRxDroppedBitmapAmpdu2 (uint8_t expected)
Check the RX dropped bitmap for A-MPDU 2.
void CheckRxFailureBitmapAmpdu1 (uint8_t expected)
Check the RX failure bitmap for A-MPDU 1.
void CheckRxFailureBitmapAmpdu2 (uint8_t expected)
Check the RX failure bitmap for A-MPDU 2.
void CheckRxSuccessBitmapAmpdu1 (uint8_t expected)
Check the RX success bitmap for A-MPDU 1.
void CheckRxSuccessBitmapAmpdu2 (uint8_t expected)
Check the RX success bitmap for A-MPDU 2.
virtual void DoRun (void)
Implementation to actually run this TestCase.
void IncrementFailureBitmap (uint32_t size)
Increment reception failure bitmap.
void IncrementSuccessBitmap (uint32_t size)
Increment reception success bitmap.
void ResetBitmaps ()
Reset bitmaps function.
void RxDropped (Ptr< const Packet > p, WifiPhyRxfailureReason reason)
RX dropped function.
void RxFailure (Ptr< WifiPsdu > psdu)
RX failure function.
void RxSuccess (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector, std::vector< bool > statusPerMpdu)
RX success function.
void SendAmpduWithThreeMpdus (double rxPowerDbm, uint32_t referencePacketSize)
Send A-MPDU with 3 MPDUs of different size (i-th MSDU will have 100 bytes more than (i-1)-th).
Private Attributes
Ptr< SpectrumWifiPhy > m_phy
Phy.
uint8_t m_rxDroppedBitmapAmpdu1
bitmap of dropped MPDUs in A-MPDU #1
uint8_t m_rxDroppedBitmapAmpdu2
bitmap of dropped MPDUs in A-MPDU #2
uint8_t m_rxFailureBitmapAmpdu1
bitmap of unsuccessfully received MPDUs in A-MPDU #1
uint8_t m_rxFailureBitmapAmpdu2
bitmap of unsuccessfully received MPDUs in A-MPDU #2
uint8_t m_rxSuccessBitmapAmpdu1
bitmap of successfully received MPDUs in A-MPDU #1
uint8_t m_rxSuccessBitmapAmpdu2
bitmap of successfully received MPDUs in A-MPDU #2
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Detailed Description
A-MPDU reception test.
Definition at line 1382 of file wifi-phy-reception-test.cc.
Constructor & Destructor Documentation
TestAmpduReception()
TestAmpduReception::TestAmpduReception ()
Definition at line 1485 of file wifi-phy-reception-test.cc.
~TestAmpduReception()
TestAmpduReception::~TestAmpduReception () virtual
Definition at line 1496 of file wifi-phy-reception-test.cc.
References m_phy.
Member Function Documentation
CheckPhyState()
void TestAmpduReception::CheckPhyState (WifiPhyState expectedState) private
Check the PHY state.
Parameters
expectedState the expected PHY state
Definition at line 1667 of file wifi-phy-reception-test.cc.
References ns3::PointerValue::Get(), ns3::ObjectBase::GetAttribute(), ns3::WifiPhyStateHelper::GetState(), m_phy, ns3::Now(), and NS_TEST_ASSERT_MSG_EQ.
CheckRxDroppedBitmapAmpdu1()
void TestAmpduReception::CheckRxDroppedBitmapAmpdu1 (uint8_t expected) private
Check the RX dropped bitmap for A-MPDU 1.
Parameters
expected the expected bitmap
Definition at line 1655 of file wifi-phy-reception-test.cc.
References m_rxDroppedBitmapAmpdu1, and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
CheckRxDroppedBitmapAmpdu2()
void TestAmpduReception::CheckRxDroppedBitmapAmpdu2 (uint8_t expected) private
Check the RX dropped bitmap for A-MPDU 2.
Parameters
expected the expected bitmap
Definition at line 1661 of file wifi-phy-reception-test.cc.
References m_rxDroppedBitmapAmpdu2, and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
CheckRxFailureBitmapAmpdu1()
void TestAmpduReception::CheckRxFailureBitmapAmpdu1 (uint8_t expected) private
Check the RX failure bitmap for A-MPDU 1.
Parameters
expected the expected bitmap
Definition at line 1643 of file wifi-phy-reception-test.cc.
References m_rxFailureBitmapAmpdu1, and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
CheckRxFailureBitmapAmpdu2()
void TestAmpduReception::CheckRxFailureBitmapAmpdu2 (uint8_t expected) private
Check the RX failure bitmap for A-MPDU 2.
Parameters
expected the expected bitmap
Definition at line 1649 of file wifi-phy-reception-test.cc.
References m_rxFailureBitmapAmpdu2, and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
CheckRxSuccessBitmapAmpdu1()
void TestAmpduReception::CheckRxSuccessBitmapAmpdu1 (uint8_t expected) private
Check the RX success bitmap for A-MPDU 1.
Parameters
expected the expected bitmap
Definition at line 1631 of file wifi-phy-reception-test.cc.
References m_rxSuccessBitmapAmpdu1, and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
CheckRxSuccessBitmapAmpdu2()
void TestAmpduReception::CheckRxSuccessBitmapAmpdu2 (uint8_t expected) private
Check the RX success bitmap for A-MPDU 2.
Parameters
expected the expected bitmap
Definition at line 1637 of file wifi-phy-reception-test.cc.
References m_rxSuccessBitmapAmpdu2, and NS_TEST_ASSERT_MSG_EQ.
Referenced by DoRun().
DoRun()
void TestAmpduReception::DoRun (void) private virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 1734 of file wifi-phy-reception-test.cc.
References ns3::WifiPhy::AssignStreams(), CheckRxDroppedBitmapAmpdu1(), CheckRxDroppedBitmapAmpdu2(), CheckRxFailureBitmapAmpdu1(), CheckRxFailureBitmapAmpdu2(), CheckRxSuccessBitmapAmpdu1(), CheckRxSuccessBitmapAmpdu2(), m_phy, ns3::MicroSeconds(), ns3::NanoSeconds(), ResetBitmaps(), ns3::Seconds(), and SendAmpduWithThreeMpdus().
DoSetup()
void TestAmpduReception::DoSetup (void) protected virtual
Implementation to do any local setup required for this TestCase.
Subclasses should override this method to perform any costly per-test setup before DoRun is invoked.
Reimplemented from ns3::TestCase.
Definition at line 1710 of file wifi-phy-reception-test.cc.
References CHANNEL_NUMBER, ns3::SpectrumWifiPhy::ConfigureStandard(), FREQUENCY, m_phy, ns3::MakeCallback(), ns3::MicroSeconds(), RxDropped(), RxFailure(), RxSuccess(), ns3::ObjectBase::SetAttribute(), ns3::SpectrumWifiPhy::SetChannelNumber(), ns3::WifiPhy::SetErrorRateModel(), ns3::WifiPhy::SetFrameCaptureModel(), ns3::SpectrumWifiPhy::SetFrequency(), ns3::WifiPhy::SetPreambleDetectionModel(), ns3::WifiPhy::SetReceiveErrorCallback(), ns3::WifiPhy::SetReceiveOkCallback(), ns3::ObjectBase::TraceConnectWithoutContext(), and ns3::WIFI_PHY_STANDARD_80211ax_5GHZ.
IncrementFailureBitmap()
void TestAmpduReception::IncrementFailureBitmap (uint32_t size) private
Increment reception failure bitmap.
Parameters
size the size of the received packet
Definition at line 1572 of file wifi-phy-reception-test.cc.
References m_rxFailureBitmapAmpdu1, and m_rxFailureBitmapAmpdu2.
Referenced by RxFailure(), and RxSuccess().
IncrementSuccessBitmap()
void TestAmpduReception::IncrementSuccessBitmap (uint32_t size) private
Increment reception success bitmap.
Parameters
size the size of the received packet
Definition at line 1533 of file wifi-phy-reception-test.cc.
References m_rxSuccessBitmapAmpdu1, and m_rxSuccessBitmapAmpdu2.
Referenced by RxSuccess().
ResetBitmaps()
void TestAmpduReception::ResetBitmaps () private
Reset bitmaps function.
Definition at line 1502 of file wifi-phy-reception-test.cc.
References m_rxDroppedBitmapAmpdu1, m_rxDroppedBitmapAmpdu2, m_rxFailureBitmapAmpdu1, m_rxFailureBitmapAmpdu2, m_rxSuccessBitmapAmpdu1, and m_rxSuccessBitmapAmpdu2.
Referenced by DoRun().
RxDropped()
void TestAmpduReception::RxDropped (Ptr< const Packet > p, WifiPhyRxfailureReason reason) private
RX dropped function.
Parameters
p the packet
reason the reason
Definition at line 1601 of file wifi-phy-reception-test.cc.
References ns3::Packet::GetSize(), m_rxDroppedBitmapAmpdu1, m_rxDroppedBitmapAmpdu2, and NS_LOG_FUNCTION.
Referenced by DoSetup().
RxFailure()
void TestAmpduReception::RxFailure (Ptr< WifiPsdu > psdu) private
RX failure function.
Parameters
psdu the PSDU
Definition at line 1562 of file wifi-phy-reception-test.cc.
References ns3::WifiPsdu::begin(), ns3::WifiPsdu::end(), IncrementFailureBitmap(), and NS_LOG_FUNCTION.
Referenced by DoSetup().
RxSuccess()
void TestAmpduReception::RxSuccess (Ptr< WifiPsdu > psdu, double snr, WifiTxVector txVector, std::vector< bool > statusPerMpdu) private
RX success function.
Parameters
psdu the PSDU
snr the SNR
txVector the transmit vector
statusPerMpdu reception status per MPDU
Definition at line 1513 of file wifi-phy-reception-test.cc.
References ns3::WifiPsdu::begin(), ns3::WifiPsdu::end(), ns3::WifiPsdu::GetNMpdus(), IncrementFailureBitmap(), IncrementSuccessBitmap(), NS_ABORT_MSG_IF, and NS_LOG_FUNCTION.
Referenced by DoSetup().
SendAmpduWithThreeMpdus()
void TestAmpduReception::SendAmpduWithThreeMpdus (double rxPowerDbm, uint32_t referencePacketSize) private
Send A-MPDU with 3 MPDUs of different size (i-th MSDU will have 100 bytes more than (i-1)-th).
Parameters
rxPowerDbm the transmit power in dBm
referencePacketSize the reference size of the packets in bytes (i-th MSDU will have 100 bytes more than (i-1)-th)
Definition at line 1678 of file wifi-phy-reception-test.cc.
References ns3::WifiPhy::CalculateTxDuration(), CHANNEL_WIDTH, ns3::lorawan::DbmToW(), ns3::SpectrumSignalParameters::duration, FREQUENCY, ns3::WifiPhy::GetFrequency(), ns3::WifiPsdu::GetSize(), GUARD_WIDTH, m_phy, ns3::WifiSpectrumSignalParameters::ppdu, ns3::SpectrumSignalParameters::psd, ns3::WifiMacHeader::SetQosTid(), ns3::WifiMacHeader::SetType(), ns3::SpectrumWifiPhy::StartRx(), ns3::SpectrumSignalParameters::txPhy, ns3::WIFI_MAC_QOSDATA, and ns3::WIFI_PREAMBLE_HE_SU.
Referenced by DoRun().
Member Data Documentation
m_phy
Ptr<SpectrumWifiPhy> TestAmpduReception::m_phy private
Phy.
Definition at line 1473 of file wifi-phy-reception-test.cc.
Referenced by ~TestAmpduReception(), CheckPhyState(), DoRun(), DoSetup(), and SendAmpduWithThreeMpdus().
m_rxDroppedBitmapAmpdu1
uint8_t TestAmpduReception::m_rxDroppedBitmapAmpdu1 private
bitmap of dropped MPDUs in A-MPDU #1
Definition at line 1481 of file wifi-phy-reception-test.cc.
Referenced by CheckRxDroppedBitmapAmpdu1(), ResetBitmaps(), and RxDropped().
m_rxDroppedBitmapAmpdu2
uint8_t TestAmpduReception::m_rxDroppedBitmapAmpdu2 private
bitmap of dropped MPDUs in A-MPDU #2
Definition at line 1482 of file wifi-phy-reception-test.cc.
Referenced by CheckRxDroppedBitmapAmpdu2(), ResetBitmaps(), and RxDropped().
m_rxFailureBitmapAmpdu1
uint8_t TestAmpduReception::m_rxFailureBitmapAmpdu1 private
bitmap of unsuccessfully received MPDUs in A-MPDU #1
Definition at line 1478 of file wifi-phy-reception-test.cc.
Referenced by CheckRxFailureBitmapAmpdu1(), IncrementFailureBitmap(), and ResetBitmaps().
m_rxFailureBitmapAmpdu2
uint8_t TestAmpduReception::m_rxFailureBitmapAmpdu2 private
bitmap of unsuccessfully received MPDUs in A-MPDU #2
Definition at line 1479 of file wifi-phy-reception-test.cc.
Referenced by CheckRxFailureBitmapAmpdu2(), IncrementFailureBitmap(), and ResetBitmaps().
m_rxSuccessBitmapAmpdu1
uint8_t TestAmpduReception::m_rxSuccessBitmapAmpdu1 private
bitmap of successfully received MPDUs in A-MPDU #1
Definition at line 1475 of file wifi-phy-reception-test.cc.
Referenced by CheckRxSuccessBitmapAmpdu1(), IncrementSuccessBitmap(), and ResetBitmaps().
m_rxSuccessBitmapAmpdu2
uint8_t TestAmpduReception::m_rxSuccessBitmapAmpdu2 private
bitmap of successfully received MPDUs in A-MPDU #2
Definition at line 1476 of file wifi-phy-reception-test.cc.
Referenced by CheckRxSuccessBitmapAmpdu2(), IncrementSuccessBitmap(), and ResetBitmaps().
The documentation for this class was generated from the following file:
src/wifi/test/wifi-phy-reception-test.cc