ns-3: ns3::EmpiricalRandomVariable Class Reference
ns3::EmpiricalRandomVariable Class Reference
Core » Random Variables
The Random Number Generator (RNG) that has a specified empirical distribution.
#include "random-variable-stream.h"
Classes
class ValueCDF
Helper to hold one point of the CDF.
Public Member Functions
EmpiricalRandomVariable ()
Creates an empirical RNG that has a specified, empirical distribution.
void CDF (double v, double c)
Specifies a point in the empirical distribution.
virtual uint32_t GetInteger (void)
Returns the next value in the empirical distribution.
virtual double GetValue (void)
Returns the next value in the empirical distribution.
Public Member Functions inherited from ns3::RandomVariableStream
RandomVariableStream ()
Default constructor.
virtual ~RandomVariableStream ()
Destructor.
int64_t GetStream (void) const
Returns the stream number for the RngStream.
bool IsAntithetic (void) const
Check if antithetic values will be generated.
void SetAntithetic (bool isAntithetic)
Specify whether antithetic values should be generated.
void SetStream (int64_t stream)
Specifies the stream number for the RngStream.
Public Member Functions inherited from ns3::Object
Object ()
Constructor.
virtual ~Object ()
Destructor.
void AggregateObject (Ptr< Object > other)
Aggregate two Objects together.
void Dispose (void)
Dispose of this Object.
AggregateIterator GetAggregateIterator (void) const
Get an iterator to the Objects aggregated to this one.
virtual TypeId GetInstanceTypeId (void) const
Get the most derived TypeId for this Object.
template<typename T >
Ptr< T > GetObject (TypeId tid) const
Get a pointer to the requested aggregated Object by TypeId.
template<typename T >
Ptr< T > GetObject (void) const
Get a pointer to the requested aggregated Object.
void Initialize (void)
Invoke DoInitialize on all Objects aggregated to this one.
bool IsInitialized (void) const
Check if the object has been initialized.
Public Member Functions inherited from ns3::SimpleRefCount< Object, ObjectBase, ObjectDeleter >
SimpleRefCount ()
Default constructor.
SimpleRefCount (const SimpleRefCount &o)
Copy constructor.
uint32_t GetReferenceCount (void) const
Get the reference count of the object.
SimpleRefCount & operator= (const SimpleRefCount &o)
Assignment operator.
void Ref (void) const
Increment the reference count.
void Unref (void) const
Decrement the reference count.
Public Member Functions inherited from ns3::ObjectBase
virtual ~ObjectBase ()
Virtual destructor.
void GetAttribute (std::string name, AttributeValue &value) const
Get the value of an attribute, raising fatal errors if unsuccessful.
bool GetAttributeFailSafe (std::string name, AttributeValue &value) const
Get the value of an attribute without raising erros.
void SetAttribute (std::string name, const AttributeValue &value)
Set a single attribute, raising fatal errors if unsuccessful.
bool SetAttributeFailSafe (std::string name, const AttributeValue &value)
Set a single attribute without raising errors.
bool TraceConnect (std::string name, std::string context, const CallbackBase &cb)
Connect a TraceSource to a Callback with a context.
bool TraceConnectWithoutContext (std::string name, const CallbackBase &cb)
Connect a TraceSource to a Callback without a context.
bool TraceDisconnect (std::string name, std::string context, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected with a context.
bool TraceDisconnectWithoutContext (std::string name, const CallbackBase &cb)
Disconnect from a TraceSource a Callback previously connected without a context.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::RandomVariableStream
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::Object
static TypeId GetTypeId (void)
Register this type.
Static Public Member Functions inherited from ns3::ObjectBase
static TypeId GetTypeId (void)
Get the type ID.
Private Member Functions
virtual double Interpolate (double c1, double c2, double v1, double v2, double r)
Linear nterpolation between two points on the CDF to estimate the value at r
virtual void Validate ()
Check that the CDF is valid.
Private Attributes
std::vector< ValueCDF > m_emp
The vector of CDF points.
bool m_validated
true once the CDF has been validated.
Additional Inherited Members
Protected Member Functions inherited from ns3::RandomVariableStream
RngStream * Peek (void) const
Get the pointer to the underlying RngStream.
Protected Member Functions inherited from ns3::Object
Object (const Object &o)
Copy an Object.
virtual void DoDispose (void)
Destructor implementation.
virtual void DoInitialize (void)
Initialize() implementation.
virtual void NotifyNewAggregate (void)
Notify all Objects aggregated to this one of a new Object being aggregated.
Protected Member Functions inherited from ns3::ObjectBase
void ConstructSelf (const AttributeConstructionList &attributes)
Complete construction of ObjectBase; invoked by derived classes.
virtual void NotifyConstructionCompleted (void)
Notifier called once the ObjectBase is fully constructed.
Related Functions inherited from ns3::ObjectBase
static TypeId GetObjectIid (void)
Ensure the TypeId for ObjectBase gets fully configured to anchor the inheritance tree properly.
Detailed Description
The Random Number Generator (RNG) that has a specified empirical distribution.
Defines a random variable that has a specified, empirical distribution. The distribution is specified by a series of calls to the CDF member function, specifying a value and the probability that the function value is less than the specified value. When values are requested, a uniform random variable is used to select a probability, and the return value is interpreted linearly between the two appropriate points in the CDF. The method is known as inverse transform sampling: (http://en.wikipedia.org/wiki/Inverse_transform_sampling).
Here is an example of how to use this class:
// Create the RNG with a uniform distribution between 0 and 10.
Ptr<EmpiricalRandomVariable> x = CreateObject<EmpiricalRandomVariable> ();
x->CDF (0.0,  0.0);
x->CDF (5.0,  0.5);
x->CDF (10.0,  1.0);
// The expected value for the mean of the values returned by this
// empirical distribution is the midpoint of the distribution
//
//     E[value]  =  5 .
//
double value = x->GetValue ();
Definition at line 2442 of file random-variable-stream.h.
Constructor & Destructor Documentation
EmpiricalRandomVariable()
ns3::EmpiricalRandomVariable::EmpiricalRandomVariable ()
Creates an empirical RNG that has a specified, empirical distribution.
Definition at line 1565 of file random-variable-stream.cc.
References NS_LOG_FUNCTION.
Member Function Documentation
CDF()
void ns3::EmpiricalRandomVariable::CDF (double v, double c)
Specifies a point in the empirical distribution.
Parameters
[in] v The function value for this point
[in] c Probability that the function is less than or equal to v
Definition at line 1629 of file random-variable-stream.cc.
References m_emp, and NS_LOG_FUNCTION.
Referenced by RandomVariableStreamEmpiricalTestCase::DoRun().
GetInteger()
uint32_t ns3::EmpiricalRandomVariable::GetInteger (void) virtual
Returns the next value in the empirical distribution.
Returns
The integer next value in the empirical distribution.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If is a uniform variable over [0,1] and is a value that would be returned normally, then) is the distance that would be from . The value returned in the antithetic case, , uses (1-u), which is the distance is from the 1.
Implements ns3::RandomVariableStream.
Definition at line 1623 of file random-variable-stream.cc.
References GetValue(), and NS_LOG_FUNCTION.
GetTypeId()
TypeId ns3::EmpiricalRandomVariable::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 1556 of file random-variable-stream.cc.
References ns3::TypeId::SetParent().
GetValue()
double ns3::EmpiricalRandomVariable::GetValue (void) virtual
Returns the next value in the empirical distribution.
Returns
The floating point next value in the empirical distribution.
Note that antithetic values are being generated if m_isAntithetic is equal to true. If is a uniform variable over [0,1] and is a value that would be returned normally, then) is the distance that would be from . The value returned in the antithetic case, , uses (1-u), which is the distance is from the 1.
Implements ns3::RandomVariableStream.
Definition at line 1573 of file random-variable-stream.cc.
References Interpolate(), ns3::RandomVariableStream::IsAntithetic(), m_emp, m_validated, NS_LOG_FUNCTION, ns3::RandomVariableStream::Peek(), ns3::RngStream::RandU01(), and Validate().
Referenced by RandomVariableStreamEmpiricalTestCase::DoRun(), and GetInteger().
Interpolate()
double ns3::EmpiricalRandomVariable::Interpolate (double c1, double c2, double v1, double v2, double r) private virtual
Linear nterpolation between two points on the CDF to estimate the value at r
Parameters
[in] c1 The first argument value.
[in] c2 The secong argument value.
[in] v1 The first CDF value.
[in] v2 The secong CDF value.
[in] r The argument value to interpolate to.
Returns
The interpolated CDF at r
Definition at line 1665 of file random-variable-stream.cc.
References NS_LOG_FUNCTION.
Referenced by GetValue().
Validate()
void ns3::EmpiricalRandomVariable::Validate () private virtual
Check that the CDF is valid.
A valid CDF has
Strictly increasing arguments, and
Strictly increasing CDF.
It is a fatal error to fail validation.
Definition at line 1636 of file random-variable-stream.cc.
References ns3::EmpiricalRandomVariable::ValueCDF::cdf, m_emp, m_validated, NS_FATAL_ERROR, NS_LOG_FUNCTION, and ns3::EmpiricalRandomVariable::ValueCDF::value.
Referenced by GetValue().
Member Data Documentation
m_emp
std::vector<ValueCDF> ns3::EmpiricalRandomVariable::m_emp private
The vector of CDF points.
Definition at line 2544 of file random-variable-stream.h.
Referenced by CDF(), GetValue(), and Validate().
m_validated
bool ns3::EmpiricalRandomVariable::m_validated private
true once the CDF has been validated.
Definition at line 2542 of file random-variable-stream.h.
Referenced by GetValue(), and Validate().
The documentation for this class was generated from the following files:
src/core/model/random-variable-stream.h
src/core/model/random-variable-stream.cc