ns-3: examples/traffic-control/cobalt-vs-codel.cc File Reference
cobalt-vs-codel.cc File Reference
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/point-to-point-module.h"
#include "ns3/applications-module.h"
#include <fstream>
#include "ns3/ipv6-static-routing-helper.h"
#include "ns3/ipv6-routing-table-entry.h"
#include "ns3/internet-module.h"
#include "ns3/tcp-header.h"
#include "ns3/traffic-control-module.h"
#include <string>
Functions
void CheckQueueSize (Ptr< QueueDisc > queue, std::string queue_disc_type)
static void CwndTrace (Ptr< OutputStreamWrapper > stream, uint32_t oldCwnd, uint32_t newCwnd)
void experiment (std::string queue_disc_type)
static void TraceCwnd (std::string queue_disc_type)
Variables
std::string dir = "MixTraffic/"
Function Documentation
CheckQueueSize()
void CheckQueueSize (Ptr< QueueDisc > queue, std::string queue_disc_type)
Definition at line 46 of file cobalt-vs-codel.cc.
References dir, ns3::QueueDisc::GetCurrentSize(), ns3::Time::GetSeconds(), ns3::QueueSize::GetValue(), ns3::Simulator::Now(), ns3::Simulator::Schedule(), and ns3::Seconds().
Referenced by experiment().
CwndTrace()
static void CwndTrace (Ptr< OutputStreamWrapper > stream, uint32_t oldCwnd, uint32_t newCwnd) static
Definition at line 58 of file cobalt-vs-codel.cc.
References ns3::Time::GetSeconds(), ns3::OutputStreamWrapper::GetStream(), and ns3::Simulator::Now().
Referenced by TraceCwnd().
experiment()
void experiment (std::string queue_disc_type)
Definition at line 74 of file cobalt-vs-codel.cc.
References ns3::ApplicationContainer::Add(), ns3::TrafficControlHelper::AddInternalQueues(), first::address, CheckQueueSize(), ns3::NodeContainer::Create(), ns3::Simulator::Destroy(), first::devices, dir, ns3::QueueDiscContainer::Get(), ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::Ipv4Address::GetAny(), ns3::TcpSocketFactory::GetTypeId(), ns3::UdpSocketFactory::GetTypeId(), ns3::TrafficControlHelper::Install(), ns3::PointToPointHelper::Install(), ns3::BulkSendHelper::Install(), ns3::OnOffHelper::Install(), ns3::PacketSinkHelper::Install(), ns3::InternetStackHelper::InstallAll(), first::interfaces, ns3::Ipv4GlobalRoutingHelper::PopulateRoutingTables(), port, ns3::Simulator::Run(), ns3::Simulator::Schedule(), ns3::Simulator::ScheduleNow(), ns3::Seconds(), ns3::BulkSendHelper::SetAttribute(), ns3::OnOffHelper::SetAttribute(), ns3::PacketSinkHelper::SetAttribute(), ns3::PointToPointHelper::SetChannelAttribute(), ns3::Config::SetDefault(), ns3::PointToPointHelper::SetDeviceAttribute(), ns3::TrafficControlHelper::SetRootQueueDisc(), sink, ns3::ApplicationContainer::Start(), ns3::ApplicationContainer::Stop(), ns3::Simulator::Stop(), stopTime, and TraceCwnd().
Referenced by ns3::DataCollector::DescribeRun(), PrintPsr(), PrintPsrVsCollisionInterval(), PrintPsrVsDistance(), and PrintSizeVsRange().
TraceCwnd()
static void TraceCwnd (std::string queue_disc_type) static
Definition at line 64 of file cobalt-vs-codel.cc.
References ns3::Config::ConnectWithoutContext(), ns3::AsciiTraceHelper::CreateFileStream(), CwndTrace(), dir, and ns3::MakeBoundCallback().
Referenced by experiment().
Variable Documentation
dir
std::string dir = "MixTraffic/"
Definition at line 43 of file cobalt-vs-codel.cc.
Referenced by CheckQueueSize(), ns3::IpcsClassifier::Classify(), ns3::ServiceFlowManager::DoClassify(), experiment(), TraceCwnd(), and ns3::OnoeWifiManager::UpdateMode().