ns-3: src/traffic-control/examples/codel-vs-pfifo-asymmetric.cc File Reference
codel-vs-pfifo-asymmetric.cc File Reference
#include <iostream>
#include <fstream>
#include <string>
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/point-to-point-module.h"
#include "ns3/applications-module.h"
#include "ns3/config-store-module.h"
#include "ns3/error-model.h"
#include "ns3/tcp-header.h"
#include "ns3/udp-header.h"
#include "ns3/enum.h"
#include "ns3/event-id.h"
#include "ns3/ipv4-global-routing-helper.h"
#include "ns3/traffic-control-module.h"
Functions
void CreateBulkFlow (AddressValue remoteAddress, Ptr< Node > sender, uint32_t pktSize, float stopTime)
void CreateOnOffFlow (AddressValue remoteAddress, Ptr< Node > sender, float stopTime)
static void CwndTracer (Ptr< OutputStreamWrapper >stream, uint32_t oldval, uint32_t newval)
static void DroppingStateTracer (Ptr< OutputStreamWrapper >stream, bool oldVal, bool newVal)
static void EveryDropTracer (Ptr< OutputStreamWrapper >stream, Ptr< const QueueDiscItem > item)
static void QueueLengthTracer (Ptr< OutputStreamWrapper >stream, uint32_t oldval, uint32_t newval)
static void SojournTracer (Ptr< OutputStreamWrapper >stream, Time oldval, Time newval)
static void TraceCwnd (std::string cwndTrFileName)
static void TraceDroppingState (std::string dropStateTrFileName)
static void TraceEveryDrop (std::string everyDropTrFileName)
static void TraceQueueLength (std::string queueLengthTrFileName)
static void TraceSojourn (std::string sojournTrFileName)
Function Documentation
CreateBulkFlow()
void CreateBulkFlow (AddressValue remoteAddress, Ptr< Node > sender, uint32_t pktSize, float stopTime)
Definition at line 192 of file codel-vs-pfifo-asymmetric.cc.
References ns3::BulkSendHelper::Install(), ns3::Seconds(), ns3::BulkSendHelper::SetAttribute(), ns3::ApplicationContainer::Start(), ns3::ApplicationContainer::Stop(), and stopTime.
CreateOnOffFlow()
void CreateOnOffFlow (AddressValue remoteAddress, Ptr< Node > sender, float stopTime)
Definition at line 204 of file codel-vs-pfifo-asymmetric.cc.
References ns3::OnOffHelper::Install(), ns3::Seconds(), ns3::OnOffHelper::SetAttribute(), ns3::ApplicationContainer::Start(), ns3::ApplicationContainer::Stop(), and stopTime.
CwndTracer()
static void CwndTracer (Ptr< OutputStreamWrapper > stream, uint32_t oldval, uint32_t newval) static
Definition at line 73 of file codel-vs-pfifo-asymmetric.cc.
References ns3::OutputStreamWrapper::GetStream().
Referenced by TraceCwnd().
DroppingStateTracer()
static void DroppingStateTracer (Ptr< OutputStreamWrapper > stream, bool oldVal, bool newVal) static
Definition at line 161 of file codel-vs-pfifo-asymmetric.cc.
References ns3::Time::GetSeconds(), ns3::OutputStreamWrapper::GetStream(), ns3::Simulator::Now(), and NS_LOG_INFO.
Referenced by TraceDroppingState().
EveryDropTracer()
static void EveryDropTracer (Ptr< OutputStreamWrapper > stream, Ptr< const QueueDiscItem > item) static
Definition at line 139 of file codel-vs-pfifo-asymmetric.cc.
References ns3::Time::GetSeconds(), ns3::OutputStreamWrapper::GetStream(), and ns3::Simulator::Now().
Referenced by TraceEveryDrop().
QueueLengthTracer()
static void QueueLengthTracer (Ptr< OutputStreamWrapper > stream, uint32_t oldval, uint32_t newval) static
Definition at line 117 of file codel-vs-pfifo-asymmetric.cc.
References ns3::OutputStreamWrapper::GetStream().
Referenced by TraceQueueLength().
SojournTracer()
static void SojournTracer (Ptr< OutputStreamWrapper > stream, Time oldval, Time newval) static
Definition at line 95 of file codel-vs-pfifo-asymmetric.cc.
References ns3::OutputStreamWrapper::GetStream().
Referenced by TraceSojourn().
TraceCwnd()
static void TraceCwnd (std::string cwndTrFileName) static
Definition at line 79 of file codel-vs-pfifo-asymmetric.cc.
References ns3::Config::ConnectWithoutContext(), ns3::AsciiTraceHelper::CreateFileStream(), CwndTracer(), ns3::MakeBoundCallback(), and NS_LOG_DEBUG.
TraceDroppingState()
static void TraceDroppingState (std::string dropStateTrFileName) static
Definition at line 176 of file codel-vs-pfifo-asymmetric.cc.
References ns3::Config::ConnectWithoutContext(), ns3::AsciiTraceHelper::CreateFileStream(), DroppingStateTracer(), ns3::MakeBoundCallback(), and NS_LOG_DEBUG.
TraceEveryDrop()
static void TraceEveryDrop (std::string everyDropTrFileName) static
Definition at line 145 of file codel-vs-pfifo-asymmetric.cc.
References ns3::Config::ConnectWithoutContext(), ns3::AsciiTraceHelper::CreateFileStream(), EveryDropTracer(), ns3::MakeBoundCallback(), and NS_LOG_DEBUG.
TraceQueueLength()
static void TraceQueueLength (std::string queueLengthTrFileName) static
Definition at line 123 of file codel-vs-pfifo-asymmetric.cc.
References ns3::Config::ConnectWithoutContext(), ns3::AsciiTraceHelper::CreateFileStream(), ns3::MakeBoundCallback(), NS_LOG_DEBUG, and QueueLengthTracer().
TraceSojourn()
static void TraceSojourn (std::string sojournTrFileName) static
Definition at line 101 of file codel-vs-pfifo-asymmetric.cc.
References ns3::Config::ConnectWithoutContext(), ns3::AsciiTraceHelper::CreateFileStream(), ns3::MakeBoundCallback(), NS_LOG_DEBUG, and SojournTracer().