ns-3: src/traffic-control/examples/codel-vs-pfifo-basic-test.cc File Reference
codel-vs-pfifo-basic-test.cc File Reference
#include <iostream>
#include <fstream>
#include <string>
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/point-to-point-module.h"
#include "ns3/applications-module.h"
#include "ns3/error-model.h"
#include "ns3/tcp-header.h"
#include "ns3/udp-header.h"
#include "ns3/enum.h"
#include "ns3/event-id.h"
#include "ns3/ipv4-global-routing-helper.h"
#include "ns3/traffic-control-module.h"
Functions
static void CwndTracer (Ptr< OutputStreamWrapper >stream, uint32_t oldval, uint32_t newval)
static void TraceCwnd (std::string cwndTrFileName)
Function Documentation
CwndTracer()
static void CwndTracer (Ptr< OutputStreamWrapper > stream, uint32_t oldval, uint32_t newval) static
Definition at line 58 of file codel-vs-pfifo-basic-test.cc.
References ns3::OutputStreamWrapper::GetStream().
Referenced by TraceCwnd().
TraceCwnd()
static void TraceCwnd (std::string cwndTrFileName) static
Definition at line 64 of file codel-vs-pfifo-basic-test.cc.
References ns3::Config::ConnectWithoutContext(), ns3::AsciiTraceHelper::CreateFileStream(), CwndTracer(), ns3::MakeBoundCallback(), and NS_LOG_DEBUG.