ns-3: src/netanim/examples/colors-link-description.cc File Reference
colors-link-description.cc File Reference
#include <iostream>
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/point-to-point-module.h"
#include "ns3/netanim-module.h"
#include "ns3/applications-module.h"
#include "ns3/point-to-point-layout-module.h"
Classes
struct rgb
RGB structure.
Functions
void modify ()
Variables
struct rgb colors []
AnimationInterface * pAnim = 0
Function Documentation
modify()
void modify ()
Definition at line 46 of file colors-link-description.cc.
References rgb::b, colors, rgb::g, ns3::Time::GetSeconds(), ns3::Simulator::Now(), pAnim, rgb::r, ns3::Simulator::Schedule(), ns3::Seconds(), ns3::AnimationInterface::UpdateLinkDescription(), ns3::AnimationInterface::UpdateNodeColor(), and ns3::AnimationInterface::UpdateNodeDescription().
Variable Documentation
colors
struct rgb colors[]
Initial value:
= {
                        { 255, 0, 0 },
                        { 0, 255, 0 },
                        { 0, 0, 255 }
                        }
Definition at line 31 of file colors-link-description.cc.
Referenced by modify().
pAnim
AnimationInterface* pAnim = 0
Definition at line 31 of file colors-link-description.cc.
Referenced by modify().