ns-3: src/lorawan/examples/complete-lorawan-network-example.cc File Reference
complete-lorawan-network-example.cc File Reference
#include "ns3/end-device-lora-phy.h"
#include "ns3/gateway-lora-phy.h"
#include "ns3/end-device-lora-mac.h"
#include "ns3/gateway-lora-mac.h"
#include "ns3/simulator.h"
#include "ns3/log.h"
#include "ns3/pointer.h"
#include "ns3/constant-position-mobility-model.h"
#include "ns3/lora-helper.h"
#include "ns3/node-container.h"
#include "ns3/mobility-helper.h"
#include "ns3/position-allocator.h"
#include "ns3/double.h"
#include "ns3/random-variable-stream.h"
#include "ns3/periodic-sender-helper.h"
#include "ns3/command-line.h"
#include <algorithm>
#include <ctime>
Classes
struct PacketStatus
Enumerations
enum PacketOutcome {
RECEIVED, INTERFERED, NO_MORE_RECEIVERS, UNDER_SENSITIVITY,
UNSET
}
Functions
void CheckReceptionByAllGWsComplete (std::map< Ptr< Packet const >, PacketStatus >::iterator it)
void InterferenceCallback (Ptr< Packet const > packet, uint32_t systemId)
void NoMoreReceiversCallback (Ptr< Packet const > packet, uint32_t systemId)
void PacketReceptionCallback (Ptr< Packet const > packet, uint32_t systemId)
void PrintEndDevices (NodeContainer endDevices, NodeContainer gateways, std::string filename)
void PrintSimulationTime (void)
std::vector< int > sfQuantity (6)
void TransmissionCallback (Ptr< Packet const > packet, uint32_t systemId)
void UnderSensitivityCallback (Ptr< Packet const > packet, uint32_t systemId)
Variables
int appPeriodSeconds = 600
bool buildingsEnabled = false
double gatewayRadius = 7500/((gatewayRings-1)*2+1)
int gatewayRings = 1
int interfered = 0
int nDevices = 2000
int nGateways = 3*gatewayRings*gatewayRings-3*gatewayRings+1
int noMoreReceivers = 0
time_t oldtime = std::time (0)
std::map< Ptr< Packet const >, PacketStatus > packetTracker
bool printEDs = true
double radius = 7500
int received = 0
double simulationTime = 600
int underSensitivity = 0
Enumeration Type Documentation
PacketOutcome
enum PacketOutcome
Enumerator
RECEIVED
INTERFERED
NO_MORE_RECEIVERS
UNDER_SENSITIVITY
UNSET
Definition at line 53 of file complete-lorawan-network-example.cc.
Function Documentation
CheckReceptionByAllGWsComplete()
void CheckReceptionByAllGWsComplete (std::map< Ptr< Packet const >, PacketStatus >::iterator it)
Definition at line 71 of file complete-lorawan-network-example.cc.
References interfered, INTERFERED, nGateways, NO_MORE_RECEIVERS, noMoreReceivers, PacketStatus::outcomes, packetTracker, received, RECEIVED, UNDER_SENSITIVITY, underSensitivity, and UNSET.
Referenced by InterferenceCallback(), NoMoreReceiversCallback(), PacketReceptionCallback(), and UnderSensitivityCallback().
InterferenceCallback()
void InterferenceCallback (Ptr< Packet const > packet, uint32_t systemId)
Definition at line 141 of file complete-lorawan-network-example.cc.
References CheckReceptionByAllGWsComplete(), INTERFERED, nDevices, packet, and packetTracker.
NoMoreReceiversCallback()
void NoMoreReceiversCallback (Ptr< Packet const > packet, uint32_t systemId)
Definition at line 153 of file complete-lorawan-network-example.cc.
References CheckReceptionByAllGWsComplete(), nDevices, NO_MORE_RECEIVERS, packet, and packetTracker.
PacketReceptionCallback()
void PacketReceptionCallback (Ptr< Packet const > packet, uint32_t systemId)
Definition at line 128 of file complete-lorawan-network-example.cc.
References CheckReceptionByAllGWsComplete(), nDevices, packet, packetTracker, and RECEIVED.
PrintEndDevices()
void PrintEndDevices (NodeContainer endDevices, NodeContainer gateways, std::string filename)
Definition at line 189 of file complete-lorawan-network-example.cc.
References ns3::NodeContainer::Begin(), ns3::NodeContainer::End(), endDevices, gateways, ns3::LoraNetDevice::GetMac(), ns3::Object::GetObject(), ns3::MobilityModel::GetPosition(), third::mac, and NS_ASSERT.
PrintSimulationTime()
void PrintSimulationTime (void)
Definition at line 179 of file complete-lorawan-network-example.cc.
References ns3::Time::GetHours(), ns3::Minutes(), ns3::Simulator::Now(), oldtime, and ns3::Simulator::Schedule().
sfQuantity()
std::vector<int> sfQuantity (6)
TransmissionCallback()
void TransmissionCallback (Ptr< Packet const > packet, uint32_t systemId)
Definition at line 114 of file complete-lorawan-network-example.cc.
References nGateways, PacketStatus::outcomeNumber, PacketStatus::outcomes, PacketStatus::packet, packet, packetTracker, PacketStatus::senderId, and UNSET.
UnderSensitivityCallback()
void UnderSensitivityCallback (Ptr< Packet const > packet, uint32_t systemId)
Definition at line 165 of file complete-lorawan-network-example.cc.
References CheckReceptionByAllGWsComplete(), nDevices, packet, packetTracker, and UNDER_SENSITIVITY.
Variable Documentation
appPeriodSeconds
int appPeriodSeconds = 600
Definition at line 37 of file complete-lorawan-network-example.cc.
buildingsEnabled
bool buildingsEnabled = false
Definition at line 47 of file complete-lorawan-network-example.cc.
gatewayRadius
double gatewayRadius = 7500/((gatewayRings-1)*2+1)
Definition at line 35 of file complete-lorawan-network-example.cc.
gatewayRings
int gatewayRings = 1
Definition at line 32 of file complete-lorawan-network-example.cc.
interfered
int interfered = 0
Definition at line 41 of file complete-lorawan-network-example.cc.
Referenced by CheckReceptionByAllGWsComplete().
nDevices
int nDevices = 2000
Definition at line 31 of file complete-lorawan-network-example.cc.
Referenced by ns3::GlobalRouter::BuildNetworkLSAs(), ns3::AnimationInterface::ConnectLte(), InterferenceCallback(), NoMoreReceiversCallback(), PacketReceptionCallback(), ns3::GrantedTimeWindowMpiInterface::ReceiveMessages(), ns3::NullMessageMpiInterface::ReceiveMessages(), and UnderSensitivityCallback().
nGateways
int nGateways = 3*gatewayRings*gatewayRings-3*gatewayRings+1
Definition at line 33 of file complete-lorawan-network-example.cc.
Referenced by CheckReceptionByAllGWsComplete(), and TransmissionCallback().
noMoreReceivers
int noMoreReceivers = 0
Definition at line 40 of file complete-lorawan-network-example.cc.
Referenced by CheckReceptionByAllGWsComplete().
oldtime
time_t oldtime = std::time (0)
Definition at line 176 of file complete-lorawan-network-example.cc.
Referenced by PrintSimulationTime().
packetTracker
std::map<Ptr<Packet const>, PacketStatus> packetTracker
Definition at line 68 of file complete-lorawan-network-example.cc.
Referenced by CheckReceptionByAllGWsComplete(), InterferenceCallback(), NoMoreReceiversCallback(), PacketReceptionCallback(), TransmissionCallback(), and UnderSensitivityCallback().
printEDs
bool printEDs = true
Definition at line 46 of file complete-lorawan-network-example.cc.
radius
double radius = 7500
Definition at line 34 of file complete-lorawan-network-example.cc.
Referenced by ns3::RocketfuelTopologyReader::GenerateFromMapsFile(), and ns3::PrintNodeInfo().
received
int received = 0
Definition at line 42 of file complete-lorawan-network-example.cc.
Referenced by CheckReceptionByAllGWsComplete(), Ns3TcpStateTestCase::Ipv4L3Rx(), Ns3TcpLossTestCase::Ipv4L3Tx(), and Ns3TcpStateTestCase::Ipv4L3Tx().
simulationTime
double simulationTime = 600
Definition at line 36 of file complete-lorawan-network-example.cc.
Referenced by LenaMimoTestCase::DoRun(), and Experiment::Run().
underSensitivity
int underSensitivity = 0
Definition at line 43 of file complete-lorawan-network-example.cc.
Referenced by CheckReceptionByAllGWsComplete().