ns-3: examples/tcp/dctcp-example.cc File Reference
dctcp-example.cc File Reference
#include <iostream>
#include <iomanip>
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/point-to-point-module.h"
#include "ns3/applications-module.h"
#include "ns3/traffic-control-module.h"
Functions
void CheckT1QueueSize (Ptr< QueueDisc > queue)
void CheckT2QueueSize (Ptr< QueueDisc > queue)
void InitializeCounters (void)
void PrintFairness (Time measurementWindow)
void PrintProgress (Time interval)
void PrintThroughput (Time measurementWindow)
void TraceS1R1Sink (std::size_t index, Ptr< const Packet > p, const Address &a)
void TraceS2R2Sink (std::size_t index, Ptr< const Packet > p, const Address &a)
void TraceS3R1Sink (std::size_t index, Ptr< const Packet > p, const Address &a)
Variables
std::ofstream fairnessIndex
std::stringstream filePlotQueue1
std::stringstream filePlotQueue2
std::vector< uint64_t > rxS1R1Bytes
std::ofstream rxS1R1Throughput
std::vector< uint64_t > rxS2R2Bytes
std::ofstream rxS2R2Throughput
std::vector< uint64_t > rxS3R1Bytes
std::ofstream rxS3R1Throughput
std::ofstream t1QueueLength
std::ofstream t2QueueLength
Function Documentation
CheckT1QueueSize()
void CheckT1QueueSize (Ptr< QueueDisc > queue)
Definition at line 246 of file dctcp-example.cc.
References ns3::Time::GetMicroSeconds(), ns3::QueueDisc::GetNPackets(), ns3::Time::GetSeconds(), ns3::MilliSeconds(), ns3::Simulator::Now(), ns3::Simulator::Schedule(), ns3::Seconds(), and t1QueueLength.
CheckT2QueueSize()
void CheckT2QueueSize (Ptr< QueueDisc > queue)
Definition at line 258 of file dctcp-example.cc.
References ns3::Time::GetMicroSeconds(), ns3::QueueDisc::GetNPackets(), ns3::Time::GetSeconds(), ns3::MilliSeconds(), ns3::Simulator::Now(), ns3::Simulator::Schedule(), ns3::Seconds(), and t2QueueLength.
InitializeCounters()
void InitializeCounters (void)
Definition at line 144 of file dctcp-example.cc.
References rxS1R1Bytes, rxS2R2Bytes, and rxS3R1Bytes.
PrintFairness()
void PrintFairness (Time measurementWindow)
Definition at line 179 of file dctcp-example.cc.
References fairnessIndex, ns3::Time::GetSeconds(), rxS1R1Bytes, rxS2R2Bytes, and rxS3R1Bytes.
PrintProgress()
void PrintProgress (Time interval)
Definition at line 119 of file dctcp-example.cc.
References ns3::Time::GetSeconds(), ns3::Simulator::Now(), and ns3::Simulator::Schedule().
PrintThroughput()
void PrintThroughput (Time measurementWindow)
Definition at line 161 of file dctcp-example.cc.
References ns3::Time::GetSeconds(), ns3::Simulator::Now(), rxS1R1Bytes, rxS1R1Throughput, rxS2R2Bytes, rxS2R2Throughput, rxS3R1Bytes, and rxS3R1Throughput.
TraceS1R1Sink()
void TraceS1R1Sink (std::size_t index, Ptr< const Packet > p, const Address & a)
Definition at line 126 of file dctcp-example.cc.
References ns3::Packet::GetSize(), and rxS1R1Bytes.
TraceS2R2Sink()
void TraceS2R2Sink (std::size_t index, Ptr< const Packet > p, const Address & a)
Definition at line 132 of file dctcp-example.cc.
References ns3::Packet::GetSize(), and rxS2R2Bytes.
TraceS3R1Sink()
void TraceS3R1Sink (std::size_t index, Ptr< const Packet > p, const Address & a)
Definition at line 138 of file dctcp-example.cc.
References ns3::Packet::GetSize(), and rxS3R1Bytes.
Variable Documentation
fairnessIndex
std::ofstream fairnessIndex
Definition at line 111 of file dctcp-example.cc.
Referenced by PrintFairness().
filePlotQueue1
std::stringstream filePlotQueue1
Definition at line 106 of file dctcp-example.cc.
filePlotQueue2
std::stringstream filePlotQueue2
Definition at line 107 of file dctcp-example.cc.
rxS1R1Bytes
std::vector<uint64_t> rxS1R1Bytes
Definition at line 114 of file dctcp-example.cc.
Referenced by InitializeCounters(), PrintFairness(), PrintThroughput(), and TraceS1R1Sink().
rxS1R1Throughput
std::ofstream rxS1R1Throughput
Definition at line 108 of file dctcp-example.cc.
Referenced by PrintThroughput().
rxS2R2Bytes
std::vector<uint64_t> rxS2R2Bytes
Definition at line 115 of file dctcp-example.cc.
Referenced by InitializeCounters(), PrintFairness(), PrintThroughput(), and TraceS2R2Sink().
rxS2R2Throughput
std::ofstream rxS2R2Throughput
Definition at line 109 of file dctcp-example.cc.
Referenced by PrintThroughput().
rxS3R1Bytes
std::vector<uint64_t> rxS3R1Bytes
Definition at line 116 of file dctcp-example.cc.
Referenced by InitializeCounters(), PrintFairness(), PrintThroughput(), and TraceS3R1Sink().
rxS3R1Throughput
std::ofstream rxS3R1Throughput
Definition at line 110 of file dctcp-example.cc.
Referenced by PrintThroughput().
t1QueueLength
std::ofstream t1QueueLength
Definition at line 112 of file dctcp-example.cc.
Referenced by CheckT1QueueSize().
t2QueueLength
std::ofstream t2QueueLength
Definition at line 113 of file dctcp-example.cc.
Referenced by CheckT2QueueSize().