var dir_f25b46aff9dd2800f353f0cc2534eabd =
[
    [ "aloha-noack-mac-header.cc", "aloha-noack-mac-header_8cc.html", null ],
    [ "aloha-noack-mac-header.h", "aloha-noack-mac-header_8h.html", null ],
    [ "aloha-noack-net-device.cc", "aloha-noack-net-device_8cc.html", "aloha-noack-net-device_8cc" ],
    [ "aloha-noack-net-device.h", "aloha-noack-net-device_8h.html", null ],
    [ "constant-spectrum-propagation-loss.cc", "constant-spectrum-propagation-loss_8cc.html", null ],
    [ "constant-spectrum-propagation-loss.h", "constant-spectrum-propagation-loss_8h.html", null ],
    [ "friis-spectrum-propagation-loss.cc", "friis-spectrum-propagation-loss_8cc.html", null ],
    [ "friis-spectrum-propagation-loss.h", "friis-spectrum-propagation-loss_8h.html", null ],
    [ "half-duplex-ideal-phy-signal-parameters.cc", "half-duplex-ideal-phy-signal-parameters_8cc.html", null ],
    [ "half-duplex-ideal-phy-signal-parameters.h", "half-duplex-ideal-phy-signal-parameters_8h.html", null ],
    [ "half-duplex-ideal-phy.cc", "half-duplex-ideal-phy_8cc.html", "half-duplex-ideal-phy_8cc" ],
    [ "half-duplex-ideal-phy.h", "half-duplex-ideal-phy_8h.html", null ],
    [ "microwave-oven-spectrum-value-helper.cc", "microwave-oven-spectrum-value-helper_8cc.html", "microwave-oven-spectrum-value-helper_8cc" ],
    [ "microwave-oven-spectrum-value-helper.h", "microwave-oven-spectrum-value-helper_8h.html", null ],
    [ "multi-model-spectrum-channel.cc", "multi-model-spectrum-channel_8cc.html", "multi-model-spectrum-channel_8cc" ],
    [ "multi-model-spectrum-channel.h", "multi-model-spectrum-channel_8h.html", "multi-model-spectrum-channel_8h" ],
    [ "non-communicating-net-device.cc", "non-communicating-net-device_8cc.html", null ],
    [ "non-communicating-net-device.h", "non-communicating-net-device_8h.html", null ],
    [ "single-model-spectrum-channel.cc", "single-model-spectrum-channel_8cc.html", null ],
    [ "single-model-spectrum-channel.h", "single-model-spectrum-channel_8h.html", null ],
    [ "spectrum-analyzer.cc", "spectrum-analyzer_8cc.html", null ],
    [ "spectrum-analyzer.h", "spectrum-analyzer_8h.html", null ],
    [ "spectrum-channel.cc", "spectrum-channel_8cc.html", null ],
    [ "spectrum-channel.h", "spectrum-channel_8h.html", null ],
    [ "spectrum-converter.cc", "spectrum-converter_8cc.html", null ],
    [ "spectrum-converter.h", "spectrum-converter_8h.html", null ],
    [ "spectrum-error-model.cc", "spectrum-error-model_8cc.html", null ],
    [ "spectrum-error-model.h", "spectrum-error-model_8h.html", null ],
    [ "spectrum-interference.cc", "spectrum-interference_8cc.html", null ],
    [ "spectrum-interference.h", "spectrum-interference_8h.html", null ],
    [ "spectrum-model-300kHz-300GHz-log.cc", "spectrum-model-300k_hz-300_g_hz-log_8cc.html", "spectrum-model-300k_hz-300_g_hz-log_8cc" ],
    [ "spectrum-model-300kHz-300GHz-log.h", "spectrum-model-300k_hz-300_g_hz-log_8h.html", null ],
    [ "spectrum-model-ism2400MHz-res1MHz.cc", "spectrum-model-ism2400_m_hz-res1_m_hz_8cc.html", "spectrum-model-ism2400_m_hz-res1_m_hz_8cc" ],
    [ "spectrum-model-ism2400MHz-res1MHz.h", "spectrum-model-ism2400_m_hz-res1_m_hz_8h.html", null ],
    [ "spectrum-model.cc", "spectrum-model_8cc.html", "spectrum-model_8cc" ],
    [ "spectrum-model.h", "spectrum-model_8h.html", "spectrum-model_8h" ],
    [ "spectrum-phy.cc", "spectrum-phy_8cc.html", null ],
    [ "spectrum-phy.h", "spectrum-phy_8h.html", null ],
    [ "spectrum-propagation-loss-model.cc", "spectrum-propagation-loss-model_8cc.html", null ],
    [ "spectrum-propagation-loss-model.h", "spectrum-propagation-loss-model_8h.html", null ],
    [ "spectrum-signal-parameters.cc", "spectrum-signal-parameters_8cc.html", null ],
    [ "spectrum-signal-parameters.h", "spectrum-signal-parameters_8h.html", null ],
    [ "spectrum-value.cc", "spectrum-value_8cc.html", "spectrum-value_8cc" ],
    [ "spectrum-value.h", "spectrum-value_8h.html", "spectrum-value_8h" ],
    [ "three-gpp-channel-model.cc", "three-gpp-channel-model_8cc.html", "three-gpp-channel-model_8cc" ],
    [ "three-gpp-channel-model.h", "three-gpp-channel-model_8h.html", [
      [ "ParamsTable", "structns3_1_1_three_gpp_channel_model_1_1_params_table.html", "structns3_1_1_three_gpp_channel_model_1_1_params_table" ],
      [ "ThreeGppChannelMatrix", "structns3_1_1_three_gpp_channel_model_1_1_three_gpp_channel_matrix.html", "structns3_1_1_three_gpp_channel_model_1_1_three_gpp_channel_matrix" ]
    ] ],
    [ "three-gpp-spectrum-propagation-loss-model.cc", "three-gpp-spectrum-propagation-loss-model_8cc.html", null ],
    [ "three-gpp-spectrum-propagation-loss-model.h", "three-gpp-spectrum-propagation-loss-model_8h.html", [
      [ "LongTerm", "structns3_1_1_three_gpp_spectrum_propagation_loss_model_1_1_long_term.html", "structns3_1_1_three_gpp_spectrum_propagation_loss_model_1_1_long_term" ]
    ] ],
    [ "trace-fading-loss-model.cc", "trace-fading-loss-model_8cc.html", null ],
    [ "trace-fading-loss-model.h", "trace-fading-loss-model_8h.html", null ],
    [ "tv-spectrum-transmitter.cc", "tv-spectrum-transmitter_8cc.html", "tv-spectrum-transmitter_8cc" ],
    [ "tv-spectrum-transmitter.h", "tv-spectrum-transmitter_8h.html", null ],
    [ "waveform-generator.cc", "waveform-generator_8cc.html", null ],
    [ "waveform-generator.h", "waveform-generator_8h.html", null ],
    [ "wifi-spectrum-value-helper.cc", "wifi-spectrum-value-helper_8cc.html", "wifi-spectrum-value-helper_8cc" ],
    [ "wifi-spectrum-value-helper.h", "wifi-spectrum-value-helper_8h.html", null ]
];