var dir_a444d77082d8b776da6eccf888b54154 =
[
    [ "aarf-wifi-manager.cc", "aarf-wifi-manager_8cc.html", "aarf-wifi-manager_8cc" ],
    [ "aarf-wifi-manager.h", "aarf-wifi-manager_8h.html", null ],
    [ "aarfcd-wifi-manager.cc", "aarfcd-wifi-manager_8cc.html", "aarfcd-wifi-manager_8cc" ],
    [ "aarfcd-wifi-manager.h", "aarfcd-wifi-manager_8h.html", null ],
    [ "adhoc-wifi-mac.cc", "adhoc-wifi-mac_8cc.html", null ],
    [ "adhoc-wifi-mac.h", "adhoc-wifi-mac_8h.html", null ],
    [ "ampdu-subframe-header.cc", "ampdu-subframe-header_8cc.html", null ],
    [ "ampdu-subframe-header.h", "ampdu-subframe-header_8h.html", null ],
    [ "ampdu-tag.cc", "ampdu-tag_8cc.html", null ],
    [ "ampdu-tag.h", "ampdu-tag_8h.html", null ],
    [ "amrr-wifi-manager.cc", "amrr-wifi-manager_8cc.html", "amrr-wifi-manager_8cc" ],
    [ "amrr-wifi-manager.h", "amrr-wifi-manager_8h.html", null ],
    [ "amsdu-subframe-header.cc", "amsdu-subframe-header_8cc.html", null ],
    [ "amsdu-subframe-header.h", "amsdu-subframe-header_8h.html", null ],
    [ "ap-wifi-mac.cc", "ap-wifi-mac_8cc.html", null ],
    [ "ap-wifi-mac.h", "ap-wifi-mac_8h.html", null ],
    [ "aparf-wifi-manager.cc", "aparf-wifi-manager_8cc.html", "aparf-wifi-manager_8cc" ],
    [ "aparf-wifi-manager.h", "aparf-wifi-manager_8h.html", null ],
    [ "arf-wifi-manager.cc", "arf-wifi-manager_8cc.html", "arf-wifi-manager_8cc" ],
    [ "arf-wifi-manager.h", "arf-wifi-manager_8h.html", null ],
    [ "block-ack-agreement.cc", "block-ack-agreement_8cc.html", null ],
    [ "block-ack-agreement.h", "block-ack-agreement_8h.html", null ],
    [ "block-ack-cache.cc", "block-ack-cache_8cc.html", "block-ack-cache_8cc" ],
    [ "block-ack-cache.h", "block-ack-cache_8h.html", null ],
    [ "block-ack-manager.cc", "block-ack-manager_8cc.html", null ],
    [ "block-ack-manager.h", "block-ack-manager_8h.html", null ],
    [ "block-ack-type.h", "block-ack-type_8h.html", "block-ack-type_8h" ],
    [ "block-ack-window.cc", "block-ack-window_8cc.html", null ],
    [ "block-ack-window.h", "block-ack-window_8h.html", null ],
    [ "capability-information.cc", "capability-information_8cc.html", null ],
    [ "capability-information.h", "capability-information_8h.html", null ],
    [ "cara-wifi-manager.cc", "cara-wifi-manager_8cc.html", "cara-wifi-manager_8cc" ],
    [ "cara-wifi-manager.h", "cara-wifi-manager_8h.html", null ],
    [ "cf-parameter-set.cc", "cf-parameter-set_8cc.html", "cf-parameter-set_8cc" ],
    [ "cf-parameter-set.h", "cf-parameter-set_8h.html", "cf-parameter-set_8h" ],
    [ "channel-access-manager.cc", "channel-access-manager_8cc.html", [
      [ "PhyListener", "classns3_1_1_phy_listener.html", "classns3_1_1_phy_listener" ]
    ] ],
    [ "channel-access-manager.h", "channel-access-manager_8h.html", null ],
    [ "constant-obss-pd-algorithm.cc", "constant-obss-pd-algorithm_8cc.html", null ],
    [ "constant-obss-pd-algorithm.h", "constant-obss-pd-algorithm_8h.html", null ],
    [ "constant-rate-wifi-manager.cc", "constant-rate-wifi-manager_8cc.html", "constant-rate-wifi-manager_8cc" ],
    [ "constant-rate-wifi-manager.h", "constant-rate-wifi-manager_8h.html", null ],
    [ "constant-wifi-ack-policy-selector.cc", "constant-wifi-ack-policy-selector_8cc.html", null ],
    [ "constant-wifi-ack-policy-selector.h", "constant-wifi-ack-policy-selector_8h.html", null ],
    [ "ctrl-headers.cc", "ctrl-headers_8cc.html", null ],
    [ "ctrl-headers.h", "ctrl-headers_8h.html", null ],
    [ "dsss-error-rate-model.cc", "dsss-error-rate-model_8cc.html", null ],
    [ "dsss-error-rate-model.h", "dsss-error-rate-model_8h.html", null ],
    [ "dsss-parameter-set.cc", "dsss-parameter-set_8cc.html", null ],
    [ "dsss-parameter-set.h", "dsss-parameter-set_8h.html", null ],
    [ "edca-parameter-set.cc", "edca-parameter-set_8cc.html", null ],
    [ "edca-parameter-set.h", "edca-parameter-set_8h.html", null ],
    [ "erp-information.cc", "erp-information_8cc.html", "erp-information_8cc" ],
    [ "erp-information.h", "erp-information_8h.html", "erp-information_8h" ],
    [ "error-rate-model.cc", "error-rate-model_8cc.html", null ],
    [ "error-rate-model.h", "error-rate-model_8h.html", null ],
    [ "extended-capabilities.cc", "extended-capabilities_8cc.html", "extended-capabilities_8cc" ],
    [ "extended-capabilities.h", "extended-capabilities_8h.html", "extended-capabilities_8h" ],
    [ "frame-capture-model.cc", "frame-capture-model_8cc.html", null ],
    [ "frame-capture-model.h", "frame-capture-model_8h.html", null ],
    [ "he-capabilities.cc", "he-capabilities_8cc.html", "he-capabilities_8cc" ],
    [ "he-capabilities.h", "he-capabilities_8h.html", "he-capabilities_8h" ],
    [ "he-configuration.cc", "he-configuration_8cc.html", null ],
    [ "he-configuration.h", "he-configuration_8h.html", null ],
    [ "he-operation.cc", "he-operation_8cc.html", "he-operation_8cc" ],
    [ "he-operation.h", "he-operation_8h.html", "he-operation_8h" ],
    [ "ht-capabilities.cc", "ht-capabilities_8cc.html", "ht-capabilities_8cc" ],
    [ "ht-capabilities.h", "ht-capabilities_8h.html", "ht-capabilities_8h" ],
    [ "ht-configuration.cc", "ht-configuration_8cc.html", null ],
    [ "ht-configuration.h", "ht-configuration_8h.html", null ],
    [ "ht-operation.cc", "ht-operation_8cc.html", "ht-operation_8cc" ],
    [ "ht-operation.h", "ht-operation_8h.html", "ht-operation_8h" ],
    [ "ideal-wifi-manager.cc", "ideal-wifi-manager_8cc.html", "ideal-wifi-manager_8cc" ],
    [ "ideal-wifi-manager.h", "ideal-wifi-manager_8h.html", null ],
    [ "infrastructure-wifi-mac.cc", "infrastructure-wifi-mac_8cc.html", null ],
    [ "infrastructure-wifi-mac.h", "infrastructure-wifi-mac_8h.html", null ],
    [ "interference-helper.cc", "interference-helper_8cc.html", "interference-helper_8cc" ],
    [ "interference-helper.h", "interference-helper_8h.html", "interference-helper_8h" ],
    [ "mac-low-transmission-parameters.cc", "mac-low-transmission-parameters_8cc.html", "mac-low-transmission-parameters_8cc" ],
    [ "mac-low-transmission-parameters.h", "mac-low-transmission-parameters_8h.html", "mac-low-transmission-parameters_8h" ],
    [ "mac-low.cc", "mac-low_8cc.html", "mac-low_8cc" ],
    [ "mac-low.h", "mac-low_8h.html", [
      [ "CfAckInfo", "structns3_1_1_mac_low_1_1_cf_ack_info.html", "structns3_1_1_mac_low_1_1_cf_ack_info" ]
    ] ],
    [ "mac-rx-middle.cc", "mac-rx-middle_8cc.html", [
      [ "OriginatorRxStatus", "classns3_1_1_originator_rx_status.html", "classns3_1_1_originator_rx_status" ]
    ] ],
    [ "mac-rx-middle.h", "mac-rx-middle_8h.html", null ],
    [ "mac-tx-middle.cc", "mac-tx-middle_8cc.html", null ],
    [ "mac-tx-middle.h", "mac-tx-middle_8h.html", null ],
    [ "mgt-headers.cc", "mgt-headers_8cc.html", null ],
    [ "mgt-headers.h", "mgt-headers_8h.html", [
      [ "ActionValue", "unionns3_1_1_wifi_action_header_1_1_action_value.html", "unionns3_1_1_wifi_action_header_1_1_action_value" ]
    ] ],
    [ "minstrel-ht-wifi-manager.cc", "minstrel-ht-wifi-manager_8cc.html", "minstrel-ht-wifi-manager_8cc" ],
    [ "minstrel-ht-wifi-manager.h", "minstrel-ht-wifi-manager_8h.html", "minstrel-ht-wifi-manager_8h" ],
    [ "minstrel-wifi-manager.cc", "minstrel-wifi-manager_8cc.html", "minstrel-wifi-manager_8cc" ],
    [ "minstrel-wifi-manager.h", "minstrel-wifi-manager_8h.html", "minstrel-wifi-manager_8h" ],
    [ "mpdu-aggregator.cc", "mpdu-aggregator_8cc.html", null ],
    [ "mpdu-aggregator.h", "mpdu-aggregator_8h.html", null ],
    [ "msdu-aggregator.cc", "msdu-aggregator_8cc.html", null ],
    [ "msdu-aggregator.h", "msdu-aggregator_8h.html", null ],
    [ "nist-error-rate-model.cc", "nist-error-rate-model_8cc.html", null ],
    [ "nist-error-rate-model.h", "nist-error-rate-model_8h.html", null ],
    [ "obss-pd-algorithm.cc", "obss-pd-algorithm_8cc.html", null ],
    [ "obss-pd-algorithm.h", "obss-pd-algorithm_8h.html", null ],
    [ "onoe-wifi-manager.cc", "onoe-wifi-manager_8cc.html", "onoe-wifi-manager_8cc" ],
    [ "onoe-wifi-manager.h", "onoe-wifi-manager_8h.html", null ],
    [ "originator-block-ack-agreement.cc", "originator-block-ack-agreement_8cc.html", null ],
    [ "originator-block-ack-agreement.h", "originator-block-ack-agreement_8h.html", null ],
    [ "parf-wifi-manager.cc", "parf-wifi-manager_8cc.html", "parf-wifi-manager_8cc" ],
    [ "parf-wifi-manager.h", "parf-wifi-manager_8h.html", null ],
    [ "preamble-detection-model.cc", "preamble-detection-model_8cc.html", null ],
    [ "preamble-detection-model.h", "preamble-detection-model_8h.html", null ],
    [ "qos-blocked-destinations.cc", "qos-blocked-destinations_8cc.html", null ],
    [ "qos-blocked-destinations.h", "qos-blocked-destinations_8h.html", [
      [ "QosBlockedDestinations", "classns3_1_1_qos_blocked_destinations.html", "classns3_1_1_qos_blocked_destinations" ]
    ] ],
    [ "qos-txop.cc", "qos-txop_8cc.html", "qos-txop_8cc" ],
    [ "qos-txop.h", "qos-txop_8h.html", "qos-txop_8h" ],
    [ "qos-utils.cc", "qos-utils_8cc.html", "qos-utils_8cc" ],
    [ "qos-utils.h", "qos-utils_8h.html", "qos-utils_8h" ],
    [ "regular-wifi-mac.cc", "regular-wifi-mac_8cc.html", null ],
    [ "regular-wifi-mac.h", "regular-wifi-mac_8h.html", null ],
    [ "rraa-wifi-manager.cc", "rraa-wifi-manager_8cc.html", "rraa-wifi-manager_8cc" ],
    [ "rraa-wifi-manager.h", "rraa-wifi-manager_8h.html", "rraa-wifi-manager_8h" ],
    [ "rrpaa-wifi-manager.cc", "rrpaa-wifi-manager_8cc.html", [
      [ "RrpaaWifiRemoteStation", "structns3_1_1_rrpaa_wifi_remote_station.html", "structns3_1_1_rrpaa_wifi_remote_station" ]
    ] ],
    [ "rrpaa-wifi-manager.h", "rrpaa-wifi-manager_8h.html", "rrpaa-wifi-manager_8h" ],
    [ "simple-frame-capture-model.cc", "simple-frame-capture-model_8cc.html", null ],
    [ "simple-frame-capture-model.h", "simple-frame-capture-model_8h.html", null ],
    [ "snr-tag.cc", "snr-tag_8cc.html", null ],
    [ "snr-tag.h", "snr-tag_8h.html", [
      [ "SnrTag", "classns3_1_1_snr_tag.html", "classns3_1_1_snr_tag" ]
    ] ],
    [ "spectrum-wifi-phy.cc", "spectrum-wifi-phy_8cc.html", null ],
    [ "spectrum-wifi-phy.h", "spectrum-wifi-phy_8h.html", null ],
    [ "ssid.cc", "ssid_8cc.html", "ssid_8cc" ],
    [ "ssid.h", "ssid_8h.html", "ssid_8h" ],
    [ "sta-wifi-mac.cc", "sta-wifi-mac_8cc.html", null ],
    [ "sta-wifi-mac.h", "sta-wifi-mac_8h.html", null ],
    [ "status-code.cc", "status-code_8cc.html", "status-code_8cc" ],
    [ "status-code.h", "status-code_8h.html", "status-code_8h" ],
    [ "supported-rates.cc", "supported-rates_8cc.html", "supported-rates_8cc" ],
    [ "supported-rates.h", "supported-rates_8h.html", "supported-rates_8h" ],
    [ "threshold-preamble-detection-model.cc", "threshold-preamble-detection-model_8cc.html", null ],
    [ "threshold-preamble-detection-model.h", "threshold-preamble-detection-model_8h.html", null ],
    [ "tx-vector-tag.cc", "tx-vector-tag_8cc.html", null ],
    [ "tx-vector-tag.h", "tx-vector-tag_8h.html", [
      [ "HighLatencyCtsToSelfTxVectorTag", "classns3_1_1_high_latency_cts_to_self_tx_vector_tag.html", "classns3_1_1_high_latency_cts_to_self_tx_vector_tag" ],
      [ "HighLatencyDataTxVectorTag", "classns3_1_1_high_latency_data_tx_vector_tag.html", "classns3_1_1_high_latency_data_tx_vector_tag" ],
      [ "HighLatencyRtsTxVectorTag", "classns3_1_1_high_latency_rts_tx_vector_tag.html", "classns3_1_1_high_latency_rts_tx_vector_tag" ]
    ] ],
    [ "txop.cc", "txop_8cc.html", "txop_8cc" ],
    [ "txop.h", "txop_8h.html", null ],
    [ "vht-capabilities.cc", "vht-capabilities_8cc.html", "vht-capabilities_8cc" ],
    [ "vht-capabilities.h", "vht-capabilities_8h.html", "vht-capabilities_8h" ],
    [ "vht-configuration.cc", "vht-configuration_8cc.html", null ],
    [ "vht-configuration.h", "vht-configuration_8h.html", null ],
    [ "vht-operation.cc", "vht-operation_8cc.html", "vht-operation_8cc" ],
    [ "vht-operation.h", "vht-operation_8h.html", "vht-operation_8h" ],
    [ "wifi-ack-policy-selector.cc", "wifi-ack-policy-selector_8cc.html", null ],
    [ "wifi-ack-policy-selector.h", "wifi-ack-policy-selector_8h.html", null ],
    [ "wifi-information-element-vector.cc", "wifi-information-element-vector_8cc.html", null ],
    [ "wifi-information-element-vector.h", "wifi-information-element-vector_8h.html", null ],
    [ "wifi-information-element.cc", "wifi-information-element_8cc.html", null ],
    [ "wifi-information-element.h", "wifi-information-element_8h.html", "wifi-information-element_8h" ],
    [ "wifi-mac-header.cc", "wifi-mac-header_8cc.html", "wifi-mac-header_8cc" ],
    [ "wifi-mac-header.h", "wifi-mac-header_8h.html", "wifi-mac-header_8h" ],
    [ "wifi-mac-queue-item.cc", "wifi-mac-queue-item_8cc.html", "wifi-mac-queue-item_8cc" ],
    [ "wifi-mac-queue-item.h", "wifi-mac-queue-item_8h.html", "wifi-mac-queue-item_8h" ],
    [ "wifi-mac-queue.cc", "wifi-mac-queue_8cc.html", null ],
    [ "wifi-mac-queue.h", "wifi-mac-queue_8h.html", null ],
    [ "wifi-mac-trailer.cc", "wifi-mac-trailer_8cc.html", null ],
    [ "wifi-mac-trailer.h", "wifi-mac-trailer_8h.html", "wifi-mac-trailer_8h" ],
    [ "wifi-mac.cc", "wifi-mac_8cc.html", null ],
    [ "wifi-mac.h", "wifi-mac_8h.html", null ],
    [ "wifi-mode.cc", "wifi-mode_8cc.html", "wifi-mode_8cc" ],
    [ "wifi-mode.h", "wifi-mode_8h.html", "wifi-mode_8h" ],
    [ "wifi-mpdu-type.h", "wifi-mpdu-type_8h.html", "wifi-mpdu-type_8h" ],
    [ "wifi-net-device.cc", "wifi-net-device_8cc.html", null ],
    [ "wifi-net-device.h", "wifi-net-device_8h.html", "wifi-net-device_8h" ],
    [ "wifi-phy-header.cc", "wifi-phy-header_8cc.html", null ],
    [ "wifi-phy-header.h", "wifi-phy-header_8h.html", null ],
    [ "wifi-phy-listener.h", "wifi-phy-listener_8h.html", [
      [ "WifiPhyListener", "classns3_1_1_wifi_phy_listener.html", "classns3_1_1_wifi_phy_listener" ]
    ] ],
    [ "wifi-phy-standard.h", "wifi-phy-standard_8h.html", "wifi-phy-standard_8h" ],
    [ "wifi-phy-state-helper.cc", "wifi-phy-state-helper_8cc.html", null ],
    [ "wifi-phy-state-helper.h", "wifi-phy-state-helper_8h.html", "wifi-phy-state-helper_8h" ],
    [ "wifi-phy-state.h", "wifi-phy-state_8h.html", "wifi-phy-state_8h" ],
    [ "wifi-phy-tag.cc", "wifi-phy-tag_8cc.html", null ],
    [ "wifi-phy-tag.h", "wifi-phy-tag_8h.html", null ],
    [ "wifi-phy.cc", "wifi-phy_8cc.html", "wifi-phy_8cc" ],
    [ "wifi-phy.h", "wifi-phy_8h.html", "wifi-phy_8h" ],
    [ "wifi-ppdu.cc", "wifi-ppdu_8cc.html", "wifi-ppdu_8cc" ],
    [ "wifi-ppdu.h", "wifi-ppdu_8h.html", "wifi-ppdu_8h" ],
    [ "wifi-preamble.h", "wifi-preamble_8h.html", "wifi-preamble_8h" ],
    [ "wifi-psdu.cc", "wifi-psdu_8cc.html", "wifi-psdu_8cc" ],
    [ "wifi-psdu.h", "wifi-psdu_8h.html", "wifi-psdu_8h" ],
    [ "wifi-radio-energy-model.cc", "wifi-radio-energy-model_8cc.html", null ],
    [ "wifi-radio-energy-model.h", "wifi-radio-energy-model_8h.html", null ],
    [ "wifi-remote-station-info.cc", "wifi-remote-station-info_8cc.html", null ],
    [ "wifi-remote-station-info.h", "wifi-remote-station-info_8h.html", [
      [ "WifiRemoteStationInfo", "classns3_1_1_wifi_remote_station_info.html", "classns3_1_1_wifi_remote_station_info" ]
    ] ],
    [ "wifi-remote-station-manager.cc", "wifi-remote-station-manager_8cc.html", null ],
    [ "wifi-remote-station-manager.h", "wifi-remote-station-manager_8h.html", [
      [ "WifiRemoteStation", "structns3_1_1_wifi_remote_station.html", "structns3_1_1_wifi_remote_station" ],
      [ "WifiRemoteStationState", "structns3_1_1_wifi_remote_station_state.html", "structns3_1_1_wifi_remote_station_state" ]
    ] ],
    [ "wifi-spectrum-phy-interface.cc", "wifi-spectrum-phy-interface_8cc.html", null ],
    [ "wifi-spectrum-phy-interface.h", "wifi-spectrum-phy-interface_8h.html", null ],
    [ "wifi-spectrum-signal-parameters.cc", "wifi-spectrum-signal-parameters_8cc.html", null ],
    [ "wifi-spectrum-signal-parameters.h", "wifi-spectrum-signal-parameters_8h.html", null ],
    [ "wifi-tx-current-model.cc", "wifi-tx-current-model_8cc.html", null ],
    [ "wifi-tx-current-model.h", "wifi-tx-current-model_8h.html", null ],
    [ "wifi-tx-vector.cc", "wifi-tx-vector_8cc.html", "wifi-tx-vector_8cc" ],
    [ "wifi-tx-vector.h", "wifi-tx-vector_8h.html", "wifi-tx-vector_8h" ],
    [ "wifi-utils.cc", "wifi-utils_8cc.html", "wifi-utils_8cc" ],
    [ "wifi-utils.h", "wifi-utils_8h.html", "wifi-utils_8h" ],
    [ "yans-error-rate-model.cc", "yans-error-rate-model_8cc.html", null ],
    [ "yans-error-rate-model.h", "yans-error-rate-model_8h.html", null ],
    [ "yans-wifi-channel.cc", "yans-wifi-channel_8cc.html", null ],
    [ "yans-wifi-channel.h", "yans-wifi-channel_8h.html", null ],
    [ "yans-wifi-phy.cc", "yans-wifi-phy_8cc.html", null ],
    [ "yans-wifi-phy.h", "yans-wifi-phy_8h.html", null ]
];