ns-3: src/network/utils/dynamic-queue-limits.cc File Reference
dynamic-queue-limits.cc File Reference
#include "ns3/log.h"
#include "ns3/uinteger.h"
#include "ns3/simulator.h"
#include "ns3/string.h"
#include "dynamic-queue-limits.h"
Namespaces
ns3
Every class exported by the ns3 library is enclosed in the ns3 namespace.
Variables
static const uint32_t DQL_MAX_LIMIT = (UINTMAX / 2) - DQL_MAX_OBJECT
static const uint32_t DQL_MAX_OBJECT = UINTMAX / 16
static const uint32_t UINTMAX = std::numeric_limits<uint32_t>::max ()
Variable Documentation
DQL_MAX_LIMIT
const uint32_t DQL_MAX_LIMIT = (UINTMAX / 2) - DQL_MAX_OBJECT static
Definition at line 35 of file dynamic-queue-limits.cc.
Referenced by ns3::DynamicQueueLimits::GetTypeId().
DQL_MAX_OBJECT
const uint32_t DQL_MAX_OBJECT = UINTMAX / 16 static
Definition at line 34 of file dynamic-queue-limits.cc.
Referenced by ns3::DynamicQueueLimits::Queued().
UINTMAX
const uint32_t UINTMAX = std::numeric_limits<uint32_t>::max () static
Definition at line 33 of file dynamic-queue-limits.cc.
Referenced by ns3::DynamicQueueLimits::Completed(), and ns3::DynamicQueueLimits::Reset().