ns-3: examples/energy/energy-model-with-harvesting-example.cc File Reference
energy-model-with-harvesting-example.cc File Reference
#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/mobility-module.h"
#include "ns3/config-store-module.h"
#include "ns3/energy-module.h"
#include "ns3/internet-module.h"
#include "ns3/yans-wifi-helper.h"
#include "ns3/wifi-radio-energy-model-helper.h"
Functions
static void GenerateTraffic (Ptr< Socket > socket, uint32_t pktSize, Ptr< Node > n, uint32_t pktCount, Time pktInterval)
void HarvestedPower (double oldValue, double harvestedPower)
Trace function for the power harvested by the energy harvester.
static std::string PrintReceivedPacket (Address &from)
void ReceivePacket (Ptr< Socket > socket)
void RemainingEnergy (double oldValue, double remainingEnergy)
Trace function for remaining energy at node.
void TotalEnergy (double oldValue, double totalEnergy)
Trace function for total energy consumption at node.
void TotalEnergyHarvested (double oldValue, double TotalEnergyHarvested)
Trace function for the total energy harvested by the node.
Function Documentation
GenerateTraffic()
static void GenerateTraffic (Ptr< Socket > socket, uint32_t pktSize, Ptr< Node > n, uint32_t pktCount, Time pktInterval) static
Parameters
socket Pointer to socket.
pktSize Packet size.
n Pointer to node.
pktCount Number of packets to generate.
pktInterval Packet sending interval.
Traffic generator.
Definition at line 110 of file energy-model-with-harvesting-example.cc.
References ns3::Socket::Close(), sample-rng-plot::n, ns3::Simulator::Schedule(), and ns3::Socket::Send().
HarvestedPower()
void HarvestedPower (double oldValue, double harvestedPower)
Trace function for the power harvested by the energy harvester.
Definition at line 143 of file energy-model-with-harvesting-example.cc.
References ns3::Simulator::Now(), and NS_LOG_UNCOND.
PrintReceivedPacket()
static std::string PrintReceivedPacket (Address & from) inline static
Definition at line 68 of file energy-model-with-harvesting-example.cc.
References ns3::InetSocketAddress::ConvertFrom(), ns3::InetSocketAddress::GetIpv4(), ns3::InetSocketAddress::GetPort(), ns3::Time::GetSeconds(), and ns3::Simulator::Now().
Referenced by ReceivePacket().
ReceivePacket()
void ReceivePacket (Ptr< Socket > socket)
Parameters
socket Pointer to socket.
Packet receiving sink.
Definition at line 87 of file energy-model-with-harvesting-example.cc.
References ns3::Packet::GetSize(), NS_LOG_UNCOND, PrintReceivedPacket(), and ns3::Socket::RecvFrom().
RemainingEnergy()
void RemainingEnergy (double oldValue, double remainingEnergy)
Trace function for remaining energy at node.
Definition at line 127 of file energy-model-with-harvesting-example.cc.
References ns3::Simulator::Now(), and NS_LOG_UNCOND.
TotalEnergy()
void TotalEnergy (double oldValue, double totalEnergy)
Trace function for total energy consumption at node.
Definition at line 135 of file energy-model-with-harvesting-example.cc.
References ns3::Simulator::Now(), and NS_LOG_UNCOND.
TotalEnergyHarvested()
void TotalEnergyHarvested (double oldValue, double TotalEnergyHarvested)
Trace function for the total energy harvested by the node.
Definition at line 151 of file energy-model-with-harvesting-example.cc.
References ns3::Simulator::Now(), and NS_LOG_UNCOND.