ns-3: src/network/test/error-model-test-suite.cc File Reference
error-model-test-suite.cc File Reference
#include "ns3/test.h"
#include "ns3/simple-net-device.h"
#include "ns3/simple-channel.h"
#include "ns3/address.h"
#include "ns3/mac48-address.h"
#include "ns3/packet.h"
#include "ns3/callback.h"
#include "ns3/node.h"
#include "ns3/simulator.h"
#include "ns3/error-model.h"
#include "ns3/pointer.h"
#include "ns3/double.h"
#include "ns3/string.h"
#include "ns3/rng-seed-manager.h"
Classes
class BurstErrorModelSimple
class ErrorModelSimple
class ErrorModelTestSuite
ErrorModel TestSuite.
Functions
static void BuildSimpleTopology (Ptr< Node > a, Ptr< Node > b, Ptr< SimpleNetDevice > input, Ptr< SimpleNetDevice > output, Ptr< SimpleChannel > channel)
static void SendPacket (int num, Ptr< NetDevice > device, Address &addr)
Variables
static ErrorModelTestSuite errorModelTestSuite
Static variable for test initialization.
Function Documentation
BuildSimpleTopology()
static void BuildSimpleTopology (Ptr< Node > a, Ptr< Node > b, Ptr< SimpleNetDevice > input, Ptr< SimpleNetDevice > output, Ptr< SimpleChannel > channel) static
Definition at line 55 of file error-model-test-suite.cc.
References ns3::Node::AddDevice(), ns3::Mac48Address::Allocate(), third::channel, ns3::SimpleNetDevice::SetAddress(), ns3::SimpleNetDevice::SetChannel(), and ns3::SimpleNetDevice::SetNode().
Referenced by ErrorModelSimple::DoRun(), and BurstErrorModelSimple::DoRun().
SendPacket()
static void SendPacket (int num, Ptr< NetDevice > device, Address & addr) static
Definition at line 45 of file error-model-test-suite.cc.
References ns3::NetDevice::Send().
Referenced by ErrorModelSimple::DoRun(), and BurstErrorModelSimple::DoRun().
Variable Documentation
errorModelTestSuite
ErrorModelTestSuite errorModelTestSuite static
Static variable for test initialization.
Definition at line 289 of file error-model-test-suite.cc.