ns-3: src/internet/model/global-router-interface.cc File Reference
global-router-interface.cc File Reference
#include "ns3/log.h"
#include "ns3/assert.h"
#include "ns3/abort.h"
#include "ns3/channel.h"
#include "ns3/net-device.h"
#include "ns3/node.h"
#include "ns3/node-list.h"
#include "ns3/ipv4.h"
#include "ns3/bridge-net-device.h"
#include "ipv4-global-routing.h"
#include "global-router-interface.h"
#include "loopback-net-device.h"
#include <vector>
Namespaces
ns3
Every class exported by the ns3 library is enclosed in the ns3 namespace.
Functions
pLSA ns3::AddLinkRecord (plr)
ns3::if (desigRtr==addrLocal)
NS_LOG_LOGIC ("Net device "<< nd<< " is not bridged")
std::ostream & ns3::operator<< (std::ostream &os, GlobalRoutingLSA &lsa)
Stream insertion operator.
plr ns3::SetLinkData (addrLocal)
plr ns3::SetLinkId (desigRtr)
plr ns3::SetMetric (metricLocal)
Variables
ns3::plr = 0
return
Function Documentation
NS_LOG_LOGIC()
NS_LOG_LOGIC ("Net device "<< nd<< " is not bridged")
Referenced by ns3::EmuEpcHelper::EmuEpcHelper(), LteRrcConnectionEstablishmentTestCase::LteRrcConnectionEstablishmentTestCase(), ns3::MicrowaveOvenSpectrumModel5MhzInitializer::MicrowaveOvenSpectrumModel5MhzInitializer(), ns3::MicrowaveOvenSpectrumModel6MhzInitializer::MicrowaveOvenSpectrumModel6MhzInitializer(), ns3::NoBackhaulEpcHelper::NoBackhaulEpcHelper(), ns3::NscTcpL4Protocol::NscTcpL4Protocol(), ns3::NscTcpSocketImpl::NscTcpSocketImpl(), ns3::SpectrumConverter::SpectrumConverter(), ns3::SPFVertex::SPFVertex(), ns3::TcpL4Protocol::TcpL4Protocol(), ns3::TcpSocketBase::TcpSocketBase(), ns3::TcpWestwood::TcpWestwood(), ns3::TypeId::TypeId(), ns3::AthstatsWifiTraceSink::~AthstatsWifiTraceSink(), ns3::GlobalRouteManagerLSDB::~GlobalRouteManagerLSDB(), ns3::SPFVertex::~SPFVertex(), ns3::HalfDuplexIdealPhy::AbortRx(), ns3::NscTcpSocketImpl::Accept(), ns3::DhcpClient::AcceptAck(), ns3::NoBackhaulEpcHelper::ActivateEpsBearer(), ns3::NamesPriv::Add(), ns3::TcpTxBuffer::Add(), ns3::TcpRxBuffer::Add(), ns3::RadvdHelper::AddAnnouncedPrefix(), ns3::IidManager::AddAttribute(), ns3::TcpLedbat::AddDelay(), ns3::dsr::DsrOptionField::AddDsrOption(), ns3::EmuEpcHelper::AddEnb(), ns3::NoBackhaulEpcHelper::AddEnb(), ns3::PointToPointEpcHelper::AddEnb(), ns3::CsmaNetDevice::AddHeader(), ns3::NscTcpL4Protocol::AddInterface(), ns3::dsr::DsrRouteCache::AddNeighbor(), ns3::OptionField::AddOption(), ns3::TcpSocketBase::AddOptionSack(), ns3::dsr::DsrRouteCache::AddRoute_Link(), ns3::MultiModelSpectrumChannel::AddRx(), ns3::IidManager::AddTraceSource(), ns3::EmuEpcHelper::AddX2Interface(), ns3::NoBackhaulEpcHelper::AddX2Interface(), ns3::TcpSocketBase::AdvertisedWindowSize(), ns3::LteUeRrc::ApplyMeasConfig(), ns3::Ipv4AddressHelper::Assign(), ns3::Ipv6AddressHelper::Assign(), ns3::NscTcpSocketImpl::Bind(), ns3::TcpSocketBase::Bind(), ns3::NscTcpSocketImpl::Bind6(), ns3::GlobalRouter::BridgeHasAlreadyBeenVisited(), ns3::BriteTopologyHelper::BuildBriteTopology(), ns3::GlobalRouteManagerImpl::BuildGlobalRoutingDatabase(), ns3::GlobalRouter::BuildNetworkLSAs(), TcpYeahDecrementTest::CalculateSsThresh(), ns3::LteUeRrc::CancelEnteringTrigger(), ns3::LteUeRrc::CancelLeavingTrigger(), ns3::LrWpanMac::ChangeMacState(), ns3::LteSpectrumPhy::ChangeState(), ns3::HalfDuplexIdealPhy::ChangeState(), ns3::LrWpanPhy::ChangeTrxState(), ns3::LteHelper::ChannelModelInitialization(), ns3::GlobalRouteManagerImpl::CheckForStubNode(), ns3::dsr::DsrRouting::CheckSendBuffer(), LteX2HandoverMeasuresTestCase::CheckStats(), ns3::dsr::DsrRouteCache::CheckUniqueAckId(), ns3::dsr::DsrRreqTable::CheckUniqueRreqId(), ns3::EpcTftClassifier::Classify(), ns3::PacketFilter::Classify(), ns3::dsr::DsrNetworkQueue::Cleanup(), ns3::Time::Clear(), ns3::GlobalRoutingLSA::ClearLinkRecords(), ns3::GlobalRouter::ClearLSAs(), ns3::Time::ClearMarkedTimes(), ThreeGppHttpObjectTestCase::ClientStateTransitionCallback(), ns3::NscTcpSocketImpl::Close(), ns3::CobaltQueueDisc::CobaltQueueFull(), ns3::NscTcpSocketImpl::CompleteFork(), ns3::SixLowPanNetDevice::CompressLowPanHc1(), ns3::SixLowPanNetDevice::CompressLowPanIphc(), ns3::LteInterference::ConditionallyEvaluateChunk(), ns3::SpectrumInterference::ConditionallyEvaluateChunk(), ns3::Ns2MobilityHelper::ConfigNodesMovements(), ns3::TcpVeno::CongestionStateSet(), ns3::BulkSendApplication::ConnectionFailed(), ns3::NscTcpSocketImpl::ConnectionSucceeded(), ns3::BulkSendApplication::ConnectionSucceeded(), ns3::RadioBearerStatsConnector::ConnectTracesDrbEnb(), ns3::RadioBearerStatsConnector::ConnectTracesDrbUe(), ns3::RadioBearerStatsConnector::ConnectTracesSrb0(), ns3::RadioBearerStatsConnector::ConnectTracesSrb1(), FemtocellBlockAllocator::Create(), ns3::Ipv4GlobalRoutingHelper::Create(), ns3::GridBuildingAllocator::Create(), ns3::PacketMetadata::Create(), ns3::LteAmc::CreateCqiFeedbacks(), ns3::WifiSpectrumValueHelper::CreateRfFilter(), ns3::WifiSpectrumValueHelper::CreateSpectrumMaskForOfdm(), ns3::LteSpectrumValueHelper::CreateTxPowerSpectralDensity(), ns3::LteSpectrumValueHelper::CreateUlTxPowerSpectralDensity(), ns3::SixLowPanNetDevice::DecompressLowPanUdpNhc(), ns3::aodv::RoutingProtocol::DeferredRouteOutput(), ns3::dsr::DsrRouteCache::DeleteAllRoutesIncludeLink(), ns3::GlobalRouteManagerImpl::DeleteGlobalRoutes(), ns3::aodv::RoutingTableEntry::DeletePrecursor(), ns3::aodv::RoutingTable::DeleteRoute(), ns3::dsr::DsrRouteCache::DeleteRoute(), ns3::dsr::DsrNetworkQueue::Dequeue(), ns3::DropTailQueue< Item >::Dequeue(), ns3::Ipv4Header::Deserialize(), ns3::RipHeader::Deserialize(), ns3::RipNgHeader::Deserialize(), ns3::TcpOptionSack::Deserialize(), ns3::PacketMetadata::Deserialize(), ns3::DefaultSimulatorImpl::Destroy(), ns3::RealtimeSimulatorImpl::Destroy(), ns3::DistributedSimulatorImpl::Destroy(), ns3::NullMessageSimulatorImpl::Destroy(), ns3::TcpSocketBase::Destroy(), ns3::TcpSocketBase::Destroy6(), ns3::TapBridge::DiscardFromBridgedDevice(), ns3::TcpTxBuffer::DiscardUpTo(), ns3::GlobalRouter::DiscoverLSAs(), ns3::NoBackhaulEpcHelper::DoAddX2Interface(), ns3::ConstantSpectrumPropagationLossModel::DoCalcRxPowerSpectralDensity(), ns3::ThreeGppSpectrumPropagationLossModel::DoCalcRxPowerSpectralDensity(), ns3::TraceFadingLossModel::DoCalcRxPowerSpectralDensity(), ns3::Queue< Item >::DoDequeue(), ns3::CobaltQueueDisc::DoDequeue(), ns3::CoDelQueueDisc::DoDequeue(), ns3::FifoQueueDisc::DoDequeue(), ns3::PfifoFastQueueDisc::DoDequeue(), ns3::PieQueueDisc::DoDequeue(), ns3::PrioQueueDisc::DoDequeue(), ns3::RedQueueDisc::DoDequeue(), ns3::TbfQueueDisc::DoDequeue(), ns3::Queue< Item >::DoEnqueue(), ns3::CobaltQueueDisc::DoEnqueue(), ns3::CoDelQueueDisc::DoEnqueue(), ns3::FifoQueueDisc::DoEnqueue(), ns3::PfifoFastQueueDisc::DoEnqueue(), ns3::PieQueueDisc::DoEnqueue(), ns3::PrioQueueDisc::DoEnqueue(), ns3::RedQueueDisc::DoEnqueue(), ns3::TbfQueueDisc::DoEnqueue(), ns3::TcpSocketBase::DoForwardUp(), ns3::Ipv4L3Protocol::DoFragmentation(), ns3::SixLowPanNetDevice::DoFragmentation(), ns3::Rip::DoInitialize(), ns3::RipNg::DoInitialize(), ns3::A2A4RsrqHandoverAlgorithm::DoInitialize(), ns3::A3RsrpHandoverAlgorithm::DoInitialize(), ns3::LteAnr::DoInitialize(), ns3::LteFfrDistributedAlgorithm::DoInitialize(), ns3::LteFfrEnhancedAlgorithm::DoInitialize(), ns3::LteFfrSoftAlgorithm::DoInitialize(), ns3::LteFrSoftAlgorithm::DoInitialize(), ns3::LteFrStrictAlgorithm::DoInitialize(), ns3::LteFfrSimple::DoInitialize(), ns3::CalendarScheduler::DoInsert(), ns3::LteRlcAm::DoNotifyTxOpportunity(), ns3::LteRlcTm::DoNotifyTxOpportunity(), ns3::LteRlcUm::DoNotifyTxOpportunity(), ns3::LteRlcSm::DoNotifyTxOpportunity(), ns3::PyViz::DoPause(), ns3::Queue< Item >::DoPeek(), ns3::CobaltQueueDisc::DoPeek(), ns3::FifoQueueDisc::DoPeek(), ns3::PfifoFastQueueDisc::DoPeek(), ns3::PrioQueueDisc::DoPeek(), ns3::RedQueueDisc::DoPeek(), ns3::TcpSocketBase::DoPeerClose(), ns3::FdNetDeviceFdReader::DoRead(), ns3::TapBridgeFdReader::DoRead(), ns3::LteEnbMac::DoReceiveLteControlMessage(), ns3::LteUeMac::DoReceiveLteControlMessage(), ns3::LteTestPdcp::DoReceivePdcpPdu(), ns3::LteRlcAm::DoReceivePdu(), ns3::LteRlcUm::DoReceivePdu(), ns3::LteRlcSm::DoReceivePdu(), ns3::LtePdcp::DoReceivePdu(), ns3::LteEnbRrc::DoRecvHandoverPreparationFailure(), ns3::LteEnbRrc::DoRecvHandoverRequest(), ns3::LteEnbRrc::DoRecvHandoverRequestAck(), ns3::LteEnbRrc::DoRecvLoadInformation(), ns3::LteEnbRrc::DoRecvResourceStatusUpdate(), ns3::LteEnbRrc::DoRecvSnStatusTransfer(), ns3::LteEnbRrc::DoRecvUeContextRelease(), ns3::LteEnbRrc::DoRecvUeData(), ns3::Queue< Item >::DoRemove(), ns3::LteRlcAm::DoReportBufferStatus(), ns3::LteRlcTm::DoReportBufferStatus(), ns3::LteRlcUm::DoReportBufferStatus(), ns3::LteAnr::DoReportUeMeas(), ns3::A3RsrpHandoverAlgorithm::DoReportUeMeas(), LteRadioLinkFailureTestCase::DoRun(), RandomRoomPositionAllocatorTestCase::DoRun(), SameRoomPositionAllocatorTestCase::DoRun(), BuildingsHelperOneTestCase::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), EpcTftClassifierTestCase::DoRun(), WifiOfdmMaskSlopesTestCase::DoRun(), ns3::CqaFfMacScheduler::DoSchedDlCqiInfoReq(), ns3::FdBetFfMacScheduler::DoSchedDlCqiInfoReq(), ns3::FdMtFfMacScheduler::DoSchedDlCqiInfoReq(), ns3::FdTbfqFfMacScheduler::DoSchedDlCqiInfoReq(), ns3::PfFfMacScheduler::DoSchedDlCqiInfoReq(), ns3::PssFfMacScheduler::DoSchedDlCqiInfoReq(), ns3::RrFfMacScheduler::DoSchedDlCqiInfoReq(), ns3::TdBetFfMacScheduler::DoSchedDlCqiInfoReq(), ns3::TdMtFfMacScheduler::DoSchedDlCqiInfoReq(), ns3::TdTbfqFfMacScheduler::DoSchedDlCqiInfoReq(), ns3::TtaFfMacScheduler::DoSchedDlCqiInfoReq(), ns3::RrFfMacScheduler::DoSchedDlTriggerReq(), ns3::CqaFfMacScheduler::DoSchedUlMacCtrlInfoReq(), ns3::FdBetFfMacScheduler::DoSchedUlMacCtrlInfoReq(), ns3::FdMtFfMacScheduler::DoSchedUlMacCtrlInfoReq(), ns3::FdTbfqFfMacScheduler::DoSchedUlMacCtrlInfoReq(), ns3::PfFfMacScheduler::DoSchedUlMacCtrlInfoReq(), ns3::PssFfMacScheduler::DoSchedUlMacCtrlInfoReq(), ns3::TdBetFfMacScheduler::DoSchedUlMacCtrlInfoReq(), ns3::TdMtFfMacScheduler::DoSchedUlMacCtrlInfoReq(), ns3::TdTbfqFfMacScheduler::DoSchedUlMacCtrlInfoReq(), ns3::TtaFfMacScheduler::DoSchedUlMacCtrlInfoReq(), ns3::SixLowPanNetDevice::DoSend(), ns3::LteUeRrc::DoSendData(), ns3::dsr::DsrOptionRerr::DoSendError(), ns3::EpcX2::DoSendHandoverPreparationFailure(), ns3::EpcX2::DoSendHandoverRequest(), ns3::EpcX2::DoSendHandoverRequestAck(), ns3::EpcX2::DoSendLoadInformation(), ns3::EpcX2::DoSendResourceStatusUpdate(), ns3::EpcX2::DoSendSnStatusTransfer(), ns3::LteEnbRrcProtocolIdeal::DoSendSystemInformation(), ns3::LteEnbRrcProtocolReal::DoSendSystemInformation(), ns3::UdpSocketImpl::DoSendTo(), ns3::EpcX2::DoSendUeContextRelease(), ns3::EpcX2::DoSendUeData(), ns3::LteRlcAm::DoTransmitPdcpPdu(), ns3::LteRlcTm::DoTransmitPdcpPdu(), ns3::LteRlcUm::DoTransmitPdcpPdu(), ns3::LtePdcp::DoTransmitPdcpSdu(), ns3::LteTestMac::DoTransmitPdu(), ns3::LteEnbRrc::DoTriggerHandover(), ns3::dsr::DsrErrorBuffer::Drop(), ns3::dsr::DsrPassiveBuffer::Drop(), ns3::dsr::DsrSendBuffer::Drop(), ns3::aodv::RequestQueue::Drop(), ns3::dsdv::PacketQueue::Drop(), ns3::QueueDisc::DropAfterDequeue(), ns3::Queue< Item >::DropAfterDequeue(), ns3::QueueDisc::DropBeforeEnqueue(), ns3::Queue< Item >::DropBeforeEnqueue(), ns3::RedQueueDisc::DropEarly(), ns3::dsr::DsrErrorBuffer::DropLink(), ns3::dsr::DsrPassiveBuffer::DropLink(), ns3::LrWpanPhy::EndCca(), ns3::HalfDuplexIdealPhy::EndRx(), ns3::LrWpanPhy::EndRx(), ns3::LteSpectrumPhy::EndRxData(), ns3::LteSpectrumPhy::EndRxDlCtrl(), ns3::HalfDuplexIdealPhy::EndTx(), ns3::LrWpanPhy::EndTx(), ns3::LteSpectrumPhy::EndTxData(), ns3::LteSpectrumPhy::EndTxDlCtrl(), ns3::LteSpectrumPhy::EndTxUlSrs(), ns3::dsr::DsrNetworkQueue::Enqueue(), ns3::TcpWestwood::EstimateBW(), ns3::LteUeRrc::EvaluateCellForSelection(), ns3::ShannonSpectrumErrorModel::EvaluateChunk(), ns3::A2A4RsrqHandoverAlgorithm::EvaluateHandover(), anonymous_namespace{sample-show-progress.cc}::Hold::Event(), ns3::LteRlcAm::ExpirePollRetransmitTimer(), ns3::LteRlcAm::ExpireRbsTimer(), ns3::LteRlcTm::ExpireRbsTimer(), ns3::LteRlcUm::ExpireRbsTimer(), ns3::LteRlcAm::ExpireReorderingTimer(), ns3::LteRlcUm::ExpireReorderingTimer(), ns3::TcpRxBuffer::Extract(), ns3::TapBridge::Filter(), ns3::NamesPriv::Find(), ns3::MultiModelSpectrumChannel::FindAndEventuallyAddTxSpectrumModel(), ns3::dsr::DsrRreqTable::FindAndUpdate(), ns3::LteStatsCalculator::FindCellIdFromEnbMac(), ns3::LteStatsCalculator::FindCellIdFromEnbRlcPath(), ns3::LteStatsCalculator::FindImsiForEnb(), ns3::LteStatsCalculator::FindImsiForUe(), ns3::LteStatsCalculator::FindImsiFromEnbMac(), ns3::LteStatsCalculator::FindImsiFromEnbRlcPath(), ns3::LteStatsCalculator::FindImsiFromLteNetDevice(), ns3::NamesPriv::FindName(), ns3::GlobalRouteManagerImpl::FindOutgoingInterfaceId(), ns3::NamesPriv::FindPath(), ns3::dsr::DsrRreqTable::FindSourceEntry(), ns3::ArpCache::Flush(), ns3::Icmpv6L4Protocol::ForgeNA(), ns3::Icmpv6L4Protocol::ForgeNS(), ns3::Icmpv6L4Protocol::ForgeRS(), ns3::BridgeNetDevice::ForwardBroadcast(), ns3::olsr::RoutingProtocol::ForwardDefault(), ns3::aodv::RoutingProtocol::Forwarding(), ns3::Ipv4FlowProbe::ForwardLogger(), ns3::dsr::DsrRouting::ForwardPacket(), ns3::TapBridge::ForwardToBridgedDevice(), ns3::BridgeNetDevice::ForwardUnicast(), ns3::Ipv4RawSocketImpl::ForwardUp(), ns3::PacketSocket::ForwardUp(), ns3::TcpSocketBase::ForwardUp(), ns3::FdNetDevice::ForwardUp(), ns3::TcpSocketBase::ForwardUp6(), ns3::Ipv4FlowProbe::ForwardUpLogger(), ns3::Icmpv6L4Protocol::FunctionDadTimeout(), ns3::BriteTopologyHelper::GenerateBriteTopology(), ns3::LteUePhy::GenerateMixedCqiReport(), ns3::WaveformGenerator::GenerateWaveform(), ns3::LteAmc::GetCqiFromSpectralEfficiency(), ns3::LteFfrEnhancedAlgorithm::GetCqiFromSpectralEfficiency(), ns3::LteSpectrumValueHelper::GetDownlinkCarrierBand(), ns3::Building::GetFloor(), ns3::CosineAntennaModel::GetGainDb(), ns3::ParabolicAntennaModel::GetGainDb(), ns3::aodv::RoutingTable::GetListOfDestinationWithNextHop(), ns3::ItuR1238PropagationLossModel::GetLoss(), ns3::ItuR1411LosPropagationLossModel::GetLoss(), ns3::ItuR1411NlosOverRooftopPropagationLossModel::GetLoss(), ns3::LteAmc::GetMcsFromCqi(), ns3::LteNetDevice::GetMulticast(), ns3::CsmaNetDevice::GetMulticast(), ns3::WimaxNetDevice::GetMulticast(), ns3::QueueBase::GetNBytes(), ns3::RandomRoomPositionAllocator::GetNext(), ns3::SameRoomPositionAllocator::GetNext(), ns3::FixedRoomPositionAllocator::GetNext(), ns3::QueueBase::GetNPackets(), ns3::TcpOptionSack::GetNumSackBlocks(), ns3::Ipv4L3Protocol::Fragments::GetPacket(), ns3::SixLowPanNetDevice::Fragments::GetPacket(), ns3::SPFVertex::GetParent(), ns3::Ipv4L3Protocol::Fragments::GetPartialPacket(), ns3::PyViz::GetPauseMessages(), ns3::Time::GetResolution(), ns3::Building::GetRoomX(), ns3::Building::GetRoomY(), ns3::dsr::DsrRreqTable::GetRreqCnt(), ns3::TcpOptionSack::GetSerializedSize(), ns3::LteAmc::GetSpectralEfficiencyFromCqi(), ns3::WifiSpectrumValueHelper::GetSpectrumModel(), ns3::LteSpectrumValueHelper::GetSpectrumModel(), ns3::TcpVeno::GetSsThresh(), ns3::TcpWestwood::GetSsThresh(), ns3::TcpYeah::GetSsThresh(), ns3::Ipv4StaticRoutingHelper::GetStaticRouting(), ns3::Ipv6StaticRoutingHelper::GetStaticRouting(), ns3::LteMiErrorModel::GetTbDecodificationStats(), ns3::QueueBase::GetTotalDroppedBytes(), ns3::QueueBase::GetTotalDroppedBytesAfterDequeue(), ns3::QueueBase::GetTotalDroppedBytesBeforeEnqueue(), ns3::QueueBase::GetTotalDroppedPackets(), ns3::QueueBase::GetTotalDroppedPacketsAfterDequeue(), ns3::QueueBase::GetTotalDroppedPacketsBeforeEnqueue(), ns3::QueueBase::GetTotalReceivedBytes(), ns3::QueueBase::GetTotalReceivedPackets(), ns3::LteSpectrumValueHelper::GetUplinkCarrierBand(), ns3::RawTextConfigSave::Global(), ns3::CommandLine::HandleNonOption(), ns3::Icmpv6L4Protocol::HandleNS(), ns3::UdpEchoServer::HandleRead(), ns3::Rip::HandleResponses(), ns3::RipNg::HandleResponses(), ns3::Icmpv6L4Protocol::HandleRS(), ns3::ArpCache::HandleWaitReplyTimeout(), ns3::IidManager::HasAttribute(), ns3::IidManager::HasTraceSource(), ns3::if(), ns3::TcpVegas::IncreaseWindow(), ns3::TcpVeno::IncreaseWindow(), ns3::TcpYeah::IncreaseWindow(), ns3::SixLowPanHelper::Install(), ns3::SpectrumAnalyzerHelper::Install(), ns3::BridgeHelper::Install(), ns3::TapBridgeHelper::Install(), ns3::DhcpHelper::InstallDhcpClientPriv(), ns3::DhcpHelper::InstallDhcpServer(), ns3::DhcpHelper::InstallFixedAddress(), ns3::LteHelper::InstallSingleEnbDevice(), WifiOfdmMaskSlopesTestCase::InterpolateAndAppendValues(), ns3::aodv::RoutingTable::InvalidateRoutesWithDst(), ns3::Ipv6L3Protocol::IpForward(), ns3::Ipv4L3Protocol::IpForward(), ns3::Ipv6L3Protocol::IpMulticastForward(), ns3::Ipv4L3Protocol::IpMulticastForward(), ns3::Ipv4AddressGeneratorImpl::IsAddressAllocated(), ns3::Ipv4L3Protocol::IsDestinationAddress(), ns3::NamesPriv::IsDuplicateName(), ns3::QueueBase::IsEmpty(), ns3::Ipv4L3Protocol::Fragments::IsEntire(), ns3::SixLowPanNetDevice::Fragments::IsEntire(), ns3::Ipv4L3Protocol::IsForwarding(), ns3::Ipv6L3Protocol::IsForwarding(), ns3::LteRlcAm::IsInsideReceivingWindow(), ns3::LteRlcUm::IsInsideReorderingWindow(), ns3::NamesPriv::IsNamed(), ns3::Ipv4L3Protocol::IsUnicast(), ns3::olsr::RoutingProtocol::LinkSensing(), ns3::Ipv4L3Protocol::LocalDeliver(), ns3::Ipv6L3Protocol::LocalDeliver(), ns3::dsdv::RoutingProtocol::LookForQueuedPackets(), ns3::Ipv4EndPointDemux::Lookup(), ns3::Rip::Lookup(), ns3::RipNg::Lookup(), ns3::NdiscCache::Lookup(), ns3::Ipv6EndPointDemux::Lookup(), ns3::ArpL3Protocol::Lookup(), ns3::Ipv4GlobalRouting::LookupGlobal(), ns3::NdiscCache::LookupInverse(), ns3::aodv::RoutingTableEntry::LookupPrecursor(), ns3::aodv::RoutingTable::LookupRoute(), ns3::dsr::DsrRouteCache::LookupRoute(), ns3::dsr::DsrRouteCache::LookupRoute_Link(), ns3::Ipv4StaticRouting::LookupStatic(), ns3::Ipv6StaticRouting::LookupStatic(), ns3::aodv::RoutingTable::LookupValidRoute(), ns3::BuildingsHelper::MakeConsistent(), ns3::MobilityBuildingInfo::MakeConsistent(), ns3::SystemPath::MakeDirectories(), ns3::LteMiErrorModel::MappingMiBler(), ns3::Time::Mark(), ns3::aodv::RoutingTable::MarkLinkAsUnidirectional(), ns3::dsr::DsrRreqTable::MarkLinkAsUnidirectional(), ns3::EpcTft::PacketFilter::Matches(), ns3::LteUeRrc::MeasurementReportTriggering(), ns3::SPFVertex::MergeParent(), ns3::LteMiErrorModel::Mib(), ns3::olsr::RoutingProtocol::MprComputation(), ns3::TcpSocketBase::NewAck(), ns3::WifiSpectrumValueHelper::NormalizeSpectrumMask(), ns3::aodv::RoutingProtocol::NotifyAddAddress(), ns3::aodv::RoutingProtocol::NotifyInterfaceDown(), ns3::dsdv::RoutingProtocol::NotifyInterfaceDown(), ns3::Rip::NotifyInterfaceUp(), ns3::RipNg::NotifyInterfaceUp(), ns3::dot11s::PeerManagementProtocol::NotifyLinkClose(), ns3::dot11s::PeerManagementProtocol::NotifyLinkOpen(), ns3::AlohaNoackNetDevice::NotifyReceptionEndOk(), ns3::aodv::RoutingProtocol::NotifyRemoveAddress(), ns3::AlohaNoackNetDevice::NotifyTransmissionEnd(), ns3::Ipv4AddressHelper::NumAddressBits(), ns3::CoDelQueueDisc::OkToDrop(), ns3::AthstatsWifiTraceSink::Open(), ns3::operator<<(), ns3::QueueDisc::PacketDequeued(), ns3::QueueDisc::PacketEnqueued(), ns3::dsr::DsrRouting::PacketNewRoute(), ns3::TcpSocketBase::PeerClose(), ns3::TcpSocketBase::PersistTimeout(), ns3::LrWpanCsmaCa::PlmeCcaConfirm(), ns3::LrWpanPhy::PlmeSetTRXStateRequest(), ns3::olsr::RoutingProtocol::PopulateTwoHopNeighborSet(), ns3::UeManager::PrepareHandover(), ns3::dsr::DsrLinkStab::Print(), ns3::RadioEnvironmentMapHelper::PrintAndReset(), ns3::dsr::DsrRouting::PriorityScheduler(), ns3::Ipv6ExtensionRouting::Process(), ns3::Ipv6ExtensionLooseRouting::Process(), ns3::dsr::DsrOptionRreq::Process(), ns3::dsr::DsrOptionRrep::Process(), ns3::dsr::DsrOptionSR::Process(), ns3::TcpSocketBase::ProcessAck(), ns3::GlobalRouteManagerImpl::ProcessASExternals(), ns3::GlobalRouter::ProcessBridgedBroadcastLink(), ns3::TcpSocketBase::ProcessClosing(), ns3::TcpSocketBase::ProcessEstablished(), ns3::SixLowPanNetDevice::ProcessFragment(), ns3::Ipv4L3Protocol::ProcessFragment(), ns3::TcpSocketBase::ProcessLastAck(), ns3::TcpSocketBase::ProcessListen(), ns3::olsr::RoutingProtocol::ProcessMid(), ns3::DefaultSimulatorImpl::ProcessOneEvent(), ns3::RealtimeSimulatorImpl::ProcessOneEvent(), ns3::DistributedSimulatorImpl::ProcessOneEvent(), ns3::NullMessageSimulatorImpl::ProcessOneEvent(), ns3::Ipv6Extension::ProcessOptions(), ns3::GlobalRouter::ProcessPointToPointLink(), ns3::GlobalRouter::ProcessSingleBroadcastLink(), ns3::TcpSocketBase::ProcessSynRcvd(), ns3::TcpSocketBase::ProcessSynSent(), ns3::TcpSocketBase::ProcessWait(), ns3::aodv::Neighbors::Purge(), ns3::aodv::RoutingTable::Purge(), ns3::dsr::DsrRouteCache::PurgeMac(), ns3::NscTcpSocketImpl::ReadPendingData(), ns3::LteRlcAm::ReassembleAndDeliver(), ns3::LteRlcUm::ReassembleAndDeliver(), ns3::LteRlcUm::ReassembleOutsideWindow(), ns3::LteRlcUm::ReassembleSnInterval(), ns3::dsr::DsrRouteCache::RebuildBestRouteTable(), ns3::ArpL3Protocol::Receive(), ns3::Ipv4L3Protocol::Receive(), ns3::Ipv6L3Protocol::Receive(), ns3::LteNetDevice::Receive(), ns3::CsmaNetDevice::Receive(), ns3::Rip::Receive(), ns3::RipNg::Receive(), ns3::OcbWifiMac::Receive(), ns3::StaWifiMac::Receive(), ns3::TcpSocketBase::ReceivedData(), ns3::LteEnbMac::ReceiveDlCqiLteControlMessage(), ns3::TapBridge::ReceiveFromBridgedDevice(), ns3::SixLowPanNetDevice::ReceiveFromDevice(), ns3::EpcEnbApplication::RecvFromLteSocket(), ns3::EpcPgwApplication::RecvFromTunDevice(), ns3::EpcX2::RecvFromX2cSocket(), ns3::EpcX2::RecvFromX2uSocket(), ns3::UeManager::RecvMeasurementReport(), ns3::olsr::RoutingProtocol::RecvOlsr(), ns3::aodv::RoutingProtocol::RecvReply(), ns3::aodv::RoutingProtocol::RecvRequest(), ns3::UeManager::RecvRrcConnectionReconfigurationCompleted(), ns3::PacketMetadata::Recycle(), ns3::DropTailQueue< Item >::Remove(), ns3::Ipv4L3Protocol::RemoveDuplicates(), ns3::CalendarScheduler::RemoveNext(), ns3::Ipv4GlobalRouting::RemoveRoute(), ns3::dsr::DsrRreqTable::RemoveRreqEntry(), ns3::NamesPriv::Rename(), ns3::CandidateQueue::Reorder(), ns3::QueueDisc::Requeue(), ns3::QueueDisc::Restart(), ns3::dot11s::PeerLink::RetryTimeout(), ns3::TcpSocketBase::ReTxTimeout(), ns3::LteUePhy::RlfDetection(), ns3::aodv::RoutingProtocol::RouteInput(), ns3::dsdv::RoutingProtocol::RouteInput(), ns3::Ipv4GlobalRouting::RouteInput(), ns3::Ipv4ListRouting::RouteInput(), ns3::Ipv4StaticRouting::RouteInput(), ns3::Rip::RouteInput(), ns3::olsr::RoutingProtocol::RouteInput(), ns3::Ipv6ListRouting::RouteInput(), ns3::Ipv6StaticRouting::RouteInput(), ns3::RipNg::RouteInput(), ns3::Ipv4L3Protocol::RouteInputError(), ns3::Ipv6L3Protocol::RouteInputError(), ns3::aodv::RoutingProtocol::RouteOutput(), ns3::dsdv::RoutingProtocol::RouteOutput(), ns3::Ipv4GlobalRouting::RouteOutput(), ns3::Ipv4ListRouting::RouteOutput(), ns3::Ipv4StaticRouting::RouteOutput(), ns3::Rip::RouteOutput(), ns3::Ipv6ListRouting::RouteOutput(), ns3::Ipv6StaticRouting::RouteOutput(), ns3::RipNg::RouteOutput(), ns3::aodv::RoutingProtocol::RouteRequestTimerExpire(), ns3::dsr::DsrRouting::RouteRequestTimerExpire(), ns3::olsr::RoutingProtocol::RoutingTableComputation(), ns3::RadioEnvironmentMapHelper::RunOneIteration(), ns3::OnOffApplication::ScheduleNextTx(), ns3::aodv::RoutingProtocol::ScheduleRreqRetry(), ns3::dsr::DsrRouting::ScheduleRreqRetry(), ns3::OnOffApplication::ScheduleStartEvent(), ns3::OnOffApplication::ScheduleStopEvent(), ns3::Ipv4Interface::Send(), ns3::Ipv6Interface::Send(), ns3::TcpSocketBase::Send(), ns3::PointToPointNetDevice::Send(), ns3::dsr::DsrRouting::Send(), ns3::Ipv4L3Protocol::Send(), ns3::Ipv6L3Protocol::Send(), ns3::Radvd::Send(), ns3::dsr::DsrRouting::SendAck(), ns3::ArpL3Protocol::SendArpReply(), ns3::ArpL3Protocol::SendArpRequest(), ns3::LteEnbPhy::SendControlChannels(), ns3::BulkSendApplication::SendData(), ns3::LteTestRrc::SendData(), ns3::LteTestPdcp::SendData(), ns3::UeManager::SendData(), ns3::LteEnbPhy::SendDataChannels(), ns3::TcpSocketBase::SendDataPacket(), TcpDctcpCongestedRouter::SendDataPacket(), ns3::TcpSocketCongestedRouter::SendDataPacket(), ns3::TcpSocketBase::SendEmptyPacket(), ns3::TcpSocketSmallAcks::SendEmptyPacket(), ns3::Icmpv6L4Protocol::SendErrorDestinationUnreachable(), ns3::Icmpv6L4Protocol::SendErrorParameterError(), ns3::dsr::DsrRouting::SendErrorRequest(), ns3::Icmpv6L4Protocol::SendErrorTimeExceeded(), ns3::Icmpv6L4Protocol::SendErrorTooBig(), ns3::CsmaNetDevice::SendFrom(), ns3::FdNetDevice::SendFrom(), ns3::AlohaNoackNetDevice::SendFrom(), ns3::dsr::DsrRouting::SendGratuitousReply(), ns3::LteEnbRrc::SendHandoverRequest(), ns3::Icmpv4L4Protocol::SendMessage(), ns3::Icmpv6L4Protocol::SendMessage(), ns3::Icmpv6L4Protocol::SendNA(), ns3::Icmpv6L4Protocol::SendNS(), ns3::DhcpServer::SendOffer(), ns3::dsr::DsrRouting::SendPacketFromBuffer(), ns3::TcpL4Protocol::SendPacketV4(), ns3::TcpL4Protocol::SendPacketV6(), ns3::TcpSocketBase::SendPendingData(), ns3::NscTcpSocketImpl::SendPendingData(), ns3::Ipv4L3Protocol::SendRealOut(), ns3::Ipv6L3Protocol::SendRealOut(), ns3::Icmpv6L4Protocol::SendRedirection(), ns3::aodv::RoutingProtocol::SendReplyByIntermediateNode(), ns3::dsr::DsrRouting::SendRequest(), ns3::aodv::RoutingProtocol::SendRerrMessage(), ns3::aodv::RoutingProtocol::SendRerrWhenBreaksLinkToNextHop(), ns3::aodv::RoutingProtocol::SendRerrWhenNoRouteToForward(), ns3::Icmpv6L4Protocol::SendRS(), ns3::Ipv4RawSocketImpl::SendTo(), ns3::Ipv6RawSocketImpl::SendTo(), ns3::PacketSocket::SendTo(), ns3::EpcPgwApplication::SendToTunDevice(), ns3::Rip::SendTriggeredRouteUpdate(), ns3::RipNg::SendTriggeredRouteUpdate(), ns3::dsdv::RoutingProtocol::SendTriggeredUpdate(), ns3::dsr::DsrRouting::SendUnreachError(), ns3::dsr::DsrOptionField::Serialize(), ns3::Ipv4Header::Serialize(), ns3::OptionField::Serialize(), ns3::LteRlcAmHeader::Serialize(), ns3::PacketMetadata::Serialize(), ns3::ThreeGppHttpServer::ServeFromTxBuffer(), ns3::RadiotapHeader::SetAmpduStatus(), ns3::RadiotapHeader::SetAntennaNoisePower(), ns3::RadiotapHeader::SetAntennaSignalPower(), ns3::Ipv4AddressHelper::SetBase(), ns3::CosineAntennaModel::SetBeamwidth(), ns3::RadiotapHeader::SetChannelFrequencyAndFlags(), ns3::CsmaNetDevice::SetEncapsulationMode(), ns3::FdNetDevice::SetEncapsulationMode(), ns3::aodv::RoutingTable::SetEntryState(), ns3::EmuFdNetDeviceHelper::SetFileDescriptor(), ns3::PlanetLabFdNetDeviceHelper::SetFileDescriptor(), ns3::TapFdNetDeviceHelper::SetFileDescriptor(), ns3::RadiotapHeader::SetFrameFlags(), ns3::RadiotapHeader::SetHeFields(), ns3::RadiotapHeader::SetMcsFields(), ns3::CsmaNetDevice::SetMtu(), ns3::Ipv6PmtuCache::SetPmtuValidityTime(), ns3::LteHexGridEnbTopologyHelper::SetPositionAndInstallEnbDevice(), ns3::RadiotapHeader::SetRate(), ns3::RadiotapHeader::SetTsft(), ns3::Ipv4L3Protocol::SetUp(), ns3::Ipv6L3Protocol::SetUp(), ns3::TcpSocketBase::SetupEndpoint(), ns3::TcpSocketBase::SetupEndpoint6(), ns3::RadiotapHeader::SetVhtFields(), ns3::PyViz::SimulatorRunUntil(), ns3::GlobalRouteManagerImpl::SPFAddASExternal(), ns3::GlobalRouteManagerImpl::SPFCalculate(), ns3::GlobalRouteManagerImpl::SPFGetNextLink(), ns3::GlobalRouteManagerImpl::SPFIntraAddRouter(), ns3::GlobalRouteManagerImpl::SPFIntraAddStub(), ns3::GlobalRouteManagerImpl::SPFIntraAddTransit(), ns3::GlobalRouteManagerImpl::SPFNext(), ns3::GlobalRouteManagerImpl::SPFNexthopCalculation(), ns3::GlobalRouteManagerImpl::SPFProcessStubs(), ns3::dsr::DsrRouting::Start(), ns3::SpectrumAnalyzer::Start(), ns3::TvSpectrumTransmitter::Start(), ns3::WaveformGenerator::Start(), ns3::FdReader::Start(), ns3::DhcpServer::StartApplication(), ns3::V4TraceRoute::StartApplication(), StartFlow(), ns3::ShannonSpectrumErrorModel::StartRx(), ns3::LteInterference::StartRx(), ns3::LteSpectrumPhy::StartRx(), ns3::HalfDuplexIdealPhy::StartRx(), ns3::LteSpectrumPhy::StartRxData(), ns3::LteSpectrumPhy::StartRxDlCtrl(), ns3::LteSpectrumPhy::StartRxUlSrs(), ns3::TapBridge::StartTapDevice(), ns3::HalfDuplexIdealPhy::StartTx(), ns3::MultiModelSpectrumChannel::StartTx(), ns3::SingleModelSpectrumChannel::StartTx(), ns3::LteSpectrumPhy::StartTxDataFrame(), ns3::LteSpectrumPhy::StartTxDlCtrlFrame(), ns3::LteSpectrumPhy::StartTxUlSrsFrame(), ns3::V4TraceRoute::StartWaitReplyTimer(), ns3::ArpCache::StartWaitReplyTimer(), ns3::Simulator::Stop(), ns3::LteUePhy::SubframeIndication(), ns3::LteUeRrc::SynchronizeToStrongestCell(), ns3::CsmaNetDevice::TransmitAbort(), ns3::PointToPointNetDevice::TransmitComplete(), ns3::CsmaNetDevice::TransmitCompleteEvent(), ns3::CsmaChannel::TransmitEnd(), ns3::CsmaNetDevice::TransmitStart(), ns3::PointToPointChannel::TransmitStart(), ns3::PointToPointRemoteChannel::TransmitStart(), ns3::CsmaChannel::TransmitStart(), ns3::PointToPointNetDevice::TransmitStart(), ns3::aodv::Neighbors::Update(), ns3::aodv::RoutingTable::Update(), ns3::LteEnbNetDevice::UpdateConfig(), ns3::LteUeNetDevice::UpdateConfig(), ns3::dsr::DsrRouteCache::UpdateNeighbor(), ns3::dsr::DsrRouteCache::UpdateRouteEntry(), ns3::TcpSocketBase::UpdateWindowSize(), ns3::dsr::DsrRouteCache::UseExtends(), and ns3::LteUeRrc::VarMeasReportListClear().
Variable Documentation
return
return
Definition at line 1796 of file global-router-interface.cc.
Referenced by ns3::LteRlcAm::DoReceivePdu(), grid.TimelineDataRange::get_bounds(), grid.TimelineEvent::get_bounds(), grid.Timeline::get_bounds(), grid.Timelines::get_bounds(), grid.GraphicRenderer::get_data_rectangle(), grid.TimelineEvent::get_events_bounds(), grid.GraphicRenderer::get_range(), grid.TimelineDataRange::get_ranges_bounds(), and grid.GraphicRenderer::get_selection_rectangle().