ns-3: TimerImpl Implementation
TimerImpl Implementation
Core » Virtual Time Timer and Watchdog
Files
file timer-impl.h
Classes
struct ns3::TimerImplFive< T1, T2, T3, T4, T5 >
TimerImpl specialization class for varying numbers of arguments.
struct ns3::TimerImplFour< T1, T2, T3, T4 >
TimerImpl specialization class for varying numbers of arguments.
struct ns3::TimerImplMemberTraits< T >
Helper for the MakeTimerImpl functions which take a class method.
struct ns3::TimerImplMemberTraits< T * >
Helper for the MakeTimerImpl functions which take a class method.
struct ns3::TimerImplOne< T1 >
TimerImpl specialization class for varying numbers of arguments.
struct ns3::TimerImplSix< T1, T2, T3, T4, T5, T6 >
TimerImpl specialization class for varying numbers of arguments.
struct ns3::TimerImplThree< T1, T2, T3 >
TimerImpl specialization class for varying numbers of arguments.
struct ns3::TimerImplTwo< T1, T2 >
TimerImpl specialization class for varying numbers of arguments.
struct ns3::TimerTraits< T >
Type and reference traits for TimerImpl arguments.
Functions
template<typename FN >
TimerImpl * ns3::MakeTimerImpl (FN fn)
Make a TimerImpl from a function pointer taking varying numbers of arguments.
template<typename FN >
TimerImpl * ns3::MakeTimerImpl (IntToType< 0 >, FN fn)
Make a TimerImpl from a function pointer taking zero arguments.
template<typename MEM_PTR , typename OBJ_PTR >
TimerImpl * ns3::MakeTimerImpl (IntToType< 0 >, MEM_PTR memPtr, OBJ_PTR objPtr)
Make a TimerImpl from a function pointer taking zero arguments.
template<typename FN >
TimerImpl * ns3::MakeTimerImpl (IntToType< 1 >, FN fn)
Make a TimerImpl from a function pointer taking one argument.
template<typename MEM_PTR , typename OBJ_PTR >
TimerImpl * ns3::MakeTimerImpl (IntToType< 1 >, MEM_PTR memPtr, OBJ_PTR objPtr)
Make a TimerImpl from a function pointer taking one argument.
template<typename FN >
TimerImpl * ns3::MakeTimerImpl (IntToType< 2 >, FN fn)
Make a TimerImpl from a function pointer taking two arguments.
template<typename MEM_PTR , typename OBJ_PTR >
TimerImpl * ns3::MakeTimerImpl (IntToType< 2 >, MEM_PTR memPtr, OBJ_PTR objPtr)
Make a TimerImpl from a function pointer taking two arguments.
template<typename FN >
TimerImpl * ns3::MakeTimerImpl (IntToType< 3 >, FN fn)
Make a TimerImpl from a function pointer taking three arguments.
template<typename MEM_PTR , typename OBJ_PTR >
TimerImpl * ns3::MakeTimerImpl (IntToType< 3 >, MEM_PTR memPtr, OBJ_PTR objPtr)
Make a TimerImpl from a function pointer taking three arguments.
template<typename FN >
TimerImpl * ns3::MakeTimerImpl (IntToType< 4 >, FN fn)
Make a TimerImpl from a function pointer taking four arguments.
template<typename MEM_PTR , typename OBJ_PTR >
TimerImpl * ns3::MakeTimerImpl (IntToType< 4 >, MEM_PTR memPtr, OBJ_PTR objPtr)
Make a TimerImpl from a function pointer taking four arguments.
template<typename FN >
TimerImpl * ns3::MakeTimerImpl (IntToType< 5 >, FN fn)
Make a TimerImpl from a function pointer taking five arguments.
template<typename MEM_PTR , typename OBJ_PTR >
TimerImpl * ns3::MakeTimerImpl (IntToType< 5 >, MEM_PTR memPtr, OBJ_PTR objPtr)
Make a TimerImpl from a function pointer taking five arguments.
template<typename FN >
TimerImpl * ns3::MakeTimerImpl (IntToType< 6 >, FN fn)
Make a TimerImpl from a function pointer taking six arguments.
template<typename MEM_PTR , typename OBJ_PTR >
TimerImpl * ns3::MakeTimerImpl (IntToType< 6 >, MEM_PTR memPtr, OBJ_PTR objPtr)
Make a TimerImpl from a function pointer taking six arguments.
template<typename MEM_PTR , typename OBJ_PTR >
TimerImpl * ns3::MakeTimerImpl (MEM_PTR memPtr, OBJ_PTR objPtr)
Make a TimerImpl from a class method pointer taking a varying number of arguments.
Detailed Description
Function Documentation
MakeTimerImpl() [1/16]
template<typename FN > TimerImpl* ns3::MakeTimerImpl (FN fn)
Make a TimerImpl from a function pointer taking varying numbers of arguments.
Template Parameters
FN [deduced] Function signature type of the callback function.
Parameters
[in] fn The function pointer to invoke when the timer expires.
Returns
The TimerImpl.
Definition at line 254 of file timer-impl.h.
MakeTimerImpl() [2/16]
template<typename FN > TimerImpl* ns3::MakeTimerImpl (IntToType< 0 > , FN fn)
Make a TimerImpl from a function pointer taking zero arguments.
Template Parameters
FN [deduced] Function signature type of the callback function.
Parameters
[in] fn The function pointer to invoke when the timer expires.
Returns
The TimerImpl.
Definition at line 266 of file timer-impl.h.
References ns3::Simulator::Schedule().
MakeTimerImpl() [3/16]
template<typename MEM_PTR , typename OBJ_PTR > TimerImpl* ns3::MakeTimerImpl (IntToType< 0 > , MEM_PTR memPtr, OBJ_PTR objPtr)
Make a TimerImpl from a function pointer taking zero arguments.
Template Parameters
MEM_PTR [deduced] Class method function signature type.
OBJ_PTR [deduced] Class type.
Parameters
[in] memPtr Class method to invoke when the timer expires.
[in] objPtr Object instance pointer.
Returns
The TimerImpl.
Definition at line 633 of file timer-impl.h.
References ns3::Simulator::Schedule().
MakeTimerImpl() [4/16]
template<typename FN > TimerImpl* ns3::MakeTimerImpl (IntToType< 1 > , FN fn)
Make a TimerImpl from a function pointer taking one argument.
Template Parameters
FN [deduced] Function signature type of the callback function.
Parameters
[in] fn The function pointer to invoke when the timer expires.
Returns
The TimerImpl.
Definition at line 292 of file timer-impl.h.
References ns3::Simulator::Schedule().
MakeTimerImpl() [5/16]
template<typename MEM_PTR , typename OBJ_PTR > TimerImpl* ns3::MakeTimerImpl (IntToType< 1 > , MEM_PTR memPtr, OBJ_PTR objPtr)
Make a TimerImpl from a function pointer taking one argument.
Template Parameters
MEM_PTR [deduced] Class method function signature type.
OBJ_PTR [deduced] Class type.
Parameters
[in] memPtr Class method to invoke when the timer expires.
[in] objPtr Object instance pointer.
Returns
The TimerImpl.
Definition at line 661 of file timer-impl.h.
References ns3::Simulator::Schedule().
MakeTimerImpl() [6/16]
template<typename FN > TimerImpl* ns3::MakeTimerImpl (IntToType< 2 > , FN fn)
Make a TimerImpl from a function pointer taking two arguments.
Template Parameters
FN [deduced] Function signature type of the callback function.
Parameters
[in] fn The function pointer to invoke when the timer expires.
Returns
The TimerImpl.
Definition at line 327 of file timer-impl.h.
References ns3::Simulator::Schedule().
MakeTimerImpl() [7/16]
template<typename MEM_PTR , typename OBJ_PTR > TimerImpl* ns3::MakeTimerImpl (IntToType< 2 > , MEM_PTR memPtr, OBJ_PTR objPtr)
Make a TimerImpl from a function pointer taking two arguments.
Template Parameters
MEM_PTR [deduced] Class method function signature type.
OBJ_PTR [deduced] Class type.
Parameters
[in] memPtr Class method to invoke when the timer expires.
[in] objPtr Object instance pointer.
Returns
The TimerImpl.
Definition at line 698 of file timer-impl.h.
References ns3::Simulator::Schedule().
MakeTimerImpl() [8/16]
template<typename FN > TimerImpl* ns3::MakeTimerImpl (IntToType< 3 > , FN fn)
Make a TimerImpl from a function pointer taking three arguments.
Template Parameters
FN [deduced] Function signature type of the callback function.
Parameters
[in] fn The function pointer to invoke when the timer expires.
Returns
The TimerImpl.
Definition at line 367 of file timer-impl.h.
References ns3::Simulator::Schedule().
MakeTimerImpl() [9/16]
template<typename MEM_PTR , typename OBJ_PTR > TimerImpl* ns3::MakeTimerImpl (IntToType< 3 > , MEM_PTR memPtr, OBJ_PTR objPtr)
Make a TimerImpl from a function pointer taking three arguments.
Template Parameters
MEM_PTR [deduced] Class method function signature type.
OBJ_PTR [deduced] Class type.
Parameters
[in] memPtr Class method to invoke when the timer expires.
[in] objPtr Object instance pointer.
Returns
The TimerImpl.
Definition at line 740 of file timer-impl.h.
References ns3::Simulator::Schedule().
MakeTimerImpl() [10/16]
template<typename FN > TimerImpl* ns3::MakeTimerImpl (IntToType< 4 > , FN fn)
Make a TimerImpl from a function pointer taking four arguments.
Template Parameters
FN [deduced] Function signature type of the callback function.
Parameters
[in] fn The function pointer to invoke when the timer expires.
Returns
The TimerImpl.
Definition at line 412 of file timer-impl.h.
References ns3::Simulator::Schedule().
MakeTimerImpl() [11/16]
template<typename MEM_PTR , typename OBJ_PTR > TimerImpl* ns3::MakeTimerImpl (IntToType< 4 > , MEM_PTR memPtr, OBJ_PTR objPtr)
Make a TimerImpl from a function pointer taking four arguments.
Template Parameters
MEM_PTR [deduced] Class method function signature type.
OBJ_PTR [deduced] Class type.
Parameters
[in] memPtr Class method to invoke when the timer expires.
[in] objPtr Object instance pointer.
Returns
The TimerImpl.
Definition at line 787 of file timer-impl.h.
References ns3::Simulator::Schedule().
MakeTimerImpl() [12/16]
template<typename FN > TimerImpl* ns3::MakeTimerImpl (IntToType< 5 > , FN fn)
Make a TimerImpl from a function pointer taking five arguments.
Template Parameters
FN [deduced] Function signature type of the callback function.
Parameters
[in] fn The function pointer to invoke when the timer expires.
Returns
The TimerImpl.
Definition at line 462 of file timer-impl.h.
References ns3::Simulator::Schedule().
MakeTimerImpl() [13/16]
template<typename MEM_PTR , typename OBJ_PTR > TimerImpl* ns3::MakeTimerImpl (IntToType< 5 > , MEM_PTR memPtr, OBJ_PTR objPtr)
Make a TimerImpl from a function pointer taking five arguments.
Template Parameters
MEM_PTR [deduced] Class method function signature type.
OBJ_PTR [deduced] Class type.
Parameters
[in] memPtr Class method to invoke when the timer expires.
[in] objPtr Object instance pointer.
Returns
The TimerImpl.
Definition at line 839 of file timer-impl.h.
References ns3::Simulator::Schedule().
MakeTimerImpl() [14/16]
template<typename FN > TimerImpl* ns3::MakeTimerImpl (IntToType< 6 > , FN fn)
Make a TimerImpl from a function pointer taking six arguments.
Template Parameters
FN [deduced] Function signature type of the callback function.
Parameters
[in] fn The function pointer to invoke when the timer expires.
Returns
The TimerImpl.
Definition at line 517 of file timer-impl.h.
References ns3::Simulator::Schedule().
MakeTimerImpl() [15/16]
template<typename MEM_PTR , typename OBJ_PTR > TimerImpl* ns3::MakeTimerImpl (IntToType< 6 > , MEM_PTR memPtr, OBJ_PTR objPtr)
Make a TimerImpl from a function pointer taking six arguments.
Template Parameters
MEM_PTR [deduced] Class method function signature type.
OBJ_PTR [deduced] Class type.
Parameters
[in] memPtr Class method to invoke when the timer expires.
[in] objPtr Object instance pointer.
Returns
The TimerImpl.
Definition at line 896 of file timer-impl.h.
References ns3::Simulator::Schedule().
MakeTimerImpl() [16/16]
template<typename MEM_PTR , typename OBJ_PTR > TimerImpl* ns3::MakeTimerImpl (MEM_PTR memPtr, OBJ_PTR objPtr)
Make a TimerImpl from a class method pointer taking a varying number of arguments.
Template Parameters
MEM_PTR [deduced] Class method function signature type.
OBJ_PTR [deduced] Class type.
Parameters
[in] memPtr Class method to invoke when the timer expires.
[in] objPtr Object instance pointer.
Returns
The TimerImpl.
Definition at line 621 of file timer-impl.h.