ns-3: Attribute Implementation
Attribute Implementation
Core » Attributes » Attribute Helper
These are the internal implementation functions for the Attribute system.
Files
file attribute-accessor-helper.h
file type-name.cc
file type-name.h
Classes
class ns3::AccessorHelper< T, U >
struct ns3::AccessorTrait< T >
Functions
template<typename V , typename T , typename U >
Ptr< const AttributeAccessor > ns3::DoMakeAccessorHelperOne (U T::*memberVariable)
template<typename V , typename T , typename U >
Ptr< const AttributeAccessor > ns3::DoMakeAccessorHelperOne (U(T::*getter)(void) const)
template<typename V , typename T , typename U >
Ptr< const AttributeAccessor > ns3::DoMakeAccessorHelperOne (void(T::*setter)(U))
template<typename W , typename T , typename U , typename V >
Ptr< const AttributeAccessor > ns3::DoMakeAccessorHelperTwo (bool(T::*setter)(U), V(T::*getter)(void) const)
template<typename W , typename T , typename U , typename V >
Ptr< const AttributeAccessor > ns3::DoMakeAccessorHelperTwo (V(T::*getter)(void) const, bool(T::*setter)(U))
template<typename W , typename T , typename U , typename V >
Ptr< const AttributeAccessor > ns3::DoMakeAccessorHelperTwo (V(T::*getter)(void) const, void(T::*setter)(U))
template<typename W , typename T , typename U , typename V >
Ptr< const AttributeAccessor > ns3::DoMakeAccessorHelperTwo (void(T::*setter)(U), V(T::*getter)(void) const)
template<typename V , typename T1 >
Ptr< const AttributeAccessor > ns3::MakeAccessorHelper (T1 a1)
template<typename V , typename T1 , typename T2 >
Ptr< const AttributeAccessor > ns3::MakeAccessorHelper (T1 a1, T2 a2)
template<typename T , typename BASE >
Ptr< AttributeChecker > ns3::MakeSimpleAttributeChecker (std::string name, std::string underlying)
template<typename T >
std::string ns3::TypeNameGet (void)
template<>
std::string ns3::TypeNameGet< int8_t > (void)
template<>
std::string ns3::TypeNameGet< int16_t > (void)
template<>
std::string ns3::TypeNameGet< int32_t > (void)
template<>
std::string ns3::TypeNameGet< int64_t > (void)
template<>
std::string ns3::TypeNameGet< uint8_t > (void)
template<>
std::string ns3::TypeNameGet< uint16_t > (void)
template<>
std::string ns3::TypeNameGet< uint32_t > (void)
template<>
std::string ns3::TypeNameGet< uint64_t > (void)
template<>
std::string ns3::TypeNameGet< float > (void)
template<>
std::string ns3::TypeNameGet< double > (void)
Detailed Description
These are the internal implementation functions for the Attribute system.
Module code shouldn't need to call these directly. Instead, see Attribute Helper.
There are three versions of DoMakeAccessorHelperOne:
With a member variable: DoMakeAccessorHelperOne(U T::*)
With a class get functor: DoMakeAccessorHelperOne(U(T::*)(void) const)
With a class set method: DoMakeAccessorHelperOne(void(T::*)(U))
There are two pairs of DoMakeAccessorHelperTwo (four total):
Taking two arguments, a set method and get functor, in either order,
With set methods returning void or bool.
Function Documentation
DoMakeAccessorHelperOne() [1/3]
template<typename V , typename T , typename U > Ptr<const AttributeAccessor> ns3::DoMakeAccessorHelperOne (U T::* memberVariable) inline
MakeAccessorHelper implementation for a class data member.
Template Parameters
V [explicit] The specific AttributeValue type to use to represent the Attribute.
T [deduced] The class holding the data member.
U [deduced] The type of the data member.
Parameters
[in] memberVariable The address of the data member.
Returns
The AttributeAccessor.
Definition at line 261 of file attribute-accessor-helper.h.
DoMakeAccessorHelperOne() [2/3]
template<typename V , typename T , typename U > Ptr<const AttributeAccessor> ns3::DoMakeAccessorHelperOne (U(T::*)(void) const getter) inline
MakeAccessorHelper implementation for a class get functor method.
Template Parameters
V [explicit] The specific AttributeValue type to use to represent the Attribute.
T [deduced] The class holding the get functor method.
U [deduced] The return type of the get functor method.
Parameters
[in] getter The address of the class get functor method.
Returns
The AttributeAccessor.
Definition at line 323 of file attribute-accessor-helper.h.
References NS_UNUSED.
DoMakeAccessorHelperOne() [3/3]
template<typename V , typename T , typename U > Ptr<const AttributeAccessor> ns3::DoMakeAccessorHelperOne (void(T::*)(U) setter) inline
MakeAccessorHelper implementation for a class set method returning void.
Template Parameters
V [explicit] The specific AttributeValue type to use to represent the Attribute.
T [deduced] The class holding the set method.
U [deduced] The argument type of the set method.
Parameters
[in] setter The address of the class set method, returning void.
Returns
The AttributeAccessor.
Definition at line 380 of file attribute-accessor-helper.h.
References NS_UNUSED.
DoMakeAccessorHelperTwo() [1/4]
template<typename W , typename T , typename U , typename V > Ptr<const AttributeAccessor> ns3::DoMakeAccessorHelperTwo (bool(T::*)(U) setter, V(T::*)(void) const getter) inline
MakeAccessorHelper implementation with a class get functor method and a class set method returning bool.
The two versions of this function differ only in argument order.
Template Parameters
W [explicit] The specific AttributeValue type to use to represent the Attribute.
T [deduced] The class holding the functor methods.
U [deduced] The argument type of the set method.
V [deduced] The return type of the get functor method.
Parameters
[in] setter The address of the class set method, returning bool.
[in] getter The address of the class get functor method.
Returns
The AttributeAccessor.
Definition at line 535 of file attribute-accessor-helper.h.
References ns3::AccessorHelper< T, U >::Set().
DoMakeAccessorHelperTwo() [2/4]
template<typename W , typename T , typename U , typename V > Ptr<const AttributeAccessor> ns3::DoMakeAccessorHelperTwo (V(T::*)(void) const getter, bool(T::*)(U) setter) inline
MakeAccessorHelper implementation with a class get functor method and a class set method returning bool.
The two versions of this function differ only in argument order.
Template Parameters
W [explicit] The specific AttributeValue type to use to represent the Attribute.
T [deduced] The class holding the functor methods.
U [deduced] The argument type of the set method.
V [deduced] The return type of the get functor method.
Parameters
[in] setter The address of the class set method, returning bool.
[in] getter The address of the class get functor method.
Returns
The AttributeAccessor.
Definition at line 596 of file attribute-accessor-helper.h.
DoMakeAccessorHelperTwo() [3/4]
template<typename W , typename T , typename U , typename V > Ptr<const AttributeAccessor> ns3::DoMakeAccessorHelperTwo (V(T::*)(void) const getter, void(T::*)(U) setter) inline
MakeAccessorHelper implementation with a class get functor method and a class set method returning void.
The two versions of this function differ only in argument order.
Template Parameters
W [explicit] The specific AttributeValue type to use to represent the Attribute.
T [deduced] The class holding the functor methods.
U [deduced] The argument type of the set method.
V [deduced] The return type of the get functor method.
Parameters
[in] setter The address of the class set method, returning void.
[in] getter The address of the class get functor method.
Returns
The AttributeAccessor.
Definition at line 508 of file attribute-accessor-helper.h.
DoMakeAccessorHelperTwo() [4/4]
template<typename W , typename T , typename U , typename V > Ptr<const AttributeAccessor> ns3::DoMakeAccessorHelperTwo (void(T::*)(U) setter, V(T::*)(void) const getter) inline
MakeAccessorHelper implementation with a class get functor method and a class set method returning void.
The two versions of this function differ only in argument order.
Template Parameters
W [explicit] The specific AttributeValue type to use to represent the Attribute.
T [deduced] The class holding the functor methods.
U [deduced] The argument type of the set method.
V [deduced] The return type of the get functor method.
Parameters
[in] setter The address of the class set method, returning void.
[in] getter The address of the class get functor method.
Returns
The AttributeAccessor.
Definition at line 447 of file attribute-accessor-helper.h.
References ns3::AccessorHelper< T, U >::Set().
MakeAccessorHelper() [1/2]
template<typename V , typename T1 > Ptr< const AttributeAccessor > ns3::MakeAccessorHelper (T1 a1) inline
Create an AttributeAccessor for a class data member, or a lone class get functor or set method.
The get functor method should have a signature like
typedef U (T::*getter)(void) const
where T is the class and U is the type of the return value.
The set method should have one of these signatures:
typedef void (T::*setter)(U)
typedef bool (T::*setter)(U)
where T is the class and U is the type of the value to set the attribute to, which should be compatible with the specific AttributeValue type V which holds the value (or the type implied by the name Make<V>Accessor of this function.) In the case of a setter returning bool, the return value should be true if the value could be set successfully.
Template Parameters
V [explicit] (If present) The specific AttributeValue type to use to represent the Attribute. (If not present, the type V is implicit in the name of this function, as "Make<V>Accessor"
T1 [deduced] The type of the class data member, or the type of the class get functor or set method.
Parameters
[in] a1 The address of the data member, or the get or set method.
Returns
The AttributeAccessor
Definition at line 606 of file attribute-accessor-helper.h.
MakeAccessorHelper() [2/2]
template<typename V , typename T1 , typename T2 > Ptr< const AttributeAccessor > ns3::MakeAccessorHelper (T1 a1, T2 a2) inline
Create an AttributeAccessor using a pair of get functor and set methods from a class.
The get functor method should have a signature like
typedef U (T::*getter)(void) const
where T is the class and U is the type of the return value.
The set method should have one of these signatures:
typedef void (T::*setter)(U)
typedef bool (T::*setter)(U)
where T is the class and U is the type of the value to set the attribute to, which should be compatible with the specific AttributeValue type V which holds the value (or the type implied by the name Make<V>Accessor of this function.) In the case of a setter returning bool, the return value should be true if the value could be set successfully.
In practice the setter and getter arguments can appear in either order, but setter first is preferred.
Template Parameters
V [explicit] (If present) The specific AttributeValue type to use to represent the Attribute. (If not present, the type V is implicit in the name of this function as "Make<V>Accessor"
T1 [deduced] The type of the class data member, or the type of the class get functor or set method.
T2 [deduced] The type of the getter class functor method.
Parameters
[in] a2 The address of the class method to set the attribute.
[in] a1 The address of the data member, or the get or set method.
Returns
The AttributeAccessor
Definition at line 614 of file attribute-accessor-helper.h.
MakeSimpleAttributeChecker()
template<typename T , typename BASE > Ptr<AttributeChecker> ns3::MakeSimpleAttributeChecker (std::string name, std::string underlying)
A simple string-based attribute checker
Template Parameters
T [explicit] The specific AttributeValue type used to represent the Attribute.
BASE [explicit] The AttributeChecker type corresponding to T.
Parameters
[in] name The name of the AttributeValue type, essentially the string form of T.
[in] underlying Underlying type name.
Returns
Ptr to AttributeChecker.
String-based AttributeChecker implementation.
Definition at line 98 of file attribute-helper.h.
References ns3::Copy(), and ns3::Create().
TypeNameGet()
template<typename T > std::string ns3::TypeNameGet (void)
Type name strings for numeric AttributeValue types.
Template Parameters
T [explicit] The numeric type.
Returns
The numeric type name as a string.
Definition at line 42 of file type-name.h.
TypeNameGet< double >()
template<> std::string ns3::TypeNameGet< double > (void)
ns3::TypeNameGet(void) specializaton.
Returns
The numeric type name as a string.
Definition at line 40 of file type-name.cc.
TypeNameGet< float >()
template<> std::string ns3::TypeNameGet< float > (void)
ns3::TypeNameGet(void) specializaton.
Returns
The numeric type name as a string.
Definition at line 39 of file type-name.cc.
TypeNameGet< int16_t >()
template<> std::string ns3::TypeNameGet< int16_t > (void)
ns3::TypeNameGet(void) specializaton.
Returns
The numeric type name as a string.
Definition at line 32 of file type-name.cc.
TypeNameGet< int32_t >()
template<> std::string ns3::TypeNameGet< int32_t > (void)
ns3::TypeNameGet(void) specializaton.
Returns
The numeric type name as a string.
Definition at line 33 of file type-name.cc.
TypeNameGet< int64_t >()
template<> std::string ns3::TypeNameGet< int64_t > (void)
ns3::TypeNameGet(void) specializaton.
Returns
The numeric type name as a string.
Definition at line 34 of file type-name.cc.
TypeNameGet< int8_t >()
template<> std::string ns3::TypeNameGet< int8_t > (void)
ns3::TypeNameGet(void) specializaton.
Returns
The numeric type name as a string.
Definition at line 31 of file type-name.cc.
TypeNameGet< uint16_t >()
template<> std::string ns3::TypeNameGet< uint16_t > (void)
ns3::TypeNameGet(void) specializaton.
Returns
The numeric type name as a string.
Definition at line 36 of file type-name.cc.
TypeNameGet< uint32_t >()
template<> std::string ns3::TypeNameGet< uint32_t > (void)
ns3::TypeNameGet(void) specializaton.
Returns
The numeric type name as a string.
Definition at line 37 of file type-name.cc.
TypeNameGet< uint64_t >()
template<> std::string ns3::TypeNameGet< uint64_t > (void)
ns3::TypeNameGet(void) specializaton.
Returns
The numeric type name as a string.
Definition at line 38 of file type-name.cc.
TypeNameGet< uint8_t >()
template<> std::string ns3::TypeNameGet< uint8_t > (void)
ns3::TypeNameGet(void) specializaton.
Returns
The numeric type name as a string.
Definition at line 35 of file type-name.cc.