ns-3: Object
Object
Core
Base classes which provide memory management and object aggregation.
Files
file attribute-construction-list.cc
file attribute-construction-list.h
file object-base.cc
file object-base.h
file object-factory.cc
file object-factory.h
file object-test-suite.cc
file object.cc
file object.h
file type-id.cc
file type-id.h
file type-traits-test-suite.cc
file type-traits.h
Classes
class ns3::AttributeConstructionList
class ns3::IidManager
TypeId information manager.
class ns3::Object
A base class which provides memory management and object aggregation.
class ns3::ObjectBase
Anchor the ns-3 type and attribute system.
struct ns3::ObjectDeleter
class ns3::ObjectFactory
Instantiate subclasses of ns3::Object.
class ns3::TypeId
a unique identifier for an interface.
struct ns3::TypeTraits< T >
Macros
#define IID "IidManager"
#define IIDL IID << ": "
#define NS_OBJECT_ENSURE_REGISTERED(type)
Register an Object subclass with the TypeId system.
#define NS_OBJECT_TEMPLATE_CLASS_DEFINE(type, param)
Explicitly instantiate a template class and register the resulting instance with the TypeId system.
Functions
template<typename T >
Ptr< T > ns3::CreateObjectWithAttributes (std::string n1="", const AttributeValue &v1=EmptyAttributeValue(), std::string n2="", const AttributeValue &v2=EmptyAttributeValue(), std::string n3="", const AttributeValue &v3=EmptyAttributeValue(), std::string n4="", const AttributeValue &v4=EmptyAttributeValue(), std::string n5="", const AttributeValue &v5=EmptyAttributeValue(), std::string n6="", const AttributeValue &v6=EmptyAttributeValue(), std::string n7="", const AttributeValue &v7=EmptyAttributeValue(), std::string n8="", const AttributeValue &v8=EmptyAttributeValue(), std::string n9="", const AttributeValue &v9=EmptyAttributeValue())
template<typename T >
Ptr< T > ns3::CreateObject (void)
Create an object by type, with varying number of constructor parameters.
template<typename T , typename T1 >
Ptr< T > ns3::CreateObject (T1 a1)
Create an object by type, with varying number of constructor parameters.
template<typename T , typename T1 , typename T2 >
Ptr< T > ns3::CreateObject (T1 a1, T2 a2)
Create an object by type, with varying number of constructor parameters.
template<typename T , typename T1 , typename T2 , typename T3 >
Ptr< T > ns3::CreateObject (T1 a1, T2 a2, T3 a3)
Create an object by type, with varying number of constructor parameters.
template<typename T , typename T1 , typename T2 , typename T3 , typename T4 >
Ptr< T > ns3::CreateObject (T1 a1, T2 a2, T3 a3, T4 a4)
Create an object by type, with varying number of constructor parameters.
template<typename T , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
Ptr< T > ns3::CreateObject (T1 a1, T2 a2, T3 a3, T4 a4, T5 a5)
Create an object by type, with varying number of constructor parameters.
template<typename T , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 >
Ptr< T > ns3::CreateObject (T1 a1, T2 a2, T3 a3, T4 a4, T5 a5, T6 a6)
Create an object by type, with varying number of constructor parameters.
template<typename T , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 >
Ptr< T > ns3::CreateObject (T1 a1, T2 a2, T3 a3, T4 a4, T5 a5, T6 a6, T7 a7)
Create an object by type, with varying number of constructor parameters.
Detailed Description
Base classes which provide memory management and object aggregation.
Macro Definition Documentation
IID
#define IID "IidManager"
Internal:
IidManager shorthand for use in NS_LOG
Definition at line 378 of file type-id.cc.
IIDL
#define IIDL IID << ": "
Internal:
IidManager shorthand for use in NS_LOG
Definition at line 384 of file type-id.cc.
NS_OBJECT_ENSURE_REGISTERED
#define NS_OBJECT_ENSURE_REGISTERED (type)
Value:
  static struct Object ## type ## RegistrationClass     \
  {                                                     \
    Object ## type ## RegistrationClass () {            \
      ns3::TypeId tid = type::GetTypeId ();             \
      tid.SetSize (sizeof (type));                      \
      tid.GetParent ();                                 \
    }                                                   \
  } Object ## type ## RegistrationVariable
Register an Object subclass with the TypeId system.
This macro should be invoked once for every class which defines a new GetTypeId method.
If the class is in a namespace, then the macro call should also be in the namespace.
Definition at line 46 of file object-base.h.
NS_OBJECT_TEMPLATE_CLASS_DEFINE
#define NS_OBJECT_TEMPLATE_CLASS_DEFINE (type, param)
Value:
  template class type<param>;                                          \
  template <> std::string DoGetTypeParamName<type<param> > ()          \
  {                                                                    \
    return #param;                                                     \
  }                                                                    \
  static struct Object ## type ## param ## RegistrationClass           \
  {                                                                    \
    Object ## type ## param ## RegistrationClass () {                  \
      ns3::TypeId tid = type<param>::GetTypeId ();                     \
      tid.SetSize (sizeof (type<param>));                              \
      tid.GetParent ();                                                \
    }                                                                  \
  } Object ## type ## param ## RegistrationVariable
Explicitly instantiate a template class and register the resulting instance with the TypeId system.
This macro should be invoked once for every required instance of a template class which derives from the Object class and defines a new GetTypeId method.
If the template class is in a namespace, then the macro call should also be in the namespace.
Definition at line 68 of file object-base.h.
Function Documentation
CreateObject() [1/8]
template<typename T , typename T1 > Ptr<T> ns3::CreateObject (T1 a1)
Create an object by type, with varying number of constructor parameters.
Template Parameters
T [explicit] The type of the derived object to construct.
T1 [deduced] The type of the constructor argument.
Parameters
[in] a1 The constructor argument
Returns
The derived object.
Definition at line 545 of file object.h.
References ns3::CompleteConstruct().
CreateObject() [2/8]
template<typename T , typename T1 , typename T2 > Ptr<T> ns3::CreateObject (T1 a1, T2 a2)
Create an object by type, with varying number of constructor parameters.
Template Parameters
T [explicit] The type of the derived object to construct.
T1 [deduced] The type of the first constructor argument.
T2 [deduced] The type of the second constructor argument.
Parameters
[in] a1 The constructor first argument
[in] a2 The constructor second argument
Returns
The derived object.
Definition at line 560 of file object.h.
References ns3::CompleteConstruct().
CreateObject() [3/8]
template<typename T , typename T1 , typename T2 , typename T3 > Ptr<T> ns3::CreateObject (T1 a1, T2 a2, T3 a3)
Create an object by type, with varying number of constructor parameters.
Template Parameters
T [explicit] The type of the derived object to construct.
T1 [deduced] The type of the first constructor argument.
T2 [deduced] The type of the second constructor argument.
T3 [deduced] The type of the third constructor argument.
Parameters
[in] a1 The constructor first argument
[in] a2 The constructor second argument
[in] a3 The constructor third argument
Returns
The derived object.
Definition at line 577 of file object.h.
References ns3::CompleteConstruct().
CreateObject() [4/8]
template<typename T , typename T1 , typename T2 , typename T3 , typename T4 > Ptr<T> ns3::CreateObject (T1 a1, T2 a2, T3 a3, T4 a4)
Create an object by type, with varying number of constructor parameters.
Template Parameters
T [explicit] The type of the derived object to construct.
T1 [deduced] The type of the first constructor argument.
T2 [deduced] The type of the second constructor argument.
T3 [deduced] The type of the third constructor argument.
T4 [deduced] The type of the fourth constructor argument.
Parameters
[in] a1 The constructor first argument
[in] a2 The constructor second argument
[in] a3 The constructor third argument
[in] a4 The constructor fourth argument
Returns
The derived object.
Definition at line 596 of file object.h.
References ns3::CompleteConstruct().
CreateObject() [5/8]
template<typename T , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > Ptr<T> ns3::CreateObject (T1 a1, T2 a2, T3 a3, T4 a4, T5 a5)
Create an object by type, with varying number of constructor parameters.
Template Parameters
T [explicit] The type of the derived object to construct.
T1 [deduced] The type of the first constructor argument.
T2 [deduced] The type of the second constructor argument.
T3 [deduced] The type of the third constructor argument.
T4 [deduced] The type of the fourth constructor argument.
T5 [deduced] The type of the fifth constructor argument.
Parameters
[in] a1 The constructor first argument
[in] a2 The constructor second argument
[in] a3 The constructor third argument
[in] a4 The constructor fourth argument
[in] a5 The constructor fifth argument
Returns
The derived object.
Definition at line 617 of file object.h.
References ns3::CompleteConstruct().
CreateObject() [6/8]
template<typename T , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 > Ptr<T> ns3::CreateObject (T1 a1, T2 a2, T3 a3, T4 a4, T5 a5, T6 a6)
Create an object by type, with varying number of constructor parameters.
Template Parameters
T [explicit] The type of the derived object to construct.
T1 [deduced] The type of the first constructor argument.
T2 [deduced] The type of the second constructor argument.
T3 [deduced] The type of the third constructor argument.
T4 [deduced] The type of the fourth constructor argument.
T5 [deduced] The type of the fifth constructor argument.
T6 [deduced] The type of the sixth constructor argument.
Parameters
[in] a1 The constructor first argument
[in] a2 The constructor second argument
[in] a3 The constructor third argument
[in] a4 The constructor fourth argument
[in] a5 The constructor fifth argument
[in] a6 The constructor sixth argument
Returns
The derived object.
Definition at line 640 of file object.h.
References ns3::CompleteConstruct().
CreateObject() [7/8]
template<typename T , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 > Ptr<T> ns3::CreateObject (T1 a1, T2 a2, T3 a3, T4 a4, T5 a5, T6 a6, T7 a7)
Create an object by type, with varying number of constructor parameters.
Template Parameters
T [explicit] The type of the derived object to construct.
T1 [deduced] The type of the first constructor argument.
T2 [deduced] The type of the second constructor argument.
T3 [deduced] The type of the third constructor argument.
T4 [deduced] The type of the fourth constructor argument.
T5 [deduced] The type of the fifth constructor argument.
T6 [deduced] The type of the sixth constructor argument.
T7 [deduced] The type of the seventh constructor argument.
Parameters
[in] a1 The constructor first argument
[in] a2 The constructor second argument
[in] a3 The constructor third argument
[in] a4 The constructor fourth argument
[in] a5 The constructor fifth argument
[in] a6 The constructor sixth argument
[in] a7 The constructor seventh argument
Returns
The derived object.
Definition at line 665 of file object.h.
References ns3::CompleteConstruct().
CreateObject() [8/8]
template<typename T > Ptr<T> ns3::CreateObject (void)
Create an object by type, with varying number of constructor parameters.
Template Parameters
T [explicit] The type of the derived object to construct.
Returns
The derived object.
Definition at line 533 of file object.h.
References ns3::CompleteConstruct().
Referenced by ns3::Ipv4L3Protocol::AddInterface(), ns3::Ipv6L3Protocol::AddInterface(), TestChildQueueDisc::CheckConfig(), Ipv6L3ProtocolTestCase::DoRun(), Ipv4L3ProtocolTestCase::DoRun(), PointToPointTest::DoRun(), ns3::Ipv6L3Protocol::SetupLoopback(), and ns3::Ipv4L3Protocol::SetupLoopback().
CreateObjectWithAttributes()
template<typename T > Ptr< T > ns3::CreateObjectWithAttributes (std::string n1 = "", const AttributeValue & v1 = EmptyAttributeValue (), std::string n2 = "", const AttributeValue & v2 = EmptyAttributeValue (), std::string n3 = "", const AttributeValue & v3 = EmptyAttributeValue (), std::string n4 = "", const AttributeValue & v4 = EmptyAttributeValue (), std::string n5 = "", const AttributeValue & v5 = EmptyAttributeValue (), std::string n6 = "", const AttributeValue & v6 = EmptyAttributeValue (), std::string n7 = "", const AttributeValue & v7 = EmptyAttributeValue (), std::string n8 = "", const AttributeValue & v8 = EmptyAttributeValue (), std::string n9 = "", const AttributeValue & v9 = EmptyAttributeValue ())
Allocate an Object on the heap and initialize with a set of attributes.
Template Parameters
T [explicit] The requested Object type.
Parameters
[in] n1 Name of attribute
[in] v1 Value of attribute
[in] n2 Name of attribute
[in] v2 Value of attribute
[in] n3 Name of attribute
[in] v3 Value of attribute
[in] n4 Name of attribute
[in] v4 Value of attribute
[in] n5 Name of attribute
[in] v5 Value of attribute
[in] n6 Name of attribute
[in] v6 Value of attribute
[in] n7 Name of attribute
[in] v7 Value of attribute
[in] n8 Name of attribute
[in] v8 Value of attribute
[in] n9 Name of attribute
[in] v9 Value of attribute
Returns
A pointer to a newly allocated object.
Definition at line 214 of file object-factory.h.
References ns3::ObjectFactory::Create(), ns3::ObjectFactory::Set(), and ns3::ObjectFactory::SetTypeId().
Referenced by ns3::CobaltQueueDisc::CheckConfig(), ns3::CoDelQueueDisc::CheckConfig(), ns3::FifoQueueDisc::CheckConfig(), ns3::PieQueueDisc::CheckConfig(), and ns3::RedQueueDisc::CheckConfig().