ns-3: MakeBoundCallback from functions bound with up to three arguments.
MakeBoundCallback from functions bound with up to three arguments.
Core » Callbacks
Build bound Callbacks which take varying numbers of arguments, and potentially returning a value.
template<typename R , typename TX , typename ARG >
Callback< R > ns3::MakeBoundCallback (R(*fnPtr)(TX), ARG a1)
template<typename R , typename TX , typename ARG , typename T1 >
Callback< R, T1 > ns3::MakeBoundCallback (R(*fnPtr)(TX, T1), ARG a1)
template<typename R , typename TX , typename ARG , typename T1 , typename T2 >
Callback< R, T1, T2 > ns3::MakeBoundCallback (R(*fnPtr)(TX, T1, T2), ARG a1)
template<typename R , typename TX , typename ARG , typename T1 , typename T2 , typename T3 >
Callback< R, T1, T2, T3 > ns3::MakeBoundCallback (R(*fnPtr)(TX, T1, T2, T3), ARG a1)
template<typename R , typename TX , typename ARG , typename T1 , typename T2 , typename T3 , typename T4 >
Callback< R, T1, T2, T3, T4 > ns3::MakeBoundCallback (R(*fnPtr)(TX, T1, T2, T3, T4), ARG a1)
template<typename R , typename TX , typename ARG , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
Callback< R, T1, T2, T3, T4, T5 > ns3::MakeBoundCallback (R(*fnPtr)(TX, T1, T2, T3, T4, T5), ARG a1)
template<typename R , typename TX , typename ARG , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 >
Callback< R, T1, T2, T3, T4, T5, T6 > ns3::MakeBoundCallback (R(*fnPtr)(TX, T1, T2, T3, T4, T5, T6), ARG a1)
template<typename R , typename TX , typename ARG , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 >
Callback< R, T1, T2, T3, T4, T5, T6, T7 > ns3::MakeBoundCallback (R(*fnPtr)(TX, T1, T2, T3, T4, T5, T6, T7), ARG a1)
template<typename R , typename TX , typename ARG , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 >
Callback< R, T1, T2, T3, T4, T5, T6, T7, T8 > ns3::MakeBoundCallback (R(*fnPtr)(TX, T1, T2, T3, T4, T5, T6, T7, T8), ARG a1)
template<typename R , typename TX1 , typename TX2 , typename ARG1 , typename ARG2 >
Callback< R > ns3::MakeBoundCallback (R(*fnPtr)(TX1, TX2), ARG1 a1, ARG2 a2)
template<typename R , typename TX1 , typename TX2 , typename ARG1 , typename ARG2 , typename T1 >
Callback< R, T1 > ns3::MakeBoundCallback (R(*fnPtr)(TX1, TX2, T1), ARG1 a1, ARG2 a2)
template<typename R , typename TX1 , typename TX2 , typename ARG1 , typename ARG2 , typename T1 , typename T2 >
Callback< R, T1, T2 > ns3::MakeBoundCallback (R(*fnPtr)(TX1, TX2, T1, T2), ARG1 a1, ARG2 a2)
template<typename R , typename TX1 , typename TX2 , typename ARG1 , typename ARG2 , typename T1 , typename T2 , typename T3 >
Callback< R, T1, T2, T3 > ns3::MakeBoundCallback (R(*fnPtr)(TX1, TX2, T1, T2, T3), ARG1 a1, ARG2 a2)
template<typename R , typename TX1 , typename TX2 , typename ARG1 , typename ARG2 , typename T1 , typename T2 , typename T3 , typename T4 >
Callback< R, T1, T2, T3, T4 > ns3::MakeBoundCallback (R(*fnPtr)(TX1, TX2, T1, T2, T3, T4), ARG1 a1, ARG2 a2)
template<typename R , typename TX1 , typename TX2 , typename ARG1 , typename ARG2 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
Callback< R, T1, T2, T3, T4, T5 > ns3::MakeBoundCallback (R(*fnPtr)(TX1, TX2, T1, T2, T3, T4, T5), ARG1 a1, ARG2 a2)
template<typename R , typename TX1 , typename TX2 , typename ARG1 , typename ARG2 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 >
Callback< R, T1, T2, T3, T4, T5, T6 > ns3::MakeBoundCallback (R(*fnPtr)(TX1, TX2, T1, T2, T3, T4, T5, T6), ARG1 a1, ARG2 a2)
template<typename R , typename TX1 , typename TX2 , typename ARG1 , typename ARG2 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 >
Callback< R, T1, T2, T3, T4, T5, T6, T7 > ns3::MakeBoundCallback (R(*fnPtr)(TX1, TX2, T1, T2, T3, T4, T5, T6, T7), ARG1 a1, ARG2 a2)
template<typename R , typename TX1 , typename TX2 , typename TX3 , typename ARG1 , typename ARG2 , typename ARG3 >
Callback< R > ns3::MakeBoundCallback (R(*fnPtr)(TX1, TX2, TX3), ARG1 a1, ARG2 a2, ARG3 a3)
template<typename R , typename TX1 , typename TX2 , typename TX3 , typename ARG1 , typename ARG2 , typename ARG3 , typename T1 >
Callback< R, T1 > ns3::MakeBoundCallback (R(*fnPtr)(TX1, TX2, TX3, T1), ARG1 a1, ARG2 a2, ARG3 a3)
template<typename R , typename TX1 , typename TX2 , typename TX3 , typename ARG1 , typename ARG2 , typename ARG3 , typename T1 , typename T2 >
Callback< R, T1, T2 > ns3::MakeBoundCallback (R(*fnPtr)(TX1, TX2, TX3, T1, T2), ARG1 a1, ARG2 a2, ARG3 a3)
template<typename R , typename TX1 , typename TX2 , typename TX3 , typename ARG1 , typename ARG2 , typename ARG3 , typename T1 , typename T2 , typename T3 >
Callback< R, T1, T2, T3 > ns3::MakeBoundCallback (R(*fnPtr)(TX1, TX2, TX3, T1, T2, T3), ARG1 a1, ARG2 a2, ARG3 a3)
template<typename R , typename TX1 , typename TX2 , typename TX3 , typename ARG1 , typename ARG2 , typename ARG3 , typename T1 , typename T2 , typename T3 , typename T4 >
Callback< R, T1, T2, T3, T4 > ns3::MakeBoundCallback (R(*fnPtr)(TX1, TX2, TX3, T1, T2, T3, T4), ARG1 a1, ARG2 a2, ARG3 a3)
template<typename R , typename TX1 , typename TX2 , typename TX3 , typename ARG1 , typename ARG2 , typename ARG3 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
Callback< R, T1, T2, T3, T4, T5 > ns3::MakeBoundCallback (R(*fnPtr)(TX1, TX2, TX3, T1, T2, T3, T4, T5), ARG1 a1, ARG2 a2, ARG3 a3)
template<typename R , typename TX1 , typename TX2 , typename TX3 , typename ARG1 , typename ARG2 , typename ARG3 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 >
Callback< R, T1, T2, T3, T4, T5, T6 > ns3::MakeBoundCallback (R(*fnPtr)(TX1, TX2, TX3, T1, T2, T3, T4, T5, T6), ARG1 a1, ARG2 a2, ARG3 a3)
Detailed Description
Build bound Callbacks which take varying numbers of arguments, and potentially returning a value.
Internal:
The following is experimental code. It works but we have not yet determined whether or not it is really useful and whether or not we really want to use it.
Function Documentation
MakeBoundCallback() [1/24]
template<typename R , typename TX , typename ARG > Callback<R> ns3::MakeBoundCallback (R(*)(TX) fnPtr, ARG a1)
Make Callbacks with one bound argument.
Parameters
[in] fnPtr Function pointer
[in] a1 First bound argument
Returns
A bound Callback
Definition at line 1847 of file callback.h.
References ns3::Create(), and TX.
Referenced by ns3::LteHelper::ActivateDataRadioBearer(), ns3::CommandLine::AddValue(), ns3::RadioBearerStatsConnector::ConnectTracesDrbEnb(), ns3::RadioBearerStatsConnector::ConnectTracesDrbUe(), ns3::RadioBearerStatsConnector::ConnectTracesSrb0(), ns3::RadioBearerStatsConnector::ConnectTracesSrb1(), MakeBoundCallbackTestCase::DoRun(), MakeCallbackTemplatesTestCase::DoRun(), LrWpanAckTestCase::DoRun(), LrWpanCcaTestCase::DoRun(), LrWpanDataIfsTestCase::DoRun(), LrWpanSlottedCsmacaTestCase::DoRun(), CarrierAggregationTestCase::DoRun(), LteCqiGenerationTestCase::DoRun(), LteCqiGenerationDlPowerControlTestCase::DoRun(), LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::DoRun(), LteHardFrTestCase::DoRun(), LteStrictFrTestCase::DoRun(), LteStrictFrAreaTestCase::DoRun(), LteSoftFrAreaTestCase::DoRun(), LteSoftFfrAreaTestCase::DoRun(), LteEnhancedFfrAreaTestCase::DoRun(), LteDistributedFfrAreaTestCase::DoRun(), LteInterferenceTestCase::DoRun(), LteLinkAdaptationTestCase::DoRun(), LteUeMeasurementsTestCase::DoRun(), LteUplinkOpenLoopPowerControlTestCase::DoRun(), LteUplinkClosedLoopPowerControlAbsoluteModeTestCase::DoRun(), LteUplinkClosedLoopPowerControlAccumulatedModeTestCase::DoRun(), WifiAcMappingTest::DoRun(), ThreadedSimulatorEventsTestCase::DoSetup(), ns3::MobilityHelper::EnableAscii(), ns3::UanHelper::EnableAscii(), ns3::WimaxHelper::EnableAsciiForConnection(), ns3::CsmaHelper::EnableAsciiInternal(), ns3::FdNetDeviceHelper::EnableAsciiInternal(), ns3::LrWpanHelper::EnableAsciiInternal(), ns3::PointToPointHelper::EnableAsciiInternal(), ns3::YansWavePhyHelper::EnableAsciiInternal(), ns3::WifiPhyHelper::EnableAsciiInternal(), ns3::WimaxHelper::EnableAsciiInternal(), ns3::InternetStackHelper::EnableAsciiIpv4Internal(), ns3::InternetStackHelper::EnableAsciiIpv6Internal(), ns3::LteHelper::EnableDlMacTraces(), ns3::LteHelper::EnableDlPhyTraces(), ns3::LteHelper::EnableDlRxPhyTraces(), ns3::LteHelper::EnableDlTxPhyTraces(), ns3::WimaxHelper::EnablePcapInternal(), ns3::LrWpanHelper::EnablePcapInternal(), ns3::YansWavePhyHelper::EnablePcapInternal(), ns3::WifiPhyHelper::EnablePcapInternal(), ns3::LteHelper::EnableUlMacTraces(), ns3::LteHelper::EnableUlPhyTraces(), ns3::LteHelper::EnableUlRxPhyTraces(), ns3::LteHelper::EnableUlTxPhyTraces(), ns3::RadioBearerStatsConnector::EnsureConnected(), ns3::AsciiTraceHelper::HookDefaultDequeueSinkWithContext(), ns3::AsciiTraceHelper::HookDefaultDequeueSinkWithoutContext(), ns3::AsciiTraceHelper::HookDefaultDropSinkWithContext(), ns3::AsciiTraceHelper::HookDefaultDropSinkWithoutContext(), ns3::AsciiTraceHelper::HookDefaultEnqueueSinkWithContext(), ns3::AsciiTraceHelper::HookDefaultEnqueueSinkWithoutContext(), ns3::AsciiTraceHelper::HookDefaultReceiveSinkWithContext(), ns3::AsciiTraceHelper::HookDefaultReceiveSinkWithoutContext(), ns3::PcapHelper::HookDefaultSink(), ns3::SpectrumAnalyzerHelper::Install(), VanetRoutingExperiment::SetupAdhocMobilityNodes(), ns3::RadioBearerStatsConnector::StoreUeManagerPath(), TraceCwnd(), TraceDroppingState(), TraceEveryDrop(), TraceQueueLength(), and TraceSojourn().
MakeBoundCallback() [2/24]
template<typename R , typename TX , typename ARG , typename T1 > Callback<R,T1> ns3::MakeBoundCallback (R(*)(TX, T1) fnPtr, ARG a1)
Make Callbacks with one bound argument.
Parameters
[in] fnPtr Function pointer
[in] a1 First bound argument
Returns
A bound Callback
Definition at line 1855 of file callback.h.
References ns3::Create(), and TX.
MakeBoundCallback() [3/24]
template<typename R , typename TX , typename ARG , typename T1 , typename T2 > Callback<R,T1,T2> ns3::MakeBoundCallback (R(*)(TX, T1, T2) fnPtr, ARG a1)
Make Callbacks with one bound argument.
Parameters
[in] fnPtr Function pointer
[in] a1 First bound argument
Returns
A bound Callback
Definition at line 1863 of file callback.h.
References ns3::Create(), and TX.
MakeBoundCallback() [4/24]
template<typename R , typename TX , typename ARG , typename T1 , typename T2 , typename T3 > Callback<R,T1,T2,T3> ns3::MakeBoundCallback (R(*)(TX, T1, T2, T3) fnPtr, ARG a1)
Make Callbacks with one bound argument.
Parameters
[in] fnPtr Function pointer
[in] a1 First bound argument
Returns
A bound Callback
Definition at line 1871 of file callback.h.
References ns3::Create(), and TX.
MakeBoundCallback() [5/24]
template<typename R , typename TX , typename ARG , typename T1 , typename T2 , typename T3 , typename T4 > Callback<R,T1,T2,T3,T4> ns3::MakeBoundCallback (R(*)(TX, T1, T2, T3, T4) fnPtr, ARG a1)
Make Callbacks with one bound argument.
Parameters
[in] fnPtr Function pointer
[in] a1 First bound argument
Returns
A bound Callback
Definition at line 1879 of file callback.h.
References ns3::Create(), and TX.
MakeBoundCallback() [6/24]
template<typename R , typename TX , typename ARG , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > Callback<R,T1,T2,T3,T4,T5> ns3::MakeBoundCallback (R(*)(TX, T1, T2, T3, T4, T5) fnPtr, ARG a1)
Make Callbacks with one bound argument.
Parameters
[in] fnPtr Function pointer
[in] a1 First bound argument
Returns
A bound Callback
Definition at line 1887 of file callback.h.
References ns3::Create(), and TX.
MakeBoundCallback() [7/24]
template<typename R , typename TX , typename ARG , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 > Callback<R,T1,T2,T3,T4,T5,T6> ns3::MakeBoundCallback (R(*)(TX, T1, T2, T3, T4, T5, T6) fnPtr, ARG a1)
Make Callbacks with one bound argument.
Parameters
[in] fnPtr Function pointer
[in] a1 First bound argument
Returns
A bound Callback
Definition at line 1895 of file callback.h.
References ns3::Create(), and TX.
MakeBoundCallback() [8/24]
template<typename R , typename TX , typename ARG , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 > Callback<R,T1,T2,T3,T4,T5,T6,T7> ns3::MakeBoundCallback (R(*)(TX, T1, T2, T3, T4, T5, T6, T7) fnPtr, ARG a1)
Make Callbacks with one bound argument.
Parameters
[in] fnPtr Function pointer
[in] a1 First bound argument
Returns
A bound Callback
Definition at line 1903 of file callback.h.
References ns3::Create(), and TX.
MakeBoundCallback() [9/24]
template<typename R , typename TX , typename ARG , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 > Callback<R,T1,T2,T3,T4,T5,T6,T7,T8> ns3::MakeBoundCallback (R(*)(TX, T1, T2, T3, T4, T5, T6, T7, T8) fnPtr, ARG a1)
Make Callbacks with one bound argument.
Parameters
[in] fnPtr Function pointer
[in] a1 First bound argument
Returns
A bound Callback
Definition at line 1911 of file callback.h.
References ns3::Create(), and TX.
MakeBoundCallback() [10/24]
template<typename R , typename TX1 , typename TX2 , typename ARG1 , typename ARG2 > Callback<R> ns3::MakeBoundCallback (R(*)(TX1, TX2) fnPtr, ARG1 a1, ARG2 a2)
Make Callbacks with two bound arguments.
Parameters
[in] fnPtr Function pointer
[in] a1 First bound argument
[in] a2 Second bound argument
Returns
A bound Callback
Definition at line 1929 of file callback.h.
References ns3::Create().
MakeBoundCallback() [11/24]
template<typename R , typename TX1 , typename TX2 , typename ARG1 , typename ARG2 , typename T1 > Callback<R,T1> ns3::MakeBoundCallback (R(*)(TX1, TX2, T1) fnPtr, ARG1 a1, ARG2 a2)
Make Callbacks with two bound arguments.
Parameters
[in] fnPtr Function pointer
[in] a1 First bound argument
[in] a2 Second bound argument
Returns
A bound Callback
Definition at line 1937 of file callback.h.
References ns3::Create().
MakeBoundCallback() [12/24]
template<typename R , typename TX1 , typename TX2 , typename ARG1 , typename ARG2 , typename T1 , typename T2 > Callback<R,T1,T2> ns3::MakeBoundCallback (R(*)(TX1, TX2, T1, T2) fnPtr, ARG1 a1, ARG2 a2)
Make Callbacks with two bound arguments.
Parameters
[in] fnPtr Function pointer
[in] a1 First bound argument
[in] a2 Second bound argument
Returns
A bound Callback
Definition at line 1945 of file callback.h.
References ns3::Create().
MakeBoundCallback() [13/24]
template<typename R , typename TX1 , typename TX2 , typename ARG1 , typename ARG2 , typename T1 , typename T2 , typename T3 > Callback<R,T1,T2,T3> ns3::MakeBoundCallback (R(*)(TX1, TX2, T1, T2, T3) fnPtr, ARG1 a1, ARG2 a2)
Make Callbacks with two bound arguments.
Parameters
[in] fnPtr Function pointer
[in] a1 First bound argument
[in] a2 Second bound argument
Returns
A bound Callback
Definition at line 1953 of file callback.h.
References ns3::Create().
MakeBoundCallback() [14/24]
template<typename R , typename TX1 , typename TX2 , typename ARG1 , typename ARG2 , typename T1 , typename T2 , typename T3 , typename T4 > Callback<R,T1,T2,T3,T4> ns3::MakeBoundCallback (R(*)(TX1, TX2, T1, T2, T3, T4) fnPtr, ARG1 a1, ARG2 a2)
Make Callbacks with two bound arguments.
Parameters
[in] fnPtr Function pointer
[in] a1 First bound argument
[in] a2 Second bound argument
Returns
A bound Callback
Definition at line 1961 of file callback.h.
References ns3::Create().
MakeBoundCallback() [15/24]
template<typename R , typename TX1 , typename TX2 , typename ARG1 , typename ARG2 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > Callback<R,T1,T2,T3,T4,T5> ns3::MakeBoundCallback (R(*)(TX1, TX2, T1, T2, T3, T4, T5) fnPtr, ARG1 a1, ARG2 a2)
Make Callbacks with two bound arguments.
Parameters
[in] fnPtr Function pointer
[in] a1 First bound argument
[in] a2 Second bound argument
Returns
A bound Callback
Definition at line 1969 of file callback.h.
References ns3::Create().
MakeBoundCallback() [16/24]
template<typename R , typename TX1 , typename TX2 , typename ARG1 , typename ARG2 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 > Callback<R,T1,T2,T3,T4,T5,T6> ns3::MakeBoundCallback (R(*)(TX1, TX2, T1, T2, T3, T4, T5, T6) fnPtr, ARG1 a1, ARG2 a2)
Make Callbacks with two bound arguments.
Parameters
[in] fnPtr Function pointer
[in] a1 First bound argument
[in] a2 Second bound argument
Returns
A bound Callback
Definition at line 1977 of file callback.h.
References ns3::Create().
MakeBoundCallback() [17/24]
template<typename R , typename TX1 , typename TX2 , typename ARG1 , typename ARG2 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 > Callback<R,T1,T2,T3,T4,T5,T6,T7> ns3::MakeBoundCallback (R(*)(TX1, TX2, T1, T2, T3, T4, T5, T6, T7) fnPtr, ARG1 a1, ARG2 a2)
Make Callbacks with two bound arguments.
Parameters
[in] fnPtr Function pointer
[in] a1 First bound argument
[in] a2 Second bound argument
Returns
A bound Callback
Definition at line 1985 of file callback.h.
References ns3::Create().
MakeBoundCallback() [18/24]
template<typename R , typename TX1 , typename TX2 , typename TX3 , typename ARG1 , typename ARG2 , typename ARG3 > Callback<R> ns3::MakeBoundCallback (R(*)(TX1, TX2, TX3) fnPtr, ARG1 a1, ARG2 a2, ARG3 a3)
Make Callbacks with three bound arguments.
Parameters
[in] a1 First bound argument
[in] a2 Second bound argument
[in] a3 Third bound argument
[in] fnPtr Function pointer
Returns
A bound Callback
Definition at line 2004 of file callback.h.
References ns3::Create().
MakeBoundCallback() [19/24]
template<typename R , typename TX1 , typename TX2 , typename TX3 , typename ARG1 , typename ARG2 , typename ARG3 , typename T1 > Callback<R,T1> ns3::MakeBoundCallback (R(*)(TX1, TX2, TX3, T1) fnPtr, ARG1 a1, ARG2 a2, ARG3 a3)
Make Callbacks with three bound arguments.
Parameters
[in] a1 First bound argument
[in] a2 Second bound argument
[in] a3 Third bound argument
[in] fnPtr Function pointer
Returns
A bound Callback
Definition at line 2012 of file callback.h.
References ns3::Create().
MakeBoundCallback() [20/24]
template<typename R , typename TX1 , typename TX2 , typename TX3 , typename ARG1 , typename ARG2 , typename ARG3 , typename T1 , typename T2 > Callback<R,T1,T2> ns3::MakeBoundCallback (R(*)(TX1, TX2, TX3, T1, T2) fnPtr, ARG1 a1, ARG2 a2, ARG3 a3)
Make Callbacks with three bound arguments.
Parameters
[in] a1 First bound argument
[in] a2 Second bound argument
[in] a3 Third bound argument
[in] fnPtr Function pointer
Returns
A bound Callback
Definition at line 2020 of file callback.h.
References ns3::Create().
MakeBoundCallback() [21/24]
template<typename R , typename TX1 , typename TX2 , typename TX3 , typename ARG1 , typename ARG2 , typename ARG3 , typename T1 , typename T2 , typename T3 > Callback<R,T1,T2,T3> ns3::MakeBoundCallback (R(*)(TX1, TX2, TX3, T1, T2, T3) fnPtr, ARG1 a1, ARG2 a2, ARG3 a3)
Make Callbacks with three bound arguments.
Parameters
[in] a1 First bound argument
[in] a2 Second bound argument
[in] a3 Third bound argument
[in] fnPtr Function pointer
Returns
A bound Callback
Definition at line 2028 of file callback.h.
References ns3::Create().
MakeBoundCallback() [22/24]
template<typename R , typename TX1 , typename TX2 , typename TX3 , typename ARG1 , typename ARG2 , typename ARG3 , typename T1 , typename T2 , typename T3 , typename T4 > Callback<R,T1,T2,T3,T4> ns3::MakeBoundCallback (R(*)(TX1, TX2, TX3, T1, T2, T3, T4) fnPtr, ARG1 a1, ARG2 a2, ARG3 a3)
Make Callbacks with three bound arguments.
Parameters
[in] a1 First bound argument
[in] a2 Second bound argument
[in] a3 Third bound argument
[in] fnPtr Function pointer
Returns
A bound Callback
Definition at line 2036 of file callback.h.
References ns3::Create().
MakeBoundCallback() [23/24]
template<typename R , typename TX1 , typename TX2 , typename TX3 , typename ARG1 , typename ARG2 , typename ARG3 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > Callback<R,T1,T2,T3,T4,T5> ns3::MakeBoundCallback (R(*)(TX1, TX2, TX3, T1, T2, T3, T4, T5) fnPtr, ARG1 a1, ARG2 a2, ARG3 a3)
Make Callbacks with three bound arguments.
Parameters
[in] a1 First bound argument
[in] a2 Second bound argument
[in] a3 Third bound argument
[in] fnPtr Function pointer
Returns
A bound Callback
Definition at line 2044 of file callback.h.
References ns3::Create().
MakeBoundCallback() [24/24]
template<typename R , typename TX1 , typename TX2 , typename TX3 , typename ARG1 , typename ARG2 , typename ARG3 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 > Callback<R,T1,T2,T3,T4,T5,T6> ns3::MakeBoundCallback (R(*)(TX1, TX2, TX3, T1, T2, T3, T4, T5, T6) fnPtr, ARG1 a1, ARG2 a2, ARG3 a3)
Make Callbacks with three bound arguments.
Parameters
[in] a1 First bound argument
[in] a2 Second bound argument
[in] a3 Third bound argument
[in] fnPtr Function pointer
Returns
A bound Callback
Definition at line 2052 of file callback.h.
References ns3::Create().