ns-3: File Descriptor Network Device
File Descriptor Network Device
This section documents the API of the ns-3 fd-net-device module. For a generic functional description, please refer to the ns-3 manual.
Classes
class ns3::EmuFdNetDeviceHelper
build a set of FdNetDevice objects attached to a physical network interface
class ns3::FdNetDevice
a NetDevice to read/write network traffic from/into a file descriptor.
class ns3::FdNetDeviceFdReader
This class performs the actual data reading from the sockets.
class ns3::FdNetDeviceHelper
build a set of FdNetDevice objects Normally we eschew multiple inheritance, however, the classes PcapUserHelperForDevice and AsciiTraceUserHelperForDevice are treated as "mixins". A mixin is a self-contained class that encapsulates a general attribute or a set of functionality that may be of interest to many other classes.
class ns3::PlanetLabFdNetDeviceHelper
build a set of FdNetDevice objects attached to a virtual TAP network interface
class ns3::TapFdNetDeviceHelper
build a set of FdNetDevice objects attached to a virtual TAP network interface
Functions
static void ns3::AddPIHeader (uint8_t *&buf, size_t &len)
Synthesize PI header for the kernel.
static void ns3::RemovePIHeader (uint8_t *&buf, ssize_t &len)
Removes PI header.
void ns3::SendSocket (const char *path, int fd, const int magic_number)
Send the file descriptor back to the code that invoked the creation.
Detailed Description
This section documents the API of the ns-3 fd-net-device module. For a generic functional description, please refer to the ns-3 manual.
Function Documentation
AddPIHeader()
static void ns3::AddPIHeader (uint8_t *& buf, size_t & len) static
Synthesize PI header for the kernel.
Parameters
buf the buffer to add the header to
len the buffer length
Todo:
Consider having a instance member m_packetBuffer and using memmove instead of memcpy to add the PI header. It might be faster in this case to use memmove and avoid the extra mallocs.
Definition at line 331 of file fd-net-device.cc.
Referenced by ns3::FdNetDevice::SendFrom().
RemovePIHeader()
static void ns3::RemovePIHeader (uint8_t *& buf, ssize_t & len) static
Removes PI header.
Parameters
buf the buffer to add the header to
len the buffer length
Definition at line 373 of file fd-net-device.cc.
Referenced by ns3::FdNetDevice::ForwardUp().
SendSocket()
void ns3::SendSocket (const char * path, int fd, const int magic_number)
Send the file descriptor back to the code that invoked the creation.
Parameters
path The socket address information from the Unix socket we use to send the created socket back to.
fd The file descriptor we're going to send.
magic_number A verification number to verify the caller is talking to the right process.
Definition at line 54 of file creator-utils.cc.
References ABORT_IF, LOG, and ns3::StringToBuffer().