ns-3: MakeCallback from member function pointer
MakeCallback from member function pointer
Core » Callbacks
Build Callbacks for class method members which take varying numbers of arguments and potentially returning a value.
Classes
struct ns3::CallbackTraits< T >
struct ns3::CallbackTraits< T * >
class ns3::MemPtrCallbackImpl< OBJ_PTR, MEM_PTR, R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >
template<typename T , typename OBJ , typename R >
Callback< R > ns3::MakeCallback (R(T::*memPtr)(void), OBJ objPtr)
template<typename T , typename OBJ , typename R >
Callback< R > ns3::MakeCallback (R(T::*memPtr)() const, OBJ objPtr)
template<typename T , typename OBJ , typename R , typename T1 >
Callback< R, T1 > ns3::MakeCallback (R(T::*memPtr)(T1), OBJ objPtr)
template<typename T , typename OBJ , typename R , typename T1 , typename T2 >
Callback< R, T1, T2 > ns3::MakeCallback (R(T::*memPtr)(T1, T2), OBJ objPtr)
template<typename T , typename OBJ , typename R , typename T1 , typename T2 , typename T3 >
Callback< R, T1, T2, T3 > ns3::MakeCallback (R(T::*memPtr)(T1, T2, T3), OBJ objPtr)
template<typename T , typename OBJ , typename R , typename T1 , typename T2 , typename T3 , typename T4 >
Callback< R, T1, T2, T3, T4 > ns3::MakeCallback (R(T::*memPtr)(T1, T2, T3, T4), OBJ objPtr)
template<typename T , typename OBJ , typename R , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
Callback< R, T1, T2, T3, T4, T5 > ns3::MakeCallback (R(T::*memPtr)(T1, T2, T3, T4, T5), OBJ objPtr)
template<typename T , typename OBJ , typename R , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 >
Callback< R, T1, T2, T3, T4, T5, T6 > ns3::MakeCallback (R(T::*memPtr)(T1, T2, T3, T4, T5, T6), OBJ objPtr)
template<typename T , typename OBJ , typename R , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 >
Callback< R, T1, T2, T3, T4, T5, T6, T7 > ns3::MakeCallback (R(T::*memPtr)(T1, T2, T3, T4, T5, T6, T7), OBJ objPtr)
template<typename T , typename OBJ , typename R , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 >
Callback< R, T1, T2, T3, T4, T5, T6, T7, T8 > ns3::MakeCallback (R(T::*memPtr)(T1, T2, T3, T4, T5, T6, T7, T8), OBJ objPtr)
template<typename T , typename OBJ , typename R , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 >
Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 > ns3::MakeCallback (R(T::*memPtr)(T1, T2, T3, T4, T5, T6, T7, T8, T9), OBJ objPtr)
Detailed Description
Build Callbacks for class method members which take varying numbers of arguments and potentially returning a value.
Generally the MakeCallback functions are invoked with the method function address first, followed by the this pointer:
MakeCallback (& MyClass::Handler, this);
There is not a version with bound arguments. You may be able to get the same result by using MakeBoundCallback with a static member function, as in:
MakeBoundCallback (& MyClass::StaticHandler, this);
This still leaves two argument slots available for binding.
Function Documentation
MakeCallback() [1/11]
template<typename T , typename OBJ , typename R > Callback<R> ns3::MakeCallback (R(T::*)() const memPtr, OBJ objPtr)
Parameters
[in] memPtr Class method member pointer
[in] objPtr Class instance
Returns
A wrapper Callback
Build Callbacks for class method members which take varying numbers of arguments and potentially returning a value.
Definition at line 1615 of file callback.h.
MakeCallback() [2/11]
template<typename T , typename OBJ , typename R , typename T1 > Callback< R, T1 > ns3::MakeCallback (R(T::*)(T1) memPtr, OBJ objPtr)
Parameters
[in] memPtr Class method member pointer
[in] objPtr Class instance
Returns
A wrapper Callback
Build Callbacks for class method members which take varying numbers of arguments and potentially returning a value.
Definition at line 1620 of file callback.h.
MakeCallback() [3/11]
template<typename T , typename OBJ , typename R , typename T1 , typename T2 > Callback< R, T1, T2 > ns3::MakeCallback (R(T::*)(T1, T2) memPtr, OBJ objPtr)
Parameters
[in] memPtr Class method member pointer
[in] objPtr Class instance
Returns
A wrapper Callback
Build Callbacks for class method members which take varying numbers of arguments and potentially returning a value.
Definition at line 1630 of file callback.h.
MakeCallback() [4/11]
template<typename T , typename OBJ , typename R , typename T1 , typename T2 , typename T3 > Callback< R, T1, T2, T3 > ns3::MakeCallback (R(T::*)(T1, T2, T3) memPtr, OBJ objPtr)
Parameters
[in] memPtr Class method member pointer
[in] objPtr Class instance
Returns
A wrapper Callback
Build Callbacks for class method members which take varying numbers of arguments and potentially returning a value.
Definition at line 1640 of file callback.h.
MakeCallback() [5/11]
template<typename T , typename OBJ , typename R , typename T1 , typename T2 , typename T3 , typename T4 > Callback< R, T1, T2, T3, T4 > ns3::MakeCallback (R(T::*)(T1, T2, T3, T4) memPtr, OBJ objPtr)
Parameters
[in] memPtr Class method member pointer
[in] objPtr Class instance
Returns
A wrapper Callback
Build Callbacks for class method members which take varying numbers of arguments and potentially returning a value.
Definition at line 1650 of file callback.h.
MakeCallback() [6/11]
template<typename T , typename OBJ , typename R , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > Callback< R, T1, T2, T3, T4, T5 > ns3::MakeCallback (R(T::*)(T1, T2, T3, T4, T5) memPtr, OBJ objPtr)
Parameters
[in] memPtr Class method member pointer
[in] objPtr Class instance
Returns
A wrapper Callback
Build Callbacks for class method members which take varying numbers of arguments and potentially returning a value.
Definition at line 1660 of file callback.h.
MakeCallback() [7/11]
template<typename T , typename OBJ , typename R , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 > Callback< R, T1, T2, T3, T4, T5, T6 > ns3::MakeCallback (R(T::*)(T1, T2, T3, T4, T5, T6) memPtr, OBJ objPtr)
Parameters
[in] memPtr Class method member pointer
[in] objPtr Class instance
Returns
A wrapper Callback
Build Callbacks for class method members which take varying numbers of arguments and potentially returning a value.
Definition at line 1670 of file callback.h.
MakeCallback() [8/11]
template<typename T , typename OBJ , typename R , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 > Callback< R, T1, T2, T3, T4, T5, T6, T7 > ns3::MakeCallback (R(T::*)(T1, T2, T3, T4, T5, T6, T7) memPtr, OBJ objPtr)
Parameters
[in] memPtr Class method member pointer
[in] objPtr Class instance
Returns
A wrapper Callback
Build Callbacks for class method members which take varying numbers of arguments and potentially returning a value.
Definition at line 1680 of file callback.h.
MakeCallback() [9/11]
template<typename T , typename OBJ , typename R , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 > Callback< R, T1, T2, T3, T4, T5, T6, T7, T8 > ns3::MakeCallback (R(T::*)(T1, T2, T3, T4, T5, T6, T7, T8) memPtr, OBJ objPtr)
Parameters
[in] memPtr Class method member pointer
[in] objPtr Class instance
Returns
A wrapper Callback
Build Callbacks for class method members which take varying numbers of arguments and potentially returning a value.
Definition at line 1690 of file callback.h.
MakeCallback() [10/11]
template<typename T , typename OBJ , typename R , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 > Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 > ns3::MakeCallback (R(T::*)(T1, T2, T3, T4, T5, T6, T7, T8, T9) memPtr, OBJ objPtr)
Parameters
[in] memPtr Class method member pointer
[in] objPtr Class instance
Returns
A wrapper Callback
Build Callbacks for class method members which take varying numbers of arguments and potentially returning a value.
Definition at line 1700 of file callback.h.
MakeCallback() [11/11]
template<typename T , typename OBJ , typename R > Callback<R> ns3::MakeCallback (R(T::*)(void) memPtr, OBJ objPtr)
Parameters
[in] memPtr Class method member pointer
[in] objPtr Class instance
Returns
A wrapper Callback
Build Callbacks for class method members which take varying numbers of arguments and potentially returning a value.
Definition at line 1610 of file callback.h.
Referenced by ns3::ApWifiMac::ApWifiMac(), ns3::BlockAckManager::BlockAckManager(), ns3::dsr::DsrRouteCache::DsrRouteCache(), ns3::EpcEnbApplication::EpcEnbApplication(), ns3::EpcPgwApplication::EpcPgwApplication(), ns3::EpcSgwApplication::EpcSgwApplication(), ns3::Ipv4FlowProbe::Ipv4FlowProbe(), ns3::Ipv6FlowProbe::Ipv6FlowProbe(), ns3::lorawan::LoraRadioEnergyModel::LoraRadioEnergyModel(), ns3::aodv::Neighbors::Neighbors(), ns3::NoBackhaulEpcHelper::NoBackhaulEpcHelper(), ns3::PyViz::PyViz(), ns3::QosTxop::QosTxop(), ns3::RegularWifiMac::RegularWifiMac(), ns3::aodv::RoutingProtocol::RoutingProtocol(), TcpRateLinuxWithBufferTest::TcpRateLinuxWithBufferTest(), ns3::TcpSocketBase::TcpSocketBase(), Tunnel::Tunnel(), ns3::WifiRadioEnergyModel::WifiRadioEnergyModel(), ns3::BridgeNetDevice::AddBridgePort(), ns3::Node::AddDevice(), ns3::Ipv4L3Protocol::AddInterface(), ns3::Ipv6L3Protocol::AddInterface(), ns3::MeshPointDevice::AddInterface(), ns3::QueueDisc::AddInternalQueue(), ns3::EpcSgwApplication::AddMme(), ns3::QueueDisc::AddQueueDiscClass(), ns3::EpcEnbApplication::AddS1Interface(), ns3::EpcMmeApplication::AddSgw(), ns3::EpcX2::AddX2Interface(), ns3::UanMacAloha::AttachPhy(), ns3::UanMacCw::AttachPhy(), ns3::UanMacRcGw::AttachPhy(), ns3::UanMacRc::AttachPhy(), TcpBytesInFlightTest::BeforeRTOExpired(), CallbackTestClass::CheckParentalRights(), ns3::aodv::AodvRqueueTest::CheckSizeLimit(), ns3::PacketSocket::Close(), ns3::LrWpanNetDevice::CompleteConfig(), ns3::QosTxop::CompleteConfig(), ns3::WifiNetDevice::CompleteConfig(), ns3::NscTcpSocketImpl::CompleteFork(), VanetRoutingExperiment::ConfigureApplications(), VanetRoutingExperiment::ConfigureDevices(), ns3::ApplicationPacketProbe::ConnectByObject(), ns3::Ipv4PacketProbe::ConnectByObject(), ns3::Ipv6PacketProbe::ConnectByObject(), ns3::PacketProbe::ConnectByObject(), ns3::BooleanProbe::ConnectByObject(), ns3::DoubleProbe::ConnectByObject(), ns3::TimeProbe::ConnectByObject(), ns3::Uinteger16Probe::ConnectByObject(), ns3::Uinteger32Probe::ConnectByObject(), ns3::Uinteger8Probe::ConnectByObject(), ns3::ApplicationPacketProbe::ConnectByPath(), ns3::Ipv4PacketProbe::ConnectByPath(), ns3::Ipv6PacketProbe::ConnectByPath(), ns3::PacketProbe::ConnectByPath(), ns3::BooleanProbe::ConnectByPath(), ns3::DoubleProbe::ConnectByPath(), ns3::TimeProbe::ConnectByPath(), ns3::Uinteger16Probe::ConnectByPath(), ns3::Uinteger32Probe::ConnectByPath(), ns3::Uinteger8Probe::ConnectByPath(), ns3::AnimationInterface::ConnectCallbacks(), ns3::ThreeGppHttpClient::ConnectionSucceededCallback(), ns3::AnimationInterface::ConnectLteEnb(), ns3::AnimationInterface::ConnectLteUe(), ns3::FileHelper::ConnectProbeToAggregator(), ns3::GnuplotHelper::ConnectProbeToAggregator(), ns3::NetDeviceQueue::ConnectQueueTraces(), TestCounter::ConnectTraces(), ns3::ConstantObssPdAlgorithm::ConnectWifiNetDevice(), ns3::DsrHelper::Create(), ns3::ArpL3Protocol::CreateCache(), ns3::Icmpv6L4Protocol::CreateCache(), Bug772ChainTest::CreateDevices(), ns3::olsr::Bug780Test::CreateNodes(), ns3::olsr::HelloRegressionTest::CreateNodes(), ns3::olsr::TcRegressionTest::CreateNodes(), TcpBytesInFlightTest::CreateReceiverErrorModel(), ns3::TcpCloseWithLossTestCase::CreateReceiverErrorModel(), TcpFastRetrTest::CreateReceiverErrorModel(), TcpRateLinuxWithSocketsTest::CreateReceiverErrorModel(), TcpSsThreshRtoTest::CreateReceiverErrorModel(), TcpTimeRtoTest::CreateReceiverErrorModel(), TcpAdvertisedWindowTest::CreateReceiverSocket(), TcpAdvWindowOnLossTest::CreateReceiverSocket(), TcpPktsAckedOpenTest::CreateSenderSocket(), ThreeGppHttpObjectTestCase::CreateSimpleInternetNode(), WaveNetDeviceExample::CreateWaveNodes(), BasicEnergyDepletionTest::DepletionTestCase(), CoDelQueueDiscBasicDrop::Dequeue(), ns3::PacketSocket::DoBind(), ns3::Rip::DoInitialize(), ns3::RipNg::DoInitialize(), ns3::olsr::RoutingProtocol::DoInitialize(), ns3::VsaManager::DoInitialize(), ns3::WaveNetDevice::DoInitialize(), ns3::AcousticModemEnergyModelHelper::DoInstall(), ns3::WifiRadioEnergyModelHelper::DoInstall(), UanTest::DoOnePhyTest(), ns3::aodv::NeighborTest::DoRun(), ns3::aodv::QueueEntryTest::DoRun(), ns3::aodv::AodvRqueueTest::DoRun(), ns3::aodv::LoopbackTestCase::DoRun(), ThreeGppHttpObjectTestCase::DoRun(), TcpEndPointBug2211Test::DoRun(), LteCellSelectionTestCase::DoRun(), LteRadioLinkFailureTestCase::DoRun(), LteSecondaryCellSelectionTestCase::DoRun(), LteUeMeasurementsPiecewiseTestCase1::DoRun(), LteUeMeasurementsPiecewiseTestCase2::DoRun(), LteUeMeasurementsHandoverTestCase::DoRun(), LteHandoverTargetTestCase::DoRun(), Ns2MobilityHelperTest::DoRun(), IntegerTraceSourceTestCase::DoRun(), TracedCallbackTestCase::DoRun(), CallbackValueTestCase::DoRun(), MakeCallbackTestCase::DoRun(), NullifyCallbackTestCase::DoRun(), MakeCallbackTemplatesTestCase::DoRun(), ns3::tests::ObjectVectorTraceConfigTestCase::DoRun(), BasicTracedCallbackTestCase::DoRun(), DhcpTestCase::DoRun(), IcmpEchoReplyTestCase::DoRun(), IcmpTimeExceedTestCase::DoRun(), IcmpV6EchoReplyTestCase::DoRun(), IcmpV6TimeExceedTestCase::DoRun(), Ipv4DeduplicationTest::DoRun(), Ipv4ForwardingTest::DoRun(), Ipv4DynamicGlobalRoutingTestCase::DoRun(), Ipv4GlobalRoutingSlash32TestCase::DoRun(), Ipv4HeaderTest::DoRun(), Ipv4PacketInfoTagTest::DoRun(), Ipv4RawSocketImplTest::DoRun(), Ipv4RipTest::DoRun(), Ipv4RipCountToInfinityTest::DoRun(), Ipv4RipSplitHorizonStrategyTest::DoRun(), Ipv4StaticRoutingSlash32TestCase::DoRun(), DualStackTestCase::DoRun(), Ipv6ForwardingTest::DoRun(), Ipv6PacketInfoTagTest::DoRun(), Ipv6RawSocketImplTest::DoRun(), Ipv6RipngTest::DoRun(), Ipv6RipngCountToInfinityTest::DoRun(), Ipv6RipngSplitHorizonStrategyTest::DoRun(), ns3::TcpGeneralTest::DoRun(), TcpHyblaIncrementTest::DoRun(), UdpSocketLoopbackTest::DoRun(), Udp6SocketLoopbackTest::DoRun(), UdpSocketImplTest::DoRun(), Udp6SocketImplTest::DoRun(), UplinkPacketTest::DoRun(), DownlinkPacketTest::DoRun(), LinkCheckTest::DoRun(), LrWpanCollisionTestCase::DoRun(), LrWpanEdTestCase::DoRun(), LrWpanErrorDistanceTestCase::DoRun(), LrWpanPlmeAndPdInterfaceTestCase::DoRun(), CarrierAggregationConfigTestCase::DoRun(), LteDownlinkPowerControlTestCase::DoRun(), LteDownlinkDataSinrTestCase::DoRun(), LteDownlinkCtrlSinrTestCase::DoRun(), LteInterferenceHardFrTestCase::DoRun(), LteInterferenceStrictFrTestCase::DoRun(), LteInterferenceTestCase::DoRun(), LteIpv6RoutingTestCase::DoRun(), LteLinkAdaptationTestCase::DoRun(), LtePathlossModelSystemTestCase::DoRun(), LteRlcAmE2eTestCase::DoRun(), LteRlcUmE2eTestCase::DoRun(), LteUplinkDataSinrTestCase::DoRun(), LteUplinkSrsSinrTestCase::DoRun(), LteEnbAntennaTestCase::DoRun(), LteHandoverDelayTestCase::DoRun(), LteRrcConnectionEstablishmentTestCase::DoRun(), LteRrcConnectionEstablishmentErrorTestCase::DoRun(), WaypointMobilityModelNotifyTest::DoRun(), WaypointMobilityModelAddWaypointTest::DoRun(), ErrorModelSimple::DoRun(), BurstErrorModelSimple::DoRun(), PacketSocketAppsTest::DoRun(), SequenceNumberTestCase::DoRun(), SixlowpanHc1ImplTest::DoRun(), SixlowpanIphcImplTest::DoRun(), SpectrumIdealPhyTestCase::DoRun(), WaveformGeneratorTestCase::DoRun(), ProbeTestCase1::DoRun(), CsmaBridgeTestCase::DoRun(), CsmaBroadcastTestCase::DoRun(), CsmaMulticastTestCase::DoRun(), CsmaOneSubnetTestCase::DoRun(), CsmaPacketSocketTestCase::DoRun(), CsmaPingTestCase::DoRun(), CsmaRawIpSocketTestCase::DoRun(), CsmaStarTestCase::DoRun(), Ns3TcpCwndTestCase1::DoRun(), Ns3TcpCwndTestCase2::DoRun(), Ns3TcpInteroperabilityTestCase::DoRun(), Ns3TcpLossTestCase::DoRun(), Ns3TcpNoDelayTestCase::DoRun(), Ns3TcpSocketTestCase1::DoRun(), Ns3TcpSocketTestCase2::DoRun(), Ns3TcpStateTestCase::DoRun(), NscTcpLossTestCase1::DoRun(), NscTcpLossTestCase2::DoRun(), AcousticModemEnergyTestCase::DoRun(), AcousticModemEnergyDepletionTestCase::DoRun(), ChannelAccessTestCase::DoRun(), AnnexC_TestCase::DoRun(), BlockAckAggregationDisabledTest::DoRun(), PreservePacketsInAmpdus::DoRun(), DcfImmediateAccessBroadcastTestCase::DoRun(), Bug730TestCase::DoRun(), QosFragmentationTestCase::DoRun(), Bug2222TestCase::DoRun(), Bug2843TestCase::DoRun(), Bug2831TestCase::DoRun(), Issue169TestCase::DoRun(), SpectrumWifiPhyBasicTest::DoSetup(), TestThresholdPreambleDetectionWithoutFrameCapture::DoSetup(), TestThresholdPreambleDetectionWithFrameCapture::DoSetup(), TestSimpleFrameCaptureModel::DoSetup(), TestAmpduReception::DoSetup(), WifiPhyThresholdsTest::DoSetup(), ns3::AthstatsHelper::EnableAthstats(), ns3::OcbWifiMac::EnableForWave(), ns3::InternetStackHelper::EnablePcapIpv4Internal(), ns3::InternetStackHelper::EnablePcapIpv6Internal(), ns3::NscTcpSocketImpl::FinishBind(), ns3::UdpSocketImpl::FinishBind(), ns3::MeshPointDevice::Forward(), TcpEndPointBug2211Test::HandleAccept(), ns3::PacketSink::HandleAccept(), ns3::TcpGeneralTest::HandleAccept(), ns3::dot11s::PeerManagementProtocol::InitiateLink(), ns3::lorawan::LoraHelper::Install(), ns3::AdhocAlohaNoackIdealPhyHelper::Install(), ns3::dot11s::HwmpProtocol::Install(), ns3::PointToPointHelper::Install(), HwmpProactiveRegressionTest::InstallApplications(), HwmpReactiveRegressionTest::InstallApplications(), HwmpSimplestRegressionTest::InstallApplications(), HwmpDoRfRegressionTest::InstallApplications(), FlameRegressionTest::InstallApplications(), ns3::lorawan::NetworkServerHelper::InstallPriv(), ns3::lorawan::ForwarderHelper::InstallPriv(), ns3::LteHelper::InstallSingleEnbDevice(), ns3::LteSimpleHelper::InstallSingleEnbDevice(), ns3::LteHelper::InstallSingleUeDevice(), ns3::LteSimpleHelper::InstallSingleUeDevice(), ns3::Dot11sStack::InstallStack(), TracedValueCallbackTestCase::CheckTvCb< T >::Invoke(), TracedCallbackTypedefTestCase::Checker< T1, T2, T3, T4, T5 >::Invoke(), TracedCallbackTypedefTestCase::Checker< T1, T2, T3, T4, empty >::Invoke(), TracedCallbackTypedefTestCase::Checker< T1, T2, T3, empty, empty >::Invoke(), TracedCallbackTypedefTestCase::Checker< T1, T2, empty, empty, empty >::Invoke(), TracedCallbackTypedefTestCase::Checker< T1, empty, empty, empty, empty >::Invoke(), ns3::DhcpClient::LinkStateHandler(), ns3::ThreeGppHttpServer::NewConnectionCreatedCallback(), ns3::aodv::RoutingProtocol::NotifyAddAddress(), ns3::dsdv::RoutingProtocol::NotifyAddAddress(), ns3::aodv::RoutingProtocol::NotifyInterfaceUp(), ns3::dsdv::RoutingProtocol::NotifyInterfaceUp(), ns3::Rip::NotifyInterfaceUp(), ns3::RipNg::NotifyInterfaceUp(), ns3::dsr::DsrRouting::NotifyNewAggregate(), ns3::Icmpv4L4Protocol::NotifyNewAggregate(), ns3::Icmpv6L4Protocol::NotifyNewAggregate(), ns3::NscTcpL4Protocol::NotifyNewAggregate(), ns3::TcpL4Protocol::NotifyNewAggregate(), ns3::UdpL4Protocol::NotifyNewAggregate(), ns3::aodv::RoutingProtocol::NotifyRemoveAddress(), ns3::dsdv::RoutingProtocol::NotifyRemoveAddress(), ns3::ThreeGppHttpClient::OpenConnection(), OcbWifiMacTestCase::PostDeviceConfiguration(), PrintTraffic(), ns3::TcpSocketBase::ProcessOptionSack(), ns3::Ipv4L3Protocol::Receive(), ns3::Ipv6L3Protocol::Receive(), ns3::TcpSocketBase::ReceivedAck(), ns3::PyViz::RegisterCsmaLikeDevice(), ns3::PyViz::RegisterDropTracePath(), ns3::PyViz::RegisterPointToPointLikeDevice(), ns3::Node::RegisterProtocolHandler(), ns3::PyViz::RegisterWifiLikeDevice(), PhyConnectivityTest::Reset(), ReceivePathTest::Reset(), ns3::MacLow::ResetPhy(), InterferenceExperiment::Run(), NetAnimExperiment::Run(), Experiment::Run(), TestInterBssConstantObssPdAlgo::RunOne(), Issue40TestCase::RunOne(), Bug2470TestCase::RunSubtest(), ns3::TrafficControlLayer::ScanDevices(), ns3::MeshPointDevice::Send(), ns3::MeshPointDevice::SendFrom(), TcpTestCase::ServerHandleConnectionCreated(), ns3::TapBridge::SetBridgedNetDevice(), ns3::HierarchicalMobilityModel::SetChild(), ns3::UanNetDevice::SetMac(), ns3::SixLowPanNetDevice::SetNetDevice(), ns3::dot11s::PeerManagementProtocolMac::SetParent(), ns3::HierarchicalMobilityModel::SetParent(), ns3::MacLow::SetPhy(), ns3::lorawan::LorawanMac::SetPhy(), ns3::WimaxNetDevice::SetReceiveCallback(), ns3::Txop::SetTxDroppedCallback(), StaWifiMacScanningTestCase::Setup(), UanExperiment::SetupApplications(), ns3::TcpSocketBase::SetupCallback(), TcpTestCase::SetupDefaultSim(), TcpTestCase::SetupDefaultSim6(), ns3::RegularWifiMac::SetupEdcaQueue(), ns3::Ipv6L3Protocol::SetupLoopback(), ns3::Ipv4L3Protocol::SetupLoopback(), RoutingExperiment::SetupPacketReceive(), DsdvManetExample::SetupPacketReceive(), Experiment::SetupPacketReceive(), SetupPacketReceive(), RoutingHelper::SetupRoutingPacketReceive(), ns3::StaWifiMac::SetWifiPhy(), ns3::dsdv::RoutingProtocol::Start(), ns3::dsr::DsrRouting::Start(), ns3::FdReader::Start(), ns3::ThreeGppHttpServer::StartApplication(), ns3::Ping6::StartApplication(), ns3::Radvd::StartApplication(), Receiver::StartApplication(), ns3::BulkSendApplication::StartApplication(), ns3::OnOffApplication::StartApplication(), ns3::PacketSink::StartApplication(), ns3::UdpEchoClient::StartApplication(), ns3::UdpEchoServer::StartApplication(), ns3::UdpServer::StartApplication(), ns3::DhcpClient::StartApplication(), ns3::DhcpServer::StartApplication(), ns3::V4Ping::StartApplication(), ns3::V4TraceRoute::StartApplication(), ns3::PacketSocketServer::StartApplication(), ns3::BsmApplication::StartApplication(), Ipv4FragmentationTest::StartClient(), Ipv6FragmentationTest::StartClient(), SixlowpanFragmentationTest::StartClient(), ns3::FdNetDevice::StartDevice(), Ns3TcpLossTestCase::StartFlow(), Ns3TcpStateTestCase::StartFlow(), StartFlow(), ns3::SSLinkManager::StartScanning(), Ipv4FragmentationTest::StartServer(), Ipv6FragmentationTest::StartServer(), SixlowpanFragmentationTest::StartServer(), ns3::TapBridge::StartTapDevice(), TcpRateLinuxWithBufferTest::TestWithSackBlocks(), TraceCwnd(), TraceInFlight(), TraceNextRx(), TraceNextTx(), TraceRto(), TraceRtt(), TraceSsThresh(), and WifiInterferenceTestCase::WifiSimpleInterference().