ns-3: MakeEvent from Function Pointers.
MakeEvent from Function Pointers.
Core » Scheduler and Events » Events
Create EventImpl instances from function pointers which take varying numbers of arguments.
Functions
template<typename U1 , typename T1 >
EventImpl * ns3::MakeEvent (void(*f)(U1), T1 a1)
Make an EventImpl from a function pointer taking varying numbers of arguments.
template<typename U1 , typename U2 , typename T1 , typename T2 >
EventImpl * ns3::MakeEvent (void(*f)(U1, U2), T1 a1, T2 a2)
Make an EventImpl from a function pointer taking varying numbers of arguments.
template<typename U1 , typename U2 , typename U3 , typename T1 , typename T2 , typename T3 >
EventImpl * ns3::MakeEvent (void(*f)(U1, U2, U3), T1 a1, T2 a2, T3 a3)
Make an EventImpl from a function pointer taking varying numbers of arguments.
template<typename U1 , typename U2 , typename U3 , typename U4 , typename T1 , typename T2 , typename T3 , typename T4 >
EventImpl * ns3::MakeEvent (void(*f)(U1, U2, U3, U4), T1 a1, T2 a2, T3 a3, T4 a4)
Make an EventImpl from a function pointer taking varying numbers of arguments.
template<typename U1 , typename U2 , typename U3 , typename U4 , typename U5 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
EventImpl * ns3::MakeEvent (void(*f)(U1, U2, U3, U4, U5), T1 a1, T2 a2, T3 a3, T4 a4, T5 a5)
Make an EventImpl from a function pointer taking varying numbers of arguments.
template<typename U1 , typename U2 , typename U3 , typename U4 , typename U5 , typename U6 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 >
EventImpl * ns3::MakeEvent (void(*f)(U1, U2, U3, U4, U5, U6), T1 a1, T2 a2, T3 a3, T4 a4, T5 a5, T6 a6)
Make an EventImpl from a function pointer taking varying numbers of arguments.
EventImpl * ns3::MakeEvent (void(*f)(void))
Make an EventImpl from a function pointer taking varying numbers of arguments.
Detailed Description
Create EventImpl instances from function pointers which take varying numbers of arguments.
Function Documentation
MakeEvent() [1/7]
template<typename U1 , typename T1 > EventImpl * ns3::MakeEvent (void(*)(U1) f, T1 a1)
Make an EventImpl from a function pointer taking varying numbers of arguments.
Template Parameters
U1 [deduced] Formal type of the argument to the function.
T1 [deduced] Actual type of the argument to the function.
Parameters
[in] f The function pointer.
[in] a1 Argument to be bound to the function.
Returns
The constructed EventImpl.
Definition at line 599 of file make-event.h.
MakeEvent() [2/7]
template<typename U1 , typename U2 , typename T1 , typename T2 > EventImpl * ns3::MakeEvent (void(*)(U1, U2) f, T1 a1, T2 a2)
Make an EventImpl from a function pointer taking varying numbers of arguments.
Template Parameters
U1 [deduced] Formal type of the first argument to the function.
U2 [deduced] Formal type of the second argument to the function.
T1 [deduced] Actual type of the first argument to the function.
T2 [deduced] Actual type of the second argument to the function.
Parameters
[in] f The function pointer.
[in] a1 First argument to be bound to the function.
[in] a2 Second argument to be bound to the function.
Returns
The constructed EventImpl.
Definition at line 628 of file make-event.h.
MakeEvent() [3/7]
template<typename U1 , typename U2 , typename U3 , typename T1 , typename T2 , typename T3 > EventImpl * ns3::MakeEvent (void(*)(U1, U2, U3) f, T1 a1, T2 a2, T3 a3)
Make an EventImpl from a function pointer taking varying numbers of arguments.
Template Parameters
U1 [deduced] Formal type of the first argument to the function.
U2 [deduced] Formal type of the second argument to the function.
U3 [deduced] Formal type of the third argument to the function.
T1 [deduced] Actual type of the first argument to the function.
T2 [deduced] Actual type of the second argument to the function.
T3 [deduced] Actual type of the third argument to the function.
Parameters
[in] f The function pointer.
[in] a1 First argument to be bound to the function.
[in] a2 Second argument to be bound to the function.
[in] a3 Third argument to be bound to the function.
Returns
The constructed EventImpl.
Definition at line 660 of file make-event.h.
MakeEvent() [4/7]
template<typename U1 , typename U2 , typename U3 , typename U4 , typename T1 , typename T2 , typename T3 , typename T4 > EventImpl * ns3::MakeEvent (void(*)(U1, U2, U3, U4) f, T1 a1, T2 a2, T3 a3, T4 a4)
Make an EventImpl from a function pointer taking varying numbers of arguments.
Template Parameters
U1 [deduced] Formal type of the first argument to the function.
U2 [deduced] Formal type of the second argument to the function.
U3 [deduced] Formal type of the third argument to the function.
U4 [deduced] Formal type of the fourth argument to the function.
T1 [deduced] Actual type of the first argument to the function.
T2 [deduced] Actual type of the second argument to the function.
T3 [deduced] Actual type of the third argument to the function.
T4 [deduced] Actual type of the fourth argument to the function.
Parameters
[in] f The function pointer.
[in] a1 First argument to be bound to the function.
[in] a2 Second argument to be bound to the function.
[in] a3 Third argument to be bound to the function.
[in] a4 Fourth argument to be bound to the function.
Returns
The constructed EventImpl.
Definition at line 694 of file make-event.h.
MakeEvent() [5/7]
template<typename U1 , typename U2 , typename U3 , typename U4 , typename U5 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > EventImpl * ns3::MakeEvent (void(*)(U1, U2, U3, U4, U5) f, T1 a1, T2 a2, T3 a3, T4 a4, T5 a5)
Make an EventImpl from a function pointer taking varying numbers of arguments.
Template Parameters
U1 [deduced] Formal type of the first argument to the function.
U2 [deduced] Formal type of the second argument to the function.
U3 [deduced] Formal type of the third argument to the function.
U4 [deduced] Formal type of the fourth argument to the function.
U5 [deduced] Formal type of the fifth argument to the function.
T1 [deduced] Actual type of the first argument to the function.
T2 [deduced] Actual type of the second argument to the function.
T3 [deduced] Actual type of the third argument to the function.
T4 [deduced] Actual type of the fourth argument to the function.
T5 [deduced] Actual type of the fifth argument to the function.
Parameters
[in] f The function pointer.
[in] a1 First argument to be bound to the function.
[in] a2 Second argument to be bound to the function.
[in] a3 Third argument to be bound to the function.
[in] a4 Fourth argument to be bound to the function.
[in] a5 Fifth argument to be bound to the function.
Returns
The constructed EventImpl.
Definition at line 730 of file make-event.h.
MakeEvent() [6/7]
template<typename U1 , typename U2 , typename U3 , typename U4 , typename U5 , typename U6 , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 > EventImpl * ns3::MakeEvent (void(*)(U1, U2, U3, U4, U5, U6) f, T1 a1, T2 a2, T3 a3, T4 a4, T5 a5, T6 a6)
Make an EventImpl from a function pointer taking varying numbers of arguments.
Template Parameters
U1 Formal type of the first argument to the function.
U2 Formal type of the second argument to the function.
U3 Formal type of the third argument to the function.
U4 Formal type of the fourth argument to the function.
U5 Formal type of the fifth argument to the function.
U6 Formal type of the sixth argument to the function.
T1 Actual type of the first argument to the function.
T2 Actual type of the second argument to the function.
T3 Actual type of the third argument to the function.
T4 Actual type of the fourth argument to the function.
T5 Actual type of the fifth argument to the function.
T6 Actual type of the sixth argument to the function.
Parameters
f The function pointer.
a1 First argument to be bound to the function.
a2 Second argument to be bound to the function.
a3 Third argument to be bound to the function.
a4 Fourth argument to be bound to the function.
a5 Fifth argument to be bound to the function.
a6 Sixth argument to be bound to the function.
Returns
The constructed EventImpl.
Definition at line 768 of file make-event.h.
MakeEvent() [7/7]
EventImpl * ns3::MakeEvent (void(*)(void) f)
Make an EventImpl from a function pointer taking varying numbers of arguments.
Parameters
[in] f The function pointer.
Returns
The constructed EventImpl.
Definition at line 34 of file make-event.cc.
References f(), and NS_LOG_FUNCTION.
Referenced by ns3::TapBridge::ReadCallback(), ns3::FdNetDevice::ReceiveCallback(), ns3::Simulator::Schedule(), ns3::Simulator::ScheduleDestroy(), ns3::Simulator::ScheduleNow(), and ns3::Simulator::ScheduleWithContext().