ns-3: UAN Models
UAN Models
This section documents the API of the ns-3 UAN module. For a generic functional description, please refer to the ns-3 manual.
Modules
uan module tests
Files
file uan-animation.cc
file uan-cw-example.cc
Classes
struct ns3::UanMacRcGw::AckData
class ns3::AcousticModemEnergyModel
class ns3::AcousticModemEnergyModelHelper
class Experiment
Helper class for UAN CW MAC example.
struct ns3::UanMacRcGw::Request
class ns3::Tap
class ns3::UanChannel
class ns3::UanHeaderCommon
class ns3::UanHeaderRcAck
class ns3::UanHeaderRcCts
class ns3::UanHeaderRcCtsGlobal
class ns3::UanHeaderRcData
class ns3::UanHeaderRcRts
class ns3::UanHelper
class ns3::UanMac
class ns3::UanMacAloha
class ns3::UanMacCw
class ns3::UanMacRc
class ns3::UanMacRcGw
class ns3::UanModesList
class ns3::UanNetDevice
class ns3::UanNoiseModel
class ns3::UanNoiseModelDefault
class ns3::UanPacketArrival
class ns3::UanPdp
class ns3::UanPhy
class ns3::UanPhyCalcSinr
class ns3::UanPhyCalcSinrDefault
class ns3::UanPhyCalcSinrFhFsk
class ns3::UanPhyDual
class ns3::UanPhyGen
class ns3::UanPhyListener
class ns3::UanPhyPer
class ns3::UanPhyPerCommonModes
class ns3::UanPhyPerGenDefault
class ns3::UanPhyPerUmodem
class ns3::UanPropModel
class ns3::UanPropModelIdeal
class ns3::UanPropModelThorp
class ns3::UanTransducer
class ns3::UanTransducerHd
class ns3::UanTxMode
class ns3::UanTxModeFactory
struct ns3::UanTxModeFactory::UanTxModeItem
Functions
std::ostream & ns3::operator<< (std::ostream &os, const UanPdp &pdp)
std::istream & ns3::operator>> (std::istream &is, UanPdp &pdp)
Detailed Description
This section documents the API of the ns-3 UAN module. For a generic functional description, please refer to the ns-3 manual.
Function Documentation
operator<<()
std::ostream & ns3::operator<< (std::ostream & os, const UanPdp & pdp)
Writes PDP to stream as list of arrivals
Parameters
os The output stream.
pdp The PDP.
Returns
The output stream.
Definition at line 29 of file uan-prop-model.cc.
References ns3::UanPdp::GetNTaps(), ns3::UanPdp::GetResolution(), ns3::Time::GetSeconds(), and ns3::UanPdp::m_taps.
operator>>()
std::istream & ns3::operator>> (std::istream & is, UanPdp & pdp)
Reads in list of arrivals from stream is
Parameters
is The input stream.
pdp The PDP variable to set.
Returns
The input stream.
Definition at line 44 of file uan-prop-model.cc.
References ns3::UanPdp::m_resolution, ns3::UanPdp::m_taps, NS_FATAL_ERROR, and ns3::Seconds().