ns-3: LTE Models
LTE Models
Modules
FF MAC Schedulers
lte module tests
Classes
class ns3::BsrLteControlMessage
class ns3::CcHelper
class ns3::ComponentCarrier
class ns3::ComponentCarrierBaseStation
class ns3::ComponentCarrierEnb
class ns3::ComponentCarrierUe
class ns3::DlCqiLteControlMessage
class ns3::DlDciLteControlMessage
class ns3::DlHarqFeedbackLteControlMessage
class ns3::DownlinkLteGlobalPathlossDatabase
class ns3::DrbActivator
class ns3::EmuEpcHelper
Create an EPC network using EmuFdNetDevice.
class ns3::EpcEnbApplication
class ns3::EpcHelper
Base helper class to handle the creation of the EPC entities.
class ns3::EpcMmeApplication
class ns3::EpcPgwApplication
class ns3::EpcS11SapMme
class ns3::EpcS11SapSgw
class ns3::EpcS1apSap
class ns3::EpcS1apSapEnb
class ns3::EpcS1apSapMme
class ns3::EpcSgwApplication
class ns3::EpcX2
class ns3::GtpcHeader
Header of the GTPv2-C protocol.
class ns3::GtpuHeader
class LteAggregationThroughputScaleTestCase
Testing that UE throughput scales linearly with number of component carriers. Also attaches UE to last component carrier to make sure no code assumes that primary carrier is first.
class ns3::LteAmc
class ns3::LteCcmMacSapProvider
Service Access Point (SAP) offered by the component carrier manager (CCM) by MAC to CCM.
class ns3::LteCcmMacSapUser
Service Access Point (SAP) offered by MAC to the component carrier manager (CCM).
class LteCellSelectionTestCase
Testing the initial cell selection procedure by UE at IDLE state in the beginning of simulation.
class ns3::LteControlMessage
class ns3::LteEnbNetDevice
class ns3::LteEnbPhy
class ns3::LteEnbRrc
class ns3::LteGlobalPathlossDatabase
class ns3::LteHarqPhy
The LteHarqPhy class implements the HARQ functionalities related to PHY layer (i.e., decodification buffers for incremental redundancy management)
class ns3::LteHelper
class ns3::LteHexGridEnbTopologyHelper
class ns3::LteNetDevice
class ns3::LtePdcpHeader
The packet header for the Packet Data Convergence Protocol (PDCP) packets.
class ns3::LtePhy
class LteRadioLinkFailureTestCase
Testing the cell reselection procedure by UE at IDLE state.
class ns3::LteRlcAmHeader
The packet header for the AM Radio Link Control (RLC) protocol packets.
class ns3::LteRlcHeader
The packet header for the Radio Link Control (RLC) protocol packets.
class ns3::LteRrcSap
Class holding definition common to all UE/eNodeB SAP Users/Providers.
class LteSecondaryCellSelectionTestCase
Testing the initial cell selection procedure by UE at IDLE state in the beginning of simulation with multiple component carriers.
class ns3::LteSimpleNetDevice
class ns3::LteSimpleSpectrumPhy
class ns3::LteSpectrumPhy
struct ns3::LteSpectrumSignalParameters
struct ns3::LteSpectrumSignalParametersDataFrame
struct ns3::LteSpectrumSignalParametersDlCtrlFrame
struct ns3::LteSpectrumSignalParametersUlSrsFrame
class ns3::LteSpectrumValueHelper
This class defines all functions to create spectrum model for lte.
class ns3::LteStatsCalculator
class ns3::LteUeNetDevice
class ns3::LteUePhy
class ns3::LteUeRrcProtocolIdeal
class ns3::LteUeRrcProtocolReal
class ns3::MacStatsCalculator
class ns3::MibLteControlMessage
Abstract model for broadcasting the Master Information Block (MIB) within the control channel (BCCH).
class ns3::NoBackhaulEpcHelper
Create an EPC network with PointToPoint links between the core network nodes.
class ns3::PhyRxStatsCalculator
class ns3::PhyStatsCalculator
class ns3::PhyTxStatsCalculator
class ns3::PointToPointEpcHelper
Create an EPC network with PointToPoint links in the backhaul network.
class ns3::RachPreambleLteControlMessage
class ns3::RadioBearerStatsCalculator
class ns3::RadioBearerStatsConnector
class ns3::RadioEnvironmentMapHelper
class ns3::RarLteControlMessage
class ns3::RrcAsn1Header
This class extends Asn1Header functions, adding serialization/deserialization of some Information elements defined in 3GPP TS 36.331.
class ns3::Sib1LteControlMessage
Abstract model for broadcasting the System Information Block Type 1 (SIB1) within the control channel (BCCH).
class ns3::UeManager
class ns3::UlDciLteControlMessage
class ns3::UplinkLteGlobalPathlossDatabase
Variables
static const Time ns3::RRC_IDEAL_MSG_DELAY = MilliSeconds (0)
RRC ideal message delay.
Detailed Description
Variable Documentation
RRC_IDEAL_MSG_DELAY
const Time ns3::RRC_IDEAL_MSG_DELAY = MilliSeconds (0) static
RRC ideal message delay.
Definition at line 44 of file lte-rrc-protocol-ideal.cc.
Referenced by ns3::LteUeRrcProtocolIdeal::DoSendIdealUeContextRemoveRequest(), ns3::LteUeRrcProtocolIdeal::DoSendMeasurementReport(), ns3::LteEnbRrcProtocolIdeal::DoSendRrcConnectionReconfiguration(), ns3::LteUeRrcProtocolIdeal::DoSendRrcConnectionReconfigurationCompleted(), ns3::LteEnbRrcProtocolIdeal::DoSendRrcConnectionReestablishment(), ns3::LteUeRrcProtocolIdeal::DoSendRrcConnectionReestablishmentComplete(), ns3::LteEnbRrcProtocolIdeal::DoSendRrcConnectionReestablishmentReject(), ns3::LteUeRrcProtocolIdeal::DoSendRrcConnectionReestablishmentRequest(), ns3::LteEnbRrcProtocolIdeal::DoSendRrcConnectionReject(), ns3::LteEnbRrcProtocolIdeal::DoSendRrcConnectionRelease(), ns3::LteUeRrcProtocolIdeal::DoSendRrcConnectionRequest(), ns3::LteEnbRrcProtocolIdeal::DoSendRrcConnectionSetup(), ns3::LteUeRrcProtocolIdeal::DoSendRrcConnectionSetupCompleted(), and ns3::LteEnbRrcProtocolIdeal::DoSendSystemInformation().