ns-3: Virtual Time
Virtual Time
Core
Management of virtual time in real world units.
Modules
Standard Time Units.
Convenience constructors in standard units.
Files
file nstime.h
file time-printer.cc
file time-printer.h
file time.cc
Classes
class ns3::Time
Simulation virtual time values and global simulation resolution.
class ns3::TimeWithUnit
A Time with attached unit, to facilitate output in that unit.
Functions
Time ns3::TimeStep (uint64_t ts)
bool ns3::operator== (const Time &lhs, const Time &rhs)
Equality operator for Time.
bool ns3::operator!= (const Time &lhs, const Time &rhs)
Inequality operator for Time.
bool ns3::operator<= (const Time &lhs, const Time &rhs)
Less than or equal operator for Time.
bool ns3::operator>= (const Time &lhs, const Time &rhs)
Greater than or equal operator for Time.
bool ns3::operator< (const Time &lhs, const Time &rhs)
Less than operator for Time.
bool ns3::operator> (const Time &lhs, const Time &rhs)
Greater than operator for Time.
Time ns3::operator+ (const Time &lhs, const Time &rhs)
Addition operator for Time.
Time ns3::operator- (const Time &lhs, const Time &rhs)
Difference operator for Time.
Time ns3::operator* (const Time &lhs, const int64_t &rhs)
Multiplication operator for Time.
Time ns3::operator* (const int64_t &lhs, const Time &rhs)
Multiplication operator for Time.
Time ns3::operator* (const Time &lhs, const int64x64_t &rhs)
Multiplication operator for Time.
Time ns3::operator* (const int64x64_t &lhs, const Time &rhs)
Multiplication operator for Time.
int64x64_t ns3::operator/ (const Time &lhs, const Time &rhs)
Division operator for Time.
Time ns3::operator/ (const Time &lhs, const int64_t &rhs)
Division operator for Time.
Time ns3::operator/ (const Time &lhs, const int64x64_t &rhs)
Division operator for Time.
Time & ns3::operator+= (Time &lhs, const Time &rhs)
Addition operator for Time.
Time & ns3::operator-= (Time &lhs, const Time &rhs)
Subtraction operator for Time.
std::ostream & ns3::operator<< (std::ostream &os, const Time &time)
Time output streamer.
std::istream & ns3::operator>> (std::istream &is, Time &time)
Time input streamer.
Time ns3::Abs (const Time &time)
Time ns3::Max (const Time &ta, const Time &tb)
Time ns3::Min (const Time &ta, const Time &tb)
Detailed Description
Management of virtual time in real world units.
The underlying simulator is unit agnostic, just dealing with dimensionless virtual time. Models usually need to handle time in real world units, such as seconds, and conversions/scaling between different units, between minutes and seconds, for example.
The convenience constructors in the Standard Units module make it easy to create Times in specific units.
The Time::SetResolution() function allows a one-time change of the base resolution, before Simulator::Run().
Function Documentation
Abs()
Time ns3::Abs (const Time & time) inline
Parameters
[in] time The input value
Returns
The absolute value of the input value.
Definition at line 976 of file nstime.h.
References ns3::Time::m_data.
Max()
Time ns3::Max (const Time & ta, const Time & tb) inline
Parameters
[in] ta The first value
[in] tb The seconds value
Returns
The max of the two input values.
Definition at line 980 of file nstime.h.
References ns3::Time::m_data.
Min()
Time ns3::Min (const Time & ta, const Time & tb) inline
Parameters
[in] ta The first value
[in] tb The seconds value
Returns
The min of the two input values.
Definition at line 984 of file nstime.h.
References ns3::Time::m_data.
operator!=()
bool ns3::operator!= (const Time & lhs, const Time & rhs) inline
Inequality operator for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
true if the two input values not are equal.
Definition at line 781 of file nstime.h.
References ns3::Time::m_data.
operator*() [1/4]
Time ns3::operator* (const int64_t & lhs, const Time & rhs) inline
Multiplication operator for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
the product of the two input values.
Definition at line 877 of file nstime.h.
References ns3::Time::m_data.
operator*() [2/4]
Time ns3::operator* (const int64x64_t & lhs, const Time & rhs) inline
Multiplication operator for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
the product of the two input values.
Definition at line 905 of file nstime.h.
operator*() [3/4]
Time ns3::operator* (const Time & lhs, const int64_t & rhs) inline
Multiplication operator for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
the product of the two input values.
Definition at line 863 of file nstime.h.
References ns3::Time::m_data.
operator*() [4/4]
Time ns3::operator* (const Time & lhs, const int64x64_t & rhs) inline
Multiplication operator for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
the product of the two input values.
Definition at line 891 of file nstime.h.
References ns3::Time::m_data.
operator+()
Time ns3::operator+ (const Time & lhs, const Time & rhs) inline
Addition operator for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
the sum of the two input values.
Definition at line 840 of file nstime.h.
References ns3::Time::m_data.
operator+=()
Time& ns3::operator+= (Time & lhs, const Time & rhs) inline
Addition operator for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
the result of the first input value plus the second input value.
Definition at line 958 of file nstime.h.
References ns3::Time::m_data.
operator-()
Time ns3::operator- (const Time & lhs, const Time & rhs) inline
Difference operator for Time.
Parameters
[in] lhs The first value
[in] rhs The seconds value
Returns
the difference of the two input values.
Definition at line 851 of file nstime.h.
References ns3::Time::m_data.
operator-=()
Time& ns3::operator-= (Time & lhs, const Time & rhs) inline
Subtraction operator for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
the result of the first input value minus the second input value.
Definition at line 970 of file nstime.h.
References ns3::Time::m_data.
operator/() [1/3]
Time ns3::operator/ (const Time & lhs, const int64_t & rhs) inline
Division operator for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
the resultof the first input value divided by the second input value.
Definition at line 931 of file nstime.h.
References ns3::Time::m_data.
operator/() [2/3]
Time ns3::operator/ (const Time & lhs, const int64x64_t & rhs) inline
Division operator for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
the resultof the first input value divided by the second input value.
Definition at line 945 of file nstime.h.
References ns3::Time::m_data.
operator/() [3/3]
int64x64_t ns3::operator/ (const Time & lhs, const Time & rhs) inline
Division operator for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
the resultof the first input value divided by the second input value.
Definition at line 917 of file nstime.h.
References ns3::Time::m_data.
operator<()
bool ns3::operator< (const Time & lhs, const Time & rhs) inline
Less than operator for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
true if the first input value is less than the second input value.
Definition at line 816 of file nstime.h.
References ns3::Time::m_data.
operator<<()
std::ostream & ns3::operator<< (std::ostream & os, const Time & time)
Time output streamer.
Generates output such as "3.96ns". Times are printed with the following format flags (independent of the stream flags):
showpos
fixed
left The stream width and precision are ignored; Time output always includes ".0".
Parameters
[in,out] os The output stream.
[in] time The Time to put on the stream.
Returns
The stream.
Definition at line 395 of file time.cc.
References ns3::Time::As(), and ns3::Time::GetResolution().
operator<=()
bool ns3::operator<= (const Time & lhs, const Time & rhs) inline
Less than or equal operator for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
true if the first input value is less than or equal to the second input value.
Definition at line 792 of file nstime.h.
References ns3::Time::m_data.
operator==()
bool ns3::operator== (const Time & lhs, const Time & rhs) inline
Equality operator for Time.
Arithmetic operator.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
true if the two input values are equal.
Definition at line 769 of file nstime.h.
References ns3::Time::m_data.
operator>()
bool ns3::operator> (const Time & lhs, const Time & rhs) inline
Greater than operator for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
true if the first input value is greater than the second input value.
Definition at line 829 of file nstime.h.
References ns3::Time::m_data.
operator>=()
bool ns3::operator>= (const Time & lhs, const Time & rhs) inline
Greater than or equal operator for Time.
Parameters
[in] lhs The first value
[in] rhs The second value
Returns
true if the first input value is greater than or equal to the second input value.
Definition at line 805 of file nstime.h.
References ns3::Time::m_data.
operator>>()
std::istream & ns3::operator>> (std::istream & is, Time & time)
Time input streamer.
Uses the Time::Time (const std::string &) constructor
Parameters
[in,out] is The input stream.
[out] time The Time variable to set from the stream data.
Returns
The stream.
Definition at line 438 of file time.cc.
TimeStep()
Time ns3::TimeStep (uint64_t ts) inline
Internal: Scheduler interface
Parameters
[in] ts The time value, in the current unit.
Returns
A Time.
Definition at line 1127 of file nstime.h.
Referenced by ns3::BuildingListPriv::Add(), ns3::NodeListPriv::Add(), ns3::Application::DoInitialize(), TimeSimpleTestCase::DoRun(), ns3::ThreeGppHttpHeader::GetClientTs(), ns3::DefaultSimulatorImpl::GetDelayLeft(), ns3::RealtimeSimulatorImpl::GetDelayLeft(), ns3::DistributedSimulatorImpl::GetDelayLeft(), ns3::NullMessageSimulatorImpl::GetDelayLeft(), ns3::Timer::GetDelayLeft(), ns3::DefaultSimulatorImpl::GetMaximumSimulationTime(), ns3::RealtimeSimulatorImpl::GetMaximumSimulationTime(), ns3::DistributedSimulatorImpl::GetMaximumSimulationTime(), ns3::NullMessageSimulatorImpl::GetMaximumSimulationTime(), ns3::ThreeGppHttpHeader::GetServerTs(), ns3::SeqTsHeader::GetTs(), ns3::DelayJitterEstimationTimestampTag::GetTxTime(), ns3::Application::GetTypeId(), ns3::DistributedSimulatorImpl::Next(), ns3::NullMessageSimulatorImpl::Next(), ns3::DefaultSimulatorImpl::Now(), ns3::RealtimeSimulatorImpl::Now(), ns3::DistributedSimulatorImpl::Now(), ns3::NullMessageSimulatorImpl::Now(), ns3::SeqTsHeader::Print(), ns3::ThreeGppHttpHeader::Print(), ns3::RealtimeSimulatorImpl::RealtimeNow(), ChannelAccessTestCase::Receive(), AnnexC_TestCase::Receive(), ns3::DefaultSimulatorImpl::Schedule(), ns3::DistributedSimulatorImpl::Schedule(), ns3::NullMessageSimulatorImpl::Schedule(), ns3::DefaultSimulatorImpl::ScheduleWithContext(), ns3::NullMessageSimulatorImpl::ScheduleWithContext(), ns3::TcpSocketBase::Send(), and ns3::Synchronizer::TimeStepToNanosecond().