ns-3: Hash Functions
Hash Functions
Core
Generic Hash function interface.
Modules
FNV Hash Implementation
Hash test suite
Murmur3 Hash Implementation
Files
file hash-example.cc
file hash-fnv.cc
ns3::Hash::Function::Fnv1a implementation.
file hash-fnv.h
ns3::Hash::Function::Fnv1a declaration.
file hash-function.cc
ns3::Hash::Implementation::GetHash64 default implementation.
file hash-function.h
ns3::Hash::Implementation, ns3::Hash::Function::Hash32 and ns3::Hash::Function::Hash64 declarations.
file hash-murmur3.cc
ns3::Hash::Function::Murmur3 implementation.
file hash-murmur3.h
ns3::Hash::Function::Murmur3 declaration.
file hash-test-suite.cc
file hash.cc
ns3::Hasher implementation.
file hash.h
ns3::Hasher, ns3::Hash32() and ns3::Hash64() function declarations.
Namespaces
ns3::Hash
ns3::Hash::Example
ns3::Hash::Function
Classes
class ns3::Hash::Function::Fnv1a
Fnv1a hash function implementation.
class ns3::Hash::Function::Hash32
Template for creating a Hash::Implementation from a 32-bit hash function.
class ns3::Hash::Function::Hash64
Template for creating a Hash::Implementation from a 64-bit hash function.
class ns3::Hasher
Generic Hash function interface.
class ns3::Hash::Implementation
Hash function implementation base class.
class ns3::Hash::Function::Murmur3
Murmur3 hash function implementation.
Functions
uint32_t ns3::Hash32 (const char *buffer, const std::size_t size)
uint32_t ns3::Hash32 (const std::string s)
uint64_t ns3::Hash64 (const char *buffer, const std::size_t size)
uint64_t ns3::Hash64 (const std::string s)
typedef uint32_t(* ns3::Hash::Hash32Function_ptr) (const char *, const std::size_t)
Function pointer signatures for basic hash functions.
typedef uint64_t(* ns3::Hash::Hash64Function_ptr) (const char *, const std::size_t)
Function pointer signatures for basic hash functions.
Detailed Description
Generic Hash function interface.
See Hasher for main entry point. See hash-example.cc for example usage.
Typedef Documentation
Hash32Function_ptr
typedef uint32_t(* ns3::Hash::Hash32Function_ptr) (const char *, const std::size_t)
Function pointer signatures for basic hash functions.
See Hash::Function::Hash32 or Hash::Function::Hash64
Definition at line 113 of file hash-function.h.
Hash64Function_ptr
typedef uint64_t(* ns3::Hash::Hash64Function_ptr) (const char *, const std::size_t)
Function pointer signatures for basic hash functions.
See Hash::Function::Hash32 or Hash::Function::Hash64
Definition at line 114 of file hash-function.h.
Function Documentation
Hash32() [1/2]
uint32_t ns3::Hash32 (const char * buffer, const std::size_t size) inline
Compute 32-bit hash of a byte buffer, using the default hash function.
Parameters
[in] buffer Pointer to the beginning of the buffer.
[in] size Length of the buffer, in bytes.
Returns
32-bit hash of the buffer.
Definition at line 278 of file hash.h.
Referenced by ns3::tests::DefaultHashTestCase::DoRun(), ns3::ArpQueueDiscItem::Hash(), ns3::Ipv4QueueDiscItem::Hash(), ns3::Ipv6QueueDiscItem::Hash(), and ns3::Ipv4L3Protocol::UpdateDuplicate().
Hash32() [2/2]
uint32_t ns3::Hash32 (const std::string s) inline
Compute 32-bit hash of a string, using the default hash function.
Parameters
[in] s String to hash.
Returns
32-bit hash of the string.
Definition at line 292 of file hash.h.
Hash64() [1/2]
uint64_t ns3::Hash64 (const char * buffer, const std::size_t size) inline
Compute 64-bit hash of a byte buffer, using the default hash function.
Parameters
[in] buffer Pointer to the beginning of the buffer.
[in] size Length of the buffer, in bytes.
Returns
64-bit hash of the buffer.
Definition at line 285 of file hash.h.
Referenced by ns3::tests::DefaultHashTestCase::DoRun().
Hash64() [2/2]
uint64_t ns3::Hash64 (const std::string s) inline
Compute 64-bit hash of a string, using the default hash function.
Parameters
[in] s String to hash.
Returns
64-bit hash of the string.
Definition at line 299 of file hash.h.