ns-3: MakeCallback with no arguments
MakeCallback with no arguments
Core » Callbacks
Define empty (Null) callbacks as placeholders for unset callback variables.
template<typename R >
Callback< R > ns3::MakeNullCallback (void)
template<typename R , typename T1 >
Callback< R, T1 > ns3::MakeNullCallback (void)
template<typename R , typename T1 , typename T2 >
Callback< R, T1, T2 > ns3::MakeNullCallback (void)
template<typename R , typename T1 , typename T2 , typename T3 >
Callback< R, T1, T2, T3 > ns3::MakeNullCallback (void)
template<typename R , typename T1 , typename T2 , typename T3 , typename T4 >
Callback< R, T1, T2, T3, T4 > ns3::MakeNullCallback (void)
template<typename R , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
Callback< R, T1, T2, T3, T4, T5 > ns3::MakeNullCallback (void)
template<typename R , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 >
Callback< R, T1, T2, T3, T4, T5, T6 > ns3::MakeNullCallback (void)
template<typename R , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 >
Callback< R, T1, T2, T3, T4, T5, T6, T7 > ns3::MakeNullCallback (void)
template<typename R , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 >
Callback< R, T1, T2, T3, T4, T5, T6, T7, T8 > ns3::MakeNullCallback (void)
template<typename R , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 >
Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 > ns3::MakeNullCallback (void)
Detailed Description
Define empty (Null) callbacks as placeholders for unset callback variables.
Function Documentation
MakeNullCallback() [1/10]
template<typename R > Callback<R> ns3::MakeNullCallback (void)
Returns
A wrapper Callback
Build null Callbacks which take no arguments, for varying number of template arguments, and potentially returning a value.
Definition at line 1786 of file callback.h.
Referenced by ns3::ThreeGppHttpServerTxBuffer::CloseAllSockets(), ns3::ThreeGppHttpServerTxBuffer::CloseSocket(), ns3::NoBackhaulEpcHelper::DoDispose(), ns3::EpcPgwApplication::DoDispose(), ns3::EpcSgwApplication::DoDispose(), TcpEndPointBug2211Test::DoRun(), DualStackTestCase::DoRun(), ns3::TcpGeneralTest::DoRun(), ns3::DhcpClient::LinkStateHandler(), ns3::ThreeGppHttpClient::NormalCloseCallback(), ns3::ThreeGppHttpServerTxBuffer::RemoveSocket(), ns3::MacLow::ResetPhy(), TcpTestCase::SetupDefaultSim(), TcpTestCase::SetupDefaultSim6(), ns3::PacketSink::StartApplication(), ns3::UdpClient::StartApplication(), ns3::UdpTraceClient::StartApplication(), EpsBearerTagUdpClient::StartApplication(), ns3::PacketSocketClient::StartApplication(), ns3::ThreeGppHttpClient::StopApplication(), ns3::ThreeGppHttpServer::StopApplication(), ns3::Ping6::StopApplication(), ns3::Radvd::StopApplication(), Receiver::StopApplication(), ns3::PacketSink::StopApplication(), ns3::UdpEchoClient::StopApplication(), ns3::UdpEchoServer::StopApplication(), ns3::UdpServer::StopApplication(), ns3::DhcpClient::StopApplication(), ns3::DhcpServer::StopApplication(), and ns3::PacketSocketServer::StopApplication().
MakeNullCallback() [2/10]
template<typename R , typename T1 > Callback<R,T1> ns3::MakeNullCallback (void)
Returns
A wrapper Callback
Build null Callbacks which take no arguments, for varying number of template arguments, and potentially returning a value.
Definition at line 1791 of file callback.h.
MakeNullCallback() [3/10]
template<typename R , typename T1 , typename T2 > Callback<R,T1,T2> ns3::MakeNullCallback (void)
Returns
A wrapper Callback
Build null Callbacks which take no arguments, for varying number of template arguments, and potentially returning a value.
Definition at line 1796 of file callback.h.
MakeNullCallback() [4/10]
template<typename R , typename T1 , typename T2 , typename T3 > Callback<R,T1,T2,T3> ns3::MakeNullCallback (void)
Returns
A wrapper Callback
Build null Callbacks which take no arguments, for varying number of template arguments, and potentially returning a value.
Definition at line 1801 of file callback.h.
MakeNullCallback() [5/10]
template<typename R , typename T1 , typename T2 , typename T3 , typename T4 > Callback<R,T1,T2,T3,T4> ns3::MakeNullCallback (void)
Returns
A wrapper Callback
Build null Callbacks which take no arguments, for varying number of template arguments, and potentially returning a value.
Definition at line 1806 of file callback.h.
MakeNullCallback() [6/10]
template<typename R , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > Callback<R,T1,T2,T3,T4,T5> ns3::MakeNullCallback (void)
Returns
A wrapper Callback
Build null Callbacks which take no arguments, for varying number of template arguments, and potentially returning a value.
Definition at line 1811 of file callback.h.
MakeNullCallback() [7/10]
template<typename R , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 > Callback<R,T1,T2,T3,T4,T5,T6> ns3::MakeNullCallback (void)
Returns
A wrapper Callback
Build null Callbacks which take no arguments, for varying number of template arguments, and potentially returning a value.
Definition at line 1816 of file callback.h.
MakeNullCallback() [8/10]
template<typename R , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 > Callback<R,T1,T2,T3,T4,T5,T6,T7> ns3::MakeNullCallback (void)
Returns
A wrapper Callback
Build null Callbacks which take no arguments, for varying number of template arguments, and potentially returning a value.
Definition at line 1821 of file callback.h.
MakeNullCallback() [9/10]
template<typename R , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 > Callback<R,T1,T2,T3,T4,T5,T6,T7,T8> ns3::MakeNullCallback (void)
Returns
A wrapper Callback
Build null Callbacks which take no arguments, for varying number of template arguments, and potentially returning a value.
Definition at line 1826 of file callback.h.
MakeNullCallback() [10/10]
template<typename R , typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 > Callback<R,T1,T2,T3,T4,T5,T6,T7,T8,T9> ns3::MakeNullCallback (void)
Returns
A wrapper Callback
Build null Callbacks which take no arguments, for varying number of template arguments, and potentially returning a value.
Definition at line 1831 of file callback.h.