ns-3: Hash test suite
Hash test suite
Test suites | Core » Core module tests | Core » Hash Functions
Files
file hash-test-suite.cc
Classes
class ns3::tests::DefaultHashTestCase
class ns3::tests::Fnv1aTestCase
class ns3::tests::Hash32FunctionPtrTestCase
class ns3::tests::Hash64FunctionPtrTestCase
class ns3::tests::HashTestCase
class ns3::tests::HashTestSuite
class ns3::tests::IncrementalTestCase
class ns3::tests::Murmur3TestCase
Functions
uint16_t ns3::tests::gnu_sum (const char *buffer, const std::size_t size)
uint32_t ns3::tests::gnu_sum32 (const char *buffer, const std::size_t size)
uint64_t ns3::tests::gnu_sum64 (const char *buffer, const std::size_t size)
Variables
static HashTestSuite ns3::tests::g_hashTestSuite
Detailed Description
Function Documentation
gnu_sum()
uint16_t ns3::tests::gnu_sum (const char * buffer, const std::size_t size)
Simple hash function based on the GNU sum program.
16-bit checksum algorithm. See http://svnweb.freebsd.org/base/stable/9/usr.bin/cksum/sum1.c?view=markup
Used to test Hash32Function_ptr/Hash64Function_ptr
Parameters
[in,out] buffer The data to hash.
[in] size The buffer size.
Returns
The checksum of the buffer contents.
Definition at line 270 of file hash-test-suite.cc.
Referenced by ns3::tests::gnu_sum32().
gnu_sum32()
uint32_t ns3::tests::gnu_sum32 (const char * buffer, const std::size_t size)
A 32-bit hash function, based on gnu_sum(). Simple hash function based on the GNU sum program.
16-bit checksum algorithm. See http://svnweb.freebsd.org/base/stable/9/usr.bin/cksum/sum1.c?view=markup
Used to test Hash32Function_ptr/Hash64Function_ptr
Parameters
[in,out] buffer The data to hash.
[in] size The buffer size.
Returns
The checksum of the buffer contents.
Definition at line 291 of file hash-test-suite.cc.
References ns3::tests::gnu_sum().
Referenced by ns3::tests::Hash32FunctionPtrTestCase::DoRun(), and ns3::tests::gnu_sum64().
gnu_sum64()
uint64_t ns3::tests::gnu_sum64 (const char * buffer, const std::size_t size)
A 64-bit hash function, base on gnu_sum(). Simple hash function based on the GNU sum program.
16-bit checksum algorithm. See http://svnweb.freebsd.org/base/stable/9/usr.bin/cksum/sum1.c?view=markup
Used to test Hash32Function_ptr/Hash64Function_ptr
Parameters
[in,out] buffer The data to hash.
[in] size The buffer size.
Returns
The checksum of the buffer contents.
Definition at line 303 of file hash-test-suite.cc.
References ns3::tests::gnu_sum32().
Referenced by ns3::tests::Hash64FunctionPtrTestCase::DoRun().
Variable Documentation
g_hashTestSuite
HashTestSuite ns3::tests::g_hashTestSuite static
HashTestSuite instance variable.
Definition at line 460 of file hash-test-suite.cc.