ns-3: src/internet/model/ipv4-address-generator.cc File Reference
ipv4-address-generator.cc File Reference
#include <list>
#include "ns3/abort.h"
#include "ns3/assert.h"
#include "ns3/log.h"
#include "ns3/simulation-singleton.h"
#include "ipv4-address-generator.h"
Classes
class ns3::Ipv4AddressGeneratorImpl::Entry
This class holds the allocated addresses.
class ns3::Ipv4AddressGeneratorImpl
Implementation class of Ipv4AddressGenerator This generator assigns addresses sequentially from a provided network address; used in topology code. It also keeps track of all addresses assigned to perform duplicate detection.
class ns3::Ipv4AddressGeneratorImpl::NetworkState
This class holds the state for a given network.
Namespaces
ns3
Every class exported by the ns3 library is enclosed in the ns3 namespace.
Functions
NS_ASSERT_MSG (false, "Ipv4AddressGenerator::MaskToIndex(): Impossible")
Variables
ns3::maskBits = 1
return
Function Documentation
NS_ASSERT_MSG()
NS_ASSERT_MSG (false , "Ipv4AddressGenerator::MaskToIndex(): Impossible")
Referenced by ns3::CsParameters::CsParameters(), ns3::dsr::DsrOptionPadnHeader::DsrOptionPadnHeader(), ns3::GlobalRoutingLSA::GlobalRoutingLSA(), ns3::IpcsClassifierRecord::IpcsClassifierRecord(), ns3::Ipv6AddressHelper::Ipv6AddressHelper(), ns3::Ipv6OptionPadnHeader::Ipv6OptionPadnHeader(), ns3::Ipv6Prefix::Ipv6Prefix(), ns3::LteUePhy::LteUePhy(), ns3::SameRoomPositionAllocator::SameRoomPositionAllocator(), ns3::ServiceFlow::ServiceFlow(), ns3::SPFVertex::~SPFVertex(), ns3::LteHelper::ActivateDataRadioBearer(), ns3::LteHelper::ActivateDedicatedEpsBearer(), ns3::NoBackhaulEpcHelper::ActivateEpsBearer(), ns3::NamesPriv::Add(), ns3::PacketTagList::Add(), ns3::EpcMmeApplication::AddBearer(), ns3::SupportedRates::AddBssMembershipSelectorRate(), ns3::ThreeGppSpectrumPropagationLossModel::AddDevice(), ns3::NoBackhaulEpcHelper::AddEnb(), ns3::SixLowPanNetDevice::Fragments::AddFragment(), ns3::CsmaNetDevice::AddHeader(), ns3::ArpQueueDiscItem::AddHeader(), ns3::Ipv4QueueDiscItem::AddHeader(), ns3::Ipv6QueueDiscItem::AddHeader(), ns3::NscTcpL4Protocol::AddInterface(), ns3::SixLowPanNetDevice::AddLinkChangeCallback(), ns3::Ipv4StaticRoutingHelper::AddMulticastRoute(), ns3::Ipv6StaticRoutingHelper::AddMulticastRoute(), ns3::MultiModelSpectrumChannel::AddRx(), ns3::NoBackhaulEpcHelper::AddS1Interface(), ns3::ThreeGppHttpServerTxBuffer::AddSocket(), ns3::DhcpServer::AddStaticDhcpEntry(), ns3::SupportedRates::AddSupportedRate(), ns3::LteEnbRrc::AddUe(), ns3::LteEnbRrc::AddUeMeasReportConfig(), ns3::LteHelper::AddX2Interface(), ns3::EpcX2::AddX2Interface(), ns3::TcpSocketBase::AdvertisedWindowSize(), TcpFastRetrTest::AfterRTOExpired(), ns3::LteUeRrc::ApplyMeasConfig(), ns3::LteUeRrc::ApplyRadioResourceConfigDedicated(), ns3::AsciiToIpv4Host(), ns3::Ipv4AddressHelper::Assign(), ns3::Ipv6AddressHelper::Assign(), ns3::TraceFadingLossModel::AssignStreams(), ns3::AodvHelper::AssignStreams(), ns3::RipHelper::AssignStreams(), ns3::RipNgHelper::AssignStreams(), ns3::OlsrHelper::AssignStreams(), ns3::PointToPointChannel::Attach(), ns3::LteHelper::AttachToClosestEnb(), ns3::RandomWaypointMobilityModel::BeginWalk(), benchA(), ns3::UdpSocketImpl::Bind(), ns3::Socket::BindToNetDevice(), ns3::BSSchedulerRtps::BSSchedulerBasicConnection(), ns3::BSSchedulerRtps::BSSchedulerBEConnection(), ns3::BSSchedulerRtps::BSSchedulerBroadcastConnection(), ns3::BSSchedulerRtps::BSSchedulerInitialRangingConnection(), ns3::BSSchedulerRtps::BSSchedulerNRTPSConnection(), ns3::BSSchedulerRtps::BSSchedulerPrimaryConnection(), ns3::BSSchedulerRtps::BSSchedulerRTPSConnection(), ns3::TcpTxBuffer::BytesInFlight(), ns3::TcpTxBuffer::BytesInFlightRFC(), ns3::ThreeGppChannelModel::CalcAttenuationOfBlockage(), ns3::InterferenceHelper::CalculateNoiseInterferenceW(), ns3::LteHelper::ChannelModelInitialization(), ns3::dot11s::PeerManagementProtocol::CheckBeaconCollisions(), LteRadioLinkFailureTestCase::CheckConnected(), LteRrcConnectionEstablishmentTestCase::CheckConnected(), LteX2HandoverMeasuresTestCase::CheckConnected(), LteX2HandoverTestCase::CheckConnected(), TcFlowControlTestCase::CheckDeviceQueueStopped(), LteRrcConnectionEstablishmentTestCase::CheckNotConnected(), TracedCallbackTypedefTestCase::CheckerBase< T1, T2, T3, T4, empty >::Cleanup(), ns3::Time::Clear(), ns3::ThreeGppHttpServerTxBuffer::CloseSocket(), ns3::SixLowPanNetDevice::CompressLowPanUdpNhc(), ns3::UanMacRcGw::ComputeAlpha(), ns3::LteEnbRrc::ConfigureCarriers(), ns3::LteEnbRrc::ConnectionRejectedTimeout(), ns3::LteEnbRrc::ConnectionRequestTimeout(), ns3::LteEnbRrc::ConnectionSetupTimeout(), ns3::ThreeGppHttpClient::ConnectionSucceededCallback(), ns3::TcpTxBuffer::ConsistencyCheck(), ns3::SixLowPanNhcExtension::CopyBlob(), ns3::TcpTxBuffer::CopyFromSequence(), FemtocellBlockAllocator::Create(), ns3::LteAmc::CreateCqiFeedbacks(), ns3::LteUePhy::CreateDlCqiFeedbackMessage(), ns3::EmuFdNetDeviceHelper::CreateFileDescriptor(), ns3::PlanetLabFdNetDeviceHelper::CreateFileDescriptor(), ns3::TapFdNetDeviceHelper::CreateFileDescriptor(), ns3::WifiSpectrumValueHelper::CreateHeOfdmTxPowerSpectralDensity(), ns3::WifiSpectrumValueHelper::CreateHtOfdmTxPowerSpectralDensity(), DsdvManetExample::CreateNodes(), ns3::LrWpanSpectrumValueHelper::CreateNoisePowerSpectralDensity(), ns3::WifiSpectrumValueHelper::CreateOfdmTxPowerSpectralDensity(), ns3::WifiSpectrumValueHelper::CreateRfFilter(), ns3::PacketTagList::CreateTagData(), ns3::TapBridge::CreateTap(), ns3::LrWpanSpectrumValueHelper::CreateTxPowerSpectralDensity(), ns3::LteHelper::DeActivateDedicatedEpsBearer(), ns3::SixLowPanNetDevice::DecompressLowPanHc1(), ns3::TrafficControlLayer::DeleteRootQueueDiscOnDevice(), ns3::ThreeGppHttpServerTxBuffer::DepleteBufferSize(), ns3::WimaxMacQueue::Dequeue(), ns3::RadiotapHeader::Deserialize(), ns3::SixLowPanHc1::Deserialize(), ns3::Tlv::Deserialize(), ns3::WifiInformationElementVector::Deserialize(), ns3::SfVectorTlvValue::Deserialize(), ns3::GtpcIes::DeserializeBearerContextHeader(), ns3::GtpcIes::DeserializeBearerQos(), ns3::GtpcIes::DeserializeBearerTft(), ns3::GtpcIes::DeserializeCause(), ns3::GtpcIes::DeserializeEbi(), ns3::GtpcIes::DeserializeFteid(), ns3::GtpcIes::DeserializeImsi(), ns3::GtpcIes::DeserializeUliEcgi(), ns3::TcpTxBuffer::DiscardUpTo(), ns3::GlobalRouter::DiscoverLSAs(), ns3::EpcUeNas::DoActivateEpsBearer(), ns3::LteEnbMac::DoAddLc(), ns3::NoOpComponentCarrierManager::DoAddLc(), ns3::LteUeMac::DoAddLc(), ns3::LteEnbMac::DoAddUe(), ns3::LteEnbPhy::DoAddUe(), ns3::NoOpComponentCarrierManager::DoAddUe(), ns3::RandomWaypointMobilityModel::DoAssignStreams(), ns3::ThreeGppPropagationLossModel::DoCalcRxPower(), ns3::ThreeGppSpectrumPropagationLossModel::DoCalcRxPowerSpectralDensity(), ns3::TraceFadingLossModel::DoCalcRxPowerSpectralDensity(), ns3::NoOpComponentCarrierManager::DoConfigureSignalBearer(), ns3::RateErrorModel::DoCorrupt(), ns3::LteEnbRrcProtocolIdeal::DoDecodeHandoverCommand(), ns3::LteEnbRrcProtocolIdeal::DoDecodeHandoverPreparationInformation(), ns3::LteEnbRrcProtocolIdeal::DoEncodeHandoverCommand(), ns3::LteEnbRrcProtocolIdeal::DoEncodeHandoverPreparationInformation(), ns3::PrioQueueDisc::DoEnqueue(), ns3::EpcMmeApplication::DoErabReleaseIndication(), ns3::Ipv4L3Protocol::DoFragmentation(), ns3::SixLowPanNetDevice::DoFragmentation(), ns3::EpcEnbApplication::DoInitialContextSetupRequest(), ns3::Rip::DoInitialize(), ns3::RipNg::DoInitialize(), ns3::LteFfrEnhancedAlgorithm::DoInitialize(), ns3::LteFfrSoftAlgorithm::DoInitialize(), ns3::LteFrHardAlgorithm::DoInitialize(), ns3::LteFrSoftAlgorithm::DoInitialize(), ns3::LteFrStrictAlgorithm::DoInitialize(), ns3::QueueDisc::DoInitialize(), ns3::EpcMmeApplication::DoInitialUeMessage(), ns3::LteRlcAm::DoNotifyTxOpportunity(), ns3::LteRlcUm::DoNotifyTxOpportunity(), ns3::NoOpComponentCarrierManager::DoNotifyTxOpportunity(), ns3::EpcMmeApplication::DoPathSwitchRequest(), ns3::EpcEnbApplication::DoPathSwitchRequestAcknowledge(), ns3::BaseStationNetDevice::DoReceive(), ns3::SubscriberStationNetDevice::DoReceive(), ns3::LteRlcAm::DoReceivePdu(), ns3::LteRlcUm::DoReceivePdu(), ns3::LteRlcSm::DoReceivePdu(), ns3::NoOpComponentCarrierManager::DoReceivePdu(), ns3::LteEnbMac::DoReceivePhyPdu(), ns3::EpcPgwApplication::DoRecvCreateSessionRequest(), ns3::EpcSgwApplication::DoRecvCreateSessionRequest(), ns3::EpcMmeApplication::DoRecvCreateSessionResponse(), ns3::EpcSgwApplication::DoRecvCreateSessionResponse(), ns3::EpcMmeApplication::DoRecvDeleteBearerRequest(), ns3::EpcPgwApplication::DoRecvDeleteBearerResponse(), ns3::EpcPgwApplication::DoRecvModifyBearerRequest(), ns3::EpcSgwApplication::DoRecvModifyBearerRequest(), ns3::EpcMmeApplication::DoRecvModifyBearerResponse(), ns3::LteUeRrc::DoRecvRrcConnectionReconfiguration(), ns3::LteUeRrc::DoRecvSystemInformation(), ns3::LteUeRrc::DoRecvSystemInformationBlockType1(), ns3::NoOpComponentCarrierManager::DoReleaseDataRadioBearer(), ns3::LteUeMac::DoRemoveLc(), ns3::LteEnbPhy::DoRemoveUe(), ns3::NoOpComponentCarrierManager::DoRemoveUe(), ns3::MinstrelHtWifiManager::DoReportAmpduTxStatus(), ns3::NoOpComponentCarrierManager::DoReportBufferStatus(), ns3::RrComponentCarrierManager::DoReportBufferStatus(), ns3::LteAnr::DoReportUeMeas(), ns3::A2A4RsrqHandoverAlgorithm::DoReportUeMeas(), ns3::LteFfrDistributedAlgorithm::DoReportUeMeas(), ns3::LteFfrSoftAlgorithm::DoReportUeMeas(), RandomRoomPositionAllocatorTestCase::DoRun(), SameRoomPositionAllocatorTestCase::DoRun(), Ipv4DeduplicationTest::DoRun(), Ipv4DeduplicationPerformanceTest::DoRun(), EpcS1uDlTestCase::DoRun(), EpcS1uUlTestCase::DoRun(), LteUplinkSrsSinrTestCase::DoRun(), ns3::LteEnbMac::DoSchedDlConfigInd(), ns3::CqaFfMacScheduler::DoSchedDlTriggerReq(), ns3::FdBetFfMacScheduler::DoSchedDlTriggerReq(), ns3::FdMtFfMacScheduler::DoSchedDlTriggerReq(), ns3::FdTbfqFfMacScheduler::DoSchedDlTriggerReq(), ns3::PfFfMacScheduler::DoSchedDlTriggerReq(), ns3::PssFfMacScheduler::DoSchedDlTriggerReq(), ns3::RrFfMacScheduler::DoSchedDlTriggerReq(), ns3::TdBetFfMacScheduler::DoSchedDlTriggerReq(), ns3::TdMtFfMacScheduler::DoSchedDlTriggerReq(), ns3::TdTbfqFfMacScheduler::DoSchedDlTriggerReq(), ns3::TtaFfMacScheduler::DoSchedDlTriggerReq(), ns3::SixLowPanNetDevice::DoSend(), ns3::LteUeRrc::DoSendData(), ns3::EpcX2::DoSendHandoverPreparationFailure(), ns3::EpcX2::DoSendHandoverRequest(), ns3::EpcX2::DoSendHandoverRequestAck(), ns3::EpcX2::DoSendLoadInformation(), ns3::EpcX2::DoSendResourceStatusUpdate(), ns3::EpcX2::DoSendSnStatusTransfer(), ns3::EpcX2::DoSendUeContextRelease(), ns3::EpcX2::DoSendUeData(), ns3::NoOpComponentCarrierManager::DoSetupDataRadioBearer(), ns3::LteUeRrc::DoStartCellSelection(), ns3::LteUeMac::DoStartContentionBasedRandomAccessProcedure(), ns3::LteUeMac::DoStartNonContentionBasedRandomAccessProcedure(), ns3::LteUeMac::DoTransmitPdu(), ns3::NoOpComponentCarrierManager::DoTransmitPdu(), ns3::LteEnbRrc::DoTriggerHandover(), ns3::NoOpComponentCarrierManager::DoUlReceiveMacCe(), ns3::RrComponentCarrierManager::DoUlReceiveMacCe(), ns3::TcpSocketBase::DupAck(), ns3::PacketMetadata::Enable(), ns3::InternetStackHelper::EnableAsciiIpv4Internal(), ns3::InternetStackHelper::EnableAsciiIpv6Internal(), ns3::InternetStackHelper::EnablePcapIpv4Internal(), ns3::InternetStackHelper::EnablePcapIpv6Internal(), ns3::LteHelper::EnablePdcpTraces(), ns3::LteHelper::EnableRlcTraces(), ns3::LrWpanPhy::EndCca(), ns3::LteSpectrumPhy::EndRxData(), ns3::SimpleOfdmWimaxPhy::EndSendFecBlock(), ns3::BaseStationNetDevice::Enqueue(), ns3::SubscriberStationNetDevice::Enqueue(), ns3::PointToPointNetDevice::EtherToPpp(), ns3::LteRlcAm::ExpireReorderingTimer(), ns3::NamesPriv::Find(), ns3::Icmpv6L4Protocol::FindCache(), ns3::GlobalRouteManagerImpl::FindOutgoingInterfaceId(), ns3::NamesPriv::FindPath(), ns3::dsr::DsrRouting::ForwardErrPacket(), ns3::dsr::DsrRouting::ForwardPacket(), ns3::TapBridge::ForwardToBridgedDevice(), ns3::BriteTopologyHelper::GenerateBriteTopology(), ns3::LteUePhy::GenerateCqiRsrpRsrq(), ns3::Gnuplot::GenerateOutput(), ns3::SixLowPanNetDevice::Get16MacFrom48Mac(), ns3::LteHarqPhy::GetAccumulatedMiUl(), ns3::SixLowPanNetDevice::GetAddress(), ns3::Node::GetApplication(), ns3::V4Ping::GetApplicationId(), ns3::V4TraceRoute::GetApplicationId(), ns3::StaWifiMac::GetAssociationId(), ns3::GlobalRoutingLSA::GetAttachedRouter(), ns3::TopologyReader::Link::GetAttribute(), ns3::PrioQueueDisc::GetBandForPriority(), ns3::SixLowPanNetDevice::GetBroadcast(), ns3::ThreeGppHttpServerTxBuffer::GetBufferContentType(), ns3::ThreeGppHttpServerTxBuffer::GetBufferSize(), ns3::BuildingListPriv::GetBuilding(), ns3::ChannelListPriv::GetChannel(), ns3::SixLowPanNetDevice::GetChannel(), ns3::BuildingsChannelConditionModel::GetChannelCondition(), ns3::SPFVertex::GetChild(), ns3::ThreeGppHttpServerTxBuffer::GetClientTs(), ns3::BaseStationNetDevice::GetConnection(), ns3::LteAmc::GetCqiFromSpectralEfficiency(), ns3::LteFfrEnhancedAlgorithm::GetCqiFromSpectralEfficiency(), ns3::WifiMode::GetDataRate(), ns3::Node::GetDevice(), ns3::LteAmc::GetDlTbSizeFromMcs(), ns3::ThreeGppAntennaArrayModel::GetElementFieldPattern(), ns3::Ipv6InterfaceContainer::GetLinkLocalAddress(), ns3::GlobalRoutingLSA::GetLinkRecord(), ns3::HybridBuildingsPropagationLossModel::GetLoss(), ns3::ItuR1238PropagationLossModel::GetLoss(), ns3::OhBuildingsPropagationLossModel::GetLoss(), ns3::ItuR1411LosPropagationLossModel::GetLoss(), ns3::ItuR1411NlosOverRooftopPropagationLossModel::GetLoss(), ns3::OkumuraHataPropagationLossModel::GetLoss(), ns3::ThreeGppRmaPropagationLossModel::GetLossLos(), ns3::ThreeGppRmaPropagationLossModel::GetLossNlos(), ns3::LteEnbRrc::GetLteFfrRrcSapUser(), ns3::WifiPhy::GetMcs(), ns3::LteAmc::GetMcsFromCqi(), ns3::SixLowPanNetDevice::GetMulticast(), ns3::Ipv4StaticRouting::GetMulticastRoute(), ns3::Ipv6StaticRouting::GetMulticastRoute(), ns3::EnumChecker::GetName(), ns3::ThreeGppChannelModel::GetNewChannel(), ns3::RandomBuildingPositionAllocator::GetNext(), ns3::RandomRoomPositionAllocator::GetNext(), ns3::SameRoomPositionAllocator::GetNext(), ns3::NodeListPriv::GetNode(), ns3::Ipv4MulticastRoutingTableEntry::GetOutputInterface(), ns3::Ipv6MulticastRoutingTableEntry::GetOutputInterface(), ns3::TcpTxBuffer::GetPacketFromList(), ns3::LteMiErrorModel::GetPcfichPdcchError(), ns3::UdpSocketImpl::GetPeerName(), ns3::WifiPhy::GetPowerDbm(), ns3::ThreeGppAntennaArrayModel::GetRadiationPattern(), ns3::LSigHeader::GetRate(), ns3::DsssSigHeader::GetRate(), ns3::Time::GetResolution(), ns3::SPFVertex::GetRootExitDirection(), ns3::BuildingsPropagationLossModel::GetShadowing(), ns3::LteAmc::GetSpectralEfficiencyFromCqi(), ns3::WifiSpectrumValueHelper::GetSpectrumModel(), ns3::LteSpectrumValueHelper::GetSpectrumModel(), ns3::Ipv4StaticRoutingHelper::GetStaticRouting(), ns3::Ipv6StaticRoutingHelper::GetStaticRouting(), ns3::Ipv4Address::GetSubnetDirectedBroadcast(), ns3::UanPdp::GetTap(), ns3::ThreeGppChannelModel::GetThreeGppTable(), ns3::TopologyReaderHelper::GetTopologyReader(), ns3::WifiPpdu::GetTxVector(), ns3::LteEnbRrc::GetUeManager(), ns3::LteEnbRrcProtocolIdeal::GetUeRrcSapProvider(), ns3::LteEnbRrcProtocolReal::GetUeRrcSapProvider(), ns3::LteAmc::GetUlTbSizeFromMcs(), ns3::EnumChecker::GetValue(), ns3::GetWildcardMatches(), ns3::Ipv6ExtensionFragment::HandleFragmentsTimeout(), ns3::Rip::HandleRequests(), ns3::RipNg::HandleRequests(), ns3::LteEnbRrc::HandoverJoiningTimeout(), ns3::LteEnbRrc::HandoverLeavingTimeout(), ns3::LteHelper::HandoverRequest(), ns3::ThreeGppHttpServerTxBuffer::HasTxedPartOfObject(), ns3::AsciiTraceHelper::HookDefaultDequeueSinkWithContext(), ns3::AsciiTraceHelper::HookDefaultDequeueSinkWithoutContext(), ns3::AsciiTraceHelper::HookDefaultDropSinkWithContext(), ns3::AsciiTraceHelper::HookDefaultDropSinkWithoutContext(), ns3::AsciiTraceHelper::HookDefaultEnqueueSinkWithContext(), ns3::AsciiTraceHelper::HookDefaultEnqueueSinkWithoutContext(), ns3::AsciiTraceHelper::HookDefaultReceiveSinkWithContext(), ns3::AsciiTraceHelper::HookDefaultReceiveSinkWithoutContext(), ns3::PcapHelper::HookDefaultSink(), ns3::LteFfrEnhancedAlgorithm::InitializeDownlinkRbgMaps(), ns3::LteFfrSoftAlgorithm::InitializeDownlinkRbgMaps(), ns3::LteFrHardAlgorithm::InitializeDownlinkRbgMaps(), ns3::LteFrSoftAlgorithm::InitializeDownlinkRbgMaps(), ns3::LteFrStrictAlgorithm::InitializeDownlinkRbgMaps(), ns3::WifiPhy::InitializeFrequencyChannelNumber(), ns3::LteFfrEnhancedAlgorithm::InitializeUplinkRbgMaps(), ns3::LteFfrSoftAlgorithm::InitializeUplinkRbgMaps(), ns3::LteFrHardAlgorithm::InitializeUplinkRbgMaps(), ns3::LteFrSoftAlgorithm::InitializeUplinkRbgMaps(), ns3::LteFrStrictAlgorithm::InitializeUplinkRbgMaps(), ns3::SsServiceFlowManager::InitiateServiceFlows(), ns3::WifiMacQueue::Insert(), ns3::SixLowPanHelper::Install(), ns3::AdhocAlohaNoackIdealPhyHelper::Install(), ns3::SpectrumAnalyzerHelper::Install(), ns3::WaveformGeneratorHelper::Install(), ns3::TvSpectrumTransmitterHelper::Install(), ns3::TvSpectrumTransmitterHelper::InstallAdjacent(), ns3::DhcpHelper::InstallDhcpClientPriv(), ns3::DhcpHelper::InstallDhcpServer(), ns3::DhcpHelper::InstallFixedAddress(), ns3::SimpleNetDeviceHelper::InstallPriv(), ns3::LteHelper::InstallSingleEnbDevice(), ns3::LteHelper::InstallSingleUeDevice(), ns3::Socket::Ipv6JoinGroup(), ns3::Ipv6RawSocketImpl::Ipv6JoinGroup(), ns3::UdpSocketImpl::Ipv6JoinGroup(), ns3::SixLowPanNetDevice::IsBridge(), ns3::SixLowPanNetDevice::IsBroadcast(), ns3::ThreeGppHttpServerTxBuffer::IsBufferEmpty(), ns3::SixLowPanNetDevice::IsLinkUp(), ns3::SixLowPanNetDevice::IsMulticast(), ns3::LteRlcAmHeader::IsNackPresent(), ns3::SixLowPanNetDevice::IsPointToPoint(), ns3::ThreeGppChannelModel::ThreeGppChannelMatrix::IsReverse(), ns3::TraceFadingLossModel::LoadTrace(), ns3::UdpTraceClient::LoadTrace(), ns3::Ipv6L3Protocol::LocalDeliver(), ns3::Rip::Lookup(), ns3::RipNg::Lookup(), ns3::TypeId::LookupByHash(), ns3::TypeId::LookupByName(), ns3::Ipv4StaticRouting::LookupStatic(), ns3::Ipv6StaticRouting::LookupStatic(), ns3::aodv::RoutingProtocol::LoopbackRoute(), ns3::dsdv::RoutingProtocol::LoopbackRoute(), ns3::LteMiErrorModel::MappingMiBler(), ns3::ArpCache::Entry::MarkWaitReply(), ns3::LteUeRrc::MeasurementReportTriggering(), ns3::TcpTxBuffer::MergeItems(), ns3::LteMiErrorModel::Mib(), ns3::SixLowPanNetDevice::NeedsArp(), ns3::Ipv4AddressHelper::NewAddress(), ns3::Ipv6AddressHelper::NewAddress(), ns3::RealtimeSimulatorImpl::NextTs(), ns3::WifiPhy::NotifyMonitorSniffRx(), ns3::WifiPhy::NotifyMonitorSniffTx(), ns3::AlohaNoackNetDevice::NotifyTransmissionEnd(), ns3::Ipv4AddressHelper::NumAddressBits(), ns3::LteRlcAmHeader::OneMoreNackWouldFitIn(), ns3::AthstatsWifiTraceSink::Open(), ns3::ThreeGppHttpClient::OpenConnection(), ns3::Ptr< T >::operator*(), ns3::Ptr< T >::operator->(), ns3::operator<<(), ns3::NetDeviceQueue::PacketDequeued(), ns3::NetDeviceQueue::PacketEnqueued(), ns3::CommandLine::Parse(), ns3::LrWpanMac::PdDataConfirm(), ns3::Buffer::Iterator::PeekU8(), ns3::SSLinkManager::PerformRanging(), ns3::LteRlcAmHeader::PopNack(), ns3::PointToPointNetDevice::PppToEther(), ns3::ThreeGppHttpServerTxBuffer::PrepareClose(), ns3::GlobalRoutingLSA::Print(), ns3::PppHeader::Print(), PrintSize(), ns3::V4TraceRouteHelper::PrintTraceRouteAt(), ns3::TcpSocketBase::ProcessAck(), ns3::GlobalRouter::ProcessBridgedBroadcastLink(), ns3::BsServiceFlowManager::ProcessDsaReq(), ns3::RealtimeSimulatorImpl::ProcessOneEvent(), ns3::BSLinkManager::ProcessRangingRequest(), ns3::SubscriberStationNetDevice::ProcessUlMap(), ns3::LteRlcAmHeader::PushNack(), ns3::QosUtilsMapTidToAc(), ns3::LteUeMac::RandomlySelectAndSendRaPreamble(), ns3::TapBridge::ReadCallback(), ns3::ReadLoDigits(), ns3::Ipv4L3Protocol::Receive(), ns3::Ipv6L3Protocol::Receive(), ns3::TapBridge::ReceiveFromBridgedDevice(), ns3::Node::ReceiveFromDevice(), ns3::ThreeGppHttpServerTxBuffer::RecordNextServe(), ns3::aodv::RoutingProtocol::RecvAodv(), ns3::EpcX2::RecvFromX2cSocket(), ns3::EpcX2::RecvFromX2uSocket(), ns3::UeManager::RecvHandoverRequestAck(), ns3::LteUeMac::RecvRaResponse(), ns3::UeManager::RecvUeContextRelease(), ns3::CqaFfMacScheduler::RefreshDlCqiMaps(), ns3::FdBetFfMacScheduler::RefreshDlCqiMaps(), ns3::FdMtFfMacScheduler::RefreshDlCqiMaps(), ns3::FdTbfqFfMacScheduler::RefreshDlCqiMaps(), ns3::PfFfMacScheduler::RefreshDlCqiMaps(), ns3::PssFfMacScheduler::RefreshDlCqiMaps(), ns3::RrFfMacScheduler::RefreshDlCqiMaps(), ns3::TdBetFfMacScheduler::RefreshDlCqiMaps(), ns3::TdMtFfMacScheduler::RefreshDlCqiMaps(), ns3::TdTbfqFfMacScheduler::RefreshDlCqiMaps(), ns3::TtaFfMacScheduler::RefreshDlCqiMaps(), ns3::CqaFfMacScheduler::RefreshUlCqiMaps(), ns3::FdBetFfMacScheduler::RefreshUlCqiMaps(), ns3::FdMtFfMacScheduler::RefreshUlCqiMaps(), ns3::FdTbfqFfMacScheduler::RefreshUlCqiMaps(), ns3::PfFfMacScheduler::RefreshUlCqiMaps(), ns3::PssFfMacScheduler::RefreshUlCqiMaps(), ns3::RrFfMacScheduler::RefreshUlCqiMaps(), ns3::TdBetFfMacScheduler::RefreshUlCqiMaps(), ns3::TdMtFfMacScheduler::RefreshUlCqiMaps(), ns3::TdTbfqFfMacScheduler::RefreshUlCqiMaps(), ns3::TtaFfMacScheduler::RefreshUlCqiMaps(), ns3::UeManager::ReleaseDataRadioBearer(), ns3::UeManager::RemoveDataRadioBearerInfo(), ns3::TcpTxBuffer::RemoveFromCounts(), ns3::ThreeGppHttpServerTxBuffer::RemoveSocket(), ns3::LteEnbRrc::RemoveSrsConfigurationIndex(), ns3::PendingData::RemoveToSeq(), ns3::LteEnbRrc::RemoveUe(), ns3::NamesPriv::Rename(), ns3::SpectrumWifiPhy::ResetSpectrumModel(), ns3::TcpSocketBase::ReTxTimeout(), ns3::EutranMeasurementMapping::RsrpRange2Dbm(), ns3::EutranMeasurementMapping::RsrqRange2Db(), ns3::RealtimeSimulatorImpl::Run(), ns3::LteUeRrc::SaveScellUeMeasurements(), ns3::LteUeRrc::SaveUeMeasurements(), ns3::TrafficControlLayer::ScanDevices(), ns3::DefaultSimulatorImpl::Schedule(), ns3::RealtimeSimulatorImpl::Schedule(), ns3::SSScheduler::Schedule(), ns3::DefaultSimulatorImpl::ScheduleDestroy(), ns3::DefaultSimulatorImpl::ScheduleNow(), ns3::RealtimeSimulatorImpl::ScheduleRealtimeNowWithContext(), ns3::RealtimeSimulatorImpl::ScheduleRealtimeWithContext(), ns3::RealtimeSimulatorImpl::ScheduleWithContext(), ns3::olsr::SecondsToEmf(), ns3::SSLinkManager::SelectRandomBackoff(), ns3::Ipv4L3Protocol::SelectSourceAddress(), ns3::Ipv4Interface::Send(), ns3::Ipv6Interface::Send(), ns3::lorawan::EndDeviceLorawanMac::Send(), ns3::LoopbackNetDevice::Send(), ns3::dsr::DsrRouting::Send(), ns3::Ipv6L3Protocol::Send(), ns3::UdpEchoClient::Send(), ns3::NscTcpL4Protocol::send_callback(), ns3::dsr::DsrRouting::SendAck(), ns3::MacLow::SendAckAfterData(), ns3::BandwidthManager::SendBandwidthRequest(), ns3::LteEnbRrc::SendData(), ns3::dsr::DsrRouting::SendErrorRequest(), ns3::CsmaNetDevice::SendFrom(), ns3::FdNetDevice::SendFrom(), ns3::LoopbackNetDevice::SendFrom(), ns3::UanNetDevice::SendFrom(), ns3::dsr::DsrRouting::SendInitialRequest(), ns3::dsr::DsrRouting::SendPacketFromBuffer(), ns3::SSLinkManager::SendRangingRequest(), ns3::dsr::DsrRouting::SendReply(), ns3::LteUeMac::SendReportBufferStatus(), ns3::dsr::DsrRouting::SendRequest(), ns3::SixLowPanHc1::Serialize(), ns3::Asn1Header::SerializeInteger(), ns3::SixLowPanNetDevice::SetAddress(), ns3::UanNetDevice::SetAddress(), ns3::PrioQueueDisc::SetBandForPriority(), ns3::Ipv4AddressHelper::SetBase(), ns3::Ipv6AddressHelper::SetBase(), ns3::SupportedRates::SetBasicRate(), ns3::PacketLossCounter::SetBitMapSize(), ns3::SixLowPanNhcExtension::SetBlob(), ns3::SimpleOfdmWimaxPhy::SetBlockParameters(), ns3::TapBridge::SetBridgedNetDevice(), ns3::LteEnbNetDevice::SetCcMap(), ns3::DhcpHeader::SetChaddr(), ns3::WifiPhy::SetChannelWidth(), ns3::Ipv4StaticRoutingHelper::SetDefaultMulticastRoute(), ns3::Ipv6InterfaceContainer::SetDefaultRoute(), ns3::Ipv6InterfaceContainer::SetDefaultRouteInAllNodes(), ns3::RipHelper::SetDefaultRouter(), ns3::RipNgHelper::SetDefaultRouter(), ns3::SixLowPanIphc::SetDscp(), ns3::SixLowPanIphc::SetDstContextId(), ns3::SixLowPanIphc::SetEcn(), ns3::ThreeGppHttpVariables::SetEmbeddedObjectSizeMean(), ns3::LteUeRrcProtocolIdeal::SetEnbRrcSapProvider(), ns3::LteUeRrcProtocolReal::SetEnbRrcSapProvider(), ns3::SixLowPanIphc::SetFlowLabel(), ns3::ThreeGppPropagationLossModel::SetFrequency(), ns3::ThreeGppChannelModel::SetFrequency(), ns3::MobilityBuildingInfo::SetIndoor(), ns3::Ipv6ExtensionHeader::SetLength(), ns3::LSigHeader::SetLength(), ns3::ThreeGppHttpVariables::SetMainObjectSizeMean(), ns3::SixLowPanNetDevice::SetMtu(), ns3::WifiPhy::SetNumberOfAntennas(), ns3::ThreeGppHttpVariables::SetNumOfEmbeddedObjectsScale(), ns3::ThreeGppHttpVariables::SetNumOfEmbeddedObjectsShape(), ns3::InfrastructureWifiMac::SetPcfSupported(), ns3::UanNetDevice::SetPromiscReceiveCallback(), ns3::JakesProcess::SetPropagationLossModel(), ns3::UanHeaderCommon::SetProtocolNumber(), ns3::InfrastructureWifiMac::SetQosSupported(), ns3::DsssSigHeader::SetRate(), ns3::LSigHeader::SetRate(), ns3::MeshPointDevice::SetRoutingProtocol(), ns3::ThreeGppChannelModel::SetScenario(), ns3::TcpTxBuffer::SetSentListLost(), ns3::SixLowPanIphc::SetSrcContextId(), ns3::LteSpectrumPhy::SetTransmissionMode(), ns3::Txop::SetTxopLimit(), ns3::EpcPgwApplication::SetUeAddress(), ns3::EpcPgwApplication::SetUeAddress6(), ns3::LteEnbRrcProtocolIdeal::SetUeRrcSapProvider(), ns3::LteEnbRrcProtocolReal::SetUeRrcSapProvider(), ns3::UeManager::SetupDataRadioBearer(), ns3::BooleanProbe::SetValueByPath(), ns3::DoubleProbe::SetValueByPath(), ns3::PacketProbe::SetValueByPath(), ns3::ApplicationPacketProbe::SetValueByPath(), ns3::Ipv4PacketProbe::SetValueByPath(), ns3::Ipv6PacketProbe::SetValueByPath(), ns3::TimeProbe::SetValueByPath(), ns3::Uinteger16Probe::SetValueByPath(), ns3::Uinteger32Probe::SetValueByPath(), ns3::Uinteger8Probe::SetValueByPath(), ns3::GlobalRouteManagerImpl::SPFAddASExternal(), ns3::GlobalRouteManagerImpl::SPFCalculate(), ns3::GlobalRouteManagerImpl::SPFIntraAddRouter(), ns3::GlobalRouteManagerImpl::SPFIntraAddStub(), ns3::GlobalRouteManagerImpl::SPFIntraAddTransit(), ns3::GlobalRouteManagerImpl::SPFNext(), ns3::dsr::DsrRouting::Start(), ns3::LteTestRrc::Start(), ns3::FdReader::Start(), ns3::ThreeGppHttpServer::StartApplication(), ns3::UdpClient::StartApplication(), ns3::UdpEchoClient::StartApplication(), ns3::UdpTraceClient::StartApplication(), ns3::DhcpClient::StartApplication(), ns3::DhcpServer::StartApplication(), ns3::PacketSocketClient::StartApplication(), ns3::PacketSocketServer::StartApplication(), ns3::SSLinkManager::StartContentionResolution(), ns3::LteSpectrumPhy::StartRxDlCtrl(), ns3::SSLinkManager::StartScanning(), ns3::WimaxPhy::StartScanning(), ns3::LteEnbPhy::StartSubFrame(), ns3::MultiModelSpectrumChannel::StartTx(), ns3::SingleModelSpectrumChannel::StartTx(), ns3::SpectrumWifiPhy::StartTx(), ns3::LteUePhy::SubframeIndication(), ns3::UanPdp::SumTapsC(), ns3::UanPdp::SumTapsFromMaxC(), ns3::UanPdp::SumTapsFromMaxNc(), ns3::UanPdp::SumTapsNc(), ns3::QueueDisc::Transmit(), ns3::CsmaNetDevice::TransmitAbort(), ns3::PointToPointNetDevice::TransmitComplete(), ns3::CsmaNetDevice::TransmitCompleteEvent(), ns3::CsmaNetDevice::TransmitReadyEvent(), ns3::CsmaNetDevice::TransmitStart(), ns3::PointToPointNetDevice::TransmitStart(), ns3::int64x64_t::Udiv(), ns3::TcpTxBuffer::Update(), ns3::Ipv4L3Protocol::UpdateDuplicate(), ns3::LteUeRrc::VarMeasReportListAdd(), ns3::AnimationInterface::WavePhyRxBeginTrace(), ns3::AnimationInterface::WifiPhyRxBeginTrace(), ns3::Buffer::Iterator::Write(), ns3::RadioBearerStatsCalculator::WriteDlResults(), ns3::Buffer::Iterator::WriteHtonU16(), ns3::Buffer::Iterator::WriteHtonU32(), ns3::ThreeGppHttpServerTxBuffer::WriteNewObject(), ns3::Buffer::Iterator::WriteU8(), and ns3::RadioBearerStatsCalculator::WriteUlResults().
Variable Documentation
return
return
Definition at line 538 of file ipv4-address-generator.cc.