ns-3: src/internet/test/ipv6-dual-stack-test-suite.cc File Reference
ipv6-dual-stack-test-suite.cc File Reference
#include "ns3/test.h"
#include "ns3/socket-factory.h"
#include "ns3/tcp-socket-factory.h"
#include "ns3/simulator.h"
#include "ns3/simple-channel.h"
#include "ns3/simple-net-device.h"
#include "ns3/config.h"
#include "ns3/ipv4-static-routing.h"
#include "ns3/ipv4-list-routing.h"
#include "ns3/ipv6-static-routing.h"
#include "ns3/ipv6-list-routing.h"
#include "ns3/node.h"
#include "ns3/inet-socket-address.h"
#include "ns3/inet6-socket-address.h"
#include "ns3/uinteger.h"
#include "ns3/log.h"
#include "ns3/arp-l3-protocol.h"
#include "ns3/ipv4-l3-protocol.h"
#include "ns3/ipv6-l3-protocol.h"
#include "ns3/icmpv4-l4-protocol.h"
#include "ns3/icmpv6-l4-protocol.h"
#include "ns3/udp-l4-protocol.h"
#include "ns3/tcp-l4-protocol.h"
#include "ns3/traffic-control-layer.h"
#include <string>
Classes
class DualStackTestCase
IPv6 dual stack Test.
class Ipv6DualStackTestSuite
IPv6 dual stack TestSuite.
Functions
Ptr< SimpleNetDevice > AddSimpleNetDevice (Ptr< Node > node, Ipv4Address v4Addr, Ipv4Mask v4Mask, Ipv6Address v6Addr, Ipv6Prefix v6Prefix)
Ptr< Node > CreateDualStackNode ()
Variables
static Ipv6DualStackTestSuite g_ipv6DualStackTestSuite
Static variable for test initialization.
Function Documentation
AddSimpleNetDevice()
Ptr<SimpleNetDevice> AddSimpleNetDevice (Ptr< Node > node, Ipv4Address v4Addr, Ipv4Mask v4Mask, Ipv6Address v6Addr, Ipv6Prefix v6Prefix)
Definition at line 175 of file ipv6-dual-stack-test-suite.cc.
References ns3::Ipv4::AddAddress(), ns3::Ipv6::AddAddress(), ns3::Node::AddDevice(), ns3::Ipv4::AddInterface(), ns3::Ipv6::AddInterface(), ns3::Mac48Address::Allocate(), ns3::Mac48Address::ConvertFrom(), ns3::Object::GetObject(), ns3::SimpleNetDevice::SetAddress(), ns3::Ipv4::SetUp(), and ns3::Ipv6::SetUp().
Referenced by DualStackTestCase::SetUpSim().
CreateDualStackNode()
Ptr<Node> CreateDualStackNode ()
Definition at line 119 of file ipv6-dual-stack-test-suite.cc.
References ns3::Ipv4ListRouting::AddRoutingProtocol(), ns3::Ipv6ListRouting::AddRoutingProtocol(), ns3::Object::AggregateObject(), ns3::Ipv6L3Protocol::RegisterExtensions(), ns3::Ipv6L3Protocol::RegisterOptions(), ns3::Ipv4L3Protocol::SetRoutingProtocol(), ns3::Ipv6L3Protocol::SetRoutingProtocol(), and ns3::ArpL3Protocol::SetTrafficControl().
Referenced by DualStackTestCase::SetUpSim().
Variable Documentation
g_ipv6DualStackTestSuite
Ipv6DualStackTestSuite g_ipv6DualStackTestSuite static
Static variable for test initialization.
Definition at line 353 of file ipv6-dual-stack-test-suite.cc.