ns-3: src/lte/examples/lena-distributed-ffr.cc File Reference
lena-distributed-ffr.cc File Reference
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/mobility-module.h"
#include "ns3/lte-module.h"
#include "ns3/spectrum-module.h"
#include "ns3/config-store.h"
#include <ns3/buildings-helper.h>
#include "ns3/point-to-point-epc-helper.h"
#include "ns3/internet-module.h"
#include "ns3/point-to-point-module.h"
#include "ns3/applications-module.h"
#include "ns3/log.h"
Functions
void PrintGnuplottableEnbListToFile (std::string filename)
void PrintGnuplottableUeListToFile (std::string filename)
Function Documentation
PrintGnuplottableEnbListToFile()
void PrintGnuplottableEnbListToFile (std::string filename)
Definition at line 68 of file lena-distributed-ffr.cc.
References ns3::NodeList::Begin(), ns3::NodeList::End(), ns3::LteEnbNetDevice::GetCellId(), ns3::Node::GetDevice(), ns3::Node::GetNDevices(), ns3::Object::GetObject(), GetPosition(), and NS_LOG_ERROR.
PrintGnuplottableUeListToFile()
void PrintGnuplottableUeListToFile (std::string filename)
Definition at line 40 of file lena-distributed-ffr.cc.
References ns3::NodeList::Begin(), ns3::NodeList::End(), ns3::Node::GetDevice(), ns3::LteUeNetDevice::GetImsi(), ns3::Node::GetNDevices(), ns3::Object::GetObject(), GetPosition(), and NS_LOG_ERROR.