ns-3: src/lte/examples/lena-x2-handover.cc File Reference
lena-x2-handover.cc File Reference
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/mobility-module.h"
#include "ns3/lte-module.h"
#include "ns3/applications-module.h"
#include "ns3/point-to-point-module.h"
#include "ns3/config-store-module.h"
Functions
void NotifyConnectionEstablishedEnb (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
void NotifyConnectionEstablishedUe (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
void NotifyHandoverEndOkEnb (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
void NotifyHandoverEndOkUe (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
void NotifyHandoverStartEnb (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti, uint16_t targetCellId)
void NotifyHandoverStartUe (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti, uint16_t targetCellId)
Function Documentation
NotifyConnectionEstablishedEnb()
void NotifyConnectionEstablishedEnb (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
Definition at line 76 of file lena-x2-handover.cc.
References ns3::Time::GetSeconds(), and ns3::Simulator::Now().
NotifyConnectionEstablishedUe()
void NotifyConnectionEstablishedUe (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
Definition at line 35 of file lena-x2-handover.cc.
References ns3::Time::GetSeconds(), and ns3::Simulator::Now().
NotifyHandoverEndOkEnb()
void NotifyHandoverEndOkEnb (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
Definition at line 104 of file lena-x2-handover.cc.
References ns3::Time::GetSeconds(), and ns3::Simulator::Now().
NotifyHandoverEndOkUe()
void NotifyHandoverEndOkUe (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
Definition at line 63 of file lena-x2-handover.cc.
References ns3::Time::GetSeconds(), and ns3::Simulator::Now().
NotifyHandoverStartEnb()
void NotifyHandoverStartEnb (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti, uint16_t targetCellId)
Definition at line 89 of file lena-x2-handover.cc.
References ns3::Time::GetSeconds(), and ns3::Simulator::Now().
NotifyHandoverStartUe()
void NotifyHandoverStartUe (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti, uint16_t targetCellId)
Definition at line 48 of file lena-x2-handover.cc.
References ns3::Time::GetSeconds(), and ns3::Simulator::Now().