ns-3: src/lte/examples/lena-cc-helper.cc File Reference
lena-cc-helper.cc File Reference
#include "ns3/core-module.h"
#include "ns3/config-store.h"
#include <ns3/buildings-helper.h>
#include "ns3/component-carrier.h"
#include "ns3/cc-helper.h"
Functions
void Print (ComponentCarrier cc)
Function Documentation
Print()
void Print (ComponentCarrier cc)
Definition at line 69 of file lena-cc-helper.cc.
References ns3::ComponentCarrier::GetDlBandwidth(), ns3::ComponentCarrier::GetDlEarfcn(), ns3::ComponentCarrier::GetUlBandwidth(), ns3::ComponentCarrier::GetUlEarfcn(), and ns3::ComponentCarrier::IsPrimary().