ns-3: src/lr-wpan/examples/lr-wpan-phy-test.cc File Reference
lr-wpan-phy-test.cc File Reference
#include <ns3/log.h>
#include <ns3/test.h>
#include <ns3/command-line.h>
#include <ns3/packet.h>
#include <ns3/lr-wpan-phy.h>
#include <ns3/lr-wpan-mac.h>
#include <ns3/simulator.h>
#include <ns3/single-model-spectrum-channel.h>
#include <ns3/constant-position-mobility-model.h>
Functions
void GetSetTRXStateConfirm (LrWpanPhyEnumeration status)
void ReceivePdDataIndication (uint32_t psduLength, Ptr< Packet > p, uint8_t lqi)
void SendOnePacket (Ptr< LrWpanPhy > sender, Ptr< LrWpanPhy > receiver)
Function Documentation
GetSetTRXStateConfirm()
void GetSetTRXStateConfirm (LrWpanPhyEnumeration status)
Definition at line 32 of file lr-wpan-phy-test.cc.
References ns3::Simulator::Now(), and NS_LOG_UNCOND.
ReceivePdDataIndication()
void ReceivePdDataIndication (uint32_t psduLength, Ptr< Packet > p, uint8_t lqi)
Definition at line 39 of file lr-wpan-phy-test.cc.
References ns3::Simulator::Now(), and NS_LOG_UNCOND.
SendOnePacket()
void SendOnePacket (Ptr< LrWpanPhy > sender, Ptr< LrWpanPhy > receiver)
Definition at line 48 of file lr-wpan-phy-test.cc.
References ns3::Packet::GetSize(), sample-rng-plot::n, and ns3::LrWpanPhy::PdDataRequest().