ns-3: src/lte/test/lte-test-ue-measurements.cc File Reference
lte-test-ue-measurements.cc File Reference
#include <ns3/simulator.h>
#include <ns3/log.h>
#include <ns3/callback.h>
#include <ns3/config.h>
#include <ns3/string.h>
#include <ns3/double.h>
#include <ns3/enum.h>
#include <ns3/boolean.h>
#include <ns3/mobility-helper.h>
#include <ns3/lte-helper.h>
#include <ns3/point-to-point-epc-helper.h>
#include <ns3/internet-stack-helper.h>
#include <ns3/point-to-point-helper.h>
#include <ns3/ipv4-address-helper.h>
#include <ns3/ipv4-static-routing-helper.h>
#include <ns3/node-container.h>
#include <ns3/net-device-container.h>
#include <ns3/ipv4-interface-container.h>
#include <ns3/ff-mac-scheduler.h>
#include <ns3/lte-enb-net-device.h>
#include <ns3/lte-enb-phy.h>
#include <ns3/lte-enb-rrc.h>
#include <ns3/lte-ue-net-device.h>
#include <ns3/lte-ue-phy.h>
#include <ns3/lte-ue-rrc.h>
#include "lte-test-ue-measurements.h"
#include <ns3/lte-common.h>
Functions
std::vector< Time > & operator<< (std::vector< Time > &v, const uint64_t &ms)
std::vector< uint8_t > & operator<< (std::vector< uint8_t > &v, const uint8_t &range)
void RecvMeasurementReportCallback (LteUeMeasurementsTestCase *testcase, std::string path, uint64_t imsi, uint16_t cellId, uint16_t rnti, LteRrcSap::MeasurementReport meas)
void ReportUeMeasurementsCallback (LteUeMeasurementsTestCase *testcase, std::string path, uint16_t rnti, uint16_t cellId, double rsrp, double rsrq, bool servingCell, uint8_t componentCarrierId)
Variables
static LteUeMeasurementsHandoverTestSuite lteUeMeasurementsHandoverTestSuite
static LteUeMeasurementsPiecewiseTestSuite1 lteUeMeasurementsPiecewiseTestSuite1
static LteUeMeasurementsPiecewiseTestSuite2 lteUeMeasurementsPiecewiseTestSuite2
static LteUeMeasurementsTestSuite lteUeMeasurementsTestSuite
Function Documentation
operator<<() [1/2]
std::vector<Time>& operator<< (std::vector< Time > & v, const uint64_t & ms)
Definition at line 243 of file lte-test-ue-measurements.cc.
operator<<() [2/2]
std::vector<uint8_t>& operator<< (std::vector< uint8_t > & v, const uint8_t & range)
Definition at line 243 of file lte-test-ue-measurements.cc.
References LteUeMeasurementsTestCase::m_rsrpDbmUeNeighborCell, LteUeMeasurementsTestCase::m_rsrpDbmUeServingCell, LteUeMeasurementsTestCase::m_rsrqDbUeNeighborCell, LteUeMeasurementsTestCase::m_rsrqDbUeServingCell, ns3::LteRrcSap::MeasurementReport::measResults, ns3::MilliSeconds(), ns3::Now(), NS_LOG_DEBUG, NS_TEST_ASSERT_MSG_EQ, ns3::LteRrcSap::MeasResults::rsrpResult, and ns3::LteRrcSap::MeasResults::rsrqResult.
RecvMeasurementReportCallback()
void RecvMeasurementReportCallback (LteUeMeasurementsTestCase * testcase, std::string path, uint64_t imsi, uint16_t cellId, uint16_t rnti, LteRrcSap::MeasurementReport meas)
Definition at line 71 of file lte-test-ue-measurements.cc.
References LteUeMeasurementsTestCase::RecvMeasurementReport().
Referenced by LteUeMeasurementsTestCase::DoRun().
ReportUeMeasurementsCallback()
void ReportUeMeasurementsCallback (LteUeMeasurementsTestCase * testcase, std::string path, uint16_t rnti, uint16_t cellId, double rsrp, double rsrq, bool servingCell, uint8_t componentCarrierId)
Definition at line 63 of file lte-test-ue-measurements.cc.
References LteUeMeasurementsTestCase::ReportUeMeasurements().
Referenced by LteUeMeasurementsTestCase::DoRun().
Variable Documentation
lteUeMeasurementsHandoverTestSuite
LteUeMeasurementsHandoverTestSuite lteUeMeasurementsHandoverTestSuite static
Definition at line 1644 of file lte-test-ue-measurements.cc.
lteUeMeasurementsPiecewiseTestSuite1
LteUeMeasurementsPiecewiseTestSuite1 lteUeMeasurementsPiecewiseTestSuite1 static
Definition at line 513 of file lte-test-ue-measurements.cc.
lteUeMeasurementsPiecewiseTestSuite2
LteUeMeasurementsPiecewiseTestSuite2 lteUeMeasurementsPiecewiseTestSuite2 static
Definition at line 1098 of file lte-test-ue-measurements.cc.
lteUeMeasurementsTestSuite
LteUeMeasurementsTestSuite lteUeMeasurementsTestSuite static
Definition at line 107 of file lte-test-ue-measurements.cc.