ns-3: src/lte/test/lte-test-carrier-aggregation.cc File Reference
lte-test-carrier-aggregation.cc File Reference
#include <ns3/object.h>
#include <ns3/spectrum-interference.h>
#include <ns3/spectrum-error-model.h>
#include <ns3/log.h>
#include <ns3/test.h>
#include <ns3/simulator.h>
#include <ns3/packet.h>
#include <ns3/ptr.h>
#include <iostream>
#include "ns3/radio-bearer-stats-calculator.h"
#include <ns3/constant-position-mobility-model.h>
#include "ns3/ff-mac-scheduler.h"
#include <ns3/eps-bearer.h>
#include <ns3/node-container.h>
#include <ns3/mobility-helper.h>
#include <ns3/net-device-container.h>
#include <ns3/lte-ue-net-device.h>
#include <ns3/lte-enb-net-device.h>
#include <ns3/lte-ue-rrc.h>
#include <ns3/lte-helper.h>
#include "ns3/string.h"
#include "ns3/double.h"
#include <ns3/lte-enb-phy.h>
#include <ns3/lte-ue-phy.h>
#include <ns3/boolean.h>
#include <ns3/enum.h>
#include <ns3/config-store-module.h>
#include <errno.h>
#include "lte-test-carrier-aggregation.h"
Functions
void LteTestDlSchedulingCallback (CarrierAggregationTestCase *testcase, std::string path, DlSchedulingCallbackInfo dlInfo)
void LteTestUlSchedulingCallback (CarrierAggregationTestCase *testcase, std::string path, uint32_t frameNo, uint32_t subframeNo, uint16_t rnti, uint8_t mcs, uint16_t sizeTb, uint8_t ccId)
Variables
const std::string dlResultsFileName = "carrier_aggregation_results_dl.txt"
static TestCarrierAggregationSuite lenaTestRrFfMacSchedulerSuite
const std::string ulResultsFileName = "carrier_aggregation_results_ul.txt"
Function Documentation
LteTestDlSchedulingCallback()
void LteTestDlSchedulingCallback (CarrierAggregationTestCase * testcase, std::string path, DlSchedulingCallbackInfo dlInfo)
Definition at line 63 of file lte-test-carrier-aggregation.cc.
References CarrierAggregationTestCase::DlScheduling().
Referenced by CarrierAggregationTestCase::DoRun().
LteTestUlSchedulingCallback()
void LteTestUlSchedulingCallback (CarrierAggregationTestCase * testcase, std::string path, uint32_t frameNo, uint32_t subframeNo, uint16_t rnti, uint8_t mcs, uint16_t sizeTb, uint8_t ccId)
Definition at line 69 of file lte-test-carrier-aggregation.cc.
References CarrierAggregationTestCase::UlScheduling().
Referenced by CarrierAggregationTestCase::DoRun().
Variable Documentation
dlResultsFileName
const std::string dlResultsFileName = "carrier_aggregation_results_dl.txt"
Definition at line 58 of file lte-test-carrier-aggregation.cc.
Referenced by TestCarrierAggregationSuite::TestCarrierAggregationSuite(), and CarrierAggregationTestCase::WriteResultToFile().
lenaTestRrFfMacSchedulerSuite
TestCarrierAggregationSuite lenaTestRrFfMacSchedulerSuite static
Definition at line 245 of file lte-test-carrier-aggregation.cc.
ulResultsFileName
const std::string ulResultsFileName = "carrier_aggregation_results_ul.txt"
Definition at line 59 of file lte-test-carrier-aggregation.cc.
Referenced by TestCarrierAggregationSuite::TestCarrierAggregationSuite(), and CarrierAggregationTestCase::WriteResultToFile().