ns-3: src/lte/test/lte-test-downlink-power-control.cc File Reference
lte-test-downlink-power-control.cc File Reference
#include <ns3/simulator.h>
#include <ns3/log.h>
#include <ns3/callback.h>
#include <ns3/config.h>
#include <ns3/string.h>
#include <ns3/double.h>
#include <ns3/enum.h>
#include <ns3/boolean.h>
#include <ns3/pointer.h>
#include "ns3/mobility-helper.h"
#include "ns3/lte-helper.h"
#include <ns3/ff-mac-scheduler.h>
#include <ns3/lte-enb-net-device.h>
#include <ns3/lte-enb-phy.h>
#include <ns3/lte-enb-rrc.h>
#include <ns3/lte-ue-net-device.h>
#include <ns3/lte-ue-phy.h>
#include <ns3/lte-ue-rrc.h>
#include "lte-ffr-simple.h"
#include <ns3/lte-common.h>
#include <ns3/lte-chunk-processor.h>
#include "lte-test-downlink-power-control.h"
#include <ns3/lte-rrc-sap.h>
Functions
void ChangePdschConfigDedicatedCallback (LteDownlinkPowerControlRrcConnectionReconfigurationTestCase *testcase, std::string context, uint16_t rnti, uint8_t pa)
void NotifyConnectionReconfigurationEnb (LteDownlinkPowerControlRrcConnectionReconfigurationTestCase *testcase, std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti)
void NotifyConnectionReconfigurationUe (LteDownlinkPowerControlRrcConnectionReconfigurationTestCase *testcase, std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti)
Variables
static LteDownlinkPowerControlTestSuite lteDownlinkPowerControlTestSuite
Function Documentation
ChangePdschConfigDedicatedCallback()
void ChangePdschConfigDedicatedCallback (LteDownlinkPowerControlRrcConnectionReconfigurationTestCase * testcase, std::string context, uint16_t rnti, uint8_t pa)
Definition at line 489 of file lte-test-downlink-power-control.cc.
References LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::ChangePdschConfigDedicated().
Referenced by LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::DoRun().
NotifyConnectionReconfigurationEnb()
void NotifyConnectionReconfigurationEnb (LteDownlinkPowerControlRrcConnectionReconfigurationTestCase * testcase, std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti)
Definition at line 482 of file lte-test-downlink-power-control.cc.
References LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::ConnectionReconfigurationEnb().
Referenced by LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::DoRun().
NotifyConnectionReconfigurationUe()
void NotifyConnectionReconfigurationUe (LteDownlinkPowerControlRrcConnectionReconfigurationTestCase * testcase, std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti)
Definition at line 475 of file lte-test-downlink-power-control.cc.
References LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::ConnectionReconfigurationUe().
Referenced by LteDownlinkPowerControlRrcConnectionReconfigurationTestCase::DoRun().
Variable Documentation
lteDownlinkPowerControlTestSuite
LteDownlinkPowerControlTestSuite lteDownlinkPowerControlTestSuite static
Definition at line 351 of file lte-test-downlink-power-control.cc.