ns-3: src/propagation/examples/main-propagation-loss.cc File Reference
main-propagation-loss.cc File Reference
#include "ns3/propagation-loss-model.h"
#include "ns3/jakes-propagation-loss-model.h"
#include "ns3/constant-position-mobility-model.h"
#include "ns3/config.h"
#include "ns3/command-line.h"
#include "ns3/string.h"
#include "ns3/boolean.h"
#include "ns3/double.h"
#include "ns3/pointer.h"
#include "ns3/gnuplot.h"
#include "ns3/simulator.h"
#include <map>
Functions
static double dround (double number, double precision)
Round a double number to the given precision.
static Gnuplot TestDeterministic (Ptr< PropagationLossModel > model)
static Gnuplot TestDeterministicByTime (Ptr< PropagationLossModel > model, Time timeStep=Seconds(0.001), Time timeTotal=Seconds(1.0), double distance=100.0)
static Gnuplot TestProbabilistic (Ptr< PropagationLossModel > model, unsigned int samples=100000)
Function Documentation
dround()
static double dround (double number, double precision) static
Round a double number to the given precision.
e.g. dround(0.234, 0.1) = 0.2 and dround(0.257, 0.1) = 0.3
Definition at line 40 of file main-propagation-loss.cc.
Referenced by TestProbabilistic().
TestDeterministic()
static Gnuplot TestDeterministic (Ptr< PropagationLossModel > model) static
Definition at line 56 of file main-propagation-loss.cc.
References ns3::Gnuplot2dDataset::Add(), ns3::Gnuplot::AddDataset(), ns3::Gnuplot::AppendExtra(), ns3::PropagationLossModel::CalcRxPower(), ns3::Gnuplot2dDataset::LINES, ns3::Simulator::Run(), ns3::Seconds(), ns3::MobilityModel::SetPosition(), ns3::Gnuplot2dDataset::SetStyle(), ns3::GnuplotDataset::SetTitle(), and ns3::Simulator::Stop().
TestDeterministicByTime()
static Gnuplot TestDeterministicByTime (Ptr< PropagationLossModel > model, Time timeStep = Seconds (0.001), Time timeTotal = Seconds (1.0), double distance = 100.0) static
Definition at line 171 of file main-propagation-loss.cc.
References ns3::Gnuplot2dDataset::Add(), ns3::Gnuplot::AddDataset(), ns3::Gnuplot::AppendExtra(), ns3::PropagationLossModel::CalcRxPower(), ns3::Time::GetSeconds(), ns3::Gnuplot2dDataset::LINES, ns3::Simulator::Now(), ns3::Simulator::Run(), ns3::MobilityModel::SetPosition(), ns3::Gnuplot2dDataset::SetStyle(), ns3::GnuplotDataset::SetTitle(), visualizer.core::start(), and ns3::Simulator::Stop().
TestProbabilistic()
static Gnuplot TestProbabilistic (Ptr< PropagationLossModel > model, unsigned int samples = 100000) static
Definition at line 102 of file main-propagation-loss.cc.
References ns3::Gnuplot3dDataset::Add(), ns3::Gnuplot::AddDataset(), ns3::Gnuplot3dDataset::AddEmptyLine(), ns3::Gnuplot::AppendExtra(), ns3::PropagationLossModel::CalcRxPower(), dround(), ns3::Simulator::Run(), ns3::Seconds(), ns3::GnuplotDataset::SetExtra(), ns3::MobilityModel::SetPosition(), ns3::Gnuplot3dDataset::SetStyle(), ns3::GnuplotDataset::SetTitle(), and ns3::Simulator::Stop().