ns-3: examples/routing/manet-routing-compare.cc File Reference
manet-routing-compare.cc File Reference
#include <fstream>
#include <iostream>
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/mobility-module.h"
#include "ns3/aodv-module.h"
#include "ns3/olsr-module.h"
#include "ns3/dsdv-module.h"
#include "ns3/dsr-module.h"
#include "ns3/applications-module.h"
#include "ns3/yans-wifi-helper.h"
Classes
class RoutingExperiment
Functions
static std::string PrintReceivedPacket (Ptr< Socket > socket, Ptr< Packet > packet, Address senderAddress)
Function Documentation
PrintReceivedPacket()
static std::string PrintReceivedPacket (Ptr< Socket > socket, Ptr< Packet > packet, Address senderAddress) inline static
Definition at line 123 of file manet-routing-compare.cc.
References ns3::Node::GetId(), ns3::InetSocketAddress::GetIpv4(), ns3::Socket::GetNode(), ns3::Time::GetSeconds(), and ns3::Now().
Referenced by RoutingExperiment::ReceivePacket().