ns-3: check-style Namespace Reference
check-style Namespace Reference
Classes
class Patch
Patch class.
class PatchChunk
PatchChunk class.
class PatchChunkLine
PatchChunkLine class.
Functions
def copy_file (filename)
def git_modified_files ()
def indent (source, debug, level)
def indent_files (files, diff=False, debug=False, level=0, inplace=False)
def parse_patchset (generator)
def remove_trailing_whitespace_changes (patch_generator)
def run_as_main ()
def uncrustify_config_file (level)
Function Documentation
copy_file()
def check-style.copy_file (filename)
Definition at line 25 of file check-style.py.
git_modified_files()
def check-style.git_modified_files ()
Definition at line 13 of file check-style.py.
Referenced by run_as_main().
indent()
def check-style.indent (source, debug, level)
Definition at line 438 of file check-style.py.
References remove_trailing_whitespace_changes(), and uncrustify_config_file().
Referenced by indent_files(), ns3::Ipv4FlowClassifier.SerializeToXmlStream(), ns3::Ipv6FlowClassifier.SerializeToXmlStream(), ns3::FlowMonitorHelper.SerializeToXmlStream(), ns3::FlowMonitor.SerializeToXmlStream(), ns3::Histogram.SerializeToXmlStream(), ns3::FlowProbe.SerializeToXmlStream(), ns3::FlowMonitorHelper.SerializeToXmlString(), and ns3::FlowMonitor.SerializeToXmlString().
indent_files()
def check-style.indent_files (files, diff = False, debug = False, level = 0, inplace = False)
Definition at line 501 of file check-style.py.
References indent(), and print.
Referenced by run_as_main().
parse_patchset()
def check-style.parse_patchset (generator)
Definition at line 373 of file check-style.py.
Referenced by remove_trailing_whitespace_changes().
remove_trailing_whitespace_changes()
def check-style.remove_trailing_whitespace_changes (patch_generator)
Definition at line 419 of file check-style.py.
References parse_patchset().
Referenced by indent().
run_as_main()
def check-style.run_as_main ()
Definition at line 532 of file check-style.py.
References git_modified_files(), indent_files(), and print.
uncrustify_config_file()
def check-style.uncrustify_config_file (level)
Definition at line 36 of file check-style.py.
Referenced by indent().