ns-3: anonymous_namespace{random-variable-stream-test-suite.cc} Namespace Reference
anonymous_namespace{random-variable-stream-test-suite.cc} Namespace Reference
Functions
void FillHistoRangeUniformly (double *array, uint32_t n, double start, double end)
void SetTestSuiteSeed (void)
Variables
bool seedSet = false
Function Documentation
FillHistoRangeUniformly()
void anonymous_namespace{random-variable-stream-test-suite.cc}::FillHistoRangeUniformly (double * array, uint32_t n, double start, double end)
Definition at line 48 of file random-variable-stream-test-suite.cc.
References sample-rng-plot::n, and visualizer.core::start().
SetTestSuiteSeed()
void anonymous_namespace{random-variable-stream-test-suite.cc}::SetTestSuiteSeed (void)
Definition at line 88 of file random-variable-stream-test-suite.cc.
References ns3::RngSeedManager::GetRun(), ns3::RngSeedManager::GetSeed(), NS_LOG_DEBUG, seedSet, and ns3::RngSeedManager::SetSeed().
Referenced by RandomVariableStreamUniformTestCase::DoRun(), RandomVariableStreamUniformAntitheticTestCase::DoRun(), RandomVariableStreamConstantTestCase::DoRun(), RandomVariableStreamSequentialTestCase::DoRun(), RandomVariableStreamNormalTestCase::DoRun(), RandomVariableStreamNormalAntitheticTestCase::DoRun(), RandomVariableStreamExponentialTestCase::DoRun(), RandomVariableStreamExponentialAntitheticTestCase::DoRun(), RandomVariableStreamParetoTestCase::DoRun(), RandomVariableStreamParetoAntitheticTestCase::DoRun(), RandomVariableStreamWeibullTestCase::DoRun(), RandomVariableStreamWeibullAntitheticTestCase::DoRun(), RandomVariableStreamLogNormalTestCase::DoRun(), RandomVariableStreamLogNormalAntitheticTestCase::DoRun(), RandomVariableStreamGammaTestCase::DoRun(), RandomVariableStreamGammaAntitheticTestCase::DoRun(), RandomVariableStreamErlangTestCase::DoRun(), RandomVariableStreamErlangAntitheticTestCase::DoRun(), RandomVariableStreamZipfTestCase::DoRun(), RandomVariableStreamZipfAntitheticTestCase::DoRun(), RandomVariableStreamZetaTestCase::DoRun(), RandomVariableStreamZetaAntitheticTestCase::DoRun(), RandomVariableStreamDeterministicTestCase::DoRun(), RandomVariableStreamEmpiricalTestCase::DoRun(), and RandomVariableStreamEmpiricalAntitheticTestCase::DoRun().
Variable Documentation
seedSet
bool anonymous_namespace{random-variable-stream-test-suite.cc}::seedSet = false
Definition at line 60 of file random-variable-stream-test-suite.cc.
Referenced by SetTestSuiteSeed().