ns-3: ns3::internal Namespace Reference
ns3::internal Namespace Reference
Namespace for implementation details.
Classes
class ObjectPtrContainerChecker
ObjectPtrContainerChecker implementation class.
class PointerChecker
PointerChecker implementation.
Functions
Ptr< const AttributeChecker > MakeDoubleChecker (double min, double max, std::string name)
Ptr< const AttributeChecker > MakeIntegerChecker (int64_t min, int64_t max, std::string name)
Ptr< const AttributeChecker > MakeUintegerChecker (uint64_t min, uint64_t max, std::string name)
Detailed Description
Namespace for implementation details.
Function Documentation
MakeDoubleChecker()
Ptr< const AttributeChecker > ns3::internal::MakeDoubleChecker (double min, double max, std::string name)
Make a Double attribute checker with embedded numeric type name.
Parameters
[in] min The minimum allowed value.
[in] max The maximum allowed value.
[in] name The original type name ("float", "double").
Returns
The AttributeChecker.
Definition at line 49 of file double.cc.
References ns3::Copy(), ns3::Create(), ns3::DoubleValue::Get(), ns3::max(), ns3::min(), NS_LOG_FUNCTION, and NS_LOG_FUNCTION_NOARGS.
MakeIntegerChecker()
Ptr< const AttributeChecker > ns3::internal::MakeIntegerChecker (int64_t min, int64_t max, std::string name)
Make an Integer attribute checker with embedded numeric type name.
Parameters
[in] min The minimum allowed value.
[in] max The maximum allowed value.
[in] name The original type name ("int8_t", "int16_t", etc.).
Returns
The AttributeChecker.
Definition at line 49 of file integer.cc.
References ns3::Copy(), ns3::Create(), ns3::IntegerValue::Get(), ns3::max(), ns3::min(), NS_LOG_FUNCTION, and NS_LOG_FUNCTION_NOARGS.
MakeUintegerChecker()
Ptr< const AttributeChecker > ns3::internal::MakeUintegerChecker (uint64_t min, uint64_t max, std::string name)
Make an Uinteger attribute checker with embedded numeric type name.
Parameters
[in] min The minimum allowed value.
[in] max The maximum allowed value.
[in] name The original type name ("uint8_t", "uint16_t", etc.).
Returns
The AttributeChecker.
Definition at line 48 of file uinteger.cc.
References ns3::Copy(), ns3::Create(), ns3::UintegerValue::Get(), ns3::max(), ns3::min(), NS_LOG_FUNCTION, and NS_LOG_FUNCTION_NOARGS.