ns-3: anonymous_namespace{sample-simulator.cc} Namespace Reference
anonymous_namespace{sample-simulator.cc} Namespace Reference
Classes
class MyModel
Simple model object to illustrate event handling.
Functions
static void CancelledEvent (void)
Simple function event handler; the corresponding event is cancelled.
static void ExampleFunction (MyModel *model)
Simple function event handler which Starts a MyModel object.
static void RandomFunction (void)
Simple function event handler; this function is called randomly.
Function Documentation
CancelledEvent()
static void anonymous_namespace{sample-simulator.cc}::CancelledEvent (void) static
Simple function event handler; the corresponding event is cancelled.
Definition at line 95 of file sample-simulator.cc.
ExampleFunction()
static void anonymous_namespace{sample-simulator.cc}::ExampleFunction (MyModel * model) static
Simple function event handler which Starts a MyModel object.
Parameters
[in] model The MyModel object to start.
Definition at line 76 of file sample-simulator.cc.
References ns3::Time::GetSeconds(), ns3::Simulator::Now(), and anonymous_namespace{sample-simulator.cc}::MyModel::Start().
RandomFunction()
static void anonymous_namespace{sample-simulator.cc}::RandomFunction (void) static
Simple function event handler; this function is called randomly.
Definition at line 87 of file sample-simulator.cc.
References ns3::Time::GetSeconds(), and ns3::Simulator::Now().