ns-3: anonymous_namespace{gnuplot-example.cc} Namespace Reference
anonymous_namespace{gnuplot-example.cc} Namespace Reference
Functions
void Create2DPlotFile ()
void Create2DPlotWithErrorBarsFile ()
void Create3DPlotFile ()
Function Documentation
Create2DPlotFile()
void anonymous_namespace{gnuplot-example.cc}::Create2DPlotFile ()
Definition at line 36 of file gnuplot-example.cc.
References ns3::Gnuplot2dDataset::Add(), ns3::Gnuplot::AddDataset(), ns3::Gnuplot::AppendExtra(), ns3::Gnuplot::GenerateOutput(), ns3::Gnuplot2dDataset::LINES_POINTS, ns3::Gnuplot::SetLegend(), ns3::Gnuplot2dDataset::SetStyle(), ns3::Gnuplot::SetTerminal(), ns3::GnuplotDataset::SetTitle(), ns3::Gnuplot::SetTitle(), and sample-rng-plot::x.
Create2DPlotWithErrorBarsFile()
void anonymous_namespace{gnuplot-example.cc}::Create2DPlotWithErrorBarsFile ()
Definition at line 102 of file gnuplot-example.cc.
References ns3::Gnuplot2dDataset::Add(), ns3::Gnuplot::AddDataset(), ns3::Gnuplot::AppendExtra(), ns3::Gnuplot::GenerateOutput(), ns3::Gnuplot2dDataset::POINTS, ns3::Gnuplot2dDataset::SetErrorBars(), ns3::Gnuplot::SetLegend(), ns3::Gnuplot2dDataset::SetStyle(), ns3::Gnuplot::SetTerminal(), ns3::GnuplotDataset::SetTitle(), ns3::Gnuplot::SetTitle(), sample-rng-plot::x, and ns3::Gnuplot2dDataset::XY.
Create3DPlotFile()
void anonymous_namespace{gnuplot-example.cc}::Create3DPlotFile ()
Definition at line 180 of file gnuplot-example.cc.
References ns3::Gnuplot3dDataset::Add(), ns3::Gnuplot::AddDataset(), ns3::Gnuplot3dDataset::AddEmptyLine(), ns3::Gnuplot::AppendExtra(), ns3::Gnuplot::GenerateOutput(), ns3::Gnuplot3dDataset::SetStyle(), ns3::Gnuplot::SetTerminal(), ns3::GnuplotDataset::SetTitle(), ns3::Gnuplot::SetTitle(), and sample-rng-plot::x.