ns-3: anonymous_namespace{gnuplot-aggregator-example.cc} Namespace Reference
anonymous_namespace{gnuplot-aggregator-example.cc} Namespace Reference
Functions
void Create2dPlot ()
Function Documentation
Create2dPlot()
void anonymous_namespace{gnuplot-aggregator-example.cc}::Create2dPlot ()
Definition at line 35 of file gnuplot-aggregator-example.cc.
References ns3::GnuplotAggregator::Add2dDataset(), ns3::DataCollectionObject::Disable(), ns3::DataCollectionObject::Enable(), ns3::GnuplotAggregator::SetLegend(), ns3::GnuplotAggregator::SetTerminal(), ns3::GnuplotAggregator::SetTitle(), and ns3::GnuplotAggregator::Write2d().