ns-3: wifi-ap Namespace Reference
wifi-ap Namespace Reference
Functions
def AdvancePosition (node)
def GetPosition (node)
def SetPosition (node, position)
Function Documentation
AdvancePosition()
def wifi-ap.AdvancePosition (node)
Definition at line 88 of file wifi-ap.py.
References GetPosition(), and SetPosition().
GetPosition()
def wifi-ap.GetPosition (node)
Definition at line 84 of file wifi-ap.py.
Referenced by AdvancePosition().
SetPosition()
def wifi-ap.SetPosition (node, position)
Definition at line 79 of file wifi-ap.py.
Referenced by AdvancePosition().