ns-3: anonymous_namespace{file-aggregator-example.cc} Namespace Reference
anonymous_namespace{file-aggregator-example.cc} Namespace Reference
Functions
void CreateCommaSeparatedFile ()
void CreateFormattedFile ()
void CreateSpaceSeparatedFile ()
Function Documentation
CreateCommaSeparatedFile()
void anonymous_namespace{file-aggregator-example.cc}::CreateCommaSeparatedFile ()
Definition at line 36 of file file-aggregator-example.cc.
References ns3::FileAggregator::COMMA_SEPARATED, ns3::DataCollectionObject::Disable(), ns3::DataCollectionObject::Enable(), and ns3::FileAggregator::Write2d().
CreateFormattedFile()
void anonymous_namespace{file-aggregator-example.cc}::CreateFormattedFile ()
Definition at line 124 of file file-aggregator-example.cc.
References ns3::DataCollectionObject::Disable(), ns3::DataCollectionObject::Enable(), ns3::FileAggregator::FORMATTED, ns3::FileAggregator::Set2dFormat(), and ns3::FileAggregator::Write2d().
CreateSpaceSeparatedFile()
void anonymous_namespace{file-aggregator-example.cc}::CreateSpaceSeparatedFile ()
Definition at line 80 of file file-aggregator-example.cc.
References ns3::DataCollectionObject::Disable(), ns3::DataCollectionObject::Enable(), and ns3::FileAggregator::Write2d().