ns-3: second Namespace Reference
second Namespace Reference
Variables
address = ns.internet.Ipv4AddressHelper()
clientApps = echoClient.Install(p2pNodes.Get(0))
cmd = ns.core.CommandLine()
csma = ns.csma.CsmaHelper()
csmaDevices = csma.Install(csmaNodes)
csmaInterfaces = address.Assign(csmaDevices)
csmaNodes = ns.network.NodeContainer()
echoClient = ns.applications.UdpEchoClientHelper(csmaInterfaces.GetAddress(nCsma), 9)
echoServer = ns.applications.UdpEchoServerHelper(9)
nCsma = int(cmd.nCsma)
p2pDevices = pointToPoint.Install(p2pNodes)
p2pInterfaces = address.Assign(p2pDevices)
p2pNodes = ns.network.NodeContainer()
pointToPoint = ns.point_to_point.PointToPointHelper()
serverApps = echoServer.Install(csmaNodes.Get(nCsma))
stack = ns.internet.InternetStackHelper()
verbose = cmd.verbose
Variable Documentation
address
second.address = ns.internet.Ipv4AddressHelper()
Definition at line 73 of file second.py.
clientApps
second.clientApps = echoClient.Install(p2pNodes.Get(0))
Definition at line 91 of file second.py.
cmd
second.cmd = ns.core.CommandLine()
Definition at line 35 of file second.py.
Referenced by ns3::CommandLine.CommandLine(), ns3::SQLiteOutput.CheckError(), RoutingExperiment.CommandSetup(), Experiment.CommandSetup(), VanetRoutingExperiment.CommandSetup(), AodvExample.Configure(), TracerouteExample.Configure(), MeshTest.Configure(), ns3::CommandLine.Copy(), ns3::tests::CommandLineBooleanTestCase.DoRun(), ns3::tests::CommandLineIntTestCase.DoRun(), ns3::tests::CommandLineUnsignedIntTestCase.DoRun(), ns3::tests::CommandLineStringTestCase.DoRun(), ns3::tests::CommandLineOrderTestCase.DoRun(), ns3::tests::CommandLineInvalidTestCase.DoRun(), ns3::tests::CommandLineNonOptionTestCase.DoRun(), ns3::SQLiteOutput.Error(), ns3.operator<<(), ns3::CommandLine.operator=(), ns3::tests::CommandLineTestCaseBase.Parse(), PrintPsr(), PrintPsrVsCollisionInterval(), PrintPsrVsDistance(), PrintSizeVsRange(), ns3::SQLiteOutput.SpinExec(), ns3::SQLiteOutput.SpinPrepare(), ns3::SQLiteOutput.WaitExec(), and ns3::SQLiteOutput.WaitPrepare().
csma
second.csma = ns.csma.CsmaHelper()
Definition at line 63 of file second.py.
Referenced by ns3::CsmaHelper.AssignStreams(), CsmaBridgeTestCase.DoRun(), CsmaBroadcastTestCase.DoRun(), CsmaMulticastTestCase.DoRun(), CsmaOneSubnetTestCase.DoRun(), CsmaPacketSocketTestCase.DoRun(), CsmaPingTestCase.DoRun(), CsmaRawIpSocketTestCase.DoRun(), CsmaStarTestCase.DoRun(), and Ns3TcpSocketTestCase2.DoRun().
csmaDevices
second.csmaDevices = csma.Install(csmaNodes)
Definition at line 67 of file second.py.
csmaInterfaces
second.csmaInterfaces = address.Assign(csmaDevices)
Definition at line 78 of file second.py.
csmaNodes
second.csmaNodes = ns.network.NodeContainer()
Definition at line 53 of file second.py.
echoClient
second.echoClient = ns.applications.UdpEchoClientHelper(csmaInterfaces.GetAddress(nCsma), 9)
Definition at line 86 of file second.py.
echoServer
second.echoServer = ns.applications.UdpEchoServerHelper(9)
Definition at line 80 of file second.py.
nCsma
int second.nCsma = int(cmd.nCsma)
Definition at line 36 of file second.py.
p2pDevices
second.p2pDevices = pointToPoint.Install(p2pNodes)
Definition at line 61 of file second.py.
p2pInterfaces
second.p2pInterfaces = address.Assign(p2pDevices)
Definition at line 75 of file second.py.
p2pNodes
second.p2pNodes = ns.network.NodeContainer()
Definition at line 50 of file second.py.
pointToPoint
second.pointToPoint = ns.point_to_point.PointToPointHelper()
Definition at line 57 of file second.py.
serverApps
second.serverApps = echoServer.Install(csmaNodes.Get(nCsma))
Definition at line 82 of file second.py.
stack
second.stack = ns.internet.InternetStackHelper()
Definition at line 69 of file second.py.
verbose
second.verbose = cmd.verbose
Definition at line 37 of file second.py.