ns-3: ns3::dot11s Namespace Reference
ns3::dot11s Namespace Reference
Classes
class AirtimeLinkMetricCalculator
Airtime link metric calculator.
class DestinationAddressUnit
Describes an address unit in PREQ information element See 7.3.2.96 for more details.
class Dot11sMeshCapability
class HwmpProtocol
Hybrid wireless mesh protocol – a mesh routing protocol defined in IEEE 802.11-2012 standard.
class HwmpProtocolMac
Interface MAC plugin for HWMP – 802.11s routing protocol.
class HwmpRtable
Routing table for HWMP – 802.11s routing protocol.
class HwmpTag
Hwmp tag implements interaction between HWMP protocol and MeshWifiMac.
class IeBeaconTiming
See 7.3.2.89 of 802.11s draft 2.07.
class IeBeaconTimingUnit
Information element describing one unit of beacon timing element.
class IeConfiguration
Describes Mesh Configuration Element see 7.3.2.86 of 802.11s draft 3.0.
class IeLinkMetricReport
a IEEE 802.11s Mesh ID 7.3.2.88 of 802.11s draft 3.0
class IeMeshId
a IEEE 802.11 Mesh ID element (Section 8.4.2.101 of IEEE 802.11-2012)
class IePeeringProtocol
Mesh Peering Protocol Identifier information element Note that it does not permit to set any value besides zero (corresponding to mesh peering management protocol)
class IePeerManagement
according to IEEE 802.11 - 2012
class IePerr
See 7.3.2.98 of 802.11s draft 2.07.
class IePrep
See 7.3.2.97 of 802.11s draft 2.07.
class IePreq
See 7.3.2.96 of 802.11s draft 2.07.
class IeRann
Root announcement (RANN) element.
class MeshHeader
Mesh Control field, see Section 8.2.4.7.3 IEEE 802.11-2012.
class PeerLink
Peer link model for 802.11s Peer Management protocol.
class PeerLinkCloseStart
802.11s Peer link close management frame
class PeerLinkConfirmStart
802.11s Peer link confirm management frame
class PeerLinkOpenStart
802.11s Peer link open management frame
class PeerManagementProtocol
802.11s Peer Management Protocol model
class PeerManagementProtocolMac
This is plugin to Mesh WiFi MAC, which implements the interface to dot11s peer management protocol: it takes proper frames from MAC-layer, extracts peer link management information element and mesh configuration element and passes it to main part of protocol.
struct RouteChange
Structure to encapsulate route change information.
Enumerations
enum dot11sAuthenticationProtocol { AUTH_NULL = 0x00, AUTH_SAE = 0x01, AUTH_IEEE = 0x02 }
enum dot11sCongestionControlMode { CONGESTION_SIGNALING = 0x01, CONGESTION_NULL = 0x00 }
enum dot11sPathSelectionMetric { METRIC_AIRTIME = 0x01 }
enum dot11sPathSelectionProtocol { PROTOCOL_HWMP = 0x01 }
enum dot11sSynchronizationProtocolIdentifier { SYNC_NEIGHBOUR_OFFSET = 0x01, SYNC_NULL = 0x00 }
enum PmpReasonCode {
REASON11S_PEERING_CANCELLED = 52, REASON11S_MESH_MAX_PEERS = 53, REASON11S_MESH_CAPABILITY_POLICY_VIOLATION = 54, REASON11S_MESH_CLOSE_RCVD = 55,
REASON11S_MESH_MAX_RETRIES = 56, REASON11S_MESH_CONFIRM_TIMEOUT = 57, REASON11S_MESH_INVALID_GTK = 58, REASON11S_MESH_INCONSISTENT_PARAMETERS = 59,
REASON11S_MESH_INVALID_SECURITY_CAPABILITY =60, REASON11S_RESERVED = 67
}
Codes used by 802.11s Peer Management Protocol.
Functions
ATTRIBUTE_HELPER_CPP (IeMeshId)
ATTRIBUTE_HELPER_HEADER (IeMeshId)
bool operator< (const IeLinkMetricReport &a, const IeLinkMetricReport &b)
std::ostream & operator<< (std::ostream &os, const IeBeaconTiming &a)
std::ostream & operator<< (std::ostream &os, const IeConfiguration &a)
std::ostream & operator<< (std::ostream &os, const IeLinkMetricReport &a)
std::ostream & operator<< (std::ostream &os, const IeMeshId &a)
std::ostream & operator<< (std::ostream &os, const IePeeringProtocol &a)
std::ostream & operator<< (std::ostream &os, const IePeerManagement &a)
std::ostream & operator<< (std::ostream &os, const IePerr &a)
std::ostream & operator<< (std::ostream &os, const IePrep &a)
std::ostream & operator<< (std::ostream &os, const IePreq &a)
std::ostream & operator<< (std::ostream &os, const IeRann &a)
bool operator== (const DestinationAddressUnit &a, const DestinationAddressUnit &b)
bool operator== (const Dot11sMeshCapability &a, const Dot11sMeshCapability &b)
bool operator== (const IeBeaconTimingUnit &a, const IeBeaconTimingUnit &b)
bool operator== (const IeConfiguration &a, const IeConfiguration &b)
bool operator== (const IeLinkMetricReport &a, const IeLinkMetricReport &b)
bool operator== (const IeMeshId &a, const IeMeshId &b)
bool operator== (const IePeerManagement &a, const IePeerManagement &b)
bool operator== (const IePerr &a, const IePerr &b)
bool operator== (const IePrep &a, const IePrep &b)
bool operator== (const IePreq &a, const IePreq &b)
bool operator== (const IeRann &a, const IeRann &b)
bool operator== (const MeshHeader &a, const MeshHeader &b)
bool operator== (const PeerLinkCloseStart &a, const PeerLinkCloseStart &b)
bool operator== (const PeerLinkConfirmStart &a, const PeerLinkConfirmStart &b)
bool operator== (const PeerLinkOpenStart &a, const PeerLinkOpenStart &b)
bool operator> (const IeLinkMetricReport &a, const IeLinkMetricReport &b)
std::istream & operator>> (std::istream &is, IeMeshId &a)
Enumeration Type Documentation
dot11sAuthenticationProtocol
enum ns3::dot11s::dot11sAuthenticationProtocol
Enumerator
AUTH_NULL
AUTH_SAE
AUTH_IEEE
Definition at line 60 of file ie-dot11s-configuration.h.
dot11sCongestionControlMode
enum ns3::dot11s::dot11sCongestionControlMode
Enumerator
CONGESTION_SIGNALING
CONGESTION_NULL
Definition at line 46 of file ie-dot11s-configuration.h.
dot11sPathSelectionMetric
enum ns3::dot11s::dot11sPathSelectionMetric
Enumerator
METRIC_AIRTIME
Definition at line 40 of file ie-dot11s-configuration.h.
dot11sPathSelectionProtocol
enum ns3::dot11s::dot11sPathSelectionProtocol
Enumerator
PROTOCOL_HWMP
Definition at line 34 of file ie-dot11s-configuration.h.
dot11sSynchronizationProtocolIdentifier
enum ns3::dot11s::dot11sSynchronizationProtocolIdentifier
Enumerator
SYNC_NEIGHBOUR_OFFSET
SYNC_NULL
Definition at line 53 of file ie-dot11s-configuration.h.
Function Documentation
ATTRIBUTE_HELPER_CPP()
ns3::dot11s::ATTRIBUTE_HELPER_CPP (IeMeshId)
ATTRIBUTE_HELPER_HEADER()
ns3::dot11s::ATTRIBUTE_HELPER_HEADER (IeMeshId)
operator<()
bool ns3::dot11s::operator< (const IeLinkMetricReport & a, const IeLinkMetricReport & b)
Parameters
a lhs
b lhs
Returns
true if equal
Definition at line 76 of file ie-dot11s-metric-report.cc.
References ns3::dot11s::IeLinkMetricReport::m_metric.
operator<<() [1/10]
std::ostream & ns3::dot11s::operator<< (std::ostream & os, const IeBeaconTiming & a)
Definition at line 214 of file ie-dot11s-beacon-timing.cc.
References ns3::dot11s::IeBeaconTiming::Print().
operator<<() [2/10]
std::ostream & ns3::dot11s::operator<< (std::ostream & os, const IeConfiguration & a)
Definition at line 212 of file ie-dot11s-configuration.cc.
References ns3::dot11s::IeConfiguration::Print().
operator<<() [3/10]
std::ostream & ns3::dot11s::operator<< (std::ostream & os, const IeLinkMetricReport & a)
Definition at line 86 of file ie-dot11s-metric-report.cc.
References ns3::dot11s::IeLinkMetricReport::Print().
operator<<() [4/10]
std::ostream & ns3::dot11s::operator<< (std::ostream & os, const IeMeshId & a)
Definition at line 137 of file ie-dot11s-id.cc.
References ns3::dot11s::IeMeshId::Print().
operator<<() [5/10]
std::ostream& ns3::dot11s::operator<< (std::ostream & os, const IePeeringProtocol & a)
Definition at line 55 of file ie-dot11s-peering-protocol.cc.
References ns3::dot11s::IePeeringProtocol::Print().
operator<<() [6/10]
std::ostream & ns3::dot11s::operator<< (std::ostream & os, const IePeerManagement & a)
Definition at line 167 of file ie-dot11s-peer-management.cc.
References ns3::dot11s::IePeerManagement::Print().
operator<<() [7/10]
std::ostream & ns3::dot11s::operator<< (std::ostream & os, const IePerr & a)
Definition at line 167 of file ie-dot11s-perr.cc.
References ns3::dot11s::IePerr::Print().
operator<<() [8/10]
std::ostream & ns3::dot11s::operator<< (std::ostream & os, const IePrep & a)
Definition at line 205 of file ie-dot11s-prep.cc.
References ns3::dot11s::IePrep::Print().
operator<<() [9/10]
std::ostream & ns3::dot11s::operator<< (std::ostream & os, const IePreq & a)
Definition at line 438 of file ie-dot11s-preq.cc.
References ns3::dot11s::IePreq::Print().
operator<<() [10/10]
std::ostream & ns3::dot11s::operator<< (std::ostream & os, const IeRann & a)
Definition at line 170 of file ie-dot11s-rann.cc.
References ns3::dot11s::IeRann::Print().
operator==() [1/15]
bool ns3::dot11s::operator== (const DestinationAddressUnit & a, const DestinationAddressUnit & b)
Parameters
a lhs
b rhs
Returns
true if equal
Definition at line 384 of file ie-dot11s-preq.cc.
References ns3::dot11s::DestinationAddressUnit::m_destinationAddress, ns3::dot11s::DestinationAddressUnit::m_destSeqNumber, ns3::dot11s::DestinationAddressUnit::m_do, ns3::dot11s::DestinationAddressUnit::m_rf, and ns3::dot11s::DestinationAddressUnit::m_usn.
operator==() [2/15]
bool ns3::dot11s::operator== (const Dot11sMeshCapability & a, const Dot11sMeshCapability & b)
Parameters
a lhs
b rhs
Returns
true if equal
Definition at line 199 of file ie-dot11s-configuration.cc.
References ns3::dot11s::Dot11sMeshCapability::acceptPeerLinks, ns3::dot11s::Dot11sMeshCapability::beaconTimingReport, ns3::dot11s::Dot11sMeshCapability::forwarding, ns3::dot11s::Dot11sMeshCapability::MCCAEnabled, ns3::dot11s::Dot11sMeshCapability::MCCASupported, ns3::dot11s::Dot11sMeshCapability::powerSaveLevel, and ns3::dot11s::Dot11sMeshCapability::TBTTAdjustment.
operator==() [3/15]
bool ns3::dot11s::operator== (const IeBeaconTimingUnit & a, const IeBeaconTimingUnit & b)
Parameters
a lhs
b rhs
Returns
true if equal
Definition at line 185 of file ie-dot11s-beacon-timing.cc.
References ns3::dot11s::IeBeaconTimingUnit::GetAid(), ns3::dot11s::IeBeaconTimingUnit::GetBeaconInterval(), and ns3::dot11s::IeBeaconTimingUnit::GetLastBeacon().
operator==() [4/15]
bool ns3::dot11s::operator== (const IeConfiguration & a, const IeConfiguration & b)
Parameters
a lhs
b rhs
Returns
true if equal
Definition at line 206 of file ie-dot11s-configuration.cc.
References ns3::dot11s::IeConfiguration::m_APId, ns3::dot11s::IeConfiguration::m_APSMId, ns3::dot11s::IeConfiguration::m_APSPId, ns3::dot11s::IeConfiguration::m_CCMId, ns3::dot11s::IeConfiguration::m_meshCap, ns3::dot11s::IeConfiguration::m_neighbors, and ns3::dot11s::IeConfiguration::m_SPId.
operator==() [5/15]
bool ns3::dot11s::operator== (const IeLinkMetricReport & a, const IeLinkMetricReport & b)
Parameters
a lhs
b lhs
Returns
true if equal
Definition at line 72 of file ie-dot11s-metric-report.cc.
References ns3::dot11s::IeLinkMetricReport::m_metric.
operator==() [6/15]
bool ns3::dot11s::operator== (const IeMeshId & a, const IeMeshId & b)
Parameters
a lhs
b lhs
Returns
true if equal
Definition at line 121 of file ie-dot11s-id.cc.
References ns3::dot11s::IeMeshId::m_meshId.
operator==() [7/15]
bool ns3::dot11s::operator== (const IePeerManagement & a, const IePeerManagement & b)
Parameters
a lhs
b rhs
Returns
true if equal
Definition at line 162 of file ie-dot11s-peer-management.cc.
References ns3::dot11s::IePeerManagement::m_length, ns3::dot11s::IePeerManagement::m_localLinkId, ns3::dot11s::IePeerManagement::m_peerLinkId, ns3::dot11s::IePeerManagement::m_reasonCode, and ns3::dot11s::IePeerManagement::m_subtype.
operator==() [8/15]
bool ns3::dot11s::operator== (const IePerr & a, const IePerr & b)
Parameters
a lhs
b rhs
Returns
true if equal
Definition at line 148 of file ie-dot11s-perr.cc.
References ns3::dot11s::IePerr::m_addressUnits.
operator==() [9/15]
bool ns3::dot11s::operator== (const IePrep & a, const IePrep & b)
Parameters
a lhs
b rhs
Returns
true if equal
Definition at line 198 of file ie-dot11s-prep.cc.
References ns3::dot11s::IePrep::m_destinationAddress, ns3::dot11s::IePrep::m_destSeqNumber, ns3::dot11s::IePrep::m_flags, ns3::dot11s::IePrep::m_hopcount, ns3::dot11s::IePrep::m_lifetime, ns3::dot11s::IePrep::m_metric, ns3::dot11s::IePrep::m_originatorAddress, ns3::dot11s::IePrep::m_originatorSeqNumber, and ns3::dot11s::IePrep::m_ttl.
operator==() [10/15]
bool ns3::dot11s::operator== (const IePreq & a, const IePreq & b)
Parameters
a lhs
b rhs
Returns
true if equal
Definition at line 390 of file ie-dot11s-preq.cc.
References ns3::dot11s::IePreq::m_destCount, ns3::dot11s::IePreq::m_destinations, ns3::dot11s::IePreq::m_flags, ns3::dot11s::IePreq::m_hopCount, ns3::dot11s::IePreq::m_lifetime, ns3::dot11s::IePreq::m_metric, ns3::dot11s::IePreq::m_originatorAddress, ns3::dot11s::IePreq::m_originatorSeqNumber, ns3::dot11s::IePreq::m_preqId, ns3::dot11s::IePreq::m_ttl, and ns3::PeekPointer().
operator==() [11/15]
bool ns3::dot11s::operator== (const IeRann & a, const IeRann & b)
Parameters
a lhs
b rhs
Returns
true if equal
Definition at line 164 of file ie-dot11s-rann.cc.
References ns3::dot11s::IeRann::m_destSeqNumber, ns3::dot11s::IeRann::m_flags, ns3::dot11s::IeRann::m_hopcount, ns3::dot11s::IeRann::m_metric, ns3::dot11s::IeRann::m_originatorAddress, and ns3::dot11s::IeRann::m_ttl.
operator==() [12/15]
bool ns3::dot11s::operator== (const MeshHeader & a, const MeshHeader & b)
Parameters
a left hand side
b right hand side
Returns
true if equal
Definition at line 172 of file dot11s-mac-header.cc.
References ns3::dot11s::MeshHeader::m_addr4, ns3::dot11s::MeshHeader::m_addr5, ns3::dot11s::MeshHeader::m_addr6, ns3::dot11s::MeshHeader::m_meshFlags, ns3::dot11s::MeshHeader::m_meshSeqno, and ns3::dot11s::MeshHeader::m_meshTtl.
operator==() [13/15]
bool ns3::dot11s::operator== (const PeerLinkCloseStart & a, const PeerLinkCloseStart & b)
Parameters
a lhs
b rhs
Returns
true if equal
Definition at line 205 of file peer-link-frame.cc.
References ns3::dot11s::IeMeshId::IsEqual(), and ns3::dot11s::PeerLinkCloseStart::m_meshId.
operator==() [14/15]
bool ns3::dot11s::operator== (const PeerLinkConfirmStart & a, const PeerLinkConfirmStart & b)
Parameters
a lhs
b rhs
Returns
true if equal
Definition at line 300 of file peer-link-frame.cc.
References ns3::dot11s::PeerLinkConfirmStart::m_aid, ns3::dot11s::PeerLinkConfirmStart::m_capability, and ns3::dot11s::PeerLinkConfirmStart::m_config.
operator==() [15/15]
bool ns3::dot11s::operator== (const PeerLinkOpenStart & a, const PeerLinkOpenStart & b)
Parameters
a lhs
b rhs
Returns
true if equal
Definition at line 130 of file peer-link-frame.cc.
References ns3::dot11s::IeMeshId::IsEqual(), ns3::dot11s::PeerLinkOpenStart::m_capability, ns3::dot11s::PeerLinkOpenStart::m_config, and ns3::dot11s::PeerLinkOpenStart::m_meshId.
operator>()
bool ns3::dot11s::operator> (const IeLinkMetricReport & a, const IeLinkMetricReport & b)
Parameters
a lhs
b lhs
Returns
true if equal
Definition at line 82 of file ie-dot11s-metric-report.cc.
References ns3::dot11s::IeLinkMetricReport::m_metric.
operator>>()
std::istream& ns3::dot11s::operator>> (std::istream & is, IeMeshId & a)
Definition at line 144 of file ie-dot11s-id.cc.