ns-3: ns3::lorawan Namespace Reference
ns3::lorawan Namespace Reference
Classes
class AdrComponent
class BuildingPenetrationLoss
A class implementing the TR 45.820 model for building losses.
class ClassAEndDeviceLorawanMac
Class representing the MAC layer of a Class A LoRaWAN device.
class ConfirmedMessagesComponent
class ConstantLoraTxCurrentModel
class CorrelatedShadowingPropagationLossModel
class DevStatusAns
Implementation of the DevStatusAns LoRaWAN MAC command.
class DevStatusReq
Implementation of the DevStatusReq LoRaWAN MAC command.
class DlChannelAns
Implementation of the DlChannelAns LoRaWAN MAC command.
class DutyCycleAns
Implementation of the DutyCycleAns LoRaWAN MAC command.
class DutyCycleReq
Implementation of the DutyCycleReq LoRaWAN MAC command.
class EndDeviceLoraPhy
Class representing a LoRa transceiver.
class EndDeviceLoraPhyListener
Receive notifications about PHY events.
class EndDeviceLorawanMac
Class representing the MAC layer of a LoRaWAN device.
class EndDeviceStatus
This class represents the Network Server's knowledge about an End Device in the LoRaWAN network it is administering.
class Forwarder
This application forwards packets between NetDevices: LoraNetDevice -> PointToPointNetDevice and vice versa.
class ForwarderHelper
This class can be used to install Forwarder applications on a set of gateways.
class GatewayLoraPhy
Class modeling a Lora SX1301 chip.
class GatewayLorawanMac
class GatewayStatus
class LinearLoraTxCurrentModel
A linear model of the transmission current for a LoRa device, based on the WiFi model.
class LinkAdrAns
Implementation of the LinkAdrAns LoRaWAN MAC command.
class LinkAdrReq
Implementation of the LinkAdrReq LoRaWAN MAC command.
class LinkCheckAns
Implementation of the LinkCheckAns LoRaWAN MAC command.
class LinkCheckComponent
class LinkCheckReq
Implementation of the LinkCheckReq LoRaWAN MAC command.
class LogicalLoraChannel
This class represents a logical LoRaWAN channel.
class LogicalLoraChannelHelper
This class supports LorawanMac instances by managing a list of the logical channels that the device is supposed to be using, and establishes their relationship with SubBands.
class LoraChannel
The class that delivers packets among PHY layers.
struct LoraChannelParameters
A struct that holds meaningful parameters for transmission on a LoraChannel.
class LoraDeviceAddress
This class represents the device address of a LoraWAN End Device.
class LoraDeviceAddressGenerator
This class generates sequential LoraDeviceAddress instances.
class LoraFrameHeader
This class represents the Frame header (FHDR) used in a LoraWAN network.
class LoraHelper
Helps to create LoraNetDevice objects.
class LoraInterferenceHelper
Helper for LoraPhy that manages interference calculations.
class LoraNetDevice
Hold together all LoRa related objects.
class LoraPacketTracker
class LoraPhy
class LoraPhyHelper
Helper to install LoraPhy instances on multiple Nodes.
class LoraRadioEnergyModel
A WiFi radio energy model.
class LoraRadioEnergyModelHelper
Assign LoraRadioEnergyModel to wifi devices.
class LoraRadioEnergyModelPhyListener
class LoraTag
Tag used to save various data about a packet, like its Spreading Factor and data about interference.
class LoraTxCurrentModel
Model the transmit current as a function of the transmit power and mode.
struct LoraTxParameters
Structure to collect all parameters that are used to compute the duration of a packet (excluding payload length).
class LorawanMac
Class representing the LoRaWAN MAC layer.
class LorawanMacHeader
This class represents the Mac header of a LoRaWAN packet.
class LorawanMacHelper
class MacCommand
This base class is used to represent a general MAC command.
struct MacPacketStatus
struct NetworkComponents
class NetworkController
This class collects a series of components that deal with various aspects of managing the network, and queries them for action when a new packet is received or other events occur in the network.
class NetworkControllerComponent
Generic class describing a component of the NetworkController.
class NetworkScheduler
class NetworkServer
The NetworkServer is an application standing on top of a node equipped with links that connect it with the gateways.
class NetworkServerHelper
This class can install Network Server applications on multiple nodes at once.
class NetworkStatus
This class represents the knowledge about the state of the network that is available at the Network Server.
class NewChannelAns
Implementation of the NewChannelAns LoRaWAN MAC command.
class NewChannelReq
Implementation of the NewChannelReq LoRaWAN MAC command.
class NwkAddr
Class representing the Network Address component of a LoraDeviceAddress (25 bits)
class NwkID
Class representing the NetworkId component of a LoraDeviceAddress (7 bits).
class OneShotSender
class OneShotSenderHelper
This class can be used to install OneShotSender applications on multiple nodes at once.
struct PacketStatus
class PeriodicSender
class PeriodicSenderHelper
This class can be used to install PeriodicSender applications on a wide range of nodes.
struct RetransmissionStatus
class RxParamSetupAns
Implementation of the RxParamSetupAns LoRaWAN MAC command.
class RxParamSetupReq
Implementation of the RxParamSetupReq LoRaWAN MAC command.
class RxTimingSetupAns
Implementation of the RxTimingSetupAns LoRaWAN MAC command.
class RxTimingSetupReq
Implementation of the RxTimingSetupReq LoRaWAN MAC command.
class SimpleEndDeviceLoraPhy
Class representing a simple LoRa transceiver, with an error model based on receiver sensitivity and a SIR table.
class SimpleGatewayLoraPhy
Class modeling a Lora SX1301 chip.
class SubBand
Class representing a SubBand, i.e., a frequency band subject to some regulations on duty cycle and transmission power.
class TxParamSetupAns
Implementation of the TxParamSetupAns LoRaWAN MAC command.
class TxParamSetupReq
Implementation of the TxParamSetupReq LoRaWAN MAC command.
Typedefs
typedef std::map< Ptr< Packet const >, MacPacketStatus > MacPacketData
typedef std::map< Ptr< Packet const >, PacketStatus > PhyPacketData
typedef std::map< Ptr< Packet const >, RetransmissionStatus > RetransmissionData
Enumerations
enum MacCommandType {
INVALID, LINK_CHECK_REQ, LINK_CHECK_ANS, LINK_ADR_REQ,
LINK_ADR_ANS, DUTY_CYCLE_REQ, DUTY_CYCLE_ANS, RX_PARAM_SETUP_REQ,
RX_PARAM_SETUP_ANS, DEV_STATUS_REQ, DEV_STATUS_ANS, NEW_CHANNEL_REQ,
NEW_CHANNEL_ANS, RX_TIMING_SETUP_REQ, RX_TIMING_SETUP_ANS, TX_PARAM_SETUP_REQ,
TX_PARAM_SETUP_ANS, DL_CHANNEL_REQ, DL_CHANNEL_ANS
}
Enum for every possible command type.
enum PhyPacketOutcome {
RECEIVED, INTERFERED, NO_MORE_RECEIVERS, UNDER_SENSITIVITY,
LOST_BECAUSE_TX, UNSET
}
Functions
Ptr< LoraChannel > CreateChannel (void)
NodeContainer CreateEndDevices (int nDevices, MobilityHelper mobility, Ptr< LoraChannel > channel)
NodeContainer CreateGateways (int nGateways, MobilityHelper mobility, Ptr< LoraChannel > channel)
Ptr< Node > CreateNetworkServer (NodeContainer endDevices, NodeContainer gateways)
double DbmToW (double dbm)
Convert from dBm to Watts.
double DbToRatio (double db)
Convert from dB to ratio.
template<typename T >
Ptr< T > GetMacLayerFromNode (Ptr< Node > n)
NetworkComponents InitializeNetwork (int nDevices, int nGateways)
bool operator!= (const Ptr< LogicalLoraChannel > &first, const Ptr< LogicalLoraChannel > &second)
Overload the != operator to compare different instances of the same LogicalLoraChannel.
std::ostream & operator<< (std::ostream &os, const EndDeviceStatus &status)
std::ostream & operator<< (std::ostream &os, const LoraChannelParameters &params)
Allow logging of LoraChannelParameters like with any other data type.
std::ostream & operator<< (std::ostream &os, const LoraDeviceAddress &address)
Operator overload to correctly handle logging when an address is passed as an argument.
std::ostream & operator<< (std::ostream &os, const LoraInterferenceHelper::Event &event)
Allow easy logging of LoraInterferenceHelper Events.
std::ostream & operator<< (std::ostream &os, const LoraTxParameters &params)
Allow logging of LoraTxParameters like with any other data type.
bool operator== (const Ptr< LogicalLoraChannel > &first, const Ptr< LogicalLoraChannel > &second)
Overload of the == operator to compare different instances of the same LogicalLoraChannel.
double RatioToDb (double ratio)
Convert from ratio to dB.
double WToDbm (double w)
Convert from Watts to dBm.
Variables
double inf = std::numeric_limits<double>::max ()
double minf = std::numeric_limits<double>::min ()
Typedef Documentation
MacPacketData
typedef std::map<Ptr<Packet const>, MacPacketStatus> ns3::lorawan::MacPacketData
Definition at line 68 of file lora-packet-tracker.h.
PhyPacketData
typedef std::map<Ptr<Packet const>, PacketStatus> ns3::lorawan::PhyPacketData
Definition at line 69 of file lora-packet-tracker.h.
RetransmissionData
typedef std::map<Ptr<Packet const>, RetransmissionStatus> ns3::lorawan::RetransmissionData
Definition at line 70 of file lora-packet-tracker.h.
Enumeration Type Documentation
MacCommandType
enum ns3::lorawan::MacCommandType
Enum for every possible command type.
Enumerator
INVALID
LINK_CHECK_REQ
LINK_CHECK_ANS
LINK_ADR_REQ
LINK_ADR_ANS
DUTY_CYCLE_REQ
DUTY_CYCLE_ANS
RX_PARAM_SETUP_REQ
RX_PARAM_SETUP_ANS
DEV_STATUS_REQ
DEV_STATUS_ANS
NEW_CHANNEL_REQ
NEW_CHANNEL_ANS
RX_TIMING_SETUP_REQ
RX_TIMING_SETUP_ANS
TX_PARAM_SETUP_REQ
TX_PARAM_SETUP_ANS
DL_CHANNEL_REQ
DL_CHANNEL_ANS
Definition at line 34 of file mac-command.h.
PhyPacketOutcome
enum ns3::lorawan::PhyPacketOutcome
Enumerator
RECEIVED
INTERFERED
NO_MORE_RECEIVERS
UNDER_SENSITIVITY
LOST_BECAUSE_TX
UNSET
Definition at line 33 of file lora-packet-tracker.h.
Function Documentation
CreateChannel()
Ptr< LoraChannel > ns3::lorawan::CreateChannel (void)
Definition at line 7 of file utilities.cc.
Referenced by InitializeNetwork().
CreateEndDevices()
NodeContainer ns3::lorawan::CreateEndDevices (int nDevices, MobilityHelper mobility, Ptr< LoraChannel > channel)
Definition at line 20 of file utilities.cc.
References third::channel, ns3::NodeContainer::Create(), ns3::lorawan::LoraPhyHelper::ED, ns3::lorawan::LorawanMacHelper::ED_A, ns3::lorawan::LoraHelper::Install(), third::mobility, nDevices, ns3::lorawan::LoraPhyHelper::SetChannel(), ns3::lorawan::LoraPhyHelper::SetDeviceType(), and ns3::lorawan::LorawanMacHelper::SetDeviceType().
Referenced by InitializeNetwork().
CreateGateways()
NodeContainer ns3::lorawan::CreateGateways (int nGateways, MobilityHelper mobility, Ptr< LoraChannel > channel)
Definition at line 48 of file utilities.cc.
References third::channel, ns3::NodeContainer::Create(), ns3::lorawan::LoraPhyHelper::GW, ns3::lorawan::LorawanMacHelper::GW, ns3::lorawan::LoraHelper::Install(), third::mobility, nGateways, ns3::lorawan::LoraPhyHelper::SetChannel(), ns3::lorawan::LoraPhyHelper::SetDeviceType(), and ns3::lorawan::LorawanMacHelper::SetDeviceType().
Referenced by InitializeNetwork().
CreateNetworkServer()
Ptr< Node > ns3::lorawan::CreateNetworkServer (NodeContainer endDevices, NodeContainer gateways)
Definition at line 75 of file utilities.cc.
References ns3::lorawan::NetworkServerHelper::Install(), ns3::lorawan::ForwarderHelper::Install(), ns3::lorawan::NetworkServerHelper::SetEndDevices(), and ns3::lorawan::NetworkServerHelper::SetGateways().
Referenced by InitializeNetwork().
DbmToW()
double ns3::lorawan::DbmToW (double dbm)
Convert from dBm to Watts.
Parameters
dbm the power in dBm
Returns
the equivalent Watts for the given dBm
Definition at line 30 of file lora-utils.cc.
Referenced by ns3::lorawan::LinearLoraTxCurrentModel::CalcTxCurrent(), WifiPhyThresholdsWeakWifiSignalTest::DoRun(), WifiPhyThresholdsWeakForeignSignalTest::DoRun(), WifiPhyThresholdsStrongWifiSignalTest::DoRun(), WifiPhyThresholdsStrongForeignSignalTest::DoRun(), TestAmpduReception::SendAmpduWithThreeMpdus(), TestThresholdPreambleDetectionWithoutFrameCapture::SendPacket(), TestThresholdPreambleDetectionWithFrameCapture::SendPacket(), TestPhyHeadersReception::SendPacket(), and TestSimpleFrameCaptureModel::SendPacket().
DbToRatio()
double ns3::lorawan::DbToRatio (double db)
Convert from dB to ratio.
Parameters
db
Returns
ratio
Definition at line 23 of file lora-utils.cc.
GetMacLayerFromNode()
template<typename T > Ptr<T> ns3::lorawan::GetMacLayerFromNode (Ptr< Node > n)
Definition at line 53 of file utilities.h.
References ns3::Object::GetObject(), and sample-rng-plot::n.
InitializeNetwork()
NetworkComponents ns3::lorawan::InitializeNetwork (int nDevices, int nGateways)
Definition at line 92 of file utilities.cc.
References third::channel, CreateChannel(), CreateEndDevices(), CreateGateways(), CreateNetworkServer(), third::mobility, nDevices, nGateways, and ns3::lorawan::LorawanMacHelper::SetSpreadingFactorsUp().
Referenced by UplinkPacketTest::DoRun(), DownlinkPacketTest::DoRun(), LinkCheckTest::DoRun(), and NetworkStatusTest::DoRun().
operator!=()
bool ns3::lorawan::operator!= (const Ptr< LogicalLoraChannel > & first, const Ptr< LogicalLoraChannel > & second)
Overload the != operator to compare different instances of the same LogicalLoraChannel.
Definition at line 134 of file logical-lora-channel.cc.
operator<<() [1/5]
std::ostream& ns3::lorawan::operator<< (std::ostream & os, const EndDeviceStatus & status)
Definition at line 389 of file end-device-status.cc.
References ns3::lorawan::EndDeviceStatus::PacketInfoPerGw::gwAddress, ns3::lorawan::EndDeviceStatus::ReceivedPacketInfo::gwList, ns3::lorawan::EndDeviceStatus::m_receivedPacketList, and ns3::lorawan::EndDeviceStatus::PacketInfoPerGw::rxPower.
operator<<() [2/5]
std::ostream & ns3::lorawan::operator<< (std::ostream & os, const LoraChannelParameters & params)
Allow logging of LoraChannelParameters like with any other data type.
Definition at line 201 of file lora-channel.cc.
References aloha::params.
operator<<() [3/5]
std::ostream & ns3::lorawan::operator<< (std::ostream & os, const LoraDeviceAddress & address)
Operator overload to correctly handle logging when an address is passed as an argument.
Definition at line 264 of file lora-device-address.cc.
References first::address.
operator<<() [4/5]
std::ostream & ns3::lorawan::operator<< (std::ostream & os, const LoraInterferenceHelper::Event & event)
Allow easy logging of LoraInterferenceHelper Events.
Definition at line 104 of file lora-interference-helper.cc.
operator<<() [5/5]
std::ostream & ns3::lorawan::operator<< (std::ostream & os, const LoraTxParameters & params)
Allow logging of LoraTxParameters like with any other data type.
Definition at line 204 of file lora-phy.cc.
References aloha::params.
operator==()
bool ns3::lorawan::operator== (const Ptr< LogicalLoraChannel > & first, const Ptr< LogicalLoraChannel > & second)
Overload of the == operator to compare different instances of the same LogicalLoraChannel.
Definition at line 120 of file logical-lora-channel.cc.
References NS_LOG_DEBUG.
RatioToDb()
double ns3::lorawan::RatioToDb (double ratio)
Convert from ratio to dB.
Parameters
ratio
Returns
dB
Definition at line 43 of file lora-utils.cc.
WToDbm()
double ns3::lorawan::WToDbm (double w)
Convert from Watts to dBm.
Parameters
w the power in Watts
Returns
the equivalent dBm for the given Watts
Definition at line 37 of file lora-utils.cc.
Referenced by TestInterBssConstantObssPdAlgo::NotifyPhyTxBegin().
Variable Documentation
inf
double ns3::lorawan::inf = std::numeric_limits<double>::max ()
Definition at line 117 of file lora-interference-helper.cc.
minf
double ns3::lorawan::minf = std::numeric_limits<double>::min ()
Definition at line 118 of file lora-interference-helper.cc.