ns-3: ns3::addressUtils Namespace Reference
ns3::addressUtils Namespace Reference
Functions
bool IsMulticast (const Address &ad)
Address family-independent test for a multicast address.
Function Documentation
IsMulticast()
bool ns3::addressUtils::IsMulticast (const Address & ad)
Address family-independent test for a multicast address.
Definition at line 114 of file address-utils.cc.
References ns3::InetSocketAddress::ConvertFrom(), ns3::InetSocketAddress::GetIpv4(), ns3::InetSocketAddress::IsMatchingType(), ns3::Ipv4Address::IsMulticast(), and NS_LOG_FUNCTION.
Referenced by ns3::PacketSink::StartApplication(), and ns3::UdpEchoServer::StartApplication().