ns-3: ns3::aodv Namespace Reference
ns3::aodv Namespace Reference
Classes
class AodvLoopbackTestSuite
AODV Loopback test suite.
struct AodvRqueueTest
Unit test for RequestQueue.
struct AodvRtableEntryTest
Unit test for AODV routing table entry.
struct AodvRtableTest
Unit test for AODV routing table.
class AodvTestSuite
AODV test suite.
struct CloseNeighbor
CloseNeighbor structure.
class DeferredRouteOutputTag
Tag used by AODV implementation.
class DuplicatePacketDetection
Helper class used to remember already seen packets and detect duplicates.
class IdCache
Unique packets identification cache used for simple duplicate detection.
class IdCacheTest
Unit test for id cache.
class IdCacheTestSuite
Id Cache Test Suite.
struct IsExpired
IsExpired structure.
class LoopbackTestCase
AODV loopback UDP echo test case.
class Neighbors
maintain list of active neighbors
struct NeighborTest
Unit test for neighbors.
class QueueEntry
AODV Queue Entry.
struct QueueEntryTest
Unit test for AODV routing table entry.
class RequestQueue
AODV route request queue.
class RerrHeader
Route Error (RERR) Message Format.
struct RerrHeaderTest
Unit test for RERR.
class RoutingProtocol
AODV routing protocol.
class RoutingTable
The Routing table used by AODV protocol.
class RoutingTableEntry
Routing table entry.
class RrepAckHeader
Route Reply Acknowledgment (RREP-ACK) Message Format.
struct RrepAckHeaderTest
Unit test for RREP-ACK.
class RrepHeader
Route Reply (RREP) Message Format.
struct RrepHeaderTest
Unit test for RREP.
class RreqHeader
Route Request (RREQ) Message Format.
struct RreqHeaderTest
Unit test for RREQ.
class TypeHeader
AODV types.
struct TypeHeaderTest
Type header test case.
Enumerations
enum MessageType { AODVTYPE_RREQ = 1, AODVTYPE_RREP = 2, AODVTYPE_RERR = 3, AODVTYPE_RREP_ACK = 4 }
MessageType enumeration.
enum RouteFlags { VALID = 0, INVALID = 1, IN_SEARCH = 2 }
Route record states.
Functions
std::ostream & operator<< (std::ostream &os, RerrHeader const &)
Stream output operator.
std::ostream & operator<< (std::ostream &os, RrepAckHeader const &)
Stream output operator.
std::ostream & operator<< (std::ostream &os, RrepHeader const &)
Stream output operator.
std::ostream & operator<< (std::ostream &os, RreqHeader const &)
Stream output operator.
std::ostream & operator<< (std::ostream &os, TypeHeader const &h)
Stream output operator.
Variables
ns3::aodv::AodvLoopbackTestSuite g_aodvLoopbackTestSuite
the test suite
ns3::aodv::AodvTestSuite g_aodvTestSuite
the test suite
ns3::aodv::IdCacheTestSuite g_idCacheTestSuite
the test suite
Function Documentation
operator<<() [1/5]
std::ostream & ns3::aodv::operator<< (std::ostream & os, RerrHeader const &)
Stream output operator.
Parameters
os output stream
Returns
updated stream
Definition at line 675 of file aodv-packet.cc.
References ns3::aodv::RerrHeader::Print().
operator<<() [2/5]
std::ostream & ns3::aodv::operator<< (std::ostream & os, RrepAckHeader const &)
Stream output operator.
Parameters
os output stream
Returns
updated stream
Definition at line 510 of file aodv-packet.cc.
References ns3::aodv::RrepAckHeader::Print().
operator<<() [3/5]
std::ostream & ns3::aodv::operator<< (std::ostream & os, RrepHeader const &)
Stream output operator.
Parameters
os output stream
Returns
updated stream
Definition at line 442 of file aodv-packet.cc.
References ns3::aodv::RrepHeader::Print().
operator<<() [4/5]
std::ostream & ns3::aodv::operator<< (std::ostream & os, RreqHeader const &)
Stream output operator.
Parameters
os output stream
Returns
updated stream
Definition at line 222 of file aodv-packet.cc.
References ns3::aodv::RreqHeader::Print().
operator<<() [5/5]
std::ostream & ns3::aodv::operator<< (std::ostream & os, TypeHeader const & h)
Stream output operator.
Parameters
os output stream
Returns
updated stream
Definition at line 132 of file aodv-packet.cc.
References ns3::aodv::TypeHeader::Print().