ns-3: anonymous_namespace{traced-callback-typedef-test-suite.cc} Namespace Reference
anonymous_namespace{traced-callback-typedef-test-suite.cc} Namespace Reference
Classes
class TracedCbSink
Sink functions.
class TracedCbSink< T1, empty, empty, empty, empty >
class TracedCbSink< T1, T2, empty, empty, empty >
class TracedCbSink< T1, T2, T3, empty, empty >
class TracedCbSink< T1, T2, T3, T4, empty >
Functions
std::set< std::string > Duplicates (void)
Record typedefs which are identical to previously declared.
void SinkIt (unsigned int N)
Log that a callback was invoked.
template<typename T >
std::string TypeName (int N)
Stringify the known TracedCallback type names.
Variables
std::set< std::string > g_dupes = Duplicates ()
Container for duplicate types.
Function Documentation
Duplicates()
std::set<std::string> anonymous_namespace{traced-callback-typedef-test-suite.cc}::Duplicates (void)
Record typedefs which are identical to previously declared.
Definition at line 100 of file traced-callback-typedef-test-suite.cc.
SinkIt()
void anonymous_namespace{traced-callback-typedef-test-suite.cc}::SinkIt (unsigned int N)
Log that a callback was invoked.
We can't actually do anything with any of the arguments, but the fact we got called is what's important.
Parameters
[in] N The number of arguments passed to the callback.
Definition at line 214 of file traced-callback-typedef-test-suite.cc.
References TracedCallbackTypedefTestCase::m_nArgs.
Referenced by anonymous_namespace{traced-callback-typedef-test-suite.cc}::TracedCbSink< T1, empty, empty, empty, empty >::Sink(), anonymous_namespace{traced-callback-typedef-test-suite.cc}::TracedCbSink< T1, T2, empty, empty, empty >::Sink(), anonymous_namespace{traced-callback-typedef-test-suite.cc}::TracedCbSink< T1, T2, T3, empty, empty >::Sink(), anonymous_namespace{traced-callback-typedef-test-suite.cc}::TracedCbSink< T1, T2, T3, T4, empty >::Sink(), and anonymous_namespace{traced-callback-typedef-test-suite.cc}::TracedCbSink< T1, T2, T3, T4, T5 >::Sink().
TYPENAME() [1/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (dot11s::PeerManagementProtocol::LinkOpenCloseTracedCallback)
TYPENAME() [2/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (dsr::DsrOptionSRHeader::TracedCallback)
TYPENAME() [3/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (EpcUeNas::StateTracedCallback)
TypeName()
template<typename T > std::string anonymous_namespace{traced-callback-typedef-test-suite.cc}::TypeName (int N) inline
Stringify the known TracedCallback type names.
Template Parameters
T [explicit] The typedef name.
Parameters
[in] N The number of arguments expected.
Returns
The TracedCallback type name.
Definition at line 128 of file traced-callback-typedef-test-suite.cc.
TYPENAME() [4/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (Ipv4L3Protocol::DropTracedCallback)
TYPENAME() [5/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (Ipv4L3Protocol::SentTracedCallback)
TYPENAME() [6/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (Ipv4L3Protocol::TxRxTracedCallback)
TYPENAME() [7/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (Ipv6L3Protocol::DropTracedCallback)
TYPENAME() [8/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (Ipv6L3Protocol::SentTracedCallback)
TYPENAME() [9/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (Ipv6L3Protocol::TxRxTracedCallback)
TYPENAME() [10/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (LrWpanMac::SentTracedCallback)
TYPENAME() [11/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (LrWpanMac::StateTracedCallback)
TYPENAME() [12/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (LrWpanPhy::StateTracedCallback)
TYPENAME() [13/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (LteEnbMac::UlSchedulingTracedCallback)
TYPENAME() [14/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (LteEnbPhy::ReportInterferenceTracedCallback)
TYPENAME() [15/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (LteEnbPhy::ReportUeSinrTracedCallback)
TYPENAME() [16/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (LteEnbRrc::ConnectionHandoverTracedCallback)
TYPENAME() [17/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (LteEnbRrc::HandoverStartTracedCallback)
TYPENAME() [18/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (LteEnbRrc::NewUeContextTracedCallback)
TYPENAME() [19/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (LteEnbRrc::ReceiveReportTracedCallback)
TYPENAME() [20/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (LtePdcp::PduRxTracedCallback)
TYPENAME() [21/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (LtePdcp::PduTxTracedCallback)
TYPENAME() [22/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (LteUePhy::RsrpSinrTracedCallback)
TYPENAME() [23/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (LteUePhy::StateTracedCallback)
TYPENAME() [24/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (LteUeRrc::CellSelectionTracedCallback)
TYPENAME() [25/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (LteUeRrc::StateTracedCallback)
TYPENAME() [26/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (Mac48Address::TracedCallback)
TYPENAME() [27/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (MobilityModel::TracedCallback)
TYPENAME() [28/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (olsr::RoutingProtocol::PacketTxRxTracedCallback)
TYPENAME() [29/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (olsr::RoutingProtocol::TableChangeTracedCallback)
TYPENAME() [30/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (Packet::AddressTracedCallback)
TYPENAME() [31/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (Packet::Mac48AddressTracedCallback)
TYPENAME() [32/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (Packet::SinrTracedCallback)
TYPENAME() [33/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (Packet::SizeTracedCallback)
TYPENAME() [34/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (Packet::TracedCallback)
TYPENAME() [35/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (PacketBurst::TracedCallback)
TYPENAME() [36/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (PhyReceptionStatParameters::TracedCallback)
TYPENAME() [37/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (PhyTransmissionStatParameters::TracedCallback)
TYPENAME() [38/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (SixLowPanNetDevice::DropTracedCallback)
TYPENAME() [39/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (SixLowPanNetDevice::RxTxTracedCallback)
TYPENAME() [40/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (SpectrumChannel::LossTracedCallback)
TYPENAME() [41/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (SpectrumValue::TracedCallback)
TYPENAME() [42/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (TimeSeriesAdaptor::OutputTracedCallback)
TYPENAME() [43/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (UanMac::PacketModeTracedCallback)
TYPENAME() [44/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (UanMacCw::QueueTracedCallback)
TYPENAME() [45/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (UanMacRc::QueueTracedCallback)
TYPENAME() [46/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (UanNetDevice::RxTxTracedCallback)
TYPENAME() [47/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (UanPhy::TracedCallback)
TYPENAME() [48/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (UeManager::StateTracedCallback)
TYPENAME() [49/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (WifiMacHeader::TracedCallback)
TYPENAME() [50/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (WifiPhyStateHelper::RxOkTracedCallback)
TYPENAME() [51/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (WifiPhyStateHelper::StateTracedCallback)
TYPENAME() [52/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (WifiPhyStateHelper::TxTracedCallback)
TYPENAME() [53/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (WifiRemoteStationManager::PowerChangeTracedCallback)
TYPENAME() [54/54]
anonymous_namespace{traced-callback-typedef-test-suite.cc}::TYPENAME (WifiRemoteStationManager::RateChangeTracedCallback)
Variable Documentation
g_dupes
std::set<std::string> anonymous_namespace{traced-callback-typedef-test-suite.cc}::g_dupes = Duplicates ()
Container for duplicate types.
Definition at line 116 of file traced-callback-typedef-test-suite.cc.