ns-3: visualizer.base Namespace Reference
visualizer.base Namespace Reference
Classes
class InformationWindow
InformationWindow class.
class Link
Link class.
class NetDeviceTraits
NetDeviceTraits class.
class PyVizObject
PyVizObject class.
Functions
def load_plugins ()
def lookup_netdevice_traits (class_type)
def register_plugin (plugin_init_func, plugin_name=None, plugin_module=None)
def transform_distance_canvas_to_simulation (d)
def transform_distance_simulation_to_canvas (d)
def transform_point_canvas_to_simulation (x, y)
def transform_point_simulation_to_canvas (x, y)
Variables
dictionary netdevice_traits
float PIXELS_PER_METER = 3.0
dictionary plugin_modules = {}
list plugins = []
bool plugins_loaded = False
Function Documentation
load_plugins()
def visualizer.base.load_plugins ()
Definition at line 115 of file base.py.
References list, print, and visualizer.base.register_plugin().
Referenced by visualizer.core.start().
lookup_netdevice_traits()
def visualizer.base.lookup_netdevice_traits (class_type)
Definition at line 72 of file base.py.
register_plugin()
def visualizer.base.register_plugin (plugin_init_func, plugin_name = None, plugin_module = None)
Register a plugin.
@param plugin: a callable object that will be invoked whenever a
Visualizer object is created, like this: plugin(visualizer)
Definition at line 102 of file base.py.
Referenced by visualizer.base.load_plugins().
transform_distance_canvas_to_simulation()
def visualizer.base.transform_distance_canvas_to_simulation (d)
Definition at line 90 of file base.py.
Referenced by wifi_intrastructure_link.WifiLink.tooltip_query().
transform_distance_simulation_to_canvas()
def visualizer.base.transform_distance_simulation_to_canvas (d)
Definition at line 84 of file base.py.
Referenced by visualizer.core.Node._update_appearance(), and visualizer.core.Node.set_svg_icon().
transform_point_canvas_to_simulation()
def visualizer.base.transform_point_canvas_to_simulation (x, y)
Definition at line 93 of file base.py.
transform_point_simulation_to_canvas()
def visualizer.base.transform_point_simulation_to_canvas (x, y)
Definition at line 87 of file base.py.
Referenced by visualizer.core.set_bounds().
Variable Documentation
netdevice_traits
dictionary visualizer.base.netdevice_traits
Initial value:
 =  {
     ns.point_to_point.PointToPointNetDevice: NetDeviceTraits(is_wireless=False),
     ns.csma.CsmaNetDevice: NetDeviceTraits(is_wireless=False),
     ns.wifi.WifiNetDevice: NetDeviceTraits(is_wireless=True),
     ns.bridge.BridgeNetDevice: NetDeviceTraits(is_virtual=True),
     ns.internet.LoopbackNetDevice: NetDeviceTraits(is_virtual=True, is_wireless=False),
     ns.mesh.MeshPointDevice: NetDeviceTraits(is_virtual=True),
     ns.wimax.SubscriberStationNetDevice: NetDeviceTraits(is_wireless=True),
     ns.wimax.BaseStationNetDevice: NetDeviceTraits(is_wireless=True),
     ns.lte.LteUeNetDevice: NetDeviceTraits(is_wireless=True),
     ns.lte.LteEnbNetDevice: NetDeviceTraits(is_wireless=True),
 }
Definition at line 59 of file base.py.
PIXELS_PER_METER
float visualizer.base.PIXELS_PER_METER = 3.0
Definition at line 15 of file base.py.
plugin_modules
dictionary visualizer.base.plugin_modules = {}
Definition at line 100 of file base.py.
plugins
list visualizer.base.plugins = []
Definition at line 99 of file base.py.
Referenced by ns3::dot11s::PeerManagementProtocol.Report(), and ns3::dot11s::PeerManagementProtocol.ResetStats().
plugins_loaded
bool visualizer.base.plugins_loaded = False
Definition at line 114 of file base.py.