ns-3: src/wave/test/ocb-test-suite.cc File Reference
ocb-test-suite.cc File Reference
#include <iostream>
#include "ns3/test.h"
#include "ns3/rng-seed-manager.h"
#include "ns3/config.h"
#include "ns3/data-rate.h"
#include "ns3/vector.h"
#include "ns3/string.h"
#include "ns3/packet-socket-address.h"
#include "ns3/mobility-model.h"
#include "ns3/yans-wifi-helper.h"
#include "ns3/position-allocator.h"
#include "ns3/packet-socket-helper.h"
#include "ns3/mobility-helper.h"
#include "ns3/wifi-net-device.h"
#include "ns3/packet-socket-server.h"
#include "ns3/packet-socket-client.h"
#include "ns3/ocb-wifi-mac.h"
#include "ns3/wifi-80211p-helper.h"
#include "ns3/wave-mac-helper.h"
Classes
class OcbTestSuite
Ocb Test Suite.
class OcbWifiMacTestCase
Ocb Wifi Mac Test Case.
Functions
static void AssignWifiRandomStreams (Ptr< WifiMac > mac, int64_t stream)
Variables
static OcbTestSuite ocbTestSuite
the test suite
Function Documentation
AssignWifiRandomStreams()
static void AssignWifiRandomStreams (Ptr< WifiMac > mac, int64_t stream) static
Definition at line 45 of file ocb-test-suite.cc.
References ns3::Txop::AssignStreams(), ns3::PointerValue::Get(), ns3::ObjectBase::GetAttribute(), and third::mac.
Referenced by OcbWifiMacTestCase::PostDeviceConfiguration().
Variable Documentation
ocbTestSuite
OcbTestSuite ocbTestSuite static
the test suite
Definition at line 464 of file ocb-test-suite.cc.