ns-3: src/network/test/pcap-file-test-suite.cc File Reference
pcap-file-test-suite.cc File Reference
#include <iostream>
#include <cstdio>
#include <cstdlib>
#include <sstream>
#include <cstring>
#include "ns3/log.h"
#include "ns3/test.h"
#include "ns3/pcap-file.h"
Classes
class DiffTestCase
Test case to make sure that the Pcap::Diff method works as expected.
class FileHeaderTestCase
Test case to make sure that the Pcap File Object can write out correct pcap file headers in both endian cases, and then read them in correctly.
struct PacketEntry
PCAP Packet structure.
class PcapFileTestSuite
PCAP file utils TestSuite.
class ReadFileTestCase
Test case to make sure that the Pcap File Object can read out the contents of a known good pcap file.
class ReadModeCreateTestCase
Test case to make sure that the Pcap File Object can open an existing pcap file.
class RecordHeaderTestCase
Test case to make sure that the Pcap File Object can write pcap packet records in both endian cases, and then read them in correctly.
class WriteModeCreateTestCase
Test case to make sure that the Pcap File Object can do its most basic job and create an empty pcap file.
Functions
static bool CheckFileExists (std::string filename)
static bool CheckFileLength (std::string filename, uint64_t sizeExpected)
static uint16_t Swap (uint16_t val)
static uint32_t Swap (uint32_t val)
Variables
static const PacketEntry knownPackets []
static const uint32_t N_KNOWN_PACKETS = 6
static const uint32_t N_PACKET_BYTES = 16
static PcapFileTestSuite pcapFileTestSuite
Static variable for test initialization.
Function Documentation
CheckFileExists()
static bool CheckFileExists (std::string filename) static
Definition at line 50 of file pcap-file-test-suite.cc.
Referenced by WriteModeCreateTestCase::DoRun(), and ReadModeCreateTestCase::DoRun().
CheckFileLength()
static bool CheckFileLength (std::string filename, uint64_t sizeExpected) static
Definition at line 64 of file pcap-file-test-suite.cc.
Referenced by WriteModeCreateTestCase::DoRun().
Swap() [1/2]
static uint16_t Swap (uint16_t val) static
Definition at line 38 of file pcap-file-test-suite.cc.
Referenced by FileHeaderTestCase::DoRun(), and RecordHeaderTestCase::DoRun().
Swap() [2/2]
static uint32_t Swap (uint32_t val) static
Definition at line 44 of file pcap-file-test-suite.cc.
Variable Documentation
knownPackets
const PacketEntry knownPackets[] static
Initial value:
= {
  { 2, 3696,   46,   46, { 0x0001, 0x0800, 0x0604, 0x0001, 0x0000, 0x0000, 0x0003, 0x0a01,
                           0x0201, 0xffff, 0xffff, 0xffff, 0x0a01, 0x0204, 0x0000, 0x0000}},
  { 2, 3707,   46,   46, { 0x0001, 0x0800, 0x0604, 0x0002, 0x0000, 0x0000, 0x0006, 0x0a01,
                           0x0204, 0x0000, 0x0000, 0x0003, 0x0a01, 0x0201, 0x0000, 0x0000}},
  { 2, 3801, 1070, 1070, { 0x4500, 0x041c, 0x0000, 0x0000, 0x3f11, 0x0000, 0x0a01, 0x0101,
                           0x0a01, 0x0204, 0xc001, 0x0009, 0x0408, 0x0000, 0x0000, 0x0000}},
  { 2, 3811,   46,   46, { 0x0001, 0x0800, 0x0604, 0x0001, 0x0000, 0x0000, 0x0006, 0x0a01,
                           0x0204, 0xffff, 0xffff, 0xffff, 0x0a01, 0x0201, 0x0000, 0x0000}},
  { 2, 3822,   46,   46, { 0x0001, 0x0800, 0x0604, 0x0002, 0x0000, 0x0000, 0x0003, 0x0a01,
                           0x0201, 0x0000, 0x0000, 0x0006, 0x0a01, 0x0204, 0x0000, 0x0000}},
  { 2, 3915, 1070, 1070, { 0x4500, 0x041c, 0x0000, 0x0000, 0x4011, 0x0000, 0x0a01, 0x0204,
                           0x0a01, 0x0101, 0x0009, 0xc001, 0x0408, 0x0000, 0x0000, 0x0000}}
}
Definition at line 1027 of file pcap-file-test-suite.cc.
Referenced by ReadFileTestCase::DoRun(), and DiffTestCase::DoRun().
N_KNOWN_PACKETS
const uint32_t N_KNOWN_PACKETS = 6 static
Definition at line 1013 of file pcap-file-test-suite.cc.
Referenced by ReadFileTestCase::DoRun(), and DiffTestCase::DoRun().
N_PACKET_BYTES
const uint32_t N_PACKET_BYTES = 16 static
Definition at line 1014 of file pcap-file-test-suite.cc.
Referenced by ReadFileTestCase::DoRun(), and DiffTestCase::DoRun().
pcapFileTestSuite
PcapFileTestSuite pcapFileTestSuite static
Static variable for test initialization.
Definition at line 1172 of file pcap-file-test-suite.cc.