ns-3: src/traffic-control/examples/pie-example.cc File Reference
pie-example.cc File Reference
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/flow-monitor-helper.h"
#include "ns3/point-to-point-module.h"
#include "ns3/applications-module.h"
#include "ns3/traffic-control-module.h"
Functions
void BuildAppsTest ()
void CheckQueueDiscSize (Ptr< QueueDisc > queue)
Variables
double avgQueueDiscSize
uint32_t checkTimes
double client_start_time
double client_stop_time
std::stringstream filePlotQueueDisc
std::stringstream filePlotQueueDiscAvg
double global_start_time
double global_stop_time
Ipv4InterfaceContainer i0i2
Ipv4InterfaceContainer i1i2
Ipv4InterfaceContainer i2i3
Ipv4InterfaceContainer i3i4
Ipv4InterfaceContainer i3i5
NodeContainer n0n2
NodeContainer n1n2
NodeContainer n2n3
NodeContainer n3n4
NodeContainer n3n5
double sink_start_time
double sink_stop_time
Function Documentation
BuildAppsTest()
void BuildAppsTest ()
Definition at line 94 of file pie-example.cc.
References ns3::ApplicationContainer::Add(), client_start_time, client_stop_time, ns3::NodeContainer::Get(), ns3::Ipv4InterfaceContainer::GetAddress(), ns3::Ipv4Address::GetAny(), i3i4, ns3::OnOffHelper::Install(), ns3::PacketSinkHelper::Install(), n0n2, n1n2, n3n4, port, ns3::Seconds(), ns3::OnOffHelper::SetAttribute(), sink_start_time, sink_stop_time, ns3::ApplicationContainer::Start(), and ns3::ApplicationContainer::Stop().
CheckQueueDiscSize()
void CheckQueueDiscSize (Ptr< QueueDisc > queue)
Definition at line 74 of file pie-example.cc.
References avgQueueDiscSize, checkTimes, filePlotQueueDisc, filePlotQueueDiscAvg, ns3::QueueDisc::GetCurrentSize(), ns3::Time::GetSeconds(), ns3::QueueSize::GetValue(), ns3::Simulator::Now(), ns3::Simulator::Schedule(), and ns3::Seconds().
Variable Documentation
avgQueueDiscSize
double avgQueueDiscSize
Definition at line 48 of file pie-example.cc.
Referenced by CheckQueueDiscSize().
checkTimes
uint32_t checkTimes
Definition at line 47 of file pie-example.cc.
Referenced by CheckQueueDiscSize().
client_start_time
double client_start_time
Definition at line 55 of file pie-example.cc.
Referenced by BuildAppsTest().
client_stop_time
double client_stop_time
Definition at line 56 of file pie-example.cc.
Referenced by BuildAppsTest().
filePlotQueueDisc
std::stringstream filePlotQueueDisc
Definition at line 70 of file pie-example.cc.
Referenced by CheckQueueDiscSize().
filePlotQueueDiscAvg
std::stringstream filePlotQueueDiscAvg
Definition at line 71 of file pie-example.cc.
Referenced by CheckQueueDiscSize().
global_start_time
double global_start_time
Definition at line 51 of file pie-example.cc.
global_stop_time
double global_stop_time
Definition at line 52 of file pie-example.cc.
i0i2
Ipv4InterfaceContainer i0i2
Definition at line 64 of file pie-example.cc.
i1i2
Ipv4InterfaceContainer i1i2
Definition at line 65 of file pie-example.cc.
i2i3
Ipv4InterfaceContainer i2i3
Definition at line 66 of file pie-example.cc.
i3i4
Ipv4InterfaceContainer i3i4
Definition at line 67 of file pie-example.cc.
Referenced by BuildAppsTest().
i3i5
Ipv4InterfaceContainer i3i5
Definition at line 68 of file pie-example.cc.
n0n2
NodeContainer n0n2
Definition at line 58 of file pie-example.cc.
Referenced by BuildAppsTest().
n1n2
NodeContainer n1n2
Definition at line 59 of file pie-example.cc.
Referenced by BuildAppsTest().
n2n3
NodeContainer n2n3
Definition at line 60 of file pie-example.cc.
n3n4
NodeContainer n3n4
Definition at line 61 of file pie-example.cc.
Referenced by BuildAppsTest().
n3n5
NodeContainer n3n5
Definition at line 62 of file pie-example.cc.
sink_start_time
double sink_start_time
Definition at line 53 of file pie-example.cc.
Referenced by BuildAppsTest().
sink_stop_time
double sink_stop_time
Definition at line 54 of file pie-example.cc.
Referenced by BuildAppsTest().