ns-3: utils/print-introspected-doxygen.cc File Reference
print-introspected-doxygen.cc File Reference
Utils
#include <iostream>
#include <iomanip>
#include <algorithm>
#include <map>
#include <climits>
#include "ns3/command-line.h"
#include "ns3/config.h"
#include "ns3/global-value.h"
#include "ns3/log.h"
#include "ns3/object-vector.h"
#include "ns3/object.h"
#include "ns3/pointer.h"
#include "ns3/string.h"
#include "ns3/node-container.h"
#include "ns3/simple-channel.h"
#include "ns3/system-path.h"
Classes
struct AttributeDescriptor
Descriptor for an AttributeValue.
class StaticInformation
Gather aggregation and configuration path information from registered types.
Namespaces
anonymous_namespace{print-introspected-doxygen.cc}
Typedefs
typedef std::map< std::string, int32_t > NameMap
Map from TypeId name to tid.
typedef NameMap::const_iterator NameMapIterator
NameMap iterator.
Functions
NameMap GetNameMap (void)
Create a map from the class names to their index in the vector of TypeId's so that the names will end up in alphabetical order.
StaticInformation GetTypicalAggregations ()
Register aggregation relationships that are not automatically detected by this introspection program.
void PrintAllAttributes (std::ostream &os)
Print the list of all Attributes.
void PrintAllGlobals (std::ostream &os)
Print the list of all global variables.
void PrintAllLogComponents (std::ostream &os)
Print the list of all LogComponents.
void PrintAllTraceSources (std::ostream &os)
Print the list of all Trace sources.
void PrintAllTypeIds (std::ostream &os)
Print the list of all TypeIds.
void PrintAttributeHelper (std::ostream &os, const AttributeDescriptor &attr)
Print documentation corresponding to use of the ATTRIBUTE_HELPER_HEADER macro or ATTRIBUTE_VALUE_DEFINE_WITH_NAME macro.
void PrintAttributeImplementations (std::ostream &os)
Print documentation for Attribute implementations.
void PrintAttributes (std::ostream &os, const TypeId tid)
Print the Attributes block for tid, including Attributes declared in base classes.
void PrintAttributesTid (std::ostream &os, const TypeId tid)
Print direct Attributes for this TypeId.
void PrintAttributeValueSection (std::ostream &os, const std::string &name, const bool seeBase=true)
Print the section definition for an AttributeValue.
void PrintAttributeValueWithName (std::ostream &os, const std::string &name, const std::string &type, const std::string &header)
Print the AttributeValue documentation for a class.
void PrintConfigPaths (std::ostream &os, const TypeId tid)
Print config paths.
void PrintMakeAccessors (std::ostream &os, const std::string &name)
Print the AttributeValue MakeAccessor documentation for a class.
void PrintMakeChecker (std::ostream &os, const std::string &name, const std::string &header)
Print the AttributeValue MakeChecker documentation for a class.
void PrintSize (std::ostream &os, const TypeId tid)
Print the size of the type represented by this tid.
void PrintTraceSources (std::ostream &os, const TypeId tid)
Print the Trace sources block for tid, including Trace sources declared in base classes.
void PrintTraceSourcesTid (std::ostream &os, const TypeId tid)
Print direct Trace sources for this TypeId.
void PrintTypeIdBlocks (std::ostream &os)
Print the doxy block for each TypeId.
void SetMarkup (bool outputText)
Initialize the markup strings, for either doxygen or text.
template<typename T >
void Uniquefy (T t)
Helper to keep only the unique items in a container.
Variables
std::string anonymous_namespace{print-introspected-doxygen.cc}::anchor
Markup tokens.
std::string anonymous_namespace{print-introspected-doxygen.cc}::argument
function argument
std::string anonymous_namespace{print-introspected-doxygen.cc}::boldStart
start of bold span
std::string anonymous_namespace{print-introspected-doxygen.cc}::boldStop
end of bold span
std::string anonymous_namespace{print-introspected-doxygen.cc}::breakBoth
linebreak
std::string anonymous_namespace{print-introspected-doxygen.cc}::breakHtmlOnly
linebreak for html output only
std::string anonymous_namespace{print-introspected-doxygen.cc}::breakTextOnly
linebreak for text output only
std::string anonymous_namespace{print-introspected-doxygen.cc}::brief
brief tag
std::string anonymous_namespace{print-introspected-doxygen.cc}::classStart
start of a class
std::string anonymous_namespace{print-introspected-doxygen.cc}::classStop
end of a class
std::string anonymous_namespace{print-introspected-doxygen.cc}::codeWord
format next word as source code
std::string anonymous_namespace{print-introspected-doxygen.cc}::commentStart
start of code comment
std::string anonymous_namespace{print-introspected-doxygen.cc}::commentStop
end of code comment
std::string anonymous_namespace{print-introspected-doxygen.cc}::copyDoc
copy (or refer) to docs elsewhere
std::string anonymous_namespace{print-introspected-doxygen.cc}::file
file
std::string anonymous_namespace{print-introspected-doxygen.cc}::flagSpanStart
start of Attribute flag value
std::string anonymous_namespace{print-introspected-doxygen.cc}::flagSpanStop
end of Attribute flag value
std::string anonymous_namespace{print-introspected-doxygen.cc}::functionStart
start of a method/function
std::string anonymous_namespace{print-introspected-doxygen.cc}::functionStop
end of a method/function
std::string anonymous_namespace{print-introspected-doxygen.cc}::headingStart
start of section heading (h3)
std::string anonymous_namespace{print-introspected-doxygen.cc}::headingStop
end of section heading (h3)
std::string anonymous_namespace{print-introspected-doxygen.cc}::hrefMid
middle part of a link
std::string anonymous_namespace{print-introspected-doxygen.cc}::hrefStart
start of a link
std::string anonymous_namespace{print-introspected-doxygen.cc}::hrefStop
end of a link
std::string anonymous_namespace{print-introspected-doxygen.cc}::indentHtmlOnly
small indent
std::string anonymous_namespace{print-introspected-doxygen.cc}::listLineStart
start unordered list item
std::string anonymous_namespace{print-introspected-doxygen.cc}::listLineStop
end unordered list item
std::string anonymous_namespace{print-introspected-doxygen.cc}::listStart
start unordered list
std::string anonymous_namespace{print-introspected-doxygen.cc}::listStop
end unordered list
std::string anonymous_namespace{print-introspected-doxygen.cc}::note
start a note section
std::string anonymous_namespace{print-introspected-doxygen.cc}::page
start a separate page
std::string anonymous_namespace{print-introspected-doxygen.cc}::reference
reference tag
std::string anonymous_namespace{print-introspected-doxygen.cc}::referenceNo
block automatic references
std::string anonymous_namespace{print-introspected-doxygen.cc}::returns
the return value
std::string anonymous_namespace{print-introspected-doxygen.cc}::sectionStart
start of a section or group
std::string anonymous_namespace{print-introspected-doxygen.cc}::seeAlso
Reference to other docs.
std::string anonymous_namespace{print-introspected-doxygen.cc}::subSectionStart
start a new subsection
std::string anonymous_namespace{print-introspected-doxygen.cc}::templArgDeduced
template argument deduced from function
std::string anonymous_namespace{print-introspected-doxygen.cc}::templArgExplicit
template argument required
std::string anonymous_namespace{print-introspected-doxygen.cc}::templateArgument
template argument
std::string anonymous_namespace{print-introspected-doxygen.cc}::variable
variable or class member
std::string anonymous_namespace{print-introspected-doxygen.cc}::anchor
Markup tokens.
std::string anonymous_namespace{print-introspected-doxygen.cc}::argument
function argument
std::string anonymous_namespace{print-introspected-doxygen.cc}::boldStart
start of bold span
std::string anonymous_namespace{print-introspected-doxygen.cc}::boldStop
end of bold span
std::string anonymous_namespace{print-introspected-doxygen.cc}::breakBoth
linebreak
std::string anonymous_namespace{print-introspected-doxygen.cc}::breakHtmlOnly
linebreak for html output only
std::string anonymous_namespace{print-introspected-doxygen.cc}::breakTextOnly
linebreak for text output only
std::string anonymous_namespace{print-introspected-doxygen.cc}::brief
brief tag
std::string anonymous_namespace{print-introspected-doxygen.cc}::classStart
start of a class
std::string anonymous_namespace{print-introspected-doxygen.cc}::classStop
end of a class
std::string anonymous_namespace{print-introspected-doxygen.cc}::codeWord
format next word as source code
std::string anonymous_namespace{print-introspected-doxygen.cc}::commentStart
start of code comment
std::string anonymous_namespace{print-introspected-doxygen.cc}::commentStop
end of code comment
std::string anonymous_namespace{print-introspected-doxygen.cc}::copyDoc
copy (or refer) to docs elsewhere
std::string anonymous_namespace{print-introspected-doxygen.cc}::file
file
std::string anonymous_namespace{print-introspected-doxygen.cc}::flagSpanStart
start of Attribute flag value
std::string anonymous_namespace{print-introspected-doxygen.cc}::flagSpanStop
end of Attribute flag value
std::string anonymous_namespace{print-introspected-doxygen.cc}::functionStart
start of a method/function
std::string anonymous_namespace{print-introspected-doxygen.cc}::functionStop
end of a method/function
std::string anonymous_namespace{print-introspected-doxygen.cc}::headingStart
start of section heading (h3)
std::string anonymous_namespace{print-introspected-doxygen.cc}::headingStop
end of section heading (h3)
std::string anonymous_namespace{print-introspected-doxygen.cc}::hrefStart
start of a link
std::string anonymous_namespace{print-introspected-doxygen.cc}::hrefMid
middle part of a link
std::string anonymous_namespace{print-introspected-doxygen.cc}::hrefStop
end of a link
std::string anonymous_namespace{print-introspected-doxygen.cc}::indentHtmlOnly
small indent
std::string anonymous_namespace{print-introspected-doxygen.cc}::listLineStart
start unordered list item
std::string anonymous_namespace{print-introspected-doxygen.cc}::listLineStop
end unordered list item
std::string anonymous_namespace{print-introspected-doxygen.cc}::listStart
start unordered list
std::string anonymous_namespace{print-introspected-doxygen.cc}::listStop
end unordered list
std::string anonymous_namespace{print-introspected-doxygen.cc}::note
start a note section
std::string anonymous_namespace{print-introspected-doxygen.cc}::page
start a separate page
std::string anonymous_namespace{print-introspected-doxygen.cc}::reference
reference tag
std::string anonymous_namespace{print-introspected-doxygen.cc}::referenceNo
block automatic references
std::string anonymous_namespace{print-introspected-doxygen.cc}::returns
the return value
std::string anonymous_namespace{print-introspected-doxygen.cc}::sectionStart
start of a section or group
std::string anonymous_namespace{print-introspected-doxygen.cc}::seeAlso
Reference to other docs.
std::string anonymous_namespace{print-introspected-doxygen.cc}::subSectionStart
start a new subsection
std::string anonymous_namespace{print-introspected-doxygen.cc}::templArgDeduced
template argument deduced from function
std::string anonymous_namespace{print-introspected-doxygen.cc}::templArgExplicit
template argument required
std::string anonymous_namespace{print-introspected-doxygen.cc}::templateArgument
template argument
std::string anonymous_namespace{print-introspected-doxygen.cc}::variable
variable or class member
Detailed Description
Generate documentation from the TypeId database.
Definition in file print-introspected-doxygen.cc.
Typedef Documentation
NameMap
typedef std::map< std::string, int32_t> NameMap
Map from TypeId name to tid.
Definition at line 570 of file print-introspected-doxygen.cc.
NameMapIterator
typedef NameMap::const_iterator NameMapIterator
NameMap iterator.
Definition at line 571 of file print-introspected-doxygen.cc.
Function Documentation
GetNameMap()
NameMap GetNameMap (void)
Create a map from the class names to their index in the vector of TypeId's so that the names will end up in alphabetical order.
Returns
NameMap
Definition at line 581 of file print-introspected-doxygen.cc.
References ns3::TypeId::GetName(), StaticInformation::GetNoTypeIds(), ns3::TypeId::GetRegistered(), ns3::TypeId::GetRegisteredN(), GetTypicalAggregations(), ns3::TypeId::MustHideFromDocumentation(), and NS_LOG_FUNCTION_NOARGS.
Referenced by PrintAllAttributes(), PrintAllTraceSources(), PrintAllTypeIds(), and PrintTypeIdBlocks().
GetTypicalAggregations()
StaticInformation GetTypicalAggregations ()
Register aggregation relationships that are not automatically detected by this introspection program.
Statements added here result in more configuration paths being added to the doxygen.
Returns
instance of StaticInformation with the registered information
Definition at line 510 of file print-introspected-doxygen.cc.
References StaticInformation::Gather(), ns3::Object::GetInstanceTypeId(), ns3::Config::GetRootNamespaceObject(), ns3::Config::GetRootNamespaceObjectN(), NS_LOG_FUNCTION_NOARGS, and StaticInformation::RecordAggregationInfo().
Referenced by GetNameMap(), and PrintConfigPaths().
PrintAllAttributes()
void PrintAllAttributes (std::ostream & os)
Print the list of all Attributes.
Parameters
[in,out] os The output stream.
Todo:
Print this sorted by class (the current version) as well as by Attribute name.
Definition at line 1050 of file print-introspected-doxygen.cc.
References anonymous_namespace{print-introspected-doxygen.cc}::boldStart, anonymous_namespace{print-introspected-doxygen.cc}::boldStop, anonymous_namespace{print-introspected-doxygen.cc}::breakHtmlOnly, anonymous_namespace{print-introspected-doxygen.cc}::commentStart, anonymous_namespace{print-introspected-doxygen.cc}::commentStop, ns3::TypeId::GetAttribute(), ns3::TypeId::GetAttributeN(), ns3::TypeId::GetName(), GetNameMap(), ns3::TypeId::GetRegistered(), ns3::TypeId::AttributeInformation::help, anonymous_namespace{print-introspected-doxygen.cc}::listLineStart, anonymous_namespace{print-introspected-doxygen.cc}::listLineStop, anonymous_namespace{print-introspected-doxygen.cc}::listStart, anonymous_namespace{print-introspected-doxygen.cc}::listStop, ns3::TypeId::AttributeInformation::name, NS_LOG_FUNCTION_NOARGS, anonymous_namespace{print-introspected-doxygen.cc}::page, and anonymous_namespace{print-introspected-doxygen.cc}::reference.
PrintAllGlobals()
void PrintAllGlobals (std::ostream & os)
Print the list of all global variables.
Parameters
[in,out] os The output stream.
Definition at line 1104 of file print-introspected-doxygen.cc.
References ns3::GlobalValue::Begin(), anonymous_namespace{print-introspected-doxygen.cc}::boldStart, anonymous_namespace{print-introspected-doxygen.cc}::boldStop, anonymous_namespace{print-introspected-doxygen.cc}::commentStart, anonymous_namespace{print-introspected-doxygen.cc}::commentStop, ns3::GlobalValue::End(), ns3::StringValue::Get(), anonymous_namespace{print-introspected-doxygen.cc}::hrefMid, anonymous_namespace{print-introspected-doxygen.cc}::hrefStart, anonymous_namespace{print-introspected-doxygen.cc}::hrefStop, anonymous_namespace{print-introspected-doxygen.cc}::indentHtmlOnly, anonymous_namespace{print-introspected-doxygen.cc}::listLineStart, anonymous_namespace{print-introspected-doxygen.cc}::listLineStop, anonymous_namespace{print-introspected-doxygen.cc}::listStart, anonymous_namespace{print-introspected-doxygen.cc}::listStop, NS_LOG_FUNCTION_NOARGS, anonymous_namespace{print-introspected-doxygen.cc}::page, and anonymous_namespace{print-introspected-doxygen.cc}::reference.
PrintAllLogComponents()
void PrintAllLogComponents (std::ostream & os)
Print the list of all LogComponents.
Parameters
[in,out] os The output stream.
Todo:
Switch to a border-less table, so the file links align See http://www.stack.nl/~dimitri/doxygen/manual/htmlcmds.html
Definition at line 1144 of file print-introspected-doxygen.cc.
References anonymous_namespace{print-introspected-doxygen.cc}::commentStart, anonymous_namespace{print-introspected-doxygen.cc}::commentStop, anonymous_namespace{print-introspected-doxygen.cc}::file, ns3::LogComponent::GetComponentList(), max, NS_LOG_FUNCTION_NOARGS, anonymous_namespace{print-introspected-doxygen.cc}::page, and anonymous_namespace{print-introspected-doxygen.cc}::reference.
PrintAllTraceSources()
void PrintAllTraceSources (std::ostream & os)
Print the list of all Trace sources.
Parameters
[in,out] os The output stream.
Todo:
Print this sorted by class (the current version) as well as by TraceSource name.
Definition at line 1207 of file print-introspected-doxygen.cc.
References anonymous_namespace{print-introspected-doxygen.cc}::boldStart, anonymous_namespace{print-introspected-doxygen.cc}::boldStop, anonymous_namespace{print-introspected-doxygen.cc}::breakHtmlOnly, anonymous_namespace{print-introspected-doxygen.cc}::commentStart, anonymous_namespace{print-introspected-doxygen.cc}::commentStop, ns3::TypeId::GetName(), GetNameMap(), ns3::TypeId::GetRegistered(), ns3::TypeId::GetTraceSource(), ns3::TypeId::GetTraceSourceN(), ns3::TypeId::TraceSourceInformation::help, anonymous_namespace{print-introspected-doxygen.cc}::listLineStart, anonymous_namespace{print-introspected-doxygen.cc}::listLineStop, anonymous_namespace{print-introspected-doxygen.cc}::listStart, anonymous_namespace{print-introspected-doxygen.cc}::listStop, ns3::TypeId::TraceSourceInformation::name, NS_LOG_FUNCTION_NOARGS, anonymous_namespace{print-introspected-doxygen.cc}::page, and anonymous_namespace{print-introspected-doxygen.cc}::reference.
PrintAllTypeIds()
void PrintAllTypeIds (std::ostream & os)
Print the list of all TypeIds.
Parameters
[in,out] os The output stream.
Definition at line 998 of file print-introspected-doxygen.cc.
References anonymous_namespace{print-introspected-doxygen.cc}::boldStart, anonymous_namespace{print-introspected-doxygen.cc}::boldStop, anonymous_namespace{print-introspected-doxygen.cc}::commentStart, anonymous_namespace{print-introspected-doxygen.cc}::commentStop, ns3::TypeId::GetName(), GetNameMap(), ns3::TypeId::GetRegistered(), anonymous_namespace{print-introspected-doxygen.cc}::indentHtmlOnly, anonymous_namespace{print-introspected-doxygen.cc}::listLineStart, anonymous_namespace{print-introspected-doxygen.cc}::listLineStop, anonymous_namespace{print-introspected-doxygen.cc}::listStart, anonymous_namespace{print-introspected-doxygen.cc}::listStop, NS_LOG_FUNCTION_NOARGS, anonymous_namespace{print-introspected-doxygen.cc}::page, anonymous_namespace{print-introspected-doxygen.cc}::reference, and anonymous_namespace{print-introspected-doxygen.cc}::referenceNo.
PrintAttributeHelper()
void PrintAttributeHelper (std::ostream & os, const AttributeDescriptor & attr)
Print documentation corresponding to use of the ATTRIBUTE_HELPER_HEADER macro or ATTRIBUTE_VALUE_DEFINE_WITH_NAME macro.
Parameters
[in,out] os The output stream.
[in] attr The AttributeDescriptor.
Definition at line 1485 of file print-introspected-doxygen.cc.
References AttributeDescriptor::m_header, AttributeDescriptor::m_name, AttributeDescriptor::m_seeBase, AttributeDescriptor::m_type, NS_LOG_FUNCTION, PrintAttributeValueSection(), PrintAttributeValueWithName(), PrintMakeAccessors(), and PrintMakeChecker().
Referenced by PrintAttributeImplementations().
PrintAttributeImplementations()
void PrintAttributeImplementations (std::ostream & os)
Print documentation for Attribute implementations.
Parameters
os The stream to print on.
Definition at line 1502 of file print-introspected-doxygen.cc.
References NS_LOG_FUNCTION_NOARGS, PrintAttributeHelper(), PrintAttributeValueSection(), PrintAttributeValueWithName(), PrintMakeAccessors(), and PrintMakeChecker().
PrintAttributes()
void PrintAttributes (std::ostream & os, const TypeId tid)
Print the Attributes block for tid, including Attributes declared in base classes.
All Attributes of this TypeId will be printed, including those defined in parent classes.
Parameters
[in,out] os The output stream.
[in] tid The TypeId to print.
Definition at line 816 of file print-introspected-doxygen.cc.
References anonymous_namespace{print-introspected-doxygen.cc}::breakBoth, ns3::TypeId::GetAttributeN(), ns3::TypeId::GetName(), ns3::TypeId::GetParent(), anonymous_namespace{print-introspected-doxygen.cc}::headingStart, anonymous_namespace{print-introspected-doxygen.cc}::headingStop, NS_LOG_FUNCTION, and PrintAttributesTid().
Referenced by PrintTypeIdBlocks().
PrintAttributesTid()
void PrintAttributesTid (std::ostream & os, const TypeId tid)
Print direct Attributes for this TypeId.
Only attributes defined directly by this TypeId will be printed.
Parameters
[in,out] os The output stream.
[in] tid The TypeId to print.
Definition at line 684 of file print-introspected-doxygen.cc.
References ns3::TypeId::AttributeInformation::accessor, ns3::TypeId::ATTR_CONSTRUCT, ns3::TypeId::ATTR_GET, ns3::TypeId::ATTR_SET, anonymous_namespace{print-introspected-doxygen.cc}::boldStart, anonymous_namespace{print-introspected-doxygen.cc}::boldStop, ns3::TypeId::AttributeInformation::checker, ns3::TypeId::AttributeInformation::flags, anonymous_namespace{print-introspected-doxygen.cc}::flagSpanStart, anonymous_namespace{print-introspected-doxygen.cc}::flagSpanStop, ns3::TypeId::GetAttribute(), ns3::TypeId::GetAttributeN(), ns3::ObjectPtrContainerChecker::GetItemTypeId(), ns3::TypeId::GetName(), ns3::PointerChecker::GetPointeeTypeId(), ns3::TypeId::AttributeInformation::help, ns3::TypeId::AttributeInformation::initialValue, anonymous_namespace{print-introspected-doxygen.cc}::listLineStart, anonymous_namespace{print-introspected-doxygen.cc}::listLineStop, anonymous_namespace{print-introspected-doxygen.cc}::listStart, anonymous_namespace{print-introspected-doxygen.cc}::listStop, ns3::TypeId::AttributeInformation::name, NS_LOG_FUNCTION, ns3::PeekPointer(), and anonymous_namespace{print-introspected-doxygen.cc}::reference.
Referenced by PrintAttributes().
PrintAttributeValueSection()
void PrintAttributeValueSection (std::ostream & os, const std::string & name, const bool seeBase = true)
Print the section definition for an AttributeValue.
In doxygen form this will print a comment block with
*   \ingroup attribute
*   \defgroup attribute_<name>Value <name>Value
*
Parameters
[in,out] os The output stream.
[in] name The base name of the resulting AttributeValue type.
[in] seeBase Print a "see also" pointing to the base class.
Definition at line 1275 of file print-introspected-doxygen.cc.
References anonymous_namespace{print-introspected-doxygen.cc}::commentStart, anonymous_namespace{print-introspected-doxygen.cc}::commentStop, NS_LOG_FUNCTION, anonymous_namespace{print-introspected-doxygen.cc}::sectionStart, anonymous_namespace{print-introspected-doxygen.cc}::seeAlso, and anonymous_namespace{print-introspected-doxygen.cc}::subSectionStart.
Referenced by PrintAttributeHelper(), and PrintAttributeImplementations().
PrintAttributeValueWithName()
void PrintAttributeValueWithName (std::ostream & os, const std::string & name, const std::string & type, const std::string & header)
Print the AttributeValue documentation for a class.
This will print documentation for the AttributeValue class and methods.
Parameters
[in,out] os The output stream.
[in] name The token to use in defining the accessor name.
[in] type The underlying type name.
[in] header The header file which contains this declaration.
Definition at line 1316 of file print-introspected-doxygen.cc.
References anonymous_namespace{print-introspected-doxygen.cc}::argument, anonymous_namespace{print-introspected-doxygen.cc}::classStart, anonymous_namespace{print-introspected-doxygen.cc}::codeWord, anonymous_namespace{print-introspected-doxygen.cc}::commentStart, anonymous_namespace{print-introspected-doxygen.cc}::commentStop, anonymous_namespace{print-introspected-doxygen.cc}::functionStart, NS_LOG_FUNCTION, anonymous_namespace{print-introspected-doxygen.cc}::returns, anonymous_namespace{print-introspected-doxygen.cc}::sectionStart, anonymous_namespace{print-introspected-doxygen.cc}::seeAlso, anonymous_namespace{print-introspected-doxygen.cc}::templArgExplicit, anonymous_namespace{print-introspected-doxygen.cc}::templateArgument, and anonymous_namespace{print-introspected-doxygen.cc}::variable.
Referenced by PrintAttributeHelper(), and PrintAttributeImplementations().
PrintConfigPaths()
void PrintConfigPaths (std::ostream & os, const TypeId tid)
Print config paths.
Parameters
os the output stream
tid the type ID
Definition at line 638 of file print-introspected-doxygen.cc.
References anonymous_namespace{print-introspected-doxygen.cc}::breakBoth, anonymous_namespace{print-introspected-doxygen.cc}::breakTextOnly, StaticInformation::Get(), ns3::TypeId::GetName(), GetTypicalAggregations(), anonymous_namespace{print-introspected-doxygen.cc}::headingStart, anonymous_namespace{print-introspected-doxygen.cc}::headingStop, anonymous_namespace{print-introspected-doxygen.cc}::listLineStart, anonymous_namespace{print-introspected-doxygen.cc}::listLineStop, anonymous_namespace{print-introspected-doxygen.cc}::listStart, anonymous_namespace{print-introspected-doxygen.cc}::listStop, and NS_LOG_FUNCTION.
Referenced by PrintTypeIdBlocks().
PrintMakeAccessors()
void PrintMakeAccessors (std::ostream & os, const std::string & name)
Print the AttributeValue MakeAccessor documentation for a class.
This will print documentation for the Make<name>Accessor functions.
Parameters
[in,out] os The output stream.
[in] name The token to use in defining the accessor name.
Definition at line 1403 of file print-introspected-doxygen.cc.
References anonymous_namespace{print-introspected-doxygen.cc}::commentStart, anonymous_namespace{print-introspected-doxygen.cc}::commentStop, anonymous_namespace{print-introspected-doxygen.cc}::copyDoc, anonymous_namespace{print-introspected-doxygen.cc}::functionStart, NS_LOG_FUNCTION, anonymous_namespace{print-introspected-doxygen.cc}::sectionStart, and anonymous_namespace{print-introspected-doxygen.cc}::seeAlso.
Referenced by PrintAttributeHelper(), and PrintAttributeImplementations().
PrintMakeChecker()
void PrintMakeChecker (std::ostream & os, const std::string & name, const std::string & header)
Print the AttributeValue MakeChecker documentation for a class.
This will print documentation for the Make<name>Checker function.
Parameters
[in,out] os The output stream.
[in] name The token to use in defining the accessor name.
[in] header The header file which contains this declaration.
Definition at line 1439 of file print-introspected-doxygen.cc.
References anonymous_namespace{print-introspected-doxygen.cc}::classStart, anonymous_namespace{print-introspected-doxygen.cc}::commentStart, anonymous_namespace{print-introspected-doxygen.cc}::commentStop, anonymous_namespace{print-introspected-doxygen.cc}::functionStart, NS_LOG_FUNCTION, anonymous_namespace{print-introspected-doxygen.cc}::returns, anonymous_namespace{print-introspected-doxygen.cc}::sectionStart, and anonymous_namespace{print-introspected-doxygen.cc}::seeAlso.
Referenced by PrintAttributeHelper(), and PrintAttributeImplementations().
PrintSize()
void PrintSize (std::ostream & os, const TypeId tid)
Print the size of the type represented by this tid.
Parameters
[in,out] os The output stream.
[in] tid The TypeId to print.
Definition at line 933 of file print-introspected-doxygen.cc.
References anonymous_namespace{print-introspected-doxygen.cc}::boldStart, anonymous_namespace{print-introspected-doxygen.cc}::boldStop, ns3::TypeId::GetSize(), NS_ASSERT_MSG(), and NS_LOG_FUNCTION.
Referenced by PrintTypeIdBlocks().
PrintTraceSources()
void PrintTraceSources (std::ostream & os, const TypeId tid)
Print the Trace sources block for tid, including Trace sources declared in base classes.
All Trace sources of this TypeId will be printed, including those defined in parent classes.
Parameters
[in,out] os The output stream.
[in] tid The TypeId to print.
Definition at line 893 of file print-introspected-doxygen.cc.
References anonymous_namespace{print-introspected-doxygen.cc}::breakBoth, ns3::TypeId::GetName(), ns3::TypeId::GetParent(), ns3::TypeId::GetTraceSourceN(), anonymous_namespace{print-introspected-doxygen.cc}::headingStart, anonymous_namespace{print-introspected-doxygen.cc}::headingStop, NS_LOG_FUNCTION, and PrintTraceSourcesTid().
Referenced by PrintTypeIdBlocks().
PrintTraceSourcesTid()
void PrintTraceSourcesTid (std::ostream & os, const TypeId tid)
Print direct Trace sources for this TypeId.
Only Trace sources defined directly by this TypeId will be printed.
Parameters
[in,out] os The output stream.
[in] tid The TypeId to print.
Definition at line 862 of file print-introspected-doxygen.cc.
References anonymous_namespace{print-introspected-doxygen.cc}::boldStart, anonymous_namespace{print-introspected-doxygen.cc}::boldStop, anonymous_namespace{print-introspected-doxygen.cc}::breakBoth, ns3::TypeId::TraceSourceInformation::callback, ns3::TypeId::GetTraceSource(), ns3::TypeId::GetTraceSourceN(), ns3::TypeId::TraceSourceInformation::help, anonymous_namespace{print-introspected-doxygen.cc}::listLineStart, anonymous_namespace{print-introspected-doxygen.cc}::listLineStop, anonymous_namespace{print-introspected-doxygen.cc}::listStart, anonymous_namespace{print-introspected-doxygen.cc}::listStop, ns3::TypeId::TraceSourceInformation::name, and NS_LOG_FUNCTION.
Referenced by PrintTraceSources().
PrintTypeIdBlocks()
void PrintTypeIdBlocks (std::ostream & os)
Print the doxy block for each TypeId.
Parameters
[in,out] os The output stream.
Definition at line 953 of file print-introspected-doxygen.cc.
References anonymous_namespace{print-introspected-doxygen.cc}::classStart, anonymous_namespace{print-introspected-doxygen.cc}::commentStart, anonymous_namespace{print-introspected-doxygen.cc}::commentStop, ns3::TypeId::GetName(), GetNameMap(), ns3::TypeId::GetRegistered(), NS_LOG_FUNCTION_NOARGS, PrintAttributes(), PrintConfigPaths(), PrintSize(), and PrintTraceSources().
SetMarkup()
void SetMarkup (bool outputText)
Initialize the markup strings, for either doxygen or text.
Parameters
[in] outputText true for text output, false for doxygen output.
Definition at line 108 of file print-introspected-doxygen.cc.
References anonymous_namespace{print-introspected-doxygen.cc}::anchor, anonymous_namespace{print-introspected-doxygen.cc}::argument, anonymous_namespace{print-introspected-doxygen.cc}::boldStart, anonymous_namespace{print-introspected-doxygen.cc}::boldStop, anonymous_namespace{print-introspected-doxygen.cc}::breakBoth, anonymous_namespace{print-introspected-doxygen.cc}::breakHtmlOnly, anonymous_namespace{print-introspected-doxygen.cc}::breakTextOnly, anonymous_namespace{print-introspected-doxygen.cc}::brief, anonymous_namespace{print-introspected-doxygen.cc}::classStart, anonymous_namespace{print-introspected-doxygen.cc}::classStop, anonymous_namespace{print-introspected-doxygen.cc}::codeWord, anonymous_namespace{print-introspected-doxygen.cc}::commentStart, anonymous_namespace{print-introspected-doxygen.cc}::commentStop, anonymous_namespace{print-introspected-doxygen.cc}::copyDoc, anonymous_namespace{print-introspected-doxygen.cc}::file, anonymous_namespace{print-introspected-doxygen.cc}::flagSpanStart, anonymous_namespace{print-introspected-doxygen.cc}::flagSpanStop, anonymous_namespace{print-introspected-doxygen.cc}::functionStart, anonymous_namespace{print-introspected-doxygen.cc}::functionStop, anonymous_namespace{print-introspected-doxygen.cc}::headingStart, anonymous_namespace{print-introspected-doxygen.cc}::headingStop, anonymous_namespace{print-introspected-doxygen.cc}::hrefMid, anonymous_namespace{print-introspected-doxygen.cc}::hrefStart, anonymous_namespace{print-introspected-doxygen.cc}::hrefStop, anonymous_namespace{print-introspected-doxygen.cc}::indentHtmlOnly, anonymous_namespace{print-introspected-doxygen.cc}::listLineStart, anonymous_namespace{print-introspected-doxygen.cc}::listLineStop, anonymous_namespace{print-introspected-doxygen.cc}::listStart, anonymous_namespace{print-introspected-doxygen.cc}::listStop, anonymous_namespace{print-introspected-doxygen.cc}::note, NS_LOG_FUNCTION, anonymous_namespace{print-introspected-doxygen.cc}::page, anonymous_namespace{print-introspected-doxygen.cc}::reference, anonymous_namespace{print-introspected-doxygen.cc}::referenceNo, anonymous_namespace{print-introspected-doxygen.cc}::returns, anonymous_namespace{print-introspected-doxygen.cc}::sectionStart, anonymous_namespace{print-introspected-doxygen.cc}::seeAlso, anonymous_namespace{print-introspected-doxygen.cc}::subSectionStart, anonymous_namespace{print-introspected-doxygen.cc}::templArgDeduced, anonymous_namespace{print-introspected-doxygen.cc}::templArgExplicit, anonymous_namespace{print-introspected-doxygen.cc}::templateArgument, and anonymous_namespace{print-introspected-doxygen.cc}::variable.
Uniquefy()
template<typename T > void Uniquefy (T t)
Helper to keep only the unique items in a container.
The container is modified in place; the elements end up sorted.
The container must support begin(), end() and erase(), which, among the STL containers, limits this to std::vector, std::dequeue and std::list.
The container elements must support operator< (for std::sort) and operator== (for std::unique).
Template Parameters
T [deduced] The container type.
Parameters
t The container.
Definition at line 396 of file print-introspected-doxygen.cc.
Referenced by StaticInformation::Gather(), and StaticInformation::GetNoTypeIds().