ns-3: src/visualizer/model/pyviz.cc File Reference
pyviz.cc File Reference
#include <cstdlib>
#include "pyviz.h"
#include "ns3/simulator.h"
#include "ns3/config.h"
#include "ns3/node-list.h"
#include "ns3/wifi-net-device.h"
#include "ns3/ppp-header.h"
#include "ns3/wifi-mac-header.h"
#include "ns3/ethernet-header.h"
#include "ns3/log.h"
#include "ns3/abort.h"
#include "visual-simulator-impl.h"
#include <sstream>
Classes
class ns3::anonymous_namespace{pyviz.cc}::FastClipping
Adapted from http://en.wikipedia.org/w/index.php?title=Line_clipping&oldid=248609574.
struct ns3::anonymous_namespace{pyviz.cc}::FastClipping::Line
Line structure.
struct ns3::PyVizPacketTag
PyVizPacketTag structure.
struct ns3::anonymous_namespace{pyviz.cc}::FastClipping::Vector2
Vector2 structure.
Namespaces
ns3
Every class exported by the ns3 library is enclosed in the ns3 namespace.
ns3::anonymous_namespace{pyviz.cc}
Macros
#define NUM_LAST_PACKETS 10
Functions
static std::vector< std::string > PathSplit (std::string str)
Variables
static PyViz * ns3::g_visualizer = NULL
the visualizer
Macro Definition Documentation
NUM_LAST_PACKETS
#define NUM_LAST_PACKETS 10
Definition at line 40 of file pyviz.cc.
Function Documentation
PathSplit()
static std::vector<std::string> PathSplit (std::string str) static
Definition at line 43 of file pyviz.cc.
Referenced by ns3::PyViz::TraceDevQueueDrop(), ns3::PyViz::TraceNetDevRxCommon(), and ns3::PyViz::TraceNetDevTxCommon().