ns-3: src/lorawan/examples/receive-path-test.cc File Reference
receive-path-test.cc File Reference
#include "ns3/log.h"
#include "ns3/command-line.h"
#include "ns3/gateway-lora-phy.h"
#include <cstdlib>
Functions
void Interference (Ptr< const Packet > packet, uint32_t node)
void NoMoreDemodulators (Ptr< const Packet > packet, uint32_t node)
void OccupiedReceptionPaths (int oldValue, int newValue)
void ReceivedPacket (Ptr< const Packet > packet, uint32_t node)
void Reset (void)
Variables
double frequency1 = 868.1
double frequency2 = 868.3
double frequency3 = 868.5
double frequency4 = 868.7
Ptr< GatewayLoraPhy > gatewayPhy
int m_interferenceCalls = 0
int m_maxOccupiedReceptionPaths = 0
int m_noMoreDemodulatorsCalls = 0
int m_receivedPacketCalls = 0
Function Documentation
Interference()
void Interference (Ptr< const Packet > packet, uint32_t node)
Definition at line 38 of file receive-path-test.cc.
References m_interferenceCalls, NS_LOG_FUNCTION, and packet.
Referenced by Reset().
NoMoreDemodulators()
void NoMoreDemodulators (Ptr< const Packet > packet, uint32_t node)
Definition at line 31 of file receive-path-test.cc.
References m_noMoreDemodulatorsCalls, NS_LOG_FUNCTION, and packet.
Referenced by Reset().
OccupiedReceptionPaths()
void OccupiedReceptionPaths (int oldValue, int newValue)
Definition at line 21 of file receive-path-test.cc.
References m_maxOccupiedReceptionPaths, and NS_LOG_FUNCTION.
Referenced by Reset().
ReceivedPacket()
void ReceivedPacket (Ptr< const Packet > packet, uint32_t node)
Definition at line 45 of file receive-path-test.cc.
References m_receivedPacketCalls, NS_LOG_FUNCTION, and packet.
Referenced by Reset().
Reset()
void Reset (void)
Definition at line 52 of file receive-path-test.cc.
References ns3::GatewayLoraPhy::AddReceptionPath(), frequency1, frequency2, frequency3, gatewayPhy, Interference(), m_interferenceCalls, m_maxOccupiedReceptionPaths, m_noMoreDemodulatorsCalls, m_receivedPacketCalls, ns3::MakeCallback(), NoMoreDemodulators(), OccupiedReceptionPaths(), ReceivedPacket(), and ns3::ObjectBase::TraceConnectWithoutContext().
Variable Documentation
frequency1
double frequency1 = 868.1
Definition at line 16 of file receive-path-test.cc.
Referenced by Reset().
frequency2
double frequency2 = 868.3
Definition at line 17 of file receive-path-test.cc.
Referenced by Reset().
frequency3
double frequency3 = 868.5
Definition at line 18 of file receive-path-test.cc.
Referenced by Reset().
frequency4
double frequency4 = 868.7
Definition at line 19 of file receive-path-test.cc.
gatewayPhy
Ptr<GatewayLoraPhy> gatewayPhy
Definition at line 10 of file receive-path-test.cc.
Referenced by Reset(), and ns3::LoraMacHelper::SetSpreadingFactorsUp().
m_interferenceCalls
int m_interferenceCalls = 0
Definition at line 12 of file receive-path-test.cc.
Referenced by Interference(), and Reset().
m_maxOccupiedReceptionPaths
int m_maxOccupiedReceptionPaths = 0
Definition at line 14 of file receive-path-test.cc.
Referenced by OccupiedReceptionPaths(), and Reset().
m_noMoreDemodulatorsCalls
int m_noMoreDemodulatorsCalls = 0
Definition at line 11 of file receive-path-test.cc.
Referenced by NoMoreDemodulators(), and Reset().
m_receivedPacketCalls
int m_receivedPacketCalls = 0
Definition at line 13 of file receive-path-test.cc.
Referenced by ReceivedPacket(), and Reset().