ns-3: src/core/test/rng-test-suite.cc File Reference
rng-test-suite.cc File Reference
#include <cmath>
#include <gsl/gsl_cdf.h>
#include <gsl/gsl_histogram.h>
#include <ctime>
#include <fstream>
#include "ns3/test.h"
#include "ns3/double.h"
#include "ns3/random-variable-stream.h"
#include "ns3/rng-seed-manager.h"
Classes
class RngExponentialTestCase
class RngNormalTestCase
class RngParetoTestCase
class RngTestSuite
class RngUniformTestCase
Functions
void FillHistoRangeUniformly (double *array, uint32_t n, double start, double end)
Variables
static RngTestSuite rngTestSuite
Function Documentation
FillHistoRangeUniformly()
void FillHistoRangeUniformly (double * array, uint32_t n, double start, double end)
Definition at line 32 of file rng-test-suite.cc.
References sample-rng-plot::n, and visualizer.core::start().
Referenced by RandomVariableStreamErlangTestCase::ChiSquaredTest(), RandomVariableStreamErlangAntitheticTestCase::ChiSquaredTest(), RandomVariableStreamExponentialTestCase::ChiSquaredTest(), RandomVariableStreamExponentialAntitheticTestCase::ChiSquaredTest(), RngExponentialTestCase::ChiSquaredTest(), RandomVariableStreamGammaTestCase::ChiSquaredTest(), RandomVariableStreamGammaAntitheticTestCase::ChiSquaredTest(), RandomVariableStreamLogNormalTestCase::ChiSquaredTest(), RandomVariableStreamLogNormalAntitheticTestCase::ChiSquaredTest(), RandomVariableStreamNormalTestCase::ChiSquaredTest(), RandomVariableStreamNormalAntitheticTestCase::ChiSquaredTest(), RngNormalTestCase::ChiSquaredTest(), RandomVariableStreamParetoTestCase::ChiSquaredTest(), RandomVariableStreamParetoAntitheticTestCase::ChiSquaredTest(), RngParetoTestCase::ChiSquaredTest(), RandomVariableStreamWeibullTestCase::ChiSquaredTest(), and RandomVariableStreamWeibullAntitheticTestCase::ChiSquaredTest().
Variable Documentation
rngTestSuite
RngTestSuite rngTestSuite static
Definition at line 428 of file rng-test-suite.cc.