ns-3: examples/tutorial/seventh.cc File Reference
seventh.cc File Reference
#include <fstream>
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/point-to-point-module.h"
#include "ns3/applications-module.h"
#include "ns3/stats-module.h"
Classes
class MyApp
Functions
static void CwndChange (Ptr< OutputStreamWrapper > stream, uint32_t oldCwnd, uint32_t newCwnd)
static void RxDrop (Ptr< PcapFileWrapper > file, Ptr< const Packet > p)
Function Documentation
CwndChange()
static void CwndChange (Ptr< OutputStreamWrapper > stream, uint32_t oldCwnd, uint32_t newCwnd) static
Definition at line 187 of file seventh.cc.
References ns3::Time::GetSeconds(), ns3::OutputStreamWrapper::GetStream(), ns3::Now(), and NS_LOG_UNCOND.
RxDrop()
static void RxDrop (Ptr< PcapFileWrapper > file, Ptr< const Packet > p) static
Definition at line 194 of file seventh.cc.
References anonymous_namespace{print-introspected-doxygen.cc}::file, ns3::Now(), and NS_LOG_UNCOND.