ns-3: src/core/test/simulator-test-suite.cc File Reference
simulator-test-suite.cc File Reference
#include "ns3/test.h"
#include "ns3/simulator.h"
#include "ns3/list-scheduler.h"
#include "ns3/heap-scheduler.h"
#include "ns3/map-scheduler.h"
#include "ns3/calendar-scheduler.h"
Classes
class SimulatorEventsTestCase
class SimulatorTemplateTestCase
class SimulatorTestSuite
Functions
static void ber1 (int &)
static void ber2 (int &, int &)
static void ber3 (int &, int &, int &)
static void ber4 (int &, int &, int &, int &)
static void ber5 (int &, int &, int &, int &, int &)
static void cber1 (const int &)
static void cber2 (const int &, const int &)
static void cber3 (const int &, const int &, const int &)
static void cber4 (const int &, const int &, const int &, const int &)
static void cber5 (const int &, const int &, const int &, const int &, const int &)
static void foo0 (void)
static void foo1 (int)
static void foo2 (int, int)
static void foo3 (int, int, int)
static void foo4 (int, int, int, int)
static void foo5 (int, int, int, int, int)
Variables
SimulatorTestSuite g_simulatorTestSuite
Function Documentation
ber1()
static void ber1 (int &) static
Definition at line 235 of file simulator-test-suite.cc.
Referenced by SimulatorTemplateTestCase::DoRun().
ber2()
static void ber2 (int & , int &) static
Definition at line 237 of file simulator-test-suite.cc.
Referenced by SimulatorTemplateTestCase::DoRun().
ber3()
static void ber3 (int & , int & , int &) static
Definition at line 239 of file simulator-test-suite.cc.
Referenced by SimulatorTemplateTestCase::DoRun().
ber4()
static void ber4 (int & , int & , int & , int &) static
Definition at line 241 of file simulator-test-suite.cc.
Referenced by SimulatorTemplateTestCase::DoRun().
ber5()
static void ber5 (int & , int & , int & , int & , int &) static
Definition at line 243 of file simulator-test-suite.cc.
Referenced by SimulatorTemplateTestCase::DoRun().
cber1()
static void cber1 (const int &) static
Definition at line 245 of file simulator-test-suite.cc.
Referenced by SimulatorTemplateTestCase::DoRun().
cber2()
static void cber2 (const int & , const int &) static
Definition at line 247 of file simulator-test-suite.cc.
Referenced by SimulatorTemplateTestCase::DoRun().
cber3()
static void cber3 (const int & , const int & , const int &) static
Definition at line 249 of file simulator-test-suite.cc.
Referenced by SimulatorTemplateTestCase::DoRun().
cber4()
static void cber4 (const int & , const int & , const int & , const int &) static
Definition at line 251 of file simulator-test-suite.cc.
Referenced by SimulatorTemplateTestCase::DoRun().
cber5()
static void cber5 (const int & , const int & , const int & , const int & , const int &) static
Definition at line 253 of file simulator-test-suite.cc.
Referenced by SimulatorTemplateTestCase::DoRun().
foo0()
static void foo0 (void) static
Definition at line 223 of file simulator-test-suite.cc.
Referenced by SimulatorTemplateTestCase::DoRun().
foo1()
static void foo1 (int) static
Definition at line 225 of file simulator-test-suite.cc.
Referenced by SimulatorTemplateTestCase::DoRun().
foo2()
static void foo2 (int , int) static
Definition at line 227 of file simulator-test-suite.cc.
Referenced by SimulatorTemplateTestCase::DoRun().
foo3()
static void foo3 (int , int , int) static
Definition at line 229 of file simulator-test-suite.cc.
Referenced by SimulatorTemplateTestCase::DoRun().
foo4()
static void foo4 (int , int , int , int) static
Definition at line 231 of file simulator-test-suite.cc.
Referenced by SimulatorTemplateTestCase::DoRun().
foo5()
static void foo5 (int , int , int , int , int) static
Definition at line 233 of file simulator-test-suite.cc.
Referenced by SimulatorTemplateTestCase::DoRun().
Variable Documentation
g_simulatorTestSuite
SimulatorTestSuite g_simulatorTestSuite