ns-3: ns3::olsr::MessageHeader::Mid Struct Reference
ns3::olsr::MessageHeader::Mid Struct Reference
OLSR Routing
#include "olsr-header.h"
Public Member Functions
uint32_t Deserialize (Buffer::Iterator start, uint32_t messageSize)
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet.
uint32_t GetSerializedSize (void) const
Returns the expected size of the header.
void Print (std::ostream &os) const
This method is used to print the content of a MID message.
void Serialize (Buffer::Iterator start) const
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet.
Public Attributes
std::vector< Ipv4Address > interfaceAddresses
Interface Address container.
Detailed Description
MID Message Format
  0                   1                   2                   3
  0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                    OLSR Interface Address                     |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                    OLSR Interface Address                     |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                              ...                              |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 313 of file olsr-header.h.
Member Function Documentation
Deserialize()
uint32_t ns3::olsr::MessageHeader::Mid::Deserialize (Buffer::Iterator start, uint32_t messageSize)
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet.
Parameters
start an iterator which points to where the header should read from.
messageSize the message size.
Returns
the number of bytes read.
Definition at line 313 of file olsr-header.cc.
References ns3::olsr::MessageHeader::GetSerializedSize(), IPV4_ADDRESS_SIZE, sample-rng-plot::n, NS_ASSERT, ns3::Buffer::Iterator::ReadNtohU32(), and visualizer.core::start().
GetSerializedSize()
uint32_t ns3::olsr::MessageHeader::Mid::GetSerializedSize (void) const
Returns the expected size of the header.
Returns
the expected size of the header.
Definition at line 289 of file olsr-header.cc.
References interfaceAddresses, and IPV4_ADDRESS_SIZE.
Print()
void ns3::olsr::MessageHeader::Mid::Print (std::ostream & os) const
This method is used to print the content of a MID message.
Parameters
os output stream
Todo:
Definition at line 295 of file olsr-header.cc.
Serialize()
void ns3::olsr::MessageHeader::Mid::Serialize (Buffer::Iterator start) const
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet.
Parameters
start an iterator which points to where the header should be written.
Definition at line 301 of file olsr-header.cc.
References visualizer.core::start(), and ns3::Buffer::Iterator::WriteHtonU32().
Member Data Documentation
interfaceAddresses
std::vector<Ipv4Address> ns3::olsr::MessageHeader::Mid::interfaceAddresses
Interface Address container.
Definition at line 315 of file olsr-header.h.
Referenced by OlsrMidTestCase::DoRun(), GetSerializedSize(), ns3::olsr::RoutingProtocol::ProcessMid(), and ns3::olsr::RoutingProtocol::SendMid().
The documentation for this struct was generated from the following files:
src/olsr/model/olsr-header.h
src/olsr/model/olsr-header.cc