ns-3: ns3::TcpTxItem::RateInformation Struct Reference
ns3::TcpTxItem::RateInformation Struct Reference
Various rate-related information, can be accessed by TcpRateOps.
#include "tcp-tx-item.h"
Public Attributes
uint64_t m_delivered {0}
Connection's delivered data at the time the packet was sent.
Time m_deliveredTime {Time::Max ()}
Connection's delivered time at the time the packet was sent.
Time m_firstSent {Time::Max ()}
Connection's first sent time at the time the packet was sent.
bool m_isAppLimited {false}
Connection's app limited at the time the packet was sent.
Detailed Description
Various rate-related information, can be accessed by TcpRateOps.
Note: This is not enforced through C++, but you developer must honour this description.
Definition at line 86 of file tcp-tx-item.h.
Member Data Documentation
m_delivered
uint64_t ns3::TcpTxItem::RateInformation::m_delivered {0}
Connection's delivered data at the time the packet was sent.
Definition at line 88 of file tcp-tx-item.h.
Referenced by TcpRateLinuxBasicTest::SendSkb(), ns3::TcpRateLinux::SkbDelivered(), and ns3::TcpRateLinux::SkbSent().
m_deliveredTime
Time ns3::TcpTxItem::RateInformation::m_deliveredTime {Time::Max ()}
Connection's delivered time at the time the packet was sent.
Definition at line 89 of file tcp-tx-item.h.
Referenced by TcpRateLinuxBasicTest::SendSkb(), TcpRateLinuxBasicTest::SkbDelivered(), ns3::TcpRateLinux::SkbDelivered(), and ns3::TcpRateLinux::SkbSent().
m_firstSent
Time ns3::TcpTxItem::RateInformation::m_firstSent {Time::Max ()}
Connection's first sent time at the time the packet was sent.
Definition at line 90 of file tcp-tx-item.h.
Referenced by ns3::TcpRateLinux::SkbDelivered(), and ns3::TcpRateLinux::SkbSent().
m_isAppLimited
bool ns3::TcpTxItem::RateInformation::m_isAppLimited {false}
Connection's app limited at the time the packet was sent.
Definition at line 91 of file tcp-tx-item.h.
Referenced by TcpRateLinuxBasicTest::SkbDelivered(), ns3::TcpRateLinux::SkbDelivered(), and ns3::TcpRateLinux::SkbSent().
The documentation for this struct was generated from the following file:
src/internet/model/tcp-tx-item.h