ns-3: ns3::aodv::AodvRtableEntryTest Struct Reference
ns3::aodv::AodvRtableEntryTest Struct Reference
AODV Routing » AODV module tests | Test suites
Unit test for AODV routing table entry.
Public Member Functions
AodvRtableEntryTest ()
virtual void DoRun ()
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Unit test for AODV routing table entry.
Definition at line 504 of file aodv-test-suite.cc.
Constructor & Destructor Documentation
AodvRtableEntryTest()
ns3::aodv::AodvRtableEntryTest::AodvRtableEntryTest () inline
Definition at line 506 of file aodv-test-suite.cc.
Member Function Documentation
DoRun()
virtual void ns3::aodv::AodvRtableEntryTest::DoRun () inline virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 509 of file aodv-test-suite.cc.
References ns3::aodv::RoutingTableEntry::DeleteAllPrecursors(), ns3::aodv::RoutingTableEntry::DeletePrecursor(), ns3::Simulator::Destroy(), ns3::aodv::RoutingTableEntry::GetBlacklistTimeout(), ns3::aodv::RoutingTableEntry::GetDestination(), ns3::Ipv4Route::GetDestination(), ns3::aodv::RoutingTableEntry::GetFlag(), ns3::aodv::RoutingTableEntry::GetHop(), ns3::aodv::RoutingTableEntry::GetInterface(), ns3::aodv::RoutingTableEntry::GetLifeTime(), ns3::aodv::RoutingTableEntry::GetNextHop(), ns3::aodv::RoutingTableEntry::GetOutputDevice(), ns3::aodv::RoutingTableEntry::GetPrecursors(), ns3::aodv::RoutingTableEntry::GetRoute(), ns3::aodv::RoutingTableEntry::GetRreqCnt(), ns3::aodv::RoutingTableEntry::GetSeqNo(), ns3::aodv::RoutingTableEntry::GetValidSeqNo(), ns3::aodv::IN_SEARCH, ns3::aodv::RoutingTableEntry::IncrementRreqCnt(), ns3::aodv::RoutingTableEntry::InsertPrecursor(), ns3::aodv::INVALID, ns3::aodv::RoutingTableEntry::Invalidate(), ns3::aodv::RoutingTableEntry::IsPrecursorListEmpty(), ns3::aodv::RoutingTableEntry::IsUnidirectional(), ns3::aodv::RoutingTableEntry::LookupPrecursor(), ns3::MilliSeconds(), NS_TEST_EXPECT_MSG_EQ, ns3::Seconds(), ns3::aodv::RoutingTableEntry::SetBlacklistTimeout(), ns3::aodv::RoutingTableEntry::SetFlag(), ns3::aodv::RoutingTableEntry::SetHop(), ns3::aodv::RoutingTableEntry::SetInterface(), ns3::aodv::RoutingTableEntry::SetLifeTime(), ns3::aodv::RoutingTableEntry::SetNextHop(), ns3::aodv::RoutingTableEntry::SetOutputDevice(), ns3::aodv::RoutingTableEntry::SetRreqCnt(), ns3::aodv::RoutingTableEntry::SetUnidirectional(), ns3::aodv::RoutingTableEntry::SetValidSeqNo(), and ns3::aodv::VALID.
The documentation for this struct was generated from the following file:
src/aodv/test/aodv-test-suite.cc