ns-3: ns3::aodv::QueueEntryTest Struct Reference
ns3::aodv::QueueEntryTest Struct Reference
AODV Routing » AODV module tests | Test suites
Unit test for AODV routing table entry.
Public Member Functions
QueueEntryTest ()
virtual void DoRun ()
Implementation to actually run this TestCase.
void Error (Ptr< const Packet > p, const Ipv4Header &h, Socket::SocketErrno e)
Error test function.
void Error2 (Ptr< const Packet > p, const Ipv4Header &h, Socket::SocketErrno e)
Error2 test function.
void Unicast (Ptr< Ipv4Route > route, Ptr< const Packet > packet, const Ipv4Header &header)
Unicast test function.
void Unicast2 (Ptr< Ipv4Route > route, Ptr< const Packet > packet, const Ipv4Header &header)
Unicast 2 testfunction.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Unit test for AODV routing table entry.
Definition at line 305 of file aodv-test-suite.cc.
Constructor & Destructor Documentation
QueueEntryTest()
ns3::aodv::QueueEntryTest::QueueEntryTest () inline
Definition at line 307 of file aodv-test-suite.cc.
Member Function Documentation
DoRun()
virtual void ns3::aodv::QueueEntryTest::DoRun () inline virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 346 of file aodv-test-suite.cc.
References Error(), Error2(), ns3::Ipv4Header::GetDestination(), ns3::aodv::QueueEntry::GetErrorCallback(), ns3::aodv::QueueEntry::GetExpireTime(), ns3::aodv::QueueEntry::GetIpv4Header(), ns3::aodv::QueueEntry::GetPacket(), ns3::Ipv4Header::GetSource(), ns3::aodv::QueueEntry::GetUnicastForwardCallback(), ns3::Callback< R, T1, T2, T3, T4, T5, T6, T7, T8, T9 >::IsEqual(), ns3::MakeCallback(), NS_TEST_EXPECT_MSG_EQ, ns3::Seconds(), ns3::Ipv4Header::SetDestination(), ns3::aodv::QueueEntry::SetErrorCallback(), ns3::aodv::QueueEntry::SetExpireTime(), ns3::aodv::QueueEntry::SetIpv4Header(), ns3::Ipv4Header::SetSource(), ns3::aodv::QueueEntry::SetUnicastForwardCallback(), Unicast(), and Unicast2().
Error()
void ns3::aodv::QueueEntryTest::Error (Ptr< const Packet > p, const Ipv4Header & h, Socket::SocketErrno e) inline
Error test function.
Parameters
p The packet
h The header
e the socket error
Definition at line 325 of file aodv-test-suite.cc.
Referenced by DoRun().
Error2()
void ns3::aodv::QueueEntryTest::Error2 (Ptr< const Packet > p, const Ipv4Header & h, Socket::SocketErrno e) inline
Error2 test function.
Parameters
p The packet
h The header
e the socket error
Definition at line 343 of file aodv-test-suite.cc.
Referenced by DoRun().
Unicast()
void ns3::aodv::QueueEntryTest::Unicast (Ptr< Ipv4Route > route, Ptr< const Packet > packet, const Ipv4Header & header) inline
Unicast test function.
Parameters
route the IPv4 route
packet the packet
header the IPv4 header
Definition at line 316 of file aodv-test-suite.cc.
Referenced by DoRun().
Unicast2()
void ns3::aodv::QueueEntryTest::Unicast2 (Ptr< Ipv4Route > route, Ptr< const Packet > packet, const Ipv4Header & header) inline
Unicast 2 testfunction.
Parameters
route The IPv4 route
packet The packet
header The header
Definition at line 334 of file aodv-test-suite.cc.
Referenced by DoRun().
The documentation for this struct was generated from the following file:
src/aodv/test/aodv-test-suite.cc