ns-3: ns3::TcpRateOps::TcpRateConnection Struct Reference
ns3::TcpRateOps::TcpRateConnection Struct Reference
Information about the connection rate.
#include "tcp-rate-ops.h"
Public Attributes
uint32_t m_appLimited {0}
The index of the last transmitted packet marked as application-limited.
uint64_t m_delivered {0}
The total amount of data in bytes delivered so far.
Time m_deliveredTime {Seconds (0)}
Simulator time when m_delivered was last updated.
Time m_firstSentTime {Seconds (0)}
The send time of the packet that was most recently marked as delivered.
bool m_rateAppLimited {false}
Was sample was taken when data is app limited?
int32_t m_rateDelivered {0}
The amount of data delivered considered to calculate delivery rate.
Time m_rateInterval {Seconds (0)}
The value of interval considered to calculate delivery rate.
uint32_t m_txItemDelivered {0}
The value of delivered when the acked item was sent.
Detailed Description
Information about the connection rate.
In this struct, the values are for the entire connection, and not just for an interval of time
Definition at line 161 of file tcp-rate-ops.h.
Member Data Documentation
m_appLimited
uint32_t ns3::TcpRateOps::TcpRateConnection::m_appLimited {0}
The index of the last transmitted packet marked as application-limited.
Definition at line 166 of file tcp-rate-ops.h.
Referenced by ns3::TcpRateLinux::CalculateAppLimited(), ns3::TcpRateLinux::GenerateSample(), ns3::operator<<(), ns3::operator==(), and ns3::TcpRateLinux::SkbSent().
m_delivered
uint64_t ns3::TcpRateOps::TcpRateConnection::m_delivered {0}
The total amount of data in bytes delivered so far.
Definition at line 163 of file tcp-rate-ops.h.
Referenced by ns3::TcpRateLinux::CalculateAppLimited(), ns3::TcpRateLinux::GenerateSample(), ns3::operator<<(), ns3::operator==(), ns3::TcpSocketBase::ReceivedAck(), ns3::TcpRateLinux::SkbDelivered(), and ns3::TcpRateLinux::SkbSent().
m_deliveredTime
Time ns3::TcpRateOps::TcpRateConnection::m_deliveredTime {Seconds (0)}
Simulator time when m_delivered was last updated.
Definition at line 164 of file tcp-rate-ops.h.
Referenced by ns3::operator<<(), ns3::operator==(), ns3::TcpRateLinux::SkbDelivered(), and ns3::TcpRateLinux::SkbSent().
m_firstSentTime
Time ns3::TcpRateOps::TcpRateConnection::m_firstSentTime {Seconds (0)}
The send time of the packet that was most recently marked as delivered.
Definition at line 165 of file tcp-rate-ops.h.
Referenced by ns3::operator<<(), ns3::operator==(), ns3::TcpRateLinux::SkbDelivered(), and ns3::TcpRateLinux::SkbSent().
m_rateAppLimited
bool ns3::TcpRateOps::TcpRateConnection::m_rateAppLimited {false}
Was sample was taken when data is app limited?
Definition at line 170 of file tcp-rate-ops.h.
Referenced by ns3::TcpRateLinux::GenerateSample(), and ns3::operator<<().
m_rateDelivered
int32_t ns3::TcpRateOps::TcpRateConnection::m_rateDelivered {0}
The amount of data delivered considered to calculate delivery rate.
Definition at line 168 of file tcp-rate-ops.h.
Referenced by ns3::TcpRateLinux::GenerateSample(), and ns3::operator<<().
m_rateInterval
Time ns3::TcpRateOps::TcpRateConnection::m_rateInterval {Seconds (0)}
The value of interval considered to calculate delivery rate.
Definition at line 169 of file tcp-rate-ops.h.
Referenced by ns3::TcpRateLinux::GenerateSample(), and ns3::operator<<().
m_txItemDelivered
uint32_t ns3::TcpRateOps::TcpRateConnection::m_txItemDelivered {0}
The value of delivered when the acked item was sent.
Definition at line 167 of file tcp-rate-ops.h.
Referenced by ns3::operator<<(), and ns3::TcpRateLinux::SkbDelivered().
The documentation for this struct was generated from the following file:
src/internet/model/tcp-rate-ops.h