ns-3: ns3::aodv::RreqHeaderTest Struct Reference
ns3::aodv::RreqHeaderTest Struct Reference
AODV Routing » AODV module tests | Test suites
Unit test for RREQ.
Public Member Functions
RreqHeaderTest ()
virtual void DoRun ()
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Unit test for RREQ.
Definition at line 144 of file aodv-test-suite.cc.
Constructor & Destructor Documentation
RreqHeaderTest()
ns3::aodv::RreqHeaderTest::RreqHeaderTest () inline
Definition at line 146 of file aodv-test-suite.cc.
Member Function Documentation
DoRun()
virtual void ns3::aodv::RreqHeaderTest::DoRun () inline virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 149 of file aodv-test-suite.cc.
References ns3::Packet::AddHeader(), ns3::aodv::RreqHeader::GetDestinationOnly(), ns3::aodv::RreqHeader::GetDst(), ns3::aodv::RreqHeader::GetDstSeqno(), ns3::aodv::RreqHeader::GetGratuitousRrep(), ns3::aodv::RreqHeader::GetHopCount(), ns3::aodv::RreqHeader::GetId(), ns3::aodv::RreqHeader::GetOrigin(), ns3::aodv::RreqHeader::GetOriginSeqno(), ns3::aodv::RreqHeader::GetUnknownSeqno(), NS_TEST_EXPECT_MSG_EQ, ns3::Packet::RemoveHeader(), ns3::aodv::RreqHeader::SetDestinationOnly(), ns3::aodv::RreqHeader::SetDst(), ns3::aodv::RreqHeader::SetDstSeqno(), ns3::aodv::RreqHeader::SetGratuitousRrep(), ns3::aodv::RreqHeader::SetHopCount(), ns3::aodv::RreqHeader::SetId(), ns3::aodv::RreqHeader::SetOrigin(), ns3::aodv::RreqHeader::SetOriginSeqno(), and ns3::aodv::RreqHeader::SetUnknownSeqno().
The documentation for this struct was generated from the following file:
src/aodv/test/aodv-test-suite.cc