ns-3: ns3::dsr::IsExpired Struct Reference
ns3::dsr::IsExpired Struct Reference
IsExpired structure.
Public Member Functions
bool operator() (DsrErrorBuffEntry const &e) const
comparison operator
bool operator() (DsrMaintainBuffEntry const &e) const
comparison operator
bool operator() (DsrPassiveBuffEntry const &e) const
Check for an expired entry.
bool operator() (DsrSendBuffEntry const &e) const
comparison operator
Detailed Description
IsExpired structure.
Definition at line 149 of file dsr-errorbuff.cc.
Member Function Documentation
operator()() [1/4]
bool ns3::dsr::IsExpired::operator() (DsrErrorBuffEntry const & e) const inline
comparison operator
Parameters
e entry to compare
Returns
true if entry expired
Definition at line 157 of file dsr-errorbuff.cc.
References ns3::dsr::DsrErrorBuffEntry::GetExpireTime(), and ns3::Seconds().
operator()() [2/4]
bool ns3::dsr::IsExpired::operator() (DsrMaintainBuffEntry const & e) const inline
comparison operator
Parameters
e maintain buffer entry
Returns
true if the entry is expired
Definition at line 223 of file dsr-maintain-buff.cc.
References ns3::dsr::DsrMaintainBuffEntry::GetExpireTime(), and ns3::Seconds().
operator()() [3/4]
bool ns3::dsr::IsExpired::operator() (DsrPassiveBuffEntry const & e) const inline
Check for an expired entry.
Parameters
e passive buffer entry
Returns
true if equal
Definition at line 175 of file dsr-passive-buff.cc.
References ns3::dsr::DsrPassiveBuffEntry::GetExpireTime(), and ns3::Seconds().
operator()() [4/4]
bool ns3::dsr::IsExpired::operator() (DsrSendBuffEntry const & e) const inline
comparison operator
Parameters
e entry to compare
Returns
true if expired
Definition at line 150 of file dsr-rsendbuff.cc.
References ns3::dsr::DsrSendBuffEntry::GetExpireTime(), and ns3::Seconds().
The documentation for this struct was generated from the following files:
src/dsr/model/dsr-errorbuff.cc
src/dsr/model/dsr-maintain-buff.cc
src/dsr/model/dsr-passive-buff.cc
src/dsr/model/dsr-rsendbuff.cc