ns-3: ns3::PacketSink::AddressHash Struct Reference
ns3::PacketSink::AddressHash Struct Reference
Hashing for the Address class.
Public Member Functions
size_t operator() (const Address &x) const
operator ()
Detailed Description
Hashing for the Address class.
Definition at line 154 of file packet-sink.h.
Member Function Documentation
operator()()
size_t ns3::PacketSink::AddressHash::operator() (const Address & x) const inline
operator ()
Parameters
x the address of which calculate the hash
Returns
the hash of x
Should this method go in address.h?
It calculates the hash taking the uint32_t hash value of the ipv4 address. It works only for InetSocketAddresses (Ipv4 version)
Definition at line 166 of file packet-sink.h.
References ns3::InetSocketAddress::ConvertFrom(), ns3::Ipv4Address::Get(), ns3::InetSocketAddress::GetIpv4(), ns3::InetSocketAddress::IsMatchingType(), NS_ABORT_IF, and sample-rng-plot::x.
The documentation for this struct was generated from the following file:
src/applications/model/packet-sink.h