ns-3: ns3::olsr::MessageHeader::Hna Struct Reference
ns3::olsr::MessageHeader::Hna Struct Reference
OLSR Routing
#include "olsr-header.h"
Classes
struct Association
Association item structure.
Public Member Functions
uint32_t Deserialize (Buffer::Iterator start, uint32_t messageSize)
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet.
uint32_t GetSerializedSize (void) const
Returns the expected size of the header.
void Print (std::ostream &os) const
This method is used to print the content of a MID message.
void Serialize (Buffer::Iterator start) const
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet.
Public Attributes
std::vector< Association > associations
Association container.
Detailed Description
HNA (Host Network Association) Message Format
  0                   1                   2                   3
  0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                         Network Address                       |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                             Netmask                           |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                         Network Address                       |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                             Netmask                           |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                              ...                              |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 514 of file olsr-header.h.
Member Function Documentation
Deserialize()
uint32_t ns3::olsr::MessageHeader::Hna::Deserialize (Buffer::Iterator start, uint32_t messageSize)
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet.
Parameters
start an iterator which points to where the header should read from.
messageSize the message size.
Returns
the number of bytes read.
Definition at line 502 of file olsr-header.cc.
References first::address, IPV4_ADDRESS_SIZE, sample-rng-plot::n, NS_ASSERT, ns3::Buffer::Iterator::ReadNtohU32(), and visualizer.core::start().
GetSerializedSize()
uint32_t ns3::olsr::MessageHeader::Hna::GetSerializedSize (void) const
Returns the expected size of the header.
Returns
the expected size of the header.
Definition at line 478 of file olsr-header.cc.
References IPV4_ADDRESS_SIZE.
Print()
void ns3::olsr::MessageHeader::Hna::Print (std::ostream & os) const
This method is used to print the content of a MID message.
Parameters
os output stream
Todo:
Definition at line 484 of file olsr-header.cc.
Serialize()
void ns3::olsr::MessageHeader::Hna::Serialize (Buffer::Iterator start) const
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet.
Parameters
start an iterator which points to where the header should be written.
Definition at line 490 of file olsr-header.cc.
References first::address, sample-rng-plot::n, visualizer.core::start(), and ns3::Buffer::Iterator::WriteHtonU32().
Member Data Documentation
associations
std::vector<Association> ns3::olsr::MessageHeader::Hna::associations
Association container.
Definition at line 525 of file olsr-header.h.
Referenced by OlsrHnaTestCase::DoRun(), ns3::olsr::RoutingProtocol::ProcessHna(), and ns3::olsr::RoutingProtocol::SendHna().
The documentation for this struct was generated from the following files:
src/olsr/model/olsr-header.h
src/olsr/model/olsr-header.cc