ns-3: ns3::olsr::MessageHeader::Tc Struct Reference
ns3::olsr::MessageHeader::Tc Struct Reference
OLSR Routing
#include "olsr-header.h"
Public Member Functions
uint32_t Deserialize (Buffer::Iterator start, uint32_t messageSize)
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet.
uint32_t GetSerializedSize (void) const
Returns the expected size of the header.
void Print (std::ostream &os) const
This method is used to print the content of a MID message.
void Serialize (Buffer::Iterator start) const
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet.
Public Attributes
uint16_t ansn
Advertised Neighbor Sequence Number.
std::vector< Ipv4Address > neighborAddresses
Neighbor address container.
Detailed Description
TC Message Format
  0                   1                   2                   3
  0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |              ANSN             |           Reserved            |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |               Advertised Neighbor Main Address                |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |               Advertised Neighbor Main Address                |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 |                              ...                              |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Definition at line 458 of file olsr-header.h.
Member Function Documentation
Deserialize()
uint32_t ns3::olsr::MessageHeader::Tc::Deserialize (Buffer::Iterator start, uint32_t messageSize)
This method is used by Packet::RemoveHeader to re-create a header from the byte buffer of a packet.
Parameters
start an iterator which points to where the header should read from.
messageSize the message size.
Returns
the number of bytes read.
Definition at line 453 of file olsr-header.cc.
References IPV4_ADDRESS_SIZE, sample-rng-plot::n, NS_ASSERT, ns3::Buffer::Iterator::ReadNtohU16(), ns3::Buffer::Iterator::ReadNtohU32(), and visualizer.core::start().
GetSerializedSize()
uint32_t ns3::olsr::MessageHeader::Tc::GetSerializedSize (void) const
Returns the expected size of the header.
Returns
the expected size of the header.
Definition at line 426 of file olsr-header.cc.
References IPV4_ADDRESS_SIZE.
Print()
void ns3::olsr::MessageHeader::Tc::Print (std::ostream & os) const
This method is used to print the content of a MID message.
Parameters
os output stream
Todo:
Definition at line 432 of file olsr-header.cc.
Serialize()
void ns3::olsr::MessageHeader::Tc::Serialize (Buffer::Iterator start) const
This method is used by Packet::AddHeader to store a header into the byte buffer of a packet.
Parameters
start an iterator which points to where the header should be written.
Definition at line 438 of file olsr-header.cc.
References visualizer.core::start(), ns3::Buffer::Iterator::WriteHtonU16(), and ns3::Buffer::Iterator::WriteHtonU32().
Member Data Documentation
ansn
uint16_t ns3::olsr::MessageHeader::Tc::ansn
Advertised Neighbor Sequence Number.
Definition at line 461 of file olsr-header.h.
Referenced by OlsrTcTestCase::DoRun(), ns3::olsr::RoutingProtocol::ProcessTc(), and ns3::olsr::RoutingProtocol::SendTc().
neighborAddresses
std::vector<Ipv4Address> ns3::olsr::MessageHeader::Tc::neighborAddresses
Neighbor address container.
Definition at line 460 of file olsr-header.h.
Referenced by OlsrTcTestCase::DoRun(), ns3::olsr::RoutingProtocol::ProcessTc(), ns3::olsr::TcRegressionTest::ReceivePktProbeA(), ns3::olsr::TcRegressionTest::ReceivePktProbeC(), and ns3::olsr::RoutingProtocol::SendTc().
The documentation for this struct was generated from the following files:
src/olsr/model/olsr-header.h
src/olsr/model/olsr-header.cc