ns-3: INetStack Struct Reference
INetStack Struct Reference abstract
Internet » NscTcp
Struct interface to NSC stack.
#include "sim_interface.h"
Public Member Functions
virtual ~INetStack ()
virtual void add_default_gateway (const char *addr)=0
Add a default gateway to the interface.
virtual void buffer_size (int size)=0
Set the buffer size.
virtual int cmd (const char *)
Simple interface to support sending any textual command to a stack.
virtual int get_hz ()=0
Get the timer_interrupt frequency.
virtual int get_id ()=0
Returns the internal id of the stack instance.
virtual const char * get_name ()=0
Return a short one-word name of the stack.
virtual bool get_var (const char *var, char *result, int result_len)
Optional function to get variables for this stack.
virtual void if_attach (const char *addr, const char *mask, int mtu)=0
Attach an interface to the stack.
virtual void if_receive_packet (int if_id, const void *data, int datalen)=0
Deliver complete packet to the NSC network stack.
virtual void if_send_finish (int if_id)=0
Signal the completion of send procedure to the NSC network stack.
virtual void if_send_packet (const void *data, int datalen)=0
Send complete packet to the NSC network stack.
virtual void increment_ticks ()=0
Increment the time ticks.
virtual void init (int hz)=0
Initialize the stack.
virtual struct INetStreamSocket * new_sctp_socket ()
Create a new SCTP socket.
virtual struct INetStreamSocket * new_tcp_socket ()
Create a new TCP socket.
virtual struct INetDatagramSocket * new_udp_socket ()
Create a new UDP socket.
virtual void set_diagnostic (int level)
Set the level of debugging or diagnostic information to print out.
virtual bool set_var (const char *var, const char *val)
Optional function to set variables for this stack.
virtual void show_config ()
Show the NSC configuration.
virtual int sysctl (const char *sysctl_name, void *oldval, size_t *oldlenp, void *newval, size_t newlen)
use sysctl to modify system parameters
virtual int sysctl_get (const char *name, char *value, size_t len)
Get system parameters using sysctl.
virtual int sysctl_getnum (size_t idx, char *name, size_t len)
Tell the cradle code to put the name of sysctl number 'idx' into name[].
virtual int sysctl_set (const char *name, const char *value)
Set system parameters using sysctl.
virtual void timer_interrupt ()=0
The stack timer_interrupt function.
Detailed Description
Struct interface to NSC stack.
Definition at line 31 of file sim_interface.h.
Constructor & Destructor Documentation
~INetStack()
virtual INetStack::~INetStack () inline virtual
Definition at line 33 of file sim_interface.h.
Member Function Documentation
add_default_gateway()
virtual void INetStack::add_default_gateway (const char * addr) pure virtual
Add a default gateway to the interface.
Parameters
addr gateway address
Referenced by ns3::NscTcpL4Protocol::AddInterface().
buffer_size()
virtual void INetStack::buffer_size (int size) pure virtual
Set the buffer size.
Parameters
size the buffer size.
cmd()
virtual int INetStack::cmd (const char *) inline virtual
Simple interface to support sending any textual command to a stack.
Returns
0 on success
Definition at line 249 of file sim_interface.h.
get_hz()
virtual int INetStack::get_hz () pure virtual
Get the timer_interrupt frequency.
This is used so the simulator can call the stack timer_interrupt function the correct amount of times per second. For example, lwip has a hz of 10, which it returns here to say that it's timer_interrupt should be called 10 times a second. FreeBSD uses 100, as does Linux 2.4, while Linux 2.6 uses 1000. (This is often configurable in the kernel in question, also.)
Returns
frequency
Referenced by ns3::NscTcpL4Protocol::SetNode().
get_id()
virtual int INetStack::get_id () pure virtual
Returns the internal id of the stack instance.
Purely for debugging/diagnostic purposes.
Returns
internal stack id
get_name()
virtual const char* INetStack::get_name () pure virtual
Return a short one-word name of the stack.
Should return a short one-word name of the stack. Eg. Linux 2.4.x -> linux24, FreeBSD 5.x -> freebsd5. This can be used to identify output from a stack, for example a packet trace file.
Returns
short one-word name of the stack
Referenced by ns3::Ns3NscStack::GetInstanceTypeId().
get_var()
virtual bool INetStack::get_var (const char * var, char * result, int result_len) inline virtual
Optional function to get variables for this stack.
Parameters
var the variable
result the result
result_len result length
Returns
true on success
Definition at line 218 of file sim_interface.h.
if_attach()
virtual void INetStack::if_attach (const char * addr, const char * mask, int mtu) pure virtual
Attach an interface to the stack.
Parameters
addr address
mask network mask
mtu MTU
Referenced by ns3::NscTcpL4Protocol::AddInterface().
if_receive_packet()
virtual void INetStack::if_receive_packet (int if_id, const void * data, int datalen) pure virtual
Deliver complete packet to the NSC network stack.
Parameters
if_id interface ID
data data
datalen data length
Referenced by ns3::NscTcpL4Protocol::Receive().
if_send_finish()
virtual void INetStack::if_send_finish (int if_id) pure virtual
Signal the completion of send procedure to the NSC network stack.
Parameters
if_id interface ID
Referenced by ns3::NscTcpL4Protocol::send_callback().
if_send_packet()
virtual void INetStack::if_send_packet (const void * data, int datalen) pure virtual
Send complete packet to the NSC network stack.
Parameters
data data
datalen data length
increment_ticks()
virtual void INetStack::increment_ticks () pure virtual
Increment the time ticks.
Referenced by ns3::NscTcpL4Protocol::SoftInterrupt().
init()
virtual void INetStack::init (int hz) pure virtual
Initialize the stack.
Parameters
hz timer_interrupt frequency
Referenced by ns3::NscTcpL4Protocol::SetNode().
new_sctp_socket()
virtual struct INetStreamSocket* INetStack::new_sctp_socket () inline virtual
Create a new SCTP socket.
Returns
A new SCTP socket.
Definition at line 134 of file sim_interface.h.
new_tcp_socket()
virtual struct INetStreamSocket* INetStack::new_tcp_socket () inline virtual
Create a new TCP socket.
Returns
A new TCP socket.
Definition at line 129 of file sim_interface.h.
new_udp_socket()
virtual struct INetDatagramSocket* INetStack::new_udp_socket () inline virtual
Create a new UDP socket.
Returns
A new UDP socket.
Definition at line 124 of file sim_interface.h.
set_diagnostic()
virtual void INetStack::set_diagnostic (int level) inline virtual
Set the level of debugging or diagnostic information to print out.
This normally means kernel messages printed out during initialisation but may also include extra debugging messages that are part of NSC.
Parameters
level debugging/diagnostic level
Definition at line 242 of file sim_interface.h.
set_var()
virtual bool INetStack::set_var (const char * var, const char * val) inline virtual
Optional function to set variables for this stack.
Parameters
var the variable
val the new value
Returns
true on success
Definition at line 229 of file sim_interface.h.
show_config()
virtual void INetStack::show_config () inline virtual
Show the NSC configuration.
Definition at line 206 of file sim_interface.h.
sysctl()
virtual int INetStack::sysctl (const char * sysctl_name, void * oldval, size_t * oldlenp, void * newval, size_t newlen) inline virtual
use sysctl to modify system parameters
Parameters
sysctl_name name of the parameter to modify
oldval old value
oldlenp old value length
newval new value
newlen new value length
Returns
The status code.
Definition at line 147 of file sim_interface.h.
sysctl_get()
virtual int INetStack::sysctl_get (const char * name, char * value, size_t len) inline virtual
Get system parameters using sysctl.
Parameters
name name of the parameter to modify
value value
len value length
Returns
length of the string in value, i.e. retval > len: 'output truncated'.
Definition at line 178 of file sim_interface.h.
Referenced by ns3::Ns3NscStack::Get(), and ns3::Ns3NscStack::GetInstanceTypeId().
sysctl_getnum()
virtual int INetStack::sysctl_getnum (size_t idx, char * name, size_t len) inline virtual
Tell the cradle code to put the name of sysctl number 'idx' into name[].
The idea is that this can be used to get a list of all available sysctls:
char buf[256]
for (i=0; sysctl_getnum(i, buf, sizeof(buf)) > 0 ;i++)
   puts(buf);
Parameters
idx index
name sysctl name
len sysctl length
Returns
-1 if idx is out of range and the length of the sysctl name otherwise.
Definition at line 198 of file sim_interface.h.
Referenced by ns3::Ns3NscStack::GetInstanceTypeId().
sysctl_set()
virtual int INetStack::sysctl_set (const char * name, const char * value) inline virtual
Set system parameters using sysctl.
Parameters
name name of the parameter to modify
value new value
Returns
Definition at line 163 of file sim_interface.h.
Referenced by ns3::Ns3NscStack::Set().
timer_interrupt()
virtual void INetStack::timer_interrupt () pure virtual
The stack timer_interrupt function.
Referenced by ns3::NscTcpL4Protocol::SoftInterrupt().
The documentation for this struct was generated from the following file:
src/internet/model/sim_interface.h