ns-3: MeshInformationElementVectorBist Struct Reference
MeshInformationElementVectorBist Struct Reference
Mesh Device » mesh module tests | Test suites
Built-in self test for MeshInformationElementVector and all IE.
Public Member Functions
MeshInformationElementVectorBist ()
void DoRun ()
Implementation to actually run this TestCase.
Public Member Functions inherited from ns3::TestCase
virtual ~TestCase ()
Destructor.
std::string GetName (void) const
Additional Inherited Members
Public Types inherited from ns3::TestCase
enum TestDuration { QUICK = 1, EXTENSIVE = 2, TAKES_FOREVER = 3 }
How long the test takes to execute.
Protected Member Functions inherited from ns3::TestCase
TestCase (std::string name)
Constructor.
void AddTestCase (TestCase *testCase, TestDuration duration=QUICK)
Add an individual child TestCase to this test suite.
TestCase * GetParent () const
Get the parent of this TestCsse.
bool IsStatusFailure (void) const
Check if any tests failed.
bool IsStatusSuccess (void) const
Check if all tests passed.
void SetDataDir (std::string directory)
Set the data directory where reference trace files can be found.
void ReportTestFailure (std::string cond, std::string actual, std::string limit, std::string message, std::string file, int32_t line)
Log the failure of this TestCase.
bool MustAssertOnFailure (void) const
Check if this run should assert on failure.
bool MustContinueOnFailure (void) const
Check if this run should continue on failure.
std::string CreateDataDirFilename (std::string filename)
Construct the full path to a file in the data directory.
std::string CreateTempDirFilename (std::string filename)
Construct the full path to a file in a temporary directory.
Detailed Description
Built-in self test for MeshInformationElementVector and all IE.
Definition at line 48 of file mesh-information-element-vector-test-suite.cc.
Constructor & Destructor Documentation
MeshInformationElementVectorBist()
MeshInformationElementVectorBist::MeshInformationElementVectorBist () inline
Definition at line 50 of file mesh-information-element-vector-test-suite.cc.
Member Function Documentation
DoRun()
void MeshInformationElementVectorBist::DoRun () virtual
Implementation to actually run this TestCase.
Subclasses should override this method to conduct their tests.
Implements ns3::TestCase.
Definition at line 58 of file mesh-information-element-vector-test-suite.cc.
References ns3::dot11s::IePerr::AddAddressUnit(), ns3::dot11s::IePreq::AddDestinationAddressElement(), ns3::Packet::AddHeader(), ns3::WifiInformationElementVector::AddInformationElement(), ns3::dot11s::IeBeaconTiming::AddNeighboursTimingElementUnit(), ns3::dot11s::IeRann::DecrementTtl(), ns3::dot11s::HwmpProtocol::FailedDestination::destination, ns3::dot11s::IeRann::GetMetric(), ns3::WifiInformationElementVector::GetSerializedSize(), ns3::dot11s::IeRann::GetTtl(), ns3::dot11s::IeRann::IncrementMetric(), NS_TEST_ASSERT_MSG_EQ, ns3::dot11s::REASON11S_MESH_CAPABILITY_POLICY_VIOLATION, ns3::Packet::RemoveHeader(), ns3::Seconds(), ns3::dot11s::HwmpProtocol::FailedDestination::seqnum, ns3::dot11s::IePrep::SetDestinationAddress(), ns3::dot11s::IePrep::SetDestinationSeqNumber(), ns3::dot11s::IeRann::SetDestSeqNumber(), ns3::dot11s::IePrep::SetFlags(), ns3::dot11s::IeRann::SetFlags(), ns3::dot11s::IePrep::SetHopcount(), ns3::dot11s::IePreq::SetHopcount(), ns3::dot11s::IeRann::SetHopcount(), ns3::dot11s::IePrep::SetLifetime(), ns3::dot11s::IePreq::SetLifetime(), ns3::dot11s::IePrep::SetMetric(), ns3::dot11s::IeRann::SetMetric(), ns3::dot11s::IePrep::SetOriginatorAddress(), ns3::dot11s::IePreq::SetOriginatorAddress(), ns3::dot11s::IeRann::SetOriginatorAddress(), ns3::dot11s::IePrep::SetOriginatorSeqNumber(), ns3::dot11s::IePreq::SetOriginatorSeqNumber(), ns3::dot11s::IePeerManagement::SetPeerClose(), ns3::dot11s::IePeerManagement::SetPeerConfirm(), ns3::dot11s::IePeerManagement::SetPeerOpen(), ns3::dot11s::IePreq::SetPreqID(), ns3::dot11s::IePrep::SetTtl(), ns3::dot11s::IePreq::SetTTL(), and ns3::dot11s::IeRann::SetTTL().
The documentation for this struct was generated from the following file:
src/mesh/test/mesh-information-element-vector-test-suite.cc