ns-3: src/internet/test/tcp-test.cc File Reference
tcp-test.cc File Reference
#include "ns3/test.h"
#include "ns3/socket-factory.h"
#include "ns3/tcp-socket-factory.h"
#include "ns3/simulator.h"
#include "ns3/simple-channel.h"
#include "ns3/simple-net-device.h"
#include "ns3/config.h"
#include "ns3/ipv4-static-routing.h"
#include "ns3/ipv4-list-routing.h"
#include "ns3/ipv6-static-routing.h"
#include "ns3/ipv6-list-routing.h"
#include "ns3/node.h"
#include "ns3/inet-socket-address.h"
#include "ns3/inet6-socket-address.h"
#include "ns3/uinteger.h"
#include "ns3/log.h"
#include "ns3/arp-l3-protocol.h"
#include "ns3/ipv4-l3-protocol.h"
#include "ns3/ipv6-l3-protocol.h"
#include "ns3/icmpv4-l4-protocol.h"
#include "ns3/icmpv6-l4-protocol.h"
#include "ns3/udp-l4-protocol.h"
#include "ns3/tcp-l4-protocol.h"
#include "ns3/traffic-control-layer.h"
#include <string>
Classes
class TcpTestCase
TCP Test - send string data from client to server and back.
class TcpTestSuite
TCP TestSuite - send string data from client to server and back.
Functions
static std::string GetString (Ptr< Packet > p)
static std::string Name (std::string str, uint32_t totalStreamSize, uint32_t sourceWriteSize, uint32_t serverReadSize, uint32_t serverWriteSize, uint32_t sourceReadSize, bool useIpv6)
Variables
static TcpTestSuite g_tcpTestSuite
Static variable for test initialization.
Function Documentation
GetString()
static std::string GetString (Ptr< Packet > p) inline static
Definition at line 180 of file tcp-test.cc.
References ns3::Packet::CopyData(), and ns3::Packet::GetSize().
Referenced by TcpTestCase::ServerHandleRecv(), TcpTestCase::ServerHandleSend(), TcpTestCase::SourceHandleRecv(), and TcpTestCase::SourceHandleSend().
Name()
static std::string Name (std::string str, uint32_t totalStreamSize, uint32_t sourceWriteSize, uint32_t serverReadSize, uint32_t serverWriteSize, uint32_t sourceReadSize, bool useIpv6) static
Definition at line 166 of file tcp-test.cc.
Variable Documentation
g_tcpTestSuite
TcpTestSuite g_tcpTestSuite static
Static variable for test initialization.
Definition at line 549 of file tcp-test.cc.