ns-3: examples/tcp/tcp-large-transfer.cc File Reference
tcp-large-transfer.cc File Reference
#include <iostream>
#include <fstream>
#include <string>
#include "ns3/core-module.h"
#include "ns3/applications-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/point-to-point-module.h"
#include "ns3/ipv4-global-routing-helper.h"
Functions
static void CwndTracer (uint32_t oldval, uint32_t newval)
void StartFlow (Ptr< Socket >, Ipv4Address, uint16_t)
void WriteUntilBufferFull (Ptr< Socket >, uint32_t)
Variables
static uint32_t currentTxBytes = 0
uint8_t data [writeSize]
static const uint32_t totalTxBytes = 2000000
static const uint32_t writeSize = 1040
Function Documentation
CwndTracer()
static void CwndTracer (uint32_t oldval, uint32_t newval) static
Definition at line 64 of file tcp-large-transfer.cc.
References NS_LOG_INFO.
StartFlow()
void StartFlow (Ptr< Socket > localSocket, Ipv4Address servAddress, uint16_t servPort)
Definition at line 185 of file tcp-large-transfer.cc.
References ns3::Socket::Connect(), ns3::Socket::GetTxAvailable(), ns3::MakeCallback(), ns3::Simulator::Now(), NS_LOG_LOGIC(), ns3::Socket::SetSendCallback(), and WriteUntilBufferFull().
WriteUntilBufferFull()
void WriteUntilBufferFull (Ptr< Socket > localSocket, uint32_t txSpace)
Definition at line 198 of file tcp-large-transfer.cc.
References ns3::Socket::Close(), currentTxBytes, data, ns3::Socket::GetTxAvailable(), min, ns3::Socket::Send(), totalTxBytes, and writeSize.
Referenced by StartFlow().
Variable Documentation
currentTxBytes
uint32_t currentTxBytes = 0 static
Definition at line 49 of file tcp-large-transfer.cc.
Referenced by WriteUntilBufferFull().
data
uint8_t data[writeSize]
Definition at line 53 of file tcp-large-transfer.cc.
Referenced by WriteUntilBufferFull().
totalTxBytes
const uint32_t totalTxBytes = 2000000 static
Definition at line 48 of file tcp-large-transfer.cc.
Referenced by WriteUntilBufferFull().
writeSize
const uint32_t writeSize = 1040 static
Definition at line 52 of file tcp-large-transfer.cc.
Referenced by WriteUntilBufferFull().