ns-3: src/spectrum/examples/three-gpp-channel-example.cc File Reference
three-gpp-channel-example.cc File Reference
#include "ns3/core-module.h"
#include "ns3/three-gpp-channel-model.h"
#include "ns3/three-gpp-antenna-array-model.h"
#include <fstream>
#include "ns3/three-gpp-spectrum-propagation-loss-model.h"
#include "ns3/net-device.h"
#include "ns3/simple-net-device.h"
#include "ns3/node.h"
#include "ns3/node-container.h"
#include "ns3/mobility-model.h"
#include "ns3/constant-position-mobility-model.h"
#include "ns3/lte-spectrum-value-helper.h"
#include "ns3/channel-condition-model.h"
#include "ns3/three-gpp-propagation-loss-model.h"
Functions
static void ComputeSnr (Ptr< MobilityModel > txMob, Ptr< MobilityModel > rxMob, double txPow, double noiseFigure)
Compute the average SNR.
static void DoBeamforming (Ptr< NetDevice > thisDevice, Ptr< ThreeGppAntennaArrayModel > thisAntenna, Ptr< NetDevice > otherDevice)
Perform the beamforming using the DFT beamforming method.
Variables
static Ptr< ThreeGppPropagationLossModel > m_propagationLossModel
the PropagationLossModel object
static Ptr< ThreeGppSpectrumPropagationLossModel > m_spectrumLossModel
the SpectrumPropagationLossModel object
Function Documentation
ComputeSnr()
static void ComputeSnr (Ptr< MobilityModel > txMob, Ptr< MobilityModel > rxMob, double txPow, double noiseFigure) static
Compute the average SNR.
Parameters
txMob the tx mobility model
rxMob the rx mobility model
txPow the transmitting power in dBm
noiseFigure the noise figure in dB
Definition at line 114 of file three-gpp-channel-example.cc.
References ns3::PropagationLossModel::CalcRxPower(), ns3::SpectrumValue::Copy(), ns3::LteSpectrumValueHelper::CreateNoisePowerSpectralDensity(), ns3::LteSpectrumValueHelper::CreateTxPowerSpectralDensity(), f(), ns3::Time::GetSeconds(), m_propagationLossModel, m_spectrumLossModel, ns3::Simulator::Now(), NS_LOG_DEBUG, and ns3::Sum().
DoBeamforming()
static void DoBeamforming (Ptr< NetDevice > thisDevice, Ptr< ThreeGppAntennaArrayModel > thisAntenna, Ptr< NetDevice > otherDevice) static
Perform the beamforming using the DFT beamforming method.
Parameters
thisDevice the device performing the beamforming
thisAntenna the antenna object associated to thisDevice
otherDevice the device towards which point the beam
Definition at line 60 of file three-gpp-channel-example.cc.
References ns3::ThreeGppAntennaArrayModel::GetElementLocation(), ns3::NetDevice::GetNode(), ns3::ThreeGppAntennaArrayModel::GetNumberOfElements(), ns3::Object::GetObject(), GetPosition(), ns3::ThreeGppAntennaArrayModel::SetBeamformingVector(), and ns3::Angles::theta.
Variable Documentation
m_propagationLossModel
Ptr<ThreeGppPropagationLossModel> m_propagationLossModel static
the PropagationLossModel object
Definition at line 50 of file three-gpp-channel-example.cc.
Referenced by ComputeSnr().
m_spectrumLossModel
Ptr<ThreeGppSpectrumPropagationLossModel> m_spectrumLossModel static
the SpectrumPropagationLossModel object
Definition at line 51 of file three-gpp-channel-example.cc.
Referenced by ComputeSnr().