ns-3: src/applications/examples/three-gpp-http-example.cc File Reference
three-gpp-http-example.cc File Reference
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/internet-module.h"
#include "ns3/point-to-point-module.h"
#include "ns3/applications-module.h"
Functions
void ClientEmbeddedObjectReceived (Ptr< const ThreeGppHttpClient >, Ptr< const Packet > packet)
void ClientMainObjectReceived (Ptr< const ThreeGppHttpClient >, Ptr< const Packet > packet)
void ClientRx (Ptr< const Packet > packet, const Address &address)
void EmbeddedObjectGenerated (uint32_t size)
void MainObjectGenerated (uint32_t size)
void ServerConnectionEstablished (Ptr< const ThreeGppHttpServer >, Ptr< Socket >)
void ServerTx (Ptr< const Packet > packet)
Function Documentation
ClientEmbeddedObjectReceived()
void ClientEmbeddedObjectReceived (Ptr< const ThreeGppHttpClient > , Ptr< const Packet > packet)
Definition at line 80 of file three-gpp-http-example.cc.
References ns3::Packet::Copy(), ns3::ThreeGppHttpHeader::EMBEDDED_OBJECT, ns3::ThreeGppHttpHeader::GetContentLength(), ns3::ThreeGppHttpHeader::GetContentType(), ns3::Packet::GetSize(), NS_LOG_INFO, and ns3::Packet::RemoveHeader().
ClientMainObjectReceived()
void ClientMainObjectReceived (Ptr< const ThreeGppHttpClient > , Ptr< const Packet > packet)
Definition at line 62 of file three-gpp-http-example.cc.
References ns3::Packet::Copy(), ns3::ThreeGppHttpHeader::GetContentLength(), ns3::ThreeGppHttpHeader::GetContentType(), ns3::Packet::GetSize(), ns3::ThreeGppHttpHeader::MAIN_OBJECT, NS_LOG_INFO, and ns3::Packet::RemoveHeader().
ClientRx()
void ClientRx (Ptr< const Packet > packet, const Address & address)
Definition at line 56 of file three-gpp-http-example.cc.
References first::address, ns3::Packet::GetSize(), and NS_LOG_INFO.
EmbeddedObjectGenerated()
void EmbeddedObjectGenerated (uint32_t size)
Definition at line 44 of file three-gpp-http-example.cc.
References NS_LOG_INFO.
MainObjectGenerated()
void MainObjectGenerated (uint32_t size)
Definition at line 38 of file three-gpp-http-example.cc.
References NS_LOG_INFO.
ServerConnectionEstablished()
void ServerConnectionEstablished (Ptr< const ThreeGppHttpServer > , Ptr< Socket >)
Definition at line 32 of file three-gpp-http-example.cc.
References NS_LOG_INFO.
ServerTx()
void ServerTx (Ptr< const Packet > packet)
Definition at line 50 of file three-gpp-http-example.cc.
References ns3::Packet::GetSize(), and NS_LOG_INFO.