ns-3: examples/wireless/wifi-simple-interference.cc File Reference
wifi-simple-interference.cc File Reference
#include "ns3/command-line.h"
#include "ns3/config.h"
#include "ns3/double.h"
#include "ns3/string.h"
#include "ns3/log.h"
#include "ns3/yans-wifi-helper.h"
#include "ns3/ssid.h"
#include "ns3/mobility-helper.h"
#include "ns3/yans-wifi-channel.h"
#include "ns3/mobility-model.h"
#include "ns3/internet-stack-helper.h"
Functions
static void GenerateTraffic (Ptr< Socket > socket, uint32_t pktSize, uint32_t pktCount, Time pktInterval)
static std::string PrintReceivedPacket (Ptr< Socket > socket)
static void ReceivePacket (Ptr< Socket > socket)
Function Documentation
GenerateTraffic()
static void GenerateTraffic (Ptr< Socket > socket, uint32_t pktSize, uint32_t pktCount, Time pktInterval) static
Definition at line 120 of file wifi-simple-interference.cc.
References ns3::Socket::Close(), ns3::Simulator::Schedule(), and ns3::Socket::Send().
PrintReceivedPacket()
static std::string PrintReceivedPacket (Ptr< Socket > socket) inline static
Definition at line 98 of file wifi-simple-interference.cc.
References ns3::InetSocketAddress::ConvertFrom(), ns3::InetSocketAddress::GetIpv4(), ns3::InetSocketAddress::GetPort(), ns3::Socket::GetSockName(), and ns3::Socket::Recv().
Referenced by ReceivePacket().
ReceivePacket()
static void ReceivePacket (Ptr< Socket > socket) static
Definition at line 115 of file wifi-simple-interference.cc.
References NS_LOG_UNCOND, and PrintReceivedPacket().