ns-3: src/wifi/examples/wifi-phy-test.cc File Reference
wifi-phy-test.cc File Reference
#include "ns3/packet.h"
#include "ns3/constant-position-mobility-model.h"
#include "ns3/simulator.h"
#include "ns3/command-line.h"
#include "ns3/flow-id-tag.h"
#include "ns3/yans-wifi-channel.h"
#include "ns3/yans-wifi-phy.h"
#include "ns3/propagation-loss-model.h"
#include "ns3/propagation-delay-model.h"
#include "ns3/nist-error-rate-model.h"
#include "ns3/wifi-psdu.h"
Classes
class CollisionExperiment
CollisionExperiment.
struct CollisionExperiment::Input
Input structure.
struct PsrExperiment::Input
Input structure.
struct CollisionExperiment::Output
Output struture.
struct PsrExperiment::Output
Output structure.
class PsrExperiment
PsrExperiment.
Functions
double CalcPsr (struct PsrExperiment::Output output, struct PsrExperiment::Input input)
static void PrintPsr (int argc, char *argv[])
static void PrintPsrVsCollisionInterval (int argc, char *argv[])
static void PrintPsrVsDistance (int argc, char *argv[])
static void PrintSizeVsRange (int argc, char *argv[])
Function Documentation
CalcPsr()
double CalcPsr (struct PsrExperiment::Output output, struct PsrExperiment::Input input)
Definition at line 343 of file wifi-phy-test.cc.
References PsrExperiment::Input::nPackets, and PsrExperiment::Output::received.
Referenced by PrintPsrVsDistance(), and PrintSizeVsRange().
PrintPsr()
static void PrintPsr (int argc, char * argv[]) static
Definition at line 321 of file wifi-phy-test.cc.
References second::cmd, COMMANDLINE, PsrExperiment::Input::distance, experiment(), PsrExperiment::Input::nPackets, PsrExperiment::Input::packetSize, PsrExperiment::Input::txMode, and PsrExperiment::Input::txPowerLevel.
PrintPsrVsCollisionInterval()
static void PrintPsrVsCollisionInterval (int argc, char * argv[]) static
Definition at line 439 of file wifi-phy-test.cc.
References second::cmd, COMMANDLINE, experiment(), CollisionExperiment::Input::interval, ns3::MicroSeconds(), CollisionExperiment::Input::nPackets, CollisionExperiment::Output::receivedA, CollisionExperiment::Output::receivedB, CollisionExperiment::Input::xA, and CollisionExperiment::Input::xB.
PrintPsrVsDistance()
static void PrintPsrVsDistance (int argc, char * argv[]) static
Definition at line 350 of file wifi-phy-test.cc.
References CalcPsr(), second::cmd, COMMANDLINE, PsrExperiment::Input::distance, experiment(), PsrExperiment::Input::nPackets, PsrExperiment::Input::packetSize, PsrExperiment::Input::txMode, and PsrExperiment::Input::txPowerLevel.
PrintSizeVsRange()
static void PrintSizeVsRange (int argc, char * argv[]) static
Definition at line 402 of file wifi-phy-test.cc.
References CalcPsr(), second::cmd, COMMANDLINE, PsrExperiment::Input::distance, experiment(), PsrExperiment::Input::nPackets, PsrExperiment::Input::packetSize, PsrExperiment::Input::txMode, and PsrExperiment::Input::txPowerLevel.