ns-3: examples/wireless/wifi-spatial-reuse.cc File Reference
wifi-spatial-reuse.cc File Reference
#include "ns3/command-line.h"
#include "ns3/config.h"
#include "ns3/string.h"
#include "ns3/spectrum-wifi-helper.h"
#include "ns3/ssid.h"
#include "ns3/mobility-helper.h"
#include "ns3/application-container.h"
#include "ns3/multi-model-spectrum-channel.h"
#include "ns3/wifi-net-device.h"
#include "ns3/ap-wifi-mac.h"
#include "ns3/he-configuration.h"
#include "ns3/packet-socket-helper.h"
#include "ns3/packet-socket-client.h"
#include "ns3/packet-socket-server.h"
Functions
std::vector< uint32_t > bytesReceived (4)
uint32_t ContextToNodeId (std::string context)
void SocketRx (std::string context, Ptr< const Packet > p, const Address &addr)
Function Documentation
bytesReceived()
std::vector<uint32_t> bytesReceived (4)
Referenced by SocketRx().
ContextToNodeId()
uint32_t ContextToNodeId (std::string context)
Definition at line 83 of file wifi-spatial-reuse.cc.
Referenced by SocketRx().
SocketRx()
void SocketRx (std::string context, Ptr< const Packet > p, const Address & addr)
Definition at line 91 of file wifi-spatial-reuse.cc.
References bytesReceived(), ContextToNodeId(), and ns3::Packet::GetSize().