ns-3: examples/wireless/wifi-hidden-terminal.cc File Reference
wifi-hidden-terminal.cc File Reference
#include "ns3/command-line.h"
#include "ns3/config.h"
#include "ns3/uinteger.h"
#include "ns3/boolean.h"
#include "ns3/string.h"
#include "ns3/yans-wifi-helper.h"
#include "ns3/internet-stack-helper.h"
#include "ns3/ipv4-address-helper.h"
#include "ns3/udp-echo-helper.h"
#include "ns3/yans-wifi-channel.h"
#include "ns3/constant-position-mobility-model.h"
#include "ns3/propagation-loss-model.h"
#include "ns3/propagation-delay-model.h"
#include "ns3/on-off-helper.h"
#include "ns3/flow-monitor-helper.h"
#include "ns3/ipv4-flow-classifier.h"
Functions
void experiment (bool enableCtsRts, std::string wifiManager)
Run single 10 seconds experiment.
Function Documentation
experiment()
void experiment (bool enableCtsRts, std::string wifiManager)
Run single 10 seconds experiment.
Internal:
The slightly different start times and data rates are a workaround for Bug 388 and Bug 912
Internal:
We also use separate UDP applications that will send a single packet before the CBR flows start. This is a workaround for the lack of perfect ARP, see Bug 187
Definition at line 51 of file wifi-hidden-terminal.cc.
References ns3::ApplicationContainer::Add(), ns3::Ipv4AddressHelper::Assign(), ns3::FlowMonitor::CheckForLostPackets(), ns3::YansWifiPhyHelper::Default(), ns3::Ipv4FlowClassifier::FiveTuple::destinationAddress, ns3::Simulator::Destroy(), first::devices, ns3::Ipv4FlowClassifier::FindFlow(), ns3::FlowMonitorHelper::GetClassifier(), ns3::FlowMonitor::GetFlowStats(), ns3::OnOffHelper::Install(), ns3::UdpEchoClientHelper::Install(), ns3::InternetStackHelper::Install(), ns3::FlowMonitorHelper::InstallAll(), first::nodes, ns3::Simulator::Run(), ns3::Seconds(), ns3::OnOffHelper::SetAttribute(), ns3::UdpEchoClientHelper::SetAttribute(), ns3::Ipv4AddressHelper::SetBase(), ns3::YansWifiPhyHelper::SetChannel(), ns3::Config::SetDefault(), ns3::MatrixPropagationLossModel::SetDefaultLoss(), ns3::MatrixPropagationLossModel::SetLoss(), ns3::YansWifiChannel::SetPropagationDelayModel(), ns3::YansWifiChannel::SetPropagationLossModel(), ns3::WifiMacHelper::SetType(), ns3::Ipv4FlowClassifier::FiveTuple::sourceAddress, ns3::Simulator::Stop(), third::wifi, and ns3::WIFI_PHY_STANDARD_80211b.