ns-3: examples/wireless/wifi-ap.cc File Reference
wifi-ap.cc File Reference
#include "ns3/command-line.h"
#include "ns3/config.h"
#include "ns3/boolean.h"
#include "ns3/string.h"
#include "ns3/yans-wifi-helper.h"
#include "ns3/ssid.h"
#include "ns3/mobility-helper.h"
#include "ns3/on-off-helper.h"
#include "ns3/yans-wifi-channel.h"
#include "ns3/mobility-model.h"
#include "ns3/packet-socket-helper.h"
#include "ns3/packet-socket-address.h"
#include "ns3/athstats-helper.h"
Functions
static void AdvancePosition (Ptr< Node > node)
void DevRxTrace (std::string context, Ptr< const Packet > p)
void DevTxTrace (std::string context, Ptr< const Packet > p)
static Vector GetPosition (Ptr< Node > node)
void PhyRxErrorTrace (std::string context, Ptr< const Packet > packet, double snr)
void PhyRxOkTrace (std::string context, Ptr< const Packet > packet, double snr, WifiMode mode, WifiPreamble preamble)
void PhyStateTrace (std::string context, Time start, Time duration, WifiPhyState state)
void PhyTxTrace (std::string context, Ptr< const Packet > packet, WifiMode mode, WifiPreamble preamble, uint8_t txPower)
static void SetPosition (Ptr< Node > node, Vector position)
Variables
static bool g_verbose = true
Function Documentation
AdvancePosition()
static void AdvancePosition (Ptr< Node > node) static
Definition at line 103 of file wifi-ap.cc.
References GetPosition(), ns3::Simulator::Schedule(), ns3::Seconds(), and SetPosition().
DevRxTrace()
void DevRxTrace (std::string context, Ptr< const Packet > p)
Definition at line 48 of file wifi-ap.cc.
References g_verbose.
DevTxTrace()
void DevTxTrace (std::string context, Ptr< const Packet > p)
Definition at line 40 of file wifi-ap.cc.
References g_verbose.
GetPosition()
static Vector GetPosition (Ptr< Node > node) static
Definition at line 96 of file wifi-ap.cc.
References ns3::Object::GetObject(), and third::mobility.
Referenced by AdvancePosition(), NodeStatistics::AdvancePosition(), ns3::LteHelper::AttachToClosestEnb(), DoBeamforming(), ThreeGppSpectrumPropagationLossModelTest::DoBeamforming(), LteEpcE2eDataTestCase::DoRun(), PrintGnuplottableEnbListToFile(), PrintGnuplottableUeListToFile(), and PrintUePosition().
PhyRxErrorTrace()
void PhyRxErrorTrace (std::string context, Ptr< const Packet > packet, double snr)
Definition at line 64 of file wifi-ap.cc.
References g_verbose.
PhyRxOkTrace()
void PhyRxOkTrace (std::string context, Ptr< const Packet > packet, double snr, WifiMode mode, WifiPreamble preamble)
Definition at line 56 of file wifi-ap.cc.
References g_verbose.
PhyStateTrace()
void PhyStateTrace (std::string context, Time start, Time duration, WifiPhyState state)
Definition at line 80 of file wifi-ap.cc.
References aloha::duration, g_verbose, and visualizer.core::start().
PhyTxTrace()
void PhyTxTrace (std::string context, Ptr< const Packet > packet, WifiMode mode, WifiPreamble preamble, uint8_t txPower)
Definition at line 72 of file wifi-ap.cc.
References g_verbose.
SetPosition()
static void SetPosition (Ptr< Node > node, Vector position) static
Definition at line 89 of file wifi-ap.cc.
References ns3::Object::GetObject(), and third::mobility.
Referenced by AdvancePosition(), NodeStatistics::AdvancePosition(), ChainRegressionTest::DoRun(), PhyConnectivityTest::DoRun(), LteX2HandoverMeasuresTestCase::DoRun(), AodvExample::InstallApplications(), and UanExperiment::SetupPositions().
Variable Documentation
g_verbose
bool g_verbose = true static
Definition at line 37 of file wifi-ap.cc.
Referenced by DevRxTrace(), DevTxTrace(), PhyRxErrorTrace(), PhyRxOkTrace(), PhyStateTrace(), and PhyTxTrace().