ns-3: src/wifi/examples/wifi-manager-example.cc File Reference
wifi-manager-example.cc File Reference
#include "ns3/log.h"
#include "ns3/config.h"
#include "ns3/uinteger.h"
#include "ns3/boolean.h"
#include "ns3/double.h"
#include "ns3/gnuplot.h"
#include "ns3/command-line.h"
#include "ns3/yans-wifi-helper.h"
#include "ns3/ssid.h"
#include "ns3/propagation-loss-model.h"
#include "ns3/propagation-delay-model.h"
#include "ns3/rng-seed-manager.h"
#include "ns3/mobility-helper.h"
#include "ns3/wifi-net-device.h"
#include "ns3/packet-socket-helper.h"
#include "ns3/packet-socket-client.h"
#include "ns3/packet-socket-server.h"
#include "ns3/ht-configuration.h"
#include "ns3/he-configuration.h"
Classes
struct StandardInfo
StandardInfo structure.
struct Step
Step structure.
Functions
void ChangeSignalAndReportRate (Ptr< FixedRssLossModel > rssModel, struct Step step, double rss, Gnuplot2dDataset &rateDataset, Gnuplot2dDataset &actualDataset)
void PacketRx (Ptr< const Packet > pkt, const Address &addr)
void RateChange (uint64_t oldVal, uint64_t newVal)
Variables
double g_intervalBytes = 0
uint64_t g_intervalRate = 0
const double NOISE_DBM_Hz = -174.0
double noiseDbm = NOISE_DBM_Hz
Function Documentation
ChangeSignalAndReportRate()
void ChangeSignalAndReportRate (Ptr< FixedRssLossModel > rssModel, struct Step step, double rss, Gnuplot2dDataset & rateDataset, Gnuplot2dDataset & actualDataset)
Definition at line 132 of file wifi-manager-example.cc.
References ns3::Gnuplot2dDataset::Add(), g_intervalBytes, g_intervalRate, noiseDbm, ns3::Simulator::Now(), NS_LOG_FUNCTION, NS_LOG_INFO, ns3::Time::S, ns3::Simulator::Schedule(), ns3::Seconds(), ns3::FixedRssLossModel::SetRss(), Step::stepSize, and Step::stepTime.
PacketRx()
void PacketRx (Ptr< const Packet > pkt, const Address & addr)
Definition at line 72 of file wifi-manager-example.cc.
References g_intervalBytes, and ns3::Packet::GetSize().
RateChange()
void RateChange (uint64_t oldVal, uint64_t newVal)
Definition at line 78 of file wifi-manager-example.cc.
References g_intervalRate, and NS_LOG_DEBUG.
Variable Documentation
g_intervalBytes
double g_intervalBytes = 0
Definition at line 68 of file wifi-manager-example.cc.
Referenced by ChangeSignalAndReportRate(), and PacketRx().
g_intervalRate
uint64_t g_intervalRate = 0
Definition at line 69 of file wifi-manager-example.cc.
Referenced by ChangeSignalAndReportRate(), and RateChange().
NOISE_DBM_Hz
const double NOISE_DBM_Hz = -174.0
Definition at line 65 of file wifi-manager-example.cc.
noiseDbm
double noiseDbm = NOISE_DBM_Hz
Definition at line 66 of file wifi-manager-example.cc.
Referenced by ChangeSignalAndReportRate().