ns-3: src/wifi/examples/wifi-phy-configuration.cc File Reference
wifi-phy-configuration.cc File Reference
#include "ns3/log.h"
#include "ns3/command-line.h"
#include "ns3/config-store.h"
#include "ns3/config.h"
#include "ns3/boolean.h"
#include "ns3/uinteger.h"
#include "ns3/string.h"
#include "ns3/ssid.h"
#include "ns3/yans-wifi-phy.h"
#include "ns3/yans-wifi-helper.h"
#include "ns3/wifi-net-device.h"
Functions
Ptr< YansWifiPhy > GetYansWifiPhyPtr (const NetDeviceContainer &nc)
void PrintAttributesIfEnabled (bool enabled)
Function Documentation
GetYansWifiPhyPtr()
Ptr<YansWifiPhy> GetYansWifiPhyPtr (const NetDeviceContainer & nc)
Definition at line 43 of file wifi-phy-configuration.cc.
References ns3::NetDeviceContainer::Get(), ns3::Object::GetObject(), and ns3::WifiNetDevice::GetPhy().
PrintAttributesIfEnabled()
void PrintAttributesIfEnabled (bool enabled)
Definition at line 51 of file wifi-phy-configuration.cc.
References ns3::ConfigStore::ConfigureAttributes().