ns-3: examples/wireless/wifi-multirate.cc File Reference
wifi-multirate.cc File Reference
#include "ns3/gnuplot.h"
#include "ns3/command-line.h"
#include "ns3/config.h"
#include "ns3/uinteger.h"
#include "ns3/boolean.h"
#include "ns3/double.h"
#include "ns3/string.h"
#include "ns3/log.h"
#include "ns3/yans-wifi-helper.h"
#include "ns3/mobility-helper.h"
#include "ns3/internet-stack-helper.h"
#include "ns3/ipv4-address-helper.h"
#include "ns3/on-off-helper.h"
#include "ns3/yans-wifi-channel.h"
#include "ns3/mobility-model.h"
#include "ns3/olsr-helper.h"
#include "ns3/ipv4-static-routing-helper.h"
#include "ns3/ipv4-list-routing-helper.h"
#include "ns3/rectangle.h"
#include "ns3/flow-monitor-helper.h"
Classes
class Experiment
Helper class for UAN CW MAC example.
Functions
static Vector GetPosition (Ptr< Node > node)
static std::string PrintPosition (Ptr< Node > client, Ptr< Node > server)
Function Documentation
GetPosition()
static Vector GetPosition (Ptr< Node > node) inline static
Definition at line 341 of file wifi-multirate.cc.
References ns3::Object::GetObject(), and third::mobility.
Referenced by PrintPosition().
PrintPosition()
static std::string PrintPosition (Ptr< Node > client, Ptr< Node > server) inline static
Definition at line 348 of file wifi-multirate.cc.
References ns3::Ipv4::GetAddress(), ns3::Node::GetDevice(), ns3::Ipv4InterfaceAddress::GetLocal(), ns3::Object::GetObject(), and GetPosition().
Referenced by Experiment::ApplicationSetup().