ns-3: examples/wireless/wifi-pcf.cc File Reference
wifi-pcf.cc File Reference
#include "ns3/log.h"
#include "ns3/config.h"
#include "ns3/command-line.h"
#include "ns3/uinteger.h"
#include "ns3/boolean.h"
#include "ns3/string.h"
#include "ns3/yans-wifi-helper.h"
#include "ns3/mobility-helper.h"
#include "ns3/internet-stack-helper.h"
#include "ns3/ipv4-address-helper.h"
#include "ns3/packet-sink-helper.h"
#include "ns3/on-off-helper.h"
#include "ns3/packet-sink.h"
#include "ns3/ssid.h"
#include "ns3/wifi-mac-header.h"
Functions
void TxCallback (std::string context, Ptr< const Packet > p, double txPowerW)
Variables
uint64_t m_countBeacon
uint64_t m_countCfEnd
uint64_t m_countCfEndAck
uint64_t m_countCfPoll
uint64_t m_countCfPollAck
uint64_t m_countCfPollData
uint64_t m_countCfPollDataAck
uint64_t m_countData
uint64_t m_countDataNull
Function Documentation
TxCallback()
void TxCallback (std::string context, Ptr< const Packet > p, double txPowerW)
Definition at line 75 of file wifi-pcf.cc.
References ns3::WifiMacHeader::HasData(), ns3::WifiMacHeader::IsBeacon(), ns3::WifiMacHeader::IsCfAck(), ns3::WifiMacHeader::IsCfEnd(), ns3::WifiMacHeader::IsCfPoll(), ns3::WifiMacHeader::IsData(), m_countBeacon, m_countCfEnd, m_countCfEndAck, m_countCfPoll, m_countCfPollAck, m_countCfPollData, m_countCfPollDataAck, m_countData, m_countDataNull, and ns3::Packet::PeekHeader().
Variable Documentation
m_countBeacon
uint64_t m_countBeacon
Definition at line 65 of file wifi-pcf.cc.
Referenced by TxCallback().
m_countCfEnd
uint64_t m_countCfEnd
Definition at line 70 of file wifi-pcf.cc.
Referenced by TxCallback().
m_countCfEndAck
uint64_t m_countCfEndAck
Definition at line 71 of file wifi-pcf.cc.
Referenced by TxCallback().
m_countCfPoll
uint64_t m_countCfPoll
Definition at line 66 of file wifi-pcf.cc.
Referenced by TxCallback().
m_countCfPollAck
uint64_t m_countCfPollAck
Definition at line 67 of file wifi-pcf.cc.
Referenced by TxCallback().
m_countCfPollData
uint64_t m_countCfPollData
Definition at line 68 of file wifi-pcf.cc.
Referenced by TxCallback().
m_countCfPollDataAck
uint64_t m_countCfPollDataAck
Definition at line 69 of file wifi-pcf.cc.
Referenced by TxCallback().
m_countData
uint64_t m_countData
Definition at line 73 of file wifi-pcf.cc.
Referenced by TxCallback().
m_countDataNull
uint64_t m_countDataNull
Definition at line 72 of file wifi-pcf.cc.
Referenced by TxCallback().