ns-3: examples/wireless/wifi-sleep.cc File Reference
wifi-sleep.cc File Reference
#include "ns3/command-line.h"
#include "ns3/config.h"
#include "ns3/string.h"
#include "ns3/log.h"
#include "ns3/yans-wifi-helper.h"
#include "ns3/mobility-helper.h"
#include "ns3/ipv4-address-helper.h"
#include "ns3/yans-wifi-channel.h"
#include "ns3/mobility-model.h"
#include "ns3/internet-stack-helper.h"
#include "ns3/on-off-helper.h"
#include "ns3/packet-sink-helper.h"
#include "ns3/basic-energy-source-helper.h"
#include "ns3/wifi-radio-energy-model-helper.h"
#include "ns3/wifi-utils.h"
#include "ns3/wifi-net-device.h"
Functions
template<int node>
void PhyStateTrace (std::string context, Time start, Time duration, WifiPhyState state)
template<int node>
void RemainingEnergyTrace (double oldValue, double newValue)
Function Documentation
PhyStateTrace()
template<int node> void PhyStateTrace (std::string context, Time start, Time duration, WifiPhyState state)
Definition at line 81 of file wifi-sleep.cc.
References aloha::duration, f(), ns3::Time::GetSeconds(), ns3::Simulator::Now(), and visualizer.core::start().
RemainingEnergyTrace()
template<int node> void RemainingEnergyTrace (double oldValue, double newValue)
Definition at line 70 of file wifi-sleep.cc.
References f(), ns3::Time::GetSeconds(), and ns3::Simulator::Now().